### ISSUE TITLE
MISRA-C Do not use feature from stdarg.h

### ISSUE THREAD

**Issue by ceolin** [zephyrproject-rtos/zephyr#10012]
There a many undefined behaviours associated with features of stdarg.h, e.g:

- va_end not being used prior to end of a function in which va_start was used;
- The type of an argument is not compatible with the type specified to va_arg.

In Zephyr's kernel with have just few problems regarding it. In `k_thread_access_grant()` and `z_syscall_verify_msg()`.

part of #9552

**Comment by ceolin** [comment]
rule 17.1

**Comment by andrewboie** [comment]
we could fix this for 1.14
hold my beer

**Comment by andrewboie** [comment]
k_thread_access_grant already fixed by Adithya, #13692 addresses the other issue
