### ISSUE TITLE
Porting Modbus Library: Need some guidance

### ISSUE THREAD

**Issue by Josh0027** [zephyrproject-rtos/zephyr#10022]
Good day! I am just starting to be active on this project and after my last botched PR, I need some advice and direction.
I am attempting to port this ModBus Library to Zephyr and although I am still learning on the steps, I can't seem to successfully compile it or link it. This is the link to the original library: 

https://github.com/Jacajack/liblightmodbus

I first built the library by itself and after verification I proceeded to look for a template code.

I have found and build the /samples/application_development/external_lib and flashed it to my Nucleo board to verify it. Afterwards I used this as my base and cloned the Modbus Library.

First problem is that the external_lib template uses make but the Modbus Library uses cmake first before make. 

Second problem is after I disabled the "ExternalProject_Add" and proceeded in linking the prebuilt library. I suddenly got "liblightmodbus/build/liblightmodbus.a: error adding symbols: File format not recognized".

I'm still in the process of learning but right now I need any help on where I can identify where my mistake is. Any advice is appreciated.

Here is my most recent log when I just attempted to link the prebuilt library.

Update: My brain is dead. Forgot that I can attach a log file. I have posted the log flies from the original library and ported one.

**Comment by Josh0027** [comment]
Here is the updated log after I ported the library into Zephyr. Please advise me where I have made the mistake. 

[stdout.log](https://github.com/zephyrproject-rtos/zephyr/files/2388720/stdout.log)

[CMakeLists.txt](https://github.com/zephyrproject-rtos/zephyr/files/2388723/CMakeLists.txt)

**Comment by Josh0027** [comment]
Second scenario is I force the cmake to generate Unix Makefiles but it gives ma an error.  It looks like mixing -GNInja and -GUnix Makefiles is not good. Maybe this is also the reason I am seeing my first issue above?

Any ideas are welcome.

[stdout2.log](https://github.com/zephyrproject-rtos/zephyr/files/2389600/stdout2.log)

[CMakeLists2.txt](https://github.com/zephyrproject-rtos/zephyr/files/2389601/CMakeLists2.txt)

**Comment by firmwareguru** [comment]
@Josh0027 Did you get anywhere with this, and where is the repository you've been working in?

**Comment by parthitce** [comment]
@firmwareguru @Josh0027 Although we have modbus RTU on it's way for in-tree Zephyr (https://github.com/zephyrproject-rtos/zephyr/pull/26516), I did tried to use liblightmodbus for my personal use case. Adding my attempts just for the completion of this thread.

Am able to successfully compile and use the sample in zephyr.

Changes in liblightmodbus is here: https://github.com/linumiz/liblightmodbus
Changes with example in zephyr is here: https://github.com/linumiz/zephyr/tree/liblightmodbus
