### ISSUE TITLE
MISRA C - Document Zephyr's code guideline based on MISRA C 2012

### ISSUE THREAD

**Issue by ceolin** [zephyrproject-rtos/zephyr#10030]
We have to document our code guideline based on MISRA-C 2012 to help newcomer developers to contribute on Zephyr. Also this is important not only because of MISRA-C rules but because of patterns that we want to be followed across the project.

This document must be clear enough to make people no introduce MISRA-C violations.

part of #9552

**Comment by d3zd3z** [comment]
Have we gotten any clarity as to how much we can document MISRA-C compliance while still complying with the license of the MISRA-C spec itself?

**Comment by ceolin** [comment]
> Have we gotten any clarity as to how much we can document MISRA-C compliance while still complying with the license of the MISRA-C spec itself?

You mean document deviations and still be compliant ? I don't think there is a number. As far as I know you can deviate from required rules as much as you can if they are properly justified. The only thing that is not allowed is deviate from mandatory rules.

In informal talk with auditors and static analysis tool owners they told me that usually projects only select a small set of rules.

**Comment by dbkinder** [comment]
I read the question asking how we document the MISRA-C rules so it's all contained in our project's publically available coding guideline documentation without infringing on the MISRA-C licensing rules.

**Comment by d3zd3z** [comment]
@dbkinder that is what I was trying to say.
