### ISSUE TITLE
Inversed logic in fade_led sample for nRF boards

### ISSUE THREAD

**Issue by JoeHut** [zephyrproject-rtos/zephyr#10038]
According to the Readme the LED will start from dark and increase its brightness gradually before fading to darkness again. On the nrf52840_pca10056 this logic is inversed. The LED starts bright and becomes darker. There is currently no functionality in the pwm_nrf5_sw driver to inverse the polarity so either this functionality has to be added to the driver or a switch to the pwm_nrfx driver has to be made.

**Comment by anangl** [comment]
Fixed by #13059.
