### ISSUE TITLE
Logger thread spins forever if there is no backend

### ISSUE THREAD

**Issue by aescolar** [zephyrproject-rtos/zephyr#10054]
A configuration with no backend registered will have the logger thread spin forever.

Instead having an assert at the start of the thread would be sensible, something like this: https://github.com/zephyrproject-rtos/zephyr/commit/fb0e038c75565b40550bcdf495cd53570a581b0f 

As of now there is 2 Xtensa tests in CI with this issue.

**Comment by nordic-krch** [comment]
In case no backends are present in the system we can add assert since in that case it's better to disable logger. What are the issues with xtensa tests? Will it fix it?

**Comment by aescolar** [comment]
> In case no backends are present in the system we can add assert since in that case it's better to disable logger.
 
Agreed.
Having an assert would be also a nice way of pointing to the reason of the (configured in) logger not working (there was no backends for it).

> What are the issues with xtensa tests?

That the assert will trigger for them, (assuming they haven't been fixed yet) and they will fail in CI.
Meaning, the assert will work as expected.

> Will it fix it?

An assert does not fix things. It fails noisily when the error condition happens.

**Comment by nordic-krch** [comment]
added assert in #10513, if CI fails i'll go from there.
