### ISSUE TITLE
threads: Need to store thread name for debugging purposes 

### ISSUE THREAD

**Issue by pfalcon** [zephyrproject-rtos/zephyr#10165]
I don't know how this was overlooked for so long, but if corresponding debugging options are enabled, we should store a thread name, just the same as with a corresponding option enabled (CONFIG_THREAD_STACK_INFO), we store stack size info.

This can be see as a follow up to https://github.com/zephyrproject-rtos/zephyr/pull/10044 - with k_call_stacks_analyze() gone, which itself worked around lack of thread names by dealing only with "well known" threads, now it's not easy (if possible at all) to get even the info it provided out, far less good thread info for all threads.

In particular, patches like https://github.com/zephyrproject-rtos/zephyr/commit/0fb9ea03043551c66e6f0ec14c4ef9a001255d7d rather goof it, there it would print something like:

~~~
HCI [info for thread1 which has nothing to do with HCI]
HCI [info for thread2 which has nothing to do with HCI]
HCI [info for thread3 which has nothing to do with HCI]
...
HCI [finally, some thread related to HCI, but user has no idea that it is, because there's no clear identification for a thread at all]
...
~~~

**Comment by nashif** [comment]
there is a wip PR https://github.com/zephyrproject-rtos/zephyr/pull/9394

**Comment by pfalcon** [comment]
> there is a wip PR #9394

Ah, cool, thanks for working on this. My motion was to close this ticket then, but maybe you'd want to use it as "Fixed: " reference there, so leaving as is, but feel free to close otherwise.
