### ISSUE TITLE
net: wrong dst mac address in echo reply

### ISSUE THREAD

**Issue by rmstoi** [zephyrproject-rtos/zephyr#10188]
If echo request is sent twice to Zephyr with same IP address but with different MAC address, the second echo reply sent by Zephyr has wrong (previous) destination MAC address.

[echo-reply-wrong-mac.pcap.gz](https://github.com/zephyrproject-rtos/zephyr/files/2411350/echo-reply-wrong-mac.pcap.gz)

**Comment by jukkar** [comment]
The ARP cache is used when sending the reply packet, if the cache contains the old address, then that is used.  Usually the host sends gratuitous ARP if its MAC address changes. Currently we do not handle these gratuitous ARP messages, or expire the addresses in ARP cache. So there is definitely some improvements needed here.

**Comment by jukkar** [comment]
@rmstoi Is this still an issue?

**Comment by rmstoi** [comment]
@jukkar This is still an issue. I compared this case to Linux and Linux sends echo response with correct (updated) MAC.

**Comment by rmstoi** [comment]
pcap from running this test with Linux DUT

[linux-echo-reply-correct-mac.pcapng.gz](https://github.com/zephyrproject-rtos/zephyr/files/2904598/linux-echo-reply-correct-mac.pcapng.gz)
