### ISSUE TITLE
GPIO callback disable has no effect due to _gpio_fire_callbacks

### ISSUE THREAD

**Issue by pdunaj** [zephyrproject-rtos/zephyr#10186]
Function `_gpio_fire_callbacks` triggers callbacks for pins present in mask passed as an argument.

This infrastructure will not work correctly when application disables callbacks for multiple pins from a currently handled callback.

E.g.
4 pin callbacks are registered (A...D). Let's assume 2 are fired (A and B) at the same time.
Interrupt handler is triggered in driver code. It sets bits corresponding for these two pins in the variable passed as an argument to `_gpio_fire_callbacks` and call the function.
As there are two pins callback will be triggered twice (once for pin A and second time for pin B).
The application gets first call (for pin A). In this call the application callback code disables callbacks for  all pins A...D. Application expects no more callbacks for any of the pins.
As `_gpio_fire_callbacks` is still in the loop, after first callback is done, it will trigger second callback for pin B. This happens even-though this callback was disabled.

**Comment by pdunaj** [comment]
We are still hit by this...

**Comment by pdunaj** [comment]
Fixing this is not trivial really. We changed the application to have one callback for all pins we use. This should do the trick.
I still believe it should be fixed but we will not be affected anymore. If somebody else is hit by that they can do what we did.

**Comment by pabigot** [comment]
Perhaps I'm missing something, but I'm surprised this even appears to work.  It's entirely reasonable to disable future callbacks from within the callback's handler; I depend on this in some situations where I have to detect rising and falling transitions on a signal that uses a level trigger (applies to most sensors where an bus transaction is required to read an observation and clear the interrupt).

However  `_gpio_fire_callbacks` iterates over the callback list using the `SYS_SLIST_FOR_EACH_CONTAINER` wrapper, which explicitly isn't safe for the condition where the node being visited is removed from the list while it's being visited.

That could be addressed by using `SYS_SLIST_FOR_EACH_CONTAINER_SAFE`, but the use case in this issue basically empties the list while visiting the first entry, invalidating every pointer that you might have kept a handle on.

One way to deal with that is to mark within callback record itself whether it's participating in a list, and skip invoking the handler if it's not.  Which won't work if a previous callback unregistered the record but re-registered it on another list: suddenly you're iterating over a completely different sequence.

So my tentative resolution would be twofold: (1) switch to the safe list iterator, and (2) document that within a callback the only GPIO callback structure you're allowed to unregister is the one you're running in.
