### ISSUE TITLE
The new shell can only be compiled on boards with SERIAL but it does not set the dependency in its Kconfig

### ISSUE THREAD

**Issue by aescolar** [zephyrproject-rtos/zephyr#10190]
The new shell (CONSOLE_SHELL) can only be compiled on boards with SERIAL but it does not set the dependency in its Kconfig options

Related to #10127

**Comment by jukkar** [comment]
As discussed this in #10127, the shell should select CONFIG_SERIAL automatically so that it is not needed to be placed in application configuration file.

**Comment by aescolar** [comment]
CC @ulfalizer

**Comment by jarz-nordic** [comment]
@aescolar @jukkar 
Shell cannot simply select CONFIG_SERIAL. In future when we will have more backends I can imagine that one wants to have only shell on RTT or BT. Hardcoded SERIAL selection makes limited sense in such case.

I will add an option in shell's Kconfig like ACTIVE_BACKEND, when user will have possiblity to select SERIAL or any other...
