### ISSUE TITLE
Shell should accept either CR or LF as line delimiter

### ISSUE THREAD

**Issue by aescolar** [zephyrproject-rtos/zephyr#10207]
Currently the shell only accepts CR (\r) as the marker for end of line.
But different terminals/terminal configurations will insert a LF (canonical end of line), and some terminal driver configurations (the canonical one with ICRNL (default)) will replace CR with LF.
Moreover Unix terminals can also be configured with IGNCR (ignore CR), which means the character is dropped from the stream (so there is no way to force it in, even by pressing Ctrl+M)

**Comment by jarz-nordic** [comment]
Hi,
Currently shell accepts EOL marker defined by macro: 
`SHELL_DEFINE(uart_shell, "uart:~$ ", &shell_transport_uart, '\r', 10);` In this case `'\r'`

Is it requested that shell shall react on both at the same time?

**Comment by aescolar** [comment]
> Is it requested that shell shall react on both at the same time?

**Either** of them would seem logical to me.

**Comment by jarz-nordic** [comment]
Ok, I will rework that.
Please let me know if it is possible that some terminal will send both at the same time?
For example: `\r\n` or `\n\r` ?

**Comment by aescolar** [comment]
> Shell needs to distinguish..

Does it? I mean, wouldn't the only result of not detecting it be an extra prompt displayed?

**Comment by jarz-nordic** [comment]
Yes.
I would like to avoid extra empty prompt display.
