### ISSUE TITLE
sys_reboot for native posix missing

### ISSUE THREAD

**Issue by vsaw** [zephyrproject-rtos/zephyr#10240]
`sys_reboot` is currently not implemented for native posix.

See also https://github.com/zephyrproject-rtos/zephyr/issues/6044

**Comment by vsaw** [comment]
Hi @aescolar, my application has [`CONFIG_REBOOT`](https://docs.zephyrproject.org/latest/reference/kconfig/CONFIG_REBOOT.html?highlight=reboot#cmdoption-arg-config-reboot) enabled and uses it on the NRF board. For the Posix Native target, the compilation fails because the Posix Arch does not implement the following function

```C
void sys_arch_reboot(int type);
void sys_clock_disable(void);
```

As a quick work-around I implemented mocks to make the code build. If there is interest I can upstream my mock implementation.

I have not looked into a "more useful" implementation of reboot on Posix.

**Comment by aescolar** [comment]
> If there is interest I can upstream my ..

You are welcome to.
