### ISSUE TITLE
Clean up remaining SPI_DW_ defines in soc.h

### ISSUE THREAD

**Issue by MaureenHelm** [zephyrproject-rtos/zephyr#10268]
Some of the SPI_DW defines were removed in #10249 when the designware spi driver was converted to get base addresses and irq numbers from device tree. There are a few defines remaining for int masks and flags that also need to be removed, but they probably require modifications to the spi and/or interrupt controller bindings for x86 and arc.

**Comment by nashif** [comment]
done already, can't find any SPI_DW defines in any soc.h files
