### ISSUE TITLE
doc build failing - no module named 'colorama'

### ISSUE THREAD

**Issue by dbkinder** [zephyrproject-rtos/zephyr#10272]
Documentation build (``make htmldocs``) is failing with the unexpected warning:
```
WARNING: autodoc: failed to import module 'west.runners.core' the following exception was raised:
No module named 'colorama'
```

Looks to be while processing the ``west`` APIs via Sphinx's autodoc extension.  @mbolivar Is ``colorama`` now required for doc generation?

**Comment by dbkinder** [comment]
... and the answer is yes.  We need to have ``colorama`` package installed to build documentation now.  Installing it with ``pip3 install --user colorama`` and doc build succeeds.

**Comment by mbolivar** [comment]
> @mbolivar Is `colorama` now required for doc generation?

Yup, as you already saw, the new dependency was added to scripts/requirements.txt today.
