### ISSUE TITLE
SystemView overflow event

### ISSUE THREAD

**Issue by MarekPieta** [zephyrproject-rtos/zephyr#10329]
When we enable SystemView, it always records events data to buffer since system starts. It may often cause overflow event (especially for bigger systems). 

I think we could add additional option in KConfig to let users decide if they want to record events since system start or since host application connects. Thanks to this we wouldn't have to allocate big buffer to store all the data collected by SystemView since system start.
This could be implemented easily - for example function SEGGER_SYSVIEW_Start may be called conditionally based on boolean in KConfig.

**Comment by nashif** [comment]
@MarekPieta do you want to propose a patch for this?

**Comment by nashif** [comment]
fixed in #12149
