### ISSUE TITLE
Publish PDF with the release doc build

### ISSUE THREAD

**Issue by dbkinder** [zephyrproject-rtos/zephyr#10324]
Currently, we do a daily doc build to publish documentation for the project's master branch to the https://docs.zephyrproject.org site.  PR #9557 enabled PDF generation of the Zephyr documentation, but generating and publishing a PDF has not been integrated with our daily doc build (or release doc build) processes.

We should not add PDF doc generation to the CI doc build testing done for every PR however.

**Comment by str4t0m** [comment]
Since #37088 PDF docs are now built in CI and published. So I think this issue could be closed?

**Comment by nashif** [comment]
done already
