### ISSUE TITLE
dts/stm32: Populate clocks for i2c nodes and use CONFIG_ #defines for instances configuration

### ISSUE THREAD

**Issue by erwango** [zephyrproject-rtos/zephyr#10435]
"clocks" property is missing in stm32 i2c nodes, which prevents using #define CONFIG_xxx for clock related code configuration in i2c instances:
```
static const struct i2c_stm32_config i2c_stm32_cfg_1 = {
	.i2c = (I2C_TypeDef *)CONFIG_I2C_1_BASE_ADDRESS,
	.pclken = {
		.enr = LL_APB1_GRP1_PERIPH_I2C1,
		.bus = STM32_CLOCK_BUS_APB1,
	},
```
Rather than using the hardcoded #defines LL_APB1_GRP1_P_XXX and STM32_CLOCK_BUS_XXX,
instance configuration code, should rather use the equivalent coming from dts #define generation.

Cf example in `drivers/can/stm32_can.c`:
```
static const struct can_stm32_config can_stm32_cfg_1 = {
        [... ]
	.pclken = {
		.enr = CONFIG_CAN_1_CLOCK_BITS,
		.bus = CONFIG_CAN_1_CLOCK_BUS,
	},
	.config_irq = config_can_1_irq
};
```

This should be done in 3 steps:
-Populate "clocks" property in all i2c nodes in stm32 dtsi files
-Populate the CONFIG_ <> generated defined in stm32 fixup files
-Update stm32 i2c instanceiation code to use CONFIG_ symbols

**Comment by avisconti** [comment]
I have done it for I2S in stm32f4 (#9034 ) and it can be taken as reference once that it is approved
by @erwango.
