### ISSUE TITLE
drivers/modem/modem_receiver.c needs LOG_MODULE_REGISTER(mdm_receiver)

### ISSUE THREAD

**Issue by sdrsdr** [zephyrproject-rtos/zephyr#10518]
As can be seen at 

https://github.com/zephyrproject-rtos/zephyr/blob/05b854c168ffc29e7164e6bc764bb05aa5f00660/drivers/modem/modem_receiver.c#L21

the  log system in the file is not fully initialized so you get compile time errors

**Comment by mike-scott** [comment]
Ah nm, it's been moved.  Just has a bug.

**Comment by sdrsdr** [comment]
The commit from @nashif  will resolve it .. quick work guys :+1:
