### ISSUE TITLE
[Coverity CID :188749]Null pointer dereferences in /subsys/bluetooth/controller/ll_sw/ctrl.c

### ISSUE THREAD

**Issue by mandarcthorat1** [zephyrproject-rtos/zephyr#10577]
Static code scan issues seen in File: /subsys/bluetooth/controller/ll_sw/ctrl.c
 Category: Null pointer dereferences
 Function: ll_rx_mem_release
 Component: Bluetooth
 CID: 188749
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by carlescufi** [comment]
Closed as false positive in Coverity.
