### ISSUE TITLE
[Coverity CID :188748]Memory - corruptions in /subsys/bluetooth/host/gatt.c

### ISSUE THREAD

**Issue by mandarcthorat1** [zephyrproject-rtos/zephyr#10578]
Static code scan issues seen in File: /subsys/bluetooth/host/gatt.c
 Category: Memory - corruptions
 Function: bt_gatt_notify_cb
 Component: Bluetooth
 CID: 188748
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by jhedberg** [comment]
Marked as false positive in Coverity
