### ISSUE TITLE
[Coverity CID :188750]Memory - illegal accesses in /subsys/bluetooth/shell/bt.c

### ISSUE THREAD

**Issue by mandarcthorat1** [zephyrproject-rtos/zephyr#10576]
Static code scan issues seen in File: /subsys/bluetooth/shell/bt.c
 Category: Memory - illegal accesses
 Function: cmd_advertise
 Component: Bluetooth
 CID: 188750
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by nniranjhana** [comment]
This is also fixed via #10738
