### ISSUE TITLE
[Coverity CID :188747]Security best practices violations in /subsys/shell/shell.c

### ISSUE THREAD

**Issue by mandarcthorat1** [zephyrproject-rtos/zephyr#10579]
Static code scan issues seen in File: /subsys/shell/shell.c
 Category: Security best practices violations
 Function: shell_execute_cmd
 Component: Other
 CID: 188747
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by nashif** [comment]
ignored als false positive in coverity
