### ISSUE TITLE
[Coverity CID :188752]Security best practices violations in /subsys/shell/shell.c

### ISSUE THREAD

**Issue by mandarcthorat1** [zephyrproject-rtos/zephyr#10575]
Static code scan issues seen in File: /subsys/shell/shell.c
 Category: Security best practices violations
 Function: help_options_print
 Component: Other
 CID: 188752
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by nashif** [comment]
file refactored, does not apply anymore.
