### ISSUE TITLE
[Coverity CID :188743]Program hangs in /tests/posix/common/src/posix_rwlock.c

### ISSUE THREAD

**Issue by mandarcthorat1** [zephyrproject-rtos/zephyr#10582]
Static code scan issues seen in File: /tests/posix/common/src/posix_rwlock.c
 Category: Program hangs
 Function: test_posix_rw_lock
 Component: Tests
 CID: 188743
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by nniranjhana** [comment]
False positive, test requires to sleep while holding lock, to verify other threads cannot acquire lock. This is not a mistake, this is intended implementation for the test.
