### ISSUE TITLE
[Coverity CID :188732]Integer handling issues in /subsys/net/lib/http/http_server.c

### ISSUE THREAD

**Issue by mandarcthorat1** [zephyrproject-rtos/zephyr#10591]
Static code scan issues seen in File: /subsys/net/lib/http/http_server.c
 Category: Integer handling issues
 Function: _http_change_state
 Component: Networking
 CID: 188732
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by jukkar** [comment]
False positive.
