### ISSUE TITLE
[Zephyr] Firmware upgrade through UART [Nordic 52840 - pca 10056 Board]

### ISSUE THREAD

**Issue by parinpatel** [zephyrproject-rtos/zephyr#10619]
Hi all,

[NRF52840 - pca10056]

I used the mcuboot for bootloader 
and I wanted to firmware upgrade using UART interface 
I also found that there is one flag "CONFIG_MCUBOOT_SERIAL" which is used for firmware upgrade through UART but after enable this , 
 I read the following document,
https://docs.zephyrproject.org/latest/samples/subsys/mgmt/mcumgr/smp_svr/README.html

But I unable to find out the steps for firmware flash using UART 

Please help me to solve this issue.

**Comment by parinpatel** [comment]
Currently I found some command from below link 

https://github.com/zephyrproject-rtos/zephyr/issues/9509

Is it correct?

**Comment by carlescufi** [comment]
@parinpatel can you comment on #9509 instead?

**Comment by parinpatel** [comment]
Ok
