### ISSUE TITLE
qustion: How to ping host target from Zephyr?

### ISSUE THREAD

**Issue by qianfan-Zhao** [zephyrproject-rtos/zephyr#10652]
Hi, I want ping a target device from Zephyr, and check if the target alive. But the API net_icmpv4_send_echo_request is declared in subsys/net/ip, not exported for us. Is there has a easy way to do that?

**Comment by qianfan-Zhao** [comment]
My personal idea is based on PR #10665 and PR #10660 .

```
static bool network_check(int arg)
{
	char cmd[64] = "net ping " CONFIG_NET_CONFIG_PEER_IPV4_ADDR;

	return !shell_execute_cmd(NULL, cmd);
}
```

This maybe not the best way, but it just works.
If we can export some ICMP APIs to public, or implement SOCK_RAW?

**Comment by jukkar** [comment]
Is there need to do anything here? I thought after IRC conversation that there is some progress when working with `shell_execute_cmd()`.
