### ISSUE TITLE
tests/net/ieee802154/crypto does not work as expected

### ISSUE THREAD

**Issue by nniranjhana** [zephyrproject-rtos/zephyr#10657]
The test in tests/net/ieee802154/crypto runs into a CPU exception without starting the test.

**Arch:** x86
**Platform:** quark_se_c1000

It looks like the test should ideally bind with the crypto device, use the key, auth data provided by the test to verify authentication, encryption and display the following results:

> Authentication only test: PASSED
> Encryption only test: PASSED
> Authentication and encryption test: PASSED

But, when test application is flashed, I only get a uart console asking for input, and then after a minute or two I get a _CPU exception_.

**Error log on console:**
```
uart:~$

***** CPU exception 6

Current thread ID = 0xa8007f60
eax: 0x1578fd4c, ebx: 0x00000000, ecx: 0xa800bd28, edx: 0xa8007444
esi: 0xa800bd38, edi: 0xa8007420, ebp: 0xa800bd54, esp: 0xa800bd18
eflags: 0x00010202 cs: 0x0008
eip: 0x40000311
Fatal fault in essential thread! Spinning...
```

**Comment by galak** [comment]
@tbursztyka have you looked at this?

**Comment by tbursztyka** [comment]
See #8339

**Comment by tbursztyka** [comment]
@nniranjhana  can you retry now #8339 is in master? that should fix the issue.

**Comment by tbursztyka** [comment]
Closing this as #14103 fixed that specific issue.

There is still an issue for the test to pass, but that's in issue #15449
