### ISSUE TITLE
Cannot use SPI_0 on nRF52810

### ISSUE THREAD

**Issue by anangl** [zephyrproject-rtos/zephyr#10658]
After the SPI driver configuration was moved to device tree (see #9781), the SPI_0 device became unusable on nRF52810. Compilation fails with a bunch of errors like this:
```
zephyr/include/generated/generated_dts_board.h:305:34: error: 'NORDIC_NRF_SPI_40003000_SCK_PIN' undeclared (first use in this function); did you mean 'NORDIC_NRF_SPI_40004000_SCK_PIN'?
 #define CONFIG_SPI_0_NRF_SCK_PIN NORDIC_NRF_SPI_40003000_SCK_PIN
                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
This is because, unlike in other chips from the nRF52 family, the base address of the SPIM0 peripheral in nRF52810 is [0x40004000](https://github.com/zephyrproject-rtos/zephyr/blob/master/dts/arm/nordic/nrf52810.dtsi#L85), not 0x40003000 as expected by [the common nrf52 fixup file](https://github.com/zephyrproject-rtos/zephyr/blob/master/soc/arm/nordic_nrf/nrf52/dts_fixup.h#L78).

**Comment by nashif** [comment]
@Qbicz fyi
