### ISSUE TITLE
samples/subsys/usb/console: Console routed to UART of no USB

### ISSUE THREAD

**Issue by erwango** [zephyrproject-rtos/zephyr#10693]
When testing samples/subsys/usb/console, "Hello World" is routed to UART console if USB console is not there.
I don't know if this is intended behavior, but this could be confusing when testing.

**Comment by zerotri** [comment]
This totally caught me off guard as well a week ago when I was trying to get a usb shell working on stm32l4. We could maybe add a disclaimer in the README for this sample.

**Comment by finikorg** [comment]
So what is the problem? Missing console?

Since we change console parameters to DTS we have to for every board include the same DTS overlay. Just copy existing overlay to your board name :)

**Comment by finikorg** [comment]
Maybe if DTS magic does not include USB console we could issue #error so that user notice that he needs to enable it?
