### ISSUE TITLE
kernel built with openocd support does not have needed symbols

### ISSUE THREAD

**Issue by nashif** [zephyrproject-rtos/zephyr#1070]
When building with CONFIG_OPENOCD_SUPPORT, the binary should have symbols that have thread data that can be used by openocd, in the current kernel those symbols are being stripped which renders this feature useless.

**Comment by nashif** [comment]
@MaureenHelm does this fix it for you?

**Comment by MaureenHelm** [comment]
> @MaureenHelm does this fix it for you?

Yes
