### ISSUE TITLE
SSD1673 driver it setting a Kconfig symbol in dts_fixup.h

### ISSUE THREAD

**Issue by galak** [zephyrproject-rtos/zephyr#10720]
We seem to set CONFIG_SSD1673_SPI_GPIO_CS in boards/arm/reel_board/dts_fixup.h.  This isn't generated, so seems like this should move into Kconfig and out of dts_fixup.h

**Comment by jfischer-phytec-iot** [comment]
I will tackle it until Sunday, there was a reason why it is there

**Comment by galak** [comment]
> I will tackle it until Sunday, there was a reason why it is there

ping :)

**Comment by jfischer-phytec-iot** [comment]
It is DT_SSD1673_SPI_GPIO_CS now. That was a hack because DT describes whether gpio CS is used or CS from the SPI core.
