### ISSUE TITLE
Cannot flash to STM32 Nucleo F446RE with SEGGER JLink

### ISSUE THREAD

**Issue by RonAmihai** [zephyrproject-rtos/zephyr#10739]
Me & my team are trying to build & flash our code to STM32 Nucleo F446RE with JLink. 
We've upgraded the board's ST-LINK to JLink on-board using SEGGER's reflash tool (as [described here](https://www.segger.com/products/debug-probes/j-link/models/other-j-links/st-link-on-board/)).

Our workspace (Ubuntu 18.04) is configured to work with JLink utillities. We've developed Zephyr using nRF JLink boards before (nRF52840 & nRF52832) and had no issues with building & flashing our projects.

But with Nucleo F466RE we are experiencing issues during flash. Despite we are building our code with CMake argument "STLINK_FW=jlink" (as described [here](https://github.com/zephyrproject-rtos/zephyr/blob/master/doc/tools/stlink-v21.rst)) - Ninja build always trying to use OpenOCD as runner during flash & fails. 

On the other hand, we have no issues to flash programs using Ozone (SEGGER's debugger), so JLink is configured correctly on the board.

When reverting back to ST-LINK, we have no issue to flash with OpenOCD of course - but we need JLink's functionality during our development. 

There are other steps we should take in order to build & flash projects to Nucleo F446RE with JLink?

**Comment by qianfan-Zhao** [comment]
Do you had updated nucleo-f446 board's cmake scripts?

**Comment by qianfan-Zhao** [comment]
Please take a look about this commit:  d1054f7

I don't has another board, so just changed f070 only

**Comment by galak** [comment]
Any updates on this?

**Comment by erwango** [comment]
@RonAmihai , did the indications provided by @qianfan-Zhao helped you?

**Comment by galak** [comment]
@RonAmihai going to change this to an enhancement.

**Comment by DenvE** [comment]
Hi,

still some issues on windows using cmake / ninja

using the hello_world example.
steps to execute

in root dir of zephyr execute zephyr-env.cmd and update the toolchain.
set ZEPHYR_TOOLCHAIN_VARIANT= ??
set GNUARMEMB_TOOLCHAIN_PATH= ??

cd sample\hello_world
mkdir build
cd build
cmake -GNinja -DBOARD=stm32f746g_disco  -DSTLINK_FW=jlink ..
ninja
 
until now all fine,.

ninja flash ==> fails

reason:

jlinkexe doesn't exists, the file name is jlink.exe

I have fixed this locally,

next issue, it found the jlink.exe,.. but which one,..
C:\Program Files\Java\jdk-11.0.1\bin\jlink.exe  ( java!!)

so also a setting for FILEPATH is needed for jlink ( like for openocd)

**Comment by erwango** [comment]
@DenvE , this does not seems related to current issue. Please raise a dedicated issue.

**Comment by carlescufi** [comment]
@RonAmihai or @erwango any chances of sending a patch for this?

**Comment by GeorgeCGV** [comment]
> Hi,
> 
> still some issues on windows using cmake / ninja
> 
> using the hello_world example.
> steps to execute
> 
> in root dir of zephyr execute zephyr-env.cmd and update the toolchain.
> set ZEPHYR_TOOLCHAIN_VARIANT= ??
> set GNUARMEMB_TOOLCHAIN_PATH= ??
> 
> cd sample\hello_world
> mkdir build
> cd build
> cmake -GNinja -DBOARD=stm32f746g_disco -DSTLINK_FW=jlink ..
> ninja
> 
> until now all fine,.
> 
> ninja flash ==> fails
> 
> reason:
> 
> jlinkexe doesn't exists, the file name is jlink.exe
> 
> I have fixed this locally,
> 
> next issue, it found the jlink.exe,.. but which one,..
> C:\Program Files\Java\jdk-11.0.1\bin\jlink.exe ( java!!)
> 
> so also a setting for FILEPATH is needed for jlink ( like for openocd)

A quick fix for this is to re-arrange entries in your PATH environment variable in a way that J-Link path is before Java path. However, this might break some tools which use java's jlink.
