### ISSUE TITLE
[Coverity CID :188883]Memory - illegal accesses in /subsys/bluetooth/host/hci_core.c

### ISSUE THREAD

**Issue by mandarcthorat1** [zephyrproject-rtos/zephyr#10756]
Static code scan issues seen in File: /subsys/bluetooth/host/hci_core.c
 Category: Memory - illegal accesses
 Function: bt_dev_show_info
 Component: Bluetooth
 CID: 188883
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by ceolin** [comment]
this was classified as false positive on Coverity. Closing it.
