### ISSUE TITLE
[Coverity CID :188889]Memory - illegal accesses in /subsys/bluetooth/host/gatt.c

### ISSUE THREAD

**Issue by mandarcthorat1** [zephyrproject-rtos/zephyr#10751]
Static code scan issues seen in File: /subsys/bluetooth/host/gatt.c
 Category: Memory - illegal accesses
 Function: gatt_find_type
 Component: Bluetooth
 CID: 188889
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by Vudentz** [comment]
@mandarcthorat1 is this still valid or can I close it?
