### ISSUE TITLE
[Coverity CID :188887]Error handling issues in /tests/posix/common/src/pthread.c

### ISSUE THREAD

**Issue by mandarcthorat1** [zephyrproject-rtos/zephyr#10753]
Static code scan issues seen in File: /tests/posix/common/src/pthread.c
 Category: Error handling issues
 Function: test_posix_pthread_termination
 Component: Tests
 CID: 188887
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by nniranjhana** [comment]
False positive, `pthread_setschedparam` can take any integer policy arguments, it is implementation defined.
