### ISSUE TITLE
shell: Uncomfortable handling of "current editline" vs history

### ISSUE THREAD

**Issue by pfalcon** [zephyrproject-rtos/zephyr#10766]
Here's how GNU readline, and a bunch of its workalines work:

1. Suppose you have some lines in the history buffer.
2. Now you start with an empty line with prompt.
3. You can press up arrow and go to previous command in history.
4. Then you can press down, and you'll get back to you empty line to type new things in!

Current Zephyr shell breaks down on step 4. You can't press down and get back to the current edit line. Suppose you types 50 or 80 char command and executed it. Then by accident you pressed up, and now you need to delete thru 50-80 chars to be able to type a new command. That's rather annoying.

Note that readline's behavior is more complex than the above, there's also:

5. You can actually start typing a new command, press up any number of times (find needed command, e.g. copy one of its arg to clipboard), then press down to get back to "current editline", and it will contain the content you already typed in, it won't be lost.

**Comment by pfalcon** [comment]
@carlescufi, @nashif : FYI. This is arguably a feature request, but a pretty priority one, I hope we won't live too much without it.

@jukkar : I wonder if you can relate to this feature quest.

**Comment by jarz-nordic** [comment]
@pfalcon : this can be quickly fixed. I will take care tomorrow.

**Comment by pfalcon** [comment]
@jarz-nordic : Thanks for acking! No too big a hurry of course.
