### ISSUE TITLE
Flash Shell compilation error without BT

### ISSUE THREAD

**Issue by chris-makaio** [zephyrproject-rtos/zephyr#10760]
Compiling without BT shell I get a compilation error for line
extern const struct shell *ctx_shell;

If I change to
const struct shell *ctx_shell;

it works, so I guess w/o BT shell it's simply not exposed.
However, I wonder why this is needed as the shell comes as param in every cmd

**Comment by Vudentz** [comment]
I wonder what the flash has to do with BT shell here? Note that any asynchronous operation that requires to print out something to the shell need a shell pointer in order to do so, which is what the ctx_shell is used for.

**Comment by derchrismakaio** [comment]
@Vudentz well, my own application... I'll keep an eye on this and when I stumble accross a sample which gives the same error I'll let you know

**Comment by galak** [comment]
Going to close this, please re-open if you can provide a reproducible test case showing the issue.

**Comment by vanwinkeljan** [comment]
Problem is reproducible by adding following configs to hello_world sample prj.conf and building for reel_board:
```
CONFIG_FLASH=y
CONFIG_FLASH_SHELL=y
```

**Comment by vanwinkeljan** [comment]
fix is merged
