### ISSUE TITLE
Recent Logger changes breaks shell example compilation

### ISSUE THREAD

**Issue by jarz-nordic** [zephyrproject-rtos/zephyr#10771]
Due to commit: be092a607aea6d3f0458ec44693951b343b9a9d0
I am not able to build shell example any longer. I have following error message:
![error_msg](https://user-images.githubusercontent.com/34125330/47321873-6bdd5900-d656-11e8-8f20-3e90f7240d22.PNG)

This problem is visible also on a master branch.

**Comment by nordic-krch** [comment]
have you cleaned the project after fetching upstream? I've fetched latest master and compiled shell example without any issues.

**Comment by jukkar** [comment]
This should be fixed by #10763

**Comment by jukkar** [comment]
The #10763 is now merged, please try again and re-open if problem persists.

**Comment by jarz-nordic** [comment]
It is fixed, thank you.
