### ISSUE TITLE
net: ipv4: Zephyr replies to TCP SYN with broadcast destination IPv4 address

### ISSUE THREAD

**Issue by rmstoi** [zephyrproject-rtos/zephyr#10780]
Zephyr TCP/IPv4 replies to  TCP SYN with destination IP address set to 255.255.255.255 broadcast address. This packet should be dropped instead.

[ipv4-tcp-bcast-syn.pcapng.gz](https://github.com/zephyrproject-rtos/zephyr/files/2505170/ipv4-tcp-bcast-syn.pcapng.gz)

**Comment by jukkar** [comment]
Never mind, this is about destination address being all ones, the other bug is about source address being all ones. We can keep these ones separate of course.
