### ISSUE TITLE
Convert Atmel SAM Watchdog driver to new API

### ISSUE THREAD

**Issue by galak** [zephyrproject-rtos/zephyr#10913]
We have a new driver API for watchdog, the old API has been deprecated for several releases now.  We need to convert the driver to use the API or remove it.

**Comment by subbu147** [comment]
Hi Kumar,
I have done in it PR #10828. Can you please take a look at it.

**Comment by galak** [comment]
@subbu147 thanks for the update.  I've made some cleanups and enhancements.  Take a look, and if you can test it out, that would be great.

**Comment by subbu147** [comment]
addressed by PR #10828. This issue can be closed.

**Comment by galak** [comment]
Resolved by merge of #10828
