### ISSUE TITLE
Add device tree support for usb controllers on x86

### ISSUE THREAD

**Issue by galak** [zephyrproject-rtos/zephyr#10996]
For boards like arduino_101, quark_se_c1000_devboard, tinytile we need to add dts support similar to what we have on stm32

**Comment by nashif** [comment]
@SavinayDharmappa please take a look at this as well.

**Comment by galak** [comment]
This would let us remove include <board.h> in subsys/usb/usb_device.c as its just need to get GPIO info, which we'd get from DT instead.  This is one of the few <board.h> references left to remove.

**Comment by SavinayDharmappa** [comment]
https://github.com/zephyrproject-rtos/zephyr/pull/13368

**Comment by carlescufi** [comment]
@galak @nashif is this still applicable?

**Comment by finikorg** [comment]
Not applicable anymore
