### ISSUE TITLE
About printk configuration

### ISSUE THREAD

**Issue by findlayfeng** [zephyrproject-rtos/zephyr#11019]
https://github.com/zephyrproject-rtos/zephyr/blob/79b9b51307940116f66783dc8bd55a38cb1f8674/subsys/debug/Kconfig#L65

The functions in printk.c are used in many places, including many places that are not related to debug.
For example, the snprintk function is used in bt_settings, which has nothing to do with CONSOLE_HAS_DRIVER.
But if I want to use it, I must configure CONSOLE_HAS_DRIVER because of dependency.
The small device I use does not have CONSOLE.

**Comment by nashif** [comment]
this is similar to #10143

**Comment by nashif** [comment]
closing as duplicate
