### ISSUE TITLE
doc: missing Doxygen generated documentation for any function which name starts with an underscore

### ISSUE THREAD

**Issue by mnkp** [zephyrproject-rtos/zephyr#11047]
"[Power Management Hook Interface](https://docs.zephyrproject.org/latest/api/power_management_api.html#power-management-hook-interface)" section of "[Power Management APIs](https://docs.zephyrproject.org/latest/api/power_management_api.html)" is empty despite the fact that zephyr/include/power.h contains all necessary Doxygen comments.

Functions which should appear in this section are:
```
static inline void _sys_soc_pm_idle_exit_notification_disable(void);
void _sys_soc_resume_from_deep_sleep(void);
void _sys_soc_resume(void);
extern int _sys_soc_suspend(s32_t ticks);
```

It looks like Doxygen ignores all function names which start with an underscore.

**Comment by dbkinder** [comment]
This is a deliberate configuration of doxygen, added by PR #6280

@lpereira @nashif The assumption was that symbols with leading underscores "shouldn't be used by applications, as there's no guarantee they will be available in subsequent versions or maintain
API and ABI compatibility.  Is this still true and the desired behavior of our API doc processing?

**Comment by nashif** [comment]
@ramakrishnapallala I do not remember the history behind the naming, but those functions are being documented and appear in a public API, so they should not have _sys prefix. The _ should be removed from all public APIs and documented hooks. underscore should only be used for internal function calls.
