### ISSUE TITLE
Compiler warning at include/misc/util.h when building for ESP32

### ISSUE THREAD

**Issue by nniranjhana** [zephyrproject-rtos/zephyr#11077]
We have a compiler warning being treated as error, thus stopping build.

The issue as reported says that 

` #define BIT(n)  (1UL << (n))`

is re-defined at _/zephyr/include/misc/util.h:135_

Well, it complains because when we build with our toolchains, **esp-idf** already includes it at 
_esp-idf/components/soc/esp32/include/soc/soc.h:128_

as `#define BIT(nr)                 (1UL << (nr))`

So we should probably not include our definition when building for ESP32.

**Comment by pfalcon** [comment]
@lpereira : Is there a reason why you're not in CODEOWNERS for any xtensa/esp32 stuff?

**Comment by lpereira** [comment]
@pfalcon I'm not working on Zephyr any longer.

**Comment by lpereira** [comment]
In any case, this is just the matter of including headers in the right order.  This error happened before; see, for instance, `drivers/serial/uart_esp32.c`.

**Comment by nashif** [comment]
not fixed yet

**Comment by nashif** [comment]
@dcpleung you introduced this issue in 5a47c60dbf4f24fa9ad2206502d5eab152587eac, can you please take a look.
