### ISSUE TITLE
Reelboard sample

### ISSUE THREAD

**Issue by wizofe** [zephyrproject-rtos/zephyr#11076]
Is there any sample files for the reelboard LCD screen and Bluetooth stack? Thanks :)

**Comment by vanwinkeljan** [comment]
A display sample for the reelboard can be found in samples/display/cfb/

**Comment by pfalcon** [comment]
@wizofe : You may get better response with such questions on the mailing list.

**Comment by wizofe** [comment]
Thank you @vanwinkeljan.
