### ISSUE TITLE
[Coverity CID :189518]Memory - illegal accesses in /samples/boards/reel_board/mesh_badge/src/reel_board.c

### ISSUE THREAD

**Issue by mandarcthorat1** [zephyrproject-rtos/zephyr#11088]
Static code scan issues seen in File: /samples/boards/reel_board/mesh_badge/src/reel_board.c
 Category: Memory - illegal accesses
 Function: epd_update
 Component: Samples
 CID: 189518
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by jhedberg** [comment]
@himanshujha199640 generally I try to do that - I just overlooked the fact that there was an open github issue for it (I fixed it as a consequence of the Coverity email report, not this github issue).

**Comment by jhedberg** [comment]
Already fixed.
