### ISSUE TITLE
[Coverity CID :189512]Null pointer dereferences in /subsys/logging/log_msg.c

### ISSUE THREAD

**Issue by mandarcthorat1** [zephyrproject-rtos/zephyr#11094]
Static code scan issues seen in File: /subsys/logging/log_msg.c
 Category: Null pointer dereferences
 Function: msg_alloc
 Component: Other
 CID: 189512
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by ceolin** [comment]
fixed in c554ab71005a10110eb959cb32c53133b18b5ac3
