### ISSUE TITLE
[Coverity CID :189514]Possible Control flow issues in /drivers/display/ssd1673.c

### ISSUE THREAD

**Issue by mandarcthorat1** [zephyrproject-rtos/zephyr#11092]
Static code scan issues seen in File: /drivers/display/ssd1673.c
 Category: Possible Control flow issues
 Function: ssd1673_write
 Component: Drivers
 CID: 189514
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by vanwinkeljan** [comment]
Note that this code has been removed in PR #11351

**Comment by vanwinkeljan** [comment]
fixed by #11351
