### ISSUE TITLE
[Coverity CID :189510]Memory - corruptions in /subsys/bluetooth/host/monitor.c

### ISSUE THREAD

**Issue by mandarcthorat1** [zephyrproject-rtos/zephyr#11096]
Static code scan issues seen in File: /subsys/bluetooth/host/monitor.c
 Category: Memory - corruptions
 Function: monitor_log_put
 Component: Bluetooth
 CID: 189510
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by jhedberg** [comment]
Flagged as false positive in Coverity
