### ISSUE TITLE
CONFIG_TICKLESS_KERNEL makes z_clock_set_timeout doesn't work

### ISSUE THREAD

**Issue by vonhust** [zephyrproject-rtos/zephyr#11129]
@andyross @nashif  @ruuddw 

in timeout.c, the function will call  the clock driver wrapper z_clock_set_timerout in legacy_api.h.

```
void z_clock_set_timeout(s32_t ticks, bool idle)
{
#ifdef CONFIG_TICKLESS_KERNEL
	if (idle) {
		_timer_idle_enter(ticks);
	} else {
		_set_time(ticks == K_FOREVER ? 0 : ticks);
	}
#endif
}
```

According to the code, if TICKLESS_KERNEL is not configured,  z_clock_set_timeout will do nothing, which means  the timeout mechnism will fail.

I already observed the failure in tests/kernel/profiling/profiling_api caused by the changes in clock driver (legacy_api.h)

BTW in line 46 of legacy_api.h 

`#ifdef TICKLESS_KERNEL` shoud be `#ifdef CONFIG_TICKLESS_KERNEL` ?

**Comment by andyross** [comment]
z_clock_set_timeout() is an internal API between the kernel and timer driver, and indeed it's a noop if TICKLESS_KERNEL is not defined.  When TICKLESS_KERNEL=n, the driver is expected to deliver regular ticks on its own, and doesn't need the kernel to tell it when to schedule the next z_clock_announce().

**Comment by vonhust** [comment]
So, how about the case TICKLESS_IDLE?  When TICKLESS_IDLE is configured and TICKLESS_KERNEL not configured,  z_clock_set_timeout should not be noop.

For ARC, in arcv2_timer0.c,  z_clock_idle_exit and _timer_idle_enter should be a couple. If z_clock_set_timeout is a noop, it means _timer_idle_enter will not be called.

Then the call to z_clock_idle_exit  in interrupt handling will cause problem.


For ARM’s systick driver,  I see similar logic.

**Comment by andyross** [comment]
Check the new drivers in #10556, hopefully that will be clearer.   I think the problem is that you're looking at only half the change (the API refactoring) and getting confused about the shim layer needed to make the older drivers work.
