### ISSUE TITLE
Building failing in arm cortex-m0

### ISSUE THREAD

**Issue by ceolin** [zephyrproject-rtos/zephyr#11167]
Building is failing when `CONFIG_NO_OPTIMIZATIONS` is enabled. This is the output for `./samples/hello_world/` with bbc-microbit as target.

```
Memory region         Used Size  Region Size  %age Used
           FLASH:      103636 B       256 KB     39.53%
            SRAM:        9240 B        16 KB     56.40%
        IDT_LIST:         120 B         2 KB      5.86zephyr/arch/arm/core/libarch__arm__core.a(isr_wrapper.S.obj): In function `_idle_state_cleared':
./zephyr/arch/arm/core/isr_wrapper.S:132:(.text._isr_wrapper+0x2c): relocation truncated to fit: R_ARM_THM_JUMP11 against symbol `_IntExit' defined in .text._HandlerModeExit section in zephyr/arch/arm/core/libarch__arm__core.a(exc_exit.S.obj)                                                                                                                             
collect2: error: ld returned 1 exit status
%
ninja: build stopped: subcommand failed.
```

**Comment by SebastianBoe** [comment]
Reproduced.

```
diff --git a/samples/hello_world/CMakeLists.txt b/samples/hello_world/CMakeLists.txt
index 9c3c38b669..ad74422ed8 100644
--- a/samples/hello_world/CMakeLists.txt
+++ b/samples/hello_world/CMakeLists.txt
@@ -1,5 +1,7 @@
 cmake_minimum_required(VERSION 3.8.2)
 
+set(BOARD nrf51_pca10028)
+
 include($ENV{ZEPHYR_BASE}/cmake/app/boilerplate.cmake NO_POLICY_SCOPE)
 project(hello_world)
 
diff --git a/samples/hello_world/prj.conf b/samples/hello_world/prj.conf
index b2a4ba5910..8c8a1404c5 100644
--- a/samples/hello_world/prj.conf
+++ b/samples/hello_world/prj.conf
@@ -1 +1,2 @@
 # nothing here
+CONFIG_NO_OPTIMIZATIONS=y

```

**Comment by SebastianBoe** [comment]
Fixed.

Not sure what kind of consequences this fix has though, it might be breaking things ...

```
diff --git a/arch/arm/core/isr_wrapper.S b/arch/arm/core/isr_wrapper.S
index 53c24645d7..d3c24d33f1 100644
--- a/arch/arm/core/isr_wrapper.S
+++ b/arch/arm/core/isr_wrapper.S
@@ -133,4 +133,4 @@ _idle_state_cleared:
 #endif /* CONFIG_ARMV6_M_ARMV8_M_BASELINE */
 
 	/* exception return is done in _IntExit() */
-	b _IntExit
+	bl _IntExit
diff --git a/samples/hello_world/CMakeLists.txt b/samples/hello_world/CMakeLists.txt

```

**Comment by SebastianBoe** [comment]
The root cause and solution options are described in https://github.com/zephyrproject-rtos/zephyr/commit/17652760001cec19cd25f48fa18d0c973f5ca345#diff-ef6459503728d8b77ea93b33e8de0117

Personally I think that porting to C is the best long-term solution. Not sure what to do short-term ...

**Comment by ceolin** [comment]
> Fixed.
> 
> Not sure what kind of consequences this fix has though, it might be breaking things ...
> 
> ```
> diff --git a/arch/arm/core/isr_wrapper.S b/arch/arm/core/isr_wrapper.S
> index 53c24645d7..d3c24d33f1 100644
> --- a/arch/arm/core/isr_wrapper.S
> +++ b/arch/arm/core/isr_wrapper.S
> @@ -133,4 +133,4 @@ _idle_state_cleared:
>  #endif /* CONFIG_ARMV6_M_ARMV8_M_BASELINE */
>  
>  	/* exception return is done in _IntExit() */
> -	b _IntExit
> +	bl _IntExit
> diff --git a/samples/hello_world/CMakeLists.txt b/samples/hello_world/CMakeLists.txt
> ```
> 
> EDIT: This fix is no good.

Yeah, it override the link register, one change that works is save lr register into other register and restore it in _IntExit. But my re-organize these sections make more sense to me.
