### ISSUE TITLE
Minor Typo "dirver" in UART of Native Posix

### ISSUE THREAD

**Issue by vsaw** [zephyrproject-rtos/zephyr#11179]
See https://github.com/zephyrproject-rtos/zephyr/blob/bded528b6b4f12ebd0d83ef2119518aa356ad8b9/drivers/serial/uart_native_posix.c#L182

**Comment by pfalcon** [comment]
@vsaw : Care to submit a patch? ;-) Fixing a typo is a smoothest way to start to contribute, if you're interested in that.
