### ISSUE TITLE
ARM V8M Trusted Execution Environments and Zephyr

### ISSUE THREAD

**Issue by agross-oss** [zephyrproject-rtos/zephyr#11193]
This issue is to document use cases, threat models, functional requirements, and design considerations for a trusted execution environment in Zephyr on ARMv8M hardware implementations.  We can broaden this if we need to include ARC.

**Comment by agross-linaro** [comment]
Associated issues:
https://github.com/zephyrproject-rtos/zephyr/issues/6648

**Comment by ioannisg** [comment]
FYI @andrewboie

**Comment by ioannisg** [comment]
FYI @dstroe2000

**Comment by d3zd3z** [comment]
FYI @microbuilder

**Comment by microbuilder** [comment]
Closing due to TF-M integration in Zephyr solving this problem.
