### ISSUE TITLE
Bluetooth Mesh: device receives it's own sent messages when CONFIG_BT_SETTINGS is enabled

### ISSUE THREAD

**Issue by RonAmihai** [zephyrproject-rtos/zephyr#11198]
@jhedberg 

I'm opening this issue further to my previous one, which also refers to Bluetooth Mesh. Maybe the issues are related.
https://github.com/zephyrproject-rtos/zephyr/issues/10952

I'm using nRF52840-pca10056 as development board.

When CONFIG_BT_SETTINGS is enabled, and messages are sent through publication context, I've noticed that the same device receives it own messages. 

In my situation, the publication context sends message with opcode 0x40, and fails afterwards with debug message "No OpCode 0x00000040 for elem 0" because this opcode isn't bound to any model (there is no point to be bound to opcode which is used to send outgoing messages).

This debug message is printed in function bt_mesh_model_recv (mesh/access.c). 

Disabling CONFIG_BT_SETTINGS solves the above issue, even though outgoing messages opcodes (as part of the message's buffer) shouldn't be stored anyway

**Comment by jhedberg** [comment]
What destination address are you using? Are you sure the local node doesn't subscribe to it?

**Comment by RonAmihai** [comment]
Erasing the device's flash using nrfjprog utility (-e / --eraseall) actually solved this issue for us. 
Thanks for helping anyway.
