### ISSUE TITLE
Turning on SystemView causes error

### ISSUE THREAD

**Issue by MarekPieta** [zephyrproject-rtos/zephyr#11244]
Starting SystemView in make menuconfig causes error - program is no longer working. Checked in gdb and noticed that execution does not even reach start of main function. 
With SystemView turned on program receives signal SIGTRAP at 

`/zephyr/kernel/mutex.c:118 (function: _impl_k_mutex_lock (mutex=0x200041d8 <rtt_term_mutex>, timeout=timeout@entry=-1)).`

Problem is caused by `sys_trace_void(SYS_TRACE_ID_MUTEX_LOCK)` (and SEGGER_SYSVIEW_RecordVoid) call in _impl_k_mutex_lock function . Currently sending data via RTT (for example in SystemView) requires locking mutex, locking mutex calls SEGGER_SYSVIEW_RecordVoid, which locks mutex, which calls SYSVIEW_Record_Void and so on.

Detected on: nrf52_pca10040, hello_world sample

**Comment by nashif** [comment]
fixed in #12149
