### ISSUE TITLE
tests/kernel/gen_isr_tables only runs on ARM

### ISSUE THREAD

**Issue by andrewboie** [zephyrproject-rtos/zephyr#11274]
This test ought to run on any platform which uses CONFIG_GEN_ISR_TABLES and has code to trigger an interrupt line from software. The test used to run on ARC and RISCV32.

The bug is in the testcase.yaml which has an incorrect filter line:
`filter: CONFIG_GEN_ISR_TABLES and CONFIG_ARMV7_M_ARMV8_M_MAINLINE`

**Comment by cfriedt** [comment]
`tests/kernel/gen_isr_tables` does run on `arm`, `arc`, `riscv32`, and `riscv64`, currently, but there are a few other platforms that select or depend on `GEN_ISR_TABLES`, like 

* `mips`
* `arm64`
* `sparc`
* `nios2`
* `xtensa`

Additionally, of the `riscv64` variety, `adp_xc7k_ae350` is excluded from this test, but it really should be included.
