### ISSUE TITLE
Installation of requirements.txt fail because of pyocd issue

### ISSUE THREAD

**Issue by aunsbjerg** [zephyrproject-rtos/zephyr#11279]
Installation of requirements.txt fails because the latest release of pyocd is not installable via pip. See mbedmicro/pyOCD#442.

I suggest locking the pyocd dependency to a version that is now to least be installable, ie. version 0.12.0.

**Comment by henrikbrixandersen** [comment]
Thanks! This was fixed via #11280. Closing.
