### ISSUE TITLE
Please clarify on BT L2CAP

### ISSUE THREAD

**Issue by chris-makaio** [zephyrproject-rtos/zephyr#11312]
Dear all,
Documentation for L2CAP is rather short and it seems as there are no samples.
Trying to move from Notdic‘s SDK I really have trouble understanding Zephyr‘s BT stack (beyond the basic old-school GATT peripheral and central ping pong).
Is there any documentation (apart from the autodocs) I am missing here?

**Comment by Vudentz** [comment]
This has been fixed by https://github.com/zephyrproject-rtos/zephyr/pull/14163
