### ISSUE TITLE
sockets: Implement select() call

### ISSUE THREAD

**Issue by pfalcon** [zephyrproject-rtos/zephyr#11333]
Now that sockets are backed by file descriptors, i.e. we know they're small integers, we can implement select().

**Comment by pfalcon** [comment]
@GAnthony, @rlubos : FYI

**Comment by pfalcon** [comment]
Actually, all this time everyone (?, perhaps just me) assumed that select, well, FD_SET, would need to be implemented in a classic (?) way using bitsets. Ahem, it doesn't have to! We could implement it long ago, with FD_SET backed by struct pollfd[]. Of course, then FD_ISSET() would need to loop over this array, which is O(n), but given that the array would be small anyway, nobody would care. And those who care about performance, shouldn't use select() in the first place.

So, I guess we should implement it like that now.

**Comment by pfalcon** [comment]
@GAnthony, @rlubos: So, I assume there're no criticism/concerns. I otherwise would plan this implementation yet for this year.

@jukkar, @tbursztyka: Also if you're interested, I try not to ping you on socket details, maybe I should.

If there's something to discuss, there's opportunity to do that at tomorrow's networking forum.

**Comment by GAnthony** [comment]
@pflacon, Thanks, select() would be good to have.
