### ISSUE TITLE
extract_dts_includes.py causes build error on cell name detection

### ISSUE THREAD

**Issue by b0661** [zephyrproject-rtos/zephyr#11357]
**Describe the bug**

Within extract_cells() in exrract_dts_inlcudes.py the default for an unavailable cell name is an empty list, whereas a  given name is a string. Leads to a build time error if the name is given because later on a list is expected.

```
    try:
        name = names.pop(0).upper()
    except:
        name = []
```

Furthermore if a device has several cell related properties the cell name definition in the yaml binding clashes because the cell names are given by the "#cells" key.

**To Reproduce**
Behaviour was detected with a set of out of tree drivers and DTS bindings.

**Expected behavior**
- Default for name should be an empty string. 
- A more specific key for the cell names in the binding shall be used. E.g. the same key that is used to define the number of cells "#whatever-cells".

**Impact**
Out of tree driver set does not work.

**Environment (please complete the following information):**
 - OS:  Linux
 - Toolchain: 0.9.5
 - Commit SHA or Version used: Zephyr/master

**Comment by galak** [comment]
> **To Reproduce**
> Behaviour was detected with a set of out of tree drivers and DTS bindings.

Can you give an example that shows the issue?
