### ISSUE TITLE
Move tests/subsys/fs/multi-fs/src/test_fs_shell to new shell

### ISSUE THREAD

**Issue by nashif** [zephyrproject-rtos/zephyr#11356]
tests/subsys/fs/multi-fs/src/test_fs_shell still using old shell.

**Comment by jarz-nordic** [comment]
In my PR: #10902 I am going to remove tests/subsys/fs/multi-fs/prj_fs_shell.conf because this project can be only build for qemu and qemu does not have DT_FLASH_DEV_NAME. Hence example compilation fails :(

If this problem can be addressed by this PR it is great!
