### ISSUE TITLE
Move STM32 RTC to new counter API

### ISSUE THREAD

**Issue by erwango** [zephyrproject-rtos/zephyr#11373]
**Is your feature request related to a problem? Please describe.**
Move STM32 RTC driver to new counter API (cf #8340)

**Describe the solution you'd like**
Could look at https://github.com/zephyrproject-rtos/zephyr/pull/11347 as example of similar work

**Comment by galak** [comment]
@ydamigos Is this something you might have some time to look into doing?

**Comment by ydamigos** [comment]
@galak My time is limited but I'll give it a try,

**Comment by erwango** [comment]
@ydamigos , have you started? I should find some time to check it this week.

**Comment by ydamigos** [comment]
@erwango yes, I did some work on it. You could find it [here](https://github.com/ydamigos/zephyr/tree/stm32-rtc). It compiles but it doesn't work on target.

**Comment by erwango** [comment]
ok, I finally started as well :-). It is [here](https://github.com/erwango/zephyr/tree/dev_rtc_counter_stm32). Not linking with Cube for some issue for now.
I took some options that could be discussed since new API doesn't fit nicely STM32 RTC IP, but out of our 2 initiatives we should manage to get through.
