### ISSUE TITLE
Enhance DTS yaml support to handle device being on different bus types

### ISSUE THREAD

**Issue by galak** [zephyrproject-rtos/zephyr#11375]
Currently we have sensors that can be connected over either I2C or SPI.  To handle this we have different compatible names like ("st,lsm6dsl-spi" & "st,lsm6dsl").  We really should only have a single compatible for the device ("st,lsm6dsl").

**Comment by erwango** [comment]
I'm surprised by this request.
Node for spi bus slave or i2c bus slave will have different properties, how can we make map this to single compatible ? (which  mean a single driver will have to be able to handle both)

**Comment by galak** [comment]
> I'm surprised by this request.
> Node for spi bus slave or i2c bus slave will have different properties, how can we make map this to single compatible ? (which mean a single driver will have to be able to handle both)

All of the properties that aren't bus specific should be identical for the same sensor like st,lsm6dsl.  I assume that if a sensor supports connecting over I2C or SPI that everything else is the same.

**Comment by erwango** [comment]
Ok, so then, they can share a common "phy", but I don't how we can have common bus slaves.
So 2 bus slaves variants that share the same sensor phy node?
