### ISSUE TITLE
device.c ignores return value from device init

### ISSUE THREAD

**Issue by koffes** [zephyrproject-rtos/zephyr#11408]
**Description**
A device driver may return an error on init, e.g. if the physical hardware is not found on the board.
Many of the existing Zephyr drivers return an error if something fails in their init function.
The device_init_fn() is passed to e.g. the DEVICE_AND_API_INIT macro.
At boot the kernel initialises these devices, and as I can see, the return value is ignored.

The decision to ignore these errors are done in device.c: `_sys_device_do_config_level` 
`(void)device_conf->init(info);`

**Expected behaviour**
When an error is returned from init() there must be some way for the user to see this.
Now, we risk that a device is not physically present/faulty/other error and Zephyr will continue the boot process as if nothing has happened.

**Impact**
Lets Zephyr boot with faults present, and no user indication. This may lead to cryptic error messages later.

**Suggested solution**
Suggest that errors for devices loaded early may be caught by an __ASSERT, and post-kernel may be caught by k_oops().

**Comment by pfalcon** [comment]
See https://github.com/zephyrproject-rtos/zephyr/pull/10496

**Comment by koffes** [comment]
I will close this issue as it is fairy covered by #3079 and #10496.
