### ISSUE TITLE
gPTP sample fails on frdm_k64f

### ISSUE THREAD

**Issue by agansari** [zephyrproject-rtos/zephyr#11416]
Interrupt is not correctly set for PTP in networking driver

To reproduce run gPTP sample on K64F, you will observe ISR 82 crash.

**Comment by tbursztyka** [comment]
Seems like the same as @jukkar reported here in #11275 but the issue you opened is actually targeting the right culprit.

**Comment by agansari** [comment]
Yes, it's the same issue

**Comment by MaureenHelm** [comment]
Fixed by #11439
