### ISSUE TITLE
checkpatch warns on .dtsi files about line length

### ISSUE THREAD

**Issue by gon1332** [zephyrproject-rtos/zephyr#11449]
**Describe the bug**
As a git hook on pre-commit I have the checkpatch enabled.
I've put a new entry in `dts/arm/st/l4stm32l4-pinctrl.dtsi`, but as you can see, every entry
is above the line length limit. So was mine.

**To Reproduce**
1. add a new entry in such a file as described above
2. add .
3. commit -s

**Expected behavior**
I expected to have some sort of whitelisting on what is checked in special(?) files.

**Impact**
It is annoying since I had the hook disabled, just to not change the format of the source in .dtsi.

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: Zephyr SDK
 - 0670ba6c9231ac1dec8a893ba40796e41a7734a8

**Comment by nashif** [comment]
we moved from 80 to 100, so that should be enough, and IMO the rule in general should apply to all files.
