### ISSUE TITLE
where is PM_CONTROL_OS defined in Kconfig?

### ISSUE THREAD

**Issue by nashif** [zephyrproject-rtos/zephyr#11464]
Can't find where PM_CONTROL_OS is being defined in Kconfig. It is being used in 

`subsys/power/Kconfig`

**Comment by ulfalizer** [comment]
Seems to be in `kernel/Kconfig.power_mgmt`.

The auto-generated Kconfig docs (and the menuconfig) list definition locations by the way: https://docs.zephyrproject.org/latest/reference/kconfig/CONFIG_PM_CONTROL_OS.html

**Comment by galak** [comment]
@nashif can we close this, seems like its defined in `kernel/Kconfig.power_mgmt` as @ulfalizer said.
