### ISSUE TITLE
kernel: msgq: add tests for k_msgq_peek

### ISSUE THREAD

**Issue by sathishkuttan** [zephyrproject-rtos/zephyr#11460]
**Is your feature request related to a problem? Please describe.**
PR #11294 is being submitted to add a `peek()` API to kernel message queue. There is a set of tests for `k_msgq` APIs using Zephyr test framework. While I could implement the actual API, I could not understand the test framework and unable to add a test for this API. This submission is to assign the work to someone who understands the test framework better.

**Describe the solution you'd like**
Add a test for `k_msgq_peek()` under `tests/kernel/msgq/msgq_api`

**Comment by nashif** [comment]
@nniranjhana , @spoorthik can you please add a test for this new API?
