### ISSUE TITLE
[Coverity CID :189742]Program hangs in /drivers/usb/device/usb_dc_sam.c

### ISSUE THREAD

**Issue by mandarcthorat1** [zephyrproject-rtos/zephyr#11481]
Static code scan issues seen in File: /drivers/usb/device/usb_dc_sam.c
 Category: Program hangs
 Function: usb_dc_ep_write
 Component: Drivers
 CID: 189742
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by aurel32** [comment]
This is a false positive from Coverity. `usb_dc_ep_mps()` can indeed return a negative value if the endpoint address is out of range, however the returned value is not used in that case.

Anyway I'll send a patch shuffling the code to get rid of this warning.
