### ISSUE TITLE
[Coverity CID :189743]Incorrect expression in /drivers/usb/device/usb_dc_sam.c

### ISSUE THREAD

**Issue by mandarcthorat1** [zephyrproject-rtos/zephyr#11480]
Static code scan issues seen in File: /drivers/usb/device/usb_dc_sam.c
 Category: Incorrect expression
 Function: usb_dc_attach
 Component: Drivers
 CID: 189743
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by aurel32** [comment]
This is a false positive from Coverity. It assumes the `DT_USBHS_MAXIMUM_SPEED` is constant, while it comes from the device tree and therefore can take different values.

**Comment by galak** [comment]
Agree with @aurel32 assessment, this is intentional because of Device Tree.
