### ISSUE TITLE
[Coverity CID :189739]Parse warnings in /subsys/usb/class/netusb/function_eem.c

### ISSUE THREAD

**Issue by mandarcthorat1** [zephyrproject-rtos/zephyr#11484]
Static code scan issues seen in File: /subsys/usb/class/netusb/function_eem.c
 Category: Parse warnings
 Function: 
 Component: Other
 CID: 189739
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by nashif** [comment]
fixed, CONFIG_USB_DEVICE_NETWORK_DEBUG_LEVEL was undefined, now it is removed.
