### ISSUE TITLE
Printk processed by logger overwrites each other

### ISSUE THREAD

**Issue by Qbicz** [zephyrproject-rtos/zephyr#11495]
**Describe the bug**
Enabled processing of printk messages by logger: `LOG_PRINTK=y`, with RTT backend, two subsequent printk calls without line break. Effect: second message is printed from beginning of the line and overwrites the first printed message.

**To Reproduce**
1. `LOG_PRINTK=y`
2. Use RTT backend to log
3. Whole log config:
```
CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=2
CONFIG_LOG_BACKEND_RTT_MODE_DROP=y
CONFIG_LOG_MODE_NO_OVERFLOW=y
CONFIG_LOG_PRINTK=y
CONFIG_LOG_PRINTK_MAX_STRING_LENGTH=256
CONFIG_LOG_PROCESS_THREAD_PRIO=10
CONFIG_LOG_BUFFER_SIZE=4096
CONFIG_LOG_BACKEND_RTT_MESSAGE_SIZE=256
CONFIG_LOG_BACKEND_SHOW_COLOR=n
CONFIG_LOG_BACKEND_FORMAT_TIMESTAMP=n

CONFIG_CONSOLE=y
CONFIG_USE_SEGGER_RTT=y
CONFIG_SEGGER_RTT_BUFFER_SIZE_UP=4096
CONFIG_RTT_CONSOLE=y
CONFIG_UART_CONSOLE=n
```
3. `printk("1: %s ", "first_printk"); printk("2: %d ", 7); printk("\n");`
4. `2: 7rst_printk`

**Expected behavior**
Printouts should come one after another.

**Impact**
Incorrect printing of logs, medium priority problem.

**Environment (please complete the following information):**
 - OS: Ubuntu 16.04 LTS
 - Toolchain: Zephyr SDK 0.9.5
 - Commit SHA or Version used: 9c14767475a68
 - HW: nRF52840

**Comment by Qbicz** [comment]
FYI @nordic-krch @pdunaj

**Comment by pdunaj** [comment]
It is possible that this bug is not yet completely fixed. Please check the comment in the PR.
