### ISSUE TITLE
Trademark not done correctly in Galileo board docs?

### ISSUE THREAD

**Issue by galak** [zephyrproject-rtos/zephyr#11516]
https://docs.zephyrproject.org/latest/boards/x86/galileo/doc/galileo.html

Has references like 'Intel |reg| Quark'  Not sure if that is for a Trademark or something.

**Comment by dbkinder** [comment]
``Intel |reg| Quark |trade|`` is translated by Sphinx into Intel® Quark™ **except** if used in a link reference or a code-block.  I'll go back through the docs looking for these and fix.  Thanks for reporting.
