### ISSUE TITLE
Get configuration of a running kernel in console

### ISSUE THREAD

**Issue by laperie** [zephyrproject-rtos/zephyr#11529]
In order to simplify debugging of certain cases it would be useful to be able to dump the configuration of a running Zephyr kernel from the console, just like /boot/config* in Linux
It would help to create an identical environment to reproduce issues remotely from the machine where the image is built. 

**Describe the solution you'd like**
A console command providing a list of config variables current kernel was built with

**Comment by pfalcon** [comment]
Storing such list in binary will east quite a lot of space, up to being impractical in majority of cases.

**Comment by nashif** [comment]
impractical
