### ISSUE TITLE
Energy-efficient BLE controller on the nRF52

### ISSUE THREAD

**Issue by spoerk** [zephyrproject-rtos/zephyr#11533]
I am interested in having a very energy-efficient BLE peripheral device based on the nRF52 platform. It is especially important for my use case that the BLE peripheral has a very low baseline current consumption (i.e. consuming only a few micro amperes when no communication is going on).

When I run the existing BLE Heartrate Peripheral sample on the nRF52840 DK, I always get a base current consumption of the SoC of about 0.4 mA. This happens even when I complete disable any logging and use a BLE connection interval of 1000 ms.

From my energy measurements with the Monsoon Power Monitor, I suspect that the nRF52 SoC does not enter its deep sleep state when BLE communication is used. Is this the case or am I missing some configuration option that enables an energy-efficient BLE SoC?

**Comment by SebastianBoe** [comment]
I suspect this is a bug and that something is keeping the HFCLK running.

**Comment by carlescufi** [comment]
@spoerk can you try disabling the UART completely?

**Comment by spoerk** [comment]
Thank you @carlescufi. Completely disabling the UART of the platform solved my problem.

**Comment by SebastianBoe** [comment]
Do we want to re-open this?

@anangl : I assume it is not expected behaviour that having UART enabled will draw 400uA.

**Comment by SebastianBoe** [comment]
Not-a-bug.

"you need to explicitly set low power for the UART by calling device_set_power_state() [...] it is the application responsibility to do power management" -- @anangl
