### ISSUE TITLE
net: arp: Zephyr does use MAC address from broadcast ARP reply

### ISSUE THREAD

**Issue by rmstoi** [zephyrproject-rtos/zephyr#11562]
If Zephyr receives unrequested broadcast ARP reply it does not update translation table. So, instead of using MAC address from request packet (ICMP, TCP, UDP) in response, it should use MAC from unrequested ARP reply.

[ipv4-unreq-arp-reply-udp.pcap.gz](https://github.com/zephyrproject-rtos/zephyr/files/2603717/ipv4-unreq-arp-reply-udp.pcap.gz)
[ipv4-unreq-arp-reply-tcp.pcap.gz](https://github.com/zephyrproject-rtos/zephyr/files/2603718/ipv4-unreq-arp-reply-tcp.pcap.gz)
[ipv4-unreq-arp-reply-icmp.pcap.gz](https://github.com/zephyrproject-rtos/zephyr/files/2603719/ipv4-unreq-arp-reply-icmp.pcap.gz)

**Comment by jukkar** [comment]
Accepting unsolicited ARP replies can be a security risk thus we do not update ARP cache if we receive them. There is a separate Kconfig option (by default it is 'n') for accepting gratuitous ARP replies but these pcap files did not contain gratuitous arp messages.
