### ISSUE TITLE
Convert remaining Kconfig symbols of devices available in dts (SPI, I2C)

### ISSUE THREAD

**Issue by erwango** [zephyrproject-rtos/zephyr#11569]
Following #11180, some CONFIG_  symbols of devices already converted to DTS remains in dts_fixup.h files:
CONFIG_I2C_X_NAME
CONFIG_SPI_X_IRQ_PRI

There are other devices impacted, like ADC, WDT... but they might not all be available in DTS.
This is different for I2C and SPI as they are available in dts and the other properties are already converted to DT_ namespace.

It apprears theyare still using CONFIG_ because they are defined in Kconfig files.
So netx steps is to remove these symbols from Kconfig and changes definitins from CONFIG_ to DT_

**Comment by carlescufi** [comment]
I think this was intentionally left out as `CONFIG_` because they still have the option to use Kconfig for platforms that do not support DT. I will let @galak confirm this.

**Comment by galak** [comment]
> I think this was intentionally left out as `CONFIG_` because they still have the option to use Kconfig for platforms that do not support DT. I will let @galak confirm this.

The SPI one needs fixing, need to look at CONFIG_I2C_X_NAME

**Comment by erwango** [comment]
What seemed strange to me is that other properties of the same devices are converted.

**Comment by galak** [comment]
> What seemed strange to me is that other properties of the same devices are converted.

Not sure why the SPI irq priority wasn't updated.  The CONFIG_I2C_X_NAME case is because I2C slave drivers need to all be updated before we can remove it.

**Comment by erwango** [comment]
> [...]The CONFIG_I2C_X_NAME case is because I2C slave drivers need to all be updated before we can remove it.

Ok, got it, txs

**Comment by erwango** [comment]
Closing the issue
