### ISSUE TITLE
net: arp: MAC address not updated if target address is not its own

### ISSUE THREAD

**Issue by rmstoi** [zephyrproject-rtos/zephyr#11579]
Zephyr does not update MAC address if it receives ARP reply which has target address that does not belong to Zephyr. Also, in this case Zephyr sends unexpected ARP request.

[ipv4-arp-reply-2ta-udp.pcap.gz](https://github.com/zephyrproject-rtos/zephyr/files/2604449/ipv4-arp-reply-2ta-udp.pcap.gz)
[ipv4-arp-reply-2ta-tcp.pcap.gz](https://github.com/zephyrproject-rtos/zephyr/files/2604450/ipv4-arp-reply-2ta-tcp.pcap.gz)
[ipv4-arp-reply-2ta-icmp.pcap.gz](https://github.com/zephyrproject-rtos/zephyr/files/2604451/ipv4-arp-reply-2ta-icmp.pcap.gz)

**Comment by jukkar** [comment]
Not sure what is suppose to happen here. For example in UDP pcap file we receive a query and reply to it. As we do not support unsolicited ARP replies, then perhaps the expected outcome by the tool is to mark the test failed.
