### ISSUE TITLE
net: icmpv4: Zephyr drops valid echo request

### ISSUE THREAD

**Issue by rmstoi** [zephyrproject-rtos/zephyr#11618]
Zephyr drops echo request with valid checksum. Zephyr must respond to valid echo request.

[icmpv4-valid-chksum2.pcap.gz](https://github.com/zephyrproject-rtos/zephyr/files/2610165/icmpv4-valid-chksum2.pcap.gz)
[icmpv4-valid-chksum1.pcap.gz](https://github.com/zephyrproject-rtos/zephyr/files/2610166/icmpv4-valid-chksum1.pcap.gz)

**Comment by jukkar** [comment]
Works for me, perhaps a glitch during the test?

**Comment by rmstoi** [comment]
That is weird, cause when I test these packets are still dropped:

```
[00:08:50.760,000] <dbg> net_ipv4.net_ipv4_process_pkt: (0x566515d0): DROP: invalid chksum
[00:08:50.760,000] <dbg> net_core.processing_data: (0x566515d0): Dropping pkt 0x56639d24

```

**Comment by tbursztyka** [comment]
Here it's the IPv4 chksum which is invalid, not the ICMPv4 one.

**Comment by rmstoi** [comment]
@tbursztyka I tried PR #14200, now echo server replies to ping, but the response has wrong id and  seq numbers. So wireshark marks request as "No response seen"

[icmpv4-valid-chksum1-pr14200.pcap.gz](https://github.com/zephyrproject-rtos/zephyr/files/2951388/icmpv4-valid-chksum1-pr14200.pcap.gz)

**Comment by tbursztyka** [comment]
@rmstoi previous echo reply build was cloning the original packet, as the un-existing ipv4 options made it assume ipv4 hdr is always same which is not. I modify the echo reply build to it only copies the payload from original packet, but builts ipv4/icmpv4 hdr properly. Should be fine now. (I quickly tried and no complaints from ws)

**Comment by rmstoi** [comment]
@tbursztyka works like charm. Thanks!
