### ISSUE TITLE
net: ipv4: udp: broadcast delivery not supported

### ISSUE THREAD

**Issue by rmstoi** [zephyrproject-rtos/zephyr#11617]
Zephyr drops UDP packet with broadcast destination IP and unicast MAC. According to RFC 1122 4.1.1 this scenarion should be supported by UDP: "... to use communications services (e.g., multicast or broadcast delivery) not available from TCP."

[ipv4-udp-bcast-dst.pcap.gz](https://github.com/zephyrproject-rtos/zephyr/files/2610099/ipv4-udp-bcast-dst.pcap.gz)

**Comment by jukkar** [comment]
Works for me, perhaps this was already fixed or there was some issue during testing. Anyway, attached is a capture of an UDP packet with broadcast destination address and it was handled by zephyr just fine.

[ipv4-udp-bcast-dst-example.pcapng.gz](https://github.com/zephyrproject-rtos/zephyr/files/2763936/ipv4-udp-bcast-dst-example.pcapng.gz)

**Comment by rmstoi** [comment]
New pcap, with correct Zephyr MAC address.

[ipv4-udp-bcast-dst2.pcap.gz](https://github.com/zephyrproject-rtos/zephyr/files/3182048/ipv4-udp-bcast-dst2.pcap.gz)
