### ISSUE TITLE
Generic GPIO reset driver

### ISSUE THREAD

**Issue by sathishkuttan** [zephyrproject-rtos/zephyr#11636]
**Is your feature request related to a problem? Please describe.**
A generic driver to use GPIOs as reset controls for [peripheral] devices.

**Describe the solution you'd like**
A generic driver conceptually similar to linux. reference: https://lwn.net/Articles/585145/

**Describe alternatives you've considered**
Using the existing GPIO driver and make calls to the config and write APIs.

**Comment by gmarull** [comment]
This can now be accomplished using the reset API (include/zephyr/drivers/reset.h).
