### ISSUE TITLE
Sensor Trigger User Data

### ISSUE THREAD

**Issue by teburd** [zephyrproject-rtos/zephyr#11666]
**Is your feature request related to a problem? Please describe.**
Currently there's no obvious way to attach user data to sensor trigger callbacks.

**Describe the solution you'd like**
Option 1: set_sensor_trigger should store the pointer to the trigger struct rather than copying it enabling the usage of CONTAINER_OF on the trigger pointer given in the trigger callback.
 Option 2: allow a user data void * to be set as part of the sensor trigger struct to allow for trigger callbacks to access user data in some manner

I have no personal preference to the solution chosen, but updated documentation and samples mentioning how to attach user data would be greatly appreciated

**Comment by henrikbrixandersen** [comment]
> Option 1: set_sensor_trigger should store the pointer to the trigger struct rather than copying it enabling the usage of CONTAINER_OF on the trigger pointer given in the trigger callback.

I'd vote for this one.

**Comment by teburd** [comment]
PRs that I believe have fixed this issue, please verify this to be correct @MaureenHelm and if not we can reopen this.

#55566
#56123
#56668

**Comment by MaureenHelm** [comment]
> PRs that I believe have fixed this issue, please verify this to be correct @MaureenHelm and if not we can reopen this.
> 
> #55566 #56123 #56668

Yes, thanks @teburd
