### ISSUE TITLE
Cannot set UART device name in menuconfig

### ISSUE THREAD

**Issue by finikorg** [zephyrproject-rtos/zephyr#11675]
menuconfig option disappeared and now I cannot set specific UART for the console.

**Comment by carlescufi** [comment]
@finikorg can you paste the name of the Kconfig option that disappeared?

**Comment by carlescufi** [comment]
`zephyr, console = &uartX` to change it now

**Comment by carlescufi** [comment]
If your board uses Device Tree then the assignment happens in the `dts` file and overlays. Closing this since we have concluded that using `chosen` nodes is the right approach for this.
