### ISSUE TITLE
ci: 'MIT' license verification fail on permissive license

### ISSUE THREAD

**Issue by b0661** [zephyrproject-rtos/zephyr#11671]
**Describe the bug**

PR #10885 contains files that are licensed **"mit"** ( see https://spdx.org/licenses/MIT.html). This is a much more permissive license than apache-2.0.  It should not make CI fail.

**To Reproduce**

Add a file wirh "SPDX-License-Identifier: mit" and run CI.

**Expected behavior**

CI license verification shall pass on  "SPDX-License-Identifier: mit".

**Impact**

CI of PR #10885, #10888 declared failed.

**Screenshots or console output**

PR #10885

**Environment (please complete the following information):**

Zephyr CI

**Additional context**

**Comment by nashif** [comment]
Any file going into the zephyr tree with a different license that the project license needs to be reviewed. This check in CI is currently not 'required' for merging and still under heavy development, so a maintainer can override this check after reviewing the warnings and determining that the files are ok.

Will add some text explaining the above in the comment posted by CI.

**Comment by b0661** [comment]
Reviewers usually do not review until the CI status is "passed". 

Can this become a hint for reviewers and CI set to "passed"?

**Comment by nashif** [comment]
We now add more information about the license scan, any license warning need to be reviewed and processed by someone, making them PASS is just going to be misleading. Those who merge can always override the check. My concern is that if we make it PASS, nobody will look at the warnings of non APL licensed files we are pulling into the tree.
