### ISSUE TITLE
Wrong assert condition @@zephyr/kernel/sched.c:345

### ISSUE THREAD

**Issue by ajaykish** [zephyrproject-rtos/zephyr#11674]
kernel.pipe.bench: assertion fails on qemu_x86, due to wrong assert condition at zephyr/kernel/sched.c:345
__ASSERT_NO_MSG(thread == _current ||  _is_thread_dummy(thread));
Issue found using the PR #11650

cd tests/kernel/pipe/pipe_api/
mkdir build
cd build
cmake -D BOARD=qemu_x86 -GNinja ../
ninja run

Console log:
starting test - test_bench
ASSERTION FAIL [thread == _kernel.current || _is_thread_dummy(thread)] @zephyr/kernel/sched.c:345:

Additional Information:
Correct assert condition should be:
__ASSERT_NO_MSG(thread != _current || !_is_thread_dummy(thread));

**Comment by andyross** [comment]
No, this code is correct.  You're allowed to pend yourself.  You're allowed to pend a DUMMY thread (becuase that somewhat ugly trick is used by the existing IPC code to "wake up" things that aren't threads).  You can't pend a third thread, becuase on SMP it might be running (or about to run).   This assertion is there to detect that.
