### ISSUE TITLE
hello world build fail on windows power shell

### ISSUE THREAD

**Issue by jsplyy** [zephyrproject-rtos/zephyr#11688]
**hello world build fail on windows power shell**
![image 3](https://user-images.githubusercontent.com/3600912/49088569-7e216700-f294-11e8-8cbb-32df1da82601.png)

Have installed cmake ninja and armgcc, still build fail, do not know how to do.

**Comment by SebastianBoe** [comment]
Hi the environment variable ZEPHYR_BASE is not set.

https://stackoverflow.com/questions/47081317/zephyr-cmake-error
