### ISSUE TITLE
Invalid hyperlink in some README pages

### ISSUE THREAD

**Issue by jsplyy** [zephyrproject-rtos/zephyr#11683]
**Invalid hyperlink in some README pages**

**To Reproduce**
1. https://github.com/zephyrproject-rtos/zephyr/tree/master/samples/bluetooth/hci_uart#id1
2. https://github.com/zephyrproject-rtos/zephyr/tree/master/samples/bluetooth/beacon

**Expected behavior**
link is invalid in these read pages.
![image 2](https://user-images.githubusercontent.com/3600912/49082416-aacd8280-f284-11e8-81a9-12a485054548.png)

**Comment by carlescufi** [comment]
This is not an invalid link. We use `rst` to format documentation but GitHub doesn't render it properly. Instead of browsing it on GitHub, you should browse it on the documentation website:

https://docs.zephyrproject.org/latest/samples/bluetooth/beacon/README.html

**Comment by carlescufi** [comment]
@jsplyy thanks for reporting, I am planning to add a FAQ in the docs and I will include this.

**Comment by jsplyy** [comment]
Thanks a lot. @carlescufi
