### ISSUE TITLE
How to be compatible with python2 on windows

### ISSUE THREAD

**Issue by jsplyy** [zephyrproject-rtos/zephyr#11689]
**How to be compatible with python2 on windows**
I have enable python3 env for zephyr, but it still find python2 in my PC when start to build project. How to config? 
Thanks
![image 5](https://user-images.githubusercontent.com/3600912/49088739-e40dee80-f294-11e8-963a-d8510159add7.png)

**Comment by SebastianBoe** [comment]
@jsplyy : If you look through the documentation for setting up a Windows environment you should find some reference to dtc.
