### ISSUE TITLE
i2c: nrf5x: unable to write data in I2C slave 

### ISSUE THREAD

**Issue by vikrant8051** [zephyrproject-rtos/zephyr#11720]
Hello,

**Board:** nRF52840_PCA10056
**Demo eg. used for testing:** zephyr/samples/drivers/i2c_fujitsu_fram

**Changes made to make it compatible for nRF52840:**
1) In main.c, modified Device Driver name from **CONFIG_I2C_0_NAME** to **DT_I2C_0_NAME**
   (This was nowhere mentioned in any documentation)
2) Add following Kconfig in prj.conf:
>    CONFIG_I2C=y
>    CONFIG_I2C_NRFX=y
>    CONFIG_I2C_0_NRF_TWI=y
>    CONFIG_I2C_INIT_PRIORITY=60
>    CONFIG_I2C_0=y

Here I observed that we could read data from I2C slave but can't write any data (single byte or multiple byte in one shot) in slave's internal memory location.

Driver doesn't return any error after write but if we read data back for comparison then it concludes that write has not successful.

**Comment by pabigot** [comment]
See #11612.  Looks like the i2c-fujitsu_fram code uses i2c_transfer, which does not send both the register and the payload in the same transaction.

**Comment by carlescufi** [comment]
Duplcate of #11612
