### ISSUE TITLE
logging: default log thread priority is too high

### ISSUE THREAD

**Issue by andrewboie** [zephyrproject-rtos/zephyr#11749]
**Describe the bug**
The logging thread currently has a default priority of -2, which is a fairly high non-preemptible priority.

**To Reproduce**
Kconfig inspection

**Expected behavior**
The logging thread should default to something very low. K_LOWEST_APPLICATION_THREAD_PRIO would be a good default. Do we even need this to be a tuneable parameter?

**Impact**
Advantages of deferred logging are lost as the background logging thread will preempt all preemptive threads and also be higher priority than some non-preemptive threads.

**Comment by nashif** [comment]
> Do we even need this to be a tuneable parameter?

I vote for this to be fixed and not configurable.
