### ISSUE TITLE
watchdog sample application not being built on Nordic devices

### ISSUE THREAD

**Issue by pabigot** [zephyrproject-rtos/zephyr#11779]
In PR #10377 the nrf infrastructure switched to using a device tree alias for watchdog, including changing the dts_fixup to use `DT_WDT_0_NAME`.

Unfortunately the change was isolated to the Nordic driver code, with a consequence that `samples/drivers/watchdog` no longer builds on Nordic hardware.  All other platforms that support watchdog are still using `CONFIG_WDT_0_NAME`, as does the driver API test application.

**Comment by carlescufi** [comment]
@anangl @kl-cruz would you please take a look at this?

**Comment by kl-cruz** [comment]
Okay, it should be only code alignment

**Comment by pabigot** [comment]
Should be resolved by #12468.
