### ISSUE TITLE
Update the sample/net/coap_client

### ISSUE THREAD

**Issue by chtavares592** [zephyrproject-rtos/zephyr#11771]
I'm developing an application in coap and I use the master of zephyr. I wonder if it would be possible for someone to update the sample from net / coap to coap_sock. So that I can base and apply the changes on my application. Thank you

**Comment by rveerama1** [comment]
This coap_client sample (https://github.com/zephyrproject-rtos/zephyr/tree/master/samples/net/sockets/coap_client) is based on COAP_SOCK.
