### ISSUE TITLE
Add Bluetooth support for Silicon Labs EFR32MG12

### ISSUE THREAD

**Issue by Puchinger** [zephyrproject-rtos/zephyr#11773]
I would like to use zephyr on the EFR32MG12 from Silicon Labs to build a Bluetooth Mesh Network.
Is there a way to use Bluetooth on EFR32MG12 which I have overlooked?
If not will there be a support in the near future?

Thanks
Thomas

**Comment by carlescufi** [comment]
@Puchinger this is not possible unless Silicon Labs provides a library or register descriptions. I encourage you to ask them directly.

**Comment by ekarlso** [comment]
@carlescufi RAIL lib I guess ?
