### ISSUE TITLE
A thread may lock a mutex before it is fully unlocked.

### ISSUE THREAD

**Issue by nicber** [zephyrproject-rtos/zephyr#11798]
**Describe the bug**
My team was trying to get Zephyr 1.13 to run on a RISC-V soft core we designed and implemented for the RISC-V Contest https://riscv.org/2018contest/ when we hit a bug in Zephyr.
After running the philosophers sample for some time the kernel fails like this:

`ASSERTION FAIL [mutex->owner == _kernel.current] @ /usr/local/share/zephyr/kernel/mutex.c:215:`

The issue is in this part of _impl_k_mutex_unlock:
```
	mutex->lock_count--;

	K_DEBUG("mutex %p lock_count: %d\n", mutex, mutex->lock_count);

	if (mutex->lock_count != 0) {
		k_sched_unlock();
		return;
	}

	key = irq_lock();

	adjust_owner_prio(mutex, mutex->owner_orig_prio);

	struct k_thread *new_owner = _unpend_first_thread(&mutex->wait_q);

	mutex->owner = new_owner;
```
What happens is:
Thread A:
1) It tries to unlock a mutex it is holding. 
2) `mutex->lock_count` is set to 0.
3) The thread recalculates its own priority.
4) At sometime thread B, which has a higher priority than A, becomes eligible to run
4) It calls `_thread_priority_set()` to reorder the run queue setting thread B first.
5) It calls `_reschedule()` and `_Swap()`s to B.
Thread B:
6) B calls `_impl_k_mutex_lock()` on the mutex A was holding.
7) B sees `mutex->lock_count == 0` and sets itself as its owner.
8) For some reason B is swapped and A starts running.
Thread A:
9) It is still in the `` function. It calls `_unpend_first_thread()` and gets thread C that was in the queue to lock the mutex.
10) A sets C as the owner of the mutex.

From this point on both B and C think they own the mutex. 
The assert is triggered when C tries to unlock the mutex after B unlocked it (it sets owner to NULL), or viceversa.

**To Reproduce**
1) Change the philosophers example.

```diff
@@ -183,7 +183,7 @@ void philosopher(void *id, void *unused1, void *unused2)
 		print_phil_state(my_id, "   HOLDING ONE FORK   ", 0);
 		take(fork2);

-		delay = get_random_delay(my_id, 25);
+		delay = get_random_delay(my_id, 2);
 		print_phil_state(my_id, "  EATING  [ %s%d ms ] ", delay);
 		k_sleep(delay);

@@ -191,7 +191,7 @@ void philosopher(void *id, void *unused1, void *unused2)
 		print_phil_state(my_id, "   DROPPED ONE FORK   ", 0);
 		drop(fork1);

-		delay = get_random_delay(my_id, 25);
+		delay = get_random_delay(my_id, 1);
 		print_phil_state(my_id, " THINKING [ %s%d ms ] ", delay);
 		k_sleep(delay);
 	}
```

2) Compile it with `cmake -GNinja -DBOARD=qemu_riscv32 ..` and run it with `ninja run`.
After a few seconds you should see the assert fail.

**Environment (please complete the following information):**
 - Zephyr 1.13 compiled for RV32I.

**Comment by nicber** [comment]
```diff
diff --git a/kernel/mutex.c b/kernel/mutex.c
index e3f3584ba..b7d9a7efd 100644
--- a/kernel/mutex.c
+++ b/kernel/mutex.c
@@ -221,11 +221,11 @@ void _impl_k_mutex_unlock(struct k_mutex *mutex)

        RECORD_STATE_CHANGE();

-       mutex->lock_count--;

        K_DEBUG("mutex %p lock_count: %d\n", mutex, mutex->lock_count);

-       if (mutex->lock_count != 0) {
+       if (mutex->lock_count - 1 != 0) {
+               mutex->lock_count--;
                k_sched_unlock();
                return;
        }
@@ -253,9 +253,10 @@ void _impl_k_mutex_unlock(struct k_mutex *mutex)
                 * waiter since the wait queue is priority-based: no need to
                 * ajust its priority
                 */
-               mutex->lock_count++;
                mutex->owner_orig_prio = new_owner->base.prio;
-       }
+       } else {
+               mutex->lock_count = 0;
+       }

        irq_unlock(key);
```

This patch works for me.

**Comment by carlescufi** [comment]
@nicber thanks for the report and the patch. Would you mind sending a Pull Request with the patch?

**Comment by andyross** [comment]
I think that looks right.  Our mutex implementation (which, to be clear, is a priority inheriting mutex -- a somewhat oddball kind of thing that most apps don't want, routine blocking mutual exclusion should be done with semaphores) is subtle and worrisome.  And honestly our test coverage of it is quite a bit weaker than the more common IPC primitives.

Yes, let's please get this submitted as  PR.

**Comment by walter-xie** [comment]
I have a doubt: in step 4, the schedule is locked, why the thread B becomes eligible to run?
