### ISSUE TITLE
cmake: CMake 3.13 doesn't like INTERFACE with target_link_libraries

### ISSUE THREAD

**Issue by yashi** [zephyrproject-rtos/zephyr#11794]
**Describe the bug**
CMake 3.13 start complaining about CMP0079: `target_link_libraries()` allows use with targets in other directories.

**To Reproduce**
Just make for some board.

**Expected behavior**
No warning while build

**Impact**
It builds fine but prints the warning a few times.

**Screenshots or console output**
```
CMake Warning (dev) at zephyr/cmake/extensions.cmake:837 (target_link_libraries):
  Policy CMP0079 is not set: target_link_libraries allows use with targets in
  other directories.  Run "cmake --help-policy CMP0079" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  Target

    zephyr_interface

  is not created in this directory.  For compatibility with older versions of
  CMake, link library

    -ldl

  will be looked up in the directory in which the target was created rather
  than in this calling directory.
Call Stack (most recent call first):
  zephyr/cmake/extensions.cmake:1055 (target_link_libraries_ifdef)
  zephyr/cmake/extensions.cmake:115 (target_ld_options)
  zephyr/arch/posix/CMakeLists.txt:30 (zephyr_ld_options)
This warning is for project developers.  Use -Wno-dev to suppress it.
```

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: CMake 3.13.1
 - Commit SHA: d38aa1f

**Comment by SebastianBoe** [comment]
I believe we want to short-term use the cmake_policy() command to set this policy to OLD, and then later on, when necessary, port the code-base to the NEW behaviour and set the policyt to NEW.

**Comment by tejlmand** [comment]
> I believe we want to short-term use the cmake_policy() command to set this policy to OLD, and then later on, when necessary, port the code-base to the NEW behavior and set the policy to NEW.

basically there is no porting needed if allowing the new behavior, current code works on `CMP0079 NEW`. The reason to state `CMP0079 OLD` is in order to still allow users to use CMake versions 3.8.2 - 3.13
