### ISSUE TITLE
sockets: Implement (POSIX-compatible) timeout support

### ISSUE THREAD

**Issue by pfalcon** [zephyrproject-rtos/zephyr#11820]
It's not possible to implement a robust networking solution without timeouts. So, sockets should implement them, following the POSIX mandated API.

**Comment by pfalcon** [comment]
@rlubos: FYI, let's have an explicit ticket on this.

**Comment by rlubos** [comment]
Ack, thanks.

**Comment by hubertmis** [comment]
#31369 fixed only receiving part of this issue. Sending part is still open.
