### ISSUE TITLE
Assert invoked in exception in ctrl.c line 7653 (zephyr 1.13.00)

### ISSUE THREAD

**Issue by alexsven** [zephyrproject-rtos/zephyr#11841]
Assert gets invoked when having one connection and starting another. Spoke to @cvinayak about this and it seems the new connection wants to resize the rx_pool while it's still in use by the first connection. 
`if (_radio.packet_rx_data_count != free_count_rx) {
  /** TODO another role instance has obtained
    * memory from rx pool.
    */
    //LL_ASSERT(0);
} `

**Comment by carlescufi** [comment]
@cvinayak can you comment on this issue?

**Comment by cvinayak** [comment]
@alexanderwachter @carlescufi this is a bug and needs fix (redesign, as I dont like the current implementation anyway) which I will work alongwith the design to be put in place for the split architecture work.

**Comment by carlescufi** [comment]
@cvinayak so this will be fixed in the new split controller only?

**Comment by cvinayak** [comment]
@alexanderwachter commenting the assert has unblocked your usecase right? I think subsequent code must be handling/deferring the data resize gracefully, right?

**Comment by alexanderwachter** [comment]
I think you guys have a little typo with the names. @alexanderwachter should be @alexsven ;-)

**Comment by alexsven** [comment]
@cvinayak Yes, it unblocked our usecase.

**Comment by carlescufi** [comment]
@cvinayak can you update on this one please?

**Comment by cvinayak** [comment]
@alexsven could you verify #14553 ?
