### ISSUE TITLE
blinky example can't work on nucleo-f070rb and nucleo-f030r8 platform

### ISSUE THREAD

**Issue by qianfan-Zhao** [zephyrproject-rtos/zephyr#11904]
**Describe the bug**
samples/basic/blinky Example can't work on nucleo-f070rb and nucleo-f030r8 platform(the led can't blinking after download), but the hello_world example can work.

**To Reproduce**
1. mkdir build; cd build
2. cmake -DBOARD=nucleo_f070rb ..
3. make
4. make flash

**Comment by erwango** [comment]
Seems fixing BUS in stm32f0.dtsi fixes the issue:
```
 			gpioa: gpio@48000000 {
 				compatible = "st,stm32-gpio";
 				gpio-controller;
 				#gpio-cells = <2>;
 				reg = <0x48000000 0x400>;
-				clocks = <&rcc STM32_CLOCK_BUS_AHB2 0x00020000>;
+				clocks = <&rcc STM32_CLOCK_BUS_AHB1 0x00020000>;
```

Though, in that case console should not be working neither.
With the change console is still working...
There is definitly something strange here.

**Comment by erwango** [comment]
AHB2 bus is actually not supported on F0 series.
Things (eg hello_world) should be working as AHB1 bus is activated by request from other subsystem.
Will submit a patch to fix this and add various check points to detect this kind of issues earlier in future
