### ISSUE TITLE
logger: rtt: Output is no longer 'utf-8' but ISO-8859-1

### ISSUE THREAD

**Issue by Qbicz** [zephyrproject-rtos/zephyr#11909]
**Describe the bug**
We used to parse the RTT output from logger in our automated high-level testing. However, yesterday an error occured:
```
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd3 in position 381: invalid continuation byte
```
After changing encoding to ISO-8859-1 this works again.

**To Reproduce**
We use `pynrfjprog` to read RTT using `utf-8` default encoding.
https://github.com/NordicSemiconductor/pynrfjprog/blob/master/pynrfjprog/API.py#L1193

Log configuration:
```
CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=2
CONFIG_LOG_BACKEND_RTT=y
CONFIG_LOG_BACKEND_RTT_MODE_DROP=y
CONFIG_LOG_MODE_NO_OVERFLOW=y
CONFIG_LOG_PRINTK=y
CONFIG_LOG_PRINTK_MAX_STRING_LENGTH=256
CONFIG_LOG_BUFFER_SIZE=4096
CONFIG_LOG_BACKEND_RTT_MESSAGE_SIZE=256
CONFIG_LOG_BACKEND_SHOW_COLOR=n
CONFIG_LOG_BACKEND_FORMAT_TIMESTAMP=n

CONFIG_CONSOLE=y
CONFIG_USE_SEGGER_RTT=y
CONFIG_SEGGER_RTT_BUFFER_SIZE_UP=4096
CONFIG_RTT_CONSOLE=y
CONFIG_UART_CONSOLE=n
```

**Environment (please complete the following information):**
 - 0da5d24c36f48

**Comment by Qbicz** [comment]
Update: the problem happens for showing string `%s` with logger.
```
	char addr[BT_ADDR_LE_STR_LEN];
	bt_addr_le_to_str(bt_conn_get_dst(conn), addr, sizeof(addr));
	LOG_INF("Connected to %s", addr);
```
```
[00086194] <inf> ble.connected: Connected to U�
```
Buffer content is correct and can be displayed with printk.
```
Connected to 88:83:22:3e:9a:6c (public)
```

I can reproduce it on application with large number of logged messages. I cannot reproduce it on Zephyr sample with exactly same logger configuration.

**Comment by jhedberg** [comment]
@Qbicz what you're getting is no surprise since the string is a stack variable that's out of scope by the time the logging thread processes the message. You'd need to use log_strdup() to get a string that's persistent until the logging thread processes it (it will also auto-free the string).

**Comment by Qbicz** [comment]
Thanks @jhedberg. Duplicating the string solves the problem:
```
LOG_INF("Logging transient string:%s", log_strdup(transient_str));
```

So the logger automatically creates a copy of stack integers, but for strings it needs to be told what to do.

**Comment by jhedberg** [comment]
> So the logger automatically creates a copy of stack integers, but for strings it needs to be told what to do.

Pretty much yes. The logger doesn't differentiate at all with the parameters that come after the format string - it just copies the value of each one regardless of the type. So when you give it a pointer it just stores the pointer value for later processing, i.e. it has no knowledge of the persistency of the data that the pointer is referring to.
