### ISSUE TITLE
CMake error when deselecting "UART Port 0 Driver type"

### ISSUE THREAD

**Issue by oxymoron87** [zephyrproject-rtos/zephyr#11932]
**Describe the bug**
CMake error when deselecting "UART Port 0 Driver type" in Device Drivers -> Serial Drivers -> nRF UART nrfx drivers (through menuconfig).

**To Reproduce**
1. mkdir build; cd build
2. cmake -GNinja -DBOARD=nrf52840_pca10056 ..
3. ninja menuconfig
4. deselect Device Drivers -> Serial Drivers -> nRF UART nrfx drivers -> UART Port 0 Driver type
3. ninja

**Screenshots or console output**
`CMake Error at zephyr/CMakeLists.txt:674 (message):`
`  The Zephyr library 'drivers__serial' was created without source files.`
`  Empty (non-imported) libraries are not supported.  Either make sure that`
`  the library has the sources it should have, or make sure it is not created`
`  when it has no source files.`

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: GNU ARM GCC
 - Commit 48f493208baf4d7e6d8f72b1473889b2cc9fcbcb

**Comment by jarz-nordic** [comment]
@oxymoron87 :In my opinion it is expected behavior. You've selected that you want to use serial but you did not choose a driver. It seems to be related to your other issue: #11928. Do you still consider this PR as an issue?

**Comment by jarz-nordic** [comment]
@oxymoron87 : Please let me know if this is still an issue for you or it can be closed?

**Comment by oxymoron87** [comment]
I just thought that UI (menuconfig) should not let me to do so, but that's my opinion.  Not an issue anymore.

**Comment by carlescufi** [comment]
@oxymoron87 unfortunately there's a bit more coupling between Device Tree and Kconfig than it might be apparent. We are working towards improving the user experience, and we are aware of this issue, thanks for letting us know!
