### ISSUE TITLE
Invalid usage of k_busy_wait()

### ISSUE THREAD

**Issue by pizi-nordic** [zephyrproject-rtos/zephyr#11935]
**Describe the bug**
Most of the timing APIs in Zephyr uses ms as a time unit. There are also several macros, which converts other time units to milliseconds. However the `k_busy_wait()` uses us as a unit, so all these helpers cannot be directly used with this call. Unfortunately this subtle difference is missed in few places in Zephyr.

- `drivers/display/ssd1673.c:  k_busy_wait(SSD1673_BUSY_DELAY);`
   The SSD1673_BUSY_DELAY is specified in ms according to comment before this define.
- `tests/kernel/interrupt/src/nested_irq.c: k_busy_wait(K_SECONDS(..));`
   (refereed in https://github.com/zephyrproject-rtos/zephyr/issues/10509)
- `drivers/wifi/winc1500/wifi_winc1500_nm_bsp.c: k_busy_wait(u32TimeMsec * MSEC_PER_SEC)`
   This one works as expected, but IMHO should be corrected.

**Comment by nashif** [comment]
> * `drivers/display/ssd1673.c:  k_busy_wait(SSD1673_BUSY_DELAY);`
>   The SSD1673_BUSY_DELAY is specified in ms according to comment before this define.

was fixed by d0afacc6b4d
