### ISSUE TITLE
Ble mesh stack not compatible with c++

### ISSUE THREAD

**Issue by rokobert** [zephyrproject-rtos/zephyr#11940]
To @jhedberg 
If I include BLE mesh stack into project, it is not possible to compile with c++ compiler.

Header files of BLE Stack are not equiped with extern "C".

Header files must be equiped with macros.
#ifdef __cplusplus
extern "C"{
#endif

#ifdef __cplusplus
}
#endif

**Comment by jhedberg** [comment]
@rokobert were you still planning to submit a pull request yourself for this? You indicated that you might do that in our email exchange a few weeks ago.
