### ISSUE TITLE
Reel Board mesh_badge sample | Light sensor bug

### ISSUE THREAD

**Issue by mrobotby** [zephyrproject-rtos/zephyr#11989]
**Describe the bug**
When the reel board is under the bright light, program stops working. 

**To Reproduce**
1. Upload mesh_badge sample
2. Choose screen with telemetry of the sensors
3. Put reel board under very bright light. Data reading will stop.
4. Remove under the bright light, program continue running.

**Screenshots or console output**
Video of the bug: https://youtu.be/hl9D_isKBhQ

**Environment (please complete the following information):**
 - OS: Xubuntu, the latest pull from the zephyr repo.
 - Zephyr SDK

**Comment by jfischer-phytec-iot** [comment]
I can reproduce it, below a workaround for non trigger mode, a fix is in progress but it will take more time for testing

```diff
index acb5ee4685..6e1cac2a9d 100644
--- a/drivers/sensor/apds9960/apds9960.h
+++ b/drivers/sensor/apds9960/apds9960.h
@@ -184,8 +184,8 @@
 #define APDS9960_DEFAULT_WTIME         255
 #define APDS9960_DEFAULT_CONFIG1       0x60
 #define APDS9960_DEFAULT_AGAIN         APDS9960_AGAIN_4X
-#define APDS9960_DEFAULT_PERS          0x11
-#define APDS9960_DEFAULT_CONFIG2       0x01
+#define APDS9960_DEFAULT_PERS          0x10
+#define APDS9960_DEFAULT_CONFIG2       (BIT(6) | BIT(0))
 #define APDS9960_DEFAULT_PROX_PPULSE   0x87
 #define APDS9960_DEFAULT_GESTURE_PPULSE        0x89
 #define APDS9960_DEFAULT_POFFSET_UR    0
@@ -207,7 +207,6 @@
 #define APDS9960_DEFAULT_CONFIG3       APDS9960_CONFIG3_SAI
 #endif
 
-#define APDS9960_DEFAULT_CONFIG2       0x01
 #define APDS9960_DEFAULT_GPENTH                40
 #define APDS9960_DEFAULT_GEXTH         30
 #define APDS9960_DEFAULT_GCONF1                0x40

```
