### ISSUE TITLE
Make icount work for real on x86_64

### ISSUE THREAD

**Issue by andyross** [zephyrproject-rtos/zephyr#12027]
The x86_64 port still doesn't quite work with qemu's -icount feature.  But it's very close.  Everything but the timer interrupt seems solid: there is a case where long-running tests will eventually get into a state where interrupts are being dropped.  The issues are probably similar on other platforms.

I dug very briefly into the qemu code, at least far enough to find the spot in the interpreter loop where current interrupt status gets checked vs. timeouts.  It seems like this should be fixable, and I've developed enough expertise on the emulated timer hardware that we should probably keep on this while it's still in my head.

Alternatively, we could come up with a framework so that tests known to work well with -icount (only about 35% are failing with it right now, which pleasingly doesn't overlap much with the tests where we see spurious failures and want icount the most) get run in that mode.  That would still have a lot of benefit, in particular tests with lots of sleep time could be made to run "instantly".

**Comment by nashif** [comment]
cc @wentongwu
