### ISSUE TITLE
OS Pwr Manager doesn't put nrf52 into LPS_1

### ISSUE THREAD

**Issue by bearsh** [zephyrproject-rtos/zephyr#12025]
**Describe the bug**
Using a very simple app (`while (1) {k_sleep(MSEC_PER_SEC);}` in main thread only) with os pwr manager enabled, the lowest current consumption I get is around 700uA, which looks more like LPS_0 than LPS_1

**Expected behavior**
A sleeping SoC for almost 1s with an expected current consumption of around ~5uA rather than 700uA

**Additional context**
Running the pwr manager demo, the systems *sometimes* (not reliable) enters LPS_1.

**Comment by tautologyclub** [comment]
If you read the code for the power management example it's pretty clear this isn't a bug. You have to implement the suspend hook yourself. Suggest closing.

**Comment by bearsh** [comment]
@tautologyclub do you mean [pwer_mgr](https://github.com/zephyrproject-rtos/zephyr/blob/master/samples/subsys/power/power_mgr)? I can't find any reference to a hook I have to implement. Just to make it clear, this issue is about 'OS Power Management' which should enter the appropriate sleep state 'by itself', see also [power.c](https://github.com/zephyrproject-rtos/zephyr/blob/master/subsys/power/power.c)

**Comment by pizi-nordic** [comment]
There are no low power states in nRF5x SoCs. The https://github.com/zephyrproject-rtos/zephyr/blob/master/samples/subsys/power/power_mgr example introduces them artificially in order to show the OS-based policies.

There is no magic switch which reduces power consumption to XX uA in your design.
And there never will be one.

**Comment by bearsh** [comment]
@pizi-nordic ok, let's not name them LPS_x (as I just notived, commit f04a4c9deb55400571fd567c8ed1378015e18a24 removed that naming). but without any magic switch, running the simple application mentioned in the description and have the pm handled by the kernel (logging etc. disabled) shouldn't end up in a current consumption of 700uA.

**Comment by carlescufi** [comment]
@pizi-nordic @pabigot is this still a valid issue?

**Comment by pabigot** [comment]
A year later I don't think this is worth keeping open.  Currently controlling power is mostly manual, and the referenced sample has been replaced by `samples/boards/system_off` which shows (crudely) how to do it for Nordic.  At some point this will be done automatically, but it's an ongoing process being tracked elsewhere (e.g. entry point at #24228).
