### ISSUE TITLE
clock_control: API should allow callback to be specified

### ISSUE THREAD

**Issue by masz-nordic** [zephyrproject-rtos/zephyr#12039]
When starting the clock asynchronously, there is no way to specify an additional callback function to propagate clock events to application.

API should include an optional registration of a handler that would be called when clock event (for example `HF_CLOCK_STARTED`) is triggered.

**Comment by cvinayak** [comment]
@carlescufi @pizi-nordic I agree on the requirement, but this needs API discussion and porting across various architectures and SoC from multiple vendors.

**Comment by pizi-nordic** [comment]
@cvinayak: That is true. The implementation must be generic. I will try to raise this topic on API meeting.

**Comment by carlescufi** [comment]
@pizi-nordic maybe you could propose an (optional) API that we could use, implementing it initially only on Nordic devices?

**Comment by pizi-nordic** [comment]
@carlescufi: OK.
