### ISSUE TITLE
Shippable parallel builders appear to be unbalanced

### ISSUE THREAD

**Issue by pfalcon** [zephyrproject-rtos/zephyr#1203]
I believe some time ago there was a switch from 2 to 3 build slaves on Shippable, to parallelize CI better. As of now, they're not well aligned however, e.g. https://app.shippable.com/github/zephyrproject-rtos/zephyr/runs/3547/summary/console :

3547.1 Tests 516  / 0  / 0  / 0
3547.2 Tests 516  / 0  / 0  / 0
3547.3 Tests 3  / 0  / 0  / 0

Perhaps, there was a drop in the number of tests built?

**Comment by nashif** [comment]
> Perhaps, there was a drop in the number of tests built?

No, this is as expected. Minion No. 3 builds the documentation and will be doing a few other things beside sanitycheck.

**Comment by pfalcon** [comment]
Ok, closing.
