### ISSUE TITLE
nrf52840 ram retention example failed

### ISSUE THREAD

**Issue by Jiurifei** [zephyrproject-rtos/zephyr#12037]
Greetings,

I want to  use a global variable to store a status value .  It can be reserved even if I execute reset operation. I referred to  nRF52840 documentary, and I got following information:

### The RAM power control registers are used for configuring the following:
What RAM sections to be retained during System OFF
What RAM sections to be retained and accessible during System ON
In System OFF, retention of a RAM section is configured in the RETENTION field of the corresponding register RAM[n].POWER (n=0..8).
In System ON, retention and accessibility for a RAM section is configured in the RETENTION and POWER fields of the corresponding register RAM[n].POWER (n=0..8).### 

![nrf_power1](https://user-images.githubusercontent.com/43055877/49862620-83a4b280-fe39-11e8-82f5-ddb776c18b5b.png)

![nrf_power](https://user-images.githubusercontent.com/43055877/49861698-6cfd5c00-fe37-11e8-95ab-8ef257acf8bd.png)

So, in order to achieve this funtion,  I do the following job:
NRF_POWER->RAM[NRF_POWER_RAMBLOCK0].POWER |=NRF_POWER_RAMPOWER_S0RETENTION_MASK;

NRF_POWER->RAM[NRF_POWER_RAMBLOCK0].POWER SET|=NRF_POWER_RAMPOWER_S0RETENTION_MASK;

I make sure that the global variable is within the ram section. but every time I press reset button, the value would change. I feel very confused! Who can give me some advice?

Thanks,

Jiurifei

**Comment by SebastianBoe** [comment]
You might want to use a NRF_POWER-GPREGRET[] variable or a flash location instead.

Anyway, probably, something is clearing the variable during the boot procedure. You need to make sure it is not placed in a section that is modified during the boot procedure, e.g. it should not be in the bss or data section.

**Comment by Jiurifei** [comment]
@SebastianBoe Thank you for your suggestion. In fact we don't gvie top priority to flash storage. From your advice, I have thought that ram control strategy is divided into two aspects: hardware and software. operating register is the operation at hardware layer. And if  I do nothing at software layer, the ram can also change, e.g, reset. Am  I right？ please let me know.

**Comment by SebastianBoe** [comment]
It's difficult to understand what you are saying, but it sounds about right.

**Comment by SebastianBoe** [comment]
Closing as resolved.
