### ISSUE TITLE
docs: Weird rendition of Apache license reference on the docs start page

### ISSUE THREAD

**Issue by pfalcon** [zephyrproject-rtos/zephyr#1204]
At https://www.zephyrproject.org/doc/index.html , text "Apache 2.0 license" is rendered in a weird way for me: word "Apache" is normal font, while "2.0 license" is bold. It's rendered in the same way both in Firefox and Chromium.

The HTML markup of that looks "normal":

~~~
<span class="pre">Apache</span> <span class="pre">2.0</span> <span class="pre">license</span>
~~~

So, apparently some weird issue with CSS.

**Comment by dbkinder** [comment]
How odd.  Looks to be an issue with the :download: directive CSS style that puts the "download symbol" before the link (and that CSS code that does this is a mess). I'll just change this reference use a nice link to the LICENSE in the GitHub repo instead.  This also would fix an annoyance that the downloaded file has Linux line endings so if you're on a Windows system and open the file with notepad (for example), the line wrapping is all off.
