### ISSUE TITLE
LOG_PANIC never returns if RTT is disconnected

### ISSUE THREAD

**Issue by pdunaj** [zephyrproject-rtos/zephyr#12051]
**Describe the bug**
When RTT is connected LOG_PANIC ends at some point. When RTT is disconnected it does not.

**To Reproduce**
Use LOG_PANIC with JLink disconnected.

**Expected behavior**
LOG_PANIC should never lock.

**Impact**
LOG_PANIC deadlocks so application cannot finish its activities.

**Environment (please complete the following information):**
- rev `5ea8454e46208ab3fd7006e98b47ca15d5c7a450`

**Comment by pdunaj** [comment]
Hi @nordic-krch , do you know this issue?

**Comment by pdunaj** [comment]
@carlescufi I am not sure this is priority low. If panic does not work we will not be able to print messages before immediate reset and this is the place where log messages are, if not most, then very useful (e.g. to indicate reason of failure).

**Comment by nordic-krch** [comment]
@pdunaj it's related to the fact that rtt log backend is missing detection for rtt host presence (like rtt console has). I has to be added there. I will try to attack this but probably not today.

**Comment by pdunaj** [comment]
Hi @nordic-krch , I have pushed change with a fix if you can have a look.
