### ISSUE TITLE
Provide a way to flash and debug for nucleo_l4r5zi

### ISSUE THREAD

**Issue by erwango** [zephyrproject-rtos/zephyr#12094]
**Is your enhancement proposal related to a problem? Please describe.**
No flashing tool is available today for board.
It appears it has no mainline openocd support (even in upstream openocd).

**Describe the solution you'd like**
We should be able to enjoy usual flash and debug commands with this board.
Two possibilities use pyocd and/or segger.
If working, I prefer to have pyocd since it should be possible using (latest) ST-Link FW.
- New ST-Link FW version now supports pyocd. Try and check flash and debug for pyocd. If needed, proceed with required pyocd changes to get the board supported 
- If pyocd flash and debug cannot work for some reason, provide segger support bu default

**Describe alternatives you've considered**
Upstream openocd > not available

**Additional context**
Add any other context or graphics (drag-and-drop an image) about the feature request here.

**Comment by psidhu** [comment]
Just leaving this here for anyone working on this: http://openocd.zylin.com/#/c/4777/

Changes are merged into openocd. Updating the SDK is required.
