### ISSUE TITLE
Not possible to print 64 bit decimal values with minimal libc

### ISSUE THREAD

**Issue by jukkar** [zephyrproject-rtos/zephyr#12098]
It is not possible to print 64-bit integer value using various print routines using either %llu or %lld in minimal libc.
The code in lib/libc/minimal/source/stdout/prf.c says that it only supports small subset of modifiers and "long long int" is not one of them.

I am asking this as in gPTP networking code there are lot of 64-bit values, and currently it is not possible to get those printed either in shell or in logs which is quite annoying when debugging things.

**Comment by andrewboie** [comment]
> I am asking this as in gPTP networking code there are lot of 64-bit values, and currently it is not possible to get those printed either in shell or in logs which is quite annoying when debugging things.

Can you enable newlib as a workaround while you debug?

**Comment by jukkar** [comment]
Sure, I have been doing just that. But it is not just debug prints that are affected but also net-shell prints status etc information using %llu and %lld. It would be nice to get this working also with minimal libc so that we do not add this kind of artifical dependency to newlib. Anyway, if we are deprecating minimal libc in the future, I think this can be considered low priority.

**Comment by pfalcon** [comment]
With https://github.com/zephyrproject-rtos/zephyr/pull/12447, at least hex 64-bit values can be printed, which should be a good workaround for those in need.

**Comment by pabigot** [comment]
This was resolved for minimal libc when cbprintf became the standard formatter in Zephyr.
