### ISSUE TITLE
64bit architecture support

### ISSUE THREAD

**Issue by Mani-Sadhasivam** [zephyrproject-rtos/zephyr#12119]
Hello,

Just wanted to know if there is any plan ongoing for adding 64bit architecture support for Zephyr? This question is not related to any SoC architecture but rather than specific to Zephyr core.

**Comment by galak** [comment]
@andyross Can you comment on this.

**Comment by ioannisg** [comment]
64bit has been added already. @Mani-Sadhasivam pls, re-open if needed.
