### ISSUE TITLE
uint32_t type changed while compiling with minimal libc and newlibc

### ISSUE THREAD

**Issue by ehudmarvell** [zephyrproject-rtos/zephyr#1214]
Hi,

I wrote the following simple code
and compile it in both cases: while using minimal libc and newlibc
```
void main(void)
{
	uint32_t i = 1;
	printf("Hello!, i = %d\n", i);
}
```

while compiling with minimal libc uint32_t type is "**unsigned int**"
while compiling with new libc uint32_t type  is "**long unsigned int**"

so basically the code won't compile in both cases withou error, because "minimal libc" use **%d** and newlibc use **%ld**.

I also note the for minimal libc you defined it:
lib/libc/minimal/include/stdint.h: typedef unsigned int        uint32_t;

Can you advise?

Thanks a lot,
Ehud

**Comment by tbursztyka** [comment]
Hi Ehud,

You have to use Zephyr's own type, u32_t, u16_t, u8_t for the unsigned, 
s32_t ...etc  for the signed ones.
See includes/zephyr/types.h

And for more information: commit id 789081673f

These types were introduced for that reason (libc differences), among 
others.

Btw, %u should be used for an unsigned. %d is for signed integer.

Tomasz

**Comment by ehudmarvell** [comment]
Thanks, I will try
