### ISSUE TITLE
net: icmpv4: Zephyr replies to ICMPv4 echo request with broadcast destination IPv4 address

### ISSUE THREAD

**Issue by rmstoi** [zephyrproject-rtos/zephyr#12162]
Zephyr replies to ICMPv4 echo request with destination IP address set to 255.255.255.255 broadcast address.

These packets should be dropped instead.

[icmpv4-bcast-dest.pcap.gz](https://github.com/zephyrproject-rtos/zephyr/files/2690655/icmpv4-bcast-dest.pcap.gz)

**Comment by tbursztyka** [comment]
Can you detail a bit which icmpv4 packet type? (echo req?)

Note there is an option: CONFIG_NET_ICMPV4_ACCEPT_BROADCAST which is set by default (I think it should not actually). Unset it and re-run the test.

**Comment by rmstoi** [comment]
The packet is an echo request. If config CONFIG_NET_ICMPV4_ACCEPT_BROADCAST is unset the test case passes. RFC 1122 in 3.2.2.6 says "ICMP Echo Request destined to an IP broadcast or IP multicast address MAY be silently discarded." Config should probably be disabled by default.

**Comment by tbursztyka** [comment]
Thanks for testing this, let's disable it by default
