### ISSUE TITLE
net: arp: Zephyr does not use MAC address from unicast ARP reply

### ISSUE THREAD

**Issue by rmstoi** [zephyrproject-rtos/zephyr#12179]
If Zephyr receives unrequested unicast ARP reply it does not update translation table. So, instead of using MAC address from request packet (ICMP, TCP, UDP) in response, it should use MAC from unrequested ARP reply.

[unreq-arp-reply-unicast.pcap.gz](https://github.com/zephyrproject-rtos/zephyr/files/2694903/unreq-arp-reply-unicast.pcap.gz)

**Comment by jukkar** [comment]
Same issue as with #11562 we do not support unsolicited ARP replies because of possible security issues.
