### ISSUE TITLE
Nested interrupt test has very poor coverage

### ISSUE THREAD

**Issue by andyross** [zephyrproject-rtos/zephyr#12191]
Discussion in #12148 showed that the nested_irq test item in tests/kernel/interrupt needs some work.

Right now we're running it only on ARM and ARC, despite the fact that nested interrupts are supported on all of our architectures and we **REALLY** want to be testing this pervasively.  (It's hard!  I've done two implementations of nested interrupt entry, and messed it up both times in ways that look like they "worked" for a long time after they were "finished").

The big thing missing is that the "trigger_irq()" function in the test needs to be implemented for all architectures.  And really, it should be an exposed, official Zephyr API (I can't think of any of our platforms where it's not possible to flag a specific interrupt).  On x86 it can be an INT instruction.   Xtensa has a writable "flagged interrupts" register.

Another complexity on Xtensa is that interrupt priorities are fixed to the IRQ, the IRQ_CONNECT() implementation ignores the priority argument.  There the test would have to select two specific unused interrupts with the desired priorities.

**Comment by andrewboie** [comment]
> The big thing missing is that the "trigger_irq()" function in the test needs to be implemented for all architectures. And really, it should be an exposed, official Zephyr API 

We sorta do, with irq_offload().
Can we implement a nested IRQ test in terms of irq_offoad()?

**Comment by andyross** [comment]
Would sort of have to work the other way around: irq_offload() could be implemented in terms of firing a specific interrupt (pretty much how everything does it right now), but the API here is the ability to trigger a specific ISR that was already registered to an arbitrary driver via IRQ_CONNECT.

**Comment by andyross** [comment]
*(Doing a grooming pass on bugs/issues that are sitting around with my name on or near them.  No one pays me right now so I get to be an unaccountable whirlwind of chaos!)*

Going to close this.  This very test just got a revisit recently that added a CONFIG_IRQ_OFFLOAD_NESTED that allows any architecture to declare support, so every such architecture now gets automatic coverage for nested interrupts.  That covers the kernel needs.  Platform layers that need this can open their own issues to implement that.
