### ISSUE TITLE
Enabling CONFIG_LOG is throwing exceptions on intel_s1000

### ISSUE THREAD

**Issue by rgundi** [zephyrproject-rtos/zephyr#12201]
When CONFIG_LOG is enabled for intel_s1000, the program crashes with a ton of exceptions. This failure can be seen from tests/boards/intel_s1000_crb as well as from samples/subsys/usb/dfu. This failure has become more pronounced since the addition of the Flash driver (spi_nor) which sits on the SPI bus.

**Comment by nashif** [comment]
@dcpleung Can you take a look at this please? Best way to test this is using the test: `tests/boards/intel_s1000_crb`. Works fine when logging is disabled, hangs when not.
