### ISSUE TITLE
DTS: Inconsistencies seen for SPI node with size-cells

### ISSUE THREAD

**Issue by rgundi** [zephyrproject-rtos/zephyr#12250]
This is observed on intel_s1000 and with PR #11850 . 

If the size-cells are kept as 1, I get the below warning when I do CMake
intel_s1000_crb.dts_compiled: Warning (spi_bus_bridge): /soc/spi@e000: incorrect #size-cells for SPI bus
intel_s1000_crb.dts_compiled: Warning (spi_bus_reg): Failed prerequisite 'spi_bus_bridge'

If i make the size-cells as 0, this warning during CMake goes away but the subsequent "make" fails with the below error.
zephyr/drivers/flash/spi_nor.c:387: error: ‘CONFIG_FLASH_SIZE’ undeclared here (not in a function)

**Comment by galak** [comment]
This is not a bug, you need to enhance how CONFIG_FLASH_SIZE gets set/defined for use with spi nor flash.
