### ISSUE TITLE
kernel: poll: outdated check for expired timeout

### ISSUE THREAD

**Issue by pabigot** [zephyrproject-rtos/zephyr#12264]
`signal_poll_event` in kernel/poll.c invokes `_is_thread_timeout_expired`, which checks whether a timeout `dticks` field has the flag value `_EXPIRED`.   After the timer updates in 987c0e5fc1fa665ce629796c97529f219380e0a7 the only reference to that value is in `benchmarks/timing_info/src/msg_passing_bench.c`.

Since there's no way the test could succeed in any other condition some cleanup needs to be done.

**Comment by nashif** [comment]
1c4177d10f7 changed signal_poll_event and removed _is_thread_timeout_expired, so this issue is not valid anymore.
