### ISSUE TITLE
doc: nightly published AWS docs are not as generated

### ISSUE THREAD

**Issue by dbkinder** [zephyrproject-rtos/zephyr#12268]
It appears the nightly process to build the ``/latest`` documentation is not properly syncing the target AWS folder with the web content being generated (e.g., there is litter from a previous publish remaining, or this might be a problem with copying a zero-length file on top of a file that previously was not zero length).

The current symptom is the board documentation for https://docs.zephyrproject.org/latest/boards/arm/nucleo_f746zg/doc/nucleof746zg.html references an image that (incorrectly) is a zero-length jpg file in the repo (not sure how that happened), but is showing up in the published web page because there previously was a non-zero length image there and is not being overwritten now as part of the nightly doc publishing.

PR #12266 is submitting a non-zero-length image to fix the problem, but it's showing there is a publishing inconsistency.

**Comment by nashif** [comment]
Now we delete and sync, so old files are removed. I think this was the issue.
