### ISSUE TITLE
I can't override CONFIG_PRINTK 

### ISSUE THREAD

**Issue by JuricaResetar** [zephyrproject-rtos/zephyr#12276]
**Describe the bug**
Hei hi. 
For some reason, I can not override the CONFIG_PRINTK define in zephyr/.config file. I've created prj.conf file and add redefinition but after the build, I can see that .config file is not changed. That method works for others defines but not for this one... :|
I'm working on sample/boards/nrf52/power_mgr example and I'm trying to reduce power consumption bellow 300uA (hope that disabling debugging options could solve that problem).

Thank you for your help.

**Comment by carlescufi** [comment]
It is probably getting selected by another option

**Comment by carlescufi** [comment]
https://docs.zephyrproject.org/latest/reference/kconfig/CONFIG_PRINTK.html#cmdoption-arg-config-printk

Try disabling `CONFIG_BOOT_BANNER` which seems to select this one

**Comment by JuricaResetar** [comment]
@carlescufi Thank you! That was the problem =) (but power consumption problem is still not solved... :( )

**Comment by ulfalizer** [comment]
Might be `BOOT_BANNER` selecting it (forcing it to `y`). See https://docs.zephyrproject.org/latest/reference/kconfig/CONFIG_PRINTK.html.

Check if `zephyr/.config` has `CONFIG_BOOT_BANNER=y`, and change it to `CONFIG_BOOT_BANNER=n` in that case (or `# CONFIG_BOOT_BANNER is not set`, which works the same, see https://docs.zephyrproject.org/latest/application/application.html#setting-application-configuration-values).

Could also do it in the `menuconfig` interface. Try jumping to `PRINTK` and `BOOT_BANNER` (with `/`) and checking the symbol information (by pressing `?`). It will mention what other symbols are selecting a symbol, etc.

A basic rule is that you'll only be able to change the value of a symbol by manually editing configuration files if it would be possible to change the value in the `menuconfig` interface.
