### ISSUE TITLE
[Coverity CID :190642]Error handling issues in /drivers/console/telnet_console.c

### ISSUE THREAD

**Issue by mandarcthorat1** [zephyrproject-rtos/zephyr#12291]
Static code scan issues seen in File: /drivers/console/telnet_console.c
 Category: Error handling issues
 Function: telnet_send
 Component: Drivers
 CID: 190642
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by nashif** [comment]
fixed
