### ISSUE TITLE
[Coverity CID :190636]Incorrect expression in /samples/subsys/usb/console/src/main.c

### ISSUE THREAD

**Issue by mandarcthorat1** [zephyrproject-rtos/zephyr#12297]
Static code scan issues seen in File: /samples/subsys/usb/console/src/main.c
 Category: Incorrect expression
 Function: main
 Component: Samples
 CID: 190636
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by nashif** [comment]
marked as fixed in coverity
