### ISSUE TITLE
[Coverity CID :190640]Null pointer dereferences in /drivers/wifi/eswifi/eswifi_core.c

### ISSUE THREAD

**Issue by mandarcthorat1** [zephyrproject-rtos/zephyr#12293]
Static code scan issues seen in File: /drivers/wifi/eswifi/eswifi_core.c
 Category: Null pointer dereferences
 Function: eswifi_init
 Component: Drivers
 CID: 190640
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by galak** [comment]
Fixed by commit c9a9e0a4ee664468e734c50f5d8ff28ed839797d
