### ISSUE TITLE
[Coverity CID :190625]Integer handling issues in /samples/bluetooth/peripheral/src/main.c

### ISSUE THREAD

**Issue by mandarcthorat1** [zephyrproject-rtos/zephyr#12308]
Static code scan issues seen in File: /samples/bluetooth/peripheral/src/main.c
 Category: Integer handling issues
 Function: write_without_rsp_vnd
 Component: Samples
 CID: 190625
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by jhedberg** [comment]
Looks like the | should be a &
