### ISSUE TITLE
[Coverity CID :190627]Incorrect expression in /samples/net/zperf/src/zperf_tcp_receiver.c

### ISSUE THREAD

**Issue by mandarcthorat1** [zephyrproject-rtos/zephyr#12306]
Static code scan issues seen in File: /samples/net/zperf/src/zperf_tcp_receiver.c
 Category: Incorrect expression
 Function: zperf_tcp_receiver_init
 Component: Samples
 CID: 190627
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by jukkar** [comment]
False positive
