### ISSUE TITLE
[Coverity CID :190626]Null pointer dereferences in /subsys/net/lib/coap/coap_sock.c

### ISSUE THREAD

**Issue by mandarcthorat1** [zephyrproject-rtos/zephyr#12307]
Static code scan issues seen in File: /subsys/net/lib/coap/coap_sock.c
 Category: Null pointer dereferences
 Function: coap_packet_parse
 Component: Networking
 CID: 190626
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by rveerama1** [comment]
False positive.
