### ISSUE TITLE
[Coverity CID :190632]Memory - corruptions in /drivers/wifi/eswifi/eswifi_offload.c

### ISSUE THREAD

**Issue by mandarcthorat1** [zephyrproject-rtos/zephyr#12301]
Static code scan issues seen in File: /drivers/wifi/eswifi/eswifi_offload.c
 Category: Memory - corruptions
 Function: __read_data
 Component: Drivers
 CID: 190632
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by loicpoulain** [comment]
Fixed in #12361
