### ISSUE TITLE
[Coverity CID :190618]Code maintainability issues in /drivers/modem/wncm14a2a.c

### ISSUE THREAD

**Issue by mandarcthorat1** [zephyrproject-rtos/zephyr#12315]
Static code scan issues seen in File: /drivers/modem/wncm14a2a.c
 Category: Code maintainability issues
 Function: wncm14a2a_rx
 Component: Drivers
 CID: 190618
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by nashif** [comment]
```
returned_value: Assigning value from net_buf_findcrlf(rx_buf, &frag, &offset) to len here, but that stored value is overwritten before it can be used.
```

**Comment by mike-scott** [comment]
Hmm, I should probably ignore the return value entirely there, and remove the check for !frag.  Either way we need to break the loop because a handler was found.
