### ISSUE TITLE
[Coverity CID :190619]Memory - illegal accesses in /subsys/bluetooth/host/mesh/settings.c

### ISSUE THREAD

**Issue by mandarcthorat1** [zephyrproject-rtos/zephyr#12314]
Static code scan issues seen in File: /subsys/bluetooth/host/mesh/settings.c
 Category: Memory - illegal accesses
 Function: store_pending_hb_pub
 Component: Bluetooth
 CID: 190619
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by jhedberg** [comment]
Looks like this was introduced by commit bfad2a0cbfe from @nvlsianpu
