### ISSUE TITLE
[Coverity CID :190620]Null pointer dereferences in /drivers/wifi/eswifi/eswifi_core.c

### ISSUE THREAD

**Issue by mandarcthorat1** [zephyrproject-rtos/zephyr#12313]
Static code scan issues seen in File: /drivers/wifi/eswifi/eswifi_core.c
 Category: Null pointer dereferences
 Function: eswifi_init
 Component: Drivers
 CID: 190620
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by loicpoulain** [comment]
Fixed in #12361
