### ISSUE TITLE
intel_s1000: SPI Flash Erase command doesn't work when booting from flash

### ISSUE THREAD

**Issue by rgundi** [zephyrproject-rtos/zephyr#12353]
In a setup where the code is in flash and the board boots from flash (via BootROM), a "Flash Erase" command is silently failing. Since the Erase fails, the subsequent Write command also silently fails (as it requires the corresponding addresses to be empty before writing).
Such an issue is NOT observed when the code (ELF) is loaded to SRAM via the debugger where the BootROM is not in picture.

**Comment by carlescufi** [comment]
@nashif is this still  relevant?
