### ISSUE TITLE
Allow multiple entries in EMU_PLATFORM 

### ISSUE THREAD

**Issue by PiotrZierhoffer** [zephyrproject-rtos/zephyr#12375]
Right now we are unable to provide multiple simulation frameworks in the board description.
It would be beneficial to allow multiple targets for each board, as mentioned in a PR where we propose Renode as one of the supported simulation frameworks for sanitycheck: https://github.com/zephyrproject-rtos/zephyr/pull/11503#issuecomment-439957641

For example, as Renode supports `riscv/hifive1` target, we would like to enable the build system to run hifive1 both in Qemu and in Renode.

The list in `EMU_PLATFORM` would allow to create multiple targets for specific tools, which is good by itself. One additional thing to consider would be to change the `simulation` node in a platform `yaml` file to a list as well - allowing it to be tested in different ways. I believe it might be considered a different task, though.

**Comment by fkokosinski** [comment]
Hi, I would like to work on this issue.

From what I understand, the `EMU_PLATFORM` variable is used when invoking the `west` command with the `-t run` argument. If it is set, then we run the selected simulator without checking what is set in the per-board yaml file. However, the yaml file is checked and used when running the `twister` script.

We need to consider the following things:
1. do we want to run all simulators in CI? If not, then we need to have a way to specify which simulator should be run by default in CI, i.e.:
```
simulation:
  - tsim
  - renode:
      default: True
  - qemu
```
2. do we want to have the default `EMU_PLATFORM` declared in a CMake script or do we want the user to decide which simulator they want to use every time when the `west` is invoked by e.g. command line argument?
