### ISSUE TITLE
Support touch button

### ISSUE THREAD

**Issue by bublover** [zephyrproject-rtos/zephyr#12385]
**Is your feature request related to a problem? Please describe.**
We're working for UNISOC and doing upstream for new chip and board. 
https://github.com/zephyrproject-rtos/zephyr/pull/10626
Now we have a new feature, touch button.
Capacitance Touch Button IP is used to deal with capacitance touch button operation. It is connected to the capacitance touch button on PCB board. When the button is triggered or released, it will generate corresponding interrupt so that CPU can deal with the specific operation according to system requirements.

**Describe the solution you'd like**
Please provide a framework of touch button, like driver, api, etc..

**Describe alternatives you've considered**
Please provide thinking and methods that I might use to add.

**Additional context**
NA.

**Comment by carlescufi** [comment]
Please submit a Pull Request
