### ISSUE TITLE
non-tickless kernels incorrectly advance system clock with delayed ticks

### ISSUE THREAD

**Issue by pabigot** [zephyrproject-rtos/zephyr#12409]
In the discussion of #12332 it was determined that the timer updates around 2018-09 through 2018-10 resulted in an unintentional change of behavior for `CONFIG_TICKLESS_KERNEL=n`.

Prior to the rework the system clock advanced by one tick on each interrupt, regardless of whether the interrupt was serviced late.

Support for `CONFIG_TICKLESS_KERNEL=y` inadvertently changed this so that the system clock was advanced by the number of ticks required to align it with the divided hardware clock, regardless of the value of `CONFIG_TICKLESS_KERNEL`.

The timer implementations need to be reworked so that for `CONFIG_TICKLESS_KERNEL=n` the original behavior is restored.  Note that this will result in an non-linear relation between the hardware and system clocks if the tick interrupt is delayed by at least `sys_clock_hw_cycles_per_tick()`.

**Comment by pabigot** [comment]
The initial issue description summarizes my understanding of the issue, which may be incorrect.  I've opened the issue because the resolution to #12332 will involve a revision of the documentation for `k_timer` that must refer to the difference between tickless and non-tickless timer behavior.  The content of the documentation depends on whether this bug is fixed.

**Comment by carlescufi** [comment]
@andyross is this something you plan to address in the near future?

**Comment by carlescufi** [comment]
Originally mentioned in [here](https://github.com/zephyrproject-rtos/zephyr/issues/12332#issuecomment-452807555)

**Comment by andyross** [comment]
Do we consider it a bug?  This is the way Zephyr has behaved forever and the existing design just preserves the behavior.

Quite frankly I'm sort of exhausted with timer at this point.  Tell me what needs fixing and I'll fix it.  I have no horse in this particular race.

**Comment by pabigot** [comment]
@andyross I understood you to say it was a bug (well, an unintentional change) here: https://github.com/zephyrproject-rtos/zephyr/issues/12332#issuecomment-452807555

I see you later commented you didn't feel this was important, so feel free to close this to confirm that position.  I only opened it because the only record of the behavior change is buried in comments in a relatively unrelated issue, and it's hard enough to find out the why of past changes without having to wade through issues with dozens of comments.

**Comment by andyross** [comment]
Cleaning up low hanging bugs in prep for release, finally got to this one
