### ISSUE TITLE
Unsupported SOC_NRF52832_CIAA / no error handling of unsupported SOCs

### ISSUE THREAD

**Issue by alexsven** [zephyrproject-rtos/zephyr#12417]
When selecting CONFIG_SOC_NRF52832_CIAA=y in a custom boards defconfig there is only a warning saying that the value 'y' was set, but the final value was 'n' but everything else compiles fine. When looking at the autoconf.h I can see that SOC_NRF52810 is set as default, as this is the first option in the select (soc\arm\nordic_nrf\nrf52\Kconfig.soc:182). So unless you try to use peripherals that aren't supported on the 810, like SPI_1, you wouldn't know until something else crashes.

The workaround for us right now is selecting SOC_NRF52832_QFAA

**Comment by carlescufi** [comment]
@alexsven do you mean `_QIAA`? `_CIAA` is not listed in our SoC list
