### ISSUE TITLE
Assert and printk not printed on RTT

### ISSUE THREAD

**Issue by Qbicz** [zephyrproject-rtos/zephyr#12410]
**Describe the bug**
Log messages are printed, but assert message is not printed out. As a result, it gives impression that device hanged, but does not give any clue why. You can see that it was an assertion, by opening debugger and stopping after the device hanged:
```
>> ninja debug
gdb> c
gdb> (CTRL + C)
```

**To Reproduce**
 Happens for any assert in Zephyr subsystems.
Can be reproduced on hello_world with small modification:

```
#include <zephyr.h>
#include <misc/printk.h>
#include <assert.h>

#define HELLO_LOG_LEVEL 4
#include <logging/log.h>
LOG_MODULE_REGISTER(hello, HELLO_LOG_LEVEL);

void main(void)
{
	for (int i=0; i<5; i++) {
		LOG_WRN("test %d", i);
	}

	k_sleep(100);

	__ASSERT(false, "Asserted!");

	printk("Hello World! %s\n", CONFIG_BOARD);
}
```

Output:
```
[00000000] <wrn> hello: test 0
[00000000] <wrn> hello: test 1
[00000000] <wrn> hello: test 2
[00000000] <wrn> hello: test 3
[00000000] <wrn> hello: test 4

```

Assert message `ASSERTION FAIL ...` is not printed. Is is the same with `__ASSERT_NO_MSG` or if instead of assert there is just a call to `printk()`;

**Environment:**
In configuration, printk is processed by logger: `CONFIG_LOG_PRINTK=y`

Full config:
```
CONFIG_ASSERT=y
CONFIG_ASSERT_LEVEL=2

CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=2
CONFIG_LOG_BACKEND_RTT=y
CONFIG_LOG_BACKEND_RTT_MODE_DROP=y
CONFIG_LOG_MODE_NO_OVERFLOW=y
CONFIG_LOG_PRINTK=y
CONFIG_LOG_PRINTK_MAX_STRING_LENGTH=256
CONFIG_LOG_BUFFER_SIZE=4096
CONFIG_LOG_BACKEND_RTT_MESSAGE_SIZE=256
CONFIG_LOG_STRDUP_BUF_COUNT=64
CONFIG_LOG_STRDUP_MAX_STRING=64
CONFIG_LOG_BACKEND_SHOW_COLOR=n
CONFIG_LOG_BACKEND_FORMAT_TIMESTAMP=n
CONFIG_LOG_PROCESS_THREAD_STACK_SIZE=1024

CONFIG_CONSOLE=y
CONFIG_USE_SEGGER_RTT=y
CONFIG_SEGGER_RTT_BUFFER_SIZE_UP=4096
CONFIG_RTT_CONSOLE=y
CONFIG_UART_CONSOLE=n
```

**Comment by Qbicz** [comment]
FYI @nordic-krch @pdunaj @wiminordic

**Comment by nordic-krch** [comment]
@Qbicz i've reproduced the issue.

**Comment by Qbicz** [comment]
Thank you @nordic-krch. Let me know if you need any further info.

**Comment by nordic-krch** [comment]
So the problem is that assert ends up in forever loop in current context: https://github.com/zephyrproject-rtos/zephyr/blob/c716f9c5aa86203746e7efbdfd25656923ad6daf/include/misc/__assert.h#L90

I'm not sure what is the intention there because depending on the context it will block the system (high priority task or interrupt) or system will continue if it happens in low priority task.

@nashif I see that it's been like that from the beginning of github history. Do we consider assert as unrecoverable? If yes then we need to do something with it because current local loop is not good.

**Comment by Qbicz** [comment]
IMHO assert should be considered a fatal, unrecoverable condition. This is used in development only and its goal is to early reveal bugs in the code and show it to a developer. If the program is buggy, it does not matter if the program can continue or not (in development) - because the bug should be fixed.

In production, the program is released without assertions.  Because of that, it makes no difference if assert trigger fatal termination of thread or entire system. So I believe there should be LOG_PANIC when assert happens.

**Comment by carlescufi** [comment]
Calling `k_oops` might make it harder to debug ASSERT conditions. Maybe @andrewboie has a suggestion here on how to deal with this particular issue.

**Comment by Qbicz** [comment]
@nordic-krch can we first fix the problem I mentioned? The visible problem is that on any assert, nothing is printed out and user has to guess that it was an assertion and use debugger to get to know where it happened.

And the `printk` has to be handled by logger `CONFIG_LOG_PRINTK=y`, because otherwise it locks RTT which is dangerous when anything is printed from interrupts.

Let's handle this problem first, maybe by using logger panic?
