### ISSUE TITLE
Support multi instances of a USB class simultaneously

### ISSUE THREAD

**Issue by RamiroOliveira** [zephyrproject-rtos/zephyr#12432]
**Is your enhancement proposal related to a problem? Please describe.**
At the moment in Zephyr it's only possible to assign one type of each USB class to a device

**Describe the solution you'd like**
A simple method to add more than one of each USB class to a device. For example, I wanted to create a USB device with two ttyACMs/ttyUSB. With the current implementation this is not possible.

**Describe alternatives you've considered**
If this is not in the immediate plans an Application Note describing the general steps would be interesting.

@finikorg

**Comment by masz-nordic** [comment]
Relates to #12060

**Comment by carlescufi** [comment]
CC @masz-nordic @jfischer-phytec-iot @pawelzadrozniak

**Comment by carlescufi** [comment]
@finikorg As part of this work it would be great to have an exmaple that combines 2 different classes each multiple instances, eg: 2x CDC ACM ports and 2x HID instances
