### ISSUE TITLE
Fix rounding in _ms_to_ticks()

### ISSUE THREAD

**Issue by pizi-nordic** [zephyrproject-rtos/zephyr#12509]
At the moment the _ms_to_ticks() rounds down, which results in premature expiration of timeouts scheduled just before edge of tick. To fix that we have to revert https://github.com/zephyrproject-rtos/zephyr/pull/9745 in order to restore rounding up.

**Comment by pabigot** [comment]
That's one place where things get rounded down.  The same truncation happens in `z_clock_elapsed` in multiple architectures where fractional ticks are discarded.  Overall the need to traffic in durations that are downsampled from the hardware clock resolution in multiple places makes proper management of sleeps and alarms quite difficult.

**Comment by ioannisg** [comment]
@pizi-nordic @carlescufi is this still applicable, and if so, how can we address it ifor 2.0?

**Comment by pizi-nordic** [comment]
IMHO it should be fixed. I can prepare PR after I finish userspace logging.

**Comment by ioannisg** [comment]
> 
> 
> IMHO it should be fixed. I can prepare PR after I finish userspace logging.

Could you please address this for 2.0 @pizi-nordic ?

**Comment by carlescufi** [comment]
> > IMHO it should be fixed. I can prepare PR after I finish userspace logging.
> 
> Could you please address this for 2.0 @pizi-nordic ?

Or actually, will this be fixed by https://github.com/zephyrproject-rtos/zephyr/pull/17155?
And if so, can we just close this and track the issue directly in https://github.com/zephyrproject-rtos/zephyr/issues/9904 ?

**Comment by pizi-nordic** [comment]
@carlescufi: Yes, it will be fixed in #17155. However I will prepare a PR with this because #17155 will not go into 2.0 and now the change is safe as #16782 is merged.

**Comment by pabigot** [comment]
This is pending in #19591 which uses ceil for ms_to_ticks.
