### ISSUE TITLE
Bluetooth: suspend private address (RPA) rotating

### ISSUE THREAD

**Issue by Qbicz** [zephyrproject-rtos/zephyr#12535]
**Is your feature request related to a problem? Please describe.**
When Bluetooth privacy is enabled, address is changed every `BT_RPA_TIMEOUT` seconds.
However, for Microsoft Swift Pair feature it is needed to pause changing the address:

> If LE Privacy is supported, the peripheral should suspend rotating the Bluetooth LE Address during the Swift Pair session. The rotated address would be received as a new device request by Windows and would show two notifications for a single peripheral.

https://docs.microsoft.com/en-us/windows-hardware/design/component-guidelines/bluetooth-swift-pair

**Describe the solution you'd like**
There could be API to stop/start the RPA change timer, which will be used by application to suspend the address change when Swift Pair advertising is used.

**Comment by Vudentz** [comment]
I wonder if we should inhibit the rotation during the advertising if it is set as (limited) discoverable since this problem affects any stack that keeps a cache of devices while discovering (BlueZ keeps devices founds for 3 min.).

**Comment by jhedberg** [comment]
> I wonder if we should inhibit the rotation during the advertising if it is set as (limited) discoverable since this problem affects any stack that keeps a cache of devices while discovering (BlueZ keeps devices found for 3 min.).

Doesn't sound like a bad idea. IIRC the discoverable mode is part of the advertising data (a "flags" data field), which bt_le_adv_start() doesn't look at currently.

**Comment by Qbicz** [comment]
@jhedberg your simpler solution sounds good, what @Vudentz says is even simpler. I think it's about don't changing the RPA as long as device advertises (may be through resetting or blocking timer from expiring). The Kconfig option could be "Do not change the resolvable private address during advertising".

**Comment by jhedberg** [comment]
> I think it's about don't changing the RPA as long as device advertises

@Qbicz 	I think that's making it too simple. There are devices that advertise all the time (e.g. beacons, but probably also some which are connectable). If the app developer enables privacy there should be a reasonable expectation that the device cannot be tracked over long periods of time. Suspending RPA rotation for discoverable advertising (where one of the discoverable flags is set in the advertising data) sounds like an interesting idea from @Vudentz . It'd be nice to hear some other opinions about it, e.g. from @sjanc @carlescufi @cvinayak and @holtmann

**Comment by joerchan** [comment]
@jhedberg I think it would be better to force an RPA timeout instead of suspending it, that way we don't risk accidentally disabling privacy.
I think it is possible to do this with `bt_le_oob_get_local`

**Comment by joerchan** [comment]
@Qbicz Does using `bt_le_oob_get_local` to generate a fresh address and reset the timer work for the swift pairing use-case?

**Comment by Qbicz** [comment]
@joerchan this looks like a good idea, I will give it a try this week.

**Comment by Qbicz** [comment]
Currently privacy does not work in our configuration because we use multiple identities. @MarekPieta will you be able to check it once problem with privacy/multiple identities is resolved?

**Comment by joerchan** [comment]
@MarekPieta @Qbicz As far as I know the privacy issues have been fixed. Can you please check if the suggestion solves the problem?

**Comment by MarekPieta** [comment]
I checked and I think we can close the issue. Thanks for all the help.
