### ISSUE TITLE
nrf timer handling exceeds bluetooth hard realtime deadline

### ISSUE THREAD

**Issue by pabigot** [zephyrproject-rtos/zephyr#12541]
As implemented and noted in #12537 the current implementation of `z_clock_set_timeout()` in `nrf_rtc_timer.c` can take as long as 11.7 us with interrupts block, exceeding the [hard deadline](https://github.com/zephyrproject-rtos/zephyr/issues/12342#issuecomment-452285493) for Bluetooth on the nRF51 platform.

**Comment by carlescufi** [comment]
CC @cvinayak
