### ISSUE TITLE
ext: stm32: revert fix https://github.com/zephyrproject-rtos/zephyr/pull/8762

### ISSUE THREAD

**Issue by erwango** [zephyrproject-rtos/zephyr#12609]
**Describe the bug**
A fix was introduced in ext to fix LL API function.
After analysis, it appears that function is actually correct, and issue was actually in parameters provided that didn't match the API.
Revert fix introduced in API and fix use of API (in drivers/i2s/i2s_ll_stm32.c)

**To Reproduce**
NA

**Expected behavior**
NA

**Impact**
Wrong waveform generated

**Screenshots or console output**
NA

**Environment (please complete the following information):**
NA

**Additional context**
In drivers/i2s/i2s_ll_stm32.c, function `LL_RCC_PLLI2S_ConfigDomain_I2S`, parameter `PLLR` should be one of:
  * @param  PLLR This parameter can be one of the following values:
```
  *         @arg @ref LL_RCC_PLLI2SR_DIV_2
  *         @arg @ref LL_RCC_PLLI2SR_DIV_3
  *         @arg @ref LL_RCC_PLLI2SR_DIV_4
  *         @arg @ref LL_RCC_PLLI2SR_DIV_5
  *         @arg @ref LL_RCC_PLLI2SR_DIV_6
  *         @arg @ref LL_RCC_PLLI2SR_DIV_7
```
which are actually already shifted values.

**Comment by avisconti** [comment]
Closing this issue as addressed by #12637
