### ISSUE TITLE
Move disco_l475_iot1 BT to new DTS CS SPI handling

### ISSUE THREAD

**Issue by erwango** [zephyrproject-rtos/zephyr#12679]
**Is your enhancement proposal related to a problem? Please describe.**
Following merge of https://github.com/zephyrproject-rtos/zephyr/pull/1264, move BT chip control for this board to the CS SPI configuration proposed by this change

**Describe the solution you'd like**
cf https://github.com/zephyrproject-rtos/zephyr/pull/12647/commits/47825f51277e9c5028b95e9fa2495cfd880ab987

**Comment by galak** [comment]
Should be resolved by #12927
