### ISSUE TITLE
Logger doesn't support %llu format string

### ISSUE THREAD

**Issue by bfrog** [zephyrproject-rtos/zephyr#12697]
On master with logging/log.h

LOG_DBG("%llu", my64bitint); results in a u in the log output rather than the number expected

**Comment by nordic-krch** [comment]
yes, it is by design: https://docs.zephyrproject.org/latest/subsystems/logging/index.html#limitations
arguments are logger as 32 bit values. Extending that is not that easy.

**Comment by bfrog** [comment]
That makes sense, maybe note which format strings are supported directly in the docs
