### ISSUE TITLE
CMAKE_EXPORT_COMPILE_COMMANDS is broken

### ISSUE THREAD

**Issue by erwango** [zephyrproject-rtos/zephyr#12696]
**Describe the bug**
When generating compile_commands.json, broken include paths are generated, for instance:
```-IE:...soc/arm/st_stm32/include -IE:.../soc/arm/st_stm32/stm32l4/include```

**To Reproduce**
1. mkdir build; cd build
2. cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DBOARD=board\_xyz
3. make
4. Check generated compile_commands.json

Alternatively, `set(CMAKE_EXPORT_COMPILE_COMMANDS Y)` in `CMakeLists.txt`

**Expected behavior**
Generate only real paths

**Impact**
Warning generated when using Eclipse

**Screenshots or console output**
If applicable, add a screenshot (drag-and-drop an image), or console logs
(cut-and-paste text and put a code fence (\`\`\`) before and after, to help
explain the issue.

**Environment (please complete the following information):**
 - OS: (e.g. Linux, MacOS, Windows)
 - Toolchain (e.g Zephyr SDK, ...)
 - Commit SHA: 0289a410baa07d79c2ceaa426e3d4c106f9dd273

**Additional context**

**Comment by erwango** [comment]
@GeorgeCGV

**Comment by SebastianBoe** [comment]
CMAKE_EXPORT_COMPILE_COMMANDS is a CMake feature that has not been integration-tested with Zephyr. If someone could figure out why it is failing, e.g. is Zephyr doing something illegal, or are we being affected by a known bug in CMake, then I might be able to figure out how to fix it.

**Comment by GeorgeCGV** [comment]
@SebastianBoe it doesn't fail...
The "issue" here is that there are predefined include paths but not every `${SOC_PATH}` and `${SOC_FAMILY}` will have `include` subfolder. 
```
  ${SOC_DIR}/${ARCH}/${SOC_PATH}/include
  ${SOC_DIR}/${ARCH}/${SOC_FAMILY}/include
```
This is not a big of a problem as such includes will produce only a `warning` within some IDEs (e.g. Eclipse).
However, if you would like the project to be clean of `warnings` for some SoCs then the strategy of global predefined include paths shall be changed; alternative is to create such directories for every `${SOC_PATH}` and `${SOC_FAMILY}` or to let the SoC manage `includes` on its own.

**Comment by SebastianBoe** [comment]
aha, thanks, that we can fix.

**Comment by SebastianBoe** [comment]
So the problem is not the "..." ?

That was what I (mis)understood.

**Comment by GeorgeCGV** [comment]
> So the problem is not the "..." ?
> 
> That was what I (mis)understood.

No. the "..." is just to remove the path to `ZEPHYR_ROOT`

**Comment by GeorgeCGV** [comment]
@SebastianBoe some SoC do use mentioned directories. It is more of a structural "issue" here, but some people might prefer to have predefined paths like that.
