### ISSUE TITLE
Issue : Information CC3220SF LaunchXL

### ISSUE THREAD

**Issue by IotPanorama** [zephyrproject-rtos/zephyr#1270]
There is a wrong information on Zephyr project site about CC3220SF launchpad. It has 4 MB flash where as the document in the link below says it has 1MB flash.  https://www.zephyrproject.org/doc/boards/arm/cc3220sf_launchxl/doc/cc3220sf_launchxl.html. please correct it.

**Comment by ydamigos** [comment]
Could you please provide a link where it mentions that CC3220SF launchpad has 4 MB flash?
TI's product page (http://www.ti.com/tool/CC3220SF-LAUNCHXL) mentions 1MB Flash.

**Comment by dbkinder** [comment]
I see lots of references to the board only having 1MB flash:  https://store.ti.com/CC3220SF-LAUNCHXL-SimpleLink-Wi-Fi-CC3220SF-Wireless-Microcontroller-LaunchPad-Development-Kit-P50638.aspx https://www.digikey.com/en/product-highlight/t/texas-instruments/cc3220sf-launchpad http://www.ti.com/lit/ds/symlink/cc3220.pdf

**Comment by GAnthony** [comment]
@IotPanorama, please provide reference showing the LaunchXL may have 4 Mb internal flash.

All TI CC3220SF documents I've seen, plus the LaunchXL description itself from digikey, have boards with 1Mb flash available:
https://www.digikey.com/en/product-highlight/t/texas-instruments/cc3220sf-launchpad

**Comment by IotPanorama** [comment]
@GAnthony , sorry for being late, CC3220SF have a 1Mb xip flash internally but the CC3220SF Launchxl  has a 32Mbit (4MB) flash (MX25R3235F) on board. Each CC3220x device need that external flash. you can find the information in block diagram present in this Document( http://www.ti.com/lit/ug/swru463/swru463.pdf )

**Comment by GAnthony** [comment]
@IotPanorama, you are correct.  I verified the *external* flash is 4MB using the TI UniFlash tool.  Internal flash is still 1MB.  I'll make this more clear in the documentation.
