### ISSUE TITLE
how to configure interrupt signals on shields via device tree?

### ISSUE THREAD

**Issue by pabigot** [zephyrproject-rtos/zephyr#12703]
I've got patches related to the HTS221 sensor for nrf52_pca20020 to enable interrupt-driven sampling.  Works fine, but I'd like to test it with the x_nucleo_iks01a2 shield on `frdm_k64f` and `nucleo_l476rg`.  The corresponding `DRDY` signal is on the Arduino header at `INT0` (or `GPIO2` or whatever they name the third-from-bottom-on-right pin).

Is there an existing solution for this?
```
        hts221@5f {
                compatible = "st,hts221";
                reg = <0x5f>;
                drdy-gpios = <&what goes here>;  /* or &arduino_int0? */
                label = "HTS221";
        };
```

**Comment by erwango** [comment]
@pabigot, can we close this point?

**Comment by pabigot** [comment]
Yes, I think the nexus node capability handles this.

Wonder if I still have those patches anywhere....
