### ISSUE TITLE
doc: Samples and Demos documentation hierarchy looks unintentionally deep

### ISSUE THREAD

**Issue by sathishkuttan** [zephyrproject-rtos/zephyr#12758]
**Describe the bug**
The documentation pages for samples and demos contain hyperlinks for pages and headings at deep levels that do not seem intentional

**To Reproduce**
1. See https://docs.zephyrproject.org/latest/samples/samples.html
Example screenshot below - the link at the bottom is the same as the one on the top of screenshot
![image](https://user-images.githubusercontent.com/21689870/51782919-ca96f080-20e5-11e9-8535-ef22dda605dc.png)

2. See https://docs.zephyrproject.org/latest/samples/boards/boards.html
Example screenshot below - the 1st link is actually a sub-page within the page in 2nd link
![image](https://user-images.githubusercontent.com/21689870/51782930-0a5dd800-20e6-11e9-8e0e-bab971325588.png)

**Expected behavior**
The intent likely was for the parent page to contain only 1st level child pages, not 2 levels. If the intent was 2 levels, then atleast the 2nd level should be indented.

**Impact**
Documentation page is cluttered and makes it difficult to locate the page one is looking for.

**Comment by dbkinder** [comment]
What happened was a second level of sample hierarchy was added for some areas (e.g., "USB Samples" under "Various Subsystem Samples" so there's a mixture of sample docs and sample organization docs.  I'll change to just be a two-level index and you'll find that there are more USB samples when you click on the link.
