### ISSUE TITLE
USB audio isochronous endpoints

### ISSUE THREAD

**Issue by m-nilsson** [zephyrproject-rtos/zephyr#12775]
Hi,

We would like support for USB audio and MIDI, mainly for the NRF52840.
The current implementation does not seem to support isochronous endpoints but it looks like they were included in the LPCUSB stack at some point, but not in a release branch.
https://sourceforge.net/p/lpcusb/code/HEAD/tree/trunk/

I have seen other people here mentioning it as well.
Would it be possible to include this functionality in Zephyr in the near future?
Is there any ongoing work on this?

**Comment by pawelzadrozniak** [comment]
Hi.
I am currently working on audio class. I was able to modify testusb class by adding iso endpoints and pass the basic linux test on nrf52840.

**Comment by m-nilsson** [comment]
@pawelzadrozniak 
Ok, that's great news!

**Comment by raveslave** [comment]
Can we request this to support USB Audio Class 2.0 as well?

**Comment by masz-nordic** [comment]
@raveslave Can you make a separate issue for Audio 2.0? I think @pawelzadrozniak is implementing 1.0.

**Comment by benolayinka** [comment]
@pawelzadrozniak any luck?

**Comment by raveslave** [comment]
@pawelzadrozniak just checking in if you planned on merging your work. would be awesome!

**Comment by raveslave** [comment]
> Hi.
> I am currently working on audio class. I was able to modify testusb class by adding iso endpoints and pass the basic linux test on nrf52840.

do you have this in a repo somewhere?

**Comment by emob-nordic** [comment]
> > Hi.
> > I am currently working on audio class. I was able to modify testusb class by adding iso endpoints and pass the basic linux test on nrf52840.
> 
> do you have this in a repo somewhere?

Hello, I've just get notification about this issue. Pawel is not working in the project anymore, I've recently start work in this topic. I don't know what Pawel had but [here](https://github.com/emob-nordic/zephyr/tree/usb_audio_class) is the temp branch where I push the changes. Feel free to comment.

**Comment by emob-nordic** [comment]
#21526
