### ISSUE TITLE
shell on Arduino Due prints "shell>" before the delayed boot banner

### ISSUE THREAD

**Issue by inakypg** [zephyrproject-rtos/zephyr#1280]
When running the samples/subsys/shell/ app on an Arduino Due (knowing it will fail because there is no IRQ serial support):
```
shell> ***** delaying boot 1000ms (per build configuration) *****
***** BOOTING ZEPHYR OS v1.9.0-rc2 (delayed boot 1000ms) *****
```
thus, the delayed boot banner is being printed AFTER the app is running (that prints shell). 

@nashif  suggests moving the banner printing / delay on top of _sys_device_do_config_level(_SYS_INIT_LEVEL_APPLICATION);

**Comment by nashif** [comment]
this is not related to Arduino Due, it is a generic bug that can be reproduced with qemu

**Comment by inakypg** [comment]
Correct.
