### ISSUE TITLE
topic-counter: nrfx_*: counter_set_top_value inconsistent behavior

### ISSUE THREAD

**Issue by pabigot** [zephyrproject-rtos/zephyr#12800]
The documentation does not indicate whether `counter_set_alarm()` which maps to `counter_set_top_value()` should be a one-shot or repeating capability.  The behavior for Nordic is inconsistent:

For RTC:

* If `counter_set_top_value` is configured with the maximum top value the callback is invoked once, but not rescheduled, though the callback remains associated with the channel.
* If `counter_set_top_value` is configured with a top value less than the maximum the RTC clock is cleared and the timer rescheduled, resulting in a repeated callback at the requested interval.

For TIMER:

* If `counter_set_top_value` is the callback is repeated at the requested interval without being rescheduled.

**Comment by nashif** [comment]
@pabigot @nordic-krch  is this still an issue?

**Comment by pabigot** [comment]
AFAIK it was closed by #12815.
