### ISSUE TITLE
spi_ll_stm32 driver does not support stm32f1soc

### ISSUE THREAD

**Issue by chunshanzhu** [zephyrproject-rtos/zephyr#1281]
when I compile the samples/hello_world with the stm32f103ze boards, Two errors appear：
error: ‘SPI_SR_FRE’ undeclared
error: ‘LL_SPI_PROTOCOL_MOTOROLA’ undeclared

**Comment by guo-mkcooc** [comment]
I also encountered the same problem.

I plan to use spi with the stm32f107 , but dts or pinmux seem can't configure SPI pins. 
however, stm32f4, f3, l4 all works with pinmux except f1.

**Comment by mgorzkowski** [comment]
I have the same problem.
I want to use SPI on stm32_min_dev board (stm32f103)

**Comment by chunshanzhu** [comment]
stm32f1 does not have the SPI_SR_FRE regesiter bit，and not support the LL_SPI_PROTOCOL_MOTOROLA protocol.

**Comment by ydamigos** [comment]
I will check it.

**Comment by ydamigos** [comment]
Just a quick update.
I started working on the issue at https://github.com/ydamigos/zephyr/tree/stm32f1-spi. 
The driver compiles fine but when I use the spi-loopback test, I get a bus fault, pointing to line 245 of spi_contex.h. The error isn't specifically in this part of the code. I will try to find the root of it.
There is a similar issue #3850 for stm32f3 family.

**Comment by ydamigos** [comment]
Could you test PR #5413?
