### ISSUE TITLE
Check if spinlock is held

### ISSUE THREAD

**Issue by pdunaj** [zephyrproject-rtos/zephyr#12823]
**Is your enhancement proposal related to a problem? Please describe.**
Spinlock cannot be taken recursively as first release of the lock will cause release of the entire spinlock (there is no counting of how many times lock was taken). This can lead to serious and hard to discover bugs (see e664c78b8297ad3ec366c7a98aa46cda77a150ad).

**Describe the solution you'd like**
Either to make spinlock counting number of times it was taken or,
make spinlock assert if it was already taken.

**Describe alternatives you've considered**
You can write that into documentation but who reads fine print...

**Comment by dcpleung** [comment]
#12891 got merged which would assert for recursive locks.
