### ISSUE TITLE
Question about k_thread_entry_t and k_thread_create

### ISSUE THREAD

**Issue by nikooiko** [zephyrproject-rtos/zephyr#12870]
Hello everyone, I was navigating through various drivers using threads to do background work and I noticed that almost everywhere there are thread creations that use functions with a different definition than the **k_thread_entry_t**.

For example at adt7420_trigger, we can see that the **adt7420_thread** function has only two params and both have different type than *(void \*)*:

https://github.com/zephyrproject-rtos/zephyr/blob/4c3bcbafef27b690273fc5e1b14b18d76a35b5d3/drivers/sensor/adt7420/adt7420_trigger.c#L129-L133

https://github.com/zephyrproject-rtos/zephyr/blob/4c3bcbafef27b690273fc5e1b14b18d76a35b5d3/drivers/sensor/adt7420/adt7420_trigger.c#L57

https://github.com/zephyrproject-rtos/zephyr/blob/eac2f7c76399bb4b30b6f2aaeb253ca5fdfa1f95/include/kernel.h#L382

1. How does this work properly?
2. Is this a good practice or we should use methods with definition based on **k_thread_entry_t** and cast the params later on?

**Comment by andrewboie** [comment]
> How does this work properly?

The other arguments are provided in registers or the stack when the new thread is set up, they are just ignored.

> Is this a good practice

No, it's not.

**Comment by nikooiko** [comment]
So from what you said I guess that indeed the best solution is to use methods with a definition based on k_thread_entry_t.

Should we close this?

**Comment by andyross** [comment]
Yeah, this is an ABI violation, but it's harmless on existing architectures.
