### ISSUE TITLE
Update uart api tests with configure/configure_get apis

### ISSUE THREAD

**Issue by erwango** [zephyrproject-rtos/zephyr#12872]
**Is your enhancement proposal related to a problem? Please describe.**
UART API now supports configure and configure_get functions in main API.
These functions remain untested in uart_basic_api test.

**Describe the solution you'd like**
Test configure and configure_get functions in uart tests

**Describe alternatives you've considered**

**Additional context**
Add any other context or graphics (drag-and-drop an image) about the feature request here.

**Comment by ioannisg** [comment]
@erwango Since this is not even assigned yet, I am moving this to 2.1 release.
Please, change back the milestone to 2.0, if this can be completed by the freeze deadline.
