### ISSUE TITLE
C++ 11 support!

### ISSUE THREAD

**Issue by Tenderson** [zephyrproject-rtos/zephyr#1289]
Hi,

Based on the C++ Support for Applications:

http://zephyr-docs.s3-website-us-east-1.amazonaws.com/online/dev/kernel/other/cxx_support.html

Is there any plan on when to support the following c++ functionalities?

1. Dynamic object management with the **new** and **delete** operators
2. Vectors
3. RTTI
4. Exceptions
5. Static global object destruction

This will open a great space to deploy c++ applications on Zephyr too. I appreciate any input.

Thank you.

**Comment by ThomasGrausgruber** [comment]
Hi!

I am also interested in this topic. Looking forward to a concrete plan for C++ 11 support 👍

**Comment by samirame** [comment]
Hi Zephyr,

i also find the c++ support an outstanding feature to compete other RTOSs and to enrich the Zephyr ecosystem with more applications supports.

Any plan for this would be great.

**Comment by mbolivar** [comment]
Looks like this issue and https://github.com/zephyrproject-rtos/zephyr/issues/4028 are dupes. The discussion in the other issue is further along, so maybe close this one as the dupe, even though it's a bit older?

**Comment by Tenderson** [comment]
@mbolivar, thank you for the notice. I close this issue, however I appreciate if you have some thoughts to share on the issue #4028.
