### ISSUE TITLE
tests/benchmarks/timing_info doesn't print userspace stats

### ISSUE THREAD

**Issue by andrewboie** [zephyrproject-rtos/zephyr#12900]
The test, when built with -DCONF_FILE=prj_userspace.conf, doesn't print out the stats for userspace tests.

Here is the output I get:

```
starting test - Time Measurement
Timing Results: Clock Frequency: 25 MHz
Interrupt latency                            :1563 cycles , 15630 ns
Heap Free                                    :15115 cycles , 151150 ns
Mutex lock                                   :2707 cycles , 27070 ns
Mutex unlock                                 :3363 cycles , 33630 ns
Timing Measurement  finished
PASS - main
===================================================================
===================================================================
PROJECT EXECUTION SUCCESSFUL
QEMU: Terminated
[100%] Built target run

```

**Comment by nashif** [comment]
@andrewboie  that on qemu_x86 I guess?
I am getting complete results on e70.

**Comment by AdithyaBaglody** [comment]
This needs to run on a real target not on emulation.

**Comment by andrewboie** [comment]
I'll let you guys decide how to handle this, but it was very strange to me that the userspace stuff ran, but didn't print anything. What's the root cause? Why doesn't PRINT_STATS do anything for these tests?

I think there is some value in showing stats under emulation, for the case where we have emulators that are cycle accurate like ARC.

**Comment by AdithyaBaglody** [comment]
> What's the root cause?

@andrewboie I filter all values which are too big to be true. 
If you have a emulator which is cycle accurate you can run this. But this cant be run on qemu_x86 or mps2_an385. The main purpose of this was to get info from the hardware platforms and not emulators. Therefore i believe we can close this.

**Comment by andrewboie** [comment]
> I filter all values which are too big to be true.

Please get rid of this filter and have it print unconditionally.

**Comment by AdithyaBaglody** [comment]
> Please get rid of this filter and have it print unconditionally.

No, this was asked hence I had to placed it. If you still need it, enable the macro PRINT_ALL_MEASUREMENTS and run.

**Comment by andrewboie** [comment]
> No, this was asked hence I had to placed it

By who?

**Comment by AdithyaBaglody** [comment]
I am not able to recollect. This was a long time ago.

**Comment by AdithyaBaglody** [comment]
@andrewboie I believe we can close this.

**Comment by andrewboie** [comment]
Please get rid of this filter and have it print unconditionally.

**Comment by andrewboie** [comment]
If you want to leave a warning that some values are suspicious that is fine but just dropping the data with no explanation to the end user is unacceptable
