### ISSUE TITLE
MCUboot: high current

### ISSUE THREAD

**Issue by chris-makaio** [zephyrproject-rtos/zephyr#12933]
When compiling our app "standalone" (flashed at offset 0) we see an average current of around 70uA at our PCA10056
But when enabling CONFIG_BOOTLOADER_MCUBOOT the average is around 500uA

Clock config is the same for both confs: RC with 20ppm

**Comment by carlescufi** [comment]
This might be MCUboot initializing the UART. Can you try disabling logging and UART in MCUboot's Kconfig?

**Comment by chris-makaio** [comment]
it's already disabled.
I guess it has something to do which the specs of Laird's BL652 when used w/o external crystal and using the internal 250ppm.
We'll add an external xtal, but it's still strange

**Comment by carlescufi** [comment]
@chris-makaio since this is probably MCUboot or Laird-related, can you please close this?

**Comment by AsgeirSH** [comment]
@chris-makaio Did you find out anything more about this? I'm seeing some of the same symptoms with higher current consumption on an nrf9160 dev kit, even with UART and logging disabled in MCUboot.

**Comment by chris-makaio** [comment]
@AsgeirSH there are SO MANY possible issues related to power management - it's hard to tell what's involved. May I suggest you create a new issue, referencing this one? Are you sure it is related to MCUboot? Maybe it's an issue with that then
