### ISSUE TITLE
Missing Documentation for many subsystems and features

### ISSUE THREAD

**Issue by nashif** [zephyrproject-rtos/zephyr#12955]
We are missing tons of documentation for various components and subsystems

- [x] LWM2M https://github.com/zephyrproject-rtos/zephyr/issues/12958
- [x] CoAP https://github.com/zephyrproject-rtos/zephyr/issues/12956
- [x] MQTT https://github.com/zephyrproject-rtos/zephyr/issues/12957
- [x] Networking section top level doc, #13378
- [x] Bluetooth section top level doc, #13394 

more to follow...

**Comment by pfalcon** [comment]
cc @rlubos, @mike-scott 

Would be nice to get more details on what exactly "We are missing tons of documentation for various components and subsystems" means. For MQTT, API reference is definitely there, not sure about a "guide" docs section.

**Comment by erwango** [comment]
Adding fs

**Comment by dcpleung** [comment]
@nashif Since we have individual bugs opened already, should we close this one?

**Comment by mike-scott** [comment]
@galak I'm working on the "overview" portion of LwM2M documentation and expect it to be ready in 1-2 days.

NOTE: High-level API documentation was merged here: https://github.com/zephyrproject-rtos/zephyr/commit/b56035c940f23e26e0e23e1765fbc0106a905931

**Comment by nashif** [comment]
closing this catchall issue
