### ISSUE TITLE
dfu/mcuboot: solution for Set pending: don't crash when image slot corrupt

### ISSUE THREAD

**Issue by nvlsianpu** [zephyrproject-rtos/zephyr#12968]
This is the Mirror issue.
Related to https://github.com/JuulLabs-OSS/mcuboot/pull/414 discussion.

**Comment by nvlsianpu** [comment]
cc @utzig @ccollins476ad

**Comment by pabigot** [comment]
Is this still relevant?  The upstream issue has been closed.

**Comment by nvlsianpu** [comment]
Not an issue
