### ISSUE TITLE
Fix workaround of using 'mmio-sram' compat for system memory (DRAM) in DTS

### ISSUE THREAD

**Issue by galak** [zephyrproject-rtos/zephyr#12987]
Right now we typically only generate defines/props for compatible's we can match against a binding.  However system memory doesn't have a compatible and thus no binding.  We are hacking a work around to use 'mmio-sram' for DRAM on i.mx-RT boards so things work.

We need to update the dts generation scripts to handle this case properly.

See PR  #12983

**Comment by carlescufi** [comment]
@galak is this still an issue?

**Comment by galak** [comment]
> @galak is this still an issue?

Yes, but I think we recent DTS changes I can finally address this.

**Comment by galak** [comment]
Fixed by a few cleanup commits in the 2.4 cycle.
