### ISSUE TITLE
sanitycheck serializes running tests on ARC simulator

### ISSUE THREAD

**Issue by andrewboie** [zephyrproject-rtos/zephyr#13000]
**Describe the bug**
I was running `sanitycheck -p nsim_sem` on a machine with 40 cores and noticed that it was taking a very long time. htop showed that all my cores were more or less idle except for one copy of nsimdrv.

Running two simultaneous sanitycheck runs in two different terminals shows two instances of nsimdrv, so the problem is with sanitycheck.

**To Reproduce**
1. Install ARC nSIM simulator with nsimdrv in PATH
2. `sanitycheck -p nsim_sem`
3. Observe CPU usage with your favorite process monitor such as htop, there is never more than one nsimdrv running at a time.

**Expected behavior**
Full usage of CPU cores like we get with QEMU.

**Impact**
Wastes a considerable amount of developer time, and also CI runs whenever we eventually get this emulator on the CI slaves. This is especially the case if a lot of tests are crashing (normal during the debug process) as sanitycheck sits there idle waiting for the test to time out before it starts the next one.

**Environment (please complete the following information):**
nSIM, Version: 2017.09 (Build: 011_FREE)
Zephyr master branch

**Comment by nashif** [comment]
should be implemented now.
