### ISSUE TITLE
openthread default configuration

### ISSUE THREAD

**Issue by ozanoner** [zephyrproject-rtos/zephyr#13097]
OpenThread is initialized with the same values as provided in kconfig. at runtime, when one wants to use another thread configuration (networkname, panid, extpanid, channel id), they are overwritten with default values as programmed after a new power cycle. 

**Describe the solution you'd like**
after changing openthread settings, they should be preserved & used in the next boot.

https://github.com/zephyrproject-rtos/zephyr/blob/128d2e2bd176b8c5e384ea46ea452e7864cce84f/subsys/net/l2/openthread/openthread.c#L313
https://github.com/zephyrproject-rtos/zephyr/blob/128d2e2bd176b8c5e384ea46ea452e7864cce84f/subsys/net/l2/openthread/openthread.c#L317
https://github.com/zephyrproject-rtos/zephyr/blob/128d2e2bd176b8c5e384ea46ea452e7864cce84f/subsys/net/l2/openthread/openthread.c#L318
https://github.com/zephyrproject-rtos/zephyr/blob/128d2e2bd176b8c5e384ea46ea452e7864cce84f/subsys/net/l2/openthread/openthread.c#L319

**Comment by rlubos** [comment]
@ozanoner I've submitted a PR with a solution for the issue you've described, see #15521. Now it will be checked during OT initialization, whether a valid dataset is stored. The default configuration will only be applied in case there no dataset.

**Comment by ozanoner** [comment]
Thank you!
