### ISSUE TITLE
Remove CONFIG_X86_PAE_MODE from scripts/gen_mmu_x86.py  

### ISSUE THREAD

**Issue by galak** [zephyrproject-rtos/zephyr#13096]
Commit 2d9bbdf5f31dd4ffd43473f7a4db180a3c85a202 remove the Kconfig symbol CONFIG_X86_PAE_MODE but it still exists in scripts/gen_mmu_x86.py

**Comment by andrewboie** [comment]
Why is this a high priority bug? There's just an unused function, I'll remove it but it's not breaking anything.
