### ISSUE TITLE
Using code relocation

### ISSUE THREAD

**Issue by Laczen** [zephyrproject-rtos/zephyr#13111]
Can I use code relocation to place a complete zephyr subsystem (e.g. Bluetooth) in a specific flash region ?

**Comment by SebastianBoe** [comment]
Unfortunately not, code_relocation works on individual source files.

Also, apart from in documentation, the concept of "subsystems" does not exist.

The relevant concepts that do exist are directories and libraries.

So it might be possible to eventually enhance code_relocation to work on libraries or directories, and not just files.
