### ISSUE TITLE
No callback - USB suspend

### ISSUE THREAD

**Issue by MarekPieta** [zephyrproject-rtos/zephyr#13127]
**Describe the bug**
USB does not provide proper callback when suspended (USB_DC_SUSPEND). Using nRF52840 USB Device Controller Driver.

**To Reproduce**
Device with mentioned driver is connected and systems hibernates, USB devices should be suspended.

**Environment (please complete the following information):**
 - OS: Linux, Ubuntu 16.04 LTS
 - Toolchain: Zephyr SDK 0.9.5

**Comment by carlescufi** [comment]
Fixed in https://github.com/zephyrproject-rtos/zephyr/pull/13132
