### ISSUE TITLE
Add exposing TOOLCHAIN_HAS_NEWLIB to Kconfig

### ISSUE THREAD

**Issue by galak** [zephyrproject-rtos/zephyr#13162]
PR #12393 is going to introduce TOOLCHAIN_HAS_NEWLIB so that various testscases can use if the toolchain supports newlib or not to determine if they should be built.

We should also take TOOLCHAIN_HAS_NEWLIB as an input to Kconfig so that we have a dependancy on even enabling CONFIG_NEWLIB_LIBC.

**Comment by pfalcon** [comment]
+1. I just now see a case where riscv32 toolchain from SDK 0.9.5 lacks a header coming from newlib and available in other toolchains in that SDK, failing a build for me.

**Comment by kartben** [comment]
See https://github.com/zephyrproject-rtos/zephyr/pull/54637
