### ISSUE TITLE
LwM2M: support Access Control objects (object id 2)

### ISSUE THREAD

**Issue by mike-scott** [zephyrproject-rtos/zephyr#13196]
**Is your enhancement proposal related to a problem? Please describe.**
LwM2M client in Zephyr currently supports 1 server connection and has no restrictions for what that server can change on the client.  LwM2M Object: Access Control (object id 2) supports fine grain control of resource access per server to allow for multiple server connections.

**Describe the solution you'd like**
Let's implement LwM2M 1.0 standard Access Control object to fix this.

**Comment by ioannisg** [comment]
@mike-scott are you planning to push this feature for 2.0 release?

**Comment by mike-scott** [comment]
Nope.  This didn't make the cut. Can bump back to 2.1.

**Comment by dleach02** [comment]
Moving to 2.2
