### ISSUE TITLE
Use correct barriers instead of relying on compiler optimizations

### ISSUE THREAD

**Issue by agross-oss** [zephyrproject-rtos/zephyr#1324]
The gen_isr_table kernel test uses GCC optimization of O0 to ensure that proper execution is achieved.  Instead of using optimizations, it should be using a proper barrier mechanism.

The optimization change is located in:
 tests/kernel/gen_isr_table/prj.conf

Need to add in an __ISB() or whatever barrier is required and test to make sure the execution is correct.

**Comment by bryan-hunt** [comment]
Also relating to ARM: arch/arm/core/cpu_idle.S makes WFI & WFE calls without DSB beforehand.

**Comment by d3zd3z** [comment]
A GCC optimization of O0 is only going to be equivalent to a compiler barrier (implemented by any `asm volatile` with `"memory"` in the clobber argument). This only serves to prevent memory reordering by the compiler. We should figure out the necessary CPU barriers to make this correct at that level.

**Comment by ioannisg** [comment]
> Also relating to ARM: arch/arm/core/cpu_idle.S makes WFI & WFE calls without DSB beforehand.
> 
> http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.dai0321a/BIHICBGB.html

@bryan-hunt this has been fixed for quite some time now 👍

**Comment by ioannisg** [comment]
This is solved for Cortex-M, not sure if we would like to keep this open, to get fixes for other ARCHes

**Comment by kartben** [comment]
I believe this has been addressed a while ago. Plus, there's even a barrier API now #57439
