### ISSUE TITLE
UART error bitmask broken by new asynchronous UART API

### ISSUE THREAD

**Issue by erwango** [zephyrproject-rtos/zephyr#13256]
**Describe the bug**
Before introduction of new UART ASYNC API,  common communication errors for UART where coded as a bitmask. UART err_check functions where coded to report error as a bitmask.
Following merge of https://github.com/zephyrproject-rtos/zephyr/pull/10820/files, uart_rx_stop_reason are not coded as an enum and as a consequence, function implementing the previous API are no more in line with new API

**To Reproduce**
1. mkdir build; cd build
2. cmake -DBOARD=board\_xyz
3. make

**Expected behavior**

**Impact**
What impact does this issue have on your progress (e.g., annoyance, showstopper)

**Screenshots or console output**
If applicable, add a screenshot (drag-and-drop an image), or console logs
(cut-and-paste text and put a code fence (\`\`\`) before and after, to help
explain the issue.

**Environment (please complete the following information):**
 - OS: (e.g. Linux, MacOS, Windows)
 - Toolchain (e.g Zephyr SDK, ...)
 - Commit SHA or Version used

**Additional context**

**Comment by Mierunski** [comment]
I will prepare patch which changes values back to their original state
