### ISSUE TITLE
NRF52 pca10040 boards open the "Flash hardware support" option, the BT Mesh example does not work properly

### ISSUE THREAD

**Issue by xiaoliang314** [zephyrproject-rtos/zephyr#13340]
**Describe the bug**
NRF52 pca10040 boards open the "Flash hardware support" option, the BT Mesh example does not work properly. The UART console does not see any output, return to normal after turning off this option and erase all flash.

**Comment by nvlsianpu** [comment]
@xiaoliang314 
At last samples/bluetooth/mesh/ works well at my desk: I was able to saw loot of loggs on the console.
Please point what example it was (pleas check before with current master). 

> "Flash hardware support" 

what do you mean?

**Comment by xiaoliang314** [comment]
@nvlsianpu This problem occurred when my project was upgraded from HEAD(2caecb5) to the latest version. My chip may still keep the old version of the flash record. When I use the example (samples/bluetooth/mesh) to download to the chip, it doesn't work. This example works when I closed "drivers/flash hardware support" in menuconfig and erased all flash.

**Comment by nvlsianpu** [comment]
Can you full erase your chip and test it with newest master?

Backward compatibility is not guaranteed for both `settings` and `fcb` which might cause problem with old records you have.
Disabling `drivers/flash hardware support` disables `settings` module as well - that why the example started working.

So It is possible that after changes your storage content is incompatible with newest code-base. This might be either fcb or settings.

**Comment by xiaoliang314** [comment]
@nvlsianpu thanks!
