### ISSUE TITLE
make flash error

### ISSUE THREAD

**Issue by Jxudong** [zephyrproject-rtos/zephyr#13354]
when i make flash, the error as follow：

West version found in path does not support '/usr/bin/make flash', ensure west is installed and not only the bootstrapper. run 'west init' to fetch west.

**Comment by ioannisg** [comment]
@carlescufi, @mbolivar  FYI

**Comment by Jxudong** [comment]
when i do
 pip3 install --user west
west --version

error as follow:
'west' is a package and cannot be directly executed

**Comment by carlescufi** [comment]
@Jxudong this is a bit puzzling.

Can you please run the following:

```
pip3 uninstall west
pip3 install -U west
```

then into an empty folder and run:

```
west init .
```
and try flashing there

**Comment by carlescufi** [comment]
Closing since there's no additional feedback
