### ISSUE TITLE
z_timeout_remaining should substract z_clock_elapsed

### ISSUE THREAD

**Issue by alenxyz** [zephyrproject-rtos/zephyr#13353]
**Describe the bug**
Applications that calls z_timeout_remaining would be interested in the actual remaining time at that moment. Right now the return value does not consider elapsed time, which means the timer will expire sooner than the returned value. Maybe the current behaviour is indented but at least for me it was unexpected and not documented.

**Expected behavior**
z_timeout_remaining returns the actual remaining time

**Impact**
Workaround: substract elapsed time in the application.

**Environment (please complete the following information):**
Custom toolchain with Zephyr 1.10 due to C99 only
1.14 seems to show same behaviour from code review

**Additional context**

**Comment by andyross** [comment]
Yeah, that's a bug.    Horrifyingly, we don't test this API **at all**, anywhere.  It's actually dead code.

**Comment by alenxyz** [comment]
Thanks Andy for confirmation. Btw, I also noticed when the head timer is removed before expiry, the HW timer can be set to a later time, or cleared when it was the only timer. It does not seem to cause any trouble though.
