### ISSUE TITLE
nvs sample should not use DT_FLASH_ERASE_BLOCK_SIZE

### ISSUE THREAD

**Issue by erwango** [zephyrproject-rtos/zephyr#13369]
**Is your enhancement proposal related to a problem? Please describe.**
Following discussion in #13328, DT_FLASH_ERASE_BLOCK_SIZE is no more needed for NVS configuration. Since it is is not available on all SoCs (for flash with non fixed block size), sample cannot be run on some boards.

**Describe the solution you'd like**
Remove DT_FLASH_ERASE_BLOCK_SIZE usage from nvs sample

**Describe alternatives you've considered**

**Additional context**
#13328

**Comment by Laczen** [comment]
Solved by PR
