### ISSUE TITLE
Can't use GPIO 2, 3 and 4

### ISSUE THREAD

**Issue by paultjepils1999** [zephyrproject-rtos/zephyr#13422]
**Describe the bug**
Can't use GPIO 2, 3 and 4. When I compile/run the application it shows errors.
I have tried to manually ad the defines to the generated_dts_board.conf but that doesn't work for me. please see image below. Are there any other settings I have to configure or is this a bug?

**To Reproduce**
1. mkdir build; cd build
2. cmake -DBOARD=mimxrt1050_evk ..
3. sudo ninja debug

**Expected behavior**
My expection was that the application would compile and run.

**Impact**
Can't power on a simple LED from GPIO_2_10 (D9), GPIO_1 and GPIO_5 are working (the built in LED can be powered on and off)

**Screenshots or console output**
![image](https://user-images.githubusercontent.com/32222520/52849187-bce6f080-3110-11e9-8c63-3757230d46c6.png)

**Environment (please complete the following information):**
 - OS: Ubuntu 16.04

**Additional context**
prj.conf:
CONFIG_PRINTK=y
CONFIG_KERNEL_SHELL=y
CONFIG_OBJECT_TRACING=y
CONFIG_THREAD_MONITOR=y
CONFIG_INIT_STACKS=y
CONFIG_BOOT_BANNER=n

CONFIG_GPIO=y

**Comment by galak** [comment]
@paultjepils1999 Guessing you need to update the DTS to enable those GPIO blocks and probably do proper pin muxing/cfg as well.

**Comment by paultjepils1999** [comment]
@galak Do you mean by downloading the newest zephyr project? because that doesn't work. I configured the gpio pin mux the same as the the built in LED like this:

IOMUXC_SetPinMux(IOMUXC_GPIO_B0_10_GPIO2_IO10, 0);

IOMUXC_SetPinConfig(IOMUXC_GPIO_B0_10_GPIO2_IO10,
			    IOMUXC_SW_PAD_CTL_PAD_PKE_MASK |
			    IOMUXC_SW_PAD_CTL_PAD_SPEED(2) |
			    IOMUXC_SW_PAD_CTL_PAD_DSE(6));
