### ISSUE TITLE
OpenOCD support code version not raised on recent additions

### ISSUE THREAD

**Issue by dgloeck** [zephyrproject-rtos/zephyr#13448]
The commit a5b6215a060676d07f9a5119f0a05ffa2edc8d85 added three elements to the `_kernel_openocd_offsets` array without raising the `OPENOCD_OFFSET_VERSION` as was instructed in the comment above the array. So even if OpenOCD was able to use those new values, it would not be able to determine if they exist.

But since our patch to OpenOCD right now rejects unknown versions (see zephyrproject-rtos/openocd#3), I suggest to change the meaning of the `OPENOCD_OFFSET_VERSION` field to inform only about **in**compatible changes. For detecting backward compatible additions to the end of the array like the commit mentioned above, we should add a new variable to the .openocd_debug section that has the value `ARRAY_SIZE(_kernel_openocd_offsets)` (C does not allow us to put this value inside the array).

Also note that our patch to OpenOCD is not yet upstream (#2933).
I'd be willing to make pull requests with the necessary changes, both for this issue and for zephyrproject-rtos/openocd.

**Comment by galak** [comment]
@dgloeck please go ahead with the fixing and upstreaming.
