### ISSUE TITLE
Lack of POSIX compliance for sched_param struct

### ISSUE THREAD

**Issue by SteveOss** [zephyrproject-rtos/zephyr#13470]
struct sched_param in Zephyr has a field named "priority", according to the POSIX specification
this field should be named "sched_priority". Is defined in include/posix/posix_sched.h

**Comment by pfalcon** [comment]
Will look into this as time permits, in the meantime also assigning @nniranjhana and @ramakrishnapallala who likely were the original authors of this code, to see if they might get earlier to it.
