### ISSUE TITLE
BLE Split Link Layer Improvements

### ISSUE THREAD

**Issue by carlescufi** [zephyrproject-rtos/zephyr#13519]
This issue lists all the improvements we want to include that are not part of bringing the Split Link Layer up to parity with the existing one (#12681).

- [x] Add support for Controller (SW deferred)-based Privacy (#14621)
- [ ] Change the role dependent event-done handling from type switch-case to callback concept.
- [x] Move the LLL event prepare/resume queue/handling into LLL. (@cvinayak )
- [x] Move the LLL-to-ULL Tx ack queue API to ULL domain.
- [ ] Add documentation for ticker @stko-ot 
- [ ] Include the diagrams done by @pskhansen in the documentation
- [ ] Robustness fix (nice to have): #13389
- [x] Add tests in nrf52_bsim to run on upstream CI for (at least basic) controller functionality
- [ ] Style fixes (#22048)
- [ ] Create a porting guide to help users port to new radio hardware

**Comment by aescolar** [comment]
"- [ ] Use `atomic_cas` when supported by the arch without disabling interrupts ([see for more info](https://github.com/zephyrproject-rtos/zephyr/pull/12404#pullrequestreview-192102680))"
 was removed due to https://github.com/zephyrproject-rtos/zephyr/pull/13471 being closed

**Comment by aescolar** [comment]
"- [ ] Add support for (current) Mesh Extensions (#14678)"
removed as there was no real interest for that, and the ticket was morphed into adding full mesh extensions to the controller.

**Comment by cfriedt** [comment]
Ooooo - I like this! It might also be a good idea to add a basic / minimum recommendation and documentation for the radio API. Naturally, most chips will have a different radio, but we are *mostly* using the same interface so far. However, that interface is largely undocumented. Some state diagrams would be nice as well.

**Comment by carlescufi** [comment]
> Ooooo - I like this! It might also be a good idea to add a basic / minimum recommendation and documentation for the radio API. Naturally, most chips will have a different radio, but we are _mostly_ using the same interface so far. However, that interface is largely undocumented. Some state diagrams would be nice as well.

Just added a point at the end, thanks!

**Comment by joerchan** [comment]
> Add tests in nrf52_bsim to run on upstream CI for (at least basic) controller functionality

Isn't this done?

**Comment by kruithofa** [comment]
@carlescufi we close this issue since realistically no work will be done on this

**Comment by KlemenDEV** [comment]
> realistically no work will be done on this

Will the split LL ever be "official", or should we use the old system?

**Comment by cvinayak** [comment]
> > realistically no work will be done on this
> 
> Will the split LL ever be "official", or should we use the old system?

Split Link Layer is the default upstream since Zephyr v2.0.0-rc1 , see https://github.com/zephyrproject-rtos/zephyr/commit/6cf26b8fe63afdb83817ad551a3f03c40f744a72

**Comment by KlemenDEV** [comment]
I see, thanks!
