### ISSUE TITLE
Missing documentation for fcb and nffs

### ISSUE THREAD

**Issue by erwango** [zephyrproject-rtos/zephyr#13574]
There is no documentation on fcb or nffs.
Specially how it behaves vs flash supported write-block-size...

**Comment by ramakrishnapallala** [comment]
@nvlsianpu  can you look into this issue as fcb and nffs are owned by you.

**Comment by nashif** [comment]
@ramakrishnapallala this is less about the specific filesystems and more about the virtual file system interface and fs support in general.

**Comment by nvlsianpu** [comment]
- fcb doc is missing - can be take form mynewt.
- NFFS is external project as well - currently not well documented, can consider documentation making but, for sure no now.

@nashif  Can we consider this as lack of documentation, not a bug. I would create separate issue for both subjects.

**Comment by nashif** [comment]
lack of documentation is a BUG :)

I would start here: https://docs.zephyrproject.org/latest/reference/file_system/index.html
This is currently the API only need more content to the file system feature in general. Probably a quick into about the supported filesystems with details to be added later.

**Comment by ramakrishnapallala** [comment]
I will start on adding more documentation to the API's

**Comment by ramakrishnapallala** [comment]
Pushed PR: https://github.com/zephyrproject-rtos/zephyr/pull/14796/

**Comment by nashif** [comment]
@nvlsianpu what about documenting fcb and nffs?

**Comment by nvlsianpu** [comment]
FCB doc I can copy form MyNewt.
NFFS is under fixing now - expects that It will change a lot. I would only refer to its design.txt file and describe its limitation.

**Comment by nashif** [comment]
@nvlsianpu any updates?

**Comment by nashif** [comment]
@nvlsianpu ping

**Comment by nvlsianpu** [comment]
I'm Preparing FCB doc right now.

**Comment by nvlsianpu** [comment]
FCB documentation: https://github.com/zephyrproject-rtos/zephyr/pull/17425

**Comment by carlescufi** [comment]
FCB is now documented and NFFS is on the path to deprecation, so closing this.
