### ISSUE TITLE
How to get the port number for an ephemeral (randomly assigned) port

### ISSUE THREAD

**Issue by GregBurns** [zephyrproject-rtos/zephyr#13602]
**I need to know what port number was assigned by net_context_bind()**

Ideally this would be functionality equivalent to getsockname() which I notice is missing from the Zephyr BSD sockets layer API.

**Comment by jukkar** [comment]
If you are directly working with net_context, then it has `struct sockaddr_ptr local;` which contains the local port.

**Comment by GregBurns** [comment]
Yes, that is my current workaround.

**Comment by jukkar** [comment]
For BSD sockets, there is the `getsockname()` function that will return the local socket information. Unfortunately we do not support that function yet.

**Comment by ioannisg** [comment]
@GregBurns please, re-open, if needed, to continue dicsussion
