### ISSUE TITLE
ATMEL SAM family UART and USART - functions u(s)art_sam_irq_is_pending doesn't respect IRQ settings

### ISSUE THREAD

**Issue by kubiaj** [zephyrproject-rtos/zephyr#13624]
The function  usart_sam_irq_is_pending  (uart_sam_irq_is_pending) return only the masked value of US_CSR register but it doesn't  respect if the IRQ is enabled or not. For proper function it must check if the IRQ is enabled for the event. 

Expected behavior: Return 0  when values in US_CSR are set and IRQs are disabled. 

Impact: Some drivers are not working because they are trying to clear the pending IRQs.

Environment :
 - OS: Linux
 - Toolchain:  Zephyr SDK 
 - Commit SHA: 06d0b6a694a733ba7188ac6df10d314612f720de

PR in progress.

**Comment by kubiaj** [comment]
PR: 13636

**Comment by galak** [comment]
Closing as we merged #13636
