### ISSUE TITLE
mimxrt1050_evk test/crypto/rand32 meets Kernel Panic

### ISSUE THREAD

**Issue by hakehuang** [zephyrproject-rtos/zephyr#13655]
**Describe the bug**
kernel panic and code assert in entropy_mcux_trng.c:27

**To Reproduce**
1. mkdir build; cd build
2. cmake -DBOARD=mimxrt1050_evk  ..
3. make

**Expected behavior**
test runs OK

**Impact**
rng function can not work well

**Screenshots or console output**
```
***** Booting Zephyr OS 1.14.0-rc1 *****

Running test suite common_test

===================================================================

starting test - test_rand32

ASSERTION FAIL [!status] @ /build/src/workspace/rt1050_master-OI33AU5JUM5KTYHISBQ5NMALLT3XI63JEDNQBAUB7MQPDOVV6BBA@2/drivers/entropy/entropy_mcux_trng.c:27

***** Kernel Panic! *****

Current thread ID = 0x80000298

Faulting instruction address = 0x600035a6
```

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain Zephyr SDK
 - Version: v1.14.0_rc1

**Comment by hakehuang** [comment]
@MaureenHelm

**Comment by agansari** [comment]
Tested on commit: [c2d5e7b](https://github.com/zephyrproject-rtos/zephyr/commit/c2d5e7b01ccff8be61ca139f578fdbce84b08713)

```
***** Booting Zephyr OS v1.14.0-rc1-445-gc2d5e7b01c *****
Running test suite common_test
===================================================================
starting test - test_rand32
Generating random numbers
PASS - test_rand32
===================================================================
Test suite common_test succeeded
===================================================================
PROJECT EXECUTION SUCCESSFUL
```

Test passes.

**Comment by MaureenHelm** [comment]
@agansari can you rerun the test on RC1 to make sure you could reproduce the failure?

**Comment by agansari** [comment]
@MaureenHelm I've tested this and #13654 on rc1, but I couldn't reproduce these issues.
@hakehuang can you show me a way to reproduce this issue? Maybe run multiple tests at once?

**Comment by dleach02** [comment]
I'm not able to reproduce either

**Comment by hakehuang** [comment]
I test RC1 based on [588d7b0](https://github.com/zephyrproject-rtos/zephyr/commit/588d7b068c9166f043ccb0f9bf50bf39d0173cee), not [c2d5e7b](https://github.com/zephyrproject-rtos/zephyr/commit/c2d5e7b01ccff8be61ca139f578fdbce84b08713)

**Comment by hakehuang** [comment]
@agansari , yes I run it for multiply time then it will be reproduces

```
***** Booting Zephyr OS 1.14.0-rc1 *****

Running test suite common_test

===================================================================

starting test - test_rand32

ASSERTION FAIL [!status] @ /build/src/workspace/rt1050_master-OI33AU5JUM5KTYHISBQ5NMALLT3XI63JEDNQBAUB7MQPDOVV6BBA@2/drivers/entropy/entropy_mcux_trng.c:27

***** Kernel Panic! *****

Current thread ID = 0x80000278

Faulting instruction address = 0x600035a6


======== Target Main Serial Content:   ========
start application at 0x600062c9 !!!

***** Booting Zephyr OS 1.14.0-rc1 *****

Running test suite common_test

===================================================================

starting test - test_rand32

Generating random numbers

PASS - test_rand32

===================================================================

Test suite common_test succeeded

===================================================================

PROJECT EXECUTION SUCCESSFUL
```

**Comment by agansari** [comment]
@hakehuang can't reproduce with 588d7b068c9166f043ccb0f9bf50bf39d0173cee
After compiling and using make flash board behaves okay, I've restarted (via button SW4) it at least 10 times for each test, but  test passes every time.

**Comment by agansari** [comment]
Is this the same issue as https://github.com/zephyrproject-rtos/zephyr/issues/13654#issuecomment-467702805 ?

**Comment by hakehuang** [comment]
@agansari  yes, close it

**Comment by hakehuang** [comment]
this error is because the FPRC of arm control register is set, then the stack is overflow as there are extra FP pushed. @agansari @nashif
