### ISSUE TITLE
how to init uart3 in stm32_dev_min

### ISSUE THREAD

**Issue by fghjhuang** [zephyrproject-rtos/zephyr#13657]
### i learn the /sample and api refrense, but i didn't see how to init a uart port in codes, can anybody help me?
* i add->"CONFIG_UART_STM32_PORT_1=y" in prj.conf
* `
#include <uart.h>
`
* 
```c
void initUSART(void){ 
	struct uart_config config={
			.baudrate=115200
	};
	usart_dev = device_get_binding("UART3");
	uart_configure(usart_dev,&config); 
} 
void sendUartData(void){
	uart_poll_out(usart_dev,0xff);
}
```
### i init like above, but it turned wrong after i flash into stm32_min_dev board

**Comment by explora26** [comment]
Create stm32_min_dev.overlay
```
&usart3 {
    status = "ok";
};
```
Add "CONFIG_UART_3=y" in prj.conf

**Comment by fghjhuang** [comment]
> Create stm32_min_dev.overlay
> 
> ```
> &usart3 {
>     status = "ok";
> };
> ```
> Add "CONFIG_UART_3=y" in prj.conf

i had add this config, what i mean is that how to init receiver from uart3 & how to send data by uart3? can you help me?

**Comment by explora26** [comment]
Try this, it's sould be work.
```
#include <zephyr.h>
#include <misc/printk.h>
#include <uart.h>

static struct device *uart_dev;

void main(void)
{
	u8_t c;
	struct uart_config config;

	uart_dev = device_get_binding("UART_3");

	uart_config_get(uart_dev, &config);

	config.baudrate = 115200;

	uart_configure(uart_dev, &config);

	while (true) {
		if (uart_poll_in(uart_dev, &c) == 0)
			uart_poll_out(uart_dev, c);
	}
}
```

**Comment by fghjhuang** [comment]
> Try this, it's should be work.
> 
> ```
> #include <zephyr.h>
> #include <misc/printk.h>
> #include <uart.h>
> 
> static struct device *uart_dev;
> 
> void main(void)
> {
> 	u8_t c;
> 	struct uart_config config;
> 
> 	uart_dev = device_get_binding("UART_3");
> 
> 	uart_config_get(uart_dev, &config);
> 
> 	config.baudrate = 115200;
> 
> 	uart_configure(uart_dev, &config);
> 
> 	while (true) {
> 		if (uart_poll_in(uart_dev, &c) == 0)
> 			uart_poll_out(uart_dev, c);
> 	}
> }
> ```

### great! it does work,ths!

**Comment by erwango** [comment]
@fghjhuang , great you managed to work it out. Please tell us when we can close this point.
