### ISSUE TITLE
No Arduino interface definition for Nordic dev. kits

### ISSUE THREAD

**Issue by overheat** [zephyrproject-rtos/zephyr#13708]
**Describe the bug**
When I try to compile "samples\shields\x_nucleo_iks01a1\" for my Nordic dev. kits(pca10040 and pca10056), occurred this error:

```
Error: nrf52840_pca10056.dts.pre.tmp:437.1-13 Label or path arduino_i2c not found
FATAL ERROR: Syntax error parsing input tree
...
Call Stack (most recent call first):
...

-- Configuring incomplete, errors occurred!
```

**To Reproduce**
1. mkdir build; cd build
2. cmake -DBOARD=nrf52840_pca10056
3. make

**Screenshots or console output**
<img width="952" alt="error" src="https://user-images.githubusercontent.com/4322417/53294279-8c910780-381e-11e9-9080-447ead9863ef.png">

** Environment:**
 - OS: ( Windows)
 - Toolchain (Zephyr SDK, ...)
 - Commit SHA or Version used: 1.14-rc1

**Comment by overheat** [comment]
I noticed that the Arduino interface, like default i2c and so on, not been included in the Nordic dev. kits, either pca10040 or pca10056. So I add this patch to nrf52_pca10040.dts and nrf52840_pca10056.dts:

```
@@ -97,7 +97,7 @@
        cts-pin = <7>;
 };

-&i2c0 {
+arduino_i2c: &i2c0 {
        status = "ok";
        sda-pin = <26>;
        scl-pin = <27>;
```
And it works.

Should every Nordic development board add the Arduino interface definition?

**Comment by tanreb1** [comment]
That' s look good, but I think we should add all arduino interfaces. Not only i2c, but spi and uart too. 

+++ ../boards/arm/nrf52840_pca10056/nrf52840_pca10056.dts
@@ -74,6 +74,10 @@
+arduino_i2c: &i2c0 {
    status = "ok";
};
+arduino_spi: &spi1 {
    status = "ok";
};
+arduino_serial: &uart0 {
    status = "ok";
};

**Comment by overheat** [comment]
Hi,

This PR fix the issue and works fine right for my X-NUCLEO-IKS01A1 and 
nrf52840_pca10056!
![nrf52840](https://user-images.githubusercontent.com/4322417/53549237-aa3bd500-3b6e-11e9-95e2-1308191f5e8e.png)

As I also have pca10040 and pca10028 on my hand, I think I can help to fix the same issue on those boards.

**Comment by carlescufi** [comment]
This should be fixed now.
