### ISSUE TITLE
Build failure when using XCC toolchain 

### ISSUE THREAD

**Issue by sathishkuttan** [zephyrproject-rtos/zephyr#13710]
**Describe the bug**
With commit 9c2ac778612da408900ff73feb7310a01634dd46, XCC is invoked with `-nostdinc` flag and this causes compilation errors. The `-nostdinc` flag seems to make XCC not look for header files in `XtensaTools/xtensa-elf/include`

**To Reproduce**
1. `cd $ZEPHYR_BASE/tests/boards/intel_s1000_crb`
1. `mkdir build; cd build`
1. `cmake -DBOARD=intel_s1000_crb ..`
1. `make`
1. See error

**Expected behavior**
Build successful

**Impact**
Can no longer build using XCC

**Screenshots or console output**
```
../../../../../include/toolchain/xcc.h:21:32: error: xtensa/config/core.h: No such file or directory
../../../../../arch/xtensa/include/xtensa_context.h:26:34: error: xtensa/config/tie.h: No such file or directory
../../../../../arch/xtensa/include/xtensa_context.h:27:32: error: xtensa/corebits.h: No such file or directory
../../../../../arch/xtensa/include/xtensa_context.h:28:37: error: xtensa/config/system.h: No such file or directory
../../../../../arch/xtensa/include/xtensa_context.h:29:40: error: xtensa/xtruntime-frames.h: No such file or directory
```
**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: Xtensa
 - Commit SHA or Version used: 9c2ac778612da408900ff73feb7310a01634dd46

**Additional context**
Temporarily removing `-nostdinc` flag for experimentation made the build successful.

**Comment by nashif** [comment]
this should fix it: #13675
