### ISSUE TITLE
mimxrt1060_evk tests/kernel/workq/work_queue meets Illegal use of the EPSR

### ISSUE THREAD

**Issue by hakehuang** [zephyrproject-rtos/zephyr#13765]
**Describe the bug**
Illegal use of the EPSR

**To Reproduce**
1. mkdir build; cd build
2. cmake -DBOARD=mimxrt1060_evk ..
3. make

**Expected behavior**
test pass

**Impact**
work queue usage

**Screenshots or console output**
```
***** Booting Zephyr OS 1.14.0-rc1 *****

Running test suite workqueue

===================================================================

starting test - H=扂?4?#?齪d飈<?簑&Dw?夠8D悓FGyq香跲髹拍Q ?汢o縧s嚬凘?4玤烼a??槼?乨+弳?H 0?滇8??,KBO,

l傖趑
降E馼氅桡=??西{頃畷..?wzY^咣??;厔寸繒g簙?`詪錈?r褵蟼??)J?Y唗=o劕種

***** USAGE FAULT *****

  Illegal use of the EPSR

***** Hardware exception *****

Current thread ID = 0x800001a8

Faulting instruction address = 0x8000031c

Fatal fault in essential thread! Spinning...

```

**Environment (please complete the following information):**
 - OS: (e.g. Linux )
 - Toolchain (Zephyr SDK)
 - Commit SHA or Version used:v1.14.0_rc1

**Comment by hakehuang** [comment]
@MaureenHelm same with #13735

**Comment by hakehuang** [comment]
mix with kernel/fatal failure.

**Comment by MaureenHelm** [comment]
I'm not able to reproduce this. @dleach02, @agansari can you please give it a try?

**Comment by hakehuang** [comment]
@MaureenHelm , @dleach02 , @agansari sorry this is the same root cause as #13727, zephyr does not reinitialize the sp. please ignore this
