### ISSUE TITLE
[Coverity CID :191002]Error handling issues in /tests/net/lib/mqtt_pubsub/src/test_mqtt_pubsub.c

### ISSUE THREAD

**Issue by mandarcthorat1** [zephyrproject-rtos/zephyr#13825]
Static code scan issues seen in File: /tests/net/lib/mqtt_pubsub/src/test_mqtt_pubsub.c
 Category: Error handling issues
 Function: publish_handler
 Component: Tests
 CID: 191002
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by agross-linaro** [comment]
looks like we aren't handing the case where rc == EGAIN.  We need to do a 'continue' in that case.
