### ISSUE TITLE
[Coverity CID :190993]Various in /subsys/shell/shell.c

### ISSUE THREAD

**Issue by mandarcthorat1** [zephyrproject-rtos/zephyr#13831]
Static code scan issues seen in File: /subsys/shell/shell.c
 Category: Various
 Function: execute
 Component: Other
 CID: 190993
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by nashif** [comment]
![image](https://user-images.githubusercontent.com/180017/53710458-500b7000-3e0b-11e9-8fb8-9789bf9679db.png)
