### ISSUE TITLE
[Coverity CID :190986]Control flow issues in /subsys/net/lib/sockets/sockets_tls.c

### ISSUE THREAD

**Issue by mandarcthorat1** [zephyrproject-rtos/zephyr#13837]
Static code scan issues seen in File: /subsys/net/lib/sockets/sockets_tls.c
 Category: Control flow issues
 Function: tls_opt_hostname_set
 Component: Networking
 CID: 190986
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by rlubos** [comment]
It's a false-positive, closing.
