### ISSUE TITLE
[Coverity CID :190972]Control flow issues in /subsys/power/power.c

### ISSUE THREAD

**Issue by mandarcthorat1** [zephyrproject-rtos/zephyr#13847]
Static code scan issues seen in File: /subsys/power/power.c
 Category: Control flow issues
 Function: sys_suspend
 Component: Other
 CID: 190972
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by ceolin** [comment]
false positive caused by `IS_ENABLED` macro. The condition is defined in build time.
