### ISSUE TITLE
[Coverity CID :190974]Integer handling issues in /subsys/net/ip/trickle.c

### ISSUE THREAD

**Issue by mandarcthorat1** [zephyrproject-rtos/zephyr#13845]
Static code scan issues seen in File: /subsys/net/ip/trickle.c
 Category: Integer handling issues
 Function: net_trickle_create
 Component: Networking
 CID: 190974
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by agansari** [comment]
Not an issue
