### ISSUE TITLE
[Coverity CID :190978]Control flow issues in /drivers/spi/spi_intel.c

### ISSUE THREAD

**Issue by mandarcthorat1** [zephyrproject-rtos/zephyr#13842]
Static code scan issues seen in File: /drivers/spi/spi_intel.c
 Category: Control flow issues
 Function: push_data
 Component: Drivers
 CID: 190978
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by pfalcon** [comment]
Also handled by @maxxlife in https://github.com/zephyrproject-rtos/zephyr/pull/13806, which was earlier. (@maxxlife, that shows that if you start working on a ticket, it makes sense to add a comment to it about that).

**Comment by maxxlife** [comment]
> 
> 
> Also handled by @maxxlife in #13806, which was earlier. (@maxxlife, that shows that if you start working on a ticket, it makes sense to add a comment to it about that).

Ok. I just didn't see that thread, maybe it appeared later.
