### ISSUE TITLE
[Coverity CID :190971]Null pointer dereferences in /subsys/net/ip/net_pkt.c

### ISSUE THREAD

**Issue by mandarcthorat1** [zephyrproject-rtos/zephyr#13848]
Static code scan issues seen in File: /subsys/net/ip/net_pkt.c
 Category: Null pointer dereferences
 Function: net_pkt_cursor_operate
 Component: Networking
 CID: 190971
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by agansari** [comment]
Not an issue
