### ISSUE TITLE
[Coverity CID :190970]Uninitialized variables in /subsys/bluetooth/shell/ll.c

### ISSUE THREAD

**Issue by mandarcthorat1** [zephyrproject-rtos/zephyr#13849]
Static code scan issues seen in File: /subsys/bluetooth/shell/ll.c
 Category: Uninitialized variables
 Function: cmd_advx
 Component: Bluetooth
 CID: 190970
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by ceolin** [comment]
#13975
