### ISSUE TITLE
[Coverity CID :190977]Integer handling issues in /lib/os/printk.c

### ISSUE THREAD

**Issue by mandarcthorat1** [zephyrproject-rtos/zephyr#13843]
Static code scan issues seen in File: /lib/os/printk.c
 Category: Integer handling issues
 Function: _vprintk
 Component: Other
 CID: 190977
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by ceolin** [comment]
false positive, the problem is spotted because in the architecture tested, long and int has the same size.
