### ISSUE TITLE
[Coverity CID :190957]Incorrect expression in /tests/kernel/fatal/src/main.c

### ISSUE THREAD

**Issue by mandarcthorat1** [zephyrproject-rtos/zephyr#13858]
Static code scan issues seen in File: /tests/kernel/fatal/src/main.c
 Category: Incorrect expression
 Function: check_stack_overflow
 Component: Tests
 CID: 190957
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by andrewboie** [comment]
I set this in Coverity as a false positive, it thought there might be side effects of reading a volatile variable (in case it was some MMIO thing) but that wasn't the case here.
