### ISSUE TITLE
[Coverity CID :190960]Various in /tests/subsys/fs/fcb/src/fcb_test_last_of_n.c

### ISSUE THREAD

**Issue by mandarcthorat1** [zephyrproject-rtos/zephyr#13856]
Static code scan issues seen in File: /tests/subsys/fs/fcb/src/fcb_test_last_of_n.c
 Category: Various
 Function: fcb_test_last_of_n
 Component: Tests
 CID: 190960
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by varun-sha** [comment]
Its false positive, all entries are getting assigned in for loop before being used
