### ISSUE TITLE
[Coverity CID :190966]Error handling issues in /samples/net/sockets/echo_async_select/src/socket_echo_select.c

### ISSUE THREAD

**Issue by mandarcthorat1** [zephyrproject-rtos/zephyr#13852]
Static code scan issues seen in File: /samples/net/sockets/echo_async_select/src/socket_echo_select.c
 Category: Error handling issues
 Function: main
 Component: Samples
 CID: 190966
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by agross-linaro** [comment]
Looks like it needs to be 1ULL instead of 1U

**Comment by agross-linaro** [comment]
https://github.com/zephyrproject-rtos/zephyr/pull/13967
