### ISSUE TITLE
[Coverity CID :190949]Error handling issues in /tests/subsys/fs/nffs_fs_api/common/test_append.c

### ISSUE THREAD

**Issue by mandarcthorat1** [zephyrproject-rtos/zephyr#13866]
Static code scan issues seen in File: /tests/subsys/fs/nffs_fs_api/common/test_append.c
 Category: Error handling issues
 Function: test_append
 Component: Tests
 CID: 190949
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by ceolin** [comment]
#13976
