### ISSUE TITLE
[Coverity CID :190946]Null pointer dereferences in /tests/net/utils/src/main.c

### ISSUE THREAD

**Issue by mandarcthorat1** [zephyrproject-rtos/zephyr#13868]
Static code scan issues seen in File: /tests/net/utils/src/main.c
 Category: Null pointer dereferences
 Function: test_utils
 Component: Tests
 CID: 190946
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by jukkar** [comment]
False positive.
