### ISSUE TITLE
[Coverity CID :190951]Control flow issues in /subsys/net/ip/net_context.c

### ISSUE THREAD

**Issue by mandarcthorat1** [zephyrproject-rtos/zephyr#13864]
Static code scan issues seen in File: /subsys/net/ip/net_context.c
 Category: Control flow issues
 Function: bind_default
 Component: Networking
 CID: 190951
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by jukkar** [comment]
False positive.
