### ISSUE TITLE
[Coverity CID :190943]Incorrect expression in /tests/kernel/fatal/src/main.c

### ISSUE THREAD

**Issue by mandarcthorat1** [zephyrproject-rtos/zephyr#13871]
Static code scan issues seen in File: /tests/kernel/fatal/src/main.c
 Category: Incorrect expression
 Function: check_stack_overflow
 Component: Tests
 CID: 190943
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by andrewboie** [comment]
Closed as false positive (and updated in Coverity), reading crash_reason has no implicit side effects.
