### ISSUE TITLE
[Coverity CID :190942]Memory - corruptions in /subsys/mgmt/smp_shell.c

### ISSUE THREAD

**Issue by mandarcthorat1** [zephyrproject-rtos/zephyr#13872]
Static code scan issues seen in File: /subsys/mgmt/smp_shell.c
 Category: Memory - corruptions
 Function: read_mcumgr_byte
 Component: Other
 CID: 190942
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by AdithyaBaglody** [comment]
False positive. mentioned this is coverity.
