### ISSUE TITLE
[Coverity CID :190929]Integer handling issues in /tests/drivers/hwinfo/api/src/main.c

### ISSUE THREAD

**Issue by mandarcthorat1** [zephyrproject-rtos/zephyr#13884]
Static code scan issues seen in File: /tests/drivers/hwinfo/api/src/main.c
 Category: Integer handling issues
 Function: test_device_id_get
 Component: Tests
 CID: 190929
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by ceolin** [comment]
#13968
