### ISSUE TITLE
[Coverity CID :190930]Integer handling issues in /samples/subsys/fs/src/main.c

### ISSUE THREAD

**Issue by mandarcthorat1** [zephyrproject-rtos/zephyr#13883]
Static code scan issues seen in File: /samples/subsys/fs/src/main.c
 Category: Integer handling issues
 Function: main
 Component: Samples
 CID: 190930
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by ceolin** [comment]
please remember close coverity issue :)
