### ISSUE TITLE
[Coverity CID :190928]Error handling issues in /samples/net/sockets/echo_async/src/socket_echo.c

### ISSUE THREAD

**Issue by mandarcthorat1** [zephyrproject-rtos/zephyr#13885]
Static code scan issues seen in File: /samples/net/sockets/echo_async/src/socket_echo.c
 Category: Error handling issues
 Function: main
 Component: Samples
 CID: 190928
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by jukkar** [comment]
This is not about CAN but to generic socket, setting label and assigning to @pfalcon
