### ISSUE TITLE
[Coverity CID :190925]Memory - corruptions in /subsys/bluetooth/controller/hci/hci_driver.c

### ISSUE THREAD

**Issue by mandarcthorat1** [zephyrproject-rtos/zephyr#13887]
Static code scan issues seen in File: /subsys/bluetooth/controller/hci/hci_driver.c
 Category: Memory - corruptions
 Function: process_hbuf
 Component: Bluetooth
 CID: 190925
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by carlescufi** [comment]
Dismissed in coverity
