### ISSUE TITLE
stm32f429i_disc1: Add DTS for USB controller

### ISSUE THREAD

**Issue by finikorg** [zephyrproject-rtos/zephyr#13894]
Add DTS for USB Controller for ST STM32F429I-DISC1 Discovery board

**Comment by finikorg** [comment]
@mbolivar Could you check this?

**Comment by mbolivar** [comment]
> @mbolivar Could you check this?

@finikorg did you mean to @-mention someone else? I don't have this board and don't work with USB on Zephyr.

**Comment by finikorg** [comment]
Closing
