### ISSUE TITLE
tests/crypto/mbedtls reports some errors without failing

### ISSUE THREAD

**Issue by andrewboie** [zephyrproject-rtos/zephyr#13919]
Observe output of tests/crypto/mbedls:

```
Running test suite test_mbedtls_fn
===================================================================
starting test - test_mbedtls
starting test - Performing mbedTLS crypto tests:
the snprintf implementation is broken

 MBEDTLS_SELF_TEST not defined.
  Executed 0 test suites

  [ All tests PASS ]

PASS - test_mbedtls
===================================================================
===================================================================
PROJECT EXECUTION SUCCESSFUL
PASS - test_mbedtls
===================================================================
Test suite test_mbedtls_fn succeeded
===================================================================
PROJECT EXECUTION SUCCESSFUL
```

Need to understand these two error messages and why they are printed. I am very unsure on priority.

> the snprintf implementation is broken

>  MBEDTLS_SELF_TEST not defined.
>   Executed 0 test suites

**Comment by andrewboie** [comment]
As far as I can tell, almost this entire test case is a no-op since 
MBEDTLS_SELF_TEST is not defined

**Comment by andrewboie** [comment]
I saw the patch #14016 
Does this also fix the `the snprintf implementation is broken` message?

**Comment by nashif** [comment]
> Does this also fix the `the snprintf implementation is broken` message?

ah, I missed this one.
