### ISSUE TITLE
tests: Ztest problem - not booting properly

### ISSUE THREAD

**Issue by MarekPieta** [zephyrproject-rtos/zephyr#13949]
**Describe the bug**
Problem with ztest - not booting properly.

**To Reproduce**
Steps to reproduce the behavior (using samples/testing/integration):
1. mkdir build; cd build
2. cmake -DBOARD=nrf52810_pca10040
3. make flash

During test I was using RTT_console.

**Expected behavior**
Messages about successfully finished tests should be displayed.

**Screenshots or console output**
```
***** Booting Zephyr OS v1.14.0-rc1-624-ge731bdc81a3b *****
ASSERTION FAIL [num_parts <= max_partitions] @ /home/mapi/ncs/zephyr_original/zephyr/kernel/mem_domain.c:90
	
***** Kernel Panic! *****
Current thread ID = 0x20000748
Faulting instruction address = 0x1340

```

**Environment:**
 - OS: Linux
 - Toolchain: Zephyr SDK 0.9.5
 - Commit: e731bdc81a3b2e2fdf498bccab9627b18fa38de6

**Additional context**
It used to work properly before. Sample commit when working: df7162331f831ac6a0ce108d7c512573ffb51ce0

**Comment by ioannisg** [comment]
The reason is described here, @MarekPieta : #13889
