### ISSUE TITLE
stm32: Implement async uart api 

### ISSUE THREAD

**Issue by erwango** [zephyrproject-rtos/zephyr#13955]
**Is your feature request related to a problem? Please describe.**
UART_ASYNC_API is not available yet on stm32  target.
Implement it

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context or graphics (drag-and-drop an image) about the feature request here.

**Comment by StefJar** [comment]
I done a demo implementation
which could be used as a [blueprint](https://github.com/StefJar/zephyr_stm32_uart3_dma_driver)

**Comment by erwango** [comment]
Fixed: https://github.com/zephyrproject-rtos/zephyr/pull/30917
