### ISSUE TITLE
no serialport output 

### ISSUE THREAD

**Issue by spring-z** [zephyrproject-rtos/zephyr#1397]
hello_word samples run 

`make BOARD=nucleo_f103rb flash`

serialport no output `Hello World! arm`.

Can you tell me what did I do wrong?

**Comment by chunshanzhu** [comment]
port1 or port2? f103rb use port2 as the default serial port

**Comment by spring-z** [comment]
ok，I try again

**Comment by dbkinder** [comment]
Alas, there is no documentation for the F103RB board, as noted in [ZEP-1907](https://jira.zephyrproject.org/browse/ZEP-1907).  The documentation for the  [F103RE board](https://www.zephyrproject.org/doc/boards/arm/nucleo_f401re/doc/nucleof401re.html) states that, "Nucleo F401RE board has 3 UARTs. The Zephyr console output is assigned to UART2. Default settings are 115200 8N1."

**Comment by nashif** [comment]
works fine for me:

Board appears as
```
/sys/bus/usb/devices/3-10.4: STMicroelectronics STM32 STLink serial: '066EFF535550755187031831', tty(s): ttyACM0
```
run:
```
sudo  screen -L  /dev/ttyACM0 115200
```

and you get serial output.

**Comment by spring-z** [comment]
no i not get Hello World! arm，
