### ISSUE TITLE
nucleo_l496zg: samples: console/echo: It doesn't echo

### ISSUE THREAD

**Issue by gon1332** [zephyrproject-rtos/zephyr#13984]
**Describe the bug**
The echo sample doesn't seem to work as expected.
The motivation to try this sample, was after I wrote a sample using tty.h and it could not receive data through `tty_read()`. My sample is a driver for a camera module. I've also mocked the camera behaviour via FTDI but nothing this function doesn't seem to response. I've also tried different UART ports.

**To Reproduce**
1. west build -b nucleo_l496zg -s samples/subsys/console/echo
2. west flash
3. Type anything
4. See unexpected behaviour

**Expected behavior**
It should echo back the input.

**Screenshots or console output**
In the output below, you can also see this artifact. It happens every time when the sample starts.
```
***** Booting Zephyr OS v1.14.0-rc1-669-g9ec9c430b312 *****
You should see another line with instructions below. If not,
the (interrupt-driven) console device doesn't work as expected:
Start typing characters to see them echoed back
�I speak to the void, but it doesn't echo back to me..
```

**Environment (please complete the following information):**
 - OS: Linux with minicom
 - Toolchain: Zephyr SDK
 - Commit hash: 9ec9c430b

**Comment by pfalcon** [comment]
If that's actual console-shot, then it actually shows characters echoed back ;-).

Otherwise, as the sample suggest, there's an issue with interrupt-driven UART functions implementation.

Can you try other BOARD's, starting with qemu_x86 ?

**Comment by gon1332** [comment]
Damn, you're right. Sorry for that one.
