### ISSUE TITLE
drivers: modem: modem receiver is sending extra bytes around \r\n

### ISSUE THREAD

**Issue by rerickson1** [zephyrproject-rtos/zephyr#14001]
**Describe the bug**
Extra 0's are being added before and after the '\r\n' terminator of every at command sent.
I am using an NRF52840 host processor to communicate with an HL7800 modem.

**To Reproduce**
This should be easily reproducible using the WNC modem driver with the NRF52840. 

**Expected behavior**
Extra bytes should not be inserted into the messages being sent on the UART.

**Impact**
Showstopper for continuing my driver development.

**Screenshots or console output**
![extra_bytes](https://user-images.githubusercontent.com/4430317/53666045-aa9da400-3c32-11e9-8b27-0a3197bb9784.png)

**Environment (please complete the following information):**
 - OS: Windows 10
 - Toolchain: GCC 7_2018-q2-update
 - Commit SHA or Version used: Zephyr 5f2099fb63ba73ab94ee1a636b91cc77890f052a

@mike-scott

**Comment by mike-scott** [comment]
@rerickson1 Confirming, that with my analyzer, I'm also seeing NULL characters sent to the wire.  Oddly, this doesn't break communications on the WNC-M14A2A modem.  So, I didn't notice it during my testing.

I'll submit a fix shortly.

NOTE: Love that Saleae UI.
