### ISSUE TITLE
Support for PPP protocol

### ISSUE THREAD

**Issue by shlomow** [zephyrproject-rtos/zephyr#14034]
Hi! I saw that there is a porting for a cellular device. I wonder if there is any idea for implementing the ppp layer 2 stack, since it is very convenient to handle sockets riding on ppp.

Thanks!
Shlomi

**Comment by nashif** [comment]
@laperie fyi

**Comment by jukkar** [comment]
I am actually working on this right now. Current plan is to implement a dedicated PPP L2 layer in networking stack, and initially support LCP, IPCP and IPv6CP. Target release would be 1.15.

**Comment by shlomow** [comment]
Thanks for the reply! Since ppp is mostly used by cellular devices there will be a generic library to handle 3gpp at commands?

**Comment by llisauskas** [comment]
@jukkar Are you targeting cellular devices? 
Most often embedded devices communicate with cellular modems via UART and designating it only for PPP limits modem features severely (env. monitoring such as serving and/or visible cells, SMS operations, incoming/outgoing calls and so on are unavailable if port is used by PPP). Have you thought about implementing CMUX (3GPP TS 07.10 multiplexer) to overcome this?
