### ISSUE TITLE
CONFIG_XUK_64_BIT_ABI is referenced but undefined (outside of tests)

### ISSUE THREAD

**Issue by ulfalizer** [zephyrproject-rtos/zephyr#14059]
No `XUK_64_BIT_ABI` Kconfig symbol ever existed. `CONFIG_XUK_64_BIT_ABI` is only set in `arch/x86_64/core/xuk-config.h`, which seems to be used for testing, so the `#ifdef CONFIG_XUK_64_BIT_ABI` in `arch/x86_64/core/xuk.c` is dead code outside of testing.

Trying to remove `CONFIG_FOO` references where `FOO` is not a Kconfig symbol, for a CI check.

**Comment by andyross** [comment]
Yeah, this was an evolution of the internal configuration values to kconfigs, except that Zephyr itself has never built in anything but x32, so it never got referenced.  Will make it internal again pending a work to make zephyr work with 64 bit pointer sizes.
