### ISSUE TITLE
net: ipv6: Neighbor table management improvements

### ISSUE THREAD

**Issue by lbise** [zephyrproject-rtos/zephyr#14063]
I've been using a setup where potentially a large number of neighbor can be added to the nbr table. With this I noticed that the neighbor management generally speaking could use some improvements and fixes.

Some issues I found:

Currently when a neighbor is added to the table, it is never ever removed. I think the intent was to remove neighbors from the table on 3 conditions, if it reaches the stale state and stays stale for a certain amount of time, if it reaches the probe state and the probe fails or if it reaches the incomplete state and the probe fails.
However currently all these 3 cases do not remove the neighbors from the table. The culprit is in the ipv6_nbr.c function ipv6_nd_reachable_timeout (https://github.com/zephyrproject-rtos/zephyr/blob/69836455521656fbaeb16c35f48621f26b56a9a5/subsys/net/ip/ipv6_nbr.c#L1256).

Stale entries are not remove because ipv6_nd_reachable_timeout NET_IPV6_NBR_STATE_STALE is never actually executed, this is because when going from the REACHABLE to the STALE state the reachable timer is not set therefore the nbr will always be skipped (this is checked at the beginning of the function).

Probe entries are a bit different, the nbr can be removed but only if it is a router? Not really sure I understand why (https://github.com/zephyrproject-rtos/zephyr/blob/69836455521656fbaeb16c35f48621f26b56a9a5/subsys/net/ip/ipv6_nbr.c#L1345). Otherwise nothing is done and the nbr is left in the table.

Incomplete entries, which are similar functionally to probe are again not working properly, in that only the first probe will be sent, after that none will be sent again because the reachable timer is not set (https://github.com/zephyrproject-rtos/zephyr/blob/69836455521656fbaeb16c35f48621f26b56a9a5/subsys/net/ip/ipv6_nbr.c#L1303).

Another issue I found is that, when attempting to free a nbr they use the nbr_free function, but I think they should be using net_ipv6_nbr_rm because otherwise if the nbr was part of a route, the reference will not be removed.

Finally, I think the restart of the delayed work could be improved, currently the first work not elapsed will trigger a work submit (https://github.com/zephyrproject-rtos/zephyr/blob/69836455521656fbaeb16c35f48621f26b56a9a5/subsys/net/ip/ipv6_nbr.c#L1281), so if it's timeout is bigger than the next item, the second item will be delayed by this much. This might not be noticeable but if stale timeout is added, and it's several minutes it might not work properly.

I think that sums up the issues I found.

**Comment by laperie** [comment]
This looks more like a bug; hence changing labels and assigning to @jukkar. 
Thanks @lbise  for reporting!

**Comment by nashif** [comment]
@laperie set priority please

**Comment by jukkar** [comment]
@lbise Thanks for the detailed analysis. Did it cause any major issues when nbr table got full with stale neighbors? I am pondering if we could do the improvements in 1.15 release.

**Comment by laperie** [comment]
While waiting for @lbise to answer, setting priority:low as we have no other reports of this problem

**Comment by lbise** [comment]
The system kept working it was just incapable of communicating with the neighbors that could not be added to the table. But nothing major like crash or anything like that.

**Comment by jukkar** [comment]
> The system kept working it was just incapable of communicating with the neighbors that could not be added to the table.

Ok, this is indeed bad too. Lets try to fix this as there is certainly impact to functionality of the device.

**Comment by rveerama1** [comment]
@lbise I tried to address as much as possible (https://github.com/zephyrproject-rtos/zephyr/pull/14557). Can you please test this with your environment and let me know?

**Comment by lbise** [comment]
Thank you @rveerama1. I'll give it a try and report back.
