### ISSUE TITLE
Allow better control on SPI pin settings

### ISSUE THREAD

**Issue by pdunaj** [zephyrproject-rtos/zephyr#14068]
**Is your enhancement proposal related to a problem? Please describe.**
This issue concerns Nordic SoCs SPI. At the moment there is no possibility to control MISO pull per SPI instance.

**Describe the solution you'd like**
It would be great to be able to control pull for each bus pin separately. This will requite a companion change in nrfx.

**Describe alternatives you've considered**
At the moment switch in Kconfix is added to allow MISO pull control for SPI type.

**Additional context**
https://github.com/zephyrproject-rtos/zephyr/issues/13901

**Comment by 5frank** [comment]
Another possible workaround is the `miso-pull-up` and `miso-pull-down` property. Example
```
&spi 0 {
    compatible = "nordic,nrf-spi";
    miso-pull-up;
    ...
}
```

**Comment by gmarull** [comment]
This is now possible using pinctrl, closing.
