### ISSUE TITLE
[bluetooth controller]

### ISSUE THREAD

**Issue by Tsai1005** [zephyrproject-rtos/zephyr#14091]
**Is your feature request related to a problem? Please describe.**
As a bluetooth controller manufacture, I found the code in subsys/bluetooth/controller is only for nordic implementation and not port friendly to other vendors.

**Describe the solution you'd like**
The files in subsys/bluetooth/controller need to be separate by vendor-specific and keep the common logic (which refer to the Bluetooth core spec) code in common directory.

**Comment by aescolar** [comment]
This is being worked on. Is what is called the split link layer. See
https://github.com/zephyrproject-rtos/zephyr/issues/12681
