### ISSUE TITLE
Minnowboard doesn't build tests/kernel/xip/

### ISSUE THREAD

**Issue by galak** [zephyrproject-rtos/zephyr#14099]
`./scripts/sanitycheck -p minnowboard -T tests/kernel/xip/` fails to build

We get the following error:

```
Memory region 2 (10a000:9b4000) overlaps memory region 0 (401000:80400000)
```

**Comment by andrewboie** [comment]
this test shouldn't be enabled for minnowboard, it is not an execute in place system, the entire kernel is put in RAM by the bootloader
