### ISSUE TITLE
Regression added by commit cd35742a (net/ethernet/arp: Let ethernet L2 managing pkt's reference while sending)

### ISSUE THREAD

**Issue by mike-scott** [zephyrproject-rtos/zephyr#1416]
On FRDM-K64F, our upstream CI testing showed the following BUS FAULT after commit cd35742a was introduced:

PROJECT EXECUTION SUCCESSFUL
***** BUS FAULT *****
  Executing thread ID (thread): 0x20002ca8
  Faulting instruction address:  0x24a0a
  Precise data bus error
  Address: 0xbd990258
Fatal fault in essential thread! Spinning...

I will add more details once I have time to debug.

**Comment by mike-scott** [comment]
NOTE This is only on master branch and does not affect v1.9

**Comment by mike-scott** [comment]
Faulting instruction address correlates to: include/net/buf.h:1024

**Comment by mike-scott** [comment]
And verified that reverting commit cd35742a2bae38a468d9163ee797f9e9b5fa194d fixes the BUS FAULT

**Comment by pfalcon** [comment]
I built echo_server for frdm_k64f. It starts up ok, but on first ping received, crashes:

~~~
[dev/eth_mcux] [DBG] eth_0_init: MAC 00:04:9f:54:59:16
shell> [dev/eth_mcux] [INF] eth_mcux_phy_event: Enabled 100M full-duplex mode.
***** BUS FAULT *****
  Executing thread ID (thread): 0x20001b28
  Faulting instruction address:  0x44ce
  Precise data bus error
  Address: 0xc63cfe56
Fatal fault in essential thread! Spinning...
~~~

**Comment by pfalcon** [comment]
@tbursztyka : ^^^

(also pinged on IRC)

**Comment by pfalcon** [comment]
Confirmed https://github.com/zephyrproject-rtos/zephyr/pull/1455 fixes this.

**Comment by pfalcon** [comment]
Also, noticed frdm_k64f didn't respond to "ping6 2001:db8::1", confirmed https://github.com/zephyrproject-rtos/zephyr/pull/1449 fixes it.

**Comment by mike-scott** [comment]
Thanks @jukkar !
