### ISSUE TITLE
kconfig options need some cleanup and reorganisation

### ISSUE THREAD

**Issue by nashif** [zephyrproject-rtos/zephyr#1418]
When you invoke 'make menuconfig' you get a view of the structure of the Kconfig variables in the kernel. Right now we have a few stray options that appear at the very top level when those should be hidden in sub-menus or should be depending on other features. Need to cleanup the structure and make sure we have all Kconfigs where they belong.

![image](https://user-images.githubusercontent.com/180017/30332119-92829712-97a7-11e7-8d4d-771506cc5446.png)

**Comment by galak** [comment]
Any specific details on what options are stray?

**Comment by nashif** [comment]
interrupt configuration, fatal handler... those are now fixed, still a few, see attachment.

**Comment by aescolar** [comment]
@ulfalizer : Maybe you have a bit of time to check if this is consistent already?

**Comment by nashif** [comment]
closing, lots of effort and work was put into this already..
