### ISSUE TITLE
tests/benchmarks: Stuck at  delaying boot banner on quark_se_c1000_ss_board

### ISSUE THREAD

**Issue by cinlyooi-intel** [zephyrproject-rtos/zephyr#14184]
**Describe the bug**
Only seeing `***** delaying boot 1000ms (per build configuration *****`
Not seeing the follow up `***** Booting Zephyr OS v1.14.0-rc1-885-g32caf24cb4aa (delayed boot 1000ms) *****`

**To Reproduce**
1. mkdir build; cd build
2. cmake -DBOARD=quark_se_c1000_ss_board -DARCH=arc
3. make
4. make run

**Screenshots or console output**
```
***** delaying boot 1000ms (per build configuration) *****
```

**Environment (please complete the following information):**
 - OS: fedora29
 - Toolchain: zephyr
 - Commit SHA or Version used:  1f74e0b1f75eff63568c1c807f003df7c3b7793b

**Additional context**
I added `printk()` statement to the start of `main()` and it did not get print out on the console. This strongly suggests the main() function was not entered.

**Comment by AdithyaBaglody** [comment]
@cinlyooi-intel unable to reproduce this issue. tested with timing_info. works as expected.

**Comment by cinlyooi-intel** [comment]
@AdithyaBaglody Still have the same problem on 4278bf5673480effdca3b1e048cecb7a9ab32976
My description of the problem is bad. Thanks for figuring out it is `timing_info`

**Comment by rljordan** [comment]
@AdithyaBaglody  It appears this is still an issue.

**Comment by AdithyaBaglody** [comment]
I am unable to reproduce this issue with the latest master f4c8e3ff3197d36773d68b4b4802daabc401f918

**Comment by rljordan** [comment]
@cinlyooi-intel  Can this be closed?

**Comment by cinlyooi-intel** [comment]
@rljordan : Sorry I cannot close it. I am still seeing it on latest master (193fb971c24f827464982307b5b3bb34de0fa98d). However, if someone can show that it cannot be reproduced on a real board then we can close it.

**Comment by AdithyaBaglody** [comment]
>cannot be reproduced on a real board then we can close it.

@cinlyooi-intel how are you testing this? because I am not able to see this issue on the actual hardware. if you are testing on a test framework then please assign it to the respective person so that this can move ahead.

**Comment by cinlyooi-intel** [comment]
Closed it since @AdithyaBaglody says it works on actual hardware.
