### ISSUE TITLE
unable to flash sam_e70_xplained due to west errors

### ISSUE THREAD

**Issue by andrewboie** [zephyrproject-rtos/zephyr#14209]
I cloned the Zephyr repo like I usually do.

    git clone git@github.com:zephyrproject-rtos/zephyr.git
    cd zephyr
    source zephyr-env.sh
    cd tests/crypto/rand32

I then build a test case in the normal way:

    mkdir out
    cd out
    export BOARD=sam_e70_xplained
    cmake ..
    make -j8

I then try to flash:

    make flash

I get:

```
West version found in path does not support '/usr/bin/gmake flash', ensure west is installed and not only the bootstrapper. run 'west init' to fetch west.
Built target flash
```

This used to work. I have installed west 0.5.4 with pip3.

**Comment by carlescufi** [comment]
@andrewboie can you run:

```
west update
west --version
```

from your zephyr folder?

**Comment by andrewboie** [comment]
I didn't setup a parent folder with west initialized in it.
Closing since this is required for flashing to work.
