### ISSUE TITLE
Logging Kconfig options are confusing

### ISSUE THREAD

**Issue by ulfalizer** [zephyrproject-rtos/zephyr#14240]
There's these two options in `(top menu) -> Logging Options`:

![Skärmbild från 2019-03-10 05-52-32](https://user-images.githubusercontent.com/154768/54080815-c5d67680-42f8-11e9-90ad-bbbdcad071ad.png)
![Skärmbild från 2019-03-10 05-52-47](https://user-images.githubusercontent.com/154768/54080816-c838d080-42f8-11e9-95c2-1dde3cee0b82.png)

The prompts don't tell you how they differ, and even after reading the help texts, it's still confusing.

For example, if `Enable Logging` is on and `Enable Logger` is off, then that says that log calls will be executed even though they're not compiled in.

Not looking for an explanation. Just saying that it could probably be made clearer, e.g. with better prompts/help texts.

**Comment by jukkar** [comment]
The "Enable Logging" is the legacy SYS_LOG logging. I thought we had already deprecated it.

**Comment by nordic-krch** [comment]
@nashif should we remove sys_log at all? Do want that in LTS? It'sremoed from the documentation and not used in the tree.

**Comment by jfischer-phytec-iot** [comment]
Please remove it or at last change the prompt.

**Comment by ulfalizer** [comment]
@nordic-krch @jfischer-phytec-iot 
Would you be happy with something like "Enable logger" and "Enable legacy logger" in the meantime?

**Comment by jfischer-phytec-iot** [comment]
>Would you be happy with something like "Enable logger" and "Enable legacy logger" in the meantime?

okay

**Comment by nashif** [comment]
> @nashif should we remove sys_log at all? Do want that in LTS? It's removed from the documentation and not used in the tree.

yes, I would actually remove it altogether. Looks like we just forgot about it.

**Comment by ulfalizer** [comment]
SYS_LOG was removed in https://github.com/zephyrproject-rtos/zephyr/pull/14883.
