### ISSUE TITLE
spi.h and spi_legacy.h documentation conflicts

### ISSUE THREAD

**Issue by dbkinder** [zephyrproject-rtos/zephyr#1425]
There are types and function names duplicated by these two include files that are causing the doxygen-generated API docs to be confused (material from both .h files is being combined into one since the names are the same).  Are both .h files needed?

**Comment by dbkinder** [comment]
Addresses #1415

**Comment by nashif** [comment]
need to exclude spi_legacy.h, no need to show it, the right header to show is spi.h
