### ISSUE TITLE
DTS file for the esp32

### ISSUE THREAD

**Issue by Michael2196** [zephyrproject-rtos/zephyr#14261]
**Describe the bug**
I'm working on developing the device tree for the esp32 (gpio). To do so, I'm trying to understand the Uart example already developed under the esp32 device tree. However, I'm having trouble understanding some basic concepts. In the esp32.dts file, under &uart0, I modified the current speed from 115200 to 9600. To my surprise, after flashing the esp32 the baud rate is still at 115200. 

**To Reproduce**
1. cd /samples/helloworld/
2.mkdir build; cd build
3. cmake -GNinja -DESP_IDF_PATH=$ESP_IDF_PATH -DBOARD=esp32 ..
4. ninja && west flash -d ./ --skip-rebuild --esp-device /dev/ttyACM0'
5.  minicom -D /dev/ttyUSB0 -b 9600

**Expected behavior**
Hello World on the console

**Impact**
Can't work on the device tree

**Environment (please complete the following information):**
 - OS: (Linux)
 - Toolchain (Zephyr SDK, espressif ...)

**Additional context**
I'm still trying to understand the concept of device tree. This would be a big help. 
Thank you

**Comment by galak** [comment]
This is because the driver doesn't support setting the baud rate at all. Take a look at `drivers/serial/uart_esp32.c`
