### ISSUE TITLE
samples/drivers/flash_shell doesn't rely on drivers/flash/flash_shell

### ISSUE THREAD

**Issue by erwango** [zephyrproject-rtos/zephyr#14260]
**Is your enhancement proposal related to a problem? Please describe.**
samples/drivers/flash_shell implements an alternative to drivers/flash/flash_shell.
Hence, we're maintaining two files that do equivalent processing and the sample does not allow to validate the driver.

**Describe the solution you'd like**
Implement samples/drivers/flash_shell based on drivers/flash/flash_shell

**Describe alternatives you've considered**

**Additional context**
Add any other context or graphics (drag-and-drop an image) about the feature request here.

**Comment by erwango** [comment]
@nvlsianpu  I'm adding you as assignee. Feel free to close if you think this is not something we want.

**Comment by erwango** [comment]
@nvlsianpu Feel free to close if you don't think this should be tackled.

**Comment by nvlsianpu** [comment]
@erwango I think this ticket is still valid.

**Comment by nashif** [comment]
This is really bug IMO

**Comment by cfriedt** [comment]
Just some observations: 
- `tests/drivers/flash` does not seem very complete
  - only 1 test
  - gives false reassurance that drivers are properly implemented
- `drivers/flash/flash_shell.c` utility does not work on esp32-c3
  - not sure why, as it passes all 1 tests from `tests/drivers/flash`
- `samples/drivers/flash_shell` utility does work on esp32-c3
  - it's obviously doing something different than `drivers/flash/flash_shell.c`
  - solution is not as simple as implementing `samples/drivers/flash_shell` on top of `drivers/flash/flash_shell`
  - likely needs to be merged with some attention paid to detail
  - additional testsuite coverage would be nice!

**Comment by erwango** [comment]
Done. Closing
