### ISSUE TITLE
USB HID Get_Report and Set_Report

### ISSUE THREAD

**Issue by masz-nordic** [zephyrproject-rtos/zephyr#14287]
**Is your enhancement proposal related to a problem? Please describe.**
Get_Report and Set_Report requests are not implemented in USB HID class.

**Describe the solution you'd like**
Both requests should be implemented and tested. Existing HID examples should be able to handle them.

**Describe alternatives you've considered**
None, this is basic HID functionality.

**Additional context**
Device Class Definition for Human Interface Devices (HID) Version 1.11
Chapters 7.2.1 and 7.2.2

**Comment by finikorg** [comment]
Already implemented.
