### ISSUE TITLE
LWM2M configs not defined

### ISSUE THREAD

**Issue by nashif** [zephyrproject-rtos/zephyr#1429]
LWM2M_BOOTSTRAP_SERVER not defined anywhere, yet being used here:

 subsys/net/lib/lwm2m/lwm2m_rd_client.c:#if defined(CONFIG_LWM2M_BOOTSTRAP_SERVER)

**Comment by nashif** [comment]
same for 
LWM2M_SECURITY_OBJ_SUPPORT
LWM2M_DEVICE_PWRSRC_MAX

**Comment by mike-scott** [comment]
Thanks @nashif.  I'll include fixing these in my next series.

**Comment by nashif** [comment]
was this fixed?

**Comment by mike-scott** [comment]
Not yet.  I can land a patch for this after the multi-fragment support is merged.

**Comment by mike-scott** [comment]
These configs will be addressed in the upcoming patches to support LwM2M bootstrap.  If there's a priority I can remove them, but some of the code will come right back later.

**Comment by mike-scott** [comment]
This adds the LWM2M_DEVICE_PWRSRC_MAX config:
https://github.com/zephyrproject-rtos/zephyr/pull/6042

**Comment by nashif** [comment]
looks like this is resolved now
