### ISSUE TITLE
USB MSC sample has no default storage backend defined

### ISSUE THREAD

**Issue by masz-nordic** [zephyrproject-rtos/zephyr#14295]
**Describe the bug**
USB mass storage sample crashes during initialization. Device is not detected by the host.

**To Reproduce**
- `cd samples/subsys/usb/mass`
- `west build --board nrf52840_pca10056`
- `west flash`

**Expected behavior**
Proper initialization, a disk should be detected.

**Impact**
Showstopper.

**Screenshots or console output**
```
***** Booting Zephyr OS v1.14.0-rc1-1025-gc78c5e693679 *****                    
[00:00:00.004,272] <err> usb_msc: Storage init ERROR !!!! - Aborting USB init   
[00:00:00.004,272] <inf> main: The device is put in USB mass storage mode.   
```
**Environment (please complete the following information):**
 - OS: Ubuntu 16.04, 4.13.0
 - Toolchain: Zephyr SDK 0.9.5
 - Zephyr: c78c5e693679cc75f6e72e55c70f179ae9f6bea8

**Comment by aurel32** [comment]
This is expected, you need to either add the `overlay-ram-disk.conf` or the `overlay-flash-disk.conf` as explained in the README.

**Comment by masz-nordic** [comment]
Right. In case of samples, I think it would be beneficial to have a default `.conf` (or at least have a board-specific configuration for most used ones).

**Comment by finikorg** [comment]
I think that the build is also described in `samples/subsys/usb/mass/sample.yaml` But we could also add `#error ....` code somewhere in mass storage code to warn user about right usage
