### ISSUE TITLE
Bluetooth connection using central and peripheral samples in nrf52840

### ISSUE THREAD

**Issue by ejpark0618** [zephyrproject-rtos/zephyr#14300]
Hi, I'm doing my research on BLE using nrf52840 board and Zephyr

However, whenever I tried to make connection using Central and Peripheral sample, 
it is repeatedly connected and disconnected with error code 22 and 19

Can I get some help on this? Thank you for your attention

**Comment by Vudentz** [comment]
Are there any traces available for this issue?

**Comment by carlescufi** [comment]
@ejpark0618 those are normal termination codes, someone has disconnected on the local or remote side. This is not a bug, it's either side disconnecting normally.

**Comment by ejpark0618** [comment]
> Are there any traces available for this issue?
![KakaoTalk_20190312_083254090](https://user-images.githubusercontent.com/15953471/54342251-54dbe980-467f-11e9-9de4-9f9ff3e69270.png)
![KakaoTalk_20190312_210511527](https://user-images.githubusercontent.com/15953471/54342252-54dbe980-467f-11e9-8897-15a251e50e2a.png)
 Here it is

**Comment by ejpark0618** [comment]
> @ejpark0618 those are normal termination codes, someone has disconnected on the local or remote side. This is not a bug, it's either side disconnecting normally.

Yes, but we do nothing on central and peripheral codes..... we did not disconnected by hand
