### ISSUE TITLE
Automatic device dependency tracking

### ISSUE THREAD

**Issue by pizi-nordic** [zephyrproject-rtos/zephyr#14309]
We need abstraction of dependencies between devices in order to perform power management operations in correct order and on all devices affected by given operation. For example when suspending a SPI device, we might also suspend SPI Controller (driving SCLK, MISO and MOSI) and GPIO controller (driving /CS) if they are no longer use as well as cut off power from unused part of SoC/board.

All data we need is in the DTS. We have to extract this and convert to a form which will be easy to use by the device power management code.

**Comment by nashif** [comment]
should we close this?

**Comment by pabigot** [comment]
Seems like this is done, yes.

**Comment by ball-hayden** [comment]
@nashif / @pabigot - do you have a link to the PR that fixed this issue, please?
(I'm trying to trace whether this has landed for our fork yet)

**Comment by pabigot** [comment]
#32127 supplies the necessary information.  There's very little infrastructure to actually use this data yet, and the API is still evolving (#32547).  But the data from DTS is now available, so this is closed.

**Comment by ball-hayden** [comment]
Thank you. To clarify, then, the example you give ("when suspending a SPI device, we might also suspend SPI Controller") is _not_ yet implemented?

**Comment by pabigot** [comment]
> To clarify, then, the example you give ("when suspending a SPI device, we might also suspend SPI Controller") is _not_ yet implemented?

Correct, no drivers have been updated to do this.  I expect it will ultimately be done using the device power management API, which is currently being discussed elsewhere (I don't know exactly where).
