### ISSUE TITLE
Make device a pollable object

### ISSUE THREAD

**Issue by pizi-nordic** [zephyrproject-rtos/zephyr#14311]
The https://github.com/zephyrproject-rtos/zephyr/pull/13382 introduces device power states which could be asynchronously changed. We should make life of our developers easier and add ability to use k_poll and k_triggered_work directly on the device in order to wait/execute some action when device enter given power state.

**Comment by gmarull** [comment]
After discussing with @pizi-nordic, we can close this issue. As of today, the runtime API uses condvar to notify waiting threads, a mechanism that overcomes some k_poll limitations. k_event could be considered in the future as an alternative if needed.
