### ISSUE TITLE
[Coverity CID :143653]Memory - corruptions in /tests/subsys/fs/nffs_fs_api/common/nffs_test_utils.c

### ISSUE THREAD

**Issue by aasthagr** [zephyrproject-rtos/zephyr#14436]
Static code scan issues seen in File: /tests/subsys/fs/nffs_fs_api/common/nffs_test_utils.c
 Category: Memory - corruptions
 Function: nffs_test_util_create_file
 Component: Tests
 CID: 143653
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by AdithyaBaglody** [comment]
False positive. mentioned the same in coverity.
