### ISSUE TITLE
python requirements.txt: pyocd and pyyaml conflict  

### ISSUE THREAD

**Issue by attdona** [zephyrproject-rtos/zephyr#14460]
`scripts/requirements.txt` declare `pyocd==0.16.1` that require `pyyaml>=4.2b1,<5.0`.

 To avoid `pip install -r script/requirements.txt` failure I've changed:

    PyYAML>=3.12

into:

    PyYAML==4.2b4

Is it ok or did I miss something?

**Comment by mbolivar** [comment]
Adding @MaureenHelm as an FYI.

@attdona, I think this is a pyOCD bug, not a Zephyr bug, for reasons explained here:

https://github.com/mbedmicro/pyOCD/issues/582

I'm closing this as a result. Please reopen if you disagree.
