### ISSUE TITLE
MPU fault during application startup

### ISSUE THREAD

**Issue by nordic-krch** [zephyrproject-rtos/zephyr#14471]
**Describe the bug**
Application can hit mpu fault before starting main thread. This is caused by stack misuse. In function `z_arch_switch_to_main_thread` thread entry is provided as forth argument (`_main`). Then within the function stack pointer is changed:
https://github.com/zephyrproject-rtos/zephyr/blob/269935dca9e139d365631979fbecf6d080cba758/arch/arm/include/kernel_arch_func.h#L106

After stack is changed, call to thread entry occurs which is using `_main` as the argument. If variable is stored on stack, it will be fetched from stack but at that point this is already different stack and value is corrupted:
https://github.com/zephyrproject-rtos/zephyr/blob/269935dca9e139d365631979fbecf6d080cba758/arch/arm/include/kernel_arch_func.h#L115
So `_main` variable will be corrupted.

**To Reproduce**
Modify hello_world example by using following prj.conf:
```
CONFIG_MPU_STACK_GUARD=y
CONFIG_NO_OPTIMIZATIONS=y
CONFIG_LOG=y
```

1. mkdir build; cd build
2. cmake -GNinja -DBOARD=nrf52840_pca10056 ..
3. ninja flash
```
Fatal fault in essential thread! Spinning...
***** MPU FAULT *****
  Instruction Access Violation
***** Hardware exception *****
Current thread ID = 0x200005d8
Faulting instruction address = 0x20001b48
Fatal fault in essential thread! Spinning...
```

**Expected behavior**
Sample should start.

**Impact**
Suddenly system crashes during initialization.

**Comment by ioannisg** [comment]
Going to look into this.

**Comment by ioannisg** [comment]
Yes, this looks like a bug. It was, probably, inserted when we refactored this file to look like a C file, instead of assembly code.
