### ISSUE TITLE
doc: update robots.txt to exclude more old docs

### ISSUE THREAD

**Issue by dbkinder** [zephyrproject-rtos/zephyr#14492]
The current robots.txt excludes old docs (from 1.4.0 through 1.8.0) from search engines but is letting really old docs from 1.2.0 and 1.3.0 through. Add these two folder to the Disallow list too (or just delete some of these really old doc sets.

**Comment by rljordan** [comment]
@dbkinder If you do not have access to do this, please let me know.

**Comment by dbkinder** [comment]
I don't have access to do this.  That's why it was assigned to Anas, he does.

**Comment by nashif** [comment]
done
