### ISSUE TITLE
Kconfig shell prompt configuration

### ISSUE THREAD

**Issue by rodrigopex** [zephyrproject-rtos/zephyr#14547]
**Is your enhancement proposal related to a problem? Please describe.**
There is no straightforward (CONFIG) way to change the prompt value for a shell backend.

**Describe the solution you'd like**
I suggest creating a Kconfig option like SHELL_PROMPT where the user can change that easily through the *prj.conf*.

**Describe alternatives you've considered**
It would be good a way to remove the prompt at least. 

**Additional context**
If you would create an AT like command interface it would be easy if we can remove the prompt and other features like echo, wildcards, etc.

**Comment by aescolar** [comment]
@rodrigopex : Please do not leave the template text ("A clear and concise ..") into the issue itself. That is just meant to be replaced with your own content.

**Comment by jarz-nordic** [comment]
Hi
First part of a request is clear. I will take care.

@rodrigopex
May you please elaborate a bit more about „AT interface like” to remove echo, meta keys... i don’t get it. Thease features can be already disabled via kconfig. In addition echo can be disabled in runtime.

**Comment by rodrigopex** [comment]
> @rodrigopex : Please do not leave the template text ("A clear and concise ..") into the issue itself. That is just meant to be replaced with your own content.

Ok, I will do that now on.

**Comment by rodrigopex** [comment]
> Hi
> First part of a request is clear. I will take care.
> 
> @rodrigopex
> May you please elaborate a bit more about „AT interface like” to remove echo, meta keys... i don’t get it. Thease features can be already disabled via kconfig. In addition echo can be disabled in runtime.

We are developing a system that must respond to commands like an AT command interface. In this case, removing the prompt is very important to enable us to use Zephyr shell as the controller of the command interface with no additional work. 

In short, for doing the "command interface" we just removed the prompt manually, disable all the other features of the shell and the interface is done. Commands like "b s 0 2" (just an example) will be easy to implement with shell subcommands and args management.

The prompt will change the message flow in a bad way.
