### ISSUE TITLE
mcuboot doesn't link into code-partition

### ISSUE THREAD

**Issue by nvlsianpu** [zephyrproject-rtos/zephyr#14566]
mcuboot doesn't link into code-partition despite it is chosen.
```
	chosen {
		zephyr,code-partition = &boot_partition;
	};
```

**To Reproduce**
build mcuboot against nrf52840_pca10059 zephyr target or any else target which has shifted code-partition.

**Expected behavior**
linking into code partition.

**Impact**
mcuboot will not work on XIP target which has mcuboot partition started at offset different than Zero.

**Environment**
 - zephyr SHA 2153c014ea2eaf27d9f3442ae00af44386abe879 (master branch)
 - mcuboot SHA  https://github.com/JuulLabs-OSS/mcuboot/commit/b899f79a2844d4e3e0dad9cb2c7a2c4e74703b2f (master branch)

**mcuboot issue**
https://github.com/JuulLabs-OSS/mcuboot/issues/444

**Comment by nvlsianpu** [comment]
I would introduce Kconfig property:
```
config USE_CODE_PARTITION
	bool "Link application into code partition"
```
And use it for conditional assignment to `FLASH_LOAD_OFFSET` and `FLASH_LOAD_SIZE` the value of
`$(dt_hex_val,DT_CODE_PARTITION_OFFSET)` (as it is now done with `BOOTLOADER_MCUBOOT`).
Then `BOOTLOADER_MCUBOOT` should just select `USE_CODE_PARTITION`.

**Comment by nvlsianpu** [comment]
cc @SebastianBoe

**Comment by lemrey** [comment]
Can you confirm that this affects other boards?

**Comment by nvlsianpu** [comment]
I confirm that this is issue for other boards as well.

**Comment by mike-scott** [comment]
I mentioned this to @carlescufi a while back on Slack.  I was having a problems getting binaries built from Zephyr to have the correct flash offset settings.

I eventually got it work by manually specifying how I wanted mcuboot built:
```
west build -d build/mcuboot -b nrf52840_pca10059 -s mcuboot/boot/zephyr -- -DCONFIG_FLASH_LOAD_OFFSET=0x1000 -DCONFIG_FLASH_LOAD_SIZE=0xf000
```

Using this method, I was able to take the .hex file directly and place it on the board using the nRF-Connect GUI tool for Linux.

**Comment by nvlsianpu** [comment]
@mike-scott Thanks for post this workaround.

**Comment by SebastianBoe** [comment]
@nvlsianpu : Could you do a PR with your proposed solution?

I'm not familiar enough with these symbols to review unfortunately.

**Comment by lemrey** [comment]
https://github.com/JuulLabs-OSS/mcuboot/pull/445

**Comment by nvlsianpu** [comment]
@SebastianBoe 
https://github.com/zephyrproject-rtos/zephyr/pull/14620 + https://github.com/JuulLabs-OSS/mcuboot/pull/447
