### ISSUE TITLE
IPv6 support in cc3220sf_launchxl

### ISSUE THREAD

**Issue by vanti** [zephyrproject-rtos/zephyr#14587]
**Is your enhancement proposal related to a problem? Please describe.**
IPv6 support is currently disabled in the SimpleLink wifi driver. It needs to be enabled to take advantage of the hardware.

**Describe the solution you'd like**
Add IPv6 support to the SimpleLink wifi driver.

**Describe alternatives you've considered**
Not supporting IPv6 is one option, but it imposes an unnecessary limitation when the hardware supports it. Also many of the samples/tests would need to be changed to allow a non-IPv6 mode (an example of this in PR #14548)

**Comment by vanti** [comment]
Implemented in #26913

**Comment by jukkar** [comment]
Closing as #26913 is already merged.
