### ISSUE TITLE
mimxrt1050_evk tests/kernel/fp_sharing kernel.fp_sharing fails

### ISSUE THREAD

**Issue by hakehuang** [zephyrproject-rtos/zephyr#14606]
**Describe the bug**
float point sharing test fails

**To Reproduce**
1. mkdir build; cd build
2. cmake -DBOARD=mimxrt1050_evk ..
3. make

**Expected behavior**
test PASS

**Impact**
fp usage

**Screenshots or console output**
```
***** Booting Zephyr OS 1.14.0-rc2 *****

Floating point sharing tests started

===================================================================

FAIL - calculate_pi_low@89. Computed pi %.6f, reference pi %.6f

FAIL - load_store_low

===================================================================

===================================================================

PROJECT EXECUTION FAILED

Pi calculation OK after 50 (high) + 0 (low) tests (computed %.6f)

Load and store OK after 100 (high) + 28782 (low) tests

Pi calculation OK after 150 (high) + 0 (low) tests (computed %.6f)

Load and store OK after 200 (high) + 28782 (low) tests
```

**Environment (please complete the following information):**
 - OS: (Linux)
 - Toolchain (Zephyr SDK,)
 - Commit SHA or Version used: v1.14.0_rc2

**Comment by hakehuang** [comment]
@MaureenHelm , rt1020/rt1060 are ok with this case

**Comment by agansari** [comment]
@hakehuang i am able to reproduce this

**Comment by MaureenHelm** [comment]
git bisect points to:

```
commit 525065dd8b9e57c53012572c5d7122643ede3970 (HEAD, refs/bisect/bad)
Author: Andrew Boie <andrew.p.boie@intel.com>
Date:   Thu Jan 31 15:31:18 2019 -0800

    tests: convert to use app shared memory
    
    CONFIG_APPLICATION_MEMORY was a stopgap feature that is
    being removed from the kernel. Convert tests and samples
    to use the application shared memory feature instead,
    in most cases using the domain set up by ztest.
    
    Signed-off-by: Andrew Boie <andrew.p.boie@intel.com>
```

**Comment by hakehuang** [comment]
frdmk64f also has problem with this case. but for frdmk64f there is no any console output

**Comment by agansari** [comment]
Went back to 525065dd8b9e57c53012572c5d7122643ede3970 commit but this issue still happens.
Went back to previous tag v1.14.0-rc1, still happens.
Went back to tag v.1.13.0 but sdk or toolchain doesn't match anymore.
This issue is older than expected i think and finding the source will not be easy.

Also K64F is slooooowwwww........ it prints, but ot takes a long time, i.MX family is alot faster.

**Comment by ioannisg** [comment]
Very similar failure to what we see in #9656 , @agansari

**Comment by agansari** [comment]
@ioannisg i'm still debugging this issue.
I've observed that that reading FPSCR register (FPU status/ctrl) in _calculate_pi_high_ task had all kinds of exceptions. Adding ___set_FPSCR(0);_ at the begining of _calculate_pi_high_ passes the test (reset register to default values).
I need to find out how configures or generates exceptions in FPU before the sample tasks.
