### ISSUE TITLE
samples/net/sockets/echo_async_select doesn’t work for qemu_x86 target

### ISSUE THREAD

**Issue by ozhuraki** [zephyrproject-rtos/zephyr#14612]
Currently, the error check of setsockopt of IPV6_V6ONLY (which is unsupported on MCU targets) is too restrictive.

Pull request with the fix:

https://github.com/zephyrproject-rtos/zephyr/pull/14610

**Comment by tedd-an** [comment]
I believe this is fixed by #14896 and can be closed.

**Comment by ozhuraki** [comment]
Fixed by #14896.
