### ISSUE TITLE
BLE controller: Add support for Controller(SW deferred)-based Privacy

### ISSUE THREAD

**Issue by aescolar** [zephyrproject-rtos/zephyr#14621]
For devices without address resolution acceleration in the LL hardware (like a nRF51), the current controller code does not support privacy (random addresses).
A method for resolving addresses in SW should be added for this kind of platforms.
This only needs to be added for the new split LL architecture (as the old will be deprecated soon).

The method shall defer the resolution of unknown addresses to a lower priority task, maintaining a table of already known and resolved addresses which the LLL will utilize inside the ADV events.

**Comment by MaureenHelm** [comment]
Will this be ready for the 2.0.0 release or should we push out to a future release?

**Comment by aescolar** [comment]
@MaureenHelm Please wait a few days. We may still be able to manage it: The 2 developers working on it are right now out on holidays, but the work is quite far, and it is a new feature with low risk for existing ones.
I will move the milestone myself if a few days (after they are back from holidays) if it still looks like we won't make it.
