### ISSUE TITLE
undefined reference to `mbedtls_debug_set_threshold' when MBEDTLS_DEBUG is enabled

### ISSUE THREAD

**Issue by laperie** [zephyrproject-rtos/zephyr#14633]
**Describe the bug**
Cannot enable debugging of MBEDTLS.  Something is rotten in the state of Denmark. (C) Shakespeare

**To Reproduce**
1. in #14632, enable MBEDTLS_DEBUG
2. build 
3. See error

**Expected behavior**

**Screenshots or console output**
```
/opt/zephyr-sdk/i586-zephyr-elf/bin/../lib/gcc/i586-zephyr-elf/8.3.0/../../../../i586-zephyr-elf/bin/ld: libzephyr.a(sockets_tls.c.obj): in function `tls_init':
/home/laperie/workspace/zephyr/zephyr/subsys/net/lib/sockets/sockets_tls.c:289: undefined reference to `mbedtls_debug_set_threshold'
collect2: error: ld returned 1 exit status
zephyr/CMakeFiles/zephyr_prebuilt.dir/build.make:99: recipe for target 'zephyr/zephyr_prebuilt.elf' failed
make[2]: *** [zephyr/zephyr_prebuilt.elf] Error 1
```

**Environment (please complete the following information):**
Linux
0.10.0 SDK

**Comment by rlubos** [comment]
Hi @laperie, I've seen this issue before. It seems that `make` does not rebuild mbedTLS in case Zephyr configuration is changed (in this case mbedTLS debug enabled). When I used make, I forced it to rebuild entire project with `make clean && make` after changing mbedTLS configuration.

Apparently this is not an issue when using `ninja` - it seems to understand better what needs to be rebuilt.

**Comment by laperie** [comment]
> Hi @laperie, I've seen this issue before. It seems that `make` does not rebuild mbedTLS in case Zephyr configuration is changed (in this case mbedTLS debug enabled). When I used make, I forced it to rebuild entire project with `make clean && make` after changing mbedTLS configuration.

Cannot confirm that, sorry -- same symptoms no matter what you use to build the sample.  Problem is likely elsewhere...

**Comment by jukkar** [comment]
I have not used public server like in the example as I do not have direct internet access from my test host. So I used simple python https server with self certified certificate, could that self cert be the culprit here?

**Comment by rlubos** [comment]
@jukkar I suppose the above comment reffered to #14632?

**Comment by jukkar** [comment]
Ah, sorry, I seemed to have commented wrong issue :)

**Comment by jukkar** [comment]
I just tried this and did not see any issues -> closing.

**Comment by hraftery** [comment]
Adding the mysterious `CONFIG_MBEDTLS_DEBUG_C` fixes it for me.
