### ISSUE TITLE
ARC: tests/posix/common/ and tests/kernel/critical time out on nsim_sem with userspace enabled

### ISSUE THREAD

**Issue by andrewboie** [zephyrproject-rtos/zephyr#14642]
Only seen failure on nsim_sem. Fails both test variants: portability.posix and portability.posix.newlib

The failure is a hang after printing some output:

```
***** Booting Zephyr OS v1.14.0-rc1-1250-g4e097b4d541f *****
Running test suite posix_apis
===================================================================
starting test - test_posix_pthread_execution
Thread 0 starting with scheduling policy 0 & priority 15
Thread 1 starting with scheduling policy 0 & priority 15
Thread 2 starting with scheduling policy 0 & priority 15

```

**Comment by andrewboie** [comment]
It looks like the test actually succeeds, but takes a long time. On my unloaded workstation it took about 21 seconds for the test to complete.

**Comment by andrewboie** [comment]
This seems to be worse since the last time I looked at it, it now appears to get stuck.

**Comment by andrewboie** [comment]
Correction. On nsim_em, the test takes about 22 seconds. on nsim_sem, it hangs forever. The bug is only on nsim_sem.

**Comment by andrewboie** [comment]
I think there is some weird race in the test itself, I'm digging deeper.

**Comment by andrewboie** [comment]
the slowness of the test is due to the sched_yield() call in thread_top_exec(), which simply calls k_yield(), presumably to allow other threads to run...if I comment it out the test finishes very quickly.

Not sure what is going on yet.

**Comment by andrewboie** [comment]
More data:

If I disable CONFIG_TEST_USERSPACE (which runs the test without user mode), it completes very quickly.

**Comment by andrewboie** [comment]
tests/kernel/critical has a similar issue:

**Time to run on nsim_sem: 116s**
Time to run on nsim_em: 13s

Now if I comment out the body of configure_mpu_thread(), I get:

Time to run on nsim_sem: 11s
Time to run on nsim_em: 7s

**Comment by andrewboie** [comment]
Both tests involve a lot of context switching, the performance of the MPU reprogramming (either in the code or the emulator) is severely impacting the test completion time. Closing the other bug #15129 as a duplicate.

**Comment by vonhust** [comment]
@andrewboie , if i recall correctly, it runs ok in hardware. I will double check it

**Comment by andrewboie** [comment]
Tomorrow I'm going to try to apply the optimization in #15135, it seems ARC code unconditionally reprograms all of the volatile MPU registers on every context switch

**Comment by vonhust** [comment]
@andrewboie  no problem in hardware, both em and sem are ok.  The difference betwenn call configure_mpu_thread and not call configure_mpu_thread is time of context switch

**Comment by ruuddw** [comment]
I did a quick experiment, looking at the count values/number of iterations completed in the (fixed) test time. There is (as can be expected) significant context switch 'overhead' due to the MPU reprogramming on both nSIM and hardware (~25%-100% less iterations with userspace enabled, for both MPU variants) but that doesn't explain the 10x slower performance on nsim_sem. Based on this, my expectation is nSIM simulation performance with the MPU "v3" is the cause of the timeouts, not the context switch overhead (though there is room for improvement for that as well). I'll check/follow up with the nSIM team.

**Comment by andrewboie** [comment]
> that doesn't explain the 10x slower performance on nsim_sem

@ruuddw nsim_sem does tons more writes to the MPU registers than nsim_em does, to implement gap-filling. See details in #15223
