### ISSUE TITLE
Gitlint is more strict than checkpatch.pl

### ISSUE THREAD

**Issue by dgloeck** [zephyrproject-rtos/zephyr#14652]
**Describe the bug**
checkpatch.pl warns if commit messages have lines that exceed 75 characters but the Gitlint check that is automatically run for pull requests rejects commit messages that have lines longer than 72 characters.

**Expected behavior**
The checks should be unified.

**Impact**
annoyance

**Comment by aescolar** [comment]
@dgloeck : Would you like to submit a patch?
