### ISSUE TITLE
net: icmp4: Zephyr strips record route and time stamp options

### ISSUE THREAD

**Issue by rmstoi** [zephyrproject-rtos/zephyr#14668]
If echo server receives ICMPv4 echo request with IPv4 options Record Route and Time Stamp it does not include them in echo response. According to [RFC 1122 3.2.2.6](https://tools.ietf.org/html/rfc1122#page-43) these options must be updated and included in the echo response.

[ipv4-timestamp-recordroute.pcap.gz](https://github.com/zephyrproject-rtos/zephyr/files/2982874/ipv4-timestamp-recordroute.pcap.gz)

**Comment by tbursztyka** [comment]
didn't you say that linux was dropping the options, when I fixed the ipv4 options parsing?

**Comment by tbursztyka** [comment]
oh btw, we don't support ANY ipv4 options. So it's not a bug, we just don't support any ipv4 options, period.

If we want to support it, that's an enhancement

**Comment by rmstoi** [comment]
> didn't you say that linux was dropping the options, when I fixed the ipv4 options parsing?

Please add reference, to where I said that

**Comment by tbursztyka** [comment]
@rmstoi It was on IRC. But that was about #11618 so probably not about these same options. nevermind

**Comment by jukkar** [comment]
This is more like an enhancement than feature.

**Comment by rmstoi** [comment]
pcap of this issue:

Linux DUT test PASS
[linux-ipv4-timestamp-recordroute.pcap.gz](https://github.com/zephyrproject-rtos/zephyr/files/3671426/linux-ipv4-timestamp-recordroute.pcap.gz)

Zephyr DUT PR #19470 test FAIL
[zephyr-pr-19470.pcap.gz](https://github.com/zephyrproject-rtos/zephyr/files/3671429/zephyr-pr-19470.pcap.gz)

FAIL reason is:
"FAIL: First Record Route entry is not DUT's IPv4 address. Time Stamp Route entry is not DUT's IPv4 address. "
