### ISSUE TITLE
Bluetooth: split controller: add support for Mesh Extensions

### ISSUE THREAD

**Issue by aescolar** [zephyrproject-rtos/zephyr#14678]
Add support to the split link layer for the HCI mesh extensions. A subset of these were already supported by the old controller, however to make the host side (mesh stack) move to use the the full spec should be implemented.

**Comment by jhedberg** [comment]
I'm not sure it's worth trying to do this for 2.0. There are no users (I know of at least) of these extensions with the old controller. I'd prefer if the full mesh vendor spec was implemented and then update the mesh stack to use them when available. However, if no-one commits to do that for 2.0 then just set some future milestone.

**Comment by aescolar** [comment]
Thanks @jhedberg , milestone changed

**Comment by taharvey** [comment]
Can you provide some color to the current status vs what needs to be built? What mesh features currently work in spilt controller mode? Does this also apply to Linux and BlueZ bridging? What needs completion?

**Comment by aescolar** [comment]
@jhedberg @cvinayak ^^

**Comment by jhedberg** [comment]
@taharvey all mesh features work with the current controller. This issue is about vendor HCI extensions that would optimize low-level packet filtering and improve transmission timing accuracy.

**Comment by aescolar** [comment]
After talking with @cvinayak : There is no plan to implement vendor specific mesh extensions in the controller. This issue is "Closed as not planned"
