### ISSUE TITLE
need end-to-end memory protection samples

### ISSUE THREAD

**Issue by andrewboie** [zephyrproject-rtos/zephyr#14683]
We need an end-to-end memory protection sample which demonstrates the following. We have ample tests for these but not an example showing everything working together.

- [x] Multiple logical applications, each having their own threads, partitioned with memory domains
- [x] Instantiation and assignment to a partition of a sys_mem_pool
- [x] Configuration and use of thread resource pools
- [x] Management of permission of drivers and kernel objects
- [ ] Allocation of dynamic kernel objects
- [x] Definition of an application-specific system call
- [x] Important: show various methods of data exchange where ISRs/callbacks use IPC mechanisms to give data to user mode.

**Comment by ioannisg** [comment]
@andrewboie I would like to know if you plan to work on this for 2.0, or whether we can move this to the following release.

**Comment by andrewboie** [comment]
I am doing this for 2.0.
