### ISSUE TITLE
elf_helper: Call to undefined debug_die() in AggregateTypeMember (wrong class)

### ISSUE THREAD

**Issue by ulfalizer** [zephyrproject-rtos/zephyr#14762]
The `self.debug_die("not yet supported location operation")` in `AggregateTypeMember.__init__()` won't work, because `debug_die()` is defined in the `ElfHelper` class.

**Comment by aescolar** [comment]
@ulfalizer  Note that the trivial tag was meant to be used to indicate the amount of reviewing a PR needed.

**Comment by ulfalizer** [comment]
Ohh... thought it meant "this isn't all that important". :P
