### ISSUE TITLE
K_THREAD_STACK_BUFFER() is broken

### ISSUE THREAD

**Issue by andrewboie** [zephyrproject-rtos/zephyr#14766]
This macro has a design flaw: it assumes that the offset to the stack buffer, within the stack object, is constant.

However, on ARC this offset changes depending on whether the stack is being used in supervisor or user mode. There are no reverse references to the thread in the stack object (nor is it possible to add one); this API is broken by design.

This API needs to be removed; if someone needs to know the bounds of an in-use stack, this information is available in the thread struct anyway.

**Comment by nashif** [comment]
what are the plans for this issue? Is it going to be fixed for 1.14 release?

**Comment by andrewboie** [comment]
Implementation is in progress.

**Comment by andrewboie** [comment]
Setting to low, in current code this may not reveal the true stack buffer, but does not point to memory outside of the stack object.
