### ISSUE TITLE
samples/net/promiscuous_mode the include file is not there

### ISSUE THREAD

**Issue by hakehuang** [zephyrproject-rtos/zephyr#14770]
**Describe the bug**
there is no net/tcp.h file to include

**To Reproduce**
1. mkdir build; cd build
2. cmake -DBOARD=frdm_k64f ..
3. make

**Expected behavior**
sample need update

**Impact**
sample

**Screenshots or console output**
```
/build/src/workspace/frdmk64f_master/samples/net/promiscuous_mode/src/main.c:17:21: fatal error: net/tcp.h: No such file or directory

 #include <net/tcp.h>

                     ^

compilation terminated.

CMakeFiles/app.dir/build.make:62: recipe for target 'CMakeFiles/app.dir/src/main.c.obj' failed

```

**Environment (please complete the following information):**
 - OS: ( Linux)
 - Toolchain ( Zephyr SDK)
 - Commit SHA or Version used: v1.14.0_rc2

**Comment by rveerama1** [comment]
https://github.com/zephyrproject-rtos/zephyr/commit/ebce5601c05d76fa75cbd478fa68e56502fa763a already merged.
