### ISSUE TITLE
DT_<Driver Name>_LABEL undeclared

### ISSUE THREAD

**Issue by bokenator** [zephyrproject-rtos/zephyr#14810]
Hi,

I'm trying to implement a driver for the ADXL345 accelerometer based the ADXL372 driver which is already available on Zephyr. However, when I'm trying to use the driver in the application, the compilation fails with the following error:

```
../src/main.c: In function 'main':
../src/main.c:50:42: error: 'DT_ADI_ADXL345_0_LABEL' undeclared (first use in this function); did you mean 'DT_FLASH_AREA_0_LABEL'?
  struct device *dev = device_get_binding(DT_ADI_ADXL345_0_LABEL);
                                          ^~~~~~~~~~~~~~~~~~~~~~
                                          DT_FLASH_AREA_0_LABEL
../src/main.c:50:42: note: each undeclared identifier is reported only once for each function it appears in
../src/main.c:48:7: warning: unused variable 'meter' [-Wunused-variable]
```

I have already made edits to `CMakeLists.txt` and `Kconfig` in the `drivers/sensor` directory to add the new custom driver.

Any help would be greatly appreciated!
Thanks!

**Comment by aescolar** [comment]
@galak : Could you help him?

**Comment by bokenator** [comment]
Figured it out!

In addition to adding the driver to `CMakeLists.txt` and `Kconfig` in the `drivers/sensor` directory, we also need to create a `.yaml` file in `dts/bindings/sensor` directory.

**Comment by thirtythreeforty** [comment]
@bokenator perhaps a bit off topic for this issue, but is your work-in-progress ADXL345 driver public anywhere?
