### ISSUE TITLE
[Coverity CID :196643]Null pointer dereferences in /subsys/net/ip/net_context.c

### ISSUE THREAD

**Issue by aasthagr** [zephyrproject-rtos/zephyr#14813]
Static code scan issues seen in File: /subsys/net/ip/net_context.c
 Category: Null pointer dereferences
 Function: context_alloc_pkt
 Component: Networking
 CID: 196643
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by rveerama1** [comment]
master already has fix for this.
