### ISSUE TITLE
[Coverity CID :196637]Uninitialized variables in /samples/net/sockets/can/src/main.c

### ISSUE THREAD

**Issue by aasthagr** [zephyrproject-rtos/zephyr#14819]
Static code scan issues seen in File: /samples/net/sockets/can/src/main.c
 Category: Uninitialized variables
 Function: tx
 Component: Samples
 CID: 196637
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by tedd-an** [comment]
Code merged and close the bug
