### ISSUE TITLE
[Coverity CID :196641]Null pointer dereferences in /samples/net/nats/src/nats.c

### ISSUE THREAD

**Issue by aasthagr** [zephyrproject-rtos/zephyr#14815]
Static code scan issues seen in File: /samples/net/nats/src/nats.c
 Category: Null pointer dereferences
 Function: receive_cb
 Component: Samples
 CID: 196641
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by galak** [comment]
Fixed by #14851
