### ISSUE TITLE
[Coverity CID :196638]Null pointer dereferences in /subsys/bluetooth/host/hci_core.c

### ISSUE THREAD

**Issue by aasthagr** [zephyrproject-rtos/zephyr#14818]
Static code scan issues seen in File: /subsys/bluetooth/host/hci_core.c
 Category: Null pointer dereferences
 Function: le_conn_param_req
 Component: Bluetooth
 CID: 196638
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by jhedberg** [comment]
This was already fixed by #14757
