### ISSUE TITLE
[Coverity CID :196635]Error handling issues in /tests/net/mld/src/main.c

### ISSUE THREAD

**Issue by aasthagr** [zephyrproject-rtos/zephyr#14821]
Static code scan issues seen in File: /tests/net/mld/src/main.c
 Category: Error handling issues
 Function: send_query
 Component: Tests
 CID: 196635
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by tedd-an** [comment]
PR merged and close the bug
