### ISSUE TITLE
Bluetooth shell scan command parameter mandatory/optional evaluation is broken

### ISSUE THREAD

**Issue by jhedberg** [zephyrproject-rtos/zephyr#14837]
```
uart:~$ bt scan on
scan: wrong parameter count
scan - <value: on, passive, off> <dup filter: dups, nodups>
uart:~$ bt scan on nodups
Bluetooth active scan enabled
...
uart:~$ bt scan off
scan: wrong parameter count
scan - <value: on, passive, off> <dup filter: dups, nodups>
uart:~$ bt scan off dups
Scan successfully stopped
```

**Comment by jarz-nordic** [comment]
@jhedberg : I have faced (and possibly caused) this problem.
This command shall accept:
`bt scan on` and `bt scan on dups/nodups` ?

**Comment by jhedberg** [comment]
@jarz-nordic yes. The dups/nodups should be an optional parameter, whereas for "off" there should be no additional parameters. I suppose "on" and "off" need to be made into sub-commands so they can have different parameter requirements?

**Comment by jarz-nordic** [comment]
I will fix that.
Haveing `on` and `off` subcommands would be great but this idea has been rejected some time ago ;-)
