### ISSUE TITLE
samples/boards/altera_max10/pio: Error configuring GPIO PORT

### ISSUE THREAD

**Issue by cinlyooi-intel** [zephyrproject-rtos/zephyr#14922]
**Describe the bug**
When running the sample, it reports "Error configuring GPIO PORT"

**To Reproduce**
1. mkdir build; cd build
2. cmake  -DBOARD=altera_max10 -DARCH=nios2
3. make
4. See run

**Screenshots or console output**
```
***** Booting Zephyr OS v1.14.0-rc1-1484-g006b97de13a4 (delayed boot 3000ms) *****
Error configuring GPIO PORT
```

**Environment (please complete the following information):**
 - OS: fedora29
 - Toolchain: zephyr
 - Commit SHA or Version used: 006b97de13a49eec05cbca20fcb0aad63f25eb23

**Comment by nashif** [comment]
sample does not exist anymore, closing
