### ISSUE TITLE
tinycbor is failing in nightly CI

### ISSUE THREAD

**Issue by galak** [zephyrproject-rtos/zephyr#14934]
In nightly ci having some issue with tinycbor:

https://app.shippable.com/github/zephyrproject-rtos/ci-test/runs/2844/8/tests

**Comment by galak** [comment]
Attempted fix:

https://github.com/zephyrproject-rtos/ci-test/pull/14

**Comment by nashif** [comment]
This is not fixed zephyrproject-rtos/ci-test#15
