### ISSUE TITLE
[Coverity CID :197463]Memory - corruptions in /samples/bluetooth/central_hr/src/main.c

### ISSUE THREAD

**Issue by aasthagr** [zephyrproject-rtos/zephyr#14952]
Static code scan issues seen in File: /samples/bluetooth/central_hr/src/main.c
 Category: Memory - corruptions
 Function: discover_func
 Component: Samples
 CID: 197463
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by jhedberg** [comment]
Marked as false positive in Coverity
