### ISSUE TITLE
samples: Specify the board target required for the sample

### ISSUE THREAD

**Issue by cinlyooi-intel** [zephyrproject-rtos/zephyr#14973]
Please specify the board target used to run the sample in README.rst

- [ ] drivers/led_wd2812
- [ ] drivers/crypto
- [ ] drivers/CAN
- [ ] drivers/led_lp8806
- [ ] drivers/led_apa102
- [ ] drivers/rtc
- [ ] drivers/gpio
- [ ] basic/disco
- [ ] nfc/nfc_hello
- [ ] sensor/sx9500
- [ ] sensor/mcp9808
- [ ] sensor/bme280
- [ ] sensor/bmg160
- [ ] sensor/grove_temperature
- [ ] sensor/max44009
- [ ] sensor/tmp112
- [ ] sensor/tc02
- [ ] xtensa_asm2

**Comment by nashif** [comment]
You can get the data from the sample.yaml file and based on filters. Those samples should run majority of boards.
