### ISSUE TITLE
samples: Create README.rst

### ISSUE THREAD

**Issue by cinlyooi-intel** [zephyrproject-rtos/zephyr#14972]
Please create README.rst for the following samples in samples directory.

 

- [ ]  application_development/external_lib
- [ ]  application_development/out_of_tree_board
- [ ]  application_development/code_relocation
- [ ]  crypto/mbedtls_benchmark
- [ ]  boards/intel_s1000_crb/audio
- [ ]  boards/intel_s1000_crb/dmic
- [ ]  boards/intel_s1000_crb/i2s
- [ ]  boards/up_squared/gpio_counter
- [ ]  drivers/led_ws2812
- [ ]  drivers/crypto
- [ ]  drivers/spi_fujitsu_fram
- [ ]  drivers/drivers/watchdog
- [ ]  drivers/rtc
- [ ]  drivers/i2c_fujitsu_fram
- [ ]  drivers/soc_flash_nrf
- [ ]  drivers/lcd_hd44780
- [ ]  drivers/spi_flash
- [ ]  driversdrivers/gpio
- [ ]  subsys/power/device_pm
- [ ]  subsys/shell/shell_module
- [ ]  cpp_synchronization
- [ ]  nfc/nfc_hello
- [ ]  sensor/sx9500
- [ ]  sensor/grove_light
- [ ]  sensor/mcp9808
- [ ]  sensor/thermometer
- [ ]  sensor/bm3280
- [ ]  sensor/bmg160
- [ ]  sensor/grove_temperature
- [ ]  sensor/bmi160
- [ ]  sensor/tmp112
- [ ]  sensor/ccs811
- [ ]  sensor/th02
- [ ]  subsys/ipc/ipm_mailbox/ap
- [ ]  subsys/ipc/ipm_mailbox/sensor
- [ ]  subsys/ipc/ipm_mcux/remote
- [ ]  testing/integration
- [ ]  xtensa_asm2

**Comment by nashif** [comment]
most of this already addressed.
