### ISSUE TITLE
Enable flash_shell on all platforms with a flash_driver

### ISSUE THREAD

**Issue by galak** [zephyrproject-rtos/zephyr#14994]
There's an old PR for doing this here:

PR #13702

We probably need a mix of board support and Kconfig to determine if the sample is valid.

**Comment by de-nordic** [comment]
@galak The #13702 has been merged, so the issue is solved?

**Comment by de-nordic** [comment]
Seems to be solved at lest since https://github.com/zephyrproject-rtos/zephyr/commit/a8d3c8e142e2a4a8ec9fb52bf0aa42ee2c7fd7cc
prior to v2.5.0-rc1, closing.
