### ISSUE TITLE
doc: replace Mac OS with macOS

### ISSUE THREAD

**Issue by carlescufi** [zephyrproject-rtos/zephyr#1499]
Apple's desktop operating system is called "macOS" and not "Mac OS". Fix the references to it in the documentation.

**Comment by dbkinder** [comment]
For the record, it was called "Mac OS X" and then changed to "macOS" :)

**Comment by carlescufi** [comment]
indeed, but I think we can now avoid using "Mac OS X" at all since it's been a while since they transitioned to the new name
