### ISSUE TITLE
Not able to set "0xFFFF No specific value" for GAP PPCP structured data

### ISSUE THREAD

**Issue by akshhr** [zephyrproject-rtos/zephyr#15017]
Currently, it is not possible to set the following parameters to "0xFFFF No specific value" 
CONFIG_BT_PERIPHERAL_PREF_MIN_INT
CONFIG_BT_PERIPHERAL_PREF_MAX_INT
CONFIG_BT_PERIPHERAL_PREF_TIMEOUT
This is required as per the specification document, core v5.0, vol 3, part C, section 12.3 Peripheral preferred connection parameters characteristic.

**Comment by jhedberg** [comment]
So the range needs to be extended to 0xffff in Kconfig and then we probably also want a `BUILD_ASSERT(within_range(val) || val == 0xffff)`

**Comment by Vudentz** [comment]
But if one don't want to specify the value why to select it in the first place? I guess it would have been better not to include the attributes if you won't specify any value.

**Comment by jhedberg** [comment]
> But if one don't want to specify the value why to select it in the first place? I guess it would have been better not to include the attributes if you won't specify any value.

@Vudentz maybe because you want a specific value on one or two of the parameters, but don't care about the value of the rest?

**Comment by akshhr** [comment]
@Vudentz I agree with @jhedberg and also it is a requirement from the specification.
