### ISSUE TITLE
tests/kernel/threads/no-multithreading: Not booting

### ISSUE THREAD

**Issue by cinlyooi-intel** [zephyrproject-rtos/zephyr#15018]
**Describe the bug**
Cannot see any sign that the board is booting up

**To Reproduce**
1. mkdir build; cd build
2. cmake -DBOARD=altera_max10
3. make
4. make run

 - OS: fedora29
 - Toolchain zephyr
 - Commit SHA or Version used:  f5a4a698ec17e6a78299966a1a3fe73c3404b78d

**Comment by nashif** [comment]
boot delay was removed when running in a single thread. So it is a test setup issue, not a zephyr bug. Need to exclude this from testing or test manually.
