### ISSUE TITLE
Unable to establish security after reconnect to dongle

### ISSUE THREAD

**Issue by pdunaj** [zephyrproject-rtos/zephyr#15012]
**Describe the bug**
We have two devices: mouse (peripheral) and dongle (central). Dongle connects to mouse when the other one is available. Until around two weeks ago everything was working fine but lately security cannot be established after one of the device reconnects.

I found out that the problem is in `ll_enc_req_send` that rejects starting an encryption
```
#if defined(CONFIG_BT_CTLR_PHY)
        if ((conn->llcp_req != conn->llcp_ack) ||
            (conn->llcp_phy.req != conn->llcp_phy.ack)) {
#else /* CONFIG_BT_CTLR_PHY */
        if (conn->llcp_req != conn->llcp_ack) {
#endif /* CONFIG_BT_CTLR_PHY */
                LOG_ERR("PDUNAJ security: %s %d", __func__, __LINE__);
                return BT_HCI_ERR_CMD_DISALLOWED;
```

There was recently a change in this area that was adding check for a collision ( https://github.com/zephyrproject-rtos/zephyr/commit/f4c8e3ff3197d36773d68b4b4802daabc401f918 )

**To Reproduce**
Bond peripheral and central. Request security level medium from peripheral. Note security established. Disconnect or reset one of the devices. Reconnect. Observe no error on security request. Observe that no security is established.

**Expected behavior**
When security is requested we should get an error or security should be established.

**Impact**
Showstopper

**Screenshots or console output**
N/A

**Environment (please complete the following information):**
ncs zephyr rev: `de69d2df908fc7bccd8c03b106e7645e90b1503b` (upstream: `373a42b`)

**Additional context**
N/A

**Comment by carlescufi** [comment]
Setting high priority since this is a critical regression

**Comment by pdunaj** [comment]
Do anybody knows if this will be fixed? If fix will not happen soon, can the change causing a problem be reverted?

**Comment by carlescufi** [comment]
@pdunaj yes, @joerchan is working on this and it's his first priority.
