### ISSUE TITLE
net: 9cd547f53b "Fix ref counting for the net_pkt" allegedly broke reference counting

### ISSUE THREAD

**Issue by pfalcon** [zephyrproject-rtos/zephyr#15031]
Culprit, based on dissecting: 9cd547f53b7474945e94111e5f8ce9b05fa9579c

Steps to reproduce: samples/net/sockets/dumb_http_server BOARD=qemu_x86 OVERLAY=overlay-e1000.conf (which got added only in 946836577bb1adfe62e25771b8d565d2074d162f), then as usual run `ab -n1000 http://192.0.2.1:8080/`.

Seen behavior (100% and exactly reproducible):

~~~
Benchmarking 192.0.2.1 (be patient)
apr_pollset_poll: The timeout specified has expired (70007)
Total of 14 requests completed
~~~

Expected behavior: 1000 requests should go thru.

**Comment by pfalcon** [comment]
This would be "Priority: High". But as I'm not a release manager, I don't set it.

**Comment by pfalcon** [comment]
Also reproducible with default set up of dumb_http_server (i.e. qemu_x86 + SLIP).

**Comment by pfalcon** [comment]
Also reproducible with BOARD=mps2_an385 CONF_FILE="prj.conf overlay-smsc911x.conf".

**Comment by jukkar** [comment]
Hmm, I will investigate this. The original commit I sent fixed a real issue. It seems that the fix exposed some other issue.
