### ISSUE TITLE
Native_posix: command line handling: Hint users why an option does not exist

### ISSUE THREAD

**Issue by jukkar** [zephyrproject-rtos/zephyr#15046]
I just compiled `samples/net/sockets/dump_http_server` which does not enable UART by default. I then tried to start the sample app using this command `zephyr/zephyr.exe -attach_uart` but got an error `Incorrect option '-attach_uart'`. It took some time to figure out what was going on.

Anyway, my point was that the all the command line options should be always available. If the option is not really usable with that configuration, it should/could tell the user that "option is not available with this configuration" and possibly give some hint what to enable in zephyr config file.

**Comment by aescolar** [comment]
( Changing to enhancement, as this is indeed an enhancement request, not a bug :) )

Uhm... The thing is, many options exist only when a given driver/component/application is compiled in. There is no central place where all possible options are known.

It would be certainly possible to change the error message, and help message, so they would hint the user about why an option is not available (Say: "Incorrect option %s. Did you miss-spell it? Is that feature supported in this build?" )
@jukkar : Would that be an acceptable enough solution?

**Comment by jukkar** [comment]
After looking how the command line options are done, I understand that is indeed difficult task to do what I was proposing. Your suggestion for a hint "Incorrect option %s. Did you miss-spell it? Is that feature supported in this build?"  sounds like a good workaround.
