### ISSUE TITLE
tests/subsys/settings/fcb/src/settings_test_save_unaligned.c fail with assertion failure on nrf52_pca10040 

### ISSUE THREAD

**Issue by cinlyooi-intel** [zephyrproject-rtos/zephyr#15063]
Same as #13734. Created new bug instead of reopening because of 
 - the time passed since bug was closed.
 - Observed on second platform

The tests in tests/subsys/settings/fcb/src/settings_test_save_unaligned.c fail with assertion failure on nrf52_pca10040 and nrf52840_pca10056:arm. It occurs on both tests/subsys/settings/fcb/base64 and tests/subsys/settings/fcb/raw/

**Commit ID: ** 89735fb401a82ac64414d14331733ab1db5ce3f

**Arch:** arm
**Platforms:** nrf52_pca10040

**Error on console log:**
nrf52_pca10040:arm
```
***** delaying boot 1000ms (per build configuration) *****
***** Booting Zephyr OS v1.14.0-rc1-506-g406e942949 (delayed boot 1000ms) *****
===================================================================
starting test - test_config_save_fcb_unaligned

Assertion failed at /home/jenkins/workspace/zephyr-master-ci-master/zephyr.git/tests/subsys/settings/fcb/src/settings_test_save_unaligned.c:40: test_config_save_fcb_unaligned: (val8_un == 33 is false)
bad value read
FAIL - test_config_save_fcb_unaligned
===================================================================
Test suite test_config_fcb failed.
PROJECT EXECUTION FAILED
```

**Comment by nvlsianpu** [comment]
@cinlyooi-intel 

Didn't you  run this test without waiting for execution end before failure? This indeed cause failure which is consequence of unexpected flash area content.

**Comment by nvlsianpu** [comment]
This is testing suite bug (test suite need to be fixed) - not setting subsystem bug.
