### ISSUE TITLE
tests/kernel/fp_sharing: undefined reference k_float_disable()

### ISSUE THREAD

**Issue by cinlyooi-intel** [zephyrproject-rtos/zephyr#15064]
**To Reproduce**
1. mkdir build; cd build
2. cmake -DBOARD=qemu_x86
3. make

**Screenshots or console output**
```
tests/zephyr.git/tests/kernel/fp_sharing/src/main.c:238: undefined reference to `k_float_disable'
```

**Environment (please complete the following information):**
 - OS: fedora29
 - Toolchain zephyr
 - Commit SHA or Version used: f89735fb401a82ac64414d14331733ab1db5ce3f

**Additional context**

**Comment by ceolin** [comment]
fixed in 96659ac83be755cd7909df4b2250bfa8378ad5f6
