### ISSUE TITLE
Is the level2 interrupt supported for ARM cortex-M0P core?

### ISSUE THREAD

**Issue by lylezhu2014** [zephyrproject-rtos/zephyr#15133]
For ARM cortex-M0P core, the MAX IRQ Line is 32 for peripherals.  In order to support more, the level2 inetrrupt controller is added.
Is the level2 interrupt supported for ARM cortex-M0P core? If yes, how to use this feature. If no, is there a plan to support this feature?

**Comment by aescolar** [comment]
@ioannisg Can you help here?

**Comment by ioannisg** [comment]
A bit confused here, are you talking about an external interrupt controller, not NVIC?

**Comment by lylezhu2014** [comment]
Yes. Both the external interrupt controller (a perperial of the ARM core) and NVIC exist for the same one core.

**Comment by mbolivar** [comment]
@ioannisg @lylezhu2014 Zephyr has generic multi-level interrupt support for all architectures. The driver API is `struct irq_next_level_api`. If the M0+ has another interrupt controller built in at architecture level, I'd start by looking for that API implemented for it. If not, I suppose it would need to be added.

**Comment by ioannisg** [comment]
Yeah, the api is not implemented for cortex-m, afaics.

**Comment by ioannisg** [comment]
Haven't heard any discussions about supporting this in the stack, do you want to file a feature request @lylezhu2014 ?

**Comment by lylezhu2014** [comment]
@ioannisg I created a ticket #16168 to address this requirement.

**Comment by ioannisg** [comment]
Great, then, I think you can close this one
