### ISSUE TITLE
implement sys_sem that can reside in user memory

### ISSUE THREAD

**Issue by andrewboie** [zephyrproject-rtos/zephyr#15139]
Semaphores are a basic IPC mechanism currently offered by k_sem, which is a kernel object. We could implement these in userspace based on the wake/wait APIs instead, allowing the semaphore data structures to reside in user memory.

**Comment by andrewboie** [comment]
Requires #14493

**Comment by wentongwu** [comment]
studying futex these days, sys_sem's implementation highly depends on userspace's API of futex, it seems most of the work is on futex side.
