### ISSUE TITLE
testing flash driver clients in CI

### ISSUE THREAD

**Issue by nvlsianpu** [zephyrproject-rtos/zephyr#15180]
**problem**
Components which are using flash driver are not well tested. Test for these component are on-board tests, so are not run in CI.

components scope:
* subsys/settings
* subsys/FS/fcb
* subsys/FS/nvs
* subsys/dfu
* ...

**solution**
We can provide emulated flash driver https://github.com/zephyrproject-rtos/zephyr/pull/8254 (https://github.com/zephyrproject-rtos/zephyr/issues/7403) which will be used along with qemu's as test target - so it can be very easily to run these tests in zephyr CI.

some component already have test using RAM emulated driver (like NFFS) - this prove that this enchantment is not difficult to achieve.

**Comment by nvlsianpu** [comment]
cc @carlescufi @kapi-no

**Comment by ioannisg** [comment]
@nvlsianpu has this issue been worked for 2.0 release? Otherwise, can we move this to next one?

**Comment by nvlsianpu** [comment]
Both posix flash driver and emulated flash driver for qemu are available in codebase since while.
FCB, NVS, settings and dfu/ modules  are tested in CI using qemu and native_posix targets.
