### ISSUE TITLE
tests/booting: Considering remove it

### ISSUE THREAD

**Issue by cinlyooi-intel** [zephyrproject-rtos/zephyr#15198]
Consider removing tests/booting

tests/booting has only one directory, i.e. `stub`

`stub` has no testcase.yaml, It has boilerplate `CMakeList.txt` and `prj.conf` and simply set `CONFIG_BOOT_BANNER=n`. `src/main.c` states
```
void main(void)
{
	/* Quark: this is an x86 stub to just run ARC; it does nothing
	 * but start the x86 kernel so it will pass messages from the
	 * ARC processor via the IPM module.
	 *
	 * There is a solution planned for the future that will allow
	 * this workaround to be removed (without need to support
	 * backwards compatibility). */
}
```

If the solution planned already exists, we should remove `tests/booting`. Otherwise please consider placing a note saying that missing testcase.yaml is intentional. That will stop pedantic person like me filing bugs like this.

**Comment by nashif** [comment]
@cinlyooi-intel afaik tcf uses this file now for flashing arduino boards, so it is not a bug. We can revisit this later.
