### ISSUE TITLE
arc: it's not reliable to use exc_nest_count to check nest interrupt

### ISSUE THREAD

**Issue by vonhust** [zephyrproject-rtos/zephyr#15285]
**Describe the bug**
   using exc_nest_count to decide whether is nest int is not reliable.  a better option is to use IRQ_ACT

**To Reproduce**
 A case is:  a high priority int preempts a low priority int before rirq_enter/firq_enter, then in _rirq_exit/_firq_exit, it will see exc_nest_cout is 0, this will lead to possible thread switch, but a low priority int is still pending.

**Expected behavior**
For the above case, when the high pri int exits, it should return to low pri int,  should not do a thread switch

**Comment by nashif** [comment]
@ruuddw @vonhust are you working on a fix for this?
