### ISSUE TITLE
add QEMU target for armv8-M with MPU support

### ISSUE THREAD

**Issue by andrewboie** [zephyrproject-rtos/zephyr#15305]
QEMU 4.0 seems to have support for ARMv8-M and its MPU. Create a CI build target that runs as this, with MPU support enabled.

This will greatly help keep the ARMv8-M port of memory protection from bit-rotting as we will be able to validate test cases with CI.

**Comment by ioannisg** [comment]
@andrewboie @galak I did a first try on this, and it seems I can execute the samples, tests on ARMV8-M, when I disable MPU.
