### ISSUE TITLE
printf causing usage fault 

### ISSUE THREAD

**Issue by Pathak94** [zephyrproject-rtos/zephyr#15316]
I'm trying to print float values to the console. But, it is causing usage fault error. Also, I'm trying to read sensor values and trying to write it to the SD card.  

Here, code fails. 
```
printf("AX=%10.2f AY=%10.2f AZ=%10.2f (m/s^2)\r\n",
 		sensor_value_to_double(&accel[0]),
 		sensor_value_to_double(&accel[1]),
 		sensor_value_to_double(&accel[2]));
```
**To Reproduce**
1. mkdir build; cd build
2. cmake -GNinja -DBOARD=nrf52840_blip ..
3. make

**Expected behavior**

***** USAGE FAULT *****
  Illegal load of EXC_RETURN into PC
***** Hardware exception *****
Current thread ID = 0x200002d0
Faulting instruction address = 0x0
Fatal fault in thread 0x200002d0! Aborting.

I get the same error with printk as well.

**Comment by ioannisg** [comment]
Could you give some more details, e.g. which sample/test your are attempting to execute, where do place the code snippet you posted, etc.?

**Comment by andrewboie** [comment]
are you using minimal libc or newlib?
what platform are you running this on?
printk doesn't support floating point at all, I can tell you that
