### ISSUE TITLE
blink_led sample does not work on most of the nRF boards

### ISSUE THREAD

**Issue by anangl** [zephyrproject-rtos/zephyr#15323]
The issue was originally reported on slack (#general):
```
Aaron Tsui 9:15 AM, March 22nd
BTW, As the PWM_CLK lowest is 125khz(16M/128) and COUNTERTOP max is 0x7fff on nrf52, my understanding the nrf52 HW PWM longest period is about 262ms, cannot reach period as 1000ms. right?
@gaute this will cause failure on sample/blink_led, which need a 1000ms period.
```
Indeed, when trying to run this sample on any board with an nRF52 series SoC, which by default uses the HW PWM driver, one hits the following error:
```
PWM demo app-blink LED
pwm pin set fails
[00:00:00.008,544] <err> pwm_nrfx: Prescaler for period_cycles 16000000 not found.

[00:00:00.008,544] <err> pwm_nrfx: Incompatible period 16000000
```
Same happens for boards with nRF91 series SoCs.

For nRF52 the solution could be to use the nRF SW PWM driver, for nRF91 the driver is unavailable.

**Comment by carlescufi** [comment]
@pabigot could you please check if this is still an issue?
