### ISSUE TITLE
There are no RISC-V boards in the list of supported boards

### ISSUE THREAD

**Issue by SebastianBoe** [zephyrproject-rtos/zephyr#1532]
The RISC-V board zedboard_pulpino is not following the standard for how board documentation should be organized.

This causes RISC-V to be omitted from the list:
https://www.zephyrproject.org/doc/boards/boards.html

It has a README file 
zephyr/boards/$ARCH/$BOARD/README 

but it should have a file like this:

zephyr/boards/<arch>/<board>/doc/*.rst

And there should be an index.rst file for RISC-V.

If there are no supported RISC-V boards then this issue can be closed as invalid.

**Comment by dbkinder** [comment]
See also: https://jira.zephyrproject.org/browse/ZEP-1897 "Missing board documentation for riscv32/zedboard_pulpino"
