### ISSUE TITLE
Unable to reset nRF52840 from nRF9160 on pca10090 DK

### ISSUE THREAD

**Issue by lemrey** [zephyrproject-rtos/zephyr#15334]
It is desirable to be able to reset the nRF52840 on the pca10090 DK from the nRF9160, especially in situations where the two SoC communicate and their state needs to be synchronized (and given that only one reset button exists on the board).

Because the nRF52840 chip does not have a reset line connected to the nRF9160, a GPIO line can be used to issue a reset. Let nrf52840_pca10090 be reset via a dedicated line.

**Comment by ioannisg** [comment]
@carlescufi are we addressing this in 1.14?

**Comment by carlescufi** [comment]
@ioannisg yes, we are waiting for a PR from @lemrey

**Comment by ioannisg** [comment]
@lemrey any updates?

**Comment by lemrey** [comment]
This was done in: https://github.com/zephyrproject-rtos/zephyr/pull/15512
