### ISSUE TITLE
ARM Cortex-M: SysTick: unhandled race condition

### ISSUE THREAD

**Issue by ioannisg** [zephyrproject-rtos/zephyr#15348]
It looks like we are not handling properly a possible race condition in ARM Cortex-M SysTick.

The implementation in `z_clock_set_timeout()` for TICKLESS mode performs the following steps:
1. Disables interrupts
2. Calculates SysTick re-load value based on the desired timeout
3. Re-configures and re-starts the SysTick timer to count-down towards this timeout.
4. Re-enables interrupts.

If, during steps (1) and (2) the SysTick actually wraps, an event will be triggered and the SysTick interrupt will be pending. As a result, as soon as we re-enable the interrupt, the ISR will be executed immediately; not after the desired timeout.

The event is rare but the impact is significant - we are advancing the clock immediately, when we should have been waited for the timeout.

Root-cause and solution:
Clearing the internal SysTick status flag (CTRL.COUNTFLAG) is not sufficient to clear a pending event; we also need to do it explicitly in ICSR (Clear the PENDSTSET bit).

Reproduce:
I have written a simple HW test case for ARM SysTick (a modified hello-world example) here:

https://github.com/ioannisg/zephyr/tree/drivers_systick_testcase/samples/hello_world

which demonstrates that clearning the COUNTFLAG is not sufficient to suppress already pending events (See TEST 4 and TEST 5).

**Comment by ioannisg** [comment]
FYI @andyross @pizi-nordic

**Comment by ioannisg** [comment]
FYI @MaureenHelm @galak 
This affects tick-less operation in ARM platforms with SysTick as system timer.

**Comment by pizi-nordic** [comment]
For me this issue is a next call for absolute time in kernel. As the timer is running all the time, the software will always be racing with it. So we either get more interrupts than we want or we lost/delay some of them.
And the code should be prepared to deal with such situations.
