### ISSUE TITLE
The docs incorrectly state that common.dts integrates with mcuboot

### ISSUE THREAD

**Issue by SebastianBoe** [zephyrproject-rtos/zephyr#15359]
The documentation is stating something that is incorrect. It says that;

> The [file common.dts] conditionally includes a fragment for MCUboot chain-loading, located at dts/common/mcuboot.overlay, if CONFIG_BOOTLOADER_MCUBOOT is set.

But in reality common.dts no longer does anything and should be removed. Along with any documentation referencing it.

**Comment by jenmwms** [comment]
This looks done. @mbolivar can you please confirm?

**Comment by SebastianBoe** [comment]
This isn't fixed, but I now added the text

"fixes #15359"

to the description of #19774, so when it is merged this will automatically be closed.
