### ISSUE TITLE
Driver for U-Blox SARA modem (used by Particle Boron)

### ISSUE THREAD

**Issue by tautologyclub** [zephyrproject-rtos/zephyr#15355]
We're currently working on a driver for the U-Blox Sara modem and I'd like to check if anyone else is working on the same thing. We're planning to upstream our work either way. 

Pinging @pabigot (author of Particle Boron board config files).

**Comment by mike-scott** [comment]
I have a working modem driver for SARA modem here: https://github.com/zephyrproject-rtos/zephyr/pull/14057

**Comment by tautologyclub** [comment]
@mike-scott Wow that's great news!

**Comment by mike-scott** [comment]
Driver added to Zephyr here: https://github.com/zephyrproject-rtos/zephyr/commit/1f199b300b8ca1ebdfccb9840dbb64262ff82199
