### ISSUE TITLE
Bluetooth qualification test MESH/SR/HM/CFS/BV-02-C is failing

### ISSUE THREAD

**Issue by jhedberg** [zephyrproject-rtos/zephyr#15365]
The Bluetooth Mesh qualification test MESH/SR/HM/CFS/BV-02-C is failing with latest master

**Comment by tedd-an** [comment]
Tested with PR above and test still failed.
AutoPTS report:
[MESH_MESH_SR_HM_CFS_BV-02-C.log](https://github.com/zephyrproject-rtos/zephyr/files/3069737/MESH_MESH_SR_HM_CFS_BV-02-C.log)

Sniffer from PTS side:
[MESH_SR_HM_CFS_BV_02_C_2019_04_11_09_52_32.zip](https://github.com/zephyrproject-rtos/zephyr/files/3069748/MESH_SR_HM_CFS_BV_02_C_2019_04_11_09_52_32.zip)
