### ISSUE TITLE
USAGE FAULT on tests/crypto/rand32/ on sam_e70_xplained

### ISSUE THREAD

**Issue by cinlyooi-intel** [zephyrproject-rtos/zephyr#15380]
Occurs for testcase  crypto.rand32.random_hw_xoroshiro.rand32

**To Reproduce**
1. mkdir build; cd build
2. cmake -DBOARD=sam_e70_xplained
3. make
4. make run

**Screenshots or console output**
```
***** USAGE FAULT *****
  Illegal load of EXC_RETURN into PC
***** Hardware exception *****
Current thread ID = 0x00000000
Faulting instruction address = 0x48024001
Fatal fault in essential thread! Spinning...
```
**Environment (please complete the following information):**
 - OS: fedora29
 - Toolchain: zephyr
 - Commit SHA or Version used: a69cb036c4e457e66e9bd94549b8151e74229598

**Additional context**
Please note that the Usage Fault message in different from that in #13935

**Comment by nashif** [comment]
I think it is still the same issue as #13935
