### ISSUE TITLE
[Coverity CID :197605]Null pointer dereferences in /subsys/testsuite/ztest/src/ztest_mock.c

### ISSUE THREAD

**Issue by aasthagr** [zephyrproject-rtos/zephyr#15399]
Static code scan issues seen in File: /subsys/testsuite/ztest/src/ztest_mock.c
 Category: Null pointer dereferences
 Function: z_ztest_check_expected_value
 Component: Other
 CID: 197605
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by aasthagr** [comment]
*** CID 197605:  Null pointer dereferences  (FORWARD_NULL)
/subsys/testsuite/ztest/src/ztest_mock.c: 196 in z_ztest_check_expected_value()
190     param = find_and_delete_value(&parameter_list, fn, name);
191     if (!param) {
192     PRINT("Failed to find parameter %s for %s\n", name, fn);
193     ztest_test_fail();
194     }
195     
>>>     CID 197605:  Null pointer dereferences  (FORWARD_NULL)
>>>     Dereferencing null pointer "param".
196     expected = param->value;
197     free_parameter(param);
198     
199     if (expected != val) {
200     /* We need to cast these values since the toolchain doesn't
201      * provide inttypes.h

**Comment by aescolar** [comment]
False positive. Confirmed by @mtpr-ot ("the ztest_test_fail() will abort the process if param == NULL, so no NULL pointer dereference is possible."). Flagged as false positive.
