### ISSUE TITLE
[Coverity CID :197613]Possible Control flow issues in /subsys/net/ip/net_core.c

### ISSUE THREAD

**Issue by aasthagr** [zephyrproject-rtos/zephyr#15391]
Static code scan issues seen in File: /subsys/net/ip/net_core.c
 Category: Possible Control flow issues
 Function: services_init
 Component: Networking
 CID: 197613
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by aasthagr** [comment]
*** CID 197613:  Possible Control flow issues  (DEADCODE)
/subsys/net/ip/net_core.c: 436 in services_init()
430     static inline int services_init(void)
431     {
432     int status;
433     
434     status = net_dhcpv4_init();
435     if (status) {
>>>     CID 197613:  Possible Control flow issues  (DEADCODE)
>>>     Execution cannot reach this statement: "return status;".
436     return status;
437     }
438     
439     dns_init_resolver();
440     
441     net_shell_init();

**Comment by tbursztyka** [comment]
@jukkar can you mark this as a non-issue in coverity? When dhcpv4 is not enabled, indeed that code flow cannot happen (but gcc is smart enough to optimize that path).

**Comment by jukkar** [comment]
Agreed, this is a non-issue. I will mark it.
