### ISSUE TITLE
[Coverity CID :197596]Memory - corruptions in /tests/net/lib/mqtt_packet/src/mqtt_packet.c

### ISSUE THREAD

**Issue by aasthagr** [zephyrproject-rtos/zephyr#15408]
Static code scan issues seen in File: /tests/net/lib/mqtt_packet/src/mqtt_packet.c
 Category: Memory - corruptions
 Function: test_mqtt_packet
 Component: Tests
 CID: 197596
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by rlubos** [comment]
False positive
