### ISSUE TITLE
reset and halt function

### ISSUE THREAD

**Issue by StefJar** [zephyrproject-rtos/zephyr#15419]
It would be great to have an "reset" or "halt" function, which can be called form user space.

Use cases:
-  something got bad inside the app
- own firmware upgrades via own bootloader written with ZephyrOS

**Comment by aescolar** [comment]
`sys_reboot` does not fulfill your needs?

**Comment by StefJar** [comment]
thanks - almost there
1st) for me a bit confusing, that a "sys_reboot" function can be activated under boot options
2nd) a halt function which stops the system but does not a reboot. This is useful for error search

**Comment by aescolar** [comment]
@StefJar I assign @andrewboie as I hope he can help be more useful in this discussion

**Comment by andrewboie** [comment]
`> a halt function which stops the system but does not a reboot. This is useful for error search

k_panic() does this

**Comment by carlescufi** [comment]
Summarizing the answers:

- `sys_reboot()` will reboot the MCU
- `k_panic()` will halt the system

**Comment by StefJar** [comment]
maybe we can add this information to the kernel API documentation
