### ISSUE TITLE
Error initiating sdhc disk

### ISSUE THREAD

**Issue by lucaspeixotot** [zephyrproject-rtos/zephyr#15444]
I tried to run samples/subsys/fs and I got error in `disk_access_init()` function. Tracking the problem, I noticed that the error was at the beginner of the communication between mcu and sdhc, when the mcu needs to send some CMD messages to initiate the communication. The error was, more specifically, in the sending of CMD9(SDHC_SEND_CSD) message.

```
(file disk_accesss_sdhc.c, sdhc_detect function, line 754)
/* Read the CSD */
	err = sdhc_cmd_r1(data, SDHC_SEND_CSD, 0);
	if (err != 0) {
		return err;
	}

	err = sdhc_rx_block(data, buf, sizeof(buf));
	if (err != 0) {
		return err;
	}

```

If we look `sdhc_cmd_r1_raw()` function, which is called inside `sdhc_cmd_r1()` function, we will see that we are discarding a byte with this code

```
(file disk_accesss_sdhc.c, sdhc_cmd_r1_raw function, line 457)
/* Ensure there's a idle byte between commands */
	sdhc_rx_u8(data);
```

I think that this is the problem, because according to this table we can't discard every time,

![2019-04-14-144849_910x463_scrot](https://user-images.githubusercontent.com/11475476/56096922-6e619280-5ec4-11e9-860c-d9db00aef0de.png)

there is some commands that have a data packet response after R1, R3/R7 response, so the existence of the code above is eating the message token of data packet response.

To solve this bug I just replace the code above with this if statement

```
	if (cmd != SDHC_SEND_CSD && cmd != SDHC_SEND_CID &&
	    cmd != SDHC_READ_SINGLE_BLOCK && cmd != SDHC_READ_MULTIPLE_BLOCK &&
	    cmd != SDHC_WRITE_BLOCK && cmd != SDHC_WRITE_MULTIPLE_BLOCK) {
		sdhc_rx_u8(data);
	}
```

and the sdhc disk was initiated and mounted successfully. I do not know if this is the best solution, but is the solution that worked for me until now.

@EDIT: I'm sorry, I think that I was not clear, I forgot to mention that the error is in sdhc_rx_block, after send SDHC_SEND_CSD. In this portion of code

```
	if (token != SDHC_TOKEN_SINGLE) {
		/* No start token */
		return -EIO;
	}
```

The data packet response token was lost.

**Comment by Pathak94** [comment]
Thank you for the fix! I also encountered this issue with nrf52840_blip board, by doing the fix you suggested, the problem is solved. Will you send a PR for this?

**Comment by lucaspeixotot** [comment]
I'm glad it worked for you. Probably this week I will create a PR.

As you are using sdhc worth another tip, the unmount function was not implemented for fatfs. So I created a PR that you can see here #15712

**Comment by Pathak94** [comment]
Noted! Thanks.
