### ISSUE TITLE
regression: net: K64F: DHCP seems to fail a lot after 91041f9e

### ISSUE THREAD

**Issue by mike-scott** [zephyrproject-rtos/zephyr#1544]
It's not 100% but most of the time, DHCP seems to fail on master branch using K64F.

I'm testing a revert on 91041f9e7363e5ccd984dfef7adbe9bd4b84b572 to see if that restores normal behavior.

**Comment by pfalcon** [comment]
> It's not 100% but most of the time, DHCP seems to fail on master branch using K64F.

Given that DHCP [server] is an external thing, probably worth mentioning your setup. (Test process too.)

**Comment by mike-scott** [comment]
Let me draw up a detailed report.  When I tested the DHCPV4 sample just now, I wasn't able to reproduce.  But our CI testing suddenly stopped working on K64F today after the mainline merges this morning.  And the logs showed that the devices weren't getting DHCP addresses anymore.

**Comment by jukkar** [comment]
Ok, lets revert the multicast IPv4 mac address setting then. I will send a patch for that.

**Comment by pfalcon** [comment]
@jukkar: I'd say we wait for additional info from @mike-scott. I eyeballed that patch and don't see anything obvious there (single bit flip is hard to blame without more arguments why would it matter). So far, @mike-scott reported that CI got broken, and well, that's normal, CIs are their to break (on their own) ;-).

**Comment by jukkar** [comment]
@pfalcon I hope @mike-scott could test the #1564 and report if it is fixing things. And if everything works ok without the bit flip (the original way), then we can go back how the thing worked originally.

**Comment by pfalcon** [comment]
Sure, sounds good. (My particular interest is due to the queued work on supporting true IPv6 multicast. Currently, the frdm_k64f eth is just in promisc mode overall; just imagine what kind of can of worms can be opened if that switched to the actual multicast filtering - unless we really try to figure out things).

**Comment by mike-scott** [comment]
@jukkar Sorry, I forgot to write back earlier.  The new patch fixes CI testing as well.
