### ISSUE TITLE
Kconfig should enforce that at most one Console driver is enabled at a time

### ISSUE THREAD

**Issue by SebastianBoe** [zephyrproject-rtos/zephyr#15453]
**Is your feature request related to a problem? Please describe.**
As the Kconfig sources are written today multiple Console drivers can be enabled simultaneously, but this results in an invalid configuration as only one Console driver should be enabled at a time.

**Describe the solution you'd like**
Kconfig should enforce somehow, for instance through a 'choice' construct, that only one Console driver is enabled at a time.

**Comment by carlescufi** [comment]
@ulfalizer could you comment on this one?

**Comment by nashif** [comment]
stale
