### ISSUE TITLE
doc: settings Misleading examples

### ISSUE THREAD

**Issue by MarekPieta** [zephyrproject-rtos/zephyr#15451]
In both examples function `foo_settings_set` is used as `.h_set` callback. There is `settings_val_read_cb(value_ctx, &foo_val, sizeof(foo_val));` used as return value. The function typically returns number of bytes read, which is treated as error code by callback (when there is no error, zero should be returned).
This makes documentation misleading for reader.

**Comment by ioannisg** [comment]
@MarekPieta @nvlsianpu  is this going to make it to 2.0.0 release?
