### ISSUE TITLE
usb composite MSC + HID (with CONFIG_ENABLE_HID_INT_OUT_EP)

### ISSUE THREAD

**Issue by dmazzella** [zephyrproject-rtos/zephyr#15486]
**HW: NRF52840 (pca10059).**
I have tried to build a composite device with MSC (ram or flash) + HID with  CONFIG_ENABLE_HID_INT_OUT_EP.

On Linux and MacOS work fine, but on Windows i have problem.

Attached minimal test build with prj_nrf52840_pca10059.conf.

[hid_w_out_ep-mass.zip](https://github.com/zephyrproject-rtos/zephyr/files/3085596/hid_w_out_ep-mass.zip)

Attached screenshots.

![hid_w_out_ep_and_msc1](https://user-images.githubusercontent.com/3988243/56220810-5d05bb00-6069-11e9-9e10-9b1e2b9f8410.png)

![hid_w_out_ep_and_msc2](https://user-images.githubusercontent.com/3988243/56220817-6000ab80-6069-11e9-94cd-1c83c5b6e534.png)

**Comment by masz-nordic** [comment]
Hi @dmazzella, can you use [bug  issue template](https://github.com/zephyrproject-rtos/zephyr/blob/master/.github/ISSUE_TEMPLATE/bug_report.md)? Also, a branch on fork would be more useful than a .zip file.

**Comment by dmazzella** [comment]
@masz-nordic sorry for template error. Yes, i can use a bug issue template.

close this and open new one?
