### ISSUE TITLE
 Can I use one custom random static bd_addr before provision?

### ISSUE THREAD

**Issue by summer20100514** [zephyrproject-rtos/zephyr#15504]
I want to change the bluetooth advertisement id_addr before provision, and I read the source code but find that the advertisement use BT_ID_DEFAULT which can't be deleted or changed and is initialized by read out static addr. Is it true? Can I use one custom random static bd_addr in other way? @jhedberg @Vudentz

**Comment by summer20100514** [comment]
@carlescufi problem solved! thank you!

**Comment by szundi** [comment]
> Yes, just use:
> 
> `bt_set_id_addr()` before you call `bt_enable()` and then the flag `BT_LE_ADV_OPT_USE_IDENTITY` when you call `bt_le_adv_start()`

Worked like a charm.
