### ISSUE TITLE
nRF timer unnecessary configuration?

### ISSUE THREAD

**Issue by pabigot** [zephyrproject-rtos/zephyr#15513]
While working on my alarm infrastructure I noticed that nrf_timer_rtc for the system clock uses nrf_rtc_event_enable() for COMPARE0, which is the basic timer event, and has done so since the module was originally implemented in 2016.

As I understand it enabling events is intended to introduce a dependency on HFCLK to support use with PPI, but it increases power consumption when HFCLK is not otherwise required.  AFAICT nobody should ever connect that event to a PPI except possibly for whitebox instrumentation.

Is that configuration step appropriate?

**Comment by nordic-krch** [comment]
Not sure if I understand the issue but enabling event is required to get interrupt from that COMPARE0 event. It has to be done even if PPI is not used.

**Comment by pabigot** [comment]
@nordic-krch No.  Enabling INTEN is necessary to get the interrupt.  Enable EVTEN is necessary for only for PPI.

**Comment by pabigot** [comment]
[Nordic devzone](https://devzone.nordicsemi.com/f/nordic-q-a/14023/evten-inten-nrf52-rtc) has a very clear description of the rolls of `EVTEN` versus `INTEN`.

The [nRF52840 Product Specification](https://infocenter.nordicsemi.com/topic/ps_nrf52840/rtc.html?cp=3_0_0_5_21_5#concept_eml_dkj_sr) explains why channels should be disabled in `EVTEN` if PPI is not being used.

**Comment by nordic-krch** [comment]
I didn't know that then.

> The nRF52840 Product Specification explains why channels should be disabled in EVTEN if PPI is not being used.

Frankly speaking, to me this section doesn't mention PPI and drawing shows that `EVTEN` register gates PPI and IRQ so i'm confused. I guess you verified it so it's rather documentation issue.

**Comment by pabigot** [comment]
Agree the diagram is a little confusing; the tie to PPI is in the text at the end of the arrow at the bottom.

I've been doing system timers with Nordic for over four years now and never had to touch the EVTEN registers, which is why I was a bit confused when I looked at what that HAL function did.  I've certainly verified it's not necessary.
