### ISSUE TITLE
[FCB question] Is it true that fcb storage won't overwrite old records which limits the max num?

### ISSUE THREAD

**Issue by summer20100514** [zephyrproject-rtos/zephyr#15549]
As we all know, zephyr uses one storage backend which is fcb. We have tested the library and find that if there is no room for more data, it won't overwrite the old ones, and therefore only a specific number of records can fit into the storage. right?
@nvlsianpu

**Comment by nvlsianpu** [comment]
@summer20100514  This was question tho the fcb setting back-endI answered on slack right?

**Comment by summer20100514** [comment]
@nvlsianpu there is high chance the program will crash(blocking?) if I write multile records using settings_save_one when it comes to the 4K boundary. is there any best practice rules I must obey here using fcb?

**Comment by summer20100514** [comment]
my usage fault, issue closed
