### ISSUE TITLE
Master reports itself as if it was 1.9.0 release

### ISSUE THREAD

**Issue by pfalcon** [zephyrproject-rtos/zephyr#1558]
Aka, we need PATCHLEVEL = 99.

**Comment by nashif** [comment]
considering to call this 1.10.0-dev or something like that, 1.9.99 while seems not realistic, is a valid dot release that we might reach at some point :-), thoughts?

**Comment by pfalcon** [comment]
Thoughts are: 1.9.99 is not realistic patch release we can reach. However, something like 5.13.99 in a dozen of years may be. If we want to solve that right now without much bikeshedding, let's just use 1.9.999. But that scheme worked pretty well for few releases, so I don't think it should be abandoned out of the blue. (And yep, the whole idea behind it was to be able to detect anything below a release X with just numeric comparisons (e.g. via C preprocessor).

**Comment by pfalcon** [comment]
@carlescufi : ^^^, FYI. I believe it was you who raised concerns with "99", I apologize if it was another Nordic guy. Please see if above works for you.

**Comment by carlescufi** [comment]
I am OK with using 999, the requirements on my side where to have a "build type" (dev, rc or production), which won't be solved by this anyway and it's tracked in an issue

**Comment by pfalcon** [comment]
> which won't be solved by this anyway and it's tracked in an issue.

> In fact, with the current macros I actually prefer the 999 scheme, because at least one knows that this is a dev build without having to parse a string

Exactly, and at the corresponding ticket, I gave an idea that we can have:

~~~
#if PATCHLEVEL == 99(9)
#define BUILDTYPE "dev"
#endif
~~~

**Comment by pfalcon** [comment]
Thanks for acking "999" btw.
