### ISSUE TITLE
nRF52: 2.4 GHz proprietary RF support

### ISSUE THREAD

**Issue by KwonTae-young** [zephyrproject-rtos/zephyr#15607]
I am trying to make a wireless keyboard using the `nRF52840`.

At first I tried to use another MCU + [nRF24L01](https://www.nordicsemi.com/?sc_itemid=%7B36BDC7E1-5E35-4967-8B4D-E41DCD96512F%7D).
However, the product description says `Not recommended for new designs`.
I do not know exactly why it is `Not recommended for new designs`.
[nRF24 Series](https://www.nordicsemi.com/?sc_itemid=%7B36BDC7E1-5E35-4967-8B4D-E41DCD96512F%7D)
![image](https://user-images.githubusercontent.com/10510127/56557862-a27d3780-65d7-11e9-9987-25d49b157757.png)

So I'm looking at the `nRF52840`.
It is said that [nRF52 Series](https://www.nordicsemi.com/Products/Low-power-short-range-wireless/nRF52840#infotabs) supports `2.4 GHz proprietary`.  
![image](https://user-images.githubusercontent.com/10510127/56558058-57afef80-65d8-11e9-83f0-cc7682c89a71.png)

Does Zephyr support the `2.4 GHz proprietary` driver?
I could not find a related source.

I'm sorry I do not have enough English. :)
Thank you.

**Comment by carlescufi** [comment]
Hi @KwonTae-young. This feature is already supported in the zephyr-based SDK maintained by Nordic, take a look here: https://github.com/NordicPlayground/fw-nrfconnect-nrf/tree/master/samples/esb

**Comment by KwonTae-young** [comment]
@carlescufi
Thank you.
I did not know there was a separate SDK. :sweat_smile:
