### ISSUE TITLE
trickle.c can't work for multiple triggerings

### ISSUE THREAD

**Issue by lingwei901011** [zephyrproject-rtos/zephyr#15606]
**Describe the bug**
in subsys/net/ip/trickle.c, the delayed work "trickle->timer" is initialized in net_trickle_start() at the first time to set its handler function as trickle_timeout(), in which the callback function we need will be invoked. Then, in the trickle_timeout(), the reschedule() will be called to re-schedule the next interval. in reschedule(), the SAME delayed work "trickle->timer" is initialized at the second time to change its handler function to double_interval_timeout().  However, when double_interval_timeout() is invoked, it calculates the next interval correctly and directly submits the delayed work BUT it doesn't re-change the SAME delayed work "trickle->timer" handler function to trickle_timeout(). so the delayed work's handler function is always the "double_interval_timeout()" and NEVER call the trickle_timeout() again and NEVER invoke the callback function we need again!. 

**Expected behavior**
for multiple triggerings, we need re-initialize the SAME  delayed work "trickle->timer" to change its handler function to trickle_timeout(). the modification is shown as follow:
```
static void double_interval_timeout(struct k_work *work)
{
           trickle->Istart = k_uptime_get_32() + rand_time;
   +++ k_delayed_wokr_init(&trickle->timer, trickle_timeout);
            k_delayed_work_submit(&trickle->timer, rand_time);
}
```
we have verified the modified trickle on our STM32F217ZG board. 

**Impact**
the pre-version trickle timer can't trigger for multiple times. 

**Environment (please complete the following information):**
 - OS: Linux Ubuntu
 - Toolchain: Zephyr SDK
 - master

please feel free to contact me if any questions

**Comment by jukkar** [comment]
Nice analysis. Could you send a PR that implements the fix you have in the comment?
