### ISSUE TITLE
pwm: nRF default prescalar value is wrong

### ISSUE THREAD

**Issue by doceme** [zephyrproject-rtos/zephyr#15601]
**Describe the bug**
A value of 1 for the ```data->prescalar``` causes the frequency to be half of desired frequency. I've confirmed this using an oscilloscope. The correct value for ```data->prescalar``` should be ```0U```. 

**To Reproduce**
1. Modify ```samples/basic/fade_led/src/main.c``` to set a PWM cycle value to something <= 32767. For example:
```
pwm_pin_set_cycles(pwm_dev, PWM_CHANNEL, 29088, 29088 / 2); // 550 Hz
```
2. build with board ```nrf52840_pca10056```
3. flash and observe actual frequency of LED is half of expected value

**Expected behavior**
A PWM value of desired frequency (not halved).

**Impact**
nRF PWM driver is not usable at certain frequencies.

**Screenshots or console output**
Oscilloscope screenshot with default ```data->prescalar``` set to ```1U```:

![nRF PWM Bad Frequency](https://user-images.githubusercontent.com/196169/56507259-bb5dee00-64ee-11e9-84e3-aca1dfa1925d.png)

Oscilloscope screenshot with default ```data->prescalar``` set to ```0U```:

![nRF PWM Good Frequency](https://user-images.githubusercontent.com/196169/56507309-daf51680-64ee-11e9-8d10-4920ab270560.png)

**Environment (please complete the following information):**
 - OS: MacOS
 - Toolchain: GNU Arm Embedded Toolchain (prebuilt version 7-2018-q2-update)
 - Commit SHA or Version used: v1.14.0

**Comment by anangl** [comment]
@doceme Thanks for reporting this.
Obviously, when there is no need to divide the PWM clock, (i.e. the requested period cycles fit into the 15-bit PWM counter), the prescaler value should be `0`, not `1`. I'll provide a PR that fixes this.

**Comment by doceme** [comment]
Thanks @anangl. I was going to make a PR, but got busy.
