### ISSUE TITLE
properly define kernel <--> arch APIs

### ISSUE THREAD

**Issue by andrewboie** [zephyrproject-rtos/zephyr#15657]
We are part of the way there, but we need a very clear definition of the interface between the core kernel, and the arch/ code.

- All APIs and macros prefixed with z_arch_ / Z_ARCH_
- All interface definitions in a single interface header under kernel/include/. If someone wants to do a new arch port, they will know that everything they need to implement is in this header.
- Pulling in arch/cpu.h has everything namespaced with either Z_ARCH/z_arch or z_<name of arch>, no random stuff like STACK_ALIGN
- Documentation updates as necessary.

**Comment by ioannisg** [comment]
I would very much like to get this into 2.0 @andrewboie; please, give a status update on this :)

**Comment by andrewboie** [comment]
@ioannisg unsure if I'll get to this for 2.0. I haven't started it.
My highest priority remaining work for 2.0 is #14206 and #14683 
Let me see what I can do though, this one might not take too long.

**Comment by dleach02** [comment]
Should this still be open?

@andrewboie

**Comment by andrewboie** [comment]
Yup, I fixed this.
