### ISSUE TITLE
Can GPTP support multiple slave nodes

### ISSUE THREAD

**Issue by Jxudong** [zephyrproject-rtos/zephyr#15679]
When I use one master node and one slave node is working well, when I use one master node and  multiple slave nodes, there is a problem, the slave node report warning is as follows：

![image](https://user-images.githubusercontent.com/27182458/56779395-6cc19400-680d-11e9-9390-68f9f7bdc831.png)

Is this a configuration problem or does GPTP not support multiple child nodes?

**Comment by jukkar** [comment]
Are you using TSN supported Ethernet switch? Note that child nodes should not see each other traffic, only master should see child nodes traffic. This means that if you connect three TSN capable devices into normal Ethernet switch, there will be conflicts and it will not work.

**Comment by Jxudong** [comment]
This means that if I want to run GPTP, I have to use a switch with TSN functionality, not a normal switch?

**Comment by Jxudong** [comment]
@jukkar

**Comment by jukkar** [comment]
TSN capable switch is only needed if you have more than two nodes that you want to connect together.
You can overcome this by using VLANs which can be used to separate Ethernet traffic. Using VLANs with gPTP is not specified in gPTP spec but both Linux and Zephyr support that.

**Comment by ioannisg** [comment]
@Jxudong please, re-open, if needed , to continue discussion
