### ISSUE TITLE
"backport v1.14 branch" label: update description and doc

### ISSUE THREAD

**Issue by aescolar** [zephyrproject-rtos/zephyr#15680]
After renaming the backport label, and using it for the backport automation it was forgotten to update the label description and doc.
=>
Update the label description for "backport v1.14 branch", and the description in the doc: https://docs.zephyrproject.org/latest/development_process/dev_env_and_tools.html#pr-only-labels
to match the meaning of the new label.
Whenever a new doc section exists to describe the backporting process, link it from the entry in the doc.

**Comment by nashif** [comment]
Backport label still exists and is correctly documented. The 'backport v1.14 branch' is currently not working, so it would be documented once it is fixed. We might use a different approach, so closing this as it is not relevant anymore.
