### ISSUE TITLE
bluetooth: bt_conn: No proper ID handling

### ISSUE THREAD

**Issue by MarekPieta** [zephyrproject-rtos/zephyr#15698]
**Describe the bug**
bt_conn->id is probably not handled properly (using hardcoded value - zero) - noticed errors connected with inproper BLE connection handling while using directed advertising (e.g. unable to properly refer to the connection).

**Expected behavior**
ID should be updated correctly for BLE connections (it should not have hardcoded value of zero).

**Impact**
 It may cause errors in applications - e.g. problems with direct advertising.

**Comment by jhedberg** [comment]
Wasn't this fixed by #15532 ?

**Comment by jhedberg** [comment]
@pdunaj @carlescufi FYI

Another note: non-default id is only supported for peripheral role, so there should be no need to add custom id functionality for central-related code.

**Comment by MarekPieta** [comment]
We didnt set conn->id and it caused problems with direct advertising. Connection was not properly handled by API, which caused problems like advertising failing to start.

**Comment by jhedberg** [comment]
@MarekPieta thanks for clarifying, your updated PR is looking better (and simpler :)

**Comment by pdunaj** [comment]
Hi @jhedberg , the previous one caused resource leak but I admit I have not tested it enough and there was another bug there.
