### ISSUE TITLE
tests/ztests/mock/ : Stuck at test_parameter_tests

### ISSUE THREAD

**Issue by cinlyooi-intel** [zephyrproject-rtos/zephyr#15719]
**Describe the bug**
Test stuck at test_parameter_tests(). If I remove the test, the other tests will run fine. 

**To Reproduce**
1. mkdir build; cd build
2. cmake -DBOARD=altera_max10
3. make

**Expected behavior**

**Impact**
What impact does this issue have on your progress (e.g., annoyance, showstopper)

**Screenshots or console output**
```
***** Booting Zephyr OS zephyr-v1.14.0-345-gd44086db5a2a (delayed boot 3000ms) *****
Running test suite mock_framework_tests
===================================================================
starting test - test_parameter_tests
```
**Environment (please complete the following information):**
 - OS: fedora29
 - Toolchain: zephyr
 - Commit SHA or Version used: d44086db5a2aa362510d7ac1a1f2f401c8ff180c

**Additional context**
Please note that at time of writing, after removing test_parameter_tests(), I will encounter #15220

**Comment by carlescufi** [comment]
@cinlyooi-intel @nashif
I assume this is an old issue since emulation/simulation is not supported on this board, closing.
