### ISSUE TITLE
flash: should write_protection be emulated?

### ISSUE THREAD

**Issue by nvlsianpu** [zephyrproject-rtos/zephyr#15729]
According to https://docs.zephyrproject.org/latest/reference/peripherals/flash.html#_CPPv326flash_write_protection_setP6deviceb
write protection might behave different depending on which flash driver is used. Is this possible to relax it completely - so make this API no-operation for a driver. Then this driver would take care on its-own regard its internal protection.

I'm asking because for nRF flash driver write protection is completely emulated already - which will be not necessary if can relax it.

Objective is to clarify the documentation on the driver - not to remove flash protection API. It is clear that for portable code this API is required and have to be used everywhere,

**Comment by carlescufi** [comment]
Proposal:

- Modify the doc to reflect that this is a NOP on platforms that do not have hardware write protection
- Return 0 on those platforms that either do not have hardware write protection or it doesn't fit the API

**Comment by d3zd3z** [comment]
What about flash drivers that don't ever need to write to the flash. For example, some flash drivers, writes are entirely done through the controller. I would assume these would just never call this API.
