### ISSUE TITLE
[Coverity CID :198007]Memory - corruptions in /subsys/bluetooth/host/hci_core.c

### ISSUE THREAD

**Issue by aasthagr** [zephyrproject-rtos/zephyr#15773]
Static code scan issues seen in File: /subsys/bluetooth/host/hci_core.c
 Category: Memory - corruptions
 Function: id_create
 Component: Bluetooth
 CID: 198007
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by jhedberg** [comment]
Marked as false positive in Coverity
