### ISSUE TITLE
[Coverity CID :186196]Unchecked return value in  samples/sensor/lsm6dsl/src/main.c

### ISSUE THREAD

**Issue by maxxlife** [zephyrproject-rtos/zephyr#15814]
Unchecked return value in File:  samples/sensor/lsm6dsl/src/main.c 
Category: Error handling issues
Function: sensor_trigger_set
Component: Samples
CID: 186196
Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by maxxlife** [comment]
Fixed by #15743

**Comment by MaureenHelm** [comment]
> Fixed by #15743

If you put this link in the PR instead, the issue will automatically close when the PR gets merged. See https://help.github.com/en/articles/closing-issues-using-keywords

**Comment by maxxlife** [comment]
> > Fixed by #15743
> 
> If you put this link in the PR instead, the issue will automatically close when the PR gets merged. See https://help.github.com/en/articles/closing-issues-using-keywords

Ok, I did it:)

**Comment by ioannisg** [comment]
OK, but this is still open

**Comment by ioannisg** [comment]
Fixed
