### ISSUE TITLE
mcumgr: taskstat show name & used size

### ISSUE THREAD

**Issue by lgl88911** [zephyrproject-rtos/zephyr#15820]
**Is your enhancement proposal related to a problem? Please describe.**
Now mcumgr taskstat show prio to task name & can't show used stack size

**Describe the solution you'd like**
mcumgr taskstat show task name & used stack size

**Comment by de-nordic** [comment]
Already happening when `ONFIG_OS_MGMT_TASKSTAT_STACK_INFO` is set (code that does it: https://github.com/zephyrproject-rtos/zephyr/blob/30cd0d4338601ffd39d8f5d1a992cb4f090ced6e/subsys/mgmt/mcumgr/lib/cmd/os_mgmt/src/os_mgmt.c#L108-L129)
