### ISSUE TITLE
USB: Add support for MS OS Descriptors

### ISSUE THREAD

**Issue by finikorg** [zephyrproject-rtos/zephyr#1582]
Add support for OS Descriptors mentioned here: https://msdn.microsoft.com/en-us/windows/hardware/gg463179

@jfischer-phytec-iot

**Comment by IvanSanchez** [comment]
See https://docs.microsoft.com/en-us/windows-hardware/drivers/usbcon/microsoft-defined-usb-descriptors also.

**Comment by finikorg** [comment]
Fixed through PR #7369
