### ISSUE TITLE
"#if XIP" block in qemu_x86 DTS always evaluates to false

### ISSUE THREAD

**Issue by andrewboie** [zephyrproject-rtos/zephyr#15835]
The intent here seems to be to properly set memory if CONFIG_XIP=y, but the qemu_x86 target does enable CONFIG_XIP, yet the amount of SRAM gets set to 8188K anyway.

Causes hard to debug runtime hangs if the amount of RAM used exceeds 4096, instead of failing at build time.

**Comment by galak** [comment]
Not sure how this snuck in, but we don't allow use of CONFIG_ ifdef's in dts anymore.

**Comment by nashif** [comment]
This is not a CONFIG_* and it was there for almost 2 years, without any effect basically. We do not define XIP anywhere AFAIK

```
#if XIP
        #define DT_SRAM_SIZE            DT_SIZE_K(4096)
#else
        #define DT_SRAM_SIZE            DT_SIZE_K(8188)
#endif
```
