### ISSUE TITLE
concerns with use of CONFIG_BT_MESH_RPL_STORE_TIMEOUT in examples

### ISSUE THREAD

**Issue by pabigot** [zephyrproject-rtos/zephyr#15904]
[CONFIG_BT_MESH_RPL_STORE_TIMEOUT](https://docs.zephyrproject.org/latest/reference/kconfig/CONFIG_BT_MESH_RPL_STORE_TIMEOUT.html) is used in multiple examples with values like 120 or 600, and its documentation suggests that this would reduce the frequency at which sequence numbers are persisted to flash.

In implementation, this option has an effect [only if it is strictly less](https://github.com/zephyrproject-rtos/zephyr/blob/735b287243115ce5595f43f812b5bd59f806472e/subsys/bluetooth/host/mesh/settings.c#L821) than [CONFIG_BT_MESH_STORE_TIMEOUT](https://docs.zephyrproject.org/latest/reference/kconfig/CONFIG_BT_MESH_STORE_TIMEOUT.html), which defaults to 2 seconds.

None of this is wrong, but the override of this symbol in the examples is misleading as it has no impact on behavior.  In particular it doesn't mitigate against exceeding the flash write/erase endurance in mesh nodes with roles that require local processing of a large number of messages, which would be a motivator for increasing the RPL store timeout.

**Comment by jhedberg** [comment]
There's a single k_delayed_work for performing pending storage actions, which is why the RPL timeout is not independent from the other one. IIRC the intention was to use the RPL timeout whenever only the RPL needs updating or if the RPL timeout is less than the global one. This was just never implemented properly. I'll prepare a PR to fix this, something along the lines of:
```
--- a/subsys/bluetooth/host/mesh/net.h
+++ b/subsys/bluetooth/host/mesh/net.h
@@ -200,7 +200,7 @@ enum {
        BT_MESH_IVU_TEST,        /* IV Update test mode */
        BT_MESH_IVU_PENDING,     /* Update blocked by SDU in progress */
 
-       /* pending storage actions */
+       /* pending storage actions, must reside within first 32 flags */
        BT_MESH_RPL_PENDING,
        BT_MESH_KEYS_PENDING,
        BT_MESH_NET_PENDING,
diff --git a/subsys/bluetooth/host/mesh/settings.c b/subsys/bluetooth/host/mesh/settings.c
index 412c8f05ec..643b1e6cfd 100644
--- a/subsys/bluetooth/host/mesh/settings.c
+++ b/subsys/bluetooth/host/mesh/settings.c
@@ -808,19 +808,29 @@ static int mesh_commit(void)
 
 BT_SETTINGS_DEFINE(mesh, mesh_set, mesh_commit, NULL);
 
+/* Pending flags that use K_NO_WAIT as the storage timeout */
+#define NO_WAIT_PENDING_BITS (BIT(BT_MESH_NET_PENDING) |           \
+                             BIT(BT_MESH_IV_PENDING) |            \
+                             BIT(BT_MESH_SEQ_PENDING))
+
+/* Pending flags that use CONFIG_BT_MESH_STORE_TIMEOUT */
+#define GENERIC_PENDING_BITS (BIT(BT_MESH_KEYS_PENDING) |          \
+                             BIT(BT_MESH_HB_PUB_PENDING) |        \
+                             BIT(BT_MESH_CFG_PENDING) |           \
+                             BIT(BT_MESH_MOD_PENDING))
+
 static void schedule_store(int flag)
 {
        s32_t timeout;
 
        atomic_set_bit(bt_mesh.flags, flag);
 
-       if (atomic_test_bit(bt_mesh.flags, BT_MESH_NET_PENDING) ||
-           atomic_test_bit(bt_mesh.flags, BT_MESH_IV_PENDING) ||
-           atomic_test_bit(bt_mesh.flags, BT_MESH_SEQ_PENDING)) {
+       if (atomic_get(bt_mesh.flags) & NO_WAIT_PENDING_BITS) {
                timeout = K_NO_WAIT;
        } else if (atomic_test_bit(bt_mesh.flags, BT_MESH_RPL_PENDING) &&
-                  (CONFIG_BT_MESH_RPL_STORE_TIMEOUT <
-                   CONFIG_BT_MESH_STORE_TIMEOUT)) {
+                  (!(atomic_get(bt_mesh.flags) & GENERIC_PENDING_BITS) ||
+                   (CONFIG_BT_MESH_RPL_STORE_TIMEOUT <
+                    CONFIG_BT_MESH_STORE_TIMEOUT))) {
                timeout = K_SECONDS(CONFIG_BT_MESH_RPL_STORE_TIMEOUT);
        } else {
                timeout = K_SECONDS(CONFIG_BT_MESH_STORE_TIMEOUT);
```
