### ISSUE TITLE
Documentation missing for SPI and ADC async operations

### ISSUE THREAD

**Issue by pabigot** [zephyrproject-rtos/zephyr#15903]
None of the user-visible SPI or ADC operations that end in `_async` appear in the [generated documentation](https://docs.zephyrproject.org/latest/reference/peripherals/spi.html) although there are [references](https://docs.zephyrproject.org/latest/reference/peripherals/spi.html#_CPPv310spi_api_io) to their existence.

(Also: in the second link above documentation comment for `spi_api_io_async` erroneously overrides its target with an incorrect `@typedef` annotation.)

**Comment by carlescufi** [comment]
This is fixed now, since the funcitons appear in the generated doc
