### ISSUE TITLE
Openthread - fault with dual network interfaces

### ISSUE THREAD

**Issue by acsplayon** [zephyrproject-rtos/zephyr#15975]
**Describe the bug**
Multiple network interfaces (ETHERNET and OPENTHREAD) cause hard fault in openthread network_management callback.

**To Reproduce**
1) You create 2 L2 network interfaces. ETHERNET and OPENTHREAD
2) I use USB cdc_ecm to interface to the ETHERNET iface.
3) no special configuration of openthread.
4) on init, openthread will install a net_mgmt callback which is located in openthread.c.

**Expected behavior**

**Impact**
Showstopper. System freezes/is unstable

**Screenshots or console output**
If applicable, add a screenshot (drag-and-drop an image), or console logs
(cut-and-paste text and put a code fence (\`\`\`) before and after, to help
explain the issue.

**Environment (please complete the following information):**
 - OS: Linux (ubuntu 16.04/18.04)
 - Toolchain Zephyr SDK
 - Commit - master

**Additional context**
ipv6_addr_event_hander at/near openthread.c:67 will be called by net management events for all net ifaces.  This event handler does no checking on whether the context returned by net_if_l2_data(iface) is a valid openthread_context and a hard fault will be issued eventually in a memcmp call.

I added a u32_t to the openthread context called ot_magic, and initialized it in openthread_init to hold a magic number/identifier.  Then, in ipv6_addr_even_handler, I check the returned data structure for both NULL and the magic number, and if either fail, skip the processing of the IPV6 address on the invalid openthread context.

**Comment by jukkar** [comment]
> I added a u32_t to the openthread context called ot_magic, and initialized it in openthread_init to hold a magic number/identifier. Then, in ipv6_addr_even_handler, I check the returned data structure for both NULL and the magic number, and if either fail, skip the processing of the IPV6 address on the invalid openthread context.

Could you send a PR if you have already a fix?

**Comment by rlubos** [comment]
@acsplayon I've reproduced the issue and submitted https://github.com/zephyrproject-rtos/zephyr/pull/17308 to fix it. Please review/verify.
