### ISSUE TITLE
Kernel tests assume SYS_CLOCK_TICKS_PER_SEC=100

### ISSUE THREAD

**Issue by carlescufi** [zephyrproject-rtos/zephyr#15983]
Merging https://github.com/zephyrproject-rtos/zephyr/pull/15707
and in particular this commit:
https://github.com/zephyrproject-rtos/zephyr/commit/c76dd1edb75001f853cfc0e23ed627f49889b2c6

Made the following tests start failing:

```
nrf52840_pca10056         tests/kernel/tickless/tickless_concept/kernel.tickless FAILED: failed
    see: sanity-out/nrf52840_pca10056/tests/kernel/tickless/tickless_concept/kernel.tickless/handler.log

total complete:    1/   3  33%  failed:    1

nrf52840_pca10056         tests/kernel/sched/schedule_api/kernel.sched       FAILED: failed
    see: sanity-out/nrf52840_pca10056/tests/kernel/sched/schedule_api/kernel.sched/handler.log

total complete:    2/   3  66%  failed:    2

nrf52840_pca10056         tests/kernel/timer/timer_api/kernel.timer          FAILED: failed
    see: sanity-out/nrf52840_pca10056/tests/kernel/timer/timer_api/kernel.timer/handler.log
```

**Comment by pabigot** [comment]
Those are all most likely problems with the tests, perhaps an assumption that the timer operates with a resolution that can exactly express multiples of 10 ms.  `tests/kernel/timer/timer_api/kernel.timer` in particular insists that the wakeup be at a 50 ms boundary, and that can't happen with 128 ticks-per-second: you can get 46.8 ms, or 54.6 ms, but not 50 ms.  (I see it get 55 ms, which is the right answer.)

`tests/kernel/sched/schedule_api/kernel.sched` seems to want a 100 ms timeslice, which it's not going to get (first pass it gets 101, which is the truncated value of 101.5625 = 13/128).
