### ISSUE TITLE
Could you give me BTP upper tester demo which can work on PC 

### ISSUE THREAD

**Issue by cobbler123** [zephyrproject-rtos/zephyr#1600]
Hi friends,
           I'm interested in BLE of Zephyr, I want to do some test for Zephyr BLE using Bluethooth tester.
But I don't find upper tester demo which can communicating with zepher tester(zephyr\tests\bluetooth\tester) through BTP protocol.
          Could you give me some upper tester demo which can work on PC ?

Thanks
shijun

**Comment by jhedberg** [comment]
There's tools/btpclient.c in BlueZ that you could use: https://git.kernel.org/pub/scm/bluetooth/bluez.git/tree/tools/btpclient.c
