### ISSUE TITLE
Source IP address for DHCP renewal messages is unset

### ISSUE THREAD

**Issue by pfl** [zephyrproject-rtos/zephyr#16012]
The source address in unicast DHCPv4 Request packets was found out
to be all zeros address 0.0.0.0. This address is only acceptable if
the destination is a multicast one, where the host in question is
acquiring a DHCP address lease. This is true for the DHCP Discover
and the initial DHCP Request message from the client towards the
server. As subsequent DHCP Request renewal messages are sent as
unicast to the server, the server will drop such packets. As Linux user space never sees the DHCP Request messages sent with source address 0.0.0.0. It will eventually work, as the Zephyr DHCP client restarts the address acquisition procedure with a DHCP Discover, but depending on the situation and DHCP servers involved, Zephyr might loose its address in between or get a new one assigned due to restarting of the DHCP procedure

**Comment by nashif** [comment]
fix is merged
