### ISSUE TITLE
Increase coverage of tests

### ISSUE THREAD

**Issue by nashif** [zephyrproject-rtos/zephyr#16011]
**Describe the bug**

When evaluating coverage data we notice some features in the core kernel is not be covered with any tests. 

**To Reproduce**

Run with coverage enable and look at reports of kernel and core OS services.

**Expected behavior**
Line and function coverage is or close to 100%.

**Impact**

We do not test everything, we might introduce bugs without being able to catch them.

**Comment by mbolivar** [comment]
Is this really a bug? It seems more like an enhancement, no?

**Comment by ioannisg** [comment]
Is this still a bug @nashif @andrewboie ? What is the definition-of-done, here?

**Comment by andrewboie** [comment]
The initial milestone is to get 100% function, 90% line coverage for kernel/ lib/os/ and related headers. We are currently treating this as a bug.

**Comment by MaureenHelm** [comment]
Low coverage is not a bug
