### ISSUE TITLE
webusb example app not reading data

### ISSUE THREAD

**Issue by Jconn** [zephyrproject-rtos/zephyr#16025]
**Describe the bug**
the webusb demo will connect but will not receive data from the sample webpage at https://github.com/finikorg/webusb-serial, with log message `<err> usb_device: RX data lost, no transfer`

**To Reproduce**

flash the webusb sample application located at samples/subsys/usb/webusb onto a pca10056 dk

launch local http server, clone https://github.com/finikorg/webusb-serial, and run index.html from localserver 

the web page is able to connect to the board fine, but fails to send anything.

The output from the debug console is. 

<err> usb_device: RX data lost, no transfer

I dug into this and realized `webusb_dev_status_cb()` is not being called. I was able to get hook that up to the usb stack and get reads partially working by replacing
`
	usb_register_status_callback(forward_status_cb);
	usb_dc_set_status_callback(forward_status_cb);
`
with 
`
       usb_register_status_callback(config->cb_usb_status);

	usb_dc_set_status_callback(config->cb_usb_status);
`
but that caused other problems.

forward_status_cb wasn't firing for me because `(__usb_data_end - __usb_data_start) == 0`

**Environment (please complete the following information):**

OS: Ubuntu 16.04 
Toolchain Zephyr-sdk-0.10.0
Commit SHA or Version used on zephyr: c2f08dadf0d6d687cc67a1f4043220637479af27

**Comment by finikorg** [comment]
I have PR which fixes (should) this issue #15818. 

`webusb-serial` also need this patch to work with recent USB product ID: https://github.com/finikorg/webusb-serial/commit/d31113e00c788eef07e37bbce20baa3c9e2e7134
