### ISSUE TITLE
Support for "split-lock" alignment check exceptions.

### ISSUE THREAD

**Issue by ghost** [zephyrproject-rtos/zephyr#16051]
Intel have added a new feature which will raise an alignment check exception when an instruction attempts a LOCKed memory access that spans cache lines, a.k.a. a "split lock":

https://lkml.org/lkml/2019/4/3/1137

Under Zephyr, it might be useful to allow enabling these exceptions as a diagnostic tool, because they will catch accesses with detrimental impact on real-time performance.  At a minimum, Zephyr should be prepared to handle alignment exceptions gracefully: if running as a hypervisor guest, the hypervisor may enable these exceptions and pass them through to Zephyr without consent.

**Comment by nashif** [comment]
original submitter does not exist anymore, no way to get any further input, closing.
