### ISSUE TITLE
Detect first block in LWM2M firmware updates.

### ISSUE THREAD

**Issue by sunkyl** [zephyrproject-rtos/zephyr#16122]
Problem
Currently, there is no way to detect when to reset the context of a firmware update via LWM2M when the process is interrupted outside of the block received callback (say in the case of a timeout).

Solution
Some indication of a first block for the callback, or exposing more functions within the LWM2M library that allows for writing our own callbacks that can start the transfer. 

Alternatives
Currently, there is the extern function inside the subsystem LWM2M files `lwm2m_firmware_start_transfer()` that I can use. I can create a semi-functional imitation of the sample post-write callback for the package URI that resets a variable to indicate a context reset, but it also has no access to the functions to change the update state. 

Thanks.

**Comment by mike-scott** [comment]
@sunkyl Did you want to submit your changes as a PR so we can discuss there while looking at code?

**Comment by yaomon** [comment]
Sorry, switching accounts here.
https://github.com/zephyrproject-rtos/zephyr/pull/16369
I think this is the simplest way. I had briefly considered hijacking the instance id parameter in the write callback to pass 1/0 based on whether the current block size is 0 (indicating the first block) but that is very inelegant.
Given access to the block context, I can check whether the current size is <= coap block size to check for the first block and reset the flash context accordingly.

Thanks.

**Comment by carlescufi** [comment]
@yaomon could you please submit a new PR?
cc @rlubos
