### ISSUE TITLE
posix: CONFIG_POSIX_API and CONFIG_NET_SOCKETS_POSIX_NAMES don't make sense to use together, and conflict when doing so

### ISSUE THREAD

**Issue by pfalcon** [zephyrproject-rtos/zephyr#16141]
As discussed in https://github.com/zephyrproject-rtos/zephyr/pull/16009 .

The meaning of CONFIG_SOCKETS_POSIX_NAMES is "expose Zephyr's namespaced socket API under standard POSIX names".

The meaning of CONFIG_POSIX_API is "expose all POSIX APIs which are available in Zephyr".

From this description, it's clear that these 2 options shouldn't be used together, as CONFIG_POSIX_API has wider scope which subsumes and supersedes meaning of CONFIG_SOCKETS_POSIX_NAMES. 

However, implementation-wise, these 2 options are implemented differently, so if someone by mistake enabled them, that can lead to compile-time errors (whose reason may be not immediately clear.

Consequently, we should:

* Either make these 2 options conflict, with explicit error message describing the above, or
* Make CONFIG_POSIX_API silently subsume CONFIG_SOCKETS_POSIX_NAMES.

**Comment by carlescufi** [comment]
Relabeling as enhancement since this is about the meaning of Kconfig options.

**Comment by pfalcon** [comment]
> Relabeling as enhancement since this is about the meaning of Kconfig options.

Interesting, then why @nashif blocks a legitimate pull request https://github.com/zephyrproject-rtos/zephyr/pull/16009 , based on this unrelated enhancement?
