### ISSUE TITLE
posix: clock_settime calculates the base time incorrectly

### ISSUE THREAD

**Issue by alexanderendian** [zephyrproject-rtos/zephyr#16143]
If you call `clock_settime` twice with the same non-zero value appears to reset the clock back to 0. I've that disovered that it's caused by `clock_settime` performing its internal calculation incorrectly when updating the clock base. I have submitted a pull request which contains some further explanation and a fix #16040.

**To Reproduce**

1. Build and run the following program in QEMU (although it should affect any target). _Disclaimer: I don't have a development environment nearby to test it, so it may contain a typo._
```C
#include <zephyr.h>
#include <posix/time.h>
#include <misc/printk.h>

void main(void)
{
	struct timespec target;
	struct timespec actual;

	target.tv_sec = 1000000;
	target.tv_nsec = 0;

	printk("clock_settime to %d\n", target->tv_sec);
	clock_settime(CLOCK_REALTIME, &target);
	clock_gettime(CLOCK_REALTIME, &actual);
	printk("clock_gettime returned %d\n", actual->tv_sec);

	printk("clock_settime to %d\n", target->tv_sec);
	clock_settime(CLOCK_REALTIME, &target);
	clock_gettime(CLOCK_REALTIME, &actual);
	printk("clock_gettime returned %d\n", actual->tv_sec);
}
```
2. Observe that the last printed line shows a time close to 0 when something close to the target of 1000000 is expected.

**Comment by galak** [comment]
@alexanderendian thanks for submitting this issue.

**Comment by jbrzozoski** [comment]
I *just* bumped into this, too.  Fix is just to use CLOCK_MONOTONIC when getting the base reference inside clock_settime.
