### ISSUE TITLE
Remove the LWM2M maximum number of instances limitation

### ISSUE THREAD

**Issue by lodup29** [zephyrproject-rtos/zephyr#16156]
LWM2M [IPSO objects are currently limited to 20 instances](https://github.com/zephyrproject-rtos/zephyr/blob/master/subsys/net/lib/lwm2m/Kconfig.ipso) :
- LWM2M_IPSO_TEMP_SENSOR_INSTANCE_COUNT
- LWM2M_IPSO_LIGHT_CONTROL_INSTANCE_COUNT
- LWM2M_IPSO_TIMER_INSTANCE_COUNT

However this limitation only appears to be self applied through kconfig and doesn't seem to be related to a limitation within the C implementation.

I feel like it should be up to the programmer to set the limit (instance count is the limit itself, it's like putting a limit on a limit) and an upper range should not be specified though kconfig

**Comment by mike-scott** [comment]
@lodup29 Agreed.  Feel free to submit a PR removing the upper range in the Kconfig files.
