### ISSUE TITLE
STM32: Could not compile with CONFIG_PINMUX=n

### ISSUE THREAD

**Issue by erwango** [zephyrproject-rtos/zephyr#16177]
**Describe the bug**
STM32 targets won't compile with CONFIG_PINMUX=n.

**To Reproduce**
1. cd samples/basic/minimal
2. west build -b nucleo_f334r8 -- -DOVERLAY_CONFIG="common.conf no-mt.conf no-timers.conf arm.conf"
3. See error

**Expected behavior**
Compilation ok

**Impact**
Minimal build ko

**Screenshots or console output**
```
/local/mcu/zephyr-sdk-0.10.0/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/8.3.0/../../../../arm-zephyr-eabi/bin/ld: Undefined initialization levels used.
/local/mcu/zephyr-sdk-0.10.0/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/8.3.0/../../../../arm-zephyr-eabi/bin/ld: zephyr/boards/arm/nucleo_f334r8/libboards__arm__nucleo_f334r8.a(pinmux.c.obj): in function `pinmux_stm32_init':
/local/mcu/zephyr/zephyr-project/boards/arm/nucleo_f334r8/pinmux.c:48: undefined reference to `stm32_setup_pins'
collect2: error: ld returned 1 exit status
```

**Environment (please complete the following information):**
 - OS: Ubuntu16.04
 - Toolchain (e.g Zephyr SDK, ...)
 - Commit SHA or Version used

**Additional context**
Could be solved with following patch in each stm32 board CMakeLists.txt
```
+ if(CONFIG_PINMUX)
   zephyr_library()
   zephyr_library_sources(pinmux.c)
   zephyr_library_include_directories(${ZEPHYR_BASE}/drivers)
+ endif()
```

**Comment by carlescufi** [comment]
I actually hit this yesterday! I was writing a minimal sample (`samples/basic/minimal`) and that did not work with ST boards because it disables PINMUX

**Comment by erwango** [comment]
> I actually hit this yesterday! I was writing a minimal sample (samples/basic/minimal) and that did not work with ST boards because it disables PINMUX

:-), I hit this when testing your minimal sample this morning
