### ISSUE TITLE
Compile error using entropy.h in C++ code

### ISSUE THREAD

**Issue by bbolen** [zephyrproject-rtos/zephyr#16185]
When compiling a C++ application that includes entropy.h, the compiler generates the following error:

include/misc/util.h:53:1: error: template with C linkage
template < class T, size_t N >

This is a result of a couple of include directives within the C linkage wrapper in entropy.h

A fix has been submitted to #16183

**Comment by galak** [comment]
thanks for submitting this bug.

**Comment by nashif** [comment]
fixed in #16183
