### ISSUE TITLE
display_mcux_elcdif driver full support frame buffer features

### ISSUE THREAD

**Issue by hakehuang** [zephyrproject-rtos/zephyr#16196]
when I enable the samples/display cases for RT1050 boards ( patch can be found https://github.com/hakehuang/zephyr/commit/986880ba138e6c8f9e88634fdd239b25d7aa19ac) 
there are many frame buffer functions that are required by cfb/cfb_customer_font/cfb_shell samples

propose to add framebuffer function support for elcd driver.
below framebuffer APIs are better to have

```
display_set_pixel_format:
mcux_elcdif_get_framebuffer:
mcux_elcdif_get_capabilities:
```

**Comment by hakehuang** [comment]
@MaureenHelm

**Comment by jfischer-phytec-iot** [comment]
cfb is designed for the monochrome displays, there are other things i would like to improve, support for rgb pannels has low priority.

**Comment by hakehuang** [comment]
in this case, do we have any plan to add a general framebuffer support?

**Comment by carlescufi** [comment]
@vanwinkeljan @jfischer-phytec-iot is this still relevant?

**Comment by vanwinkeljan** [comment]
I don't think so cfb is mainly targeting monochrome displays and mcux elcdif can use lvgl.
