### ISSUE TITLE
tests/kernel/msgq/msgq_api twr_ke18f fails with assert

### ISSUE THREAD

**Issue by hakehuang** [zephyrproject-rtos/zephyr#16225]
**Describe the bug**
assert failure

**To Reproduce**
1. mkdir build; cd build
2. cmake -DBOARD=twr_ke18f ..
3. make

**Expected behavior**
PASS

**Impact**
message queue issue

**Screenshots or console output**
```
***** Booting Zephyr OS 1.14.99 *****
ASSERTION FAIL [num_parts <= max_partitions] @ ./kernel/mem_domain.c:90
***** Kernel Panic! *****
Current thread ID = 0x2000070c
Faulting instruction address = 0xa154
```
**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain Zephyr SDK
 - Commit SHA: c8708d9

**Comment by hakehuang** [comment]
@MaureenHelm

**Comment by hakehuang** [comment]
tests/kernel/semaphore/sema_api
tests/kernel/semaphore/semaphore
tests/kernel/timer/timer_api
tests/kernel/workq/work_queue_api/
has the same failure

**Comment by henrikbrixandersen** [comment]
These all fail due to the combination of limited number of MPU regions in the KE1xF SoC series and userspace, see the full explanation in #16229.
