### ISSUE TITLE
Add CONFIG_UART_DYNAMIC_SETTINGS option

### ISSUE THREAD

**Issue by erwango** [zephyrproject-rtos/zephyr#16231]
**Is your enhancement proposal related to a problem? Please describe.**
Add an option to disable dynamic settings in uart.h (uart_configure, and uart_configure_get).
This saves around 500 bytes of flash per UART device (seen on STM32)

**Describe the solution you'd like**
Add a config UART_DYNAMIC_SETTINGS which would be conditional for uart settings related apis:
 - uart_configure
 - uart_configure_get
When disabled, they would not be available, and settings values would be the ones set at startup either from device tree or HW default values.

Default choice for this new value could be either n or y.
I'd propose n.

**Comment by erwango** [comment]
@dcpleung I'm adding you as assignee. Feel free to close if you think this is not something we want.

**Comment by dcpleung** [comment]
Maybe something more like `CONFIG_UART_SUPPORT_RUNTIME_CONFIGURE`? I just looked at a couple drivers and they call configure() during init(), and `uart_apbuart` doesn't configure the port during init (... possibly relying on runtime config). So I think in general this doesn't save us much in code size on other platforms.

Is it something you can do in the STM32 driver? If you set `.configure` and `.config_get` to null in API struct, and ifdef the functions, it would archive some code saving. Calling to API would simply return -ENOTSUP in this case.
