### ISSUE TITLE
Add 32K RAM support for nRF51822 REVC/microbit board

### ISSUE THREAD

**Issue by david-foo** [zephyrproject-rtos/zephyr#16268]
I'm using microbit board for bluetooth mesh estimate. But the 16K RAM is not enough, so I replace the chip wich a 32K one. The question si how to let the build system to adapt to the 32K memory map? I mean how to change the microbit board info from 16K to 32K in a direct way.

**Comment by carlescufi** [comment]
You need to change this line:
https://github.com/zephyrproject-rtos/zephyr/blob/master/boards/arm/bbc_microbit/bbc_microbit.dts#L8

So it points to this file instead:
https://github.com/zephyrproject-rtos/zephyr/blob/master/dts/arm/nordic/nrf51822_qfac.dtsi

**Comment by david-foo** [comment]
@carlescufi  Thank you. It works.
