### ISSUE TITLE
doc: networking: overview has out of date info for LwM2M

### ISSUE THREAD

**Issue by mike-scott** [zephyrproject-rtos/zephyr#16327]
**Describe the bug**
The networking overview page: https://docs.zephyrproject.org/latest/guides/networking/overview.html states that LwM2M doesn't support DTLS or Bootstrap mode.  This was added a while back and doesn't match with the rest of the docs.

**To Reproduce**
View: https://docs.zephyrproject.org/latest/guides/networking/overview.html

**Expected behavior**
LwM2M documentation should match throughout the docs.

**Impact**
Developers are getting misinformation and possibly avoiding Zephyr use.

**Comment by ioannisg** [comment]
Are you going to address this for 2.0 @mike-scott ?

**Comment by mike-scott** [comment]
Wow.. this totally feel off my plate.  Let me look.
