### ISSUE TITLE
Bluetooth: GATT Server failed to send Service Change Indication

### ISSUE THREAD

**Issue by tedd-an** [zephyrproject-rtos/zephyr#16341]
**Describe the bug**
GATT server failed to send Service Change Indication.
Ref: PTS GATT/SR/GAS/BV-01-C

**To Reproduce**
This was tested with PTS (Bluetooth SIG testing tool)

**Expected behavior**
GATT Server (IUT) should send Service Change indication to the client.

**Impact**
Test fail

**Environment (please complete the following information):**
Using AutoPTS on Linux
HW: reel_board

**Comment by jhedberg** [comment]
Is this a recent regression, or something that's been there for a longer time? Should the fix be back ported to LTS?

**Comment by tedd-an** [comment]
Hi @jhedberg 
> Is this a recent regression, or something that's been there for a longer time? Should the fix be back ported to LTS?

The issue was introduced with e0f3ab6 and it was a part of regression list. But we missed it I guess. 
It doesn't need to be backported.
