### ISSUE TITLE
net: ipv6: Zephyr does not reply to fragmented packet

### ISSUE THREAD

**Issue by rmstoi** [zephyrproject-rtos/zephyr#16354]
Zephyr receives fragmented packet, but does not reply. The same test is done with Linux DUT and it successfully replies to fragmented echo request.

[ipv6-frag-zephyr.pcap.gz](https://github.com/zephyrproject-rtos/zephyr/files/3212117/ipv6-frag-zephyr.pcap.gz)
[ipv6-frag-linux.pcap.gz](https://github.com/zephyrproject-rtos/zephyr/files/3212119/ipv6-frag-linux.pcap.gz)

**Comment by ioannisg** [comment]
Is this issue being looked at, @jukkar ?

**Comment by jukkar** [comment]
It was forgotten, but I will start to look it now.
