### ISSUE TITLE
Build error on QEMU x86 and quark_se_c1000_devboard

### ISSUE THREAD

**Issue by yerabolu** [zephyrproject-rtos/zephyr#16366]
**Describe the bug**
Not able to build Zephyr successfully.

**To Reproduce**
1. mkdir build; cd build
2. cmake -DBOARD=board\qemu_x86  or quark_se_c1000_devboard
3. make

**Expected behavior**
Successful build 

**Impact**
Not able to run any tests on QEMU and Quark_SE_c1000_devboard.

**Screenshots or console output**
              @local                    will run on target group 'target=/qc10000-05:x86'
C          @local                    NOTE: this testcase will unfold subcases: thread_flags_signalled thread_prio_dynamic thread_flags_no_wait_timeout event_flags_isr event_flags_signalled kernel_apis messageq event_flags_no_wait_timeout thread_flags_isr delay mutex thread_detached semaphore thread_apis_dynamic mempool_dynamic mempool thread_join thread_prio thread_joinable_detach timer mutex_lock_timeout thread_joinable_terminate thread_apis
Che5d      @/qc10000-05      enabled Zephyr config file 500_boot_config.conf at /home/jenkins/workspace/zephyr-master-ci-master/tmp/tcf.run-rEM0Qh/7crj/outdir-7crj-u5zf-quark_se_c1000_devboard
Che5d      @/qc10000-05      config file: # Introduce a boot delay of 1s to make sure the system
Che5d      @/qc10000-05      config file: # has had time to setup the serial ports and start recording
Che5d      @/qc10000-05      config file: # from them
Che5d      @/qc10000-05      config file: CONFIG_BOOT_BANNER=y
Che5d      @/qc10000-05      config file: CONFIG_BOOT_DELAY=1000
Che5d      @/qc10000-05/arc  enabled Zephyr config file 500_boot_config.conf at /home/jenkins/workspace/zephyr-master-ci-master/tmp/tcf.run-rEM0Qh/7crj/outdir-7crj-u5zf-quark_se_c1000_ss_devboard
Che5d      @/qc10000-05/arc  config file: # Stubs be quiet and don't delay, ready ASAP
Che5d      @/qc10000-05/arc  config file: CONFIG_BOOT_BANNER=n
Che5d      @/qc10000-05/arc  config file: CONFIG_BOOT_DELAY=0
           @local                    configure passed
Brwzl      @/qc10000-05      build passed: 'mkdir -p /home/jenkins/workspace/zephyr-master-ci-master/tmp/tcf.run-rEM0Qh/7crj/outdir-7crj-u5zf-quark_se_c1000_devboard; rm -f /home/jenkins/workspace/zephyr-master-ci-master/tmp/tcf.run-rEM0Qh/7crj/outdir-7crj-u5zf-quark_se_c1000_devboard/.config' @/home/jenkins/workspace/zephyr-master-ci-master/tcf.git/tcfl/app_zephyr.py:252
Brwzl      @/qc10000-05      enabled Zephyr config file 500_bsp_arc_off.conf at /home/jenkins/workspace/zephyr-master-ci-master/tmp/tcf.run-rEM0Qh/7crj/outdir-7crj-u5zf-quark_se_c1000_devboard
Brwzl      @/qc10000-05      config file: CONFIG_ARC_INIT=n
B          @local                    build errored: exit code 1 from 'cmake -DBOARD=quark_se_c1000_devboard -DARCH=x86 -DEXTRA_CPPFLAGS="-DTC_RUNID=ci-190523-0736-827:u5zf" -DEXTRA_CFLAGS="-Werror -Wno-error=deprecated-declarations" -DEXTRA_AFLAGS=-Wa,--fatal-warnings -DEXTRA_LDFLAGS=-Wl,--fatal-warnings  -B"/home/jenkins/workspace/zephyr-master-ci-master/tmp/tcf.run-rEM0Qh/7crj/outdir-7crj-u5zf-quark_se_c1000_devboard" -H"/home/jenkins/workspace/zephyr-master-ci-master/zephyr.git/tests/cmsis_rtos_v2"' @/home/jenkins/workspace/zephyr-master-ci-master/tcf.git/tcfl/app_zephyr.py:301
B          @local                    build errored trace: Traceback (most recent call last):
B          @local                    build errored trace:   File "/home/jenkins/workspace/zephyr-master-ci-master/tcf.git/tcfl/tc.py", line 1962, in _decorated_fn
B          @local                    build errored trace:     r = fn(*args, **kwargs)
B          @local                    build errored trace:   File "/home/jenkins/workspace/zephyr-master-ci-master/tcf.git/tcfl/tc.py", line 3864, in _methods_call
B          @local                    build errored trace:     self._build_serial, self._build_parallel)
B          @local                    build errored trace:   File "/home/jenkins/workspace/zephyr-master-ci-master/tcf.git/tcfl/tc.py", line 3771, in __method_trampoline_thread
B          @local                    build errored trace:     self.__method_trampoline_call(fname, fn, _type, targets),
B          @local                    build errored trace:   File "/home/jenkins/workspace/zephyr-master-ci-master/tcf.git/tcfl/tc.py", line 3728, in __method_trampoline_call
B          @local                    build errored trace:     r = getattr(self, fname)(self, *targets)
B          @local                    build errored trace:   File "/home/jenkins/workspace/zephyr-master-ci-master/tcf.git/tcfl/tc.py:2209|/home/jenkins/workspace/zephyr-master-ci-master/tcf.git/tcfl/tc.py:2111", line 2, in __tc_zephyr_sanity_c_build_50_for_target
B          @local                    build errored trace:   File "/home/jenkins/workspace/zephyr-master-ci-master/tcf.git/tcfl/tc.py", line 3261, in _build_50_for_target
B          @local                    build errored trace:     app.build(_app, self, _target, app_src)
B          @local                    build errored trace:   File "/home/jenkins/workspace/zephyr-master-ci-master/tcf.git/tcfl/app.py", line 203, in build
B          @local                    build errored trace:     ab.build(testcase, target, app_src)
B          @local                    build errored trace:   File "/home/jenkins/workspace/zephyr-master-ci-master/tcf.git/tcfl/app_zephyr.py", line 301, in build
B          @local                    build errored trace:     'cmake'
B          @local                    build errored trace:   File "/home/jenkins/workspace/zephyr-master-ci-master/tcf.git/tcfl/tc.py", line 1038, in shcmd_local
B          @local                    build errored trace:     reporter = self, logfile = logfile)
B          @local                    build errored trace:   File "/home/jenkins/workspace/zephyr-master-ci-master/tcf.git/tcfl/tc.py", line 3952, in _shcmd_local
B          @local                    build errored trace:     { output_tag: logf, "alevel": 0})
B          @local                    build errored trace: error_e: (u'exit code 1 from \'cmake -DBOARD=quark_se_c1000_devboard -DARCH=x86 -DEXTRA_CPPFLAGS="-DTC_RUNID=ci-190523-0736-827:u5zf" -DEXTRA_CFLAGS="-Werror -Wno-error=deprecated-declarations" -DEXTRA_AFLAGS=-Wa,--fatal-warnings -DEXTRA_LDFLAGS=-Wl,--fatal-warnings  -B"/home/jenkins/workspace/zephyr-master-ci-master/tmp/tcf.run-rEM0Qh/7crj/outdir-7crj-u5zf-quark_se_c1000_devboard" -H"/home/jenkins/workspace/zephyr-master-ci-master/zephyr.git/tests/cmsis_rtos_v2"\' @/home/jenkins/workspace/zephyr-master-ci-master/tcf.git/tcfl/app_zephyr.py:301', {'build output': <open file '<fdopen>', mode 'w+b' at 0x7f4ced16a930>, 'alevel': 0})
B          @local                    build output: Zephyr version: 1.14.99
B          @local                    build output: -- Found PythonInterp: /usr/bin/python3 (found suitable version "3.7.0", minimum required is "3.4")
B          @local                    build output: -- Selected BOARD quark_se_c1000_devboard
B          @local                    build output: -- Loading /home/jenkins/workspace/zephyr-master-ci-master/zephyr.git/boards/x86/quark_se_c1000_devboard/quark_se_c1000_devboard.dts as base
B          @local                    build output: -- Overlaying /home/jenkins/workspace/zephyr-master-ci-master/zephyr.git/dts/common/common.dts
B          @local                    build output: quark_se_c1000_devboard.dts.pre.tmp:89.23-92.5: Warning (simple_bus_reg): /soc/virtualcom: missing or empty reg/ranges property
B          @local                    build output: Parsing Kconfig tree in /home/jenkins/workspace/zephyr-master-ci-master/zephyr.git/Kconfig
B          @local                    build output: Loading /home/jenkins/workspace/zephyr-master-ci-master/zephyr.git/boards/x86/quark_se_c1000_devboard/quark_se_c1000_devboard_defconfig as base
B          @local                    build output: Merging /home/jenkins/workspace/zephyr-master-ci-master/zephyr.git/tests/cmsis_rtos_v2/prj.conf
B          @local                    build output: Merging /home/jenkins/workspace/zephyr-master-ci-master/tmp/tcf.run-rEM0Qh/7crj/outdir-7crj-u5zf-quark_se_c1000_devboard/500_boot_config.conf
B          @local                    build output: Merging /home/jenkins/workspace/zephyr-master-ci-master/tmp/tcf.run-rEM0Qh/7crj/outdir-7crj-u5zf-quark_se_c1000_devboard/500_bsp_arc_off.conf
B          @local                    build output:
B          @local                    build output: warning: MAX_THREAD_BYTES (defined at arch/Kconfig:212) was assigned the value '4' but got the value
B          @local                    build output: ''. You can check symbol information (including dependencies) in the 'menuconfig' interface (see the
B          @local                    build output: Application Development Primer section of the manual), or in the Kconfig reference at
B          @local                    build output: http://docs.zephyrproject.org/latest/reference/kconfig/CONFIG_MAX_THREAD_BYTES.html (which is
B          @local                    build output: updated regularly from the master branch). See the 'Setting configuration values' section of the
B          @local                    build output: Board Porting Guide as well.
B          @local                    build output:
B          @local                    build output: warning: BOOT_BANNER (defined at kernel/Kconfig:313) was assigned the value 'y' but got the value
B          @local                    build output: 'n'. You can check symbol information (including dependencies) in the 'menuconfig' interface (see
B          @local                    build output: the Application Development Primer section of the manual), or in the Kconfig reference at
B          @local                    build output: http://docs.zephyrproject.org/latest/reference/kconfig/CONFIG_BOOT_BANNER.html (which is updated
B          @local                    build output: regularly from the master branch). See the 'Setting configuration values' section of the Board
B          @local                    build output: Porting Guide as well.
B          @local                    build output:
B          @local                    build output: warning: UART_CONSOLE (defined at drivers/console/Kconfig:46) was assigned the value 'y' but got the
B          @local                    build output: value 'n'. You can check symbol information (including dependencies) in the 'menuconfig' interface
B          @local                    build output: (see the Application Development Primer section of the manual), or in the Kconfig reference at
B          @local                    build output: http://docs.zephyrproject.org/latest/reference/kconfig/CONFIG_UART_CONSOLE.html (which is updated
B          @local                    build output: regularly from the master branch). See the 'Setting configuration values' section of the Board
B          @local                    build output: Porting Guide as well.
B          @local                    build output:
B          @local                    build output: warning: UART_QMSI (defined at drivers/serial/Kconfig.qmsi:3) was assigned the value 'y' but got the
B          @local                    build output: value 'n'. You can check symbol information (including dependencies) in the 'menuconfig' interface
B          @local                    build output: (see the Application Development Primer section of the manual), or in the Kconfig reference at
B          @local                    build output: http://docs.zephyrproject.org/latest/reference/kconfig/CONFIG_UART_QMSI.html (which is updated
B          @local                    build output: regularly from the master branch). See the 'Setting configuration values' section of the Board
B          @local                    build output: Porting Guide as well.
B          @local                    build output:
B          @local                    build output: warning: QMSI (defined at soc/x86/intel_quark/quark_d2000/Kconfig.defconfig.series:33, soc/x86/intel_quark/quark_se/Kconfig.defconfig.series:30) defined without a type
B          @local                    build output:
B          @local                    build output: warning: HAS_SPI_DW (defined at drivers/spi/Kconfig.dw:9) has direct dependencies SPI with value n, but is currently being y-selected by the following symbols:
B          @local                    build output:  - SOC_QUARK_SE_C1000 (defined at soc/x86/intel_quark/quark_se/Kconfig.soc:9), with value y, direct dependencies <choice> (value: y), and select condition <choice> (value: y)
B          @local                    build output:
B          @local                    build output: Error: Aborting due to non-whitelisted Kconfig warning 'warning: QMSI (defined at
B          @local                    build output: soc/x86/intel_quark/quark_d2000/Kconfig.defconfig.series:33,
B          @local                    build output: soc/x86/intel_quark/quark_se/Kconfig.defconfig.series:30) defined without a type'. Note: If this
B          @local                    build output: warning doesn't point to an actual problem, you can add it to the whitelist at the top of
B          @local                    build output: /home/jenkins/workspace/zephyr-master-ci-master/zephyr.git/scripts/kconfig/kconfig.py.
B          @local                    build output:
B          @local                    build output: CMake Error at /home/jenkins/workspace/zephyr-master-ci-master/zephyr.git/cmake/kconfig.cmake:195 (message):
B          @local                    build output:   command failed with return code: 1
B          @local                    build output: Call Stack (most recent call first):
B          @local                    build output:   /home/jenkins/workspace/zephyr-master-ci-master/zephyr.git/cmake/app/boilerplate.cmake:434 (include)
B          @local                    build output:   CMakeLists.txt:4 (include)
B          @local                    build output:
B          @local                    build output:
B          @local                    build output: -- Configuring incomplete, errors occurred!
           @local                    build errored

**Environment (please complete the following information):**
 - OS: (e.g. Linux, MacOS, Windows) - Fedora
 - Toolchain (e.g Zephyr SDK, ...) - 
 - Commit ID: 3e166d9631d5ebe96e72f35b2aac320db2d92c9d

**Additional context**

**Comment by nashif** [comment]
@yerabolu not a bug, looks like west is not being used to fetch dependencies and modules here. (QMSI)

In the future please do not submit raw logs from TCF, this is confusing and very difficult to read. Reproduce locally and submit the build errors if any from a local build, not TCF.
