### ISSUE TITLE
net: ipv4: udp: Zephyr does not reply to a valid datagram with checksum zero

### ISSUE THREAD

**Issue by rmstoi** [zephyrproject-rtos/zephyr#16375]
If Zephyr receives datagram with valid UDP checksum zero, it does not reply and drops the packet. Instead, a reply to this packet must be sent. Attached also Linux pcap for this case.

[udp-checksum-zero-linux.pcap.gz](https://github.com/zephyrproject-rtos/zephyr/files/3216312/udp-checksum-zero-linux.pcap.gz)
[udp-checksum-zero-zephyr.pcap.gz](https://github.com/zephyrproject-rtos/zephyr/files/3216313/udp-checksum-zero-zephyr.pcap.gz)

**Comment by tbursztyka** [comment]
A checksum field full of zeros in not a valid checksum. It means "no checksum".
See RFC 768 

> An all zero  transmitted checksum  value means that the transmitter  generated  no checksum  (for debugging or for higher level protocols that don't care).

So I guess if that field is full of 0s we should not check it at all.

**Comment by jukkar** [comment]
> So I guess if that field is full of 0s we should not check it at all.

That is probably the proper thing to do. I just wonder if this behavior should be configurable via Kconfig option.

**Comment by tbursztyka** [comment]
Good question indeed.
