### ISSUE TITLE
net: ipv6: udp: Zephyr replies with illegal UDP checksum zero

### ISSUE THREAD

**Issue by rmstoi** [zephyrproject-rtos/zephyr#16379]
If Zephyr receives IPv6 UDP datagram with valid UDP checksum 0xffff, it replies with IPv6/UDP having illegal checksum zero. Zephyr replies correctly to the same UDP datagram in IPv4. Attached also Linux pcap for this case.

[zephyr-udpv4-checksum-good.gz](https://github.com/zephyrproject-rtos/zephyr/files/3216825/zephyr-udpv4-checksum-good.gz)
[zephyr-udpv6-checksum-bad.gz](https://github.com/zephyrproject-rtos/zephyr/files/3216826/zephyr-udpv6-checksum-bad.gz)
[linux-udpv6-checksum-good.gz](https://github.com/zephyrproject-rtos/zephyr/files/3216827/linux-udpv6-checksum-good.gz)

**Comment by rmstoi** [comment]
[linux-udpv4-checksum-good.gz](https://github.com/zephyrproject-rtos/zephyr/files/3216866/linux-udpv4-checksum-good.gz)

**Comment by rmstoi** [comment]
It seems that Linux sets the checksums in both cases, IPv4 and IPv6, to 0xffff_

**Comment by tbursztyka** [comment]
In this case as well as in #16375, I think it is the same root cause in UDP side.
