### ISSUE TITLE
drivers: ethernet: stm32, sam, mcux: LAA bit not set

### ISSUE THREAD

**Issue by alexanderwachter** [zephyrproject-rtos/zephyr#16452]
**Describe the bug**
Random generated MAC addresses flip the wrong bit for LAA.
The LAA bit is the second bit in the first OUI byte, not the last byte in the NIC specific part.
Generally all assigned addresses should have the LAA bit set when using the vendo's OUI not only random generated.

**Impact**
MAC address looks like it is UAA address but is LAA.

**Comment by pfalcon** [comment]
@alexanderwachter: Can you please update the title of this ticket to correspond to the bug reported?

**Comment by ioannisg** [comment]
@pfalcon is this issue being looked at?
I am checking if this could be done for 2.0.

**Comment by pfalcon** [comment]
I don't look into this so far. Is this issue breaking something? I didn't notice Ethernet not working due to addresses being assigned. If so, I'd suggest to set priority as low.

**Comment by alexanderwachter** [comment]
@pfalcon No, it does not break anything. It just violates the IANA specifications.
Assumed I'm not wrong here and the actual implementation is correct.

**Comment by alexanderwachter** [comment]
@pfalcon If you can confirm that the actual implementation is wrong, I can fix the drivers. But IMO the priority is low.

**Comment by pfalcon** [comment]
> But IMO the priority is low.

Thanks for confirming. 3 days before release, there're bigger priorities to look into, and I have backlog of tasks otherwise, but we'll get to this issue too of course.
