### ISSUE TITLE
tests/subsys/settings/fcb_init fails on second run

### ISSUE THREAD

**Issue by hakehuang** [zephyrproject-rtos/zephyr#16463]
**Describe the bug**
build the tests/subsys/settings/fcb_init application, run and test_init fails

**To Reproduce**
1. mkdir build; cd build
2. cmake -DBOARD=twr_ke18f ..
3. make

**Expected behavior**
the setting_fcb test can PASS

**Impact**
settings fcb can not work

**Screenshots or console output**
```
***** Booting Zephyr OS 1.14.99 *****

Running test suite test_initialization

===================================================================

starting test - test_init



    Assertion failed at ./tests/subsys/settings/fcb_init/src/settings_test_fcb_init.c:61: test_init: (prev_int not equal to val32)

load value doesn't match to what was saved

FAIL - test_init

===================================================================

Test suite test_initialization failed.

===================================================================

PROJECT EXECUTION FAILED

```

**Environment (please complete the following information):**
 - OS: (e.g. Linux)
 - Toolchain (e.g Zephyr SDK, ...)
 - Commit SHA : 59c8c9930d0b27e2a53e05cd5947cbe7f8bc800b

**Comment by hakehuang** [comment]
@MaureenHelm @henrikbrixandersen

**Comment by henrikbrixandersen** [comment]
***** Booting Zephyr OS zephyr-v1.14.0-1117-g93fb695244c6 *****
Running test suite test_initialization
===================================================================
starting test - test_init
PASS - test_init
===================================================================
Test suite test_initialization succeeded
===================================================================
PROJECT EXECUTION SUCCESSFUL

**Comment by henrikbrixandersen** [comment]
@hakehuang It works for me on 59c8c9930d0b27e2a53e05cd5947cbe7f8bc800b.

I cannot find the commit SHA, you mention?
```
$ git show 59c8c9930d0b27e2a53e05cd5947cbe7f8bc800b
fatal: bad object 59c8c9930d0b27e2a53e05cd5947cbe7f8bc800b
```

**Comment by hakehuang** [comment]
sorry, it the master branch the SHAshall be e72e457360ffa8b07f29f6a5ce496a62d7ceb253

**Comment by henrikbrixandersen** [comment]
@hakehuang Have you tried erasing the entire flash before running this test? From a quick glance it seems that the test would fail the second time it is run without erasing the flash beforehand.

**Comment by hakehuang** [comment]
@henrikbrixandersen , you are right, but this seems the fcb has problem, it supposes to erase the fcb area, before usage.

**Comment by henrikbrixandersen** [comment]
@nvlsianpu Could you please take a look at this?

**Comment by nvlsianpu** [comment]
@hakehuang - I understand than with storage area erased before you run the tests, tests passed?

**Comment by henrikbrixandersen** [comment]
> @hakehuang - I understand than with storage area erased before you run the tests, tests passed?

Correct.

**Comment by nvlsianpu** [comment]
I confirm - this test assumes that storage partition is clear before the test is run.
So the issue appears just because `west flash` doesn't erase more flash than needed for program the device, so doesn't erase especially storage partition.

This test can't ensurer storage clearance because it reboots the device as the part of the testing routine.
So need to find a way take storage into build product.

**Comment by hakehuang** [comment]
> @hakehuang - I understand than with storage area erased before you run the tests, tests passed?

yes, it passes after erase.

@nvlsianpu
