### ISSUE TITLE
Code Coverage for qemu_x86 is not getting generated due to a build error

### ISSUE THREAD

**Issue by yerabolu** [zephyrproject-rtos/zephyr#16501]
**Describe the bug**
While running the below command for code coverage the tests on qemu_x86 are failing due to a build error. Tests are passing while running sanity check with out the code coverage option. 

~/zephyr/scripts/sanitycheck --coverage --coverage-platform qemu_x86 -p qemu_x86 --coverage-platform qemu_x86_nommu -p qemu_x86_nommu --gcov-tool /opt/zephyr-sdk/i586-zephyr-elf/bin/i586-zephyr-elf-gcov -T ~/zephyr/tests/kernel -T ~/zephyr/tests/subsys/logging | tee output.log

What have you tried to diagnose or workaround this issue?
Build error is observed after the below commit.
Commit ID: fb0faaa1239ad5f6577d3268c67ba168aab57656

**To Reproduce**
Run the above command and tests fail due to a build error. 

**Expected behavior**
Tests should pass. 

**Impact**
Blocking the code coverage.

**Screenshots or console output**
[ 83%] Building C object zephyr/CMakeFiles/zephyr_prebuilt.dir/misc/empty_file.c.obj
[ 84%] Linking C executable zephyr_prebuilt.elf
/opt/zephyr-sdk/i586-zephyr-elf/bin/../lib/gcc/i586-zephyr-elf/8.3.0/../../../../i586-zephyr-elf/bin/ld:linker.cmd:161: undefined symbol `_region_min_align' referenced in expression
collect2: error: ld returned 1 exit status
make[3]: *** [zephyr/CMakeFiles/zephyr_prebuilt.dir/build.make:95: zephyr/zephyr_prebuilt.elf] Error 1
make[3]: Target 'zephyr/CMakeFiles/zephyr_prebuilt.dir/build' not remade because of errors.
make[3]: Leaving directory '/home/syerabol/zephyr/sanity-out/qemu_x86/tests/subsys/logging/log_output/logging.log_output'
make[2]: *** [CMakeFiles/Makefile2:480: zephyr/CMakeFiles/zephyr_prebuilt.dir/all] Error 2
make[2]: Target 'all' not remade because of errors.
make[2]: Leaving directory '/home/syerabol/zephyr/sanity-out/qemu_x86/tests/subsys/logging/log_output/logging.log_output'
make[1]: *** [Makefile:84: all] Error 2
make[1]: Target 'default_target' not remade because of errors.
make[1]: Leaving directory '/home/syerabol/zephyr/sanity-out/qemu_x86/tests/subsys/logging/log_output/logging.log_output'

For complete log, please find the attached log.
[build.log](https://github.com/zephyrproject-rtos/zephyr/files/3234507/build.log)

**Environment (please complete the following information):**
 - OS: (e.g. Linux, MacOS, Windows): Fedora
 - Toolchain (e.g Zephyr SDK, ...)
 - Commit SHA or Version fb0faaa1239ad5f6577d3268c67ba168aab57656

**Additional context**

**Comment by wentongwu** [comment]
it seems this change just consider Arm platform, we should also take care x86. I'm cooking the patch for this issue.
