### ISSUE TITLE
FXOS8700 is not well supported in twr_ke18f

### ISSUE THREAD

**Issue by hakehuang** [zephyrproject-rtos/zephyr#16524]
**Describe the bug**
enable the i2c_api test with attached patch, I find that the twrke18f board missing defines the int2 gpio for the FXOS8700_0

**To Reproduce**
1. mkdir build; cd build
2. cmake -DBOARD=twr_ke18f ..
3. make

**Expected behavior**
missing in2_gpio define on twrke18f board

**Impact**
What impact does this issue have on your progress (e.g., annoyance, showstopper)

**Screenshots or console output**
```
/home/shared/disk/zephyr_project/zephyr/tests/drivers/i2c/i2c_api/src/test_i2c_mcux.c:52:34: error: 'CONFIG_FXOS8700_I2C_ADDRESS' undeclared (first use in this function); did you mean 'CONFIG_FXOS8700_PM_NORMAL'?
  if (i2c_read(i2c_dev, datas, 1, CONFIG_FXOS8700_I2C_ADDRESS)) {
                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~
                                  CONFIG_FXOS8700_PM_NORMAL
/home/shared/disk/zephyr_project/zephyr/tests/drivers/i2c/i2c_api/src/test_i2c_mcux.c:52:34: note: each undeclared identifier is reported only once for each function it appears in
/home/shared/disk/zephyr_project/zephyr/tests/drivers/i2c/i2c_api/src/test_i2c_mcux.c: In function 'test_burst_fxos':
/home/shared/disk/zephyr_project/zephyr/tests/drivers/i2c/i2c_api/src/test_i2c_mcux.c:83:31: error: 'CONFIG_FXOS8700_I2C_ADDRESS' undeclared (first use in this function); did you mean 'CONFIG_FXOS8700_PM_NORMAL'?
  if (i2c_burst_write(i2c_dev, CONFIG_FXOS8700_I2C_ADDRESS,F_SETUP_REG, datas, 3)) {
                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~
                               CONFIG_FXOS8700_PM_NORMAL
CMakeFiles/app.dir/build.make:88: recipe for target 'CMakeFiles/app.dir/src/test_i2c_mcux.c.obj' failed
make[2]: *** [CMakeFiles/app.dir/src/test_i2c_mcux.c.obj] Error 1
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/app.dir/all' failed
make[1]: *** [CMakeFiles/app.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

```
**Environment (please complete the following information):**
 - OS: (e.g. Linux)
 - Toolchain (e.g Zephyr SDK)
 - Commit SHA

**Comment by hakehuang** [comment]
@henrikbrixandersen  @MaureenHelm

**Comment by hakehuang** [comment]
[0001-enalbe-i2c_api-for-twrke18f.zip](https://github.com/zephyrproject-rtos/zephyr/files/3240574/0001-enalbe-i2c_api-for-twrke18f.zip)

**Comment by hakehuang** [comment]
need config CONFIG_FXOS8700_TRIGGER_NONE=y

**Comment by hakehuang** [comment]
[0001-enalbe-i2c_api-for-twrke18f.zip](https://github.com/zephyrproject-rtos/zephyr/files/3240616/0001-enalbe-i2c_api-for-twrke18f.zip)

**Comment by hakehuang** [comment]
seems the device driver changed, I need update my test settings

**Comment by henrikbrixandersen** [comment]
The first part of handling this was already submitted in #16116.
