### ISSUE TITLE
[Coverity CID :198880]Possible Control flow issues in /samples/net/lwm2m_client/src/lwm2m-client.c

### ISSUE THREAD

**Issue by aasthagr** [zephyrproject-rtos/zephyr#16567]
Static code scan issues seen in File: /samples/net/lwm2m_client/src/lwm2m-client.c
 Category: Possible Control flow issues
 Function: temperature_get_buf
 Component: Samples
 CID: 198880
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by aasthagr** [comment]
```
*** CID 198880:  Possible Control flow issues  (DEADCODE)
/samples/net/lwm2m_client/src/lwm2m-client.c: 193 in temperature_get_buf()
187     
188     #if defined(CONFIG_FXOS8700_TEMP)
189     	dev = device_get_binding(DT_NXP_FXOS8700_0_LABEL);
190     #endif
191     
192     	if (dev != NULL) {
>>>     CID 198880:  Possible Control flow issues  (DEADCODE)
>>>     Execution cannot reach this statement: "if (sensor_sample_fetch(dev...".
193     		if (sensor_sample_fetch(dev)) {
194     			LOG_ERR("temperature data update failed");
195     		}
196     
197     		sensor_channel_get(dev, SENSOR_CHAN_DIE_TEMP,
198     				  (struct sensor_value *) &v);
```

**Comment by mike-scott** [comment]
Coding style is intentional here.  The plan is to add more sensors as #if checks and end with a check of dev != null.

**Comment by ioannisg** [comment]
Then this issue will always trigger the same coverity report, @mike-scott , is there anything we can do? Should we just close it then?

**Comment by ioannisg** [comment]
Otherwise, we can keep the issue, but tet's remove the bug, at least, since this is intentional.

**Comment by carlescufi** [comment]
Marked as intentional in Coverity
