### ISSUE TITLE
Fault in CPU stats

### ISSUE THREAD

**Issue by pdunaj** [zephyrproject-rtos/zephyr#16606]
**Describe the bug**
```
ASSERTION FAIL [current_thread == k_current_get()] @ ./subsys/debug/tracing/cpu_stats.c:126
```

**To Reproduce**
1. Enable `TRACING_CPU_STATS`
2. Try to run...

**Expected behavior**
Should work.

**Impact**
annoyance - profiling tool is unusable

**Screenshots or console output**
Above.

**Environment (please complete the following information):**
master

**Additional context**
N/A

**Comment by pdunaj** [comment]
It seems that `sys_trace_thread_switched_out` happened before `sys_trace_thread_switched_in`...

**Comment by pdunaj** [comment]
I added a null-check on first switched out (and ignore it). After that CPU load seems to show the valid data (as far as I can tell).

**Comment by nashif** [comment]
This was introduced by @MarekPieta originally, can you please look at this?

**Comment by MarekPieta** [comment]
Yes, no problem. I will take look at it.

**Comment by MarekPieta** [comment]
I created a PR fixing this
