### ISSUE TITLE
SDK_VERSION

### ISSUE THREAD

**Issue by imadeveloper247** [zephyrproject-rtos/zephyr#16631]
building under Ubuntu 18.04

I think that the file ~zephyrproject/zephyr/cmake/toolchain/zephyr/generic.cmake might have an error on line 3:
     if(NOT DEFINED SDK_VERSION)
perhaps that should be:
    if(NOT SDK_VERSION)

Also the build docs for linux should have us:

export SDK_VERSION=0.10.0

Hope this is of some help!

Phil

**Comment by carlescufi** [comment]
@imadeveloper247 you don't need to export the SDK version at all. This is checked by the CMake files, you should only need to export:

`ZEPHYR_SDK_INSTALL_DIR=/path/to/sdk`
`ZEPHYR_TOOLCHAIN_VARIANT=zephyr`

What are you trying to solve exactly?

**Comment by SebastianBoe** [comment]
Closing due to reporter being unresponsive.
