### ISSUE TITLE
z_init_timeout() ignores fn parameter

### ISSUE THREAD

**Issue by zzzh** [zephyrproject-rtos/zephyr#16649]
Look the code below:

static inline void z_init_timeout(struct _timeout *t, _timeout_func_t fn)
{
	sys_dnode_init(&t->node);
}

As you can see, the parameter fn is not used, if it's not needed, it should not exist, or at least there should be a comment.

**Comment by zzzh** [comment]
As I see, there should be another line:
t.fn = fn;

**Comment by andyross** [comment]
Yeah, this is vestigial.  Looks like the argument got left in during refactoring.  The callback is passed in z_add_timeout.

**Comment by nashif** [comment]
code now has:
```
static inline void z_init_timeout(struct _timeout *t)
{
        sys_dnode_init(&t->node);
}
```
