### ISSUE TITLE
Checkpatch generates incorrect warning for __DEPRECATED_MACRO

### ISSUE THREAD

**Issue by mnkp** [zephyrproject-rtos/zephyr#16674]
**Bug descritpion**
When trying to deprecate a macro using `__DEPRECATED_MACRO` e.g.
```
#define GPIO_PUD_NORMAL        __DEPRECATED_MACRO 0
```
checkpatch generates the following warning
```
-:1067: WARNING:COMPLEX_MACRO: Macros with complex values should be enclosed in parentheses
#1067: FILE: include/gpio.h:274:
+#define GPIO_PUD_NORMAL        __DEPRECATED_MACRO 0
```
even if `__DEPRECATED_MACRO` is used correctly.

**To Reproduce**
1. modify source code by adding
`#define GPIO_PUD_NORMAL        __DEPRECATED_MACRO 0` 
2. commit changes using git.

**Expected behavior**
No warning.

**Environment:**
 - OS: Linux
 - Zephyr version 1.14

**Comment by gmarull** [comment]
We currently ignore COMPLEX_MACRO, so this no longer applies.
