### ISSUE TITLE
soc: stm32: Is the setting of NUM_IRQS in the F3 series wrong?

### ISSUE THREAD

**Issue by KwonTae-young** [zephyrproject-rtos/zephyr#16716]
I am currently looking at the soc settings of the `F3` series.
The current `F3` series are all set to `82` with the same `NUM_IRQS`.
``` 
config NUM_IRQS
	int
	default 82
```

As far as I know, these settings seem to be wrong.

**STM32F302X8**
Current code: https://github.com/zephyrproject-rtos/zephyr/blob/master/soc/arm/st_stm32/stm32f3/Kconfig.defconfig.stm32f302x8#L18-L20
Datasheet: https://www.st.com/resource/en/datasheet/stm32f302c8.pdf
![image](https://user-images.githubusercontent.com/10510127/59172849-28a00e00-8b85-11e9-9ee2-b6fd9c21d71b.png)

**STM32F303XC**
Current code: https://github.com/zephyrproject-rtos/zephyr/blob/master/soc/arm/st_stm32/stm32f3/Kconfig.defconfig.stm32f303xc#L18-L20
Datasheet: https://www.st.com/resource/en/datasheet/stm32f303vc.pdf
![image](https://user-images.githubusercontent.com/10510127/59172886-52f1cb80-8b85-11e9-82fd-bd0255a3c0f1.png)

**STM32F334X8**
Current code: https://github.com/zephyrproject-rtos/zephyr/blob/master/soc/arm/st_stm32/stm32f3/Kconfig.defconfig.stm32f334x8#L18-L20
Datasheet: https://www.st.com/resource/en/datasheet/stm32f334r8.pdf
![image](https://user-images.githubusercontent.com/10510127/59172918-7a489880-8b85-11e9-81e3-7739f8a30478.png)

**STM32F373XC**
Current code: https://github.com/zephyrproject-rtos/zephyr/blob/master/soc/arm/st_stm32/stm32f3/Kconfig.defconfig.stm32f373xc#L18-L20
Datasheet: https://www.st.com/resource/en/datasheet/stm32f373c8.pdf
![image](https://user-images.githubusercontent.com/10510127/59172938-951b0d00-8b85-11e9-8a59-cb0999c66a3c.png)

Is the setting of `NUM_IRQS` of F3 series wrong?
Or am I mistaken about the setting value of `NUM_IRQS`?

I'm sorry I do not have enough English. :)
Thank you.

**Comment by ioannisg** [comment]
@erwango could you address this one?

**Comment by KwonTae-young** [comment]
I reviewed all the STM32 series and created a commit to modify `NUM_IRQS`.

**Comment by ydamigos** [comment]
@KwonTae-young Please check IRQn_Type enumerations in SoC header files at `ext/hal/st/stm32cube/stm32fxxx/soc`. `NUM_IRQS` is equal to the maximum IRQ number plus 1.

**Comment by KwonTae-young** [comment]
@ydamigos Thank you. I was misunderstanding NUM_IRQS. :sweat_smile:
