### ISSUE TITLE
spi: stm32: pinmux: default configuration does not opt for low power consumption

### ISSUE THREAD

**Issue by gon1332** [zephyrproject-rtos/zephyr#16739]
**Is your enhancement proposal related to a problem? Please describe.**
The SPI MOSI/MISO are configured as PP NOPULL from the pinmux. The use case is when having a SPI peripheral. Putting the board in STOP2 mode with the current configuration, the consumption is approximately 20uA (per pin) more than having those pins set as PP PULL{UP, DOWN}.

**Describe the solution you'd like**
I would like to have these pins configured as PP PULL{UP, DOWN} from the pinmux driver.

**Describe alternatives you've considered**
Set these pins as PULL{UP, DOWN} after Zephyr initialization from the application.

**Additional context**
Tested on a custom board with a STM32L496RE and on Nucleo L496ZG.

If you think that's OK, I can open a PR to fix this.

**Comment by gon1332** [comment]
@galazari @nikooiko

**Comment by gon1332** [comment]
Also the same behaviour is observed while in RUN mode.

**Comment by erwango** [comment]
@gon1332 , I'm fine with this change

**Comment by loicpoulain** [comment]
A bus like SPI is generally push-pull, I don't fully understand the root cause of this issue, any input or official recommendation from ST is welcome here. Moreover, I suspect adding a pull (up/down) increases consumption during active transfers and **may** cause issue at highest speeds due to the created low pass filter, though it needs to be calculated.

**Comment by erwango** [comment]
One interesting document could be found here:
https://www.st.com/resource/en/application_note/dm00033348.pdf
Though it does not mention anything on pupd pin configuration.
One interesting hint though: deactivate GPIO clock once pin configuration is done.

**Comment by loicpoulain** [comment]
> One interesting document could be found here:
> https://www.st.com/resource/en/application_note/dm00033348.pdf
> Though it does not mention anything on pupd pin configuration.
> One interesting hint though: deactivate GPIO clock once pin configuration is done.

Indeed, it deserves a try!
