### ISSUE TITLE
net: net_pkt_copy don't work as expected when data was pulled from destination

### ISSUE THREAD

**Issue by alexanderwachter** [zephyrproject-rtos/zephyr#16766]
**Describe the bug**
`net_pkt_clone` don't work as expected when data was pulled from the destination.
Data is usually pulled when headers are removed (Ethernet header for example).
The reason for this that d_len is calculeted using buf->size but the data pointer is already advanced. This results in a out of bounds write.

**Expected behavior**
Stop writing at the end of the buffer

**Impact**
`net_pkt_clone` is actually not used on such packets. But This seems to be dangerous.

**Comment by carlescufi** [comment]
@jukkar @tbursztyka is this still an issue?
