### ISSUE TITLE
K_THREAD_STACK_EXTERN() confuses gen_kobject_list.py

### ISSUE THREAD

**Issue by andrewboie** [zephyrproject-rtos/zephyr#16760]
**Describe the bug**
If a C file is built that has an extern declaration of a thread stack, before the actual declaration of the thread stack, the kernel object detection mechanism will fail to register the stack object and system calls on it (such as k_thread_create()) will fail:

```
0x00423000 is not a valid _k_thread_stack_element
syscall z_hdlr_k_thread_create failed check: bad stack object
***** Kernel OOPS! *****
Current thread ID = 0x00401ae0
eax: 0x00000000, ebx: 0x00000000, ecx: 0x00000000, edx: 0x00000000
esi: 0x00000000, edi: 0x00000000, ebp: 0x00000000, esp: 0x00428f98
eflags: 0x00000246 cs: 0x002b
call trace:
eip: 0x00002fb0
NULL base ptr
Fatal fault in thread 0x00401ae0! Aborting.
```

This could happen commonly if a header file has the extern declaration, and the C file which defines the thread stack object includes it.

Only seems to affect thread stacks, other kernel object types work fine if an extern declaration is present. Probably has something to do with how gen_kobject_list.py handles arrays.

This also affects K_THREAD_STACK_ARRAY_DEFINE.

**To Reproduce**
Build an application with CONFIG_USERSPACE enabled with the following code snippet:

```
K_THREAD_STACK_EXTERN(ustack);
K_THREAD_STACK_DEFINE(ustack, STACK_SIZE);
```

If you build with VERBOSE=1, the output of gen_kobject_list.py will not show it.

If you then comment out the K_THREAD_STACK_EXTERN() line, it will be detected:

`
gen_kobject_list.py: symbol 'ustack' at 0x423000 contains 1 object(s)
`

Similar behavior with K_THREAD_STACK_ARRAY_DEFINE, please make sure both are fixed.

```
extern k_thread_stack_t
	tstacks[MAX_NUM_THREAD][K_THREAD_STACK_LEN(STACK_SIZE)];
K_THREAD_STACK_ARRAY_DEFINE(tstacks, MAX_NUM_THREAD, STACK_SIZE);
```

I found this when making adjustments to tests/kernel/sched/schedule_api to run some tests in user mode.

**Expected behavior**
gen_kobject_list.py should not disregard thread stacks which have an extern declaration in the same compilation unit.

**Impact**
major annoyance, possible to work around. will greatly confuse users who don't know about this bug.

please backport to 1.14

**Environment (please complete the following information):**
Seen on qemu_x86, probably affects all userspace arches

**Comment by andrewboie** [comment]
@wentongwu can you take a look at this one? This would be a good opportunity to learn more about how gen_kobject_list.py works.

**Comment by wentongwu** [comment]
> @wentongwu can you take a look at this one? This would be a good opportunity to learn more about how gen_kobject_list.py wo

**Comment by wentongwu** [comment]
sorry, mis-click.
yes, I'm checking this issue. Thanks

**Comment by wentongwu** [comment]
will add analysis for DW_TAG_typedef to fix this issue.

**Comment by wentongwu** [comment]
not only DW_TAG_typedef doesn't been considered, but also handle "extern type variable[]" incorrectly.
