### ISSUE TITLE
Build failures in various mimxrt boards

### ISSUE THREAD

**Issue by jukkar** [zephyrproject-rtos/zephyr#16778]
**Describe the bug**
I am seeing this error in several PRs that I have submitted
```
ERROR: section nocache is 128 bytes in the virtual/runtime address space, but only 0 in the loaded/XIP section!
```
when sanitychecker uses board mimxrt1050_evk_qspi, mimxrt1050_evk or mimxrt1064_evk.
Some of the PRs that show this issue are #16743 #16464  #16403 #16772 
One example shippable log can be found here
https://app.shippable.com/github/zephyrproject-rtos/zephyr/runs/43576/summary/console

**Impact**
This is a showstopper for those PRs that I mentioned above. I do not see any issue in the PRs that would cause this issue.

**Comment by ioannisg** [comment]
I think I saw this recently. I'll take a look.

**Comment by agansari** [comment]
@ioannisg i remember somethin similar in #15836

**Comment by jukkar** [comment]
I submitted #16811 that will disable Ethernet so that networking PRs can be merged. That is of course a workaround and should be reverted eventually.

**Comment by ioannisg** [comment]
@agansari yes, you're right, that's  why this looked familiar. @jukkar perhaps, the root cause **is** the check_link_map.py script. Could we confirm that before merging the revert PR?

**Comment by jukkar** [comment]
> Could we confirm that before merging the revert PR?

Sure, np.

**Comment by jukkar** [comment]
@ioannisg have you managed to figure out the culprit of this one?

**Comment by ioannisg** [comment]
@jukkar on my task list for today :)
