### ISSUE TITLE
TCP2 integration

### ISSUE THREAD

**Issue by laperie** [zephyrproject-rtos/zephyr#16809]
The final steps of preparing new TCP stack for integration to Zephyr tree will be tracked in this issue.  As a result of these steps, the TCP2 should be available under certain KConfig flag (mutually exclusive with existing TCP stack) with existing TCP unit tests passing, existing samples functional and comparable Maxwell Pro results

These are the steps to integrate TCP2 to the existing net stack:
- [x] Use specific KConfig option
- [x] Integrate to connection.c  (RX side of things)
- [x] Integrate with net_context API (RX and TX side of things)  

We expect to run the following tests on the TCP2
- [x] Current TCP unit tests (passing)
- [x] Maxwell Pro  (comparable pass rate)
- [x] Samples (all working)

TODO:
- [x] Add support for big payloads
- [x] Add support for IPv6 (both TCP2 and TTCN-3)
- [ ] Add support for IP options (both TCP2 and TTCN-3)
- [x] Check and add log_strdup() where necessary
- [ ] Add tests with overlapping TCP data segments into TTCN-3
- [x] Make TCP2 the default

**Comment by jukkar** [comment]
>     * Maxwell Pro  (comparable pass rate)

For integration work, I think this is not really needed. It is very much needed when we want to replace TCP1 by TCP2.

**Comment by jukkar** [comment]
TCP2 was merged to upstream last Friday so we will concentrate next to test it.

**Comment by dleach02** [comment]
There are a number of issues on this ticket that look like they will be v2.2 (and potentially beyond) items. It would make sense to mapout the "todo" items over the various release milestones.

**Comment by carlescufi** [comment]
@jukkar could you update the description with any progress made in the last couple of months?

**Comment by jukkar** [comment]
I need to pass this req to the source, @ozhuraki could you update the description about what has been done and what is still missing.

**Comment by carlescufi** [comment]
@jukkar is this on track for 2.3?

**Comment by jukkar** [comment]
> is this on track for 2.3?

Yes, we are doing our best to improve the functionality and test coverage more.

**Comment by jukkar** [comment]
TCP2 is now the default -> closing.
