### ISSUE TITLE
nRF52: UARTE: Data corruption right after resuming device

### ISSUE THREAD

**Issue by endian-benjamin** [zephyrproject-rtos/zephyr#16861]
Providing a bare-bones reproducible example isn't easy in this case, but I can reproduce it reliably with customer code. It seems that when you suspend the UARTE and then resume it (using `device_set_pm_state()`), there is a window right after resume in which transmissions get corrupted. This is the setup:

1. pm hooks suspends UART and `cpu_idle()`
2. timer interrupt triggers; pm hooks resume UART, ISR pushes item to work queue
3. work item TX:es eight bytes and RX:es eight bytes

I have verified by oscilloscope that the bytes TXed are correct and the bytes RXed are correct on the serial line. However, when my application reads the RX bytes, they are garbled (and an extra byte is added). This can be reproduced consistently, but only if the power management hooks suspending/resuming the UART are enabled.

It can be worked around by adding a dummy RX prior to TXing, so it's not a high prio bug (for me atleast :P) but it's clearly indicative of something generating spurious events.

**Comment by Mierunski** [comment]
Hi, thank you for sharing!

Could you please elaborate on which API you are using? Polling, interrupt or asynchronous?

**Comment by ioannisg** [comment]
@endian-benjamin can you elaborate a bit more here?

**Comment by endian-benjamin** [comment]
@ioannisg @Mierunski Using the interrupt driven approach (with a wrapper handler).

So

- pm hooks calls `device_set_power_state` to wake up UART
- work item sets tx irq handler and calls `uart_irq_tx_enable`
- work item enables rx interrupts and waits for response
- response on the line is, say, `AA BB CC DD EE`, verified by oscilloscope
- work item receives NOT five bytes, but SIX, and they are garbled. 

If I disable power manager, then no bytes are garbled and no bytes are added. The current workaround is to flush the RX line prior to every TX (by triggering an RX and simply discarding the bytes received), which works fine for our use case.

**Comment by ioannisg** [comment]
@Mierunski could you follow up with this one?

**Comment by ioannisg** [comment]
@endian-benjamin could you please, check the patch proovided by @Mierunski ?
