### ISSUE TITLE
No test coverage for CONFIG_ZERO_LATENCY_IRQS

### ISSUE THREAD

**Issue by andyross** [zephyrproject-rtos/zephyr#16901]
This ARM feature exists and appears correct (and builds, at least), but is exercised anywhere in the existing test suite.  It needs validation if we're going to claim it as a feature.

**Comment by andyross** [comment]
Discovered when code review for #16782 asked for ZLI support.

**Comment by ioannisg** [comment]
FYI @pizi-nordic

**Comment by pizi-nordic** [comment]
FYI: @nordic-krch

**Comment by ioannisg** [comment]
I've got an idea of a simple test for this feature; if you have any proposals, @nordic-krch , you can write here.
