### ISSUE TITLE
Missing test case coverage for include/misc/byteorder.h functions

### ISSUE THREAD

**Issue by andrewboie** [zephyrproject-rtos/zephyr#16942]
According to LCOV, for include/misc/byteorder.h we only have 58.1% line coverage for this header file.

Need to create a testcase for these functions that prove that each one of them works with all conditional branches taken.

**Comment by nashif** [comment]
> According to LCOV, for include/misc/byteorder.h we only have 58.1% line coverage for this header file.

this number is misleading, probably applies to usage coverage, not test coverage. I can only see two functions with tests.

**Comment by andrewboie** [comment]
Yeah, we don't have any explicit tests to prove that these APIs work.

**Comment by nashif** [comment]
afaik covered in tests/kernel/common/src/byteorder.c
