### ISSUE TITLE
Missing test coverage for lib/os/crc*.c

### ISSUE THREAD

**Issue by andrewboie** [zephyrproject-rtos/zephyr#16943]
We have a bunch of C files in lib/os for computing CRC values. These are not being tested. LCOV shows 42.9% line coverage for crc16_sw.c, and zero coverage for crc32_sw.c, crc7_sw.c, crc8_sw.c. Need to get these up to 100% coverage including branches.

**Comment by aescolar** [comment]
@andrewboie Did you account for its unit test? the codecov report seems to indicate they are quite well covered:
https://codecov.io/gh/zephyrproject-rtos/zephyr/tree/master/lib/os

**Comment by andrewboie** [comment]
@aescolar we are not getting any of this stuff when we run coverage reports using gcovr/lcov.
Someone needs to fix that.

**Comment by aescolar** [comment]
> @aescolar we are not getting any of this stuff when we run coverage reports using gcovr/lcov.
Someone needs to fix that.

@andrewboie Do you mean we don't when run with the QEMU target? The unit tests are their own target: ```sanitycheck -p unit_testing -C```
The old codecov report was based on everything run in the 1st CI instance (which should include unit_testing, native_posix and nrf52_bsim).

**Comment by andrewboie** [comment]
>  and the crc is covered by unit tests (their only user actually))

Why are the CRC tests a special snowflake?
This is a total, inconsistent mess!!

**Comment by aescolar** [comment]
Don't ask me, it was there before I joined the project.
But you can see the positive side of it: the CRC test is a test of the unit tests and all related infrastructure ;-)

**Comment by nashif** [comment]
last time I tried I was not able to combine results generated by qemu targets with native_poisx and unit_test.

crc in any case is well covered with the unit_test, shows 100% here when I run locally.

**Comment by andrewboie** [comment]
@nashif what should we do about this with respect to our code coverage reports?
Should I convert this into a standard ztest? Leave it alone?
