### ISSUE TITLE
revise concurrency control in kernel/userspace.c

### ISSUE THREAD

**Issue by andrewboie** [zephyrproject-rtos/zephyr#17021]
The concurrency control in kernel/userspace.c used to be implemented completely in terms of irq_lock()/irq_unlock(), and ports poorly to SMP-safe spinlocks.

The current port to spinlocks will not really work well on a real SMP system, the locks are not used consistently and some are "protecting" code and not data. In addition, we would like in some cases to use k_mutex for protecting things like the dynamic object lists, which would reduce the amount of interrupt suppression going on.

**Comment by ceolin** [comment]
SMP is being around for while and it seems to be working fine. If a related problem appears I re-open it.
