### ISSUE TITLE
Bluetooth: GAP/IDLE/NAMP/BV-01-C requires Read by UUID

### ISSUE THREAD

**Issue by Vudentz** [zephyrproject-rtos/zephyr#17092]
GAP/IDLE/NAMP/BV-01-C:

Verify the IUT can perform the Name Discovery Procedure and retrieve the device name from a peer device.

In order to pass this test PTS expects Read by UUID to be used.

**Comment by ioannisg** [comment]
This seems to be already merged. Right @Vudentz
