### ISSUE TITLE
arch/x86: eliminate support for CONFIG_REALMODE

### ISSUE THREAD

**Issue by gnuless** [zephyrproject-rtos/zephyr#17166]
Jailhouse was the only "board" that started in real mode, so this option and its supporting logic in crt0.S and the linker script is orphaned and should be removed.

**Comment by ioannisg** [comment]
Will you submit a patch for this @gnuless ?

**Comment by gnuless** [comment]
@ioannisg I was planning to, eventually, unless someone else beats me to it.
