### ISSUE TITLE
net-mgmt should pass info element size to callback

### ISSUE THREAD

**Issue by jukkar** [zephyrproject-rtos/zephyr#17190]
**Describe the bug**
The information element size should be passed to the user defined callback. The system works atm if the info element can be determined from the network management event type. Sometimes this is not possible so the application needs to know the info element size.

**Impact**
The application might not be able to utilize the information element tied to the network management event.

This issue is created so that we can backport few commits from PR #16743 to 1.14

**Comment by tbursztyka** [comment]
"Sometimes this is not possible so the application" Currently it is always possible. Even for the socket layer.

**Comment by jukkar** [comment]
The PR was merged -> closing.
