### ISSUE TITLE
Bluetooth: controller: Fix handling of L2CAP start frame with zero PDU length

### ISSUE THREAD

**Issue by cvinayak** [zephyrproject-rtos/zephyr#17288]
**Describe the bug**
When a host sends HCI ACL packet with L2CAP start frame length of zero, the controller is sending incorrect LL_DATA START PDU with zero length.

**To Reproduce**
Run BT LL TS 5.1.0 conformance test cases

**Expected behavior**
The controller should not send LL_DATA START PDU with zero length.

**Impact**
Failing test case

**Screenshots or console output**
Not available

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain Zephyr SDK
 - Commit SHA or Version used: Zephyr v1.14 release

**Additional context**
None

**Comment by ioannisg** [comment]
Looks like this is fixed. Correct @cvinayak
