### ISSUE TITLE
insufficient code coverage for include/sys/math_extras_impl.h

### ISSUE THREAD

**Issue by andrewboie** [zephyrproject-rtos/zephyr#17336]
The inline functions declared here are not sufficiently tested by test cases in tests/kernel/ or tests/lib/.

I can find no test case at all which proves that these work. Need to add a test under tests/lib/ which exercises every function, with and without builtins, and prove that they work.

**Comment by rubidijum** [comment]
These are actually covered in `/tests/unit_tests`. 
Here is the lcov report:
![image](https://user-images.githubusercontent.com/19934088/233806989-ce720771-126c-45ce-aaad-7b4a505a11dd.png)

I tested with both builtin and portable versions, although there is a small bug in `tests/unit/math_extras/portable.c`:

```
#define VNAME(N) test_portable_##N
#include "tests.inc"

ZTEST(math_extras_portable, test_portable_u32_add) {
	run_portable_u32_add();
}

...
```

Where i had to change `#define VNAME(N) test_portable_##N` to `#define VNAME(N) run_portable_##N`

**Comment by nashif** [comment]
well, I would say we have many things that do not have good code coverage, we do not need to have an issue about each.,
