### ISSUE TITLE
CODEOWNERS is broken (III)

### ISSUE THREAD

**Issue by aescolar** [zephyrproject-rtos/zephyr#17342]
A comma was added to a new path in
9dbdd81

But GitHub's CODEOWNERS parsing cannot handle commas in paths

Related to #16000

**Comment by ioannisg** [comment]
Can we just, go once through the CODEOWNERS file and remove all commas? So we avoid new breakings when doing legitimate changes to the file.

I this this should do it; we are , anyways, careful, when doing changes in that file (doesn't mean I don't agree with adding a CI check)
