### ISSUE TITLE
Regression: sanitycheck coverage generation defaults will error out for POSIX arch targets

### ISSUE THREAD

**Issue by aescolar** [zephyrproject-rtos/zephyr#17366]
**Describe the bug**
After #17271 (8047a6f), running sanitycheck with the `-C`/`--coverage` option for POSIX arch based boards (e.g. `native_posix`) will result in a lot of errors instead of a coverage report due to `gcov` version incompatibilities.

**To Reproduce**
For example:
sanitycheck -p native_posix -T tests/kernel -C

**Expected behavior**
Things working as before the offending commit for POSIX arch boards (`native_posix` and `nrf52_bsim`)

**Impact**
Confused users of POSIX arch boards due to their workflows broken.

**Environment:**
 - OS: Linux (e.g. Ubuntu 18.04)
 - Toolchain: SDK 0.10.1 + host gcc 7.3.0-27ubuntu1~18.04
 - Commit SHA or Version used: Any after 8047a6f

-------
Related to #17365

**Comment by aescolar** [comment]
@andrewboie Will you take this?

**Comment by andrewboie** [comment]
> @andrewboie Will you take this?

Why are there two bugs filed on this?
If #17359 is not an acceptable solution to this, no I will not take this.

**Comment by aescolar** [comment]
@andrewboie : Well, #17359 does not fix the regression in itself, though it reduces the effect for new users.
Would it be a reasonable solution, that would make both qemu_x86 and native_posix users happy, to have the default  gcov tool in sanitycheck be selected based on the selected platform? (if type native => gcov, else, the current default)
