### ISSUE TITLE
Time Slicing cause system sleep short time

### ISSUE THREAD

**Issue by wentongwu** [zephyrproject-rtos/zephyr#17368]
**Describe the bug**
When enabled CONFIG_TIMESLICING and there is only idle thread running, cpu will enter low power state, but time slicing wake up cpu with CONFIG_TIMESLICE_SIZE frequency. and that causes some unnecessary power consuming because when idle thread running, there should be no other thread ready, time slicing should be disabled.

**Comment by aescolar** [comment]
CC @andyross
