### ISSUE TITLE
device tree diagnostic failure in enum

### ISSUE THREAD

**Issue by pabigot** [zephyrproject-rtos/zephyr#17376]
If a devicetree YAML specifies that valid content is constrained to be an enumerated value, and the devicetree property does not match one of the listed values, `extract/default.py` simply prints "ERROR" on the console and proceeds without providing a `PATH_ENUM` define.

It should instead emit a diagnostic and reject the property.

**Comment by galak** [comment]
@pabigot is this still an issue with the new scripts?

**Comment by pabigot** [comment]
No, there's a diagnostic now.
