### ISSUE TITLE
v1.14-branch: SDK 0.10.1 support?

### ISSUE THREAD

**Issue by pfalcon** [zephyrproject-rtos/zephyr#17487]
Current master requires (forces) use of SDK 0.10.1, while current v1.14-branch vice-versa, is unable to work with it (due to lack of cmake/toolchain/zephyr/0.10.1 or whatever).

This complicates various triaging and CI tasks.

Is there interest for the latest LTS release to support the latest SDK? If not, d'oh.

**Comment by pfalcon** [comment]
cc @galak

**Comment by pfalcon** [comment]
Specifically issues happen with Zephyr.js project - that was barely updated to build against 1.14, we definitely don't want to switch it to master yet. But would be nice to use the current SDK (I don't even know if our (Linaro's) CI supports multiple SDK versions, likely we just switch to the latest.

**Comment by pfalcon** [comment]
@ioannisg, @galak, Any feedback?

**Comment by andrewboie** [comment]
I already have a backport PR which does this #17470

**Comment by pfalcon** [comment]
@andrewboie : Thanks!

**Comment by nashif** [comment]
this was already merged.
