### ISSUE TITLE
SimpleLink WiFi host driver should revert back to using static memory model

### ISSUE THREAD

**Issue by vanti** [zephyrproject-rtos/zephyr#17550]
**Describe the bug**
During the upgrade to TI SDK 2.40, the SimpleLink WiFi host driver code has moved to using the dynamic memory model. This only works well if malloc() is thread-safe, but the implementation in newlib does not appear to be. So it is best to revert back to using static memory allocation in the driver, the way it used to be before the upgrade.

**Impact**
Memory corruption issues might occur if SimpleLink host driver is used concurrently with other threads calling malloc().

**Environment (please complete the following information):**
 - OS: Linux
 - Zephyr SDK 0.10.1
 - Commit SHA: 92ddf63cb80141bc6a032f2c96801556b2f755bd

**Comment by andrewboie** [comment]
> This only works well if malloc() is thread-safe, but the implementation in newlib does not appear to be

This seems like the bug right here.
I suspect the problem is in _sbrk(), in lib/libc/newlib/libc-hooks.c.
Probably need to change it to do an atomic_add() perhaps?

**Comment by andrewboie** [comment]
@vanti can you try #17552

**Comment by vanti** [comment]
Verified build of #17552. The latter should address the issue. I suggest we only apply this PR if #17552 does not make it in time for the 2.0 release.

**Comment by galak** [comment]
Merged #17552, so I think we can close this.  @vanti, can you verify.

**Comment by vanti** [comment]
Thanks @andrewboie @galak. Now that malloc() is thread-safe, we can keep using the dynamic memory model.
