### ISSUE TITLE
k_mutex is not SMP-safe

### ISSUE THREAD

**Issue by andrewboie** [zephyrproject-rtos/zephyr#17584]
The mutex code was written to rely on a k_sched_lock() to prevent
preemption by other threads while inspecting the mutex state for the
uncontended fast paths. The k_mutex APIs cannot be legally used in
ISRs, so this is a safe and clever way to reduce the size of the
critical section.

Unfortunately it just doesn't work in SMP. Preventing the kernel from
preempting your thread says nothing about threads running on other
CPUs.

**Comment by andrewboie** [comment]
There is an unfinished patch related to this #15164

**Comment by andrewboie** [comment]
This is at least medium if not high priority, although k_mutex is not used much within the kernel itself, we cannot make such assertions for applications

**Comment by andrewboie** [comment]
@jocelyn-li can you have someone look into this?

**Comment by andyross** [comment]
Drop priority.  This is a real race, but it was found by inspection and has never been seen in the wild.
