### ISSUE TITLE
ARC: unable to induce kernel_oops or stack check fail errors from user mode

### ISSUE THREAD

**Issue by andrewboie** [zephyrproject-rtos/zephyr#17590]
Steps to reproduce:

Pull https://github.com/zephyrproject-rtos/zephyr/pull/17589
And run tests/kernel/mem_protect/userspace
All cases need to succeed.
Right now, calling z_arch_except() from user mode results in an EV_PrivilegeV error.
The result is that the wrong error reason is reported.

**Comment by vonhust** [comment]
Fixed by PR #18079
