### ISSUE TITLE
devicetree: missing preferred instance presence macro

### ISSUE THREAD

**Issue by pabigot** [zephyrproject-rtos/zephyr#17650]
A recent change prefers ` DT_INST_0_JEDEC_SPI_NOR_LABEL` over `DT_JEDEC_SPI_NOR_0_LABEL`, however the flag symbol `DT_JEDEC_SPI_NOR_0` remains undeprecated and there is no `DT_INST_0_JEDEC_SPI_NOR` that can be used to detect presence of the device.

This should be made consistent.

**Comment by pabigot** [comment]
@ioannisg I disagree with the priority low: we need a standard way to detect presence of specific instances of a device using `IS_ENABLED()` and `#ifdef`.  At present this is inconsistent and incomplete.  This should be medium and fixed before 2.0.

@ulfalizer please address this in or after merge of #17660.  Currently the new tooling generates `DT_INST_0_JEDEC_SPI_NOR_LABEL` and does not generate `DT_JEDEC_SPI_NOR_0_LABEL`, but it still generates `DT_JEDEC_SPI_NOR_0` and not `DT_INST_0_JEDEC_SPI_NOR`.

**Comment by ulfalizer** [comment]
Will look later, unless @galak gets to it first.

Honestly a lot of those macros still feel like random combinations of words to me. Probably a bunch of stuff that could be cleaned up.
