### ISSUE TITLE
Missing 'reg-names' string in riscv32-litex-vexriscv.dtsi

### ISSUE THREAD

**Issue by ulfalizer** [zephyrproject-rtos/zephyr#17715]
`dts/riscv32/riscv32-litex-vexriscv.dtsi` has this:

```
#address-cells = <1>;
#size-cells = <1>;

...

eth0: ethernet@e0009800 {
	...
	reg = <0xb0000000 0x2000 0xe0009800 0x6b>;
	...
	reg-names = "control";
	...
};

```

Since `reg` has two entries, `reg-names` should have two strings instead of one.

Don't know what to put in here.

Causes a failure in https://github.com/zephyrproject-rtos/zephyr/pull/17660:

    device tree error: reg-names property in ethernet@e0009800 has 1 strings, expected 2 strings

**Comment by ulfalizer** [comment]
CC @mateusz-holenko

**Comment by mateusz-holenko** [comment]
I'm on it.
