### ISSUE TITLE
how to make zephyr as a ble mesh provisioner to other BLE based board having ble mesh

### ISSUE THREAD

**Issue by rahul30694** [zephyrproject-rtos/zephyr#17727]
I tried to flash the mesh sample to nordic board , but how to provision a board having ble mesh software using zephyr?

**Comment by carlescufi** [comment]
@rahul30694 you can use BlueZ or any number of mobile apps such as the SiLabs or Nordic ones

**Comment by carlescufi** [comment]
This is covered by https://github.com/zephyrproject-rtos/zephyr/issues/17454
