### ISSUE TITLE
stm32: Move clock configuration to device tree

### ISSUE THREAD

**Issue by erwango** [zephyrproject-rtos/zephyr#17745]
**Is your enhancement proposal related to a problem? Please describe.**
Current clock-control configuration (ie system clock source configuration) for stm32 based devices currently happens via Kconfig. To comply with overall device configuration, and follow other zephyr clock evolution (#15363, #16958) this should be moved to device tree.

Supersets #17703

**Describe the solution you'd like**
Bindings used for clock configuration should be similar to usual Linux clocks bindings.
Only difference would be new bindings introduced for pll parameters (various divisors, pre-divisors and multipliers) following current Kconfig scheme. This deviates from usual Linux binding which usually provides the output pll freq and use an algo at run time to calculate the various parameters allowing to set the required freq. At a later step, we might study the run time calculation option but for now, considering the range of clock-control IPs to study, keeping the current configuration scheme should speed up the implementation.
Same choice would be done for bus prescalers.

**Describe alternatives you've considered**

**Additional context**
Add any other context or graphics (drag-and-drop an image) about the feature request here.

**Comment by b0661** [comment]
> Only difference would be new bindings introduced for pll parameters (various divisors, pre-divisors and multipliers) following current Kconfig scheme

What is the benefit to move application specific configurations (various divisors, pre-divisors and multipliers) to DTS?

DTS is a hardware description - with some exceptions. Fixed clocks (SoC internal & external on board) are hardware. Clock (tree) selection and clock divisor configuration is in my view related to the application and shall therefor be defined by Kconfig. An application developer may select a different clock tree based on the application needs using the same hardware/ board.

**Comment by erwango** [comment]
@b0661 

Since last year discussions, community agreed that DTS would be used for hardware description AND its boot-time configuration. This is reflected in zephyr documentation in following section: [Device Tree vs Kconfig](https://docs.zephyrproject.org/latest/guides/dts/index.html?#device-tree-vs-kconfig). In that view, clocks configuration is part of hardware configuration and moving it to DTS fits that split.
This is also matching the DTS practice done in other systems using it such as Linux kenel.

**Comment by b0661** [comment]
@erwango 

> Since last year discussions, community agreed that DTS would be used for hardware description AND its boot-time configuration.

Thanks for the info.

>  In that view, clocks configuration is part of hardware configuration and moving it to DTS fits that split.

As an application developer will I still be able to change the clock configuration _WITHOUT_ changing the DTS?

**Comment by erwango** [comment]
@b0661 

> As an application developer will I still be able to change the clock configuration WITHOUT changing the DTS?

This won't be possible indeed. And tbh, I think it's for the best since having mixed dts/Kconfig would be source of bugs, confusion and finally misuse.
Though, one option I see is to support run time clock configuration, which is not available for now.

**Comment by gon1332** [comment]
Just to put more info on runtime clock configuration there this relative issue: https://github.com/zephyrproject-rtos/zephyr/issues/12134
