### ISSUE TITLE
Microchip XEC rtos timer should be using values coming from DTS 

### ISSUE THREAD

**Issue by tbursztyka** [zephyrproject-rtos/zephyr#17775]
Though dts/arm/microchip/mec1501hsz.dtsi provide the right values (base address, irq...), code source found in drivers/timer/mchp_xec_rtos_timer.c use none of these.

Using HAL is nice in case of a lot of code being already written and drivers can then make a good use of it, but things like macros for  base address, IRQ ... not really

**Comment by nashif** [comment]
@albertofloyd @dcpleung @franciscomunoz  can you please look it that? it seems part of it was already addressed?
