### ISSUE TITLE
Question:Is it possible to connect the device on internet using bluetooth connection?

### ISSUE THREAD

**Issue by chtavares592** [zephyrproject-rtos/zephyr#17781]
Hello,

I am developing an application that connects my device via Bluetooth to my smartphone. I wonder if I can use my smartphone's internet connection on the device.

I am using nrf52840 board. I am running the example `/samples/boads/nrf52/mesh/onoff-app`.

 If it is possible to connect the device on the internet using Bluetooth connection, how I can do that?

**Comment by Vudentz** [comment]
Not with mesh, with IPSP it might be possible if you have a gateway to route the IP traffic but having mesh with IPSP means you can not longer use the whole bandwidth for advertising/scanning.
