### ISSUE TITLE
Bluetooth: host: conn.c missing parameter copy

### ISSUE THREAD

**Issue by xiaoliang314** [zephyrproject-rtos/zephyr#17789]
Missing interval_min
https://github.com/zephyrproject-rtos/zephyr/blob/81ef42d2bcc3d7d59d61fa996712fc6ac5f10e1e/subsys/bluetooth/host/conn.c#L1944-L1950

**Comment by aescolar** [comment]
CC @jhedberg

**Comment by xiaoliang314** [comment]
@jhedberg Can you pay attention to this issue?

**Comment by jhedberg** [comment]
> @jhedberg Can you pay attention to this issue?

@xiaoliang314 this looks like a trivial thing to fix. Would you like to try submitting a pull request for it? FWIW, I've just returned from vacation and going through my backlog - this one didn't show up on my list since it's not assigned to me.
