### ISSUE TITLE
Timeutil_api test fails with sanitycheck on iotdk board.

### ISSUE THREAD

**Issue by chen-png** [zephyrproject-rtos/zephyr#17794]
**Describe the bug**
The timeutil_api test fails with sanitycheck on iotdk board. We are seeing the error message of "gmtime disagreed with gmtime_r".

**To Reproduce**
 ./scripts/sanitycheck -p iotdk --device-testing --device-serial /dev/ttyUSB0 --testcase-root tests/lib/timeutil/ --detailed-report ./test_report.xml

**Screenshots or console output**
JOBS: 8
Cleaning output directory /home/chenpeng/zephyrproject/zephyr/sanity-out
Building testcase defconfigs...
Filtering test cases...
1 tests selected, 190 tests discarded due to filters
total complete:    0/   1   0%  failed:    0

iotdk                     tests/lib/timeutil/libraries.libc.minimal          FAILED: failed
        see: sanity-out/iotdk/tests/lib/timeutil/libraries.libc.minimal/handler.log

total complete:    1/   1  100%  failed:    1
0 of 1 tests passed with 0 warnings in 32 seconds

![image](https://user-images.githubusercontent.com/52983984/61930712-354fb880-afb1-11e9-9fa1-11f755f95607.png)

**Environment (please complete the following information):**
 - OS: Fedora28
 - Toolchain: Zephyr SDk
 - Commit ID: 491702a6c6

**Comment by IRISZZW** [comment]
in test_gmtime function[test_gmtime.c], struct tm tm is a uninitialized local variable. and tm.tm_isdst is never used. so the value of tm.tm_isdst is inscrutable.
and struct tm *tp is pointed to a static static struct tm shared which defined in gmtime function[gmtime.c]. although shared.tm_isdst is never used, but it will initialize to 0 by z_bss_zero function.

**Comment by ioannisg** [comment]
@chen-png @IRISZZW  I wonder if you could quickly check the provided bug-fix PR, #17889 and see if it solves this issue.

**Comment by chen-png** [comment]
Yes, the bug-fix PR #17889 has sloved this issue. Thanks.
