### ISSUE TITLE
Mesh Bug on access.c

### ISSUE THREAD

**Issue by menglingao1997** [zephyrproject-rtos/zephyr#17821]
# On line 235 in access.c

```c
if(pub->count)
{
    k_delayed_work_cancel(&pub->timer);
}
```

## description

when call bt_mesh_model_publish function in application, and use retransmit, for example,use pub->count not equal zero. so first bt_mesh_model_publish call from app, and mod_publish will be call after Publish Period timer time out, when count minus one and equal zero, the mod_publish func will call bt_mesh_model_publish again, when result is success, so the publish->count with reset, but In the above code, we see that when count is not zero, the timer is canceled, so how to continue publish?

**Comment by jhedberg** [comment]
The timer will be reset through the `publish_sent()` callback in `access.c` which gets called when the PDU has been transmitted. Is this again a GATT-related issue? In that case `bt_mesh_net_send()` calls the callback synchronously, meaning the branch you've mentioned above would indeed cancel this. That said, why would you be using retransmissions for GATT? That doesn't make sense to me.

**Comment by jhedberg** [comment]
That said, the call to `k_delayed_work_cancel()` does look redundant to me - perhaps it was needed before but some refactoring eliminated the need for it. I'm still looking through the code to verify this.
