### ISSUE TITLE
Mesh  bug report In access.c

### ISSUE THREAD

**Issue by menglingao1997** [zephyrproject-rtos/zephyr#17820]
hello everyone:
 When I first call bt_mesh_model_publish on access.c and do not use retransmission, the internal call to pub_send_cb.publish_send, the next_period function is executed, and the pub->period_start state is not initialized, which may cause a malfunction.

## Suggest：

* Add conditional judgments in bt_mesh_model_publish, for example:
```c
if(!pub->count)
{
    pub->period_start=k_uptime_get32();
}
```
* remove pub->period_start=k_uptime_get32 in mod_publish func.

**Comment by aescolar** [comment]
CC @jhedberg @Vudentz

**Comment by carlescufi** [comment]
@jhedberg @trond-snekvik can you comment on this one?

**Comment by jhedberg** [comment]
This does look like a potential bug to me. Still looking at the code to confirm it and figure out whether your proposal is the right fix or not.
