### ISSUE TITLE
x86: update mmustructs.h and x86_mmu.c to support long mode

### ISSUE THREAD

**Issue by andrewboie** [zephyrproject-rtos/zephyr#17832]
arch/x86/include/ia32/mmustructs.h contains all the definitions for page tables. x86_mmu.c has the code for managing page tables.

Right now, this only implements page tables for PAE on 32-bit x86. Need to add support for 64-bit page tables as well. I think the following needs to be done:

1. X86_MMU_GET_* macros should take a pdpt pointer for PAE, and a pml4 pointer for long mode
2. When long mode enabled, need a definition for PDPTEs which specify a 1GB area, instead of a page directory. Need a container union similar to union x86_mmu_pde.
3. When long mode enabled, need a X86_MMU_GET_PDPT_ADDR() macro
4. Need some ifdefs for the different fields in all the page table structure when long mode is enabled
5. Need MMU_*_MASK macros for both types of PDPT, and PML4
6. Our new coding guidelines don't allow anonymous unions. Remove all the value fields in the table entry structures, and instead create some inline functions to convert table entries into u64_t values.
7. We have lots of APIs which take a PDPT but what they really need is the toplevel pointer to all the page tables, likely need to introduce some typedef

Also need to up-level x86_mmu.c so that it works in long mode.

**Comment by gnuless** [comment]
@andrewboie I dunno how far along you are in this (if at all), but a shortcut here would be to assume everything we want to physically address is <= 512GB, and then use a "fixed" PML4 for each CPU and just change its first entry before "reloading" CR3.  I see little reason to expand the logic to 4 levels -- if we do want to use all 4, I'd suggest maybe we take advantage of the fact that page tables are recursive structures.

**Comment by andrewboie** [comment]
> @andrewboie I dunno how far along you are in this (if at all), but a shortcut here would be to assume everything we want to physically address is <= 512GB, and then use a "fixed" PML4 for each CPU and just change its first entry before "reloading" CR3. I see little reason to expand the logic to 4 levels -- if we do want to use all 4, I'd suggest maybe we take advantage of the fact that page tables are recursive structures.

I'm just starting, but this sounds like a good idea. I'm currently adding structure definitions and ifdefs to mmustructs.h for long mode and cleaning up some cruft.

**Comment by andrewboie** [comment]
> @andrewboie I dunno how far along you are in this (if at all), but a shortcut here would be to assume everything we want to physically address is <= 512GB, and then use a "fixed" PML4 for each CPU and just change its first entry before "reloading" CR3. I see little reason to expand the logic to 4 levels -- if we do want to use all 4, I'd suggest maybe we take advantage of the fact that page tables are recursive structures.

I didn't get this far. Right now we just generate a single get of page tables (or two if KPTI is turned on).

Back when I was implementing per-thread page tables for 32-bit, I considered having a master PDPT and just updating pointers to the first PDE when switching between threads. I decided not to do it at the time because it would make the switching more complex than a simple cr3 update.
