### ISSUE TITLE
state DEVICE_PM_LOW_POWER_STATE of Device Power Management

### ISSUE THREAD

**Issue by wentongwu** [zephyrproject-rtos/zephyr#17838]
Currently Device Power Management only support state DEVICE_PM_ACTIVE_STATE and DEVICE_PM_SUSPEND_STATE. And DEVICE_PM_SUSPEND_STATE will be triggered when system will enter into deep sleep state. But for non deep sleep state, device power management will not be considered. State of DEVICE_PM_LOW_POWER_STATE requires less time than DEVICE_PM_SUSPEND_STATE, so I suggest to schedule state DEVICE_PM_LOW_POWER_STATE for devices when system will suspend but not deep sleep.

**Comment by wentongwu** [comment]
@pizi-nordic could you please give some comments, thanks a lot.

**Comment by wentongwu** [comment]
Consider more, in the documentation we claim support DEVICE_PM_LOW_POWER_STATE, DEVICE_PM_SUSPEND_STATE, DEVICE_PM_OFF_STATE, DEVICE_PM_ACTIVE_STATE states, when system going to suspend state, we let device driver decide himself's state based on the system idle ticks, and then system will make the final decision based on every device's feedback. 
@pizi-nordic could you please take a look this issue and give some comments? Thanks

**Comment by pizi-nordic** [comment]
@wentongwu: Hi. I apologize for the delay. I already looked at your PR.

**Comment by wentongwu** [comment]
> @wentongwu: Hi. I apologize for the delay. I already looked at your PR.

@pizi-nordic no problem, thanks for the review.
