### ISSUE TITLE
[zephyr 1.14]  Database Out of Sync error is not returned as expected

### ISSUE THREAD

**Issue by MariuszSkamra** [zephyrproject-rtos/zephyr#17882]
**Describe the bug**
In test case GATT/SR/GAS/BV-05-C, step 8 the Database Out of Sync error is not returned as expected on GATT Characteristic Value Read after, the Zephyr GATT database changed.

**To Reproduce**
0. Set TPSX_iut_device_name_in_adv_packet_for_random_address = tester
1. Run bluetooth/shell application
2. bt init
3. gatt register
4. bt clear all (as requested by PTS)
5. gatt metrics on/off (Add/Remove GATT Metrics service)

**Expected behavior**
Test Case pass

**Impact**
Qualification test case GATT/SR/GAS/BV-05-C is failing

**Additional context**
https://github.com/zephyrproject-rtos/zephyr/pull/17884
This PR extends GATT shell functionality with needed prerequisites and verification for this test case

**Comment by Vudentz** [comment]
Hmm maybe you just want to toggle the metrics so that guarantees a new hash is generated, I can have a look tomorrow.

**Comment by Vudentz** [comment]
It does look like we are reseting change-aware flag which should trigger the right error, so we may need some logs here.

**Comment by MariuszSkamra** [comment]
it appeared to be 'registered' flag not be cleared when calling "gatt metrics off"
