### ISSUE TITLE
k_busy_wait not working when using 32KHz timer driver

### ISSUE THREAD

**Issue by albertofloyd** [zephyrproject-rtos/zephyr#17897]
k_busy_wait results in inaccurate delays causing MEC1501 I2C driver to always report timeout.
This breaks I2C tests in this board. 

**To Reproduce**
1. mkdir build; cd build
2.  cmake -DBOARD=mec15xxevb_assy6853 
3. make

**Expected behavior**
k_busy_wait should result in expected delays. 

**Impact**
This affects behavior from drivers relaying in k_busy_wait.
Additionally usage of I2C driver cause most tests to fail

**Additional context**

**Comment by andrewboie** [comment]
@scottwcpg would be the best person to work on this

**Comment by andyross** [comment]
Updating for posterity: this is a @scottwcpg bug, but alas we can't assign it to him because he's not administratively added to the  github project yet.

**Comment by MaureenHelm** [comment]
> Updating for posterity: this is a @scottwcpg bug, but alas we can't assign it to him because he's not administratively added to the github project yet.

Invite sent to @scottwcpg

**Comment by pabigot** [comment]
See #15707 for how this was handled in Nordic.

**Comment by albertofloyd** [comment]
This has been fixed as part of https://github.com/zephyrproject-rtos/zephyr/pull/18318
Will close when that's merged
