### ISSUE TITLE
Is POSIX I/O supported on peripheral?

### ISSUE THREAD

**Issue by qiutongs** [zephyrproject-rtos/zephyr#17956]
**Is your feature request related to a problem? Please describe.**
I want to know if zephyr supports POSIX I/O on any peripherals, like UART, I2C, SPI.
From what I find in the source code, it seems zephyr only has POSIX I/O for file system but not peripherals. Can you confirm this in case I miss anything?

**Describe the solution you'd like**
If what I find is true, is there any plan that zephyr will support POSIX I/O on peripherals?

**Describe alternatives you've considered**
N/A

**Additional context**
My reference: https://github.com/zephyrproject-rtos/zephyr/tree/master/lib/posix

**Comment by andrewboie** [comment]
Currently there is no generic file descriptor access to Zephyr peripherals, you need to use the driver subsystem APIs to interact with them.

I know of no current plans to change this.

**Comment by qiutongs** [comment]
Thanks for confirmation.
