### ISSUE TITLE
drivers/pwm/pwm_api test failed on frdm_k64f board.

### ISSUE THREAD

**Issue by chen-png** [zephyrproject-rtos/zephyr#17967]
**Describe the bug**
Running suite pwm_basic_test on frdm_k64f board, it failed on the pwm_cycle test, we can see the error message "Fail to set the period and pulse width".

**To Reproduce**
1. west build -b frdm_k64f -p=auto tests/drivers/pwm/pwm_api/
2. west flash

**Screenshots or console output**
![image](https://user-images.githubusercontent.com/52983984/62352532-f4205100-b53a-11e9-9223-574df67be9b0.png)

**Environment (please complete the following information):**
 - OS: Fedora28
 - Toolchain: Zephyr-SDK-0.10.1
 - Commit ID: 14db558939d

**Comment by MaureenHelm** [comment]
Hi @chen-png , please have a look at #18203 and confirm if it fixes the issue for you.

**Comment by chen-png** [comment]
> Hi @chen-png , please have a look at #18203 and confirm if it fixes the issue for you.

OK, the PR#18203 has fixed this issue and the tests/drivres/pwm/pwm_api test run successfully on frdm_k64f board now. Thanks.
