### ISSUE TITLE
BLE Mesh When IV update test procedure

### ISSUE THREAD

**Issue by menglingao1997** [zephyrproject-rtos/zephyr#17990]
https://github.com/zephyrproject-rtos/zephyr/blob/0440a815a91b83bdb27e272b9770f558c1b8975c/subsys/bluetooth/mesh/net.c#L672-L678

When `CONFIG_BT_MESH_IV_UPDATE_TEST` not enable, and `BT_MESH_IVU_TEST` flag is enable, must ignore the limit of IV duration.but just as above code show, does not meet specifications.

**Comment by aescolar** [comment]
CC @jhedberg

**Comment by jhedberg** [comment]
The `BT_MESH_IVU_TEST` flag can only be changed using the `bt_mesh_iv_update_test()` API, and that API is only available when `CONFIG_BT_MESH_IV_UPDATE_TEST=y`, so I don't see any issue here - the flag cannot be set if the Kconfig isn't also set.

**Comment by menglingao1997** [comment]
> The `BT_MESH_IVU_TEST` flag can only be changed using the `bt_mesh_iv_update_test()` API, and that API is only available when `CONFIG_BT_MESH_IV_UPDATE_TEST=y`, so I don't see any issue here - the flag cannot be set if the Kconfig isn't also set.

You are right,I mistake.
