### ISSUE TITLE
Dead link in documentation

### ISSUE THREAD

**Issue by asbjornsabo** [zephyrproject-rtos/zephyr#18009]
In the page https://docs.zephyrproject.org/latest/guides/tools/nordic_segger.html
there is a dead link (gives a 404).
The erroneous link is
https://www.nordicsemi.com/Software-and-Tools/Development-Tools/nRF5-Command-Line-Tools 
It is found in the section "nRF5x Command-Line Tools Installation" and in the section "References"

The correct link seems to be
https://www.nordicsemi.com/Software-and-Tools/Development-Tools/nRF-Command-Line-Tools/

(The difference is the removal of a "5" from "nRF5")

**Comment by carlescufi** [comment]
thanks @asbjornsabo, I will send a PR
