### ISSUE TITLE
why kconfiglib.py doesn't throw error for file drivers/serial/Kconfig.nrfx

### ISSUE THREAD

**Issue by wentongwu** [zephyrproject-rtos/zephyr#18029]
in file drivers/serial/Kconfig.nrfx, there is  config NRFX_TIMER0 default y, and it's defined without a type. @ulfalizer

**Comment by wentongwu** [comment]
I found the reason, thanks everyone. Thanks

**Comment by ulfalizer** [comment]
Yeah, it's defined in two locations. One of them gives the type.

**Comment by wentongwu** [comment]
> Yeah, it's defined in two locations. One of them gives the type.

Thanks

**Comment by kqian0327** [comment]
mute the thread

发自我的 iPhone
