### ISSUE TITLE
It's impossible to build Zephyr via cmake/make with west 0.6.0 installed

### ISSUE THREAD

**Issue by PiotrZierhoffer** [zephyrproject-rtos/zephyr#18034]
**Describe the bug**
If not cloning using west (but just regular git clone), it's impossible to build with the usual cmake/make commands.

**To Reproduce**
1. git clone https://github.com/zephyrproject-rtos/zephyr
2. cd samples/hello_world
3. mkdir build; cd build
2. cmake -DBOARD=sam_e70_xplained #or any other
3. make
4. See error: `FATAL ERROR: no west installation found from ".../zephyr/samples/hello_world/build"; "west list" requires one.`

**Comment by aescolar** [comment]
CC: @mbolivar

**Comment by carlescufi** [comment]
`west` is required upstream because of modules. Unless you provide a list of modules separately, you need to have west installed. This is not a bug.

**Comment by carlescufi** [comment]
If you really want to build without west then you need to provide CMake with a `ZEPHYR_MODULES` variable: https://docs.zephyrproject.org/latest/guides/modules.html

**Comment by PiotrZierhoffer** [comment]
The documentation you pointed to explicitly says it's fine not to use modules:

> If you don’t have west installed and don’t specify ZEPHYR_MODULES yourself, then no additional modules are added to the build. You will still be able to build any applications that don’t require code or Kconfig options defined in an external repository.

**Comment by PiotrZierhoffer** [comment]
The main problem comes from the change in the error message that is filtered out in Zephyr build system. Please take a look at the PR I suggested.

**Comment by carlescufi** [comment]
> The main problem comes from the change in the error message that is filtered out in Zephyr build system. Please take a look at the PR I suggested.

Yep, sorry for the noise, I confused the root cause of the issue.
