### ISSUE TITLE
Only corporate members can join the slack channel

### ISSUE THREAD

**Issue by olofj** [zephyrproject-rtos/zephyr#18042]
Right now it seems that only people with certain corporate email addresses can join the slack channel. Given that slack is communicated as an official support channel, this seems like a bug.

At the very least, it should have information to how you get invited to the workspace if you have a Slack account under another email address.

Current login page says:

If you have an @intel.com, @linaro.com, @linux.intel.com, @nordicsemi.no, @nxp.com, @oticon.com, @foundries.io, @ti.com, @synopsys.com, @antmicor.com, or @sifive.com email address, you can create an account.

**Comment by carlescufi** [comment]
I fixed this yesterday I believe, see the invite link in the GitHub doc: https://tinyurl.com/y5glwylp I also updated the link in the doc, it might not be updated yet on the website

**Comment by olofj** [comment]
Fantastic, thanks!

**Comment by scttnlsn** [comment]
It seems as though this invite link is no longer working:

```
Secure Connection Failed

An error occurred during a connection to tinyurl.com. PR_END_OF_FILE_ERROR

    The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
    Please contact the website owners to inform them of this problem.
```

**Comment by schneider42** [comment]
The link posted above is also on the website: https://www.zephyrproject.org/contact-us/

It does lead to slack, but the invitation is not working:

![Screenshot from 2021-09-15 15-52-09](https://user-images.githubusercontent.com/452051/133446200-e3d62799-fa4f-4814-9187-8c7d7ab3f26a.png)

**Comment by schneider42** [comment]
Never mind: Discord is the new Slack: https://lists.zephyrproject.org/g/users/message/2702
