### ISSUE TITLE
BT Host: Advertising Extensions - Periodic Advertisement

### ISSUE THREAD

**Issue by aescolar** [zephyrproject-rtos/zephyr#18045]
The host needs to support the HCI commands related to Periodic Advertisement

This can be upstreamed as it is in already adopted spec. (Bluetooth Core Specification 5.0)

- [x] hci_core.c implementations
- [x] bluetooth.h API
- [x] bt.c shell support
- [x] Kconfig options

**Comment by Emil-Gydesen-Bose** [comment]
For those interested, the work in progress can be following at https://github.com/Emil-Gydesen-Bose/zephyr/tree/per_adv.
