### ISSUE TITLE
BT Host: Advertising Extensions - Advertiser

### ISSUE THREAD

**Issue by aescolar** [zephyrproject-rtos/zephyr#18047]
The host needs to support the HCI commands related to Advertising Extensions as an advertiser. If talking to a controller with support these will have to be used instead of the Bluetooth 4.0 commands for advertising

This can be upstreamed as it is in already adopted spec. (Bluetooth Core Specification 5.0)

**Comment by dleach02** [comment]
We seem to keep moving this down the release chain. Is this something that is actively being worked?

**Comment by jhedberg** [comment]
> We seem to keep moving this down the release chain. Is this something that is actively being worked?

@dleach02 AFAIK @joerchan has been working on it and should be submitting a draft PR soon. Actually, should this be reassigned from @carlescufi to @joerchan ?

**Comment by joerchan** [comment]
Assigned myself and put them in progress.

**Comment by carlescufi** [comment]
Covered by #18050
