### ISSUE TITLE
BT Host: Advertising Extensions - Scanner

### ISSUE THREAD

**Issue by aescolar** [zephyrproject-rtos/zephyr#18046]
The host needs to support the HCI commands related to Advertising Extensions as a scanner. If talking to a controller with AE support these will have to be used instead of the Bluetooth 4.0 commands for Scanning

This can be upstreamed as it is in already adopted spec. (Bluetooth Core Specification 5.0)

**Comment by carlescufi** [comment]
Covered by #18050
