### ISSUE TITLE
BT Host - Advertisement extensions support

### ISSUE THREAD

**Issue by aescolar** [zephyrproject-rtos/zephyr#18050]
Issue to keep track of advertisement extensions support in the host

**Comment by kapi-no** [comment]
Could you also fix the problem of starting an advertiser when Host has run out of connection objects as part of this task?

**Comment by carlescufi** [comment]
> Could you also fix the problem of starting an advertiser when Host has run out of connection objects as part of this task?

I think this is different @kapi-no. I suggest @joerchan takes a look at this separately.

**Comment by joerchan** [comment]
@carlescufi We have discussed this on slack,and there is a change that we have decided to take as part of the AE work that would fix the issue mentioned. which is why @kapi-no added the reminder for it.
