### ISSUE TITLE
k_busy_wait passed milliseconds instead of microseconds

### ISSUE THREAD

**Issue by jimparis** [zephyrproject-rtos/zephyr#18059]
These bugs have popped up after #11935 was fixed:

```$ egrep -r 'k_busy_wait.*K_M?SEC' .
./samples/net/zperf/src/zperf_udp_uploader.c:		k_busy_wait(K_MSEC(100));
./samples/net/zperf/src/zperf_tcp_uploader.c:		k_busy_wait(K_MSEC(100));
./samples/subsys/usb/hid-cdc/src/main.c:	k_busy_wait(K_SECONDS(1));
```
@masz-nordic @jukkar

**Comment by FERASMANASEER** [comment]
./samples/net/zperf/src/zperf_udp_uploader.c:		k_busy_wait(K_MSEC(100));
./samples/net/zperf/src/zperf_tcp_uploader.c:		k_busy_wait(K_MSEC(100));
./samples/subsys/usb/hid-cdc/src/main.c:	k_busy_wait(K_SECONDS(1));
