### ISSUE TITLE
LWM2M bootstrap issue

### ISSUE THREAD

**Issue by rlubos** [zephyrproject-rtos/zephyr#18080]
I'm not sure if the issue I describe here is a bug report or my misunderstanding, hence not marking it as a bug yet. The documentation is quite scarce on how to initiate the bootstrap with the LWM2M library so I might miss some information.

I've tried to run the LWM2M bootstrap in the `lwm2m_client` sample, using local LWM2M bootstrap server (`leshan-bsserver-demo.jar` from the same source as the `leshan-server-demo.jar` from docs). What I did (all w/o security enabled):
1.  Started the local BS server instance at port 5683, along with local LWM2M server instance at port 5783.
2. Configured the BS server with client endpoint name (`qemu_x86`) and local LWM2M server address (`coap://localhost:5783`)
3. Enabled bootstrap support in the sample (`CONFIG_LWM2M_RD_CLIENT_SUPPORT_BOOTSTRAP`) and increased the maximum number of security and server object instances.
4. Configured the security object, to indicate it points to a bootstrap server (`lwm2m_engine_set_u8("0/0/1", 1);`)

After this, I was able to initiate the LWM2M bootstrap procedure, yet the client was not able to finalize it.  It seems, that the procedure that should set the appropriate state in the state machine (`engine_bootstrap_finish()`) is not called anywhere.  When the server sent the Bootstrap-finish message, the client replied with 4.04 Not Found. This clearly indicates that I miss a handler for the `Bootstrap-finish` message. 

![image](https://user-images.githubusercontent.com/22167799/62616915-f3a80180-b910-11e9-9b15-acc1386de76e.png)

So my question is, is the `Bootstrap-finish` handler supposed to be present in LWM2M engine and we miss it or is the application supposed to provide it and register it somehow with LWM2M on its own?

Also, I have a side question regarding client deregistration - is it possible to deregister a LWM2M server with current implementation? I saw there is an `ENGINE_DEREGISTER` state which seems to handle the deregistration procedure, yet I've seen no way to set this state. Is it possible to trigger deregistration from the application somehow?

**Comment by mike-scott** [comment]
@rlubos It's probably a bug :)  I will run some tests today.

**Comment by mike-scott** [comment]
So by "today" I meant "9 days from now".  Looking at this now.
