### ISSUE TITLE
getting_started should indicate upgrade rather than just install west

### ISSUE THREAD

**Issue by egcd32** [zephyrproject-rtos/zephyr#18132]
**Describe the bug**
Following the instructions in https://docs.zephyrproject.org/latest/getting_started/index.html 
to 
pip3 install west
followed by 
west init zephyrproject
on a system where west 0.5.8 was previously installed (from several months ago following the getting started with zephyr), the west init zephyrproject fails partway through. The error message indicates that something is looking for a west subcommand that doesn't exist. This is because  Zephyr is requiring west 0.6.0 to init, but 'pip3 install west' was fine and did not make any change if west 0.5.8 was already installed.

**To Reproduce**
Install west 0.5.8.  This was from follow the quickstart instructions before July 2019, resulting in west 0.5.8 being installed.
Create a new directory and type 
pip3 install west
west init zephyrproject
Watch it fail partway through because Zephyr is expecting a subcommand added in west 0.6.0.

**Expected behavior**
The instructions in doc/getting_started/index.rst would have been to do 
   # Linux
   pip3 install -U --user west

   # macOS (Terminal) and Windows (cmd.exe)
   pip3 install -U west

which I believe would upgrade west, if already installed, and install the latest version if not already installed.

**Impact**
Annoyance. It wasn't obvious when west init fails that it is a problem with west rather than with the zephyr sources.

**Screenshots or console output**

**Environment (please complete the following information):**
 - OS: Windows 10

**Comment by aescolar** [comment]
@mbolivar @carlescufi
