### ISSUE TITLE
Cleanup dts compatible for "nxp,kinetis-sim" on nxp_ke1xf

### ISSUE THREAD

**Issue by galak** [zephyrproject-rtos/zephyr#18160]
"nxp,kinetis-sim" is used in the following dtsi files:

```
dts/arm/nxp/nxp_k6x.dtsi:                       compatible = "nxp,kinetis-sim";
dts/arm/nxp/nxp_ke1xf.dtsi:                     compatible = "nxp,kinetis-sim";
dts/arm/nxp/nxp_kl25z.dtsi:                     compatible = "nxp,kinetis-sim";
dts/arm/nxp/nxp_kw2xd.dtsi:                     compatible = "nxp,kinetis-sim";
dts/arm/nxp/nxp_kw40z.dtsi:                     compatible = "nxp,kinetis-sim";
dts/arm/nxp/nxp_kw41z.dtsi:                     compatible = "nxp,kinetis-sim";
```

However nxp_ke1xf.dtsi is the only one what doesn't use it as a clock controller.  The HW is a little different and as such we should use a different compatible for it on nxp_ke1xf.

**Comment by henrikbrixandersen** [comment]
@galak Could you please elaborate a bit on why a different `compatible` is needed? What problem does the current solution pose?

**Comment by galak** [comment]
> @galak Could you please elaborate a bit on why a different `compatible` is needed? What problem does the current solution pose?

The idea with compatible is that it should be used if the software/programming model is the same for the HW.  While I'm guessing the manual's call the block SIM on all the Kinetis SoC's, it seems as if the way clocks and SIM work differ greatly between the KE1XF and other SoC's.  As such we should use a slightly different compatible on KE1XF.

Such as "nxp,kinetis-ke1xf-sim" and introduce a binding specific to it.

**Comment by galak** [comment]
Got a patch in progress
