### ISSUE TITLE
BLE Mesh When Provisioning Use Input OOB Method

### ISSUE THREAD

**Issue by menglingao1997** [zephyrproject-rtos/zephyr#18178]
**FUNCTION1**
https://github.com/zephyrproject-rtos/zephyr/blob/4524035bc8d5e8eb892bccc1ce9547b09e9c7f52/subsys/bluetooth/mesh/prov.c#L866-L907

**FUNCTION2**
https://github.com/zephyrproject-rtos/zephyr/blob/4524035bc8d5e8eb892bccc1ce9547b09e9c7f52/subsys/bluetooth/mesh/prov.c#L828-L864

According to the specification,device use input oob method when provisioning.Once input of the number has been performed,the device shall send the provisioning input complete pdu to the provisioner to confirm that device has an input value.Then confirmation of provisioner and device followed exchange.

**So,the provisioning input complete pdu is send before confirm value of provisioner.**

In the **FUNCTION1**,when sended public key,
``` C
        atomic_set_bit(link.flags, SEND_CONFIRM); 
 	link.expect = PROV_CONFIRM; 
```
when user input complete on the device side, call **FUNCTION2**, but at this function the confirm pdu were sent while sending the input completion pdu.

```C
        if (atomic_test_and_clear_bit(link.flags, SEND_CONFIRM)) { 
 		send_confirm(); 
 	} 
```

**Comment by aescolar** [comment]
CC @jhedberg
