### ISSUE TITLE
Unable to reconnect paired devices with controller privacy disabled (host privacy enabled)

### ISSUE THREAD

**Issue by mtpr-ot** [zephyrproject-rtos/zephyr#18306]
**Description**
With host privacy enabled and controller privacy disabled, it is not possible to re-connect to a paired device.

**To Reproduce**
_Preconditions:_
CONFIG_BT_PRIVACY=y
CONFIG_BT_CTLR_PRIVACY=n

Peripheral advertises constantly. Central scans, connects, disconnects and then scans and finally attempts to re-connect. At second attempt:
- Scanner scans for ADV packets, sees our peripheral by random address and sends scan report
- In the host layer, the advertiser address is looked up and a key is found
- The random address is translated to public address and app is notified
- The app takes the public address of the advertiser and initiates a connection
- The scanner receives connection information containing the public address
- Scanner waits forever for a match between received random address and the public address from app

**Expected behavior**
Central and peripheral should connect every time.

**Impact**
Unable to connect after devices have paired.

**Environment (please complete the following information)**
 - Zephyr 2.0 RC1

**Comment by aescolar** [comment]
@joerchan This seems like a regression. But please remove the label if it is not.

**Comment by joerchan** [comment]
Yes, regression from here: 45da629b24f720019355fca8e1ddddb798ac409f
