### ISSUE TITLE
tests/drivers/can/api/peripheral.can fail on FRDM-K64F

### ISSUE THREAD

**Issue by galak** [zephyrproject-rtos/zephyr#18320]
**Describe the bug**
Test timesout in `test_set_loopback`

This is all the output we get:
```
***** Booting Zephyr OS build v2.0.0-rc1-63-g25a9cde22349 *****
Running test suite can_driver
===================================================================
starting test - test_set_loopback
```

**To Reproduce**
`scripts/sanitycheck -p frdm_k64f --device-testing --device-serial /dev/ttyACM0 -s tests/drivers/can/api/peripheral.can`

**Comment by galak** [comment]
The issue appears to be in `FLEXCAN_Enable()`.  When its called to disable the FLEXCAN, we spin for ever waiting on the hardware to go to low power mode:

```
while (!(base->MCR & CAN_MCR_LPMACK_MASK))
```

**Comment by galak** [comment]
This also appears related to reset in some form.

**Comment by alexanderwachter** [comment]
This issue can occur when the CAN0_RX pin is floating. The low-power-mode can only be switched when the controller is idling. The bus is in the recessive state (idling) when the RX pin is logical high.
