### ISSUE TITLE
Is there a way to get the bytes that shell receives?

### ISSUE THREAD

**Issue by lucaspeixotot** [zephyrproject-rtos/zephyr#18345]
I'm using shell in UART2 but I need that the bytes in this interface be redirected to a msg queue in my firmware. How can I do that?

**Comment by carlescufi** [comment]
All of the bytes? If you only need specific sequences and use some SLIP code of some sort you can use the mcumgr hooks. Search for MCUMGR in the shell code

**Comment by jakub-uC** [comment]
Hi,
It is not possible from the command context to get all bytes received by the shell. The command is already trimmed and escape codes are handled (if activated in Kconfig).
