### ISSUE TITLE
[Coverity CID :203466]Memory - illegal accesses in /drivers/can/can_mcux_flexcan.c

### ISSUE THREAD

**Issue by aasthagr** [zephyrproject-rtos/zephyr#18355]
Static code scan issues seen in File: /drivers/can/can_mcux_flexcan.c
 Category: Memory - illegal accesses
 Function: mcux_flexcan_send
 Component: Drivers
 CID: 203466
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by alexanderwachter** [comment]
CID 203466 (#4 of 4): Out-of-bounds read (OVERRUN)10. overrun-local: Overrunning array data->tx_cbs of 11 52-byte elements at element index 11 (byte offset 623) using index alloc (which evaluates to 11).

Line 218

**Comment by henrikbrixandersen** [comment]
That should be safe to ignore. The counting semaphore will ensure that this can never happen.

**Comment by alexanderwachter** [comment]
Set coverty state to „ignore“
