### ISSUE TITLE
[Coverity CID :203449]Memory - illegal accesses in /boards/posix/native_posix/cmdline_common.c

### ISSUE THREAD

**Issue by aasthagr** [zephyrproject-rtos/zephyr#18354]
Static code scan issues seen in File: /boards/posix/native_posix/cmdline_common.c
 Category: Memory - illegal accesses
 Function: cmd_read_option_value
 Component: Other
 CID: 203449
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by aescolar** [comment]
False positive, due to static analysis tool not knowing `posix_print_error_and_exit` never returns => lowering priority
Will fix nontheless
