### ISSUE TITLE
[Coverity CID :203492]Memory - corruptions in /drivers/net/ppp.c

### ISSUE THREAD

**Issue by aasthagr** [zephyrproject-rtos/zephyr#18363]
Static code scan issues seen in File: /drivers/net/ppp.c
 Category: Memory - corruptions
 Function: ppp_driver_feed_data
 Component: Networking
 CID: 203492
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by jukkar** [comment]
False positive.
