### ISSUE TITLE
[Coverity CID :203412]Control flow issues in /drivers/net/ppp.c

### ISSUE THREAD

**Issue by aasthagr** [zephyrproject-rtos/zephyr#18362]
Static code scan issues seen in File: /drivers/net/ppp.c
 Category: Control flow issues
 Function: ppp_send
 Component: Networking
 CID: 203412
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by jukkar** [comment]
False positive.
