### ISSUE TITLE
[Coverity CID :203531]Memory - corruptions in /drivers/espi/espi_mchp_xec.c

### ISSUE THREAD

**Issue by aasthagr** [zephyrproject-rtos/zephyr#18360]
Static code scan issues seen in File: /drivers/espi/espi_mchp_xec.c
 Category: Memory - corruptions
 Function: espi_xec_send_vwire
 Component: Drivers
 CID: 203531
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by galak** [comment]
Not a bug, this is due to how register access/pointer math is working.
