### ISSUE TITLE
[Coverity CID :203440]Null pointer dereferences in /samples/net/nats/src/main.c

### ISSUE THREAD

**Issue by aasthagr** [zephyrproject-rtos/zephyr#18375]
Static code scan issues seen in File: /samples/net/nats/src/main.c
 Category: Null pointer dereferences
 Function: nats_client
 Component: Samples
 CID: 203440
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by jukkar** [comment]
False positive.
