### ISSUE TITLE
[Coverity CID :203537]Error handling issues in /samples/subsys/nvs/src/main.c

### ISSUE THREAD

**Issue by aasthagr** [zephyrproject-rtos/zephyr#18378]
Static code scan issues seen in File: /samples/subsys/nvs/src/main.c
 Category: Error handling issues
 Function: main
 Component: Samples
 CID: 203537
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by aescolar** [comment]
from b1e45b413ef #6391

**Comment by jenmwms** [comment]
This looks 'Fixed' in the report page (link below). Can someone confirm? @aasthagr 
https://scan9.coverity.com/reports.htm#v39298/p12996/fileInstanceId=55470800&defectInstanceId=6797685&mergedDefectId=203537

**Comment by Laczen** [comment]
Hi @jenmwms, this is not really an issue. However if you would like to fix it completely all calls of nvs_write() or nvs_delete() that are not using the return value can be changed to `(void)nvs_write` and `(void)nvs_delete`.

**Comment by jenmwms** [comment]
Thanks @Laczen!

**Comment by jenmwms** [comment]
I contemplated a patch that checked the return values, but it is bulky and checking the return in that context does not appear to add value. So it is cleaner to simply change those few calls to (void).
