### ISSUE TITLE
[Coverity CID :203543]Memory - illegal accesses in /samples/bluetooth/eddystone/src/main.c

### ISSUE THREAD

**Issue by aasthagr** [zephyrproject-rtos/zephyr#18372]
Static code scan issues seen in File: /samples/bluetooth/eddystone/src/main.c
 Category: Memory - illegal accesses
 Function: write_adv_data
 Component: Samples
 CID: 203543
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by jhedberg** [comment]
Marked as false positive in Coverity

**Comment by aescolar** [comment]
@jhedberg forgot to close?

**Comment by jhedberg** [comment]
> @jhedberg forgot to close?

@aescolar yep, thanks for pointing out
