### ISSUE TITLE
[Coverity CID :203447]Memory - corruptions in /subsys/bluetooth/host/att.c

### ISSUE THREAD

**Issue by aasthagr** [zephyrproject-rtos/zephyr#18383]
Static code scan issues seen in File: /subsys/bluetooth/host/att.c
 Category: Memory - corruptions
 Function: find_type_cb
 Component: Bluetooth
 CID: 203447
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by jhedberg** [comment]
Marked as false positive in Coverity
