### ISSUE TITLE
[Coverity CID :203396]Null pointer dereferences in /subsys/bluetooth/mesh/access.c

### ISSUE THREAD

**Issue by aasthagr** [zephyrproject-rtos/zephyr#18389]
Static code scan issues seen in File: /subsys/bluetooth/mesh/access.c
 Category: Null pointer dereferences
 Function: bt_mesh_model_publish
 Component: Bluetooth
 CID: 203396
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by jhedberg** [comment]
Marked as false positive in Coverity

**Comment by nashif** [comment]
see https://habr.com/en/company/pvs-studio/blog/495284/
