### ISSUE TITLE
[Coverity CID :203545]Memory - corruptions in /subsys/bluetooth/host/smp.c

### ISSUE THREAD

**Issue by aasthagr** [zephyrproject-rtos/zephyr#18388]
Static code scan issues seen in File: /subsys/bluetooth/host/smp.c
 Category: Memory - corruptions
 Function: smp_br_distribute_keys
 Component: Bluetooth
 CID: 203545
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by jhedberg** [comment]
Marked as false positive in Coverity
