### ISSUE TITLE
[Coverity CID :203494]Integer handling issues in /subsys/fs/littlefs_fs.c

### ISSUE THREAD

**Issue by aasthagr** [zephyrproject-rtos/zephyr#18392]
Static code scan issues seen in File: /subsys/fs/littlefs_fs.c
 Category: Integer handling issues
 Function: littlefs_mount
 Component: Other
 CID: 203494
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by alexanderwachter** [comment]
CID 203494 (#1 of 1): Division or modulo by zero (DIVIDE_BY_ZERO)22. divide_by_zero: In expression fs->area->fa_size / block_size, division by expression block_size which may be zero has undefined behavior.

Line 623
