### ISSUE TITLE
[Coverity CID :203441]Null pointer dereferences in /subsys/bluetooth/mesh/transport.c

### ISSUE THREAD

**Issue by aasthagr** [zephyrproject-rtos/zephyr#18390]
Static code scan issues seen in File: /subsys/bluetooth/mesh/transport.c
 Category: Null pointer dereferences
 Function: bt_mesh_heartbeat_send
 Component: Bluetooth
 CID: 203441
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by jhedberg** [comment]
Marked as false positive in Coverity
