### ISSUE TITLE
[Coverity CID :203483]Control flow issues in /subsys/net/lib/conn_mgr/events_handler.c

### ISSUE THREAD

**Issue by aasthagr** [zephyrproject-rtos/zephyr#18400]
Static code scan issues seen in File: /subsys/net/lib/conn_mgr/events_handler.c
 Category: Control flow issues
 Function: conn_mgr_ipv4_events_handler
 Component: Networking
 CID: 203483
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by jukkar** [comment]
@tbursztyka can you check this one, looks like the bits are wrongly checked in the code.
