### ISSUE TITLE
[Coverity CID :203445]Error handling issues in /subsys/net/lib/sockets/getnameinfo.c

### ISSUE THREAD

**Issue by aasthagr** [zephyrproject-rtos/zephyr#18418]
Static code scan issues seen in File: /subsys/net/lib/sockets/getnameinfo.c
 Category: Error handling issues
 Function: zsock_getnameinfo
 Component: Networking
 CID: 203445
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by tbursztyka** [comment]
intentional.

**Comment by jukkar** [comment]
In order to avoid this same warning in the future, we might want to change the code to `(void)snprintf(serv, servlen, "%hu", ntohs(a->sin_port));` in this case. TBDL.
