### ISSUE TITLE
[Coverity CID :203473]Null pointer dereferences in /subsys/usb/usb_descriptor.c

### ISSUE THREAD

**Issue by aasthagr** [zephyrproject-rtos/zephyr#18423]
Static code scan issues seen in File: /subsys/usb/usb_descriptor.c
 Category: Null pointer dereferences
 Function: usb_fix_descriptor
 Component: Other
 CID: 203473
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by dleach02** [comment]
Coverity is flagging that cfg_data is initialized to NULL and is passed to usb_validate_ep_cfg_data() in the USB_ENDPOINT_DESC case statement where a dereference occurs. Not knowing this code, I suspect that the while loop is processing the descriptor and as such it may assume that the bDescriptorType of USB_INTERFACE_DESC is invoked AND the code path routes through the code that initializes cfg_data. 

Looks like a legit bug that should be fixed.
