### ISSUE TITLE
[Coverity CID :203504]Uninitialized variables in /subsys/net/lib/sockets/sockets_net_mgmt.c

### ISSUE THREAD

**Issue by aasthagr** [zephyrproject-rtos/zephyr#18421]
Static code scan issues seen in File: /subsys/net/lib/sockets/sockets_net_mgmt.c
 Category: Uninitialized variables
 Function: znet_mgmt_recvfrom
 Component: Networking
 CID: 203504
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by dleach02** [comment]
This looks like a false hit. The scan is complaining because the nm_msg field of the header was never explicitly initialized. But the 'if (info)' block above this does initialize it in the case that there is 'info' and if there isn't then the length will be set to 0.

**Comment by tbursztyka** [comment]
yep, false positive.
