### ISSUE TITLE
[Coverity CID :203498]Memory - corruptions in /tests/application_development/gen_inc_file/src/main.c

### ISSUE THREAD

**Issue by aasthagr** [zephyrproject-rtos/zephyr#18425]
Static code scan issues seen in File: /tests/application_development/gen_inc_file/src/main.c
 Category: Memory - corruptions
 Function: test_gen_gz_inc_file_no_mtime
 Component: Tests
 CID: 203498
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996/fileInstanceId=53306900&defectInstanceId=6680795&mergedDefectId=203498

**Comment by aescolar** [comment]
@marc-hb from 3061c92aafc

**Comment by nashif** [comment]
marked as fixed in coverity with comment: "Source code is not available because it has been purged."
