### ISSUE TITLE
[Coverity CID :203489]Memory - corruptions in /tests/application_development/gen_inc_file/src/main.c

### ISSUE THREAD

**Issue by aasthagr** [zephyrproject-rtos/zephyr#18424]
Static code scan issues seen in File: /tests/application_development/gen_inc_file/src/main.c
 Category: Memory - corruptions
 Function: test_gen_gz_inc_file_mtime_arg
 Component: Tests
 CID: 203489
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996/fileInstanceId=53306900&defectInstanceId=6681005&mergedDefectId=203489

**Comment by aescolar** [comment]
@marc-hb from 3061c92

**Comment by aescolar** [comment]
Related to #18425

**Comment by marc-hb** [comment]
After a few seconds https://scan9.coverity.com/reports.htm#v32951/p12996 redirects to https://scan9.coverity.com/reports.htm#v38298 which shows a spinning wheel for a few more seconds and then leaves a blank page. The top right corner shows my email address even though I didn't explicitly logged in, at least not in the last few months. The bottom left corner shows "0 projects match". This could be an awkward and falsely "secure" way to tell me I don't have access? I just requested access at https://scan.coverity.com/memberships/new?project_id=zephyr, hope it helps.
