### ISSUE TITLE
[Coverity CID :203424]Control flow issues in /tests/kernel/common/src/sflist.c

### ISSUE THREAD

**Issue by aasthagr** [zephyrproject-rtos/zephyr#18436]
Static code scan issues seen in File: /tests/kernel/common/src/sflist.c
 Category: Control flow issues
 Function: test_sflist
 Component: Tests
 CID: 203424
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by andyross** [comment]
Duplicate of #18566

**Comment by andyross** [comment]
Oops, that was the PR, not the bug.  This is a dup of #18437, which is fixed via #18566.  Closing.
