### ISSUE TITLE
[Coverity CID :203391]Null pointer dereferences in /tests/bluetooth/gatt/src/main.c

### ISSUE THREAD

**Issue by aasthagr** [zephyrproject-rtos/zephyr#18431]
Static code scan issues seen in File: /tests/bluetooth/gatt/src/main.c
 Category: Null pointer dereferences
 Function: test_gatt_read
 Component: Tests
 CID: 203391
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by aescolar** [comment]
@jhedberg
