### ISSUE TITLE
[Coverity CID :203502]Error handling issues in /tests/bluetooth/tester/src/gap.c

### ISSUE THREAD

**Issue by aasthagr** [zephyrproject-rtos/zephyr#18432]
Static code scan issues seen in File: /tests/bluetooth/tester/src/gap.c
 Category: Error handling issues
 Function: le_connected
 Component: Tests
 CID: 203502
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by aescolar** [comment]
@jhedberg

**Comment by jhedberg** [comment]
Marked as false-positive in Coverity
