### ISSUE TITLE
[Coverity CID :203422]Memory - illegal accesses in /tests/subsys/fs/littlefs/src/testfs_util.c

### ISSUE THREAD

**Issue by aasthagr** [zephyrproject-rtos/zephyr#18458]
Static code scan issues seen in File: /tests/subsys/fs/littlefs/src/testfs_util.c
 Category: Memory - illegal accesses
 Function: testfs_path_init
 Component: Tests
 CID: 203422
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by alexanderwachter** [comment]
CID 203422 (#1 of 1): Buffer not null terminated (BUFFER_SIZE_WARNING)4. buffer_size_warning: Calling strncpy with a maximum size argument of 128 bytes on destination array pp->path of size 128 bytes might leave the destination string unterminated.

Line 64
