### ISSUE TITLE
[Coverity CID :203490]Error handling issues in /tests/net/socket/net_mgmt/src/main.c

### ISSUE THREAD

**Issue by aasthagr** [zephyrproject-rtos/zephyr#18455]
Static code scan issues seen in File: /tests/net/socket/net_mgmt/src/main.c
 Category: Error handling issues
 Function: test_net_mgmt_setup
 Component: Tests
 CID: 203490
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by tbursztyka** [comment]
false positive.
