### ISSUE TITLE
[Coverity CID :203480]Null pointer dereferences in /tests/net/context/src/main.c

### ISSUE THREAD

**Issue by aasthagr** [zephyrproject-rtos/zephyr#18453]
Static code scan issues seen in File: /tests/net/context/src/main.c
 Category: Null pointer dereferences
 Function: net_ctx_get_success
 Component: Tests
 CID: 203480
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by tbursztyka** [comment]
false positive. (will wait to get the right to set the cid on ignore to close this issue).
