### ISSUE TITLE
[Coverity CID :203463]Memory - corruptions in /tests/lib/ringbuffer/src/main.c

### ISSUE THREAD

**Issue by aasthagr** [zephyrproject-rtos/zephyr#18452]
Static code scan issues seen in File: /tests/lib/ringbuffer/src/main.c
 Category: Memory - corruptions
 Function: test_ringbuffer_raw
 Component: Tests
 CID: 203463
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by ceolin** [comment]
False positive - `ring_buf_get` calls `ring_buf_get_claim` that checks if the requested size is bigger than available space.

**Comment by nashif** [comment]
please close and mark it as such in coverity :)

**Comment by ceolin** [comment]
have already done it there.
