### ISSUE TITLE
[Coverity CID :203401]Security best practices violations in /tests/net/traffic_class/src/main.c

### ISSUE THREAD

**Issue by aasthagr** [zephyrproject-rtos/zephyr#18456]
Static code scan issues seen in File: /tests/net/traffic_class/src/main.c
 Category: Security best practices violations
 Function: traffic_class_recv_packets_with_prio
 Component: Tests
 CID: 203401
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by jukkar** [comment]
False positive.
