### ISSUE TITLE
[Coverity CID :203419]Security best practices violations in /tests/net/traffic_class/src/main.c

### ISSUE THREAD

**Issue by aasthagr** [zephyrproject-rtos/zephyr#18457]
Static code scan issues seen in File: /tests/net/traffic_class/src/main.c
 Category: Security best practices violations
 Function: traffic_class_send_packets_with_prio
 Component: Tests
 CID: 203419
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by ceolin** [comment]
this is a false positive, `test_data`  is `static const char *test_data = "Test data to be sent"` and `data` is `u8_t data[128];` so, no overrun will happen.
