### ISSUE TITLE
Bluetooth: length variable inconsistency in keys.c

### ISSUE THREAD

**Issue by jhedberg** [zephyrproject-rtos/zephyr#18483]
After commit 94451b22fcc there's an inconsistency with length variable usage:
https://github.com/zephyrproject-rtos/zephyr/blob/c635f4cb6d56492620114ade116c9b85b20bb9e6/subsys/bluetooth/host/keys.c#L339-L341

Is the if-statement wrong in using `len_rd` or is the log message wrong in using `len`?

**Comment by aescolar** [comment]
Unfortunately @fnde-ot is out for the next 2 weeks. But he had left this comment about this: https://github.com/zephyrproject-rtos/zephyr/commit/94451b22fcc6a068de2a2982b202772c6bbefae8#r34438851

**Comment by aescolar** [comment]
@jhedberg ^^

**Comment by aescolar** [comment]
@jhedberg I bounce this issue back at you as we cannot expect @fnde-ot to react any time soon.

**Comment by aescolar** [comment]
Fixed as a sideeffect of #19407
