### ISSUE TITLE
Microchip's MEC1501 HAL is broken (watchdog part)

### ISSUE THREAD

**Issue by tbursztyka** [zephyrproject-rtos/zephyr#18480]
Obvious bug:

ext/hal/microchip/mec/mec1501/component/wdt.h:50:28: error: invalid suffix "u1" on integer constant
 #define MCHP_WDT_CTRL_EN  (1u1 << (MCHP_WDT_CTRL_EN_POS))

And: 
- It lacks of some registers field pos/mask/en macros.
- Naming convention is not consistent either.

**Comment by tbursztyka** [comment]
@scottwcpg please fix.

**Comment by scottwcpg** [comment]
Hi, updated HAL WDT header file in PR 18497.

**Comment by galak** [comment]
Setting the milestone to v2.1.0 as we don't have a watchdog driver in the tree so, this doesn't impact v2.0.0.

**Comment by dcpleung** [comment]
https://github.com/zephyrproject-rtos/hal_microchip/pull/2 fixes this.
