### ISSUE TITLE
BLE: Mesh: when friend send msg to LPN

### ISSUE THREAD

**Issue by menglingao1997** [zephyrproject-rtos/zephyr#18521]
https://github.com/zephyrproject-rtos/zephyr/blob/951b47fab95db493c9469e53a77275312ac6637e/subsys/bluetooth/mesh/friend.c#L1351-L1359

How could a friend node have multiple identical LPNs.
if no space to this msg, should use `break`,such as:
```C
		if (!friend_queue_prepare_space(frnd, rx->ctx.addr, seq_auth,
						seg_count)) {
			break;
		}
```

**Comment by jhedberg** [comment]
@menglingao1997 we use a single buffer pool for all LPNs, but the friend queue size is enforced per-LPN. Some LPN might have multiple SAR sessions causing there not to be enough buffers for it, however another LPN might have enough free buffers (those not allocated to SAR sessions). I'm not sure why you think this is a case about "identical LPNs". If the destination is a group address we need to match it against every LPN.
