### ISSUE TITLE
BLE: Mesh: When transport send seg_msg to LPN

### ISSUE THREAD

**Issue by menglingao1997** [zephyrproject-rtos/zephyr#18522]
https://github.com/zephyrproject-rtos/zephyr/blob/07460176ed9edb731e5ffee775c7c09259ee33d8/subsys/bluetooth/mesh/transport.c#L314-L465
```C
        if (IS_ENABLED(CONFIG_BT_MESH_FRIEND) && 
 	    !bt_mesh_friend_queue_has_space(tx->sub->net_idx, net_tx->src, 
 					    tx->dst, &tx->seq_auth, 
 					    tx->seg_n + 1) && 
 	    BT_MESH_ADDR_IS_UNICAST(tx->dst)) { 
 		BT_ERR("Not enough space in Friend Queue for %u segments", 
 		       tx->seg_n + 1); 
 		seg_tx_reset(tx); 
 		return -ENOBUFS; 
 	} 
```

According to the code above, if I send a **SEG** message (greater than `CONFIG_BT_MESH_FRIEND_QUEUE_SIZE`) to a **UNICAST** Address (not an LPN address),will be cause an abnormality.

I think should add some functions to determine if it is sent to LPN, such as `bt_mesh_friend_match`

**Comment by jhedberg** [comment]
@menglingao1997 I don't see a bug here. Could be because of bad naming of the APIs, but if you look at the implementation of `bt_mesh_friend_queue_has_space()` you'll see that it'll return `true` if no LPN matches the given address, i.e. this branch will not be taken in that case.

**Comment by jhedberg** [comment]
@menglingao1997 here's the code I'm referring to:
https://github.com/zephyrproject-rtos/zephyr/blob/07460176ed9edb731e5ffee775c7c09259ee33d8/subsys/bluetooth/mesh/friend.c#L1280-L1285

I'll close this, but please reopen if you think something is still buggy or unclear.

**Comment by jhedberg** [comment]
Just wanted to add that one of the reasons I didn't go for a separate "match" call is that I'm trying to avoid iterating the LPN list too many times. We're already doing it twice for TX and three times for RX, which I'm not very happy about.

**Comment by menglingao1997** [comment]
https://github.com/zephyrproject-rtos/zephyr/blob/07460176ed9edb731e5ffee775c7c09259ee33d8/subsys/bluetooth/mesh/friend.c#L1256-L1264
if seg num bigger than CONFIG_BT_MESH_FRIEND_QUEUE_SIZE, above function return false, this is my concerned.

**Comment by jhedberg** [comment]
> if seg_count bigger than CONFIG_BT_MESH_FRIEND_QUEUE_SIZE, above function return false, this is my concerned.

@menglingao1997 that's a real issue, thanks for clarifying. I'm thinking we might be able solve this through Kconfig so that the Friend Queue size must be at least as big as the maximum number of segments we can receive.

**Comment by jhedberg** [comment]
FWIW, e.g. with the default settings this is a non-issue, since that's 3 RX segments max and 16 for the friend queue size.

I also realised it's not so trivial with Kconfig since the RX segment count is derived indirectly from BT_MESH_RX_SDU_MAX

**Comment by jhedberg** [comment]
@menglingao1997 I think I'll just fix it like this:
```
--- a/subsys/bluetooth/mesh/friend.c
+++ b/subsys/bluetooth/mesh/friend.c
@@ -1226,6 +1226,10 @@ static bool friend_queue_has_space(struct bt_mesh_friend *frnd, u16_t addr,
        u32_t total = 0;
        int i;
 
+       if (seg_count > CONFIG_BT_MESH_FRIEND_QUEUE_SIZE) {
+               return false;
+       }
+
        for (i = 0; i < ARRAY_SIZE(frnd->seg); i++) {
                struct bt_mesh_friend_seg *seg = &frnd->seg[i];
 
@@ -1259,10 +1263,6 @@ bool bt_mesh_friend_queue_has_space(u16_t net_idx, u16_t src, u16_t dst,
        bool someone_has_space = false, friend_match = false;
        int i;
 
-       if (seg_count > CONFIG_BT_MESH_FRIEND_QUEUE_SIZE) {
-               return false;
-       }
-
        for (i = 0; i < ARRAY_SIZE(bt_mesh.frnd); i++) {
                struct bt_mesh_friend *frnd = &bt_mesh.frnd[i];
 
```

Can I get a quick ack to proceed?

**Comment by menglingao1997** [comment]
I think ok.
