### ISSUE TITLE
Bluetooth: GATT: Unable to indicate by UUID

### ISSUE THREAD

**Issue by Vudentz** [zephyrproject-rtos/zephyr#18572]
With https://github.com/zephyrproject-rtos/zephyr/commit/648a53d50ffa01583a52cfdbfdc06d4d175ba534 bt_gatt_notify_cb added support for notifying by UUID but the same has not been done to bt_gatt_indicate.

**Comment by aescolar** [comment]
Is this really a bug or an enhancement you want to add?

**Comment by aescolar** [comment]
@Vudentz ^^
