### ISSUE TITLE
STM32G4 support

### ISSUE THREAD

**Issue by rosterloh** [zephyrproject-rtos/zephyr#18585]
There is currently no zephyr support for the STM32G4 family

It would be great if there was support for these. Any sort of timeline for support would be greatly appreciated

**Comment by erwango** [comment]
@rosterloh, there is currently no plan to add this series in Zephyr, but for sure it would be welcome!
Help can be provided to any effort to do this porting work.

**Comment by rosterloh** [comment]
Ok, I've started work on it. Submitted a PR for the hal and working on the dts

**Comment by martinjaeger** [comment]
Here is the PR, if others are looking for it aswell: https://github.com/zephyrproject-rtos/zephyr/pull/18806

**Comment by erwango** [comment]
Closing as G4 is supported now. Thanks!
