### ISSUE TITLE
(nRF51) The RSSI signal does not rise above -44 dBm

### ISSUE THREAD

**Issue by Trubochkin** [zephyrproject-rtos/zephyr#18592]
**Describe the bug**
The RSSI signal from the bluetooth beacon does not rise above -44 dBm even when the beacon is at a distance of 1 cm. But at the same time, the value decreases only at a distance of 25 cm or more. I use the NRF51_BLE400 debugging board as the receiver, and the factory beacon on the NRF51822 as the transmitter.
Here my code: https://github.com/Trubochkin/ble-gsm-gateway.zephyrproject/blob/fffd5c04624ac5ba11e491fda99f2ae5554aba1e/src/f_bluetooth.c#L95

**Expected behavior**
I need the RSSI to change over the entire range of distance. In the android application (nRF_Connect), I see that the RSSI value changes at any distance from the beacon. I can get a value of -20 dBi (at a distance of 1 cm) and below (at a distance). Maybe someone knows what could be the problem?

**Screenshots or console output**
![SharedScreenshot](https://user-images.githubusercontent.com/12196780/63534306-923e8000-c517-11e9-96e7-a4a20667b108.jpg)
![InkedScreenshot_2019-08-22-19-54-32-319_no nordicsemi android mcp_LI](https://user-images.githubusercontent.com/12196780/63534317-966a9d80-c517-11e9-89fe-a1bc8d285f34.jpg)

**Environment (please complete the following information):**
 - OS: Windows 10
 - Zephyr OS build v2.0.0-rc1

**Comment by carlescufi** [comment]
The RSSI is calculated by the phone’s radio and stack, not by Zephyr. I will change this to a question and copy additional people.

**Comment by cvinayak** [comment]
> The RSSI is calculated by the phone’s radio and stack, not by Zephyr.

Yes, the value comes from the Radio hardware. Did you try your Zephyr scanner on a nRF51/nRF52  Development Kit?

**Comment by Trubochkin** [comment]
> Yes, the value comes from the Radio hardware. Did you try your Zephyr scanner on a nRF51/nRF52 Development Kit?
I tried, but the result is the same.

**Comment by carlescufi** [comment]
> > Yes, the value comes from the Radio hardware. Did you try your Zephyr scanner on a nRF51/nRF52 Development Kit?
> 
> Yes

And was it better than the BLE400?

**Comment by Trubochkin** [comment]
> And was it better than the BLE400?

No, all the same

**Comment by Trubochkin** [comment]
Updated to [v2.0.0rc3](https://github.com/zephyrproject-rtos/zephyr/releases/tag/v2.0.0-rc3) and this solved the problem. Now the value of RSSI rises above -44 dBm 👍
