### ISSUE TITLE
tests/arch/arm/arm_zero_latency_irqs fails on cc3220sf_launchxl

### ISSUE THREAD

**Issue by vanti** [zephyrproject-rtos/zephyr#18593]
**Describe the bug**
Running the test leads to failure to set the test flag.

```
***** Booting Zephyr OS build v2.0.0-rc1-144-g048b0359bcd2 *****
Running test suite zero_latency_irqs
===================================================================
starting test - test_arm_zero_latency_irqs
Available IRQ line: 178

    Assertion failed at ZEPHYR_BASE/tests/arch/arm/arm_zero_latency_irqs/src/arm_zero_latency_irqs.c:72: test_arm_zero_latency_irqs: (post_flag == 1 is false)
Test flag not set by ISR

FAIL - test_arm_zero_latency_irqs
===================================================================
Test suite zero_latency_irqs failed.
===================================================================
PROJECT EXECUTION FAILED
```

**To Reproduce**
0. cd tests/arch/arm/arm_zero_latency_irqs
1. mkdir build; cd build
2. cmake .. -DBOARD=cc3220sf_launchxl
3. make flash

**Expected behavior**
I would expect the test to pass.

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04
 - Toolchain: Zephyr SDK 0.10.3
 - Commit SHA tested: 1751648db02258d6c56c4ca1e6fea591bf5bc806

**Comment by ioannisg** [comment]
I don't have this board to check, but the test does not fail for any other board I have tested it on.

**Comment by galak** [comment]
The test fails because it's making an assumption that all IRQs are valid up to CONFIG_NUM_IRQS, which on the CC3220 isn't valid from what I can tell.

**Comment by ioannisg** [comment]
@galak Yes, I 've just realized that, and will fix this, so I have moved the milestone back to 2.0 :)

**Comment by vanti** [comment]
@galak @ioannisg I think the number of irqs on the cc3220sf is wrong based on the behavior seen when I try to set the Interrupt Set Enable registers. I am submitting #18623 to fix this.
