### ISSUE TITLE
LwM2M client sample: an overlay for OpenThread support

### ISSUE THREAD

**Issue by andynnd** [zephyrproject-rtos/zephyr#18601]
LWM2M client has a Bluetooth networking sample. We need an overlay configuration sample for Thread networking. The node can connect to a [border router](https://openthread.io/guides/border-router).

There is an overlay-ot.conf sample in this [issue](https://github.com/zephyrproject-rtos/zephyr/issues/12245#issue-394868628). But it can not work as I test.

Thanks.

**Comment by rlubos** [comment]
Fixed by https://github.com/zephyrproject-rtos/zephyr/pull/28836.
