### ISSUE TITLE
PCA9685 PWM driver is broken

### ISSUE THREAD

**Issue by tbursztyka** [zephyrproject-rtos/zephyr#18608]
It misses the API function get_cycles_per_sec() which is mandatory to get pwm.h public function to work.

So currently this driver just does not work at all due to that.

**Comment by galak** [comment]
@tbursztyka I think this driver was added for an x86 platform that we have since removed.  Are you wanting to use this on some other board?  Curious how you are hitting this.

**Comment by tbursztyka** [comment]
@galak PCA9685 is an i2c slave device. There is no board using it yet, but what about zephyr user that would wire such device on a board? 
Hitting it is easy: just reading the driver code.

**Comment by jfischer-phytec-iot** [comment]
There are expansion boards with PCA9685, for example https://www.adafruit.com/product/815

**Comment by vagotec** [comment]
Hi,
is there any example code for https://www.adafruit.com/product/815?

Thanks

sarvg

**Comment by nixward** [comment]
> Hi,
> is there any example code for https://www.adafruit.com/product/815?
> 
> Thanks
> 
> sarvg
Hi @vagotec if an [overlay](https://docs.zephyrproject.org/latest/reference/devicetree/index.html) was written for the PCA9685 the following sample could be used:
https://github.com/zephyrproject-rtos/zephyr/tree/master/samples/drivers/led_pwm
