### ISSUE TITLE
same70 hsmci interface

### ISSUE THREAD

**Issue by JonathanWoodward** [zephyrproject-rtos/zephyr#18614]
**Is your feature request related to a problem? Please describe.**
I can find no support in the device tree or drivers for same70 hsmci

**Describe the solution you'd like**
The driver and device tree bindings adding

**Describe alternatives you've considered**
Nothing found

**Additional context**
The SD card connector is mentioned but not supported?

![image](https://user-images.githubusercontent.com/54439477/63589012-dc6b4400-c59f-11e9-985e-b1281510ebf8.png)

**Comment by carlescufi** [comment]
Please submit a Pull Request.
