### ISSUE TITLE
SMP fails to allocate buffer and pairing times out

### ISSUE THREAD

**Issue by carlescufi** [zephyrproject-rtos/zephyr#18705]
If you replace the `k_sleep(MSEC_PER_SEC);` with `k_sleep(10)` in `samples/bluetooth/peripheral` and then do the following:

1. Connect from a mobile app
2. Enable Battery Level notifications
3. Initiate pairing by trying to read any of the 128-bit UUID characteristics in the custom service

Then the pairing will not complete because SMP is unable to allocate a packet.
The error message printed will be:

```
[00:01:35.083,007] <err> bt_smp: Unable to allocate Ident Info buffer
```
or
```
[00:00:29.879,852] <err> bt_att: Unable to allocate buffer for op 0x0b
[00:00:29.879,852] <err> bt_att: Unable to allocate buffer for op 0x01
```

**Comment by ioannisg** [comment]
Is there a pull-request for this issue @Vudentz ?

**Comment by carlescufi** [comment]
> Is there a pull-request for this issue @Vudentz ?

Yep, linked it now @ioannisg. Almost ready to be merged.
