### ISSUE TITLE
USB broken on disco l475 iot board

### ISSUE THREAD

**Issue by loicpoulain** [zephyrproject-rtos/zephyr#18717]
**Describe the bug**
Unable to init USB core

**To Reproduce**
Try any USB sample

**Expected behavior**
USB working

**Additional context**
Issue  is caused by commit 737d8051927d3354fbf398babfe1d156f4420442

**Comment by jfischer-phytec-iot** [comment]
This is certainly not high priority.

**Comment by loicpoulain** [comment]
Correct, only in my todo list.
