### ISSUE TITLE
k_uptime_get_32() does not behave as documented

### ISSUE THREAD

**Issue by pabigot** [zephyrproject-rtos/zephyr#18739]
It was recently pointed out on slack that `k_uptime_get_32()` does not return `The lower 32-bits of the elapsed time since the system booted, in milliseconds.`

It returns instead the number of milliseconds corresponding to the low 32 bits of the tick counter.

```
u32_t z_impl_k_uptime_get_32(void)
{
        return __ticks_to_ms(z_tick_get_32());
}
```

The values are significantly different when you look at a 32-bit rollover of the tick clock:
```
At 10000 Hz ticks and 2^32 +/- 50:
t0 = 0x0000ffffffce = 4294967246 ticks => t0m = 429496724 ms
t1 = 0x000100000032 = 4294967346 ticks => t1m = 429496734 ms
t1-t0 = 100 ticks = 10 ms
and t1m-t0m = 10 ms
tt0 = 0x0000ffffffce = 4294967246 ticks => tt0m = 429496724 ms
tt1 = 0x000000000032 = 50 ticks => tt1m = 5 ms
tt1-tt0 = 100 ticks = 10 ms
but tt1m-tt1m = 3865470577 ms
```

This explains https://github.com/zephyrproject-rtos/zephyr/pull/17155#discussion_r309013463 which had claimed that the current implementation followed an algorithm that I noted was incorrect.  Apparently it does.

**Comment by carlescufi** [comment]
> Doesn't #17155 already fix this, though? The resolution to that discussion was that the 32 bit conversion results should be correct to the full precision of the output word, and that's what the new conversion utilities implement and test for.

@pabigot might want to weigh in, but I think the reason for this is the fact that we can get a fix in time for 2.0, whereas #17155 will only be merged in time for 2.1.

**Comment by carlescufi** [comment]
@pabigot we've had this issue for a few releases now, so that might be why there was no vote. Just not deemed urgent enough given the amount of time this has been in the tree.

**Comment by carlescufi** [comment]
@pabigot that's a very good point.
That said, I am afraid it's just too late now for code changes for 2.0. Is there a chance you can instead send a PR that updates the documentation of `k_uptime_get_32()`?

**Comment by pabigot** [comment]
@carlescufi @ioannisg OK, there's now  #18771 for this, intended for 2.0 merge as a "documentation fix".

It's a fine line between documenting the serious problems with this API to suggest people not to use it, while it's still used for many timeout operations within the kernel.

BTW: Accepting this for 2.0 probably implies deprecating the function in 2.1, since we don't want the behavior of an API function to change multiple times in successive releases.
