### ISSUE TITLE
hello_world sample instructions don't work

### ISSUE THREAD

**Issue by dbkinder** [zephyrproject-rtos/zephyr#18760]
**Describe the bug**
Following the instructions in https://docs.zephyrproject.org/latest/samples/hello_world/README.html will result in a build error.

**To Reproduce**
1. ``cd samples/hello_world``
2. ``west build -t run``

```
-- west build: build configuration:
       source directory: /home/dbkinder/zephyrproject/zephyr/samples/hello_world
       build directory: /home/dbkinder/zephyrproject/zephyr/samples/hello_world/build (created)
       BOARD: UNKNOWN
WARNING: This looks like a fresh build and BOARD is unknown; so it probably won't work. To fix, use --board=<your-board>.
Note: to silence the above message, run 'west config build.board_warn false'
-- west build: generating a build system
Zephyr version: 2.0.0
-- Found PythonInterp: /usr/bin/python3 (found suitable version "3.6.8", minimum required is "3.4")
CMake Error at /home/dbkinder/zephyrproject/zephyr/cmake/app/boilerplate.cmake:176 (message):
  BOARD is not being defined on the CMake command-line in the environment or
  by the app.
Call Stack (most recent call first):
  CMakeLists.txt:5 (include)


-- Configuring incomplete, errors occurred!
ERROR: command exited with status 1: /home/dbkinder/.local/bin/cmake -B/home/dbkinder/zephyrproject/zephyr/samples/hello_world/build -S/home/dbkinder/zephyrproject/zephyr/samples/hello_world -GNinja
```

**Expected behavior**
Instructions should work as written.

I think what's happened here is that sometime in the past, the default board target was ``qemu_x86`` if no board was specified.  That's not the case now, and the board must be explicitly defined:

This command does run successfully:
```
west build -t run -b qemu_x86
```
But then there are no instructions for how to exit qemu :)    (CTRL-A X)

**Comment by dbkinder** [comment]
If you add ``:tool: all`` to the directive you get this output (the CMake and ninja instructions look OK, but the west instructions aren't):

Using west:
```
# From the root of the zephyr repository
west build -t run
```

Using CMake and ninja:
```
# From the root of the zephyr repository
# Use cmake to configure a Ninja-based buildsystem:
cmake -B build -GNinja -DBOARD=qemu_x86 samples/hello_world

# Now run ninja on the generated build system:
ninja -C build run
```

**Comment by mbolivar** [comment]
This script has too many options :(. I can no longer say with confidence that they all play together nicely. I'm going to clean it up after 2.0 but am trying to come up with the smallest hot fix I can for just this issue.
