### ISSUE TITLE
UART API documentation

### ISSUE THREAD

**Issue by jcyrax** [zephyrproject-rtos/zephyr#18815]
I'm looking at website API documentation for UART and it looks like some parts of functionality documentation aren't generated. It is for  https://docs.zephyrproject.org/latest/reference/peripherals/uart.html 2.0.0-rc2.

1. Some functions aren't documented, but only mentioned: uart_callback_set, uart_tx, uart_tx_abort, uart_rx_enable, uart_rx_buf_rsp to mention first I checked.

1. I think there is problem with uart_fifo_fill function documentation:
   1. **"This function is expected to be called from UART interrupt handler (ISR)"**
I don't see how you would get IRQ to fire if you don't initiate any transfer at first. This basically means you have to use uart_poll_out and then only uart_fifo_fill when that byte is sent and triggers IRQ. Looking at few existing drivers I think it would be better to remove this expectation and mandate for drivers to support that uart_fifo_fill could be called also from outside ISR.
   1. **"Likewise, not calling this function from an ISR if uart_irq_tx_ready() returns true may lead to undefined behavior, e.g. infinite interrupt loops."**
This means user has to call it even if there are no data to send. Is it expected to call it with zero size?

**Comment by pabigot** [comment]
API: It appears that at least most of these now appear, so closing.
