### ISSUE TITLE
Documentation: parent vs child in DeviceTree nodes

### ISSUE THREAD

**Issue by karstenkoenig** [zephyrproject-rtos/zephyr#18821]
In my understanding parent is used in node descriptions for bus devices. 
[spi-device.yaml](https://github.com/zephyrproject-rtos/zephyr/blob/master/dts/bindings/spi/spi-device.yaml) sets `parent: bus: spi` and is included by all sort of spi devices, such as sensors.

Where as [spi.yaml](https://github.com/zephyrproject-rtos/zephyr/blob/master/dts/bindings/spi/spi.yaml) sets `child: bus: spi`and is included by all actual SPI controllers/peripherals.

In the [binding template yaml](https://github.com/zephyrproject-rtos/zephyr/blob/0d766c668de052f00c04820897ca966cfd781aa4/dts/bindings/binding-template.yaml#L18) the explanation of parent and child seems to be the opposite of what it is used by implementations

Now do I just misunderstand the description? Or is the use of child and parent inverted in the actual yaml files using it?

**Comment by karstenkoenig** [comment]
Ping @ulfalizer 
You did lots of DTS cleanup, maybe you can shed some light here :-)

**Comment by ulfalizer** [comment]
Oops... I accidentally swapped them when adding the documentation.

Fix here: https://github.com/zephyrproject-rtos/zephyr/pull/18822
