### ISSUE TITLE
Bluetooth: controller: Advertiser following directed advertiser will have corrupt data

### ISSUE THREAD

**Issue by joerchan** [zephyrproject-rtos/zephyr#18850]
**Describe the bug**
Directed advertiser makes advertising data corrupt and the data cannot be reset.
1. Starting a directed advertiser will overwrite the advertising data with directed advertise PDU
 The following commands should advertise with the correct advertising data.
```
ll_adv_data_set(data = "name")
ll_adv_param_set(type = ADV_DIRECT, peer = addr)
ll_adv_enable(ON)
# Advertises directed towards peer
ll_adv_enable(OFF)
ll_adv_param_set(type = ADV_IND)
ll_adv_enable(ON)
# Advertising data has been overwritten by peer addr
```

2. The set advertising data command does not update the advertising data if the current advertising PDU is a directed advertising data.
```
ll_adv_param_set(type = ADV_DIRECT, peer = addr)
ll_adv_enable(ON)
# Advertises directed towards peer
ll_adv_enable(OFF)
ll_adv_data_set(data = "name")
ll_adv_param_set(type = ADV_IND)
ll_adv_enable(ON)
# Advertising data has not been set
```
Affects both Split and Legacy bluetooth controller.
```
	/* Dont update data if directed or extended advertising. */
	prev = lll_adv_data_peek(&adv->lll);
	if ((prev->type == PDU_ADV_TYPE_DIRECT_IND) ||
	    (IS_ENABLED(CONFIG_BT_CTLR_ADV_EXT) &&
	     (prev->type == PDU_ADV_TYPE_EXT_IND))) {
		/* TODO: remember data, to be used if type is changed using
		 * parameter set function ll_adv_params_set afterwards.
		 */
		return 0;
	}

```

**Reproduce**
Start directed advertiser
Stop directed advertiser
Start undirected advertiser

**Expected behavior**
Advertising data should be remembered even though the advertising parameters changes.

**Workaround**
Host must update advertising data after setting advertising parameters

**Comment by carlescufi** [comment]
Double-check if this applies to legacy adv only or also to extended avd. Low complexity, will impact RAM.
