### ISSUE TITLE
zsock_poll() unnecessarily wait when querying for ZSOCK_POLLOUT

### ISSUE THREAD

**Issue by kFYatek** [zephyrproject-rtos/zephyr#18867]
**Describe the bug**
When `zsock_poll()` is called to wait for the `ZSOCK_POLLOUT` event, and the socket is already ready for sending, it does not return immediately, but waits for the entirety of the `timeout` passed to it.

An analogous bug also affects `zsock_select()`.

This has been tested on the QEMU emulated target, and on an ST Nucleo-F429ZI board that is equipped with an Ethernet port. I have not tested it on non-Ethernet interfaces (e.g. WiFi, cellular, etc.).

**To Reproduce**
1. Build the following application:

**CMakeLists.txt**:
```cmake
cmake_minimum_required(VERSION 3.13.1)
include($ENV{ZEPHYR_BASE}/cmake/app/boilerplate.cmake NO_POLICY_SCOPE)
project(pollout_bug_demo)
target_sources(app PRIVATE main.c)
```

**prj.conf**:
```
CONFIG_NETWORKING=y
CONFIG_NET_IPV4=y
CONFIG_NET_SOCKETS=y
CONFIG_NET_CONFIG_NEED_IPV4=y
CONFIG_NET_CONFIG_SETTINGS=y
CONFIG_NET_CONFIG_MY_IPV4_ADDR="192.0.2.1"
```

**main.c**:
```c
#include <assert.h>
#include <net/socket.h>

void main(void) {
    struct sockaddr_in addr = {
        .sin_family = AF_INET,
        .sin_port = htons(1234)
    };
    int ret = zsock_inet_pton(AF_INET, "192.0.2.2", &addr.sin_addr);
    assert(!ret);

    int fd = zsock_socket(AF_INET, SOCK_DGRAM, IPPROTO_UDP);
    assert(fd >= 0);
    ret = zsock_connect(fd, (const struct sockaddr *) &addr, sizeof(addr));
    assert(!ret);
    
    printf("Connected!\n");
    
    struct zsock_pollfd pollfd = {
        .fd = fd,
        .events = ZSOCK_POLLOUT
    };
    ret = zsock_poll(&pollfd, 1, 5000);
    assert(ret == 1);
    assert(pollfd.revents == ZSOCK_POLLOUT);
    
    zsock_send(fd, "Hello, world", 12, 0);

    printf("Packet sent!\n");
}
```

2. Run it on an Ethernet-equipped board, or the QEMU emulator. On the 192.0.2.2 host, run something like `nc -u -l 1234`
3. Observe the 5-second delay between "Connected!" and "Packet sent!" messages. If you change the timeout passed to `zsock_poll()`, the delay will change accordingly.

An analogous application using `zsock_select()` instead of `zsock_poll()` can be written, exhibiting the same behaviour. Also, changing the socket type from UDP to TCP also shows the same problem.

**Expected behavior**
`zsock_poll()` shall return immediately, as equivalent calls do on Linux, macOS and Windows. In this usage, it shall block only if the internal socket buffers are indeed full.

**Impact**
Some network-related libraries that would be otherwise trivial to port to Zephyr cause the code to wait for extremely long if `poll()` is used to wait for the `POLLOUT` event (or an equivalent `select()` call).

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04
 - Toolchain: Zephyr SDK 0.10.3
 - Commit SHA or Version used: `aa9b762d12`

**Comment by pfalcon** [comment]
Mind that in https://github.com/zephyrproject-rtos/zephyr/pull/18879, I argue against workarounds for this issue, and instead call for proper fix of the underlying issue, which is https://github.com/zephyrproject-rtos/zephyr/issues/5842 .
