### ISSUE TITLE
boards: mec15xxevb_assy6853: consider moving ARCH_HAS_CUSTOM_BUSY_WAIT to SoC definition

### ISSUE THREAD

**Issue by ioannisg** [zephyrproject-rtos/zephyr#18880]
**Describe the bug**
There has been a suggestion in #18318 to consider moving ARCH_HAS_CUSTOM_BUSY_WAIT definition/selection in the SoC definition instead of board definition.

This makes sense since this requirement appears to be SoC specific.

**Comment by scottwcpg** [comment]
I agree. Does everyone agree on moving the logic that enables ARM SYSTICK if MEC RTOS timer is not enabled into SoC?
