### ISSUE TITLE
[Zephyr 1.14] drivers: flash: spi_nor: Problematic write with page boundaries

### ISSUE THREAD

**Issue by gon1332** [zephyrproject-rtos/zephyr#18935]
**Describe the bug**
The driver is known to have an issue when the size of the chunk to be written is bigger than the page boundaries. It is fixed for the later versions of Zephyr through https://github.com/zephyrproject-rtos/zephyr/pull/17691 and https://github.com/zephyrproject-rtos/zephyr/pull/17994, but not for Zephyr v1.14.

In my opinion https://github.com/zephyrproject-rtos/zephyr/pull/17994 should be backported as a whole.

This issue has been created to backport the needed fixes in v1.14.

The needed commits are:
* fde373313a24eaae25562c816babc6d0e2e0c23a
* ef62bf3c47ed285de60f50f2ab9da9a53072d1b0
* 7501968027501df489146443e98be4f7c86a411b

**To Reproduce**
Write an application that writes at unaligned page addresses.

**Expected behavior**
The driver should handle correctly writes across page boundaries.

**Impact**
Showstopper

**Screenshots or console output**

**Environment (please complete the following information):**
 - OS: GNU/Linux
 - Toolchain: Zephyr SDK
 - v1.14-branch

**Comment by gon1332** [comment]
@pabigot Here you are.

**Comment by pabigot** [comment]
Fixed in 1.14.1
