### ISSUE TITLE
Counter External Trigger

### ISSUE THREAD

**Issue by bfrog** [zephyrproject-rtos/zephyr#18940]
**Is your feature request related to a problem? Please describe.**
I'd like to use the externally driven trigger/clock source for counters (edge causes counter to
increment) for frequency counting in a hardware agnostic way.

**Describe the solution you'd like**
A way to tell the counter it should be driven by an external pin. It would make sense I think to use DTS to describe the pin/clock source to use and on which edge(s) to increment on.

**Describe alternatives you've considered**
I can of course use the vender specific driver libraries as needed, and I will be for
an upcoming project. I'd like to do it in a vendor agnostic way.

**Comment by carlescufi** [comment]
@nordic-krch could you please comment on this feature request and see how it aligns with the current counter API design?

**Comment by henrikbrixandersen** [comment]
As far I see it, that is already fully supported by the current counter API. It is just a matter of having a driver, that configures the underlying counter hardware for counting external events (I have implemented a few these out-of-tree using the counter API already).

**Comment by carlescufi** [comment]
Closing this based on @henrikbrixandersen 's assessment, please reopen if incorrect.
