### ISSUE TITLE
z_arch_system_halt() does not block interrupts

### ISSUE THREAD

**Issue by pizi-nordic** [zephyrproject-rtos/zephyr#18973]
**Describe the bug**
The `z_arch_system_halt()` is implemented in the following way:
```
FUNC_NORETURN __weak void z_arch_system_halt(unsigned int reason)
{
        ARG_UNUSED(reason);

        /* TODO: What's the best way to totally halt the system if SMP
         * is enabled?
         */

        (void)z_arch_irq_lock();
        for (;;) {
                k_cpu_idle();
        }
}
```

This function seems to block all interrupts and halt the CPU, which is intention here.
However the `k_cpu_idle()` unconditionally enable interrupts. As result, the interrupts
can be executed.

**Expected behavior**
The ` z_arch_system_halt()` should completely halt the system.

**Comment by pizi-nordic** [comment]
FYI: @andyross, @ioannisg

**Comment by carlescufi** [comment]
I think I've seen this during my debugging sessions actually! This matches my observations.

**Comment by ioannisg** [comment]
is this a bug? Do we document that z_arch_system_halt needs to halt execution completely, or just the "kernel"?

**Comment by pizi-nordic** [comment]
The interrupts are part of the "kernel", so not even kernel is halted...

**Comment by ioannisg** [comment]
@pizi-nordic can a timer interrupt trigger a context-switch if we are already in z_arch_system_halt()?

**Comment by andrewboie** [comment]
I sent a PR to fix this

**Comment by andrewboie** [comment]
> @pizi-nordic can a timer interrupt trigger a context-switch if we are already in z_arch_system_halt()?

Yes

**Comment by ioannisg** [comment]
> 
> 
> > @pizi-nordic can a timer interrupt trigger a context-switch if we are already in z_arch_system_halt()?
> 
> Yes

Then this is a bug

**Comment by andyross** [comment]
FWIW: the misfeature where `k_cpu_idle()` is expected to be called with an interrupt lock and to release it before returning is an API bug.  Obviously it needs to enable interrupts internally (so that something can wake it up), but the interrupt state really ought to be consistent on return.  Obviously fixing that involves an incompatible change to our architecture API.  But we really should do it...
