### ISSUE TITLE
Failed to flash on ESP32

### ISSUE THREAD

**Issue by nguyen-phuoc-dai** [zephyrproject-rtos/zephyr#19098]
I have followed the "Getting Started Guide" section to setup the environment on Windows 10 to start experience on Zephyr. Everything was OK till final step when I tried to flash zephyr to ESP32 device by "west flash -- esp-device COM44". I got "OSError: [WinError 193] %1 is not a valid Win32 application" error.

**To Reproduce**
1. Install windows host
2. Build sample project "hello, world" on ESP32
3. Flash the Zephyr image on real ESP32
4. Got the error

**Expected behavior**
Flash the zephyr image on the ESP32 and see "Hello, World! esp32" message on console window of putty that connected to ESP32

The following was screenshot for build and flash steps

![success_build](https://user-images.githubusercontent.com/25454206/64751484-6f1b5500-d546-11e9-9767-90834f47eeaa.png)
![error_flash](https://user-images.githubusercontent.com/25454206/64751491-75113600-d546-11e9-9aa9-dad2404840f2.png)

Is anyone have this error? Please help me what and how to fix it

Thanks

**Comment by nguyen-phuoc-dai** [comment]
Hi all,

Is anyone here see the issue? Please help tell me what i can do to flash the image on ESP32
Thanks

**Comment by ExtremeGTX** [comment]
Could you please tell me if windows is 32/64-bit and if python is 32/64-bit ?
I will test this on my setup (Windows 10 64-bit/Py3.7 64-bit)

**Comment by nguyen-phuoc-dai** [comment]
Hi @ExtremeGTX ,

Thanks for your support.

The following was my testing environment

Python 3.7.4
C:\Users\phuocdai>python --version
Python 3.7.4

OS was Windows 10 64bits
C:\Users\phuocdai>systeminfo

Host Name:                 DAIPC
OS Name:                   Microsoft Windows 10 Home Single Language
OS Version:                10.0.17134 N/A Build 17134
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
Registered Owner:          HP
Registered Organization:   HP
Product ID:                00327-35818-48690-AAOEM
Original Install Date:     5/15/2018, 9:15:18 AM
System Boot Time:          9/15/2019, 10:22:55 AM
System Manufacturer:       HP
System Model:              HP ENVY Notebook 13-ab0XX
System Type:               x64-based PC

**Comment by ExtremeGTX** [comment]
After some analysis i can see the problem is calling the `.py` file directly on windows
https://github.com/zephyrproject-rtos/zephyr/blob/af30f2b7d4ebb547ed9ce92494c97943e5a59331/scripts/west_commands/runners/esp32.py#L81-L82

Changing this to 
```python
cmd_convert = ['python', self.espidf, '--chip', 'esp32', 'elf2image', self.elf]
cmd_flash = ['python', self.espidf, '--chip', 'esp32', '--port', self.device,
```
makes it working.

AFAIK Windows doesn't support shebang line `#!/bin/python` so you must call the required interpreter and pass the the script as an arg.

**Comment by nguyen-phuoc-dai** [comment]
Hi ExtremeGTX,

I did follow your guide and it works like a charm.

Thank you very much

**Comment by ExtremeGTX** [comment]
@galak i think this needs to be reopened and fixed.

**Comment by nguyen-phuoc-dai** [comment]
Hi @galak,

Please take your time to check and fix it

**Comment by ioannisg** [comment]
@dcpleung could it be something you could look at?
