### ISSUE TITLE
Add 3-wire support to SPI protocol

### ISSUE THREAD

**Issue by avisconti** [zephyrproject-rtos/zephyr#19134]
Some chips provides SPI with a half-duplex single data line (MISO and MOSI shares the same wire). Interfaces like this are commonly called "3-wire SPI".
It seems that zephyr is missing the SPI 3-wire mode feature.

I think that "struct spi_config" should be enhanced to provide the possibility to pass SPI-3-WIRE-MODE. Then drivers would accept or discard the option according to their capabilities.

**Comment by avisconti** [comment]
@galak @erwango @pabigot 
I put you too here as I feel it is something we should have in zephyr.

**Comment by chris-makaio** [comment]
@avisonti just came across this issue because I'm working with a device which only supports 3-wire SPI. At least for nRF52840 it seems to work out of the box - I see no problems having MISO set but not in use

**Comment by avisconti** [comment]
> @avisonti just came across this issue because I'm working with a device which only supports 3-wire SPI. At least for nRF52840 it seems to work out of the box - I see no problems having MISO set but not in use

@chris-makaio 
Thank you for the info. Currently I stopped investigating the SPI 3-wire because I discovered that on the board I'm working on (SensorTile.box) I can use SPI 4 wire for all the sensors. 
Anyway, are you saying that you didn't do anything special to make SPI working in 3-wire mode?

**Comment by chris-makaio** [comment]
Correct!

**Comment by pabigot** [comment]
@chris-makaio I'm a little confused about that.  You say you have "MISO set but not in use"; that suggests you're not using a half-duplex true 3-wire SPI (where MOSI is bidirectional) but a SPI device that doesn't use MISO (such as a common write-only OLED display).  That's a unidirectional 3-wire SPI interface, not what's being requested here.

According to https://devzone.nordicsemi.com/f/nordic-q-a/9750/3-wire-interface-on-nrf52 and other answers on that site Nordic doesn't support true 3-wire SPI. You can fake it by reconfiguring the peripheral by changing whether the pin is assigned to MISO or MOSI between each read and write transition, or by shorting MISO and MOSI through a 10k resistor.

In any case Zephyr doesn't seem to have any support to configure for (bidirectional) 3-wire SPI so for the general case this seems to be a true functionality gap.

**Comment by chris-makaio** [comment]
Oh sorry, I simply thought that 3-wire SPI meant half-duplex with no MISO data, shame

**Comment by avisconti** [comment]
> @chris-makaio I'm a little confused about that. You say you have "MISO set but not in use"; that suggests you're not using a half-duplex true 3-wire SPI (where ~MOSI~ SDIO is bidirectional) but a SPI device that doesn't use MISO (such as a common write-only OLED display). That's a unidirectional 3-wire SPI interface, not what's being requested here.

@pabigot 
Ah ok. Yes, that's why it is working in his case.
Thanks for pointing it out!

**Comment by erwango** [comment]
@avisconti, going quickly through the comments there is no more need for this ticket, am i right ?

**Comment by pabigot** [comment]
@erwango That depends on what "need" means:

> In any case Zephyr doesn't seem to have any support to configure for (bidirectional) 3-wire SPI so for the general case this seems to be a true functionality gap.

Zephyr doesn't support 3-wire SPI, so we need the issue.  The original requester no longer has case where 3-wire SPI is required, so we don't need the issue.

I think it should remain open at low priority.

**Comment by avisconti** [comment]
> @erwango That depends on what "need" means:
> 
> > In any case Zephyr doesn't seem to have any support to configure for (bidirectional) 3-wire SPI so for the general case this seems to be a true functionality gap.
> 
> Zephyr doesn't support 3-wire SPI, so we need the issue. The original requester no longer has a case where 3-wire SPI is required, so we don't need the issue.
> 
> I think it should remain open at low priority.

Yes, I confirm.
I think that would be really nice to add 3-wire support to SPI API sooner or later.
But yes, I am not requiring it as for what concern sensortile.box board support.

**Comment by tbursztyka** [comment]
I'll look into this in a few weeks  (I need 3-wire mode supported to hook some sensors at home so...)

**Comment by skandinaff** [comment]
I’d like to revisit this issue because I have a concrete use case and a working prototype. I’m integrating an SSD1680-based e-ink display using Zephyr’s SSD16xx and MIPI-DBI drivers. The display uses three-wire SPI, with a single bidirectional SDA line for both command transmission and register reads.

The SSD1680 exposes its internally measured temperature through a readable register. This information is useful in my application, but reading it through the standard Zephyr driver stack is currently prevented because the Nordic SPIM driver rejects SPI_HALF_DUPLEX.

I have tested a local modification that configures MOSI and MISO to the same physical pin and switches the pin direction between TX-only and RX-only transfers. This allows the temperature to be read through the existing MIPI-DBI and SSD16xx paths while retaining Zephyr’s SPI locking and chip-select handling.

Would there be interest in supporting this shared-data-line half-duplex configuration in spi_nrfx_spim? I can prepare a focused pull request.
