### ISSUE TITLE
sock_set_flag implementation in sock_internal.h does not work for 64 bit pointers

### ISSUE THREAD

**Issue by eyuval** [zephyrproject-rtos/zephyr#19181]
The implementation of sock_set_flag in subsys/net/lib/sockets/sockets_internal.h uses u32_t types and therefore does not work for 64 bit system. I am working in the native posix system:

CONFIG_BOARD="native_posix_64"
CONFIG_BOARD_NATIVE_POSIX_64BIT=y

The call to sock_set_flag happens, because I want to set the socket to O_NONBLOCK. When the sock_set_flag occurs, the ctx->user_data pointer, which previously contained a 64 bit address gets corrupted, i.e. basically downcasted to u32.

**Comment by jukkar** [comment]
@eyuval can you test the fix if it works for you?

**Comment by eyuval** [comment]
I tested and it fixed this specific issue. Thanks. However, I see a different problem with using the user_data pointer to store the flags. At some places e.g. in zsock_accepted_cb, the user data pointer is cast to a net_context pointer, without erasing the flag bits in the casting. Now, if one of the flags SOCK_EOF/SOCK_NONBLOCK is on, the resulting pointer will be wrong. So in my view when using the user_data pointer, one needs to discard the flag bits, or take another approach to the flag bits. Should I open a separate issue for this problem?

**Comment by jukkar** [comment]
> Should I open a separate issue for this problem?

Yes, please do that.
