### ISSUE TITLE
deprecate spi_flash_w25qxxdv

### ISSUE THREAD

**Issue by pabigot** [zephyrproject-rtos/zephyr#19224]
`spi_flash_w25qxxdv` has been superseded by `spi_nor` which is a generic driver that should support all JEDEC-compatible SPI NOR devices.  It should be removed because people with Winbond flash devices see it and think it's what they should use.  It's no longer active for any in-tree target.

There's some evidence this is being used in out-of-tree boards (a bug fix was merged 2019-04-16). 
 I don't see anything in the documentation providing a deprecation process for drivers.

**Comment by nashif** [comment]
the driver in the title does not exist anymore
