### ISSUE TITLE
doc: two-column tricks for HTML breaks PDF 

### ISSUE THREAD

**Issue by dbkinder** [zephyrproject-rtos/zephyr#19259]
In doc/guides/networking/net-stack-architecture.rst some HTML trickery was used to fake a two-column HTML presentation (putting the explaining text next to the picture) that severely broke the PDF generation.  

PR #19255 removed the trickery and the nicer presentation.  This issue is to track adding a solution that works for HTML and PDF generation.

**Comment by nashif** [comment]
not an issue anymore, file a bug if issue persists
