### ISSUE TITLE
NVS: Overwriting an item with a shorter matching item fails

### ISSUE THREAD

**Issue by jbrzozoski** [zephyrproject-rtos/zephyr#19250]
**Describe the bug**
Calling nvs_write to overwrite a data item with another data item that is a truncated version of the existing data will not overwrite the old item.  The "is this equal" check in nvs_write ignores differing lengths and then compares the old/new data up to the length of the incoming item, but it should consider differing lengths as non-matching.

**To Reproduce**
1. Call nvs_write and store a string like "ABCD"
2. Call nvs_write again to overwrite the item with "ABC"
3. Read back the NVS item and get "ABCD"

**Expected behavior**
In step 3 above, you should read back "ABC"

**Impact**
Could be causing subtle issues for any application that uses NVS.  Workarounds are possible if you're aware of the problem.

**Additional context**
A simple patch to fix this is attached.

[nvs_patch.diff.txt](https://github.com/zephyrproject-rtos/zephyr/files/3627146/nvs_patch.diff.txt)

**Comment by Laczen** [comment]
@jbrzozoski, thanks for reporting this. Your analysis is correct as well as the proposed fix.

**Comment by carlescufi** [comment]
@jbrzozoski thanks for the patch, could you actually open a Pull Request with that code?
