### ISSUE TITLE
Bluetooth: Mesh: Friend Send model message to LPN

### ISSUE THREAD

**Issue by menglingao1997** [zephyrproject-rtos/zephyr#19265]
When Friend node send model message to LPNs, 
firstly: the message encrypt use application key and application nonce(**include SEQ**).
secondly: the **same seq** should also use to encrypt in network layer.

Obviously, this association is interrupted in the new code. In other words, seq will be inconsistent at different layers. Eventually leading to decryption failure.

**Comment by jhedberg** [comment]
Does #18745 address this?

**Comment by menglingao1997** [comment]
Not only has this problem not been solved, it is precisely because of this pattern that this has happened.

**Comment by menglingao1997** [comment]
![Uploading 1568879193(1).png…]()

**Comment by trond-snekvik** [comment]
Looks like I screwed up. I'll take a look and see if this can be fixed properly without too big a change. Otherwise, we should probably revert #18745, as it just replaces one corner case with a much bigger one.

**Comment by menglingao1997** [comment]
#18745 Can effectively process messages sent by other nodes to LPNs, However The friend self have  issure, and segment message may also present this problem, but due to present `seg_zero`  filed, so segment message will compute correctly `seq` even not Inconsistent between different layer.

**Comment by menglingao1997** [comment]
but, when `segment` message `seq` is `8192` higher than `seqauth`, will be incorrect.

**Comment by menglingao1997** [comment]
I'll take a stab at this :)

**Comment by jhedberg** [comment]
> I'll take a stab at this :)

Hold on. If I understood right @trond-snekvik already has some code for this, but perhaps didn't yet open a PR. @trond-snekvik can you confirm?

**Comment by trond-snekvik** [comment]
Hey, yeah I've got a branch in progress, but I've been held up by some other issues the last few days
