### ISSUE TITLE
_interrupt_stack is defined in the kernel, but declared in arch headers

### ISSUE THREAD

**Issue by gnuless** [zephyrproject-rtos/zephyr#19307]
`kernel/init.c` defines `_interrupt_stack` (and on SMP systems, additional per-CPU interrupt stacks), but no kernel header file exports a declaration.  As a result, most (if not all) arch trees redeclare it themselves (and `kernel/smp.c` redeclares the additional stacks).  These declarations should all be consolidated, probably in `kernel_internal.h`.

**Comment by ioannisg** [comment]
Got this. I think, if we go for it, we could try to address #16210, if possible.

**Comment by ioannisg** [comment]
FYI @andrewboie

**Comment by ioannisg** [comment]
BTW,  @gnuless is it possible to have a Zephyr build without an interrupt stack?

**Comment by andrewboie** [comment]
> BTW, @gnuless is it possible to have a Zephyr build without an interrupt stack?

Why would you want to do this?
