### ISSUE TITLE
build error using logger in test case

### ISSUE THREAD

**Issue by andrewboie** [zephyrproject-rtos/zephyr#19320]
The following trivial patch:

```
diff --git a/tests/kernel/fatal/src/main.c b/tests/kernel/fatal/src/main.c
index b6f6922c70..e71445a028 100644
--- a/tests/kernel/fatal/src/main.c
+++ b/tests/kernel/fatal/src/main.c
@@ -11,6 +11,9 @@
 #include <irq_offload.h>
 #include <kswap.h>
 
+#include <logging/log.h>
+LOG_MODULE_DECLARE(fatal);
+
 #if defined(CONFIG_USERSPACE)
 #include <syscall_handler.h>
 #include "test_syscalls.h"
@@ -360,6 +363,7 @@ void test_fatal(void)
 /*test case main entry*/
 void test_main(void)
 {
+       LOG_ERR("hi there");
        ztest_test_suite(fatal,
                        ztest_unit_test(test_fatal));
        ztest_run_test_suite(fatal);
```

Is expected to work, but results in a build error at link time:

```
/opt/zephyr-sdk/i586-zephyr-elf/bin/../lib/gcc/i586-zephyr-elf/8.3.0/../../../../i586-zephyr-elf/bin/ld: ../app/libapp.a(main.c.obj): in function `log_const_source_id':
/home/apboie/projects/zephyr4/zephyr/include/logging/log_core.h:388: undefined reference to `log_const_fatal'
collect2: error: ld returned 1 exit status
zephyr/CMakeFiles/app_smem_unaligned_prebuilt.dir/build.make:94: recipe for target 'zephyr/app_smem_unaligned_prebuilt.elf' failed
make[2]: *** [zephyr/app_smem_unaligned_prebuilt.elf] Error 1
CMakeFiles/Makefile2:528: recipe for target 'zephyr/CMakeFiles/app_smem_unaligned_prebuilt.dir/all' failed
make[1]: *** [zephyr/CMakeFiles/app_smem_unaligned_prebuilt.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```

I reviewed the documentation at https://docs.zephyrproject.org/latest/reference/logging/index.html and I don't see what I'm missing, if this is a problem on my end.

In this scenario CONFIG_LOG and CONFIG_LOG_IMMEDIATE are enabled. I reproduced this on qemu_x86.

Just to rule out any issues with user mode, I tried this on some tests which don't enable user mode, and got the same result, it broke in the same way building tests/kernel/spinlock on qemu_x86_64.

**Comment by nordic-krch** [comment]
@andrewboie now sample builds because `LOG_MINIMAL` is enabled which is not using module registration. If `LOG_MINIMAL` is not set then sample in fact does not build because `LOG_MODULE_DECLARE(fatal)` expects that somewhere in the build there is `LOG_MODULE_REGISTER(fatal)` call and there is no such logging module registered. `kernel/fatal.c` is using `os` module.
