### ISSUE TITLE
Bluetooth: Mesh: Persistent storage of Virtual Addresses

### ISSUE THREAD

**Issue by LingoMeng** [zephyrproject-rtos/zephyr#19342]
Is this information not stored in FLASH?

**Comment by menglingao1997** [comment]
Virtual Address?

**Comment by jhedberg** [comment]
It seems this is one feature that's not yet implement. I think the 16-bit format group addresses will be stored, but we don't store (or restore) the virtual label UUIDs, i.e. after a power cycle the 16-bit group addresses would be meaningless. Are you interested in contributing this feature?

**Comment by menglingao1997** [comment]
No problem, but there is no time recently, waiting for the National Day holiday.
