### ISSUE TITLE
net: TCP/IPv6 set of fragmented packets causes Zephyr QEMU to double free

### ISSUE THREAD

**Issue by rmstoi** [zephyrproject-rtos/zephyr#19348]
If Zephyr QEMU echo server receives couple of TCP/IPv6 fragmented packets it quits with log:

```
[00:00:16.390,000] <err> net_tcp: context->tcp == NULL
[00:00:16.390,000] <err> net_echo_server_sample: TCP (IPv6): Connection error 9
...
[00:00:17.400,000] <err> net_pkt: *** ERROR *** pkt 0x001457d0 is freed already by tcp_retry_expired():244 (net_tcp_release():331)                                                           
```
After this happens, TCP context stops working, Zephyr prints for incoming TCP segments:

`[00:01:58.440,000] <dbg> net_tcp._tcp_syn_rcvd: (0x0013b918): Context 0x0013a5e0 is not listening
`

Two pcaps are attached. This issue is reproduced by sending pcaps as: frag1.pcap.gz && frag2.pcap.gz && frag2.pcap.gz

[frag1.pcap.gz](https://github.com/zephyrproject-rtos/zephyr/files/3647024/frag1.pcap.gz)
[frag2.pcap.gz](https://github.com/zephyrproject-rtos/zephyr/files/3647023/frag2.pcap.gz)

**Comment by jukkar** [comment]
We are catching double frees so the system is not crashing -> low priority atm.

**Comment by dleach02** [comment]
If this is with the legacy TCP and we have switched to the new TCP do we need to retain this bug?

**Comment by jukkar** [comment]
This is for legacy and it is an old one -> closing.
