### ISSUE TITLE
arch/x86: QEMU doesn't appear to support x2APIC

### ISSUE THREAD

**Issue by gnuless** [zephyrproject-rtos/zephyr#19353]
Even with +x2apic, QEMU in the Zephyr SDK reports no x2APIC support in CPUID.  This might be a matter of needing additional flags or lack of support in the build in the Zephyr SDK.

In any case this makes it necessary to test x2APIC on real hardware and thus x2APIC tests are excluded in CI runs.

**Comment by galak** [comment]
> Even with +x2apic, QEMU in the Zephyr SDK reports no x2APIC support in CPUID. This might be a matter of needing additional flags or lack of support in the build in the Zephyr SDK.
> 
> In any case this makes it necessary to test x2APIC on real hardware and thus x2APIC tests are excluded in CI runs.

As far as I can tell the support should be in the SDK qemu, so its probably a flag passing/enabling issue.
