### ISSUE TITLE
LwM2M sample reorganization: split out LwM2M source into object-based .c files

### ISSUE THREAD

**Issue by mike-scott** [zephyrproject-rtos/zephyr#19356]
**Is your enhancement proposal related to a problem? Please describe.**
The LwM2M sample has become fairly complex over the last 2 years.  I propose to break out each LwM2M object / configuration into it's own source file.

**Describe the solution you'd like**
Each object-based .c file could be located under the `src/lwm2m/` directory.  This way new users of the code can easily locate things they are interested in like the `lwm2m_button.c` file or `lwm2m_firmware.c`.

**Describe alternatives you've considered**
The sample is only going to get more complex as I add support for different network type, so this is needed prior to those changes.

**Comment by mike-scott** [comment]
@endian-benjamin @retfie FYI

**Comment by dleach02** [comment]
Removed the 2.1 milestone.
