### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by WilliamGFish** [zephyrproject-rtos/zephyr#19385]
**Describe the bug**
When compiling receive following error:
```
Device tree configuration written to ../sensor_server/build/zephyr/include/generated/generated_dts_board.conf
warning: please put 'required: false' instead of 'category: optional' in 'properties: center-aligned: ...' in ../dts/bindings\pwm\nordic,nrf-pwm.yaml - 'category' will be removed
warning: please put 'required: false' instead of 'category: optional' in 'properties: center-aligned: ...' in ../dts/bindings\pwm\nordic,nrf-pwm.yaml - 'category' will be removed 
```

**To Reproduce**
Compile via west for NRF52840 DVK

**Expected behavior**
yaml file updated to remove error

**Impact**
annoyance, may become showstopper awaiting full impacts

**Comment by ulfalizer** [comment]
Fix: https://github.com/zephyrproject-rtos/zephyr/pull/19387

**Comment by WilliamGFish** [comment]
My error is with the NRF52 : /dts/bindings\pwm\nordic,nrf-pwm.yaml

I'm guesing that every Soc will require changes and is a much larger problem. Hence will need a review of all yaml files.

    _center-aligned:
      type: boolean
      description: Use center-aligned (up and down) counter mode
      category: optional_
