### ISSUE TITLE
Bluetooth: Mesh: Mesh model implementation?

### ISSUE THREAD

**Issue by menglingao1997** [zephyrproject-rtos/zephyr#19452]
Is there more implementation of the mesh model here?

**Comment by menglingao1997** [comment]
Is there more implementation of the mesh model here?

**Comment by jhedberg** [comment]
Which model?

**Comment by menglingao1997** [comment]
Generic, defined by mesh model spec. Such as generic light, generic power, generic property.

**Comment by jhedberg** [comment]
Could you come over to Slack if you're not already? That might be more convenient for this kind of discussion.

**Comment by menglingao1997** [comment]
Okay

**Comment by jhedberg** [comment]
There's a link here if you're looking for it: https://www.zephyrproject.org/developers/how-to-contribute/

There's a dedicated #bluetooth channel for Bluetooth topics
