### ISSUE TITLE
Error building samples with PWM

### ISSUE THREAD

**Issue by mron** [zephyrproject-rtos/zephyr#19467]
I'm using macOS 10.14.6. I did a new install and update of zephyr following the "Getting Started" guide.

When building for an nrf52840_pca10056,

west build -b nrf52840_pca10056 samples/basic/servo_motor  --- works.

I can build the blinky sample, and the servo_motor sample. However samples/basic/fade_led fails with:

 error: #error "Choose supported PWM driver"
 #error "Choose supported PWM driver"

nrf52840_pca10056 is listed as supported for fade_led. The define for "DT_ALIAS_PWM_LED0_PWMS_CONTROLLER" is not being created.

**Comment by mron** [comment]
Tell me what PWMS_CONTROLLER is and where to look for it, I'll see if I can find the problem.

**Comment by ValentiWorkLearning** [comment]
@mrrosen  see answer here: https://github.com/zephyrproject-rtos/zephyr/issues/19523

**Comment by mrrosen** [comment]
@ValentiWorkLearning I think you have the wrong "@"; @mron see above for help
