### ISSUE TITLE
Bluetooth: split:  bt_set_name() asserts due to flash and radio coex

### ISSUE THREAD

**Issue by paulgavrikov** [zephyrproject-rtos/zephyr#19484]
**Describe the bug**
Using the split ll calling `bt_set_name()` **sometimes** fails even though no radio activity is present.
This appears to be only happening when a LE scan was started before (and stopped). Independent of the duty cycle.

**To Reproduce**
![image](https://user-images.githubusercontent.com/9333587/65889873-44345c00-e3a2-11e9-929e-9869d0285b2a.png)

Happens after a couple of loops on nrf52840_dks. Only happens with `test1()` and `test2()`. Removing either of them appears to never run in the assertion.

**Expected behavior**
No assert.

**Impact**
showstopper.

**Screenshots or console output**
```
ASSERTION FAIL [ll_radio_state_is_idle()] @ ZEPHYR_BASE/drivers/flash/soc_flash_nrf.c:291␍␊
[15:04:10:857] ⇥    Radio is on during flash operation.␍␊
```

**Environment (please complete the following information):**
 - OS: (e.g. Linux, MacOS, Windows): Kubuntu 18.04
 - Toolchain (e.g Zephyr SDK, ...): Zephyr SDK 0.10.3
 - Commit SHA or Version used: 2051ad184614f02975ea8ba923cf5bff13c2535a

**Additional context**

**Comment by paulgavrikov** [comment]
@cvinayak

**Comment by carlescufi** [comment]
@paulgavrikov please let us know if https://github.com/zephyrproject-rtos/zephyr/pull/19395 fixes the issue.

**Comment by paulgavrikov** [comment]
@carlescufi #19395 does not fix this

**Comment by paulgavrikov** [comment]
Actually I am not sure if `test2()` waits for the discovery callback to be triggered. Could it be possible that a stop call is not processed if the start was issued shortly before?

**Comment by cvinayak** [comment]
@paulgavrikov I tried the same scenario manually using the bluetooth shell app, but could not reproduce. I tried to modify the scan_adv sample to perform the scenario by enabling settings and flash features in the sample, but could not manage to get the app to flash (and hence not reproduce your scenario). 

Option 1: provide a very simple application that reproduces the issue.
Option 2: we try a screen sharing call to debug the issue live (between 0600 to 1400 CET)

**Comment by cvinayak** [comment]
@paulgavrikov I may have managed to reproduce something similar manually (though with difficulty, like 1 in 20 times) trying to use ```flash erase 60000``` while having ```bt scan on``` with bt shell app and 2.5 ms continuous scan.

I have updated https://github.com/zephyrproject-rtos/zephyr/pull/19395

**Comment by paulgavrikov** [comment]
@cvinayak Appears to be working with #19395! Thank you very much!
