### ISSUE TITLE
Reference and sample codes to get started with the friendship feature in ble mesh

### ISSUE THREAD

**Issue by stephenmasih** [zephyrproject-rtos/zephyr#19488]
Please, can anyone guide me with setting up a friend node and an LPN in ble mesh?

I went through the guidelines as provided in this link 
https://lists.zephyrproject.org/g/devel/topic/how_to_configure_ble_mesh_fn/28612902?p=,,,20,0,0,0::recentpostdate%2Fsticky,,,20,2,20,28612902

I worked on with mesh-demo samples and it worked fine. I have understood the concept of friendship in ble mesh. Please share some code reference to start developing applications in a friend node and a low powered node.

**Comment by aescolar** [comment]
CC @jhedberg

**Comment by jhedberg** [comment]
You could start by playing around with `tests/bluetooth/mesh_shell`. It supports both LPN and Friend roles, and you can control those from the command line.

**Comment by carlescufi** [comment]
Question answered
