### ISSUE TITLE
insufficient test case coverage for log subsystem

### ISSUE THREAD

**Issue by andrewboie** [zephyrproject-rtos/zephyr#19496]
We do not have very much test coverage for our logging subsystem.

The output of `sanitycheck --coverage -p qemu_x86 -T tests/subsys/logging/` reports:

include/logging: 84.0% line coverage, 92.6% function coverage, 18.8% branch coverage
subsys/logging: 55.9% line coverage, 63% function coverage, 51.6% branch coverage

Need to get these to 100% or exhaustively document any exceptions. Such coverage needs to be induced by tests under tests/subsys/logging which prove that this code works.

**Comment by aescolar** [comment]
CC  @nordic-krch @jakub-uC

**Comment by nashif** [comment]
stale, code coverage is a general goal, for all subsystems, not only logging.
