### ISSUE TITLE
 Can't change the slave latency on a connection. 

### ISSUE THREAD

**Issue by WFarber** [zephyrproject-rtos/zephyr#19525]
Zephyr 2.0.0
 I can't seem to change the slave latency on a connection.  I am using the central_hr and peripheral_hr sample code.
After connecting, i execute the following:
   param = BT_LE_CONN_PARAM(40, 40, 2, 420);
   conn_update(shell, param);The result (captured on an Elisys) is:

    LE-C Packet (Connection Parameter Request, Min= 50.000 ms, Max= 50.000 ms, Lat= 2, T/o= 4.200 s, Per= No Prefer
<Empty LE Packet
    Empty LE Packet
<LE-C Packet (Connection Parameter Response, Min= 50.000 ms, Max= 50.000 ms, Lat= 2, T/o= 4.200 s, Per= No Prefe
    Empty LE Packet
<Empty LE Packet
    LE-C Packet (Connection Update Indication, WinSz= 1.250 ms, WinOfs= 0, Int= 50.000 ms, Lat= 2, T/o= 4.200 s, Inst=
<Empty LE Packet
    Empty LE Packet
<Empty LE Packet
    Empty LE Packet
<Empty LE Packet
    Empty LE Packet
<Empty LE Packet
    Empty LE Packet
<Empty LE Packet
    Empty LE Packet
<Empty LE Packet
    Empty LE Packet
<Empty LE PacketI expected the slave (<) to reply to every third master (>) packet.  Any ideas??

**Comment by cvinayak** [comment]
@WFarber Please try #19570.
