### ISSUE TITLE
Doubly freed memory in the pipe_api test

### ISSUE THREAD

**Issue by npitre** [zephyrproject-rtos/zephyr#19535]
While working on the new heap memory allocator, I stumbled across a test
failure that appears to be triggered by the new allocator that currently
checks for double-free occurrences.

In tests/kernel/pipe/pipe_api/src/test_pipe_contexts.c there is that
code:

```
static void tpipe_block_put(struct k_pipe *ppipe, struct k_sem *sema,
                            int timeout)
{
        struct k_mem_block block;

        for (int i = 0; i < PIPE_LEN; i += BYTES_TO_WRITE) {
                /**TESTPOINT: pipe block put*/
                zassert_equal(k_mem_pool_alloc(&mpool, &block, BYTES_TO_WRITE,
                                               timeout), 0, NULL);
                memcpy(block.data, &data[i], BYTES_TO_WRITE);
                k_pipe_block_put(ppipe, &block, BYTES_TO_WRITE, sema);
                if (sema) {
                        k_sem_take(sema, K_FOREVER);
                }
                k_mem_pool_free(&block);
        }
}
```

This code is invoked from test_pipe_block_put() with sema == NULL.

The call chain from k_pipe_block_put() is z_pipe_put_internal(),
pipe_async_finish(), k_mem_pool_free(). When execution returns, we call
k_mem_pool_free() on the same momery again in the loop above.

**Comment by aescolar** [comment]
Was fixed in #19702 => closing
