### ISSUE TITLE
Allow running and testing network samples in automatic way

### ISSUE THREAD

**Issue by jukkar** [zephyrproject-rtos/zephyr#19540]
**Is your enhancement proposal related to a problem? Please describe.**
The network samples can bit rot easily as they are only compile tested by sanitycheck script.
We need to run the network samples in some semi-automatic way so that we can be sure that there is no regressions in network stack.

**Describe the solution you'd like**
Use Docker to to run scripts and programs from net-tools, then have qemu / native_posix to connect to that Docker instance. Have also IP addresses setup properly so that connectivity between these two works.

The task can can be split up as follows:

- [x] Create a script to run sample tests against the Docker host tools from 'net-tools'
- [x] Add sample tests where the Docker 'net-tools' image can serve as the client end as the result is easy to have available when the client stops executing in the Docker container
- [x] Investigate how to utilize e.g. native_posix Zephyr target to exit with a return value after a completed test where Zephyr acts as a client and the Docker image is the server end
- [x] Create sample tests where the native_posix Zephyr target can serve as the test client, if the above point works out properly
~- [ ] Write the test script in some other language than bash, python has been proposed~ (_future development, if needed_)
- [ ]  https://github.com/zephyrproject-rtos/zephyr/pull/19677 Is tracking items

**Comment by dleach02** [comment]
@jukkar, I note that all the subtasks are checked off but it is unclear to me if there are actual PRs or items merged into main?

**Comment by pfl** [comment]
>  note that all the subtasks are checked off but it is unclear to me if there are actual PRs or items merged into main?

We have https://github.com/zephyrproject-rtos/zephyr/pull/19677 in the pipeline implementing the ticked off items. The support in net-tools was handled by https://github.com/zephyrproject-rtos/net-tools/pull/37 which was already merged.
