### ISSUE TITLE
drivers/pcie: `pcie_get_mbar()` should return a `void *` not `u32_t`

### ISSUE THREAD

**Issue by ghost** [zephyrproject-rtos/zephyr#19550]
These bars are meant to be used for MMIO, so they should return `void *`.

**Comment by andrewboie** [comment]
Not sure why this was closed. This is an actual problem on 64-bit if an MMIO base address is returned that is greater than 4GB.

**Comment by andrewboie** [comment]
Suggest having this and related APIs return a uintptr_t since it is a physical address that will need to be mapped in the MMU.

**Comment by andrewboie** [comment]
I don't remember who fixed this but it returns a `uintptr_t` now, closing
