### ISSUE TITLE
zephyr_library: missing 'kernel-mode' vs 'app-mode' documentation

### ISSUE THREAD

**Issue by marc-hb** [zephyrproject-rtos/zephyr#19582]
Not sure where this should be documented, probably as a comment in `cmake/extensions/cmake`?

From: `tests/subsys/settings/functional: make common code a zephyr_library()` #19531, see also references there.
```
zephyr_library_named(  settings_func_test)
add_dependencies(      settings_func_test offsets_h)
```

@mbolivar :

> Why is this `add_dependencies()` required?
> 
> I see this in the top level zephyr/CMakeLists.txt:
> 
> foreach(zephyr_lib ${ZEPHYR_LIBS_PROPERTY})
>   add_dependencies(${zephyr_lib} ${OFFSETS_H_TARGET})
> endforeach()
> So it looks like zephyr_library_named() should be taking care of this:

@SebastianBoe 
> From: "Bøe, Sebastian" <Sebastian.Boe@nordicsemi.no>
> Date: Thursday, 3 October 2019 at 08:12
> To: @marc-hb , @mbolivar , @nvlsianpu 
> Subject: Re: [zephyrproject-rtos/zephyr] tests/subsys/settings/functional: make common code a zephyr_library() (#19531)
> 
> The build system runs in two "modes", or phases, kernel-mode,
> and app-mode. Scripts executed directly or in-directly by boilerplate.cmake
> is in kernel-mode, everything else is in app-mode.
> 
> It's not supported to create zephyr libraries in app-mode as we are doing here,
> but this is not documented anywhere AFAIK so therefore us needing
> to do workarounds like this is a "lack-of-documentation bug" and not a "design bug".
> 
> We use the API in this unsupported way in this case because it happens to do roughly
> (with the exception of needing to manually add_dependencies) what we need to do
> with minimal build script boilerplate.
> 
> The supported way of doing nearly the same thing would be for the app build script to
> add a zephyr_extra_module because west modules are run in kernel-mode and can use
> the zephyr_library API in a supported way. But I decided not to do it in this case because
> creating a zephyr module for this seemed like overkill.

**Comment by marc-hb** [comment]
What I find concerning here is the **randomness** of build failures.

Quoting myself from: `tests/subsys/settings/functional: make common code a zephyr_library()` #19531

```
zephyr_library_named(  settings_func_test)
add_dependencies(      settings_func_test offsets_h)
```

`make -C build [settings_func_test]` always fails without `add_dependencies(      settings_func_test offsets_h)`
`make -j` sometimes succeeds in building even without this dependency thanks to a race condition. `make -k; make` obviously succeeds too.

`ninja -j1` doesn't fail, it seems "lucky" enough to build in some order that avoids the missing dependency issue. However `ninja settings_func_test` fails with the same error than `make settings_func_test` above.

**Comment by nashif** [comment]
if you think this is not stale, then please do something about it, this is now the 3rd time being reopened.

**Comment by marc-hb** [comment]
@tejlmand , @mbolivar-nordic , is Sebastian's email in the description above still valid today and is it still missing from https://docs.zephyrproject.org/latest/guides/zephyr_cmake_package.html ?

**Comment by mbolivar-nordic** [comment]
I assume it is still valid. I think https://docs.zephyrproject.org/latest/application/index.html might be a better place to document this, but I defer to @tejlmand .

**Comment by tejlmand** [comment]
This is still valid, but instead of just documenting this, I think it's better to issue a warning if the user tries to use `zephyr_library()` after `find_package(Zephyr)` completes, and then in future we can remove the possibility.

**Comment by galak** [comment]
@tejlmand can you look at this for the 2.6 release

**Comment by tejlmand** [comment]
> @tejlmand can you look at this for the 2.6 release

Done, fixed here: https://github.com/zephyrproject-rtos/zephyr/pull/35887
