### ISSUE TITLE
Bluetooth: Mesh: Provisioning Over PB-ADV

### ISSUE THREAD

**Issue by menglingao1997** [zephyrproject-rtos/zephyr#19638]
https://github.com/zephyrproject-rtos/zephyr/blob/41a72e4c00b3bd2061be64309266ba715127d1e3/subsys/bluetooth/mesh/prov.c#L260-L275

It should be better to change it to this way.

```C
               if (!buf) { 
 			continue; 
 		} 
```

**Comment by jhedberg** [comment]
The buffers in `link.tx.buf[]` are always allocated contiguously (see `prov_send_adv()` in `prov.c`), and never freed independently, so finding a NULL means the end of allocated buffers. Continuing further than this would therefore just waste CPU cycles unnecessarily.
