### ISSUE TITLE
missing file reference in samples/sensor/ti_hdc doc

### ISSUE THREAD

**Issue by dbkinder** [zephyrproject-rtos/zephyr#19660]
@nikooiko  samples/sensor/ti_hdc/README.rst line 45  references ``samples/boards/nucleo_l496zg/sensors`` that doesn't exist

**Comment by dbkinder** [comment]
I fixed references I could find in PR #19659, but couldn't find a suitable fix for this reference.

**Comment by nikooiko** [comment]
The sample originally was placed at `samples/boards/nucleo_l496zg/sensors` but then moved into `samples/sensor/ti_hdc/`. We can simply rename this ref to `samples/sensor/ti_hdc`

**Comment by dbkinder** [comment]
Thanks @nikooiko , I've updated PR #19659 with your recommendation.
