### ISSUE TITLE
missing files in xtensa/xt-sim doc

### ISSUE THREAD

**Issue by dbkinder** [zephyrproject-rtos/zephyr#19661]
boards/xtensa/xt-sim/doc/index.rst line 135 refers to ``soc/xtensa/hifi3_bd5/linker.ld`` that doesn't exist, and on line 144, the referenced folder ``tests/kernel/test_build`` doesn't exist either.

@mbolivar @mazen-neifer

**Comment by dbkinder** [comment]
I fixed references I could find in PR #19659, but couldn't find a suitable fix for this reference.

**Comment by mbolivar** [comment]
Did you mean to @-mention me? I don't use this board.
