### ISSUE TITLE
doc: [message_queues.rst] unclear about data_item structure type

### ISSUE THREAD

**Issue by sdalu** [zephyrproject-rtos/zephyr#19684]
In documentation: reference/kernel/data_passing/message_queues.html
- [x]  `sizeof(data_item_type)` is used instead of `sizeof(struct data_item_type)`
- [x]  struct is defined as `data_item_type` and `next data_item_t`
- [x]  could be useful when talking about defining message queue, to talk again about the message queue alignment and propose to use the `aligned` attribute when defining type: `typedef struct { }  __attribute__((aligned(4))) data_item_t`
- [x]  in "reading from message queue", `k_msgq_get` return value must be tested as `-ENOMSG` can be returned due to `k_msgq_purge`(edited)

**Comment by aescolar** [comment]
CC @andrewboie @andyross

**Comment by jenmwms** [comment]
> could be useful when talking about defining message queue, to talk again about the message queue alignment and propose to use the `aligned` attribute when defining type: `typedef struct { }  __attribute__((aligned(4))) data_item_t`

I need some help understanding this, please. Where do you suggest we discuss this in relation to the implementation example of [Defining a Message Queue](https://docs.zephyrproject.org/latest/reference/kernel/data_passing/message_queues.html#defining-a-message-queue)?

**Comment by jenmwms** [comment]
Perhaps I could add something like this at the end of that section?  
`
typedef struct {
    uint32_t field1;
    uint32_t field2;
    uint32_t field3;
}__attribute__((aligned(4))) data_item_type;
`

**Comment by jenmwms** [comment]
I think I understood the suggestions correctly. Please check the PR - https://github.com/zephyrproject-rtos/zephyr/pull/28423
