### ISSUE TITLE
Bluetooth: Mesh: Receiving an access message

### ISSUE THREAD

**Issue by menglingao1997** [zephyrproject-rtos/zephyr#19724]
https://github.com/zephyrproject-rtos/zephyr/blob/b71eb71de72f2c688c114f6cd8809dd11522bc2f/subsys/bluetooth/mesh/transport.c#L656-L692

According Mesh Profile Spec1.0.1  3.7.4.2
A message is delivered to the model for processing if all the following conditions are met:
**The model is bound to the application or device key that was used to secure the transportation of the-message.**

However In the above code, I not see any check for this condition.

**Comment by jhedberg** [comment]
The check is done in access.c through bt_mesh_model_recv() -> find_op() -> model_has_key()
