### ISSUE TITLE
k_sleep(K_FOREVER) behavior unexpected

### ISSUE THREAD

**Issue by pabigot** [zephyrproject-rtos/zephyr#19748]
> One side comment. During playing with k_sleep and negative numbers I've noticed that `k_sleep(K_FOREVER)` returns immediately. Is K_FOREVER intended to be used for `k_sleep`?

_Originally posted by @nordic-krch in https://github.com/zephyrproject-rtos/zephyr/pull/19591#issuecomment-540554331_

Since we had recently reached some consensus that `k_sleep` should use the standard timeout API it should support `K_FOREVER`.

If it does not a fix might be integrated with rework of `k_poll` since functionally `k_sleep` could be seen as `k_poll` with no events.   (The current implementation has asserts that at least one event is provided, but passing zero events works as expected when asserts are not enabled, which is the default condition.)

**Comment by aescolar** [comment]
@pabigot So, an enhacement? ;)

**Comment by nordic-krch** [comment]
Note that there are few places in the tree where `k_sleep(FOREVER)` is used even though it expires immediately (probably against user's intention).
