### ISSUE TITLE
Provide command to check board supported features

### ISSUE THREAD

**Issue by erwango** [zephyrproject-rtos/zephyr#19760]
Would be nice to have a command to check supported features on one board.
Something like:
```
$ west boardcheck nucleo_f334r8
  - arduino_i2c
  - gpio
  - i2c
  - spi
  - pwm
  - rtc
  - watchdog
  - counter
  - nvs
```

Output could be a dump of the board yaml or something more sophisticated.

**Comment by mbolivar** [comment]
Moved from west, since this would be a zephyr extension

**Comment by erwango** [comment]
I'm not requesting this anymore, so I'm closing. One can feel free to reopen if interested
