### ISSUE TITLE
tests/crypto/rand32 failed on sam_e70 board on v1.14 branch.

### ISSUE THREAD

**Issue by chen-png** [zephyrproject-rtos/zephyr#19813]
**To Reproduce**
1. west build -b=sam_e70_xplained tests/crypto/rand32 
              -DCONF_FILE=prj_hw_random_xoroshiro.conf
2. west flash
3. See error

**Screenshots or console output**

***** USAGE FAULT *****
  Illegal load of EXC_RETURN into PC
***** Hardware exception *****
Current thread ID = 0x00000000
Faulting instruction address = 0x48024001
Fatal fault in essential thread! Spinning...

**Environment (please complete the following information):**
 - OS: Fedora28
 - Toolchain: zephyr-sdk-0.10.3
 - Commit ID: v1.14-branch 9591025

**Comment by ioannisg** [comment]
@chen-png could you please, confirm that you do not see this error on current master ?

**Comment by chen-png** [comment]
> @chen-png could you please, confirm that you do not see this error on current master ?

Yes, i ran it with the master(commit: 5881f1), it worked well.
***** Booting Zephyr OS build zephyr-v2.0.0-1163-g5881f118c0a4 *****
Running test suite common_test

starting test - test_rand32
Generating random numbers
PASS - test_rand32

Test suite common_test succeeded

PROJECT EXECUTION SUCCESSFUL

**Comment by ioannisg** [comment]
Thanks @chen-png 
Then it seems we need to back port the driver fix in #17199  to 1.14.x branch.
Do we want to do this @nashif @dleach02 ?

**Comment by dleach02** [comment]
@ioannisg will cherry pick and merge to 1.14

**Comment by nashif** [comment]
This was fixed by #22984
