### ISSUE TITLE
stm32wb MPU failure

### ISSUE THREAD

**Issue by pavlohamov** [zephyrproject-rtos/zephyr#19848]
**Describe the bug**
Flash write operations leads to MPU failure 

**To Reproduce**
1. mkdir samples/subsys/fs/littlefs/build; cd samples/subsys/fs/littlefs/build
2. cmake -GNinja -DBOARD=nucleo_wb55rg ../ && ninja flash
3. Open serial console
4. See exception trace
![2019-10-16 15_52_57-Window](https://user-images.githubusercontent.com/52959375/66921033-19e2cf80-f02d-11e9-89fe-24a6eb568a64.png)

**Expected behavior**
Flash write operation must lead to valid read/write operation.

**Impact**
No file system could be created ins partition located on the device internal flash due to MPU exceptions

**Environment (please complete the following information):**
 - OS: Linux Ubuntu 18.04
 - Zephyr
 - master e1ae80c038

**Additional context**
```
+++ b/samples/subsys/fs/littlefs/prj.conf
@@ -21,3 +21,4 @@ CONFIG_FLASH_PAGE_LAYOUT=y
 
 CONFIG_FILE_SYSTEM=y
 CONFIG_FILE_SYSTEM_LITTLEFS=y
+CONFIG_ARM_MPU=n
```
will show that Flash operations are working properly

**Comment by pavlohamov** [comment]
@erwango I've updated description. FS sample is more convenient to troubleshoot this issue.

**Comment by pavlohamov** [comment]
Update: ```

+++ b/scripts/kconfig/kconfiglib.py
@@ -1406,10 +1406,6 @@ class Kconfig(object):
                     .format(self.config_prefix, sym.name, escape(val)))
 
             else:  # sym.orig_type in _INT_HEX:
-                if sym.orig_type is HEX and \
-                   not val.startswith(("0x", "0X")):
-                    val = "0x" + val
-
                 add("#define {}{} {}\n"
                     .format(self.config_prefix, sym.name, val))
```
Will fix the issue with sizes

**Comment by pavlohamov** [comment]
https://github.com/zephyrproject-rtos/zephyr/issues/19877

**Comment by ulfalizer** [comment]
Potential fix: https://github.com/zephyrproject-rtos/zephyr/pull/19891

Note that I didn't write the `kconfigfunctions.py` functions. Just pattern-matching a bit here.
