### ISSUE TITLE
Bluetooth: Mesh: Modular settings handling

### ISSUE THREAD

**Issue by trond-snekvik** [zephyrproject-rtos/zephyr#19850]
The mesh settings.c module manipulates the data of a lot of modules, and this pattern is causing some awkwardness in encapsulation, as experienced in #19799.

To improve encapsulation of module data, the mesh settings module could allow registering of handlers in the different mesh modules, and only take care of the multiplexing and orchestration itself. This'll improve maintainability and modularity, reducing the risk of missing functionality and impact of internal changes.

**Comment by LingaoM** [comment]
I think we should solve this ancient problem. I agree with @trond-snekvik point of view, I think each module should manage its own data storage separately.

At present, there are 10 modules that need to be decoupled from setting. The list is as follows:

1. 	BT_MESH_RPL_PENDING
2. 	BT_MESH_KEYS_PENDING
3. 	BT_MESH_NET_PENDING
4. 	BT_MESH_IV_PENDING
5. 	BT_MESH_SEQ_PENDING
6. 	BT_MESH_HB_PUB_PENDING
7. 	BT_MESH_CFG_PENDING
8. 	BT_MESH_MOD_PENDING
9. 	BT_MESH_VA_PENDING
10.	BT_MESH_CDB

My current idea is to create a handler in settings, each module implements this interface separately, as show in below:

``` C
struct bt_mesh_settings {

	/* Settings module name */
	const char *name;

	/* Setting module store flag */
	int bit;
	atomic_t *flags;

	/* Setting module store callback */
	void (*store)(void);

	/* Setting module recovery callback */
	void (*recover)(const char *name, size_t len_rd,
		    settings_read_cb read_cb, void *cb_arg);
};
```
This will completely decouple, and the settings module will not take up additional RAM to store data.

**Comment by trond-snekvik** [comment]
@LingaoM is this something you're currently working on? It's approaching the top of our task queue as well

**Comment by LingaoM** [comment]
In fact, I have always wanted to do it, but my recent work has nothing to do with it

**Comment by trond-snekvik** [comment]
Alright, I'll let you know if we start working on it.
