### ISSUE TITLE
sensor/lis2dh: using runtime scale other than 2g generates strange values

### ISSUE THREAD

**Issue by sdalu** [zephyrproject-rtos/zephyr#19872]
Using the following code to change scale of measure at runtime will result in reading wrong values for accel_xyz channel
~~~
    sensor_g_to_ms2(16, &fs_attr);
    if (sensor_attr_set(lis2dh, SENSOR_CHAN_ACCEL_XYZ,
			SENSOR_ATTR_FULL_SCALE, &fs_attr) < 0) {
	printk("Cannot set fs for LIS2DH accel\n");
    }
~~~

The problem doesn't seem to exists if scale is selected at build time (Kconfig)

**Comment by MaureenHelm** [comment]
Fixed by #20004
