### ISSUE TITLE
Bluetooth: Mesh: Thread stack can reduce by use malloc&free function

### ISSUE THREAD

**Issue by LingoMeng** [zephyrproject-rtos/zephyr#19910]
https://github.com/zephyrproject-rtos/zephyr/blob/f79fbac101f8febb459acee577e9f6b76e00acc0/subsys/bluetooth/mesh/transport.c#L610-L615

Just as above code, when `sdu_recv` be called, stack will occupy at least `CONFIG_BT_MESH_RX_SDU_MAX ` octers, this problem occurs in many places. I think we can replace a large number of stack uses with heap.

**Comment by jhedberg** [comment]
Zephyr doesn't have a heap by default, and neither the Bluetooth stack nor the mesh code requires it. Creating a heap would therefore initially likely consume more memory than the current code. Additionally the current mempool-based allocator isn't super efficient. I remember seeing some work toward a better heap allocator, so we could potentially reconsider this in the future.

Another drawback of moving to heap is that we have to start handling allocation errors everywhere, whereas now we're always guaranteed to have the memory available.
