### ISSUE TITLE
Incremental builds broken for OpenAMP sample

### ISSUE THREAD

**Issue by SebastianBoe** [zephyrproject-rtos/zephyr#19918]
**Describe the bug**
When doing an incremental build only the "app" image will be rebuilt, changes to the "remote" image will not result in a rebuild. This corrupts the build as the produced binary does not match the source code.

**To Reproduce**
1. Do a full build
2. echo "// touch a file used by the remote image" >> $ZEPHYR_BASE/kernel/device.c 
3. ninja
4. Observe that only one image is rebuilt instead of two.

**Expected behavior**
Both images should rebuild when a source file shared by them is modified.

**Impact**
Users will get a corrupt build resulting in undefined behaviour. Users must always do a clean build to safeguard themselves.

**Comment by dleach02** [comment]
@SebastianBoe , can you own this issue?
