### ISSUE TITLE
settings test tests/subsys/settings/fcb/raw failing

### ISSUE THREAD

**Issue by nashif** [zephyrproject-rtos/zephyr#19963]
A bug in sanitycheck let a a failing test go in un-noticed. The issue was introduced in 0b0f375190c061dedfe7c454a0d4d89bc43b99fd part of PR #19541.

This can now be seen here:

https://app.shippable.com/github/zephyrproject-rtos/zephyr/runs/53822/1/tests

**Comment by nashif** [comment]
@carlescufi  fyi

**Comment by rakons** [comment]
Just after quick look into test - it seems that the test requires update. After PR #19541, fcb backend does not call element callback when element was deleted (no history is presented), and test requires the callback to be called with element size equal 0.
