### ISSUE TITLE
[TOPIC-GPIO] mcux driver problems with pull configuration

### ISSUE THREAD

**Issue by pabigot** [zephyrproject-rtos/zephyr#19969]
`gpio_basic_api` currently passes on the topic branch, but #19553 has not yet been merged.  What it does is make sure that `gpio_pin_interrupt_configure()` is not invoked from `gpio_pin_configure()` unless the flags include either enabling or disabling interrupts.

If `gpio_pin_interrupt_configure()` is not invoked from `gpio_pin_configure()` `gpio_mcux` starts to fail `gpio_basic_api` because in some way the pull flags are not being set properly:
```
NOTE: cannot configure pin as disconnected; trying as input

    Assertion failed at ../src/test_gpio_port.c:389: check_pulls: (raw_in() not 
equal to false)
physical pull-down does not read low
FAIL - test_gpio_port
```

This can be demonstrated in the current topic branch by removing the pass-through to `gpio_pin_interrupt_configure()` and running the test (which is not supposed to depend on any legacy processing of interrupt-related flags in `gpio_pin_configure()`.

#19847 does not fix this problem.

**Comment by mnkp** [comment]
@pabigot Could you introduce a delay between the call to `gpio_pin_configure` and the moment you attempt to read out pin input level. The pull up resistors have typically large values, if there is any capacitance attached to the pin it will take a moment for the value to change.

**Comment by pabigot** [comment]
Thanks; I've verified that the problem does disappear with a delay before reading the signal.

**Comment by pabigot** [comment]
Should be resolved.
