### ISSUE TITLE
Add a module to Zephyr to include TF-M project and it's related repos

### ISSUE THREAD

**Issue by karl-zh** [zephyrproject-rtos/zephyr#20021]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.

Current we want Zephyr to pass [PSA certification ](https://www.arm.com/why-arm/architecture/platform-security-architecture) for security. And TF-M is an implementation that we want to merge. Currently, I have a [PR19985](https://github.com/zephyrproject-rtos/zephyr/pull/19985) which build TFM in for secure execution and  Zephyr for nonsecure execution. But the current solution will be pull all repos after build start.

**Describe the solution you'd like**

Add a module for TF-M and it's related in Zephyr, and link them in west.yml finally.

**Describe alternatives you've considered**

**Additional context**
Add any other context or graphics (drag-and-drop an image) about the feature request here.

**Repo name**
The name for the repository could be: psa_tfm or just tfm

**Comment by carlescufi** [comment]
@karl-zh thanks. Can you add a link to the tf-m repo and its license?

**Comment by karl-zh** [comment]
> @karl-zh thanks. Can you add a link to the tf-m repo and its license?

https://git.trustedfirmware.org/trusted-firmware-m.git/

BSD-3

**Comment by karl-zh** [comment]
@carlescufi Hi, could you please give some help on this ticket to further?
Thanks

**Comment by carlescufi** [comment]
@karl-zh https://github.com/zephyrproject-rtos/trusted-firmware-m

**Comment by karl-zh** [comment]
Hi
@carlescufi 
TFM build needs include other projects, shall we add 3 more projects in zephyr as it's modules?
The projects details:
https://git.trustedfirmware.org/trusted-firmware-m.git/tree/docs/user_guides/tfm_build_instruction.rst#n90

**Comment by carlescufi** [comment]
> Hi
> @carlescufi
> TFM build needs include other projects, shall we add 3 more projects in zephyr as it's modules?
> The projects details:
> https://git.trustedfirmware.org/trusted-firmware-m.git/tree/docs/user_guides/tfm_build_instruction.rst#n90

Well we already have mbedtls, is it possible to use the one we currently have? The two others are going to have to be dependencies, yes. That said this is getting into an area we haven't touched before, so can you please raise this as a TSC meeting topic for this week?

**Comment by carlescufi** [comment]
As per the TSC meeting with @microbuilder and @galak, the single repository created at https://github.com/zephyrproject-rtos/trusted-firmware-m will hold all the required dependencies, including of course tf-m itself.

**Comment by carlescufi** [comment]
Closing the issue since the repo is created and it will contain all dependencies.
