### ISSUE TITLE
sanitycheck corrupts stty in some cases

### ISSUE THREAD

**Issue by pabigot** [zephyrproject-rtos/zephyr#20026]
Manual runs of sanitycheck since 83fc06a8feb6074d1baaa0e93c56e4de76c578bb periodically complete with the following stty settings changed:

    -brkint -icrnl -ixon -icanon -echo

This is something like what I would expect if `stty sane` was not invoked at a necessary time.

I can reproduce this with some regularity with:

    sanitycheck -p mps2_an385 -T tests/kernel/

but it doesn't always leave the terminal corrupted.  There's some evidence it can also affect a subset of the flags.

**Comment by nashif** [comment]
issue confirmed.

**Comment by aescolar** [comment]
Note for whoever faces it, you can always write
``stty sane`` 
and press enter (even if you dont get the echo)
or in the worst case
Ctrl+J `stty sane`Ctrl+J

**Comment by nashif** [comment]
a fix was added in 1fe1f3a23d31efa99ef2be65dd38a6be868e1a2a
