### ISSUE TITLE
Slave PTP clock time is updated with large value when Master PTP Clock time has changed

### ISSUE THREAD

**Issue by wvk86** [zephyrproject-rtos/zephyr#20100]
**Describe the bug**
When performing gPTP time synchronization on two system connected directly to each other via Ethernet LAN cable. The PTP clock of the system running on Zephyr as Slave is updated with a very large value as close as UINT32_MAX (4,294,967,295).

**Hardware Setup/Software Configuration**
* Master
Intel i210 Ethernet Card 
Clear Linux ver. 30450 kernel 5.1.17-796.native
ptp4l version 2.0 with gPTP.cfg from https://sourceforge.net/p/linuxptp/code/ci/master/tree/configs/gPTP.cfg

* Slave
Atmel SAM E70 xPlained Board
Zephyr (master @ SHA: 813ef68554a12b6244cf9c9a7196e16f69599f00)
Zephyr SDK 0.10.3
Flash with samples/net/gptp sample application.

Both systems connected directly back-to-back via Ethernet cable without going through any network switch.

**Steps to reproduce**

Linux (Master) | Zephyr (Slave)
------------ | -------------
Power up and boot into Linux | Power up and boot into Zephyr
Run ptp4l | gPTP thread start by default
Clock synchronization... | Clock synchronization...
Quit ptp4l to stop clock sync | Clock synchronization stopped
Set the PTP clock to a much smaller value <br>using testptp tool | Clock synchronization stopped
Restart ptp4l | Clock synchronization and PTP clock <br>is being updated with a wrong large value.

**Expected behavior**
The Slave PTP clock of system running on Zephyr should be updated with the correct value.

**Impact**
Both Master and Slave Clock time off sync.

**Comment by jukkar** [comment]
ping @wvk86 can you do some testing with your setup and verify that this now works as expected?
