### ISSUE TITLE
Bluetooth: controller: split: Missing initialization of master terminate_ack flag

### ISSUE THREAD

**Issue by mtpr-ot** [zephyrproject-rtos/zephyr#20135]
The LL.TS.5.1.1 test case LL/CON/SLA/BV-11-C [Slave Sending Termination] fails in BabbleSim  after the commit fcd9612016e170abc4abb5387a2b3057ea840859, which correctly prevents MD bit being set indiscriminately.
This is caused by the master not acknowleding the TERMINATION_IND, now  the slave is no longer sending it with MD=1.

**To Reproduce**
1. Run test case LL/CON/SLA/BV-11-C, with nRF52 board as Upper- and Lower Tester
2. Test fails with disconnect cause **0x22** (BT_HCI_ERR_LL_RESP_TIMEOUT) instead of **0x16** (BT_HCI_ERR_LOCALHOST_TERM_CONN)
3. Inspecting the air trace shows that master did not acknowledge the TERMINATION_IND

**Expected behavior**
Slave (IUT) should disconnect with **0x16** (BT_HCI_ERR_LOCALHOST_TERM_CONN)

**Impact**
This issue, besides failing LL verification test, slows down BLE disconnection

**Comment by cvinayak** [comment]
@mtpr-ot This test is passing on the EBQ Qualifier, sent logs by email.

**Comment by mtpr-ot** [comment]
> @mtpr-ot This test is passing on the EBQ Qualifier, sent logs by email.

Logs recevied and look fine, thanks. However, the problem is that if you run it twice without reset, it fails at my desk.
Looking int the implementation in ull_conn.c, it looks like "lll.master.terminate_ack" is never set to zero, so after first terminate ack, it cleans up before sending the ack.
@cvinayak, can you confirm?

**Comment by cvinayak** [comment]
@mtpr-ot confirmed. I will try sending a PR tomorrow.
