### ISSUE TITLE
support external spi nor flash on mimxrt1060-evk

### ISSUE THREAD

**Issue by pabigot** [zephyrproject-rtos/zephyr#20171]
There's a nice IS25WP064 64 Mb flash on the MIMXRT1060-EVK, but AFAICT it can't be used in Zephyr because it's attached to the `flexspi0` node and there's no flexspi driver support.  Fumbling attempts to switch to lpspi which is supposed to be available on the chip (but is not supported in the SOC/board files for this target) produced no joy.

**Comment by pabigot** [comment]
Potential solution in #15364

**Comment by MaureenHelm** [comment]
Fixed by #34845
