### ISSUE TITLE
[TOPIC-GPIO] efr32mg_sltb004a fails 2-pin double-edge detection test

### ISSUE THREAD

**Issue by pabigot** [zephyrproject-rtos/zephyr#20223]
On the current topic-gpio branch the efr32mg_sltb004a fails to pass the double-edge detection test in `gpio_basic_api`.

**Comment by chrta** [comment]
I will have a look at it, since i am currently working with this board.

**Comment by pabigot** [comment]
@chrta sorry, didn't see your comment but was already working on it before you posted.

**Comment by chrta** [comment]
No problem, another race condition...

**Comment by dleach02** [comment]
@pabigot can you confirm if the merged PR fixes this problem? And then close this if it does?
