### ISSUE TITLE
[TOPIC-GPIO] sam_e70_xplained fails 2-pin active-low pull test

### ISSUE THREAD

**Issue by pabigot** [zephyrproject-rtos/zephyr#20225]
The failure occurs when the output is disconnected and the input is configured as an active-low pull-up: the pin reads low/false when it should read high/true.  Interestingly the corresponding test for active-high pull-up passes.

**Comment by dleach02** [comment]
@pabigot can you confirm that the referenced PRs fixe this issue and close if addressed?
