### ISSUE TITLE
HTTP parser error with chunked transfer encoding

### ISSUE THREAD

**Issue by ssharks** [zephyrproject-rtos/zephyr#20245]
With the fixes from #6410, the HTTP parser now breaks when there is a chunked transfer encoding. The issue reproduces with release 1.11.

I added a test to the http_header_field test and fixed the prj.cfg, so the test runs
[http_header_fields.zip](https://github.com/zephyrproject-rtos/zephyr/files/3789427/http_header_fields.zip)
I tried to involve the http_client.c to get it to reproduce, but did not succeed.

The issue seems to be directly caused by the following commit
https://github.com/zephyrproject-rtos/zephyr/commit/a2dfaebafc7c4f376db84c5eb1567ea52d188c71#diff-b2ade45d3b0611e018c938960b8e5943

Since the content-length is not set in case of a chunked encoding and therefore it is an invalid way of estimating the body length.

Bij changing the commit to:
`if ((ctx->http.req.method == HTTP_PUT ||`
`	     ctx->http.req.method == HTTP_POST)`
`	    && ((ctx->http.rsp.content_length == 0)`
`	    || (ctx->http.rsp.content_length == ULLONG_MAX))`
`	    && ((parser->flags & F_CHUNKED) == 0)) {`
`		NET_DBG("No body expected");`
`		return 1;`
`	}`
It at least it resembles the hasBody statement in the parser.

Although it seems to me like a fix in the wrong location

**Comment by jukkar** [comment]
You are using very old release 1.11, is it possible that you could use some later release? Currently we support 1.14 LTS and latest upstream.

**Comment by jukkar** [comment]
Closing as we do not support 1.11 any longer.
