### ISSUE TITLE
sifive_gpio: gpio_basic_api test fails

### ISSUE THREAD

**Issue by galak** [zephyrproject-rtos/zephyr#20337]
gpio_basic_api fails on this platform.  When two level tests occur consecutively the second will fail.  Instrumentation confirms that the registers are being configured correctly, and ip indicates that the condition was detected, but the interrupt does not occur.  Tests pass as long as no level test precedes the failing test.

gpio_api_1pin also fails.

It's not clear whether this is an issue with the PLIC, or the GPIO implementation (hardware or software).  #23714 re-enables the basic functionality, but there's more investigation to be done.

**Comment by galak** [comment]
@pabigot is this still an issue?

**Comment by pabigot** [comment]
@galak Yes.
