### ISSUE TITLE
Convert remaining entropy to Devicetree

### ISSUE THREAD

**Issue by galak** [zephyrproject-rtos/zephyr#20348]
Catch all issue to track what DT related enhancements / changes / fixes we are aiming for in the Zephyr 2.3 Release.

- [x] Convert Sensor drivers to DT - #9962
- [x] Remove old generation script (its been deprecated for at least 2 releases now)
- [x] Convert entropy drivers to DT

**Comment by pabigot** [comment]
@galak Should this include #20253 or at least some milestones toward that?

**Comment by pabigot** [comment]
In fact I'd like to see progress on as many of these as possible:

* #19904 better support for one-driver-multiple-devices (compatibles)
* #20287 instance number inconsistency with multiple compatibles
* #19448 support devices enabled/disabled at runtime (requires device API change)
* #19285 which could help resolve #20325
* #20253 which could ensure initialization order that supports dependencies

**Comment by pabigot** [comment]
@carlescufi Why did you change the name of this?  I thought the original name was right (and this *is* the issue I considered the roll-up list).

**Comment by carlescufi** [comment]
> @carlescufi Why did you change the name of this? I thought the original name was right (and this _is_ the issue I considered the roll-up list).

Because I wanted something descriptive for the Release Plan project. Hence also why I asked @galak to move your comment to wherever it is appropriate.

**Comment by galak** [comment]
Posted several PRs for entropy DTS conversion.  After those PRs, left with NRF and STM32 as the outstanding drivers that need conversion.

**Comment by galak** [comment]
NRF and STM32 entropy drivers now using DTS.
