### ISSUE TITLE
sensors: grove temperature and light drivers out of date

### ISSUE THREAD

**Issue by pabigot** [zephyrproject-rtos/zephyr#20426]
The grove temperature and light sensors pre-date the rework of the ADC API.  While they build they do not work, for reasons that include:
* On Nordic it's necessary to set the `input_positive` field, which requires a Nordic-specific constant from the HAL header:
    ```
    drv_data->ch10_cfg.input_positive = 
        (SAADC_CH_PSELP_PSELP_AnalogInput0 << CONFIG_GROVE_TEMPERATURE_SENSOR_ADC_CHANNEL);
    ```
* The ADC is configured to use the internal reference and gain 1, but it appears that driver does not account for the reference voltage varying across platforms.

**Comment by galak** [comment]
We should also convert them to devicetree.
