### ISSUE TITLE
storage/flash_map: flash_area_get_sectors can't fetch sectors on devices with non-zero flash base address

### ISSUE THREAD

**Issue by nvlsianpu** [zephyrproject-rtos/zephyr#20425]
**Describe the bug**
The function is implemented with silent assumption that addresses begins from zero.
Flash_map description structures provides partitioning info in absolute notation.

**Origin of the bug:**
The flash API  doesn't allow to fetch information about the flash begin offset.

**solution**
Intorduce API for fetch flash base address and use it for fixing flash_map module.

**related issue**
https://github.com/zephyrproject-rtos/zephyr/issues/20423

**Comment by nvlsianpu** [comment]
cc @ioannisg @carlescufi

**Comment by Laczen** [comment]
@nvlsianpu, would it not be better to hide the flash base address inside the flash api? So for all flash_read, writes, erase offset 0 refers to the flash base address.

**Comment by nvlsianpu** [comment]
After revving STM drivers I see that the uses relative addressing in flash API implementation.
The same for DT partitions description.

If flash driver and flash_map should use relative addressing then this is not a bug.

**Comment by nvlsianpu** [comment]
@galak Have you opinion on that?

**Comment by nvlsianpu** [comment]
> Flash_map description structures provides partitioning info in absolute notation.

Looks like i recognize this unproperly. Flash_map description uses relative offsets and flash driver API as well.

**Comment by nvlsianpu** [comment]
This is NOT an issue then, so I'm closing it.
