### ISSUE TITLE
User definable logger tag

### ISSUE THREAD

**Issue by koffes** [zephyrproject-rtos/zephyr#20430]
Sometimes, one desires to investigate real-time logs from multiple devices simultaneously.
One can of course print the name, ID or state of a device, but if you have lots of log output, this involves scrolling back in the log to see.

Another scenario is that there is some basic "state" in your device which would like to know at all times. 

A great feature would be to be able to prepend all log messages with a user given string.
A standard log may look like this: 
[00:21:43.946,258] <err> ble did not connect.
Where a user may now get:
`[master][00:21:43.946,258] <err> Did not connect`
or
`[00:21:43.946,258][slave] <err> Did not connect`
 
This would be supported by an API call to the logger that lets you set this string runtime. Each time an err, wrn, inf or dbg is printed, this user defined message is appended.

**Comment by koffes** [comment]
Any plans to include such a feature?

**Comment by nordic-krch** [comment]
@koffes just opened #41403.
