### ISSUE TITLE
tests/kernel/critical failed on mimxrt1050_evk board.

### ISSUE THREAD

**Issue by chen-png** [zephyrproject-rtos/zephyr#20445]
**To Reproduce**
1. west build -b=mimxrt1050_evk  tests/kernel/critical
2. west flash
3. See error

**Screenshots or console output**
***** Booting Zephyr OS build zephyr-v2.0.0-1818-g0b27cacabdab *****

Running test suite kernel_critical
starting test - test_critical

**Environment (please complete the following information):**
 - OS: Fedora28
 - Toolchain: Zephyr-sdk-0.10.3
 - Commit ID: 0b27cacabd

**Comment by maksimmasalski** [comment]
@chen-png Do you think that it is again wrong setup of the watchdog like it was with sam_e70_xplained?

**Comment by chen-png** [comment]
> @chen-png Do you think that it is again wrong setup of the watchdog like it was with sam_e70_xplained?

you can disable the watchdog config and have a try.

**Comment by pabigot** [comment]
FWIW I can reproduce this on mimxrt1060 and it looks like a stack issue.  I'll keep going and transfer to @agansari if I can't make progress.

**Comment by pabigot** [comment]
Confirmed, diagnosed, potential solutions discussed in #20585.  An extension to #15487 described in that issue would solve the problem for this platform, but the failure may apply to multiple targets.
