### ISSUE TITLE
'west flash' command failed on sam_e70_xplained board.

### ISSUE THREAD

**Issue by chen-png** [zephyrproject-rtos/zephyr#20449]
**Describe the bug**
we can't use west flash command to download test image to sam_e70.
the related PR is #20279 , and i use the 'west flash -r openocd', it's the same error.

**To Reproduce**
1.  west build -b sam_e70_xplained  samples/hello_world/
2.  west flash
3. See error

**Screenshots or console output**
 west flash 
-- west flash: rebuilding
ninja: no work to do.
-- west flash: using runner openocd
-- runners.openocd: Flashing file: /home/ztest/work/zephyrproject/zephyr/build/zephyr/zephyr.hex
Open On-Chip Debugger 0.10.0+dev-00992-g3333261df-dirty (2019-08-16-00:14)
Licensed under GNU GPL v2
For bug reports, read
        http://openocd.org/doc/doxygen/bugs.html
Unexpected command line argument: atsamv gpnvm set 1
ERROR: command exited with status 1: /home/ztest/zephyr-sdk-0.10.3/sysroots/x86_64-pokysdk-linux/usr/bin/openocd -s /home/ztest/zephyr-sdk-0.10.3/sysroots/x86_64-pokysdk-linux/usr/share/openocd/scripts -f /home/ztest/work/zephyrproject/zephyr/boards/arm/sam_e70_xplained/support/openocd.cfg -c init -c targets -c 'reset halt' -c 'flash write_image erase /home/ztest/work/zephyrproject/zephyr/build/zephyr/zephyr.hex' -c 'reset halt' -c 'verify_image /home/ztest/work/zephyrproject/zephyr/build/zephyr/zephyr.hex' 'atsamv gpnvm set 1' -c 'reset run' -c shutdown

**Environment (please complete the following information):**
 - OS: Fedora28
 - Toolchain: zephyr-sdk-0.10.3
 - Commit ID:  28fb4264

**Comment by pabigot** [comment]
Confirmed on Pop!_0S 19.04, and very odd since this worked on the same machine a couple weeks ago.

Reverting the following commit makes it work:

* 0df4a53107 [Fri Nov 1 15:43:35 2019 +0100] scripts: runners: new openocd fixes and features
