### ISSUE TITLE
[Coverity CID :205634]Code maintainability issues in /samples/net/sockets/websocket_client/src/main.c

### ISSUE THREAD

**Issue by aasthagr** [zephyrproject-rtos/zephyr#20508]
Static code scan issues seen in File: /samples/net/sockets/websocket_client/src/main.c
 Category: Code maintainability issues
 Function: setup_socket
 Component: Samples
 CID: 205634
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by aescolar** [comment]
b031a5a163f
