### ISSUE TITLE
[Coverity CID :205612]Control flow issues in /subsys/disk/disk_access_spi_sdhc.c

### ISSUE THREAD

**Issue by aasthagr** [zephyrproject-rtos/zephyr#20511]
Static code scan issues seen in File: /subsys/disk/disk_access_spi_sdhc.c
 Category: Control flow issues
 Function: sdhc_spi_detect
 Component: Other
 CID: 205612
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by aescolar** [comment]
```
567                if (err != 0) {
568                        /* Card never finished power-up */
   	
CID 205612 (#1 of 1): Logically dead code (DEADCODE)
dead_error_line: Execution cannot reach this statement: return -60;.
569                        return -ETIMEDOUT;
570                }
571        }
```

**Comment by aescolar** [comment]
c7e625f2b39

**Comment by aescolar** [comment]
@JunYangNXP

**Comment by aescolar** [comment]
@MaureenHelm note that @JunYangNXP is not a GH collaborator so I could not assign him
