### ISSUE TITLE
[Coverity CID :205633]Memory - illegal accesses in /subsys/settings/src/settings.c

### ISSUE THREAD

**Issue by aasthagr** [zephyrproject-rtos/zephyr#20514]
Static code scan issues seen in File: /subsys/settings/src/settings.c
 Category: Memory - illegal accesses
 Function: settings_call_set_handler
 Component: Other
 CID: 205633
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by ceolin** [comment]
false positive, variable `name_key` is initialized in `settings_name_steq`.

**Comment by rakons** [comment]
@ceolin 
> false positive, variable `name_key` is initialized in `settings_name_steq`.

Unless ```load_arg->subtree``` is not set to NULL - in other case, we have a problem.
