### ISSUE TITLE
[Coverity CID :205621]Memory - illegal accesses in /subsys/net/lib/websocket/websocket.c

### ISSUE THREAD

**Issue by aasthagr** [zephyrproject-rtos/zephyr#20513]
Static code scan issues seen in File: /subsys/net/lib/websocket/websocket.c
 Category: Memory - illegal accesses
 Function: websocket_connect
 Component: Networking
 CID: 205621
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by jukkar** [comment]
False positive.
