### ISSUE TITLE
[Coverity CID :205609]Control flow issues in /subsys/testsuite/ztest/src/ztest.c

### ISSUE THREAD

**Issue by aasthagr** [zephyrproject-rtos/zephyr#20516]
Static code scan issues seen in File: /subsys/testsuite/ztest/src/ztest.c
 Category: Control flow issues
 Function: z_test_1cpu_start
 Component: Other
 CID: 205609
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by aescolar** [comment]
efc1ec037be

**Comment by andyross** [comment]
Same issue as #20517 - a loop evaluates to having zero iterations because of kconfig configuration.  Needs a policy decision as to how to deal with coverity errors like this.
