### ISSUE TITLE
[Coverity CID :205652]Memory - corruptions in /tests/crypto/tinycrypt/src/ecc_dsa.c

### ISSUE THREAD

**Issue by aasthagr** [zephyrproject-rtos/zephyr#20520]
Static code scan issues seen in File: /tests/crypto/tinycrypt/src/ecc_dsa.c
 Category: Memory - corruptions
 Function: cavp_sign
 Component: Tests
 CID: 205652
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by aescolar** [comment]
e2ad85b696e As Leandro is not around anymore, and @andrewboie , you got a few around here, maybe you don't mind taking one more?

**Comment by dleach02** [comment]
source code in coverity has been purged so not sure what this was referencing. Going to close and maybe coverity will identify it again later...
