### ISSUE TITLE
imgtool: signing image fails: missing DT_FLASH_WRITE_BLOCK_SIZE

### ISSUE THREAD

**Issue by LeBlue** [zephyrproject-rtos/zephyr#20545]
**Describe the bug**
The image signing with imgtool (1.4.0) fails through west

**To Reproduce**
1. west build -b nrf52840_pca10056 -d build/sign_example zephyr/samples/subsys/mgmt/mcumgr/smp_svr
2. west sign -t imgtool -d build/sign_example -- --key SIGNING_KEY.pem
produces:
```
ERROR: imgtool parameter unknown, build directory has no device tree define DT_FLASH_WRITE_BLOCK_SIZE
```

**Environment:**
 - zephyr https://github.com/zephyrproject-rtos/zephyr/commit/80faac41bc6106ab3c679c05c45d28766258a1d1
- imgtool 1.4.0

**Additional context**
commit https://github.com/zephyrproject-rtos/zephyr/commit/9da1d41a12c114a596a9413b84638b08013f6317 drops loading device tree config needed for building the sign command line in https://github.com/zephyrproject-rtos/zephyr/blob/80faac41bc6106ab3c679c05c45d28766258a1d1/scripts/west_commands/sign.py#L208

**Comment by mbolivar** [comment]
@galak .... I guess we found an issue where a script needs DT information :)

@ulfalize @galak what's the right thing to do here? Can I import dtlib or edtlib and get the value of DT_FLASH_WRITE_BLOCK_SIZE from there somehow? If not, I may need to parse the .conf again.

**Comment by galak** [comment]
> @galak .... I guess we found an issue where a script needs DT information :)
> 
> @ulfalizer @galak what's the right thing to do here? Can I import dtlib or edtlib and get the value of DT_FLASH_WRITE_BLOCK_SIZE from there somehow? If not, I may need to parse the .conf again.

Yeah, we should import edtlib and pull the info out from there.

**Comment by mbolivar** [comment]
ACK. For those watching, the regression was introduced in 9da1d41a12c114a596a9413b84638b08013f6317. Working on a fix that doesn't require reverting that, but if you want to get unblocked you can just revert that for now.
