### ISSUE TITLE
[Coverity CID :205639]Security best practices violations in /tests/subsys/settings/functional/src/settings_basic_test.c

### ISSUE THREAD

**Issue by aasthagr** [zephyrproject-rtos/zephyr#20541]
Static code scan issues seen in File: /tests/subsys/settings/functional/src/settings_basic_test.c
 Category: Security best practices violations
 Function: test_direct_loading_filter
 Component: Tests
 CID: 205639
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by ceolin** [comment]
this seems to be a false positive. Coverity is complaining about not checking a string length in a function but this is a hardcoded variable.

**Comment by nvlsianpu** [comment]
@aasthagr  I confirm that this is false positive for reason described above.
