### ISSUE TITLE
Crypto API: Separate IV from ciphertext based on struct cipher_ctx::flags

### ISSUE THREAD

**Issue by cbsiddharth** [zephyrproject-rtos/zephyr#20561]
**Problem:**
The crypto API now prefixes the IV to to the ciphertext. This is because Tinycrypt expects the IV and ciphertext to be in the contiguous memory for better performance. This is a problem if applications what to do inplace encrypt/decrypt (`in_buf == out_buf`) as now, the `in_buf` has to be larger by 2x block length and the IV has to be removed manually. Besides, not all use-cases expect IV to be prefixed to the ciphertext.

**Proposed Solution:**
Create new flag and pass it in struct `cipher_ctx::flags` that would allow `out_buf` to have only ciphertext. This means the TC shim would now have to do some extra buffer copy but MbedTLS can skip some.

I will raise a PR based on comments here.

**Comment by cbsiddharth** [comment]
Related to: #20434

@tbursztyka @chrta @galak @nashif

**Comment by cbsiddharth** [comment]
Does anyone have any objections/suggestions on this approach? Do I go ahead to a PR?

**Comment by tbursztyka** [comment]
Go with an RFC PR.

**Comment by cbsiddharth** [comment]
@tbursztyka: I've raised PR. Could you please help add the RFC label to it? I cannot add it.

**Comment by tbursztyka** [comment]
it was just needed in the title of the PR
