### ISSUE TITLE
samples: CAN: kconfig: CONFIG_CAN_AUTO_BOFF_RECOVERY does not exist

### ISSUE THREAD

**Issue by alexanderwachter** [zephyrproject-rtos/zephyr#20692]
The sample code uses the wrong config symbol.
`CONFIG_CAN_AUTO_BOFF_RECOVERY` should be `CONFIG_CAN_AUTO_BUS_OFF_RECOVERY`

#20679 is a fix for this bug.

**Comment by ulfalizer** [comment]
Fixed
