### ISSUE TITLE
Bluetooth: host: Skip pre-scan done by bt_conn_create_le if not needed

### ISSUE THREAD

**Issue by wdhpawa** [zephyrproject-rtos/zephyr#20698]
**Is your enhancement proposal related to a problem? Please describe.**
The host API function bt_conn_create_le uses the HCI_LE_Create_Connection command to make the controller scan for and connect to an advertiser. However, bt_conn_create_le appears to be doing a pre-scan to find the advertiser before issuing the HCI_LE_Create_Connection command. This pre-scan is supposedly needed to support host-based privacy in case the controller doesn't support privacy, or the controller's resolving list cannot hold all required device identities.

In the (probably common) use cases when the controller's resolving list is (or can be made) large enough for the given application, or when the list rarely overflows, or when the application already did a scan and provides a random address, the pre-scan adds an unnecessary extra latency (and an extra risk of failure which would translate to additional latency) when connecting to devices. This might impact the responsiveness of the system as perceived by the end user.

**Describe the solution you'd like**
The bt_conn_create_le function should skip the pre-scan in cases when the host doesn't need to resolve the address, either because the controller can do it, or because the application provides a random address from a prior scan.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by joerchan** [comment]
>  This pre-scan is supposedly needed to support host-based privacy in case the controller doesn't support privacy, or the controller's resolving list cannot hold all required device identities.

As an optimization on the case where the controllers resolving list has been exceeded. It would be possible to add just the device that we wish to connect to in this case in order to start the initiator role.
Same for connecting with a whitelist, we could add all the devices in the whitelist to the resolving list, as long as rl_size >= wl_size
