### ISSUE TITLE
rtc driver may interrupt in a short time for large timeouts on cc13x2/cc26x2

### ISSUE THREAD

**Issue by vanti** [zephyrproject-rtos/zephyr#20715]
**Describe the bug**
In cc13x2_cc26x2_rtc_timer.c, depending on the setting for CONFIG_SYS_CLOCK_TICKS_PER_SEC and on the timing, z_clock_set_timeout may round up the timeout to the next tick, resulting in setThreshold() being called with a value greater than (0x80000000 + current counter value). In this case, setThreshold() would set the comparator to a value very close to the current count, thinking that the timeout had already expired.

**Expected behavior**
Large timeouts should result in the comparator being set to a value corresponding to MAX_TICKS.

**Impact**
This results in more RTC interrupts than is necessary, potentially wasting cycles and power.

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04
 - Toolchain (e.g Zephyr SDK, ...): Zephyr SDK 0.10.3
 - Commit SHA or Version used: 86461ac559a6c9a45e39ecff2beaecf785994e8a

**Comment by nashif** [comment]
fixed by #21017
