### ISSUE TITLE
Reel board Ethernet Support using the Link board ETH

### ISSUE THREAD

**Issue by Deliver88** [zephyrproject-rtos/zephyr#20741]
Does the reel board support ethernet connection, including the samples socket/http(s), telnet etc. by using the Link board ETH?  Or does it require adjustments? It would be an alternative for the nRF52840 PDK (not available and supported - according to my information) board then, or?

Thanks

**Comment by jfischer-phytec-iot** [comment]
There is shield support for [link board ETH ](https://docs.zephyrproject.org/latest/boards/shields/link_board_eth/doc/index.html). You can use it with any board that provides corresponding connector. Also nRF52840 DK is well supported and [available](https://octopart.com/search?q=nRF52840%20DK). [Slack channel](https://docs.zephyrproject.org/latest/guides/getting-help.html?highlight=slack) is more suitable for this kind of questions.
