### ISSUE TITLE
shell: shell_execute_cmd introduce new line

### ISSUE THREAD

**Issue by sdalu** [zephyrproject-rtos/zephyr#20750]
when executing `shell_execute_cmd` in a shell command, unwanted new line are introduced.

~~~c
static int cmd_sys_tz(const struct shell *shell, size_t argc, char **argv)
{
    shell_print(shell, "TZ: %s", "Europe/Paris");
    return 0;
} 
static int cmd_sys(const struct shell *shell, size_t argc, char **argv)
{
    shell_execute_cmd(shell, "sys tz");
    return 0;
}
~~~

~~~
uart:~$ sys tz
TZ: Europe/Paris
~~~

~~~
uart:~$ sys

TZ: Europe/Paris
~~~

Expected:
~~~
uart:~$ sys
TZ: Europe/Paris
~~~

**Comment by jakub-uC** [comment]
This behavior is correct and in fact expected. First of all function: `shell_execute_cmd` was mainly introduced for unit test purposes. It is highlighted in the API description.

Second of all when the shell is executing a command it moves the cursor to the next line. In the example, you have provided when executing `cmd_sys` in fact you are executing two commands: `cmd_sys` by the shell engine and `sys tz` using API function.
Hence two new lines. 

In fact, what shell "sees" during your command execution is:
```
uart:~$ sys
uart:~$ sys tz  -> this is not printed by the function `shell_execute_cmd` but it is visible by the shell in the command buffer
TZ: Europe/Paris
```
