### ISSUE TITLE
Feature Request: Half-duplex UART shell backend

### ISSUE THREAD

**Issue by n3rd4i** [zephyrproject-rtos/zephyr#20780]
Is ther any easy way (config option) to make the shell backend, UART driver to communicate in half-duplex way?

Basically discard all RX bytes while TX is printing on the console.

**Comment by nordic-krch** [comment]
@n3rd4i, no there is no such option.

**Comment by n3rd4i** [comment]
This could be done by discarding rx data while the tx is busy, potentially configurable from KConfig?
It could be helpful to have such support in the future, should I change this ticket to feature request?
