### ISSUE TITLE
our nRF52840 board power management sleep duration

### ISSUE THREAD

**Issue by atKeitaroTakahashi** [zephyrproject-rtos/zephyr#20892]
I want to make our nRF52840 board by zephyr-v2.0.0 work into low power mode for specified seconds at k_sleep.
But our board often sleeps 512 seconds longer than specified seconds if we specified time longer 512 seconds.
For example, if we specified 600 seconds, our board often sleeps 1112 seconds.
I only understand this probrem is related nRF52 RTC overflow.
What's the difference when sleeped specified seconds and sleeped 512 seconds longer?
Just in case I tried zephyr-v2.1.0-rc1, but the situation does not change.
Incidentally, consumption when our board sleeped is 5uA.

**Comment by pabigot** [comment]
Does your application stay completely asleep for the entire 600/1112 second period, or does it have to wake up to do other things like wireless communication, react to external signals, get timer callbacks?  If it wakes, how frequently?

**Comment by pabigot** [comment]
Confirmed: a sleep of 600 s (10:00 m:s) on Nordic nrf52840_pca10056 will not wake until 18:32 m:s external time has passed.  The Zephyr uptime clock will show 600 s elapsed.

The bug is not present on nucleo_l476rg so it's likely to be specific to the Nordic timer infrastructure.

**Comment by atKeitaroTakahashi** [comment]
> Does your application stay completely asleep for the entire 600/1112 second period,

Our application stay completely asleep for the entire 600/1112 second period.

> If it wakes, how frequently?

I tried 136 times, problem happened 103 times.
103/136: wake up on 1112 seconds.
33/136: wake up on 600 seconds.

> The Zephyr uptime clock will show 600 s elapsed.

We confirmed it as well. 
I was relieved it isn't inherent probrem on our board.

**Comment by carlescufi** [comment]
@nordic-krch can you check if this can be something related to our system timer driver?

**Comment by nordic-krch** [comment]
i will try to investigate

**Comment by pabigot** [comment]
I'm on this.  I know what the problem is, and it probably applies to other boards.

**Comment by nordic-krch** [comment]
ok
