### ISSUE TITLE
doc: Kconfig section in board_porting.rst should be moved or removed

### ISSUE THREAD

**Issue by erwango** [zephyrproject-rtos/zephyr#20915]
**Describe the bug**

An important piece of Kconfig documentation sits under doc/guides/porting/board_porting.rst
Another part of Kconfig doc is in doc/guides/kconfig/index.rst but does not reference the other part.

I think most of Kconfig relative doc in board_porting section should be moved in actual kconfig guide. 
Some part might be cleaned as well ('Old Zephyr Kconfig behavior for defaults') for instance.

**Comment by ulfalizer** [comment]
Yeah, another iffy thing at the moment is that the Kconfig tips page has turned into a dumping ground for random Kconfig documentation (like documentation for the `kconfigfunctions.py` macros). Might be nice to keep the "generic" Kconfig stuff separate.

**Comment by erwango** [comment]
> Might be nice to keep the "generic" Kconfig stuff separate.

I'd say: better to put everything in one place (`guides/Kconfig`) but make use of different pages  (General, tips, scripts, ..)

**Comment by aescolar** [comment]
I reclassify this as an enhancement, as it is a request for an improvement to the documentation usability, independently of how welcome it may be, and not a bug that prevents using the system or a reason to gate releases.

**Comment by ulfalizer** [comment]
Working on this now.

**Comment by ulfalizer** [comment]
Done now. See https://github.com/zephyrproject-rtos/zephyr/pull/21133, which moves lots of Kconfig documentation into its own dedicated section in User and Developer Guides, with links from e.g. Application Developmend the board porting guide.
