### ISSUE TITLE
No SOURCES given to target: drivers__gpio

### ISSUE THREAD

**Issue by tluio** [zephyrproject-rtos/zephyr#20969]
Hello!
I'm new in zephyr. I did as Getting Started Guide, but when I ran 'west build -p auto -b qemu_x86  samples/basic/blinky', I got an error:
`CMake Error at ../../../cmake/extensions.cmake:372 (add_library):
  No SOURCES given to target: drivers__gpio
Call Stack (most recent call first):
  ../../../cmake/extensions.cmake:349 (zephyr_library_named)
  ../../../drivers/gpio/CMakeLists.txt:3 (zephyr_library)
`
I have tried a lot but still cannot solve the problem. Any suggestion?

**Comment by jfischer-phytec-iot** [comment]
Hi, I suggest to use real hardware instead, or which LED should blink? Please take a look at this https://docs.zephyrproject.org/latest/guides/getting-help.html?highlight=slack.
