### ISSUE TITLE
Bluetooth: Mesh: seg_tx_reset in the transport layer

### ISSUE THREAD

**Issue by Campou** [zephyrproject-rtos/zephyr#20970]
In the function `seg_tx_reset()`, before trying to do `net_buf_unref()` with the adv buf, do we need to set the `busy` flag to `0U`, in cast the adv buf has already been put in the mesh adv_queue?
Thanks.

**Comment by aescolar** [comment]
CC @trond-snekvik @jhedberg

**Comment by jhedberg** [comment]
@Campou yes, I think that makes sense. It seems analogous to what we do in `friend_clear()` in `friend.c`. Do you want to try submitting a PR for it?

**Comment by Campou** [comment]
@jhedberg Thanks, i will submit a PR for this.
