### ISSUE TITLE
Read out heap space used and unallocated

### ISSUE THREAD

**Issue by kristoftjonck** [zephyrproject-rtos/zephyr#21033]
**Is your feature request related to a problem? Please describe.**
I need to know how much heap size is allocated, how much is used and how much is left. Like the "xPortGetFreeHeapSize()" in freeRTOS.

**Describe the solution you'd like**
Function to read out the total heap size, used allocated heap space / unallocated heap space left.

Not sure if it is implemented, but could not find it in the documentation.

**Comment by aescolar** [comment]
CC @andyross @andrewboie

**Comment by carlescufi** [comment]
@andyross could you consider adding this to your new heap allocator?

**Comment by andyross** [comment]
Duplicate of #23076
