### ISSUE TITLE
Help: Pull request "Identity/Emails issues"

### ISSUE THREAD

**Issue by LuoZhongYao** [zephyrproject-rtos/zephyr#21077]
I have a pull request #21073 , the zephyrbot reported "Identity / Emails issues", I checked the commits, but couldn't find the problem.

**Comment by aescolar** [comment]
Answered in https://github.com/zephyrproject-rtos/zephyr/pull/21073#issuecomment-559721821 , please continue the discussion in the PR itself.
Closing this question
