### ISSUE TITLE
Slack link at https://www.zephyrproject.org/ is expired

### ISSUE THREAD

**Issue by jmgao** [zephyrproject-rtos/zephyr#21102]
The slack link at https://www.zephyrproject.org points to https://join.slack.com/t/zephyrproject/shared_invite/enQtNDgwNzk5MTU3NTA3LWNhZjc4MzM4Nzg5NGRiNTA2OGVhN2ZlNzZmYWE5Yjc2ZDIwYjYzNGJmMzNiYmY2MTdiYmQ1M2I4NGEzMmUzZjA which is expired (but still works if you already have an account).

The one at https://lists.zephyrproject.org/g/devel works (and points to https://join.slack.com/t/zephyrproject/shared_invite/enQtNzE2Mzk3MjQ2NjEzLWFiYmFiMGZlMWEyZTg0ZDI2YmMxM2Y4MDczNTRjOTEyNzYyZWU2MzdjODFlZWI0NmUwYjJlN2EwMmI1ZGE5MDQ instead)

@ulfalizer @dbkinder

**Comment by carlescufi** [comment]
This is an issue with the website itself, so we can't cover it here. I have reported this internally.
