### ISSUE TITLE
netusb: RNDIS host support

### ISSUE THREAD

**Issue by Jeepgoing** [zephyrproject-rtos/zephyr#21121]
Hi, i am testing Zephyr connect to Android Phone with Type-C, i found Android Phone only supports RNDIS Device mode, so it that mean Zephyr device should support RNDIS Host?

I also tried ECM mode, but Zephyr can't run DHCP Server, so Android Phone doesn't have IP

**Comment by tuobaye1988** [comment]
Hi， I have same question

**Comment by carlescufi** [comment]
@Jeepgoing Zephyr only supports the USB Device role, not USB Host.

**Comment by Jeepgoing** [comment]
@carlescufi @finikorg I think RNDIS have Host and Decice itself , is it possible RNDIS host run on USB device?

**Comment by finikorg** [comment]
@Jeepgoing Do you have Android phone with OTG?

**Comment by Jeepgoing** [comment]
yes @finikorg  It's have OTG function

**Comment by finikorg** [comment]
> yes @finikorg It's have OTG function

Then Zephyr is USB device and RNDIS should work

**Comment by Jeepgoing** [comment]
@finikorg But  Android phone need DHCP by Zephyr, I can't find DHCP server support

**Comment by jukkar** [comment]
If Zephyr is compiled with auto IPv4 support `CONFIG_NET_IPV4_AUTO=y`, the system should start using 169.254.xxx.xxx addresses so there should be no need for DHCP server support.

**Comment by Jeepgoing** [comment]
@jukkar you mean Zephyr Device and Android Phone all use default IP?

**Comment by jukkar** [comment]
> you mean Zephyr Device and Android Phone all use default IP?

No, I mean that if devices are configured to use auto IPv4 addresses, then they will select suitable IPv4 addresses from 169.254/16 block in order to communicate with each other. Linux typically has this support automatically enabled but in zephyr you need to manually enable this.

**Comment by finikorg** [comment]
Closing per comments
