### ISSUE TITLE
Interrupts do not work on UP Squared board

### ISSUE THREAD

**Issue by dcpleung** [zephyrproject-rtos/zephyr#21156]
**Describe the bug**
`samples/boards/up_squared/gpio_counter` no longer works on UP Squared due to interrupts no longer being delivered.

**To Reproduce**
1. cd samples/boards/up_squared/gpio_counter/
2. mkdir build; cd build
3. cmake -DBOARD=up_squared
4. make
5. Set BIOS configurations described inside `src/main.c`.
6. Boot the Zephyr image according to documentation.
7. Observe the counter would not increment when inputs are pulsed on HAT pin 16.

**Expected behavior**
The counter would increment, and reflected on the 4-bit output of pin35/37/38/40.

**Impact**
- Broken board support.
- Blocking verification of GPIO API changes and app updates.

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: Zephyr SDK 0.10.3
 - Commit: 58e2057aaf9af4d299814f4aece585e287587162

**Comment by dleach02** [comment]
Change was reverted.

**Comment by jhedberg** [comment]
@dcpleung do you know if anyone is looking at this? Should it be reassigned to someone else?

**Comment by dcpleung** [comment]
I have been looking at this on-and-off. The problems are lack of documentation on IO-APIC, and QEMU having the 0xFF broadcast which does not seem to be the case for actual hardware. One of the solution is to use logical destination, which works on UP^2 but fails QEMU. So more investigation is needed.

**Comment by andrewboie** [comment]
Reopening this. I had to revert @ZideChen0 change #22848 as it was causing timeouts when running tests on qemu_x86_64. Needs further analysis.

**Comment by dcpleung** [comment]
Another attempt #23325.
