### ISSUE TITLE
Error west flash

### ISSUE THREAD

**Issue by pankaj18** [zephyrproject-rtos/zephyr#21240]
Open On-Chip Debugger 0.10.0
Licensed under GNU GPL v2
For bug reports, read
	http://openocd.org/doc/doxygen/bugs.html
/Users/pankajjadhav/zephyrproject/zephyr/boards/arm/stm32_min_dev/support/openocd.cfg:1: Error: Can't find interface/stlink.cfg
in procedure 'script' 
at file "embedded:startup.tcl", line 60
at file "/Users/pankajjadhav/zephyrproject/zephyr/boards/arm/stm32_min_dev/support/openocd.cfg", line 1
ERROR: command exited with status 1: /usr/local/bin/openocd -f /Users/pankajjadhav/zephyrproject/zephyr/boards/arm/stm32_min_dev/support/openocd.cfg -c init -c targets -c 'reset halt' -c 'flash write_image erase /Users/pankajjadhav/zephyrproject/zephyr/build/zephyr/zephyr.hex' -c 'reset halt' -c 'verify_image /Users/pankajjadhav/zephyrproject/zephyr/build/zephyr/zephyr.hex' -c 'reset run' -c shutdown

**Comment by aescolar** [comment]
cc @mbolivar

**Comment by chrta** [comment]
Was an stlink programmer properly connected?

I believe there is no on-board programmer, but this is not clearly documented in the board documentation of zephyr.

**Comment by mbolivar** [comment]
> I believe there is no on-board programmer, but this is not clearly documented in the board documentation of zephyr.

Looks like you're right: https://embedjournal.com/iot-rtos-zephyr-stm32-minimum-system-development-board/#hardware-setup

@pankaj18 can you please answer @chrta 's question?

> Was an stlink programmer properly connected?

Please also read the embedjournal link above if you need more information.

**Comment by yhyuan** [comment]
I am having the same issue. It seems openocd fails to find the stlink.cfg. I am not sure how to fix it.
