### ISSUE TITLE
tests/net/net_pkt failed on mimxrt1050_evk board.

### ISSUE THREAD

**Issue by chen-png** [zephyrproject-rtos/zephyr#21257]
**Describe the bug**
It was similar to the issue #20088 and #20007.

**To Reproduce**
1.  west build -b=mimxrt1050_evk -p=auto tests/net/net_pkt
2.  west flash
3.  See error

**Screenshots or console output**

E: ***** BUS FAULT *****
E: Precise data bus error
E: BFAR Address: 0x3a4f7828
E: r0/a1: 0x00000000 r1/a2: 0x6000b7f9 r2/a3: 0x00000000
E: r3/a4: 0x3a4f7820 r12/ip: 0x00000000 r14/lr: 0x60003ceb
E: xpsr: 0x41000000
E: Faulting instruction address (r15/pc): 0x60006a46
E: >>> ZEPHYR FATAL ERROR 0: CPU exception on CPU 0
E: Current thread: 0x800011d0 (sysworkq)
E: Halting system

**Environment (please complete the following information):**
 - OS: Fedora28
 - Toolchain : zephyr-sdk-0.10.3
 - Commit ID: e3dc05f14d

**Comment by jukkar** [comment]
I just tested this and I could only trigger the issue half of the time. All the tests pass and the error is printed only after all the tests are run. This is some timing issue that happens semi-randomly, I will investigate.
