### ISSUE TITLE
Compiler warnings in flash.h: invalid conversion from 'const void*' to 'const flash_driver_api*'

### ISSUE THREAD

**Issue by szundi** [zephyrproject-rtos/zephyr#21290]
There is a missing cast in `/include/drivers/flash.h`, i checked it on master too.

These are only warnings:
`In file included from ../src/main.cpp:15:
/Users/szundi/zephyrproject/zephyr/include/drivers/flash.h: In function 'int z_impl_flash_read(device*, off_t, void*, size_t)':
/Users/szundi/zephyrproject/zephyr/include/drivers/flash.h:104:44: warning: invalid conversion from 'const void*' to 'const flash_driver_api*' [-fpermissive]
  104 |  const struct flash_driver_api *api = dev->driver_api;
      |                                       ~~~~~^~~~~~~~~~
      |                                            |
      |                                            const void*
/Users/szundi/zephyrproject/zephyr/include/drivers/flash.h: In function 'int z_impl_flash_write(device*, off_t, const void*, size_t)':
/Users/szundi/zephyrproject/zephyr/include/drivers/flash.h:128:44: warning: invalid conversion from 'const void*' to 'const flash_driver_api*' [-fpermissive]
  128 |  const struct flash_driver_api *api = dev->driver_api;
      |                                       ~~~~~^~~~~~~~~~
      |                                            |
      |                                            const void*
/Users/szundi/zephyrproject/zephyr/include/drivers/flash.h: In function 'int z_impl_flash_erase(device*, off_t, size_t)':
/Users/szundi/zephyrproject/zephyr/include/drivers/flash.h:159:44: warning: invalid conversion from 'const void*' to 'const flash_driver_api*' [-fpermissive]
  159 |  const struct flash_driver_api *api = dev->driver_api;
      |                                       ~~~~~^~~~~~~~~~
      |                                            |
      |                                            const void*
/Users/szundi/zephyrproject/zephyr/include/drivers/flash.h: In function 'int z_impl_flash_write_protection_set(device*, bool)':
/Users/szundi/zephyrproject/zephyr/include/drivers/flash.h:185:44: warning: invalid conversion from 'const void*' to 'const flash_driver_api*' [-fpermissive]
  185 |  const struct flash_driver_api *api = dev->driver_api;
      |                                       ~~~~~^~~~~~~~~~
      |                                            |
      |                                            const void*
/Users/szundi/zephyrproject/zephyr/include/drivers/flash.h: In function 'size_t z_impl_flash_get_write_block_size(device*)':
/Users/szundi/zephyrproject/zephyr/include/drivers/flash.h:272:44: warning: invalid conversion from 'const void*' to 'const flash_driver_api*' [-fpermissive]
  272 |  const struct flash_driver_api *api = dev->driver_api;
      |                                       ~~~~~^~~~~~~~~~
      |                                            |
      |                                            const void*`

**Comment by nvlsianpu** [comment]
Thanks for reporting and fix providing!
