### ISSUE TITLE
ARC: syscall register save/restore needs backport to 1.14

### ISSUE THREAD

**Issue by andrewboie** [zephyrproject-rtos/zephyr#21306]
The PR https://github.com/zephyrproject-rtos/zephyr/pull/19404 fixed a serious issue with saving/restoring registers on ARC architecture.

This fix needs to be backported to the V1.14 branch.

In addition to the fixes stated in its commit message, it also fixes a problem where registers r3-r5 were not properly saved/restored if these registers were not used as system call arguments (arch_syscall_invoke0, for example)

**Comment by vonhust** [comment]
Fixed in #21364
