### ISSUE TITLE
error update for project civetweb

### ISSUE THREAD

**Issue by boonpin1975** [zephyrproject-rtos/zephyr#21321]
this error occurs when doing west update 

![image](https://user-images.githubusercontent.com/17423725/70677993-b93ddf00-1ccb-11ea-9d2a-5f927470033e.png)

**Comment by FWeissenb** [comment]
Same here.

`=== updating civetweb (modules\lib\civetweb):
fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'`

That's the error message not shown in the screenshot above.

**Comment by jukkar** [comment]
Is this the same issues as #21426?

**Comment by szundi** [comment]
> Is this the same issues as #21426?

workaround suggested not worked for me with this problem

**Comment by boonpin1975** [comment]
this work around is not working on my system

**Comment by carlescufi** [comment]
@szundi and @boonpin1975 can you please comment on https://github.com/zephyrproject-rtos/zephyr/issues/21426? I am closing this since it's clearly a duplicate.

**Comment by szundi** [comment]
Updated to newer git, deleted the folder that holds civetweb with all the others and this fixed it, after this the update worked. Before the delete it did not.
