### ISSUE TITLE
Apparent network context leak with offloading driver (u-blox Sara r4)

### ISSUE THREAD

**Issue by gpaquet85** [zephyrproject-rtos/zephyr#21328]
**Describe the bug**
I have an issue when I try to make multiple MQTT connection/disconnection.
I focused on net_context management.
Indeed in net_context_get function, I saw that I reached CONFIG_NET_MAX_CONTEXTS (equal to 10 in my prj.conf).
For your information, I use UBLOX sara r4 driver (on zephyr 1.14.1) and I wonder if contexts are well managed in this revision (or new one?), especially when socket is closed ?

**To Reproduce**
Compiling https://github.com/zephyrproject-rtos/zephyr/tree/master/samples/net/mqtt_publisher:
1. mkdir build; cd build
2. cmake -DBOARD=boards\nrf52840_pca10059 -DSHIELD=sparkfun_sara_r4 -DCONF_FILE="prj.conf overlay-wncm14a2a.conf" (I am not sure of this configuration because I did this with our own board)
3. make

**Expected behavior**
After 10 (equal to CONFIG_NET_MAX_CONTEXTS) connection/disconnection in TCP, you should have this behavior: 
[try_to_connect:233] mqtt_connect: -2 <ERROR>.

**Impact**
It is not possible to communicate anymore in MQTT (TCP) because it is not possible to connect to broker after CONFIG_NET_MAX_CONTEXTS attemps

**Screenshots or console output**
![image](https://user-images.githubusercontent.com/33019844/70696083-4466a700-1cc3-11ea-846d-59d49953f279.png)

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain ARM-GCC
 - Tag: v1.14.1

**Additional context**
I also saw an issue in UBLOX SARA R4 socket close management when URC +UUCLOSE happens.
I am not sure that this issue is linked to our issue. Moreover, maybe it is well managed in new revision

**Comment by pfalcon** [comment]
cc: @jukkar, @mike-scott

**Comment by pfalcon** [comment]
> cmake -DBOARD=board_xyz

@gpaquet85: Are you sure such a board exists?

**Comment by gpaquet85** [comment]
> 
> 
> > cmake -DBOARD=board_xyz
> 
> @gpaquet85: Are you sure such a board exists?

Indeed I forgot to change board name in my description. Sorry about that. I correct it in bug description right now

**Comment by WilliamGFish** [comment]
Isn't the the +UUSOCL  a remote close response? I think it is worth looking at the remote server connection.

You may need look your server to get some clues.

**Comment by gpaquet85** [comment]
> 
> 
> Isn't the the +UUSOCL a remote close response? I think it is worth looking at the remote server connection.
> 
> You may need look your server to get some clues.

Yes this +UUSOCL come from remote server. However, I can't modify anythinbg on this one because it is handled by Orange operator

**Comment by WilliamGFish** [comment]
> > Isn't the the +UUSOCL a remote close response? I think it is worth looking at the remote server connection.
> > You may need look your server to get some clues.
> 
> Yes this +UUSOCL come from remote server. However, I can't modify anything on this one because it is handled by Orange operator

I get that response if you send to many malformed messages. I use Google, afafruit and bluemix. I've got that result when the JSON message upsets the server. 

It's worth checking...

**Comment by gpaquet85** [comment]
> 
> 
> > > Isn't the the +UUSOCL a remote close response? I think it is worth looking at the remote server connection.
> > > You may need look your server to get some clues.
> > 
> > 
> > Yes this +UUSOCL come from remote server. However, I can't modify anything on this one because it is handled by Orange operator
> 
> I get that response if you send to many malformed messages. I use Google, afafruit and bluemix. I've got that result when the JSON message upsets the server.
> 
> It's worth checking...

@WilliamGFish thanks for your feedback it looks interesting. I will have a look.

**Comment by mike-scott** [comment]
@gpaquet85 Can you see if this is fixed by https://github.com/zephyrproject-rtos/zephyr/pull/22149

**Comment by gpaquet85** [comment]
@mike-scott it is ok for me. This is clearly fixed by your PR. Thanks again.
