### ISSUE TITLE
z_arch_cpu_halt() should enter deep power-down where supported

### ISSUE THREAD

**Issue by pabigot** [zephyrproject-rtos/zephyr#21342]
Are we assuming that power consumption does not matter here?

_Originally posted by @pizi-nordic in https://github.com/zephyrproject-rtos/zephyr/pull/18977/files_

**Comment by andrewboie** [comment]
it's just work that needs to be done, I'm sure a lot of people would be happy if you wanted to implement this for ARM (overriding the __weak placeholder implementation in the kernel)

**Comment by nashif** [comment]
isnt z_arch_cpu_halt declared weak for a reason here? You can always override it. Not sure what the enhancement request is..

**Comment by nashif** [comment]
closing, this is outdated, this API does not exist anymore.
