### ISSUE TITLE
RFC: API Change: PWM: add support for inverted PWM signals

### ISSUE THREAD

**Issue by henrikbrixandersen** [zephyrproject-rtos/zephyr#21384]
## Introduction

The Zephyr PWM API currently lacks a way of  requesting an inverted PWM pulse (active-low) when setting up the period and pulse width of a PWM pin. This is useful when driving external, active-low circuitry with a PWM signal.

### Problem description

The current Zephyr PWM API only allows for a "poor mans" inverted PWM pulse by "inverting" the pulse width, but without proper API support for inverted PWM signals it is not possible to do edge-aligned PWM with either a mix of active-low/active-high or any number of active-low PWM signals (which is often needed for motor control).

Some PWM signals will always need to be driven inverted ("active-low"), e.g. LEDs where the current is sourced from VCC and sinked into the SoC. Other PWM signals sometimes needs to be driven with normal polarity and at other times with inverted polarity (e.g. for motor control applications).

The above calls for both a way to specify PWM polarity for a given PWM client/consumer in the device tree (compile-time) and to be able to specify the polarity through the PWM API (run-time).

### Proposed change

Please see PR #20657 for the proposed changes.

## Detailed RFC

Please see PR #20657 for the details.

### Proposed change (Detailed)

Please see PR #20657 for the detailed proposed changes.

### Dependencies

Upon accepting this change, out-of-tree device trees needs to updated to specify PWM flags for any PWM clients/consumers referencing PWM controller drivers which now support flags.

Furthermore, all calls to the PWM API functions needs to changed to match the new function prototypes (e.g. by passing a 0 for the flags parameter).

Any out-of-tree PWM controller drivers will also need to be updated to match the new PWM API function prototypes.

### Concerns and Unresolved Questions

None so far.

## Alternatives

None to my knowledge.

**Comment by StefJar** [comment]
thx for pushing it.
I was asking about the pwm polarity on slack.
My practical case is the pwm generation for an RGB LED. Because of resistors the board comes up after init with all 3 LEDs with maximum brightness. So I was looking for a solution and figured out that the sm32 port of the pwm driver(realized via TIM) does not support reversed polarity. My stm32f412 supports that and this stuff is somehow easy addable via LL/HAL.
