### ISSUE TITLE
NUCLEO-H745ZI-Q Support

### ISSUE THREAD

**Issue by Nukersson** [zephyrproject-rtos/zephyr#21399]
The support of ST's [NUCLEO-H745ZI-Q](https://www.st.com/en/evaluation-tools/nucleo-h745zi-q.html)  would be nice.

**Comment by gon1332** [comment]
@carlescufi It's `platform: ST`.

**Comment by carlescufi** [comment]
> @carlescufi It's platform: STM32.

Oops, sorry about that.

**Comment by Nukersson** [comment]
Can I implement this?

**Comment by galak** [comment]
> Can I implement this?

yes feel free to provide a PR with support.

**Comment by Nukersson** [comment]
Okay. Then I am working on this problem.
