### ISSUE TITLE
sanitycheck: cmd.exe colorized output

### ISSUE THREAD

**Issue by JordanYates** [zephyrproject-rtos/zephyr#21409]
**Describe the bug**
The windows cmd.exe terminal does not respect ANSI escape sequences for colors.
These escape sequences are used in sanitycheck for formatting the output.
Alternate tools (west/log.py) use the colorama library for colorizing output.

**To Reproduce**
On windows
```python.exe zephyr\scripts\sanitycheck --ninja -T zephyr\tests\unit\util```

**Expected behavior**
Nice colorized output

![Colorized](https://user-images.githubusercontent.com/8476715/70898614-b41cbf00-2040-11ea-8a73-154c551e3479.png)

**Actual behavior**

![ANSI_Sequence](https://user-images.githubusercontent.com/8476715/70898632-bda62700-2040-11ea-9699-1681486c66c1.png)

**Impact**
Minor annoyance, makes the test output hard to read.

**Environment**
 - OS: Windows 10
 - Commit 5af54075703c248fae2bf69a50909bf2e3cc977e

**Additional context**
Issue can be resolved via
```
import colorama
colorama.init()
```

**Comment by stephanosio** [comment]
This is still an issue. We need to call `colorama.init()` at the beginning for this to work properly.
