### ISSUE TITLE
civetweb triggers an error on Windows with Git 2.24

### ISSUE THREAD

**Issue by carlescufi** [zephyrproject-rtos/zephyr#21426]
**Describe the bug**
Using west and Git on Windows worked fine up until Git 2.23 (included).
When running `west update` using Git 2.24 on Windows, you get:

```
fatal: filename in tree entry contains backslash: '\'
error: https://github.com/zephyrproject-rtos/civetweb did not send all necessary objects
```

**To Reproduce**

On Windows, and with Git 2.24:
```
west init zephyr
cd zephyr
west update
```

**Additional Context**

- Git commit that introduced the issue: https://github.com/git/git/commit/e1d911dd4c7b76a5a8cec0f5c8de15981e34da83
- Potential civetweb commit with the issue: https://github.com/zephyrproject-rtos/civetweb/commit/4ac467e3e07a2abb02b894c0b508e9885ee4d7d8
- Civetweb issue: https://github.com/civetweb/civetweb/issues/812
- Git for Windows issue: https://github.com/git-for-windows/git/issues/2435

**Workarounds**

- Disable [core.protectNTFS](https://git-scm.com/docs/git-config#Documentation/git-config.txt-coreprotectNTFS): `git config --global core.protectNTFS false`

- Update to Git 2.25

**Environment (please complete the following information):**
 - OS: Windows
 - Git for Windows 2.24
 - Commit: civetweb 99129c5efc907ea613c4b73ccff07581feb58a7a

**Comment by mbolivar** [comment]
Users on the duplicate issue (#21321) reported the `git config --global core.protectNTFS` workaround did not work for them.

I would recommend:

1. apply the `git config work around`
2. backing up any local commits, then deleting the civetweb directory (modules/lib/civetweb) entirely
3. retrying `west update`

**Comment by andrewboie** [comment]
A note about this in our documentation would be nice, I tripped over this the other day.

**Comment by mbolivar** [comment]
> A note about this in our documentation would be nice, I tripped over this the other day.

The patch fixing it appears to be making its way through review on mainline git and git-for-windows, so hopefully a new version with the fix will be out soon and we can just close this.

**Comment by carlescufi** [comment]
Closing this issue. See workarounds in the description

**Comment by szundi** [comment]
just a tip: if you get the error with git 2.26+, delete modules/lib/civetweb folder, then retry with west update, this fixed me some bad state
