### ISSUE TITLE
Added nucleo-f767zi board support and would like to share

### ISSUE THREAD

**Issue by rolandma** [zephyrproject-rtos/zephyr#21422]
I added nucleo-f767zi board support and would like to upload to share.

**Comment by erwango** [comment]
@rolandma , please feel free to push a PR.
You can follow contribution guidelines documented on zephyr documentation.
Also, you can use the following PR as example: https://github.com/zephyrproject-rtos/zephyr/pull/20994

**Comment by rolandma** [comment]
@erwango Okay, I created a PR. I tested with the blinky sample app compilation. The board definition is tested with other projects I'm working on and also flashed onto the actual board.
