### ISSUE TITLE
sanitycheck: hardware map generation unexpected exit during the first attempt

### ISSUE THREAD

**Issue by maksimmasalski** [zephyrproject-rtos/zephyr#21475]
**Describe the bug**
When I create a hardware map for any board, for example reel_board, it finishes work on the step:
```
[maksim@maksim-nuc scripts]$ sanitycheck --device-serial /dev/ttyACM0 --generate-hardware-map mec.file
INFO    - Scanning connected hardware...
[maksim@maksim-nuc scripts]$
```
At the same time hardware map file `mec.file` was succesfully created, at can be opened.
When I run the same command at the second time, it gives me the full output.
```
[maksim@maksim-nuc scripts]$ sanitycheck --device-serial /dev/ttyACM0 --generate-hardware-map mec.file
INFO    - Scanning connected hardware...
INFO    - Registered devices:

| Platform   | ID                       | Serial device   |
|------------|--------------------------|-----------------|
| unknown    | 024002010E8B3E61F375C3D9 | /dev/ttyACM0    |
[maksim@maksim-nuc scripts]$ 
```

**To Reproduce**
1. Use the latest master 17d066b9dc0e0ac632edce4a2e723332ee950ec6
2. Connect  reel_board or any other board. Tested on Sam_e70_xplained and FRDM have the same behaviour.
3. Run `$ sanitycheck --device-serial /dev/ttyACM0 --generate-hardware-map mec.file`
4. If after the first run, was no suspicious behavior, try to to delete hardware `map.file` and run command again. You should be able to see that bug.

**Expected behavior**
I expect that hardware map output should be full after the first attempt.

**Impact**
Annoyance, not clear understanding if hardware map was created or not, so need to run command again.

**Environment (please complete the following information):**
 - OS: Fedora 28
 - Toolchain Zephyr SDK 0.10.3
 - Commit 17d066b9dc0e0ac632edce4a2e723332ee950ec6

**Comment by nashif** [comment]
@maksimmasalski  you do not need to call `--generate-hardware-map mec.file` with ` --device-serial /dev/ttyACM0 `, the serial is supposed to be detected.



> I expect that hardware map output should be full after the first attempt.

it is full, however we do not show the detected devices.
