### ISSUE TITLE
Logging - strange behaviour with RTT on nRF53

### ISSUE THREAD

**Issue by koffes** [zephyrproject-rtos/zephyr#21514]
Currently using the logger with mostly default settings on the nRF53.
Whilst using LOG_WRN in a high frequency loop, I would expect to see something like: 
`--- 71 messages dropped ---`
This usually happens. Though, sometimes the logger skips a series of prints without the "messages dropped" warning.

If I set CONFIG_LOG_BLOCK_IN_THREAD=y the same thing happens. I would expect this to block the thread and output all messages from the for-loop.

If CONFIG_LOG_IMMEDIATE=y is set, I would expect to get all logs, but there is a gap in the prints from the for loop, and no error message.

@nordic-krch

**Comment by nordic-krch** [comment]
@koffes will take a look.

**Comment by nordic-krch** [comment]
> If CONFIG_LOG_IMMEDIATE=y is set, I would expect to get all logs, but there is a gap in the prints from the for loop, and no error message.

I've been looking into that a bit and i think that it is host related. When there is a debugging session opened (e.g. Ozone) and RTT viewer then actually both are trying to read RTT data. Most is read by RTT viewer but some is read by debug session.

I've been successfully reading all logs (on nrf52 and nrf53) when i was running Ozone debug session and use PuTTY to connect to telnet 127.0.0.1:19021.

However, I've found one issue that was causing RTT performance degradation in immediate mode (#21644).

**Comment by koffes** [comment]
Interesting. AFAIK, the debug session should read from a different channel than RTT. I am quite certain that I did not have a debug session running whilst reading RTT.  Is this something that can be described and sent to Segger?

**Comment by nordic-krch** [comment]
Without debug session, RTT viewer only i see some occasional bytes loss (1 per 1000 entries). I don't see them when using Ozone+PuTTY. When I use Ozone+RTT viewer i see multiple losses on RTT viewer (that's competing for RTT data that i've described above).

So it seems that there are 2 issues that could be reported to segger:
- debug session + rtt viewer
- occasional losses on rtt viewer

**Comment by XavierChapron** [comment]
As @koffes , I am still having issues with #21517
I have created a PR that resolves it (at least in my situation): https://github.com/zephyrproject-rtos/zephyr/pull/24647
Please have a look.
