### ISSUE TITLE
SPI broken for STM32L1

### ISSUE THREAD

**Issue by Mani-Sadhasivam** [zephyrproject-rtos/zephyr#21546]
**Describe the bug**
With the current Zephyr master, SPI is not working as expected on STM32L1 based 96boards Wistrio board. Some of the bytes of the received data seems to be dropping.

**To Reproduce**
Reproducible with the LoRa PR #18998 which uses SPI for communicating to the Radio.

The issue seems to be with this commit: https://github.com/zephyrproject-rtos/zephyr/commit/2ce8fa1e42d3d60e4119f15e82c29d2daaf67c00
To be more precise, setting `xfer_16` flag manually to `false` fixes the issue, which means the problem is with sending/receiving 16bits of data.

**Comment by Mani-Sadhasivam** [comment]
@psidhu Since you are the actual author of the commit, could you please look into this?

**Comment by erwango** [comment]
@Mani-Sadhasivam, thanks for reporting. This is partly my bad, not enough tests have been made for this behavior to be made used by default.
@psidhu, can you push a change to set this behavior available only under specific Kconfig flag (default n)?

**Comment by psidhu** [comment]
@erwango Sure, though it may take me a small bit of time to get to.
