### ISSUE TITLE
GNU ARM Embedded link broken in Getting Started

### ISSUE THREAD

**Issue by danieleggert** [zephyrproject-rtos/zephyr#21581]
The link to GNU ARM Embedded on https://docs.zephyrproject.org/latest/getting_started/toolchain_3rd_party_x_compilers.html#gnu-arm-embedded should probably be updated to https://developer.arm.com/tools-and-software/open-source-software/developer-tools/gnu-toolchain/gnu-rm/downloads

**Comment by ulfalizer** [comment]
Thanks for the report.

Fix: https://github.com/zephyrproject-rtos/zephyr/pull/21583

**Comment by carlescufi** [comment]
@danieleggert as I commented in the PR, the existing link seems to work fine? https://developer.arm.com/open-source/gnu-toolchain/gnu-rm

**Comment by jhedberg** [comment]
The existing link works for me too, maybe it was a temporary issue with the website. Therefore closing this issue.
