### ISSUE TITLE
Allow per module prj.conf

### ISSUE THREAD

**Issue by hadrienk** [zephyrproject-rtos/zephyr#21617]
**Is your enhancement proposal related to a problem? Please describe.**

I am using mcuboot. I need to manually update the .config under `build/mcuboot/zephyr/.config` when the build directory is cleaned.

**Describe the solution you'd like**

Use a special configuration file name convention: `prj_mcuboot.conf`

This should be compatible with the board configuration `prj_mcuboot_YOURBOARD.conf`

**Comment by carlescufi** [comment]
@hadrienk  thanks for the feedback. spm is not part of Zephyr, but rather only present in Nordic's Zephyr-based SDK. Could you edit your proposal so that it doesn't mention spm and instead focuses on mcuboot?

**Comment by hadrienk** [comment]
@carlescufi sure thing.

**Comment by carlescufi** [comment]
@ulfalizer could you comment on this?

**Comment by SebastianBoe** [comment]
In NCS one can specify the mcuboot prj.conf like this:

https://github.com/NordicPlayground/fw-nrfconnect-nrf/blob/master/applications/nrf_desktop/CMakeLists.txt#L34

In Zephyr upstream it doesn't make sense to put a child image's build dir inside of the parent image's build dir so this problem does not exist.

Please re-open if more clarification is needed.

**Comment by hadrienk** [comment]
Thanks. Got it to work. If anyone want to do the same, remember to set the image_CONF_FILE **before** the `include($ENV{ZEPHYR_BASE}/cmake/app/boilerplate.cmake)`
```
set(mcuboot_CONF_FILE "${CMAKE_CURRENT_SOURCE_DIR}/mcuboot.conf")
include($ENV{ZEPHYR_BASE}/cmake/app/boilerplate.cmake)
```
