### ISSUE TITLE
improve documentation on meta-IRQ threads

### ISSUE THREAD

**Issue by pabigot** [zephyrproject-rtos/zephyr#21648]
Related to #21185 there is a distinct lack of documentation on meta-IRQ threads and how they can be used safely.  They are not mentioned at all in the discusson of [thread priorities](https://docs.zephyrproject.org/latest/reference/kernel/threads/index.html#thread-priorities).

For example, it appears that somebody who's using `K_PRIO_COOP(0)` to create a cooperative thread might be surprised to learn that when `CONFIG_NUM_METAIRQ_PRIORITIES` is positive this thread can now pre-empt other "cooperative" threads.

**Comment by nashif** [comment]
You mean in addition to this https://docs.zephyrproject.org/latest/reference/kernel/scheduling/index.html?highlight=meta#meta-irq-prioritie and this https://docs.zephyrproject.org/latest/reference/kconfig/CONFIG_NUM_METAIRQ_PRIORITIES.html#cmdoption-arg-config-num-metairq-priorities?

**Comment by pabigot** [comment]
Yes.

**Comment by andrewboie** [comment]
@pabigot this being an open source project the fastest path to success is if you would send a PR with the changes you want.

**Comment by nashif** [comment]
@laurenmurphyx64  Can you please look into this?
