### ISSUE TITLE
Link to releases in README.rst give a 404 error

### ISSUE THREAD

**Issue by admorgan** [zephyrproject-rtos/zephyr#21706]
When trying to find the SDK releases I click on https://zephyrproject.org/developers/#downloads from the readme. The page displays a 404 error.

**Comment by dbkinder** [comment]
@nashif Alas, in the new zephyrproject.org site, there is no longer a list of SDK releases.  We may need to instead link to https://github.com/zephyrproject-rtos/sdk-ng/releases/latest in our documentation instead of to the zephyrproject.org site.
