### ISSUE TITLE
tests/kernel/obj_tracing failed on mec15xxevb_assy6853 board.

### ISSUE THREAD

**Issue by chen-png** [zephyrproject-rtos/zephyr#21756]
**To Reproduce**

1.  programming the tests/kernel/obj_tracing  to mec15xxevb_assy6853 board, according to
https://docs.zephyrproject.org/latest/boards/arm/mec1501modular_assy6885/doc/index.html to set up.
2. See error

**Screenshots or console output**
*** Booting Zephyr OS build zephyr-v2.1.0-744-g7ee5cf6a0bd1 ***

Running test suite obj_tracing
starting test - test_philosophers_tracing
SEMAPHORE REF: 0x00118628
SEMAPHORE REF: 0x00118610
SEMAPHORE REF: 0x001185f8
SEMAPHORE REF: 0x001185e0
SEMAPHORE REF: 0x001185c8
SEMAPHORE REF: 0x00118ba4
SEMAPHORE REF: 0x00118104
SEMAPHORE REF: 0x00118cc0
SEMAPHORE REF: 0x00118cdc
SEMAPHORE REF: 0x0011cd74
SEMAPHORE REF: 0x0011cd5c
SEMAPHORE QUANTITY: 5
COOP: 0x00118640 OPTIONS: 0x00, STATE: 0x40
COOP: 0x0011893c OPTIONS: 0x00, STATE: 0x02
COOP: 0x001188a4 OPTIONS: 0x00, STATE: 0x02
COOP: 0x0011880c OPTIONS: 0x00, STATE: 0x40
COOP: 0x00118774 OPTIONS: 0x00, STATE: 0x02
COOP: 0x001186dc OPTIONS: 0x00, STATE: 0x40
PREMPT: 0x00118eac OPTIONS: 0x00, STATE: 0x02
COOP: 0x00118124 OPTIONS: 0x00, STATE: 0x02
COOP: 0x00118cf4 OPTIONS: 0x01, STATE: 0x00
COOP: 0x00118d8c OPTIONS: 0x01, STATE: 0x40
THREAD QUANTITY: 10

**Assertion failed at ZEPHYR_BASE/tests/kernel/obj_tracing/src/main.c:120: object_monitor: (((thread_counter == TOTAL_THREADS) && (obj_counter == TOTAL_OBJECTS)) is false)
test failed**

FAIL - test_philosophers_tracing
starting test - test_obj_tracing

PASS - test_obj_tracing
Test suite obj_tracing failed.
PROJECT EXECUTION FAILED

**Environment (please complete the following information):**
 - OS: fedora28
 - Toolchain: zephyr-sdk-0.10.3
 - Commit ID: g7ee5cf6a0b

**Comment by nashif** [comment]
I am sure this is not a bug, looks like the board is enabling all kind of options that most likely have some kernel objects, so the counting does not match.

**Comment by nashif** [comment]
this is not a bug, the PS2 and other IPs being enabled by default add objects and the count does not match anymore, so the test fails. Boards should by default only enable the bare minimum, all optional features should only be enabled by the application using them, and not by default for every configuration 

cc @albertofloyd @franciscomunoz

**Comment by franciscomunoz** [comment]
The current number of threads "10" did not matched the expected "9". The kscan driver has a thread which is messing with the expected count. The test passes after disabling it ... I'm going to create a PR for disabling the KSCAN in the board.

starting test - test_philosophers_tracing
SEMAPHORE REF: 0x00118088
SEMAPHORE REF: 0x00118070
SEMAPHORE REF: 0x00118058
SEMAPHORE REF: 0x00118040
SEMAPHORE REF: 0x00118028
SEMAPHORE REF: 0x00118604
SEMAPHORE REF: 0x00118b50
SEMAPHORE REF: 0x00118b6c
SEMAPHORE REF: 0x00118730
SEMAPHORE REF: 0x00118718
SEMAPHORE REF: 0x0011cbf8
SEMAPHORE REF: 0x0011cbe0
SEMAPHORE QUANTITY: 5
COOP: 0x001180a0 OPTIONS: 0x00, STATE: 0x80
COOP: 0x0011839c OPTIONS: 0x00, STATE: 0x02
COOP: 0x00118304 OPTIONS: 0x00, STATE: 0x02
COOP: 0x0011826c OPTIONS: 0x00, STATE: 0x80
COOP: 0x001181d4 OPTIONS: 0x00, STATE: 0x02
COOP: 0x0011813c OPTIONS: 0x00, STATE: 0x80
PREMPT: 0x00118d3c OPTIONS: 0x00, STATE: 0x02
COOP: 0x00118b84 OPTIONS: 0x01, STATE: 0x00
COOP: 0x00118c1c OPTIONS: 0x01, STATE: 0x80
THREAD QUANTITY: 9
PASS - test_philosophers_tracing
===================================================================
starting test - test_obj_tracing
PASS - test_obj_tracing
===================================================================
Test suite obj_tracing succeeded
===================================================================
PROJECT EXECUTION SUCCESSFUL



https://github.com/zephyrproject-rtos/zephyr/pull/22816

**Comment by ashaannajoy** [comment]
This test passes by disabling KSCAN in zephyr/boards/arm/mec15xxevb_assy6853/mec15xxevb_assy6853_defconfig

**Comment by nashif** [comment]
#22921 has a more generic fix that should work with pre-existing conditions. Please verify.
