### ISSUE TITLE
Make [CONFIG_NET_SOCKETS_SOCKOPT_TLS] dependent on [CONFIG_MBEDTLS] in menuconfig

### ISSUE THREAD

**Issue by DenvE** [zephyrproject-rtos/zephyr#21768]
**Describe the bug**
When you define CONFIG_NET_SOCKETS_SOCKOPT_TLS without CONFIG_MBEDTLS, zephyr has build errors in socket_tls.c.
Workaround is knowing the dependencies and add it to configuration

**To Reproduce**
1. build the dhcpv4_client sample application for the stm32f746g_disco
2. add to prj.conf

# Enable Sockets support
CONFIG_NET_SOCKETS=y
CONFIG_NET_SOCKETS_SOCKOPT_TLS=y

3. build will fail

**Expected behavior**
At configuration time before building, error should indicate configuration of socket depends on mbedtls and should not start building the source code

**Impact**
annoying and configuration not consistent

**Environment (please complete the following information):**
 - MacOS
 - using zephyr-v2.1.0

**Comment by carlescufi** [comment]
@DenvE maybe you could send a Pull Request with the added dependency?
