### ISSUE TITLE
rename zassert functions

### ISSUE THREAD

**Issue by andrewboie** [zephyrproject-rtos/zephyr#21783]
Coverity thinks any function with the word "assert" in its name is a conditionally compiled expression, and generates false positives about side effects.

To avoid this hassle, rename the zassert... family of APIs used in our test cases to something which doesn't have "assert" in the same. zcheck perhaps?

The existing APIs should be marked with __deprecated and just call the new APIs. All test cases should be converted.

**Comment by jukkar** [comment]
I am not familiar with Coverity so do not know if this is possible, but IMHO we should instead try to configure Coverity to not generate these false positives. It sounds wrong to change our code just to satisfy some weird rule in a tool.

**Comment by nashif** [comment]
agree with @jukkar
