### ISSUE TITLE
Update document generating tools to newer versions

### ISSUE THREAD

**Issue by dbkinder** [zephyrproject-rtos/zephyr#21809]
We settled in on specific versions of tools for our project documentation, specifically:
```
breathe          version: 4.9.1
docutils         version: 0.14
sphinx           version: 1.7.7
sphinx_rtd_theme version: 0.4.3
doxygen          version: 1.8.13
```
We've had issues upgrading some of the tools to their latest versions in the past, but now we're rather far behind.  We should investigate moving to later versions of these tools, fix issues encountered, and make it so.   (Switching tools will likely affect the known issues processing we do to remove expected error and warning messages from the doc build output.)  We may also be able to enable multi-processing on newer versions of these tools to speed up the doc build process.

**Comment by carlescufi** [comment]
This is not applicable anymore.
