### ISSUE TITLE
tests/arch/arm/arm_irq_advanced_features failed on reel_board.

### ISSUE THREAD

**Issue by chen-png** [zephyrproject-rtos/zephyr#21812]
**To Reproduce**
1. west build -b reel_board -p auto tests/arch/arm/arm_irq_advanced_features
2. west flash
3. See error

**Screenshots or console output**
*** Booting Zephyr OS build zephyr-v2.1.0-803-gf05cbb421ddf ***

Running test suite arm_irq_advanced_features
starting test - test_arm_dynamic_direct_interrupts
ASSERTION FAIL [!arch_irq_is_enabled(irq)] @ ZEPHYR_BASE/arch/common/sw_isr_common.c:19
IRQ 47 is enabled
E: r0/a1: 0x00000004 r1/a2: 0x00000013 r2/a3: 0x00000001
E: r3/a4: 0x00006664 r12/ip: 0x00000000 r14/lr: 0x00000db3
E: xpsr: 0x61000000
E: Faulting instruction address (r15/pc): 0x00005824
E: >>> ZEPHYR FATAL ERROR 4: Kernel panic on CPU 0
E: Current thread: 0x2000004c (unknown)
E: Halting system

**Environment (please complete the following information):**
 - OS: fedora28
 - Toolchain: zephyr-sdk-0.10.3
 - Commit ID: f05cbb42

**Comment by activebug202** [comment]
@ioannisg @chen-png 
I have solved the bug.
This is my pull request, please review.thx.
https://github.com/zephyrproject-rtos/zephyr/pull/21929
