### ISSUE TITLE
Print unmet Kconfig dependency

### ISSUE THREAD

**Issue by oyvindronningstad** [zephyrproject-rtos/zephyr#21888]
**Is your enhancement proposal related to a problem? Please describe.**
When the following is printed

    warning: MY_CONFIG (defined at ...) was assigned the value 'y' but got the value 'n'.

It's often to figure out manually what Kconfig dependency is not met, especially if cmake fails so there's no `menuconfig` to run.

**Describe the solution you'd like**

Print which dependency was not met.

See also https://github.com/ulfalizer/Kconfiglib/issues/86

**Comment by ulfalizer** [comment]
Will get https://github.com/zephyrproject-rtos/zephyr/pull/20742 in first, because it changes some stuff in `scripts/kconfig/kconfig.zephyr`.
