### ISSUE TITLE
make include hierarchy consistent with expected usage

### ISSUE THREAD

**Issue by pabigot** [zephyrproject-rtos/zephyr#21974]
In response to a review comment I proposed #21776 which removed the implicit addition of `${ZEPHYR_BASE}/include/drivers` from the default include path, so that `<drivers/sensor.h>` would be enforced.  This breaks bluetooth, which wants to use `<bluetooth/whatever.h>` but the location is `${ZEPHYR_BASE}/include/drivers/bluetooth`.

It would be nice if the two were consistent, which probably means `bluetooth` should move up one level.

**Comment by SebastianBoe** [comment]
FYI: @jhedberg , @joerchan , @cvinayak

**Comment by joerchan** [comment]
In `include/drivers/bluetooth` there is only `hci_driver.h`. Most HCI drivers are implemented in Zephyr itself. So only out-of-tree HCI drivers would be affected by this. 

I don't mind switching to `drivers/bluetooth/hci_driver.h` to make in consistent. It would require updating our downstream HCI driver but shouldn't pose any big issues.
I`m currently not aware of any other maintaining their hci driver out-of-tree though.

@aescolar Any comments?

**Comment by joerchan** [comment]
Actually it appears both paths are used. And our downstream use `drivers/bluetooth/hci_driver.h` so only zephyr HCI drivers are affected (that I'm aware of).
