### ISSUE TITLE
Bluetooth: controller: split: Fix procedure complete event generation

### ISSUE THREAD

**Issue by cvinayak** [zephyrproject-rtos/zephyr#21994]
**Describe the bug**
Generate PHY update complete and Conn Update events after the on-air instant

**To Reproduce**
1. mkdir build; cd build
2. cmake -DBOARD=board\_xyz
3. make

**Expected behavior**

**Impact**
What impact does this issue have on your progress (e.g., annoyance, showstopper)

showstopper

**Screenshots or console output**
If applicable, add a screenshot (drag-and-drop an image), or console logs
(cut-and-paste text and put a code fence (\`\`\`) before and after, to help
explain the issue.

**Environment (please complete the following information):**
 - OS: (e.g. Linux, MacOS, Windows)
 - Toolchain (e.g Zephyr SDK, ...)
 - Commit SHA or Version used

**Additional context**

**Comment by cvinayak** [comment]
Use inspiration from legacy controller: zephyrproject-rtos/zephyr@2bf9d49

**Comment by carlescufi** [comment]
@kruithofa @cvinayak is this still an issue on the current EBQ runs?

**Comment by cvinayak** [comment]
@carlescufi This is not an issue for the runs, we have workaround.

**Comment by cvinayak** [comment]
@carlescufi this depends on new LLCP work, not worth new effort to fix this in current split controller.
