### ISSUE TITLE
Bluetooth: controller: split: Porting of connection event length

### ISSUE THREAD

**Issue by cvinayak** [zephyrproject-rtos/zephyr#21995]
**Is your enhancement proposal related to a problem? Please describe.**
A clear and concise description of what the problem is.

Without use of connection event length, radio events would overlap and cause degradation in performance/throughput.

**Describe the solution you'd like**

Be inspired by zephyrproject-rtos/zephyr@32c2f85

**Describe alternatives you've considered**

**Additional context**
Add any other context or graphics (drag-and-drop an image) about the feature request here.

**Comment by carlescufi** [comment]
@kruithofa @thoh-ot  this needs follow-up in the new LLCP
