### ISSUE TITLE
west: openocd runner fails for boards without support/openocd.cfg

### ISSUE THREAD

**Issue by JordanYates** [zephyrproject-rtos/zephyr#22026]
**Describe the bug**
Python exception when attempting to use the openocd runner with west for boards that do not contain support/openocd.cfg

Lines 27-36 of openocd.py 
```
        if not config:
            default = path.join(cfg.board_dir, 'support', 'openocd.cfg')
            if path.exists(default):
                config = default
        self.openocd_config = config

        if path.exists(self.openocd_config):
            search_args = ['-s', path.dirname(self.openocd_config)]
        else:
            search_args = []
```
When config is None, and openocd.cfg is not present, self.openocd_config is None.
path.exists(None) results in a TypeError

For the nordic development kits, the openocd settings are initialised in board.cmake and openocd-nrf5.board.cmake
This is presumably why they are missing openocd.cfg files even through openocd is supported.

Modifying the above to the following allows flashing to succeed.
```
        if self.openocd_config is not None and path.exists(self.openocd_config):
```
Alternatively, manually specifying an empty configuration file also works.

**To Reproduce**
```
west build -b nrf52840_pca10056 zephyr\samples\basic\blinky
west flash -r openocd
```

**Expected behavior**
Flashing should succeed

**Impact**

Affected boards can't be flashed with openocd without modifying the core repo, or specifying some empty configuration file via `west flash -r openocd --config empty.cfg`

**Environment (please complete the following information):**
 - OS: Windows
 - Commit SHA: 5af54075703c248fae2bf69a50909bf2e3cc977e

**Comment by mbolivar** [comment]
This was fixed in https://github.com/zephyrproject-rtos/zephyr/pull/21823
