### ISSUE TITLE
Add support for USB device on STM32L1 series

### ISSUE THREAD

**Issue by takumiando** [zephyrproject-rtos/zephyr#22034]
Why doesn't Zephyr support USB device features on STM32L1?
There's no DTS and its fixup but STM32L1 has USB device functions.

**Comment by erwango** [comment]
@takumiando, this status reflect work and needs of zephyr community.
If USB has not been enabled on L1, this is because no one in the community did the effort of enabling and testing it.

**Comment by takumiando** [comment]
@erwango 
Okay, I understand.
I will try it.

**Comment by erwango** [comment]
@takumiando I'm closing this point. Please reopen if need be
