### ISSUE TITLE
RISCV arch_irq_connect_dynamic() broken with PLIC interrupts

### ISSUE THREAD

**Issue by jaronkelleher** [zephyrproject-rtos/zephyr#22145]
Inside arch_irq_connect_dynamic(), the first call is to z_isr_install() which uses the irq number to index into _sw_isr_table when storing the callback information. The next call is to riscv_plic_set_priority(), which sets the priority register inside the PLIC for the irq number passed in. The problem is the perspective of each function is different. z_isr_install() views the interrupts from an MCU perspective, while riscv_plic_set_priority views interrupts from a different perspective (i.e PLIC irq 1 corresponds to MCU interrupt 15 if CONFIG_2ND_LVL_ISR_TBL_OFFSET=14).

**To Reproduce**
1. Create application with CONFIG_DYNAMIC_INTERRUPTS=y 
2. Call irq_connect_dynamic(1+CONFIG_2ND_LVL_ISR_TBL_OFFSET, 7, <some_handler>, nullptr, 0) in your main function
3. cmake -DBOARD=qemu_riscv32
4. make
5. run application with debugger
6. set breakpoint at arch_irq_connect_dynamic (zephyr/arch/common/sw_isr_common.c)
7. continue application
8. Watch as the isr is stored into index 1+CONFIG_2ND_LVL_ISR_TBL_OFFSET with z_isr_install
9. Watch as PLIC irq 1+CONFIG_2ND_LVL_ISR_TBL_OFFSET priority is set
10. set breakpoint at plic_irq_handler (zephyr/drivers/interrupt_controller/plic.c)
10. continue application and trigger plic irq1
11. No interrupt is signalled becaused PLIC irq 1 priority is still 0, which disables the interrupt

**Expected behavior**
Registering dynamic interrupt callbacks with irq_connect_dynamic will know if it is a second level interrupt on riscv and adjust irq passed into riscv_plic_set_priority accordingly. Interrupt numbers passed into arch_irq_dynamic_connect are of the expected format for multilevel interrupts (0xTTSSFF).

**Impact**
Annoyance. This can be worked around by manually resetting the priority of 1+CONFIG_2ND_LVL_ISR_TBL_OFFSET and properly setting the priority of 1 in the PLIC

**Environment**
 - OS: Linux
 - Toolchain Zephyr SDK
 - Version 2.1.0

**Additional context**

**Comment by jhedberg** [comment]
Is this reproducible on the master branch?
