### ISSUE TITLE
Implement uart_err_check for cdc_acm

### ISSUE THREAD

**Issue by efra-mx** [zephyrproject-rtos/zephyr#22178]
**Is your enhancement proposal related to a problem? Please describe.**
I am using the `cdc_acm` driver a device, to sync the communication I am waiting for a UART_BREAK.

I would expect to use this snippet:
```
static void usb_uart_interrupt_handler_new(struct device* dev)
{
	int ret = 0;
	char c;

	while (uart_irq_update(dev) && uart_irq_is_pending(dev)) {
		while(0 == uart_irq_tx_complete(dev)){
			continue;
		};
		ret = uart_err_check(dev);
		if(ret == UART_BREAK){
			/* do something */
		}
	}

}
```

**Describe the solution you'd like**
Implement the missing functions of the cdc_acm driver.

static_int cdc_acm_err_check(struct device *dev);
static void cdc_acm_err_irq_err_enable(struct device *dev);

**Describe alternatives you've considered**
I have consider to send a special command as a break signal.

**Additional context**
Add any other context or graphics (drag-and-drop an image) about the feature request here.

**Comment by jfischer-no** [comment]
> ```
> static void usb_uart_interrupt_handler_new(struct device* dev)
> {
> 	int ret = 0;
> 	char c;
> 
> 	while (uart_irq_update(dev) && uart_irq_is_pending(dev)) {
> 		while(0 == uart_irq_tx_complete(dev)){
> 			continue;
> 		};
> 		ret = uart_err_check(dev);
> 		if(ret == UART_BREAK){
> 			/* do something */
> 		}
> 	}
> 
> }
> ```

From the UART driver API, it is not clear if uart_err_check() is intended or can be used from interrupt handler context and is not part of IRQ API.

> **Describe the solution you'd like**
> Implement the missing functions of the cdc_acm driver.

No plans to implement it.
