### ISSUE TITLE
Bluetooth ：Mesh：Provison init should after proxy

### ISSUE THREAD

**Issue by moringe** [zephyrproject-rtos/zephyr#22207]
https://github.com/zephyrproject-rtos/zephyr/blob/bce335458bbf9fbeeb82c16073773a46a3d4533e/subsys/bluetooth/mesh/main.c#L292-L328

Provision use pb-gatt use buffer from proxy client, however proxy client init after prov init. Prov init call reset_state to allocate buf from proxy client, get-proxy-buf call net_buf_simple_reset to init buf->data = buf->__buf, but at this time buf->__buf currently not initiating.

**Comment by jhedberg** [comment]
You're right, this looks like a real bug - I'm surprised no one has noticed since it results in the provisioning buffer having `buf->data` pointing to NULL. The fix should be as simple as reordering the calls in `bt_mesh_init()` i.e. so that `bt_mesh_proxy_init()` gets called before `bt_mesh_prov_init()`.

**Comment by jhedberg** [comment]
@moringe can you confirm that the following would solve the issue:

```
--- a/subsys/bluetooth/mesh/main.c
+++ b/subsys/bluetooth/mesh/main.c
@@ -304,6 +304,10 @@ int bt_mesh_init(const struct bt_mesh_prov *prov,
                return err;
        }
 
+       if (IS_ENABLED(CONFIG_BT_MESH_PROXY)) {
+               bt_mesh_proxy_init();
+       }
+
        if (IS_ENABLED(CONFIG_BT_MESH_PROV)) {
                err = bt_mesh_prov_init(prov);
                if (err) {
@@ -316,10 +320,6 @@ int bt_mesh_init(const struct bt_mesh_prov *prov,
        bt_mesh_beacon_init();
        bt_mesh_adv_init();
 
-       if (IS_ENABLED(CONFIG_BT_MESH_PROXY)) {
-               bt_mesh_proxy_init();
-       }
-
        if (IS_ENABLED(CONFIG_BT_SETTINGS)) {
                bt_mesh_settings_init();
        }
```
