### ISSUE TITLE
Enabling OpenThread SLAAC

### ISSUE THREAD

**Issue by braiden** [zephyrproject-rtos/zephyr#22222]
**Is your enhancement proposal related to a problem? Please describe.**
My OpenThread device is not configuring its addresses via SLAAC. It appears that SLAAC is not enabled in zephyr's build of openthread.

**Describe the solution you'd like**
A KConfig? or, just enable by default?

**Describe alternatives you've considered**
`set(OT_SLAAC ON)` in my project's own `CMakeLists.txt` seems to work, but that seems like a hack and not how i'm supposed to enable the feature(?).

**Additional context**

**Comment by rlubos** [comment]
I'd keep it configurable, just as some other OpenThread features already are. `OPENTHREAD_SLAAC` on the Zephyr side plus the following entry in the OpenThread CMake file should do the job:
```
if(CONFIG_OPENTHREAD_SLAAC)
  set(OT_SLAAC ON CACHE BOOL "...")
endif()
```

**Comment by rlubos** [comment]
SLAAC was added in https://github.com/zephyrproject-rtos/openthread/pull/6
