### ISSUE TITLE
STM32G4xx: Wrong SystemCoreClock variable

### ISSUE THREAD

**Issue by martinjaeger** [zephyrproject-rtos/zephyr#22245]
**Description**
Because of a bug in STM32Cube LL, the `SystemCoreClock` variable is set wrong if the actual system frequency is >80 MHz.

More details are described in a related (but already closed) PR:
https://github.com/zephyrproject-rtos/hal_stm32/pull/34#issuecomment-578881473

I raised this issue to track the bug, as I can't raise an issue in the original HAL repository.

**Impact**
Boards with STM32G431 are hardly useable with high clock frequencies, as e.g. UART baud rates are get configured wrong.
Preliminary workaround could be to reduce the system frequency to <80 MHz.

**Comment by ulfalizer** [comment]
Semi-unrelated, but could we enable issues on module repos? @nashif

**Comment by rosterloh** [comment]
https://github.com/zephyrproject-rtos/hal_stm32/pull/36
