### ISSUE TITLE
test wdt_basic_api failed on nucleo_f746zg

### ISSUE THREAD

**Issue by erwango** [zephyrproject-rtos/zephyr#22257]
**Describe the bug**
Test is failed and device keeps looping in first test functsion:
```
Running test suite wdt_basic_test
===================================================================
starting test - test_wdt
Testcase: test_wdt_no_callback
Waiting to restart MCU
Running test suite wdt_basic_test
===================================================================
starting test - test_wdt
Testcase: test_wdt_no_callback
Waiting to restart MCU
Running test suite wdt_basic_test
===================================================================
...
```

**To Reproduce**
`./scripts/sanitycheck -p nucleo_f746zg --device-serial /dev/ttyACM0 --device-testing -T tests/drivers/watchdog`

**Expected behavior**
Test pass

**Comment by FRASTM** [comment]
in the iwdg watchdog driver for stm32 (wdt_iwdg_stm32.c), the sequence to `iwdg_stm32_install_timeout` does not wait for register update after setting the Prescaler and the Reload Counter.
--> add a loop on LL_IWDG_IsReady
--> reload the counter just before leaving the function
