### ISSUE TITLE
sanitycheck fails to merge OVERLAY_CONFIG properly

### ISSUE THREAD

**Issue by mniestroj** [zephyrproject-rtos/zephyr#22258]
**Describe the bug**
Sanitycheck fails to merge OVERLAY_CONF properly before passing this argument to build system.

**To Reproduce**
1. ./scripts/sanitycheck -p qemu_x86 -T samples/net/sockets/echo_client/ -i
2. Look at ./sanity-out/qemu_x86/samples/net/sockets/echo_client/sample.net.sockets.echo_client.bt/build.log
3. Look at merged configuration, there is no overlay-bt.conf that should be mentioned there:
```
Loaded configuration '/zephyr/boards/x86/qemu_x86/qemu_x86_defconfig'
Merged configuration '/zephyr/samples/net/sockets/echo_client/prj.conf'
Merged configuration '/zephyr/samples/net/sockets/echo_client/boards/qemu_x86.conf'
Configuration saved to '/zephyr/sanity-out/qemu_x86/samples/net/sockets/echo_client/sample.net.sockets.echo_client.bt/zephyr/.config'
```

**Expected behavior**
overlay-bt.conf should be taken into account:
```
Merged configuration 'overlay-bt.conf'
```

**Impact**
Sanitycheck doesn't properly test all configurations within the project, because it fails to merge OVERLAY_CONF options together.

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: Zephyr SDK
 - Commit SHA or Version used: c793c0edda931ab95644ee3bf977600a88266260

**Comment by nashif** [comment]
should be fixed
