### ISSUE TITLE
The file flash_stm32wbx.c generates compilation error

### ISSUE THREAD

**Issue by r2r0** [zephyrproject-rtos/zephyr#22299]
**Describe the bug**
During compilation the file flash_stm32wbx.c in project configured for nucleo_wb55rg board there is generated compilation error.
It looks that the latest commit missed changes in flash_stm32_check_status function.

**To Reproduce**
1. mkdir build; cd build
2. cmake -DBOARD=nucleo_wb55rg
3. make

**Expected behavior**
Clean compilation.

**Impact**
Need manual patching.

**Screenshots or console output**
[48/138] Building C object zephyr/CMakeFiles/zephyr.dir/drivers/flash/flash_stm32wbx.c.obj
FAILED: zephyr/CMakeFiles/zephyr.dir/drivers/flash/flash_stm32wbx.c.obj 
ccache /opt/zephyr-sdk/arm-zephyr-eabi/bin/arm-zephyr-eabi-gcc -DBUILD_VERSION=zephyr-v2.1.0-1472-g268f65d2212c -DCORE_CM4 -DHSE_VALUE=32000000 -DKERNEL -DSTM32WB55xx -DUSE_FULL_LL_DRIVER -DUSE_HAL_DRIVER -D_FORTIFY_SOURCE=2 -D__LINUX_ERRNO_EXTENSIONS__ -D__PROGRAM_START -D__ZEPHYR__=1 -I/home/hid/aurora_repo/zephyr/include -Izephyr/include/generated -I/home/hid/aurora_repo/zephyr/soc/arm/st_stm32/stm32wb -I/home/hid/aurora_repo/zephyr/lib/libc/newlib/include -I/opt/zephyr-sdk/arm-zephyr-eabi/arm-zephyr-eabi/include -I/home/hid/aurora_repo/zephyr/drivers -I/home/hid/aurora_repo/zephyr/ext/hal/cmsis/Core/Include -I/home/hid/aurora_repo/modules/hal/stm32/stm32cube/stm32wbxx/soc -I/home/hid/aurora_repo/modules/hal/stm32/stm32cube/stm32wbxx/drivers/include -I/home/hid/aurora_repo/modules/hal/stm32/stm32cube/stm32wbxx/drivers/include/Legacy -Os -imacros/home/hid/aurora_repo/build_dir/zephyr/include/generated/autoconf.h -ffreestanding -fno-common -g -mthumb -mcpu=cortex-m4 -imacros/home/hid/aurora_repo/zephyr/include/toolchain/zephyr_stdint.h -Wall -Wformat -Wformat-security -Wno-format-zero-length -Wno-main -Wno-pointer-sign -Wpointer-arith -Wno-unused-but-set-variable -Werror=implicit-int -fno-asynchronous-unwind-tables -fno-pie -fno-pic -fno-strict-overflow -fno-reorder-functions -fno-defer-pop -fmacro-prefix-map=/home/hid/aurora_repo/app=CMAKE_SOURCE_DIR -fmacro-prefix-map=/home/hid/aurora_repo/zephyr=ZEPHYR_BASE -ffunction-sections -fdata-sections -mabi=aapcs -march=armv7e-m -std=c99 -MD -MT zephyr/CMakeFiles/zephyr.dir/drivers/flash/flash_stm32wbx.c.obj -MF zephyr/CMakeFiles/zephyr.dir/drivers/flash/flash_stm32wbx.c.obj.d -o zephyr/CMakeFiles/zephyr.dir/drivers/flash/flash_stm32wbx.c.obj   -c /home/hid/aurora_repo/zephyr/drivers/flash/flash_stm32wbx.c
/home/hid/aurora_repo/zephyr/drivers/flash/flash_stm32wbx.c: In function 'flash_stm32_check_status':
/home/hid/aurora_repo/zephyr/drivers/flash/flash_stm32wbx.c:178:15: error: 'FLASH_TypeDef' {aka 'struct <anonymous>'} has no member named 'sr'
  error = (regs->sr & FLASH_FLAG_SR_ERRORS);
               ^~
/home/hid/aurora_repo/zephyr/drivers/flash/flash_stm32wbx.c:179:16: error: 'FLASH_TypeDef' {aka 'struct <anonymous>'} has no member named 'eccr'
  error |= (regs->eccr & FLASH_FLAG_ECCC);
                ^~
/home/hid/aurora_repo/zephyr/drivers/flash/flash_stm32wbx.c:183:7: error: 'FLASH_TypeDef' {aka 'struct <anonymous>'} has no member named 'sr'
   regs->sr |= FLASH_FLAG_SR_ERRORS;
       ^~

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain Zephyr SDK 0.10.3
 - 4f2c107

**Comment by erwango** [comment]
Same as https://github.com/zephyrproject-rtos/zephyr/issues/22297.
Closing
