### ISSUE TITLE
Bug in sockets.c (subsys\net\lib\sockets)

### ISSUE THREAD

**Issue by bran795** [zephyrproject-rtos/zephyr#22366]
**Describe the bug**
When zsock_accept_ctx is called on a non-blocking socket, after a few times it returns ENFILE - no more file descriptors available

Call 		
z_free_fd(fd);
Before returning EAGAIN (line 16 of the function accept)

**To Reproduce**
1. mkdir build; cd build
2. cmake -DBOARD=frdm_k64f
3. make

**Expected behavior**
Accept should return EAGAIN when there is no pending connection on the listening socket

**Impact**
Showstopper. This bug means non-blocking sockets cannot be used for listening and accepting on the server side.

**Screenshots or console output**
N/A

**Environment (please complete the following information):**
 - OS:  Windows
 - Toolchain arm mbed
 - Commit SHA or Version used: top as of Jan 30 2020

**Additional context**
code snippet:
```
@@ -421,6 +421,7 @@ int zsock_accept_ctx(struct net_context *parent, struct sockaddr *addr,
	ctx = k_fifo_get(&parent->accept_q, timeout);
	if (ctx == NULL) {
		errno = EAGAIN;
+		z_free_fd(fd);
		return -1;
	}
```

**Comment by jhedberg** [comment]
@bran795 are you planning to send a pull request, since you seem to have a fix proposal in the description?

**Comment by bran795** [comment]
@jhedberg Hi, newbie here
I haven't checked the procedure for sending a pull request
Can anyone send a pull request?

**Comment by bran795** [comment]
@jhedberg
I would appreciate a little help with the pull request
Is there a way to edit the pull request comment after it has been created?
Thanks

**Comment by pfalcon** [comment]
@bran795: "Comment", not (well, it won't help). "Commit message", yes. Use `git rebase -i master` in your branch. Read instructions carefully, and feel free to google it up for more details (Zephyr docs may also include suggestions for development process).

**Comment by bran795** [comment]
@pfalcon right
what about the Identity/Emails issues? I added an email address first.last@company to my github account but that doesn't seem to work either
thanks

**Comment by jhedberg** [comment]
@bran795 you need to configure your local git correctly, which is normally done through `$HOME/.gitconfig`. E.g. in mine I have:
```
[user]
	name = Johan Hedberg
	email = johan.hedberg@intel.com
```

Since you already created the commit you'll need to amend its author explicitly. You should be able to do that with `git commit --amend --author="Your Name <your@email>` or with `git commit --amend --reset-author` after you've fixed your git configuration.

**Comment by pfalcon** [comment]
@bran795: Name/email in commit's "Author:" field should match those in "Signed-off-by:" as present in the commit message. In #22366 I see (`git log`):

~~~
Author: bran795 <48238460+bran795@users.noreply.github.com>
~~~

which suggests that you submitted that PR from Github's web UI. That won't work here, you would need to use command-line git client, I'm afraid.

**Comment by bran795** [comment]
@jhedberg 
@pfalcon 
Thanks, I'll install git and try again

**Comment by jhedberg** [comment]
> you submitted that PR from Github's web UI

I had no idea that GitHub had such a feature. I wonder if it can be disabled per-project, since it doesn't seem to be able to produce what's required for Zephyr.

**Comment by bran795** [comment]
Getting closer...

Gitlint issues
1: UC2 Signed-off-by: must have a full name

Identity/Emails issues
1a868e8: author email (Inbar Anson Bratspiess inbar.anson.bratspiess@330plus.net) needs to match one of the signed-off-by entries.

Please help 

Thanks
