### ISSUE TITLE
Build warnings in http_get on cc3220sf_launchxl

### ISSUE THREAD

**Issue by vanti** [zephyrproject-rtos/zephyr#22388]
(From https://github.com/zephyrproject-rtos/zephyr/pull/22385.)

**Describe the bug**
Build warnings are seen when building http_get sample for cc3220sf_launchxl in CI:

```
NET_CONFIG_MY_IPV4_GW (defined at subsys/net/lib/config/Kconfig:104) was
assigned the value '192.0.2.2' but got the value ''. Check these unsatisfied
dependencies: NET_CONFIG_SETTINGS (=n). ...


warning: NET_SOCKETS_POSIX_NAMES (defined at subsys/net/lib/sockets/Kconfig:13)
was assigned the value 'n' but got the value 'y'. ...


warning: TLS_CREDENTIAL_FILENAMES (defined at
subsys/net/lib/tls_credentials/Kconfig:17) was assigned the value 'y' but got
the value 'n'. Check these unsatisfied dependencies: TLS_CREDENTIALS (=n). ...


warning: NET_SOCKETS_POSIX_NAMES (defined at subsys/net/lib/sockets/Kconfig:13)
has direct dependencies !POSIX_API && NET_SOCKETS && NETWORKING with value n,
but is currently being y-selected by the following symbols:
 - NET_SOCKETS_OFFLOAD (defined at subsys/net/lib/sockets/Kconfig:102), with
   value y, direct dependencies NET_SOCKETS && NETWORKING (value: y), and
   select condition NET_SOCKETS && NETWORKING (value: y)

error: Aborting due to Kconfig warnings
```

For full log, see:
https://ci.linaro.org/job/zephyr-upstream/PLATFORM=cc3220sf_launchxl,ZEPHYR_TOOLCHAIN_VARIANT=zephyr,label=docker-xenial-amd64-13/4801/console

**To Reproduce**
1. cd zephyr/samples/net/sockets/http_get
2. west build -b cc3220sf_launchxl -p
3. See warnings

**Expected behavior**
There should be no build warnings.

**Impact**
Breaks CI.

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04
 - Toolchain: Zephyr SDK 0.11.0
 - Commit SHA or Version used: 9dc4eed622e642e2423e2c71526b95f2b1c1ab08

**Comment by ulfalizer** [comment]
This one is an issue with the Kconfig files (more select shenanigans):

```
warning: NET_SOCKETS_POSIX_NAMES (defined at subsys/net/lib/sockets/Kconfig:13)
has direct dependencies !POSIX_API && NET_SOCKETS && NETWORKING with value n,
but is currently being y-selected by the following symbols:
 - NET_SOCKETS_OFFLOAD (defined at subsys/net/lib/sockets/Kconfig:102), with
   value y, direct dependencies NET_SOCKETS && NETWORKING (value: y), and
   select condition NET_SOCKETS && NETWORKING (value: y)
```

Will look into later.

**Comment by vanti** [comment]
> This one is an issue with the Kconfig files (more select shenanigans):
> 
> ```
> warning: NET_SOCKETS_POSIX_NAMES (defined at subsys/net/lib/sockets/Kconfig:13)
> has direct dependencies !POSIX_API && NET_SOCKETS && NETWORKING with value n,
> but is currently being y-selected by the following symbols:
>  - NET_SOCKETS_OFFLOAD (defined at subsys/net/lib/sockets/Kconfig:102), with
>    value y, direct dependencies NET_SOCKETS && NETWORKING (value: y), and
>    select condition NET_SOCKETS && NETWORKING (value: y)
> ```
> 
> Will look into later.

@ulfalizer I had proposed a change in #22385 to address this one, since that test doesn't really apply to cc32xx imho. If it is due to something else, keep me posted and I'll remove that commit. Thanks!

**Comment by ulfalizer** [comment]
@vanti 
When there's selects with unsatisfied dependencies, it's always a problem within the Kconfig files, because it means dependencies aren't properly specified.

Best to think of Kconfig in terms of the menuconfig. It shouldn't be possible to go into the menuconfig and create weird configurations where symbols are enabled but not their dependencies.

A quick workaround is fine though.
