### ISSUE TITLE
RFC: API Change: clock_control

### ISSUE THREAD

**Issue by nordic-krch** [zephyrproject-rtos/zephyr#22424]
### Problem description

Clock control API has `clock_control_async_on()` call which starts clock asynchronously and results in callback being called on clock being started. `clock_control_async_on()` call has as one of the arguments`clock_control_subsys_t sys` which is an opaque data representing clock subsystem. Currently, callback function prototype is missing that argument:
```
typedef void (*clock_control_cb_t)(struct device *dev, void *user_data);
```

### Proposed change

Add `clock_control_subsys_t sys`  to callback arguments.

```
typedef void (*clock_control_cb_t)(struct device *dev,
                                   clock_control_subsys_t sys, void *user_data);
```

## Impact

Clock control is mainly used internally by other drivers or modules. `clock_control_async_on()` and `clock_control_cb_t` is only used in nordic clock control driver (`nrf_power_clock.c`) so scope of change is limited.

**Comment by carlescufi** [comment]
Only nRF platforms implement the async version of clock control, so this is very low risk
