### ISSUE TITLE
not driver found in can bus samples for olimexino_stm32

### ISSUE THREAD

**Issue by boonpin1975** [zephyrproject-rtos/zephyr#22452]
is the canbus supported for olimexino_stm32 ? 
reproduce :
west build -b olimexino_stm32 samples/drivers/CAN
console output : 
uart:~$ �*** Booting Zephyr OS build zephyr-v2.1.0-1628-gb45b1e393c95  ***
CAN: Device driver not found.

uart:~$ canbus
canbus - CAN commands
Subcommands:
  send    :Send a CAN frame.
           Usage: send device_name [-re] id [byte_1 byte_2 ...]
           -r Remote transmission request
            -e Extended address
  attach  :Attach a message filter and print those messages.
           Usage: attach device_name [-re] id [mask [-r]]
           -r Remote transmission request
            -e Extended address
  detach  :Detach the filter and stop receiving those messages
           Usage: detach device_name filter_id
uart:~$

**Comment by erwango** [comment]
I don't have hardware to test but CAN support on olimexino_stm32 is enabled since 2302d2615b519fe2ccc1a94d33e493fc10b3953d.

Maybe @alexanderwachter you can comment on this ?

**Comment by alexanderwachter** [comment]
@boonpin1975 Can you turn on the debug log-level for the CAN driver and send the logs?

**Comment by alexanderwachter** [comment]
@boonpin1975 don't forget to connect the board to a CANbus that is terminated.
Otherwise, the driver does not initialize, because it needs 11 recessive bits on the bus to initialize.

**Comment by boonpin1975** [comment]
hi all ,

 I am connecting the olimexino_stm32 to the komodo can solo for verification purposes , CANH -> CAN+ ( komodo ) , CANL - > CAN- (komodo) , GND -> GND ( komodo )
![image](https://user-images.githubusercontent.com/17423725/73802320-4ac35c00-47f8-11ea-8812-a721cb8e54fa.png)

my prj.conf
CONFIG_CAN=y
CONFIG_CAN_INIT_PRIORITY=80
CONFIG_CAN_MAX_FILTER=5
CONFIG_CAN_STM32=y
CONFIG_CAN_1=y
CONFIG_CAN_LOG_LEVEL_DBG=y
CONFIG_SHELL=y
CONFIG_CAN_SHELL=y
CONFIG_DEVICE_SHELL=y

**Comment by alexanderwachter** [comment]
Are you on the latest master?

**Comment by boonpin1975** [comment]
the version is 2.1.99  . I can build the example but it can not loaded the CAN driver when connected to komodo can analyzer

**Comment by alexanderwachter** [comment]
@walzert can you check if the tip of master works on your setup?

**Comment by walzert** [comment]
@alexanderwachter will do that tomorrow.

**Comment by alexanderwachter** [comment]
@boonpin1975 did you get your board working?

**Comment by alexanderwachter** [comment]
No response from issuer since two weeks.

**Comment by songmaotian** [comment]
I have same problem，I open the can Log，and it's seems because it's doesn't get 11 recessive bits on the bus to leave sleep mode

**Comment by erwango** [comment]
@songmaotian 
> I have same problem，I open the can Log，and it's seems because it's doesn't get 11 recessive bits on the bus to leave sleep mode

Can you open a new issue? Please provide as much as possible information on your environment and application.
