### ISSUE TITLE
tests/kernel/mem_protect/syscalls fails test_string_nlen on nsim_sem

### ISSUE THREAD

**Issue by andrewboie** [zephyrproject-rtos/zephyr#22561]
**Describe the bug**
```
*** Booting Zephyr OS build zephyr-v2.1.0-2104-g46b3af124a93  ***
Running test suite syscalls
===================================================================
starting test - test_string_nlen

    Assertion failed at ZEPHYR_BASE/tests/kernel/mem_protect/syscalls/src/main.c:174: test_string_nlen: (err not equal to -1)
nonsense string address did not fault
FAIL - test_string_nlen
```

On further inspection, it appears that on ARC, if you are in supervisor mode, it seems you can read the memory address 0xFFFFFFF0 without generating a fault.

This only affects nsim_sem and not nsim_em.

@vonhust @abrodkin is this expected? Is this a valid address in the memory map?

I could change the test case to only run the failing scenario from user mode, but I was hoping to exercise the exception recovery code directly.

**Comment by ruuddw** [comment]
This could be expected behaviour, the nsim simulator default behavior is to simulate memory on the full address space. In kernel mode, there are no MPU restrictions either, so I expect 0xFFFFFFF0 is simply a valid memory address. I believe this nsim behavior can be changed, probably cleaner to only model the memory defined in the dts file.

**Comment by andrewboie** [comment]
> This could be expected behaviour, the nsim simulator default behavior is to simulate memory on the full address space. In kernel mode, there are no MPU restrictions either, so I expect 0xFFFFFFF0 is simply a valid memory address. I believe this nsim behavior can be changed, probably cleaner to only model the memory defined in the dts file.

@ruuddw OK, thanks. Is there an easy way to configure nSIM to not enable RAM for the full address space?

**Comment by andrewboie** [comment]
A workaround has been put in place.
Leaving this open to explore configuration of nSIM to not emulate the entire address space, using DTS as a bounds.
