### ISSUE TITLE
tests/drivers/gpio/gpio_basic_api failed on multiple ARM platforms

### ISSUE THREAD

**Issue by chen-png** [zephyrproject-rtos/zephyr#22622]
**Describe the bug**
tests/drivers/gpio/gpio_basic_api failed on reel_board, frdm_k64f, sam_e70_xplained and  mimxrt1050_evk boards.

**To Reproduce**
1. west build -b reel_board -p auto tests/drivers/gpio/gpio_basic_api/
2. west flash
3. See error

**Screenshots or console output**

****Booting Zephyr OS build zephyr-v2.1.0-2179-g55eb4a11cdb1****
Running test suite gpio_basic_test

starting test - test_gpio_port
Validate device GPIO_0
Check GPIO_0 output 2 connected to input 3
FATAL output pin not wired to input pin? (out high => in low)

**Environment (please complete the following information):**
 - OS: fedora28
 - Toolchain: zephyr-sdk-0.11.1
 - Commit ID: 55eb4a11c

**Comment by pabigot** [comment]
This is a documentation issue: people running the tests need to know that for the test to work on a given platform there must be a devicetree overlay for that platform in the `boards` directory, and that the two pins identified in that overlay need to be shorted together.  This is currently indicated in the output:

> Check GPIO_0 output 2 connected to input 3
> FATAL output pin not wired to input pin? (out high => in low)

There is no overlay for `reel_board` since what it tests would be handled by `nrf52840_pca10056`.  For `frdm_k64f` the overlay specifies that Arduino D0 and D1 must be shorted.

I'll prepare a README for this test to explain all this, unless somebody else does it first.

**Comment by chen-png** [comment]
@pabigot Can we use the testcase.yml to exclude those unsupported boards?

because we use the sanitycheck to run all tests in testing system, if we modify the README file, for each board, when running sanitycheck command, we have to use the sanitycheck's option to exclude this test.
if we can modify the testcase.yml, we can just run sanitycheck command, don't care about boards.

**Comment by pabigot** [comment]
@chen-png Probably.  Please see #22754; I think it should exclude unsupported boards.

**Comment by chen-png** [comment]
>  Please see #22754; I think it should exclude unsupported boards.

@pabigot  it seems that it only excludes the reel_board,  for frdm_k64f, sam_e70_xplained and mimxrt1050_evk, still the same error.

**Comment by pabigot** [comment]
Does it work if you short the input pin to the output pin, as directed in the README?

Because the test simply cannot pass on a board that doesn't have the test configuration.  There's nothing I can do about that.

**Comment by nashif** [comment]
@chen-png  please follow up

**Comment by chen-png** [comment]
@pabigot  for sam_e70_xplained,  according to the board's overlay, i connected portd 21 and portd 20, then this test passed.
but for frdm_k64f and mimxrt1050_evk, i couldn't find the GPIO pin on board, so do you know where the pin is or have any board manual?

**Comment by pabigot** [comment]
For `frdm_k64f` the overlay specifies these are Arduino D0 and D1.   When oriented with the ethernet jack on the front at tht top, these are the lowest two pins on the right side outer column of female headers.   There's silkscreen on the back that shows which pins are on each header.

The same two pins are used on the arduino header of mimxrt10x0_evk.  The header on the 1060 next to the 20-pin JTAG header.

**Comment by chen-png** [comment]
@pabigot  thanks for your information.
shorted related pins and tested this case on frdm_k64f and mimxrt1050_evk, this case passed.
