### ISSUE TITLE
arm: cortex-a: no default board for testing

### ISSUE THREAD

**Issue by ioannisg** [zephyrproject-rtos/zephyr#22682]
**Describe the bug**
The recently merged ARM Cortex-A architecture has not defined a default board for testing.
Currently, qemu_cortex_a53 is the only Cortex-A board in the tree, and should IMO be set to be tested by default.

**Impact**
No testing coverage for Cortex-A architecture, similar to the other architectures.

**Comment by ioannisg** [comment]
FYI @jhedberg

**Comment by carlocaione** [comment]
Opened #22683
