### ISSUE TITLE
Implement counter driver for lpcxpresso55s69

### ISSUE THREAD

**Issue by MaureenHelm** [zephyrproject-rtos/zephyr#22705]
**Is your enhancement proposal related to a problem? Please describe.**
The `lpcxpresso55s69` board currently lacks support for counter in zephyr.

**Describe the solution you'd like**
Implement a shim driver that adapts the mcux lpc RTC driver to the zephyr counter interface. The existing `counter_mcux_rtc.c` and `counter_mcux_gpt.c` shim drivers for kinetis and i.mx rt can be used for reference. Enable `tests/drivers/counter` for this board to ensure the counter driver builds and functions correctly.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by puranjaymohan** [comment]
Hi, I want to work on this as a first-time contributor. Please tell me if a contribution wiki or guide is available?

**Comment by galak** [comment]
https://docs.zephyrproject.org/latest/contribute/index.html
