### ISSUE TITLE
Implement ADC driver for lpcxpresso55s69

### ISSUE THREAD

**Issue by MaureenHelm** [zephyrproject-rtos/zephyr#22703]
**Is your enhancement proposal related to a problem? Please describe.**
The `lpcxpresso55s69` board currently lacks support for ADC in zephyr.

**Describe the solution you'd like**
Implement a shim driver that adapts the mcux lpc ADC driver to the zephyr ADC interface. The existing `adc_mcux_adc12.c` and `adc_mcux_adc16.c` shim drivers for kinetis and i.mx rt can be used for reference. Enable `tests/drivers/adc` for this board to ensure the ADC driver builds and functions correctly.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by tobyfirth** [comment]
I have created a pull request that adds the driver shim for the lpadc. The ADC tests are all passing. I have tried using the driver to read from the internal temperature sensor but I don't seem to be able to get expected temperature values. I think this is probably dues to not altering the board correctly as the user manual and the readme.txt in the example code from the SDK. This could also be to not setting the external voltage reference up correctly.
