### ISSUE TITLE
Implement watchdog driver for lpcxpresso55s69

### ISSUE THREAD

**Issue by MaureenHelm** [zephyrproject-rtos/zephyr#22704]
**Is your enhancement proposal related to a problem? Please describe.**
The `lpcxpresso55s69` board currently lacks support for watchdog in zephyr.

**Describe the solution you'd like**
Implement a shim driver that adapts the mcux lpc wwdt driver to the zephyr watchdog interface. The existing `wdt_mcux_wdog.c` and `wdt_mcux_wdog32.c` shim drivers for kinetis and i.mx rt can be used for reference. Enable `tests/drivers/watchdog` for this board to ensure the watchdog driver builds and functions correctly.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by Nephirus** [comment]
Here is PR for NXP HAL, that builds relevant HAL driver when shim driver is enabled: https://github.com/zephyrproject-rtos/hal_nxp/pull/48

I also have a working shim driver for the watchdog, I'll create PR for that soon (after some clean-up).

**Comment by MaureenHelm** [comment]
Great, thank you!

**Comment by Nephirus** [comment]
No problem :)

Promised PR for shim driver: https://github.com/zephyrproject-rtos/zephyr/pull/26779

`samples/drivers/watchdog` works on LPCXpresso55S69 board, but I'm not 100% sure about Kconfig related stuff.
