### ISSUE TITLE
mesh: typo in condition in comp_add_elem of cfg_srv

### ISSUE THREAD

**Issue by ToJIka4** [zephyrproject-rtos/zephyr#22822]
https://github.com/zephyrproject-rtos/zephyr/blob/1156412904605cdbe43310680e9311dc5998423d/subsys/bluetooth/mesh/cfg_srv.c#L53
i think there should be
`4 + (elem->model_count * 2U) + (elem->vnd_model_count * 4U)) {`

**Comment by aescolar** [comment]
CC @jhedberg

**Comment by jhedberg** [comment]
@ToJIka4 looks like you're right. Are you planning to submit a pull request?

**Comment by ToJIka4** [comment]
@jhedberg Okay, I'll do it
