### ISSUE TITLE
Problem using 3 instances of SPIM on NRF52840

### ISSUE THREAD

**Issue by mi-alkoudsi** [zephyrproject-rtos/zephyr#22893]
When enabling 3 instances of SPIM (1,2,3) on nrf52840_pca10056 the application doesn't start at all (Keeps restarting when trying to get the references to spi drivers).

Weirdly however, the application works fine when SPI3 takes SPIM3 and the rest SPI0, SPI2 respectively, or when SPIM1 and SPIM2 are enabled and "SPI3 instance" is disabled

The simultaneous sending on 3 SPI, which I need for my application can only happen if all are SPIM thanks to easyDMA

Attached is a sample application to reproduce this problem
[3spi.zip](https://github.com/zephyrproject-rtos/zephyr/files/4218227/3spi.zip)

Help is highly appreciated.

Many thanks

**Comment by anangl** [comment]
@mi-alkoudsi You need to apply [this patch](https://github.com/zephyrproject-rtos/zephyr/commit/377002d4b59aafa20ce9bb71ae561c7536185c19), which is already present in master but unfortunately didn't manage to get into v2.1.0 release.
