### ISSUE TITLE
si7006 temperature conversion offset missing

### ISSUE THREAD

**Issue by anthonybrandon** [zephyrproject-rtos/zephyr#22907]
The si7006 sensor driver (./drivers/sensor/si7006/si7006.c) is missing an offset as described in the [datasheet.](https://www.silabs.com/documents/public/data-sheets/Si7006-A20.pdf) An offset of 46.85 should be subtracted in order to get the temperature in degrees Celsius. 

#19941 attempts to fix it along with some unrelated changes.

**Comment by carlescufi** [comment]
@anthonybrandon would you mind reviewing and testing #19941 to see if we can move it forward?

**Comment by anthonybrandon** [comment]
@carlescufi 

Sure, I have a board I can try it out on.
Do I just report it in a comment on the merge request once I have tried it, or did you mean something else?

**Comment by carlescufi** [comment]
> @carlescufi
> 
> Sure, I have a board I can try it out on.
> Do I just report it in a comment on the merge request once I have tried it, or did you mean something else?

Yep, just approve the Pull Request and add a comment there.

**Comment by MaureenHelm** [comment]
Fixed by #24563
