### ISSUE TITLE
PTS: Test Framework: Bluetooth: SM/MAS/SIGN/BV-03-C, SM/MAS/SIGN/BI-01-C - INCONCLUSIV 

### ISSUE THREAD

**Issue by agata-ponitka** [zephyrproject-rtos/zephyr#22928]
Describe the bug
Failed to distribute keys.

To Reproduce
run auto-pts

Expected behavior
IUT faild to distribute CSRK.

[SM_MAS_SIGN_BI-01-C-INCONC.txt](https://github.com/zephyrproject-rtos/zephyr/files/4223782/SM_MAS_SIGN_BI-01-C-INCONC.txt)
[SM_MAS_SIGN_BV-03-C-INCONC.txt](https://github.com/zephyrproject-rtos/zephyr/files/4223783/SM_MAS_SIGN_BV-03-C-INCONC.txt)

**Comment by aescolar** [comment]
CC @jhedberg @joerchan

**Comment by joerchan** [comment]
If I am reading the attached logs correctly it looks like there is an SMP error with SMP_UNSPECIFIED error code. Is it possible to get some more information or logs for these 2 test cases?

**Comment by agata-ponitka** [comment]
Yes, I am sending logs in attachment. 

[SM_MAS_SIGN_BI-01-C.zip](https://github.com/zephyrproject-rtos/zephyr/files/4230941/SM_MAS_SIGN_BI-01-C.zip)

[SM_MAS_SIGN_BV-03-C.zip](https://github.com/zephyrproject-rtos/zephyr/files/4230805/SM_MAS_SIGN_BV-03-C.zip)

**Comment by carlescufi** [comment]
@agata-ponitka could you please give us the exact command-line that you are using on the client side please?

**Comment by agata-ponitka** [comment]
@carlescufi of course: ./autoptsclient-zephyr.py autopts-zephyr-210 ~/zephyrproject/zephyr/build/zephyr/zephyr.elf -i 192.168.56.101 -t /dev/ttyACM0 -b nrf52 -l 192.168.56.1 -c SM/MAS/SIGN/BI-01-C

**Comment by carlescufi** [comment]
> @carlescufi of course: ./autoptsclient-zephyr.py autopts-zephyr-210 ~/zephyrproject/zephyr/build/zephyr/zephyr.elf -i 192.168.56.101 -t /dev/ttyACM0 -b nrf52 -l 192.168.56.1 -c SM/MAS/SIGN/BI-01-C

Thank you @agata-ponitka.

**Comment by joerchan** [comment]
@agata-ponitka The PTS appears to be affected by a race condition in the HCI USB protocol. I have created a PR which has a workaround for this during testing, by simply sleeping for 10 ms before starting to distribute the keys.
The tests are still inconclusive though. I think some extra auto-pts changes might be needed to confirm that the data with wrong MAC was not accepted on the tester side.

**Comment by jhedberg** [comment]
Downgraded to medium since this looks like a PTS & auto-pts issue

**Comment by carlescufi** [comment]
@agata-ponitka this is now an autops/tester app issue with an "mmi" failure.

**Comment by agata-ponitka** [comment]
I have added changes in autopts and retested with the latest master. The tests are pass now. Thank you.

**Comment by aescolar** [comment]
Closing then. Thanks

**Comment by carlescufi** [comment]
I've also re-run those locally and they pass for me as well. cc @joerchan
