### ISSUE TITLE
Missing TX power options for nRF52833

### ISSUE THREAD

**Issue by pdunaj** [zephyrproject-rtos/zephyr#22942]
**Describe the bug**
TX power higher then +4 dBm in not available for nRF52833.

**To Reproduce**
See `subsys/bluetooth/controller/Kconfig` or try enabling +8 dBm on mentioned SoC.

**Expected behavior**
All power configurations supported by HW should be made available.

**Impact**
Reduced functionality.

**Screenshots or console output**
N/A

**Environment (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by aescolar** [comment]
CC @carlescufi

**Comment by pdunaj** [comment]
Hi @carlescufi , maybe instead of adding nRF5233 in the `depend on` it would be better to add some characteristic to SoC family that support higher TX power options? Otherwise this will be edited more frequently.

**Comment by carlescufi** [comment]
Fixed in https://github.com/zephyrproject-rtos/zephyr/commit/3b4ead139fc2
