### ISSUE TITLE
scripts/footprint/size_report doesn't work on qemu_x86_64

### ISSUE THREAD

**Issue by andrewboie** [zephyrproject-rtos/zephyr#22996]
**Describe the bug**

From running "make rom_report" on a test built for qemu_x86_64:

```
Traceback (most recent call last):
  File "/home/apboie/projects/zephyr3/zephyr/scripts/footprint/size_report", line 461, in <module>
    main()
  File "/home/apboie/projects/zephyr3/zephyr/scripts/footprint/size_report", line 449, in main
    fp = get_footprint_from_bin_and_statfile(bin_file, stat_file, 0, 0)
  File "/home/apboie/projects/zephyr3/zephyr/scripts/footprint/size_report", line 137, in get_footprint_from_bin_and_statfile
    get_section_size(f, ".bss") +
  File "/home/apboie/projects/zephyr3/zephyr/scripts/footprint/size_report", line 117, in get_section_size
    decimal_size = int(res.split()[4], 16)
IndexError: list index out of range
zephyr/cmake/reports/CMakeFiles/rom_report.dir/build.make:57: recipe for target 'zephyr/cmake/reports/CMakeFiles/rom_report' failed
make[3]: *** [zephyr/cmake/reports/CMakeFiles/rom_report] Error 1
CMakeFiles/Makefile2:2751: recipe for target 'zephyr/cmake/reports/CMakeFiles/rom_report.dir/all' failed
make[2]: *** [zephyr/cmake/reports/CMakeFiles/rom_report.dir/all] Error 2
CMakeFiles/Makefile2:2758: recipe for target 'zephyr/cmake/reports/CMakeFiles/rom_report.dir/rule' failed
make[1]: *** [zephyr/cmake/reports/CMakeFiles/rom_report.dir/rule] Error 2
Makefile:560: recipe for target 'rom_report' failed
make: *** [rom_report] Error 2

```

Looking at the code, this script needs a redesign how it obtains data. It relies on external tools and text processing, but this is not ideal. This script should be able to inspect a .elf file directly and get all the info it needs with pyelftools, as scripts like gen_kobject_list.py do.

In addition, its calculation of RAM sizes depends on a hard-coded list of sections:
```

    # getting used ram on target
    total_used_ram = (get_section_size(f, "noinit") +
                      get_section_size(f, "bss") +
                      get_section_size(f, "initlevel") +
                      get_section_size(f, "datas") +
                      get_section_size(f, ".data") +
                      get_section_size(f, ".heap") +
                      get_section_size(f, ".stack") +
                      get_section_size(f, ".bss") +
                      get_section_size(f, ".panic_section"))

```

This is highly susceptible to bit-rot as new data sections are added or removed from the kernel. Several of these named above don't even exist. The .elf contains sufficient information on section properties to determine what ends up in RAM and what doesn't, do that instead.

**Comment by nashif** [comment]
> Looking at the code, this script needs a redesign how it obtains data. It relies on external tools and text processing, but this is not ideal. This script should be able to inspect a .elf file directly and get all the info it needs with pyelftools, as scripts like gen_kobject_list.py do.

this script predates all the pyelftool magic we added, agree it should use the same infrastructure we have already...
