### ISSUE TITLE
logging: Sync timestamp between cores

### ISSUE THREAD

**Issue by koffes** [zephyrproject-rtos/zephyr#23021]
The logging system has a useful feature where a timestamp is prepended each log message.

This works well on single core MCU's, but in some situations you want to investigate multi-core applications. E.g. both cores crash, and you need to figure ut what took place first.
Suggest adding a config of type CONFIG_LOG_TIMESTAMP_SYNC. This will ensure that e.g. a LOG_DBG which is called on each core at the same point in time gets the same timestamp.

I realise that this is may well be far from trivial, as well as platform specific.
@nordic-krch

**Comment by carlescufi** [comment]
This should probably be generalized to synchronization between cores of several data items, including timestamps.

**Comment by koffes** [comment]
@nordic-krch: Is this something that is feasible? We often come across issues where figuring out which log message comes first is essential.

**Comment by koffes** [comment]
Test

**Comment by nordic-krch** [comment]
@koffes I've prepared PR which adds mechanism for synchronization. It's nrf53 specific. See #38495
