### ISSUE TITLE
LL.TS Test LL/CON/SLA/BV-129-C fails (split)

### ISSUE THREAD

**Issue by mtpr-ot** [zephyrproject-rtos/zephyr#23109]
With the introduction of commit "Bluetooth: controller: split: fix LL/CON/MAS/BV-74-C tx timing" (0ac4433a12), the test LL/CON/SLA/BV-129-C fails on EBQ.

**To Reproduce**
Run LL/CON/SLA/BV-129-C on EBQ on "split" controller, without coded PHY.

**Expected behavior**
Without commit 0ac4433a12 the test passes - with it, it fails.

**Impact**
Qualification on Zephyr 2.2 will fail.

**Additional context**
Non-Nordic HW platform and link layer used.

**Comment by aescolar** [comment]
CC @kruithofa @cvinayak
