### ISSUE TITLE
boards: adafruit_feather_m0: don't throw compiler warnings on using custom sercom config

### ISSUE THREAD

**Issue by KubaFYI** [zephyrproject-rtos/zephyr#23133]
In order to use it's serial peripheral SERCOMs SAD1 requires their pins to be configured with pinmux. Currently that's enabled only for the board default serial interfaces: the USART TX/RX on sercom0, an SPI interface on sercom4, and the USB port. The pinmux code currently is written to throw a compiler error if a user app tries to use any sercom in a way it wasn't pre-defined to be used. The error claims the pin mapping have not been configured but at the same time it doesn't give a chance for this configuration to take place in app code. 

I propose that those errors are changed to warnings which would allow users to proceed with compilation and configure the pin mappings themselves should they wish to use sercom1-sercom3.

The relevant file is [pinmux.c](https://github.com/zephyrproject-rtos/zephyr/blob/master/boards/arm/adafruit_feather_m0_basic_proto/pinmux.c)

**Comment by KubaFYI** [comment]
What do you think @henrikbrixandersen ?

**Comment by henrikbrixandersen** [comment]
Sounds like an okay solution to me.
