### ISSUE TITLE
Toolchain docs: describe macOS un-quarantine procedure

### ISSUE THREAD

**Issue by snej** [zephyrproject-rtos/zephyr#23168]
I'm new to Zephyr and embedded development, but an experienced Mac/iOS developer. I'm following the Getting Started guide.

When building the "blinky" program, I get an onscreen alert saying that the app "arm-none-eabi-gcc" is from an unknown developer and can't be opened. The only options are to cancel (which causes the build to fail, of course) or delete the binary.

I'm used to this with apps and know the workaround (right-click, choose Open, click OK). This works with raw binaries as well once I find them in the Finder; however, this keeps happening for every different binary in the GCC toolchain.

I found the answer on StackOverflow: run `xattr -r -d com.apple.quarantine .` in the GCC toolchain root directory (not just its `bin` subdirectory!)

This would be very useful to add to your 3rd-party-toolchain documentation, since I imagine a lot of developers won't have run into this issue before — I haven't, probably because HomeBrew un-quarantines binaries automatically.

**Comment by carlescufi** [comment]
There is an "easier" way, see this screenshot:

![image](https://user-images.githubusercontent.com/12450381/75769118-e091ce80-5d45-11ea-89d0-033b13e34637.png)

Would you mind sendin a pull request @snej ?
