### ISSUE TITLE
Common west flash, debug arguments like --hex-file can't be used from command line

### ISSUE THREAD

**Issue by mbolivar** [zephyrproject-rtos/zephyr#23172]
**Describe the bug**
https://github.com/zephyrproject-rtos/zephyr/commit/eb95bed552f2977d77511d3c4fab0cba9f30a7a9 broke the ability to `west flash --hex-file foo.hex`.

A fix is in https://github.com/zephyrproject-rtos/zephyr/pull/23171

**To Reproduce**
1. west build -b nrf52840_pca10056 -s samples/hello_world
2. cp build/zephyr/zephyr.hex my-cool-zephyr.hex
3. west flash --hex-file my-cool-zephyr.hex

Notice that build/zephyr/zephyr.hex is flashed, not my-cool-zephyr.hex.

**Expected behavior**
my-cool-zephyr.hex is flashed instead.

**Impact**
Showstopper

**Environment (please complete the following information):**
 - Commit SHA or Version used: introduced in eb95bed552f

**Additional context**
Reported by Tarjei Knapstad on Slack.

**Comment by jhedberg** [comment]
#23171 was merged
