### ISSUE TITLE
Bluetooth: Mesh: Access structure member with a possible NULL pointer

### ISSUE THREAD

**Issue by tluio** [zephyrproject-rtos/zephyr#23177]
File: /subsys/bluetooth/mesh/cfg_srv.c
Function: friend_set, send_friend_status

On line 2681 of the code, in function friend_set, **model->user_data** is assigned to **cfg**.
On line 2692 of the code, if **cfg** is NULL, jump to label send_status where send_friend_status is called and **model** is passed as the first argument.
On line 2656 of the code, in function send_friend_status, **model->user_data** is assigned to **cfg**. **model** is the first formal parameter, so the local variable **cfg** is NULL here.
On line 2659 of the code, when calling function net_buf_simple_add_u8, a member is accessed through **cfg->frnd**, but **cfg** is NULL here.

[https://github.com/zephyrproject-rtos/zephyr/blob/master/subsys/bluetooth/mesh/cfg_srv.c](url)

**Comment by aescolar** [comment]
CC @jhedberg @trond-snekvik

**Comment by jhedberg** [comment]
The bug is actually the unnecessary check in `friend_set()` since the `cfg_srv_init()` function ensures that `model->user_data` is always non-NULL. Setting low priority for this one since it's essentially harmless, but we should still strive to eliminate dead code like this.

**Comment by joerchan** [comment]
@tluio Not sure why you closed it. We should eliminate the dead code.

**Comment by tluio** [comment]
> @tluio Not sure why you closed it. We should eliminate the dead code.

Sorry, I am not familiar with github, so I am not sure when issues should be closed. Thank you for reopening it. I will be more careful next time.

**Comment by joerchan** [comment]
Fixed by: https://github.com/zephyrproject-rtos/zephyr/pull/25365
