### ISSUE TITLE
Macro value for 10 bit ADC is wrong in MEC driver.

### ISSUE THREAD

**Issue by AdiIntel** [zephyrproject-rtos/zephyr#23202]
Current microchip ADC driver is using reserved fields to program 10bit resolution setting.
In :\modules\hal\microchip\mec\mec1501\component\adc.h: 
`#define MCHP_ADC_SAR_CTRL_RES_10_BITS	(0x01ul << 1)`

This value should be: 
`#define MCHP_ADC_SAR_CTRL_RES_10_BITS	(0x02ul << 1)`

Also, when using 10 bit resolution, driver should shift data in reading register.
adc_mchp_xec.c driver should use `MCHP_ADC_SAR_CTRL_SHIFTD_EN ` when using 10bit resolution.

**Comment by albertofloyd** [comment]
@scottwcpg could you update  the HAL ?
@dcpleung seems driver changes is also required.
