### ISSUE TITLE
RISCV Machine Timer consistently interrupts long running system after soft reset

### ISSUE THREAD

**Issue by jaronkelleher** [zephyrproject-rtos/zephyr#23231]
On a long running riscv platform, the microprocessor may get a soft reset, while the rest of the platform is not reset. In this scenario, the riscv machine timer driver does not function properly. After the first tick interrupt, the timer will constantly interrupt the microprocessor due to invalid mtimecmp register values.

1. Run the system long enough for the mtime register to be greater than 0x2_0000_0000
2. Using a debugger, reset the MCU. Debugger will execute an ndmreset. Since the implementation of ndmreset is platform specific, the CLINT registers may not be reset.
3. Allow the system to boot
4. Witness as the system is constantly interrupted by the timer.

**Expected behavior**
I expect the microprocessor to start normally

**Impact**
Showstopper without the fix

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain Zephyr SDK
 - Commit SHA: 2709b14bcb368dcc5a0e61783bcff7a04b0488c6

Edit 1: Added debugger command for reset
Edit 2: Issue is experienced on platforms that do not reset CLINT registers with ndmreset signal

**Comment by jaronkelleher** [comment]
Associated with pull request #23201

**Comment by jhedberg** [comment]
@jaronkelleher if #23201 will fix this, could you add the appropriate "Fixes #23231" to its description so that GitHub will auto-close this one once it's merged.
