### ISSUE TITLE
Add secure version of strcpy

### ISSUE THREAD

**Issue by yashi** [zephyrproject-rtos/zephyr#23248]
We lack `strlcpy()` or `strscpy()` and its friend.  As a secure RTOS, we should have at least one of those string copy functions.  Rationale behind the new APIs are that neither standard `strcpy()` nor `strncpy()` does not guarantee the terminal NUL character.

 - [`strlcpy()`][1] is more widely used variant from OpenBSD.  It returns the length of the source string.
- [`strscpy()`][2] is Linux kernel version of it.  It doesn't touch the source string past the specified size and returns negative when error.

There are some discussion on both [OpenBSD side][3] and [Linux kernel side][4], but both functions make sure that the destination string is NUL terminated.

[1]: https://www.usenix.org/legacy/event/usenix99/full_papers/millert/millert.pdf
[2]: https://www.kernel.org/doc/htmldocs/kernel-api/API-strscpy.html
[3]: https://marc.info/?l=openbsd-tech&m=154859632818332&w=2
[4]: https://lkml.org/lkml/2015/4/28/570

**Comment by vaussard** [comment]
You have an implementation of `strlcpy()` in Zephyr SDK:
```
arm-zephyr-eabi/include/string.h:116:size_t     strlcpy (char *, const char *, size_t);
```
but it is hidden by default. You have to `#define _GNU_SOURCE` before including `string.h`.

**Comment by nashif** [comment]
this should not be part of zephyr, you can have this as part of your application/environment.

**Comment by stephanosio** [comment]
TODO:
1. Consider adding a config to enable the relevant functions in newlib.
2. Consider adding tests for these as part of the newlib tests.

**Comment by yashi** [comment]
A few questions:
 - Is it just for newlib? I don't really follow #3102 but does it still hold?
 - What has changed since https://github.com/zephyrproject-rtos/zephyr/issues/23248#issuecomment-668721295?

**Comment by yashi** [comment]
I'm closing this since picolibc is the default c library for Zephyr for a while now. And it at least provides `strlcpy()`.
