### ISSUE TITLE
power: subsystem: Application hangs when logging is enabled after entering deep sleep

### ISSUE THREAD

**Issue by albertofloyd** [zephyrproject-rtos/zephyr#23274]
When logging is enabled and used in app that sleeps periodically for enough time to enter deep sleep (Sleep time higher than minimum residency)

After entering deep sleep the application thread never execute again which can be perceived as application hang.

Note: from kernel debug traces, deep sleep is exited but immediately re-entered, giving no opportunity for other threads to run.

1. Get board sample code from https://github.com/zephyrproject-rtos/zephyr/pull/23275
2. cd samples/boards/mec15xxevb_assy6853 
3. mkdir build; cd build
4. cmake -DBOARD=mec15xxevb_assy6853
5. make
6. Flash on EVB
7. Check UART logs
"Wake from light sleep" will be seen, 
"Wake from deep sleep" won't be seen

**Expected behavior**
Board test sleeps for different duration in a loop.
1st case app sleeps for 500 ms more than minimum light sleep residency.
2nd case app sleeps for 500 ms more than minimum deep sleep residency.

Note: Issue is not reproducible if logging is either completely disabled or not used in between k_sleep() during the test.

**Impact**
High cannot enable/use logging simultaneously with deep sleep. 

**Environment (please complete the following information):**
 - OS: (e.g. Linux, MacOS, Windows)
 - Toolchain (e.g Zephyr SDK, ...)
 - Commit SHA or Version used

**Comment by wentongwu** [comment]
```
#ifdef CONFIG_KERNEL_DEBUG
#define K_DEBUG(fmt, ...) printk("[%s]  " fmt, __func__, ##__VA_ARGS__)
#else
#define K_DEBUG(fmt, ...)
#endif
```
if enabled CONFIG_KERNEL_DEBUG, it will use printk to output debug message. But for your test case, you also enable logging system with CONFIG_LOG=y, I think we should same mechanism to do the output, so could you please try below patch with latest commit, I test it locally, there is no hang like the description. 

```
diff --git a/samples/boards/mec15xxevb_assy6853/power_management/prj.conf b/samples/boards/mec15xxevb_assy6853/power_management/prj.conf
index 328bcabbec..fc2b07a5e6 100644
--- a/samples/boards/mec15xxevb_assy6853/power_management/prj.conf
+++ b/samples/boards/mec15xxevb_assy6853/power_management/prj.conf
@@ -6,6 +6,7 @@ CONFIG_LOG_PROCESS_THREAD_SLEEP_MS=2100
 
 # Enable kernel debug
 CONFIG_KERNEL_DEBUG=y
+CONFIG_LOG_PRINTK=y
 CONFIG_THREAD_NAME=y
 # Enable PM debug in MEC1501 this will give indication in MCHP_060
 CONFIG_SYS_PM_DEBUG=y
```

**Comment by wentongwu** [comment]
@albertofloyd I will submit a PR.

**Comment by albertofloyd** [comment]
@wentongwu  are you saying that the problem is due to wrong combination of debug options in KConfig?  I will try the PR

**Comment by wentongwu** [comment]
> @wentongwu are you saying that the problem is due to wrong combination of debug options in KConfig? I will try the PR

@albertofloyd yes, please try it, thanks.
