### ISSUE TITLE
Bluetooth: controller: Use defines for 625 us and 1250 us

### ISSUE THREAD

**Issue by cvinayak** [zephyrproject-rtos/zephyr#23314]
**Is your enhancement proposal related to a problem? Please describe.**
Bluetooth controller implementation uses magic numbers 625 and 1250 for the advertising interval and connection interval units.

**Describe the solution you'd like**
Use defines for the values 625 and 1250

**Describe alternatives you've considered**
None

**Additional context**
Refer to comments in https://github.com/zephyrproject-rtos/zephyr/pull/21831

**Comment by Nukersson** [comment]
Maybe Kconfig solution would be better?

**Comment by cvinayak** [comment]
These are constant values, and used all around the implementation for varies purposes. Based on their use, suitable names need be given. If some of these are user (desired) configurables, then they can be Kconfig.
