### ISSUE TITLE
tests/kernel/sched/schedule_api failed on mps2_an385 with v1.14 branch.

### ISSUE THREAD

**Issue by chen-png** [zephyrproject-rtos/zephyr#23339]
**To Reproduce**
1. west build -b mps2_an385 -p auto tests/kernel/sched/schedule_api -t run

**Screenshots or console output**
****Booting Zephyr OS zephyr-v1.14.1-49-gff6829261918 *****
Running test suite threads_scheduling

starting test - test_bad_priorities
PASS - test_bad_priorities

starting test - test_priority_cooperative
PASS - test_priority_cooperative

starting test - test_priority_preemptible
PASS - test_priority_preemptible

starting test - test_yield_cooperative
PASS - test_yield_cooperative

starting test - test_sleep_cooperative
PASS - test_sleep_cooperative

starting test - test_sleep_wakeup_preemptible
PASS - test_sleep_wakeup_preemptible

starting test - test_pending_thread_wakeup
PASS - test_pending_thread_wakeup

starting test - test_time_slicing_preemptible
PASS - test_time_slicing_preemptible

starting test - test_time_slicing_disable_preemptible
PASS - test_time_slicing_disable_preemptible

starting test - test_lock_preemptible
PASS - test_lock_preemptible

starting test - test_unlock_preemptible
PASS - test_unlock_preemptible

starting test - test_sched_is_preempt_thread
PASS - test_sched_is_preempt_thread

starting test - test_slice_reset
PASS - test_slice_reset

**starting test - test_slice_scheduling
ABCDEFGHI
A
    Assertion failed at /home/chenpeng/zephyr-branch-1.14-github/zephyr/tests/kernel/sched/schedule_api/src/test_slice_scheduling.c:51: thread_tslice: ((tdelta >= expected_slice_min) && (tdelta <= expected_slice_max) && ((int)p1 == thread_idx)) is false**

B
    Assertion failed at /home/chenpeng/zephyr-branch-1.14-github/zephyr/tests/kernel/sched/schedule_api/src/test_slice_scheduling.c:51: thread_tslice: ((tdelta >= expected_slice_min) && (tdelta <= expected_slice_max) && ((int)p1 == thread_idx)) is false

C
    Assertion failed at /home/chenpeng/zephyr-branch-1.14-github/zephyr/tests/kernel/sched/schedule_api/src/test_slice_scheduling.c:51: thread_tslice: ((tdelta >= expected_slice_min) && (tdelta <= expected_slice_max) && ((int)p1 == thread_idx)) is false

D
    Assertion failed at /home/chenpeng/zephyr-branch-1.14-github/zephyr/tests/kernel/sched/schedule_api/src/test_slice_scheduling.c:51: thread_tslice: ((tdelta >= expected_slice_min) && (tdelta <= expected_slice_max) && ((int)p1 == thread_idx)) is false

E
    Assertion failed at /home/chenpeng/zephyr-branch-1.14-github/zephyr/tests/kernel/sched/schedule_api/src/test_slice_scheduling.c:51: thread_tslice: ((tdelta >= expected_slice_min) && (tdelta <= expected_slice_max) && ((int)p1 == thread_idx)) is false

F
    Assertion failed at /home/chenpeng/zephyr-branch-1.14-github/zephyr/tests/kernel/sched/schedule_api/src/test_slice_scheduling.c:51: thread_tslice: ((tdelta >= expected_slice_min) && (tdelta <= expected_slice_max) && ((int)p1 == thread_idx)) is false

G
    Assertion failed at /home/chenpeng/zephyr-branch-1.14-github/zephyr/tests/kernel/sched/schedule_api/src/test_slice_scheduling.c:51: thread_tslice: ((tdelta >= expected_slice_min) && (tdelta <= expected_slice_max) && ((int)p1 == thread_idx)) is false

H
    Assertion failed at /home/chenpeng/zephyr-branch-1.14-github/zephyr/tests/kernel/sched/schedule_api/src/test_slice_scheduling.c:51: thread_tslice: ((tdelta >= expected_slice_min) && (tdelta <= expected_slice_max) && ((int)p1 == thread_idx)) is false

I
    Assertion failed at /home/chenpeng/zephyr-branch-1.14-github/zephyr/tests/kernel/sched/schedule_api/src/test_slice_scheduling.c:51: thread_tslice: ((tdelta >= expected_slice_min) && (tdelta <= expected_slice_max) && ((int)p1 == thread_idx)) is false

    Assertion failed at /home/chenpeng/zephyr-branch-1.14-github/zephyr/tests/kernel/sched/schedule_api/src/test_slice_scheduling.c:51: thread_tslice: ((tdelta >= expected_slice_min) && (tdelta <= expected_slice_max) && ((int)p1 == thread_idx)) is false

FAIL - test_slice_scheduling

starting test - test_priority_scheduling
PASS - test_priority_scheduling

starting test - test_wakeup_expired_timer_thread
PASS - test_wakeup_expired_timer_thread

starting test - test_user_k_wakeup
PASS - test_user_k_wakeup

starting test - test_user_k_is_preempt
PASS - test_user_k_is_preempt

Test suite threads_scheduling failed.

PROJECT EXECUTION FAILED

**Environment (please complete the following information):**
 - OS: fedora28
 - Toolchain: zephyr-sdk-0.10.3
 - Commit ID: ff682926

**Comment by nashif** [comment]
fixed in 1.14 branch
