### ISSUE TITLE
bl65x_dvk boards do not reset after flashing

### ISSUE THREAD

**Issue by lairdjm** [zephyrproject-rtos/zephyr#23346]
**Describe the bug**
After flashing bl65x_dvk boards, they do not automatically reset

**To Reproduce**
ninja flash

**Expected behavior**
The module to reset

**Impact**
Slight annoyance

**Comment by lairdjm** [comment]
Fix for 1.14: https://github.com/zephyrproject-rtos/zephyr/pull/23344
Fix for master: https://github.com/zephyrproject-rtos/zephyr/pull/23345

**Comment by lairdjm** [comment]
There is still https://github.com/zephyrproject-rtos/zephyr/pull/23344 which needs to be merged (on the 1.14 branch)

**Comment by jhedberg** [comment]
> There is still #23344 which needs to be merged (on the 1.14 branch)

I've added it to the "To-do" column of https://github.com/zephyrproject-rtos/zephyr/projects/19 so that it gets processed appropriately.
