### ISSUE TITLE
UART Console input does not work on SiFive HiFive1 on echo sample app

### ISSUE THREAD

**Issue by carlosedp** [zephyrproject-rtos/zephyr#23395]
**Describe the bug**

The UART (serial) console does not work on the SiFive HiFive1 board (tested on the physical board and [Renode Simulation Framework](https://renode.io)).

I've built the `echo` [sample](https://github.com/zephyrproject-rtos/zephyr/tree/master/samples/subsys/console/echo) application, loaded to the board and simulator and it does not print to the console by using the `console_write` or `console_putchar` commands.

I only see:

```
 You should see another line with instructions below. If not,
the (interrupt-driven) console device doesn't work as expected:
```

![image](https://user-images.githubusercontent.com/20382/76415945-eb1d1b00-6378-11ea-8ce9-709d01be49e3.png)

And nothing more. On Renode debugging console, whenever I press some key in the console, I see on the logs: `09:08:07.4953 [WARNING] uart0: Trying to read data from empty receive fifo` but the character is not echoed back.

**To Reproduce**
1. mkdir build; cd build
2. cmake -DBOARD=hifive1 ../
3. make

The binary is correctly generated but presents the issue above.

To simulate the board, download and install Renode, build the ELF for the `echo` sample app. Open Renode and enter in the "Monitor" window (keep the @ characters):

```
include @scripts/single-node/sifive_fe310.resc
sysbus LoadELF @path/to/file/zephyr.elf
start
```

A new window will open with the serial console.

**Expected behavior**

Characters being correctly echoed back.

**Impact**

Nothing that requires serial console input works (notably, the shell).

**Environment (please complete the following information):**
 - OS: MacOS Mojave. Using PlatformIO as development IDE.
 - Toolchain: Zephyr 2.1.0 and 2.2.0
 - Renode: v1.9

**Additional context**

**Comment by carlosedp** [comment]
Hi folks, any news on this?
Cc. @carlescufi @nategraff-sifive

**Comment by nategraff-sifive** [comment]
I'm sheltering in-place for the foreseeable future and I don't have a board with me, so if you want progress from this it's not going to be from me, unfortunately. Sorry about that.

**Comment by carlosedp** [comment]
Could you try with a simulated HiFive1 on Antmicro Renode?

Check: https://www.zephyrproject.org/developing-zephyr-rtos-embedded-applications-on-platformio-and-simulating-on-antmicro-renode/

**Comment by carlescufi** [comment]
@carlosedp I suggest you  post in the mailing list and/or Slack to get more visibility. Aside from @nategraff-sifive, I know that there are a few ANT Micro employees that know this platform.

**Comment by carlosedp** [comment]
Confirming that both [echo](https://github.com/zephyrproject-rtos/zephyr/tree/master/samples/subsys/console/echo) and [shell](https://github.com/zephyrproject-rtos/zephyr/tree/master/samples/subsys/shell/shell_module) sample applications worked on the Renode HiFive1 simulated board with this fix.
Thanks @pabigot!
