### ISSUE TITLE
Remote opencd

### ISSUE THREAD

**Issue by steros76** [zephyrproject-rtos/zephyr#23425]
I use Raspberry PI as programmer for NRF 52832 chips.
Now I installed Zephyr on my PC and switched my project to this platform.
I see openocd is supported by Zephyr but it seems to me only for local use.
Is there a way to automate deployment with west tool using opencd listening on remote 4444 port of my Raspberry?
Thanks.

**Comment by mbolivar** [comment]
I don't know what this would take, sorry. I personally do not use openocd very much. Can you explain what you would do with openocd to get this done without using west?

**Comment by mbolivar-nordic** [comment]
I've switched my work-related account to @mbolivar-nordic (https://github.com/zephyrproject-rtos/zephyr/pull/23530).

**Comment by steros76** [comment]
Sorry, at the moment I can't give you exact command to execute.
Using command line I do it in 2 steps but using Eclipse it works automatically in remote mode.
I should investigate deeply how it works behind the scene. I'll post the instructions when I understand it. Sorry for the delay.

**Comment by mbolivar-nordic** [comment]
There's no rush. Thank you for your response.

**Comment by carlescufi** [comment]
We have no plans to implement this functionality. Please send a Pull Request if you have interest in this becoming part of the tree.
