### ISSUE TITLE
better Kconfig ontology for thread stack debugging

### ISSUE THREAD

**Issue by andrewboie** [zephyrproject-rtos/zephyr#23448]
In order to get the best output from the "kernel stacks" shell command, you need to have several Kconfigs turned on:

CONFIG_INIT_STACKS - to set up the stack buffers so measurements can be taken
CONFIG_THREAD_MONITOR - to be able to iterate over all threads
CONFIG_THREAD_STACK_INFO - to be able to get a reference to the stack object and its metadata from a thread object
CONFIG_THREAD_NAME - to be able to print human-readable thread names when dumping out thread information

It would be great if the end user could just enable something like CONFIG_THREAD_DEBUG which would either imply or replace some of these options.

**Comment by kartben** [comment]
See commit 3f8bdf1
