### ISSUE TITLE
bluetooth: host: Runtime HCI_LE_Create_Connection timeout

### ISSUE THREAD

**Issue by JordanYates** [zephyrproject-rtos/zephyr#23468]
**Is your enhancement proposal related to a problem? Please describe.**
I have a common GATT central application that is expected to connect to many different peripheral applications. Consider 2 applications, one which advertises at 10Hz, another at 1Hz.

A timeout of 500ms is likely sufficient for connecting to application A, while 5s may be desired for application B.
Waiting for 5 seconds for application A is a waste of time, as if you haven't connected in 500ms, you likely wont connect in 5 seconds (device has probably moved out of range).

Time spent initiating a connection that will never happen is time that you are not scanning for useful information from other devices.

**Describe the solution you'd like**
An additional interface `bt_conn_create_timeout` or similar, that updates the timeout for initiating connections.

**Describe alternatives you've considered**
Currently I am implementing this functionality by waiting on a semaphore that is given in the connection callback, where the wait duration is my desired timeout. Connection is then canceled through bt_conn_disconnect if the semaphore times out.

**Comment by JordanYates** [comment]
I will have a go at implementing this

**Comment by joerchan** [comment]
@JordanYates Have you considered to use a whitelist and `bt_conn_create_aute_le` for this?

**Comment by JordanYates** [comment]
@joerchan I hadn't previously, but it does not really fit the model of what we are trying to achieve.
We aren't interested in connecting to ANY device running application A or B. There can easily be over 50 devices  within bluetooth range, none of which I want to connect to. At some point in time, in response to an external command or as a result of the data that one particular device has sent, I want to connect to a specific device. Using the whitelists appears to add overhead without solving my actual problem, which is receiving a timely response that I can't connect to a device. Sometimes there is a user (often me) in the loop of this process, making the timely response more important.
