### ISSUE TITLE
Import from linux to zephyr?

### ISSUE THREAD

**Issue by didi110296** [zephyrproject-rtos/zephyr#23467]
Hello, I would like to import the library of a linux sensor on zephyr, is it possible? knowing that this library is under GPL license, can we use two licenses because zephyr is Apache license?
Thank you, cordially.

**Comment by carlescufi** [comment]
The Apache 2.0 license is not compatible with the GPLv2, but is compatible with the GPLv3:

https://www.gnu.org/licenses/license-list.html#GPLCompatibleLicenses
