### ISSUE TITLE
zephyr/samples/application_development/code_relocation execution stop at z_arm_bus_fault

### ISSUE THREAD

**Issue by kkiyota** [zephyrproject-rtos/zephyr#23599]
When I ran code_relocation sample on my custom board, execution was stopped by vector catch fault at z_arm_bus_fault.  Debugger screen shot is shown below.  I'm not sure so far if this is related to board, soc, DTS, etc or hardware, 

Could you advise which one I should check? 

![z_arm_bus_fault](https://user-images.githubusercontent.com/59073069/77050466-28367c80-6a0d-11ea-9463-c2cf0b62daad.png)

Thank you for your help!

**Comment by kkiyota** [comment]
In addition, it could work on qemu_cortex_m3 and nucleo_f767zi, but not on my own board.  So I assume something wrong for my own board setting.  I need your suggestions which items I should check.

Thanks!

**Comment by kkiyota** [comment]
I captured the following info when bus fault occurred.   Could you let me know how I can interpret it and how I can fix it?



![image](https://user-images.githubusercontent.com/59073069/77319709-a1f2a100-6d52-11ea-9e36-09ba57b93184.png)

**Comment by carlescufi** [comment]
@wentongwu @ioannisg @andrewboie any ideas?

**Comment by wentongwu** [comment]
@kkiyota please check the memory range for your board, sram2 section will be like this.
```
#define RAM_SIZE2 (CONFIG_SRAM_SIZE * 512)
MEMORY
    {
#ifdef CONFIG_SRAM2
    SRAM2                  (wx) : ORIGIN = (CONFIG_SRAM_BASE_ADDRESS + RAM_SIZE2), LENGTH = RAM_SIZE2
#endif
    }
```

**Comment by andrewboie** [comment]
@ioannisg might have some insight here.

**Comment by wentongwu** [comment]
@kkiyota ping

**Comment by wentongwu** [comment]
@kkiyota ping

**Comment by wentongwu** [comment]
@kkiyota any comment? Thanks

**Comment by kkiyota** [comment]
@wentongwu Since time has passed, I don't have this setup anymore.  So I need to decline it.

Thank you for your follow up!

**Comment by wentongwu** [comment]
@kkiyota ok, I will close this issue, please reopen it if any new finding, Thanks.
