### ISSUE TITLE
drivers: kscan: ft5336: add multitouch gestures etc.

### ISSUE THREAD

**Issue by k0d** [zephyrproject-rtos/zephyr#23643]
**Is your enhancement proposal related to a problem? Please describe.**
It appears that there are some gesture detection features in the ft5336 IC. These should be implemented.

**Describe the solution you'd like**
Not sure yet, this needs more research.

Registers are listed here.
https://github.com/STMicroelectronics/STM32CubeF7/blob/master/Drivers/BSP/Components/ft5336/ft5336.h
This could be useful also.
https://www.newhavendisplay.com/datasheets.html (application_notes has registers)

Edit: 
Official linux driver? We could port from this.
https://github.com/focaltech-systems/drivers-input-touchscreen-FTS_driver

**Comment by k0d** [comment]
@MaureenHelm I intend to implement more missing features from this. Just thought you'd like to know.

**Comment by gmarull** [comment]
Obsolete, this can now be handled using the input API.

**Comment by JohnAZoidberg** [comment]
See:

- https://github.com/zephyrproject-rtos/zephyr/pull/70631
- https://github.com/petejohanson/maxtouch-zephyr-module
- https://github.com/zephyrproject-rtos/zephyr/commit/ad254b06c8343fb607e6ab352b40c7c20dc4eff7
