### ISSUE TITLE
Building blinky sample program goes wrong

### ISSUE THREAD

**Issue by nonopx** [zephyrproject-rtos/zephyr#23662]
I have followed https://docs.zephyrproject.org/2.2.0/getting_started/index.html guide in order to
download zephyr.

On step 6.2 - west build -p auto -b <your-board-name> samples/basic/blinky
(I put esp32 although I do not have the hardware yet. just trying to build the program)

I was excepting the build to go right but instead, I'm getting this error message (screenshot ):

![img1](https://user-images.githubusercontent.com/39962003/77234269-a46bc400-6bb5-11ea-8067-c89645d97ec6.png)
![img2](https://user-images.githubusercontent.com/39962003/77234272-aa61a500-6bb5-11ea-98db-8de87df98ddb.png)

Environment:
 - OS: (Linux VM on windows host)
 - Toolchain (Zephyr SDK)
 - Zephyr version: 2.2.99

**Comment by nashif** [comment]
Zephyr SDK does not support building the ESP32, for that, you need to download the toolchain from espressif and setup the toolchain according to the board documentation.

**Comment by jenmwms** [comment]
@nonopx Here is some documentation with that info for the ESP32 board in Zephyr - https://docs.zephyrproject.org/latest/boards/xtensa/esp32/doc/index.html
Check out the https://docs.zephyrproject.org/latest/boards/xtensa/esp32/doc/index.html#system-requirements

**Comment by nonopx** [comment]
Thank you very much
