### ISSUE TITLE
SPI slave driver doesn't work correctly on STM32F746ZG; needs spi-fifo to be enabled in DT

### ISSUE THREAD

**Issue by bobcagle** [zephyrproject-rtos/zephyr#23677]
**Describe the bug**
SPI slave transactions do not complete successfully on STM32F746ZG. The Master gets the initial transmitted response (4-bytes) okay, but the Slave does not complete the transaction. It waits for more data, which will only arrive in a future  transaction.

I verified my hardware was working by generating and running an equivalent STM32cubeIDE app as the Slave app. The app ran with no problems. 

I noticed the SPI driver makes use of #ifdefs to enable FIFO support, but the #ifdefs were not enabled on my build. Looking into that, I  added  'st,spi-fifo' to the compat driver to the spi1 device in 
dts/arm/st/f7/stm32f7.dtsi:
                      compatible = "st,stm32-spi-fifo", "st,stm32-spi";

This solved the problem, so apparently the logic does not work correctly if the FIFOs are not enabled but the hardware supports them.

Sorry, I accidentally submitted before I completed the rest of the form.

Platform was Linux. Zephyr SDK. 
Commit: e4538c6807c34735a3ed5ed76999d5e98b39dee0

**Comment by erwango** [comment]
^^@ABOSTM, can you check ?
