### ISSUE TITLE
STACK_POINTER_RANDOM is not working on ARM for the main thread

### ISSUE THREAD

**Issue by ceolin** [zephyrproject-rtos/zephyr#23702]
On arm (and possible others arch with custom swap to main) the main stack is not randomized, because `arch_switch_to_main_thread()` is called with `K_THREAD_STACK_SIZEOF(z_main_stack)` in switch_to_main_thread(), completely ignoring the value that was previous randomized in `z_setup_new_thread()`. The problem is that this value is not available anymore, except if it is build with `CONFIG_THREAD_STACK_INFO`

**Comment by ceolin** [comment]
Possible solutions:

1) Make `STACK_POINTER_RANDOM` depends on `CONFIG_THREAD_STACK_INFO` for this platform.
2) change `z_setup_new_thread` to return this info
3) randomize stack before call `zetup_new_thread` -> the worst probably
4) Add stack size to  `k_thread` independently of `CONFIG_THREAD_STACK_INFO`

Other possibilities ? Thoughts ?

**Comment by ceolin** [comment]
@andrewboie @andyross @ioannisg

**Comment by ioannisg** [comment]
(1) and (2) seem OK to me, (4) as well, if we don't care about the extra bytes...
Didn't take a detailed look yet, though

**Comment by stephanosio** [comment]
I haven't followed this up closely; but at first glance, this seems to be being addressed in #24714, is that correct? @ceolin @andrewboie

**Comment by andrewboie** [comment]
@stephanosio yes correct, I incorporated @ceolin's idea into my series.

My large stack overhaul PR is not landing until 2.4, so if we strongly desire a fix for 2.3 just use @ceolin's PR that he closed and I'll rebase on it later

**Comment by ioannisg** [comment]
> @stephanosio yes correct, I incorporated @ceolin's idea into my series.
> 
> My large stack overhaul PR is not landing until 2.4, so if we strongly desire a fix for 2.3 just use @ceolin's PR that he closed and I'll rebase on it later

That's fine with me.

**Comment by ioannisg** [comment]
@andrewboie pls, clarify if this issue can be consider closed after we merged #24714

**Comment by andrewboie** [comment]
yeah this shouldn't be a problem anymore.
