### ISSUE TITLE
CMake integration with libmetal errors-out with the bleeding edge CMake release

### ISSUE THREAD

**Issue by SebastianBoe** [zephyrproject-rtos/zephyr#23713]
**Describe the bug**
Building a libmetal application with the newly released CMake version 3.17.0 will trigger a build error.

**To Reproduce**
1. cmake -DBOARD=nrf5340_dk_nrf5340_cpuapp -Hzephyr/samples/bluetooth/peripheral_hr -Boe && ninja -C oe
4. See error:

`ninja: error: 'cmake_object_order_depends_target_metal_', needed by 'cmake_object_order_depends_target_zephyr_final_', missing and no known rule to make it
`

**Impact**
Users must not use the latest CMake version if they are to use libmetal.

Does not affect 3.16.x.

**Comment by SebastianBoe** [comment]
This is likely due to CMake behaving slightly differently in CMake 3.17.x and us not having adjusted our build scripts to this new behaviour yet.

It appears to have something to do with how CMAKE_BUILD_TYPE is manipulated by the libmetal build scripts.

**Comment by SebastianBoe** [comment]
I have a fix now, will push soon.

**Comment by tejlmand** [comment]
Has been fixed on a later upmerge of open-amp
