### ISSUE TITLE
Getting started with zephyr OS

### ISSUE THREAD

**Issue by adriantoro26** [zephyrproject-rtos/zephyr#23718]
Hello community,

I am having troubles getting started with zephyr OS. I followed **nRF v3.0.0 - Getting Started Assistant** in order to download **nRF Connect SDK tag release v1.1.0**  which includes zephyr version 2.0.99. I am not able to build the code for my ESP32 (which is a supported board), even though I followed these [steps](https://docs.zephyrproject.org/latest/boards/xtensa/esp32/doc/index.html), the same goes for qemu_x86. However, I do can build for any Nordic board. Is it that there are some bugs inside the zephyr supported board libraries which nordic uses?. Below there are some attachments containing the console outputs.
[qemu_x86_issue.txt](https://github.com/zephyrproject-rtos/zephyr/files/4375715/qemu_x86_issue.txt)
[esp32_issue_2.txt](https://github.com/zephyrproject-rtos/zephyr/files/4375716/esp32_issue_2.txt)
[esp32_issue.txt](https://github.com/zephyrproject-rtos/zephyr/files/4375717/esp32_issue.txt)
![Screenshot from 2020-03-24 10-15-55](https://user-images.githubusercontent.com/61877673/77435364-98038900-6db8-11ea-95bc-c5dbe1c0a639.png)

**Comment by carlescufi** [comment]
@adriantoro26 this is an nRF Connect SDK question, and this is not the right forum for it. Please ask the question in the [Nordic devzone](https://devzone.nordicsemi.com/) instead.
