### ISSUE TITLE
hifive1_revb fails to work with samples/subsys/console/getline

### ISSUE THREAD

**Issue by pabigot** [zephyrproject-rtos/zephyr#23729]
On startup the application goes dark (no console output).  Appears to be related to `console_getline_init()` turning off transmit interrupts.  Instrumentation indicates things are actually running but no output.

**Comment by jenmwms** [comment]
Can you please briefly describe the instrumentation used to observe that things are running despite no output? Thanks!

**Comment by pabigot** [comment]
I'd hacked things and ran it under gdb, but at this time I can't reproduce the results.

**Comment by pabigot** [comment]
By which I mean: it goes dark, and the debugger doesn't confirm that it even gets into main, though adding an LED shows it's getting in there somewhere.  Looks almost like an interrupt is getting signalled and never cleared.
