### ISSUE TITLE
k_poll() documentation is wrong or unclear

### ISSUE THREAD

**Issue by baw-serafin** [zephyrproject-rtos/zephyr#23775]
**Describe the bug**
The `events` argument to `k_poll` is documented wrong or at least misleading.
It states: `events: An array of pointers to events to be polled for.` but the signature is `int k_poll(struct k_poll_event *events, int num_events, s32_t timeout)` so it wants an array of events no pointer to events. That's also how the examples are doing it.

[Online Docu](https://docs.zephyrproject.org/latest/reference/kernel/other/polling.html#_CPPv46k_pollP12k_poll_eventi5s32_t)

**Comment by carlescufi** [comment]
@baw-serafin would you mind sending a Pull Request?
