### ISSUE TITLE
up_squared(acrn):tests/kernel/timer/timer_api/ failed.

### ISSUE THREAD

**Issue by chen-png** [zephyrproject-rtos/zephyr#23802]
**Describe**
set up acrn on up_squared board and run zephyr tests.

**To Reproduce**
1. sanitycheck -p acrn --device-testing --device-serial /dev/ttyUSB1 
    -T tests/kernel/timer/timer_api/  -west-flash="acrn_up2.sh"
2. See error

**Screenshots or console output**

*** Booting Zephyr OS build zephyr-v2.2.0-622-ge27cf1576338  ***
Running test suite timer_api

starting test - test_time_conversions
PASS - test_time_conversions

starting test - test_timer_duration_period
**ASSERTION FAIL [z_spin_lock_valid(l)] @ WEST_TOPDIR/zephyr/include/spinlock.h:74**
Recursive spinlock 0x00000000001088e0
E: RAX: 0x0000000000000004 RBX: 0x0000000000000046 RCX: 0x00000000000003f8 RDX: 0x00000000000003f8
E: RSI: 0x000000000000004a RDI: 0x000000000010680e RBP: 0x000000000000000a RSP: 0x0000000000109c88
E:  R8: 0x0000000000000006  R9: 0x0000000000000000 R10: 0x0000000000000000 R11: 0x0000000000000000
E: R12: 0x0000000000000206 R13: 0x0000000000000000 R14: 0x0000000000000000 R15: 0x0000000000000000
E: RSP: 0x0000000000109c88 RFLAGS: 0x0000000000000006 CS: 0x0018 CR3: 0x000000000000b000
E: RIP: 0x00000000001018af
**E: >>> ZEPHYR FATAL ERROR 4: Kernel panic on CPU 0
E: Current thread: 0x0000000000107e60 (unknown)
E: Halting system**

**Environment (please complete the following information):**
 - OS: fedora28
 - Toolchain : zephyr-sdk-0.11.1
 - Commit ID: e27cf157633

**Comment by tbursztyka** [comment]
Still a valid issue
