### ISSUE TITLE
Question: Is there any example for BR/EDR profile/protocols (like A2DP, AVDTP, RFCOMM)?

### ISSUE THREAD

**Issue by lylezhu2014** [zephyrproject-rtos/zephyr#23949]
There is a sample bluetooth/handsfree for HFP. Whether is there any example for A2DP, AVDTP?

**Comment by carlescufi** [comment]
> There is a sample bluetooth/handsfree for HFP. Whether is there any example for A2DP, AVDTP?

No, there isn't one right now. We are working on LE Audio and that is our main focus, so not much effort has been put into BR/EDR at all.

**Comment by lylezhu2014** [comment]
Thanks.
