### ISSUE TITLE
soc: arm: atmel: sam4e: Enable FPU

### ISSUE THREAD

**Issue by nandojve** [zephyrproject-rtos/zephyr#23947]
**Is your enhancement proposal related to a problem? Please describe.**
Enable FPU support

**Additional context**
Atmel SAM4E have a Cortex-M4F FPU that implements the FPv4-SP floating-point extension.
The FPU fully supports single-precision add, subtract, multiply, divide, multiply and accumulate, and square root operations. It also provides conversions between fixed-point and floating-point data formats, and floating-point constant instructions.
The FPU provides floating-point computation functionality that is compliant with the ANSI/IEEE Std 754-2008, IEEE Standard for Binary Floating-Point Arithmetic, referred to as the IEEE 754 standard.
The FPU contains 32 single-precision extension registers, which can also be accessed as 16 doubleword registers for load, store, and move operations.

**Comment by stephanosio** [comment]
REMINDER: Make sure we do this after #23904 is merged.
