### ISSUE TITLE
west flash don't flash right signed file when system build both hex and bin files

### ISSUE THREAD

**Issue by nandojve** [zephyrproject-rtos/zephyr#23945]
**Describe the bug**
The **west flash --bin-file build/zephyr/zephyr-\<signed\>.bin** command flash wrong file when system have a **zephyr.hex** file.

**To Reproduce**
1. checkout zephyr master
2. add **CONFIG_BOOTLOADER_MCUBOOT=y** on **prj.conf** file from **hello_world** app 
3. run **west build -b sam_v71_xult samples/hello_world**
4. sign binary file **~/\<zephyr home\>/bootloader/mcuboot/scripts/imgtool.py sign --key ~/\<zephyr home\>/bootloader/mcuboot/root-rsa-2048.pem --header-size 0x200 --align 8 --version 1.0.0 --slot-size 0xE0000 \<zephyr home\>/zephyr/build/zephyr/zephyr.bin \<zephyr home\>/zephyr/build/zephyr/zephyr-1.0.0.bin**
5. run **west --verbose flash --bin-file build/zephyr/zephyr-1.0.0.bin**
6. check screen logs searching for **-- runners.openocd: Flashing file: /home/gfbudke/zephyros/mainline/zephyr/build/zephyr/zephyr.hex**

**Expected behavior**
The **west flash --bin-file ...** working as expected.

**Impact**
annoyance

**Screenshots or console output**
```
ZEPHYR_BASE=/home/gfbudke/zephyros/mainline/zephyr (origin: env)
-- west flash: rebuilding
cmake version 3.13.4 is OK; minimum version is 3.13.1
Running CMake: /usr/bin/cmake --build /home/gfbudke/zephyros/mainline/zephyr/build
ninja: no work to do.
-- west flash: using runner openocd
-- runners.openocd: Flashing file: /home/gfbudke/zephyros/mainline/zephyr/build/zephyr/zephyr.hex
runners.openocd: /home/gfbudke/zephyr-sdk-0.11.2/sysroots/x86_64-pokysdk-linux/usr/bin/openocd -s /home/gfbudke/zephyros/mainline/zephyr/boards/arm/sam_v71_xult/support -s /home/gfbudke/zephyr-sdk-0.11.2/sysroots/x86_64-pokysdk-linux/usr/share/openocd/scripts -f /home/gfbudke/zephyros/mainline/zephyr/boards/arm/sam_v71_xult/support/openocd.cfg -c init -c targets -c 'reset halt' -c 'flash write_image erase /home/gfbudke/zephyros/mainline/zephyr/build/zephyr/zephyr.hex' -c 'reset halt' -c 'verify_image /home/gfbudke/zephyros/mainline/zephyr/build/zephyr/zephyr.hex' -c 'atsamv gpnvm set 1' -c 'reset run' -c shutdown
Open On-Chip Debugger 0.10.0+dev-01340-ga0e8edc4e-dirty (2020-02-14-05:38)
Licensed under GNU GPL v2
For bug reports, read
	http://openocd.org/doc/doxygen/bugs.html
Info : flash bank command
Info : CMSIS-DAP: SWD  Supported
Info : CMSIS-DAP: FW Version = 03.25.01B6
Info : CMSIS-DAP: Serial# = ATML2407060200000551
Info : CMSIS-DAP: Interface Initialised (SWD)
Info : SWCLK/TCK = 1 SWDIO/TMS = 1 TDI = 1 TDO = 1 nTRST = 0 nRESET = 1
Info : CMSIS-DAP: Interface ready
Info : clock speed 1800 kHz
Info : SWD DPIDR 0x0bd11477
Warn : Silicon bug: single stepping may enter pending exception handler!
Info : atsamv71q21.cpu: hardware has 8 breakpoints, 4 watchpoints
Info : atsamv71q21.cpu: external reset detected
Info : Listening on port 3333 for gdb connections
    TargetName         Type       Endian TapName            State       
--  ------------------ ---------- ------ ------------------ ------------
 0* atsamv71q21.cpu    cortex_m   little atsamv71q21.cpu    running

target halted due to debug-request, current mode: Thread 
xPSR: 0x01000000 pc: 0x00402c14 msp: 0x204056f8
Info : device id = 0xa1220e00
Info : erasing lock regions 8-8...
Info : erasing lock region 8
auto erase enabled
wrote 16384 bytes from file /home/gfbudke/zephyros/mainline/zephyr/build/zephyr/zephyr.hex in 0.343439s (46.588 KiB/s)

target halted due to debug-request, current mode: Thread 
xPSR: 0x01000000 pc: 0x00402c14 msp: 0x204056f8
verified 9160 bytes in 0.298013s (30.017 KiB/s)

shutdown command invoked
```
**Environment (please complete the following information):**
 - OS: Debian Buster
 - Zephyr SDK 0.11.2
 - 3501766231827ab986379a2d84c763ab3a8220fb

**Additional context**
The **west flash --hex-file build/zephyr/zephyr-\<signed\>.hex** works fine.

**Comment by mbolivar-nordic** [comment]
This is working as documented:

> The availability of a hex file, and whether west flash uses it to flash, depends on your board and build configuration. At least the west flash runners using nrfjprog and pyocd work with the above flow.

https://docs.zephyrproject.org/latest/guides/west/sign.html

There are no guarantees about which file is used by the underlying runner.

Fixing this to use a single `--file` argument that the runner should always respect is a longstanding wishlist item. I left a comment on this pull request describing the work that would need to be done to make this happen: https://github.com/zephyrproject-rtos/zephyr/pull/18159

Help is wanted. Thanks.
