### ISSUE TITLE
Question: How is pdata.tsize initialized in zephyr/subsys/usb/usb_transfer.c?

### ISSUE THREAD

**Issue by tluio** [zephyrproject-rtos/zephyr#23953]
In function usb_transfer_sync, pdata.tsize is returned. I wonder how it is initialized. Is it initialized through DMA?

**Comment by jfischer-phytec-iot** [comment]
For `usb_transfer_sync()`, which blocks until finished, pointer to the pdata is `cb_data` and `pdata.tsize` will be assigned in the callback of [usb_transfer()](https://github.com/zephyrproject-rtos/zephyr/blob/master/subsys/usb/usb_transfer.c#L296).

**Comment by tluio** [comment]
Thank you very much! Would you please tell me how usb_transfer_sync() blocks.

**Comment by emob-nordic** [comment]
There is semaphore which is [taken](https://github.com/zephyrproject-rtos/zephyr/blob/master/subsys/usb/usb_transfer.c#L317) and later [released](https://github.com/zephyrproject-rtos/zephyr/blob/master/subsys/usb/usb_transfer.c#L301).

**Comment by tluio** [comment]
@emob-nordic Thank you! Now I think I should close this issue.
