### ISSUE TITLE
Switching among different PHY Modes

### ISSUE THREAD

**Issue by BOZHENG001** [zephyrproject-rtos/zephyr#23989]
**Is your enhancement proposal related to a problem? Please describe.**
I am working with nRF52840 DK using Zephyr 2.0, and now i would like to see the difference among different PHY Modes. In BLE stack, there are totally 4 PHY Modes, which are LE 1M PHY, LE 2M PHY, Coded PHY (S2) and Coded PHY (S8). 

I saw some configuration choices like `CONFIG_BT_CTLR_PHY_2M` and `CONFIG_BT_CTLR_PHY_CODED`. I suppose if I would like to enable LE 2M PHY, I could easily use `CONFIG_BT_CTLR_PHY_2M=y`, and set `CONFIG_BT_CTLR_PHY_2M=n` to use LE 1M PHY. But how could I know which Coded PHY am I using, if I only enable Coded PHY by `CONFIG_BT_CTLR_PHY_CODED=y`? S2 or S8? Or maybe I still need to do some other configurations?

**Additional context**
Add any other context or graphics (drag-and-drop an image) about the feature request here.

**Comment by carlescufi** [comment]
@BOZHENG001 I think it makes sense to be able to configure this from the application's perspective. Let us hear from others to see how we can add this functionality.

**Comment by joerchan** [comment]
Makes sense. I have had similar requests already and have a branch ready. I can submit a PR soon.
