### ISSUE TITLE
Possible use of uninitialized variable in subsys/net/ip/utils.c

### ISSUE THREAD

**Issue by tluio** [zephyrproject-rtos/zephyr#23986]
File: subsys/net/ip/utils.c
Function: z_impl_net_addr_ntop
If **family == AF_INET**, **w** declared on line 150 is not initialized but it may be used on line 236.

**Comment by jukkar** [comment]
I think you have a false positive here. If the family is AF_INET (then len = 4), the code only loop in IPv4 branch between lines 198 - 216 and never gets to line 236.
