### ISSUE TITLE
flash sector erase fails on stm32l475

### ISSUE THREAD

**Issue by mtahirbutt** [zephyrproject-rtos/zephyr#23997]
**Describe the bug**

 I am facing a similary problem with my disco_l475_iot1 board which has stm32l475 MCU. I am using mcuboot for updatehub app. I am not able to erase flash memory partition.

What have you tried to diagnose or workaround this issue?

flash_write_protection_set() works fine but flash_erase() inside mcuboot.c is not successful.
 I checked carefully all the partition sizes they are perfectly according to DTS file. Now I tried to see OPTCR register but could not find it.
Additionally I tried flash_shell app from zephyr to see if the erase is successful. but it also generated the problem with error code -5.

**To Reproduce**
1. mkdir build; cd build
2. cmake -DBOARD=disco_l475_iot1
3. make

**Expected behavior**

I should see successful erase and the method flash_erase should return 0 on successful return.

**Impact**
What impact does this issue have on your progress (e.g., annoyance, showstopper)

I am working with updatehub app but not able to achieve that because of this error.

**Screenshots or console output**
If applicable, add a screenshot (drag-and-drop an image), or console logs
(cut-and-paste text and put a code fence (\`\`\`) before and after, to help
explain the issue.

**Environment (please complete the following information):**
 - OS: (e.g. Linux,)
 - Toolchain (e.g Zephyr 2.2.99, SDK,0.11.2.)
 - commit- 1c79096559f5b95f7153cd6784459734c8bb76b9

**Additional context**

**Comment by nandojve** [comment]
It may be related to #18263

**Comment by erwango** [comment]
^^@ABOSTM

**Comment by mtahirbutt** [comment]
Hi @erwango, I tried with zephyr 2.2.0, there I tried flash page_erase 200 and that worked. so I am switching to zephyr 2.2.0 and will now try updatehub app.

**Comment by erwango** [comment]
@mtahirbutt out of curiosity, on which release did you face the issue ?

**Comment by otavio** [comment]
@mtahirbutt to be sure, this works on 2.2 and fails on master, right?
