### ISSUE TITLE
Bluetooth: Mesh: Friend node not cache ALL_Node Address or different app_idx

### ISSUE THREAD

**Issue by LingaoMeng** [zephyrproject-rtos/zephyr#24009]
Set up there nodes, call publish node, friend node ,lpn node.

All node share single network key, but friend & lpn node with different application key, 
the lpn node has same application key will publish node.

when publish node periodic send model message with the dst = 0xffff, lpn node not receive all of them.

**Comment by LingaoMeng** [comment]
https://github.com/zephyrproject-rtos/zephyr/blob/c98652b42f12f07736259788ba067d8987387cb9/subsys/bluetooth/mesh/transport.c#L905-L914 and sdu_recv_seg

should be change as return 0 ?

**Comment by LingaoMeng** [comment]
https://github.com/zephyrproject-rtos/zephyr/blob/c98652b42f12f07736259788ba067d8987387cb9/subsys/bluetooth/mesh/friend.c#L1387-L1411 should add judgement for ALL_NODE_ADDRESS ?

**Comment by jhedberg** [comment]
I remember seeing some discussion in the Mesh WG about this, with the conclusion that LPNs need to explicitly subscribe to these addresses, so based on that it's not a bug. @trond-snekvik can you confirm?

**Comment by trond-snekvik** [comment]
I remember this too, according to spec, the LPN has to explicitly subscribe to 0xffff. There's no public API for doing this in zephyr though, as it's controlled by the config server, which won't accept 0xffff. Perhaps it could be compile time option to automatically subscribe to 0xffff when the friendship is established?

**Comment by LingaoMeng** [comment]
well, it's still another problem, friend node has different `appkey `with lpn node , but currently call `sud_recv` return `-EINVAL` when local node unable find `appkey`,
so, even the friend node known its dst is lpn node,  and not store this to friend queue.

**Comment by jhedberg** [comment]
@LingaoMeng let's not mix multiple issues into a single GitHub issue. Open a new one since I already categorised this based on the 0xffff address concern.
