### ISSUE TITLE
Bluetooth: Mesh: Friend node not cache for lpn which receiveing unknown app_idx

### ISSUE THREAD

**Issue by Kupeo** [zephyrproject-rtos/zephyr#24014]
When friend node use a different application key with lpn node, the friend not cache them.
But, the spec not limited for this.

**Comment by LingaoMeng** [comment]
@jhedberg

**Comment by jhedberg** [comment]
@LingaoMeng could you provide the additional details (like a quote of the code) as you did in the original issue?

**Comment by LingaoMeng** [comment]
https://github.com/zephyrproject-rtos/zephyr/blob/7ab754d9973e7b7481658bd937e186362f603f70/subsys/bluetooth/mesh/transport.c#L1765-L1801

https://github.com/zephyrproject-rtos/zephyr/blob/7ab754d9973e7b7481658bd937e186362f603f70/subsys/bluetooth/mesh/transport.c#L909-L913
