### ISSUE TITLE
double to sensor_val

### ISSUE THREAD

**Issue by GeorgeGkinis** [zephyrproject-rtos/zephyr#24051]
**Is your feature request related to a problem? Please describe.**

I want to convert a double to sensor_val

**Describe the solution you'd like**
I would like a function **double_to_sensor_value** the way **sensor_value_to_double** exists.

**Describe alternatives you've considered**
Googled allot.

**Additional context**
None.

**Comment by JonBruchim** [comment]
would like to get assigned to this issue

**Comment by saltyJeff** [comment]
Any progress made on this? I'm currently using this function as an inline: https://repl.it/@JeffersonLee/zephyr-double-to-sensor-val#main.c

I included the test cases from: https://docs.zephyrproject.org/latest/reference/peripherals/sensor.html#c.sensor_value

**Comment by henrikbrixandersen** [comment]
A helper function `sensor_value_from_double(struct sensor_value *, double)` was added in commit 3c36cd4242ae94971ebe4d6dfcc6ade6ea9a6cb8.

Closing.
