### ISSUE TITLE
cross-platform inconsistency in I2C bus speeds

### ISSUE THREAD

**Issue by pabigot** [zephyrproject-rtos/zephyr#24067]
The [I2C bus specification](http://cache.nxp.com/documents/user_manual/UM10204.pdf) in section 5 specifies these named speeds:

* Standard up to 100 kHz
* Fast up to 400 kHz
* Fast+ up to 1 MHz
* High up to 3.4 MHz
* Ultra up to 5 MHz (unidirectional only)

Evaluation in https://github.com/zephyrproject-rtos/zephyr/pull/23971#pullrequestreview-387200780 plus code review show that NXP (mcux, mcux_lpi2c, imx) and SiLabs (gecko) I2C drivers use 1 MHz for Fast, and do not implement Fast+.

The interpretation of named I2C bus speeds in Zephyr should be (a) documented and (b) consistent.

**Comment by carlescufi** [comment]
@mnkp and @MaureenHelm could you send a patch to correct Fast so it becomes Fast+?

**Comment by MaureenHelm** [comment]
> @mnkp and @MaureenHelm could you send a patch to correct Fast so it becomes Fast+?

yes
