### ISSUE TITLE
UART driver for sifive does not compile when configuring PORT_1

### ISSUE THREAD

**Issue by matanix** [zephyrproject-rtos/zephyr#24068]
**Describe the bug**
I am working with zephyr and hifive revb board. Tried to configure UART port 1 in order to use it for communication while keeping UART port 0 for console output. It does not compile either for qemu or the actual board.

**To Reproduce**
1. mkdir build; cd build
2. cmake -DBOARD=qemu_riscv32 or -DBOARD=hifive1_revb
3. configure zephyr/.config CONFIG_UART_SIFIVE_PORT_1=y
4. make
5. see error

**Expected behavior**
I believe zephyr should compile with this configuration in order to allow UART_PORT1 for QEMU or hifive revb board. According to the documentation, only UART_SIFIVE && SERIAL are the dependency configurations required and they are configured in my workspace.

**Impact**
Cannot work with uart port 1.

**Screenshots or console output**
/home/matan/workspace/zephyr/drivers/serial/uart_sifive.c:425:10: error: 'DT_N_INST_1_sifive_uart0_REG_IDX_0_VAL_ADDRESS' undeclared here (not in a function)
  425 |  .port         = DT_INST_REG_ADDR(1),
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~                  
/home/matan/workspace/zephyr/drivers/serial/uart_sifive.c:426:18: error: 'DT_N_INST_1_sifive_uart0_P_clock_frequency' undeclared here (not in a function)
  426 |  .sys_clk_freq = DT_INST_PROP(1, clock_frequency),
      |                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~         
/home/matan/workspace/zephyr/drivers/serial/uart_sifive.c:427:15: error: 'DT_N_INST_1_sifive_uart0_P_current_speed' undeclared here (not in a function)
  427 |  .baud_rate    = DT_INST_PROP(1, current_speed),
      |               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~      
/home/matan/workspace/zephyr/drivers/serial/uart_sifive.c:435:144: error: 'DT_N_INST_1_sifive_uart0_P_label' undeclared here (not in a function)
  435 | DEVICE_AND_API_INIT(uart_sifive_1, DT_INST_PROP(1, label),
      |                                                                                                                                                ^                               
zephyr/drivers/serial/CMakeFiles/drivers__serial.dir/build.make:79: recipe for target 'zephyr/drivers/serial/CMakeFiles/drivers__serial.dir/uart_sifive.c.obj' failed
make[2]: *** [zephyr/drivers/serial/CMakeFiles/drivers__serial.dir/uart_sifive.c.obj] Error 1
CMakeFiles/Makefile2:1681: recipe for target 'zephyr/drivers/serial/CMakeFiles/drivers__serial.dir/all' failed
make[1]: *** [zephyr/drivers/serial/CMakeFiles/drivers__serial.dir/all] Error 2
Makefile:100: recipe for target 'all' failed
make: *** [all] Error 2

**Environment (please complete the following information):**
 - OS: Ubuntu 16.04
 - Toolchain official zephyr sdk installed using zephyr-sdk-0.11.2-setup.run
 - Zephyr commit is 2e879fae4841b28c5ccb0fef4951fb1fa6efb359 from master branch.

**Comment by carlescufi** [comment]
The UART1 is not initialized, use this to fix it:

```
diff --git a/boards/riscv/qemu_riscv32/qemu_riscv32.dts b/boards/riscv/qemu_riscv32/qemu_riscv32.dts
index 75b97b89c9..61f780fa18 100644
--- a/boards/riscv/qemu_riscv32/qemu_riscv32.dts
+++ b/boards/riscv/qemu_riscv32/qemu_riscv32.dts
@@ -28,6 +28,8 @@
 };

 &uart1 {
+       status = "okay";
+       current-speed = <115200>;
        clock-frequency = <16000000>;
 };
```
