### ISSUE TITLE
Question: Context save/restore after deep sleep using device driver

### ISSUE THREAD

**Issue by tektronix-94** [zephyrproject-rtos/zephyr#24133]
Hello,

I'm having some issues related to power management and context restore after sleep using BlueNRG SOC with Cortex M0.

According to documentation context should be restored in `_sys_resume_from_deep_sleep()` function but this function is not supported on Cortex M0.
So, I tried to add device driver context restore in the Reset Vector handler. Unfortunately it does not work properly.

After wake up from deep sleep the application is resumed from the point where the system entered the deep sleep state. However, all the threads are stopped and k_sleep() does not work.

Where `_sys_resume_from_deep_sleep()` should be called for context restore on Cortex M0 architecture ?

How to save/restore stack of threads?

**Comment by tektronix-94** [comment]
area: Power Management

**Comment by pabigot** [comment]
I wouldn't expect the application to restart from deep sleep at the point where it called it.  It's generally expected to be equivalent to a system reset, potentially with some flags set somewhere system-/application-specific to indicate that a wake has occurred.

AFAIK there is no in-tree support for recovering state from deep sleep on any platform, though there's a non-functional stub that allows applications to link to it.  Only ARC and X86 seem to have boot-time paths that might cause it to be invoked automatically.

**Comment by carlescufi** [comment]
@tektronix-94 I think the question is answered, though the functionality you want is not implemented yet. Could you close this if you agree?

**Comment by tektronix-94** [comment]
> 
> 
> @tektronix-94 I think the question is answered, though the functionality you want is not implemented yet. Could you close this if you agree?

Sure.
