### ISSUE TITLE
deadlock potential in nrf_qspi_nor

### ISSUE THREAD

**Issue by pabigot** [zephyrproject-rtos/zephyr#24144]
As pointed out [here](https://github.com/zephyrproject-rtos/zephyr/pull/24128#issuecomment-610235114) by @ball-hayden the QSPI driver for Nordic persistently invokes an operation but blocks for release of a semaphore whether or not the operation failed.  At least some error codes may indicate that the operation was never initiated, which would produce a deadlock in that case, as demonstrated in #24122.

**Comment by carlescufi** [comment]
@kamlaz could you provide a fix?

**Comment by kamlaz** [comment]
> @kamlaz could you provide a fix?

Yes, I will handle this.

**Comment by pabigot** [comment]
I lost a couple hours due to running into this when updating the USB mass storage to support mounting a littlefs file system, so there's now a fix.  Many things that use wrappers to the SPI flash API are likely to fail to supply an aligned memory buffer and will produce a deadlock that is very hard to diagnose, so I've increased this to medium priority.
