### ISSUE TITLE
nrf5340 pdk: BOARDS_ENABLE_CPUNET does not allow proper NET MCU configuration

### ISSUE THREAD

**Issue by ioannisg** [zephyrproject-rtos/zephyr#24147]
**Describe the bug**
A recently introduced Kconfig option, BOARDS_ENABLE_CPUNET controls whether remoteproc_mgr_boot() is called from nrf5340 Application MCU booting process.

remoteproc_mgr_boot() should be ideally called only once, and by the image that resets the nrf5340 NETWORK MCU. So BOARDS_ENABLE_CPUNET should be set by the  image that cooperates with the NETWORK MCU. If this is a Non-Secure image, then parts of the configuration done in remoteproc_mgr_config() are never executed, and this is a problem.

If, instead, we allow BOARDS_ENABLE_CPUNET to be enabled from both Secure and Non-Secure Application MCU images, then the RESET of NET MCU is occurring twice, which is very confusing.

We also do not deal with (extreme) corner cases when the image responsible to reset the NET MCU does not own the shared memory.

**Expected behavior**
We need to make sure remoteproc_mgr_boot does not contain dead code.
We should really re-organize the code in the respective module, to ensure that all parts of the code are executed by the intended images.

**Comment by carlescufi** [comment]
@ioannisg is this really a bug? what priority should it have?

**Comment by ioannisg** [comment]
confirmed, so I re-open
