### ISSUE TITLE
NRF5340 PA/LNA support

### ISSUE THREAD

**Issue by binkboyd** [zephyrproject-rtos/zephyr#24142]
**Describe the bug**
When enabling PA/LNA pin control the build fails with what appears to be both GPIO and PPID related errors. It doesn't look like the NRF53 PA/LNA code is implemented yet.

**To Reproduce**
1) 
add following to hci_rpmsg sample prj.conf, using the 
CONFIG_BT_CTLR=y
CONFIG_BT_CTLR_GPIO_PA=y
CONFIG_BT_CTLR_GPIO_PA_PIN=29
CONFIG_BT_CTLR_GPIO_LNA=y
CONFIG_BT_CTLR_GPIO_LNA_PIN=24

2)
west build samples/bluetooth/hci_rpmsg -b nrf5340_dk_nrf5340_cpunet
3)
Fails with lots of error, but seems to be both GPIO and ppi related:
...error: 'NRF_GPIO' undeclared (first use in this function); did you mean 'NRF_GPIOTE'?
 #define NRF_GPIO_PA     NRF_GPIO

...warning: implicit declaration of function 'hal_enable_palna_ppi_config'; did you mean 'hal_trigger_aar_ppi_config'? [-Wimplicit-function-declaration]

...error: 'HAL_ENABLE_PALNA_PPI' undeclared 

**Expected behavior**
Expected the sample to build and PA/LNA control to work.

**Impact**
My board is not useable as I have an external amplifier which cannot be controlled by the NRF5340.

**Environment (please complete the following information):**
- Latest NCS, so not up to date zephyr - but the affected file (radio.c) is the same as in latest zephyr master (7ba5e012f7f2e380b360df84f3a345fdec9cc234)

**Comment by carlescufi** [comment]
@anangl would you please take a look at this? It's a matter of porting the PPI to DPPI

**Comment by ioannisg** [comment]
Is this really a bug @carlescufi ? PA/LNA support has not been ported yet to nRF5340, so AFAIU, it has never worked, so the ticket should be labeled as feature/enhancement

**Comment by carlescufi** [comment]
Yep, agreed @ioannisg. Let's relabel this as hardware support

**Comment by SloMusti** [comment]
I have the same issue and would like to use this functionality.

**Comment by cvinayak** [comment]
@binkboyd and @SloMusti 

Please try using #30950  and leave your comments here or in the PR.

Add the following to your application core MCU program, to permit the GPIO to be controlled by network core MCU.
```
	NRF_P0->PIN_CNF[29] =
		GPIO_PIN_CNF_MCUSEL_NetworkMCU << GPIO_PIN_CNF_MCUSEL_Pos;
	NRF_P0->PIN_CNF[24] =
		GPIO_PIN_CNF_MCUSEL_NetworkMCU << GPIO_PIN_CNF_MCUSEL_Pos;
```
