### ISSUE TITLE
CI: extra_args from sanitycheck *.yaml do not propogate to cmake

### ISSUE THREAD

**Issue by finikorg** [zephyrproject-rtos/zephyr#24178]
extra_args from *.yaml do not go to the build system.

**Reproduce**
extra_args: "-DDEBUG_PRINTF=1" from samples/philosophers/sample.yaml is lost.
```
$ sanitycheck -c -M -p native_posix --test samples/philosophers/sample.kernel.philosopher
```

Output:
```
...
CMake Warning:
  Manually-specified variables were not used by the project:

    -DDEBUG_PRINTF
...
```

and

```
DEBUG   - Calling cmake with arguments: ['-B/home/niko/work/zephyrproject/sanity-out/native_posix/samples/philosophers/sample.kernel.philosopher', '-S/home/niko/work/zephyrproject/zephyr/samples/philosophers', '-DEXTRA_CFLAGS="-Werror ', '-DEXTRA_AFLAGS=-Wa,--fatal-warnings', '-DEXTRA_LDFLAGS="-Wl,--fatal-warnings', '-GUnix Makefiles', '-D-DDEBUG_PRINTF=1', '-DBOARD=native_posix']
```

**Comment by mbolivar-nordic** [comment]
I don't think I'm the right assignee.

**Comment by nashif** [comment]
so, this is not an issue in sanitycheck or west.. The fact that cmake reports about the variable means it was passed correctly to the sample.
Looks like cmake has no idea what to with this and some additional handling is needed in the cmake file, fixed for this sample. If we do not want this to go through cmake then i think we should add

```
-DEXTRA_CFLAGS="-DDEBUG_PRINTF=1"
```
instead, not sure yet.

**Comment by finikorg** [comment]
We can keep this bug to handle also other parameters in extra_args.
