### ISSUE TITLE
[v2.2] Bluetooth: controller: split: Regression slave latency during connection update

### ISSUE THREAD

**Issue by cvinayak** [zephyrproject-rtos/zephyr#24183]
**Describe the bug**
Slave latency should not be applied between the ack of a
Connection Update Indication PDU and until the instant.
When caching was introduced in split controller, implementation missed this
consideration which caused connection events to be skipped, being in slave latency.

**To Reproduce**
You will need logic analyser to observe the GPIO toggles of BLE controller radio events.

Steps to reproduce the behavior in peripheral, building:
1. mkdir build; cd build
2. cmake -GNinja -DBOARD=nrf52_pca10040 -DCONFIG_BT_CTLR_DEBUG_PINS=y ../samples/bluetooth/peripheral
3. ninja

Building of central (test shell) for testing:
1. mkdir build; cd build
2. cmake -GNinja -DBOARD=nrf52_pca10040 ../tests/bluetooth/shell
3. ninja

Steps:
1. `bt init`
2. `bt scan on`
3. Use the discovered Bluetooth address of the peripheral
4. `bt connect <address>`
5. wait until auto connection update completes
6. `bt conn-update 6 6 9 64`
7. `bt conn-update 28 28 0 64`

Observe in the logic trace that connection events before the switch to 50 ms interval does not show cancelled slave latency during the time between the connection update procedure intiation to the connection update instant.

**Expected behavior**
Slave latency should not be applied between the ack of a
Connection Update Indication PDU and until the instant.

**Impact**
BT Specification violation.

**Screenshots or console output**
If applicable, add a screenshot (drag-and-drop an image), or console logs
(cut-and-paste text and put a code fence (\`\`\`) before and after, to help
explain the issue.

None.

**Environment (please complete the following information):**
 - OS: (e.g. Linux, MacOS, Windows): Linux 
 - Toolchain (e.g Zephyr SDK, ...): Zephyr SDK
 - Commit SHA or Version used: 79942b47cc

**Additional context**

This is fixed in bc357718a7 for the split controller and b7e35ae4a3 for legacy controller.
Backport 2.2 PR: #23965

**Comment by wopu-ot** [comment]
Fix has been merged, no reason to keep the issue open.
