### ISSUE TITLE
Build error when using MCHP ACPI HAL macros

### ISSUE THREAD

**Issue by albertofloyd** [zephyrproject-rtos/zephyr#24241]
**Describe the bug**
Compilation error when using MCHP ACPI HAL macros i.e.
MCHP_ACPI_EC_STS_OBF

**To Reproduce**
1. mkdir build; cd build
2. cmake -DBOARD=board\mec15xx
3. make

**Expected behavior**
Need update HAL header with correct definitions

**Comment by scottwcpg** [comment]
Please see PR #9 https://github.com/zephyrproject-rtos/hal_microchip.
I keep forgetting how to add reviewers because the reviewers section is grey'd out.
