### ISSUE TITLE
 tests/subsys/storage/flash_map failed on frdm_k64f board.

### ISSUE THREAD

**Issue by chen-png** [zephyrproject-rtos/zephyr#24299]
**To Reproduce**
1.  west build -b frdm_k64f -p auto tests/subsys/storage/flash_map/ 
      -DOVERLAY_CONFIG=overlay-mpu.conf
2. west flash
3. See error

**Screenshots or console output**
*** Booting Zephyr OS build zephyr-v2.2.0-1416-g47f1665e7837  ***
Running test suite test_flash_map

starting test - test_flash_area_get_sectors
E: ***** MPU FAULT *****
E:   Instruction Access Violation
E: r0/a1:  0x00000000  r1/a2:  0x00000000  r2/a3:  0x00000046
E: r3/a4:  0x406100f4 r12/ip:  0x00000000 r14/lr:  0x00000489
E:  xpsr:  0x60000000
E: Faulting instruction address (r15/pc): 0x406100f4
E: >>> ZEPHYR FATAL ERROR 0: CPU exception on CPU 0
E: Current thread: 0x20000880 (unknown)
E: Halting system

**Environment (please complete the following information):**
 - OS: Fedora28
 - Toolchain : Zephyr-sdk-0.11.2
 - Commit ID: 47f1665e783

**Comment by MaureenHelm** [comment]
Fixed by #24247
