### ISSUE TITLE
Support for multi core STM32 H75/H77 boards

### ISSUE THREAD

**Issue by stevewells20** [zephyrproject-rtos/zephyr#24301]
Problem:
There is no support for multi core STM32 boards in the Nucleo in the H7*7 and H7*5 families; these are quite powerful and offer interesting new possibilities.

I would like to know if it would be a quick operation to implement support for these board families, as there is already support for both Cortex M7 and M4 STM32 boards. Is there a guide for doing this type of implementation?

**Comment by erwango** [comment]
Hi @stevewells20,

Adding Dual core support for these soc/boards should not be a complex task.
You first need to add device tree for the targeted SoCs.
Then provide board support based on what was done on stm32h747i_disco.

**Comment by stevewells20** [comment]
Thank you for the response! I'll look into it. Are there any resources available for best practices or examples for adding new boards? I'm new to Zephyr, and would like to get my feet wet by diving in.

**Comment by erwango** [comment]
@stevewells20, you can look at https://github.com/zephyrproject-rtos/zephyr/pull/23160 for reference.
You don't need to provide full support for the board, but a minimum needs to be added like done in this example.
From what I understand, you want to introduce new SoC, so we'll wait 2 commits:
- new SoC introduction
- board introduction

For the board configuration, dual core support is a bit specific, so you can check how it is done for this board:
https://github.com/zephyrproject-rtos/zephyr/tree/master/boards/arm/stm32h747i_disco

If you feel stuck, don't hesitate to push a draft PR and ask for help: @FRASTM or @ABOSTM

**Comment by Nukersson** [comment]
I am also working on support for NUCLEO-H745ZI
