### ISSUE TITLE
UICR & FICR missing from nRF52* devicetree files

### ISSUE THREAD

**Issue by JordanYates** [zephyrproject-rtos/zephyr#24338]
**Describe the bug**
Locations of the FICR and UICR hardware peripherals are missing from many devicetree files.

SOC's without:
- nRF52840
- nRF52833
- nRF52832
- nRF52811
- nRF52810

SOC's with:
- nRF9160
- nrf5340_cpuapp
- nrf5340_cpunet

**Expected behavior**
FICR and UICR should be present in devicetree for any SOC that has them.

**Impact**
FICR and UICR have to be manually added to board .dts files (third-party) or overlays (in-tree)

**Comment by tautologyclub** [comment]
Would be nice with a driver for reserving the slots too, I'm still not sure which ones are hijacked by the radio tbh
