### ISSUE TITLE
Application Cortex M Systick driver broken by merge of #24012

### ISSUE THREAD

**Issue by b0661** [zephyrproject-rtos/zephyr#24347]
**Describe the bug**

To get the z_clock_isr() into the vector table now requires to define CONFIG_CORTEX_M_SYSTICK, If CONFIG_CORTEX_M_SYSTICK is defined the standard Zephyr driver is added to the zephyr lib. The application driver and the Zephyr driver now are both providing the same symbols (that were defined weak just for the purpose to allow for application drivers - see history of the vector table file). 

**To Reproduce**
See above

**Expected behavior**
Allow application systick driver

**Impact**
Showstopper - application does not compile and needs a special systick driver.

**Screenshots or console output**
N/A

**Environment (please complete the following information):**
 - d280660792c288f67a4f4e31eb99c4dd4a7940ba

**Additional context**
N/A

**Comment by stephanosio** [comment]
Initial discussion at https://github.com/zephyrproject-rtos/zephyr/commit/4364f2d455c56d02e3d7284ea489f094c8835eb9
