### ISSUE TITLE
k_heap / sys_heap needs overview documentation

### ISSUE THREAD

**Issue by andrewboie** [zephyrproject-rtos/zephyr#24359]
We've introduced new heap APIs to supersede k_mem_pool / sys_mem_pool, but have no overview documentation for it, just API doxygen.

I expect this file will need to be rewritten to reflect the new API set:

`doc/reference/kernel/memory/pools.rst`

**Comment by carlescufi** [comment]
@andrewboie don't forget to update docs/releases/, section about API deprecation
