### ISSUE TITLE
Json: array of objects is not properly handled

### ISSUE THREAD

**Issue by ivangarrera** [zephyrproject-rtos/zephyr#24372]
**Describe the bug**
An array of objects like this: 
`{"t_0": [{"id": "t01","d": 20,"t": 1},{"id": "t02","d":10,"t": 1},{"id": "t03","d": 15,"t": 0},{"id": "t04","d": 50,"t": 1}], "t_1": [{"id": "t11","d":10},{"id":"t12","d":20}]}`
is not properly encoded/decoded

**To Reproduce**
The structs are:

    typedef struct {
        char *id; 
        uint32_t d; 
        uint8_t t; 
    } data_first;

    typedef struct {
        char *id; 
        uint32_t d; 
    } data_second;

    typedef struct {
        data_first t_0[4];
        size_t data_first_size;
        data_second t_1[2]; 
        size_t data_second_size;
    } message;

    const struct json_obj_descr data_first_json[] = {
        JSON_OBJ_DESCR_PRIM(data_first, id, JSON_TOK_STRING),
        JSON_OBJ_DESCR_PRIM(data_first, d, JSON_TOK_NUMBER),
        JSON_OBJ_DESCR_PRIM(data_first, t, JSON_TOK_NUMBER)
    };

    const struct json_obj_descr data_second_json[] = {
        JSON_OBJ_DESCR_PRIM(data_first, id, JSON_TOK_STRING),
        JSON_OBJ_DESCR_PRIM(data_first, d, JSON_TOK_NUMBER)
    };

    const struct json_obj_descr message_json[] = {
        JSON_OBJ_DESCR_OBJ_ARRAY(message, t_0, 4,
                                    data_first_size, data_first_json,
                                    ARRAY_SIZE(data_first_json)),
        JSON_OBJ_DESCR_OBJ_ARRAY(message, t_1, 2, 
                                    data_second_size, data_second_json,
                                    ARRAY_SIZE(data_second_json)),
    };

**Expected behavior**
For the data:

    message m= {
        .t_0[0] = {
            id = "t01",
            .d = 20,
            .t= 1
        },
        .t_0[1] = {
            .id = "t02",
            .d= 10,
            .t= 1
        },
        .t_0[2] = {
            .id = "t03",
            .d= 15,
            .t= 0
        },
        .t_0[3] = {
            .id = "t04",
            .d = 50,
            .t = 1
        },
        .data_first_size= 4,
        .t_1[0] = {
            .id = "t11",
            .d = 10
        },
        .t_1[1] = {
            .id = "t12",
            .d= 20
        },
        .data_second_size = 2
    };

the original JSON should be returned. However, I obtain:

`{"t_0":[{"id":"t01","d":20,"t":-905969664},{"id":"t03","d":50,"t":-738197504},{"id":"I\f","d":0,"t":0},{"id":"▒EXI\f","d":0,"t":0}]}`

and the same weird data with `t_1`

**Comment by pabigot** [comment]
I'm unable to reproduce this with https://gist.github.com/pabigot/f33f471cc9498f6e98c157deb5d227b2 on nrf52840dk_nrf52840 or native_posix.  The only thing in `prj.conf` is `CONFIG_JSON_LIBRARY=y`.

It does segfault if built on native_posix_64, suggesting the json library is not safe for non-32-bit platforms.

What target platform are you using, and which version of Zephyr?
