### ISSUE TITLE
nsim_sem_normal target is broken

### ISSUE THREAD

**Issue by andrewboie** [zephyrproject-rtos/zephyr#24390]
**Describe the bug**
When testing nsim_sem_normal under sanitycheck, the following result is observed:

```
Total complete:  182/ 182  100%  skipped:   37, failed:  113
```

**To Reproduce**
1. Ensure nSIM 2019.09 `nsimdrv` executable is in $PATH
2. `sanitycheck -p nsim_sem_normal`

**Expected behavior**
All tests passing.

**Impact**
We have a build target in tree which is nominally supposed to be working and supported, but doesn't actually work.

**Comment by nashif** [comment]
fixed
