### ISSUE TITLE
When the delay parameter of k_delayed_work_submit is K_FOREVER, the system will crash

### ISSUE THREAD

**Issue by LuoZhongYao** [zephyrproject-rtos/zephyr#24409]
**Describe the bug**
If the k_delayed_work_submit function is called with the K_FOREVER parameter, the system will error

**To Reproduce**
1. Use any board
2. Call the k_delayed_work_submit function and set the parameter to K_FOREVER, then call k_delayed_work_submit through another k_delayed_work

**Expected behavior**
Calling k_delayed_work_submit with K_FOREVER can directly return an error, or directly return..

**Environment (please complete the following information):**
 - OS: Any
 - Toolchain Zephyr SDK
 - Commit SHA 40ee38a9450598f8ddc384cf891fc55a44ded38f

**Comment by carlescufi** [comment]
@andyross we are likely missing a test for this particular usage of delayed work?

**Comment by andyross** [comment]
This actually never worked correctly (well, "correctly" -- it's a pathological case after all), and AFAICT the behavior didn't change with the timeout patch.  What actually happens in practice is that the delayed work timeout gets set for -1 (== K_FOREVER) ticks into the future, which means it fires immediately at the next timer interrupt.

I can't reproduce a crash, btw; it just fires normally but unexpectedly.  Maybe your app is hitting an unexpected situation and crashing?

As far as a fix: we can either document this as a "don't do that", or (what I think I'll submit) add a check to z_add_timeout() which noops if a K_FOREVER reaches down that far.
