### ISSUE TITLE
LPCXpresso55S69_ns target : build failed

### ISSUE THREAD

**Issue by CindyChmt** [zephyrproject-rtos/zephyr#24439]
There are some compilation problems when trying to compile Zephyr samples with the target "lpcxpresso55s69_ns".

**To Reproduce**
`west build -p auto -b lpcxpresso55s69_ns samples/hello_world`

**Issues**
It seems that there are 3 problems : 
One in `lpcxpresso55s69_ns_defconfig` file : CONFIG_ARM is not user configurable
and two in `nxp_lpc55s6x_ns.dtsi` file : It's missing i2c.h as included file and we have to replace kinetis-gpio by lpc-gpio otherwise the declaration of kinetis-port is missing.

**Environment :**
 - OS: Ubuntu
 - Toolchain : Zephyr SDK
 - Zephyr version : 2.2.99

**Comment by galak** [comment]
Fixed by #24368
