### ISSUE TITLE
docs: Allow to use the exact current zephyr version number in place of /latest/ in documentation URLs

### ISSUE THREAD

**Issue by KubaFYI** [zephyrproject-rtos/zephyr#24453]
**Is your enhancement proposal related to a problem? Please describe.**

Currently when `/latest/` in Zephyr docs URL (`https://docs.zephyrproject.org/latest/*`) is substituted with `<MAJOR>.<MINOR>.<PATCH>` of the most recent release (like one would reach docs for older releases) a `Page Not Found` page is being shown. This creates a problem in a situation when the most recent release changes, and links used externally in mind with the old release version start pointing to that new release.

This is problematic in situations like writing set-up instructions for an external project using a specific version of Zephyr, which at the time of writing is the latest release.

**Describe the solution you'd like**
Have `/latest/` in docs URL be interchangeable with the actual version number of that release, in the same way one can use older release version numbers.

**Comment by carlescufi** [comment]
@KubaFYI the problem is that if we do that you'd get the false impression that the doc corresponds to the release, and it really doesn't: it instead just mirrors the current state of master at the time the docs were published (docs are built and published once a day).
One thing we could do is to use the .99 notation and have `2.3.99` redirect to `latest`.

CC @nashif

**Comment by nashif** [comment]
I do not follow what the issue is...

**Comment by stephanosio** [comment]
The latest Zephyr release, at the time of writing, is 2.2.0 and https://docs.zephyrproject.org/2.2.0/ is working just fine.

**Comment by KubaFYI** [comment]
@carlescufi Thanks for explaining this, it seems I misunderstood what the website claimed - I assumed that the 'latest' which right now corresponds to 2.2.99 was an actual release (I should have checked that). To be fair in the docs menu 'latest' figures under a "Document Release Versions" header, so this might give people the wrong idea that the current state is a release and not unset and changing master it actually is.

![Document Release Versions](https://i.imgur.com/IYw6Ha0.png)

**Comment by nashif** [comment]
I think what we could fix is remove the `2.2.99` and put `latest` instead in the picture above.

**Comment by carlescufi** [comment]
@nashif is this something we can do or does it require changes in the web server or sphinx?

**Comment by nashif** [comment]
it is something that can be done in the doc source code, templates...
