### ISSUE TITLE
Bluetooth: Mesh: Configuration Client: Add support for Model Subscription Get

### ISSUE THREAD

**Issue by robinh17** [zephyrproject-rtos/zephyr#24505]
**Problem**
Nodes implemented with the Configuration Client model needs to be able to send a "Config SIG Model Subscription Get" message or "Config Vendor Model Subscription Get". On the target node, the configuration server model shall reply with a "Config SIG Model Subscription List" or "Config Vendor Model Subscription List" containing all addresses from the Subscription List of the model. The Bluetooth mesh APIs does not have a function for this. 

**Possible solution**
Bluetooth mesh configuration client model:
-Add function that gets the Subscription List from target node. 
-Add model opcode handler for ("Config SIG Model Subscription List", 0x80 0x2A)
-Add model opcode handler for ("Config Vendor Model Subscription List", 0x80 0x2C)

Bluetooth mesh configuration server model:
-Add model opcode handler for("Config SIG Model Subscription Get, 0x80 0x29)
-Add model opcode handler for("Config Vendor Model Subscription Get, 0x80 0x2B)

**Comment by jhedberg** [comment]
The server side of this is already implemented, as far as I can see

**Comment by LingaoMeng** [comment]
it's true, the cfg_srv side already implemented. see https://github.com/zephyrproject-rtos/zephyr/blob/c97f6f8eeb06c20c75b2c9a7690d9c58f3ea07af/subsys/bluetooth/mesh/cfg_srv.c#L3175-L3181

**Comment by trond-snekvik** [comment]
All the "get list" type config client messages are missing.

I can take a look at this.

**Comment by robinh17** [comment]
Fixed in #24594
