### ISSUE TITLE
devicetree: are some defines missing from the bindings?

### ISSUE THREAD

**Issue by sslupsky** [zephyrproject-rtos/zephyr#24533]
There are some gpio configuration defines in the file located at includes/drivers/gpio.h such as GPIO_OUTPUT

There are a few gpio configuration defines in the file located at includes/dt-bindings/gpio/gpio.h such as GPIO_ACTIVE_HIGH

When I define a gpio phandle in my devicetree file, I would like to include the GPIO input/output configuration flags such as GPIO_OUTPUT, GPIO_INPUT, GPIO_OUTPUT_INACTIVE, etc.

At the moment this is not possible because these defines are not part of dt-bindings/gpio/gpio.h and drivers/gpio.h cannot be included in the dts because of references to other includes (stdlib.h, etc).

My question is should some of the defines be moved from drivers/gpio.h to dt-bindings/gpio/gpio.h so they can be used in the devicetree?

**Comment by pabigot** [comment]
No, they shouldn't.  For compatibility across systems the flags available for use in devicetree descriptions are those used by Linux devicetree sources, which are only the ones devinced in the `dt-bindings` version of the header.  The other flags must be provided by the application in source code.
