### ISSUE TITLE
arch_mem_domain_max_partitions_get() returns equal number for all architectures

### ISSUE THREAD

**Issue by maksimmasalski** [zephyrproject-rtos/zephyr#24534]
Kernel function arch_mem_domain_max_partitions_get() returns equal number of maximum available memory partitions for all architectures. Now it returns 16. That is a software limit made by CONFIG_MAX_DOMAIN_PARTITIONS.

Different architectures have different maximum possible hardware number of partitions. Necessary to change the maximum number of domain partitions according to the architecture.
For example:
ARM Cortex-M4 has only 8 MPU regions total
ARM Cortex-M7 has 16 MPU regions total
ARC has 8 MPU regions IIRC
x86 has an MMU, there's no HW limit

**Comment by andrewboie** [comment]
I am unable to reproduce this.

What platforms have you tested this on?
