### ISSUE TITLE
scripts/subfolder_list.py: Support long paths

### ISSUE THREAD

**Issue by Abhishek-brcm** [zephyrproject-rtos/zephyr#24576]
I am facing an issue where os.symlink call in subfolder_list.py(zephyr v2.2) results in below error:
"scripts/subfolder_list.py", line 56, in main
os.symlink(directory, symlink)
OSError: [Errno 36] File name too long   

Here is the example of one of the symlink getting created on one of the systems:
directory path:
```
'/tmp/yocto_builds/ 20133855_ genericx86-64/poky/build/tmp/work/
aarch64-poky-linux/brcm-zephyr/gitAUTOINC+a20a30cd86_bfa48a337e_dbbf7c9b30_f3635d87f4_90d93a11ba_ae871b61ae_5ba575618e-r0/git/
zephyr/include/arch/arm/aarch32/cortex_m/mpu'

```
It's symlink created by subfolder_list.py:
```
 '/tmp/yocto_builds/ 20133855_ genericx86-64/poky/build/tmp/work/
aarch64-poky-linux/brcm-zephyr/gitAUTOINC+a20a30cd86_bfa48a337e_dbbf7c9b30_f3635d87f4_90d93a11ba_ae871b61ae_5ba575618e-r0/git/
zephyr/samples/hello_world/build_soc/zephyr/misc/generated/syscalls_links/
_tmp_yocto_builds_20133855_genericx86-64_poky_build_tmp_work_aarch64-poky-linux_brcm-zephyr_gitAUTOINC+a20a30cd86_bfa48a337e_dbbf7c9b30_f3635d87f4_90d93a11ba_ae871b61ae_5ba575618e-r0_git_zephyr_include_arch_arm_aarch32_cortex_m_mpu'

```
Above symlink is evidently too long.

I can think of 2 ways to reduce symlink length:
1. Symlink creation should use relative path instead of absolute path.
As symlink is in zephyr build directory and original directory is in source directory;
a relation needs to be established in between zephyr source directory and build directory.

2. The final symlink name should not use entire PATH in the name, rather just start from "include_*"
For example: Instead of this:
`_tmp_yocto_builds_20133855_genericx86-64_poky_build_tmp_work_aarch64-poky-linux_brcm-zephyr_gitAUTOINC+a20a30cd86_bfa48a337e_dbbf7c9b30_f3635d87f4_90d93a11ba_ae871b61ae_5ba575618e-r0_git_zephyr_include_arch_arm_aarch32_cortex_m_mpu`
Name could be just:
`include_arch_arm_aarch32_cortex_m_mpu
`
This should reduce symlink length almost by half.

**Comment by tejlmand** [comment]
> 
> 
> I am facing an issue where os.symlink call in subfolder_list.py(zephyr v2.2) results in below error:
> "scripts/subfolder_list.py", line 56, in main
> os.symlink(directory, symlink)
> OSError: [Errno 36] File name too long
> 
> Here is the example of one of the symlink getting created on one of the systems:
> directory path:
> 
> ```
> '/tmp/yocto_builds/ 20133855_ genericx86-64/poky/build/tmp/work/
> aarch64-poky-linux/brcm-zephyr/gitAUTOINC+a20a30cd86_bfa48a337e_dbbf7c9b30_f3635d87f4_90d93a11ba_ae871b61ae_5ba575618e-r0/git/
> zephyr/include/arch/arm/aarch32/cortex_m/mpu'
> ```
> 
> It's symlink created by subfolder_list.py:
> 
> ```
>  '/tmp/yocto_builds/ 20133855_ genericx86-64/poky/build/tmp/work/
> aarch64-poky-linux/brcm-zephyr/gitAUTOINC+a20a30cd86_bfa48a337e_dbbf7c9b30_f3635d87f4_90d93a11ba_ae871b61ae_5ba575618e-r0/git/
> zephyr/samples/hello_world/build_soc/zephyr/misc/generated/syscalls_links/
> _tmp_yocto_builds_20133855_genericx86-64_poky_build_tmp_work_aarch64-poky-linux_brcm-zephyr_gitAUTOINC+a20a30cd86_bfa48a337e_dbbf7c9b30_f3635d87f4_90d93a11ba_ae871b61ae_5ba575618e-r0_git_zephyr_include_arch_arm_aarch32_cortex_m_mpu'
> ```
> 
> Above symlink is evidently too long.
> 
> I can think of 2 ways to reduce symlink length:
> 
>     1. Symlink creation should use relative path instead of absolute path.
>        As symlink is in zephyr build directory and original directory is in source directory;
>        a relation needs to be established in between zephyr source directory and build directory.
> 

This would actually not help, as the symlink name itself is what causes a too long filename, not whether that link is full path or relative path.

>     2. The final symlink name should not use entire PATH in the name, rather just start from "include_*"
>        For example: Instead of this:
>        `_tmp_yocto_builds_20133855_genericx86-64_poky_build_tmp_work_aarch64-poky-linux_brcm-zephyr_gitAUTOINC+a20a30cd86_bfa48a337e_dbbf7c9b30_f3635d87f4_90d93a11ba_ae871b61ae_5ba575618e-r0_git_zephyr_include_arch_arm_aarch32_cortex_m_mpu`
>        Name could be just:
>        `include_arch_arm_aarch32_cortex_m_mpu `
>        This should reduce symlink length almost by half.

Well, in you case this will make the symlink name itself much shorter than half.
But if you count the fullpath to the symlink itself, that your right, it will be half, but we cannot move the location of the build folder, only the user can decide where to place build folder.

But this is now fixed in #24584
