### ISSUE TITLE
Couldn't get test results from device serial on mimxrt1050_evk board.

### ISSUE THREAD

**Issue by chen-png** [zephyrproject-rtos/zephyr#24579]
**Describe the bug**
running tests on mimxrt1050_evk board, it was good to flash test images, but **couldn't get the tests output from /device/serial.**

**used git bisect and found the first bad commit is 50129f8d**

**To Reproduce**
1. west build -b mimxrt1050_evk -p auto samples/hello_world
2. west flash

**Screenshots or console output**

nothing 

**Environment (please complete the following information):**
 - OS: Fedora28
 - Toolchain : zephyr-sdk-0.11.2
 - Commit ID: 6e3f8687

**Comment by nashif** [comment]
@galak your commit...

**Comment by henrikbrixandersen** [comment]
@chen-png Could you please test the fix in #24606?
