### ISSUE TITLE
Devices vs. drivers

### ISSUE THREAD

**Issue by chris-makaio** [zephyrproject-rtos/zephyr#24632]
Sorry for not specifying more, but I'm not sure if this is an issue at all.

Let me describe our challenge:
Our board features multiple PMICs and depending on the current main system voltage, we start either LDO, BUCK or BOOST. The problem here is that it is bad to start all three because there will be some excess current (a design problem ATM) which will persist even if we shut down all PMICs (switches leaking).

What we do now is to ask the main PMIC via I2C about the main system voltage and decide which PMICs to shut down. But currently, this kicks in too late (as described above). As stated in #24318 and #19448 we currently have no app-level control to run drivers conditionally.

I could move the logic to the drivers, but since it is application logic, that won't fit well and hold me back from contributing the sources (as they won't be generic anymore). 

Putting it in a board.c with SYS_INIT at POST_KERNEL prohibits the use of k_sleep (which is required for ADCing the sys voltage).

For now I guess I'll add it as a driver, although the logic is not really a driver, but rather .. uhm.. a device manager, I guess. Where do you recommend to put it?

**Comment by andrewboie** [comment]
> Putting it in a board.c with SYS_INIT at POST_KERNEL prohibits the use of k_sleep (which is required for ADCing the sys voltage).

Are you sure k_sleep() is forbidden? The POST_KERNEL phase runs in the context of the main thread with interrupts enabled (and not a pre-thread environment on the irq stack), I think you should be able to sleep there.
