### ISSUE TITLE
Board IP Can Not Be Set Manually

### ISSUE THREAD

**Issue by sercantun** [zephyrproject-rtos/zephyr#24695]
**Describe the bug**
I am using Nucleo F429ZI Board. And trying to run net/sockets/echo server example. 
Problem is that card can not set its own IPv4 nor IPv6 address given with CONFIG_NET_CONFIG_MY_IPV6_ADDR and CONFIG_NET_CONFIG_MY_IPV4_ADDR  parameters. 

Although, CONFIG_NETWORKING, CONFIG_NET_IPV4 and CONFIG_NET_CONFIG_SETTINGS selected in the original prj.conf file, when compiling I get these errors;

warning: NET_CONFIG_PEER_IPV4_ADDR (defined at subsys/net/lib/config/Kconfig:110) was assigned the
value '192.0.2.2' but got the value ''.

warning: ignoring malformed line ' CONFIG_NET_CONFIG_SETTINGS=y'
warning: ignoring malformed line ' CONFIG_NET_CONFIG_MY_IPV6_ADDR="2001:db8::1"'
warning: ignoring malformed line ' CONFIG_NET_CONFIG_PEER_IPV6_ADDR="2001:db8::2"'
warning: ignoring malformed line ' CONFIG_NET_CONFIG_MY_IPV4_ADDR="192.0.2.1"'

**Comment by jukkar** [comment]
Note that the config option is named `CONFIG_NET_CONFIG_PEER_IPV4_ADDR`, are you missing `CONFIG_`?

**Comment by sercantun** [comment]
Yes, the configuration is set with CONFIG_NET_CONFIG_PEER_IPV4_ADDR.

**Comment by jukkar** [comment]
How you have modified the conf file, the upstream conf file works just fine with the board you mentioned.

**Comment by carlescufi** [comment]
@sercantun please post the whole `build/zephyr/.config` file.

**Comment by sercantun** [comment]
.config file can not be generated because of the compile error.

Compile stops here;
Error: Aborting due to non-whitelisted Kconfig warning
../zephyrproject/zephyr/samples/net/sockets/echo_server/prj.conf:47: warning: ignoring
malformed line ' CONFIG_NET_CONFIG_SETTINGS=y''.

**Comment by jukkar** [comment]
> Error: Aborting due to non-whitelisted Kconfig warning
> ../zephyrproject/zephyr/samples/net/sockets/echo_server/prj.conf:47: warning: ignoring
> malformed line ' CONFIG_NET_CONFIG_SETTINGS=y''.

Do you have extra space in start of the config entry, the error print indicates that.

**Comment by sercantun** [comment]
Thank you all for your support. Problem is solved when I re-install zephyr in another directory. And board had a static IP.
