### ISSUE TITLE
ztest_test_fail() doesn't always work

### ISSUE THREAD

**Issue by andrewboie** [zephyrproject-rtos/zephyr#24713]
**Describe the bug**
I started to notice that sometimes in tests a `zassert` expression would fail, and this would be reported to the console output, but the test scenario would still pass.

Upon further inspection, I found that the zassert was being invoked from a child thread,
but the main ztest_thread kept running, and the entire suite passed even though I had
multiple failures.

**Expected behavior**
I expect when ztest_test_pass(), ztest_test_fail(), ztest_test_skip() are invoked, this is not clobbered by some other call to these same APIs.

**Impact**
What impact does this issue have on your progress (e.g., annoyance, showstopper)

showstopper, tests can report passing when they are not

**Comment by carlescufi** [comment]
See #24714 for a partial? fix?

**Comment by andrewboie** [comment]
@carlescufi is that the right GH link? #24714 is unrelated to this I think (although I encountered this problem while developing it)

**Comment by andrewboie** [comment]
I have a partial fix for this in #25011 I think we can lower priority if that goes in.

Better still would be a kernel API to iterate over all nonessential threads and abort them, but there isn't a safe/robust way to do this currently.

**Comment by pabigot** [comment]
@carlescufi the partial fix has been merged, should this be lowered in priority as suggested above?

**Comment by andrewboie** [comment]
I'll just close this, the few test setups that create complex hierarchies of threads need to be written to clean up after themselves properly and can be dealt with on a case-by-case basis if they don't
