### ISSUE TITLE
Bluetooth: controller: Network privacy not respected when address resolution is disabled

### ISSUE THREAD

**Issue by joerchan** [zephyrproject-rtos/zephyr#24731]
**Describe the bug**
The resolving list is not used when address resolution has been disabled by the host.
The address resolution enable command should (after a few erratas) only control resolving of RPAs.
If a device has been added to the resolving list with a valid IRK, and address resolution is not enabled. This should act as a blacklist, and we should not connect to it, or accept connection requests from it.
Since we cannot resolve it, and using it's identity is a violation of network privacy.

**To Reproduce**
Uncomment the following line in `tests/bluetooth/bsim_bt/edtt_ble_test_app/tests_scripts/ll.set1.test_list` and run it according to the readme:
`#LL/CON/INI/BV-24-C #currently failing, to be investigated`

**Expected behavior**
Initiator should not connect to devices in the resolving list with a valid IRK when address resolution is disabled.

**Impact**
Failing LL conformance testcase.
Affects all vendors of Split, and Legacy controller.

**Additional information**
The test has a TSE waiver, but that is not related to why this test is failing now. But would explain why we have qualified without this test before:
https://www.bluetooth.org/tse/errata_view.cfm?errata_id=11429
The waiver seems not to apply anymore when using TCRL 2019-2 or higher.

**Comment by joerchan** [comment]
The test has a TSE waiver, but that is not related to why this test is failing now. But would explain why we have qualified without this test before:
https://www.bluetooth.org/tse/errata_view.cfm?errata_id=11429

**Comment by carlescufi** [comment]
We might need to revisit this the next time we run Controller qualification tests.
