### ISSUE TITLE
Low throughput with the zperf sample using stm32f746g_disco

### ISSUE THREAD

**Issue by iwasz** [zephyrproject-rtos/zephyr#24770]
**Describe the bug**
TCP benchmark as described in [zperf sample documentation](https://docs.zephyrproject.org/latest/samples/net/zperf/README.html) reports low transfer rate abd errors on **stm32f746g_disco**, while UDP test works, and gives 30Mbps result. I am referring to the scenario where Zephyr acts as a client, while Linux host runs the iperf server.

**What have you tried to diagnose or workaround this issue?**
I tried to tweak CONFIG_NET_BUF_TX_COUNT, CONFIG_NET_PKT_TX_COUNT and NET_BUF_DATA_SIZE Kcoinfig values. 

**To Reproduce**
1. set correct IP addresses in ```zephyrproject/zephyr/samples/net/zperf/prj.conf```. In my case:
```ini
CONFIG_NET_CONFIG_MY_IPV4_ADDR="192.168.0.33"
CONFIG_NET_CONFIG_PEER_IPV4_ADDR="192.168.0.29"
```
2. cd zephyrproject/zephyr
3. west build --pristine -b stm32f746g_disco samples/net/zperf/
4. west flash
4. Connect the nucleo board to a router.

On the host (IP 192.168.0.29) run iperf:

```sh
iperf -s -p 5001 -B 192.168.0.29
```
5. On the Zephyr target run zperf as so:

```
uart:~$ zperf tcp upload2 v4 
Connecting to 192.168.0.29
Duration:	1.00 s
Packet size:	256 bytes
Rate:		10 kbps
Starting...
New session started
There was 4 network buffer allocation errors during send.
Consider increasing the value of CONFIG_NET_BUF_TX_COUNT and
optionally CONFIG_NET_PKT_TX_COUNT Kconfig options.
-
Upload completed!
Duration:	4.00 s
Num packets:	11
Num errors:	4 (retry or fail)
Rate:		5 Kbps
[00:17:30.743,000] <err> net_pkt: Data buffer (304) allocation failed.
[00:17:31.744,000] <err> net_pkt: Data buffer (304) allocation failed.
[00:17:32.744,000] <err> net_pkt: Data buffer (304) allocation failed.
[00:17:33.744,000] <err> net_pkt: Data buffer (304) allocation failed.
```

On the Linux host use iperf (2.0.13) as so:

```
iperf -s -p 5001 -B 192.168.0.29 
------------------------------------------------------------
Server listening on TCP port 5001
Binding to local address 192.168.0.29
TCP window size:  128 KByte (default)
------------------------------------------------------------
[  4] local 192.168.0.29 port 5001 connected with 192.168.0.33 port 5001
```

After increasing ```CONFIG_NET_BUF_TX_COUNT``` to 128 (as suggested by zperf) and increasing ```NET_BUF_DATA_SIZE``` to 1024 and ```CONFIG_NET_PKT_TX_COUNT``` to 16 the errors reported changed a little bit. 

```
uart:~$ zperf tcp upload2 v4

Setting IP address 2001:db8::1
Setting destination IP address 2001:db8::2
Setting IP address 192.168.0.33
Setting destination IP address 192.168.0.29

Connecting to 192.168.0.29
Duration:	1.00 s
Packet size:	256 bytes
Rate:		10 kbps
Starting...
New session started
There was 1 network buffer allocation errors during send.
Consider increasing the value of CONFIG_NET_BUF_TX_COUNT and
optionally CONFIG_NET_PKT_TX_COUNT Kconfig options.
-
Upload completed!
Duration:	1.00 s
Num packets:	19
Num errors:	1 (retry or fail)
Rate:		37 Kbps
```

**Expected behavior**
When tests are run using UDP protocol, the results are much higher (~30Mbps). I would assume TCP test without any error, and should give better speeds than 5Kbps or 37 Kbps. Below is the output from UDP test:

```
uart:~$ zperf udp upload2 v4 10 1K 50M
Connecting to 192.168.0.29
Duration:	10.00 s
Packet size:	1024 bytes
Rate:		51200 kbps
Starting...
Rate:		50.00 Mbps
nb_packets=3707	delay=0	adjust=-26366
nb_packets=7400	delay=0	adjust=-19878
nb_packets=11093	delay=0	adjust=-20327
nb_packets=14786	delay=0	adjust=-27277
nb_packets=18477	delay=0	adjust=-26586
nb_packets=22168	delay=0	adjust=-26483
nb_packets=25859	delay=0	adjust=-19589
nb_packets=29550	delay=0	adjust=-26585
nb_packets=33244	delay=0	adjust=-20369
-
Upload completed!
LAST PACKET NOT RECEIVED!!!
Statistics:		server	(client)
Duration:		67.56 m	(10.00 s)
Num packets:		0	(36940)
Num packets out order:	1
Num packets lost:	74559
Jitter:			43.00 m
Rate:			0 Kbps	(28.85 Mbps)
```
At the same time, the output on on the host:

```
iperf -s -p 5001 -B 192.168.0.29 -u 
------------------------------------------------------------
Server listening on UDP port 5001
Binding to local address 192.168.0.29
Receiving 1470 byte datagrams
UDP buffer size:  208 KByte (default)
------------------------------------------------------------
[  3] local 192.168.0.29 port 5001 connected with 192.168.0.33 port 5001
[ ID] Interval       Transfer     Bandwidth        Jitter   Lost/Total Datagrams
[  3]  0.0-10.1 sec  46.1 MBytes  38.3 Mbits/sec   0.020 ms    0/47171 (0%)
```

**Impact**
I have problems when sending big chunks of TCP data (from Zephyr to a host) at once using sockets. I've tried to stream 160x120 static video stream from stm32f746g_disco to the Linux host running gst-launch as can be seen in [```samples/video/tcpserversink```](https://docs.zephyrproject.org/latest/samples/video/tcpserversink/README.html) example. This example sends relatively big amounts of data from the Zephyr target to a host, just like zperf tests described above. I lowered the resolution to prevent memory depletion, and observed very unstable behavior. gst-launch would exit after 0.3s saying that stream was cut, and Zephyr would say hat the peer closed the connection. Then when I risen various log levels to ```debug``` which caused the log to flood, I could see a few seconds of "static" video capture. 

**Environment (please complete the following information):**
 - OS: Manjaro
 - Toolchain : Zephyr SDK
 - Commit SHA or Version used : commit 9be1ba9e0875f4baaa990dd36326a1d60270e621

**Comment by jukkar** [comment]
There is also report about poor TCP performance #23302
