### ISSUE TITLE
Remove all uses of CONFIG_LEGACY_TIMEOUT_API  from the tree before 2.3

### ISSUE THREAD

**Issue by carlescufi** [zephyrproject-rtos/zephyr#24926]
Convert the remaining subsystems that still enable `CONFIG_LEGACY_TIMEOUT_API` so that it can be safely disabled by default.
Please use `SYS_FOREVER_MS` (in `include/sys/time_util.h`) as the value for infinite timeout if you decide to stay with `s32_t` instead of switching to `k_timeout_t` in the API. Also use `SYS_TIMEOUT_MS()` to convert from `s32_t` to `k_timeout_t` instead of rolling your own.

Subsystems to do:

#24861 (@carlescufi)
- [x] drivers/display/Kconfig.microbit
- [x] drivers/video/Kconfig
- [x] drivers/serial/Kconfig
- [x] soc/arm/ti_simplelink/Kconfig
- [x] subsys/console/Kconfig
- [x] drivers/i2s/Kconfig
- [x] drivers/modem/Kconfig

#24649:
- [x] drivers/lora/Kconfig

#24956 (@andyross)
- [x] lib/cmsis_rtos_v1/Kconfig
- [x] lib/cmsis_rtos_v2/Kconfig

#24964 (@pfalcon)
- [x] lib/posix/Kconfig

#24931 (@alexanderwachter):
- [x] drivers/can/Kconfig
- [x] subsys/canbus/isotp/Kconfig

**Comment by Mani-Sadhasivam** [comment]
@carlescufi For LoRa, conversion is done in #24649

**Comment by carlescufi** [comment]
> @carlescufi For LoRa, conversion is done in #24649

Thank you! Updated

**Comment by carlescufi** [comment]
@andrewboie could you port the CMSIS RTOS API please?
@pfalcon could you do `lib/posix`?

**Comment by pfalcon** [comment]
> @pfalcon could you do lib/posix please or let me know if you can't?

I will look into it. I assume the timeframe is "before the release"?

I also wish the description pointed to a "model" commit doing such a refactor.

**Comment by carlescufi** [comment]
> > @pfalcon could you do lib/posix please or let me know if you can't?
> 
> I will look into it. I assume the timeframe is "before the release"?

Thanks! Yes, there is still time during the 2.3 stabilization period

> I also wish the description pointed to a "model" commit doing such a refactor.

Right, sorry. https://github.com/zephyrproject-rtos/zephyr/pull/24861 could be a starting point, though I see you have already pushed a PR! Thank you!

**Comment by pfalcon** [comment]
@carlescufi 

>  though I see you have already pushed a PR

Indeed, https://github.com/zephyrproject-rtos/zephyr/pull/24964 was posted, but that appears to systematically fail CI due to https://github.com/zephyrproject-rtos/zephyr/issues/25017. I would need help with driving resolution for that issue.

**Comment by carlescufi** [comment]
Thanks @andyross for #24956. Marked as done now.
