### ISSUE TITLE
LSPI of NXP i.MX RT timing delay issue

### ISSUE THREAD

**Issue by lgl88911** [zephyrproject-rtos/zephyr#24939]
**Describe the bug**
1. Zephyr Can't update DBT/SCKPCS/PCSSCK to nxp_hal according to spi rate， cause spi transfer slow.
2. The delay time calculated by nxp_hal has an overflow problem，will casue no update  DBT/SCKPCS/PCSSCK,cause spi transfer slow.

I submitted 2 pr to solve these problems：
https://github.com/zephyrproject-rtos/hal_nxp/pull/36
https://github.com/zephyrproject-rtos/zephyr/pull/23918

**Comment by carlescufi** [comment]
@MaureenHelm could you please take a look?

**Comment by MaureenHelm** [comment]
@lgl88911 will you please split this into two separate GitHub issues:
1. Configure/optimize the delay time. This is an enhancement. The overflow can be addressed as part of the enhancement, since it's not a problem otherwise.
2. Other interrupts treated as transfer completion. This is a bug. Can you elaborate on how to reproduce this, and the priority?

**Comment by lgl88911** [comment]
@MaureenHelm  Thanks for your reply
1. for delay time:When the spi speed is configured to be relatively high, the delay calculated by 500K will greatly reduce the transmission rate. The following is an example of 5M. Looking at the overall transmission at a time, the actual transmission speed is only slightly higher than 500K, but far below 5M .
![image](https://user-images.githubusercontent.com/3456246/82732889-cf53cf00-9d42-11ea-9134-1243448297f3.png)
 2. After the master transfer is completed,if the sr flag is not clear, the callback of the transfer
completion will be called again in other interrupts. You can use the following method to reproduce：
       Call spi_wirte about 150K Byte , Measure the time used by spi_write, under normal circumstances it will take some time, this time will become 0 once issue occur. The occurrence of issues is random and cannot be recovered once it occur. The speed of SPI is set between 20M ~ 25M, which is relatively easy to copy.

**Comment by lgl88911** [comment]
@MaureenHelm 
I raise https://github.com/zephyrproject-rtos/zephyr/issues/25566 to tracking interrupt issue. This issue to keep tracking time delay issue
