### ISSUE TITLE
BT_LE_ADV_NCONN_NAME doesn't actually advertise name

### ISSUE THREAD

**Issue by jeremyherbert** [zephyrproject-rtos/zephyr#25016]
**Describe the bug**
If I use `BT_LE_ADV_CONN_NAME` as the first parameter to `bt_le_adv_start`, then the device name (as set in the `prj.conf` file) shows up correctly when scanning for devices using an iOS or Android app. However, when I use `BT_LE_ADV_NCONN_NAME` the name does not show up, even though `BT_LE_ADV_OPT_USE_NAME` is used in its definition in `bluetooth.h`.

**To Reproduce**
1. Build and flash the following code with `BOARD=nrf52840_pca10056`: https://gist.github.com/jeremyherbert/62cbed007f2f0c1b5b1a550fd14726ec
2. Open a BLE scanning app
3. Observe that there is no advertised name
4. Change `BT_LE_ADV_NCONN_NAME` in `main.c` to `BT_LE_ADV_CONN_NAME`, build and flash
5. Observe that the name is now advertised

**Expected behavior**
The name should be advertised in both cases

**Impact**
It makes finding the device very difficult in an area with lots of BLE devices.

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04
 - Commit: ff214d637e
 - Board: nrf52840_pca10056

**Comment by joerchan** [comment]
This has already been fixed by: ffa10eba8350
