### ISSUE TITLE
kernel: pipe: read_avail / write_avail syscalls

### ISSUE THREAD

**Issue by cfriedt** [zephyrproject-rtos/zephyr#25036]
**Is your enhancement proposal related to a problem? Please describe.**
It's not immediately obvious how much of a k_pipe buffer is available for reading / writing (if the buffer even exists - they can be created with no buffer).

**Describe the solution you'd like**
Just a few extra functions. I've already written them for buffered pipes. Handling unbuffered pipes may be a simple modification.
```
size_t k_pipe_read_avail(const struct k_pipe *pipe);
size_t k_pipe_write_avail(const struct k_pipe *pipe);
```

**Describe alternatives you've considered**
I didn't see any other alternatives, so I just wrote them myself. 

**Additional context**
Was going to keep them static inside of my socketpair(2) implementation (#24813) but was asked to make a separate PR for this by @pfalcon CC @carlescufi .

**Comment by pfalcon** [comment]
+1 for adding this functionality, the usecase is pretty clear.

**Comment by cfriedt** [comment]
Also, for reasons that are probably obvious to the maintainers, I'm going to add a timeout parameter as well; even though the pipes are constant, it's possible that another thread could be modifying values concurrently and therefore it would probably be safe to hold the semaphore.

**Comment by cfriedt** [comment]
CC @pfalcon @carlescufi
