### ISSUE TITLE
optimize 32-bit x86 system calls

### ISSUE THREAD

**Issue by andrewboie** [zephyrproject-rtos/zephyr#25093]
**Is your enhancement proposal related to a problem? Please describe.**
System calls on 32-bit x86 use the old-style `int 0x80` mechanism to trap to supervisor mode (Ring 0). There are more efficient ways to do this.

**Describe the solution you'd like**
Use `SYSENTER`/`SYSEXIT` instead to perform syscalls. This has much less overhead but requires manual stack switching. Our 64-bit port already uses the very similar `SYSCALL`/`SYSRET`.
https://c9x.me/x86/html/file_module_x86_id_313.html
https://c9x.me/x86/html/file_module_x86_id_314.html
https://wiki.osdev.org/SYSENTER

**Describe alternatives you've considered**
None.

**Comment by andrewboie** [comment]
Top two commits of this old branch is where I started working on this, but I set it aside. https://github.com/andrewboie/zephyr/tree/sysenterexit

**Comment by dcpleung** [comment]
`SYSENTER` is not very secure as it does not save `EIP` and `ESP` automatically. This needs to be done with code in ring 3. `SYSENTER` just jumps to syscall entry and has to trust whatever coming `EIP` and `ESP` are. This can be abused to return to some arbitrary code after handling the syscall. So not going to implement this.
