### ISSUE TITLE
driver: gpio: mchp: GPIO initialization value doesn't get reflected when using new flags

### ISSUE THREAD

**Issue by albertofloyd** [zephyrproject-rtos/zephyr#25101]
If GPIO is configure to have an initial value HIGH using new GPIO flags, the value doesn't reflect for mec15 boards.
This gets masked because on subsequent steps of test cases gpio_pin_set_raw() is used.

**To Reproduce**
Modify code so no calls to gpio_pin_set_raw() are done

1) cd test/drivers/gpio
2) west build -c -b mec15xxevb_assy6853
3) west flash
Check GPIO output with multimeter, it's LOW

**Expected behavior**
INitialization value passed as flag to GPIO, needs to reflect in physical pin after configure() operation

**Impact**
MEC15 board initialization may have pins erroneously configured, before they are been used and pins that only get initialized once.

**Comment by maksimmasalski** [comment]
@albertofloyd folder tests/drivers/gpio has 2 tests folders: gpio_api_1pin and gpio_basic_api
Which one you used?
