### ISSUE TITLE
Bluetooth: controller: Incorrect version information

### ISSUE THREAD

**Issue by cvinayak** [zephyrproject-rtos/zephyr#25130]
**Describe the bug**
During Bluetooth conformance testing of v2.2-branch, tests with version information exchange failed with incorrect HCI and LL version number.

**To Reproduce**
1. mkdir build; cd build
2. cmake -GNinja -DBOARD=nrf52_pca10040 ../samples/bluetooth/hci_uart
3. ninja flash
4. Use the board under conformance tester

**Expected behavior**
Correct Bluetooth version of v5.2 is recorded in the test logs and results/

**Impact**
showstopper

**Screenshots or console output**
NA

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: Zephyr SDK
 - Commit SHA or Version used: 82083a90cc23ae62ff7d9a269857491a17d8891c

**Additional context**
Fixed upstream in #25072

**Comment by jhedberg** [comment]
Closing this one as the PR was abandoned for 2.2
