### ISSUE TITLE
Cannot use C++ on APPLICATION level initialization

### ISSUE THREAD

**Issue by r2r0** [zephyrproject-rtos/zephyr#25141]
**Describe the bug**
Cannot use C++ in functions called at APPLICATION initialization level.
Because setup of C++ subsystem is performed after APPLICATION level initialization then C++ usage is limited to main & following threads.

**To Reproduce**
1. Define static instance of class with non trivial constructor
2. Use SYS_INIT macro to define function called at APPLICATION level
3. Try to use C++ object in function defined in point 2
4. Object is not properly constructed

**Expected behavior**
C++ sybsystem should be avialable at APPLICATION initialization level.
It would be great if the POST_KERNEL level will be also usable from C++ but maybe I am going too far.
If it is not possible (i.e. because of Zephyr design philosophy) then this limitation should be clearly mentioned in the documentation.

**Impact**
Annoyance.

**Screenshots or console output**

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: Zephyr SDK
 - Commit: 6789ecbd5e13cc19e69f25314cf486493df9dde3

**Additional context**

**Comment by pabigot** [comment]
I agree; I personally would like this to occur even earlier, but there was strong pushback at the suggestion that C++ might be used in drivers.

The [documentation](https://docs.zephyrproject.org/latest/reference/kernel/other/cxx_support.html) says it's supported for applications.  It is ambiguous whether that includes initialization routines run at the application init level, but I think it's worth trying.
