### ISSUE TITLE
tests/drivers/console: drivers.console.semihost can't work

### ISSUE THREAD

**Issue by erwango** [zephyrproject-rtos/zephyr#25191]
**Describe the bug**
When running sanitycheck, drivers.console.semihost is run on all cortex-m boards.
Though, it is failed on all boards I could test (various STM32, frdm_k64f_reel_board)
When running with west, test doesn't output anything on console.

**To Reproduce**
Run test with sanitycheck, west 

**Expected behavior**
Test runs successfully

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain (e.g Zephyr SDK, ...)
 - Commit SHA or Version used

**Additional context**

**Comment by stephanosio** [comment]
While the test can run on real hardware targets, sanitycheck will not be able to validate its output, unless the semihosting console output is somehow redirected to the serial port to which sanitycheck is connected.

I will provide a fix for this.

**Comment by erwango** [comment]
@stephanosio Txs for the fix.

About this feature, is that complying will all cortex-m ?
I checked given link: https://developer.arm.com/docs/dui0471/k/what-is-semihosting/what-is-semihosting

And they mention: "ARM processors use the SVC instructions, formerly known as SWI instructions, to make semihosting calls. However, if you are compiling for an ARMv6-M or ARMv7-M, for example a Cortex-M1 or Cortex-M3 processor, semihosting is implemented using the BKPT instruction."

I don't see these cases in `drivers/console/semihost_console.c`

**Comment by stephanosio** [comment]
> About this feature, is that complying will all cortex-m ?
> I checked given link: https://developer.arm.com/docs/dui0471/k/what-is-semihosting/what-is-semihosting

@erwango Yes, it works on all Cortex-M cores.

https://github.com/zephyrproject-rtos/zephyr/blob/c2a77db6d1a466ce54e05d4027390f7d914c55a2/drivers/console/semihost_console.c#L22

![image](https://user-images.githubusercontent.com/11345418/81578026-3a1d1600-93e5-11ea-82c1-25d307cc7b8c.png)

**Comment by erwango** [comment]
@stephanosio Txs for the confirmation!
