### ISSUE TITLE
CI seems to be stuck for my pull request

### ISSUE THREAD

**Issue by sglass68** [zephyrproject-rtos/zephyr#25210]
**Describe the bug**
https://github.com/zephyrproject-rtos/zephyr/pull/25110
Something seems to be wrong with the checks here. I tried twice and these three seem to be broken:

Gitlint
Identity/Emails
Kconfig

**To Reproduce**
1. Go to https://github.com/zephyrproject-rtos/zephyr/pull/25110
2. See error that everything is stuck

**Expected behavior**
Expect the checks to finish eventually. I pushed an updated tree but the same thing happened.

**Impact**
Cannot get pull request merged

**Screenshots or console output**
If applicable, add a screenshot (drag-and-drop an image), or console logs
(cut-and-paste text and put a code fence (\`\`\`) before and after, to help
explain the issue.

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain Zephyr SDK
 - Commit SHA or Version used: 0c77e80

**Additional context**

**Comment by galak** [comment]
Should be fixed by https://github.com/zephyrproject-rtos/ci-tools/pull/135/files
