### ISSUE TITLE
tests/drivers/gpio/gpio_basic_api failed on mec15xxevb_assy6853 board.

### ISSUE THREAD

**Issue by chen-png** [zephyrproject-rtos/zephyr#25272]
**Describe the bug**
running tests/drivers/gpio/gpio_basic_api on mec board,  **i connected Pin11 and Pin 13 on JP27, and removed jumper on JP15, but it still failed with "Check GPIO040_076 output 8 connected to input 9".**

i read the related issue #22931 and git bisect, found the **first bad commit is  e11da0582d8.**

**To Reproduce**
1. sanitycheck --hardware-map ~/mec1.file --device-testing 
    -T tests/drivers/gpio/gpio_basic_api/ -vv

**Screenshots or console output**

DEBUG   - DEVICE: *** Booting Zephyr OS build zephyr-v2.2.0-322-ge11da0582d85  ***
DEBUG   - DEVICE: Running test suite gpio_basic_test
DEBUG   - DEVICE: 
DEBUG   - DEVICE: starting test - test_gpio_port
**DEBUG   - DEVICE: Validate device GPIO040_076
DEBUG   - DEVICE: Check GPIO040_076 output 8 connected to input 9
DEBUG   - DEVICE: FATAL output pin not wired to input pin? (out high => in low)**

DEBUG   - Timed out while monitoring serial output on mec15xxevb_assy6853
INFO    - 1/1 mec15xxevb_assy6853       tests/drivers/gpio/gpio_basic_api/drivers.gpio.2pin FAILED Timeout (device 113.219s)

**Environment (please complete the following information):**
 - OS: fedora28
 - Toolchain: zephyr-sdk-0.11.2
 - Commit ID: 4980a13fc4

**Comment by chen-png** [comment]
@franciscomunoz @dcpleung  Could you take a look of this?

**Comment by dcpleung** [comment]
Because GPIO_050 has set to be used for TACH, so this is supposed to fail. A new GPIO line is needed.

**Comment by carlescufi** [comment]
@chen-png could you please label test failures with the "Tests" label?

**Comment by carlescufi** [comment]
> Because GPIO_050 has set to be used for TACH, so this is supposed to fail. A new GPIO line is needed.
@dcpleung 
Is this something that will be fixed, or should this test be blacklisted for this platform?

**Comment by dcpleung** [comment]
I am going to look for another GPIO line today.

**Comment by chen-png** [comment]
> @chen-png could you please label test failures with the "Tests" label?

yes,i will.
