### ISSUE TITLE
test/benchmarks/latency_measure fails on nucleo_f429zi and nucleo_f207zg

### ISSUE THREAD

**Issue by ABOSTM** [zephyrproject-rtos/zephyr#25287]
test/benchmarks/latency_measure fails on nucleo_f429zi and nucleo_f207zg

**To Reproduce**
1. west -v build -p auto  -b nucleo_f429zi test/benchmarks/latency_measure
2. test report failure

**Expected behavior**
Test should be passed

**Comment by ABOSTM** [comment]
This issue is fixed thanks to #24381

**Comment by erwango** [comment]
@carlescufi I set prio to medium, but you're free to adjust
