### ISSUE TITLE
SYSTICK: Inconsistency between dts status and Kconfig

### ISSUE THREAD

**Issue by QSQCaito** [zephyrproject-rtos/zephyr#25299]
**Describe the bug**
In the dts the systick is disabled, however, it's enabled via Kconfig options.
I'm not changing the systick status in my board dts. The dts systick status is taken from armv7-m.dtsi, and it appears as is in my build/zephyr/zephyr.dts file:
```
systick: timer@e000e010 {
			compatible = "arm,armv7m-systick";
			reg = < 0xe000e010 0x10 >;
			status = "disabled";
```
However,  `CORTEX_M_SYSTICK` is enabled by default because `CPU_CORTEX_M_HAS_SYSTICK` is also enabled. So this would mean that the SysTick is indeed enabled.

**To Reproduce**
I'm building a custom board, but any STM32L4 board should produce same results. 

**Expected behavior**
I would imagine that for SysTick to be effectively enabled, it would have to be first enabled in the dts.

**Impact**
None so far.

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain (GCC, J-link)
 - Commit SHA: 6e8775ff84

**Comment by mbolivar-nordic** [comment]
@ioannisg I'm guessing this is just because CONFIG_CORTEX_M_SYSTICK does not depend on the node being enabled, right?

Seems like we could just set it to "okay" and add the appropriate Kconfig dependency. The driver Kconfig is default n so it wouldn't affect nRF as far as I can see.

Am I missing something?

**Comment by QSQCaito** [comment]
@mbolivar-nordic , does it make sense to enable it directly at the armv7-m.dtsi level? For STM32 the LPTIM can be used as a Kernel tick, then it would have to be disabled, no?

**Comment by ioannisg** [comment]
@mbolivar CONFIG_CORTEX_M_SYSTICK indicates that the system timer is based on the SysTick.

> Seems like we could just set it to "okay" in armv7-m.dtsi and add the appropriate Kconfig dependency. The driver Kconfig is default n so it wouldn't affect nRF as far as I can see.

What does it "mean" the SysTick having status "okay"? Does this mean the timer driver is actually used? If so, setting it as "okay" gives the wrong signal.

**Comment by mbolivar-nordic** [comment]
> @mbolivar CONFIG_CORTEX_M_SYSTICK indicates that the system timer is based on the SysTick.

Yep, for sure. 

> What does it "mean" the SysTick having status "okay"? Does this mean the timer driver is actually used? If so, setting it as "okay" gives the wrong signal.

It just means the hardware is available for use. In general we're moving towards drivers being automatically enabled if the subsystem is turned on and the right devicetree nodes have status "okay".

**Comment by ioannisg** [comment]
>In general we're moving towards drivers being automatically enabled if the subsystem is turned on and the right devicetree nodes have status "okay".

That's fair.

> Seems like we could just set it to "okay" in armv7-m.dtsi and add the appropriate Kconfig dependency.

@mbolivar-nordic what would be the appropriate Kconfig dependency? You mean something like:

```
config CORTEX_M_SYSTICK
    bool
    depends on "some DTS-macro indicating it is "status okay"
```
??

**Comment by mbolivar-nordic** [comment]
>     depends on "some DTS-macro indicating it is "status okay"

Yep. I've got a PR adding some potential ones here if the existing kconfigfunctions aren't sufficient:
https://github.com/zephyrproject-rtos/zephyr/pull/24794

**Comment by mbolivar-nordic** [comment]
Aha, I misread this. Actually, it's meant to be `default y if $(dt_<whatever>_enabled,<foo>)`, not `depends on`.

**Comment by ioannisg** [comment]
> Aha, I misread this. Actually, it's meant to be `default y if $(dt_<whatever>_enabled,<foo>)`, not `depends on`.

Then this is not so straightforward. That's because the SysTick DTS node is part of the SoC definition only, while the config CORTEX_M_SYSTICK is enabled at board level.

For your proposal to work we need to be setting the SysTick node to status = okay at the board DTS, for all boards (and only those boards) that are supposed to work with the SysTick.

@QSQCaito has a relevant comment about this.

> In general we're moving towards drivers being automatically enabled if the subsystem is turned on and the right devicetree nodes have status "okay".

I'll wait until you make this work for Nordic and the RTC driver; then I 'll revisit this issue.

**Comment by mbolivar-nordic** [comment]
> For your proposal to work we need to be setting the SysTick node to status = okay at the board DTS, for all boards (and only those boards) that are supposed to work with the SysTick.

Is that true?

Why can't we set a default to status 'okay' on the SoC level where the SoC expects most users to use systick, and then set it to status 'disabled' on a board specific basis if required?
