### ISSUE TITLE
Bluetooth: controller: legacy: Backport conformance test related changes

### ISSUE THREAD

**Issue by cvinayak** [zephyrproject-rtos/zephyr#25314]
**Describe the bug**
During conformance testing of v2.2-branch, numerous implementation fixes related to conformance test changes and failures were undertaken. These fixes are missing in legacy controller in v1.14-branch.

**To Reproduce**
Re-run conformance testing using hci_uart application in v1.14-branch

**Expected behavior**
Bluetooth Controller in v1.14-branch shall meet the same level of quality as v2.2-branch for a said Bluetooth v5.1 qualified design listing.

**Impact**
showstopper

**Screenshots or console output**
NA

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain Zephyr SDK
 - Commit SHA or Version used: v1.14.2

**Additional context**
backport PR #23091

**Comment by cvinayak** [comment]
This issue corresponds to #23091

**Comment by carlescufi** [comment]
@cvinayak does #23091 fix this issue?

**Comment by cvinayak** [comment]
> 
> 
> @cvinayak does #23091 fix this issue?

@carlescufi Yes.
