### ISSUE TITLE
Fails to compile when SYS_PM_DIRECT_FORCE_MODE is true

### ISSUE THREAD

**Issue by MZachmann** [zephyrproject-rtos/zephyr#25354]
**To reproduce:**
1. Use the sample samples\boards\nrf\system_off (or any other power oriented sample).
2. Change the prj.conf to add the line
   CONFIG_SYS_PM_DIRECT_FORCE_MODE=y
3. Try to build

**Produces the error:**
-c C:/z/zephyr/subsys/power/power.c
In file included from C:/z/zephyr/include/kernel_includes.h:41,
                 from C:/z/zephyr/include/kernel.h:17,
                 from C:/z/zephyr/include/zephyr.h:18,
                 from C:/z/zephyr/subsys/power/power.c:7:
C:/z/zephyr/subsys/power/power.c: In function 'sys_pm_force_power_state':
C:/z/zephyr/include/sys_clock.h:85:28: error: incompatible type for argument 1 of '_sys_suspend'
   85 | #define Z_TIMEOUT_TICKS(t) ((k_timeout_t) { .ticks = (t) })
…..
C:/z/zephyr/include/power/power.h:288:38: note: expected 's32_t' {aka 'int'} but argument is of type 'k_timeout_t' {aka 'struct <anonymous>'}
  288 | enum power_states _sys_suspend(s32_t ticks);
….      |                                ~~~~~~^~~~~
C:/z/zephyr/subsys/power/power.c:87:15: note: in expansion of macro 'K_FOREVER'
   87 |  _sys_suspend(K_FOREVER);

**Expected behavior:** build should succeed

So, the call to _sys_suspend is passing in K_FOREVER in power.c line 87 but _sys_suspend is expecting an s32_t ticks count not a k_timeout setting.

**Environment**: Windows 10 pro
Compiler: GNUARMEMB_TOOLCHAIN_PATH=C:\Program Files (x86)\GNU Tools ARM Embedded\9 2019-q4-major
Commit: 
commit d898ada917782289dbd5ceb6de70547189a141d0 (HEAD -> master, origin/master)
Author: Maureen Helm <maureen.helm@nxp.com>
Date:   Tue Apr 28 20:34:44 2020 -0500

Thanks.

**Comment by pabigot** [comment]
This was fixed by 04d1104ee51754193efb557d6d4d0d1d9452e965 which is in current master.
