### ISSUE TITLE
net: socket: socketpair: check for ISR context

### ISSUE THREAD

**Issue by cfriedt** [zephyrproject-rtos/zephyr#25417]
**Is your enhancement proposal related to a problem? Please describe.**
Blocking calls are not allowed in ISR context.

If `sock_is_nonblock()` returns false and `arch_is_in_isr()` returns true, any operation that `will_block` should return an error. If there is a more generic function than `arch_is_in_isr()`, then that should be used instead.

Really, ISR's are probably the wrong place to use socketpair IPC, but the implementation should be robust in that case as well.

**Describe the solution you'd like**
I can put together a patch and test.

**Describe alternatives you've considered**
Always return an error if any of the socketpair operations are called from isr context?

**Additional context**

**Comment by jukkar** [comment]
> If there is a more generic function than `arch_is_in_isr()`, then that should be used instead.

Yes there is, the `k_is_in_isr()` should be used here.
