### ISSUE TITLE
cf_set() returns 0 when no cfg is available

### ISSUE THREAD

**Issue by TTJO** [zephyrproject-rtos/zephyr#25447]
In gatt.c @ cf_set(), the function returns with success (0) when no cfg is available.

`	
        cfg = find_cf_cfg_by_addr(id, &addr);
	if (!cfg) {
		cfg = find_cf_cfg(NULL);
		if (!cfg) {
			BT_ERR("Unable to restore CF: no cfg left");
			return 0;
		}
	}
`

The function should probably return
`return -ENOMEM;`
when no cfg is available.

The impact on my progress is currently not assessed. Just found this bug as part of another bug-hunt.

**Comment by carlescufi** [comment]
@TTJO would you mind sending a PR? This is a trivial change and a good first Pull Request.

**Comment by TTJO** [comment]
Yes... I will do that
