### ISSUE TITLE
FRDM_K82F DTS missing information for ADC-0

### ISSUE THREAD

**Issue by paulvohs** [zephyrproject-rtos/zephyr#25468]
To my understanding, in order to enable a CPU feature that is disabled by default, an entry of the form 
&feature {
    status="okay"
}; 
must be added into the board DTS. I added this to enable ADC functionality to the FRDM_K82F DTS and it failed to compile. 

A coworker of mine figured out that there is a missing
#io-channel-cells = <1>;
in the file zephyr/dts/arm/nxp/nxp_k8x.dtsi. I am not sure if this is a bug or intended behavior.

1. Add the following to zephyr/boards/arm/frdm_k82f/frdm_k82f.dts:
&adc0 {
    status = "okay";
};
2. Build any sample project with -b frdm_k82f.
3. See attached screenshot of error output.
![Screen Shot 2020-05-19 at 5 36 56 PM](https://user-images.githubusercontent.com/50847232/82392052-c045e780-99f7-11ea-909e-c28e0ec2d6b0.png)

I believe this is something that needed to be included in the FRDM_K82F DTS but was not, though I am unsure.

This is an important issue for anyone planning to utilize the ADC on the Freedom K82F board.

- OS is Ubuntu 18.04.4 VM running on Mac OS X
- Toolchain is Zephyr with Ninja
- Commit SHA is ed2d263e0c233df015448de8d45a0fae359afc8b

**Comment by carlescufi** [comment]
@paulvohs enabling a feature is done through a combination of Devicetree and Kconfig. The particular error you are getting doesn't ring a bell but I am sure that @MaureenHelm or @galak will be able to point you to the right direction.

**Comment by MaureenHelm** [comment]
Yes, this is a bug in the soc device tree. The dts fix is easy, but I'd like to also enable `tests/drivers/adc/adc_api` for this board while we're here. I can work up a PR, but I don't have access to the hardware right now so I'll need your help to test it.
