### ISSUE TITLE
UART input does not work on mps2_an{385,521}

### ISSUE THREAD

**Issue by stephanosio** [zephyrproject-rtos/zephyr#25601]
**Describe the bug**
UART input does not work on `mps2_an385` and `mps2_an521` boards (in QEMU).

For example, the tests and samples that rely on the UART input functionality such as `drivers/uart/uart_basic_api` and shell are unable to accept any user input.

**To Reproduce**
In QEMU, run any tests and samples that require user input through the UART interface such as:

* drivers/uart/uart_basic_api
* samples/subsys/shell/shell_module

**Expected behavior**
UART user input is echo-ed on the input prompt.

**Impact**
Board usability is limited

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04
 - Toolchain: Zephyr SDK 0.11.2
 - Commit SHA: 855b6c1a5ded091003d96a7b8d2b81662edbef70

**Additional context**
Broken UART driver suspected

Also reproducible in H/W (see https://github.com/zephyrproject-rtos/zephyr/issues/25601#issuecomment-634267494).

**Comment by carlescufi** [comment]
Removing the priority, we will go through it later today.

**Comment by galak** [comment]
@microbuilder can you try one of these tests/samples on a real MPS2 to see if this shows up on real HW as well.

**Comment by microbuilder** [comment]
Repeatable on actual HW as well (UART input also doesn't work, output from AN521 -> USB Serial does work fine, as is the case with QEMU).
