### ISSUE TITLE
smp_svr fails for nrf5340

### ISSUE THREAD

**Issue by hakonfam** [zephyrproject-rtos/zephyr#25652]
[placeholder for proper bug report when I have time]

Message is incorrectly split when transferring image in `smp_svr` for nRF5340

Perform FOTA for smp_svr using nRF Connect on iOS

The mcumgr response should be sent as a fragmented L2CAP-messag, instead it is split up.

See filenames in wireshark trace for relevant packets.

[trace.zip](https://github.com/zephyrproject-rtos/zephyr/files/4687442/trace.zip)

**Comment by joerchan** [comment]
@hakonfam There is a possible fix here: https://github.com/zephyrproject-rtos/zephyr/pull/26018
Could you give it a try? Or update placeholder :)

**Comment by hakonfam** [comment]
The fix did not affect this issue. Placeholder remains unchanged ;)

**Comment by joerchan** [comment]
@hakonfam Will you have time soon to update the bug-report?
