### ISSUE TITLE
lib: updatehub: Corrupted updated when receiving CoAP duplicate packages

### ISSUE THREAD

**Issue by otavio** [zephyrproject-rtos/zephyr#25704]
The updatehub library is not properly handling the case where the CoAP packages are duplicated and we end flashing a broken firmware on the device's storage.

The short term solution is to have an engine that handles these packages reception and ensures we handle the proper sequence of blocks.

**Comment by hwilmers** [comment]
There is a mechanism to avoid duplicate packages proposed in PR #25558

**Comment by nandojve** [comment]
This was addressed on #25603, #25683 and #26093.
