### ISSUE TITLE
[lpcxpresso55s69_cpu1] no applications and build guide, hello world can not build

### ISSUE THREAD

**Issue by hakehuang** [zephyrproject-rtos/zephyr#25833]
**Describe the bug**
lack supporting information for lpcxpresso55s69_cpu1

**To Reproduce**
if using hello world
1. mkdir build; cd build
2. cmake -DBOARD=lpcxpresso55s69_cpu1 ..
3. make
4. see error

**Expected behavior**
expect to have cpu1 core application guide

**Impact**
lpcxpresso55s69_cpu1 core can not demo

**Screenshots or console output**
```
warning: TRUSTED_EXECUTION_NONSECURE (defined at arch/Kconfig:174) was assigned the value 'y' but
got the value 'n'. Check these unsatisfied dependencies: ARCH_HAS_TRUSTED_EXECUTION (=n). See
http://docs.zephyrproject.org/latest/reference/kconfig/CONFIG_TRUSTED_EXECUTION_NONSECURE.html
and/or look up TRUSTED_EXECUTION_NONSECURE in the menuconfig/guiconfig interface. The Application
Development Primer, Setting Configuration Values, and Kconfig - Tips and Best Practices sections of
the manual might be helpful too.

-- The C compiler identification is GNU 9.2.0
-- The CXX compiler identification is GNU 9.2.0
-- The ASM compiler identification is GNU
-- Found assembler: /home/ubuntu/zephyr-sdk/arm-zephyr-eabi/bin/arm-zephyr-eabi-gcc
-- Cache files will be written to: /home/ubuntu/.cache/zephyr
-- Configuring done
CMake Error at ../../cmake/extensions.cmake:372 (add_library):
  No SOURCES given to target: drivers__gpio
Call Stack (most recent call first):
  ../../cmake/extensions.cmake:349 (zephyr_library_named)
  ../../drivers/gpio/CMakeLists.txt:3 (zephyr_library)

```

**Environment (please complete the following information):**
 - OS: ( Linux,)
 - Toolchain (e.g Zephyr SDK, ...)
 - v2.3.0-rc1

**Comment by agansari** [comment]
https://docs.zephyrproject.org/latest/boards/arm/lpcxpresso55s69/doc/index.html#supported-features

> Targets available for this board are:
>  - lpcxpresso55s69_cpu0 secure (S) address space for CPU0
>  - lpcxpresso55s69_ns non-secure (NS) address space for CPU0
>  - lpcxpresso55s69_cpu1 CPU1 target, NS only
> 
> **CPU1 does not work without CPU0 enabling it.**

**Comment by agansari** [comment]
It can work similar to how LPC54114's dual core works

**Comment by hakehuang** [comment]
I can not find any more details steps on how to use cpu1 core.
