### ISSUE TITLE
Where is the definition of SystemInit()?

### ISSUE THREAD

**Issue by zzzh** [zephyrproject-rtos/zephyr#25863]
In soc/arm/nordic_nrf/nrf52/soc.c, there's a SystemInit(), which I can't find any definition in files under zephyr folder.
So, where's the definition of it?

**Comment by stephanosio** [comment]
Try https://github.com/zephyrproject-rtos/hal_nordic

**Comment by zzzh** [comment]
Found it in hal_nordic, cool.
Thank you, stephanosio.
