### ISSUE TITLE
2.3: Missing release notes

### ISSUE THREAD

**Issue by carlescufi** [zephyrproject-rtos/zephyr#25869]
- [x] Overview: @carlescufi 
- [x] Kernel: @andrewboie @andyross @nashif 
- Architectures
  - [x] ARC: @ruuddw , @vonhust 
  - [x] POSIX: @aescolar 
  - [x] x86: @andrewboie @andyross @nashif 
- Drivers and sensors @MaureenHelm #25949
  - [x] CAN
  - [x] Console
  - [x] Display
  - [x] Entropy
  - [x] Hardware Info
  - [x] I2S
  - [x] Interrupt Controller
  - [x] IPM
  - [x] Keyboard Scan
  - [x] LED: @mbolivar-nordic 
  - [x] Pinmux
  - [x] PS/2
  - [x] Sensors
  - [x] Timer
  - [x] Video
- [x] Bluetooth: @carlescufi 
- [x] Build and infrastructure: @tejlmand 
- Libraries and subsystems
  - [x] Random @carlescufi 
- [x] Documentation: @carlescufi 
- [x] Tests and samples: @nashif @PerMac

**Comment by mbolivar-nordic** [comment]
>  LED: @mbolivar-nordic

There are just API conversions for DT and timeouts in these since 2.2. Is it worth writing into the release notes?
