### ISSUE TITLE
legacy timeout API does not work as expected

### ISSUE THREAD

**Issue by pabigot** [zephyrproject-rtos/zephyr#25887]
With `CONFIG_LEGACY_TIMEOUT_API=y` this:
```
void main(void)
{
	printk("Hello World! %s\n", CONFIG_BOARD);
	k_sleep(K_SECONDS(3));
	printk("post 3 s at uptime %u \n", k_uptime_get_32());
	k_sleep(K_MSEC(30));
	printk("post 30 ms at uptime %u\n", k_uptime_get_32());
	k_sleep(K_USEC(3));
	printk("post 3 us at uptime %u \n", k_uptime_get_32());
	k_sleep(K_NSEC(3));
	printk("post 3 ns at uptime %u \n", k_uptime_get_32());
}
```
prints
```
*** Booting Zephyr OS build v2.3.0-rc1-399-g394ff7a28b6b  ***
Hello World! nrf52840dk_nrf52840
post 3 s at uptime 3007 
post 30 ms at uptime 3039
post 3 us at uptime 6041 
```
and presumably would print
```
post 3 ns at uptime 3006041
```
if I waited long enough.

**Comment by andyross** [comment]
K_USEC and K_NSEC are new macros, they didn't exist for legacy code so I don't undertand filing a bug report against them.  Is there old code that's going to break because the new macros don't honor old units correctly?

**Comment by andyross** [comment]
For clarity: I mean, if you want you can stick those macros inside an "#ifndef CONFIG_LEGACY_TIMEOUT_API".  I just don't see the point.

**Comment by pabigot** [comment]
Sure, but it's obviously confusing or we wouldn't have gotten that question on slack.  Making it work as expected seems trivial.

**Comment by andyross** [comment]
I'd definitely prefer to wall off the new APIs from legacy usage vs. trying to add code to a legacy mode.  Making it work "right" only perpetuates a mode we're trying to deprecate.  The simple answer for anyone trying to do this (i.e. mix legacy mode with the new units) is "don't".
