### ISSUE TITLE
devicetree: support generating symbols for -gpios properties w/o compatible

### ISSUE THREAD

**Issue by pabigot** [zephyrproject-rtos/zephyr#25945]
A recent change to devicetree tooling allowed generation of nodes for which there was no `compatible`, but that generation did not include any properties on such nodes (which I still think is weird).

Do we have enough special-casing in the tooling to support something like:
```
/ {
  app {
    power-gpios = <&gpioa 5 GPIO_ACTIVE_HIGH>;
  };
};
```
then look it up by `DT_PATH(app, power_gpios)`?  At least for GPIO we can reasonably say that if the property ends in `-gpios` we can assume it's a GPIO phandle+specifier.  @galak?

_Originally posted by @pabigot in https://github.com/zephyrproject-rtos/zephyr/pull/25596_

**Comment by pabigot** [comment]
From https://github.com/zephyrproject-rtos/zephyr/pull/24769#pullrequestreview-402765100 re converting other properties where the corresponding representation can be inferred w/o recourse to a binding would be useful: 
I added these to `/`:

```
       special = "this";
       subspecial {
          bar = "that";
       };
```

The subordinate node was generated, but neither `/special` nor `/subspecial/bar` were generated

Is that what was intended?  Generating the node without its properties seems odd; will this satisfy the need identified in https://github.com/zephyrproject-rtos/zephyr/pull/24460#discussion_r414774455

**Comment by pabigot** [comment]
Also needed for things like:

    servo-pwms = <&pwm0 17>;

per a slack discussion.

**Comment by sslupsky** [comment]
Yeah, I ran into this issue a while ago too.  This would be useful.

**Comment by pabigot** [comment]
This keeps coming up.  @galak Do you have fundamental objections to this that will prevent us from implementing it, or can we proceed?

@mbolivar-nordic It would probably be more efficient for you to do this, but if you're fully booked I'm willing to take it on.

**Comment by mbolivar-nordic** [comment]
I don't think I'll have cycles for this anytime soon

**Comment by carlescufi** [comment]
API meeting 4th August 2020

- The functionality in itself is welcome by most
- The namespace is however under debate:
  - Arbitrary namespace (`app`. `mygpios`, etc): not gathering any support
  - Fixed namespace (`zephyr-aux`, `zephyr-app`, `zephyr-user`). The tooling can then limit the generation of these (nodes without a compatible) when they are under the fixed namespace: `/zephyr,user/<user-chosen-name>-{gpios, pwms, ..} `
- The use of these nodes should be limited to samples/tests but not drivers
- The use of `chosen` for this does not seem to match the original intent of `chosen` in Zephyr (limited set of known chosen nodes)

**Comment by carlescufi** [comment]
This proposal would effectively replace the one in #18544
