### ISSUE TITLE
Bluetooth: Scanning + Non-connectable advertising broken on nRF5340

### ISSUE THREAD

**Issue by trond-snekvik** [zephyrproject-rtos/zephyr#25942]
Non-connectable advertising fails if scanning is already enabled on the nRF5340. It does not provide any error messages, but advertising never starts. Removing the call to `bt_le_scan_start` fixes the issue. Changing to connectable advertising also fixes the issue. The problem is the same regardless of whether advertising or scanning is started first.

The behavior is only observable on the open source split LL Nordic controller, not the Nordic proprietary controller. 

**To Reproduce**
Flash samples/bluetooth/scan_adv on the app core (`nrf5340pdk_nrf5340_cpuapp`) and samples/bluetooth/hci_rpmsg on the net core (`nrf5340pdk_nrf5340_cpunet`). The device is supposed to advertise with a 100ms interval, but doesn't. Remove the call to `bt_le_scan_start`, and it starts working. The expected behavior can be observed if the sample is flashed on an nRF52832 DK.

Tested on latest master and v2.2.0 tag. Same behavior on both.

**Impact**
This is a showstopper for the Bluetooth Mesh on nRF5340, which relies heavily on these two features being combined.

**Comment by trond-snekvik** [comment]
cc @carlescufi @joerchan

**Comment by cvinayak** [comment]
Root cause and fix mentioned in #26018.
