### ISSUE TITLE
Need root LICENSE files in hal_stm32 module

### ISSUE THREAD

**Issue by jettr** [zephyrproject-rtos/zephyr#25979]
**Describe the bug**
The https://github.com/zephyrproject-rtos/hal_stm32 repository does not have a root LICENSE file. Most, but not all of the source files within the repository have license information.

**Impact**
 This is blocker to locally replicating this repository for builds.

**Comment by erwango** [comment]
@jettr, Txs for reporting this issue.
I'm not sure how we can fix this, more explicitly I'm not sure what should a root LICENSE file contain in case of a module like hal_stm32.

Here is the status of the package:
Most of the files (the ones coming from cube packages) are BSD-3 Licensed in this module, when this is not the case, they are:
-CMake related files (some of them being Apache 2.0, few not licensed)
-2 python scripts (ST Copyright, missing Apache 2.0 that should be added)
-README (not licensed)

What can be done easily is to update the CMake and python scripts to Apache 2.0.
I don't think there is a need to do anything on README.

Once this is done:
- is the root License file still required ?
- What could it mention knowing that the module contains mix of BSD3 and few Apache 2.0  ?

cc @MaureenHelm, as it seems more modules could be impacted

**Comment by jettr** [comment]
I am talking with our internal teams on which potential solution would work best. I will let you know when I hear back. Thank you for responding so quickly!

**Comment by MaureenHelm** [comment]
> cc @MaureenHelm, as it seems more modules could be impacted

@ioannisg Can you add this to the list of items to consider for module repos?

**Comment by ioannisg** [comment]
@MaureenHelm I think we already have a discussion item for license files and license checks.
Will make sure we discuss this soon.

**Comment by jettr** [comment]
Is there any update on this? This is blocking our forward progress on replicating our needed Zephyr dependencies and building it in an official way.

Do we have an estimate on when we think we can resolve this for the stm32 repository?

**Comment by erwango** [comment]
@jettr sorry for the delay, we'll try to get this fixed by next week.

**Comment by jettr** [comment]
Thank you! I really appreciate it!

**Comment by jettr** [comment]
Do we have an idea of how we are going to fix this with a potential timeline? This really is blocking us.

**Comment by erwango** [comment]
@jettr, please have a look to https://github.com/zephyrproject-rtos/hal_stm32/pull/61 and provide feedback

**Comment by jettr** [comment]
I can't add my feedback on that pull request (I don't think I have permissions to leave a comment). It looks like it will be okay, but I am getting it reviewed internally just to make sure I am not missing anything. I will let you know soon. Thank you!
