### ISSUE TITLE
tests/net/socket/select failed on sam_e70_xplained board.

### ISSUE THREAD

**Issue by chen-png** [zephyrproject-rtos/zephyr#25990]
**To Reproduce**
1. west build -b sam_e70_xplained -p auto tests/net/socket/select
2. west flash
3. See error

**Screenshots or console output**

*** Booting Zephyr OS build v2.3.0-rc2  ***
Running test suite socket_select

starting test - test_fd_set
PASS - test_fd_set

starting test - test_select
E: 0x00000000 is not a valid NET_SOCKET
E: address is not a known kernel object
E: 0x00000000 is not a valid NET_SOCKET
E: address is not a known kernel object
**Assertion failed at WEST_TOPDIR/zephyr/tests/net/socket/select/src/main.c:160: test_select: (k_uptime_get_32() - tstamp <= FUZZ is false)
FAIL - test_select**

Test suite socket_select failed.

PROJECT EXECUTION FAILED

**Environment (please complete the following information):**
 - OS: Fedora28
 - Toolchain: Zephyr-sdk-0.11.3
 - Commit ID: v2.3.0-rc2

**Comment by ABOSTM** [comment]
The same for STM32 boards.
It looks like a regression introduced by #25804

**Comment by dleach02** [comment]
@andrewboie , this is being traced back to your PR
