### ISSUE TITLE
RFC: API Change: Bluetooth Mesh

### ISSUE THREAD

**Issue by LingaoM** [zephyrproject-rtos/zephyr#26037]
## Problem Description
Before each model can only store a single information, there are constraints in the application.

## Proposed Change (detailed)
`bt_mesh_model_data_store`  add `name` params to store as key-value pairs.
`bt_mesh_model_cb::settings_set` add `name` params to store as key-value pairs.

**Comment by carlescufi** [comment]
No objections.
