### ISSUE TITLE
sanitycheck reports failing tests with timeout as passing

### ISSUE THREAD

**Issue by yingmingx** [zephyrproject-rtos/zephyr#26065]
**Describe the bug**
When I test an example in the directory "samples/hello_world", I changed the regex in sample.yaml file. For example, change as follows:
-        - "Hello World! (.*)"
+        - "intel shanghai! (.*)"
this means the regex does not match the character string which should be print in main.c, after I run the sanitycheck tool, it passed without report errors.
This situation also happened when I changed the samples/hello_world/src/main.c  without changed the sample.yaml.

**To Reproduce**
1. open samples/hello_world/sample.yaml
2. change as follows:
-        - "Hello World! (.*)"
+        - "intel shanghai! (.*)"
3. sanitycheck -p qemu_x86 -T samples/hello_world/

**Comment by yingmingx** [comment]
Steven Wang is busy these days，please others help to take a look at this problem, thanks.

**Comment by nashif** [comment]
introduced in 7ec57b4666c6b724ce4b349fab10884a6fb05929 <-- @wentongwu

**Comment by andrewboie** [comment]
Upgrade to high. This may let code get merged which actually breaks the build.
