### ISSUE TITLE
Requirements.txt pip version conflict

### ISSUE THREAD

**Issue by Kreijstal** [zephyrproject-rtos/zephyr#26095]
**Describe the bug**
What have you tried to diagnose or workaround this issue?
There is a version conflict with pip
**To Reproduce**
```
sudo apt install --no-install-recommends git cmake ninja-build gperf \
  ccache dfu-util device-tree-compiler wget \
  python3-dev python3-pip python3-setuptools python3-tk python3-wheel xz-utils file \
  make gcc gcc-multilib g++-multilib libsdl2-dev
west init zephyrproject
cd zephyrproject
west update
west zephyr-export
pip3 install -r ./zephyr/scripts/requirements.txt
```
and then you get error

**Expected behavior**
installing requirements.txt should be a smoother experience.

**Impact**
What impact does this issue have on your progress (e.g., annoyance, showstopper)
well, it's annoying if you have to fix it by hand.

**Screenshots or console output**
If applicable, add a screenshot (drag-and-drop an image), or console logs
(cut-and-paste text and put a code fence (\`\`\`) before and after, 
to help
explain the issue.
![image](https://user-images.githubusercontent.com/2415206/84230208-bccfe880-aaeb-11ea-9817-93eafa2d368b.png)

**Environment (please complete the following information):**
Ubuntu 18.04.3 LTS

**Comment by carlescufi** [comment]
I just ran this now on a clean virtual environment and it worked fine, and installed Sphinx 2.4.4. This might well be something in your existing Python packages that is forcing an older Sphinx version. 
Please try with a clean virtual environment or check other packages that you might have installed previously and that might be forcing an older Sphinx version.

Also, you probably want to use `--user` on Linux when invoking `pip3`, as documented.
