### ISSUE TITLE
Asynchronous input via UART

### ISSUE THREAD

**Issue by biwecka** [zephyrproject-rtos/zephyr#26104]
I'm currently experimenting with UART on a nRF52840 (on an Arduino Nano 33 BLE Sense) and wonder how I can archieve the following two connections side by side.

1. Logging/printing things to the connected computer.
2. Make settings via console inputs to control the main program.

Until now I got an input and output connection working with these settings in my prj.conf file:
```
# GPIO
CONFIG_GPIO=y

# Enable console functionality
CONFIG_CONSOLE_SUBSYS=y
CONFIG_CONSOLE_GETLINE=y

# Enable USB+UART functionality
CONFIG_USB=y
CONFIG_USB_DEVICE_STACK=y
CONFIG_USB_DEVICE_PRODUCT="Arduino Nano 33 BLE Sense"
CONFIG_USB_UART_CONSOLE=y
CONFIG_USB_UART_DTR_WAIT=y

#CONFIG_UART_INTERRUPT_DRIVEN=y
CONFIG_UART_LINE_CTRL=y
CONFIG_UART_CONSOLE_ON_DEV_NAME="CDC_ACM_0"
```
With these settings I was able to simply send strings to the computer with "printk" and receive inputs from the computer with "console_getline".
My problem with that is, that the program won't start until I connect to the Arduino's UART with my computer (e.g. with Putty).

Is it even possible to start the program execution independent of an established UART connection? Do I need two UART connections for 1. and 2.? What is the best way to retrieve the commands via UART in an asynchronous way, to not interrupt the main program?

I'm thankful for any help.

**Comment by carlescufi** [comment]
I am unclear about what you are trying to achieve @biwecka. Do you have a physical UART at all, or only a CDC ACM one?

**Comment by biwecka** [comment]
It's only UART over USB, so a CDC ACM one.
What I try to archieve: The main program runs and logs things to my computer. Independend from that I also want to send input (commands) to the Arduino, which change the behaviour of the main program (e.g. change the log level or show the program status via the LEDs).

**Comment by carlescufi** [comment]
I see, so you want a CDC ACM UART to be able to log to your computer but at the same time be able to receive data from the same computer and act on it.
I am not sure if it's possible to use the RX path of the logging UART, @nordic-krch ?

**Comment by nordic-krch** [comment]
in theory nothing prevents you from reading from the same uart as one used for logging/console. However, I recommend to check out `shell` as it might be exactly what you are looking for.

**Comment by emob-nordic** [comment]
I think You can have a look into [this PR](https://github.com/zephyrproject-rtos/zephyr/pull/26122). It adds possibility to route shell through CDC_ACM.

**Comment by bpbradley** [comment]
> My problem with that is, that the program won't start until I connect to the Arduino's UART with my computer (e.g. with Putty).

For this, if I understand correctly, I believe you should be able to resolve that with `CONFIG_USB_UART_DTR_WAIT=n`

**Comment by biwecka** [comment]
> For this, if I understand correctly, I believe you should be able to resolve that with CONFIG_USB_UART_DTR_WAIT=n

When I set CONFIG_USB_UART_DTR_WAIT to "n" (or omit it completely) the Arduino doesn't show up as serial device anymore.

**Comment by jfischer-phytec-iot** [comment]
> When I set CONFIG_USB_UART_DTR_WAIT to "n" (or omit it completely) the Arduino doesn't show up as serial device anymore.

Zephyr RTOS version? Please try v2.3

**Comment by biwecka** [comment]
I'm using Nordic's nrfconnect/sdk-nrf version 1.3.0-rc3 which currently uses Zephyr v2.3.0-rc1-ncs1-rc3.

**Comment by jfischer-phytec-iot** [comment]
DTR WAIT issue was fixed by https://github.com/zephyrproject-rtos/zephyr/pull/25894/commits/ad018b9f663259b006dff8f5d1a2a5e93999cd3a

**Comment by biwecka** [comment]
Thank you for this information. The commit ad018b9 is not included yet in Nordic's downstream of Zephyr, so I'll have to change it myself.
