### ISSUE TITLE
Bluetooth: controller: nRF5x: refactor radio_nrf5_ppi.h

### ISSUE THREAD

**Issue by kruithofa** [zephyrproject-rtos/zephyr#26118]
**Is your enhancement proposal related to a problem? Please describe.**
The conditional compilation makes the code more difficult to read/understand.
There is also inconsistency in the functionality for the routine 'hal_radio_switch_disable()', in radio_nrf5_ppi.h lines 454 vs. 1268 

**Describe the solution you'd like**
- Split the nrf5_ppi.h in 2 files for improved readability
- Make the different routines consistent

**Describe alternatives you've considered**
[None]

**Additional context**
See PR #26019

**Comment by cvinayak** [comment]
Fixed in https://github.com/zephyrproject-rtos/zephyr/pull/30732
