### ISSUE TITLE
Extend the sensor API with function for getting the value of a sensor attribute

### ISSUE THREAD

**Issue by henrikbrixandersen** [zephyrproject-rtos/zephyr#26167]
## Introduction

The Zephyr sensor API currently allows for setting attributes for sensor channels, but no way of retrieving the value of a sensor attribute.

### Problem description

Extend the sensor API with function for getting the value of a sensor attribute. Sensor attributes should not be write-only, as they provide means for exposing sensor-specific settings that might be of interest for the calling application (calibration values, limits, ...).

### Proposed change

Add a new, optional API function for retrieving the value of a sensor attribute.

### Proposed change (Detailed)

Please see PR #26166.

### Dependencies

None.

### Concerns and Unresolved Questions

None.

## Alternatives

Each sensor could implement a sensor-specific API for retrieving the values of sensor attributes.

**Comment by carlescufi** [comment]
Cc @MaureenHelm @gmarull
