### ISSUE TITLE
icount support for qemu_arc_{em,hs}

### ISSUE THREAD

**Issue by andrewboie** [zephyrproject-rtos/zephyr#26227]
**Is your enhancement proposal related to a problem? Please describe.**
The `qemu_arc_em` and `qemu_arc_hs` targets aren't using icount. This causes timing sensitive tests to intermittently fail.

**Describe the solution you'd like**
icount enabled in QEMU command line arguments for `qemu_arc_em` and `qemu_arc_hs`, as we have done on most other arches.

My understanding is that some issues in upstream QEMU must be resolved for the ARC port in order for this to happen.

**Comment by stephanosio** [comment]
NOTE/EDIT: This issue is applicable to both `qemu_arc_em` and `qemu_arc_hs`.

**Comment by nashif** [comment]
closed by #31550
