### ISSUE TITLE
bluetooth: controller: Cannot receive long packets

### ISSUE THREAD

**Issue by rugeGerritsen** [zephyrproject-rtos/zephyr#26252]
**Describe the bug**
When running the NCS throughput sample with SoftDevice LL as master and Zephyr LL as slave, the connection drops after the master starts transmitting long packets.

**To Reproduce**
Checkout NCS v1.3.0-rc3
Run throughput sample on two nrf52 devkits.
Configure the SoftDevice LL to be master, Zephyr LL to be slave

**Expected behavior**
The Zephyr LL should be able to receive long packets.

**Impact**
Showstopper. It annoys the user because it initially looks like it is the SoftDevice LL which is misbehaving. 

**Screenshots or console output**
Entire sequence:
![image](https://user-images.githubusercontent.com/23234783/84919292-0a3aef80-b0c2-11ea-8766-f03083db0339.png)

The screenshot below shows pin toggles on RADIO_READY and RADIO_DISABLED for both the master and slave. You can see that the Zephyr LL toggles multiple times during the packet sent from the master.
![image](https://user-images.githubusercontent.com/23234783/84919025-ae706680-b0c1-11ea-8877-b930b96db805.png)

**Environment (please complete the following information):**
 - OS: Windows
 - Toolchain: gnuarmemb, 8 2019 q3
 - Commit SHA or Version used: NCS v1.3.0-rc3

**Comment by rugeGerritsen** [comment]
@cvinayak , @kruithofa FYI

**Comment by cvinayak** [comment]
@rugeGerritsen if you have the sniffer logs, upload here if the size is permitted, else by other means.

**Comment by rugeGerritsen** [comment]
@cvinayak. Here are two sniffer logs. One for the default configuration and one for the case where only 1M PHY is used
[ThroughputSampleFails.zip](https://github.com/zephyrproject-rtos/zephyr/files/4796669/ThroughputSampleFails.zip)

**Comment by cvinayak** [comment]
I have identified the bug in Zephyr LL control procedure handling of unknown rsp. I will send a fix as soon as I can get back to work.
