### ISSUE TITLE
Zephyr os bluetooth peripheral example indication. When i flash code to my board custom configuration for indication will shown and after i click button for indication it device will disconnect from phone. My board is nrf52832.

### ISSUE THREAD

**Issue by athulvalsanvp** [zephyrproject-rtos/zephyr#26265]
I am using custom characteristic for indication. But its not working.

**Comment by cvinayak** [comment]
Please provide board details, sample or the modified application used, build details, how to reproduce, screenshots and console logs (preferrably please use the github issue template that was presented when you created this issue).

**Comment by athulvalsanvp** [comment]
![Screenshot_20200619-072544__01](https://user-images.githubusercontent.com/67083981/85088757-7c185380-b1fe-11ea-9492-497b47fced5a.jpg)
![Screenshot_20200619-072620__01](https://user-images.githubusercontent.com/67083981/85088770-82a6cb00-b1fe-11ea-8676-a31a873ce175.jpg)
Board: nrf52832.
Modified Example: bluetooth/peripheral
From center device(phone) i can see indication characteristics . When i click button for indication. It shows Device disconnected and also shows error 22

**Comment by carlescufi** [comment]
Please send an email to the mailing list of contact us on Slack for code-related questions.
