### ISSUE TITLE
Cast and shift operator priority issue may lead to wrong memory size result in fat_fs example

### ISSUE THREAD

**Issue by rick1082** [zephyrproject-rtos/zephyr#26266]
**Describe the bug**
In fat_fs example, if we choose a large size SD card to connect with, the result of memory size calculation coule be wrong due to the missing brace for manipulating operator priority.
E.g., if we run the example with a 16GB SDHC card, the print out memory size is 2799 MB which is wrong. 
This is because in this [line](https://github.com/zephyrproject-rtos/zephyr/blob/zephyr-v2.3.0/samples/subsys/fs/fat_fs/src/main.c#L62), we should do shift operation first, and then cast with uint32_t.
However, the current code will do cast first and then do shift, which may cause the result overflowed.

**To Reproduce**
1. Prepare a nRF52840-DK, and connect with a 16GB SD card
2. west build -b nrf52840dk_nrf52840 zephyr/samples/subsys/fs/fat_fs
3. west flash
4. check the "Memory Size" print out in serial terminal

**Expected behavior**
E.g. For my 16 GB SDHC card, the sector size is 512 KB, and the block count is 30898176.
The memory size should be 512 * 30898176 = 15819866112 bytes
Which is 15087 MB.
But since there's no brace in the issue line, the code will do cast first then shift.
So result is 2552 MB, which is wrong.

**Impact**
When using large size SD card (>4GB), the print memory size is wrong

**Additional context**
The fix could be 
```
-printk("Memory Size(MB) %u\n", (u32_t)memory_size_mb>>20);
+printk("Memory Size(MB) %u\n", (u32_t)(memory_size_mb>>20));
```

**Comment by carlescufi** [comment]
@rick1082 thanks for the report. Would you mind sending a Pull Request to fix this?
