### ISSUE TITLE
Question: Does NRF52840-DK support both OpenThread and BLE at the same time

### ISSUE THREAD

**Issue by zhanglongxia** [zephyrproject-rtos/zephyr#26281]
Hi,

I'm planing to use the zephyr BLE  as one link interface of OpenThread, so that OpenThread needs to support 802.15.4 and BLE radio at the same time. However, NRF52840 only has one hardware radio module on it. Nordic enabled [multiprotocol](https://www.nordicsemi.com/Products/Low-power-short-range-wireless/Multiprotocol-2_0) function in nRF5 SDK to resolve this issue.
 
I want to know if the zephyr supports both OpenThread and BLE at the same time on nRF52840?

Thank you

**Comment by carlescufi** [comment]
No, it does not. If you want multiprotocol support please use [nRF Connect SDK](https://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/nrf/index.html), which is based on Zephyr.
