### ISSUE TITLE
drivers: ieee802154: cc13xx_cc26xx: adopt hal/ti rf driverlib

### ISSUE THREAD

**Issue by cfriedt** [zephyrproject-rtos/zephyr#26312]
**Is your enhancement proposal related to a problem? Please describe.**
The ti hal rf driverlib and driver portability layer (dpl) likely contains most of what is necessary to support ieee 802.15.4 in Zephyr on the cc13xx_cc26xx platform.

It might be advantageous to consider adopting the rf driverlib api so that there is api commonality a vendor-supported hardware api.  

Other benefits:
* less code duplication
* multi-band / multi-mac operation with ble

**Describe the solution you'd like**
Refactor some common low-level / ti register apis with rf driverlib calls.

**Describe alternatives you've considered**
Just never doing that, and how it would be missing out on multi-mode operation.

**Additional context**

**Comment by vanti** [comment]
@cfriedt Just to be clear, I think you meant the TI HAL's `RF driver `(the API defined in hal/ti/simplelink/source/ti/drivers/rf/RF.h) as opposed to `driverlib`, which is the package located under hal/ti/simplelink/source/ti/devices/cc13x2_cc26x2/driverlib - a library that gives low-level access to peripheral registers that Zephyr's ieee 802.15.4 driver is already relying on today.

**Comment by cfriedt** [comment]
@vanti - yes, that's right, sorry.

**Comment by cfriedt** [comment]
Going to get this moving again.

**Comment by cfriedt** [comment]
Also blocks #21631
