### ISSUE TITLE
disco_l475_iot1: flash storage corruption caused by partition overlap

### ISSUE THREAD

**Issue by hwilmers** [zephyrproject-rtos/zephyr#26413]
**Describe the bug**

On disco_l475_iot1, the flash partition "storage" gets corrupted by mcuboot when an image swap is performed.

The cause of the problem is that in the devicetree for disco_l475_iot1, the flash partitions "storage" and "image-scratch"
have overlapping address spaces:
https://github.com/zephyrproject-rtos/zephyr/blob/979e124e21fb05cfedf8ed12078983d40e2f0b6c/boards/arm/disco_l475_iot1/disco_l475_iot1.dts#L173-L181

**To Reproduce**

1. build following sample: net/updatehub
2. perform an OTA firmware update
3. wait for system restart

**Expected behavior**

It is expected that after the firmware update, the original contents of partition "storage" are still intact.

**Impact**

This is preventing a usage of storage partition accross system updates.

**Environment**
 - Zephyr Version 2.3.0

**Comment by hwilmers** [comment]
See #26417 for a proposed bugfix.

**Comment by nandojve** [comment]
CC @mtahirbutt @otavio
