### ISSUE TITLE
LPSPI support for i.MX RT106x

### ISSUE THREAD

**Issue by leokrueger** [zephyrproject-rtos/zephyr#26428]
**Is your feature request related to a problem? Please describe.**
When checking the documentation as well as compiling and running samples for the mimxrt1064_evk board, we noticed that LPSPI is not supported for this board/mcu. The same holds for the (feature equivalent apart from mcu internal flash) mimxrt1060_evk board. However, it seems that the earlier mimxrt1050_evk supports LPSPI. From the documentation this part of the mcu at least seems to be similar to the 106x.

Is there any particular reason the mimxrt106x_evk currently lacks this feature apart from that no one has yet worked on it?

**Describe the solution you'd like**
We would like to have LPSPI supported out of the box on mimxrt106x_evk by Zephyr :)

**Describe alternatives you've considered**
Obviously, we are considering implementing it ourselves but it would be nice to know if there are any showstoppers unknown to us or if somebody is already working on it or if there are any hints on how easily e.g. parts of the relevant code/config for the mimxrt1050_evk could be reused.

**Additional context**
None so far...

**Comment by MaureenHelm** [comment]
> Is there any particular reason the mimxrt106x_evk currently lacks this feature apart from that no one has yet worked on it?

No blocking issues, it just hasn't been worked on yet. It should be easy to add using the `mimxrt1050_evk` as an example. You'll need to add board-level dts, pinmuxing, and configure `tests/drivers/spi/spi_loopback` to verify it works.
