### ISSUE TITLE
PCIe: add API to get BAR region size

### ISSUE THREAD

**Issue by andrewboie** [zephyrproject-rtos/zephyr#26491]
**Is your enhancement proposal related to a problem? Please describe.**
We have pcie_get_mbar() to get a BAR MMIO base address, but no API to also obtain the region size. This means that memory-mapping drivers needs to use hard-coded region sizes instead of just querying it.

**Describe the solution you'd like**
An API to obtain a BAR region size given a BDF and a BAR index.

**Describe alternatives you've considered**
Change pcie_get_mbar() to return both address and size instead of just address.

**Additional context**
This is more of an annoyance since driver code already "knows" the bounds since it's written against a datasheet and you can just #define it.

**Comment by dcpleung** [comment]
Done in #29818
