### ISSUE TITLE
An example of using the microphone in Thingy 52

### ISSUE THREAD

**Issue by trungnq97** [zephyrproject-rtos/zephyr#26505]
**Is your enhancement proposal related to a problem? Please describe.**
None.

**Describe the solution you'd like**
An example of using the microphone in Thingy 52. I would like to acquire PCM from the microphone and send PCM data to a PC.

**Describe alternatives you've considered**
I tried to use https://github.com/zephyrproject-rtos/zephyr/tree/master/samples/boards/96b_argonkey/microphone for Thingy 52, but it didn't work. The error was no SOURCES for driver dma.

**Additional context**
None.

**Comment by carlescufi** [comment]
I2S is not supported in nRF devices yet. We are planning to add support for it very soon. As soon as that is added please request an example if the one that will be part of the implementation is not sufficient. Thanks!
