### ISSUE TITLE
how does hci_usb (hci_usb fw : \ncs\v1.3.0\zephyr\samples\bluetooth\hci_usb) set mac and send/receive files ?

### ISSUE THREAD

**Issue by zhaoyangyang12** [zephyrproject-rtos/zephyr#26506]
HI,the urgent problem we are facing now is:debugging hci_usb on Linux, how to set MAC address and send/receive files ? hci_usb fw : \ncs\v1.3.0\zephyr\samples\bluetooth\hci_usb.Have you ever tested it? Can you give me more effective information？

**Comment by emob-nordic** [comment]
What are You using to communicate with the device?

**Comment by zhaoyangyang12** [comment]
On the virtual machine, Ubuntu18.04,use hciconfig 、bluetoothctl、obexctl。

**Comment by emob-nordic** [comment]
Haven't heard about any samples, experiment by yourself.

**Comment by carlescufi** [comment]
@zhaoyangyang12 this is an NCS question, and should be asked in the Nordic DevZone.
