### ISSUE TITLE
timers: platforms using cortex_m_systick does not enter indefinite wait on SLOPPY_IDLE

### ISSUE THREAD

**Issue by Kludentwo** [zephyrproject-rtos/zephyr#26515]
**Describe the bug**
There is a spot in the SLOPPY_IDLE handling, which allows you to wait indefinite when idle, that has code that can never be reached. 

**To Reproduce**
1. west build -p -b frdm_k64f zephyr/samples/hello_world/ -- -DOPENDSA_FW=jlink
2. west build -t menuconfig
3. enable SLOPPY_IDLE
4. west debug
5. b sys_power_save_idle
6. step to z_set_timeout_expiry
7. with CONFIG_TIMEOUT_64BIT set `K_TICKS_FOREVER == -1`
8. `-1 < IDLE_THRESH` makes `ticks = 1`
9. `z_clock_set_timeout(ticks, idle);` cannot be reached inside `z_set_timeout_expiry`

**Expected behavior**
It is expected that the system enters SLOPPY_IDLE sleep and waits indefinitely.

**Impact**
Power Management modules with Cortex_m_systick.c timer can never go to sleep indefinitely.
More power usage than needed.

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04
 - Toolchain: Zephyr SDK 11.2
 - Commit: b5fb9497b6 (zephyr/master) as of 29/6 - 2020

**Comment by ioannisg** [comment]
This is not an issue with the SyStick timer driver, which, as mentioned correctly, has a way to disable timer interrupts, so the system waits indefinitely:

```
	if (IS_ENABLED(CONFIG_TICKLESS_IDLE) && idle
	    && ticks == K_TICKS_FOREVER) {
		SysTick->CTRL &= ~SysTick_CTRL_ENABLE_Msk;
		last_load = TIMER_STOPPED;
		return;
	}

```

As described, the issue concerns the check in z_set_timeout_expiry

@andyross can you look at this?
