### ISSUE TITLE
Add support for GPIO configuration in high speed SPI on nRF5340

### ISSUE THREAD

**Issue by rick1082** [zephyrproject-rtos/zephyr#26512]
**Is your enhancement proposal related to a problem? Please describe.**
Now the "zephyr\drivers\spi_nrfx_spim.c" provides great support for nRF52 series chips.
However, there's a high speed SPI (HS-SPI) interface on nRF5340 which SCLK can reach to 32 MHz, but needs dedicated GPIO pin and drive strength setting which current SPI driver doesn't handle.

**Describe the solution you'd like**
Add API for setting GPIO properly for nRF5340 when using HS-SPI

**Additional context**
Detail information regarding with the GPIO setting for HS-SPI can be found in the following link:
https://infocenter.nordicsemi.com/index.jsp?topic=%2Fps_nrf5340%2Fchapters%2Fpin.html&cp=3_0_0_8_0

**Comment by trembel** [comment]
has this been adressed in the meantime?
