### ISSUE TITLE
tests: net: socket: af_packet: is ethernet cable now mandatory to run this test ?

### ISSUE THREAD

**Issue by ABOSTM** [zephyrproject-rtos/zephyr#26568]
**Question**
Test tests/net/socket/af_packet/
used to be successful on stm32 boards (nucleo_f429zi, nucleo_f746zg for example), on test bench.
Since merged of PR  #26339  (specially commit net: conn: Handle multi interface AF_PACKET recv() properly)
the test is now failed.

Note: On test bench, there is no ethernet cable connected to the boards.
But the test used to be successful without cable.

Now test is failed, but if I plug an ethernet cable, it is passed.

Does it mean that it is now mandatory to plug ethernet cable to the boards to pass this test ?

**Comment by ABOSTM** [comment]
^^  @jukkar

**Comment by jukkar** [comment]
No, connecting an ethernet cable should not be needed. There is now some side effect when running the test in the stm32 boards. I am currently on vacation without proper hw so cannot pinpoint immediately what should be changed in the test.

**Comment by galak** [comment]
Was able to run the test on `disco_l475_iot1` but seeing it hang on `frdm_k64f`
