### ISSUE TITLE
DT_CALL_WITH_ARG macro missing

### ISSUE THREAD

**Issue by sslupsky** [zephyrproject-rtos/zephyr#26587]
I noticed that the macro DT_CALL_WTH_ARG is missing in 2.3.  What happened to this macro?  There is nothing in the release notes about it being deprecated.

**Comment by mbolivar-nordic** [comment]
This was never an API function; it was an implementation detail explicitly marked internal. It was removed as part of some refactoring in 63d5529a0d08e14f91997d0ec29e3e49431a45c4.
