### ISSUE TITLE
GH Action: Automatize removal of tag "Waiting for response"

### ISSUE THREAD

**Issue by erwango** [zephyrproject-rtos/zephyr#26602]
**Is your enhancement proposal related to a problem? Please describe.**
We put some rules around the "Waiting for response" tag.
These rules are known (or will tend to be known) more by maintainers and usual issue assignees that will put this tag after a question is raised to the one that opened the issue.
It would be fair that this tag is removed as soon as the response is given (at least soon enough), but:
- people raising issues might not have the rights to remove the tag
- assignee/maintainers might not clean the tag as often/soon as it would be required

**Describe the solution you'd like**
Set up a bot to daily check the "Waiting for response" issues and remove the tag when response has been given.

**Describe alternatives you've considered**
As mentioned above, the manual way is not perfect and might suffer from delays.

**Comment by nashif** [comment]
this is not addressed with stale action.
