### ISSUE TITLE
Couldn't find Definition for CTE transmit and enable command for Connectionless AoA/AoD implementation in Zephyr

### ISSUE THREAD

**Issue by danielkc26** [zephyrproject-rtos/zephyr#26628]
i am trying to implement AoA in nrf52833 in PlatformIO, the board is added. And i couldn’t find macro definition for LE Set Connectionless CTE Transmit Parameters command and LE Set Connectionless CTE Transmit Enable command in the …platformio\packages\framework-zephyr\include\bluetooth\hci.h

Where it will be available?

To establish a Connectionless AoA/AoD- Advertising
the procedure to configure host in the ADVERTISING DEVICE side and corresponding macro definition in the hci.h file

Configure extended advertising-BT_HCI_OP_LE_SET_EXT_ADV_PARAM

Configure periodic advertising- BT_HCI_OP_LE_SET_PER_ADV_PARAM

Configure CTE transmission - **not defined**

Enable CTE advertising - **not defined**

Enable periodic advertising - BT_HCI_OP_LE_SET_PER_ADV_ENABLE

Enable extended advertising - BT_HCI_OP_LE_SET_EXT_ADV_ENABLE

Set the advertising data - BT_HCI_OP_LE_SET_PER_ADV_DATA

A platformIO forum member suggested to raise this issue in zephyr. So i did

**Comment by carlescufi** [comment]
@danielkc26 AoA/AoD is not supported in Zephyr for now. If you want this to be supported you can either submit a Pull Request or create a new GitHub issue for it, in the form of a Feature Request.
