### ISSUE TITLE
net: TCP2: connect() returns 0 without waiting for handshake completion

### ISSUE THREAD

**Issue by a8961713** [zephyrproject-rtos/zephyr#26695]
**Describe the bug**
When using `CONFIG_NET_TCP2=y`:
A call to BSD `connect()` or `zsock_connect()` returns 0 immediately after sending SYN, without waiting for TCP handshake completion. Specifically it does not wait for [SYN,ACK] reply from server.
That leads to client assuming connection is established. Immediately sending data after `connect()`, results with an error -128 (ENOTCONN).

**To Reproduce**
The bug can be reproduced on MQTT sample at path: samples/net/mqtt_publisher.
The sample uses `mqtt_connect()`, which calls `connect()`  followed immediately by writing to the socket (`send()`).
This works with `CONFIG_NET_TCP1=y`, but fails with `CONFIG_NET_TCP2=y`.

The bug was reproduced on the following boards:
- stm32f746g_disco (using the on board ethernet)
- nucleo_l432kc (using SLIP over usart1)

**Expected behavior**
`connect()` should return with 0 only after completing the TCP handshake, i.e. receiving [SYN,ACK].

**Impact**
This is a showstopper. You should be able to send immediately after `connect()` returns successfully.

**Environment (please complete the following information):**
 - OS: Linux, Ubuntu 18.04
 - Toolchain: Zephyr SDK

**Comment by a8961713** [comment]
**Additional remark**
`connect()` succeeds (returns 0) even when there is no listening server.

**Comment by rveerama1** [comment]
Check with this PR https://github.com/zephyrproject-rtos/zephyr/pull/26098

**Comment by a8961713** [comment]
> Check with this PR #26098

Great! This is what we need.

**Comment by MaureenHelm** [comment]
> Great! This is what we need.

Can you confirm it fixes this issue?

**Comment by a8961713** [comment]
> > Great! This is what we need.
> 
> Can you confirm it fixes this issue?

Yes, it does.
