### ISSUE TITLE
Big HTTP Download - Upgrade

### ISSUE THREAD

**Issue by Nukersson** [zephyrproject-rtos/zephyr#26717]
**Is your enhancement proposal related to a problem? Please describe.**

- [Big HTTP Download](https://docs.zephyrproject.org/latest/samples/net/sockets/big_http_download/README.html) example does not prints useful metrics (KiB, MiB, KiB/sec.) of download progress. It leads to time waste at development.

- [Big HTTP Download](https://docs.zephyrproject.org/latest/samples/net/sockets/big_http_download/README.html) example does not supports [Zephyr logging API](https://docs.zephyrproject.org/latest/reference/logging/index.html) properly. It leads to lost debug messages at dev time.

**Describe the solution you'd like**
The example project should become above upgrades.

**Comment by pfalcon** [comment]
> does not prints useful metrics (KiB, MiB, KiB/sec.) of download progress. It leads to time waste at development.

Can you elaborate, what you mean by this? (The last sentence specifically).

**Comment by Nukersson** [comment]
> > does not prints useful metrics (KiB, MiB, KiB/sec.) of download progress. It leads to time waste at development.
> 
> Can you elaborate, what you mean by this? (The last sentence specifically).

I mean downloaded [`Kibibytes aka KiB`](https://en.wikipedia.org/wiki/Kibibyte), `Mibibytes aka MiB`. Currently only Bytes will be printed - it is kind a hard to read.
