### ISSUE TITLE
Single channel selection - Bluetooth - Zephyr

### ISSUE THREAD

**Issue by EdytaBosacka** [zephyrproject-rtos/zephyr#26731]
I would like to advertise and scan ONLY on one bluetooth channel (for example channel 37). Is there any way to do this in Zephyr? I tried to search parametr responsibles for it in this structure: 
struct bt_le_scan_param scan_param = {
		.type       = BT_HCI_LE_SCAN_PASSIVE,
		.options    = BT_LE_SCAN_OPT_NONE,
		.interval   = 0x0010,
		.window     = 0x0010,}
but i dont think that this is solution.

I also found  a file lll_chan in zephyrproject\zephyr\subsys\bluetooth\controller\ll_sw\nordic\lll. TI includes channel selection algorithms, but i dont see where can i select just one advertising channel?

**Comment by El-Mokhtar-AIssaoui** [comment]
@EdytaBosacka can you share the solution to scan it if you found it please?
