### ISSUE TITLE
Build failure on nucleo_wb55rg for tests/kernel/profiling/profiling_api/kernel.common.profiling

### ISSUE THREAD

**Issue by galak** [zephyrproject-rtos/zephyr#26766]
The following fails (shown in the daily overall build):

```./scripts/sanitycheck -p nucleo_wb55rg -s tests/kernel/profiling/profiling_api/kernel.common.profiling```

**Comment by galak** [comment]
Also seeing some other similar cI failures that look like the same issue:

```
tests/kernel/tickless/tickless_concept/kernel.tickless.concept
tests/kernel/timer/timer_api/kernel.timer.tickless
 ```

**Comment by erwango** [comment]
Should be fixed by https://github.com/zephyrproject-rtos/zephyr/pull/26660
