### ISSUE TITLE
UART API has ifdefs around API functions

### ISSUE THREAD

**Issue by nordic-krch** [zephyrproject-rtos/zephyr#26801]
**Describe the bug**
UART API has 2 optional, exclusive APIs: interrupt driven (`CONFIG_UART_INTERRUPT_DRIVEN` ) and later introduced asynchronous (`CONFIG_UART_ASYNC_API`). Both API's are ifdefed. That causes more ifdefs in the code which is using them. 

It is also not consistent with other optional API's, e.g. `k_poll` in kernel.

**Expected behavior**
API, even if not implemented, should not be ifdefed. It can be removed from the code using `IS_ENABLED` or any other compile time flags.

**Impact**
More dirty, harder to maintain code.

**Comment by carlescufi** [comment]
Agreed, this is also being documented here:
https://github.com/zephyrproject-rtos/zephyr/pull/26773
