### ISSUE TITLE
Cortex-M7 Thumb-2 Instructions Alignment 

### ISSUE THREAD

**Issue by kkiyota** [zephyrproject-rtos/zephyr#26803]
**Describe the bug**
Since I got a bus fault, I analyzed my code by Trace32 debugger.  It seemed that the bus fault occurred at the code like  "cmp r6,#0x40000" which is 32 bits instruction.  This one is allocated at address 0x622A where is not a word aligned.   

**To Reproduce**
1. mkdir build; cd build
2. cmake -DBOARD=myownboard
3. ninja
4. run by trace32

**Expected behavior**
No bus fault occurred.  32 bits instructions should be word aligned.

**Impact**
What impact does this issue have on your progress (e.g., annoyance, showstopper)

**Logs and console output**
![image](https://user-images.githubusercontent.com/59073069/87165439-1d2d9200-c305-11ea-8520-74f53915686e.png)

**Environment (please complete the following information):**
 - OS: Ubuntu
 - Toolchain (gcc)
 - Zephyr 2.2

**Additional context**

**Comment by kkiyota** [comment]
I found the assembler directive, ".align 2" to make the word alignment.  Although the first Thumb-2 instruction, "cmp r6, #262144", was word aligned by addition NOP at 0x542e as shown below.   However, second one at 0x5436 was not word aligned.  Since I have 3 cases, gcc seems to generate 3 cmp instructions at switch statement.  As a result, I can't put other ".align 2". 

![image](https://user-images.githubusercontent.com/59073069/87410345-27030e00-c601-11ea-8714-0955532eb954.png)


As next step, I rewrite this portion to IF-THEN statements.  There is only one "cmp" instruction which is the word aligned properly at 0x5430 as shown below.

I couldn't run it on my hardware today.  I'll let you know when I can run it on my hardware.


I also tried several different gcc options thru CONFIG_*, but there was no solution yet.  I'm not sure if this is gcc limitation or whatever.  Any idea? 


![image](https://user-images.githubusercontent.com/59073069/87411354-94636e80-c602-11ea-89a8-7fffb558e93c.png)

**Comment by stephanosio** [comment]
All Thumb instructions (including the 32-bit Thumb-2 instructions) are to supposed be half-word (i.e. 2-byte) aligned.

The bus fault must be due to something else.

**Comment by kkiyota** [comment]
My CPU is ARMv7-M (Coretex-M7).  According to ARM document, some unaligned instructions seem to be supported, but my case is cmp.w.  I guess it may be out of support.



![image](https://user-images.githubusercontent.com/59073069/87522474-a1df2e00-c6c0-11ea-8002-d8966ed78881.png)

**Comment by stephanosio** [comment]
The portion you quoted above only apply to the data accesses. See the section right below that:
![image](https://user-images.githubusercontent.com/11345418/87524074-b15f7680-c6c2-11ea-9fc5-834fc7bebe2e.png)

**Comment by ioannisg** [comment]
> All Thumb instructions (including the 32-bit Thumb-2 instructions) are supposed to be half-word (i.e. 2-byte) aligned.
> 
> The bus fault must be due to something else.

@stephanosio you mean, they are _required_ to be half-word aligned?

**Comment by ioannisg** [comment]
@kkiyota could you post some more information on the fault you're getting, as @stephanosio suggested above?

**Comment by kkiyota** [comment]
@stephanosio @ioannisg Sure I will do it later.  Unfortunately, I ca't access to my system due to a network problem.

**Comment by kkiyota** [comment]
I ran step execution and change my program to figure out root causes.  Looks like it may be related to interrupt related rather than Thumb-2 instructions' alignment so far.  I'll let you know again when I figure it out.

**Comment by kkiyota** [comment]
I found that my device setting had a typo.  As a result, my ISR structure made an incorrect address.  

Bus fault was gone after I fixed it.

Appreciated your help!
