### ISSUE TITLE
STM32: mcu goes to sleep inadvertently when using PM.

### ISSUE THREAD

**Issue by BBekker** [zephyrproject-rtos/zephyr#26896]
**Describe the bug**
When using the (experimental) STM32L4 power management, the `deepsleep` enable bit (sleep in Zephyr terms) is not set back to `sleep` (idle in zephyr terms) when waking up, resulting in the next `WFI` call also going to sleep.

**To Reproduce**
1. use stm32l* PM
2. Do a long wait to go to sleep.
3. Do a short wait that should not go do sleep but idle.
4. System goes to sleep anyway

**Expected behavior**
System only goes to sleep when executing `sys_set_power_state` with the appropriate power state.

**Fix**

In the soc specific power.c, add  `LL_LPM_EnableSleep` to `_sys_pm_power_state_exit_post_ops`. This sets the system configuration bit to use regular sleep (idle) instead of deepsleep when executing WFI.

I found this bug while porting powermanagement to the STM32L5, but I think the behavior should be the same on the other STM32 cores.

edit: fixed some potential confusion with idle/sleep/deepsleep terminology.

**Comment by FRASTM** [comment]
@BBekker  the soc residency policy does not go to sleep for a _too_ "short wait"
do you mean that `_sys_pm_power_state_exit_post_ops`() has to LL_LPM_EnableDeepSleep (like the `sys_set_power_state` function does) ?

**Comment by BBekker** [comment]
The bug is that the MCU goes to sleep, even when the residency policy does not decide it has to go to sleep.

`sys_set_power_state` uses `LL_LPM_EnableDeepSleep` to set the `SLEEPDEEP` bit in the cortex-m33 system control register.
https://developer.arm.com/documentation/100235/0003/the-cortex-m33-peripherals/system-control-block/system-control-register?lang=en

But since that bit is not reset after wakeup, it stays active.
`_sys_pm_power_state_exit_post_ops` should disable that bit again to prevent the system going to deep sleep at every WFI instruction.

**Comment by FRASTM** [comment]
This is the position of the SLEEPONEXIT bit of the System Control Register (SCR) of the cortex
Clearing this bit will avoid going to sleep when returning to Thread mode
This is the LL_LPM_DisableSleepOnExit() call during _sys_pm_power_state_exit_post_ops
