### ISSUE TITLE
[RFC] API change - Normalize DMA, IPM and UART callbacks signatures including the caller's device pointer.

### ISSUE THREAD

**Issue by tbursztyka** [zephyrproject-rtos/zephyr#26923]
## Introduction

Adding callback caller's device pointer to DMA, IPM and UART callbacks.

### Problem description

DMA, IPM and UART callbacks do not provide the device's callback caller as parameter, forcing users to use the callback_arg parameter instead for this purpose, which in turn limits its usage (they cannot provide some private data, or have to mangle thing together storing the device pointer into the private data).

### Proposed change

Adding such device pointer to DMA, IPM and UART callbacks.

## Detailed RFC

Problem description section is clear enough
The issue was spotted while switching all struct device * to constant. But it is also a normalization procedure, as all other APIs always provide the device pointer to the callbacks.

### Proposed change (Detailed)

Add struct device *dev to DMA, IPM and UART callbacks (it's pretty trivial so it does not need more details)

### Dependencies

All users of these callbacks need to adapt their callbacks accordingly.
PRs will fix all zephyr internal code, but there are module dependencies as well (mbedtls and Segger)

### Concerns and Unresolved Questions

None.

## Alternatives

None.

**PRs fixing this:**
- [RFC] API Change: DMA - callback improvement (#26781)
- [RFC] API Change: IPM - callback improvement (#26780)
- [RFC] API Change: UART - callback improvement (#26426)

**Comment by tbursztyka** [comment]
@carlescufi @nashif @pabigot @galak

**Comment by carlescufi** [comment]
API meeting 21st July:

- Why is UART being added a context/user data pointer but not others that are also missing it (eg. gpio)
- Can we take this opportunity to settle on a name for data that is carried transparently by the driver without ever accessing it?
  - `context` +
  - `user_data` +++++ (selected)
  - `callback_args`

**Comment by carlescufi** [comment]
> API meeting 21st July:
> 
> * Why is UART being added a context/user data pointer but not others that are also missing it (eg. gpio)
> * Can we take this opportunity to settle on a name for data that is carried transparently by the driver without ever accessing it?
>   
>   * `context` +
>   * `user_data` +++++ (selected)
>   * `callback_args`

API meeting 28th July

- @tbursztyka will update the PRs to unify the user param to be named `user_data`
