### ISSUE TITLE
Example OTA-DFU for Android/IOS app

### ISSUE THREAD

**Issue by nhuanhuynh** [zephyrproject-rtos/zephyr#26966]
Hi everyone,

I am a newbie in Zephyr project. Now I need to implement an application for OTA_DFU with the Android/IOS app.

Could anyone help me with an example of this?

Thank you so much

**Comment by carlescufi** [comment]
Hi there. There are iOS and Android libraries available here:

https://github.com/JuulLabs-OSS/mcumgr-ios
https://github.com/JuulLabs-OSS/mcumgr-android
