### ISSUE TITLE
Avoid oppressive language in code base

### ISSUE THREAD

**Issue by jettr** [zephyrproject-rtos/zephyr#27000]
Let's make the Zephyr codebase a more inclusive codebase by avoiding oppressive terms and keywords.

- [x] We should document our expectations with regards to what terms are blocked, and when there may be exceptions. For example, following the naming convention of an external specification could allow for an exception (DONE: #30508)

- [ ] We should introduce an automated check for each pull request to scan for blocked words. We would also need a way to suppress a warning/error if the instance was allowed via above to-be-documented policy
- [ ] We should audit the current codebase for existing instances of oppressive terms and replace them. This should include the names of git branches like `master`. 

As a first round, we could specifically target to remove the following terms: master, slave, whitelist, and blacklist

Suggested alternatives include
 * master - main, controller
 * slave - peripheral, replica
 * blacklist - deny list, block list
 * whitelist - allow list, approve list

List of sub-issues for different components:

- I2C: #27033.

**Comment by jettr** [comment]
@ioannisg @nashif @MaureenHelm @carlescufi fyi. I didn't find an existing issue to track this.

**Comment by jfischer-phytec-iot** [comment]
I suggest to follow Linux Kernel, https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=49decddd39e5f6132ccd7d9fdc3d7c470b0061bb

**Comment by jettr** [comment]
I like the idea of consistency. Are you suggesting that we use the kernel's recommend replacements or something else about that commit?

**Comment by pabigot** [comment]
I hadn't seen this; for I2C I have #27033.

**Comment by jettr** [comment]
> I hadn't seen this; for I2C I have #27033.

Do you prefer to merge the two issues or keep them separates since the one you filed is more targeted to the I2C subsystem?

**Comment by pabigot** [comment]
I'd like to keep I2C separate; the changes are likely to be made one subsystem at a time anyway.

**Comment by sslupsky** [comment]
I believe that for API's created / defined in the Zephyr codebase, this is a good approach.  However, for API's that are defined by external standards (USB, I2C, CAN, etc), it seems necessary that changes have to be addressed with the standards first.
