### ISSUE TITLE
samples/drivers/spi_flash has no README

### ISSUE THREAD

**Issue by mbolivar-nordic** [zephyrproject-rtos/zephyr#27130]
**Describe the bug**

All samples should have README.txt files so they are discoverable by users reading the HTML documentation. This one doesn't.

**Comment by nashif** [comment]
does that even qualify as a sample? Looking at the code, it is just running some tests.. If we do not have tests for this, we should move it to be a test, if we do, then we should consider dropping it.

**Comment by mbolivar-nordic** [comment]
> does that even qualify as a sample? 

I don't know. I guess since @pabigot self-assigned he can answer the question.
