### ISSUE TITLE
[v1.14] Restore socket descriptor permission management

### ISSUE THREAD

**Issue by jukkar** [zephyrproject-rtos/zephyr#27176]
Issue created for backporting #25804 to 2.2 and 1.14.
For description about the issue see #25804 for details.

**Comment by ioannisg** [comment]
Just doing a test @jukkar , and will restore the priority to medium.

**Comment by d3zd3z** [comment]
This issue should be reopened, as this needs to be fixed in LTS (or clearly marked as not applicable).
