### ISSUE TITLE
[v2.1] Unable to build Zephyr 2.1 for Upsquared board running ACRN

### ISSUE THREAD

**Issue by starmachine24** [zephyrproject-rtos/zephyr#27173]
Hi

We cannot build Zephyr 2.1 for ACRN because we get errors related to CTF. We want to get the CTF output over UART but this does not seem to be an option for this version of Zephyr as it seems that POSIX is the only way.  We want to try this version because we noticed that whenever we ran Zephyr version 2.2.99 and 2.3 on the board via ACRN we got a 10x slowdown, so a task set to run for 1 tick ran for 10 ticks. This is when running the same settings as we have when we are running Zephyr directly on the board. 

Ticks/s = 1000
System clock = 19200000 Hz

We posted about this issue on the ACRN github and they suggested we try running Zephyr 2.1 since that was the only version they have verifed. 

We took our ctf_functions and just copied them over from the newer version of Zephyr to the older one as the interface for those looked the same. And we only added the changes we have made and not changed the files in any other way.  

The errors we got looked like this:
```
/home/linux/zephyrproject/zephyr/subsys/debug/tracing/ctf/bottoms/posix/ctf_bottom.h:36:17: note: in expansion of macro 'MAP'
   36 |  u8_t epacket[0 MAP(CTF_BOTTOM_INTERNAL_FIELD_SIZE, ##VA_ARGS)];
```
Which we have no idea what it means or what it want us to change with the implementations.

Here is the link to our issue on the ACRN gituhb: https://github.com/projectacrn/acrn-hypervisor/issues/5008

**Comment by nashif** [comment]
this is not a bug, you are trying to port a new feature into an older code base, so this is not a bug in zephyr.
