### ISSUE TITLE
shell: logging: CONFIG_SHELL_LOG_BACKEND is forced if CONFIG_LOG is chosen

### ISSUE THREAD

**Issue by a8961713** [zephyrproject-rtos/zephyr#27172]
**Describe the bug**
When selecting CONFIG_LOG, CONFIG_SHELL_LOG_BACKEND is automatically selected.
As CONFIG_SHELL_LOG_BACKEND is not user configurable, user cannot disable it.

**An example for this being problematic:**
When selecting CONFIG_SHELL_BACKEND_TELNET and CONFIG_LOG,
all log messages will be sent over the telnet TCP connection by default.

*Impact*
This is a problem when debugging the network subsys, as all log messages are using the network subsys itself.

**suggested solution**
in subsys/shell/Kconfig:
The lines:
```
config SHELL_LOG_BACKEND
	bool
	depends on !LOG_MINIMAL
	default y if LOG

```
Either add a description after the `bool` so the user could alter the selection, 
or remove the default y.

**Comment by jakub-uC** [comment]
#27190
