### ISSUE TITLE
sanitycheck: add option to only build/run on emulated targets

### ISSUE THREAD

**Issue by andrewboie** [zephyrproject-rtos/zephyr#27211]
**Is your enhancement proposal related to a problem? Please describe.**
`sanitycheck` with no args selects 4000+ cases. Even with a beefy system this can take a long time.

**Describe the solution you'd like**
A command line option added, that restricts the set of platforms tested to only those with emulation support. We have emulators for all of our target architectures. 99% of the time I already know my code builds fine I'm using `sanitycheck` to debug runtime issues.

**Describe alternatives you've considered**
Open to ideas. The main goal is to reduce the amount of tests selected and get data about runtime behavior much faster.

One possible alternative is to implement tags for target boards. All the emulated targets could be tagged with "emu" or something, with options to filter based on that.

Another alternative would be to remove all boards without emulation from the default set.

**Comment by nashif** [comment]
this one done part of #27812
