### ISSUE TITLE
Ring buffer does not allow to partially put/get data

### ISSUE THREAD

**Issue by nordic-krch** [zephyrproject-rtos/zephyr#27258]
**Is your feature request related to a problem? Please describe.**
Current ring buffer implementation allow to claim the buffer for putting data (`ring_buf_put_claim`) and get pointer to the location within the buffer. When data is copied into that location `ring_buf_put_finish` is called to indicated how much data is copied. User can then claim the buffer, fill it (e.g. by passing it to the driver) and finish it. If for some reason data is not filled then `ring_buf_put_finish(buf, 0)` can be called to indicate that there is data copied.

What is not supported is ability to put portion of data because `ring_buf_put_finish` updates also internal pointer for claiming new buffer. Ring buffer fails in following scenario:

- allocate buffer for UART reception (`ring_buf_put_claim(buf, data, 8)`) and pass it to the driver
- on RX timeout receive 3 bytes (less that buffer size). Call `ring_buf_put_finish(buf, 3)`. UART is keep using the same buffer.
- allocate second buffer for UART and pass it to the driver. UART async API supports double buffering so buffer can be passed before previous one is completed. Because `ring_buf_put_finish` moved internal pointer, new buffer will overlap with previous buffer.

**Describe the solution you'd like**
In some cases it is vital that internal "claim" pointer is updated by `ring_buf_put_finish`. That is when we are actually done with the buffer. In the UART case above that would be if receiver is actually done with receiver to given buffer when timeout occurs. To support both cases i would add a `partial` flag to `ring_buf_put_finish` and `ring_buf_get_finish`. When `partial` flag is set to true then internal, "claim" pointer is not updated.

**API change**
That change would extend API with legacy behavior achieved by converting `ring_buf_put_finish(buf, n)` to  `ring_buf_put_finish(buf, false)`. Ring buffer API is not mentioned in https://docs.zephyrproject.org/latest/reference/overview.html#

**Comment by nashif** [comment]
@nordic-krch  looks like your PR was closed due to inactivity, do you still need this? I guess you can reopen this, but closing this as stale right now, given that the PR was stale.
