### ISSUE TITLE
RFC: downgrade i2c eeprom_slave driver to test

### ISSUE THREAD

**Issue by pabigot** [zephyrproject-rtos/zephyr#27303]
We have a [driver accessed under `CONFIG_I2C_EEPROM_SLAVE`](https://docs.zephyrproject.org/latest/reference/peripherals/i2c_eeprom_slave.html)  that implements the I2C follower (slave) driver API.  This device isn't an actual hardware driver: it's a virtual EEPROM that stores data in an instance-specific RAM buffer, with the data exposed on an I2C bus as a I2C follower device that can be controlled by another device acting as a leader (master) on that same bus.

As such it's a reasonable example of how to write an I2C follower driver, but it's not clear that it has a real use in applications: the sole in-tree reference is in the `i2c_slave_api` test.

Can anybody make a case for having this "device" available to applications?  If not, I propose to move it into the test source directory.

**Comment by pabigot** [comment]
@henrikbrixandersen @superna9999 your input requested, please.

**Comment by henrikbrixandersen** [comment]
@pabigot That is a good idea. I came across the that driver when I introduced the EEPROM API, and wondered what the use-case was.

**Comment by carlescufi** [comment]
API meeting 4th August 2020:

- No objections in the meeting
- This unmaintained driver will be removed and a note will be added to the release notes, along with information on how to use the sample instead.

**Comment by pabigot** [comment]
Mail sent 2020-08-04
