### ISSUE TITLE
Decouple TLS socket from net_context

### ISSUE THREAD

**Issue by parthitce** [zephyrproject-rtos/zephyr#27318]
**Is your feature request related to a problem? Please describe.**
The current implementation of TLS socket is tightly bound to Zephyr's native socket implementation. Devices like W5500 doesn't provide provision for TLS in device TCP/IP stack. Implementing socket/net offloading leaves the device without TLS support.

**Describe the solution you'd like**
Based on the discussion with @rlubos in slack, the idea is to abstract/decouple the net_context from Zephyr socket implementation. This way we can use TLS from Zephyr TCP/IP and socket/net offloading from device TCP/IP.

@jukkar please share your views.

**Comment by jukkar** [comment]
This might be tricky as the net_context calls would be needed to be replaced by some other API. The question is, what would that API be. Also note that there are two kind of offloading in zephyr, socket offloading in BSD socket level, and network offloading on net_context level. The latter should work with those device that provide plain network offloading as the net_context calls would be directed to offloading engine and TLS should work just fine. So this question is only about socket offloading.
