### ISSUE TITLE
up_squared: Zephyr does not boot via grub anymore

### ISSUE THREAD

**Issue by tbursztyka** [zephyrproject-rtos/zephyr#27339]
**Describe the bug**
Trying this https://docs.zephyrproject.org/latest/boards/x86/up_squared/doc/index.html#preparing-the-boot-device
Grub boots, but nothing appears on the console once zephyr has supposedly started.

**To Reproduce**
Just follow the link information

**Expected behavior**
the sample should print out something into the ftdi console

**Environment (please complete the following information):**
 - OS: Linux
- Board: UP squared

**Comment by tbursztyka** [comment]
@nashif @andyross @andrewboie  @laperie @jhedberg

**Comment by MaureenHelm** [comment]
@andyross will you be able to fix this soon?
