### ISSUE TITLE
include in prj.conf

### ISSUE THREAD

**Issue by Delsian** [zephyrproject-rtos/zephyr#27330]
**Is your feature request related to a problem? Please describe.**
Different subprojects in single superproject has a lot of common setting. On every superproject's change I need to replace the same values in all subprojects.

**Describe the solution you'd like**
Implement "#include <common.conf>" directive inside prj.conf

**Comment by jukkar** [comment]
You can use overlays instead. You can do this by giving `-DOVERLAY_CONFIG=overlay-foobar.conf` in cmake. Then you could place the common settings into the overlay file and use it in your subprojects.

**Comment by Delsian** [comment]
Ok, I see the right solution, using CONF_FILE directive in CMakeList.txt:

`set(CONF_FILE
  prj.conf
  log.conf
)`

Sorry for the wrong request
