### ISSUE TITLE
<wrn> bt_driver: Discarding event 0x3e

### ISSUE THREAD

**Issue by marshed18** [zephyrproject-rtos/zephyr#27340]
**Describe the bug**
I am have programmed my Thingy 91 device with lte_ble_gateway program to collect data from 5 bluetooth devices and send them to the cloud. I am using this version lte_gateway_thingy91_v1.1.0_R2.zip posted on this https://devzone.nordicsemi.com/f/nordic-q-a/52689/nrf9160-lte-sensor-gateway-on-thingy-91/217018 I am powering it using USB and it displays this error in the beginning 

<wrn> bt_hci_core: opcode 0x0000 pool id 5 pool 0x200312bc != &hci_cmd_pool 0x20031298

after running the program for a while it gives this error for a while and stop running 

<wrn> bt_driver: Discarding event 0x3e

**To Reproduce**
1. ../ncs/zephyr/samples/bluetooth/hci_uart_with_usb_uart_bridge/CMakeLists.txt
2. ../ncs/nrf/boards/arm/nrf52840_pca20035
3. ../ncs/nrf/samples/nrf9160/lte_ble_gateway/CMakeLists.txt
4. ../ncs/nrf/boards/arm/nrf9160_pca20035

**Expected behavior**
<wrn> bt_hci_core: opcode 0x0000 pool id 5 pool 0x200312bc != &hci_cmd_pool 0x20031298

after running the program for a while it gives this error for a while and stop running 

<wrn> bt_driver: Discarding event 0x3e

**Impact**
makes the program useless 

**Logs and console output**
<wrn> bt_driver: Discarding event 0x3e

**Environment (please complete the following information):**
 - Windows
 - nRF Connect SDK 
 - v1.1.0

**Additional context**

**Comment by carlescufi** [comment]
@marshed18 thank you for reporting this, but this is an issue in Nordic's nRF Connect SDK, which uses a custom version of Zephyr. Please use Nordic's DevZone instead to report this.
