### ISSUE TITLE
Constant asserts from nrf5 clock calibration

### ISSUE THREAD

**Issue by MZachmann** [zephyrproject-rtos/zephyr#27370]
**Describe the bug**
Running program I now get a periodic (very often) assert in temp_nrf_sample_fetch. The stack trace is

assert_post_action
temp_nrf5_sample_fetch
get_temperature
measure_temperature
z_work_q_main

and the assert is here:
	r = onoff_release(data->clk_mgr);
	__ASSERT_NO_MSG(!r);

This is the result of this change: **ff089217cb3fdc24dc276041fb41bdd241c3626f** because if I back this out it asserts once at startup and then not again.

**To Reproduce**
This seems to be the result of calibrating the rc clock using temperature. I have no idea why. I haven't walked through the onoff code to identify the root cause.

**Expected behavior**
I expect either there's a bug in my application, which is now new, or the assert should not be trapping.

**Impact**
It's annoying and seems like I have a bug but I have no idea if that's true.

**Logs and console output**

I'm trapping the assert and logging it and see this:

ASSERTION FAIL [!r] @ WEST_TOPDIR/zephyr/drivers/sensor/nrf5/temp_nrf5.c:64
[00:00:14.009,765] [0m<inf> main: *** ASSERT from WEST_TOPDIR/zephyr/drivers/sensor/nrf5/temp_nrf5.c at line 64.[0m
ASSERTION FAIL [!r] @ WEST_TOPDIR/zephyr/drivers/sensor/nrf5/temp_nrf5.c:64
[00:00:18.041,809] [0m<inf> main: *** ASSERT from WEST_TOPDIR/zephyr/drivers/sensor/nrf5/temp_nrf5.c at line 64.[0m
ASSERTION FAIL [!r] @ WEST_TOPDIR/zephyr/drivers/sensor/nrf5/temp_nrf5.c:64
[00:00:22.042,053] [0m<inf> main: *** ASSERT from WEST_TOPDIR/zephyr/drivers/sensor/nrf5/temp_nrf5.c at line 64.[0m

**Environment (please complete the following information):**
 - OS: Windows
 - Toolchain : gnu arm embedded
 - Commit SHA or Version used: a4410367e5c81aa419e04532befc2a10e1b9e0c3

**Additional context**
This is running on a Nrf52840 with no 32KHz crystal. Prj.conf settings are:
CONFIG_CLOCK_CONTROL_NRF=y
CONFIG_CLOCK_CONTROL_NRF_K32SRC_RC=y
CONFIG_CLOCK_CONTROL_NRF_K32SRC_250PPM=y
#CONFIG_CLOCK_CONTROL_NRF_K32SRC_RC_CALIBRATION=n

if the last line is enabled it also stops asserting since calibration no longer takes place.

**Comment by nordic-krch** [comment]
this is fixed by #27253
