### ISSUE TITLE
LOG_BACKEND_NET does not work for certain application/ip configurations

### ISSUE THREAD

**Issue by chrta** [zephyrproject-rtos/zephyr#27464]
I am integrating LOG_BACKEND_NET in an application that sets neither CONFIG_NET_CONFIG_NEED_IPV4 nor CONFIG_NET_CONFIG_NEED_IPV6. It uses ppp as a network interface and a static IPv6 address as LOG_BACKEND_NET_SERVER. LOG_BACKEND_NET_SERVER is only reachable after the ppp link is set-up completely.

With the current zephyr code this is not possible. After the first log message (on the shell), the logging thread is blocked and no more log message are visible (on the shell). I had to delay the initialization/enablement of the net-backend by modifying the backend code. It seems that the developer anticipated the problem (see code comment right above the changed line), but it is not handled.

Would this be the proper fix to the backend code?

```diff
diff --git a/subsys/logging/log_backend_net.c b/subsys/logging/log_backend_net.c
index 072b3410cd..3a7bf9a108 100644
--- a/subsys/logging/log_backend_net.c
+++ b/subsys/logging/log_backend_net.c
@@ -250,7 +250,9 @@ const struct log_backend_api log_backend_net_api = {
 /* Note that the backend can be activated only after we have networking
  * subsystem ready so we must not start it immediately.
  */
-LOG_BACKEND_DEFINE(log_backend_net, log_backend_net_api, true);
+LOG_BACKEND_DEFINE(log_backend_net, log_backend_net_api,
+                  IS_ENABLED(CONFIG_NET_CONFIG_NEED_IPV4) ||
+                  IS_ENABLED(CONFIG_NET_CONFIG_NEED_IPV6));
 
 const struct log_backend *log_backend_net_get(void)
 {

```

**Comment by jukkar** [comment]
Yes, the logging NET backend is not fully ready in this respect. What you are proposing look like a good workaround for now.

It is probably not obvious to casual reader how these options would fix the issue. Perhaps it is more clearer if you create a Kconfig option like `CONFIG_LOG_BACKEND_NET_AUTOSTART` and put these `NEED` symbols to there (in default values) and describe in the help text what those options mean. Then here we could just do `IS_ENABLED(CONFIG_LOG_BACKEND_NET_AUTOSTART)` here.
