### ISSUE TITLE
testcases under zephyr/tests/application_development take a very long time to dump coverage data

### ISSUE THREAD

**Issue by wangnuannuan** [zephyrproject-rtos/zephyr#27503]
**Describe the bug**
When I run the testcases under `zephyr/tests/application_development`,  it seems that too many source files are  referenced, `gcov_coverage_dump()`  keeps output coverage data and can't stop. 

**To Reproduce**
1. `west build -b qemu_x86 ./zephyr/tests/application_development/cpp -- -DCONFIG_COVERAGE=y -DCONFIG_COVERAGE_DUMP=y`
2. `ninja run -Cbuild`

I tried to run the above command, and 2 hours later it was still outputting coverage data.

**Comment by tejlmand** [comment]
The `cpp` and `libcxx` tests are not supporting coverage on `qemu_x86` and are for the same reason excluded:
https://github.com/zephyrproject-rtos/zephyr/blob/4d3580d29735bd3d3d7a89e7475ccd9e001cd818/tests/application_development/cpp/testcase.yaml#L3

https://github.com/zephyrproject-rtos/zephyr/blob/4d3580d29735bd3d3d7a89e7475ccd9e001cd818/tests/application_development/libcxx/testcase.yaml#L8

`gen_inc_file` works as expected.
https://github.com/zephyrproject-rtos/zephyr/tree/master/tests/application_development/gen_inc_file
