### ISSUE TITLE
driver: peci: mchp: Ping command is failing due to improper tx wait timeout.

### ISSUE THREAD

**Issue by VenkatKotakonda** [zephyrproject-rtos/zephyr#27506]
**Describe the bug**
When ping command is sent driver which has zero data lenth, as the tx timeout is calculated in multiples of Tx data length, driver is not waiting for tx to complete.
Need to fix this.

**To Reproduce**
1. send peci_ping() command to driver.

**Expected behavior**
ping command should tx success.

**Impact**
peci app will fail for ping.

**Comment by albertofloyd** [comment]
@VenkatKotakonda  check with PR created
