### ISSUE TITLE
[v1.14] Bluetooth: controller: Fix uninit conn context after invalid channel map

### ISSUE THREAD

**Issue by erbr-ot** [zephyrproject-rtos/zephyr#27510]
When a connect indication contains a channel map of all zeros, the adv->conn is left NULL'ed after connect establishment is abborted and next connect attempt leads to a crash.

This was identified via the Sweyntooth test suite - executing the script re. issue 6.14 towards an Oticon target.
https://asset-group.github.io/disclosures/sweyntooth/
Zephyr v1.14 needs to be analysed.

See #27507

**Comment by carlescufi** [comment]
@erbr-ot will you create a backport PR for this, targetting the v1.14-branch?

**Comment by erbr-ot** [comment]
@carlescufi I will, in the next few days.

**Comment by erbr-ot** [comment]
Hi @carlescufi - sorry this got back-seated during our race to finish-line. Looking into this now, and have a question: I see that the guard re. lll->data_chan_hop is not present in v1.14.2, should I introduce this also in the same PR?

**Comment by carlescufi** [comment]
> Hi @carlescufi - sorry this got back-seated during our race to finish-line. Looking into this now, and have a question: I see that the guard re. lll->data_chan_hop is not present in v1.14.2, should I introduce this also in the same PR?

I think this is a question for @cvinayak

**Comment by cvinayak** [comment]
This slipped through me. Now addressed here https://github.com/zephyrproject-rtos/zephyr/pull/33760
