### ISSUE TITLE
[RFC] drivers: display: Implementing driver for sharp memory display

### ISSUE THREAD

**Issue by rgujju** [zephyrproject-rtos/zephyr#27523]
## Introduction

 I am writing a driver for the [sharp memory in pixel displays](https://www.sharpsma.com/products?sharpCategory=Memory%20LCD&p_p_parallel=0)  and wanted to know your thoughts regarding the best way to implement in zephyr. 
[datasheet](https://www.mouser.com/datasheet/2/365/LS013B7DH03%20SPEC_SMA-224806.pdf)

### Problem description

 The display expects a complete line to be written to it which brings up a few challenges of how to allocate the memory for it. 
 The format for a write is
  +---------------------+-------------------------+--------------------------+
  | line num (8 bits) | data (WIDTH bits) | dummy bits (8 bits) |
  +---------------------+-------------------------+--------------------------+
 Consider WIDTH and HEIGHT is 128px then total size will be LINE_MEM: 18 bytes.
 The CFB subsys expects the display to have a SCREEN_INFO_MONO_VTILED but this display is horizontally tiled so I guess CFB wont work with this display at the moment.
 Hence I switched to lvgl for testing.

### Concerns and Unresolved Questions

 Option 1:
 Allocate memory for the line in .write API. This will have to be dynamic allocation as number of lines can differ. The maximum size allocated will be HEIGHT*(LINE_MEM) ie. 128*18 bytes. The limitation of this method will be that X co-ordinate will always have to be 0 becaue of which lvgl does not work. lvgl sends co-ordinates corresponding to the updated area hence X can have any value. Unless there is a way to force lvgl to provide X as 0.
 
 
 Option 2:
 Allocate the complete frame buffer in memory either statically or dynamically. When .write API is called copy given buf to our allocated frame buffer and then update the required lines only. This will remove the constraint of X being 0.

**Comment by jfischer-phytec-iot** [comment]
I think the question was answered on the slack, can we close it then?
