### ISSUE TITLE
How to use stm32cubeIDE to build and debug?

### ISSUE THREAD

**Issue by ahmedwahdan** [zephyrproject-rtos/zephyr#27559]
How to use stm32cubeIDE to build and debug?

**Comment by erwango** [comment]
@ahmedwahdan stm32cubeIDE is not made to use with zephyr. If you need an IDE to use zephyr I suggest to use VSCode (cf https://github.com/zephyrproject-rtos/zephyr/issues/21119 for configuration) or Eclipse with Zephyr plugin (http://marketplace.eclipse.org/content/eclipse-plug-zephyr-project).

**Comment by erwango** [comment]
@ahmedwahdan are you satisfied with the answer provided ? 
If yes, can we close the issue?

**Comment by EminYagmahan** [comment]
Alternatively I can recommend CLion from JetBrains. With the Embedded Development Support Plugin, STM32CubeMX and OpenOCD can be integrated into the IDE quite well. This is how it can look like. Zephyr projects also work great. A guide is available here:
https://www.jetbrains.com/clion/features/embedded-dev.html
![CLion_Zephyr](https://user-images.githubusercontent.com/47952672/92979814-2ddcbe80-f494-11ea-892e-ef6ead304b3e.png)

**Comment by erwango** [comment]
Thanks @EminYagmahan.
I would just warn people that using Zephyr, you won't be able to use the configuration and code generated by CubeMx.
