### ISSUE TITLE
sample.drivers.sample.drivers.peci failed to run

### ISSUE THREAD

**Issue by Zhaoningx** [zephyrproject-rtos/zephyr#27576]
Describe the bug
building tests/kernel/device/peci on mec15xxevb_assy6853 board, it would report a error at output log.

To Reproduce

    west build -b mec15xxevb_assy6853 -p auto samples/drivers/peci
    ~/software/ci/tools/usbgpio_ftdi/pre_script.sh
    west flash
    ~/software/ci/tools/usbgpio_ftdi/post_script.sh

    see error

Logs and console output
*** Booting Zephyr OS build zephyr-v2.3.0-1774-g34859d0d3e40  ***
PECI sample test
00
00
00
00
00

peci_resp 0
00
00
00
00
00

peci_resp 0
00
00
00
00
00

peci_resp 0
Maximum temperature: 0
Start thread...
Get temp failed -5
Get temp failed -5
Get temp failed -5
Get temp failed -5

Environment (please complete the following information):

    OS: Fedora28
    Toolchain: Zephyr-sdk-0.11.4
    Commit ID: 34859d0d3e

**Comment by albertofloyd** [comment]
Not supported in EVB, only in modular MEC mated to Intel RVP.

**Comment by Zhaoningx** [comment]
> Not supported in EVB (mec15xxevb_assy6853 ) only in modular MEC (mec1501modular_assy6885) mated to Intel RVP.

OK, got it, close the PR later.

**Comment by Zhaoningx** [comment]
Hi @albertofloyd , so, you mean to add a platform_exclude tag at sample.yaml to exclude the platform mec15xxevb_assy6853?

**Comment by albertofloyd** [comment]
Yes.
Note that theoretically EVB can be connected to Intel RVP as well, but HW setup is not documented, hence qualifying as unsupported.

**Comment by Zhaoningx** [comment]
OK, so I'll close this issue later.
