### ISSUE TITLE
BT Identity address is overwritten when using extended advertising

### ISSUE THREAD

**Issue by Thalley** [zephyrproject-rtos/zephyr#27582]
**Describe the bug**
If attempting to advertise by a random static address by creating an ID and using that ID for extended advertising, the random static address of the ID is overwritten with an NRPA when advertising is started. This when BT host privacy is disabled (`CONFIG_BT_PRIVACY=n`). 

**To Reproduce**
Steps to reproduce the behavior in the bt shell:
1. bt id-create ed:a1:a2:a3:a4:ab
2. bt id-select 1
3. bt adv-create conn-scan identity name
4. bt adv-start

**Expected behavior**
That advertising is using `ed:a1:a2:a3:a4:ab` as the address.

**Impact**
What impact does this issue have on your progress (e.g., annoyance, showstopper)

**Logs and console output**
```
< HCI Command: LE Set Advertising Set Random Address (0x08|0x0035) plen 7         #2408 3522.372113
        Advertising handle: 0x00
        Advertising random address: ED:A1:A2:A3:A4:AB (OUI ED-A1-A2)
> HCI Event: Command Complete (0x0e) plen 4                                       #2409 3522.373426
      LE Set Advertising Set Random Address (0x08|0x0035) ncmd 1
        Status: Success (0x00)
< HCI Command: LE Set Advertising Set Random Address (0x08|0x0035) plen 7         #2410 3523.841970
        Advertising handle: 0x00
        Advertising random address: 0C:7F:C0:08:65:48 (OUI 0C-7F-C0)
> HCI Event: Command Complete (0x0e) plen 4                                       #2411 3523.842528
      LE Set Advertising Set Random Address (0x08|0x0035) ncmd 1
        Status: Success (0x00)
```

**Environment (please complete the following information):**
Commit: 0dc187584c7248ebd3ae61136ebd8414a11eb04f

**Comment by joerchan** [comment]
Closing since this was fixed by https://github.com/zephyrproject-rtos/zephyr/pull/27907
