### ISSUE TITLE
threads without name show up as junk names in SystemView

### ISSUE THREAD

**Issue by lowlander** [zephyrproject-rtos/zephyr#27592]
When a thread does not have a name set (in this case the RX thread of the STM32 ethernet driver) SystemView shows the name as junk;

![systemview_thread_no_name](https://user-images.githubusercontent.com/1266398/90309261-41255a00-dee7-11ea-8591-8f48248e0689.png)

I will give the STM32 thread a name, but I think there is some deeper problem on why SystemView shows junk and not just an empty string.

**Comment by andrewboie** [comment]
probably need to ensure `thread->name[0]` is set to `\0` in `z_setup_new_thread()`
