### ISSUE TITLE
CONFIG_ASSERT not working on nrf5340dk_nrf5340_cpunet in hci_rpmsg sample

### ISSUE THREAD

**Issue by alexsven** [zephyrproject-rtos/zephyr#27613]
**Describe the bug**
When running the hci_rpmsg + central_hr/peripheral_hr on two nrf5340DK, if I set CONFIG_ASSERT=y in prj.conf in hci_rpmsg it doesn't start. I get *** Booting Zephyr OS build zephyr-v2.3.0-1883-g4bd247af700a  *** but nothing else. This is not an issue when compiling for nrf5340pdk, however.

**Environment (please complete the following information):**
 - OS: Windows
 - Toolchain: gnuarmemb
 - Commit SHA: 4bd247af700a

**Comment by alexsven** [comment]
> I wonder @alexsven if you could bisect and find an offending commit.
> Of course it has to be after the support for DK was introduced..

Tested with #26110 (first PR with support for the DK) and it didn't work there

**Comment by ioannisg** [comment]
Thanks @alexsven , I am taking a look.
