### ISSUE TITLE
Sanitycheck: non-existing test case shows up in .xml file.

### ISSUE THREAD

**Issue by LeiW000** [zephyrproject-rtos/zephyr#27765]
Run sanitycheck as below to run the test cases under tests/kernel/workq/work_queue_api/. The test case "kernel.workqueue.api" shows in reel_board.xml, which is generated by sanitycheck. But the test case does not exist. 

./scripts/sanitycheck -p reel_board --device-testing --device-serial /dev/ttyACM0 -T tests/kernel/workq/work_queue_api/

> testcase classname="kernel.workqueue" name="kernel.workqueue.api" time="7.722598"

**Comment by nashif** [comment]
found offending commit, working on this.
