### ISSUE TITLE
iotdk: cpu_stats function doesn't work as expected

### ISSUE THREAD

**Issue by maksimmasalski** [zephyrproject-rtos/zephyr#27771]
**Describe the bug**
cpu_stats profiling function doesn’t work as expected, it always report cpu usage 100 even if cpu in idle thread for a long time. It looks like the cpu_stats hooks does not have a chance to count the switch in of idle thread (stats_hw_tick.idle always 0). 

```
Hello World! iotdk
CPU usage: 100
CPU usage: 100
CPU usage: 100
CPU usage: 100
CPU usage: 100
```
It always report cpu usage 100%, and global variable stats_hw_tick.idle is 0, but I confirmed cpu can enter idle

**To Reproduce**
1. Use latest master c64e0ce923cde54415d203e447a1dc62894ed2b0
2. SDK 0.11.4
3. Go to samples/hello_world
4. Add to prj.conf configuration for turning on cpu_stats:
```
CONFIG_TRACING=y
CONFIG_TRACING_CPU_STATS=y
CONFIG_TRACING_CPU_STATS_LOG=y
```
5. west build -p -b iotdk samples/hello_world/
6. west flash
7. View the output

**Expected behavior**
When system idle, the cpu usage reported should not be always 100%
My expectation
```
Hello World! iotdk
CPU usage: 0
CPU usage: 0
CPU usage: 0
CPU usage: 0
CPU usage: 0
```

**Impact**
Wrong cpu_stats function execution on the arc board.

**Environment (please complete the following information):**
 - OS: Linux Ubuntu 18.04.4 LTS
 - Toolchain Zephyr SDK 0.11.4
 - Commit SHA c64e0ce923cde54415d203e447a1dc62894ed2b0

**Comment by nashif** [comment]
Here we are not recording switched_in/switched_out correctly for all threads and cpu stats depends on such information. switched_in might need to move to the arch context switch code and not be in the c code.

**Comment by jocelyn-li** [comment]
@evgeniy-paltsev I am interested with this fix. Do you have timeline for the fix?
