### ISSUE TITLE
Default clock settings for STM32F7 violates operating conditions

### ISSUE THREAD

**Issue by hjuul** [zephyrproject-rtos/zephyr#27792]
**Describe the bug**
When building applications for stm32f7 devices with upstream board configurations the CPU clock speed defaults to 216MHz. 

According to the STM32F76xxx Reference Manual, this clock speed mandates that the internal regulator is in overdrive mode and that the flash is configured for at least seven wait states.

Neither of these requirements are met for upstream Zephyr, which in my opinion is a critical violation of the device operating conditions.

**To Reproduce**
1. Build and flash `samples/basic/blinky` for stm32f746g_disco
2. Run with debugger and verify registers:
    * PWR->CR1->ODEN = 0
    * FLASH->ACR->LATENCY=5

**Expected behavior**
* PWR->CR1->ODEN = 1
* FLASH->ACR->LATENCY=7

(or CPU frequency <180MHz)

**Impact**
Everything seems to be working, but if my assumptions are correct this is a critical reliability issue.

**Environment (please complete the following information):**
 - OS:  Linux
 - Toolchain: Zephyr SDK 0.11.3
 - Zephyr v2.3.0

**Additional context**
This issue would be fixed by just enabling overdrive mode. If overdrive mode is enabled, the stm32cube LL will set the correct number of flash wait states. I've posted an issue on STM32F7Cube repository related to this, but the Zephyr fix does not depend on it: https://github.com/STMicroelectronics/STM32CubeF7/issues/24

I've tested this with blinky app on stm32f746g_disco and a custom app on a custom board with STM32F769.

**Comment by ABOSTM** [comment]
Hi @hjuul,
I agree with your analysis and I proposed a fix: #27916
