### ISSUE TITLE
Cannot enable MPU for nucleo_l552ze_q_ns

### ISSUE THREAD

**Issue by NolwennV** [zephyrproject-rtos/zephyr#27809]
The current L5 TF-M implementation configures and enables both a secure and a non secure MPU. This is incompatible with an activation from Zephyr side (non secure binary). 
This is a known issue tracked at : https://developer.trustedfirmware.org/T806

As a result, the  MPU stay disabled for the target nucleo_l552ze_q_ns in the PR https://github.com/zephyrproject-rtos/zephyr/pull/27524.

**Comment by erwango** [comment]
This issue should be kept open for now.
