### ISSUE TITLE
reel_board:running failed in tests/drivers/gpio/gpio_api_1pin/

### ISSUE THREAD

**Issue by Zhaoningx** [zephyrproject-rtos/zephyr#27820]
Describe the bug
Running test cases and the output assert failed on reel_board

To Reproduce
west build -b reel_board tests/drivers/gpio/gpio_api_1pin/
west flash
see error

*** Booting Zephyr OS build zephyr-v2.3.0-2118-g94721b316f63  ***
Running test suite gpio_api_1pin_test

===================================================================
START - test_gpio_pin_configure_push_pull
Running test on port=GPIO_0, pin=11

    Assertion failed at WEST_TOPDIR/zephyr/tests/drivers/gpio/gpio_api_1pin/src/test_config.c:23: pin_get_raw_and_verify: (val_expected )
Test point 10: invalid pin get value
 FAIL - test_gpio_pin_configure_push_pull

===================================================================
START - test_gpio_pin_configure_single_ended
Running test on port=GPIO_0, pin=11
When configured as input test pin value is high
 PASS - test_gpio_pin_configure_single_ended

===================================================================
START - test_gpio_pin_set_get_raw
Running test on port=GPIO_0, pin=11

.
.
.

Environment (please complete the following information):

OS: Fedora28
Toolchain: Zephyr-sdk-0.11.3
Commit ID: g94721b316f63

**Comment by pabigot** [comment]
Confirmed failure, but I suspect this is a test failure.  The Nordic GPIO driver has been pretty heavily tested on other platforms.

**Comment by Zhaoningx** [comment]
Hello @pabigot , I don't get your point, you mean, this failure is normal and could be ignored on reel_board?

**Comment by pabigot** [comment]
No, I mean this test depends on an input that is wired to an LED behaving in a particular way, which might not be how the circuit on this particular board actually behaves.  It doesn't mean the GPIO driver is wrong, though that is remotely possible.

**Comment by Zhaoningx** [comment]
Good to know, so what should we do next?

**Comment by pabigot** [comment]
Wait for the people who have been assigned this issue to look at it.

**Comment by carlescufi** [comment]
@jfischer-phytec-iot would you mind taking a look at why this test is failing? It doesn't need any fixtures, just an LED.

**Comment by jfischer-phytec-iot** [comment]
The LED (junction capacitance) and resistor between the GPIO pin and VDD form an RC element. The resistors on the board are intentionally larger, one for LED1 is the largest. The state of the pin is not yet settled at the time it is read, see:
_"Verify that it is not possible to change value of a pin via gpio_pin_set_raw function if pin is configured as an input."_ [gpio_pin_configure(port, TEST_PIN, GPIO_INPUT)](https://github.com/zephyrproject-rtos/zephyr/blob/master/tests/drivers/gpio/gpio_api_1pin/src/test_config.c#L119)
With the change below the test runs through. I am not sure if the value TEST_GPIO_MAX_RISE_FALL_TIME_US is always sufficient.

```diff
diff --git a/tests/drivers/gpio/gpio_api_1pin/src/test_config.c b/tests/drivers/gpio/gpio_api_1pin/src/test_config.c
index fa69e29a7e..0df0b56ea9 100644
--- a/tests/drivers/gpio/gpio_api_1pin/src/test_config.c
+++ b/tests/drivers/gpio/gpio_api_1pin/src/test_config.c
@@ -118,6 +118,7 @@ void test_gpio_pin_configure_push_pull(void)
         */
        ret = gpio_pin_configure(port, TEST_PIN, GPIO_INPUT);
        zassert_equal(ret, 0, "Failed to configure the pin as an input");
+       k_busy_wait(TEST_GPIO_MAX_RISE_FALL_TIME_US);
 
        int pin_in_val;

```

**Comment by pabigot** [comment]
@jfischer-phytec-iot Thanks; I can work with that and will add that as an optional constant in the test's devicetree binding.  What delay value are you using here?

**Comment by pabigot** [comment]
Ah, I see, it's defined in a header.  It should be in devicetree.
