### ISSUE TITLE
tests/lib/sprintf fails on native_posix_64

### ISSUE THREAD

**Issue by pabigot** [zephyrproject-rtos/zephyr#27847]
On updated Ubuntu 20.04 hosts, and on [buildkite](https://buildkite.com/zephyr/zephyr/builds/6377#de9379aa-7a42-4b95-9c4b-3369f80e4d9e), the test fails at:
```
===================================================================
START - test_sprintf_misc
*** %n in writable segment detected ***
Aborted (core dumped)
tirzah[73]$
```

**Comment by nashif** [comment]
started failing after b51eeb03f4a3c2b6ece78d2c79d336c90587f4cf

**Comment by pabigot** [comment]
@petejohanson @aescolar
