### ISSUE TITLE
up_squared: couldn't get test result from serial of each test.

### ISSUE THREAD

**Issue by chen-png** [zephyrproject-rtos/zephyr#27867]
**Describe the bug**
for up_squared, when using zephyr.strip file and usb disk to run tests on this board, couldn't get test result from serial for each test.

the good commit is 4cf1832fa8, but for the latest, it's broken.

**To Reproduce**
1.  west build -b up_squared -p auto samples/hello_world/
2.  west flash ~/up_squared.sh
3.  see error

**Logs and console output**
there is nothing in the console, it seems that the test doesn't boot up.

**Environment (please complete the following information):**
 - OS: fedora28
 - Toolchain: zephyr-sdk-0.11.4
 - CommitID: 6a8c622bcca

**Comment by jhedberg** [comment]
@chen-png did you try `git bisect` to narrow this down, since you have a fairly recent "good" commit?

**Comment by chen-png** [comment]
> @chen-png did you try `git bisect` to narrow this down, since you have a fairly recent "good" commit?

the recent good commit is e9d1545, and the first bad commit is 38e17b6.

**Comment by MaureenHelm** [comment]
@wentongwu @jhedberg any update on this issue? will it be fixed soon?

**Comment by andrewboie** [comment]
@MaureenHelm I'm taking a look at this.

**Comment by andrewboie** [comment]
Also there appears to be a workaround via BIOS settings to use PIO for serial, in which case we might consider lowering severity. I'll follow up on this.

**Comment by tbursztyka** [comment]
@andrewboie I'll try your fix on my up² (so far, nor efi nor grub boot works, even on commit before your paging ones...)

**Comment by nashif** [comment]
so just to document this here, building with -DCONFIG_PCIE_MMIO_CFG=n, get this back to a working state, if this is a workable solution, we could downgrade priority while working on a  fix.
