### ISSUE TITLE
Make i2c_slave callbacks public in the documentation

### ISSUE THREAD

**Issue by franciscomunoz** [zephyrproject-rtos/zephyr#27879]
**Is your feature request related to a problem? Please describe.**
Currently, i2c slave callback APIs are marked as hidden in the documentation which I believe is a little restrictive since we would like to 
create Zephyr applications handling I2C slave  scenarios. 

**Describe the solution you'd like**
All the code is already in place, but we would like to have  the hidden attributte to be removed @cond INTERNAL_HIDDEN

**Comment by ceolin** [comment]
I don't see any problem in make it public if there are application use cases.
