### ISSUE TITLE
Bluetooth: controller: use sys_get_le24 to fetch 24-bit data

### ISSUE THREAD

**Issue by cvinayak** [zephyrproject-rtos/zephyr#27971]
**Is your enhancement proposal related to a problem? Please describe.**
Refer to https://github.com/zephyrproject-rtos/zephyr/pull/27357#discussion_r477324409
and
https://github.com/zephyrproject-rtos/zephyr/pull/27357#discussion_r477319846

**Describe the solution you'd like**
- Use sys_get_le24() to pass crc_init value
- Define CRC polynomial and use the define instead of magic numbers.

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by sappyh** [comment]
Hi, I want to give it a try, can you assign this to me?

**Comment by cvinayak** [comment]
Hi, please go ahead and send a pull request.
