### ISSUE TITLE
TCP2: Apparent issues with client-side connections (hangs when server (apparently) closes connection).

### ISSUE THREAD

**Issue by pfalcon** [zephyrproject-rtos/zephyr#27982]
This is a kind of dual to #27876. While that dealt with Zephyr-as-server case, this is about Zephyr-as-client case, and `samples/net/sockets/big_http_download` sample.

When running that sample (frdm_k64f tested so far), I get:

~~~
Iteration 1 of INF
sock = 0
[00:00:03.000,000] <inf> net_config: Interface 1 (0x20000ef0) coming up
[00:00:03.001,000] <inf> eth_mcux: ETH_0 enabled 100M full-duplex mode.
[00:00:03.001,000] <inf> net_config: IPv4 address: 192.0.2.1
[00:00:03.001,000] <inf> net_config: Running dhcpv4 client...
Download progress: 7015896 Bytes; 6851 KiB; 6 MiB
~~~

At which point it hangs. Looks like another issue with FIN handling.

I tested this with and without https://github.com/zephyrproject-rtos/zephyr/pull/27960, the behavior is the same.

**Comment by pfalcon** [comment]
Ah, forgot to mention that:

> Download progress: 7015896 Bytes

is exactly the size of the file being downloaded, http://archive.ubuntu.com:80/ubuntu/dists/xenial/main/installer-amd64/current/images/hd-media/vmlinuz

**Comment by jukkar** [comment]
Not a high issue as there is a workaround.

**Comment by pfalcon** [comment]
To confirm, the issue also happens with qemu_x86.
