### ISSUE TITLE
call k_malloc or k_mem_slab_alloc allowed or not

### ISSUE THREAD

**Issue by lanvis** [zephyrproject-rtos/zephyr#28020]
We are calling k_malloc() and k_mem_slab_alloc() from our timer and uart ISRs and were not experiencing any issues that we knew of.  We noticed that the documentation does not say it can't be called from an ISR but it doesn't say we can either (like other kernel APIs do).

Can they be called from an ISR?

Thanks

**Comment by andrewboie** [comment]
These APIs use spinlocks for syncrhonization and should be ISR safe, but the timeout value must be K_NO_WAIT for `k_mem_slab_alloc()` as you can't sleep in an ISR.

don't use libc malloc() though ;)

**Comment by andrewboie** [comment]
converting this to a minor documentation issue

**Comment by andyross** [comment]
Note that k_mem_pool_alloc() (soon to be deprecated) and k_heap_alloc() both have the same documentation bug.  They're safe to call in an interrupt as long as the timeout is K_NO_WAIT
