### ISSUE TITLE
nucleo_wb55rg: test/spi/spi_loopback build failure 

### ISSUE THREAD

**Issue by erwango** [zephyrproject-rtos/zephyr#28049]
**Describe the bug**
When building `test/spi/spi_loopback` with nucleo_wb55rg, build failure happens:
```
zephyr/drivers/dma/libdrivers__dma.a(dmamux_stm32.c.obj): in function `dmamux_stm32_init':
/local/mcu/zephyrproject/zephyr/drivers/dma/dmamux_stm32.c:155: undefined reference to `k_malloc'
```

**To Reproduce**
`sanitycheck -b -p nucleo_wb55rg -T tests/drivers/spi`

**Expected behavior**
Test should build

**Comment by FRASTM** [comment]
The pb comes from the CONFIG_HEAP_MEM_POOL_SIZE not defined correctly
which comes from the `drivers/dma/Kconfig.stm32`

**Comment by FRASTM** [comment]
config of the HEAP_MEM_POOL_SIZE depends on DMAMUX_STM32
