### ISSUE TITLE
[mimxrt1050_evk] uart_fifo_fill only  send 1 byte 

### ISSUE THREAD

**Issue by wchyan** [zephyrproject-rtos/zephyr#28045]
**Describe the bug**
Hardware loop lpuart3 back rx/tx   in mimxrt1050_evk, build and run the samples/nfc/nfc_hello to test the lpuart3 function.  The uart_fifo_fill function only sent out 1 byte.

**To Reproduce**
1. west build -b mimxrt1050_evk samples/nfc/nfc_hello/
2. west flash
3. push the SW4

**Expected behavior**
Expect the ISR happened 8 times, like
uart1_init() done
uart1_isr: 61 (1 bytes)
uart1_isr: 73 (1 bytes)
uart1_isr: 64 (1 bytes)
uart1_isr: 73 (1 bytes)
uart1_isr: 61 (1 bytes)
uart1_isr: 0a (1 bytes)
uart1_isr: 73 (1 bytes)
uart1_isr: 73 (1 bytes)

**Impact**
The serial can't work well, and the bluetooth module can't be enabled.

**Logs and console output**
Serial debug console output:

Booting Zephyr OS build zephyr-v2.3.0  ***
Sample app running on: arm
uart1_init() done
uart1_isr: 00 (1 bytes)

**Environment (please complete the following information):**
 - OS: MacOS, Windows
 - Toolchain: gcc-arm-none-eabi-9-2020-q2-update-mac
 - 2.3.0

**Additional context**

Check the  uart_fifo_fill  return length, it's 1 very time.

**Comment by MaureenHelm** [comment]
This sample was removed after 2.3.0
