### ISSUE TITLE
Align MWDT and LD linker scripts

### ISSUE THREAD

**Issue by tejlmand** [zephyrproject-rtos/zephyr#28083]
**Is your enhancement proposal related to a problem? Please describe.**
As discussed in #22668, there is additional risk ascociated with splitting linker files, as one may update one script and not be aware of the other.
Especially related to updating GNU ld, and not mwdt could break code for mwdt unnoticed, as mwdt is not part of CI.

**Describe the solution you'd like**
A single entry point for linker template.

**Describe alternatives you've considered**
n/a

**Additional context**
See comments here:
https://github.com/zephyrproject-rtos/zephyr/pull/22668#discussion_r483867725
https://github.com/zephyrproject-rtos/zephyr/pull/22668#discussion_r483579164

**Comment by evgeniy-paltsev** [comment]
Fixed by #28451
