### ISSUE TITLE
Make SPI speed of SDHC card configurable

### ISSUE THREAD

**Issue by lowlander** [zephyrproject-rtos/zephyr#28092]
The SD-card-spi driver has a hardcoded 400kHz and 4Mhz SPI bus speed, it would be good to make this configurable (maybe via DT?)

**Comment by EminYagmahan** [comment]
This PR #26319 contains already a working fix, but is still blocked due to some conflicts.

**Comment by lowlander** [comment]
@EminYagmahan  thanks for pointing that PR out, I kind of overlooked that, if that ends up in master this issue can be closed.

**Comment by lowlander** [comment]
Closing this because things seem to be fixed in the mentioned PR and with the 2.4.rc1 stage it might take a while for that to be merged, no reason to keep open this bug report for that long (there are already enough others).

**Comment by thelittlebug** [comment]
ok, and now?
the PR is closed and this ticket is closed. nothing changed.
