### ISSUE TITLE
Doc: Getting Started Guide: reel board blinky gif is outdated

### ISSUE THREAD

**Issue by DSc-de** [zephyrproject-rtos/zephyr#28095]
**Describe the bug**
If setting up Zephyr according to the Getting Started Guide including build and flash of blinky sample on reel_board / real_board_v2, one can see blinking of red LED D3 (GPIO P0.11) at the front side. However, the Getting Starting Guide shows blinking of another led: LED D13 ( P0.13) at the back side.

**To Reproduce**
1. build and flash blinky sample for reel_board or reel_board_v2
2. compare blinking led on the board with blinking led in the Getting Started Guide gif
3. observe difference: board blinking on front side, gif blinging on back side

**Expected behavior**
Gif shall show blinking of front LED D3 (GPIO P0.11).

**Impact**
Could confuse new users setting up Zephyr on reel_board / reel_board_v2 according to Getting Started Guide.

**Environment:**
 - OS: Windows
 - Toolchain: GNU ARM embedded
 - Version used: 2.4.0-rc1

**Additional context**
Root cause: blinky controls led0. led0 has been reallocated on the reel_board from the back side led to the front side led. For example, version of 18 Sep 2019 still has "old" mapping which matches the Getting Started Guide blinking.

**Comment by jfischer-phytec-iot** [comment]
> Root cause: blinky controls led0. led0 has been reallocated on the reel_board from the back side led to the front side led.

That is not quite true, the LED on the back was removed and GPIO reused for the buzzer. Actually documentation issue not a bug.

**Comment by carlescufi** [comment]
@DSc-de or @jfischer-phytec-iot will you update the .gif please?

**Comment by DSc-de** [comment]
Below please find the updated gif. If acceptable, please commit to /doc/getting_started/img . Please let me know if I shall do a pull request instead (never done this before but the great zephyr documentation will tell me how to).

![ReelBoard-Blinky](https://user-images.githubusercontent.com/68108999/92525549-5a8a9f00-f224-11ea-81cc-93f409f19b10.gif)
