### ISSUE TITLE
CoAP/LWM2M: Blockwise Observe/Notify

### ISSUE THREAD

**Issue by broglep-work** [zephyrproject-rtos/zephyr#28120]
When LWM2M server observes a large resource that does not fit in one single CoAP packet, the zephyr client should use block-wise transfer for its notify messages. The notify packet should contain block headers, the server then identifies it as block message and will then in return request the other blocks of the notify packet from the zephyr client. 

This use case is specified in https://tools.ietf.org/html/rfc7959#section-2.6 and an example is available at  https://tools.ietf.org/html/rfc7959#section-3.4 (be aware of the difference in terminology in CoAP spec, client = LWM2M server, server = zephyr client)

**Comment by rlubos** [comment]
Blockwise transfer for notifications was added to LwM2M in https://github.com/zephyrproject-rtos/zephyr/pull/54761
