### ISSUE TITLE
mec15xxevb_assy6853:running samples/drivers/espi/ failed

### ISSUE THREAD

**Issue by Zhaoningx** [zephyrproject-rtos/zephyr#28148]
Describe the bug
running samples/drivers/espi/, and there are not output,and the result just block here until system hangs.

To Reproduce

west build -b mec15xxevb_assy6853 samples/drivers/espi/
~/software/ci/tools/usbgpio_ftdi/pre_script.sh
west flash
~/software/ci/tools/usbgpio_ftdi/post_script.sh
see error

*** Booting Zephyr OS build v2.4.0-rc1-11-g8c3efc7be5fe  ***
(no output here)

Environment (please complete the following information):
OS: Fedora28
Toolchain: Zephyr-sdk-0.11.3
Commit ID: g8c3efc7be5fe

**Comment by maksimmasalski** [comment]
Yes, test should work on the Microchip, because in the its datasheet https://github.com/MicrochipTech/CPGZephyrDocs/blob/master/MEC1501/MEC1501_Datasheet.pdf page 165 has a description about eSPI.

**Comment by albertofloyd** [comment]
@maksimmasalski  this is supported in MEC15 chips but similar to PECI, I2C, eSPI bus testing requires another device to act as eSPI host. 
While this sample can be run in EVB the HW connection to a eSPI host (Intel RVP) is not documented/supported.

Suggest to mark as not supported in that HW only in Modular card (which setup is documented)

**Comment by nashif** [comment]
need to change the yaml for this sample file to get excluded. @maksimmasalski  can you please take care of that?

**Comment by maksimmasalski** [comment]
> need to change the yaml for this sample file to get excluded. @maksimmasalski can you please take care of that?

I will do that
