### ISSUE TITLE
tests: drivers: spi: spi_loopback: fails on board nucleo_wb55rg

### ISSUE THREAD

**Issue by ABOSTM** [zephyrproject-rtos/zephyr#28184]
**Describe the bug**
What have you tried to diagnose or workaround this issue?

**To Reproduce**
1. west -p auto -b nucleo_wb55rg tests/drivers/spi/spi_loopback  nucleo_wb55rg
2. west flash
3. See error

**Expected behavior**
test passed

**Logs and console output**
```
*** Booting Zephyr OS build v2.4.0-rc1-10-g4d3580d29735  ***
Running test suite test_spi
===================================================================
START - test_spi_loopback
I: SPI test on buffers TX/RX 0x20000000/0x200004f0
I: SPI test slow config
I: Start complete multiple
I: CS control inhibited (no GPIO device)
E: DMA callback channel 8 is not valid.
E: Code -5

    Assertion failed at WEST_TOPDIR/zephyr/tests/drivers/spi/spi_loopback/src/spi.c:140: spi_complete_multiple: (ret is true)
SPI transceive failed
 FAIL - test_spi_loopback
===================================================================
Test suite test_spi failed.
===================================================================
PROJECT EXECUTION FAILED
```

**Environment (please complete the following information):**
 - OS: Linux and Windows
 - Toolchain : Zephyr SD
 - Commit SHA:4d3580d29735bd3d3d7a89e7475ccd9e001cd818

**Comment by lowlander** [comment]
@ABOSTM sadly I don't have stm32wb hardware to test, but is this a new failure (after I reworked the DMA driver) or did it fail before?  The 8 not valid seems to be a off by one error (the channel, stream, id numbering is very confusing for the v1, v2, and dmamux) 

I could try with L4R5 hardware that should have the same DMAMUX setup.

**Comment by ABOSTM** [comment]
@lowlander , I pushed a PR which solves the issue: #28182.
