### ISSUE TITLE
"make zephyr_generated_headers" produces incorrect result (SHELL:") after recent cmake refactor

### ISSUE THREAD

**Issue by pfalcon** [zephyrproject-rtos/zephyr#28230]
Originally reported at https://github.com/zephyrproject-rtos/zephyr/pull/24851#issuecomment-689501804 :

"cmake: toolchain disable -imacro deduplication" commit from this PR (merged as f109e6839be04f105ede7c2aaecc034b26c0a613) broke "make zephyr_generated_headers" target, specifically creation of Makefile.exports.* (e.g. Makefile.exports.C) files containing CFLAGS, etc. for integration with external build systems. The effect of that can be seen e.g. at https://ci.linaro.org/job/lite-aeolus-micropython/PLATFORM=frdm_k64f,ZEPHYR_TOOLCHAIN_VARIANT=zephyr,label=docker-xenial-amd64-13/1317/console  (Zephyr MicroPython port build) :

> 00:06:44.936 GEN build/genhdr/qstr.i.last
00:06:44.936 arm-zephyr-eabi-gcc: error: SHELL:: No such file or directory
00:06:44.936 arm-zephyr-eabi-gcc: error: SHELL:: No such file or directory

I.e., these `SHELL:` moniker leaks into CFLAGS, and of course leads to errors.

I see that there was a similar problem elsewhere, addressed in 9d501f4ba8fa46bd2f4d1f412a8f2bc68c3126dd. It would be nice to adapt it to "make zephyr_generated_headers" case too.

**Comment by pfalcon** [comment]
(Sorry, I initially mis-pressed Enter and incomplete ticket was submitted, I edited description afterwards, so it might not go into email notification.)

**Comment by tejlmand** [comment]
Fixed: https://github.com/zephyrproject-rtos/zephyr/pull/28232
