### ISSUE TITLE
mimxrt1050_evk: running samples/subsys/fs/fat_fs/ failed

### ISSUE THREAD

**Issue by Zhaoningx** [zephyrproject-rtos/zephyr#28256]
Describe the bug
running samples/subsys/fs/fat_fs/, and no output and timeout failure is reported.

To Reproduce
west build -b mimxrt1050_evk samples/subsys/fs/fat_fs/
west flash
see error

*** Booting Zephyr OS build v2.4.0-rc1-19-gd7468bf836b7  ***
(block here forever)

Environment (please complete the following information):
OS: Fedora28
Toolchain: Zephyr-sdk-0.11.3
Commit ID: d7468bf836b7

**Comment by CristXu** [comment]
> Describe the bug
> running samples/subsys/fs/fat_fs/, and no output and timeout failure is reported.
> 
> To Reproduce
> Steps to reproduce the behavior:
> west build -b mimxrt1050_evk samples/subsys/fs/fat_fs/
> west flash
> see error
> 
> *** Booting Zephyr OS build v2.4.0-rc1-19-gd7468bf836b7 ***
> (block here forever)
> 
> Environment (please complete the following information):
> OS: Fedora28
> Toolchain: Zephyr-sdk-0.11.3
> Commit ID: [d7468bf](https://github.com/zephyrproject-rtos/zephyr/commit/d7468bf836b75c29980441f294a61eae6bf4bc75)

Hi， with a sdcard inserted?
