### ISSUE TITLE
Slave host auto-initiate stalls if master does not support extended reject indications, and procedure collision occurs

### ISSUE THREAD

**Issue by mtpr-ot** [zephyrproject-rtos/zephyr#28282]
**Problem**
If an LLCP collision occurs during auto-initiate, e.g. with PHY_UPDATE, and master sends a REJECT_IND, auto-initatiate is not continued, as no notification is sent to host from LL.

**Impact**
Other host- or app initiated LLCP requests are never sent.

**Additional context**
In function `ctrl_rx` `(ull_conn.c)`, `PDU_DATA_LLCTRL_TYPE_REJECT_IND` is not handled properly. The case needs to handle the packet similar to `reject_ind_phy_upd_recv` in `reject_ext_ind_recv`.

NOTE: This was found on the 2.2.1 branch, but as far as I can tell, it hasn't been fixed on master.

**Comment by cvinayak** [comment]
@mtpr-ot will a PR be upstream soon? I will be available to review/test the same.

**Comment by mtpr-ot** [comment]
> @mtpr-ot will a PR be upstream soon? I will be available to review/test the same.

I'm not sure I can provide the full functionality - I have only fixed locally for PHY_UPDATE. Perhaps I can have Thomas (@thoh-ot) make the full implementation.

**Comment by mtpr-ot** [comment]
The following patch implements REJECT_IND handling for PHY collision only:
[phy_reject_ind_fix.zip](https://github.com/zephyrproject-rtos/zephyr/files/5217145/phy_reject_ind_fix.zip)
