### ISSUE TITLE
Deep sleep(system off) is not working with LVGL and display driver

### ISSUE THREAD

**Issue by honestech74** [zephyrproject-rtos/zephyr#28298]
**Describe the bug**
I am going to write a deep sleep in nRF52840-DK. Also I am using the LVGL to display the graph on the SPI LCD screen. But the application was halted at the beginning in zephyr. I can see only one line on debug output.

**To Reproduce**
1. Merge ```samples/boards/nrf/system_off``` to ```samples/display/lvgl```.
2. add the power management config of system_off sample to lvgl sample.
```
CONFIG_SYS_POWER_MANAGEMENT=y
CONFIG_SYS_POWER_DEEP_SLEEP_STATES=y
# Required to disable default behavior of deep sleep on timeout
CONFIG_SYS_PM_STATE_LOCK=y
CONFIG_GPIO=y
```
3. add the SPI LCD on the nrf52840dk_nrf52840.overlay
for example,
```
&arduino_spi {
	status = "okay";
	cs-gpios = <&arduino_header 16 0>;	/* D10 */

	st7735s@0 {
		compatible = "sitronix,st7735s";
		label = "ST7735S";
		spi-max-frequency = <2625000>;
		reg = <0>;
		cmd-data-gpios = <&arduino_header 15 GPIO_ACTIVE_LOW>;	/* D9 */
		//reset-gpios = <&arduino_header 14 GPIO_ACTIVE_LOW>;	/* D8 */
		width = <160>;
		height = <80>;
		x-offset = <26>;
		y-offset = <1>;
		orientation = <1>;

		frmctrl1-param = [01 2c 2d];
		frmctrl2-param = [01 2c 2d];
		frmctrl3-param = [01 2c 2d 01 2c 2d];
		invctrl = <0x07>;
		pwctrl1-param = [a2 02 84];
		pwctrl2-param = [c5];
		pwctrl3-param = [a0 00];
		pwctrl4-param = [8a 2a];
		pwctrl5-param = [8a ee];
		vmctr1 = <0x0e>;
		madctl = <0xc8>;
		colmod = <0x05>;
		gmctrp1-param = [02 1c 07 12 37 32 29 2d 29 25 2b 39 00 01 03 10];
		gmctrn1-param = [03 1d 07 06 2e 2c 29 2d 2e 2e 37 3f 00 00 02 10];
	};
};
```

**Expected output**
```
*** Booting Zephyr OS build v2.3.0-rc1-ncs1  ***                       
                                                                                
nrf52840dk_nrf52840 system off demo                                             
Busy-wait 2 s                                                                   
Sleep 2 s                                                                                       
Sleep 2000 ms (deep sleep minimum)                                              
Entering system off; press BUTTON1 to restart
```

**Impact**
What impact does this issue have on your progress (e.g., annoyance, showstopper)

**Logs and console output**
```*** Booting Zephyr OS build v2.3.0-rc1-ncs1  ***```

**Environment (please complete the following information):**
 - OS: Ubuntu 18
 - Toolchain Zephyr SDK-11
 - Zephyr version: v2.3.0

**Additional context**
I have merged ```samples/boards/nrf/system_off``` to ```samples/drivers/display```, then it works well.
I guess that LVGL or SPI conflicts with power management.

**Comment by pabigot** [comment]
As I explained on slack: as long as you're using the Nordic fork which apparently doesn't have #26580 enabling deep sleep won't work.  You need to confirm this fails to work on current master, or file this as a bug against the downstream fork, or integrate #26580 and #25490 into your environment.

**Comment by MaureenHelm** [comment]
@honestech74 can you reproduce this issue in upstream master?

**Comment by pabigot** [comment]
Marking as low as this is believed to be fixed; close or reprioritize if that changes.

**Comment by RuslanSpartak** [comment]
What I found on that. Seems that after system off zephyr display driver is not ready, but it is not true. If not adding return statement after unsuccesseful checking if it is ready - all is working as expexted.
