### ISSUE TITLE
Asymmetric nrfx spi_transceive tx/rx lengths outputs error

### ISSUE THREAD

**Issue by mshaw11** [zephyrproject-rtos/zephyr#28317]
**Describe the bug**
Calling spi_transceive using the nrfx library with an asymmetric length of tx and rx buffers it produces the error `<err> spi_nrfx_spi: Update exceeds current buffer`. Making both equal length solves the problem.

**To Reproduce**
````
int8_t err = 0;
uint8_t txData[1] = {0x9F};
uint8_t rxData[4] = {0};
const struct spi_buf tx_buf = { .buf = txData, .len = 1 };
const struct spi_buf_set tx_buf_set = { .buffers = &tx_buf, .count = 1 };
const struct spi_buf rx_buf = { .buf = rxData, .len = 4 };
const struct spi_buf_set rx_buf_set = { .buffers = &rx_buf, .count = 1 };
err = spi_transceive(handle->spi_device, &handle->spiConfig, &tx_buf_set, &rx_buf_set);
````

**Expected behavior**
I would expect that it would be okay to have assymetric tx and rx lengths. I’ve written a few drivers now with the assumption this didn’t matter as normally if I don’t specify tx data it’s because the chip I’m talking to doesn’t care either, this saves me filling buffers with dummy bytes. Some zephyr samples use a null buffer instead.

If this is intended then the error could be a bit clearer and it might be worth adding to the release notes that this is now considered an error. 

**Impact**
This will impact existing drivers. The error printing every SPI call is likely to have performance implications if not caught by the user. 

**Logs and console output**
`[01556626] <err> spi_nrfx_spi: Update exceeds current buffer`

GDB stack trace of error location (line 265 and 315 of spi_context.h).
````
(gdb) bt
#0  spi_context_update_tx (len=4, dfs=1 '\001', ctx=0x20000960 <spi_2_data>) at /Users/matthew/git/firmware/zephyr/drivers/spi/spi_context.h:265
#1  event_handler (p_event=0x20006328 <m_cb+48>, p_context=0x20000960 <spi_2_data>) at /Users/matthew/git/firmware/zephyr/drivers/spi/spi_nrfx_spi.c:253
#2  0x00022486 in finish_transfer (p_cb=p_cb@entry=0x20006320 <m_cb+40>) at /Users/matthew/git/firmware/modules/hal/nordic/nrfx/drivers/src/nrfx_spi.c:239
#3  0x0002255a in irq_handler (p_spi=p_spi@entry=0x40023000, p_cb=p_cb@entry=0x20006320 <m_cb+40>) at /Users/matthew/git/firmware/modules/hal/nordic/nrfx/drivers/src/nrfx_spi.c:411
#4  0x00022da6 in nrfx_spi_2_irq_handler () at /Users/matthew/git/firmware/modules/hal/nordic/nrfx/drivers/src/nrfx_spi.c:432
#5  0x0002eea8 in nrfx_isr (irq_handler=<optimized out>) at /Users/matthew/git/firmware/modules/hal/nordic/nrfx_glue.c:12
#6  0x0000bcc6 in _isr_wrapper () at /Users/matthew/git/firmware/zephyr/arch/arm/core/aarch32/isr_wrapper.S:186
````

**Environment (please complete the following information):**
 - OS: MacOS
 - Toolchain Gnuarmemb
 - Commit SHA: eb2a705497394497f64feeb49e80219fed2513ae (Zephyr master 11/09/2020)

**Comment by pabigot** [comment]
Just a marker: my comment on slack was the following:

> That may be a bug, or an underspecified API.  AIUI the transaction length should be the greater of the lengths of the tx and rx buffer sets.  Where a corresponding buffer is NULL, the corresponding data is unspecified (tx) or discarded (rx).  I would think that if one buffer set is shorter than the other that the effect should be the same as adding a null buffer for the difference in length to the set that's short.
> That may not be what's actually done, though.  If that's what you're trying, and it doesn't work, could you open an issue that we can use to investigate this and at minimum improve the documentation (if it isn't clear)? (edited) 

I.e. this may be a cross-platform concern related to the SPI API.  So I'd like to it to get some visibility at that level as well.  @tbursztyka
