### ISSUE TITLE
What is the airspeed velocity of an unladen swallow running Zephyr?

### ISSUE THREAD

**Issue by mbolivar-nordic** [zephyrproject-rtos/zephyr#28332]
What is the airspeed velocity of an unladen swallow running Zephyr?

_Originally posted by @mbolivar-nordic in https://github.com/zephyrproject-rtos/zephyr/discussions/28328_

**Comment by utzig** [comment]
> What is the airspeed velocity of an unladen swallow running Zephyr?

What do you mean? African or European swallow?

**Comment by mbolivar-nordic** [comment]
I don't know that....
