### ISSUE TITLE
Document limitations of net_buf queuing functions

### ISSUE THREAD

**Issue by JordanYates** [zephyrproject-rtos/zephyr#28355]
**Is your enhancement proposal related to a problem? Please describe.**
The current documentation for `net_buf_get` and `net_buf_slist_get` does not specify that the functions are only safe to use from a single thread if the net_buf contains fragments.

**Describe the solution you'd like**
Documentation that describes the above, or an alternate implementation that does not suffer the same problems.

**Additional context**
The functions are not thread safe due to multiple independent calls to `k_fifo_get`, which can be interrupted at any point in time.
The `net_buf_put` variants are fine as they use an atomic function `k_fifo_put_list`.

**Comment by jhedberg** [comment]
I vaguely remember some discussion around moving to use a separate fragments list net_buf struct member rather than reusing the first four bytes of the net_buf struct (combined with flags) for this purpose. This would remove this limitation in the implementation. @carlescufi  was it with you that this came up?

**Comment by carlescufi** [comment]
> I vaguely remember some discussion around moving to use a separate fragments list net_buf struct member rather than reusing the first four bytes of the net_buf struct (combined with flags) for this purpose. This would remove this limitation in the implementation. @carlescufi was it with you that this came up?

It might've been because I also have a vague recollection of this. I am not up to speed with the problem right now, but feel free to include me in a discussion about this after the release.
