### ISSUE TITLE
USB audio samples fails if ASSERT=y

### ISSUE THREAD

**Issue by alexsven** [zephyrproject-rtos/zephyr#28361]
**Describe the bug**
Running the USB audio samples for nrf5340dk_nrf5340_cpuapp fails on ASSERT in nrf_usbd.h:1273 if asserts are turned on

**To Reproduce**
1. cd samples\subsys\usb\audio\headphones_microphone
2. west build -b nrf5340dk_nrf5340_cpuapp
3. west flash
4. See error on UART

**Comment by emob-nordic** [comment]
The issue is visible when trying to set dtoggle for ISO endpoint. It is not applicable as those type of endpoints does not support dtoggle, will post a patch that will filter it out.
