### ISSUE TITLE
bq274xx sample is not working

### ISSUE THREAD

**Issue by jrananth1032** [zephyrproject-rtos/zephyr#28383]
**Describe the bug**
I am trying to get bq27421 up and running on our developement board(soc:nrf52840).But sample is not working, because in sample trying to fetch samples for all channels(SENSOR_CHAN_ALL) ,but driver does not handling SENSOR_CHAN_ALL
**To Reproduce**
1. west build 
2. Opened minicom
4. Seeing values as zero for all the channels

**Environment (please complete the following information):**
 - OS: Linux
 - gcc-arm-none-eabi-9-2020-q2-update
 - revision: 0742a45ac9f51d45f7b1fe148ac7d9bbfecb2f83

**Comment by MaureenHelm** [comment]
@parthitce will you please take a look?

**Comment by jrananth1032** [comment]
It is not a big issue , just need to read each channel one by one otherwise ,SENSOR_CHAN_ALL should be handled in driver.

**Comment by parthitce** [comment]
> @parthitce will you please take a look?

@MaureenHelm Sure I will.

**Comment by parthitce** [comment]
PR [28429](https://github.com/zephyrproject-rtos/zephyr/pull/28429) fixed this issue. Closing this issue @jrananth1032. Please re-open if anything else needs to be added.
