### ISSUE TITLE
SHIELD not handled correct in CMake when using custom board

### ISSUE THREAD

**Issue by lund-prevas** [zephyrproject-rtos/zephyr#28462]
In CMakeList.txt set BOARD_ROOT and SHIELD e.g
set(BOARD_ROOT ${MY_CUSTOM_BOARD_ROOT})
set(SHIELD myShield)
.
pull in the Zephyr boilerplate

CMake will then look for the myShield DTS overlay in ${MY_CUSTOM_BOARD_ROOT}/boards/shields/myShield
but it will look for the Kconfig.shield in .../zephyr/boards/shields/myShield
Furthermore is the SHIELD_AS_LIST only set to myShield, when CMake scans ${MY_CUSTOM_BOARD_ROOT}, it is empty when it scans zephyr/boards

Expected behaviour would be both DTS overlay and Kconfig.shield was found in same location.
First look for ${MY_CUSTOM_BOARD_ROOT}/boards/shields/myShield
and if not found look for .../zephyr/boards/shields/myShield

**Comment by erwango** [comment]
@tejlmand would you have time to check this ?

**Comment by lund-prevas** [comment]
Any update on this issue ?

**Comment by tejlmand** [comment]
@lund-prevas Fixed here: #29571
