### ISSUE TITLE
Fix nanosleep(2) for sub-microsecond durations

### ISSUE THREAD

**Issue by cfriedt** [zephyrproject-rtos/zephyr#28483]
**Is your enhancement proposal related to a problem? Please describe.**
Nanosleep should probably round-up instead of down for sub-microsecond durations.

This is just a placeholder for now until I have a few spare cycles.

https://github.com/zephyrproject-rtos/zephyr/issues/28394#issuecomment-692731513

cc @pabigot 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by pabigot** [comment]
This is really a bug, since no sleep should ever expire in less than the specified time.
