### ISSUE TITLE
FCB support for non-0xFF flash erase values

### ISSUE THREAD

**Issue by de-nordic** [zephyrproject-rtos/zephyr#28693]
**Is your enhancement proposal related to a problem? Please describe.**
Currently FCB is able to work with flash devices that erase to 0xFF values.
Since it's implementation new devices have appeared that use non-0xFF erase values (0x00), which is not supported
by the FCB as it relies on 0xFF as an erased/empty value in some cases.

**Describe the solution you'd like**
Make FCB flash erase value independent.

**Describe alternatives you've considered**
There is none as long as FCB is to be used.

**Additional context**
The flash API now supports  `flash_get_parameters` that returns `flash_parameters` structure that has `erase_value` member, which is initialized by driver with the erase value.

**Comment by nvlsianpu** [comment]
Also newly proposed [flash_area_ersed_val()](//github.com/zephyrproject-rtos/mcuboot/pull/35) might be usefull.

**Comment by utzig** [comment]
Also we should consider importing `fcb2` from Mynewt, it was huge improvement over `fcb`.

**Comment by de-nordic** [comment]
> 
> 
> Also we should consider importing `fcb2` from Mynewt, it was huge improvement over `fcb`.

Does the fcb2 support the original fcb or this is parallel?

**Comment by utzig** [comment]
> > Also we should consider importing `fcb2` from Mynewt, it was huge improvement over `fcb`.
> 
> Does the fcb2 support the original fcb or this is parallel?

`fcb2` originated from refactoring `fcb` but it ended up with a slightly different metadata formats AFAIR, so not compatible, you have to use one or the other from the beginning.

**Comment by de-nordic** [comment]
> 
> `fcb2` originated from refactoring `fcb` but it ended up with a slightly different metadata formats AFAIR, so not compatible, you have to use one or the other from the beginning.

OK then, we will have to add it as an alternative. Do you want me to create enhancement request for importing `fcb2` or do you want to post the request  yourself?

**Comment by utzig** [comment]
> > `fcb2` originated from refactoring `fcb` but it ended up with a slightly different metadata formats AFAIR, so not compatible, you have to use one or the other from the beginning.
> 
> OK then, we will have to add it as an alternative. Do you want me to create enhancement request for importing `fcb2` or do you want to post the request yourself?

Please go ahead and do it! :-)

**Comment by nvlsianpu** [comment]
^^ Please count benefits of having fcb2 in compassion to FCB and NVS.
