### ISSUE TITLE
phandle-array doesn't allow array of just phandles

### ISSUE THREAD

**Issue by ChaosinaCan** [zephyrproject-rtos/zephyr#28709]
**Describe the bug**

https://github.com/zephyrproject-rtos/zephyr/blob/0a0cb52fb2290b825f4e6b0d8d1f7bfad358cf01/dts/binding-template.yaml#L157-L160 indicates that in a value of type phandle-array, numbers are optional, so `<&foo &bar>` should be valid.

However, https://github.com/zephyrproject-rtos/zephyr/blob/0a0cb52fb2290b825f4e6b0d8d1f7bfad358cf01/scripts/dts/edtlib.py#L1225-L1230  appears to only allow `TYPE_PHANDLE` (a single phandle) and `TYPE_PHANDLES_AND_NUMS`. Is that supposed to be `TYPE_PHANDLES` instead of `TYPE_PHANDLE`?

**To Reproduce**

1. [Set up the ZMK keyboard firmware project](https://zmkfirmware.dev/docs/dev-setup).
2. Edit `app/boards/shields/romac/romac.keymap` and change one of the `bindings` arrays to contain only values such as `&reset` and `&trans` so there are no numbers in the array.
3. Build with 
```
cd app
west build -b proton_c -- -DSHIELD=romac
```

This will fail with an error like

> devicetree error: expected property 'bindings' in /keymap/nav_layer in proton_c.dts.pre.tmp to be assigned with 'bindings = < &foo 1 2 ... &bar 3 4 ... >' (a mix of phandles and numbers), not 'bindings = < &reset &trans &trans &trans &trans &trans  &trans &trans &trans  &trans &trans &trans >;'

**Expected behavior**
As far as I can tell, an array of just phandles should be valid for a phandle-array.

**Impact**
Annoyance. Can be worked around by adding something that uses numbers somewhere in the array.

**Environment (please complete the following information):**
 - OS: Windows 10
 - Toolchain: GNU Arm Embedded
 - Commit SHA or Version used: https://github.com/petejohanson/zephyr/tree/zmk-v2.3.0-with-fixes

**Comment by henrikbrixandersen** [comment]
How about `<&foo>, <&bar>`?

**Comment by ChaosinaCan** [comment]
Same error (tested in a different keymap with a slightly different array):

> devicetree error: expected property 'bindings' in /keymap/daw_layer in nice_nano.dts.pre.tmp to be assigned with 'bindings = < &foo 1 2 ... &bar 3 4 ... >' (a mix of phandles and numbers), not 'bindings = < &none >, < &none >, < &none >, < &none >, < &none >, < &none >, < &none >, < &none >, < &trans >, < &none >, < &none >, < &none >, < &none >, < &none >, < &none >, < &none >;'

**Comment by b0661** [comment]
https://github.com/zephyrproject-rtos/zephyr/blob/0a0cb52fb2290b825f4e6b0d8d1f7bfad358cf01/dts/binding-template.yaml#L157-L160 the ´(possibly)´ relates to ´32-bit´ (and *not* to numbers). phandle-array is always a combination of phandle and associated number(s). The numbers may be up to 32-bit size. In case you only have phandles just use ´phandles´ in the binding.

´(possibly)´ should possibly replaced or removed.

**Comment by ChaosinaCan** [comment]
> phandle-array is always a combination of phandle and associated number(s).

I'll admit I am still very unfamiliar with DT, but I'm confused as to why edtlib.py allows phandle-array to be either `TYPE_PHANDLE` or `TYPE_PHANDLES_AND_NUMS` then.

Having phandles with no associated numbers seems to work as long as there is at least one number somewhere in the array. If phandle-array allows any element to be a phandle with no associated number, why is it not valid for the entire array to be made of such elements? If that is not valid, then should phandle-array _require_ every phandle to have at least one associated number?

I don't know if DT was intended to be used like this, but one of the ways it is used in ZMK is to define a mapping between keyboard keys and the behaviors to use when each key is pressed. Some behaviors such as `&kp KEY` and `&lt LAYER KEY` have one or more associated numbers. Other behaviors such as `&reset` and `&none` don't have any associated numbers. ZMK allows you to mix both types of behaviors in a keymap.

**Comment by b0661** [comment]
> Having phandles with no associated numbers seems to work as long as there is at least one number somewhere in the array. If phandle-array allows any element to be a phandle with no associated number, why is it not valid for the entire array to be made of such elements?

You are right, the error check seems too strict for the degenerated case that you describe. 
https://github.com/zephyrproject-rtos/zephyr/blob/adb62ea290ee4d127c5134630489f64c43c252ef/scripts/dts/edtlib.py#L1229

I could not find `behaviors.dtsi` which defines the behavior nodes. The reset and none nodes should have properties like `xxx-cells = 0;` that define the count of values to be 0. With this given the phandles list as a degenerated phandles-array is a valid construct.

In my view TYPE_PHANDLES should be added to the allowed dtslib types for `phandle-array`.

**Comment by ChaosinaCan** [comment]
> I could not find behaviors.dtsi which defines the behavior nodes. The reset and none nodes should have properties like xxx-cells = 0; that define the count of values to be 0.

Yep. See https://github.com/zmkfirmware/zmk/blob/main/app/dts/behaviors/none.dtsi for example.

Should `TYPE_PHANDLE` be kept and `TYPE_PHANDLES` added, or should that be replaced with `TYPE_PHANDLES`?

**Comment by b0661** [comment]
> Should TYPE_PHANDLE be kept and TYPE_PHANDLES added

Yes. Looking at https://github.com/zephyrproject-rtos/zephyr/blob/1342d12500867d3de09025037e65e756d5486eba/scripts/dts/dtlib.py#L1353-L1357 suggests that TYPE_PHANDLE and TYPE_PHANDLES are valid types.

**Comment by mbolivar-nordic** [comment]
> TYPE_PHANDLE and TYPE_PHANDLES are valid types.

Agreed; I'll send a PR
