### ISSUE TITLE
Bluetooth: provide `struct bt_conn` to ccc_changed callback

### ISSUE THREAD

**Issue by JordanYates** [zephyrproject-rtos/zephyr#28722]
**Is your enhancement proposal related to a problem? Please describe.**

It is currently not possible from application code for a CCC write to trigger events on that same connection.
The current callback does not contain enough information for this to occur.
The current arguments are the attr that changed (the CCC descriptor itself) and its new value.

Each CCC descriptor is unique per connection, per the Bluetooth Core Specification (3.3.3.3):
```
In the case where multiple ATT bearers from the same device are supported by the GATT server,
each ATT bearer shall be considered to have a separate GATT client instance. Therefore each GATT
client shall have a separate Client Characteristic Configuration.
```

Therefore applications should be notified of **which** connection has written to the CCC descriptor.

**Describe the solution you'd like**

`struct bt_conn` should be provided to the `ccc_changed ` callback.
This will also bring it in line with the `ccc_write` callback, which does take a `struct bt_conn` parameter.

**Describe alternatives you've considered**

`ccc_write` does provide the connection object, but before the write has actually been applied.
It is also called regardless of whether the value has actually changed.
AFAICT that callback is intended to be used to save CCC values for later, not notification.
It is also not possible to use this callback through the `BT_GATT_CCC()` constructor.

**Comment by JordanYates** [comment]
Given that "just use `ccc_write`" is a valid answer to this request, I will await feedback before implementing anything.

**Comment by JordanYates** [comment]
Per slack, manually constructing the CCC characteristic is the way forward.
```
BT_GATT_CCC_MANAGED(((struct _bt_gatt_ccc[])
					    { BT_GATT_CCC_INITIALIZER(NULL, uc_bt_ccc_data_written, NULL) }),
					   BT_GATT_PERM_READ | BT_GATT_PERM_WRITE)
```
`ccc_changed` is not useful for applications that care about the actual changed value of the CCC characteristic per connection, as all connections are grouped together.

**Comment by JordanYates** [comment]
One downside of using `ccc_write` instead of `ccc_changed`  that I realised later is that the GATT layer doesn't recognize that the characteristic has been subscribed at that point in the function.

i.e. you can't call `bt_gatt_notify` inside the `ccc_write` callback.

**Comment by ChumKiu** [comment]
I've a peripheral device that have to get two connection from two central, one central have to activate some standard services and another one that have to activate a custom service, how to know what is the connection that have activated the custom service if into the bss_ccc_cfg_changed I do not know what service have selected the CCC inside my custom service?
Thanks for any hint.
BR
