### ISSUE TITLE
Bug in drivers/modem/hl7800.c

### ISSUE THREAD

**Issue by picsil** [zephyrproject-rtos/zephyr#28745]
**Describe the bug**
Compilation fails if CONFIG_MODEM_HL7800_FW_UPDATE is defined. On line 4673 the call to fs_open is missing a parameter.

**To Reproduce**
Enable CONFIG_MODEM_HL7800_FW_UPDATE in prj.conf
Build any project using board pinnacle_100_dvk / HL7800 modem.

**Expected behavior**
Code compiles with this config option enabled

**Impact**
Workaround by modifying hl7800.c, but this should be fixed.

**Logs and console output**
    /home/reid/software/p3-2.4.0/zephyr/drivers/modem/hl7800.c: In function 'mdm_hl7800_update_fw':
    /home/reid/software/p3-2.4.0/zephyr/drivers/modem/hl7800.c:4673:8: error: too few arguments to function 'fs_open'
     4673 |  ret = fs_open(&ictx.fw_update_file, file_path);
          |        ^~~~~~~
    In file included from /home/reid/software/p3-2.4.0/zephyr/drivers/modem/hl7800.c:41:
    /home/reid/software/p3-2.4.0/zephyr/include/fs/fs.h:225:5: note: declared here
      225 | int fs_open(struct fs_file_t *zfp, const char *file_name, fs_mode_t flags);
          |     ^~~~~~~
    [31/189] Building C object zephyr/subsys/net/ip/CMakeFiles/subsys__net__ip.dir/utils.c.obj
    ninja: build stopped: subcommand failed.
    FATAL ERROR: command exited with status 1: /usr/bin/cmake --build /home/reid/software/p3-2.4.0/P3/build

**Environment (please complete the following information):**
Linux. Fresh codebase, trying to compile my project after a clean west init ; west update. Zephyr version 2.4.0.

**Additional context**
To fix, change hl7800.c line 4673 to read:
    ret = fs_open(&ictx.fw_update_file, file_path, FS_O_READ);

**Comment by rerickson1** [comment]
PR https://github.com/zephyrproject-rtos/zephyr/pull/28766 resolved this.
