### ISSUE TITLE
STM32: SPI DMA Driver - HW CS handling not compatible with spi_nor (Winbond W25Q)

### ISSUE THREAD

**Issue by LuxLuthor** [zephyrproject-rtos/zephyr#28833]
**Describe the bug**
When spi_nor driver is sending command over SPI it uses two rx buffers and two tx buffers. In current implementation in function transceive_dma (spi_ll_stm32.c) SPI peripheral is turned off after each buffer finishes resulting in CS pin being pulled up between bytes send. Flash that I use (Winbond W25Q) after falling edge on CS expect command to be send therefore communication does not work. 

**To Reproduce**
1. Always reproducible when using spi_nor driver with spi_dma turned on and hardware slave select
CONFIG_SPI_NOR=y
CONFIG_SPI_STM32_USE_HW_SS=y
CONFIG_SPI_STM32_DMA=n

**Expected behavior**
CS not being pulled up when switching DMA for next buffer. This is how it behaves when software CS is used. 

**Impact**
Prevents SPI flash chips form being used with DMA

**Comment by lowlander** [comment]
@LuxLuthor what SOC are you using ?

**Comment by LuxLuthor** [comment]
> @LuxLuthor what SOC are you using ?

I use ST32WB55RG

**Comment by lowlander** [comment]
> I use STM32WB55RG

Hmm one of the only few STM SOC's I don't have :-/

But I assume the problem happens on all STM32 SOC's, I am not sure if it can be fixed, will have to dive deeper into the DMA/SPI documentation to see how it can be done.

>Impact Prevents SPI flash chips form being used with DMA

You mean not being able to use DMA + HW CS, right ? 

For your use case would using "software" CS be a workaround, or is there a special reason you want/need "hardware" CS support?

**Comment by LuxLuthor** [comment]
I would guess that this is visible on every STM32. Using software CS would be a workaround but I looked into driver code and moved turning SPI peripheral ON and OFF outside while loop that is handling iteration over buffers. It seems to work well now. I will make pull request later today.

**Comment by lowlander** [comment]
> moved turning SPI peripheral ON and OFF outside while loop that is handling iteration over buffers.

We will really have to double check if that doesn't have any side effects, the DMA timing is a bit tricky.  But we can discus that in your PR.

**Comment by LuxLuthor** [comment]
I removed only disabling SPI peripheral. TXDMAEN RXDMAEN stayed in place. Tested on WB55RG with Winbond W25Q and works fine. Enabling/disabling TXDMAEN RXDMAEN while SPI enabled does not seem to be against manual.
