### ISSUE TITLE
code_relocation sample does not work on windows 

### ISSUE THREAD

**Issue by KevinThompson-SR** [zephyrproject-rtos/zephyr#28847]
code_relocation sample doesn't work on windows (paths in Windows includes ":", which causes problems).

**To Reproduce**
1. /zephyr/samples/application_development/code_relocation example
2. nrf5340pdk_nrf5340
3. using .proj and CMakeList.txt
4. Build Error:  Occurs because the result of line.split(':') contains three elements (["'SRAM2", 'C', '/code_relocation/src/test_file1.c']) and it tries to assign it to two variables (see here).

**Expected behavior**
Relocate desired regions to SRAM.

**Impact**
CRITICAL: Required for final test of our product... We move all regions to SRAM during manufacturing test 

other (build):
Booting: *** Booting Zephyr OS build v2.3.0-rc1-ncs2 ***
using: nrf5340pdk_nrf5340_cpunet

**Logs and console output**
build will fail: Segger Embedded Studio for ARM

**Environment (please complete the following information):**
 - OS: Windows 10
 - nRF Connect SDK v1.3.1

**Additional context**
Modifying gen_relocate_app.py caused other errors... I think it would be wise for the domain expert to take this one on and provide a fix.... would be greatly appreciated!  Best - Kevin

**Comment by jturnsek** [comment]
The same with mimxrt1064_evk board.

**Comment by tejlmand** [comment]
@KevinThompson-SR @jturnsek  Fixed here: #30528
