### ISSUE TITLE
Automatic reviewer assignment for PR does not seem to work anymore

### ISSUE THREAD

**Issue by eugmes** [zephyrproject-rtos/zephyr#28979]
**Describe the bug**
Newly created PRs don't get reviewers assigned automatically anymore.

**To Reproduce**
1. Create a PR changing some files.
2. See that there are no reviewers assigned.

**Expected behavior**
Required reviewers are assigned automatically.

**Impact**
PRs have no reviewers and no way to add reviewers manually.

**Additional context**
Here are two examples from me:

* https://github.com/zephyrproject-rtos/zephyr/pull/28978
* https://github.com/zephyrproject-rtos/zephyr/pull/28918

**Comment by MaureenHelm** [comment]
Fixed by #28983
