### ISSUE TITLE
clarify thread life-cycle documentation

### ISSUE THREAD

**Issue by andrewboie** [zephyrproject-rtos/zephyr#28970]
**Describe the bug**
Noted in code review for https://github.com/zephyrproject-rtos/zephyr/pull/28926. The documentation states:

> The kernel does not currently make any claims regarding an application’s ability to respawn a thread that terminates.

This is apparently very old. Re-visit this to make clear what limitations the kernel has with respect to thread lifecycle and thread object re-use.

**Comment by andyross** [comment]
Cleaning up some stale bugs, I added a rewrite to this doc section at: https://github.com/zephyrproject-rtos/zephyr/pull/31498

I **think** that should address the specific confusion here, but I wasn't part of the original discussion so there may have been some side questions that went unanswered.  Please review if you have input.
