### ISSUE TITLE
Docs: Dead links to sample source directories

### ISSUE THREAD

**Issue by martinjaeger** [zephyrproject-rtos/zephyr#28990]
Links to sample source files point to `docs.zephyrproject.org` instead of `github.com`.

Example: https://docs.zephyrproject.org/latest/samples/net/gsm_modem/README.html

Link behind `samples/net/gsm_modem` points to:

```https://docs.zephyrproject.org/blob/master/samples/net/gsm_modem```

instead of:

```https://github.com/zephyrproject-rtos/zephyr/blob/master/samples/net/gsm_modem```

**Comment by nashif** [comment]
@utzig you recently made a change here (#28245), can you please take a look?

**Comment by utzig** [comment]
This seems to happen after the update to `west==0.8.0`; previously `WestManifest.from_file().get_projects(['zephyr'])[0].url` was `None`, now with `0.8.0` it is not anymore, so I'll check what changed there. Any tips @mbolivar-nordic?

**Comment by mbolivar-nordic** [comment]
>  Any tips @mbolivar-nordic?

Looks like you figured it out from the API changes documentation?
