### ISSUE TITLE
Boards: nucleo_stm32g474re does not build

### ISSUE THREAD

**Issue by alexanderwachter** [zephyrproject-rtos/zephyr#29047]
**Describe the bug**
The devicetree was switched to use use pinctrl, but the pinctrl dtsi file is not in the tree

Please add the stm32g474r(b-c-e)tx-pinxtrl.dtsi file to rhe tree

**Comment by gmarull** [comment]
The file exists: https://github.com/zephyrproject-rtos/hal_stm32/blob/master/dts/st/g4/stm32g474r(b-c-e)tx-pinctrl.dtsi. Can you check if modules are updated?

**Comment by alexanderwachter** [comment]
Oh. That is in the HAL. Is there a reason for that?
