### ISSUE TITLE
Bluetooth: Host: Inconsistent permission value during discovery procedure

### ISSUE THREAD

**Issue by boachair** [zephyrproject-rtos/zephyr#29083]
**Describe the bug**
After calling Zephyr Bluetooth API, bt_gatt_discover(), GATT client expects a response structured as Attribute, which contains one permission field (see below). However, it is always 0 now. It might be caused because the GATT server response does not update this attribute permission.

--
struct bt_gatt_attr {
/** Attribute UUID */
const struct bt_uuid *uuid;
...
/** Attribute user data */
void *user_data;
/** Attribute handle */
u16_t handle;
/** Attribute permissions */
u8_t perm;
};

**To Reproduce**
1. call Zephyr API, bt_gatt_discover() with discover type as the primary service
2. Read the permission field in the response (structured as Attribute) in the callback

**Expected behavior**
The Attribute Permissions shall be read-only (BT_GATT_PERM_READ).

**Impact**
annoyance

**Logs and console output**
None

**Environment (please complete the following information):**
- Zephyr 2.4.0
- nRF52840 DK

**Additional context**
None

**Comment by joerchan** [comment]
@boachair What is the annoyance there? The permissions on the field is not sent, which is why it is not set of the attribute structure. I don't see setting it to "READ" as something that provides any useful information.

**Comment by boachair** [comment]
There exists a difference in discovering service and characteristics, i.e., Characteristic discovery returns the permission field as 1 (READ only) in the callback, while Primary Service/included service discovery return this permission as 0. However, the requirement for attribute permission are the same for both.

**Comment by joerchan** [comment]
@boachair Yes I noticed that, and I'd like to fix that. However what I would like to do is to set it to 0 in all cases, and then document that this field is not valid in the discovery callback.

Setting them to be "READ" would only be misleading, since we don't actually know the correct permissions, and there is no way to retrieve them either.

**Comment by joerchan** [comment]
@nashif I set it to low instead. It's just an inconsistency in the parameters, nothing is missing.
