### ISSUE TITLE
usb: allow more extensive settings of the device descriptor

### ISSUE THREAD

**Issue by jfischer-no** [zephyrproject-rtos/zephyr#29134]
It should be possible to configure the device descriptor
during runtime by the user before the USB stack is enabled.
The following properties of the device descriptor should to
be adjustable by the user:
idVendor, idProduct, iSerialNumber, bcdDevice,
(to consider: bDeviceClass, bDeviceSubClass, bDeviceProtocol).

The following properties of the Configuration Descriptor
should be adjustable by the user: bmAttributes, bMaxPower.

**Comment by carlescufi** [comment]
Fixed in the new USB stack, use `CONFIG_USB_DEVICE_STACK_NEXT` to enable it.
