### ISSUE TITLE
usb: USB device stack should store and validate the device state

### ISSUE THREAD

**Issue by jfischer-no** [zephyrproject-rtos/zephyr#29133]
USB device stack does not track or validate the device state (Figure 9-1, USB 2.0 spec).                                                                   
At least the states: Attached, Addressed, Configured, Suspended should be tracked.                                                           
Current device state is required for validation and processing of control requests,                                                          
and at the class level for correct management of devices like CDC ACM or HID.

**Comment by carlescufi** [comment]
Fixed in the new USB stack, use `CONFIG_USB_DEVICE_STACK_NEXT` to enable it.
