### ISSUE TITLE
usb: allow the instances of a USB class to be enabled and disabled at runtime

### ISSUE THREAD

**Issue by jfischer-no** [zephyrproject-rtos/zephyr#29135]
Allow the instances of a USB class to be enabled and disabled at runtime.
Before the USB stack is initialized it should be possible to enable and disable
the built-in instances of a class (e.g. CDC_ACM0, CDC_ACM1...).
The order in which the instances are mapped
in the descriptor should be the same as the order in which they are registered.
Advantage for the user is that one can change the role of the device at runtime,
but it is also very useful for testing of the stack.

**Comment by carlescufi** [comment]
Fixed in the new USB stack, use `CONFIG_USB_DEVICE_STACK_NEXT` to enable it.
