### ISSUE TITLE
usb: USB device stack should track and check the state of control transfers

### ISSUE THREAD

**Issue by jfischer-no** [zephyrproject-rtos/zephyr#29132]
USB spec. Chapter "8.5.3" describes the  Control Transfers. 
The USB stack does not track the state and does not check the correctness of the stages. 
Although the real drawbacks of this are minor, it makes troubleshooting and 
validation of the drivers more difficult.

**Comment by carlescufi** [comment]
Fixed in the new USB stack, use `CONFIG_USB_DEVICE_STACK_NEXT` to enable it.
