### ISSUE TITLE
shell_print doesn't support anymore %llx when used with newlib

### ISSUE THREAD

**Issue by sdalu** [zephyrproject-rtos/zephyr#29165]
Since upgraded to zephyr 2.4, the `%llx` support for 64bit is not available anymore when using `shell_print` with `NEWLIB` enabled.

**Comment by pabigot** [comment]
Side effect of #27655: I missed that `z_prf` had a Kconfig to enable this functionality when I moved it into lib/os.

**Comment by pabigot** [comment]
This should have been fixed as a result of #29876
