### ISSUE TITLE
sanitycheck: sanitycheck defines test expected to fail as FAILED

### ISSUE THREAD

**Issue by maksimmasalski** [zephyrproject-rtos/zephyr#29259]
**Describe the bug**
I've developed test that is expected to fail with ZEPHYR FATAL ERROR 3. That PR of my test #29188
When I run it using west, it works fine. When I run it using sanitycheck, sanitycheck verdict 

**Logs and console output**
```
DEBUG   - QEMU: Test suite queue_api succeeded
DEBUG   - QEMU: ===================================================================
DEBUG   - QEMU: PROJECT EXECUTION SUCCESSFUL
DEBUG   - QEMU complete (failed) after 2.173544 seconds
DEBUG   - No timeout, return code from qemu: 0
DEBUG   - return code from qemu: 0
DEBUG   - run status: failed
DEBUG   - QEMU complete (failed) after 2.259162 seconds
DEBUG   - No timeout, return code from qemu: 0
DEBUG   - return code from qemu: 0
DEBUG   - run status: failed
INFO    - 1/2 qemu_x86                  tests/kernel/queue/kernel.queue                    FAILED Failed (qemu 2.259s)
ERROR   - see: /home/maksim/zephyrproject/zephyr/sanity-out/qemu_x86/tests/kernel/queue/kernel.queue/handler.log
INFO    - 2/2 qemu_x86                  tests/kernel/queue/kernel.queue.poll               FAILED Failed (qemu 2.174s)
ERROR   - see: /home/maksim/zephyrproject/zephyr/sanity-out/qemu_x86/tests/kernel/queue/kernel.queue.poll/handler.log

DEBUG   - running footprint_reports
INFO    - 0 of 2 tests passed (0.00%), 2 failed, 0 skipped with 0 warnings in 11.30 seconds
INFO    - In total 28 test cases were executed on 1 out of total 292 platforms (0.34%)
INFO    - 2 tests executed on platforms, 0 tests were only built.
```

**To Reproduce**
1. Take my branch from that PR #29188
2. `west build -t run -p -b qemu_x86 tests/kernel/queue/`
3. Then try to run it using sanitycheck `sanitycheck -p qemu_x86  -T tests/kernel/queue/ -vv`
4. See the error like above

**Expected behavior**
Sanitycheck should be PASSED.

**Impact**
CI failure, as a result can't merge PR.

**Environment (please complete the following information):**
 - OS: Linux Fedora 28
 - Toolchain Zephyr SDK 0.11.3
 - Commit SHA or Version used
5e9804b357767796546240e6e9455273e3c0ef42 

**Additional context**
If I run run tests from the code base, that also have expected errors, like 
`sanitycheck -p qemu_x86  -T tests/kernel/mem_protect/userspace/  -vv` Sanitycheck passes. 
What is wrong with my developed test that makes sanitycheck to fail? In fact, test works (west shows it), but sanitycheck doesn't like it.

**Comment by nashif** [comment]
Not a bug, you need to add `ignore_faults` tag to such cases where you expect a fault
