### ISSUE TITLE
Build all tests of module mcuboot

### ISSUE THREAD

**Issue by nvlsianpu** [zephyrproject-rtos/zephyr#29397]
**only test for frdm_k64f board are build for mcuboot project**
I expected that all test for which `platform_allow:`  in https://github.com/zephyrproject-rtos/mcuboot/blob/master/boot/zephyr/sample.yaml of should be tested.
For MCUBoot nrf52840 boards are used as target for integration test (all of them are expected to be build-only)

Neither nrf52840dk_nrf52840 nor nrf52840dongle_nrf52840 are integration platform which cause impossible to use it for mcuboot's integration test.

These a few mcuboot integration tests are testing a few basic configuration build.

**Comment by PerMac** [comment]
With the #29829 merged this should be possible by adding platforms that need to be tested (build level in case of not simulated ones) in 'integration_platforms` list. This list expands/limits the CI to the platforms in the list (`platform_allow` only works as an additional filter preventing anything that is not on the list from being tested).

**Comment by nvlsianpu** [comment]
@PerMac Have to check again, but as i remember mcuboot was not build even with these hints. Maybe because it is external application.

**Comment by nordic-krch** [comment]
Just wanted to mention that was just fixing an issue with mcuboot failing to compile in certain configuration (reported by downstream project) #35765. It is not verified by zephyr CI though.

**Comment by nvlsianpu** [comment]
Can building of MCUboot can be added to the CI? I think additional twister run with `--testcase-root` set to `bootloader/mcuboot/boot/zephyr` will do the job.

@carlescufi Can this be considered and implemented? Maybe this need TSC approval.

Here draft with modified sample.yaml
https://github.com/mcu-tools/mcuboot/pull/890/
