### ISSUE TITLE
SDCard via SD/SDIO/MMC interfaces

### ISSUE THREAD

**Issue by haipas** [zephyrproject-rtos/zephyr#29435]
**Is your feature request related to a problem? Please describe.**
Currently, an SD card is accessed via the SPI interface. Many controllers have a native SD/SDIO/MMC interface (STM32F4, STM32H7 and many more). This allows up to 4 times higher data rates when reading and writing to the SD card.

**Describe the solution you'd like**
Access to the SD card via the native interface of the controller and transfer the data from RAM via DMA to SD card.

**Comment by erwango** [comment]
@haipas There's already a `subsys/disk/disk_access_stm32_sdmmc.c` driver. Can you check if this could match your request ?

**Comment by erwango** [comment]
@haipas Please let us know if this answered your point and if the point could be closed.

**Comment by haipas** [comment]
@erwango thanks for the hint. #29480 is a PR which adds the sdmmc support for the nucleo h743zi
