### ISSUE TITLE
Missing hw-flow-control; in hci_uart overlay files

### ISSUE THREAD

**Issue by koffes** [zephyrproject-rtos/zephyr#29440]
**Describe the bug**
I attempted to get HW flow control working on the nRF5340.
`hw-flow-control` is missing in the overlay of some boards in https://github.com/zephyrproject-rtos/zephyr/tree/master/samples/bluetooth/hci_uart/boards

1. https://github.com/zephyrproject-rtos/zephyr/blob/master/samples/bluetooth/hci_uart/boards/nrf5340pdk_nrf5340_cpuapp.overlay has this enabled, but on the APP core instead of NET.
2. The nRF5340 DK should be added in addition to the PDK

As a general question. Why is not `hw-flow-control` enabled by default on more boards and simply deactivated using CONFIG_UART_LINE_CTRL=n ?

**Impact**
UART with flow control cannot be used for hci_uart on some boards.

**Comment by nordic-krch** [comment]
so `nrf5340pdk_nrf5340_cpuapp` configuration does not make sense. It should be `nrf5340pdk_nrf5340_cpunet`.

**Comment by nordic-krch** [comment]
fyi @carlescufi

**Comment by carlescufi** [comment]
> so `nrf5340pdk_nrf5340_cpuapp` configuration does not make sense. It should be `nrf5340pdk_nrf5340_cpunet`.

Yes it does make sense, unless I'm mistaken. The net CPU runs the controller but the main app CPU runs the hci_uart `main.c`, right @joerchan ?

**Comment by carlescufi** [comment]
Agree that we are missing the overlay for the DK (we only have it for the PDK).

**Comment by joerchan** [comment]
Haven't tested this combination yet. Is this with hci-uart on the application core and then hci-rpmsg on network core then?

**Comment by koffes** [comment]
This particular issue was with APP core idle and hci-uart on NET. I.e. the host running on a PC.

**Comment by koffes** [comment]
Stale label should be removed.

**Comment by carlescufi** [comment]
@anangl and @nordic-krch could you please weigh in here?

**Comment by carlescufi** [comment]
> This particular issue was with APP core idle and hci-uart on NET. I.e. the host running on a PC.

OK, then we will fix this particular case.
