### ISSUE TITLE
Samples: TF-M: Add PSA FF API Sample

### ISSUE THREAD

**Issue by microbuilder** [zephyrproject-rtos/zephyr#29476]
In order to certify Zephyr + TF-M + a specific board for PSA FF API compliance, the results of the PSA FF API tests must be send to the certifying lab: [ARM-software/psa-arch-tests](https://github.com/ARM-software/psa-arch-tests).

These can be manually run, but adding a sample application that runs these tests on the desired board target as a standard Zephyr+TF-M build will facilitate future testing.

**Comment by ioannisg** [comment]
FYI @oyvindronningstad

**Comment by ioannisg** [comment]
Isn't this done now @oyvindronningstad , @microbuilder ?

**Comment by oyvindronningstad** [comment]
My PR added support for the dev APIs test. FF tests is still not available.

**Comment by adrianlshaw** [comment]
Just mentioning here that the Dev APIs are all you need for Functional API certification. See here https://www.psacertified.org/getting-certified/functional-api-certification/ The FF ones are good to have but not strictly needed.

**Comment by microbuilder** [comment]
> Just mentioning here that the Dev APIs are all you need for Functional API certification. See here https://www.psacertified.org/getting-certified/functional-api-certification/ The FF ones are good to have but not strictly needed.

Thanks for the clarification Adrian.

**Comment by microbuilder** [comment]
@ioannisg @oyvindronningstad I'm OK for now with only having the regression tests, and not the individual test suites, since facilitating PSA certification was my main goal. The extra tests are nice to have, but I'd consider them bonus points. Feel free to close this if you'd like to get it off the ToDo list.
