### ISSUE TITLE
Warning in CR2

### ISSUE THREAD

**Issue by Bresolini** [zephyrproject-rtos/zephyr#29497]
**Unknown error 0x88982F61 while opening CR2 file**
When I use a CR2 file from Canon EOS Rantel T5, a warning is shown:
> ```WIC: IWICImagingFactory::CreateDecoderFromStream failed. Error: Unknown error 0x88982F61```

in the log file every time the image file is loaded. It is said that the fault is not known and I do not know if it is affecting the quality of the reconstruction.
I would like information about the warning and what can be done.
The reconstruction was done with photos of a monochromatic box with some drawings and obtained some holes (I added a mousepad to enrich the base).

**To Reproduce**
Use a dataset with CR2 photos only and reconstruct the object by checking the log.
I'm using trial version 5.0 of the software.
My hardware is an i7-2600@3,40 GHz, 8GB DDR3 RAM in Windows 7 Professional.
The computer contains a GeForce GTX 550 Ti with updated drivers, but which was not recognized by Zephyr.

**Expected behavior**
As it is an available extension, I expected that there would be no warnings during the reconstruction

**Impact**
The impact is not known for sure, but the reconstruction has been done.

**Logs and console output**
> ```WIC: IWICImagingFactory::CreateDecoderFromStream failed. Error: Unknown error 0x88982F61```

**Environment (please complete the following information):**
- OS: Windows 7 Professional
- i7-2600@3,40 GHz
- 8GB DDR3 RAM.
- GeForce GTX 550 Ti (updated drivers, not recognized by Zephyr)
 - Zephyr trial version

![IMG_9219](https://user-images.githubusercontent.com/38844711/97032173-c3f61100-1537-11eb-9447-0f387067a4b0.JPG)
![IMG_9220](https://user-images.githubusercontent.com/38844711/97032212-d4a68700-1537-11eb-89c5-4a7c71a1449f.JPG)
![IMG_9221](https://user-images.githubusercontent.com/38844711/97032250-e4be6680-1537-11eb-870f-dd3397dc2f91.JPG)

**Comment by galak** [comment]
I think you submitted this to the wrong project.  Closing this as it does not appear to be Zephyr related.
