### ISSUE TITLE
kernel: provide aligned variants for allocators

### ISSUE THREAD

**Issue by cfriedt** [zephyrproject-rtos/zephyr#29519]
**Is your enhancement proposal related to a problem? Please describe.**
While it is not really meaningful to provide allocators for arbitrary alignments (1, 2, 3, .., 42) it should certainly be feasible to adjust the existing allocators so that they are able to select memory blocks to return based on alignment criteria.

I think the generally accepted alignment constraints are that the alignment must be a multiple of the word size (i.e. `sizeof(void *)`). 

**Describe the solution you'd like**
* modify the allocators in question to accept an alignment parameter and rename
* create wrapper versions of the old allocators (which request alignment of `void *`, possibly static inline)
* adjust the primary allocation routines (It seems like it's mainly in `lib/os/mempool.c`)

**Describe alternatives you've considered**

I've only glanced at the allocator in `lib/os/mempool.c`, and it seems like a buddy allocator with some additional features.

If anyone is knowledgeable about the workings of `lib/os/mempool.c`, some input would be greatly appreciated on how to efficiently search through the metadata to find a suitably-aligned block.

The approach I've taken for a similar buddy allocator in the past is to look at each available order-N block, and then move to order-N+1, etc, but I don't know if that would be acceptable performance-wise for Zephyr. 

**Additional context**
This will be used for dynamic thread stacks, including #29029

**Comment by andrewboie** [comment]
k_mem_pool_* and sys_mem_pool_* are being removed from the kernel.

**Comment by cfriedt** [comment]
> k_mem_pool_* and sys_mem_pool_* are being removed from the kernel.

Just saw #28611 - now everything makes sense! Thanks ;-)
