### ISSUE TITLE
sleep in qemu to short

### ISSUE THREAD

**Issue by maxbachmann** [zephyrproject-rtos/zephyr#29518]
**Describe the bug**
When I try to use sleeps in qemu_x86 they are a lot shorter than expected. I tried to modify `CONFIG_SYS_CLOCK_TICKS_PER_SEC` and `CONFIG_SYS_CLOCK_HW_CYCLES_PER_SEC`. However both of them did not appear to have a big impact on this behaviour.

I currently use `k_sleep(K_HOURS(200));` to sleep around 1 second. 

**Expected behavior**
The expected behaviour is that sleep lasts roughly as long as specified.

**Impact**
annoyance

**Comment by nashif** [comment]
I suspect this is because of ICOUNT, disable ICOUNT and see if you get the results you are expecting

**Comment by maxbachmann** [comment]
Thanks yes disabling icount solves the issue
