### ISSUE TITLE
generic page pool for MMU-based systems

### ISSUE THREAD

**Issue by andrewboie** [zephyrproject-rtos/zephyr#29526]
**Is your enhancement proposal related to a problem? Please describe.**
We have some use-cases for a page pool:

1. Pages to allocate MMU data structures
2. Pages for anonymous memory mappings
3. Pages to increase the size of the system heap arena with sbrk() which is really just a special case of #2

Right now on x86 we have:
- a separate pool for MMU paging structure pages which has to be tuned in a cumbersome way; the number you need depends on how many active memory domains are required and how much memory has been mapped besides system RAM.
- For the newlib libc, we do not memory map the heap. We have a fixed sized physical arena from the `_end` symbol to the bounds of RAM. sbrk() calls just increment a pointer within this area. No attempt is made not to crash into data structures populated by firmware and we are not using available memory in the first megabyte.
- No support for anonymous memory mappings yet

**Describe the solution you'd like**
A page pool to draw page frames from for all the above use-cases.
All these pages are either getting memory mapped into the virtual address space, or are used for paging structures, there is no need for contiguous physical regions larger than a page.
Will need to play nice with demand paging, with ability to anonymously map more memory even when all RAM frames are in use.

**Comment by dcpleung** [comment]
Already done. (commit b01177156f8bfd40992485752798188c1ff88e71)
