### ISSUE TITLE
use TLS for stack canaries

### ISSUE THREAD

**Issue by andrewboie** [zephyrproject-rtos/zephyr#29524]
**Is your enhancement proposal related to a problem? Please describe.**
We have thread-local storage now. Historically we haven't and had to tell the compiler to use a global for stack canaries:

```
cmake/compiler/gcc/compiler_flags.cmake
142-
143-# Security canaries.
144:set_compiler_property(PROPERTY security_canaries -fstack-protector-all)
145-
146-# Only a valid option with GCC 7.x and above, so let's do check and set.
147:check_set_compiler_property(APPEND PROPERTY security_canaries -mstack-protector-guard=global)
148-
```

We should get rid of this override and let the default be TLS if supported. This makes it harder for attackers to guess the canary location, and its value will be different between threads. We can set an initial value for each thread's canary probably in z_thread_entry().

**Comment by ceolin** [comment]
https://github.com/zephyrproject-rtos/zephyr/pull/61052
