### ISSUE TITLE
question: create runtime instantiated kernel objects in kernel mode

### ISSUE THREAD

**Issue by maxbachmann** [zephyrproject-rtos/zephyr#29608]
In Usermode I use `k_object_alloc` to create runtime instantiated kernel objects. However this requires `CONFIG_DYNAMIC_OBJECTS` to be activated, which is only available in Usermode. In Kernel Mode `k_object_alloc` is a no op. I could not find anything in the documentation on how this can be achieved in Kernel Mode. I did try to create them using `k_malloc`:
```cpp
struct k_thread* my_thread = (struct k_thread*)k_malloc(sizeof(struct k_thread));
```
However this fails with a General Protection Fault. So I assume there has to be another method on how to achieve this in Kernel Mode.
Thanks in advance

**Comment by hwmaier** [comment]
Just a comment for those who stumble across the same issue and read this post, I managed to use `k_malloc()` successfully without usermode to create dynamic threads after I had set `CONFIG_HEAP_MEM_POOL_SIZE` to a size sufficient to accommodate `struct k_thread`.

Working example:
```
HANDLE ThreadCreate(char *name, void (*fn) (void *, void *, void *), void *arg, size_t stackSize)
{
    k_thread_stack_t *threadStack;
    struct k_thread *threadObj;

    stackSize = stackSize * 4;
    threadStack = k_thread_stack_alloc(stackSize, 0);
    __ASSERT(threadStack, "k_thread_stack_alloc failed");
    threadObj = (struct k_thread *)k_malloc(sizeof(struct k_thread));
    // threadObj = k_object_alloc(K_OBJ_THREAD); // Does not work w/o CONFIG_USERSPACE
    __ASSERT(threadObj, "k_object_alloc failed");
    k_tid_t threadId = k_thread_create(threadObj, threadStack, stackSize,
                                 fn, arg, NULL, NULL,
                                 K_PRIO_COOP(7), 0, K_NO_WAIT);
    __ASSERT(threadId, "k_thread_create failed");
    return (HANDLE)threadId;
}
```
and proj.conf settings:
```
CONFIG_DYNAMIC_THREAD=y
CONFIG_DYNAMIC_THREAD_ALLOC=y
CONFIG_DYNAMIC_THREAD_PREFER_ALLOC=y
CONFIG_DYNAMIC_OBJECTS=y
CONFIG_HEAP_MEM_POOL_SIZE=32768
