### ISSUE TITLE
BLE IPSP sample doesn't work on raspberry pi 4 with nrf52840_mdk board

### ISSUE THREAD

**Issue by hguomin8** [zephyrproject-rtos/zephyr#29683]
**Describe the bug**
Follow the steps in the [IPSP sample documen](https://docs.zephyrproject.org/latest/samples/bluetooth/ipsp/README.html)t to test BLE IPSP connection between RPI4 and nrf52840_mdk board, while I can ping nrf52840_mdk successfully with scoped IPv6 address, but can't ping with static ipv6 address, also can't connect to the board using telnet, please check the screen shot below.

**To Reproduce**
1. cd zephyr\samples\bluetooth\ipsp
2. west build -b nrf52840_mdk . -DCONF_FILE="prj_dbg.conf"
3. west flash
4. See error in below screen shot

**Expected behavior**
Can ping and telnet via static ipv6 address

**Impact**
Can not make any progress without this ipsp feature...

**Logs and console output**
1. Steps and ouputs on RPI 4
![image](https://user-images.githubusercontent.com/59328845/97804208-5a89a700-1c89-11eb-88bf-559a64611090.png)

2. net shell logs on nrf52840_board
![image](https://user-images.githubusercontent.com/59328845/97804341-206cd500-1c8a-11eb-89e9-609e4b26681f.png)

**Environment (please complete the following information):**
 - OS: (Raspberry pi OS(buster, kernel 5.4.51-v7l+))
 - Zephyr branch: master

**Additional context**
1. In below environment, it works
 - OS: Raspberry pi OS(buster, kernel 4.19.97-v7+)
 - Zephry branch: v2.3.0

2. In below environment, can ping with static ipv6 address, but can not connect via telnet
 - OS: Raspberry pi OS(buster, kernel 5.4.51-v7l+)
 - Zephyr branch: v2.3.0

**Comment by Vudentz** [comment]
We will probably need some HCI logs, but it does looks like this is a Linux problem rather than Zephyr.

**Comment by hguomin8** [comment]
Hmm...this issue can be reproduced easily, look forward you guys can help to fix it, I am not specialize in kernel development

**Comment by carlescufi** [comment]
@hguomin8 could you please report this to the [Linux BlueZ mailing list](http://www.bluez.org/development/lists/), since this looks like a BlueZ issue? I will close this issue but feel free to reopen it if you find out this to be a Zephyr issue instead.
