### ISSUE TITLE
Redundant error check of function  uart_irq_update() in tests/drivers/uart/uart_basic_api/src/test_uart_fifo.c

### ISSUE THREAD

**Issue by lc3412** [zephyrproject-rtos/zephyr#29832]
**Is your enhancement proposal related to a problem? Please describe.**
From the description of the offical documentation (see the following link), function uart_irq_update() always returns 1, and it doesn't have an error code. Therefore, it is no need to perform an extra error check.

Ref: https://docs.zephyrproject.org/apidoc/latest/group__uart__interface_gac5241e000d482c40b2a4856c58c106a6.html#gac5241e000d482c40b2a4856c58c106a6

However, in the tests/drivers/uart/uart_basic_api/src/test_uart_fifo.c, the return value of function uart_irq_update() is checked . See the following code,  a redundant error check occurs, which will never be executed.

https://github.com/zephyrproject-rtos/zephyr/blob/389a03777e95e2e9eaa6c83669da6ce1fd4aa940/tests/drivers/uart/uart_basic_api/src/test_uart_fifo.c#L52-L55

**Describe the solution you'd like**
There is no need to do the error check. Could consider delete the redundant error check code.

**Additional context**
Further, in the other call sites of function uart_irq_update(), developers do not check the error.

**Comment by nashif** [comment]
This code has changed and this function does return error codes, not always 1, so this can be considered outdate or obsolete.
