### ISSUE TITLE
[v1.14, v2.4] Bluetooth: Mesh: RPL cleared on LPN disconnect

### ISSUE THREAD

**Issue by trond-snekvik** [zephyrproject-rtos/zephyr#29858]
Whenever the LPN disconnects from a friend, it will clear its replay protection list. 

This is invalid behavior, as the RPL should only be cleared on node reset.

Fixed in master in #28062, needs backport to the v1.14 LTS and v2.4.

**Comment by nashif** [comment]
afaik, this was fixed and merged already. #29859
