### ISSUE TITLE
new documentation build warning

### ISSUE THREAD

**Issue by pabigot** [zephyrproject-rtos/zephyr#29896]
From #28779 which included a closing `@}` in the header without any opening one.  Probably some of the macros in this are supposed to be in user documentation

```
 ---- New errors/warnings not tracked as .known-issues/, please fix them ----

/mnt/nordic/zp/zephyr/include/sys/util_macro.h:577: warning: unbalanced grouping commands
```

**Comment by utzig** [comment]
@pabigot What is your Doxygen version?

**Comment by pabigot** [comment]
> What is your Doxygen version?

Locally built, doxygen-Release_1_8_19-5-g8e87f6bb4 which is a little past 1.8.19.

**Comment by pabigot** [comment]
Regardless, the file needs to be fixed to have balanced group commands.

**Comment by utzig** [comment]
> Regardless, the file needs to be fixed to have balanced group commands.

I have not considered not fixing the file. I just found it weird that 1.8.13 ignores the problem. I will check if we can just move on to something a bit newer...
