### ISSUE TITLE
XCC Build isr_tables.c fail

### ISSUE THREAD

**Issue by hongshui3000** [zephyrproject-rtos/zephyr#29936]
**Describe the bug**

build FAIL:
file : sections.h
```
#define _SW_ISR_TABLE_SECTION_NAME	.gnu.linkonce.sw_isr_table*
```
build PASS
file : sections.h
```
#define _SW_ISR_TABLE_SECTION_NAME	.gnu.linkonce.sw_isr_table
```

**To Reproduce**
west build -b qemu_xtensa samples/hello_world

**Logs and console output**
FAILED: zephyr/arch/common/CMakeFiles/isr_tables.dir/isr_tables.c.obj 
C:\usr\xtensa\XtDevTools\install\tools\RI-2020.5-win32\XtensaTools\bin\xt-xcc.exe -DBUILD_VERSION=zephyr-v2.4.0-1113-g0bcd66ac36d8 -DKERNEL -D_FORTIFY_SOURCE=2 
-D__ZEPHYR_SUPERVISOR__ -D__ZEPHYR__=1 -I../kernel/include -I../arch/xtensa/include -I../include -Izephyr/include/generated -I../soc/xtensa/sample_controller -I../soc/xtensa/sample_controller/include -IE:/work/rtos_work/zephyrproject/modules/hal/xtensa/include -IE:/work/rtos_work/zephyrproject/modules/hal/xtensa/zephyr/soc/sample_controller -isystem ../lib/libc/minimal/include -Os -imacros E:/work/rtos_work/zephyrproject/zephyr/build/zephyr/include/generated/autoconf.h -ffreestanding -fno-common -g -imacrosE:/work/rtos_work/zephyrproject/zephyr/include/toolchain/xcc_missing_defs.h -fms-extensions -imacros E:/work/rtos_work/zephyrproject/zephyr/include/toolchain/zephyr_stdint.h -Wall -Wformat -Wformat-security -Wno-format-zero-length -Wno-main -Wno-pointer-sign -Wpointer-arith -Werror=implicit-int -fno-pic -fno-strict-overflow -ffunction-sections -fdata-sections -mlongcalls -std=c99 -MD -MT zephyr/arch/common/CMakeFiles/isr_tables.dir/isr_tables.c.obj -MF zephyr\arch\common\CMakeFiles\isr_tables.dir\isr_tables.c.obj.d -o zephyr/arch/common/CMakeFiles/isr_tables.dir/isr_tables.c.obj -c E:/work/rtos_work/zephyrproject/zephyr/arch/common/isr_tables.c
C:/Users/xxx/AppData/Local/Temp/cc0spin#1bce.a11124: Assembler messages:
C:/Users/xxx/AppData/Local/Temp/cc0spin#1bce.a11124:220: Warning: missing operand; zero assumed
C:/Users/xxx/AppData/Local/Temp/cc0spin#1bce.a11124:220: Error: invalid operands (*UND* and *ABS* sections) for `*'
xt-xcc.exe ERROR:  C:/usr/xtensa/XtDevTools/install/tools/RI-2020.5-win32/XtensaTools/bin/xt-as.exe returned non-zero status 1
[54/66] Building C object zephyr/lib/posix/CMakeFiles/lib__posix.dir/pthread_common.c.obj
ninja: build stopped: subcommand failed.
FATAL ERROR: command exited with status 1: 'C:\Program Files\CMake\bin\cmake.EXE' --build 'E:\work\rtos_work\zephyrproject\zephyr\build'

**Environment (please complete the following information):**
 - OS: Windows
 - Toolchain XCC(Xplorer 8.0.15)

**Comment by andrewboie** [comment]
Would you like to send a PR which addresses this?

**Comment by nashif** [comment]
@dcpleung  can you please take a look?
