### ISSUE TITLE
XCC Build offsets.c ：FAILED

### ISSUE THREAD

**Issue by hongshui3000** [zephyrproject-rtos/zephyr#29937]
**Describe the bug**
Build FAIL:
file:mem_domain.h
```
struct k_thread;
typedef struct k_thread *k_tid_t;
```
Build PASS:
file:mem_domain.h
```
struct k_thread;
typedef struct k_thread *k_tid_tXXXX;
```

**To Reproduce**
west build -b qemu_xtensa samples/hello_world

**Logs and console output**
FAILED: zephyr/CMakeFiles/offsets.dir/arch/xtensa/core/offsets/offsets.c.obj 
C:\usr\xtensa\XtDevTools\install\tools\RI-2020.5-win32\XtensaTools\bin\xt-xcc.exe -DBUILD_VERSION=zephyr-v2.4.0-1113-g0bcd66ac36d8 -DKERNEL -D_FORTIFY_SOURCE=2 
-D__ZEPHYR__=1 -I../kernel/include -I../arch/xtensa/include -I../include -Izephyr/include/generated -I../soc/xtensa/sample_controller -I../soc/xtensa/sample_controller/include -IE:/work/rtos_work/zephyrproject/modules/hal/xtensa/include -IE:/work/rtos_work/zephyrproject/modules/hal/xtensa/zephyr/soc/sample_controller -isystem ../lib/libc/minimal/include -Os -imacros E:/work/rtos_work/zephyrproject/zephyr/build/zephyr/include/generated/autoconf.h -ffreestanding -fno-common -g 
-imacrosE:/work/rtos_work/zephyrproject/zephyr/include/toolchain/xcc_missing_defs.h -fms-extensions -imacros E:/work/rtos_work/zephyrproject/zephyr/include/toolchain/zephyr_stdint.h -Wall -Wformat -Wformat-security -Wno-format-zero-length -Wno-main -Wno-pointer-sign -Wpointer-arith -Werror=implicit-int -fno-pic -fno-strict-overflow -ffunction-sections -fdata-sections -mlongcalls -std=c99 -MD -MT zephyr/CMakeFiles/offsets.dir/arch/xtensa/core/offsets/offsets.c.obj -MF zephyr\CMakeFiles\offsets.dir\arch\xtensa\core\offsets\offsets.c.obj.d -o zephyr/CMakeFiles/offsets.dir/arch/xtensa/core/offsets/offsets.c.obj -c E:/work/rtos_work/zephyrproject/zephyr/arch/xtensa/core/offsets/offsets.c
In file included from E:/work/rtos_work/zephyrproject/zephyr/arch/xtensa/core/offsets/offsets.c:27:
../include/kernel.h:380: error: redefinition of typedef 'k_tid_t'
../include/app_memory/mem_domain.h:22: error: previous declaration of 'k_tid_t' was here
ninja: build stopped: subcommand failed.
FATAL ERROR: command exited with status 1: 'C:\Program Files\CMake\bin\cmake.EXE' --build 'E:\work\rtos_work\zephyrproject\zephyr\build'

**Environment (please complete the following information):**
 - OS:  Windows
 - Toolchain ：XCC(Xplorer 8.0.15)

**Comment by nashif** [comment]
this should be addressed with #29359
