### ISSUE TITLE
Missing error check of function isotp_send()

### ISSUE THREAD

**Issue by Hxinrong** [zephyrproject-rtos/zephyr#29943]
Hi,
As described in the project API documentation, function isotp_send() is used to send data to a peer that listens to the tx_addr, returns ISOTP_N_OK on success, and returns ISOTP_N_* on error. But as shown in the following codes, the return value is not error checked before it is assigned by another function.
https://github.com/zephyrproject-rtos/zephyr/blob/21cac03b7cd77b9ced90120ad41f212c0bc485b8/tests/subsys/canbus/isotp/conformance/src/main.c#L634-L642
https://github.com/zephyrproject-rtos/zephyr/blob/21cac03b7cd77b9ced90120ad41f212c0bc485b8/tests/subsys/canbus/isotp/conformance/src/main.c#L650-L655
https://github.com/zephyrproject-rtos/zephyr/blob/21cac03b7cd77b9ced90120ad41f212c0bc485b8/tests/subsys/canbus/isotp/conformance/src/main.c#L823-L830

Moreover, the return values of the function from other call sites are checked. See the following code, for example.
https://github.com/zephyrproject-rtos/zephyr/blob/21cac03b7cd77b9ced90120ad41f212c0bc485b8/tests/subsys/canbus/isotp/implementation/src/main.c#L68-L70

**Comment by alexanderwachter** [comment]
Hi @Hxinrong. You are right, we could check them. The reason why I did not check it is that Iḿ not particularly interested in the return value of the first sent in the case of a timeout test. Nevertheless, a PR to check the values is always welcome.
Thanks!
