### ISSUE TITLE
Add the sofproject as a module

### ISSUE THREAD

**Issue by nashif** [zephyrproject-rtos/zephyr#29953]
Add https://github.com/thesofproject/sof as a module to enable building Audio application and support Audio DSPs available in some platforms.

Proposed Module name: `sof`

**Comment by carlescufi** [comment]
Agreed. Where is the "porting layer" to Zephyr in that project though?

**Comment by carlescufi** [comment]
+1 to the name

**Comment by nashif** [comment]
> Agreed. Where is the "porting layer" to Zephyr in that project though?

not sure what you mean
