### ISSUE TITLE
sanitycheck fails to build samples/bluetooth/peripheral_hr/sample.bluetooth.peripheral_hr_rv32m1_vega_ri5cy

### ISSUE THREAD

**Issue by galak** [zephyrproject-rtos/zephyr#29967]
`./scripts/sanitycheck -s samples/bluetooth/peripheral_hr/sample.bluetooth.peripheral_hr_rv32m1_vega_ri5cy -l`

Get:

```
/home/galak/git/zephyr/subsys/bluetooth/controller/ll_sw/ull.c:248:7: error: 'BT_CTLR_ADV_SET' undeclared here (not in a function)
  248 |       BT_CTLR_ADV_SET + BT_CTLR_SCAN_SYNC_SET))
      |       ^~~~~~~~~~~~~~~
/home/galak/git/zephyr/subsys/bluetooth/controller/ll_sw/ull.c:252:15: note: in expansion of macro 'PDU_RX_POOL_SIZE'
  252 |  uint8_t pool[PDU_RX_POOL_SIZE];
      |               ^~~~~~~~~~~~~~~~
gmake[2]: *** [zephyr/subsys/bluetooth/controller/CMakeFiles/subsys__bluetooth__controller.dir/build.make:213: zephyr/subsys/bluet
```

**Comment by galak** [comment]
This looks like it was introduced by this commit:

commit c2fc629dd21bbaa1fd36678ea4adb28e778b8a0d
Author: Vinayak Kariappa Chettimada <vich@nordicsemi.no>
Date:   Thu Oct 22 18:40:38 2020 +0530

    Bluetooth: controller: 255 byte AD payload support

**Comment by cvinayak** [comment]
@MaureenHelm @dleach02 Not sure who is maintaining the openisa port now. I will try patch up build related failure, but I will not be able to test any regressions in functionality. Please bring to notice of resources who can help maintain the port. (I do have a vega board but I dont have a debugger that I can use with it to flash and test).
