### ISSUE TITLE
RFC: dfu/boot/mcuboot: consider usage of boootloader/mcuboot code

### ISSUE THREAD

**Issue by nvlsianpu** [zephyrproject-rtos/zephyr#29963]
## Introduction

mcuboot.c file implements functionality required for interact with MCUBoot bootloader.
This had been introduced before the west was introduced.

Some parts of this code are reimpregnations of what is implemented in mcuboot repository.
Mcuboot's repository provide implementation of function required for application for interact with the MCUboot.

### Problem description

As some code are defined here and there it becomes problem when module is compiled within MCUboot.
It is possible to mitigate problem using #fdefry - but this is temporary hack.

**Comment by carlescufi** [comment]
CC @utzig and @d3zd3z

**Comment by de-nordic** [comment]
Do you consider to make common the FLASH_* definitions so that the macros that are enabling "image" access don't get redefined all over the code?

**Comment by d3zd3z** [comment]
I think it makes sense to have much of the definition here in a single place, probably making sense to have it in the mcuboot repo. It mostly makes sense to build this dfu/boot/mcuboot module when mcuboot itself is also being included, so it shouldn't be an issue of the module being present.
