### ISSUE TITLE
usbd: support more than one configuration descriptors

### ISSUE THREAD

**Issue by jfischer-no** [zephyrproject-rtos/zephyr#30042]
A USB device has one or more configuration descriptors. Current Zephyr implementation supports only one configuration descriptor. Allow USB device support to have multiple configuration descriptors. This is a part of USB device stack rework and #29135 should be implemented so that it takes multiple configuration descriptors into account.

**Comment by raveslave** [comment]
just checking in, curious about timings for when this might be done

**Comment by carlescufi** [comment]
Fixed in the new USB stack, use `CONFIG_USB_DEVICE_STACK_NEXT` to enable it.
