### ISSUE TITLE
sanitycheck --build-only gets stuck

### ISSUE THREAD

**Issue by andrewboie** [zephyrproject-rtos/zephyr#30099]
The run completes but it just sits there without returning to the shell:

```
$ sanitycheck -a riscv32 --build-only
INFO    - Zephyr version: zephyr-v2.4.0-1654-g52dd8e60a1
INFO    - JOBS: 60
INFO    - Selecting default platforms per test case
INFO    - Building initial testcase list...
INFO    - 14202 test configurations selected, 298472 configurations discarded due to filters.
INFO    - Adding tasks to the queue...
INFO    - Total complete:  211/ 211  100%  skipped:   49, failed:    0
INFO    - 162 of 162 tests passed (100.00%), 0 failed, 14040 skipped with 0 warnings in 139.41 seconds
INFO    - In total 1634 test cases were executed on 307 out of total 307 platforms (100.00%)
INFO    - 0 tests executed on platforms, 162 tests were only built.
```

**Comment by yerabolu** [comment]
Ran the tests couple of times and it takes a little time to return to the shell. But it does return to the shell.

**Comment by nashif** [comment]
> Ran the tests couple of times and it takes a little time to return to the shell. But it does return to the shell.

it is still a bug, should return immediately, based on initial observation it is stuck writing the reports, so something is fishy at this level.

**Comment by nashif** [comment]
It is basically spending most of the time writing reports about stuff that did not happen for all platforms, although we asked to only run on a few platforms within riscv32

**Comment by nashif** [comment]
I think I fixed this while cleaning up in another PR, see #28372
