### ISSUE TITLE
out of tree （board soc doc subsystem ...）

### ISSUE THREAD

**Issue by hongshui3000** [zephyrproject-rtos/zephyr#30179]
Now the zephyr project is getting bigger and bigger, supporting more and more development boards and SOCs. Can these be maintained outside the reengineering tree (including documentation)
The WEST tool should be able to support selective download of the corresponding modules, allowing users to decide to download the software packages they need.

**Comment by carlescufi** [comment]
@hongshui3000 Thanks for posting. This is a request for an enhancement in west, not in zephyr itself, so I suggest you post this in the west repository instead: https://github.com/zephyrproject-rtos/west
