### ISSUE TITLE
Missing error check of function sensor_trigger_set()

### ISSUE THREAD

**Issue by Hxinrong** [zephyrproject-rtos/zephyr#30189]
Hi,
As described in the project API documentation, function sensor_trigger_set() is used to activate a sensor's trigger and set the trigger handler. It returns 0 if successful, negative errno code if failure. But as shown in the following codes, the return value is not error checked before it is assigned by another function.
https://github.com/zephyrproject-rtos/zephyr/blob/0a0404df29ed890cacadc94ecbd6e1e7f79c3d75/samples/sensor/sht3xd/src/main.c#L51-L61

But, the return values of the function from other call sites are all checked. See the following code,
https://github.com/zephyrproject-rtos/zephyr/blob/0a0404df29ed890cacadc94ecbd6e1e7f79c3d75/samples/sensor/sm351lt/src/main.c#L72-L76

**Comment by MaureenHelm** [comment]
@pabigot can you have a look at this? it looks like you originally added this sample application
