### ISSUE TITLE
TCP2 : How to add MSS option on sending [SYN, ACK] to client?

### ISSUE THREAD

**Issue by liang8057** [zephyrproject-rtos/zephyr#30209]
I want to add mms to the tcp option during the three-way handshake.
Is there any API available?

**Comment by jukkar** [comment]
Currently the TCP stack does not add any tcp options when sending data. We could support `TCP_MAXSEG` socket option that the application could set. Patches are welcome if you want to implement it.

**Comment by liang8057** [comment]
Can TCP1 add mss tcp option?

**Comment by liang8057** [comment]
I did not find the TCP_MAXSEG socket option, is there an example for reference?

**Comment by jukkar** [comment]
> Can TCP1 add mss tcp option?

Yes, there is some option setting in TCP1. Seach `net_tcp_set_syn_opt()` function.

**Comment by jukkar** [comment]
> I did not find the TCP_MAXSEG socket option, is there an example for reference?

Yes, see for example `subsys/net/lib/sockets/sockets.c` and ` zsock_setsockopt_ctx()`

**Comment by carlescufi** [comment]
Closing since it's out of date (TCP1 is no longer in the tree).
