### ISSUE TITLE
stm32f4_disco: User button press is inverted

### ISSUE THREAD

**Issue by dogtopus** [zephyrproject-rtos/zephyr#30224]
**Describe the bug**

The User button is inverted and reads 0 when pressed and 1 when released.

The [schematic for all 4 revisions of this board](https://www.st.com/en/evaluation-tools/stm32f4discovery.html) clearly shows that the button is pulled down by external resistor instead of up and a button press overrides the pull-down resistor.

**To Reproduce**

Check for `samples/basic/button`. The LED should lit up when the button is not pressed for this board.

**Expected behavior**

A non-inverted User button that when pressed reads 1

**Impact**

Minor annoyance. Needs to override the configuration in overlay DTS.

**Logs and console output**

Should be straightforward without logs.

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: GCC ARM Embedded Toolchain
 - Commit SHA or Version used: Latest master.

**Additional context**

N/A

**Comment by ABOSTM** [comment]
Hi @dogtopus,
Thanks for pointing out this issue and fixing it.
I agree there is a pull down, but so default reading is 0 and when pressed it is read at 1.
This justify your changed to `GPIO_ACTIVE_HIGH`.
