### ISSUE TITLE
Bluetooth: controller: event scheduling pipeline preemption by short schedule

### ISSUE THREAD

**Issue by cvinayak** [zephyrproject-rtos/zephyr#30245]
**Describe the bug**
A request to schedule an event shorter than preemption timeout could be delayed upto the preemption timeout making the event to be delayed beyond its hard deadline.

![image](https://user-images.githubusercontent.com/6350656/100312631-20bf6e00-2fb3-11eb-9ac5-986aa2d932da.png)

1 - Prepare callback of continuous scan window
2 - Preemption abort after 1.5 ms since 1
3 - New schedule, short offset, lower than 300 us, which is lesser than the 1.5 ms preemption timeout
4 - New scheduled event executed beyond the preemption timeout, instead of being scheduled at its hard deadline.

Further details to be filled as works starts towards fixing it.

**To Reproduce**
1. mkdir build; cd build
2. cmake -DBOARD=board\_xyz
3. make

**Expected behavior**

**Impact**
What impact does this issue have on your progress (e.g., annoyance, showstopper)

**Logs and console output**
If applicable, add console logs or other types of debug information
e.g Wireshark capture or Logic analyzer capture (upload in zip archive).
copy-and-paste text and put a code fence (\`\`\`) before and after, to help
explain the issue. (if unable to obtain text log, add a screenshot)

**Environment (please complete the following information):**
 - OS: (e.g. Linux, MacOS, Windows)
 - Toolchain (e.g Zephyr SDK, ...)
 - Commit SHA or Version used

**Additional context**

**Comment by carlescufi** [comment]
Downgrading to low since this feature is still WIP in the controller.

**Comment by cvinayak** [comment]
Increased to high priority as issue could be the cause of the #36381
