### ISSUE TITLE
Bluetooth: controller: IRK resolution in extended scanning breaks auxiliary PDU reception

### ISSUE THREAD

**Issue by cvinayak** [zephyrproject-rtos/zephyr#30243]
**Describe the bug**
`radio_irk_resolve` function takes ~300 us which prevents reception of auxiliary PDUs that are as close as 300us of T_MAFS from next auxiliary PDU.

Details be filled as we go about fixing.

**To Reproduce**
1. mkdir build; cd build
2. cmake -DBOARD=board\_xyz
3. make

**Expected behavior**

**Impact**
What impact does this issue have on your progress (e.g., annoyance, showstopper)

**Logs and console output**
If applicable, add console logs or other types of debug information
e.g Wireshark capture or Logic analyzer capture (upload in zip archive).
copy-and-paste text and put a code fence (\`\`\`) before and after, to help
explain the issue. (if unable to obtain text log, add a screenshot)

**Environment (please complete the following information):**
 - OS: (e.g. Linux, MacOS, Windows)
 - Toolchain (e.g Zephyr SDK, ...)
 - Commit SHA or Version used

**Additional context**

**Comment by cvinayak** [comment]
@nashif This issue is against experimental and work in progress support for Advertising Extensions feature in Bluetooth Controller. We should move this out of v2.5 release bug list.

**Comment by carlescufi** [comment]
Downgrading to low since this feature is still WIP in the controller.

**Comment by carlescufi** [comment]
Since complete Advertising Extensions support is a main focus for 2.7 LTS, and this is a blocker for it, raising the priority to medium
