### ISSUE TITLE
Bluetooth: controller: Extended scan window time reservation prevents auxiliary channel reception

### ISSUE THREAD

**Issue by cvinayak** [zephyrproject-rtos/zephyr#30244]
**Describe the bug**
Time space is reserved for scan window, this will cancel single shot scheduling being used for auxiliary PDU.

- Add implementation for abort scan window
- Add new ticker interface to yield currently occupied timespace

More info be filled as we work on this issue...

**To Reproduce**
1. mkdir build; cd build
2. cmake -DBOARD=board\_xyz
3. make

**Expected behavior**

**Impact**
What impact does this issue have on your progress (e.g., annoyance, showstopper)

**Logs and console output**
If applicable, add console logs or other types of debug information
e.g Wireshark capture or Logic analyzer capture (upload in zip archive).
copy-and-paste text and put a code fence (\`\`\`) before and after, to help
explain the issue. (if unable to obtain text log, add a screenshot)

**Environment (please complete the following information):**
 - OS: (e.g. Linux, MacOS, Windows)
 - Toolchain (e.g Zephyr SDK, ...)
 - Commit SHA or Version used

**Additional context**

**Comment by cvinayak** [comment]
@asmk-ot @mtpr-ot @wopu-ot @kruithofa 

Relates to the below design requirement (serial no. 2):
![image](https://user-images.githubusercontent.com/6350656/100439945-71fb5a80-30a4-11eb-90f8-89a7cb0bf836.png)

Discussion welcome...

**Comment by cvinayak** [comment]
@nashif This issue is against experimental and work in progress support for Advertising Extensions feature in Bluetooth Controller. We should move this out of v2.5 release bug list.

**Comment by carlescufi** [comment]
Downgrading to low since this feature is still WIP in the controller.
