### ISSUE TITLE
Sanitycheck: can't find mdb.pid

### ISSUE THREAD

**Issue by wangnuannuan** [zephyrproject-rtos/zephyr#30276]
**Describe the bug**
When platform is `nsim_hs_smp`, if testcase timeout, the sanitycheck may raise error.

```
FileNotFoundError: [Errno 2] No such file or directory: 'xxxx/nsim_hs_smp/tests/application_development/cpp/application_development.cpp.main/mdb.pid'
```
So please check if this file exist brfore 
https://github.com/zephyrproject-rtos/zephyr/blob/83b6fa20fe5def289ac2b9a8588097f211bff457/scripts/sanity_chk/sanitylib.py#L352

**Comment by nashif** [comment]
@wangnuannuan  is this still an issue?

**Comment by nashif** [comment]
seems to be fixed already.
