### ISSUE TITLE
Data Reallocation in SRAM

### ISSUE THREAD

**Issue by KozhinovAlexander** [zephyrproject-rtos/zephyr#30303]
Dear Zephyr community,

I have following problem:

1. `sram0` and `sram1` of some SoC DT are placed on non-consecutive memory addresses.
2. DT of the board chooses `zephyr,sram = &sram0`.

How do I place some array of data `static char foo[10];` in `sram1`?

Thanks to everyone, helping to solve it.

**Comment by erwango** [comment]
^^ @galak
