### ISSUE TITLE
BT Mesh LPN max. poll timeout calculated incorrectly

### ISSUE THREAD

**Issue by stefbo** [zephyrproject-rtos/zephyr#30338]
**Describe the bug**
Bluetooth Mesh LPN poll frequency solely determined by poll timeout starting value `CONFIG_BT_MESH_LPN_INIT_POLL_TIMEOUT`. Seems to be a regression from https://github.com/zephyrproject-rtos/zephyr/commit/3b4d58aa4bb05a7b30bb720132bbfa35ea90be7d. The macro `POLL_TIMEOUT_MAX` should use `CONFIG_BT_MESH_LPN_POLL_TIMEOUT` instead of `CONFIG_BT_MESH_LPN_INIT_POLL_TIMEOUT`. The described algorithm to grow the poll timeout implemented in function `poll_timeout` does not work with this implementation. The algorithm is described in the description of Kconfig value `BT_MESH_LPN_INIT_POLL_TIMEOUT`.

**To Reproduce**
Configure an LPN with a starting value of say 5s and a poll timeout value of say 100s.

**Expected behavior**
The poll frequency starts at below 5s and is increased continuously towards a value derived from 100s.

**Impact**
Any reasonable low-power configuration has to set `CONFIG_BT_MESH_LPN_INIT_POLL_TIMEOUT` to `CONFIG_BT_MESH_LPN_POLL_TIMEOUT`. Existing devices updating to the current version without having such a configuration may suffer from too frequent polling.

**Comment by LingaoM** [comment]
@stefbo  Thanks.
