### ISSUE TITLE
out of tree （board soc doc subsystem ...） 

### ISSUE THREAD

**Issue by hongshui3000** [zephyrproject-rtos/zephyr#30373]
Now the zephyr project is getting bigger and bigger, supporting more and more development boards and SOCs. Can these be maintained outside the reengineering tree (including documentation)
The WEST tool should be able to support selective download of the corresponding modules, allowing users to decide to download the software packages they need.

**Comment by mbolivar-nordic** [comment]
Hi, this isn't really a west question, but zephyr repository structure organization. I believe the reasons why the current modules are organize they way they are is documented here:

https://docs.zephyrproject.org/latest/guides/modules.html

Out of tree boards, etc. are already quite well supported. See the various `_ROOT` variables like `BOARD_ROOT`, `DTS_ROOT`, etc.
