### ISSUE TITLE
No restore possible with mesh shell app from /tests using qemu_x86 on RaspberryPi3

### ISSUE THREAD

**Issue by CSparn** [zephyrproject-rtos/zephyr#30416]
Hi,
I'm trying to run the mesh shell from tests on a RaspberryPi with Qemu_x86.
This is working fine as long as I'm not expecting to use store and restore of the mesh network.
After some research I released that this is not working, because qemu has no flash where it can save the data.
So I created an image with 8MB to pass it to the qemu command as pflash:

`qemu-img create -f raw flash/flash.img 8M`

The final qemu command looks like this:
`
qemu-system-x86_64 -m 9 -cpu qemu32,+nx,+pae -device isa-debug-exit,iobase=0xf4,iosize=0x04 -no-reboot -nographic -net none -pidfile qemu.pid -chardev stdio,id=con,mux=on -serial chardev:con -mon chardev==con,mode=readline -drive file=flash/flash.img,format=raw,if=pflash -serial unix:/tmp/bt-server-bredr -s -kernel zephyr/build/zephyr/zephyr.elf
`

When I'm running it like that, nothing happens. Qemu is started but no shell is shown. When I'm deleting the if=pflash from the command qemu and the mesh shell is starting. But when I run the 'mesh init' command qemu crahes with the error:

`ASSERTION FAIL [err == 0] @ WEST_TOPDIR/zephyr/subsys/bluetooth/host/hci_core.c:374
        k_sem_take failed with err -11`

I'm not even sure if this is a bug in the zephyr code or if I did something wrong configuring qemu. But does any have an idea how to get this working?

**To Reproduce**
1. Build mesh shell app for qemu_x86
2. Copy the folder to RaspberryPi
3. Start the btproxy from bluez with `sudo ./btproxy -u -i 0`
4. Create the flash image like described
5. Start qemu with the aboth command

**Expected behavior**
Error Message or nothing.

Thanks in Advance
CSparn

**Comment by Laczen** [comment]
@CSparn, I don't know if qemu provides flash support. Native_posix does provide flash support where a file is used as a flash emulator. Maybe it is possible to achieve your goal  using native_posix.

**Comment by CSparn** [comment]
Hi,
as far as I know, it is possible to use a flash in qemu. For that you need to create an image and add -pflash image_name to the command you start qemu with. But when I do this starting the mesh app, I just see a black line but qemu is not starting properly.
More information you can find here:
https://wiki.qemu.org/Features/PC_System_Flash
and here
https://qemu.readthedocs.io/en/latest/system/images.html

Greetings
CSparn

**Comment by Laczen** [comment]
@CSparn, I don't know if that is the correct way to use flash on qemu. Qemu_x86 does provide simulated flash storage support but  I think this is all done in memory and not on a "flash" device (even if you provide -pflash image_name). Is there a zephyr flash driver to support the -pflash area added to the command line ? For storage you need to be able to write this "flash", so a flash driver is needed.

**Comment by CSparn** [comment]
Hi,
I'm also not sure if the command line is the only option to add a flash to qemu. 
And I couldn't find a driver for pflash or qemu. But it looks like there is a flash simulator. 
Maybe this is the right way to get the flash running with qemu. But when I enable the config
CONFIG_FLASH_SIMULATOR it does not change anything. Maybe another option is missing?
But the flash simulator seems to run on qemu:
https://docs.zephyrproject.org/latest/reference/kconfig/CONFIG_FLASH_SIMULATOR.html#cmdoption-arg-CONFIG_FLASH_SIMULATOR
Greetings CSparn

**Comment by Laczen** [comment]
Hi @CSparn, please give native_posix a try, this has full support for flash storage.

**Comment by CSparn** [comment]
Hi,
I tried with native_posix but I could not get it running properly. I always get errors running the app. I will go on trying with native_posix, but for me it seems that the app is running more stable in Qemu. So I also try to find a solution for the flash problem in qemu.

**Comment by carlescufi** [comment]
> ASSERTION FAIL [err == 0] @ WEST_TOPDIR/zephyr/subsys/bluetooth/host/hci_core.c:374 k_sem_take failed with err -11

This assertion will happen if you have not correctly configured your Bluetooth/BLE controller so that qemu (or native_posix) finds it.
Please follow the documentation [on this page](https://docs.zephyrproject.org/latest/guides/bluetooth/bluetooth-tools.html#running-on-qemu-and-native-posix) and see if you can get it working.

**Comment by Laczen** [comment]
@carlescufi, IIRC the question was to have persistent storage support for qemu, so that on a restart the previous stored settings could be used. I think a flash driver is missing for the case a file is passed to qemu as a flash representation.

**Comment by carlescufi** [comment]
> @carlescufi, IIRC the question was to have persistent storage support for qemu, so that on a restart the previous stored settings could be used. I think a flash driver is missing for the case a file is passed to qemu as a flash representation.

Sure, but I was addressing the error log from the PR description.

**Comment by CSparn** [comment]
Hi,
thanks for all your help. I could finally solve it by using the native_posix app.
Greetings CSparn
