### ISSUE TITLE
No network interface was found when running socketcan sample

### ISSUE THREAD

**Issue by Navin-Sankar** [zephyrproject-rtos/zephyr#30432]
**Describe the bug**
When running the socketcan sample application with spi based mcp2515 CAN shield, it report that there is no network interface to work with:

![no-network-interface](https://user-images.githubusercontent.com/28673597/101122664-028fe880-3619-11eb-9cbe-3e836225bcfc.png)

There is no network interface is created during compile time itself
```
                0x0000000020000640                _net_if_list_start = .
 *(SORT_BY_NAME(SORT_BY_ALIGNMENT(._net_if.static.*)))
                0x0000000020000640                _net_if_list_end = .

net_if_dev_area
                0x0000000020000640        0x0 load address 0x000000000801310c
                0x0000000020000640                _net_if_dev_list_start = .
 *(SORT_BY_NAME(SORT_BY_ALIGNMENT(._net_if_dev.static.*)))
                0x0000000020000640                _net_if_dev_list_end = .
```

**To Reproduce**
1. cd samples/net/sockets/can
2. west build -b disco_l475_iot1 -- -DSHIELD=dfrobot_can_bus_v2_0
3. west flash

**Expected behavior**
The sample should initialize the socket CAN interface without any error

The same sample create's the network interface for onboard CAN controller.
**board:** nucleo_l432kc
**compile time output**

```
                0x00000000200002d4                _net_if_list_start = .
 *(SORT_BY_NAME(SORT_BY_ALIGNMENT(._net_if.static.*)))
 ._net_if.static.net_if
                0x00000000200002d4        0x4 zephyr/libzephyr.a(can_stm32.c.obj)
                0x00000000200002d8                _net_if_list_end = .

net_if_dev_area
                0x00000000200002d8       0x1c load address 0x0000000008013870
                0x00000000200002d8                _net_if_dev_list_start = .
 *(SORT_BY_NAME(SORT_BY_ALIGNMENT(._net_if_dev.static.*)))
 ._net_if_dev.static.__net_if_dev_socket_can_stm32_1_0
                0x00000000200002d8       0x1c zephyr/libzephyr.a(can_stm32.c.obj)
                0x00000000200002f4                _net_if_dev_list_end = .
```

**Comment by jukkar** [comment]
As mentioned in slack, the `mcp2515` does not call `NET_DEVICE_INIT()` macro so no network interface will be created. In practice, this also means that socketcan is currently not supported for `mcp2515`.
