### ISSUE TITLE
frdm_k64f: testcase samples/net/cloud/tagoio_http_post/ failed to be ran

### ISSUE THREAD

**Issue by Zhaoningx** [zephyrproject-rtos/zephyr#30476]
To Reproduce
sanitycheck -p frdm_k64f --device-testing --device-serial /dev/ttyACM0 -T samples/net/cloud/tagoio_http_post/
see error

**condition 1: tagoio_http_post**
^@^@*** Booting Zephyr OS build zephyr-v2.4.0-2085-gd9666ff4d091  ***
^[[1;32muart:~$ ^[[m^[[8D^[[J[00:00:00.006,000] ^[[0m<inf> net_config: Initializing network^[[0m
^[[1;32muart:~$ ^[[m^[[8D^[[J[00:00:00.006,000] ^[[0m<inf> net_config: Waiting interface 1 (0x20001b30) to be up...^[[0m
^[[1;32muart:~$ ^[[m^[[8D^[[J^[[1;32muart:~$ ^[[m

**condition 2: tagoio_http_post.modem**
^A*** Booting Zephyr OS build zephyr-v2.4.0-2085-gd9666ff4d091  ***
^[[1;32muart:~$ ^[[m^[[8D^[[J[00:00:00.006,000] ^[[0m<inf> net_config: Initializing network^[[0m
^[[1;32muart:~$ ^[[m^[[8D^[[J[00:00:00.006,000] ^[[0m<inf> net_config: Waiting interface 1 (0x20001520) to be up...^[[0m
^[[1;32muart:~$ ^[[m^[[8D^[[J^[[1;32muart:~$ ^[[m

**condition 3: tagoio_http_post.wifi.esp**
^[[1;32muart:~$ ^[[m*** Booting Zephyr OS build zephyr-v2.4.0-2085-gd9666ff4d091  ***
^[[8D^[[J[00:00:09.002,000] ^[[1;31m<err> wifi_esp: Failed to reset device:  -60^[[0m

^[[1;32muart:~$ ^[[m^[[8D^[[J[00:00:09.007,000] ^[[0m<inf> tagoio_http_post: TagoIO IoT - HTTP Client - Temperature demo^[[0m
^[[1;32muart:~$ ^[[m^[[8D^[[J[00:00:09.007,000] ^[[0m<inf> tagoio_http_post: WIFI try connecting to <your network ssid>...^[[0m
^[[1;32muart:~$ ^[[m^[[8D^[[J[00:00:09.008,000] ^[[0m<inf> tagoio_http_post: Temp: 97^[[0m
^[[1;32muart:~$ ^[[m^[[8D^[[J[00:00:09.008,000] ^[[1;31m<err> tagoio_http_post: Cannot connect to IPv4 remote (-51)^[[0m
^[[1;32muart:~$ ^[[m^[[8D^[[J[00:00:09.008,000] ^[[0m<inf> tagoio_http_post: No connection available.^[[0m
^[[1;32muart:~$ ^[[m^[[8D^[[J^[[1;32muart:~$ ^[[m^[[8D^[[J[00:00:19.008,000] ^[[0m<inf> tagoio_http_post: Temp: 61^[[0m
^[[1;32muart:~$ ^[[m^[[8D^[[J[00:00:19.009,000] ^[[1;31m<err> tagoio_http_post: Cannot connect to IPv4 remote (-51)^[[0m
^[[1;32muart:~$ ^[[m^[[8D^[[J[00:00:19.009,000] ^[[0m<inf> tagoio_http_post: No connection available.^[[0m
^[[1;32muart:~$ ^[[m^[[8D^[[J^[[1;32muart:~$ ^[[m^[[8D^[[J[00:00:29.009,000] ^[[0m<inf> tagoio_http_post: Temp: 68^[[0m
^[[1;32muart:~$ ^[[m^[[8D^[[J[00:00:29.009,000] ^[[1;31m<err> tagoio_http_post: Cannot connect to IPv4 remote (-51)^[[0m
^[[1;32muart:~$ ^[[m^[[8D^[[J[00:00:29.009,000] ^[[0m<inf> tagoio_http_post: No connection available.^[[0m
^[[1;32muart:~$ ^[[m^[[8D^[[J^[[1;32muart:~$ ^[[m^[[8D^[[J[00:00:39.010,000] ^[[0m<inf> tagoio_http_post: Temp: 47^[[0m
^[[1;32muart:~$ ^[[m^[[8D^[[J[00:00:39.010,000] ^[[1;31m<err> tagoio_http_post: Cannot connect to IPv4 remote (-51)^[[0m
^[[1;32muart:~$ ^[[m^[[8D^[[J[00:00:39.010,000] ^[[0m<inf> tagoio_http_post: No connection available.^[[0m
^[[1;32muart:~$ ^[[m^[[8D^[[J^[[1;32muart:~$ ^[[m^[[8D^[[J[00:00:49.010,000] ^[[0m<inf> tagoio_http_post: Temp: 50^[[0m
^[[1;32muart:~$ ^[[m^[[8D^[[J[00:00:49.010,000] ^[[1;31m<err> tagoio_http_post: Failed to create IPv4 HTTP socket (-23)^[[0m
^[[1;32muart:~$ ^[[m^[[8D^[[J[00:00:49.010,000] ^[[0m<inf> tagoio_http_post: No connection available.^[[0m
^[[1;32muart:~$ ^[[m^[[8D^[[J^[[1;32muart:~$ ^[[m^[[8D^[[J[00:00:59.010,000] ^[[0m<inf> tagoio_http_post: Temp: 41^[[0m
^[[1;32muart:~$ ^[[m^[[8D^[[J[00:00:59.010,000] ^[[1;31m<err> tagoio_http_post: Failed to create IPv4 HTTP socket (-23)^[[0m
^[[1;32muart:~$ ^[[m^[[8D^[[J[00:00:59.010,000] ^[[0m<inf> tagoio_http_post: No connection available.^[[0m

Environment (please complete the following information):

OS: Fedora33
Toolchain: zephyr-sdk-0.11.4
Commit ID: d9666ff

**Comment by nashif** [comment]
This test probably should be excluded for this board and requires additional setup (networking)
