### ISSUE TITLE
kconfig.py exits with error when using multiple shields

### ISSUE THREAD

**Issue by arludwig** [zephyrproject-rtos/zephyr#30553]
**Describe the bug**
When I try to set two shields
```
list(APPEND SHIELD "shield1")
list(APPEND SHIELD "shield2")
```
`kconfig.py` exits with return code 1 (System can't find file).

When I use a single shield instead
```
list(APPEND SHIELD "shield1")
```
everything works as expected.

I dug a bit through the cmake code, in particular `kconfig.cmake`, and ended up comparing the `execute_process` calls in line 241. I found, that they differed in their `COMMON_KCONFIG_ENV_SETTINGS`, in particular the `SHIELD_AS_LIST` part.

Single shield:
```
SHIELD_AS_LIST=shield1;
```

Two shields:
```
SHIELD_AS_LIST=shield1;shield2;
```

From what I can tell, those are variable definitions for the shell, which are separated by semicolons. My guess is, that the `shield2;` part is responsible for the "File not found" error.

After commenting out line 75 of `kconfig.cmake`
```
  #SHIELD_AS_LIST=${SHIELD_AS_LIST}
```
so far everything seems to work with two shields as well. I don't know whether the setting is needed, as both my custom shields currently are device tree only.

**To Reproduce**
1. Create (or find) two device tree only shields, and choose a compatible board
2. CMake configure a zephyr based project using both shields
3. Unless the issue is specific to my system, you should see an error.

**Expected behavior**
CMake configuring should work with zero, one or more shields, as described in the zephyr documentation.

**Impact**
As I need to use multiple shields in my project, this issue forces me to run a personally modified zephyr source tree (which I try to avoid whenever possible), until I can pull the fix from the zephyr repository. Also I don't know (yet) whether my workaround (hack) has any unintended side effects.

**Environment (please complete the following information):**
 - Windows 10
 - CMake 3.17.2
 - Zephyr 2.4 (c2a0b0f)
 - GNU ARM Embedded Toolchain (9 2020-q2-update)

**Additional context**
May be related to #25716.

**Comment by erwango** [comment]
@tejlmand would you be able to have a look ?

**Comment by henrikbrixandersen** [comment]
This is broken in Zephyr v2.4.0 as well. It works as expected in Zephyr v2.3.0.

**Comment by henrikbrixandersen** [comment]
Raising the priority since this is a regression compared to v2.3.0.

**Comment by galak** [comment]
@henrikbrixandersen does your PR address this issue?

**Comment by henrikbrixandersen** [comment]
> @henrikbrixandersen does your PR address this issue?

@galak No, it does not address this issue. I only stumbled across it while trying to implement another feature using multiple shields.
