### ISSUE TITLE
TCP stack locks irq's for too long

### ISSUE THREAD

**Issue by lund-prevas** [zephyrproject-rtos/zephyr#30636]
In subsys/net/ip/tcp2.c, function "net_tcp_get", the irq_lock() is used to avoid interrupts.

On a Freedom K64 board, with a Kinetis K64 running 120 MHz, this function locks interrupts for ~164 us
Same board provides several UART's with no flowcontrol signals and no FIFO, so each byte has to be read before next byte is received.
With a baudrate on 115200, there is ~86 us between each byte, so locking interrupts for 164 us causes data loss on UART's

TCP is a logical component, so there is no reason to use irq_lock, instead it should use k_mutex or k_semaphore to protect critical data.

**Comment by jukkar** [comment]
Hi @lund-prevas, I have a fix proposal at #30707. I did test it but could you report does it help in your use case?

**Comment by lund-prevas** [comment]
Hi, 
It does help. I am not seeing data loss on the UART when applying this commit
