### ISSUE TITLE
doc: "Variable ZEPHYR_TOOLCHAIN_VARIANT is not defined"

### ISSUE THREAD

**Issue by andrewboie** [zephyrproject-rtos/zephyr#30713]
**Describe the bug**
Imaged a new Ubuntu machine and followed all the directions on https://docs.zephyrproject.org/latest/getting_started/index.html

I used the default location for the SDK.

Unfortunately, this page doesn't mention that ZEPHYR_TOOLCHAIN_VARIANT has to be set for `twister` to work.

**To Reproduce**
```
andrew@meatwad:~/projects/zephyr/zephyr$  twister -p qemu_x86
Renaming output directory to /home/andrew/projects/zephyr/zephyr/twister-out.1
INFO    - Zephyr version: zephyr-v2.4.0-2399-g7883eedfde
INFO    - JOBS: 32
E: Variable ZEPHYR_TOOLCHAIN_VARIANT is not defined
```

**Expected behavior**
Doc page would mention this detail.

**Impact**
Minor

**Comment by SeppoTakalo** [comment]
I was just searching for the same issue.
Apparently `export ZEPHYR_TOOLCHAIN_VARIANT=zephyr` is the right choice, if you installed the Zephyr SDK, and it has been visible in the documentation in the past:
https://docs.zephyrproject.org/1.14.1/getting_started/installation_linux.html#zephyr-sdk

But current documentation does not mention it. Probably at some point all the build tools detected Zephyr SDK automatically, so they removed the mention about setting that variable.

**Comment by tejlmand** [comment]
> Probably at some point all the build tools detected Zephyr SDK automatically, so they removed the mention about setting that variable.

Correct. CMake handles this automatically when using newer Zephyr SDK's. (from 0.11.3 and beyond).

This issue is related to running twister, which seems to also test for the Toolchain variable, so i'm looking into aligning code so this can be done in a single place.
See also:
https://github.com/zephyrproject-rtos/zephyr/pull/31936/files#r570036292

**Comment by tejlmand** [comment]
if trying to build using west or CMake / Ninja, then you should not see this issue.

**Comment by SeppoTakalo** [comment]
west+CMake+Ninja works OK, as expected.
This issue is only within Twister.
