### ISSUE TITLE
CAN J1939 Support

### ISSUE THREAD

**Issue by Navin-Sankar** [zephyrproject-rtos/zephyr#30724]
**Is your feature request related to a problem? Please describe.**
    SAE J1939 is the vehicle bus recommended practice used for communication
    and diagnostics among vehicle components. Originating in the car and
    heavy-duty truck industry in the United States, it is now widely used in
    other parts of the world.
    J1939, ISO 11783 and NMEA 2000 all share the same high level protocol.
    SAE J1939 can be considered the replacement for the older SAE J1708 and
    SAE J1587 specifications.

**Describe the solution you'd like**
In linux there is separate implementation for SAE J1939 protocol (net/can/j1939/).
Likewise I try to add j1939 protocol support in zephyr by creating **sockets_j1939.c** file in subsys/net/lib/sockets directory to handle the  socket type: **SOCK_DGRAM** and protocol: **CAN_J1939**

**Comment by Navin-Sankar** [comment]
@jukkar @alexanderwachter requesting for comments and feedback.

**Comment by jukkar** [comment]
> Likewise I try to add j1939 protocol support in zephyr by creating **sockets_j1939.c** file in subsys/net/lib/sockets directory to handle the socket type: **SOCK_DGRAM** and protocol: **CAN_J1939**

That is the way to go if you want support socket interface for this protocol. Your plan looks ok to me.

**Comment by alexanderwachter** [comment]
@Navin-Sankar don't forget that you are not allowed to copy any code from the Linux kernel (GPL licensed) to the Zephyr repository. Only Apache licensed or compatible code is allowed.

**Comment by wysman** [comment]
@Navin-Sankar do you have some news about you work on J1939 ? I may be interested to use it too.

**Comment by henrikbrixandersen** [comment]
@Navin-Sankar Any work done on this yet that you can share?

**Comment by alexanderwachter** [comment]
No progress here. We can reopen if there is progress on this issue

**Comment by cperkulator** [comment]
I'm working on contributing a J1939 stack and had a few questions....

- there are quite a few pieces to the protocol. Should I break up the PRs to just include one "feature" at a time? i.e. just address claiming. Or should an RFC be submitted as [this](https://docs.zephyrproject.org/latest/contribute/contributor_expectations.html#contributor-expectations) says?
- J1939 is obviously just software but I've been using device tree as follows. This makes it really convenient to `describe` the bus layout and which nodes are on which CAN bus.  I've heard that device tree has been thought of as needing to be purely hardware but I'm wondering if this is kosher.
```c
&can0 {
    #address-cells = <1>;
    #size-cells = <0>;

    diag_node: virtual-node@11 {
            compatible = "zephyr,j1939-node";
            reg = <0x11>;
            label = "diag";
            ecu-instance = <1>;
            vehicle-system = <3>;
    };

    test_node: virtual-node@12 {
            compatible = "zephyr,j1939-node";
            reg = <0x12>;
            label = "test";
    };

    status = "okay";
    /* adjust zcan0 to desired host interface or create an alternative
     * name, e.g.: sudo ip link property add dev vcan0 altname zcan0
     */
    host-interface = "vcan0";
};
```
-I'm not using sockets, just using the CAN driver directly. That cool?

And just fyi, I'm hoping to publish code soon but waiting on legals sign off so who knows how long that will take....

**Comment by alexanderwachter** [comment]
> I'm working on contributing a J1939 stack and had a few questions....
> 
> - there are quite a few pieces to the protocol. Should I break up the PRs to just include one "feature" at a time? i.e. just address claiming. Or should an RFC be submitted as [this](https://docs.zephyrproject.org/latest/contribute/contributor_expectations.html#contributor-expectations) says?

I would expect a PR that is testet and adds a piece of functionality.
Contributing it in too small PRs could hide the bigger picture, so that the architecture might not be lear from there.

> - J1939 is obviously just software but I've been using device tree as follows. This makes it really convenient to `describe` the bus layout and which nodes are on which CAN bus.  I've heard that device tree has been thought of as needing to be purely hardware but I'm wondering if this is kosher.
> ```c
> &can0 {
>     #address-cells = <1>;
>     #size-cells = <0>;
> 
>     diag_node: virtual-node@11 {
>             compatible = "zephyr,j1939-node";
>             reg = <0x11>;
>             label = "diag";
>             ecu-instance = <1>;
>             vehicle-system = <3>;
>     };
> 
>     test_node: virtual-node@12 {
>             compatible = "zephyr,j1939-node";
>             reg = <0x12>;
>             label = "test";
>     };
> 
>     status = "okay";
>     /* adjust zcan0 to desired host interface or create an alternative
>      * name, e.g.: sudo ip link property add dev vcan0 altname zcan0
>      */
>     host-interface = "vcan0";
> };
> ```

Device-Tree is there to describe HW. Making an alias or something to tell the stach which interface to use is ok. Defining virtual nodes is too much for me. Maybe others think differently.

> -I'm not using sockets, just using the CAN driver directly. That cool?
> 

Super cool!

> And just fyi, I'm hoping to publish code soon but waiting on legals sign off so who knows how long that will take....

**Comment by henrikbrixandersen** [comment]
> I'm working on contributing a J1939 stack and had a few questions....
> 
>     * there are quite a few pieces to the protocol. Should I break up the PRs to just include one "feature" at a time? i.e. just address claiming. Or should an RFC be submitted as [this](https://docs.zephyrproject.org/latest/contribute/contributor_expectations.html#contributor-expectations) says?

I would prefer an RFC and a PR for adding the various features in one go. At least the features needed for an MVP should be included in the first PR. Optional parts can (but doesn't have to) be added in follow-up PRs.

>     * J1939 is obviously just software but I've been using device tree as follows. This makes it really convenient to `describe` the bus layout and which nodes are on which CAN bus.  I've heard that device tree has been thought of as needing to be purely hardware but I'm wondering if this is kosher.

No, that would not be acceptable. Devicetree is not supposed to be used for this (imagine if we applied the same strategy for defining e.g. Ethernet-based networks). Devicetree should define the device-local hardware. Remote nodes or nodes reached via networking protocol should not be described in devicetree.

> -I'm not using sockets, just using the CAN driver directly. That cool?

Very cool. This is the preferred approach.
 
> And just fyi, I'm hoping to publish code soon but waiting on legals sign off so who knows how long that will take....

👍

**Comment by parthitce** [comment]
Re-opening based on to the new activity from Caleb.
