### ISSUE TITLE
Remove LEGACY_TIMEOUT_API 

### ISSUE THREAD

**Issue by nashif** [zephyrproject-rtos/zephyr#30893]
Remove legacy timeout API support, this has been there for a few releases already and shall be removed for LTS, so ideally remove before 2.5 is released.

**Comment by andyross** [comment]
Agreed.  Patch away.

**Comment by pabigot** [comment]
Deprecated in 2.3 by #23382 so it's "legal" to remove it, though we never actually marked it deprecated.
