### ISSUE TITLE
PDM Driver for nrf52840dk

### ISSUE THREAD

**Issue by nehalrohit** [zephyrproject-rtos/zephyr#30929]
I want to interface with an MP34DT05 MEMS audio sensor for nrf52840dk_pca10056.

can you give me some steps or any sample example? 
Thanks...
Nehal

**Comment by anangl** [comment]
@nehalrohit You can take a look at #27671 and perhaps use it as your starting point. This PR aims at adding API for PDM drivers so any feedback in this regard is welcome.

**Comment by nehalrohit** [comment]
Hi @anangl 
I  added all files and their config for nrf52840dk 
do the same as the change did for Thingy:52 and create pdm example.
I have below problem 
![Screenshot from 2021-01-04 17-03-25](https://user-images.githubusercontent.com/50902801/103531420-4a6f8d00-4eaf-11eb-990c-d556a9f46e0e.png)
