### ISSUE TITLE
up_squared_adsp: Twister can not capture testcases log correctly

### ISSUE THREAD

**Issue by KangJianX** [zephyrproject-rtos/zephyr#30979]
**Describe the bug**
When use twister to run test cases, after to check the handle.log(the test cases result), the result of testcases are not specified by myself.

**To Reproduce**
1. twister -p intel_adsp_cavs15 --device-testing -T **tests/kernel/mutex/mutex_api/** --west-flash="/home/ztest/work/zephyrproject/zephyr/boards/xtensa/intel_adsp_cavs15/tools/flash.sh, /home/ztest/work/sof/rimage/keys/otc_private_key.pem" --device-serial-pty="/home/ztest/work/zephyrproject/zephyr/boards/xtensa/intel_adsp_cavs15/tools/adsplog.py"
 
2. twister -p intel_adsp_cavs15 --device-testing -T **tests/kernel/poll/** --west-flash="/home/ztest/work/zephyrproject/zephyr/boards/xtensa/intel_adsp_cavs15/tools/flash.sh, /home/ztest/work/sof/rimage/keys/otc_private_key.pem" --device-serial-pty="/home/ztest/work/zephyrproject/zephyr/boards/xtensa/intel_adsp_cavs15/tools/adsplog.py"

3. check the result of step2 
  vim twister-out/intel_adsp_cavs15/tests/kernel/**poll/kernel.poll**/handler.log
handler.log: 
**Running test suite mutex_api**
===================================================================
START - test_mutex_lock_unlock
PASS - test_mutex_lock_unlock
===================================================================
START - test_mutex_reent_lock_forever
access resource from main thread
access resource from main thread
PASS - test_mutex_reent_lock_forever
===================================================================
START - test_mutex_reent_lock_no_wait
access resource from main thread
bypass locked resource from spawn thread
access resource from main thread
bypass locked resource from spawn thread
PASS - test_mutex_reent_lock_no_wait
===================================================================
START - test_mutex_reent_lock_timeout_fail
access resource from main thread
bypass locked resource from spawn thread
access resource from main thread
bypass locked resource from spawn thread
PASS - test_mutex_reent_lock_timeout_fail
===================================================================
START - test_mutex_reent_lock_timeout_pass
access resource from main thread
access resource from spawn thread
access resource from main thread
bypass locked resource from spawn thread
PASS - test_mutex_reent_lock_timeout_pass
===================================================================
START - test_mutex_recursive
PASS - test_mutex_recursive
===================================================================
START - test_mutex_priority_inheritance
PASS - test_mutex_priority_inheritance
===================================================================
**Test suite mutex_api succeeded**
===================================================================
PROJECT EXECUTION SUCCESSFUL

**Expected behavior**
The result of step2 is poll, not mutex_api.

OS: Fedora28
Toolchain: Zephyr-sdk-0.11.4
Commit ID: fe8311843285b93951

**Comment by andyross** [comment]
This doesn't seem to happen for me.  I tried several times and couldn't reproduce.

That said: this is not impossible, owing to the fact that the log output is static in the device memory and that twister will start the log reader script earlier than the flash script, causing the earlier output to be emitted first.  I suppose we could add an argument that doesn't print the current buffer contents, though that would likewise be subject to a race in the opposite direction.

If you need a workaround: flash something that is not a ztest (e.g. hello_world) first.

Ideally, you can then run twister with **all** the tests you want to run, so it sees them all in a single log stream.  That is faster too.

(Dropping priority, given that there's a trivial workaround.)
