### ISSUE TITLE
USB: SET_ADDRESS logic error

### ISSUE THREAD

**Issue by LuoZhongYao** [zephyrproject-rtos/zephyr#30972]
**Describe the bug**
When enumerating USB, when HOST sends a SET_ADDRESS command to zephyr, zephyr first calls usb_dc_set_address, and then responds via usb_dc_write, and this response uses a new device address, causing enumeration to fail, because HOST is still waiting for a response at address 0.

**Expected behavior**
After zephyr receives the SET_ADDRESS command, it should answer first, and then call usb_dc_set_address

**Impact**
usb enumeration failed

**Environment (please complete the following information):**
 - OS: Linux DESKTOP-GLN7DSM 4.4.0-19041-Microsoft #488-Microsoft Mon Sep 01 13:43:00 PST 2020 x86_64 x86_64 x86_64 GNU/Linux
 - Toolchain Zephyr SDK
 - fe8311843285b93951adfdb55c411dffe4bf78ca.

**Comment by jfischer-no** [comment]
> When enumerating USB, when HOST sends a SET_ADDRESS command to zephyr, zephyr first calls usb_dc_set_address, and then responds via usb_dc_write, and this response uses a new device address, causing enumeration to fail, because HOST is still waiting for a response at address 0.

It is up to the driver to handle this situation correctly. This is due to historical reasons and it does not work differently with some drivers. For the current implementation of the stack this will not change.
