### ISSUE TITLE
driver : STM32 Ethernet : Pin definition for PH6

### ISSUE THREAD

**Issue by sercantun** [zephyrproject-rtos/zephyr#30989]
Hi,

We are working on a Stm32f429 based custom board. We are trying to test the Ethernet interface.
MII mode is used.  While trying to make HW configuration in pinmux.c, we realised that there is no ethernet definition for the PH6 in  pinmux_stm32f4.h

Can we define it in a similiar way to the other ethernet pins? Or will this cause a problem in the driver?

**Comment by gmarull** [comment]
You can define your own pinmux definitions. Note that however, these are now deprecated in favor of DT pinctrl definitions, see e.g. https://github.com/zephyrproject-rtos/zephyr/blob/master/boards/arm/stm32h747i_disco/stm32h747i_disco_m7.dts#L74
