### ISSUE TITLE
Unable to add new i2c sensor to nrf/samples

### ISSUE THREAD

**Issue by VinodSHegde** [zephyrproject-rtos/zephyr#30991]
I am trying to add adxl345 to nrf52840 and BMI160 to NRF52840.

I followed all configuration mentioned in nordic devzone but device_get_binding(DT_LABEL(DT_INST(0,adi_adxl345))) returns NULL.

How to properly setup sensor with nrf/sample examples.

**Comment by nashif** [comment]
@carlescufi fyi

**Comment by carlescufi** [comment]
@pabigot could you please give some hints to @VinodSHegde?

**Comment by pabigot** [comment]
If this is still an issue: `device_get_binding()` will return null if the driver init function returns a non-zero value.  You should add instrumentation to the init function to figure out what that's happening.
