### ISSUE TITLE
LwM2M FOTA pull not working with modem (offloaded socket) driver using UART

### ISSUE THREAD

**Issue by MaikVermeulen** [zephyrproject-rtos/zephyr#31053]
**Describe the bug**
[`lwm2m_firmware_start_transfer()`](https://github.com/zephyrproject-rtos/zephyr/blob/7127f0a7420869876e425f514dedf6c1645269a5/subsys/net/lib/lwm2m/lwm2m_obj_firmware_pull.c#L460) is issuing a work item for [`firmware_transfer()`](https://github.com/zephyrproject-rtos/zephyr/blob/7127f0a7420869876e425f514dedf6c1645269a5/subsys/net/lib/lwm2m/lwm2m_obj_firmware_pull.c#L369), which calls [`lwm2m_socket_start()`](https://github.com/zephyrproject-rtos/zephyr/blob/7127f0a7420869876e425f514dedf6c1645269a5/subsys/net/lib/lwm2m/lwm2m_obj_firmware_pull.c#L397), which contains a blocking [`connect()`](https://github.com/zephyrproject-rtos/zephyr/blob/4cfd2a19439bff143061b2465add3e4d6017da7c/subsys/net/lib/lwm2m/lwm2m_engine.c#L4519) call. 

With an offloaded socket driver that uses AT commands (over UART), this blocking work item blocks the working of the UART driver, because that uses the work queue to process received frames. (Or at least the Nordic UART driver, uart_nrfx_uart.) Hence, the `connect()` call blocks the code that should unlock it.

**To Reproduce**
1. Nordic chip (maybe others as well)
2. Offloaded socket driver with modem that use AT commands over UART
3. Use LwM2M
4. Set Package URI in 5/0/1 resource

**Expected behavior**
Successful block-wise coap download of firmware binary from server.

**Impact**
Firmware pulls do not work when using this setup.

**Possible solutions**
- Use a direct call to the `firmware_transfer()` function, but I guess this was considered and there was deliberately chosen to use the the work queue.
- Use a dedicated work queue so that the system work queue is not held up.
- Use non-blocking sockets.

If we can decide on a solution, I would like to implement it, so this issue can be assigned to me!

**Comment by rlubos** [comment]
I had a look into it, and actually, I can't find a reason why is `firmware_transfer()` submitted to a workqueue instead of being called directly from the LwM2M thread. I'd rather avoid creating yet another thread for LwM2M due to increased memory usage. So I think the first proposal is acceptable.

@MaikVermeulen Feel free to submit a PR if it solves your problem.
