### ISSUE TITLE
nordic: west flash no longer supports changing `CONFIG_GPIO_PINRESET` when flashing

### ISSUE THREAD

**Issue by pabigot** [zephyrproject-rtos/zephyr#31055]
6628a16e4d7aa46e57fd2cc8796592983bcc6516 changed the behavior of west flash, which formerly used `--eraseall` which clears both flash and UICR.  `CONFIG_GPIO_PINRESET=n` is intended to support *not* programming `NRF_UICR->PSELRESET` to co-opt the reset pin for the reset function, instead leaving it available for the application to use as a button.

It appears that the west change prevents these registers in UICR from being cleared, so that flashing a new image that changes the intended PSELRESET value has no effect.

The workaround is bypass west and use `nrfjprog --eraseall`, but there probably should be some way to do it in west.

**Comment by mbolivar-nordic** [comment]
> there probably should be some way to do it in west.

There is, for the nrfjprog runner, which supports `west flash --erase`. Please reopen if I'm missing something and that's not what you mean.
