### ISSUE TITLE
How can I overwrite west build in command?

### ISSUE THREAD

**Issue by Cherish-forever** [zephyrproject-rtos/zephyr#31110]
Is there a way to overwrite west build command? I want have a pretty print for west status.

**Comment by mbolivar-nordic** [comment]
You are free to add your own extension commands to the workspace if you need to by editing the manifest file as described in the [Extensions](https://docs.zephyrproject.org/latest/guides/west/extensions.html) page. There is no way to 'hook' an existing extension to modify its behavior, though. You will either need to edit the west build implementation or add a different extension with its own name.
