### ISSUE TITLE
Seems like the rule ".99 tag to signify major work started, minor+1 started " not used anymore ?

### ISSUE THREAD

**Issue by manoj153** [zephyrproject-rtos/zephyr#31137]
Reason: I don't see such tags on the majority of the releases 

Based on the latest doc:

v[Major].[Minor].99 - A tag applied to master branch to signify that work on v[Major].[Minor+1] has started. For example, v1.7.99 will be tagged at the start of v1.8 process. The tag corresponds to VERSION_MAJOR/VERSION_MINOR/PATCHLEVEL macros as defined for a work-in-progress master version. Presence of this tag allows generation of sensible output for “git describe” on master, as typically used for automated builds and CI tools.

![image](https://user-images.githubusercontent.com/17961318/103845768-afa5c700-50d7-11eb-8203-76f2f4d75c6a.png)
![image](https://user-images.githubusercontent.com/17961318/103846308-c7ca1600-50d8-11eb-89b1-ff687ad9d82b.png)
Here are the only .99 tags I find in the repo

**Comment by nashif** [comment]
we stopped doing this long time ago, you get this with the last release tag..
