### ISSUE TITLE
tests/subsys/canbus/isotp/implementation: failing on nucleo_f746zg

### ISSUE THREAD

**Issue by erwango** [zephyrproject-rtos/zephyr#31149]
**Describe the bug**
tests/subsys/canbus/isotp/implementation: failing on nucleo_f746zg (and stm32f3_disco)

**To Reproduce**
1- twister --hardware-map ../map.yaml --device-testing -p nucleo_746zg -T tests/subsys/canbus/isotp/conformance
2- See error

**Expected behavior**
Test should pass

**Impact**
What impact does this issue have on your progress (e.g., annoyance, showstopper)

**Logs and console output**
$ cat /local/mcu/zephyrproject/zephyr/twister out/nucleo_f746zg/tests/subsys/canbus/isotp/implementation/can.isotp.implemmentation/handler.log
```
I: Init of CAN_1 done
*** Booting Zephyr OS build zephyr-v2.4.0-2807-gb34d05592666  ***
Running test suite isotp
===================================================================
START - test_bind_unbind
I: Got a frame in a state where it is unexpected.
E: ***** USAGE FAULT *****
E:   Unaligned memory access
E: r0/a1:  0x080040ad  r1/a2:  0x080040ad  r2/a3:  0x00000040
E: r3/a4:  0x080040b5 r12/ip:  0x20012070 r14/lr:  0x08002165
E:  xpsr:  0x01000024
E: Faulting instruction address (r15/pc): 0x08003fc6
E: >>> ZEPHYR FATAL ERROR 0: CPU exception on CPU 0
E: Fault during interrupt handling
E: Current thread: 0x20010788 (sysworkq)
E: Halting system
```

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04
 - Toolchain: Zephyr SDK 0.12
 - Commit SHA: zephyr-v2.4.0-2807-gb34d055926

**Additional context**
No additional wire used with the board

**Comment by carlescufi** [comment]
Single platform and subsystem, downgrading to low.
