### ISSUE TITLE
STM32F1 RTC

### ISSUE THREAD

**Issue by coderkalyan** [zephyrproject-rtos/zephyr#31175]
To my knowledge, STM32F1 devices have an RTC. For example the reference manual for the [stm32f103rc](https://www.st.com/en/microcontrollers-microprocessors/stm32f103rc.html) includes content about the RTC. However I didn't see a definition for the RTC in arm/st/f1/stm32f1.dtsi. I tried copying in a definition from stm32f4.dtsi (according to the reference manual the registers are all the same, might be mistaken about that though) but then it doesn't compile. I'm investigating to see if any headers need to be included or configuration options enabled. I have been able to build an RTC example for STM32F4.

**Comment by FRASTM** [comment]
Note that the RTC hardware of the stm32F1xx differs from stm32F4.
In stm32F1xx the RTC register map is made of counter registers, not directly Date and Time.
