### ISSUE TITLE
fatal error: setjmp.h: No such file or directory

### ISSUE THREAD

**Issue by Quincy-Zh** [zephyrproject-rtos/zephyr#31203]
I'm trying to compile Lua with Zephyr, but an error has occurred, some *.h can not find. setjmp.h, locale.h for now.

I checked toolchain gcc-arm-none-eabi-8-2019-q3-update-win32 and gcc-arm-none-eabi-10-2020-q4-major-win32, the problem is still.

I create an project without zephyr, the problem not happend. 

Maybe some compiler options missing in zephyr project...

**Comment by pabigot** [comment]
You're probably using Zephyr's internal minimal libc, which doesn't have that header.  Try setting `CONFIG_NEWLIB_LIBC=y`.

**Comment by Quincy-Zh** [comment]
**CONFIG_NEWLIB_LIBC=y** works!
