### ISSUE TITLE
Cortex-M: vector table relocation is incorrect with XIP=n

### ISSUE THREAD

**Issue by GrixaYrev** [zephyrproject-rtos/zephyr#31235]
**Describe the bug**
In first, everything bellow is actual for case CONFIG_CPU_CORTEX_M_HAS_VTOR=y.
CortexM vector table relocate to SRAM start when CONFIG_XIP is not defined (see `arch\arm\core\aarch32\prep_c.c:50`).
But vector table can be placed with some offset, for example in i.MX RT.
So it is not possible to use non XIP application with i.MX RT boot header.

**To Reproduce**
1. i.MX RT1052
2. CONFIG_NXP_IMX_RT_BOOT_HEADER=y
3. CONFIG_XIP=n
4. Runtime error

**Expected behavior**
Definition `VECTOR_ADDRESS` is set to `_vector_start` in `arch\arm\core\aarch32\prep_c.c:48` if CONFIG_XIP=y.
But `_vector_start` is declared in `arch\arm\core\aarch32\vector_table.ld`, which in turn is added to linker script in `CMakeLists.txt` unconditional.
So it is possible to set `VECTOR_ADDRESS` equal `_vector_start` unconditionally also (if CONFIG_CPU_CORTEX_M_HAS_VTOR=y, of course).

**Impact**
Showstopper

**Environment:**
 - Commit SHA a7135bca17177122cfc70deb2dff4277c0108b72

 **Additional context**
It is not possible to set CONFIG_XIP=y and CONFIG_FLASH_BASE_ADDRESS=CONFIG_SRAM_BASE_ADDRESS, because .text and .bss sections will be overlapped. So CONFIG_XIP=n is required.

**Comment by ioannisg** [comment]
Will take a look

**Comment by ioannisg** [comment]
Looks like the case with CPU_HAS_VTOR=y and XIP=n has not been changed, since it was originally introduced long time ago, in https://github.com/zephyrproject-rtos/zephyr/pull/5988/

**Comment by ioannisg** [comment]
@GrixaYrev is there some specific in-tree sample or test you want to run with XIP=n

**Comment by ioannisg** [comment]
@GrixaYrev  https://github.com/zephyrproject-rtos/zephyr/pull/31872 , please, see if this simple fix makes sense.

**Comment by GrixaYrev** [comment]
@ioannisg is not, I use my custom project. In additional VTOR it is need to set custom MPU regions, because SRAM is not executable by default in `zephyr\soc\arm\common\cortex_m\arm_mpu_regions.c`.

**Comment by ioannisg** [comment]
> @ioannisg is not, I use my custom project. In additional VTOR it is need to set custom MPU regions, because SRAM is not executable by default in zephyr\soc\arm\common\cortex_m\arm_mpu_regions.c.

OK, fine but this is another issue - not part of the ticket here.
(FYI vector table fetches do not suffer from MPU settings)

I wanted to check with you whether #31872 is in the right direction, in your opinion.

**Comment by GrixaYrev** [comment]
> @GrixaYrev #31872 , please, see if this simple fix makes sense.

@ioannisg, I have tested `ioannisg:arch_arm_cortex_m_non_xip_vector_fix`, it's OK. VTOR have actual value now, i have checked with jLink debugger on i.MX RT1052.
