### ISSUE TITLE
i2c shell functions non-functional on nRF53

### ISSUE THREAD

**Issue by thedjnK** [zephyrproject-rtos/zephyr#31248]
**Describe the bug**
I2C is working on an nRF53-based system e.g. using sensor sample apps, however the I2C shell itself does not seem to function at all.

**To Reproduce**
1. Build BME680 sample for nRF53 (nrf5340dk_nrf5340_cpuapp) with shell enabled
2. Build hello world sample for nRF53 (nrf5340dk_nrf5340_cpuapp) with shell enabled
3. Flash BME680 sample app
4. Observe that sensor data is correctly output
5. Try to scan I2C bus, it returns 0 devices
6. Flash hello world sample app
7. Try to scan I2C bus, it returns 0 devices
8. Try to read from BME680 sensor, it fails

**Expected behavior**
It to work

**Impact**
Seems like a bit of an annoyance if this doesn't work

**Logs and console output**
Output from BME680 sample app:
    uart:~$ *** Booting Zephyr OS build zephyr-v2.4.0-2823-gf4a26837c8cb  ***
    Device 0x20000234 name is BME680
    T: 24.100000; P: 100.585000; H: 42.176000; G: 37582.000000
    T: 24.180000; P: 100.585000; H: 42.056000; G: 46444.000000
    T: 24.220000; P: 100.586000; H: 41.935000; G: 51387.000000
    T: 24.250000; P: 100.585000; H: 41.840000; G: 55226.000000

    scan I2C_1
           0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
    00:             -- -- -- -- -- -- -- -- -- -- -- --
    10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
    20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
    30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
    40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
    50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
    60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
    70: -- -- -- -- -- -- -- --
    0 devices found on I2C_1

Output from hello world:

    *** Booting Zephyr OS build zephyr-v2.4.0-2823-gf4a26837c8cb  ***
    Hello World! nrf5340dk_nrf5340_cpuapp

    uart:~$ i2c scan I2C_1
         0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
    00:             -- -- -- -- -- -- -- -- -- -- -- --
    10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
    20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
    30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
    40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
    50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
    60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
    70: -- -- -- -- -- -- -- --
    0 devices found on I2C_1
    [00:00:03.736,206] <err> i2c_nrfx_twim: Error 195952641 occurred for message 0
    [00:00:03.736,419] <err> i2c_nrfx_twim: Error 195952641 occurred for message 0
    [00:00:03.736,938] <err> i2c_nrfx_twim: Error 195952641 occurred for message 0
    [00:00:03.737,121] <err> i2c_nrfx_twim: Error 195952641 occurred for message 0
    [00:00:03.737,609] <err> i2c_nrfx_twim: Error 195952641 occurred for message 0
    [00:00:03.737,792] <err> i2c_nrfx_twim: Error 195952641 occurred for message 0
    [00:00:03.738,311] <err> i2c_nrfx_twim: Error 195952641 occurred for message 0
    [00:00:03.738,525] <err> i2c_nrfx_twim: Error 195952641 occurred for message 0
    [00:00:03.738,708] <err> i2c_nrfx_twim: Error 195952641 occurred for message 0
    [00:00:03.739,013] <err> i2c_nrfx_twim: Error 195952641 occurred for message 0
    [00:00:04.239,135] <err> i2c_nrfx_twim: Error on I2C line occurred for message 0

    uart:~$ i2c read_byte I2C_1 0x76
    Failed to read from device: I2C_1
    uart:~$ i2c read I2C_1 0x76
    Failed to read from device: I2C_1
    uart:~$ i2c read I2C_1 0x76 1
    Failed to read from device: I2C_1

**Environment (please complete the following information):**
 - OS: Windows 7
 - Toolchain: GNU GCC from ARM (version 9.3.1, 2020 Q2 update)
 - Commit SHA or Version used: Mainline zephyr and also nRF connect SDK (issue appears on both). Mainline zephyr commit: f4a26837c8cb6d39f3307193068c3163b20ac584

**Additional context**

**Comment by pabigot** [comment]
Initial review suggests the nRF53 doesn't behave the same as nRF52 with respect transfers with no data, which is the mechanism used to detect presence of a device on the bus.  The sensor signals an ACK at the end of the address, but the underlying nrfx driver must be continuing to perform a transaction even though the length should be zero.

This seems to be a difference in behavior at the nrfx driver level for the two chip lines.  @anangl any ideas?
