### ISSUE TITLE
Compilation warning regards the SNTP subsys

### ISSUE THREAD

**Issue by WilliamGFish** [zephyrproject-rtos/zephyr#31323]
**Describe the bug**
Compilation warning regards the SNTP subsys.

/subsys/net/lib/sntp/sntp.c:161:3: warning: implicit declaration of function 'close' [-Wimplicit-function-declaration]
  161 |   close(ctx->sock.fd);

**Expected behavior**
No compilation warning as the "close" function is available.

**Impact**
Annoyance, does not appear to have any impact on functionality

**Logs and console output**
/subsys/net/lib/sntp/sntp.c:161:3: warning: implicit declaration of function 'close' [-Wimplicit-function-declaration]
  161 |   close(ctx->sock.fd);

**Environment (please complete the following information):**
 -  Windows 10
 - West latest and GCC
 - 2.4.99

**Additional context**

**Comment by pfalcon** [comment]
@WilliamGFish: Can you please update the subject of this ticket to summarize its content? Please see https://github.com/zephyrproject-rtos/zephyr/issues for examples of good ticket subjects.

**Comment by nashif** [comment]
Can you provide some more context and what test/sample on which platform you are getting this?
