### ISSUE TITLE
ci compliance failures due to intel_adsp_cavs25 sample

### ISSUE THREAD

**Issue by pabigot** [zephyrproject-rtos/zephyr#31327]
samples/audio/sof/boards/intel_adsp_cavs25.conf references a bunch of Kconfig symbols that are out-of-tree, resulting in CI failures as with https://github.com/zephyrproject-rtos/zephyr/pull/28977/checks?check_run_id=1704198353

**Comment by pabigot** [comment]
This went away when I rebased my branch on current master in https://github.com/zephyrproject-rtos/zephyr/pull/28977/checks?check_run_id=1704273529  so these Kconfig variables must be defined in an external module; but this suggests the compliance tests aren't properly setting up the environment for what the PR looks like when rebased on master.

**Comment by nashif** [comment]
compliance tests were not setting up west and modules, now they are, any PRs that were submitted prior to that change will fail with the above, so those PRs will need to be rebased.

**Comment by pabigot** [comment]
Aren't all the compliance tests including CI done on the branch after it's been rebased on current master?  If not, it's not giving us a correct view of what will happen if it's merged.
