### ISSUE TITLE
kconfiglib.py _save_old() may rename /dev/null -- replacing /dev/null with a file

### ISSUE THREAD

**Issue by domo141** [zephyrproject-rtos/zephyr#31362]
**Describe the bug**

the kconfiglib.py _save_old("/dev/null") may actually, unexpectly, succeed. 

afterwards /dev/null was opened for writing as a (new) file 

**To Reproduce**
1. mkdir build; cd build
2. cmake -DBOARD=board\_xyz
3. ls -l /dev/null
4. cat /dev/null

**Expected behavior**

/dev/null is still device node

**Impact**

/dev/null is a file, with kconfig content

**What impact does this issue have on your progress**

host code that opened /dev/null as config file got "garbage"

**Environment (please complete the following information):**

- a docker container (not as root, but probably enough capabilites to rename /dev/null)

zephyr v1.14 -- but after investigating main in 2021-01 it still can happen

** how to fix **

`if not os.path.isfile(path) return` to skip rename if path does not point to a file
(either directly, or via symlink)

**Comment by nashif** [comment]
Can you please submit a PR with the proposed fix?

**Comment by domo141** [comment]
Created (as usual, change was simple, comments and commit message hard)...

 #31438: based on commit msgs ulfalizer may (or may not) follow up soon...

**Comment by nashif** [comment]
lowering priority as this happens only if /dev/null is writable or as root, which is not recommended.
