### ISSUE TITLE
Update CAN-API Documentation

### ISSUE THREAD

**Issue by Nukersson** [zephyrproject-rtos/zephyr#31379]
**Describe the bug**
Current [CAN-API](https://docs.zephyrproject.org/latest/reference/networking/can_api.html) mention  wrong structure parameters in `zcan_filter`, (for example `std_id`):

```
const struct zcan_filter my_filter = {
        .id_type = CAN_STANDARD_IDENTIFIER,
        .rtr = CAN_DATAFRAME,
        .std_id = 0x120,
        .rtr_mask = 1,
        .std_id_mask = 0x7F0
};
```

**To Reproduce**
Compare current [CAN-API](https://docs.zephyrproject.org/latest/reference/networking/can_api.html) with [doxygen docs](https://docs.zephyrproject.org/apidoc/latest/group__can__interface.html#structzcan__filter)

**Expected behavior**
Right names in structures

**Additional context**
Placeholder for me for later fix or somebody, willing update it.

**Comment by alexanderwachter** [comment]
#31380 updates the doc. Thanks for reporting @Nukersson
