### ISSUE TITLE
ARC MPU version number misuse ver3, should be ver4

### ISSUE THREAD

**Issue by YuguoWH** [zephyrproject-rtos/zephyr#31416]
ARC MPU version has number 2, 3, and 4. EM cores can be configured to version 2 and 4. So the version number quoted here should be ver4 instead of ver3. 
https://github.com/zephyrproject-rtos/zephyr/blob/1a369f5cdd6d4afd106d3df8f3d6cc1d988e06ca/arch/arc/core/mpu/arc_mpu_v3_internal.h#L15
Should be version 4

https://github.com/zephyrproject-rtos/zephyr/blob/1a369f5cdd6d4afd106d3df8f3d6cc1d988e06ca/arch/arc/core/mpu/arc_mpu.c#L58
This should actually be arc_mpu_v4

ARC MPU Ver 3, which supports 32Bytes minimal region, is actually an enhanced version of ver 2. But starting from ver 4 it becomes a quite different implement as we could find in `arc_mpu_v3_internal.h` (and should be renamed to arc_mpu_v4_internal.h)
To correct this misuse we could prevent future conflicts between EM and HS cores in ARC MPU versions.

**Comment by nashif** [comment]
@evgeniy-paltsev  can you please take a look at this one?
