### ISSUE TITLE
TSC Strategic Objectives 2021

### ISSUE THREAD

**Issue by MaureenHelm** [zephyrproject-rtos/zephyr#31462]
| Objective | Owner | Contributors |
|-|-|-|
|Support development on Linux, Windows, and MacOS host operating systems.| @stephanosio ||
|Support development with GCC, LLVM, and commercial toolchains.| Toolchain WG ||
|Maintain long term support (LTS) releases for at least two years.| Release Team||
|Make the second long term support (LTS2) release two years after the first (LTS1).| Release Team ||
|Make mainline releases every 4 months that satisfy well-defined quality criteria.| Release Team, Testing WG ||
|Use continuous integration builds and automated checks to validate pull requests, release branches, and the mainline branch.| @nashif ||
|Test release candidates on hardware and consolidate results in a common location.| Testing WG ||
|Review and update APIs to be suitable for Zephyr applications and compatible with hardware from multiple vendors.| @carlescufi ||
|Maintain qualifiability of Bluetooth host and mesh subsystems with the latest version of the Bluetooth standard for every mainline and LTS release.| @carlescufi ||
|Support the Bluetooth controller subsystem with the latest version of the Bluetooth standard.| @asmk-ot | @cvinayak |
|Define and track memory footprint, power, and performance metrics to validate support for resource-constrained and low power devices. This includes support for rebasing reference applications onto new releases without growing beyond resource constraints.| @robwoolley | Testing WG, @nashif, @daor-oti |
|Document development maturity of boards and subsystems to distinguish between experimental and mature support.| Release Team, Testing WG ||
|Publish documentation and sample applications that demonstrate how to use the kernel, drivers, and subsystems.|||
|Engage community developers at all levels, including occasional hobbyists, students, nonmembers, and member company employees.| TSC ||

**Comment by eanderlind** [comment]
For first objective would be useful to clarify if goal is just to  support building on all the hosts (currently supported with at least gcc on X86), or also covers unit/integration testing (posix_native/native64 currently only Linux, and with macOS host on ARM may require more effort). 

MISRA not a goal? (Asking since implies a lot around coding standards etc) Not advocating either way for inclusion.
