### ISSUE TITLE
it8xxx2_evb should not define TICKLESS_CAPABLE

### ISSUE THREAD

**Issue by mengxianglinx** [zephyrproject-rtos/zephyr#31502]
**Describe the bug**
In boards/riscv/it8xxx2_evb/it8xxx2_evb_defconfig CONFIG_TICKLESS_CAPABLE=y while this configure is not user-configurable, it causes build failure.

**To Reproduce**
1. twister -T tests/subsys/logging/log_core_additional/ -p it8xxx2_evb

**Expected behavior**
Test case PASS

**Logs and console output**
error: TICKLESS_CAPABLE (defined at drivers/timer/Kconfig:332) is assigned in a configuration file,
but is not directly user-configurable (has no prompt). It gets its value indirectly from other
symbols. See http://docs.zephyrproject.org/latest/reference/kconfig/CONFIG_TICKLESS_CAPABLE.html
and/or look up TICKLESS_CAPABLE in the menuconfig/guiconfig interface. The Application Development
Primer, Setting Configuration Values, and Kconfig - Tips and Best Practices sections of the manual
might be helpful too.

**Environment (please complete the following information):**
 - OS: (e.g. Linux, MacOS, Windows)
 - Toolchain (e.g Zephyr SDK, ...)
 - Commit SHA or Version used

**Additional context**

**Comment by KangJianX** [comment]
Same problem here, CI build will failed when submit testcases PRs.
