### ISSUE TITLE
Communication across Memory Domains (IPC)

### ISSUE THREAD

**Issue by aangarov** [zephyrproject-rtos/zephyr#31518]
# Motivation
In the modern world security is a critical part of nearly every system design and there are two fundamental security principles: Least Privilege and Separation/Isolation.
Zephyr supports these principles by enabling multiple isolated user-level memory domains.
Design of a system with multiple isolated user-level memory domains requires communication mechanism between the memory domains. Such mechanism is frequently referred as IPC (Inter-Process Communication).
This request proposes to introduce IPC which:
 - Allows secure communication between user-level memory domains
 - Allows to move some drivers from Kernel to User privilege level
 - Supports embedded systems with limited resources (memory)
 - Facilitates transition from a monolithic user-level application design to set of multiple isolated user-level components

Presence of such IPC would make Zephyr security offering more complete and as a result would make Zephyr more attractive.
# Terminology
**IPC server (or server)**
IPC Server is a thread receiving requests/events from IPC clients, processing them, and (if needed) sending responses to the clients.
**IPC client (or client)**
IPC client is a thread sending requests/events to IPC server and (if needed) receiving responses from it.
**IPC Channel**
IPC Channel is a kernel object allowing communication between IPC clients and IPC server
**Queue**
An abstract data type allowing to organize multiple items in a particular order from their delivery perspective. Queue can be implemented in different ways (array, linked list, etc.).
**IPC request (or request)**
A method allowing IPC client to either ask IPC server to provide some service (IPC call) or notify IPC server about occurence of some event (IPC Event). 
**IPC call**
Type of IPC request used in the cases where IPC client waits for a response from IPC server
**IPC Event**
    Type of IPC request used in the cases where IPC client just notifies IPC server about some event without being blocked. An IPC Event is classified as either IPC_EVENT or IPC_INTERRUPT. An event is classified as IPC_INTERRUPT where Kernel needs to notify user-level driver (IPC Server) about occurrence of an interrupt. IPC_EVENT classification is used in all other cases. IPC Events classified as IPC_INTERRUPT are always delivered before the ones classified as IPC_EVENT.
# IPC Overview
IPC is a “many-to-one” communication mechanism (multiple clients and single server) where the communication is always initiated by the clients. The clients can communicate with the server in two ways: Synchronously and Asynchronously.
Synchronous IPC is designed to support “procedure call” paradigm where the client “calls” a function implemented by the server which is executed in the server’s thread context. Execution of the client's thread is blocked until response from the server is received.
Asynchronous IPC is designed to allows IPC clients to notify IPC server about different events. These notifications are delivered to the server without blocking execution of the client's thread.
There are two types of IPC clients: Privileged and Non-Privileged. The only difference between Privileged and Non-Privileged clients is that the privileged ones have more control over priority and classification of their requests.
All IPC communications go through a kernel object called IPC Channel. There could be multiple IPC Channels where each of them used by one specific IPC server and particular set of IPC clients. Note that a thread playing IPC server role for one IPC Channel may be IPC client for other IPC Channel.
Access permissions to IPC Channel are granted to clients and servers at the build/design time. IPC server and clients have different permissions in accessing same IPC Channel (part of IPC APIs is available for IPC servers only and other part of IPC APIs is available for IPC clients only).
IPC Channels are initialized as part of kernel initialization and are ready for use from very beginning of every server/client thread execution.
The pictures below show different types of client-server interactions via IPC Channel and possible system design based on IPC.
![image](https://user-images.githubusercontent.com/77722711/105462130-deef3300-5c96-11eb-95b3-12cbfdee25ff.png)

![image](https://user-images.githubusercontent.com/77722711/105468004-1661dd80-5c9f-11eb-90ce-2e880b9689a9.png)
# IPC APIs (description)
There are four APIs associated with IPC Channel. Details description of the APIs will be given later.
**ipc_call**
This API is used by IPC clients for synchronous IPC with IPC server. It allows the clients to pass to the server a request (IPC call) with additional data and receive a response with additional data (similar to a function call with input and output parameters).
**ipc_event**
This API is used by IPC clients for asynchronous communication with IPC server. It allows the clients to notify the server about particular event and pass limited (by the server design) amount of the data associated with the event. Entire request (including the data) is copied to Event Queue of IPC Channel without blocking client's thread execution.
**ipc_get_request**
This API is used by IPC servers for receiving the requests sent via “ipc_call” and “ipc_event” APIs. This API is blocking meaning that execution of the server’s thread is suspended until either a request/event is delivered or the timeout expires.
**ipc_response**
This API is used by IPC server in order to respond to the client’s requests sent via “ipc_call” APIs. Calling this API does not block execution of the server’s thread.
# IPC Channel
IPC Channel is a composite Kernel object including Call Queue, Event Queue, and Channel State information.
**Call Queue**
Queue object likely implemented as a linked list. Elements in the queue represent IPC client threads waiting in "ipc_call" API. Depending of "ipc_call" parameter the elements are added either according to the client's thread priority or to the end.
**Event Queue**
Queue object where every element is a complete IPC request made through "ipc_event" API. Although each element tracks priority of the thread which called "ipc_event" API, order of the elements in the queue depends on the parameters used in "ipc_event" API. IPC events classified as IPC_INTERRUPT are always server first.
**Channel State**
Data structure containing all the information required for the proper functioning of IPC Channel. Exact structure of Channel State is very implementation dependent, but in this or other form it keeps the the following information and control data:
- Server Thread
Awareness of the server thread associated with the given IPC Channel may be needed for several purposes: a) Scheduling decisions where IPC request release the server thread waiting in "ipc_get_request" API, b) Access control to distinguish between IPC server and IPC client allowed to access the given IPC Channel.
- Call State
State of the served IPC clients in Call Queue (e.g. waiting to send request vs. waiting to get response). It may be used checking correctness of the server behavior (e.g. making sure that the server responds to the client that already "sent" the request and waits for response).
- Request delivery QoS
IPC Channel should provide some fairness in delivering the requests (IPC calls and IPC events) to the server. There shouldn't bea situation that a client (except privileged one) sending IPC events completely blocks delivery of IPC call requests (and vice versa).
- Event sending QoS
IPC design should avoid any dynamic allocation of the resources. Thus capacity of Event Queue is fixed (set and design time). In this case one IPC client could fill Event Queue with its requests and block ability of other clients to send events. IPC Channel need to implement a mechanism preventing such situation (e.g. maintain for each IPC client maximal number of enqueued IPC events). 
# Thread Scheduling
Synchronous IPC can be seen as a mechanism allowing to "move" execution of particular function from the context of IPC client thread to the context of IPC server thread. All the functions executed by IPC client thread are executed at the priority assigned to IPC client thread, but once the function execution moves to the context of IPC server thread the priority may change. In IPC client's flow designed to be executed at low priority some part would be executed at higher priroity (affecting scheduling of other threads) or in IPC client's flow designed to be executed at high priority some part would be executed at lower priroity (potentially leading to QoS degradation). As a mitigation for the issues related to the changes of schedulng priority IPC implements "priority inheritance" mechanism.
At the design time to IPC server thread is assigned base priority. Actual priority of IPC server thread depends on its base priority and priority of the client threads waiting (in IPC call) on the associated IPC Channel. At any moment priority of the server's thread for particular IPC channel is defined as a maximin between the base priority and priority of all IPC client threads waiting in Call Queue for the given IPC Channel.
Picture below demonstrates use of the priority inheritance mechanism. 
![image](https://user-images.githubusercontent.com/77722711/105464039-9a18cb80-5c99-11eb-8da8-91737e92b0d9.png)
**Entry Conditions**
- Thread H (high priority) is waiting for some event.
- Thread M (medium priority) is waiting for some event.
- Thread L (low priority) is running
- Server Thread S (base priority of S is between L and M) is waiting in “ipc_get_request” API
- Call Queue of IPC Channel is empty

**Flow**
1. Thread L calls “ipc_call” API and starts waiting for response. Thread L is added to the head of Call Queue. Thread S starts processing of the request from Thread L at its base priority (S) which is higher than L.
2. Thread M wakes up and starts execution. Execution of Thread S is suspended as its priority (S) is lower than M.
3. Thread M calls “ipc_call” API and starts waiting for response. Thread M is added to Call Queue after Thread L. Processing of request from Thread L in Thread S is resumed at the priority of Thread M.
4. Thread H wakes up and starts execution. Execution of Thread S is suspended as its priority (M) is lower than H.
5. Thread H calls “ipc_call” API and starts waiting for response. Thread H is added to Call Queue before Thread M. Processing of request from Thread L in Thread S is resumed at the priority of Thread H.
6. Processing of request from Thread L is complete and Thread S calls “ipc_response” API. Thread L is removed from Call Queue. Execution of thread L is suspended as its priority (L) is lower than H.
7. Thread S calls “ipc_get_request” API which returns immediately. Thread S starts processing of the request from Thread H at priority H.
8. Processing of request from Thread H is complete and Thread S calls “ipc_response” API. Thread H is removed from Call Queue. Priority of Thread S drops to M. Execution of thread H is resumed as its priority (H) is higher than M.
9. Thread H enters waiting (for some event) state. Execution of Thread S is resumed at priority M.
10. Thread S calls “ipc_get_request” API which returns immediately. Thread S starts processing of the request from Thread M at priority M.
11. Processing of request from Thread M is complete and Thread S calls “ipc_response” API. Thread M is removed from Call Queue. Priority of Thread S drops to S. Execution of thread M is resumed as its priority (M) is higher than S.
12. Thread M enters waiting (for some event) state. Execution of Thread S is resumed at priority S.
13. Thread S calls “ipc_get_request” API and starts waiting for new requests. Execution of thread L is resumed.
# IPC Configuration
**Deadlocks**
Use of IPC may result in deadlocks. For example, Thread A waits in "ipc_call" API on IPC Channel X for thread B playing role of IPC server on IPC Channel X. At the same time thread B waits in "ipc_call" API on IPC Channel Y for thread C playing role of IPC server on IPC Channel Y. At the same time thread C waits in "ipc_call" API on IPC Channel Z for thread A playing role of IPC server on IPC Channel Z. Now we have a deadlock.
Although this situation is a result of pure system design which cannot be fixed at the runtime, but it is possible to help in detecting the deadlocks. Logic of the deadlocks detection may be complicated and may have meaningful impact on the system performance and may be not needed in the final product (where user can believe that there are no deadlocks). Thus the deadlock detection logic can be compiled out by setting corresponding build configuration option.
**Event Queue size**
For each IPC Channel number of elements in Event Queue and their size depends on the functionality and load of the associated IPC server. There should be a way to configure number of elements and element size on per IPC Channel basis. Lack of such configuration (same configuration for all IPC Channels) would result in wastage of system resources (memory).
# Performance
Data transfer between the memory domains in "ipc_call", "ipc_get_request", and "ipc_response" API may have meaningful impact on the overall system performance. With full understanding of importance of the performance this proposal takes quite simple approach: IPC client puts all input parameters of "ipc_call" API in a single buffer and provides single buffer for output parameters. Content of the buffers is copied between the memory domains by Kernel as part of "ipc_get_request" and "ipc_response" API. Within a memory domain parameters are frequently passed by reference and there will be a need some wrapping functions which take multiple parameters passed by reference and copy the parameters into single buffer (prior to calling "ipc_call" API) or from a single buffer (after calling "ipc_call" API). There are multiple ways to avoid (or minimize) such double copying and these improvements should be considered going forward.
# IPC APIs (details)
There are four APIs associated with IPC Channel. User-level threads call these API using syscall mechanism while Kernel-level threads call the APIs directly. Two of these APIs ("ipc_call" and "ipc_event") are available for IPC clients only and other two APIs ("ipc_get_request" and "ipc_response") are available for IPC servers only.
All IPC APIs have a return value indicating success or failure (from Kernel perspective) of the API call. IPC servers may provide additional failure indication specific to the server implementation using its own mechanism (e.g. a field in output data sent via "ipc_response" API).
Multiple parameters of IPC APIs  are pointers to different buffers or variables. For all user-level IPC clients and servers all these pointers are completely verified by Kernel (at least at the point of use).
### ipc_call
This API is used by IPC clients for synchronous IPC with IPC server. It allows the clients to pass to the server a request (IPC call) with additional data and receive a response with additional data (similar to a function call with input and output parameters).
Parameters:
- **channel** - reference of the IPC Channel (kernel object ID, pointer, handle, ...)
- **call_id** - ID of the job to be done by the server (internally server maps this ID to particular function)
- **in_data** - pointer to the buffer containing input data associated with the requested job. This parameter is ignored when “in_data_size” parameter is 0.
- **in_data_size** - size in bytes of the data in the buffer referred by “in_data” parameter. This parameter can be 0 if there is no input data.
- **out_buf** - pointer to the buffer for the output data associated with the requested job. This parameter is ignored when “out_buf_size” parameter is 0.
- **out_buf_size** - size in bytes of the buffer referred by “out_buf” parameter. This parameter can be 0 if no output data is expected.
- **out_data_size** - pointer to a variable which upon successful API execution inidcates size in bytes of the output data in the buffer referred by “out_buf” parameter. In case of API failure due to lack of space in the buffer referred by “out_buf” parameter this parameter indicates size of the output data generated by the server ("out_data_size" parameter in "ipc_response" API).
- **options** - this parameter allows Privileged clients to control priority of the request. For Non-Privileged Clients the request priority is derived from the priority of the thread calling the API. This parameter also is be used by all clients in order define how the requests should be engueued (according to the caller priority or added to the end of the queue).

### ipc_event
This API is used by IPC clients for asynchronous communication with IPC server. It allows the clients to notify the server about particular event and pass limited (by the server design) amount of the data associated with the event. Entire request (including the data) is copied to Event Queue of IPC Channel without blocking client's thread execution.
Parameters:
- **channel** - reference of the IPC Channel (kernel object ID, pointer, handle, ...)
- **event_id** - ID of the event
- **in_data** - pointer to the buffer containing input data associated with the event. This parameter is ignored when “in_data_size” parameter is 0.
- **in_data_size** - size in bytes of the data in the buffer referred by “in_data” parameter. This parameter can be 0 if there is no input data.
- **options** - this parameter allows Privileged Clients: a) control priority of the event, b) send events classified as IPC_INTERRUPT. For Non-Privileged Clients the events are always classified as IPC_EVENT and their priority is derived from the priority of the thread calling the API. This parameter also is be used by all clients in order define how the requests should be enqueued (according to the caller priority or added to the end of the queue).

### ipc_get_request
This API is used by IPC servers for receiving the requests sent via “ipc_call” and “ipc_event” APIs. This API is blocking meaning that execution of the server’s thread is suspended until either a request/event is delivered or the timeout expires.
Parameters:
- **channel** - reference of the IPC Channel (kernel object ID, pointer, handle, ...)
- **client_filter** - ID of the client to receive request from. This parameter can be ANY in order to receive requests from any IPC client.
- **type_filter** - specifies type of the request to receive. This parameter can be any commbination of IPC_CALL, IPC_EVENT, or IPC_INTERRUPT.
- **client_id** - pointer to a variable indicating ID of the client who sent the received request. "client_id" is filled (or verified) by Kernel.
- **req_type** - pointer to a variable indicating type of the received request which can be IPC_CALL, IPC_EVENT, or IPC_INTERRUPT.
- **req_id** - pointer to a variable indicating ID of the received request ("call_id" or "event_id")
- **in_buf** - pointer to the buffer for the input data associated with the request. This parameter is ignored when “in_buf_size” parameter is 0.
- **in_buf_size** - size in bytes of the buffer referred by “in_buf” parameter. This parameter can be 0 if there is no input data.
- **in_data_size** - pointer to a variable indicating actual size in bytes of the data copied to the buffer referred by “in_buf” parameter.
- **out_buf_size** - pointer to a variable indicating size of the client’s buffer for the output data ("out_data_size" of "ipc_call" API).
- **timeout** - maximal amount to time to wait for new request/event. This parameter can be set as NO_WAIT or FOREVER.

### ipc_response
This API is used by IPC server for sending response to the client’s requests issued via “ipc_call” APIs. Calling this API does not block execution of the server’s thread.
Parameters:
- **channel** - reference of the IPC Channel (kernel object ID, pointer, handle, ...)
- **client_id** - ID of the Client the response should be sent to.
- **out_data** - Pointer to the buffer containing the data to be sent to the client. This parameter is ignored when “out_buf_size” parameter is 0.
- **out_data_size** - size in bytes of the data in the buffer referred by “out_data” parameter. This parameter can be 0 if there is no output data.

**Comment by dcpleung** [comment]
Have you looked at zbus? It is a message bus for Zephyr.

**Comment by aangarov** [comment]
No, I didn't look at zbus. Unfortunately I had to switch to other activities and do not work anymore on Zephyr.

**Comment by rodrigopex** [comment]
@aangarov, Could we close this issue so far?

**Comment by BorisKrichevski** [comment]
Sorry for late response. 
@aangarov moved to other activities and is not involved into Zephyr related project
I cover for him and need couple weeks to learn current status and update.

**Comment by rodrigopex** [comment]
@BorisKrichevski, any update on that?

**Comment by BorisKrichevski** [comment]
Hi Rodrigo

Sorry for delay
We can withdraw the issue of “Communication across Memory Domains” in the form that Alexander proposed it.
Our Zephyr software should keep maximal compatibility with Linux software we develop for parallel project with unlimited memory (DDR) and extended  capabilities.
End last week we finally decided to use gRPC for communication between Linux processes.
Zephyr does not have gRPC support, we need to choose/develop/modify protocol for communication between Memory Domains that provides maximal compatibility with gRPC with minimal memory usage.
Advices are appreciated.

Boris Krichevski
NCNG FW Architecture

**Comment by rodrigopex** [comment]
@BorisKrichevski, thank you. I am closing the issue. If you need to discuss something related to that, please reopen it.
