### ISSUE TITLE
unexpected sign-extension in Kconfig linker symbols on 64-bit platforms

### ISSUE THREAD

**Issue by andrewboie** [zephyrproject-rtos/zephyr#31562]
**Describe the bug**

Kconfig exposes all Kconfig values as linker symbols in the generated binary. On 64-bit platforms, it appears that if a 32-bit hex value is expressed in Kconfig with a 1 in the most significant bit, this gets sign-extended in the generated linker symbol, as if it were a negative value.

**To Reproduce**

```
diff --git a/boards/x86/up_squared/up_squared_defconfig b/boards/x86/up_squared/up_squared_defconfig
index 5e8005a539..aabd59afb4 100644
--- a/boards/x86/up_squared/up_squared_defconfig
+++ b/boards/x86/up_squared/up_squared_defconfig
@@ -11,3 +11,4 @@ CONFIG_UART_CONSOLE=y
 CONFIG_X2APIC=y
 CONFIG_SMP=y
 CONFIG_MP_NUM_CPUS=2
+CONFIG_KERNEL_VM_SIZE=0xC0000000
```

Do a build and examine the binary:

```
$ nm -n zephyr/zephyr.elf | grep VM_SIZE
ffffffffc0000000 A CONFIG_KERNEL_VM_SIZE
```

**Expected behavior**
`CONFIG_KERNEL_VM_SIZE` should be 0xC0000000 and not 0xffffffffc0000000 

**Impact**
Some build scripts examine the ELF binary to obtain Kconfig values, and will be working with incorrect data.
I *think* the scope of this problem is only these linker symbols, which is are not used by the kernel itself at runtime.

**Comment by dcpleung** [comment]
This is probably due to `GEN_ABSOLUTE_SYM()` inside `include/toolchain/gcc.h` where values are parsed as signed 32-bit integers.
