### ISSUE TITLE
lora: sx126x: interrupt pin permanently enabled

### ISSUE THREAD

**Issue by JordanYates** [zephyrproject-rtos/zephyr#31569]
**Describe the bug**
The sx126x driver leaves the `DIO1` interrupt permanently enabled, resulting in excess power consumption.
For nRF SoC's, this means the `GPIOTE` peripheral is permanently enabled, increasing current draw by ~15uA.
Per the datasheet (Table 8-3), DIO1 is not driven as an output in `Reset`, `Startup`, or `Sleep` modes.
We can therefore safely turn off the interrupt in sleep mode.

**Expected behavior**
`DIO1` pin should only have the interrupt enabled when it is actually needed (Not in sleep mode).

**Impact**
Minor, permanent +15uA to the current consumption of any application.

**Environment (please complete the following information):**
 - Zephyr v2.4

**Comment by tagunil** [comment]
Does the sx1276 driver have the same issue?

**Comment by JordanYates** [comment]
> Does the sx1276 driver have the same issue?

Yes, all DIO pins have their interrupts permanently enabled in `SX1276IoIrqInit`.
The sx1276 has a much different sleep model, so the same solution doesn't directly apply.
That driver also currently uses `loramac-node` implementations for sleep and standby transitions.
I don't have any hardware with the older LoRa modem however, so I can't validate any potential solutions.
