### ISSUE TITLE
Wrong log settings in can_stm32 driver

### ISSUE THREAD

**Issue by Nukersson** [zephyrproject-rtos/zephyr#31573]
https://github.com/zephyrproject-rtos/zephyr/blob/77861037d9ca71f0093c3e604b7545084ce7fb16/drivers/can/can_stm32.c#L20

It must be `LOG_MODULE_REGISTER` instead of `LOG_MODULE_DEFINE`.

**Comment by alexanderwachter** [comment]
LOG_MODULE_REGISTER(can_driver);
Is called in can_common.c:13.
You can only register a module once.

**Comment by Nukersson** [comment]
> LOG_MODULE_REGISTER(can_driver);
> Is called in can_common.c:13.
> You can only register a module once.

LOG_MODULE_DEFINE not worked for me with samples/can/driver

**Comment by alexanderwachter** [comment]
the sample builds without error on the latest HEAD.
`west build -b nucleo_f746zg zephyr/samples/drivers/can`

**Comment by Nukersson** [comment]
> nucleo_f746zg

Sorry. It was my bad. It is not worked for me with my h7 can driver under dev.

**Comment by Nukersson** [comment]
Found it out.

I've used `LOG_MODULE_DECLARE(can_stm32h7_driver, CONFIG_CAN_LOG_LEVEL); ` with different name than `can_driver`, thus I need `LOG_MODULE_DEFINE` since it is not declared in can_common.c

**Comment by alexanderwachter** [comment]
BTW @Nukersson #31061should work on the H7 too.

**Comment by Nukersson** [comment]
> BTW @Nukersson #31061 should work on the H7 too.

Thank you very much! I will try to help in PR pointed by you.
