### ISSUE TITLE
BMD345: Extended BLE range with PA/LNA 

### ISSUE THREAD

**Issue by Navin-Sankar** [zephyrproject-rtos/zephyr#31585]
I am using [BMD-345 Eval kit](https://www.mouser.com/datasheet/2/1025/BMD-345_DataSheet_(UBX-19039908)-1879743.pdf) from ubox  to extended the BLE range using PA/LNA.

How to enable PA/LNA feature in zephyr to achieve long range using dynamic method?

-> **BT_CTLR_GPIO_LNA_PIN** Kconfig is used to control LNA pin.
-> **BT_CTLR_GPIO_PA_PIN** Kconfig is used to control PA pin

what about **MODE** and **A-SEL** pin?

**Comment by cvinayak** [comment]
Yes, use the PA/LNA Kconfig options in then Zephyr BLE controller.

Setup the MODE and A-SEL pins using GPIO APIs in your application or if you have a board defined then initialize them in the board init. (Example, https://github.com/zephyrproject-rtos/zephyr/blob/master/boards/arm/nrf52840dongle_nrf52840/board.c)
