### ISSUE TITLE
test: ipc: Test from samples/subsys/ipc/rpmsg_service fails on nrf5340dk_nrf5340_cpuapp

### ISSUE THREAD

**Issue by PerMac** [zephyrproject-rtos/zephyr#31616]
**Describe the bug**
The test from the title fails on nrf53_cpuapp. The sample is started and hangs after printing:
DEVICE: RPMsg Service [master] demo started
 
**To Reproduce**
1. Have nrf5340dk connected
2. call `/scripts/twister --device-testing -T samples/subsys/ipc/rpmsg_service/ -p nrf5340dk_nrf5340_cpuapp --device-serial /dev/ttyACM2 -v -v`
3. See error

**Expected behavior**
The test passes

**Impact**
Not clear

**Logs and console output**
```
DEBUG   - DEVICE: *** Booting Zephyr OS build v2.5.0-rc1-16-g085d2eda8d2b  ***
DEBUG   - DEVICE: Starting application thread!
DEBUG   - DEVICE: 
DEBUG   - DEVICE: RPMsg Service [master] demo started
```
and then hangs

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04
 - Toolchain Zephyr SDK
 - Commit SHA or Version used: v2.5.0-rc1-16-g085d2eda8d2b

**Comment by ioannisg** [comment]
will take a look

**Comment by ioannisg** [comment]
@PerMac I am not sure this is a bug. For the sample to work one needs to flash the two cores (master and remote), I guess, separately. West build takes care of building both executables, but the images needs to be flashed individually.

**Comment by KeremSAR** [comment]
I have the same issue, It hangs there for both remote and master application.
`while (!rpmsg_service_endpoint_is_bound(ep_id)) {
		k_sleep(K_MSEC(1));
	}`
I flashed the images individually for nrf5340 cores. What could be the issue ?

**Comment by pauleffect90** [comment]
Same issue. @KeremSAR. Did you manage to fix it?

**Comment by Thomas000001** [comment]
Hello, @KeremSAR and @pauleffect90, I also got the same issue of  while (!rpmsg_service_endpoint_is_bound(ep_id)) { k_sleep(K_MSEC(1)); } . Did you fix it?
Sincerely.

**Comment by pauleffect90** [comment]
> Hello, [@ioannisg](https://github.com/ioannisg) 、[@KeremSAR](https://github.com/KeremSAR) and [@pauleffect90](https://github.com/pauleffect90), I also got the same issue of while (!rpmsg_service_endpoint_is_bound(ep_id)) { k_sleep(K_MSEC(1)); } . Did you fix it? Sincerely.

yeah, from what I remember, it was an overlay issue. The tx/ rx endpoint addresses (ram) need to be inverted on the app/ network core (like the uart rx goes to the uart tx). Im speaking off the top of my head, though.

**Comment by Thomas000001** [comment]
@pauleffect90 OK, I will try it later. Thank you for your suggestion.
