### ISSUE TITLE
Add an application power management sample (PM_POLICY_APP)

### ISSUE THREAD

**Issue by eHammarstrom** [zephyrproject-rtos/zephyr#31774]
Currently the device_pm API is documented and also used in samples, so figuring the device_pm API
out should be no obstacle.
But for the system-wide PM it is not as straight forward, a simple example application based on one of
the supported SoCs would be helpful when looking into the system PM API.

**Describe the solution you'd like**
Add a sample with a short life cycle of waking up, doing something, and then going back to deep sleep or
anything similar for a while.

Perhaps this is clear for people using the PM subsystem -- but I have gotten used to be able to find neat
samples in Zephyr :)

**Comment by ceolin** [comment]
We have samples and tests in tree doing what was requested here. I think the biggest problem is that some of them are not easily found. Instead of just creating another similar test I'll gather all of them and ensure they are visible in the documentation.
