### ISSUE TITLE
twister: Raise error/warning when non-existing platform called

### ISSUE THREAD

**Issue by PerMac** [zephyrproject-rtos/zephyr#31868]
**Is your enhancement proposal related to a problem? Please describe.**
When twister is called for an unexisting platform it will just report, that 0 tests were executed. Apparently, this can cause issues in internal CI plans. If a platform name changed, it was removed or typo was made, it can result in not detecting such changes in the CI as currently no error/warning is raised.

**Describe the solution you'd like**
When a given platform is not existing in zephyr, twister should report it by raising a warning/error when a user tries to run twister for such platform.

**Comment by PerMac** [comment]
@nashif @galak Is there any reason why no warning/error is raised in the above case? Any objection against adding such a warning?

**Comment by nashif** [comment]
submit a PR please.
