### ISSUE TITLE
uart_nrfx_uarte: `CONFIG_UART_ASYNC_API` with `CONFIG_PM_DEVICE` breaks

### ISSUE THREAD

**Issue by JordanYates** [zephyrproject-rtos/zephyr#31930]
**Describe the bug**

There are two breaking problems with the `uart_nrfx_uarte.c` driver.

Firstly, commit 751bdf483b0345eb4de3f424587fd5ce75ec5b25 makes `uarte_nrfx_poll_out` early exit if the device is not in the active state. This has exposed the issue that `data->pm_state` is never updated in `uarte_nrfx_set_power_state` if the async API is enabled on that instance. This issue only appears after disabling the driver for the first time, as `data->pm_state` is initialised to `DEVICE_PM_ACTIVE_STATE`. Therefore after disabling the driver once, all further calls to `uarte_nrfx_poll_out` will do nothing.

After fixing the above issue by appropriately updating `data->pm_state`, the second issue appears.

When the async API is enabled on an instance, and the driver transitions to the off mode, the UART peripheral is immediately disabled: https://github.com/zephyrproject-rtos/zephyr/blob/67f43119be9485844219bb38025f9e49d37da0bf/drivers/serial/uart_nrfx_uarte.c#L1577

This cancels any ongoing transmissions, but more importantly the `ENDTX` and `TXSTOPPED` events are never generated. This means that when the peripheral is next enabled, `is_tx_ready` will always return false, locking up whichever thread is trying to send data (the logging thread in my case). I cannot easily test whether this same error appears when the async API is not enabled. Without bisecting, this appears to be a regression introduced in db6bfde8b36ec4e164eed11715acb29996172459.

The second issue can be resolved (poorly) by waiting for the transmission to complete before disabling the peripheral:
```
		if (get_dev_data(dev)->async) {
			while(!is_tx_ready(dev)) {
				k_sleep(K_MSEC(1));
			}
			nrf_uarte_disable(uarte);
			uarte_nrfx_pins_enable(dev, false);
			return;
		}
```

**Expected behavior**

The UARTE peripheral should be able to be powered up and down when the async API is enabled.
`uarte_nrfx_poll_out` should not block forever / the power down sequence should properly cleanup the peripheral

**Impact**
This breaks logging/printk in my applications which use the async API together with power management.

**Environment (please complete the following information):**
 - Zephyr v2.5rc2

**Comment by nashif** [comment]
@carlescufi  please reassign
