### ISSUE TITLE
Implement an I2S / SAI (shim) driver for NXP IMX-RT1060 (mcux).

### ISSUE THREAD

**Issue by micnet49** [zephyrproject-rtos/zephyr#32037]
**Is your feature request related to a problem? Please describe.**
I would like to develop an application which can play / receive audio via the SAI1 peripheral (by means of eDMA) of the NXP IMX-RT1060 MCU using the board IMXRT1060-EVK (and its I2C controlled codec WM8960).

**Describe the solution you'd like**
I simply like to use the Zephyr I2S API for getting audio sending and audio receiving to work at the SAI1 interface. I guess a shim driver for the exisiting [NXP HAL driver `fsl_sai.c` and `fsl_sai_edma.c` ](https://github.com/NXPmicro/hal_nxp/tree/master/mcux/drivers/imx) has to be developped.

**Describe alternatives you've considered**
I tried to use the NXP HAL drivers functions from `fsl_sai.h` and `fsl_sai_edma.h` directly... still without success.

**Additional context**
Codec driver for WM8960 (also missing for Zephyr).

**Comment by micnet49** [comment]
Is there a chance that there will be a contribution to this issue within the next three month?

**Comment by MaureenHelm** [comment]
> Is there a chance that there will be a contribution to this issue within the next three month?

We're planning to work on this, but a little further out. In the meantime, #32054 may provide some inspiration if you'd like to tackle it sooner.

**Comment by micnet49** [comment]
I would like to have the "stale" label removed. The issue is still important for my application.

**Comment by JonathanVanWin** [comment]
If you are interested, I started developing the general API, and driver for ST https://github.com/zephyrproject-rtos/zephyr/issues/34631#issuecomment-879055848
