### ISSUE TITLE
net: lwm2m: Testing Strategy for LWM2M Engine

### ISSUE THREAD

**Issue by broglep-work** [zephyrproject-rtos/zephyr#32075]
Currently only coap lib is covered with some unit tests, apart from that it appears that there is no other testing coverage of the LWM2M engine or the client. 

Are there any ideas what the best approach would be to increase the test coverage of the LWM2M engine?
Would it make sense to add unit tests for big parts of the LWM2M engine or would it be better to take an more end to end approach and test the engine together with sample LWM2M client against an actual LWM2M server (maybe related to #29764), or rather something in between like component tests?

There are also TestFests held by OMA where clients are tested for their spec conformance against different servers. If not yet happened, it could make sense to take part of such a TestFest

**Comment by rlubos** [comment]
Yeah, that's a weak point of our LwM2M implementation, there's a very old issue regarding this which hasn't gotten much attention yet (https://github.com/zephyrproject-rtos/zephyr/issues/4634).

I think that any contribution in the test area would be valuable, it's a pity there's no test coverage for the LwM2M implementation and I didn't get to adding tests yet.

Personally, I was thinking of extending the Docker-based testing for the LwM2M, it'd require some initial research first though, i. e. it'd be needed to run some LwM2M server implementation in the Docker (only Leshan comes to my mind). Plus I don't know Leshan API very well, so it'd be needed to investigate whether it'd be feasible to use it in an automated test environment (I've only used web UI).

Another option I can see is to use ztest to verify the overall LwM2M operation, but that would require some minimalistic server implementation on our side (I'm not thinking of providing a LwM2M server implementation as a library to Zephyr, more of a minimal set of handlers in the test itself needed to proceed with bootstrap/register and to test some basic read/write/discover/observe operations).

As for the unit testing, there are components that I think could be covered fairly easy with tests (content writers), but as for the  LwM2M engine itself I haven't given it a good thought yet - perhaps it'd be needed to modularize it a bit, currently lwm2m_egine.c is a huge blob.
