### ISSUE TITLE
spi_nor flash multi-instance support

### ISSUE THREAD

**Issue by DarrylGamroth** [zephyrproject-rtos/zephyr#32100]
**Is your enhancement proposal related to a problem? Please describe.**
I would like to use multiple SPI connected serial NOR flash ICs but the existing spi_nor driver only supports a single device.

**Describe the solution you'd like**
Multi-instance support similar to spi_flash_at45.

**Describe alternatives you've considered**
Using AT45 DataFlash except its capacity is too small.

**Comment by madscientist159** [comment]
Just ran into this rather odd limitation.  Looking into fixing it.

**Comment by madscientist159** [comment]
Initial patch here:
https://gitlab.raptorengineering.com/kestrel-collaboration/kestrel-firmware/zephyr-rtos/-/commit/e93d84d2621b569bc5700e7a8e57fb6fcc6661c5

We're blocked on submitting a PR for this until https://github.com/zephyrproject-rtos/zephyr/pull/32844 has been merged.

**Comment by dakejahl** [comment]
What's the status here? Looks like #32844 is merged. I am also interested in using multiple external flash devices.

**Comment by Man0D** [comment]
Hi, is there any news on this issue ?

**Comment by madscientist159** [comment]
Unfortunately commit fb76f47f864 (merged shortly after #32844) broke this support, and with Zephyr 3.2 dropping support for key features required by Kestrel (#46758) we probably won't be looking at this in the near term.  If someone else would like to pick it up we can test on existing hardware with multiple devices.

**Comment by GeorgePriestner-Eaton** [comment]
Is there any update on this please?

I am attempting to use external NOR flash with STM32H743 and getting 'undefined reference to `__device_dts_ord_132' error.

I disabled all SPI controllers other than spi3 (the one I'm, using with the jedec,spi-nor) but still get the issue.

**Comment by de-nordic** [comment]
> 
> I am attempting to use external NOR flash with STM32H743 and getting 'undefined reference to `__device_dts_ord_132' error.

That describes nothing.

**Comment by de-nordic** [comment]
The request is quite vague but I guess that https://github.com/zephyrproject-rtos/zephyr/pull/70415 has already fixed it, closing. If not fixed, reopen and fill in with more details what is required.
