### ISSUE TITLE
Provide test execution times per ztest testcase 

### ISSUE THREAD

**Issue by nashif** [zephyrproject-rtos/zephyr#32137]
**Is your enhancement proposal related to a problem? Please describe.**
We do not have any information about how long each test runs when running tests using ztest.

**Describe the solution you'd like**
For each test, print our the execution time as part of the results

**Describe alternatives you've considered**
Provide test execution time per testcase.

For example:

now:
```
START - test_sem_multi_take_timeout_diff_sem
 PASS - test_sem_multi_take_timeout_diff_sem
```
with per test execution time:
```
START - test_sem_multi_take_timeout_diff_sem
 PASS - test_sem_multi_take_timeout_diff_sem in 2.54 seconds
```

**Comment by nashif** [comment]
@jocelyn-li FYI

**Comment by enjiamai** [comment]
Ok, got it, will add this.
