### ISSUE TITLE
AArch64 idle loop corrupts IRQ state with CONFIG_TRACING

### ISSUE THREAD

**Issue by jharris-intel** [zephyrproject-rtos/zephyr#32143]
**Describe the bug**
[arch_cpu_atomic_idle](https://github.com/zephyrproject-rtos/zephyr/blob/b3ff89bd511afef484c193a428633f6a1c866944/arch/arm/core/aarch64/cpu_idle.S#L31) on AArch64 with CONFIG_TRACING clobbers X0, resulting in potentially corrupted IRQ state.

**To Reproduce**

Examine [arch_cpu_atomic_idle](https://github.com/zephyrproject-rtos/zephyr/blob/b3ff89bd511afef484c193a428633f6a1c866944/arch/arm/core/aarch64/cpu_idle.S#L31) 

**Expected behavior**
`arch_cpu_atomic_idle` restores the correct IRQ state on AArch64.

**Impact**
`arch_cpu_atomic_idle` on AArch64 potentially corrupts IRQ state / restores the wrong IRQ state, leading to missing interrupts and hangs. This only affects AArch64.

**Logs and console output**

n/a

**Environment (please complete the following information):**
- OS: Ubuntu 18.04.5 LTS
- Toolchain (e.g Zephyr SDK, ...)
- Commit SHA or Version used: based off of /u/MrVan's AArch64 SMP branch (#30676) with some additional fixes that I'm in the process of upstreaming. That being said, the references below are from trunk.

**Additional context**

The current source of [arch_cpu_atomic_idle](https://github.com/zephyrproject-rtos/zephyr/blob/b3ff89bd511afef484c193a428633f6a1c866944/arch/arm/core/aarch64/cpu_idle.S#L31)  is as follows:

```asm
GTEXT(arch_cpu_atomic_idle)
SECTION_FUNC(TEXT, arch_cpu_atomic_idle)
#ifdef CONFIG_TRACING
	stp	xzr, x30, [sp, #-16]!
	bl	sys_trace_idle
	ldp	xzr, x30, [sp], #16
#endif
	msr	daifset, #(DAIFSET_IRQ)
	isb
	wfe
	tst	x0, #(DAIF_IRQ)
	beq	_irq_disabled
	msr	daifclr, #(DAIFSET_IRQ)
_irq_disabled:
	ret
```
If CONFIG_TRACING is enabled, the call to `sys_trace_idle` is allowed to clobber X0. This then results in the check after wfe being unknown, potentially unmasking interrupts when interrupts should not be unmasked, or potentially _not_ unmasking interrupts when interrupts _should_ be unmasked.

`arch_cpu_idle` has much the same issue, but only as a latent bug (because `arch_cpu_idle` doesn't use X0.)

The simplest fix here is just to change 
```asm
#ifdef CONFIG_TRACING
	stp	xzr, x30, [sp, #-16]!
	bl	sys_trace_idle
	ldp	xzr, x30, [sp], #16
#endif
```
to
```asm
#ifdef CONFIG_TRACING
	stp	x0, x30, [sp, #-16]!
	bl	sys_trace_idle
	ldp	x0, x30, [sp], #16
#endif
```
(This would be unsafe if `arch_cpu_atomic_idle` required that other arguments were preserved after the call to `sys_trace_idle` - luckily `arch_cpu_atomic_idle` only takes one argument.)

**Comment by MrVan** [comment]
Indeed. arch/arm/core/aarch32/cpu_idle.S store/restore r0. I think it should be ok to just store/restore x0 here and add a comment that x0-x3 maybe clobbered?
