### ISSUE TITLE
Plan to support raspberry pi Pico?

### ISSUE THREAD

**Issue by awsa2ron** [zephyrproject-rtos/zephyr#32193]
Hi,

Could zephyr support support raspberry pi Pico? 
Looks rtt and freeRTOS already support it.
FYI.
https://www.seeedstudio.com/blog/2021/02/05/rust-rt-thread-os-freertos-come-to-the-raspberry-pi-pico/

**Comment by panchalnikunj** [comment]
https://www.youtube.com/channel/UCA4j-J-TFW_9Dt4iTwIjtYQ

Once visit this channel for raspberry pi pico projects.

**Comment by panchalnikunj** [comment]
https://www.youtube.com/channel/UCA4j-J-TFW_9Dt4iTwIjtYQ

Once visit this channel for Raspberry Pi Pico Projects
