### ISSUE TITLE
STM32F4 stuck handling I2C interrupt

### ISSUE THREAD

**Issue by JonasNorling** [zephyrproject-rtos/zephyr#32265]
Our STM32F4 based system locks up and gets reset by the watchdog once in a while. It gets stuck handling I2C interrupts continuously, starving the rest of the system of CPU cycles.

I have narrowed it down to that stm32_i2c_msg_write() in i2c_ll_stm32_v1.c enables the BUF interrupt twice, first in stm32_i2c_enable_transfer_interrupts() and then by a call to LL_I2C_EnableIT_TX(). On some parts BUF and TX are separate interrupt flags and the code makes sense, but on STM32F4 LL_I2C_EnableIT_TX() turns on the BUF interrupt. The transfer kicks off after the interrupts are first enabled, and the transfer may have been completed by the time the interrupt is enabled a second time in stm32_i2c_msg_write(). The ISR code is not prepared to have interrupts re-enabled when it thought there is no work left to do, so handle_txe() gets called repeatedly forever.

Tested on Zephyr v2.2.0, but the code looks basically the same on 2.4.0.

Removing the LL_I2C_EnableIT_TX() call in stm32_i2c_msg_write() makes the behaviour better, but that wouldn't work on all STM32 parts. Reproduction is easy if a k_sleep() call is inserted between the interrupt calls in stm32_i2c_msg_write().

**Comment by erwango** [comment]
Thanks for reporting and investigating the issue. I've been able to test this on F4 device.
It appears that the same applies to F1, F2 and L1, while other series use _v2.c so this could be fixed unconditionally in this file.
I've also validated on F1 board.
