### ISSUE TITLE
shield: cmake: Shield conf is not loaded during build

### ISSUE THREAD

**Issue by Zzzwierzak** [zephyrproject-rtos/zephyr#32269]
**Describe the bug**
Shield conf is not loaded during build

**To Reproduce**
1. mkdir build; cd build
2. cmake -DBOARD=board\_xyz -DSHIELD=abc
3. make
4. See error - abc.proj is not taken to build. 

**Expected behavior**
abc.conf is used during cmake 

**Impact**
Missing configuration(in autoconf.h) for shield. 

**Workaround/Fix**
zephyr/cmake/app/boilerplate.cmake

Change line 350 from : 
if(EXISTS ${shield_dir}/${s_dir}/${s}.conf)
To:
if(EXISTS ${SHIELD_DIR_${s}}/${s}.conf)

**Comment by erwango** [comment]
@tejlmand

**Comment by carlescufi** [comment]
@jfischer-no and @erwango can you confirm?

**Comment by jfischer-no** [comment]
> @jfischer-no and @erwango can you confirm?

No. Just tried it out, the shields we have in the tree work fine.
This issue description is weird. It is been a long time since we switched from *.conf to similar Kconfig structure as in boards.

**Comment by tejlmand** [comment]
@Zzzwierzak thanks for reporting, fixed here: #32318

**Comment by Zzzwierzak** [comment]
@tejlmand Thank you.
