### ISSUE TITLE
STM32 counter driver error in estimating alarm time

### ISSUE THREAD

**Issue by Antonis510** [zephyrproject-rtos/zephyr#32260]
**Describe the bug**

The RTC alarm of the counter driver for STM32 devices fails if the RTC time and date have been initialized with the current date. The initialization process is done using the low-level stm32 libraries. Then, if the alarm is set for a few seconds, it will not be triggered. Here you can find a [sample.](https://github.com/Antonis510/Zephyr-RTOS/tree/stm32_counter_issue)

After investigating the stm32 counter driver, I found that the estimated alarm time has the year 2000 as a base and is used as an input to the gmtime_r function, to produce the alarm date and time. The gmtime_r function needs as input, time from 1970. I believe the problem is here. Although this approach works because the output year will not be used in the process, 2000 is a leap year while 1970 is not. As RTC progresses, the time that the alarm is calculating will have one day difference due to the leap year.

To test my theory, I run the same example with a date before the end of February 2000 (10/1/2000) and it works. Then I run it one more time with 28/2/2000 23:59:00 as date and time. The code runs successfully for almost one minute and then stalls.

The issue can be solved by adding the 2000 timestamp to the estimated time and can be found [here](https://github.com/Antonis510/zephyr-1/tree/fix_stm32_driver_counter). 
All the above test run faultlessly.

**To Reproduce**

1. from [here](https://github.com/Antonis510/Zephyr-RTOS/tree/stm32_counter_issue), build the sample/counter/stm32_counter sample. There are three configuration files for the different dates mentioned above.

2. Flash it to nucleo_l496zg using west flash.

3. Open a serial console.

**Expected behavior**

The application should print the date and time every few seconds (ex: “Date is 2021:01:12:10:00:00”)

**Impact**

High impact for applications with wakeup alarm.

**Environment:**

- OS: Linux Mint 

- Toolchain  Zephyr SDK

- Commit SHA 88725260e622ab4d0a71a267f0a67b99f1ec6d0e

**Comment by erwango** [comment]
@Antonis510 Many thanks for reporting the bug, solution and way to reproduce, this really helps!
