### ISSUE TITLE
drivers: flash: stm32: Flush ART Flash cache after erase operation

### ISSUE THREAD

**Issue by ABOSTM** [zephyrproject-rtos/zephyr#32320]
**Describe the bug**
Implement the same than 
* #32218 drivers: flash: stm32g4: Flush caches after erase and write #32218

but for other STM32 series.
STM32G0 and SGTM32WB are concerned.
Other series, either do not support ART or have cache disabled by default.

**Comment by FRASTM** [comment]
For the stm32G0 series, the FLASH ACR only has CPU Instruction cache reset bit (ICRST:) :
```
 Programming and cache
If an erase operation in Flash memory also concerns data in the instruction cache, the user
has to ensure that these data are rewritten before they are accessed during code execution.
```
