### ISSUE TITLE
reimplement tests/kernel/timer/timer_api

### ISSUE THREAD

**Issue by pabigot** [zephyrproject-rtos/zephyr#32339]
As described in https://github.com/zephyrproject-rtos/zephyr/pull/32277#issuecomment-779283999 and related discussion, the timer_api test was designed for a world that exists only when tickless timer is disabled; that world was made opt-in via c0a184c067e50bb1ba753d9a9d30ad0275a66a52 back in 2018.

This repeatedly causes problems where the conditions for passing are tweaked as new platforms are discovered to reveal gaps in the test design.

The test should be re-implemented to be correct in the face of tickless configurations.  To the degree `CONFIG_TICKLESS_KERNEL=n` is to be supported it should have an equivalent test.

**Comment by nashif** [comment]
new tests or improved tests are always welcome, just submit a PR.
