### ISSUE TITLE
Use of unitialized variables in can_set_bitrate()

### ISSUE THREAD

**Issue by talih0** [zephyrproject-rtos/zephyr#32331]
**Describe the bug**
The function can_set_bitrate() doesn't set timing.sjw and timing_data.sjw. 
The variables are uninitialized and parsed to can_set_timing(), which uses the uninitialized values to set sjw parameters.
Functions that calls can_set_bitrate() will also have this bug. (i.e. can_configure()).

The function was added in pull request #28345.

**To Reproduce**
west build -p auto -b ... samples/subsys/canbus/canopen
(I'm working on a board that hasn't yet been upstreamed)

**Comment by alexanderwachter** [comment]
@henrikbrixandersen @karstenkoenig @martinjaeger
Any ideas how ti set a proper sjw. We could pass 0 and define in the API that zero does not change the value.

**Comment by henrikbrixandersen** [comment]
> Any ideas how ti set a proper sjw. We could pass 0 and define in the API that zero does not change the value.

That sounds reasonable.
