### ISSUE TITLE
2021 GSoC Project Idea: Transplantation for embarc_mli

### ISSUE THREAD

**Issue by IRISZZW** [zephyrproject-rtos/zephyr#32445]
Indroduction:

The [embARC Machine Learning Inference Library](https://github.com/foss-for-synopsys-dwc-arc-processors/embarc_mli) (MLI Library) is the basis for machine learning inference for lower power families of ARCv2 DSP cores (ARC EMxD and ARC HS4xD). Its purpose is to enable porting of machine learning models mostly based on NN to ARC processors.

The library is a collection of ML algorithms (primitives) that roughly can be separated into the following groups:

- Convolution - convolve input features with a set of trained weights

- Pooling – pool input features with a function

- Common - Common ML, mathematical, and statistical operations

- Transform - Transform each element of input set according to a particular function

- Element-wise - Apply multi-operand function element-wise to several inputs

- Data manipulation - Move input data by a specified pattern

we are interesting to transplant this library to zephyr RTOS and do some applications using embarc_mli and zephyr RTOS.

Difficulty: Medium
Skill Required: C, cmake, machine learning
Hardware requirement: Computer with ARC tools installed
Possible mentor: Watson Zeng(zhiwei@synopsys.com)

**Comment by puranjaymohan** [comment]
Hi! This looks very interesting to me. I would like to submit a proposal for this idea, if it gets selected.
