### ISSUE TITLE
intel_adsp_cavs15: run testcases of fifo failed

### ISSUE THREAD

**Issue by KangJianX** [zephyrproject-rtos/zephyr#32513]
**Describe the bug**
run testcases of fifo failed

**To Reproduce**
1. twister -p intel_adsp_cavs15 --device-testing -T tests/kernel/fifo/ --west-flash="/home/ztest/work/zephyrproject/zephyr/boards/xtensa/intel_adsp_cavs15/tools/flash.sh,/home/ztest/work/zephyrproject/modules/audio/sof/keys/otc_private_key.pem,/home/ztest/work/zephyrproject/modules/audio/sof/zephyr/ext/rimage/config,/home/ztest/work/zephyrproject/modules/audio/sof/zephyr/ext/rimage/build/rimage" --device-serial-pty="/home/ztest/work/zephyrproject/zephyr/boards/xtensa/intel_adsp_cavs15/tools/adsplog.py,--no-history"
2. See error

**Logs and console output**
Running test suite fifo_api
..................................................................................................................................................................................................................
START - test_fifo_thread2thread
PASS - test_fifo_thread2thread
..................................................................................................................................................................................................................
START - test_fifo_thread2isr
PASS - test_fifo_thread2isr
..................................................................................................................................................................................................................
START - test_fifo_isr2thread
PASS - test_fifo_isr2thread
..................................................................................................................................................................................................................
START - test_fifo_get_fail
**ASSERTION FAIL** [z_spin_lock_mem_coherent(l)] @ WEST_TOPDIR/zephyr/include/spinlock.h:131
@ WEST_TOPDIR/zephyr/lib/os/assert.c:45

**Environment (please complete the following information):**
 - OS: Fedora28
 - Toolchain: Zephyr-sdk-0.12.2
 - Commit ID: 3fe33fe3883ffa

**Comment by andyross** [comment]
This particular test is actually working for me, though queue tests seem to show the coherence issue in #32705 more commonly for some reason (queue and lifo_usage are broken for me in my tree right now).  I'm going to close this as a duplicate and track the work there.
