### ISSUE TITLE
Add Xtensa xt-ld linker support to CONFIG_XIP

### ISSUE THREAD

**Issue by hongshui3000** [zephyrproject-rtos/zephyr#32563]
**Describe the bug**
file : linker-tool-gcc.h
```
#ifdef CONFIG_XIP
#define SECTION_DATA_PROLOGUE(name, options, align) \
	name options : ALIGN_WITH_INPUT align
#else
```

If CONFIG_XTENSA & CONFIG_XIP is configured, ALIGN_WITH_INPUT is not supported in XTENSA's xt-ld

Please check again

**Comment by carlescufi** [comment]
@hongshui3000 could you perhaps send a Pull Request for this?

**Comment by andyross** [comment]
What are you trying to do, exactly?  We don't support XIP on any existing xtensa platforms, and XIP as implemented definitely requires binutils-style alignment control.  If you need it for your app maybe there's a hybrid solution where you could build with the Xtensa toolchain and link with binutils?

**Comment by hongshui3000** [comment]
> What are you trying to do, exactly? We don't support XIP on any existing xtensa platforms, and XIP as implemented definitely requires binutils-style alignment control. If you need it for your app maybe there's a hybrid solution where you could build with the Xtensa toolchain and link with binutils?

XIP mode is used in my application. I wrote the ld script myself and found this problem when I wanted to use the SECTION_DATA_PROLOGUE macro definition. So I gave up the SECTION_DATA_PROLOGUE macro when writing the ld script to avoid this problem. As you said, I did use the hybrid solution

**Comment by hongshui3000** [comment]
> @hongshui3000 could you perhaps send a Pull Request for this?

My solution may not have much reference value for zephyr. I just rewrote my own ld script. So I am not going to submit these

**Comment by hongshui3000** [comment]
By the way, there is no big problem with xip on Xtensa, except for linking scripts.

**Comment by andyross** [comment]
So... this isn't really a bug.  I'm going to change it to an enhancement: "Add Xtensa xt-ld linker support to CONFIG_XIP" and assign it to @hongshui3000 in the hope that something gets contributed back. :)

But broadly, I agree.  Our whole linkage framework is sort of a mess and could stand with rework.  This is one glitch of many.

**Comment by hongshui3000** [comment]
file：zephyr\soc\xtensa\intel_adsp\cavs_v15\linker.ld  
```
#define RAMABLE_REGION ram :ram_phdr
#define ROMABLE_REGION ram :ram_phdr ------------------------------->this
#include <linker/common-rom.ld>------------------------------------------>this
```
I feel bad about this way of changing the name to specify the characteristics
This is the beginning of code confusion

**Comment by dcpleung** [comment]
No XIP on Xtensa support. So this is a moot point... closing for now. If needed, please re-open.
