### ISSUE TITLE
lwm2m: Long endpoint names are truncated due to short buffer

### ISSUE THREAD

**Issue by mlasch** [zephyrproject-rtos/zephyr#32566]
**Describe the bug**
When using long endpoint names for the lwm2m client, the `ep=` query in the bootstrap/register URL is truncated. Increasing  `CONFIG_LWM2M_RD_CLIENT_ENDPOINT_NAME_MAX_LENGTH` doesn't help.

**To Reproduce**
1. Set `CONFIG_LWM2M_RD_CLIENT_ENDPOINT_NAME_MAX_LENGTH` to a big number e.g. 100
2. Run the lwm2m_client sample with a long endpoint name (e.g. 80 characters)
3. Build and run the client and observe the packets in wireshark
4. In the bootstrap or registration URL, `ep=abc123xxx` gets truncated

**Expected behavior**
The endpoint name can be as long as configured with `CONFIG_LWM2M_RD_CLIENT_ENDPOINT_NAME_MAX_LENGTH`

**Impact**
Long endpoint names, recommended in the lwm2m 1.0 specification _6.3.1 Endpoint Client Name_, are not possible.

**Additional context**
To serialize the bootstrap/register URL a static 64-byte buffer is used. This silently truncates long strings.
https://github.com/zephyrproject-rtos/zephyr/blob/d8283b63ec6fe9aa1948db163923afc0594a2bde/subsys/net/lib/lwm2m/lwm2m_rd_client.c#L120

Should this buffer be increased to at least `CONFIG_LWM2M_RD_CLIENT_ENDPOINT_NAME_MAX_LENGTH` or something like `MAX(<longest configured query string>)`?

**Comment by rlubos** [comment]
Hi, thanks for reporting. I think your proposal is legit - endpoint query string will be the longest one in most cases so it'll make sense to correlate the `query_buffer` size with this config value. I'll send a PR.
