### ISSUE TITLE
Function z_find_first_thread_to_unpend() missing coverage in sched.c

### ISSUE THREAD

**Issue by yingmingx** [zephyrproject-rtos/zephyr#32691]
**Describe the bug**
Function z_find_first_thread_to_unpend() missing coverage in sched.c. 

**To Reproduce**
1. twister -p qemu_x86 --coverage -T tests/kernel

**Expected behavior**
It's probably dead code that should be removed.

Environment (please complete the following information):

OS: ubuntu1~18.04
Toolchain zephyr-sdk-0.12.1
Commit id 5de3f850a752ec638b695c151d3de8f19503907f

**Comment by andyross** [comment]
Agreed.  This looks to have been orphaned fairly recently; there was a scheduler race fix a while back (that exposed another issue, and begat the big abort rewrite and bug hunt of the past two weeks) that addressed synchronization issues by combining operations in a few spots.  This looks like a "half" of the operation that got combined.

**Comment by yerabolu** [comment]
Working on the changes and will submit a PR soon.
