### ISSUE TITLE
Need openthread merge

### ISSUE THREAD

**Issue by krbvroc1** [zephyrproject-rtos/zephyr#32757]
https://github.com/openthread/openthread/pull/6173

Fixes compile error on arm compilers.

**Comment by rlubos** [comment]
The fixes you mention are already integrated into Zephyr OT fork, it was updated in https://github.com/zephyrproject-rtos/openthread/pull/37.

**Comment by krbvroc1** [comment]
@rlubos My apologies.

**Comment by rlubos** [comment]
> @rlubos My apologies.

No need to, really :)
