### ISSUE TITLE
Sensor BMI160: set of undersampling mode is not working

### ISSUE THREAD

**Issue by vinceWii4** [zephyrproject-rtos/zephyr#32774]
**Problem description**
In low power mode, the accelerometer current consumption is to high. After investigation I discovered that the undersampling mode wasn't corretly set in BMI160_REG_ACC_CONF.

**To Reproduce**
1. Add in prj.conf:
 * CONFIG_BMI160=y
 * CONFIG_BMI160_ACCEL_PMU_LOW_POWER=y
 * CONFIG_BMI160_GYRO_PMU_SUSPEND=y
2. Modify drivers/sensor/bmi160/bmi160.c
```
int bmi160_reg_field_update(struct device *dev, u8_t reg_addr,
			    u8_t pos, u8_t mask, u8_t val)
{
	u8_t old_val, new_val, val;

	if (bmi160_byte_read(dev, reg_addr, &old_val) < 0)
		return -EIO;
	val = (old_val & ~mask) | ((val << pos) & mask);
	if (bmi160_byte_write(dev, reg_addr, &val) < 0)
		return -EIO;
	if (bmi160_byte_read(dev, reg_addr, &new_val) < 0)
		return -EIO;

	if (reg_addr == BMI160_REG_ACC_CONF)
		printk("BMI160_REG_ACC_CONF - old: %d, value to write "
			  "in reg: %d, new val: %d", old_val, val, new_val);

	return 0;
}
```
3. Run a simple program
4. See that new value in BMI160_REG_ACC_CONF has not the expected value

**Expected behavior**
BMI160_REG_ACC_CONF: bit 7 of new_val should be enabled.

**Impact**
High current consumption in accelerometer low power mode

**Solution**
bmi160_pmu_set calls bmi160_reg_field_update() with a wrong *pos* parameter (shift of 128 instead of 7).

```
git diff drivers/sensor/bmi160/bmi160.h
@@ -170,7 +170,8 @@
 #define BMI160_ACC_CONF_ODR_MASK	0xF
 #define BMI160_ACC_CONF_BWP_POS		4
 #define BMI160_ACC_CONF_BWP_MASK	(0x7 << 4)
-#define BMI160_ACC_CONF_US		BIT(7)
+#define BMI160_ACC_CONF_US_POS		7
+#define BMI160_ACC_CONF_US_MASK		BIT(7)

 /* BMI160_REG_GYRO_CONF */
 #define BMI160_GYR_CONF_ODR_POS	0
 ```

```
git diff drivers/sensor/bmi160/bmi160.c
@@ -163,7 +163,7 @@ static int bmi160_pmu_set(struct device *dev, union bmi160_pmu_status *pmu_sts)
 	/* set the undersampling flag for accelerometer */
 	return bmi160_reg_field_update(dev, BMI160_REG_ACC_CONF,
-				       BMI160_ACC_CONF_US, BMI160_ACC_CONF_US,
+				       BMI160_ACC_CONF_US_POS, BMI160_ACC_CONF_US_MASK,
 				       pmu_sts->acc != BMI160_PMU_NORMAL);
 }
```

**Comment by GunZi200** [comment]
@vinceWii4 I created a pull request with the changes you suggested. The fix makes sense to me. 😃
