### ISSUE TITLE
Zephyr C++ support documentation conflicts to the code

### ISSUE THREAD

**Issue by evgeniy-paltsev** [zephyrproject-rtos/zephyr#32885]
Latest Zephyr documentation related to C++ support ([doc/reference/kernel/other/cxx_support.rst](https://github.com/zephyrproject-rtos/zephyr/blob/master/doc/reference/kernel/other/cxx_support.rst)) explicitly mentions that following features are *not* supported:

* Dynamic object management with the **new** and **delete** operators
* RTTI (runtime type information)
* Exceptions

However the commit 26e0f9a9e1267858848cbad0a145b87a4c07b2c6 says that it

* Add support of C++ exceptions
* Add support of C++ RTTI
* Implements new and delete using k_malloc and k_free

which is conflicting to the documentation statements.

Hence the question to C++ experts:
Do we still have some significant flaws in these features implementation so we consider them as *not* supported or we just have outdated documentation?

**Comment by evgeniy-paltsev** [comment]
@nashif, @Benichou34 could you please take a look at this? 
Thanks!

**Comment by nashif** [comment]
@evgeniy-paltsev  yes, docs might be outdated, here is a list of what works and what does not: https://github.com/zephyrproject-rtos/zephyr/issues/31281

**Comment by andygikling** [comment]
Bump, I think the very brief description in cxx_support.rst is misleading people (me).

**Comment by andygikling** [comment]
Never mind I can confirm new is working.  For people who end up looking here, you need to change a few things in your menuconfig:
CONFIG_CPLUSPLUS=y
# Enable 17
CONFIG_STD_CPP17=y
# Newlib 
CONFIG_NEWLIB_LIBC=y
# Standar c++ libraries
CONFIG_LIB_CPLUSPLUS=y
# Support runtime type system
CONFIG_RTTI=y

**Comment by stephanosio** [comment]
not stale

**Comment by stephanosio** [comment]
Related to https://github.com/zephyrproject-rtos/zephyr/issues/43636
