### ISSUE TITLE
Where should a few include/ headers live

### ISSUE THREAD

**Issue by galak** [zephyrproject-rtos/zephyr#32975]
There are a few headers in include/ that seem like they shouldn't be at the top level:

`include/ec_host_cmd.h`
`include/emul.h`
`include/ptp_clock.h`

Should these files still live here are be moved under some sub-dir.

**Comment by galak** [comment]
@jukkar should `ptp_clock.h` be `include/net/ptp_clock.h`?

**Comment by galak** [comment]
@sjg20 should `emul.h` be `include/drivers/emul.h`?

**Comment by galak** [comment]
@sjg20 should `ec_host_cmd.h` be `include/mgmt/ec_host_cmd.h`?

**Comment by jukkar** [comment]
> should `ptp_clock.h` be `include/net/ptp_clock.h`?

I would put that to `include/drivers/` directory

**Comment by sjg20** [comment]
> @sjg20 should `emul.h` be `include/drivers/emul.h`?

Yes that seems fine

**Comment by sjg20** [comment]
> @sjg20 should `ec_host_cmd.h` be `include/mgmt/ec_host_cmd.h`?

Yes OK
