### ISSUE TITLE
West: openocd runner: Don't let debug mode on by default

### ISSUE THREAD

**Issue by erwango** [zephyrproject-rtos/zephyr#32984]
**Describe the bug**
When flashing using openocd runner, the cortex-m processor is left in debug mode. It can, then, only be released after a power-on reset (cold reset).

This conflicts with the use of https://github.com/zephyrproject-rtos/zephyr/pull/31481 (Null pointer exception detection via DWT), and prevent its use by default in tests.

~~For this reason, Null pointer exception detection was disabled by default on all STM32 platforms, but it would be great to be able to re-instantiate it.~~

Note: This potentially affect other runners as well (~~pyocd~~, for instance).

**To Reproduce**
1. Revert https://github.com/zephyrproject-rtos/zephyr/pull/32983
2. Run any zephyr test on a STM32 target using openocd runner for flashing

**Expected behavior**
Don't prevent use of Null pointer exception detection when using openocd runner

**Impact**
Prevent use of Null pointer exception detection when using openocd runner in zephyr tests

**Logs and console output**
If applicable, add console logs or other types of debug information
e.g Wireshark capture or Logic analyzer capture (upload in zip archive).
copy-and-paste text and put a code fence (\`\`\`) before and after, to help
explain the issue. (if unable to obtain text log, add a screenshot)

**Environment (please complete the following information):**
 - OS: (e.g. Linux, MacOS, Windows)
 - Toolchain (e.g Zephyr SDK, ...)
 - Commit SHA or Version used

**Additional context**

**Comment by ioannisg** [comment]
Thanks for the ticket @erwango 
To the best of my knowledge, pyocd, jlink, or nrfjprog are not affected. I've tried with several boards/runners and this seems to be the case.

**Comment by ioannisg** [comment]
Guess the main issue here is that we do not have a consistent west flash, with respect to the state the core is left at, after west flash is done.

**Comment by ioannisg** [comment]
@mbolivar-nordic can you take a look here (or suggest alternative maintainer)?

**Comment by nashif** [comment]
looks like pyocd is also affected

see https://github.com/zephyrproject-rtos/zephyr/issues/32966

**Comment by mbolivar-nordic** [comment]
> @mbolivar-nordic can you take a look here (or suggest alternative maintainer)?

Sorry @ioannisg, I don't know enough about the underlying debug IPs to really help here. I see you already posted a PR for openocd, so it seems like you're on your own here :(.
