### ISSUE TITLE
Support for the Raspberry Pi RP2040 soc

### ISSUE THREAD

**Issue by burumaj** [zephyrproject-rtos/zephyr#33012]
**Is this request related to a missing driver support for a particular hardware platform, SoC or board? Please describe.**
This request is for the support of RP2040 SoC by the Raspberry Pi foundation. This is a dual core
Cortex-M0+ device. The reason I think this would be a great addition to Zephyr is that it is a well documented SoC
with a well documented SDK too.

**Describe why you are asking for this support?**
Describe why you are asking for this support instead of contributing it directly to the tree

The reason I am asking for this support is because I am interested in using Zephyr on this chip.
However, I'm not that experienced with porting socs to zephyr, so i would probably need some guidance or help
taking on this task

Also seeing as Arduino, Adafruit and other distributors are creating boards for this soc.

If this is a new board or SoC, please state whether you are willing to maintain the Zephyr support for it if it is included in the main tree
If this SoC were to be included in the main tree i would be willing to maintain the code for it.

**Additional context**
Add any other context or graphics (drag-and-drop an image) about the hardware here.

**Comment by ioannisg** [comment]
CC @carlescufi

**Comment by de-nordic** [comment]
Same issue here: https://github.com/zephyrproject-rtos/zephyr/issues/32193

**Comment by ioannisg** [comment]
Draft PR started: #33172

**Comment by voxpelli** [comment]
Not very helpful to have a bot close tracking issues like this one :/ Will only result in new ones being created and this adding to the noise rather than the intended opposite.

**Comment by de-nordic** [comment]
There is active interest in the issue.

**Comment by fkromer** [comment]
#37134

**Comment by voxpelli** [comment]
> #37134

The Pico and the Compute Module are very different

**Comment by fkromer** [comment]
@voxpelli Sorry. I wanted to reference another github issue.

**Comment by voxpelli** [comment]
There is active interest in the issue.

(Any way to make the Stale bot ignore an issue?)

**Comment by voxpelli** [comment]
Active interest

**Comment by carlescufi** [comment]
The HAL request is here: #40817
