### ISSUE TITLE
Enabling DHCP without NET_MGMT shouldn't be allowed

### ISSUE THREAD

**Issue by pabigot** [zephyrproject-rtos/zephyr#33137]
> It may be that enabling DHCP without NET_MGMT shouldn't be allowed

Yes, that is the case. After looking the code, the DHCP needs to know about the network interface status in order to trigger a renew when the network interface comes back up. It looks like we are missing proper selects for net mgmt config option in `subsys/net/ip/Kconfig.ipv4` for DHCPv4.

_Originally posted by @jukkar in https://github.com/zephyrproject-rtos/zephyr/issues/33105#issuecomment-792585286_

**Comment by jukkar** [comment]
I can take and fix this.
