### ISSUE TITLE
twister: Add option to load list with quarantined tests

### ISSUE THREAD

**Issue by PerMac** [zephyrproject-rtos/zephyr#33207]
**Is your enhancement proposal related to a problem? Please describe.**
The broken test/item under test can cause multiple failures in the final results. Until the problem is solved these failures will "pollute" the results in daily reporting and burden the execution time due to --retry-failed

**Describe the solution you'd like**
I think we can add an argument like `--quarantine-tests <path_to_quarantine_list>` which will mark the tests in that list to be skipped and get a "quarantine" reason. Each user should be able to easily modify the list.

**Additional context**
 I believe this would be very useful for internal CI on-target test setups, where the checking out is done automatically. Currently, it is inconvenient to modify the execution scope to skip failing tests. E.g the watchdog sample was broken in a way, that blocked the execution of the whole test suite. Applying a local patch changes the git describe version, therefore results with it cannot be accepted for daily on-target reports. I solved it by adding a command that will delete the folder in the test plan, which is rather a nasty solution. Having tests marked as "skipped reason: quarantine" would be easy to track in the final results and a single list with such tests would be easier to maintain

**Comment by nashif** [comment]
good idea, patches welcome.

**Comment by PerMac** [comment]
ok, I will work on this

**Comment by nashif** [comment]
btw, those tests would qualify as the real `skipped`, as opposed to the others which are being filtered.
