### ISSUE TITLE
Incorrect documentation CONFIG_LOG_STRDUP_MAX_STRING

### ISSUE THREAD

**Issue by wldevries** [zephyrproject-rtos/zephyr#33218]
**Describe the bug**
According to documentation `CONFIG_LOG_STRDUP_MAX_STRING` should default to 66 when `CONFIG_BT` is enabled, but it has no effect.

https://docs.zephyrproject.org/latest/reference/kconfig/CONFIG_LOG_STRDUP_MAX_STRING.html

**To Reproduce**
Build a sample with the following minimal `prj.conf`
```
CONFIG_BT=y
CONFIG_LOG=y
```

**Expected behavior**
I expect `CONFIG_LOG_STRDUP_MAX_STRING=66` to appear in `build\zephyr\.config`, but it is at `32` instead.

**Impact**
annoyance

**Logs and console output**
none

**Environment (please complete the following information):**
 - OS: Windows 10
 - Toolchain: `gnuarmemb`
 - Commit SHA or Version used: `ff5b040f782297003040c1dc4fe43521bc8dc052`

**Additional context**
none

**Comment by nordic-krch** [comment]
Documentation is from latest master and your commit not. `66` was introduced in https://github.com/zephyrproject-rtos/zephyr/pull/32370/commits/85754127d3100fe8fcab9dc92769f32b7a193c77.
