### ISSUE TITLE
uart9 missing from <st/h7/stm32h7.dtsi>

### ISSUE THREAD

**Issue by manoj153** [zephyrproject-rtos/zephyr#33233]
Hi, I've been using the dev kit stm32 nucleo_h723zg and noticed one of its uart (UART9) is not supported, Any particular reason?

**Comment by erwango** [comment]
@manoj153 No particular reason aside that it missed to no one until now. Feel free to add it via a pull request.

**Comment by manoj153** [comment]
thanks, I am working on it. Will PR

**Comment by manoj153** [comment]
here in my PR:
https://github.com/zephyrproject-rtos/zephyr/pull/33296/commits/6474d37bc6b61ae7df34345ae0153a566bb10883
