### ISSUE TITLE
Power Management Overhaul 

### ISSUE THREAD

**Issue by nashif** [zephyrproject-rtos/zephyr#33265]
- [x] Runtime device power management overhaul
   - [x] Device dependency integration with power management
   - [x] Address thread concurrency and move away from work queues when calling _get()/_put APIs in device drivers
   - [x] Address device PM during startup and availability of kernel services
   - [x] Document on the API level per peripheral the PM related interfaces and when a device needs to be active or when it can be put into a lower power state.
   - [x] Add samples using hardware for device_pm_get/put APIs
- [x] System Level Power Management
  - [x] Account for wakup times.
  - [x] Add additional wakeup/sleep time data in DTS per state
  - [x] Device power management triggered by system/idle thread
  - [x] Finalize hooks to be implemented by application/SoC.
- [x] Documentation
- [x] Testing

**Comment by nashif** [comment]
see #14307 for some dependencies..

**Comment by ceolin** [comment]
https://github.com/zephyrproject-rtos/zephyr/pull/33942

- Address device PM during startup and availability of kernel services
- Add samples using hardware for device_pm_get/put APIs
- Address thread concurrency and move away from work queues when calling _get()/_put APIs in device drivers (mostly)

**Comment by ceolin** [comment]
https://github.com/zephyrproject-rtos/zephyr/pull/34781

**Comment by nashif** [comment]
closing this
