### ISSUE TITLE
Using AT HOST  fails build

### ISSUE THREAD

**Issue by CiochinaVitalie** [zephyrproject-rtos/zephyr#33356]
**Describe the bug** 
I am working on the project where is involved SIM 800C module and nrf52832, so I  I tried to use AT HOST library
The risult is Build fails.

**To Reproduce**

1. Generate zephyr project by visualGDB
2.  prj.conf file

- CONFIG_HEAP_MEM_POOL_SIZE=2048
- CONFIG_NRF_MODEM_LIB=y
- CONFIG_AT_HOST_LIBRARY=y
- CONFIG_AT_HOST_CMD_MAX_LEN=256
- CONFIG_AT_HOST_THREAD_PRIO=5
- CONFIG_CR_LF_TERMINATION=y

3. Try to build zephyr project
4. Build fails.

**Expected**
Zephyr project builds successfully

**Logs and console output**

1. ERROR This combination of SoC and floating point ABI is not supported by libmodem (C:/nrf_sdk/v1.5.0/nrfxlib/nrf_modem/lib/cortex-m4/hard-float doesn't exist.)
2. Error    'C:/nrf_sdk/v1.5.0/nrfxlib/nrf_modem/lib/cortex-m4/hard-float/libmodem.a', needed by 'zephyr/zephyr_prebuilt.elf',missing and no known rule to make it.

**Environment** 
 - OS: Windows 10
 - Toolchain (visualGDB, sdk-nrf)

**Comment by carlescufi** [comment]
Hi @CiochinaVitalie. This is an nRF Connect SDK question. Please use the [Nordic devzone](https://devzone.nordicsemi.com/) instead.
