### ISSUE TITLE
Properly indicate ISR number in SystemView

### ISSUE THREAD

**Issue by khutchens** [zephyrproject-rtos/zephyr#33363]
**Is your enhancement proposal related to a problem? Please describe.**
When recording traces via SystemView, all ISRs share IRQ number 0, which makes ISR tracing pretty useless.

**Describe the solution you'd like**
SystemView should show the individual ISR as separate traces with the correct IRQ numbers.

This is a pretty easy change since the SystemView tracing backend already provides [`sysview_get_interrupt()`](https://github.com/zephyrproject-rtos/zephyr/blob/b8b8e8cd6b1a697340fb52c7565cc9bff71eed33/subsys/tracing/sysview/sysview.c#L28), which propogates the current interrupt number (not currently set) back to SystemView. All that's needed is a hook in [isr_wrapper.S:158](https://github.com/zephyrproject-rtos/zephyr/blob/b8b8e8cd6b1a697340fb52c7565cc9bff71eed33/arch/arm/core/aarch32/isr_wrapper.S#L158) (and other configurations) to set the current IRQ number during ISR entry.

I'm happy to submit a PR to add this, but I'm not equipped to add or test it for anything other than the `CONFIG_ARMV7_M_ARMV8_M_MAINLINE` configuration, which would be a pretty incomplete addition.

**Comment by nashif** [comment]
This was already addressed in 10ee29e947ba5e3ec19a856b6b9cd63f3d82314f
