### ISSUE TITLE
Remove deprecated items in 2.7

### ISSUE THREAD

**Issue by galak** [zephyrproject-rtos/zephyr#33449]
Here's a list we should update on things deprecated in 2.5 that should be removed in zephyr 2.7

- [x] STM32 pinmux macros
- [x] bt_set_id_addr - include/bluetooth/bluetooth.h
- [x] DEVICE_INIT / DEVICE_AND_API_INIT - include/device.h
- [x] BUILD_ASSERT_MSG - include/toolchain/common.h, include/toolchain/gcc.h
- [x] GET_ARG2 / GET_ARGS_LESS_1 - include/sys/util_macro.h
- [x] CONFIG_FS_LITTLEFS_FC_MEM_POOL - subsys/fs/Kconfig.littlefs 
- [x] CONFIG_PRINTK64 in lib/os/Kconfig
- [x] DT properties (`timer-instance` in `nordic,nrf-sw-pwm`, `has-be32k` in `jedec,jesd216`)

**Comment by nashif** [comment]
>     * CONFIG_MULTITHREADING - kernel/Kconfig (not 100% sure on this one) ???

we need to drop this or fully support it and overhaul the code before 2.6 is released. Actually this should have happened in 2.5, so, this should be done earlier than 2.7

**Comment by nashif** [comment]
https://github.com/zephyrproject-rtos/zephyr/issues/27415#issuecomment-685833663

**Comment by galak** [comment]
> we need to drop this or fully support it and overhaul the code before 2.6 is released. Actually this should have happened in 2.5, so, this should be done earlier than 2.7
> 
> [#27415 (comment)](https://github.com/zephyrproject-rtos/zephyr/issues/27415#issuecomment-685833663)

yeah, wasn't sure what @carlescufi is looking to do in this area for 2.6.

**Comment by carlescufi** [comment]
> > we need to drop this or fully support it and overhaul the code before 2.6 is released. Actually this should have happened in 2.5, so, this should be done earlier than 2.7
> > [#27415 (comment)](https://github.com/zephyrproject-rtos/zephyr/issues/27415#issuecomment-685833663)
> 
> yeah, wasn't sure what @carlescufi is looking to do in this area for 2.6.

I am looking into this for the 2.6 timeline.

**Comment by galak** [comment]
```
arch/arm/include/aarch32/cortex_r/exc.h:#ifndef CONFIG_COMPAT_INCLUDES
arch/arm/include/aarch32/cortex_r/stack.h:#ifndef CONFIG_COMPAT_INCLUDES
arch/arm/include/cortex_m/cmse.h:#ifndef CONFIG_COMPAT_INCLUDES
arch/arm/include/cortex_m/exc.h:#ifndef CONFIG_COMPAT_INCLUDES
arch/arm/include/cortex_m/stack.h:#ifndef CONFIG_COMPAT_INCLUDES
arch/arm/include/cortex_m/tz.h:#ifndef CONFIG_COMPAT_INCLUDES
arch/arm/include/cortex_r/exc.h:#ifndef CONFIG_COMPAT_INCLUDES
arch/arm/include/cortex_r/stack.h:#ifndef CONFIG_COMPAT_INCLUDES
include/arch/arm/aarch32/cortex_r/cmsis.h:#ifndef CONFIG_COMPAT_INCLUDES
include/arch/arm/aarch32/cortex_r/cpu.h:#ifndef CONFIG_COMPAT_INCLUDES
include/arch/arm/aarch32/cortex_r/sys_io.h:#ifndef CONFIG_COMPAT_INCLUDES
```

**Comment by galak** [comment]
https://github.com/zephyrproject-rtos/zephyr/pull/36134

**Comment by galak** [comment]
@de-nordic can you possibly look at the cleanup/removal of deprecated code in the littlefs code?

**Comment by de-nordic** [comment]
> 
> 
> @de-nordic can you possibly look at the cleanup/removal of deprecated code in the littlefs code?

Here: https://github.com/zephyrproject-rtos/zephyr/pull/36285

**Comment by cfriedt** [comment]
@galak - looks as though this one is done - are there any other deprecated items to remove?

**Comment by mniestroj** [comment]
Deprecated DT properties: #36862 #36863
