### ISSUE TITLE
Need to add device node for UART10 in dts/arm/st/h7/stm32h723.dtsi

### ISSUE THREAD

**Issue by Kshitij4kk** [zephyrproject-rtos/zephyr#33475]
My organization is using stm32h723zg MCU for prototyping. 
We wanted to add USART10 device node in the stm32h723.dtsi.

Following snip is from stm32h723 data sheet which shows USART10 in the block diagram.
![image](https://user-images.githubusercontent.com/36400253/111652689-4952c880-882d-11eb-932e-e887b01c7a12.png)

**Comment by Kshitij4kk** [comment]
@erwango @manoj153

**Comment by erwango** [comment]
@Kshitij4kk Feel free to push a PR to add it. We're welcoming contributions!

**Comment by FRASTM** [comment]
@Kshitij4kk thanks to provide this change, do not hesitate to push and add a board config, if needed.
