### ISSUE TITLE
west: Question on `west flash --hex-file` behavior with build.dir-fmt

### ISSUE THREAD

**Issue by erwango** [zephyrproject-rtos/zephyr#33498]
**Describe the bug**
Cf related dicussion [here](https://github.com/zephyrproject-rtos/zephyr/pull/31118/files#r596729811)

**To Reproduce**
0. Configure dir-fmt as follows 
[build]
dir-fmt = build/{board}/
1. cd samples/tfm_integration/tfm_ipc
2. west build -b stm32l562e_dk_ns
3. west flash --hex-file build/stm32l562e_dk_ns/tfm_merged.hex
Reported error:
```
FATAL ERROR: --build-dir was not given, /local/mcu/zephyrproject/zephyr/samples/tfm_integration/tfm_ipc is not a build directory and the default build directory cannot be determined. Check your build.dir-fmt configuration option
```

The equivalent procedure works well w/o dir-fmt configuration

**Expected behavior**
`west flash --hex-file` has same behavior whatever dir-fmt configuration.

**Impact**
Annoying

**Comment by mbolivar-nordic** [comment]
I don't think this is a bug. West should not guess which build directory you are using IMO.

You can try using [build.guess-dir](https://docs.zephyrproject.org/latest/guides/west/build-flash-debug.html#configuration-options) which will work in some situations if the build directory can be guessed unambiguously. But it's not clear that we can just start at the hex file location and assume it's in a build directory, I think.

**Comment by erwango** [comment]
@mbolivar-nordic My request is not to ask west to guess the location in current case (at least this is not my understanding):
Observation is that the following works:
```
$ west flash --hex-file build/tfm_merged.hex
```
But the following reports an error, while the file location is given in the same way
```
$ west flash --hex-file build/stm32l562e_dk_ns/tfm_merged.hex
FATAL ERROR: --build-dir was not given, /local/mcu/zephyrproject/zephyr/samples/tfm_integration/tfm_ipc is not a build directory and the default build directory cannot be determined. Check your build.dir-fmt configuration option
```

**Comment by mbolivar-nordic** [comment]
The first example looks like `build.dir-fmt` is not set, and therefore the default build directory `build` can be checked and used if it exists.

The second example seems to be using `build.dir-fmt`, so there is no single default location. It could be `build/my-board` or `build/my-other-board`. West has to guess in this case.

**Comment by erwango** [comment]
Ok, I had a try using `west flash -d build/nucleo_l552ze_q_ns/ --hex-file build/nucleo_l552ze_q_ns/tfm_merged.hex `.
This works indeed. Thanks for the support.

**Comment by mbolivar-nordic** [comment]
> I had a try using `west flash -d build/nucleo_l552ze_q_ns/ --hex-file build/nucleo_l552ze_q_ns/tfm_merged.hex `.
> This works indeed.

I know that's kind of pain to specify twice but I don't see a good way to avoid it.
