### ISSUE TITLE
images for the wiki

### ISSUE THREAD

**Issue by nashif** [zephyrproject-rtos/zephyr#335]
Use this issue to add images that can be linked from the wiki. There is no way to upload images to the wiki right now.

**Comment by nashif** [comment]
![development_model 2](https://cloud.githubusercontent.com/assets/180017/26566703/55380d24-44c3-11e7-9f5f-2058e8274f89.png)

**Comment by dbkinder** [comment]
This option wasn't availble because the issue tab wasn't enabled previously. Indeed uploadng an image to the issue (drag and drop) is one oe the "cheats" for getting an url for uploading images to the wiki, but the image upload file won't be part of the wiki git repo (it's part of the issue).

**Comment by nashif** [comment]
and that is fully ok, the link will still be available in the git history, having the file in the wiki git is not critical. We will still have the history of the image changes in git.

**Comment by mjlinkme** [comment]
![zephyr schedule milestones](https://user-images.githubusercontent.com/8398699/26997469-dbc0073e-4d2e-11e7-9aec-2c81e4bec584.jpg)

**Comment by mjlinkme** [comment]
![x and x 1 release timeline](https://user-images.githubusercontent.com/8398699/26997967-2f7da832-4d33-11e7-81c5-885516cdcf76.jpg)

**Comment by dbkinder** [comment]
![lts](https://user-images.githubusercontent.com/11063618/29428109-dc2a2e8c-8340-11e7-8f2c-5ddaedc64cd0.png)
![flow4](https://user-images.githubusercontent.com/11063618/29428111-dfa76d9a-8340-11e7-9287-6ffc1c440bf2.png)
![flow3](https://user-images.githubusercontent.com/11063618/29428113-e206a614-8340-11e7-8154-877f1bcddb28.png)
![flow2](https://user-images.githubusercontent.com/11063618/29428114-e40024fe-8340-11e7-898b-f6e5060192c0.png)
![flow](https://user-images.githubusercontent.com/11063618/29428115-e55edf34-8340-11e7-9207-b8b807b504f1.png)

**Comment by linkmeyer** [comment]
[More Schedule Details.pdf](https://github.com/zephyrproject-rtos/zephyr/files/1561049/More.Schedule.Details.pdf)

**Comment by dbkinder** [comment]
Issue needs to remain open for us to upload images for the wiki

**Comment by dbkinder** [comment]
![issuetoapproval](https://user-images.githubusercontent.com/11063618/35293433-823ee33a-0028-11e8-898c-6ea5a9e03cc9.png)
![githubproposalcycle](https://user-images.githubusercontent.com/11063618/35293746-81eea4c8-0029-11e8-9b09-c2e50ba98643.png)

**Comment by MaureenHelm** [comment]
Is this issue still needed? Why not commit the images to the wiki git?

**Comment by dbkinder** [comment]
We created this so folks without merge permission could upload images here, and then reference them in the wiki.  We can close this.

**Comment by nashif** [comment]
![reel_board_flyer_back_draft](https://user-images.githubusercontent.com/180017/44124451-42e6196a-9ffb-11e8-9f82-28544a29770e.png)
![reel_board_flyer_front_draft](https://user-images.githubusercontent.com/180017/44124452-42f99bca-9ffb-11e8-8d14-30f72000e947.png)

**Comment by nashif** [comment]
![image2018-10-29_20-12-26](https://user-images.githubusercontent.com/180017/55962232-79a38c80-5c3e-11e9-909a-b80e273b9ebd.png)

**Comment by nashif** [comment]
![image2018-10-29_20-13-37](https://user-images.githubusercontent.com/180017/55962263-87f1a880-5c3e-11e9-94c6-710a6611b3bc.png)

**Comment by dbkinder** [comment]
![Screen Shot 2019-04-30 at 8 56 10 AM](https://user-images.githubusercontent.com/11063618/58356908-b6fa5d00-7e2d-11e9-9275-e5e826d4ce32.png)
![Screen Shot 2019-04-30 at 8 52 08 AM](https://user-images.githubusercontent.com/11063618/58356928-c7aad300-7e2d-11e9-832f-55b88b6a3949.png)

**Comment by dbkinder** [comment]
added some images to the wiki, so can close this issue again.
