### ISSUE TITLE
Update module civetweb (bug fixes and increased stack size requirement)

### ISSUE THREAD

**Issue by gudnimg** [zephyrproject-rtos/zephyr#33520]
## Proposal

The current revision in `west.yml` refers to commit https://github.com/zephyrproject-rtos/civetweb/commit/e6903b80c09d17cd1a8bb32e40080005558aad29
https://github.com/zephyrproject-rtos/zephyr/blob/f9a0e20432818308bead889fece60869337a32cb/west.yml#L41

As I understand it, Zephyr is directly using this repo: https://github.com/zephyrproject-rtos/civetweb

I was trying to help with an issue related to Civetweb https://github.com/zephyrproject-rtos/zephyr/issues/33516 and noticed the Zephyr version pulled by West is out of date. One commit of interest: https://github.com/zephyrproject-rtos/civetweb/commit/356545184e861ae84f89a024dcf695bd021de9cd  

The stack size increases a lot and may rule out some boards.

----

## Example:

When compiling sample `samples/net/civetweb/http_server` the stack size increases by **24576 bytes**. For a Nucleo F429ZI board this represents an increase of 12.5%. 

Command: `west build samples/net/civetweb/http_server -b nucleo_f429zi`

```
Memory region         Used Size  Region Size  %age Used
           FLASH:      121408 B         2 MB      5.79%
             CCM:          0 GB        64 KB      0.00%
            SRAM:       95199 B       192 KB     48.42%
        IDT_LIST:          0 GB         2 KB      0.00%
```

After https://github.com/zephyrproject-rtos/civetweb/commit/356545184e861ae84f89a024dcf695bd021de9cd:
```
Memory region         Used Size  Region Size  %age Used
           FLASH:      123392 B         2 MB      5.88%
             CCM:          0 GB        64 KB      0.00%
            SRAM:      119775 B       192 KB     60.92%
        IDT_LIST:          0 GB         2 KB      0.00%
```

Release notes: https://github.com/civetweb/civetweb/blob/master/RELEASE_NOTES.md

----
## How to update Zephyr's Civetweb?
To update the revision I found these steps:

1. Copy the commit number from https://github.com/zephyrproject-rtos/civetweb you want to use as HEAD
2. Paste it in line https://github.com/zephyrproject-rtos/zephyr/blob/f9a0e20432818308bead889fece60869337a32cb/west.yml#L41
3. Call `west update` to update Civetweb locally.

**Comment by gmarull** [comment]
civetweb is no longer part of Zephyr, closing
