### ISSUE TITLE
pin setting error on frdm_kl25z boards

### ISSUE THREAD

**Issue by hakehuang** [zephyrproject-rtos/zephyr#33559]
**Describe the bug**
uart port has no output, bisect found the issue is related to commit fbfd75e19ab7dce9c0fd38c1b215dd1b2512734e

**To Reproduce**
1. mkdir build; cd build
2. cmake -DBOARD=frdm_kl25z ..
3. make flash
4. uart port has no output

**Expected behavior**
output
hello world

**Impact**
frdm_kl25z

**Logs and console output**

**Environment (please complete the following information):**
 - OS: (e.g. Linux)
 - Toolchain (e.g Zephyr SDK, ...)
 - Commit SHA or Version used: 911ba334a06ac55e28856e49a694083974196f8c

**Comment by hakehuang** [comment]
@MaureenHelm  @galak seems the need add more dts fixes

```
DEVICE_DT_GET(DT_NODELABEL(porta));
__ASSERT_NO_MSG(device_is_ready(porta));
```

**Comment by MaureenHelm** [comment]
@dleach02 or @galak can you take a look? I don't have this board at the moment

**Comment by galak** [comment]
> @dleach02 or @galak can you take a look? I don't have this board at the moment

I looked at the code and nothing obvious.  @dleach02 do you have this board?

**Comment by dleach02** [comment]
I have this board

**Comment by dleach02** [comment]
bisect information was pointing to the wrong sha. I've updated the sha in the description above.

The problem appears to be a different value is ending up in the clkdiv1. Previously this was hard coded to 0x10010000 and now with the integration of device tree stuff it is set to 0x90000000

**Comment by dleach02** [comment]
I have a fix and will get the PR in soon
