### ISSUE TITLE
 <err> esp_event: SYSTEM_EVENT_STA_DISCONNECTED for wifi sample for esp32 board

### ISSUE THREAD

**Issue by houssine97** [zephyrproject-rtos/zephyr#33572]
**Describe the bug**
When running the wifi_station sample on ESP32 , it reports that : 

iface 0x3ffb0140 is down
[00:06:29.873,000] <err> esp_event: SYSTEM_EVENT_STA_DISCONNECTED

**To Reproduce**

cd zephyr/samples/boards/esp32/wifi_station
west build -b esp32
west flash
See error
Expected behavior
get ESP32 wifi running

**Comment by sylvioalves** [comment]
@houssine97, let me ask you a few things:
1) did you set proper wifi SSID and PASS on the `prj.con` or in the application code?
2) Was it connected before and it suddenly disconnected/iface down?

**Comment by houssine97** [comment]
thank you i did not set wifi ssid and pass when i did that it worked .

**Comment by sylvioalves** [comment]
Great. let me know if you have any issues. Closing this.
