### ISSUE TITLE
ARC: add ARCv3 HS6x support

### ISSUE THREAD

**Issue by evgeniy-paltsev** [zephyrproject-rtos/zephyr#33610]
This is an issue to track progress on ARCv3 HS6x upstraming.

TODO:
- [x] [Add ARCv3 HS6x GNU toolchain to Zephyr SDK](https://github.com/zephyrproject-rtos/sdk-ng/pull/327)
- [x] [ARC Kconfig refactor](https://github.com/zephyrproject-rtos/zephyr/pull/33518)
- [x] [Upstream ARC-specific ARCv3 HS6x part; add nsim_hs6x, qemu_arc_ns6x boards](https://github.com/zephyrproject-rtos/zephyr/pull/34393)
- [x] [Update ARC support status page ](https://github.com/zephyrproject-rtos/zephyr/pull/35404)

Related issues / PR:
#33518 #30996, https://github.com/zephyrproject-rtos/sdk-ng/issues/324

**Comment by abrodkin** [comment]
SDK with ARC64 support is being discussed here: https://github.com/zephyrproject-rtos/sdk-ng/pull/327

**Comment by evgeniy-paltsev** [comment]
Everything that was planned is merged now, so close this issue.
