### ISSUE TITLE
tests: subsys: logging:  Tests from /tests/subsys/logging/log_backend_fs fail on nrf52840dk

### ISSUE THREAD

**Issue by PerMac** [zephyrproject-rtos/zephyr#33629]
**Describe the bug**
A test case test_log_fs_files_max from  /tests/subsys/logging/log_backend_fs fails on nrf52840dk, causing two scenarios to fail:
subsys.logging.log_backend_fs.manualmounted.nrf5840dk and subsys.logging.log_backend_fs.automounted

**To Reproduce**
1. have nrf52840dk connected
2. go to your zephyr dir
3. call `/scripts/twister -T tests/subsys/logging/log_backend_fs -p nrf52840dk_nrf52840 --device-testing --device-serial /dev/ttyACM0 -v --inline-logs`

**Expected behavior**
Tests pass.

**Impact**
Not clear

**Logs and console output**
```
START - test_log_fs_files_max
Assertion failed at WEST_TOPDIR/zephyr/tests/subsys/logging/log_backend_fs/src/log_fs_test.c:227: test_log_fs_files_max: (test_mask not equal to 0b11110)
Unexpected file numeration
FAIL - test_log_fs_files_max in 3.407 seconds
```

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04
 - ToolchainZephyr SDK 0.12.2
 - Commit SHA or Version used: zephyr-v2.5.0-1463-gc59cf6008b60

**Comment by nvlsianpu** [comment]
@PerMac Thanks for reporting. Will investigate.
