### ISSUE TITLE
Random MAC after RESET - NRF52832

### ISSUE THREAD

**Issue by tcpipchip** [zephyrproject-rtos/zephyr#33645]
**Describe the bug**
I implemented a Beacon using NRF52832 to broadcast the BME680 data!
All the time that i reset the NRF52832, a different MAC is detected my  BLE SCANNER.

**To Reproduce**
Reseting the ZEPHYR, the BLE SCANNER detects different MAC.
**Expected behavior**
Allways the Same MAC

**Impact**
I had to use the CHIP ID to identify my ZEPHYR module and broadcast it!

log

⸮Scanning...
Advertised Device: Name: , Address: 53:82:42:2c:76:80, manufacturer data: 060001092002c26e567ce60e5aa77c136ea14dd8b4c1c0c631b49fe438 
**Advertised Device: Name: , Address: 2b:76:14:04:16:2a, manufacturer data: 59000000001f000000650000003d000052b264000000b34fc9f8** 
Devices found: 2
Scan done!

After reset, changed the MAC :(

Advertised Device: Name: , Address: 53:82:42:2c:76:80, manufacturer data: 060001092002c26e567ce60e5aa77c136ea14dd8b4c1c0c631b49fe438 
Advertised Device: Name: , Address: 60:3a:7e:4e:b4:9d, manufacturer data: 4c0010051a1c369185, txPower: 12 
**Advertised Device: Name: , Address: 20:33:77:f2:bf:26, manufacturer data: 59000000000000000000000000000000000064000000b34fc9f8** 

Thanks!

**Comment by joerchan** [comment]
@tcpipchip It looks like you have privacy disabled `CONFIG_BT_PRIVACY=n` and have a non-connectable advertiser.
In this case the advertiser will use a new NRPA address each time it starts to advertise. If this behavior is not wanted you can use
BT_LE_ADV_OPT_USE_IDENTITY to advertise with the identity address.

**Comment by tcpipchip** [comment]
@joerchan 
Thanks for the feedback!

I have other question
sprintf(g_localName,"%s%x","INDRIYA-G-",NRF_FICR->DEVICEADDR[0]); 

/* Set Scan Response data */
	static struct bt_data sd[] = {
	BT_DATA(BT_DATA_NAME_COMPLETE, g_localName, 17),
	};

Why sometimes advertsing the INDRIYA-G-XXXXXX and sometimes not adverstising the INDRIYA-G-XXXXXX ?

Thanks again!

**Comment by joerchan** [comment]
@tcpipchip Not much information to go on there, are you sure it isn't just the difference in the advertising PDU? You have put the name in the scan-response, so you won't see it in the ADV_IND pdu.

**Comment by tcpipchip** [comment]
@joerchan 
I want to broadcast the localname....
What do you suggest

**Comment by joerchan** [comment]
Putting the localname in the scan-response achieves that, but the scanner needs to be an active one.
The other option is to put it in the advertising data (ADV_IND).

**Comment by tcpipchip** [comment]
i had choosen the second option! It[s working
Have you a little example showing the scan-response example

**Comment by joerchan** [comment]
https://docs.zephyrproject.org/2.5.0/reference/bluetooth/gap.html?highlight=adv_start#c.bt_le_adv_start
if you put it as `ad` in will be in the advertising data `ADV_IND`, if you put is `sd` it will be in the scan response data `SCAN_RSP`.

**Comment by tcpipchip** [comment]
Yes, i did that

Maybe is the BLE SCANNER (ARDUINO) ESP32 example bug :(

**Comment by joerchan** [comment]
Maybe, can you verify with your phone that the name shows up? You can use the  nRF Connect app

**Comment by tcpipchip** [comment]
they show!

But, is using ESP32 as ble scan :(

**Comment by joerchan** [comment]
Closing as original question and follow-up question has been answered.
