### ISSUE TITLE
Add support for board: Nucleo-L412RB-P

### ISSUE THREAD

**Issue by GunZi200** [zephyrproject-rtos/zephyr#33655]
I bought this board to try out the L4 series and noticed L412RB is not supported: https://docs.zephyrproject.org/latest/boards/index.html

I'm thinking about adding this support to Zephyr myself as a challenge/exercise.

* https://www.digikey.com/en/products/detail/stmicroelectronics/NUCLEO-L412RB-P/9656230

-----
Self notes:

* Board porting guide: https://docs.zephyrproject.org/latest/guides/porting/board_porting.html

### SoC Support
1. - [x] Define STM32L412RB  in device tree. (PR: https://github.com/zephyrproject-rtos/zephyr/pull/33660)
2. - [x] The SoC is not fully supported. I need to add something similar for `STM32L412RB` as is done for `STM32L32`: https://docs.zephyrproject.org/latest/reference/kconfig/CONFIG_SOC_STM32L432XX.html#cmdoption-arg-CONFIG_SOC_STM32L432XX

----

### Creating files for the board

1. - [x] Write devicetree file: `boards/arm/nucleo_l412rb/nucleo_l412rb.dts` https://docs.zephyrproject.org/latest/guides/porting/board_porting.html#write-your-devicetree
      - - [x] User LED
      - - [x] User buttons
      - - [ ] Add 32.768kHz RTC clock 
2. - [x] Write Kconfig files
3. - [x] Build, test, and fix
    * `west build -b nucleo_l412rb samples/hello_world`
    * `west flash`
4. - [x] Update documentation

----

### Test samples

- [x] Hello World
- [x] Blinky
- [ ] Blinky PWM (compiles and flashes -- but PWM does not work)
- [x] Button
- [ ] Fade LED (compiles and flashes -- but PWM does not work)
- [ ] Threads
- [x] Counter

----
Other commits as examples:
* Commit where support for SoC STM32F410XX was added c99ae8d
* Commit where support for Nucleo L432KC was added: https://github.com/zephyrproject-rtos/zephyr/commit/6256c997034b6188e0dc908d64d73a90b780766e

**Comment by GunZi200** [comment]
I've got the hello world sample working 😃 
![image](https://user-images.githubusercontent.com/8218499/112381427-76e2ba80-8ce2-11eb-8af6-e38d8a3c73f6.png)

**Comment by GunZi200** [comment]
@erwango I've hit a wall with PWM. Seems this board's User LED uses a "**Complementary PWM**" output.. 

  * Pin is PB13
  * TIM1_CH1N.

From what I gather from Googling is that this is an advanced feature which must be activated specifically.

Is this type of PWM not supported in Zephyr? I can't find any specific information that says to treat it differently. Though maybe I'm not looking in the right places.


This is what my board's device tree looks like at the moment. I see no LED action. The examples "Blinky PWM" and "Fade LED" show no errors when I run them on the board.

Any ideas? Should I perhaps skip PWM for initial support?

```c
#include <st/l4/stm32l412rbtx-pinctrl.dtsi>
#include <st/l4/stm32l412XB.dtsi>

/ {
	model = "STMicroelectronics STM32L412RB-NUCLEO board";
	compatible = "st,stm32l412rb-nucleo";

	chosen {
		zephyr,console = &usart2;
		zephyr,shell-uart = &usart2;
		zephyr,sram = &sram0;
		zephyr,flash = &flash0;
	};

	leds {
		compatible = "gpio-leds";
		green_led: led_0 {
			gpios = <&gpiob 13 GPIO_ACTIVE_HIGH>;
			label = "User LD3";
		};
	};

	pwmleds {
		compatible = "pwm-leds";
		green_pwm_led: green_pwm_led {
			pwms = <&pwm2 1 0 PWM_POLARITY_INVERTED>;
		};
	};

	aliases {
		led0 = &green_led;
		pwm-led0 = &green_pwm_led;
	};
};

&timers1 {
	status = "okay";

	pwm2: pwm {
		status = "okay";
		pinctrl-0 = <&tim1_ch1n_pb13>;
	};
};
```

**Comment by erwango** [comment]
@GunZi200 

When looking to ref manual for this board [UM1956.pdf](https://www.st.com/resource/en/user_manual/dm00231744-stm32-nucleo32-boards-mb1180-stmicroelectronics.pdf), user LED is indicated as PB3, and I see you're setting it as PB13. Can you cross check ?
This would mean using `timer2s` and `tim2_ch2_pb3`.

**Comment by GunZi200** [comment]
> @GunZi200
> 
> When looking to ref manual for this board [UM1956.pdf](https://www.st.com/resource/en/user_manual/dm00231744-stm32-nucleo32-boards-mb1180-stmicroelectronics.pdf), user LED is indicated as PB3, and I see you're setting it as PB13. Can you cross check ?
> This would mean using `timer2s` and `tim2_ch2_pb3`.

No I'm sure it is PB13 since the Blinky example (without PWM) works. [UM2206.pdf](https://github.com/zephyrproject-rtos/zephyr/files/6212037/dm00387966-stm32-nucleo64p-boards-mb1319-stmicroelectronics.pdf) I also looked at the schematic drawing to confirm this.

![image](https://user-images.githubusercontent.com/8218499/112637932-9b4fab80-8e36-11eb-9915-f29fb4fdad22.png)

**Comment by erwango** [comment]
> No I'm sure it is PB13 since the Blinky example (without PWM) works. UM2206.pdf I also looked at the schematic drawing to confirm this.

Right, mixed with nucleo_l412**k**b which is a nucleo-32. So let me check and come back to you.
