### ISSUE TITLE
Question: How is NUM_IRQS determined for example for STM32F401xC

### ISSUE THREAD

**Issue by GunZi200** [zephyrproject-rtos/zephyr#33658]
Example: https://github.com/zephyrproject-rtos/zephyr/blob/75a74bfad2b1f8fa100914314c8a59c9418416a9/soc/arm/st_stm32/stm32f4/Kconfig.defconfig.stm32f401xc#L12

I'm confused how `NUM_IRQS = 85` is determined?

Looking at the datasheet for STM32F401RC: [stm32f401rc.pdf](https://github.com/zephyrproject-rtos/zephyr/files/6196532/stm32f401rc.pdf)
![image](https://user-images.githubusercontent.com/8218499/112299826-1aef4600-8c90-11eb-9e24-2fed34069a8e.png)

Wouldn't this mean that the number of interrupts available are `NUM_IRQS` = 62 + 16 = 78? What am I missing? 🤔

**Comment by erwango** [comment]
@GunZi200 `NUM_IRQS = 85` is indeed not accurate, but we applied a simple rule of thumb which is to set NUM_IRQ to highest IRQ number (84 for stm32f401xc) +1. This was defined long time ago and the rule is questionnable.

Though, I think the real solution would be to get this info from dts extracted information, to set the numbed dynamically depending on the number of IRQ actually enabled in the binary so we can have a irq vector table tuned to the current binary configuration and save some bytes.
With existing dts parsing tools, I don't think there is anything that prevents us to enable this, aside from missing spare time.

**Comment by GunZi200** [comment]
@erwango I see that all stm32f401xc have 78 interrupts. How do you get 84?

It is my understanding that we count the 62 maskable interrupt channels + the 16 lines of the Cortex M4 with FPU

**Comment by erwango** [comment]
@GunZi200, as I mentioned, highest IRQ number + 1:
For f401.
`  SPI4_IRQn                   = 84      /*!< SPI4 global Interrupt                                              */`

And as I said, I know the rule is questionable.

**Comment by GunZi200** [comment]
Ok, where is the definition defined? I cannot find it anywhere. Is this part of some autogenerated code? I'm wondering about this because I need to determine this number for STM32L412RB but I'm not sure where to look for it to be sure I have the correct number.

**Comment by erwango** [comment]
F401:
https://github.com/zephyrproject-rtos/hal_stm32/blob/master/stm32cube/stm32f4xx/soc/stm32f401xc.h
L412:
https://github.com/zephyrproject-rtos/hal_stm32/blob/master/stm32cube/stm32l4xx/soc/stm32l412xx.h

**Comment by GunZi200** [comment]
Thank you for the patience @erwango closing the issue...
