### ISSUE TITLE
dts:dt-bindings No OCTOSPIM dt-bindings available for stm32h723

### ISSUE THREAD

**Issue by Kshitij4kk** [zephyrproject-rtos/zephyr#33697]
In my project, I wanted to connect a storage device to OCTOSPIM Port1 in stm32h723 MCU on Nucleo 144 board.

I am facing issue while writing the device tree because I can't find any dt-bindings for OCTOSPIM peripheral.
I needed help on how to write the device nodes for OCTOSPIM and OCTOSPI1.

@KwonTae-young @galak

**Comment by galak** [comment]
Adding @erwango as the STM32 maintainer.

**Comment by erwango** [comment]
@Kshitij4kk Sorry but octospi driver is not available yet for stm32 (and we have currently no plans unfortunately)

**Comment by Kshitij4kk** [comment]
Understood @erwango. Thanks for your comment.
