### ISSUE TITLE
cmake -E env: unknown option '-Wno-unique_unit_address_if_enabled'

### ISSUE THREAD

**Issue by nandojve** [zephyrproject-rtos/zephyr#33693]
**Describe the bug**
The #31960 introduced the **pre_dt_board.cmake** file in many boards. The new rules add _EXTRA_DTC_FLAGS "-Wno-unique_unit_address_if_enabled"_ to build system. This rules if not proper defined will break _make menuconfig_.

**To Reproduce**
1. cd samples/hello_world
2. west build -b atsamr21_xpro
3. west build -t menuconfig

**Expected behavior**
**west build -t menuconfig** should never be broken by any change in Zephyr configuration.

**Impact**
It is not possible configure Zephyr without rollback.

**Logs and console output**
```
-- west build: running target menuconfig
...
cmake -E env: unknown option '-Wno-unique_unit_address_if_enabled'
...
```

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain Zephyr SDK sdk-0.12.3
 - Commit #mainline

**Additional context**
It is expected a test that can check broken Kconfig options

**Comment by chrta** [comment]
Is this fixed with https://github.com/zephyrproject-rtos/zephyr/pull/32753 ?

**Comment by tejlmand** [comment]
> Is this fixed with #32753 ?

I believe so.

**Comment by nandojve** [comment]
> > Is this fixed with #32753 ?
> 
> I believe so.

Works For Me!

**Comment by chrta** [comment]
With the merge, this issue is now fixed and can be closed. I verified this with the current master and "Steps to reproduce"

**Comment by galak** [comment]
Closing this, @nandojve feel free to re-open if there is still an issue.
