### ISSUE TITLE
`west attach` silently downgrades to `debugserver` for openocd runner

### ISSUE THREAD

**Issue by areusch** [zephyrproject-rtos/zephyr#33745]
**Describe the bug**
What have you tried to diagnose or workaround this issue?

Ran `west attach` with nucleo_f746zg, expected GDB to appear. Instead, terminal hangs because it's running gdbserver only.

**To Reproduce**
1. build a project which uses openocd runner
2. run `west flash` to program the device.
2. run `west attach` to attach to the device.

**Expected behavior**
`west attach` should launch GDB server and GDB.

**Impact**
What impact does this issue have on your progress (e.g., annoyance, showstopper)
annoyance

**Logs and console output**
If applicable, add console logs or other types of debug information
e.g Wireshark capture or Logic analyzer capture (upload in zip archive).
copy-and-paste text and put a code fence (\`\`\`) before and after, to help
explain the issue. (if unable to obtain text log, add a screenshot)

```
...
make[1]: Leaving directory '/Users/andrew/ws/tvm4/tests/micro/zephyr/test_zephyr-stm32f746xx-workspace/2021-03-26T17-37-04/build/runtime'
-- west attach: using runner openocd
Open On-Chip Debugger 0.10.0+dev-01341-g580d06d9d-dirty (2020-05-16-15:41)
Licensed under GNU GPL v2
For bug reports, read
	http://openocd.org/doc/doxygen/bugs.html
Info : The selected transport took over low-level target control. The results might differ compared to plain JTAG/SWD
Info : clock speed 2000 kHz
Info : STLINK V2J29M18 (API v2) VID:PID 0483:374B
Info : Target voltage: 3.247431
Warn : Silicon bug: single stepping may enter pending exception handler!
Info : stm32f7x.cpu: hardware has 8 breakpoints, 4 watchpoints
Info : Listening on port 3333 for gdb connections
    TargetName         Type       Endian TapName            State
--  ------------------ ---------- ------ ------------------ ------------
 0* stm32f7x.cpu       hla_target little stm32f7x.cpu       halted

Info : Unable to match requested speed 2000 kHz, using 1800 kHz
Info : Unable to match requested speed 2000 kHz, using 1800 kHz
target halted due to debug-request, current mode: Thread
xPSR: 0x01000000 pc: 0x08001f78 msp: 0x20029258
Info : Listening on port 6333 for tcl connections
Info : Listening on port 4444 for telnet connections

```

**Environment (please complete the following information):**
 - OS: (e.g. Linux, MacOS, Windows)
 - Toolchain (e.g Zephyr SDK, ...)
 - Commit SHA or Version used
https://app.vagrantup.com/tlcpack/boxes/microtvm-zephyr/versions/0.0.4

Ubuntu 18.04, Zephyr 2.4.0 (problem code seems to still exist at HEAD)

**Additional context**

Offending code: https://github.com/zephyrproject-rtos/zephyr/blob/master/scripts/west_commands/runners/openocd.py#L131

In general I don't think blanket-else should be interpreted to mean launch debugserver.

**Comment by mbolivar-nordic** [comment]
Fixed in  #35419
