### ISSUE TITLE
Regular loss of a few connection intervals

### ISSUE THREAD

**Issue by BOZHENG001** [zephyrproject-rtos/zephyr#33765]
**Describe the bug**
When I use an nRF sniffer (nRF52840 DK) to sniff a BLE connection built between another two nRF52840 DKs (`central_hr` and `peripheral_hr`), I can always see a regular loss of some connection intervals. For example, after the event counter reached 1009, it directly goes up to 1012, and the delta time shows as 35839us (my connection interval is 12.5ms). In the beginning, I thought it should be some loss due to the sniffer serial port to my laptop, but after that, I tried to print the event `counter` variable from the `channel selection algorithm #2` in file `lll_chan.c`, and I did see the `counter` also shows the regular connection interval loss (in my case after every four connection intervals, there are around four connection intervals lost). I am wondering if there is something wrong with my settings because the loss is so regular?

**To Reproduce**
1. printk `counter` in the `channel selection algorithm #2`
2. flash `central_hr` and `peripheral_hr` to two nRF52840 DKs
4. See the issue from a serial port

**Expected behavior**
I expect the results from the "printk `counter`" should be continuous, instead of some regular connection interval loss.

**Impact**
It does confuse me also stops my work here because I don't know if I made it wrong or something else.

**Logs and console output**
A screenshot of the results of the "printk `counter`" from my Linux is provided below. Please have a check.
![image](https://user-images.githubusercontent.com/50182201/112809055-e9a0bc80-9079-11eb-9b09-065663589fed.png)

**Environment (please complete the following information):**
 - OS: Linux Mint
 - Toolchain (Zephyr RTOS version 2.4.99)

**Comment by cvinayak** [comment]
Modifying the lower link layer and adding printk and if on UART will break the hard real time requirements of connection events. Depending on UART baud rate, connection events during the UART transmission will be delayed and skipped.

If your issue is with modified lower link layer, please close this issue.
