### ISSUE TITLE
Continuous Integration check patch false warnings

### ISSUE THREAD

**Issue by bbolen** [zephyrproject-rtos/zephyr#33890]
When submitting a pull request that moves code without making any other changes, the compliance checker flags errors that the current author did not create.  For example, if the code that the committer is moving contains a typdef, the compliance checker flags an error that a new typedef is being added.

An example of such error is:
https://github.com/zephyrproject-rtos/zephyr/pull/28231/checks?check_run_id=2184913426
The offending commit is only moving, not adding, the code that the compliance checker flags.

It would be nice to be able to mark the test as a false positive so that the pull request doesn't appear as failed.

This is a very low priority annoyance.

**Comment by nashif** [comment]
you can already do that by commenting in the PR, just comment that the checks are unrelated, and someone would be able to override.
