### ISSUE TITLE
Device tree: STM32L4 defines can1 node for chips which do not support CAN peripheral

### ISSUE THREAD

**Issue by GunZi200** [zephyrproject-rtos/zephyr#33896]
The device tree includes CAN node `can1` for all STM32L4 chips when in fact they don't all support it.

This affects STM32L412xx and STM32L422xx. They're the only ones I see which do not support CAN bus.

`dts/arm/st/stm32l4.dtsi` should be changed and the `can1` node should be moved so that it is not included into chips which do not support CAN bus.

### Fix Described:
This can be fixed by moving `can1` from `dts/arm/st/stm32l4.dtsi` to the following files:

* `dts/arm/st/stm32l4r5.dtsi`
* `dts/arm/st/stm32l432.dtsi`
* `dts/arm/st/stm32l452.dtsi`
* `dts/arm/st/stm32l471.dtsi`

**Comment by erwango** [comment]
@GunZi200 Thanks for reporting. Don't hesitate to push the changes if you have some time.
