### ISSUE TITLE
tests: kernel: fpu: Several tests related to fpu fail on nrf5340dk_nrf5340_cpuappns

### ISSUE THREAD

**Issue by PerMac** [zephyrproject-rtos/zephyr#33956]
**Describe the bug**
Several tests related to fpu fail on nrf5340dk_nrf5340_cpuappns. The following test scenarios fail to build:

- benchmark.kernel.application.fp.arm from zephyr/tests/benchmarks/app_kernel/
- driver.sensor.fpu from zephyr/tests/drivers/sensor/generic
- kernel.common.stack_protection_arm_fpu_sharing from zephyr/tests/kernel/fatal/exception
- kernel.fpu_sharing.kernel.fpu_sharing.float_disable.arm and kernel.fpu_sharing.kernel.fpu_sharing.generic.arm from zephyr/tests/kernel/fpu_sharing

**To Reproduce**
1. have nrf5340dk connected
2. run `scripts/twister -p nrf5340dk_nrf5340_cpuappns -T <path from the above>
3. see error

**Expected behavior**
Tests pass

**Impact**
Not clear

**Logs and console output**
Not sure which parts are relevant. The output is very extensive. 

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04
 - Toolchain zephyr sdk 0.12.2
 - Commit SHA or Version used zephyr-v2.5.0-1831-g58a0ba6dbb28

**Comment by oyvindronningstad** [comment]
Turns out TFM doesn't support -mfloat-abi=hard. Fixing this is not trivial so it probably won't be done in the foreseeable future. We could set up a relationship between BUILD_WITH_TFM and FP_HARDABI though. @ioannisg @frkv thoughts?
