### ISSUE TITLE
TCP connection does not support keepalive function

### ISSUE THREAD

**Issue by maweicoltsmart** [zephyrproject-rtos/zephyr#34044]
The keepalive function in tcp is very important. When will Zephyr OS support this function?

**Comment by maweicoltsmart** [comment]
If the lwip protocol stack is transplanted, the network function of zephyr os will be more powerful.

**Comment by jukkar** [comment]
Indeed, the keepalive messages are currently not there. I cannot really say when they would be implemented. If you want that feature urgently, one option is to send a PR that fixes the issue. As always patches are welcome.

**Comment by ycsin** [comment]
> If the lwip protocol stack is transplanted, the network function of zephyr os will be more powerful.

May I ask why is that more powerful?

**Comment by jukkar** [comment]
I just wonder why #46716 was abandoned as it was quite near for merging. It is rather pointless to have keepalive support patches out-of-tree. @RBartonMesh would you be able to re-submit the patches with the fixes?

**Comment by jukkar** [comment]
ping @RBartonMesh / @maweicoltsmart if possible, please review / try #66316
