### ISSUE TITLE
Unrecognized characters generated during document construction

### ISSUE THREAD

**Issue by hongshui3000** [zephyrproject-rtos/zephyr#34076]
**Describe the bug**
file:zephyr\doc\_build\rst\doc\reference\devicetree\bindings.rst
```
W眉rth Elektronik GmbH. (we)
===========================

.. rst-class:: rst-columns

- :ref:`dtbinding_we_wsen_itds`

.. _dt_vendor_xlnx:
```
file:zephyr/dts/bindings/vendor-prefixes.txt
```
Würth Elektronik GmbH
```
Open this file in my system, the text is correct(utf-8)
The intermediate file generated by the build is incorrect，It seems that utf-8 is not used, generating

**Environment (please complete the following information):**
 -  Windows(Chinese)

**Comment by hongshui3000** [comment]
Similarly, I can’t write Chinese characters in it, and I will report an error directly.
zephyr/dts/bindings/vendor-prefixes.txt
LOG:
```
FAILED: CMakeFiles/devicetree
cmd.exe /C "cd /D E:\work\zephyr\doc && "C:\Program Files\CMake\bin\cmake.exe" -E env PYTHONPATH=E:/work/zephyr/scripts/dts/python-devicetree/src; ZEPHYR_BASE=E:/work/ZC3827/ZCAN-IOT/zephyr GEN_DEVICETREE_REST_ZEPHYR_DOCSET= C:/Python39/python.exe E:/work/ZC3827/ZCAN-IOT/zephyr/doc/_scripts/gen_devicetree_rest.py --vendor-prefixes E:/work/ZC3827/ZCAN-IOT/zephyr/dts/bindings/vendor-prefixes.txt --dts-root E:/work/ZC3827/ZCAN-IOT/zephyr E:/work/ZC3827/ZCAN-IOT/zephyr/doc/_build/rst/doc/reference/devicetree"
ninja: build stopped: subcommand failed.
```

**Comment by mbolivar-nordic** [comment]
That's weird. The issue doesn't reproduce on Linux. At first I thought it was just a missing PYTHONIOENCODING environment variable setting, but I see that doc/CMakeLists.txt includes cmake/python.cmake, which sets PYTHONIOENCODING to "utf-8" on Windows.

@gmarull any idea?

**Comment by mbolivar-nordic** [comment]
@hongshui3000 could you please apply this patch and retest, to see if the change to vendor-prefixes.txt is working?

```patch
diff --git a/doc/CMakeLists.txt b/doc/CMakeLists.txt
index 3cc9928381..562ad52098 100644
--- a/doc/CMakeLists.txt
+++ b/doc/CMakeLists.txt
@@ -111,6 +111,7 @@ configure_file(${DOXYFILE_IN} ${DOXYFILE_OUT} @ONLY)
 set(EXTRACT_CONTENT_COMMAND
   ${CMAKE_COMMAND} -E env
   ZEPHYR_BASE=${ZEPHYR_BASE}
+  PYTHONIOENCODING=utf-8
   ${PYTHON_EXECUTABLE} _scripts/extract_content.py
   # Ignore any files in the output directory.
   --ignore ${CMAKE_CURRENT_BINARY_DIR}
```

**Comment by gmarull** [comment]
We may need to explicitly open file with encoding, ie `open("file", "r", encoding="utf-8")`. I faced similar encoding problems on Windows and solved them this way (see https://github.com/nrfconnect/sdk-nrf/pull/4449/files#diff-87607595cbd4c2220ec7e0a03979db859c93fc90c6e060b326f406afd08ebb45R68)

**Comment by mbolivar-nordic** [comment]
> It looks like there is an `-X utf8` we can use instead:
> 
> [](https://docs.python.org/3/library/locale.html#locale.getpreferredencoding)

@hongshui3000 could you please test with this patch, which uses that option: https://github.com/zephyrproject-rtos/zephyr/pull/35234

**Comment by hongshui3000** [comment]
> > It looks like there is an `-X utf8` we can use instead:
> 
> @hongshui3000 could you please test with this patch, which uses that option: #35234

**Comment by hongshui3000** [comment]
> > It looks like there is an `-X utf8` we can use instead:
> 
> @hongshui3000 could you please test with this patch, which uses that option: #35234

![image](https://user-images.githubusercontent.com/25566498/118086807-1b39d100-b3f7-11eb-98bf-d8e4decba3fd.png)
it works

**Comment by mbolivar-nordic** [comment]
Thank you very much for testing!

**Comment by mbolivar-nordic** [comment]
I've removed my assignment since I've posted a fix that @gmarull rejected. Will leave it up to him to decide on a proper fix.
