### ISSUE TITLE
Convert CAN to new kwork API

### ISSUE THREAD

**Issue by galak** [zephyrproject-rtos/zephyr#34095]
Convert  subsys/canbus/canopen/CO_driver.c &  subsys/canbus/isotp/isotp.c to use new kwork API.

See the following issue for details:

#33104

**Comment by galak** [comment]
@alexanderwachter / @henrikbrixandersen any updates here?

**Comment by alexanderwachter** [comment]
Isn't this change included in the mass conversion?

**Comment by galak** [comment]
> Isn't this change included in the mass conversion?

The mass conversion is just an example, we have no intents to convert it.  Each subsystem / driver maintainer needs to review it and determine if those changes actually make sense and send a PR.
