### ISSUE TITLE
Convert drivers/console/uart_mux.c to new kwork API

### ISSUE THREAD

**Issue by galak** [zephyrproject-rtos/zephyr#34103]
Convert drivers/console/uart_mux.c to use new kwork API.

See the following issue for details:

#33104

**Comment by jukkar** [comment]
Hmm, I can take this as it is tied to gsm_mux that I already converted in the same directory.

**Comment by galak** [comment]
> Hmm, I can take this as it is tied to gsm_mux that I already converted in the same directory.

thanks.
