### ISSUE TITLE
Convert tests/kernel/workq to new kwork API

### ISSUE THREAD

**Issue by galak** [zephyrproject-rtos/zephyr#34105]
Convert tests/kernel/workq/critical/src/main.c & tests/kernel/workq/work_queue/src/main.c to use new kwork API.

See the following issue for details:

#33104

**Comment by pabigot** [comment]
Two choices for the maintainer:
* (Recommended) Once all other in-tree uses are converted merge #32888 to deprecate the old API.  That PR includes a solution that retains the tests of the deprecated API without causing CI failures.  #34112 should be merged when the deprecated API is removed in a future release.
* (Not Recommended) Merge #34112 immediately, opening the possibility that the behavior of the deprecated API will be broken before the API is removed.
