### ISSUE TITLE
mec15xxevb_assy6853: tests/kernel/mutex/sys_mutex/

### ISSUE THREAD

**Issue by yerabolu** [zephyrproject-rtos/zephyr#34116]
**Describe the bug**
test_mutex_multithread_competition in tests/kernel/mutex/sys_mutex/ failed

This test is also failing on Up squared x86 and Nordic Reel board

**To Reproduce**
1.  twister --hardware-map ~/mec1.file --device-testing -s tests/kernel/mutex/sys_mutex/test_mutex_multithread_competition/
2. See error

**Expected behavior**
Test should pass

**Logs and console output**
```
*** Booting Zephyr OS build zephyr-v2.5.0-2011-gecac194448da  ***
Running test suite mutex_complex
===================================================================
START - test_mutex
START - Test kernel Mutex API
===================================================================
Done LOCKING!  Current priority = 5
*** Booting Zephyr OS build zephyr-v2.5.0-2011-gecac194448da  ***
Running test suite mutex_complex
===================================================================
START - test_mutex
START - Test kernel Mutex API
===================================================================
Done LOCKING!  Current priority = 5
Testing recursive locking
Recursive locking tests successful
PASS - test_mutex in 7.519 seconds
===================================================================
START - test_user_access
SKIP - test_user_access in 0.1 seconds
===================================================================
START - test_supervisor_access
PASS - test_supervisor_access in 0.1 seconds
===================================================================
START - test_mutex_multithread_competition
Assertion failed at WEST_TOPDIR/zephyr/tests/kernel/mutex/sys_mutex/src/thread_competition.c:119: test_mutex_multithread_competition: (flag == LOW_PRO is false)
The low priority thread failed to take the mutex.
FAIL - test_mutex_multithread_competition in 0.75 seconds
===================================================================
Test suite mutex_complex failed.
===================================================================
PROJECT EXECUTION FAILED 
```

**Environment (please complete the following information):**
 - OS: Fedora 
 - Toolchain: zephyr-sdk-0.12.3
 - Commit ID: ecac194448da

**Comment by nashif** [comment]
This is a new test that was introduced recently in 7e91223ae0e, please verify if the issue is in the test as the first thing.

**Comment by PerMac** [comment]
I see failures in the same place on all Nordic boards we deliver results for, Ubuntu 20.04, zephyr-sdk 0.12.2
Hovewer, I see `The highest priority thread failed to take the mutex.` on most of them

**Comment by Zhaoningx** [comment]
Hi, yes, there are some platforms failed to run this case, I'm working on it now. And this case's PR is : https://github.com/zephyrproject-rtos/zephyr/pull/33492 , and I designed this case based on the zephyr doc:
![image](https://user-images.githubusercontent.com/62736294/113995357-c3083000-9888-11eb-8933-b28edbe2de2b.png)

**Comment by KangJianX** [comment]
Same behavior can be reproduce on ADSP.
