### ISSUE TITLE
Convert NXP kinetis boards to have pindata in devicetree

### ISSUE THREAD

**Issue by galak** [zephyrproject-rtos/zephyr#34145]
- [x] frdm_k22f
- [x] frdm_k64f
- [x] frdm_k82f
- [x] frdm_kl25z
- [x] frdm_kw41z: need to understand what's going on w/ TPM/PWM
- [x] hexiwear_k64
- [x] hexiwear_kw40z: requires had coded pin dts file
- [x] ip_k66f: 
- [x] twr_ke18f (#34200)
- [x] twr_kv58f220m
- [x] usb_kw24d512: Need to figure out how to handle internal signals connected to modem

**Comment by Kludentwo** [comment]
regarding frdm_kw41z: In the pinmux.c file it says kPORT_MuxAlt4 but in the dts file it says < 0 5 >. Is it muxed wrong?

**Comment by galak** [comment]
@Kludentwo take a look at https://github.com/zephyrproject-rtos/zephyr/pull/34146

**Comment by henrikbrixandersen** [comment]
@galak I had a look at the usb_kw24d512. I am not sure what you mean by "Need to figure out how to handle internal signals connected to modem"?

**Comment by galak** [comment]
@henrikbrixandersen so I believe if you look at the manual for the SoC.  There is this section:

4.3 Internal Functional Interconnects and System Reset

The pins define there relate to how we setup SPI1 in boards/arm/usb_kw24d512/pinmux.c.  However those pins don't show up in the DTS pinmux data file as I dont believe they are in the xml data files from NXP.

So thus my comment on how to handle them.
