### ISSUE TITLE
Invalid link in Zephyr document to ACRN page

### ISSUE THREAD

**Issue by NanlinXie** [zephyrproject-rtos/zephyr#34149]
There's one invalid link in document page for "Getting started guide for Intel NUC "
https://docs.zephyrproject.org/latest/boards/x86/acrn/doc/index.html#on-the-acrn-sos

The latest ACRN GSG guide link should be:
https://projectacrn.github.io/latest/getting-started/rt_industry_ubuntu.html

**Comment by galak** [comment]
@NanlinXie can you submit a PR to fix this?

**Comment by jenmwms** [comment]
> @NanlinXie can you submit a PR to fix this?

This was quick to fix, I hope that helps @NanlinXie . Thanks for providing the corrected link in the bug report!
