### ISSUE TITLE
samples: telnet: Tab completion not working in telnet shell

### ISSUE THREAD

**Issue by madscientist159** [zephyrproject-rtos/zephyr#34197]
**Describe the bug**
When connecting via telnet to the system shell, tab completion does not function.  Tab completion works fine on the standard UART shell.

**To Reproduce**
Build the telnet sample application, and attempt to interact with the console using tab completion.  Note that no commands are completed, and the tab is echoed locally with no effect.

**Expected behavior**
Commands should be auto-completed when tab is pressed.

**Impact**
Annoyance

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: host
 - GIT head

**Additional context**
The root of the problem is that Zephyr's telnet server doesn't understand raw mode.  All connections stay in line buffered mode, and if the telnet client is manually switched to raw character mode (`^]mode char`) no keypresses are registered by Zephyer except `\n` and `\r`.

**Comment by rlubos** [comment]
I've submitted a fix in https://github.com/zephyrproject-rtos/zephyr/pull/34284, @madscientist159 please have a look.
