### ISSUE TITLE
BBC micro:bit v1.5 LSM303AGR-ACCEL 

### ISSUE THREAD

**Issue by Liviu112** [zephyrproject-rtos/zephyr#34225]
**Describe the bug**
Hi, I was trying to use the lis2dh example code in combination with BBC micro:bit v1.5 . 
The code compiles without issues and can be flashed, when the board is reseted the following message is received: 

![image](https://user-images.githubusercontent.com/38521446/114413033-89e00080-9ba5-11eb-9560-9968db042a5f.png)

**What have you tried to diagnose or workaround this issue?**
I have found that, in the definition of the board, the status is set to disable for some reason: 
![image](https://user-images.githubusercontent.com/38521446/114413278-c01d8000-9ba5-11eb-94f9-0a95524585ca.png)
(zephyr/boards/arm/bbc_microbit/bbc_microbit.dts)

In order to get the lis2dh to work, it is required to change the status to "okay". After reflashing the lis2dh example the terminal showed the following: 
![image](https://user-images.githubusercontent.com/38521446/114414316-9d3f9b80-9ba6-11eb-8726-d883e5c6dacf.png)

***Fix:*** 
Change line 81 and 89 to : ```status = "okay";``` in file ``` zephyr/boards/arm/bbc_microbit/bbc_microbit.dts```

**To Reproduce**
1.  ```west build -p auto -b bbc_microbit samples/sensor/lis2dh```
2. ``` west flash```
3. See error

**Impact**
Inability to use the LSM303AGR-ACCEL sensor.

**Environment:**
OS: Linux 20.04
Toolchain: Zephyr version: 2.5.0

**Comment by FRASTM** [comment]
LSM303AGR sensor (MAGN part) is mentioned in the issue https://github.com/zephyrproject-rtos/zephyr/issues/34196

**Comment by Liviu112** [comment]
That does not yet explain why is disabled in bbc_microbit.dts file :)

**Comment by jfischer-no** [comment]
> That does not yet explain why is disabled in bbc_microbit.dts file :)

Because it is for [v1.5 variant of bbc:microbit](https://github.com/zephyrproject-rtos/zephyr/blob/master/boards/arm/bbc_microbit/bbc_microbit.dts#L78), the "default" variant v1.3 has MMA8653FC enabled.
"_See https://tech.microbit.org/hardware/i2c/ for board variants_ "
This is all in the dts file you screenshotted instead of just posting a link to the line.

**Comment by Liviu112** [comment]
It didn't was clear to me at the start what was the problem. Now looking back that makes sense, also you do not have to feel offended I tried just to help.
