### ISSUE TITLE
Unable to find detailed documentation on pinmux driver development

### ISSUE THREAD

**Issue by Berte-Yu** [zephyrproject-rtos/zephyr#34262]
I‘m porting zephyr to a new soc(cortex-m3), 

When developing the pinmux driver, the detailed documentation cannot be found..

**Comment by mnkp** [comment]
The existing pinmux driver is going to be deprecated. I think the best option for now when adding a new SoC to Zephyr is to keep pinmux driver private to the soc. I.e. place it in `soc/<arch>/<family>/` and do not provide the public pinmux driver. You can take Atmel SAM family as an example. The pinmux driver is located in `soc/arm/atmel_sam/common/soc_gpio.c`. It's used by all Atmel SAM drivers but there is no Atmel SAM pinmux driver in drirvers/pinmux/.

**Comment by Berte-Yu** [comment]
Thanks,  I have ported the pinmax driver。
