### ISSUE TITLE
Add USB to LPCXpresso55S69 board 

### ISSUE THREAD

**Issue by thanhduongvs** [zephyrproject-rtos/zephyr#34280]
How to adding usb hid to device tree?

**Comment by jfischer-no** [comment]
There is no USB device controller support for LPCXpresso55S69 in Zephyr.
It is not necessary to add "usb hid" to any tree.

**Comment by thanhduongvs** [comment]
thanks @jfischer-no

**Comment by jfischer-no** [comment]
I found old PR regarding device controller support for lpc55s69, see https://github.com/zephyrproject-rtos/zephyr/pull/19014
