### ISSUE TITLE
unable to connect to azure iot hub via mqtt protocol

### ISSUE THREAD

**Issue by moncef-bibani** [zephyrproject-rtos/zephyr#34309]
**Describe the bug**
I am trying to connect the nucleo-f429zi using the wifi shield esp-01 to my azure-iot-hub. The samples project is here: https://docs.zephyrproject.org/latest/samples/net/cloud/mqtt_azure/README.html
i created an iot-hub and i added a device. The sample project requires these parameters:

- Username: {iothubhostname}/{device_id}/?api-version=2018-06-30
- Device ID
- SaS token.
- IoT-hub-hostname

I set up these parameters in the menuconfig of the project, except the azure cloud server address and port.

**To Reproduce**
1. cd zephyrproject/zephyr
2. west build -b nucleo_f429zi samples/net/cloud/mqtt_azure -- -DCONF="prj.conf" -DSHIELD=esp_8299
3. west build -t menuconfig
4. west build
5. west flash

**Impact**
the sample project cannot connect to the iot-hub. I guess because i didn´t set up correctly the SAS-token. please see the logs in the picture below. in which format is the SAS token for mqtt protocol ?

**Logs and console output**
![azure-error-wifi](https://user-images.githubusercontent.com/82579384/114896926-0b879680-9e11-11eb-93b0-4b1c9ec42aa1.png)

**Environment (please complete the following information):**
 - OS: Linux Ubuntu
 - Toolchain Zephyr SDK

**Comment by jukkar** [comment]
The -116 errno is ETIMEDOUT, so the connection cannot be established. Difficult to know what is going on, there are lot of moving parts involved when setting the Azure configuration parameters etc. I do not have Azure credentials to try this.

**Comment by jukkar** [comment]
BTW, the current timeout (from your screenshot) seems to be 3 sec. Could you try to increase it as I remember seeing some complaints that the cloud connection establishment can take a long time.

**Comment by moncef-bibani** [comment]
i tried again with esp-01. i could connect the nucleo to my wifi. But this time, i get another error. see picture below:
![azure-error-wifi](https://user-images.githubusercontent.com/82579384/114897449-89e43880-9e11-11eb-902a-d4c2032a26c4.png)

**Comment by moncef-bibani** [comment]
> The -116 errno is ETIMEDOUT, so the connection cannot be established. Difficult to know what is going on, there are lot of moving parts involved when setting the Azure configuration parameters etc. I do not have Azure credentials to try this.

i skiped the field for the ip-address because it is not mandatory for this sample. But i got another error. thank you for your Response.
