### ISSUE TITLE
Configuration HAS_DTS has no function, preventing compile for vendors without device tree

### ISSUE THREAD

**Issue by mtpr-ot** [zephyrproject-rtos/zephyr#34416]
DTS has been made mandatory, however certain vendors do not want to go down that road.
Where an empty device tree in certain configurations is sufficient, in others, the number of hacks needed to compile is unreasonable.

**Expected behavior**
It should be possible to use- and unset the existing CONFIG_HAS_DTS to compile zephyr on vendor platforms.

**Impact**
Currently a local hack is used to compile without DTS. This can quickly be made into a PR if accepted (the "if/endif" added to CMakeLists.txt):

```
if(CONFIG_HAS_DTS)
  # dev_handles.c is generated from ${ZEPHYR_PREBUILT_EXECUTABLE} by
  # gen_handles.py
  add_custom_command(
    OUTPUT dev_handles.c
    COMMAND
    ${PYTHON_EXECUTABLE}
    ${ZEPHYR_BASE}/scripts/gen_handles.py
    --output-source dev_handles.c
    --kernel $<TARGET_FILE:${ZEPHYR_PREBUILT_EXECUTABLE}>
    --zephyr-base ${ZEPHYR_BASE}
    DEPENDS ${ZEPHYR_PREBUILT_EXECUTABLE}
    )
  set_property(GLOBAL APPEND PROPERTY GENERATED_KERNEL_SOURCE_FILES dev_handles.c)
endif()
```

**Comment by galak** [comment]
Can you post this as a PR.  Thanks.
