### ISSUE TITLE
significant build time increase with new logging subsystem

### ISSUE THREAD

**Issue by galak** [zephyrproject-rtos/zephyr#34419]
We are seeing large increases in CI times associated with the new logging subsystem:

Comparing https://buildkite.com/zephyr/zephyr-daily/builds/304#_ [before logging changes merged] to https://buildkite.com/zephyr/zephyr-daily/builds/305#_.

We can take a random build like 6/400 and see an increase from 33m41s to 42m28s.

Looking at git commits this seems to be between 67fade04a0cf (before logging) and f1bb20f6b43b (logger builds)

Looking at micro level if we take a test like samples/net/vlan and build file subsys/net/ip/tcp2.c.  We see a huge increase in C-preprocessor time (on my system going from 0.12s to 2.8s).  [This file was picked since it showed such a large increase]

**Comment by carlescufi** [comment]
The increase is visible also when building locally.

**Comment by nashif** [comment]
@nordic-krch  do we have an idea what is going on?

**Comment by nordic-krch** [comment]
currently, both versions are compiled since `IS_ENABLED` compile-time switch is used also logging v2 is more extensively using preprocess (analyzing each argument and determining its type and size). Tomorrow i will be looking into speeding things up.

**Comment by nordic-krch** [comment]
I've added another (final?) speed up to logging. Seems that there are also other factors in build time increase.

I've been testing with:
```
 ccache -C; time scripts/twister -p frdm_k64f -b -c -s tests/kernel/common/kernel.common
```
And getting following results:

Before | After | Without logging v2 | v2.5.0
------------ | ------------- | ------------ | ------------
35.17s | 32,6 | 29.6 | 23.25

It means that something else contributed to the build time increase from v2.5.0.

**Comment by galak** [comment]
How are you "disabling" logging v2?

**Comment by nordic-krch** [comment]
by deleting content of this if statement:
https://github.com/zephyrproject-rtos/zephyr/blob/db4359cfd2492cf658f18cf0cd49736d7a6788b6/include/logging/log_core.h#L312
