### ISSUE TITLE
Add Requirements repository with infrastructure and placeholder requirements

### ISSUE THREAD

**Issue by laurenmurphyx64** [zephyrproject-rtos/zephyr#34473]
Initialize a GitHub repository for requirements with placeholder requirements and put in applicable infrastructure.

**Comment by carlescufi** [comment]
@laurenmurphyx64 what exactly do you mean by this? There is a Docker image and a Getting Started Guide, so I am unsure what specifically you are referring to.

**Comment by laurenmurphyx64** [comment]
> @laurenmurphyx64 what exactly do you mean by this? There is a Docker image and a Getting Started Guide, so I am unsure what specifically you are referring to.

@carlescufi Sorry, maybe documentation isn't the best tag to put it under. A [separate requirements catalog repository](https://github.com/zephyrproject/reqmgmt) is part of our safety collateral for functional safety certification. @AmberHibberd asked for a card for 2.6 so I made one.

**Comment by nashif** [comment]
> @laurenmurphyx64 what exactly do you mean by this? There is a Docker image and a Getting Started Guide, so I am unsure what specifically you are referring to.

discussed with @carlescufi , this is unrelated to python requirements file.

**Comment by nashif** [comment]
repo created.
