### ISSUE TITLE
west sign regression when HEX file not exists

### ISSUE THREAD

**Issue by nandojve** [zephyrproject-rtos/zephyr#34534]
**Describe the bug**
`west sign`, as command says, should sign zephyr output files for MCUboot, for instance. When using minimal parameters west will try sign both hex and bin files. The `west sign` is failing on current zephyr mainline for projects that create only a bin file. This is the case of `frdm-k64f` board.

**To Reproduce**
1. `west build -b frdm_k64f -d build/app zephyr/samples/subsys/mgmt/updatehub`
2. `west sign -t imgtool -d build/app -- --version 1.0.0 --pad --key bootloader/mcuboot/root-rsa-2048.pem`
3. See error

FATAL ERROR: no unsigned .hex found at /home/gfbudke/zephyros/mainline/build/app/zephyr/zephyr.hex

**Expected behavior**
`west sign` should skip to sign when target file not exists. if no targets, a graceful exit is expected.

**Impact**
annoyance

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain Zephyr SDK 0.12.3
 - Commit SHA 3eb05e5456

**Additional context**
`west sign --no-hex` can be used as workaround.

```
west sign --no-hex -t imgtool -d build/app -- --version 1.0.0 --pad --key bootloader/mcuboot/root-rsa-2048.pem
=== image configuration:
partition offset: 131072 (0x20000)
partition size: 393216 (0x60000)
rom start offset: 512 (0x200)
=== signing binaries
unsigned bin: /home/gfbudke/zephyros/mainline/build/app/zephyr/zephyr.bin
signed bin:   /home/gfbudke/zephyros/mainline/build/app/zephyr/zephyr.signed.bin
```

This was discovered at #34442

**Comment by mbolivar-nordic** [comment]
This was fixed in 250b2133ee7e8c4ea8caecedda49ec9f37a5c9ae, with a follow-up fix for a spurious warning in 2de6bf91d5db9460255d035ba3ab073595bed3a0.
