### ISSUE TITLE
net: lib: sockets: Unable to select() file descriptors with number >= 32

### ISSUE THREAD

**Issue by chyu313** [zephyrproject-rtos/zephyr#34563]
**Describe the bug**
zsock_select() cannot poll file descriptors if all the file descriptors in readfds or writefds are all greater than or equal to 32.

**To Reproduce**
1. Create 32 threads to accept 32 TCP connections, each thread handles one TCP connection. Some of the file descriptor returned by zsock_accept() are >= 32.
2. In each thread, use zsock_select() to poll read event for the file descriptor. If the file descriptor >= 32, it never becomes ready for reading even there is data received.

**Solution**
In zsock_select(), when there is no any bit set in the first 32 bits of readfds, we should still add 32 to fd_no before iterating to next bitset, so I add `fd_no += 32;`  as following (code in red color):

![image](https://user-images.githubusercontent.com/56861030/116045419-9d5e9180-a6a4-11eb-8e46-a069de5c26c7.png)

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: Zephyr SDK
 - Commit: abb94b1198ec6ce618f61dff367275f96cad4eca

**Comment by jukkar** [comment]
@chyu313 could you send a PR for this?
