### ISSUE TITLE
Bluetooth: L2CAP: Deadlock when there are no free buffers while transmitting on multiple channels

### ISSUE THREAD

**Issue by KatrineNordic** [zephyrproject-rtos/zephyr#34600]
**Describe the bug**
Transmitting many large SDUs as quickly as possible on multiple L2CAP channels quickly fills a lot of buffers. When no more segments can be queued to be transmitted because there are no more free buffers, or there are no more credits for the channel, queuing of segments is stopped. Whenever a previously queued segment has been transmitted, or more credits are received, segments are again being queued for transmission. If there are still no free buffers, queuing of segments is stopped again right away. If this happens when all segments that have previously been queued on the channel have already been transmitted, and there are no more credits to receive, queuing of segments is stopped indefinitely. 

**Expected behavior**
Queuing of segments continues when there are free buffers available.

**Impact**
Annoyance.

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain (e.g Zephyr SDK, ...)
 - https://github.com/nrfconnect/sdk-zephyr/commit/6a1d340b632ec62f5abfb2e0c3e54838bbfd086e

**Additional context**
It is possible to work around this by having a high enough number of buffers (CONFIG_BT_L2CAP_TX_BUF_COUNT or CONFIG_BT_CONN_TX_MAX) that there are always buffers available when queuing of segments is restarted.

**Comment by carlescufi** [comment]
@KatrineNordic which Nordic (upstream, not NCS/sdk-zephyr) revision did you test this with?

**Comment by carlescufi** [comment]
> @KatrineNordic which Nordic (upstream, not NCS/sdk-zephyr) revision did you test this with?

This seems to be an issue upstream, as per a discussion with @KatrineNordic and @joerchan

**Comment by carlescufi** [comment]
Downgrading to low since:

- This is only an issue when using  multiple L2CAP Connection-Oriented Channels (a rare use case in practice)
- There is a workaround (increase `CONFIG_BT_L2CAP_TX_BUF_COUNT`)

**Comment by carlescufi** [comment]
@Vudentz FYI, in case you have additional comments to this.

**Comment by carlescufi** [comment]
> @Vudentz FYI, in case you have additional comments to this.

@Vudentz ping on this one, would be good to get your input.

**Comment by alwa-nordic** [comment]
@KatrineNordic, it sounds like you've already done some digging here to find the cause. Do you have any suspicions on where in the code the bug is? Where does this queuing happen?

**Comment by cvinayak** [comment]
@alwa-nordic is following up on possible solutions.

**Comment by jori-nordic** [comment]
Working on it, managed to reproduce -a- deadlock (not sure if it's that specific one yet, but does look like it) on https://github.com/jori-nordic/zephyr/tree/l2cap-deadlock
