### ISSUE TITLE
STM32 SAI peripheral shim

### ISSUE THREAD

**Issue by arienjudge** [zephyrproject-rtos/zephyr#34631]
**Is your feature request related to a problem? Please describe.**
Add support for STM32's SAI on STM32H7 (and others). Currently, Zephyr's I2S shim driver makes use of the I2S/SPI interface available on most STM parts. For the H7 parts, the on-chip SAI peripheral provides more flexibility in the available data formats, number of slots, and more synchronisation options between multiple SAIs.

**Describe the solution you'd like**
A Zephyr shim for the SAI peripheral available on the STM32H7xx.

**Would like to support**
At a minimum:
    I2S
    TDM16
    DMA 

**Describe alternatives you've considered**
I2S/SPI driver - doesn't work out of the box on H7 parts. Differences in the RCC config to be ironed out.
Using the STM SAI HAL driver directly - did what we wanted, but not as tidy as working with a Zephyr shim

**Additional context**

**Comment by Sujung84** [comment]
https://github.com/zephyrproject-rtos/zephyr/issues/35083
There are that  can use it by changing the sai and spi addresses in the device tree.
If I just set the address and pin with  using the existing i2s/spi driver will it work?

Also Could I know when the work will be finished? I started developing for stm32f469i-disc0.
So I want need help.
