### ISSUE TITLE
CAN - Bus Driver Sample

### ISSUE THREAD

**Issue by Nukersson** [zephyrproject-rtos/zephyr#34644]
https://github.com/zephyrproject-rtos/zephyr/blob/4e6cb116f87bb2ff0ece7d8f968adac4dd2c9b3d/samples/drivers/can/src/main.c#L161

Shouldn't it be: `if (can_recover(can_dev, K_MSEC(100)) != 0)`

**Comment by alexanderwachter** [comment]
Good catch! Thanks for reporting.
