### ISSUE TITLE
STM32 ADC - read of multiple channels in a sequence

### ISSUE THREAD

**Issue by roland-xz** [zephyrproject-rtos/zephyr#34656]
**Is your enhancement proposal related to a problem? Please describe.**
Currently STM32 only supports a single channel in a sequence read, this is not consistent with the driver of other SoCs and not documented anywhere.
https://github.com/zephyrproject-rtos/zephyr/blob/1cc73074d0540caa8dd7ea9501afefea2e410791/drivers/adc/adc_stm32.c#L325

**Describe the solution you'd like**
Make it consistent with other drivers and reflect what the `int adc_read(conststructdevice *dev, conststructadc_sequence *sequence)` API intends to do.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by erwango** [comment]
I'm closing as already requested in https://github.com/zephyrproject-rtos/zephyr/issues/32288.
