### ISSUE TITLE
FANSTEL BT840X

### ISSUE THREAD

**Issue by RenierVDWBluerain** [zephyrproject-rtos/zephyr#34855]
Hi,

The Fanstel BT840 devices are growing in popularity and are wondering if .dts and .yaml files can't be generated for those boards.

Especially the BT840X which has a PA/LNA Skyworks SKY66112 amplifier and there are no example code as to how one would enable that feature.

I'm currently using nrf52840dk_nrf52840.dts.

**Comment by dsconyers** [comment]
@RenierVDWBluerain I agree.  A working sample and a Fanstel EV-BT840X board support package would have allowed me to evaluate the Fanstel BT840X module much faster to determine if it was best fit for my application.  

I started from the nrf85840dk_nrf52840 board as well and had to add an overlay file to get it to work with the EV-BT840X board.  Then I created my custom board from there.
