### ISSUE TITLE
Add error check to twister if set of platforms between platform_allow and integration_platforms is empty

### ISSUE THREAD

**Issue by galak** [zephyrproject-rtos/zephyr#34927]
We have a testcase in https://github.com/zephyrproject-rtos/zephyr/blob/0e39b7d707d8fda73e72494fcb9d25c911e50a9c/tests/lib/cbprintf_package/testcase.yaml

that has `native_posix` as the `integration_platforms` but that platform is not in `platform_allow`.  As such nothing  runs in CI for this test.  We should treat this as an error when twister is run with `-G` for this test.

**Comment by nashif** [comment]
This should have been fixed already.
