### ISSUE TITLE
drvers/flash/nrf_qspi_nor: high power consumption on nrf52840

### ISSUE THREAD

**Issue by nvlsianpu** [zephyrproject-rtos/zephyr#34932]
**Describe the bug**
Energy consumption is to high.
This is related to nRF52840 anomaly 122
[here](https://devzone.nordicsemi.com/f/nordic-q-a/73909/qspi-high-current-improvements-for-anomaly-122-in-nrf52840)

**solution**
here: https://github.com/zephyrproject-rtos/zephyr/pull/34405

**Comment by rodrigobrochado** [comment]
#34405 is merged, can close
