### ISSUE TITLE
SoF module is not pointing at Zehpyr repo

### ISSUE THREAD

**Issue by galak** [zephyrproject-rtos/zephyr#34948]
West.yml has:

```
    - name: sof
      url: https://github.com/nordic-krch/sof
      revision: 2f8ef204454d278f0c189e8c7cc70e84f745561a
      path: modules/audio/sof
```

This is not acceptable for release and needs to be resolved to use the Zephyr SoF fork.

**Comment by nordic-krch** [comment]
@nashif Fix in sof has been merged but I am not sure how that gets to zephyr fork.

**Comment by nashif** [comment]
huh,  and I was wondering how the MAX issue was worked around, @carlescufi  how can we block such changes from being merged, anyway we can do a check on the manifest and block PRs that have such entries?

**Comment by marc-hb** [comment]
> huh, and I was wondering how the MAX issue was worked around,

https://github.com/zephyrproject-rtos/zephyr/issues/33567#issuecomment-829868678
