### ISSUE TITLE
Using BT_ISO bluetooth hci_usb sample, and  enable, but still shows no command supported

### ISSUE THREAD

**Issue by super6602** [zephyrproject-rtos/zephyr#34999]
**Describe the bug**
Attempted to use the samples/bluetooth/hci_usb/ project with

CONFIG_BT_ISO=y

to run application over HCI over USB for on a NRF52840-DK. But still shows no BLE ISO related command supported

**Comment by cvinayak** [comment]
CONFIG_BT_ISO is not supported in the controller implementation, and hence not enabled in the hci_usb configuration.
