### ISSUE TITLE
mcuboot with enabled  serial recovery does not compile

### ISSUE THREAD

**Issue by de-nordic** [zephyrproject-rtos/zephyr#35048]
**Describe the bug**
The mcuboot, selected by west,  does not compile since b85250108cef66033cdb0bdbecea5d3e7926c62f commit to Zephyr.

**To Reproduce**
0. Download overlay file and replace <dir-to>with the download dir
1. Go to zephyr root
2. west build -b nrf52840dk_nrf52840 --build-dir voot bootloader/mcuboot/boot/zephyr/  -t menuconfig -- -DOVERLAY_CONFIG=<dir_to>/serial-recovery.overlay.txt
3. See linker error

**Expected behavior**

**Impact**
Not able to compile mcuboot for serial recovery.

**Environment (please complete the following information):**
 - OS: Ubuntu 20
 - Toolchain zephyr sdk 0.12
 - Commit 5e9d6d638c627f66da25b2393ac63e3846c59594

[serial-recovery.overlay.txt](https://github.com/zephyrproject-rtos/zephyr/files/6457554/serial-recovery.overlay.txt)

**Comment by nordic-krch** [comment]
The issue is MULTITHREADING is off so kernel files for scheduling are not included but there are modules fetched that are using multithreading essentially making it multithreading app.

Is see 2 ways:
- removed `CONFIG_MULTITHREADING=n`
- fix module to not use multithreading stuff (`k_sleep`) by replacing it with no-multithreading friendly `k_busy_wait`.

**Comment by de-nordic** [comment]
> Is see 2 ways:
> 
>     * removed `CONFIG_MULTITHREADING=n`
> 
>     * fix module to not use multithreading stuff (`k_sleep`) by replacing it with no-multithreading friendly `k_busy_wait`.

The removal significantly increase the binary size (4k)

The problem is with `z_impl_k_sleep` and `z_pm_save_idle_exit` and and one seems to be reported from `zephyr/drivers/serial/libdrivers__serial.a(uart_nrfx_uarte.c.obj)` and the other from `zephyr/arch/arch/arm/core/aarch32/libarch__arm__core__aarch32.a(isr_wrapper.S.obj)`

**Comment by nvlsianpu** [comment]
@nordic-krch 
> Actually, there is already a fix in uarte:
...

Yes, but it is compiled-out using complier, and now need to use preprocessor instead.
Easy to fix then :D

**Comment by nvlsianpu** [comment]
MCUboot upstream fix: https://github.com/mcu-tools/mcuboot/pull/1009
