### ISSUE TITLE
Tracing shows k_busy_wait() being executed very often on nRF platforms

### ISSUE THREAD

**Issue by carlescufi** [zephyrproject-rtos/zephyr#35046]
As per the screenshots below, provided by @nashif, `k_busy_wait()` is executing repeatedly on traces obtained on a Nordic board.

This can be reproduced by building `samples/synchronization` with tracing enabled.

nRF Platform:
<img width="1928" alt="Screenshot 2021-05-08 at 08 30 36" src="https://user-images.githubusercontent.com/12450381/117655483-6e154d80-b197-11eb-98db-dd6d969c4220.png">

k64f Platform:
<img width="1934" alt="Screenshot 2021-05-08 at 08 29 32" src="https://user-images.githubusercontent.com/12450381/117655442-605fc800-b197-11eb-868b-8b11399ee7e8.png">

**Comment by nordic-krch** [comment]
It is expected. `k_busy_wait(1)` is used inside `uart_poll_out` when driver is pending for driver readiness to send next byte. Safe loop is used there which is using `k_busy_wait` to track timeout. https://github.com/zephyrproject-rtos/zephyr/blob/5e9d6d638c627f66da25b2393ac63e3846c59594/drivers/serial/uart_nrfx_uarte.c#L483
