### ISSUE TITLE
example-application: Add example library & tests

### ISSUE THREAD

**Issue by gregshue** [zephyrproject-rtos/zephyr#35177]
**Is your enhancement proposal related to a problem? Please describe.**
Enhance the example-application repo with a `lib/` folder, a trivial configurable library, and tests.  This is to help fill out the agreed-upon scope of implementation.

**Describe the solution you'd like**
Add to the example-application repository a 'lib/' tree, a trivial configurable library, a 'tests/lib/' tree, and tests to verify the library.

**Describe alternatives you've considered**
No other alternatives were considered.

**Additional context**
None.

**Comment by gregshue** [comment]
An implementation in [example-application](https://github.com/zephyrproject-rtos/example-application/pull/4) has been under review since May 11, 2021.

**Comment by carlescufi** [comment]
Merged https://github.com/zephyrproject-rtos/example-application/pull/4
