### ISSUE TITLE
Coding Guidelines: Resolve the issues under Rule 21.2

### ISSUE THREAD

**Issue by yerabolu** [zephyrproject-rtos/zephyr#35189]
**Describe the bug**
Code should be compliant with the Rule 21.2 - A reserved identifier or reserved macro name shall not be declared
https://docs.zephyrproject.org/latest/guides/coding_guidelines/index.html?highlight=guidelines 

Also refer to the discussion in RFC #32590

**To Reproduce**
Static analysis scans with enabled coding guideline checkers will show all the issues. 

**Expected behavior**
Code should be compliant with the rule. 

**Additional context**
Code should be compliant with the rules for Functional Safety

**Comment by nashif** [comment]
we should not have bugs/enhancements for each coding guideline, this is unmanageable, This is a project direction and should be tracked in the tools we use, not here.
