### ISSUE TITLE
echo_server sample non-functional rails all CPUs on native_posix_64 board build

### ISSUE THREAD

**Issue by bob2oneil** [zephyrproject-rtos/zephyr#35190]
The same echo_server from the Zephyr distribution is not functional when building for native_posix_64 on a Ubuntu machine.

From an external view, when executing the application native on the platform, it will rail all of the cores of an 8 core machine.

The runtime terminal output is as follows:

UART_0 connected to pseudotty: /dev/pts/11
WARNING: Using a test - not safe - entropy source
*** Booting Zephyr OS build zephyr-v2.5.0-2076-g930893fc5678  ***

When I view the output of the UART using the screen command, I get a ton of the following messages

[00:00:00.000,000] <err> log: argument 1 in source log log message "argument %d in source %s log message "%s" missinglog_strdup()." missinglog_strdup().
[00:00:00.000,000] <err> log: argument 2 in source log log message "argument %d in source %s log message "%s" missinglog_strdup()." missinglog_strdup().
[00:00:00.000,000] <err> log: argument 1 in source log log message "argument %d in source %s log message "%s" missinglog_strdup()." missinglog_strdup().
[00:00:00.000,000] <err> log: argument 2 in source log log message "argument %d in source %s log message "%s" missinglog_strdup()." missinglog_strdup().

This occurs with the standard demo using the standard demo's project/kernel configuration.

To explore this behavior, I enabled the following:

CONFIG_ENTROPY_GENERATOR=y
CONFIG_TEST_RANDOM_GENERATOR=y

The results did not change.

I also when through the kernel configuration and removed TCP and IPv6 settings to simplify the distribution.

The results were the same, CPUs railed, pseudo-terminal has endless errors.

**To Reproduce**
1. west build -p always -b native_posix_64 ./
2. west built -t run

**Expected behavior**
Behavior as described in online documentation.

**Impact**
Sshowstopper

**Logs and console output**
Provided

**Environment (please complete the following information):**
 - OS: Ubuntu20)
 - Toolchain (e.g Zephyr SDK Native Posix 64.)

**Additional context**
HTOP shows what appears to be an ever increasing number of threads associated with the built version as zephyr.exe

**Comment by jukkar** [comment]
I just tried to run echo-server sample with Fedora 32 like this

Terminal 1:
```
cd $ZEPHYR_BASE/../net-tools
./net-setup.sh
```
Terminal 2:
```
cd $ZEPHYR_BASE/samples/net/sockets/echo-server
cmake -Bbuild . -DBOARD=native_posix_64 -DCONFIG_NATIVE_UART_AUTOATTACH_DEFAULT_CMD=\""gnome-terminal -- screen %s"\" -DCONFIG_NET_BUF_POOL_USAGE=y
make -Cbuild -j9
build/zephyr/zephyr.exe -attach_uart
```
Terminal 3:
```
cd $ZEPHYR_BASE/../net-tools
./echo-client 2001:db8::1
./echo-client 192.0.2.1
```
I did not see any `missing log_strdup().` prints and everything seemed to work just fine. This with latest upstream Zephyr.

**Comment by jukkar** [comment]
Note that `west update` does not update zephyr, it just updates the modules one dir up. For updating zephyr, you can do `git pull`

**Comment by bob2oneil** [comment]
I did a pull of the master branch as 2.6.0.rc1, which differs from my standard "west based" install.  Are you recommending using this 2.6.0.rc1 GIT repo pull for this test?  The reason I ask, is that release candidates are generally considered less stable that perhaps a non-resource candidate.  But I want to test using as much common to your environment, and no need to fight bugs that have already been fixed.  

Going forward, is it considered good practice to pull the master branch on GIT, and then work those changes into /zephryproject?

Thanks for the help on this.

**Comment by bob2oneil** [comment]
I did another creation of the Zephyr folder using the west process as follows:

west init ~/zephyrproject
cd ~/zephyrproject
west update

When I checked the version, it now matches the GIT pull of the master branch.

So I suppose the conclusion is that the 2.6.0.rc1 is consider the official release to work with.

**Comment by jukkar** [comment]
If you are developing new stuff that is suppose to be upstreamed, then you should use the latest upstream version. That git head version is probably not suitable to be used in products where you want to use a stable release.

**Comment by aescolar** [comment]
From the discussion it would seem the issue is not present in the tip of main.
@bob2oneil Should this issue be closed?

**Comment by bob2oneil** [comment]
I need to follow up and determine where the problem lies, perhaps with the 'screen" implementation. There are a ton of string duplicate warnings that I can suppress with a kernel config setting.
