### ISSUE TITLE
tests/kernel/msgq/msgq_usage failed on hsdk board

### ISSUE THREAD

**Issue by IRISZZW** [zephyrproject-rtos/zephyr#35215]
**Describe the bug**
tests/kernel/msgq/msgq_usage failed on hsdk board

**To Reproduce**
1. west build -b hsdk -d build -p auto tests/kernel/msgq/msgq_usage
2. west flash
3. See error

**Logs and console output**
```
*** Booting Zephyr OS build v2.6.0-rc1-60-g41afd838aabd  ***
Running test suite msgq_usage
===================================================================
START - test_msgq_usage

    Assertion failed at WEST_TOPDIR/zephyr/tests/kernel/msgq/msgq_usage/src/main.c:196: client_entry: q

 FAIL - test_msgq_usage in 0.33 seconds
===================================================================
Test suite msgq_usage failed.
===================================================================
PROJECT EXECUTION FAILED
```

**Environment (please complete the following information):**
 - OS: (Linux)
 - Toolchain (Zephyr SDK)
 - Commit 8e69dafccf25bc5b4015a607cdba114216c4ea0e

**Comment by KangJianX** [comment]
This issue also can be found on ADSP.
