### ISSUE TITLE
tests: dma: memory-to-memory transfer fails on stm32f746zg nucleo board

### ISSUE THREAD

**Issue by FRASTM** [zephyrproject-rtos/zephyr#35220]
**Describe the bug**
test cases `tests/drivers/dma/chan_blen_transfer`/ and `tests/drivers/dma/loop_transfer` fail on nucleo_f746zg board

**To Reproduce**
1. west build -p auto -b nucleo_f746zg tests/drivers/dma/chan_blen_transfer/

**Expected behavior**
test PASSED

**Logs and console output**
... _timeout_

**Environment (please complete the following information):**
 - Commit SHA 53b8706f05aee7777caae8b6d3c2e5bde957a4bf

**Comment by FRASTM** [comment]
FIXED by https://github.com/zephyrproject-rtos/zephyr/pull/35165

**Comment by galak** [comment]
Need to validate if #35258 fixes this.

**Comment by FRASTM** [comment]
The pb of the #35220 is **not** fixed with this PR. The
Because the the soc/arm/st_stm32/stm32f7 does not define the `CONFIG_INIT_ARCH_HW_AT_BOOT`
then the Cache memory  is not disabled here in the `arch/arm/core/aarch32/cortex_m/scb.c`

**Comment by galak** [comment]
> The pb is **not** fixed with this PR #35258
> Because the the soc/arm/st_stm32/stm32f7 does not define the `CONFIG_INIT_ARCH_HW_AT_BOOT`
> then the Cache memory is not disabled here in the `arch/arm/core/aarch32/cortex_m/scb.c`

Shouldn't the cache get invalidated though in `z_arm_mpu_init()`?

**Comment by FRASTM** [comment]
This is not enough since in the `soc/arm/st_stm32_f7` st_stm32f7_init  function already enables the cache.So that
1)  	`select INIT_ARCH_HW_AT_BOOT` in the soc/arm/st_stm32/stm32f7/Kconfig.series
2) remove the SCB_EnableICache/SCB_EnableDCache  in the soc.c of the stm32F7 (and probalbly also of the stm32H7

**Comment by galak** [comment]
@FRASTM I dont follow.  It seems if I'm reading the code correctly that `z_arm_mpu_init()` will get called before `st_stm32f7_init`.

**Comment by FRASTM** [comment]
FIXED by #35165
tests are now PASSED
