### ISSUE TITLE
ieee802.15.4 support for stm32wb55

### ISSUE THREAD

**Issue by preetham05** [zephyrproject-rtos/zephyr#35238]
We are porting our proprietary 802.15.4 stack to stm32wb mc. It would be nice to have 802.15.4 driver support for stm32wb55 board

**Comment by erwango** [comment]
@preetham05 Thanks for your interest but this is not in our plans currently. If possible please contact your local ST FAE contact to see what would be possible to achieve with their support.

**Comment by piotrParf** [comment]
@erwango Has anything changed in the last 1.5 years?

**Comment by erwango** [comment]
> @erwango Has anything changed in the last 1.5 years?

Not on this regard. I'd suggest to report to local ST contact if you have any.
