### ISSUE TITLE
DOC:  DATA PASSING TABLE MISSING THE OBJECT QUEUES

### ISSUE THREAD

**Issue by manoj153** [zephyrproject-rtos/zephyr#35256]
https://docs.zephyrproject.org/latest/reference/kernel/index.html#data-passing
Data passing group in the left pane has included queue, but the table on the main body excluded or missed `queues `object
![image](https://user-images.githubusercontent.com/17961318/118132559-66bda080-b432-11eb-8569-3df1f65afd87.png)

**Comment by galak** [comment]
Sounds like this might be a bug?

**Comment by gmarull** [comment]
Seems like missing docs, Assigned Kernel code owners.

**Comment by nashif** [comment]
A queue is a FIFO, that is why it missing in the table.
