### ISSUE TITLE
Improve STM32: Serial Driver,Handle uart mode per instance 

### ISSUE THREAD

**Issue by manoj153** [zephyrproject-rtos/zephyr#35321]
The goal is to have each serial (instance)  mode to be configured independently as either, interrupt, or async.

 the issue I noticed is, the shell uses interrupt API, while when we enable the`CONFIG_UART_ASYNC_API=y` there is no mean to make a particular UART instance driven using interrupt mechanism, as such the shell is completely not functional.

**Additional context**
https://github.com/zephyrproject-rtos/zephyr/issues/34672 
The issue above describes the problem related to the shell with the current arrangement of serial driver

I can contribute a PR to address this, I would like to hear some inputs.

**Comment by shlomow** [comment]
@manoj153 I fixed the issue. The bug is described in the commit message. In general the only place that has shared code between interrupt api and async api is the isr function. So when there is a strange issue between the two modes the isr is the place to look

**Comment by manoj153** [comment]
@shlomow I'll do a testing a verify the commit

**Comment by erwango** [comment]
> IMPROVE STM32: SERIAL DRIVER,HANDLE UART MODE PER INSTANCE

@manoj153 caps lock ? ;-)

**Comment by manoj153** [comment]
> > IMPROVE STM32: SERIAL DRIVER,HANDLE UART MODE PER INSTANCE
> 
> @manoj153 caps lock ? ;-)

my bad, I am used to writing title as caps, should downcase them all?

**Comment by erwango** [comment]
> my bad, I am used to writing title as caps, should downcase them all?

In general all caps is seen as a bit aggressive (search for "all caps" in google),
so we use mixed or all lower cases, as one prefer.

**Comment by manoj153** [comment]
> > my bad, I am used to writing title as caps, should downcase them all?
> 
> In general all caps is seen as a bit aggressive (search for "all caps" in google),
> so we use mixed or all lower cases, as one prefer.

Thank you, appreciate your feedback, I have made the changes to the title
