### ISSUE TITLE
Adding support for measurement of Ultraviolet(UV) Light.

### ISSUE THREAD

**Issue by murali-tejeshwar** [zephyrproject-rtos/zephyr#35354]
The Zephyr sensor subsystem currently does not support the measurement of Ultraviolet(UV) light.

This can be solved by adding a new enumeration entry in the header file "include/drivers/sensor.h" so that sensors that measure UV light(such as Silicon Labs Si1133) can report UV measurements on this UV channel.

The following two lines are to be added to the  "enum sensor_channel", which is present in the above header file.
/** Ultraviolet index, in UVI. */
SENSOR_CHAN_UV,

**Comment by henrikbrixandersen** [comment]
The sensors subsystem allows sensor-specific extensions to the channels enumeration. See e.g. https://github.com/zephyrproject-rtos/zephyr/blob/main/include/drivers/sensor/mcux_acmp.h

**Comment by nashif** [comment]
For something generic I think it should be ok to submit this as a new channel and have it in the sensor  API. So, submit a PR please.

**Comment by murali-tejeshwar** [comment]
@nashif thank you. I have submitted a PR(#37259). Requesting @MaureenHelm and @avisconti to look into this, so that I can submit a driver patch(for Si1133 sensor) which references this new channel(SENSOR_CHAN_UV).

**Comment by MaureenHelm** [comment]
> I have submitted a PR(#37259). Requesting @MaureenHelm and @avisconti to look into this, so that I can submit a driver patch(for Si1133 sensor) which references this new channel(SENSOR_CHAN_UV).

Can you submit the driver in the same PR that introduces the new channel? First commit for the new channel, second commit for the driver that uses it?

**Comment by avisconti** [comment]
> > I have submitted a PR(#37259). Requesting @MaureenHelm and @avisconti to look into this, so that I can submit a driver patch(for Si1133 sensor) which references this new channel(SENSOR_CHAN_UV).
> 
> Can you submit the driver in the same PR that introduces the new channel? First commit for the new channel, second commit for the driver that uses it?

Yeah, that would be easier to review and to refer to it later on.

**Comment by murali-tejeshwar** [comment]
@MaureenHelm @galak I have submitted a new PR(#37354) that includes both the driver and the new channel.
