### ISSUE TITLE
CAN driver for LPCXpresso55S16

### ISSUE THREAD

**Issue by Qbicz** [zephyrproject-rtos/zephyr#35437]
**Is your feature request related to a problem? Please describe.**
NXP LPCXpresso5x series has already a good support in Zephyr:
https://docs.zephyrproject.org/latest/boards/arm/lpcxpresso55s16/doc/index.html
The only thing that stops me from using it in a project is a missing CAN bus support.

- Is there any ongoing effort to support CAN on this board/MCU?
- If not, how much work it is to port the driver from LPC Xpresso SDK, or extend already existing NXP CAN driver in Zephyr? What would be the best approach?

**Describe the solution you'd like**
Have CAN bus support on NXP LPCXpresso55S16.

**Describe alternatives you've considered**
Alternatively, I can use other NXP LPC microcontrollers with CAN controller, if it's easier to add CAN support for them in Zephyr.

**Comment by alexanderwachter** [comment]
It seems that it is an Bock M_CAN. If that is the case, you "only" need a fronted for the generic M_CAN driver.
(see the stm32_fdcan). @legoabram already ported to a SAM SoC.

**Comment by henrikbrixandersen** [comment]
@Qbicz Sorry it took so long, but I have a working CAN-FD driver for the LPC55S1x in #35832 if you would like to test it.
