### ISSUE TITLE
drivers: sensor: sbs-gauge: The sbs-gauge cannot be read from sensor shell

### ISSUE THREAD

**Issue by alexanderwachter** [zephyrproject-rtos/zephyr#35444]
**Describe the bug**
The sensor shell does unconditionally fetch all channels whenever something is read.
The sbs-gauge does not implement the SENSOR_CHAN_ALL and therefor cannot be used with the shell.

**Expected behavior**
Sensor shell can read the values

**Impact**
Sensor shell cannot be used with the sbs-gauge

**Logs and console output**
```
uart:~$ sensor get BAT_GAUGE 
Failed to read sensor: -134
```

**Additional context**
Fix: #35443

**Comment by grillchef** [comment]
This issue is also related to the driver bq274xx
