### ISSUE TITLE
The dma-stm32 driver don't build for STM32F0 MCUs

### ISSUE THREAD

**Issue by simonguinot** [zephyrproject-rtos/zephyr#35474]
Here is the error message when building the dma-stm32 driver for a STM32F0 MCU:

```
drivers/dma/dma_stm32.c: In function 'dma_stm32_configure':
drivers/dma/dma_stm32.c:470:16: error: 'LL_DMA_InitTypeDef' {aka 'struct <anonymous>'} has no member named 'PeriphRequest'
  DMA_InitStruct.PeriphRequest = config->dma_slot;
                ^
```

I encountered this issue when building a Zephyr application for a nucleo_f070rb board with SPI_STM32_DMA enabled.

**Comment by simonguinot** [comment]
Looking at #34972, I think it is not related.

**Comment by str4t0m** [comment]
I guess FRASTM meat to refer to #34666, which omits the assignment of DMA_InitStruct.PeriphRequest for series that are compatible to st_stm32_dma_v2bis.
