### ISSUE TITLE
Bluetooth: Cannot connect if extended advertising is enabled in `prj.conf`

### ISSUE THREAD

**Issue by chrisswinchatt-arm** [zephyrproject-rtos/zephyr#35596]
**Describe the bug**

A Zephyr program compiled with the following in `prj.conf`:

```
CONFIG_BT=y
CONFIG_BT_CENTRAL=y
CONFIG_BT_PERIPHERAL=y
CONFIG_BT_EXT_ADV=y
CONFIG_BT_PER_ADV=y
```

Calling `bt_conn_le_create` after discovering a peer returns -5 (`-EIO`) when compiled with the above config. Removing or setting to `n` the `CONFIG_BT_EXT_ADV` option and recompiling corrects the behaviour.

CONFIG_BT_EXT_ADV | CONFIG_BT_PER_ADV | Return value of `bt_conn_le_create`
:---:|:---:|:---:
n | n | 0
n | y | 0
y | n | -5
y | y | -5

**To Reproduce**
1. Compile [the code in this gist](https://gist.github.com/chrisswinchatt-arm/e1bb45e088def70db0aed158c3b44d4f)
2. Flash to the boards; I tested with `nucleo_wb55rg`, `disco_l475_iot1` and `nrf52840_mdk`; which is central and which is peripheral doesn't matter
3. Use serial console to send A to one board to tell it to advertise and S to the other to tell it to scan
4. The error is shown on the serial console of the scanning board when it attempts to connect

**Expected behavior**
It should be possible for a single program to support both connect & periodic sync.

**Impact**
Showstopper

**Logs and console output**
```
*** Booting Zephyr OS build zephyr-v2.5.0-2959-g9a14f627426b  ***
Initialising...
Press A to start advertising or S to start scanning
Scanning for 10 seconds
Connecting to Issue (80:e1:26:1b:76:02)
bt_conn_le_create: error -5
```

**Environment (please complete the following information):**
 - OS: (e.g. Linux, MacOS, Windows) Windows
 - Toolchain (e.g Zephyr SDK, ...): Zephyr / West
 - Commit SHA or Version used: 9a14f627426ba1e25e75d8ea3ebbdcccc4d9b2a7

**Additional context**
N/A

**Comment by joerchan** [comment]
Support for extended advertising needs to be enabled in the zephyr controller.
`CONFIG_BT_CTLR_ADV_EXT=y`

**Comment by carlescufi** [comment]
@chrisswinchatt-arm if you objective is to come up with a [power consumption comparison](https://github.com/chrisswinchatt-arm/bluetooth-power-consumption-benchmark/tree/feature-zephyr) between different RTOS, may I point out that you need to take into account not only Bluetooth, but also things like other peripherals (the UART in particular) as well as the behavior of the application itself.

**Comment by joerchan** [comment]
Did some digging because it was weird that only creating connections was affected, but advertising and scanning worked fine.

Turns out the feature bit checking was inconsistent, I've created a fix for it.

**Comment by chrisswinchatt-arm** [comment]
Thanks for speedy response @all.
