### ISSUE TITLE
arch.interrupt.arm.irq_vector_table.arm_irq_vector_table: MPU FAULT Halting system for mximxrt685_evk_cm33

### ISSUE THREAD

**Issue by hakehuang** [zephyrproject-rtos/zephyr#35658]
**Describe the bug**
irq_vector_table test hangs

**To Reproduce**
1. mkdir build; cd build
2. cmake -Dmimxrt685_evk_cm33 ..
3. make; make flash

**Expected behavior**
PASS

**Impact**
irq vector teable

**Logs and console output**

```
E: ***** MPU FAULT *****
E:   Instruction Access Violation
E: r0/a1:  0x180044b1  r1/a2:  0x00000000  r2/a3:  0x180044b1
E: r3/a4:  0x30180868 r12/ip:  0xa0000000 r14/lr:  0xfffffffd
E:  xpsr:  0x68000039
E: Faulting instruction address (r15/pc): 0xfb06fef6
E: &gt;&gt;&gt; ZEPHYR FATAL ERROR 0: CPU exception on CPU 0
E: Fault during interrupt handling
E: Current thread: 0x30180218 (main)
E: Halting system
```

**Environment (please complete the following information):**
 - OS: (e.g. Linux)
 - Toolchain (e.g Zephyr SDK, ...)
 - Commit SHA or Version used: v2.6.0-rc1-323-gae4fb20f6733

**Comment by hakehuang** [comment]
@MaureenHelm , @dleach02 , @mmahadevan108 , this issue also existing in RC1

**Comment by MaureenHelm** [comment]
git bisect landed on commit ff398d81a46596cdc18b7fe5ea4ae24d8599940c:
```
commit ff398d81a46596cdc18b7fe5ea4ae24d8599940c
Author: Mahesh Mahadevan <mahesh.mahadevan@nxp.com>
Date:   Fri Apr 23 16:50:13 2021 -0500

    drivers: timer: rt600: Update SYS_CLOCK_TICKS_PER_SEC
    
    Use the default value as we were failing kernel
    timer tests with the increased value
    
    Signed-off-by: Mahesh Mahadevan <mahesh.mahadevan@nxp.com>
```

**Comment by mmahadevan108** [comment]
This issue seems to be related to switching the kernel tick timer away from SYSTICK to OS Event timer. The test is failing the below lines
https://github.com/zephyrproject-rtos/zephyr/blob/main/tests/arch/arm/arm_interrupt/src/arm_interrupt.c#L336-L353
because the test is expecting a CPU exception instead and RT600 is throwing a Kernel Panic. 

I am not clear how to address this.

**Comment by MaureenHelm** [comment]
I think the test needs to be updated similar to Nordic platforms:
https://github.com/zephyrproject-rtos/zephyr/blob/45bd3dee08ef9804fd4684ae20fde4e53af2c0f2/tests/arch/arm/arm_irq_vector_table/src/arm_irq_vector_table.c#L177-L196

**Comment by dleach02** [comment]
#36278 points to the underlying issue here.

After some discussion with @ioannisg it may be that we are doing this test correctly but that the original test/nordic board exhibited a different behavior because of #36278
