### ISSUE TITLE
The channel selection of auxiliary advertisments in extended advertisments

### ISSUE THREAD

**Issue by lukasbrchl** [zephyrproject-rtos/zephyr#35668]
Hi, is there any planned support for some heuristic functionality that would dynamically select channels for auxiliary advertisements? We found out that channel 0 is selected as the default for any extended advertising payloads which might be quite unreliable if there is a lot of inference on this particular channel.

Thanks,
Lukas

**Comment by cvinayak** [comment]
Advertising extensions is work in progress, currently no one is working  is being done on the auxiliary advertising channels. Contributions to add it is welcome.
