### ISSUE TITLE
Check minimal version of llvm/lld linker

### ISSUE THREAD

**Issue by tejlmand** [zephyrproject-rtos/zephyr#35671]
Support for lld instead of ld.bfd was introduced here:
 #31706, in this commit: 2a59fa52b8e8fe2923a5295cf6c2a71a5eb837c8

However, linking fails if user is using a older llvm, for example v10.0.0.

So a check should be introduced which ensures that llvm in use is >=v12.0.0

**Describe the solution you'd like**
A check to ensure llvm >=12.0.0 is used.

**Describe alternatives you've considered**
N/A

**Additional context**

Edit: old description removed, as it was caused by an old llvm (version 10), instead changed into request to ensure llvm >=12 is used.

**Comment by XiaZhouZero** [comment]
Does anybody know how to build Zephyr and generate the whole IR file of an application, e.g., sample/hello_world?
I tried to add compiler flags in the application CmakeLists.txt by add this command `zephyr_library_compile_options(-flto -fuse-ld=lld)` . However, the building process failed when linking the libapp.a file.

Thanks for your help in advance!

**Comment by tejlmand** [comment]
> Does anybody know how to build Zephyr with LLVM/Clang and generate the whole IR file of an application, e.g., sample/hello_world?

@XiaZhouZero Could you open a dedicated question on this topic, as it is unrelated to this issue.
Issue if there is something you think should be improved.
Question if you just need to know more.

That being said, are you talking about the final image or each individual object file ?
As compile option you may use the `COMPILER_OPT` in Kconfig to add additional compiler options, like `-emit-llvm`.

And that will give you the llvm bytecode, however there are python scripts that relies on the elf object file as output, so it's not really useful as such as those scripts will then fail.

So it could be we should have some kind of possibility to allow users to also output an additional format, bytecode, assembly, pre-processed file, etc.
