### ISSUE TITLE
samples: subsys: testusb: I want to know how to test in window10.

### ISSUE THREAD

**Issue by wngur300** [zephyrproject-rtos/zephyr#35714]
**Describe the bug**
Unable to perform usb loopback test on Desktop (window10). 

![etc](https://user-images.githubusercontent.com/46815991/119916804-2c124700-bfa0-11eb-83e8-a0752c07f2f7.png)
**Device Status :**
 - The driver for this device is not installed. (Code 28)
 - There are no compatible drivers for this device. 

There are no compatible drivers on this device

**To Reproduce**
1. mkdir build; cd build
2. cmake -DBOARD=nucleo_wb55rg ..
3. west flash

**Expected behavior**
I want to do a usb loopback test on window10 OS.

**Environment (please complete the following information)**
OS: Linux ubuntu 18.04
Toolchain: zephyr-sdk-0.11.4
Commit SHA or Version used: 7a3b253

**Additional context**
I read README.rst and tested usbloopback sources on Linux.
However, I would like to do a usbloopback test on my Desktop (OS: winow7, 10).
When you build samples/subsys/usb/testusb sources and connect them to Desktop (window10) as usb, the device looks like this, but there are no compatible drivers for this device:
I found a way to test it in the window, but I couldn't find a good way to post it for advice.
Is there a good way to test it simply?

**Comment by jfischer-no** [comment]
Only Linux host is supported by this example. Other host OS can not be supported.
