### ISSUE TITLE
drivers: can: mcan: sjw not initialized when CAN_FD_MODE is enabled

### ISSUE THREAD

**Issue by str4t0m** [zephyrproject-rtos/zephyr#35737]
**Describe the bug**
The mcan driver does not initialize the timing.sjw variable in CAN_FD_MODE configuration.
This causes undefined behavior and might trigger a assert that checks the valid range of this parameter.

**Expected behavior**
The synchronization jump width should be initialized with the parameter configured.

**Impact**
Undefined behavior might lead to synchronization problems.

**Comment by alexanderwachter** [comment]
Fix: #35738
