### ISSUE TITLE
sample: USB audio samples are not working on STM32

### ISSUE THREAD

**Issue by LongerHV** [zephyrproject-rtos/zephyr#35809]
I wanted to play around with USB audio on STM32, but included samples are not working corectly.
I have nucleo_h743zi and stm32f103_mini boards. Both of them behave the same.
Program compiles, flashes and board is recognized as USB audio device as expected.
The problem is with the actual audio loopback, which is not working.

# Steps to reproduce:
1. Build and flash sample subsys/usb/audio/headset on STM32 board
2. Connect board via USB
3. Play some audio on the playback device
4. Audio is supposed to loop back and appear on the capture device, but it is silent

# Logs
## dmesg
```
[94911.490729] usb 1-4: new full-speed USB device number 33 using xhci_hcd
[94911.618411] usb 1-4: New USB device found, idVendor=2fe3, idProduct=0100, bcdDevice= 2.06
[94911.618424] usb 1-4: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[94911.618429] usb 1-4: Product: Zephyr USB audio sample
[94911.618434] usb 1-4: Manufacturer: ZEPHYR
[94911.618438] usb 1-4: SerialNumber: 5109842531335552
```
## tcpdump
I attach an usblog from tcpdump, which can be viewed using wireshark (device 1.34 is a STM32 board and 1.23 is Focusrite serving as output device).
![patchbay](https://user-images.githubusercontent.com/46924944/120072079-30b72800-c092-11eb-91f9-bdc883841196.png)
[usblog.tar.gz](https://github.com/zephyrproject-rtos/zephyr/files/6564742/usblog.tar.gz)

# Environment
## Build
 - OS: Arch Linux
 - Toolchain: Zephyr SDK 0.12.4

## Testing
  - Arch Linux (pipewire)
  - Kubuntu (pulse audio)
  - Windows 10

# Notes
PR #35421 is necessary to flash stm32f103_mini board with USB support.

**Comment by petarsusac** [comment]
The USB audio samples are still not functional on STM32 boards (Zephyr v4.1, Debian 12 host OS).

Maybe the development effort is focused on the device_next stack? Are there any equivalent samples that are able to run on STM32 boards using this stack?
