### ISSUE TITLE
ADC support for STM32l496_disco board

### ISSUE THREAD

**Issue by chandramauli-mpc** [zephyrproject-rtos/zephyr#35835]
Currently example code of ADC is not supporting STM32l496_disco board. 

Add support of ADC for STM32l496_disco board.
I am getting error in adding dts node and implementing code . 

![Capture](https://user-images.githubusercontent.com/55747909/120280734-af4fd780-c2d5-11eb-8930-d00a9543996d.JPG)

**Comment by affrinpinhero-2356** [comment]
We will add support at the earliest.
