### ISSUE TITLE
intel_adsp_cavs15: run msgq testcases failed on ADSP

### ISSUE THREAD

**Issue by KangJianX** [zephyrproject-rtos/zephyr#35857]
**Describe the bug**
run tests/kernel/msgq/msgq_usage/ failed on ADSP

**To Reproduce**
1. twister -p intel_adsp_cavs15 --device-testing -T tests/kernel/msgq/msgq_usage/ --west-flash="/home/ztest/work/zephyrproject/zephyr/boards/xtensa/intel_adsp_cavs15/tools/flash.sh,/home/ztest/work/zephyrproject/modules/audio/sof/keys/otc_private_key.pem,/home/ztest/work/rimage/config,/home/ztest/work/rimage/build/rimage" --device-serial-pty="/home/ztest/work/zephyrproject/zephyr/boards/xtensa/intel_adsp_cavs15/tools/adsplog.py,--no-history"

**Logs and console output**

> Running test suite msgq_usage
===================================================================
START - test_msgq_usage
Unknown message 0

**Environment (please complete the following information):**
 - OS: Fedora28
 - Toolchain: Zephyr-sdk-0.12.4
 - Commit ID: c5e50ef0e219

**Comment by LeiW000** [comment]
Please remove Stale label.

**Comment by andyross** [comment]
Works for me on both cavs15 and cavs25 as of current main.  Retest?

**Comment by KangJianX** [comment]
Blocked by #38446 . I will retest this one when #38446 is fixed.

**Comment by nashif** [comment]
I can reproduce this, getting:

```
ups1:zephyr(main): sudo  boards/xtensa/intel_adsp_cavs15/tools/adsplog.py
Running test suite msgq_usage
===================================================================
START - test_msgq_usage
Unknown message 0
```
