### ISSUE TITLE
H

### ISSUE THREAD

**Issue by trintinwibul** [zephyrproject-rtos/zephyr#35868]
**Is your enhancement proposal related to a problem? Please describe.**
A clear and concise description of what the problem is.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context or graphics (drag-and-drop an image) about the feature request here.

**Comment by carlescufi** [comment]
@trintinwibul I have closed this since it had no content. Please create a new issue.
