### ISSUE TITLE
Bluetooth: host: CCC store not correctly handled for multiple connections

### ISSUE THREAD

**Issue by joerchan** [zephyrproject-rtos/zephyr#35876]
**Describe the bug**

Reported on slack:

> I see a problem in bt_gatt_attr_write_ccc function (gatt.c L1749). The cfg value is compared to ccc value  ("Highest value of all connected peer's subscriptions"). I am not sure why "Highest value" is of interest here. A subscription flag (boolean) indicating whether a subscription has been made makes more sense to me. Anyway, the compare made in bt_gatt_attr_write_ccc function (L1749) will result in gatt_ccc_store.work NOT submitted for a second device subscribing for notification and subscription will be lost for second device on reboot!
I am not familiar with the code in gatt.c but looks like the following code (from L1744)
    ...
    cfg->value = value;
    BT_DBG("handle 0x%04x value %u", attr->handle, cfg->value);
    /* Update cfg if don't match */
    if (cfg->value != ccc->value) {
        gatt_ccc_changed(attr, ccc);
    ...
should be replaced by
    ...
    BT_DBG("handle 0x%04x value %u", attr->handle, value);
    /* Update cfg if don't match */
    if (cfg->value != value) {
        cfg->value = value;
        gatt_ccc_changed(attr, ccc);
    ...

Reported issue is pointing out that storing for CCC configurations are not correctly handled when multiple connections are subscribed to the same attribue when using CCC store on write feature.

This is because the same condition for delivering the CCC changed callback is used to enqueue CCC stores.
This condition only handles the difference between "any connection is subscribed" and "no connection is subscribed". 
Instead CCCs should be stored if the value for the connection is different from the already stored value for the connection.

**Expected behavior**
CCCs should be stored when updated by application.

**Impact**
CCC store on write does not work for multiple connections.

**Workaround**
Don't use CONFIG_BT_SETTINGS_CCC_STORE_ON_WRITE together with CONFIG_BT_MAX_CONN > 1

**Comment by aescolar** [comment]
CC @jrth
