### ISSUE TITLE
Fixed width documentation makes DT bindings docs unreadable

### ISSUE THREAD

**Issue by mbolivar-nordic** [zephyrproject-rtos/zephyr#35882]
**Describe the bug**

See  e.g. https://docs.zephyrproject.org/latest/reference/devicetree/bindings/spi/nordic%2Cnrf-spim.html#dtbinding-nordic-nrf-spim

Which, on my system's Firefox, looks like this (notice how the property description is cut off and requires scrolling to read):

![2021-06-02T08:08:08,424747574-07:00](https://user-images.githubusercontent.com/62298616/120505336-ba5c4380-c379-11eb-8d41-46c8a4e5a9c7.png)

**Expected behavior**

No side scrolling required. Having to scroll horizontally is a real annoyance.

**Environment (please complete the following information):**

 - Commit SHA or Version used: 282a644b0ea3a79cf0dcd98b989037f5d85c30a9

**Comment by gmarull** [comment]
We can make a workaround as we did for Kconfig, but we really need to move away from tables (or structure them better), specially if we plan to support LaTeX properly at some point.

Ref. https://github.com/zephyrproject-rtos/zephyr/pull/35369/commits/fb1957ea1f0a0c9dda8f81930ecd96a0823001e8
