### ISSUE TITLE
up_squared: samples/boards/up_squared/gpio_counter/ is failing

### ISSUE THREAD

**Issue by yerabolu** [zephyrproject-rtos/zephyr#35970]
**Describe the bug**
samples/boards/up_squared/gpio_counter/ is failing to set HAT pin 35 to OUT (-22).

**To Reproduce**
1. twister -W -p up_squared --device-testing --device-serial /dev/ttyUSB0 -T samples/boards/up_squared/gpio_counter/  --west-flash="~/up_squared.sh"
2. see error

**Expected behavior**
Test should get executed and Pass as below:

**Impact**
What impact does this issue have on your progress (e.g., annoyance, showstopper)

**Logs and console output**
```
*** Booting Zephyr OS build v2.6.0-rc3-33-ga02704bacf46  ***
ERROR: cannot set HAT pin 35 to OUT (-22)
```
**Environment (please complete the following information):**
 - OS: Fedor 29
 - Toolchain. 12.4
 - Commit SHA: a02704bacf46

**Comment by chen-png** [comment]
closed this, as the main problem is that the necessary gpio configuration of this test have not been done, I tested with the latest version, it was passed.
>*** Booting Zephyr OS build zephyr-v2.6.0-2360-gc94e53c9f5b6  ***
counter: 0x0
counter: 0x1
counter: 0x2
counter: 0x3
counter: 0x4
counter: 0x5
counter: 0x6
counter: 0x7
counter: 0x8
counter: 0x9
counter: 0xa
counter: 0xc
counter: 0xd
counter: 0xe
counter: 0xf
