### ISSUE TITLE
arm: qemu: run cmsis-dsp tests on the qemu target with FPU

### ISSUE THREAD

**Issue by ioannisg** [zephyrproject-rtos/zephyr#36013]
As soon as we have a qemu target with FPU on Cortex-M (mps2_an521_remote), cmsis-dsp tests should be updated to test with this target (w/ hardfp). Currently cmsis-dsp tests are being tested using mps2_an521 with softfp.

Depends on #35381.

**Comment by stephanosio** [comment]
NOTE: `mps3_an547` (Cortex-M55) should be added as an integration platform later once #37687 is implemented in order to test CMSIS-DSP with the Helium/MVE instruction set.
