### ISSUE TITLE
Wrong channel index in connectionless IQ samples report

### ISSUE THREAD

**Issue by ppryga** [zephyrproject-rtos/zephyr#36022]
**Describe the bug**
`struct bt_df_per_adv_sync_iq_samples_report` contains channel index. The value provided by host is not correct channel index.
From time to time it may be observed that is exceeds valid channels range 0x0-0x27.

**To Reproduce**
Two nRF52833 DKs are required.
First one must run direction_finding_connectionless_tx sample.
Second one must run direction_finding_connectionless_rx sample.

The error may be observed after extending cte_recv_cb to print channel index.
Channel index does not change between periodic advertising events.
Channel index may be out of valid channels range.

**Expected behavior**
Reported channel index to be in range: 0x0-0x27.
Reported channel should change every periodic advertising event.

**Impact**
Issue impacts usage of Direction Finding.

**Logs and console output**
PER_ADV_SYNC[0]: [DEVICE]: 1B:3F:16:8E:39:0A (random), tx_power 127, RSSI -45, CTE AOA, data length 0, data:
CTE[0]: samples count 45, cte type AOA, slot durations: 2 [us], packet status CRC OK, RSSI -450, chan: 141
PER_ADV_SYNC[0]: [DEVICE]: 1B:3F:16:8E:39:0A (random), tx_power 127, RSSI -50, CTE AOA, data length 0, data:
CTE[0]: samples count 45, cte type AOA, slot durations: 2 [us], packet status CRC OK, RSSI -500, chan: 141

**Environment (please complete the following information):**
 - Current main e.g. commit: https://github.com/zephyrproject-rtos/zephyr/commit/33fafe1e2f41e5b61b1dc71f9ad0d8cb0930607f

**Additional context**

**Comment by carlescufi** [comment]
This is fixed in #36023
