### ISSUE TITLE
bt_init returning success when Bluetooth initialization does not get finalized.

### ISSUE THREAD

**Issue by pigeonhands** [zephyrproject-rtos/zephyr#36037]
**Describe the bug**
`bt_enable` is returning success when not initialized.
Caused by [`bt_init` returning early](https://github.com/zephyrproject-rtos/zephyr/blob/main/subsys/bluetooth/host/hci_core.c#L3435) and [not calling `bt_finalize_init`](https://github.com/zephyrproject-rtos/zephyr/blob/38eaabc9c75c9a0932bbd272952dc81a2f2939ef/subsys/bluetooth/host/hci_core.c#L3441) if `CONFIG_BT_SETTINGS=y` is and `bt_dev.id_count` is 0.

**To Reproduce**
1. set `CONFIG_BT_SETTINGS=y`
2. call `bt_enable` whoult calling `settings_load`

**Expected behavior**
Either returning a non-zero error code if this is an error condition, or finalizing the Bluetooth initializing if it is not.

**Impact**
It causes functions like `bt_le_ext_adv_start` to return `EAGAIN` because the `BT_DEV_READY` [does not get set](https://github.com/zephyrproject-rtos/zephyr/blob/38eaabc9c75c9a0932bbd272952dc81a2f2939ef/subsys/bluetooth/host/hci_core.c#L3407) even though it seems that Bluetooth got enabled successfully.

**Environment (please complete the following information):**
 - OS: Windows
 - Toolchain: NRF Sdk
 - v1.5.0

**Comment by joerchan** [comment]
@pigeonhands This is the intended behavior, If you enable BT_SETTINGS you have to call settings_load.
Otherwise the stack does not have any identities, which is needed to start the advertiser.

**Comment by pigeonhands** [comment]
> @pigeonhands This is the intended behavior, If you enable BT_SETTINGS you have to call settings_load.
> Otherwise the stack does not have any identities, which is needed to start the advertiser.

Should'nt bt_init return an error if called before settings_load then?

**Comment by joerchan** [comment]
> Should'nt bt_init return an error if called before settings_load then?

No, calling settings_load after bt_enable is supported, and what most of the samples do.
If you see the documentation for `bt_id_create` you can see that the order of these matters when it comes to the handling of the identities.
