### ISSUE TITLE
coredump.logging_backend: lpcxpresso55s28: test failure assertion fail

### ISSUE THREAD

**Issue by hakehuang** [zephyrproject-rtos/zephyr#36078]
**Describe the bug**
     lpcxpresso55S28
    ASSERTION FAIL [esf != ((void *)0)] @ WEST_TOPDIR/zephyr/arch/arm/core/aarch32/cortex_m/fault.c:993
    	ESF could not be retrieved successfully. Shall never occur.
    ASSERTION FAIL [esf != ((void *)0)] @ WEST_TOPDIR/zephyr/arch/arm/core/aarch32/cortex_m/fault.c:993
    	ESF could not be retrieved successfully. Shall never occur.
    

**To Reproduce**
two applications has same issue:

-  tests/arch/arm/arm_interrupt with '-DCONFIG_EXTRA_EXCEPTION_INFO=y'
- tests/kernel/fatal/exception -DCONF_FILE=prj_arm_fpu_sharing.conf

1. mkdir build; cd build
2. cmake -DBOARD=lpcxpresso55s28 -- -DCONFIG_EXTRA_EXCEPTION_INFO=y ..
3. make; make flash

**Expected behavior**
test pass

**Impact**
logging for core dump

**Logs and console output**
```
*** Booting Zephyr OS build zephyr-v2.6.0-90-gefccfcbfc915  ***
Coredump: lpcxpresso55S28
ASSERTION FAIL [esf != ((void *)0)] @ WEST_TOPDIR/zephyr/arch/arm/core/aarch32/cortex_m/fault.c:993
	ESF could not be retrieved successfully. Shall never occur.
ASSERTION FAIL [esf != ((void *)0)] @ WEST_TOPDIR/zephyr/arch/arm/core/aarch32/cortex_m/fault.c:993
	ESF could not be retrieved successfully. Shall never occur.
    
```

**Environment (please complete the following information):**
 - OS: (e.g. Linux )
 - Toolchain (e.g Zephyr SDK)
 - Commit SHA or Version used: zephyr-v2.6.0-90-gefccfcbfc915

**Comment by hakehuang** [comment]
@MaureenHelm , @dleach02 , found in this weekly

**Comment by henrikbrixandersen** [comment]
@galak Sorry, but I don't have access to an lpcxpresso55s28 board (only lpcxpresso55s16).

**Comment by galak** [comment]
> @galak Sorry, but I don't have access to an lpcxpresso55s28 board (only lpcxpresso55s16).

Oops, couldn't remember which one you had.  I guessed wrong ;).

**Comment by dleach02** [comment]
I have this board

**Comment by dleach02** [comment]
#37725 fixed this
