### ISSUE TITLE
intel_adsp_cavs25: secondary boot fails in arch_start_cpu()

### ISSUE THREAD

**Issue by kv2019i** [zephyrproject-rtos/zephyr#36088]
**Describe the bug**
SOF test cases using multiple DSP cores fail on cAVS25 hardware (TGL).

**To Reproduce**
Compile SOF application with Zephyr for cavs25 target and load SOF Linux kernel driver using a DSP topology that has at least one pipeline element assigned to non-primary core. This will result in SOF application to call arch_start_cpu(1).

Tracing the problem, zephyr/soc/xtensa/intel_adsp/common/soc_mp.c:arch_start_cpu() never gets pass
»       while (!start_rec.alive)
»       »       ;

**Expected behavior**
SOF test cases with multiple cores should pass.

**Impact**
Showstopper for SOF usage on TGL hw when using Zephyr as OS.

**Logs and console output**
n/a

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: Zephyr SDK 0.12.4
 - Commit SHA: 1f0b783bbb2cd0546d0fee12d72cccc694847915

**Additional context**
Related SOF bug https://github.com/thesofproject/sof/issues/4298

**Comment by kv2019i** [comment]
FYI @nashif @lgirdwood @lyakh

**Comment by lgirdwood** [comment]
@andyross I will try and run this on Qemu and see if we are programming different IP to SOF

**Comment by kv2019i** [comment]
Removing the stale label as this is actively worked on, with latest fix candidate in https://github.com/zephyrproject-rtos/zephyr/pull/37647

**Comment by andyross** [comment]
Fixed and merged.  Closing this.  Seems like in those 19 patches or whatever that I might have remembered to include a "Fixed:" header, but apparently I didn't.
