### ISSUE TITLE
pb_gatt buf_send does not call callback

### ISSUE THREAD

**Issue by Sterling-Sleight** [zephyrproject-rtos/zephyr#36100]
I am provisioning a BT Mesh device that is set up as a PB Gatt device. Provisioning is failing because the OOB input_complete message is never received when inputting an alphanumeric OOB value. The provisioner device times out after 60 seconds of not receiving the input_complete message. This is because the callback 'public_key_sent' is never called for PB Gatt devices when sending the public key. 

In commit 4cc8cb1c1513033e8aa6d9c1086456a062c9bc57 the 'public_key_sent' callback is added to manage flags to make sure that 'send_input_complete' isn't called before the public key is sent. The flag that specifies that the public key was sent never gets set and that flag is checked before calling 'send_input_complete()'. PB Gatt function 'buf_send' takes a callback as input but does nothing with it, causing the PUB_KEY_SENT flag to never get set.

To fix, 'buf_send' in pb_gatt.c should call the callback argument if one exists

This is a show stopper as I can not provision my PB Gatt device

**Comment by LingaoM** [comment]
Hi, PR https://github.com/zephyrproject-rtos/zephyr/pull/35702 is fixing this problem.
