### ISSUE TITLE
tests/subsys/cpp/cxx - doesn't compile on native_posix when CONFIG_EXCEPTIONS=y

### ISSUE THREAD

**Issue by avigreen1978** [zephyrproject-rtos/zephyr#36250]
**Describe the bug**
When compiling c++ code for `native_posix` board with `CONFIG_EXCEPTIONS=y`, the following error is produced:
```
c++: error: /crtbegin.o: No such file or directory
c++: error: /crtend.o: No such file or directory
ninja: build stopped: subcommand failed.
```
The source of this problem is that no cmake file sets `LIBGCC_DIR` value

**To Reproduce**
1. cd tests/subsys/cpp/cxx
2. Add `CONFIG_EXCEPTIONS=y`, `CONFIG_LIB_CPLUSPLUS=y`
3. west build -b native_posix

**Expected behavior**
Some cmake file before should set the `LIBGCC_DIR` value

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04

**Comment by stephanosio** [comment]
cc @tejlmand

**Comment by stephanosio** [comment]
It looks like `${LIBGCC_DIR}` is not set/valid for the `native_posix` target.
https://github.com/zephyrproject-rtos/zephyr/blob/08dfe74c15a8e9d5afa3aa3cb0713e5d894018fa/cmake/linker/ld/target.cmake#L16-L24
