### ISSUE TITLE
TF-M integration: add a brief user guide

### ISSUE THREAD

**Issue by ioannisg** [zephyrproject-rtos/zephyr#36298]
Zephyr/TF-M integration has matured in the latest period and it is time we added a brief TF-M integration user guide that assists the users start with TF-M in Zephyr.

**Comment by microbuilder** [comment]
Track via #36345

**Comment by cfriedt** [comment]
fwiu, this aligns with #35552 on getting the next major revision of mbedTLS into Zephyr LTS. Setting a priority to reflect that.

**Comment by microbuilder** [comment]
Solved by #37050
