### ISSUE TITLE
TF-M: enhance the TF-M/Zephyr integration for Zephyr v2.7.0 release

### ISSUE THREAD

**Issue by ioannisg** [zephyrproject-rtos/zephyr#36294]
Enhance the TF-M integration with Zephyr, for the LTS2 release

- [ ] Upmerge TF-M to 1.4 when ready
- [x] Improve TF-M documentation regarding the integration with Zephyr https://github.com/zephyrproject-rtos/zephyr/pull/37050
       - A TF-M integration user guide
       - Build and flash instructions, in all the boards
       - List of boards supported
       - Additional doc improvements
- [x] Consolidate NS target naming https://github.com/zephyrproject-rtos/zephyr/pull/36780
- [ ] Complete Kconfig for TF-M configuration, reflecting latest added Tf-M CMake options
- [x] Update MCUboot for TF-M, potentially adding a local path (#36954 )
- [ ] Update mbedtls for better PSA crypto support

Removed from 2.7.0

The following tasks won't be completed for 2.7.0 before the code freeze due to blocking issues that won't be resolved before the cutoff:

- [ ] FW update sample https://github.com/zephyrproject-rtos/zephyr/pull/34401

**Comment by microbuilder** [comment]
Thanks for putting this together.

I made a bunch of notes for myself for the TF-M presentation for ZDS 2021, and can recycle those to give people a starting point to understand TF-M: https://gist.github.com/microbuilder/53ac490db265e86e5840a9f752b3dc48

**Comment by ioannisg** [comment]
just FYI @cfriedt , this is planned for 2.7.0
