### ISSUE TITLE
Add intel HAL support

### ISSUE THREAD

**Issue by kumarnac** [zephyrproject-rtos/zephyr#36476]
## Origin
https://github.com/intel/hal-intel

## Purpose
Provide  HAL support  for Intel boards and  Intel SoC  specific hardware definitions to be referred by boards in Zephyr 

## Mode of integration
Mode of integration - Module 
Module Name:  hal_intel

## Pull Request

N/A

## Description
The module inclusion being requested would  host  Intel  platform  specific files and  driver abstraction layers to support  Intel boards in Zephyr.

# Dependencies
This module does not have a direct dependency on Zephyr.
Future Intel  boards included in Zephyr will refer to this module.

## Revision

SHA to be included initially **5b686a41d717a64fbfef637c4639459adf09832e** 

## License

``BSD-3-Clause``

**Comment by kumarnac** [comment]
The HAL  is required for supporting  ehl_pse_crb board  (https://github.com/kumarnac/zephyr/pull/1)  in zephyr

**Comment by nashif** [comment]
closing, if we need to introduce this hal for intel, a new issue will need to be created.
