### ISSUE TITLE
espressif: cannot install toolchain on Darwin-arm64

### ISSUE THREAD

**Issue by cfriedt** [zephyrproject-rtos/zephyr#36500]
**Describe the bug**
before:
```
% west espressif install
=== downloading ESP-IDF tools..
ERROR: Platform Darwin-arm64 appears to be unsupported
FATAL ERROR: command exited with status 1: ./tools/idf_tools.py --tools-json=tools/zephyr_tools.json install
```
after:
```
% west espressif install                             
=== downloading ESP-IDF tools..
Installing tools: xtensa-esp32-elf
Installing xtensa-esp32-elf@esp-2020r3-8.4.0
Downloading xtensa-esp32-elf-gcc8_4_0-esp-2020r3-macos.tar.gz to /Users/cfriedt/.espressif/dist/xtensa-esp32-elf-gcc8_4_0-esp-2020r3-macos.tar.gz.tmp
Done
Extracting /Users/cfriedt/.espressif/dist/xtensa-esp32-elf-gcc8_4_0-esp-2020r3-macos.tar.gz to /Users/cfriedt/.espressif/tools/xtensa-esp32-elf/esp-2020r3-8.4.0
=== downloading ESP-IDF tools completed
```
**To Reproduce**
See above

**Expected behavior**
See above

**Impact**
showstopper (sort of)

**Logs and console output**
see above

**Environment (please complete the following information):**
 - OS: `Darwin ChristophersAir.cogeco.local 20.5.0 Darwin Kernel Version 20.5.0: Sat May  8 05:10:31 PDT 2021; root:xnu-7195.121.3~9/RELEASE_ARM64_T8101 arm64`
 - Toolchain: espressif
 - Commit: `hal/espressif` 22e757632677e3579e6f20bb9955fffb2e1b3e1c

**Additional context**
FIX (rosetta allows the x86_64 binaries to Just Work™)
```
diff --git a/tools/idf_tools.py b/tools/idf_tools.py
index cb88b7223..d12d4f501 100755
--- a/tools/idf_tools.py
+++ b/tools/idf_tools.py
@@ -117,6 +117,7 @@ PLATFORM_FROM_NAME = {
     'osx': PLATFORM_MACOS,
     'darwin': PLATFORM_MACOS,
     'Darwin-x86_64': PLATFORM_MACOS,
+    'Darwin-arm64': PLATFORM_MACOS,
     # Linux
     PLATFORM_LINUX64: PLATFORM_LINUX64,
     'linux64': PLATFORM_LINUX64,
```

**Comment by sylvioalves** [comment]
@cfriedt thanks for the input.  
This has been already pushed upstream. However, it needs this PR (https://github.com/zephyrproject-rtos/zephyr/pull/36378) merged to take that change in place.
