### ISSUE TITLE
RFC: API Change: Bluetooth: Read Multiple

### ISSUE THREAD

**Issue by KKopyscinski** [zephyrproject-rtos/zephyr#36544]
### Problem description

Currently, if GATT Read Multiple is used, at first host tries to use GATT Read Multiple Variable Length. If `Not Supported` error is returned, host will try again using GATT Read Multiple. This makes both certification tests problematic, and is not most efficient.

### Proposed change

As in Pull Request https://github.com/zephyrproject-rtos/zephyr/pull/36281

### Detailed RFC

If multiple handles are used in `bt_gatt_read_params` they shall be defined in struct `multiple`, which will also contain boolean value `variable`, which will indicate if Variable Length procedure will be used or not.

### Dependencies

Applications using `bt_gatt_read_params` shall modify it as described in `Detailed RFC` section

**Comment by carlescufi** [comment]
Raised in the API meeting. No objections raised.
