### ISSUE TITLE
ehl_crb: Only boot banner is printed but not the test related details for multiple tests due to PR #36191 is not backported to v2.6.0 release

### ISSUE THREAD

**Issue by yerabolu** [zephyrproject-rtos/zephyr#36565]
**Describe the bug**
PR #36191 is not backported to the V2.6.0 release. Due to the missing fix, after any test is run we get the boot banner but not the test-related details.

What have you tried to diagnose or workaround this issue?

**To Reproduce**
1. twister -W -p ehl_crb --device-testing --device-serial /dev/ttyUSB0 -T tests --west-flash=/home/ztest/EHL_X86_PXE.sh -j 1
2. Boot banner comes up but nothing after that.

**Expected behavior**
Test details need to be displayed after the zephyr boot banner.

**Impact**
Multiple tests have the same issue and the pass rate for EHL_CRB comes down.

**Logs and console output**
```
DEBUG   - DEVICE: NBP filename is zephyr.efi
DEBUG   - DEVICE: NBP filesize is 6539951 Bytes
DEBUG   - DEVICE: Downloading NBP file...
DEBUG   - DEVICE:
DEBUG   - DEVICE: NBP file downloaded successfully.
DEBUG   - DEVICE: *** Zephyr EFI Loader ***
DEBUG   - DEVICE: Zeroing 23871488 bytes of memory at 0x12d000
DEBUG   - DEVICE: Copying 32768 data bytes to 0x1000 from image offset
DEBUG   - DEVICE: Copying 184320 data bytes to 0x100000 from image offset 32768
DEBUG   - DEVICE: Copying 6316576 data bytes to 0x17f1000 from image offset 217088
DEBUG   - DEVICE: Jumping to Entry Point: 0x112b (48 31 c0 48 31 d2 48)
DEBUG   - DEVICE: *** Booting Zephyr OS build zephyr-v2.6.0-119-g5719e545af4d
```
**Environment (please complete the following information):**
 - OS: Fedora
 - Toolchain: SDK 12.4
 - Zephyr v2.6.0 - commit: 79a6c07536bc14583198f8e3555df6134d8822cf

**Comment by nashif** [comment]
PR backported to 2.6 and merged
