### ISSUE TITLE
ESP32 adds support for OTA

### ISSUE THREAD

**Issue by maweicoltsmart** [zephyrproject-rtos/zephyr#36580]
I want ESP32 to download firmware and upgrade via HTTP. Is there any plan to support OTA?

**Comment by rftafas** [comment]
We have a draft on MCUBoot support: https://github.com/mcu-tools/mcuboot/pull/1032

It should be possible to do HTTP update when that gets done.

**Comment by maweicoltsmart** [comment]
Great, I just want to update the firmware via HTTP.

--------------原始邮件--------------
发件人："Ricardo F Tafas Jr ***@***.***&gt;;
发送时间：2021年6月30日(星期三) 晚上9:45
收件人："zephyrproject-rtos/zephyr" ***@***.***&gt;;
抄送："maweicoltsmart ***@***.***&gt;;"Author ***@***.***&gt;;
主题：Re: [zephyrproject-rtos/zephyr] ESP32 adds support for OTA (#36580)
-----------------------------------

 

 
We have a draft on MCUBoot support: mcu-tools/mcuboot#1032
 
It should be possible to do HTTP update when that gets done.
