### ISSUE TITLE
nrf5 ieee802154 driver does not compile and breaks CI

### ISSUE THREAD

**Issue by aurel32** [zephyrproject-rtos/zephyr#36713]
Following merge of PR #36008, the commit bde592e91aa0e797429a61e6754d06e578c80d7a breaks CI, as the `IEEE802154_CONFIG_ENH_ACK_HEADER_IE` case now appears twice.

It seems a similar code with minor differences has already been committed as part of PR #36455.

**Comment by edmont** [comment]
Thanks for warning!

**Comment by ppryga** [comment]
It breaks also this PR https://github.com/zephyrproject-rtos/zephyr/pull/36705

**Comment by edmont** [comment]
Fixed by https://github.com/zephyrproject-rtos/zephyr/pull/36746

**Comment by aurel32** [comment]
Fixed by #36746
