### ISSUE TITLE
Enable "template repository" for zephyrproject-rtos/example-application

### ISSUE THREAD

**Issue by beriberikix** [zephyrproject-rtos/zephyr#36711]
Sorry for posting this here but https://github.com/zephyrproject-rtos/example-application doesn't have issues enabled. Github has a nice feature that enables copying template repos in one click (see [here](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/creating-a-template-repository).) It simply needs to be enabled by someone with admin rights.

**Comment by nashif** [comment]
done

**Comment by beriberikix** [comment]
Thanks!
