### ISSUE TITLE
The road to a stable Controller Area Network driver API

### ISSUE THREAD

**Issue by henrikbrixandersen** [zephyrproject-rtos/zephyr#36724]
The Controller Area Network driver API was introduced in Zephyr v1.14 but it is still marked as experimental here two years after.

This issue is intended to track the changes and actions required to get to the point where we can declare the CAN driver API as stable:

- [x] #36723
- [x] #26541
- [x] #19502
- [x] #21010
- [x] #40912
- [x] #43048
- [x] Review and document all test suites, ensure 100% code coverage:
  - [x] #43542
  - [x] #44197
  - [x] #44233
  - [x] #44293
  - [x] #44351
  - [x] #44429
  - [x] #44362
  - [x] #44505
  - [x] #44498
  - [x] #44508
  - [x] #44688
  - [x] #44681
  - [x] #44567
  - [x] #44838
- [x] #45303
- [x] #48941
- [x] #45304
- [ ] #53445 (see [requirements](https://docs.zephyrproject.org/latest/reference/api/api_lifecycle.html#stable))

**Comment by kentindell** [comment]
I'd just like to point out that eliminating priority inversion isn't an "enhancement": priority inversion is a dangerous flaw in a real-time system. When it is in CAN drivers, the latency of an urgent message can grow hugely from a few hundred microsecond to hundreds of milliseconds, and it can do this unpredictably, leading to Heisenbugs that cannot be replicated in a test environment.

This has already happened - on Mars. And for systems that are intended to be used with safety critical applications it must be fixed, even if that comes at the expense of average case performance.

**Comment by henrikbrixandersen** [comment]
> I'd just like to point out that eliminating priority inversion isn't an "enhancement"

You are quite right. I have removed the enhancement label from this meta issue. I agree that this bug needs fixing.

**Comment by alexanderwachter** [comment]
@kentindell you are right. We are working hard on this topic. The API change will include a rework of the send API call that makes it context based without any limits of buffers. Not sure about the ETA tough.
Thanks again for pointing out this bug! For me it was not obvious that we have a problem there.
