### ISSUE TITLE
Adding Board Support for STEVAL-STWINKT1B

### ISSUE THREAD

**Issue by EminYagmahan** [zephyrproject-rtos/zephyr#36747]
To improve my experience with Zephyr, I plan to add support for the following eval kit from STMicroelectronics to the already existing hardware platform:

https://www.st.com/en/evaluation-tools/steval-stwinkt1b.html

I have already been able to find templates under zephyr/doc/templates/. Under zephyr/boards/arm/ I have not been able to find the board so far, issues or pull requests do not exist either. My approach would be as follows:
1) create a DTS file for the board (zephyr/dts/arm/st/l4/).
2) A DTS file for the processor already exists. I would check it for completeness and correctness as well as I can.
3) A Hello World sample, pictures and documentation.

Are there any other points to consider? I will probably not be able to provide continuous support.

**Comment by erwango** [comment]
@EminYagmahan Thanks for your interest.

I suggest to adapt from following board that should be close to the STWIN kit:
https://github.com/zephyrproject-rtos/zephyr/tree/main/boards/arm/sensortile_box.

Aside from the suggested points, please take care of providing a method to flash & debug.
Also, don't hesitate to enable various peripherals when they reuse existing drivers or components.
For such a board, that would be a shame to restrict to hello_world (of course this can be done in several steps depending on your time)
