### ISSUE TITLE

tests-ci :kernel.tickless.concept.tickless_slice : test failed


### ISSUE THREAD

**Issue by hakehuang** [zephyrproject-rtos/zephyr#36766]
**Describe the bug**
kernel.tickless.concept.tickless_slice test is failed on zephyr-v2.6.0-734-gc1cff7558928 on mimxrt1170_evk_cm7

see logs for details

**To Reproduce**
1. 
```
scripts/twister --device-testing --device-serial /dev/ttyACM0 -p mimxrt1170_evk_cm7  --sub-test kernel.tickless
```
2. See error

**Expected behavior**
test pass

**Impact**

**Logs and console output**
```
*** Booting Zephyr OS build zephyr-v2.6.0-734-gc1cff7558928  ***
Running test suite tickless_concept
===================================================================
START - test_tickless_sysclock
time 10, 8600
time 8610, 17200
PASS - test_tickless_sysclock in 4.267 seconds
===================================================================
START - test_tickless_slice
elapsed selapsed slice 4290, expected: <100, 110>
Assertion failed at WEST_TOPDIR/zephyr/tests/kernel/tickless/tickless_concept/src/main.c:58: thread_tslice: t <= SLICE_SIZE_LIMIT is false
elapsed slice 4300, expected: <100, 110>
Assertion failed at WEST_TOPDIR/zephyr/tests/kernel/tickless/tickless_concept/src/main.c:58: thread_tslice: t <= SLICE_SIZE_LIMIT is false
elapsed slice 0, expected: <100, 110>
Assertion failed at WEST_TOPDIR/zephyr/tests/kernel/tickless/tickless_concept/src/main.c:56: thread_tslice: t >= SLICE_SIZE is false
lice 8600, expected: <100, 110>
Assertion failed at WEST_TOPDIR/zephyr/tests/kernel/tickless/tickless_concept/src/main.c:58: thread_tslice: t <= SLICE_SIZE_LIMIT is false
FAIL - test_tickless_slice in 4.228 seconds
===================================================================
Test suite tickless_concept failed.
===================================================================
PROJECT EXECUTION FAILED

    
```

**Environment (please complete the following information):**
 - OS: (e.g. Linux )
 - Toolchain (e.g Zephyr SDK)
 - Commit SHA or Version used: zephyr-v2.6.0-734-gc1cff7558928

**Comment by hakehuang** [comment]
@mmahadevan108 is thickless support in 1170?

**Comment by mmahadevan108** [comment]
It should be as this is the default setting in Zephyr

**Comment by MaureenHelm** [comment]
I attempted to bisect but found that the test fails at the commit when the board was first introduced.

I suspect there is overflow problem due to the fast system clock (996 MHz). The test passes if I set `CONFIG_SYS_CLOCK_TICKS_PER_SEC=200`

```
$ west build -p auto -b mimxrt1170_evk_cm7 -T kernel.tickless.concept tests/kernel/tickless/tickless_concept -- -DCONFIG_SYS_CLOCK_TICKS_PER_SEC=200
```

**Comment by danieldegrasse** [comment]
@dleach02 The RT1170 was switched over to the GPT as a clock source by #39449, so the issue with the frequency of systick shouldn't be present anymore. The test is passing on my RT1170 EVK now. I think we can close this issue if you are alright with that.

**Comment by dleach02** [comment]
@hakehuang, can you confirm if this is still an open issue in your test range?
