### ISSUE TITLE
Bluetooth Require paired after disconnected work with iphone

### ISSUE THREAD

**Issue by sam131208** [zephyrproject-rtos/zephyr#36764]
I am test the `zephyr\samples\bluetooth\peripheral_hids` project, we don't need input passkey while paired, so remove the function `bt_conn_auth_cb_register(&auth_cb_display)`. It's work fine with android.
But, the iphone will require paired while reconnecting after disconnected.

**Comment by cfriedt** [comment]
Can you provide more information such as the board / platform that this was tested on?

**Comment by cfriedt** [comment]
Closed due to inactivity
