### ISSUE TITLE
source_periph incorrectly set in dma_stm32

### ISSUE THREAD

**Issue by benediktibk** [zephyrproject-rtos/zephyr#36781]
**Describe the bug**
The flag source_periph seems to be incorrectly set in dma_stm32:
https://github.com/zephyrproject-rtos/zephyr/blob/0ef77d4ea41fb765061c64896b3fbd0b2e4bc276/drivers/dma/dma_stm32.c#L418

**To Reproduce**
None, did not cause an issue for me yet. I just stumbled upon it whilst debugging.

**Expected behavior**
I suppose correct would be:
`stream->source_periph = stream->direction == PERIPHERAL_TO_MEMORY;`

**Additional context**
Don't get me wrong, I'm not a 100% sure about this one. But considering the usages of this flag I suppose it is set incorrectly at the moment.

**Comment by FRASTM** [comment]
Correct, this is written in the wrong way even no config was found to prove it.
