### ISSUE TITLE
i2c_samd0.c burst write not compatible with ssd1306.c

### ISSUE THREAD

**Issue by Tubbles** [zephyrproject-rtos/zephyr#36857]
Running Zephyr with a SSD1306 compatible OLED screen does not work over I2C

I am running with a [seeeduino xiao](https://wiki.seeedstudio.com/Seeeduino-XIAO/) and its accompanying [dev kit](https://wiki.seeedstudio.com/Seeeduino-XIAO-Expansion-Board/) which features a SSD1306 compatible 128x64 pixels OLED screen, accessed over the I2C bus.

Comparing with a similar library from the Arduino ecosystem I saw that the I2C packets of Zephyr was incorrectly chopped up into smaller chunks. I tracked it down and it seems that it comes from the usage of `i2c_burst_write()`, but I don't know what is the supposed behavior of the I2C driver. Is it okay for it to inject STOP conditions between each I2C message? There is a warning in the header file which seems to indicate that it is.

**To Reproduce**
1. checkout the below zephyr version
2. apply the changes in the below attached patch (except the one for the ssd1306.c file which contains a workaround)
3. unpack blinken.zip below
4. `west build -b seeeduino_xiao`
5. `west flash`
6. See error

**Expected behavior**
A stripey pattern on the display

**Impact**
Showstopper for any application using this driver combo (and possibly others with the ssd1306?)

**Logs and console output**
Expected comms:
![image](https://user-images.githubusercontent.com/2370561/125139088-2f0c6580-e110-11eb-8e88-2a7d923c385f.png)

Actual comms:
![image](https://user-images.githubusercontent.com/2370561/125139047-19973b80-e110-11eb-9bd9-70b3e0f47de4.png)

**Environment (please complete the following information):**
 - Manjaro Linux
 - zephyr-v2.6.0-740-gc32a96af6ade

**Additional context**
[0001-seeduino-xiao-add-i2c-support-fix-ssd1306-burst-writ.patch.txt](https://github.com/zephyrproject-rtos/zephyr/files/6794058/0001-seeduino-xiao-add-i2c-support-fix-ssd1306-burst-writ.patch.txt)
[blinken.zip](https://github.com/zephyrproject-rtos/zephyr/files/6794100/blinken.zip)

**Comment by jfischer-no** [comment]
This is not a ssd1306 controller driver issue but i2c_samd0.c driver bug/incompatibility.

**Comment by Tubbles** [comment]
> This is not a ssd1306 controller driver issue but i2c_samd0.c driver bug/incompatibility.

Is there some more specification anywhere on how the API implementer is supposed to handle this situation? If it is a bug, we need to fix the driver; on the other hand, if its an incompatibility, we need to change what API we are using..

**Comment by carlescufi** [comment]
@Tubbles there is a lengthy discussion regarding i2c burst writes in [this PR](https://github.com/zephyrproject-rtos/zephyr/pull/34066). If your issue is similar to this maybe you want to weigh in there.

**Comment by rustypig91** [comment]
> This is not a ssd1306 controller driver issue but i2c_samd0.c driver bug/incompatibility.
Stumbled across the same issue with ssd1306 and seeeduino xiao
This is my fix https://github.com/rustypig91/zephyr/commit/2b98cfb2bcb98662736e4ed35bdf75314e763bc1

**Comment by dstahlke** [comment]
@rustypig91 This fix works for me, for both the Adafruit OLED FeatherWing (SH1107) and the common 0.96" OLED breakout board (SSD1306?).  Very nice work - it took way too much time to debug this to the point where I found this ticket.  Could you submit a pull request for this?

**Comment by dstahlke** [comment]
i2c_burst_write does have a warning saying it's not portable and doesn't work correctly on some devices.  It'd be nice if ssd1306.c could use i2c_transfer instead.

Looking through the code, it appears this would be easy to do for all the command buffers (just prepend the command byte), but for ssd1306_write would not be so easy because the data comes from a user-supplied buffer.

**Comment by dstahlke** [comment]
Relevant issues: #20154 #33606

**Comment by Tubbles** [comment]
> This fix works for me, for both the Adafruit OLED FeatherWing (SH1107) and the common 0.96" OLED breakout board (SSD1306?).

What processor are you using?

**Comment by dstahlke** [comment]
@Tubbles ATSAMD21G18, on the Adafruit Feather M0 Basic board.

**Comment by rustypig91** [comment]
#38482 created
