### ISSUE TITLE
Static object constructors execute twice on the NATIVE_POSIX target

### ISSUE THREAD

**Issue by palchak-google** [zephyrproject-rtos/zephyr#36858]
**Describe the bug**
All C++ global object constructors are executed twice upon startup of a NATIVE_POSIX executable. This breaks code that relies upon constructor side effects (such as registering unit tests with a test framework).

**To Reproduce**
1. Create a trivial C++ application with the following `main.cc`:
```
#include <string>
#include <iostream>

struct SideEffectConstructor {
    SideEffectConstructor(std::string s) {
        std::cerr << "Constructing " << s << std::endl;
    }
};

static auto object_a = SideEffectConstructor{"Object A"};
static auto object_b = SideEffectConstructor{"Object B"};
static auto object_c = SideEffectConstructor{"Object C"};
static auto object_d = SideEffectConstructor{"Object D"};

void main() {
    exit(0);
}
```

2. Build the application for the `native_posix` target.
3. Execute the application.
4. Observe the following console output:
```
Constructing Object A
Constructing Object B
Constructing Object C
Constructing Object D
*** Booting Zephyr OS build v2.4.99-ncs2  ***
Constructing Object A
Constructing Object B
Constructing Object C
Constructing Object D
```

**Expected behavior**
The following lines should be printed to the terminal exactly once:
```
Constructing Object A
Constructing Object B
Constructing Object C
Constructing Object D
```

**Impact**
This bug results in a major discrepancy between the behavior of code running on the `native_posix` board and the behavior of that same code running on physical board. This bug also interferes with the use of common unit test frameworks that rely on auto-registration of tests via global object constructors.

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: Host g++ (v10.2.1)
 - Zephyr version v2.4.99-ncs2 (NRF Connect SDK v1.5.1)

**Additional context**
It was discovered that this problem not occur if `CONFIG_CPLUSPLUS` is unset the `prj.conf` file and instead `CONFIG_CPLUSPLUS` is defined directly in `CMakeLists.txt`:
```
set(CONFIG_CPLUSPLUS 1)
```

This is obviously not the recommended way to go about enabling build support for C++. However, it's interesting that doing this results in the correct behavior (i.e. global constructors only run once).

**Comment by alexanderwachter** [comment]
Ping @stephanosio @aescolar
