### ISSUE TITLE
make existing gpio_pin_configure_dt() to configure interrupt  seamlessly from DT info, if interrupt related config found

### ISSUE THREAD

**Issue by manoj153** [zephyrproject-rtos/zephyr#36904]
**Is your enhancement proposal related to a problem? Please describe.**
Not a problem, but rather an enhancement/suggestion

**Describe the solution you'd like**
I think it is doable and nice to have that the existing `gpio_pin_configure_dt()`  configures interrupt. 
as long the DT_FLAGS are agreeing and bits are not unique to their sole function  
This will allow such possibility in device tree definition :
```
  gpios = <&gpioe 7 (GPIO_ACTIVE_HIGH | GPIO_INT_EDGE_BOTH)>
```

**Describe alternatives you've considered**
current way of doing is explicitly running `gpio_pin_interrupt_configure_dt()`  upon `gpio_pin_configure_dt()` and passing the level information from source code
**Additional context**
 A checking can take place in `gpio_pin_configure_dt()` on DT_FLAG , if interrupt level flag is **found** this API could help to configure interrupts. I felt this would allow the user to config edge level without touching the source code.

**Comment by henrikbrixandersen** [comment]
The GPIO interrupt flags such as `GPIO_INT_EDGE_BOTH` are not DT flags but rather flags set up by the driver. While this may seem like an odd limitation, configuring the interrupt flags is really a driver task and should not be done in the hardware description (DTS). It is the driver registering for GPIO interrupts that knows how the nature of the device generating those interrupts.
