### ISSUE TITLE
LWM2M: Writing to Write-Only resource causes notification

### ISSUE THREAD

**Issue by huelsenfruchtzwerg** [zephyrproject-rtos/zephyr#36927]
**Describe the bug**
Writing to any ressource that's declared as writable only triggers a notification, i.e. if the containing object is observed.

**Expected behavior**
Writing to non-readable ressources should not trigger a notification. At least that's how Leshan implements it (... I'm told)

**Impact**
Unnecessary Trafic/Power-Consumption

**Environment (please complete the following information):**
Nordic Connect SDK 2.6.0, nrf9160

**Comment by rlubos** [comment]
I agree, it doesn't make much sense to send a notification if there are no new data to notify. I'll send a patch.

**Comment by rlubos** [comment]
@huelsenfruchtzwerg Please have a look at https://github.com/zephyrproject-rtos/zephyr/pull/36984, it was actually a pretty simple fix. Feel free to approve if it works ok for you.
