### ISSUE TITLE
drivers: sensor: sensor_value_to_double requieres non const sensor_value pointer

### ISSUE THREAD

**Issue by helo9** [zephyrproject-rtos/zephyr#37029]
When `const struct sensor value * ` is given, a pointer cast is needed to get rid of the `const`
qualifier e.g., you want to set an attribute given as `sensor_value`.

As I would not expect `sensor_value_to_double` to change the value of its parameter anyways,
I would propose to add the `const` qualifier there:
```
static inline double sensor_value_to_double(const struct sensor_value *val)
```

**Comment by gmarull** [comment]
Would you mind opening a PR?
