### ISSUE TITLE
zephyr_prebuilt.elf and zephyr.elf has inconsistent symbol address in RISC-V platform

### ISSUE THREAD

**Issue by cwshu** [zephyrproject-rtos/zephyr#37023]
**Describe the bug**
This bug occurs on `tests/kernel/mem_protect/obj_validation` test on `qemu_riscv32` platform with userspace enabled. [1]
The `sem1` symbol has different address in `zephyr_prebuilt.elf` and `zephyr.elf`, which causes object validation failed.

```
> nm -n zephyr/zephyr_prebuilt.elf | grep sem1
80015070 D sem1

> nm -n zephyr/zephyr.elf | grep sem1
80015074 D sem1
```

The difference of 2 ELF file is `_thread_idx_map` symbol. 

- It is at `.kobject_data` section in `zephyr_prebuilt.elf`
- It is at `.data `section in `zephyr.elf`, so it shifts 4 bytes to all symbols after it in `zephyr.elf`. 
- In ARM platform, `_thread_idx_map` symbol is at `.kobject_data` section in `zephyr.elf`.

Compared RISC-V platform to ARM, the `_thread_idx_map` in RISC-V platform is at `.sdata` section instead of `.data` section in `kobject_hash.c.obj`, so the `.sdata` section symbols aren't changed to `.kobject_data.*` section in `kobject_hash_renamed.o` (by renaming section) and isn't placed to `.kobject_data` output section in zephyr.elf.

This issue also occurs on `hifive1_revb`, if enlarging memory size twice to avoid RAM overflow.
(enlarge dtim size from 0x4000 to 0x8000 in `dts/riscv/riscv32-fe310.dtsi`)

[1] Enable userspace in qemu_riscv32
```
# soc/riscv/riscv-privilege/virt/Kconfig.series add
select ARCH_HAS_USERSPACE if RISCV_PMP

# boards/riscv/qemu_riscv32/qemu_riscv32_defconfig add
CONFIG_RISCV_PMP=y
CONFIG_PMP_POWER_OF_TWO_ALIGNMENT=y
CONFIG_PMP_SLOT=16
```

Related to #31811

**To Reproduce**
1. Enable userspace in `qemu_riscv32`
2. build `tests/kernel/mem_protect/obj_validation`
3. check `sem1` symbol in zephyr_prebuilt.elf and zephyr.elf

**Expected behavior**
`sem1` symbol has same address in zephyr_prebuilt.elf and zephyr.elf

**Impact**
RISC-V userspace get failed in object validation.

**Environment (please complete the following information):**
Zephyr 2.6.99

**Comment by dcpleung** [comment]
Already has a PR pending.
