### ISSUE TITLE
document: API reference missing: In clock of zephyr document

### ISSUE THREAD

**Issue by KangJianX** [zephyrproject-rtos/zephyr#37032]
In the latest document of Zephyr, the chapter of API reference -> Kernel Services -> Kernel Timing, in this chapter, it does not have API reference to introduce the APIs what is invoked at concept part.

**Comment by cfriedt** [comment]
It's possible that links are not working in the latest documentation (possibly earlier) on this page.

https://docs.zephyrproject.org/latest/reference/kernel/timing/clocks.html?highlight=kernel%20timing

Also compared to below, the API doc at the bottom of the page is missing.
https://docs.zephyrproject.org/2.0.0/reference/kernel/timing/clocks.html
