### ISSUE TITLE
PlatformIO: i cannot use the Wifi Shield ESP8266 to build the sample wifi project with the Nucleo F429ZI

### ISSUE THREAD

**Issue by moncef-bibani** [zephyrproject-rtos/zephyr#37075]
**Describe the bug**
I want to build a wifi sample with nucleo_f439zi with esp_8266 as Wi-Fi shield on virtual studio code using PlatformIO. When i use west in the console on linux. i use this command "west build -b nucleo_f429zi samples/net/wifi -- -DSHIELD=esp_8266"                    

But  in PlatformIO,  i don't have the possibility to add this parameter for the Wi-Fi shield.  Do you know how to add this parameter for build options in PlatformIO ?
I tried in the platformio.ini, and I added this parameter "build_flags= -DSHIELD = esp_8266" but it's still not working...

**Impact**
the Nucleo F429ZI Board is trying to use the network interface (Ethernet port) for the Wi-Fi sample project and not the Wi-Fi shield ESP8266.

**Logs and console output**
![image](https://user-images.githubusercontent.com/82579384/126323980-08550122-51c6-4719-bb99-d0a8d7cdf21f.png)

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain  Zephyr SDK, Visual Studio Code, PlatformIO

**Comment by cfriedt** [comment]
Please report to the platformio github project, as we do not support specifying build flags on the command line in that fashion yet.
