### ISSUE TITLE
Zephyr POSIX layer uses swapping with an interrupt lock held

### ISSUE THREAD

**Issue by evgeniy-paltsev** [zephyrproject-rtos/zephyr#37109]
Zephyr POSIX layer actively uses swapping with an interrupt lock held.

According to @andyross ([link](https://github.com/zephyrproject-rtos/zephyr/issues/36736#issuecomment-875945758))

> THAT we need to get fixed ASAP. It really should just never happen, it was a quirk about the old API that we'd like to deprecate if possible.

Such mechanism is used (at least) in 

- lib/posix/pthread_cond.c
- lib/posix/pthread_mutex.c
- lib/posix/pthread_barrier.c

and rest of POSIX code relies on the APIs implemented in these files.

Here is an example of code using swapping with an interrupt lock held (in `lib/posix/pthread_cond.c`)

```
int pthread_cond_signal(pthread_cond_t *cv)
{
	int key = irq_lock();

	_ready_one_thread(&cv->wait_q);
	z_reschedule_irqlock(key);

	return 0;
}
```

The swapping with an interrupt lock held is broken and problems with it were discussed in #36736

**Comment by andyross** [comment]
Drop this one to medium.  While I agree that this is an important issue to get fixed, it's not actually a "bug" as it doesn't misbehave currently for correct code (if you're using POSIX calls, you shouldn't be in an irq_lock() context by definition).   Project management gets messy if we put a high on everything, basically.  High needs to be for things that block deployment of correct code.
