### ISSUE TITLE
nucleo-f756zg: rtos aware debugging not working

### ISSUE THREAD

**Issue by maksimdrachov** [zephyrproject-rtos/zephyr#37175]
**Describe the bug**

In [this](https://www.youtube.com/watch?v=jR5E5Kz9A-k) video (50:30) it is shown how to debug a reel-board using gdb.

**To Reproduce**
The following commands are issued:
```
cd zephyr/samples/philosophers
west build -b nucleo_f756zg
west build --target guiconfig (set OPENOCD support)
west debug
(gdb) c
```
Output looks fine
![output_normal](https://user-images.githubusercontent.com/39975120/126816493-14c36bf5-9fbb-424d-b165-3c55312a568b.png)

If I interrupt, it looks like this, seemingly no threads detected by gdb?
![my_threads_output](https://user-images.githubusercontent.com/39975120/126816636-6adb89f4-2494-446a-a102-c8e40b09f3bb.png)

**Expected behavior**
However I'm expecting something like this (as shown in the video)
![video_threads_output](https://user-images.githubusercontent.com/39975120/126816775-c1de8edb-a00f-45db-b034-7b76220f30d3.png)

I've checked my Konfig, but the problem remains.
![kernel_config_1](https://user-images.githubusercontent.com/39975120/126818212-eda9f330-7a9e-476c-83d3-cee3331501ba.png)

**Impact**
I can't really start developing with Zephyr.

**Environment (please complete the following information):**
 - OS: MacOS
 - Board: Nucleo-F756ZG
 - Commit SHA: f3d9808012

**Comment by erwango** [comment]
@maksimdrachov Thread awareness support was only merge relatively recently in openocd (http://openocd.zylin.com/#/c/4988/).
Can you check you're using a version that embed this patch ?

**Comment by maksimdrachov** [comment]
Hmm you're right

Upgraded openocd to the latest commit:
![openocd-vers](https://user-images.githubusercontent.com/39975120/126977415-951a2576-d12e-486c-9727-017323557300.png)

I've removed the previous install to make sure there was no chance of the older version being used. Used the following commands:
```
brew uninstall openocd
brew install openocd --HEAD
```

Serial output seems to be working as expected:
![serial](https://user-images.githubusercontent.com/39975120/126977713-831770ae-a7aa-4ddb-816b-8d1b45941afe.png)

However the same issue remains:
![gdb-info-threads](https://user-images.githubusercontent.com/39975120/126978377-fb983e0e-36b9-4db5-89f6-13ae8b027265.png)

Any other suggestions?
Should I take this to openocd?
Are there any tools you could recommend that work with STM32 and Zephyr?

**Comment by erwango** [comment]
@maksimdrachov Ok, thanks for having had a try. I'll have a check on my side as well.
As an alternative, you should be able to use pyocd.
Also, you could use Segger, but please note that it currently dos not work for some targets, so I'd not advise it right now.

**Comment by erwango** [comment]
@maksimdrachov One additional piece of info:
In the video you mention, pycocd is the debugger in use.

For openocd, one additional config can be required (to be added in <board>/support/openocd.cfg)
```
# Enable Zephyr thread awareness.
$_TARGETNAME configure -rtos Zephyr
```
But I've not been able to test yet.

**Comment by maksimdrachov** [comment]
Ok, I'll try to test 👍

**Comment by maksimdrachov** [comment]
It works! Big thanks!

The proposed (working) solution can be seen in the screenshot below:
![solution](https://user-images.githubusercontent.com/39975120/126994288-c983f222-1cab-4c13-a4f3-d4cfd77bbe2f.png)

**Comment by erwango** [comment]
ok, great. We need need to set this by default. I'll raise an issue for that.

**Comment by erwango** [comment]
@maksimdrachov I'm closing current issue.
