### ISSUE TITLE
Get an error  of "Illegal load of EXC_RETURN into PC" when print log in IO interrupt callback

### ISSUE THREAD

**Issue by ThisSummerRace** [zephyrproject-rtos/zephyr#37188]
**Describe the bug**
What have you tried to diagnose or workaround this issue?
I print log both in the UART callback function and  IO interrupt callback function , unless remove the log in  IO interrupt callback, it will get the error of "Illegal load of EXC_RETURN into PC" sometimes.
**To Reproduce**
1. mkdir build; cd build
2. cmake -DBOARD=board\_xyz
3. make

**Expected behavior**

**Impact**
What impact does this issue have on your progress (e.g., annoyance, showstopper)

**Logs and console output**
If applicable, add console logs or other types of debug information
e.g Wireshark capture or Logic analyzer capture (upload in zip archive).
copy-and-paste text and put a code fence (\`\`\`) before and after, to help
explain the issue. (if unable to obtain text log, add a screenshot)

**Environment (please complete the following information):**
 - OS: (e.g. Linux, MacOS, Windows)
 - Toolchain (e.g Zephyr SDK, ...)
 - Commit SHA or Version used

**Additional context**

**Comment by carlescufi** [comment]
@ThisSummerRace you'll need to be a bit more specific here. What are you using exactly for logging? What board can you reproduce this with? Which sample?

**Comment by ThisSummerRace** [comment]
> @ThisSummerRace you'll need to be a bit more specific here. What are you using exactly for logging? What board can you reproduce this with? Which sample?

1、I use the  RTT for logging
2、I do the sample with homekit,not a standard sample on zephyr source code.

**Comment by cfriedt** [comment]
@ThisSummerRace - please reopen the issue if you can provide something reproducible with minimal changes to an upstream sample or test case. We currently do not have enough information to verify that this is a bug let alone triage it.

E.g. if you were to provide a `.patch` file for some upstream test or sample application and provide something like.
```
west build -b qemu_cortex_a53 -t run samples/foo/bar
```

Also, please fill in fields such as the toolchain, OS, and commit sha
