### ISSUE TITLE
mcumgr: Probably incorrect error handling with udp backend

### ISSUE THREAD

**Issue by emob-nordic** [zephyrproject-rtos/zephyr#37193]
In case there is no free space for mcumgr buffer, received data are probably
inproperly dropped [smp_udp.c:114-127](https://github.com/zephyrproject-rtos/zephyr/blob/main/subsys/mgmt/mcumgr/smp_udp.c#L114:L127).

For more information refer to:
https://github.com/zephyrproject-rtos/zephyr/issues/37105
https://github.com/zephyrproject-rtos/zephyr/pull/37081

**Comment by carlescufi** [comment]
@emob-nordic are you looking into this?

**Comment by emob-nordic** [comment]
@carlescufi I'm not. I was told in the past to write this issue so someone competent could address it later.

**Comment by carlescufi** [comment]
@aunsbjerg could you please take a look at this issue?

**Comment by aunsbjerg** [comment]
@carlescufi I will try, but am a bit pressed for time, so it will be a few days before I can do anything

**Comment by de-nordic** [comment]
I'll take over. I have idea how to follow with this, although it requires change in mcumgr/lib.

**Comment by nordicjm** [comment]
@de-nordic the file has since moved and changed, what parts are wrong in the UDP handling?

**Comment by nordicjm** [comment]
It is assumed that this is a duplicate of https://github.com/zephyrproject-rtos/zephyr/issues/44536 whereby if there are insufficient buffers to receive the command, no error response is sent.
