### ISSUE TITLE
improve docs with diagram for boot flow of ACRN on x86 ehl_crb

### ISSUE THREAD

**Issue by jenmwms** [zephyrproject-rtos/zephyr#37212]
**Is your enhancement proposal related to a problem? Please describe.**
The boot flow of the virtualized platform on Elkhart Lake (acrn_ehl__crb) is slightly different than native (ehl_crb).  

**Describe the solution you'd like**
Simple diagram to demonstrate and describe the differences, such as stages and padding, etc.

**Describe alternatives you've considered**
A high-level diagram of boot flow on ehl_crb and highlight where the differences are in that flow with callout to source-level documentation for more information.

**Comment by andyross** [comment]
*(Doing a grooming pass on bugs/issues that are sitting around with my name on or near them.  No one pays me right now so I get to be an unaccountable whirlwind of chaos!)*

Closing.  More docs are always good, but the ACRN support has been stable(-ish) for a while now and to the extent it's being exercised no one seems to be confused.  Also note that the ACRN project themselves have excellent documentation of the configuration/boot/init flow.  I don't see a big need for us to try to duplicate that absent demand from users.
