### ISSUE TITLE
stm32l4 System Power Management issue

### ISSUE THREAD

**Issue by ivonalo** [zephyrproject-rtos/zephyr#37270]
### Discussed in https://github.com/zephyrproject-rtos/zephyr/discussions/37269

<div type='discussions-op-text'>

<sup>Originally posted by **ivonalo** July 28, 2021</sup>
I am using the system PM on the stm32l4 board because I want to use the `pm_power_state_set` function to put the stm32l4 into `stop2_mode` but only after certain conditions are fulfilled. So, the idea is that after turning on, the stm32l4 is in active state (PM_STATE_ACTIVE) and stays in active state. Only when certain conditions are fulfilled, I want to call the `pm_power_state_set` function to put in some other PM state.

As I understood, when CONFIG_PM is enabled I can implement my own power management policy, and my policy would be when turned on go to  PM_STATE_ACTIVE and stay there as long as I don't tell you to go to some other state.

In prj.conf I  have enabled following things:
CONFIG_PM=y
CONFIG_SOC_LOG_LEVEL_DBG=y
CONFIG_PM_LOG_LEVEL_DBG=y
CONFIG_IDLE_STACK_SIZE=8192
CONFIG_PM_POLICY_APP=y

My policy handler is very simple:
```
struct pm_state_info pm_policy_next_state(int ticks)
{
	LL_LPM_DisableSleepOnExit();

	return (struct pm_state_info){ PM_STATE_ACTIVE, 0, 0 };
}
```
The problem I have, is that after turning on, my stm32l4 after few seconds just stops working, I don't get anything on the serial output anymore and it seems like it is in some deep sleep mode because it is totally unresponsive. In my main.cpp i have forbidden any other state then PM_STATE_ACTIVE, so I don't understand how this can happen:
```
static int disable_ds_1(const struct device *dev) {
  ARG_UNUSED(dev);

  pm_constraint_set(PM_STATE_STANDBY);
  pm_constraint_set(PM_STATE_SOFT_OFF);
  pm_constraint_set(PM_STATE_SUSPEND_TO_IDLE);
  pm_constraint_set(PM_STATE_RUNTIME_IDLE);
  pm_constraint_set(PM_STATE_SUSPEND_TO_DISK);
  pm_constraint_set(PM_STATE_SUSPEND_TO_RAM);

  return 0;
}

SYS_INIT(disable_ds_1, PRE_KERNEL_2, 0);
```

What I also don't understand is that after debugging I see that once I tell the smt32l4 to go to PM_STATE_ACTIVE it still continuously enters the `pm_system_suspend` function, like in a while loop, even though in my main.cpp application it is executing some other functions so it should not go into Idle Thread.

Also, I have tried to use the other two power management policies: Residency and Dummy and it didn't work for me.

Am I missing something or am I totally on the wrong track here?

</div>

**Comment by erwango** [comment]
@ivonalo I'm closing this ticket as there's a discussion open and no clear evidence if this is a bug or incorrect use of the api
