### ISSUE TITLE
k_timer_status_sync can lock forever on qemu_x86_64

### ISSUE THREAD

**Issue by nordic-krch** [zephyrproject-rtos/zephyr#37304]
**Describe the bug**
`hello_world` from this commit https://github.com/nordic-krch/zephyr/commit/be32f10751e850e5f2b55267140ba596f4bb3b3e locks forever on `k_timer_status_sync` on `qemu_x86_64` and works as expected on other qemu platforms.

**To Reproduce**
1. build `hello_world` from https://github.com/nordic-krch/zephyr/commit/be32f10751e850e5f2b55267140ba596f4bb3b3e for `qemu_x86_64`
3. Run and notice that it stops printing after some time.

**Expected behavior**
It should not lock as on other platforms.

**Impact**
Deadlock

**Comment by chen-png** [comment]
this is related to smp, there is a potential timer timeout race condition between multiple cpus.

i.e, on qemu_x86_64, the smp is enabled with two cpus in default.
in the code of sample test, when invoking k_timer_status_sync function, if the timer hasn't been expired, it will invoke z_pend_curr function to make the current thread wait for the timer expired, it will set the current thread state as pending and add it into the timer wait queue.
but **before doing that, the second timeout interrupt of this timer maybe handled by cpu2, at this point, the thread state and timer wait queue have not been updated**, so in the timer expire function, it won't remove thread from timer wait queue and set it as ready. after running over, the cpu2 goes into the idle thread.
when resuming to cpu1 z_pend_curr, it continues to execute to set the current thread state as pending and add it into the timer wait queue, then cpu1 goes  into the idle thread too.

**so the final result is that the two cpus are all in the idle state, the timer is already expired, but the z_main_thread is still pending on the timer,** so the test stops to execute, like below:

**>(gdb) info threads**
  Id   Target Id                    Frame
1    **Thread 1.1 (CPU#0 [halted ]) 0x0000000000101021 in arch_cpu_idle ()** at /home/chenpeng/zephyrproject/zephyr/arch/x86/core/cpuhalt.c:14
  2    **Thread 1.2 (CPU#1 [halted ]) 0x0000000000101021 in arch_cpu_idle ()** at /home/chenpeng/zephyrproject/zephyr/arch/x86/core/cpuhalt.c:14

(gdb) **p *(struct k_timer*)0x114d38**
$1 = {timeout = {node = {{head = 0x0, next = 0x0}, {tail = 0x0, prev = 0x0}}, fn = 0x1035cc <z_timer_expiration_handler>, dticks = 0}, **wait_q = {waitq = {{head = 0x1064c0 <z_main_thread>,**
        next = 0x1064c0 <z_main_thread>}, {tail = 0x1064c0 <z_main_thread>, prev = 0x1064c0 <z_main_thread>}}}, expiry_fn = 0x100001 <timeout>, stop_fn = 0x0, period = {ticks = 0},
  **status = 1**, user_data = 0x0}

**(gdb) p z_main_thread**
$2 = {base = {{qnode_dlist = {{head = 0x114d58 <z_main_stack+8072>, next = 0x114d58 <z_main_stack+8072>}, {tail = 0x114d58 <z_main_stack+8072>, prev = 0x114d58 <z_main_stack+8072>}},
      qnode_rb = {children = {0x114d58 <z_main_stack+8072>, 0x114d58 <z_main_stack+8072>}}}, **pended_on = 0x114d58 <z_main_stack+8072>, user_options = 1 '\001', thread_state = 2 '\002',**
