### ISSUE TITLE
Bluetooth: Host: Support setting long advertising data

### ISSUE THREAD

**Issue by rugeGerritsen** [zephyrproject-rtos/zephyr#37367]
**Is your enhancement proposal related to a problem? Please describe.**
I want to be able to transmit 1650 bytes of advertising data using a single advertiser as supported by a given Bluetooth Controller. Currently the host only supports setting advertising data in one operation. Therefore the maximum advertising and periodic advertising data length is limited to 251 bytes.

**Describe the solution you'd like**
- If the advertising data is longer than 251 bytes, the host shall set the advertising data in multiple steps using the parameter named `operation` in the commands:
  - HCI LE Set Extended Advertising Data (Core_v5.3, Vol 4, Part E, Section 7.8.54)
  - HCI LE Set Extended Scan Response Data (Core_v5.3, Vol 4, Part E, Section 7.8.55)
  - HCI LE Set Periodic Advertising Data (Core_v5.3, Vol 4, Part E, Section 7.8.62)
- Setting more than 251 bytes while advertising shall return an error code as it is not allowed by HCI.

**Comment by cvinayak** [comment]
@rugeGerritsen Add the Fixes with this issue number in the PR so that this issue gets linked and gets closed when the PR is merged.
