### ISSUE TITLE
esp32 build

### ISSUE THREAD

**Issue by mridulzz** [zephyrproject-rtos/zephyr#37400]
i'm getting this error while running west espressif update

FATAL ERROR: cannot find espressif project in $ZEPHYR_BASE path

**Comment by nashif** [comment]
@mridulzz  Can you please provide more details

**Comment by mridulzz** [comment]
I am following https://zephyrproject.org/zephyr-rtos-on-esp32/ steps after west update command when i am using west espressif update i am getting this error

**Comment by sylvioalves** [comment]
@mridulzz This message tells that your `ZEPHYR_BASE` might be incorrect. Can you write what is the value?

**Comment by mridulzz** [comment]
From my understanding west init sets the ZEPHYR_BASEwhen i run west init command it's showing
"FATAL ERROR: already initialized in /home/mycomp/zephyrproject ,aborting.
Note:
    In your environment, ZEPHYR_BASE is set to:
    /home/tosil/zephyr

    This forces west to search for a workspace there.
    Try unsetting ZEPHYR_BASE and re-running this command.
"
And i am working in zephyrproject directory

**Comment by mridulzz** [comment]
The error is due to the "echo ‘export PATH=~/.local/bin:”$PATH”’ >> ~/.bashrc' command .Please correct this line in the documentation of Zephyr RTOS ESP32.I was getting this error 
Command '‘export' not found, did you mean:

  command 'mexport' from deb mblaze

Try: sudo apt install <deb name>

Then i copied the same line from another documentation and it worked.
