### ISSUE TITLE
Allow dual controler on usb 

### ISSUE THREAD

**Issue by bastien-roucaries** [zephyrproject-rtos/zephyr#37409]
Actually it is not possible to enable USB on first and second port of dual port card like the olimex E407 (see https://github.com/zephyrproject-rtos/zephyr/blob/c4079e4be29afd57f6cae431c4b849970eb91dd5/boards/arm/olimex_stm32_e407/olimex_stm32_e407.dts#L93)

It will be nice to enable both usb port for instance for implementing null modem usb cdc wire for debugging purpose

**Comment by jfischer-no** [comment]
Support for multiple USB device controllers is planned, and the new API will be published soon. However, I am closing this issue because the description is not sufficient and only refers to a specific board.
