### ISSUE TITLE
Sensor driver: sht4x, sgp40, invalid include path

### ISSUE THREAD

**Issue by DominusFulguris** [zephyrproject-rtos/zephyr#37454]
The driver source file, "sht4x.c", attempts to include the header file "sht4x.h" twice with the first occurrence from an apparently invalid path:

(Line 18)
#include <drivers/sensor/sht4x.h>

The same thing seems to be true for the sgp40 driver.

The shgp40_sht4x sample application also references this invalid path.

**Comment by gmarull** [comment]
The file exists in `<REPO_ROOT>/include/drivers/sensor/sht4x.h`. Sample also builds fine: `west build -b blackpill_f411ce samples/sensor/sgp40_sht4x`. Closing as this doesn't seem to be a bug.
