### ISSUE TITLE
Bluetooth: Advertising becomes scannable even if BT_LE_ADV_OPT_FORCE_NAME_IN_AD is set

### ISSUE THREAD

**Issue by Thalley** [zephyrproject-rtos/zephyr#37462]
**Describe the bug**
When creating an extended advertiser or just using the `bt_le_adv_start` with the `BT_LE_ADV_OPT_USE_NAME` option, it implicitly makes the advertisements scannable, as it would put the name in the scan response data. 

However, we introduced another option, `BT_LE_ADV_OPT_FORCE_NAME_IN_AD` (https://github.com/zephyrproject-rtos/zephyr/pull/34332), which forces the name to be in the advertising data, but the advertisement will still become scannable, even if the upper layer didn't request it to be. 

**To Reproduce**
N/A

**Expected behavior**
If `BT_LE_ADV_OPT_FORCE_NAME_IN_AD` is set with `BT_LE_ADV_OPT_USE_NAME`, `BT_LE_ADV_OPT_SCANNABLE` isn't set and no scan response data was provided, then the advertisement should not be scannable.

This can be fixed by changing how we determine whether it should be scannable from doing 
```
scannable = param->options & BT_LE_ADV_OPT_USE_NAME;
```
to
```
scannable = (param->options & BT_LE_ADV_OPT_USE_NAME != 0) && (param->options & BT_LE_ADV_OPT_FORCE_NAME_IN_AD == 0);
```

**Impact**
Minor, will just making it scannable without any scan response data. 

**Logs and console output**
N/A

**Environment (please complete the following information):**
 - Commit SHA or Version used: 1c0ed946018e4f1ee4b766d5db811d097f44f2ba

**Additional context**
N/A

**Comment by carlescufi** [comment]
@lairdjm any comments on this one?

**Comment by lairdjm** [comment]
Looks good to me
