### ISSUE TITLE
mcuboot: Booting an image flashed on top of a Hawkbit updated ones results in hard fault

### ISSUE THREAD

**Issue by ycsin** [zephyrproject-rtos/zephyr#37495]
**Describe the bug**

After `hawkbit` downloaded an image and performed a test update, if the device is reset after booted up that test update, for some reason MCUboot doesn't perform swap even though it should, as the image isn't confirmed.

Then if an image is flashed to the `image-0` partition using a hw debugger (Jlink), the MCUboot would think that it needs to `boot_complete_partial_swap`. However, in `boot_swap_image`, the `swap_size` (`copy_size`) from `boot_read_image_size` is likely corrupted?

![image](https://user-images.githubusercontent.com/1563974/128485086-ae8aea7f-5907-402e-a887-3cabeefe7c54.png)

And caused it to hard fault while it finds the last sector in the primary slot that needs swapping in `swap_run`

![image](https://user-images.githubusercontent.com/1563974/128485134-708ecaf1-7170-4b6a-b3ba-3bf18c78f4aa.png)

I'm not sure if this is an expected behavior. To be able to boot an image again, full chip erase is required.

___

**My board**
- STM32G0B1RE custom board
  - `mcuboot` - 64 kiB
  - `image-0` - 416 kiB 
  - Remaining 32 kiB - left blank
- 1 MiB external `spi-nor` flash
  - `image-1` - 416 kiB
  - `scratch` - 140 kiB 
  - Other partitions like `storage`, etc
- `gsm_ppp` LTE modem

**To Reproduce**
1. Flash `hawkbit` sample and OTA upgrade to an image
2. After the OTA upgraded image is booted, flash an image on top using hardware flasher
3. Reset to boot the flashed image
4. See hard fault error

**Expected behavior**
I expect the bootloader to boot the flashed image.

**Impact**
Extra steps required to flash the device using a hardware flasher.

**Environment (please complete the following information):**
 - OS: Windows 10
 - Toolchain: GNUARMEMB
 - v2.6.0-1638-g0296d12675fd

**Comment by ycsin** [comment]
@d3zd3z After few days of testing I've edited the title and narrowed the scope of the problem in the description

**Comment by d3zd3z** [comment]
I'm not exactly sure I'd call it expected behavior, but it is unsurprising. The easiest fix is going to be either 1. erase the entire partition for the primary image slot before flashing the image with the hw tools, or 2. Pass `--pad` to `imgtool.py` (as well as `--slot-size`), which will fill out the entire image, overwriting whatever state is present.

This could indeed be improved, but it is hard to as there is no correlation between the image in the trailer and a given image itself. If a hw tool replaces the image, but not the trailer, it will still behave. Regardless. Fixing this would be an issue on https://github.com/mcu-tools/mcuboot and not really against Zephyr. Feel free to create an issue there if you'd like.

**Comment by d3zd3z** [comment]
I've gone ahead and created #mcu-tools/mcuboot#1116 to track any work on a fix, and I will go ahead and close the issue here on Zephyr.

**Comment by ycsin** [comment]
@d3zd3z Hey, give that my image slot has 448kiB:

```dts
...
		partitions {
			compatible = "fixed-partitions";
			#address-cells = <1>;
			#size-cells = <1>;

			/*
			 * 448 kB slot-1 for DFU
			 * Must be 4 kB aligned
			 */
			slot1_partition: partition@0 {
				label = "image-1";
				reg = <0x0 0x70000>;
			};
...
```

I've added
```conf
CONFIG_MCUBOOT_EXTRA_IMGTOOL_ARGS="--version 1.0.0 --pad --slot-size 458752"
```

in my `prj.conf`, then build and flash like I normally would

```
west build -b gtsb_ivm21 --pristine; west flash --hex-file build\zephyr\zephyr.signed.confirmed.hex
```
but it still results in hardfault, any idea what I'm missing?
