### ISSUE TITLE
wrong documentation format on DMA peripheral API reference

### ISSUE THREAD

**Issue by FRASTM** [zephyrproject-rtos/zephyr#37491]
_Not sure if this is the right place to submit:_

The Zephyr doc page for the **API Reference / Peripherals / DMA / API Reference** is  not well formatted for the struct `dma_block_config` section.

https://docs.zephyrproject.org/latest/reference/peripherals/dma.html is
![zephyr_doc_dma 2021-08-06 09-18-36](https://user-images.githubusercontent.com/51417392/128474944-5f532318-1cd5-4747-83a9-4497b62b852e.png)

**Comment by dleach02** [comment]
@FRASTM can you provide a PR to fix this?

**Comment by FRASTM** [comment]
sure, but i have no idea yet of where it is made/stored/pushed. Is there a repo for this ?

**Comment by dleach02** [comment]
sorry for the delay. These are extracted from the doxygen style comments in the header files. This particular file, /include/drivers/dma.h, appears to not be specifying the structure parameters or other things (look at dac.h as a reference). When you make the changes, if you want to test locally then rebuild the documents see https://docs.zephyrproject.org/latest/guides/docs/index.html
