### ISSUE TITLE
OPENTHREAD_CUSTOM_PARAMETERS does not seem to work

### ISSUE THREAD

**Issue by neye-zhaw** [zephyrproject-rtos/zephyr#37502]
OpenThread defines set with the `OPENTHREAD_CUSTOM_PARAMETERS` Kconfig
option don't seem to take effect.

Steps to reproduce:
1. Set a custom parameter
`CONFIG_OPENTHREAD_CUSTOM_PARAMETERS="OPENTHREAD_CONFIG_MLE_CHILD_TIMEOUT_DEFAULT=610"`
2. Check the value with `otThreadGetChildTimeout()`. The default
   value of 240 is returned.

I'd expect the custom parameters to be applied.

This makes changing some of the OpenThread configuration hard or even impossible.

 - OS: Linux
 - zephyr-sdk-0.12.4
 - zephyr-v2.6.0 (fe7c2efca8)

This affects the https://github.com/zephyrproject-rtos/openthread repo.

**Comment by rlubos** [comment]
@neye-zhaw Indeed, OpenThread build system integration, which combines Zephyr and OpenThread build systems, used some obsolete variables from OpenThread build system that were removed at some point. I've submitted a fix in https://github.com/zephyrproject-rtos/zephyr/pull/37532, please have a look.

**Comment by neye-zhaw** [comment]
Thanks, the fix works.
