### ISSUE TITLE
friend.c:unseg_app_sdu_decrypt causes assert: net_buf_simple_tailfroom(buf) >= len when payload + opcode is 10 or 11 bytes long

### ISSUE THREAD

**Issue by ChasinSpin** [zephyrproject-rtos/zephyr#37519]
**Describe the bug**
Using bluetooth mesh with a friend and LPN node.   When the first message is sent after friend establishment with an LPN node, the following error occurs on the friend:
ASSERTION FAIL [net_buf_simple_tailroom(buf) >= len] @ WEST_TOPDIR/zephyr/subsys/net/buf.c:789
This occurs for opcode + payload sizes of 10 or 11 bytes.  For example, OPCODE3 + 8 byte payload

**What have you tried to diagnose or workaround this issue?**

I have traced this issue back t the unseg_app_sdu_decrypt function in friend.c, specifically this line:
	return bt_mesh_app_decrypt(meta->key, &meta->crypto, &sdu, &sdu);

Note that the bt_mesh_app_decrypt is called with the source (sdu) and destination (sdu) as the same.
Then in 	bt_mesh_app_decrypt in crypto.c, net_buf_simple_add(out, buf->len) attempts to add
buf->len onto the buffer which already has buf->len data bytes in, leading to the assertion.

I.E. if bt_mesh_app_decrypt is called with the same buf for source and destination, it ends up being twice the length it should be.

The other use of bt_mesh_app_decrypt (transport.c) uses different sources and destinations.
bt_mesh_app_encrypt is structured similarly but uses an update in place method instead.

Possible ways to fix it would be to make bt_mesh_app_decrypt operate on the buffer in place or change unseg_app_sdu_decrypt to work on a copy.

9 bytes and below it works fine because the double length still fits within the buffer so the assertion isn't triggered. 12 bytes and above it works fine because it then uses segmented messages instead so doesn't encounter the issue.

This issue does not show up in the examples, because they use typically <=9 bytes for the payload.

So it needs a specific set of circumstances to occur, unsegmented message of 10/11 bytes payload being sent to an LPN node from an established friend.

**Impact**
Annoyance, have work around for now, but would like to see it fixed correctly.

**Workaround**
This is the temporary workaround I'm using, but is not an elegant fix.
It detects when source and destination buffers are the same, and if they are, doesn't try to increase the buffer size by buf->len again.  This just targets unsegmented friend transmissions only, so it works for now.

```
diff crypto.c crypt.c~
400c400
<   if (out!=buf) net_buf_simple_add(out, buf->len);
---
>  net_buf_simple_add(out, buf->len);
```

I'm unsure on the best approach to fix this correctly, would appreciate one of the bluetooth mesh maintainers to take a look.

**Comment by trond-snekvik** [comment]
Hi, thanks for the detailed bug report. I have increased the payload size in the friendship test, and was able to reproduce. 

I'll post a PR with a fix a bit later today.
