### ISSUE TITLE
Replace mqtt-azure example with azure-sdk-for-c 

### ISSUE THREAD

**Issue by xiongyu0523** [zephyrproject-rtos/zephyr#37527]
The current mqtt-azure example project on Zephyr is implemented according to MQTT protocol documented by Microsoft. While Microsoft now provide a very lightweight c sdk (helper) library to handle MQTT protocol stuff and allow user to bring their own connectivity stack (TLS, MQTT, TCP/IP) which should be good fit for Zephyr network, would you mind if I submit a PR to replace the original mqtt-azure project and document with the new one? Thanks.

**Comment by xiongyu0523** [comment]
Add Link:
https://github.com/Azure/azure-sdk-for-c

**Comment by aurel32** [comment]
MQTT is not a protocol specific to Microsoft, it has been created many years ago by IBM. The protocol being a standard there is no point in using one external implementation per provider.
