### ISSUE TITLE
Bluetooth: Direction Finding: Channel index of received CTE packet is incorrect

### ISSUE THREAD

**Issue by saleh-unikie** [zephyrproject-rtos/zephyr#37547]
**Describe the bug**
By running the direction finding examples, I tried to print the "channel index", which returns 209 while it is expected to be less than 40.
At the receiver side:
```
static void cte_recv_cb(struct bt_le_per_adv_sync *sync,
			struct bt_df_per_adv_sync_iq_samples_report const *report)
{
       ...
	printk("Channel: %u\n",
		report->chan_idx);
	...
}
```

**To Reproduce**
Run the "direction finding examples" and add above code to the receiver side, main.c
https://github.com/zephyrproject-rtos/zephyr/tree/main/samples/bluetooth/direction_finding_connectionless_rx
https://github.com/zephyrproject-rtos/zephyr/tree/main/samples/bluetooth/direction_finding_connectionless_tx

**Expected behavior**
In total, there are 40 channels available in BLE, so the value expected for "chan_idx" of the report to be in this range.

**Impact**
It is not possible to do some calculations because channel number is not available.

**Logs and console output**
N/A

**Environment (please complete the following information):**
OS: Linux
Toolchain: nRF Connect SDK
v2.6.0

**Additional context**
It seems incorrect value has assigned to chan_idx, it has been set in **hci.c**:
`sep->chan_idx = lll->data_chan_id`

while "data_chan_id" is a 16 bit value and has been assigned to "chan_idx" of 8 bit value. By printing "data_chan_id", it was seen its value is 33233 and obviously it doesn't present a channel index. This value is used to calculate the next free channel and is passed to "lll_chan_sel_2" function.

**Comment by ppryga** [comment]
There were issue about wrong channel number in IQ report: https://github.com/zephyrproject-rtos/zephyr/issues/36022
The bug was fixed by PR: https://github.com/zephyrproject-rtos/zephyr/pull/36023

Here is output from `direction_finding_connectionless_rx` sample from main branch.

```
Channel: 19
CTE[0]: samples count 45, cte type AOD 2 [us], slot durations: 2 [us], packet status CRC OK, RSSI -400
PER_ADV_SYNC[0]: [DEVICE]: 1F:C5:FE:B0:47:65 (random), tx_power 127, RSSI -39, CTE AOD 2 [us], data length 0, data:
Channel: 0
CTE[0]: samples count 45, cte type AOD 2 [us], slot durations: 2 [us], packet status CRC OK, RSSI -390
PER_ADV_SYNC[0]: [DEVICE]: 1F:C5:FE:B0:47:65 (random), tx_power 127, RSSI -46, CTE AOD 2 [us], data length 0, data:
Channel: 30
CTE[0]: samples count 45, cte type AOD 2 [us], slot durations: 2 [us], packet status CRC OK, RSSI -460
PER_ADV_SYNC[0]: [DEVICE]: 1F:C5:FE:B0:47:65 (random), tx_power 127, RSSI -40, CTE AOD 2 [us], data length 0, data:
Channel: 7
CTE[0]: samples count 45, cte type AOD 2 [us], slot durations: 2 [us], packet status CRC OK, RSSI -400
PER_ADV_SYNC[0]: [DEVICE]: 1F:C5:FE:B0:47:65 (random) sync terminated
```

It looks like you are using code that hasn't got the fix.

Closing the issue because it is a duplicate of old issue that was resovled.
