### ISSUE TITLE
Schedule or timeline of LE audio in zephyr

### ISSUE THREAD

**Issue by xin10pan** [zephyrproject-rtos/zephyr#37556]
As mentioned in #37461, I have some other questions:
When will the LE audio related profiles be pushed to public repo? Is there a schedule or timeline?
By the way, how to join the Zephyr Project as a company?
Looking forward to your reply.

**Comment by carlescufi** [comment]
Hi @xin10pan. I would recommend you follow the instructions in [this page](https://www.zephyrproject.org/become-a-member/). Once you are a Zephyr member and verify that you are an Associate Bluetooth SIG member then we can share details about work on upcoming Bluetooth specifications.

**Comment by carlescufi** [comment]
Closing this since the membership question has been answered.
