### ISSUE TITLE
PWM: Issue compiling project when CONFIG_PWM and CONFIG_PWM_SAM is used with SAME70

### ISSUE THREAD

**Issue by jmahkye** [zephyrproject-rtos/zephyr#37579]
**Describe the bug**
Unable to compile any project that using CONFIG_PWM with the a board definition using the SAME70 MCU

**To Reproduce**
Using a board definition that uses the SAME7021QB MCU with a blank main with CONFIG_PWM and CONFIG_PWM_SAM in prj.conf.
1. west build -p auto --board=battery_cycler_xpl pwm_sample
zephyr/drivers/pwm/pwm_sam.c:116:1: error: macro "DEVICE_DT_DEFINE" requires 9 arguments, but only 7 given
  116 | DT_INST_FOREACH_STATUS_OKAY(SAM_INST_INIT)

**Expected behavior**
Build succeeds

**Impact**
Showstopper

**Logs and console output**
`FAILED: zephyr/drivers/pwm/CMakeFiles/drivers__pwm.dir/pwm_sam.c.obj 
ccache /home/jeanmarc/bin/zephyr-sdk-0.12.1/arm-zephyr-eabi/bin/arm-zephyr-eabi-gcc -DBUILD_VERSION=zephyr-v2.5.0-4405-g71704e745055 -DKERNEL -D_FORTIFY_SOURCE=2 -D__PROGRAM_START -D__ZEPHYR_SUPERVISOR__ -D__ZEPHYR__=1 -I/home/jeanmarc/zephyr/ZEPHYR_WORKSPACE/cdo2zephyr/zephyr/include -Izephyr/include/generated -I/home/jeanmarc/zephyr/ZEPHYR_WORKSPACE/cdo2zephyr/zephyr/soc/arm/atmel_sam/same70 -I/home/jeanmarc/zephyr/ZEPHYR_WORKSPACE/cdo2zephyr/zephyr/soc/arm/atmel_sam/common/. -I/home/jeanmarc/zephyr/ZEPHYR_WORKSPACE/cdo2zephyr/include -I/home/jeanmarc/zephyr/ZEPHYR_WORKSPACE/cdo2zephyr/hw -I/home/jeanmarc/zephyr/ZEPHYR_WORKSPACE/cdo2zephyr/util -I/home/jeanmarc/zephyr/ZEPHYR_WORKSPACE/cdo2zephyr/drivers -I/home/jeanmarc/zephyr/ZEPHYR_WORKSPACE/modules/hal/cmsis/CMSIS/Core/Include -I/home/jeanmarc/zephyr/ZEPHYR_WORKSPACE/modules/hal/atmel/asf/sam/include/same70b -isystem /home/jeanmarc/zephyr/ZEPHYR_WORKSPACE/cdo2zephyr/zephyr/lib/libc/minimal/include -isystem /home/jeanmarc/bin/zephyr-sdk-0.12.1/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/10.2.0/include -isystem /home/jeanmarc/bin/zephyr-sdk-0.12.1/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/10.2.0/include-fixed -Os -imacros /home/jeanmarc/zephyr/workspace/build/zephyr/include/generated/autoconf.h -ffreestanding -fno-common -g -fdiagnostics-color=always -mcpu=cortex-m7 -mthumb -mabi=aapcs -imacros /home/jeanmarc/zephyr/ZEPHYR_WORKSPACE/cdo2zephyr/zephyr/include/toolchain/zephyr_stdint.h -Wall -Wformat -Wformat-security -Wno-format-zero-length -Wno-main -Wno-pointer-sign -Wpointer-arith -Wexpansion-to-defined -Wno-address-of-packed-member -Wno-unused-but-set-variable -Werror=implicit-int -fno-asynchronous-unwind-tables -fno-pie -fno-pic -fno-strict-overflow -fno-reorder-functions -fno-defer-pop -fmacro-prefix-map=/home/jeanmarc/zephyr/workspace/pwm_sample=CMAKE_SOURCE_DIR -fmacro-prefix-map=/home/jeanmarc/zephyr/ZEPHYR_WORKSPACE/cdo2zephyr/zephyr=ZEPHYR_BASE -fmacro-prefix-map=/home/jeanmarc/zephyr/ZEPHYR_WORKSPACE=WEST_TOPDIR -ffunction-sections -fdata-sections -std=c99 -nostdinc -MD -MT zephyr/drivers/pwm/CMakeFiles/drivers__pwm.dir/pwm_sam.c.obj -MF zephyr/drivers/pwm/CMakeFiles/drivers__pwm.dir/pwm_sam.c.obj.d -o zephyr/drivers/pwm/CMakeFiles/drivers__pwm.dir/pwm_sam.c.obj -c /home/jeanmarc/zephyr/ZEPHYR_WORKSPACE/cdo2zephyr/zephyr/drivers/pwm/pwm_sam.c
/home/jeanmarc/zephyr/ZEPHYR_WORKSPACE/cdo2zephyr/zephyr/drivers/pwm/pwm_sam.c:116:1: error: macro "DEVICE_DT_DEFINE" requires 9 arguments, but only 7 given
  116 | DT_INST_FOREACH_STATUS_OKAY(SAM_INST_INIT)
      | ^~~~~~~~~~~~~~~~
In file included from /home/jeanmarc/zephyr/ZEPHYR_WORKSPACE/cdo2zephyr/zephyr/drivers/pwm/pwm_sam.c:9:
/home/jeanmarc/zephyr/ZEPHYR_WORKSPACE/cdo2zephyr/zephyr/include/device.h:219: note: macro "DEVICE_DT_DEFINE" defined here
  219 | #define DEVICE_DT_DEFINE(node_id, init_fn, pm_control_fn,  \
      | 
In file included from /home/jeanmarc/zephyr/ZEPHYR_WORKSPACE/cdo2zephyr/zephyr/include/sys/util_macro.h:34,
                 from /home/jeanmarc/zephyr/ZEPHYR_WORKSPACE/cdo2zephyr/zephyr/include/sys/util.h:17,
                 from /home/jeanmarc/zephyr/ZEPHYR_WORKSPACE/cdo2zephyr/zephyr/include/sched_priq.h:9,
                 from /home/jeanmarc/zephyr/ZEPHYR_WORKSPACE/cdo2zephyr/zephyr/include/kernel_includes.h:23,
                 from /home/jeanmarc/zephyr/ZEPHYR_WORKSPACE/cdo2zephyr/zephyr/include/kernel.h:17,
                 from /home/jeanmarc/zephyr/ZEPHYR_WORKSPACE/cdo2zephyr/zephyr/include/init.h:11,
                 from /home/jeanmarc/zephyr/ZEPHYR_WORKSPACE/cdo2zephyr/zephyr/include/device.h:29,
                 from /home/jeanmarc/zephyr/ZEPHYR_WORKSPACE/cdo2zephyr/zephyr/drivers/pwm/pwm_sam.c:9:
/home/jeanmarc/zephyr/ZEPHYR_WORKSPACE/cdo2zephyr/zephyr/include/device.h:239:2: warning: data definition has no type or storage class
  239 |  DEVICE_DT_DEFINE(DT_DRV_INST(inst), __VA_ARGS__)
      |  ^~~~~~~~~~~~~~~~
/home/jeanmarc/zephyr/ZEPHYR_WORKSPACE/cdo2zephyr/zephyr/include/sys/util_internal.h:67:26: note: in definition of macro '__DEBRACKET'
   67 | #define __DEBRACKET(...) __VA_ARGS__
      |                          ^~~~~~~~~~~
/home/jeanmarc/zephyr/ZEPHYR_WORKSPACE/cdo2zephyr/zephyr/include/sys/util_internal.h:59:2: note: in expansion of macro '__GET_ARG2_DEBRACKET'
   59 |  __GET_ARG2_DEBRACKET(one_or_two_args _if_code, _else_code)
      |  ^~~~~~~~~~~~~~~~~~~~
/home/jeanmarc/zephyr/ZEPHYR_WORKSPACE/cdo2zephyr/zephyr/include/sys/util_internal.h:54:2: note: in expansion of macro '__COND_CODE'
   54 |  __COND_CODE(_XXXX##_flag, _if_1_code, _else_code)
      |  ^~~~~~~~~~~
/home/jeanmarc/zephyr/ZEPHYR_WORKSPACE/cdo2zephyr/zephyr/include/sys/util_macro.h:117:2: note: in expansion of macro 'Z_COND_CODE_1'
  117 |  Z_COND_CODE_1(_flag, _if_1_code, _else_code)
      |  ^~~~~~~~~~~~~
/home/jeanmarc/zephyr/ZEPHYR_WORKSPACE/cdo2zephyr/zephyr/include/devicetree.h:2211:2: note: in expansion of macro 'COND_CODE_1'
 2211 |  COND_CODE_1(DT_HAS_COMPAT_STATUS_OKAY(DT_DRV_COMPAT), \
      |  ^~~~~~~~~~~
/home/jeanmarc/zephyr/ZEPHYR_WORKSPACE/cdo2zephyr/zephyr/drivers/pwm/pwm_sam.c:109:2: note: in expansion of macro 'DEVICE_DT_INST_DEFINE'
  109 |  DEVICE_DT_INST_DEFINE(inst,     \
      |  ^~~~~~~~~~~~~~~~~~~~~
zephyr/include/generated/devicetree_unfixed.h:14477:48: note: in expansion of macro 'SAM_INST_INIT'
14477 | #define DT_FOREACH_OKAY_INST_atmel_sam_pwm(fn) fn(0)
      |                                                ^~
/home/jeanmarc/zephyr/ZEPHYR_WORKSPACE/cdo2zephyr/zephyr/include/sys/util_internal.h:85:36: note: in expansion of macro 'DT_FOREACH_OKAY_INST_atmel_sam_pwm'
   85 | #define UTIL_PRIMITIVE_CAT(a, ...) a##__VA_ARGS__
      |                                    ^
/home/jeanmarc/zephyr/ZEPHYR_WORKSPACE/cdo2zephyr/zephyr/drivers/pwm/pwm_sam.c:116:1: note: in expansion of macro 'DT_INST_FOREACH_STATUS_OKAY'
  116 | DT_INST_FOREACH_STATUS_OKAY(SAM_INST_INIT)
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/jeanmarc/zephyr/ZEPHYR_WORKSPACE/cdo2zephyr/zephyr/include/device.h:239:2: error: type defaults to 'int' in declaration of 'DEVICE_DT_DEFINE' [-Werror=implicit-int]
  239 |  DEVICE_DT_DEFINE(DT_DRV_INST(inst), __VA_ARGS__)
      |  ^~~~~~~~~~~~~~~~
/home/jeanmarc/zephyr/ZEPHYR_WORKSPACE/cdo2zephyr/zephyr/include/sys/util_internal.h:67:26: note: in definition of macro '__DEBRACKET'
   67 | #define __DEBRACKET(...) __VA_ARGS__
      |                          ^~~~~~~~~~~
/home/jeanmarc/zephyr/ZEPHYR_WORKSPACE/cdo2zephyr/zephyr/include/sys/util_internal.h:59:2: note: in expansion of macro '__GET_ARG2_DEBRACKET'
   59 |  __GET_ARG2_DEBRACKET(one_or_two_args _if_code, _else_code)
      |  ^~~~~~~~~~~~~~~~~~~~
/home/jeanmarc/zephyr/ZEPHYR_WORKSPACE/cdo2zephyr/zephyr/include/sys/util_internal.h:54:2: note: in expansion of macro '__COND_CODE'
   54 |  __COND_CODE(_XXXX##_flag, _if_1_code, _else_code)
      |  ^~~~~~~~~~~
/home/jeanmarc/zephyr/ZEPHYR_WORKSPACE/cdo2zephyr/zephyr/include/sys/util_macro.h:117:2: note: in expansion of macro 'Z_COND_CODE_1'
  117 |  Z_COND_CODE_1(_flag, _if_1_code, _else_code)
      |  ^~~~~~~~~~~~~
/home/jeanmarc/zephyr/ZEPHYR_WORKSPACE/cdo2zephyr/zephyr/include/devicetree.h:2211:2: note: in expansion of macro 'COND_CODE_1'
 2211 |  COND_CODE_1(DT_HAS_COMPAT_STATUS_OKAY(DT_DRV_COMPAT), \
      |  ^~~~~~~~~~~
/home/jeanmarc/zephyr/ZEPHYR_WORKSPACE/cdo2zephyr/zephyr/drivers/pwm/pwm_sam.c:109:2: note: in expansion of macro 'DEVICE_DT_INST_DEFINE'
  109 |  DEVICE_DT_INST_DEFINE(inst,     \
      |  ^~~~~~~~~~~~~~~~~~~~~
zephyr/include/generated/devicetree_unfixed.h:14477:48: note: in expansion of macro 'SAM_INST_INIT'
14477 | #define DT_FOREACH_OKAY_INST_atmel_sam_pwm(fn) fn(0)
      |                                                ^~
/home/jeanmarc/zephyr/ZEPHYR_WORKSPACE/cdo2zephyr/zephyr/include/sys/util_internal.h:85:36: note: in expansion of macro 'DT_FOREACH_OKAY_INST_atmel_sam_pwm'
   85 | #define UTIL_PRIMITIVE_CAT(a, ...) a##__VA_ARGS__
      |                                    ^
/home/jeanmarc/zephyr/ZEPHYR_WORKSPACE/cdo2zephyr/zephyr/drivers/pwm/pwm_sam.c:116:1: note: in expansion of macro 'DT_INST_FOREACH_STATUS_OKAY'
  116 | DT_INST_FOREACH_STATUS_OKAY(SAM_INST_INIT)
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/jeanmarc/zephyr/ZEPHYR_WORKSPACE/cdo2zephyr/zephyr/drivers/pwm/pwm_sam.c:102:37: warning: 'sam_pwm_config_0' defined but not used [-Wunused-const-variable=]
  102 |  static const struct sam_pwm_config sam_pwm_config_##inst = { \
      |                                     ^~~~~~~~~~~~~~~
/home/jeanmarc/zephyr/ZEPHYR_WORKSPACE/cdo2zephyr/zephyr/include/sys/util_internal.h:67:26: note: in definition of macro '__DEBRACKET'
   67 | #define __DEBRACKET(...) __VA_ARGS__
      |                          ^~~~~~~~~~~
/home/jeanmarc/zephyr/ZEPHYR_WORKSPACE/cdo2zephyr/zephyr/include/sys/util_internal.h:59:2: note: in expansion of macro '__GET_ARG2_DEBRACKET'
   59 |  __GET_ARG2_DEBRACKET(one_or_two_args _if_code, _else_code)
      |  ^~~~~~~~~~~~~~~~~~~~
/home/jeanmarc/zephyr/ZEPHYR_WORKSPACE/cdo2zephyr/zephyr/include/sys/util_internal.h:54:2: note: in expansion of macro '__COND_CODE'
   54 |  __COND_CODE(_XXXX##_flag, _if_1_code, _else_code)
      |  ^~~~~~~~~~~
/home/jeanmarc/zephyr/ZEPHYR_WORKSPACE/cdo2zephyr/zephyr/include/sys/util_macro.h:117:2: note: in expansion of macro 'Z_COND_CODE_1'
  117 |  Z_COND_CODE_1(_flag, _if_1_code, _else_code)
      |  ^~~~~~~~~~~~~
/home/jeanmarc/zephyr/ZEPHYR_WORKSPACE/cdo2zephyr/zephyr/include/devicetree.h:2211:2: note: in expansion of macro 'COND_CODE_1'
 2211 |  COND_CODE_1(DT_HAS_COMPAT_STATUS_OKAY(DT_DRV_COMPAT), \
      |  ^~~~~~~~~~~
zephyr/include/generated/devicetree_unfixed.h:14477:48: note: in expansion of macro 'SAM_INST_INIT'
14477 | #define DT_FOREACH_OKAY_INST_atmel_sam_pwm(fn) fn(0)
      |                                                ^~
/home/jeanmarc/zephyr/ZEPHYR_WORKSPACE/cdo2zephyr/zephyr/include/sys/util_internal.h:85:36: note: in expansion of macro 'DT_FOREACH_OKAY_INST_atmel_sam_pwm'
   85 | #define UTIL_PRIMITIVE_CAT(a, ...) a##__VA_ARGS__
      |                                    ^
/home/jeanmarc/zephyr/ZEPHYR_WORKSPACE/cdo2zephyr/zephyr/drivers/pwm/pwm_sam.c:116:1: note: in expansion of macro 'DT_INST_FOREACH_STATUS_OKAY'
  116 | DT_INST_FOREACH_STATUS_OKAY(SAM_INST_INIT)
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/jeanmarc/zephyr/ZEPHYR_WORKSPACE/cdo2zephyr/zephyr/drivers/pwm/pwm_sam.c:96:36: warning: 'sam_pwm_driver_api' defined but not used [-Wunused-const-variable=]
   96 | static const struct pwm_driver_api sam_pwm_driver_api = {
      |                                    ^~~~~~~~~~~~~~~~~~
/home/jeanmarc/zephyr/ZEPHYR_WORKSPACE/cdo2zephyr/zephyr/drivers/pwm/pwm_sam.c:78:12: warning: 'sam_pwm_init' defined but not used [-Wunused-function]
   78 | static int sam_pwm_init(const struct device *dev)
      |            ^~~~~~~~~~~~
cc1: some warnings being treated as errors
ninja: build stopped: subcommand failed.
FATAL ERROR: command exited with status 1: /usr/bin/cmake --build /home/jeanmarc/zephyr/workspace/build
`

**Environment (please complete the following information):**
 - OS:  Fedora 33
 - Toolchain: Zephyr SDK 2.6

**Additional context**

**Comment by nandojve** [comment]
CC: @mnkp @stephanosio @nandojve
