### ISSUE TITLE
Make access to device data and config consistent across drivers

### ISSUE THREAD

**Issue by gmarull** [zephyrproject-rtos/zephyr#37616]
**Is your enhancement proposal related to a problem? Please describe.**

Drivers usually need to access `data` and `config` fields from `struct device`. If one looks at `drivers/`, there seems to be a few different ways of accessing those fields. I think they can be classified in 3 _groups_:

1. Some drivers access `dev->config` and `dev->data` directly (I think this is the majority of drivers). In this case `void *` is not explicitly cast to its type.

https://github.com/zephyrproject-rtos/zephyr/blob/0f949caee12441dd4996017210d2d05971b3cf23/drivers/pwm/pwm_stm32.c#L266-L267

2. Some drivers provide helper macros like `DEV_CFG` or `DEV_DATA`. These macros usually perform an explicit cast to the actual config/data type.

https://github.com/zephyrproject-rtos/zephyr/blob/0f949caee12441dd4996017210d2d05971b3cf23/drivers/serial/uart_stm32.c#L45-L60

3. Some drivers provide helper inline functions like `get_dev_config` or `get_dev_data`. The return type of these functions is the actual config/data type, but in most (if not all) cases no cast is performed inside.

https://github.com/zephyrproject-rtos/zephyr/blob/0f949caee12441dd4996017210d2d05971b3cf23/drivers/serial/uart_nrfx_uarte.c#L175-L183

**Describe the solution you'd like**

I'd like to have consistency across drivers, that is, agree on a pattern, document it and convert all drivers. I think case (1) is the simplest and most common one, so I'd vote for that option.

**Describe alternatives you've considered**

N/A

**Additional context**

Any of the current solution (including explicit cast) violates MISRA 11.5 rule "A conversion should not be performed from pointer to void into pointer to object" (advisory category, though).

**Comment by carlescufi** [comment]
API meeting:

- Approach 1. selected as the preferred approach, due to it being the most natural given the current variable names
- The documentation needs updating: doc/reference/drivers/index.rst
