### ISSUE TITLE
Warnings when disabling LOG, MCUBOOT_SERIAL and SERIAL_CDC_ACM 

### ISSUE THREAD

**Issue by caco3** [zephyrproject-rtos/zephyr#37708]
We have nrf52840_dongle board (resp. a [Laird USB Adapter](https://www.lairdconnect.com/wireless-modules/bluetooth-modules/bluetooth-5-modules/bl654-series-bluetooth-module-nfc) without JTAG access) where we want to run a minimalistic 2nd stage bootloader (after the pre-installed Nordic bootloader).

To minimize the flash footprint, we need to disable `LOG`, how ever this leads to the 2 following warnings and we did not find a ways to avoid this:
```
warning: LOG_DEFAULT_LEVEL (defined at subsys/logging/Kconfig.filtering:13) was assigned the value
'0' but got the value ''. Check these unsatisfied dependencies: LOG (=n). 

warning: The choice symbol LOG_MODE_MINIMAL (defined at subsys/logging/Kconfig.mode:45) was selected
(set =y), but no symbol ended up as the choice selection.
```

Also we want to disable the `MCUBOOT_SERIAL` but again this leads to the following 2 warnings (only in conjunction with `USB_DEVICE_VID=xxxx`):
```
warning: BOOT_SERIAL_DETECT_PORT (defined at
/opt/zephyrproject-v2.6.0/bootloader/mcuboot/boot/zephyr/Kconfig:511) was assigned the value
'GPIO_1' but got the value ''. Check these unsatisfied dependencies: MCUBOOT_SERIAL (=n).

warning: BOOT_SERIAL_DETECT_PIN (defined at
/opt/zephyrproject-v2.6.0/bootloader/mcuboot/boot/zephyr/Kconfig:518) was assigned the value '6' but
got the value ''. Check these unsatisfied dependencies: MCUBOOT_SERIAL (=n). 
```

Also we always get following warning despite `SERIAL_CDC_ACM` should be disabled by default:
```
warning: The choice symbol BOOT_SERIAL_CDC_ACM (defined at
/opt/zephyrproject-v2.6.0/bootloader/mcuboot/boot/zephyr/Kconfig:489) was selected (set =y), but no
symbol ended up as the choice selection.
```

proj.conf:
```
# MCUboot config
CONFIG_MCUBOOT_SERIAL=n

# Log
CONFIG_LOG=n
CONFIG_UART_CONSOLE=n
CONFIG_CONSOLE_HANDLER=n

# USB device stack
#CONFIG_USB_DEVICE_VID=0x1545

# USB Device Support
CONFIG_USB_CDC_ACM=n
```

Is there a proper way to solve/suppress those warnings?

**Comment by de-nordic** [comment]
I will take a look at the mcuboot serial settings.
Regarding the logs: the problem may be that the default level overrides the level you select for MCUBOOT, this may be similar to the problem I identified while investigating https://github.com/zephyrproject-rtos/zephyr/issues/35821, comment https://github.com/zephyrproject-rtos/zephyr/issues/35821#issuecomment-888319376.
