### ISSUE TITLE
net: dtls: received close_notify alerts are not properly handled by DTLS client sockets 

### ISSUE THREAD

**Issue by phise** [zephyrproject-rtos/zephyr#37720]
**Describe the bug**
In the current state of the DTLS implementation, received `close_notify` alerts are not properly handled by a DTLS client socket.

According to the mbedtls documentation the SSL context must be reset when `mbedtls_ssl_read ` returns the following:

> If this function returns something other than a positive value, MBEDTLS_ERR_SSL_WANT_READ, MBEDTLS_ERR_SSL_WANT_WRITE, MBEDTLS_ERR_SSL_ASYNC_IN_PROGRESS, MBEDTLS_ERR_SSL_CRYPTO_IN_PROGRESS or MBEDTLS_ERR_SSL_CLIENT_RECONNECT, you must stop using the SSL context for reading or writing, and either free it or call mbedtls_ssl_session_reset() on it before re-using it for a new connection; the current connection must be closed.
see https://tls.mbed.org/api/ssl_8h.html#aa2c29eeb1deaf5ad9f01a7515006ede5

For the case of `MBEDTLS_ERR_SSL_PEER_CLOSE_NOTIFY` the SSL context is not reset for DTLS clients: https://github.com/zephyrproject-rtos/zephyr/blob/zephyr-v2.6.0/subsys/net/lib/sockets/sockets_tls.c#L1808
This may lead to an application still trying to send data over an already closed connection.

Furthermore, it is not possible to detect (in an application) that the session has been closed when using `poll()` because neither `POLLHUP` nor `POLLERR` are set.

**To Reproduce**
1. open a DTLS client socket in zephyr
2. establish session with a DTLS server
3. send `close_notify` alert from DTLS server

**Expected behavior**

- Internally in `sockets_tls`, the SSL context should be reset when receiving a `close_notify` alert on a DTLS client socket (similar to how it is already done for DTLS server sockets: https://github.com/zephyrproject-rtos/zephyr/blob/zephyr-v2.6.0/subsys/net/lib/sockets/sockets_tls.c#L1893).

- Ideally, `POLLHUP` is set as well on the poll FD so an application can decide how to deal with the closed session.

**Impact**
Possibly a lot of packets are sent over a closed connection unnecessarily until e.g. an application decides to renew the DTLS session.

**Environment (please complete the following information):**
 - Zephyr v2.6.0

**Comment by rlubos** [comment]
@phise Thanks for the report. Please have a look at https://github.com/zephyrproject-rtos/zephyr/pull/37794 where I proposed a fix for the issue. `poll()` will now report `POLLHUP` when peer closes the connection, a new session will be established on a consecutive send.
