### ISSUE TITLE
Merge vendor-prefixes.txt from all modules with build.settings.dts_root in zephyr/module.yml

### ISSUE THREAD

**Issue by mniestroj** [zephyrproject-rtos/zephyr#37797]
**Is your enhancement proposal related to a problem? Please describe.**
Recently all device tree compatible strings are checked for valid vendor prefixes and a warning is generated if vendor is not listed in `${ZEPHYR_BASE}/dts/bindings/vendor-prefixes.txt`. In case of twister builds warnings are errors by default, which results in CI failures. If downstream project has downstream drivers with downstream DT bindings with unknown vendor, then there is no easy way of extending list of possible vendors and suppressing generated warning/error.

**Describe the solution you'd like**
Iterate over all `MODULE/dts/bindings/` directories that are used so far for DT bindings resolution and check if `vendor-prefixes.txt` exists there. If yes, then merge list of all vendors, so that warnings for downstream drivers (that use vendor unspecified in Zephyr's `vendor-prefixes.txt`) can be suppressed.

**Additional context**
Introduced checking of vendor-prefixes.txt breaks downstream projects that use twister in CI. The workaround for now is to disable "warnings as error" in twister or patching Zephyr's `vendor-prefixes.txt`.

**Comment by mbolivar-nordic** [comment]
Implemented in https://github.com/zephyrproject-rtos/zephyr/pull/37802. Working in my testing.
