### ISSUE TITLE
stm32h747i_disco M4 not working, if use large size(>1KB) global array

### ISSUE THREAD

**Issue by cameled** [zephyrproject-rtos/zephyr#37827]
**Describe the bug**
Hi, I meet a strange problem this week. stm32h747i_disco M4 will not working, if I'm tring to use large size(>1KB) global or static array.
I have test it on fresh build zephyr blinky sample, with below large_size_array patch:
```
index e2fbfd3dc5..edada65a24 100644
--- a/samples/basic/blinky/src/main.c
+++ b/samples/basic/blinky/src/main.c
@@ -27,12 +27,16 @@
 #define FLAGS  0
 #endif
 
+char large_size_array[1024];
+
 void main(void)
 {
        const struct device *dev;
        bool led_is_on = true;
        int ret;
 
+       large_size_array[0] = '\0';
+
        dev = device_get_binding(LED0);
        if (dev == NULL) {
                return;
```

**To Reproduce**
1. cd zephyr
2. apply large_size_array patch
3. west build -p -b stm32h747i_disco_m4 samples/basic/blinky
4. west flash

**Expected behavior**
blue led for M4 is blink.

**Impact**
Can not use large size global or statis array .

**Logs and console output**
doesn't have any output(usart1 on M4)

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: zephyr-sdk-0.13.0
 - main branch

**Comment by cameled** [comment]
Looks it's a link issue, If reduce the CONFIG_HEAP_MEM_POOL_SIZE to 1024, blinky sample start to work.

**Comment by cameled** [comment]
After erase by STM32Programer, this issue disappeared.

**Comment by erwango** [comment]
@cameled Strange. Anyway, thanks for feedback.

**Comment by cameled** [comment]
Looks that's a random success, STM32Programer is not the key.

**Comment by cameled** [comment]
As said in  #38322, disable BCM4 config can fix this issue.
