### ISSUE TITLE
samples: bluetooth: mesh: build failed for native posix

### ISSUE THREAD

**Issue by LingaoM** [zephyrproject-rtos/zephyr#37896]
`west build -b native_posix zephyr/samples/bluetooth/mesh`

mon=descending  -Wl,--sort-section=alignment  -Wl,-u,_OffsetAbsSyms  -Wl,-u,_ConfigAbsSyms  -m32  -ldl  -pthread  -lm && cd /home/lingao/zephyrproject/build/zephyr && /home/lingao/cmake-3.21.1-linux-x86_64/bin/cmake -E echo
/usr/bin/ld: app/libapp.a(board.c.obj): in function `z_device_usable_check':
/home/lingao/zephyrproject/zephyr/include/device.h:572: undefined reference to `__device_dts_ord_21'
/usr/bin/ld: app/libapp.a(board.c.obj): in function `z_impl_gpio_pin_configure':
/home/lingao/zephyrproject/zephyr/include/drivers/gpio.h:718: undefined reference to `__device_dts_ord_21'
/usr/bin/ld: /home/lingao/zephyrproject/zephyr/include/drivers/gpio.h:761: undefined reference to `__device_dts_ord_21'
/usr/bin/ld: /home/lingao/zephyrproject/zephyr/include/drivers/gpio.h:761: undefined reference to `__device_dts_ord_21'
/usr/bin/ld: app/libapp.a(board.c.obj): in function `gpio_pin_set':
/home/lingao/zephyrproject/zephyr/include/drivers/gpio.h:1201: undefined reference to `__device_dts_ord_21'
/usr/bin/ld: app/libapp.a(board.c.obj):/home/lingao/zephyrproject/zephyr/include/drivers/gpio.h:1159: more undefined references to `__device_dts_ord_21' follow
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.

**Comment by nashif** [comment]
This is not supported on native posix, run this on actual hardware please, for example the bbc_microbit.
