### ISSUE TITLE
twister: The --board-root parameter doesn't appear to work

### ISSUE THREAD

**Issue by DRuffer** [zephyrproject-rtos/zephyr#38047]
**Describe the bug**
We are trying to use "out of tree" sources for our board, but I have been unable to get --board_root to work.
I can copy the board folder into Zephyr/boards/arm and it works fine without this flag.

**To Reproduce**
1. ./scripts/twister -vvv --device-testing --device-serial /dev/ttyUSB1 --board-root /home/druffer/zephyrproject/zephyr-tmo-sdk --platform pets_v2_dev_kit --testcase-root tests/kernel/sched/preempt
2. Copy our board folder into Zephyr/boards/arm
3. ./scripts/twister -vvv --device-testing --device-serial /dev/ttyUSB1 --board-root /home/druffer/zephyrproject/zephyr-tmo-sdk --platform pets_v2_dev_kit --testcase-root tests/kernel/sched/preempt
4. It builds and PASSES

**Expected behavior**
I expect that the test PASSES without having to copy it into Zephyr/boards/arm

**Impact**
This means we cannot use the "out of tree" methods.

**Logs and console output**
Without the copy in Zephyr/boards/arm:
druffer@druffer-Surface-Pro-2:~/zephyrproject/zephyr$ ./scripts/twister -vvv --device-testing --device-serial /dev/ttyUSB1 --board-root /home/druffer/zephyrproject/zephyr-tmo-sdk --platform pets_v2_dev_kit --testcase-root tests/kernel/sched/preempt
ZEPHYR_BASE unset, using "/home/druffer/zephyrproject/zephyr"
Renaming output directory to /home/druffer/zephyrproject/zephyr/twister-out.16
INFO    - Zephyr version: v2.6.0-rc2-124-gc8ccacef8f82
INFO    - JOBS: 4
DEBUG   - Reading test case configuration files under /home/druffer/zephyrproject/zephyr/tests/kernel/sched/preempt...
DEBUG   - Found possible test case in /home/druffer/zephyrproject/zephyr/tests/kernel/sched/preempt
DEBUG   - Reading platform configuration files under /home/druffer/zephyrproject/zephyr/boards...
DEBUG   - Reading platform configuration files under /home/druffer/zephyrproject/zephyr/scripts/pylib/twister/boards...
DEBUG   - Reading platform configuration files under /home/druffer/zephyrproject/zephyr-tmo-sdk...
DEBUG   - Running cmake script /home/druffer/zephyrproject/zephyr/cmake/verify-toolchain.cmake
DEBUG   - Calling cmake with arguments: ['-DFORMAT=json', '-P', PosixPath('/home/druffer/zephyrproject/zephyr/cmake/verify-toolchain.cmake')]
DEBUG   - Finished running  /home/druffer/zephyrproject/zephyr/cmake/verify-toolchain.cmake
INFO    - Using 'zephyr' toolchain.
DEBUG   - platform filter: ['pets_v2_dev_kit']
DEBUG   -     arch_filter: None
DEBUG   -      tag_filter: None
DEBUG   -     exclude_tag: None
INFO    - Building initial testcase list...
INFO    - 1 test scenarios (0 configurations) selected, 0 configurations discarded due to filters.

Device testing on:

| Platform        | ID   | Serial device   |
|-----------------|------|-----------------|
| pets_v2_dev_kit |      | /dev/ttyUSB1    |

INFO    - Adding tasks to the queue...
INFO    - Added initial list of jobs to queue
DEBUG   - Launch process 0
DEBUG   - Launch process 1
DEBUG   - Launch process 2
DEBUG   - Launch process 3

DEBUG   - running footprint_reports
INFO    - 0 of 0 test configurations passed (0.00%), 0 failed, 0 skipped with 0 warnings in 0.99 seconds
INFO    - In total 0 test cases were executed, 0 skipped on 0 out of total 372 platforms (0.00%)
INFO    - 0 test configurations executed on platforms, 0 test configurations were only built.

Hardware distribution summary:

| Board   | ID   | Counter   |
|---------|------|-----------|
INFO    - Run completed

With the copy in Zephyr/boards/arm:
druffer@druffer-Surface-Pro-2:~/zephyrproject/zephyr$ ./scripts/twister -vvv --device-testing --device-serial /dev/ttyUSB1 --board-root /home/druffer/zephyrproject/zephyr-tmo-sdk --platform pets_v2_dev_kit --testcase-root tests/kernel/sched/preempt
ZEPHYR_BASE unset, using "/home/druffer/zephyrproject/zephyr"
Renaming output directory to /home/druffer/zephyrproject/zephyr/twister-out.17
INFO    - Zephyr version: v2.6.0-rc2-124-gc8ccacef8f82
INFO    - JOBS: 4
DEBUG   - Reading test case configuration files under /home/druffer/zephyrproject/zephyr/tests/kernel/sched/preempt...
DEBUG   - Found possible test case in /home/druffer/zephyrproject/zephyr/tests/kernel/sched/preempt
DEBUG   - Reading platform configuration files under /home/druffer/zephyrproject/zephyr/boards...
DEBUG   - Reading platform configuration files under /home/druffer/zephyrproject/zephyr/scripts/pylib/twister/boards...
DEBUG   - Reading platform configuration files under /home/druffer/zephyrproject/zephyr-tmo-sdk...
DEBUG   - Running cmake script /home/druffer/zephyrproject/zephyr/cmake/verify-toolchain.cmake
DEBUG   - Calling cmake with arguments: ['-DFORMAT=json', '-P', PosixPath('/home/druffer/zephyrproject/zephyr/cmake/verify-toolchain.cmake')]
DEBUG   - Finished running  /home/druffer/zephyrproject/zephyr/cmake/verify-toolchain.cmake
INFO    - Using 'zephyr' toolchain.
DEBUG   - platform filter: ['pets_v2_dev_kit']
DEBUG   -     arch_filter: None
DEBUG   -      tag_filter: None
DEBUG   -     exclude_tag: None
INFO    - Building initial testcase list...
INFO    - 1 test scenarios (1 configurations) selected, 0 configurations discarded due to filters.

Device testing on:

| Platform        | ID   | Serial device   |
|-----------------|------|-----------------|
| pets_v2_dev_kit |      | /dev/ttyUSB1    |

INFO    - Adding tasks to the queue...
DEBUG   - adding pets_v2_dev_kit/tests/kernel/sched/preempt/kernel.scheduler.preempt
INFO    - Added initial list of jobs to queue
DEBUG   - Launch process 0
DEBUG   - Launch process 1
DEBUG   - Launch process 2
DEBUG   - Launch process 3
DEBUG   - Running cmake on /home/druffer/zephyrproject/zephyr/tests/kernel/sched/preempt for pets_v2_dev_kit
DEBUG   - Calling cmake with arguments: ['-B/home/druffer/zephyrproject/zephyr/twister-out/pets_v2_dev_kit/tests/kernel/sched/preempt/kernel.scheduler.preempt', '-S/home/druffer/zephyrproject/zephyr/tests/kernel/sched/preempt', '-DEXTRA_CFLAGS="-Werror"', '-DEXTRA_AFLAGS="-Wa,--fatal-warnings', '-DEXTRA_LDFLAGS="-Wl,--fatal-warnings"', '-DEXTRA_GEN_DEFINES_ARGS=--err-on-deprecated-properties', '-GUnix Makefiles', '-DBOARD=pets_v2_dev_kit']
DEBUG   - Finished building /home/druffer/zephyrproject/zephyr/tests/kernel/sched/preempt for pets_v2_dev_kit
DEBUG   - build test: pets_v2_dev_kit/tests/kernel/sched/preempt/kernel.scheduler.preempt
DEBUG   - Building /home/druffer/zephyrproject/zephyr/tests/kernel/sched/preempt for pets_v2_dev_kit
DEBUG   - run test: pets_v2_dev_kit/tests/kernel/sched/preempt/kernel.scheduler.preempt
DEBUG   - Using serial device /dev/ttyUSB1
DEBUG   - Flash command: ['make', '-C', '/home/druffer/zephyrproject/zephyr/twister-out/pets_v2_dev_kit/tests/kernel/sched/preempt/kernel.scheduler.preempt', 'flash']
DEBUG   - DEVICE: *** Booting Zephyr OS build v2.6.0-rc2-124-gc8ccacef8f82  ***
DEBUG   - make: Entering directory '/home/druffer/zephyrproject/zephyr/twister-out/pets_v2_dev_kit/tests/kernel/sched/preempt/kernel.scheduler.preempt'
make[1]: Entering directory '/home/druffer/zephyrproject/zephyr/twister-out/pets_v2_dev_kit/tests/kernel/sched/preempt/kernel.scheduler.preempt'
make[2]: Entering directory '/home/druffer/zephyrproject/zephyr/twister-out/pets_v2_dev_kit/tests/kernel/sched/preempt/kernel.scheduler.preempt'
make[3]: Entering directory '/home/druffer/zephyrproject/zephyr/twister-out/pets_v2_dev_kit/tests/kernel/sched/preempt/kernel.scheduler.preempt'
Scanning dependencies of target flash
make[3]: Leaving directory '/home/druffer/zephyrproject/zephyr/twister-out/pets_v2_dev_kit/tests/kernel/sched/preempt/kernel.scheduler.preempt'
make[3]: Entering directory '/home/druffer/zephyrproject/zephyr/twister-out/pets_v2_dev_kit/tests/kernel/sched/preempt/kernel.scheduler.preempt'
Flashing pets_v2_dev_kit
-- west flash: rebuilding
make[4]: Entering directory '/home/druffer/zephyrproject/zephyr/twister-out/pets_v2_dev_kit/tests/kernel/sched/preempt/kernel.scheduler.preempt'
make[5]: Entering directory '/home/druffer/zephyrproject/zephyr/twister-out/pets_v2_dev_kit/tests/kernel/sched/preempt/kernel.scheduler.preempt'
make[6]: Entering directory '/home/druffer/zephyrproject/zephyr/twister-out/pets_v2_dev_kit/tests/kernel/sched/preempt/kernel.scheduler.preempt'
make[6]: Leaving directory '/home/druffer/zephyrproject/zephyr/twister-out/pets_v2_dev_kit/tests/kernel/sched/preempt/kernel.scheduler.preempt'
[  1%] Built target parse_syscalls_target
make[6]: Entering directory '/home/druffer/zephyrproject/zephyr/twister-out/pets_v2_dev_kit/tests/kernel/sched/preempt/kernel.scheduler.preempt'
make[6]: Leaving directory '/home/druffer/zephyrproject/zephyr/twister-out/pets_v2_dev_kit/tests/kernel/sched/preempt/kernel.scheduler.preempt'
[  2%] Built target kobj_types_h_target
make[6]: Entering directory '/home/druffer/zephyrproject/zephyr/twister-out/pets_v2_dev_kit/tests/kernel/sched/preempt/kernel.scheduler.preempt'
make[6]: Leaving directory '/home/druffer/zephyrproject/zephyr/twister-out/pets_v2_dev_kit/tests/kernel/sched/preempt/kernel.scheduler.preempt'
[  2%] Built target syscall_list_h_target
make[6]: Entering directory '/home/druffer/zephyrproject/zephyr/twister-out/pets_v2_dev_kit/tests/kernel/sched/preempt/kernel.scheduler.preempt'
make[6]: Leaving directory '/home/druffer/zephyrproject/zephyr/twister-out/pets_v2_dev_kit/tests/kernel/sched/preempt/kernel.scheduler.preempt'
[  3%] Built target driver_validation_h_target
make[6]: Entering directory '/home/druffer/zephyrproject/zephyr/twister-out/pets_v2_dev_kit/tests/kernel/sched/preempt/kernel.scheduler.preempt'
make[6]: Leaving directory '/home/druffer/zephyrproject/zephyr/twister-out/pets_v2_dev_kit/tests/kernel/sched/preempt/kernel.scheduler.preempt'
[  4%] Built target offsets
make[6]: Entering directory '/home/druffer/zephyrproject/zephyr/twister-out/pets_v2_dev_kit/tests/kernel/sched/preempt/kernel.scheduler.preempt'
make[6]: Leaving directory '/home/druffer/zephyrproject/zephyr/twister-out/pets_v2_dev_kit/tests/kernel/sched/preempt/kernel.scheduler.preempt'
[  5%] Built target offsets_h
make[6]: Entering directory '/home/druffer/zephyrproject/zephyr/twister-out/pets_v2_dev_kit/tests/kernel/sched/preempt/kernel.scheduler.preempt'
make[6]: Leaving directory '/home/druffer/zephyrproject/zephyr/twister-out/pets_v2_dev_kit/tests/kernel/sched/preempt/kernel.scheduler.preempt'
[  5%] Built target zephyr_generated_headers
make[6]: Entering directory '/home/druffer/zephyrproject/zephyr/twister-out/pets_v2_dev_kit/tests/kernel/sched/preempt/kernel.scheduler.preempt'
make[6]: Leaving directory '/home/druffer/zephyrproject/zephyr/twister-out/pets_v2_dev_kit/tests/kernel/sched/preempt/kernel.scheduler.preempt'
[  6%] Built target app
make[6]: Entering directory '/home/druffer/zephyrproject/zephyr/twister-out/pets_v2_dev_kit/tests/kernel/sched/preempt/kernel.scheduler.preempt'
make[6]: Leaving directory '/home/druffer/zephyrproject/zephyr/twister-out/pets_v2_dev_kit/tests/kernel/sched/preempt/kernel.scheduler.preempt'
[ 22%] Built target kernel
make[6]: Entering directory '/home/druffer/zephyrproject/zephyr/twister-out/pets_v2_dev_kit/tests/kernel/sched/preempt/kernel.scheduler.preempt'
make[6]: Leaving directory '/home/druffer/zephyrproject/zephyr/twister-out/pets_v2_dev_kit/tests/kernel/sched/preempt/kernel.scheduler.preempt'
[ 22%] Built target linker_zephyr_prebuilt_script_target
make[6]: Entering directory '/home/druffer/zephyrproject/zephyr/twister-out/pets_v2_dev_kit/tests/kernel/sched/preempt/kernel.scheduler.preempt'
make[6]: Leaving directory '/home/druffer/zephyrproject/zephyr/twister-out/pets_v2_dev_kit/tests/kernel/sched/preempt/kernel.scheduler.preempt'
[ 49%] Built target zephyr
make[6]: Entering directory '/home/druffer/zephyrproject/zephyr/twister-out/pets_v2_dev_kit/tests/kernel/sched/preempt/kernel.scheduler.preempt'
make[6]: Leaving directory '/home/druffer/zephyrproject/zephyr/twister-out/pets_v2_dev_kit/tests/kernel/sched/preempt/kernel.scheduler.preempt'
[ 51%] Built target isr_tables
make[6]: Entering directory '/home/druffer/zephyrproject/zephyr/twister-out/pets_v2_dev_kit/tests/kernel/sched/preempt/kernel.scheduler.preempt'
make[6]: Leaving directory '/home/druffer/zephyrproject/zephyr/twister-out/pets_v2_dev_kit/tests/kernel/sched/preempt/kernel.scheduler.preempt'
[ 52%] Built target arch__common
make[6]: Entering directory '/home/druffer/zephyrproject/zephyr/twister-out/pets_v2_dev_kit/tests/kernel/sched/preempt/kernel.scheduler.preempt'
make[6]: Leaving directory '/home/druffer/zephyrproject/zephyr/twister-out/pets_v2_dev_kit/tests/kernel/sched/preempt/kernel.scheduler.preempt'
[ 60%] Built target arch__arm__core__aarch32
make[6]: Entering directory '/home/druffer/zephyrproject/zephyr/twister-out/pets_v2_dev_kit/tests/kernel/sched/preempt/kernel.scheduler.preempt'
make[6]: Leaving directory '/home/druffer/zephyrproject/zephyr/twister-out/pets_v2_dev_kit/tests/kernel/sched/preempt/kernel.scheduler.preempt'
[ 67%] Built target arch__arm__core__aarch32__cortex_m
make[6]: Entering directory '/home/druffer/zephyrproject/zephyr/twister-out/pets_v2_dev_kit/tests/kernel/sched/preempt/kernel.scheduler.preempt'
make[6]: Leaving directory '/home/druffer/zephyrproject/zephyr/twister-out/pets_v2_dev_kit/tests/kernel/sched/preempt/kernel.scheduler.preempt'
[ 69%] Built target arch__arm__core__aarch32__mpu
make[6]: Entering directory '/home/druffer/zephyrproject/zephyr/twister-out/pets_v2_dev_kit/tests/kernel/sched/preempt/kernel.scheduler.preempt'
make[6]: Leaving directory '/home/druffer/zephyrproject/zephyr/twister-out/pets_v2_dev_kit/tests/kernel/sched/preempt/kernel.scheduler.preempt'
[ 79%] Built target lib__libc__minimal
make[6]: Entering directory '/home/druffer/zephyrproject/zephyr/twister-out/pets_v2_dev_kit/tests/kernel/sched/preempt/kernel.scheduler.preempt'
make[6]: Leaving directory '/home/druffer/zephyrproject/zephyr/twister-out/pets_v2_dev_kit/tests/kernel/sched/preempt/kernel.scheduler.preempt'
[ 81%] Built target lib__posix
make[6]: Entering directory '/home/druffer/zephyrproject/zephyr/twister-out/pets_v2_dev_kit/tests/kernel/sched/preempt/kernel.scheduler.preempt'
make[6]: Leaving directory '/home/druffer/zephyrproject/zephyr/twister-out/pets_v2_dev_kit/tests/kernel/sched/preempt/kernel.scheduler.preempt'
[ 83%] Built target soc__arm__common__cortex_m
make[6]: Entering directory '/home/druffer/zephyrproject/zephyr/twister-out/pets_v2_dev_kit/tests/kernel/sched/preempt/kernel.scheduler.preempt'
make[6]: Leaving directory '/home/druffer/zephyrproject/zephyr/twister-out/pets_v2_dev_kit/tests/kernel/sched/preempt/kernel.scheduler.preempt'
[ 84%] Built target boards__arm__pets_v2_dev_kit
make[6]: Entering directory '/home/druffer/zephyrproject/zephyr/twister-out/pets_v2_dev_kit/tests/kernel/sched/preempt/kernel.scheduler.preempt'
make[6]: Leaving directory '/home/druffer/zephyrproject/zephyr/twister-out/pets_v2_dev_kit/tests/kernel/sched/preempt/kernel.scheduler.preempt'
[ 86%] Built target subsys__testsuite__ztest
make[6]: Entering directory '/home/druffer/zephyrproject/zephyr/twister-out/pets_v2_dev_kit/tests/kernel/sched/preempt/kernel.scheduler.preempt'
make[6]: Leaving directory '/home/druffer/zephyrproject/zephyr/twister-out/pets_v2_dev_kit/tests/kernel/sched/preempt/kernel.scheduler.preempt'
[ 87%] Built target drivers__gpio
make[6]: Entering directory '/home/druffer/zephyrproject/zephyr/twister-out/pets_v2_dev_kit/tests/kernel/sched/preempt/kernel.scheduler.preempt'
make[6]: Leaving directory '/home/druffer/zephyrproject/zephyr/twister-out/pets_v2_dev_kit/tests/kernel/sched/preempt/kernel.scheduler.preempt'
[ 89%] Built target drivers__i2c
make[6]: Entering directory '/home/druffer/zephyrproject/zephyr/twister-out/pets_v2_dev_kit/tests/kernel/sched/preempt/kernel.scheduler.preempt'
make[6]: Leaving directory '/home/druffer/zephyrproject/zephyr/twister-out/pets_v2_dev_kit/tests/kernel/sched/preempt/kernel.scheduler.preempt'
[ 91%] Built target drivers__serial
make[6]: Entering directory '/home/druffer/zephyrproject/zephyr/twister-out/pets_v2_dev_kit/tests/kernel/sched/preempt/kernel.scheduler.preempt'
make[6]: Leaving directory '/home/druffer/zephyrproject/zephyr/twister-out/pets_v2_dev_kit/tests/kernel/sched/preempt/kernel.scheduler.preempt'
[ 92%] Built target ..__zephyr-tmo-sdk__drivers__sensor__tmp108
make[6]: Entering directory '/home/druffer/zephyrproject/zephyr/twister-out/pets_v2_dev_kit/tests/kernel/sched/preempt/kernel.scheduler.preempt'
make[6]: Leaving directory '/home/druffer/zephyrproject/zephyr/twister-out/pets_v2_dev_kit/tests/kernel/sched/preempt/kernel.scheduler.preempt'
[ 94%] Built target zephyr_prebuilt
make[6]: Entering directory '/home/druffer/zephyrproject/zephyr/twister-out/pets_v2_dev_kit/tests/kernel/sched/preempt/kernel.scheduler.preempt'
make[6]: Leaving directory '/home/druffer/zephyrproject/zephyr/twister-out/pets_v2_dev_kit/tests/kernel/sched/preempt/kernel.scheduler.preempt'
[ 95%] Built target linker_zephyr_final_script_target
make[6]: Entering directory '/home/druffer/zephyrproject/zephyr/twister-out/pets_v2_dev_kit/tests/kernel/sched/preempt/kernel.scheduler.preempt'
make[6]: Leaving directory '/home/druffer/zephyrproject/zephyr/twister-out/pets_v2_dev_kit/tests/kernel/sched/preempt/kernel.scheduler.preempt'
[100%] Built target zephyr_final
make[5]: Leaving directory '/home/druffer/zephyrproject/zephyr/twister-out/pets_v2_dev_kit/tests/kernel/sched/preempt/kernel.scheduler.preempt'
make[4]: Leaving directory '/home/druffer/zephyrproject/zephyr/twister-out/pets_v2_dev_kit/tests/kernel/sched/preempt/kernel.scheduler.preempt'
-- west flash: using runner jlink
-- runners.jlink: JLink version: 7.22
-- runners.jlink: Flashing file: /home/druffer/zephyrproject/zephyr/twister-out/pets_v2_dev_kit/tests/kernel/sched/preempt/kernel.scheduler.preempt/zephyr/zephyr.hex
make[3]: Leaving directory '/home/druffer/zephyrproject/zephyr/twister-out/pets_v2_dev_kit/tests/kernel/sched/preempt/kernel.scheduler.preempt'
Built target flash
make[2]: Leaving directory '/home/druffer/zephyrproject/zephyr/twister-out/pets_v2_dev_kit/tests/kernel/sched/preempt/kernel.scheduler.preempt'
make[1]: Leaving directory '/home/druffer/zephyrproject/zephyr/twister-out/pets_v2_dev_kit/tests/kernel/sched/preempt/kernel.scheduler.preempt'
make: Leaving directory '/home/druffer/zephyrproject/zephyr/twister-out/pets_v2_dev_kit/tests/kernel/sched/preempt/kernel.scheduler.preempt'

DEBUG   - DEVICE: Running test suite suite_preempt
DEBUG   - DEVICE: ===================================================================
DEBUG   - DEVICE: START - test_preempt
DEBUG   - DEVICE: PASS - test_preempt in 0.61 seconds
DEBUG   - DEVICE: ===================================================================
DEBUG   - DEVICE: Test suite suite_preempt succeeded
DEBUG   - DEVICE: ===================================================================
DEBUG   - DEVICE: PROJECT EXECUTION SUCCESSFUL
DEBUG   - run status: pets_v2_dev_kit/tests/kernel/sched/preempt/kernel.scheduler.preempt passed
INFO    - 1/1 pets_v2_dev_kit           tests/kernel/sched/preempt/kernel.scheduler.preempt PASSED (device 2.575s)

DEBUG   - running footprint_reports
INFO    - 1 of 1 test configurations passed (100.00%), 0 failed, 0 skipped with 0 warnings in 11.74 seconds
INFO    - In total 1 test cases were executed, 0 skipped on 1 out of total 373 platforms (0.27%)
INFO    - 1 test configurations executed on platforms, 0 test configurations were only built.

Hardware distribution summary:

| Board           | ID   |   Counter |
|-----------------|------|-----------|
| pets_v2_dev_kit |      |         1 |
INFO    - Saving reports...
INFO    - Writing xunit report /home/druffer/zephyrproject/zephyr/twister-out/twister.xml...
INFO    - Writing xunit report /home/druffer/zephyrproject/zephyr/twister-out/twister_report.xml...
INFO    - Run completed

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain Zephyr SDK
 - Commit SHA or Version used: 69a95bcafaf696f86aaada131c298028e6796e89

**Additional context**
N/A

**Comment by nashif** [comment]
you need to specify the "boards" directory, so for example:

cd ../
git clone git@github.com:zephyrproject-rtos/example-application.git
cd zephyr
twister -T samples/hello_world/ -p custom_plank --board-root ../example-application/boards

This works as expected.

**Comment by DRuffer** [comment]
I still have not been able to make it work for me, so I will be looking into this shortly.

I'm not sure how to reopen this though

**Comment by DRuffer** [comment]
Using druffer@druffer-Surface-Pro-2:~/zephyrproject/zephyr$ ./scripts/twister -vvv --device-testing --testcase-root tests/drivers/gpio/gpio_basic_api --hardware-map map2.yml --board-root ../zephyr-tmo-sdk/boards/arm
removes the error message, but still does not run the tests.

Adding a soft link to the project continues to work fine:
druffer@druffer-Surface-Pro-2:~/zephyrproject/zephyr$ cd boards/arm
druffer@druffer-Surface-Pro-2:~/zephyrproject/zephyr/boards/arm$ ln -s ../../../zephyr-tmo-sdk/boards/arm/pets_v2_dev_kit pets_v2_dev_kit

**Comment by DRuffer** [comment]
@catch-twenty-two found a solution for this problem:
``
./scripts/twister -vvv --device-testing --device-serial-baud 9600 --device-serial /dev/ttyUSB1 --platform pets_v2_dev_kit -T  samples/sensor/tmp108/ --board-root /home/jimmy/zephyrupstream/zephyr-tmo-sdk/boards/ --extra-args=BOARD_ROOT=/home/jimmy/zephyrupstream/zephyr-tmo-sdk/
``
Basically, the twister scripts are not passing the BOARD_ROOT parameter

**Comment by carlescufi** [comment]
> @catch-twenty-two found a solution for this problem:
> `./scripts/twister -vvv --device-testing --device-serial-baud 9600 --device-serial /dev/ttyUSB1 --platform pets_v2_dev_kit -T samples/sensor/tmp108/ --board-root /home/jimmy/zephyrupstream/zephyr-tmo-sdk/boards/ --extra-args=BOARD_ROOT=/home/jimmy/zephyrupstream/zephyr-tmo-sdk/`
> Basically, the twister scripts are not passing the BOARD_ROOT parameter

Reopening based on the above

**Comment by nashif** [comment]
BOARD_ROOT is not something twister cares about, this is a build system variable and as you see above, it is different from what you specify to --board-root. So either put this in the module yaml file or declare it before you call twister.

**Comment by CodingGhost** [comment]
@nashif could you explain how to put the board root in the module yaml? I couldnt find out how to do this.

**Comment by Maxxus220** [comment]
https://docs.zephyrproject.org/latest/develop/modules.html
![image](https://github.com/zephyrproject-rtos/zephyr/assets/90416568/6d5351cd-1b13-4b87-8374-fbe3a58db234)

**Comment by porthengrath** [comment]
Just a note to anyone like me who's having this issue, make sure your board yaml file name ends in ".yaml" not ".yml", e.g. "custom_plank.yaml" NOT "custom_plank.yml"....
