### ISSUE TITLE
Bluetooth: Direction Finding: Compiler warning when included in other header files

### ISSUE THREAD

**Issue by saleh-unikie** [zephyrproject-rtos/zephyr#38065]
**Describe the bug**
I am developing an application based on "direction finding" service. when the corresponding header is included in one of my application header files, it generates compiler warnings.

**To Reproduce**
I am using nRF52833DK boards:
1. make a header file (e.g myapp.h) as a part of application
2. add #include <bluetooth/direction.h> to myapp.h
3. include myapp.h in one your application source codes (e.g myapp.c)
4. west build -b nrf52833dk_nrf52833

**Expected behavior**
It is expected to be compiled without any warning.

**Impact**
annoyance!

**Logs and console output**
it is the warning messages:
```
/home/zephyr/zephyrproject/zephyr/include/bluetooth/direction.h:118:39: warning: 'struct bt_le_ext_adv' declared inside parameter list will not be visible outside of this definition or declaration
  118 | int bt_df_set_adv_cte_tx_param(struct bt_le_ext_adv *adv,
      |                                       ^~~~~~~~~~~~~
/home/zephyr/zephyrproject/zephyr/include/bluetooth/direction.h:132:36: warning: 'struct bt_le_ext_adv' declared inside parameter list will not be visible outside of this definition or declaration
  132 | int bt_df_adv_cte_tx_enable(struct bt_le_ext_adv *adv);
      |                                    ^~~~~~~~~~~~~
/home/zephyr/zephyrproject/zephyr/include/bluetooth/direction.h:141:37: warning: 'struct bt_le_ext_adv' declared inside parameter list will not be visible outside of this definition or declaration
  141 | int bt_df_adv_cte_tx_disable(struct bt_le_ext_adv *adv);
      |                                     ^~~~~~~~~~~~~
/home/zephyr/zephyrproject/zephyr/include/bluetooth/direction.h:154:45: warning: 'struct bt_le_per_adv_sync' declared inside parameter list will not be visible outside of this definition or declaration
  154 | int bt_df_per_adv_sync_cte_rx_enable(struct bt_le_per_adv_sync *sync,
      |                                             ^~~~~~~~~~~~~~~~~~
/home/zephyr/zephyrproject/zephyr/include/bluetooth/direction.h:164:46: warning: 'struct bt_le_per_adv_sync' declared inside parameter list will not be visible outside of this definition or declaration
  164 | int bt_df_per_adv_sync_cte_rx_disable(struct bt_le_per_adv_sync *sync);
      |                                              ^~~~~~~~~~~~~~~~~~
[4/10] Linking C executable zephyr/zephyr_prebuilt.elf
```

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: Zephyr SDK
 - Commit SHA: 497cb2e58795142fb3b117eecf21ca8497b04e0a

**Additional context**
N/A

**Comment by ppryga** [comment]
@saleh-unikie Did you include `bluetooth/bluetooth.h` in your source files before include `bluetooth/direction.h`?

**Comment by saleh-unikie** [comment]
No! because only it was needed to access one of the enums (bt_df_antenna_switching_slot), so I didn't include any other header file.

Now I have included the header file you've mentioned and now it doesn't generate warning messages anymore. Thanks!

From software design point of view, is it ok that a header file is dependent to including another header file? For example isn't it better to include `bluetooth/bluetooth.h` into the `bluetooth/direction.h` directly?

**Comment by ppryga** [comment]
This is kind of a policy in Zephyr. Please take a look into other header files. But in many other places you will find usage on #includes as you described.

**Comment by saleh-unikie** [comment]
Thanks a lot for the description. Now it is clear, and I will close the issue.
