### ISSUE TITLE
RT6XX I2S test fails after d92d1f162af3ba24963f1026fc0a304f1a44d1f3

### ISSUE THREAD

**Issue by mmahadevan108** [zephyrproject-rtos/zephyr#38078]
**Describe the bug**
The I2S test `tests/drivers/i2s/i2s_speed` starts to fail after commit: d92d1f162af3ba24963f1026fc0a304f1a44d1f3 

**To Reproduce**
1. mkdir build; cd build
2. cmake -DBOARD=board\mimxrt685_evk_cm33
3. make

**Expected behavior**
The test should pass

**Logs and console output**
Below failure is seen on the console output:
```
E: ***** BUS FAULT *****
E:   Precise data bus error
E:   BFAR Address: 0xc5970e48
E: r0/a1:  0x301822c4  r1/a2:  0x00000000  r2/a3:  0xc5970e48
E: r3/a4:  0x00000001 r12/ip:  0x00000000 r14/lr:  0x18006e55
E:  xpsr:  0x41000000
E: Faulting instruction address (r15/pc): 0x18009b62
E: >>> ZEPHYR FATAL ERROR 0: CPU exception on CPU 0
E: Current thread: 0x30180e10 (test_i2s_transfer_short)
E: Halting system
```

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: e.g Zephyr SDK
 - Commit SHA: 8b13046cb6639449161c41826491947179641211

**Comment by mmahadevan108** [comment]
cc @hakehuang @MaureenHelm @dleach02

**Comment by MaureenHelm** [comment]
Is the driver assuming initialized memory allocation?

**Comment by hakehuang** [comment]
in rt1060 PR this case, starts fail with below log
```
===================================================================
START - test_i2s_dir_both_transfer_short
D: i2s_mcux_write
0->OK
D: i2s_mcux_write
1->OK
D: i2s_mcux_write
2->OK
D: Starting DMA Ch1
D: i2s_mD: RX cb
cux_read
D: i2s_mcux_read
D: need retry

    Assertion failed at WEST_TOPDIR/zephyr/tests/drivers/i2s/i2s_speed/src/test_i2s_speed.c:426: test_i2s_dir_both_transfer_short: ret not equal to 0

 FAIL - test_i2s_dir_both_transfer_short in 2.28 seconds
===================================================================

```

**Comment by mmahadevan108** [comment]
@dcpleung any suggestions for this issue we are seeing the I2S tests

**Comment by dcpleung** [comment]
That's weird... as far as I can tell, the test does not use k_heap.

As for the assert, did it return `-EIO` or `-EAGAIN`? Given the debug message above saying `need retry`, I am assuming `-EAGAIN`. If this is the case, maybe the timeout in the driver is not long enough? Could you try to loop the call to `i2s_mcux_read()` just above the assertion a few times to see if it goes through? I don't have anything hardware on hand to test I2S so I can't debug this locally.

**Comment by mmahadevan108** [comment]
The test uses `k_mem_slab`. Would this change have an impact?

**Comment by dcpleung** [comment]
`K_MEM_SLAB_DEFINE()` is not backed by k_heap. There doesn't seem to be any connection to the failure.

My guess is that this may be due to memory alignment. The k_heap change moves other symbols around in memory. That commit might cause issue if the hardware requires certain memory alignment of the buffers. If this is indeed the case, we have been lucky so far on the test, as adding one `uint32_t` might have broken the test.

**Comment by mmahadevan108** [comment]
Thank you, I was able to find a fix.

**Comment by mmahadevan108** [comment]
Issue has been fixed
