### ISSUE TITLE
Wrong output from printk() with CONFIG_CBPRINTF_NANO=y

### ISSUE THREAD

**Issue by CanastraRF** [zephyrproject-rtos/zephyr#38141]
**Describe the bug**
I want to use CONFIG_CBPRINTF_NANO=y.
For %lu the output can be wrong

**To Reproduce**
I take the blinky sample from zephyr\samples\basic\blinky
I add to prj.conf: CONFIG_CBPRINTF_NANO=y
I add the following code to main()

	const unsigned int ui  =  4000000000U;
	const   signed int sip = +2000000000;
	const   signed int sin = -2000000000;

	const unsigned long ul  =  4000000000UL;
	const   signed long slp = +2000000000L;
	const   signed long sln = -2000000000L;

	printk("ui: %u\n", ui);
	printk("si?: %d - %d\n", sin, sip);

	printk("ul: %lu\n", ul);
	printk("sl?: %ld - %ld\n", sln, slp);

**Expected behavior**
Output should be:
ui: 4000000000
si?: -2000000000 - 2000000000
ul: 4000000000
sl?: -2000000000 - 2000000000  

Output is:
ui: 4000000000
si?: -2000000000 - 2000000000
ul: 18446744073414584320
sl?: -2000000000 - 2000000000 

**Impact**
Can't use CONFIG_CBPRINTF_NANO=y

**Environment (please complete the following information):**
 - OS: Windows 10
 - Toolchain: nRF connect SDK 1.60 with "Booting Zephyr OS build v2.6.0-rc1-ncs1"

**Comment by npitre** [comment]
Please see #38188 for the fix.
