### ISSUE TITLE
aarch32: flags value collision between base IRQ layer and GIC interrupt controller driver

### ISSUE THREAD

**Issue by ibirnbaum** [zephyrproject-rtos/zephyr#38168]
The aarch32 GIC interrupt controller specifies four interrupt cells in its device tree binding:
- type
- irq
- flags
- priority

The flags word is used to declare the sensitivity of an interrupt, where:
- IRQ_TYPE_LEVEL equals 0x0 and
- IRQ_TYPE_EDGE equals 0x1.
This is defined in include/dt-bindings/interrupt-controller/arm-gic.h.

The flags word is evaluated in the ARCH_IRQ_(DIRECT_)CONNECT macros in include/arch/arm/aarch32/irq.h, where a build assertion checks that the IRQ_ZERO_LATENCY flags, defined within the same header as BIT(0), is not set without the CONFIG_ZERO_LATENCY_IRQS feature being activated, which is unsupported on non-Cortex-M CPUs.

Therefore, there's a collision between the definitions IRQ_TYPE_EDGE and IRQ_ZERO_LATENCY in this setup, and any interrupt associated with the GIC that is declared in the respective target's device tree as edge triggered will trigger this assertion when building for a non-Cortex-M aarch32 target that uses the GIC if the corresponding device driver actually hands over the flags from the device tree to IRQ_CONNECT. The majority of peripheral drivers just seems to call IRQ_CONNECT with a constant 0 as flags parameter, but the ARM Architected Timer driver does. That's where I ran into the assertion as for the Cortex-A9, the system timer interrupt is edge triggered.

**To Reproduce**
As of yet, there is no board available in the main repo with which this problem can be reproduced out-of-the-box. It can be reproduced by modifying the device tree of a supported aarch32 Cortex-R board (e.g. qemu_cortex_a5, rcar_h3ulb_cr7) so that the interrupt(s) of an active peripheral are declared IRQ_TYPE_EDGE instead of IRQ_TYPE_LEVEL. The corresponding device driver would have to be modified so that DT_IRQ_BY_IDX(..., flags) instead of 0 is used as the flags parameter of IRQ_CONNECT.

**Expected behavior**
No collision between GIC-specific and IRQ layer generic flag values.

**Impact**
Manual workaround required during current aarch32 Cortex-A development.

**Environment**
Current Ubuntu, Zephyr 2.6.0-2558-gba2bfe87f5b7, Zephyr SDK 0.13.0

**Comment by stephanosio** [comment]
cc @bbolen @carlocaione
