### ISSUE TITLE
modem_context_sprint_ip_addr returns pointer to stack array

### ISSUE THREAD

**Issue by ssharks** [zephyrproject-rtos/zephyr#38172]
In the function modem_context_sprint_ip_addr a local array is constructed. The pointer to that structure is returned. Since this array is constructed on the stack, outside this function, this array does not exist, resulting in unexpected behavior.

File location:
drivers/modem/modem_context.c
Lines 23 - 40.

I see two options to solve this problem:
1. Either pass the array as an argument to the function, so it declared outside this function
2. Return a structure containing the array

**Comment by cfriedt** [comment]
@ssharks - are you able to submit a PR for either of your proposed fixes?

**Comment by ssharks** [comment]
Somewhere next week I'll give it a try.

**Comment by ssharks** [comment]
Currently I'm trying to create a pull request, the code looks to be ready, but I have no simple way to compile the modified drivers to test if the fix doesn't break compilation. Any suggestions how to tackle this?

**Comment by rerickson1** [comment]
> Currently I'm trying to create a pull request, the code looks to be ready, but I have no simple way to compile the modified drivers to test if the fix doesn't break compilation. Any suggestions how to tackle this?

You can run the `drivers/build_all` test on Linux or MacOS using the following command:
`./scripts/twister -v  -T tests/drivers/build_all`
