### ISSUE TITLE
Use of unaligned noinit data hangs qemu_arc_hs

### ISSUE THREAD

**Issue by nordic-krch** [zephyrproject-rtos/zephyr#38207]
**Describe the bug**
Placing not aligned variable in noinit section hangs execution on `qemu_arc_hs`.

**To Reproduce**
Modify hello_world by adding following to `main()`
```
static uint8_t __noinit foo;
printk("%d\n", foo);
```

Build and run `samples/hello_world` for `qemu_arc_hs`. Observe that nothing is printed (even boot banner).
Add `__aligned(sizeof(int))` to `foo` variable or remove `__noinit` and check that data is printed.

**Expected behavior**
Sample should run.

**Environment (please complete the following information):**
 - Commit 49e06ea1e4

Issue is a root cause of #37861.

**Comment by evgeniy-paltsev** [comment]
Fixed by #38817
