### ISSUE TITLE
mbedtls and littlefs on a STM32L4

### ISSUE THREAD

**Issue by jhfigueiredo** [zephyrproject-rtos/zephyr#38202]
### Discussed in https://github.com/zephyrproject-rtos/zephyr/discussions/37329

<div type='discussions-op-text'>

<sup>Originally posted by **jhfigueiredo** July 30, 2021</sup>
I'm quite new to Zephyr so this might just be some missing configuration or lack of knowledge.
The objective is to load a x509 certificate from the filesystem (littlefs) using the mbedtls mbedtls_x509_crt_parse_file function. For that I need to include MBEDTLS_FS_IO. But when I do include this configuration it includes <dirent.h> which then returns the following error:

In file included from /home/jhf/zephyr-sdk-0.12.4/arm-zephyr-eabi/arm-zephyr-eabi/sys-include/dirent.h:39,
                 from /home/jhf/zephyrproject/modules/crypto/mbedtls/mbedtls/library/x509_crt.c:78:
/home/jhf/zephyr-sdk-0.12.4/arm-zephyr-eabi/arm-zephyr-eabi/sys-include/sys/dirent.h:10:2: error: #error "<dirent.h> not supported"
   10 | #error "<dirent.h> not supported"
      |  ^~~~~

I have a work around but would imply changes to the mbedtls original code, which I really would try to avoid.
Any help would be appreciated.
</div>

**Comment by cfriedt** [comment]
@jhfigueiredo - please continue in the original discussion.
