### ISSUE TITLE
xtensa builds fail in CI due to running out of ram to link

### ISSUE THREAD

**Issue by galak** [zephyrproject-rtos/zephyr#38214]
The following commit causes the amount of memory the linker needs to grow drastically such that linking on xtensa builds fails:

9505ee89a3401af93ffddc68e7b04fc948e2f89a

See logs here:

https://buildkite.com/zephyr/zephyr-daily/builds/443#73c88eb1-df25-4260-b43a-c3e84d94f87a

**Comment by galak** [comment]
@dcpleung don't know if you have any ideas on how we might adjust IDT_BASE

**Comment by dcpleung** [comment]
IIRC, on all the modified SoCs, there is nothing after the end of RAM. Maybe we can simply revert that commit?

**Comment by JordanYates** [comment]
> IIRC, on all the modified SoCs, there is nothing after the end of RAM. Maybe we can simply revert that commit?

That's not a robust solution. The previous behavior is equivalent to placing `IDT_LIST` after the `sram` node.
You then can't do this for example:
```
soc {
    sram@0 {
        reg = <0 0x80000>;
    }
    my-sram@80000 {
        reg = <0x80000 0x100>;
    }
}
```
That said, I'm not sure how else to work around this compiler bug.

**Comment by cfriedt** [comment]
@JordanYates, @galak - if there is no clear solution right now, we will have to revert the commit.

**Comment by galak** [comment]
> @JordanYates, @galak - if there is no clear solution right now, we will have to revert the commit.

I think we should revert it for now.

**Comment by andyross** [comment]
I'm just noticing this now.  FWIW: the correct solution here (to having a section that links far from another) is to emit it to a separate ELF phdr, which avoids the need to pad.  But that requires changing a bunch of linker scripts.
