### ISSUE TITLE
board: bl654_usb project: samples/basic/blinky does not blink LED

### ISSUE THREAD

**Issue by carlberg74** [zephyrproject-rtos/zephyr#38245]
Built and flashed the blinky sample project for the bl654_usb board.
following this guide: https://docs.zephyrproject.org/latest/boards/arm/bl654_usb/doc/bl654_usb.html

But the LED does not flash.

Tested also samples/bluetooth/hci_usb, but dongle is not detected as ble device after flashing.
About to test some serial console to see if I get any output from the dongle after flashing.

Environment:
Version: DTC 1.5.0
Python 3.8.10
cmake version 3.21.1
Zephyr version: 2.6.99
Toolchain: zephyr 0.13.0
Build OS: Linux Ubuntu 20.04 (west build, nrfutil pkg generate)
Flash: OS: Windows 10 (nrfutil dfu usb-serial)

**Comment by rerickson1** [comment]
@lairdjm can you help with this?
