### ISSUE TITLE
DHCP Server

### ISSUE THREAD

**Issue by kdhaka** [zephyrproject-rtos/zephyr#38284]
**Is your feature request related to a problem? Please describe.**
When computer connect to my Wifi hotspot, it should assign IP address to the computer.
<https://en.wikipedia.org/wiki/Dynamic_Host_Configuration_Protocol>

**Describe the solution you'd like**
A DHCP server that reply to DHCP client.

**Describe alternatives you've considered**
- BOOTP <https://en.wikipedia.org/wiki/Bootstrap_Protocol>
- Automatic configuration <https://en.wikipedia.org/wiki/Address_autoconfiguration>

**Additional context**
Show up as a Wifi Hotspot and accept configuration.  Used for configuration purpose only.

**Comment by enthunilu** [comment]
Hi all, 

Any update or plan on DHCP server support ?

Thanks!!!

**Comment by rlubos** [comment]
Implemented in https://github.com/zephyrproject-rtos/zephyr/pull/67713
