### ISSUE TITLE
Make Zephyr modules compatible with PlatformIO libdeps

### ISSUE THREAD

**Issue by cfoucher-laas** [zephyrproject-rtos/zephyr#38291]
**Is your enhancement proposal related to a problem? Please describe.**
Currently,  it is not possible to include a Zephyr module as a PlatformIO libdeps, as there are multiple issues emerging from the compilation flow. As PlatformIO is a very widely used tool which provides a user-friendly entry point to Zephyr development, it could be useful to combine the modularity power of these two tools.

Currently, I observed two main issues preventing the joint use of Zephyr modules as PlatformIO libdeps:
- `prj.conf` symbols evaluation/`CMakeList.txt` module reference are done before PlatformIO download of the library;
- Zephyr and PlatformIO both compile the downloaded files, leading to duplicate symbols.

Regarding the first issue, it seems that the CMake evaluation of the symbols (i.e. `CMakeLists.txt` execution and `prj.conf` parsing to check if symbols are valid) is done before PlatformIO downloading the `lib_deps` key content. This leads to compilation flow aborting before there has been any chance to download the module. As a workaround, the first compilation can disable the module by commenting reference to library in`CMakeLists.txt` and symbol in `prj.conf`. Even if the compilation fails, the download occurs and then re-enabling the module will make it be successfully recognized on later compile.

On the second issue, the libdeps are automatically compiled by PlatformIO. But Zephyr will also compile the module as it is part of its code. Thus, duplicated symbols are found and compilation fails. This can be worked around, ether by tweaking the `library.json` file of the PlatformIO library to exclude source files (if the library code is yours and is only intended for this use), or by again disabling the library in PlatformIO confiuration (e.g. using `lib_ignore` or by removing the `lib_deps` key).

A minimal example of this behavior can be found here : https://gitlab.laas.fr/cfoucher/zephyr_module_and_pio_libdeps
Just clone the repository and follow instructions in `README.md`.

**Describe the solution you'd like**
It would be very interesting to make these two functionalities compatible with each other, as they both intend as modularity in the projects.

**Describe alternatives you've considered**
I presented workaround in the first section, that allow the functionalities to work together, but rely on the user taking a series of actions that are not suited for direct use. 

**Additional context**
In our project (https://gitlab.laas.fr/owntech/power-api/core) the end user just has to clone a repository in order to begin developing. We can't ask the user (which is not required to have a knowledge of the underlying mechanics) to take a series of actions (or even run a script) on the first run, and further maintain it when changes are made to a library. Having these two functions compatible with each other would provide us a level of flexibility to work with external modules that would be very appreciated.

**Comment by nordicjm** [comment]
platformio was removed as being a supported system for zephyr recently due to lack of updates/support from platformio, closing as there are no plans to add anything for platformio specific support at the current time.
