### ISSUE TITLE
Synchronize multiple DF TX devices in the DF Connectionless RX Example "Periodic Advertising list"

### ISSUE THREAD

**Issue by Faizan-Ellahi-DE** [zephyrproject-rtos/zephyr#38316]
I got an Unknown Command error while working with the periodic advertising list feature #29127

When I tried to add the device to the Periodic Advertising list or clear the Periodic Advertising list, **error -5** shows over the terminal after deep looking at the source code found the reason for such error is that commands (BT_HCI_OP_LE_ADD_DEV_TO_PER_ADV_LIST, BT_HCI_OP_LE_REM_DEV_FROM_PER_ADV_LIST, BT_HCI_OP_LE_CLEAR_PER_ADV_LIST, BT_HCI_OP_LE_READ_PER_ADV_LIST_SIZE) are not defined/handled in the **static int controller_cmd_handle(uint16_t  ocf, struct net_buf *cmd, struct net_buf **evt, void **node_rx)** function.

Is there any way to solve such a bug, kindly guide me?

**Comment by cvinayak** [comment]
Periodic Advertising List is work in progress, please try this PR: https://github.com/zephyrproject-rtos/zephyr/pull/38338

**Comment by cvinayak** [comment]
@Thalley Does the host support synchronization from periodic advertising lists?

Shouldn't this check addresses in the list? https://github.com/zephyrproject-rtos/zephyr/blob/f50574a6a0773e74efb468265ac94cdbabeb97c1/subsys/bluetooth/host/scan.c#L696-L702

**Comment by Thalley** [comment]
> @Thalley Does the host support synchronization from periodic advertising lists?
> 
> Shouldn't this check addresses in the list?
> 
> https://github.com/zephyrproject-rtos/zephyr/blob/f50574a6a0773e74efb468265ac94cdbabeb97c1/subsys/bluetooth/host/scan.c#L696-L702

Yes, that is actually still missing. Basically we need to implement this paragraph: 
> If the Periodic Advertiser List is not used, the Advertising_SID, Advertiser Address_Type, and Advertiser Address parameters specify the periodic advertising device to listen to; otherwise they shall be ignored.

So if the option to use the list is set, then we shall ignore the address parameters and instead either just accept it, or store the list in the host and validate whether the address of the event is in the list. The former is the simpler solution, and I am not sure if we need to validate the address in the host.
