### ISSUE TITLE
modules: hal: stm32: cube update scripts 

### ISSUE THREAD

**Issue by ABOSTM** [zephyrproject-rtos/zephyr#38453]
**Describe the bug**
Following https://github.com/zephyrproject-rtos/hal_stm32/pull/115
STM32 cube update python scripts should be updated to automate this specific U5 license:
* copy automatically LICENSE file

It is necessary to check why, in  https://github.com/zephyrproject-rtos/hal_stm32/pull/115 there is a specific case for 
* drivers/include/stm32u5xx_ll_rcc.h 
* drivers/include/stm32u5xx_hal_conf.h
and to determine whether automation is required

Note this need to be done after merge of https://github.com/zephyrproject-rtos/hal_stm32/pull/112

**Comment by erwango** [comment]
No longer required
