### ISSUE TITLE
Python script for checking PR errors

### ISSUE THREAD

**Issue by naiyuantian** [zephyrproject-rtos/zephyr#38450]
## Introduction
When reading the code, I found that some of our PRs have many language errors. So I think a python script for checking the errors is needed to help make the project more clear and easy to read. 

### Problem description

In our PRs, there are many grammar mistakes or typos, which will make it hard to understand for users. 

### Proposed change

Create a python script -- which can automatically examine the language, including not only the typos but also the grammar and structure of the sentences. 

### Proposed change (Detailed)

There are a lot of open sources for checking the language mistakes. And we can use it to build the script.

### Dependencies

The script will help the PRs easier to read for developers.

**Comment by nashif** [comment]
if you have something in mind, please submit it as a PR. We already have some spelling coverage in checkpatch.
