### ISSUE TITLE
check_compliance gives very many Kconfig warnings

### ISSUE THREAD

**Issue by asbjornsabo** [zephyrproject-rtos/zephyr#38463]
**Describe the bug**
When running check_compliance locally, it produces around 1650 warnings.  Most of these warnings are Kconfig related warnings, of the form
"warning: the choice symbol <SYMBOL> [...] is defined with a prompt outside the choice"

**To Reproduce**
1) In a shell, from the root of a zephyr checkout, run check_compliance:
<user>@<computer>:~/repoutsjekk/zephyrproject/zephyr$ ./scripts/ci/check_compliance.py

2) Observe the warnings

**Expected behavior**
No warnings.
I would expect contributors to run check_compliance and fix the cause of warnings in parts of the code they are responsible for or have touched.

**Impact**
No significant impact.
But I do think that either these warnings are important, and should be fixed.  Or, they are not important, in which case the warning is not needed.

**Logs and console output**
As in the example above

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: Zephyr SDK
 - Commit: Has been observed since some time summer 2021.

**Comment by tejlmand** [comment]
@asbjornsabo Thanks for reporting this.
Fixed here: https://github.com/zephyrproject-rtos/zephyr/pull/38774
