### ISSUE TITLE
json: JSON Library Orphaned, Request to Become a Maintainer

### ISSUE THREAD

**Issue by Sir-Branch** [zephyrproject-rtos/zephyr#38477]
Apologies in advance if the format is incorrect, didn't find a template or previous issue for Orphaned code. 

The JSON library appears to be orphaned (technically JSON Web Token, because the JSON library is a subsystem of the OS) according to [MAINTAINERS.YML](https://github.com/zephyrproject-rtos/zephyr/blob/main/MAINTAINERS.yml), @mrfuchs appears a collaborator (@M1cha has also recently submitted a couple of PRs).

The library currently isn't fully compatible with C++. I have a couple of PRs open for improvements #37941 #38052 #38061. I'm looking to improve the general functionality, maintainability and readability of the code. It's not a very easy code to follow and there's some architectural shortcomings in my opinion.

What's the process to become a maintainer for these files ( [/lib/os/json.c](https://github.com/zephyrproject-rtos/zephyr/blob/main/lib/os/json.c) and [include/data/json.h](https://github.com/zephyrproject-rtos/zephyr/blob/main/include/data/json.h))? I know there's a lot of work to be done in the testing side, I don't have much experience with twister and unit test on Zephyr but I'm willing to learn.

Given that this is part of the OS I should also probably aim for MISRA-C compliance according to #9552. 

Thanks & Best Regards,
Ramiro

**Comment by cfriedt** [comment]
Please submit a PR to add yourself as maintainer
