### ISSUE TITLE
boards: beaglev_starlight_jh7100: integrate manual flashing steps using python so that west flash works

### ISSUE THREAD

**Issue by cfriedt** [zephyrproject-rtos/zephyr#38484]
**Is your enhancement proposal related to a problem? Please describe.**
In [the docs](https://docs.zephyrproject.org/latest/boards/riscv/beaglev_starlight_jh7100/doc/index.html), it mentions
> The bootloader expects size information at the start of the binary file, so the bin file needs to be processed first to include that information. Download the helper script from starfive-tech github repo here

with a link pointing to 

https://github.com/starfive-tech/freelight-u-sdk/blob/starfive/fsz.sh

Additionally, there are some manual steps required (open `minicom`, use xmodem protocol, etc).

**Describe the solution you'd like**
It would probably be helpful to simply integrate those processes into some board-specific hook when west is invoked

Most of these additional steps can be hidden from the user. E.g. the *binary* does not need to be prefixed by its size, but the bootloader expects that the size appear first on the wire.

Additionally, the python xmodem package can be used to transmit data via python, as long as the correct uart can be specified or detected.

**Describe alternatives you've considered**

**Additional context**
The additional manual processes raised a flag for me when reviewing #38397

**Comment by henrikbrixandersen** [comment]
You may be able to find some inspiration in how post processing is done in https://github.com/zephyrproject-rtos/zephyr/blob/main/boards/arm/arty/CMakeLists.txt

**Comment by cfriedt** [comment]
Damn... the other 2 links to Seeed Studio's site for that board return 404. I heard production was delayed until next year. Odd that they would take down the BeagleV Getting Started guide and the bootloader docs.
