### ISSUE TITLE
drivers: modem: bg9x: Kconfig values compiled into `autoconf.h` even if it isn't being used

### ISSUE THREAD

**Issue by ycsin** [zephyrproject-rtos/zephyr#38535]
**Describe the bug**
The bg9x modem's [Kconfig](https://github.com/zephyrproject-rtos/zephyr/blob/main/drivers/modem/Kconfig.quectel-bg9x) is lacking the `if MODEM_QUECTEL_BG9X` `endif` guard to prevent its default values from being compiled into the `autoconf.h`

**To Reproduce**
1. Build anything
2. Check the `autoconf.h` for bg9x related configs

**Expected behavior**
Kconfig default values should be compiled only when its source is being used.

**Impact**
`autoconf.h` pollution.

**Comment by cfriedt** [comment]
Thanks!!
