### ISSUE TITLE
ISO broadcast cannot send with callback if CONFIG_BT_CONN=n

### ISSUE THREAD

**Issue by Thalley** [zephyrproject-rtos/zephyr#38563]
**Describe the bug**
https://github.com/zephyrproject-rtos/zephyr/pull/38194 introduced a bug for ISO broadcast if CONFIG_BT_CONN=n. 
If CONFIG_BT_CONN=n then the `free_tx` FIFO is never intiialized, causes the FIFO to be empty and thus no able to use the `bt_conn_send_cb` function that `bt_iso_chan_send` now relies on. 

Update: It seems that TX still works, but the callback is missing.

**To Reproduce**
Build and run `samples/bluetooth/iso_broadcast/` and see the `<err> bt_conn.bt_conn_send_cb: Unable to allocate TX context` error

**Expected behavior**
Expect broadcast ISO to be fully independent on CONFIG_BT_CONN. 

**Impact**
Showstopper for specific builds. Increased memory usage as a work around. 

**Logs and console output**
N/A

**Environment (please complete the following information):**
 - Commit SHA or Version used: cd5357ca56c2629b957a3a79a3dd71fe528e2626

**Additional context**

**Comment by carlescufi** [comment]
@Thalley will you send a fix in time for 2.7.0?

**Comment by Thalley** [comment]
> @Thalley will you send a fix in time for 2.7.0?

That's the plan :)

**Comment by Thalley** [comment]
Updated the priority to low as the callback is just missing, but it is still sending data.
