### ISSUE TITLE
Process: binary blobs in Zephyr

### ISSUE THREAD

**Issue by mbolivar-nordic** [zephyrproject-rtos/zephyr#38570]
This tracks ongoing discussions around the distribution or inclusion of binary blobs related to Zephyr development.

Current status (9 December 2021):

- The process WG has debated this at length and written a proposal describing the problem and a proposal for how blobs could be included more formally by the project: https://docs.google.com/document/d/1heqcv7dzGvM5rA9xpTMW3kyKJLpZsl2Gjsmr5eqBje8/edit (this a cleaner version of [another document](https://docs.google.com/document/d/16QU8OT4pnKuhszZHIYfsj1WInN-LRXjPdt87hxG5IRU/edit#) which contains an audit trail of discussions and their resolution.)
- pull request https://github.com/zephyrproject-rtos/zephyr/pull/41044 for the zephyr documentation reflects a "no blobs allowed" policy
- The goal is to have the TSC consider these two alternatives and vote on them

**Comment by mbolivar-nordic** [comment]
Process WG:

- distributing binary blobs in the default distribution (YY path through the problem statement's decision diagram) is explicitly rejected due to lack of backers and doubtful acceptance by the board
- @mbolivar-nordic to provide a detailed proposal for what it would look like for blobs to be totally out of scope (N path)
- remaining WG time on this issue will be devoted to rejecting/accepting particular policies for mechanisms that users can use to fetch blobs (YN path)

The N and YN paths will be presented as a single up-or-down vote (to approve the YN path or reject it and therefore implicitly accept the N path) to the TSC.

**Comment by mbolivar-nordic** [comment]
Process WG:

- additional decisions were taken in the live document linked to in the issue description

**Comment by mbolivar-nordic** [comment]
Process WG:

- No consensus on finding a maintainer before getting a vote, agree to continue discussion, but also involve Espressif and SiLabs with a view towards getting them involved

**Comment by marc-hb** [comment]
First commit adding a new `west blob` command: 336aa9dc88
First documentation commit 2c301fe22f53468
