### ISSUE TITLE
Builds with macOS SDK are failing

### ISSUE THREAD

**Issue by Sn0wfreezeDev** [zephyrproject-rtos/zephyr#38572]
**Describe the bug**

When building anything on macOS I receive an error. 

```
west build -p auto -b nrf52dk_nrf52832 samples/basic/blinky
```

```c
/zephyrproject/zephyr/arch/arm/include/aarch32/cortex_m/stack.h:29:8: error: argument to 'section' attribute is not valid for this target: mach-o section specifier requires a segment whose length is between 1 and 16 characters
extern K_KERNEL_STACK_ARRAY_DEFINE(z_interrupt_stacks, CONFIG_MP_NUM_CPUS,
       ^
```

**To Reproduce**

I downloaded the SDK and installed the toolchain for macOS. 
I strictly followed the tutorial on the [Zephyr Website](https://docs.zephyrproject.org/latest/getting_started/index.html), which seems outdated for macOS, as it says it's not supported. 

So I followed the [Nordic getting started guide](https://developer.nordicsemi.com/nRF_Connect_SDK/doc/0.4.0/zephyr/getting_started/index.html) for setting up the toolchain. 

I set the environment to `ZEPHYR_TOOLCHAIN_VARIANT=host`

**Expected behavior**
The build should complete 

**Impact**
This is a showstopper since the Toolchain does not run 

**Logs and console output**
Can be found above. 

**Environment (please complete the following information):**
 - OS macOS 
 - Toolchain Zephyr SDK
 - Commit cd5357ca56c2629b957a3a79a3dd71fe528e2626

**Comment by carlescufi** [comment]
>I set the environment to ZEPHYR_TOOLCHAIN_VARIANT=host

I am not quite sure this is right. @tejlmand ?
