### ISSUE TITLE
HL7800 PSM not working as intended

### ISSUE THREAD

**Issue by rerickson1** [zephyrproject-rtos/zephyr#38617]
**Describe the bug**
When using PSM (power save mode), and app should be able to send socket data at any time.
Currently if the app try to send data when the HL7800 is asleep, the HL7800 does not wake up properly and restore the IP connection and sockets.

**To Reproduce**
Build this sample app with PSM turned on: https://github.com/LairdCP/Pinnacle_100_Sample_Applications/tree/master/apps/low_power

**Expected behavior**
The user app should not have to be aware of the HL7800 sleep state. The app should be able to send data when it wants and the HL7800 driver should do the proper wake up tasks in order to send the data.

**Impact**
Showstopper for those interested in using PSM.

**Comment by bsphere** [comment]
i think this issue is related - https://github.com/zephyrproject-rtos/zephyr/issues/60546
