### ISSUE TITLE
Multiple potential dead-locks modem_socket_wait_data

### ISSUE THREAD

**Issue by ssharks** [zephyrproject-rtos/zephyr#38632]
This function implements to block to receive incoming modem data. There are at least 2 ways this could lead to a deadlock situation:

1. On receiving
The function works in tandem with modem_socket_data_ready. This function read the sock->is_waiting flag, and and gives a semaphore if the socket was waiting. If the function is executed between the function modem_socket_data_ready reads sock->is_waiting and gives the semaphore, the function modem_socket_wait_data keeps waiting forever.

2. On socket closure
There is no mechanism in place to unlock the function modem_socket_wait_data when a socket is being closed. This way the function modem_socket_wait_data can be still waiting for data that can never come anymore.

This affects the ublox driver.

**Comment by jonathan-wdtl** [comment]
1. also affects bg9x driver. 

2. There is a mechanism to unblock. offload_close calls modem_socket_put -> k_sem_reset.
"Any outstanding semaphore takes will be aborted with -EAGAIN." This unblocks modem_socket_wait_data. I don't ublox hardware, not sure if what driver does after this is valid.
