### ISSUE TITLE
drivers: modem: gsm_ppp: Add support for Quectel modems

### ISSUE THREAD

**Issue by ycsin** [zephyrproject-rtos/zephyr#38653]
**Is this request related to a missing driver support for a particular hardware platform, SoC or board? Please describe.**
Multiple Quetel modems supports the PPP and maybe GSM MUX, the current `gsm_ppp` driver should be able to support these modems with minimal changes.

**Describe why you are asking for this support?**
I'm currently using Quectel modems in my custom board.

**Additional context**
The [CMUX document](https://forums.quectel.com/uploads/short-url/uoB16C44M5IzrdgmZ87PPJ9axSc.pdf) is available [publicly on the internet](https://www.google.com/search?q=quectel+at%2Bcmux+site%3Aforums.quectel.com&rlz=1C1SQJL_enMY906MY907&oq=quectel+at%2Bcmux+site%3Aforums.quectel.com).
Based on my testing, a Quectel modem can support the GSM MUX without publicly stating it in the reference manual, so Quectel user should just try.

**Comment by tcpipchip** [comment]
Hi,
I am using that driver, GSM_PPP (Generic), but i never getting the GATEWAY and  MASK, they always are returning 0.0.0.0 and 0.0.0.0
I only got the IP
I am testing in three u-blox models, LISA U200, G350 and G450.
Looks that the problem is that we dont have the USER and PASSWORD option on GENERIC_MODEM

**Comment by ycsin** [comment]
@tcpipchip 

> Looks that the problem is that we dont have the USER and PASSWORD option on GENERIC_MODEM
> Yes, the GSM_PPP needs a reset option to MODEM :(

Maybe create another issue(s) for these?
This issue is for the support of Quectel modems, and will be closed automatically when PR #38652 get merged

**Comment by tcpipchip** [comment]
Ok!
