### ISSUE TITLE
Add real support for MIMXRT1050_EVK_QSPI

### ISSUE THREAD

**Issue by ainguraXmarquiegui** [zephyrproject-rtos/zephyr#38665]
**Is your enhancement proposal related to a problem? Please describe.**
Zephyr currently has a compile target named `mimxrt1050_evk_qspi` that any newcomer to the platform would expect to work as straightforward as any other target. Unfortunately, images compiled for this target cannot be flashed with `west flash`, and if flashed with some other methods, they will not boot.

**Describe the solution you'd like**
I would like to integrate my proposed changes to all of these: zephyr repository, `modules/hal/nxp` and `bootloader/mcuboot`:

https://github.com/ainguraXmarquiegui/zephyr/tree/feature/mimxrt1050_evk_qspi_support
https://github.com/ainguraXmarquiegui/hal_nxp/tree/feature/mimxrt1050_evk_qspi_support
https://github.com/ainguraXmarquiegui/mcuboot/tree/feature/mimxrt1020_evk_mimxr1050_evk_qspi_support

The hal changes adds support for the QSPI flash. My code change proposition uses the config flags to decide whether to compile hyperflash or QSPI flash support.

On the zephyr part, I propose to add a link to the SEGGER documentation where they explain what needs to be manually modified to be able to flash a QSPI board. When merging these code changes, `westl.yml` shoud point to the correct hal revision with support for QSPI boot.

**Describe alternatives you've considered**
I think improving the documentation, and adding code changes to really support the platform are our best alternative. It would be even better if SEGGER would add support for both hyperflash and QSPI, but I think that's outside the scope of this project.

**Comment by ainguraXmarquiegui** [comment]
@MaureenHelm
@dleach02

**Comment by mmahadevan108** [comment]
Thank you for the changes, kindly submit your PR's and we will be happy to review and merge.

**Comment by ainguraXmarquiegui** [comment]
We can close the issue and keep tracking progress in the pull requests.
