### ISSUE TITLE
DNS-SD library does not support `_services._dns-sd._udp.local` meta-query for service enumeration

### ISSUE THREAD

**Issue by AllemanMa** [zephyrproject-rtos/zephyr#38673]
**Is your enhancement proposal related to a problem? Please describe.**
When building and running the mdns_responder sample, the device won't show up in avahi-browse or zeroconfServiceBrowser automatically. The device will only reply when you specifically query the following: `avahi-browse -t -r _zephyr._tcp`.

It seems like `_services._dns-sd._udp.<domain>` meta-query handling is not implemented.

When I open up zeroconfServiceBrowser or avahi-browse, the following is printed out at regular intervals: 
`net_dns_sd.dns_sd_extract_service_proto_domain: (rx_q[0]): could not get proto for '▒▒...'`

**Describe the solution you'd like**
The device should respond properly to the meta-query `_services._dns-sd._udp.<domain>` so that my device is displayed automatically in avahi-browse without having to specifically query `avahi-browse -t -r _zephyr._tcp`

**Comment by cfriedt** [comment]
The specific feature is called "service type enumeration" and is mentioned in the RFC on section 9.

https://datatracker.ietf.org/doc/html/rfc6763#section-9
