### ISSUE TITLE
The coap_server sample is missing the actual send in the retransmit routine

### ISSUE THREAD

**Issue by AllemanMa** [zephyrproject-rtos/zephyr#38697]
**Describe the bug**
If a device can't reach it's destination, it will get into `retransmit_request` for several times to decrement its retries, however no actual send is performed which makes the retransmit request useless.

**To Reproduce**
1. Build the coap_server sample
2. Observe the resource i.e. `coap get -o coap://xx.xx.xx.xx/obs`
3. Stop the coap client
4. Wait until the coap server gets into the retransmit_request

**Expected behavior**
I would expect the coap server to actual resend a message instead of just decrementing the retries.

**Impact**
It leaves the coap server retry mechanism useless.

**Environment (please complete the following information):**
 - Zephyr v2.6.0

**Comment by cfriedt** [comment]
@AllemanMa - are you able to submit any PRs for this or other coap issues? tests welcome as well.

**Comment by rlubos** [comment]
I've submitted a fix in https://github.com/zephyrproject-rtos/zephyr/pull/38748, indeed the retransmission mechanism was broken.
