### ISSUE TITLE
drivers: syscon: missing implementation

### ISSUE THREAD

**Issue by henrikbrixandersen** [zephyrproject-rtos/zephyr#38737]
**Describe the bug**
The syscon API (`include/drivers/syscon.h`) added in commit bc305984565a8f30e8afd02026dc99c16853a362 lacks an implementation. The generic syscon driver (`drivers/syscon/syscon.c`) implements the API functions, but uses different naming, so linking will fail.

This was never caught by CI since there are no in-tree users/testcases/samples using the syscon driver API.

The low-impact bug fix would just be renaming the functions in `drivers/syscon/syscon.c` to match those of the API, but a new approach, which addresses both the missing implementation, missing tests and generalizes the functionality even more, was already approved (#37424).

I suggest we merge #37424 for v2.7.0.

**Impact**
The syscon API lacks an in-tree implementation.

**Comment by carlocaione** [comment]
Weird, I wonder if something went wrong on my side when pushing. Anyway, merging #37424 sounds good to me.
