### ISSUE TITLE
kernel/mem_domain: Remove dead case in check_add_partition()

### ISSUE THREAD

**Issue by LixinGuoX** [zephyrproject-rtos/zephyr#38815]
**Describe the bug**
I find some code that would never be reached here in mem_domain.c(lines 57-61), the code shows as below:
```
	if (part->size == 0U) {
		LOG_ERR("zero sized partition at %p with base 0x%lx",
			part, part->start);
		return false;
	}

	pstart = part->start;
	pend = part->start + part->size;

	if (pend <= pstart) {
		LOG_ERR("invalid partition %p, wraparound detected. base 0x%lx size %zu",
			part, part->start, part->size);
		return false;
	}
```
With situation where `part->size == 0U` excluded above, I think add `part->size`(long unsigned int) to `pend` will make 
`pend `larger than `pstart` and this `if (pend <= pstart)` will never be satisfied.
Or, is it possible for partition address to be wraparound?
So, I think we should delete this `if (pend <= pstart){}` code.

**Impact**
It will influence the code coverage.

**Comment by dcpleung** [comment]
This is error checking to prevent integer overflow which would make `pend` less than `pstart`. So this is not an issue.
