### ISSUE TITLE
There is no valid date setting function in the RTC driver of the LL Library of STM32

### ISSUE THREAD

**Issue by DylanSang** [zephyrproject-rtos/zephyr#38899]
There is no valid date setting function in the RTC driver of the LL Library of STM32

I want to use the RTC universal interface function for setting time and date based on STM32 ll library

I see that the current counter function implemented in the rtc driver of stm32 based on the ll library only obtains the value, and the set value function does not implement the corresponding function.

**Comment by erwango** [comment]
Same as https://github.com/zephyrproject-rtos/zephyr/issues/35333.
