### ISSUE TITLE
ITE RISCV I2C driver returning positive values for error instead of negative values

### ISSUE THREAD

**Issue by Asthachavda** [zephyrproject-rtos/zephyr#38959]
**Describe the bug**
While tried to bind the i2c driver, wrote the 1-byte data in particular address (using i2c_write API), received positive number as an error instead of negative error code.   

**To Reproduce**
1. Wrote a simple code to test the I2C interface for ITE board.
2. Try to write & read the data using aardvark
3. Used aardvark as a slave

**Expected behavior**
It must be giving Negative number for error or zero for success as per the Standard. 
(https://docs.zephyrproject.org/apidoc/latest/group__i2c__interface.html#ga2cc5f49493dce89e128ccbfa9d6149a0)

**Impact**
EC app. code fail to understand the error, because of wrong return code.

**Logs and console output**
***** delaying boot 1ms (per build configuration) *****
*** Booting Zephyr OS build zephyr-v2.6.0-804-gb7b7709eecb0  (delayed boot 1ms) ***
Failed to write 8

**Environment (please complete the following information):**
 - OS: Linux (Ubuntu 18.04.5)
 - Toolchain: Zephyr SDK 12.04
 - Board used: ITE IT8XXX2 (RISC-V 32)

**Comment by yingmingx** [comment]
Hi, in reproduce step 3, you haven't connect any slave device. I'm confused on it. 
Because when we use i2c, we should physically connect the device with the host controller. Then the host will send device address bitor R/W bit and hoping to get the ACK. 
If we haven't connect the slave device physically, we cannot get the right response.
Could you please check you hardware connection？

**Comment by Asthachavda** [comment]
Hi, We used aardvark I2C host adapter as a master.

**Comment by NagarajuGundimi** [comment]
Issue is NOT about whether I2C driver is working or not, Its about why ITE I2C driver returning +ve values for error instead of -ve values. This should have been caught in code reviews itself. No need to have any test setup and test case to reproduce it.
