### ISSUE TITLE
MCP2515 driver CS gpio active high support issue

### ISSUE THREAD

**Issue by zoedemertzis** [zephyrproject-rtos/zephyr#38988]
**Describe the bug**
`SPI_CS_ACTIVE_HIGH` not supported when setting `spi_cfg.operation` in mcp2515 driver when `cs-gpio` is `GPIO_ACTIVE_HIGH` in devicetree. 

What have you tried to diagnose or workaround this issue?
Manually set `dev_data->spi_cfg.operation = SPI_WORD_SET(8) | SPI_CS_ACTIVE_HIGH;` in `mcp2515_init`

**To Reproduce**
```
&spi4 {
    compatible = "nordic,nrf-spim";
    status = "okay";
    cs-gpios = <&gpio0 16 GPIO_ACTIVE_HIGH>;
    sck-pin = <2>;
    mosi-pin = <3>;
    miso-pin = <15>;

	can0: can@0 {
		compatible = "microchip,mcp2515";
		spi-max-frequency = <8000000>;
		int-gpios = <&gpio0 26 GPIO_ACTIVE_LOW>;
		reg = <0>;
		status = "okay";
		label = "CAN_0";
		osc-freq = <20000000>;
		bus-speed = <250000>;
		sjw = <1>;
		prop-seg = <2>;
		phase-seg1 = <7>;
		phase-seg2 = <6>;
		#address-cells = <1>;
		#size-cells = <0>;
	};
};
```
results in `"Devicetree and spi_context CS levels are not equal"` error from `spi_context.h` because `SPI_CS_ACTIVE_HIGH` is not set in spi config operation field

**Expected behavior**
Expect the mcp2515 driver to set the `SPI_CS_ACTIVE_HIGH` flag when the `cs-gpios` gpio is `GPIO_ACTIVE_HIGH`

**Impact**
Annoyance for now but something we can't move forward with. Don't want to modify the driver, not sure if I'm introducing any other issues by doing so.

**Logs and console output**
If applicable, add console logs or other types of debug information
![image](https://user-images.githubusercontent.com/19480523/135325270-e2f0fe15-13b9-41f2-9e02-eaa0ee5c5567.png)

**Environment (please complete the following information):**
 - OS:Linux
 - Toolchain (e.g Zephyr SDK, ...)
 - board: nrf5340

**Comment by henrikbrixandersen** [comment]
This was fixed in commit 41325bd1fbf4e494da9a6e81dafa9373d0e927a0 in #37325. I am no longer able to reproduce this on HEAD (e1ad3b2ab3a0b1b849782df8a557487c9ab0612e) using a `frdm_k64f` board and a `dfrobot_can_bus_v2_0` shield.
