### ISSUE TITLE
sensor: fdc2x1x: warnings and compilation errors when PM_DEVICE is used

### ISSUE THREAD

**Issue by skullbox305** [zephyrproject-rtos/zephyr#39115]
**Describe the bug**
The bug is related to changes made to the way the power management is used and only apply when `PM_DEVICE=y`:

1. Due to the removal of the internal pm_state in `drivers/sensor/fdc2x1x/fdc2x1x.h` two instances of `struct fdc2x1x_data *data` in `fdc2x1x.c` (line 488 and 616) are unused, which cause warnings during compilation.

2. Due to the removal of the arguments `dev` and `arg` in `pm_info()` in `samples/sensor/fdc2x1x/main.c`, the lines 39 (`ARG_UNUSED(dev)`) and 40 (`ARG_UNUSED(arg)`) cause compilation errors.

3. The switch in `pm_info()` in `samples/sensor/fdc2x1x/main.c` is not handling the state `PM_DEVICE_STATE_LOW_POWER`, which is unsupported by the sensor. This causes warnings during compilation.

**To Reproduce**
1. set `PM_DEVICE=y` in `proj.conf` in `samples/sensor/fdc2x1x`
2. compile with `west build -b nrf9160dk_nrf9160`
3. see warnings and compilation errors

For the solution, see PR #39077

**Comment by nashif** [comment]
fixed by #39077
