### ISSUE TITLE
ztest:  Broken on NRF52840 Platform  

### ISSUE THREAD

**Issue by pratapnaidu** [zephyrproject-rtos/zephyr#39123]
**Describe the bug**
 ztest crashing on NRF52840 starting from 2.6.0 release, but working find prior

**To Reproduce**
1. mkdir build; cd build
2. cmake -DBOARD=nrf52840dk_nrf52840 tests/drivers/adc/adc_api
3. make
4. openocd -f interface/cmsis-dap.cfg -f target/nrf52.cfg -c "program zephyr.bin" -c "init" -c "reset" -c "exit"
5. /scripts/twister -vv --device-testing --jobs 1 --hardware-map map.yaml --west-flash --west-runner=pyocd -p nrf52840dk_nrf52840 -T tests/drivers/adc/adc_api

**Expected behavior**
Twister should execute the test case and prompt the test as passed, but instead, device timeout, as the internal firmware crashed

**Impact**
Unable to run the test framework

**Logs and console output**

| Platform            | ID                                               | Serial device   |
|---------------------|--------------------------------------------------|-----------------|
| nrf52840dk_nrf52840 | 1102000050203220324e4a54323035323330303597969903 | /dev/ttyACM0    |

INFO    - Adding tasks to the queue...
DEBUG   - adding nrf52840dk_nrf52840/tests/drivers/adc/adc_api/drivers.adc
INFO    - Added initial list of jobs to queue
DEBUG   - Launch process 0
DEBUG   - Running cmake on /home/forgelab/Projects/twister_zephyr/zephyr-experiment-old/zephyrproject/zephyrproject/zephyr/tests/drivers/adc/adc_api for nrf52840dk_nrf52840
DEBUG   - Calling cmake with arguments: ['-B/home/forgelab/Projects/twister_zephyr/zephyr-experiment-old/zephyrproject/zephyrproject/zephyr/twister-out/nrf52840dk_nrf52840/tests/drivers/adc/adc_api/drivers.adc', '-S/home/forgelab/Projects/twister_zephyr/zephyr-experiment-old/zephyrproject/zephyrproject/zephyr/tests/drivers/adc/adc_api', '-DEXTRA_CFLAGS="-Werror"', '-DEXTRA_AFLAGS="-Wa,--fatal-warnings', '-DEXTRA_LDFLAGS="-Wl,--fatal-warnings"', '-DEXTRA_GEN_DEFINES_ARGS=--err-on-deprecated-properties', '-GUnix Makefiles', '-DBOARD=nrf52840dk_nrf52840']
DEBUG   - Finished building /home/forgelab/Projects/twister_zephyr/zephyr-experiment-old/zephyrproject/zephyrproject/zephyr/tests/drivers/adc/adc_api for nrf52840dk_nrf52840
DEBUG   - build test: nrf52840dk_nrf52840/tests/drivers/adc/adc_api/drivers.adc
DEBUG   - Building /home/forgelab/Projects/twister_zephyr/zephyr-experiment-old/zephyrproject/zephyrproject/zephyr/tests/drivers/adc/adc_api for nrf52840dk_nrf52840
DEBUG   - run test: nrf52840dk_nrf52840/tests/drivers/adc/adc_api/drivers.adc
DEBUG   - Using serial device /dev/ttyACM0
DEBUG   - Flash command: ['west', 'flash', '--skip-rebuild', '-d', '/home/forgelab/Projects/twister_zephyr/zephyr-experiment-old/zephyrproject/zephyrproject/zephyr/twister-out/nrf52840dk_nrf52840/tests/drivers/adc/adc_api/drivers.adc', '--runner', 'pyocd', '--', '--board-id', '1102000050203220324e4a54323035323330303597969903']
DEBUG   - -- west flash: using runner pyocd
-- runners.pyocd: Flashing file: /home/forgelab/Projects/twister_zephyr/zephyr-experiment-old/zephyrproject/zephyrproject/zephyr/twister-out/nrf52840dk_nrf52840/tests/drivers/adc/adc_api/drivers.adc/zephyr/zephyr.hex
[---|---|---|---|---|---|---|---|---|----]
[========================================]

DEBUG   - Timed out while monitoring serial output on nrf52840dk_nrf52840
DEBUG   - run status: nrf52840dk_nrf52840/tests/drivers/adc/adc_api/drivers.adc timeout
INFO    - 1/1 nrf52840dk_nrf52840       tests/drivers/adc/adc_api/drivers.adc              FAILED Timeout (device 64.507s)
ERROR   - see: /home/forgelab/Projects/twister_zephyr/zephyr-experiment-old/zephyrproject/zephyrproject/zephyr/twister-out/nrf52840dk_nrf52840/tests/drivers/adc/adc_api/drivers.adc/device.log

**Environment (please complete the following information):**
 - OS: (Linux)
 - Toolchain (gnuarmemb)
 - Commit SHA or Version used 
 Commit: 79a6c07536bc14583198f8e3555df6134d8822cf   
 Version: (2.6.0)

**Additional context**
After  debugging through the code, found out the exception is happening in device.c file within the following code, but fixing is code haven't helped with the situation

	for (entry = levels[level]; entry < levels[level+1]; entry++) {
		const struct device *dev = entry->dev;
		int rc = entry->init(dev);------------------------------------->Crashing here because of null pointer exception
		if (dev != NULL) {
			/* Mark device initialized.  If initialization
			 * failed, record the error condition.
			 */
			if (rc != 0) {
				if (rc < 0) {
					rc = -rc;
				}
				if (rc > UINT8_MAX) {
					rc = UINT8_MAX;
				}
				dev->state->init_res = rc;
			}
			dev->state->initialized = true;
		}
	}
}

**Comment by gmarull** [comment]
The test works well on `main` (used ef0d955758e549f39d97b07089dedc4bdd05bc0e).

You can try to just run (no more commands are needed):
```
./scripts/twister --device-testing --device-serial /dev/ttyACM0 -p nrf52840dk_nrf52840 -T tests/drivers/adc/adc_api -vv
```

Adjust `--device-serial` as needed.
