### ISSUE TITLE
subsys/net/ip/tcp2: Missing feature to decrease Receive Window size sent in the ACK messge

### ISSUE THREAD

**Issue by ycsin** [zephyrproject-rtos/zephyr#39132]
**Is your feature request related to a problem? Please describe.**
TCP2 implementation missing the feature to limit the amount of data sent by the server by decreasing the Receive Window size sent in the ACK messge, effectively giving no limits to the server and can overload a constrained embedded device.

**Describe the solution you'd like**
Implement the feature in TCP2.

**Additional context**
[comment](https://github.com/zephyrproject-rtos/zephyr/issues/37324#issuecomment-934167646)

**Comment by rlubos** [comment]
This isn't implemented yet.
