### ISSUE TITLE
gsm_ppp: stop & starting not working as expected with nullpointer dereference & no full modem init

### ISSUE THREAD

**Issue by wcappelle** [zephyrproject-rtos/zephyr#39144]
**Describe the bug**
When stopping & starting the modem, the rssi_work_handle can lead to nullpointer crash in the timeout.c::remove_timeout. This due to the re-initialization of the rssi_work_handle in the gsm start, while the work was still sheduled (so re-init the sys_snode_t to nullpointers).
A similar error could occur with the gsm_configure if the stop & start is done while it's work is still ongoing (although very little chance since init & reshedule is just after eachother)

Next to the crash, when the modem starts, not all commands are re-executed due to a flag being set in the previous gsm_configure stage:
gsm_finalize_connection: gsm->attached. This leads to skipping the setup commands the next gsm start (like echo & disabling URC for network registration).

**To Reproduce**
```
//First time startup of the 
gsm_ppp_stop()
modem_reset() //own function --> takes about 12 seconds
gsm_ppp_start()

// Wait some time like 40 seconds
gsm_ppp_stop()
modem_reset() //own function --> takes about 12 seconds
gsm_ppp_start()
--> sometimes crash at this point 
```
Reproduction rate is about 70% for me

**Environment (please complete the following information):**
I'm using the GSM_MUX configuration with a Quectell BG95.
MODEM_GSM_RSSI_POLLING_PERIOD is set to 30 (I think it will be less visible with bigger timeouts)
This work is done on the 2.7.0-rc1 branch + single commit to fix PPP UART name

**Comment by ycsin** [comment]
Reopen issue as this is still an active issue since neither #39175 nor #38596 is merged
