### ISSUE TITLE
Improve ztest test suites (setup/teardown/before/after + OOD)

### ISSUE THREAD

**Issue by yperess** [zephyrproject-rtos/zephyr#39153]
**Is your enhancement proposal related to a problem? Please describe.**
Current implementation of zephyr's test suites and unit tests is hard to use. Setup and teardown functions have to be
set per unit test and rely on setting up global state. Additionally, all unit tests have to be declared in the same compilational unit which makes it hard to use `#ifdef` macros to guard them. Test suites also don't have a way to retain state which is configured via the setup function. This means that unit tests rely on global state and can be buggy or at least risky.

**Describe the solution you'd like**
I would like for the ztest framework to be closer aligned with modern testing frameworks. This means that the following changes should be implemented:
1. The declaration of a test suite should be separate from adding unit tests to it. It should look like:
```
ztest_test_suite(
    my_test_suite, /* The name of the test suite */
    my_predicate_fn, /* A predicate function to decide if the suite should be run now */
    my_struct_t, /* A type used for the struct containing the suite's data */
    my_setup_fn, /* The suite's setup function (called before the suite is run) */
    my_before_fn, /* The setup function to call before each unit test in the suite */
    my_after_fn, /* The teardown function to call after each unit test in the suite */
    my_teardown_fn /* The teardown function to call when the suite finishes all unit tests */
);

// Example use:
struct my_data {
  bool setup;
  bool before;
};

void my_setup_fn(struct my_data *data)
{
  data->setup = true;
}

void my_before_fn(struct my_data *data)
{
  data->before = true;
}

void my_after_fn(struct my_data *data)
{
  data->before = false;
}

void my_teardown_fn(struct my_data *data)
{
  data->setup = false;
}

ztest_test_suite(
    my_test_suite,
    /* predicate= */ NULL,
    struct my_data,
    my_setup_fn,
    my_before_fn,
    my_after_fn,
    my_teardown_fn
);
```
2. The unit tests should be added at any point after and should accept the same type as the data structure associate with the test suite.
```
ztest_unit_test(my_test_suite, test_fn)(struct my_data *data)
{
  zassert_true(data->setup, NULL);
  zassert_true(data->before, NULL);
}
```

This will all be relatively easy to implement, but it does break current APIs. Might be a good candidate for v3.0. If accepted, I would suggest maybe doing this in a feature branch?

**Describe alternatives you've considered**
I've considered bringing in a third party testing framework, but they all appear too complex for Zephyr, especially if we want them to be compiled and run on the devices.

**Comment by jeremybettis** [comment]
Assuming that PR #39714 is merged as is, the next step really ought to be to set CONFIG_ZTEST_NEW_API=n in all existing tests, and then default it to y to encourage new tests to use the new api.
