### ISSUE TITLE
esp32: Undocumented dependency of libpython2

### ISSUE THREAD

**Issue by adalava** [zephyrproject-rtos/zephyr#39212]
The following error message is seen when building esp32 on a system without python2 installed:

`/home/alfredoj/.espressif/tools/zephyr/xtensa-esp32-elf/bin/xtensa-esp32-elf-gdb: error while loading shared libraries: libpython2.7.so.1.0: cannot open shared object file: No such file or directory
`
I think it's undocumented dependency, but depends on python3 instead would be nice, if possible.

Fix/workaround: sudo apt install libpython2.7

**To Reproduce**

1. Fresh install Ubuntu 20.04
2. Install zephyr
3. Install espressif tools https://docs.zephyrproject.org/latest/boards/xtensa/esp32/doc/index.html
4. Run: west build -b esp32 samples/hello_world

**Expected behavior**
Run without errors. The gdb console should appear when executing /home/alfredoj/.espressif/tools/zephyr/xtensa-esp32-elf/bin/xtensa-esp32-elf-gdb

**Impact**
gdb debugger not working.
**Environment (please complete the following information):**
 - OS: Ubuntu 20.04
 - Toolchain: espressif
 - 4dedae5861a9a0ea83bbe8ac917e002c9bb50216

**Comment by b0661** [comment]
Adding **-DPYTHON=${PYTHON_EXECUTABLE}** before here
https://github.com/zephyrproject-rtos/zephyr/blob/4dedae5861a9a0ea83bbe8ac917e002c9bb50216/boards/xtensa/esp32/CMakeLists.txt#L21 made it work in my Ubuntu 20.04 environment.

There is no real dependency on Python2. It perfectly works with Python3.

**Comment by adalava** [comment]
Thanks!
You can see the error message during `west build` bellow, right after "-- Found toolchain:", but yes, the build works fine.

```
$ rm -rf build/
$ west build -b esp32 samples/hello_world
-- west build: generating a build system
Including boilerplate (Zephyr base): /home/alfredoj/zephyrproject/zephyr/cmake/app/boilerplate.cmake
-- Application: /home/alfredoj/zephyrproject/zephyr/samples/hello_world
-- Zephyr version: 2.7.99 (/home/alfredoj/zephyrproject/zephyr), build: v2.7.0-rc3-315-g4dedae5861a9
-- Found Python3: /usr/bin/python3.8 (found suitable exact version "3.8.10") found components: Interpreter 
-- Found west (found suitable version "0.11.1", minimum required is "0.7.1")
-- Board: esp32
-- Cache files will be written to: /home/alfredoj/.cache/zephyr
-- Found dtc: /usr/bin/dtc (found suitable version "1.5.0", minimum required is "1.4.6")
-- Found BOARD.dts: /home/alfredoj/zephyrproject/zephyr/boards/xtensa/esp32/esp32.dts
-- Generated zephyr.dts: /home/alfredoj/zephyrproject/zephyr/build/zephyr/zephyr.dts
-- Generated devicetree_unfixed.h: /home/alfredoj/zephyrproject/zephyr/build/zephyr/include/generated/devicetree_unfixed.h
-- Generated device_extern.h: /home/alfredoj/zephyrproject/zephyr/build/zephyr/include/generated/device_extern.h
-- Including generated dts.cmake file: /home/alfredoj/zephyrproject/zephyr/build/zephyr/dts.cmake
Parsing /home/alfredoj/zephyrproject/zephyr/Kconfig
Loaded configuration '/home/alfredoj/zephyrproject/zephyr/boards/xtensa/esp32/esp32_defconfig'
Merged configuration '/home/alfredoj/zephyrproject/zephyr/samples/hello_world/prj.conf'
Configuration saved to '/home/alfredoj/zephyrproject/zephyr/build/zephyr/.config'
Kconfig header saved to '/home/alfredoj/zephyrproject/zephyr/build/zephyr/include/generated/autoconf.h'
-- Found toolchain: espressif (/home/alfredoj/.espressif/tools/zephyr)
/home/alfredoj/.espressif/tools/zephyr/xtensa-esp32-elf/bin/xtensa-esp32-elf-gdb: error while loading shared libraries: libpython2.7.so.1.0: cannot open shared object file: No such file or directory
-- The C compiler identification is GNU 8.4.0
-- The CXX compiler identification is GNU 8.4.0
-- The ASM compiler identification is GNU
-- Found assembler: /home/alfredoj/.espressif/tools/zephyr/xtensa-esp32-elf/bin/xtensa-esp32-elf-gcc
-- Configuring done
-- Generating done
-- Build files have been written to: /home/alfredoj/zephyrproject/zephyr/build
-- west build: building application
[1/154] Preparing syscall dependency handling
..
..
..
..

esptool.py v3.1-dev
Merged 5 ELF sections

```
