### ISSUE TITLE
Random MAC with native posix target

### ISSUE THREAD

**Issue by TomekSleboda** [zephyrproject-rtos/zephyr#39244]
**Is your enhancement proposal related to a problem? Please describe.**
With configuration for native posix target:
CONFIG_ENTROPY_GENERATOR=y
CONFIG_ETH_NATIVE_POSIX_RANDOM_MAC=y

'Fake entropy native posix' driver is selected, resulting in random MAC config not working well (same MAC assigned all the time).

**Describe the solution you'd like**
Modify eth_native_posix.c:eth_iface_init not to use entropy driver, but system clock (k_cycle_get_32 or something similar)

**Describe alternatives you've considered**
Implement TRNG driver for x86 (e.g. when CONFIG_FAKE_ENTROPY_NATIVE_POSIX=n).

**Comment by aescolar** [comment]
@TomekSleboda The native_posix entropy generator is pseudo-random. If you want different random values in different runs you need to provide it a different seed.
If you want to just feed a different seed automatically in each run you can do
`zephyr.exe --seed=$RANDOM `

**Comment by aescolar** [comment]
Closing, as the request goes against the reproducible principle of the native_posix target, and there is a simple way of getting the same result on invocation.
