### ISSUE TITLE
STM32L562E-DK display support

### ISSUE THREAD

**Issue by lochej** [zephyrproject-rtos/zephyr#39289]
**Is this request related to a missing driver support for a particular hardware platform, SoC or board? Please describe.**
The STM32L562E-DK platform embeds a ST7789H2 driving a 240x240 TFT LCD screen as well as a FT6236 I2C touch controller.
This makes it an ideal development platform for small GUI applications.
The display controller is wired to the STM32 FMC interface.

**Describe why you are asking for this support?**
Development with the LVGL and Zephyr capabilities on this board and provide display demo with colors.
I can contribute on this task since I have the hardware. 
But I'm unsure about the FMC usage through the **memc/sdram** driver for STM32 or about the structure of the configuration files. 

To me there is a few things to do to get the display working:

Main objective: _Make the LCD work_
- [x] Create an ST7789H2 bitbanging driver to make to make the display work
- [x] Develop a kscan driver for the FT6236 touch controller (dt-bindings, kconfig, c driver source), I2C + 2 gpios (RST, INT) -> **No need the current FT5336 is compatible so only DT definition and .conf are needed**

Secondary objective: _Make it efficient_
- [x] Define the FMC dt-bindings and update the dtsi for the STM32L5 SOC (example can be taken from the H7 series)
- [x] Update the stm32l562e-dk board DT to define the pinctrl-0 of the FMC (example can be taken from stm32h747i_disco) and setup the interface to be LCD compatible (need FMC-SRAM mode)
- [ ] Update the ST7789H2 driver based to use the FMC interface (20 lines) + 4 gpios (RST, TE, Power, backlight) 
- [x] Develop a kscan driver for the FT6236 touch controller (dt-bindings, kconfig, c driver source), I2C + 2 gpios (RST, INT) -> No need the current FT5336 is compatible
- [ ] Create display samples with **stm32l562e-dk.conf** and **stm32l562e-dk.overlay** for display and lvgl samples

**Additional context**
Reference manuel : um2617
![image](https://user-images.githubusercontent.com/1338015/136627426-2a06bda1-cddd-490f-bd85-ddacdffd8a84.png)

**Comment by douardda** [comment]
Is there any interest in making FMC/FSMC based LCD drivers? I'm currently playing with a (clone) [Black STM32F407VE](https://stm32-base.org/boards/STM32F407VET6-STM32-F4VE-V2.0) board with an ILI-9341 based LCD display in 16b 8080 mode, I would have loved to be able to test zephyr to do so. The support for stm32's FMC/FSMC seems very limited, and the provided ili9343 driver seems to have the SPI transport layer hardcoded, and it should be possible to use any other LCD controller the same.

Before digging too much, I wonder if there have already been some work in this direction. Ideally, the LCD driver should be decoupled from the transport layer (SPI, parallel, etc), and the parallel communication should also be configurable (direct gpios vs controllers like stm32's FMC/FSMC,etc.) via the devicetree.
