### ISSUE TITLE
`BT_SETTINGS=y` without `bt_enable()` causes MPU fault

### ISSUE THREAD

**Issue by NZSmartie** [zephyrproject-rtos/zephyr#39317]
**Describe the bug**

Enabling the Settings subsystem  for use with a project using a SD card mounted with a FAT file system works as intended. However, when the Bluetooth subsystem is also enabled, then a MPU Fault is caused in most cases the as `settings_load()` is called. Or some other failure. related to the file system.

**To Reproduce**

I've modified the [samples/syubsys/settings](https://github.com/NZSmartie/zephyr/tree/samples/settings-fs-backed) sample to include support for SD card backed settings to make it easier to reproduce this problem.

1. `git clone https://github.com/NZSmartie/zephyr -b samples/settings-fs-backed`
2. Modify `samples/subsys/settings/boards/nrf52840_blip.conf` and add:

   ```property
   # Enable Bluetooth subsys
   CONFIG_BT=y
   CONFIG_BT_SETTINGS=y
   ```

3. `west build -b nrf52840_blip`
4. `west flash`
5. See error

**Expected behavior**
The settings sample project using the FAT FS backend and with the Bluetooth subsys enabled (`CONFIG_BT=y`) to run to completion.

**Impact**
What impact does this issue have on your progress (e.g., annoyance, showstopper)

**Logs and console output**
```
*** Booting Zephyr OS build v2.7.99-420-g9c4366f1ae33  ***

*** Settings usage example ***

disk mount: OK.
settings subsys initialization: OK.
subtree <alpha> handler registered: OK
subtree <alpha/beta> has static handler

##############
# iteration 0
##############

=================================================
basic load and save using registered handlers

load all key-value pairs using registered handlers
<alpha/beta/voltage> = -3450
<alpha/beta/source> =
<alpha/angle/1> = 18
<alpha/length/1> = 58
<alpha/length/2> = 42
loading all settings under <beta> handler is done
ASSERTION FAIL [err == 0] @ WEST_TOPDIR/zephyr/subsys/bluetooth/host/hci_core.c:306
        k_sem_take failed with err -11
```

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04 x64
 - Toolchain: zephyr SDK 0.13.1
 - g9c4366f1ae

**Additional context**

**Comment by carlescufi** [comment]
@NZSmartie you wrote `MPU fault` in the title but the description says:

```
ASSERTION FAIL [err == 0] @ WEST_TOPDIR/zephyr/subsys/bluetooth/host/hci_core.c:306
        k_sem_take failed with err -11
```

which is a timeout when sending an HCI command. Which one is it?

**Comment by NZSmartie** [comment]
Spent a while looking into the issue and it's both!
Also, please excuse the slight confusion. I've encoutnered this issue in `v2.6.0`, but i've recreated the issue using a sample project on the repository's main branch. 

The HCI command does time out and the following line creates the kernel panic:
```
<err> os: r0/a1:  0x00000003  r1/a2:  0x00000000  r2/a3:  0x20000d28       
<err> os: r3/a4:  0x00000002 r12/ip:  0x00000000 r14/lr:  0x000061b9       
<err> os:  xpsr:  0x41000000                                               
<err> os: EXC_RETURN: 0x0                                                  
<err> os: Faulting instruction address (r15/pc): 0x000061c4                
<err> os: >>> ZEPHYR FATAL ERROR 3: Kernel oops on CPU 0                   
<err> os: Current thread: 0x20001818 (main)                                
```

```sh
arm-zephyr-eabi-addr2line -e build/zephyr/zephyr.elf 0x000061c4
/home/nzsmartie/myproject/zephyr/subsys/bluetooth/host/hci_core.c:308 (discriminator 3)
```

The settings API when initialised will attempt to commit the settings. https://github.com/zephyrproject-rtos/zephyr/blob/b7063164916e9e9359a58b871f1cce12cf1debfb/subsys/bluetooth/host/settings.c#L232-L249

However, the BT TX thread hasn't started yet (it's the last operation in bt_enable()`, so there is nothing to process the HCI commands, like the one one created by `bt_setup_public_id_addr`. 

As for the MPU fault (now seems to be called *Kernel oops*), the next line after k_sem_take creates teh fault when the status property is accessed.

**Comment by carlescufi** [comment]
@NZSmartie could you please put together a small branch/sample that reproduces the issue so that we can reproduce it locally and then fix it?

**Comment by carlescufi** [comment]
@NZSmartie ping

**Comment by carlescufi** [comment]
> However, the `BT TX` thread hasn't started yet (it's the last operation in `bt_enable()`), so there is nothing to process the HCI commands, like the one one created by `bt_setup_public_id_addr`.

@jhedberg could you take a look at the statement above and see if this is indeed something that can happen?

**Comment by jhedberg** [comment]
@carlescufi @NZSmartie I might be missing something, but I don't see how that can happen. The threads are indeed started in `bt_enable()` but that's done before calling the bt_ready callback (or returning from `bt_enable()` in case it's called synchronously with a NULL callback). Remember that `settings_load()` should not be called before `bt_enable()`, rather the right place for it is in the bt_ready callback or after bt_enable() returns (if it was called with a NULL callback).

**Comment by alwa-nordic** [comment]
It seems to me that the crash happens because there is no call to `bt_enable()` in the sample.

I believe this is a bug in the stack. The application may want to delay Bluetooth initialization but still make use of `settings_load()` early.

**Comment by carlescufi** [comment]
@jhedberg @alwa-nordic as per @alwa-nordic 's analysis, the fix would be to exit early in `set()` and `commit()` in `subsys/bluetooth/host/settings.c` if Bluetooth is not enabled. That sounds like the proper fix.

**Comment by alwa-nordic** [comment]
@jhedberg I think it should be safe to call `settings_load_subtree("bt")` at least. I'll add this to the doc.
