### ISSUE TITLE
TFM: Split trusted-firmware-m repository

### ISSUE THREAD

**Issue by joerchan** [zephyrproject-rtos/zephyr#39353]
## Introduction

Split the zephyr project maintained repository trusted-firmware-m into a fork of the individual upstream repositories

## Problem description

In the current setup of the TF-M repositories the history of the upstream repositories are lost.
This complicates the maintainability of the project, for example:
 - Checking if a fix has been included
 - Checking why a change was made
 - Cherry-picking important fixes outside of a regular sync-up.
 - Bisecting

## Proposed change

Split the current trusted-firmware-m repository into a per-repository fork of upstream.

## Detailed RFC
Create 3 forks of the upstream repositories:
 - https://git.trustedfirmware.org/TF-M/trusted-firmware-m.git
   revision: a199c3047f320a2f82b9a0c27af5b50991184e0f
 - https://git.trustedfirmware.org/TF-M/tf-m-tests.git
   revision: b0c06b46b8a32d73794637e2a034a9cfbb4e883b
 - https://github.com/ARM-software/psa-arch-tests.git 
   revision: 02d145d80da31bc78ce486bda99ad55597fea0ca

Apply the current set of downstream patches to the individual repositories.
The organization of the folders would remain the same.

### Dependencies

Affects projects / users that have forked the current repository (i.e NCS).

## Alternatives

Do nothing

**Comment by SebastianBoe** [comment]
I support this.

Usually we fork repositories instead of copying them. I do not consider TF-M to be exceptional enough
to deviate from this.

**Comment by galak** [comment]
> The tf-m tests repo is providing the same value as the files in zephyr/tests do, the ability to regression test Zephyr's integration with TF-M.

We should look at this in a bit more detail and discuss if tf-m-tests.git should be optionally pulled in and move the zephyr integration into that zephyr fork of tf-m-tests.git
