### ISSUE TITLE
STM32L496 uart rx interrupt mode not working

### ISSUE THREAD

**Issue by glin00** [zephyrproject-rtos/zephyr#39395]
**Describe the bug**
I had problem that on my STM32L496 uart rx interrupt mode is not working. 
I tested both the uart tx and rx polling mode and both are working. 

Following is my uart related config
CONFIG_STDOUT_CONSOLE=y
CONFIG_PRINTK=y

#UART related
CONFIG_SERIAL=y
CONFIG_UART_INTERRUPT_DRIVEN=y
CONFIG_UART_STM32=y
CONFIG_UART_3_INTERRUPT_DRIVEN=y
CONFIG_UART_3_ASYNC=y

Following is my uart code
const struct device *uart_dev;
const struct uart_config uart_cfg = {
		.baudrate = 115200,
		.parity = UART_CFG_PARITY_NONE,
		.stop_bits = UART_CFG_STOP_BITS_1,
		.data_bits = UART_CFG_DATA_BITS_8,
		.flow_ctrl = UART_CFG_FLOW_CTRL_NONE
};
uint8_t uart_buffer[512];
uint16_t uart_buf_idx=0;
uint16_t uart_buf_len=0;
bool uart_buf_ready=false;
static uint8_t recvData;

static void uart_fifo_callback(const struct device *dev, void *user_data)
{
	
		/* Verify uart_irq_update() */
	if (!uart_irq_update(dev)) {
		//TC_PRINT("retval should always be 1\n");
		return;
	}

	if (uart_irq_rx_ready(dev)) {
		/* Verify uart_fifo_read() */
		uart_fifo_read(dev, &recvData, 1);
		uart_buf_ready=true;
		uart_buffer[0]=recvData;
		uart_buf_len=1;
	}
}

void main(void)
{
     uart_dev = device_get_binding("UART_3"); 

	if (!device_is_ready(uart_dev)) {
		//TC_PRINT("UART device not ready\n");
		return ;
	}

	/* Verify configure() - set device configuration using data in cfg */
	int ret = uart_configure(uart_dev, &uart_cfg);

	if (ret == -ENOSYS) {
		return ;//TC_SKIP;
	}
	
	/* Verify uart_irq_callback_set() */
	uart_irq_callback_set(uart_dev, uart_fifo_callback);

	/* Enable Tx/Rx interrupt before using fifo */
	uart_irq_rx_enable(uart_dev);
	uart_irq_tx_disable(uart_dev);

	while (1) {
		if (uart_buf_ready) {
			uart_fifo_send_data(uart_buffer, uart_buf_len);
			uart_buf_ready=false;
		}
	}
}

Can anyone give me some advise regarding this issue?

**Expected behavior**
uart rx interrupt should work.

**Impact**
Although uart rx polling mode is working for me, but it is not efficient comparing to interrupt mode.

**Environment (please complete the following information):**
Linux Ubuntu 20.04.3 LTS
Zephyr SDK,-0.13.0
Zephyr SHA1 ID:bb85a55

**Additional context**

**Comment by glin00** [comment]
after I change my code from usart3 to usart2 in dts file, the above interrupt mode program can start to work. So, I will try to use usart2 in the meantime.  
But if I want to use usart3 for interrupt mode later on, do you have any advises how to debug this problem?

**Comment by erwango** [comment]
From what I can see hardware blocks USART3 and USART2 are strictly equivalent.
From software point of view, they will also share the same instantiated code.
The only difference could be the device tree description (but it seems correct), or the pin assignation.
But if you say that USART3 is working in polling mode then I guess that pin and dts description are also correct.
So I'm not sure what could be wrong here.

**Comment by erwango** [comment]
> how to debug this problem?

Advice would be to monitor USART3 registers
See if properly configured and then monitor USART_ISR

**Comment by erwango** [comment]
@glin00 is this issue still valid ?

**Comment by glin00** [comment]
I will come back to this issue later since I need to focus on other higher priority issues first.
