### ISSUE TITLE
CTE report callback have the wrong pointer to bt_le_per_adv_sync

### ISSUE THREAD

**Issue by jakkra** [zephyrproject-rtos/zephyr#39405]
**Describe the bug**
In `cte_report_cb` the parameter `struct bt_le_per_adv_sync *sync` is not correct it's always the one corresponding to "handle" 0.
Calling `bt_le_per_adv_sync_get_index(sync)` always returns 0 for all synced CTE transmitters.

I think the reason is that in [lll_sync.c:L944](https://github.com/zephyrproject-rtos/zephyr/blob/8ed9f6406437de75d1e0dc294a7177f44513e5e0/subsys/bluetooth/controller/ll_sw/nordic/lll/lll_sync.c#L944) `iq_report->hdr.handle` is not filled in, hence it's always zero.

**To Reproduce**
1. Modify the sample direction_finding_connectionless_rx to sync with more than one periodic advertiser and set `CONFIG_BT_PER_ADV_SYNC_MAX=2` (anything above 1).
2. Compile above application and stock direction_finding_connectionless_tx.
3. Flash two devices with direction_finding_connectionless_tx and one with direction_finding_connectionless_rx.
4. Study the logs and you can see that [this print](https://github.com/zephyrproject-rtos/zephyr/blob/8ed9f6406437de75d1e0dc294a7177f44513e5e0/samples/bluetooth/direction_finding_connectionless_rx/src/main.c#L168) always will print CTE[0].

**Expected behavior**
Below code not always printing handle 0 when synced to multiple periodic advertisers.
```
static void cte_recv_cb(struct bt_le_per_adv_sync *sync,
			struct bt_df_per_adv_sync_iq_samples_report const *report)
{
	uint8_t index = bt_le_per_adv_sync_get_index(sync);
	printf("CTE sync handle: %d\n");
}
```

**Impact**
Not possible to see from which advertiser a CTE is sent, major impact as it's not possible to do DF with more than one synced device.

**Environment (please complete the following information):**
 - OS: Windows
 - Toolchain:Zephyr SDK
 - Commit SHA or Version used: commit 8ed9f6406437de75d1e0dc294a7177f44513e5e0 (origin/main, origin/HEAD as of now)

**Log**
[log.txt](https://github.com/zephyrproject-rtos/zephyr/files/7339449/log.txt)

**Comment by jakkra** [comment]
Thanks @ppryga it seems to work as expected now.

**Comment by saleh-unikie** [comment]
I encountered a similar problem this week and hopefully provided fix has solved my problem too, thanks @ppryga 

But there is a minor problem after switching to the above fix, if `max_cte_count` of `struct bt_df_per_adv_sync_cte_rx_param ` has been set to 0, it doesn't receive any CTE data.
