### ISSUE TITLE
arduino_nano_33_ble_sense: Add More Devices to the Device Tree

### ISSUE THREAD

**Issue by DhruvaG2000** [zephyrproject-rtos/zephyr#39431]
**Is your enhancement proposal related to a problem? Please describe.**
The arduino_nano_33_ble_sense has many on-board sensors and also features an RGB LED which can and should be imo added to the device tree. This will help run the rgb example on this board which currently is not supported.

**Describe the solution you'd like**
One can refer to [this detailed schematic](https://content.arduino.cc/assets/NANO33BLE_V2.0_sch.pdf) and then make the necessary additions to either [arduino_nano_33_ble.dts](https://github.com/zephyrproject-rtos/zephyr/blob/main/boards/arm/arduino_nano_33_ble/arduino_nano_33_ble.dts) or create a new one entirely specifically for arduino_nano_33_ble_sense.

**Describe alternatives you've considered**
None

**Additional context**
The aim is to make zephyr as easy to use with the arduino_nano_33_ble_sense as it is with the [Arduino IDE and mbed-os](https://docs.arduino.cc/hardware/nano-33-ble-sense).

**Comment by henrikbrixandersen** [comment]
Please submit PRs for adding more functionality to the board.
