### ISSUE TITLE
Scanning for devices sending periodic advertisements stops working after a while, but keeps reporting none periodic.

### ISSUE THREAD

**Issue by jakkra** [zephyrproject-rtos/zephyr#39438]
**Describe the bug**
From what I can read it's ok to keep scanning enabled while using `bt_le_per_adv_sync_create` etc. By removing the `scan_disable()` in direction_finding_connectionless_rx sample scanning stops working after a while. The standard scan callback keeps reporting standard advertisements, but stops reporting devices sending periodic advertisments. I guess the extended scanning stops working, but normal continues. (never getting in [here ](https://github.com/zephyrproject-rtos/zephyr/blob/82d7d3c5c98296fde51f157e54583f535e4dee12/samples/bluetooth/direction_finding_connectionless_rx/src/main.c#L198) as `info->interval `is always 0.

**To Reproduce**
1. Use latest Zephyr direction_finding_connectionless_tx on one device
2. Use latest Zephyr direction_finding_connectionless_rx on another device and commit out call to `scan_disable()` in `main`. Also comment out the large print in `scan_recv` to avoid to much spam in the logs.
3. Power on the tag, wait for sync and IQ data, then reset the device.
4. Re-do step 3. a few times until the sending device will not be found anymore.

**Expected behavior**
Continuous scanning still reporting devices sending periodic advertisements until scan is stopped. Or that application get notfied somehow that scanning stopped.

**Impact**
Application ends up in an unknown state and quirky workarounds are necessary (I assume restarting scanning will work, but have not tried it. If that does not work then impact is larger.

**Logs and console output**
In the log I added a print in `scan_recv` to show that scanning is still running, but no device advertising periodic are found.
[log.txt](https://github.com/zephyrproject-rtos/zephyr/files/7345929/log.txt)

**Environment (please complete the following information):**
 - OS: Windows
 - Toolchain (e.g Zephyr SDK, ...): Zephyr SDK
 - Commit SHA or Version used: 429d6cf055766d63add2a000ba81c522d2e24f77

**Comment by cvinayak** [comment]
@jakkra please check if reverting this helps: https://github.com/zephyrproject-rtos/zephyr/commit/190532bcc4d54879c71a83a13382718630c21a70

**Comment by ppryga** [comment]
Hello @jakkra 

I've taken a look on the issue. Thank you for reporting it by the way. I checked the commit you have pointed as the one that causes the problem as well as one before: 04e2e84cb7a319657c2b63a3f5fe69668ba144b5.
It looks that there is the same behavior, after resetting advertising device the periodic advertising sync is not established with advertiser. In my case I was able to reproduce it every second reset.

I'd like to ask you to run a test to confirm my findings. Build the received with this option `CONFIG_BT_CTLR_DUP_FILTER_LEN=0`.

There is a filtering duplicates functionality implemented in HCI. It looks that is it is a feature that has a side effect.
When periodic advertising is established first time, everything works correctly. After reset of advertiser it is possible that received will scan the device and add it to duplicate list. Then terminated periodic advertising timeouts. 
Receiver will not sync again with the advertiser because all advertisements after first one were dropped by filter.

It looks like there is no bug in this case. But I still there is some enhancement that possibly may be implemented to filtering functionality. 
@cvinayak what it your opinion about it?

**Comment by jakkra** [comment]
Hi, I don't think it's the same thing we reproduce, if the issue is with the duplicate filter that the tag is in it, then after resetting the tag (or starting a new one) then periodic advertismenets from any device should be found right? I reset the tag to make it loose the sync and tag starts with a new MAC every reset, hence should not be in the filter.

But anyway I tried again with that and can still reproduce, see full log:
[log.txt](https://github.com/zephyrproject-rtos/zephyr/files/7497727/log.txt)

Commit: 429d6cf055766d63add2a000ba81c522d2e24f77
[diff.txt](https://github.com/zephyrproject-rtos/zephyr/files/7497749/diff.txt)

**Comment by jakkra** [comment]
Also there is another problem maybe it's the same issue or it is related to https://github.com/zephyrproject-rtos/zephyr/issues/39432, anyway the problem is the same (no periodic adv found). 

Code is same as in my prevous comment except I did not comment out `scan_disable` meaning it's stock example code with no change except prints. 

1. Click reset button on your tag like evry 2-3s (before IQ results are received)
2. Repeat a few times, but fairly quickly you get the same problem.
3. Maybe something is not cleaned up correctly when canceling the sync, hence it may be related to the other https://github.com/zephyrproject-rtos/zephyr/issues/39432 (error codes from cancel sync received)

[log.txt](https://github.com/zephyrproject-rtos/zephyr/files/7497822/log.txt)

**Comment by jakkra** [comment]
It's with CONFIG_BT_CTLR_DUP_FILTER_LEN=0, also even after waiting and keep resetting the tag it never finds it or any new one.

**Comment by ppryga** [comment]
Ok, I've checked everything (at least it looks like).

From this issue emerge two issues that should be solved and one that should be verified in regard of BT Core spec.:
- https://github.com/zephyrproject-rtos/zephyr/issues/40202 (this has to be verified against BT Core spec),
- https://github.com/zephyrproject-rtos/zephyr/issues/40209
- https://github.com/zephyrproject-rtos/zephyr/issues/40204

**Comment by cvinayak** [comment]
@jakkra Please verify if this PR resolves stopped advertising reports: https://github.com/zephyrproject-rtos/zephyr/pull/40753

**Comment by jakkra** [comment]
@cvinayak tested it and looks like the I'm not able to reproduce the original issue anymore, however instead get this error now when I just sit and reset the tag randomly:

```
...
...
CTE[0]: samples count 45, cte type AOA, slot durations: 2 [us], packet status CRC OK, RSSI -530
PER_ADV_SYNC[0]: [DEVICE]: 05:63:C1:B8:F5:09 (random) sync terminated
Periodic sync lost.
Start scanning...success
Waiting for periodic advertising...success. Found periodic advertising.
Creating Periodic Advertising Sync...success.
Waiting for periodic sync...
PER_ADV_SYNC[0]: [DEVICE]: 1A:CE:9B:A8:C2:99 (random) synced, Interval 0x0050 (100 ms), PHY LE 1M
PER_ADV_SYNC[0]: [DEVICE]: 1A:CE:9B:A8:C2:99 (random), tx_power 127, RSSI -54, CTE AOA, data length 202, data:
success. Periodic sync established.
Enable receiving of CTE...
success. CTE receive enabled.
Scan disable...Success.
Waiting for periodic sync lost...
PER_ADV_SYNC[0]: [DEVICE]: 1A:CE:9B:A8:C2:99 (random), tx_power 127, RSSI -56, CTE AOA, data length 202, data: ▒
CTE[0]: samples count 45, cte type AOA, slot durations: 2 [us], packet status CRC OK, RSSI -560
PER_ADV_SYNC[0]: [DEVICE]: 1A:CE:9B:A8:C2:99 (random), tx_power 127, RSSI -62, CTE AOA, data length 202, data: ▒
CTE[0]: samples count 45, cte type AOA, slot durations: 2 [us], packet status CRC OK, RSSI -620
PER_ADV_SYNC[0]: [DEVICE]: 1A:CE:9B:A8:C2:99 (random), tx_power 127, RSSI -60, CTE AOA, data length 202, data: ▒
CTE[0]: samples count 45, cte type AOA, slot durations: 2 [us], packet status CRC OK, RSSI -600
CTE[0]: samples count 45, cte type AOA, slot durations: 2 [us], packet status CRC not OK, CTE Info OK, RSSI -620
PER_ADV_SYNC[0]: [DEVICE]: 1A:CE:9B:A8:C2:99 (random) sync terminated
Periodic sync lost.
Start scanning...success
Waiting for periodic advertising...success. Found periodic advertising.
Creating Periodic Advertising Sync...success.
Waiting for periodic sync...
Scan running...
PER_ADV_SYNC[0]: [DEVICE]: 07:1B:4D:E7:84:A2 (random) sync terminated
Scan running...
failed (err -11)
Deleting Periodic Advertising Sync...success
Waiting for periodic advertising...success. Found periodic advertising.
Creating Periodic Advertising Sync...failed (err -5)
Waiting for periodic sync...
Scan running...
Scan running...
failed (err -11)
Deleting Periodic Advertising Sync...success
Waiting for periodic advertising...success. Found periodic advertising.
Creating Periodic Advertising Sync...
... fails forever
```
![capture_err_39438](https://user-images.githubusercontent.com/4318648/144635310-7bc2558e-62f8-42a2-9573-549f35d013e7.PNG)


Full log
[log_issue39438.txt](https://github.com/zephyrproject-rtos/zephyr/files/7650847/log_issue39438.txt)

To reproduce it faster I set `CONFIG_BT_PER_ADV_SYNC_MAX=1` in the direction_finding_connectionless_rx sample.

**Comment by cvinayak** [comment]
Thank you. I appreciate your quick response and testing.

> Waiting for periodic sync...
Scan running...
PER_ADV_SYNC[0]: [DEVICE]: 07:1B:4D:E7:84:A2 (random) sync terminated
Scan running...
failed (err -11)
...

This concerns me, the spurious `sync terminated` may be a cause of `sync` context leak.
The PR #40753 addresses `aux` context leak.

I will continue investigation... thank you for your support.

**Comment by cvinayak** [comment]
@jakkra I have made a consolidated PR of all the open changes to the controller, please test this PR with your application: https://github.com/zephyrproject-rtos/zephyr/pull/41091

**Comment by ppryga** [comment]
@jakkra FYI https://github.com/zephyrproject-rtos/zephyr/issues/40202

**Comment by jakkra** [comment]
Hi @ppryga closing #40202 is fine, we will not use any duplicate filtering and if we want to later then we will make sure to re-start the scan, no problem.
