### ISSUE TITLE
Improve emulator APIs for testing

### ISSUE THREAD

**Issue by yperess** [zephyrproject-rtos/zephyr#39486]
**Is your enhancement proposal related to a problem? Please describe.**
The current model of creating and using emulators has some difficulties in implementation:

* Bus specific APIs use a pointer to the bus API in the callback which is easy to implement and understand but hard to use. For example the `struct i2c_emul` is passed to the transfer function. When the function is called, currently, the pattern is to use `CONTAINER_OF` to get the config struct of the parent emulator and from there holding a pointer to either the data or the emulator.
* The emulator node in the devicetree is completely disjoint from the device it is emulating. This causes a few issues, primarily due to the duplication of information. Currently, the emulator node is added using an overlay into the appropriate bus, `&i2c0` for example. The address on the bus is passed in as the `reg` property. This becomes an issue if the board changes configuration (such as the address of the device on the bus or the bus that the peripheral is connected to). Similarly, this becomes an issue if the overlay used for testing is used with multiple boards (they all must have the peripheral on the same bus and at the same address).

**Describe the solution you'd like**
First, the emulator should be directly linked to the device. This can be done by having all the emulator DTS bindings include a common emulator binding which uses a phandle to the device. This would mean that when declaring the emulator in the test's overlay, the bus and address no longer need to be specified, they can be obtained from the phandle's `DT_ON_BUS`/`DT_PARENT`.

Next, the `struct emul` should allow directly housing the bus API in a similar manner to its own APIs. This would look like:

```
enum emul_bus_type {
  EMUL_BUS_TYPE_I2C,
  EMUL_BUS_TYPE_ESPI,
  EMUL_BUS_TYPE_SPI,
};
struct emul {
  emul_init_t init;
  const char *dev_label;
  const void *cfg;
  void *data;
  enum emul_bus_type bus_type;
  union bus {
    const struct i2c_emul *i2c;
    const struct espi_emul *espi;
    const struct spi_emul *spi;
  } bus;
};
#define Z_EMUL_BUS(_dev, _i2c, _espi, _spi)                                       \
    DT_COND_1(DT_ON_BUS(DT_LABEL(_dev), i2c), (_i2c),                             \
              (DT_COND_1(DT_ON_BUS(DT_LABEL(_dev), espi),                         \
                         (_espi),                                                 \
                         (DT_COND_1(DT_ON_BUS(DT_LABEL(_dev), spi),               \
                                    (_spi), (-1))))))

#define EMUL_DEFINE(init_ptr, node_id, cfg_ptr, data_ptr, bus_cfg_ptr)            \
    static struct emul EMUL_REG_NAME(node_id)                                     \
    __attribute__((__section__(".emulators"))) __used = {                         \
      .init = (init_ptr),                                                         \
      .dev_label = DT_LABEL(node_id),                                             \
      .cfg = (cfg_ptr),                                                           \
      .data = (data_ptr),                                                         \
      .bus_type = Z_EMUL_BUS(DT_PHANDLE(node_id, device), EMUL_BUS_TYPE_I2C,      \
                             EMUL_BUS_TYPE_ESPI, EMUL_BUS_TYPE_SPI),              \
      .bus = {                                                                    \
          .Z_EMUL_BUS(i2c, espi, spi) = bus_cfg_ptr,                              \
      },                                                                          \
    };
```

The above is a small change to the `EMUL_DEFINE` macro that now accepts the bus API as a bus config explicitly. The type of bus is automatically resolved and the appropriate bus configuration is set in the parent emulator. At this point, all the bus specific APIs should stop getting their own bus specific struct pointer as the first argument and get the emulator owning the config instead. This would make for a much better developer experience as the data pointer and other configurations are much more easily accessed.

Next, since the bus is known at compile time (as well as the device being emulated) it is now possible to call the appropriate register function automatically in the bus initialization instead of having each individual emulator do it along with a final runtime check to make sure that every emulator was registered.

**Comment by sjg20** [comment]
Can you please point to (or add here) an example node for the emulator? Originally the emulator did not have its own node. Has that changed?
