### ISSUE TITLE
Zephyr boot banner not updated on rebuild with opdated SHA

### ISSUE THREAD

**Issue by tejlmand** [zephyrproject-rtos/zephyr#39503]
**Describe the bug**
The Zephyr build system includes the `git describe` in the boot banner.
Unfortunately the boot banner does not update correctly when there are code changes

**To Reproduce**
```
# Checkout zephyr/main
$ git checkout zephyr/main
HEAD is now at 726656dda5 net: openthread: Add crypto backend based on PSA API

$ git describe
v2.7.99-570-g726656dda5

$ cmake -GNinja -DBOARD=qemu_cortex_m3 -Bbuild .
Including boilerplate (Zephyr repository): /projects/github/ncs/zephyr/cmake/app/boilerplate.cmake
...
-- Zephyr version: 2.7.99 (/projects/github/ncs/zephyr), build: v2.7.99-570-g726656dda554
...
$ ninja -Cbuild run
ninja: Entering directory `build'
[1/129] Preparing syscall dependency handling
...
[128/129] To exit from QEMU enter: 'CTRL+a, x'[QEMU] CPU: cortex-m3
qemu-system-arm: warning: nic stellaris_enet.0 has no peer
Timer with period zero, disabling
*** Booting Zephyr OS build v2.7.99-570-g726656dda554  ***
Hello World! qemu_cortex_m3
```
as can see, the revision in the boot banner is identical to the `git describe` earlier

Let's make a code change, commit it, and rebuild:
```
$ sed -i 's/Hello World/Hello Updated World/g' src/main.c
$ git add -u; git commit -m "updated world" -s

$ git describe
v2.7.99-571-gc82161c229

$ ninja -Cbuild run
ninja: Entering directory `build'
[3/10] Linking C executable zephyr/zephyr_prebuilt.elf

[9/10] Linking C executable zephyr/zephyr.elf
Memory region         Used Size  Region Size  %age Used
           FLASH:        8600 B       256 KB      3.28%
            SRAM:        3944 B        64 KB      6.02%
        IDT_LIST:          0 GB         2 KB      0.00%
[9/10] To exit from QEMU enter: 'CTRL+a, x'[QEMU] CPU: cortex-m3
qemu-system-arm: warning: nic stellaris_enet.0 has no peer
Timer with period zero, disabling
*** Booting Zephyr OS build v2.7.99-570-g726656dda554  ***
Hello Updated World! qemu_cortex_m3
```
as can see, the print message in the application was update, but the boot banner still contains the old `git describe` output.

Let's force a CMake re-run, and then re-build:
```
$ cmake -Bbuild .
Including boilerplate (Zephyr base (cached)): /projects/github/ncs/zephyr/cmake/app/boilerplate.cmake
-- Application: /projects/github/ncs/zephyr/samples/hello_world
-- Zephyr version: 2.7.99 (/projects/github/ncs/zephyr), build: v2.7.99-571-gc82161c229e4
...
$ ninja -Cbuild run
...
[123/124] To exit from QEMU enter: 'CTRL+a, x'[QEMU] CPU: cortex-m3
qemu-system-arm: warning: nic stellaris_enet.0 has no peer
Timer with period zero, disabling
*** Booting Zephyr OS build v2.7.99-571-gc82161c229e4  ***
Hello Updated World! qemu_cortex_m3
```
and as can be seen, after a CMake re-run the boot banner is updated correctly.

**Expected behavior**
The `git describe` content in the boot banner should be updated when there are code changes impacting the build output.

**Impact**
Possible confusion on what was used for building a test sample.

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: Zephyr SDK

**Additional context**
Would be nice if boot banner also contains information whether the repository is considered dirty, `git describe --dirty`.
But that can be seen as an enhancement.

**Comment by marc-hb** [comment]
Maybe a trick to fix this without losing incremental build speed is to run git describe and re-create version.h (or whatever) every time ninja is run BUT "cheat" and restore the old version.h timestamp when the content has not changed. Would that be enough to fool ninja and make?

> Would be nice if boot banner also contains information whether the repository is considered dirty, git describe --dirty.

This was rejected by @SebastianBoe in #13608 . I understand the cons but I think they are outweighed by the pros and that there are other ways to achieve the same thing. Off-topic, #13608 is probably a better place to discuss --dirty (or create a new issue)

**Comment by tejlmand** [comment]
> > Would be nice if boot banner also contains information whether the repository is considered dirty, git describe --dirty.
> 
> This was rejected by @SebastianBoe in #13608 . I understand the cons but I think they are outweighed by the pros and that there are other ways to achieve the same thing.

Thanks for the link, very valuable.

I agree the `kdiff` of the build that @SebastianBoe shows is very valid, but that use-case is also supported by using: `-DBUILD_VERSION="stay_put"` which ensures the version doesn't change between stashes.
It can even be used to ensure a range of commits doesn't impact the build.

https://github.com/zephyrproject-rtos/zephyr/blob/963d05bd525766701cbce44d0aaa63f57e26ae9b/cmake/git.cmake#L16

I don't see why this particular and very valid use-case (kdiff) should block the use-case of `-dirty` status.

> to run git describe and re-create version.h (or whatever)

it's a compile definition:
https://github.com/zephyrproject-rtos/zephyr/blob/963d05bd525766701cbce44d0aaa63f57e26ae9b/CMakeLists.txt#L114-L118

**Comment by SebastianBoe** [comment]
Unless someone has a non-invasive solution to this problem I suggest we fix this through documentation:

"Boot banner shows the git revision when the banner was compiled, which due to ccache and incremental builds may not be the actual current revision. To ensure it matches the current git revision a clean build with empty ccache should be used."

To understand what the best solution is it would be nice to know what exactly people are using this for.

BOOT_BANNER was initially introduced without git revision, just the Zephyr version, so that in support cases one could see the revision when logs were dumped without asking the developer what the revision is. If a very old version was in the logs one could say "You are using an old version that is not supported, please update".

If people are using it for other things then a different solution might be desired. But it works well for what it was designed for.

**Comment by marc-hb** [comment]
> But it works well for what it was designed for.

Right, let's not lose sight of the fact this is an extremely useful feature working well for CI and other automated, _non incremental_ builds. It would be nicer if it worked for developers and incremental builds too but the former are supposed to know what they're doing a little bit.

**Comment by tejlmand** [comment]
> "Boot banner shows the git revision when the banner was compiled, which due to ccache and incremental builds may not be the actual current revision. To ensure it matches the current git revision a clean build with empty ccache should be used."

But the problem is that users might copy this code and think it's a good and a trustworthy way to include current git revision into the build and not realizing that it's actually flawed.
Just like here:
https://github.com/nrfconnect/sdk-nrf/blob/17999765cd133f2816bdc0fe9007fac01b3d79fb/lib/modem_info/CMakeLists.txt#L12-L28
https://github.com/nrfconnect/sdk-nrf/blob/9c8d291764984c7885af8445d9cb15e8c4738ec2/cmake/fw_zip.cmake#L21-L45
where even dirty is trying to be append.

**Comment by marc-hb** [comment]
> But the problem is that users might copy this code and think it's a good

Adding comments and warning should help (and fixing the issue would be even better). On the other hand, I don't think educating wannabe developers who copy/paste/diverge code without understanding it is one of the objectives of the Zephyr project. I realize it's much more likely to happen with ["much universally despited"](https://mesonbuild.com/Design-rationale.html) build system code but... still not a Zephyr objective IMHO.

**Comment by SebastianBoe** [comment]
I don't think it's possible to fix this issue without unwanted side-effects, like a slower build, for those that don't care that the git revision is inaccurate for certain types of small changes.

Which is why I advocate documenting this.

**Comment by tejlmand** [comment]
> On the other hand, I don't think educating wannabe developers who copy/paste/diverge code without understanding it is one of the objectives of the Zephyr project.

In an ideal workd, I would agree.
But I live in a world of embedded developers who are skilled at C and I don't expect them to be fluent at CMake and I can't blame them for copying CMake code that appears to be doing what they nees without.
And I much less expect them to know how to solve this issue themselves.

That's why I believe we should do this properly.

**Comment by tejlmand** [comment]
> like a slower build

How can any changes to current behavior possibly make the solution slower ?
See this: https://github.com/zephyrproject-rtos/zephyr/issues/40167

If CMake is re-run, then all source files will rebuild, because the git revision is added as a compile definition on all sources.

So today you have the worst possible solution.
- Slow build when CMake re-runs and `git` revision has changes
- An outdated revision if CMake didn't re-run.

The right solution would be:
- Don't depend on a CMake re-run in order to build with correct revision
- Only rebuilt files that needs to know the revision (that is, don't use a compile definition)
  - Files that needs to know the revision should instead use a `#include <revision.h>` or we should add this info to `version.h`

**Comment by SebastianBoe** [comment]
> How can any changes to current behavior possibly make the solution slower ?

For instance, if we were to solve "Don't depend on a CMake re-run in order to build with correct revision", by having an always-dirty target, then incremental builds would slow down.

Nice idea about 40167, would be nice to get that fixed :)

**Comment by tejlmand** [comment]
> an always-dirty target, then incremental builds would slow down.

you should now me better than that.
Would never go from a bad, to a horrible solution :wink:

**Comment by SebastianBoe** [comment]
hehe, well, good luck in finding a solution.

I'll be impressed if it can be done :)

**Comment by marc-hb** [comment]
> But I live in a world of embedded developers who are skilled at C and I don't expect them to be fluent at CMake and I can't blame them for copying CMake code that appears to be doing what they nees without.

On one hand this particular piece of code is deceiving and should definitely have some "don't do this at home" comments/warnings. Or even better: your future fix.

On the other hand no one should ever copy/paste/diverge code they don't understand - in any language; period. In fact copying C code is much more dangerous than copying CMake code and your assumption that all Zephyr developers are skilled C developers is... interesting? If all the ones you know are skilled then lucky you.
