### ISSUE TITLE
Add support for the BlueNRG-LP SoC

### ISSUE THREAD

**Issue by trembel** [zephyrproject-rtos/zephyr#39520]
Dear community,

I would kindly request a port of the BlueNRG-LP SoC ([https://www.st.com/en/wireless-connectivity/bluenrg-lp.html](https://www.st.com/en/wireless-connectivity/bluenrg-lp.html)).

Some small informations about it:
- Cortex M0+
- BLE radio interface
- 256kB Flash
- 32/64kB RAM
- 10nA shutdown current, 0.6uA Deepstop (external LSE)
- 4.3mA TX current @ 0dBm, 3.3V
- 3.4mA RX current @ 3.3V

**Comment by trembel** [comment]
Thanks for your answer.
Thats a pitty, as I really think its a nice MCU.
Maybe we missunderstood each other, but the LP is IMO quite different to the MS, as I'm talking about it as a programmable application processor (similar to the nRF52), whereas the MS is just a network processor, which needs an external host MCU connected over SPI.

**Comment by manoj153** [comment]
There is a chance for me to port after receiving a board that features this SoC.

**Comment by erwango** [comment]
@manoj153 Are you still working on this ?
If yes, Let reopen the issue

**Comment by manoj153** [comment]
Have some WIP some time ago. I need to rekindle my motivation to pursue

**Comment by manoj153** [comment]
> @manoj153 I'm also adding myself in the list of requester. I'm not sure if we can push this inside internally. I'm currently adding support to sensortile_box_pro board (https://www.st.com/en/evaluation-tools/steval-mkboxpro.html), which has that BLE chip.

I was working on the port but didn't finish because I got busy with other things.

**Comment by jhedberg** [comment]
We don't generally track hardware request issues, so closing this. Pull requests are welcome though!
