### ISSUE TITLE
mcumgr over serial does not add CRC to length of packet len

### ISSUE THREAD

**Issue by de-nordic** [zephyrproject-rtos/zephyr#39546]
**Describe the bug**
Due to bug in documentation, the mcumgr responses from Zephyr, over serial, have been sending payload length without including CRC.
This documentation has been corrected here; https://github.com/apache/mynewt-mcumgr/commit/9bd9d55d00bb70f93d85e52d7b016bbbb8c79942

**To Reproduce**
1) Compile smp_svr:
```
west build -d smp_svr -b nrf52840dk_nrf52840 zephyr/samples/subsys/mgmt/mcumgr/smp_svr/ --   -DDTC_OVERLAY_FILE=$PWD/zephyr/samples/subsys/mgmt/mcumgr/smp_svr/overlay-serial.conf
```
2) upload it to board with correct mcuboot;
3) issue echo command:
sudo ~/go/bin/mcumgr -t 1200 --loglevel="debug" --conntype serial --connstring dev=/dev/ttyUSB0,baud=115200 echo  aa

**Expected behavior**
The length should be included

**Impact**
No one seem to notice?

**Logs and console output**
This is correct echo frame as issued from mcumgr to smp_svr (1):
```
DEBU[2021-10-19 15:00:26.64] Tx serial
00000000  02 00 00 06 00 00 42 00  a1 61 64 62 61 61        |......B..adbaa|
(...)
00000000  41 42 41 43 41 41 41 47  41 41 42 43 41 4b 46 68  |ABACAAAGAABCAKFh|
00000010  5a 47 4a 68 59 55 76 78                           |ZGJhYUvx|
```
Decoding the base64 encoded frame payload:
```
ABACAAAGAABCAKFhZGJhYUvx
```
gives:
```
b'\x00\x10\x02\x00\x00\x06\x00\x00B\x00\xa1adbaaK\xf1'
```
where two first bytes are Big Endian encoded 16bit length, here it is 16, which corresponds to the frame payload (1), which is 14 bytes long,  + 2 bytes of CRC = 16: this means that mcumgr cli sets length as the documentation states.

Now the smp_svr response to above is:
```
...
DEBU[2021-10-19 15:00:26.662] Rx serial:
00000000  06 09 41 41 38 44 41 41  41 48 41 41 42 43 41 4c  |..AA8DAAAHAABCAL|
00000010  39 68 63 6d 4a 68 59 66  39 33 2b 67 3d 3d        |9hcmJhYf93+g==|
DEBU[2021-10-19 15:02:38.427] Decoded input:
00000000  03 00 00 07 00 00 42 00  bf 61 72 62 61 61 ff     |......B..arbaa.|
```
decoding the frame from base64:
```
AA8DAAAHAABCAL9hcmJhYf93+g==
```
gives:
```
b'\x00\x0f\x03\x00\x00\x07\x00\x00B\x00\xbfarbaa\xffw\xfa'
```
so the size encoded by the smp_svr is obviously 15, which is exactly size of "Decoded input:" from above, and that input does not include the two byte CRC.

**Environment (please complete the following information):**
 - OS: Linux
 - SDK 0.13.1
 - zephyr fd316a5452b538e5c59a41dd15973897cb43384f

**Why have I logged this long issue instead of just making commit that adds two to len?**
Well, to notify people that there is issue and query whether there is client software that actually have been using the field with incorrect value before breaking other people stuff. Mcumgr cli does  not seem to care anyway.

**Comment by de-nordic** [comment]
@sw You may also be interested in this.

**Comment by mniestroj** [comment]
Didn't notice it earlier, but I am not heavy user of serial transport (just used it several times). I do have client software (other than mcumgr cli) with serial transport, but same story here, I am not using it very often. Changing (fixing) won't affect anything on my side. Thanks for reporting, though!
