### ISSUE TITLE
stm32: lpuart: 9600 baudrate doesn't work

### ISSUE THREAD

**Issue by ycsin** [zephyrproject-rtos/zephyr#39608]
`lpuart1` won't work when it is set to 9600 baudrate on `nucleo_g0b1re` board, in fact it will not work for anything below ~15k baudrate by calculation.

![image](https://user-images.githubusercontent.com/1563974/138208934-bd723674-7966-494c-ae90-cfcd360355be.png)

The `LPUARTDIV` based on the formula above is ~1,706,666, which doesn't fit into a 20bit `BRR` register and was truncated into 658,091 instead after the `LPUART_BRR_MASK` mask, see pictures below.

![image](https://user-images.githubusercontent.com/1563974/138209144-748cdaf2-1d06-49e7-b136-429ad2ed44b5.png)

![image](https://user-images.githubusercontent.com/1563974/138208686-2e4ae063-2a4b-4359-b44c-351b319ac169.png)
![image](https://user-images.githubusercontent.com/1563974/138208843-3c6efb67-7dac-42ca-8d84-f72b3495feb0.png)
![image](https://user-images.githubusercontent.com/1563974/138208712-f3b889d7-b20c-4ca2-85bf-20101334fd77.png)

**Comment by ycsin** [comment]
I'm able to get it to work by editing the [driver](https://github.com/zephyrproject-rtos/zephyr/blob/main/drivers/serial/uart_stm32.c#L96) like so:

```c
#if HAS_LPUART_1
	if (IS_LPUART_INSTANCE(UartInstance)) {
		LL_LPUART_SetPrescaler(UartInstance, LL_USART_PRESCALER_DIV4);
		LL_LPUART_SetBaudRate(UartInstance,
				      clock_rate,
#ifdef USART_PRESC_PRESCALER
				      LL_USART_PRESCALER_DIV4,
#endif
				      baud_rate);
	} else {
```

But I think we might need something more so that the driver can select the correct prescaler value to cover whole baudrate range

**Comment by erwango** [comment]
> I'm able to get it to work by editing the driver like so:

Ok, nice. Feel free to contribute
