### ISSUE TITLE
west/sign: fix mapping of Zephyr board names to rimage config file name

### ISSUE THREAD

**Issue by marc-hb** [zephyrproject-rtos/zephyr#39604]
> This is merely mapping a Zephyr codename to the name of an `rimage/config/$target.toml` config file in SOF so it seems a bit far from "describing hardware components" ... @mbolivar-nordic Could you sketch a bit how it could look like?

Sorry, I wasn't reading in detail and just assumed this was coming from devicetree because the function name begins with `edt_`. If that is not appropriate, there are any number of places you can put the metadata you need in the board directory itself:

- `$BOARD.yaml`
- `board.cmake` (currently just used for runners, but maybe you can set a value here that ultimately tells rimage what to do?)
- some Kconfig symbol

_Originally posted by @mbolivar-nordic in https://github.com/zephyrproject-rtos/zephyr/pull/39050#r729421324_

**Comment by cfriedt** [comment]
@mbolivar-nordic - can you follow up with this?

**Comment by marc-hb** [comment]
That's SOF specific and not for @mbolivar-nordic

**Comment by MaureenHelm** [comment]
> Sorry, I wasn't reading in detail and just assumed this was coming from devicetree because the function name begins with `edt_`. If that is not appropriate, there are any number of places you can put the metadata you need in the board directory itself:
> 
> * `$BOARD.yaml`
> * `board.cmake` (currently just used for runners, but maybe you can set a value here that ultimately tells rimage what to do?)
> * some Kconfig symbol

I stumbled upon this on my own last week. I think `board.cmake` is the way to go, I'll try to put a PR together.

**Comment by mbolivar-nordic** [comment]
Thanks @MaureenHelm !
