### ISSUE TITLE
Build type warning is broken

### ISSUE THREAD

**Issue by arludwig** [zephyrproject-rtos/zephyr#39626]
**Describe the Bug**
No matter how I set the build types and optimization options, I always get the build type warning.

> [cmake]         The CMake build type was set to 'MinSizeRel', but the optimization flag was set to '-Os'.
[cmake]         This may be intentional and the warning can be turned off by setting the CMake variable 'NO_BUILD_TYPE_WARNING'

**To Reproduce**
1. Set CMake build type to MinSizeRel
2. In prj.conf set `CONFIG_SIZE_OPTIMIZATIONS=y`
3. Configure the project

Should work on any minimal zephyr project where `NO_BUILD_TYPE_WARNING` is not set

**Impact**
Purely aesthetic / maybe pedantic.
Since I use zephyr as a git submodule inside my projects source tree, I always get a warning indicator for zephyr's root CMakeLists.txt.

**Technical Analysis**
`CMAKE_C_FLAGS_${CMAKE_BUILD_TYPE_uppercase}` is not a list but a string. so
https://github.com/zephyrproject-rtos/zephyr/blob/f24367963e3ec50c14fd30454ca883ee8c831dc5/CMakeLists.txt#L1676
will always be true.

Something like
```
string(REPLACE " " ";" _current_cmake_c_flags ${CMAKE_C_FLAGS_${CMAKE_BUILD_TYPE_uppercase}})
if(NOT (${OPTIMIZATION_FLAG} IN_LIST _current_cmake_c_flags))
```
should do the trick.

**Comment by tejlmand** [comment]
@arludwig thanks for noticing this.

This has been fixed here: #41067
