### ISSUE TITLE
STM32L496 Zephyr using LVGL disp_drv.flush_cb can not work

### ISSUE THREAD

**Issue by glin00** [zephyrproject-rtos/zephyr#39645]
**Describe the bug**
I am using LVGL with Zephyr.  The hardware is STM32L496 and FW uses SPI DMA to send display data to OLED. The problem is that when LVGL call disp_drv.flush_cb, the transmission of SPI data can not made within this flush_cb.  
The picture show this result. 
![NotCorrectImage](https://user-images.githubusercontent.com/20088622/138410720-924d12ff-a055-43d0-93f6-fc9f770f5009.jpg)

The code implementation which I call A is as follow:

```
void hal_oled_lvgl_init(void)
{
    disp_drv.flush_cb = hal_oled_lvgl_flush;
    lv_disp_drv_register(&disp_drv);
}

static void hal_oled_lvgl_flush(lv_disp_drv_t * drv, const lv_area_t * area, lv_color_t * color_p)
{
    oled_lvgl_flush=1;
    hal_oled_lvgl_flush_exe();     // the transmission of SPI data is done here
    lv_disp_flush_ready(drv);
}
void hal_oled_lvgl_flush_exe(void)
{
    if (oled_lvgl_flush) {
        oled_lvgl_flush=0;
	APP_SPI_Write_DataLvgl(flush_data_p, NUM_BYTES_BY_ROW_COL(flush_area_num_row,flush_area_num_col));

    }  
}
```

To fix this problem, I have to move  the transmission of SPI data outside LVGL and put it in main. 
The picture show this result. 
![CorrectImage](https://user-images.githubusercontent.com/20088622/138408727-0780ec6b-60e2-4269-956e-d299b0dd460d.png)

The  code implementation which I call B is as follow::

```
static void hal_oled_lvgl_flush(lv_disp_drv_t * drv, const lv_area_t * area, lv_color_t * color_p)
{
    oled_lvgl_flush=1;
    lv_disp_flush_ready(drv);
}

void main(void)
{
	lv_init();
	hal_oled_lvgl_init();
	while (1) {
            hal_oled_lvgl_flush_exe();  // the transmission of SPI data is done here
        }
}
```

**Expected behavior**
The transmission of SPI data should be within disp_drv.flush_cb. So, how to solve the problem if I want to use code implementation A?  
Implementation B only solve the problem on the surface but produces side effects.

**Environment (please complete the following information):**
Hardware:STM32L496
Display: OLED display with 4 wire SPI interface.
Linux Ubuntu 20.04.3 LTS
Zephyr SDK,-0.13.0
Zephyr SHA1 ID:bb85a55
LVGL:7.6.1

**Additional context**

**Comment by erwango** [comment]
@cfriedt Removing the STM32 label as nothing point to STM32 specific code fro now but purely to lvgl usage (and I won't be able to help on this)

**Comment by glin00** [comment]
The problem is solved. Thank You.
