### ISSUE TITLE
On ESP32S2 platform GPIO interrupt causes RTOS to crash on arch_is_isr() assertion

### ISSUE THREAD

**Issue by TeXniKK** [zephyrproject-rtos/zephyr#39695]
**Describe the bug**
On ESP32S2 platform GPIO interrupt causes RTOS to crash on arch_is_isr() assert when configured to GPIO_INT_EDGE_BOTH and rapid interrupts occur

**To Reproduce**
1. checkout sample code of modified "button" example from https://github.com/zephyrproject-rtos/zephyr/pull/39600
2. west build -b esp32s2_saola samples/basic/button
3. west flash
4. reset board, observe logs. 'alive' log is printed every 1 sec
5. shortly connect GPIO pin 14 to +3.3V multiple times
6. kernel crashes on ASSERTION FAIL [!arch_is_isr()] WEST_TOPDIR/zephyr/kernel/sched.c:1307 

**Expected behavior**
Interrupt handler processed correctly, 'Button pressed at <ticks>' printed to console. No crash on  assertion

**Impact**
Blocks UI development of new product

**Logs and console output**
`ESP-ROM:esp32s2-rc4-20191025
Build:Oct 25 2019
rst:0x1 (POWERON),boot:0x8 (SPI_FAST_FLASH_BOOT)
SPIWP:0xee
mode:DIO, clock div:2
load:0x3ffe6100,len:0x19d8
load:0x4004c000,len:0x9e8
load:0x40050000,len:0x2b70
SHA-256 comparison failed:
Calculated: 96756701be462e06554f6d00bfa1416fcc010a0f909c2a82a043e9b46d3a1508
Expected: 6b58599fd32de533aea8a503ba1b8ca8d6172dc4065ab78917e8fc29bbaa1e4b
Attempting to boot anyway...
entry 0x4004c1ec
I (42) boot: ESP-IDF release/v4.3-96-ga360365cb 2nd stage bootloader
I (42) boot: compile time 13:24:36
I (42) boot: chip revision: 0
I (47) boot.esp32s2: SPI Speed      : 40MHz
I (51) boot.esp32s2: SPI Mode       : DIO
I (56) boot.esp32s2: SPI Flash Size : 4MB
I (61) boot: Enabling RNG early entropy source...
I (66) boot: Partition Table:
I (70) boot: ## Label            Usage          Type ST Offset   Length
I (77) boot:  0 nvs              WiFi data        01 02 00009000 00006000
I (84) boot:  1 phy_init         RF data          01 01 0000f000 00001000
I (92) boot:  2 factory          factory app      00 00 00010000 00100000
I (99) boot: End of partition table
I (103) esp_image: segment 0: paddr=00010020 vaddr=3f000020 size=013a0h (  5024) map
I (113) esp_image: segment 1: paddr=000113c8 vaddr=3ffb6308 size=00484h (  1156) load
I (121) esp_image: segment 2: paddr=00011854 vaddr=3ffb678c size=00150h (   336) load
I (129) esp_image: segment 3: paddr=000119ac vaddr=40022000 size=00400h (  1024) load
I (138) esp_image: segment 4: paddr=00011db4 vaddr=40022400 size=03f08h ( 16136) load
I (151) esp_image: segment 5: paddr=00015cc4 vaddr=00000000 size=0a354h ( 41812) 
I (166) esp_image: segment 6: paddr=00020020 vaddr=40080020 size=0253ch (  9532) map
I (171) boot: Loaded app from partition at offset 0x10000
*** Booting Zephyr OS build v2.7.99-685-gff59cde7c331  ***
ok
Set up button at GPIO_0 pin 14
Press the button
Button pressed at 15529719
Button pressed at 15815975
Button pressed at 16399307
Button pressed at 18907874
Button pressed at 18913847
Button pressed at 18919793
Button pressed at 18925739
Button pressed at 19315949
Button pressed at 20330648
Button pressed at 20482601
Button pressed at 21065933
Button pressed at 23702627
Button pressed at 23708600
Button pressed at 23714546
Button pressed at 23720492
Button pressed at 23982560
Button pressed at 25149629
Button pressed at 25161344
Button pressed at 25732553
Button pressed at 28517585
Button pressed at 28523558
Button pressed at 28529504
Button pressed at 28535450
Button pressed at 28649180
Button pressed at 29831363
Button pressed at 29843510
Button pressed at 30399167
alive
alive
Button pressed at 571478627
Button pressed at 572714501
Button pressed at 572726246
Button pressed at 572738018
Button pressed at 572749937
Button pressed at 572761913
Button pressed at 573038411
Button pressed at 573642572
Button pressed at 574246733
Button pressed at 574850894
Button pressed at 575455055
Button pressed at 576059216
Button pressed at 577523972
Button pressed at 577535900
Button pressed at 577871690
Button pressed at 578475851
Button pressed at 579080012
Button pressed at 579684173
Button pressed at 580288334
Button pressed at 580892495
Button pressed at 582321575
Button pressed at 582333290
Button pressed at 582704990
Button pressed at 583309151
Button pressed at 583913300
Button pressed at 584517461
Button pressed at 585121622
Button pressed at 585725783
Button pressed at 587116508
Button pressed at 587128310
Button pressed at 587538260
Button pressed at 588142421
Button pressed at 588746582
Button pressed at 589350743
Button pressed at 589954904
Button pressed at 590559071
Button pressed at 591927281
Button pressed at 591938873
Button pressed at 592371557
Button pressed at 592975718
Button pressed at 593579879
Button pressed at 594184040
Button pressed at 594788201
Button pressed at 595392362
Button pressed at 596717279
Button pressed at 596729144
Button pressed at 597204830
Button pressed at 597808991
Button pressed at 598413152
Button pressed at 599017313
Button pressed at 599621474
Button pressed at 600225635
Button pressed at 603030689
Button pressed at 603042692
Button pressed at 603054761
Button pressed at 603066794
Button pressed at 603246452
Button pressed at 603850595
Button pressed at 604454756
Button pressed at 605058917
Button pressed at 606319820
Button pressed at 606331631
Button pressed at 606871415
Button pressed at 607475576
Button pressed at 608079737
Button pressed at 608683880
Button pressed at 609288041
Button pressed at 609892202
Button pressed at 611127275
Button pressed at 611139218
Button pressed at 611704688
Button pressed at 612308849
Button pressed at 612913010
Button pressed at 613517171
Button pressed at 614121332
Button pressed at 615927125
Button pressed at 615938612
Button pressed at 615949082
Button pressed at 616537970
Button pressed at 617142131
Button pressed at 617746292
Button pressed at 618350453
Button pressed at 618954614
Button pressed at 620720720
Button pressed at 620732735
Button pressed at 620767097
Button pressed at 621371258
Button pressed at 621975419
Button pressed at 622579580
Button pressed at 623183741
Button pressed at 623787902
Button pressed at 625522400
Button pressed at 625534229
Button pressed at 625600379
Button pressed at 626204540
Button pressed at 626808701
Button pressed at 627412862
Button pressed at 628017023
Button pressed at 628621184
Button pressed at 630327236
Button pressed at 630338795
Button pressed at 630433673
Button pressed at 631037834
Button pressed at 631830644
Button pressed at 632246156
Button pressed at 632850317
Button pressed at 633454478
Button pressed at 635129192
Button pressed at 635140208
Button pressed at 635266964
Button pressed at 635871125
Button pressed at 636632438
Button pressed at 637079432
Button pressed at 637683593
Button pressed at 638287754
Button pressed at 639925955
Button pressed at 639937259
Button pressed at 640100249
Button pressed at 640704401
Button pressed at 641433968
Button pressed at 641912723
Button pressed at 642516875
Button pressed at 643121045
Button pressed at 644716265
Button pressed at 644727992
Button pressed at 644933525
Button pressed at 645537695
Button pressed at 646234853
Button pressed at 646746008
Button pressed at 647350160
Button pressed at 647954330
Button pressed at 649527044
Button pressed at 649538732
Button pressed at 649766819
Button pressed at 650370971
Button pressed at 651026501
Button pressed at 651579290
Button pressed at 652183460
Button pressed at 652787612
Button pressed at 654335108
Button pressed at 654347048
Button pressed at 654600101
Button pressed at 655204253
Button pressed at 655837865
Button pressed at 656412584
Button pressed at 657016742
Button pressed at 657620900
Button pressed at 659130656
Button pressed at 659142467
Button pressed at 659433380
Button pressed at 660037538
Button pressed at 660641708
Button pressed at 661245860
Button pressed at 661850030
Button pressed at 662454182
Button pressed at 663927287
Button pressed at 663938831
Button pressed at 664266674
Button pressed at 664870826
Button pressed at 665474996
Button pressed at 666079148
Button pressed at 666683300
Button pressed at 667287470
Button pressed at 668727743
Button pressed at 668739887
Button pressed at 669099950
Button pressed at 669704120
Button pressed at 670308272
Button pressed at 670912442
Button pressed at 671516594
Button pressed at 672120746
Button pressed at 673533644
Button pressed at 673545266
Button pressed at 673933229
Button pressed at 674537399
Button pressed at 675141551
Button pressed at 675745721
alive
Button pressed at 741193622
Button pressed at 741211085
Button pressed at 741241049
Button pressed at 741253526
Button pressed at 741265967
Button pressed at 741517526
Button pressed at 742121696
Button pressed at 742725848
Button pressed at 743330018
Button pressed at 743934170
Button pressed at 745552904
Button pressed at 745563524
Button pressed at 745746665
Button pressed at 746350817
Button pressed at 746954987
Button pressed at 747559139
Button pressed at 748163291
Button pressed at 748767461
Button pressed at 750356723
Button pressed at 750368867
Button pressed at 750579944
Button pressed at 751184096
Button pressed at 751852121
Button pressed at 752392418
Button pressed at 752996588
Button pressed at 753600740
Button pressed at 755154998
Button pressed at 755166491
Button pressed at 755413226
Button pressed at 756017396
Button pressed at 756658145
Button pressed at 757225712
Button pressed at 757829864
Button pressed at 758434034
Button pressed at 759942887
Button pressed at 759954980
Button pressed at 760246517
Button pressed at 760850675
Button pressed at 761454827
Button pressed at 762058997
Button pressed at 762663149
Button pressed at 763267319
Button pressed at 764749688
Button pressed at 764761556
Button pressed at 765079805
Button pressed at 765683957
Button pressed at 766288127
Button pressed at 766892279
Button pressed at 767496431
Button pressed at 768100601
Button pressed at 769556447
Button pressed at 769568273
Button pressed at 769913090
Button pressed at 770517242
Button pressed at 771121412
Button pressed at 771725564
Button pressed at 772329716
Button pressed at 772933886
Button pressed at 774356060
Button pressed at 774367823
Button pressed at 774746372
Button pressed at 775350524
Button pressed at 775954694
Button pressed at 776558846
Button pressed at 777163016
Button pressed at 777767168
Button pressed at 779149718
Button pressed at 779161187
Button pressed at 779579660
Button pressed at 780183812
Button pressed at 780787982
Button pressed at 781392134
Button pressed at 781996286
Button pressed at 782600456
Button pressed at 783951383
Button pressed at 783963845
Button pressed at 784412936
Button pressed at 785017106
Button pressed at 785621258
Button pressed at 786225428
Button pressed at 786829580
Button pressed at 787433738
Button pressed at 788757527
Button pressed at 788769293
Button pressed at 789246230
Button pressed at 789850382
Button pressed at 790454552
Button pressed at 791058704
Button pressed at 791662856
Button pressed at 792267026
Button pressed at 793565486
Button pressed at 793576679
Button pressed at 794079500
Button pressed at 794683670
Button pressed at 795287822
Button pressed at 795891992
Button pressed at 796496144
Button pressed at 797100314
Button pressed at 798360161
Button pressed at 798371033
Button pressed at 798912788
Button pressed at 799516958
Button pressed at 800121110
Button pressed at 800725280
Button pressed at 801329432
Button pressed at 801933602
Button pressed at 803165822
Button pressed at 803177570
Button pressed at 803746073
Button pressed at 804350243
Button pressed at 804954395
Button pressed at 805558565
Button pressed at 806162717
Button pressed at 807949538
Button pressed at 807961151
Button pressed at 807975200
Button pressed at 808579370
Button pressed at 809183522
Button pressed at 809787692
Button pressed at 810391844
Button pressed at 810995996
Button pressed at 812759390
Button pressed at 812770823
Button pressed at 812808488
Button pressed at 813412640
Button pressed at 814016810
Button pressed at 814620962Button pressed at 815186348
Button pressed at 815787614
ASSERTION FAIL [!arch_is_in_isr()] @ WEST_TOPDIR/zephyrButton pressed at 817551514
Button pressed at 818141771
Button pressed at 818745917
Button pressed at 819350081
Button pressed at 819954245
Button pressed at 820558409
/kernel/sched.c:1231

@ WEST_TOPDIR/zephyr/lib/os/asseButton pressed at 822350785
Button pressed at 822954218
Button pressed at 823558382
Button pressed at 824162528
Button pressed at 824766692
Button pressed at 825370856
rt.c:45`

**Environment (please complete the following information):**
 - OS: MacOS
 - Commit SHA or Version used: 349f9dfc714c02273a60657d84919fbed1c24a68
 - Board: ESP32-S2FH32 based TinyS2

**Additional context**
Link to pull request with sample code: https://github.com/zephyrproject-rtos/zephyr/pull/3960
Prebuilt example  [Archive.zip](https://github.com/zephyrproject-rtos/zephyr/files/7409415/Archive.zip)

**Comment by sylvioalves** [comment]
@andyross @dcpleung, I guess you can give some thoughts in here?
I tested and confirmed that `ASSERT(!arch_is_in_isr())` is being triggered in `sched.c, 1301`. Main thread is looping with `k_msleep()` and that is where the ASSERT is triggered from. It seems GPIO interrupts are "overlapping" each other when triggered fast/spurious way. If I replace `k_msleep` to `k_busy_wait` in main loop then it does not ASSERT. Also, disabling the ASSERT works without any issue. Looking forward for some opinion, thanks.
