### ISSUE TITLE
Can't enable CONFIG_SHELL_LOG_BACKEND Log Shell Menus with pure Telnet Shell Backend

### ISSUE THREAD

**Issue by bob2oneil** [zephyrproject-rtos/zephyr#39707]
**Describe the bug**
I want to implement the Shell Interface exclusively using the Telnet interface, while it is ok to also have the UART backend as functional.

To implement this, I have used the following kernel SHELL settings successfully set.

```
# Shell and logging device backends
CONFIG_SHELL_LOG_BACKEND=n
CONFIG_SHELL_BACKEND_TELNET=y
CONFIG_LOG_BACKEND_UART=y
```

I do not want logging to overwrite content in the Shell interface - this should be reserved for shell content only.  If I have substantial serial logging occurring, the Telnet menus get sweep out of view and obscured.

Unfortunately, with these kernel configuration settings, I am not able to change log settings runtime that result from having CONFIG_SHELL_LOG_BACKEND set false.

BUT - when I do enable CONFIG_SHELL_LOG_BACKEND in the kernel configuration, to expose the log **disable**, **enable**, and **status** dynamic memory commands - then the Telnet interface is overwritten by content from the serial interface.

If I use a Shell command such as "**log halt**" to terminate serial logging overwrite of the Telnet menus - then when I attempt to change the logging level for a particular module, the shell interface indicates logging of said module is disabled, and refuses to make the changes.
```

~$ log enable dbg os
log enable dbg os
Backend not active.
os: level set to inf.
```

**To Reproduce**
1. Standard west build for Native-POSIX target

**Expected behavior**
Full support for dynamically changing logging levels by module when the Telnet interface is used exclusively for the shell.

**Impact**
Annoyance.

**Logs and console output**
```
Sample output and configuration for Telnet interface, initially with serial content overwrite, then halting logging to be able to change module logging levels:

[00:17:44.433,824] <inf> net_stats.stats: TCP seg rsterr 0	rst	0	re-xmit	0
[00:17:44.433,824] <inf> net_stats.stats: TCP conn drop  0	connrst	0
[00:17:44.433,824] <inf> net_stats.stats: Bytes received 139685
[00:17:44.433,824] <inf> net_stats.stats: Bytes sent     263975
[00:17:44.433,824] <inf> net_stats.stats: Processing err 6
~$ log halt
~$ log
log
log - Commands for controlling logger
Subcommands:
  backend        :Logger backends commands.
  disable        :'log disable <module_0> .. <module_n>' disables logs in
                  specified modules (all if no modules specified).
  enable         :'log enable <level> <module_0> ...  <module_n>' enables logs
                  up to given level in specified modules (all if no modules
                  specified).
  go             :Resume logging
  halt           :Halt logging
  list_backends  :Lists logger backends.
  status         :Logger status
~$ log status
log status
Logs are halted!
module_name                              | current | built-in 
----------------------------------------------------------
app                                      | wrn     | inf
bridge_queues                            | inf     | inf
channel_plan                             | inf     | inf
config_set                               | inf     | inf
ddlcontroller                            | inf     | inf
ddlt_commands                            | inf     | inf
ddlt_if                                  | inf     | inf
ddlt_udp_server                          | inf     | inf
eth_posix                                | inf     | inf
eth_posix_adapt                          | inf     | inf
eth_utils                                | inf     | inf
flash                                    | dbg     | dbg
fs                                       | dbg     | dbg
littlefs                                 | dbg     | dbg
log                                      | inf     | inf
main                                     | inf     | inf
manual_bit_and_health                    | inf     | inf
net_arp                                  | inf     | inf
net_buf                                  | inf     | inf
net_conn                                 | inf     | inf
net_core                                 | inf     | inf
net_ctx                                  | inf     | inf
net_ethernet                             | inf     | inf
net_ethernet_mgmt                        | inf     | inf
net_ethernet_stats                       | inf     | inf
net_icmpv4                               | inf     | inf
net_if                                   | inf     | inf
net_ipv4                                 | inf     | inf
net_mgmt                                 | inf     | inf
net_pkt                                  | inf     | inf
net_promisc                              | inf     | inf
net_shell                                | dbg     | dbg
net_sock                                 | inf     | inf
net_sock_addr                            | inf     | inf
net_sock_packet                          | inf     | inf
net_sockets_raw                          | inf     | inf
net_stats                                | inf     | inf
net_tc                                   | inf     | inf
net_tcp                                  | inf     | inf
net_udp                                  | inf     | inf
net_utils                                | inf     | inf
node_directory                           | inf     | inf
node_focus                               | inf     | inf
node_op_param                            | inf     | inf
os                                       | inf     | inf
radio_control                            | inf     | inf
radio_status                             | inf     | inf
session                                  | inf     | inf
shell.shell_telnet                       | inf     | inf
shell.shell_uart                         | inf     | inf
shell_telnet                             | inf     | inf
shell_uart                               | inf     | inf
statemachine                             | inf     | inf
sys_utils                                | inf     | inf
time_utils                               | inf     | inf
tx_queues                                | inf     | inf

log - Commands for controlling logger
Subcommands:
  backend        :Logger backends commands.
  disable        :'log disable <module_0> .. <module_n>' disables logs in
                  specified modules (all if no modules specified).
  enable         :'log enable <level> <module_0> ...  <module_n>' enables logs
                  up to given level in specified modules (all if no modules
                  specified).
  go             :Resume logging
  halt           :Halt logging
  list_backends  :Lists logger backends.
  status         :Logger status
~$ log enable dbg os
log enable dbg os
Backend not active.
os: level set to inf.
~$ log status
log status
Logs are halted!
module_name                              | current | built-in 
----------------------------------------------------------
app                                      | wrn     | inf
bridge_queues                            | inf     | inf
channel_plan                             | inf     | inf
config_set                               | inf     | inf
ddlcontroller                            | inf     | inf
ddlt_commands                            | inf     | inf
ddlt_if                                  | inf     | inf
ddlt_udp_server                          | inf     | inf
eth_posix                                | inf     | inf
```

**Environment (please complete the following information):**
 - OS: (e.g. Linux)
 - Toolchain (e.g Zephyr SDK 13.1.)
 - Commit SHA or Version used: Booting Zephyr OS build v2.7.99-666-g074bd00bcbae

**Comment by jakub-uC** [comment]
@nordic-krch May you please take a look at this?

**Comment by nordic-krch** [comment]
not sure if i understood correctly but standard logging shell commands are specific to the current shell instance. If it has logging disabled then it won't work. However, there is a set of commands to control another backend.
`log list_backends` lists all logging backends. Then you can use `log backend log_backend_uart enable dbg os` in telnet shell to change logging level for uart backend.

**Comment by bob2oneil** [comment]
Thanks for this information.   However, the issue I presented remains, that is when I have CONFIG_SHELL_LOG_BACKEND enabled, and I want the Telnet interface to be purely the shell interface, and the serial interface to be the output of LOG* outputs (can be shell as well), once I enable CONFIG_SHELL_LOG_BACKEND to allow the shell menu to control logging, just enabling that setting then polutes the Telnet interface with serial output from LOG output, whereas I was trying to keep those separate so that the Telnet shell interface menus are not overwritten by log content.


> BUT - when I do enable CONFIG_SHELL_LOG_BACKEND in the kernel configuration, to expose the log disable, enable, and status dynamic memory commands - then the Telnet interface is overwritten by content from the serial interface.

**Comment by bob2oneil** [comment]
It might be worth talking about the 200 foot view.  What I am trying to do is have a Telnet interface to be used exclusively for the shell menu, because the serial is not suitable for a user interface menu as content will be quickly overwritten by program logging.  So I want the Telnet interface to be the command and control interface, but from within the Telnet interface, I want to change the logging levels per module runtime/dynamically.  

Through the kernel configuration listed, I am able to get the Telnet interface to be used for the shell interface.  It also exists in the serial interface, which is not desirable, but not a show stopper.

What is now failing is the attempt from the Telnet interface to runtime change logging levels per module as described.

When logging dynamics are enabled for shell access within the Telnet menu, executing a command must change some setting that isolated the serial interface logging from the Telnet interface logging.

It is likely due to the way the dynamic shell menu is populated, and the fact that the Telnet interface needs to control the serial interface instead.

I am out of ideas on how to fix this.

**Comment by nordic-krch** [comment]
Have you been trying to set `SHELL_TELNET_INIT_LOG_LEVEL_NONE=y`? This should disable logging to telnet shell from the start.

**Comment by bob2oneil** [comment]
Spoke too soon, runtime dynamic changes using the Telnet interface but targeting the serial interface does not change the logging level.
```

~$ log backend log_backend_uart enable dbg

app: level set to inf.
bridge_queues: level set to inf.
channel_plan: level set to inf.
config_set: level set to inf.

$ log backend log_backend_uart enable dbg app

app: level set to inf.
~$ log backend log_backend_uart status

module_name                              | current | built-in 
----------------------------------------------------------
app                                      | inf     | inf
```

**Comment by nordic-krch** [comment]
try `log backend log_backend_uart enable wrn app`. App module has no debug level compiled in  (`built-in` column) so you cannot change to it.

**Comment by bob2oneil** [comment]
Got it, I did not understand what the "built-in" column represented in terms of compiled logging levels.

Thanks for the help on this, closing it out.

**Comment by bob2oneil** [comment]
Quick question on this topic.  So the registration for a module for the logging system does both establishing the maximum level of logging, but also the current.

So how might I for example enable DBG level as possible (this is understood) while at the same time having the application current set only to INF?  Is there an API for that?
