### ISSUE TITLE
stm32 uart testing fails on test_read_abort

### ISSUE THREAD

**Issue by FRASTM** [zephyrproject-rtos/zephyr#39703]
The test case tests/drivers/uart/uart_async_api/  fails on several stm32 target boards  with a deadlock in the 
**START - test_read_abort**  sequence

The https://github.com/zephyrproject-rtos/zephyr/pull/37859   could be linked to that failure

**To Reproduce**
1. west build -p auto -b nucleo_g071rb tests/drivers/uart/uart_async_api/

**Expected behavior**
TEST passed

**Impact**
test campaign failure on:
   _tests/drivers/uart/uart_async_api/drivers.uart.uart_async_api, disco_l475_iot1
   tests/drivers/uart/uart_async_api/drivers.uart.uart_async_api, nucleo_f746zg
   tests/drivers/uart/uart_async_api/drivers.uart.uart_async_api, nucleo_g071rb
   tests/drivers/uart/uart_async_api/drivers.uart.uart_async_api, nucleo_g474re
   tests/drivers/uart/uart_async_api/drivers.uart.uart_async_api, stm32f3_disco_

**Logs and console output**
```
*** Booting Zephyr OS build v2.7.99-283-gd79d26f1ae1f  ***
Running test suite uart_async_test
===================================================================
START - test_single_read_setup
 PASS - test_single_read_setup in 0.1 seconds
===================================================================
START - test_single_read
 PASS - test_single_read in 0.403 seconds
===================================================================
START - test_chained_read_setup
 PASS - test_chained_read_setup in 0.1 seconds
===================================================================
START - test_chained_read
 PASS - test_chained_read in 0.269 seconds
===================================================================
START - test_double_buffer_setup
 PASS - test_double_buffer_setup in 0.1 seconds
===================================================================
START - test_double_buffer
 PASS - test_double_buffer in 3.420 seconds
===================================================================
START - test_read_abort_setup
 PASS - test_read_abort_setup in 0.1 seconds
===================================================================
START - test_read_abort
```

**Environment (please complete the following information):**
 - Commit SHA  (detected on  0162f4c67a9b3337736c41d7e6acb3e5904b1dbd)
 - test PASSED on release 2.7.0

**Additional context**

**Comment by manoj153** [comment]
Oh, I think it makes sense because you have aborted the DMA reception process, which my previous patch enables the RXNE to interrupt, 

My ISR callback had `uart_fifo_read()` in my app case, so I overlooked and did not notice this issue.
