### ISSUE TITLE
STM32L496G_DISCO uart testing fails on single buffer read

### ISSUE THREAD

**Issue by glin00** [zephyrproject-rtos/zephyr#39718]
**Describe the bug**
I want to use UART DMＡ　to receive data on STM32L496G_DISCO board. So I build the uart_async_api and flash download to the board. The following is the error message.

```
*** Booting Zephyr OS build v2.7.0-rc1-36-g0552d329c88c  ***
Running test suite uart_async_test
===================================================================
START - test_single_read_setup
 PASS - test_single_read_setup in 0.1 seconds
===================================================================
START - test_single_read
E: Unimplemented system call
E: r0/a1:  0x00000000  r1/a2:  0x00000000  r2/a3:  0x00000000
E: r3/a4:  0x00000000 r12/ip:  0x00000000 r14/lr:  0x00000000
E:  xpsr:  0x00000000
E: Faulting instruction address (r15/pc): 0x2cc393b8
E: >>> ZEPHYR FATAL ERROR 3: Kernel oops on CPU 0
E: Current thread: 0x20001000 (test_single_read)
E: Halting system
```

**To Reproduce**
west build -b stm32l496g_disco zephyr/tests/drivers/uart_async_api
west flash

**Expected behavior**
UART DMA with rx, tx should be working without errors .

**Environment (please complete the following information):**
Hardware:STM32L496G_DISCO
Linux Ubuntu 20.04.3 LTS
Zephyr SDK,-0.13.0
Zephyr SHA1 ID:bb85a55

**Comment by FRASTM** [comment]
@glin00 could you please detail the UART instance you are using and the corresponding pins on the disco board
It is important to add the uart of this board in the` tests/drivers/uart/uart_async_api/src/test_uart.h `
to connected Tx and Rx pins on the board
and to configure the DTS for the test case with a  t`ests/drivers/uart/uart_async_api/boards/stm32l496g_disco.overlay`
Depending on the uart, the dma request is specified for a DMA channel of a DMA instance (1 or 2)
(like it is done for the disco_l475_iot1 board)

**Comment by FRASTM** [comment]
Because of the drivers/serial/Kconfig.stm32, the UART_ASYNC_API requires a DMA

**Comment by erwango** [comment]
@glin00 Is this issue still active ?

**Comment by erwango** [comment]
@glin00 please reopen if required.
