### ISSUE TITLE
Bluetooth: Controller: Refactor radio_pkt_configure and radio_ar_configure function signatures

### ISSUE THREAD

**Issue by cvinayak** [zephyrproject-rtos/zephyr#39723]
**Is your enhancement proposal related to a problem? Please describe.**
Refactor the following Controller Radio HAL interfaces:
- `radio_pkt_configure`
- `radio_ar_configure`

**Describe the solution you'd like**
Avoid the magic numbers such as BIT(1)  and bit shifts used to pass PHY and packet flags

**Describe alternatives you've considered**
May be have explicit parameters for PHY and separate functions to configure data channel or advertising channel PDU/packet.

**Additional context**
NA

**Comment by carlescufi** [comment]
Addressed as part of #41122
