### ISSUE TITLE
twister: tests: samples: Skips on integration_platforms in CI

### ISSUE THREAD

**Issue by PerMac** [zephyrproject-rtos/zephyr#39738]
**Describe the bug**
If `integration_platforms` are given in a sample/testcase yaml it means the CI has to evaluate these platforms (they must not get skipped). A CI test for #36433 exposed that the following tests/samples requires a fix:

- samples/subsys/shell/shell_module/sample.shell.shell_module.minimal_rtt in native_posix:samples/subsys/shell/shell_module/sample.shell
- tests/drivers/flash/drivers.flash.stm32 in nrf52840dk_nrf52840:tests/drivers/flash/drivers.flash
- tests/subsys/logging/log_core_additional/logging.add.user in native_posix:tests/subsys/logging/log_core_additional/logging.add
- tests/ztest/mock_fff/testing.ztest.mock_fff in native_posix:tests/ztest/mock_fff/testing.ztest
- tests/ztest/mock_fff/testing.ztest.mock_fff_global in native_posix:tests/ztest/mock_fff/testing.ztest

**To Reproduce**
See error in CI https://buildkite.com/zephyr/zephyr/builds/44471#16cc743c-5380-409d-aee4-fd17801a3155
run `scripts/twister -G -v -T <path_to_problematic_test>
see skips in results

**Impact**
Breach in CI regression testing. Instead of being executed, a test/sample was silently skipped. These tests has to be fixed before #36433 can be merged

**Environment (please complete the following information):**
Doesn't matter

**Comment by nashif** [comment]
not sure why this is a high TBH, will look at it regardless.

**Comment by nashif** [comment]
for those:

> tests/ztest/mock_fff/testing.ztest.mock_fff in native_posix:tests/ztest/mock_fff/testing.ztest
> tests/ztest/mock_fff/testing.ztest.mock_fff_global in native_posix:tests/ztest/mock_fff/testing.ztest

you probably need a different approach, the filter here is a software/env filter and not a platform filter, so the error should not apply.
