### ISSUE TITLE
Arm Ethos-U Core Driver

### ISSUE THREAD

**Issue by kristofer-jonsson-arm** [zephyrproject-rtos/zephyr#39739]
## Origin

Arm Ethos-U Core Driver

https://git.mlplatform.org/ml/ethos-u/ethos-u-core-driver.git

## Purpose

Driver for the Arm Ethos-U NPU.

## Mode of integration

Module.

The driver is actively maintained upstream, and it would make most sense to keep the differences between the upstream repository and the fork at a minimum.

Suggested name: https://github.com/zephyrproject-rtos/ethos-u-core-driver

## Pull Request

No pull request exists.

## Description

The Ethos-U Core Driver is a small platform agnostic device driver for the Arm Ethos-U NPU. It provides an interface that frameworks like Tensorflow Lite Micro or uTVM can use to execute command streams on the hardware accelerator.

With this module the Tensorflow Lite Micro framework can be updated to include the Ethos-U kernel (`<tflite-micro>/tensorflow/lite/micro/kernels/ethos_u/ethosu.cc`), which allows networks optimized by the Vela compiler [1] to be run on TFLu.

[1] https://git.mlplatform.org/ml/ethos-u/ethos-u-vela.git

# Dependencies

This module depends on CMSIS Core.

For boards that are built with support for Ethos-U, the tflite-micro module (`zephyr/modules/tflite-micro/CMakeLists.txt`) will be updated to include the Ethos-U kernel (`<tflite-micro>/tensorflow/lite/micro/kernels/ethos_u/ethosu.cc`), which creates a dependency on this module.

## Revision

https://git.mlplatform.org/ml/ethos-u/ethos-u-core-driver.git
Revision: a0e4d31c5531b55a638d1efa0a43e1f296a2f2d9

## License

``Apache-2.0``

https://spdx.org/licenses/Apache-2.0.html

**Comment by carlescufi** [comment]
TSC meeting: No objections to creating the repo and adding the module.

**Comment by galak** [comment]
We may want to see about moving zephyr/init.c into the zephyr tree itself to easy maintainership of that glue code.

I assume we'll see updates on the zephyr side for device tree binding, updating dts for an547, some kinda of sample or test.

**Comment by freddan80** [comment]
@carlescufi my Github ID.

**Comment by carlescufi** [comment]
> We may want to see about moving zephyr/init.c into the zephyr tree itself to easy maintainership of that glue code.

Agreed, let's do that @freddan80 and @kristofer-jonsson-arm. This belongs in the main tree, in `modules/`.

Speaking of, we need to choose whether we want an isolated repo for this, or a new `hal_arm` repository that covers all future HALs or drivers that come from Arm. This would be a repo of repos, which has the disadvantage of not being able to track upstream history since updates are done by copying files and not by merging in commits.

**Comment by kristofer-jonsson-arm** [comment]
I think we can follow the example of tflite-micro and create `<zephyr>/modules/ethos-u-core-driver` and place the `CMakeLists.txt`, `Kconfig` and `init.c` there.

We will be making minor updates to the `an547` board files, adding DTS entries describing the Ethos-U NPU. 

We will also need to make a minor adjustment to `modules/tflite-micro/CMakeLists.txt`, selecting a different version of `ethos-u.cc` if `CONFIG_ARM_ETHOS_U` is set.

**Comment by microbuilder** [comment]
@carlescufi I can see benefit to both approaches, but looking at TF-M we started with this mono repo approach and it became enough of a support burden to keep the three repos up to date that we broke them out individually. I also think losing the history is non a trivial side effect here.

Would you object with starting with this repo as a direct fork with the history, and when we get to a situation where there are multiple Arm libraries to deal with we can reconsider moving them into a single repo with some sort of update strategy or script defined for that?

I don't have strong feelings here, I'm just aware of the update burden from TF-M with this approach and the messy history situation.

**Comment by kristofer-jonsson-arm** [comment]
I can see a few advantages of keeping the driver as a standalone repository. Upmerges from the parent repository will be easier. We will hopefully be able to preserve the git history. And ownership of the repo will be clearer, as a `hal_arm` repo would need to be shared across different teams at Arm.

**Comment by carlescufi** [comment]
> @carlescufi I can see benefit to both approaches, but looking at TF-M we started with this mono repo approach and it became enough of a support burden to keep the three repos up to date that we broke them out individually. I also think losing the history is non a trivial side effect here.

Yes, I saw that and was actually supportive of the change, but that is a much bigger project. This project is quite small, so I was trying to coalesce it together with other future drivers.  But we can do that later too, let's start simple. Since this is effectively a "HAL", I will create a new `hal_ethos_u_core` repo.

**Comment by kristofer-jonsson-arm** [comment]
Thanks, much appreciated.

Talked to Fredrik and we believe `hal_ethos_u_core_driver` would better reflect the connection to the upstream repository at MLPlatform.

**Comment by carlescufi** [comment]
> Thanks, much appreciated.
> 
> Talked to Fredrik and we believe `hal_ethos_u_core_driver` would better reflect the connection to the upstream repository at MLPlatform.

Right, but that is a bit of a [RAS syndrome](https://en.wikipedia.org/wiki/RAS_syndrome), since the `hal_` prefix is intended to cover the `_driver` part.

**Comment by carlescufi** [comment]
> > Thanks, much appreciated.
> > Talked to Fredrik and we believe `hal_ethos_u_core_driver` would better reflect the connection to the upstream repository at MLPlatform.
> 
> Right, but that is a bit of a [RAS syndrome](https://en.wikipedia.org/wiki/RAS_syndrome), since the `hal_` prefix is intended to cover the `_driver` part.

@kristofer-jonsson-arm @freddan80 ping on this. Are you ok with `hal_ethos_u_core`? Will this driver ever contain sources for additional Ethos producs? Should it be `hal_ethos_npu` instead?

**Comment by kristofer-jonsson-arm** [comment]
I see what you mean. The repo will not contain any other Ethos-U products, so I would suggest to name the repo `hal_ethos_u`.

**Comment by carlescufi** [comment]
https://github.com/zephyrproject-rtos/hal_ethos_u

**Comment by freddan80** [comment]
Thx @carlescufi
