### ISSUE TITLE
Road from pinmux to pinctrl

### ISSUE THREAD

**Issue by carlescufi** [zephyrproject-rtos/zephyr#39740]
## Goals of the transition for each SoC family

- nRF
  - Allow users to continue using `<signal>-pin` properties during the transition period (when `CONFIG_PINCTRL=n`)
  - No pre-defined combinations since almost every pin can take any function
- NXP
  - i.MX
  - Kinetis
  - LPC
- STM32
  - Existing Devicetree representation will be kept
  - Pinmux driver will be kept in tree during the transition period, but will not be used by any driver

## Timeline

- Grace period between 2.7.99 and 3.1 where both pinctrl and pinmux coexist, no deprecation
- By 3.1 all in-tree boards must've switched to pinctrl:
  - Pinctrl driver complete
  - All peripheral drivers for the SoC family supporting pinctrl
  - In-tree boards use the new pinctrl representation
- After 3.1 is released (3.1.99) we deprecate pinmux
- Zephyr 3.2 deprecates pinmux, Zephyr 3.4 removes pinmux

## Porting status

- [x] Telink B91
  - Existing pinmux driver: https://github.com/zephyrproject-rtos/zephyr/blob/main/drivers/pinmux/pinmux_b91.c
  - Proposal: https://github.com/zephyrproject-rtos/zephyr/pull/42773
  - Assignee: @yurvyn
- [x] TI CC13xx/CC26xx
  - Existing pinmux driver: https://github.com/zephyrproject-rtos/zephyr/blob/main/drivers/pinmux/pinmux_cc13xx_cc26xx.c
  - Note: uses `<signal>-pin` DT properties
  - Proposal: #44492
  - Assignee: @vaishnavachath
- [x] ESP32
  - Existing pinmux driver: https://github.com/zephyrproject-rtos/zephyr/blob/main/drivers/pinmux/pinmux_esp32.c
  - Notes: uses `<signal>-pin` DT properties
  - Proposal: https://github.com/zephyrproject-rtos/zephyr/pull/43589
  - Assignee: @glaubermaroto  
- [x] HSDK
  - Existing pinmux driver: https://github.com/zephyrproject-rtos/zephyr/blob/main/drivers/pinmux/pinmux_hsdk.c
  - Proposal: #45343
  - Assignee: @evgeniy-paltsev
- [x] Intel S1000
  - Existing pinmux driver: https://github.com/zephyrproject-rtos/zephyr/blob/main/drivers/pinmux/pinmux_intel_s1000.c
  - Proposal: https://github.com/zephyrproject-rtos/zephyr/pull/46496
  - Assignee: @nashif
- [x]  ITE IT8xxx2
  - Existing pinmux driver: https://github.com/zephyrproject-rtos/zephyr/blob/main/drivers/pinmux/pinmux_ite_it8xxx2.c
  - Proposal: #44786
  - Assignee: @GTLin08
- [x] NXP LPC11U6X
  - Existing pinmux driver: https://github.com/zephyrproject-rtos/zephyr/blob/main/drivers/pinmux/pinmux_lpc11u6x.c
  - Proposal: #44843
  - Assignee: @danieldegrasse
- [x] Microchip MCHP XEC
  - Existing pinmux driver: https://github.com/zephyrproject-rtos/zephyr/blob/main/drivers/pinmux/pinmux_mchp_xec.c
  - Proposal: https://github.com/zephyrproject-rtos/zephyr/pull/43282
  - Assignee: @jvasanth1
  - Missing: MEC1501, e.g. https://github.com/zephyrproject-rtos/zephyr/tree/main/boards/arm/mec1501modular_assy6885 https://github.com/zephyrproject-rtos/zephyr/pull/48893
- [x] NXP Kinetis
  - Existing pinmux driver: https://github.com/zephyrproject-rtos/zephyr/blob/main/drivers/pinmux/pinmux_mcux.c
  - Proposal: #39743, #43033 #43560
  - Assignee: @danieldegrasse 
- [x] NXP iMX RT1xxx
  - Existing pinmux driver: https://github.com/zephyrproject-rtos/zephyr/blob/main/boards/arm/mimxrt1060_evk/pinmux.c
  - Proposal: #42238 #44150
  - Assignee: @danieldegrasse 
- [x] NXP MCUX LPC
  - Existing pinmux driver: https://github.com/zephyrproject-rtos/zephyr/blob/main/drivers/pinmux/pinmux_mcux_lpc.c
  - Proposal: #43454, #44907
  - Assignee: @danieldegrasse 
- [x] NXP iMX RT6xx/5xx
  - Existing pinmux driver: N/A [(custom implementation)](https://github.com/zephyrproject-rtos/zephyr/blob/main/boards/arm/mimxrt685_evk/pinmux.c)
  - Proposal: #44571
  - Assignee: @danieldegrasse 
- [x] NXP iMX8M
  - Existing pinmux driver: N/A [(custom implementation)](https://github.com/zephyrproject-rtos/zephyr/blob/main/boards/arm/mimx8mm_evk/pinmux.c)
  - Proposal: https://github.com/zephyrproject-rtos/zephyr/pull/45126
  - Assignee: @danieldegrasse 
- [x] RV32M1
  - Existing pinmux driver: https://github.com/zephyrproject-rtos/zephyr/blob/main/drivers/pinmux/pinmux_rv32m1.c
  - Proposal: #45274
  - Assignee: @henrikbrixandersen
- [x] Atmel SAM/SAM0
  - Existing pinmux driver: https://github.com/zephyrproject-rtos/zephyr/blob/main/drivers/pinmux/pinmux_sam0.c
  - Proposal: (pending: multiple device drivers, board conversion)
    - #35423
    - #42512
    - #43731
  - Assignee: @nandojve
- [x] SiFive
  - Existing pinmux driver: https://github.com/zephyrproject-rtos/zephyr/blob/main/drivers/pinmux/pinmux_sifive.c
  - Proposal: https://github.com/zephyrproject-rtos/zephyr/pull/44068
  - Assignee: @tgorochowik 
- [x] nRF
  - Existing pinmux driver: N/A (done at device drivers)
  - Proposal: #39429 #43926
  - Assignee: @anangl 
- [x] STM32
  - Existing pinmux driver: https://github.com/zephyrproject-rtos/zephyr/blob/main/drivers/pinmux/pinmux_stm32.c
  - Proposal: #40194
- [x] Nuvoton NPCX
  - Existing pinmux driver: N/A (custom implementation)
  - Proposal: #43638 
  - Assignee: @MulinChao @ChiHuaL @WealianLiao

## Custom APIs

- [ ] SiLabs
  - Existing pinmux driver: N/A (custom implementation)
  - Proposal: #50352
  - Assignee: @chrta

- [ ] Cypress psoc6
  - Existing pinmux driver: N/A (custom implementation, see e.g. `dts/arm/cypress/psoc6-pinctrl.dtsi`)
  - Assignee: @npal-cy (please confirm)
  - Enhancement issue: https://github.com/zephyrproject-rtos/zephyr/issues/52434

- [ ] armv8-m/armv7-m
  - Existing pinmux driver: N/A (board level C code)
  - Assignee: @microbuilder (please confirm)
  - https://github.com/zephyrproject-rtos/zephyr/blob/main/boards/arm/v2m_musca_b1/pinmux.c
  - https://github.com/zephyrproject-rtos/zephyr/blob/main/boards/arm/mps2_an385/pinmux.c
  - Enhancement issue: https://github.com/zephyrproject-rtos/zephyr/issues/52435
 
- [ ] ARC emsk
  - Existing pinmux driver: N/A (board level C code)
  - https://github.com/zephyrproject-rtos/zephyr/blob/main/boards/arc/em_starterkit/pmodmux.c
  - Assignee: @ruuddw (please confirm: tbd, see #45771)
  - Enhancement issue: https://github.com/zephyrproject-rtos/zephyr/issues/52436

- [ ] Xilinx ZynqMP
  - Existing pinmux driver: N/A (board level C code)
  - https://github.com/zephyrproject-rtos/zephyr/blob/main/boards/arm/mercury_xu/board.c
  - Assignee: @wsipak (please confirm)
  - Enhancement issue: https://github.com/zephyrproject-rtos/zephyr/issues/52437

## New drivers

List of new driver proposals for SoCs that did not have an existing pinmux driver.

- [X] GigaDevice
  - Proposal: https://github.com/zephyrproject-rtos/zephyr/pull/39974
- [x] RaspberryPi Pico (RP2040)
  - Proposal: https://github.com/zephyrproject-rtos/zephyr/pull/34835
- [X] Renesas R-Car
  - Proposal: https://github.com/zephyrproject-rtos/zephyr/pull/40550 
- [x] Bouffalo Lab
  - Proposal: https://github.com/zephyrproject-rtos/zephyr/pull/37686
- [x] Xilinx Zynq-7000
  - Proposal: https://github.com/zephyrproject-rtos/zephyr/pull/46648

**Comment by erwango** [comment]
Updated STM32 reference (https://github.com/zephyrproject-rtos/zephyr/pull/40194 replaces #30430)

**Comment by henrikbrixandersen** [comment]
I have added assignees to the various conversions from pinmux to pinctrl drivers. Please confirm, comment, or reassign as needed.

**Comment by tgorochowik** [comment]
Feel free to assign me to the SiFive port. I'll coordinate the implementation

**Comment by carlescufi** [comment]
> Feel free to assign me to the SiFive port. I'll coordinate the implementation

Thank you very much!

**Comment by evgeniy-paltsev** [comment]
Feel free to assign me to the HSDK pinmux.

**Comment by carlescufi** [comment]
> Feel free to assign me to the HSDK pinmux.

Great! Thank you!

**Comment by GTLin08** [comment]
Hi Carles,
I have updated the assignee.

**Comment by GTLin08** [comment]
I have updated the assignee of ITE.

**Comment by cfriedt** [comment]
@carlescufi - I believe @vaishnav98 will be volunteering to step up to maintain the cc13xx_cc26xx as well as cc32xx SoCs. Please do not delete from the codebase. He has direct experience working with them with various Zephyr-based products and is an employee at TI.

Vaishnav - first steps:
- Make a PR to add yourself to the MAINTAINERS.yml file for TI areas
- Go over some of the existing Pinmux drivers to get a feel for how others have managed their port
- Make PRs for the new drivers (I would be happy to review)
- Likely, you may want to step in to collaborate on [hal_ti](https://github.com/zephyrproject-rtos/hal_ti) as well

**Comment by bwitherspoon** [comment]
> @carlescufi - I believe @vaishnav98 will be volunteering to step up to maintain the cc13xx_cc26xx as well as cc32xx SoCs. Please do not delete from the codebase. He has direct experience working with them with various Zephyr-based products and is an employee at TI.
> 
> Vaishnav - first steps:
> 
> * Make a PR to add yourself to the MAINTAINERS.yml file for TI areas
> * Go over some of the existing Pinmux drivers to get a feel for how others have managed their port
> * Make PRs for the new drivers (I would be happy to review)
> * Likely, you may want to step in to collaborate on [hal_ti](https://github.com/zephyrproject-rtos/hal_ti) as well

I will help with this effort in anyway I can. I have been unable to contribute for some time, but this situation has most likely changed with my recent position change.

**Comment by carlescufi** [comment]
@evgeniy-paltsev @GTLin08 ping on your respective assigned work items. Do you have a rough time estimate for the PRs to be posted?

**Comment by GTLin08** [comment]
@carlescufi, I will post the PRs by next week.

**Comment by carlescufi** [comment]
@bwitherspoon will you be able to transition the TI CC32x one?
https://github.com/zephyrproject-rtos/zephyr/blob/main/boards/arm/cc3220sf_launchxl/pinmux.c

Thanks!

**Comment by carlescufi** [comment]
> @bwitherspoon will you be able to transition the TI CC32x one? https://github.com/zephyrproject-rtos/zephyr/blob/main/boards/arm/cc3220sf_launchxl/pinmux.c
> 
> Thanks!

After a discussion with Brett, he cannot help here with the CC32xx, so we still need someone to help out.

**Comment by cfriedt** [comment]
> > @bwitherspoon will you be able to transition the TI CC32x one? https://github.com/zephyrproject-rtos/zephyr/blob/main/boards/arm/cc3220sf_launchxl/pinmux.c
> > Thanks!
> 
> After a discussion with Brett, he cannot help here with the CC32xx, so we still need someone to help out.

Paging Dr. @vaishnavachath

**Comment by nandojve** [comment]
> @carlescufi, for the Cypress part migration, can you confirm that this is the existing parts introduced by @nandojve? I believe he is the current code owner there.
> 
> What is the timeline for the 3.1 release?
> 
> Thank you,
> 
> Ian

Infineon have joined to Zephyr Project as a Silver Member and they have plans to improve PSoC-6 support.
Maybe @npal-cy can give a more accurate info about current pinctrl API migration plans.

**Comment by gmarull** [comment]
@jvasanth1 MEC1501 boards seem to depend on pinmux API, are they going to be ported?

**Comment by npal-cy** [comment]
> > @carlescufi, for the Cypress part migration, can you confirm that this is the existing parts introduced by @nandojve? I believe he is the current code owner there.
> > What is the timeline for the 3.1 release?
> > Thank you,
> > Ian
> 
> Infineon have joined to Zephyr Project as a Silver Member and they have plans to improve PSoC-6 support. Maybe @npal-cy can give a more accurate info about current pinctrl API migration plans.

Current PSoC 6 implementation is not using pinmux, so it is not block this migration. We will remove current PSoC 6 integration, once new one add (so we do not want add any updates here, if it is not real critical).

In new PSoC 6 we implemented pinctrl driver. Can be review in scope of https://github.com/zephyrproject-rtos/zephyr/pull/44211. 

Regards,
Nazar

**Comment by ruuddw** [comment]
For ARC emsk, with a different custom API: I'm not sure yet, need to investigate (see #45771) is pinctl would be the right solution for our connector-level pmod muxing.

**Comment by fabiobaltieri** [comment]
@carlescufi do you think we can close this if the MEC1501 support gets merged? Thinking that the remaining 5 platforms that currently have no multiplexing driver at all should be covered separately (if at all).

**Comment by gmarull** [comment]
I think we should give at most a couple more releases for those platforms to move to pinctrl or be removed (these are likely platforms with poor maintenance). Many of the migrated platforms (e.g. Nordic or STM32) did not use pinmux API at all, but they were included in the migration list.

**Comment by fabiobaltieri** [comment]
Cool, was just thinking about this in the context of v3.2 and keeping as a target to remove the last pinmux users, and then track implementing new platforms separately for v3.3.

**Comment by cfriedt** [comment]
> @carlescufi @cfriedt I will volunteer to transition TI CC32x, will try to get the PR ready by coming Monday.

@vaishnavachath - was this one already merged? I can't recall

**Comment by vaishnavachath** [comment]
> > @carlescufi @cfriedt I will volunteer to transition TI CC32x, will try to get the PR ready by coming Monday.
> 
> @vaishnavachath - was this one already merged? I can't recall

@cfriedt , No sorry I missed the CC32XX platforms I am working on this and will send a PR soon.

**Comment by henrikbrixandersen** [comment]
Closing this issue as I have opened enhancement issues for the remaining, custom implementations in-tree.

**Comment by nandojve** [comment]
Hi @henrikbrixandersen , @gmarull ,

Zephyr is moving to a LTS version using custom implementations in this topic (and maybe in others). I can be wrong but as far I remember it was agreed that they should be moved to the official API.

IMHO this is open a bad precedent in Zephyr were the rules/agreement are imposed for a few and for the others are just convenience. The project should enforce participants to be in sync with project roadmap and not the contrary.

This is clearly accumulating debit since after one year there are participants that not even have a plan.

Can you clarify what is going on?

**Comment by gmarull** [comment]
> Hi @henrikbrixandersen , @gmarull ,
> 
> Zephyr is moving to a LTS version using custom implementations in this topic (and maybe in others). I can be wrong but as far I remember it was agreed that they should be moved to the official API.
> 
> IMHO this is open a bad precedent in Zephyr were the rules/agreement are imposed for a few and for the others are just convenience. The project should enforce participants to be in sync with project roadmap and not the contrary.
> 
> This is clearly accumulating debit since after one year there are participants that not even have a plan.
> 
> Can you clarify what is going on?

I don't know who can decide on this topic (TSC? A maintainer? A WG?). I'd be brave and drop all those who haven't migrated. If they care about Zephyr, they'll eventually come back with a PR adding the platform back with a proper driver.

**Comment by microbuilder** [comment]
For the two Arm parts that need updating, this is completely my bad that it fell off my radar. I've asked @ithinuel if he can have a look at those since both those platforms come from Arm itself and are a bit unusual, but if he doesn't have the free cycles to update these I'll try to remember the details of those two platforms myself. Thanks for calling this out.
