### ISSUE TITLE
Build is broken if LWM2M_CANCEL_OBSERVE_BY_PATH config is set

### ISSUE THREAD

**Issue by apsigma** [zephyrproject-rtos/zephyr#39758]
**Describe the bug**
Build is broken when LWM2M_CANCEL_OBSERVE_BY_PATH config is set.

Commit e3f8757b70b7a13c8352409c7632d57a9def20b1 added the Kconfig option `LWM2M_CANCEL_OBSERVE_BY_PATH` and some code for when this is enabled.

Commit 05b2018ffa6d9a4ad5e7752bef3c1f914be36787 then removed some of the code related to observers. However, this commit did not remove all code ifdef:ed with `LWM2M_CANCEL_OBSERVE_BY_PATH`, nor was the Kconfig option removed.

**To Reproduce**
If a project has defined `CONFIG_LWM2M_CANCEL_OBSERVE_BY_PATH=y`, then some build errors are produced, eg.:

```
zephyr/subsys/net/lib/lwm2m/lwm2m_engine.c:586:32: error: 'engine_observer_list' undeclared (first use in this function); did you mean 'engine_service_list'?
```

Removing the config of `CONFIG_LWM2M_CANCEL_OBSERVE_BY_PATH` makes the project build fine.

**Expected behavior**
No build errors, or complaints about the config option being deprecated/removed/unklnown.

The code ifdef:ed should be updated or removed, and the Kconfig option shold also be removed if no longer required.

**Environment (please complete the following information):**
- OS: Linux
- Commit: b92ce9a6c1ca1a45371ffc204823bb5db537ab6e

**Comment by rlubos** [comment]
@apsigma I've opened a PR with a fix: https://github.com/zephyrproject-rtos/zephyr/pull/39995
