### ISSUE TITLE
STM32L4: usb-hid: regression in hal 1.17.0

### ISSUE THREAD

**Issue by bearsh** [zephyrproject-rtos/zephyr#39888]
**Describe the bug**
usb-hid does not work correctly using the current hal revision (zephyrproject-rtos/hal_stm32@5c8275071ec1cf160bfe8c18bbd9330a7d714dc8). this revision contains the cube pkg for the stm32l4 in version 1.17.0. going back to 1.16.0 solves the problem for me.
sending from to pc (I therefor use a python script using hidapi) works the first time (.int_out_ready callback is called). afterwards this callback gets never called.

**To Reproduce**
as I use a custom board, I have to figure out first...

**Expected behavior**
Sending and receiving pkg should work.

**Impact**
communication over hid is impossible

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: GNU Arm Embedded Toolchain 10-2020-q4-major
 - Commit SHA or Version used: v2.7.99-763-gb92ce9a6c1

**Comment by FRASTM** [comment]
@bearsh could you please detail a bit more the application running or a similar one and soc 
What kind of failure do you get ?

**Comment by FRASTM** [comment]
Actually, versions 1.17.0 and 1.16.0 have few significant differences in the stm32l4xx_ll_usb.c. 
Could you point a particular one 
[stm32l4xx__ll_usb.diff.txt](https://github.com/zephyrproject-rtos/zephyr/files/7667675/stm32l4xx__ll_usb.diff.txt)
?

**Comment by bearsh** [comment]
sorry for not replaying earlier...

Unfortunately I can not point to a particular change, but your diff is only about ll_usb but AFAIK one should also look at `stm32l4xx_hal_pcd.c`

a more complete diff would be this:
[stm32l4xx_e5090a6..manifest-rev.diff.txt](https://github.com/zephyrproject-rtos/zephyr/files/7667810/stm32l4xx_e5090a6.manifest-rev.diff.txt)
 
Just FYI, I use a stm32l422

hopefully I'm able to provide a minimal example in the next days.

**Comment by erwango** [comment]
@bearsh Any update on this ?

**Comment by bearsh** [comment]
yes I did test it again, this time using a sample application (`samples/subsys/usb/hid`) and it still does not work, at least with a stm32l422.

steps to (hopefully) reproduce:
- as zephyr doesn't seems to support a board with a stm32l422 and I even don't have a eval board with it, I use a custom board. this board is very simple and it should theoretically also work on other hw with the same cpu as the usb pins are fixed and beside usb, I don't need anything for this demo. my board in here: [boards.tar.gz](https://github.com/zephyrproject-rtos/zephyr/files/7852624/boards.tar.gz)
- unpack in to some directory and run: `west build -b my-stm32l422-board ../zephyrproject/zephyr/samples/subsys/usb/hid/ -- -DBOARD_ROOT=$(pwd)`
- `west flash` (I used west flash -r jlink)
- on linux, make sure udev has the appropriate rule, in my case: `SUBSYSTEM=="usb", ATTRS{idVendor}=="2fe3", ATTRS{idProduct}=="0006", MODE="0666"`
- open a python interpreter ([hidapi](https://pypi.org/project/hidapi/) needs to be installed)
- `import hid`
- `d = hid.device()`
- `d.open(0x2fe3, 0x0006)`
- `d.read(2)`
- the last command shout output something like `[1, 1]`, in a subsequent call the second number changes: `[1, 2]` `[1, 3]`

the output mentioned above only happens if use https://github.com/zephyrproject-rtos/hal_stm32 on `e5090a6` but not on HEAD.

**Comment by FRASTM** [comment]
Is there something more to have the hid api working ? I got this error:
```
>>> d.open(0x2fe3, 0x0006)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "hid.pyx", line 113, in hid.device.open
OSError: open failed
>>> 
```

**Comment by bearsh** [comment]
> Is there something more to have the hid api working ? I got this error:
> 
> ```
> >>> d.open(0x2fe3, 0x0006)
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "hid.pyx", line 113, in hid.device.open
> OSError: open failed
> >>> 
> ```

(I assume you're on linux) 
- after writing the udev rule, did you either reconnect the board or call `sudo udevadm control --reload-rules`?
- do you have the same vid/pid in your project? `lsusb` (wenn connected) or `journalctl --follow -k` while connecting may help

**Comment by FRASTM** [comment]
Thx, That's better now.  "Bus 004 Device 018: ID 2fe3:0006 ZEPHYR Zephyr HID sample"

My  zephyrproject-rtos /hal_stm32  is on the main top branch [9153102](https://github.com/zephyrproject-rtos/hal_stm32/commit/91531028be0bfa554ae1dd9e2b5d3ed6fd7287c3) 
(stm32l4xx  in V1.17.0) and my target board is nucleo_l4r5zi (zephyr OS e8df8a579033be238beb774e4909d637da649f3a) running samples/subsys/usb/hid

```
>>> d.open(0x2fe3, 0x0006)
>>> d.read(2)
[1, 14]
>>> d.read(2)
[1, 15]
>>> d.read(2)
[1, 16]
...
>>> d.read(2)
[1, 236]
```

**Comment by bearsh** [comment]
strange, so the difference between your and my setup is the zephyr version and the used mcu. just to be sure, I can try again with the zephyr version you used.

may it also be some difference/errata/whatever in the mcu?

**Comment by FRASTM** [comment]
One difference is stm32L422 has USB FS interface and stm32L4+ has USB OTG

**Comment by erwango** [comment]
@bearsh Did you make some progress identifying the rrot cause?

**Comment by bearsh** [comment]
no. I discovered the issue while evaluating Zephyr for a project but in the end we decided to go the bare metal way as we already had working code to share from another project. this means my time working on this is quite limited.

I would really appreciate if someone related to ST could run the example (https://github.com/zephyrproject-rtos/zephyr/issues/39888#issuecomment-1010741093) on a stm32L4 (stm32L422 would probably be best). I suppose ST people could also bisect the changes between 1.16 and 1.17 but I don't have that info :unamused: 

We use that hal in version 1.16.0 on one product (bare metal) and I think I can remember having problem with v1.17 as well once I played with it but stoppe doing so as 1.16 is running fine. but in the long run, having an upgrade path would be nice...

**Comment by FRASTM** [comment]
Definitely, no difference found both versions of stm32cube/stm32l4xx  1.16.0  and 1.17 and even latest 1.17.1 give the same output

**Comment by erwango** [comment]
> Definitely, no difference found between both versions of stm32cube/stm32l4xx 1.16.0 and 1.17 and even latest 1.17.1 gives the same output
> 
> ```
>  >>> d.read(2)
> [1, 11]
> ```
> 
> etc

Thanks @FRASTM, was it tested using L4 or L4+ ?

**Comment by FRASTM** [comment]
> > Definitely, no difference found between both versions of stm32cube/stm32l4xx 1.16.0 and 1.17 and even latest 1.17.1 gives the same output
> > ```
> >  >>> d.read(2)
> > [1, 11]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > etc
> 
> Thanks @FRASTM, was it tested using L4 or L4+ ?

This was tested on a nucleo_l452re board where USB is connected on pin PA11 & PA12 (usb_dm_pa11 & usb_dp_pa12)
with latest ../modules/hal/stm32/stm32cube/stm32l4xx = v1.17.1

**Comment by erwango** [comment]
Closing as not reproduced on our side.
Please reopen if required
