### ISSUE TITLE
Instruction fetch fault happens on RISC-V with XIP and userspace enabled

### ISSUE THREAD

**Issue by atshinbo-etrinity** [zephyrproject-rtos/zephyr#39922]
**Describe the bug**
When run samples/userspace/hello_world_user on hifive1_revb with XIP enabled, instruction fetch fault happens.

The value set to the pmpaddr1 register was not appropriate for NAPOT format.
pmpaddr0 : 0x20000004 (NA4   0x80000010 - 0x80000013)
pmpaddr1 : 0x08006442 (NAPOT invalid value)
pmpaddr2 : 0x20000c7f (NAPOT 0x80003000 - 0x800033FF)
pmpcfg0  : 0x001b1d11

**Expected behavior**
"Table 3.9: NAPOT range encoding in PMP address and configuration registers" of "Volume II: RISC-V Privileged Architectures V1.10" says,
> aaaa...aaa0 NAPOT 8-byte NAPOT range
> aaaa...aa01 NAPOT 16-byte NAPOT range
> aaaa...a011 NAPOT 32-byte NAPOT range
> ...

The size part of NAPOT value should be power of two. And when the size is larger than 16 bytes, LSB bit should be 1.

**To Reproduce**
1. Modify samples/userspace/hello_world_user/src/main.c so that the link result does not exceed the RAM capacity.
```
< #define USER_STACKSIZE	2048

> #define USER_STACKSIZE	1024
```
2. west build -b hifive1_revb samples/userspace/hello_world_user
3. cd build/zephyr
4. $ZEPHYR_SDK_INSTALL_DIR/riscv64-zephyr-elf/bin/riscv64-zephyr-elf-objcopy -O ihex zephyr.elf zephyr.hex
5. Write zephyr.hex to the Hifive1 revB board and run.

**Logs and console output**
> *** Booting Zephyr OS build v2.7.99-779-gf6e829a68b1a  ***
> E:
> E:  mcause: 1, Instruction Access fault
> E:   mtval: 2001367c
> E:      a0: 20010e7c    t0: 20013680
> E:      a1: 00000000    t1: 200137fc
> E:      a2: 00000000    t2: 7fffffff
> E:      a3: 00000000    t3: 2001d484
> E:      a4: 00000001    t4: 2001d484
> E:      a5: 80000000    t5: 2001d484
> E:      a6: 00000000    t6: 2001d484
> E:      a7: ffffffff
> E:                      tp: 2001d484
> E:      ra: 200137c0
> E:    mepc: 2001367c
> E: mstatus: 00000080
> E:
> E: >>> ZEPHYR FATAL ERROR 0: CPU exception on CPU 0
> E: Current thread: 0x80000048 (unknown)
> E: Halting system

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04.5 LTS
 - Toolchain: zephyr-sdk-0.13.1
 - Version: v2.7.99
 - Commit: f6e829a68b1ae7b127bb847d0947df0cc9f708a2
 - Target: hifive1_revb

**Additional context**

Workaround:
The value of pmpaddr is calcuteled at zephyr/arch/riscv/core/pmp/core_pmp.c.
```
 234 :        ulong_t rom_size = (ulong_t) __rom_region_size;
 250 :        thread->arch.u_pmpaddr[index] = TO_PMP_NAPOT(rom_start, rom_size);
 251 :        uchar_pmpcfg[index++] = PMP_NAPOT | PMP_R | PMP_X;
```
In this implementation, rom_size is expected to be power of two.
For workaround, change zephyr/include/arch/riscv/common/linker.ld as following,
```
< __rom_region_size = __rom_region_end - __rom_region_start;

> __rom_region_size_orig = __rom_region_end - __rom_region_start;
> __rom_region_size = (1 << LOG2CEIL(__rom_region_size_orig));
```

After changes, 
pmpaddr0 : 0x20000004 (NA4   0x80000010 - 0x80000013)
pmpaddr1 : 0x08007fff (NAPOT 0x20000000 - 0x2003FFFF)
pmpaddr2 : 0x20000c7f (NAPOT 0x80003000 - 0x800033FF)
pmpcfg0  : 0x001b1d11

**Comment by fkokosinski** [comment]
Hi, thanks for reporting this issue. I've tried reproducing the error that you've described here, but wasn't able to. 

> **Describe the bug**
> When run samples/userspace/hello_world_user on hifive1_revb with XIP enabled, instruction fetch fault happens.

Could you elaborate on how you enable XIP? From what I see, it's enabled by default (`CONFIG_XIP=y`).

**Comment by cwshu** [comment]
@atshinbo-etrinity @fkokosinski
It is a problem that rom_region symbols aren't power-of-2 alignment in XIP RISC-V when `CONFIG_PMP_POWER_OF_TWO_ALIGNMENT=y`. It breaks NAPOT mode PMP region.

```
$ nm -n zephyr/zephyr.elf | grep rom_region
00011f68 A __rom_region_size
20010000 A __rom_region_start
20021f68 A __rom_region_end
```

I think it is not easy to align rom_region symbols in the linker script in XIP mode (e.g. align both start & end symbol via MPU_ALIGN()).
Instead, we can use another way to protect ROM region in XIP mode: configure whole flash area via single PMP region with RX attr. It is used in Cortex-M implementation: `soc/arm/common/cortex_m/arm_mpu_regions.c`

I also implement it on the PR #39299 just now, and verify it on the QEMU (qemu_riscv32_xip, but patched for larger memory size to avoid RAM overflow).
Would you like to verify it on real HW? I think it should resolve this issue.

**Comment by atshinbo-etrinity** [comment]
Thank you for the pull request.
I have tried to execute it on the real Hifive1 revB board.

Unfortunately, a fault has occurred again.

```
*** Booting Zephyr OS build v2.7.99-729-g64b99b2faeed  ***
E:
E:  mcause: 1, Instruction Access fault
E:   mtval: 20013d94
E:      a0: 20010e9c    t0: 20013d98
E:      a1: 00000000    t1: 20013f14
E:      a2: 00000000    t2: 7fffffff
E:      a3: 00000000    t3: 76697264
E:      a4: 00000001    t4: 00007265
E:      a5: 80000000    t5: 6e756f63
E:      a6: 00000004    t6: 20726574
E:      a7: ffffffff
E:                      tp: 7264206d
E:      ra: 20013ed8
E:    mepc: 20013d94
E: mstatus: 00000080
E:
E: >>> ZEPHYR FATAL ERROR 0: CPU exception on CPU 0
E: Current thread: 0x80000048 (unknown)
E: Halting system
```

* The results of my investigation

The actual value set to the pmp registers in this pull request are belows.
```
pmpaddr7 : 0x0807c11f (NAPOT 0x201F0400 - 0x201F04FF)
pmpcfg1 : 0x9d000000
pmpaddr0 : 0x20000004 (NA4 0x80000010 - 0x80000013)
pmpaddr1 : 0x20000c7f (NAPOT 0x80003000 - 0x800033FF)
pmpcfg0 : 0x00001b11
```

The value of pmpaddr7 is set according to the definition of mpu_regions[0].
And actual definition on my build are following.
> {start = 0x20010000, size = 0x3c0900, perm = 0x85, mode = 0x1}

Above definition seems like taken from following values.
```
zephyr/zephyr.map
Name             Origin             Length             Attributes
ROM              0x0000000020010000 0x00000000003c0900 xr
RAM              0x0000000080000000 0x0000000000004000 xrw
IDT_LIST         0x00000000fffff7ff 0x0000000000000800 xw
```

I think the root cause is that the size part of NAPOT value should be power of two, and size=0x3c0900 does not match this constraint.
The value of pmpaddr7 register (=0x0807c11f) is separated by the hardware into address part and size part by least bit of 0 bit.
```
pmpaddr7 = 0x0807c11f = 0b1000000001111100000100011111
address  = 0b1000000001111100000100000000 = 0x0807c100 (means start address is 0x201F0400)
size     = 0b11111 = 0x1f (means size is 0x100)
```
This result is not expected one.

**Comment by cwshu** [comment]
hmm, I find the problem is because flash base & size in hifive1_revb isn't power-of-2 alignment.
I didn't notice that hifive1 and hifive1_revb has different flash address.

Flash base & size: (2nd reg of `&spi0` in `<BOARD>.dts`)
- hifive1 / qemu_riscv32_xip: (0x20400000, 0xc00000)
- hifive1_revb: (0x20010000, 0x3c0900)

It needs some modification of PMP porting to handle unaligned flash size, but flash base of `hifive1_revb` also seems a trouble (only be aligned to 0x10000)

**Comment by cwshu** [comment]
@atshinbo-etrinity 
I create new PR #40647 for this issue.
Unaligned flash address has been fixed and I have tested it on QEMU. (PMP region should be 0x20000000 ~ 0x20400000)
Would you like to try it on real HW?

**Comment by atshinbo-etrinity** [comment]
Thank you for the pull request.
I have confirmed that the PR #40647 solved the issue on the real Hifive1 revB hardware.
I think this issue can be closed.

**Comment by cwshu** [comment]
@atshinbo-etrinity Thank you for verification.

@tgorochowik I'd like to handle this issue, could you assign it to me?

**Comment by tgorochowik** [comment]
Sure, thanks!
