### ISSUE TITLE
STM32L496AG mcu flash can not be erase, write

### ISSUE THREAD

**Issue by glin00** [zephyrproject-rtos/zephyr#39937]
**Describe the bug**
I want to access STM32L496AG16P mcu flash memory. The following is my code. Device binding is ok but erase get fail.
Does anybody know why it happen? And how to solve this?

**To Reproduce**
<code implentations>
 flash_device =
		device_get_binding(DT_CHOSEN_ZEPHYR_FLASH_CONTROLLER_LABEL);
	if (flash_device) {
		APP_UART_SendString("\n\rflash device ok");
	} else {
		APP_UART_SendString("\n\rflash device fail");
	}

    addr=0x080f0000;
    ret = flash_erase(flash_device, addr, len);
    if (ret == 0) {
        APP_UART_SendString("\n\rflash ers ok");
    }else {
        APP_UART_SendString("\n\rflash ers fail");
    }
    for (i=0;i<len; i++) {
        wr_buf[i]=(uint8_t)(i%0x100);
    }
    ret = flash_write(flash_device, addr, wr_buf, len);
    if (ret == 0) {
        APP_UART_SendString("\n\rflash write ok");
    }else {
        APP_UART_SendString("\n\rflash write fail");
    }

<prj.conf>
CONFIG_FLASH=y

uart print result:

flash device ok

flash ers fail

**Expected behavior**
mcu flash rom erase, write should be working, but it is not working now.

**Environment (please complete the following information):**
Hardware:STM32L496AG16P 
Linux Ubuntu 20.04.3 LTS
Zephyr SDK,-0.13.0
Zephyr SHA1 ID:bb85a55

**Comment by erwango** [comment]
@glin00 Can you have another test using `samples/drivers/flash_shell` ?
