### ISSUE TITLE
twister: cannot build samples/tests on Windows

### ISSUE THREAD

**Issue by gopiotr** [zephyrproject-rtos/zephyr#40007]
**Describe the bug**
Twister cannot be used to run tests with `--build-only` flag on Windows OS.

**To Reproduce**
1. Clone Zephyr repository on Windows OS according to this tutorial:
https://docs.zephyrproject.org/latest/getting_started/index.html# 
2. Run Twister to build `hello_world` sample by this command:
```
python scripts/twister -p nrf52840dk_nrf52840 -T samples/hello_world --ninja --build-only
```

**Expected behavior**
Sample should be built with no error.

**Impact**
Twister cannot be used on Windows for build any samples or tests

**Logs and console output**
```
>python scripts/twister -p nrf52840dk_nrf52840 -T samples/hello_world --ninja --build-only 
ZEPHYR_BASE unset, using "C:\zephyr"
Traceback (most recent call last):
  File "C:\zephyr\scripts\twister", line 209, in <module>
    from twisterlib import HardwareMap, TestSuite, SizeCalculator, CoverageTool, ExecutionCounter
  File "C:\zephyr\scripts/pylib/twister\twisterlib.py", line 28, in <module>
    import pty
  File "C:\Python39\lib\pty.py", line 12, in <module>
    import tty
  File "C:\Python39\lib\tty.py", line 5, in <module>
    from termios import *
ModuleNotFoundError: No module named 'termios'
```

**Environment:**
 - OS: Windows 10
 - Toolchain: GNU Arm Embedded
 - Commit SHA: e8f09b471e907d05772b8fc42e9e14a28101c0b8

**Additional information**
I already have proposition for fix this bug and I will create PR soon

**Comment by nashif** [comment]
@gopiotr  can you please send a PR?
