### ISSUE TITLE
samples or unit test for components without RTOS

### ISSUE THREAD

**Issue by TheSilentDawn** [zephyrproject-rtos/zephyr#40042]
**Is your feature request related to a problem? Please describe.**
With RTOS, it's hard to debug the program step by step.

**Describe the solution you'd like**
Provides samples or unit tests compiled as a bare-metal firmware which enrolls components such as Bluetooth, without RTOS.

**Comment by henrikbrixandersen** [comment]
Let me understand this correctly. You want to use the Zephyr RTOS without the RTOS part?

**Comment by nashif** [comment]
Sorry, we are an RTOS, we test as an RTOS, in an RTOS.
