### ISSUE TITLE
OBJECT_TRACING for kernel objects

### ISSUE THREAD

**Issue by rdienstbeck** [zephyrproject-rtos/zephyr#40119]
Unfortunately, the object tracing for kernel objects was dropped from version 2.5 to 2.6. 

Our (Lauterbach) debuggers provide a Zephyr awareness, that allows to list and inspect threads and kernel objects. We used the linked list created by CONFIG_OBJECT_TRACING to show tables of created objects, e.g. semaphores or mutexes. Since Zephyr version 2.6, this linked list is no longer configurable, which makes it impossible for debuggers to find and display created objects.

It would be great to get the linked list back in the kernel objects, e.g. like it was in k_mutex of 2.5:
https://github.com/zephyrproject-rtos/zephyr/blob/8be935fe5cda14db37549446e2d571b485cddf0e/include/kernel.h#L3087

**Comment by dleach02** [comment]
@rdienstbeck, can you bisect to the exact changeset that broke this feature for you?

**Comment by rdienstbeck** [comment]
@dleach02, thanks for looking into this. The bisect was easy, the change log actually says "kernel: remove object tracing":
https://github.com/zephyrproject-rtos/zephyr/commit/4d994af03284ce94616c00c741e21b9b22e8ff62#diff-d425c69d5282cb213b62e545f89a0aa44326d0187725db1d83c8209a9bb1585f
Change from May 8 2021.

**Comment by dleach02** [comment]
Okay. So it was removed with this PR #34843

**Comment by tleksell-pe** [comment]
Interesting, I don't think there should be any problems re-adding this kind of feature as a "new" trace format within the updated tracing system that was introduced in PR #34843.

**Comment by nashif** [comment]
Hi @rdienstbeck, and nice to meet you again, we often meet at Embedded World ;-)
There were issues with the design of the original feature and realized the new tracing support added in 2.5 would mostly replace that, but I guess this will not replace the availability of this data in the debugger. Will take a look and see how we can solve this.

**Comment by rdienstbeck** [comment]
Hi @nashif, I remember our talks at EW, nice to talk to you again!
Thanks for looking into this, customers are already complaining...

**Comment by edersondisouza** [comment]
@rdienstbeck have you had the chance to look at #40606 ?

**Comment by rdienstbeck** [comment]
Hi @edersondisouza ,
I had a quick look at it, implemented it and tested it in our debugger. It looks like this includes exactly what we need. Thanks a lot for this!
I will modify our Zephyr Awareness to use the linked list as defined in #40606 and will report my results here.
It's now part of CONFIG_TRACING, which also offers a lot of options (and additional code) for tracing, while it is not exactly for tracing but only for keeping a list of objects. Me, personally, I'd put it to kernel debugging options rather than to tracing, but then I'm not a Zephyr expert...

**Comment by dleach02** [comment]
@rdienstbeck, recommend you provide your feedback/results directly to #40606. When that gets approved/merged it will automatically close this issue
