### ISSUE TITLE
Build fails with `CONFIG_SHELL_VT100_COMMANDS=n`

### ISSUE THREAD

**Issue by weinholtendian** [zephyrproject-rtos/zephyr#40124]
Zephyr apps do not build with `CONFIG_SHELL_VT100_COMMANDS=n`.

**To Reproduce**
1. `echo CONFIG_SHELL_VT100_COMMANDS=n >> samples/subsys/shell/fs/prj.conf`
2. `west build -b nrf52840dk_nrf52840 samples/subsys/shell/fs`
3. See error:

```
zephyr/subsys/shell/shell_cmds.c:446:26: error: 'cmd_clear' undeclared here (not in a function); did you mean 'cmd_select'?
        SHELL_HELP_CLEAR, cmd_clear, 1, 0);
```

**Expected behavior**
It should build.

**Impact**
Annoyance. In our case we can filter the vt100 codes elsewhere.

**Environment (please complete the following information):**
 - OS: Debian bullseye
 - Toolchain: arm-none-eabi- cross-compiler
 - Commit 963d05bd525766701cbce44d0aaa63f57e26ae9b

**Comment by jakub-uC** [comment]
I will fix it shortly. Thank you for finding
