### ISSUE TITLE
Use correct clock frequency for systick+DWT

### ISSUE THREAD

**Issue by Michel-Haber** [zephyrproject-rtos/zephyr#40163]
**Is your enhancement proposal related to a problem? Please describe.**
 zephyr/arch/arm/core/aarch32/cortex_m/timing.c uses CONFIG_SYS_CLOCK_HW_CYCLES_PER_SEC to determine the Arm core's frequency, but this variable doesn't necessarily have the right value if CONFIG_TIMER_READS_ITS_FREQUENCY_AT_RUNTIME is set.

**Describe the solution you'd like**
sys_clock_hw_cycles_per_sec() should be used to replace the config constant when CONFIG_TIMER_READS_ITS_FREQUENCY_AT_RUNTIME is set

**Additional context**
I believe this is a latent error from before frequency change at runtime was introduced.

**Comment by carlescufi** [comment]
@Michel-Haber thanks for this, would you mind sending a Pull Request to fix it?

**Comment by Michel-Haber** [comment]
Sure, @carlescufi PR #40219
