### ISSUE TITLE
Shell module doesn't work on main branch for esp32 board

### ISSUE THREAD

**Issue by andrei-edward-popa** [zephyrproject-rtos/zephyr#40198]
**Describe the bug**
On the main branch, I think something is crashed on the shell part because when I load the code into the board nothing happens.

**To Reproduce**
1. west build -b esp32 samples/subsys/shell/shell_module
2. west flash

**Logs and console output**
Nothing is output to the console.

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04 LTS
 - Toolchain ESP-IDF
 - On the main branch

**Additional context**
Can you check this?

**Comment by andrei-edward-popa** [comment]
@sylvioalves I think something is broken in uart driver (drivers/serial/uart_esp32.c) because with previous version it works.

**Comment by sylvioalves** [comment]
Sure, that uart update should be pre-kernel initialization and not post kernel. Submitting a PR.  
Thanks for pointing that out.

**Comment by andrei-edward-popa** [comment]
@sylvioalves I tried to put PRE_KERNEL_1 instead of POST_KERNEL in driver, but still doesn't work

**Comment by sylvioalves** [comment]
You need to use PRE_KERNEL_2 because pinmux needs to be initilialized before.
