### ISSUE TITLE
[v2.7-branch] hci_spi sample cannot be built for nrf51dk_nrf51422 and 96b_carbon_nrf51

### ISSUE THREAD

**Issue by anangl** [zephyrproject-rtos/zephyr#40244]
**Describe the bug**
An attempt to build the hci_spi sample for any of the platforms indicated as allowed in its `sample.yaml` file ends up with a "region `SRAM' overflowed" error.

**To Reproduce**
Build `samples/bluetooth/hci_spi` for `nrf51dk_nrf51422` or `96b_carbon_nrf51`.

**Expected behavior**
The sample should build fine for platforms listed as `allowed_platforms` in its `sample.yaml` file.

**Impact**
Annoyance.

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: Zephyr SDK 0.13.1
 - Commit SHA: 3a39b7824eb68c724afc3e25659a6c53cfb1804d

**Comment by carlescufi** [comment]
#40155 is now merged
