### ISSUE TITLE
https://github.com/zephyrproject-rtos/zephyr/blob/main/include/drivers/counter.h

### ISSUE THREAD

**Issue by sadapenore** [zephyrproject-rtos/zephyr#40350]
https://github.com/zephyrproject-rtos/zephyr/blob/main/include/drivers/counter.h

_Originally posted by @carlescufi in https://github.com/zephyrproject-rtos/zephyr/issues/40247#issuecomment-965193510_

Thank you for prompt response.

I tried using the counter example which uses RTC as clock source.
So I cannot change the resolution below 1 second.
I need timer interval in the order of few milliseconds to 100 micro seconds.
So that is not suitable. ( Please confirm )
I tried using 'timers1' but it is giving below error:
"C:/xxxxx/.platformio/packages/framework-zephyr/include/devicetree.h:303:40: error: 'DT_N_INST_0_timers1_P_label' was not declared in this scope"
The timers1 device is already define in dts file and status is marked as okay.

Is this error because the timer hal is not supported?

**Comment by erwango** [comment]
Incoming with https://github.com/zephyrproject-rtos/zephyr/pull/39414
