### ISSUE TITLE
Request more information at bug submission

### ISSUE THREAD

**Issue by erwango** [zephyrproject-rtos/zephyr#40356]
**Is your enhancement proposal related to a problem? Please describe.**

It happens often that we are missing basic inputs in bug descriptions,
and some bug descriptions look like the user dropped the issue just
before running away from a building in fire.

In section `**Environment **`, we should also request: 
- hardware platform in use

In `**Additional context**`, instead of `Add any other context about the problem here.`, be more explicit:
Please provide any information that could be relevant to your issue, such as pin setting, ..
Also, you could details the attempts you made to solve the issue by your own..

**Describe alternatives you've considered**
Close bugs with obviously missing information

**Comment by erwango** [comment]
@carlescufi Maybe you know the person I can assign this to ?

**Comment by nashif** [comment]
@erwango  why dont you just submit a PR with required changes to .github/ISSUE_TEMPLATE/bug_report.md ?
