### ISSUE TITLE
sample: cycle_64 is failing out due to a timeout on 64-bit versions of qemu_x86 and ehl_crb

### ISSUE THREAD

**Issue by yerabolu** [zephyrproject-rtos/zephyr#40367]
**Describe the bug**
Sample cycle64 in Kernel should run successfully but it is failing on **64-bit version of qemu_x86 and ehl_crb**. 

What have you tried to diagnose or workaround this issue?
Ran the sample on 32-bit qemu_x86 and it is passing without any issue. 

**To Reproduce**
1. twister -W -p qemu_x86_64 -T samples/kernel/cycle64/  -j 1 -vvv    
                    **or** 
 twister -W -p ehl_crb --device-testing --device-serial /dev/ttyUSB0 -T samples/kernel/cycle64/  --west-flash=/home/ztest/EHL_X86_PXE.sh -j 1

2. See timeout.

**Expected behavior**
```
DEBUG   - QEMU (2771557): Booting from ROM..*** Booting Zephyr OS build v2.7.99-1382-g742412606090  ***
DEBUG   - QEMU (2771557): wrap-around should occur in 42s
DEBUG   - QEMU (2771557): [ddd:hh:mm:ss.0ms]
DEBUG   - QEMU (2771557): [000:00:00:00.000]: cycle: 000000000001fad0
DEBUG   - QEMU (2771557): [000:00:00:42.960]: cycle: 00000001000fd823
DEBUG   - QEMU (2771557): [000:00:01:25.920]: cycle: 00000002001f9a23
DEBUG   - QEMU (2771557): [000:00:02:08.880]: cycle: 00000003002f5c23
DEBUG   - QEMU (2771557): SUCCESS
DEBUG   - QEMU (2771557) complete (passed) after 2.0869383811950684 seconds
DEBUG   - No timeout, return code from QEMU (None): 0
DEBUG   - return code from QEMU (None): 0
```

**Logs and console output**
```
DEBUG   - QEMU (2772183): Booting from ROM..*** Booting Zephyr OS build v2.7.99-1382-g742412606090  ***
DEBUG   - QEMU (2772183): wrap-around should occur in 42s
DEBUG   - QEMU (2772183): [ddd:hh:mm:ss.0ms]
DEBUG   - QEMU (2772183): [000:00:00:00.010]: cycle: 000000000014555c
DEBUG   - QEMU (2772183): [000:00:00:42.980]: cycle: 00000001005cecd4
```

**Environment (please complete the following information):**
 - OS: Fedora
 - Toolchain: SDK 0.13.1
 - Commit SHA: 74241260

**Comment by cfriedt** [comment]
Thanks - I'll take a look at it.

**Comment by cfriedt** [comment]
```
```

Right - there is a reason that these platforms are not used in

**Comment by cfriedt** [comment]
Reopening since I've had 2 reports of this now.
