### ISSUE TITLE
Bluetooth: Controller: Move BT_EVT_MASK_LE_META_EVENT check to a common place

### ISSUE THREAD

**Issue by cvinayak** [zephyrproject-rtos/zephyr#40375]
**Is your enhancement proposal related to a problem? Please describe.**
`(event_mask & BT_EVT_MASK_LE_META_EVENT)`  is check many places in the code. Would it be possible to move this checks to a single place in e.g. `encode_control` for all LE events?

**Describe the solution you'd like**
https://github.com/zephyrproject-rtos/zephyr/pull/31009/files#r736212741

**Describe alternatives you've considered**

**Additional context**
Add any other context or graphics (drag-and-drop an image) about the feature request here.

**Comment by wolterhv** [comment]
@cvinayak I see that the pull request, which you referenced as the solution to this issue in the issue description, is merged. Is this issue still open in spite of that?

**Comment by cvinayak** [comment]
Not planned in the near future.
