### ISSUE TITLE
modem: uart interface does not disable TX interrupt in ISR

### ISSUE THREAD

**Issue by JordanYates** [zephyrproject-rtos/zephyr#40371]
**Describe the bug**

The UART ISR handler `modem_iface_uart_isr` in `modem_iface_uart.c` does not disable the TX interrupt when executed.
For the `uart_nrfx_uarte` serial driver at least, this results in the UARTE ISR permanently triggering after the end of the first transmission.
This locks up the system.

**To Reproduce**

Place an `esp-at` device on a UARTE port and attempt to run the `samples/net/wifi` sample.
```
&uart0 {
	compatible = "nordic,nrf-uarte";
	current-speed = <115200>;
	status = "okay";
	tx-pin = <34>;
	rx-pin = <33>;
	rts-pin = <40>;
	cts-pin = <7>;

	esp32e16 {
		compatible = "espressif,esp-at";
		label = "esp32e16";
		status = "okay";
	};
};
```
By default, the application will not reach the boot banner.
Adding the following lines to the bottom of `modem_iface_uart_isr ` resolves this issue:
```
	/* Disable the TX interrupt once tranmission is complete */
	if (uart_irq_tx_complete(ctx->iface.dev)) {
		uart_irq_tx_disable(ctx->iface.dev);
	}
```

**Expected behavior**
The interrupt should not be permanently triggered.

**Impact**
Applications fail to boot.

**Environment (please complete the following information):**
 - Zephyr v2.7.0

**Comment by carlescufi** [comment]
@rerickson1 could you please take a look and send a PR if appropriate?

**Comment by rerickson1** [comment]
> @rerickson1 could you please take a look and send a PR if appropriate?

I could submit a PR but have no way of testing this. @JordanYates could you submit a PR with your requested change?

**Comment by JordanYates** [comment]
> I could submit a PR but have no way of testing this. @JordanYates could you submit a PR with your requested change?

Done
