### ISSUE TITLE
Undefined escape sequence: ill-formed for the C standard

### ISSUE THREAD

**Issue by Abramo-Bagnara** [zephyrproject-rtos/zephyr#40439]
<code>#define Z_PROGBITS_SYM  "\\%"</code>

The <code>"\\%"</code> string literal used in <code>#define Z_PROGBITS_SYM "\\%"</code> has
the syntax of a C escape sequence, but no defined meaning by the C standard.
It should be replaced with <code>"%"</code> or with <code>"\\\\%"</code> depending on whether
the intended behavior is to produce the <code>%</code> or the <code>\\%</code> strings, respectively.

**Comment by dcpleung** [comment]
?????

It is `"\%"` with the back slash already.

**Comment by Abramo-Bagnara** [comment]
Sorry, I've messed up with the markup. Please see the edited note.

**Comment by stephanosio** [comment]
https://github.com/zephyrproject-rtos/zephyr/blob/21d1ad3762302b3e461953df59430c77e0709274/include/app_memory/app_memdomain.h#L84

**Comment by cfriedt** [comment]
@nashif @dcpleung - can you please categorize this issue? Is it a bug?

It sounds as though this is for linker script generation.

**Comment by d3zd3z** [comment]
I believe the fix is to just remove the backslash. It would generate a compiler warning, if the appropriate warning were enabled. However, I believe the behavior would be correct.

**Comment by dcpleung** [comment]
Not sure if this is actually a bug... the Zephyr toolchains never complain about this, and it is working for generating the necessary assembly code.

**Comment by RobertoBagnara** [comment]
Well, see, e.g., C18 6.4.4.4 (Character constants) and, in particular, footnote 179 where it says "If any other character follows a backslash, the result is not a token and a diagnostic is required."
The support for \% as a valid escape sequence could be offered as an extension by all Zephyr toolchain but, unless I am missing something, they are all GCC-based, and GCC does not officially offer such an extension: https://gcc.gnu.org/onlinedocs/gcc/C-Extensions.html#C-Extensions
As a result, Zephyr is now counting on what, at best, is an undocumented GCC extension, and GCC is not compliant to the C standard if it is true that it is not giving the diagnostic required by the standard.
Given that there is no need whatsoever to have that backslash, removing it seems to me the only sensible thing to be done.

**Comment by dcpleung** [comment]
I actually have submitted a PR to remove the slash.

Just out of curiosity, what does C99 say about this? I was only able to search for the C17 draft which doesn't have footnote 179. And the C99 draft doesn't have similar footnote.

**Comment by RobertoBagnara** [comment]
C99 TC3 says the same thing, as far as I can see. The clause has the same number  6.4.4.4 (Character constants), the footnote text seems the same, but the footnote number if 65.  You can download the last draft before ISO blessing here: http://www.open-std.org/jtc1/sc22/wg14/www/docs/n1256.pdf
