### ISSUE TITLE
Bluetooth: L2CAP tester application is missing preprocessor flags for ECFC function call

### ISSUE THREAD

**Issue by LundinJohan** [zephyrproject-rtos/zephyr#40456]
Compiling the L2CAP tester application with CONFIG_BT_L2CAP_ECRED=n produces a bug since there is a function call not guarded by ifdefs here: https://github.com/zephyrproject-rtos/zephyr/blob/main/tests/bluetooth/tester/src/l2cap.c#L322

**Comment by carlescufi** [comment]
Fixed by #40498
