### ISSUE TITLE
Upgrade LittleFS to 2.4.1 version

### ISSUE THREAD

**Issue by poojamg** [zephyrproject-rtos/zephyr#40462]
## Origin

https://github.com/littlefs-project/littlefs

## Purpose

Latest version has flags like LFS_READONLY to produce smaller code print

## Mode of integration

module to existing littlefs in zephyr

## Pull Request
https://github.com/zephyrproject-rtos/littlefs/pull/7

## Description

# Dependencies

## Revision
Version 2.4.1

**Comment by de-nordic** [comment]
Would fix issue https://github.com/zephyrproject-rtos/zephyr/issues/40453

**Comment by carlescufi** [comment]
@poojamg no need for an issue, just need the PR to be merged. Thanks!
