### ISSUE TITLE
npcx uart driver uses device PM callback to block suspension

### ISSUE THREAD

**Issue by gmarull** [zephyrproject-rtos/zephyr#40621]
**Describe the bug**

The npcx UART driver is currently using the device PM callback to block suspension if the UART is transmitting, as shown below:

https://github.com/zephyrproject-rtos/zephyr/blob/5e035b0f4eb43df68313b401e0a71d2cdcd54d65/drivers/serial/uart_npcx.c#L441-L460

The device PM callback needs to be used only to suspend/resume devices. If the system cannot be suspended because UART is in a particular state, the `pm_constraint_set/release` API should be used.

**To Reproduce**

https://github.com/zephyrproject-rtos/zephyr/blob/main/drivers/serial/uart_npcx.c

**Expected behavior**

Device driver should prevent system suspension by using `pm_constraint_set/release` API.

**Impact**

PM API misuse, PM subsystem needs to account for such “special cases” when it should not.

**Logs and console output**

N/A

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: Zephyr SDK
 - Commit SHA or Version used: 5e035b0

**Additional context**

STM32 UART driver may be taken as an example: https://github.com/zephyrproject-rtos/zephyr/blob/main/drivers/serial/uart_stm32.c#L85

**Comment by MulinChao** [comment]
@gmarull Got it. Nuvoton will prepare a PR to fix this bug.
