### ISSUE TITLE
drivers: usb_dc_mcux: processing endpoint callbacks in ISR context causes assertion

### ISSUE THREAD

**Issue by ottojo** [zephyrproject-rtos/zephyr#40638]
**Describe the bug**
When using USB networking, the driver accesses networking functions which lock mutexes from ISR context. This leads to failed assertion `mutexes cannot be used inside ISRs.`.

* `ecm_status_cb` is registered as USB status callback [here](https://github.com/zephyrproject-rtos/zephyr/blob/main/subsys/usb/class/netusb/function_ecm.c#L435) (apparently called via ISR)
* `ecm_status_cb` calls `ecm_status_interface` [here](https://github.com/zephyrproject-rtos/zephyr/blob/main/subsys/usb/class/netusb/function_ecm.c#L374)
* `ecm_status_interface` calls `netusb_enable` [here](https://github.com/zephyrproject-rtos/zephyr/blob/main/subsys/usb/class/netusb/function_ecm.c#L356)
* `netusb_enable` calls `net_if_up` [here](https://github.com/zephyrproject-rtos/zephyr/blob/main/subsys/usb/class/netusb/netusb.c#L102)
* `net_if_up` locks mutex [here](https://github.com/zephyrproject-rtos/zephyr/blob/main/subsys/net/ip/net_if.c#L3978)

* `netusb_enable` calls `net_if_up` [here](https://github.com/zephyrproject-rtos/zephyr/blob/main/subsys/usb/class/netusb/netusb.c#L102)

**To Reproduce**
(Working on providing a minimal example...)

**Expected behavior**
Assertion should not fail, the interface should not be enabled from ISR context.

**Impact**
The network interface seems to work, but this makes it impossible to me to use `__ASSERT`, since the program can't run with `CONFIG_ASSERT` enabled.

**Logs and console output**
(WIP)

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04
 - Toolchain: Zephyr SDK 0.13.1
 - Zephyr: 70b0734b5e53d53b49e1fd95feef5cd2ff233117 (reasonably recent main branch)
 - Board: `teensy41`

**Comment by jfischer-no** [comment]
@ottojo There is no workaround, USB_DeviceNotificationTrigger needs to be offloaded to a thread/workqueue.

**Comment by danieldegrasse** [comment]
@ottojo I can reproduce the error on a RT1064 EVK building the "echo_server" sample with the following command:
`west build -p always -b mimxrt1064_evk samples/net/sockets/echo_server -DOVERLAY_CONFIG=overlay-netusb.conf -DCONFIG_ETH_MCUX=n -DCONFIG_ASSERT=y`. On my board, #42019 fixes the issue (per @jfischer-no's suggestion of offloading the ISR to a thread) can you verify that branch works for you?
