### ISSUE TITLE
intel_adsp_cavs15:  the zephyr_pre0.elf  is quite large (530MB) on ADSP for some test cases

### ISSUE THREAD

**Issue by enjiamai** [zephyrproject-rtos/zephyr#40643]
**Describe the bug**
The zephyr_pre0.elf is quite large, about 530MB, when the test cases have CONFIG_USERSPACE=y or CONFIG_HAS_DTS=y  
Take "tests/kernel/mutex/sys_mutex/system.mutex.nouser" as an example, running the original test case need about 20M disk space, but after this commit:
28b2e55321 cmake: rework linker script generation and linker prebuilt stages
This single test cases need about 540M disk space to run.

**To Reproduce**
1. source zephyr-env.sh
2. twister -p intel_adsp_cavs15 --device-testing -s tests/kernel/mutex/sys_mutex/system.mutex.nouser --west-flash="/home/ztest/work/zephyrproject/zephyr/boards/xtensa/intel_adsp_cavs15/tools/flash.sh,/home/ztest/work/zephyrproject/modules/audio/sof/keys/otc_private_key.pem,/home/ztest/work/rimage/config,/home/ztest/work/rimage/build/rimage" --device-serial-pty="/home/ztest/work/zephyrproject/zephyr/boards/xtensa/intel_adsp_cavs15/tools/adsplog.py,--no-history"
3. du -sh twister-out
4. You can see the disk space is about 540M

**Expected behavior**
The twister-out should be about 20M.

**Impact**
The test case won't be failure, but it spends lots of diskspace for twister-out.

**Logs and console output**

Please take a look at the size of zephyr_pre0.elf :
```
ztest@zserverUP2:~/work/zephyrproject/zephyr/twister-out/intel_adsp_cavs15/tests/kernel/mutex/sys_mutex/system.mutex.nouser/zephyr$ ls -al
total 529924
drwxrwxr-x 14 ztest ztest      4096 11月 25 09:03 .
drwxrwxr-x  8 ztest ztest      4096 11月 25 09:03 ..
drwxrwxr-x  5 ztest ztest      4096 11月 25 09:03 arch
drwxrwxr-x  3 ztest ztest      4096 11月 25 09:03 boards
-rw-rw-r--  1 ztest ztest       197 11月 25 09:03 boot_ldr.d
-rw-rw-r--  1 ztest ztest      5472 11月 25 09:03 boot_ldr.ld
-rwxrwxr-x  1 ztest ztest     15812 11月 25 09:03 bootloader.elf.mod
drwxrwxr-x  5 ztest ztest      4096 11月 25 09:03 cmake
-rw-rw-r--  1 ztest ztest        96 11月 25 09:03 .cmake.dotconfig.checksum
drwxrwxr-x 17 ztest ztest      4096 11月 25 09:03 CMakeFiles
-rw-rw-r--  1 ztest ztest     15056 11月 25 09:03 cmake_install.cmake
-rw-rw-r--  1 ztest ztest     17196 11月 25 09:03 .config
-rw-rw-r--  1 ztest ztest      1614 11月 25 09:03 dev_handles.c
drwxrwxr-x 10 ztest ztest      4096 11月 25 09:03 drivers
-rw-rw-r--  1 ztest ztest     12237 11月 25 09:03 dts.cmake
-rw-rw-r--  1 ztest ztest    175590 11月 25 09:03 edt.pickle
drwxrwxr-x  3 ztest ztest      4096 11月 25 09:03 include
-rw-rw-r--  1 ztest ztest       500 11月 25 09:03 intel_adsp_cavs15.dts.pre.d
-rw-rw-r--  1 ztest ztest      2430 11月 25 09:03 intel_adsp_cavs15.dts.pre.tmp
-rwxrwxr-x  1 ztest ztest       104 11月 25 09:03 isrList.bin
-rw-rw-r--  1 ztest ztest      7034 11月 25 09:03 isr_tables.c
drwxrwxr-x  3 ztest ztest      4096 11月 25 09:03 kconfig
drwxrwxr-x  3 ztest ztest      4096 11月 25 09:03 kernel
drwxrwxr-x  8 ztest ztest      4096 11月 25 09:03 lib
-rw-rw-r--  1 ztest ztest    764744 11月 25 09:03 libzephyr.a
-rw-rw-r--  1 ztest ztest     22492 11月 25 09:03 linker.cmd
-rw-rw-r--  1 ztest ztest      3162 11月 25 09:03 linker.cmd.dep
-rw-rw-r--  1 ztest ztest     22502 11月 25 09:03 linker_zephyr_pre0.cmd
-rw-rw-r--  1 ztest ztest      3174 11月 25 09:03 linker_zephyr_pre0.cmd.dep
-rw-rw-r--  1 ztest ztest     22502 11月 25 09:03 linker_zephyr_pre1.cmd
-rw-rw-r--  1 ztest ztest      3174 11月 25 09:03 linker_zephyr_pre1.cmd.dep
-rw-rw-r--  1 ztest ztest     58185 11月 25 09:03 Makefile
drwxrwxr-x  3 ztest ztest      4096 11月 25 09:03 misc
-rw-rw-r--  1 ztest ztest       701 11月 25 09:03 runners.yaml
drwxrwxr-x  3 ztest ztest      4096 11月 25 09:03 soc
drwxrwxr-x 19 ztest ztest      4096 11月 25 09:03 subsys
-rw-rw-r--  1 ztest ztest      2363 11月 25 09:03 zephyr.dts
-rwxrwxr-x  1 ztest ztest    638612 11月 25 09:03 zephyr.elf
-rwxrwxr-x  1 ztest ztest    634700 11月 25 09:03 zephyr.elf.mod
-rw-rw-r--  1 ztest ztest    706714 11月 25 09:03 zephyr.lst
-rw-rw-r--  1 ztest ztest    397762 11月 25 09:03 zephyr.map
-rwxrwxr-x  1 ztest ztest 537960404 11月 25 09:03 zephyr_pre0.elf    <== Note here
-rw-rw-r--  1 ztest ztest    397129 11月 25 09:03 zephyr_pre0.map
-rw-rw-r--  1 ztest ztest    398450 11月 25 09:03 zephyr_pre1.map
-rw-rw-r--  1 ztest ztest    106496 11月 25 09:03 zephyr.ri
-rw-rw-r--  1 ztest ztest        96 11月 25 09:03 zephyr.ri.met
-rw-rw-r--  1 ztest ztest         0 11月 25 09:03 zephyr.ri.rom
-rw-rw-r--  1 ztest ztest    105344 11月 25 09:03 zephyr.ri.uns
-rw-rw-r--  1 ztest ztest      7092 11月 25 09:03 zephyr.stat

```

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain :  Zephyr-sdk-0.13.1
 - Commit SHA or Version used: 28b2e55321

**Additional context**
It makes the daily automation failed due to "not enough space".

**Comment by tejlmand** [comment]
Fixed here: #40667

> 28b2e55 cmake: rework linker script generation and linker prebuilt stages
> This single test cases need about 540M disk space to run.

additional context.
The test-case still reqiures 540M diskspace temporarily, and that also required that before 28b2e55.

The difference was that the `gen_handles.py` was moved to an earlier pre-built stage which weren't being cleaned.
This is fixed in #40667 so that all prebuilt stages are cleaned out, and not only the final pre-built stage.
