### ISSUE TITLE
WWDG not supported on STM32H7 family 

### ISSUE THREAD

**Issue by nvincent-vossloh** [zephyrproject-rtos/zephyr#40663]
**Describe the bug**
I tried to use the `wwdg1` peripheral of the `nucleo_h743zi` board as an hardware backend for the `task_wdt` subsys.

During the compilation I have the following error:
```
/home/nicolas/work/siema/be/VOG/src/zephyrproject/zephyr/drivers/watchdog/wdt_wwdg_stm32.c: In function 'wwdg_stm32_setup':
/home/nicolas/work/siema/be/VOG/src/zephyrproject/zephyr/drivers/watchdog/wdt_wwdg_stm32.c:172:36: error: 'LL_DBGMCU_APB1_GRP1_WWDG_STOP' undeclared (first use in this function); did you mean 'LL_DBGMCU_APB3_GRP1_WWDG1_STOP'?
  172 |   LL_DBGMCU_APB1_GRP1_FreezePeriph(LL_DBGMCU_APB1_GRP1_WWDG_STOP);
      |                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                    LL_DBGMCU_APB3_GRP1_WWDG1_STOP
/home/nicolas/work/siema/be/VOG/src/zephyrproject/zephyr/drivers/watchdog/wdt_wwdg_stm32.c:172:36: note: each undeclared identifier is reported only once for each function it appears in
[29/42] Building C object zephyr/kernel/CMakeFiles/kernel.dir/sched.c.obj
ninja: build stopped: subcommand failed.
```

**To Reproduce**
1. I modified the board's dts to enable the `wwdg1` peripheral instead of `iwdg1`:
```
diff --git a/boards/arm/nucleo_h743zi/nucleo_h743zi.dts b/boards/arm/nucleo_h743zi/nucleo_h743zi.dts
index 183ba1a85e..e43f392fb4 100644
--- a/boards/arm/nucleo_h743zi/nucleo_h743zi.dts
+++ b/boards/arm/nucleo_h743zi/nucleo_h743zi.dts
@@ -196,6 +196,6 @@ zephyr_udc0: &usbotg_fs {
        };
 };
 
-&iwdg1 {
+&wwdg1 {
        status = "okay";
 };
```

2. Compilation command:
```
west build -p auto -b nucleo_h743zi -d build/nucleo_h743zi/task_wdt_wwdg zephyr/samples/subsys/task_wdt/
```

**Expected behavior**
No compilation error

**Impact**
Cannot use `wwdg` peripheral as hw backend for `task_wdt` subsys.

**Logs and console output**
N/A

**Environment (please complete the following information):**
 - OS: ubuntu 20.04.3 LTS
 - Toolchain: zephyr-sdk-0.13.1
 - 67a265b0df7c13625b52849595c96ab5b2133487

**Additional context**
Using `iwdg` peripheral works.

**Comment by FRASTM** [comment]
The reason is that for the stm32H7 serie, the control of the WWDG1 stop in debug is present on the BGMCU APB3 peripheral freeze register (DBGMCU_APB3FZ1)  bit 6
