### ISSUE TITLE
Function typedef issue when generating htmldocs.

### ISSUE THREAD

**Issue by m-kru** [zephyrproject-rtos/zephyr#4066]
While generating htmldocs we can see some errors about function typedefs with following messages:
> Invalid definition: Expected identifier in nested name.

Here is more robust example. I have declared following typedef:

    typedef void (*wdt_callback_t)(struct device *dev, void *handle);

When I try to build htmldocs I get some errors with following structure:

>      Invalid definition: Expected identifier in nested name. [error at 4]
>      void(* wdt_callback_t) (struct device *dev, void *handle)
>      ----^
There are also some issues for http_send_data_t:

    int(* http_send_data_t) (struct net_pkt *pkt, net_context_send_cb_t cb, s32_t timeout, void *token,       void *user_data)

>      If declId, parameters, and qualifiers:
>       Invalid definition: Expecting "," or ")" in parameters_and_qualifiers, got "p". [error at 41]
>          int(* http_send_data_t) (struct net_pkt *pkt, net_context_send_cb_t cb, s32_t timeout, void  *token, void *user_data)
 >         -----------------------------------------^

**Comment by dbkinder** [comment]
Alas, there's an open issue with the sphinx/breathe documentation tools (https://github.com/sphinx-doc/sphinx/issues/2683) where unnamed structures, in particular in nested unions / structs, generate this warning.  In our Zephyr documentation world if the unnamed structure can't be avoided, we add an entry to our filter list (.known-issues) to filter out "expected" warnings like this so our CI tools don't flag this as a problem.

**Comment by dbkinder** [comment]
@m-kru Where are you seeing this warning show up? (Which PR?) With PR #1592,  ``make htmldocs`` should filter out "expected" warnings like this.)

**Comment by m-kru** [comment]
I saw it on master.

**Comment by tbursztyka** [comment]
It's a common issue, this willl require a fix in .known-issues/doc/networking.conf

**Comment by dbkinder** [comment]
This is a reported issue with doxygen/breathe that we're unable to fix ourselves.  Workaround is to give unnamed nested structs and unions a name, or to add an exception to the warning message using the .known-issues mechanism we created to hide "expected" errors.

**Comment by dbkinder** [comment]
Workaround provided until (if) Sphinx/Breathe addresses the unnamed nested structs/unions problem.
