### ISSUE TITLE
newlib: assertion failed when printf is called

### ISSUE THREAD

**Issue by atshinbo-etrinity** [zephyrproject-rtos/zephyr#40686]
**Describe the bug**
Assertion failed when newlib/printf is called under a specific combination of configuration items.

**To Reproduce**
1. Modify samples/hello_world/src/main.c as following.
```
#include <zephyr.h>
#include <stdio.h>

void main(void)
{
	printf("Hello World! %s\n", CONFIG_BOARD);	// changed from printk() to printf()
}
```

2. Add following lines to samples/hello_world/prj.conf
```
CONFIG_ASSERT=y
CONFIG_USERSPACE=y
CONFIG_MINIMAL_LIBC=n
CONFIG_NEWLIB_LIBC=y
```

3. west build -b hifive1_revb samples/hello_world
4. cd build/zephyr
5. $ZEPHYR_SDK_INSTALL_DIR/riscv64-zephyr-elf/bin/riscv64-zephyr-elf-objcopy -O ihex zephyr.elf zephyr.hex
6. Write zephyr.hex to the Hifive1 revB board and run.

| Conbinations       | 1  | 2  | 3  |
| ------------------ | -- | -- | -- |
| CONFIG_USERSPACE   | y  | y  | n  |
| CONFIG_MINIMAL_LIBC| n  | y  | n  |
| CONFIG_NEWLIB_LIBC | y  | n  | y  |
| result             | NG | OK | OK |

In this example, printf() is called from kernel thread. 
However, when CONFIG_USERSPACE=y and CONFIG_NEWLIB_LIBC=y, the assertion has been failed.

**Logs and console output**
```
*** Booting Zephyr OS version 2.7.99  ***
ASSERTION FAIL [*lock != ((void *)0)] @ ZEPHYR_BASE/lib/libc/newlib/libc-hooks.c:378
        recursive lock allocation failed

```

**Expected behavior**
```
*** Booting Zephyr OS version 2.7.99  ***
Hello World! hifive1_revb
```

**Environment (please complete the following information):**
- OS: Ubuntu 18.04.5 LTS
- Toolchain: zephyr-sdk-0.13.1
- Version: v2.7.99
- Commit: 1238410914597aef1e0661e0b2e240a448f2dd60
- Target: hifive1_revb

**Comment by stephanosio** [comment]
When userspace is enabled, you need to ensure the following:

1. Kernel dynamic object allocation is enabled.
2. The executing thread is assigned a resource memory pool (heap).

You can ensure (1) by setting `CONFIG_DYNAMIC_OBJECTS=y`.
You can ensure (2) by either:

a. Defining a dedicated heap and assigning it to the executing thread (refer to the `k_thread_heap_assign` documentation).
b. Enabling the default system heap and assigning it to the executing thread (set `CONFIG_HEAP_MEM_POOL_SIZE` to a desired value and call `k_thread_system_pool_assign`).

For more details, refer to the relevant documentation:
https://docs.zephyrproject.org/latest/reference/usermode/kernelobjects.html#dynamic-objects
https://docs.zephyrproject.org/latest/reference/kernel/memory/heap.html
https://docs.zephyrproject.org/latest/reference/usermode/memory_domain.html?highlight=k_thread_system_pool_assign#thread-resource-pools
