### ISSUE TITLE
Question devicetree overlay file gpios nrf52840dongle_nrf52840

### ISSUE THREAD

**Issue by hakkimakki** [zephyrproject-rtos/zephyr#40691]
I would like to specify a device that uses one ADC and Two GPIOs with a devicetree-overlay file (app.overlay):

<pre><code>/ {
	zephyr,user,spec {
		clk-gpios = <&gpio0 15 GPIO_ACTIVE_LOW>; /* 0.15 */
		st-gpios = <&gpio1 0 GPIO_ACTIVE_LOW>; /* 1.00 */
		io-channels = <&adc 7>;
	};
};
</code></pre>

To get the device binding of the clk-gpio i would like to use the following code:
<pre><code>#define ZEPHYR_USER_SPEC DT_PATH(zephyr_user_spec)
const struct gpio_dt_spec spec_clk = GPIO_DT_SPEC_GET(ZEPHYR_USER_SPEC,clk_gpios);
</code></pre>

But the compiler is failing with the following error:
<pre><code>C:\Users\raffa\Github\ncs\zephyr\include\device.h:80:39: error: '__device_dts_ord_DT_N_S_zephyr_user_spec_P_clk_gpios_IDX_0_PH_ORD' undeclared here (not in a function)</code></pre>

and 

<pre><code>C:\Users\raffa\Github\ncs\zephyr\include\devicetree.h:81:17: error: 'DT_N_S_zephyr_user_spec_P_clk_gpios_IDX_0_VAL_pin' undeclared here (not in a function)</code></pre>

**To Reproduce**
In your app dir:
1. crate the file app.overlay with the content above
2. add the code lines above to src/main.c
3. west build

**Expected behavior**
The overlayfile gets accepted by the compiler as shown in the logs. Therefore the Device should be declared.

**Environment (please complete the following information):**
 - OS: Windows 10
<pre><code>-- Zephyr version: 2.6.99 (C:/Users/raffa/Github/ncs/zephyr), build: v2.6.99-ncs1-1
-- Found Python3: C:/Python37/python.exe (found suitable exact version "3.7.7") found components: Interpreter 
-- Found west (found suitable version "0.11.1", minimum required is "0.7.1")
-- Board: nrf52840dongle_nrf52840
-- Cache files will be written to: C:/Users/raffa/Github/ncs/zephyr/.cache
-- Found dtc: C:/ProgramData/chocolatey/bin/dtc.exe (found suitable version "1.5.0", minimum required is "1.4.6")
-- Found toolchain: gnuarmemb (c:/gnuarmemb/opt)
-- Found BOARD.dts: C:/Users/raffa/Github/ncs/zephyr/boards/arm/nrf52840dongle_nrf52840/nrf52840dongle_nrf52840.dts
-- Found devicetree overlay: c:/Users/raffa/Github/hamamatsu_spec_c12880ma/app.overlay
-- Generated zephyr.dts: C:/Users/raffa/Github/hamamatsu_spec_c12880ma/build/zephyr/zephyr.dts
-- Generated devicetree_unfixed.h: C:/Users/raffa/Github/hamamatsu_spec_c12880ma/build/zephyr/include/generated/devicetree_unfixed.h
-- Generated device_extern.h: C:/Users/raffa/Github/hamamatsu_spec_c12880ma/build/zephyr/include/generated/device_extern.h
-- Including generated dts.cmake file: C:/Users/raffa/Github/hamamatsu_spec_c12880ma/build/zephyr/dts.cmake
</code></pre>

**Comment by mbolivar-nordic** [comment]
> zephyr,user,spec {

There is a typo here. It should be `zephyr,user`. See https://docs.zephyrproject.org/latest/guides/dts/bindings.html#inferred-bindings for examples.
