### ISSUE TITLE
Should it be I2C_MSG_READ, shouldn't? I didn't understand

### ISSUE THREAD

**Issue by mrr00b00t** [zephyrproject-rtos/zephyr#40715]
The line on this code contains the flag I2C_MSG_WRITE, but in my mind it should be I2C_MSG_READ, right?

https://github.com/zephyrproject-rtos/zephyr/blob/a1c49be42e371a865865d52d0ea5ef83b2a3a9db/samples/drivers/i2c_fujitsu_fram/src/main.c#L61

**Comment by DariusBabrauskas** [comment]
Yes of course. Read I2c protocol, please.
B.R.

**Comment by cfriedt** [comment]
Looks OK as-is. Often i2c devices need a write before a read.
