### ISSUE TITLE
Bluetooth: host: CCC values are not immediately stored on GATT Server by default (risk of inconsistency)

### ISSUE THREAD

**Issue by MarekPieta** [zephyrproject-rtos/zephyr#40758]
**Describe the bug**
CCC values are not immediately stored on GATT Server. That could lead to inconsistency of CCC values for GATT Client and GATT Server. The inconsistency could lead to e.g. GATT Client waiting for some notifications/indications and never receiving them.

**To Reproduce**
Use a sample that has a GATT Server, supports bonding and Bluetooth settings.

**Expected behavior**
CCC values should be stored quickly by default. A developer could disable CONFIG_BT_SETTINGS_CCC_STORE_ON_WRITE  explicitly to save some memory if needed. In that case developer would be aware of potential issues that are related to the selected configuration.

We could also consider removing or shortening  the CCC_STORE_DELAY if possible or delaying sending response to CCC write with response until the data is properly stored in FLASH.

**Impact**
For my use case, the problem affected Service Changed characteristic. In that case GATT Client may not receive the indication which leads to inconsistent cached data related to GATT discovery (the GATT Client would not be aware that GATT Server dropped the subscription, so it would not re-subscribe).

**Comment by alwa-nordic** [comment]
I agree that immediate write should be the default. The spec requires the GATT server to remember the CCC value. A positive write response for a CCC write must mean that the server has committed the value to persistent storage when bonded. The bonded client is allowed to assume this. It is unsafe to not to do so. So I think the application developer should make a non-default choice to enable unsafe behavior.
