### ISSUE TITLE
remove _current NULL check in ARM's _is_thread_user()

### ISSUE THREAD

**Issue by andrewboie** [zephyrproject-rtos/zephyr#4082]
See #4080 .  the call to k_object_access_grant() in setup_new_thread() makes this necessary. revise the code so we don't need the extra NULL check in this very hot code path.

**Comment by nashif** [comment]
@andrewboie is this still valid?  we do not have k_object_grant_access anymore :)

**Comment by andrewboie** [comment]
@nashif it is, the API is called k_object_access_grant()

**Comment by andrewboie** [comment]
Not a problem any more.
