### ISSUE TITLE
Add a pre and post initialization among CONFIG_APPLICATION_INIT_PRIORITY

### ISSUE THREAD

**Issue by ck-telecom** [zephyrproject-rtos/zephyr#40868]
**Is your enhancement proposal related to a problem? Please describe.**
when application module initialized, some modules depend on the CONFIG_APPLICATION_INIT_PRIORITY finished(eg add custom lvgl input, when using CONFIG_APPLICATION_INIT_PRIORITY, can not make sure the initial sequence is correct and result failure)

**Describe the solution you'd like**
add a post application and pre applicaion PRIORITY

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by henrikbrixandersen** [comment]
You can use `POST_KERNEL` as "pre-application".
