### ISSUE TITLE
STM32 ADC gets stuck in Calibration

### ISSUE THREAD

**Issue by pdietl** [zephyrproject-rtos/zephyr#40936]
**Describe the bug**
Here https://github.com/zephyrproject-rtos/zephyr/blob/main/drivers/adc/adc_stm32.c#L595 we try to calibrate the ADC, but at least on STM32G4, the ADC is not permitted to be calibrated unless the ADC is disabled. 

![image](https://user-images.githubusercontent.com/10335942/144902964-ce488501-0217-483c-bedd-c45871735f6e.png)

I discovered this bug while trying to use the sensor here: https://github.com/zephyrproject-rtos/zephyr/blob/main/drivers/sensor/stm32_temp/stm32_temp.c#L116 which requests calibration. I saw the thread in question get stuck here: https://github.com/zephyrproject-rtos/zephyr/blob/main/drivers/adc/adc_stm32.c#L337

I need help confirming this ADC disabled requirement on other STM32 models.

**Comment by FRASTM** [comment]
that's right, ADC calibration requires ADC disable (ADCEN =0) except for **stm32F1** mcus 
_"Before starting a calibration, the ADC must have been in power-on state (ADON bit = ‘1’) for
at least two ADC clock cycles."_
and stm32L1x (no cal.)

**Comment by pdietl** [comment]
I think I may have split our conversation between the PR and issue :p
