### ISSUE TITLE
SPI performance with zephyr and the nRF52832 is currently relatively slow

### ISSUE THREAD

**Issue by dwalton65** [zephyrproject-rtos/zephyr#40943]
A 5 byte SPI transfer is taking about 17us when using the nordic spim drivers and about 56us when using the zephyr spim drivers.
This is with clock freq = 8M and using DMA.

Would this be considered normal when using the Zephyr drivers as apposed to calling the Nordic drivers?

More information can be seen [here](https://devzone.nordicsemi.com/f/nordic-q-a/81966/slow-spi-performance-with-zephyr).

SPI timing with the nordic drivers
![nrfx_spim1](https://user-images.githubusercontent.com/92129795/144965149-0e1c2074-819c-4f10-bac4-f360b5f58abc.png)

SPI timing with the zephyr drivers
![zephyr_spim](https://user-images.githubusercontent.com/92129795/144965180-7034c395-7456-49b2-89c1-2345e9c6e972.png)

**Comment by anangl** [comment]
@dwalton65 Please take a look at https://github.com/zephyrproject-rtos/zephyr/issues/33583#issuecomment-826854527.

**Comment by carlescufi** [comment]
Closing since this is responded.
