### ISSUE TITLE
Build system: West: Add a warning when used repository does not match manifest

### ISSUE THREAD

**Issue by rakons** [zephyrproject-rtos/zephyr#40982]
**Is your feature request related to a problem? Please describe.**
I often forget to run west update before building. Sometimes it takes time to understand that reported build system errors are related to wrong repositories used.

**Describe the solution you'd like**
Add a warning at the very beginning that used repository does not match the manifest. It should be only a warning and should allow build continuation.

**Describe alternatives you've considered**
I do not see a real alternatives. We should not force the user to use the right repositories as it would make testing solutions before pushing it into a branch much harder.

**Comment by henrikbrixandersen** [comment]
CC: @mbolivar-nordic

**Comment by mbolivar-nordic** [comment]
Dupe of https://github.com/zephyrproject-rtos/zephyr/issues/23025
