### ISSUE TITLE

tests-ci : portability: posix: fs.tls.newlib test Build failure


### ISSUE THREAD

**Issue by hakehuang** [zephyrproject-rtos/zephyr#41052]
**Describe the bug**
fs.tls.newlib test is Build failure on v2.7.99-2147-g183328a4fbdb on mimxrt685_evk_cm33

see logs for details

**To Reproduce**
1. 
```
scripts/twister --device-testing --device-serial /dev/ttyACM0 -p mimxrt685_evk_cm33  --sub-test portability.posix
```
2. See error

**Expected behavior**
test pass

**Impact**

**Logs and console output**
```
/home/ubuntu/zephyr_project/zephyr_rt685/zephyr/drivers/disk/usdhc.c: In function 'usdhc_dat3_pull':
/home/ubuntu/zephyr_project/zephyr_rt685/zephyr/drivers/disk/usdhc.c:2618:2: error: implicit declaration of function 'imxrt_usdhc_dat3_pull'; did you mean 'usdhc_dat3_pull'? [-Werror=implicit-function-declaration]
 2618 |  imxrt_usdhc_dat3_pull(pullup);
      |  ^~~~~~~~~~~~~~~~~~~~~
      |  usdhc_dat3_pull
cc1: all warnings being treated as errors
    
```

**Environment (please complete the following information):**
 - OS: (e.g. Linux )
 - Toolchain (e.g Zephyr SDK)
 - Commit SHA or Version used: v2.7.99-2147-g183328a4fbdb

**Comment by hakehuang** [comment]
dup with zephyr#41052

**Comment by dleach02** [comment]
@hakehuang, does this error still occur? 

If so, can you provide a more focused target to reproduce this error? I run the twister command you specified and it ends up trying to build 543 test cases. After 257 of them built without error I stopped it because I'm running out of disk space.

**Comment by hakehuang** [comment]
@dleach02  in latest build this is ok.
