### ISSUE TITLE
console: gsm_mux: could not send more than 128 bytes of data on dlci

### ISSUE THREAD

**Issue by kurddt** [zephyrproject-rtos/zephyr#41077]
**Describe the bug**
When sending more than 128 bytes of data through a muxed uart the header is not correctly formatted. This seems to be due to a wrong encoded length indicator in the frame header

**Expected behavior**
The header should be correct when sending more than 128 bytes

**Impact**
It's possible to work-around this bug by splitting the data to send in smaller chunck

**Additional context**
This was experienced with while communicating with a ublox sara-r4 module. Probably the bug was hidden until #39776 was merged

**Comment by kurddt** [comment]
@jukkar Since you seems to be the original author of the gsm muxing implementation I was wondering if you were able to test this use case (sending of more than 127 bytes)?
Since the 3GPP specification is not really explicit on which one of the length indicator byte is the MSB it could be a bug on the module side

**Comment by jukkar** [comment]
> I was wondering if you were able to test this use case (sending of more than 127 bytes)?

I do not remember testing this. There are no unit tests for the muxing driver so all the testing is "manual" (at least now), there are probably bugs in the code because of this. Thanks for the PR, it looks good.
