### ISSUE TITLE
[backport v2.7-branch] backport of #40862 (power modes for STM32H7)

### ISSUE THREAD

**Issue by belolap** [zephyrproject-rtos/zephyr#41089]
Some boards on STM32H7 uses SMPS with different power supply configurations. So Zephyr 2.7 can't start without property power supply and clock init sequence. PR #40862 add support for all possible power supply configurations.

I suggest to backport #40862 to zephyr 2.7, so more boards can start.

**Comment by erwango** [comment]
@belolap Indeed, backporting this one is justified.

**Comment by belolap** [comment]
Ok, I'll make PR tomorrow.

**Comment by belolap** [comment]
I'm close it because pr was merged.
