### ISSUE TITLE
Allow customize timestamp format

### ISSUE THREAD

**Issue by manoj153** [zephyrproject-rtos/zephyr#41146]
It would be nice if zephyr allowed registering a user-provided function to format the output string of the timestamp. 

Perhaps introduce a new kconfig symbol as an alternate to `CONFIG_LOG_BACKEND_FORMAT_TIMESTAMP`?
Will `CONFIG_LOG_BACKEND_FORMAT_TIMESTAMP_CUSTOM` sounds good?

**Comment by carlescufi** [comment]
@manoj153 sure, would you mind sending a Pull Request with a proposal?

**Comment by heinwessels** [comment]
Here is an PR that implements custom timestamp formatting https://github.com/zephyrproject-rtos/zephyr/pull/56277
