### ISSUE TITLE
LE Audio: Unify the unicast client and server API

### ISSUE THREAD

**Issue by Thalley** [zephyrproject-rtos/zephyr#41195]
As a developer I want to use the same API for audio streams for both server (local) and client (remote) streams.

 Some functionality can only be done as client, and some only as the server, depending on whether the stream in sink or source. Refer to the BAP and ASCS specs.

Currently to some degree unified.

2021-11-02: Postponed until F2F

**Comment by asbjornsabo** [comment]
No longer relevant.
Emil will create new issue for common API for streams.
