### ISSUE TITLE
LE Audio: Media API with one call per command, rather than sending opcodes

### ISSUE THREAD

**Issue by Thalley** [zephyrproject-rtos/zephyr#41199]
(This is something we may, or may not, want to do. Issue created for record-keeping and future consideration.)

Change the MCC and media_proxy APIs to have one function call per possible command, rather than one function call sending command opcodes.

E.g.: bt_mcs_play()
bt_mcs_pause()

rather than

bt_mcs_send(BT_MCS_OPC_PLAY)
bt_mcs_send(BT_MCS_OPC_PAUSE)

This would add 21 function calls to the API (for each of MCC and media_proxy, possibly also for media_proxy_internal). It would remove one call (times 2 or 3).
The callbacks could probably be common - if so, no change there.

Emil:
"The downside, besides the large API file, is that it may require additional code size as well, and other complexitiesI haven't considered, but to me the API will be easier to read and understand, and if we want to not support certain opcodes, such as rewind/forward (if possible), then using bt_mcs_fast_rewind() would give a compile-time error, rather than runtime. Furthermore, it will be easier to describe what happens for each of the opcodes as those will be "normal" function descriptions, whereas with the opcode approach, we'd have to put the description of the action for the #defines instead.

But it's fully up to you, and I do get why the specific command approach is somewhat overwheming due to the many opcodes. "

**Comment by asbjornsabo** [comment]
Will not be done - close
