### ISSUE TITLE
LE Audio: BASS use multi-characteristic macro for receive states

### ISSUE THREAD

**Issue by Thalley** [zephyrproject-rtos/zephyr#41208]
As a developer I want to use the macro from https://github.com/zephyrproject-rtos/zephyr/issues/41207 to define multiple instances of the receive state characteristic.
 

As a user I want to be able to set a variable number of receive state characteristics for the BASS using Kconfig.

**Comment by asbjornsabo** [comment]
Zephyr-bt F2F: Covered by other issues - closing
