### ISSUE TITLE
LE Audio: Cleanup handling of objects and included OTS

### ISSUE THREAD

**Issue by Thalley** [zephyrproject-rtos/zephyr#41202]
Expected things to do

- ensure local controller using media_proxy can access media player objects directly, not via MCS
- => probable solution: Add direct object interface to MPL
- update handling of included services to follow pattern from VCS (can possibly be factored out as separate story)
- handling of objects in media_proxy
  - API, functions and callbacks - ~8 or so APIs
- update media_controller shell commands
  - ~8 commands, some are very similar, these relate to APIs

2022-03-23: Also: Guard object-related callbacks in media_proxy.h so that they are excluded from the struct if objects are not used.

**Comment by kruithofa** [comment]
Issue becomes obsolete after refactoring is done
