### ISSUE TITLE
OTS: Debug metadata output

### ISSUE THREAD

**Issue by Thalley** [zephyrproject-rtos/zephyr#41205]
Introduce in the upstream OTS functionality similar to the bt_ots_dump_metadata() from downstream.
Also consider bt_ots_dump_directory_listing() if it does not exist

 

2021.04.21:
- is this a debug dump function or to-string function?
- in favour of to-string so that the dump is represented as information that can be logged or used via shell subsystem
  - We want object id, name, current size, allocated size and others

**Comment by asbjornsabo** [comment]
Zephyr-bt F2F: We have managed without for  a long time -  closing
