### ISSUE TITLE
LE Audio: Store of bonded data

### ISSUE THREAD

**Issue by Thalley** [zephyrproject-rtos/zephyr#41212]
(Converted from a VCS issue to a general issue)

 We store a lot of data on the client, but do not have a means of restoring these data on reboot.
Similarly, some data is stored on the server side.

Update clients/servers to be able to export the client data to the application, so that it can be saved in flash and restored. 

What about e.g. volume settings - must they be restored after reboot?

Q: Is it possible to store info that this reboot was caused by firmware update?
May want to delete some stored information - start from a clean slate, with values from the firmware update.
Zephyr has a reboot function that takes a type as an input.

**Comment by Thalley** [comment]
Alternative to offloading this to the application, the stack could use the BT_SETTINGS to store the information itself.

**Comment by asbjornsabo** [comment]
Zephyr-bt host meeting 2022-01-18:
Emil: We store a lot of data on the client, but do not have a means of restoring these data on reboot.
Need to start looking at method to store (permanently) these data. => May end up as a general issue.

**Comment by Thalley** [comment]
We should ues the bt_settings to store the data automatically from the stack.
