### ISSUE TITLE
LE Audio: TBS/CCP long read

### ISSUE THREAD

**Issue by Thalley** [zephyrproject-rtos/zephyr#41218]
Need to properly handle long notifications from TBS in the Call Control client. 

The easy way is to simply do a read if the value matches the MTU, but is slightly troublesome as the CC client does not now whether notify multiple, or notify (1 octet difference in header len) was used, and can thus not properly determine if the lenght is the MTU size. 

Request to add a field to the long values for the clients to easily know if they have been truncated has been sent to the GA group, and awaiting response. The implemenation for this may depend on the response.

**Comment by kruithofa** [comment]
Related to #68173

**Comment by Thalley** [comment]
Closing in favor of https://github.com/zephyrproject-rtos/zephyr/issues/68173
