### ISSUE TITLE
LE Audio: Add public API to CCP/TBS

### ISSUE THREAD

**Issue by Thalley** [zephyrproject-rtos/zephyr#41214]
Add a public API for the Call Control client and the Telephone Bearer Service. 

Todo:
- Guesstimate, >20 functions?!! already in tbs header + some callbacks
  - Functions do exists, this is to make a common public interface for local and remote
- Add tests in a different PR, as an exception to have smaller story point stories, create new story Gydesen, Emil create the new story.

**Comment by asbjornsabo** [comment]
Zephyr-bt F2F: Duplicated by newer API renaming issue - closing
