### ISSUE TITLE
LE Audio: Automated tests for TBS/CCP

### ISSUE THREAD

**Issue by Thalley** [zephyrproject-rtos/zephyr#41210]
As a developer I want have automated tests to validate any changes done to the TBS server or client. 
As a developer I want all API calls to be tested on the server and on the client. 

2021-11-16
- Expect these tests to be BabbleSim tests
- Have some limited tests - around 25 percent of the functionality tested

**Comment by szymon-czapracki** [comment]
https://github.com/zephyrproject-rtos/zephyr/pull/55332

**Comment by Thalley** [comment]
> #55332

Have a look at https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue :)
