### ISSUE TITLE
LE Audio: Support for a minimum CCP client

### ISSUE THREAD

**Issue by Thalley** [zephyrproject-rtos/zephyr#41217]
The CCP client implementation right now is a fully-featured implementation, with support for everything, including multiple instances of TBS. 

The minimum CCP client should only subscribe to e.g. Call State list (or perhaps the Current Calls list) and the control point, and then either only use GTBS, or in the case of a single TBS instance, just one TBS instance. 

The Simple client should be enabled by a KConfig option, which may or may not set some other Kconfig options.

**Comment by asbjornsabo** [comment]
Zephyr-bt F2F: Already done in related PR - closing
