### ISSUE TITLE
LE Audio: Unify list handling for groups, tracks and segments

### ISSUE THREAD

**Issue by Thalley** [zephyrproject-rtos/zephyr#41219]
I want the list handling for groups, tracks and track segments unified, using the same functions, so that I can avoid the triplicate set of functions that is there now and save some code and memory.

As part of this, I may want to use the zephyr-bt doubly linked list, instead of the list functions I have built myself, to gain reuse and save code/memory.

2020.12.02:
- currently baremetal list implementation
- use kernel sys functions?
- Not sure any better gain in re-implementing

Keep it open for sometime

**Comment by asbjornsabo** [comment]
This is an optimization for a code module that is a dummy/sample, and which we expect the users to replace with something else.
=> Not important to do.
