### ISSUE TITLE
STM32H7: Check for VOSRDY instead of ACTVOSRDY

### ISSUE THREAD

**Issue by benediktibk** [zephyrproject-rtos/zephyr#41220]
**Describe the bug**
In soc_m7.c:91the system is waiting for VOSRDY to become ready. According to the reference manual of a STM32H735 this bit should already be ready anyway at this point, but instead one should wait for ACTVOSRDY to become ready.

For working on a different issue I already changed this locally, and honestly it made no difference. At least in my case. I just stumbled upon this by accident and I think the currently implemented behaviour is incorrect.

**To Reproduce**
1. Run an example on STM32H735 Discovery Kit

**Expected behavior**
Waiting for ACTVOSRDY to be ready instead of VOSRDY.

**Impact**
None so far.

**Logs and console output**

**Environment (please complete the following information):**
Zephyr Version 38c42f69d28b8ce7cefb2b1a265400e83dd654aa

**Additional context**

**Comment by benediktibk** [comment]
Just checked the reference manuals for the (as far as I know) all by zephyr supported H7 variants:

- H723
- H735
- H743
- H745
- H747
- H750
- H753

This behaviour should be the same for all of them, hence no differentiation based on the chip will be necessary.

**Comment by FRASTM** [comment]
In the stm32h7_init(), as the LDO  (is switched on for M7 run Mode, it seems correct to monitor the VOSRDY bit of the PWR_D3CR register for the Domain3 : that's the LL_PWR_IsActiveFlag_VOS()
My understanding is that The ACTVOSRDY bit of the PWR_CSR1 register should be used to monitor the SVOS level as set by the PWR_CR1 register --> VOS in STOP mode.

**Comment by benediktibk** [comment]
![startup_sequence](https://user-images.githubusercontent.com/9367089/146333533-16ebae70-522a-4260-94d4-0fd27394561d.png)
![startup_sequence_text](https://user-images.githubusercontent.com/9367089/146333928-50ee77aa-3f36-4009-9443-5a43c0bad922.png)

Looking at the reference manual I come to a different conclusion. VOSRDY will happen way earlier, before the actual code is executed after step 4 of the startup sequence. The application running on the chip should then check for ACTVOSRDY before the VOS levels can be changed.

**Comment by benediktibk** [comment]
Just stumbled upon this: https://github.com/zephyrproject-rtos/hal_stm32/blob/34fe6f7332925417b5c7fbd1eed2414b2741c2e4/stm32cube/stm32h7xx/drivers/src/stm32h7xx_hal_pwr_ex.c#L350

Looks like HAL is also checking ACTVOSRDY.

**Comment by benediktibk** [comment]
I addressed the issue in #41439

**Comment by FRASTM** [comment]
now addressed by https://github.com/zephyrproject-rtos/zephyr/pull/41871
