### ISSUE TITLE
[v2.7] drivers: ieee802154_dw1000: use dedicated workqueue

### ISSUE THREAD

**Issue by cfriedt** [zephyrproject-rtos/zephyr#41237]
**Describe the bug**

Driver has dedicated workqueue for IRQ processing.
Submit work to dedicated workqueue intead of system workqueue.
It also fixes driver functionality when NET_TC_TX_COUNT is set to 0.

Bug description:
With NET_TC_TX_COUNT set to 0, and IRQ processing submitted to system workqueue can lead to a situation where lock mutex in `subsys/net/ip/net_if.c`, executed in workqueue context, is locked and IRQ processing in driver is blocked.
Driver already has its own workqueue, it just was not used.

**Comment by cfriedt** [comment]
@jfischer-no - can you please fill in the details above?

**Comment by jfischer-no** [comment]
Added more details to bug description.
