### ISSUE TITLE
pthread_cond_wait return value incorrect

### ISSUE THREAD

**Issue by povergoing** [zephyrproject-rtos/zephyr#41284]
**Describe the bug**
The `pthread_cond_wait` always returns `ETIMEDOUT`

I try to use `pthread_cond_wait` and find that its return value is always `ETIMEDOUT`, even the thread is wakened normally.

**To Reproduce**
https://github.com/zephyrproject-rtos/zephyr/blob/c3715da5d95c10527e65624d47954987037f50c5/tests/posix/common/src/pthread.c#L100

we can easily check the return value here.
And I think this test case also needs to check the return value.

I guess we should reset the thread's ret_val in `pthread_cond_signal `and `pthread_cond_broadcast`, just like the `pthread_mutex` doing. 
https://github.com/zephyrproject-rtos/zephyr/blob/c3715da5d95c10527e65624d47954987037f50c5/lib/posix/pthread_mutex.c#L148

**Expected behavior**
The thread calling `pthread_cond_wait` should return 0 (its wait time is K_FOREVER, so it should not return `ETIMEDOUT`.

**Impact**
We will fail to port some code because of the incorrect return value.

**Comment by cfriedt** [comment]
@povergoing - thanks for providing all of the detail and the RC.
