### ISSUE TITLE
QSPI flash need read, write via 4 lines not 1 line 

### ISSUE THREAD

**Issue by glin00** [zephyrproject-rtos/zephyr#41297]
**Describe the bug**
The project I am working need to use QSPI flash to store some image data(ex. 5MB size of data).  QSPI flash read, write data is working without any problems, but I found that the flash_stm32_qspi_write routine uses QSPI_INSTRUCTION_1_LINE, QSPI_ADDRESS_1_LINE, QSPI_DATA_1_LINE to write data.  Is it possible that I can use   QSPI_DATA_4_LINES to increase the speed of write? The same is for flash_stm32_qspi_read which uses QSPI_INSTRUCTION_1_LINE, QSPI_ADDRESS_1_LINE, QSPI_DATA_1_LINE to read data.   Is it possible that I can use   QSPI_DATA_4_LINES to increase the speed of read?

the prj.conf concerning qspi i/f is as following:
#SPI related 
CONFIG_SPI=y
CONFIG_SPI_STM32_DMA=y
CONFIG_DMA=y
CONFIG_GPIO=y
CONFIG_GPIO_STM32=y

#flash related
CONFIG_FLASH=y

the dts is as following:

&quadspi {
	pinctrl-0 = <&quadspi_clk_pa3 &quadspi_bk1_ncs_pb11
		     &quadspi_bk1_io0_pb1 &quadspi_bk1_io1_pb0
		     &quadspi_bk1_io2_pa7 &quadspi_bk1_io3_pa6>;
	dmas = < &dma2 7 3 0x0000  >;
	dma-names = "tx_rx";

	status = "okay";

	mt25qu128abaf: qspi-nor-flash@0 {
		compatible = "st,stm32-qspi-nor";
		label = "MT25QU128ABA";
		reg = <0>;
		qspi-max-frequency = <50000000>;
		/* 128 Megabits = 16 Megabytes */
		size = <0x8000000>;
		status = "okay";
	};

};

As you can see, I already use SPI DMA and spi clock 40mhz. The next thing to consider to increase access speed is to change 1 line to 4 lines of  QSPI i/f.

**Expected behavior**
QSPI flash read, write using 4 lines data should be possible. 

**Impact**
Wish to use QSPI flash read, write using 4 lines data to increase access speed since the data stored in the flash is quite large(at least 5MB). 

**Environment (please complete the following information):**
Hardware:STM32L496AGI6P
Display: OLED display with 4 wire SPI interface.
Linux Ubuntu 20.04.3 LTS
Zephyr SDK,-0.13.0
Zephyr SHA1 ID:bb85a55

**Comment by erwango** [comment]
No issue description. Closing

**Comment by glin00** [comment]
@erwango , please open up this issue since I had filled up all the information I know. If there is any information not enough, please let me know. Thanks.

**Comment by erwango** [comment]
@glin00 Can you have a look to https://github.com/zephyrproject-rtos/zephyr/pull/40859, to see if filling the gap ?

**Comment by erwango** [comment]
Also, @glin00 please make the effort to distinguish 'bug' from 'enhacement'.

**Comment by lmajewski** [comment]
@glin00 The PR #40859 mentioned by @erwango shall fulfill this enhancement request.

**Comment by glin00** [comment]
@lmajewski . would you mind to tell me the SHA1 ID of zephyr you are using to test #40859?
I am using SHA1 ID b48276e9954a11ccf1ebeb93c635f5f16fe8fdb2 and I copy paste the files you changed in #40859 and there are some compiling errors which I am trying to solve now.
But I think the quickest way is to know which SHA1 ID of zephyr you are using, so I can spend less time to solve this problem.

**Comment by lmajewski** [comment]
@glin00 

Compiler: Found host-tools: zephyr 0.13.1
Branch: upstream/main
SHA1: 9e4968bb901c8dddde661b8f2d0a0046b338a8ab
Compilation: west build -p always -b nucleo_h743zi ./zephyr/samples/subsys/fs/littlefs
Flashing: west flash

**Comment by lmajewski** [comment]
IIRC there was a pinctrl rework:

`tig b48276e9954a11ccf1ebeb93c635f5f16fe8fdb2..9e4968bb901c8dddde661b8f2d0a0046b338a8ab`

Please look into: SHA1: 37bf7cbe4f3bd7239b6675e9f9b3e7746fde193f

**Comment by erwango** [comment]
Fixed in https://github.com/zephyrproject-rtos/zephyr/pull/40859,.
Please open a new issue if required
