### ISSUE TITLE
LVGL touch event "LV_EVENT_LONG_PRESSED" can not be generated if I press the screen without lift up my finger

### ISSUE THREAD

**Issue by glin00** [zephyrproject-rtos/zephyr#41291]
**Describe the bug**
I am using lvgl as GUI library with zephyr.  The display which is an OLED display can be displayed ok using lvgl.  The OLED display touch function is working since I touch the display, the correct display x,y can be reported.  If I press the screen and lift up my finger, "LV_EVENT_CLICKED" can be generated within lvgl. But if I press the screen without lift up my finger ,"LV_EVENT_LONG_PRESSED" can not be generated.    

When I trace the code using west debug, I found that indev_proc_press can be entered but line 978 which will generate  LV_EVENT_LONG_PRESSED can not be entered(see attached). 

Can any one help me how to solve this problem?

**To Reproduce**
The following is the part of prj.conf related to lvgl.
#LVGL 
CONFIG_MAIN_STACK_SIZE=16384
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=4096
CONFIG_HEAP_MEM_POOL_SIZE=16384
CONFIG_LVGL_MEM_POOL_HEAP_KERNEL=y

CONFIG_LVGL=y
CONFIG_LVGL_HOR_RES_MAX=300 
CONFIG_LVGL_VER_RES_MAX=340
CONFIG_LVGL_VDB_SIZE=100
CONFIG_LVGL_BITS_PER_PIXEL=16
CONFIG_LVGL_DPI=130

#LVGL color
CONFIG_LVGL_COLOR_DEPTH_16=y

#LVGL display
CONFIG_DISPLAY=y
CONFIG_LVGL_DISPLAY_DEV_NAME="SmallOLED"
CONFIG_LVGL_DISP_DEF_REFR_PERIOD=30

#LVGL INDEV
CONFIG_LVGL_POINTER_KSCAN=y
CONFIG_LVGL_POINTER_KSCAN_DEV_NAME="OLEDTouch"
CONFIG_LVGL_INDEV_DEF_READ_PERIOD=50
CONFIG_LVGL_INDEV_DEF_DRAG_LIMIT=10
CONFIG_LVGL_INDEV_DEF_DRAG_THROW=20
CONFIG_LVGL_INDEV_DEF_LONG_PRESS_TIME=400
CONFIG_LVGL_INDEV_DEF_LONG_PRESS_REP_TIME=100

#LVGL buffer
CONFIG_LVGL_BUFFER_ALLOC_STATIC=y

#LVGL USE options
CONFIG_LVGL_USE_BTN=y
CONFIG_LVGL_USE_CONT=y
CONFIG_LVGL_USE_LABEL=y

**Impact**
This project I am doing now requires lvgl to generate "LV_EVENT_LONG_PRESSED" when user touches the screen's button long enough without lift up finger. 

**Environment (please complete the following information):**
Hardware:STM32L496AGI6P
Display: OLED display with 4 wire SPI interface.
Linux Ubuntu 20.04.3 LTS
Zephyr SDK,-0.13.0
Zephyr SHA1 ID:bb85a55
LVGL:7.6.1

**Additional context**
Add any other context that could be relevant to your issue, such as pin setting,
target configuration, ...
![oled](https://user-images.githubusercontent.com/20088622/146522187-1105ec83-15dc-491c-b5f6-3a0939a04314.png)

**Comment by glin00** [comment]
After I trace code, I found that ,within indev_proc_press function (line 975), proc->pr_timestamp (press screen time stamp) always equal to sys_time.  This causes lv_tick_elaps return a value not greater than indev_act->driver.long_press_time. 
 As a result, LV_SIGNAL_LONG_PRESS can not be triggered. 
Can any one help why  proc->pr_timestamp is always equal to sys_time?

**Comment by carlescufi** [comment]
@gmarull or @brgl any ideas?

**Comment by gmarull** [comment]
`proc.pr_timestamp` seems to be updated in some places using `lv_tick_get()`, which is a shim for `k_uptime_get_32()`, so the problem may come from input events generated by the corresponding kscan driver. Check lvgl_pointer_kscan_read and related functions.

**Comment by dkalowsk** [comment]
@kisvegabor any input?

**Comment by kisvegabor** [comment]
I've answered in the same in issue in https://github.com/lvgl/lvgl/issues/2923 but didn't get answer :slightly_frowning_face:
