### ISSUE TITLE
nordic nrf52/nrf53 and missing cpu-power-states (dts) for automatic device PM control

### ISSUE THREAD

**Issue by invoxiaamo** [zephyrproject-rtos/zephyr#41382]
Hi all.

I'm playing with nrf52 and nrf53 DK board in order to evaluate the power consumption.
- There is some general documentation (https://devzone.nordicsemi.com/nordic/nordic-blog/b/blog/posts/optimizing-power-on-nrf53-designs) to explain what to do.
- one specific example (zephyr/samples/boards/nrf/system_off) that show that UART (and any active device) must be suspend manually if we expect a proper low consumption

Well...
first, I would expect a complete ble example that achieve THIS low consumption (few uA) without hacking the prj.conf (to disable UART mainly) or hacking main.c (to do the same manually UART disabling), so we can all start from a good example.

But, more important, I don't understand why automatic device suspend is not supported at first.

I did some test:
- provide a proper cpu-power-states in DTS (ie. add power-state-name = "suspend-to-idle" case) 
  ```
  	power-states {
		idle: idle {
			compatible = "zephyr,power-state";
			power-state-name = "suspend-to-idle";
			min-residency-us = <1000>;
		};
	};
  ```
- modify  soc/arm/nordic_nrf/nrf52/power.c to call k_cpu_idle() when a low power mode is requested
  ```
  @@ -16,10 +16,12 @@ __weak void pm_power_state_set(struct pm_state_info info)
 	switch (info.state) {
 	case PM_STATE_SOFT_OFF:
 		nrf_power_system_off(NRF_POWER);
 		break;
 	default:
  +	    k_cpu_idle();
 		LOG_DBG("Unsupported power state %u", info.state);
 		break;
 	}
   }
   ```
- add the PM_DEVICE_ACTION_LOW_POWER case  in uarte_nrfx_pm_control to disable the uart just for the idle period
   ```
  @@ -1858,10 +1860,11 @@ static int uarte_nrfx_pm_control(const struct device *dev,
 		}
 		break;
 	case PM_DEVICE_ACTION_SUSPEND:
  +	case PM_DEVICE_ACTION_LOW_POWER:
 		/* Disabling UART requires stopping RX, but stop RX event is
 		 * only sent after each RX if async UART API is used.
   ```

With those changes, zephyr properly request devices PM suspend before going in idle and consume as few as expected (few uA with a 1s advertising). And serial log , printk & co are still working as expected once we exit idle.

Is there something I miss in nrf52 support that prevent this automatic device PM ? or is it just that nordic didn't finalize the support yet ?

Regards,
Arnaud

**Comment by dakejahl** [comment]
I've been struggling with this on the nrf52840dk for months. I have not been able to get current consumption below 270uA. I've tried everything with no luck. Can you share with me your code you used to successfully achieve the few uA? I added your above snippets but I am still seeing 270uA. If I got into System OFF mode I do indeed see a very low current oonsumption, so I know at least that works, but I'd like to stay in System ON with all of the peripherals disabled.
