### ISSUE TITLE
stm32h7: Ethernet: Migrate driver to the new eth HAL api

### ISSUE THREAD

**Issue by erwango** [zephyrproject-rtos/zephyr#41380]
**Is your enhancement proposal related to a problem? Please describe.**
A new eth cube hal api is being pushed in STM32Cube (https://github.com/STMicroelectronics/stm32h7xx_hal_driver/pull/16).
It is first deployed to H7 series and will be then be progressively extended to other STM32 series.
This new HAL provides significant performance benefits and additional features (cf related github PR)
To use it, existing STM32 ethernet HAL driver should be reworked.

I'm raising this issue to synchronize efforts on this task.

EDIT: A STM32H7Cube package has been proposed that includes examples using the new HAL API. It's available here:
https://github.com/STMicroelectronics/STM32CubeH7/pull/195

**Comment by erwango** [comment]
FYI: @Nukersson, @lochej (as code owners), @alsrgv(as ptp contributor).
I'm assigning the issue to myself for now (as if I don't do it, someone else will do anyway),
but please don't hesitate to take it, if interested.

**Comment by alsrgv** [comment]
@erwango, I can help verify PTP functionality once you have a PR up.
