### ISSUE TITLE
littlefs(external spi flash) + mcuboot can't get right mount area

### ISSUE THREAD

**Issue by xinglongzhu** [zephyrproject-rtos/zephyr#41395]
**Describe the bug**
external flash
Only littlefs works ok.
When you add littlefs and mcuboot together, you can't get right mount area.
I have add pm_static.yml but it no work well in real hardware.

 - What target platform are you using?
 ncs\zephyr\samples\subsys\fs\littlefs
 - What have you tried to diagnose or workaround this issue?
 - mcuboot + littlefs(external flash)

**Expected behavior**
littlefs(external flash) can work when you add mcuboot

**Impact**
When I add mcuboot my littlefs(external flash can't work)

**Logs and console output**
My pm_static.yml
```
external_flash:
  address: 0x0
  end_address: 0x1000000
  region: external_flash
  size: 0x1000000
littlefs_storage:
  address: 0x0
  device: FM25Q08B
  region: external_flash
  size: 0x20000
```

log
```
[00:00:00.000,122] <inf> littlefs: littlefs partition at /lfs1
Area 0 at 0x0 on FM25Q08B for 0x1000000 bytes

Erasing flash area ... 0

[00:00:42.495,635] <inf> littlefs: LittleFS version 2.2, disk version 2.0
[00:00:42.496,337] <inf> littlefs: FS at FM25Q08B:0x0 is 256 0x10000-byte blocks with 512 cycle
[00:00:42.496,887] <inf> littlefs: sizes: rd 16 ; pr 16 ; ca 64 ; la 32
[00:00:42.498,046] <err> littlefs: WEST_TOPDIR/modules/fs/littlefs/lfs.c:997: Corrupted dir pair at {0x0, 0x1}
[00:00:42.498,657] <wrn> littlefs: can't mount (LFS -84); formatting
[00:00:43.011,901] <inf> littlefs: /lfs1 mounted
/lfs1 mount: 0

/lfs1: bsize = 16 ; frsize = 65536 ; blocks = 256 ; bfree = 254

/lfs1/boot_count stat: -2

/lfs1/boot_count read count 0: 0

/lfs1/boot_count seek start: 0

/lfs1/boot_count write new boot count 1: 4

/lfs1/boot_count close: 0

/lfs1 opendir: 0

  F 4 boot_count

End of files

[00:00:43.019,439] <inf> littlefs: /lfs1 unmounted
/lfs1 unmount: 0
```

**Environment (please complete the following information):**
 -  Windows
 - ncs v2.6.99
 - SHA-1: 18e072b03270436fcd58312217fa8f362abb5ccd

**Additional context**
Add any other context that could be relevant to your issue, such as pin setting,
target configuration, ...

**Comment by nvlsianpu** [comment]
@xinglongzhu Mentioned NCS version has issue with littlefs automount when the NCS Partition manager (PM) is used. When you has built the sample without CONFIG_MCUBOOT_BOOTLOADER=y the PM was not enabled, otherwise as for building with mcuboot.

This was fixed recently by https://github.com/nrfconnect/sdk-zephyr/pull/645 + https://github.com/nrfconnect/sdk-nrf/pull/6459.

Nordic devzone is the proper place to register issues with NCS, this issue is not a zephyr-rtos fault, that why I'm closing it.
