### ISSUE TITLE
power_init for STM32L4 and STM32G0 in POST_KERNEL

### ISSUE THREAD

**Issue by benediktibk** [zephyrproject-rtos/zephyr#41442]
**Describe the bug**
For STM32L4 and STM32G0 stm32_power_init is executed in POST_KERNEL.

**Expected behavior**
For STM32L4 and STM32G0 stm32_power_init should be executed in PRE_KERNEL_1.

**Impact**
Did not stumble upon any problems, it just came up during the review of #41439.

**Comment by FRASTM** [comment]
All stm32 mcu with low power modes (power.c) 

- stm32G0, stm32L0, stm32L4, stm32L5, stm32U5, stm32WB, stm32WL

have the `SYS_INIT(stm32_power_init, POST_KERNEL`
So that I propose to change each  with  **PRE_KERNEL_1**  in their soc/power.c
