### ISSUE TITLE
Transition message on jira.zephyrproject.org needed

### ISSUE THREAD

**Issue by dbkinder** [zephyrproject-rtos/zephyr#4149]
We need some message on jira.zephyrproject.org indicating it's no longer being used for tracking Zephyr issues, with a pointer referring folks to the GitHub issues page instead.

**Comment by pfalcon** [comment]
+1

**Comment by nashif** [comment]
done

**Comment by pfalcon** [comment]
@nashif : Nice. But note that on https://jira.zephyrproject.org/ , in the "Introduction" box (below the notice which you added) it says:

> The Zephyr™ Project uses this JIRA system to collect and track requirements and reported issues.

Maybe it would make sense to do something about that sentence too, e.g. remove "and report issues", or maybe remove the sentence completely.
