### ISSUE TITLE
tests: drivers: : ethernet: fails to link for sam_v71_xult and sam_v71b_xult

### ISSUE THREAD

**Issue by cfriedt** [zephyrproject-rtos/zephyr#41525]
**Describe the bug**
The daily build fails to link for this test / platform combination.

**To Reproduce**
```
twister -i -p sam_v71_xult -s tests/drivers/build_all/ethernet/net.ethernet.build
twister -i -p sam_v71b_xult -s tests/drivers/build_all/ethernet/net.ethernet.build
```

**Expected behavior**
The daily build should not fail.

**Impact**
Showstopper for anyone using ethernet on these platforms.

**Logs and console output**
```
/opt/toolchains/zephyr-sdk-0.13.2/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/10.3.0/../../../../arm-zephyr-eabi/bin/ld.bfd: zephyr/drivers/spi/libdrivers__spi.a(spi_sam.c.obj):(.rodata.__compound_literal.0+0x0): undefined reference to `__device_dts_ord_27'
/opt/toolchains/zephyr-sdk-0.13.2/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/10.3.0/../../../../arm-zephyr-eabi/bin/ld.bfd: zephyr/drivers/spi/libdrivers__spi.a(spi_sam.c.obj):(.rodata.__compound_literal.0+0x8): undefined reference to `__device_dts_ord_27'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
```

**Environment (please complete the following information):**
 - OS: CI
 - Toolchain: Zephyr SDK 0.13.2
 - Commit SHA: 7f5eb921dc8bb1b7014886986bbffdf111b68b15

**Additional context**
Daily build failure:
https://github.com/zephyrproject-rtos/zephyr/runs/4676614702?check_suite_focus=true

**Comment by dkalowsk** [comment]
seems similar to #41677
