### ISSUE TITLE
Modbus Gateway: Transaction ID Error!

### ISSUE THREAD

**Issue by maweicoltsmart** [zephyrproject-rtos/zephyr#41637]
samples/subsys/modbus/tcp_gateway/

fix the bug:
```
diff --git a/subsys/modbus/modbus_raw.c b/subsys/modbus/modbus_raw.c
index e4e330f5ad..e283dc7f8f 100644
--- a/subsys/modbus/modbus_raw.c
+++ b/subsys/modbus/modbus_raw.c
@@ -147,7 +147,7 @@ int modbus_raw_backend_txn(const int iface, struct modbus_adu *adu)
        err = modbus_tx_wait_rx_adu(ctx);
 
        if (err == 0) {
-               memcpy(adu, &ctx->rx_adu, sizeof(struct modbus_adu));
+               memcpy((uint8_t *)adu + 4, (uint8_t *)&ctx->rx_adu + 4, sizeof(struct modbus_adu) - 4);
        } else {
                modbus_set_exception(adu, MODBUS_EXC_GW_TARGET_FAILED_TO_RESP);
        }

```

**Comment by jukkar** [comment]
Please send a PR for the fix so that it can be reviewed and merged properly.

**Comment by jfischer-no** [comment]
> Please send a PR for the fix so that it can be reviewed and merged properly.

It does not look like correct fix for me. And for what bug?

**Comment by jukkar** [comment]
> > Please send a PR for the fix so that it can be reviewed and merged properly.
> 
> It does not look like correct fix to me. And for what bug?

I do not know, that is why I suggested that a PR is created so that the "fix" can be reviewed.
