### ISSUE TITLE
esp32 newlib

### ISSUE THREAD

**Issue by sam131208** [zephyrproject-rtos/zephyr#41707]
**Describe the bug**
We know that esp32 compile errors after enabling CONFIG_NEWLIB_LIBC.
Sometimes, we need some functions of newlib, such as the mathematical function log(). We found that in ESP-IDF, there is a newlib, can you tell us how to use it in zephyr.

**Expected behavior**
Looking for an alternative to CONFIG_NEWLIB_LIBC.

**Comment by sylvioalves** [comment]
Closing this as there is another issue opened: https://github.com/zephyrproject-rtos/zephyr/issues/38978
This is WIP. Custom toolchain to be release soon.
