### ISSUE TITLE
assert.h should not include non libc headers

### ISSUE THREAD

**Issue by yonsch** [zephyrproject-rtos/zephyr#41765]
**Describe the bug**
If a source file includes the standard `assert.h` header, it also includes non standard Zephyr specific headers, as the assertions use `printk`, which includes logging.
In my case, a HAL source file included `assert.h`, and ended up also including the following files (in order):
```
zephyr/lib/libc/minimal/include/assert.h
zephyr/include/sys/__assert.h
zephyr/include/sys/printk.h
zephyr/include/logging/log.h
zephyr/include/logging/log_core.h
zephyr/include/logging/log_msg.h
zephyr/include/sys/util.h
```
And so a non Zephyr source file ended up "contaminated" with Zephyr definitions. One such definition was the `KHZ` macro, which conflicted with a definition of the same name in the HAL.

**Expected behavior**
In my opinion, standard library headers should not rely on non standard headers, or at least should be extra careful about including such headers.

**Impact**
Definitions ending up in a source file not expecting them (HAL) can cause redefinition warnings, with a possibility of the wrong definitions being chosen.
Another possible case is a definition coincidentally having the same name as a symbol in a source file. If we're unlucky, the symbol would be quietly substituted, possibly causing a bug.

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: 0.13.1
 - Commit SHA or Version used: #34835

**Comment by nashif** [comment]
this should have been kept as a bug, but regardless, the issue was resolved in 786647bdcfd
