### ISSUE TITLE
tests: drivers: i2c: I2C test does not build for Microchip platforms

### ISSUE THREAD

**Issue by albertofloyd** [zephyrproject-rtos/zephyr#41770]
**Describe the bug**
I2C test does not build for Microchip platform

**To Reproduce**
1. cd tests/drivers/i2c/i2c_api$
2. rm -rf build && west build -c  -b mec15xxevb_assy6853
or
2. rm -rf build && west build -c  -b  mec172xevb_assy6906
3. See error

**Expected behavior**
Test should be able to build and run during sanity check for this board

**Impact**
I2C driver for Microchip is not executed as part of sanity check

**Logs and console output**
/home/jamezaar/ecwork/zephyr_fork/tests/drivers/i2c/i2c_api/src/test_i2c.c:26:2: error: #error "Please set the correct I2C device"
   26 | #error "Please set the correct I2C device"
      |  ^~~~~
/home/jamezaar/ecwork/zephyr_fork/tests/drivers/i2c/i2c_api/src/test_i2c.c: In function 'test_gy271':
/home/jamezaar/ecwork/zephyr_fork/tests/drivers/i2c/i2c_api/src/test_i2c.c:34:52: error: 'I2C_DEV_NAME' undeclared (first use in this function)
   34 |  const struct device *i2c_dev = device_get_binding(I2C_DEV_NAME);
      |                                                    ^~~~~~~~~~~~
/home/jamezaar/ecwork/zephyr_fork/tests/drivers/i2c/i2c_api/src/test_i2c.c:34:52: note: each undeclared identifier is reported only once for each function it appears in
/home/jamezaar/ecwork/zephyr_fork/tests/drivers/i2c/i2c_api/src/test_i2c.c: In function 'test_burst_gy271':
/home/jamezaar/ecwork/zephyr_fork/tests/drivers/i2c/i2c_api/src/test_i2c.c:89:52: error: 'I2C_DEV_NAME' undeclared (first use in this function)
   89 |  const struct device *i2c_dev = device_get_binding(I2C_DEV_NAME);

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain Zephyr SDK,

**Comment by teburd** [comment]
Fixed with PR https://github.com/zephyrproject-rtos/zephyr/pull/41983
