### ISSUE TITLE
UART ESP32 - Enabling UART1 / UART2 prevents console output

### ISSUE THREAD

**Issue by WilliamRoyle** [zephyrproject-rtos/zephyr#41836]
Hello, 

I am trying to get UART2 running on the ESP32 (In particular, the Huzzah board- ESP WROOM). I've left the esp32 dtsi file as configured, including the section with disables uart0, uart1, uart2 through `status = "disabled"; `. The relevant section of the devicetree (dts) for the ESP32 is as follows:

```
&uart0 {
        status = "okay";
        current-speed = <115200>;
        tx-pin = <1>;
        rx-pin = <3>;
        rts-pin = <22>;
        cts-pin = <19>;
};

&uart1 {
        status = "okay";
        current-speed = <115200>;
        tx-pin = <10>;
        rx-pin = <9>;
        rts-pin = <11>;
        cts-pin = <6>;
        hw-flow-control;
};

&uart2 {
        status = "okay";
        current-speed = <115200>;
        tx-pin = <17>;
        rx-pin = <16>;
        rts-pin = <7>;
        cts-pin = <8>;
        hw-flow-control;
};
```

The only change from default is adding  status = "okay". When I compile and run any code with this setting, even "Hello World", I do not see program output on the terminal after the program has been booted. Why is this? Enabling UART1 and UART2 should not cause any changes in default operation.

**Comment by sylvioalves** [comment]
@WilliamRoyle, please, would you test this issue using this https://github.com/zephyrproject-rtos/zephyr/pull/41941?

**Comment by LixinGuoX** [comment]
I have problem on building with this patch, is this a common issue?
```
/home/guo/.espressif/tools/zephyr/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.bfd: zephyr/drivers/serial/libdrivers__serial.a(uart_esp32.c.obj):(.literal.uart_esp32_configure_pins+0x0): undefined reference to `uart_periph_signal'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
FATAL ERROR: command exited with status 1: /usr/local/bin/cmake --build /home/guo/zephyrproject/zephyr/build
```

**Comment by sylvioalves** [comment]
@LixinGuoX, please, run `west update` so that `hal_espressif` brings that symbol.

**Comment by sylvioalves** [comment]
@LixinGuoX Can we close this?

**Comment by sylvioalves** [comment]
Closing. Re-open if needed.

**Comment by WilliamRoyle** [comment]
Sylvio,

Thank you so much for your help with this. Unfortunately, I won't be able to test - long story Glad that this is cleared up in the code base.
