### ISSUE TITLE
ESP32 Wifi AP Mode DHCP Service

### ISSUE THREAD

**Issue by huarunlin** [zephyrproject-rtos/zephyr#41864]
I set the wifi working mode to ap mode, the mobile phone is connected to the esp32, and found that the mobile phone cannot obtain an IP through DHCP, how to start the DHCP service?

zephyr version: main branch c9a3dae6519fc788d33233fc1c4d1364ba129034

**Comment by dkalowsk** [comment]
@huarunlin can you please provide for more details for resolving the issue?  Follow the steps at https://github.com/zephyrproject-rtos/zephyr/issues/new?assignees=&labels=bug&template=bug_report.md&title=

**Comment by sylvioalves** [comment]
@huarunlin ESP32 WiFi SoftAP is not supported yet in Zephyr.

**Comment by rftafas** [comment]
Going further: DHCP server is not supported also by Zephyr networking stack, not even for cabled (or the doc misses that, see link below). So, even if AP mode is supported, there will be the need to manually configure all IP addresses which seems messy. If the necessity for AP mode is to configure future IOT devices, I suggest:

-Using Bluetooth
-Use suitable host mode config (tethering, app,...)

PTAL: https://docs.zephyrproject.org/latest/guides/networking/overview.html#supported-features

Currently there is no short/mid plans to support DHCP server and AP mode.

**Comment by huarunlin** [comment]
@rftafas Thanks,  looking forward to support in future updates

**Comment by sylvioalves** [comment]
@huarunlin Closing this as we already have an issue opened regarding DHCP server: #38284

**Comment by munir-zin** [comment]
Hi,
I need to get AP mode of ESP32 working. I am having the same issue of no ip address is assigned to client device when connecting to AP mode. Can anyone confirm if the support has been added for the DHCP or not? I am using `zephyr vv3.6.0`.

**Comment by rftafas** [comment]
It has support since early this year (2024). All comments here are very outdated.

**Comment by rftafas** [comment]
I suggest opening a new issue. This one is closed. Put all normal info for opening an issue there.
