### ISSUE TITLE
ieee802154_settings.c is duplicated in the codebase

### ISSUE THREAD

**Issue by pfalcon** [zephyrproject-rtos/zephyr#4189]
It's now at:

* samples/net/common/
* subsys/net/lib/app/

I hope everyone agrees that's not an OK situation, as the next step for them to diverge, so I'm marking this as prio:high.

**Comment by tbursztyka** [comment]
That's already taken care of actually. I am just about to send patches for cleaning up this.

**Comment by pfalcon** [comment]
Cool!

**Comment by pfalcon** [comment]
Addressed by #4191.

**Comment by nashif** [comment]
why are you closing issues before the PR is even merged? That is something that needs to be closed when the PR is merged using the "Fixes #XXXX" handler.
