### ISSUE TITLE
Add Cortex-A55 support

### ISSUE THREAD

**Issue by chojpsh1** [zephyrproject-rtos/zephyr#41900]
Hello, I'm studying Zephyr nowadays. I saw Zephyr supports the Cortex-A53 for supporting ARMv8-A type (via #11172 issue)
But I hope Zephyr also supports Cortex-a55, so I would like to ask if Zephyr has any plans for A55.
Thank you!

**Comment by dbaluta** [comment]
@chojpsh1 we at NXP are looking at this. ETA mid 2023. 

Cc: @LaurentiuM1234
