### ISSUE TITLE
pm_power_state_force returns false after first call

### ISSUE THREAD

**Issue by r2r0** [zephyrproject-rtos/zephyr#41911]
**Describe the bug**
I modified the zephyr/samples/boards/stm32/power_mgmt/stm32wb_ble/src/main.c file and I changed "pure" call to pm_power_state_force for sometihing to allow visually detect problems witch switching to shutdown:
```C
        if (!pm_power_state_force(0u, (struct pm_state_info){PM_STATE_SOFT_OFF, 0, 0})) {
                printk("Cannot force SHUTDOWN!\n");
        }
        k_sleep(K_MSEC(5));
        printk("Not in SHUTDOWN!\n");
```
And unfortunately above condition is met and also "Not in SHUTDOWN!" is printed.

**To Reproduce**
1. Change code in zephyr/samples/boards/stm32/power_mgmt/stm32wb_ble/src/main.c as described above
2. west build -b nucleo_wb55rg
3. west flash
4. Both messages from code above can be observed.

**Expected behavior**
No messages from modified code should be visible and MCU should switch to SHUTDOWN mode..

**Impact**
showstopper

**Logs and console output**
```
*** Booting Zephyr OS build v2.7.99-3296-ge8df8a579033  ***
Starting Beacon Demo
Bluetooth initialized
Beacon started, advertising as 80:E1:26:08:24:BC (public)
Beacon stopped
Beacon started
Device shutdown
Cannot force SHUTDOWN!
Not in SHUTDOWN!
```

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain Zephyr SDK 0.13.1
 - Commit SHA e8df8a579033be238beb774e4909d637da649f3a

**Additional context**
I observed that `z_power_states_forced` in pm.c is not equal 0 when `pm_power_state_force` is called **first** time.

**Comment by ceolin** [comment]
That is really weird, this function only returns `false` if the cpu bit in `z_power_states_forced` is 1 and this should be zeroed initialized. Can you try to following change and see what happens ?
```
@@ -29 +29 @@ static struct pm_state_info z_power_states[CONFIG_MP_NUM_CPUS];
-static ATOMIC_DEFINE(z_power_states_forced, CONFIG_MP_NUM_CPUS);
+static ATOMIC_DEFINE(z_power_states_forced, CONFIG_MP_NUM_CPUS) = { 0 };
```

**Comment by r2r0** [comment]
Unfortunately it changes nothing.
I suspect that problem can be caused by the fact that `z_power_states_forced` flag is cleared **after** scheduler is unlocked (in `pm_system_suspend`).
And then `pm_system_suspend` is called before main (issue #41839) then after main is scheduled the `z_power_states_forced` flag is still set and it prevents proper `pm_power_state_force` functionality.
Even if there was no sleep before main then such control flow (scheduler unlock -> flag clearing) is IMHO problematic.

**Comment by ceolin** [comment]
Ohh, I see. I have overlooked the messages, the first call works. Will look it better.

**Comment by ceolin** [comment]
Yep, I can confirm, if we clear out the flags with the scheduler locked the problem seems to go away. The assessment is correct, the main thread is scheduled after the system resumes and before the flags being cleared out.
