### ISSUE TITLE
drivers: dma/i2c: nios2: config used as non-const

### ISSUE THREAD

**Issue by gmarull** [zephyrproject-rtos/zephyr#41924]
**Describe the bug**

These drivers seem to treat device configuration as non-const. For example:

https://github.com/zephyrproject-rtos/zephyr/blob/40bb3d808acb3e40b4a96f3bee794eab2f021b52/drivers/dma/dma_nios2_msgdma.c#L107-L110

**To Reproduce**

1. Don't cast config to non-const (as it should be):
```
#define DEV_CFG(dev) \
	((const struct nios2_msgdma_dev_cfg *)(dev)->config)
```
2. `/scripts/twister -T tests/boards/altera_max10/msgdma -p altera_max10 -vv`

**Expected behavior**

Device driver should use `data` to store non-ROMable data.

**Impact**

Impacts https://github.com/zephyrproject-rtos/zephyr/pull/41918

**Logs and console output**

N/A

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain Zephyr SDK 0.13.1
 - Commit SHA or Version used e8df8a579033be238beb774e4909d637da649f3a

**Additional context**

N/A

**Comment by teburd** [comment]
I'm not sure this is a real issue on nios2, but intend on fixing it anyways given the const attributes we have going. Will have a finalized PR once I have the hardware to test against (early next week).
