### ISSUE TITLE
drivers: audio: tlv320dac310x: device config used as non-const

### ISSUE THREAD

**Issue by gmarull** [zephyrproject-rtos/zephyr#41931]
**Describe the bug**

The driver seems to treat device configuration as non-const. For example:

https://github.com/zephyrproject-rtos/zephyr/blob/5598ae85c0e3b29ed5042d890715b71a5dfce5d2/drivers/audio/tlv320dac310x.c#L84-L92
**To Reproduce**

1. Don't cast config to non-const (as it should be):
```
#define DEV_CFG(dev) \
	((const struct codec_driver_config *const)(dev)->config)
```
2. `/scripts/twister -T samples/boards/intel_s1000_crb/audio -p intel_s1000_crb -vv`

**Expected behavior**

Device driver should use `data` to store non-ROMable data.

**Impact**

Impacts https://github.com/zephyrproject-rtos/zephyr/pull/41918

**Logs and console output**

N/A

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain Zephyr SDK 0.13.1
 - Commit SHA or Version used e8df8a579033be238beb774e4909d637da649f3a

**Additional context**

N/A

**Comment by nashif** [comment]
fixed already.
