### ISSUE TITLE
Extra closing bracket in function lsm6dso_handle_interrupt

### ISSUE THREAD

**Issue by erikhole** [zephyrproject-rtos/zephyr#41976]
**Describe the bug**
On line 207 in file ` zephyr/drivers/sensor/lsm6dso/lsm6dso_trigger.c ` there is an extra closing bracket.

Please also mention any information which could help others to understand
the problem you're facing:
 - What target platform are you using?
 - What have you tried to diagnose or workaround this issue?
 - ...

**To Reproduce**
1. Open ` zephyr/drivers/sensor/lsm6dso/lsm6dso_trigger.c`
2. See the extra bracket

**Expected behavior**
That there are the same amount of opening and closing brackets in the code.

**Impact**
It looks like the last function in `lsm6dso_handle_interrupt()` won't run the last function `gpio_pin_interrupt_configure_dt(&cfg->gpio_drdy,
					GPIO_INT_EDGE_TO_ACTIVE);` 

**Environment (please complete the following information):**
 - OS: Debian
 - Toolchain (e.g nRF SDK, ...)
 - v2.7.0-ncs1

**Comment by henrikbrixandersen** [comment]
Please submit a PR.

**Comment by erikhole** [comment]
There was a bug in our local repo, and when checking the zephyr sdk I wasn't thorough enough.
