### ISSUE TITLE
Bluetooth Controller: scan aux setup not checking extended header length of received packet

### ISSUE THREAD

**Issue by carlst** [zephyrproject-rtos/zephyr#42065]
**Describe the bug**
Extended Header Length of received BLE packet is not checked before reading Extended Header field in `subsys/bluetooth/controller/ll_sw/nordic/lll/lll_scan_aux.c`, `lll_scan_aux_setup()`

Extended Header field (including Extended Header Flags) is therefore invalid and should not be used here.

**To Reproduce**
1. Use 2 nRF52840DK boards
2. Add `LL_ASSERT(pri_com_hdr->ext_hdr_len)` after `pri_dptr` is initially set at beginning of `lll_scan_aux_setup()`.
2. Run `periodic_sync` sample on board 2.
3. Run `periodic_adv` sample on board 1.
4. Board 2 will halt

**Expected behavior**
If Extended Header length `pri_com_hdr->ext_hdr_len == 0`, function should return 0 and system continue operating normally.

**Impact**
Annoyance.

**Environment (please complete the following information):**
 - nRF52840DK

**Comment by cvinayak** [comment]
Should be fixed by https://github.com/zephyrproject-rtos/zephyr/pull/41091/commits/94cf4cba9e61196c1fcac682a8b3ff1059fa852f and this commit in a separate PR will be sent to cover this github issue.
