### ISSUE TITLE
OTS: L2CAP: Unable to find channel of LE Credits packet

### ISSUE THREAD

**Issue by asbjornsabo** [zephyrproject-rtos/zephyr#42112]
Running the mcs_mcc BabbleSim tests, the following error message occurs when transferring objects over L2CAP:

d_01: @00:00:14.031757  [00:00:14.031,738] <dbg> bt_mpl: on_object_send: Read complete
d_01: @00:00:14.031757  [00:00:14.031,738] <dbg> bt_ots: l2cap_disconnected: Channel 0x82523fc disconnected
d_01: @00:00:14.032209  [00:00:14.032,196] <err> bt_l2cap: Unable to find channel of LE Credits packet
d_00: @00:00:14.032467  [00:00:14.032,440] <dbg> bt_ots: l2cap_disconnected: Channel 0x82549a8 disconnected
d_00: @00:00:14.032467  [00:00:14.032,440] <dbg> bt_otc: closed: L2CAP closed, context: 0x82549a4, conn: 0x825f0c0

After the OTS L2CAP server has disconnected the channel, there is an error message from l2cap that it can not find the channel of the LE Credits packet

**Comment by carlescufi** [comment]
@sjanc does this ring a bell at all?

**Comment by asbjornsabo** [comment]
I plan to look at this in the sprint that starts today.
