### ISSUE TITLE
drivers: serial: remove struct uart_device_config

### ISSUE THREAD

**Issue by gmarull** [zephyrproject-rtos/zephyr#42130]
## Introduction

I've opened this RFC to question if `struct uart_device_config` should be removed.

### Problem description

The main reasons:

1. It is not used by all drivers (in fact, I think it's a minority using it)
2. It pretends to be generic, but it is not (see for instance #42131)
3. No other subsystems are using this kind of _inheritance_ mechanism.
4. Some fields are not always used, wasting extra ROM space

### Proposed change

Each driver is responsible to store whatever is needed.

## Detailed RFC

See above.

### Proposed change (Detailed)

1. Remove usage of `struct uart_device_config` from all drivers
2. Remove `struct uart_device_config`

### Dependencies

None

### Concerns and Unresolved Questions

None

## Alternatives

N/A

**Comment by gmarull** [comment]
cc: @dcpleung

**Comment by dcpleung** [comment]
Probably a good move since only a few drivers are using it.
