### ISSUE TITLE
hts221 driver fails to build

### ISSUE THREAD

**Issue by ewalt1** [zephyrproject-rtos/zephyr#42147]
The sensor driver twister test is failing due to the hts221 driver being broken. It includes a header file that doesn't exist.
https://github.com/zephyrproject-rtos/zephyr/blob/main/drivers/sensor/hts221/hts221.h#L17

ZEPHYR_TOOLCHAIN_VARIANT=llvm twister -c -T tests/driver/build_all/sensor -p native_posix

**Comment by gmarull** [comment]
Would you mind submitting a fix?

**Comment by erwango** [comment]
Have you tried `west update` ?

**Comment by gmarull** [comment]
Closing as file exists in `stmemsc` module:

```
../modules/hal/st/sensor/stmemsc/hts221_STdC/driver/hts221_reg.h
```

Sensor build_all tests works fine, so `west update` is likely needed.
