### ISSUE TITLE
driver: i2s: i2s_mcux_sai build failure on mixmrt1170_evk_cm7

### ISSUE THREAD

**Issue by hakehuang** [zephyrproject-rtos/zephyr#42179]
**Describe the bug**
when enable the CONFIG_I2S_MCUX_SAI the i2s_api test build fail.

Please also mention any information which could help others to understand
the problem you're facing:

i2s driver issue

**To Reproduce**
1. mkdir build; cd build
2. cmake -DBOARD=mixmrt1170_evk_cm7
3. make

**Expected behavior**
Build PASS

**Impact**
What impact does this issue have on your progress (e.g., annoyance, showstopper)

**Logs and console output**

**Environment (please complete the following information):**
 - OS: (e.g. Linux,, )
 - Toolchain (e.g Zephyr SDK, ...)
 - Commit SHA or Version used: v3.0.0-rc1

**Comment by dleach02** [comment]
Fixed by #42155
