### ISSUE TITLE
[Backport v2.7-branch] drivers: can: m_can: The can_set_bitrate() function doesn't work.

### ISSUE THREAD

**Issue by JeremyBCD** [zephyrproject-rtos/zephyr#42271]
**Describe the bug**
Using the `can_set_bitrate()` function to change the bitrate of a m_can-compatible CANBUS peripheral doesn't work. The function returns success (0) but the bitrate doesn't change.

Tested on STM32H753-based proprietary board, nucleo_g474re, and nucleo_h753zi.

**To Reproduce**
1. Call `can_set_bitrate()`, setting a new bitrate.
2. Attempt to receive at the new bitrate.
3. No frames received.
4. Check at old bitrate.
5. Frames still received.

**Expected behavior**
The peripheral should change to the new bitrate.

**Impact**
I found the issue and solved it. I've submitted [a PR to main](https://github.com/zephyrproject-rtos/zephyr/pull/42239), which was accepted and merged. This issue report is intended to help make the argument for back-porting this fix to 2.7.0.

**Environment (please complete the following information):**
 - OS: macOS, Linux
 - Toolchain: Zephyr SDK on Linux, arm-gcc on macOS
 - Commit: v3.0.0-rc1

**Comment by henrikbrixandersen** [comment]
Fixed in #42266.
