### ISSUE TITLE
Use twister with out of tree drivers.

### ISSUE THREAD

**Issue by helo9** [zephyrproject-rtos/zephyr#42288]
**Is your enhancement proposal related to a problem? Please describe.**
I would like to run twister in an application with out of tree drivers. As far as I could see, that is not possible atm.

**Describe the solution you'd like**
Add a option to define an module path (where _zephyr/module.yml_ is living and use the folders given there.

**Describe alternatives you've considered**
Manually set the pathes, maybe?

**Comment by henrikbrixandersen** [comment]
Please describe the problem you are seeing. I am using twister with out-of-tree drivers just fine.

**Comment by helo9** [comment]
Ah nice, I get this error:
```
-- Found BOARD.dts: /home/jonathanh/Programmieren/controllearning/frickelflightcontrol/boards/arm/openpilot_cc3d/openpilot_cc3d.dts
devicetree error: node '/soc/serial@40013800/srxl2' compatible 'spektrum,srxl2receiver' has unknown vendor prefix 'spektrum'
CMake Error at /home/jonathanh/Programmieren/controllearning/zephyr/cmake/dts.cmake:205 (message):
  gen_defines.py failed with return code: 1
```
when running `../zephyr/scripts/twister -T samples -A boards` in my application. But when looking into my normal builds again, I see the same message, it is just ignored from the build system. So I rather have to see how to make spektrum a known vendor or rename it. Will close and eventually reopen, in case problem is present afterwards.

**Comment by henrikbrixandersen** [comment]
The procedure for adding new vendor prefixes, which also applies to out-of-tree bindings, is described here:
https://docs.zephyrproject.org/latest/guides/dts/bindings.html#vendor-prefixes
