### ISSUE TITLE
pm: Force shutdown has no effect 

### ISSUE THREAD

**Issue by erwango** [zephyrproject-rtos/zephyr#42308]
**Describe the bug**
Running `samples/boards/stm32/power_mgmt/stm32wb_ble`, we can observe that call to `pm_power_state_force((struct pm_state_info){PM_STATE_SOFT_OFF, 0, 0});` has no effect anymore.

When adding following lines after the shutdown command, we can observe the ERROR statement is reached
```
+	printk("ERROR: System off failed\n");
+	while (true) {
+		/* spin to avoid fall-off behavior */
+	}
```

**To Reproduce**
1. west build -p -b nucleo_wb55rg boards/stm32/power_mgmt/stm32wb_ble
2. west flash

**Expected behavior**
Shutdown should be triggered

**Impact**
Not possible to force shutdown anymore

**Comment by erwango** [comment]
Short analysis points to https://github.com/zephyrproject-rtos/zephyr/pull/40339.

**Comment by r2r0** [comment]
This is related to issue #41911.
Effectively current implementation of `pm_power_state_force` do nothing.
Sadly #41911 issue has low priority but fortunately fix is pending.

**Comment by erwango** [comment]
Closing in favor of https://github.com/zephyrproject-rtos/zephyr/issues/41911
