### ISSUE TITLE
log mem shell command not working

### ISSUE THREAD

**Issue by cfriedt** [zephyrproject-rtos/zephyr#42360]
**Describe the bug**
The `log mem` shell command does not seem to work anymore, with `CONFIG_LOG2` at least (which is IIRC, the default). I was specifically hoping to find the high watermark of log buffer memory usage with `CONFIG_MEM_SLAB_TRACE_MAX_UTILIZATION` but all values are zero.

Please also mention any information which could help others to understand
the problem you're facing:
 - What target platform are you using? `qemu_cortex_a53`
 - What have you tried to diagnose or workaround this issue? Yes - I suspect this has to do with the transition from slab memory to ring buffer and it may have been overlooked.

**To Reproduce**
1. Add the following to `samples/subsys/logging/logger/prj.conf`
    ```
    CONFIG_MEM_SLAB_TRACE_MAX_UTILIZATION=y
    CONFIG_SHELL=y
    CONFIG_LOG_CMDS=y
    ```
2. `west build -p auto -b qemu_cortex_a53 -t run samples/subsys/logging/logger`
3.  `log mem`

**Expected behavior**
I would expect that used, free, and max memory is displayed (although likely now in bytes rather than blocks).

**Impact**
It's a bit of a showstopper for me, as I was in the middle of performance tuning my log backend and I was unable to get the high watermark of log buffer usage.

**Logs and console output**
```
uart:~$ log mem
Blocks used:    0
Blocks free:    0
Blocks max:     0
```

**Environment (please complete the following information):**
 - OS: macOS
 - Toolchain: Zephyr SDK v0.13.1
 - Commit SHA or Version used: 84fd7f35d523d1f841ba955b5ddf93aca3e0210c

**Additional context**

**Comment by nordic-krch** [comment]
Hm, v2 does not use memslabs for storing log messages but `mpsc_pbuf` so this command is for v1 case only. I will see tomorrow what are the options regarding profiling memory usage of v2, currently mpsc_pbuf has no instrumentation like that but it should be possible to add it.
