### ISSUE TITLE
`crc16_ansi()` isn't CRC-16-ANSI

### ISSUE THREAD

**Issue by attie-argentum** [zephyrproject-rtos/zephyr#42403]
**Describe the bug**
It appears that the [`crc16_ansi()`](https://github.com/zephyrproject-rtos/zephyr/blob/main/include/sys/crc.h#L136) function (introduced in bd75219b) does not actually implement CRC-16-ANSI.
According to Wikipedia, CRC-16-IBM is the same thing as (aka) ANSI, Modbus, etc... `poly: 0x8005`, `init: 0xffff`, `reversed: yes`.
Online calculators (e.g: [crccalc.com](https://crccalc.com/)) and other implementations (e.g: [crc16-ansi](https://github.com/bd2357/crc16-ansi/blob/master/src/crc16.c#L140)) agree with each other.

Within Zephyr, this function is only used by `subsys/net/lib/dns/resolve.c` and tests (which appear to use incorrect constants)... the DNS subsys only actually uses the CRC for internal identification of a request/response, so its value is not validated.

Note also that the Modbus subsys implements its own (correct) CRC function: [`modbus_rtu_crc16()`](https://github.com/zephyrproject-rtos/zephyr/blob/main/subsys/modbus/modbus_serial.c#L241).

I suspect that this may be a "_reflected_" (aka reversed) vs. "_not reflected_" issue, but I've not pursued that at this time.

Am I misunderstanding here? (i.e: is this function correct? misnamed?)

**To Reproduce**
Use the attached files - [crc-test.zip](https://github.com/zephyrproject-rtos/zephyr/files/7986973/crc-test.zip).

1. `unzip crc-test.zip`
2. `cd crc-test`
3. `gcc crc-test-zephyr.c -o crc-test-zephyr`
4. `gcc crc-test-other.c -o crc-test-other`
5. `./crc-test-zephyr`
6. `./crc-test-other`

**Expected behavior**
Output of `./crc-test-zephyr` and `./crc-test-other` should match.

**Impact**
I was planning to use `crc16_ansi()` in my application, but it provides incorrect values... I've re-implemented `modbus_rtu_crc16()` instead.

As noted above, this isn't actually used in the Zephyr code base in any meaningful way, but it could be used by applications. Similarly to the DNS use-case above, internal integrity checking would be mostly unaffected (though for example, existing non-volatile storage may appear to be corrupt after a firmware update)... I suspect that anyone using this function with other systems will have issues.

**Logs and console output**
```
$ git clone --depth 1 https://github.com/bd2357/crc16-ansi.git
Cloning into 'crc16-ansi'...
remote: Enumerating objects: 307, done.
remote: Counting objects: 100% (307/307), done.
remote: Compressing objects: 100% (257/257), done.
remote: Total 307 (delta 16), reused 306 (delta 16), pack-reused 0
Receiving objects: 100% (307/307), 1.79 MiB | 0 bytes/s, done.
Resolving deltas: 100% (16/16), done.
Checking connectivity... done.
$ gcc crc-test-zephyr.c -o crc-test-zephyr
$ gcc crc-test-other.c -o crc-test-other
$ ./crc-test-zephyr
[hello world] --> 0x971b
68 65 6c 6c 6f 20 77 6f 72 6c 64
$ ./crc-test-other
[hello world] --> 0xddc7
68 65 6c 6c 6f 20 77 6f 72 6c 64
```

**Comment by carlescufi** [comment]
Thanks for reporting this. You are completely right, I will submit a fix.

**Comment by attie-argentum** [comment]
@carlescufi - no problem, thanks for confirming and taking it on.
