### ISSUE TITLE
where is auto-pts py script of zephyr?

### ISSUE THREAD

**Issue by cobbler123** [zephyrproject-rtos/zephyr#4249]
hi friends,
        could you tell me where is auto-pts py script of zephyr?

Thanks very much!

**Comment by jhedberg** [comment]
where did you see a reference to it?

**Comment by jhedberg** [comment]
Anyway, the auto-pts project is not (at least yet) public, so unfortunately the script is not available.

**Comment by cobbler123** [comment]
I See, Thank you very much for your reply!

**Comment by mringwal** [comment]
hi. It's mentioned in Luiz' talk "BlueZ meets Zephyr". Any update on the status or some estimates? Running PTS in a CI setup would be nice :)
