### ISSUE TITLE
bt_ots Doxygen documentation does not seem to be included in the Zephyr project documentation.

### ISSUE THREAD

**Issue by Thalley** [zephyrproject-rtos/zephyr#42520]
(Do not find any bt_ots entries when searching)

**Comment by carlescufi** [comment]
I'll take this one

**Comment by Thalley** [comment]
@asbjornsabo You created this originally as a note; did you look into this at all?

**Comment by asbjornsabo** [comment]
> @asbjornsabo You created this originally as a note; did you look into this at all?

I only saw that I could not find the OTS content in the Zephyr documentation.

**Comment by Thalley** [comment]
@carlescufi Are you planning on working on this? Otherwise @asbjornsabo  will take a look at it soon

**Comment by cvinayak** [comment]
Bluetooth team is not currently looking into this, @asbjornsabo is free to take up.
