### ISSUE TITLE
Wrong implementation of SPI driver

### ISSUE THREAD

**Issue by paveldedourek-eaton** [zephyrproject-rtos/zephyr#42524]
Wrong implementation of SPI protocol

1. wrong bits are used for command
2. wrong bits are used for address
3. address in 8bit and not 16bit

### SPI write Command
https://github.com/zephyrproject-rtos/zephyr/blob/a775606ae95559daca40b65ba68509712fa5be65/drivers/ethernet/dsa_ksz8863.h#L11

https://github.com/zephyrproject-rtos/zephyr/blob/a775606ae95559daca40b65ba68509712fa5be65/drivers/ethernet/dsa_ksz8xxx.c#L60

![ksz8863_write_protocol](https://user-images.githubusercontent.com/98147995/152762347-69e1ed74-52d9-4a9c-a4b9-be41c15ff8dc.PNG)

Wrong bit are used in SPI write command.

### SPI read command
https://github.com/zephyrproject-rtos/zephyr/blob/a775606ae95559daca40b65ba68509712fa5be65/drivers/ethernet/dsa_ksz8863.h#L12

https://github.com/zephyrproject-rtos/zephyr/blob/a775606ae95559daca40b65ba68509712fa5be65/drivers/ethernet/dsa_ksz8xxx.c#L92

![ksz8863_read_protocol](https://user-images.githubusercontent.com/98147995/152762551-39c0adf1-e89b-4c3b-9702-443bff62ab80.PNG)
Wrong bit are used in SPI read command.

**Comment by carlescufi** [comment]
@paveldedourek-eaton since you've analyzed the issue, is there a chance you can send a Pull Request with the fix? Thanks!

**Comment by carlescufi** [comment]
> @carlescufi I can try, is there some procedure to follow for bugfix and PR?

You just need to open a Pull Request with the fix and then we can add @arvinf, the original author, to review it.

**Comment by arvinf** [comment]
Please also tag @lmajewski. He is the original author, including the SPI support. I refactored the driver to add support for a variant.

**Comment by lmajewski** [comment]
@paveldedourek-eaton @arvinf  The part for KSZ8794 is working - at least the configuration (and communication) via SPI for the `ip_k66f` board. Recently, I've added several fixes (now in upstream/main) which were correcting some errors after adding the KSZ8863 variant.

**Comment by paveldedourek-eaton** [comment]
I made working I2C communication between KSZ8863 and my Nucleo-F429ZI. 
I am just struggling with correct assignment of ports: eth0, lan1, lan2... when this will be done I will concentrate to prepare Pull Request.

**Comment by paveldedourek-eaton** [comment]
Issue is solved in following PR: https://github.com/zephyrproject-rtos/zephyr/pull/43069
Waiting for approvals .
