### ISSUE TITLE
LE Audio: Move media_proxy out of bt subsystem?

### ISSUE THREAD

**Issue by Thalley** [zephyrproject-rtos/zephyr#42523]
Make media_proxy general (usable also for other protocols than Bluetooth) and move out of bt subsystem.
- [ ] Proposal for subsystem for media - draw on Linux/AOSP
 - "In my opinion, SOF is a media subsystem, but it only supports the xtensa architecture." https://github.com/zephyrproject-rtos/zephyr/issues/44295#issuecomment-1082573378
- [ ] Move media

**Comment by asbjornsabo** [comment]
From discussion with @Thalley : The media_proxy is quite tied to mcc.  Keep in bluetooth directory for now.

**Comment by asbjornsabo** [comment]
Reopen, as a result of https://github.com/zephyrproject-rtos/zephyr/pull/43029#discussion_r812838270

**Comment by Mikdadali** [comment]
any way to fix bt crashing in a13, as we have LE audio support and we are not able to fix it

**Comment by Thalley** [comment]
> any way to fix bt crashing in a13, as we have LE audio support and we are not able to fix it

This comment seems unrelated to the issue.
