### ISSUE TITLE
3.0.0-rc1: warning: LOG_STRDUP_MAX_STRING was assigned the value '100' but got the value ''

### ISSUE THREAD

**Issue by caco3** [zephyrproject-rtos/zephyr#42585]
I just updated from `2.7.0` to `3.0.0-rc1`.
Now I get the following warning: `warning: LOG_STRDUP_MAX_STRING (defined at subsys/logging/Kconfig.processing:124) was assigned the value '100' but got the value ''`.
`LOG_STRDUP_MAX_STRING  `is defined in my `proj.conf` with `LOG_STRDUP_MAX_STRING=100`.

Same with `LOG_STRDUP_BUF_COUNT`.

What is the reason for this? The flags are still documented and I haven't found any commit related to this.

**Comment by KKopyscinski** [comment]
@caco3 I don't know anything about this issue but looking at Discord I think you wanted to ask @nordic-krch

**Comment by caco3** [comment]
ah, sry, I picked the wrong username.
