### ISSUE TITLE
doc: broken CONFIG_GPIO link in https://docs.zephyrproject.org/latest/reference/peripherals/gpio.html

### ISSUE THREAD

**Issue by joeyh** [zephyrproject-rtos/zephyr#42604]
https://docs.zephyrproject.org/latest/reference/peripherals/gpio.html has a broken link for CONFIG_GPIO

**Comment by gmarull** [comment]
The link works well, points to https://docs.zephyrproject.org/latest/reference/kconfig/CONFIG_GPIO.html#std-kconfig-CONFIG_GPIO.
