### ISSUE TITLE
[ 2.7.1 ] pm: pm_device structure bigger than nessecary when PM_DEVICE_RUNTIME not set

### ISSUE THREAD

**Issue by kurddt** [zephyrproject-rtos/zephyr#42622]
**Describe the bug**
The PM structure created for each device is bigger than necessary when PM_DEVICE_RUNTIME is not set

**Expected behavior**
A big part of the structure should not be compiled (since not used) when PM_DEVICE_RUNTIME is not set

**Impact**
This will use quite some resources (RAM/ROM) for nothing

This issue has been solved by #39227 but need to be backported to 2.7

**Comment by ceolin** [comment]
https://github.com/zephyrproject-rtos/zephyr/pull/44097
