### ISSUE TITLE
sample.bootloader.mcuboot.serial_recovery fails to compile

### ISSUE THREAD

**Issue by nordic-krch** [zephyrproject-rtos/zephyr#42690]
**Describe the bug**
Seen on PR https://github.com/zephyrproject-rtos/zephyr/runs/5139241363?check_suite_focus=true and fails locally.

**To Reproduce**
Run in zephyr dir: `scripts/twister -c -T ../bootloader/mcuboot/boot/zephyr/`

**Expected behavior**
Should compile.

**Impact**
Red CI.

**Environment (please complete the following information):**
- b68bdf20cf17094801f2b42d6bd75ba6f67535a7

**Comment by carlescufi** [comment]
Fix in progress: https://github.com/mcu-tools/mcuboot/pull/1304
