### ISSUE TITLE
sys_slist / sys_dlist get number of nodes in list

### ISSUE THREAD

**Issue by Thalley** [zephyrproject-rtos/zephyr#42775]
**Is your enhancement proposal related to a problem? Please describe.**
There's a number of cases where the user of a linked list would like the get the number of nodes in the list. 

**Describe the solution you'd like**
Add a function e.g. `size_t sys_slist_len(sys_slist_t *list)` that returns the number of nodes in the list. Ditto for `dlist`. 

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by balajikulkarni** [comment]
@Thalley Interested in taking up this enhancement, please assign to me.

**Comment by Thalley** [comment]
Fixed by https://github.com/zephyrproject-rtos/zephyr/pull/56886
