### ISSUE TITLE
gptp correction field in sync follow up message does not have correct endianness

### ISSUE THREAD

**Issue by bibibibi89** [zephyrproject-rtos/zephyr#42799]
**Describe the bug**
When gptp prepare sync follow up message, endianness of correction does not get converted to network endianness. 

https://github.com/zephyrproject-rtos/zephyr/blob/main/subsys/net/l2/ethernet/gptp/gptp_md.c#L51-L54
Other filed in followup hdr get converted to network endian not correction_field.

**To Reproduce**
1. Run gptp
2. Set correction_field in follow up message to non-zero value
3. Monitor gptp follow up message in wireshark
4. Correction field value does not match expected value. Endianness is incorrect.

**Expected behavior**
a htonll should be called to convert correct_field to network endian (big endian).

**Impact**
Slave port receives followup message from master port can't calculate timestamp correctly due to incorrect correction_field in followup message

**Comment by jukkar** [comment]
Hi @bibibibi89, would you be able to send a fix for this issue?

**Comment by bibibibi89** [comment]
I will create a fix.
