### ISSUE TITLE
gptp_mi neighbor_prop_delay is not included in sync_receipt_time calculation due cast from double to uint64_t

### ISSUE THREAD

**Issue by bibibibi89** [zephyrproject-rtos/zephyr#42800]
**Describe the bug**
in gptp_mi_clk_slave_sync_compute function, both pss->rate_ratio and nport_ds->neighbor_rate_ratio are double type but sync_receipt_time is uint64_t.

If pss->rate_ratio is less than 1 or port_ds->neighbor_rate_ratio is less than 1, sync_receipt_time will be 0 after first 2 statements. Then port_ds->neighbor_prop_delay won't be included in sync_receipt_time. 

sync_receipt_time = pss->rate_ratio;
sync_receipt_time /= port_ds->neighbor_rate_ratio;
sync_receipt_time *= port_ds->neighbor_prop_delay;

https://github.com/zephyrproject-rtos/zephyr/blob/main/subsys/net/l2/ethernet/gptp/gptp_mi.c#L709-L710

**Expected behavior**

**Impact**
global_ds->sync_receipt_time does not include neighbor_prop_delay but global_ds->sync_receipt_local_time does include neighbor_prop_delay properly then calculated time difference between GM clock and local clock is not correct. Sometimes, we observed time difference equals to neighbor_prop_delay.

**Comment by jukkar** [comment]
Hi @bibibibi89, would you be able to send a fix for this issue?

**Comment by bibibibi89** [comment]
I will creat a fix.

**Comment by bibibibi89** [comment]
Will do. Now I know the PR process better.

**Comment by rlubos** [comment]
Thank you @bibibibi89 for the PR :+1:
