### ISSUE TITLE
Zephyr User and Developer Guides - Documentation Generation Instructions Issues

### ISSUE THREAD

**Issue by wu-frances** [zephyrproject-rtos/zephyr#42839]
Encountered 2 issues while following instructions in v2.6.0 Documentation Generation. 
https://docs.zephyrproject.org/2.6.0/README.html#running-the-documentation-processors

1.  #Use cmake to configure a Ninja-based build system
     cmake -GNinja -B_build

Got the following error while performing the step:

CMake Error at /usr/share/cmake-3.22/Modules/FindPaackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Doxygen (missing: dot) (found version “1.8.13”)
Call Stack (most recent call first):
  /usr/share/cmake-3.22/Modules/FidPackageHandleStandardArgs.cmake:594 (_+FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.22/Modules/FindDoxygen.cmake:646 (find_package_handle_standard_args)
  CMakeLists.txt:26 (find_package)

In the very first step while installing tools required to generate documentation, Doxygen was installed, but graphviz was missing.  
Added the following dependency and then retried, the issue was resolved:
   sudo apt-get install graphviz

2. #To generate HTML output, run ninja on the generated build system:
    ninja htmldocs

Got the following error while performing the step:
ninja: error: unknown target ‘htmldocs’

Tried: 
ninja html 
I was able to generate HTML output.

Thanks!

**Comment by gmarull** [comment]
Docs for v2.6.0 used the `htmldocs` target: https://github.com/zephyrproject-rtos/zephyr/blob/zephyr-v2.6.0/doc/Makefile, so documentation is correct for 2.6.0. `main` uses `html` and documentation is up-to-date: https://docs.zephyrproject.org/latest/guides/docs/index.html
