### ISSUE TITLE
it8xxx2_evb: Multiple tests in tests/subsys/portability/cmsis_rtos_v2 fail.

### ISSUE THREAD

**Issue by fuhaolei** [zephyrproject-rtos/zephyr#42847]
**Describe the bug**
portability.cmsis_rtos_v2 : portability.cmsis_rtos_v2.semaphore
portability.cmsis_rtos_v2 : portability.cmsis_rtos_v2.mempool
portability.cmsis_rtos_v2 : portability.cmsis_rtos_v2.mempool_dynamic
portability.cmsis_rtos_v2 : portability.cmsis_rtos_v2.messageq
portability.cmsis_rtos_v2 : portability.cmsis_rtos_v2.event_flags_no_wait_timeout
portability.cmsis_rtos_v2 : portability.cmsis_rtos_v2.event_flags_signalled
portability.cmsis_rtos_v2 : portability.cmsis_rtos_v2.event_flags_isr
portability.cmsis_rtos_v2 : portability.cmsis_rtos_v2.thread_flags_no_wait_timeout
portability.cmsis_rtos_v2 : portability.cmsis_rtos_v2.thread_flags_signalled
portability.cmsis_rtos_v2 : portability.cmsis_rtos_v2.thread_flags_isr
portability.cmsis_rtos_v2 : portability.cmsis_rtos_v2.thread_join
portability.cmsis_rtos_v2 : portability.cmsis_rtos_v2.thread_detached
portability.cmsis_rtos_v2 : portability.cmsis_rtos_v2.thread_joinable_detach
portability.cmsis_rtos_v2 : portability.cmsis_rtos_v2.thread_joinable_terminate

**To Reproduce**
1. cd zephyrproject
2. ./zephyr/scripts/twister -p it8xxx2_evb --device-testing -T zephyr/tests/subsys/portability/cmsis_rtos_v2 --west-flash="../itetool/loader.sh" --device-serial=/dev/ttyUSB0
3. See error

**Logs and console output**
> ***** delaying boot 1ms (per build configuration) *****
*** Booting Zephyr OS build v3.0.0-rc3-2-g8889114e3ca9  (delayed boot 1ms) ***
Running test suite test_cmsis_v2_apis
===================================================================
START - test_kernel_apis
PASS - test_kernel_apis in 0.2 seconds
===================================================================
START - test_delay
PASS - test_delay in 0.3 seconds
===================================================================
START - test_thread_apis
PASS - test_thread_apis in 0.5 seconds
===================================================================
START - test_thread_apis_dynamic
PASS - test_thread_apis_dynamic in 0.5 seconds
===================================================================
START - test_thread_prio
PASS - test_thread_prio in 0.2 seconds
===================================================================
START - test_thread_prio_dynamic
PASS - test_thread_prio_dynamic in 0.2 seconds
===================================================================
START - test_timer
oneshot_callback (Timer 1) = 1
periodic_callback (Timer 2) = 1
periodic_callback (Timer 2) = 2
periodic_callback (Timer 2) = 3
periodic_callback (Timer 2) = 4
periodic_callback (Timer 2) = 5
PASS - test_timer in 0.40 seconds
===================================================================
START - test_mutex
PASS - test_mutex in 0.102 seconds
===================================================================
START - test_mutex_lock_timeout
PASS - test_mutex_lock_timeout in 0.3 seconds
===================================================================
START - test_semaphore
ASSERTION FAIL [thread->base.pended_on] @ WEST_TOPDIR/zephyr/kernel/sched.c:643
E: 
E:  mcause: 2, Illegal instruction
E:   mtval: 0
E:      a0: 80011b68    t0: 00001880
E:      a1: 00000283    t1: 60000000
E:      a2: 00f02705    t2: fffffff5
E:      a3: 00f02700    t3: 00000020
E:      a4: 00000020    t4: 00000006
E:      a5: 00000004    t5: 00dead00
E:      a6: a0000000    t6: 00000004
E:      a7: 0000a000
E:                      tp: aaaaaaaa
E:      ra: 80009762
E:    mepc: 800051f0
E: mstatus: 00001800
E: 
E: >>> ZEPHYR FATAL ERROR 4: Kernel panic on CPU 0
E: Current thread: 0x80101748 (Mutex_check)
E: Halting system

**Environment (please complete the following information):**
 - OS: Ubuntu
 - Toolchain zephyr-sdk-0.13.2
 - Commit 8889114e3ca9

**Comment by hunterhu3000** [comment]
It seems the bug is fixed on the commit 574e166e1357641cb80dda00ff0a01096b6695a0
Please check the log:
```
ztest@ztest-NUC7i7BNH:~/zephyrproject$ ./zephyr/scripts/twister -p it8xxx2_evb --device-testing -T zephyr/tests/subsys/portability/cmsis_rtos_v2 --west-flash="../itetool/loader.sh" --device-serial=/dev/ttyUSB0
Renaming output directory to /home/ztest/zephyrproject/twister-out.2
INFO    - Zephyr version: zephyr-v3.0.0-1332-g574e166e1357
INFO    - JOBS: 4
INFO    - Using 'zephyr' toolchain.
INFO    - Building initial testcase list...
INFO    - 1 test scenarios (1 configurations) selected, 0 configurations discarded due to filters.

Device testing on:

| Platform    | ID   | Serial device   |
|-------------|------|-----------------|
| it8xxx2_evb |      | /dev/ttyUSB0    |

INFO    - Adding tasks to the queue...
INFO    - Added initial list of jobs to queue
INFO    - Total complete:    1/   1  100%  skipped:    0, failed:    0
INFO    - 1 of 1 test configurations passed (100.00%), 0 failed, 0 skipped with 0 warnings in 70.26 seconds
INFO    - In total 23 test cases were executed, 0 skipped on 1 out of total 443 platforms (0.23%)
INFO    - 1 test configurations executed on platforms, 0 test configurations were only built.

Hardware distribution summary:

| Board       | ID   |   Counter |
|-------------|------|-----------|
| it8xxx2_evb |      |         1 |
INFO    - Saving reports...
INFO    - Writing xunit report /home/ztest/zephyrproject/twister-out/twister.xml...
INFO    - Writing xunit report /home/ztest/zephyrproject/twister-out/twister_report.xml...
INFO    - Run completed

```
