### ISSUE TITLE
CONFIG items disappeared in zephyr-3.0-rc3

### ISSUE THREAD

**Issue by zzzh** [zephyrproject-rtos/zephyr#42850]
**Describe the bug**
Some configs disappeared in latest zephyr version, but can not find any description on docs.zephyrproject.org or github of zephyr, I believe this is a documentation bug since it's hard for users of earlier zephyr version to find out what's happening and how to migrate to newer version.

In my case, these configs are:
```
CLOCK_STM32_SYSCLK_SRC_PLL
CLOCK_STM32_PLL_SRC_HSI
CLOCK_STM32_PLL_MULTIPLIER
CLOCK_STM32_AHB_PRESCALER
CLOCK_STM32_APB1_PRESCALER
LOG_MINIMAL
```

All reported as undefined symbol in building.

Please also mention any information which could help others to understand
the problem you're facing:
 - What target platform are you using?   STM32F0
 - What have you tried to diagnose or workaround this issue?     pass the building
 - ...

**To Reproduce**
1. west build for a board that have defconfig file including these config items.

**Expected behavior**
Pass the building
**Impact**
What impact does this issue have on your progress (e.g., annoyance, showstopper)
Can't continue
**Logs and console output**
If applicable, add console logs or other types of debug information
e.g Wireshark capture or Logic analyzer capture (upload in zip archive).
copy-and-paste text and put a code fence (\`\`\`) before and after, to help
explain the issue. (if unable to obtain text log, add a screenshot)
```
myboard_defconfig:37: warning: attempt to assign the value 'y' to the undefined symbol CLOCK_STM32_SYSCLK_SRC_PLL

myboard_defconfig:40: warning: attempt to assign the value 'y' to the undefined symbol CLOCK_STM32_PLL_SRC_HSI

myboard_defconfig:42: warning: attempt to assign the value '12' to the undefined symbol CLOCK_STM32_PLL_MULTIPLIER

myboard_defconfig:43: warning: attempt to assign the value '1' to the undefined symbol CLOCK_STM32_AHB_PRESCALER

myboard_defconfig:44: warning: attempt to assign the value '2' to the undefined symbol CLOCK_STM32_APB1_PRESCALER

myboard_path/prj.conf:11: warning: attempt to assign the value 'y' to the undefined symbol LOG_MINIMAL
```
\\\

**Environment (please complete the following information):**
 - OS: (e.g. Linux, MacOS, Windows)   Linux
 - Toolchain (e.g Zephyr SDK, ...)         Zephyr SDK
 - Commit SHA or Version used         zephyr-3.0-rc3

**Additional context**
Add any other context that could be relevant to your issue, such as pin setting,
target configuration, ...

**Comment by zzzh** [comment]
I think there should be an obsolete folder inside doc folder in zephyr, which contain files that explain obsoleted things, so that people can find out what happened by a searching for the obsoleted configs and names.

**Comment by zzzh** [comment]
For this case, I found some words that are close to the configs I have trouble with in some c files(but not in any config files):
STM32_SYSCLK_SRC_PLL
STM32_PLL_SRC_HSI
STM32_PLL_MULTIPLIER
STM32_AHB_PRESCALER
STM32_APB1_PRESCALER
Though, after changing the configs to these names, they are warned to be malformed line and at last become an error.

Any ideas?

**Comment by carlescufi** [comment]
@erwango still time to add a release note regarding the configs above?

**Comment by erwango** [comment]
@carlescufi That was one day short, but I can push a fix today

**Comment by erwango** [comment]
@zzzh These clock configuration bit were moved to device tree, see https://github.com/zephyrproject-rtos/zephyr/pull/34120.
The mentionned Kconfig symbols were removed after deprecation period, but I'll add a word in the release note.
