### ISSUE TITLE
Bluetooth: Controller: Group auxiliary PDU transmissions

### ISSUE THREAD

**Issue by cvinayak** [zephyrproject-rtos/zephyr#42885]
**Is your enhancement proposal related to a problem? Please describe.**
When scheduling Extended Advertising and Periodic Advertising PDUs, group them together to optimise any fragmentation over the time line, this will allow better management of overlapping radio events.

**Describe the solution you'd like**
Use advanced scheduling using ticker APIs to group radio events.

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by kruithofa** [comment]
This is implemented as proven by successful conformance tests
