### ISSUE TITLE
Bluetooth: Controller: Extended Advertising: AD data fragmentation

### ISSUE THREAD

**Issue by cvinayak** [zephyrproject-rtos/zephyr#42889]
**Is your enhancement proposal related to a problem? Please describe.**

Spec wants to send 251 octets of data
A minimum of 191 can go in the first packet, the rest must be in CHAIN_IND PDU

This is fragmenting and sending fragments

Framework for handling chained PDUs is in place and used by direction finding

Todo:

- reuse framework for chained PDUs and add advertising data
- implement ISR to handle back-to-back TX similar to what is in periodic advertising
- populate PDUs by fragmenting the AD data: AD data can be 251 bytes, which may not fit in a PDU due to overhead in PDU
- filling the auxiliary pointer offset of the PDUs
- implement babblesim tests (using host)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context or graphics (drag-and-drop an image) about the feature request here.

**Comment by kruithofa** [comment]
This is implemented by PR #48491
