### ISSUE TITLE
Bluetooth: Controller: CIG: LE CIS Request Event

### ISSUE THREAD

**Issue by cvinayak** [zephyrproject-rtos/zephyr#42897]
**Is your enhancement proposal related to a problem? Please describe.**
A clear and concise description of what the problem is.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context or graphics (drag-and-drop an image) about the feature request here.

**Comment by erbr-ot** [comment]
This is implemented as part of PR43023 and subsequent fixup PRs
