### ISSUE TITLE
Bluetooth: Controller: CIG: LL Reject: Local initiated being rejected

### ISSUE THREAD

**Issue by cvinayak** [zephyrproject-rtos/zephyr#42904]
**Is your enhancement proposal related to a problem? Please describe.**
A clear and concise description of what the problem is.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context or graphics (drag-and-drop an image) about the feature request here.

**Comment by mtpr-ot** [comment]
Supposedly implemented in #52147. Will need testing to verify correct behavior.

**Comment by cvinayak** [comment]
Manually tested using central_iso sample to try create second CIS  to peripheral_iso sample which rejects it in `iso_accept` callback. The behavior is as expected.
