### ISSUE TITLE
Bluetooth: Controller: CIG: LE Remove CIG

### ISSUE THREAD

**Issue by cvinayak** [zephyrproject-rtos/zephyr#42908]
**Is your enhancement proposal related to a problem? Please describe.**
A clear and concise description of what the problem is.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context or graphics (drag-and-drop an image) about the feature request here.

**Comment by mtpr-ot** [comment]
Fixed by #52147
