### ISSUE TITLE
it8xxx2_evb: Test in tests/kernel/timer/timer_api fail.

### ISSUE THREAD

**Issue by fuhaolei** [zephyrproject-rtos/zephyr#42953]
**Describe the bug**
kernel.timer : kernel.timer.timer_duration_period

**To Reproduce**
1. cd zephyrproject
2. ./zephyr/scripts/twister -p it8xxx2_evb --device-testing -T zephyr/tests/kernel/timer/timer_api --west-flash="../itetool/loader.sh" --device-serial=/dev/ttyUSB0
3. See error

**Logs and console output**
> ***** delaying boot 1ms (per build configuration) *****
*** Booting Zephyr OS build v3.0.0-rc3-36-g35ec3c957992  (delayed boot 1ms) ***
Running test suite timer_api
===================================================================
START - test_time_conversions
PASS - test_time_conversions in 0.118 seconds
===================================================================
START - test_timer_duration_period
Assertion failed at WEST_TOPDIR/zephyr/tests/kernel/timer/timer_api/src/main.c:195: test_timer_duration_period: tdata.expire_cnt == 4 is false
FAIL - test_timer_duration_period in 0.339 seconds
===================================================================
START - test_timer_restart
PASS - test_timer_restart in 0.276 seconds
===================================================================
START - test_timer_period_0
PASS - test_timer_period_0 in 0.202 seconds
===================================================================
START - test_timer_period_k_forever
PASS - test_timer_period_k_forever in 0.202 seconds
===================================================================
START - test_timer_expirefn_null
PASS - test_timer_expirefn_null in 0.326 seconds
===================================================================
START - test_timer_periodicity

**Environment (please complete the following information):**
 - OS: Ubuntu
 - Toolchain zephyr-sdk-0.13.2
 - Commit 35ec3c957992

**Comment by Dino-Li** [comment]
@fuhaolei , @Zhaoningx , the PR fixed this issue.
