### ISSUE TITLE
Media control initialization

### ISSUE THREAD

**Issue by asbjornsabo** [zephyrproject-rtos/zephyr#42965]
The initialization of media control service and media player must be cleaned up.
Currently, the player initializes the service.  But the service may not be present, in which case initialization fails.
Only initialize if the service is present?

2022-07-12: The MPL should probably never initialize the service.

**Comment by carlescufi** [comment]
@asbjornsabo please add labels, at least "Bluetooth" and "Bluetooth Audio".

**Comment by kruithofa** [comment]
This is obsolete after the refactoring
