### ISSUE TITLE
Release notes v3.0.0 sign off - Drivers and sensors

### ISSUE THREAD

**Issue by dkalowsk** [zephyrproject-rtos/zephyr#42977]
Looking for sign off on the v3.0.0 release notes for drivers and sensors.

**Comment by mnkp** [comment]
The GPIO drivers section looks correct.

**Comment by dkalowsk** [comment]
Thanks @mnkp .  Any others on this list ready to give a sign off?  If we're all good we can close the issue.

**Comment by dkalowsk** [comment]
Release channel recommending closing the issues.
