### ISSUE TITLE
Release Notes v3.0.0 sign off - Devicetree

### ISSUE THREAD

**Issue by dkalowsk** [zephyrproject-rtos/zephyr#42976]
Looking for sign off of the v3.0.0 release notes on the devicetree.

**Comment by mbolivar-nordic** [comment]
https://github.com/zephyrproject-rtos/zephyr/pull/42989 contains the rest of the API changes that are worth mentioning in my opinion. Then I'm ready to sign-off. I think it's probably no longer worthwhile to track bindings changes.
