### ISSUE TITLE
Release notes v3.0.0 sign off - Filesystems

### ISSUE THREAD

**Issue by dkalowsk** [zephyrproject-rtos/zephyr#42978]
Looking for sign off on the v3.0.0 release notes for file systems.

**Comment by de-nordic** [comment]
@dkalowsk Can you point me to some procedure, in documentation, for this? Thanks.

**Comment by dkalowsk** [comment]
@de-nordic was trying to use the tooling GitHub provides for this.  If you're good with the release-notes just close the issue.

**Comment by dkalowsk** [comment]
Release channel recommending closing the issues.
