### ISSUE TITLE
Release Notes v3.0.0 sign off - Build and infrastructure

### ISSUE THREAD

**Issue by dkalowsk** [zephyrproject-rtos/zephyr#42975]
Looking for sign off on the build and infrastructure portion of the release notes for v3.0

**Comment by tejlmand** [comment]
LGTM, no big work made it into 3.0.
Would like a second person to check before closing this.

**Comment by dkalowsk** [comment]
@nashif or @galak either of you want to double check?

**Comment by dkalowsk** [comment]
Release channel recommending closing the issues.
