### ISSUE TITLE
twister: error while executing twister script on windows machine for sample example code

### ISSUE THREAD

**Issue by enthunilu** [zephyrproject-rtos/zephyr#43057]
**Describe the bug**
On executing twister script on windows machine, getting below error

  File "scripts/twister", line 195
    print(f'ZEPHYR_BASE unset, using "{ZEPHYR_BASE}"')
                                                    ^
SyntaxError: invalid syntax

**To Reproduce**
1. Clone zephyr version 2.7 or nrf sdk v1.8 ( on both I am getting issue ) 
2. open command prompt and navigate to zephyr source directory
2. cmd: python scripts/twister -T samples/hello_world
or 
cmd: python scripts/twister -p nrf52840dk_nrf52840 -T samples/hello_world
or
python scripts/twister -p nrf52840dk_nrf52840 -T samples/hello_world --ninja --build-only
3. See error

**Logs and console output**
  File "scripts/twister", line 195
    print(f'ZEPHYR_BASE unset, using "{ZEPHYR_BASE}"')
                                                    ^
SyntaxError: invalid syntax

**Environment (please complete the following information):**
 - OS: Windows
 - Toolchain nrf sdk 
 - Zephyr Version: 2.7

**Comment by carlescufi** [comment]
You are using Python 2, twister requires Python at least 3.7.
