### ISSUE TITLE
[Slack] Slack invite works only on very few mail addresses - this should be changed!

### ISSUE THREAD

**Issue by walterchris** [zephyrproject-rtos/zephyr#43081]
Hi everyone,
Currently the slack invite only works with the following mail addresses:
```
You can use any account with the domain:
intel.com
linaro.com
linux.intel.com
nordicsemi.no
nxp.com
oticon.com
foundries.io
ti.com
synopsys.com
antmicro.com
sifive.com
teenage.engineering
lairdconnect.com
adafruit.com
eclipse-foundation.org
google.com
chromium.org
windriver.com
```
Why are we so closed here? Any particular reason? I'd like to join the conversation on Slack, however I am unable to register!

Best,
Chris

**Comment by stephanosio** [comment]
We are no longer using Slack. Please use Discord.
