### ISSUE TITLE
Request for support to maintaining hal_silabs

### ISSUE THREAD

**Issue by chrta** [zephyrproject-rtos/zephyr#43139]
**Issue**

There is no maintainer for SiLabs platforms and especially https://github.com/zephyrproject-rtos/hal_silabs
@galak did a most of the "high level" work in hal_silabs to ensure that the licenses are fine and the general code structure is ok.

It would really be good is someone closer to the TSC could step up and do this for SiLabs code. I can still do some code reviews, but i would also like some feedback if the code is worth to be reviewed and i do not spend time on code that will not be merged anyway.

It would also be good if additional collaborators could be found for SiLabs, since i do not have time to review the big pending changes like https://github.com/zephyrproject-rtos/hal_silabs/pull/13 thoroughly or in a timely manner.

Side note: I am not actively developing for SiLabs any more, so my focus change away from this platform within the last years.

**Comment by chrta** [comment]
@mbolivar

**Comment by mbolivar-nordic** [comment]
We are formalizing ownership of HALs in the process working group; I will be sure to mark this HAL as only receiving odd fixes.

**Comment by henrikbrixandersen** [comment]
@chrta Have you considered "advertising" for more maintainers on the developers mailing list?

**Comment by chrta** [comment]
@henrikbrixandersen I have not done it, yet. It is probably a good idea to ask for maintainers and collaborators also for the SiLabs code in the main repository, not only the hal.

**Comment by rettichschnidi** [comment]
I will let my contact at SiLabs know about this issue.

**Comment by rettichschnidi** [comment]
Or maybe @conq could help us here?

**Comment by chrta** [comment]
Related comment from @sateeshkotapati (Silicon Labs developer) offering to maintain SiLabs code: https://github.com/zephyrproject-rtos/zephyr/pull/35361#issuecomment-986866047

**Comment by conq** [comment]
We're working on finding dedicated resources for Zephyr as we speak :)

**Comment by mbolivar-nordic** [comment]
@conq any updates?

**Comment by conq** [comment]
Yes, this is getting staffed. I've asked the team to pipe up and let people know that we're taking ownership of this code.
