### ISSUE TITLE
Ethernet and PPP communication conflicts

### ISSUE THREAD

**Issue by maweicoltsmart** [zephyrproject-rtos/zephyr#43142]
The PCB I designed myself has an Ethernet interface and a GSM PPP interface. My application creates a UDP connection, this UDP connection can correctly receive and send data through Ethernet before PPP gets IP, but after PPP gets IP, this UDP connection can only receive data, but cannot send data , I'm guessing that the data may be sent from PPP. Is there any way to solve this situation of multiple network card communication?

**Comment by rlubos** [comment]
I'm assuming you're using socket interface? You could use `SO_BINDTODEVICE` socket option to bind your socket to a specific network interface.

**Comment by maweicoltsmart** [comment]
@rlubos 
Thanks, the problem has been solved with the suggestion you gave. Thanks again!
