### ISSUE TITLE
LE Audio: Avoid hardcoding context type for LC3 macros

### ISSUE THREAD

**Issue by Thalley** [zephyrproject-rtos/zephyr#43202]
**Is your enhancement proposal related to a problem? Please describe.**
The `BT_CODEC_LC3_CONFIG_*` macros have a hardcoded context type, which doesn't really make any sense. 

**Describe the solution you'd like**
I see 3 options:
1. The context type should be removed from `BT_CODEC_LC3_CONFIG_*` and thus also from `BT_CODEC_LC3_CONFIG`
2. The context type becomes a parameter to `BT_CODEC_LC3_CONFIG_*`
3. The `BT_CODEC_LC3_CONFIG_*` should be removed and users should use `BT_CODEC_LC3_CONFIG` directly

**Describe alternatives you've considered**
See above

**Additional context**
N/A

**Comment by Casper-Bonde-Bose** [comment]
Also the LC3 part of the macros should be removed, as they have been "upgraded" to Generic Audio - hence _can_ be used for any codec.
