### ISSUE TITLE
BLE: With BT_SETTINGS and BT_SMP, second connection blocks the system in connection event notification

### ISSUE THREAD

**Issue by eloisesko** [zephyrproject-rtos/zephyr#43203]
**Describe the bug**
A second BLE connection event makes a circular reference on 'gatt_conn_cb' in linked list `callback_list` (conn.c), blocking the system in event notification (infinite loop).

This is due to the fact that the function `bt_gatt_connected` (gatt.c) can register multiple times the `gatt_conn_cb` object with `bt_conn_cb_register`  [here]( https://github.com/zephyrproject-rtos/zephyr/blob/zephyr-v3.0.0/subsys/bluetooth/host/gatt.c#L5103) if CONFIG_BT_SETTINGS and CONFIG_BT_SMP are enabled.

**To Reproduce**
1. Enable CONFIG_BT_SETTINGS  and CONFIG_BT_SMP 
2. Make a first BLE connection and disconnect
3. Make a second BLE connection

**Expected behavior**
The gatt_conn_cb callback should not be registered twice

**Impact**
The system is blocked in infinite loop.

**Logs and console output**

**Environment (please complete the following information):**

**Additional context**

**Comment by petejohanson** [comment]
I've just hit this very bug when working on the 3.0 update for https://github.com/zmkfirmware/zmk/

We use multiple connections for our split keyboards, and our central side if getting into this infinite loop.
