### ISSUE TITLE
UART console broken since 099850e916ad86e99b3af6821b8c9eb73ba91abf

### ISSUE THREAD

**Issue by henrikbrixandersen** [zephyrproject-rtos/zephyr#43205]
**Describe the bug**
The UART console on my `stm32f3_disco`, `twr_ke18f` and even `qemu_cortex_m0` boards is no longer functional (doesn't accept keystrokes, sometimes receives gibberish) since commit 099850e916ad86e99b3af6821b8c9eb73ba91abf (as revealed by `git bisect`).

**To Reproduce**
1. west build -b qemu_cortex_m0-s samples/hello_world/ -- -DCONFIG_SHELL=y
2. west run
3. Start typing on the console

**Expected behavior**
Console should accept keystrokes.

**Impact**
Serial console not usable.

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: Zephyr SDK 0.13.1
 - Commit SHA: 3470ace98d4dae4918cf74491c07d74ad69d3559

**Comment by henrikbrixandersen** [comment]
Commit 099850e916ad86e99b3af6821b8c9eb73ba91abf  was introduced in #42845.

**Comment by carlescufi** [comment]
@npitre no need for hardware, you can use `qemu_cortex_m0` to reproduce.
@nordic-krch FYI

**Comment by npitre** [comment]
FYI I reproduced the issue. I'm digging.
Seems to affect modem drivers too.

**Comment by npitre** [comment]
The fix is in PR #43226.
