### ISSUE TITLE
nvs: change nvs_init to accept a device reference

### ISSUE THREAD

**Issue by gmarull** [zephyrproject-rtos/zephyr#43229]
## Introduction

`nvs_init()` now accepts the name of a flash device, forcing the usage of `device_get_binding()`. This adds unnecessary runtime overhead when the flash device can be obtained at compile time, e.g. with `DEVICE_DT_GET()`.

### Problem description

The NVS API is marked as stable, the proposed change would break all direct users of the NVS API. However, the change has low impact (a single API call).

### Proposed change

Change `nvs_init()` to be like:

```c
/**
 * @brief nvs_init
 *
 * Initializes a NVS file system in flash.
 *
 * @param fs Pointer to file system
 * @param dev Pointer to flash device
 * @retval 0 Success
 * @retval -ERRNO errno code if error
 */
int nvs_init(struct nvs_fs *fs, const struct device *dev);
```

## Detailed RFC

https://github.com/zephyrproject-rtos/zephyr/pull/43220
https://github.com/zephyrproject-rtos/zephyr/pull/43260

### Proposed change (Detailed)

N/A

### Dependencies

Settings NVS backend

### Concerns and Unresolved Questions

N/A

## Alternatives

- Deprecate `nvs_init()`
- Create `nvs_mount()`, an equivalent to `nvs_init()` that expects `.flash_device` to be initialized.

**Comment by Laczen** [comment]
@gmarull, maybe it is better to create a `nvs_mount(struct nvs_fs *fs)` routine that does not take an argument. The flash_dev can then be set prior to a call to `nvs_mount` and `nvs_init` can set the device based on the name.
