### ISSUE TITLE
net: tcp.c: prepare_segment() may leak fragments in case of error

### ISSUE THREAD

**Issue by pfalcon** [zephyrproject-rtos/zephyr#4323]
Continuing from https://github.com/zephyrproject-rtos/zephyr/issues/4292#issuecomment-336139174 :

prepare_segment() has code like: https://github.com/zephyrproject-rtos/zephyr/blob/master/subsys/net/ip/tcp.c#L346 , which means that in case of early error return (e.g. https://github.com/zephyrproject-rtos/zephyr/blob/master/subsys/net/ip/tcp.c#L384), the original fragment chain of incoming packet will be lost and leaked.

**Comment by jukkar** [comment]
Is there still some issue with this, I thought this was fixed by #4292 or is the bug description wrong.

**Comment by pfalcon** [comment]
No, this wasn't fixed by #4292, this is a separate issue, and the title and description are correct.

I'd say, this waits triaging by the maintainers, to confirm the issue and priority of "high".

**Comment by linkmeyer** [comment]
@jukkar , @tbursztyka , what's the status?

**Comment by jukkar** [comment]
The #4907 looks like a perfect match that would fix this.
