### ISSUE TITLE
Deprecate DT_CHOSEN_ZEPHYR_ENTROPY_LABEL

### ISSUE THREAD

**Issue by gmarull** [zephyrproject-rtos/zephyr#43230]
## Introduction

Deprecate the helper macro `DT_CHOSEN_ZEPHYR_ENTROPY_LABEL`, mainly used together with `device_get_binding()` to promote usage of `DEVICE_DT_GET()`.

### Problem description

Usage of `device_get_binding()` is being replaced with `DEVICE_DT_GET()` in most cases because device reference can be resolved at compile time. In this situation, `DT_CHOSEN_ZEPHYR_ENTROPY_LABEL` becomes less relevant or unused. Other similar macros have also been deleted for the same reason. This change should have low impact since `DT_LABEL(DT_CHOSEN(zephyr_entropy))` can still be used with the exact same behavior.

### Proposed change

Deprecate `DT_CHOSEN_ZEPHYR_ENTROPY_LABEL`.

## Detailed RFC

Deprecate `DT_CHOSEN_ZEPHYR_ENTROPY_LABEL`.

### Proposed change (Detailed)

https://github.com/zephyrproject-rtos/zephyr/pull/43221

### Dependencies

All in-tree users of this helper macro.

### Concerns and Unresolved Questions

N/A

## Alternatives

List any alternatives considered, and the reasons for choosing this option
over them.

**Comment by mbolivar-nordic** [comment]
+1
