### ISSUE TITLE
GitHub settings: Update topics

### ISSUE THREAD

**Issue by beriberikix** [zephyrproject-rtos/zephyr#43245]
This repo already has a few [topics](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/classifying-your-repository-with-topics) and at the time of writing they are:
- `iot`
- `real-time`
- `microcontroller`
- `embedded`
- `mcu`
- `rtos`

Notably missing is [`zephyr-rtos`](https://github.com/topics/zephyr-rtos), [`zephyr`](https://github.com/topics/zephyr) & [`zephyros`](https://github.com/topics/zephyros). I propose we at least add those at this time as they will help with searching, especially for related repos. 

There's no penalty for adding many relevant topics and we may consider adding additional ones like supported architectures. For example, see PlatformIO's topic list:
![image](https://user-images.githubusercontent.com/178376/155851621-e4372e34-9f8d-41f2-be8b-58302a6d1938.png)

**Comment by beriberikix** [comment]
I submitted `zephyr-rtos`, `zephyros` & `zephyr` to GitHub as an official topic and it is now merged . You can see right now that PlatformIO is the first result. It would be beneficial to add these topics to include the official project in search results :)

![image](https://user-images.githubusercontent.com/178376/156561577-52c3c96e-03f0-4914-9236-bf56a82cd977.png)

**Comment by henrikbrixandersen** [comment]
@stephanosio Does this fall under your umbrella?

**Comment by stephanosio** [comment]
> @stephanosio Does this fall under your umbrella?

I would like to get some feedback from others before proceeding with it.

cc @bprestonlf @kestewart @nashif @carlescufi @MaureenHelm @galak @gmarull or anyone else highly involved with the project

**Comment by carlescufi** [comment]
Done, I updated the topics with a few select ones. Should do for now.
