### ISSUE TITLE
Bluetooth: Host: Deadlock with Mesh and Ext Adv on native_posix

### ISSUE THREAD

**Issue by LingaoM** [zephyrproject-rtos/zephyr#43246]
Use native_posix as Bluetooth Mesh Demo
Use Another board as Controller，attach to host.

Note：EXT_ADV used.

https://github.com/zephyrproject-rtos/zephyr/blob/main/drivers/bluetooth/hci/userchan.c#L67
Not Mark discardable flag, cause deadlock.

May be introduce by https://github.com/zephyrproject-rtos/zephyr/pull/41337

@hermabe CC

**Comment by Thalley** [comment]
@LingaoM Can you please provide more information, as requested by the bug report template?

How exactly can this be reproduced? Any logs you can share? What commit SHA are you on?

**Comment by LingaoM** [comment]
@Thalley  https://github.com/zephyrproject-rtos/zephyr/commit/8b54f08a690e2817be111ed43cd33ec05dfe25b3

**Comment by LingaoM** [comment]
`rx.hdr[sizeof(*hdr)] == BT_HCI_EVT_LE_EXT_ADVERTISING_REPORT)` has been removed by https://github.com/zephyrproject-rtos/zephyr/pull/41337 cause deadlock https://github.com/zephyrproject-rtos/zephyr/issues/30955

**Comment by hermabe** [comment]
Extended advertising reports cannot be discarded as the host needs to do reassembly of long advertising data. Legacy advertising reports can be discarded because each report is complete.

**Comment by LingaoM** [comment]
From the current design, whether discarded or not, there will be problems, so it needs to be reconstructed

**Comment by Thalley** [comment]
> From the current design, whether discarded or not, there will be problems, so it needs to be reconstructed

Can you elaborate more on how/why it is causing a deadlock?

**Comment by LingaoM** [comment]
The Bluetooth receiving thread may not be able to process broadcast
packets because the system API(bt_hci_cmd_send_sync) is in block state.
If HCI driver is still waiting buffer for adv report, an assertion will
be triggered.

**Comment by Thalley** [comment]
> The Bluetooth receiving thread may not be able to process broadcast packets because the system API(bt_hci_cmd_send_sync) is in block state. If HCI driver is still waiting buffer for adv report, an assertion will be triggered.

Ah, so the `bt_hci_cmd_send_sync` can not finish because the event RX buffers are full of adv reports? 

But as @hermabe said, the extended advertising reports cannot be discarded that easily anymore, and doesn't the same issue exist for any other event unsolicited event (including PA reports as well)? 

We current have a system with 2 priorities for events that somewhat handles this. Perhaps we need a 3rd priority, such that 
Highest priority: Disconnect events etc.
Medium priority: Events from commands
Lowest priority: Events from scanning/PA syncs

**Comment by cvinayak** [comment]
@LingaoM  and @Thalley have you had any progress here?

**Comment by Thalley** [comment]
> @LingaoM and @Thalley have you had any progress here?

I have not looked more into this

**Comment by PavelVPV** [comment]
@LingaoM is this still an issue? Could you re-check?

**Comment by LingaoM** [comment]
Closed
