### ISSUE TITLE
wifi: esp_at: shell command "wifi scan" not working well

### ISSUE THREAD

**Issue by pbatiot** [zephyrproject-rtos/zephyr#43305]
**Describe the bug**
The shell command "wifi scan" doesn't print every wifi AP available when used by esp-at driver

**To Reproduce**
To launch the wifi sample with esp-at driver :
1. Connect your board to ESP32 board. I used a ST board b_u585i_iot02a connected to esp32-c3-devkitC, through UART3.
2. Create overlay file : zephyr/samples/net/wifi/boards/b_u585i_iot02a.overlay containing
"&usart3 {
	pinctrl-0 = <&usart3_tx_pd8 &usart3_rx_pd9>;
	pinctrl-names = "default";
	current-speed = <115200>;
	status = "okay";
	
    espressif,esp-at {
	label = "Driver AT for ESP32-C3";
        compatible = "espressif,esp-at";
    };
};"
4. Modify zephyr/samples/net/wifi/prj.conf : 
    - Remove line 4: CONFIG_TEST_RANDOM_GENERATOR=y
    - add lines "CONFIG_NET_TCP_ISN_RFC6528=n" and "CONFIG_WIFI_ESP_AT=y"
5. west build -b b_u585i_iot02a platform/zephyr/samples/net/wifi/ -p
6. west flash -r openocd

**Expected behavior**
Every wifi AP detected by esp32-c3-devkitC should be printed on zephyr shell.

**Impact**
annoyance, I need this functionnality for tests

**Logs and console output**
The zephyr shell prints :
"
uart:~$ *** Booting Zephyr OS build v2.7.99-2259-ge9f6e05b5a97  ***
Connected
Disconnected
uart:~$ wifi scan

Scan requested

Num  | SSID                             (len) | Chan | RSSI | Sec      | MAC
1    | SFR_1985                         8     | 1    | -50  | WPA/WPA2 |
2    | FreeWifi_secure                  15    | 11   | -87  | WPA/WPA2 |
3    |                                  0     | 11   | -88  | WPA/WPA2 |
4    | FreeWifi                         8     | 11   | -89  | Open     |
Scan request done
"

I am able to spy the AT communication between esp32-c3-devkitC and the ST board
On the AT link the anwser of esp32-c3-devkitC is 
"+CWLAP:(2,"SFR_1985",-50,1)
+CWLAP:(2,"Livebox-642C",-85,1)
+CWLAP:(0,"SFR WiFi FON",-85,6)
+CWLAP:(5,"SFR WiFi Mobile",-87,6)
+CWLAP:(4,"SFR_3838",-87,6)
+CWLAP:(2,"freebox_XEGBMZ",-87,11)
+CWLAP:(5,"FreeWifi_secure",-87,11)
+CWLAP:(3,"",-88,11)
+CWLAP:(0,"FreeWifi",-89,11)
"

-> so we can see that some lines have been dropped

**Environment (please complete the following information):**
 - OS: WSL in windows 10

**Comment by pbatiot** [comment]
I have been able to solve the bug with this workarround :

```
diff --git a/subsys/net/l2/wifi/wifi_shell.c b/subsys/net/l2/wifi/wifi_shell.c
index 5a8bb3e9cb..c00893139e 100644
--- a/subsys/net/l2/wifi/wifi_shell.c
+++ b/subsys/net/l2/wifi/wifi_shell.c
@@ -31,6 +31,7 @@ LOG_MODULE_REGISTER(net_wifi_shell, LOG_LEVEL_INF);
                                NET_EVENT_WIFI_CONNECT_RESULT |         \
                                NET_EVENT_WIFI_DISCONNECT_RESULT)

+#define WIFI_SCAN_RESULT_MAX 20
 static struct {
        const struct shell *shell;

@@ -49,6 +50,8 @@ static uint32_t scan_result;

 static struct net_mgmt_event_callback wifi_shell_mgmt_cb;

+static struct wifi_scan_result wifi_scan_result_list[WIFI_SCAN_RESULT_MAX];
+
 #define print(shell, level, fmt, ...)                                  \
        do {                                                            \
                if (shell) {                                            \
@@ -62,11 +65,15 @@ static void handle_wifi_scan_result(struct net_mgmt_event_callback *cb)
 {
        const struct wifi_scan_result *entry =
                (const struct wifi_scan_result *)cb->info;
-       uint8_t mac_string_buf[sizeof("xx:xx:xx:xx:xx:xx")];
+       /*uint8_t mac_string_buf[sizeof("xx:xx:xx:xx:xx:xx")];*/
+
+       if (scan_result<WIFI_SCAN_RESULT_MAX) {
+               memcpy(&wifi_scan_result_list[scan_result], entry, sizeof(struct wifi_scan_result));
+       }

        scan_result++;

-       if (scan_result == 1U) {
+       /*if (scan_result == 1U) {
                print(context.shell, SHELL_NORMAL,
                      "\n%-4s | %-32s %-5s | %-4s | %-4s | %-5s    | %s\n",
                      "Num", "SSID", "(len)", "Chan", "RSSI", "Sec", "MAC");
@@ -77,7 +84,7 @@ static void handle_wifi_scan_result(struct net_mgmt_event_callback *cb)
              (entry->security == WIFI_SECURITY_TYPE_PSK ? "WPA/WPA2" : "Open    "),
              ((entry->mac_length) ?
                      net_sprint_ll_addr_buf(entry->mac, WIFI_MAC_ADDR_LEN, mac_string_buf,
-                                            sizeof(mac_string_buf)) : ""));
+                                            sizeof(mac_string_buf)) : ""));*/
 }

 static void handle_wifi_scan_done(struct net_mgmt_event_callback *cb)
@@ -85,13 +92,29 @@ static void handle_wifi_scan_done(struct net_mgmt_event_callback *cb)
        const struct wifi_status *status =
                (const struct wifi_status *)cb->info;

+       uint8_t mac_string_buf[sizeof("xx:xx:xx:xx:xx:xx")];
+
        if (status->status) {
                print(context.shell, SHELL_WARNING,
                      "Scan request failed (%d)\n", status->status);
        } else {
+               for (int i=0; i<scan_result; i++) {
+                       if (i == 0U) {
+                               print(context.shell, SHELL_NORMAL,
+                                       "\n%-4s | %-32s %-5s | %-4s | %-4s | %-5s    | %s\n",
+                                       "Num", "SSID", "(len)", "Chan", "RSSI", "Sec", "MAC");
+                       }
+                       print(context.shell, SHELL_NORMAL, "%-4d | %-32s %-5u | %-4u  | %-4d| %-5s | %s\n",
+                               i, wifi_scan_result_list[i].ssid, wifi_scan_result_list[i].ssid_length,
+                               wifi_scan_result_list[i].channel, wifi_scan_result_list[i].rssi,
+                               (wifi_scan_result_list[i].security == WIFI_SECURITY_TYPE_PSK ? "WPA/WPA2" : "Open    "),
+                               ((wifi_scan_result_list[i].mac_length) ?
+                                       net_sprint_ll_addr_buf(wifi_scan_result_list[i].mac, WIFI_MAC_ADDR_LEN, mac_string_buf,
+                                                               sizeof(mac_string_buf)) : ""));
+               }
                print(context.shell, SHELL_NORMAL, "Scan request done\n");
        }
-
+
        scan_result = 0U;
 }

```

**Comment by carlescufi** [comment]
@pbatiot thanks for the report, please consider opening a Pull Request with the workaround you posted.

**Comment by sylvioalves** [comment]
@mniestroj Would you take a look?

**Comment by mniestroj** [comment]
@pbatiot Could you see if increasing `NET_MGMT_EVENT_QUEUE_SIZE` Kconfig option solves your problem? Set it to value that is higher than the number of WiFi networks you are expecting.

**Comment by pbatiot** [comment]
@mniestroj Your solution works. 
I put `CONFIG_NET_MGMT_EVENT_QUEUE_SIZE=20` in prj.conf, now i am not missing any wifi in the printed list.
As you have said, the queue size must be higher than the number of WiFi networks expected, to avoid dropping some. 
I will close the issue, the correct configuration of the queue size is what i needed. 
Thanks Marcin
