### ISSUE TITLE
RFC: Bring zcbor as CBOR decoder/encoder in replacement for TinyCBOR

### ISSUE THREAD

**Issue by de-nordic** [zephyrproject-rtos/zephyr#43333]
## Origin

zcbor https://github.com/NordicSemiconductor/zcbor

## Purpose

In replacement of  the current heavily-modified TinyCBOR fork we use as a CBOR encoder/decoder.
zcbor is a light CBOR encoder/decoder with, optional, capability of generating decoding code from CDDL descriptions of data structures.
Our TinyCBOR fork will then be deprecated and removed in time.

## Mode of integration

As a module: it is easier to maintain and update with patches from the origin.
Module path would be modules/lib/zcbor

## Pull Request

** THIS IS WORK IN PROGRESS **
The zcbor module Kconfig and cmake recipe:
https://github.com/zephyrproject-rtos/zephyr/pull/43332

## Description

Currently the only user of CBOR encoder/decoder within Zephyr is mcumgr. The encoder we use is custom version of TinyCBOR.
Complete discussion on TinyCBOR replacement, on what are possible alternatives and reasons is present here https://github.com/zephyrproject-rtos/zephyr/issues/40591

In general we are trying to replace hard to update non vanilla fork of TinyCBOR with lightweight, simpler and easier to maintain variant zcbor.

# Dependencies

This is standalone project and depends only on C compiler.
Additional and optional feature of auto generating decoding source is dependent on python interpreter.

## Revision

The newest commit on main:
https://github.com/NordicSemiconductor/zcbor/commit/942ae07b0d94168526ceb85bf1d0f18deaf2d482

## License

As stated here: https://github.com/NordicSemiconductor/zcbor/blob/main/LICENSE
is Apache v2.

**Comment by carlescufi** [comment]
Approved by the TSC
