### ISSUE TITLE
Automatic Automated Backports?

### ISSUE THREAD

**Issue by cfriedt** [zephyrproject-rtos/zephyr#43335]
**Is your enhancement proposal related to a problem? Please describe.**
Even though there is already a fair bit of automation for backports, it still relies on the manual step of applying backport tags such as `backport v2.7-branch`. At that point, a backport PR is created. With the volume of bugfixes that go into main, it is difficult for maintainers and release managers to see *all* of the candidate PRs that should be backported. It is quite possible that some `bug` PRs **should be backported but have been missed**.

**Describe the solution you'd like**
The vast majority of backports are legitimate and end up being merged into release branches. With that, it makes sense to automatically consider **every** `bug` PR that has been merged into `main` as a backport candidate. Then, the minority of backport candidates that should not be backported can be manually filtered-out.

This will rely on continued strong differentiation between bugs and feature enhancements on the part of the release / bug triage team. Of course, **all** backport candidate PRs should continue to be audited, but the process of creating them can be fully automated.

Propose running a script on a weekly basis to look at `bug` PRs that have *already* been merged into `main`.

Within the script, run the following approximate steps:
* For each supported release branch, check the PR merge date against the date the branch was made
* if merge date > branch date, add tag to PR for backport to branch

It's possible that there may be additional steps necessary for security-related backports.

There may be the occasional non-bugfix PR that **also** should be backported if it satisfies the criteria for "improving general stability". Since these represent a very small minority of backport candidates, it's acceptable to leave this as a manual process.

**Describe alternatives you've considered**
The status quo, but that is not scaling.

**Additional context**
Discussed in release meeting on 2022-03-01 (as well as the previous week).
cc @zephyrproject-rtos/release-team

**Comment by cfriedt** [comment]
> This also raises a question on the need to have an issue filled for each PR that should be merged on a "maintenance branch". Merging a bug fix PR out of the stabilization period doesn't require an associated issue. But since most of bug fixes are back-ported, we frequently need to raise issues just to satisfy the merge criteria on the back-port target branch, which is adding its own overhead. Can we do something about that as well ? Specially if we start saying that each `bug` PR is a potential back-port candidate.

@erwango  - That's a really good point. It should be possible to automatically create a new issue if there is no linked issue in the original PR to `main`. However, those backport PRs would **necessarily** need to be labeled `DNM` and **not** moved out of triage until the issue is filled in with sufficient detail.

**Comment by henrikbrixandersen** [comment]
How would you automatically determine if a bug being fixed in `main` is also present in the release branches? The bug fix may apply cleanly even if the bug is not present on that branch.

**Comment by cfriedt** [comment]
https://github.com/zephyrproject-rtos/zephyr/wiki/Zephyr-Change-Control-Board-%28CCB%29
https://wiki.ubuntu.com/StableReleaseUpdates
https://lwn.net/Articles/764647/

**Comment by cfriedt** [comment]
> How would you automatically determine if a bug being fixed in `main` is also present in the release branches? The bug fix may apply cleanly even if the bug is not present on that branch.

Also an excellent point. Especially difficult with bugs that are nondeterministic or otherwise not easy to reproduce.

At the other end of the spectrum, we have negative side-effects, like what @nashif mentioned. We do not want to start adding bugfixes for bugfixes (regressions) - we need a buffer (a.k.a. soak period) preferably with lots of vendor testing as well.

**Comment by cfriedt** [comment]
We also discussed whether to apply backports to non-LTS release branches. Some are still on v2.6.0, for example. Having 10 different development branches does not make a lot of sense.

**Comment by erwango** [comment]
> t the other end of the spectrum, we have negative side-effects, like what @nashif mentioned. Every backport has some amount of risk. We do not want to start adding bugfixes for bugfixes (regressions) - we need a buffer (a.k.a. soak period) preferably with lots of vendor testing as well.

Don't we also have backport on the V3.0 for instance?

**Comment by nashif** [comment]
also see discussion here https://github.com/zephyrproject-rtos/zephyr/discussions/43561 and provide your feedback there.
