### ISSUE TITLE
Bluetooth: ISO: unallocated memory written during mem_init

### ISSUE THREAD

**Issue by carlst** [zephyrproject-rtos/zephyr#43392]
**Describe the bug**
In `subsys/bluetooth/controller/ll_sw/ull_iso.c` `init_reset()` function, `sizeof(struct ll_iso_datapath)` is used in `mem_init()` call. But  `struct ll_iso_datapath` may refer to a 0 length array `datapath_pool[0]` (whose length is not actually 0 due to structure tail padding).

The array length of 0 can occur if BT_CTLR_CONN_ISO_STREAMS and BT_CTLR_SYNC_ISO_STREAMS are both 0 (ISO broadcast only configuration). This can occur if BT_CTLR_ADV_ISO is defined (for ISO broadcast) but BT_CTLR_SYNC_ISO is not defined.

**To Reproduce**
1. build, flash, and run `bluetooth/samples/iso_broadcast` for nRF52840
2. Error in `memset() `called from `mem_init()` called from `init_reset()` in `ull_iso.c`

**Environment (please complete the following information):**
 - Toolchain: Zephyr SDK
 - Commit `feffe639a3f8a2d2459d21a390ffd2d9d96c2437`

**Comment by cvinayak** [comment]
Regression introduced by https://github.com/zephyrproject-rtos/zephyr/pull/43328, will add back the removed conditional compiles.
