### ISSUE TITLE
Pull request not updated after force push the original branch

### ISSUE THREAD

**Issue by MrVan** [zephyrproject-rtos/zephyr#43419]
This PR not automatically updated https://github.com/zephyrproject-rtos/zephyr/pull/32694, after I force push patches to https://github.com/MrVan/zephyr/tree/8mm-v1

**Comment by stephanosio** [comment]
I have seen the same problem happening on other PRs lately.

This seems to be a mishap on the GitHub side and the only solution seems to be to close the current pull request and open a new one.
