### ISSUE TITLE
USBD_CLASS_DESCR_DEFINE section name bug

### ISSUE THREAD

**Issue by Cherish-Gww** [zephyrproject-rtos/zephyr#43469]
https://github.com/zephyrproject-rtos/zephyr/blob/c32d10cc9e13d9e050d27b5804c0213f6cd3f452/include/usb/usb_device.h#L56

change dot to comma define like:
`static __in_section(usb, descriptor_##p, 1, instance) __used __aligned(1)`

**Comment by stephanosio** [comment]
This does not make sense.
