### ISSUE TITLE
`py` command not found when using nanopb on windows

### ISSUE THREAD

**Issue by nvandamme** [zephyrproject-rtos/zephyr#43505]
When using Nordic ncs 1.9.1 and zephyr, nanopb module is generating a .bat script. 
This script is invoking python with the command `py -3`.
This specific command is not available from the ncs toolchain nor in a python3 install on windows 10...

Workaround : 
in file `nanopb/generator/protoc-gen-nanopb.bat` https://github.com/zephyrproject-rtos/nanopb/blob/master/generator/protoc-gen-nanopb.bat

Replace `py -3` with `python`

Or pull the last published version of nanopb : https://github.com/nanopb/nanopb/releases/tag/0.4.5

**Comment by mbolivar-nordic** [comment]
Hi, since this is an NCS specific issue, please report on DevZone.
