### ISSUE TITLE
it8xxx2_evb: tests/kernel/sleep failed

### ISSUE THREAD

**Issue by fuhaolei** [zephyrproject-rtos/zephyr#43513]
**Describe the bug**
The test: "tests/kernel/sleep" failed.

**To Reproduce**
1. source zephyr-env.sh
2. twister -p it8xxx2_evb --device-testing -T tests/kernel/sleep/ --west-flash="$HOME/itetool/loader.sh" --device-serial=/dev/ttyUSB0
3. See error

**Expected behavior**
The test should pass.

**Impact**
No serious impact.

**Logs and console output**
```
***** delaying boot 1ms (per build configuration) *****
*** Booting Zephyr OS build zephyr-v3.0.0-808-gd74cb2a3df23  (delayed boot 1ms) ***
Running test suite sleep
===================================================================
START - test_sleep
Kernel objects initialized
Test thread started: id = 0x801010f8
Helper thread started: id = 0x80101050
Testing normal expiration of k_sleep()
Testing: test thread sleep + helper thread wakeup test
Testing: test thread sleep + isr offload wakeup test
Testing: test thread sleep + main wakeup test thread
Testing kernel k_sleep()
PASS - test_sleep in 2.34 seconds
===================================================================
START - test_usleep
elapsed_ms = 5750
Assertion failed at WEST_TOPDIR/zephyr/tests/kernel/sleep/src/usleep.c:95: test_usleep: (elapsed_ms <= UPPER_BOUND_MS is false)
overslept
FAIL - test_usleep in 57.516 seconds
===================================================================
START - test_sleep_forever
Kernel objects initialized
PASS - test_sleep_forever in 0.4 seconds
===================================================================
Test suite sleep failed.
===================================================================
PROJECT EXECUTION FAILED
```

**Environment (please complete the following information):**
 - OS: Ubuntu
 - Toolchain Zephyr SDK 0.13.2
 - Commit d74cb2a3df23

**Comment by hunterhu3000** [comment]
It looks like the CONFIG_SYS_CLOCK_TICKS_PER_SEC on ITE81xxx2 platform is different from others. If we change the code like this, the test can pass:

ztest@ztest-NUC7i7BNH:~/zephyrproject/zephyr$ git diff soc/riscv/riscv-ite/it8xxx2/Kconfig.defconfig.series
diff --git a/soc/riscv/riscv-ite/it8xxx2/Kconfig.defconfig.series b/soc/riscv/riscv-ite/it8xxx2/Kconfig.defconfig.series
index 2d0aa304b9..d105f1ffed 100644
--- a/soc/riscv/riscv-ite/it8xxx2/Kconfig.defconfig.series
+++ b/soc/riscv/riscv-ite/it8xxx2/Kconfig.defconfig.series
@@ -23,7 +23,7 @@ config SYS_CLOCK_HW_CYCLES_PER_SEC
        default 32768

 config SYS_CLOCK_TICKS_PER_SEC
-       default 32768
+       default 5800

 config UART_NS16550
        default y

I do not check the ITE spec and the value of 5800 is an estimated value.
