### ISSUE TITLE
[v2.7] gen_relocate_app truncates files on incremental builds

### ISSUE THREAD

**Issue by carlocaione** [zephyrproject-rtos/zephyr#43548]
The problem with append is that when doing incremental (non-clean)
build, the content of these files are appended each time to the previous
leftover content.

Example:
```
 # west build -p -b qemu_cortex_m3 \
 	samples/application_development/code_relocation/

 #   // disable for example CONFIG_XIP

 # west build -b qemu_cortex_m3 \
        samples/application_development/code_relocation/
```
at this point the content of the generated files (i.e.
linker_relocate.ld) is wrong.

**Comment by carlescufi** [comment]
Fixed in #42841
