### ISSUE TITLE
ITE eSPI driver expecting OOB header also along with OOB data from app code - espi_it8xxx2_send_oob() & espi_it8xxx2_receive_oob

### ISSUE THREAD

**Issue by NagarajuGundimi** [zephyrproject-rtos/zephyr#43568]
ITE eSPI driver expecting OOB header also along with OOB data from app code - espi_it8xxx2_send_oob() & espi_it8xxx2_receive_oob.

In espi_oob_msg_packet structure cycle_type, tag_len_bit_11_8 & len_bit_7_0 fields are OOB header. Currently ITE driver is such a way that app code has to fill/prepare OOB header also along with OOB data.

But in other EC vendors driver this OOB header data is taken care at driver level itself for both send & receive APIs.

<img width="233" alt="ITEbug" src="https://user-images.githubusercontent.com/85330759/157376733-29d91a46-c12c-4534-8587-d235a8e05a77.png">

**Comment by kashah1** [comment]
> ITE eSPI driver expecting OOB header also along with OOB data from app code - espi_it8xxx2_send_oob() & espi_it8xxx2_receive_oob.
> 
> In espi_oob_msg_packet structure cycle_type, tag_len_bit_11_8 & len_bit_7_0 fields are OOB header. Currently ITE driver is such a way that app code has to fill/prepare OOB header also along with OOB data.
> 
> But in other EC vendors driver this OOB header data is taken care at driver level itself for both send & receive APIs.
> 
> <img alt="ITEbug" width="233" src="https://user-images.githubusercontent.com/85330759/157376733-29d91a46-c12c-4534-8587-d235a8e05a77.png">
