### ISSUE TITLE
[Backport v2.7-branch] stm32: wrong clock the LSI freq for stm32l0x mcus

### ISSUE THREAD

**Issue by FRASTM** [zephyrproject-rtos/zephyr#43572]
**Describe the bug**
The LSI clock freq is  set to 32kHz in the stm32l0.dtsi which is not the value specified by the RefMan = "around 37 kHz." 

**Environment (please complete the following information):**
 - V2.7 branch

**Comment by cfriedt** [comment]
Fixed by #43312
