### ISSUE TITLE
hl7800: tcp stack freezes on slow response from modem

### ISSUE THREAD

**Issue by murraybo** [zephyrproject-rtos/zephyr#43580]
**Describe the bug**
The TCP stack freezes/locks if the response from the hl7800 modem is slow while sending out data. This can be caused by network congestion, high load or internal routines on the hl7800. The specification of the sierra wireless hl7800 states that it can take up to 60 seconds for this response.

The problem occurred on a Laird MG-100 which was constantly sending out data over a longer period of time.

I documented/analyzed long running sessions with debug log turned on for the hl7800.

**To Reproduce**
1. unfortunately this is initial caused by the (correct) internal handling of the hl7800 this can not be easily reproduced.
2. constantly send data over a tcp connection. 
3. If an error occures (ex. timeout or not all data got sent) - close the tcp connection or try to send more data.
4. the close or next sent will block forever

**Expected behavior**
The TCP Stack should not freeze. The modem driver should handle this situation according to the modem specification.

**Impact**
Only a reboot (in our case by a watchdog) is able to resolve the blocked stack.

**Logs and console output**
I can provide these if needed

**Environment (please complete the following information):**
 - OS: Zephyr 2.7

 
**Additional context**
There is already a pull request addressing the issue:
* https://github.com/zephyrproject-rtos/zephyr/pull/43462
* https://github.com/zephyrproject-rtos/zephyr/pull/43495

**Comment by rlubos** [comment]
Closing, as the fix seems to already be merged and backported. @murraybo please reopen if I'm wrong here.
