### ISSUE TITLE
Checkpatch: Support in-code ignore tags

### ISSUE THREAD

**Issue by koffes** [zephyrproject-rtos/zephyr#43604]
**Is your enhancement proposal related to a problem? Please describe.**
Sometimes, it may be desirable/required to violate something which Checkpatch gives an error or warning on.
Usually, this is handled by adding something to `.checkpatch.conf`

Though, this is a harsh approach as this ignores an entire file/files, or a given rule globally.

**Describe the solution you'd like**
A tag we can put into a source file which ignores N lines. 
Example:
```

/* Checkpatch ignore AVOID_EXTERNS */
extern foo_bar;
/*Checkpatch enable */

```

**Comment by nashif** [comment]
please submit this enhancement request to the upstream checkpatch code base, the linux kernel.
