### ISSUE TITLE
[v2.7] Bluetooth: controller: Missing NULL assign to df_cfg in ll_adv_set 

### ISSUE THREAD

**Issue by ppryga** [zephyrproject-rtos/zephyr#43602]
**Describe the bug**
`ll_adv_set` stores pointer to direction finding TX configuration.
When `ll_reset` is executed the pointer in not NULL assigned.
That leads to erroneous behavior e.g. `df_cfg->is_enabled` was set
to TRUE even the functionality was not enabled.

**Impact**
Touches direction finding functionality only, so it isn't showstopper in general but block use of direction finding.

**Comment by carlescufi** [comment]
Fixed in  #40751
