### ISSUE TITLE
Documentation incorrectly states that C++ new and delete operators are unsupported

### ISSUE THREAD

**Issue by waqas-mazhar** [zephyrproject-rtos/zephyr#43636]
**Issue Description**
The RTOS documentation, [C++ Support for Applications](https://docs.zephyrproject.org/latest/reference/kernel/other/cxx_support.html), indicates that C++ Dynamic Objects can't be managed using `new`/`delete` operators. However, there is a test case at `tests/subsys/cpp/cxx` for them. Also, `new`/`delete` operators are implemented at `subsys/cpp/cpp_new.cpp` which eventually resolve into `malloc`/`free` respectively both of which are mutex protected. Is there any specific reason due to which they are marked as _not supported_ in the document?

**Expected behavior**
Document should have more information regarding C++ `new`/`delete` support

**Comment by stephanosio** [comment]
Related to https://github.com/zephyrproject-rtos/zephyr/issues/32885
