### ISSUE TITLE
LSM6DSL IMU driver - incorrect register definitions

### ISSUE THREAD

**Issue by flo-carrere** [zephyrproject-rtos/zephyr#43669]
Multiple incorrect definitions are noticeable on the LSM6DSL (IMU sensor) from ST.

Datasheet source is here:
https://www.st.com/resource/en/datasheet/lsm6dsl.pdf

----------------

https://github.com/zephyrproject-rtos/zephyr/blob/ec7451b485fdb051c0ffc00fafb60d9b3e130c5b/drivers/sensor/lsm6dsl/lsm6dsl.h#L186-L187

This mask is incorrect, missing a | (OR).

It should be corrected to this (without formatting)
```
 #define LSM6DSL_MASK_CTRL5_C_ROUNDING			(BIT(7) | BIT(6) | BIT(5))
```
---------------

https://github.com/zephyrproject-rtos/zephyr/blob/ec7451b485fdb051c0ffc00fafb60d9b3e130c5b/drivers/sensor/lsm6dsl/lsm6dsl.h#L375-L381

The LSM6DSL_MASK_FIFO_STATUS3_FIFO_PATTERN should be **0xFF** 
as the FIFO_PATTERN takes the full register width (+2 bits on LSM6DSL_REG_FIFO_STATUS4 - see datasheet page 79)

The LSM6DSL_REG_FIFO_STATUS4 address is **0x3D** (see datasheet page 80)

It should be corrected to this (without formatting)
```
 #define LSM6DSL_REG_FIFO_STATUS3			0x3C 
 #define LSM6DSL_MASK_FIFO_STATUS3_FIFO_PATTERN		0xFF 
 #define LSM6DSL_SHIFT_FIFO_STATUS3_FIFO_PATTERN		0 
  
 #define LSM6DSL_REG_FIFO_STATUS4			0x3D 
 #define LSM6DSL_MASK_FIFO_STATUS4_FIFO_PATTERN		(BIT(1) | BIT(0)) 
 #define LSM6DSL_SHIFT_FIFO_STATUS4_FIFO_PATTERN		0 
```

**Comment by carlescufi** [comment]
Thanks, can you please open a Pull Request to fix this?

**Comment by flo-carrere** [comment]
Sorry I won't probably handle it myself, just reporting it for someone else to correct it.
