### ISSUE TITLE
samples/arch/smp/pktqueue not working on ESP32

### ISSUE THREAD

**Issue by sylvioalves** [zephyrproject-rtos/zephyr#43702]
**Describe the bug**
Sample `samples/arch/smp/pktqueue` does not complete.

**To Reproduce**
1. rm -rf build; west build -b esp32 samples/arch/smp/pktqueue/
3. west flash; west espressif monitor

**Expected behavior**
```c
   RESULT: OK
    Application ran successfully.
    All 20000 packet headers were processed in 89 msec
```

**Comment by evgeniy-paltsev** [comment]
@sylvioalves may I ask you to provide the error message you get?

Thanks!
