### ISSUE TITLE
intel_adsp_cavs: tests are not running with twister

### ISSUE THREAD

**Issue by yerabolu** [zephyrproject-rtos/zephyr#43713]
**Describe the bug**
Tests on intel_adsp_cavs25, intel_adsp_cavs18 and intel_adsp_cavs15 are blocked when run with twister. This issue is also seen on acrn.

**To Reproduce**
1. twister -W -p intel_adsp_cavs25 --device-testing --device-serial-pty=$HOME/zephyrproject/zephyr/soc/xtensa/intel_adsp/tools/cavstwist.sh --west-flash=$HOME/zephyrproject/zephyr/soc/xtensa/intel_adsp/tools/cavstwist.sh -T samples/hello_world/ -vvv
2. See error

**Impact**
All the tests are blocked after PR #42276  got merged yesterday.

**Logs and console output**
```

Device testing on:

| Platform          | ID   | Serial device   |
|-------------------|------|-----------------|
| intel_adsp_cavs25 |      |                 |

INFO    - Adding tasks to the queue...
DEBUG   - adding intel_adsp_cavs25/samples/hello_world/sample.basic.helloworld
INFO    - Added initial list of jobs to queue
DEBUG   - Launch process 0
DEBUG   - Launch process 1
DEBUG   - Launch process 2
DEBUG   - Launch process 3
DEBUG   - Running cmake on /home/ztest/zephyrproject/zephyr/samples/hello_world for intel_adsp_cavs25
DEBUG   - Calling cmake with arguments: ['-B/home/ztest/zephyrproject/zephyr/twister-out/intel_adsp_cavs25/samples/hello_world/sample.basic.helloworld', '-S/home/ztest/zephyrproject/zephyr/samples/hello_world', '-DEXTRA_CFLAGS=', '-DEXTRA_AFLAGS=', '-DEXTRA_LDFLAGS=', '-DEXTRA_GEN_DEFINES_ARGS=', '-GUnix Makefiles', '-DBOARD=intel_adsp_cavs25']
```

**Environment (please complete the following information):**
 - OS: Fedora
 - Toolchain : SDK 13.2
 - Commit SHA: b4dfdb5afb5e

**Comment by nashif** [comment]
the patch introducing this was reverted.
