### ISSUE TITLE
ADC Driver build is broken for STM32L412

### ISSUE THREAD

**Issue by benediktibk** [zephyrproject-rtos/zephyr#43750]
**Describe the bug**
Trying to build the ADC driver for a system with an STM32L412 results in an error.

**To Reproduce**
1. Use ADC driver in a project based upon a STM32L412
2. Build the project

**Expected behavior**
ADC3 should not be used.

**Impact**
Breaks the build for projects using the ADC driver and a STM32L412

**Logs and console output**

    zephyr/drivers/adc/adc_stm32.c: In function 'adc_stm32_setup_channels':
    zephyr/drivers/adc/adc_stm32.c:858:29: error: 'ADC3' undeclared (first use in this function); did you mean 'ADC1'?
      858 |  if ((adc == ADC1 || adc == ADC3) &&
          |                             ^~~~
          |                             ADC1

**Environment (please complete the following information):**
Zephyr revision df443f1d29e49f69708da1dfb3018ae8d1ec3f30

**Comment by benediktibk** [comment]
Probably caused by this commit: https://github.com/zephyrproject-rtos/zephyr/commit/90c369300561a2fddb733bac3ea5bc0802eb7d6c

**Comment by benediktibk** [comment]
The following controllers do not have ADC3:

- STM32L41XXX
- STM32L42XXX
- STM32L43XXX
- STM32L44XXX
- STM32L45XXX
- STM32L46XXX

The following controllers have ADC3:

- STM32L47XXX
- STM32L48XXX
- STM32L49XXX

**Comment by benediktibk** [comment]
All STM32L4+ (STM32L4P5/Q5, STM32L4R5/S5, STM32L4R7/S7, STM32L4R9/S9) also do not have ADC3.

**Comment by bpbradley** [comment]
The referenced PR appears to have introduced a different issue on `SOC_SERIES_STM32G4X` which causes ADC builds to fail still.

It appears to be using `ADC_CHANNEL_TEMPSENSOR` but on g4 series it has internal temperature on `ADC_CHANNEL_TEMPSENSOR_ADC1` and `ADC_CHANNEL_TEMPSENSOR_ADC5` -- there is no definition for `ADC_CHANNEL_TEMPSENSOR`
