### ISSUE TITLE
[Backport v3.0-branch] stm32: wrong clock the LSI freq for stm32l0x mcus

### ISSUE THREAD

**Issue by FRASTM** [zephyrproject-rtos/zephyr#43775]
Describe the bug
The LSI clock freq is set to 32kHz in the stm32l0.dtsi which is not the value specified by the RefMan = "around 37 kHz."

fixed by https://github.com/zephyrproject-rtos/zephyr/pull/43313

Environment (please complete the following information):

- V3.0 branch

**Comment by erwango** [comment]
https://github.com/zephyrproject-rtos/zephyr/pull/43313 was merged
