### ISSUE TITLE
BMI160 Driver: Waiting time between SPI activation and reading CHIP IP is too low

### ISSUE THREAD

**Issue by PeachBug** [zephyrproject-rtos/zephyr#43794]
**Describe the bug**
When resetting the SoC (nrf52840) via jlink, BMI160 stops responding. The code blocks when the driver tries to read the CHIP ID register. I solved the issue by increasing the k_busy_wait from 100 to 200.

https://github.com/zephyrproject-rtos/zephyr/blob/565fc4d29c90e244cb16b5af05d5cc47d1edc059/drivers/sensor/bmi160/bmi160.c#L901

**To Reproduce**
1. west build -b nrf52840dk_nrf52840
2. JLinkRTTClient
3. JLinkExe
3.1. connect
3.2. r
3.3. g
4. See error on JLinkRTTClient

**Impact**
It induces the user to think there is some type of BMI160 misconfiguration issue.

**Environment:**
 - OS: Ubuntu 20.04
 - Toolchain: Zephyr SDK
 - Version: 2.7.0

**Comment by mbolivar-nordic** [comment]
@anangl -- do you have this sensor?

**Comment by anangl** [comment]
> @anangl -- do you have this sensor?

No, unfortunately, I don't have one.

**Comment by carlescufi** [comment]
@PeachBug can you please send a Pull Request changing the delay from 100 to 200?
