### ISSUE TITLE
Alllow callbacks to CDC_ACM events

### ISSUE THREAD

**Issue by holgerschurig** [zephyrproject-rtos/zephyr#43793]
Szenario: Firmware inside a STM32 microcontroller connected via USB to host OS Linux

Wish:

* knowing when host OS has enumerated the CDC_ACM USB device
* knowing when host OS stops using the firmware (e.g. to reset a JSON parsing statemachine)

The events already exists, and one can then see in the console log already:

```
[00:00:13.076,000] <inf> usb_cdc_acm: Device configured
```

But unfortunately I cannot react to these USB events programmatically. So it would be nice if one could register a callback that cdc_acm_do_cb() calls. That would one allow to react programmatically to everything: USB_DC_ERROR, USB_DC_RESET, USB_DC_CONNECTED, USB_DC_DISCONNECTED, ...

**Comment by jfischer-no** [comment]
You can pass a callback to usb_enable(), https://docs.zephyrproject.org/latest/reference/usb/uds.html?highlight=usb_enable#c.usb_enable

**Comment by holgerschurig** [comment]
Thanks, can be closed. `usb_enable()` does the job for me.
