### ISSUE TITLE
tests: cmsis_dsp: rf16 and cf16 tests are not executed on Native POSIX

### ISSUE THREAD

**Issue by gopiotr** [zephyrproject-rtos/zephyr#43816]
**Describe the bug**
Following test scenarios:
 * `libraries.cmsis_dsp.transform.cf16`
 * `libraries.cmsis_dsp.transform.cf16.fpu`
 * `libraries.cmsis_dsp.transform.rf16`
 * `libraries.cmsis_dsp.transform.rf16.fpu`

From this directory:
`tests/lib/cmsis_dsp/transform/`
are not executed - only `PROJECT EXECUTION SUCCESSFUL` is printed.
Problem concerns only `native_posix` platform.
On `mps2_an521` and `mps2_an521_remote` platforms everything works properly.

**To Reproduce**
1. Run Twister by this command:
`./scripts/twister -p native_posix -T tests/lib/cmsis_dsp/transform/`
3. Analyze twister.log file - especially execution of `rf16` and `cf16` tests.

**Expected behavior**
Tests should be executed - not only printing of `PROJECT EXECUTION SUCCESSFUL` information.

**Impact**
At this moment those tests are marked as `PASS` what is misleading information, because they aren't even executed.

**Logs and console output**
```
2022-03-15 17:14:39,977 - twister - DEBUG - Spawning BinaryHandler Thread for native_posix/tests/lib/cmsis_dsp/transform/libraries.cmsis_dsp.transform.cf16.fpu
2022-03-15 17:14:39,978 - twister - DEBUG - OUTPUT: *** Booting Zephyr OS build zephyr-v3.0.0-884-gadc901aa6a39  ***
2022-03-15 17:14:39,978 - twister - DEBUG - OUTPUT: ===================================================================
2022-03-15 17:14:39,979 - twister - DEBUG - OUTPUT: PROJECT EXECUTION SUCCESSFUL
2022-03-15 17:14:39,979 - twister - DEBUG - OUTPUT: 
```

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: Zephyr SDK
 - Commit SHA: adc901aa6a39caffd7971ff99456b26414cd3793

**Additional context**
Similar problem occurred here:
https://github.com/zephyrproject-rtos/zephyr/issues/42396
But I verified, that those tests do not work since the beginning - since they was added in those commits:
https://github.com/zephyrproject-rtos/zephyr/commit/600ca01464ef253097644f2fc4dd0f3f2a3f5087
https://github.com/zephyrproject-rtos/zephyr/commit/6547025bc19b0bfd6078b3e76ba54b1193de9196
So, the source of problem is probably not connected with changes introduced in ZTest API in October last year.

This problem was discovered during review of this PR:
https://github.com/zephyrproject-rtos/zephyr/pull/42482
Enhancement proposed in this PR could help to avoid this situation, due to the additional verification of printed test suite name.

If everything works properly on QEMU platforms, then perhaps it should be considered to remove support for Native POSIX platform for those tests?

**Comment by stephanosio** [comment]
NOTE: similar situation with the `matrix` tests.
