### ISSUE TITLE
http_client: http_client_req() returns incorrect number of bytes sent

### ISSUE THREAD

**Issue by ewalt1** [zephyrproject-rtos/zephyr#43829]
The `http_client_req()` function is supposed to return the number of bytes sent to the server:
https://github.com/zephyrproject-rtos/zephyr/blob/main/include/net/http_client.h#L327

However, there is a bug in the implementation such that it generally returns something much larger. Each line of the headers is sent via one call to `http_send_data()`, the return value of which is added to the `total_sent` summation variable.
https://github.com/zephyrproject-rtos/zephyr/blob/main/subsys/net/lib/http/http_client.c#L529

However, `http_send_data()` doesn't typically return the number of bytes that were added in that particular invocation. Instead it copies the values into a local 192 byte buffer and returns the current position within that buffer.

For example, if I wanted to send:

            PATCH /v1/123456789abcd HTTP/1.1
            Host: xxxxxxxxxxxxxxxxxx.uc.r.appspot.com
            Content-Length: 34

Then the http_client sends 33+43+22==98 bytes of headers plus my 34 bytes of payload for a total of 132 bytes.

However the calls to `http_send_data()` will return 33, (33 + 43), and (33 + 43 + 22) respectively. This leads to `total_sent` being set to 207 by the time the headers have been sent, which causes an incorrect return value of 207+34==241 from `http_client_req()`.

**Comment by rlubos** [comment]
@ewalt1 Please check https://github.com/zephyrproject-rtos/zephyr/pull/43916 where I proposed a fix for the problem.
