### ISSUE TITLE
stm32: g0b1: RTT doesn't work properly after stop mode

### ISSUE THREAD

**Issue by ycsin** [zephyrproject-rtos/zephyr#43836]
**Describe the bug**
The RTT stops working properly after the MCU enter stop mode. I'm on 2.7.1 LTS branch which already has #38561 patch.
It prints garbage after MCU went to sleep, it also missed some lines that would have been printed if UART backend were used:

![image](https://user-images.githubusercontent.com/1563974/158517001-3b00d253-a6d1-460b-a6b5-315988ba20b0.png)

![image](https://user-images.githubusercontent.com/1563974/158517252-35b07a9b-9750-4c63-8190-fcf23532085a.png)

Apart from this, I believe some of the character (next line?) sent from the log/shell cant be recognized by the RTT viewer for some reason:
```
WARNING: <Terminal 0>: ANSI CSI SGR parameter 7 not supported.
WARNING: <Terminal 0>: ANSI CSI SGR parameter 7 not supported.
WARNING: <Terminal 0>: ANSI CSI SGR parameter 7 not supported.
WARNING: <Terminal 0>: ANSI CSI SGR parameter 7 not supported.
WARNING: <Terminal 0>: ANSI CSI SGR parameter 7 not supported.
```

**Environment (please complete the following information):**
 - OS: Windows
 - gnuarmemb
 - 2.7.1 LTS

**`prj.conf`**
I have these extra Kconfig to get the RTT built:
```conf
CONFIG_USE_SEGGER_RTT=y
CONFIG_LOG_BACKEND_RTT=y
CONFIG_LOG_BACKEND_UART=n

CONFIG_LOG_BACKEND_RTT_BUFFER=1
CONFIG_SHELL_BACKEND_SERIAL=n
CONFIG_SHELL_BACKEND_RTT=y
```

`shell_rtt.c` fails to build without `CONFIG_LOG_BACKEND_RTT_BUFFER=1`:
```
C:/Users/yongc/zephyrproject/zephyr/subsys/shell/shell_rtt.c:12:1: note: in expansion of macro 'BUILD_ASSERT'
   12 | BUILD_ASSERT(!(IS_ENABLED(CONFIG_LOG_BACKEND_RTT) &&
      | ^~~~~~~~~~~~
```

**Comment by ycsin** [comment]
@erwango @ABOSTM any idea?

**Comment by ABOSTM** [comment]
At first glance I would say: maybe one of the condition described in #38561 in not respected after wakeup
* one of the DMA is clocked

and sometimes also
* one of the DBGMCU bit STOP/STANDBY/SLEEP is set

@ycsin , could you check that ?

**Comment by ycsin** [comment]
> @ycsin , could you check that ?

Thanks for looking into this.
How should I check this? Break point in the `power.c` exit post ops?

**Comment by ABOSTM** [comment]
Anywhere but after wakeup,  `power.c` exit post ops  sounds good, but at the end of this function.

**Comment by ycsin** [comment]
> @ycsin , could you check that ?

I added a breakpoint [here](https://github.com/zephyrproject-rtos/zephyr/blob/main/soc/arm/st_stm32/stm32g0/power.c#L72):
<img width="800" alt="image" src="https://user-images.githubusercontent.com/1563974/159399800-1f2a191a-060d-46e9-9137-be83f3685a9f.png">

<img width="300" alt="image" src="https://user-images.githubusercontent.com/1563974/159399849-11e59db8-613b-43f5-a172-890a083bc4d9.png">
<img width="300" alt="image" src="https://user-images.githubusercontent.com/1563974/159399944-b11c0b3f-0272-4ef7-8e65-3562cb3e3a7f.png">

**Comment by erwango** [comment]
@ycsin Did you made any progress on this issue? Is it still valid ?

**Comment by ycsin** [comment]
> @ycsin Did you made any progress on this issue? Is it still valid ?

I've left my previous company and I doubt if anyone made any progress on this issue, it should still be valid

**Comment by erwango** [comment]
> > @ycsin Did you made any progress on this issue? Is it still valid ?
> 
> I've left my previous company and I doubt if anyone made any progress on this issue, it should still be valid

Thanks for the head's up.

**Comment by erwango** [comment]
Would need another test since #48640 was merged and can have an impact
