### ISSUE TITLE
LPC55S69 Not flashing to second core.

### ISSUE THREAD

**Issue by durinwinter** [zephyrproject-rtos/zephyr#43830]
Dual Core examples not working on Zephyr. MCU Expresso dual core examples for bare metal does work on this board.

**To Reproduce**
Attempt flashing a dual core example on the LPC55S69-EVK.

**Expected behavior**
Dual core functionality acts as expected according to sample documentation.

**Impact**
Showstopper for LPC55S69 Usage with Zephyr.

**Comment by danieldegrasse** [comment]
@durinwinter How are you flashing the sample? You need to use `JLinkExe` to manually load the multicore binary, see here: https://docs.zephyrproject.org/latest/boards/arm/lpcxpresso55s69/doc/index.html#building-a-dual-core-image. Additionally, the only sample I am aware of that supports dual code on the LPC55S69 is `samples/subsys/ipc/openamp`

**Comment by danieldegrasse** [comment]
@durinwinter Could you confirm if you were able to get this sample to work for you?

**Comment by dleach02** [comment]
closing due to nonresponse
