### ISSUE TITLE

tests-ci : libraries: encoding: jwt test Timeout


### ISSUE THREAD

**Issue by hakehuang** [zephyrproject-rtos/zephyr#43842]
**Describe the bug**
jwt test is ***** USAGE FAULT ***** on zephyr-v3.0.0-1108-ge65e26162199 on mimxrt1060_evk

see logs for details

test apps:  tests/subsys/jwt

**To Reproduce**
1. 
```
scripts/twister --device-testing --device-serial /dev/ttyACM0 -p mimxrt1060_evk  --sub-test libraries.encoding
```
2. See error

**Expected behavior**
test pass

**Impact**

**Logs and console output**
```
*** Booting Zephyr OS build zephyr-v3.0.0-1108-ge65e26162199  ***
Running test suite lib_jwt_test
===================================================================
START - test_jwt
E: ***** USAGE FAULT *****
E:   Illegal use of the EPSR
E: r0/a1:  0x00000000  r1/a2:  0x8000a758  r2/a3:  0x00000000
E: r3/a4:  0x00000000 r12/ip:  0xee119966 r14/lr:  0x6000f675
E:  xpsr:  0x60000000
E: Faulting instruction address (r15/pc): 0x00000000
E: >>> ZEPHYR FATAL ERROR 0: CPU exception on CPU 0
E: Current thread: 0x80000608 (test_jwt)
E: Halting system

    
```

**Environment (please complete the following information):**
 - OS: (e.g. Linux )
 - Toolchain (e.g Zephyr SDK)
 - Commit SHA or Version used: zephyr-v3.0.0-1108-ge65e26162199

**Comment by LixinGuoX** [comment]
Found the same issue on mimxrt1050_evk, #43792 for reference.

**Comment by hakehuang** [comment]
@dleach02 , @danieldegrasse , @mmahadevan108
