### ISSUE TITLE
[v2.7-auditable branch]: X86 MSI messages always get to BSP core (need a fix to be backported)

### ISSUE THREAD

**Issue by tbursztyka** [zephyrproject-rtos/zephyr#43854]
**Describe the bug**

On x86, MSI messages are configured to be treated always by the BSP core (BootStrap Processor). 
While this is just fine on plain hardware, this may not be the case in a virtualizer or emulator.

**Expected behavior**
MSI message should be directed to current running core, whether it's BSP or not.

**Impact**
MSI support (and thus all relevant drivers using it) do not work on ACRN.

**Comment by mbolivar-nordic** [comment]
closing per @nashif
