### ISSUE TITLE
Twister:  test case number discrepancy in the result xml.

### ISSUE THREAD

**Issue by smrtos** [zephyrproject-rtos/zephyr#43898]
**Describe the bug**
Run test with twister and generate the raw result XML.  (Zephyr commit: 63a109e17fce）

The top row of the XML like below indicates some case stats like below:

`<testsuite name="reel_board" time="3264.340588" tests="10574" failures="0" errors="0" skipped="5888">`

Some discrepancies:

1. The skipped case number 5888 is much larger than the actual number of below XML nodes:
`<skipped type="skipped" ...`   = 116

2. The total  tests number 10574 is much larger than the actual number of below XML nodes:
`<testcase classname=`  = 4802

Below is the full XML:
https://github.com/smrtos/zephyr_bug_repro/blob/main/twister/testcase_number_discrepancy.xml

**Expected behavior**
The 1st line stats should match with counting the XML nodes.

**Impact**
Inconsistent test statistics.

**Comment by carlescufi** [comment]
Maybe fixed by https://github.com/zephyrproject-rtos/zephyr/pull/44094

**Comment by smrtos** [comment]
Here's a script to ease the validation of the raw XML result.
https://github.com/intel-sandbox/sm_zephyr_tools/blob/main/Traceability/zRawTestXmlStats.py

**Comment by nashif** [comment]
with some additions to https://github.com/zephyrproject-rtos/zephyr/pull/44094, this might address any problems now, at least we will get warnings about discrepancies

**Comment by nashif** [comment]
lots of the discrepancy can be attributed to malformed tests, but also to some accounting bugs in twister, so this should be addressed once https://github.com/zephyrproject-rtos/zephyr/pull/44094 is merged.
