### ISSUE TITLE
LE Audio: Callbacks as singletons or lists? 

### ISSUE THREAD

**Issue by Thalley** [zephyrproject-rtos/zephyr#43913]
**Is your enhancement proposal related to a problem? Please describe.**
Typically the callback structs used by LE Audio are currently singletons, but most of them are not defined as `const`. For these we should either add `const` or we should allow multiple users to register it. 

**Describe the solution you'd like**
Add `const` to callback structs for LE Audio profiles

**Describe alternatives you've considered**
Allow multiple users of the callbacks, which is done by adding a `slist` node and storing the callbacks in a list similar to e.g. the `bt_conn_cb`s. 

**Additional context**
We may want to decide this based on each profile.

**Comment by asbjornsabo** [comment]
Zephyr-bt F2F: Decide for each profile, open issues when needed.  Closing.
