### ISSUE TITLE
LTSv2 Service Pack 1 WishList

### ISSUE THREAD

**Issue by cfriedt** [zephyrproject-rtos/zephyr#43912]
Features that did not make it into LTSv2 that users would like to see in a service pack.

Propose SP1 be released on July 1.

This is something entirely outside of the scope of the regular release channel, and should really be considered a **best-effort approach**. Beyond CI and reported acceptance testing, there will be no promises made.

I am willing to merge changes into a branch off based on the v2.7.2 tag (pending) for this purpose. 

This will likely involve some additional work by the community as well as maintainers and collaborators. Changes should be kept as minimal and atomic as possible. It may well be more bandwidth than collaborators and maintainers have, so external contributions are welcome. If anything, even just some high-level direction and / or notes from maintainers would be appreciated.

- [ ] LVGLv8 cc @brgl
  - Notes here

**Comment by brgl** [comment]
Another changeset we'd be interested in getting into LTSv2 is the following PR: https://github.com/zephyrproject-rtos/zephyr/pull/43927 Fortunately this is straightforward.

**Comment by brgl** [comment]
WRT LVGL v8 in 2.7: the bit about the changes needing to be atomic and minimal is a no-go. While eventually we ended up moving almost of the lvgl code out of the zephyr tree for 3.1, the changes that stayed in-tree encompas many defconfigs, samples etc. I did a minimal, squashed port of the LVGL changes to 3.0 and it still amounts to 800 LOC changed. Is this still acceptable?

**Comment by cfriedt** [comment]
> WRT LVGL v8 in 2.7: the bit about the changes needing to be atomic and minimal is a no-go. While eventually we ended up moving almost of the lvgl code out of the zephyr tree for 3.1, the changes that stayed in-tree encompas many defconfigs, samples etc. I did a minimal, squashed port of the LVGL changes to 3.0 and it still amounts to 800 LOC changed. Is this still acceptable?

I wonder if we could remove what is necessary to adopt the approach taken in 3.1 - a module sounds far more appealing. I would definitely consider it.

Minimal in this case should also mean "minimal effort", so if the work has been done and it's not too, too hard to apply to v2.7-branch, that would work too.

**Comment by cfriedt** [comment]
This is likely not going to happen - closing.
