### ISSUE TITLE
ipc_service: Extend API with zero-copy send

### ISSUE THREAD

**Issue by nordic-krch** [zephyrproject-rtos/zephyr#43924]
**Is your feature request related to a problem? Please describe.**
Currently ipc service support standard send function https://github.com/zephyrproject-rtos/zephyr/blob/e8f93a915def87b9c7e1bce3323bec996d7863da/include/ipc/ipc_service.h#L171

It has two drawbacks:
- if message is prepared ad hoc, does not come from any buffer, often space needs to be allocated on stack which is problematic if message has variable size.
- there is a performance degradation due to copying. Often shared memory has more wait-states so copying is slow. Wait-states impact is diminished if packet building includes some processing between writes. In that case performance difference can be significant (my benchmark shown that building a message directly in shared memory was twice faster compared to building on stack and copying to shared memory (on nrf5340)).

**Describe the solution you'd like**
Extend `ipc_service.h` with API similar to:

```
/* -EALREADY - if already claimed
 * -ENOTSUP - not supported by the backend
 */
int ipc_service_send_claim(ept, void **data, size_t len);

int ipc_service_send_commit(ept, void **data, size_t len); /* maybe just int ipc_service_send_commit(ept) */
```

**Comment by carlocaione** [comment]
This should be already supported by OpenAMP so this could be a nice addition (is that correct @arnopo ?)

**Comment by arnopo** [comment]
Yes, 
At OpenAMP level the APi exists in TX:
https://github.com/zephyrproject-rtos/open-amp/blob/master/open-amp/lib/include/openamp/rpmsg.h#L331
https://github.com/zephyrproject-rtos/open-amp/blob/master/open-amp/lib/include/openamp/rpmsg.h#L366

RX part could also been optimized.  An example of holding RX buffer is available here:
https://github.com/zephyrproject-rtos/zephyr/blob/main/samples/subsys/ipc/openamp_rsc_table/src/main_remote.c#L110
