### ISSUE TITLE
zephyr/tests/crypto/ccm_mode :-Evalution failed due to esp32

### ISSUE THREAD

**Issue by rrahulkx** [zephyrproject-rtos/zephyr#4398]
This testcase is faild due to esp32 failure.
because of this esp32 lot many testcase is failed.
I have pasted the log for the corresponding testcase log.

**Testcase :--**
zephyr.git/tests/crypto/ccm_mode/testcase.yaml#test @ esp32-40:xtensa COMPLETION failed

Toolchain: ZEPHYR_GCC_VARIANT=espressif

Commit ID                                Branch          URL
---------------------------------------- --------------- -------------------
ee71332b99f92730ccb009371a650e2dd199b68b master          https://github.com/zephyrproject-rtos/zephyr.git

Target Name  Remote ID          Type
-----------  -----------------  -----
target      esp32-40                 esp32

**Detailed description**

**Build procedure :-**

Output (the target might have produced none; GDB will be needed at this point):

will run on target group 'target=esp32-40:xtensa'
 build passed: 'mkdir -p outdir-ajke-zuqd-esp32; rm -f outdir-ajke-zuqd-esp32/.config'
 build passed: 'make -j -C espressif/zephyr.git/tests/crypto/ccm_mode/ 
EXTRA_CFLAGS="-Werror -Wno-error=deprecated-declarations" 
KCPPFLAGS=-DTC_RUNID=ci-171017-1145-379:zuqd 
BOARD=esp32 
ARCH=xtensa  
O=outdir-ajke-zuqd-esp32 initconfig'

 build output: Using zephyr.git/boards/xtensa/esp32/esp32_defconfig as base
 build output: Merging espressif/zephyr.git/tests/include/test.config
 build output: Merging prj.conf
 build output: Merging outdir-ajke-zuqd-esp32/boot_config.conf
 build passed: 'make -j -C espressif/zephyr.git/tests/crypto/ccm_mode 
EXTRA_CFLAGS="-Werror -Wno-error=deprecated-declarations" 
KCPPFLAGS=-DTC_RUNID=ci-171017-1145-379:zuqd 
BOARD=esp32 
ARCH=xtensa  
O=outdir-ajke-zuqd-esp32'

Make flash

deploy passed

Reset

**Console output obtain :-**

```

eval failed: found expected (for failure) `(USAGE FAULT|[Ff]atal fault in )` in console `esp32-40:default` at 0.98s
console output: I^B^B%9
console output: : 0 WOE : 1
console output:   OWB      : 06 CALLINC : 2
console output: INTENABLE = 0D = 0x3ffb15c8
console output: Faulting instruction address = 0xdeaddead
console output: Fatal fault in ISR! Spinning...
console output: *** Reserved Interrupt ***
console output: Exception cause 4 (level-1 interrupt):
console output:   EPC1     : 0x400837e6 EXCSAVE1 : 0x800826f7 EXCVADDR : 0x00000000
console output: Program state (PS):
console output:   INTLEVEL : 01 EXCM    : 0 UM  : 1 RING : 0 WOE : 1
console output:   OWB      : 15 CALLINC : 2
console output: INTENABLE = 0x640
console output: INTERRUPT = 0x1 (0)
console output: Current thread ID = 0x3ffb15c8
console output: Faulting instruction address = 0xdeaddead
console output: Fatal fault in ISR! Spinning...
console output: *** Reserved Interrupt ***
console output: Exception cause 4 (level-1 interrupt):
console output:   EPC1     : 0x400837e6 EXCSAVE1 : 0x800826f7 EXCVADDR : 0x00000000
console output: Program state (PS):
console output:   INTLEVEL : 01 EXCM    : 0 UM  : 1 RING : 0 WOE : 1
console output:   OWB      : 08 CALLINC : 2
console output: INTENABLE = 0x640
console output: INTERRUPT = 0x1 (0)
console output: Current thread ID = 0x3ffb1720
console output: Faulting instruction address = 0xdeaddead
console output: Fatal fault in thread 0x3ffb1720! Aborting.
console output: *** Unhandled exception ****
```

**Comment by lpereira** [comment]
I'll take a look either today or next week.
