### ISSUE TITLE
net: tcp: Running out of buffers by packet loss

### ISSUE THREAD

**Issue by ssharks** [zephyrproject-rtos/zephyr#44018]
When transferring a big TCP send, packet loss causes the send to return with a NOMEM error.

The tests/net/socket/tcp has been modified to reproduce this.
The packet loss is simulated by throwing away one every 8 packets in the loopback driver.
https://github.com/ssharks/zephyr/tree/tcp_big_data_transfer

**Comment by carlescufi** [comment]
@ssharks please add more information about the board you are using to reproduce this.

**Comment by ssharks** [comment]
Totally forget to mention, I use the platform qemu_x86
Run the test using:
./scripts/twister -s tests/net/socket/tcp/net.socket.tcp.preempt -T tests/net/socket/tcp -p qemu_x86
