### ISSUE TITLE
Align k_poll with waiters

### ISSUE THREAD

**Issue by Vudentz** [zephyrproject-rtos/zephyr#4404]
The current assumption with k_poll and waiters is that the consumers list is sorted in priority order with the higher priority thread always being server first. This along with the fact that k_poll only notifies about objects make it hard to align these APIs, so we probably need to start discussing a few points:

1. Does the waiters/consumers should really be sorted in priority order? If it does perhaps the code should be changed to evaluate the priorities on wakeup, though this will most like increase the time the irq lock must be held. It might be possible to remove any sorting and have it serving in fifo mode, this would prevent lower priority threads to starve in case a higher priority thread is consuming everything.

2. Should we have a way to interrupt consumers once they have been flagged to wakeup? Regardless if the consumers are sorted based on priority or not there may be situations where it may not be enough to mark consumer thread as ready and pretend once the thread swaps it will be alright since there exists APIs, such as k_delayed_work_cancel, that are intended to cancel consumers even if they are already pending.

**Comment by jukkar** [comment]
This is very old one. Is this is an issue?

**Comment by pfalcon** [comment]
Well, this likely came from some issues/discussion of k_poll rough edges, but as this is not cross-linked, it's now indeed hard to remember context of it.
