### ISSUE TITLE
rand32_ctr_drbg fails to call the respective initialization routing

### ISSUE THREAD

**Issue by dleach02** [zephyrproject-rtos/zephyr#44092]
**Describe the bug**
f44b3dc4dfe changed where initialization of entropy_dev to occur at compile time but the logic in z_impl_sys_csrand_get() calls the initialization routine IF entropy_dev is NULL. In the init routine it will assign the device object to entropy_dev and properly initialize the context object. 

Using an initialized context object results in a crash.

**To Reproduce**
1. west build -b mimxrt1050_evk -p always tests/net/socket/tls/
2. See error

**Impact**
Code crashes from an indirect call to a NULL address when getting sys_csrand_get() data.

**Comment by dleach02** [comment]
ping @gmarull

**Comment by gmarull** [comment]
Thanks for reporting @dleach02 , will submit a fix tomorrow

**Comment by dleach02** [comment]
I have a fix... posting now
