### ISSUE TITLE
The SMP nsim boards are started incorrectly when launching on real HW

### ISSUE THREAD

**Issue by evgeniy-paltsev** [zephyrproject-rtos/zephyr#44107]
**Describe the bug**
The SMP nsim boards (`nsim_hs_smp`, `nsim_hs6x_smp`) are started incorrectly when launching on real HW instead of nSIM simulator.

The rootcause is the missing `--cores` argument to `mdb-hw` runner - we pass it to `mdb-nsim` (which is used to launch simulation) but not for `mdb-hw` (which is used to launch on real HW), so we start only CPU0 when launching app on HW.

Fixed in: #42791, #43039

**Comment by carlescufi** [comment]
Merged to 2.7 in #43039
