### ISSUE TITLE
a build error when CONFIG_MULTITHREADING=n

### ISSUE THREAD

**Issue by tangguowen** [zephyrproject-rtos/zephyr#44101]
build command: 
west build -b mimxrt1050_evk samples/hello_world

link error file: drivers/serial/uart_mcux_lpuart.c: 345:k_sleep(K_MSEC(1));
the Implementation of k_sleep is z_impl_k_sleep in sched.c, but not compiled, see kernel/CMakeLists.txt.

Maybe need a nop delay implementation for k_sleep when CONFIG_MULTITHREADING=n

@carlescufi

**Comment by carlescufi** [comment]
No, as documented [in this page](https://docs.zephyrproject.org/latest/reference/kernel/threads/nothread.html#nothread), `CONFIG_MULTITHREADING=n` is only supported on selected platforms and on a subset of drivers. If you'd like that UART driver to work without threads you will need to modify it so it doesn't use `k_sleep()`, at least conditionally.
