### ISSUE TITLE
drivers/ethernet/eth_stm32_hal.c: eth_stm32_hal_set_config() always returns -ENOTSUP (-134)

### ISSUE THREAD

**Issue by greenlava82** [zephyrproject-rtos/zephyr#44125]
**Describe the bug**
When trying to set enable promiscuous mode on an STM32 (specifically Nucleo H743zi), the HAL function eth_stm32_hal_set_config() in drivers/ethernet/eth_stm32_hal.c always returns -ENOTSUP as shown at line 1023

`return -ENOTSUP;`

Please also mention any information which could help others to understand
the problem you're facing:
 - What target platform are you using? Nucleo_H743zi
 - What have you tried to diagnose or workaround this issue? 
       Found error using debugger.  changing line 1023 to:
      
      `return ret;`

  Allows the system to return success (0) if appropriate and promiscuous mode packet capture works as expected

**To Reproduce**
1. west build -p -b nucleo_h743zi zephyr/samples/net/promiscuous_mode
2. west flash
3.  See error

**Expected behavior**
Promiscuous mode can be enabled on supported STM32 nucleo hardware

**Impact**
What impact does this issue have on your progress (e.g., annoyance, showstopper)
critical to my application, but a workaround is in place

**Logs and console output**
If applicable, add console logs or other types of debug information
e.g Wireshark capture or Logic analyzer capture (upload in zip archive).
copy-and-paste text and put a code fence (\`\`\`) before and after, to help
explain the issue. (if unable to obtain text log, add a screenshot)

```
*** Booting Zephyr OS build zephyr-v3.0.0-973-g0dbbf3b61bc3  ***
[00:00:00.007,000] <inf> net_config: Initializing network
[00:00:00.007,000] <inf> net_config: Waiting interface 1 (0x2400119c) to be up...
[00:00:01.501,000] <inf> net_config: Interface 1 (0x2400119c) coming up
[00:00:01.502,000] <inf> net_config: IPv4 address: 192.168.0.93
[00:00:01.602,000] <inf> net_config: IPv6 address: 2001:db8::1
[00:00:01.603,000] <inf> net_promisc_sample: Cannot set promiscuous mode for interface 0x2400119c (-134)
```

**Environment (please complete the following information):**
 - OS: (e.g. Linux, MacOS, Windows). MacOS
 - Toolchain (e.g Zephyr SDK, ...) GNU Arm Embedded (https://docs.zephyrproject.org/latest/getting_started/toolchain_3rd_party_x_compilers.html#gnu-arm-embedded)
 - Commit SHA or Version used 
   zephyr-v3.0.0-973-g0dbbf3b61bc3

**Additional context**
Add any other context that could be relevant to your issue, such as pin setting,
target configuration, ...

**Comment by jukkar** [comment]
Already fixed by #43539
