### ISSUE TITLE
net: Duplicated functionality between net_pkt_get_src_addr() and net_context.c:create_sockaddr()

### ISSUE THREAD

**Issue by pfalcon** [zephyrproject-rtos/zephyr#4421]
In my review of https://github.com/zephyrproject-rtos/zephyr/pull/1055#issuecomment-331155034 , I expressed my surprised that we didn't have a func like net_pkt_get_src_addr() before. And indeed, we had something like that as net_context.c:create_sockaddr(), except that latter was confusingly named and worked only for TCP (kinda, the only thing it needs from TCP are port numbers, and those match UDP header).

Let's now think how to get rid of duplication.

**Comment by pfalcon** [comment]
Note that net_pkt_get_src_addr() almost certainly incorrectly uses net_pkt_tcp_data() to access TCP/UDP headers. Almost, unless @askawu have thought of that and a net data fragment guaranteed to be even (which probably can't be, e.g. `default 125 if NET_L2_IEEE802154` (it's strange it's not 127 btw)).

**Comment by pfalcon** [comment]
See https://github.com/zephyrproject-rtos/zephyr/pull/4422

**Comment by pfalcon** [comment]
My proposal would be to base on net_pkt_get_src_addr(), fix it, and drop sockaddr_len param - it and associated checks are superfluous and only add overhead.

**Comment by pfalcon** [comment]
@askawu : Please let me know if you agree with the changes proposed above and if you're interested to implement them. Otherwise, I'll go for them.

**Comment by askawu** [comment]
@pfalcon, net_pkt_get_src_addr() has been fixed by #4484. I will work on replacing create_sockaddr().
