### ISSUE TITLE
xtensa arch_cpu_idle not correct on cavs18+ platforms

### ISSUE THREAD

**Issue by kv2019i** [zephyrproject-rtos/zephyr#44213]
**Describe the bug**

A few issues found when comparing arch/xtensa/core/cpu_idle.c:arch_cpu_idle() against SOF mainline
implementation:

- code to set interrupt level to 5 is missing ()
           - https://github.com/thesofproject/sof/blob/main/src/arch/xtensa/include/arch/lib/wait.h
           - SOF tree commit "arch: xtensa: Support wait_for_interrupt on LX6"
- CONFIG_XTENSA_WAITI_BUG is not defined for cavs18+ platforms in Zephyr mainline
           - this is a hw property so should be defined in the soc Kconfig defaults

**Comment by kv2019i** [comment]
FYI @nashif @lgirdwood

**Comment by andyross** [comment]
I have a vague memory that this was a problem only on cAVS 1.5 (or maybe just on APL or something?).  It's entirely possible I was wrong.  If that's wrong then clearly we need to set that on all the affected hardware.

The interrupt level should be OK as-is though.  arch_cpu_idle() is only ever called with interrupts masked by arch_irq_lock(), whose action is precisely to set PS.INTLVL to XCHAL_EXCM_LEVEL.

**Comment by kv2019i** [comment]
Ack @andyross . I submitted a patch here https://github.com/zephyrproject-rtos/zephyr/pull/44694 . Actually the workaround is needed for all LX6 platforms, e.g. cAVS1.8 and newer.

**Comment by andyross** [comment]
Sounds great.  I see that merged, so closing this bug.
