### ISSUE TITLE
tests: drivers: pwm_api: PWM driver test doesn't compile for mec172xevb_assy6906

### ISSUE THREAD

**Issue by albertofloyd** [zephyrproject-rtos/zephyr#44240]
**Describe the bug**

Please also mention any information which could help others to understand
the problem you're facing:
 - What target platform are you using?
 - What have you tried to diagnose or workaround this issue?
 - ...

**To Reproduce**
1. cd tests/drivers/pwm/pwm_api
2. rm -rf build && west build -c -b mec172xevb_assy6906
3. See error

**Expected behavior**
Test should build succesfully

**Impact**
Cannot verify driver functionality in CI for mec172xevb_assy6906

**Logs and console output**
/home/jamezaar/ecwork/zephyr/tests/drivers/pwm/pwm_api/src/test_pwm.c:52:2: error: #error "Define a PWM device"
   52 | #error "Define a PWM device"
      |  ^~~~~
In file included from /home/jamezaar/ecwork/zephyr/include/toolchain/gcc.h:88,
                 from /home/jamezaar/ecwork/zephyr/include/toolchain.h:50,
                 from /home/jamezaar/ecwork/zephyr/include/init.h:10,
                 from /home/jamezaar/ecwork/zephyr/include/device.h:29,
                 from /home/jamezaar/ecwork/zephyr/tests/drivers/pwm/pwm_api/src/test_pwm.c:27:
/home/jamezaar/ecwork/zephyr/tests/drivers/pwm/pwm_api/src/test_pwm.c: In function 'get_pwm_device':
/home/jamezaar/ecwork/zephyr/include/device.h:96:39: error: '__device_dts_ord_PWM_DEV_NODE_ORD' undeclared (first use in this function)

**Comment by gmarull** [comment]
Note that test builds on `main` with the suggested command: `west build -b mec172xevb_assy6906 tests/drivers/pwm/pwm_api -p `. Closing, reopen if issue is observed again.
