### ISSUE TITLE
mimxrt1050_evk: build time too long for this platform

### ISSUE THREAD

**Issue by LixinGuoX** [zephyrproject-rtos/zephyr#44262]
**Describe the bug**
After this PR(#44150) merged, the total build and run time for mimxrt1050_evk has been extended a lot, from approximately 4-5 hours to 7-8 hours.
And found the the biggest change is in the build stage, time cost almost doubled.

**To Reproduce**
1. twister -p mimxrt1050_evk --device-testing --device-serial /dev/ttyACM0 -T tests/ -T samples/ - j 1

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain zephyr-sdk-0.13.2
 - Commit 40526f853e0643ab76fb401ba5c8ae50cd926bd2

**Comment by LixinGuoX** [comment]
Hi @danieldegrasse, any idea on this?

**Comment by nashif** [comment]
"-j 1" is really bad, you should try without -j1, not directly related to the issue and commits above, but this will speed up things considerably, i.e. build on process while you are flashing and testing on another.

**Comment by nashif** [comment]
@gmarull  @carlescufi  FYI

**Comment by LixinGuoX** [comment]
Without '- j 1' , it can speed up to 90min, will then reset back and see real effect of the patch above.

**Comment by mbolivar-nordic** [comment]
@danieldegrasse have a look at `/omit-if-no-ref/` here: https://elinux.org/Device_Tree_Source_Undocumented and see if adding it to your pinctrl nodes might work for you

**Comment by danieldegrasse** [comment]
@mbolivar thanks for the hint- build time seems to improve with that change, from 49 to 37 seconds. `devicetree_unfixed.h` goes from 103959 SLOC to 41148 SLOC. I've opened #44319 to include the new pin control headers, with that property present.
