### ISSUE TITLE
direction_finding_connectionless_rx/tx U-Blox Nora B106 EVK

### ISSUE THREAD

**Issue by peda4209** [zephyrproject-rtos/zephyr#44274]
I am trying to get the direction finding samples for the U-Blox Nora B106 EVK based on the Nordic 5340 running, but im having difficulties doing that. I have the hci_rpsmg loaded to the network core. When i try to compile the rx sample for the application core i get  an error that file 'system_nrf5340_network.c.obj.d does not exist in the directory: modules\hal_nordic\nrfx\CMakeFiles\modules__hal_nordic__nrfx.dir\8d68e5038effc38d99a85f2ef2451c80

for the tx sample i get following errors:
C:/Users/selp/ncs/v1.9.1/zephyr/subsys/bluetooth/host/adv.c:1926:12 error: variable 'info' has initializer but incomplete type
C:/Users/selp/ncs/v1.9.1/zephyr/subsys/bluetooth/host/adv.c:1927:7: error: struct 'bt_le_ext_adv_connected_info' has no member named 'conn'
C:/Users/selp/ncs/v1.9.1/zephyr/subsys/bluetooth/host/adv.c:1926:41: error: storage size of 'info' isn't known

I am using the latest version of the samples from this github repository and with the suggested modifications from the README.rst file.

**Comment by carlescufi** [comment]
This question is for the nRF Connect SDK, please ask in the Nordic Devzone instead.
