### ISSUE TITLE
Proposal for subsystem for media

### ISSUE THREAD

**Issue by asbjornsabo** [zephyrproject-rtos/zephyr#44295]

**Comment by nashif** [comment]
Please provide more information on what this is and what you want done

**Comment by hongshui3000** [comment]
In my opinion, SOF is a media subsystem, but it only supports the xtensa architecture.

**Comment by asbjornsabo** [comment]
My apologies - this was a too hasty attempt to split up another issue (https://github.com/zephyrproject-rtos/zephyr/issues/42523)
I will move this back as a sub-point there and close this issue.
