### ISSUE TITLE
[v2.7] net: gptp: type mismatch calculation error in gptp_mi

### ISSUE THREAD

**Issue by fulong82** [zephyrproject-rtos/zephyr#44310]
Interpreted from https://github.com/zephyrproject-rtos/zephyr/pull/44256

The NSEC_PER_SEC is an unsigned integer macro. Thus, -NSEC_PER_SEC will be treated as unsigned integer as well which lead to calculation error on 64bits integer variables.

The type mismatch causing nanosecond existed 9 digits value when passing to ptp_clock_set() API at gptp_update_local_port_clock():

![image](https://user-images.githubusercontent.com/19462849/160629746-3e2c8bf6-a010-47d3-88dd-7eb01256be22.png)

**Comment by jhedberg** [comment]
The associated PR was merged
