### ISSUE TITLE
boards: arm: rpi_pico: Enable CONFIG_ARM_MPU=y for raspberry pi pico board

### ISSUE THREAD

**Issue by noahp** [zephyrproject-rtos/zephyr#44318]
It looks like `CONFIG_ARM_MPU` is usually set in the board .defconfig for targets that include an MPU- the RP2040 (raspberry pi pico SOC) has an MPU, see datasheet here:
https://datasheets.raspberrypi.com/rp2040/rp2040-datasheet.pdf

I think it makes sense to add the config flag to `boards/arm/rpi_pico/rpi_pico_defconfig`, similar to the other boards?

For my own understanding, this flag is not included in the SOC defaults (eg, for this case, [here](https://github.com/zephyrproject-rtos/zephyr/blob/db5b2780bf76a3c61379c9e71cd20f6384c2ceb8/soc/arm/rpi_pico/rp2/Kconfig.series#L7-L18)), because it's desirable to have it only opt-in for a particular user configuration?

**Comment by DaAwesomeP** [comment]
Has anyone tested this?
