### ISSUE TITLE
Bluetooth:controller: Implement support for Advanced Scheduling in refactored LLCP

### ISSUE THREAD

**Issue by erbr-ot** [zephyrproject-rtos/zephyr#44339]
Advanced scheduling is not yet supported in refactored LLCP, and it should be
Also a test for this needs to be added, for example based on the babblesim test for 250 simultaneous connections

see pr #51239

**Comment by kruithofa** [comment]
From F2F in august 2022:
Action item:
- Enable auto-connection update via Kconfig so that correct behaviour is tested in babblesim test
- Find who will implement this behaviour?

**Comment by carlescufi** [comment]
Downgrading to Low priority because users can choose to revert back to the legacy LLCP which supports advanced scheduling.

**Comment by Thalley** [comment]
@carlescufi @kruithofa Should this be upgrade to Medium priority, since we are removing the legacy LLCP? 

@cvinayak Is this still an issue?
