### ISSUE TITLE
Bluetooth: controller: Handle parallel (across connections) CU/CPRs in refactored LLCP

### ISSUE THREAD

**Issue by erbr-ot** [zephyrproject-rtos/zephyr#44340]
In legacy LLCP exists a mechanism to enforce running only a single CU/CPR procedure at a time across all connections. 
The refactored LLCP should support this also, however it is suggested to do this without rejecting incoming requests, but take advantage of procedure timeout and 'queue' them up and perform them in some order.

**Comment by kruithofa** [comment]
Is fixed by PR #45163 and in 3.1 release
