### ISSUE TITLE

tests-ci : peripheral: gpio: 1pin test Timeout


### ISSUE THREAD

**Issue by hakehuang** [zephyrproject-rtos/zephyr#44391]
**Describe the bug**
1pin test is Timeout on zephyr-v3.0.0-1964-g199048b2ed45 on mimxrt1015_evk

see logs for details

**To Reproduce**
1. 
```
scripts/twister --device-testing --device-serial /dev/ttyACM0 -p mimxrt1015_evk  --sub-test peripheral.gpio
```
2. See error

**Expected behavior**
test pass

**Impact**

**Logs and console output**
```
*** Booting Zephyr OS build zephyr-v3.0.0-1964-g199048b2ed45  ***
Running test suite gpio_api_1pin_test
===================================================================
START - test_gpio_pin_configure_push_pull
Running test on port=GPIO_3, pin=21
ASSERTION FAIL [pin < config->mux_count] @ WEST_TOPDIR/zephyr/drivers/gpio/gpio_mcux_igpio.c:142
E: r0/a1:  0x00000004  r1/a2:  0x0000008e  r2/a3:  0x40184000
E: r3/a4:  0x60006131 r12/ip:  0x00000000 r14/lr:  0x60006269
E:  xpsr:  0x41000000
E: Faulting instruction address (r15/pc): 0x60008c6c
E: >>> ZEPHYR FATAL ERROR 4: Kernel panic on CPU 0
E: Current thread: 0x20000248 (test_gpio_pin_configure_push_pu)
E: Halting system

    
```

**Environment (please complete the following information):**
 - OS: (e.g. Linux )
 - Toolchain (e.g Zephyr SDK)
 - Commit SHA or Version used: zephyr-v3.0.0-1964-g199048b2ed45

**Comment by hakehuang** [comment]
@danieldegrasse , @dleach02 , @mmahadevan108

**Comment by hakehuang** [comment]
@danieldegrasse looks like the igpio does not compatible with latest pinmux code

**Comment by hakehuang** [comment]
![image](https://user-images.githubusercontent.com/800198/162358850-3e94214c-0af8-485b-8cf8-be1381a5edab.png)

**Comment by danieldegrasse** [comment]
@hakehuang See #44858, I reproduced and fixed the issue on the RT1015, but was not able to see a failure on the RT1060. What console output did you see on that platform, if any?

**Comment by hakehuang** [comment]
@danieldegrasse , rt1060 is ok, but the case requires some manual settings. connect gpio 23 to 22.
