### ISSUE TITLE
Zephyr RTOS support for Litex SoC with 64 bit rocket cpu.

### ISSUE THREAD

**Issue by Aravindh-Swaminathan** [zephyrproject-rtos/zephyr#44399]
**Is this request related to a missing driver support for a particular hardware platform, SoC or board? Please describe.**
Describe in details the hardware support being requested and why this support benefits Zephyr.
Requesting Zephyr RTOS support for Litex SoC with Rocket cpu (64 bit) and Xilinx AC701 board. 

**Describe why you are asking for this support?**
Describe why you are asking for this support instead of contributing it directly to the tree
Tried adding the board as mentioned in the Zephyr documentation. But I am getting lot of driver related errors while building the sample code. 

If this is a new board or SoC, please state whether you are willing to maintain the Zephyr support for it if it is included in the main tree
NA. 
**Additional context**
Add any other context or graphics (drag-and-drop an image) about the hardware here.
Board - Xilinx AC701
SoC-Litex
Cpu - Rocket

**Comment by fkokosinski** [comment]
Hi @Aravindh-Swaminathan!

> **Describe why you are asking for this support?** Describe why you are asking for this support instead of contributing it directly to the tree Tried adding the board as mentioned in the Zephyr documentation. But I am getting lot of driver related errors while building the sample code.

Could you perhaps share these errors that you're getting, or even better - create a draft PR so that we can take a look at your code?
