### ISSUE TITLE
Bluetooth: Controller: Extended and Periodic Advertising HCI Component Conformance Test Coverage

### ISSUE THREAD

**Issue by cvinayak** [zephyrproject-rtos/zephyr#44439]
List of pending Extended and Periodic Advertising HCI Component Conformance Test Coverage

- [x] HCI/CCO/BI-33-C - [Invalid LE Set Periodic Advertising Data Parameters]
- [x] HCI/DDI/BI-01-C - [Reject Invalid Extended Advertising Parameters]
- [x] HCI/DDI/BI-13-C - [Reject Invalid Periodic Advertising Enable Command]
  - Added check for partial data
- [x] HCI/DDI/BI-15-C - [Reject Set Extended Advertising Parameters Command using a Periodic
Advertising Set and Incompatible Advertising is Specified - Non-connectable non-scannable
anonymous undirected]
- [x] HCI/DDI/BI-16-C - [Reject Set Extended Advertising Parameters Command using a Periodic
Advertising Set and Incompatible Advertising is Specified - Non-connectable non-scannable
anonymous directed]
- [x] HCI/DDI/BI-17-C - [Reject Set Extended Advertising Parameters Command using a Periodic
Advertising Set and Incompatible Advertising is Specified - Legacy connectable and scannable
undirected]
- [x] HCI/DDI/BI-18-C - [Reject Set Extended Advertising Parameters Command using a Periodic
Advertising Set and Incompatible Advertising is Specified - Legacy connectable directed (low duty
cycle)]
- [x] HCI/DDI/BI-19-C - [Reject Set Extended Advertising Parameters Command using a Periodic
Advertising Set and Incompatible Advertising is Specified - Legacy connectable directed (high duty
cycle)]
- [x] HCI/DDI/BI-20-C - [Reject Set Extended Advertising Parameters Command using a Periodic
Advertising Set and Incompatible Advertising is Specified - Legacy scannable undirected]
- [x] HCI/DDI/BI-21-C - [Reject Set Extended Advertising Parameters Command using a Periodic
Advertising Set and Incompatible Advertising is Specified - Legacy non-connectable and nonscannable,
undirected]
- [x] HCI/DDI/BI-22-C - [Reject Set Extended Advertising Parameters Command using a Periodic
Advertising Set and Incompatible Advertising is Specified - Extended connectable undirected]
- [x] HCI/DDI/BI-23-C - [Reject Set Extended Advertising Parameters Command using a Periodic
Advertising Set and Incompatible Advertising is Specified - Extended connectable directed]
- [x] HCI/DDI/BI-24-C - [Reject Set Extended Advertising Parameters Command using a Periodic
Advertising Set and Incompatible Advertising is Specified - Extended scannable undirected]
- [x] HCI/DDI/BI-25-C - [Reject Set Extended Advertising Parameters Command using a Periodic
Advertising Set and Incompatible Advertising is Specified - Extended scannable directed]
- [x] HCI/DDI/BI-26-C - [Reject Set Periodic Advertising Parameters Command when the Associated
Handle Specifies Incompatible Advertising - Non-connectable non-scannable
anonymous undirected]
- [x] HCI/DDI/BI-27-C - [Reject Set Periodic Advertising Parameters Command when the Associated
Handle Specifies Incompatible Advertising - Non-connectable non-scannable
anonymous directed]
- [x] HCI/DDI/BI-28-C - [Reject Set Periodic Advertising Parameters Command when the Associated
Handle Specifies Incompatible Advertising - Legacy connectable and scannable
undirected]
- [x] HCI/DDI/BI-29-C - [Reject Set Periodic Advertising Parameters Command when the Associated
Handle Specifies Incompatible Advertising - Legacy connectable directed (low duty
cycle)]
- [x] HCI/DDI/BI-30-C - [Reject Set Periodic Advertising Parameters Command when the Associated
Handle Specifies Incompatible Advertising - Legacy connectable directed (high duty
cycle)]
- [x] HCI/DDI/BI-31-C - [Reject Set Periodic Advertising Parameters Command when the Associated
Handle Specifies Incompatible Advertising - Legacy scannable undirected]
- [x] HCI/DDI/BI-32-C - [Reject Set Periodic Advertising Parameters Command when the Associated
Handle Specifies Incompatible Advertising - Legacy non-connectable and nonscannable,
undirected]
- [x] HCI/DDI/BI-33-C - [Reject Set Periodic Advertising Parameters Command when the Associated
Handle Specifies Incompatible Advertising - Extended connectable undirected]
- [x] HCI/DDI/BI-34-C - [Reject Set Periodic Advertising Parameters Command when the Associated
Handle Specifies Incompatible Advertising - Extended connectable directed]
- [x] HCI/DDI/BI-35-C - [Reject Set Periodic Advertising Parameters Command when the Associated
Handle Specifies Incompatible Advertising - Extended scannable undirected]
- [x] HCI/DDI/BI-36-C - [Reject Set Periodic Advertising Parameters Command when the Associated
Handle Specifies Incompatible Advertising - Extended scannable directed]
- [x] HCI/DDI/BI-37-C - [Reject Set Periodic Advertising Enable Command when the Associated
Handle Specifies Incompatible Advertising - Non-connectable non-scannable
anonymous undirected]
- [x] HCI/DDI/BI-38-C - [Reject Set Periodic Advertising Enable Command when the Associated
Handle Specifies Incompatible Advertising - Non-connectable non-scannable
anonymous directed]
- [x] HCI/DDI/BI-39-C - [Reject Set Periodic Advertising Enable Command when the Associated
Handle Specifies Incompatible Advertising - Non-connectable non-scannable
anonymous directed]
- [x] HCI/DDI/BI-40-C - [Reject Set Periodic Advertising Enable Command when the Associated
Handle Specifies Incompatible Advertising - Legacy connectable directed (low duty
cycle)]
- [x] HCI/DDI/BI-41-C - [Reject Set Periodic Advertising Enable Command when the Associated
Handle Specifies Incompatible Advertising - Legacy connectable directed (high duty
cycle)]
- [x] HCI/DDI/BI-42-C - [Reject Set Periodic Advertising Enable Command when the Associated
Handle Specifies Incompatible Advertising - Legacy scannable undirected]
- [x] HCI/DDI/BI-43-C - [Reject Set Periodic Advertising Enable Command when the Associated
Handle Specifies Incompatible Advertising - Legacy non-connectable and nonscannable,
undirected]
- [x] HCI/DDI/BI-44-C - [Reject Set Periodic Advertising Enable Command when the Associated
Handle Specifies Incompatible Advertising - Extended connectable undirected]
- [x] HCI/DDI/BI-45-C - [Reject Set Periodic Advertising Enable Command when the Associated
Handle Specifies Incompatible Advertising - Extended connectable directed]
- [x] HCI/DDI/BI-46-C - [Reject Set Periodic Advertising Enable Command when the Associated
Handle Specifies Incompatible Advertising - Extended scannable undirected]
- [x] HCI/DDI/BI-47-C - [Reject Set Periodic Advertising Enable Command when the Associated
Handle Specifies Incompatible Advertising - Extended scannable directed]
- [x] HCI/DDI/BI-50-C - [LE Set Periodic Advertising Parameters, Reject, Data Too Long, LE 1M PHY]
  - Inclusive verdict, > 191 bytes AD data not supported in the implementation
- [x] HCI/DDI/BI-51-C - [LE Set Periodic Advertising Parameters, Reject, Data Too Long, LE Coded PHY]
  - Inclusive verdict, > 191 bytes AD data not supported in the implementation
- [x] HCI/DDI/BI-52-C - [Reject Set Periodic Advertising Data Command when Advertising Data Too Long]
  - Inclusive verdict, > 191 bytes AD data not supported in the implementation
- [x] HCI/DDI/BI-53-C - [Reject LE Set Periodic Advertising Enable Command, Legacy Packet - Non-connectable non-scannable anonymous undirected]
- [x] HCI/DDI/BI-54-C - [Reject LE Set Periodic Advertising Enable Command, Legacy Packet - Non-connectable non-scannable anonymous directed]
- [x] HCI/DDI/BI-58-C - [Reject LE Set Periodic Advertising Enable Command, Legacy Packet - Extended connectable undirected]
- [x] HCI/DDI/BI-59-C - [Reject LE Set Periodic Advertising Enable Command, Legacy Packet - Extended connectable directed]
- [x] HCI/DDI/BI-60-C - [Reject LE Set Periodic Advertising Enable Command, Legacy Packet - Extended scannable undirected]
- [x] HCI/DDI/BI-61-C - [Reject LE Set Periodic Advertising Enable Command, Legacy Packet - Extended scannable directed]
- [x] HCI/DDI/BI-62-C - [Reject Set Extended Advertising Parameters Command, Packet Too Long, LE Coded]
  - Inclusive verdict, > 191 bytes AD data not supported in the implementation
- [x] HCI/DDI/BI-63-C - [Reject Set Extended Advertising Data Command, Data Too Long, LE 1M PHY]
- [x] HCI/DDI/BI-64-C - [Reject Set Extended Advertising Data Command, Data Too Long, LE Coded PHY]
- [x] HCI/DDI/BI-65-C - [Reject Set Extended Scan Response Data Command, Data Too Long, LE 1M PHY]
- [x] HCI/DDI/BI-66-C - [Reject Set Extended Scan Response Data Command, Data Too Long, LE Coded PHY]
- [x] HCI/DDI/BI-67-C - [Reject Invalid Periodic Advertising Parameters]

**Comment by carlescufi** [comment]
@cvinayak can this be closed now?

**Comment by cvinayak** [comment]
@carlescufi I have couple more PRs to send that have conflict with #45205, hence need to wait for that to be merged.
