### ISSUE TITLE
LE Audio: Remove `struct bt_codec *codec` parameter from `bt_audio_broadcast_sink_sync`

### ISSUE THREAD

**Issue by Thalley** [zephyrproject-rtos/zephyr#44455]
**Is your enhancement proposal related to a problem? Please describe.**
The `codec` parameter seems to be unused, and it is odd that we application need to provide a codec when creating a sink. 

**Describe the solution you'd like**
Remove the parameter. 

The codec information could be inferred from the BIGInfo once the PA is synced and provided by the `syncable` callback. 

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by Casper-Bonde-Bose** [comment]
A sink would rely on knowing the parameters of the stream, hence when removing this parameter, please check that the stack will set the codec config for the stream into the stream instance data. (`stream->codec` is where you would normally extract the information when setting up the codec)
