### ISSUE TITLE
Add guide for disabling MSD on JLink OB devices and link to from smp_svr page

### ISSUE THREAD

**Issue by lairdjm** [zephyrproject-rtos/zephyr#44497]
**Is your enhancement proposal related to a problem? Please describe.**
This issue has arisen many times now where someone is unable to perform a firmware update on usually a nordic development board using mcumgr because by default the MSD endpoint is enabled and this forces the CDC endpoint to one with a lower size, which is incompatible with the large firmware update packet sizes

**Describe the solution you'd like**
Add a new documentation page describing how to disable MSD and allow firmware updating to work

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by carlescufi** [comment]
We already have https://docs.zephyrproject.org/latest/guides/tools/nordic_segger.html#disabling-the-mass-storage-device-functionality.

So all we need is a link.
