### ISSUE TITLE
net: tcp: Context still open after timeout on connect

### ISSUE THREAD

**Issue by ssharks** [zephyrproject-rtos/zephyr#44504]
**Describe the bug**
When a TCP connect fails with a timeout, because there is no communication possible, the context is not cleaned up properly.

**To Reproduce**
Use the testcase as submitted in the pull request
https://github.com/zephyrproject-rtos/zephyr/pull/44501

Run the test using
./scripts/twister -T tests/net/socket/tcp -p qemu_x86

**Expected behavior**
When a socket connect timeouts, I would expect the context to close, no connection has been build, so why do we need to close it?

**Impact**
Could cause resource leakage in case of a bad network connection.

**Environment:**
 - OS: (Ubuntu 20.04)
 - Target: Qemu x86
 - Toolchain: Zephyr SDK 0.13.2
 - Commit: Pull request https://github.com/zephyrproject-rtos/zephyr/pull/44501

**Comment by 12csw1** [comment]
Should this issue be labeled as priority: low?

We are doing research about “Issue Priority Prediction". We have developed a tool to automatically label the priority of an issue. The basic idea is to employ Bert model to encode the textual and code descriptions of the issue, and incorporate the issue’s attributes in the model, then apply multi-task learning to facilitate other information boosting the prediction performance. 
 We have conducted experiments on four GitHub projects with 21700 issues, and results show that [79 accuracy]() can be achieved.

Our tool shows that this issue has a very large possibility to be labeled as priority: low 
Could you please tell us whether it should be labeled as priority: low?
And if you have any comments or suggestions with this tool, could you please tell us? 
Thank you so much.

**Comment by rlubos** [comment]
> So if I understand you correctly, a socket should be closed even when the connect fails?

That's right, once opened the only way to clean up its resources is to close it. Anyway, it's generally expected that you always close a socket that is no longer used, it's not only about net_context but also the file description needs to be freed etc.
