### ISSUE TITLE
twister: test_plan configuration based on manifest update

### ISSUE THREAD

**Issue by JordanYates** [zephyrproject-rtos/zephyr#44593]
**Is your enhancement proposal related to a problem? Please describe.**

PR's which update the manifest file `west.yml` do not trigger the appropriate level of testing.

For example, #43795 updated the hal_stm32 module, but did not trigger tests which would have caught compilation errors on in-tree drivers (#44486).

The following test would have caught the above problem:
``
zephyr/scripts/twister -T zephyr/tests/drivers/build_all/ethernet/ --all
``

**Describe the solution you'd like**

If the manifest file is updated:
* the `--all` option should be enabled.
* `tests/drivers/build_all` should be added as a testcase root

Potentially other tests would also be useful to enable, but testing all drivers still compile is a good start.

**Comment by nashif** [comment]
This has been addressed already, manifest changes now use tags to run test of relevant area.
