### ISSUE TITLE
Backport 'doc: Add link to J-Link virtual MSD disable for SMP' to 2.7

### ISSUE THREAD

**Issue by lairdjm** [zephyrproject-rtos/zephyr#44618]
**Describe the bug**
This is a backport request for the upcoming zephyr 2.7 release to add a link in the documentation to show how to disable MSD on some devices to prevent issues when using the smp_svr sample application. Note that one file in the original update is not present in 2.7 and can be skipped.
Original PR: https://github.com/zephyrproject-rtos/zephyr/pull/44500

**Comment by mbolivar-nordic** [comment]
Closing as dupe of https://github.com/zephyrproject-rtos/zephyr/issues/44497 (unclear why original issue is Enhancement while this is bug)
