### ISSUE TITLE
mimxrt1050_evk_qspi crash or freeze when accessing flash

### ISSUE THREAD

**Issue by jeppenodgaard** [zephyrproject-rtos/zephyr#44676]
**Describe the bug**
Accessing the flash causes the system to hang forever or crash depending on what application is run.

**To Reproduce**
1. west build -p -b mimxrt1050_evk_qspi zephyr/samples/drivers/flash_shell/ && west flash
2. flash page_count

**Expected behavior**
Shell outputs `Flash device contains 2048 pages.`

**Impact**
Sheel outputs
```
[00:00:19.245,025] <err> os: ***** MPU FAULT *****
[00:00:19.245,086] <err> os:   Instruction Access Violation
[00:00:19.245,117] <err> os: r0/a1:  0x6000de48  r1/a2:  0x80002ab8  r2/a3:  0x80002abc
[00:00:19.245,117] <err> os: r3/a4:  0xf011d418 r12/ip:  0x00000000 r14/lr:  0x6000d0cf
[00:00:19.245,117] <err> os:  xpsr:  0x60000000
[00:00:19.245,117] <err> os: Faulting instruction address (r15/pc): 0xf011d418
[00:00:19.245,208] <err> os: >>> ZEPHYR FATAL ERROR 0: CPU exception on CPU 0
[00:00:19.245,208] <err> os: Current thread: 0x80000620 (shell_uart)
[00:00:19.308,502] <err> os: Halting system
```

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain Zephyr SDK
 - Version 3.0.0 used

**Additional context**
Changing to `zephyr,flash-controller = &is25wp064; ` from https://github.com/zephyrproject-rtos/zephyr/blob/b0089162e91adee685a5d13d724fb60c048b7634/boards/arm/mimxrt1050_evk/mimxrt1050_evk_qspi.dts#L13 seems to resolve the issue. It also aligns with mimxrt1050_evk.dts https://github.com/zephyrproject-rtos/zephyr/blob/f1e75dea501630343bf259cdac3070baa238724b/boards/arm/mimxrt1050_evk/mimxrt1050_evk.dts#L29

**Comment by mmahadevan108** [comment]
@jeppenodgaard . Could you please submit a PR with the proposed fix you mentioned.

**Comment by danieldegrasse** [comment]
@jeppenodgaard after some internal discussion, we're going to fix this issue as part of a broader PR since it is present on several of our evaluation kits. Are you ok using the fix you have for the time being while that PR is created and tested?

**Comment by jeppenodgaard** [comment]
@danieldegrasse Sure! Is there a link to the PR or is it to be created?

**Comment by danieldegrasse** [comment]
@jeppenodgaard to be created-likely sometime today or Monday.

**Comment by danieldegrasse** [comment]
@jeppenodgaard #44762 should fix the `flash-controller` to use the correct node label

**Comment by jeppenodgaard** [comment]
@danieldegrasse thanks, I'll try it out 😊

**Comment by jeppenodgaard** [comment]
Cannot reproduce with your branch :+1:
