### ISSUE TITLE
Add support for Rigado BMD-3XX-EVAL boards

### ISSUE THREAD

**Issue by bencorrado** [zephyrproject-rtos/zephyr#4475]
Add board support for Rigado's BMD-300, BMD-301, BMD-350 & BMD-330 developments boards all using the nRF52832 SoC from Nordic.  These boards integrate the Segger debugger as well.

Boards to support:
[BMD-300-EVAL](https://www.rigado.com/products/modules/bmd-300/)
[BMD-301-EVAL](https://www.rigado.com/products/modules/bmd-301/)
[BMD-330-EVAL](https://www.rigado.com/products/modules/bmd-330/)
[BMD-350-EVAL](https://www.rigado.com/products/modules/bmd-350/)

**Comment by carlescufi** [comment]
@bencorrado are you planning to add support for these boards?

**Comment by ioannisg** [comment]
@bencorrado Do you have a plan to work on this board porting?

**Comment by carlescufi** [comment]
Please submit a Pull Request
