### ISSUE TITLE
Nominate @brgl as contributor

### ISSUE THREAD

**Issue by brgl** [zephyrproject-rtos/zephyr#44752]
# Nomination

I would like to request some additional permissions, like adding labels to PRs/issues and adding reviewers as well as launching CI for first-time contributors. This will help me with my job as the maintainer of the lvgl module.

## GitHub User

1. Bartosz Golaszewski
1. brgl
1. Huawei

## Supporting Documents

https://github.com/zephyrproject-rtos/zephyr/pull/41336
https://github.com/zephyrproject-rtos/zephyr/pull/43170
https://github.com/zephyrproject-rtos/zephyr/pull/43365
https://github.com/zephyrproject-rtos/zephyr/pull/44267
https://github.com/zephyrproject-rtos/zephyr/pull/43927

**Comment by nashif** [comment]
invite sent.
