### ISSUE TITLE
Build failure with CONFIG_NET_DEBUG_APP=y

### ISSUE THREAD

**Issue by vakulgarg** [zephyrproject-rtos/zephyr#4481]
Sample applications fail to build on defining CONFIG_NET_DEBUG_APP=y in project configuration.
Error log with zephyr/samples/net/lwm2m_client/ is given below.

-------------------------------------------------------------------------------------------------------------
  LINK    zephyr.lnk
subsys/built-in.o: In function `net_app_connect':
/home/b16394/network_protocols/networkprotocols/WP1/zephyr/subsys/net/lib/app/client.c:599: undefined reference to `_net_app_select_net_ctx'
collect2: error: ld returned 1 exit status
make[2]: *** [/home/b16394/network_protocols/networkprotocols/WP1/zephyr/Makefile:876: zephyr_prebuilt.elf] Error 1
make[2]: Leaving directory '/home/b16394/network_protocols/networkprotocols/WP1/zephyr/samples/net/lwm2m_client/outdir/qemu_x86'
make[1]: *** [Makefile:178: sub-make] Error 2
make[1]: Leaving directory '/home/b16394/network_protocols/networkprotocols/WP1/zephyr'
make: *** [/home/b16394/network_protocols/networkprotocols/WP1/zephyr/Makefile.inc:82: all] Error 2

**Comment by mike-scott** [comment]
Hello, may I have the command you are using to build the app, SDK version and host OS / version?

**Comment by vakulgarg** [comment]
I am compiling lwm2m_client after setting CONFIG_NET_DEBUG_APP=y using command 'make' inside zephyr/samples/net/lwm2m_client. The zephyr code is from HEAD of master branch. 

The host machine is fedora 26.
The SDK version is 0.9.1.

**Comment by mike-scott** [comment]
@jukkar yep, I get this same error.
