### ISSUE TITLE
CSIS: Add support for parallel operations and make implementation thread-safe

### ISSUE THREAD

**Issue by MariuszSkamra** [zephyrproject-rtos/zephyr#44867]
**Is your enhancement proposal related to a problem? Please describe.**
The current implementation disallows parallel operations on different set members. This might be problematic, as CSIS will be most likely used from different contexts.

Looking at the code, there is a static structure active_members that holds context. I guess the user might get into trouble when tries to use this API with multithreads and forbids concurrent operations on 2 sets.

**Comment by asbjornsabo** [comment]
Zephyr-bt F2F: Applies for all profiles in LA Audio.

**Comment by Thalley** [comment]
This is still valid, but needs to be split up into multiple issues, as fixing the entire LE Audio stack in a single go would be impossible

**Comment by Thalley** [comment]
The parallel operation support was added by https://github.com/zephyrproject-rtos/zephyr/issues/44867. The thread-safe part require a new issue.
