### ISSUE TITLE
Support ESP32 ADC

### ISSUE THREAD

**Issue by wolterhv** [zephyrproject-rtos/zephyr#44908]
## Initial description

This is a request to support the ADC peripheral on the ESP32 board. This would benefit Zephyr since the ESP32 is a popular board; supporting it better may increase Zephyr's user base.

I will be working to implement support for this peripheral. This issue is meant to track progress and signal the community that there are efforts being made in this area. This is a volunteering effort from a community member, not involved in any way with Espressif (OEM).

Some documents of interest:

* [ESP32 Technical Reference Manual](https://www.espressif.com/sites/default/files/documentation/esp32_technical_reference_manual_en.pdf). This has detailed information about the subsystems in the board, ADC and clocks included.
* [ESP32 Datasheet](https://www.espressif.com/sites/default/files/documentation/esp32_datasheet_en.pdf). This has some information about the ESP32 internals, though it is less in-depth than the TRM.

### First PR

- [x] Support all attenuation levels (raw to voltage conversion)
- [ ] Implement driver-side functions from `adc_context.h`
- [ ] Update adc example to support ESP32
- [ ] Support calibration
    - [ ] Look into adc_vref_to_gpio
    - [ ] Look into esp_adc_cal_check_efuse
    - [x] Look into esp_adc_cal_characterize
    - [ ] Look into the three references for calibration, which seem to vary by chip
    production date: two point, eFuse vRef, default vRef
- [ ] Support both ADCs
- [x] Support only the RTC clock
- [x] Fix that ESP-IDF and Zephyr give completely different readings
- [x] Implement a "get attenuation" method (since there is a "set attenuation" one)
- [ ] Implement automated hardware test application and test circuit to test all functionality dimensions (ADC number, channel, sampling period, reference voltage, attenuation, resolution)

### Deferred

- [ ] Support the different clocks available
- [ ] Support other ESP32 family members
    - [ ] Support different devices in the raw to voltage conversion (ESP32-S2 has
    different lookup table values). This data should be encoded in the DTS.
    - [ ] Check out the exceptions that are applied throughout the ESP-IDF source
    code to handle different family members
- [ ] Support clock division configuration (adc_set_clk_div)
- [ ] Check out what adc_set_data_width is for
- [ ] Support the ULP (adc1_ulp_enable)
- [ ] Find out whether differential channels are supported -> no mention on doc,
assume not supported
- [ ] Add warnings for ADC 2 that it will block if WiFi is being used (shared
hardware)
- [ ] Find out whether non-single reading is supported (check out ESP-IDF example)

### Nice to haves

- [ ] Get GPIO number associated to ADC channel
- [ ] Support digital ADC
- [ ] Unit testing

**Comment by sylvioalves** [comment]
@wolterhv, great to see that.  
Please, consider using `hal` calls so we can keep this a common approach.  
https://github.com/zephyrproject-rtos/hal_espressif/blob/zephyr/components/hal/adc_hal.c

**Comment by sylvioalves** [comment]
@wolterhv Do you have updates?

**Comment by wolterhv** [comment]
@sylvioalves No progress yet, actually just getting to it now. Let me see if I understand the suggested approach correctly: the idea is to implement a HAL-based ADC driver so that it works for all versions of ESP32, and implement the chip-specific code in the HAL?

**Comment by gweisberger** [comment]
Any updates?

**Comment by prayassamriya** [comment]
@wolterhv can you please provide rough estimate by when it could be ready. I would like to plan my project accordingly

**Comment by prayassamriya** [comment]
@sylvioalves, is there any updates on adc driver development for ESP?

**Comment by wolterhv** [comment]
For reference, at least some of the features in the task list have been implemented by @marekmatej in PR https://github.com/zephyrproject-rtos/zephyr/pull/52751
