### ISSUE TITLE
build fails for nucleo wb55 rg board.

### ISSUE THREAD

**Issue by 99003662** [zephyrproject-rtos/zephyr#44966]
Build fails for p-nucleo wb55rg board.
      Hi am using vs code with nrfconnect through vs code. while building am getting below error.
![image](https://user-images.githubusercontent.com/78849757/164165254-1ab5b26f-357b-48d1-b08b-3dcb47b3c422.png)

kindly suggest .

**Comment by erwango** [comment]
Please run "west update"

**Comment by erwango** [comment]
Also, note that nucleo_wb55rg might not be able to work in NRFConnect, you might need to fetch/use Zephyr directly.

**Comment by erwango** [comment]
Closing as this is not a Zephr issue, but a misuse of nrf SDK
