### ISSUE TITLE
tests: drivers: can: timing: failure to set bitrate of 800kbit/s on nucleo_g474re

### ISSUE THREAD

**Issue by henrikbrixandersen** [zephyrproject-rtos/zephyr#44985]
**Describe the bug**
The `drivers/can/can_stm32fd.c` uses the PCLK clock as clock source for the FDCAN IP. This clock is 170MHz, at least on the nucleo_g474re board. This prevents the use of the CAN in Automation (CiA) standard bitrate of 800kbit/s (170000000/(n * 800000) is not an integer).

**To Reproduce**
1. west build -b nucleo_g474re tests/drivers/can/timing/
2. west flash
3. See error

**Expected behavior**
CAN in Automation standard bitrates can be met.

**Impact**
CAN in Automation standard bitrates cannot be met, causing the CAN timing tests to fail.

**Logs and console output**
```
*** Booting Zephyr OS build zephyr-v3.0.0-2817-g536e06118159  ***
testing on device CAN_1
Running test suite can_timing_tests
===================================================================
START - test_set_timing_min
 PASS - test_set_timing_min in 0.1 seconds
===================================================================
START - test_set_timing_max
 PASS - test_set_timing_max in 0.1 seconds
===================================================================
START - test_timing
testing bitrate 20000, sample point 87.5% (valid): prop_seg = 0, phase_seg1 = 217, phase_seg2 = 32, prescaler = 34 OK, sample point error 0.3%
testing bitrate 50000, sample point 87.5% (valid): prop_seg = 0, phase_seg1 = 174, phase_seg2 = 25, prescaler = 17 OK, sample point error 0.0%
testing bitrate 125000, sample point 87.5% (valid): prop_seg = 0, phase_seg1 = 237, phase_seg2 = 34, prescaler = 5 OK, sample point error 0.0%
testing bitrate 250000, sample point 87.5% (valid): prop_seg = 0, phase_seg1 = 118, phase_seg2 = 17, prescaler = 5 OK, sample point error 0.0%
testing bitrate 500000, sample point 87.5% (valid): prop_seg = 0, phase_seg1 = 147, phase_seg2 = 22, prescaler = 2 OK, sample point error 0.5%
testing bitrate 800000, sample point 80.0% (valid): 
    Assertion failed at WEST_TOPDIR/zephyr/tests/drivers/can/timing/src/main.c:194: test_timing_values: (sp_err >= 0 is false)
unknown error -22
 FAIL - test_timing in 0.80 seconds
===================================================================
START - test_timing_data
testing bitrate 500000, sample point 87.5% (valid): prop_seg = 0, phase_seg1 = 28, phase_seg2 = 5, prescaler = 10 OK, sample point error 2.3%
testing bitrate 1000000, sample point 87.5% (valid): prop_seg = 0, phase_seg1 = 28, phase_seg2 = 5, prescaler = 5 OK, sample point error 2.3%
testing bitrate 500000, sample point 90.0% (valid): prop_seg = 0, phase_seg1 = 17, phase_seg2 = 2, prescaler = 17 OK, sample point error 0.0%
testing bitrate 500000, sample point 80.0% (valid): prop_seg = 0, phase_seg1 = 15, phase_seg2 = 4, prescaler = 17 OK, sample point error 0.0%
testing bitrate 500000, sample point 100.0% (invalid): OK
testing bitrate 8000001, sample point 75.0% (invalid): OK
 PASS - test_timing_data in 0.60 seconds
===================================================================
Test suite can_timing_tests failed.
===================================================================
PROJECT EXECUTION FAILED
```

**Environment (please complete the following information):**
 - OS: Ubuntu Linux 20.04 LTS
 - Toolchain: Zephyr SDK v0.14.0
 - Commit SHA: 536e061181599c94e19991cf4550336d1ec2cbb4

**Comment by 12csw1** [comment]
Should this issue be labeled as priority: high?

We are doing research about “Issue Priority Prediction". We have developed a tool to automatically label the priority of an issue. The basic idea is to employ Bert model to encode the textual and code descriptions of the issue, and incorporate the issue’s attributes in the model, then apply multi-task learning to facilitate other information boosting the prediction performance. 
 We have conducted experiments on four GitHub projects with 21700 issues, and results show that [79 accuracy]() can be achieved.

Our tool shows that this issue has a very large possibility to be labeled as priority: high 
Could you please tell us whether it should be labeled as priority: high?
And if you have any comments or suggestions with this tool, could you please tell us? 
Thank you so much.
