### ISSUE TITLE
stm32: usart: rx pin inversion missing

### ISSUE THREAD

**Issue by helo9** [zephyrproject-rtos/zephyr#45089]
**Is your enhancement proposal related to a problem? Please describe.**
SBUS is a common serial protocol in radio control that uses inverted logic (1=L, 0=H). 

**Describe the solution you'd like**
STM32 can natively support this, by setting pin `RXINV` in `USART_CR2` for many chips. Therefore I would add this option
to the devicetree bindings and the API.

**Describe alternatives you've considered**
Leave the functionality out, as it is hardly used.

**Comment by FRASTM** [comment]
That could be an USART  _option flag_ like it is done withthe PWM_STM32_COMPLEMENTARY by the https://github.com/zephyrproject-rtos/zephyr)/include/zephyr/dt-bindings/pwm/stm32_pwm.h

**Comment by erwango** [comment]
@helo9, Can you check if what you request is matching following feature which was merged recently ?https://github.com/zephyrproject-rtos/zephyr/pull/44487/

**Comment by helo9** [comment]
@erwango have seen those changes, but they do not exactly help me. Have already implemented a prototype of what I need: https://github.com/helo9/zephyr/commit/bd5c9e00fb2b1d8f17b693c4168bb4fa668cc88d

@FRASTM I thought about adding this to the `uart_stm32_init` and maybe the `uart_stm32_configure` functions.

I'll open a PR with my branch, so we can discuss it there.

**Comment by helo9** [comment]
was closed by #45124
