### ISSUE TITLE
mimxrt1050_evk: GPIO button pushed only once

### ISSUE THREAD

**Issue by CarloWM** [zephyrproject-rtos/zephyr#45129]
**Is your enhancement proposal related to a problem? Please describe.**
the GPIO button can only be pushed once. than it fails to push again. this is because in the DTS the up function is missing

	gpio_keys {
		compatible = "gpio-keys";
		user_button: button_0 {
			label = "User SW8";
			gpios = <&gpio5 0 GPIO_ACTIVE_LOW>;
		};
	};

**Describe the solution you'd like**
change gpios from only GPIO_ACTIVE_LOW to pull GPIO_PULL_UP and GPIO_ACTIVE_LOW. 

	gpio_keys {
		compatible = "gpio-keys";
		user_button: button_0 {
			label = "User SW8";
			gpios = <&gpio5 0 (GPIO_PULL_UP | GPIO_ACTIVE_LOW)>;
		};
	};

**Describe alternatives you've considered**
as alternative it is possible to make a overlay and change it there. but this has to be done by every user itself. and the samples wouldn't work out of the box.

**Comment by danieldegrasse** [comment]
@CarloWM verified this issue also exists on an RT1064- can you test the PR #45214 to ensure it fixes the issue for you?
