### ISSUE TITLE
parsetab.py is getting corrupted when multiple instance of sanitycheck is executed simultaneously

### ISSUE THREAD

**Issue by mnirmaladevi** [zephyrproject-rtos/zephyr#4513]
When we run /scripts/sanitycheck command with multiple instance simultaneously the /scripts/parsetab.py generated file is getting corrupted.

**Command:**
$ZEPHYR_BASE//scripts/sanitycheck -z outdir/quark_se_c1000_devboard/zephyr.elf

When above command is executed sanitycheck command generates parsetab.py file inside the $ZEPHYR_BASE/scripts directory. When multiple instance of the above command is executed the autogenerated file parsetab.py gets corrupted since it is in the source code tree directory.

**Comment by andrewboie** [comment]
this is probably a PLY option we need to set in scripts/sanity_chk/expr_parser.py, these files are generated by the PLY library

**Comment by nashif** [comment]
Just wondering, why do you need to run multiple instances of sanitycheck ?

**Comment by mnirmaladevi** [comment]
Our automation environment runs multiple instance of sanitycheck for different targets on the same workspace and hence facing this issue.

**Comment by nashif** [comment]
solved by setting environment variable PARSETAB_DIR for each run

**Comment by jeremybettis** [comment]
This appears to be a problem with twister also.
