### ISSUE TITLE
MCUBoot Usage Fault on RT1060 EVK

### ISSUE THREAD

**Issue by danieldegrasse** [zephyrproject-rtos/zephyr#45182]
**Describe the bug**
When flashing the MCUBoot bootloader (`mcuboot/boot/zephyr`), the bootloader encounters a usage fault and does not load a bootable image. Reproduced on zephyr-v3.0.0-3118-g82634eda93, with a RT1060 EVK

**To Reproduce**
1. mkdir build; cd build
2. cmake -DBOARD=mimxrt1060_evk mcuboot/boot/zephyr
3. make
4. make flash
5. see usage fault

**Expected behavior**
The bootloader should load an image if a valid one is found, or print an error about not finding a valid image.

**Impact**
MCUboot support for the RT1060 EVK is not functional.

**Logs and console output**
```
I: Starting bootloader
E: ***** USAGE FAULT *****
E:   Illegal use of the EPSR
E: r0/a1:  0x6000a9e8  r1/a2:  0x8000a804  r2/a3:  0x8000a7f4
E: r3/a4:  0x00000000 r12/ip:  0x00000000 r14/lr:  0x60008ae1
E:  xpsr:  0x60000000
E: Faulting instruction address (r15/pc): 0x00000000
E: >>> ZEPHYR FATAL ERROR 0: CPU exception on CPU 0
E: Current thread: 0x800000f0 (unknown)
E: Halting system
```

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04 (WSLv1)
 - Toolchain: Zephyr SDK
 - Commit SHA or Version used: zephyr-v3.0.0-3118-g82634eda93

**Comment by kunoh** [comment]
Hi, I'm getting a similar error on RT1050 EVKB QSPI

I: Starting bootloader
E: ***** USAGE FAULT *****
E:   Illegal use of the EPSR
E: r0/a1:  0x6000aa44  r1/a2:  0x800087e4  r2/a3:  0x800087d4
E: r3/a4:  0x00000040 r12/ip:  0x00000000 r14/lr:  0x60008b73
E:  xpsr:  0x60000000
E: Faulting instruction address (r15/pc): 0x00000040
E: >>> ZEPHYR FATAL ERROR 0: CPU exception on CPU 0
E: Current thread: 0x800000f8 (unknown)
E: Halting system

**Comment by kunoh** [comment]
Thank you @danieldegrasse, it works perfectly!

**Comment by dleach02** [comment]
@kunoh, can you review #45183
