### ISSUE TITLE
NET_TCP_BACKLOG_SIZE is unused, it has to be either implemented or deleted

### ISSUE THREAD

**Issue by AndreyDodonov-EH** [zephyrproject-rtos/zephyr#45324]
### Discussed in https://github.com/zephyrproject-rtos/zephyr/discussions/44973

<div type='discussions-op-text'>

<sup>Originally posted by **AndreyDodonov-EH** April 20, 2022</sup>
According to the quick grep, it's not used anymore, but still present in KConfig:
https://github.com/zephyrproject-rtos/zephyr/blob/main/subsys/net/ip/Kconfig#L366

Is it not needed anymore or am I missing something?</div>

**Comment by mbolivar-nordic** [comment]
@AndreyDodonov-EH could you please send a PR removing the unused option as suggested by @jukkar ?

**Comment by AndreyDodonov-EH** [comment]
@mbolivar-nordic Yeah, will do!
But we need to keep this (or similar) issue open to make sure that we know that there is implementation missing.

**Comment by AndreyDodonov-EH** [comment]
@mbolivar-nordic Here you go: https://github.com/zephyrproject-rtos/zephyr/pull/45614

**Comment by mbolivar-nordic** [comment]
> But we need to keep this (or similar) issue open to make sure that we know that there is implementation missing.

OK, please open a new issue and mark it as an "enhancement" describing the missing implementation

**Comment by AndreyDodonov-EH** [comment]
@mbolivar-nordic 
I think I was incorrect, I spent some time trying to understand the current implementation, and now I think that this functionality is not missing, because we can have multiple contexts (i.e. sockets) independent of each other, so the number of simultaneous connection attempts can be arbitrary.

@rlubos  Can you confirm that this is indeed so and it's not necessary to open a new issue?

As reference:
https://docs.zephyrproject.org/3.0.0/reference/kconfig/CONFIG_NET_TCP_BACKLOG_SIZE.html

**Comment by rlubos** [comment]
> @mbolivar-nordic I think I was incorrect, I spent some time trying to understand the current implementation, and now I think that this functionality is not missing, because we can have multiple contexts (i.e. sockets) independent of each other, so the number of simultaneous connection attempts can be arbitrary.
> 
> @rlubos Can you confirm that this is indeed so and it's not necessary to open a new issue?
> 
> As reference: https://docs.zephyrproject.org/3.0.0/reference/kconfig/CONFIG_NET_TCP_BACKLOG_SIZE.html

I think you're right, we allocate a new TCP context for each initiated connection so that config is no longer applicable.
