### ISSUE TITLE
tests: drivers: pwm_api fails with stm32 devices

### ISSUE THREAD

**Issue by FRASTM** [zephyrproject-rtos/zephyr#45322]
**Describe the bug**
the tests/drivers/pwm/pwm_api/ fails in the test_pwm_usec  sequence when running on stm32 target boards

`Assertion failed at WEST_TOPDIR/zephyr/tests/drivers/pwm/pwm_api/src/test_pwm.c:137: test_pwm_usec: test_task(DEFAULT_PWM_PORT, DEFAULT_PERIOD_USEC, DEFAULT_PULSE_USEC, UNIT_USECS) == TC_PASS is false`

Please also mention any information which could help others to understand
the problem you're facing:
 - platforms:  nucleo_h743zi, nucleo_f103rb, nucleo_f429zi, nucleo_f746zg, nucleo_h743zi, nucleo_l073rz, nucleo_wb55rg, stm32f3_disco

 
 
**To Reproduce**
1. `west build -p auto -b nucleo_wb55rg tests/drivers/pwm/pwm_api/`
2.  `west flash`

**Expected behavior**
test PASSED

**Impact**
test campaign failure

**Logs and console output**
```
Running test suite pwm_basic_test
===================================================================
START - test_pwm_usec
[PWM]: 1, [period]: 2000, [pulse]: 1000
Fail to set the period and pulse width

    Assertion failed at WEST_TOPDIR/zephyr/tests/drivers/pwm/pwm_api/src/test_pe

 FAIL - test_pwm_usec in 0.26 seconds
===================================================================
START - test_pwm_nsec
[PWM]: 1, [period]: 2000000, [pulse]: 1000000
[PWM]: 1, [period]: 2000000, [pulse]: 2000000
[PWM]: 1, [period]: 2000000, [pulse]: 0
 PASS - test_pwm_nsec in 3.13 seconds
===================================================================
START - test_pwm_cycle
[PWM]: 1, [period]: 64000, [pulse]: 32000
[PWM]: 1, [period]: 64000, [pulse]: 64000
[PWM]: 1, [period]: 64000, [pulse]: 0
 PASS - test_pwm_cycle in 2.12 seconds
===================================================================
Test suite pwm_basic_test failed.                                               
===================================================================             
PROJECT EXECUTION FAILED  
```                                                      

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain Zephyr SDK sdk-0.14.0
 - Commit SHA : 005968a81fb61217efb667ca79fb844fce872b07

**Additional context**
Seems related to the PR https://github.com/zephyrproject-rtos/zephyr/pull/44583

**Comment by erwango** [comment]
Same as https://github.com/zephyrproject-rtos/zephyr/issues/45372 (fixed by https://github.com/zephyrproject-rtos/zephyr/pull/45376).
Closing
