### ISSUE TITLE
MinGW-w64: Cannot build Zephyr project

### ISSUE THREAD

**Issue by lescopc** [zephyrproject-rtos/zephyr#45390]
**Describe the bug**
It is not possible to build & run Zephyr on MinGW-w64 because of PATH Unix/Windows difference

Because of [MSYS2 PATH auto-conversion](https://www.msys2.org/docs/filesystem-paths/), sometimes we get the wrong value going in-and-out CMake (to Shell or Python3).

To Reproduce
cmake -DBOARD=qemu_cortex_m3 -DZEPHYR_TOOLCHAIN_VARIANT=gnuarmemb -DGNUARMEMB_TOOLCHAIN_PATH=/c/Users/%USER%/gcc-arm-10.3-2021.07-mingw-w64-i686-arm-none-eabi %ZEPHYR_BASE%/samples/hello_world

**Expected behavior**
Get a Zephyr.elf file able to run on QEMU
Then:
> qemu-system-arm.exe -M lm3s6965evb -nographic -kernel mybuild/zephyr/zephyr.elf

console:
`Timer with period zero, disabling `
`*** Booting Zephyr OS build v3.0.0-rc3-23-gba939b126203  ***`
`Hello World! qemu_cortex_m3`

**Impact**
annoyance

**Logs and console output**
Logs do not reflect the fact that sometimes we get
> C:/my/path/on/mingw (which might be valid depending on how you use it)

instead of

> /c/my/path/on/mingw (also valid)

**Environment (please complete the following information):**
 - OS: Windows: MinGW-w64
 - Toolchain gcc-arm-10.3-2021.07-mingw-w64-i686-arm-none-eabi
 - Commit SHA: https://github.com/zephyrproject-rtos/zephyr/commit/ba939b126203f4977a50d379ee09333b4aa84a33
which cmake
/mingw64/bin/cmake
which python3
/mingw64/bin/python3

**Comment by stephanosio** [comment]
See https://github.com/zephyrproject-rtos/zephyr/issues/45383#issuecomment-1118672615

We do not support building Zephyr inside MSYS environment.
