### ISSUE TITLE
Bug when sending a BLE proxy mesh msg of length exactly 2x the MTU size

### ISSUE THREAD

**Issue by aralex1** [zephyrproject-rtos/zephyr#45394]
Hi all, I am sorry if this is not the correct format for reporting something. I am new to open source code, so beforehand, I apologize if this is not the correct procedure. 

I am currently using the [bt_mesh_proxy_msg_send ](https://github.com/zephyrproject-rtos/zephyr/blob/d8b45e38c130b6c83fc8eba6f9e031c78cb2b276/subsys/bluetooth/mesh/proxy_msg.c#L140) function call in my implementation and I noticed that if the message is exactly double or triple of the MTU size minus the msg size/MTU, the while loop in this function will never send the SAR_LAST message. 

Let's consider this scenario that it is how I noticed this. If the MTU is equal to 250 and the msg length is equal to 498, the function will add the type to the original msg increasing the msg length to 499, and then, it will send 250 bytes. Now, we have the rest of the msg whose length is now 249. Then, once we enter into the while loop, it checks if we can send the complete msg only if the msg length +1 (249 + 1) is less than 250. Since it is not less than the MTU, we add the type to the message which increases the message length to 250 and we send a SAR_CONT msg. This leaves us with a msg of size 0 and we leave the loop without ever sending the SAR_LAST msg.

Shouldn't the while loop either check if the msg length + 1 is less or equal than the MTU size or use the same check on line 150 for consistency? [here](https://github.com/zephyrproject-rtos/zephyr/blob/d8b45e38c130b6c83fc8eba6f9e031c78cb2b276/subsys/bluetooth/mesh/proxy_msg.c#L167)  in either case, we will send the SAR_LAST msg when the msg is exactly the MTU size.

**Comment by mbolivar-nordic** [comment]
@PavelVPV could you please take a look and decide if it's a bug or not?

**Comment by PavelVPV** [comment]
Hi @aralex1 , yes, you are right, this is a bug. I'll fix this.

**Comment by aralex1** [comment]
Hi @PavelVPV, thanks for checking this bug.

**Comment by cvinayak** [comment]
@PavelVPV Adding the `Fixes #45394` in the PR description would link it with this issue, adding as a comment does not.
