### ISSUE TITLE
Bluetooth: Controller: Periodic advertising scheduling is broken, TIFS/TMAFS maintenance corrupted

### ISSUE THREAD

**Issue by ppryga** [zephyrproject-rtos/zephyr#45404]
**Describe the bug**
TIFS/TMAFS is not maintained correctly when use of PHY CODED and periodic advertising with chained PDUs.
The problem may be observed with use of a BLE sniffer.

**To Reproduce**
Prepare a sample application that uses CODE PHY and a chain of PDUs for periodic advertising.

**Expected behavior**
TIFS/TMAFS is maintained correctly.

**Impact**
Medium. The issue was found during conformance tests preparation. It looks like it is not very common case.

**Comment by cvinayak** [comment]
Fixed by https://github.com/zephyrproject-rtos/zephyr/pull/43385 or https://github.com/zephyrproject-rtos/zephyr/pull/43480
