### ISSUE TITLE
tests/crypto/mbedtls/testcase.yaml#test :Build failed

### ISSUE THREAD

**Issue by rrahulkx** [zephyrproject-rtos/zephyr#4549]
We are getting build  failure Issue while running this testcase.

The failure report is pasted below :---
tests/crypto/mbedtls/testcase.yaml#test @ esp32

Toolchain: ZEPHYR_GCC_VARIANT=espressif

Commit ID                                Branch          URL
---------------------------------------- --------------- -------------------
3f508e911eb1d43171eb11bdb7a44e7140454bb0 master          https://github.com/zephyrproject-rtos/zephyr.git

**Detailed description**
====================
Automated test run failed.

Output (the target might have produced none; GDB will be needed at this point):
configure passed
build passed: 'mkdir -p outdir-dwm5-ixus-esp32; rm -f outdir-dwm5-ixus-esp32/.config'
build passed: 'make -j -C 
ZEPHYR_GCC_VARIANT/espressif/zephyr.git/tests/crypto/mbedtls/ 
EXTRA_CFLAGS="-Werror -Wno-error=deprecated-declarations" 
KCPPFLAGS=-DTC_RUNID=ci-171024-1324-426:ixus BOARD=esp32 ARCH=xtensa  outdir-dwm5-ixus-esp32 initconfig'

build output: Using espressif/zephyr.git/boards/xtensa/esp32/esp32_defconfig as base
build output: Merging espressif/zephyr.git/tests/include/test.config
build output: Merging prj.conf
build output: Merging outdir-dwm5-ixus-esp32/boot_config.conf
build output: # configuration written to .config
build failed: 'make -j -C /tests/crypto/mbedtls EXTRA_CFLAGS="-Werror -Wno-error=deprecated-declarations" KCPPFLAGS=-DTC_RUNID=ci-171024-1324-426:ixus BOARD=esp32 ARCH=xtensa  O=outdir-dwm5-ixus-esp32'

build output: drivers/built-in.o: In function `esp32_uart_init':
build output: drivers/serial/uart_esp32.c:46:(.text.esp32_uart_init+0x3): dangerous relocation: call8: call target out of range: esp32_rom_uart_attach
build output: drivers/built-in.o: In function `esp32_uart_tx':
build output: drivers/serial/uart_esp32.c:19:(.text.esp32_uart_tx+0x9): dangerous relocation: call8: call target out of range: esp32_rom_uart_tx_one_char
build output: collect2: error: ld returned 1 exit status
build output: zephyr.git/Makefile:876: recipe for target 'zephyr_prebuilt.elf' failed
build output: make[3]: *** [zephyr_prebuilt.elf] Error 1
build output: Makefile:178: recipe for target 'sub-make' failed
build output: make[2]: *** [sub-make] Error 2
build output: Makefile.inc:82: recipe for target 'all' failed
build output: make[1]: *** [all] Error 2

build failed trace: 'make -j -C tests/crypto/mbedtls
 EXTRA_CFLAGS="-Werror -Wno-error=deprecated-declarations" 
KCPPFLAGS=-DTC_RUNID=ci-171024-1324-426:ixus BOARD=esp32 
ARCH=xtensa  O=outdir-dwm5-ixus-esp32\'
build failed
         @local              COMPLETION failed

**Comment by nashif** [comment]
not enough details
