### ISSUE TITLE
GdbStub get_mem_region bug

### ISSUE THREAD

**Issue by mrkhldn** [zephyrproject-rtos/zephyr#45529]
**Describe the bug**
When analyzing a core dump, the get_mem_region function in gdbstub.py currently will return a given memory region if the desired address is equal to the "end" of the memory region. A valid memory region should only be returned if the given address is less than the "end". Otherwise we won't be able to read the value at "addr". Additionally, a different memory region may have that "addr" as its "start" and would be a more appropriate selection.

Please also mention any information which could help others to understand
the problem you're facing:
 - What target platform are you using?
 I was using RISC-V, but the issue would reproduce on any platform where coredump is supported
 - What have you tried to diagnose or workaround this issue?
 I am still able to directly examine a single memory address in gdb, but some commands that would require reading memory from two memory regions return inaccurate data.
 - ...

**To Reproduce**
1. Add multiple memory regions to a core dump using a coredump device (or some other means) where the second region has a start address equal to the first region's end address
2. Write some unique expected values into the memory regions
3. Force a crash
4. Load the dump into gdb
5. Attempt to read from the start of the second memory region

**Expected behavior**
GDB prints actual data captured at that memory

**Impact**
Annoyance, as examining memory in a crash dump sometimes reports inaccurate data

**Logs and console output**

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: Zephyr SDK

**Additional context**
@cfriedt , here's an issue for the backport

**Comment by cfriedt** [comment]
Fixed by https://github.com/zephyrproject-rtos/zephyr/pull/42711
