### ISSUE TITLE
bt_gatt_write_without_response_cb doesn't use callback

### ISSUE THREAD

**Issue by PavelVPV** [zephyrproject-rtos/zephyr#45549]
**Describe the bug**
Seems like in this PR https://github.com/zephyrproject-rtos/zephyr/pull/44269 `bt_gatt_write_without_response_cb` was refactored so that it doesn't use `func` callback anymore. This brakes some mesh functionality which relies on the callback.

**Comment by hermabe** [comment]
Looks like an oversight on my part. Does adding this line fix the issue?
```
bt_att_set_tx_meta_data(buf, func, user_data);
```

Commit with potential fix: https://github.com/hermabe/zephyr/commit/01ca4e387b1fbbf9a1707c691792dc965c85e018

**Comment by PavelVPV** [comment]
Yes, it works, checked on latest main. Thanks!
