### ISSUE TITLE
cmake: gcc --print-multi-directory doesn't print full path and checks fails

### ISSUE THREAD

**Issue by luca-fancellu** [zephyrproject-rtos/zephyr#45578]
**Describe the bug**

When building Zephyr through environment like yocto using cross-compiling gcc (not zephyr toolchain), the configuration stops
because of a check in a cmake file that expects a full path to a library file but instead just the name of the file is found in the variable.
Here the problem in zephyr/cmake/modules/extensions.cmake:2068:
```
  No such file or directory: LIBGCC_FILE_NAME: 'libgcc.a'
Call Stack (most recent call first):
  /path/to/yocto/tmp/work/armv8a-poky-linux/xtp/0+git1-r0/zephyr/cmake/compiler/gcc/target.cmake:73 (assert_exists)
  /path/to/yocto/tmp/work/armv8a-poky-linux/xtp/0+git1-r0/zephyr/cmake/modules/target_toolchain.cmake:63 (include)
  /path/to/yocto/tmp/work/armv8a-poky-linux/xtp/0+git1-r0/zephyr/cmake/modules/zephyr_default.cmake:121 (include)
  /path/to/yocto/tmp/work/armv8a-poky-linux/xtp/0+git1-r0/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:45 (include)
  /path/to/yocto/tmp/work/armv8a-poky-linux/xtp/0+git1-r0/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:75 (include_boilerplate)
  CMakeLists.txt:3 (find_package)
```

The problem is in these lines:
```
# This libgcc code is partially duplicated in compiler/*/target.cmake
execute_process(
  COMMAND ${CMAKE_C_COMPILER} ${TOOLCHAIN_C_FLAGS} --print-libgcc-file-name
  OUTPUT_VARIABLE LIBGCC_FILE_NAME
  OUTPUT_STRIP_TRAILING_WHITESPACE
  )

assert_exists(LIBGCC_FILE_NAME)
```
Because --print-libgcc-file-name should print the full path to the library file but instead it prints just the name, the problem can be easily solved by passing the correct --sysroot to the compiler through TOOLCHAIN_C_FLAGS.

I have a patch ready for that, that checks if SYSROOT_DIR is set and it appends --sysroot=<path> to the flags passed to the compiler.

**To Reproduce**
`cmake -S < application > -B < build_dir > -DBOARD=< board > -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile -DCROSS_COMPILE=/path/to/yocto/tmp/work/armv8a-poky-linux/recipe/0+git1-r0/recipe-sysroot-native/usr/bin/aarch64-poky-linux/aarch64-poky-linux- -DZEPHYR_BASE=/path/to/yocto/tmp/work/armv8a-poky-linux/recipe/0+git1-r0/zephyr`

**Expected behavior**

The desired behaviour is the complete build of Zephyr

**Impact**

It prevents the build.

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04
 - Toolchain aarch64-poky-linux
 - Commit SHA or Version used: 176240c3c2319060f2103a34c9b71e9d9a8bb8dd

**Comment by carlescufi** [comment]
>I have a patch ready for that, that checks if SYSROOT_DIR is set and it appends --sysroot= to the flags passed to the compiler.

@luca-fancellu can you please open a Pull Request with this patch?
