### ISSUE TITLE
samples: usb: mass: Sample.usb.mass_flash_fatfs fails on non-secure nrf5340dk

### ISSUE THREAD

**Issue by PerMac** [zephyrproject-rtos/zephyr#45581]
**Describe the bug**
A test scenario sample.usb.mass_flash_fatfs https://github.com/zephyrproject-rtos/zephyr/blob/main/samples/subsys/usb/mass/sample.yaml#L29 fails on nrf5340dk_nrf5340_cpuapp_ns. The test expects 
`The device is put in USB mass storage mode.` in the output. However, the only output produced is:
```
DEBUG   - DEVICE: *** Booting Zephyr OS build zephyr-v3.0.0-3725-g806ee8601ca7  ***
DEBUG   - DEVICE: Area 6 at 0xfa000 on NRF_FLASH_DRV_NAME for 24576 bytes
```
and the test timeout

The test passes on not "non-secure" version, i.e. nrf5340dk_nrf5340_cpuapp. 

**To Reproduce**
1. have nrf5340dk connected
2. run `scripts/twister -v -v --device-testing --device-serial /dev/ttyACM2 --west-flash="--erase" -p nrf5340dk_nrf5340_cpuapp_ns -s samples/subsys/usb/mass/sample.usb.mass_flash_fatfs`
3. See error

**Expected behavior**
Test passes

**Impact**
Not clear

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04
 - Toolchain zephyr-sdk
 - Commit SHA or Version used: zephyr-v3.0.0-3725-g806ee8601c

**Comment by jfischer-no** [comment]
@PerMac actually it is mass_flash_littlefs timeouts not mass_flash_fatfs, see first commit in #47031. The reason is that there is no devicetree overlay for nrf5340dk_nrf5340_cpuapp_ns, the fix is either to add integration platform or overlay.
