### ISSUE TITLE
Typo in definition of lsm6ds0.h

### ISSUE THREAD

**Issue by 2Eagle2** [zephyrproject-rtos/zephyr#45583]
threre is typo in definition 
zephyr/drivers/sensor/lsm6ds0/lsm6ds0.h:362

there is 
#define LSM6DS0_DEFALUT_ACCEL_FULLSCALE
and should be:
#define LSM6DS0_DEFAULT_ACCEL_FULLSCALE

because of that there is no way how to build CONFIG_LSM6DS0_ACCEL_FULLSCALE = 16

**Comment by erwango** [comment]
@2Eagle2 Thanks for raising this. Would you be able to push a PR to fix this directly ?
