### ISSUE TITLE
ipc_service: Align return codes for available backends.

### ISSUE THREAD

**Issue by emob-nordic** [zephyrproject-rtos/zephyr#45630]
**Is your enhancement proposal related to a problem? Please describe.**
Available IPC service backends does not align the return code in `ipc_service_send` when there is no space in shared buffer.
- `ipc_rpmsg_static_vrings` returns `RPMSG_ERR_NO_BUFF == -2002`
- `ipc_icmsg` return `-ENOMEM == -12`
this is inconvenient for the users that may wish to swap backends. The user is forced to change error handling implementation.

I think no buffer error is that common that it could be introduced.

**Describe the solution you'd like**
Unify return code when buffer is not available. Add `-ENOMEM` to IPC service API:
https://github.com/zephyrproject-rtos/zephyr/blob/main/include/zephyr/ipc/ipc_service.h#L236

**Describe alternatives you've considered**
I'm creating this issue to get one.

**Additional context**
I'm open for a discussion if any of assignees see additional stuff that should be fixed.

**Comment by carlocaione** [comment]
Uhm, I would have preferred to return `-ENOBUFS` instead of `-ENOMEM` but I guess it's too late for that. Let me push a PR.
