### ISSUE TITLE
Lorawan: Devnonce has already been used

### ISSUE THREAD

**Issue by Andermutu** [zephyrproject-rtos/zephyr#45678]
**Describe the bug**

We are trying to move from NRF connect SDK 1.6.0 (zephyr v2.6.0-rc1-ncs1) to 1.7.1 (zephyr v2.6.99-ncs1-1). If we try the lorawan sample located under "/subsys/lorawan/class_a" with NRF connect SDK 1.6.0, everything works as expected:

<img width="1158" alt="Captura de pantalla 2022-05-16 a las 12 34 55" src="https://user-images.githubusercontent.com/30649760/168578744-31f97314-ec9c-47cf-b093-a8f0e03d37dd.png">
<img width="1158" alt="Captura de pantalla 2022-05-16 a las 12 44 52" src="https://user-images.githubusercontent.com/30649760/168578782-fd6789a1-5216-425d-b24d-95594d6f11d6.png">
<img width="1158" alt="Captura de pantalla 2022-05-16 a las 12 42 37" src="https://user-images.githubusercontent.com/30649760/168578795-cb1277eb-72a2-411c-aff1-9920ebd15143.png">

 If we try the same exact lorawan sample located under "/subsys/lorawan/class_a" with NRF connect SDK 1.7.1, we get "DevNonce" error on the TTN console:

<img width="1158" alt="Captura de pantalla 2022-05-16 a las 12 49 29" src="https://user-images.githubusercontent.com/30649760/168579094-f12a1bfd-d006-4389-b724-7ea20a4b876a.png">
<img width="1158" alt="Captura de pantalla 2022-05-16 a las 12 48 12" src="https://user-images.githubusercontent.com/30649760/168579114-927687be-5e77-4340-a1ba-a2e6ba0f52b0.png">
<img width="1158" alt="Captura de pantalla 2022-05-16 a las 12 48 35" src="https://user-images.githubusercontent.com/30649760/168580503-a87d27d5-fd1f-4b5e-91dc-d0d9beafce01.png">

**Please also mention any information which could help others to understand the problem you're facing**

 - Hardware: Actinius Icarus v1.4 (nrf9160)
 - When we use NRF connect SDK 1.7.1, the "class_a" sample only works when a NEW device is registered on TTN, and this sample works until we make a reboot to the device and it tries to reconnect to the TTN network. After that, it stops working and the "Devnonce" error appears.

**To Reproduce**

1. build lorawan class_a project with NRF connect SDK 1.6.0 (zephyr v2.6.0-rc1-ncs1)
2. try the sample on the target device, it works.
3. build lorawan class_a project with NRF connect SDK 1.7.1 (zephyr v2.6.99-ncs1-1)
4. try the sample on the target device, "DevNonce" error on TTN console.

**Impact**

We have problems updating to NRF connect SDK 1.7.1

**Environment (please complete the following information):**

 - OS: MacOS
 - Toolchain: NRF connect SDK 1.6.0 (zephyr v2.6.0-rc1-ncs1) and 1.7.1 (zephyr v2.6.99-ncs1-1)

**Comment by fabiobaltieri** [comment]
@Andermutu do you have the device LoRaWAN version configured correctly on the TTN console? I think that the current stack should use "LoRaWAN Specification 1.0.4", I have few devices set up with that with no explicit devnonce handling and they work fine. You may also want to look into either storing and setting a devnonce from the application either using https://github.com/zephyrproject-rtos/zephyr/blob/main/include/zephyr/lorawan/lorawan.h#L94

or the NVM module 
https://github.com/zephyrproject-rtos/zephyr/blob/main/subsys/lorawan/nvm/lorawan_nvm_settings.c

(though they may not be available in the current nRF Connect SDK Zephyr version).

**Comment by Andermutu** [comment]
@fabiobaltieri @Mani-Sadhasivam, you are right, the problem is that the `class_a` sample must provide a unique `dev_nonce` to work with "LoRaWAN Specification 1.0.4". I have first tried not to use explicit devnonce handling. On TTN, my device was configured as 1.0.3. After changing to 1.0.4 I was getting "devnonce is too small" error. The solution was to provide a unique devnonce, that should be stored on the nvs.

The [9cc32af](https://github.com/zephyrproject-rtos/zephyr/commit/9cc32af99e7986e32e1fe82f3c8e5d30e1fc3997) changes worked well to provide that unique devnonce, after modifying `lorawan.h` and `lorawan.c` files.

**Comment by ballardr** [comment]
I've had this same issue. I've added the below function which I call just before lorawan_join(). It's a bit hacky, but it works. For me it just means I don't need to muck round too much with the upstream libraries.

```
#include <random/rand32.h>
#include <LoRaMac.h>
int lorawan_setRandomDevNonce () {

	MibRequestConfirm_t mibReq;
	mibReq.Type = MIB_NVM_CTXS;
	LoRaMacMibGetRequestConfirm( &mibReq );
	union {
		uint16_t u16[2];
		uint32_t u32;
		uint8_t u8[4];
	} num;

	int ret = sys_csrand_get(num.u8,2);
	if (ret < 0) {
		num.u32 = sys_rand32_get();
	}
    LoRaMacNvmData_t* MacContexts = mibReq.Param.Contexts;

    MacContexts->Crypto.DevNonce = num.u16[0];

	return 0;
}
```

Note, to get #include <LoRaMac.h> to work in my application code, I had to add the below to cmake so to include the loramac-node directories as search paths for headers.
zephyr_library_include_directories($ENV{ZEPHYR_BASE}/../modules/lib/loramac-node/src/mac)
zephyr_library_include_directories($ENV{ZEPHYR_BASE}/../modules/lib/loramac-node/src/mac/region)
zephyr_library_include_directories($ENV{ZEPHYR_BASE}/../modules/lib/loramac-node/src/boards)
zephyr_library_include_directories($ENV{ZEPHYR_BASE}/../modules/lib/loramac-node/src/system)
zephyr_library_include_directories($ENV{ZEPHYR_BASE}/../modules/lib/loramac-node/src/radio)

**Comment by Andermutu** [comment]
@ballardr Thank you for sharing your solution! I have been questioning whether using a random devnonce is a good solution in terms of reliability, and finally decided to make a counter that saves on flash memory. For people like me who have limited knowledge of how zephyr builds/versions work, it's tricky to figure out the problem without asking for help.

**Comment by ballardr** [comment]
So LoRaWAN Specifications 1.0.3 (and similar for older versions) on line 974 specifically says "DevNonce is a random value".

However specifications 1.0.4 and 1.1 both say "DevNonce is a counter starting at 0 when the device is initially powered up and incremented with every Join-request. A DevNonce value SHALL NEVER be reused for a given JoinEUI value."

So a random devnonce is a good solution depending what version of LoRaWAN your targeting. In reality, it more so depends how strict the network server is (Chirpstack, TTN etc) as I don't think for instance that chirpstack actually cares if its random or incremented.

**Comment by Mani-Sadhasivam** [comment]
Closing this issue since we already have a solution in mainline. Please reopen if you face any further issue, thanks!

**Comment by DivyaaMohann** [comment]
Hi, 
I am facing the same issue in LoRaWAN specification 1.0.4, DevNonce is too small. How do I manually rectify this in the code any source of reference would greatly help. I would also like to know the dependencies that the Zephyr prj.conf file requires to run the LoRaWAN sample in Zephyr.
Thank you.
