### ISSUE TITLE
dts generation incorrect

### ISSUE THREAD

**Issue by galak** [zephyrproject-rtos/zephyr#4568]
We end up generating something like:

/* i2c@40066000 */
#define NXP_KINETIS_I2C_40066000_BASE_ADDRESS_0         0x40066000
#define NXP_KINETIS_I2C_40066000_BASE_ADDRESS_1         0x1000

This is wrong, this is probably due to miss handling of addr/size cells in the i2c bus controller node.

This should be:

/* i2c@40066000 */
#define NXP_KINETIS_I2C_40066000_BASE_ADDRESS_0         0x40066000
#define NXP_KINETIS_I2C_40066000_SIZE_0         0x1000

**Comment by erwango** [comment]
@galak , @agross-linaro: 
We are adding "#size-cells = <0>;", for I2C on both NXP and ST for I2C
This is not done for UART and UART generates the correct define (_SIZE_0) (inheriting from armv6/7.dtsi #size-cells = <1>;)

Should we have same size-cells for both UART and I2C? 
If yes, then one of these above is wrong. And then either dts either script should be updated.
(If not I don't really see why).

Anyway, if you can confirm the exact configuration, I'll have a deeper look to the 'reg' generation algo.

**Comment by nashif** [comment]
is this still an issue?

**Comment by galak** [comment]
Yes, looking at it now
