### ISSUE TITLE
twister: map generation fails

### ISSUE THREAD

**Issue by erwango** [zephyrproject-rtos/zephyr#45713]
**Describe the bug**
Twister map generation fails after merging of #44094:
```
twister --generate-hardware-map ../map.yaml -c --persistent-hardware-map 

Deleting output directory /local/mcu/zephyrproject/zephyr/twister-out
INFO    - Scanning connected hardware...
WARNING - Unsupported device (None): /dev/ttyS4 - n/a
Traceback (most recent call last):
  File "/local/mcu/zephyrproject/zephyr/scripts/twister", line 1370, in <module>
    main()
  File "/local/mcu/zephyrproject/zephyr/scripts/twister", line 879, in main
    hwm.save(options.generate_hardware_map)
  File "/local/mcu/zephyrproject/zephyr/scripts/pylib/twister/twisterlib.py", line 4642, in save
    hwm.sort(key=lambda x: x.get('serial', ''))
TypeError: '<' not supported between instances of 'NoneType' and 'NoneType'

```

Please also mention any information which could help others to understand
the problem you're facing:
 - Test on bbb8c91afa6e54d24999298a0843303eb23eb2d6 (just before #44094) is working fine

**To Reproduce**
1. Use SHA1 a195f9826531d43244330634376f785a9f8acf2a
2. Launch `twister --generate-hardware-map ../map.yaml -c --persistent-hardware-map `
3. See error

**Expected behavior**
Map generation works 

**Impact**
Impact on test bench when adding/removing boards

**Logs and console output**
If applicable, add console logs or other types of debug information
e.g Wireshark capture or Logic analyzer capture (upload in zip archive).
copy-and-paste text and put a code fence (\`\`\`) before and after, to help
explain the issue. (if unable to obtain text log, add a screenshot)

**Environment (please complete the following information):**
 - OS: Linux (Ubuntu 20.04)
 - Toolchain (e.g Zephyr SDK, ...): sdk-0.14.0
 - Commit SHA or Version used: a195f9826531d43244330634376f785a9f8acf2a

**Comment by henrikbrixandersen** [comment]
I can confirm the issue locally.
