### ISSUE TITLE
drivers: gpio: pca9555: Driver is writting to output port despite all pins been configured as input

### ISSUE THREAD

**Issue by albertofloyd** [zephyrproject-rtos/zephyr#45774]
**Describe the bug**
Extra time for board initialization due unnecessary setup for each IO expander.

**To Reproduce**
1. mkdir build; cd build
2. cmake -DBOARD=board\_xyz
3. make

**Expected behavior**
Output port should not be written to if not required

**Impact**
It takes more time to complete initialization

**Logs and console output**
![image](https://user-images.githubusercontent.com/16172078/169087530-56413328-2e1f-4945-88b1-d2588a392825.png)

**Comment by danieldegrasse** [comment]
@albertofloyd based off the description here I've updated the pca95xx driver to no longer unconditionally write to the output configuration register, and only do so if the pin is configured as an output. However, I do not have hardware to verify this change with. Could you test the linked PR #46028, and verify that you no longer see the unnecessary register write?
