### ISSUE TITLE
Unable to use thread aware debugging with STM32H743ZI

### ISSUE THREAD

**Issue by bdesterBE** [zephyrproject-rtos/zephyr#45778]
**Describe the bug**
When attempting to use the `CONFIG_DEBUG_THREAD_INFO` configuration option for thread aware debugging with the STM32H743ZI develpment board, after running `west debug` an output containing 'cant read "_TARGETNAME": no such variable', followed by "You can't do that when you target is `exec'" is received.

If the configuration option is not added to the project's prj.conf file, I am able to use `west debug` without issue.

I have attempted to add `$_TARGETNAME configure -rtos Zephyr` to zephyr/boards/arm/nucleo_h743zi/support/openocd.cfg per https://github.com/zephyrproject-rtos/zephyr/issues/37205, to no avail.

**To Reproduce**
The behavior can be seen on the blinky example.
1. add CONFIG_DEBUG_THREAD_INFO to zephyr/samples/basic/blinky/prj.conf
2. west build -p -b nucleo_h743zi zephyr/samples/basic/blinky
3. west debug

**Expected behavior**
The ability to run openocd debugging with thread awareness using `west debug` on the STM32H743ZI development board.

**Impact**
Currently have no other way of debugging with thread awareness in our system, making it difficult to see which thread could be causing various issue including watchdog timer triggers.

**Logs and console output**
![Screenshot from 2022-04-28 15-57-55](https://user-images.githubusercontent.com/91616875/169156441-14340487-0912-406e-99c2-e79096c1db4f.png)

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04
 - Zephyr SDK 13.
 - Commit SHA: 140837ce3ac6ba6ac01d804ebd40c8aaf00a3011
 - Latest version: v3.0.0-rc1

EDIT (@erwango):
Fixed the Kconfig option name

**Comment by erwango** [comment]
Correct flag name is `CONFIG_DEBUG_THREAD_INFO`

**Comment by erwango** [comment]
Ok, here is the problem:

https://github.com/zephyrproject-rtos/zephyr/pull/37516 implemented integrated west runner support for openocd thread info configuration. For that it relied on the command `$_TARGETNAME configure -rtos Zephyr` which unfortunately is not generic enough to work with all openocd targets.
For instance, on stm32h743, it should use `$_CHIPNAME.cpu0 configure -rtos Zephyr`, which is getting the whole feature to work as expected.

We miss a way to overload this default generic command, either fully, either only overwriting the target handle (`_TARGETNAME` replaced by `_CHIPNAME.cpu0`). Note that this i required for all STM32H7 target, but likely other targets subject to multicore (for instance lpc4370 > `$_CHIPNAME.m4 `).

**Comment by erwango** [comment]
Proposal to fix this is to add an openocd runner arg which would overwrite the default openocd script target handle `_TARGETNAME`. For instance:
`board_runner_args(openocd --target-script-handle "_CHIPNAME.cpu0")`

@mbolivar-nordic Would it be fine with you ?

**Comment by mbolivar-nordic** [comment]
> @mbolivar-nordic Would it be fine with you ?

Yes
