### ISSUE TITLE
Implementing ARCH_EXCEPT on Xtensa unmasks nested interrupt handling bug

### ISSUE THREAD

**Issue by laurenmurphyx64** [zephyrproject-rtos/zephyr#45779]
**Describe the bug**
https://github.com/zephyrproject-rtos/zephyr/pull/45570 introduces an implementation of ARCH_EXCEPT so that k_panic and other calls to z_except_reason create exception stack frames. Now that we trigger a hardware exception on Xtensa for software exceptions, @andyross and I found out that when `xtensa_excint1_c` finishes handling an exception (e.g. stack check failure) inside of an interrupt (e.g. scheduler, timer, etc.), it can incorrectly reschedule a new thread without letting the old thread finish handling the outer interrupt. 

In the case of the failed test `tests/kernel/fatal/exception`, the fact that we never finish handling the interrupt after we're done handling the exception means we don't properly decrement `nested` to 0 before resuming execution (assuming that the user implemented a `k_sys_fatal_error` handler that returns). I.e. nested goes to 1 into the interrupt, goes to 2 for the exception, goes back 1 coming out of the exception and stays at 1 as execution resume. This causes Zephyr to think it's in an ISR for every ASSERT on `nested`, preventing us from starting new threads among many other things.

Note: @andyross Unless it's urgently needed for 3.1, I think it would be best to add the ARCH_EXCEPT implementation and fix this bug in one PR, so if you're OK with it, could you put the fix as the top commit on the PR? https://github.com/zephyrproject-rtos/zephyr/pull/45570 . If you think it's better to introduce just the fix and ARCH_EXCEPT in another PR so the fix can make the 3.1 merge window, that's fine too.

**To Reproduce**

1. gh pr checkout 45570
2. west build -t run tests/kernel/fatal/exception

**Expected behavior**

Resume handling interrupt after finished handling nested interrupt and properly increment / decrement `nested`. Modify exception testing in `tests/kernel/fatal/exception` if necessary.

**More details e.g. logs and console output**

- https://github.com/zephyrproject-rtos/zephyr/pull/45570
- https://github.com/zephyrproject-rtos/zephyr/pull/45570#discussion_r872843870
- https://gist.github.com/laurenmurphyx64/a77b83930b028cc4512080eadf936e61

**Impact**
Showstopper for coredump. I'm not sure what the priority is for Zephyr as a whole. I guess it depends on what the priority of implementing ARCH_EXCEPT for Zephyr is, since this bug hasn't caused problems before. @andyross may have thoughts.

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: Zephyr SDK
 - SHA: https://github.com/zephyrproject-rtos/zephyr/pull/45570

**Comment by andyross** [comment]
We definitely need to get this in for 3.1, nested interrupts are broken on xtensa (though in a way that's hard to exercise for typical code; you need a nested interrupt that forces a context switch, which is a multi-mode failure for a real time app -- a fatal error handler that aborts the current thread does this deterministically of course).
