### ISSUE TITLE
nominate me as zephyr contributor

### ISSUE THREAD

**Issue by yinfangw** [zephyrproject-rtos/zephyr#45784]
# Background

The [TSC Project Roles] defines the main roles for the Zephyr Project, including
Maintainer, Collaborator, and Contributor.

By default anyone that contributes code or documentation is a Contributor, but
with the lowest [GitHub Permission Level] of Read. For example, Contributors
with Read permission do not have the permission to add reviewers to a pull
request.

Use this template to nominate a GitHub user for an elevated permission level in
the Contributor role.

# Nomination

## GitHub User

Provide the following information about the GitHub user:

1. Full Name: Yinfang Wang
1. GitHub username: yinfangw
1. Organization (optional): Intel

## Supporting Documents

Add links to 3-5 GitHub pull requests, in the Zephyr project, authored or
reviewed by the GitHub user that demonstrate the user's dedication to the
Zephyr project.

https://github.com/zephyrproject-rtos/zephyr/pulls?q=is%3Apr+author%3Ayinfangw

[TSC Project Roles]: <https://docs.zephyrproject.org/latest/project/project_roles.html>
[GitHub Permission Level]: <https://docs.github.com/en/organizations/managing-access-to-your-organizations-repositories/repository-permission-levels-for-an-organization>

**Comment by stephanosio** [comment]
Added as a contributor with triage permission level.
