### ISSUE TITLE
bluetooth: host: Failed to set security right after reconnection with bonded Central

### ISSUE THREAD

**Issue by MarekPieta** [zephyrproject-rtos/zephyr#45820]
**Describe the bug**
Failed to set security right after reconnection with bonded peer. The failure is caused by inability to find SMP channel. It seems that ATT L2CAP channel tries to send security request before SMP L2CAP channel is initialized.

**To Reproduce**
The issue can be observed with `samples/bluetooth/peripheral_hids` sample. Steps to reproduce:

1. Build and program the `peripheral_hids` sample.
2. Connect with device over BLE (e.g. with Android phone) and establish security
3. Disconnect
4. Reconnect
5. Right after reconnection, the information about error is observed in the logs. The error log is observed on every reconnection.

**Expected behavior**
The SMP channel must be initialized before ATT channel tries to send the security request, so that security request from peripheral would work fine.

**Impact**
Sending SMP security request by peripheral right after reconnection with bonded peer ends with error. The SMP request is triggered by `CONFIG_BT_GATT_AUTO_SEC_REQ` which is enabled by default.

**Logs and console output**
Error log denoting problem:
```
[00:00:43.157,531] <err> bt_smp: Unable to find SMP channel
[00:00:43.157,562] <wrn> bt_gatt: Failed to set security for bonded peer (-128)
```

**Environment (please complete the following information):**
Commit hash: `2dc866fa487ba524b426adc453d028bdd7aaa4e2`
Board: `nrf52840dk_nrf52840`

**Comment by alwa-nordic** [comment]
I set this issue to **priority medium** because @MarekPieta told me it affects a lot of samples in NCS.
