### ISSUE TITLE
USB ECM/RNDIS Can't receive broadcast messages

### ISSUE THREAD

**Issue by Coi-l** [zephyrproject-rtos/zephyr#45862]
**Describe the bug**
I can't receive udp broadcast messages when using usb ecm or usb rndis.

Board: blackpill: blackpill_f411ce

**To Reproduce**
Code used:

```
   struct sockaddr server_addr;
    memset(&server_addr, 0, sizeof(server_addr));
    net_sin(&server_addr)->sin_family = AF_INET;
    net_sin(&server_addr)->sin_port = htons(DHCP_SERVER_PORT);
    net_sin(&server_addr)->sin_addr.s_addr = htonl(INADDR_ANY);

    sock = zsock_socket(server_addr.sa_family, SOCK_DGRAM, IPPROTO_UDP);

	ret = zsock_bind(sock, &server_addr, sizeof(server_addr));
	if (ret < 0) {
		LOG_ERR("Failed to bind UDP socket: %d", errno);
		ret = -errno;
	}


```

**Expected behavior**
Broadcast packets should be received

**Impact**
Can't continue with the current feature

**Logs and console output**

I get this from the usb system:
[00:00:00.475,000] <inf> usb_ecm: len 0 req_type 0x21 req 0x43 enabled 1
[00:00:00.475,000] <inf> usb_ecm: Set Interface 0 Packet Filter 0x000c not supported
[00:00:00.525,000] <inf> usb_ecm: len 0 req_type 0x21 req 0x43 enabled 1
[00:00:00.525,000] <inf> usb_ecm: Set Interface 0 Packet Filter 0x000e not supported
[00:00:00.527,000] <inf> usb_ecm: len 0 req_type 0x21 req 0x43 enabled 1

I can see the dhcp packets being sent in wireshark

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: Zephyr SDK
 - Commit SHA: Zephyr: 47850a301c419df5d01e2c5eef04ca05c48e33e1

**Additional context**
I am not sure if this is supposed to be supported and I am doing this the wrong way, missing some config option or the like. Or if the current usb system just doesn't support it.

**Comment by jfischer-no** [comment]
For CDC ECM, SetEthernetPacketFilter, filter bitmaps PACKET_TYPE_MULTICAST and PACKET_TYPE_BROADCAST are required but not implemented by CDC ECM function, what can be considered as a bug.
