### ISSUE TITLE
[CID: 178242]: Parse warnings samples/mpu/mem_domain_apis_test/src/main.c 

### ISSUE THREAD

**Issue by Shilpashree3lc** [zephyrproject-rtos/zephyr#4586]
Static code scan issues seen in File: /samples/mpu/mem_domain_apis_test/src/main.c
 Category: Parse warnings
 Function: 
 Component: Samples
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by nashif** [comment]
a sample, so mark as low

**Comment by lpereira** [comment]
Parse errors are often issues with Coverity itself. This appears to be the case here, as the code builds and runs.  I'm closing this as false positive.
