### ISSUE TITLE
ESP32: PWM parameter renaming broke compilation

### ISSUE THREAD

**Issue by Bl4d3s** [zephyrproject-rtos/zephyr#45886]
**Describe the bug**
Commit [fbf73334f3](https://github.com/zephyrproject-rtos/zephyr/commit/fbf73334f38cc7888cc59e39f82fe682be72e125) renamed parameters for the various pwm drivers to channel to unify these.
Unfortunately the esp32 driver already has some interal variable named "channel", thus breaking compilation.

- Platform: Ubuntu WSL

**To Reproduce**
1. mkdir build; cd build
2. cmake -DBOARD=esp32
3. make
4. error: 'channel' redeclared as different kind of symbol

**Expected behavior**
Compilation to succeed

**Impact**
PWM on esp32 unusable

**Environment (please complete the following information):**
 - OS: Linux (Ubuntu WSL on Windows
 - Toolchain: Zephyr SDK
 - Commit SHA: e9d3791e3f33b7b95f57de80a85c374660680a1c (main)

Will submit PR shortly.

**Comment by gmarull** [comment]
@mbolivar-nordic https://github.com/zephyrproject-rtos/zephyr/pull/45888
