### ISSUE TITLE
[coverity] Null pointer dereferences in tests/net/app/src/main.c

### ISSUE THREAD

**Issue by Shilpashree3lc** [zephyrproject-rtos/zephyr#4589]
Static code scan issues seen in File: /tests/net/app/src/main.c
 Category: Null pointer dereferences
 Function: iface_setup
 Component: Tests
 CID: 178239
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by jukkar** [comment]
This is false positive.
