### ISSUE TITLE
[CID: 178237] memory corruption in drivers/ieee802154/ieee802154_mcr20a.c

### ISSUE THREAD

**Issue by Shilpashree3lc** [zephyrproject-rtos/zephyr#4591]
Static code scan issues seen in File: /drivers/ieee802154/ieee802154_mcr20a.c
 Category: Memory - corruptions
 Function: _mcr20a_write_burst
 Component: Drivers
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by jfischer-phytec-iot** [comment]
already taken into account in the commit 114d671e24e47fe0c56f319d368ff07642d2e13c

**Comment by jfischer-phytec-iot** [comment]
I think Coverity makes a mistake here, I will leave it open until someone confirms.
