### ISSUE TITLE
tests/net/mgmt/testcase.yaml#test :failed due to un-handled exception

### ISSUE THREAD

**Issue by rrahulkx** [zephyrproject-rtos/zephyr#4596]
Testcase :--tests/net/mgmt/testcase.yaml#test @ esp32:xtensa COMPLETION failed
This testcase is failed due to unhandled exception.

The failure report are pasted below :--
**Detailed description**
====================
 configure passed

**Build procedure :--**

build passed: 'mkdir -p /outdir-ari3-asid-esp32; outdir-ari3-asid-esp32/.config'
build passed: 'make -j -C zephyr/tests/net/mgmt/ 
EXTRA_CFLAGS="-Werror -Wno-error=deprecated-declarations" 
KCPPFLAGS=-DTC_RUNID=:asid 
BOARD=esp32 ARCH=xtensa 
 O=/outdir-ari3-asid-esp32 initconfig'

build output: Using zephyr/boards/xtensa/esp32/esp32_defconfig as base
build output: Merging /zephyr/tests/include/test.config
build output: Merging prj.conf
build output: outdir-ari3-asid-esp32/boot_config.conf
build output: # configuration written to .config

build passed: 'make -j -C zephyr/tests/net/mgmt 
EXTRA_CFLAGS="-Werror -Wno-error=deprecated-declarations" 
KCPPFLAGS=-DTC_RUNID=:asid 
BOARD=esp32 ARCH=xtensa  
O=outdir-ari3-asid-esp32'

build passed

make flash

Reset

eval failed: found expected (for failure) `(USAGE FAULT|[Ff]atal fault in )` in console `esp32
:default` at 1.35s

console output: Running test suite test_mgmt_fn

**console output:** ===================================================================
console output: starting test - test_mgmt
console output: Starting Network Management API test
console output: - Request Net MGMT
console output: - Sending event 1 times, without a receiver, without info
console output:         Throwing event 0x97ab1234 1 times
console output: - Sending event 2 times, without a receiver, without info
console output:         Throwing event 0x97ab1234 2 times
console output: - Sending event 1 times, with a receiver, without info
console output:         Throwing event 0x97ab1234 1 times
console output:                 Received event 0x97ab1234
console output:         Received 0x97ab1234 1 times
console output: - Sending event 2 times, with a receiver, without info
console output:         Throwing event 0x97ab1234 2 times
console output:                 Received event 0x97ab1234
console output:                 Received event 0x97ab1234
console output:         Received 0x97ab1234 2 times
console output: - Sending event 1 times, without a receiver, with info
console output:         Throwing event 0x97ab1234 1 times
console output:         Throwing event 0x97ab1234 1 times
console output:                 Received event 0x97ab1234
console output:         Received 0x97ab1234 1 times
console output: - Sending event 2 times, with a receiver, without info
console output:         Throwing event 0x97ab1234 2 times
console output:                 Received event 0x97ab1234
console output:                 Received event 0x97ab1234
console output:         Received 0x97ab1234 2 times
console output: - Sending event 1 times, without a receiver, with info
console output:         Throwing event 0x97ab1234 1 times
console output: - Sending event 2 times, without a receiver, with info
console output:         Throwing event 0x97ab1234 2 times
console output: - Sending event 1 times, with a receiver, with info
console output:         Throwing event 0x97ab1234 1 times
console output:                 Received event 0x97ab1234
console output:         Received 0x97ab1234 1 times
console output: - Sending event 2 times, with a receiver, with info
console output:         Throwing event 0x97ab1234 2 times
console output:                 Received event 0x97ab1234
console output:                 Received event 0x97ab1234
console output:         Received 0x97ab1234 2 times
console output: - Triggering core event: 0xf0600001
console output:                 Received event 0xf0600001
console output: - Triggering core event: 0xf0600002
console output:                 Received event 0xf0600002
console output: - Synchronous event listener
console output:         Throwing event 0x97ab1234 2 times
console output: *** Unhandled exception ****
console output: Exception cause 28 (load prohibited):
console output:   EPC1     : 0x40086386 EXCSAVE1 : 0x8008827d EXCVADDR : 0x00000010
console output: Program state (PS):
console output:   INTLEVEL : 03 EXCM    : 0 UM  : 1 RING : 0 WOE : 1
console output:   OWB      : 04 CALLINC : 2
console output: Current thread ID = 0x3ffb2214
console output: Faulting instruction address = 0xdeaddead
console output: Fatal fault in ISR! Spinning...

  evaluation failed

**Comment by nashif** [comment]
can't reproduce, also esp32 is currently not a platform where networking is supported.
