### ISSUE TITLE
subsys settings: should check the return value of function cs->cs_itf->csi_load(cs, &arg).

### ISSUE THREAD

**Issue by CV-Bowen** [zephyrproject-rtos/zephyr#46034]
**Is your enhancement proposal related to a problem? Please describe.**
I see the return value of function `cs->cs_itf->csi_load(cs, &arg)` was ignored in function `settings_load_subtree()` and `settings_load_subtree_direct()`, i think the return value should be processed instead ignored.

**Describe the solution you'd like**
If the `csi_load()` failed, a error number should be returned.

**Comment by Laczen** [comment]
> **Is your enhancement proposal related to a problem? Please describe.** I see the return value of function `cs->cs_itf->csi_load(cs, &arg)` was ignored in function `settings_load_subtree()` and `settings_load_subtree_direct()`, i think the return value should be processed instead ignored.
> 
> **Describe the solution you'd like** If the `csi_load()` failed, a error number should be returned.

Hi @CV-Bowen, the problem is that `csi_load` is returning multiple entries, and one of them fails. Should the routine then stop, or continue ?

**Comment by CV-Bowen** [comment]
> > **Is your enhancement proposal related to a problem? Please describe.** I see the return value of function `cs->cs_itf->csi_load(cs, &arg)` was ignored in function `settings_load_subtree()` and `settings_load_subtree_direct()`, i think the return value should be processed instead ignored.
> > **Describe the solution you'd like** If the `csi_load()` failed, a error number should be returned.
> 
> Hi @CV-Bowen, the problem is that `csi_load` is returning multiple entries, and one of them fails. Should the routine then stop, or continue ?

I think the routine should stop immediately and return the error code once `csi_load()` failed.

**Comment by Laczen** [comment]
@CV-Bowen, stopping immediately doesn't seem a good idea. The error code from `csi_load()` would be the result of the set handler. The application already knows that there is some problem with loading a specific entry (in the set handler), why should it stop loading other entries.

**Comment by Laczen** [comment]
> @CV-Bowen, stopping immediately doesn't seem a good idea. The error code from `csi_load()` would be the result of the set handler. The application already knows that there is some problem with loading a specific entry (in the set handler), why should it stop loading other entries?

**Comment by CV-Bowen** [comment]
> @CV-Bowen, stopping immediately doesn't seem a good idea. The error code from `csi_load()` would be the result of the set handler. The application already knows that there is some problem with loading a specific entry (in the set handler), why should it stop loading other entries?

Do you mean application has known the error code in the callback function (`struct settings_load_arg: cb`) called in `settings_call_set_handler()` ?

**Comment by CV-Bowen** [comment]
OK, i understood, thank you for detailed explanation! I will close this issue.
