### ISSUE TITLE
`unexpected eof` with twister running `tests/subsys/logging/log_api/logging.log2_api_immediate_printk_cpp` on `qemu_leon3`

### ISSUE THREAD

**Issue by dcpleung** [zephyrproject-rtos/zephyr#46056]
**Describe the bug**
When running twister during testing `tests/subsys/logging/log_api/logging.log2_api_immediate_printk_cpp` on `qemu_leon3`, it reports `unexpected eof` even though the tests reported successful. This results in twister reporting the test being failed.

When running it using `west build`, QEMU quits immediately after printing `PROJECT EXECUTION SUCCESSFUL` instead of just waiting there for `Ctrl-A X`. If main stack size is changed to 4096 instead of 2048, QEMU would behave correctly.

**To Reproduce**
1. `west build -p -b qemu_leon3 tests/subsys/logging/log_api -t run -- -DCONFIG_LOG_MODE_IMMEDIATE=y -DCONFIG_LOG_PRINTK=y -DCONFIG_CPLUSPLUS=y`
2. Terminal shows `PROJECT EXECUTION SUCCESSFUL`, and QEMU terminates itself, returning to command prompt.

**Expected behavior**
This should pass twister test without errors.

**Impact**
Annoyance for now but it's causing CI to report test failures on PRs.

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: Zephyr SDK 0.14.2
 - Commit SHA: 4b111c1ee81e912f57d4a5ce03d242213bd1b959

**Comment by mbolivar-nordic** [comment]
Fixed by https://github.com/zephyrproject-rtos/zephyr/pull/46082
