### ISSUE TITLE
LE Audio: Use bt_codec_data data and size_t data_count in codec.c

### ISSUE THREAD

**Issue by alexsven** [zephyrproject-rtos/zephyr#46079]
**Is your enhancement proposal related to a problem? Please describe.**
When receiving a base in broadcast samples I want to be able to use the functions described in codec.c to get codec information like frequency, frame_duration etc, but the functions there all require bt_codec to be sent. As far I've seen, the bt_codec is not necessarily populated for a given subgroup, only the bis_data is.

**Describe the solution you'd like**
 To avoid having duplicated code for getting this information these functions should accept bt_codec_data *data and size_t data_count.

**Comment by Thalley** [comment]
Closing as the new API from https://github.com/zephyrproject-rtos/zephyr/pull/58331 and https://github.com/zephyrproject-rtos/zephyr/pull/58079 indirectly fixed this
