### ISSUE TITLE
esp32: Unable to select GPIO for PWM LED driver channel

### ISSUE THREAD

**Issue by LucasTambor** [zephyrproject-rtos/zephyr#46167]
**Describe the bug**
The PWM channel is defined in the device tree overlay file, but the GPIO that is mapped to this channel is defined in Kconfig. 
The current implementation is swapping the configured  PWM channel with the associated GPIO, using the channel given in DTS as both PWM channel and GPIO. By doing this it makes the driver unable to configure another GPIO for a given channel.

I tested this with the blinky_pwm sample in both esp wrover kit and esp32 devkitc boards and had the same results.

**To Reproduce**

esp_wrover_kit.overlay and esp32.overlay:
```
#include <zephyr/dt-bindings/pwm/pwm.h>

/ {
	aliases {
		pwm-0 = &ledc0;
		pwm-led0 = &pwm_led_blue;
	};

	pwmleds {
		compatible = "pwm-leds";
		pwm_led_blue: pwm_led_gpio0_2 {
		   label = "PWM LED0";
		   pwms = <&ledc0 2 1000 PWM_POLARITY_NORMAL>;
		};
	};
};

&ledc0 {
	status = "okay";
};

```

1. west build -b esp_wrover_kit samples/basic/blinky_pwm
2. west build -b esp_wrover_kit -t menuconfig
3. Select the GPIO number for PWM channel 2 (DTS). 

![image](https://user-images.githubusercontent.com/25518792/171407404-9eb2f210-84c0-4b89-8638-9d3a9c2e85cd.png)

The selected GPIO_4 is connected to LED Blue in the esp wrover kit.

5. Rebuild
6. west flash

You will see that the LED Green lights up, regardless of the GPIO configuration. If you change the PWM channel number in the esp_wrover_kit.overlay to 4, the LED Blue will light up, but will ignore the GPIO configuration for channel 4.

**Expected behavior**
It is expected that the driver uses the given GPIO to PWM channel mapping.

**Impact**
This bugs limits the use of the PWM, since we have up to 16 PWM channels and 40 GPIOs that can be mapped to this channels. This bug allow us to use only one GPIO at a given channel, limited in 16 channels.

**Environment (please complete the following information):**
 - OS: Linux 
 - Toolchain: zephyr-sdk-0.14.2
 - Zephyr version: 3.1.0-rc3

**Comment by bhuvanchandra** [comment]
Hello,
I see " https://github.com/zephyrproject-rtos/zephyr/issues/46167 - esp32: Unable to select GPIO for PWM LED driver channel " mentioned in the release notes of v3.1.0 but the commit didn't really make it into release.
