### ISSUE TITLE
ipc_service: open-amp backend may never leave

### ISSUE THREAD

**Issue by rakons** [zephyrproject-rtos/zephyr#46170]
**Describe the bug**
In this commit: https://github.com/zephyrproject-rtos/zephyr/commit/7f51907fda2dd30f18d01262f06c175714a9be3f the default priority level of the was set to K_PRIO_COOP(0) instead of K_PRIO_PREEMPT(0).

There are 2 issues with this:
1. K_PRIO_COOP(0) is the highest available priority in the system. It should rather be K_PRIO_COOP(CONFIG_NUM_COOP_PRIORITIES - 1) by default.
2. The function rpmsg_virtio_rx_callback that is used from open-amp never leaves the loop as long as it has data to process. So even if the thread level is low enough to allow other threads to run, if it is fed fast enough it would starve the rest of the system as long as it is cooperative thread. We need a k_yield here in the right place when it runs on cooperative level.

**To Reproduce**
It is enough to continuously send a lot of messages using IPC.

**Expected behavior**
CPU needs to have a time to process the messages. It is better to postpone the transmission than allow whole program to fail because it cannot process messages and some internal buffers overflows.

**Impact**
As long as open-amp works on any level of cooperative mode we cannot trust it in current state.

**Comment by carlocaione** [comment]
tagging a few people here @arnopo @hubertmis @ahasztag 

I think the real problem here is that using the highest cooperative priority here is a mistake. That was introduced back in the days by https://github.com/zephyrproject-rtos/zephyr/commit/001894a1c0f1c0a8d90857134a7627644bdc670c to solve some internal performance issues.

> K_PRIO_COOP(0) is the highest available priority in the system. It should rather be K_PRIO_COOP(CONFIG_NUM_COOP_PRIORITIES - 1) by default.

I would really much prefer to have something like `K_PRIO_PREEMPT(0)` as default value and leave to the user the possibility to move to a cooperative priority if needed using the `zephyr,priority` DT property.

> The function rpmsg_virtio_rx_callback that is used from open-amp never leaves the loop as long as it has data to process. So even if the thread level is low enough to allow other threads to run, if it is fed fast enough it would starve the rest of the system as long as it is cooperative thread. We need a k_yield here in the right place when it runs on cooperative level.

Yes, but this is indeed a consequence of having an higher-than-everything-else thread running, by lowering its priority this problem should disappear, so I don't think that having a `k_yield()` is needed at all. Also, if the user really needs that, that can be added in the endpoint received callback in the user code.

**Comment by rakons** [comment]
> Yes, but this is indeed a consequence of having an higher-than-everything-else thread running, by lowering its priority this problem should disappear

As long as it is preemptive priority it is ok. As long as it is cooperative priority level it starts to be an issue.

**Comment by rakons** [comment]
Right. Then it just cannot be cooperative by default. I think that default should be the safe option and then the user may tune it for his application.

**Comment by pdunaj** [comment]
> tagging a few people here @arnopo @hubertmis @ahasztag
> 
> I think the real problem here is that using the highest cooperative priority here is a mistake. That was introduced back in the days by [001894a](https://github.com/zephyrproject-rtos/zephyr/commit/001894a1c0f1c0a8d90857134a7627644bdc670c) to solve some internal performance issues.
> 
> > K_PRIO_COOP(0) is the highest available priority in the system. It should rather be K_PRIO_COOP(CONFIG_NUM_COOP_PRIORITIES - 1) by default.
> 
> I would really much prefer to have something like `K_PRIO_PREEMPT(0)` as default value and leave to the user the possibility to move to a cooperative priority if needed using the `zephyr,priority` DT property.
> 
> > The function rpmsg_virtio_rx_callback that is used from open-amp never leaves the loop as long as it has data to process. So even if the thread level is low enough to allow other threads to run, if it is fed fast enough it would starve the rest of the system as long as it is cooperative thread. We need a k_yield here in the right place when it runs on cooperative level.
> 
> Yes, but this is indeed a consequence of having an higher-than-everything-else thread running, by lowering its priority this problem should disappear, so I don't think that having a `k_yield()` is needed at all. Also, if the user really needs that, that can be added in the endpoint received callback in the user code.

Great that the priority was reconsidered. I still recommend to add explicit yield if we expect code might enter a processing loop (which I believe is the case here).

**Comment by hubertmis** [comment]
> I still recommend to add explicit yield if we expect code might enter a processing loop (which I believe is the case here).

I agree with @carlocaione . I think it's user of this API who should decide if callback should yield or not. Someone could have high priority IPC which should not yield to other tasks.

**Comment by rakons** [comment]
@pdunaj 
> Check it quickly - there should be yield as workq uses default config so no_yield is disabled. Lowering the prio should be fine there.

Open-AMP uses modules/lib/open-amp/lib/rpmsg/rpmsg_virtio.c. There is processing function that handles the data in rpmsg_virtio_rx_callback. It is called via the workqueue in our backend. But this function would not leave as long as there is any data to process:

```
static void rpmsg_virtio_rx_callback(struct virtqueue *vq)
{
	(...)
	rp_hdr = rpmsg_virtio_get_rx_buffer(rvdev, &len, &idx);

	(...)

	while (rp_hdr) {
		(...)
		rp_hdr = rpmsg_virtio_get_rx_buffer(rvdev, &len, &idx);
		(...)
	}
```
So as long as it is cooperative thread it can starve the system if overloaded with transfer.

Just for testing purposes I was trying to set a k_yield in ept_cb inside ipc_rpmsg_static_varings.c (just not to touch the sources in external modules). Exactly in this point:

```
static int ept_cb(struct rpmsg_endpoint *ep, void *data, size_t len, uint32_t src, void *priv)
{
	(...)
	if (ept->cb->received) {
		ept->cb->received(data, len, ept->priv);
		k_yield();
	}
	(...)
}
```

And it worked, but I am not really sure if it is really smart as being inside rpmsg_virtio_rx_callback main loop we keep the mutex locked there.
