### ISSUE TITLE
ISO Broadcaster fails silently on unsupported RTN/SDU_Interval combination

### ISSUE THREAD

**Issue by GatCode** [zephyrproject-rtos/zephyr#46186]
When a user selects a specific RTN/SDU_Interval combination in the ISO_BROADCAST sample, broacaster fails without an error message. The user doesn't know what has happened.

As @Thalley suggested, a short error message would be nice to have.

Note: tested on two nRF52840DK boards with the code of the following draft PR: https://github.com/zephyrproject-rtos/zephyr/pull/46187

![Screenshot 2022-06-02 at 12 18 32 PM](https://user-images.githubusercontent.com/19287308/171609043-5fe14e99-21ca-47eb-980f-56896a38b8cd.png)

**Comment by Thalley** [comment]
The error seen is that no ISO data is seemingly received on the sync receiver, right @GatCode ?

**Comment by GatCode** [comment]
Exactly, only the BigInfo is printed on the receiver side.
Additionally the output on the sender side is exactly the screenshot above but it should print `Sending value ...` every second.

**Comment by Thalley** [comment]
> Exactly, only the BigInfo is printed on the receiver side. Additionally the output on the sender side is exactly the screenshot above but it should print `Sending value ...` every second.

So at least the periodic advertisement seems to be fine. From your log, it seems that just the BIG sync never completes.
