### ISSUE TITLE
Release notes for v3.1.0: eeprom

### ISSUE THREAD

**Issue by mbolivar-nordic** [zephyrproject-rtos/zephyr#46213]
As maintainer, please send a pull request filling in the "eeprom" section(s) in doc/releases/release-notes-3.1.rst as soon as possible.

**Comment by henrikbrixandersen** [comment]
@mbolivar-nordic There were no relevant changes to the EEPROM drivers/API for v3.1.0. Previous release notes have just kept empty sections - would you like me to remove the EEPROM sections instead?
