### ISSUE TITLE
imxrt1010 wrong device tree addresses

### ISSUE THREAD

**Issue by teburd** [zephyrproject-rtos/zephyr#46255]
**Describe the bug**
nxp_rt1010 includes nxp_rt, which has incorrect IP address locations for at least lpi2c1 and sai1. It's missing sai1 as enabled despite having an audio codec (wm8960) on the board. There also seem to be some power/clock gating issues.

**To Reproduce**
1. build real world samples using IPs with mimxrt1010_evk. I tried to configure the wm8960 dac and play audio from it.

Partially working sample with rt1010 hack ups: https://github.com/teburd/zephyr/commit/8dbdc9b9935f37d74a68bfc56bd94ceaf9aa7af7
Same sample without rt1010 hack ups: https://github.com/teburd/zephyr/commit/855943fe4ee84c490727a6da19c0838ee30c3e36

Hack ups for nxp_rt.dtsi and Kconfigs to make it partially work are in commit https://github.com/teburd/zephyr/commit/dfc28de0e4978e85936390df649a815463058e26

Same sample (without the hack ups) works mostly on a 1060evk (doesn't play audio yet, but thats a codec configuration issue I'm sure).

The rt1010 stuff with my hackups gets stuck on i2c calls, I'm guessing due to clock/power gating?

```
west build -b mimxrt1010_evk -p always samples/rtio/mosyn
west flash -r pyocd
```

**Expected behavior**
Valid and correct device tree addresses for peripherals.

**Impact**
Peripheral accesses cause bus faults on imxrt1010

**Comment by mmahadevan108** [comment]
@teburd I have looked at the changes proposed to the `nxp_rt10xx.dtsi` file. The Reference Manual states L1I2C start address is `0x403F0000` and SAI1  is at '0x40384000' which is what we have in the dtsi file. These values in the .dtsi file looks correct.

**Comment by teburd** [comment]
@mmahadevan108 Which reference manual? I'm looking right at imxrt1010rm and it says SAI1 base is 401E_0000h

![Screenshot from 2022-09-15 17-03-22](https://user-images.githubusercontent.com/135839/190516455-cf2c7cc7-bd20-4f92-b12d-d4f51fbf0639.png)
