### ISSUE TITLE
Regulator Control 

### ISSUE THREAD

**Issue by klewisBE** [zephyrproject-rtos/zephyr#46263]
I am having issues controlling regulators. I am on version 3.0 of zephyr. We have three regulators defined in the dts file and they all turn on properly during startup. I am trying to add power management where the regulators will need to be disabled and enabled by software. When I try to disable and enable them I end up with an error. I have it set up as compatible with regulator-fixed-sync and regulator-fixed. For the disable I am failing because im getting 0 as a return from onoff_sync_lock and thus and invalid argument error https://github.com/zephyrproject-rtos/zephyr/blob/main/drivers/regulator/regulator_fixed.c#L305. Im not getting any compilation errors which I would have expected if I wasn’t setting up the dts file correctly.

I am doing this on a custom board with an STM32 h7 inside of it.
I cannot share the full software, but I think this is all of the relevant parts.

dts file 
```
aliases {
  pwr3v3 = &pwr_3v3;
};

pwr_3v3: pwr-3v3-ctrl {
  /*
  * PWR rail for SPI-flash, Temp-Sensor, RS-485 Transceiver,
  * and for external devices(Grove, header).
  * Requires closed J15 (D9)
  */
  compatible = "regulator-fixed-sync", "regulator-fixed";
  label = "pwr-3v3-ctrl";
  regulator-name = "pwr-3v3-ctrl";
  enable-gpios = <&gpioe 4 GPIO_ACTIVE_HIGH>;
  regulator-boot-on;
  status = "okay";
};
```

test usage
```
#define REGULATOR3_3	DT_ALIAS(pwr3v3) 
if (regulator_disable(DEVICE_DT_GET(REGULATOR3_3)) < 0) {
    printk("didnt work\n");
}
k_msleep(1000);
if (regulator_enable(DEVICE_DT_GET(REGULATOR3_3), NULL) < 0) {
    printk("didnt work\n");
}
```

I would expect the regulator to turn off for one second. Instead both prink statements are hit.

**Comment by carlescufi** [comment]
@nordic-krch since this seems to be an issue at the `onoff` handling level, would you mind taking a look?
