### ISSUE TITLE
Sample app enabling sensors on disco_l475_iot1 board

### ISSUE THREAD

**Issue by erwango** [zephyrproject-rtos/zephyr#4628]
Board disco_l475_iot1 board embeds several sensors (hts221, LIS3MDL, LSM6DSL, LPS22HB)
Provide a board specific app making all work together.

**Comment by nashif** [comment]
@erwango is this ever going to happen? Or has it happened already?

**Comment by erwango** [comment]
Well, I don't think this is a priority now and I don't think anyone will miss it. There are samples for these sensors (or equivalent), so nothing critical here. Let me close it
