### ISSUE TITLE
Sample app 'coaps_server' fails to parse coap pkt

### ISSUE THREAD

**Issue by vakulgarg** [zephyrproject-rtos/zephyr#4630]
On running coaps_server sample, it fails and displays error:

"Could not parse packet".

I am using steps provided with example's README file.
The non-dtls variant of same sample application coap_server works as expected.

------------------------------------------------------------------------------------------
On digging into code, I found that the api coap_packet_parse() expects that input 'net_pkt' contains  IP header, UDP header and any extension headers. Therefore the  api first skips all the headers.
The application coaps_server receives the data from api mbedtls_ssl_read(). So it does not get the transport headers back. 

Hence while constructing net_pkt to be parsed using coap_packet_parse(), the packet fragments do not have any transport headers.

**Comment by jukkar** [comment]
This is related to issue described in commit 4fea5b18ab6aeb6db691589e227051a299f63528 
As there is no IP header after packet is received from DTLS tunnel, the coap library fails to parse it. I am working on a similar fix as described in above commit.

**Comment by vakulgarg** [comment]
Hi Jukka

Isn't it a layer violation to require coap library having to deal with
transport (& possibly DTLS) headers?
IMO, coap library should be passed only the data relevant to it.
The other headers if any should be stripped by application itself.

Regards

Vakul

**Comment by jukkar** [comment]
> Isn't it a layer violation to require coap library having to deal with transport (& possibly DTLS) headers? IMO, coap library should be passed only the data relevant to it. The other headers if any should be stripped by application itself.

Coap library does not need information about the actual data in transport headers, it needs to know where the user payload (=coap in this case) starts etc. So it might be enough if we set this accounting information properly in net_pkt, but I need to investigate this more. Currently the coaps code just strips away the transport headers but does not update the packet accounting information.
