### ISSUE TITLE
get_maintainer.py incorrectly invoked by Github?

### ISSUE THREAD

**Issue by marc-hb** [zephyrproject-rtos/zephyr#46345]
In PR #44188, the `MAINTAINERS.yml` file should have added some SOF people, see lyakh, lgirdwood, marc-hb and kv2019i below. It did not. No one from the SOF team was aware of the very useful but backward-incompatible 44188 and it caused a (fortunately short-lived) Zephyr build failure in SOF CI.

@nashif, @cfriedt  there seems to some `get_maintainer.py`-related glitch somewhere. Where is the `get_maintainer.py`invocation that assigns reviewers and the corresponding log for 44168?

PS: the "platform: Intel CAVS" github label was not automatically added either.

```
git checkout e4c171ed2255
./scripts/get_maintainer.py commits e4c171ed2255~5..e4c171ed2255

Intel Platforms (Xtensa)
	status: maintained
	maintainers: nashif
	collaborators: andyross, dcpleung, lyakh, lgirdwood, mengxianglinx, marc-hb, kv2019i, MaureenHelm
	inform: 
	labels: platform: Intel CAVS
	description: 

Twister
	status: maintained
	maintainers: nashif
	collaborators: chen-png, galak, PerMac, enjiamai, hakehuang, gopiotr
	inform: 
	labels: area: Twister
	description: 

West
	status: maintained
	maintainers: mbolivar-nordic
	collaborators: carlescufi, swinslow
	inform: 
	labels: area: West
	description: 
```

_Originally posted by @marc-hb in https://github.com/zephyrproject-rtos/zephyr/issues/44188#issuecomment-1147928311_

**Comment by nashif** [comment]
we do not use `./scripts/get_maintainer.py ` to assign reviewers, this is done manually at the moment and probably this PR was missed for some other reason, so this is an invalid bug.
The step is planned to be automated, but we are not there yet.

**Comment by marc-hb** [comment]
Interestingly, some "zephyrbot" just performed a large update to the list of reviewers of #44188. This update seems to match MAINTAINERS.yml but... days after 44188 was merged.
![Screenshot 2022-06-08 at 06 57 31](https://user-images.githubusercontent.com/46978960/172635161-7f015301-8fa8-4c04-b0d1-cbeb79582cc7.png)

**Comment by stephanosio** [comment]
https://github.com/zephyrproject-rtos/zephyr/pull/46380
