### ISSUE TITLE
xtensa-esp32-elf-gcc.exe: error: unrecognized command line option '-no-pie'

### ISSUE THREAD

**Issue by micheljung** [zephyrproject-rtos/zephyr#4635]
OS: Windows 10
Board: ESP32
Zephyr at [e5b3918](https://github.com/zephyrproject-rtos/zephyr/commit/e5b3918a9ffc80e6ba079c6a0eff60aaa42917d0)
esp-idf at [dc8c338](https://github.com/espressif/esp-idf/commit/dc8c33892e0082822c4c69afa201c02d9758a1c0)
ESP32 Win32 msys2 environment: [2017-09-18](https://dl.espressif.com/dl/esp32_win32_msys2_environment_and_toolchain-20170918.zip)

    MSYS zephyr/samples/hello_world
    $ make BOARD=esp32

```
[...]
xtensa-esp32-elf-gcc.exe: error: unrecognized command line option '-no-pie'
make[2]: *** [/s/sb-dev/zephyr/Makefile:876: zephyr_prebuilt.elf] Error 1
make[2]: Leaving directory '/s/sb-dev/zephyr/samples/hello_world/outdir/esp32'
make[1]: *** [Makefile:178: sub-make] Error 2
make[1]: Leaving directory '/s/sb-dev/zephyr'
make: *** [/s/sb-dev/zephyr/Makefile.inc:82: all] Error 2
```

see https://github.com/zephyrproject-rtos/zephyr/commit/cdec108bfe0ff33c94542b31ef19ce547e2d5f67

**Comment by nashif** [comment]
should be fixed now with cmake
