### ISSUE TITLE
ARM64: Relax 4K MMU mapping alignment

### ISSUE THREAD

**Issue by carlocaione** [zephyrproject-rtos/zephyr#46401]
The problem came up in #45737

In same (rare) cases you want to map a MMIO region that is either smaller or not aligned to 4K. This is currently not supported by the MMU driver.

We have two solutions here:

1. We map the physical 4k-aligned address to different virtual addresses.
2. We check whether the mapping overlaps with an existing mapping and fix / extend the mapping when required.

**Comment by jhedberg** [comment]
Any schedule for completing this one? The Stale label has been added tons of times :)

**Comment by carlocaione** [comment]
@jhedberg I don't think anyone is working on this, so no ETA on this.
