### ISSUE TITLE
STM32WB BLE HCI interface problem.

### ISSUE THREAD

**Issue by rokobertcm** [zephyrproject-rtos/zephyr#46400]
I'm try to use BLE controller stack in STM32WB55 to comunicate with Zephyr BLE host stack with no success.
In network procesor M0+ run ST propriatery controller stack "stm32wb5x_BLE_Stack_full_fw.bin" V1.13.3.
In application processor M4 I use sample application "boards-stm32-power_mgmt-stm32wb_ble-sample".

Compiling and flashing goes well. But when I start program, it stops after 10 second with error when waiting semaphore:

ASSERTION FAIL [err == 0] @ WEST_TOPDIR/zephyr/subsys/bluetooth/host/hci_core.c:309
        k_sem_take failed with err -11

Is there any support team for STM32 and their BLE stack?

**Comment by piotrParf** [comment]
Check if you have turned on the proprietary BLE stack(do not check the version or FUS after flashing the ble stack). Also, check with only the HCI stack version. I had similar issues and I addressed them in this comment. It stops because of lack of executing the HCI commands.

**Comment by rokobertcm** [comment]
I'm got an answer from ST support. They said, that they use "stm32wb5x_BLE_HCILayer_extended_fw.bin" firmware V1.13.3. I can confirm that this firmware works with Zephyr 3.1 HCI interface. Other firmawares does not work.
I will be in touch with ST support to clarify how to use other firmwares. I'm also interested to use BLE and Thread together.

This is list of all firmwares:

stm32wb5x_BLE_HCILayer_extended_fw.bin
stm32wb5x_BLE_HCILayer_fw.bin
stm32wb5x_BLE_HCI_AdvScan_fw.bin
stm32wb5x_BLE_LLD_fw.bin
stm32wb5x_BLE_Mac_802_15_4_fw.bin
stm32wb5x_BLE_Stack_basic_fw.bin
stm32wb5x_BLE_Stack_full_extended_fw.bin
stm32wb5x_BLE_Stack_full_fw.bin
stm32wb5x_BLE_Stack_light_fw.bin
stm32wb5x_BLE_Thread_static_fw.bin
stm32wb5x_BLE_Zigbee_FFD_dynamic_fw.bin
stm32wb5x_BLE_Zigbee_FFD_static_fw.bin
stm32wb5x_BLE_Zigbee_RFD_dynamic_fw.bin
stm32wb5x_BLE_Zigbee_RFD_static_fw.bin
stm32wb5x_Mac_802_15_4_fw.bin
stm32wb5x_Phy_802_15_4_fw.bin
stm32wb5x_Thread_FTD_fw.bin
stm32wb5x_Thread_MTD_fw.bin
stm32wb5x_Thread_RCP_fw.bin
stm32wb5x_Zigbee_FFD_fw.bin
stm32wb5x_Zigbee_RFD_fw.bin

**Comment by cvinayak** [comment]
> I can confirm that this firmware works with Zephyr 3.1 HCI interface. 

Closing

**Comment by erwango** [comment]
Note:
Since V13.2.0, 2 versions of the fw are compatible with Zephyr:
- stm32wb5x_BLE_HCILayer_fw.bin
- stm32wb5x_BLE_HCILayer_extended_fw.bin
- stm32wb5x_BLE_HCI_AdvScan_fw.bin

For more information on these binaries, get release notes from [STM32CubeWB github page](https://github.com/STMicroelectronics/STM32CubeWB/blob/master/Projects/STM32WB_Copro_Wireless_Binaries/STM32WB5x/)
