### ISSUE TITLE
Triage role for bbilas

### ISSUE THREAD

**Issue by bbilas** [zephyrproject-rtos/zephyr#46424]
# Nomination

## GitHub User

1. Full Name: Bartosz Biłas
2. GitHub username: [bbilas](https://github.com/bbilas)
3. Organization: [Grinn](https://github.com/grinn-pub)

## Supporting Documents

https://github.com/zephyrproject-rtos/zephyr/pulls?q=is%3Apr+author%3Abbilas+

**Comment by stephanosio** [comment]
Added as a contributor with triage permission.
