### ISSUE TITLE
STM32F4 CAN2 peripheral not working

### ISSUE THREAD

**Issue by martinjaeger** [zephyrproject-rtos/zephyr#46519]
**Describe the bug**

Devices like the STM32F466 have two CAN peripherals, which are closely coupled (they share memory and filters).

If CAN2 is enabled, it acts as a slave and requires CAN1 to be clocked as well. This is not done in current Zephyr driver.

Without CAN1 clock enabled, CAN2 only receives and sends garbage. This issue is also described [here](https://community.st.com/s/question/0D50X0000A1nrx4SQA/using-can2-slave-without-can1-master).

**To Reproduce**

`west build -b nucleo_f446re samples/drivers/can -p` with the following overlay:

```
/ {
        chosen {
                zephyr,canbus = &can2;
        };
};

&can1 {
	status = "disabled";
};

&can2 {
	pinctrl-0 = <&can2_rx_pb12 &can2_tx_pb13>;
	pinctrl-names = "default";
	bus-speed = <125000>;
	status = "okay";
};
```

**Expected behavior**
The sample should print an increasing counter as shown below, but it does not receive the messages.

```
Counter received: 0
Counter received: 1
Counter received: 2
Counter received: 3
Counter received: 4
```

With loopback mode disabled, random CAN frames can be observed on the bus.

**Impact**

CAN2 cannot be used.

**Comment by fabiobaltieri** [comment]
(assigning back since there's a linked PR)
