### ISSUE TITLE
Wrong file name for drivers/aio/aio_comparator_handlers.o

### ISSUE THREAD

**Issue by SebastianBoe** [zephyrproject-rtos/zephyr#4654]
@andrewboie : Should be .c, not .o

https://github.com/zephyrproject-rtos/zephyr/commit/9c37af10ece52e8c992e1c14464431be896cb218

**Comment by SebastianBoe** [comment]
Same with drivers/flash/flash_handlers.o

**Comment by andrewboie** [comment]
fixing this now
