### ISSUE TITLE
Bluetooth: Controller: Doc inconsistency

### ISSUE THREAD

**Issue by caco3** [zephyrproject-rtos/zephyr#46556]
There seem to be some documentation inconsistency:

1. `CONFIG_BT_CTLR_ULL_HIGH_PRIO` can be found in the docs for Zephyr `3.0.0`: https://docs.zephyrproject.org/3.0.0/search.html?q=BT_CTLR_ULL_HIGH_PRIO but can not be found in 3.1.0: https://docs.zephyrproject.org/3.1.0/search.html?q=BT_CTLR_ULL_HIGH_PRIO, see also https://github.com/zephyrproject-rtos/zephyr/discussions/46529
2. In `3.1.0` it only can be found through the `Kconfig Search` at https://docs.zephyrproject.org/3.1.0/kconfig.html
3. Searching there for `CONFIG_BT_CTLR_ULL_HIGH_PRIO` shows a dependency for its default value to `CONFIG_BT_CTLR_ULL_LLL_PRIO_SUPPORT`. How ever that flag itself can not be found: https://docs.zephyrproject.org/3.1.0/kconfig.html#CONFIG_BT_CTLR_ULL_LLL_PRIO_SUPPORT

**Comment by carlescufi** [comment]
I am not sure if this is a Kconfig doc issue or an actual Bluetooth controller problem.

**Comment by cvinayak** [comment]
This is not Bluetooth Controller problem, the Kconfigs are common to both v3.0.0 and v3.1.0 releases.

1. The documentation search no longer finds Kconfigs in the v3.1.0 documentation.
2. The Kconfig options section in documentation only find the non-hidden Kconfigs in v3.1.0 documentation.

In comparison, v3.0.0 can find all Kconfigs (non-hidden and hidden) in the documentation search available in the left side margin.

Also, the Kconfig options page is missing in v3.1.0 release:
![image](https://user-images.githubusercontent.com/6350656/174225632-1e6afb8d-b57f-48a9-a63a-2838435c1dfc.png)

Whereas v3.0.0 release displays this:
![image](https://user-images.githubusercontent.com/6350656/174225693-adfef9e2-43ed-4b83-b7d6-fc2deacb8ba7.png)

**Comment by carlescufi** [comment]
Closing with explanation from @cvinayak and @gmarull, thanks both!

**Comment by caco3** [comment]
Thanks for the explanations!

Personally I think it is rater odd that a parameter shows references to other parameters with a link but then the new page does not provide new information. It would be more consistent if those hidden parameters would have no link.
But I understand that this might not be trivial to improve.
