### ISSUE TITLE
test: samples/drivers/adc twister result wrong

### ISSUE THREAD

**Issue by hunterhu3000** [zephyrproject-rtos/zephyr#46555]
**Describe the bug**
While running daily test, the test case of samples/drivers/adc is failed due to the mec172xevb_assy6906.overlay does not contain the info of adc0. This can be fixed by https://github.com/zephyrproject-rtos/zephyr/pull/46854.

But there is another issue. The logs in email "Jenkins auto test result: Github main" -> HTML-> sample.drivers.sample.drivers.adc  displays the log which does not belong to this test case.  See below:
```
Test Class: sample.drivers
sample.drivers.adc
sample.drivers
Time Taken: 15.85s
Failed: No Console Output(Timeout)
Toggled led0; counter=37
Toggled led0; counter=38
Toggled led0; counter=39
Toggled led1; counter=4
Toggled led0; counter=40
Toggled led0; counter=41
Toggled led0; counter=42
***** delaying boot 500ms (per build configuration) *****
***** delaying boot 500ms (per build configuration) *****
*** Booting Zephyr OS build zephyr-v3.1.0-394-g2d87948818cc  (delayed boot 500ms) ***
Could not setup channel #0 (-134)
```
Grep the "Toggled led" in the code, we found it belongs to the test of samples/basic/threads/, which is pass in the daily test.

Please also mention any information which could help others to understand
the problem you're facing:
 - What target platform are you using?  mec172xevb_assy6906

**To Reproduce**
1. twister -p mec172xevb_assy6906 --device-testing --device-serial /dev/ttyUSB0 -v -T tests/ -e cmsis_dsp -x=CONFIG_BOOT_DELAY=500 -T samples/

**Expected behavior**
The samples/drivers/adc should pass, and if it fails, it should display the correct fail log.

**Impact**
As the samples/drivers/adc is fixed by https://github.com/zephyrproject-rtos/zephyr/pull/46854. There will be a potential problem for twister or Jenkins to creat wrong fail log in the daily test report. 

**Logs and console output**
See the "Jenkins auto test result: Github main" of June.14 above.

**Environment (please complete the following information):**
 - OS: (e.g. Linux, MacOS, Windows): Ubuntu 20.04
 - Toolchain (e.g Zephyr SDK, ...): 0.14.1
 - Commit SHA or Version used:  3f8d5c49b3fb54878504f50e87902eab113fc5e2

**Comment by nashif** [comment]
> **Logs and console output**
> See the "Jenkins auto test result: Github main" of June.14

what is that? Please provide all information in the bug report. It is not clear what the results you are getting and what you are expecting and why this is an issue with twister and not with the test/platform itself.

**Comment by hunterhu3000** [comment]
The issue is not reproduced after 6/16. So the issue can be closed. When it happens again, we will submit a new issue. Thanks
