### ISSUE TITLE
drivers: lps25hb driver returning wrong fractional part of a pressure

### ISSUE THREAD

**Issue by karold2412** [zephyrproject-rtos/zephyr#46615]
During my work with lps25hb pressure sensor I have faced problem that fractional part of the measurement is completely wrong. During debug I figured out that we are probably overflowing `int32_t` range during computations in this function:
![lps25hb_problem](https://user-images.githubusercontent.com/84409421/174118806-95ddf518-1736-4d2d-946f-45f3a504f689.png)
Since this sensor is returning 24 bit wide result - when we multiply it million times - it will clearly overflow.

So my local solution for now is:
![suggested_change](https://user-images.githubusercontent.com/84409421/174119248-3025651a-c957-46c4-85f8-695224ed9b38.png)
To give compiler the idea that we need 64 bit value in order to proceed with calculations. As far as I have tested it - it works like a charm.

What do you guys think? Is it a good solution? Should I create a pull request for that?

**Comment by avisconti** [comment]
@karold2412 Sorry, I'm looking now at very old issues. If you still work on zephyr you may create and submit a PR. Otherwise I'll do it. Thanks
