### ISSUE TITLE
stm32: QSPI flash driver have a broken priority configuration

### ISSUE THREAD

**Issue by johnkjellberg** [zephyrproject-rtos/zephyr#46725]
I was looking through the source code of `flash_stm32_qspi.c` and I noticed that `Priority` is set wrong. In line
1106 `hdma.Init.Priority = dma_cfg.channel_priority;`

the value is set base on the `STM32_DMA_CONFIG_PRIORITY` macro. This however creates a value with bits 0 and 1. But the HAL API expects bit matching the MCU registers, i.e shifted up to match the values in `DMA_PRIORITY_LOW` `DMA_PRIORITY_MEDIUM`, `DMA_PRIORITY_HIGH`, `DMA_PRIORITY_VERY_HIGH`.

Zephyr 3.1

**Comment by FRASTM** [comment]
@johnkjellberg  could you please review the PR
