### ISSUE TITLE
L2CAP disconnected packet timing in ecred reconf function

### ISSUE THREAD

**Issue by yajunzhi** [zephyrproject-rtos/zephyr#46822]
**Describe the bug**
When test with PTS, the case is L2CAP/ECFC/BI-03-C.
PTS needs response reconfig first, then send disconnect. But zephyr stack first send disconnect, the timing is incorrect.

`        if (BT_L2CAP_LE_CHAN(chan)->tx.mtu > mtu) {
            BT_ERR("chan %p decreased MTU %u -> %u", chan,
                   BT_L2CAP_LE_CHAN(chan)->tx.mtu, mtu);
            result = BT_L2CAP_RECONF_INVALID_MTU;

            bt_l2cap_chan_disconnect(chan);
            goto response;
        }

response:
    buf = l2cap_create_le_sig_pdu(buf, BT_L2CAP_ECRED_RECONF_RSP, ident,
                                  sizeof(*rsp));

    rsp = net_buf_add(buf, sizeof(*rsp));
    rsp->result = sys_cpu_to_le16(result);

    l2cap_send(conn, BT_L2CAP_CID_LE_SIG, buf);
`

**To Reproduce**
running stack. And test with PTS. The case is L2CAP/ECFC/BI-03-C.

**Expected behavior**
First send BT_L2CAP_ECRED_RECONF_RSP packet, then send disconnect packet.

**Comment by hermabe** [comment]
L2CAP/ECFC/BI-03-C passed in latest weekly PTS run. Looking at the logs, the order of the response and disconnection is as described in the TS.

Which version of zephyr are you on? I cannot see the call to `bt_l2cap_chan_disconnect()` in [the current implementation](https://github.com/zephyrproject-rtos/zephyr/blob/f79eaba7e6d2c698fbaba3f7bc7348f9a78a611d/subsys/bluetooth/host/l2cap.c#L1305).

**Comment by hermabe** [comment]
> I cannot see the call to bt_l2cap_chan_disconnect() in [the current implementation](https://github.com/zephyrproject-rtos/zephyr/blob/f79eaba7e6d2c698fbaba3f7bc7348f9a78a611d/subsys/bluetooth/host/l2cap.c#L1305).


This was changed in https://github.com/zephyrproject-rtos/zephyr/pull/44742. There was a TSE raised to remove the requirement to disconnect from the test as this was not mandated by spec.

**Comment by yajunzhi** [comment]
Got it.
My zephyr version is not the latest. I will sync and verify the case.  
I agree with your comments. The disconnect is not mandatory step for the case verification.
Thanks a lot.
