### ISSUE TITLE
STOP2 Mode on Nucleo-WL55JC1 not accessed

### ISSUE THREAD

**Issue by senseDan** [zephyrproject-rtos/zephyr#46847]
**Describe the bug**
For a power manager test and general test of power consumption I built and flashed the following two applications:
samples/boards/stm32/power_mgmt/blinky
tests/subsys/pm/power_mgmt_soc

I built it using west build -b nucleo_wl55jc and flashed it with west flash. I also debugged it with VS Code and both applications were working fine, but i did not debug any pm stuff, just the applications.

I measured the power consumption of the nucleo board (debugger disconnected) with a multi meter. The consumption was never below 5mA. I also used the STM32 toolchain to verfiy my measurement and i reached around 15uA in stop2 mode.

So I guess these applications should reach the around 15uA of power consumption as well as is discussed in the zephyr discord.

OS: Ubuntu 20.04
Zephyr SDK 0.14.1
Zephyrproject  3.1.99

**Comment by erwango** [comment]
I'm back at this, I'm reproducing an issue, but not exactly with the same difference
Here are the figures I can observe:
- STM32CubeWL/Projects/NUCLEO-WL55JC/Examples_LL/PWR/PWR_EnterStopMode: 450uA
- zephyrproject/zephyr/samples/boards/stm32/power_mgmt/blinky: 1500uA/5000uA (Led OFF/Led ON)

In Zephyr, when changing sysclk to HSI@16MHz (same as Cube sample): 440uA/4200uA (Led OFF/Led ON). So this is not exactly the 15uA that you observe, but that's on par with Cube on my setup.

Can you proceed to the same change on your side and see if this also impacts the figure you get?

For reference, my board (nucleo_wl55jc) configuration for the measurement:
- Anmeter on I_SOC(JP1)
- JP7 OFF
- JP4 OFF
- ST-Link unplugged

**Comment by senseDan** [comment]
I checked both projects with the nucleo board as well and my results are completely different to your results and my results back then. The measurements of my inital post were differently powered, maybe that caused a sideeffect I did not expect

STM32CubeWL/Projects/NUCLEO-WL55JC/Examples_LL/PWR/PWR_EnterStopMode: 1.2uA
To make sure I am measuring the same way you do i made a photo of my setup.

![stm32_pwr](https://user-images.githubusercontent.com/108049583/183045680-38b7080a-d12e-431a-8b86-fa05166c4a2d.JPEG)

zephyrproject/zephyr/samples/boards/stm32/power_mgmt/blinky: 2.1uA/3560uA (Led OFF/Led ON)

Per default the device tree settings of the nucleo_wl55jc set hsi@16MHz as sysclk, so i measured it only with that setting.

LED_OFF:
![zephyr_ledoff](https://user-images.githubusercontent.com/108049583/183049271-73e0ccbb-f5b1-472d-a351-422dd462609f.JPEG)


LED_ON:
![zephyr_ledon](https://user-images.githubusercontent.com/108049583/183045815-481e19fc-332a-49c6-82ae-0f2b971a7811.JPEG)


I like the idea of having a lower consumption in the sleep mode, but it confuses me to have different results and also the gap between zephyr and the bare metal stm32 example.
Can you check the difference between our setups or provide me with a photo of yours?
Is your bare metal stm32 project configured as a single core or as a dual core problem? Or is it good in both ways?

**Comment by erwango** [comment]
> Per default the device tree settings of the nucleo_wl55jc set hsi@16MHz as sysclk, so i measured it only with that setting.

That is not actually the case:
https://github.com/zephyrproject-rtos/zephyr/blob/3ba0cb19ea99a8c85756308432652d762de54f7e/boards/arm/nucleo_wl55jc/nucleo_wl55jc.dts#L108-L110
This should be updated to:
```
 &rcc { 
 	clocks = <&clk_hsi>; 
 	clock-frequency = <DT_FREQ_M(16)>; 
```

Also, 1uA difference is small and may come from pin configuration for instance.
I'd suggest modifying the sample and add:
```
CONFIG_CONSOLE=n
CONFIG_SERIAL=n
```

**Comment by senseDan** [comment]
> That is not actually the case:

Okay, first I was looking at this:
![Screenshot_20220805_131741](https://user-images.githubusercontent.com/108049583/183067442-7b2e4f8d-95a6-4933-b476-a968f8070d99.png)

I updated it and I got 3uA/3500uA (LED_ON/LED_OFF) in the same measurement setup. So more then before. It was at 2.1uA.

> I'd suggest modifying the sample and add:

I tried it with both clock configurations:
48MHz:  1.8uA / 3570uA LED_ON/LED_OFF
16Mhz:   1.8uA / 3570uA LED_ON/LED_OFF no change

It is getting a little bit lower with the flags disabled, but the clock configuration does not seem to matter.

Is my jumper setting fine?

**Comment by erwango** [comment]
> the clock configuration does not seem to matter.

Ok. Using HSI instead of PLL allows to use low power range for VOS.
But indeed that doesn't impact Stop2 consumption since VCore is disabled.
In theory this should have an impact in run mode though, but run mode is extremely brief in this sample.

> I tried it with both clock configurations:
48MHz: 1.8uA / 3570uA LED_ON/LED_OFF
16Mhz: 1.8uA / 3570uA LED_ON/LED_OFF no change

1.8uA with Zephyr compared to 1.2uA using Cube, I guess we won't be able to get below this.
Difference might be due to LSI/LSE being on in Zephyr in order to allow LPTIM to run (used by kernel ticker), which is not available in Cube sample.

Are you fine with these figures then ?

**Comment by senseDan** [comment]
I'm totally fine with it, Thanks!

**Comment by Maroua-ux** [comment]
Hi everyone ,

I'm testing ultra-low power on the NUCLEO-WL55JC using STM32CubeIDE . My goal is to reach ~0.9 µA in Stop 2 mode, but I consistently measure around 2.9 mA, even with the debugger disconnected.

 My setup:
Stop 2 mode enabled

MSI @ 100 kHz, PLL disabled

PVD disabled

All unused GPIOs set to analog

SUBGHZSPI clock disabled

Debug disabled

CPU2 not activated

Tick suspended

Entering Stop 2 with HAL_PWREx_EnterSTOP2Mode()

 Measurement:


JP7 and JP8 removed

Powered via JP1 using STLINK-V3PWR

Measured with STM32CubeMonitor-Power
 Question:
Why is the current still so high? Is there anything specific on the NUCLEO-WL55JC board (RF switch, etc.) that needs to be disabled? Any working CubeIDE example that reaches ~0.9 µA?

**Comment by erwango** [comment]
@Maroua-ux If you're using Cube environment, please raise your question on https://community.st.com/
