### ISSUE TITLE
mtls and tinycrypt crypto drivers not returning number of bytes written to output buffer

### ISSUE THREAD

**Issue by vakulgarg** [zephyrproject-rtos/zephyr#4684]
In structure cipher_pkt, there is an output field 'out_len'. This is supposed to return back to the caller number of bytes written in output buffer. 

The said field is left uninitialized by the crypto apis (e.g. cipher_ccm_op).

**Comment by tbursztyka** [comment]
Up to the crypto driver to do so. But heh, now you mentioned this: both mtls and tc shim drivers do not set it. Only the ataes132c and cc2520 do it properly.

**Comment by vakulgarg** [comment]
Right. Only mtls and tinycrypt shims miss it.

**Comment by MaureenHelm** [comment]
@vakulgarg Is this still an issue?

**Comment by vakulgarg** [comment]
Yes, it should still be an issue. I do not find any updates or fixes in the mtls, tinycrypt shim drivers.

**Comment by MaureenHelm** [comment]
@tbursztyka @lpereira Will you please provide a fix?

**Comment by lpereira** [comment]
@MaureenHelm Just sent a PR fixing this.

I'm not sure how correct this is, but it seems that, at least on the CCM encryption/decryption, both mbedTLS and TinyCrypt agree on how to calculate the output length.

For the other primitives supported by the TinyCrypt shim but not the mbedTLS shim, I believe things are correct after inspecting the respective TinyCrypt code, but I'd expect someone that knows more about this to review.

**Comment by MaureenHelm** [comment]
@lpereira Thank you!
