### ISSUE TITLE
net: RFC: Make the last arg ("data") of net_frag_read() be void* instead of u8_t*

### ISSUE THREAD

**Issue by pfalcon** [zephyrproject-rtos/zephyr#4690]
Oftentimes, net_frag_read() is used to read values directly into integral variables, e.g.

~~~
u16_t mss;
frag = net_frag_read(frag, pos, &pos, sizeof(mss), &mss);
~~~

Usage like that requires constant (and thus excessive) use of casts (`(u8_t *)&mss` in the example above). Why, if we just can make arg to arg void* ? We don't get much more type safety with u8_t*, but definitely get compromised readability (we have code where net_frag_read() is called literally dozen times in row).

**Comment by jukkar** [comment]
net_pkt api changed -> closing
