### ISSUE TITLE
PWM LED Driver for ESP32

### ISSUE THREAD

**Issue by micheljung** [zephyrproject-rtos/zephyr#4699]
I'd like to use PWM with the ESP32, but (with my limited knowledge) I understand that there is no such driver yet? I expected it to be listed in #3471 but for some reason, it's not.

If I got it right and it's missing, I'm willing to pay [a $100.- Bounty](https://www.bountysource.com/issues/51086816-pwm-driver-for-esp32) for it.

**Comment by lpereira** [comment]
What PWM controller are you talking about? There are two: LED control PWM and motor control PWM.

**Comment by micheljung** [comment]
See, I didn't even know there's a difference ;) LED.

**Comment by iha** [comment]
Hi @micheljung , I have started to study the ESP32 PWM in the datasheet and will keep you informed as soon as I have any progress.

**Comment by iha** [comment]
@micheljung I made some tests and probably I'll send the PR until next Wednesday:

https://twitter.com/vitoriha/status/941654878862168064

**Comment by lpereira** [comment]
Closing as merged.
