### ISSUE TITLE
Intel CAVS: tests/subsys/logging/log_switch_format/ are skipped as no result captured

### ISSUE THREAD

**Issue by LixinGuoX** [zephyrproject-rtos/zephyr#47077]
**Describe the bug**
`tests/subsys/logging/log_switch_format/` is written in ztest but it also uses console harness in yaml file. This will be misleading for twister, twister can not get the status of each test case, and then mark them as `Skipped: No results captured, testsuite misconfiguration?`.
We should find a way to avoid this. Tests should be reported correctly.

**To Reproduce**
1. twister -W --hardware-map ~/cavs/cavs.map --device-testing -v -T tests/lib/subsys/logging/log_switch_format/ -vv -x=CONFIG_BOOT_DELAY=500

**Expected behavior**
Test should pass.

**Comment by aasthagr** [comment]
@LixinGuoX I noticed this issue earlier and a PR is already in place for this . [#46959](https://github.com/zephyrproject-rtos/zephyr/pull/46959). Tagged you as a reviewer. Feel free to provide your reviews. Thanks!!
