### ISSUE TITLE
ZTEST Docs Page

### ISSUE THREAD

**Issue by teburd** [zephyrproject-rtos/zephyr#47072]
The Test Framework documents mix new and old APIs which is a bit confusing, it would be great to have a page that shows how to do things with samples and such with the new API, keeping the old docs as Legacy or something

https://docs.zephyrproject.org/latest/develop/test/ztest.html?highlight=tests

**Comment by aaronemassey** [comment]
@yperess Feel free to assign to me unless you think you can get this done by end of next week.

**Comment by nashif** [comment]
this is completed, closing.
