### ISSUE TITLE
driver: nrf: uarte: new dirver breaks our implementation for uart. 

### ISSUE THREAD

**Issue by ghost** [zephyrproject-rtos/zephyr#47092]
**Describe the bug**
We have updated to a newer NCS version. During this process also the zephyr version has changed. This caused our UART implementation to fail. I'm pretty sure it is related to this commit `ba6d9139bbbda3211e0c1f65f4ccca0719f17fa5`. 

Relevant implementation snippet:
```
K_MSGQ_DEFINE(s_rcvd_msgq,
				sizeof(size_t),
				2,
				alignof(size_t));

K_MSGQ_DEFINE(s_snt_msgq,
				sizeof(size_t),
				2,
				alignof(size_t));

static void uart_callback(const struct device *dev,
							struct uart_event *evt,
							void *user_data)
{
	const bool workaround = true;
	switch (evt->type) 
	{
		case UART_TX_DONE:
			k_msgq_put(&s_snt_msgq, &(evt->data.tx.len), K_NO_WAIT);
			break;
		case UART_TX_ABORTED: break;
		case UART_RX_RDY:
			k_msgq_put(&s_rcvd_msgq, &(evt->data.rx.len), K_NO_WAIT);
			break;
		case UART_RX_BUF_REQUEST:
		{
				if(workaround)
				{
					static uint8_t dummy = 0;
					uart_rx_buf_rsp(dev, &dummy, sizeof(dummy));
				}
				break;
		}
		case UART_RX_BUF_RELEASED: break;
		case UART_RX_DISABLED: break;
		case UART_RX_STOPPED: break;
	}
}

int impl_rx(const struct device *dev, uint8_t* buf, size_t size, int32_t timeout_ms)
{
	int ret = -1;
	size_t rcvd = 0;

	// make sure queue is empty
	while (0 == k_msgq_get(&s_rcvd_msgq, (void*)&rcvd, K_NO_WAIT)){};

	(void)pm_device_action_run(dev, PM_DEVICE_ACTION_RESUME);
	if (0 == uart_rx_enable(dev, buf, size, SYS_FOREVER_US))
	{
		if (0 == k_msgq_get(&s_rcvd_msgq, (void*)&rcvd, K_MSEC(timeout_ms)))
		{
			ret = rcvd;
		}
		else
		{
			ret = CAP_ERR_TIMEOUT;
		}

		// disable rx so that the device can be put back to PM_DEVICE_ACTION_SUSPEND
		(void)uart_rx_disable(dev);

		(void)pm_device_action_run(dev, PM_DEVICE_ACTION_SUSPEND);
		return ret;
	}
	return -1;
}
```

The relevant UART KConfig values:

```
CONFIG_UART_ASYNC_API=y
CONFIG_UART_1_ASYNC=y
CONFIG_UART_1_INTERRUPT_DRIVEN=n
```

So we try to use the async UART API to implement a synchronous UART API. The problem is now that after we have received the data and have called `uart_rx_disable` this function actually fails (https://github.com/zephyrproject-rtos/zephyr/blob/main/drivers/serial/uart_nrfx_uarte.c#L1006) because the https://github.com/zephyrproject-rtos/zephyr/blob/main/drivers/serial/uart_nrfx_uarte.c#L1201 was called and made the buffer NULL. This then prevents the `uart_rx_disable` function to set https://github.com/zephyrproject-rtos/zephyr/blob/main/drivers/serial/uart_nrfx_uarte.c#L1015 and because of that `pm_device_action_run` runs into the assert https://github.com/zephyrproject-rtos/zephyr/blob/main/drivers/serial/uart_nrfx_uarte.c#L1961.

This was not the case for the earlier version of the driver implementation. I'm not sure if it is really appropriate to make the buffer just NULL or rather that it is not possible to put the driver now in the suspend mode unless you give it another buffer. In my snipped I also added our current workaround in the callback. 

**Expected behavior**

**Impact**
An assert is trigged which causes the device to reboot.

**Environment (please complete the following information):**
 - OS: `MacOS`
 - Toolchain `nRF Connect SDK`
 - Commit SHA `ba6d9139bbbda3211e0c1f65f4ccca0719f17fa5`

**Comment by dcpleung** [comment]
@nordic-krch Do you think you can get this fixed for v3.2? If not, please mark it as `future` in milestone. Thanks.
