### ISSUE TITLE
shell uart: busy wait for DTR in ISR

### ISSUE THREAD

**Issue by aurel32** [zephyrproject-rtos/zephyr#47120]
**Describe the bug**
With `CONFIG_SHELL_BACKEND_SERIAL_CHECK_DTR=y`, the shell uart backend waits for DTR before sending data to the UART. However it does so in the ISR via `uart_callback()` -> `uart_tx_handle()` -> `uart_dtr_wait()`

The consequences are very different depending on how the UART driver is implemented. In my case I use this USB CDC ACM UART, so it only blocks the whole USB workqueue, and thus the whole USB stack.

**To Reproduce**
- Take a USB sample
- Set `CONFIG_USB_COMPOSITE_DEVICE=y`
- Enable the shell on the USB CDC ACM UART
- The other USB device interfaces are unresponsive until a connection is make to the CDC ACM interface.

**Expected behavior**
Using a shell on USB CDC ACM UART should not impact the other interfaces of a composite USB device.

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: zephyr-sdk-0.14.2
 - Commit SHA: 74afc2df0667532315d01430dd9d4631e0c350fa

**Comment by mmahadevan108** [comment]
@aurel32 does the suggestion from @jfischer-no work for you? If so kindly close this issue.

**Comment by jakub-uC** [comment]
@aurel32 please let me know if this is still an issue or if we can close it.

**Comment by jfischer-no** [comment]
> @aurel32 please let me know if this is still an issue or if we can close it.

It is still an issue. Maybe we can not init/enable uart backend per default if CDC ACM UART is used and enable/uninit it on DTR state change?
