### ISSUE TITLE
SPI: Update drivers to drop support of the legacy API 

### ISSUE THREAD

**Issue by tbursztyka** [zephyrproject-rtos/zephyr#4713]
- [x] mcux driver
- [x] nrf driver  (note: all drivers starts with spi_ prefix, there is _no_ spis_ spim_: instead it should be spi_nrf5_master.c, spi_nrf5_slave.c for instance)
- [x] intel driver (question: do we still support Galileo board? if not, this driver could be removed.)
- [x] qmsi driver
- [x] qmsi ss driver

**Comment by tbursztyka** [comment]
Being addressed by #5921

**Comment by galak** [comment]
@tbursztyka can we close this?

**Comment by tbursztyka** [comment]
Definitely! Legacy API is dead and buried now.
