### ISSUE TITLE
CAN filter with RTR mask causes infinite loop in MCAN driver on filtered message arrival

### ISSUE THREAD

**Issue by dragonlock2** [zephyrproject-rtos/zephyr#47204]
**Describe the bug**
Using a CAN filter with the RTR mask set causes the MCAN driver to hang in `can_mcan_get_message` when a message that would be filtered arrives.

Tested on STM32G0B1KET6N but it should happen on any platform using the MCAN driver.

The issue is on [line 661](https://github.com/zephyrproject-rtos/zephyr/blob/main/drivers/can/can_mcan.c#L661) where the incoming message never gets ACK'd since the RTR doesn't match. A super simple workaround is to just add `*fifo_ack_reg = get_idx;` but I'm guessing that isn't a proper fix?

**To Reproduce**
Here's a minimal application that demonstrates the issue. "done!" never gets printed unless I apply the workaround.
```C
#include <zephyr/zephyr.h>
#include <zephyr/drivers/can.h>
#include <zephyr/device.h>

const struct zcan_filter filter = {
    .id_type  = CAN_STANDARD_IDENTIFIER,
    .id_mask  = 0,
    .rtr      = CAN_DATAFRAME,
    .rtr_mask = 1,
};
CAN_MSGQ_DEFINE(msgq, 8);
const struct device *dev = DEVICE_DT_GET(DT_NODELABEL(can1));

void main(void) {
    can_set_mode(dev, CAN_MODE_LOOPBACK);
    can_add_rx_filter_msgq(dev, &msgq, &filter);
    struct zcan_frame txmsg = {
        .id_type = CAN_STANDARD_IDENTIFIER,
        .rtr = CAN_REMOTEREQUEST,
        .dlc = 0,
    };
    can_send(dev, &txmsg, K_FOREVER, NULL, NULL);
    printk("done!\r\n");
}
```

**Expected behavior**
It prints "done!".

**Impact**
Just a minor annoyance, very low priority.

**Logs and console output**
Verified in GDB that it's hanging in this function.
<img width="724" alt="Screen Shot 2022-07-03 at 4 29 18 AM" src="https://user-images.githubusercontent.com/43054648/177037520-dba57465-953e-4fe7-976c-ce8bc1826644.png">

**Environment**
 - OS: MacOS
 - GNU Toolchain for the Arm Architecture 11.2-2022.02 (arm-11.14)
 - v3.1.0

**Additional context**

**Comment by henrikbrixandersen** [comment]
Thank you. I can confirm the issue. I am looking into providing a fix.
