### ISSUE TITLE
Twister: Skipping *.cpp files

### ISSUE THREAD

**Issue by jwhite-enphase** [zephyrproject-rtos/zephyr#47220]
**Describe the bug**
When a test is written in a *.cpp file Twister does not scan it for tests if it is in the same directory as the testcase.yaml file. If the cpp file is moved into a /src/ sub-directory then it works as expected. E.g. if the directory layout is:
```
- test:
    - CMakeLists.txt
    - main.cpp
    - testcase.yaml
```
Then main.cpp will not get scanned but if the layout is:
```
- test:
    - src 
        - main.cpp 
    - CMakeLists.txt
    - testcase.yaml
```
Then it will get scanned.

**To Reproduce**
Create a test layout as above.

**Expected behavior**
I would expect the behavior to be the same when the main.cpp file is in a /src/ sub-directory and when it is not.

**Impact**
Minor annoyance, creates a skipped test in the test report, the tests in the cpp file are still run and are reported.

**Environment:**
 - OS: Linux
 - Toolchain: Zephyr SDK v0.14.2
 - Commit SHA: 2ddd73feafd3316af2c547c34d6969bea637d5c6

**Additional context**
I think it is because this line: https://github.com/zephyrproject-rtos/zephyr/blob/db3f8c16e9c95801961a433c07f481bfcb385466/scripts/pylib/twister/twisterlib.py#L2021 has `*.c*` whereas this line: https://github.com/zephyrproject-rtos/zephyr/blob/db3f8c16e9c95801961a433c07f481bfcb385466/scripts/pylib/twister/twisterlib.py#L2042 only has `*.c`

**Comment by nashif** [comment]
can you submit a PR fixing this please?
