### ISSUE TITLE
zephyr doc: Unable to open pdf document version 3.1.0

### ISSUE THREAD

**Issue by hongshui3000** [zephyrproject-rtos/zephyr#47222]
**Describe the bug**
https://docs.zephyrproject.org/3.1.0-0/zephyr.pdf   can't open

![image](https://user-images.githubusercontent.com/25566498/177071443-76cbdf3d-a8ee-41a2-9ea4-c380a00b70c7.png)

**Comment by gmarull** [comment]
3.1.0 docs were built before this fix https://github.com/zephyrproject-rtos/zephyr/commit/90537fe447d66e627b62efaa26f28d7a18926adc, they should probably be re-built and uploaded.
