### ISSUE TITLE
Please add STM32F412RX

### ISSUE THREAD

**Issue by kiryl90** [zephyrproject-rtos/zephyr#47232]
**Is this request related to a missing driver support for a particular hardware platform, SoC or board? Please describe.**
I use the STM32F412RE controller on my board, but it is not supported at this point. 

**Describe why you are asking for this support?**
This is also an often used mcu with 64pins from the F412 series.

**Additional context**
I tried also the solution from the Issue [#38966](https://github.com/zephyrproject-rtos/zephyr/issues/38966), but my MCU is not starting on the right adress on flash.

**Comment by FRASTM** [comment]
STM32F412RE 
  64 pins  
  512Kbytes of Flash memory
  256Kbytes of RAM
  97 irq lines
