### ISSUE TITLE
nrf51_ble400: onboard chip should be updated to nRF51822_QFAC in dts

### ISSUE THREAD

**Issue by yang325** [zephyrproject-rtos/zephyr#47272]
**Describe the bug**
Waveshare BLE400 core board has upgraded the onboard chip to Rev3, i.e. nRF51822_QFAC. While nrf51822_qfaa is still used in nrf51_ble400.dts.

**Expected behavior**
Update the dts and other files.

**Comment by carlescufi** [comment]
@yang325 would you like to send a Pull Request for this?

**Comment by yang325** [comment]
Sure, will do it soon.
