### ISSUE TITLE
LE Audio: Move board files for nRF5340 Audio development kit upstream

### ISSUE THREAD

**Issue by asbjornsabo** [zephyrproject-rtos/zephyr#47296]
We want to, and have been given approval to, copy the board files for the Nordic Semiconductor nRF5340 LE Audio development kit to Zephyr upstream, so that the board can more easily be used in that code base.

Remaining question to be resolved: Board files only, or also drivers?

**Comment by koffes** [comment]
As linked, this will be resolved by #49720.
The SD card is accessible using standard upstream drivers.
Using the Jack/analog input is dependent on third party drivers with dependencies. There is no plan to upstream these at present time, so we encourage users to go to https://github.com/nrfconnect/sdk-nrf for full support.

The binary controller will be in the NCS repo, yes.
