### ISSUE TITLE
Module request: Lua

### ISSUE THREAD

**Issue by oscarbaselga** [zephyrproject-rtos/zephyr#47301]
## Origin

Lua - [https://github.com/lua/lua](https://github.com/lua/lua)

## Purpose

Lua is a scripting language that can be integrated into embedded systems thanks to its lightweight. It is perfect for complex applications where a two-parts separated implementation is needed: firmware and services.

Lua provides a C API that allows a bidirectional C-Lua interaction.

## Mode of integration

I would like to integrate Lua as an external module in order to give users the posibility to include Lua in their applications whenever they want. I suggest making an integration of Lua as a library rather than as an interpreter, so an appropriate name is `liblua` and could be located in `modules/lib/`.

The goal is to add the Lua repository in the west manifest and define a configuration option which enable the module in the user application.

## Maintainership

I present myself as a single maintainer (@oscarbaselga).

## Pull Request

TBD

## Description

As previously mentioned, Lua is a lighweight scripting language that can be integrated in embedded systems. A scripting language will allow users to implement their own services over their firmwares and manage their applications from a higher level view.

Currently, Lua is not supported in Zephyr applications, so users would need to include all its source files to use it, something that also implies to re-write the building process of their projects.

Lua is a proper solution due to its lightweight and license, as the repository is under an OSI-compliant license.

However, there is a support problem with stubs. There are three functions in newlib that are not implemented: `_times()`, `_unlink()` and `_link()`. All of them are necessary to build Lua, so I decided to declare them in an auxiliary C file and throw a warning if they are called. I consider this problem out of the module flow, so my solution is a temporary approach while waiting for a newlib update.

## Dependencies

Lua module depends on file system and newlib components, which are enabled with `CONFIG_FILE_SYSTEM` and `CONFIG_NEWLIB_LIBC` respectively. Moreover, the main stack size must be set at 4096 (`CONFIG_MAIN_STACK_SIZE=4096`).

## Revision

Lua v5.4.4

## License

MIT License - [http://www.lua.org/license.html](http://www.lua.org/license.html)

**Comment by nashif** [comment]
related #45485
