### ISSUE TITLE
Bluetooth: LE Audio: Move discover_params and read_params into MCS instance struct

### ISSUE THREAD

**Issue by asbjornsabo** [zephyrproject-rtos/zephyr#47335]
File mcc.c: Move discover_params and read_params to the struct mcs_instance_t

Beware that the cur_mcs_inst is not assigned until an MCS service is found, which creates a chicken and egg problem: The discovery parameters (within the struct) can not be used until the service has been discovered.

**Comment by fredrikdanebjer** [comment]
This issue has already been solved.
