### ISSUE TITLE
ble-mesh: proxy.c : Is clients-> conn a clerical error? it should be client-> conn?

### ISSUE THREAD

**Issue by wayen30** [zephyrproject-rtos/zephyr#4738]
In function bt_mesh_proxy_prov_disable  & bt_mesh_proxy_gatt_disable
		if (clients->conn && client->filter_type == PROV) {
Is clients-> conn a clerical error? it should be client-> conn?

**Comment by jhedberg** [comment]
That's a good catch. Will send a fix PR in a moment.
