### ISSUE TITLE
USB OTG FS controller support on STM32F413 broken

### ISSUE THREAD

**Issue by jfischer-no** [zephyrproject-rtos/zephyr#47445]
**Describe the bug**
USB OTG FS controller support on STM32F413 broken because of latest changes on clock configuration.
git bisect: first bad commit: [c959b58bf15659628d2b64b1b38f5a89348d4db4]
drivers/clock_control: stm32 common: enable PLL_P/Q and set PLL_P div
Introduced by PR #47102

**To Reproduce**
build & flash any USB device support sample for nucleo_f413zh board.

My workaround:
```diff
diff --git a/drivers/clock_control/clock_stm32_ll_common.c b/drivers/clock_control/clock_stm32_ll_common.c
index b7e778e89e7..37916dcbd80 100644
--- a/drivers/clock_control/clock_stm32_ll_common.c
+++ b/drivers/clock_control/clock_stm32_ll_common.c
@@ -474,6 +474,10 @@ static void set_up_plls(void)
        RCC_PLLQ_ENABLE();
 #endif
 
+#if STM32_PLL_Q_ENABLED
+       MODIFY_REG(RCC->PLLCFGR, RCC_PLLCFGR_PLLQ, pllq(STM32_PLL_Q_DIVISOR));
+#endif
+
        config_pll_sysclock();
 
        /* Enable PLL */
```

**Comment by erwango** [comment]
I think that I get it.
The guilty code should actually be the last version
```
#if defined(STM32_SRC_PLL_Q) & STM32_PLL_Q_ENABLED
	MODIFY_REG(RCC->PLLCFGR, RCC_PLLCFGR_PLLQ, pllq(STM32_PLL_Q_DIVISOR));
	RCC_PLLQ_ENABLE();
#endif
```
And `STM32_SRC_PLL_Q` is not defined on F4 devices.
We might need to define all PLL outputs for SoC that don't support them today (F4/F7).

**Comment by str4t0m** [comment]
@erwango Has someone from st time to add the clock source defines and add alternate clock source support for the affected series?
I won't be able to do so this week(and also don't have access to a board of these series), but if not I could send a PR that just fixes the condition in the meantime.

**Comment by erwango** [comment]
> I won't be able to do so this week(and also don't have access to a board of these series), but if not I could send a PR that just fixes the condition in the meantime.

@FRASTM will have a look

**Comment by str4t0m** [comment]
Thanks!
