### ISSUE TITLE
twister: cmake: Failure of "--build-only -M" combined with "--test-only" for --device-testing

### ISSUE THREAD

**Issue by PerMac** [zephyrproject-rtos/zephyr#47500]
**Describe the bug**
A combination of running --build-only with minimal set of artifacts required (-M), and then --test-only fails for --device-testing.
**To Reproduce**
1. run `./scripts/twister -T samples/philosophers/ -p nrf52840dk_nrf52840 --device-testing --device-serial /dev/ttyACM0 --build-only -M`
2. run `./scripts/twister -T samples/philosophers/ -p nrf52840dk_nrf52840 --device-testing --device-serial /dev/ttyACM0 --test-only`
3. See error

**Expected behavior**
Building the minimal set of artifact and then only testing them should work without errors.
**Impact**
annoyance

**Logs and console output**
```
CMake Error: The current CMakeCache.txt directory /home/maciej/zephyrproject/zephyr/twister-out/nrf52840dk_nrf52840/samples/philosophers/sample.kernel.philosopher.coop_only/CMakeCache.txt is different than the directory twister-out/nrf52840dk_nrf52840/samples/philosophers/sample.kernel.philosopher.coop_only where CMakeCache.txt was created. This may result in binaries being created in the wrong place. If you are not sure, reedit the CMakeCache.txt
CMake Error: The source "/home/maciej/zephyrproject/zephyr/samples/philosophers/CMakeLists.txt" does not match the source "samples/philosophers/CMakeLists.txt" used to generate cache.  Re-run cmake with a different source directory.
ninja: error: rebuilding 'build.ninja': subcommand failed
```

**Environment (please complete the following information):**
 - OS: ubuntu 18.04
 - Toolchain zephyr-sdk 0.14.2
 - Commit SHA or Version used zephyr-v3.1.0-1610-gccf9292a52b6

**Additional context**
It looks like some mismatch between the way how path are stored in cmake cache and current directory (whole prefix is missing/added `/home/maciej/zephyrproject/zephyr/`).

I also find a bit unfortunate the combination of params required for build-only for devices with minimum artifacts. i.e. that a user has to  use --device-testing flag (which is fine by itself) and this flag has to be combined (due to arg parser requirements) with either --hardware-map or --device-serial flags. This makes no sense on build agents without hardware connected, which are also unaware about the hw setup on test nodes

**Comment by nashif** [comment]
cant reproduce with a different board, are you moving files around or are you running both commands in place?

**Comment by PerMac** [comment]
I tried it with other boards (reel_board and frdm_k64f) and it seems unrelated to a platform chosen. I got the same error since it fails before getting to the part where platform matters. I run in the same env/dir, i.e. I just run `--build-only -M` and `--test-only` just one after the other in the same dir. When I ran --build-only without cleaning the artifacts (no -M arg) it works

**Comment by PerMac** [comment]
I played just a bit and it seems that if I copy the list of allow leftover files from https://github.com/zephyrproject-rtos/zephyr/blob/main/scripts/pylib/twister/twisterlib/runner.py#L516 into the device-testing leftovers here https://github.com/zephyrproject-rtos/zephyr/blob/main/scripts/pylib/twister/twisterlib/runner.py#L549 the workflow starts to work. I will try to pin point down which files make the difference

**Comment by PerMac** [comment]
It works with your command, but not with the one I reported ;) The difference is that you used it with hw map. From a quick check:
- One can only succeed if using --build-only with provided hw map and then --test-only also with the map.
- when using --device-serial instead of a hw map twister will fail with the error I reported
- I see your  fix, that untangled the need for --device-testing to get the test artifacts with -M ( --prep-artifacts-for-testing) which is nice. 

With the current version the runners.yaml file has to be available during the --test-only stage and this file is generated when --build-only is called with the hw map. In other scenarios one will get `FATAL ERROR: either a pristine build is needed, or board nrf52840dk_nrf52840 doesn't support west flash/debug (no ZEPHYR_RUNNERS_YAML in CMake cache)`

Running twister with the new arg works (e.g like `./scripts/twister -s "samples/philosophers/sample.kernel.philosopher" -p nrf52840dk_nrf52840 --prep-artifacts-for-testing -M`).

I am not sure do we need the split workflow with minimal artifacts to work with --device-serial. I guess it is to be decided. It also seems to me that `runners.yaml` might be build environment dependent. I see references to local tools there:
```
  gdb: /home/maciej/zephyr-sdk-0.14.2/arm-zephyr-eabi/bin/arm-zephyr-eabi-gdb-no-py
  openocd: /home/maciej/zephyr-sdk-0.14.2/sysroots/x86_64-pokysdk-linux/usr/bin/openocd
  openocd_search:
    - /home/maciej/zephyr-sdk-0.14.2/sysroots/x86_64-pokysdk-linux/usr/share/openocd/scripts
```

I guess if we want to be able to build on one agent and then ship artifacts to other agent with hw farm we would need to create aligned runner.yaml 

We also made a quick check with @gopiotr. We built tests independently on on PC with
`./scripts/twister -s "samples/philosophers/sample.kernel.philosopher" -p nrf52840dk_nrf52840 --prep-artifacts-for-testing -M`
and sent twister-out to another one and run:
`./scripts/twister -s "samples/philosophers/sample.kernel.philosopher" -p nrf52840dk_nrf52840 --device-testing --hardware-map hwmap.yml --test-only -M -v -v`
The test passed (but our boards doesn't use openocd).
@hakehuang I think this workflow might be what you were looking for (building on one agent and executing on another). Only the minimal amount of artifacts is left. Maybe you'd like to give it a try?

**Comment by nashif** [comment]
> Running twister with the new arg works (e.g like `./scripts/twister -s "samples/philosophers/sample.kernel.philosopher" -p nrf52840dk_nrf52840 --prep-artifacts-for-testing -M`).

lowering priority due to the above.

**Comment by hakehuang** [comment]
> @hakehuang I think this workflow might be what you were looking for (building on one agent and executing on another). Only the minimal amount of artifacts is left. Maybe you'd like to give it a try?

this works for me.  the one thing we want is that do we need send the whole twister-out folder? say if we have several same boards on different machine, and how we split them?

**Comment by PerMac** [comment]
For now my only idea is to manage this on the "CI-level" i.e. in Jenkins or other orchestrator you use. I would play with building in subsets and sending each subset as a whole to different agents. So each subset has its own test plan etc. Making twister able of distributing tests over the net based on available resources is quite challenging and I am still not sure if this should be a twister feature.
