### ISSUE TITLE
up_squared: issues of EFI console feature

### ISSUE THREAD

**Issue by enjiamai** [zephyrproject-rtos/zephyr#47512]
**Describe the bug**
There is an issue that https://github.com/zephyrproject-rtos/zephyr/issues/45929, fixed by https://github.com/zephyrproject-rtos/zephyr/pull/46918.

- But there are still a few known tests failed after applied this solution, these are:

tests/kernel/mutex/sys_mutex/  -s tests/kernel/mutex/sys_mutex/system.mutex
tests/lib/sprintf/libraries.libc.sprintf
tests/subsys/logging/log_immediate/logging.log_immediate.clean_output
tests/subsys/logging/log_immediate/logging.log_immediate 

- And some tests failed due to apply this change:

tests/kernel/mem_protect/mem_protect/kernel.memory_protection
tests/subsys/rtio/rtio_api/subsys.rtio.api
tests/subsys/rtio/rtio_api/subsys.rtio.api.submit_sem
sample/portability/sample.portability/cmsis_rtos_v1.timer_synchronization
sample/portability/sample.portability/cmsis_rtos_v2.timer_synchronization
samples/userspace/shared_mem/sample.kernel.memory_protection.shared_mem

Need to keep fixing these tests.

**To Reproduce**
1. source zephyr-env.sh
2. twister -p up_squared --device-testing --device-serial /dev/ttyUP2 --west-flash=./up_squared_efi.sh -v -T tests/ -s {testcase}
3. See error

**Expected behavior**

**Impact**
Not serious but need to fix as soon.

**Logs and console output**
Most of them hang up during test execution.

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain Zephyr SDK 0.14.2
 - Commit SHA or Version used: 05147693ca0898f592fa8dfd1eaf09b91e8fb70d

**Comment by enjiamai** [comment]
Now we are working on two ways: (a) apply Zephyr workaround from OS layer (b) report to UEFI BIOS team a bug.

**Comment by enjiamai** [comment]
For these failed tests:
tests/kernel/mem_protect/mem_protect/kernel.memory_protection
tests/subsys/rtio/rtio_api/subsys.rtio.api
tests/subsys/rtio/rtio_api/subsys.rtio.api.submit_sem
sample/portability/sample.portability/cmsis_rtos_v1.timer_synchronization
sample/portability/sample.portability/cmsis_rtos_v2.timer_synchronization
samples/userspace/shared_mem/sample.kernel.memory_protection.shared_mem

They all passed when CONFIG_PRINTK_SYNC=n, it is likely to be under condition it will hang up due to 2 spinlocks using here. (because the CONFIG_PRINTK_SYNC means add spinlock to sync output from different cores. Keep getting more debug information on it.

**Comment by enjiamai** [comment]
After reporting this bug to UEFI BIOS team, I got some response for this:
1. When we boot Zephyr as an EFI application, the ExitBootService() should be called before EFI handover all the control to OS. After invoking the ExitBootService(), the EFI context will be cleaned. Otherwise the EFI timer interrupt might be triggered during Zephyr running. But after invoking ExitBootService() also means the EFI console cannot be used in a way of function call.

2. So they don't suggest we use it this way after OS fully take over the hardware. EFI console is very useful and mostly used for debugging in the silicon enabling phase, or when the UART console is not enabled yet. as @andyross mentioned before.

Hence, for this EFI console feature, a proposal of solving might be:
(1) We enable the UART console output (That means set CONFIG_UART_CONSOLE=y even EFI console is using, and the ExitBootService() should be called at some point.
(2) We need to write some dedicate tests for EFI console, because we will not use EFI console for testing by default. 

Also change the Bug title.

**Comment by andyross** [comment]
FWIW: we clear the timer hardware at OS start, and are always running our own IDT anyway that will detect and report any spurious interrupts.  That's not much of a problem in practice.  Also FWIW: I'm not really the expert, but my understanding is that Linux also doesn't call ExitBootService, precisely because it wants to preserve the EFI library state for use at runtime just like we do.

Frankly I think the firmware folks are making excuses here.  There are very few good reasons for a call to unconditionally enable interrupts -- surely they want their own locking layers to work, no?

**Comment by enjiamai** [comment]
> FWIW: we clear the timer hardware at OS start, and are always running our own IDT anyway that will detect and report any spurious interrupts. That's not much of a problem in practice. Also FWIW: I'm not really the expert, but my understanding is that Linux also doesn't call ExitBootService, precisely because it wants to preserve the EFI library state for use at runtime just like we do.

Thanks for providing this idea, @andyross , so it seems like we already disabled the timer interrupt of the EFI context but it would still be enabled in the EFI context. And you mentioned Linux also not call ExitBootService (they told me this usually call by grub). I saw this part of code in Linux kernel and it also mentioned things of the firmware bug.

> Frankly I think the firmware folks are making excuses here. There are very few good reasons for a call to unconditionally enable interrupts -- surely they want their own locking layers to work, no?

Totally agree with you. I would like to keep asking them if there is any way to prevent this.
