### ISSUE TITLE
Support for sub-ghz channels in at86rf2xx radio driver 

### ISSUE THREAD

**Issue by maxmclau** [zephyrproject-rtos/zephyr#47520]
Currently the at86rf2xx radio driver does not support sub-ghz channels (e.g. 868 Mhz or 915Mhz). Microchip's [AT86RF215](https://www.microchip.com/en-us/product/AT86RF215) and [AT86RF212B](https://www.microchip.com/en-us/product/AT86RF212B) are capable of sub-ghz channels and would be a nice addition for long-range low power comms.

As it is the driver likely is not far off from supporting these chips - perhaps [RIOT's implementation](
https://github.com/RIOT-OS/RIOT/blob/master/drivers/include/at86rf2xx.h) that supports all at86rf2xx devices could be used for reference.

@nandojve any advice on what would be required to support these other chips?

**Comment by nandojve** [comment]
Hi @maxmclau ,

AT86RF212[B] can be integrated into current rf2xx driver. The rf215 is almost certainly that will require a new driver implementation. Currently Zephyr L2 assumes IEEE-802.15.4-2003 version only, which can use channels from 0-26 at page one.
If you require page 2, to select O-QPSK modulation, it will be necessary a discussion with network group to add `set_page` API in the driver.
