### ISSUE TITLE
kw41z-frdm: assertion failure while setting IRQ priority

### ISSUE THREAD

**Issue by vakulgarg** [zephyrproject-rtos/zephyr#4757]
While running any networking demo e.g. in zephyr/samples/net/sockets/echo/, we get an assertion failure if we define CONFIG_ASSERT=y in project configuration.

The assert in the  function _irq_priority_set() is failing.
On disabling CONFIG_ASSERT, the application can start.

**Comment by galak** [comment]
Fixed by PR #4473 4473
