### ISSUE TITLE
stm32f4_disco and frdm_k64f  samples/basic/blink_led ,Choose supported PWM driver

### ISSUE THREAD

**Issue by spring-z** [zephyrproject-rtos/zephyr#4760]
```
/Volumes/Embedded/Zephyr/zephyr/samples/basic/blink_led/src/main.c:33:2: error: #error "Choose supported PWM driver"
 #error "Choose supported PWM driver"
  ^
/Volumes/Embedded/Zephyr/zephyr/samples/basic/blink_led/src/main.c: In function 'main':
/Volumes/Embedded/Zephyr/zephyr/samples/basic/blink_led/src/main.c:50:31: error: 'PWM_DRIVER' undeclared (first use in this function)
  pwm_dev = device_get_binding(PWM_DRIVER);
                               ^
/Volumes/Embedded/Zephyr/zephyr/samples/basic/blink_led/src/main.c:50:31: note: each undeclared identifier is reported only once for each function it appears in
/Volumes/Embedded/Zephyr/zephyr/samples/basic/blink_led/src/main.c:57:33: error: 'PWM_CHANNEL' undeclared (first use in this function)
   if (pwm_pin_set_usec(pwm_dev, PWM_CHANNEL,
                                 ^
make[3]: *** [src/main.o] Error 1
make[2]: *** [zephyr-app-dir] Error 2
make[1]: *** [sub-make] Error 2
make: *** [all] Error 2

```

**Comment by spring-z** [comment]
@galak

**Comment by galak** [comment]
@spring-z can you try and explain what issue are you running into?

**Comment by spring-z** [comment]
I try run samples to stm32f4_disco

**Comment by galak** [comment]
What are you specific build steps?

**Comment by spring-z** [comment]
➜  make BOARD=stm32f4_disco
Using /Volumes/Embedded/Zephyr/zephyr/boards/arm/stm32f4_disco/stm32f4_disco_defconfig as base
Merging prj.conf
#
# configuration written to .config
#
  GEN     ./Makefile
scripts/kconfig/conf --silentoldconfig Kconfig
  DTC     dts/arm/stm32f4_disco.dts_compiled
dts/arm/stm32f4_disco.dts_compiled: Warning (unit_address_vs_reg): Node /soc/pin-controller has a reg or ranges property, but no unit name
dts/arm/stm32f4_disco.dts_compiled: Warning (unit_address_vs_reg): Node /soc/pin-controller/usart3@0 has a unit name, but no reg property
dts/arm/stm32f4_disco.dts_compiled: Warning (unit_address_vs_reg): Node /soc/pin-controller/usart3@1 has a unit name, but no reg property
dts/arm/stm32f4_disco.dts_compiled: Warning (unit_address_vs_reg): Node /soc/pin-controller/usart6@0 has a unit name, but no reg property
dts/arm/stm32f4_disco.dts_compiled: Warning (unit_address_vs_reg): Node /soc/pin-controller/usart6@1 has a unit name, but no reg property
dts/arm/stm32f4_disco.dts_compiled: Warning (unit_address_vs_reg): Node /soc/pin-controller/usart1@0 has a unit name, but no reg property
dts/arm/stm32f4_disco.dts_compiled: Warning (unit_address_vs_reg): Node /soc/pin-controller/usart1@1 has a unit name, but no reg property
dts/arm/stm32f4_disco.dts_compiled: Warning (unit_address_vs_reg): Node /soc/pin-controller/usart1@2 has a unit name, but no reg property
dts/arm/stm32f4_disco.dts_compiled: Warning (unit_address_vs_reg): Node /soc/pin-controller/usart2@0 has a unit name, but no reg property
dts/arm/stm32f4_disco.dts_compiled: Warning (simple_bus_reg): Node /soc/pin-controller simple-bus unit address format error, expected "40020000"
dts/arm/stm32f4_disco.dts_compiled: Warning (simple_bus_reg): Node /soc/i2c@40005C00 simple-bus unit address format error, expected "40005c00"
dts/arm/stm32f4_disco.dts_compiled: Warning (clocks_property): Missing property '#clock-cells' in node /soc/rcc@40023800 or bad phandle (referred from /soc/serial@40011000:clocks[0])
dts/arm/stm32f4_disco.dts_compiled: Warning (clocks_property): Missing property '#clock-cells' in node /soc/rcc@40023800 or bad phandle (referred from /soc/serial@40004400:clocks[0])
dts/arm/stm32f4_disco.dts_compiled: Warning (clocks_property): Missing property '#clock-cells' in node /soc/rcc@40023800 or bad phandle (referred from /soc/serial@40011400:clocks[0])
dts/arm/stm32f4_disco.dts_compiled: Warning (clocks_property): Missing property '#clock-cells' in node /soc/rcc@40023800 or bad phandle (referred from /soc/serial@40004800:clocks[0])
dts/arm/stm32f4_disco.dts_compiled: Warning (clocks_property): Missing property '#clock-cells' in node /soc/rcc@40023800 or bad phandle (referred from /soc/serial@40004c00:clocks[0])
dts/arm/stm32f4_disco.dts_compiled: Warning (clocks_property): Missing property '#clock-cells' in node /soc/rcc@40023800 or bad phandle (referred from /soc/serial@40005000:clocks[0])
  CHK     include/generated/generated_dts_board.conf
  UPD     include/generated/generated_dts_board.conf
  CHK     include/generated/generated_dts_board.conf
  Using /Volumes/Embedded/Zephyr/zephyr as source for kernel
  GEN     ./Makefile
  CHK     include/generated/version.h
  UPD     include/generated/version.h
  CHK     include/generated/generated_dts_board.h
  UPD     include/generated/generated_dts_board.h
  CHK     include/generated/syscall_list.h
  UPD     include/generated/syscall_list.h
  CHK     include/generated/syscall_dispatch.c
  UPD     include/generated/syscall_dispatch.c
  CHK     misc/generated/configs.c
  UPD     misc/generated/configs.c
  CHK     include/generated/offsets.h
  UPD     include/generated/offsets.h
  CC      lib/libc/minimal/source/stdlib/strtol.o
  CC      lib/libc/minimal/source/stdlib/strtoul.o
  CC      lib/libc/minimal/source/stdlib/atoi.o
  LD      lib/libc/minimal/source/stdlib/built-in.o
  CC      lib/libc/minimal/source/stdout/fprintf.o
  CC      lib/libc/minimal/source/stdout/prf.o
  CC      lib/libc/minimal/source/stdout/sprintf.o
  CC      lib/libc/minimal/source/stdout/stdout_console.o
  LD      lib/libc/minimal/source/stdout/built-in.o
  CC      lib/libc/minimal/source/string/string.o
  CC      lib/libc/minimal/source/string/strncasecmp.o
  CC      lib/libc/minimal/source/string/strstr.o
  LD      lib/libc/minimal/source/string/built-in.o
  LD      lib/libc/minimal/source/built-in.o
  LD      lib/libc/minimal/built-in.o
  LD      lib/libc/built-in.o
  LD      lib/built-in.o
  LD      tests/built-in.o
  CC      kernel/version.o
  LD      kernel/built-in.o
  CC      kernel/alert.o
  CC      kernel/device.o
  CC      kernel/errno.o
  CC      kernel/idle.o
  CC      kernel/init.o
  CC      kernel/mailbox.o
  CC      kernel/mem_slab.o
  CC      kernel/mempool.o
  CC      kernel/msg_q.o
  CC      kernel/mutex.o
  CC      kernel/pipes.o
  CC      kernel/queue.o
  CC      kernel/sched.o
  CC      kernel/sem.o
  CC      kernel/stack.o
  CC      kernel/sys_clock.o
  CC      kernel/system_work_q.o
  CC      kernel/thread.o
  CC      kernel/thread_abort.o
  CC      kernel/timer.o
  CC      kernel/work_q.o
  AR      kernel/lib.a
  CC      drivers/clock_control/stm32_ll_clock.o
  CC      drivers/clock_control/stm32f4x_ll_clock.o
  LD      drivers/clock_control/built-in.o
  CC      drivers/console/uart_console.o
  LD      drivers/console/built-in.o
  CC      drivers/crc/crc16_sw.o
  LD      drivers/crc/built-in.o
  LD      drivers/display/built-in.o
  LD      drivers/entropy/built-in.o
  CC      drivers/gpio/gpio_stm32.o
  LD      drivers/gpio/built-in.o
  CC      drivers/interrupt_controller/exti_stm32.o
  LD      drivers/interrupt_controller/built-in.o
  CC      drivers/pinmux/stm32/pinmux_stm32.o
  LD      drivers/pinmux/built-in.o
  LD      drivers/pwm/built-in.o
  CC      drivers/serial/uart_stm32.o
  LD      drivers/serial/built-in.o
  CC      drivers/timer/cortex_m_systick.o
  CC      drivers/timer/sys_clock_init.o
  LD      drivers/timer/built-in.o
  LD      drivers/built-in.o
  CC      misc/printk.o
  CC      misc/generated/configs.o
  LD      misc/generated/built-in.o
  LD      misc/built-in.o
  CC      boards/arm/stm32f4_disco/pinmux.o
  LD      boards/arm/stm32f4_disco/built-in.o
  LD      boards/built-in.o
  LD      ext/debug/built-in.o
  CC      ext/hal/st/stm32cube/stm32f4xx/drivers/src/stm32f4xx_hal.o
  CC      ext/hal/st/stm32cube/stm32f4xx/drivers/src/stm32f4xx_hal_rcc.o
  CC      ext/hal/st/stm32cube/stm32f4xx/drivers/src/stm32f4xx_ll_utils.o
  CC      ext/hal/st/stm32cube/stm32f4xx/drivers/src/stm32f4xx_hal_tim.o
  CC      ext/hal/st/stm32cube/stm32f4xx/soc/system_stm32f4xx.o
  LD      ext/hal/st/stm32cube/built-in.o
  LD      ext/hal/built-in.o
  LD      ext/lib/crypto/built-in.o
  LD      ext/lib/built-in.o
  LD      ext/built-in.o
  LD      subsys/debug/built-in.o
  CC      subsys/logging/sys_log.o
  LD      subsys/logging/built-in.o
  LD      subsys/random/built-in.o
  LD      subsys/built-in.o
  AS      arch/arm/core/exc_exit.o
  CC      arch/arm/core/irq_init.o
  AS      arch/arm/core/swap.o
  CC      arch/arm/core/fault.o
  CC      arch/arm/core/irq_manage.o
  CC      arch/arm/core/thread.o
  AS      arch/arm/core/cpu_idle.o
  AS      arch/arm/core/fault_s.o
  CC      arch/arm/core/fatal.o
  CC      arch/arm/core/sys_fatal_error_handler.o
  CC      arch/arm/core/thread_abort.o
  AS      arch/arm/core/isr_wrapper.o
  AS      arch/arm/core/cortex_m/vector_table.o
  AS      arch/arm/core/cortex_m/reset.o
  AS      arch/arm/core/cortex_m/nmi_on_reset.o
  CC      arch/arm/core/cortex_m/prep_c.o
  CC      arch/arm/core/cortex_m/scb.o
  CC      arch/arm/core/cortex_m/nmi.o
  CC      arch/arm/core/cortex_m/exc_manage.o
  LD      arch/arm/core/cortex_m/built-in.o
  CC      arch/arm/core/cortex_m/mpu/arm_core_mpu.o
  CC      arch/arm/core/cortex_m/mpu/arm_mpu.o
  LD      arch/arm/core/cortex_m/mpu/built-in.o
  LD      arch/arm/core/built-in.o
  CC      arch/arm/soc/st_stm32/common/arm_mpu_regions.o
  LD      arch/arm/soc/st_stm32/common/built-in.o
  CC      arch/arm/soc/st_stm32/stm32f4/soc.o
  CC      arch/arm/soc/st_stm32/stm32f4/soc_gpio.o
  LD      arch/arm/soc/st_stm32/stm32f4/built-in.o
  LD      arch/arm/soc/st_stm32/built-in.o
  LD      arch/arm/built-in.o
  CC      arch/common/isr_tables.o
  LD      arch/common/built-in.o
  LD      arch/built-in.o
  CC      src/main.o
/Volumes/Embedded/Zephyr/zephyr/samples/basic/blink_led/src/main.c:33:2: error: #error "Choose supported PWM driver"
 #error "Choose supported PWM driver"
  ^
/Volumes/Embedded/Zephyr/zephyr/samples/basic/blink_led/src/main.c: In function 'main':
/Volumes/Embedded/Zephyr/zephyr/samples/basic/blink_led/src/main.c:50:31: error: 'PWM_DRIVER' undeclared (first use in this function)
  pwm_dev = device_get_binding(PWM_DRIVER);
                               ^
/Volumes/Embedded/Zephyr/zephyr/samples/basic/blink_led/src/main.c:50:31: note: each undeclared identifier is reported only once for each function it appears in
/Volumes/Embedded/Zephyr/zephyr/samples/basic/blink_led/src/main.c:57:33: error: 'PWM_CHANNEL' undeclared (first use in this function)
   if (pwm_pin_set_usec(pwm_dev, PWM_CHANNEL,
                                 ^
make[3]: *** [src/main.o] Error 1
make[2]: *** [zephyr-app-dir] Error 2
make[1]: *** [sub-make] Error 2
make: *** [all] Error 2

**Comment by galak** [comment]
Based on zephyr/samples/basic/blink_led/sample.yaml the only platforms this sample is buildable for are:
      platform_whitelist: arduino_101 quark_d2000_crb
        nucleo_f103rb nucleo_f401re nucleo_l476rg hexiwear_k64

So one needs to port the sample for the stm32f4_disco board

**Comment by spring-z** [comment]
Thanks, I need STM32 samples

**Comment by spring-z** [comment]
add PR

**Comment by spring-z** [comment]
@erwango

**Comment by spring-z** [comment]
Sorry. CI block. I am trying to meet the standard.
