### ISSUE TITLE
ci: workflows: compliance: Add commit title to an error msg

### ISSUE THREAD

**Issue by PerMac** [zephyrproject-rtos/zephyr#47611]
**Is your enhancement proposal related to a problem? Please describe.**
Whenever the compliance script fails, gh workflow reports the SHA of the commit and what was the issue. However, the reported SHA points to a commit in a tree rebased internally in the workflow and doesn't match the commit SHA from a PR. This is not a problem in PRs with a couple of commits, since a user can easily guess which commit is the problematic one. However for PRs with dozens commits, tracking the offending one becomes impossible.    

**Describe the solution you'd like**
Add the title of the offending commit to the reported msg. Then a user will have a direct indication what failed and should be able to easily find it in their tree.

**Describe alternatives you've considered**
Haven't considered.

**Comment by PerMac** [comment]
@stephanosio What do you think about the enhancement? Is it something you can take care off?

**Comment by nashif** [comment]
This is not obsolete after @carlescufi  converted the action to use annotations, so you do not need to look into the log.
