### ISSUE TITLE
Poor Ethernet Performance using NXP Enet MCUX Driver

### ISSUE THREAD

**Issue by danieldegrasse** [zephyrproject-rtos/zephyr#47641]
**Describe the bug**
Ethernet performance is very poor when running `samples/net/zperf` on any board using the MCUX Enet driver. This poor performance does not manifest on the STM32 Ethernet driver, so it is unlikely this issues is related to the networking stack

**To Reproduce**

***Flashing the sample***
1. west build -p always -b mimxrt1050_evk samples/net/zperf
2. west flash

***Host configuration***
1. sudo ifconfig *network_adapter_name* 192.0.2.0 netmask 255.255.255.0

***Running TX test***
2. run `sudo iperf -s -B 192.0.2.0` on host
4. run `zperf tcp upload 192.0.2.0 5001 10 1K 1000M` on device

***Running RX test***
1. run `zperf tcp download` on device
2. run `iperf -c 192.0.2.1` on host

The below TCP TX/RX results were collected using an RT1050 EVKB:

RX: 496Kbps
TX: 23.1 Mbps

**Expected behavior**
This Ethernet hardware is capable of iperf results up to 94Mbps download and 94Mbps upload on other NXP stacks. The Zephyr implementation should at least approach these numbers.

**Environment (please complete the following information):**
 - OS: Ubuntu 22.04
 - Toolchain: Zephyr SDK 0.14.2
 - 355da1dd84e4550683e8cc1cf9a2c69fdbbfd49e

**Additional context**
STM32 iperf tests yield up to 63Mbps RX, so this should be treated as an initial goal for the iMX.RT 1050 board to achieve. That being said, there is still roughly 40 Mbps of performance left on the table versus the maximum seen on this hardware.

**Comment by danieldegrasse** [comment]
#47643 should serve as a hotfix: it does not correct all issues with the driver, but fixes TCP download performance back to usable levels

**Comment by dleach02** [comment]
@danieldegrasse, do we want to keep this issue open given the merge of #48752?

**Comment by danieldegrasse** [comment]
@dleach02 I think we can close it.
