### ISSUE TITLE
kernel: mem_pool_api test case fails on quark_d2000_crb board

### ISSUE THREAD

**Issue by rrahulkx** [zephyrproject-rtos/zephyr#4766]
TC failed while executing on zephyr Commit ID:-c968e102e679f41f0fd2016fea7391f4c121a320
From the log the TC does not seem to complete.

Failure log is pasted below:-

Detailed description
====================
configure passed
build passed: 'mkdir -p outdir-d4pp-aoov-quark_d2000_crb; rm -f outdir-d4pp-aoov-quark_d2000_crb/.config'
build passed: 'make -C zephyr/tests/kernel/mem_pool/mem_pool_api/ 
EXTRA_CFLAGS="-Werror -Wno-error=deprecated-declarations" 
KCPPFLAGS=-DTC_RUNID=:aoov 
BOARD=quark_d2000_crb ARCH=x86   
O=outdir-d4pp-aoov-quark_d2000_crb initconfig'
build output: # configuration written to .config
build passed: 'make -C zephyr/tests/kernel/mem_pool/mem_pool_api
 EXTRA_CFLAGS="-Werror -Wno-error=deprecated-declarations" 
KCPPFLAGS=-DTC_RUNID=:aoov 
BOARD=quark_d2000_crb 
ARCH=x86   
O=outdir-d4pp-aoov-quark_d2000_crb'

build passed

deploy passed
Reset

**console output:**

console output: Running test suite test_mpool_api
console output: ===================================================================
console output: starting test - test_mpool_alloc_free_thread
console output: PASS - test_mpool_alloc_free_thread.
console output: ===================================================================
console output: starting test - test_mpool_alloc_free_isr

Additional information
===============
TC started to fail from  Zephyr commit id:637087cc56040b7b3c4a81d0707723fb68e17895

**Comment by nashif** [comment]
@AdithyaBaglody are you looking into this?
