### ISSUE TITLE
bt_data_parse is destructive without warning

### ISSUE THREAD

**Issue by Klievan** [zephyrproject-rtos/zephyr#47676]
**Describe the bug**
When calling bt_data_parse, the advertisement data that you pass to it gets destroyed. It get's passed as a net_buf_simple and the data is being removed by the function directly calling net_buf_simple_pull on the data. This makes it so the data becomes unusable in other parts of the function. I could not find any pointers in the documentation that this would render the ad pointer useless.

**To Reproduce**
1. Call bt_data_parse on a received advertisement.
2. Observe that now data is partially or fully missing in the advertisement data buffer.

**Expected behavior**
Either a warning in the documentation that data in the buffer passed will disappear, or that data in the buffer is preserved. Below the relevant documentation
https://docs.zephyrproject.org/latest/connectivity/bluetooth/api/gap.html?highlight=bt_data_parse#c.bt_data_parse

**Impact**
Annoyance, minor loss of development time.

**Environment (please complete the following information):**
 - OS: MacOS
 - Toolchain: Zephyr SDK/nRF Connect SDK
 - Zephyr 3.0.99

**Comment by Thalley** [comment]
Not really a bug, but rather some documentation that can be enhanced.
