### ISSUE TITLE
qemu_arc: tests/kernel/context/ failed when migrating to new ztest API

### ISSUE THREAD

**Issue by LixinGuoX** [zephyrproject-rtos/zephyr#47725]
**Describe the bug**
I am migrating tests/kernel/context/ to new ztest API, see #47229, I got a CI failure on qemu_arc_hs and qemu_arc_em.
Test execution order has been changed, but this change only blocks the two platforms.

**To Reproduce**
1. See CI error of https://github.com/zephyrproject-rtos/zephyr/pull/47229

**Logs and console output**
```
*** Booting Zephyr OS build zephyr-v3.1.0-1812-g2760104632c1  ***
Running TESTSUITE context
===================================================================
START - test_kernel_cpu_idle
 PASS - test_kernel_cpu_idle in 0.150 seconds
===================================================================
START - test_kernel_cpu_idle_atomic
 PASS - test_kernel_cpu_idle_atomic in 0.150 seconds
===================================================================
START - test_kernel_ctx_thread
E: ***** Exception vector: 0x2, cause code: 0x1, parameter 0x0
E: Address 0x80000110
E: >>> ZEPHYR FATAL ERROR 0: CPU exception on CPU 0
E: Current thread: 0x804005cc (test_kernel_ctx_thread)
E: Halting system
```

**Comment by evgeniy-paltsev** [comment]
Hi @LixinGuoX ,

I'm wondering if this is still an issue?
As I can see the PR is merged and I don't see any failures with qemu_arc_hs / qemu_arc_em even though they are not filtered out for this test.


Do we have the test itself fixed?

**Comment by ruuddw** [comment]
This doesn't seem to be a problem anymore, please re-open if it is.
