### ISSUE TITLE
tests/posix/eventfd/ : failed on both nucleo_f103rb and nucleo_l073rz with 20K RAM only

### ISSUE THREAD

**Issue by ABOSTM** [zephyrproject-rtos/zephyr#47734]
**Describe the bug**
Test 
   `tests/posix/eventfd/portability.posix.eventfd.newlib,`
fails on both nucleo_f103rb and nucleo_l073rz which have only 20K RAM

As we can see in the error log:
`memory space available for newlib heap is less than the minimum required size specified by CONFIG_NEWLIB_LIBC_MIN_REQUIRED_HEAP_SIZE`
So it seem there is not enough RAM for this test. There is effectively only 20K RAM on those failed boards.

This is a new configuration (portability.posix.eventfd.newlib) for this test that has been added recently #47288
And I noticed that there is a restriction on another configuration `portability.posix.eventfd`:
`    min_ram: 32`

@cfriedt shall we extand the 32K min_ram to this new configuration ?

**To Reproduce**
1. twister -N --device-testing --hardware-map ../map.yaml -c -p nucleo_f103rb -T tests/posix/eventfd
2. See error

**Logs and console output**
ASSERTION FAIL [((((size_t)20) << 10) - (((uintptr_t) (&_end)) - 0x20000000)) >= 2048] @ WEST_TOPDIR/zephyr/lib/libc/newlib/libc-hooks.c:129
memory space available for newlib heap is less than the minimum required size specified by CONFIG_NEWLIB_LIBC_MIN_REQUIRED_HEAP_SIZE
E: r0/a1:  0x00000004  r1/a2:  0x00000081  r2/a3:  0x080128bd
E: r3/a4:  0x08002e69 r12/ip:  0x00000000 r14/lr:  0x08002e71
E:  xpsr:  0x21000000
E: Faulting instruction address (r15/pc): 0x0800eb9a
E: >>> ZEPHYR FATAL ERROR 4: Kernel panic on CPU 0
E: Current thread: 0x20000da0 (main)
E: Halting system

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain Zephyr SDK
 - Commit SHA: 3d2b04c9a8

**Comment by cfriedt** [comment]
@ABOSTM - Sounds good to me. I'll tag you on the PR
