### ISSUE TITLE
Some github users in the MAINTAINERS file are missing permissions

### ISSUE THREAD

**Issue by keith-zephyr** [zephyrproject-rtos/zephyr#47762]
**Describe the bug**
Some of the github users in the MAINTAINTERS file are missing triage/write permission.

Specific github users:
* @sambhurst (maintainer of state machine framework)
* @jeremybettis (collaborator of Ztest)

I am unable to select either user as a reviewer on PRs.

**Comment by keith-zephyr** [comment]
@sambhurst @jeremybettis for visibilty

**Comment by stephanosio** [comment]
@sambhurst has been added to the maintainers team
@jeremybettis has been added to the collaborators team.
