### ISSUE TITLE
warning: attempt to assign the value 'y' to the undefined symbol UART_0_NRF_FLOW_CONTROL

### ISSUE THREAD

**Issue by SRikinR** [zephyrproject-rtos/zephyr#47783]
We are trying to compile zephyr V3.1.0 from our linux system (OS version: Ubuntu 20.04.4 LTS | 64 bit) but are not able to build the the image as per configuration for nrf52840 soc.

 Following are the steps we followed to compile the image:
1) we cloned the zephyr repo from the following link https://github.com/zephyrproject-rtos/zephyr and then we have checkout to branch zephyr-v3.1.0. 
2) As per our IoT Gateway we have changed the **nrf52840dk_nrf52840.dts**, **nrf52840dk_nrf52840-pinctrl.dtsi** (PATH:: [zephyr/boards/arm/nrf52840dk_nrf52840/)] and **prj.conf** (PATH:: zephyr/sample/bluetooth/hci_uart/). 
3) We followed below command to compile hci_uart sample for nrf52840. 

> west build -b nrf52840dk_nrf52840 samples/bluetooth/hci_uart/

Now, When try to compile v3.1 repo using **UART_0_NRF_FLOW_CONTROL** config macro in prj.conf file but we get some warnnings such as 

> **warning: attempt to assign the value 'y' to the undefined symbol UART_0_NRF_FLOW_CONTROL**. 

Based on that warning we are getting below error.
> error: Aborting due to Kconfig warnings

We tried to solve all dependencies required for this macro.we have refered below link to solve dependency.

https://docs.zephyrproject.org/1.14.0/reference/kconfig/CONFIG_UART_0_NRF_FLOW_CONTROL.html

when we try to compile v3.1 without this config macro we are uable to get the hci interface as up and running status.

If we are missing something please let us know. Or else please help us to solve this issue.

We have attached the nrf52840dk_nrf52840.dts, nrf52840dk_nrf52840-pinctrl.dtsi and prj.conf file.
[zephyer_issue.zip](https://github.com/zephyrproject-rtos/zephyr/files/9111105/zephyer_issue.zip)

**Comment by jfischer-no** [comment]
CONFIG_UART_0_NRF_FLOW_CONTROL was removed in favor of `hw-flow-control` property in devicetree, see
commit 43cad10f73694e81cd73e245ddea273f01098c6d and `samples/bluetooth/hci_uart/boards/nrf52840dk_nrf52840.overlay`.
Remove Kconfig option CONFIG_UART_0_NRF_FLOW_CONTROL from your configuration and use `hw-flow-control` in your board devicetree or application devicetree overlay.
