### ISSUE TITLE
[Coverity CID: 178794] Error handling issues in /tests/subsys/dfu/mcuboot/src/main.c

### ISSUE THREAD

**Issue by Shilpashree3lc** [zephyrproject-rtos/zephyr#4780]
Static code scan issues seen in File: /tests/subsys/dfu/mcuboot/src/main.c
 Category: Error handling issues
 Function: test_bank_erase
 Component: Tests
 CID: 178794
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by nvlsianpu** [comment]
fix: https://github.com/zephyrproject-rtos/zephyr/pull/4945
