### ISSUE TITLE
rpl-node uses testcase.ini instead of sample.yaml format

### ISSUE THREAD

**Issue by SebastianBoe** [zephyrproject-rtos/zephyr#4791]

**Comment by SebastianBoe** [comment]
Also, as a related issue.

I could not get rpl-node to build with qemu_x86.

Does anyone know how to get it to build?

**Comment by rveerama1** [comment]
rpl-node is not intended for qemu purpose. Main purpose of this sample is to run it on h/w and joins in real RPL mesh network. So simple 'make' should compile sources at-least.

**Comment by SebastianBoe** [comment]
Does not build with a simple make unfortunately. I suspect it has bit rotted.
