### ISSUE TITLE
Asynchronous UART API (DMA) not working like expected on nrf52840

### ISSUE THREAD

**Issue by vleeb** [zephyrproject-rtos/zephyr#47925]
hi,
i am trying to use the async uart api on a nrf52840 for communicating to a quectel bg95 modem.
no matter which timeout or buffer-size i am using, i am experiencing the problem that that some (1-2) bytes of the modem response are not received (or forwarded via the api) when they are arriving ... they are received with delay, when the next response of the modem comes in.

so the usual communication flow to the modem is:
(1) request from nrf -> modem
(2) response from the modem -> nrf (usually ending with "\r\n")
(3) some delay
(4) next request from nrf -> modem
(5) next response from the modem -> nrf

when using the async api it happens very often, that one or both of "\r\n" of (2) are missing as long as the response of (5) is beginning to come in. then the response of (5) is prepended with the missing "\r\n" of (2).

**Comment by anangl** [comment]
@vleeb Could you provide some code snippet that can be used to reproduce the behavior you described?

**Comment by vleeb** [comment]
Hi Andrzej,

 

Thank you for your reply and your attempt to help. In the meantime I was able to solve the problem by myself.

 

At first there was a very confusing side-effect with CONFIG_NETWORKING. 
As long as I did not activate CONFIG_NETWORKING everything worked find. But after adding CONFIG_NETWORKING it did not work anymore … even while not actively using any of the networking features.

Then I found out, that CONFIG_SERIAL=y and CONFIG_UART_ASYNC_API=y without any additional nrf-specific configs are leading to a driver configuration where the incoming bytes are counted in software by an ISR, which leads to missed bytes-counts when CONFIG_NETWORKING is active. Therefore I had to add the following config lines:

CONFIG_UART_0_ASYNC=y               

CONFIG_UART_0_NRF_HW_ASYNC=y        

CONFIG_UART_0_NRF_HW_ASYNC_TIMER=2

…which were hard to find, as they are not documented and they are not working via menuconfig (compilation errors).

Very important is the proper assignment of HW_ASYNC_TIMER, as there are other driver components (i2c), which might also use hardware-timers (capture compare counters) and there is no software check for mutual exclusive use. So trial and error is the way to find it.

 

Regards,

Volker

 

 

 

Von: Andrzej Głąbek ***@***.***> 
Gesendet: Mittwoch, 3. August 2022 12:25
An: zephyrproject-rtos/zephyr ***@***.***>
Cc: Volker Leeb ***@***.***>; Mention ***@***.***>
Betreff: Re: [zephyrproject-rtos/zephyr] Asynchronous UART API (DMA) not working like expected on nrf52840 (Issue #47925)

 

@vleeb <https://github.com/vleeb>  Could you provide some code snippet that can be used to reproduce the behavior you described?
