### ISSUE TITLE
Obtaining the DNS domain name from the DHCP lease

### ISSUE THREAD

**Issue by cperera-aud** [zephyrproject-rtos/zephyr#48049]
**Is your enhancement proposal related to a problem? Please describe**

We would like to obtain the DNS domain name from the DHCP lease so that this DNS domain name can be used later on. In our solution we need to use the this DNS domain name as a search path for looking up DNS records. Following is the workflow expected in our solution:

1. Obtain a DHCP lease with IP address, DNS server, DNS domain name
2. Use the DNS domain name for DNS SRV, TXT record lookups e.g. _service._udp.<DNS domain name>
3. Use information in the DNS record for additional workflows

**Describe the solution you'd like**

What we would like is for the Zephyr DHCP client to be enhanced so that it is able to parse the Domain Name DHCP option as per RFC 2132:

![image](https://user-images.githubusercontent.com/16928715/179899767-a394f2a6-acd4-45f0-9444-2bedc8a2bc99.png)

https://www.rfc-editor.org/rfc/rfc2132.html#section-3.17

Subsequently, we would then need a API to access the domain name. 

We also need to consider a means to set the DNS domain name as part of setting a static IP configuration. 

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by cperera-aud** [comment]
I'll contribute to this issue. Feel free to assign it to me, I don't seem to be able to assign the issue to myself.

**Comment by m-byte** [comment]
The first step can be accomplished using DHCP option callbacks (https://github.com/zephyrproject-rtos/zephyr/blob/01ba923bb203c749f96bfa9d757f515d1fd91838/samples/net/dhcpv4_client/src/main.c#L98)

**Comment by cperera-aud** [comment]
Thanks Matthias, for the tip, this work wasn't high priority until recently. I'm hoping to address this in the coming weeks.

**Comment by cperera-aud** [comment]
I've tried out the changes on my end and with my application I'm able to get the DNS domain name from the DHCP lease. I didn't have much time to try setting a static DNS domain name in the case of setting a static IP address in my application.

**Comment by cperera-aud** [comment]
We're happy with the changes to get the DNS domain, so we're closing this case.
