### ISSUE TITLE
Have modbus RTU Client and modbus TCP Master on the same microcontroller

### ISSUE THREAD

**Issue by Gioelinho** [zephyrproject-rtos/zephyr#48060]
**Is your enhancement proposal related to a problem? Please describe.**
At the moment there isn't a way to have, i.e. , a Modbus TCP Mastert and Modbus RTU Client on the same microcontroller
We only have a CONFIG_MODBUS_ROLE_SERVER for both TCP and RTU

**Describe the solution you'd like**
I want one configuration option for MODBUS RTU and other one to MODBUS TCP like:
CONFIG_MODBUS_TCP_ROLE_SERVER/CLIENT
CONFIG_MODBUS_RTU_ROLE_SERVER/CLIENT 

**Describe alternatives you've considered**
No alternatives

**Additional context**
None

**Comment by jfischer-no** [comment]
Kconfig options MODBUS_ROLE_CLIENT_SERVER, MODBUS_ROLE_CLIENT, MODBUS_ROLE_SERVER, specify supported roles in the core, MODBUS_ROLE_CLIENT_SERVER is selected by default. The role of an interface is determined during initialization by `modbus_init_client(iface, param);` or `modbus_init_server(iface, param);` 

>At the moment there isn't a way to have, i.e. , a Modbus TCP Mastert and Modbus RTU Client on the same microcontroller
We only have a CONFIG_MODBUS_ROLE_SERVER for both TCP and RTU

For Modbus TCP to RTU gateway, support for the server role is not necessary, see `samples/subsys/modbus/tcp_gateway`
