### ISSUE TITLE
AF_PACKET sockets not filling L2 header details in `sockaddr_ll`

### ISSUE THREAD

**Issue by krish2718** [zephyrproject-rtos/zephyr#48089]
**Describe the bug**

We have agreed in https://github.com/zephyrproject-rtos/zephyr/pull/45592#issuecomment-1127794846 that all unknown ether types will be passed and its up to application to filter. But with fix in https://github.com/zephyrproject-rtos/zephyr/pull/45592 L2 header is now removed but the `recvfrom` doesn't fill the `sockaddr_ll` details, so, we don't have access to the protocol (ether type) for filtering. 

**To Reproduce**
Open and Receive packets from AF_PACKET and try to check `sockaddr_ll` information, `sll_addr`, `sll_protocol` etc are zeros.

**Expected behavior**
All removed L2 header details should be filled in `sll_*` fields.

**Impact**
Extra processing and filtering should be done at app.

**Logs and console output**
Can provide on demand as its trivial

**Environment (please complete the following information):**
nrf7002DK

**Comment by krish2718** [comment]
@rlubos unable to assign, so, tagging you.

**Comment by rlubos** [comment]
@krish2718 I've submitted https://github.com/zephyrproject-rtos/zephyr/pull/48422, please give it a try.
