### ISSUE TITLE
JSON parses uses recursion (breaks rule 17.2)

### ISSUE THREAD

**Issue by Sir-Branch** [zephyrproject-rtos/zephyr#48102]
Creating bug to not lose track, came up during #47989. 

We should remove recursion inside the JSON parser library, as this breaks rule  breaks rule 17.2 and is not MISRA C compliant (#11425).

 @mrfuchs pointed out:

>The library already makes use of recursion (cf. `obj_parse()`, `arr_parse()` and `decode_value()`), so I followed that approach for the `skip_field()` function.

**Comment by erickcinco** [comment]
Will this be revisited?

**Comment by simhein** [comment]
@erickcinco yes it will be revisited
