### ISSUE TITLE
tests: subsys: dfu: mcuboot_multi: dfu.mcuboot.multiimage hangs at first test case - test_request_upgrade_multi

### ISSUE THREAD

**Issue by nordic-piks** [zephyrproject-rtos/zephyr#48115]
**Describe the bug**
The test - tests/subsys/dfu/mcuboot_multi/dfu.mcuboot.multiimage
hangs during first test case:
```
ERROR   - *** Booting Zephyr OS build zephyr-v3.1.0-2425-g8fb2210cfb92  ***
Running TESTSUITE test_mcuboot_interface
 ===================================================================
START - test_request_upgrade_multi
```
no other console output within 60 sec.

Reproduction 3/3.

Observed for
- nrf52840dk_nrf52840

**To Reproduce**
1. have nrf52840dk connected
2. go to your zephyr dir
3. call ./scripts/twister -T tests/subsys/dfu/mcuboot_multi -p nrf52840dk_nrf52840 --device-testing --device-serial /dev/ttyACM0 -v --inline-logs
4. See console output

**Expected behavior**
Valid console output

**Impact**
Not clear

**Logs and console output**
```
ERROR   - *** Booting Zephyr OS build zephyr-v3.1.0-2425-g8fb2210cfb92  ***
Running TESTSUITE test_mcuboot_interface
 ===================================================================
START - test_request_upgrade_multi
```

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04.1 LTS
 - Toolchain Zephyr SDK 0.14.1
 - Commit SHA or Version used: zephyr-v3.1.0-2425-g8fb2210cfb92

**Comment by nvlsianpu** [comment]
Reproduced - this is test algorithm issue.
