### ISSUE TITLE
LVGL: License agreement not found for the font arial.ttf

### ISSUE THREAD

**Issue by rahulmohang** [zephyrproject-rtos/zephyr#48111]
Hello, 

There is a proprietary font software at https://github.com/zephyrproject-rtos/lvgl/blob/zephyr/examples/libs/freetype/arial.ttf. There is a reference to a license agreement. However, the location of the license agreement is not explicitly mentioned. We tried browsing to the URL of the webpage mentioned in the page. However, we could not reach the server. 

Is it possible to remove this font software?

**Comment by brgl** [comment]
@kisvegabor I think this is an upstream issue, does this ring a bell for you?

**Comment by kisvegabor** [comment]
Hi,

It's really an LVGL upstream issue. I replaced Arial with Lato in the  7master` branch and cherry-picked it to the `release/v8.3` branch too. I'll release v8.3.1 next week which will contain this fix.

**Comment by fabiobaltieri** [comment]
This is still pending an uprev of https://github.com/zephyrproject-rtos/lvgl, @brgl can we make sure this gets addressed before the merge window closes on Sept 9th?

**Comment by brgl** [comment]
@kisvegabor which commit can I cherry-pick to address this?

**Comment by kisvegabor** [comment]
These two, please:
https://github.com/lvgl/lvgl/commit/7354b2ea
https://github.com/lvgl/lvgl/commit/c6f76ec7

**Comment by fabiobaltieri** [comment]
Reopening until we update west.yaml to pick this up.

**Comment by brgl** [comment]
@fabiobaltieri I'm on it
