### ISSUE TITLE
Fix github permissions for user "alevkoy"

### ISSUE THREAD

**Issue by keith-zephyr** [zephyrproject-rtos/zephyr#48281]
User @alevkoy has been added as a collaborator under the [Emulation](https://github.com/zephyrproject-rtos/zephyr/blob/dfa71ca332b11ef4605577abdd6c029501258ef7/MAINTAINERS.yml#L2665) section.  However this user appears to be stuck with only contributor/read only access.

**Comment by stephanosio** [comment]
@alevkoy has been added to the "collaborators" team.
