### ISSUE TITLE
SHT3XD_CMD_WRITE_TH_LOW_SET should be SHT3XD_CMD_WRITE_TH_LOW_CLEAR

### ISSUE THREAD

**Issue by louiscr** [zephyrproject-rtos/zephyr#48299]
https://github.com/zephyrproject-rtos/zephyr/blob/1c1c57b31bc4dbcd220cb7d1ca7445d9e3da4cce/drivers/sensor/sht3xd/sht3xd_trigger.c#L231

**Comment by fabiobaltieri** [comment]
@louiscr can you send a pull request?
