### ISSUE TITLE
GSM Mux does not transmit all queued data when uart_fifo_fill is called

### ISSUE THREAD

**Issue by mmaslik** [zephyrproject-rtos/zephyr#48468]
**Describe the bug**
On some occasions a call to uart_fifo_fill results in only a part of the provided data buffer sent out when using gsm mux due to tx_ringbuf in uart_mux.c wrapping.

**To Reproduce**

1. Allocate muxing UART device
2. Attach the muxing UART to a real UART device
3. Call uart_fifo_fill outside of an ISR to transmit data
4. If the transmitted data leads to wrapping in tx_ringbuf of uart_mux.c, only the first part of the buffer (before the wrap) is sent out. The rest is sent only when another call to uart_fifo_fill is made.

**To Fix**

I would suggest wrapping ring_buf_get_claim call in uart_mux_tx_work in a loop, passing data to gsm_dlci_send until ring_buf_get_claim returns 0.

**Expected behavior**
All data provided to uart_fifo_fill should be sent out through GSM Mux when the function is called.

**Impact**
This bug makes the GSM Mux driver difficult or almost impossible to use in some scenarios.

**Environment (please complete the following information):**
 - OS: MacOS
 - Commit 0a904d0c176acf67ab10285e42f4d1924bc5bb79 tag: v3.0.99-ncs1

**Comment by mmahadevan108** [comment]
@mmaslik would you like to submit a PR to fix this issue.
