### ISSUE TITLE
Inconsistent return value of uart_mux_fifo_fill when called inside/outside of an ISR

### ISSUE THREAD

**Issue by mmaslik** [zephyrproject-rtos/zephyr#48470]
**Describe the bug**
Calling uart_fifo_fill on a GSM Mux UART device results in inconsistent return values, dependent on whether the function is called from an ISR or outside of it.

According to documentation uart_fifo_fill should return the number of bytes sent. This happens correctly when called on a UART Mux outside of an ISR. If called inside of an ISR, uart_mux_fifo_fill calls gsm_dlci_send which returns 0 on success, as opposed to number of bytes sent. 

**To Reproduce**

1. Allocate muxing UART device
2. Attach the muxing UART to a real UART device
3. Call uart_fifo_fill outside of an ISR to send data
4. The function will now return 0 on success, instead of number of bytes sent

**Expected behavior**
uart_fifo_fill should return the number of bytes sent according to documentation.

**Impact**
Low impact

**Environment (please complete the following information):**
OS: MacOS
Commit 0a904d0c176acf67ab10285e42f4d1924bc5bb79 tag: v3.0.99-ncs1

**Comment by mmahadevan108** [comment]
@mmaslik Would you like to submit a PR to fix this issue?
