### ISSUE TITLE
ZTEST: duplicate symbol linker error

### ISSUE THREAD

**Issue by asemjonovs** [zephyrproject-rtos/zephyr#48480]
**Describe the bug**
https://github.com/zephyrproject-rtos/zephyr/pull/48105 introduced linker errors

When different test suites use the same function test name, we'll encounter a duplicate symbol linker error.  Please include suite when defining test functions

```
#define Z_TEST(suite, fn, t_options, use_fixture)                                                  \
	struct ztest_unit_test_stats UTIL_CAT(z_ztest_unit_test_stats_, fn); \  // missing suite in function name
```

**To Reproduce**
1. Create test suites A and B
2. Define test `foo` in both of them
3. Compile

**Expected behavior**
Successful compilation/linking

**Impact**
annoyance

**Logs and console output**
If applicable, add console logs or other types of debug information
e.g Wireshark capture or Logic analyzer capture (upload in zip archive).
copy-and-paste text and put a code fence (\`\`\`) before and after, to help
explain the issue. (if unable to obtain text log, add a screenshot)

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain Zephyr
 - Commit SHA or Version used

**Additional context**
Add any other context that could be relevant to your issue, such as pin setting,
target configuration, ...

**Comment by smrtos** [comment]
@asemjonovs Could you take a look at https://github.com/zephyrproject-rtos/zephyr/pull/48484. I cannot add you as the reviewer.
