### ISSUE TITLE
cmake does not show verbose output of build tools

### ISSUE THREAD

**Issue by andrewboie** [zephyrproject-rtos/zephyr#4851]
In the old build system, if V=1 was passed to Make, then this would implictly pass --verbose flags to tools like gen_idt, gen_gdt, gen_kobject_list, etc...
This isn't happening any more, if I pass VERBOSE=1 to the build I see no debug output from post build tools.

**Comment by nashif** [comment]
Does 

`cmake -DCMAKE_VERBOSE_MAKEFILE=ON .. -DBOARD=qemu_x86`

give you what you want?

**Comment by andrewboie** [comment]
that prints the output I am expecting yes
can we make "make VERBOSE=1" do this??

**Comment by SebastianBoe** [comment]
I'm not able to reproduce what was originally reported here.

Steps to reproduce:
https://asciinema.org/a/pseZ5zugMwdyaJ3ynCDQvnVUp

**Comment by SebastianBoe** [comment]
I can't see an easy way to do that unfortunately.

**Comment by carlescufi** [comment]
@andrewboie try `make --trace`

**Comment by SebastianBoe** [comment]
That won't work Carles. The build system needs to invoke the underlying commands differently.

Make does not know that our custom commands accept a "--verbose" flag.

The only solution I can see here is having the scripts accept environment variables.

**Comment by pfalcon** [comment]
For me, `make VERBOSE=1` usually works (without having added any special flags to cmake previously). But sometimes it doesn't, pattern is not clear so far.

**Comment by SebastianBoe** [comment]
The desired design is that "make VERBOSE=1" is used.

But today, if you want a truly verbose build, you need to do

cmake -DCMAKE_VERBOSE_MAKEFILE=ON && make VERBOSE=1

**Comment by pfalcon** [comment]
Attempt to established a more general outlook of the problems we experience with make variables: https://github.com/zephyrproject-rtos/zephyr/issues/5153
