### ISSUE TITLE
flash: sam: Build error for sam4s_xplained

### ISSUE THREAD

**Issue by pdgendt** [zephyrproject-rtos/zephyr#48516]
**Describe the bug**
Building `samples/drivers/flash_shell` fails for the `sam4s_xplained` board.

**To Reproduce**
```shell
west build -b sam4s_xplained -s samples/drivers/flash_shell
```

**Expected behavior**
Build succeeds.

**Impact**
Current CI builds with `sam4s_xplained` board fail. (For example [this run](https://github.com/zephyrproject-rtos/zephyr/runs/7606463844?check_suite_focus=true))

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04
 - Toolchain Zephyr SDK 0.14.2
 - Commit 23bed3c93a

**Comment by galak** [comment]
Need to understand from @nandojve or someone more familiar with the atmel hardware if the sam4s flash hardware is really the same as the same70.
