### ISSUE TITLE
clang-format: #include reorder due to default: SortIncludesOptions != SI_Never 

### ISSUE THREAD

**Issue by ppryga-nordic** [zephyrproject-rtos/zephyr#48520]
**Describe the bug**
If use `clang-format` to apply formatting on save and e.g. add `#include<xxx.h>` in a source file then it runs sorting of all `#includes`.

The problem is caused by change of `.clang-format` to use `BasedOnStyle: LLVM`. This style, by default, has enabled `SortIncludes` that causes an issue. This option has to be disabled, in other case it makes a mess with `#include` directives.
Unfortunately the `SortIncludes` has been changed from SortIncludes (bool) to `SortIncludes (SortIncludesOptions)`. So we have to stick to some recent version of a clang-format causing lack of a backward compatibility.

**Expected behavior**
#include directives are not changed by formatting tool.

**Comment by gmarull** [comment]
If sorting includes introduces issues, headers should be fixed to be self-contained instead.

**Comment by ppryga** [comment]
Well that may be difficult.... There are dependencies between headers. I'm not sure it making them standalone is possible at all. Even if it is that would be significant effort to satisfy tool. In my humble opinion the tool has to satisfy us.

**Comment by gmarull** [comment]
> Well that may be difficult.... There are dependencies between headers. I'm not sure if making them standalone is possible at all. Even if it is that would be significant effort to satisfy tool. In my humble opinion the tool has to satisfy us.

It should be possible, non-self contained headers should be treated as a bug IMO. 

https://google.github.io/styleguide/cppguide.html#Self_contained_Headers

**Comment by nashif** [comment]
> It should be possible, non-self contained headers should be treated as a bug IMO.

ok, but we are not there yet and IMO this should not be part of the default style configuration we use, maybe  once all issues are resolved we could enable that, right now it is just introducing potential issues for anyone trying to use clang-format for the rest of guidelines.

**Comment by gmarull** [comment]
> > It should be possible, non-self contained headers should be treated as a bug IMO.
> 
> ok, but we are not there yet and IMO this should not be part of the default style configuration we use, maybe once all issues are resolved we could enable that, right now it is just introducing potential issues for anyone trying to use clang-format for the rest of guidelines.

Certain areas will take a loooong time to get fixed (if they ever do because if things _work_ there's no real incentive to improve unless it is enforced somehow). I think that areas doing things well should be using this option to avoid yet another file reformat in the future. When working with buggy headers, one can disable that option locally, or, resolve the problem.

**Comment by ppryga-nordic** [comment]
> > > It should be possible, non-self contained headers should be treated as a bug IMO.
> > 
> > 
> > ok, but we are not there yet and IMO this should not be part of the default style configuration we use, maybe once all issues are resolved we could enable that, right now it is just introducing potential issues for anyone trying to use clang-format for the rest of guidelines.
> 
> Certain areas will take a loooong time to get fixed (if they ever do because if things _work_ there's no real incentive to improve unless it is enforced somehow). I think that areas doing things well should be using this option to avoid yet another file reformat in the future. When working with buggy headers, one can disable that option locally, or, resolve the problem.

That is a bit uncomfortable for all maintainers that changes something in the areas where headers are no-self contained. Enable-disable the feature depending what area is updated. I suggest to disable it globally and enable it when we are actually ready for that step. I support @nashif opinion here.

**Comment by ppryga-nordic** [comment]
PR provided by @nashif #49293 has two approvals and can be merged. Then the issue may be closed.
