### ISSUE TITLE
NRF GPIO Toggle introduces race condition when multithreaded

### ISSUE THREAD

**Issue by NickolasLapp** [zephyrproject-rtos/zephyr#48578]
**Describe the bug**
`gpio_nrfx_port_toggle_bits` introduces a race condition between threads, and can cause GPIO writes to be lost.

https://github.com/zephyrproject-rtos/zephyr/blob/13714a6742ad180fff60be4b80e2d6955614eeca/drivers/gpio/gpio_nrfx.c#L210-L211

Specifically, if a pin in the `GPIO.OUT` register is changed in between capturing the assignment to `value` and writing value back out to `GPIO.OUT`, the previously written value can be lost.

Consider for example this flow:
```
gpio_nrfx_port_toggle_bits:
    value = nrf_gpio_port_out_read(reg);

ISR interrupt modifies GPIO:
    nrf_gpio_port_out_write(reg, some_new_val);

gpio_nrfx_port_toggle_bits, resumes, calls
    nrf_gpio_port_out_write(reg, value ^ mask);
```

In this case, the value written to pins, even outside of the provided mask, will get overridden by the toggle call.
The same problem also seems like it should exist for: `gpio_nrfx_port_set_masked_raw`:

https://github.com/zephyrproject-rtos/zephyr/blob/13714a6742ad180fff60be4b80e2d6955614eeca/drivers/gpio/gpio_nrfx.c#L178-L179

I ran into this problem on an nRF5340 running Zephyr plus some custom software with heavy SPI traffic. The issue presented itself because the SPI's CS_n pin would sometimes toggle an extra time, causing SPI transfers to stall out. This was because a separate, low-priority thread, was calling `gpio_pin_toggle_dt` (for a different LED pin on the same Port as the SPI CS pin), and getting interrupted by the SPI Complete Event ISR (which would toggle CS_n) between the assignment to `value` and the write to the `GPIO.OUT` register.

**Expected behavior**
GPIO toggle should only toggle the masked pins, and should not have any possibility of affecting other pins.

**Impact**
This can lead to seemingly random, hard-to-reproduce bugs in software using `gpio_pin_toggle_dt` or `gpio_set_masked` and related APIs.

**Environment (please complete the following information):**
 - OS: MacOS
 - Toolchain: Zephyr SDK
 - Commit SHA or Version used: 0a904d0c17

**Additional context**
Tested on nRF5340 DK

**Comment by anangl** [comment]
Fixed by #48582.
