### ISSUE TITLE
Remove netifaces Python package dependency

### ISSUE THREAD

**Issue by stephanosio** [zephyrproject-rtos/zephyr#48584]
The `requirements-run-test.txt` file specifies the `netifaces` package as a dependency:

https://github.com/zephyrproject-rtos/zephyr/blob/ce18d3c4ff66ae0f81212ef2f2b9143a1dca6a36/scripts/requirements-run-test.txt#L20-L21

[This package is no longer maintained](https://github.com/al45tair/netifaces) and will likely cause various problems in the future.

It already lacks the pre-built binary package (aka. wheel) for the Python 3.10 release and must be built from source during the package installation (on Windows, this requires users to have Visual Studio installed on their system ...), and it is not going to get any better for the future Python releases.

Consider replacing this dependency with another package that is well maintained.

Note that this dependency is only used by `cavstool.py`:
https://github.com/zephyrproject-rtos/zephyr/blob/20177daa0f73005d84f02941a7bebdd4d9c7e3e8/soc/xtensa/intel_adsp/tools/cavstool.py#L16

**Comment by marc-hb** [comment]
Perfect timing: for a while I've been asking @enjiamai to get rid of the misguided binding to a semi-random interface and I think he just did: https://github.com/zephyrproject-rtos/zephyr/pull/46972#issuecomment-1199760762

(and to use `INADDR_ANY` by default like any other program
https://docs.python.org/3/library/socket.html#socket-families)

**Comment by enjiamai** [comment]
Ok, @stephanosio, I think as @marc-hb mentioned, I will remote the netifaces, thanks.

**Comment by enjiamai** [comment]
Thanks for the help! @mbolivar-nordic !
