### ISSUE TITLE
drivers: gpio: expose gpio_utils.h to external GPIO drivers

### ISSUE THREAD

**Issue by mkschreder** [zephyrproject-rtos/zephyr#48609]
**Is your enhancement proposal related to a problem? Please describe.**
The problem is with external gpio drivers. These helpers are needed but by convention everything that is not under "include" is "private" headers.

**Describe the solution you'd like**

- Remove inlines
- Put this code into drivers/gpio/gpio_util.c
- Put public interface under include/drivers/gpio/gpio_util.h
- Add a kconfig option which is enabled by default if GPIO is enabled

**Describe alternatives you've considered**
Moving the header into the repo with external drivers. Not optimal because it creates duplication. 

**Additional context**
N/A

**Comment by balajikulkarni** [comment]
@mkschreder I would like to pick up this issue. One quick query though, could we have the existing gpio_util.h (with inlines) itself exposed under public header interface?

**Comment by mkschreder** [comment]
> @mkschreder I would like to pick up this issue. One quick query though, could we have the existing gpio_util.h (with inlines) itself exposed under public header interface?

Lets start with that. It would be a very small change to start with.
