### ISSUE TITLE
GSM_PPP api keeps sending commands to muxed AT channel

### ISSUE THREAD

**Issue by ivonalo** [zephyrproject-rtos/zephyr#48625]
When enabling the `CONFIG_MODEM_GSM_PPP=y `and ` CONFIG_GSM_MUX=y` options the ` gsm_ppp.c` api keeps sending "AT+CSQ" command to the modem with the `CONFIG_MODEM_GSM_RSSI_POLLING_PERIOD` period. 
Because of this, when I am sending some other AT commands in my custom api to the muxed AT channel, the response to my AT command interferes with the response to the ` AT+CSQ` command and part of my command output gets lost.
 Any idea how to solve this issue of responses interfering?

**Comment by ivonalo** [comment]
My question is how to synchronize the access to the modem with the gsm_ppp.c file from the application code? The semaphore is initialized in the gsm_ppp.c file and I have no idea how to access it from my application code

**Comment by rerickson1** [comment]
This should not be synchronized from the application code. The driver needs to change to have proper locking to account for this use case.
