### ISSUE TITLE
jlink flasher not working with recent versions of pylink dependency

### ISSUE THREAD

**Issue by fgrandel** [zephyrproject-rtos/zephyr#48626]
**Describe the bug**
 <snip>
  File ".../zephyr/scripts/west_commands/runners/jlink.py", line 162, in jlink_version
    lib = Library(dllpath=os.fspath(Path(self.commander).parent /
  File ".../.venv/lib/python3.8/site-packages/pylink/library.py", line 278, in __init__
    self.load(dllpath)
  File ".../.venv/lib/python3.8/site-packages/pylink/library.py", line 384, in load
    with open(self._path, 'rb') as inputfile:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/SEGGER/JLink_V768b/jlinkarm.so'

**To Reproduce**
1. install latest python requirements in venv
2. west flash --runner=jlink -d some-binary-dir
3. see error

**Expected behavior**
Constructing the correct library name .../libjlinkarm.so

**Impact**
What impact does this issue have on your progress (e.g., annoyance, showstopper)

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: up-to-date JLink (v768b)
 - Commit SHA: 0200da97c2

PR with potential fix follows.

**Comment by mbolivar-nordic** [comment]
This is due to a pylink change; see discussion starting at https://github.com/zephyrproject-rtos/zephyr/pull/48627#issuecomment-1204000385.
