### ISSUE TITLE
LC3 External Source Code

### ISSUE THREAD

**Issue by MariuszSkamra** [zephyrproject-rtos/zephyr#48620]
## Origin

liblc3 - Low Complexity Communication Codec library
https://github.com/google/liblc3

## Purpose

Audio codec specified by Bluetooth SIG for LE Audio purposes.

## Mode of integration

External component (fork of existing repository).

## Maintainership

Casper-Bonde-Bose
MariuszSkamra

## Pull Request

TBD
Sample PR - https://github.com/zephyrproject-rtos/zephyr/pull/46970

## Description

There is https://github.com/zephyrproject-rtos/liblc3codec repository created already, but it contains copy of old version of the code (without history and modified file structures). Because Zephyr has a copy of the code (not explicit fork) users fork and create issues in Zephyr repository instead of the one the code origins.

## Dependencies

Replacement for https://github.com/zephyrproject-rtos/liblc3codec (should be deprecated ?)

## Revision

e07f313d57347b01c04092dda00515aa6f36c9c8

## License

``Apache-2.0``

**Comment by stephanosio** [comment]
cc @nashif @carlescufi

**Comment by carlescufi** [comment]
@MariuszSkamra can you provide a sample PR that uses the new repo? For now just point directly to upstream [google/liblc3](https://github.com/google/liblc3).

**Comment by MariuszSkamra** [comment]
> @MariuszSkamra can you provide a sample PR that uses the new repo? For now just point directly to upstream [google/liblc3](https://github.com/google/liblc3). This could be the PR that just moves everything from `modules/liblc3codec/` to `modules/liblc3` in the main tree.

Done, just re-opened https://github.com/zephyrproject-rtos/zephyr/pull/46970

**Comment by carlescufi** [comment]
TSC approved this today, will create the repo.

**Comment by carlescufi** [comment]
Here is the repo: https://github.com/zephyrproject-rtos/liblc3
