### ISSUE TITLE
mpu9250 driver init function register setup using the same config parameter twice.

### ISSUE THREAD

**Issue by ShenMansell** [zephyrproject-rtos/zephyr#48724]
the mpu9250.c driver mpu9250_init function seems suspect at line 311 & 312 ->
```
ret = i2c_reg_write_byte_dt(&cfg->i2c, MPU9250_REG_ACCEL_CFG2,
                    cfg->gyro_dlpf);
```
It is using the gyro_dlpf to setup the accel cfg register. Presumably this should be using cfg->accel_dlpf?

This seems like a typo, and that thinking is confirmed by
* checks to the cfg->accel_dlpf directly before this line.
* cfg->gyro_dlpf is used to setup a different register earlier in the function.
* cfg->accel_dlpf is not used to setup any registers.

**Comment by gmarull** [comment]
cc: @dchat-nordic

**Comment by fabiobaltieri** [comment]
@ShenMansell can you send a pull request?
