### ISSUE TITLE
flash_map: pointer dereferencing causes build to fail

### ISSUE THREAD

**Issue by sslupsky** [zephyrproject-rtos/zephyr#48722]
**Describe the bug**
A recent change to flash_map is causing build problems.  A pointer is not properly declared which causes the build to fail.
https://github.com/zephyrproject-rtos/zephyr/blob/57487622f57dbb3aa7582f8dbf62c148e07c9138/subsys/storage/flash_map/flash_map_shell.c#L26-L28

```
In file included from /Users/stevenslupsky/Documents/source/zephyrproject/zephyr/subsys/storage/flash_map/flash_map_shell.c:7:
/Users/stevenslupsky/Documents/source/zephyrproject/zephyr/subsys/storage/flash_map/flash_map_shell.c: In function 'fa_cb':
/Users/stevenslupsky/Documents/source/zephyrproject/zephyr/subsys/storage/flash_map/flash_map_shell.c:27:46: error: dereferencing pointer to incomplete type 'const struct device'
       fa->fa_id, fa->fa_device_id, fa->fa_dev->name,
                                              ^~
```

flash_map_shell.c and flash_map.h do not include device.h so the device struct has an incomplete type hence the error.  Including device.h in flash_map.h resolves the problem.

@JordanYates  FYI.  #47193 appears to have caused this issue.

**Comment by sslupsky** [comment]
Also, the fa->fa_off argument is throwing a Wformat warning.  I am compiling on arm32 and the sizes are actually correct but the compiler is generating a warning.  Probably should type cast the argument?

**Comment by fabiobaltieri** [comment]
FYI @de-nordic.
