### ISSUE TITLE
net.socket.select: failed (qemu/mps2_an385)

### ISSUE THREAD

**Issue by erwango** [zephyrproject-rtos/zephyr#48779]
**Describe the bug**
See https://github.com/zephyrproject-rtos/zephyr/runs/7721882961?check_suite_focus=true

`tests/net/socket/tcp/net.socket.tcp (mps2_an385:tests/net/socket/tcp/net.socket.tcp) failed`.

Error log: 
```
START - test_v4_msg_waitall

    Assertion failed at WEST_TOPDIR/zephyr/tests/net/socket/tcp/src/main.c:203: test_context_cleanup: (wait_for_n_tcp_contexts(0, TCP_TEARDOWN_TIMEOUT) not equal to 0)
Not all TCP contexts properly cleaned up
 FAIL - test_v4_msg_waitall in 0.200 seconds
```

**Expected behavior**

**Impact**
Blocks CI

**Comment by stephanosio** [comment]
Likely related to https://github.com/zephyrproject-rtos/zephyr/issues/48608

**Comment by rlubos** [comment]
I'd say we disable other time-sensitive network tests on this platform as well, until https://github.com/zephyrproject-rtos/zephyr/issues/48608 is resolved. I'll send a PR.
