### ISSUE TITLE
test: driver: wdt: wdt cases fails in LPC platfrom randonly

### ISSUE THREAD

**Issue by hakehuang** [zephyrproject-rtos/zephyr#48801]
**Describe the bug**
wdt cases fails in LPC platfrom randonly

Please also mention any information which could help others to understand
the problem you're facing:

in watchdog testing, the test data is put in noninit area and expect to be persisted after rest, however in LPC and RTxxx series, this area may conflict with the power firmware.  so there will be some random failure for wdt cases.

**To Reproduce**
1. west build -p lpcxpresso55s28
2. west flash

**Expected behavior**
test pass

**Impact**
watchdog usage

**Logs and console output**

```
INFO    - /home/shared/disk/zephyr_project/zephyr_lpcxpresso55s28/zephyr/twister-out/lpcxpresso55s28/tests/drivers/watchdog/wdt_basic_api/drivers.watchdog/handler.log
ERROR   - Running TESTSUITE wdt_basic_test_suite
===================================================================
START - test_wdt
Testcase: test_wdt_no_callback
Waiting to restart MCU
Running TESTSUITE wdt_basic_test_suite
===================================================================
START - test_wdt
Testcase: test_wdt_no_callback
Testcase passed
Testcase: test_wdt_callback_1
Waiting to restart MCU
Running TESTSUITE wdt_basic_test_suite
===================================================================
START - test_wdt
Testcase: test_wdt_callback_1
Assertion failed at WEST_TOPDIR/zephyr/tests/drivers/watchdog/wdt_basic_api/src/test_wdt.c:362: wdt_basic_test_suite_test_wdt: test_wdt_callback_1() == TC_PASS is false
FAIL - test_wdt in 0.19 seconds
===================================================================
TESTSUITE wdt_basic_test_suite failed.
===================================================================
RunID: 5e1b0aade25e2f93b8a9407f5633fe5c
PROJECT EXECUTION FAILED

```

**Environment (please complete the following information):**
 - OS: (e.g. Linux)
 - Toolchain (e.g Zephyr SDK, ...)
 - Commit SHA or Version used:  zephyr-v3.1.0-3174-g0491242d64

**Comment by dleach02** [comment]
Problem is because the test relies on a variable in the 'noinit' section to retain its value through resets. On the LPC platform, the first 4K can be configured to retain memory but the build system doesn't have a good way to ensure that this variable resides in this 4K area.
