### ISSUE TITLE
Clicking a link leads to "Sorry, Page Not Found", where they ask to notify this GitHub 

### ISSUE THREAD

**Issue by Tsjerfell** [zephyrproject-rtos/zephyr#48828]
Hi!

I'm currently trying to implement the qdec peripheral in my code. While browsing the documentation I ended up at a "Sorry, Page Not Found"-page, where they kindly ask to report this to you. 

Reproduce :
 1. Go to this page: https://docs.zephyrproject.org/3.0.0/reference/devicetree/bindings/sensor/nordic%2Cnrf-qdec.html
 2. Click the on the "latest development version" at the top of the page. 

This is not that big of an issue, but since it says "If you got this error by following a link, please let us know by creating an issue on GitHub", I figured why not?

Have a nice day!

**Comment by gmarull** [comment]
dts bindings have been relocated, in this case https://docs.zephyrproject.org/latest/build/dts/api/bindings/sensor/nordic,nrf-qdec.html. The "latest" link is added to all pages, but those that are removed in "latest" will lead to 404.
