### ISSUE TITLE
Should command line examples be "cut and paste" ready?

### ISSUE THREAD

**Issue by dbkinder** [zephyrproject-rtos/zephyr#4883]
With multi-line command line (bash) examples, it's convenient for users to just cut and paste them into a terminal window.  Our examples (mostly) start with a ``$`` on each line, making it inconvenient to cut and paste examples such as:
```
$ cd $ZEPHYR_BASE/tests/booting/stub

# Make a build directory, and use cmake to configure a Make-based build system:
$ mkdir build && cd build
$ cmake -DBOARD=arduino_101 ..

# Now run make on the generated build system:
$ make flash
``` 
vs.
```
cd $ZEPHYR_BASE/tests/booting/stub

# Make a build directory, and use cmake to configure a Make-based build system:
mkdir build && cd build
cmake -DBOARD=arduino_101 ..

# Now run make on the generated build system:
make flash
```

For examples that mix command and their output, I'm personally in favor of putting the ``$`` in, but for multi-line examples (without output) not using the ``$`` makes more sense.  

Your thoughts?

**Comment by andrewboie** [comment]
> For examples that mix command and their output, I'm personally in favor of putting the $ in, but for multi-line examples (without output) not using the $ makes more sense.

+1

**Comment by nashif** [comment]
Samples are mostly c/p ready, it depends on how complex the sample is, but for most part, you can just copy and paste them.
