### ISSUE TITLE
cmake: IS_TEST guessing gets thrown off by symlinks

### ISSUE THREAD

**Issue by inakypg** [zephyrproject-rtos/zephyr#4885]
cmake/app/boilerplate.cmake tries to guess if something is a testcase, to define IS_TEST that then is used to automatically bring in somethings

The test gets thrown off if ZEPHYR_BASE is set to PATH1 and the app source is set to PATH2, where part of PATH2 is a symlink to PATH1.

I'd suggest changing the target of the regex match to both get the canonical path name (equivalent to 'readlink -e')

**Comment by nashif** [comment]
Actually we should not make this depend on some directory, I would rather define IS_TEST in every testcase that needs that instead, i.e. 

`set(IS_TEST 1)`

tests might be somewhere else and not in the directory structure of the project.
