### ISSUE TITLE
LwM2M: Fix BT device pending / retry errors

### ISSUE THREAD

**Issue by mike-scott** [zephyrproject-rtos/zephyr#4888]
In the bluetooth L2 layer the packets are being compressed prior to send.  This means we cannot merely resend the existing packets upon a packet timeout in the LwM2M / CoAP libraries.  Much like they do in the TCP subsystem, we need to make a clone of the original data for the pending / retry process.

As a result, we are seeing a double unref on NON-bluetooth devices:
https://github.com/zephyrproject-rtos/zephyr/pull/4391

And on bluetooth devices the retry process fails w/ ENOMEM (-12).

**Comment by Vudentz** [comment]
Not following, is this suggesting to clone every single packet? Perhaps LwM2M should follow the TCP design and have its own poll to clone the packets for timeout handling.

**Comment by Vudentz** [comment]
Btw, this is not unique to Bluetooth, afaik any driver using 6lo compression will change the packet.

**Comment by galak** [comment]
Any updates on a fix for this?

**Comment by mike-scott** [comment]
Let's mark this as 1.11.  I want to get the fix right for this.

**Comment by carlescufi** [comment]
@mike-scott can we still expect a fix for this on 1.11?

**Comment by mike-scott** [comment]
@carlescufi I think I'll defer this until post net-buf changes land.  This fix needs to go into the CoAP lib processing for retry so that it not only fixes LwM2M but also users of CoAP APIs as well.  Removing 1.11 target.

**Comment by nashif** [comment]
what is the status of this one?

**Comment by nashif** [comment]
@mike-scott ping

**Comment by mike-scott** [comment]
@nashif This issue goes away in the move to sockets.  We can close.  Unless you want to track it separately.
