### ISSUE TITLE
Flashing EM Starterkit with EM7D fails on master

### ISSUE THREAD

**Issue by nashif** [zephyrproject-rtos/zephyr#4889]
This works fine on 1.9.x but fails on master with the new flashing scripts

**Comment by mnkp** [comment]
Flashing on SAM E70 Xplained Atmel board also fails with new scripts. @nashif could you please describe EM Starterkit issue in more details so I know if it is the same failure mode or if we need a second ticket.

**Comment by nashif** [comment]
@mnkp dont think it is related, this was me doing something that the flasher did not support originally.

**Comment by mbolivar** [comment]
@nashif your fix looks good to me.
