### ISSUE TITLE
ztest: tests: add CONFIG_ZTEST_SHUFFLE=y to tests/subsys/logging/log_benchmark/prj.conf cause build failure

### ISSUE THREAD

**Issue by shaoanxli** [zephyrproject-rtos/zephyr#48918]
**Describe the bug**
After updating the new ztest api (https://github.com/zephyrproject-rtos/zephyr/pull/48902), add CONFIG_ZTEST_SHUFFLE=y to tests/subsys/logging/log_benchmark/prj.conf, build failure occurred while testing this module.

The error shows here :
zephyrproject/zephyr/subsys/testsuite/ztest/src/ztest_new.c:496:13: error: unused variable ‘start_pos’ [-Werror=unused-variable]:
![image](https://user-images.githubusercontent.com/68639634/184100180-d72ddd43-89c6-441d-8150-3079de37231e.png)

**To Reproduce**
1. sync this pr(https://github.com/zephyrproject-rtos/zephyr/pull/48902).
2. add CONFIG_ZTEST_SHUFFLE=y to tests/subsys/logging/log_benchmark/prj.conf
3. west build -p always -b frdm_k64f tests/subsys/logging/log_benchmark/

**Environment :**
OS: Linux,
Toolchain Zephyr SDK 0.14.2
Commit SHA or Version: 2748fa508508d4873248375cfc798dcae1461cb3

**Comment by yperess** [comment]
I'll try to have a fix tonight
