### ISSUE TITLE
build system/west: Add a warning if any project repo does not match the manifest

### ISSUE THREAD

**Issue by rakons** [zephyrproject-rtos/zephyr#48921]
**Is your enhancement proposal related to a problem? Please describe.**
Often build fails and I look a while for a reason before I realize I need to run west updaet

**Describe the solution you'd like**
Generate a warning during build when such situation is detected. It should be a warning, not an error to allow developing in other repositories.

**Comment by mbolivar-nordic** [comment]
This is a dupe of https://github.com/zephyrproject-rtos/zephyr/issues/23025
