### ISSUE TITLE
Fix multiple issues with adxl372 driver

### ISSUE THREAD

**Issue by nordicjm** [zephyrproject-rtos/zephyr#49019]
**Describe the bug**
The adxl372 driver has many issues, it uses a Kconfig to select if it uses SPI or I2C interface which leads to undefined operation, this should be handled in the dts instead. It also does not support multiple instances, nor can it cope with 2 devices on SPI and I2C simultaneously, therefore the driver needs to be updated and fixed to support this and prevent firmware from crashing at start up.

**Impact**
Showstopper

**Comment by nordicjm** [comment]
@mhennerich ping

**Comment by mhennerich** [comment]
Well. When this driver was mainlined. The issues you mentioned were the way zephyr worked. Coming from Linux I was wondering a lot how Devicetree was    used in zephyr...
Anyways do you have a fix we can review? Otherwise I need to see who will have a look on our side.

Anyways thanks for pointing out!

**Comment by nordicjm** [comment]
We do not have a fix for this unfortunately, no

**Comment by MaureenHelm** [comment]
> Well. When this driver was mainlined. The issues you mentioned were the way zephyr worked. Coming from Linux I was wondering a lot how Devicetree was used in zephyr... Anyways do you have a fix we can review? Otherwise I need to see who will have a look on our side.
> 
> Anyways thanks for pointing out!

@mhennerich Any update finding someone at ADI that can help fix this driver?

**Comment by mhennerich** [comment]
> @mhennerich Any update finding someone at ADI that can help fix this driver?

Yes @amiclaus will take care of this.

**Comment by MaureenHelm** [comment]
> > @mhennerich Any update finding someone at ADI that can help fix this driver?
> 
> Yes @amiclaus will take care of this.

Thank you!
