### ISSUE TITLE
cmake: BOOT_BANNER disappeared

### ISSUE THREAD

**Issue by erwango** [zephyrproject-rtos/zephyr#4904]
BOOT_BANNER disappeared following cmake migration:

Eg: 
sample/hello_world:
***** BOOTING ZEPHYR OS v1.9.99 - BUILD: Nov  8 2017 11:07:46 *****       
Hello World! arm

**Comment by SebastianBoe** [comment]
Found the root cause.

With KBuild, hello_world was a test, with CMake it is a sample. Will push a fix.

**Comment by nashif** [comment]
or we might as well just make BOOT_BANNER set to y by default...

**Comment by SebastianBoe** [comment]
Fine by me. Copying KBuild is a mental shortcut.

I'll do a new PR.
