### ISSUE TITLE
ARC: west: mdb runner: fix folder where MDB is run

### ISSUE THREAD

**Issue by cfriedt** [zephyrproject-rtos/zephyr#49119]
**Describe the bug**

See https://github.com/zephyrproject-rtos/zephyr/pull/45941 for the description. This bugfix was backported without an issue. It seems more related to CI / twister than anything else.

Please also mention any information which could help others to understand
the problem you're facing:
 - What target platform are you using?
 - What have you tried to diagnose or workaround this issue?
 - ...

**To Reproduce**
1. mkdir build; cd build
2. cmake -DBOARD=board\_xyz
3. make

**Expected behavior**

**Impact**
What impact does this issue have on your progress (e.g., annoyance, showstopper)

**Logs and console output**
If applicable, add console logs or other types of debug information
e.g Wireshark capture or Logic analyzer capture (upload in zip archive).
copy-and-paste text and put a code fence (\`\`\`) before and after, to help
explain the issue. (if unable to obtain text log, add a screenshot)

**Environment (please complete the following information):**
 - OS: (e.g. Linux, MacOS, Windows)
 - Toolchain (e.g Zephyr SDK, ...)
 - Commit SHA or Version used

**Additional context**
Add any other context that could be relevant to your issue, such as pin setting,
target configuration, ...

**Comment by mbolivar-nordic** [comment]
As discussed at the meeting, I'm not really clear on what the "unexpected mdb behavior is", so I'm going to close this. I'm also just going to close the backport issue as well and ask that the author file a bug before reopening
