### ISSUE TITLE
cmake cached BOARD_DIR variable does not get overwritten

### ISSUE THREAD

**Issue by CodingVoid** [zephyrproject-rtos/zephyr#49116]
**Describe the bug**
There is a bug in cmake/modules/boards.cmake that causes BOARD_DIR to not be overwritten if it is already in the cmake cache. 

**To Reproduce**
1. git clone https://github.com/zephyrproject-rtos/zephyr
2. cd samples/application/out_of_tree_boards
3. west init
4. west update
5. west build -c -p auto -b nrf52840dk_pca10056
6. change in CMakeLists.txt: 
`set(BOARD_ROOT ${CMAKE_CURRENT_LIST_DIR}) -> set(BOARD_ROOT ${CMAKE_CURRENT_LIST_DIR}/out-of-tree-boards)`
7. mkdir out-of-tree-boards
8. cp -r boards out-of-tree-boards/boards
9. west build -c -p auto -b nrf52840dk_pca10056
10.  now see that the board being build is actually the one in boards/arm/nrf52840dk... instead of out-of-tree-boards/arm/nrf52840dk...

**Expected behavior**
Since it is explicitly specified in the CMakeLists.txt that the BOARD_ROOT is actually the application directory/workspace, I expected the board to be build, that is inside the BOARD_ROOT directory. I could of course just do 'cmake clean' or remove the CMakeCache.txt, but I don't expect it. It took me quite a while to find out this out, which I guess is not the intention. 

The responsible code is: 
https://github.com/zephyrproject-rtos/zephyr/blame/0514c3b139bffd1813e862a1de42aece0f454c1e/cmake/modules/boards.cmake#L104
the 'find_path' function does not overwrite the value (as stated in the official cmake doc), which it is given.  Which means cached cmake variables are never overwritten (in this case BOARD_DIR).

If I know what the problem is, why didn't I just do a pull request:
Honestly I am not sure if that behaviour is actually intended. Is it normal to do a clean cmake build every time you change something in CMakeLists.txt? (I honestly don't know). I can imagine to have to make a clean build after some major changes to a CMakeLists.txt, but not just by changing the BOARD_ROOT path.

**Impact**
Well I just did a one line change in the CMakeList.txt and it took me quite a while to find out what to do.

**Comment by tejlmand** [comment]
>  Is it normal to do a clean cmake build every time you change something in CMakeLists.txt? 

no, if you do a change in a CMake file and re-run the build command, for example `ninja`, then that itself should trigger a re-run of CMake.

In Zephyr, we don't allow swapping the board to another in the build dir without a full clean.
This because of too many dependencies to the board in use, especially devicetree.

But you are not doing that, you are just moving the board folder, and that itself should be supported.

Thanks for raising this.
