### ISSUE TITLE
lack of support for lpsram cache

### ISSUE THREAD

**Issue by tmleman** [zephyrproject-rtos/zephyr#49112]
**Describe the bug**
z_xtensa_cache_flush_inv_all() doesn't flush lpsram.

**To Reproduce**
1. write something into memory area started from address 0xA0000000,
2. call z_xtensa_cache_flush_inv_all(),
3. check if changes are visible under physical memory starting from address 0x40000000

**Expected behavior**
Cache is flushed.

**Comment by edersondisouza** [comment]
I'm not sure this classifies as a bug - indeed, although it's called "flush_inv_all", there's no support currently for flushing other cache areas than a default one. I'll change the label to "Enhancement" instead of "bug".

**Comment by edersondisouza** [comment]
> I'm not sure this classifies as a bug - indeed, although it's called "flush_inv_all", there's no support currently for flushing other cache areas than a default one. I'll change the label to "Enhancement" instead of "bug".

Heh, it turned out to be actually a bug, PR at #51090
