### ISSUE TITLE
Self triage nomination Bjarki Arge Andreasen

### ISSUE THREAD

**Issue by bjarki-trackunit** [zephyrproject-rtos/zephyr#49124]
# Nomination

## GitHub User

Provide the following information about the GitHub user:

Full name: Bjarki Arge Andreasen
GitHub name: bjarki-trackunit
Organization: Trackunit A/S

## Supporting Documents

Cleanup of modem driver libraries https://github.com/zephyrproject-rtos/zephyr/pull/48530
Issue with solutions to multiple APIs pr device instance https://github.com/zephyrproject-rtos/zephyr/issues/48934
Solution 1 to multiple APIs pr device instance https://github.com/zephyrproject-rtos/zephyr/pull/48817
Solution 2 to multiple APIs pr device instance https://github.com/zephyrproject-rtos/zephyr/pull/48932
Location API proposal https://github.com/zephyrproject-rtos/zephyr/pull/48536

We probably discussed at the arch and dev meetings, I'm the one with the camera on :)

[TSC Project Roles]: <https://docs.zephyrproject.org/latest/project/project_roles.html>
[GitHub Permission Level]: <https://docs.github.com/en/organizations/managing-access-to-your-organizations-repositories/repository-permission-levels-for-an-organization>

**Comment by stephanosio** [comment]
Added as a contributor with triage permssion.
