### ISSUE TITLE
Not using the Zephyr SDK is broken

### ISSUE THREAD

**Issue by SebastianBoe** [zephyrproject-rtos/zephyr#4912]
Selecting toolchains and SDKs with environment variables is broken.

We are documenting that ZEPHYR_GCC_VARIANT specifies whether we are using a Zephyr SDK,
or a toolchain, like gccarmemb. But, this would not allow us to simultaneously use an SDK and a toolchain like issm. So we have implemented this slightly different behaviour:

ZEPHYR_GCC_VARIANT can be specified to something else than zephyr to enable a toolchain.
If a toolchain is enabled, the SDK is also assumed to be in use and present at ZEPHYR_SDK_INSTALL_DIR, if it is not an error will occur.

Find and implement a design that is understandable and satisfies the requirements of today and the near future (multiple SDK providers).

**Comment by GautierAtWork** [comment]
Using environment variables for dealing with different tools versions is a generic approach, which is used  also in large scale:
http://modules.sourceforge.net/
https://en.wikipedia.org/wiki/Environment_Modules_(software)

It is not uncommon to see hundreds of tools with tens of versions each managed this way...

**Comment by SebastianBoe** [comment]
I'm sorry @GautierAtWork , I should have been more specific, let me rework the issue text.

**Comment by SebastianBoe** [comment]
Fixed by https://github.com/zephyrproject-rtos/zephyr/pull/4918
