### ISSUE TITLE
[v2.7-branch] can't run west or DT tests on windows / py 3.6

### ISSUE THREAD

**Issue by mbolivar-nordic** [zephyrproject-rtos/zephyr#49139]
**Describe the bug**

West command and DT tests are failing in v2.7-branch because windows x python 3.6 is not a supported element of the test matrix anymore. The 3.6 runner for that platform was already explicitly disabled in main in 773242cbb705a887ca6b7445ec79636ce7b65069, but we haven't backported that yet.

**To Reproduce**

See e.g. https://github.com/zephyrproject-rtos/zephyr/pull/46190 results from today.

**Expected behavior**

Do not run on 3.6 on windows.

**Impact**

Can't backport west command patches to LTS

**Comment by carlescufi** [comment]
Fixed by #49140
