### ISSUE TITLE
Missing handling of UNKNOWN_RSP in peripheral PHY UPDATE procedure

### ISSUE THREAD

**Issue by erbr-ot** [zephyrproject-rtos/zephyr#49183]
Peripheral PHY UPDATE does not handle UNKNOWN_RSP to a PHY_UPDATE.
This led to stall of procedure and subsequent procedure timeout.

In case of UNKNOWN_RSP the peripheral should un-mask PHY support and complete procedure properly.

This is fixed by https://github.com/zephyrproject-rtos/zephyr/pull/49182

**Comment by carlescufi** [comment]
Fixed by https://github.com/zephyrproject-rtos/zephyr/pull/49182
