### ISSUE TITLE
BL5340 board cannot build bluetooth applications

### ISSUE THREAD

**Issue by nordicjm** [zephyrproject-rtos/zephyr#49210]
**Describe the bug**
Building any bluetooth sample application for the BL5340 board fails with the following error: `error: '__device_dts_ord_DT_CHOSEN_zephyr_bt_hci_rpmsg_ipc_ORD' undeclared (first use in this function)`
This is caused by a missing chosen device in the boards files.

**To Reproduce**
1. mkdir build; cd build
2. cmake -DBOARD=bl5340_dvk_cpuapp ..
3. make

**Impact**
Board is useless

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: Zephyr SDK 0.14.2
 - Commit SHA or Version used: 84f3a0a8c6a930f0252d9ceca6adf8c3b1284af0

**Comment by greg-leach** [comment]
Up to avoid stale.
