### ISSUE TITLE
dumb_http_server pollutes the source directory

### ISSUE THREAD

**Issue by andrewboie** [zephyrproject-rtos/zephyr#4924]
After running sanitycheck, I see the following from 'git status':

```
$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
Untracked files:
  (use "git add <file>..." to include in what will be committed)

	samples/net/sockets/dumb_http_server/src/response_big.html.bin.inc
	samples/net/sockets/dumb_http_server/src/response_small.html.bin.inc
```

This is not correct, build artifacts need to end up in the out directory and not in the source tree.

**Comment by pfalcon** [comment]
dumb_http_server does it because that's how @jukkar initially implemented the functionality of converting a .bin file into a C header with data. (So assignment to him looks right).
