### ISSUE TITLE
Bluetooth: Host doesn't seem to handle INCOMPLETE per adv reports

### ISSUE THREAD

**Issue by jori-nordic** [zephyrproject-rtos/zephyr#49266]
**Describe the bug**

It seems the host only handles truncated and complete periodic advertising reports.
See the main logic here https://github.com/zephyrproject-rtos/zephyr/blob/main/subsys/bluetooth/host/scan.c#L798-L833

As no controllers were sending those before, the issue wasn't caught.

Opening the issue so we don't forget about it.

**To Reproduce**

@cvinayak could you fill in some steps to reproduce here? or a branch.

**Comment by rugeGerritsen** [comment]
@jori-nordic, this has previously been validated with the SoftDevice Controller. We should still consider adding some test coverage upstream. I would guess the zephyr controller now also supports this functionality.
