### ISSUE TITLE
BLE scanning - BT RX thread hangs on.

### ISSUE THREAD

**Issue by fomst** [zephyrproject-rtos/zephyr#49373]
**Describe the bug**
During ble scan the BT RX thread hangs on and ble scan callback is not fired. This happens at random time after scan start.

**To Reproduce**
Example: bluetooth/scan_adv
west build -b nucleo_wb55rg .

scan parameters:
- BT_HCI_LE_SCAN_ACTIVE
- BT_LE_SCAN_OPT_NONE
- interval=128  (tried with other values too)
- windows=64 (tried with other values too)

**Expected behavior**
Scanning is going continously until manually stopped.

**Impact**
Hard reset has to be done to begin scanning again.

**Logs and console output**
As you can see below the number of cpu ticks of BT RX thread doesn't change for following threads analysis (time interval = 30s)
![aurora_issue_threads_info_cpu](https://user-images.githubusercontent.com/111794644/186007709-69cff5ac-3583-41e0-a432-2da01430e86d.PNG)
![aurora_issue_threads_info](https://user-images.githubusercontent.com/111794644/186007718-53d9ae1b-41bf-4bfb-925c-ff4bd8691b06.PNG)

**Environment (please complete the following information):**
 - OS: Linux
 - Zephyr SDK 3.1.99
 - FUS v.1.2.0
 - ble stack: stm32wb5x_BLE_Stack_full_fw (1.12.1) on stm32wb55 nucleo
 - ble stack: stm32wb5x_BLE_HCILayer_extended_fw (1.13.2) on own hardware
 - boards: stm32wb55 nucleo, own pcb based on stm32wb55 mcu

**Additional context**
This issue occurs on our own hardware based on stm32wb55 mcu and on stm32wb55 nucleo board. There are different ble stacks used as mentioned in Environment section.

This issue occurs at random time (from my observations this time depends on scan parameters, when scan interval and window are bigger then it's harder to reproduce this issue).

When performing tests on scan_adv example i've commented the code part responsible for advertising. Only scanning is performed.

Also i tried to do some workaround and try to reset the bt stack when noticed that this issue occured, but there is another problem.
When i do:
(pseudocode:)
bt_le_scan_disable();
hci_command->BT_HCI_OP_RESET
bt_disable();
bt_enable();

I'm getting an assertion:
![assertion_bt_enable](https://user-images.githubusercontent.com/111794644/186011344-90c08cd6-4754-4303-a7ff-ec613f4a0006.PNG)

Adding this line in hci_core.c bt_enable() resolves problem with assertion.
`k_work_queue_init(&bt_workq);`
![assertion_bt_enable_resolv](https://user-images.githubusercontent.com/111794644/186012119-55551d76-9c33-4d39-a5f3-78f6c178b87f.PNG)

**Comment by carlescufi** [comment]
@erwango @fomst could you please try to reproduce this with the Zephyr Link Layer using Nordic nRF hardware?

**Comment by erwango** [comment]
> @erwango @fomst could you please try to reproduce this with the Zephyr Link Layer using Nordic nRF hardware?

@fmost, also can you give an idea about the occurence frequency ?

**Comment by fomst** [comment]
@carlescufi I'm not able to do that. I've no nordic's hardware.

@erwango As i wrote this occures randomly, but most frequent this happens for low scan interval and scan window. For parameters passed in my first post this happens relatively often - after max few minutes.

**Comment by erwango** [comment]
@fomst Would you be able to provide a [HCI trace using btmon](https://docs.zephyrproject.org/latest/connectivity/bluetooth/bluetooth-dev.html?highlight=btmon#embedded-hci-tracing) ?
This would speed up investigation

**Comment by erwango** [comment]
@fomst Would you be able to reproduce the same configuration on a STM32Cube based application ?

**Comment by fomst** [comment]
> @fomst Would you be able to provide a [HCI trace using btmon](https://docs.zephyrproject.org/latest/connectivity/bluetooth/bluetooth-dev.html?highlight=btmon#embedded-hci-tracing) ? This would speed up investigation

@erwango 
Here are logs from bt_mon
[ble_logs.txt](https://github.com/zephyrproject-rtos/zephyr/files/9439434/ble_logs.txt)



> @fomst Would you be able to reproduce the same configuration on a STM32Cube based application ?

Do you mean to reproduce this without zephyr environment? Just with ST's code base?

**Comment by erwango** [comment]
> @erwango Here are logs from bt_mon [ble_logs.txt](https://github.com/zephyrproject-rtos/zephyr/files/9439434/ble_logs.txt)

Great, thanks

> > @fomst Would you be able to reproduce the same configuration on a STM32Cube based application ?
> 
> Do you mean to reproduce this without zephyr environment? Just with ST's code base?

Indeed.

**Comment by erwango** [comment]
@fomst Can you confirm status of `CONFIG_BT_RECV_BLOCKING` ?

**Comment by fomst** [comment]
@erwango CONFIG_BT_RECV_BLOCKING=n as the BT_RECV_WORKQ_BT is selected.

About reproducing the issue with pure ST's ble stack - i'll try to do it asap, but i've other higher priority tasks to do, so it may take some time, until i'll be back with results.

**Comment by erwango** [comment]
@fomst I have been trying to reproduce the issue in the conditions you describe since several hours now using Zephyr (only unknown is the SHA1 you're using). To no avail so far.

**Comment by fomst** [comment]
@erwango Sorry for late answer. Somehow i've missed notification.
Here is the SHA1 string: ae7f349367312dbf3f92e6aea028c0a89bb409a7.

Did you tried to reproduce this issue on the STM32 hardware, or on another one?
I still work on reproducing this issue with ST's sdk, but had not much time. Hope i'll be back with results next week.

**Comment by erwango** [comment]
> Did you tried to reproduce this issue on the STM32 hardware, or on another one?

Was using nucleo_wb55rg.

**Comment by erwango** [comment]
@fomst Have you been able to make some progress in you investigation ?

**Comment by fomst** [comment]
Hi @erwango,

Sorry for late answer, i had other stuff to do meantime.
unfortunately no progress from my side. I've not been able to reproduce this issue on pure ST's stack.
If i'll get anything new i'll inform you asap.

**Comment by carlescufi** [comment]
@jori-nordic @alwa-nordic maybe we could try to reproduce on nRF:

```
To Reproduce
Example: bluetooth/scan_adv
west build -b nucleo_wb55rg .

scan parameters:

BT_HCI_LE_SCAN_ACTIVE
BT_LE_SCAN_OPT_NONE
interval=128 (tried with other values too)
windows=64 (tried with other values too)
```
