### ISSUE TITLE
tests: tests/kernel/fatal/exception/ test case fail

### ISSUE THREAD

**Issue by hunterhu3000** [zephyrproject-rtos/zephyr#49462]
**Describe the bug**
tests/kernel/fatal/exception/ failed in daily test.

Please also mention any information which could help others to understand
the problem you're facing:
 - What target platform are you using? it8xxx2_evb
 - Is this a regression? Yes
   specific commit? 77e1e39cfff80c12ac3b0b1b802eee9e61ae79c4 
 - ...

**To Reproduce**
west build -p always -b it8xxx2_evb tests/kernel/fatal/exception/ -DCONFIG_STACK_SENTINEL=y -DCONFIG_TEST_HW_STACK_PROTECTION=n -DCONFIG_HW_STACK_PROTECTION=n -DCONFIG_ZTEST=y -DCONFIG_COVERAGE=n -DCONFIG_MP_NUM_CPUS=1 -DCONFIG_ZTEST_NEW_API=y
OR
twister  -p it8xxx2_evb --device-testing --west-flash="../../itetool/loader.sh" --device-serial=/dev/ttyUSB0 -T tests/kernel/fatal/exception/ -vv

**Expected behavior**
The test can pass

**Impact**
1 test case fail in daily test

**Logs and console output**
```
*** Booting Zephyr OS build zephyr-v3.1.0-3392-g77e1e39cfff8  (delayed boot 1ms) ***
Running TESTSUITE fatal_exception
===================================================================
START - test_fatal
test alt thread 1: generic CPU exception
E: Spurious interrupt detected! IRQ: 11
E: >>> ZEPHYR FATAL ERROR 1: Unhandled interrupt on CPU 0
E: Current thread: 0x80101048 (unknown)
Caught system error -- reason 1
Wrong crash type got 1 expected 0
```

**Environment (please complete the following information):**
 - OS: (e.g. Linux, MacOS, Windows): Ubuntu20.04
 - Toolchain (e.g Zephyr SDK, ...) 0.14.1
 - Commit SHA or Version used: 77e1e39cfff80c12ac3b0b1b802eee9e61ae79c4

**Comment by Dino-Li** [comment]
In entry_cpu_exception(), the test code runs an illegal instruction from RAM section to trigger an expection on RISCV architecture.
Since IT8xxx2 series run program from flash (text section) directly, run code from RAM section will cause an unknown result.
Can the test code be changed like this?

```
void entry_cpu_exception(void *p1, void *p2, void *p3)
{
	expected_reason = K_ERR_CPU_EXCEPTION;

#if defined(CONFIG_X86)
	__asm__ volatile ("ud2");
#elif defined(CONFIG_NIOS2)
	__asm__ volatile ("trap");
#elif defined(CONFIG_ARC)
	__asm__ volatile ("swi");
#elif defined(CONFIG_RISCV)
	/* illegal instruction on RISCV */
	__asm__ volatile (".long 0");
#else
	/* Triggers usage fault on ARM, illegal instruction on
	 * xtensa, TLB exception (instruction fetch) on MIPS.
	 */
	{
		volatile long illegal = 0;
		((void(*)(void))&illegal)();
	}
#endif
	rv = TC_FAIL;
}
```

**Comment by hunterhu3000** [comment]
Looks good to me
The patch can fix the problem on it8xxx2_evb.
Could you please provide a PR?
