### ISSUE TITLE
k_sleep in native_posix always sleeps one tick too much    

### ISSUE THREAD

**Issue by SkryptX** [zephyrproject-rtos/zephyr#49523]
I tried the LVGL example in the Zephyr repository (zephyr/samples/subsys/display/lvgl/src) with the `native_posix_64` board and added a log statement into the while loop at the end of main. After a bit of debugging I realized that every `k_sleep` call waits 10ms (the tick duration) too much. I simplified the code and got this:

```
while (1) {
  LOG_INF("%d", count);
  k_sleep(K_MSEC(<value>));
  count++;
}
```
Console output for value=1000:
```
*** Booting Zephyr OS build zephyr-v3.1.0-4114-g32e2e1cb799e  ***
[00:00:00.000,000] <inf> app: 0
[00:00:01.010,000] <inf> app: 1
[00:00:02.020,000] <inf> app: 2
```

For <value> 10ms it waits 20ms, for 1000ms it waits 1010ms and so on. Also tried `K_TICKS(...) `and this also has the same behavior. `k_busy_wait(...)` on the other hand works correctly. 

I would expect it to correctly print a message every 1000ms.

 - OS: Linux
 - Toolchain: GNU
 - Zephyr OS build zephyr-v3.1.0-4114-g32e2e1cb799e

**Comment by aescolar** [comment]
@SkryptX that is the expected behavior and is not related to native_posix but the kernel. k_sleep waits for at least the time you request not less, and the resolution of that wait is the system tick period.
When k_sleep is called the first time, the time 0 tick has just passed, and the kernel waits until the first tick after 1s meaning it will wake that thread after the 1.01s tick. After that tick has come, the thread is woken and it requests to wait 1ms, so the next tick after that is at 2.02 and so forth.

**Comment by SkryptX** [comment]
This means the definition of `k_sleep` is to wait the given amount of ticks and not to wake x ticks later?

Like this (with tick duration 10ms):
```
t_0--------------------------------t_1010ms
----------------------------------------------------
Tick 0      | 100 Ticks wait time | Tick 101
----------------------------------------------------
k_sleep(1s) | waiting...          | LOG_INF(...)
```

Not like this:
```
t_0---------------------------------t_1000ms
----------------------------------------------------
Tick 0      | wait till tick 0+100 | Tick 100
----------------------------------------------------
k_sleep(1s) | waiting...           | LOG_INF(...)
```
That kinda makes sense. The problem just seems way worse than it actually is, because native_posix doesn't know any execution time, so there are always the full 1010ms in between and not _something_ between 1000ms and 1010ms. This means that the behavior is actually correct. 

What I still would consider:

- Extend the documentation with an explicit statement, that the delay specified is tick-based and guarantees a delay between [specified amount, specified amount + 1 tick).
- Arithmethics with k_timeout_t in case you want a delay of 1000ms - 1 tick for example. I see no easy and expressive way to do this currently.

**Comment by aescolar** [comment]
Yes.

> What I still would consider..

This would be feedback for the kernel API itself. Maybe you want to create a separate issue?
