### ISSUE TITLE
LE Audio: TMAP: Broadcast Media Sender

### ISSUE THREAD

**Issue by asbjornsabo** [zephyrproject-rtos/zephyr#49537]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context or graphics (drag-and-drop an image) about the feature request here.

**Comment by Thalley** [comment]
Closing as it is implemented
