### ISSUE TITLE
Backport cmake string cache fix to v2.7 branch

### ISSUE THREAD

**Issue by nordicjm** [zephyrproject-rtos/zephyr#49569]
**Describe the bug**
If a string variables is passed when configuring a project, then the project configuration is edited, the project will then fail to work because the string variable has had it's quotes removed.

Original issue: https://github.com/zephyrproject-rtos/zephyr/issues/48950
Original fix in main: https://github.com/zephyrproject-rtos/zephyr/pull/49267

**Expected behavior**
For re-configured applications to still compile

**Impact**
Annoyance

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: Unimportant
 - Commit SHA or Version used: 003de78ce0dd213a1c7b3d159b967fb19a12aa45

**Comment by tejlmand** [comment]
Fixed by: https://github.com/zephyrproject-rtos/zephyr/pull/49570
