### ISSUE TITLE
All boards for all arch's should use DTS

### ISSUE THREAD

**Issue by galak** [zephyrproject-rtos/zephyr#4960]
- [x] x86: Issue #3704
- [x] ARC: Issue #4964 
- [x] NIOS2: Issue #4963 
- [x] RISCV: Issue #4962 
- [x] XTENSA: Issue #4961

**Comment by psidhu** [comment]
I hope once this occurs, we can start using dts more heavily in drivers?

**Comment by nashif** [comment]
moving to enhancement, this is not really a bug...

**Comment by galak** [comment]
Now all arch's support DTS.
