### ISSUE TITLE
BeagleBone Black / AM335x Support

### ISSUE THREAD

**Issue by shaggygi** [zephyrproject-rtos/zephyr#49606]
**Is this request related to a missing driver support for a particular hardware platform, SoC or board? Please describe.**
BeagleBone Black and the TI AM335x.

**Describe why you are asking for this support?**
Used with lots of makers and IoT projects.

Thanks for any help.

**Comment by henrikbrixandersen** [comment]
A PR for adding support for this board is most welcome. If you have access to this hardware, please consider adding a board definition yourself and submitting it.
