### ISSUE TITLE
Convert xtensa boards to device tree

### ISSUE THREAD

**Issue by galak** [zephyrproject-rtos/zephyr#4961]
The following boards need to get converted:
- [x] esp32
- [x] qemu_xtensa
- [x] xt-sim

**Comment by nashif** [comment]
moving to enhancement, this is not really a bug...

**Comment by galak** [comment]
esp32 board dts conversion completed by PR #7581

**Comment by galak** [comment]
Merging of #7872 gets the last two boards to use DTS.
