### ISSUE TITLE
&usart2_rx_pd6 no more available for STM32L073RZ

### ISSUE THREAD

**Issue by LaVoute974** [zephyrproject-rtos/zephyr#49618]
Hi everybody, 

After an update of my zephyr folder, I found that the pin &usart2_rx_pd6 is no more available. When declaring in the .dts file, it outputs an error : 

`devicetree error: /soc/serial@40004400: undefined node label 'usart2_rx_pd6'`

Is that normal ? 

Thanks for your help :)

**Comment by str4t0m** [comment]
According to the datasheet this pin is only available on the 100-pin variants, not the 64-pin variants.
Are you running zephyr on a STM32L073VZ SoC?

**Comment by LaVoute974** [comment]
Yes indeed !

**Comment by str4t0m** [comment]
So then your problem should be fixed by including the pinctrl file matching your soc.
I will close this issue.
