### ISSUE TITLE
Convert ARC boards to device tree

### ISSUE THREAD

**Issue by galak** [zephyrproject-rtos/zephyr#4964]
The following boards need to get converted:

- [ ] arduino_101_sss
- [ ] em_starterkit
- [ ] ~~panther_ss~~ (no need to do this, will be dropped)
- [x] quark_se_c1000_ss_devboard

**Comment by SavinayDharmappa** [comment]
@galak  @nashif  arduino_101_sss dts support is added only for em_starterkit needs to added

**Comment by linkmeyer** [comment]
I moved the milestone to v1.12 per Manoj's feedback that it will not be fixed until then.

**Comment by nashif** [comment]
was completed by @galak
