### ISSUE TITLE
v3.1-branch: some cases failed with build warnings after upgrading zephyr sdk to 0.15.0.

### ISSUE THREAD

**Issue by chen-png** [zephyrproject-rtos/zephyr#49658]
**Describe the bug**
On v3.1-branch, after upgrading to zephyr-sdk-0.15.0, some tests failed due to build warnings, like some compilation warnings:

1. "warning: 'elapsed_ms' may be used uninitialized [-Wmaybe-uninitialized]".
2. ":error: comparison between two arrays -Werror=array-compare
      if (_net_if_list_start == _net_if_list_end)"
3.  warning: 'version' may be used uninitialized [-Wmaybe-uninitialized]
       get_version_check(&version);

**To Reproduce**
1. west build -b qemu_x86 -p auto tests/kernel/sleep/

**Logs and console output**

zephyrproject/zephyr/subsys/testsuite/ztest/include/ztest_assert.h:101:21: **warning: 'elapsed_ms' may be used uninitialized [-Wmaybe-uninitialized]**
     bool _ret = z_zassert(cond, msg ? ("(" default_msg ")") : (default_msg), \
zephyrproject/zephyr/tests/kernel/sleep/src/usleep.c:68:17: note: 'elapsed_ms' was declared here
     int64_t elapsed_ms;

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04
 - Toolchain: Zephyr-sdk-0.15.0
 - Commit ID: 6628b0631

**Comment by stephanosio** [comment]
As noted in the [SDK release notes](https://github.com/zephyrproject-rtos/sdk-ng/releases/tag/v0.15.0), Zephyr SDK 0.15.0 is "only compatible with the Zephyr development branch (main) and the Zephyr release v3.2 and above," and there currently is no plan to support SDK 0.15.0 in Zephyr 3.1.

Please use Zephyr SDK 0.14.x if you are using Zephyr 3.1 or an earlier release.
