### ISSUE TITLE
frdm_k64f: tests: failed to run tests/drivers/adc/adc_dma/drivers.adc-dma

### ISSUE THREAD

**Issue by shaoanxli** [zephyrproject-rtos/zephyr#49713]
**Describe the bug**
The test failure occurs after 5ceba48473951feced93aa2076370250e0cea544.

**To Reproduce**
1. source zephyr-env.sh
2. twister -p frdm_k64f --hardware-map map.yml --device-testing -T tests/drivers/adc/adc_dma/  -v
3. See error
or 
2.picocom -b 115200 /dev/ttyACM2
3.west build -p always -b frdm_k64f tests/drivers/adc/adc_dma/
4.west flash
5.See error
  
**Expected behavior**
The test should pass.

**Impact**
test failed.

**Logs and console output**
```
▒*** Booting Zephyr OS build zephyr-v3.1.0-4300-g5ceba4847395  ***
Running TESTSUITE adc_dma
===================================================================
START - test_adc_asynchronous_call
ASSERTION FAIL [(((uint32_t)(uint32_t *)destAddr) % destWidth) == 0U] @ WEST_TOPDIR/modules/hal/nxp/mcux/mcux-sdk/drivers/edma/fsl_edma.c:1015
E: r0/a1:  0x00000004  r1/a2:  0x000003f7  r2/a3:  0x00000080
E: r3/a4:  0x0000000f r12/ip:  0x00000000 r14/lr:  0x00006cf3
E:  xpsr:  0x4100000f
E: Faulting instruction address (r15/pc): 0x0000e52c
E: >>> ZEPHYR FATAL ERROR 4: Kernel panic on CPU 0

```

**Environment :**
 OS: Linux
Toolchain Zephyr SDK 0.15.0
Commit SHA or Version: 5ceba48473951feced93aa2076370250e0cea544

**Comment by mmahadevan108** [comment]
This is similar to Issue https://github.com/zephyrproject-rtos/zephyr/issues/49792.

@shaoanxli kindly help review PR https://github.com/zephyrproject-rtos/zephyr/pull/49793 that fixes this issue
