### ISSUE TITLE
Intel CAVS15/18: Failure in tests/arch/common/timing

### ISSUE THREAD

**Issue by shuai1x** [zephyrproject-rtos/zephyr#49716]
**Describe the bug**
On intel_adsp_cavs15/18 platform, tests/arch/common/timing failed.
Bisect result: 4819e5488da15f8c0714dbbc1fa333993a8df214

Please also mention any information which could help others to understand
the problem you're facing:
 - intel_adsp_cavs15/18
 - tests/arch/common/timing failed.

**To Reproduce**
1. twister -W --hardware-map /home/ztest/cavs/cavs.map --device-testing -x=CONFIG_BOOT_DELAY=500 -T tests/arch/common/timing --no-skipped-report -vv
4. see error

**Logs and console output**
```
START - test_arch_timing

Assertion failed at WEST_TOPDIR/zephyr/tests/arch/common/timing/src/main.c:66: perform_tests: diff1_ns not within WAIT_NS +/- WAIT_NS * TOLERANCE

FAIL - test_arch_timing in 0.003 seconds
```
```
START - test_arch_timing_smp

Assertion failed at WEST_TOPDIR/zephyr/tests/arch/common/timing/src/main.c:66: perform_tests: diff1_ns not within WAIT_NS +/- WAIT_NS * TOLERANCE

Assertion failed at WEST_TOPDIR/zephyr/tests/arch/common/timing/src/main.c:66: perform_tests: diff1_ns not within WAIT_NS +/- WAIT_NS * TOLERANCE


FAIL - test_arch_timing_smp in 0.003 seconds
```

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain - SDK 15.0
 - Commit SHA: 4819e5488da15f8c0714dbbc1fa333993a8df214

**Comment by nashif** [comment]
this should be fixed already by https://github.com/zephyrproject-rtos/zephyr/pull/49771
