### ISSUE TITLE
USB: documentation needs to be updated

### ISSUE THREAD

**Issue by jfischer-phytec-iot** [zephyrproject-rtos/zephyr#4977]
doc/subsystems/usb/usb.rst, chapter `USB device class drivers ` needs to be updated. The description is not wrong, but does not reflect current status.

**Comment by nashif** [comment]
@finikorg , @jfischer-phytec-iot  will you take a stab at this?

**Comment by jfischer-phytec-iot** [comment]
I will update the description of the USB Device Descriptor. I think everything else should be updated when #4661,#4767 are ready (or with it).

**Comment by finikorg** [comment]
@nashif I could document USB Networking, what would be the proper place for it?

**Comment by nashif** [comment]
@finikorg doc/subsystems/usb/

**Comment by carlescufi** [comment]
This has been fixed
