### ISSUE TITLE
Intel CAVS25: Failure in tests/boards/intel_adsp/smoke sporadically

### ISSUE THREAD

**Issue by shuai1x** [zephyrproject-rtos/zephyr#49790]
**Describe the bug**
On intel_adsp_cavs25 platform, tests/boards/intel_adsp/smoke failed.
This case has a one in ten chance of failure.
Bisect result: Can’t find the exact commit.

Please also mention any information which could help others to understand
the problem you're facing:
 - intel_adsp_cavs25
 - tests/boards/intel_adsp/smoke failed.

**To Reproduce**
1. twister -W --hardware-map /home/ztest/cavs/cavs.map --device-testing -x=CONFIG_BOOT_DELAY=500 -T tests/boards/intel_adsp/smoke/ --no-skipped-report -vv
2. see error

**Logs and console output**
```
START - test_2nd_cpu_halt
halt/restart core 1...
halt/restart core 2...
Assertion failed at WEST_TOPDIR/zephyr/tests/boards/intel_adsp/smoke/src/cpus.c:167: halt_and_restart: (alive_flag is true)
cpu didn't halt
FAIL - test_2nd_cpu_halt in 0.251 seconds
```

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain - SDK 15.0

**Comment by edersondisouza** [comment]
This is an interesting one. Firstly, I could reproduce it, but the ratio wasn't anything like 1 in 10. From around 500 runs, I got the error 2 times. That in itself is curious. Secondly, I couldn't reproduce it using previous SDK (0.14.2), which is a hint for why this hadn't appeared before. Finally, I think I have fix, but I'm not sure I can explain it completely. Will send a PR soon.

**Comment by edersondisouza** [comment]
Hi @shuai1x, could you please check if my draft PR https://github.com/zephyrproject-rtos/zephyr/pull/49877 fixes this issue for you? If it does, I'll make it a proper PR.

**Comment by shuai1x** [comment]
> Hi @shuai1x, could you please check if my draft PR #49877 fixes this issue for you? If it does, I'll make it a proper PR.

Ok, will reply to you soon.

**Comment by shuai1x** [comment]
> Hi @shuai1x, could you please check if my draft PR #49877 fixes this issue for you? If it does, I'll make it a proper PR.

Hi, I have checked your draft PR, and it can't fix this issue. And I have also tested 500 times, it would fail 6 times.

**Comment by edersondisouza** [comment]
Oh, that's a bummer. Just to clarify, did it at least make it less likely? On the original report, it is mentioned 1 in 10, but more likely 1 in 100 with my draft PR. So, did it become less likely, or no influence at all?

**Comment by shuai1x** [comment]
> Oh, that's a bummer. Just to clarify, did it at least make it less likely? On the original report, it is mentioned 1 in 10, but more likely 1 in 100 with my draft PR. So, did it become less likely, or no influence at all?

I think I need to test it again to compare the results of these two tests. And will reply to you soon.

**Comment by shuai1x** [comment]
> Oh, that's a bummer. Just to clarify, did it at least make it less likely? On the original report, it is mentioned 1 in 10, but more likely 1 in 100 with my draft PR. So, did it become less likely, or no influence at all?

I did the test again. And I wonder whether the failure is random. Because before I tested it, it would fail 1 in 10, but this test I ran 100 times, and failed 27, which seems 3 in 10. And after using your draft PR, it would pass 5 in 100. So it seems your PR make it become less.

**Comment by edersondisouza** [comment]
Thanks for the input, I'm finalizing a patch here that should truly solve the issue, stay tuned =D

**Comment by edersondisouza** [comment]
Ok, so I updated my draft PR - I think it solves this issue. Even if it doesn't, it still fix some code issues. @shuai1x could you check, please?

**Comment by shuai1x** [comment]
> Ok, so I updated my draft PR - I think it solves this issue. Even if it doesn't, it still fix some code issues. @shuai1x could you check it, please?

Ok, will reply to you soon.
