### ISSUE TITLE
I/O APIC Driver in Zephyr makes incorrect register access.

### ISSUE THREAD

**Issue by aradhumal** [zephyrproject-rtos/zephyr#49803]
**Describe the bug**
The ioapic driver in the zephyr OS makes an incorrect access to the register offset of IOAPIC during the init process.
[https://github.com/zephyrproject-rtos/zephyr/blob/main/drivers/interrupt_controller/intc_ioapic.c](url)
line number : 466
The typecast to char causes the assembly language instruction movsbl to have a signed extension of the ebx register starting with register offset 0x80.

The dissassembly of the __IoApicSet routine:
`<html>
<body>

0000000000101d07 <__IoApicSet>:
--
101d07:    55                       push   %rbp
101d08:    48 89 e5                 mov    %rsp,%rbp
101d0b:    41 54                    push   %r12
101d0d:    41 89 f4                 mov    %esi,%r12d
101d10:    53                       push   %rbx
101d11:    89 fb                    mov    %edi,%ebx
101d13:    e8 8a 1f 00 00           callq  103ca2 <z_smp_global_lock>
101d18:    89 c7                    mov    %eax,%edi
101d1a:    48 8b 05 ef fc 48 00     mov    0x48fcef(%rip),%rax        # 591a10 <z_mmio_ram__ioapic_regs>
101d21:    0f be db                 movsbl %bl,%ebx
101d24:    89 18                    mov    %ebx,(%rax)
101d26:    44 89 60 10              mov    %r12d,0x10(%rax)
101d2a:    5b                       pop    %rbx
101d2b:    41 5c                    pop    %r12
101d2d:    5d                       pop    %rbp
101d2e:    e9 a4 1f 00 00           jmpq   103cd7 <z_smp_global_unlock>

</body>
</html>`

**Expected behavior**
No crash.

**Impact**
I/O APIC initialisation for register access after 0x80 is not executed correctly.

**Platform**
Intel x86 Elkhart Lake (ehl_crb)

**Bug Fix**
Removing the type cast to char in the __IoApicSet function helps to fix the bug. 
![ioapic_zephyr_fix](https://user-images.githubusercontent.com/112617287/187876994-5619865e-ab8d-4f01-a934-cdead87fc491.PNG)

**Comment by henrikbrixandersen** [comment]
Please submit a PR with the proposed fix.

**Comment by fabiobaltieri** [comment]
Hi @aradhumal if you need help creating a pull request, this is the documentation for the contribution guideline and workflow: https://docs.zephyrproject.org/latest/contribute/guidelines.html#contribution-workflow.
