### ISSUE TITLE
net: shell: Extend ping command

### ISSUE THREAD

**Issue by krish2718** [zephyrproject-rtos/zephyr#49843]
Extend networking shell ping command to take more arguments

* payload size (`-s` in Linux)
* QoS setting (`-Q`/-`T`/`-S`) that can accepted hex/decimal

https://github.com/zephyrproject-rtos/zephyr/issues/49843#tasklist-block-d04b0db3-9a5c-4baa-b0ef-453d43d9e7ac

**Comment by krish2718** [comment]
@rlubos

**Comment by krish2718** [comment]
QoS setting is now added, only `payload size` is remaining.

**Comment by sachinthegreen** [comment]
Hi @rlubos ,

Just following up on this since this would help in unblocking a few test cases that we need to run. Do you have a feel as to by when the `payload size` support could be added?

Regards,
Sachin

**Comment by rlubos** [comment]
@sachinthegreen I'll prioritize this.
