### ISSUE TITLE
shell: Add abort support

### ISSUE THREAD

**Issue by krish2718** [zephyrproject-rtos/zephyr#49844]
Currently, if we run a shell command, then there is no way to abort it, e.g., `net ping -c 100 192.168.0.1` you need to wait for the command to complete. It would be good to have support for `ctrl + c` keyboard interrupt.

I don't see much support for signal handlers in Zephyr except for [this](https://github.com/zephyrproject-rtos/zephyr/commit/e04764dbc716301604cb4e201eebe15cde6a4aee).

**Comment by krish2718** [comment]
@rlubos

**Comment by rlubos** [comment]
CC @jakub-uC

**Comment by jakub-uC** [comment]
You redirect keyboard input to your handler and bypass shell. Please check: 
https://github.com/zephyrproject-rtos/zephyr/blob/main/include/zephyr/shell/shell.h#L1154

**Comment by rlubos** [comment]
> You can redirect keyboard input to your handler and bypass shell. Please check: https://github.com/zephyrproject-rtos/zephyr/blob/main/include/zephyr/shell/shell.h#L1154

I need to give it a try, thanks for the information!
