### ISSUE TITLE
Add possibility to do calculations with k_timeout_t 

### ISSUE THREAD

**Issue by nylnx** [zephyrproject-rtos/zephyr#49858]
There is currently no easy way to calculate a custom timeout. Something like `1000ms - 1 tick` is error-prone and difficult to get right, especially when compiling for different hardware with different tick-bases. This could be solved with a few standardized add, subtract, multiply and divide macros/functions which let you do timeout calculations on the opaque `k_timeout_t` data type.

**Comment by andyross** [comment]
Absent doing it all in floating point, this isn't actually possible.  The different time units aren't guaranteed to be easily convertible, and that is down to hardware clocks and not something we can fix.  At best, you can convert everything to us/ns using the existing standard utilities (which we do provide) and do the math there.  The units of k_timeout_t are still ticks, and thus lossy if you're trying to look at something finer.
