### ISSUE TITLE
TEE support for ARMv8-M

### ISSUE THREAD

**Issue by carlescufi** [zephyrproject-rtos/zephyr#4985]
Implement https://github.com/zephyrproject-rtos/zephyr/issues/1900 for ARMv8-M.

Blocked by https://github.com/zephyrproject-rtos/zephyr/issues/4983

**Comment by carlescufi** [comment]
@ioannisg FYI

**Comment by dleach02** [comment]
@carlescufi since #4983 is closed can we move #1900?

**Comment by carlescufi** [comment]
> @carlescufi since #4983 is closed can we move #1900?

I think so, but let @ioannisg decide since he's the maintainer of TEE on Armv8-M

**Comment by carlescufi** [comment]
This is done
