### ISSUE TITLE
ctf trace: unknown event id when parsing samples/tracing result on reel board

### ISSUE THREAD

**Issue by smrtos** [zephyrproject-rtos/zephyr#49889]
**Describe the bug**
Try to capture ctf trace on reel_board with below steps:

Preparation:

0. As mentioned [here](https://github.com/zephyrproject-rtos/zephyr/issues/24457#issuecomment-617486501), to make sure only trace data go through the UART, I comment out all the `printk()` in [main.c](https://github.com/zephyrproject-rtos/zephyr/blob/main/samples/subsys/tracing/src/main.c).

Build the sample app:

```
1. cmake -GNinja -DBOARD=reel_board -DCONF_FILE=prj_uart_ctf.conf -B bld_ctf_reel -S samples/subsys/tracing/
2. cd bld_ctf_reel
3. ninja flash
```

Then capture the trace from UART with script from [here](https://github.com/zephyrproject-rtos/zephyr/blob/main/scripts/tracing/trace_capture_uart.py):

`4.  python ../scripts/tracing/trace_capture_uart.py -d /dev/ttyACM0 -b 115200 -o ctf_data/cap1.ctf`

To avoid the boot banner message messing with the parsing, do another capture:

`5.  python ../scripts/tracing/trace_capture_uart.py -d /dev/ttyACM0 -b 115200 -o ctf_data/cap2.ctf`

Put the second capture file and CTF metadata in one folder and parse it with `babeltrace`:

```
6. mkdir ctf_data
7. cp ../subsys/tracing/ctf/tsdl/metadata ./ctf_data/
8. mv cap2.ctf ./ctf_data/
9. babeltrace ctf_data
```

Below error shows up:

```
[error] Event id 32 is unknown.
[error] Reading event failed.
Error printing trace.

```

I also tried using `minicom` to capture the UART trace output. And saw similar errors.

I also found issue https://github.com/zephyrproject-rtos/zephyr/issues/24457, which seems to be the same as what I did.
That issue is closed but I still see the same symptom.

The `babeltrace` I am using is:

> BabelTrace Trace Viewer and Converter 1.5.8

Then I tried with `babeltrace2` with the same data folder. It shows below error:

> 09-04 17:49:39.758 2329126 2329126 E PLUGIN/CTF/MSG-ITER set_current_event_class@msg-iter.c:1276 [auto-disc-source-ctf-fs] No event class with ID of event class ID to use in stream class: msg-it-addr=0x56472970bc70, stream-class-id=0, event-class-id=32, trace-class-addr=0x56472967fb60
> 09-04 17:49:39.758 2329126 2329126 E PLUGIN/CTF/MSG-ITER ctf_msg_iter_get_next_message@msg-iter.c:2897 [auto-disc-source-ctf-fs] Cannot handle state: msg-it-addr=0x56472970bc70, state=AFTER_EVENT_HEADER
> 09-04 17:49:39.758 2329126 2329126 E PLUGIN/SRC.CTF.FS ctf_fs_iterator_next_one@fs.c:108 [auto-disc-source-ctf-fs] Failed to get next message from CTF message iterator.
> 09-04 17:49:39.758 2329126 2329126 W LIB/MSG-ITER bt_message_iterator_next@iterator.c:861 Component input port message iterator's "next" method failed: iter-addr=0x56472970ba80, iter-upstream-comp-name="auto-disc-source-ctf-fs", iter-upstream-comp-log-level=WARNING, iter-upstream-comp-class-type=SOURCE, iter-upstream-comp-class-name="fs", iter-upstream-comp-class-partial-descr="Read CTF traces from the file sy", iter-upstream-port-type=OUTPUT, iter-upstream-port-name="/home/ming/zephyrproject2/zephyr/bld_ctf_reel/ctf_data | 0 | /home/ming/zephyrproject2/zephyr/bld_ctf_reel/ctf_data/cap4.txt", status=ERROR
> 09-04 17:49:39.758 2329126 2329126 E PLUGIN/FLT.UTILS.MUXER muxer_upstream_msg_iter_next@muxer.c:452 [muxer] Upstream iterator's next method returned an error: status=ERROR
> 09-04 17:49:39.758 2329126 2329126 E PLUGIN/FLT.UTILS.MUXER validate_muxer_upstream_msg_iters@muxer.c:986 [muxer] Cannot validate muxer's upstream message iterator wrapper: muxer-msg-iter-addr=0x56472970ba30, muxer-upstream-msg-iter-wrap-addr=0x56472970bf20
> 09-04 17:49:39.758 2329126 2329126 E PLUGIN/FLT.UTILS.MUXER muxer_msg_iter_next@muxer.c:1411 [muxer] Cannot get next message: comp-addr=0x56472970ab70, muxer-comp-addr=0x56472970abf0, muxer-msg-iter-addr=0x56472970ba30, msg-iter-addr=0x56472970b950, status=ERROR
> 09-04 17:49:39.758 2329126 2329126 W LIB/MSG-ITER bt_message_iterator_next@iterator.c:861 Component input port message iterator's "next" method failed: iter-addr=0x56472970b950, iter-upstream-comp-name="muxer", iter-upstream-comp-log-level=WARNING, iter-upstream-comp-class-type=FILTER, iter-upstream-comp-class-name="muxer", iter-upstream-comp-class-partial-descr="Sort messages from multiple inpu", iter-upstream-port-type=OUTPUT, iter-upstream-port-name="out", status=ERROR
> 09-04 17:49:39.758 2329126 2329126 W LIB/GRAPH consume_graph_sink@graph.c:469 Component's "consume" method failed: status=ERROR, comp-addr=0x56472970ad30, comp-name="pretty", comp-log-level=WARNING, comp-class-type=SINK, comp-class-name="pretty", comp-class-partial-descr="Pretty-print messages (`text` fo", comp-class-is-frozen=0, comp-class-so-handle-addr=0x56472968f0b0, comp-class-so-handle-path="/usr/local/lib/babeltrace2/plugins/babeltrace-plugin-text.so", comp-input-port-count=1, comp-output-port-count=0
> 09-04 17:49:39.758 2329126 2329126 E CLI cmd_run@babeltrace2.c:2547 Graph failed to complete successfully

I also tried the https://github.com/zephyrproject-rtos/zephyr/blob/main/scripts/tracing/parse_ctf.py, which requires [Babeltrace 2 python3 bindings](https://babeltrace.org/docs/v2.0/python/bt2/). It gives some graph error similar to above:

> 
> Traceback (most recent call last):
>   File "/home/ming/zephyrproject2/zephyr/bld_ctf_reel/../scripts/tracing/parse_ctf.py", line 145, in <module>
>     main()
>   File "/home/ming/zephyrproject2/zephyr/bld_ctf_reel/../scripts/tracing/parse_ctf.py", line 56, in main
>     for msg in msg_it:
>   File "/usr/lib/python3/dist-packages/bt2/trace_collection_message_iterator.py", line 399, in __next__
>     self._graph.run_once()
>   File "/usr/lib/python3/dist-packages/bt2/graph.py", line 154, in run_once
>     utils._handle_func_status(status, 'graph object could not run once')
>   File "/usr/lib/python3/dist-packages/bt2/utils.py", line 140, in _handle_func_status
>     raise bt2._Error(msg)
> bt2.error._Error: graph object could not run once
> ERROR:    [libbabeltrace2] (graph.c:469)

Attached is the trace data.
[ctf_data_reel.zip](https://github.com/zephyrproject-rtos/zephyr/files/9484430/ctf_data_reel.zip)

**Comment by smrtos** [comment]
Attached is the trace data.
[ctf_data_reel.zip](https://github.com/zephyrproject-rtos/zephyr/files/9484430/ctf_data_reel.zip)

**Comment by nashif** [comment]
are you sure you have the latest `../subsys/tracing/ctf/tsdl/metadata` file? ID 32 is defined in the latest file. Please double check.

**Comment by nashif** [comment]
ping

**Comment by nashif** [comment]
My suspecion here is that the data capture is not complete, they way you are making the changes is not ideal, tracing needs to have a dedicated backend. See how this work with qemu which emits the trace to a file under build/, those events you are missing show up correctly.

**Comment by smrtos** [comment]
No time to try it recently. Will take a look.

**Comment by smrtos** [comment]
I did checked the qemu command line in the build folder before.
But no time to further investigate it recently. Will continue the work.
Sorry for the late response.

**Comment by nashif** [comment]
there was a similar report, so there might be an issue here, will continue looking...

**Comment by diocorreia** [comment]
Having similar issue (but with nrf52840), @smrtos did you figure out the problem? I've already tried two releases of Zephyr  (v2.7.0 and 3.2.0) and the issue occurs in both. I've also tried to use TraceCompass, but the outcome is the same (fails when parsing the file).

**Comment by ball-hayden** [comment]
Also seeing issues with invalid CTF traces while trying to open in TraceCompass.

My setup is using the nRF52840DK with the tracing sample and `prj_usb_ctf.conf`.

Please find attached an example (invalid) trace:
[trace.zip](https://github.com/zephyrproject-rtos/zephyr/files/12925768/trace.zip)

**Comment by ball-hayden** [comment]
In my case, the issue was that I hadn't copied the `metadata` file to sit next to the trace.
RTFM. Sorry.
