### ISSUE TITLE
Bluetooth: PTS fails to connect to Zephyr

### ISSUE THREAD

**Issue by MariuszSkamra** [zephyrproject-rtos/zephyr#4989]
HW
- Tester application running on QEMU
- Bluetooth USB dongle or Zephyr based (hci_uart) bt dongle
or 
- Tester combined build on nrf52 board

PTS fails to connect to the Zephyr. Note that only few test cases are failing due to this, the rest of tests is passing. PTS orders IUT to enable advertising, then tries to connect. Connection fails to be established. 

Steps to reproduce:
- Run one of the failing test cases
- PTS will try to connect to the IUT
- Connection will fail (Disconnection with Reason: Connection Failed to be Established)

Regression found in following test cases:
GATT/SR/GAW/BI-01-C
GATT/SR/GAS/BV-01-C

Git bisect testing pointed **a74feaaf557012d42ace232d0411d9275e21e066** as first bad commit. Tests are passing on build before this commit.

I enclose [debug logs](https://pastebin.com/fZfcbVBN), [btmon](https://pastebin.com/X2EPBrUz) and [Protocol Viewer logs](https://drive.google.com/file/d/1hiBc8D0BiKDJA2fUkszQQX16oKoLKDjT/view?usp=sharing) running on current master - new (7f6070fb6c3b5075040c3de7880edaad697de762) and old, before the change (on 7762578de4b7bc5784b08dc0a71a64615d82a471) [debug logs](https://pastebin.com/TE0AeMPv), [btmon](https://pastebin.com/AuDrZdTX), [PV logs](https://drive.google.com/file/d/1ZDLiDuaxHKvkqwVd_Vc6IgqoclmriQD3/view?usp=sharing)

**Comment by kolodgrz** [comment]
This also affects GATT/SR/GAW/BV-02-C, GATT/SR/GAD/BV-01-C

**Comment by MariuszSkamra** [comment]
I tested this with privacy disabled (CONFIG_BT_PRIVACY=n) and it passed

**Comment by MariuszSkamra** [comment]
So there is a connection issue only if privacy is enabled

**Comment by MariuszSkamra** [comment]
Steps to reproduce:
1. Start samples/bluetooth/peripheral application in QEMU
2. Try to connect

Expected result:
Connection successful

Actual result:
Connection failed to be established

**Comment by jhedberg** [comment]
Is this any different from https://github.com/zephyrproject-rtos/zephyr/issues/5486 ?

**Comment by MariuszSkamra** [comment]
Yes, it is. Those tests are related to peripheral role, while in #5486 Zephyr is central

**Comment by MariuszSkamra** [comment]
Tests are passing on QEMU with PTS dongle

**Comment by nashif** [comment]
@MariuszSkamra  any updates?
