### ISSUE TITLE
riscv: Enabling IRQ vector table makes Zephyr unbootable

### ISSUE THREAD

**Issue by stephanosio** [zephyrproject-rtos/zephyr#49903]
**Describe the bug**

Enabling IRQ vector table (`CONFIG_GEN_IRQ_VECTOR_TABLE=y`) for RISC-V causes the firmware image to become unbootable because the IRQ vector table is placed in the `ROM_START` section and, since #49810, the `ROM_START` section precedes the `vectors` section, which contains the start-up code:

https://github.com/zephyrproject-rtos/zephyr/blob/8563744997a057780a30b5566de8acfe699b3f9d/arch/common/CMakeLists.txt#L27-L31

See also https://github.com/zephyrproject-rtos/zephyr/pull/49810#issuecomment-1235684318

**To Reproduce**

```
scripts/twister -v -N -M -s tests/kernel/gen_isr_table/arch.interrupt.gen_isr_table.riscv_direct
```

**Expected behavior**

`vectors` section comes before the IRQ vector table section.

**Impact**

RISC-V images are unbootable with `CONFIG_GEN_IRQ_VECTOR_TABLE=y`

**Logs and console output**

No output (hangs on boot)

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04
 - Toolchain: Zephyr SDK 0.15.0
 - Commit SHA: a5ee862ff0b857ff98357bf5f4e9cd1568c178f3

**Additional context**

The affected test (`arch.interrupt.gen_isr_table.riscv_direct`) will be disabled for now, with a reference to this issue.

This issue should eventually be fixed by placing the `vectors` section through the `zephyr_linker_sources(ROM_START ...)`, as done in the ARM architecture port, such that its order can be adjusted using the `SORT_KEY` parameter.

**Comment by stephanosio** [comment]
cc @msierszulski @carlocaione @tgorochowik @kgugala @pgielda

**Comment by msierszulski** [comment]
Hi @stephanosio, can you please assign me to this issue? I will start working on it as soon as possible.

**Comment by stephanosio** [comment]
> Hi @stephanosio, can you please assign me to this issue? I will start working on it as soon as possible.

Done. Thanks.
