### ISSUE TITLE
RFC: Stable API Change:  SMP (Simple Management Protocol) transport API within MCUMgr drops zephyr_ prefix in functions and type definitions and drop zst parameter from zephyr_smp_transport_out_fn

### ISSUE THREAD

**Issue by de-nordic** [zephyrproject-rtos/zephyr#49962]
## Introduction

The MCUMgr, which used to be external library, used to support multiple operating systems and required implementations of some functions to be provided by operating system it was linked to.
In case of Zephyr port of mcumgr, such functions, and type definitions, would have `zephyr_` prefix.
Since MCUMgr is now Zephyr subsystem, it seems redundant to have `zephyr_` prefix added, for example to SMP Transport API identifiers.
The proposal is to drop the `zephyr_` prefix.

The second part of proposal is to drop `zst ` parameter from `zephyr_smp_transport_out_fn` type, which is type for callback function which is called from inside of MCUMgr to pass `net_buf` type of buffer to a transport providing the callback.
This parameter is no longer needed as  it has never been used wit Zephyr, since we are able to carry transport information within `net_buf` itself.

### Problem description

Redundant prefix and a little bit confusing naming which may suggest that transport service for MCUMgr is provided by Zephyr, which is not true: a transport is registered directly to MCUMgr and transport is a client for Zephyr provided services (like drivers and other APIs).

### Proposed change

Remove the `zephyr_` prefix for transport. The `smp_transport` is enough to distinguish the API, `zephyr_` addition is redundant.
There is exception to naming which is `smp_reassembly`, but this is MCUMgr internal API and its usage out of MCUMgr makes no sense.

### Concerns and Unresolved Questions

User provided transport may require changes, the `zephyr_` prefixed functions have been deprecated but are left there to allow more fluent transition.
Removal of `zst` parameter from `zephyr_smp_transport_out_fn` function is less friendly and will just break user code, until removed.

**Comment by carlescufi** [comment]
Architecture WG meeting:

- No objections
