### ISSUE TITLE
Normalize IEEE802514 driver "raw" mode.

### ISSUE THREAD

**Issue by galak** [zephyrproject-rtos/zephyr#5004]
All the other drivers implement a RAW mode, enabled by a config like IEEE802154_MCR20A_RAW.  We should do this on KW41Z as well.  Eventually at least the config option should get refactored up a level.

**Comment by galak** [comment]
@dleach02 can you take a look at this when you have a few cycles.  @jfischer-phytec-iot might be helpful to ask about exactly what RAW mode is doing/needs since he did something for MCR20A.

**Comment by tbursztyka** [comment]
raw mode is useless but for wpan samples.

**Comment by tbursztyka** [comment]
Actually, I think it's the good occasion to get rid of that awful hack that wpan introduced, I'll investigate.

**Comment by dleach02** [comment]
I'm curious about what this raw mode is? I'll follow up with the Phytek guys to get some insight but my first instinct is similar to @tbursztyka. I prefer seeing systems using a common interface to the driver.

**Comment by tbursztyka** [comment]
see PR #5018  

drivers will still need to implement a little bit of it: it should keep/write the FCS in the net_pkt. That's all.
(no more lqi written in the beginning etc... that was linux / wpan specific.)
