### ISSUE TITLE
syscalls: properly fix how unit testing deals with __syscall

### ISSUE THREAD

**Issue by inakypg** [zephyrproject-rtos/zephyr#5006]
Currently the unit testing build process does not generate syscall stubs
Thus, including common.h generates warnings because we have all the syscall declaration with no definition.
So the current hack on #4887 is not a final solution but a hack.
We are waiting for PR for #4174, that will add native support and will have to implement the same to re-use the solution and then #4887 can be undone.

This issue is opened to keep track of it and not forget #4887 has to be reverted

**Comment by galak** [comment]
Closing this and move to native posix for testing, see #7316.
