### ISSUE TITLE
SMT32: incorrect internal temperature value 

### ISSUE THREAD

**Issue by TDhaouST** [zephyrproject-rtos/zephyr#50152]
**Describe the bug**
 Fix the internal temperature sensor value (Die temp) incorrect when reading internal  temperature from ADC. 

This ticket is to fix the incorrect temperature sensor (Die temp) value in the ADC device-tree node for the stm32 series below:

- stm32U5
- stm32L1
- stm32L4
- stm32L0

Acquired values seems inconsistent and not compatible. Example for the stm32U5 (b_u585i_iot02a), here is the required configuration of the ADC and the die temp nodes:

	adc1: adc@42028000 {
			compatible = "st,stm32-adc";
			reg = <0x42028000 0x400>;
			clocks = <&rcc STM32_CLOCK_BUS_AHB2 0x00000400>;
			interrupts = <37 0>;
			status = "disabled";
			vref-mv = <3300>;
			#io-channel-cells = <1>;
			has-temp-channel;
			has-vref-channel;
			has-vbat-channel;
		};

	die_temp: dietemp {
		compatible = "st,stm32-temp-cal";
		ts-cal1-addr = <0x0BFA0710>;
		ts-cal2-addr = <0x0BFA0742>;
		ts-cal1-temp = <30>;
		ts-cal2-temp = <130>;
		ts-cal-vrefanalog = <3000>;
		ts-cal-resolution = <14>;
		io-channels = <&adc1 19>;
	};
On running sample we get: 

*** Booting Zephyr OS build v3.2.0-rc1-18-g687816ba42c9  ***
STM32 Die temperature sensor test
Current temperature: -173.3 �°C
Current temperature: -126.2 �°C
Current temperature: -128.2 �°C
Current temperature: -128.8 �°C
Current temperature: -128.8 �°C
Current temperature: -126.9 �°C
Current temperature: -126.2 �°C
Current temperature: -126.5 �°C
Current temperature: -126.9 �°C

**To Reproduce**
1. west build -p auto -b nucleo_wl55jc samples/sensor/stm32_temp_sensor/
2. west flash
3. see error

**Logs and console output**
see description

**Environment (please complete the following information):**
 - OS: linux
 - Toolchain Toolchain Zephry SDK 0.15.0
 - latest main

**Comment by erwango** [comment]
Removing STM32WL as this is specific. See #49897

**Comment by FRASTM** [comment]
Regarding the stm32F3 disco.
The mcu is stm32F303VCT6 which refman is [RM0316 Rev 8.0](https://www.st.com/resource/en/reference_manual/rm0316-stm32f303xbcde-stm32f303x68-stm32f328x8-stm32f358xc-stm32f398xe-advanced-armbased-mcus-stmicroelectronics.pdf)  and product spec is [DS9118 Rev 14](https://www.st.com/resource/en/datasheet/stm32f303vc.pdf)
