### ISSUE TITLE
Missing human readable names in names file od deive structure

### ISSUE THREAD

**Issue by asarbs** [zephyrproject-rtos/zephyr#50214]
**Describe the bug**

after commit [dts: bindings: bus labels are now optional](https://github.com/zephyrproject-rtos/zephyr/commit/b200b9a9e034a1c1d7bb8ad229c1bbb187da46e4) human readbel names of device despaired from "name" filed of  
 
```
/**
 * @brief Runtime device structure (in ROM) per driver instance
 */
struct device {
	/** Name of the device instance */
	const char *name;
	/** Address of device instance config information */
	const void *config;
	/** Address of the API structure exposed by the device instance */
	const void *api;
	/** Address of the common device state */
	struct device_state *state;
	/** Address of the device instance private data */
	void *data;
	/** optional pointer to handles associated with the device.
	 *
	 * This encodes a sequence of sets of device handles that have
	 * some relationship to this node. The individual sets are
	 * extracted with dedicated API, such as
	 * device_required_handles_get().
	 */
	Z_DEVICE_HANDLES_CONST device_handle_t *handles;

#ifdef CONFIG_PM_DEVICE
	/** Reference to the device PM resources. */
	struct pm_device *pm;
#endif
};
```

Please also mention any information which could help others to understand
the problem you're facing:
 - Zephyr 0.15.0, NXP 1024. 
 - What have you tried to diagnose or workaround this issue?
 [dts: bindings: bus labels are now optional](https://github.com/zephyrproject-rtos/zephyr/commit/b200b9a9e034a1c1d7bb8ad229c1bbb187da46e4)

**To Reproduce**
1. mkdir build; cd build
2. cmake -DBOARD=board\_xyz
3. make

**Expected behavior**

**Impact**
What impact does this issue have on your progress (e.g., annoyance, showstopper)

**Logs and console output**
If applicable, add console logs or other types of debug information
e.g Wireshark capture or Logic analyzer capture (upload in zip archive).
copy-and-paste text and put a code fence (\`\`\`) before and after, to help
explain the issue. (if unable to obtain text log, add a screenshot)

**Environment (please complete the following information):**
 - OS: (e.g. Linux, MacOS, Windows)
 - Toolchain (e.g Zephyr SDK, ...)
 - Commit SHA or Version used

**Additional context**
Add any other context that could be relevant to your issue, such as pin setting,
target configuration, ...

**Comment by henrikbrixandersen** [comment]
Not sure what you are reporting or asking here. Please read through your report, clarify it where needed, and replace the placeholder texts with actual information. When done, feel free to reopen this issue.
