### ISSUE TITLE
twister: --coverage option does not work for qemu_x86_64 and other boards

### ISSUE THREAD

**Issue by finikorg** [zephyrproject-rtos/zephyr#50257]
I have the latest SDK 0.15.0.
When generating coverage for my board I have 0% hits. I can reproduce this with qemu_x86_64 for example with the command:

`$ twister -T zephyr/samples/hello_world/ --coverage -c -p qemu_x86_64`

**Comment by enjiamai** [comment]
This seems to be duplicated with #50255, could you please closed it, @finikorg ?

**Comment by finikorg** [comment]
> This seems to be duplicated with #50255, could you please closed it, @finikorg ?

My issue is different, I do not see crash, only coverage report incomplete.

**Comment by enjiamai** [comment]
Ok, got it, thanks for clarifying!

**Comment by finikorg** [comment]
> Hi @finikorg , I fixed this by #50477, could you please help review it?

Hi @enjiamai , I verified the issue is fixed with the PR mentioned.
