### ISSUE TITLE
k_poll() documentation is wrong

### ISSUE THREAD

**Issue by andrewboie** [zephyrproject-rtos/zephyr#5026]
The patch https://github.com/zephyrproject-rtos/zephyr/commit/90b471fe4afacd279c9423612b5ea1e40bde3e64?diff=unified
introduced -EINTR return value to k_poll(), but the documentation was not updated to reflect this, and user may not know that it can return something other than 0 or -EAGAIN

**Comment by dbkinder** [comment]
(a quick edit to include/kernel.h and the doxygen comments above k_poll() will address this)
