### ISSUE TITLE
CI failure in v3.1.0-rc2 full run

### ISSUE THREAD

**Issue by fabiobaltieri** [zephyrproject-rtos/zephyr#50374]
https://github.com/zephyrproject-rtos/zephyr/runs/8405077838 full run reports 124 broken tests

Full list of board and tests: https://gist.github.com/fabiobaltieri/5c671f56be012ed88472269f3671ca6e

Groups:

- [x] samples/subsys/logging/syst
  - https://github.com/zephyrproject-rtos/zephyr/issues/50341
- [x] bl5340_dvk_cpuapp
  - https://github.com/zephyrproject-rtos/zephyr/issues/50344
- [x] samples/subsys/usb/dfu and samples/modules/canopennode
  - https://github.com/zephyrproject-rtos/zephyr/issues/50342
- [x] lpcxpresso55s69_ns samples/net/sockets/http_get
  - FLASH overflow `Error: Image size (0x1819e) + trailer (0x1b0) exceeds requested size 0x18000`
  - Error from imgtool, does not trigger the "FLASH overflow" skip
  - Recent change in cbprintf actually goes over the flash size for good, underlying problem is still there but this specific combination should be alright.
  - https://github.com/zephyrproject-rtos/zephyr/issues/50386
- [x] esp32c3_devkitm tests/drivers/build_all/led/drivers.led.build
  - `./scripts/twister -v -n -M -p esp32c3_devkitm -T tests/drivers/build_all/led`
  - `zephyrproject/zephyr/drivers/i2c/i2c_esp32.c:764:2: error: #error "Properties <sda-gpios> and <scl-gpios> are not required for this target."`
  - https://github.com/zephyrproject-rtos/zephyr/pull/50377
- [x] mpfs_icicle tests/kernel/workq/work_queue and qemu_x86_tiny@768 tests/kernel/workq/work_queue
  - https://github.com/zephyrproject-rtos/zephyr/issues/50343
- [ ] fvp_base_revc_2xaemv8a_smp_ns tests/ztest/custom_output
  - `./scripts/twister -v -n -M -p fvp_base_revc_2xaemv8a_smp_ns -T tests/ztest/custom_output`
  - `make: execvp: tools/fiptool/fiptool: Text file busy` can't reproduce locally

**Comment by stephanosio** [comment]
Updated with the links to the relevant issues

**Comment by fabiobaltieri** [comment]
cc @mmahadevan108

**Comment by fabiobaltieri** [comment]
Not sure what to do with the last one, runs fine locally, seems like some race condition in the build scripts, maybe we are trying to build it multiple times in parallel? Guess let's see what we get in the next --all run.
