### ISSUE TITLE
Boot banner can cut through output of shell prompt

### ISSUE THREAD

**Issue by nordicjm** [zephyrproject-rtos/zephyr#50464]
**Describe the bug**
Whilst testing `smp_svr` with a build including many overlay files, this was seen at startup on a module:
```
*** Booting Zephyr OS build v3.2.0-rc2-88-gf7251073c4b6  ***
I: Starting bootloader
I: Primary image: magic=unset, swap_type=0x1, copy_done=0x3, image_ok=0x3
I: Secondary image: magic=unset, swap_type=0x1, copy_done=0x3, image_ok=0x3
I: Boot source: none
I: Swap type: none
I: Bootloader chainload address offset: 0x10000
I: Jumping to the first image slot


ua*** Booting Zephyr OS build v3.2.0-rc2-92-g6030b85f71ce  ***
rt:~$ 
```
The boot banner is output part the way through the shell prompt output.

**To Reproduce**
`cmake -GNinja -DBOARD=nrf5340dk_nrf5340_cpuapp -DOVERLAY_CONFIG="overlay-shell.conf;overlay-shell-mgmt.conf;overlay-bt.conf;overlay-udp.conf" ..` (note: also requires mcuboot for cpuapp and hci_rpmsg for cpunet) then run

**Expected behavior**
The output of the boot banner to not obscure the shell, and ideally, output before the shell prompt starts

**Impact**
Annoyance

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: Zephyr SDK 0.14.2
 - Commit SHA or Version used: 6030b85f71ce05a69d6953f265ae1831a6c67548

**Comment by nordicjm** [comment]
@nordic-krch Is there any reason `CONFIG_LOG_PRINTK` isn't enabled by default if logging is enabled and `CONFIG_PRINTK` is enabled? That avoids this issue

**Comment by nordic-krch** [comment]
The main reason was that logging behaves differently, especially deferred mode where output is delayed. Imo, `CONFIG_LOG_PRINTK=y` could be the default but I guess that  we need broader audience to make that decision. Maybe Architecture working group meeting (@carlescufi).

**Comment by nordicjm** [comment]
I've just tried enabling `CONFIG_LOG_PRINTK` on this issue https://github.com/zephyrproject-rtos/zephyr/issues/38947 and it's magically resolved, so it does seem like defaulting to this option when logging is enabled would help with a few bugs

**Comment by carlescufi** [comment]
> The main reason was that logging behaves differently, especially deferred mode where output is delayed. Imo, `CONFIG_LOG_PRINTK=y` could be the default but I guess that we need broader audience to make that decision. Maybe Architecture working group meeting (@carlescufi).

Can you please post a PR changing the default @nordic-krch? Then we'll drive the discussion in that PR.

**Comment by carlescufi** [comment]
Closing this issue since it's a matter of enabling `CONFIG_LOG_PRINTK`.
