### ISSUE TITLE
document error: getting_started.rst

### ISSUE THREAD

**Issue by zhaozhongchen** [zephyrproject-rtos/zephyr#5047]
In the section **Building without the Zephyr SDK**

is there lost **cd $ZEPHYR_BASE** before *make* ?
and i don't know what the $PWD/kconfig means, is it means $ZEPHYR_BASE/scripts/kconfig ?

```
$ cd $ZEPHYR_BASE
$ mkdir build && cd build
$ cmake $ZEPHYR_BASE/scripts
$ make
$ echo "export PATH=$PWD/kconfig:\$PATH" >> $HOME/.zephyrrc
$ source $ZEPHYR_BASE/zephyr-env.sh
```

**Comment by dbkinder** [comment]
I believe it is correct as written; make is supposed to run in the ``build`` directory, right @SebastianBoe

**Comment by zhaozhongchen** [comment]
@dbkinder But there is no such file named *Makefile* in build directory.

**Comment by zhaozhongchen** [comment]
@dbkinder  sorry, it's my fault. the right way is **cmake $ZEPHYR_BASE/scripts**, but i forgot to type **scripts**

**Comment by dbkinder** [comment]
OK.  We'll close this issue then.
