### ISSUE TITLE
mcumgr: img_mgmt: zephyr_img_mgmt_flash_area_id has wrong slot3 ID

### ISSUE THREAD

**Issue by nordicjm** [zephyrproject-rtos/zephyr#50482]
**Describe the bug**
Lines 139 onwards of zephyr_img_mgmt.c have the following code:
```
#if FIXED_PARTITION_EXISTS(SLOT2_PARTITION)
        case 2:
                fa_id = FIXED_PARTITION_ID(SLOT2_PARTITION);
                break;
#endif
 
#if FIXED_PARTITION_EXISTS(slot3_partition)
        case 3:
                fa_id = FIXED_PARTITION_ID(SLOT3_PARTITION);
                break;
#endif
```

The #if check for slot3 looks to have the wrong case

**Impact**
Probably nil as no boards currently support slot3 images

**Environment (please complete the following information):**
 - Commit SHA or Version used: 6030b85f71ce05a69d6953f265ae1831a6c67548

**Comment by de-nordic** [comment]
Should be fixed, although it is not really a bug, unless somebody changes line 29 of the file where there is this definition:
```
#define SLOT3_PARTITION slot3_partition
```
so unless the line is changed `SLOT3_PARTITION == slot3_partition`.

> Probably nil as no boards currently support slot3 images

You can define 4 slots (2 images) for any board, the mcuboot may not be able to boot it but they will be visible in mcumgr and it will be possible to upload images to them.
The nrf5340dk_nrf5340 may be configured with secondary image being the NET code image.
