### ISSUE TITLE
nxp,mcux-usbd devicetree binding issues

### ISSUE THREAD

**Issue by mbolivar-nordic** [zephyrproject-rtos/zephyr#50506]
**Describe the bug**

The point of a  devicetree binding is to describe hardware and its initial configuration. We have carved out a few exceptions for driver-specific property names prefixed with `zephyr,`. However, we should not be designing devicetree bindings to cater to the software requirements of vendor HALs.

This USB device driver binding has a name that seems to specifically refer to the HAL itself, not the actual hardware. It also has problematic properties, such as `usb-controller-index`, added in 3a7c719fb45ea33f35a6464c8bbaa736ab6fc8cb.

**Expected behavior**

Devicetree bindings that reflect the hardware, not the software. Removal of this binding and replacement with individual bindings for the IP blocks in question, as many as needed. Removal of HAL-specific configuration properties.

**Comment by mmahadevan108** [comment]
@mbolivar-nordic. I am looking to address this change as part of an updated MCUX USB driver that would use the new USB framework.
