### ISSUE TITLE
Non-existing test cases reported as "Skipped" with reason  “No results captured, testsuite misconfiguration?” in test report

### ISSUE THREAD

**Issue by mengxianglinx** [zephyrproject-rtos/zephyr#50515]
**Describe the bug**
Some test cases reported as Skipped even they never have been compiled into binary.
It happens on all platforms.

Steps to reproduce the behavior, take nsim_em as an example
1.  twister -p nsim_em -T tests/
in twister_report.xml, following test cases labeled as skipped with “No results captured, testsuite misconfiguration?”
libraries.picolibc.sprintf.EOF
libraries.picolibc.sprintf_new.sprintf_misc
libraries.picolibc.sprintf_new.vsnprintf
libraries.picolibc.sprintf_new.sprintf_string
libraries.picolibc.sprintf_new.vprintf
libraries.picolibc.sprintf_new.snprintf
libraries.picolibc.sprintf_new.sprintf_double
libraries.picolibc.sprintf_new.sprintf_integer
libraries.picolibc.sprintf_new.print
libraries.picolibc.sprintf_new.fprintf
libraries.picolibc.sprintf_new.put
libraries.picolibc.sprintf_new.vsprintf
libraries.picolibc.sprintf_new.fwrite
libraries.picolibc.sprintf_new.vfprintf
testing.ztest.base.verbose_0.fixture_created_and_initialized
testing.ztest.base.verbose_0_userspace.fixture_created_and_initialized
testing.ztest.base.verbose_1.fixture_created_and_initialized
testing.ztest.base.verbose_2.fixture_created_and_initialized

Actually, in handler.log of libraries.picolibc.sprintf, there is no test_EOF(), likewise in handler.log of libraries.picolibc.sprintf_new, there no test case like test_sprintf_misc, test_vsnprintf, test_sprintf_string....., but they are listed in test report as skipped cases.

**Environment (please complete the following information):**
 - OS: (Linux)
 - Toolchain (Zephyr SDK-0.15.0)
 - Commit SHA or Version used: main line

**Comment by mengxianglinx** [comment]
As of now, there is three kind of cases cause this kind of skip:
1) Test log is lost in handler.log. for example, test case shell.core.cmd_history on acrn_ehl_crb, output of this case is not in handler.log
2) If test cases call k_oops(), panic() which cause fatal error, test case actually passed, but the handler.log is not complete, the test report is not ended as expected.
3) If test case source file is orgnized as
#ifdef CONFIG_XXX
test_a();
test_b();
#else
test_c();
test_d();
#endif
for test suite with CONFIG_XXX, test_c(), test_d() will be reported as skipped, even there are never run. likewise for test suite without CONFIG_XXX, test_a(), test_b() are reported as skipped.

**Comment by nordicjm** [comment]
CC @PerMac

**Comment by smrtos** [comment]
Should be fixed by https://github.com/zephyrproject-rtos/zephyr/pull/49619
