### ISSUE TITLE
[Coverity CID: 179254] Possible Control flow issues in /samples/net/zperf/src/zperf_udp_receiver.c

### ISSUE THREAD

**Issue by Shilpashree3lc** [zephyrproject-rtos/zephyr#5055]
Static code scan issues seen in File: /samples/net/zperf/src/zperf_udp_receiver.c
 Category: Possible Control flow issues
 Function: zperf_rx_thread
 Component: Samples
 CID: 179254
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by jukkar** [comment]
This is false positive.
