### ISSUE TITLE
samples/drivers/can/counter fails in twister for native_posix

### ISSUE THREAD

**Issue by martinjaeger** [zephyrproject-rtos/zephyr#50570]
**Describe the bug**

`samples/drivers/can/counter` works when run using west, but fails in twister with a timeout.

**To Reproduce**

Set `can_loopback0` to `status = "okay"` in devicetree and run:

```
west build -b native_posix -t run samples/drivers/can/counter
```
It works with the following output:
```
*** Booting Zephyr OS build v3.2.0-rc2-183-g5af0fbc2e302  ***
Change LED filter ID: 0
Finished init.
Counter filter id: 1
Counter received: 0
Counter received: 1
Counter received: 2
Counter received: 3
Counter received: 4
```

Now try with twister:
```
scripts/twister -p native_posix -T samples/drivers/can/counter
```
It fails with a timeout. The file `handler.log` is empty.
```
ERROR   - native_posix              samples/drivers/can/counter/sample.drivers.can.counter FAILED: Timeout
```

**Expected behavior**

The sample runs successfully in Twister.

**Impact**

Annoyance because the board has to be excluded from CI and the sample cannot be tested.

**Environment (please complete the following information):**

SHA: 5af0fbc2e30250968289ff4d3ffb69ea45f41d37

**Additional context**

Realized this during work on #50530

**Comment by henrikbrixandersen** [comment]
I'll look into this. The CAN counter sample runs fine in twister on regular hardware boards.
