### ISSUE TITLE
ESP32 GPIO driver 

### ISSUE THREAD

**Issue by sam131208** [zephyrproject-rtos/zephyr#50615]
**Describe the bug**
The input configuration of GPIO34~GPIO39 cannot be performed. When the following code block is executed, it ends abnormally and return the value -134.

The following code is located on line 119 of gpio_esp32.c。

 	if (flags & GPIO_PULL_UP) {
		if (!rtc_gpio_is_valid_gpio(io_pin) || SOC_GPIO_SUPPORT_RTC_INDEPENDENT) {
			gpio_ll_pullup_en(&GPIO, io_pin);
		} else {
                   #if SOC_RTCIO_INPUT_OUTPUT_SUPPORTED
			int rtcio_num = rtc_io_num_map[io_pin];

			if (rtc_io_desc[rtcio_num].pullup) {
				rtcio_hal_pullup_enable(rtcio_num);
			} else {
				ret = -ENOTSUP;
				goto end;
			}
                   #endif
		}
	} else {
		if (!rtc_gpio_is_valid_gpio(io_pin) || SOC_GPIO_SUPPORT_RTC_INDEPENDENT) {
			gpio_ll_pullup_dis(&GPIO, io_pin);
		} else {
                   #if SOC_RTCIO_INPUT_OUTPUT_SUPPORTED
			int rtcio_num = rtc_io_num_map[io_pin];

			if (rtc_io_desc[rtcio_num].pulldown) {
				rtcio_hal_pullup_disable(rtcio_num);
			} else {
				ret = -ENOTSUP;
				goto end;
			}
                   #else
			ret = -ENOTSUP;
			goto end;
                   #endif
		}
	}

**Environment (please complete the following information):**
 - OS:  Windows
 - Toolchain zephyr-sdk-0.15.0
 - zephyr version build v3.2.0-rc2-178-g55c4e06b3563

**Comment by henrikbrixandersen** [comment]
@sam131208 Please revisit the description of this issue and fix the formatting to make it readable.

**Comment by sam131208** [comment]
@henrikbrixandersen format fixed。

**Comment by sylvioalves** [comment]
@sam131208  thanks for reporting. Indeed there is an issue in there.
