### ISSUE TITLE
k_heap_aligned_alloc does not handle a timeout of K_FOREVER correctly

### ISSUE THREAD

**Issue by jshoen** [zephyrproject-rtos/zephyr#50611]
When K_FOREVER is passed the return value of z_timeout_end_calc is MAX_UINT64 which equates to -1 when treated as an int64_t.  This causes the end-now check to always return < 0.

The timeout handing code in k_mem_pool_alloc appears to be correct.  k_heap_aligned_alloc should be updated with similar logic.

This was found in Zephyr 2.4, but the issue is still present in current code.

**Comment by henrikbrixandersen** [comment]
@jshoen Can you submit a PR for fixing this?

**Comment by jshoen** [comment]
I can submit a PR, but may take me some time.  I have not submitted to zephyr before.

**Comment by jshoen** [comment]
PR Submitted.  PR Number 50731

**Comment by stephanosio** [comment]
Setting this issue to high priority since it is a kernel bug and we definitely want it fixed in this release.
