### ISSUE TITLE
nominate me as zephyr contributor

### ISSUE THREAD

**Issue by shuai1x** [zephyrproject-rtos/zephyr#50632]
# Background

The [TSC Project Roles] defines the main roles for the Zephyr Project, including
Maintainer, Collaborator, and Contributor.

By default anyone that contributes code or documentation is a Contributor, but
with the lowest [GitHub Permission Level] of Read. For example, Contributors
with Read permission do not have the permission to add reviewers to a pull
request.

Use this template to nominate a GitHub user for an elevated permission level in
the Contributor role.

# Nomination

## GitHub User

Provide the following information about the GitHub user:

1. Full Name: Shuai Zhao
1. GitHub username: shuai1x
1. Organization (optional): Intel

## Supporting Documents

Add links to 3-5 GitHub pull requests, in the Zephyr project, authored or
reviewed by the GitHub user that demonstrate the user's dedication to the
Zephyr project.

https://github.com/zephyrproject-rtos/zephyr/pulls?q=shuai1X

**Comment by nashif** [comment]
triage role granted.
