### ISSUE TITLE
Please Add __heapstats() to stdlib.h

### ISSUE THREAD

**Issue by jwestmoreland** [zephyrproject-rtos/zephyr#50631]
Hello,

As an enhancement - can __heapstats() be added to stdlib.h?

A full implementation of __heapstats() would be helpful - of course, a pointer to the active heap to be interrogated will be required - for certain processor architectures like the M33 - a first round of this so to speak would be only for the NS part of the heap unless a global heap is easily interrogated in both secure and NS modes.

I've tried sys_heap_runtime_stats_get() - but get compile errors (running SDK v1.9.1 on nRF9160).

Reference to ARM's __heapstats() page is here:
https://developer.arm.com/documentation/dui0475/m/the-c-and-c---library-functions-reference/--heapstats--?lang=en

Thanks In Advance,
John W.

**Comment by stephanosio** [comment]
> As an enhancement - can __heapstats() be added to stdlib.h?

`__heapstats()` is not a standard C function and will not be added to the C standard library (it seems to be some random function Keil decided to add).

> I've tried sys_heap_runtime_stats_get() - but get compile errors (running SDK v1.9.1 on nRF9160).

Please enable `CONFIG_SYS_HEAP_RUNTIME_STATS`.
