### ISSUE TITLE
MEC15xx/MEC1501: UART and and special purpose pins missing pinctrl configuration

### ISSUE THREAD

**Issue by fabiobaltieri** [zephyrproject-rtos/zephyr#50665]
Known issue affecting `mec1501modular_assy6885` and `mec15xxevb_assy6853`: to facilitate the pinmux subsystem deprecation, the custom pin configuration for these two boards has been removed in https://github.com/zephyrproject-rtos/zephyr/pull/48893 and the boards have been excluded from CI. Due to this the UART and other special purpose peripherals on those boards are not functional, see https://github.com/zephyrproject-rtos/zephyr/pull/48893#issuecomment-1254121986 for more details.

TODO: after the UART pinmux have been implemented, revert b3ead37efaa55e20bb66e0920211c68a4bcf74c2 to include those boards in the CI again.

**Comment by jvasanth1** [comment]
uart for mec15xx pinctrl is addressed in PR #50934  and merged
