### ISSUE TITLE
net: tests/net/ieee802154/l2/net.ieee802154.l2 failed on reel_board due to build failure

### ISSUE THREAD

**Issue by shuai1x** [zephyrproject-rtos/zephyr#50732]
**Describe the bug**
When delete the platform_allow in testcase.yaml, we can run tests/net/ieee802154/l2/net.ieee802154.l2 on reel_board.
On reel_board platform,  tests/net/ieee802154/l2/net.ieee802154.l2 failed due to build failure.

Please also mention any information which could help others to understand
the problem you're facing:
 - reel_board
 - tests/net/ieee802154/l2/net.ieee802154.l2 Build failure

**To Reproduce**
1. west build -p auto -b reel_board tests/net/ieee802154/l2
2. see error

**Logs and console output**
```
-- west build: building application
[1/377] Preparing syscall dependency handling

[2/377] Generating include/generated/version.h
-- Zephyr version: 3.2.99 (/home/zhao/zephyrproject/zephyr), build: zephyr-v3.2.0-512-gb09973c460e3
[335/377] Building C object modules/mbedtls/CMakeFiles/module...e/zhao/zephyrproject/modules/crypto/mbedtls/library/rsa.c.obj
/home/zhao/zephyrproject/modules/crypto/mbedtls/library/rsa.c: In function 'myrand':
/home/zhao/zephyrproject/modules/crypto/mbedtls/library/rsa.c:2356:21: warning: implicit declaration of function 'rand'; did you mean 'myrand'? [-Wimplicit-function-declaration]
 2356 |         output[i] = rand();
      |                     ^~~~
      |                     myrand
[367/377] Linking C executable zephyr/zephyr_pre0.elf

[371/377] Linking C executable zephyr/zephyr_pre1.elf

[377/377] Linking C executable zephyr/zephyr.elf
Memory region         Used Size  Region Size  %age Used
           FLASH:      179396 B         1 MB     17.11%
             RAM:       57548 B       256 KB     21.95%
        IDT_LIST:          0 GB         2 KB      0.00%
```

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain - SDK 15.0

**Comment by galak** [comment]
This tests isn't valid to run on real hardware so this isn't an issue.

See commit f1e059a3e54684f7ec1d6b94ba7298f925705f11
