### ISSUE TITLE
Stale kernel memory pool API references

### ISSUE THREAD

**Issue by stephanosio** [zephyrproject-rtos/zephyr#50746]
**Describe the bug**

There are various stale references to the kernel memory pool API (`k_mem_pool`) in the current Zephyr codebase.

The `k_mem_pool` support was (supposed to be) removed in the Zephyr v2.5.0 release as part of #28611, but it seems to have missed a few references.

```
$ git grep k_mem_pool
cmake/linker_script/common/common-ram.cmake:zephyr_iterable_section(NAME k_mem_pool GROUP DATA_REGION ${XIP_ALIGN_WITH_INPUT} SUBALIGN 4)
doc/kernel/usermode/memory_domain.rst:must assign themselves to a resource pool, which is a k_mem_pool object.
... (release notes stuff)
include/zephyr/kernel.h:struct k_mem_pool;
include/zephyr/kernel.h: * k_mem_pool_malloc().
include/zephyr/kernel/mempool_heap.h:/* Compatibility implementation of a k_mem_pool backend in terms of a
include/zephyr/linker/common-ram.ld:    ITERABLE_SECTION_RAM_GC_ALLOWED(k_mem_pool, 4)
scripts/pylib/twister/twisterlib/size_calc.py:        "k_mem_pool_area",
soc/xtensa/esp32_net/linker.ld:    Z_LINK_ITERABLE_GC_ALLOWED(k_mem_pool);
tests/benchmarks/app_kernel/src/master.h:extern struct k_mem_pool DEMOPOOL;
```

**Comment by stephanosio** [comment]
cc @andyross @peter-mitsis @dcpleung

**Comment by stephanosio** [comment]
Keeping this open since there are still leftovers that require more intrusive cleaning as noted in https://github.com/zephyrproject-rtos/zephyr/pull/50749#issue-1389197533.

> [1] There are also k_mem_block and all the mailbox "memory block" support bits, which were also supposed to be removed in https://github.com/zephyrproject-rtos/zephyr/pull/28611 (see https://github.com/zephyrproject-rtos/zephyr/commit/c844bd87b3fdb059d7a81dcb02777fad558f77db), but it failed to do so completely. This is going to be done in the next release.

**Comment by sylvioalves** [comment]
@stephanosio `soc/xtensa/esp32_net/linker.ld` is outdated and will be updated soon.
