### ISSUE TITLE
MCUboot update breaks compilation for boards without CONFIG_WATCHDOG=y

### ISSUE THREAD

**Issue by henrikbrixandersen** [zephyrproject-rtos/zephyr#50754]
**Describe the bug**
The MCUboot update in cfc96eaacceeaa09bb19d8df35af7bdbbf7af189 breaks compilation for at least the `twr_ke18f` board (and likely all other boards having a DTS `watchdog0` alias with status `okay` but not setting `CONFIG_WATCHDOG=y`).

**To Reproduce**
1. `west build -b twr_ke18f ../bootloader/mcuboot/boot/zephyr/`
2. See error:

```
[ 95%] Linking C executable zephyr_pre0.elf
/opt/zephyr-sdk/0.15.0/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/12.1.0/../../../../arm-zephyr-eabi/bin/ld.bfd: ../app/libapp.a(main.c.obj): in function `main':
/home/hebad/Projects/zephyrproject/bootloader/mcuboot/boot/zephyr/main.c:612: undefined reference to `__device_dts_ord_105'
/opt/zephyr-sdk/0.15.0/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/12.1.0/../../../../arm-zephyr-eabi/bin/ld.bfd: ../app/libapp.a(loader.c.obj): in function `boot_copy_region':
/home/hebad/Projects/zephyrproject/bootloader/mcuboot/boot/bootutil/src/loader.c:1035: undefined reference to `__device_dts_ord_105'
collect2: error: ld returned 1 exit status
make[2]: *** [zephyr/CMakeFiles/zephyr_pre0.dir/build.make:120: zephyr/zephyr_pre0.elf] Error 1
make[1]: *** [CMakeFiles/Makefile2:2921: zephyr/CMakeFiles/zephyr_pre0.dir/all] Error 2
make: *** [Makefile:91: all] Error 2
FATAL ERROR: command exited with status 2: /home/hebad/Projects/zephyrproject/venv/bin/cmake --build /home/hebad/Projects/zephyrproject/zephyr/build
```

**Expected behavior**
MCUboot compiles without errors.

**Impact**
Unable to build MCUboot for affected boards.

**Environment (please complete the following information):**
 - OS: Ubuntu Linux 20.04 LTS
 - Toolchain: Zephyr SDK v0.15.0
 - Commit SHA: a5ce3da6ab425d104d73d34f47352ae721c5d216

**Comment by henrikbrixandersen** [comment]
This comes from `CONFIG_BOOT_WATCHDOG_FEED` now defaulting to `y` regardless of the selected SoC family (and even more important, regardless if `CONFIG_WATCHDOG` was enabled.

Comparing the MCUboot repository changes in #50148 reveals that `CONFIG_WATCHDOG=y` was added for the boards enabled in the sample.

**Comment by bbilas** [comment]
> This comes from `CONFIG_BOOT_WATCHDOG_FEED` now defaulting to `y` regardless of the selected SoC family (and even more important, regardless if `CONFIG_WATCHDOG` was enabled).
> 
> Comparing the MCUboot repository changes in #50148 reveals that `CONFIG_WATCHDOG=y` was added for the boards enabled in the sample.

For some reason, it detects `DT_NODE_HAS_STATUS(DT_ALIAS(watchdog0), okay)` even though there is no watchdog alias in the DTS.

<pre>
	aliases {
		led0 = &orange_led;
		led1 = &yellow_led;
		led2 = &green_led;
		led3 = &red_led;
		led4 = &tri_red_led;
		led5 = &tri_green_led;
		led6 = &tri_blue_led;
		pwm-led0 = &orange_pwm_led;
		pwm-led1 = &yellow_pwm_led;
		pwm-led2 = &green_pwm_led;
		pwm-led3 = &red_pwm_led;
		red-pwm-led = &tri_red_pwm_led;
		green-pwm-led = &tri_green_pwm_led;
		blue-pwm-led = &tri_blue_pwm_led;
		sw0 = &user_button_3;
		sw1 = &user_button_2;
		magn0 = &fxos8700;
		accel0 = &fxos8700;
	};
</pre>

**Comment by henrikbrixandersen** [comment]
> For some reason, it detects `DT_NODE_HAS_STATUS(DT_ALIAS(watchdog0), okay)` even though there is no watchdog alias in the DTS.

No. The alias is defined at the SoC level. The issue here is that MCUboot is trying to obtain a reference to that device even with `CONFIG_WATCHDOG=n`.

**Comment by nvlsianpu** [comment]
I will make CONFIG_BOOT_WATCHDOG_FEED dependent on CONFIG_WATCHDOG.

**Comment by bbilas** [comment]
> > For some reason, it detects `DT_NODE_HAS_STATUS(DT_ALIAS(watchdog0), okay)` even though there is no watchdog alias in the DTS.
> 
> No. The alias is defined at the SoC level. The issue here is that MCUboot is trying to obtain a reference to that device even with `CONFIG_WATCHDOG=n`.

Ouch, I have not completely thought that it can be taken from the SoC level... I feel so stupid right now.

**Comment by nvlsianpu** [comment]
fix proposal : https://github.com/zephyrproject-rtos/mcuboot/pull/92
