### ISSUE TITLE
tests: kernel: timer: timer_behavior: kernel.timer.timer - SRAM overflow on nrf5340dk_nrf5340_cpunet and nrf52dk_nrf52832

### ISSUE THREAD

**Issue by nordic-piks** [zephyrproject-rtos/zephyr#50843]
**Describe the bug**
The tests:
tests/kernel/timer/timer_behavior/kernel.timer.timer

Does not fit into SRAM - SRAM overflow.

Observed at:
- nrf52dk_nrf52832
- nrf5340dk_nrf5340_cpunet

**To Reproduce**
1. have nrf52dk_nrf52832 connected
2. go to your zephyr dir
3. call ./scripts/twister -T tests/kernel/common -p nrf52dk_nrf52832 --device-testing --device-serial /dev/ttyACM0 -v --inline-logs
4. See console output with error

**Expected behavior**
Valid tests output

**Impact**
Not clear

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04.1 LTS
 - Toolchain Zephyr SDK 0.14.1
 - Commit SHA or Version used: v3.2.0-rc3-98-g1c953834d671

**Comment by stephanosio** [comment]
SRAM overflow is not a bug.
