### ISSUE TITLE
Error while installing python dependecies

### ISSUE THREAD

**Issue by WajahatRiaz** [zephyrproject-rtos/zephyr#50872]
I'm setting up zephyr for my eclipse IDE using the guide from the following link:
[https://www.nxp.com/docs/en/training-reference-material/BUILD-YOUR-FIRST-ZEPHYR-APPLICATION-ON-I.MX-RT.pdf](url)

I use the following command to install dependecies:
`pip3 install -r zephyr/scripts/requirements.txt
`

But i'm getting the following error message:
<img width="731" alt="image" src="https://user-images.githubusercontent.com/61377755/193403499-f14d1c4c-5799-4daa-892f-0c6e3a9d0d65.png">

**Comment by WajahatRiaz** [comment]
I believe I found a solution. It's trivial but solves the issue. Open the requirements.tx file on your windows and simply change **hub==2.0** to **hub==3.0.0**. Then save the file and run the following command:
`pip3 install --user -r zephyrproject/zephyr/scripts/requirements.txt`

**Comment by carlescufi** [comment]
This report is incorrect:

- `hub` is not a requirement, direct or indirect, in Zephyr
- `hub` is now called `deeplake`, and again, is not a requirement
