### ISSUE TITLE
no makefile in zephyr/samples/bluetooth/mesh examples

### ISSUE THREAD

**Issue by vikrant8051** [zephyrproject-rtos/zephyr#5090]
no makefile in zephyr/samples/bluetooth/mesh examples

in this https://github.com/zephyrproject-rtos/zephyr/releases/tag/v1.10.0-rc1

**Comment by SebastianBoe** [comment]
That is intentional.

Zephyr version 1.10 has migrated to CMake. See https://lists.zephyrproject.org/pipermail/zephyr-users/2017-November/000772.html

**Comment by vikrant8051** [comment]
Thanks for reply !!

http://docs.zephyrproject.org/boards/arm/nrf52840_pca10056/doc/nrf52840_pca10056.html

cd $ZEPHYR_BASE/samples/bluetooth/mesh

# Make a build directory, and use cmake to configure a Make-based build system:
$ mkdir build && cd build
$ cmake -DBOARD=nrf52840_pca10056 ..
