### ISSUE TITLE
RFC: Stable API change: Rework and improve mcumgr callback system

### ISSUE THREAD

**Issue by nordicjm** [zephyrproject-rtos/zephyr#50923]
## Introduction

mcumgr has a callback system which allows applications to register for events and get callbacks on those events, this allows the application to know the current status of e.g. a firmware update or block access to a file.

### Problem description

The problem with the current callback method is that there is not a single callback system, there are 3 or 4 entirely separate callback systems which make it hard to use and do not offer much flexibility. They also cannot be properly excluded from the code to reduce code size if they are not required.

### Proposed change

The proposed change is shown in https://github.com/zephyrproject-rtos/zephyr/pull/50578
Essentially, it replaces the multiple different callback systems and their flaws with a single callback system that can register (or unregister) multiple callbacks, with each callback using a bitmask of values for which events it wants called for. This can pass back data to the notification function which is specific to that callback, it also allows returning a status to the management caller which, optionally, can be used to reject or accept an action (for example, if a firmware upload is started, writing data can be restricted to conditions that the user application specifies). This new system can be customised by Kconfig options to select which events are available for callbacks (by default, the notification system is disabled).

For this new system to become the standard, the old system needs to be removed, hence the stable API change.

## Alternatives

Keeping the current disparate broken system.

**Comment by ExtremeGTX** [comment]
Will this fix https://github.com/zephyrproject-rtos/zephyr/issues/36882#issue-941861859?

when console, shell and mcumgr are sharing the same serial connection, the logs can stop while there is a file transfer and resume again when file transfer is done?

Thanks

**Comment by nordicjm** [comment]
> Just asking, Will this fix https://github.com/zephyrproject-rtos/zephyr/issues/36882#issue-941861859?

No, you can use this to fix that specific issue: https://github.com/zephyrproject-rtos/zephyr/pull/50945
The fundamental issue with it is that there might be other filesystem errors that are emitted that it won't fix, that and the actual issue lies with the `mcumgr` go application itself, not the mcumgr code in zephyr. The mcumgr response is received fully by the application, it should be searching for the mcumgr over console start header bytes (0x06, 0x09) which it does not do, therefore the implementation in https://github.com/apache/mynewt-newtmgr/ is to blame

**Comment by carlescufi** [comment]
Architecture WG meeting:

- @nashif raises the fact that, yet again, we will break out-of-tree users, but this is how the process is designed right now
- Separate discussion to improve the process and reduce out-of-tree breakage will take place
- No objections to this particular change
