### ISSUE TITLE
Default parition addressing for nrf52_pca10040 is incompatible

### ISSUE THREAD

**Issue by jsiloto** [zephyrproject-rtos/zephyr#5107]
After loading the https://github.com/runtimeco/mcuboot zephyr sample:
[MCUBOOT] [INF] main: Starting bootloader
[MCUBOOT] [ERR] flash_area_get_sectors: area 1 size 0x32000 not divisible by sector size 0xd000
[MCUBOOT] [ERR] main: Unable to find bootable image

**Comment by nvlsianpu** [comment]
This is caused by https://runtimeco.atlassian.net/browse/MCUB-90 bug

**Comment by nvlsianpu** [comment]
This is not zephyr's bug. Compiling with CONFIG_FLASH_PAGE_LAYOUT=y will solve this for sure.
