### ISSUE TITLE
yaml: fix key/value syntax to 'mapping' instead of 'series' 

### ISSUE THREAD

**Issue by erwango** [zephyrproject-rtos/zephyr#5109]
According to yaml syntaxic rules, '- attribute' should be used for series (list of single element)
and 'attribute' (w/o hyphen) should be used for 'mapping' (key/value couple),
When treated by yaml python library, yaml mappings are converted to python type 'dict'
while series are converted to python type 'list'.

In some yaml files, we're using hyphen before key/value element.
They are then converted to 'list' of key/value element instead of 'dict' which is not ideal to deal with in python.

Rework yaml files to be syntaxically correct and do the modifications (which should be code simplification) in scripts that deal with the yaml files.

**Comment by erwango** [comment]
Impacted:
-dts/bindings/\*/\*.yaml  -> fixed by #5076
-samples/\*/\*.yaml
-tests/\*/\*.yaml

**Comment by galak** [comment]
Can we write a script or something to modify the yaml files?

**Comment by nashif** [comment]
> Can we write a script or something to modify the yaml files?

i have a script already and will take  care of that.
