### ISSUE TITLE
Bluetooth: l2cap needs check rx.mps when le_recv

### ISSUE THREAD

**Issue by yajunzhi** [zephyrproject-rtos/zephyr#51174]
**Describe the bug**
When a le dynamic channel connected on l2cap, and the mtu value is bigger than BUF_ACL_RX_SIZE, mps value is smaller than BUF_ACL_RX_SIZE. Then receiving l2cap packet from remote device, it could be received, but expect discard this too large packet according protocol.

So, in l2cap_chan_le_recv() function, should add some code to check the buffer length, refer the following,

```
 static void l2cap_chan_le_recv(struct bt_l2cap_le_chan *chan,
                               struct net_buf *buf) {
    ...
    **if (buf->len > chan->rx.mps) {
        BT_ERR("Invalid mps length");
        bt_l2cap_chan_disconnect(&chan->chan);
        return;
    }**

    /* Check if segments already exist */
    if (chan->_sdu) {
        l2cap_chan_le_recv_seg(chan, buf);
        return;
    }
    ...
}

```

**Comment by carlescufi** [comment]
@yajunzhi feel free to open a Pull Request to fix this.

**Comment by kruithofa** [comment]
May be related to #52228

**Comment by jori-nordic** [comment]
Thanks for the code snippet @yajunzhi ! I opened a PR (https://github.com/zephyrproject-rtos/zephyr/pull/52631) to fix this issue. 
Closing it as duplicate, since https://github.com/zephyrproject-rtos/zephyr/issues/52228 has more details.
