### ISSUE TITLE
[Coverity CID: 179984] Memory - corruptions in /drivers/ethernet/eth_mcux.c

### ISSUE THREAD

**Issue by Shilpashree3lc** [zephyrproject-rtos/zephyr#5118]
Static code scan issues seen in File: /drivers/ethernet/eth_mcux.c
 Category: Memory - corruptions
 Function: eth_0_init
 Component: Drivers
 CID: 179984
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by lpereira** [comment]
This looks like a non-issue: ENET_GetDefaultConfig() initializes ringNum from a enet_config_t to 1, and between eth_0_init() calling it and all the functions called by ENET_Init() using the buffer_config struct as an array, nothing changes the ringNum value. I'm closing this as intentional.
