### ISSUE TITLE
Bluetooth: Host: `bt_le_oob_get_local` gives incorrect address

### ISSUE THREAD

**Issue by alwa-nordic** [zephyrproject-rtos/zephyr#51208]
`bt_le_oob_get_local` gives incorrect address when using the extended advertisement code paths. (i.e. `(IS_ENABLED(CONFIG_BT_EXT_ADV) && BT_DEV_FEAT_LE_EXT_ADV(bt_dev.le.features))` is true.)

_Originally posted by @joerchan in https://github.com/zephyrproject-rtos/zephyr/discussions/50967#discussioncomment-3850650_

When you start an advertiser using the legacy API (`bt_le_adv_*`) then the OOB information is provided by `bt_le_oob_get_local`. When you start an advertiseng using the extended API then the OOB informartion is provided by `bt_le_ext_adv_oob_get_local`.

The new bug now is that `bt_le_oob_get_local` does not return the RPA address of the advertiser.

You can verify this bug like this:
```bash
west build -b nrf52840dk_nrf52840 tests/bluetooth/shell  -- -DCONFIG_BT_PRIVACY=y -DCONFIG_BT_LOG_SNIFFER_INFO=y -DCONFIG_BT_RPA_TIMEOUT=30
```

Using the nRF Sniffer for Bluetooth LE.
Add the printed IRK to the sniffer, and select follow IRK.

```
uart:~$ bt advertise on
Advertising started
[00:00:10.378,570] <inf> bt_id: bt_id_set_adv_private_addr: RPA: 5E:0B:7D:F9:9A:D1
uart:~$ bt oob
OOB data:
addr                          random                           confirm                         
   4E:44:19:A9:44:12 (random) 015ce2d5e52416dfc3f54a562822b10d c47cb850fd05737e21eb502cd65c8003
[00:00:23.610,137] <inf> bt_id: bt_id_set_adv_private_addr: RPA: 6D:28:FE:FE:A3:61
[00:00:23.610,717] <inf> bt_id: bt_id_set_private_addr: RPA: 4E:44:19:A9:44:12
```

The advertiser starts using `5E:0B:7D:F9:9A:D1`. When calling `bt_le_oob_get_local` it returns `4E:44:19:A9:44:12 (random)`, but is advertising using `6D:28:FE:FE:A3:61`.

On zephyr 3.0.0 release this works as expected.

Reverting the fix https://github.com/zephyrproject-rtos/zephyr/commit/6c40427931dba65092d0eb050a2ed7e9e8069845 shows that the RPA is not updated, neither on calling bt_le_oob_get_local, or on an RPA timeout.

https://github.com/zephyrproject-rtos/zephyr/issues/51208#tasklist-block-11cca9a8-bf0c-4ea2-b69b-3116fb495c40

**Comment by cvinayak** [comment]
Course of action, in a PR revert 6c40427931dba65092d0eb050a2ed7e9e8069845 and fix the changes to `le_rpa_invalidate` that was done in 4e924b6b1f4d8c9acd3fe2501b06572ddf4d4ed3
