### ISSUE TITLE
[Coverity CID: 179981] Incorrect expression in /drivers/ieee802154/ieee802154_kw41z.c

### ISSUE THREAD

**Issue by Shilpashree3lc** [zephyrproject-rtos/zephyr#5121]
Static code scan issues seen in File: /drivers/ieee802154/ieee802154_kw41z.c
 Category: Incorrect expression
 Function: kw41z_phy_abort
 Component: Drivers
 CID: 179981
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by lpereira** [comment]
False positive.  This is a hardware register and code has a comment already.
