### ISSUE TITLE
[Coverity CID: 179980] Integer handling issues in /subsys/bluetooth/host/mesh/friend.c

### ISSUE THREAD

**Issue by Shilpashree3lc** [zephyrproject-rtos/zephyr#5122]
Static code scan issues seen in File: /subsys/bluetooth/host/mesh/friend.c
 Category: Integer handling issues
 Function: bt_mesh_friend_req
 Component: Bluetooth
 CID: 179980
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by jhedberg** [comment]
Already fixed in the master branch
