### ISSUE TITLE
LE Audio: Always require BT_AUDIO_CONTEXT_TYPE_UNSPECIFIED for BAP

### ISSUE THREAD

**Issue by Thalley** [zephyrproject-rtos/zephyr#51245]
**Is your enhancement proposal related to a problem? Please describe.**
The broadcast sink and the unicast server shall always **support** the `BT_AUDIO_CONTEXT_TYPE_UNSPECIFIED` value in the supported contexts:

> 3.8.2.1 Audio data Context Type support requirements
> The Broadcast Sink shall support the Context Type value defined as ‘unspecified’ in the Supported_Sink_Contexts field of the Supported Audio Contexts characteristic.

> 3.5.2.1 Audio data Context Type requirements
> If the Unicast Server supports the Audio Sink role, the Unicast Server shall support the Context Type value defined as ‘unspecified’ in the Supported_Sink_Contexts field of the Supported Audio Contexts characteristic.
> If the Unicast Server supports the Audio Source role, the Unicast Server shall support the Context Type value defined as ‘unspecified’ in the Supported_Source_Contexts field of the Supported Audio Contexts characteristic.

Currently the supported contexts are set via the CONFIG_BT_PACS_SNK_CONTEXT and CONFIG_BT_PACS_SRC_CONTEXT, but we do not verify whether the unspecified context is always set. 

**Describe the solution you'd like**
Either add a build check to verify that the unspecified bit is set or automatically add it in the stack silently. 

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by kruithofa** [comment]
Was already fixed by #52530
