### ISSUE TITLE
[Coverity CID: 179975] Error handling issues in /subsys/bluetooth/host/mesh/health_srv.c

### ISSUE THREAD

**Issue by Shilpashree3lc** [zephyrproject-rtos/zephyr#5126]
Static code scan issues seen in File: /subsys/bluetooth/host/mesh/health_srv.c
 Category: Error handling issues
 Function: send_attention_status
 Component: Bluetooth
 CID: 179975
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by jhedberg** [comment]
Already fixed in the master branch
