### ISSUE TITLE
include guards missing in toolchain/gcc.h and toolchain/common.h

### ISSUE THREAD

**Issue by aescolar-ot** [zephyrproject-rtos/zephyr#5130]
Both toolchain/gcc.h and toolchain/common.h lack include guards.
=> Including them twice thru other headers will cause quite a few warnings.

Also both headers define BUILD_ASSERT() and BUILD_ASSERT_MSG(), but only toolchain/common.h has a guard for it in its definition.

**Comment by andrewboie** [comment]
Hmm, we could add guards, but really nobody should ever include those headers directly. People should be doing #include <toolchain.h>
