### ISSUE TITLE
x86_64: Thread Local Storage pointer not setup before first thread started

### ISSUE THREAD

**Issue by keith-packard** [zephyrproject-rtos/zephyr#51318]
When `CONFIG_THREAD_LOCAL_STORAGE` is enabled, x86_64 doesn't initialize the thread local storage pointer (via %fs) before starting the first thread. If tracing is enabled, then the first call to sys_trace_k_thread_switched_out will attempt to fetch the current (i.e. outgoing) thread and crash.

Please also mention any information which could help others to understand
the problem you're facing:
 - I'm debugging picolibc integration, which selects `THREAD_LOCAL_STORAGE` for architectures which support it. This is required to use picolibc from the toolchain as that will use TLS if available.
 - Zephyr switches to the initial thread using the same path as any other context switch, and that invokes the switched_out trace points. Those functions generally want to reference the old thread pointer, which is stored in a TLS variable used by `k_current_get`. If TLS is not initialized, references to that variable will crash.

**To Reproduce**
1. `west build -T sample.tracing.transport.uart -b qemu_x86_64 -o run samples/subsys/tracing -DCONFIG_THREAD_LOCAL_STORAGE=y`
2. Note hang:
```
Booting from ROM..
```
4. `west build -d build_notls -T sample.tracing.transport.uart -b qemu_x86_64 -o run samples/subsys/tracing`
5. See correct output:
```
Booting from ROM..
*** Booting Zephyr OS build zephyr-v3.2.0-675-g5f8983f2ec77  ***
thread_a: Hello World from qemu_x86_64!
```

**Expected behavior**
The sample should run the same as it does with `THREAD_LOCAL_STORAGE` disabled

**Impact**
This is preventing picolibc support for x86_64 from being integrated

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: Zephyr SDK 0.15.1
 - Commit SHA: ae9de202220ce51e1ed61157f73d3800f84c6b06 (main as of 2022-10-16)

**Additional Information:**
An example of what needs doing can be seen in arch/arm/core/aarch32/thread.c:arch_switch_to_main_thread, although that only sets the base pointer for the first CPU and not additional CPUs.

**Comment by stephanosio** [comment]
cc @jhedberg @dcpleung @andyross
