### ISSUE TITLE
qemu_x86_tiny doesn't place libc-hooks data in z_libc_partition

### ISSUE THREAD

**Issue by keith-packard** [zephyrproject-rtos/zephyr#51343]
**Describe the bug**
qemu_x86_tiny.ld places data from the newlib and picolibc integration code (libc-hooks.c) in the `pinned.data` and `pinned.bss` sections rather than in the `z_libc_partition` areas. When userspace code attempts to access this data, an access fault occurs. Changing the linker script to place that data in the `z_libc_partition` caused several memory protection tests to fail.

Please also mention any information which could help others to understand
the problem you're facing:
 - Need to use a C library that requires data from libc-hooks to be accessible from userspace, either newlib or picolibc.

**To Reproduce**
1. `west build -b qemu_x86_tiny samples/userspace/hello_world_user -DCONFIG_PICOLIBC=y -o run`
2. should crash
3. `west build -b qemu_x86 -d build_x86 samples/userspace/hello_world_user -DCONFIG_PICOLIBC=y -o run`
4. should print `Hello World from UserSpace! (qemu_x86)`

**Expected behavior**
Expect qemu_x86_tiny to work like qemu_x86

**Impact**
This is blocking integration of picolibc for x86

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain (e.g Zephyr SDK, ...): Zephyr SDK 0.15.1
 - Commit SHA or Version used: main as of 2022-10-17 5f8983f2ec77ff0333d111bc23d454afc0de4176

**Comment by stephanosio** [comment]
cc @dcpleung @jhedberg @andyross
