### ISSUE TITLE
Driver error precision LPS22HH 

### ISSUE THREAD

**Issue by sevirip** [zephyrproject-rtos/zephyr#51370]
Hi,
I found an error in driver of LPS22HH in file drivers/sensor/lps22hh.c in the function lps22hh_press_convert.

I think it's better to have :

val->val1 = press_tmp / 4096;
val->val2 = (press_tmp % 4096) * 3125 / 128;

instead of : 

val->val1 = press_tmp / 40960;
val->val2 = (press_tmp % 40960) * 3125 / 128;

I understand that returning in kPa is the intended behavior here but it's create side effect and loss precision.

It's necessary to have the value in hPa instead of kPa to avoid side effet for the digits after the comma. You won more precision in having the value in hPa. It's really important for example to calculate a height (precision of 10 centimeters instead of 3 meters).

Best regards,

Pierre-Yves

**Comment by avisconti** [comment]
@sevirip, sorry for taking a look at it only now. I think that it is not possible to return hPa, as  SENSOR_CHAN_PRESS data are expected in kPa, as mentioned in sensor.h. I don't think that this modification can be accepted, because it will break the compatibility. I also involve @MaureenHelm, who may better clarify. Does it make sense to you?

**Comment by sevirip** [comment]
But why do you expect  SENSOR_CHAN_PRESS  in kPa instead of hPa ? 
Maybe there is another change to do this modification, but for this sensor driver there is something wrong because there is a big loss of precision.
I used an other driver in NRF5 SDK 17 with the same HW and i have a really better precision....
Also the pressure is used in hPa in many formula and not in kPa.

**Comment by avisconti** [comment]
> But why do you expect SENSOR_CHAN_PRESS in kPa instead of hPa ? Maybe there is another change to do this modification, but for this sensor driver there is something wrong because there is a big loss of precision. I used an other driver in NRF5 SDK 17 with the same HW and i have a really better precision.... Also the pressure is used in hPa in many formula and not in kPa.

To be honest I don't know. What I se is that in include/zephyr/drivers/sensor.h in sensor_channel we have                                                                                    
                                                                                                                         
   	/** Pressure in kilopascal. */
	SENSOR_CHAN_PRESS,
                                      
                                                                                
I'm not sure how to overcome to this. What driver is using hPa?
