### ISSUE TITLE
nsim_em: tests/subsys/logging/log_link_order run failed on nsim_em

### ISSUE THREAD

**Issue by mengxianglinx** [zephyrproject-rtos/zephyr#51422]
**Describe the bug**
tests/subsys/logging/log_link_order run failed on nsim_em,
commit: 042e23328487a

**To Reproduce**
1. west build -b nsim_em tests/subsys/logging/log_link_order/
2. west flash

**Expected behavior**
test pass

**Logs and console output**
Running TESTSUITE log_link_order
\===================================================================
START - test_log_local_unordered
 PASS - test_log_local_unordered in 0.002 seconds
\===================================================================
START - test_log_one_remote_ordering
ASSERTION FAIL [level] @ WEST_TOPDIR/zephyr/include/zephyr/logging/log_link.h:266
Console now belongs to simulator.

**Environment (please complete the following information):**
 - OS: (Linux)
 - Toolchain (Zephyr SDK 0.15.0)
 - Commit SHA or Version used: 042e23328487a

**Comment by evgeniy-paltsev** [comment]
The test is failing on various ARC nSIM platforms - seems to be generic ARC / platform issue.
