### ISSUE TITLE
tests: net: socket: tls: net.socket.tls region `FLASH' overflowed

### ISSUE THREAD

**Issue by nordic-piks** [zephyrproject-rtos/zephyr#51421]
**Describe the bug**
The tests:
- tests/net/socket/tls/net.socket.tls.preempt
- tests/net/socket/tls/net.socket.tls
- tests/net/socket/offload_dispatcher/net.socket.offload.dispatcher

Does not build - region `FLASH' overflowed

Observed for
- nrf9160dk_nrf9160_ns
- nrf5340dk_nrf5340_cpuapp_ns

**To Reproduce**
1. have nrf5340dk_nrf5340_cpuapp connected
2. go to your zephyr dir
3. call ./scripts/twister -T tests/net/socket/tls  -p nrf5340dk_nrf5340_cpuapp_ns --device-testing --device-serial /dev/ttyACM0 -v --inline-logs
4. See console output with error

**Expected behavior**
Valid console output

**Impact**
Not clear

**Logs and console output**
```
arm-zephyr-eabi/bin/ld.bfd: zephyr/zephyr_pre0.elf section `log_const_sections' will not fit in region `FLASH'
arm-zephyr-eabi/bin/ld.bfd: region `FLASH' overflowed by 59714 bytes
```

```
arm-zephyr-eabi/bin/ld.bfd: zephyr/zephyr_pre0.elf section `rodata' will not fit in region `FLASH'
arm-zephyr-eabi/bin/ld.bfd: region `FLASH' overflowed by 58934 bytes
```

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04.1 LTS
 - Toolchain Zephyr SDK 0.15
 - Commit SHA or Version used: zephyr-v3.2.0-679-g5ab62a43777d

**Comment by nordicjm** [comment]
Is this with picolibc enabled? There was a change to the heap size for libc, which was 64KB by default, maybe that's the cause?
