### ISSUE TITLE
Only one instance of mcp2515

### ISSUE THREAD

**Issue by babos** [zephyrproject-rtos/zephyr#51458]
Hello,
nrf52840 with Zephyr v2.x.x
I am unable to get two mcp2515 instances using DEVICE_DT_GET because the can_cmp2515 driver creates a device only for the first found instance of "microchip, mcp2515".
The adxl362 driver, on the other hand, will iterate through all adxl362 instances, using **DT_INST_FOREACH_STATUS_OKAY**

why mcp2515 not ? would it be possible to remedy?
I'm not sure why the can_mcp2515 driver won't iterate through all the instances, if it is intentional or just a mistake. 

thank'you

Babos

**Comment by nordicjm** [comment]
>  I'm not sure why the can_mcp2515 driver won't iterate through all the instances, if it is intentional or just a mistake.

Drivers have been updated over time but this one has not, it should be possible to replace the macros and add support for multiple devices.

**Comment by henrikbrixandersen** [comment]
I'll add multi-instance support. This was just an oversight.

**Comment by henrikbrixandersen** [comment]
@babos You can test the multi-instance support in #51539.

**Comment by babos** [comment]
awesome, thx
