### ISSUE TITLE
lis2dw12 function latch is misunderstood with drdy latch

### ISSUE THREAD

**Issue by sfeutrier** [zephyrproject-rtos/zephyr#51488]
**Describe the bug**
in file lis2dw12_trigger.c, line 425 to 433.
drdy_ready is checked. Regarding the documentation here : https://docs.zephyrproject.org/3.2.0/build/dts/api/bindings/sensor/st%2Clis2dw12-i2c.html, it should set the flag "drdy_pulsed" of the CTRL7 register (see datasheet p56). However, in lis2dw12_trigger.c, the function "lis2dw12_int_notification_set" is called.
This function allows to set the "lir" flag of the register CTRL3. This flag is for Wake up / free-fall / tap detections.
One should call function "lis2dw12_data_ready_mode_set" which is the function for the drdy pulsed / latch state.

**Expected behavior**
Just replace "lis2dw12_int_notification_set" by "lis2dw12_data_ready_mode_set".
An improvement would be to add the posibility to use the "lis2dw12_int_notification_set" function. Because it is not accessible nor compatible with the interruption function currently.

**Impact**
You cannot change the behaviour of the drdy pin without changing the source code.

**Environment (please complete the following information):**
 - Zephyr release v3.2.0

**Comment by avisconti** [comment]
@sfeutrier, thank you for catching this issue. Yes, I agree that CTRL7.drdy_pulsed must be set, and not CTRL3.lir, which is for interrupts such as wakeup and taps. I will provide a fix asap!

**Comment by avisconti** [comment]
@sfeutrier can you possibly take a look to #51901 and review it? Thx!

**Comment by avisconti** [comment]
> > @sfeutrier can you possibly take a look to #51901 and review it? Thx!
> 
> Done! I'll let you close this ticket as i'm not familiar with your process!

Once that #51901 will be reviewed (at least 2 with write access) and merged this bug will be closed. Thanks for reporting it and reviewed the commit that you actually provided ;)

**Comment by xyzzy42** [comment]
@sfeutrier, Do you have a known use case for latched mode for DRDY?  I can think of no reason to use it instead of pulsed mode.  latched mode will not work if only temp and/or sensor hub data is read, since accel or gyro read only are needed to reset drdy.

**Comment by sfeutrier** [comment]
> @sfeutrier, Do you have a known use case for latched mode for DRDY? I can think of no reason to use it instead of pulsed mode. latched mode will not work if only temp and/or sensor hub data is read, since accel or gyro read only are needed to reset drdy.

I just use latch mode to avoid having too many interruptions. I use latch mode + wakeup interruption. Wakeup interruptions can be triggered a lot but I only need the "first" ones to check if device is indeed moving above the threshold I set.
You should post your question on the stm forum if you have more questions ;)

**Comment by xyzzy42** [comment]
It looks to me like lis2w12 driver has the same bug as lsm6dso driver with latched interrupts.  If a new interrupt is generated after the latched interrupt is de-asserted but before the GPIO interrupt is re-enabled, then no edge will be detected and the driver stalls.

**Comment by sfeutrier** [comment]
I cannot say because with nrf connect sdk / zephyr, I did not use the latch feature. On other projects (with nRf SDK) I use the latch feature but I have create my own driver.
I'm not sure the interruption handler is developed with the latch feature taken into consideration. Do not hesitate to modify the driver to match your use case
