### ISSUE TITLE
drivers: modem: gsm: gsm_ppp_stop() does not change gsm->state

### ISSUE THREAD

**Issue by jeppenodgaard** [zephyrproject-rtos/zephyr#51505]
**Describe the bug**
`gsm_ppp_stop()` does not set `gsm->state` to `GSM_PPP_STOP`.

Please also mention any information which could help others to understand
the problem you're facing:
I want to restart gsm_ppp by calling `gsm_ppp_stop()` then `gsm_ppp_start()`. However `gsm_ppp_start()` does not run because `gsm->state` is not `GSM_PPP_STOP`.

**To Reproduce**
When gsm_ppp is in `gsm->state` GSM_PPP_SETUP_DONE call `gsm_ppp_stop()` then `gsm_ppp_start()`.

**Expected behavior**
`gsm_ppp_start()` runs normally.

**Impact**
It is not possible to start gsm_ppp again if e.g. NO CARRIER is received.

**Logs and console output**
```
[00:01:54.403,503] <inf> modem_gsm: GSM network interface down
[00:01:54.403,594] <err> modem_gsm: gsm_ppp is already started
[00:03:04.419,921] <wrn> modem_gsm: Failed locking modem cmds!
[00:03:04.419,921] <err> modem_gsm: gsm_ppp is already started
[00:04:14.436,279] <wrn> modem_gsm: Failed locking modem cmds!
[00:04:14.436,309] <err> modem_gsm: gsm_ppp is already started
[00:05:24.452,636] <wrn> modem_gsm: Failed locking modem cmds!
[00:05:24.452,636] <err> modem_gsm: gsm_ppp is already started

```

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain Zephyr SDK
 - v3.1.0 with cherry-pick from https://github.com/zephyrproject-rtos/zephyr/pull/48533

https://github.com/zephyrproject-rtos/zephyr/issues/51505#tasklist-block-ce1f6f6a-fc56-4e48-9852-6fbc167498d0

**Comment by jeppenodgaard** [comment]
To me it looks like this line `gsm->state = GSM_PPP_STOP` is missing. Do you have any feedback @ycsin ?

**Comment by ycsin** [comment]
@jeppenodgaard yes you are right, somehow the reset is missing from the FSM implementation PR.
In https://github.com/zephyrproject-rtos/zephyr/blob/main/drivers/modem/gsm_ppp.c#L1212, the state should be reset to `GSM_PPP_STOP`, would it be possible for you to submit a patch for this?

**Comment by jeppenodgaard** [comment]
@ycsin Yes :) Created a PR.
