### ISSUE TITLE
RFC: API Change: SYS_INIT function signature

### ISSUE THREAD

**Issue by gmarull** [zephyrproject-rtos/zephyr#51609]
## Problem Description

The init infrastructure, found in `init.h`, is currently used by:

- `SYS_INIT`: to call functions before `main`
- `DEVICE_*`: to initialize devices

They are all sorted according to an initialization level + a priority.
`SYS_INIT` calls are really orthogonal to devices, however, the required
function signature requires a `const struct device *dev` as a first
argument. The only reason for that is because the same init machinery is
used by devices, so we have something like:

```c
struct init_entry {
	int (*init)(const struct device *dev);
	/* only set by DEVICE_*, otherwise NULL */
	const struct device *dev;
}
```

As a result, we end up with such weird/ugly pattern:

```c
static int my_init(const struct device *dev)
{
	/* always NULL! add ARG_UNUSED to avoid compiler warning */
	ARG_UNUSED(dev);
	...
}
```

This is really a result of poor internals isolation. 

##  Background information on why the change is required

This change adjusts SYS_INIT function so that it takes no arguments. Currently, it takes one argument (a `const struct device *`) that is always set to NULL by the caller. This means it is not necessary.

## Proposed Change (detailed)

See https://github.com/zephyrproject-rtos/zephyr/pull/51217

## Brief description of the API change

```c
static int my_init(const struct device *dev)
{
	ARG_UNUSED(dev);
	...
}

SYS_INIT(my_init, LEVEL, PRIO);
```

will become

```c
static int my_init(void)
{
	...
}

SYS_INIT(my_init, LEVEL, PRIO);
```

## Detailed RFC

- Function call changes: `SYS_INIT`/`SYS_INIT_NAMED` function signature
- Device Tree changes (source and bindings): None
- Kconfig option changes: None

## Dependencies

None

## Impact to users of the API

Users will need to adjust SYS_INIT functions signature. A Python script will be provided to automate such process, allowing for a smooth and quick transition. See the linked PR for more details.

**Comment by nashif** [comment]
can this be closed now?
