### ISSUE TITLE
RFC: Add Apache Thrift Upstream Module (from GSoC 2022 Project)

### ISSUE THREAD

**Issue by cfriedt** [zephyrproject-rtos/zephyr#51617]
## Introduction

Thrift is mostly ready for prime-time, with only a few more items on the checklist to complete. It would be great to get that into the 3.3 release.

https://github.com/zephyrproject-rtos/gsoc-2022-thrift/issues/147

TODO: fill out rest of issue @cfriedt 

### Problem description

Why do we want this change and what problem are we trying to address?

### Proposed change

A brief summary of the proposed change - the 10,000 ft view on what it will
change once this change is implemented.

## Detailed RFC

In this section of the document the target audience is the dev team. Upon
reading this section each engineer should have a rather clear picture of what
needs to be done in order to implement the described feature.

### Proposed change (Detailed)

This section is freeform - you should describe your change in as much detail
as possible. Please also ensure to include any context or background info here.
For example, do we have existing components which can be reused or altered.

By reading this section, each team member should be able to know what exactly
you're planning to change and how.

### Dependencies

Highlight how the change may affect the rest of the project (new components,
modifications in other areas), or other teams/projects.

### Concerns and Unresolved Questions

List any concerns, unknowns, and generally unresolved questions etc.

## Alternatives

List any alternatives considered, and the reasons for choosing this option
over them.

**Comment by stephanosio** [comment]
This should be using "External Source Code" template, as with any other module addition requests.
