### ISSUE TITLE

    tests-ci : net: socket: tls test Failed
    

### ISSUE THREAD

**Issue by hakehuang** [zephyrproject-rtos/zephyr#51692]
**Describe the bug**
    tls test is Failed on zephyr-v3.2.0-818-g938b9533c727 on frdm_k64f

    see logs for details

    **To Reproduce**
    1. 
    ```
    scripts/twister --device-testing --device-serial /dev/ttyACM0 -p frdm_k64f      --sub-test net.socket
    ```
    2. See error

    **Expected behavior**
    test pass

    **Impact**

    **Logs and console output**
    
    ```
    START - test_v4_dtls_sendmsg

Assertion failed at WEST_TOPDIR/zephyr/tests/net/socket/tls/src/main.c:530: test_dtls_sendmsg: (rv not equal to 0)
server bind failed
FAIL - test_v4_dtls_sendmsg in 0.013 seconds

        
    ```

    **Environment (please complete the following information):**
     - OS: (e.g. Linux )
     - Toolchain (e.g Zephyr SDK)
     - Commit SHA or Version used: zephyr-v3.2.0-818-g938b9533c727

**Comment by EmilioCBen** [comment]
@hakehuang, I can confirm that this test case passes with the current version of main. Via git bisect, the failure was introduced with #51240 and subsequently fixed with #51613
