### ISSUE TITLE
zephyr-v1.9.2 tag missing

### ISSUE THREAD

**Issue by dbkinder** [zephyrproject-rtos/zephyr#5176]
Final tagged releases for Zephyr all have the form zephyr-v1.x.x except for the latest v1.9.2 (where there's no zephyr-v1.9.2 tag).  See https://github.com/zephyrproject-rtos/zephyr/tags

**Comment by nashif** [comment]
done

**Comment by dbkinder** [comment]
Almost.  The release notes should be on the zephyr-1.9.2 tag too.

**Comment by nashif** [comment]
done
