### ISSUE TITLE
drivers/clock_control: stm32: Can support configure stm32_h7 PLL2 ?

### ISSUE THREAD

**Issue by CmST0us** [zephyrproject-rtos/zephyr#51785]
I found this PR #49878 has supported configure pll2 for stm32f1* devices.
Is there any plan for supporting configure pll2 for stm32h7 devices?
In my project, sdram needs to config pll2.

**Comment by FRASTM** [comment]
@CmST0us thanks for pointing this about the stm32h7 serie. 
That was not planned yet but if you wish to propose a PR on a similar model as what is done for the stm32f1x, your contribution would be really appreciated.

**Comment by CmST0us** [comment]
@FRASTM thanks for your reply, I am trying to figure out how to add.

**Comment by CmST0us** [comment]
Fix on Release 3.3.0
