### ISSUE TITLE
Sysbuild support for hardware model v2

### ISSUE THREAD

**Issue by mbolivar-nordic** [zephyrproject-rtos/zephyr#51832]
# Parent issue

This issue is part of a larger issue: https://github.com/zephyrproject-rtos/zephyr/issues/51833

# Is your enhancement proposal related to a problem?

Zephyr's [sysbuild](https://docs.zephyrproject.org/latest/build/sysbuild/index.html) feature lets users set up and develop with multiple interrelated Zephyr- and non-Zephyr application directories. If my application directory has sysbuild integration, I can use it to build, flash, and debug all of the applications at once with command lines like this example:

```
$ west build --sysbuild -b board my-top-level-app-dir # builds multiple applications
$ west flash # flashes all the application images to my board
```

If Zephyr adopts a hardware model "v2" (see #51831), I will still not have a convenient way to build multiple interrelated applications using these features.

# Describe the solution you'd like

Sysbuild awareness of hardware (socs / boards) supported via hardware model v2 (HWMv2).

At a high level, I would like sysbuild to be able to manage the interrelationships between application images compiled for all the cores on an AMP SoC as specified in a single board directory using the file conventions established by HWMv2.

I would like this enhancement to be supported in a backwards compatible way: no existing sysbuild use cases with hardware model v1 should be broken. This will allow a gradual migration period for existing boards.

# Describe alternatives you've considered

Continuing to use multiple regular `west build` commands to generate individual build systems, flashing the individual zephyr application images to my board via multiple `west flash` commands.

# Change history

- 2023-05-05: Move system devicetree support to a separate issue
- 2022-10-31: Many details are TBD given the lack of implementation details being settled in system devicetree and hardware model v2 at the present time, so this is mainly a placeholder issue for now.

**Comment by mbolivar-nordic** [comment]
Split the system DT portions out. I will file a separate issue for these.

**Comment by carlescufi** [comment]
This is now complete
