### ISSUE TITLE
kernel system call handlers missing due to -Wl,--no-whole-archive

### ISSUE THREAD

**Issue by andrewboie** [zephyrproject-rtos/zephyr#5184]
Discovered by @agross-linaro, who was getting "unimplemented system call" errors on ARM for k_thread_abort().

ARM has a custom implementation of k_thread_abort under arch/arm. This has the effect of compiling out everything in kernel/thread_abort.c except the handler function.
For some strange reason, if --no-whole-archive is enabled, the linker decides to prefer the weak handler for k_thread_abort() in syscall_dispatch.c.

**Comment by linkmeyer** [comment]
@andrewboie , can you please set the priority?

**Comment by lpereira** [comment]
I set the priority to high since the way things are right now, they won't work on ARM.  This fix is required.

**Comment by lpereira** [comment]
I had originally set this to high because this wouldn't work on ARM, but userland isn't working on ARM yet and won't be at least for 1.11. So moved back to medium.

**Comment by andrewboie** [comment]
This issue affects x86 and needs to go into 1.10

**Comment by andrewboie** [comment]
@AdithyaBaglody discovered that this problem is still happening, my patch didn't completely fix it.
Diving in....

**Comment by andrewboie** [comment]
@AdithyaBaglody found a fix
