### ISSUE TITLE
sensor: bmp388: missing if check around i2c device ready function

### ISSUE THREAD

**Issue by Cherish-forever** [zephyrproject-rtos/zephyr#51873]
https://github.com/zephyrproject-rtos/zephyr/blob/3a3cfbb652b29e9f39a38fe6febf29e1570d32bc/drivers/sensor/bmp388/bmp388.c#L600

when device is on spi bus, there is no i2c

https://github.com/zephyrproject-rtos/zephyr/issues/51873#tasklist-block-3e9cf6e6-2736-4b13-8365-aa9ec8b0e700

**Comment by Cherish-forever** [comment]
It is judged that the way the device attaches the bus is incorrect during operation

**Comment by nordicjm** [comment]
@xodus7 since you submitted this driver

**Comment by xodus7** [comment]
Indeed this is a bug, and very suggestive of which hardware configuration I has to test with :-( . I see a now closed PR #51876 that was making changes to this driver. Is someone working to fix this? If not, I'd be happy to submit a simple patch.
