### ISSUE TITLE
Bluetooth: Central rejects connection parameters update request from a connected peripheral

### ISSUE THREAD

**Issue by ahmedmoheb-nordic** [zephyrproject-rtos/zephyr#51984]
## Introduction

The use case includes a Central that connects to 4 peripherals

### Problem description

The Central uses the following procedure to connect to the peripherals
1 - Central starts a scanning procedure
2 - When a device is found, central attempt to connect to it 
3 - When the 'connected' callback is received, a signal is set to start a new scanning procedure from the main thread
4 - When a peripheral is connected, it sends a connection parameters update request

Connecting to the 4 peripherals is working as expected, except that one of the connection update request is missed at the central side.

Even after increasing the following configuration parameters, issue still exist.
- CONFIG_BT_BUF_ACL_TX_COUNT=8
- CONFIG_BT_BUF_ACL_RX_COUNT=8
- CONFIG_BT_BUF_EVT_RX_COUNT=8

Please check the following draft PR which shows the case and can be executed using BabbleSim
https://github.com/zephyrproject-rtos/zephyr/pull/51983

A shell script can be found under ~/zephyrproject/zephyr/tests/bluetooth/bsim_bt/bsim_test_conn_stress/tests_scripts/conn_stress.sh

**Comment by ahmedmoheb-nordic** [comment]
@jori-nordic @alwa-nordic please check this

**Comment by cvinayak** [comment]
Zephyr Controller supports LE Connection Parameter Request Procedure, which generates LL_REJECT_EXT_IND PDU with error code Unsupported Link Layer Parameter Value (0x20) when the Controller is busy with another Connection Update procedure.

I have shared a PR #52006 that I use locally for testing LE Connection Parameter Request across multiple simultaneous to reschedule connections of similar connection interval in a non-overlapping schedule.
