### ISSUE TITLE
Nominate Attie Grande as zephyr Collaborator

### ISSUE THREAD

**Issue by nandojve** [zephyrproject-rtos/zephyr#51998]
# Background

The [TSC Project Roles] defines the main roles for the Zephyr Project, including Maintainer, Collaborator, and Contributor.

By default anyone that contributes code or documentation is a Contributor, but with the lowest [GitHub Permission Level] of Read. For example, Contributors with Read permission do not have the permission to add reviewers to a pull request.

Use this template to nominate a GitHub user for the Contributor role with Triage permission level, which allows the user to add reviewers to a pull request and be added as a reviewer by other users.

# Nomination

## GitHub User

Provide the following information about the GitHub user:

1. Full Name: Attie Grande
1. GitHub username: attie-argentum (https://github.com/attie-argentum)
1. Organization: Argentum Systems Ltd (https://github.com/argentum-systems)

## Supporting Documents

[Zephyr authored PRs](https://github.com/pulls?q=is%3Apr+author%3Aattie-argentum+archived%3Afalse+repo%3Azephyrproject-rtos%2Fzephyr+repo%3Azephyrproject-rtos%2Fhal_atmel+)
[Zephyr reviewed PRS](https://github.com/pulls?q=is%3Apr+reviewed-by%3Aattie-argentum+archived%3Afalse+repo%3Azephyrproject-rtos%2Fzephyr)

Maybe require for #51996

CC: @stephanosio 

[TSC Project Roles]: <https://docs.zephyrproject.org/latest/project/project_roles.html>
[GitHub Permission Level]: <https://docs.github.com/en/organizations/managing-access-to-your-organizations-repositories/repository-roles-for-an-organization>

**Comment by stephanosio** [comment]
Added in https://github.com/zephyrproject-rtos/zephyr/pull/51996

FYI, for collaborators and maintainers, you do not need to use this form; simply opening a pull request to add the user to the MAINTAINERS.yml alone should be enough.
