### ISSUE TITLE
RFC: API Change: mgmt: mcumgr: transport: Add query valid check function

### ISSUE THREAD

**Issue by nordicjm** [zephyrproject-rtos/zephyr#52022]
## Problem Description:

This is a stable API change request for MCUmgr to add a new function pointer to transports to be used in a callback to check if pending queries are still valid or invalid (and, if invalid, to purge them from the queue). The requirement for this is with connection-orientated transports, e.g. Bluetooth - if a connection is dropped then it does not make sense to continue running MCUmgr commands that it queued up.

## Proposed Change (detailed):

This change is to add a new function pointer to the `smp_transport_init()` function which takes takes a netbuf pointer and void pointer (the void pointer is supplied when the `smp_rx_remove_invalid()` function is called) and returns false if a netbuf is no longer valid and should be purged, or true if it is still valid.

PR: https://github.com/zephyrproject-rtos/zephyr/pull/51757

For out-of-tree zephyr application code implementing MCUmgr transports, this requires either implementing the function (for transports that would need to support it) or setting the function to NULL in the `smp_transport_init()` call, in which case the transport will behave as it does now. If a transport implements this functionality, it will also need to make a call to `smp_rx_remove_invalid()` when the connection is no longer valid to start the cleaning up process

**Comment by carlescufi** [comment]
Arch WG meeting:

N/A since it's not a stable API: Please make the changes and declare it stable.
