### ISSUE TITLE
Bluetooth: Missing LL data length update callback on Central and Peripheral sides 

### ISSUE THREAD

**Issue by ahmedmoheb-nordic** [zephyrproject-rtos/zephyr#52056]
## Introduction

Updating LL data length fails

### Problem description

After establishing a connection between a Central and a Peripheral, trying to update the LL data length fails.
Also, the update callback isn't called.

Please check the following draft PR which shows the case and can be executed using BabbleSim
https://github.com/zephyrproject-rtos/zephyr/pull/51985

A shell script can be found under ~/zephyrproject/zephyr/tests/bluetooth/bsim_bt/bsim_test_conn_stress/tests_scripts/conn_stress.sh

**Comment by ahmedmoheb-nordic** [comment]
@jori-nordic @alwa-nordic please check this

**Comment by ahmedmoheb-nordic** [comment]
No longer exist after rebasing.

It seemed to be related to the interval between receiving the "connected" callback and starting the next scanning procedure.
Before rebasing:

- The connection update request from the second connected peripheral was missed which is related to this issue https://github.com/zephyrproject-rtos/zephyr/issues/51984
- By introducing a delay between receiving the "connected" callback after connecting to the first peripheral and starting the scanning procedure, the central got the connection update request and LL data length update callback was received as expected

**Comment by jori-nordic** [comment]
not reproducible anymore after @ahmedmoheb-nordic upgraded from ubuntu 20.04 as host system to ubuntu 22.04.
Probably this is due to the different compiler/linker in the previous system.

**Comment by ahmedmoheb-nordic** [comment]
I tried to reproduce the issue with a VM running Ubuntu 20.04, but I couldn't.

Adding a delay before starting the second scanning procedure allows the 2 expected connection parameters update requests from the connected peripherals to be received, then the LL data length update callbacks are received normally after initiating a LL data length update.

Also, removing the waiting condition and without a delay before the second scanning procedure, an error code is returned upon requesting to update the LL data length.

Please find the attached screen shots showing the 2 cases.

![LL callback](https://user-images.githubusercontent.com/109019690/202848268-61483c32-54e5-4cf8-bcba-66206baf74a6.png)

![MTU update error](https://user-images.githubusercontent.com/109019690/202848278-a86f81dc-d5b3-49d1-b540-0a7f0e04a043.png)
