### ISSUE TITLE
ESP32-C3 UART1 not available after zephyr update to v3.2.99

### ISSUE THREAD

**Issue by abdulayubzoi** [zephyrproject-rtos/zephyr#52073]
***Note:** This bug is similar to this [issue ](https://github.com/zephyrproject-rtos/zephyr/issues/46434)*

**Describe the bug**
I'm using the `UART1` on ESP32-C3 to communicate to a connected device. I updated the `zephyr-sdk` to `v0.15.1` and updated `zephyr` to `v3.2.99`, and the `UART1` just stopped working.

The peripheral is existing in [esp32c3.dtsi](https://github.com/zephyrproject-rtos/zephyr/blob/0ace177a32faaf9b113a87febcfbd8ae3e53c5b3/dts/riscv/espressif/esp32c3.dtsi#L126-L135) file, but it is still not covered in the [esp32c3_devkitm-pinctrl.dtsi](https://github.com/zephyrproject-rtos/zephyr/blob/0ace177a32faaf9b113a87febcfbd8ae3e53c5b3/boards/riscv/esp32c3_devkitm/esp32c3_devkitm-pinctrl.dtsi).

I have the `UART1` assignments in the application's custom board definition, but unfortunately the required macros in [esp32c3-pinctrl.h in hal_espressif](https://github.com/zephyrproject-rtos/hal_espressif/blob/zephyr/include/dt-bindings/pinctrl/esp32c3-pinctrl.h) are missing in the `zephyr` branch of `hal_espressif`. The macros are however present in the `hal_4.3` branch in [esp32c3-pinctrl.h in hal_espressif](https://github.com/zephyrproject-rtos/hal_espressif/blob/hal_4.3/include/dt-bindings/pinctrl/esp32c3-pinctrl.h#:~:text=/*%20UART1_CTS%20*/,21%2C%20ESP_NOSIG%2C%20ESP_U1TXD_OUT)

My `west.yml` looks like this for `hal_espressif`:
```
    - name: hal_espressif
      revision: 8c7ee781ea4c4a010740f5231709ce7b21ad96d6
      path: modules/hal/espressif
      west-commands: west/west-commands.yml
      groups:
        - hal
```
I realize that the commit for `hal_espressif` does not have the required macros. But this [PR](https://github.com/zephyrproject-rtos/zephyr/pull/46568) describes how this was fixed, just on a different branch `hal_4.3`. However, when I direct `west.yml` to switch to the latest commit on `hal_4.3`, and run `west update && west blobs fetch hal_espressif`, and try to build the application...I run into issues like `ESP_IDF_PATH is not set`. Also I believe it is not the right thing to do, since `hal_4.3` branch is quite behind `zephyr` branch of `hal_espressif`.

**To Reproduce**

Try to compile a sample with `esp32c3_devkitm` board using the following `.overlay`:

```
&uart1 {
	pinctrl-0 = <&uart1_rx_gpio8 &uart1_tx_gpio9>;
	pinctrl-names = "default";
	current-speed = <9600>;
	status = "okay";
};
```

**Expected behavior**

The pinctrl definitions of all previously supported peripherals are existing in the `zephyr` branch and it's possible to use them.

**Impact**

Showstopper: My custom hardware is not useable with Zephyr v3.2.99 anymore if there is no workaround. I need both UART peripherals.

**Logs and console output**
Not applicable

**Environment:**
 - OS: devcontainer on WSL2
 - Toolchain: Zephyr SDK v0.15.1
 - Zephyr version: 3.2.99

**Additional context**
The `UART1` in my custom `esp32c3.dts` looks like this:
```
&uart1 {
	status = "okay";
	current-speed = <115200>;
	pinctrl-0 = <&uart1_tx_gpio19 &uart1_rx_gpio18 &uart1_cts_gpio2 &uart1_rts_gpio3>;
	pinctrl-names = "default";
};
```

The `UART1` in my custom `esp32c3_custom-pinctrl.dtsi` looks like this:
```
&pinctrl {
	uart1_tx_gpio19: uart1_tx_gpio19 {
		pinmux = <ESP32_PINMUX(19, ESP_NOSIG, ESP_U1TXD_OUT)>;
		bias-pull-up;
	};

	uart1_rx_gpio18: uart1_rx_gpio18 {
		pinmux = <ESP32_PINMUX(18, ESP_U1RXD_IN, ESP_NOSIG)>;
	};

	uart1_rts_gpio3: uart1_rts_gpio3 {
		pinmux = <ESP32_PINMUX(3, ESP_NOSIG, ESP_U1RTS_OUT)>;
		bias-pull-up;
		drive-open-drain;
	};

	uart1_cts_gpio2: uart1_cts_gpio2 {
		pinmux = <ESP32_PINMUX(2, ESP_U1CTS_IN, ESP_NOSIG)>;
		bias-pull-up;
		drive-open-drain;
	};
};
```

**Comment by sylvioalves** [comment]
@abdulayubzoi, thanks for pointing this out. I'll fix it.
