### ISSUE TITLE
ADC Channel SCAN mode for STM32U5

### ISSUE THREAD

**Issue by aks-bit** [zephyrproject-rtos/zephyr#52181]
Hi 

I am working with zephyr project to develop a platform.
I need to access ADC channel in scan mode with DMA.
Can any one help on this.

Thanks!

**Comment by aks-bit** [comment]
Hi Erwan,

Can you comment on this.

**Comment by erwango** [comment]
@aks-bit Similar request was raised here: https://github.com/zephyrproject-rtos/zephyr/issues/39640.
I'd suggest to follow up from there.
I'm closing current request
