### ISSUE TITLE
native port: Mirror the zephyr thread name onto native threads

### ISSUE THREAD

**Issue by nylnx** [zephyrproject-rtos/zephyr#52223]
The idea is to have the thread name mirrored from the zephyr task struct into the native OS thread name. It would make debugging easier, since there is no second guessing which thread is which.

From my research the only portable/posix way to set the thread name `prctl(PR_SET_NAME, "...")`, which can only set the thread name of the currently executing thread. In posix-zephyr-land, this only enables setting the name once at the start. The other way is to rely on the `pthread_setname_np` which is not the same on all posix-capable platforms, but allows to set the name of any thread and therefore would allow `k_thread_name_set` to work.

Maybe somebody has a fix for this problem and a solution that would allow zephyr to implement this feature.

**Comment by stephanosio** [comment]
cc @cfriedt

**Comment by cfriedt** [comment]
@SkryptX - it's actually already done the second way that you mentioned, via `pthread_setname_np()`. You just need `CONFIG_THREAD_NAME=y`.

See `lib/posix/pthread.c`.

From what I gather, `prctl()` is a linuxism.

**Comment by SkryptX** [comment]
@cfriedt I actually want the reverse of that :P I wish that Zephyr would set the thread names I set in Zephyr to be mirrored onto a POSIX thread, in my case Linux. So I don't want to use Zephyr with Posix, I want Zephyr to use Posix. 

Use case: I want to debug my Zephyr application on my Linux host and see the Zephyr thread names :)

**Comment by cfriedt** [comment]
> @cfriedt I actually want the reverse of that :P I wish that Zephyr would set the thread names I set in Zephyr to be mirrored onto a POSIX thread, in my case Linux. So I don't want to use Zephyr with Posix, I want Zephyr to use Posix. 

Yes, that is how the POSIX subsystem currently works (both forward and in reverse).

> Use case: I want to debug my Zephyr application on my Linux host and see the Zephyr thread names :)

It's possible that you're confusing `CONFIG_ARCH_POSIX` and `CONFIG_POSIX_API`.

Note, they are mutually exclusive at the moment (you cannot use Zephyr's POSIX subsystem currently when building for `native_posix`).

It is unlikely that this will ever be fixed for the POSIX arch.

**Comment by SkryptX** [comment]
> It's possible that you're confusing `CONFIG_ARCH_POSIX` and `CONFIG_POSIX_API`.

I maybe should have said native port instead of POSIX. I was always talking about the native port and `CONFIG_ARCH_POSIX` and never `CONFIG_POSIX_API`. So if I execute Zephyr with the something like `native_posix` I would like it to mirror the thread names onto the native thread names (for example on Linux `/proc/<pid>/task/<tid>/comm`).

**Comment by aescolar** [comment]
@nylnx (I had completely missed this request, as it went to the wrong area/collaborators).
It is a fair request, I will try to look into it, but it won't be high priority. I assigned myself so I won't forget.
