### ISSUE TITLE
USB: Support for max packet size other then 64 for control endpoint

### ISSUE THREAD

**Issue by kasjer** [zephyrproject-rtos/zephyr#52253]
### Max packet size hardcoded to 64 prevents usage of USB in SmartBond devices
Max packet size for control endpoint as described in USB specification
can be 8, 16, 32 and 64 for full speed devices.
Zephyr defines maximum value for this endpoint size in _usb_device.h_
```c
#define USB_MAX_CTRL_MPS	64   /**< maximum packet size (MPS) for EP 0 */
```
This value is later used in _usb_descriptor.c_ and _usb_dfu.c_ when device descriptor is constructed.
This value is also used in _usb_device.c_ in function **use_enable()**.

SmartBond devices by Renesas (supported in Zephyr) have endpoint 0 packet size limited to 8 bytes.

### Desired solution
Add separate definition of max packet size that will be used in device descriptor creation and **usb_enable()** function.

I'm not sure if this should be done in DTS or some other way.

**Comment by jfischer-no** [comment]
Resolved by #57028
