### ISSUE TITLE
Compiling with -O0 causes the kobject text area to exceed the limit (linker error)

### ISSUE THREAD

**Issue by SebastianBoe** [zephyrproject-rtos/zephyr#5226]
Compiling with -O0 causes the kobject text area to exceed the limit (linker error).

This PR has a failing testcase:

https://github.com/zephyrproject-rtos/zephyr/pull/5225

To reproduce, do

cmake -DBOARD=qemu_x86 -DEXTRA_CFLAGS=-O0 -Hzephyr/tests/kernel/test_build -Bb && make -C b

on commit 967d8b5

**Comment by SebastianBoe** [comment]
Tweaking

 #define KOBJECT_TEXT_AREA	128

to be 256 

fixed the issue, so perhaps we just need to tweak

#if defined(CONFIG_DEBUG) || defined(CONFIG_STACK_CANARIES)

to fix the issue.

**Comment by andrewboie** [comment]
@AdithyaBaglody can you take a look at this?
