### ISSUE TITLE
west flash --file

### ISSUE THREAD

**Issue by mbolivar-nordic** [zephyrproject-rtos/zephyr#52262]
**Is your enhancement proposal related to a problem? Please describe.**

People (understandably) want commands like `west flash --bin-file my.bin` to mean "you must flash my.bin". But the meaning of the `--bin-file` option is not "you must flash this bin file", it's "if you are going to flash a bin file, flash this one".

This is bad UX. I did it this way out of expediency when I was first writing the glue layer between the build system and the west flash/debug commands.

**Describe the solution you'd like**

Two new `west flash` options:

1. `-f/--file FOO`: this means, unambiguously, "you must flash `FOO`; do not flash anything else"
2. `-t/--file-type {hex,bin,elf,...}`: normally, the type of `FOO` is taken from its extension. This overrides that default behavior

Alongside that, either making the existing --bin-file, --hex-file, and --elf-file hidden options that don't show up in the help text, or changing the help text to explicitly discourage using them and adding a deprecation mechanism.

**Describe alternatives you've considered**

The other option would be changing `--bin-file` etc. to work the way many people expect them to.

It's too late to change now in my opinion, as other users are likely expecting them to behave the way they are designed to, bad UX and all.

It's also not clear what to do when you say `west flash --bin-file foo.bin --hex-file bar.hex`. I guess an error is always a possibility, or "last one wins", but if you look at the implementation details for how runners.yaml is generated, you'll see why that isn't so nice.

**Additional context**

Here are some starting point ideas for the implementation:

- add a flag capability to `RunnerCaps` named `file` which says that the runner can work using an arbitrary file passed by the user
- if the `file` RunnerCaps flag is set, adding a `-f` or `--file` argument to the parser in `ZephyrBinaryRunner.add_parser()` that represents it, along with a `-t` or `--file-type` argument that captures the file type (which if not given should be inferred from the file extension, e.g. .bin, .hex, .elf, or something else runner specific)
- requiring that all runners which have the `RunnerCaps` flag set accept a `file` kwarg which represents this file
- requiring that `create()` implementations for those runner accept `--file` and pass it to the file `kwarg`

The big problems to solve are:

- dealing with the `--{bin,elf,hex}-file` arguments,
- their values in `RunnerConfig`,
- the corresponding handling of the `cfg` arg in runner constructors,
- the way `cmake/flash/CMakeLists.txt` caches bin/elf/etc data
- the way `run_common.py` parses that data from the build directory when building `RunnerConfig` instances (note this happens multiple times in this file, as it's needed for things like `west flash --context` too)

I don't have a detailed design in mind.

Something like this in `runners/core.py` could be used if we want to implement a deprecation policy:

```
class UseFileInsteadAction(argparse.Action):

    def __call__(self, parser, namespace, values, option_string):
        _logger.warning('argument {} is deprecated; use --file instead'.
                        format(option_string))
        setattr(namespace, 'file', values)

# [...]

parser.add_argument('--hex-file', action=UseFileInsteadAction)
parser.add_argument('--elf-file', action=UseFileInsteadAction)
parser.add_argument('--bin-file', action=UseFileInsteadAction)
parser.add_argument('--file')
```

**Comment by marc-hb** [comment]
> People (understandably) want commands like west flash --bin-file my.bin to mean "you must flash my.bin". But the meaning of the --bin-file option is not "you must flash this bin file", it's "if you are going to flash a bin file, flash this one".

> This is bad UX. [...] The other option would be changing --bin-file etc. to work the way many people expect them to. It's too late to change now in my opinion, as other users are likely expecting them to behave the way they are designed to, bad UX and all.

@mbolivar your description above describes the new options really well, but how about the older design and older options still in use? How does one select the file type? If not using `--bin-file` then how? Past and present.

Same question for both runners that have the new "file=True" capability and have deprecated the older options, and for those runners that don't have the new thing yet.


(I see that `west flash --context -r openocd` has `--use-hex`, etc. Others runners don't)

cc: @MeisterBob
