### ISSUE TITLE
ci: Automatic backport PR detection

### ISSUE THREAD

**Issue by stephanosio** [zephyrproject-rtos/zephyr#52263]
**Is your enhancement proposal related to a problem? Please describe.**

Zephyr Project uses the [Backports project](https://github.com/zephyrproject-rtos/zephyr/projects/19) on GitHub to keep track of the backport pull requests.

The backports pull request are not automatically added to the Backports project and the current process requires the release managers to manually look up the pull requests to the release branches and add them to the list, which is a major inconvenience.

**Describe the solution you'd like**

Add a CI workflow that:

* runs when a pull request is created.
* checks if the base branch of the pull request is a release branch (`v*-branch`).
* adds the pull request to the "Todo" column of the Backports project

**Comment by nashif** [comment]
> * checks if the base branch of the pull request is a release branch (`v*-branch`).

if the base branch is a release branch, why do you need a backport?

**Comment by stephanosio** [comment]
> > * checks if the base branch of the pull request is a release branch (`v*-branch`).
> 
> if the base branch is a release branch, why do you need a backport?

Because we want to detect the PRs that **are** backports, not the PRs to the main that need to be backported.

As described in the issue, the goal is to automatically add the backport PRs (i.e. PRs to the release branches) to the "Backport" project.

**Comment by stephanosio** [comment]
Implemented using the new GH project "Workflows" function. Any PRs labeled "Backport" are automatically added to the "Backports" project (note that the automatic backport action adds "Backport" label to all backport PRs).
