### ISSUE TITLE
boards: thingy53 non-secure (thingy53_nrf5340_cpuapp_ns) does not build

### ISSUE THREAD

**Issue by nordicjm** [zephyrproject-rtos/zephyr#52280]
**Describe the bug**
The thingy53_nrf5340_cpuapp_ns board fails building of various samples e.g. bluetooth samples, due to:
```
warning: SOC_NRF_GPIO_FORWARDER_FOR_NRF5340 (defined at soc/arm/nordic_nrf/nrf53/Kconfig.soc:48) has direct dependencies NRF_SOC_SECURE_SUPPORTED && SOC_NRF5340_CPUAPP && SOC_SERIES_NRF53X && SOC_FAMILY_NRF with value n, but is currently being y-selected by the following symbols:
 - BOARD_ENABLE_CPUNET (defined at boards/arm/thingy53_nrf5340/Kconfig:32), with value y, direct dependencies BOARD_THINGY53_NRF5340_CPUAPP || BOARD_THINGY53_NRF5340_CPUAPP_NS (value: y), and select condition BOARD_THINGY53_NRF5340_CPUAPP || BOARD_THINGY53_NRF5340_CPUAPP_NS (value: y)
Parsing /tmp/aa/zephyr/Kconfig
Loaded configuration '/tmp/aa/zephyr/boards/arm/thingy53_nrf5340/thingy53_nrf5340_cpuapp_ns_defconfig'
Merged configuration '/tmp/aa/zephyr/samples/bluetooth/peripheral_hids/prj.conf'

error: Aborting due to Kconfig warnings
```

It also fails to configure TF-M based samples, e.g. tfm_integration/psa_protected_storage:
```
warning: BUILD_WITH_TFM (defined at modules/trusted-firmware-m/Kconfig.tfm:27, modules/trusted-
firmware-m/Kconfig.tfm:27, soc/arm/nordic_nrf/nrf53/Kconfig.soc:134) was assigned the value 'y' but
got the value 'n'. See http://docs.zephyrproject.org/latest/kconfig.html#CONFIG_BUILD_WITH_TFM
and/or look up BUILD_WITH_TFM in the menuconfig/guiconfig interface. The Application Development
Primer, Setting Configuration Values, and Kconfig - Tips and Best Practices sections of the manual
might be helpful too.


warning: The choice symbol TFM_PROFILE_TYPE_NOT_SET (defined at modules/trusted-
firmware-m/Kconfig.tfm:93, modules/trusted-firmware-m/Kconfig.tfm:93) was selected (set =y), but no
symbol ended up as the choice selection. See
http://docs.zephyrproject.org/latest/kconfig.html#CONFIG_TFM_PROFILE_TYPE_NOT_SET and/or look up
TFM_PROFILE_TYPE_NOT_SET in the menuconfig/guiconfig interface. The Application Development Primer,
Setting Configuration Values, and Kconfig - Tips and Best Practices sections of the manual might be
helpful too.
```

**To Reproduce**
Build bluetooth or TF-M samples

**Expected behavior**
Builds to work

**Impact**
Board is incomplete and does not build

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: Zephyr SDK 0.15.0
 - Commit SHA or Version used: 53a3ff0dfff0fa1191d5d16bc48966993508b09d

**Comment by nordicjm** [comment]
@emob-nordic @joerchan not sure who'd be responsible for this bug

**Comment by emob-nordic** [comment]
@bjornspock who is taking care of thingy53 support? Can you direct us to anyone?

**Comment by bjornspock** [comment]
@emob-nordic  I would ask @MarekPieta or @pdunaj as they were the ones adding the initial support for Thingy:53 in NCS regarding the gpio forwarder issue. Regarding TF-M, when the THingy:53 was launched it was decided that SPM ( which is replaced by TFM) was out of scope for Thingy:53. Hence, SPM (TF-M)was not considered when setting up the static partition map and the Thingy:53 board files.

**Comment by joerchan** [comment]
Close as won't fix. The thingy53_nrf5340_cpuapp_ns board has no valid configuration in zephyr as TF-M is not supported, and no other secure firmware solution exists to enable the NS configuration.
