### ISSUE TITLE
Linker Error using CONSOLE_GETCHAR and CONSOLE_GETLINE

### ISSUE THREAD

**Issue by mkettn** [zephyrproject-rtos/zephyr#52307]
**Describe the bug**

It looks like `console_getline_init` and `console_getline` cannot get linked, when both `CONFIG_CONSOLE_GETLINE` and `CONFIG_CONSOLE_GETCHAR` are enabled in prj.conf

Is this intended?

**To Reproduce**

goto `<zephyr-root>/samples/subsys/console/getline`

add the following line to prj.conf:
CONFIG_CONSOLE_GETCHAR=y

1. mkdir build; cd build
2. cmake -DBOARD=qemu_x86 ..
3. make -j8
4. See error:

```
... 
a lot output during build process
...
[ 89%] Linking C executable zephyr_pre0.elf
/opt/zephyr-sdk-0.15.1/x86_64-zephyr-elf/bin/../lib/gcc/x86_64-zephyr-elf/12.1.0/../../../../x86_64-zephyr-elf/bin/ld.bfd: ../app/libapp.a(main.c.obj): in function `main':
/home/mark/zephyrproject/zephyr/samples/subsys/console/getline/src/main.c:14: undefined reference to `console_getline_init'
/opt/zephyr-sdk-0.15.1/x86_64-zephyr-elf/bin/../lib/gcc/x86_64-zephyr-elf/12.1.0/../../../../x86_64-zephyr-elf/bin/ld.bfd: /home/mark/zephyrproject/zephyr/samples/subsys/console/getline/src/main.c:19: undefined reference to `console_getline'
collect2: error: ld returned 1 exit status
make[2]: *** [zephyr/CMakeFiles/zephyr_pre0.dir/build.make:110: zephyr/zephyr_pre0.elf] Error 1
make[1]: *** [CMakeFiles/Makefile2:2717: zephyr/CMakeFiles/zephyr_pre0.dir/all] Error 2
make: *** [Makefile:91: all] Error 2

```

**Expected behavior**

No linkage error

**Impact**

I cannot use both getchar and getline

**Environment (please complete the following information):**
 - OS: Ubuntu 22.04
 - Toolchain: Zephyr SDK
 - Commit: 9a491a1b5b434549ce7b7a83aacab12eab4dd14e (most recent right now on main branch)

**Comment by kartben** [comment]
Closing with the correct reason as this was improperly marked as "completed".
