### ISSUE TITLE
SAM0 flash driver with page emulated enabled will not write data at 0 block

### ISSUE THREAD

**Issue by benys** [zephyrproject-rtos/zephyr#52309]
**Describe the bug**
I tried to port my program which updates bootloader from main program.
I discovered that program will not update in first page (for example offset 0-128)

Updates doesn't happen because code assumes that nobody will not write any data in first flash page.

**To Reproduce**
1. Use any SAM0 board for example C21N Xpro
2. Make program which changes flash in first page - for example 0 offset
3. Discover that nothing changes in flash

**Expected behavior**
Flash operation should work for all block/page even in 0 offset.

**Impact**
Flash driver

**Environment (please complete the following information):**
 - Any SAM0 board

**Comment by Laczen** [comment]
@benys, would it not be better to initialize (and reset) the offset to an invalid value of the flash_size ?

Please also realize that this BYTE_EMULATION is prone to errors as a result of power failure. When the power is cut just after the erase there will be no data in flash. Using this as a way to provide support for e.g. mcuboot could result in a non-recoverable error.
