### ISSUE TITLE
Bluetooth: Controller: ISOAL ASSERT failure

### ISSUE THREAD

**Issue by carlst** [zephyrproject-rtos/zephyr#52351]
**Describe the bug**
An ASSERT failure occurs in `subsys/bluetooth/controller/ll_sw/isoal.c` `isoal_get_wrapped_time_us()`

**To Reproduce**
1. Using nRF52840DK
2. Edit samples/bluetooth/broadcast_audio_source/src/main.c and set 
    `BROADCAST_SOURCE_LIFETIME  (13 * 2 * 30U)`
3. Build `samples/bluetooth/broadcast_audio_source`
4. Build `samples/bluetooth/broadcast_audio_sink`
5. Run the samples for > 8-9 minutes (until 24-bit ticker wraps)
6. ASSERT occurs
7. N.B. `subsys/bluetooth/controller/ll_sw/nordic/lll/lll_sync_iso.c` `isr_rx_iso_data_valid()` sets timestamp

**Expected behavior**
ASSERT should not occur.

**Impact**
Low priority.

**Environment (please complete the following information):**
 - OS: Windows
 - Toolchain: zephyr-sdk-0.15.1
 - commit 9a491a1b5b434549ce7b7a83aacab12eab4dd14e

**Additional context**
RTT log attached.

[broadcast_audio_source_20221117.txt](https://github.com/zephyrproject-rtos/zephyr/files/10037168/broadcast_audio_source_20221117.txt)

**Comment by cvinayak** [comment]
@niag-Oticon could you analyse?

**Comment by niag-Oticon** [comment]
One of the input time values has most likely exceeded what was considered to be the maximum possible absolute time of the controller's clock in microseconds.
i.e. `#define ISOAL_TIME_WRAPPING_POINT_US      (HAL_TICKER_TICKS_TO_US(HAL_TICKER_CNTR_MASK))`
I guess the sum in `isr_rx_iso_data_valid()` that sets the time-stamp would probably do that when the ticker reaches the end of it's 24-bit range. Let me see if I can get this running locally. Our environment has issues building the upstream.
But is the rationale that we should not see absolute time values that exceed the controller's clock's range sound for Nordic?

**Comment by cvinayak** [comment]
@carlst The fix should be available in v3.3.0-rc1, if you still see issue, please reopen this issue.
