### ISSUE TITLE
STM32: support external ULPI PHY with OTG_HS

### ISSUE THREAD

**Issue by arbrauns** [zephyrproject-rtos/zephyr#52420]
Followup to #12504.

**Is your enhancement proposal related to a problem? Please describe.**
It is currently unclear whether the driver for the OTG_HS peripheral supports using an external ULPI PHY rather than the internal PHY. These ULPI PHYs are used on several ST dev boards such as the STM3240G-EVAL (from the original issue) or the STM32F769I-DISCOVERY (among probably many others); there is no way to use the on-board USB-OTG connectors with the internal PHY.

**Describe the solution you'd like**
If this setup is not yet supported, support should be added to the driver. If such support already exists, a sample should be added to demonstrate how it should be used, esp. regarding devicetree configuration.

**Comment by whati001** [comment]
Hi, any update regarding this issue?
