### ISSUE TITLE
drivers: pinctrl: Use common pinctrl DTS bindings for Cypress psoc6

### ISSUE THREAD

**Issue by henrikbrixandersen** [zephyrproject-rtos/zephyr#52434]
**Is your enhancement proposal related to a problem? Please describe.**
As noted in #39740 the Cypress PSoC6 implementation uses a custom devicetree pinctrl representation (as seen in `dts/arm/cypress/psoc6-pinctrl.dtsi`).

**Describe the solution you'd like**
The Cypress PSoC6 implementation should use one of the standard Zephyr pinctrl devicetree representations as described in https://docs.zephyrproject.org/latest/hardware/pinctrl/index.html#devicetree-representation along with a pinctrl driver.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by gmarull** [comment]
@npal-cy This has been open for a while, is the platform maintained? Should it be removed or is it going to be fixed?

**Comment by ifyall** [comment]
@gmarull, these platforms are being maintained. We will generate a plan internally to bring them up to standards.

**Comment by henrikbrixandersen** [comment]
@ifyall Any updates on this?

**Comment by keithmwheeler** [comment]
Our team will be addressing this issue over the next three weeks; hopefully will complete sooner.

**Comment by npal-cy** [comment]
Working on this now.

**Comment by npal-cy** [comment]
PR is ready for review: https://github.com/zephyrproject-rtos/zephyr/pull/73233
