### ISSUE TITLE
ARC: MWDT: minimal libc includes

### ISSUE THREAD

**Issue by kokas-a** [zephyrproject-rtos/zephyr#52455]
**Describe the bug**
Hi,
I'm working on fixing system includes of C++ headers (via -isystem flag) in #52424 PR. 
I use MWDT toolchain with ARC nsim_hs platform.
 
After I carefully removed MWDT includes, I tried to build Zephyr using built-in Minimal libc. This corresponds to case "NOT CONFIG_ARCMWDT_LIBC" and flag '''-Hno_default_include''' has been passed into toolchain (ref. cmake/compiler/arcmwdt/compiler_flags.cmake). This means that only external (regarding toolchain) includes should be used.

Building has broken with error ` fatal error: 'stddef.h' file not found''.`
Also 'stdarg.h' was not found in header dependencies.

According the issue I'd like to get clarification. Why this two headers (stddef.h and stdarg.h) were not added into Mimimal libc set of includes?
Is this some kind of omission, or headers were not added intentionally?

**To Reproduce**
in cmake/compiler/arcmwdt/target.cmake
replace
```
list(APPEND NOSTDINC ${TOOLCHAIN_HOME}/arc/inc)
```
with
```
if(CONFIG_ARCMWDT_LIBC)
 list(APPEND NOSTDINC ${TOOLCHAIN_HOME}/arc/inc)
endif()
 ```

**Expected behavior**
The build process should not be failed because of missing header errors.

**Impact**

**Logs and console output**
```
In file included from zephyrproject/zephyr/arch/arc/core/offsets/offsets.c:25:
In file included from zephyrproject/zephyr/include/zephyr/kernel.h:17:
zephyrproject/zephyr/include/zephyr/kernel_includes.h:16:10: fatal error: 'stddef.h' file not found
#include <stddef.h>
         ^~~~~~~~~~
1 error generated.
```

**Environment (please complete the following information):**
```
ZEPHYR_TOOLCHAIN_VARIANT=arcmwdt
west -v build -b  nsim_hs samples/hello_world
```
**Additional context**

**Comment by evgeniy-paltsev** [comment]
It seems that it was done intentionally (given how it's implemented for GNU toolchain) that in case of minimal libc implementation we steel uses a few headers from toolchain.

The implementation for ARC MWDT was proper reworked as part of #52606

**Comment by evgeniy-paltsev** [comment]
It seems that it was done intentionally (given how it's implemented for GNU toolchain) that in case of minimal libc implementation we steel uses a few headers from toolchain.

The implementation for ARC MWDT was proper reworked as part of #52606
