### ISSUE TITLE
SPI NOR DPD comment is misleading/wrong

### ISSUE THREAD

**Issue by jeremyherbert** [zephyrproject-rtos/zephyr#52494]
**Describe the bug**
In the latest `spi_nor.c` file it has the following comment: https://github.com/zephyrproject-rtos/zephyr/blob/main/drivers/flash/spi_nor.c

```
/* Device Power Management Notes
 *
 * These flash devices have several modes during operation:
 * * When CSn is asserted (during a SPI operation) the device is
 *   active.
 * * When CSn is deasserted the device enters a standby mode.
 * * Some devices support a Deep Power-Down mode which reduces current
 *   to as little as 0.1% of standby.
 *
 * The power reduction from DPD is sufficient to warrant allowing its
 * use even in cases where Zephyr's device power management is not
 * available.  This is selected through the SPI_NOR_IDLE_IN_DPD
 * Kconfig option.
 *
 * When mapped to the Zephyr Device Power Management states:
 * * PM_DEVICE_STATE_ACTIVE covers both active and standby modes;
 * * PM_DEVICE_STATE_SUSPENDED, and PM_DEVICE_STATE_OFF all correspond to
 *   deep-power-down mode.
 */
```

The last paragraph is the confusing bit, because as far as I can tell there is no power management handling for the NOR flash in the pm subsystem. The only way to enable deep power down in this file is via the `enter_dpd` function, but all calls to this function are conditional on `IS_ENABLED(CONFIG_SPI_NOR_IDLE_IN_DPD)`. 

So it seems that this comment is perhaps misplaced, old or just incorrect and should be removed. Though I would love for someone to prove me wrong :)

**Comment by anangl** [comment]
@jeremyherbert I don't find this comment harmful in any way. To me it just suggests how to handle Zephyr's device PM states in case someone would want to implement those in the driver (that's how I read commit 98a344fe21a4439b0cd1d340635a6ccb3e166f46 where the comment was added). I don't think it's worth removing it, so I'm closing this issue.
