### ISSUE TITLE
GPIO multiple gaps cause incorrect pinout check

### ISSUE THREAD

**Issue by 28itay** [zephyrproject-rtos/zephyr#52506]
**Describe the bug**
The gpio configuration failed because of a gpio pin that "fall" in a gap.

I'm using a custom board with MIMXRT1021CAF4A MCU (it was only 100 pins compare to it's bigger versions), there are 2 gaps in gpio2 one from 0 to 3 and the second from 10 to 15, this was generated using imx_cfg_utils.py (from https://github.com/zephyrproject-rtos/hal_nxp).

![image](https://user-images.githubusercontent.com/89452318/203569995-0075fc9f-bfe6-445e-9dfc-350c7ae4ba1d.png)

While trying to configure gpio_emc_18 the configurate returned -134 (ENOTSUP) error, while debugging the code I found that `mcux_igpio_configure` in drivers/gpio/gpio_mcux_igpio.c in line 58 checks if the pin number fall inside a gap, thinks that pin 18 is inside the second gap, because the gaps values are absolute while the value that it's being compared to is it's relative value.

**To Reproduce**
This isn't was straight forwarded.

I used MIMXRT1020_EVK as a reference board, changed it's MCU to MIMXRT1021CAF4A, generated the relevant gpio pin out using imx_cfg_utils.py.

And tried to configured gpio_emc_18.

**Expected behavior**
For the gpio to be configured as it does exist.

**Impact**
I can't configured the 4 existing gpios that are above the second gap which are gpio_emc_16 through gpio_emc_19.

**Logs and console output**
![image](https://user-images.githubusercontent.com/89452318/203572707-e910e3ee-d504-4737-b9f2-3e2c09b1ffc5.png)
![image](https://user-images.githubusercontent.com/89452318/203572829-3e78d829-b1de-4131-8b8e-91dd06d5dc17.png)

**Environment (please complete the following information):**
 - OS: WSL
 - Toolchain Zephyr SDK 0.15.1
 - Zephyr commit SHA: 4c53a4067a6750987e4ebca354d7e00514b5bd45
 - HAL/NXP commit SHA: 3e3648526824cc5b52ab59d5dd308473e291b760

**Comment by 28itay** [comment]
@DerekSnell 
I'm not sure hot to submit a code 😅, but the change is really simple.
Change line 59 from:
`if (cfg_idx < (config->pin_gaps[i].start +`
to:
`if (pin< (config->pin_gaps[i].start +`

Basically checking if `pin` (the absolute pin value) is in side the current gap (which is also being specified by an absolute values)

**Comment by danieldegrasse** [comment]
Hi @28itay, I've tested your proposed fix on an RT1015 EVK (since the SOC present there has the same pin mux gaps as the RT1021 SOC you have). PR #52610 should fix this issue, it appears that both checks should use `pin` over `cfg_idx`
