### ISSUE TITLE
net: lwm2m: wrong SenML CBOR object link encoding

### ISSUE THREAD

**Issue by broglep-work** [zephyrproject-rtos/zephyr#52527]
Zephyr's SenML CBOR encoding is not in line with the specification. It it using TLV format (encoding the object link into a 32 bit value) instead of using the text format (encoding the link to a string).

References:
- [JSON Format](https://www.openmobilealliance.org/release/LightweightM2M/V1_1-20180710-A/HTML-Version/OMA-TS-LightweightM2M_Core-V1_1-20180710-A.html#Table-744-1-JSON-format-and-description)
- [Object Link Format](https://www.openmobilealliance.org/release/LightweightM2M/V1_1-20180710-A/HTML-Version/OMA-TS-LightweightM2M_Core-V1_1-20180710-A.html#Table-C-1-Data-Types)
- [CBOR Example](https://github.com/OpenMobileAlliance/OMA_LwM2M_for_Developers/issues/484#issuecomment-705490737)

**Comment by rlubos** [comment]
Fixed with https://github.com/zephyrproject-rtos/zephyr/pull/53461
