### ISSUE TITLE
Broken linker script for the esp32 platform

### ISSUE THREAD

**Issue by rillbert** [zephyrproject-rtos/zephyr#52539]
I believe that the linker script `.../zephyr/soc/xtensa/esp32/linker.ld` makes a faulty calculation for the size of read-only data residing in flash. This, in turn, will in some cases yield an incorrect configuration of the Cache MMU resulting in difficult-to-find application crashes with 'LoadException' or similar.

The error is that the value of `_image_drom_size` is calculated as:

```
 _image_drom_size = LOADADDR(_RODATA_SECTION_NAME) + SIZEOF(_RODATA_SECTION_NAME) - _image_drom_start;
```
but there are _more sections than `rodata` that are mapped to the flash_ and thus need to be taken into consideration when setting up the Cache MMU.

The long-and-short of it is that the `_image_drom_size` value is set too small with the current linker script.

`_image_drom_size` is used in zephyr's startup code (`static int map_rom_segments(void)`) to configure the Cache MMU mapping. A too small value will sometimes lead to the case where the last flash block that should be mapped in fact is not, leading to difficult-to-find crashes.

The tricky bit is that this only explodes when the erroneously calculated value is just under 64KB (the Cache MMU granularity) but the readonly data missing in the calculation tips it above a 64KB boundary.

To fix this, all data from the included `...common-rom...` files in `linker.ld` should also be included in `_image_drom_size`, that is the lines:

```
  /* Flash segments (rodata and text) should be mapped in virtual address space by providing VMA.
   * Executing directly from LMA is not possible. */
  #pragma push_macro("GROUP_ROM_LINK_IN")
  #undef GROUP_ROM_LINK_IN
  #define GROUP_ROM_LINK_IN(vregion, lregion) > RODATA_REGION AT > lregion
  #include <zephyr/linker/common-rom/common-rom-cpp.ld>
  #include <zephyr/linker/common-rom/common-rom-kernel-devices.ld>
  #include <zephyr/linker/common-rom/common-rom-ztest.ld>
  #include <zephyr/linker/common-rom/common-rom-net.ld>
  #include <zephyr/linker/common-rom/common-rom-bt.ld>
  #include <zephyr/linker/common-rom/common-rom-debug.ld>
  #include <zephyr/linker/common-rom/common-rom-misc.ld>
  #pragma pop_macro("GROUP_ROM_LINK_IN")
```

I have tested this by hacking the `linker.ld` in order for the above sections to also be included in the value of `_image_drom_size`. And verified that the Cache MMU is setup incorrectly with the stock version and correctly with my hack (provided as an attachment).

**To Reproduce**
It is difficult to give an exact scenario but this is a shot:
1. build an application _without enabling the shell_ where the linker script reports a `_image_drom_size` size just under 64KB (say 0xfec0)
2. run the application

If you're lucky, it will run.

3. enable the shell for the same application in the prj.config file
4. build again and make sure that the `_image_drom_size` is still reported below 64KB
5. run the application and watch it explode when you try to use the shell by issuing different commands.

**Impact**
Disaster

**Logs and console output**

The below is an example output from a zephyr.map file showing the problematic behavior.

```
...
.rela.dyn
 *(SORT_BY_ALIGNMENT(.rela.*))
                0x0000000000000040                _image_drom_start = LOADADDR (rodata)

/* NOTE the reported size 0xfe34 for the _image_drom_size */

                0x000000000000fe34                _image_drom_size = ((LOADADDR (rodata) + SIZEOF (rodata)) - _image_drom_start)
                0x000000003f400040                _image_drom_vaddr = ADDR (rodata)

rodata          0x000000003f400040     0xfe34 load address 0x0000000000000040
                0x000000003f400040                _rodata_start = ABSOLUTE (.)

...

 .rodata_wlog_warning.4
                0x000000003f40fe3c        0x9 /home/anders/maintrac/zephyr_os/modules/hal/espressif/zephyr/esp32/../blobs/lib/esp32/libpp.a(hal_mac_tx.o)
 .rodata_wlog_warning.3
                0x000000003f40fe45       0x2f /home/anders/maintrac/zephyr_os/modules/hal/espressif/zephyr/esp32/../blobs/lib/esp32/libpp.a(hal_mac_tx.o)
                0x000000003f40fe74                _thread_local_end = ABSOLUTE (.)
                0x000000003f40fe74                . = ALIGN (0x4)

/* NOTE the last entry in the .rodata section is at 0xfe74, that is _image_drom_size + 0x40 */

/* NOTE - The below data is set by the ...common-rom... includes in the linker script but is 
    _not included_ in the _image_drom_size and if this data happens to pass a 64KB boundary, the   
   corresponding flash block will _not be mapped_ in the Cache MMU */

initlevel       0x000000003f40fe74       0x88 load address 0x000000000000fe74
                0x000000003f40fe74                __init_start = .
                0x000000003f40fe74                __init_EARLY_start = .
 *(SORT_BY_NAME(SORT_BY_ALIGNMENT(.z_init_EARLY[0-9]_*)))
 *(SORT_BY_NAME(SORT_BY_ALIGNMENT(.z_init_EARLY[1-9][0-9]_*)))
                0x000000003f40fe74                __init_PRE_KERNEL_1_start = .

...

/* NOTE in this particular example the boundary happens to be passed  at the  .shell_root_cmd_hwinfo 
   symbol and, sure enough, this application crashes hard when the shell code tries to enumerate the 
   available shell commands */

 .shell_root_cmd_history
                0x000000003f40fffc        0x4 zephyr/libzephyr.a(shell_cmds.c.obj)
 .shell_root_cmd_hwinfo
                0x000000003f410000        0x4 zephyr/drivers/hwinfo/libdrivers__hwinfo.a(hwinfo_shell.c.obj)
 .shell_root_cmd_kernel
                0x000000003f410004        0x4 zephyr/libzephyr.a(kernel_service.c.obj)
 .shell_root_cmd_log
                0x000000003f410008        0x4 zephyr/libzephyr.a(log_cmds.c.obj)
 .she
```

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04
 - Toolchain Zephyr-SDK 0.15.1
 - Zephyr commit sha: b1d1f442
 
[linker.ld.zip](https://github.com/zephyrproject-rtos/zephyr/files/10086816/linker.ld.zip)

**Comment by sylvioalves** [comment]
@rillbert I think you are correct, there is a missing area to be added in there. Thanks for noticing this and offering some solution as well. I'll try to reproduce and bring a PR for this.
