### ISSUE TITLE
missing test for kernel event logger

### ISSUE THREAD

**Issue by nashif** [zephyrproject-rtos/zephyr#5254]
while we have a sample for the kernel event logger, we are missing a test that verifies the implementation and values. A test that verifies all functionality and options is needed to improve kernel code coverage.

Options to verify:

- [ ] KERNEL_EVENT_LOGGER
- [ ] KERNEL_EVENT_LOGGER_BUFFER_SIZE
- [ ] KERNEL_EVENT_LOGGER_DYNAMIC
- [ ] KERNEL_EVENT_LOGGER_CUSTOM_TIMESTAMP
- [ ] KERNEL_EVENT_LOGGER_CONTEXT_SWITCH
- [ ] KERNEL_EVENT_LOGGER_INTERRUPT
- [ ] KERNEL_EVENT_LOGGER_SLEEP
- [ ] KERNEL_EVENT_LOGGER_THREAD

**Comment by SavinayDharmappa** [comment]
@nashif  do i have to implement it as ztest ?

**Comment by nashif** [comment]
@SavinayDharmappa yes

**Comment by carlescufi** [comment]
@SavinayDharmappa Do you plan to fix this in time for 1.11? (timeline is end of February)

**Comment by SavinayDharmappa** [comment]
@carlescufi yes i have just started . I will be pushing first set of patch by end on next week .

**Comment by linkmeyer** [comment]
I moved the milestone to v1.12 per Manoj's feedback that it will not be fixed until then.

**Comment by nashif** [comment]
closing, this interface will be deprecated.
