### ISSUE TITLE
Add support for different SDHC high-speed modes (currently defaults to SDR25)

### ISSUE THREAD

**Issue by plinnie** [zephyrproject-rtos/zephyr#52589]
**Is your enhancement proposal related to a problem? Please describe.**
In de SDMMC subsystem the high-speed mode defaults to SDR25. However, atmel only supports Legacy High-Speed mode and can't switch to the required 1.8 V required for SDR25.

**Describe the solution you'd like**
The function `sdmmc_init_hs(struct sd_card *card)` should be modified such that high-speed mode is derived from the capabilities as provided by the SD card AND the driver, such that the best mode is chosen for that combination of SD card and host interface.

**Describe alternatives you've considered**
I'm now not enabling high-speed mode, which seems to work, but does not provide me with the maximum performance.

**Additional context**
This is where the SDMMC defaults to SDR 25 MHz mode
https://github.com/zephyrproject-rtos/zephyr/blob/027b79ecc4f71d36dbd89b9e0fb1dab7d096f0f7/subsys/sd/sdmmc.c#L947

**Comment by danieldegrasse** [comment]
Reopening this, as it is still an issue I need to address
