### ISSUE TITLE
drivers: sensors: bmi08x config file

### ISSUE THREAD

**Issue by XenuIsWatching** [zephyrproject-rtos/zephyr#52652]
## Origin

Binary blob `bmi08x_config_file[]` from: https://github.com/BoschSensortec/BMI08x-Sensor-API/blob/631a966891885643f180e18e94870411b8f4c3fc/bmi08a.c#L69

## Purpose

This is written to the BMI08x to enable Data Sync as described in this App Note. https://www.bosch-sensortec.com/media/boschsensortec/downloads/application_notes_1/bst-mis-an006.pdf

## Mode of integration

Integration in to the main tree as a standalone header file

## Maintainership

@XenuIsWatching 

## Pull Request

https://github.com/zephyrproject-rtos/zephyr/pull/51545 as the file `bmi08x_config_file.h`

## Description

Please view the app note for the bmi08x for data synchronization between the accelerometer and gyroscope https://www.bosch-sensortec.com/media/boschsensortec/downloads/application_notes_1/bst-mis-an006.pdf

## Dependencies

None

## Revision

https://github.com/BoschSensortec/BMI08x-Sensor-API Tag 1.5.8

## License

BSD-3-Clause

**Comment by MaureenHelm** [comment]
Approved by the TSC on 13 Dec 2022 via email vote.
