### ISSUE TITLE
Ensure the Licensing page is up-to-date for the release 

### ISSUE THREAD

**Issue by Shilpashree3lc** [zephyrproject-rtos/zephyr#5266]
Ensure the "Licensing of Zephyr Project Components" page is updated and correct for the release. See https://www.zephyrproject.org/doc/1.7.0/LICENSING.html.

**Comment by Shilpashree3lc** [comment]
Quick review show the below list of files are NOT having any license.

tests/net/socket/tcp/src/main.c
boards/arm/stm32l476g_disco/pinmux.c
samples/basic/threads/src/main.c

**Comment by pfalcon** [comment]
> Quick review show the below list of files are NOT having any license.

Which would mean they're licensed under the project license...

Let us know how you'd like to get those resolved - original authors submit patches, or you'd fix that handful of cases on your side. @askawu : FYI, re: tests/net/socket/tcp/src/main.c

**Comment by nashif** [comment]
> Which would mean they're licensed under the project license...

true, but we need the header including any copyrights for every file to remove ambiguity
