### ISSUE TITLE
I2C: STM32F0 can't switch to HSI clock by default and change timing

### ISSUE THREAD

**Issue by andy3469** [zephyrproject-rtos/zephyr#52675]
Even with the dts correctly set we can't set the HSI clock for I2C1 peripheral and change the timings accordingly.

```
clocks = <&rcc STM32_CLOCK_BUS_APB1 0x00200000>,
	         <&rcc STM32_SRC_HSI I2C1_SEL(2)>;
	clock-frequency = <I2C_BITRATE_STANDARD>;
	timings = <48000000 I2C_BITRATE_STANDARD 0x20303E5D>,
	          <48000000 I2C_BITRATE_FAST 0x2010091A>,
	          <8000000 I2C_BITRATE_STANDARD 0x2000090E>,
	          <8000000 I2C_BITRATE_FAST 0x0000020B>;
```

The clock is instantly set to SYSCLK and it doesn't check if another clock is set inside the clocks property.
https://github.com/zephyrproject-rtos/zephyr/blob/2bfc4451cf4d39b585d9a65f86d8b38facc84277/drivers/i2c/i2c_ll_stm32.c#L238-L250

We can't even use the `i2c_configure` function as it also force the clock to SYSCLK.

Actually, the only way is to disable the I2C, change the clock with `clock_control_configure`, change the timing with `LL_I2C_SetTiming` and enable the I2C inside the application code...

Is it possible to change the driver as to make sure the right clock is selected on init or when we use `clock_control_configure` and `i2c_configure` ?

**Comment by gautierg-st** [comment]
Please have a look at PR #53216. It adds support for I2C source clock in the dts.
You'll have to set <&rcc STM32_SRC_HSI I2C1_SEL(0)> in your board configuration, and not I2C1_SEL(2) since F0 has only two choices for source clock
