### ISSUE TITLE
drivers: wifi: esp_at: Some issues on Passive Receive mode

### ISSUE THREAD

**Issue by ccli8** [zephyrproject-rtos/zephyr#52702]
**Describe the bug**
ESP8266 supports Passive Receive mode (`CONFIG_WIFI_ESP_AT_PASSIVE_MODE`).
Without enable, ESP8266 shield will continuously push data to board (`+IPD`) anyway on receive and board's Rx buffer can get OOM easily. However, current driver implementation on Passive Receive mode has the following issues:

**Issue 1**:
On `<conn_id>,CLOSED`, driver closes the socket prematurely and buffered Rx data on ESP8266 shield gets unable to fetch (`AT+RECVDATA`).
https://github.com/zephyrproject-rtos/zephyr/blob/56284d7017dc593f18c3aaa128d2c4e596a8e4c8/drivers/wifi/esp_at/esp_offload.c#L510-L511
https://github.com/zephyrproject-rtos/zephyr/blob/56284d7017dc593f18c3aaa128d2c4e596a8e4c8/drivers/wifi/esp_at/esp_socket.c#L154-L158

**Issue 2**:
On `+IPD`, driver doesn't consider available Rx buffer and straight schedules to fetch buffered Rx data on ESP8266 shield, still causing Rx buffer OOM. One approach may pre-allocate Rx buffer before the schedule.
https://github.com/zephyrproject-rtos/zephyr/blob/56284d7017dc593f18c3aaa128d2c4e596a8e4c8/drivers/wifi/esp_at/esp.c#L659-L663

**To Reproduce**
The issues are re-produced on one Cortex-M4 board which is to plan to add into Zephyr, but I think another board with ESP8266 shield can also re-produce the issues.

**Issue 1**:
1. Add WiFi connection into `samples/net/sockets/http_get`
2. Build with `CONFIG_WIFI_ESP_AT_PASSIVE_MODE=y` and ESP8266 shield enabled.
3. Flash and run

**Issue 2**:
1. Add WiFi connection into `samples/net/sockets/big_http_download`
2. Add k_msleep(8000) in `big_http_download.c` `download()` while loop.
3. Build with `CONFIG_WIFI_ESP_AT_PASSIVE_MODE=y` and ESP8266 shield enabled.
4. Flash and run

**Expected behavior**
**Issue 1**:
You will see http request is sent but http response is not received.

**Issue 2**:
You will see `net_pkt:` is failed to allocate.

**Logs and console output**
**Issue 1**:
Note http response is not received.

```
Preparing HTTP GET request for http://google.com:80/
getaddrinfo status: 0
addrinfo @0x20009bc8: ai_family=1, ai_socktype=1, ai_protocol=6, sa_family=1, sin_port=5000
sock = 0
Response:

```

**Issue 2**:
Note `net_pkt` is failed to allocate.

```
Preparing HTTP GET request for http://archive.ubuntu.com:80/ubuntu/dists/xenial/main/installer-amd64/current/images/hd-media/vmlinuz
addrinfo @0x2000bc88: ai_family=1, ai_socktype=1, ai_protocol=6, sa_family=1, sin_port=5000

Iteration 1 of 3:
sock = 0
[00:00:13.867,000] <err> wifi_esp_at: Failed to get net_pkt: len 1394
Download progress: 3581 Bytes; 3 KiB; 0 MiB
```

**Environment (please complete the following information):**
 - OS: Windows 10
 - Toolchain: GNU Arm Embedded Toolchain 10.3-2021.07
 - Commit 3f0e8dda3d72bd9dda069bc0c013d7d67f593c7e

**Comment by kartben** [comment]
Closing with the correct reason as this was improperly marked as "completed".
