### ISSUE TITLE
bl5340_dvk_cpuapp has wrong button for mcuboot button

### ISSUE THREAD

**Issue by nordicjm** [zephyrproject-rtos/zephyr#52741]
**Describe the bug**
The bl5340 dvk board has a dedicated boot button, instead the mcuboot button is using one of the 4 application buttons, which is wrong, and pulls in the whole i2c driver and port expander driver, which conversely makes mcuboot far too big to build for the board.

**Environment (please complete the following information):**
 - Commit SHA or Version used: 4d906d944bf34de355f55e0e278550bebee8a106

**Comment by kartben** [comment]
Closing with the correct reason as this was improperly marked as "completed".
