### ISSUE TITLE
tests/drivers/bbram: Refactor to use a common prj.conf

### ISSUE THREAD

**Issue by erwango** [zephyrproject-rtos/zephyr#52754]
**Is your enhancement proposal related to a problem? Please describe.**
Implementation of `tests/drivers/bbram` doesn't use a common prj.conf but requires each platform to declare it's own \<vendor\>.conf
file that are all copy paste of each others

**Describe the solution you'd like**
Refactor test to use a single prj.conf and vendors overlays when required

**Comment by markCwatson** [comment]
Hi @erwango you can assign this issue to me. I will take care of it. It is only my second contribution, so please expect to give some feedback. Thanks.

**Comment by markCwatson** [comment]
@erwango I have an [open PR](https://github.com/zephyrproject-rtos/zephyr/pull/53344) that is good to go and ready for approval.
