### ISSUE TITLE
Error While adding the mcuboot folder in repo.

### ISSUE THREAD

**Issue by jyotibabasahebyadav-eaton** [zephyrproject-rtos/zephyr#52779]
Hi We are using the nordic sdk 1.9.1.
I have created my own project and i want whole sdk commit to my repo. I am able to build the project.I am not able to commit the mcuboot, It showing the error you are not able to commit the git repository under another git repository.

1 .If i remove .git folder in the sdk then we are able to commit but nothing got committed in the mcuboot folder .I am not able to build the project.
2 .I have tried to create the mcuboot as repository which contain the same file which mcuboot repo having and add as the submodule to my repo still am facing the build issue
can you please explain by removing the .git folder we are facing the build issue. What is the role of .git folder of mcuboot for the successfully building of the project.

Is there is any way to commit the whole nordic sdk.

**Comment by nordicjm** [comment]
1. ncs support should go to https://devzone.nordicsemi.com/ - this repo is for upstream zephyr
2. "I have created my own project and i want whole sdk commit to my repo" This is completely invalid, it is not supported, it will not work

Closing as unrelated to zephyr.
