### ISSUE TITLE
http: client: lack of ability to parse chunked data

### ISSUE THREAD

**Issue by Likailiu** [zephyrproject-rtos/zephyr#5278]
We are trying to download a large file from a web server on the Internet, the web server sends chunked data over HTTP 1.1, and our application sometimes gets wrong data which contains characters such as CR and LF from “http_app_client” in http library. Unfortunately we found that on_chunk_header() and on_chunk_complete() in http library are left unimplemented, so we are afraid that current http library doesn’t support parsing chunked data. In this case we have to reparse the data in our application which is probably not what we are supposed to do. We are looking forward to a fully functional http library in the near future.

**Comment by jukkar** [comment]
This refers to old and already removed HTTP API so closing it.
