### ISSUE TITLE
ATWINC1500 : (wifi_winc1500_nm_bsp.c : nm_bsp_reset) The reset function is not logical and more 

### ISSUE THREAD

**Issue by hichemMenta** [zephyrproject-rtos/zephyr#52792]
Hello,

I use the nRF5340 DK and the nRF Connect SDK. 
The module used is ATWINC1500-XPRO.

The bug comes from the nm_bsp_reset function in the 
drivers/wifi/winc1500/wifi_winc1500_nm_bsp.c.

```
void nm_bsp_reset(void)
{
	gpio_pin_set_dt(&winc1500_config.chip_en_gpio, 0);
	gpio_pin_set_dt(&winc1500_config.reset_gpio, 0);
	nm_bsp_sleep(100);

	gpio_pin_set_dt(&winc1500_config.chip_en_gpio, 1);
	nm_bsp_sleep(10);

	gpio_pin_set_dt(&winc1500_config.reset_gpio, 1);
	nm_bsp_sleep(10);
}
```

At the end of the reset function (nm_bsp_reset), the reset pin stays in the active state, low physical level. 
This is not the expected behavior. 

The problem is that the function `gpio_pin_set_dt`  is not used correctly.
It is a regression. This part of the code has changed 5 months ago. 
![git](https://user-images.githubusercontent.com/100126269/205644590-6a0098d6-0ebd-4ad9-bf2b-2e7b7b1ba6b7.png)
The function is used in the physical sense and not in the logical sense which is not correct because the reset pin is active in the low state.

I am convinced that the WINC1500 driver has not been fully tested, as I cannot get the module to work. 
The chip_id check fails.

Thanks,
Hichem

**Comment by GeorgePriestner-Eaton** [comment]
Is this still an issue?
@hichemMenta Did you set the reset-gpio to GPIO_ACTIVE_LOW in the device tree?

![image](https://github.com/zephyrproject-rtos/zephyr/assets/99959954/5f4babf5-e220-41ce-9752-610a39b7b632)

**Comment by GeorgePriestner-Eaton** [comment]
@hichemMenta How did you resolve? Codebase still seems the same.
