### ISSUE TITLE
Overflow in settime posix function

### ISSUE THREAD

**Issue by AndreyDodonov-EH** [zephyrproject-rtos/zephyr#52825]
**Describe the bug**
Overflow in settime posix function

This is a follow-up of https://github.com/zephyrproject-rtos/zephyr/issues/41111
and https://github.com/zephyrproject-rtos/zephyr/pull/41814/

In this PR gettime function was changed: https://github.com/zephyrproject-rtos/zephyr/pull/41814/
Settime uses same conversion and has same effect.
So API should be symmetrical.

**Comment by AndreyDodonov-EH** [comment]
Obviously it will reduce precision, but it was already done anyway by changing gettime function.

**Comment by nordic-krch** [comment]
> Obviously it will reduce precision, but it was already done anyway by changing gettime function.

It does not reduce the precision. It's just that calculation is performed on seconds and only remainder is in nanoseconds. Contrary to the approach where all is calculated in nanoseconds and that can result in overflow.

**Comment by AndreyDodonov-EH** [comment]
> > Obviously it will reduce precision, but it was already done anyway by changing gettime function.
> 
> It does not reduce the precision. It's just that calculation is performed on seconds and only remainder is in nanoseconds. Contrary to the approach where all is calculated in nanoseconds and that can result in overflow.

But doesn't in this case remainder have milliseconds precision? (even though saved in ns member of the struct)
I'm talking about using ms in settime.

**Comment by cfriedt** [comment]
@AndreyDodonov-EH - can you verify that this is also fixed by #52977

**Comment by AndreyDodonov-EH** [comment]
> @AndreyDodonov-EH - can you verify that this is also fixed by #52977

Will check on Tuesday, thanks for updating!

**Comment by AndreyDodonov-EH** [comment]
@NilsRuf-EH FYI

**Comment by AndreyDodonov-EH** [comment]
@cfriedt 
Thanks for pinging!
We had a look at your PR, and it fixes the symmetry problem which I mention in this issue.

As for the settime overflow issue, it is addressed in https://github.com/zephyrproject-rtos/zephyr/commit/50c7c7b1e4027b08a594f108df5d62bce1fc229f

However, it depends there on an arbitrary rule-of-thumb constant `CONFIG_SYS_CLOCK_MAX_TIMEOUT_DAYS`, which is by default 365, which means device is expected to have maximum uptime of roughly a year.

**Comment by cfriedt** [comment]
> However, it depends there on an arbitrary rule-of-thumb constant `CONFIG_SYS_CLOCK_MAX_TIMEOUT_DAYS`, which is by default 365, which means device is expected to have maximum uptime of roughly a year.

@AndreyDodonov-EH - I agree. I'm not a huge fan of the concept of `CONFIG_SYS _CLOCK_MAX_TIMEOUT_DAYS` either.

I feel like the better thing to do would be to specify either
* the number of bits in the counter (preferable)
* the counter maximum (less preferable)

**Comment by cfriedt** [comment]
@AndreyDodonov-EH - I'm going to close this because it seems as though the issues have been resolved. 

If there are other related enhancement requests, please open up a new issue.
