### ISSUE TITLE
reference to non-existing functions in arch/x86/core/intstub.S

### ISSUE THREAD

**Issue by nashif** [zephyrproject-rtos/zephyr#5283]
```

 * Only the volatile integer registers are saved since ISRs are assumed not to
 * utilize floating point (or SSE) instructions.  If an ISR requires the usage
 * of floating point (or SSE) instructions, it must first invoke nanoCpuFpSave()
 * (or nanoCpuSseSave()) at the beginning of the ISR.  A subsequent
 * nanoCpuFpRestore() (or nanoCpuSseRestore()) is needed just prior to returning
 * from the ISR.  Note that the nanoCpuFpSave(), nanoCpuSseSave(),
 * nanoCpuFpRestore(), and nanoCpuSseRestore() APIs have not been
 * implemented yet.

```

most of the above functions were probably renamed and do not exist, need to clean this up and use current implementation functions in the docs.

**Comment by dbkinder** [comment]
Note the mentioned documentation says these APIs have not been implemented yet, so perhaps they never have, and we should just delete this paragraph except for the first sentence?

**Comment by carlescufi** [comment]
@andrewboie could you give us the names of the functions that replace the former `nano*` ones?
