### ISSUE TITLE
Bluetooth: Unable use native_posix with shell demo

### ISSUE THREAD

**Issue by LingaoM** [zephyrproject-rtos/zephyr#52878]
**Describe the bug**
Hi, i'm use latest main branch,

`west build -b native_posix zephyr/tests/bluetooth/shell -p auto`

`sudo ./build/zephyr/zephyr.exe --bt-dev=hci0`

No boot information at all.
![middle_img_v2_a2fbdf78-04ee-41e3-9bf6-701f4ca4bddl](https://user-images.githubusercontent.com/26378606/206381895-5f662cac-1e85-419e-a355-b0a81ab46cc7.png)

**Comment by nordicjm** [comment]
Did you connect a serial utility to `/dev/pts/18` as the output indicated?

**Comment by LingaoM** [comment]
yeah，no response at all

**Comment by nordicjm** [comment]
Works fine here.
```
uart connected to pseudotty: /dev/pts/1
```
and
```
uart:~$ 
  bt       clear    device   devmem   flash    gatt     help     history
  hrs      iso      kernel   l2cap    log      resize   shell    stats
uart:~$ kernel 
  cycles     stacks     threads    uptime     version    sleep      log-level
uart:~$ kernel 
  cycles     stacks     threads    uptime     version    sleep      log-level
uart:~$ kernel version 
Zephyr version 3.2.99
uart:~$ 
```

**Comment by LingaoM** [comment]
please type: bt init

**Comment by LingaoM** [comment]
Confirm my problem. Sorry to bother you.
