### ISSUE TITLE
Bluetooth: Add functionality for bt_disable for off-chip HCI drivers

### ISSUE THREAD

**Issue by sean-madigan** [zephyrproject-rtos/zephyr#52907]
**Is your feature request related to a problem? Please describe.**
At the moment bt_disable cannot be used with rpmsg, spi, uart etc. 

**Describe the solution you'd like**
Currently bt_hci_driver.open just sets up communication for off-chip HCI drivers, this would also have to also set up the controller on this command. A bt_hci_driver.close functionality would have to be implemented that tears down the controller.

**Comment by pawelosyp-hid** [comment]
In my project I have observed the same issue. Is there any update?

**Comment by swojo** [comment]
We're facing the same issue as well.

**Comment by jori-nordic** [comment]
I was doing something like this in https://github.com/zephyrproject-rtos/zephyr/pull/55648 .
The building blocks are here, it just needs implementation (has to be different for every driver).
