### ISSUE TITLE
tests/net/ieee802154/crypto:  linking error

### ISSUE THREAD

**Issue by gurucharanx** [zephyrproject-rtos/zephyr#5296]
Currently the crypto test is failing because of the linking error as shown below.

Scanning dependencies of target arch__x86__soc__ia32
[ 84%] Building C object zephyr/arch/x86/soc/ia32/CMakeFiles/arch__x86__soc__ia32.dir/soc.c.obj
[ 85%] Linking C static library libarch__x86__soc__ia32.a
[ 85%] Built target arch__x86__soc__ia32
Scanning dependencies of target zephyr_prebuilt
[ 86%] Building C object zephyr/CMakeFiles/zephyr_prebuilt.dir/misc/empty_file.c.obj
[ 87%] Linking C executable zephyr_prebuilt.elf
libzephyr.a(ieee802154_cc2520.c.obj): In function `cc2520_init':
/home/intel/v1.10/zephyr/drivers/ieee802154/ieee802154_cc2520.c:1072: **undefined reference to `cc2520_configure_gpios'**
collect2: error: **ld returned 1 exit status**
zephyr/CMakeFiles/zephyr_prebuilt.dir/build.make:102: recipe for target 'zephyr/zephyr_prebuilt.elf' failed
make[3]: *** [zephyr/zephyr_prebuilt.elf] Error 1
CMakeFiles/Makefile2:443: recipe for target 'zephyr/CMakeFiles/zephyr_prebuilt.dir/all' failed
make[2]: *** [zephyr/CMakeFiles/zephyr_prebuilt.dir/all] Error 2
CMakeFiles/Makefile2:2191: recipe for target 'zephyr/cmake/qemu/CMakeFiles/run.dir/rule' failed
make[1]: *** [zephyr/cmake/qemu/CMakeFiles/run.dir/rule] Error 2
Makefile:534: recipe for target 'run' failed
make: *** [run] Error 2

The test has been verified on zephyr v1.10.0-rc3.
The steps I have followed for this test case verification is as below

$ cd  tests/net/ieee802154/crypto/
$ mkdir build && cd build/ && cmake -D BOARD=qemu_x86 ../ &&make clean && make run

**Comment by tbursztyka** [comment]
See testcase.yaml  in the sample, it is meant to be built only for quark_se_c1000_devboard
