### ISSUE TITLE
Add triage permissions for dianazig

### ISSUE THREAD

**Issue by keith-zephyr** [zephyrproject-rtos/zephyr#52995]
# Nomination

## GitHub User

Provide the following information about the GitHub user:

1. Diana Zigterman
1. dianazig
1. Google

## Supporting Documents

Diana is a USB-C power delivery expert.  We would like to enable triage permission so Diana can participate in reviews of the USB-C power delivery subsystem on Zephyr.

https://github.com/zephyrproject-rtos/zephyr/pull/39383
https://github.com/zephyrproject-rtos/zephyr/pull/51660

**Comment by keith-zephyr** [comment]
@DianaZig for visibility

**Comment by stephanosio** [comment]
@DianaZig has been added as a user with Triage permission.

**Comment by DianaZig** [comment]
Thank you!
