### ISSUE TITLE
Invalid ISO interval configuration

### ISSUE THREAD

**Issue by giuseppebarba** [zephyrproject-rtos/zephyr#53008]
As indicated in the comment the "iso_interval shall be at least SDU interval, or integer multiple of SDU interval for unframed PDUs" but the implemented formula can return iso_intervals sub multiple of sdu_interval (e.g.: iso_interval = 1/2 sdu_interval)

https://github.com/zephyrproject-rtos/zephyr/blob/72db5c09c04a81fbf4e9536cfe357c11fe3e2c97/subsys/bluetooth/controller/ll_sw/ull_adv_iso.c#L321-L322

**Comment by cvinayak** [comment]
```
BN shall be an integer multiple of ISO_Interval ÷ SDU_Interval and shall be at
least ceil(Max_SDU ÷ Max_PDU) × (ISO_Interval ÷ SDU_Interval).
```

`iso_interval_us` is derived based on the above statement in BT Core Spec. v5.3 Vol 6 Part G Section 2.1 UNFRAMED PDU

And from Section BT Core Spec. v5.3 Vol 6 Part B Section 4.4.6.3 BIG parameters

```
• Max_PDU is the maximum number of data octets (excluding the MIC, if any)
that can be carried in each BIS Data PDU in the BIG. The value shall be
between 1 and 251 octets.
• Max_SDU is the maximum size of an SDU on this BIG (see [Vol 6] Part G,
Section 1). The value shall be between 1 and 4095 octets.
```

```
The value of BN shall be between 1 and 7.
```

Hence, in order to be able to transmit a 4095 octets SDU with 251 bytes PDU, there have to be 3 ISO Intervals of BN=7 each per SDU_Interval.

Your implementation suggestions are welcome, i.e. if there is something I am missing here or the implementation needs changes.

**Comment by giuseppebarba** [comment]
As you stated:

> BN shall be an integer multiple of ISO_Interval ÷ SDU_Interval and shall be at
>
> least ceil(Max_SDU ÷ Max_PDU) × (ISO_Interval ÷ SDU_Interval).
>
>
> iso_interval_us is derived based on the above statement in BT Core Spec.
> v5.3 Vol 6 Part G Section 2.1 UNFRAMED PDU
>
ISO_Internal has to be greater than SDU_Interval.


> And from Section BT Core Spec. v5.3 Vol 6 Part B Section 4.4.6.3 BIG
> parameters
>
> • Max_PDU is the maximum number of data octets (excluding the MIC, if any)
>
> that can be carried in each BIS Data PDU in the BIG. The value shall be
>
> between 1 and 251 octets.
>
> • Max_SDU is the maximum size of an SDU on this BIG (see [Vol 6] Part G,
>
> Section 1). The value shall be between 1 and 4095 octets.
>
>
> The value of BN shall be between 1 and 7.
>
>
> Hence, in order to be able to transmit a 4095 octets SDU with 251 bytes
> PDU, there have to be 3 ISO Intervals of BN=7 each per SDU_Interval.
>
You have to use framed mode to send a huge SDU. Otherwise the previous
constraint about ISO_Interval vs SDU_interval is not respected.
But this is not clear in the spec and shall be discussed in SIG.
I saw that you have opened a ticket (ES-22506). There is already a ticket
for the same aspect: ES-22475. We will see what is the common thinking
about this!

Your implementation suggestions are welcome, i.e. if there is something I

**Comment by kartben** [comment]
Closing with the correct reason as this was improperly marked as "completed".
