### ISSUE TITLE
Delaying logging via CONFIG_LOG_PROCESS_THREAD_STARTUP_DELAY_MS doesn't work if another backend is disabled

### ISSUE THREAD

**Issue by xyzzy42** [zephyrproject-rtos/zephyr#53000]
**Describe the bug**
One of the purposes of CONFIG_LOG_PROCESS_THREAD_STARTUP_DELAY_MS was to allow time to connect to a USB CDC ACM UART before logging starts and messages are discarded.

This fails to work correctly if another logging backend is disabled during the delay before logging starts.

All log messages generated before the logging thread starts will be discarded, rather than saved until the thread starts and then processed after backends are initialized.

**To Reproduce**
1. Enable CONFIG_LOG_BACKEND_UART and CONFIG_SHELL_LOG_BACKEND and runtime filtering.
2. Set CONFIG_LOG_PROCESS_THREAD_STARTUP_DELAY_MS
3. In main(), disable shell_uart_backend:
```c
for (int i = 0; i < log_backend_count_get(); i++) {
        const struct log_backend *backend = log_backend_get(i);
        if (!strcmp(backend->name, "shell_uart_backend")) {
                log_backend_disable(backend);
                break;
        }
}
```
4. Log messages periodically, both before and after CONFIG_LOG_PROCESS_THREAD_STARTUP_DELAY_MS

**Expected behavior**
When CONFIG_LOG_PROCESS_THREAD_STARTUP_DELAY_MS expires, all log messages generated since boot, unless the log buffer as over will appear on the log_backend_uart device.

**Observed behavior**
All log messages generated before CONFIG_LOG_PROCESS_THREAD_STARTUP_DELAY_MS expires have been discarded.

**Impact**
This causes boot logging messages logged over a USB CDC ACM device to be lost when CONFIG_LOG_PROCESS_THREAD_STARTUP_DELAY_MS is set, rather than preserved, which was the whole point of the delay. 
 There is a delay after boot before a host can connect to CDC ACM, so the log messages are still lost even with no delay.  The boot log messages can be very useful.

**Environment (please complete the following information):**
 - OS: Linux
 - GCC 10.2.0
 - v2.7.99-ncs1-1-0-gb05b8ad63a

**Additional context**
It is critical that another initialized backend, such as shell_log_backend, is turned off before the log process delay expires.  This is what causes the bug.

It's caused when the shell_log_backend is disabled before the logging thread has started and this before log_backend_uart has initialized.  `log_backend_disable()` will set the filter level of the disabled backend to NONE.  Eventually, this calls `set_runtime_filter()`.  That then finds the max level of every *initialized* backend, with `max_filter_get()`, to set as the new aggregate runtime filter level.

If the only backend initialized at this point, due to LOG_PROCESS_THREAD_STARTUP_DELAY_MS, is the shell_log_backend, then the aggregate runtime filter level will be set to NONE.  All log messages generated will now be discarded due to the runtime filter.

When the logging thread starts, log_backend_uart will be initialized and enabled, and then a new aggregate runtime filter level will be calculated that now includes log_backend_uart.  Logging will start working again.  But everything before this point will be discarded.  The whole point of the startup delay was to preserve it.

The problem seems to be that set_runtime_filter()'s recalculation of the aggregate log level doesn't work if not all filters have been initialized.  Indeed, if it was called before any backends were initialized, it would set the aggregate level to NONE and boot log messages would always be discarded.  The way the initial aggregate runtime filter level is found in `z_log_runtime_filters_init()` is different and doesn't result in a result of NONE.

**Comment by kartben** [comment]
Closing with the correct reason as this was improperly marked as "completed".
