### ISSUE TITLE
stm32u5: timer api: lptim: k_msleep is twice long as expected

### ISSUE THREAD

**Issue by erwango** [zephyrproject-rtos/zephyr#53012]
**Describe the bug**

Some timer_api tests are failed on b_u585i_iot02a
```
   zephyr/tests/kernel/tickless/tickless_concept/kernel.tickless.concept, b_u585i_iot02a
   zephyr/tests/kernel/timer/timer_api/kernel.timer.tickless, b_u585i_iot02a
```
Using `samples/boards/stm32/power_mgmt/blinky/src/main.c`, it can also be seen that `k_msleep(2000)` generates 4s sleep.
Though, `k_busy_wait` provides correct duration, so driver configuration and  `sys_clock_cycle_get_32()` implementation seem to be correct.

**To Reproduce**
1. mkdir build; cd build
2. cmake -DBOARD=board\_xyz
3. make

**Expected behavior**
Using LPTIM as kernel ticker should provide correct sleep timeouts

**Environment (please complete the following information):**
zephyr-v3.2.0-2520-g33900ab99e

**Comment by FRASTM** [comment]
![capture](https://user-images.githubusercontent.com/51417392/207391692-befafc14-b2d8-4c76-9ecd-0f087d0abf6f.jpg)
