### ISSUE TITLE

    tests-ci : crypto: rand32: random_ctr_drbg test No Console Output(Timeout)
    

### ISSUE THREAD

**Issue by hakehuang** [zephyrproject-rtos/zephyr#53035]
**Describe the bug**
    random_ctr_drbg test is No Console Output(Timeout) on zephyr-v3.2.0-2490-ga1b4896efe46 on mimxrt1170_evk_cm7

    see logs for details

    **To Reproduce**
    1. 
    ```
    scripts/twister --device-testing --device-serial /dev/ttyACM0 -p mimxrt1170_evk_cm7      --sub-test crypto.rand32
    ```
    2. See error

    **Expected behavior**
    test pass

    **Impact**

    **Logs and console output**
    
    ```
    *** Booting Zephyr OS build zephyr-v3.2.0-2490-ga1b4896efe46 ***
Running TESTSUITE rand32_common
===================================================================
START - test_rand32
E: ***** USAGE FAULT *****
E:   Illegal use of the EPSR
E: r0/a1:  0x00000000  r1/a2:  0xe000ed00  r2/a3:  0xfffffffd
E: r3/a4:  0x80000fb9 r12/ip:  0x40460000 r14/lr:  0x30006821
E:  xpsr:  0x60000000
E: Faulting instruction address (r15/pc): 0x00000000
E: >>> ZEPHYR FATAL ERROR 0: CPU exception on CPU 0
E: Current thread: 0x80000438 (test_rand32)
E: Halting system

        
    ```

    **Environment (please complete the following information):**
     - OS: (e.g. Linux )
     - Toolchain (e.g Zephyr SDK)
     - Commit SHA or Version used: zephyr-v3.2.0-2490-ga1b4896efe46

**Comment by dleach02** [comment]
@hakehuang can you bisect this to find where this was broken?

**Comment by hakehuang** [comment]
@dleach2 is is below commit

`commit b5708e273b5f34a74e26ec60ac05c759ad0717ce
Author: Declan Snyder <declan.snyder@nxp.com>
Date:   Tue Sep 27 09:40:11 2022 -0500

    drivers: entropy: Fix MCUX CAAM Entropy

    Re-enable the CAAM for entropy
    now that the HAL driver has been fixed

    Job descriptors must be accessed coherently
    between CAAM DMA and core.

    The M4 Cores still do not work
    because of mpu/cache/kconfig arch complications,
    disable caam for M4 cores in DTS

    Signed-off-by: Declan Snyder <declan.snyder@nxp.com>

 drivers/entropy/Kconfig.mcux           | 5 ++---
 drivers/entropy/entropy_mcux_caam.c    | 2 +-
 dts/arm/nxp/nxp_rt1160_cm4.dtsi        | 5 +++++
 dts/arm/nxp/nxp_rt1170_cm4.dtsi        | 5 +++++
 tests/drivers/entropy/api/Kconfig.mcux | 9 +++++++++
`
