### ISSUE TITLE
Bluetooth: Failed to set security level for the second connection

### ISSUE THREAD

**Issue by ahmedmoheb-nordic** [zephyrproject-rtos/zephyr#53046]
**Describe the bug**
An HCI error is generated with the following scenario
- Start a scan procedure and connect to the first peripheral
- From the 'connected' callback, set the security level for the current connection and start a new scan procedure
- When the second device is found, start a new connection to the second peripheral
- From the 'connected' callback, set the security level for the current connection

**To Reproduce**
1. Pull this commit ec021bf7ca18b3286e82f033692db5a646cc23e7
2. Run ~/zephyrproject/zephyr/tests/bluetooth/bsim_bt/bsim_test_conn_stress/tests_scripts/conn_stress.sh

**Logs and console output**

![Screenshot from 2022-11-02 09-15-06](https://user-images.githubusercontent.com/109019690/199424595-7f137d84-d90e-433d-be1d-ac600e3d6642.png)

**Comment by jori-nordic** [comment]
doesn't happen any more after rebasing on main. Closing.

**Comment by kruithofa** [comment]
As per comment from @jori-nordic fixed by PR#51300
