### ISSUE TITLE
Bluetooth: legacy advertising doesn't resume if CONFIG_BT_EXT_ADV=y

### ISSUE THREAD

**Issue by jori-nordic** [zephyrproject-rtos/zephyr#53048]
**Describe the bug**
In this configuration: HCI over RPMSG, `CONFIG_BT_EXT_ADV=y`, `CONFIG_BT_MAX_CONN>1`:
- a legacy advertiser is started using `bt_le_adv_start`, _without setting_ `BT_LE_ADV_OPT_ONE_TIME`.
- a device connects
- `bt_le_adv_resume` fails to resume the advertiser

See the original discussion in https://github.com/zephyrproject-rtos/zephyr/pull/51309 .

edit: wasn't really related to nRF53, also reproduced with just a single device with `CONFIG_BT_EXT_ADV=y`.

**To Reproduce**
- flash `samples/bluetooth/peripheral` with the following config: `CONFIG_BT_MAX_CONN=2`, `CONFIG_BT_EXT_ADV=y` to the nRF5340 app core.
- flash `samples/bluetooth/hci_rpmsg` with the following config: `CONFIG_BT_MAX_CONN=2`, `CONFIG_BT_EXT_ADV=y` to the nRF5340 net core.

**Expected behavior**
Advertising resumes after a connection is established.

**Comment by kruithofa** [comment]
@jhedberg can you have a look?

**Comment by jori-nordic** [comment]
@tgagneret-embedded could you double-check if the merged patch fixes your original issue?
