### ISSUE TITLE
Unable to chage initialization priority of logging subsys

### ISSUE THREAD

**Issue by dkalowsk** [zephyrproject-rtos/zephyr#53088]
**Describe the bug**

The current design of subsys/logging has a hard coded POST_KERNEL initialization value of 0.  This forces some drivers to be initialized in earlier PRE_KERNEL stages if the system needs them for logging output.

**Expected behavior**

The subsys/logging to have a mechanism to set the initialization priority at compile time via a Kconfig, similar to other Zephyr devices.

**Impact**

Mostly an annoyance.

**Environment (please complete the following information):**

N/A

**Additional context**

**Comment by dkalowsk** [comment]
Resolved with https://github.com/zephyrproject-rtos/zephyr/pull/52994.  Issue filed to get backport to 2.7 enabled

**Comment by kartben** [comment]
Closing with the correct reason as this was improperly marked as "completed".
