### ISSUE TITLE
Extend Zperf command

### ISSUE THREAD

**Issue by sr1dh48r** [zephyrproject-rtos/zephyr#53094]
Extend zperf shell to take more arguments

QoS setting (-Q/-T/-S) that can accept hex/decimal

**Comment by sr1dh48r** [comment]
@rlubos

**Comment by rlubos** [comment]
@sr1dh48r `-S` option has been added recently to `zperf` upload commands, which allows to specify IP ToS/TC fields:
https://github.com/zephyrproject-rtos/zephyr/blob/main/subsys/net/lib/zperf/zperf_shell.c#L1219

Or is it something else that you're requesting here?

**Comment by sr1dh48r** [comment]
@rlubos Yeah, looks like -S option is enough for our testing. Thanks, closing the issue.
