### ISSUE TITLE
For pinctrl on STM32 pin cannot be defined as push-pull with low level

### ISSUE THREAD

**Issue by r2r0** [zephyrproject-rtos/zephyr#53141]
**Describe the bug**
Following pinctrl pin definition for STM32WB55 does not set pin as push-pull (and sets pin as digital input):
```
/omit-if-no-ref/ pph_rst_init: gpio_pb0 {
        pinmux = <STM32_PINMUX('B', 0, GPIO)>;
        drive-push-pull;
        output-low;
    };
```

In the `pinctrl_configure_pins` function in pinctrl_stm32.c there is following code:
```C
		} else if (STM32_DT_PINMUX_FUNC(mux) == STM32_GPIO) {
			uint32_t gpio_out = pins[i].pincfg &
						(STM32_ODR_MASK << STM32_ODR_SHIFT);
			if (gpio_out != 0) {
				pin_cgf = pins[i].pincfg | STM32_MODER_OUTPUT_MODE;
			} else {
				pin_cgf = pins[i].pincfg | STM32_MODER_INPUT_MODE;
			}
		} else {
```
The bit under `STM32_ODR_MASK << STM32_ODR_SHIFT` is based on DT pin definition and it encodes if output pin should have low or high level.
This means that if there is defined low level (encoded as 0) then `if (gpio_out != 0)` will cause configuration of pin as input.

**To Reproduce**
Build application with pinctrl pin definition like above and observerve pin behaviour.

**Expected behavior**
For the GPIO pin the pin direction should be deduced basing on `drive-push-pull` or `drive-open-drain` atributes.

**Impact**
showstopper

**Logs and console output**

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain Zephyr SDK 0.15.2
 - ca6d02147d352a25cb935770c6c87978a1fe49b5

**Additional context**

**Comment by erwango** [comment]
@r2r0, please check https://github.com/zephyrproject-rtos/zephyr/pull/53211

**Comment by LuxLuthor** [comment]
@r2r0, @erwango 
alternative solution in #53217
