### ISSUE TITLE
Bluetooth: Controller: BT_HCI_OP_LE_BIG_TERMINATE_SYNC on syncing BIG sync returns invalid BIG handle

### ISSUE THREAD

**Issue by Thalley** [zephyrproject-rtos/zephyr#53148]
**Describe the bug**
Calling `hci_le_big_sync_term` on a BIG that is currently syncing (i.e. a `BT_HCI_EVT_LE_BIG_SYNC_ESTABLISHED` event has not yet been generated) results in a `BT_HCI_EVT_LE_BIG_SYNC_ESTABLISHED` event with a wrong handle (always seems to be `0xff`)

**To Reproduce**
1. Modify `tests/bluetooth/bsim_bt/bsim_test_audio/src/broadcast_sink_test.c` to do `bt_audio_broadcast_sink_stop` right after the call to `bt_audio_broadcast_sink_sync` in e.g. `test_main` to initiate the BIG Sync terminate while it is still syncing
2. Run the `tests/bluetooth/bsim_bt/bsim_test_audio/test_scripts/broadcast_audio.sh` test
3. See the `<wrn> bt_iso: hci_le_big_sync_established: Invalid BIG handle` warning in the log (potentially expand the log statement to also log the BIG handle to see the handle `255`)

**Expected behavior**
Expected behavior is that the `BT_HCI_EVT_LE_BIG_SYNC_ESTABLISHED` will come with the correct handle and with `status == 0x44` as defined by the core spec: 

> If the Host attempts to terminate synchronization with a BIG while the process of synchronization with that BIG is in progress (i.e. HCI_LE_BIG_Sync_Established event has not been generated) the process of synchronization shall stop, and the Controller shall generate the HCI_LE_BIG_Sync_Established event to the Host with the error code Operation Cancelled by Host (0x44).

**Impact**
Significant as it stops Zephyr from terminating a syncing BIG, and affects both the ISO and LE Audio implementation. 

**Logs and console output**N/A

**Environment (please complete the following information):**
 - Commit SHA or Version used: b8f8c3c10eda6d1529d0e616b24ba9719efab2c8

**Additional context**
N/A

**Comment by carlescufi** [comment]
Downgrading to Low since LE Audio is experimental in the Controller and has not gone through qualification yet.
