### ISSUE TITLE
SHTCx driver wrong negative temperature values

### ISSUE THREAD

**Issue by stanvn** [zephyrproject-rtos/zephyr#53172]
**Describe the bug**
There is a error in calculating negative temperature values in the SHTCx driver. The line below causes the problem. The fraction part of the temperature is calculated using `15625U`, however this converts `val->val2`  to a unsigned integer while it should be a signed integer containing a negative value.  
https://github.com/zephyrproject-rtos/zephyr/blob/9cf89603dfffd320d9b3d127e5cccc1d8c40b24e/drivers/sensor/shtcx/shtcx.c#L56 
Simply removing the `U` will fix this.

**To Reproduce**
I've placed the sensor in the freezer to reproduce the bug. 

**Expected behavior**
Expect `val->val2` to be a negative value once the temperature drops below 0.

**Impact**
Wrong readout values for temperatures below 0. 

**Logs and console output**
![Screenshot from 2022-12-18 13-58-31](https://user-images.githubusercontent.com/8735520/208318711-19692b38-4973-457d-b690-bbef1a40efea.png)

**Environment (please complete the following information):**
 - Linux Ubunut (22.04)
 - Zephyr 3.2.0 (main branch)

**Comment by henrikbrixandersen** [comment]
@stanvn Good catch. Are you able to submit a PR for fixing this?

**Comment by stanvn** [comment]
I'll try to find some time for this, but I cannot guarantee anything.
