### ISSUE TITLE
Select pin properties from shield overlay

### ISSUE THREAD

**Issue by pideu-sj** [zephyrproject-rtos/zephyr#53175]
### Discussed in https://github.com/zephyrproject-rtos/zephyr/discussions/52974

<div type='discussions-op-text'>

<sup>Originally posted by **pideu-sj** December 12, 2022</sup>
Hi everyone,
I have a question regarding the selection of pin properties like ``bias-pull-up``, when using a shield. Is there a possibility, to add a pinctrl configuration to a shield overlay, that tells e.g. the ``i2c0_default`` node, that he should use a pull up resistor? The only option, came to my mind is to adding a pinctrl alternative like this in the shield overlay:

````
&arduino_i2c {
	status = "okay";
	pinctrl-0 = <&i2c0_default_alt>;
	pinctrl-1 = <&i2c0_sleep_alt>;
	pinctrl-names = "default", "sleep";
	amg88xx_amg88xx_grid_eye_eval_shield: amg88xx@68 {
		compatible = "panasonic,amg88xx";
		reg = <0x68>;
		/* Pin D2 from Arduino Connector */
		int-gpios = <&arduino_header 8 (GPIO_ACTIVE_LOW | GPIO_PULL_UP)>;
		status = "okay";
	};
};

&pinctrl {
	i2c0_default_alt: i2c0_default_alt {
		group1 {
			psels = <NRF_PSEL(TWIM_SDA, 0, 26)>,
				<NRF_PSEL(TWIM_SCL, 0, 27)>;
			bias-pull-up;
		};
	};

	i2c0_sleep_alt: i2c0_sleep_alt {
		group1 {
			psels = <NRF_PSEL(TWIM_SDA, 0, 26)>,
				<NRF_PSEL(TWIM_SCL, 0, 27)>;
			low-power-enable;
		};
	};
};
````
But the problem is, that psels is required inside group1. So I would overwrite the pin numbers for SDA and SCL in previous example code. 

When looking from the perspective of the shield, it does not know, which board is used, so I can not simply overwrite with some pin number, that won't fit for every board underneath the shield. So I have somehow reference to the psels pin number of the board? Is this somehow possible, or are there any other ways, to enable a pull-up from a shield overlay?</div>

**Comment by gmarull** [comment]
You can achieve that using a board specific overlay. Since SDA/SCL are usually part of the same group, you can just do:

```dts
/* myboard.overlay */
&i2c0_default {
   group1 {
      bias-pull-up;
   };
};
```

Note: internal pull-ups for I2C are, in general, a bad idea since its optimal value depends on bus speed.
