### ISSUE TITLE
esp32: AMP(Asymmetric Multi-Processing) Support 

### ISSUE THREAD

**Issue by 5ami** [zephyrproject-rtos/zephyr#53212]
**Is your feature request related to a problem? Please describe.**
Yes. It could be a problem depending on the application, as there is no official support for BareMetal programming from esp32. 
**Describe the solution you'd like**
For now, We would like to Have AMP  (i.e., running FreeRTOS on one core and a bare metal/other OS on the other).

**Describe alternatives you've considered**
I considered this online article, https://hackaday.io/project/174521-bare-metal-second-core-on-esp32, but the implementation is highly experimental and not reliable especially in esp32s3.  
**Additional context**
![image](https://user-images.githubusercontent.com/43592883/208631054-cdc4fcef-0f5d-43df-910d-9015bf651e8d.png)

**Comment by rftafas** [comment]
Hi!

To note, I was not aware of this project. Thanks for sharing.

PTAL: 

- [Espressif devcon22 about the topic](https://www.youtube.com/watch?v=oble9ObAqxM).
- AMP on Zephyr, [check this link](https://github.com/zephyrproject-rtos/zephyr/pull/44645).
- MCUboot [Multimage on ESP32 devices](https://github.com/mcu-tools/mcuboot/pull/1326) (make sure to check the links within).

Current situation:

- There are 2 ways to put AMP to work: MCUboot+Multiboot starting both apps _or_ Zephyr starting the second app. 
- In any case, it requires a deep understanding of Zephyr to be usable at this stage (i.e. tinkering with linkers and list goes on).
- There is a [WIP](https://github.com/zephyrproject-rtos/zephyr/issues/51728) for better compliance to Zephyr practices.

MCUboot questions and FreeRTOS should be on proper forums, but for the sake of a good answer:

- AFAIK, FreeRTOS is compatible with MCUboot, but only [a preliminary port from Amazon](https://freertos.org/mcuboot/mcuboot-demo.html). So it is feasible to tinker FreeRTOS and have it on AMP scenario by using MCUboot and FreeRTOS. Better to ask on ESP32 forums for more info.
- ESP32 bare metal is already possible, but we do not encourage using HAL layers directly, it is not public and may change without notice. Users should stick to RTOS APIs.

ALL THAT SAID...

I do hope what we have been doing meets your request. Not sure about bare metal, the more likely scenarios to be supported are:

- Zephyr - Zephyr
- Zephyr - Bare Metal Rust (which requires a deep understanding of Rust, linkers and etc)

We need to advance on the implementation to get a better 'applications' understanding. Of course, everything is out in the open, so any capable developer may already knit, glue and tinker with all this info to get to their intended results. Probably with a lot of learning along the way.

**Comment by 5ami** [comment]
Hi, thank you for the response !
**ESP32 bare metal is already possible, but we do not encourage using HAL layers directly, it is not public and may change without notice. Users should stick to RTOS APIs. ** 

Is there a way to use Zepher MCUboot with esp-idf, to start second core without any RTOS ?

We can use the HAL layers or make our own HAL layers, The issue is that by using esp-idf, there no supported method to start the second CPU without starting freeRTOS. The second stage bootloader sequence, always starts the scheduler just after starting the CPU. and getting rid of freeRTOS running on second core is not straight forward.

**Comment by rftafas** [comment]
Hi!

By 'there is a way' I'll assume you mean "feasibility". It is possible. You would have to glue all the info I provided and get hands on to make it work. It is a lot of work, though.

I hope this helps your decision.

Zephyr wise, I consider this request was already attended, even with current WIP.
