### ISSUE TITLE
Bluetooth: Controller: Cannot recreate CIG

### ISSUE THREAD

**Issue by Thalley** [zephyrproject-rtos/zephyr#53301]
**Describe the bug**
It is not possible to recreate the CIG if no CIS has been connected, significantly limiting the usage of unicast ISO. 

**To Reproduce**
1. Add `CONFIG_BT_CTLR_CENTRAL_ISO=y` to `tests/bluetooth/bsim_bt/bsim_test_audio/prj.conf`
2. Apply https://github.com/zephyrproject-rtos/zephyr/pull/53291
3. Build and run the `tests/bluetooth/bsim_bt/bsim_test_audio/test_scripts/unicast_audio.sh`
4. See the following error on the second iteration (the tests runs in multiple iterations):
```
d_00: @00:00:04.330994  ASSERTION FAIL [!cig] @ WEST_TOPDIR/zephyr/subsys/bluetooth/controller/ll_sw/ull_central_iso.c:235
d_00: @00:00:04.330994  @ WEST_TOPDIR/zephyr/subsys/bluetooth/controller/ll_sw/ull_central_iso.c:235
d_00: @00:00:04.330994  [00:00:04.330,993] <err> os: z_fatal_error: >>> ZEPHYR FATAL ERROR 3: Kernel oops on CPU 0
d_00: @00:00:04.330994  [00:00:04.330,993] <err> os: z_fatal_error: Current thread: 0x81c38a0 (BT TX)
d_00: @00:00:04.330994  [00:00:04.330,993] <err> os: k_sys_fatal_error_handler: Halting system
```

**Expected behavior**
Expect to be able to create and delete (remove) a CIG using the same CIG ID multiple times. 

**Impact**
Since the ISO implementation reuses the CIG IDs, this is a major issue for ISO central. 

**Logs and console output**
See above

**Environment (please complete the following information):**
 - Commit SHA or Version used: 02b83892d2da063e665b114438b21a4f3b2443a2

**Additional context**
N/A

**Comment by wopu-ot** [comment]
@mtpr-ot does this ring any bells?

**Comment by mtpr-ot** [comment]
> @mtpr-ot does this ring any bells?

No, I would expect that to work.

**Comment by mtpr-ot** [comment]
> > @mtpr-ot does this ring any bells?
> 
> No, I would expect that to work.

On second thought, I think there was an issue there, which Vinayak pointed out. Will take a look.

**Comment by cvinayak** [comment]
@Thalley is this still an issue upstream in v3.3.0-rc1 ? if not, can we close this as fixed?

**Comment by Thalley** [comment]
> @Thalley is this still an issue upstream in v3.3.0-rc1 ? if not, can we close this as fixed?

No, this was fixed by https://github.com/zephyrproject-rtos/zephyr/pull/53450 - Closing

**Comment by mtpr-ot** [comment]
> > @Thalley is this still an issue upstream in v3.3.0-rc1 ? if not, can we close this as fixed?
> 
> No, this was fixed by #53450 - Closing

Hang on - my fix was removed by @cvinayak's copmmit, so the question is valid. Please check.

**Comment by mtpr-ot** [comment]
Reopened until verified on RC.

**Comment by Thalley** [comment]
> Reopened until verified on RC.

I can confirm that the CI BSIM tests for unicast works on the current `main`
