### ISSUE TITLE
Take Advantage Of "Hardware Accelerated" Components?

### ISSUE THREAD

**Issue by vindicatorr** [zephyrproject-rtos/zephyr#53316]
**Is this request related to a missing driver support for a particular hardware platform, SoC or board? Please describe.**
Describe in details the hardware support being requested and why this support benefits Zephyr.
There are hardware features that appear not to be taken advantage of.
The one thing that brought it to light for me was the CRC/Checksum capability of the STM32.

**Describe why you are asking for this support?**
It'd be nice to take full advantage of a SOC's abilities.

**Additional context**
EG. `HAL CRC Generic Driver` [Drivers_en.DM00105879.pdf](https://www.st.com/resource/en/user_manual/um1725-description-of-stm32f4-hal-and-lowlayer-drivers-stmicroelectronics.pdf): pg.141

I recognize the complexity of what boards/soc/arch supports what, but that's already been dealt with by the function/purpose of this project.

Reference to a project that appears to have done just that (at least for STM32 CRC): https://github.com/nanoframework/metadata-processor/blob/acacc000e3cff87d902ed347c9c9e7e55e5ade3d/native/nf-interpreter/targets/CMSIS-OS/ChibiOS/nf-overlay/os/hal/ports/STM32/LLD/CRCv1/crc_lld.h

**Comment by kartben** [comment]
Closing with the correct reason as this was unproperly marked as "completed".
