### ISSUE TITLE
usb: device: usb_dfu: k_mutex is being called from isr

### ISSUE THREAD

**Issue by RobertGalatNordic** [zephyrproject-rtos/zephyr#53326]
**Describe the bug**
I have a sample where I use usb dfu for update, When I started the upload process I immediatelly got an error that k_mutex has been called from ISR

I opened the debug session and reproduced the issue and gathered following call trace:
![MicrosoftTeams-image](https://user-images.githubusercontent.com/77001564/209350924-f95cb052-cd6c-4d19-835c-a2f20f246579.png)

As it can be seen, the rtc_nrf_isr which I assume is an interrupt handler, has been called, which in trun triggered the sys_clock_timeout_handler, and that triggered the dfu_timer_expired. This function eventually calls the mutex, but we are still in IRS context.

I tried to reproduce the issue on the zephyr sample, but it seems like the issue does not reproduces there.
I also attached the .config file for further investigation:
https://gist.github.com/RobertGalatNordic/6c50c2529dcf310acf0d33606a03253e

I Observed the issue on the private project that uses the zephyr from the nrf, but it seems that the issue is in mainstream
As I mentioned I tried to reproduce the issue with the zephyr usb dfu sample, but this sample works fine, so maybe there is something in configuration of my project that triggers this issue.
Never the less, when I analyzed the stack trace it seems like a bug.

**Expected behavior**
There should be no path in the code where mutex is called from ISR. The stack trace showed above proves that at liest one of such path exists, and it is clearly a bug that should not exist.

**Impact**
It is a blocker for the project

**Environment (please complete the following information):**
 - OS:  Linux
 - Toolchain: zephyr 0.15.1
 - Commit SHA or Version used: v3.2.99-ncs1 (https://github.com/nrfconnect/sdk-zephyr)

**Comment by anangl** [comment]
This is a problem in the usb_dfu class. Commit https://github.com/zephyrproject-rtos/zephyr/commit/c27d48c89ae67397139ee5b1a245505ed10b071f introduced calls to `usb_dc_detach()` performed from `dfu_timer_expired()` which is a timer handler.
