### ISSUE TITLE
subsys: logging: use of timestamping during early boot may crash MMU-based systems

### ISSUE THREAD

**Issue by ibirnbaum** [zephyrproject-rtos/zephyr#53343]
During the work on #51035, it has turned out that the combination of:

- a MMU-based system, in this case an ARMv7 Cortex-A CPU (e.g. arm/qemu_cortex_a9),
- a system timer driver mapping its register space via the MMU using the DEVICE_MMIO API - if the system timer is the first device to be initialized,
- alternatively, the driver of the first device of any kind to be initialized using the DEVICE_MMIO API,
- CONFIG_KERNEL_LOG_LEVEL being set to 'debug' and
- memory address 0 having no read permission

causes a data abort exception whenever the first device driver using the DEVICE_MMIO API and therefore the MMU attempts to map the respective device's register space. This is due to a LOG_DBG call in kernel/mmu.c, z_phys_map(), line 748. Similar LOG_DBG calls exist in the kernel's MMU code for anonymous page mapping and memory unmapping.

Within said LOG_DBG call, if the log level is configured accordingly, the logging subsystem will attempt to acquire a timestamp from the system timer driver. At this point, there's a problem if the system timer driver maps its own register space using the DEVICE_MMIO API:

- Either the attempt of the system timer driver to map its own register space will lead us to z_phys_map() and therefore the LOG_DBG call contained therein if the system timer driver is the first driver to be inititialized,
- or we're not even at the point yet where an attempt is made to get the timer's register space mapped as some other device is first in the list of devices to be initialized, if this is the case, it's likely the UART which is initialized before the timer.

Either way, the logging subsystem will now attempt to acquire a timestamp prior to the system timer's register space being added to the MMU page table. This has worked so far on ARMv7 Cortex-A, although the result was garbage: device driver instances whose register space has not yet been mapped will use the base address 0 for any premature driver API calls - such as the system timer driver's timestamp get-function. Before the development of #51035, the first 4k page of memory had RX permissions as the exception vector table was located at address 0. Therefore, a read call for the 64 bit current timer value prior to the timer driver being fully initialized used to return the first two jump instructions from the exception vector table, interpreted as a timestamp.

If the 4k memory page at address 0 is not accessible, as is the intention of #51035, the system will crash instead.

**To Reproduce**
Build a simple demo for qemu_cortex_a9 using the forked repo and branch referred to in #51035 with CONFIG_KERNEL_LOG_LEVEL set to 'debug'. However, do *not* apply the PR's deletion of the LOG_DBG statement from the kernel's MMU code (the only change to kernel/mmu.c), as this is a workaround affecting multiple arches that should not be generalized

**Environment**
#51035 is based on Zephyr version 3.2.99. 

**Expected behavior**
System booting successfully. The logging subsystem should consider that due to the kernel's MMU code, it is possible to trigger logging calls prior to the underlying hardware required for timestamping being available. Maybe timer access should generally be omitted in PRE_KERNEL_1, as it's not even assured by default that the system timer is the first device to be initialized.

**Impact**
Currently prevents the move of the exception vector table away from address 0 with a corresponding fixed MMU page table entry to leaving the vector table at its original location within the Zephyr binary image, pointed to by the VBAR register, if the Kernel's log level is set to 'debug'.

**Comment by kartben** [comment]
Closing with the correct reason as this was unproperly marked as "completed". @ibirnbaum please feel free to re-open.
