### ISSUE TITLE
CAN-FD / MCAN driver: Possible variable overflow for some MCUs

### ISSUE THREAD

**Issue by martinjaeger** [zephyrproject-rtos/zephyr#53417]
**Describe the bug**

The CAN-FD driver stores different flags for the filters as a bitset in the following variables:

https://github.com/zephyrproject-rtos/zephyr/blob/e4fcb32451c587a3e4ba7f8bf3fc602b16f9652b/drivers/can/can_mcan.h#L181-L184

These variables should have as many bits as the maximum number of filters of this type.

For the NXP LPC55Sxx the `uint8_t` is not sufficient for the number of extended filters:

https://github.com/zephyrproject-rtos/zephyr/blob/e4fcb32451c587a3e4ba7f8bf3fc602b16f9652b/dts/arm/nxp/nxp_lpc55S1x_common.dtsi#L216

The variable size should be increased to `uint16_t`.

**Impact**

Other flags would be overwritten if an application actually uses more than 8 extended ID filters.

The overflow has no impact on device security, as far as I can see. However, it could lead to unexpected behavior of the CAN driver.

**Comment by henrikbrixandersen** [comment]
This is still an issue. The Bosch M_CAN IP core allows up to 128 standard (11-bit) filter elements and up to 64 extended (29-bit) filter elements.

I am preparing a PR for fixing this for any Bosch M_CAN IP core instance.
