### ISSUE TITLE
cmake: libapp.a in unexpected location

### ISSUE THREAD

**Issue by andrewboie** [zephyrproject-rtos/zephyr#5343]
I notice that libapp.a is directly in the build directory instead of being under zephyr/ with the rest of the build artifacts.
Is this intentional?

```
apboie@wintermute:/projects/zephyr2/samples/philosophers/out master /projects/zephyr2
$ ls -l
total 256
-rw-rw-r--.  1 apboie apboie  19938 Dec 11 13:29 CMakeCache.txt
drwxrwxr-x. 12 apboie apboie   4096 Dec 11 13:29 CMakeFiles
-rw-rw-r--.  1 apboie apboie   1566 Dec 11 13:29 cmake_install.cmake
-rw-rw-r--.  1 apboie apboie 184762 Dec 11 13:29 libapp.a
-rw-rw-r--.  1 apboie apboie  37935 Dec 11 13:29 Makefile
drwxrwxr-x. 15 apboie apboie   4096 Dec 11 13:29 zephyr
```

**Comment by SebastianBoe** [comment]
This was unintentional, it would have been cleaner to have it somewhere in <build>/zephyr/**

**Comment by SebastianBoe** [comment]
Oops, I referenced this issue by mistake in #1c2de10.

**Comment by SebastianBoe** [comment]
This patch resolves the issue: https://github.com/SebastianBoe/zephyr/commit/d3fa360f4d6970c129c7476bdc1060e8eb60788f

But I am hesitant to apply it as it is not obvious to me whether the improved organization outweighs the possibility of breaking backwards compatibility with external systems.

**Comment by galak** [comment]
@SebastianBoe I think we should go ahead with this change.  Can you please submit a PR for this.

**Comment by SebastianBoe** [comment]
>  Can you please submit a PR for this.
-- @galak 

Done.
