### ISSUE TITLE
USB: Suspending CDC ACM can lead to endpoint/transfer state mismatch

### ISSUE THREAD

**Issue by desowin** [zephyrproject-rtos/zephyr#53451]
**Describe the bug**
There is a race condition during USB bus suspend, observable at least in `nrf52840dk_nrf52840`, where CDC ACM interface is no longer able to send any data to host. After the race is lost, USB device controller driver considers endpoint to be busy, but the USB stack thinks the endpoint is available.

**To Reproduce**
1. Significantly increase race chance by modifying console sample to output data without extra delay.
```diff
--- a/samples/subsys/usb/console/src/main.c
+++ b/samples/subsys/usb/console/src/main.c
@@ -99,6 +99,5 @@ void main(void)
 
        while (1) {
                printk("Hello World! %s\n", CONFIG_ARCH);
-               k_sleep(K_SECONDS(1));
        }
 }
```
2. `west build --pristine -b nrf52840dk_nrf52840 -d build-usb-console zephyr/samples/subsys/usb/console -- -DCONFIG_USB_DEVICE_REMOTE_WAKEUP=n`
3. `cd build-usb-console; west flash`
4. Open ttyACM port in some terminal application (e.g. gtkterm), observe steady data flow
5. Close ttyACM port
6. Wait for host to suspend USB device due to inactivity
7. Open ttyACM port, observe that data is no longer received

**Expected behavior**
CDC ACM should survive bus suspend regardless of what application does, especially if it is simply an endless `printk` loop.

**Impact**
This is seriously annoying issue, it can even be considered a showstopper if it happens in the wild.

**Logs and console output**
USB bus logs are too big to attach here, but the device keeps sending NAK as response to IN tokens.

**Environment (please complete the following information):**
 - OS: Linux 6.0.12
 - Toolchain: Zephyr SDK 0.15.2
 - Zephyr 8c8d41c32fb5d7a6a965c4cbdfa955d95905cf4a

**Additional context**
After losing the race, connect with debugger to observe that CDC ACM is trying to send the data, i.e. `tx_work_handler` is calling `usb_transfer`. The endpoint is not getting armed because `usb_write` called in `usb_transfer_work` fails with `-EAGAIN` because `ep_ctx->write_in_progress` is true in `usb_dc_ep_write`.

The discrepancy is because https://github.com/zephyrproject-rtos/zephyr/blob/abe50cc92991389e2508de8ea721bee36cd5fb17/subsys/usb/device/usb_device.c#L1249-L1257 cancels the transfer on `USB_DC_SUSPEND` while leaving endpoint armed. I believe the transfer should not be canceled on suspend which matches review comments that were left without any reply back in 2019: https://github.com/zephyrproject-rtos/zephyr/issues/17488#issuecomment-516800469 and https://github.com/zephyrproject-rtos/zephyr/pull/17492#discussion_r309145878 Unfortunately the transfers were cancelled since 1370f162877bd738ab725f5ef2096100b0720e2a and the cancelling was not altered by subsequent changes, e.g. 8e9bf88d66a91f63e8e345cf2accb541bc434134.

**Comment by stephanosio** [comment]
FYI @jfischer-no
