### ISSUE TITLE
Sysbuild cmake enters infinite loop if 2 images are added to a build with the same name

### ISSUE THREAD

**Issue by nordicjm** [zephyrproject-rtos/zephyr#53474]
**Describe the bug**
Essentially cmake will lock up in an infinite loop if 2 images are added that have the same name to the "IMAGES" variable, e.g. "mcuboot" and "mcuboot". Doing this is a mistake, but sysbuild should detect this and error out instead of chewing up the host's CPU.

**Expected behavior**
Error to be output

**Impact**
Annoyance

**Environment (please complete the following information):**
 - Commit SHA or Version used: 58c924ec569afceaa96d8e771a91c797b978c81b

**Comment by tejlmand** [comment]
> Essentially cmake will lock up in an infinite loop if 2 images are added that have the same name to the "IMAGES" variable

Are you sure ?
And where does it start to loop ?

I'm asking because we use ExternalProject and ExternalProject itself should ensure not two images with identical names are added, for example if you use ExternalProject to add `foo` twice you'll get this error:
```
ExternalProject.cmake:3985 (add_custom_target):
  add_custom_target cannot create target "foo" because another target with
  the same name already exists.  The existing target is a custom target
  created in source directory "/projects/github/ncs/zephyr/dub_target".  See
  documentation for policy CMP0002 for more details.
```

**Comment by tejlmand** [comment]
yes, I noticed after my comment that if the list is manipulated so that same name appears twice, then `images_sysbuild_processed ` is not updated cause each image can only be added there once, ref:
https://github.com/zephyrproject-rtos/zephyr/blob/3e98f20d66b8558e23fc63447259da0f66d12d59/share/sysbuild/CMakeLists.txt#L76
