### ISSUE TITLE
Missing UUID for PBA and TMAS

### ISSUE THREAD

**Issue by alexsven** [zephyrproject-rtos/zephyr#53488]
**Is your enhancement proposal related to a problem? Please describe.**
The `uuid.h` is missing the UUID for Public Broadcast Announcement (0x1856) and Telephony and Media Audio Service (0x1855)

These can be found in https://btprodspecificationrefs.blob.core.windows.net/assigned-numbers/Assigned%20Number%20Types/Assigned%20Numbers.pdf 

**Describe the solution you'd like**
Add the missing UUIDs to `uuid.h`. 

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by balajikulkarni** [comment]
Interested in taking up this enhancement, will send out a PR soon.

**Comment by markCwatson** [comment]
@alexsven @Thalley I'll add this now and open a PR. Can assign to me. Thx

**Comment by markCwatson** [comment]
See https://github.com/zephyrproject-rtos/zephyr/pull/53578
