### ISSUE TITLE
zephyr kernel Kconfig USE_STDC_LSM6DS3TR and hal_st CMakeLists.txt lsm6ds3tr-c variable name mismatched (hyphen sign special case)

### ISSUE THREAD

**Issue by JiapengLi** [zephyrproject-rtos/zephyr#53546]
**Describe the bug**

zephyr kernel Kconfig `USE_STDC_LSM6DS3TR` and hal_st CMakeLists.txt `lsm6ds3tr-c` variable name are mismatched, this is becuase there is hyphen sign in `lsm6ds3tr-c`, and Kconfig need take care of it. Current implementation in zephyr code is to remove '-c'. And we need to the same in hal_st to support it.

Zephyr Knernel implementation:
https://github.com/zephyrproject-rtos/zephyr/blob/main/modules/Kconfig.st#L145
```
config USE_STDC_LSM6DS3TR
	bool
```
hal_st implementation:
https://github.com/zephyrproject-rtos/hal_st/blob/master/sensor/stmemsc/CMakeLists.txt#L61
```cmake
set(stmems_pids
...
  lsm6ds3tr-c
...
  )
foreach(stmems_pid ${stmems_pids})
  string(TOUPPER ${stmems_pid} pid_to_upper)
  if(CONFIG_USE_STDC_${pid_to_upper})
    zephyr_include_directories(
        ${stmems_pid}_STdC/driver/
        )
    zephyr_library_sources(
        ${stmems_pid}_STdC/driver/${stmems_pid}_reg.c
        )
  endif()
endforeach()
```

**To Reproduce**

This leads to lsm6ds3tr-c register lib unusable, `select USE_STDC_LSM6DS3TR` is not able to load lsm6ds3tr-c
```
	select USE_STDC_LSM6DS3TR
```
**To Fix**
A propsal fix of hal_st: (singal patch)
```patch
diff --git a/sensor/stmemsc/CMakeLists.txt b/sensor/stmemsc/CMakeLists.txt
index 215cab6..e55560c 100644
--- a/sensor/stmemsc/CMakeLists.txt
+++ b/sensor/stmemsc/CMakeLists.txt
@@ -74,7 +74,8 @@ set(stmems_pids
 
 foreach(stmems_pid ${stmems_pids})
   string(TOUPPER ${stmems_pid} pid_to_upper)
-  if(CONFIG_USE_STDC_${pid_to_upper})
+  string(REPLACE "-C" "" pid_to_upper_ ${pid_to_upper} )
+  if(CONFIG_USE_STDC_${pid_to_upper_})
     zephyr_include_directories(
         ${stmems_pid}_STdC/driver/
         )
```
A more neatly fix is to patch both zephyr and hal_st, convert hyphen (`-`) to undersocre (`_`)

zephyr:
USE_STDC_LSM6DS3TR -> USE_STDC_LSM6DS3TR_C

hal_st
```
diff --git a/sensor/stmemsc/CMakeLists.txt b/sensor/stmemsc/CMakeLists.txt
index 215cab6..e8f7389 100644
--- a/sensor/stmemsc/CMakeLists.txt
+++ b/sensor/stmemsc/CMakeLists.txt
@@ -74,7 +74,8 @@ set(stmems_pids
 
 foreach(stmems_pid ${stmems_pids})
   string(TOUPPER ${stmems_pid} pid_to_upper)
-  if(CONFIG_USE_STDC_${pid_to_upper})
+  string(REPLACE "-" "_" pid_to_upper_ ${pid_to_upper} )
+  if(CONFIG_USE_STDC_${pid_to_upper_})
     zephyr_include_directories(
         ${stmems_pid}_STdC/driver/
         )
```
sensor dirver:
```
	select USE_STDC_LSM6DS3TR_C
```

**Expected behavior**
N/A

**Impact**
N/A

**Logs and console output**
N/A

**Environment (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by kartben** [comment]
Closing with the correct reason as this was unproperly marked as "completed".
@JiapengLi would you be maybe willing to work on a PR to fix this?
