### ISSUE TITLE
qemu_x86/qemu_x86_nommu hangs on big executable files

### ISSUE THREAD

**Issue by pfalcon** [zephyrproject-rtos/zephyr#5355]
When executing "make run" with BOARD=qemu_x86/qemu_x86_nommu on the following file:

~~~
   text	   data	    bss	    dec	    hex	filename
 198386	 779936	  41768	1020090	  f90ba	zephyr.elf
~~~

QEMU justs hangs, not providing any ouput.

**Comment by pfalcon** [comment]
That particular file contains a testsuite (tests to run, reference output to match against).

**Comment by andrewboie** [comment]
What steps have you taken to debug this?
How do you know this is a function of file size, or related to the MMU?

**Comment by andrewboie** [comment]
This bug report is severely insufficient.
Please do more diligence and gather proper data for a developer to reproduce the problem with their own builds. Sending just an ELF file isn't acceptable.

**Comment by pfalcon** [comment]
Please have patience with community bugreports. Thank you.
