### ISSUE TITLE
Kconfig search has white on white text

### ISSUE THREAD

**Issue by decsny** [zephyrproject-rtos/zephyr#53568]
**Describe the bug**
The Kconfig search on the documentation site has white text on the white background of the search bar, so you can only see entered text by highlighting as seen in the screenshot below:
![image](https://user-images.githubusercontent.com/110566814/211084089-2247849f-7b4f-4cc7-ad0f-c197ec9e9aa2.png)

**Expected behavior**
Perhaps the text is meant to be white, but the background of the search bar should be black? I don't know, but I just expected the text to be readable

**Impact**
Annoyance 

**Environment (please complete the following information):**
Other people have the same issue as me, and the common factors seem to be 1) Firefox 2) Windows 10 3) Windows has the dark color theme. Switching the windows color theme to light results in black on white text in the Kconfig search bar, as would be expected

**Comment by beriberikix** [comment]
Was just going to report this. I'm on Windows 11 and latest Chrome (108.0.5359.125 (Official Build) (64-bit))

**Comment by decsny** [comment]
I have also confirmed the issue exists on linux mint on firefox as well
