### ISSUE TITLE
CII Badge: Use of deprecated functions/APIs

### ISSUE THREAD

**Issue by agross-linaro** [zephyrproject-rtos/zephyr#5360]
The project SHOULD avoid using deprecated or obsolete functions and APIs where FLOSS alternatives are available in the set of technology it uses (its "technology stack") and to a supermajority of the users the project supports (so that users have ready access to the alternative).

This is a little generic of a requirement.  We'd need to do a scan to check for deprecated/obsolete functions that have FLOSS alternatives.

**Comment by nashif** [comment]
I am not aware of any APIs that we used that can be seen as deprecated, would mark this as Met and if something deprecated is discovered, mark it as a bug.

**Comment by agross-linaro** [comment]
Agreed.

**Comment by agross-linaro** [comment]
The project is self-contained and does use minimal external APIS, mostly from libc. We verify usage of those APIs on constant basis and remove any obsolete usage when found or reported.
