### ISSUE TITLE
unicast_audio_client and unicast_audio_server example assert

### ISSUE THREAD

**Issue by JiaLWang** [zephyrproject-rtos/zephyr#53617]
**Describe the bug**
When using CIS example of LE audio will cause a crash. What is the reason for the above crash?

**To Reproduce**
1. Need two nrf52840 board
2. one board flash unicast_audio_client example and another flash unicast_audio_server example.
3. will cause crash

error log as below:

![image](https://user-images.githubusercontent.com/89066760/211310898-dc3ef8da-7a3b-4595-99d1-cab4a859cc79.png)

**Environment (please complete the following information):**
 - OS: Linux
 - Commit : 58c924ec569afceaa96d8e771a91c797b978c81b

**Comment by JiaLWang** [comment]
Hi @cvinayak , Anything update?

**Comment by cvinayak** [comment]
Zephyr Controller does not yet support Connected ISO feature.

**Comment by JiaLWang** [comment]
OK, Thanks for you help.
