### ISSUE TITLE
k_malloc and settings

### ISSUE THREAD

**Issue by mkettn** [zephyrproject-rtos/zephyr#53610]
**Describe the bug**
Using k_malloc to allocate memory for recovered settings strings on the fly in the set/get/export handlers of the settings does not work (at least on esp32).

**To Reproduce**

1. download, unpack and cd into: [malloc_settings.zip](https://github.com/zephyrproject-rtos/zephyr/files/10372607/malloc_settings.zip)
2. mkdir build; cd build
3. cmake -GNinja -DBOARD=esp32 ..
4. ninja flash
5. west espressif monitor
6. answer console prompts a couple of times
```
... a lot of boot bla bla ... 

foo/str: NULL
set new foo/str?(y/N) y
new foo/str: hello world<RET>

... first reboot ...

setter called for str
foo/str: hello world
set new foo/str?(y/N) n
export called

... second reboot ...

foo/str: NULL
set new foo/str?(y/N) 
```

**Expected behavior**
after the second reboot foo/str should still show "hello world"

I can confirm that this works if I define "STATIC_STRING" during compilation. in this case all the strings are allocated statically with a fixed size and no k_malloc/k_free performed during settings handling.

**Impact**
I'll have to statically allocate all my string variables. this will increase the binary size since i cannot just source the data from NV storage.

**Environment (please complete the following information):**
 - OS: Ubuntu 22.04
 - Toolchain: Zephyr SDK 0.15.1
 - Commit SHA: 9ebb9abab7b0d662e0d5379367fb7f052959c545

**Comment by sylvioalves** [comment]
I could not reproduce the issue. Can you retry flashing and erasing: `west flash --erase`?  There is an issue with the reboot function, but it isn't related to this.

**Comment by mkettn** [comment]
> Which SDK you've used?
Zephyr SDK 0.15.1

**Comment by sylvioalves** [comment]
@mkettn, this does not seem to be `k_malloc` issue. What if you check the content of `str_val_len` before saving the content?  
```c
static int foo_settings_export(int (*export_func)(const char *name,
						  const void *val,
						  size_t val_len))
{
    if (str_val_len > 0) {
	    export_func("foo/str", str_val, str_val_len);
    }
    return 0;
}
```

The `if` below won't let `foo/str` to be erroneous replaced by NULL string.
```c
if (str_val_len > 0) {
	    export_func("foo/str", str_val, str_val_len);
    }
```

**Comment by mkettn** [comment]
Ah you're right. The problem was on my side, not on zephyrs! 

Due to wrong values for `str_val_len` the export function sometimes dropped the value. Thank you very much!
