### ISSUE TITLE
net: lwm2m: inconsistent path string handling throughout the codebase

### ISSUE THREAD

**Issue by broglep-work** [zephyrproject-rtos/zephyr#53676]
Thought the lwm2m code base there are different lwm2m path strings in use. following deviations / differences can be found:

1. Leading or no leading slash. E.g. `0/0` vs `/0/0`
2. Trailing or no training slash. E.g. `/0/1` vs. `/0/1/` 
3. Different assumptions on length of each path segment. E.g. `/65535/999` vs. `/65535/65535` 
4. Null terminated or not

At some places multiple of those differences are even combined together. 
As a result, there are various bugs sprinkled throughout the code base which are hard to find, which only show in edge cases, where you can be off-by-one (or 2,3,4) 

We should up come with a consistent formatting scheme for each use case where paths are used and after that clean up the code base. The use cases I found so far:

1. As part of lwm2m engine api (`lwm2m_engine_set_XY`)
2. As part of content formatters (senml json & cbor)
3. Presentation only: e.g. debug messages, shell commands

Some Examples / References (many more to be found):
https://github.com/zephyrproject-rtos/zephyr/blob/4c90d054524532fa6ed69a6bd55922d0b40fee57/subsys/net/lib/lwm2m/lwm2m_object.h#L63
https://github.com/zephyrproject-rtos/zephyr/blob/8cd6c55d96ff0d5f599877df29e03c358930e216/subsys/net/lib/lwm2m/lwm2m_rw_senml_cbor.c#L40
https://github.com/zephyrproject-rtos/zephyr/blob/main/include/zephyr/net/lwm2m.h#L1401
https://github.com/zephyrproject-rtos/zephyr/blob/4c90d054524532fa6ed69a6bd55922d0b40fee57/include/zephyr/net/lwm2m.h#L1401
https://github.com/zephyrproject-rtos/zephyr/blob/4c90d054524532fa6ed69a6bd55922d0b40fee57/include/zephyr/net/lwm2m_path.h#L27
https://github.com/zephyrproject-rtos/zephyr/blob/2527320848e51b15577398cfb2010131521d6e50/subsys/net/lib/lwm2m/lwm2m_util.c#L427

**Comment by carlescufi** [comment]
PR #53677 will fix this partially, but the full resolution will come when #53209 is implemented.
