### ISSUE TITLE
[Coverity CID: 180699] Error handling issues in /tests/bluetooth/tester/src/gatt.c

### ISSUE THREAD

**Issue by Shilpashree3lc** [zephyrproject-rtos/zephyr#5370]
Static code scan issues seen in File: /tests/bluetooth/tester/src/gatt.c
 Category: Error handling issues
 Function: get_attrs
 Component: Tests
 CID: 180699
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by jhedberg** [comment]
This has already been fixed by commit c20af890206e75ab4a3031c06e196bdfc1e1fe36
