### ISSUE TITLE
[Coverity CID: 180698] Null pointer dereferences in /tests/bluetooth/tester/src/gatt.c

### ISSUE THREAD

**Issue by Shilpashree3lc** [zephyrproject-rtos/zephyr#5371]
Static code scan issues seen in File: /tests/bluetooth/tester/src/gatt.c
 Category: Null pointer dereferences
 Function: get_attrs_rp
 Component: Tests
 CID: 180698
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by nashif** [comment]
unavailable in coverity anymore.
