### ISSUE TITLE
mec15xxevb_assy6853: broken UART console output

### ISSUE THREAD

**Issue by golowanow** [zephyrproject-rtos/zephyr#53715]
**Describe the bug**
mec15xxevb_assy6853 rev.A broken (binary) output at its UART console.
Bisect points to commit c7e0d727 introduced with #52303 

**To Reproduce**
1. west build -p always -b mec15xxevb_assy6853 samples/hello_world
2. flash the board as usual
3. check console output at another shell with e.g. `picocom -b 115200 /dev/ttyUSB1` 

**Expected behavior**
correct console output

**Impact**
all our test cases fail to get expected console output

**Logs and console output**
corrupted output (with commit c7e0d727)
![image](https://user-images.githubusercontent.com/61272506/211850166-0f73d26e-12b4-40ae-bb73-8b5bdc6a215f.png)
correct output (for previous commit)
![image](https://user-images.githubusercontent.com/61272506/211850420-0d46a793-3bd2-4ea4-87c6-d7d73691aa59.png)

**Environment (please complete the following information):**
 - OS: Fedora Linux kernel 5.10.12-200.fc33.x86_64
 - Toolchain zephyr-sdk-0.15.0
 - Commit c7e0d727

**Additional context**
n/a

**Comment by golowanow** [comment]
@jvasanth1, could you please have a look why this issue happens after your recent #52303 ?

**Comment by jvasanth1** [comment]
@golowanow we are unable to reproduce the issue so far. Can you let us know the MEC15xx silicon version on your board?

**Comment by golowanow** [comment]
> @golowanow we are unable to reproduce the issue so far. Can you let us know the MEC15xx silicon version on your board?

do you mean `mec15xxevb_assy6853 rev.A` as 'silicon version' of the board or something else (then where to read what you need) ?

**Comment by jvasanth1** [comment]
It should be written on the main silicon (soc chip) on the EVB below the string MICROCHIP

**Comment by golowanow** [comment]
@jvasanth1 can it be `144WFBGA` ?

**Comment by jvasanth1** [comment]
it should be something beginning with MEC15

**Comment by golowanow** [comment]
> it should be something beginning with MEC15

aha, `MEC1501`

**Comment by jvasanth1** [comment]
great, Thanks!

**Comment by golowanow** [comment]
@jvasanth1, I've also noticed it is `rev.B` not `rev.Ą`
![image](https://user-images.githubusercontent.com/61272506/212722859-7839e753-9101-45f0-a853-b102ab0d8520.png)

**Comment by golowanow** [comment]
> I think you are looking at the wrong place. The chip will be square like this image. The example is a MEC1521 (written below the microchip logo)

@jvasanth1 in our case the chip is on CPU daughter board and it has pretty weak label. Not sure we are able to read it.
Is there a way to read silicon version another way, e.g. from registers ?

**Comment by jvasanth1** [comment]
can you provide us the value of the 32-bit register at 0x400FFF1C?

**Comment by golowanow** [comment]
> it should be something beginning with MEC15

@jvasanth1 

![image](https://user-images.githubusercontent.com/61272506/212840145-c7a5e744-e4b7-41c5-972b-114b612b38e2.png)

**Comment by jvasanth1** [comment]
@golowanow can you try the draft PR to see if it solves the problem
https://github.com/zephyrproject-rtos/zephyr/pull/53869

**Comment by jvasanth1** [comment]
Thanks @golowanow 

this PR https://github.com/zephyrproject-rtos/zephyr/pull/53874 should address the issue

**Comment by jvasanth1** [comment]
Thanks!

**Comment by golowanow** [comment]
@jvasanth1, thank you !  I close the issue as resolved.
