### ISSUE TITLE
No way to get clock control subsystem type

### ISSUE THREAD

**Issue by askawu** [zephyrproject-rtos/zephyr#5376]
The clock control API is introduced since 1.9. clock_control_subsys_t is an opaque data structure used to abstract the platform-dependent information. However, there's no way for an application to get a clock_control_subsys_t from somewhere and use it to access clock control API.

For example, on the frdm k64f, the clock control should be configured correctly before accessing pins in port D because the clock control of port D is disabled by default.

IMHO, we should provide a function like device_get_binding() to get the desired clock control subsystem.

**Comment by carlescufi** [comment]
@askawu I see that `device_get_binding()` is being used to obtain a reference to an instance of the clock subsystem. Closing this, please reopen if you think this is still an issue.
