### ISSUE TITLE
sample: net/socket/http_get: no printf output

### ISSUE THREAD

**Issue by erwango** [zephyrproject-rtos/zephyr#5379]
Using net/socket/http_get, no output appears on console.
printf is hooked to newlib, but somehow, this does not work properly to get any output on console.

In this condition, it's difficult to see sample status after run.

**Comment by erwango** [comment]
Just noticed following comment:
 # Without CONFIG_NET_BUF_LOG printf() doesn't work

Closing

**Comment by pfalcon** [comment]
Yeah, and that's a weird and unresolved issue. I'd suggest to reopen it, it needs to be tracked, and we need to get to the bottom of it.

**Comment by erwango** [comment]
Issue repoened.

Ideally CONFIG_NET_BUF_LOG should not needed to get prinft output
