### ISSUE TITLE
P2P Device Firwmare Update (FOTA) over BLE and Serial

### ISSUE THREAD

**Issue by carlescufi** [zephyrproject-rtos/zephyr#5382]
Point to Point DFU with a "push" strategy: the source of the DFU procedure initiates the transfer and sends the image to the target or destination device.

Initial target transports:
* BLE (GATT)
* Serial

This will be supported using the new "MCUmgr" cross-RTOS framework.

**Comment by carlescufi** [comment]
@vrahane @ccollins476ad @sterlinghughes FYI

**Comment by lpereira** [comment]
Commenting to "subscribe" to this issue.

**Comment by carlescufi** [comment]
This will consist of a new repo “MCUmgr”, compatible with both Zephyr and Mynewt. Additional details coming soon.

**Comment by carlescufi** [comment]
MCUmgr repository: https://github.com/apache/mynewt-mcumgr

**Comment by nashif** [comment]
merged
