### ISSUE TITLE
Response on the shell missing with fast queries

### ISSUE THREAD

**Issue by SadanandPenore-eaton** [zephyrproject-rtos/zephyr#53858]
**Describe the bug**
This is regard the shell module.
If the queries on the shell is sent fast the shell module enters into unknown state.

Refer the attached image "Test2.jpg" in the attched "Test_example.zip"
[Test_example.zip](https://github.com/zephyrproject-rtos/zephyr/files/10433581/Test_example.zip)

Here also note that the problem is reproducible when the device takes more time for executing the command ( hard coded delay of 1 Sec added to simulate the extended execution time ).

Please also mention any information which could help others to understand
the problem you're facing:
 - What target platform are you using?  - nucleo_f429zi
 - What have you tried to diagnose or workaround this issue? - NA
 - Is this a regression? If yes, have you been able to "git bisect" it to a
   specific commit? - Zephyr 3.1.0
 - ...

**To Reproduce**
1. west build -b nucleo_f429zi ./ --pristine
west flash
2. Send "Test MT_MOCK" command over USB serial port one after another quickly for 8 times.
4. See error as shown in Test2.jpg ( Also present in the attached zip.

**Expected behavior**
we are using shell_print() for sending the data back on shell. If quick queries are sent the controller stops responding to any further queries. 
Expectation is that the running program should not enter the unresponsive state.

**Impact**
We are trying to implement a utility based on shell communication. This problem is impacting the utilities output.

**Logs and console output**
Already provided as Test1.jpg and Test2.jpg

**Environment (please complete the following information):**
 - Building on Windows
 - Zephyr SDK with 3.1.0 zephyr
 -3.1.0

**Additional context**
Only USB port connection required.

**Comment by jakub-uC** [comment]
This is not a bug, you are simply overflowing the buffer for input data. You are sending data faster than the shell is able to process it. You can try to increase the input buffer with a parameter:
CONFIG_SHELL_BACKEND_SERIAL_RX_RING_BUFFER_SIZE. By default, this value is 64 bytes.
