### ISSUE TITLE
Syscall parser creates syscall macro for commented/ifdefed out syscall prototype

### ISSUE THREAD

**Issue by aaronemassey** [zephyrproject-rtos/zephyr#53873]
**Describe the bug**
Code syscall parser creates syscall macro for commented/ifdefed out protoypes. This
can be reproduced when building any platform. I believe it was never reported
because this is largely only an issue when prototyping. However, since I assumed
I was at fault, I spent considerable time debugging this only to find it was
commented out code that was causing the problem.

**To Reproduce**
1. Duplicate any pre-existing syscall function name prototype but comment/ifdef it out.
1. Build the file containing the duplicate commented out syscall

Example:

```c
Causes a duplicate error

__syscall int foo_syscall(const struct device * dev);

static inline int z_impl_foo_syscall(const struct device * dev)
{
	ARG_UNUSED(dev);

	return 0;
}

// ifdefed out will break the build

#ifdef 0

__syscall int foo_syscall(int i);

#endif

// Commented out will also break the build

// __syscall int foo_syscall(int i);

```

**Expected behavior**
A syscall macro is not created for commented or ifdefed out code.

**Impact**
Definite annoyance when prototyping syscalls. I bet I'm not the first person to
run into this nor will I be the last.

**Logs and console output**

```
In file included from /home/aaronmassey/zephyrproject/zephyr/include/zephyr/syscall.h:11,
                 from /home/aaronmassey/zephyrproject/zephyr/include/zephyr/kernel_includes.h:31,
                 from /home/aaronmassey/zephyrproject/zephyr/include/zephyr/kernel.h:17,
                 from /home/aaronmassey/zephyrproject/zephyr/arch/arc/core/offsets/offsets.c:25:
/home/aaronmassey/zephyrproject/zephyr/twister-out/qemu_arc_hs/zephyr/tests/drivers/fuel_gauge/sbs_gauge/drivers.sbs_gauge_new_api/zephyr/include/generated/syscall_list.h:112: error: "K_SYSCALL_FOO_SYSCALL" redefined [-Werror]
  112 | #define K_SYSCALL_FOO_SYSCALL 106
      | 
/home/aaronmassey/zephyrproject/zephyr/twister-out/qemu_arc_hs/zephyr/tests/drivers/fuel_gauge/sbs_gauge/drivers.sbs_gauge_new_api/zephyr/include/generated/syscall_list.h:111: note: this is the location of the previous definition
  111 | #define K_SYSCALL_FOO_SYSCALL 105
      | 
cc1: all warnings being treated as errors
ninja: build stopped: subcommand failed.
```

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain Zephyr SDK
 - Commit SHA or Version used: 5c3032e51e76e42897103c95d83b0dc62444ab0e (old by
   a week but shouldn't matter)

**Additional context**

I've spent next to zero cycles debugging the syscall parser. However, I believe
it's because the parser is likely based on keyword/regex matching and that it
runs **before** the preprocessor. If we move the syscall parser to consume the
sources after the processor compilation stage, we should see this problem
resolved. I'm happy to look into this myself, but don't have the immediate
background/context.

**Comment by cfriedt** [comment]
> **Describe the bug** Code syscall parser creates syscall macro for commented/ifdefed out protoypes. This can be 

This is not a bug, it's by design. Syscalls are always available to code and should never be `#ifdef`ed-out

See https://docs.zephyrproject.org/latest/kernel/usermode/syscalls.html

> The preprocessor is intentionally not used when determining the set of system calls to generate.
