### ISSUE TITLE
usb: stm32g0: sometimes get write error during CDC ACM enumeration when using USB hub

### ISSUE THREAD

**Issue by jeromephilbert** [zephyrproject-rtos/zephyr#53937]
**Describe the bug**
On the Nucleo G0B1RE board, I run the USB CDC ACM sample program.
The board is connected to a Linux PC on 2 USB ports (see attached pictures):
- USB ST-Link => USB port 1
- PA11/PA12/GND => USB cable => USB hub => USB port 2

Sometimes when I plug the USB cable to the USB hub, I get USB write errors in the console:
```
[00:26:37.864,000] <err> usb_dc_stm32: Unable to get write lock (-16)                               
[00:26:37.864,000] <err> usb_dc_stm32: Unable to get write lock (-16)                               
[00:26:37.864,000] <err> usb_dc_stm32: Unable to get write lock (-16)                               
[00:26:42.992,000] <err> usb_dc_stm32: Unable to get write lock (-16)                               
[00:26:42.992,000] <err> usb_dc_stm32: Unable to get write lock (-16)                               
[00:26:42.992,000] <err> usb_dc_stm32: Unable to get write lock (-16)                               
[00:26:42.992,000] <err> usb_dc_stm32: Unable to get write lock (-16)                               
[00:26:48.117,000] <err> usb_dc_stm32: Unable to get write lock (-16)                               
[00:26:48.117,000] <err> usb_dc_stm32: Unable to get write lock (-16)                               
[00:26:48.117,000] <err> usb_dc_stm32: Unable to get write lock (-16)                               
[00:26:48.117,000] <err> usb_dc_stm32: Unable to get write lock (-16)                               
[00:26:58.868,000] <inf> usb_cdc_acm: Device configured
```

dmesg on the PC:
```
[575917.101610] usb 3-2.3: new full-speed USB device number 4 using xhci_hcd
[575932.545641] usb 3-2.3: device descriptor read/64, error -110
[575937.841651] usb 3-2.3: device descriptor read/all, error -110
[575937.921636] usb 3-2.3: new full-speed USB device number 5 using xhci_hcd
[575938.049137] usb 3-2.3: New USB device found, idVendor=2fe3, idProduct=0001, bcdDevice= 3.02
[575938.049139] usb 3-2.3: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[575938.049140] usb 3-2.3: Product: Zephyr CDC ACM sample
[575938.049141] usb 3-2.3: Manufacturer: ZEPHYR
[575938.049142] usb 3-2.3: SerialNumber: 4E43500400520019
[575938.089232] cdc_acm 3-2.3:1.0: ttyACM1: USB ACM device
```

This adds about 20 seconds to the enumeration phase.
If I remove the USB hub and connect the USB cable from the board directly to the PC, I do not encounter such errors.
I tested with 2 different USB hubs and I got the same results.

**To Reproduce**
1. Connect ST-Link USB port to the PC
2. Build the USB CDC ACM sample for nucleo_g0b1re: west build -b nucleo_g0b1re samples/subsys/usb/cdc_acm
3. Flash it
4. Connect PA11/PA12/GND to a USB cable, plug it to the PC through a USB hub
5. Plug/unplug USB cable to/from the USB hub, in loop until getting errors in the console

**Expected behavior**
No error should occur.

**Impact**
Sometimes USB enumeration takes up to 20 seconds, which is not acceptable in production.

**Environment:**
 - PC OS: Linux Ubuntu 18.04.6 LTS
 - PC with USB3.0 ports
 - USB3.0 hub
 - Toolchain: Zephyr SDK
 - Zephyr sha1 3d6f3a52cf075d8d9f3a94fe2c30156423fc1066 (Jan 13 2023)
 - Board: nucleo_g0b1re 

![20230119_153220](https://user-images.githubusercontent.com/78806354/213477519-e5e652ee-ed83-4ec9-a01b-c1879259b3da.jpg)
![20230119_162129](https://user-images.githubusercontent.com/78806354/213482184-61b5d182-bafe-4096-b6c2-80c13fbb8d09.jpg)

**Comment by nordicjm** [comment]
Adding both for possible USB and/or STM32 issue since Brix has seen similar issues with hubs/docks on different boards

**Comment by jfischer-no** [comment]
> If I remove the USB hub and connect the USB cable from the board directly to the PC, I do not encounter such errors.
> I tested with 2 different USB hubs and I got the same results.

There is no dedicated USB port. The only thing left is to find out if it is the shim driver or your cable connection between controller and device.

**Comment by jeromephilbert** [comment]
The issue also occurs with a shorter USB cable.
![20230119_173239](https://user-images.githubusercontent.com/78806354/213499784-1f78d6d1-90f3-4f82-9372-cbb8daee51ee.jpg)

**Comment by jfischer-no** [comment]
@erwango VBUS sensing is required, right?

**Comment by jeromephilbert** [comment]
> @erwango VBUS sensing is required, right?

You mean the VDD pin of the USB cable?
I also tested with VDD connected to 5V on the board, it does not change anything, I get the same errors.

**Comment by erwango** [comment]
@jeromephilbert I think VBUS sensing refers as what was implemented here recently https://github.com/zephyrproject-rtos/zephyr/pull/53239. This is worth having a try.

**Comment by jeromephilbert** [comment]
> @jeromephilbert I think VBUS sensing refers as what was implemented here recently #53239. This is worth having a try.

VBUS detection is not supported by the USB controller of the STM32G0.
This could be done with a dedicated GPIO but this seems not supported by the actual STM32 USB driver.

**Comment by jeromephilbert** [comment]
Yes, we can close this issue, since it is expected according to the USB specification.

**Comment by jfischer-no** [comment]
> Yes, we can close this issue, since it is expected according to the USB specification.

I have to ask, what is to be expected?

**Comment by jeromephilbert** [comment]
VBUS sensing is mandatory for self-powered devices according to the USB specification, that means that if the MCU is using an external power input the USB driver will operate correctly only if the voltage sensing is enabled.
Problem is that VBUS sensing is not supported by the USB controller of the STM32G0, but it is another topic.

**Comment by jfischer-no** [comment]
> VBUS sensing is mandatory for self-powered devices according to the USB specification, that means that if the MCU is using an external power input the USB driver will operate correctly only if the voltage sensing is enabled. Problem is that VBUS sensing is not supported by the USB controller of the STM32G0, but it is another topic.

Can you please test if it works without issues when your board is self-powered, means remove cable from USB_STLINK and connect VBUS line to board's external power pin, not sure there is one, maybe +5 on arduino connector?

**Comment by aurel32** [comment]
I already encountered similar behaviour (but on other STM32 families) and this smells like a clock accuracy issue. By default Zephyr uses the HSI48 oscillator for USB, however it does not enable the CRS to increase the accuracy. I usually use the following configuration code in my projects to workaround the issue:

```
LL_APB1_GRP1_EnableClock(LL_APB1_GRP1_PERIPH_CRS);
LL_CRS_EnableAutoTrimming();
LL_CRS_EnableFreqErrorCounter();
```

If it affects more people, it might be the time to fix it properly. I have opened PR #56639 as a first step.

**Comment by erwango** [comment]
@jeromephilbert did you had a try using https://github.com/zephyrproject-rtos/zephyr/pull/56639 ?

**Comment by erwango** [comment]
@jeromephilbert did you had a try using https://github.com/zephyrproject-rtos/zephyr/pull/56639 ?

**Comment by Desvauxm-st** [comment]
@jeromephilbert 
can you try again we push this PR
[drivers: clock_control: stm32: add an option to enable CRS for HSI48](https://github.com/zephyrproject-rtos/zephyr/pull/63111#top)
#63111
