### ISSUE TITLE
Websocket: No close message on websocket close

### ISSUE THREAD

**Issue by ssharks** [zephyrproject-rtos/zephyr#53942]
**Describe the bug**
When a websocket is being closed, it is expected to send a message of WEBSOCKET_FLAG_CLOSE. Although this implementations just closes the TCP connection without sending a websocket message with the flag WEBSOCKET_FLAG_CLOSE. The result is that other implementations observe an unexpected websocket close error.

**To Reproduce**
1. Build an websocket application
2. Build up a connection to a websocket server
3. Do some data transfer
4. Call a close on the websocket
5. See the server create an exception of an unexpected websocket close

**Expected behavior**
The websocket is properly closed, no error by the websocket server.

**Comment by rlubos** [comment]
@ssharks Please give https://github.com/zephyrproject-rtos/zephyr/pull/54141 a try.

Funnily, it was actually not that easy to find a peer to test that would actually respect the RFC in terms of close procedure. Python websocket server did not reply with `close` packet, MQTT mosquitto behaved the same way as Zephyr, closing the underlying connection as soon as MQTT disconnect was received.
