### ISSUE TITLE
[RFC] mgmt: mcumgr: Add command result code (rc) optional response

### ISSUE THREAD

**Issue by nordicjm** [zephyrproject-rtos/zephyr#53955]
**Is your enhancement proposal related to a problem? Please describe.**
At present, in MCUmgr, there is a "rc" result code variable that is returned to the client, if an error has occurred. This variable is designed around returning an error at the SMP-level, however it has been wrongly used in the past for returning the status of an actual command i.e. command level error, despite the fact that the MCUmgr command was received and processed correctly. For command handlers, error handling is a mess, it is in fact impossible to know what an error is.

For fs_mgmt, the following error codes are returned:

- MGMT_ERR_ENOENT: if a file does not exist
- MGMT_ERR_EUNKNOWN: any sort of non-0 return code from a function (could be any sort of error, what does it actually mean?)
- MGMT_ERR_EINVAL: if an invalid value was sent, if the underlying state is wrong, if the write size is larger than the original size provided (all very different errors)

for img_mgmt, the following error codes are returned:

- MGMT_ERR_EINVAL: if CBOR decoding is unsuccessful, if offset/length field is missing, if first packet size is too small, if image header magic is incorrect, if sha256 length is too long, if offset and header address are different
- MGMT_ERR_ENOENT: if no free slot is available
- MGMT_ERR_EUNKNOWN: any sort of non-0 return code from flash functions, from version check function, if upload slot already contains an image and progressive erase is not enabled, if image ID is not valid, if slot is erased, if reading slot header fails, if slot header magic is not valid/erased, if image TLV lookup fails, if more than one hash is present, if a hash is not found - also likely that this error would be returned if a flash driver was not enabled in the build

As can be seen from the groupings above, from a MCUmgr client, it is impossible to know what the error is, conversely it is also impossible to know how to handle that error because error handling depends upon what the problem is - if the problem is that (e.g. img_mgmt during an upload) a corrupt image was uploaded and it needs to be erased, how would a client know that is the actual error? Or from a filesystem perspective, is the filesystem full? Is the underlying flash device broken/corrupt? If the flash driver not enabled at all? Is the write location/mount point wrong?

**Describe the solution you'd like**
To add a new optional result code response (i.e. value of 0 would mean it is not included, and clients would assume this if the field was missing - same as "rc" has today), with a different name and meaning to the existing one, it could be named something like "cmdrc" and either have an error code list that is unique to each transport, or matches up with zephyr's errno - the latter would probably initially be thought of as the preferred method because then functions can just return this directly, e.g. calls to opening files no longer need a translation layer to convert from errno to cmdrc then cmdrc to errno, but this may be problematic because from a clients perspective, those errno errors could match up to multiple different causes still whereas a dedicated error list for each group would not, e.g. file_open_failed, file_seek_failed, file_write_failed, file_in_use, etc. could all be defined. The system used would need to be decided.

Also, to update existing groups to make use of the new command level result code. This would likely mean that the go application would probably no longer work, or if it did, would not understand error responses/conditions. Therefore a new MCUmgr client would also be needed alongside this which supported the new command format. The rule for this new MCUmgr client is fairly simple: it must not be coded in go or c#.

**Describe alternatives you've considered**
Replacing the MCUmgr rc directly with this - that then becomes an issue because then it is not known if there is an issue with the command itself or execution of the command
Not doing anything - the same problem that MCUmgr has now, inability of knowing what an error means or how to do anything with it
PR for adding additional error codes https://github.com/zephyrproject-rtos/zephyr/issues/40931 - this further increases the current problem because it is then using "rc" to return command specific errors

**Comment by nordicjm** [comment]
CC @de-nordic @carlescufi

**Comment by nordicjm** [comment]
Things to also consider:

- If this change is agreed, how will it be implemented - will it replace the existing groups making it incompatible, for devices in the field which upgrade, suddenly the commands will respond different? Should a new group be added for returning something like the MCUmgr system version - then if a device has that, it can be queried to know what the command structure should be (this could also be used going forward if breaking changes are introduced in the future) and if a device does not have that, it would use the old method. Or would it be introduced with new group IDs, keeping the old group IDs available and deprecating them so that they can still be enabled?

**Comment by de-nordic** [comment]
This addresses issue I have been also rising here https://github.com/zephyrproject-rtos/zephyr/issues/42590. I am in favor of giving the "rc" codes the meaning they should have, as SMP protocol processing return codes.

Regarding the backward compatibility issue, I was considering using the `res` field of header (https://docs.zephyrproject.org/latest/services/device_mgmt/smp_protocol.html) to pass SMP protocol version; for some time we could support two version (00 and 01), where "rc" use in  responses would differ depending on header version in request.
