### ISSUE TITLE
Bluetooth: hci: spi: race condition leading to deadlock

### ISSUE THREAD

**Issue by JordanYates** [zephyrproject-rtos/zephyr#53980]
**Describe the bug**

Due to the implementation of the driver, it is possible to get into a state where the IRQ line from the controller is active but the receive thread does not attempt to read the event. This leads to the RX thread being permanently inactive.

At the same time, the host becomes unable to transmit anything to the controller due to the manual IRQ line check before transmission:
https://github.com/zephyrproject-rtos/zephyr/blob/61f89b7b18a100744066c71c0cdee0c5ec58719a/drivers/bluetooth/hci/spi.c#L403-L410

The root cause is the following lines:

https://github.com/zephyrproject-rtos/zephyr/blob/61f89b7b18a100744066c71c0cdee0c5ec58719a/drivers/bluetooth/hci/spi.c#L291-L293
https://github.com/zephyrproject-rtos/zephyr/blob/61f89b7b18a100744066c71c0cdee0c5ec58719a/drivers/bluetooth/hci/spi.c#L316-L318

Before transmitting the interrupt is disabled, only being re-enabled after the transmission is complete. If the interrupt line goes high anywhere between these two points, the edge is not seen by the GPIO driver, and therefore `sem_request` is never given to unblock the RX thread. Therefore the code is currently racing the controller to re-enable the interrupt before the IRQ line is asserted again.

**To Reproduce**

Deadlock is easily reproducible by adding `k_sleep(K_TICKS(1));` between the following lines
https://github.com/zephyrproject-rtos/zephyr/blob/61f89b7b18a100744066c71c0cdee0c5ec58719a/drivers/bluetooth/hci/spi.c#L316-L318

**Expected behavior**

Receive thread should always attempt to read packets from the controller is the IRQ line is active.

**Impact**

Deadlocks leading to device reboots through assertion failures or watchdog timeout.

**Environment (please complete the following information):**
 - Debugged/observed on Zephyr v3.0
 - Confirmed issue still exists on Zephyr v3.2 by inspection.

**Additional context**

Happy to resolve this myself in the process of upgrading to v3.2.
PSA rather than a request for someone else to fix.

**Comment by carlescufi** [comment]
@JordanYates will you send a PR for this? thanks!
