### ISSUE TITLE
Missing fixes for v2.7 LTS backported from main

### ISSUE THREAD

**Issue by npitre** [zephyrproject-rtos/zephyr#53981]
The v2.7 LTS branch is exhibiting crashes when used as basis for custom work.

Missing fixes from the main branch are:

- commit 46eb3e5f ("gen_app_partitions: add .sdata/.sbss section into
  app_smem")

- commit df80c77e ("scripts: gen_syscalls: fix access validation size 
  on extra params array")

- commit 2cdac33d ("scripts: gen_syscalls: add missing --split-type case")

- commit 1db5c8b9 ("scripts: gen_syscalls: fix argument marshalling with 
  64-bit debug builds")

**Comment by cfriedt** [comment]
Fixed by https://github.com/zephyrproject-rtos/zephyr/issues/53981
