### ISSUE TITLE
drivers: ethernet: stm32: Enable ethernet statistics in the driver

### ISSUE THREAD

**Issue by cperera-aud** [zephyrproject-rtos/zephyr#53995]
**Is your enhancement proposal related to a problem? Please describe.**
We would like to enable the ethernet statistics in the STM32 ethernet driver so that the statistics can be queried by our application. 

**Describe the solution you'd like**
Essentially assign a function to the `get_stats` function pointer which is part of the `ethernet_api` structure. The function that is assigned to the `get_stats` API will be implemented as follows:

```
#if defined(CONFIG_NET_STATISTICS_ETHERNET)
static struct net_stats_eth *eth_stm32_hal_get_stats(const struct device *dev)
{
	struct eth_stm32_hal_dev_data *dev_data = dev->data;

	return &dev_data->stats;
}
#endif /* CONFIG_NET_STATISTICS_ETHERNET */
```

If this proposal makes sense, feel free to assign the case to me and I'll generate a PR for the changes. Without this change calls to `eth_stats_update_xyz` e.g. `eth_stats_update_bytes_rx`, `eth_stats_update_errors_rx` etc. does nothing. In addition, I would like to add some additional handling for the ethernet error counts. 

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by erwango** [comment]
@cperera-aud This would be a welcome addition. Thanks for working on this.
