### ISSUE TITLE
[DOC] drivers: pinctrl: Improvement for the pinctrl documentation

### ISSUE THREAD

**Issue by MrGreensWorkshop** [zephyrproject-rtos/zephyr#53992]
**Is your enhancement proposal related to a problem? Please describe.**

Needless to say, pinctrl is one of the awesome features of Zephyr RTOS. I want to mention a minor problem with the documentation. I just brought up some parts of the code for better understanding. As the description mentions, 'group1' name is arbitrary, so you can set any name you want. I actually use those names in my program.
https://github.com/zephyrproject-rtos/zephyr/blob/10130d8e6de8c3889f42d498d3de6115db8f2d35/dts/bindings/pinctrl/nordic%2Cnrf-pinctrl.yaml#L23-L39

The problem is that the pinctl document doesn't mention that 'group1' name is arbitrary. 
https://docs.zephyrproject.org/latest/hardware/pinctrl/index.html

**Describe the solution you'd like**
I wish there was an explanation for that.

**Describe alternatives you've considered**
none

**Additional context**
none

Thanks in advance.

**Comment by gmarull** [comment]
It's arbitrary because it doesn't mean anything, that is, no code is expecting the node to be named exactly `groupN`.
