### ISSUE TITLE
Modules: TF-M: Resolve QCBOR issues with TF-M 1.7.0

### ISSUE THREAD

**Issue by microbuilder** [zephyrproject-rtos/zephyr#54017]
## Origin

TF-M requires access to https://github.com/laurencelundblade/QCBOR.git to build.

TF-M relies on [QCBOR](https://github.com/laurencelundblade/QCBOR.git) for CBOR and COSE functionality, and currently downloads QCBOR during builds, which is incompatible with Zephyr project policies. We require a local fork of this repo under `zephyrproject-rtos` to comply with these build requirements, or an alternate solution to solve this problem.

UPDATE: It has also been pointed out the QCBOR does not have an OSI-compliant license, requiring a license exception from the TSC and board, or the removal of any code that makes use of QCBOR in default Zephyr builds.

> Note that QCBOR is really a **COSE LIBRARY**, adding encryption and signing support on top of CBOR, and as such is functionally different than zcbor as it exists today.

> **NOTE**: This repo will NOT be used directly by Zephyr, and is only required by TF-M during the managed secure firmware build process, to prevent downloading the build requirement at compile time.

## Possible Solutions

To prevent downloads and comply with project policy, one of the following needs to happen:

1. Add QCBOR to `west.yml` under `zephyrproject-rtos` as a fork
2. Add QCBOR to `west.yml` pointing to the **upstream** module (outside `zephyrproject-rtos`) 
3. Setup QCBOR as a **submodule** (see [git-submodules-in-projects](https://docs.zephyrproject.org/latest/develop/west/manifest.html#git-submodules-in-projects))
  - NOTE: The submodule approach would require two instances of QCBOR as a sub-module, since the following repos make use of it:
    - [zephyrproject-rtos/trusted-firmware-m](https://github.com/zephyrproject-rtos/trusted-firmware-m)
    - [zephyrproject-rtos/tf-m-tests](https://github.com/zephyrproject-rtos/tf-m-tests)
4. Propose a change upstream to TF-M to include QCBOR source in `lib/ext/qcbor` (they already do this for `t_cose`), but this is unlikely to pass since they recently pulled it out: https://github.com/joerchan/sdk-trusted-firmware-m/commit/8836b2229a36fe6eb23d889bbf146d1fe6226c86
5. Re-commit QCBOR files in the Zephyr fork via `git subtree`, maintaining this on top of every update until an acceptable upstream solution is found
6. Other?

## Maintainership (assuming new repo)

@microbuilder, @joerchan

## Revision

Version or SHA you would like to integrate initially

`b0e7033268e88c9f27146fa9a1415ef4c19ebaff`

## License

`BSD-3-Clause`

**Comment by stephanosio** [comment]
Marking it as a release blocker since we are currently pulling the QCBOR component via an undocumented and unauthorised method, and we need some form of resolution on this (ideally, approve it for inclusion as a module).

For instance, building `tests/drivers/entropy/api/drivers.entropy.psa_crypto` for `bl5340_dvk_cpuapp_ns`:

```
-- The C compiler identification is GNU 12.1.0
-- The ASM compiler identification is GNU
-- Found assembler: /opt/toolchains/zephyr-sdk-0.15.2/arm-zephyr-eabi/bin/arm-zephyr-eabi-gcc
-- Populating qcbor
-- Configuring done
-- Generating done
-- Build files have been written to: /__w/zephyr/zephyr/twister-out/bl5340_dvk_cpuapp_ns/tests/drivers/entropy/api/drivers.entropy.psa_crypto/tfm/lib/ext/qcbor-subbuild
[1/9] Creating directories for 'qcbor-populate'
[1/9] Performing download step (git clone) for 'qcbor-populate'
Cloning into 'qcbor-src'...
remote: Enumerating objects: 3776, done.        
remote: Counting objects:   0% (1/642)        
remote: Counting objects:   1% (7/642)    
...
``` 

cc @nashif @laurenmurphyx64

**Comment by galak** [comment]
So I hate to through a wrench into this, but qcbor isn't pure BSD-3-CLAUSE and thus wouldn't conform to Zephyr's guidelines.

**Comment by galak** [comment]
https://github.com/laurencelundblade/QCBOR/blob/master/README.md?plain=1#L527

**Comment by microbuilder** [comment]
@galak Terrible timing, but good catch, thanks for bringing this up.  

I've sent an email off to the author to see if something can be done quickly about a compliant license, but I'll look at how this can be isolated from TF-M builds as a fallback in case a last minute license change for something OSI-compliant isn't possible.

I believe only the attestation token code requires QCBOR, but I'll have to dig deeper to verify, and see how complicated it is to disable that in Zephyr.

**Comment by microbuilder** [comment]
License diff, for reference sake:

![qcbor_licdiff](https://user-images.githubusercontent.com/181073/217841794-dc452697-85d1-44ee-9b69-703e5dcc5e34.png)

@nashif What kind of time frame would be involved to ask the board for an exception here?

Presumably too long, since any exception vote request from the TSC will go to an email vote already (I suspect), then escalation to the board itself. The terms here aren't fundamentally different either.

I agree with @carlescufi (discussion on Discord) that ultimately, enabling support in t_cose -- which has it's [source included in TF-M](https://github.com/laurencelundblade/t_cose), and introduces the QCBOR dependency -- to optionally use zcbor as another backend in place of QCBOR likely solves this long term, and also gives us COSE support which we don't have today in zcbor, but that's not going to happen before the release. Discussion: https://discord.com/channels/720317445772017664/884102464985518110/1073182094525726750

Eugene (@quic-egmc) was also looking with Qualcomm legal at license changes, but it looks like this involves about 20 people, and co-ordinating signatures with all of them for a license change, which is neither quick nor guaranteed short term.

A license exception feels like the path of least resistance in the short term, given that the license terms don't seem that far off the beaten path either? That's unlikely in an acceptable time frame, though? (Also, obligatory IANAL!!!)

If an exception isn't feasible, I'll look at updating t_cose to try to pull QCBOR out in a reasonable manner, but still trying to scope how far the build dependency goes.

**Comment by microbuilder** [comment]
@stephanosio This should solve any issues causing QCBOR to be downloaded in the test case you mentioned, as well as others: https://github.com/zephyrproject-rtos/zephyr/pull/54690

That set of PRs removes the ability to enable the initial attestation secure service in TF-M as part of a standard Zephyr build -- which is what was pulling in t_cose and then the problematic QCBOR depenency -- until we can properly sort out a license exception, or another solution for QCBOR.

**Comment by joerchan** [comment]
@microbuilder Should we have another issue to re-enable initial attestation service?
Now we've closed this as a temporary workaround for the release, and not as a proper solution. I suggest we make another issue with most of the information from this issue.

**Comment by microbuilder** [comment]
> @microbuilder Should we have another issue to re-enable initial attestation service? Now we've closed this as a temporary workaround for the release, and not as a proper solution. I suggest we make another issue with most of the information from this issue.

Added: #54742
