### ISSUE TITLE
Bluetooth: Host: Invalid handling of Service Changed indication if GATT Service is registered after Bluetooth initialization and before settings load

### ISSUE THREAD

**Issue by MarekPieta** [zephyrproject-rtos/zephyr#54047]
**Describe the bug**
Registering GATT Service after Bluetooth is initialized, but before settings are loaded from non-volatile memory may lead to sending Service Changed indication to bonded peers even though the GATT database is actually not changed. 

**To Reproduce**
Selected sample must register GATT Service dynamically after Bluetooth is initialized, but before settings are loaded.
Use `samples/bluetooth/peripheral_hids_mouse` from https://github.com/nrfconnect/sdk-nrf repository.

1.` west build -b nrf52840dk_nrf52840 --pristine`
2. `west flash --erase`
3. Connect and bond with a Central.
4. Reboot the sample and reconnect with the Central.
   See the not needed Service Changed indication (either using Bluetooth sniffer or add additional logs).

The issue should replicate on any board.

**Expected behavior**
Service Changed should not be sent unless GATT database is actually changed.
To verify if the GATT database has changed, we shall wait until settings are loaded from non-volatile memory.

**Impact**
Sending unnecessary Service Changed indications.

I think that it could also make the GATT Client permanently change unaware.
Client marked as change unaware in `db_changed` called by `bt_gatt_service_register`.
Then `db_hash_process` could cancel the `sc_process` work without clearing the change-unaware state improperly set to a GATT Client.
The second issue case was not replicated locally by me.

**Logs and console output**

Below are the logs from running the sample.
I introduced additional logs (in bold) that are directly related to the SC indication handling and GATT database hash matching value read from settings.

*** Booting Zephyr OS build v3.2.99-ncs1-1522-g1a5051acc44c ***
Starting Bluetooth Peripheral HIDS mouse example
I: 8 Sectors of 4096 bytes
I: alloc wra: 0, fe8
I: dat.](7@J
I: 7b ba 2d 1b 10 ef d7 17 |{.-.....
I: 4d cb d8 5b             |M..[
I: HW Platform: Nordic Semiconductor (0x0002)
I: HW Variant: nRF52x (0x0002) 1077356637
I: No ID address. App must call settings_load()
I: Bluetooth initialized
I: Identity: E2:5anufacturer 0x0059
I: LMP: version 5.3 (0x0c) subver 0x122a
Regular advertising started
**E: SC process start 0x0001 end 0xffff**
**E: SC process start 0x0000 end 0x0000**
Connected 65:73:A4:04:A0:8C (random)
Regular advertising started
Passkey for 65:73:A4:04:A0:8C (random): 529859
Press Button 1 to confirm, Button 2 to reject.
Numeric Match, conn 0x20001d68
Security changed: 65:73:A4:04:A0:8C (random) level 4
Pairing completed: C4:93:D9:41:94:17 (public), bonded: 1
**E: stored SC for C4:93:D9:41:94:17 (public) (bt/sc/c493d94194170, 0x0000-0x0000)**

After reboot:

*** Booting Zephyr OS build v3.2.99-ncs1-1522-g1a5051acc44c ***
Starting Bluetooth Peripheral HIDS mouse example
I: 8 Sectors of 4096 bytes
I: alloc wra: 0, f80
I: data wra: 0, d4
I: SoftD 7 40 4a |.Y.](7@J
I: 7b ba 2d 1b 10 ef d7 17 |{.-.....
I: 4d cb d8 5b             |M..[
I: HW Platform: Nordic Semiconductor (0x0002)
I: HW Variant: nRF52x (0x0002)
I: Firmware: Standard Bluetooth controller (0x00) Version 18.42841 Build 1077356637
I: No ID address. App must
I: Identity: E2:59:1B:9F:37:58 (random)
I: HCI: version 5.3 (0x0c) revision 0x122a, manufacturer 0x0059
I: LMP: version 5.3 (0x0c) subver 0x122a
Direct advertising to C4:93:D9:41:94:17 (public) started
**E: SC process start 0x001b end 0x0032**
**E: Hash matches clear SC range changed**
**E: stored SC for C4:93:D9:41:94:17 (public) (bt/sc/c493d94194170, 0x001b-0x0032)**
**E: SC restore peer C4:93:D9:41:94:17 (public) start 0x001b end 0x0032**
Regular advertising started (public)
**E: stored SC for C4:93:D9:41:94:17 (public) (bt/sc/c493d94194170, 0x0000-0x0000)**
Security changed: C4:93:D9:41:94:17 (public) level 4

**Environment:**
Replicated with current main (`855cc65badf7f54fe8b5341dd0b3efb7f7370bd9`) of  https://github.com/nrfconnect/sdk-nrf.
Zephyr SDK 0.15.0.

**Comment by carlescufi** [comment]
Downgrading to Low since there's an easy workaround: to register the GATT service before initializing Bluetooth. Also, the impact is low given that it only produces a spurious SC indication.
