### ISSUE TITLE
Improve docs & samples on device tree overlay

### ISSUE THREAD

**Issue by galak** [zephyrproject-rtos/zephyr#5408]
Work up a sample to show usage of device tree overlay and document the sample so a user / app developer knows how to utilize overlay

**Comment by DWagenk** [comment]
thanks, your e-mail response already helped me a lot

> You should be able to use an device tree overlap file.  There’s examples in ./samples/bluetooth/hci_uart. The overlay file needs to be named BOARD_NAME.overlay.

**Comment by mbolivar-nordic** [comment]
@galak I believe this is fixed now: https://docs.zephyrproject.org/latest/guides/dts/howtos.html#set-devicetree-overlays

Please reopen if you disagree. I don't think a whole sample is needed

**Comment by KenthJohan** [comment]
More whole overlay samples please. I have a hard time filling in the gaps of incomplete examples to make it compile and work.
