### ISSUE TITLE
Secondary repos are missing licenses

### ISSUE THREAD

**Issue by MaureenHelm** [zephyrproject-rtos/zephyr#5411]
Need to add license headers and a top-level license files to all the secondary repositories that aren't forks from somewhere else:
net-tools
ci-*

Also, why does meta-zephyr-sdk have an MIT license?

**Comment by nashif** [comment]
> Also, why does meta-zephyr-sdk have an MIT license?

this is the yocto/openembedded license AFAIK.

**Comment by nashif** [comment]
added licenses where applicable.
