### ISSUE TITLE
Bluetooth: Audio: race hazard bt_audio_discover() callback vs unicast_client_ase_cp_discover()

### ISSUE THREAD

**Issue by Chris-StJohn-Bose** [zephyrproject-rtos/zephyr#54139]
`bt_audio_discover()` has a callback when an ASE is discovered on a remote device
`unicast_client_ase_cp_discover()` asynchronously subscribes to notifications of ASE state changes

There's no way of the application knowing when `unicast_client_ase_cp_discover()` has completed so that it is safe to call `bt_audio_stream_config()`

This causes occasional race hazards when stream configuration occurs before state changes are notified.

I'm working on a PR to resolve this, probably calling the discovery callback **after** notifications have been enabled.

Relevant lines in mainline:
https://github.com/zephyrproject-rtos/zephyr/blob/main/subsys/bluetooth/audio/unicast_client.c#L1882
https://github.com/zephyrproject-rtos/zephyr/blob/main/subsys/bluetooth/audio/unicast_client.c#L1799

**Comment by Chris-StJohn-Bose** [comment]
Example of that happens over-the-air
![image](https://user-images.githubusercontent.com/79916852/215052259-547c6e6a-4626-4b36-a412-7163fbc57970.png)

**Comment by Chris-StJohn-Bose** [comment]
Adding a `cp_subscribe[index].subscribe` callback and re-using `bt_gatt_discover_params` seems to work plus I got rid of `cp_disc[]`

**Comment by Chris-StJohn-Bose** [comment]
> Moved the commit to a separate PR to get it in ASAP: #54283

Yes that looks a lot like the fix I'm using. I'll stop preparing a PR and watch for #54283 merge. Thanks!

**Comment by Thalley** [comment]
> > Moved the commit to a separate PR to get it in ASAP: #54283
> 
> Yes that looks a lot like the fix I'm using. I'll stop preparing a PR and watch for #54283 merge. Thanks!

Feel free to add your review to https://github.com/zephyrproject-rtos/zephyr/pull/54283 :)

**Comment by Chris-StJohn-Bose** [comment]
Note sure about the priority:low as this is currently preventing streaming to a 3rd party receiver that doesn't automatically notify on CCC write, but it's being dealt with so the priority is fairly irrelevant.

**Comment by Thalley** [comment]
> Note sure about the priority:low as this is currently preventing streaming to a 3rd party receiver that doesn't automatically notify on CCC write, but it's being dealt with so the priority is fairly irrelevant.

It's something that has been in the code for more than 2 years and haven't seen any reports about it until now, so arguably it isn't that big of an issue. Aside from that, it would be quite trivial for an application to add a small waiting period between the discover callback and the next procedure. 

Finally, until https://github.com/zephyrproject-rtos/zephyr/pull/53484 is merged, none of the notifications does anything besides being logged
