### ISSUE TITLE
Socket error after deregistration causes RD client state machine to re-register

### ISSUE THREAD

**Issue by chmielewskiandreas** [zephyrproject-rtos/zephyr#54136]
Please run tests you see in this PR

https://github.com/zephyrproject-rtos/zephyr/pull/54134

The issue is quite clear. If the rdclient is suspended or deregistered any network errors caused by lwm2m_engine and forwarded by socket_fault handler should not change the rd client state.

**Comment by SeppoTakalo** [comment]
@chmielewskiandreas Please review https://github.com/zephyrproject-rtos/zephyr/pull/54307 these should fix the corner cases in state machine that you have found.

**Comment by chmielewskiandreas** [comment]
Yep, the fix works fine :) Thx
