### ISSUE TITLE
Provide a python based kconfig processing script, replacement for conf/mconf..

### ISSUE THREAD

**Issue by nashif** [zephyrproject-rtos/zephyr#5419]
Using kconfiglib, provide a python based conf replacement to allow native building on windows and drop dependency on host compiler.

**Comment by carlescufi** [comment]
Beyond `.config` and `include/generated/autoconf.h`, the current `conf` creates a `kconfig/include` tree that contains 2 non-empty files:
```
kconfig/include/config/auto.conf
kconfig/include/config/auto.conf.cmd
```

**Comment by carlescufi** [comment]
See https://github.com/zephyrproject-rtos/zephyr/pull/5569
