### ISSUE TITLE
LE Audio: Server version of bt_audio_stream_config()

### ISSUE THREAD

**Issue by mkasenberg** [zephyrproject-rtos/zephyr#54220]
To pass the ASCS/SR/ACP/BV-07-C PTS test case the server has to initiate Codec Config procedure. I did not find in public api any server version of bt_audio_stream_config() function. Is there any way around to perform the procedure in runtime?

If not, I have some quick solution here #54219.

**Comment by Thalley** [comment]
Closed by https://github.com/zephyrproject-rtos/zephyr/pull/54219
