### ISSUE TITLE
b_u585i_iot02a_ns: Can't build TFM enabled samples (TF-M 1.7.0)

### ISSUE THREAD

**Issue by erwango** [zephyrproject-rtos/zephyr#54236]
**Describe the bug**
Since https://github.com/zephyrproject-rtos/zephyr/pull/53899, TFM samples compilation fails on b_u585i_iot02a_ns target:

Traceback (most recent call last):
  File "/local/mcu/zephyrproject/zephyr/scripts/build/mergehex.py", line 28, in merge_hex_files
    ih.merge(to_merge, overlap=overlap)
  File "/local/home/frq07517/.local/lib/python3.8/site-packages/intelhex/__init__.py", line 858, in merge
    raise AddressOverlapError(
intelhex.AddressOverlapError: Data overlapped at address 0xC094000

**To Reproduce**
1. west build -p always -b b_u585i_iot02a_ns samples/tfm_integration/tfm_secure_partition
2. See error

**Expected behavior**
Compilation should be successful

**Comment by erwango** [comment]
Issue spotted. Due to changes in flash partition in TF-M v1.7.0 on board b_u585i_iot02a, b_u585i_iot02a_ns flash partition should be updated to have NS primary slot starting at 0x98000 (instead of 0x74000 with v1.6.0).
I will check if other targets could be impacted and push an update.

**Comment by microbuilder** [comment]
You might want to add this board to one of the samples (tfm_ipc, for example) so that CI catches these builds errors. I didn't notice it wasn't on the list: https://github.com/zephyrproject-rtos/zephyr/blob/main/samples/tfm_integration/tfm_ipc/sample.yaml#L8

**Comment by erwango** [comment]
> You might want to add this board to one of the samples (tfm_ipc, for example) so that CI catches these builds errors

Good point. Will do

**Comment by erwango** [comment]
Fixed by https://github.com/zephyrproject-rtos/zephyr/pull/54269
