### ISSUE TITLE
newlib: Document CONFIG_NEWLIB_LIBC_NANO default change

### ISSUE THREAD

**Issue by Jon-Salmon** [zephyrproject-rtos/zephyr#54274]
The changes made in commit 28b22b276aa8e792f4c6f0a55468240f3d24fdb1 are not documented in the 3.3.0 changelog.

This is a breaking change that resulted in a 40% change in the ROM size of my application.

**Comment by stephanosio** [comment]
This will be documented later when the "C Library" section of the release notes is filled out. I will keep this issue open to make sure that we do not forget.
