### ISSUE TITLE
ci: Scan code workflow does not report a violation for unknown LicenseRef

### ISSUE THREAD

**Issue by stephanosio** [zephyrproject-rtos/zephyr#54273]
**Describe the bug**

The [CI scan code workflow](https://github.com/zephyrproject-rtos/zephyr/blob/main/.github/workflows/license_check.yml) fails to report a license violation when an unknown SPDX LicenseRef is specified.

This resulted in the following non-compliant PRs with the license type of `LicenseRef-Nordic-5-Clause` getting merged without being noticed:

* https://github.com/zephyrproject-rtos/zephyr/pull/53929
* https://github.com/zephyrproject-rtos/zephyr/pull/43544

Reference scancode run: https://github.com/zephyrproject-rtos/zephyr/actions/runs/4024233986
Scancode result: [scancode.zip](https://github.com/zephyrproject-rtos/zephyr/files/10547714/scancode.zip)

**Comment by fabiobaltieri** [comment]
I think this has been fixed by https://github.com/zephyrproject-rtos/zephyr/pull/64105
