### ISSUE TITLE
[esp32] Console doesn't work with power management enabled

### ISSUE THREAD

**Issue by mkettn** [zephyrproject-rtos/zephyr#54301]
**Describe the bug**
I cannot use the console (e.g. `console_getchar`) with power management enabled (`CONFIG_PM=`y). I tested this only on a esp32 board, but I am sure others are affected as well.

**To Reproduce**
1. goto `zephyr/samples/subsys/console/echo/`
2. echo "CONFIG_PM=y" >> prj.conf
3. mkdir build; cd build
4. cmake -GNinja -DBOARD=esp32
5. ninja flash
6. west espressif monitor -n LF

...and try to enter any characters, the console wont work.

**Expected behavior**
The sample to work as intended, even with power management turned on.

**Impact**
The device can be set to "config mode" and expects user input, during this mode I'd like to turn off power management. Not a showstopper, but annoying.

**Logs and console output**
not applicable

**Environment (please complete the following information):**
 - OS: Ubuntu 22.04
 - Toolchain: Zephyr SDK 0.15.1
 - Commit: 883e9d367f6cd489666a562c83df0f56458c94b2

**Comment by nordicjm** [comment]
Works fine here on bl653_dvk, marking as espressif issue

**Comment by sylvioalves** [comment]
@mkettn, sorry for taking so long to reply. The simple explanation is that PM features on ESP32 are still under development. Currently the PM only works for GPIO and timer wake up. Check `samples/boards/esp32/deep_sleep` and  samples/boards/esp32/light_sleep`.  
It means that enabling PM for uart wake up (when interrupt-driven is enabled) won't work yet.

**Comment by mkettn** [comment]
Hello @sylvioalves 
thank you for the status update. When I have time I'll take a closer look at the samples you mentioned.

**Comment by nashif** [comment]
@sylvioalves  Can you please look at this bug please and see if it still exists?

**Comment by sylvioalves** [comment]
Yes, it does exists. We haven't added PM support over UART driver yet.
