### ISSUE TITLE
CANopen SYNC message is not received

### ISSUE THREAD

**Issue by jmbrederveld** [zephyrproject-rtos/zephyr#54364]
I am currently facing an issue using CANopen on the STM32F205RB:
I am in the process of upgrading my (working) code base to support zephyr-3.3-RC1.
All CANopen related functionality seems to be present and working (NMT, SDO, ..), however I am facing issues regarding a configured TPDO.

Since the configured transmission type is set to `1`, it should send the TPDO on every SYNC message (COB-ID 0x80) sent by the NMT master.
In testing, it was observed that the SYNC message is not received by the stack, as it does not enter the `if` statement located here: `modules/lib/canopennode/stack/CO_SYNC.c:312` 

I am able to reproduce this issue while running the `samples/modules/canopennode` sample by adjusting the python canopen script as written in the README file, by setting the transmission type to 1.

My setup currently is:
- OS: Linux, xubuntu 22.10
- Toolchain: gnuarmemb 
- Zephyr v3.3-RC1

I hope you can aid me in resolving this issue.

Kind regards,
Justin

**Comment by henrikbrixandersen** [comment]
Please provide the changes to the Python test code you used to reproduce this issue. Also, are you upgrading from a previous Zephyr revision where the same tests pass? If so, which revision? Are you able to bisect where they bug was introduced?

**Comment by henrikbrixandersen** [comment]
I can reproduce the issue. Looking into providing a fix.

**Comment by sjuut** [comment]
Thank you!

I was already in the process of bisecting the git history of zephyr and the respective canopennode module, but proved a bit tedious on my hardware.
Let me know if I can assist or provide any additional information.

**Comment by jmbrederveld** [comment]
Thank you!

I was already in the process of bisecting the git history of zephyr and the respective canopennode module, but proved a bit tedious on my hardware.
Let me know if I can assist or provide any additional information.

**Comment by henrikbrixandersen** [comment]
@jmbrederveld Please test the fix in #54771 and report back.

**Comment by sjuut** [comment]
I can confirm this works on my setup!
Thank you so much for this effort, amazing work!

**Comment by jmbrederveld** [comment]
I can confirm this works on my setup!
Thank you so much for this effort, amazing work!
