### ISSUE TITLE
soc: arm: st_stm32: Incorrect SRAM devicetree definition for the STM32L471xx

### ISSUE THREAD

**Issue by liamclarkza** [zephyrproject-rtos/zephyr#54387]
**Description**
The SRAM devicetree definition for the STM32L471xx series of SOCs is incorrect. Currently, a single 128kb block of SRAM is being defined where there should be two blocks, one 96kb and the other 32kb both at separate addresses.

**To Reproduce**
You can cause a fault if you run any application that runs over the 96kb boundary of the SRAM.

**Expected behavior**
Define SRAM boundaries correctly.

**Impact**
Causes hard-to-diagnose issues when using the SOC.

**Comment by liamclarkza** [comment]
I have linked a PR that fixes the issue: #54281

**Comment by erwango** [comment]
Fixed by #54281
