### ISSUE TITLE
Nominate @Vge0rge as contributor

### ISSUE THREAD

**Issue by Vge0rge** [zephyrproject-rtos/zephyr#54405]
# Background

The [TSC Project Roles] defines the main roles for the Zephyr Project, including
Maintainer, Collaborator, and Contributor.

By default anyone that contributes code or documentation is a Contributor, but
with the lowest [GitHub Permission Level] of Read. For example, Contributors
with Read permission do not have the permission to add reviewers to a pull
request.

Use this template to nominate a GitHub user for the Contributor role with
Triage permission level, which allows the user to add reviewers to a pull
request and be added as a reviewer by other users.

# Nomination

## GitHub User

Provide the following information about the GitHub user:

1. Full Name: Georgios Vasilakis
1. GitHub username: Vge0rge
1. Organization (optional): Nordic Semiconductor

## Supporting Documents
https://github.com/zephyrproject-rtos/zephyr/pull/47931
https://github.com/zephyrproject-rtos/zephyr/pull/48774
https://github.com/zephyrproject-rtos/zephyr/pull/52299

[TSC Project Roles]: <https://docs.zephyrproject.org/latest/project/project_roles.html>
[GitHub Permission Level]: <https://docs.github.com/en/organizations/managing-access-to-your-organizations-repositories/repository-roles-for-an-organization>

**Comment by stephanosio** [comment]
@Vge0rge has been added as a user with Triage permission.
