### ISSUE TITLE
Missing documentation of lwm2m_rd_client_resume and lwm2m_rd_client_pause

### ISSUE THREAD

**Issue by chmielewskiandreas** [zephyrproject-rtos/zephyr#54439]
https://docs.zephyrproject.org/latest/connectivity/networking/api/lwm2m.html

This feature has been implemented but the state machine was not yet updated.

**Comment by SeppoTakalo** [comment]
Those mentioned functions are internal, and should not appear on a public documentation. However `lwm2m_engine_pause()` and `lwm2m_engine_resume()` are the public part, and their events and states were missing on the state diagram. I added those in #56560
