### ISSUE TITLE
Build system should skip zephyr\drivers\ethernet module if TAP & SLIP already provides a network driver in zephyr\drivers\net\slip.c

### ISSUE THREAD

**Issue by ofirshe** [zephyrproject-rtos/zephyr#54460]
Hey, 

I have set up a UART device on my board as a UART-pipe to run a TCP/IP application using SLIP. To do so, I added a node in the 'chosen' section in the DTS file:
` "zephyr,uart-pipe = &lpuart1".`

In the prj.conf file, I enabled the following configurations:
```
#SLIP
CONFIG_SLIP=y
CONFIG_SLIP_TAP=y
CONFIG_NET_DRIVERS=y

#Networking 
CONFIG_NETWORKING=y
CONFIG_NET_TCP=y
CONFIG_NET_IPV4=y
CONFIG_NET_CONFIG_SETTINGS=y
CONFIG_NET_CONFIG_NEED_IPV4=y
CONFIG_NET_CONFIG_MY_IPV4_ADDR="192.0.2.1"
CONFIG_NET_SOCKETS=y
CONFIG_NET_SOCKETS_POSIX_NAMES=y
```

However, enabling CONFIG_NETWORKING causes the build system to search for source files in the zephyr\drivers\ethernet module, which is not necessary as the ethernet driver setup is already provided in drivers/net/slip.c if CONFIG_SLIP=y. As a result, I am getting a compilation warning "CMake Warning at zephyr/CMakeLists.txt:824 (message): No SOURCES given to Zephyr library: drivers__ethernet. Excluding target from build."

The build system should bypass the zephyr\drivers\ethernet module if TAP & SLIP already provides a network driver in zephyr\drivers\net\slip.c.

Best regards,
Ofir.

**Comment by jukkar** [comment]
Some discussion at https://github.com/zephyrproject-rtos/zephyr/discussions/54203
