### ISSUE TITLE
SAM spi bus inoperable when interrupted on fast path

### ISSUE THREAD

**Issue by nandojve** [zephyrproject-rtos/zephyr#54461]
**Describe the bug**
The Atmel SAM fast tx/rx/txrx spi functions will leave the SPI bus in an inoperable state if interrupted, potentially spinning forever waiting on some data.

There are evidence from @yperess as he ran into trouble with faster data ready interrupts on the icm42688 with the tdk robokit.

**Expected behavior**
SAM fast spi driver functions should work properly when driver is interrupted.

**Impact**
This could lead product inoperative.

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain Zephyr SDK 0.15
 - Commit v3.3-RC2

**Comment by yperess** [comment]
Thanks for making the big report, I'm going to run my driver with this patch tonight and verify. Currently I can't get interrupts faster than 12.5Hz on the TDK robokit1 board.
