### ISSUE TITLE
Bluetooth: Controller: le_ext_create_connection fails with initiating_PHYs == 0x03

### ISSUE THREAD

**Issue by Tronil** [zephyrproject-rtos/zephyr#54531]
When CONFIG_BT_CTLR_PARAM_CHECK is set, the `le_ext_create_connection()` function in hci.c will fail with BT_HCI_ERR_UNSUPP_FEATURE_PARAM_VAL  when initiating_PHYs is set to 0x03 (ie. bit 0 and bit 1 set). This is incorrect; 0x03 simply means that connection parameters are provided for the LE 2M PHY as well (see BT Core Spec Vol 4 Part E, section 7.8.66).

The offending code is here:
```
	phys_bitmask = BT_HCI_LE_EXT_SCAN_PHY_1M;
	if (IS_ENABLED(CONFIG_BT_CTLR_PHY_CODED)) {
		phys_bitmask |= BT_HCI_LE_EXT_SCAN_PHY_CODED;
	}

	phys = cmd->phys;
	if (IS_ENABLED(CONFIG_BT_CTLR_PARAM_CHECK) &&
	    (((phys & phys_bitmask) == 0) || (phys & ~phys_bitmask))) {
		*evt = cmd_status(BT_HCI_ERR_UNSUPP_FEATURE_PARAM_VAL);

		return;
	}
```
The `(phys & phys_bitmask) == 0` check is fair; I don't understand why  `(phys & ~phys_bitmask)` is there though (and it causes this failure).

**Comment by cvinayak** [comment]
`(phys & ~phys_bitmask)` checks that unsupported PHY is not supplied to the controller. Connection shall only be initiated on 1M or Coded PHY.
