### ISSUE TITLE
[nRF] The nRF boards should not enable networking stacks

### ISSUE THREAD

**Issue by SebastianBoe** [zephyrproject-rtos/zephyr#5454]
It is IMHO undesired behaviour that nrf52840_pca10056_defconfig and friends are enabling SW components.

Especially big SW components like BT.

HW Kconfig should be describing the available HW, not making assumptions about what SW is going to be used.

Networking stacks should be pulled in directly or indirectly because they are needed by applications.

**Comment by SebastianBoe** [comment]
Kconfiglib was recently merged and it enabled warnings when configs were redundant, previously these warnings defaulted to being suppressed.

Building the Bluetooth beacon sample for nrf52_pca10040 now shows the warning:

> /home/sebo/zephyr/samples/bluetooth/beacon/prj.conf:1: warning: BT set more than once. Old value: "y", new value: "y".


```
sebo@mach:~/zephyr/samples/bluetooth/beacon$ cb
-- Found PythonInterp: /usr/bin/python3 (found suitable version "3.5.2", minimum required is "3.4") 
-- Selected BOARD nrf52_pca10040
Zephyr version: 1.10.99
/home/sebo/zephyr/samples/bluetooth/beacon/prj.conf:1: warning: BT set more than once. Old value: "y", new value: "y".

```

We are redundantly setting this config because both the sample and the board is enabling BT. So fixing this issue would also fix the warning.

**Comment by pfalcon** [comment]
A quick note that this doesn't have to be an "issue" which needs to be fixed. It may be that such values should be logically unified, and no warning should be produced.

**Comment by SebastianBoe** [comment]
> A quick note that this doesn't have to be an "issue" which needs to be fixed. It may be that such values should be logically unified, and no warning should be produced.

I agree, not all warnings of this kind are "issues", but in this particular case IMHO it is.

**Comment by nashif** [comment]
isnt CONFIG_BT here for the controller and radio which is considered a HW component, if you apply this rule globally, then we also should not be enabling UART and GPIO and and...

**Comment by SebastianBoe** [comment]
I can't speak to the original intention.

The radio is a HW component.
The controller is a SW component that runs on top of the radio.

I am OK with board's declaring that CONFIG_HAS_BT_RADIO or something similiair if needed.

I have not looked into UART or GPIO. But there might be some exceptions to the rule when
the impact is less severe.

**Comment by SebastianBoe** [comment]
Another example of this in the wild: https://github.com/SebastianBoe/mcuboot/blob/master/boot/zephyr/prj.conf#L19
