### ISSUE TITLE
Add SDHC card support

### ISSUE THREAD

**Issue by nzmichaelh** [zephyrproject-rtos/zephyr#5457]
This is a tracking bug for adding SDHC card support.  I plan to do this, but I thought I'd log a bug so others can find it if they're interested.

The straw man plan is:

* Support SDHC cards (no MMC or plain SD)
* Use the SD SPI mode
* Implement using the disk layer and test with ELMFAT
* Implement CRC7 and CRC16
* Stretch: support hotplug

**Comment by MaureenHelm** [comment]
SDHC support added in #5528 and #16468
