### ISSUE TITLE
[ESP32] Make error

### ISSUE THREAD

**Issue by iha** [zephyrproject-rtos/zephyr#5458]
@lpereira 

Building hello_world sample, for example,  I got this error:

`xtensa-esp32-elf/5.2.0/../../../../xtensa-esp32-elf/bin/ld: unrecognized option '--print-memory-usage'`

I've been using this toolchain [version 1.22.0-73](https://dl.espressif.com/dl/xtensa-esp32-elf-linux64-1.22.0-73-ge28a011-5.2.0.tar.gz). And it worked until my last git rebase.

**Comment by SebastianBoe** [comment]
Regression from https://github.com/zephyrproject-rtos/zephyr/commit/dbdd7222392a627e7d5b6b0a741b99e9a8258cc9.

**Comment by iha** [comment]
@SebastianBoe  thanks, it works.
