### ISSUE TITLE
scripts: extract_dts_includes: check yaml dts binding property "category: "

### ISSUE THREAD

**Issue by erwango** [zephyrproject-rtos/zephyr#5460]
yaml dt-binding files document a property category: <optional | required>
Aim is to document that a dts node property should be present or not.

This property is currently not checked, which makes it bogus.

Check the property when dts file is parsed, and trigger an error when a property node tagged "required" is not present.

**Comment by mbolivar** [comment]
Thanks for raising this! I agree this issue seems valid. @agross-linaro, any comments?

**Comment by erwango** [comment]
@galak: We recently discussed about "improve error checking of yaml in the future".
I think this issue belongs to this topic.
If you already have pre-defined requirements, let's put them here, so this issue could be solved in the good direction from start.

**Comment by erwango** [comment]
@ulfalizer , maybe you can take this one, while you're cleaning out the script?

**Comment by erwango** [comment]
@ulfalizer , I hope you don't mind I assign this to you since you are in the process of heavily reworking the script.

**Comment by pabigot** [comment]
@galak @ulfalizer Is this being actively worked in the scripting overhaul?  Is that overhaul being tracked somewhere?  The lack of robust device tree validation and presence of quirky behavior is very disheartening.

**Comment by galak** [comment]
@erwango is this still relevant with the new dts generation scripts?

**Comment by erwango** [comment]
Tested and working indeed.
One question though, I tested setting `category: required` to a `type: boolean`. If prop is not present, no message is generated. @ulfalizer is that an intended behavior?

**Comment by galak** [comment]
> One question though, I tested setting `category: required` to a `type: boolean`. If prop is not present, no message is generated. @ulfalizer is that an intended behavior?

If the prop is not in the dts?  Than this is correct behavior as a 'boolean' is allowed to not exist in the .dts

**Comment by pabigot** [comment]
Note that in this special case a define is generated for `DT_PROPERTY=0`, unlike other property types where the absence is indicated by no generated define.  This is a little inconsistent, but can be dealt with.

**Comment by erwango** [comment]
Fine with me then. Let me close this point.
