### ISSUE TITLE
cmake: signing: Allow extended/replacing signing with external or out of tree systems

### ISSUE THREAD

**Issue by nordicjm** [zephyrproject-rtos/zephyr#54653]
**Is your enhancement proposal related to a problem? Please describe.**
At present, when creating a signed application which targets mcuboot, west automatically does the signing using this cmake file: https://github.com/zephyrproject-rtos/zephyr/blob/main/cmake/mcuboot.cmake

This works fine for in-tree samples and testing, but is limited to how it works in that file and cannot (at present) be changed or extended for projects without forking the zephyr repository itself.

**Describe the solution you'd like**
A way to be able to extend this or override it, either for adding new functionality (e.g. instead of using a private key to sign the hash, someone might want to take the hash and send it to another system or device with a HSM (hardware security module) which is then used to generate the signature), or to have a different method of signing (e.g. to support other bootloaders, or to change what information is used for signing).

**Describe alternatives you've considered**
Forking zephyr and changing - not even worth considering

**Comment by sjg20** [comment]
See here for a firmware-packaging solution that might be useful for Zephyr

https://u-boot.readthedocs.io/en/latest/develop/package/binman.html#what-it-does

Basically, we have the same issue in U-Boot and it is being solved in that tool
