### ISSUE TITLE
NFFS file system does no build when newlib libc is used

### ISSUE THREAD

**Issue by vanwinkeljan** [zephyrproject-rtos/zephyr#5467]
The NFFS file system does not build when newlib libc is used due to type conflicts in NFFS os specific function  implementations. This is caused due to the fact that NFFS uses uint32_t (defined as unsigned long in case of newlib) in the prototypes but zephyr uses u32_t (defined as unsigned int) in the implementations.

**Comment by lpereira** [comment]
Shouldn't the fix in #5468 be the other way around, fixing the declaration of `u32_t` to match `uint32_t`?  (I never bought the argument for these short types, but... pick your battles, I guess.)

**Comment by vanwinkeljan** [comment]
@lpereira  Actually that was my first fix where I update zephyr/types.h to typedef uint32_t to u32_t but I thought this was a bit to intrusive.
