### ISSUE TITLE
ESP32 SPI word size is not respected

### ISSUE THREAD

**Issue by morsisko** [zephyrproject-rtos/zephyr#54746]
I need to communicate with SPI device. To do so, 32 bits need to be send in single SPI transaction, as this is required by the receiving device. However, when you set SPI word size to 32 in Zephyr, only 8 bits will be send when you use ESP32 SPI driver. 

**To Reproduce**
Initialize your SPI driver like this:
```
SPI_DT_SPEC_INST_GET(_num, \
			SPI_OP_MODE_MASTER | \
			SPI_TRANSFER_MSB | \
			SPI_MODE_CPOL | \
			SPI_WORD_SET(32), \
			0),
```

Send your payload like this:
```
        uint8_t buffer_tx[4] = { 0xAA, 0xBB, 0xCC, 0xDD };
	uint8_t buffer_rx[4];

	const struct spi_buf tx_buf = {
		.buf = buffer_tx,
		.len = sizeof(buffer_tx),
	};

	const struct spi_buf_set tx = {
		.buffers = &tx_buf,
		.count = 1
	};

	const struct spi_buf rx_buf= {
		.buf = buffer_rx,
		.len = sizeof(buffer_rx),
	};

	const struct spi_buf_set rx = {
		.buffers = &rx_buf,
		.count = 1
	};

	spi_transceive_dt(&config->bus, &tx, &rx));
```

**Expected behavior**
0xAA 0xBB 0xCC 0xDD should be send over SPI in single transaction

**Impact**
This would make SPI sensor drivers that use 32 bit word size unable to work

**Logs and console output**
Screen from logic analyzer:
![obraz](https://user-images.githubusercontent.com/11231925/218284099-4753cdc7-d462-4cd4-b02c-cd03da194664.png)

As you can see, only 8 bits are being sent when 32 bit word size is used.
**Environment:**
 - OS: Linux Ubuntu 22
 - Toolchain: zephyr-sdk-0.15.0_linux-x86_64
 - Commit SHA: bb8b74502091a90bff08de1b66b560a04b7c28e1

**Additional context**
Board that I used: esp32

Interestingly, when you use `SPI_WORD_SET(16)`, indeed 16 bits will be sent in single transaction:
![obraz](https://user-images.githubusercontent.com/11231925/218284196-d2ea3799-23f3-4ca2-a6b0-9954fed3aef8.png)

And when you set `SPI_WORD_SET(8)`... 32 bits will be sent in single transaction! (In my opinion this is what should happen when `SPI_WORD_SET(32)` is set):
![obraz](https://user-images.githubusercontent.com/11231925/218284262-6fa8e76b-76e0-4b61-b7bc-c4c91a8fb92c.png)

For my tests I can use `SPI_WORD_SET(8)` so this is not a problem for me, however as I said above, this will make all sensor drivers that would use `SPI_WORD_SET(32)` unable to work, as the sensor won't receive all the data.

**Comment by morsisko** [comment]
Update. I just did the same experiment with STM32 board (to be more precise: nucleo_f429zi). Unfortunately this driver doesn't support 32 bit word length, but this is what happen when I set the word size to 16:
![obraz](https://user-images.githubusercontent.com/11231925/218322401-6f2f3573-81b8-4f4a-a391-8e34548452e7.png)
It looks like the driver treat `len` property of `spi_buf` as number of words, not number of bytes, however ESP32 driver treat is as number of bytes. Which behavior is correct?

**Comment by LucasTambor** [comment]
@morsisko can you please test #56283?  I believe it solves the issue. Thanks!

**Comment by morsisko** [comment]
Hello @LucasTambor. Sorry, I forgot about the issue. I checked it right now. At this moment, no matter what spi_len buffer size I choose, all 32 bits are sent in single transaction. If this is the desired behavior it works ok.

By the way, I see some inconsistency between SPI drivers. Please look at this code:

```
const struct spi_buf tx_buf = {
	.buf = buffer_tx,
	.len = sizeof(buffer_tx),
};
```
What is the .len here? Is it the length of the buffer in bytes, or length of the buffer in words?

**Comment by LucasTambor** [comment]
Hello @morsisko. No problem :) I believe the correct behaviour of the driver is now expected since #57426 .
