### ISSUE TITLE
ESP32C3 SPI DMA host ID   

### ISSUE THREAD

**Issue by LucasTambor** [zephyrproject-rtos/zephyr#54846]
**Describe the bug**
The current value of ESP32C3 host ID for SPI DMA is 1. The correct value should be 0.

The PR #54832 fixes the issue.

**Comment by henrikbrixandersen** [comment]
Please use our bug template when reporting bugs. You need to edit this issue to include the needed information from https://github.com/zephyrproject-rtos/zephyr/blob/main/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by LucasTambor** [comment]
Closing this issue because it is not really a bug, but a problem that came up after refactoring some aspects of the drive. I will submit the PR as a normal contribution and wait until after feature freeze for it to be merged :)
