### ISSUE TITLE
ESP32: Compilation errors after migrating to zephyr 3.2.0

### ISSUE THREAD

**Issue by VineetaNarkhede-eaton** [zephyrproject-rtos/zephyr#54855]
**Build error in dma_types.h and i2s_ll.h after migrating to zephyr 3.2.0**
We have custom ADC code running on ESP32 using zephyr 3.1.0, now we are migrating to zephyr 3.2.0 and observed following errors in espressif module files i.e dma_types.h and i2s_ll.h

1. Error in dma_types.h
`c:\workspace\zephyr-v3.2.0\modules\hal\espressif\components\hal\include\hal\dma_types.h:41:15: error: expected constructor, destructor, or type conversion before '(' token
 _Static_assert(sizeof(dma_descriptor_t) == 12, "dma_descriptor_t should occupy 12 bytes in memory");`
       
This statement is same in zephyr 3.1.0 and 3.2.0

2. Error in i2s_ll.h
`c:\workspace\zephyr-v3.2.0\modules\hal\espressif\components\hal\esp32\include\hal\i2s_ll.h:757:25: error: invalid conversion from 'unsigned int' to 'i2s_pdm_dsr_t' [-fpermissive]
     *dsr = hw->pdm_conf.rx_sinc_dsr_16_en;`
Function is modified in zephyr 3.2.0 as shown below:
![image](https://user-images.githubusercontent.com/88422239/218983854-a4262768-d274-4685-9de3-dd3bfc41a760.png)
I am able to fix this error by typecasting like `*dsr = (i2s_pdm_dsr_t)hw->pdm_conf.rx_sinc_dsr_16_en;`

Latest version of [hal_espressif](https://github.com/zephyrproject-rtos/hal_espressif) is having the same code in both files, I haven't seen the fix for these errors.

Please suggest the resolution for both errors as soon as possible. 

**Environment :**
 - OS: Windows
 - Toolchain Zephyr SDK 0.15.2 , espressif 8.4.0 (C:\Users\<username>\.espressif\tools\zephyr)

**Comment by sylvioalves** [comment]
Checked ADC and it is properly working. Closing this. Open again if needed.
