### ISSUE TITLE
west flash --elf-file is not flashing using .elf file, but using zephyr.hex to flash

### ISSUE THREAD

**Issue by mithunpandey** [zephyrproject-rtos/zephyr#54872]
I used the following build and flash command and expecting that when we use a -elf-file flag for west flash, it should not require the zephyr.hex file, if i remove the zephyr hex file from the build folder, then the flash command is failing. with error "build\zephyr\zephyr.hex does not exist"

west build -b nucleo_f429zi -p 
**west flash --elf-file .\build\zephyr\zephyr.elf** -r openocd --skip-rebuild --cmd-pre-init  "hla_serial 066CFF363336485043072710"

-- west flash: using runner openocd
**-- runners.openocd: Flashing file: C:/XXXX/build/zephyr/zephyr.hex**
Open On-Chip Debugger 0.11.0 (2021-11-18) [https://github.com/sysprogs/openocd]
Licensed under GNU GPL v2
libusb1 09e75e98b4d9ea7909e8837b7a3f00dda4589dc3
For bug reports, read
        http://openocd.org/doc/doxygen/bugs.html
Info : The selected transport took over low-level target control. The results might differ compared to plain JTAG/SWD
Info : clock speed 2000 kHz
Info : STLINK V2J32M22 (API v2) VID:PID 0483:374B
Info : Target voltage: 3.232461
Info : stm32f4x.cpu: Cortex-M4 r0p1 processor detected
Info : stm32f4x.cpu: target has 6 breakpoints, 4 watchpoints
Info : starting gdb server for stm32f4x.cpu on 3333
Info : Listening on port 3333 for gdb connections
    TargetName         Type       Endian TapName            State
--  ------------------ ---------- ------ ------------------ ------------
 0* stm32f4x.cpu       hla_target little stm32f4x.cpu       running

Info : Unable to match requested speed 2000 kHz, using 1800 kHz
Info : Unable to match requested speed 2000 kHz, using 1800 kHz
target halted due to debug-request, current mode: Thread
xPSR: 0x01000000 pc: 0x0800b0a0 msp: 0x2000a9c0
Info : device id = 0x20016419
Info : flash size = 2048 kbytes
Info : Dual Bank 2048 kiB STM32F42x/43x/469/479 found
auto erase enabled
wrote 262144 bytes from file C:/XXXXX/build/zephyr/zephyr.hex in 7.781227s (32.900 KiB/s)

Info : Unable to match requested speed 2000 kHz, using 1800 kHz
Info : Unable to match requested speed 2000 kHz, using 1800 kHz
target halted due to debug-request, current mode: Thread
xPSR: 0x01000000 pc: 0x0800b0a0 msp: 0x2000a9c0
verified 168160 bytes in 1.359219s (120.818 KiB/s)

Info : Unable to match requested speed 2000 kHz, using 1800 kHz
Info : Unable to match requested speed 2000 kHz, using 1800 kHz
shutdown command invoked

**Comment by mbolivar-nordic** [comment]
Thanks for taking the time to file an issue. Please see https://github.com/zephyrproject-rtos/zephyr/issues/52262 for an explanation of why this is not working the way you think it should. To try to resolve your issue, check if your runner supports `--file` and use that instead if it does.
