### ISSUE TITLE
west espressif install and update commands failing in zephyr 3.2.0

### ISSUE THREAD

**Issue by VineetaNarkhede-eaton** [zephyrproject-rtos/zephyr#54890]
Hi,
I want to get espressif tools through west espressif install and update but these commands are not working in zephyr 3.2.0. getting below error,
`usage: west espressif [-h] [-b BAUD] [-p PORT] [-e ELF] {monitor} west espressif: error: argument command: invalid choice: 'install' (choose from 'monitor')`

Commands: 
west update  (command successful)
west espressif install
west espressif update

I ran install.bat from "\zephyr-v3.2.0\modules\hal\espressif", but running into other errors.

west espressif install and update working partially in zephyr 3.1.0, it is installing only openocd-esp32, I somehow managed to get other tools as shown below
![image](https://user-images.githubusercontent.com/88422239/219314966-da492573-541c-4a72-b7f3-bc4c6aff43eb.png)

**Environment** :
OS: Windows
Toolchain Zephyr SDK 0.15.2 , espressif : esp-2020r3-8.4.0 (C:\Users\<username>\.espressif\tools\zephyr)
Zephyr version: 3.2.0

**Comment by henrikbrixandersen** [comment]
You should be using the Zephyr SDK for ESP32 as well for v3.2.0.

**Comment by VineetaNarkhede-eaton** [comment]
> You should be using the Zephyr SDK for ESP32 as well for v3.2.0.
Thanks @henrikbrixandersen for your response!
I am able to use Zephyr SDK for ESP32.  I still have following queries,
1. In which case `west espressif install` should be used?
2. Why this command is not working in zephyr 3.2.0?
