### ISSUE TITLE
drivers: sensors: bmi270 does not wait for data ready bit resulting in many failed i2c transactions

### ISSUE THREAD

**Issue by maxmclau** [zephyrproject-rtos/zephyr#54921]
**Describe the bug**
BMI270 driver does not currently support GPIO interrupt driven data ready triggering so you are forced to constantly poll the device at whatever rate it should be producing data. This causes many i2c transactions to fail, especially when sampling at higher data rates.

**Expected behavior**
Drivers should not request data from BMI270 device unless data is ready. This can be done by waiting on the the `DRDY` bits. This behavior is already implemented in BMI160 driver.

**Impact**
Annoyance when sole device on bus. Showstopper when i2c bus is shared with many peripherals. As noted in [#54917](https://github.com/zephyrproject-rtos/zephyr/issues/54917) this can cause unrecoverable bus arbitration errors.

**Additional context**
I'm currently working on a PR to fix this. Will update when ready.

**Comment by tautologyclub** [comment]
See https://github.com/zephyrproject-rtos/zephyr/pull/55275

**Comment by maxmclau** [comment]
Closed with https://github.com/zephyrproject-rtos/zephyr/pull/55275
