### ISSUE TITLE
config BT_CTLR_DEBUG_PINS

### ISSUE THREAD

**Issue by grapygrape** [zephyrproject-rtos/zephyr#5499]
In subsys/bluetooth/controller/Kconfig it says at config BT_CTLR_DEBUG_PINS:

"Turn on debug GPIO toggling for the BLE Controller. This is useful when debugging with a logic analyzer or profiling certain sections of the code. When enabled, pins P0.16 to P0.25 are taken over exclusively by the controller and cannot be used outside of it."

but in subsys/bluetooth/controller/hal/nrf5/debug.h it says:
#ifdef CONFIG_BT_CTLR_DEBUG_PINS
#if defined(CONFIG_BOARD_NRF52840_PCA10056)
#define DEBUG_PORT       NRF_P1

Is this correct?

**Comment by cvinayak** [comment]
@grapygrape "When enabled, pins P0.16 to P0.25 are taken over exclusively by the controller and cannot be used outside of it." is incorrect statement once I introduced the pins being on the same Pinhead on the different DKs. If you have a suggested help text, feel free to mention here or even better send a PR.
