### ISSUE TITLE
API for getting the response ATT MTU

### ISSUE THREAD

**Issue by alwa-nordic** [zephyrproject-rtos/zephyr#55027]
The Zephyr Bluetooth API is not expressive enough to perform the "Read Long Characteristic Values" procedure (Core 5.3 Vol 3 Part G 4.8.3). In this procedure, the ATT MTU of the operation is significant. There is however no API to unambiguously get the ATT MTU for a specific request.

Core 5.3 Vol 3 Part F 3.4.2.2 Figure 3.1 makes it clear that ATT MTU is a property of a Req/Rsp pair. The value of this property remains constant even if the ATT bearer associated with the request changes MTU.

The API `bt_gatt_get_mtu` is not good enough because..
	- ..it's a singular value, but (with EATT) different bearers have independent MTU.
	- ..the value can change mid-request if the remote initiates an MTU update (even if EATT is disabled).

**Describe the solution you'd like**
To make implementing the "Read Long Characteristic Values" procedure possible, the GATT read callbacks must convey the effective MTU. For example, the MTU could be a new field in the params struct. We must also ensure that the `bt_gatt_attr_read_func_t` parameter `len` is the effective MTU.

**Workaround**
Instead of performing the "Read Long Characteristic Values" procedure exactly, don't pay attention to the ATT MTU and instead continue the blob reads until an empty response is obtained. Hopefully the result is the same.

**Comment by kruithofa** [comment]
@Vudentz Do you have time to comment on this issue?
