### ISSUE TITLE
flash_stm32_qspi not working on W25Q02JV

### ISSUE THREAD

**Issue by hglassdyb** [zephyrproject-rtos/zephyr#55041]
**Describe the bug**

I'm trying to run the `zephyr/samples/drivers/flash_shell/` using the `flash_stm32_qspi` driver. I use a Nucleo F413ZH with a W25Q02JV.

The initialization fails with the following message (full log shown at the end):
```
flash_stm32_qspi: Unable to enter 4B mode: -22
```
As a result, it was not possible to read/write the flash.

Here is the overlay:

``` 
&quadspi {
    pinctrl-0 = <&quadspi_clk_pb2 &quadspi_bk1_ncs_pb6
                 &quadspi_bk1_io0_pd11 &quadspi_bk1_io1_pd12
                 &quadspi_bk1_io2_pe2 &quadspi_bk1_io3_pd13>;
    pinctrl-names = "default";
    status = "okay";
    w25q02Jv: qspi-nor-flash@0 {
        compatible = "st,stm32-qspi-nor";
        reg = <0>;
        qspi-max-frequency = <80000000>;
        size = <0x80000000>; // 256 MB
        writeoc = "PP_1_1_4";
        reset-gpios = <&gpiod 7 GPIO_ACTIVE_LOW>;
        reset-gpios-duration = <10>;
        spi-bus-width = <4>;
        status = "okay";
        label = "W25Q02JV";
    };
};
```

Here is the configuration file:

```
CONFIG_PRINTK=y
CONFIG_SHELL=y
CONFIG_LOG=y
CONFIG_LOG_MODE_IMMEDIATE=n
CONFIG_FLASH_LOG_LEVEL_DBG=y
CONFIG_LOG_BUFFER_SIZE=1024
CONFIG_LOG_DEFAULT_LEVEL=4
CONFIG_DEBUG=y
CONFIG_FLASH=y
CONFIG_FLASH_PAGE_LAYOUT=y
CONFIG_HEAP_MEM_POOL_SIZE=16384

CONFIG_FLASH_STM32_QSPI=y
```

**Workaround**

I found that `qspi_program_addr_4b` tries to enable the 4 bytes addressing mode, but it verifies the wrong bit.
It checks for the bit `SPI_NOR_4BYTE_BIT` which is defined as `BIT(5)` but according to the [W25Q02JV datasheet](https://download.mikroe.com/documents/datasheets/W25Q02JV%20Datasheet.pdf) it should be `BIT(0)`.

By replacing the value of `SPI_NOR_4BYTE_BIT` to `BIT(0)` I was able to read and write the flash.

**To Reproduce**
1. Use the DTS overlay and config provided above
2. `west build -p -b nucleo_f413zh zephyr/samples/drivers/flash_shell/`
3. `west flash`

**Expected behavior**
Being able to read / write the flash.

**Impact**
This would require a local patch of the driver to apply the workaround.

**Logs and console output**

```
*** Booting Zephyr OS build zephyr-v3.2.0-2-g8d0b726c3ef9  ***
Found flash controller flash-controller@40023c00.
Flash I/O commands can be run.
[00:00:00.010,000] <inf> flash_stm32_qspi: W25Q02JV: SFDP v 1.6 AP ff with 2 PH
[00:00:00.010,000] <inf> flash_stm32_qspi: PH0: ff00 rev 1.6: 16 DW @ 80
[00:00:00.010,000] <inf> flash_stm32_qspi: W25Q02JV: 256 MiBy flash
[00:00:00.010,000] <dbg> flash_stm32_qspi: spi_nor_process_bfp: Erase 4096 with 20
[00:00:00.010,000] <dbg> flash_stm32_qspi: spi_nor_process_bfp: Erase 32768 with 52
[00:00:00.010,000] <dbg> flash_stm32_qspi: spi_nor_process_bfp: Erase 65536 with d8
[00:00:00.010,000] <dbg> flash_stm32_qspi: spi_nor_process_bfp: Page size 256 bytes
[00:00:00.010,000] <dbg> flash_stm32_qspi: spi_nor_process_bfp: Flash size 268435456 bytes
[00:00:00.010,000] <dbg> flash_stm32_qspi: qspi_send_cmd: Instruction 0xb7
[00:00:00.010,000] <dbg> flash_stm32_qspi: qspi_send_cmd: CCR 0x1b7
[00:00:00.010,000] <err> flash_stm32_qspi: Unable to enter 4B mode: -22

[00:00:00.010,000] <err> flash_stm32_qspi: SFDP BFP failed: -22
[00:00:00.010,000] <dbg> flash_stm32_qspi: setup_pages_layout: layout page 256 not compatible with erase size 4096
[00:00:00.010,000] <dbg> flash_stm32_qspi: setup_pages_layout: erase size will be used as layout page size
[00:00:00.010,000] <dbg> flash_stm32_qspi: setup_pages_layout: layout 65536 x 4096 By pages

```

**Environment:**
 - OS: Arch Linux
 - Toolchain: Zephyr SDK 0.15.2
 - Version: v3.2.0

**Comment by FRASTM** [comment]
Do you mean that the drivers/flash/spi_nor.h should have 
diff --git a/drivers/flash/spi_nor.h b/drivers/flash/spi_nor.h
index fb9389bb85..de9c9ff20d 100644
--- a/drivers/flash/spi_nor.h
+++ b/drivers/flash/spi_nor.h
@@ -16,7 +16,7 @@
 #define SPI_NOR_WEL_BIT         BIT(1)  /* Write enable latch */
 
 /* Control register bits */
-#define SPI_NOR_4BYTE_BIT       BIT(5)  /* 4B addressing */
+#define SPI_NOR_4BYTE_BIT       BIT(0)  /* 4B addressing */
 
 /* Flash opcodes */
 #define SPI_NOR_CMD_WRSR        0x01 
to read the configuration register and parse according to the 


![configuration register](https://user-images.githubusercontent.com/51417392/220415327-fbbe81a6-9dca-40d5-871c-2eaa7ad52cf8.jpg)

**Comment by hglassdyb** [comment]
Yes exactly, in my case this solved the issue.

However it seems to be device/vendor specific because the logic is inverted in the Micron datasheet you showed.

Here is the Winbond datasheet for reference:

![image](https://user-images.githubusercontent.com/94455765/220554262-b54dd7e4-ed67-4f89-9442-dc05a656fc51.png)

**Comment by FRASTM** [comment]
In that case, this should be more reliable to get this info from the SDFP. That's probably what the flash_stm32_ospi does with spi_nor_process_bfp_addrbytes()
 
Do you have a result from the execution of the samples/drivers/jesd216/  on your target ?
for example : 
```
Summary of BFP content:
DTR Clocking not supported
Addressing: 3-Byte only
```

**Comment by FRASTM** [comment]
Changing to the 4-BYTE ADDRESS MODE with the (0xB7) command : _The effect of the command is immediate. The default address mode is three bytes, and the device returns to the default upon exiting the 4-byte address mode._
So I wonder if the checking back the configuration register is really required in the qspi_program_addr_4b(). Could you please check retrurning just after the  qspi_send_cmd :
```
diff --git a/drivers/flash/flash_stm32_qspi.c b/drivers/flash/flash_stm32_qspi.c
index 7cda68c8bf..2096c30b04 100644
--- a/drivers/flash/flash_stm32_qspi.c
+++ b/drivers/flash/flash_stm32_qspi.c
@@ -729,22 +729,14 @@ static int qspi_program_addr_4b(const struct device *dev)
 	};
 
 	ret = qspi_send_cmd(dev, &cmd);
-	if (ret) {
-		return ret;
-	}
 
 	/*
-	 * Read control register to verify if 4byte addressing mode
-	 * is enabled.
+	 * No need to Read control register to verify if 4byte addressing mode
+	 * is enabled as the effect of the command is immediate
+	 * and the SPI_NOR_CMD_RDCR is vendor-specific
+	 * SPI_NOR_4BYTE_BIT is BIT 5 for Macronix and 0 for Micron or Windbond
+	 * Moreover bit value meaning is also vendor specific
 	 */
-	cmd.Instruction = SPI_NOR_CMD_RDCR;
-	cmd.InstructionMode = QSPI_INSTRUCTION_1_LINE;
-	cmd.DataMode = QSPI_DATA_1_LINE;
-
-	ret = qspi_read_access(dev, &cmd, &reg, sizeof(reg));
-	if (!ret && !(reg & SPI_NOR_4BYTE_BIT)) {
-		return -EINVAL;
-	}
 
 	return ret;
 }
```

**Comment by hglassdyb** [comment]
Yeah, it's working:

```
[00:00:00.010,000] <dbg> flash_stm32_qspi: qspi_send_cmd: CCR 0x1b7
[00:00:00.010,000] <inf> flash_stm32_qspi: Flash - address mode: 4B
```
The return code of `qspi_send_cmd` is 0 with the W25Q02JV and I was able to read and write data in the flash.
