### ISSUE TITLE
up_squared: zbus: hello_world: sample output mangling fails regex verification

### ISSUE THREAD

**Issue by KamilxPaszkiet** [zephyrproject-rtos/zephyr#55071]
The hello_world test requires orderly console output to verify the proper operation of the program via RegEx. The bug mangles the output of two output lines in total, making RegEx not recognize the required lines and timing out the test.

part of the log:
```
DEBUG   - DEVICE: I: Sensor sample started raw reading, version 0.1-2!
DEBUG   - DEVICE: I: Channel list:
DEBUG   - DEVICE: I: 0 - Channel acc_data_chan:
DEBUG   - DEVICE: I:       Message size: 12    
DEBUG   - DEVICE: I:       Observers:
DEBUG   - DEVICE: I:       - foo_lis
DEBUG   - DEVICE: I:       - bar_sub
DEBUG   - DEVICE: I: 1 - Channel simple_chan:
DEBUG   - DEVICE: I:       Message size: 4   
DEBUG   - DEVICE: I:       Observers:        
DEBUG   - DEVICE: I: 2 - Channel version_chan:
DEBUG   - DEVICE: I:       Message size: 4
DEBUG   - DEVICE: I:       Observers:
DEBUG   - DEVICE: I: Observers list:
DEBUG   - DEVICE: I: 0 - Subscriber bar_sub
DEBUG   - DEVICE: I: 1 - Listener foo_lis
DEBUG   - DEVICE: I: From listener -> Acc x=1, y=1, z=1  
DEBUG   - DEVICE: I: From subscriber -> Acc x=1, y=1, z=1
DEBUG   - DEVICE: I: From listener -> Acc x=2, y=2, z=2
DEBUG   - DEVICE: II::  FPruobm  as uvbaslcirdi bvearl u-e>  tAoc ca  xc=h2a,n nye=l2 ,w izt=h2
DEBUG   - DEVICE: validator successfully.
DEBUG   - DEVICE: I: Pub an invalid value to a channel with validator successfully.
```
This line is corrupted:
```
DEBUG   - DEVICE: II::  FPruobm  as uvbaslcirdi bvearl u-e>  tAoc ca  xc=h2a,n nye=l2 ,w izt=h2
```
And it should looks like:
```
DEBUG   - DEVICE: I: Pub a valid value to a channel with validator successfully."
```

**To Reproduce**

1. Connect at least one UP Squared board to your controller and map it

1. Run the CHRE test
`<path/to>/zephyrproject/zephyr$ ./scripts/twister --device-testing --hardware-map <path/to>/<up2.map> -T samples/subsys/zbus/hello_world/ -vv`

1. The test should fail.

**Expected behavior**
The test should pass.

**Impact**
Currently, annoyance and lack of clear test output. However, name mangling while using RegEx to verify program operation can lead to further test failures and thus useless tests.

**Logs and console output**
```DEBUG   - DEVICE: >>Checking Media Presence......
DEBUG   - DEVICE: >>Media Present......
DEBUG   - DEVICE: Downloading NBP file...
DEBUG   - DEVICE: 
DEBUG   - DEVICE: Succeed to download NBP file.
DEBUG   - DEVICE: *** Zephyr EFI Loader ***
DEBUG   - DEVICE: RSDP found at 0x79c34000
DEBUG   - DEVICE: Zeroing 4824560 bytes of memory at 0x108000
DEBUG   - DEVICE: Copying 32768 data bytes to 0x1000 from image offset
DEBUG   - DEVICE: Copying 32768 data bytes to 0x100000 from image offset 32768  
DEBUG   - DEVICE: Copying 2110184 data bytes to 0x5a1e00 from image offset 65536
DEBUG   - DEVICE: Jumping to Entry Point: 0x1137 (48 31 c0 48 31 d2 48)
DEBUG   - DEVICE: I: Sensor sample started raw reading, version 0.1-2!
DEBUG   - DEVICE: I: Channel list:
DEBUG   - DEVICE: I: 0 - Channel acc_data_chan:
DEBUG   - DEVICE: I:       Message size: 12    
DEBUG   - DEVICE: I:       Observers:
DEBUG   - DEVICE: I:       - foo_lis
DEBUG   - DEVICE: I:       - bar_sub
DEBUG   - DEVICE: I: 1 - Channel simple_chan:
DEBUG   - DEVICE: I:       Message size: 4   
DEBUG   - DEVICE: I:       Observers:        
DEBUG   - DEVICE: I: 2 - Channel version_chan:
DEBUG   - DEVICE: I:       Message size: 4
DEBUG   - DEVICE: I:       Observers:
DEBUG   - DEVICE: I: Observers list:
DEBUG   - DEVICE: I: 0 - Subscriber bar_sub
DEBUG   - DEVICE: I: 1 - Listener foo_lis
DEBUG   - DEVICE: I: From listener -> Acc x=1, y=1, z=1  
DEBUG   - DEVICE: I: From subscriber -> Acc x=1, y=1, z=1
DEBUG   - DEVICE: I: From listener -> Acc x=2, y=2, z=2
DEBUG   - DEVICE: II::  FPruobm  as uvbaslcirdi bvearl u-e>  tAoc ca  xc=h2a,n nye=l2 ,w izt=h2
DEBUG   - DEVICE: validator successfully.
DEBUG   - DEVICE: I: Pub an invalid value to a channel with validator successfully.
DEBUG   - Timed out while monitoring serial output on up_squared
DEBUG   - run status: up_squared/samples/subsys/zbus/hello_world/sample.zbus.hello_world error
INFO    - 2/2 up_squared                samples/subsys/zbus/hello_world/sample.zbus.hello_world  ERROR No Console Output(Timeout) (device 63.291s)
```

**Environment:**
- OS: Ubuntu for the controller
- Toolchain: Zephyr SDK 15.0
- The current Zephyr version used

**Additional context**
Multiline RegEx used in the test in question:
```
regex:
        - "I: Sensor sample started raw reading, version 0.1-2!"
        - "I: Channel list:"
        - "I: 0 - Channel acc_data_chan:"
        - "I:       Message size: 12"
        - "I:       Observers:"
        - "I:       - foo_lis"
        - "I:       - bar_sub"
        - "I: 1 - Channel simple_chan:"
        - "I: 2 - Channel version_chan:"
        - "I:       Message size: 4"
        - "I: Observers list:"
        - "I: 0 - Subscriber bar_sub"
        - "I: 1 - Listener foo_lis"
        - "I: From subscriber -> Acc x=1, y=1, z=1"
        - "I: From listener -> Acc x=1, y=1, z=1"
        - "I: From subscriber -> Acc x=2, y=2, z=2"
        - "I: From listener -> Acc x=2, y=2, z=2"
        - "I: Pub a valid value to a channel with validator successfully."
        - "I: Pub an invalid value to a channel with validator successfully."
```
The problem is similar to this issue:
[https://github.com/zephyrproject-rtos/zephyr/issues/54861](54861)
[https://github.com/zephyrproject-rtos/zephyr/issues/55076](55076)

**Comment by nashif** [comment]
The template text needs to be changed to something useful. Please change the content in each section with details.

**Comment by KamilxPaszkiet** [comment]
@nashif > The template text needs to be changed to something useful. Please change the content in each section with details.
Sorry, I was in the middle of typing when I accidentally posted an issue

**Comment by gbarkadiusz** [comment]
According to my investigation, this test passed after changing CONFIG_SMP parameter in
`<paht/to>/zephyr/boards/x86/up_squared/up_squared_defconfig`
from `CONFIG_SMP=y` to `CONFIG_SMP=n`.
Moreover, test `<path/to>/tests/kernel/smp` has a parameter `platform_allow: qemu_x86_64`. This can mean, that the up2 board doesn't support smp.

**Comment by teburd** [comment]
This is likely a shared stack variable going across cores where the cache coherence isn't kept. Just a guess though.

**Comment by SzymonRichert** [comment]
Any update ?

**Comment by rodrigopex** [comment]
> Any update ?

@SzymonRichert 

Does the up2 board support SMP? Because based on the  @gbarkadiusz comment, the test passed when SMP was disabled.

**Comment by nashif** [comment]
@rodrigopex  yes, this board supports SMP.

**Comment by teburd** [comment]
This might be more related to how logging works and on SMP its possible to get mangled logs if the log backend doesn't deal with concurrency in a log immediate mode. Or similarly with SMP and printk. There's a Kconfig option to serialize printk calls I believe. Or route printk through logging.

In the end this looks like a race on the output stream where the messages are not being serialized properly in some way. That seems to be likely the case for #54861 as well.

**Comment by KamilxPaszkiet** [comment]
The isssue still exists

**Comment by rodrigopex** [comment]
@KamilxPaszkiet, Would you happen to have a solution idea? I could not figure out a way to solve that. Changing the regex to fit the case is not the way to go. The SMP support for the architecture is out of ZBus's scope. I cannot even run the code. There is no simulator for that.

**Comment by KamilxPaszkiet** [comment]
@nashif maybe you can help?

**Comment by jhedberg** [comment]
@rodrigopex I have the board and can reproduce the issue. I don't have a concrete fix proposal however.

Do I understand correctly that the issue is multiple CPU cores trying to produce output to the console at the same time? In that case this doesn't sound board-specific, rather SMP specific. Most likely the logging subsystem (and printk implementation) should somehow create critical regions over each high-level logging call, so that while the call is entered (typically mapping to one line of output) no other place in the tree can also try to output something at the same time.

As far as I can see, this is at least not an issue with the UART driver - the interface between UART console and the UART driver, or `log_backend_uart.c` and the UART driver, is on a per-character basis, so the (seemingly) missing locking would need to be done in some layer above the UART driver. @nordic-krch any thoughts here?

**Comment by rodrigopex** [comment]
@jhedberg, I see. Based on that, we can say that it is not a zbus issue, right? I imagine it is a more general "big" issue related to SMP and log/print.

**Comment by jhedberg** [comment]
> @jhedberg, I see. Based on that, we can say that it is not a zbus issue, right? I imagine it is a more general "big" issue related to SMP and log/print.

Yes, that's what it looks like to me. Would be good to get some comment from the logging subsystem maintainer.

**Comment by jhedberg** [comment]
Btw, looks like there are other bug reports as well with the same likely root cause: #54861

**Comment by nordic-krch** [comment]
When minimal logging is used, then any log is converted to printk which polls out characters one by one so it can be interrupted by any other thread and output can be interleaved. There are two options: change to use deferred mode (`CONFIG_LOG_MODE_DEFERRED=y`) or use immediate mode with clean output (interrupts are locked for each message processing): `CONFIG_LOG_MODE_IMMEDIATE=y` `CONFIG_LOG_IMMEDIATE_CLEAN_OUTPUT=y`

**Comment by jhedberg** [comment]
@nordic-krch thanks. I can confirm that with the following patch (which causes deferred mode to be used) the output is normal again:
```patch
--- a/samples/subsys/zbus/hello_world/prj.conf
+++ b/samples/subsys/zbus/hello_world/prj.conf
@@ -1,5 +1,4 @@
 CONFIG_LOG=y
-CONFIG_LOG_MODE_MINIMAL=y
 CONFIG_BOOT_BANNER=n
 CONFIG_MAIN_THREAD_PRIORITY=5
 CONFIG_ZBUS=y
```

**Comment by jhedberg** [comment]
@KamilxPaszkiet in the future when you have these "output fails regex verification", as the first thing please check what log mode is used. It seems both this issue as well as #54861 are both caused by the samples setting `CONFIG_LOG_MODE_MINIMAL=y`. I just confirmed that the output is normal (not garbled) if I remove the setting and let the default (`LOG_MODE_DEFERRED`) be used instead. Same goes for `LOG_MODE_IMMEDIATE` - it's expected that the output is garbled if that's not combined with `LOG_IMMEDIATE_CLEAN_OUTPUT`.

Now, I'm wondering what's the right course of action here: do we want to forbid any application from using `LOG_MODE_MINIMAL`? It has its uses, so that seems a bit harsh. Maybe you should simply filter out any tests from your test matrix that enable `LOG_MODE_MINIMAL` (or `LOG_MODE_IMMEDIATE` without `LOG_IMMEDIATE_CLEAN_OUTPUT`).

Either way, neither of these two issues is specific to `up_squared`, rather they could happen on any SMP platform.

**Comment by jhedberg** [comment]
@nordic-krch would it perhaps make sense to add `depends on !SMP` to `LOG_MODE_MINIMAL`?

**Comment by jhedberg** [comment]
> @nordic-krch would it perhaps make sense to add `depends on !SMP` to `LOG_MODE_MINIMAL`?

Hmm, I took a look at the implementation, and it seems it's just mapping to printk(). And actually even if it wasn't possible to enable it for SMP systems there's still any direct printk() calls themselves that apps might do. I wonder if it'd then make sense to consider adding (behind a new Kconfig option) some locking to printk itself, to prevent garbled output.

**Comment by nordic-krch** [comment]
Strange but there is already `PRINTK_SYNC` (https://github.com/zephyrproject-rtos/zephyr/blob/ecb2df0444f10bd21dbdd1220cbe353655cab5cc/lib/os/Kconfig#L37)  default to `y` for SMP but not when log is used.

`default y if SMP && MP_MAX_NUM_CPUS > 1 && !(EFI_CONSOLE && LOG) `

**Comment by jhedberg** [comment]
@nordic-krch that seems to come from commit e696de1f316e85dc2209f7ff5e6a6518e54eb9ed

I'm not so sure it's a valid change though, since typically what you get on x86 systems is that EFI console is used during early boot and the overridden by UART console later, so there locking will still be needed.

**Comment by jhedberg** [comment]
@enjiamai any comments on the above?

**Comment by jhedberg** [comment]
After reading https://github.com/zephyrproject-rtos/zephyr/issues/45929#issuecomment-1141159022 it sounds like maybe we should remove `default y` from `X86_EFI_CONSOLE`:
https://github.com/zephyrproject-rtos/zephyr/blob/f89c5ddd1aaf0e4a5b6fd0a1397c5a72f1cba388/arch/x86/Kconfig#L471-L475

@andyross @dcpleung @tbursztyka @finikorg FYI

**Comment by jhedberg** [comment]
Created a fix proposal: https://github.com/zephyrproject-rtos/zephyr/pull/65739
