### ISSUE TITLE
Any command or macro  to get board name in CMakefileList.txt, need to compare boards to execute specifi board

### ISSUE THREAD

**Issue by Niranjan-eaton** [zephyrproject-rtos/zephyr#55098]
**Describe the bug**
Require information/data how to get current execution board name in CMakelist.txt. 

Please provide command or macro related.
 - ...

**Expected behavior**
Need to get board name in cmakelistfile.txt

**Impact**
What impact does this issue have on your progress (e.g., annoyance, showstopper)

**Environment (please complete the following information):**
 - OS: Zephyr 3.2.0
 - Toolchain sdk 15.2

**Comment by carlescufi** [comment]
Use `CONFIG_BOARD` which is available in CMake.
