### ISSUE TITLE
mec : test_jitter_drift failing

### ISSUE THREAD

**Issue by pkunieck** [zephyrproject-rtos/zephyr#55136]
**Describe the bug**
Test jitter_drift from tests/kernel/timer/timer_behavior/kernel.timer.timer is failing on mec172 and mec15 platforms, there are logs from console: 

mec172xevb_assy6906       tests/kernel/timer/timer_behavior/kernel.timer.timer  FAILED Failed
mec15xxevb_assy6853       tests/kernel/timer/timer_behavior/kernel.timer.timer  FAILED : Failed

START - test_jitter_drift
periodic timer behavior test (approx 7 seconds)
periodic timer samples gathered, calculating statistics
timer clock rate 32768, kernel tick rate 32768
Assertion failed at WEST_TOPDIR/zephyr/tests/kernel/timer/timer_behavior/src/jitter_drift.c:177: timer_jitter_drift_test_jitter_drift: expected_period_drift == 0.0 is false
FAIL - test_jitter_drift in 7.118 seconds

Fails occurred after changing the output from this test in this commit: a115fd21d4 . 

**To Reproduce**
Run command on newest commit (mec17 for example):
twister -p mec172xevb_assy6906 --device-testing --device-serial /dev/ttyUSB0 -T tests/kernel/timer/timer_behavior/ -vv

**Expected behavior**
Passing tests

**Impact**
annoyance

**Logs and console output**
See above.

**Environment (please complete the following information):**
OS: Linux
Toolchain Zephyr SDK

**Comment by teburd** [comment]
@npitre this seems tied to the new assertions you added to the test, can you take a look?
