### ISSUE TITLE
Drivers: Sensor: Store `struct sensor_trigger` as a const pointer for CONTAINER_OF usage.

### ISSUE THREAD

**Issue by anthony32086** [zephyrproject-rtos/zephyr#55130]
**Is your enhancement proposal related to a problem? Please describe.**
Currently the `const struct sensor_trigger *` passed to all sensor drivers with the `sensor_trigger_set_t` are de-referenced and saved as a copy instead of the const pointer, [ex: adxl372](https://github.com/zephyrproject-rtos/zephyr/blob/main/drivers/sensor/adxl372/adxl372_trigger.c#L114). Then when an event occurs either the pointer to the [dev_data copy of sensor_trigger](https://github.com/zephyrproject-rtos/zephyr/blob/main/drivers/sensor/adxl372/adxl372_trigger.c#L47) is passed or a [local stack copy](https://github.com/zephyrproject-rtos/zephyr/blob/main/drivers/sensor/bmi160/bmi160_trigger.c#L20) is made.

**Describe the solution you'd like**
Instead of making a copy of the user provided `const struct sensor_trigger *` change all drivers to save the const pointer directly and pass it to the `sensor_trigger_handler_t` function when an event occurs.
This allows the usage of **CONTAINER_OF** by the callee to retrieve a context pointer if they choose to embedded the sensor_trigger in a higher struct.

**Describe alternatives you've considered**
No change and instead users continue to use global variables for callback access to user data.

**Comment by henrikbrixandersen** [comment]
I agree. I would consider the existing behavior of allocating the struct on the stack before passing it to the callback a bug. I reckon we need to clarify the sensors API to reflect this.

@MaureenHelm Opinions?

**Comment by MaureenHelm** [comment]
> I agree. I would consider the existing behavior of allocating the struct on the stack before passing it to the callback a bug. I reckon we need to clarify the sensors API to reflect this.
> 
> @MaureenHelm Opinions?

Yes, I agree on both points.
