### ISSUE TITLE
[Coverity CID: 181848] Null pointer dereferences in /subsys/bluetooth/host/mesh/access.c

### ISSUE THREAD

**Issue by Shilpashree3lc** [zephyrproject-rtos/zephyr#5530]
Static code scan issues seen in File: /subsys/bluetooth/host/mesh/access.c
 Category: Null pointer dereferences
 Function: publish_retransmit
 Component: Bluetooth
 CID: 181848
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by jhedberg** [comment]
classified as intentional in coverity
