### ISSUE TITLE
samples: bluetooth: Bluetooth Mesh sample has 55-byte RAM overflow on BBC micro:bit

### ISSUE THREAD

**Issue by kartben** [zephyrproject-rtos/zephyr#55328]
**Describe the bug**

* Follow the instructions at https://docs.zephyrproject.org/3.1.0/samples/bluetooth/mesh_demo/README.html to build Bluetooth Mesh sample for micro:bit 
* Build fails during the linking phase due to RAM overflow:
```
/Users/kartben/zephyr-sdk-0.15.2/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/12.1.0/../../../../arm-zephyr-eabi/bin/ld.bfd: region `RAM' overflowed by 55 bytes
```

**To Reproduce**

See above

**Expected behavior**

Compilation should work and user should be able to flash their micro:bit

**Impact**

This sample claims to be "specially" designed for the micro:bit, so it'd be great if it'd work out-of-the-box!

**Environment (please complete the following information):**

macOS, SDK 0.15.2
Zephyr 6a5a2534a0556b04be83f6149cb4bd8e4f66d77f

**Comment by carlescufi** [comment]
> > This sample claims to be "specially" designed for the micro:bit, so it'd be great if it'd work out-of-the-box!
> 
> If that is the case, the sample should have this board as one of the integration platforms such that a RAM overflow on that platform is treated as a hard error rather than skip.

Will add that now.
