### ISSUE TITLE
flash_mcux_flexspi_nor: incorrect enabling quad mode

### ISSUE THREAD

**Issue by GrixaYrev** [zephyrproject-rtos/zephyr#55379]
**Describe the bug**
For enable quad mode `flash_mcux_flexspi_nor` driver [send](https://github.com/zephyrproject-rtos/zephyr/blob/69966dd452e5ebf9f057b393b1e5cdac9ea2034b/drivers/flash/flash_mcux_flexspi_nor.c#L340) value `0x40` to status register 1. It is valid value for **IS25WP064**, which is used in `mimxrt1064_evk` board, but for [Winbond **W25Q128JV**](https://www.winbond.com/hq/product/code-storage-flash-memory/serial-nor-flash/?__locale=en&partNo=W25Q128JV) need set bit 2 in status register 2.

**Expected behavior**
Driver should select way to enable quad mode accordance vendor id. List of ways (vendors) should be extensible.

------

Later i will try to propose PR with fix. Please, give me comments.

**Comment by fabiobaltieri** [comment]
Hi! Thanks for reporting the issue, can you send the PR and then we can comment and review on it?

**Comment by henrikbrixandersen** [comment]
Please use our bug template when reporting bugs. You need to edit this issue to include the needed information from https://github.com/zephyrproject-rtos/zephyr/blob/main/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by mbrunnen** [comment]
Would be a dedicated driver for `nxp,imx-flexspi-w25q128jv` acceptable?

**Comment by GrixaYrev** [comment]
@mbrunnen, i think it is redundant and violates principle DRY.
