### ISSUE TITLE
External Source Code: Integrate Coremark as a module

### ISSUE THREAD

**Issue by carlescufi** [zephyrproject-rtos/zephyr#55460]
## Origin

Coremark, by the Embedded Microprocessor Benchmark Consortium:
https://github.com/eembc/coremark

## Purpose

Coremark is an industry standard for CPU benchmarking.

## Mode of integration

Would be integrated as a module, upstream already contains the `zephyr/` folder so I just suggest forking [the coremark repo](https://github.com/eembc/coremark) into the Zephyr GH org.

## Maintainership

@volodymyr-bondarchuk
@carlescufi 

## Pull Request

https://github.com/zephyrproject-rtos/zephyr/pull/55461

## Description

The Coremark library is very useful to those wanted to evaluate the performance and energy efficiency of a particular SoC. It allows users to compare different silicon vendors using the same standardized benchmark.

Goals: Benchmarking of MCUs without the hassle of porting the benchmarking software, using Zephyr's portability.

Coremark is the industry standard, it's maintained by a non-profit consortium and is small in code size and complexity.

## Dependencies

None

## Revision

[d5fad6bd094899101a4e5fd53af7298160ced6ab](https://github.com/eembc/coremark/commit/d5fad6bd094899101a4e5fd53af7298160ced6ab)

## License

There is an [Acceptable User Agreement](https://github.com/eembc/coremark/blob/main/LICENSE.md), that covers the Coremark trademark, but it clearly states that "Licensor offers benchmarking software (“Software”) pursuant to an open source license".
All source  code is provided under the Apache v2 license.
```
Apache-2.0
```

**Comment by volodymyr-bondarchuk** [comment]
PR #55461 with Coremark bring up created.

**Comment by ruuddw** [comment]
> Similar attempt, but as a standalone application: https://github.com/claziss/coremark-pro-zephyr/tree/main

Note that that's for a subset of CoreMark-PRO, that's not the same as the base CoreMark.

**Comment by galak** [comment]
I don't think this belongs in Zephyr.  Coremark glue code for Zephyr we should try and upstream to Coremark.  As Coremark is primarily benchmarking the CPU hardware and not RTOS I don't think Zephyr should be including.

**Comment by carlescufi** [comment]
Removed the TSC label until we decide how to proceed with this internally at Nordic.
