### ISSUE TITLE
boards: mpfs_icicle: Runtime fault in samples/philosophers due to CONFIG_NO_OPTIMIZATIONS=y

### ISSUE THREAD

**Issue by mars-low** [zephyrproject-rtos/zephyr#55466]
**Describe the bug**
The philosophers sample on `mpfs_icicle` board works for several seconds and then hangs with no particular error printed to the console.

Attaching GDB shows that fatal error was dropped by the kernel and system was halted:
```
(gdb) bt
#0  0x000000008000600a in arch_system_halt (reason=0)
    at /home/ant/zephyrproject/zephyr/kernel/fatal.c:32
#1  0x0000000080006028 in k_sys_fatal_error_handler (reason=0, 
    esf=0x80011550 <stacks+7696>)
    at /home/ant/zephyrproject/zephyr/kernel/fatal.c:46
#2  0x000000008000607a in z_fatal_error (reason=0, 
    esf=0x80011550 <stacks+7696>)
    at /home/ant/zephyrproject/zephyr/kernel/fatal.c:131
#3  0x0000000080003c50 in z_riscv_fatal_error (reason=0, 
    esf=0x80011550 <stacks+7696>)
    at /home/ant/zephyrproject/zephyr/arch/riscv/core/fatal.c:58
#4  0x0000000080003cb8 in _Fault (esf=0x80011550 <stacks+7696>)
    at /home/ant/zephyrproject/zephyr/arch/riscv/core/fatal.c:183
#5  0x0000000080000110 in z_riscv_thread_start ()
    at /home/ant/zephyrproject/zephyr/arch/riscv/core/isr.S:588
Backtrace stopped: frame did not save the PC
```

Removing `CONFIG_NO_OPTIMIZATIONS=y` from [mpfs_icicle_defconfig](https://github.com/zephyrproject-rtos/zephyr/blob/main/boards/riscv/mpfs_icicle/mpfs_icicle_defconfig#L10) makes it work. Otherwise it seems that stack is overflowed due to disabled optimizations.

It seems that per thread stack size is too small and it could be increased directly in philosophers sample code: https://github.com/zephyrproject-rtos/zephyr/blob/0e70b36c9f7cd94eb546d6ecbdf73fde1120b9f8/samples/philosophers/src/main.c#L86 
Increasing `STACK_SIZE` to e.g. `2560` seems to prevent fault even with `CONFIG_NO_OPTIMIZATIONS=y`, which is default for this board.

**To Reproduce**
1. Build and run the philosophers sample on the mpfs\_icicle board with CONFIG\_NO\_OPTIMIZATIONS=y
```
west build -p always -b mpfs_icicle samples/philosophers/
```
2. Connect the board and your workstation via USB. Turn on the board using the power button.
3.  Run the OpenOCD server (replace `<softconsole_path>` with a proper path for softconsole installation):
```
sudo LD_LIBRARY_PATH=<softconsole_path>/openocd/bin\
<softconsole_path>/openocd/bin/openocd\
-c "set DEVICE MPFS"\
--file <softconsole_path>/openocd/share/openocd/scripts/board/microsemi-riscv.cfg
```
4. Load the binary using gdb (replace the `<softconsole_path>` and `<binary_path>`:
```
sudo <softconsole_path>/riscv-unknown-elf-gcc/bin/riscv64-unknown-elf-gdb \ 
-ex "target extended-remote localhost:3333" \
-ex "set mem inaccessible-by-default off" \
-ex "set arch riscv:rv64" \
-ex "set riscv use_compressed_breakpoints no" \
-ex "load" <binary_path>
```
5. Run the picocom on corresponding ttyUSB in order to track the output from Zephyr:
```
sudo picocom /dev/ttyUSBX -b 115200
```
6. Start binary execution and observe the output. It hangs after several seconds.

**Expected behavior**
Philosophers sample should run indefinitely without fault.

**Impact**
Automated test for this sample and board fails on https://zephyr-dashboard.renode.io/. It is also not possible to run this sample on the hardware in the default configuration. Workarounds exist that allow to run the sample:
1. Disable `CONFIG_NO_OPTIMIZATIONS=y` in the board configuration
2. Increase thread stack size in philosophers sample code

Perhaps first workaround could be a fix for this problem, but I understand it depends on both board and sample configuration. Config for philosophers sample that allows to override `STACK_SIZE` from command line also could be useful. 

**Logs and console output**
I attached screencast which shows that it hangs after a few seconds: 
[mpfs_icicle_philosophers_fault.webm](https://user-images.githubusercontent.com/53299913/223107729-1d722169-5cd3-423f-af14-9e200f6db1da.webm)

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: Zephyr SDK 0.15.0
 - Commit SHA: 0e70b36c9f7cd94eb546d6ecbdf73fde1120b9f8

**Comment by fkokosinski** [comment]
FYI @con-pax
