### ISSUE TITLE
Exiting Deep Power Down on a p25q16h flash chip is not working with QSPI

### ISSUE THREAD

**Issue by oryjkov** [zephyrproject-rtos/zephyr#55543]
**Describe the bug**
I am not able to exit DPD on a p25q16h flash chip (which is used on Seeed Xiao BLE nrf52840) when using the NRF QSPI driver.

Exiting DPD works fine on the same hardware when the NRF SPI driver is used.

I suspect that the QSPI driver is attempting to read a status register of the flash chip when the latter is in DPD mode. The flash chip is not responding, so the MCU gives up on it and never gets to send the RDPD (release deep sleep) command.

I have more detains in https://github.com/zephyrproject-rtos/zephyr/pull/55199#issuecomment-1455195564

**To Reproduce**
1. Patch in the QSPI pull request https://github.com/zephyrproject-rtos/zephyr/pull/55199
2. Enter System OFF and wake up (or just put the flash chip in DPD) and try to use flash.

**Expected behavior**
It should be possible to exit deep sleep with the QSPI peripheral.

**Impact**
Unable to use QSPI, have to use SPI mode instead.

**Logs and console output**

**Environment (please complete the following information):**
Using the nrf sdk v2.3.0

**Additional context**
Flash datasheet: https://datasheet.lcsc.com/lcsc/2006021534_PUYA--P25Q16H-SUH-IR_C559219.pdf
Seeed ble schematic: https://files.seeedstudio.com/wiki/XIAO-BLE/Seeed-Studio-XIAO-nRF52840-Sense-v1.1.pdf

**Comment by oryjkov** [comment]
Yes, same happens with a zephyr workspace (head at d61dcf2f1d)

**Comment by carlescufi** [comment]
This is indeed an issue and requires changes both in the Zephyr shim and the nrfx qspi driver. @anangl will propose a solution in the near future.
