### ISSUE TITLE
Support for mode and state changes in AICS API

### ISSUE THREAD

**Issue by sjanc** [zephyrproject-rtos/zephyr#55552]
**Describe the bug**
there are some tests (mandatory...) in AICS that require runtime changes in eg. gain mode or mutable but currently implementation doesn't allow to change what was registered on init

This is affecting some of mandatory qualification test cases.

**Expected behavior**
Provide API that will allow to properly implement Upper Tester interface.

This is currently affecting following qualification test cases:
AICS/SR/SGGIT/CP/BI-03-C
AICS/SR/SGGIT/CP/BI-04-C

**Comment by Thalley** [comment]
Modified to enchancement as this is intended behavior, and what this is asking for is an improvement for the existing API
