### ISSUE TITLE
it8xxx2_evb : tests/kernel/sleep failing

### ISSUE THREAD

**Issue by pkunieck** [zephyrproject-rtos/zephyr#55563]
**Describe the bug**
Test: test_usleep from tests/kernel/sleep/ is failing, and this is output from console:

```
START - test_usleep
elapsed_ms = 2347
Assertion failed at WEST_TOPDIR/zephyr/tests/kernel/sleep/src/usleep.c:95: sleep_test_usleep: (elapsed_ms <= UPPER_BOUND_MS is false)
overslept
FAIL - test_usleep in 23.478 seconds
```

At this moment we have 100% repro rate in daily validation. 

**To Reproduce**
Run command on newest commit:
twister -p it8xxx2_evb --device-testing -T tests/kernel/sleep/ --west-flash=/home/ztest/itetool/loader.sh --device-serial=/dev/ttyUSB0 --fixture=gpio_loopback

**Expected behavior**
Passing tests

**Impact**
annoyance

**Logs and console output**
See above.

**Environment:**
 - OS: Linux
 - Toolchain Zephyr SDK

**Comment by Dino-Li** [comment]
@GTLin08 Tim, can you help to look into this issue?
