### ISSUE TITLE
Cloning Zephyr with git's core.autocrlf=true leads to obscure errors

### ISSUE THREAD

**Issue by SebastianBoe** [zephyrproject-rtos/zephyr#5557]
Windows users are likely to have a pre-configured git client that will clone Zephyr with "core.autocrlf true". This causes LF to be converted to CRLF and will break Kconfig in an obscure way.

Not sure what the best fix is here.

# Possible solutions

- Document that git must be cloned with "core.autocrlf false".
- Detect that files have the wrong line endings and give a sane error message.
- Support both types of line endings.

Option 3 is obviously the best for the user, but perhaps this is non-trivial and we should combine it with the two first options as well.

**Comment by carlescufi** [comment]
This should not happen anymore once we transition to a Python version of Kconfig.
