### ISSUE TITLE
Bluetooth examples not run on esp32c3 based boards.

### ISSUE THREAD

**Issue by trembel** [zephyrproject-rtos/zephyr#55653]
### Discussed in https://github.com/zephyrproject-rtos/zephyr/discussions/54131

<div type='discussions-op-text'>

<sup>Originally posted by **icatorze** January 26, 2023</sup>
No one bluetooth examples run on esp32c3. Application hangs on line: register_chipv7_phy(init_data, cal_data, PHY_RF_CAL_FULL); of this phy_init.c file.

Other examples like blinky and applications that use I2C run normally. 

Are there limitations to run bluetooth apps over esp32c3?</div>

**Comment by stephanosio** [comment]
Please do not create issues from a Q&A discussion.

**Comment by twilfredo** [comment]
> ### Discussed in #54131
> 
> Originally posted by **icatorze** January 26, 2023 No one bluetooth examples run on esp32c3. Application hangs on line: register_chipv7_phy(init_data, cal_data, PHY_RF_CAL_FULL); of this phy_init.c file.
> 
> Other examples like blinky and applications that use I2C run normally.
> 
> Are there limitations to run bluetooth apps over esp32c3?

I think there's is a regression, the bluetooth samples worked when I tested on v3.1.0
