### ISSUE TITLE
Bluetooth TX Power setting on the nucleo_wb55rg board.

### ISSUE THREAD

**Issue by 2songh** [zephyrproject-rtos/zephyr#55662]
**Is your feature request related to a problem? Please describe.**
When requesting pairing, priority is low.
When distance increases, the connection is lost.
I think Bluetooth TX power is weak.

**Environment**
Board: nucleo_wb55rg
OS: Linux ubuntu 18.04
Versioin: Zephyr 2.4.0

**Describe the solution you'd like**
I want to increase TX power through setting.

I think the default value is 0dBm.
I want to raise this value more than 6dBm.
Can I change and define this value?

**Reference**
I think a change is needed in this part.
 * zephyr/drivers/bluetooth/hci/ipm_stm32wb.c

The current TX level is the default value.
I want to increase the TX level by modifying the param values.

![image](https://user-images.githubusercontent.com/126455296/224247112-92d4f8ea-980c-4ea3-85de-1985f97ca940.png)

**Comment by carlescufi** [comment]
@2songh you know you can send arbitrary HCI commands from your application?
`bt_hci_cmd_send_sync()` is a public API

**Comment by 2songh** [comment]
I already know that.

![image](https://user-images.githubusercontent.com/126455296/224589050-67ae8b7c-5263-4763-8d94-c1e7dc044445.png)
First test, I only changed the param->cmd, param->value[0], param->value[1].
TX Power did not change.

Second test, I found information related to CONFIG.
And I added CONFIG.
CONFIG_BT_CTLR_TX_PWR_DYNAMIC_CONTROL=y
CONFIG_BT_HCI_VS_EXT=y

So I want to know which value to change to increase the TX Power.

ex) param->value[0]
      0x18 -> 0x1F
