### ISSUE TITLE
Contributor Nomination: semihalf-niedzwiecki-dawid

### ISSUE THREAD

**Issue by semihalf-niedzwiecki-dawid** [zephyrproject-rtos/zephyr#55691]
# Background

The [TSC Project Roles] defines the main roles for the Zephyr Project, including
Maintainer, Collaborator, and Contributor.

By default anyone that contributes code or documentation is a Contributor, but
with the lowest [GitHub Permission Level] of Read. For example, Contributors
with Read permission do not have the permission to add reviewers to a pull
request.

Use this template to nominate a GitHub user for the Contributor role with
Triage permission level, which allows the user to add reviewers to a pull
request and be added as a reviewer by other users.

# Nomination

## GitHub User

Provide the following information about the GitHub user:

1. Dawid Niedzwiecki
1. semihalf-niedzwiecki-dawid
1. Semihalf

## Supporting Documents

Add links to 3-5 GitHub pull requests, in the Zephyr project, authored or
reviewed by the GitHub user that demonstrate the user's dedication to the
Zephyr project.

https://github.com/zephyrproject-rtos/zephyr/pull/54132
https://github.com/zephyrproject-rtos/zephyr/pull/53432
https://github.com/zephyrproject-rtos/zephyr/pull/51741
https://github.com/zephyrproject-rtos/zephyr/pull/42846

[TSC Project Roles]: <https://docs.zephyrproject.org/latest/project/project_roles.html>
[GitHub Permission Level]: <https://docs.github.com/en/organizations/managing-access-to-your-organizations-repositories/repository-roles-for-an-organization>

**Comment by stephanosio** [comment]
@semihalf-niedzwiecki-dawid has been added as a user with Triage permission.
