### ISSUE TITLE
None of the :github:'XYZ' links work in the 1.10 release notes

### ISSUE THREAD

**Issue by linkmeyer** [zephyrproject-rtos/zephyr#5576]
None of the :github:'XYZ' links work in the 1.10 release notes found at https://github.com/zephyrproject-rtos/zephyr/blob/master/doc/release-notes-1.10.rst

**Comment by dbkinder** [comment]
That's because you need to click on the generated HTML links here (and not on the .rst files): http://docs.zephyrproject.org/release-notes-1.10.html
