### ISSUE TITLE
Address untested options in kernel

### ISSUE THREAD

**Issue by nashif** [zephyrproject-rtos/zephyr#5579]
Following options in the kernel are either not being tested or executed at all or test is not complete:

- [x] **CONFIG_ERRNO**: Test exists, but no use of function declared in kernel/errno.c
- [x] [#5254] CONFIG_KERNEL_EVENT_LOGGER
- [x] CONFIG_INT_LATENCY_BENCHMARK

**Comment by pfalcon** [comment]
Can there be some textual content in tickets instead of them being kinda cryptic?

Because literal taking of:

> [ ] CONFIG_ERRNO

shows that assumption of "Untested" is incorrect: https://github.com/zephyrproject-rtos/zephyr/tree/master/tests/kernel/errno

**Comment by nashif** [comment]
be patient, I am just collecting the data right now and using this as a place holder

re errno: while CONFIG_ERRNO is enabled in the mentioned list, errno.c in kernel/ is not being tested at all.

**Comment by pfalcon** [comment]
Ah, so this is about coverage after all...

**Comment by nashif** [comment]
all listed items fixed
