### ISSUE TITLE
Test GPIO driver does not provide config and data

### ISSUE THREAD

**Issue by benediktibk** [zephyrproject-rtos/zephyr#55884]
As far as I understood all GPIO drivers are supposed to provide a data and config struct with specific first elements (struct gpio_driver_config and struct gpio_driver_data). The driver for vnd,gpio does not so.

This triggers a null pointer access for instance if gpio_pin_configure is called in:

	__ASSERT((cfg->port_pin_mask & (gpio_port_pins_t)BIT(pin)) != 0U,
		 "Unsupported pin");

**Comment by henrikbrixandersen** [comment]
@benediktibk Please test #56173.
