### ISSUE TITLE
k_thread_entry_t undefined in in kernel/thread.h if CONFIG_THREAD_MONITOR is enabled

### ISSUE THREAD

**Issue by jimmyzumthurm** [zephyrproject-rtos/zephyr#55974]
**Describe the bug**
It seems that a header kernel file misses include, as `k_thread_entry_t` is undefined in `<zephyr/kernel/thread.h>` and it is used if `CONFIG_THREAD_MONITOR ` is enabled. As this is defined in `<zephyr/sys/arch_interface.h>` , I would guess that this include is missing, as including this file fixes the issue. 

**To Reproduce:**
- Enable `CONFIG_THREAD_MONITOR `
- Add source file that includes <zephyr/thread.h>
- `west build` with `CONFIG_THREAD_MONITOR `enabled

This started occurring after upgrading from Zephyr 3.0.99 to Zephyr 3.2.99, but it seems that this could be valid for Zephr 3.3.99 as include also misses there. 

**Expected behavior:**
Zephyr compiles without errors. 

**Impact:**
Build system generates error because it does not recognize `k_thread_entry_t ` type. 

**Logs and console output:**

```
In file included from c:\work\git\projects\my_project\src\main.c:7:
C:\work\git\projects\zephyr\include\zephyr\kernel\thread.h:35:9: error: unknown type name 'k_thread_entry_t'
   35 |         k_thread_entry_t pEntry;
      |         ^~~~~~~~~~~~~~~~
C:\work\git\projects\zephyr\include\zephyr\kernel\thread.h:50:9: error: unknown type name 'sys_dnode_t'
   50 |         sys_dnode_t      node;
      |         ^~~~~~~~~~~
C:\work\git\projects\zephyr\include\zephyr\kernel\thread.h:61:17: error: unknown type name 'sys_dnode_t'
   61 |                 sys_dnode_t qnode_dlist;
      |                 ^~~~~~~~~~~
C:\work\git\projects\zephyr\include\zephyr\kernel\thread.h:62:31: error: field 'qnode_rb' has incomplete type
   62 |                 struct rbnode qnode_rb;
      |                               ^~~~~~~~
C:\work\git\projects\zephyr\include\zephyr\kernel\thread.h:68:9: error: unknown type name '_wait_q_t'
   68 |         _wait_q_t *pended_on;
      |         ^~~~~~~~~
C:\work\git\projects\zephyr\include\zephyr\kernel\thread.h:131:25: error: field 'timeout' has incomplete type
  131 |         struct _timeout timeout;
      |                         ^~~~~~~
C:\work\git\projects\zephyr\include\zephyr\kernel\thread.h:250:30: error: field 'callee_saved' has incomplete type
  250 |         struct _callee_saved callee_saved;
      |                              ^~~~~~~~~~~~
C:\work\git\projects\zephyr\include\zephyr\kernel\thread.h:256:9: error: unknown type name '_wait_q_t'
  256 |         _wait_q_t join_queue;
      |         ^~~~~~~~~
C:\work\git\projects\zephyr\include\zephyr\kernel\thread.h:343:29: error: field 'arch' has incomplete type
  343 |         struct _thread_arch arch;
```

**Environment:**
 - Windows
 - Zephyr SDK 0.15.2
 - Zephyr 3.2.99 version

**Additional context:**

**Comment by henrikbrixandersen** [comment]
Please use our bug template when reporting bugs. You need to edit this issue to include the needed information from https://github.com/zephyrproject-rtos/zephyr/blob/main/.github/ISSUE_TEMPLATE/bug_report.md
