### ISSUE TITLE
Bluetooth: audio: BAP Unicast Client: Invalid Opcode and Invalid Length Response_Codes are not handled properly

### ISSUE THREAD

**Issue by MariuszSkamra** [zephyrproject-rtos/zephyr#55977]
**Describe the bug**
When the server rejects the operation with errors `0x01 = Unsupported Opcode` or `0x02 = Invalid Length` the "`Number_of_ASEs` shall be set to `0xFF`";
Moreover,  the ASCS_v1.0 _Table 4.7: Format of ASE Control Point characteristic value when notified_  states that `ASE_ID[i]` "If the `Response_Code` value is `0x01` or `0x02`, ASE_ID shall be set to `0x00`, and `[i]` shall be set to 0."
`Response_Code[i]` and `Reason[i]` will be `0x00` as well, where `[i]` shall be 0.

Consider Config Codec operation request below :
```
Opcode:                                 0x01
Number_of_ASEs:                         0x02
ASE_ID[0]:                              0x01
Target_Latency[0]:                      0x01
Target_PHY[0]:                          0x01
Codec_ID[0]:                            0x0600000000
Codec_Specific_Configuration_Length[0]: 0x00
ASE_ID[0]:                              0x02
Target_Latency[0]:                      0x01
Target_PHY[0]:                          0x01
Codec_ID[0]:                            0x0600000000
Codec_Specific_Configuration_Length[0]: 0x05 <- here' the bug. The PDU seems to be truncated
```

Once the server received such PDU, it shall reject it with Invalid Length Response_Code
```
Opcode:                                 0x01
Number_of_ASEs:                         0xFF
ASE_ID[0]:                              0x00
Response_Code[0]:                       0x02
Reason[i]:                              0x00
```

The current implementation does not handle that.
It fails to parse the correctly formatted ASE Control Point notification. The Response_Code is not passed to the application. The Application is not informed about the failed operation, because the Client does not store the context of operation performed.

**Comment by Thalley** [comment]
@MariuszSkamra I think this has been fixed. 

I modified the stack to send an invalid length codec configure, and this is the notification I received:

```
Opcode:                                 0x01
Number_of_ASEs:                         0xFF
ASE_ID[0]:                              0x00
Response_Code[0]:                       0x02
Reason[i]:                              0x00
```

as seen from the log:
```
unicast_client_cp_notify: rsp->num_ase 255
unicast_client_cp_notify: op Config Codec (0x01) id 0x00 code Invalid Length (0x02) reason None (0x00)
```

I suggest to close this, unless you can otherwise provide evidence that this is still an issue
