### ISSUE TITLE
STM32: I2C 10 bit addressing not working in zephyr 3.2.0

### ISSUE THREAD

**Issue by VineetaNarkhede-eaton** [zephyrproject-rtos/zephyr#55987]
**I2C 10 bit addressing not working in zephyr 3.2.0 due to newly added code, it is working with zephyr 3.1.0 **
I am using two nucleo_u575zi_q boards, one as a master and another is simulated as slave/target.
I am passing 0x3fe as slave address (10 bit), the slave is going into BUS fault at to line number 129 in i2c_ll_stm32_v2.c which is newly added in zephyr 3.2.0. 
![image](https://user-images.githubusercontent.com/88422239/226322606-f062173c-dc9f-49f9-a464-9a96b04aa655.png)

I have investigated the issue and found that `LL_I2C_GetAddressMatchCode(i2c)` is giving wrong value as it can handle only the value between 0x00 and 0x3F. Due to this, first if condition becomes false (line no. 127), then control goes to next if condition (line no. 127), here slave2_cfg is null hence it runs into BUS fault. nullptr check should be added here.

When slave address is set 0x3fe, `LL_I2C_GetAddressMatchCode(i2c)` returns 0xf6 (instead of 0x7fc) and `slave_address` becomes 0x7b instead of 0x3fe. `data->slave_cfg->address` is correct i.e 0x3fe. `slave_address `data type should be `uint16_t` instead of `uint8_t`, like the data type of `data->slave_cfg->address`. 

I modified the code as shown in below snapshot and I2C 10 bit addressing is working fine
![image](https://user-images.githubusercontent.com/88422239/226323152-34f89fcb-e105-4fa0-bf38-a47f93df1f2e.png)

**Comment by carlescufi** [comment]
@VineetaNarkhede-eaton thanks for the report, perhaps consider posting a Pull Request with the suggested fix?

**Comment by VineetaNarkhede-eaton** [comment]
@carlescufi Yes, I can raise a pull request.

**Comment by erwango** [comment]
@VineetaNarkhede-eaton Do you still plan to raise a PR for this ? (we'd be glad)

**Comment by VineetaNarkhede-eaton** [comment]
@erwango I have a plan to raise a PR, but not in the immediate plan.

**Comment by erwango** [comment]
@VineetaNarkhede-eaton I'm removing the stale label, if that's still in your plans.

**Comment by VineetaNarkhede-eaton** [comment]
@erwango  I can see the pull request is already raised, hence this ticket can be closed.
https://github.com/zephyrproject-rtos/zephyr/pull/60620

**Comment by erwango** [comment]
> @erwango I can see the pull request is already raised, hence this ticket can be closed. #60620

We'll close it once it is merged. To help in the review process, can you have a look to it, possibly test it on your side and provide a feedback ? This will likely speed up things

**Comment by erwango** [comment]
@VineetaNarkhede-eaton Would you be able to test/review https://github.com/zephyrproject-rtos/zephyr/pull/60620 ?
We're unable to test on our side, so this can't progress.

**Comment by VineetaNarkhede-eaton** [comment]
@erwango I reviewed the pull request https://github.com/zephyrproject-rtos/zephyr/pull/60620, I see exact code fix which I had suggested in this ticket, hence approved. This issue fix was tested while working on this issue.
