### ISSUE TITLE
RFC: topic-v2.7-riscv branch

### ISSUE THREAD

**Issue by cfriedt** [zephyrproject-rtos/zephyr#55991]
## Introduction

Create a topic branch for RISC-V support on top of `v2.7-branch`.

### Problem description

Although the TSC voted some time ago (and it was very close) to not incorporate RISC-V unicore and SMP bugfixes back into the `v2.7-branch` (LTSv2), it is nevertheless important to acknowledge the Zephyr Community members who depend on LTS releases on the RISC-V architecture.

### Proposed change

Create a `topic-v2.7-riscv` branch and enable CI on that branch.

At some point in the future, if it is possible to re-evaluate merging the RISC-V changes back into `v2.7-branch`, then there will at least be a central point of reference for doing so. That will allow additional evidence to be collected (performance, funcationality, and reliability improvements, deployments, etc).

### Proposed change (Detailed)

Create a `topic-v2.7-riscv` branch and enable CI on that branch.
- [x] fork upstream `v2.7-branch` to `topic-v2.7-riscv`
- [x] rebase `topic-v2.7-riscv` onto `v2.7_riscv_smp` from https://github.com/npitre/zephyr/

Note: the `v2.7_riscv_smp` fixes originally appeared in https://github.com/zephyrproject-rtos/zephyr/pull/51727

The resulting branch is here, and the kernel testsuites pass for
* all [tier0](https://github.com/zephyrproject-rtos/zephyr/issues/38566) RISC-V targets
* out-of-tree / custom RISC-V silicon
* (will add specific tier1 targets as they are tested)

https://github.com/zephyrproject-rtos/zephyr/tree/topic-v2.7-riscv

```shell
$ twister --retry-failed 3 -i -p qemu_riscv32 -p qemu_riscv64 -p qemu_riscv32_smp -p qemu_riscv64_smp -T tests/kernel/
INFO    - Total complete:  368/ 368  100%  skipped:  334, failed:    3
INFO    - 2 Iteration:
INFO    - Adding tasks to the queue...
INFO    - Added initial list of jobs to queue
INFO    - Total complete:  624/ 368  169%  skipped:  334, failed:    0
INFO    - 290 of 290 test configurations passed (100.00%), 0 failed, 334 skipped with 0 warnings in 207.49 seconds
INFO    - In total 3378 test cases were executed, 2794 skipped on 4 out of total 396 platforms (1.01%)
INFO    - 286 test configurations executed on platforms, 4 test configurations were only built.
INFO    - Saving reports...
INFO    - Writing xunit report /home/cfriedt/zephyrproject/zephyr/twister-out/twister.xml...
INFO    - Writing xunit report /home/cfriedt/zephyrproject/zephyr/twister-out/twister_report.xml...
INFO    - Run completed
$ echo $?
0
```

### Dependencies

Only `v2.7-branch`

### Concerns and Unresolved Questions

Although the TSC voted some time ago (and it was very close) to not incorporate unicore and SMP bugfixes back into the `v2.7-branch` (LTSv2), it is nevertheless important to support Zephyr community members who depend on LTS releases. 

## Alternatives

Maintaining (many) external forks of `v2.7-branch` instead of a centralized branch.

**Comment by henrikbrixandersen** [comment]
The TSC voted against back porting these commits to the `v2.7-branch` in upstream Zephyr. With the newly pushed `topic-v2.7-riscv` branch we now effectively have an upstream-hosted fork of the official Zephyr v2.7 release branch containing commits which the TSC explicitly voted against back porting.

A lot of testing goes into our LTS releases in general and this was certainly also the case for v2.7. With the amount of commits/changes added to the RISC-V fork users can not rely on the QA being performed on the `v2.7-branch` prior to release holding up for the fork, but this is not evident in any way.

Personally, I think upstream `topic`/development branches should only be allowed for short-term feature development as a last resort (e.g. when development work involves contributors from multiple downstream users/companies). We should not use `topic` branches for hosting unofficial forks like the `topic-v2.7-riscv` branch, especially when the TSC already voted no to making said commits part of the official `v2.7-branch`.

**Comment by cfriedt** [comment]
> The TSC voted against back porting these commits to the `v2.7-branch` in upstream Zephyr. With the newly pushed `topic-v2.7-riscv` branch we now effectively have an upstream-hosted fork of the official Zephyr v2.7 release branch containing commits which the TSC explicitly voted against back porting.

Correct. The votes were 11-10 against, IIRC (discounting abstentions). However, it is entirely feasible and permitted to re-table a vote with more evidence as to why it is being re-tabled.

It would be premature, undemocratic, and punitive to have the TSC vote on
a) deleting this topic branch
b) voting on the feasibility of the backport without seeing all of the available evidence.

> A lot of testing goes into our LTS releases in general and this was certainly also the case for v2.7. With the amount of commits/changes added to the RISC-V fork users can not rely on the QA being performed on the `v2.7-branch` prior to release holding up for the fork, but this is not evident in any way.

The only changes that have been added to `topic-v2.7-riscv` are those that exist already in `main`. I.e. they are all backports. You can easily verify that.

The entire point of the `topic-v2.7-riscv` branch and this RFC are to collect evidence to satisfy QA requirements.

> Personally, I think upstream `topic`/development branches should only be allowed for short-term feature development as a last resort (e.g. when development work involves contributors from multiple downstream users/companies).

And that is exactly what this topic branch is being used for.

> We should not use `topic` branches for hosting unofficial forks like the `topic-v2.7-riscv` branch, especially when the TSC already voted no to making said commits part of the official `v2.7-branch`.

I disagree on that take. Several members of the Zephyr board have also reassured me that it is entirely permitted to re-table a vote to the TSC. Moreover, the work that goes in to something like that, involving several companies, *should* be done in the open, and not behind closed doors. Additionally, it is incredibly important to have a central location for doing so, where the entire Zephyr Community *and* the TSC is able to see all of the evidence that *does* justify the backport.

Preventing TSC members from seeing that additional evidence would be odd to say the least, and I would question the motivation for doing so.

Generally speaking, more information is usually useful than less information, when making a technical decision.

**Comment by nashif** [comment]
approved by the TSC. closing
