### ISSUE TITLE
latency_measure benchmark runs out of stack with CONFIG_NO_OPTIMIZATIONS=y

### ISSUE THREAD

**Issue by Archie-Elvie** [zephyrproject-rtos/zephyr#56008]
When running the latency_measure with CONFIG_NO_OPTIMIZATIONS, it runs out of stack during the `suspend_resume()` test.

**To Reproduce**
Steps to reproduce the behaviour:
1. Be in zephyr root folder 
2. `west build -p -b nrf52833dk_nrf52833  tests/benchmarks/latency_measure -- -DCONFIG_NO_OPTIMIZATIONS=y`
3. `west flash`
4. View crash in terminal

**Logs and console output**
``` bash
�*** Booting Zephyr OS build v3.2.99-ncs1 ***
START - Time Measurement
Timing results: Clock frequency: 64 MHz
Average thread context switch using yield                   :    1033 cycles ,    16149 ns
Average context switch time between threads (coop)          :    1157 cycles ,    18092 ns
Switch from ISR back to interrupted thread                  :    1536 cycles ,    24000 ns
E: ***** MPU FAULT *****
E:   Data Access Violation
E:   MMFAR Address: 0x4c
E: r0/a1:  0xfffffffd  r1/a2:  0xffffffff  r2/a3:  0xe000ed00
E: r3/a4:  0x00000000 r12/ip:  0x00000040 r14/lr:  0x00011bbd
E:  xpsr:  0x81000000
E: Faulting instruction address (r15/pc): 0x00011bbc
E: >>> ZEPHYR FATAL ERROR 0: CPU exception on CPU 0
E: Current thread: 0x200002e8 (int_thread_id)
```

**Environment (please complete the following information):**
NCS version 2.2.0
ZDSK versions 0.15.2
nRF2833-DK

It can be fixed by increasing the stack by 512 bytes.

**Comment by henrikbrixandersen** [comment]
> This can be fixed by increasing the stack. This is not a bug. Description for the kconfig option will be added.

I have opened #56084 for mentioning having to increase the default stack sizes when using `CONFIG_NO_OPTIMIZATIONS=y`.
