### ISSUE TITLE
Building SPI_FLASH sample with stm32h7b3i_dk fails.

### ISSUE THREAD

**Issue by dale-herman** [zephyrproject-rtos/zephyr#56028]
Same results in 3.3.0 and tip.
Cannot get SPI flash AND DMA working.
By removing dmas, I can get SPI working. But I would like to get DMA also working.

(.venv) dherman@ub:~/zephyrproject/zephyr$ west build -p always -b stm32h7b3i_dk samples/drivers/spi_flash
-- west build: making build dir /home/dherman/zephyrproject/zephyr/build pristine
-- west build: generating a build system
Loading Zephyr default modules (Zephyr base).
-- Application: /home/dherman/zephyrproject/zephyr/samples/drivers/spi_flash
-- CMake version: 3.24.2
-- Found Python3: /home/dherman/zephyrproject/.venv/bin/python3.10 (found suitable exact version "3.10.7") found components: Interpreter 
-- Cache files will be written to: /home/dherman/.cache/zephyr
-- Zephyr version: 3.3.99 (/home/dherman/zephyrproject/zephyr)
-- Found west (found suitable version "1.0.0", minimum required is "0.7.1")
-- Board: stm32h7b3i_dk
-- ZEPHYR_TOOLCHAIN_VARIANT not set, trying to locate Zephyr SDK
-- Found host-tools: zephyr 0.15.0 (/home/dherman/zephyr-sdk-0.15.0)
-- Found toolchain: zephyr 0.15.0 (/home/dherman/zephyr-sdk-0.15.0)
-- Found Dtc: /home/dherman/zephyr-sdk-0.15.0/sysroots/x86_64-pokysdk-linux/usr/bin/dtc (found suitable version "1.6.0", minimum required is "1.4.6") 
-- Found BOARD.dts: /home/dherman/zephyrproject/zephyr/boards/arm/stm32h7b3i_dk/stm32h7b3i_dk.dts
-- Found devicetree overlay: /home/dherman/zephyrproject/zephyr/samples/drivers/spi_flash/boards/stm32h7b3i_dk.overlay
devicetree error: /home/dherman/zephyrproject/zephyr/samples/drivers/spi_flash/boards/stm32h7b3i_dk.overlay:12 (column 1): parse error: undefined node label 'mdma'
-- In: /home/dherman/zephyrproject/zephyr/build/zephyr, command: /home/dherman/zephyrproject/.venv/bin/python3.10;/home/dherman/zephyrproject/zephyr/scripts/dts/gen_defines.py;--dts;/home/dherman/zephyrproject/zephyr/build/zephyr/zephyr.dts.pre;--dtc-flags;'';--bindings-dirs;/home/dherman/zephyrproject/zephyr/dts/bindings;--header-out;/home/dherman/zephyrproject/zephyr/build/zephyr/include/generated/devicetree_generated.h.new;--dts-out;/home/dherman/zephyrproject/zephyr/build/zephyr/zephyr.dts.new;--edt-pickle-out;/home/dherman/zephyrproject/zephyr/build/zephyr/edt.pickle;--vendor-prefixes;/home/dherman/zephyrproject/zephyr/dts/bindings/vendor-prefixes.txt
CMake Error at /home/dherman/zephyrproject/zephyr/cmake/modules/dts.cmake:297 (message):
  gen_defines.py failed with return code: 1
Call Stack (most recent call first):
  /home/dherman/zephyrproject/zephyr/cmake/modules/zephyr_default.cmake:113 (include)
  /home/dherman/zephyrproject/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:66 (include)
  /home/dherman/zephyrproject/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:92 (include_boilerplate)
  CMakeLists.txt:4 (find_package)

-- Configuring incomplete, errors occurred!
FATAL ERROR: command exited with status 1: /usr/bin/cmake -DWEST_PYTHON=/home/dherman/zephyrproject/.venv/bin/python3 -B/home/dherman/zephyrproject/zephyr/build -GNinja -DBOARD=stm32h7b3i_dk -S/home/dherman/zephyrproject/zephyr/samples/drivers/spi_flash
(.venv) dherman@ub:~/zephyrproject/zephyr$

**Comment by FRASTM** [comment]
You're right, the mdma driver is not available for the stm32h7. 
As the DMA transfer on the octospi2 is only available on MDMA (not DMAMUX request),  it should not be enabled for octospi transfer.
