### ISSUE TITLE
Fix build issues with arm clang compiler for mec17xx platforms

### ISSUE THREAD

**Issue by galak** [zephyrproject-rtos/zephyr#56067]
There are a number of different failures we see when building the arm clang compiler when building the mec17xx platforms.

**Comment by galak** [comment]
https://github.com/zephyrproject-rtos/zephyr/issues/56067

**Comment by galak** [comment]
Backport #56577 to fix init order issue w/arm-clang.

**Comment by galak** [comment]
Backport #50049 to fix build warnings/errors with arm-clang.  Really just need commit f5e892749b82f2b2e3dc9e343205a37a21fb2f88.

**Comment by galak** [comment]
Backport 49899 as start of fixing some linker issues w/arm-clang and logging.

**Comment by jgl-meta** [comment]
@galak what's the status of this one? It was marked stale and has many PRs that have been merged.

**Comment by jhedberg** [comment]
Many/most issues already fixed. If something is still broken please open a new bug report.
