### ISSUE TITLE
Bluetooth: audio: ascs: The service is unusable when the unicast_server_cb gets unregistered

### ISSUE THREAD

**Issue by MariuszSkamra** [zephyrproject-rtos/zephyr#56111]
**Describe the bug**
Once the callbacks are unregisterd, the service becomes unusable, because none of the operations can be performed. Every operation is rejected with -ENOTSUP error. Meaning that ASE in e.g. streaming state cannot be released by the client.

**Comment by henrikbrixandersen** [comment]
Please use our bug template when reporting bugs. You need to edit this issue to include the needed information from https://github.com/zephyrproject-rtos/zephyr/blob/main/.github/ISSUE_TEMPLATE/bug_report.md
