### ISSUE TITLE
Bluetooth: audio: ascs: mandatory Control Point operation returns Unsupported Opcode error

### ISSUE THREAD

**Issue by MariuszSkamra** [zephyrproject-rtos/zephyr#56139]
**Describe the bug**
When the Unicast Server callbacks are not registered, every operation that is initiated by client fails with Unsupported Opcode error. That behavior violates the specification, where the all of the operations defined in the ASCS_v1.0 so far are Mandatory. Thus Unsupported Opcode response code shall not be returned.

**Comment by henrikbrixandersen** [comment]
Please use our bug template when reporting bugs. You need to edit this issue to include the needed information from https://github.com/zephyrproject-rtos/zephyr/blob/main/.github/ISSUE_TEMPLATE/bug_report.md
