### ISSUE TITLE
Rename efr32bg_sltb010a board 

### ISSUE THREAD

**Issue by antoinebout0** [zephyrproject-rtos/zephyr#56155]
efr32bg_sltb010a is a commercial kit name. efr32bg_sltb010a may refer to BRD4184A and BRD4184B boards which have different pin mapping. Currently in Zephyr, efr32bg_sltb010a corresponds to BRD4184A.

I would like to rename efr32bg_sltb010a to something more specific to BRD4184A and then add support for the efr32bg22 BRD4184B board. I'll create a PR soon.

EFR32BG22-SLTB010A support was committed by @lpawelcz and @fkokosinski 
What your opinion on this issue?

**Comment by henrikbrixandersen** [comment]
Sounds good to me. Please submit a PR.
