### ISSUE TITLE
samples/drivers/counter/alarm fails for nrf boards in main branch

### ISSUE THREAD

**Issue by manuargue** [zephyrproject-rtos/zephyr#56188]
**Describe the bug**
`samples/drivers/counter/alarm` fails to build for nrf52840dk_nrf52840, nrf51dk_nrf51422, nrf9160dk_nrf9160, nrf52dk_nrf52832

**To Reproduce**
Build the test for these boards.

**Expected behavior**
Twister build pass for these boards.

**Impact**
Blocking https://github.com/zephyrproject-rtos/zephyr/pull/56178

**Logs and console output**
See https://github.com/zephyrproject-rtos/zephyr/actions/runs/4510053473/jobs/7940581606?pr=56178

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: Zephyr SDK
 - Commit SHA 2d26baaeb1b764350fe226a4089395d958154168

**Additional context**
N/A

**Comment by anangl** [comment]
#56078 should fix this.
