### ISSUE TITLE
zephyr.git/tests/misc/test_build/testcase.yaml#test_newlib @ esp32:xtensa BUILD failed

### ISSUE THREAD

**Issue by pswarnak** [zephyrproject-rtos/zephyr#5619]
Commit ID:                                34b8b3b5ee6c24401a9490c0dd2b2cc11ad65479 
Branch:          master
URL:          https://github.com/zephyrproject-rtos/zephyr.git
Target Name: esp32 

### Testcase and steps to reproduce
To clone (if you have not yet):
  git clone https://github.com/zephyrproject-rtos/zephyr.git -b master zephyr.git

Checkout the right versions:
  (cd zephyr.git; git checkout -f 34b8b3b5ee6c24401a9490c0dd2b2cc11ad65479)

Setup build environment for esp32 toolchain:
  Toolchain: ZEPHYR_GCC_VARIANT=espressif
  
Reproduce it [*]:
```
  cd zephyr.git/tests/misc/test_build
  rm -rf build && mkdir build && cd build
  cp ../newlib.conf prj.conf
  cmake -D BOARD=esp32 ../
  make BOARD=esp32
```
### Actual Output:
build output: collect2: error: ld returned 1 exit status
build output: make[3]: *** [zephyr/CMakeFiles/zephyr_prebuilt.dir/build.make:102: zephyr/zephyr_prebuilt.elf] Error 1
build output: make[2]: *** [CMakeFiles/Makefile2:542: zephyr/CMakeFiles/zephyr_prebuilt.dir/all] Error 2
build output: make[1]: *** [Makefile:84: all] Error 2
build failed

### Expected Output:
No compilation errors and test run completion.

### Detailed description
Automated test run failed.
will run on target group 'target=esp32-00:xtensa'
configure passed
build passed: 'mkdir -p outdir-s9zx-urzm-esp32; rm -f outdir-s9zx-urzm-esp32/.config'
build passed: 'cmake -DPREBUILT_HOST_TOOLS=/opt/zephyr-sdk-0.9.2/sysroots/x86_64-pokysdk-linux/usr/bin -DBOARD=esp32 -DARCH=xtensa -DEXTRA_CPPFLAGS="-DTC_RUNID=ci-180109-0618-800:urzm" -DEXTRA_CFLAGS="-Werror -Wno-error=deprecated-declarations" -DEXTRA_AFLAGS=-Wa,--fatal-warnings -DEXTRA_LDFLAGS=-Wl,--fatal-warnings -DCONF_FILE=newlib.conf -B"outdir-s9zx-urzm-esp32" -H"zephyr.git/tests/misc/test_build"'
build output: CMake Deprecation Warning at zephyr.git/cmake/app/boilerplate.cmake:38 (cmake_policy):
build output:   The OLD behavior for policy CMP0000 will be removed from a future version
build output:   of CMake.
build output:
build output:   The cmake-policies(7) manual explains that the OLD behaviors of all
build output:   policies are deprecated and that a policy should be set to OLD only under
build output:   specific short-term circumstances.  Projects should be ported to the NEW
build output:   behavior and not rely on setting a policy to OLD.
build output: Call Stack (most recent call first):
build output:   CMakeLists.txt:1 (include)
build output:
build output:
build output: -- Found PythonInterp: /usr/bin/python3 (found suitable version "3.6.3", minimum required is "3.4")
build output: -- Selected BOARD esp32
build output: Zephyr version: 1.10.99
build output: Using zephyr.git/boards/xtensa/esp32/esp32_defconfig as base
build output: Merging newlib.conf
build output: #
build output: # configuration written to outdir-s9zx-urzm-esp32/zephyr/.config
build output: #
build output: -- Generating zephyr/include/generated/autoconf.h
build output: -- Generating zephyr/include/generated/generated_dts_board.h
build output: CMake Warning at zephyr.git/boards/common/esp32.board.cmake:5 (message):
build output:   Setting ESP_IDF_PATH in the environment is deprecated.  Use cmake
build output:   -DESP_IDF_PATH=...  instead.
build output: Call Stack (most recent call first):
build output:   zephyr.git/boards/xtensa/esp32/board.cmake:1 (include)
build output:   zephyr.git/cmake/app/boilerplate.cmake:234 (include)
build output:   CMakeLists.txt:1 (include)
build output:
build output:
build output: -- The C compiler identification is GNU 5.2.0
build output: -- The CXX compiler identification is GNU 5.2.0
build output: -- The ASM compiler identification is GNU
build output: -- Found assembler: /opt/xtensa-esp32-elf/bin/xtensa-esp32-elf-gcc
build output: -- Performing Test toolchain_is_ok
build output: -- Performing Test toolchain_is_ok - Success
build output: -- Performing Test check_nostartfiles
build output: -- Performing Test check_nostartfiles - Success
build output: -- Performing Test check_nodefaultlibs
build output: -- Performing Test check_nodefaultlibs - Success
build output: -- Performing Test check_nostdlib
build output: -- Performing Test check_nostdlib - Success
build output: -- Performing Test check_static
build output: -- Performing Test check_static - Success
build output: -- Performing Test check_no_pie
build output: -- Performing Test check_no_pie - Failed
build output: -- Performing Test check_fno_asynchronous_unwind_tables_C
build output: -- Performing Test check_fno_asynchronous_unwind_tables_C - Success
build output: -- Performing Test check_fno_pie_C
build output: -- Performing Test check_fno_pie_C - Success
build output: -- Performing Test check_fno_pic_C
build output: -- Performing Test check_fno_pic_C - Success
build output: -- Performing Test check_fno_strict_overflow_C
build output: -- Performing Test check_fno_strict_overflow_C - Success
build output: -- Performing Test check_Wno_pointer_sign_C
build output: -- Performing Test check_Wno_pointer_sign_C - Success
build output: -- Performing Test check_Wno_unused_but_set_variable_C
build output: -- Performing Test check_Wno_unused_but_set_variable_C - Success
build output: -- Performing Test check_fno_reorder_functions_C
build output: -- Performing Test check_fno_reorder_functions_C - Success
build output: -- Performing Test check_fno_defer_pop_C
build output: -- Performing Test check_fno_defer_pop_C - Success
build output: -- Performing Test check_Werror_implicit_int_C
build output: -- Performing Test check_Werror_implicit_int_C - Success
build output: -- Performing Test check_Wl__X
build output: -- Performing Test check_Wl__X - Success
build output: -- Performing Test check_Wl__N
build output: -- Performing Test check_Wl__N - Success
build output: -- Performing Test check_Wl___gc_sections
build output: -- Performing Test check_Wl___gc_sections - Success
build output: -- Performing Test check_Wl___build_id_none
build output: -- Performing Test check_Wl___build_id_none - Success
build output: -- Performing Test check_ffunction_sections_C
build output: -- Performing Test check_ffunction_sections_C - Success
build output: -- Performing Test check_fdata_sections_C
build output: -- Performing Test check_fdata_sections_C - Success
build output: -- Performing Test check_mlongcalls_C
build output: -- Performing Test check_mlongcalls_C - Success
build output: -- Performing Test check_Wl___print_memory_usage
build output: -- Performing Test check_Wl___print_memory_usage - Failed
build output: -- Configuring done
build output: -- Generating done
build output: CMake Warning:
build output:   Manually-specified variables were not used by the project:
build output:
build output:     PREBUILT_HOST_TOOLS
build output:
build output:
build output: -- Build files have been written to: outdir-s9zx-urzm-esp32
build passed: 'make -C outdir-s9zx-urzm-esp32 config-sanitycheck'
build output: Scanning dependencies of target config-sanitycheck
build output: Built target config-sanitycheck
build failed: exit code 2 from 'make -C outdir-s9zx-urzm-esp32'
build output: Scanning dependencies of target syscall_list_h_target
build output: Scanning dependencies of target syscall_macros_h_target
build output: [  1%] Generating always_rebuild
build output: Building for board esp32
build output: [  3%] Generating include/generated/syscall_macros.h
build output: [  4%] Generating misc/generated/syscalls.json
build output: [  4%] Built target syscall_macros_h_target
build output: [  6%] Generating include/generated/syscall_dispatch.c, include/generated/syscall_list.h
build output: [  6%] Built target syscall_list_h_target
build output: Scanning dependencies of target offsets
build output: [  7%] Building C object zephyr/CMakeFiles/offsets.dir/arch/xtensa/core/offsets/offsets.c.obj
build output: [  9%] Linking C static library liboffsets.a
build output: [  9%] Built target offsets
build output: Scanning dependencies of target offsets_h
build output: [ 10%] Generating include/generated/offsets.h
build output: [ 10%] Built target offsets_h
build output: Scanning dependencies of target app
build output: Scanning dependencies of target linker_pass2_script
build output: [ 12%] Generating linker_pass2.cmd
build output: [ 13%] Building C object CMakeFiles/app.dir/src/main.c.obj
build output: Scanning dependencies of target kernel
build output: [ 13%] Built target linker_pass2_script
build output: [ 15%] Building C object zephyr/kernel/CMakeFiles/kernel.dir/alert.c.obj
build output: [ 16%] Linking C static library libapp.a
build output: [ 18%] Building C object zephyr/kernel/CMakeFiles/kernel.dir/device.c.obj
build output: [ 18%] Built target app
build output: [ 19%] Building C object zephyr/kernel/CMakeFiles/kernel.dir/errno.c.obj
build output: [ 22%] Building C object zephyr/kernel/CMakeFiles/kernel.dir/init.c.obj
build output: [ 22%] Building C object zephyr/kernel/CMakeFiles/kernel.dir/idle.c.obj
build output: [ 24%] Building C object zephyr/kernel/CMakeFiles/kernel.dir/mailbox.c.obj
build output: [ 25%] Building C object zephyr/kernel/CMakeFiles/kernel.dir/mem_slab.c.obj
build output: [ 27%] Building C object zephyr/kernel/CMakeFiles/kernel.dir/mempool.c.obj
build output: Scanning dependencies of target zephyr
build output: [ 28%] Building C object zephyr/CMakeFiles/zephyr.dir/lib/crc/crc16_sw.c.obj
build output: [ 30%] Building C object zephyr/kernel/CMakeFiles/kernel.dir/msg_q.c.obj
build output: [ 31%] Building C object zephyr/CMakeFiles/zephyr.dir/misc/printk.c.obj
build output: [ 33%] Building C object zephyr/kernel/CMakeFiles/kernel.dir/mutex.c.obj
build output: [ 34%] Building C object zephyr/CMakeFiles/zephyr.dir/misc/generated/configs.c.obj
build output: [ 36%] Building C object zephyr/kernel/CMakeFiles/kernel.dir/pipes.c.obj
build output: [ 37%] Building C object zephyr/CMakeFiles/zephyr.dir/arch/common/isr_tables.c.obj
build output: Scanning dependencies of target linker_script
build output: [ 39%] Generating linker.cmd
build output: [ 39%] Built target linker_script
build output: [ 40%] Building C object zephyr/CMakeFiles/zephyr.dir/arch/xtensa/soc/esp32/soc.c.obj
build output: Scanning dependencies of target lib__libc__newlib
build output: [ 42%] Building C object zephyr/CMakeFiles/zephyr.dir/arch/xtensa/core/cpu_idle.c.obj
build output: [ 43%] Building C object zephyr/lib/libc/newlib/CMakeFiles/lib__libc__newlib.dir/libc-hooks.c.obj
build output: [ 45%] Building C object zephyr/kernel/CMakeFiles/kernel.dir/queue.c.obj
build output: [ 46%] Building C object zephyr/CMakeFiles/zephyr.dir/arch/xtensa/core/fatal.c.obj
build output: [ 48%] Linking C static library liblib__libc__newlib.a
build output: [ 50%] Building C object zephyr/kernel/CMakeFiles/kernel.dir/sched.c.obj
build output: [ 50%] Built target lib__libc__newlib
build output: [ 51%] Building C object zephyr/CMakeFiles/zephyr.dir/arch/xtensa/core/irq_manage.c.obj
build output: [ 53%] Building ASM object zephyr/CMakeFiles/zephyr.dir/arch/xtensa/core/swap.S.obj
build output: [ 54%] Building C object zephyr/kernel/CMakeFiles/kernel.dir/sem.c.obj
build output: [ 56%] Building C object zephyr/CMakeFiles/zephyr.dir/arch/xtensa/core/thread.c.obj
build output: [ 57%] Building C object zephyr/kernel/CMakeFiles/kernel.dir/stack.c.obj
build output: [ 59%] Building ASM object zephyr/CMakeFiles/zephyr.dir/arch/xtensa/core/xtensa_context.S.obj
build output: [ 60%] Building C object zephyr/kernel/CMakeFiles/kernel.dir/sys_clock.c.obj
build output: [ 62%] Building ASM object zephyr/CMakeFiles/zephyr.dir/arch/xtensa/core/xtensa_intr_asm.S.obj
build output: [ 63%] Building C object zephyr/kernel/CMakeFiles/kernel.dir/system_work_q.c.obj
build output: [ 65%] Building C object zephyr/CMakeFiles/zephyr.dir/arch/xtensa/core/xtensa_intr.c.obj
build output: [ 66%] Building C object zephyr/kernel/CMakeFiles/kernel.dir/thread.c.obj
build output: [ 68%] Building C object zephyr/kernel/CMakeFiles/kernel.dir/thread_abort.c.obj
build output: [ 69%] Building C object zephyr/kernel/CMakeFiles/kernel.dir/version.c.obj
build output: [ 71%] Building ASM object zephyr/CMakeFiles/zephyr.dir/arch/xtensa/core/xtensa_vectors.S.obj
build output: [ 72%] Building ASM object zephyr/CMakeFiles/zephyr.dir/arch/xtensa/core/xt_zephyr.S.obj
build output: [ 74%] Building C object zephyr/kernel/CMakeFiles/kernel.dir/work_q.c.obj
build output: [ 75%] Building ASM object zephyr/CMakeFiles/zephyr.dir/arch/xtensa/core/atomic.S.obj
build output: [ 77%] Building C object zephyr/CMakeFiles/zephyr.dir/drivers/console/uart_console.c.obj
build output: [ 78%] Building C object zephyr/kernel/CMakeFiles/kernel.dir/timer.c.obj
build output: [ 80%] Building C object zephyr/CMakeFiles/zephyr.dir/drivers/gpio/gpio_esp32.c.obj
build output: [ 81%] Building C object zephyr/CMakeFiles/zephyr.dir/drivers/i2c/i2c_esp32.c.obj
build output: [ 83%] Building C object zephyr/CMakeFiles/zephyr.dir/drivers/pinmux/pinmux_esp32.c.obj
build output: [ 84%] Building C object zephyr/CMakeFiles/zephyr.dir/drivers/serial/uart_esp32.c.obj
build output: [ 86%] Building C object zephyr/CMakeFiles/zephyr.dir/drivers/timer/sys_clock_init.c.obj
build output: [ 87%] Building C object zephyr/CMakeFiles/zephyr.dir/drivers/timer/xtensa_sys_timer.c.obj
build output: [ 89%] Linking C static library libkernel.a
build output: [ 90%] Linking C static library libzephyr.a
build output: [ 90%] Built target kernel
build output: [ 90%] Built target zephyr
build output: Scanning dependencies of target zephyr_prebuilt
build output: [ 92%] Building C object zephyr/CMakeFiles/zephyr_prebuilt.dir/misc/empty_file.c.obj
build output: [ 93%] Linking C executable zephyr_prebuilt.elf
build output: /opt/xtensa-esp32-elf/xtensa-esp32-elf/lib/./libc.a(lib_a-assert.o):(.literal+0xc): undefined reference to `__getreent'
build output: /opt/xtensa-esp32-elf/xtensa-esp32-elf/lib/./libc.a(lib_a-assert.o): In function `__assert_func':
build output: /home/ivan/e/crosstool-NG/.build/src/newlib-2.2.0/newlib/libc/stdlib/assert.c:59: undefined reference to `__getreent'
build output: /opt/xtensa-esp32-elf/xtensa-esp32-elf/lib/./libc.a(lib_a-fiprintf.o): In function `fiprintf':
build output: /home/ivan/e/crosstool-NG/.build/src/newlib-2.2.0/newlib/libc/stdio/fiprintf.c:49: undefined reference to `__getreent'
build output: /opt/xtensa-esp32-elf/xtensa-esp32-elf/lib/./libc.a(lib_a-vfiprintf.o): In function `_vfiprintf_r':
build output: /home/ivan/e/crosstool-NG/.build/src/newlib-2.2.0/newlib/libc/stdio/vfprintf.c:1791: undefined reference to `__getreent'
build output: /opt/xtensa-esp32-elf/xtensa-esp32-elf/lib/./libc.a(lib_a-wsetup.o): In function `__swsetup_r':
build output: /home/ivan/e/crosstool-NG/.build/src/newlib-2.2.0/newlib/libc/stdio/wsetup.c:39: undefined reference to `__getreent'
build output: /opt/xtensa-esp32-elf/xtensa-esp32-elf/lib/./libc.a(lib_a-fflush.o):/home/ivan/e/crosstool-NG/.build/src/newlib-2.2.0/newlib/libc/stdio/fflush.c:293: more undefined references to `__getreent' follow
build output: /opt/xtensa-esp32-elf/xtensa-esp32-elf/lib/./libc.a(lib_a-freer.o):(.literal+0x14): undefined reference to `_sbrk_r'
build output: /opt/xtensa-esp32-elf/xtensa-esp32-elf/lib/./libc.a(lib_a-freer.o): In function `_malloc_trim_r':
build output: /home/ivan/e/crosstool-NG/.build/src/newlib-2.2.0/newlib/libc/stdlib/mallocr.c:3331: undefined reference to `_sbrk_r'
build output: /home/ivan/e/crosstool-NG/.build/src/newlib-2.2.0/newlib/libc/stdlib/mallocr.c:3340: undefined reference to `_sbrk_r'
build output: /home/ivan/e/crosstool-NG/.build/src/newlib-2.2.0/newlib/libc/stdlib/mallocr.c:3345: undefined reference to `_sbrk_r'
build output: /opt/xtensa-esp32-elf/xtensa-esp32-elf/lib/./libc.a(lib_a-locale.o): In function `_localeconv_r':
build output: /home/ivan/e/crosstool-NG/.build/src/newlib-2.2.0/newlib/libc/locale/locale.c:1023: undefined reference to `__getreent'
build output: /opt/xtensa-esp32-elf/xtensa-esp32-elf/lib/./libc.a(lib_a-locale.o): In function `setlocale':
build output: /home/ivan/e/crosstool-NG/.build/src/newlib-2.2.0/newlib/libc/locale/locale.c:1035: undefined reference to `__getreent'
build output: /opt/xtensa-esp32-elf/xtensa-esp32-elf/lib/./libc.a(lib_a-makebuf.o):(.literal+0x4): undefined reference to `_fstat_r'
build output: /opt/xtensa-esp32-elf/xtensa-esp32-elf/lib/./libc.a(lib_a-makebuf.o): In function `__smakebuf_r':
build output: /home/ivan/e/crosstool-NG/.build/src/newlib-2.2.0/newlib/libc/stdio/makebuf.c:59: undefined reference to `_fstat_r'
build output: /opt/xtensa-esp32-elf/xtensa-esp32-elf/lib/./libc.a(lib_a-mallocr.o): In function `malloc_extend_top':
build output: /home/ivan/e/crosstool-NG/.build/src/newlib-2.2.0/newlib/libc/stdlib/mallocr.c:2165: undefined reference to `_sbrk_r'
build output: /home/ivan/e/crosstool-NG/.build/src/newlib-2.2.0/newlib/libc/stdlib/mallocr.c:2202: undefined reference to `_sbrk_r'
build output: /opt/xtensa-esp32-elf/xtensa-esp32-elf/lib/./libc.a(lib_a-signal.o):(.literal+0x0): undefined reference to `_getpid_r'
build output: /opt/xtensa-esp32-elf/xtensa-esp32-elf/lib/./libc.a(lib_a-signal.o):(.literal+0x4): undefined reference to `_kill_r'
build output: /opt/xtensa-esp32-elf/xtensa-esp32-elf/lib/./libc.a(lib_a-signal.o): In function `_raise_r':
build output: /home/ivan/e/crosstool-NG/.build/src/newlib-2.2.0/newlib/libc/signal/signal.c:163: undefined reference to `_getpid_r'
build output: /home/ivan/e/crosstool-NG/.build/src/newlib-2.2.0/newlib/libc/signal/signal.c:163: undefined reference to `_kill_r'
build output: /opt/xtensa-esp32-elf/xtensa-esp32-elf/lib/./libc.a(lib_a-signal.o): In function `raise':
build output: /home/ivan/e/crosstool-NG/.build/src/newlib-2.2.0/newlib/libc/signal/signal.c:215: undefined reference to `__getreent'
build output: /opt/xtensa-esp32-elf/xtensa-esp32-elf/lib/./libc.a(lib_a-signal.o): In function `signal':
build output: /home/ivan/e/crosstool-NG/.build/src/newlib-2.2.0/newlib/libc/signal/signal.c:223: undefined reference to `__getreent'
build output: /opt/xtensa-esp32-elf/xtensa-esp32-elf/lib/./libc.a(lib_a-signal.o): In function `_init_signal':
build output: /home/ivan/e/crosstool-NG/.build/src/newlib-2.2.0/newlib/libc/signal/signal.c:229: undefined reference to `__getreent'
build output: /opt/xtensa-esp32-elf/xtensa-esp32-elf/lib/./libc.a(lib_a-signal.o): In function `__sigtramp':
build output: /home/ivan/e/crosstool-NG/.build/src/newlib-2.2.0/newlib/libc/signal/signal.c:235: undefined reference to `__getreent'
build output: /opt/xtensa-esp32-elf/xtensa-esp32-elf/lib/./libc.a(lib_a-stdio.o):(.literal+0x4): undefined reference to `_read_r'
build output: /opt/xtensa-esp32-elf/xtensa-esp32-elf/lib/./libc.a(lib_a-stdio.o):(.literal+0x8): undefined reference to `_lseek_r'
build output: /opt/xtensa-esp32-elf/xtensa-esp32-elf/lib/./libc.a(lib_a-stdio.o):(.literal+0xc): undefined reference to `_write_r'
build output: /opt/xtensa-esp32-elf/xtensa-esp32-elf/lib/./libc.a(lib_a-stdio.o):(.literal+0x10): undefined reference to `_close_r'
build output: /opt/xtensa-esp32-elf/xtensa-esp32-elf/lib/./libc.a(lib_a-stdio.o): In function `__sread':
build output: /home/ivan/e/crosstool-NG/.build/src/newlib-2.2.0/newlib/libc/stdio/stdio.c:48: undefined reference to `_read_r'
build output: /opt/xtensa-esp32-elf/xtensa-esp32-elf/lib/./libc.a(lib_a-stdio.o): In function `__swrite':
build output: /home/ivan/e/crosstool-NG/.build/src/newlib-2.2.0/newlib/libc/stdio/stdio.c:89: undefined reference to `_lseek_r'
build output: /home/ivan/e/crosstool-NG/.build/src/newlib-2.2.0/newlib/libc/stdio/stdio.c:97: undefined reference to `_write_r'
build output: /opt/xtensa-esp32-elf/xtensa-esp32-elf/lib/./libc.a(lib_a-stdio.o): In function `__sseek':
build output: /home/ivan/e/crosstool-NG/.build/src/newlib-2.2.0/newlib/libc/stdio/stdio.c:117: undefined reference to `_lseek_r'
build output: /opt/xtensa-esp32-elf/xtensa-esp32-elf/lib/./libc.a(lib_a-stdio.o): In function `__sclose':
build output: /home/ivan/e/crosstool-NG/.build/src/newlib-2.2.0/newlib/libc/stdio/stdio.c:135: undefined reference to `_close_r'
build output: /opt/xtensa-esp32-elf/xtensa-esp32-elf/lib/./libc.a(lib_a-wbuf.o): In function `__swbuf_r':
build output: /home/ivan/e/crosstool-NG/.build/src/newlib-2.2.0/newlib/libc/stdio/wbuf.c:82: undefined reference to `__getreent'
build output: /opt/xtensa-esp32-elf/xtensa-esp32-elf/lib/./libc.a(lib_a-wcrtomb.o): In function `_wcrtomb_r':
build output: /home/ivan/e/crosstool-NG/.build/src/newlib-2.2.0/newlib/libc/stdlib/wcrtomb.c:40: undefined reference to `__getreent'
build output: /opt/xtensa-esp32-elf/xtensa-esp32-elf/lib/./libc.a(isatty.o): In function `_isatty_r':
build output: /home/ivan/e/crosstool-NG/.build/src/newlib-2.2.0/newlib/libc/sys/xtensa/isatty.c:13: undefined reference to `_fstat_r'
build output: /opt/xtensa-esp32-elf/xtensa-esp32-elf/lib/./libc.a(lib_a-fclose.o): In function `_fclose_r':
build output: /home/ivan/e/crosstool-NG/.build/src/newlib-2.2.0/newlib/libc/stdio/fclose.c:114: undefined reference to `__getreent'
build output: collect2: error: ld returned 1 exit status
build output: make[3]: *** [zephyr/CMakeFiles/zephyr_prebuilt.dir/build.make:102: zephyr/zephyr_prebuilt.elf] Error 1
build output: make[2]: *** [CMakeFiles/Makefile2:542: zephyr/CMakeFiles/zephyr_prebuilt.dir/all] Error 2
build output: make[1]: *** [Makefile:84: all] Error 2
build failed
COMPLETION failed

**Comment by nashif** [comment]
same issue as #4705
