### ISSUE TITLE
libc no sources given warning emitted for all builds

### ISSUE THREAD

**Issue by nordicjm** [zephyrproject-rtos/zephyr#56243]
**Describe the bug**
Commit 672aeace88c6300fd7f8e7a53d12fbeb9ad815a0 has introduced an issue whereby for each build, the following warning is emitted:
```
CMake Warning at /tmp/aa/zephyr/CMakeLists.txt:828 (message):
  No SOURCES given to Zephyr library: lib__libc__common

  Excluding target from build.
```

This should be fixed

**To Reproduce**
Configure `hello_world` for `nrf52840dk_nrf52840`

**Expected behavior**
No warning to be emitted

**Impact**
Annoyance

**Environment (please complete the following information):**
 - Commit SHA or Version used: de81c48a244150c6ebc8422dcddb29a6bca4e322

**Comment by keith-packard** [comment]
I've stuck a commit into #56309 which should fix this issue.

**Comment by galak** [comment]
re-assigning to @keith-packard as he has a fix this in his PR.
