### ISSUE TITLE
Twister/build failure for os.mgmt.info_bt

### ISSUE THREAD

**Issue by ahedin25** [zephyrproject-rtos/zephyr#56248]
Twister fails on this pull request (https://github.com/zephyrproject-rtos/zephyr/pull/55768).  Last rebase was on ccd88a4b611ca4dfe3985709d3cd36021910a6c2.
I don't think it failed previously, but I didn't keep track of the starting SHA.

I get the same error on Linux with zephyr-sdk-0.15.2 with other boards.

west build -p -b nrf5340dk_nrf5340_cpunet -T /tests/subsys/mgmt/mcumgr/os_mgmt_info/os.mgmt.info_bt
west build -p -b nrf52dk_nrf52832 -T zephyr/tests/subsys/mgmt/mcumgr/os_mgmt_info/os.mgmt.info_bt

```
build/zephyr/misc/generated/extra_kconfig_options.conf:3: warning: malformed string literal in assignment to BT_DEVICE_NAME (defined at subsys/bluetooth/host/Kconfig:758). Assignment ignored.
Parsing /home/arbol/z1/zephyr/tests/subsys/mgmt/mcumgr/os_mgmt_info/Kconfig
Loaded configuration 'zephyr/boards/arm/nrf5340dk_nrf5340/nrf5340dk_nrf5340_cpunet_defconfig'

error: Aborting due to Kconfig warnings
```

**Comment by henrikbrixandersen** [comment]
Please use our bug template when reporting bugs. You need to edit this issue to include the needed information from https://github.com/zephyrproject-rtos/zephyr/blob/main/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by nordicjm** [comment]
@mbolivar-nordic @PerMac sounds like a west bug? Above tests work fine when using twister but when using west it is not copying the quotes from the .yml file:
```
    extra_configs:
      - CONFIG_BT=y
      - CONFIG_BT_DEVICE_NAME="a_bt_name"
```
But `build/zephyr/misc/generated/extra_kconfig_options.conf` has:
```
CONFIG_BT=y
CONFIG_BT_DEVICE_NAME=a_bt_name
```

**Comment by mbolivar-nordic** [comment]
> sounds like a west bug? Above tests work fine when using twister but when using west it is not copying the quotes from the .yml file:

probably; @nashif any idea what's going on here in the `west build -T` handling?
