### ISSUE TITLE
net: lwm2m: rd client stop hangs if rd client is suspended

### ISSUE THREAD

**Issue by chmielewskiandreas** [zephyrproject-rtos/zephyr#56254]
I have tried to integrate rd_client_pause/resume into our product again. Unfortunately I see another bug in its implementation. Unfortunately lwm2m_rd_client_stop with deregister-param set to true hangs if the rd_client is in suspended state. I already raised a discussion about this https://github.com/zephyrproject-rtos/zephyr/discussions/54478 some weeks ago.

@SeppoTakalo, can you take a look into that, please?

**Comment by chmielewskiandreas** [comment]
To fix this issue quickly I have opened a PR https://github.com/zephyrproject-rtos/zephyr/pull/56269

**Comment by SeppoTakalo** [comment]
@chmielewskiandreas please review https://github.com/zephyrproject-rtos/zephyr/pull/56564
