### ISSUE TITLE
mcp23xxx driver incorrectly assumes all chips in family have push-pull outputs

### ISSUE THREAD

**Issue by arbrauns** [zephyrproject-rtos/zephyr#56280]
**Describe the bug**

The `mcp23xxx` driver [only allows push-pull pins](https://github.com/zephyrproject-rtos/zephyr/blob/9c69f29d0d37aa608b575154696aba088fc2a15e/drivers/gpio/gpio_mcp23xxx.c#L182-L185). This is correct for the MCP23008, MCP23016 and MCP23017, but the MCP23009 and MCP23018 have open-drain outputs instead of push-pull outputs.

**Expected behavior**
The driver and device bindings should be adjusted to match the real hardware capabilities.

**Impact**
Currently, open-drain outputs have to be configured as if they were push-pull outputs, which can make the devicetree slightly confusing to read (e.g. `GPIO_ACTIVE_HIGH | GPIO_PULL_UP`, which should be `GPIO_OPEN_DRAIN | GPIO_PULL_UP`).

**Comment by henrikbrixandersen** [comment]
Please use our bug template when reporting bugs. You need to edit this issue to include the needed information from https://github.com/zephyrproject-rtos/zephyr/blob/main/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by arbrauns** [comment]
Hasn't fixed itself yet.

**Comment by henrikbrixandersen** [comment]
> Hasn't fixed itself yet.

If you have the hardware to test it, you are most welcome to submit a PR for fixing it.

**Comment by arbrauns** [comment]
Sure, I'll probably do that eventually, but it's not the top priority right now - if this issue wasn't here I'd definitely forget it though :)

**Comment by arbrauns** [comment]
I'll get to it eventually.

**Comment by arbrauns** [comment]
See #65797.

**Comment by arbrauns** [comment]
The fix PR hasn't magically merged itself yet.

**Comment by arbrauns** [comment]
PR is still open.

**Comment by arbrauns** [comment]
PR is *still* open with no relevant review.

**Comment by arbrauns** [comment]
Sometimes I dream of making the stale bot close its own miserable self
