### ISSUE TITLE
Some peripheral tests are failing if CONFIG_BT_EXT_ADV=n

### ISSUE THREAD

**Issue by sjanc** [zephyrproject-rtos/zephyr#56326]
**Describe the bug**
Some BLE qualification tests are failing if tester application is build without CONFIG_BT_EXT_ADV=y.
This seems to affect peripheral role privacy tests.

Affected tests:
GAP/BROB/BCST/BV-03-C
GAP/CONN/UCON/BV-06-C
GAP/PRIV/CONN/BV-10-C

There seems to be some discrepancy in host on how privacy and peripheral role works with and without ExtAdv enabled.
tester application doesn't have any CONFIG_BT_EXT_ADV dependent code and simply calls bt_le_adv_start().
Note that tester is always advertising with legacy PDUs 

**To Reproduce**

Build tester application with CONFIG_BT_EXT_ADV=n and execute any of mentioned qualification tests.

**Expected behavior**
Tests should pass regardless of CONFIG_BT_EXT_ADV being enabled or not.

**Comment by jori-nordic** [comment]
Hi @sjanc, PTS is not fast to install and setup, would you have any logs that you could attach to this issue?

**Comment by sjanc** [comment]
Hi,

Attaching logs from pass and failed runs for GAP/BROB/BCST/BV-03-C.
Only difference between those two is tester configuration prj.conf:
CONFIG_BT_EXT_ADV=y for pass
CONFIG_BT_EXT_ADV=n for fail

[GAP_BROB_BCST_BV_03_C_FAIL.zip](https://github.com/zephyrproject-rtos/zephyr/files/11286742/GAP_BROB_BCST_BV_03_C_FAIL.zip)
[GAP_BROB_BCST_BV_03_C_PASS.zip](https://github.com/zephyrproject-rtos/zephyr/files/11286743/GAP_BROB_BCST_BV_03_C_PASS.zip)
