### ISSUE TITLE
Optimize the CMake configuration time by reducing the time spent testing the toolchain

### ISSUE THREAD

**Issue by SebastianBoe** [zephyrproject-rtos/zephyr#5633]
valgrind shows that a significant amount of time[0] is spent on TryCompile. TryCompile is invoked when we test the toolchain to determine what flags it supports.

Intuitively, the toolchain feature set is very static and should not impact the build system performance as much as it is. In addition, TryCompile is very verbose.

You would think that either maintaining some sort of database for the supported toolchains or caching
the toolchain results outside of the build directory would be a fairly straightforward optimization to do.

[0] 14% of the CMake execution time is spent in TryCompile.
"valgrind --tool=callgrind cmake -Boe -Hsamples/hello_world -DBOARD=qemu_cortex_m3"

**Comment by SebastianBoe** [comment]
By set'ing

set(CMAKE_C_COMPILER ccache ${CMAKE_C_COMPILER})

I could observe that running CMake 

was reduced to 

real	0m0.862s

from

real	0m1.192s

which is a speedup of 40%, much more than what valgrind indicated.

This re-inforces that we should try to fix this performance issue. Perhaps using ccache (Unfortunately this does not help non-ccache users).

**Comment by marc-hb** [comment]
I just noticed while looking at strange cache bug #15551 that changing option parameters like for instance ${source_dir} in`-fmacro-prefix-map=${source_directory=..` regenerates brand new entries and a bit of noise in the cache. Suboptimal but I guess not big deal; just FYI.
