### ISSUE TITLE
mec172xmodular_assy6930 standalone fails to boot hello_world on zephy3.3 or mainline

### ISSUE THREAD

**Issue by galak** [zephyrproject-rtos/zephyr#56332]
Zephyr 3.3 or mainline don't boot hello_world on mec172xmodular_assy6930 when used in standalone.

Changing some of the boot params in spi_cfg seem to make it work:

```
diff --git a/boards/arm/mec172xmodular_assy6930/support/spi_cfg_4MBit.txt b/boards/arm/mec172xmodular_assy6930/support/spi_cfg_4MBit.txt
index 809e67b356..43debfe40a 100644
--- a/boards/arm/mec172xmodular_assy6930/support/spi_cfg_4MBit.txt
+++ b/boards/arm/mec172xmodular_assy6930/support/spi_cfg_4MBit.txt
@@ -16,8 +16,8 @@ BoardID = 0
 [IMAGE "0"]
 ImageLocation = 0x1000
 SpiFreqMHz = 24
-SpiReadCommand = Dual
-SpiDriveStrength = 4
+SpiReadCommand = Quad
+SpiDriveStrength = 8
```

**Comment by galak** [comment]
@scottwcpg, @albertofloyd fyi.

**Comment by scottwcpg** [comment]
@galak  If your 6930 board has the 1.8V Gigadevice GD25LR256 that had an issue with dual.  I will try to find the details

**Comment by galak** [comment]
@scottwcpg looks like MEC1723, REV B board, with Gigadevices GD25LR256.

**Comment by galak** [comment]
I have JP26 set to 1-2 for 1.8V since its a gigadevices chip.

**Comment by galak** [comment]
@scottwcpg any updates on this?

**Comment by scottwcpg** [comment]
Hi @galak 
The GigaDevice SPI flash on the MEC172x MECC card does not support dual mode. This issue was also seen by @albertofloyd at Intel.  I was informed a request was made of GigaDevice to release a public application note.  The work-around is to use Quad mode.  Application level code will need to implement the application note to switch the part to another mode.

**Comment by albertofloyd** [comment]
@galak only Dual to Quad change should be  required, the spi strength is only needed when using with RVP not in standalone mode. Do confirm
