### ISSUE TITLE
The dependency between the Kconfig source files and the Kconfig output is missing

### ISSUE THREAD

**Issue by SebastianBoe** [zephyrproject-rtos/zephyr#5634]
Editing prj.conf will correctly cause Kconfig to be re-executed when make is invoked. But editing Kconfig sources does not. The user must manually reconfigure (by calling cmake .. or make rebuild_cache).

### Solution proposal
Invoke

  set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS ${kconfig_source})

on all kconfig sources.

**Comment by ulfalizer** [comment]
Simplest would be to always execute it I think.

If `sync_deps()` (see https://github.com/zephyrproject-rtos/zephyr/issues/4951) is called before each build and some `fixdep`-like scheme is added (see the `sync_deps()` docstring in Kconfiglib), then you could also automatically rebuild just the files that reference Kconfig symbols that have changed.

**Comment by SebastianBoe** [comment]
The incremental build runtime is unacceptable if all incremental builds run CMake.

Do you see any issues with the solution proposal?

**Comment by carlescufi** [comment]
@SebastianBoe @ulfalizer did we ever come to a conclusion on this issue? Are we using `sync_deps()` or @SebastianBoe's proposal?

**Comment by ulfalizer** [comment]
Kconfiglib now makes a list of parsed Kconfig files available in `kconf.kconfig_filenames` at least. Might help, though it'd just be an optimization, as `sync_deps()` can detect all changes that matter.

See https://github.com/zephyrproject-rtos/zephyr/issues/4951 too.
