### ISSUE TITLE
Integrate ACPICA external module to enable full ACPI support

### ISSUE THREAD

**Issue by najumon1980** [zephyrproject-rtos/zephyr#56356]
## Origin

Name of project hosting the original open source code: https://www.acpica.org/
Link to the source: https://github.com/acpica/acpica

## Purpose

Currently Zephyr does not have an ACPI bus driver to support platforms which expose hardware resource and platform configuration details via acpi. This effort is to integrating acpica open-source project into Zephyr for enable acpi bus driver support.

## Mode of integration

The plan is to integrate the acpica external component as a module. 
The suggested repository name for the module is "acpica"

## Maintainership
najumon1980 (Najumon B.A)

## Pull Request

Zephyr mainline: https://github.com/zephyrproject-rtos/zephyr/pull/56347
Acpica open-source: https://github.com/acpica/acpica/pull/861

## Description

The effort here is for adding ACPI bus driver support for Zephyr using acpica open source project. ACPI bus driver use to discover and configure platform components, perform power management (e.g. putting unused hardware components to sleep), auto configuration (e.g. Plug and Play and hot swapping) etc. Though acpica support full-fledged acpi bus driver functionalities, current scope limited to device enumeration and retrieve acpi device resource such as MMIO address and IRQ details, PCI interrupt routing information etc.

Following are some of the details of ACPI bus driver functionalities:
- Enumerate PCI bus/bridge and acpi device such as WDT, RTC, GPIO, APIC, DMA etc.
- Enumerate device resources such as MMIO or IO address, IRQ details
- Retrieve IO configurations such as clk freq, boud rate, polarity etc. for SOC device like I2C, SPI, UART, SMBus etc.
- Bus and other config details for on board sensors
- Retrieve platform configuration such as PCI legacy interrupt routing, APIC
- Retrieve CPU configurations/Information
- Device/platform power management and configuration

ACPI will significantly reduce Zephyr porting effort on newer platforms since it will identify supported devices and cpu/platform/device resource and automatically configure them dynamically during system boot. Please note that most of current DTS information can be removed since acpi will provide those information on run time. The device and platform configuration for these platforms normally provided via BIOS. Hence user can go and modify them via BIOS menu which help to avoid re-build of Zephyr image.

Following block diagram depict overall Zephyr BSP architecture based on ACPI sub system:

Please note that "zephyr acpi bus interface" will provide a generic interface to other Zephyr sub systems/drivers and also provide some glue logics for abstract under lying acpica instantiate and complexity. The acpica is an OS-independent implementation of ACPI and hence OS Service layer will provide necessary logic to port acpica into Zephyr. The OS Service layer for Zephyr already upstreamed into acpica opensource tree.

![image](https://user-images.githubusercontent.com/42460060/229976049-95ed7d27-d151-4351-99ba-72f07219bcba.png)

## Dependencies

Acpica is an os independent open-source component which can easily integrated with any OS by adding os service layer  into it . This component will be required only if the platform need acpi bus driver support (platform support ACPI).

## Revision

master

## License

2-clause BSD license (https://www.acpica.org/Licensing)

**Comment by nashif** [comment]
approved by the TSC.
