### ISSUE TITLE
tests: kernel: device: test failing in CI for qemu_x86_tiny

### ISSUE THREAD

**Issue by cfriedt** [zephyrproject-rtos/zephyr#56414]
**Describe the bug**

The following test is currently failing in `main`:
```
west build -p auto -b qemu_x86_tiny@768 -t run -T tests/kernel/device/kernel.device.pm
```

Please also mention any information which could help others to understand
the problem you're facing:
 - What target platform are you using? `qemu_x86_tiny`
 - What have you tried to diagnose or workaround this issue? just a git bisect
 - Is this a regression? Yes.
 
 It seems to be broken as of 06c9bf47b37c0722559f3333c2e85240d4ecbddb but I'm not entirely sure why.
cc @mbolivar-nordic 

**To Reproduce**
1. `west build -p auto -b qemu_x86_tiny@768 -t run -T tests/kernel/device/kernel.device.pm`
2. See error

**Expected behavior**
Tests should pass

**Impact**
Breaking CI in `main`

**Logs and console output**
```
SeaBIOS (version rel-1.16.1-0-g3208b098f51a-prebuilt.qemu.org)
Booting from ROM..ASSERTION FAIL [page_frames_initialized] @ WEST_TOPDIR/zephyr/kernel/mmu.c:1325
        page fault at 0x40196266 happened too early
E: EAX: 0x00000001, EBX: 0x00009500, ECX: 0x00000000, EDX: 0x00000000
E: ESI: 0x00000000, EDI: 0x00001000, EBP: 0x401905ec, ESP: 0x401905e8
E: EFLAGS: 0x00000046 CS: 0x0008 CR3: 0x0016f000
E: call trace:
E: EIP: 0x4013d1db
E:      corrupted? (bp=0x401905ec)
E: >>> ZEPHYR FATAL ERROR 4: Kernel panic on CPU 0
E: Current thread: 0x40190728 (unknown)
E: Halting system
```

**Environment (please complete the following information):**
 - OS: Linux (CI)
 - Toolchain: SDK v0.16.0
 - Commit SHA or Version used: bf46f7351066c78cf5eb2d056fdfdfb182dab985

**Additional context**
git bisect steps
```
git bisect start HEAD v3.3.0 --
git bisect run twister -p qemu_x86_tiny@768 -s tests/kernel/device/kernel.device.pm
git bisect reset
```

**Comment by cfriedt** [comment]
This test isn't failing across the board, just on a single platform, so I've set it to medium, but if anyone thinks it should by high priority, please escalate.

**Comment by nordicjm** [comment]
Pinging @dcpleung as this issue seems to vanish when demand paging support is disabled.
