### ISSUE TITLE
devicetree: update comment in build/zephyr/include/generated/device_extern.h

### ISSUE THREAD

**Issue by erwango** [zephyrproject-rtos/zephyr#56425]
**Describe the bug**
Here is the content of generated file `include/generated/device_extern.h`:
```
#error The contents of this file are now implemented directly in zephyr/device.h.
```

From what I can observe device.h is not generated anymore, unless this refers to `include/zephyr/device.h`, in which case comment should be updated.
Alt option: do not generate anymore

**To Reproduce**
1- build a sample
2- Look into  build/zephyr/include/generated/device_extern.h

**Comment by gmarull** [comment]
`device.h` has never been generated. This comment means that `device_extern.h` is no longer required because `zephyr/device.h` contains the necessary pieces to achieve the same goal. I'm not sure what needs to be fixed here.
