### ISSUE TITLE
samples: sensors: fxas21002 sample overflows on warp7_m4

### ISSUE THREAD

**Issue by PerMac** [zephyrproject-rtos/zephyr#56455]
**Describe the bug**
Sample sample.sensor.fxas21002  from samples/sensor/fxas21002 overflows flash on warp7_m4. It is an integration platform, hence should be buildable. 

Please also mention any information which could help others to understand
the problem you're facing:
 - What target platform are you using?
   - warp7_m4
 - What have you tried to diagnose or workaround this issue?
   - no 
 - Is this a regression? If yes, have you been able to "git bisect" it to a
   specific commit?
   - It is possible that the sample is overflowing for I while since skips are not monitored. I haven't run git bisect

**To Reproduce**
1. `scripts/twister -T samples/sensor/fxas21002/ -G -v`

**Expected behavior**
Sample builds without overflows

**Impact**
Not clear

**Logs and console output**
` 1/1 warp7_m4                  samples/sensor/fxas21002/sample.sensor.fxas21002   SKIPPED (FLASH overflow)`

**Environment (please complete the following information):**
 - Ubuntu 18.04
 - zephyr sdk, 0.15.0
 - Version zephyr-v3.3.0-1953-g6ee9e72909e0

**Additional context**
Error was exposed with https://github.com/zephyrproject-rtos/zephyr/pull/55986 which turns overflow skips to errors on integration platforms. That PR was unblocked by choosing the other platform from allow list as an integration one.

**Comment by jgl-meta** [comment]
Can you just remove this from the platform?
