### ISSUE TITLE
rtio: Sign compare error during project build with SPI enabled. 

### ISSUE THREAD

**Issue by Zzzwierzak** [zephyrproject-rtos/zephyr#56597]
**Describe the bug**
Compiling project with SPI enabled and -Werror and -Wsign-compare ends with error in rtio header. 

**To Reproduce**
1. In spi_loopback ztest CMakeList file add :
set(CMAKE_CXX_FLAGS "-Wall -Werror -Wsign-compare")
set(CMAKE_C_FLAGS "${CMAKE_CXX_FLAGS}")
2. Build test for nucleo_wb55rg or other STM

**Expected behavior**
Build successful.

**Logs and console output**
/home/zephyr/include/zephyr/rtio/rtio.h: In function 'rtio_cqe* rtio_cqe_consume(rtio*)':
/home/zephyr/include/zephyr/rtio/rtio_spsc.h:222:44: error: comparison of integer expressions of different signedness: 'long unsigned int' and 'atomic_val_t' {aka 'long int'} [-Werror=sign-compare]
  222 |                 bool has_consumable = (idx != atomic_get(&(spsc)->_spsc.in));                      \

**Environment:**
 - OS: Ubuntu 22.04
 - Toolchain: Zephyr SDK 16.0
 - Commit SHA : 6fe83ea810ca35ca21bc3bc460dbc0fde332a559

**Comment by teburd** [comment]
Thanks for the report @Zzzwierzak , will see about getting this fixed
