### ISSUE TITLE
[v2.7] application booted from v3.x mcuboot uptime resets

### ISSUE THREAD

**Issue by nordicjm** [zephyrproject-rtos/zephyr#56604]
**Describe the bug**
It seems that with https://github.com/zephyrproject-rtos/zephyr/pull/56528 applied to mcuboot, a 2.7-built application which uses uptime will ungracefully seem to lose it's uptime value after about 8.5 minutes, that is, the device will continue functioning but e.g. using `kernel uptime` from the shell will wrongly output an uptime value of seconds rather than 10 minutes which is wrong.

**To Reproduce**

 - Build mcuboot with above PR for nrf52840dk_nrf52840 and flash to board
 - Checkout v2.7-branch, west update, then build samples/subsys/shell/shell_module with mcuboot enabled and flash
 - Check `kernel uptime` and `kernel threads` output every minute, after the 8.5 minute mark, seemingly the uptime has set to 0.

**Expected behavior**
Uptime to continue incrementing

**Impact**
Showstopper, applications seemingly are unaware of the true uptime. Note that this only happens when older images e.g. 2.7 are booted from new versions of mcuboot e.g. from zephyr 3.x onwards

**Environment (please complete the following information):**
 - Commit SHA or Version used: `main` with above PR for mcuboot and `v2.7-branch` for application

**Comment by cfriedt** [comment]
@nordicjm - any chance you could provide a fix?

**Comment by nordicjm** [comment]
> @nordicjm - any chance you could provide a fix?

Not likely, can't determine cause

**Comment by nordicjm** [comment]
@anangl is there a PR that needs to be ported?

**Comment by anangl** [comment]
> @anangl is there a PR that needs to be ported?

I have no idea, to be honest. I don't know what could cause such behavior.

**Comment by nordicjm** [comment]
Assigning to @anangl and @nordic-krch it seems to be something wrong with `drivers/timer/nrf_rtc_timer.c` and that file has been vastly changed in 3.x, if I add debug out then it seems to prevent the issue (albeit I get a continuous stream of output) so maybe something is not being handled properly like an overflow or next count or something.

**Comment by nordicjm** [comment]
Ping on @anangl and @nordic-krch

**Comment by anangl** [comment]
The issue is not actually related to mcuboot. It can be also observed in `samples/subsys/shell/shell_module` built with `v2.7-branch` without using mcuboot. The behavior is caused by specific construction of the application. Details in #59154.
