### ISSUE TITLE
[RFC] Add extensible version infrastructure

### ISSUE THREAD

**Issue by nordicjm** [zephyrproject-rtos/zephyr#56605]
### Problem description

At present, there is a way that applications can get various versions of things in zephyhr - they can get the version of zephyr that is checked out, they can get the version of a board that is being compiled for, but from an application perspective there is no unified way of getting a version of the application itself and users that want to have such a system in their applications must do so out of tree. The main bootloader supported in zephyr is MCUboot, which supports a modified semantic versioning system of a.b.c+d (a = major, b = minor, c = patch, d = build) where each of these fields is numeric. To date in zephyr, all applications are signed with version 0.0.0+0 for signing is enabled in a build, it can be manually over-wrote by including the desired version in the MCUboot signing options Kconfig variable, but similarly as mentioned before, this is a string that is provided directly the imgtool command line option and cannot be easily used or accessed by applications.

Therefore the idea would be to have a new standardised version system in zephyr *for applications* that can be easily set or read from the build system, singing system and application code itself that can (in future) be extended or replaced with out of tree code so it can be used freely.

### Proposed change

I suggest that there be a new Kconfig added which specifies the version of the application, the format of this field would not be inherently restricted to any specific format but format restrictions could be applied depending upon the signing system used if it has strict requirements (i.e. imgtool does not support alphanumeric characters as part of a version). This version can default to `0.0.0+0` for semantic versioning and to stay constant with how things are set in zephyr already. A cmake file can then be used to generate an (optional) include file with the version string and also split the individual components up. The Kconfig itself can be used for e.g. imgtool to sign when the application is generated.

## Detailed RFC

Similar to the new support for external/out of tree replacement of the zephyr signing tasks, this system can be fully replaced if users so wish - as an example, a user might have a bootloader which takes just a single integer as the version, they can replace the cmake script which reads the Kconfig and generates the output file to customise it however they see fit, or supply it to their custom signing applications, by doing it like this and keeping it unlinked from the kernel version (and kernel version file) it allows complete flexibility for expansion by users without being limited to a set format.

The choice of Kconfig for the version is to allow for multiple different builds in the same application folder depending upon configuration or build type, it can also be set dynamically by the build system e.g. CI automatically incrementing the version when it performs a build. It would also allow the version of a zephyr application to be over-wrote without having to fork it, for example MCUboot could have a version set which users might want to change to their own scheme or increment the version because they've added a custom zephyr module/board/arch/soc without having changed the MCUboot base code/repository.

### Concerns and Unresolved Questions

How to get/store the version, if it should be inherently tied between an application version and the version provided to the imgtool/other tool application (if anyone can provide a valid reason/use case whereby they build an application and embed a version to it and the version that they use with imgtool when signing that application is **different** to the actual application version, I'd like to hear why. Simply saying "because" is not a valid reason as to why this would be a required feature)

## Alternatives

Let users do as they currently do and deal with everything themselves - not a good option

**Comment by nordicjm** [comment]
Kconfig initial test PR: https://github.com/zephyrproject-rtos/zephyr/pull/55814
Alternative version file test PR: https://github.com/zephyrproject-rtos/zephyr/pull/56141

**Comment by Laczen** [comment]
@nordicjm, from your RFC it is clear that there should be some definition of `CONFIG_MCUBOOT_APP_VERSION` that is used for signing an application.

I don't understand the need to promote this to an application version.

**Comment by tejlmand** [comment]
as stated here:
> @tejlmand @nashif: too MCUboot-centered, let's make this more generic, decouple it from imgtool and MCUboot

ref: https://github.com/zephyrproject-rtos/zephyr/pull/55814#issuecomment-1496169537

this RFC is still too imgtool centric in its description as to why an application version should be introduced.

Many users of Zephyr are interested in an application version so it should be possible to describe such a feature for itself.


> the format of this field would not be inherently restricted to any specific format but format restrictions could be applied depending upon the signing system used if it has strict requirements (i.e. imgtool does not support alphanumeric characters as part of a version).

I strongly disagree here.
Zephyr should decide how an application version format can described, and users should be able to choose the fields they like to use semantic versioning, use of pre-release fields, like `rcX`.
If a signing tool has special restrictions compared to the version infrastructure provided by Zephyr, then it's the responsibility of such tool configuration to use just the portions of Zephyr app version that it understands, for example the `major.minor.patch` of such app version without the pre-release information.

No tool should restrict the version format that Zephyr version infrastructure supports.
Zephyr community should decide the version format we want to support, and then tools must use the field parts they understand or have their own version setting.

**Comment by Laczen** [comment]
@tejlmand, I agree that there should be no restriction on the format of the application version, but I disagree that zephyr should decide on the application version format. This should be left to the user.

There is a very easy way out for this problem: define a `CONFIG_MCUBOOT_APP_VERSION` (as proposed by @nordicjm) and a `CONFIG_ZEPHYR_APP_VERSION` (as proposed by @tejlmand), ... and set (configurable) what is wanted into a `CONFIG_APPLICATION_VERSION`. This `CONFIG_APPLICATION_VERSION` can then be used by the user in reporting or storing the application version using the bindesc PR (##54464). For the signing `CONFIG_MCUBOOT_APP_VERSION` can be used, for something else the `CONFIG_ZEPHYR_APP_VERSION` could be used. When users wish to deviate from the proposed standards they can be defining there own `CONFIG_APPLICATION_VERSION`.

For applications that are using mcuboot the `CONFIG_APPLICATION_VERSION` could default be set to `CONFIG_MCUBOOT_APP_VERSION`.

For applications that are not using mcuboot the `CONFIG_APPLICATION_VERSION` could default be set to `CONFIG_ZEPHYR_APP_VERSION`.

**Comment by nordicjm** [comment]
> If a signing tool has special restrictions compared to the version infrastructure provided by Zephyr, then it's the responsibility of such tool configuration to use just the portions of Zephyr app version that it understands, for example the `major.minor.patch` of such app version without the pre-release information.

And this is where it causes a problem, if there is a bootloader which has one integer field for a version, this would mean that the major version of the application would be used. Now if we use an example based on a very popular piece of software, let's say windows 10, that has 14 major versions (to date) each of which must have thousands of minor versions - so we're saying it's fine to just completely bin the minor version because it's not needed? I think end users might disagree with that view, I know I do.

**Comment by tejlmand** [comment]
>  I think end users might disagree with that view, I know I do.

i'm leaving it for the end-user to decide.
End users create their application and decides their versioning and their signing tool.

If the sign tool only supports a single digit and application version infrastructure supports `major.minor.patch-preRelease`, then the user must decide whether to use all fields or just a subset. Or if the signing tool should use a completely different numbering scheme. **That is for the user to decide**.

To me it appears that if the signing tool has special restrictions, then you want the Zephyr's app version infrastructure to be limited.
I disagree on that. Let the user decide. For the signing tool Zephyr natively supports and where the tool doesn't support all fields, there we can default the sign version of the tool based on a subset of app version.
And then it is for the user developing an application to decide if the app version only should use the fields supported by the tool, or how the signing version should be configured.

@nordicjm that means that in your case, you can choose to just use the `major.minor.patch` in your application, and imgtool will use those fields. No one forces you to use `-preRelease` field.

Another user can decide to use `major.minor.pacth-rcX` and if they are happy that imgtool uses only the` major.minor.patch` portion for signing, then everything is fine.
If they are unhappy, they must decide whether to only use `major.minor.patch` (as @nordicjm would do) or set the imgtool Kconfig sign version to what they want.

That has the benefit of re-using existing version infrastructure, and have a dedicated imgtool sign version with a sane default value.

I prefer having a good default value that will suit users needing just `major.minor.patch` with imgtool, while still allow end-users that wants additional app version information like `-rcX` to do so.
And I'm highly in favor of just a single implementation for creation of version header files and CMake variable handling, instead of multiple implementations.

**Comment by nordicjm** [comment]
> Building on that, we should also consider how to embed the version in the binary header, so we can verify the version of a built binary.

@yonsch has a PR for adding binary descriptor support, it gets the version that it embeds from Kconfig: https://github.com/zephyrproject-rtos/zephyr/pull/54464/files#diff-cc6728571822866d8ccc320879d622948d055562d5affed1c824e0cc88addfa0
