### ISSUE TITLE
arm-clang linker sets `__data_region_end` incorrectly

### ISSUE THREAD

**Issue by galak** [zephyrproject-rtos/zephyr#56614]
When linking `tests/misc/iterable_sections` the `__data_region_end` symbols isn't set correctly.

In `armlink_symbol_steering.steer` the symbol gets set:

`RESOLVE __data_region_end AS Image$$test_ram2_area$$Limit`

However, the section that is linked is actual `test_ram2_area_100`.

**Comment by galak** [comment]
https://github.com/zephyrproject-rtos/zephyr/pull/56615 is needed to demonstrate the issue described here.

**Comment by carlescufi** [comment]
Could this be related to https://github.com/zephyrproject-rtos/zephyr/pull/56615 ?
