### ISSUE TITLE
Introduce a Battery Charging API

### ISSUE THREAD

**Issue by rriveramcrus** [zephyrproject-rtos/zephyr#56635]
## Introduction

Add a kernel device driver API for battery charging control and status reporting.

### Problem description

Charging devices are application specific power converters with built in
protection and sensing for safe battery charging and system power
delivery. ~~There is currently no suitable subsystem, API, or example of a
charging IC in Zephyr.~~ Some out-of-tree charging drivers leverage the sensor
APIs channels and attributes. While this approach is suitable for more simple
charging applications and platforms, more complicated power trees could have
multiple charging ICs, a fuel gauge, power muxes, and input source detection
components. These more complicated power trees require inter and intra subsystem
communication via the host controller running Zephyr.

### Proposed change

Adding a battery charging device driver API that facilitates communication to the necessary components of the power tree to complete a charge cycle. This proposed subsystem would be akin to the recently merged fuel gauge subsystem (#44847).

#### MVP

As an MVP we'll have a simple setter/getter style API that is similar to the
fuel gauge API.

This will create a starting API that is semantically specific to kernel charger
drivers.

A~~n external draft PR ([Creates Charging
Subsystem](https://github.com/CirrusLogic/zephyr-drivers/pull/2))~~ PR (#56666)
is available that resembles the Zephyr fuel gauge API and the Linux mainline
power supply subsystem ([Linux Kernel's power supply subsystem
documentation](https://docs.kernel.org/power/power_supply_class.html)).

#### Future Work that will happen after the MVP PR

* Additional drivers
* Additonal properties
* Some kind of trigger/alert/callback mechanism specific to chargers (though
  usuallying charging is handled by a client charger loop). This would allow
  clients to have the driver call specific code based on some kind of trigger
  mechanism.
	
#### Example Charging Task Loop ####

The example below shows how a client of the charging API would create a task loop to execute a charging cycle.

The host must initialize the charging device by configuring its operating limits according to the battery pack specifications and system requirements.

Once configured, the host can enter the charging task loop. The charging task loop is a client of the charging API. The host can poll or be notified of the charger’s online status by requesting the state from the API. An online status indicates that the charger is supplied with external power and should proceed with making use of the power available.

Based on the state-of-charge (SoC) and the state-of-health (SoH) of the battery pack, the host will determine whether or not to attempt executing a charging cycle on the battery pack. The host's involvement in the charging cycle depends on the autonomy of the charging device and the system’s requirements.

A charge cycle ends via charge termination, power source removal, or a fault condition. The host must determine what action to take, if-any, and proceed to the appropriate state of the charging task loop.

##### Main Charger Task Loop #####

```c
/* Client usage */
int charge_task_main(void) 
{
	const struct device *const fg_dev = DEVICE_DT_GET_ANY(fuel_gauge);
	const struct device *const chg_dev = DEVICE_DT_GET_ANY(charger);
	struct charger_get_property props[] = {
		{
			.property_type = CHARGER_PROP_ONLINE,
		},
	};
	int ret;

	while (1) {
		ret = charger_get_prop(fixture->dev, props, ARRAY_SIZE(props));
		if (ret < 0) {
			LOG_ERR("Failed to get charger online status!\n");
		}

		if (props[0].value != CHARGER_ONLINE_OFFLINE) {
			ret = charge_task_enter_cycle(chg_dev, fg_dev);
			if (ret < 0) {
				LOG_ERR("Failed to enter charge cycle!\n");
			}
		}
	}
}

```

##### Enter Charge Cycle #####

```c
/* Client usage */
int charge_task_enter_cycle(const struct device *const chg_dev,
						const struct device *const fg_dev)
{
	struct charger_get_property get_props[] = {
		{
			.property_type = CHARGER_PROP_STATUS,
		},
		{
			.property_type = CHARGER_PROP_HEALTH,
		},
	};
	struct charger_set_property set_props[] = {
		{
			.property_type = CHARGER_PROP_STATUS,
		},
	};
	int ret;

	ret = charger_get_prop(fixture->dev, get_props, ARRAY_SIZE(get_props));
	if (ret < 0) {
		LOG_ERR("Failed to check charge cycle readiness");
	}

	if (get_props[0].value == CHARGER_STATUS_CHARGING) {
		return charge_task_exit_cycle(chg_dev, fg_dev);
	} else if (get_props[1].value == CHARGER_HEALTH_GOOD) {
		ret = charger_set_prop(fixture->dev, set_props, ARRAY_SIZE(set_props));
		if (ret < 0) {
			LOG_ERR("Failed to set charging");
			return -1;
		}
		return charge_task_exit_cycle(chg_dev, fg_dev);
	} else {
		return -1;
	}

	/* 
 	 * Alternatively, do something like adaptive charging while checking the 
	 * battery capacity through the fuel gauge API
	 */

	return 0;
}
```

##### Exit Charge Cycle #####

```c
/* Client usage */
int charge_task_exit_cycle(const struct device *const chg_dev,
					     const struct device *const fg_dev)
{
	struct charger_set_property get_props[] = {
		{
			.property_type = CHARGER_PROP_ONLINE,
		},
		{
			.property_type = CHARGER_PROP_STATUS,
		},
	};
	int ret;

	ret = charger_get_prop(fixture->dev, get_props, ARRAY_SIZE(get_props));
	if (ret < 0) {
		LOG_ERR("Failed to check charge cycle state");
	}

	while (props[1].value == CHARGER_STATUS_CHARGING ||
				props[1].value == CHARGER_STATUS_FULL) {
		ret = charger_get_prop(fixture->dev, get_props, ARRAY_SIZE(get_props));
		if (ret < 0) {
			LOG_ERR("Failed to check charge cycle state");
		}
	}

	if (props[0].value == CHARGER_ONLINE_OFFLINE) {
		return 0;
	}

	return -1;
}


```

### Status Quo

Pros
- No additional code base or complexity

Cons
- No true home for charging ICs
- Power Supply Subsystem remains incomplete

**Comment by nashif** [comment]
@aaronemassey @teburd  FYI

**Comment by nashif** [comment]
@rriveramcrus

> An external draft PR (https://github.com/CirrusLogic/zephyr-drivers/pull/2)

Maybe post this against the zephyr repo to get more visibility and reviews? Thank you for the posting this RFC and sharing the link to the PR.

**Comment by teburd** [comment]
I think this could slot right in given the diagram @aaronemassey provided in the linked RFC (#44847) which is great.

It may require some tweaks and such but the premise looks like a good one to me.

Please send the PR to the main tree so we can look and review.

**Comment by rriveramcrus** [comment]
Created a proper PR, I'm going to go ahead and close the original external PR.
