### ISSUE TITLE
tests/drivers/uart/uart_async_api fails with CONFIG_TIMESLICING

### ISSUE THREAD

**Issue by FRASTM** [zephyrproject-rtos/zephyr#56650]
**Describe the bug**
Running the tests/drivers/uart/uart_async_api/ on the nucleo_f103rb target is failing
in the test_write_abort testcase

--> when aborting the uart Tx, more char then were received as reported by the test_write_abort_callback

Please also mention any information which could help others to understand
the problem you're facing:
The  commit 524ac8a29a2f8b93510826593c25cee5117b9efa from PR https://github.com/zephyrproject-rtos/zephyr/pull/56441
has introduced a regression on the nucleo_f103rb

**To Reproduce**
1. west build -p auto -b nucleo_f103rb tests/drivers/uart/uart_async_api/
2. west flash
3. See error

**Expected behavior**
Test PASSED

**Impact**
CI failure

**Logs and console output**
```
START - test_write_abort

    Assertion failed at WEST_TOPDIR/zephyr/tests/drivers/uart/uart_async_api/src/test_uart_async.c:526: uart_async_write_abort_test_write_abort: (sent not equal to received)
Sent is not equal to received.
 FAIL - test_write_abort in 0.120 seconds
===================================================================
```                                                                    

**Environment (please complete the following information):**
 - OS: ubuntu
 - zephyr-sdk-0.15.2
 - Commit SHA : 7338333274869182ceea5972fc77a23bc4056238

**Additional context**
testcase PASSED when the 
`CONFIG_SYS_CLOCK_TICKS_PER_SEC=1000`
_or_ when the 
`CONFIG_TIMESLICING=n`

**Comment by jhedberg** [comment]
@erwango @FRASTM any progress on this issue? It keep getting the Stale label added.
