### ISSUE TITLE
posix: SCHED_RR valid thread priorities

### ISSUE THREAD

**Issue by ambroise-arm** [zephyrproject-rtos/zephyr#56729]
**Describe the bug**
Zephyr does not correctly advertize the minimum acceptable priority value that can be used with its posix threads when using `SCHED_RR`.

Calling `sched_get_priority_min` returns 0: https://github.com/zephyrproject-rtos/zephyr/blob/d5f83d2a7f1d3c7031bc2eec6b72e7261234bcba/lib/posix/pthread_sched.c#L39

But looking at `posix_to_zephyr_priority` (used by `pthread_create`), 0 is not an acceptable value as it translates to a Zephyr thread priority of `CONFIG_NUM_PREEMPT_PRIORITIES`: https://github.com/zephyrproject-rtos/zephyr/blob/d5f83d2a7f1d3c7031bc2eec6b72e7261234bcba/lib/posix/pthread.c#L92 which fails on the following assert when using the Zephyr test framework: https://github.com/zephyrproject-rtos/zephyr/blob/d5f83d2a7f1d3c7031bc2eec6b72e7261234bcba/kernel/thread.c#L536

Note that the priority set by `pthread_attr_init` is 1, so it isn't an issue when leaving the default thread priority. But this value looks arbitrary: https://github.com/zephyrproject-rtos/zephyr/blob/d5f83d2a7f1d3c7031bc2eec6b72e7261234bcba/lib/posix/pthread.c#L21

**To Reproduce**
1. Use `CONFIG_PREEMPT_ENABLED=y` in order to get `SCHED_RR`.
2. Use `CONFIG_ZTEST=y` in order to get the kernel asserts.
3. Have something like the following:
```c
pthread_attr_t attr;
struct sched_param sched_param;
sched_param.sched_priority = sched_get_priority_min();
pthread_attr_init(&attr);
pthread_attr_setschedparam(&attr, &sched_param);
pthread_create(..., &attr, ...);
```

**Expected behavior**
No assert failed when using a priority advertized by Zephyr as being valid.

**Impact**
Annoyance

**Logs and console output**
With `CONFIG_NUM_PREEMPT_PRIORITIES=15`:
```
ASSERTION FAIL [((((prio)) == 15 && z_is_idle_thread_entry((entry))) || (((15 - 1) >= ((-16))) && ((prio)) >= ((-16)) && ((prio)) <= (15 - 1)))] @ WEST_TOPDIR/zephyr/kernel/thread.c:536
	invalid priority (15); allowed range: 14 to -16
```

**Environment (please complete the following information):**
Tested on tag zephyr-v3.3.0, looks still relevant on tip of main as of the time of writing.

**Additional context**
N/A

cc @PatrickM-ZS

**Comment by cfriedt** [comment]
@ambroise-arm - would it help to have the `sysconf()` function available? IIRC there are some keys that can be used to query priority levels.

A sysconf enhancement issue was created here #56670 a couple of days ago.
