### ISSUE TITLE
sample project mentioned in the doc no longer exists

### ISSUE THREAD

**Issue by botbotty** [zephyrproject-rtos/zephyr#56962]
The doc says:
https://github.com/zephyrproject-rtos/zephyr/blob/f5b7752c64eba16bd00b45d920e78f2b2888ef5b/doc/kernel/code-relocation.rst?plain=1#L134-L140

but `$ZEPHYR_BASE/samples/application_development/code_relocation` does not exist

**Comment by nordicjm** [comment]
Indeed it seems that it was replaced in https://github.com/zephyrproject-rtos/zephyr/pull/47771 with tests/application_development/code_relocation

@carlocaione is it a drop-in replacement that functions the same? Should the path in the documentation just be updated or does it operate differently?

**Comment by carlocaione** [comment]
> @carlocaione is it a drop-in replacement that functions the same? Should the path in the documentation just be updated or does it operate differently?

Yes, that should be the same code just in a "test form".
