### ISSUE TITLE
gpio: some drivers still use GPIO_PORT_PIN_MASK_FROM_NGPIOS macro the old way

### ISSUE THREAD

**Issue by avolkov-1221** [zephyrproject-rtos/zephyr#56999]
GPIO drivers **drivers/gpio/gpio_ite_it8xxx2.c** and  **drivers/gpio/gpio_kscan_ite_it8xxx2.c** still use GPIO_PORT_PIN_MASK_FROM_NGPIOS macro the old way, as shown below:

        .port_pin_mask = GPIO_PORT_PIN_MASK_FROM_NGPIOS(              \
                           DT_INST_PROP(inst, ngpios))

while this usage has been deprecated and replaced by the newer style (in v2.3.0):

        .port_pin_mask =  GPIO_PORT_PIN_MASK_FROM_DT_INST(inst)             \

Or, even better, in the latest way:

        .port_pin_mask =  GPIO_PORT_PIN_MASK_FROM_DT_INST(inst)             \

As result driver are ignoring handling of the 'gpio-reserved-ranges' DT property value.

The patch is attached.

[gpio_ite_fix.txt](https://github.com/zephyrproject-rtos/zephyr/files/11264896/gpio_ite_fix.txt)

**Comment by nordicjm** [comment]
> The patch is attached.

We do not accept patches submitted like this, can you submit a PR with the fix?

**Comment by avolkov-1221** [comment]
Hello Jamie,
Actually the diff is a part of PR  https://github.com/zephyrproject-rtos/zephyr/pull/56295 , it was sent as an example of the problem solution.

**Comment by avolkov-1221** [comment]
BTW should I create the issues for another drivers affected the same problem?

**Comment by nordicjm** [comment]
> BTW should I create the issues for another drivers affected the same problem?

If there's other drivers with the same problem, yes

**Comment by henrikbrixandersen** [comment]
Please beware that `GPIO_PORT_PIN_MASK_FROM_NGPIOS()` is not deprecated in any way, so it is perfectly okay for a driver to use it.

**Comment by avolkov-1221** [comment]
Ok, I've 'un-deprecated' it. Could you review the last commit?
