### ISSUE TITLE
can: incorrect RTR flag handling in incoming frames

### ISSUE THREAD

**Issue by avolkov-1221** [zephyrproject-rtos/zephyr#57002]
Hello @henrikbrixandersen, @alexanderwachter, @martinjaeger 

I've just discovered that almost all CAN bus drivers assume that an incoming CAN frame with the RTR flag has a valid payload and copies data from FIFOs/registers up onto the stack.

Unfortunately this behavior is incorrect, since RTR mean that some data should be transferred FROM the node, not TO.

Thus, trying to copy CAN's frame data in the case of RTR is nothing but a waste of resources at best, or a security problem at worst ("disclose sensitive data"), since the payload from some old frame will be copied almost everywhere and/or machine check can be raised on some odd hardware.

Regards
Andrey VOLKOV
Linux Socketcan co-founder

**Comment by avolkov-1221** [comment]
Hi @henrikbrixandersen,

I also checked the sending routines a little harder, and the situation there is also "not so good": almost all drivers are trying to send data while  RTR is active.

Unfortunately this can cause an almost guaranteed panic, since the actual payload length is 0 (so possible "read out of the buffer boundary" case). Luckily for now, almost all current drivers pre-allocate packets with a maximum payload length, so you (I mean the team) have not seen this problem before and why it's probably not so critical. Meanwhile this is not the case when the device acts as a CAN router, then both incoming and outgoing traffic will contain RTR packets with zero payload in the Zephyr's CAN stack. Those, we will have a classic ping of death.

I've seen such situation before on Linux when someone from Freescale broke my MSCAN driver in their BSP by "optimizing" the RTR flag check.

**Comment by henrikbrixandersen** [comment]
Thank you for reporting these findings.

> I've just discovered that almost all CAN bus drivers assume that an incoming CAN frame with the RTR flag has a valid payload and copies data from FIFOs/registers up onto the stack.
> 
> Unfortunately this behavior is incorrect, since RTR mean that some data should be transferred FROM the node, not TO.

Right.

> Thus, trying to copy CAN's frame data in the case of RTR is nothing but a waste of resources at best, or a security problem at worst ("disclose sensitive data"), since the payload from some old frame will be copied almost everywhere and/or machine check can be raised on some odd hardware.

Zephyr is not a "multi-user" system, so the security problem is more theoretical than practical. However, we should not read potentially uninitialized data from the CAN controller MB/FIFO.

> I also checked the sending routines a little harder, and the situation there is also "not so good": almost all drivers are trying to send data while RTR is active.

Right.

> Unfortunately this can cause an almost guaranteed panic, since the actual payload length is 0 (so possible "read out of the buffer boundary" case). Luckily for now, almost all current drivers pre-allocate packets with a maximum payload length, so you (I mean the team) have not seen this problem before and why it's probably not so critical. Meanwhile this is not the case when the device acts as a CAN router, then both incoming and outgoing traffic will contain RTR packets with zero payload in the Zephyr's CAN stack. Those, we will have a classic ping of death.

In Zephyr `struct can_frame` is always allocated with full data size, so reading the data buffer, even for RTR frames, will not lead to a panic. However, it might result in writing uninitialized data to the CAN controller MB/FIFO, which should not happen.

I will look into providing a fix.

**Comment by avolkov-1221** [comment]
Under the "CAN router" I mean the following usage scenario:
 1. the chip with Zephir is receiving raw CAN frames from any other interface but CAN, as raw packets stream;
 2. the recv thread is calling the can_send for above stream without any intermediate copy;
 3. error. Out of bound reading for RTR packet.
 
BTW in theory the security problem could arise when working with the ARM sec/normal world modes frames handling, and not in the case of a "multi-user".

**Comment by avolkov-1221** [comment]
FYI @grantramsay can_mcan.c is affected too.

**Comment by henrikbrixandersen** [comment]
> FYI @grantramsay can_mcan.c is affected too.

Yes, I am working on a fix.

**Comment by avolkov-1221** [comment]
> > FYI @grantramsay can_mcan.c is affected too.
> 
> Yes, I am working on a fix.

It was mainly an alert for @grantramsay :). He had just worked on MCAN driver and probably still has access to the hardware. Therefore, he can probably fix and check RTR. Moreover, for MCAN driver, this error is not so low priority, but looks like a "ping of death": data fetching from Rx FIFO/pointers updating is based on the wrong DLC, so content of all following frames will be unpredictable.

**Comment by henrikbrixandersen** [comment]
> It was mainly an alert for @grantramsay :). He had just worked on MCAN driver and probably still has access to the hardware. Therefore, he can probably fix and check RTR.

No worries. I have access to a handful or more different boards from different vendors all implementing CAN controllers based on the Bosch M_CAN IP, allowing me to verify the changes across a wide range of different M_CAN IPs.

> Moreover, for MCAN driver, this error is not so low priority, but looks like a "ping of death": data fetching from Rx FIFO/pointers updating is based on the wrong DLC, so content of all following frames will be unpredictable.

That is not how the Rx FIFOs in the Bosch M_CAN work. FIFO elements are of a fixed size. Please avoid speculating the impact of issues like this as it just adds uncertainty and doubt.

This is purely an issue of reading and writing potentially unitialized memory regions.
