### ISSUE TITLE
LE Audio: CAP Initiator unicast sample

### ISSUE THREAD

**Issue by Thalley** [zephyrproject-rtos/zephyr#57022]
**Is your enhancement proposal related to a problem? Please describe.**
We do not have a sample that uses the CAP Initiator unicast sample.

**Describe the solution you'd like**
Create a sample application that uses the CAP Initiator.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by kartben** [comment]
TMAP Central and TMAP BMS seem to use CAP initiator unicast, is that good enough to call victory?

**Comment by Thalley** [comment]
> TMAP Central and TMAP BMS seem to use CAP initiator unicast, is that good enough to call victory?

I think that's a fair argument. Let's close this, and reopen if someone requests this again
