### ISSUE TITLE
Bluetooth BR L2CAP channel flag setting looks incorrect

### ISSUE THREAD

**Issue by yajunzhi** [zephyrproject-rtos/zephyr#57155]
**Describe the bug**
In l2cap_br.c, bt_l2cap_br_chan_connect() function,  I found that the order of set channel flag code is not proper. Currently, the step is:
```c
    atomic_set_bit(br_chan->flags, **L2CAP_FLAG_CONN_PENDING**);
    switch (l2cap_br_conn_security(chan, psm)) {
        case L2CAP_CONN_SECURITY_PENDING:
            return 0;
        case L2CAP_CONN_SECURITY_PASSED:
            break;
        case L2CAP_CONN_SECURITY_REJECT:
        default:
            bt_l2cap_chan_cleanup(chan);
            return -EIO;
    }
    ...
    l2cap_br_chan_send_req(br_chan, buf, L2CAP_BR_CONN_TIMEOUT);
```

The issue is that set flag as "CONN_PENDING", and the return value of l2cap_br_conn_security() is "PASSED", then send l2cap connection request.  But then if remote triggers a ”start_encryption_req“ again, when local zephyr received ”encrypt changed“ event, then call l2cap_br_conn_pend() function. At this time, the flag is "CONN_PENDING", the l2cap connection request could be sent again.
At this context, two L2CAP_CONNECTION_REQ package were sent to remote device. At last the connection could be failed.

More, the description of the enum ”CONN_PENDING“ is ambiguous.
```c
enum {
	/* Connection oriented channels flags */
	L2CAP_FLAG_CONN_LCONF_DONE,	/* local config accepted by remote */
	L2CAP_FLAG_CONN_RCONF_DONE,	/* remote config accepted by local */
	L2CAP_FLAG_CONN_ACCEPTOR,	/* getting incoming connection req */
	L2CAP_FLAG_CONN_PENDING,	/* **remote sent pending result in rsp** */
};
```

So my modification of the code is that 
```c
    switch (l2cap_br_conn_security(chan, psm)) {
        case L2CAP_CONN_SECURITY_PENDING:
            **atomic_set_bit(br_chan->flags, L2CAP_FLAG_CONN_PENDING);**
            return 0;
        case L2CAP_CONN_SECURITY_PASSED:
            break;
        case L2CAP_CONN_SECURITY_REJECT:
        default:
            bt_l2cap_chan_cleanup(chan);
            return -EIO;
    }
    ...
    l2cap_br_chan_send_req(br_chan, buf, L2CAP_BR_CONN_TIMEOUT);
```

**Comment by carlescufi** [comment]
@yajunzhi can you please open a Pull Request with the suggested fix?
