### ISSUE TITLE
git hooks are Linux-specific and don't work on Windows

### ISSUE THREAD

**Issue by dbkinder** [zephyrproject-rtos/zephyr#5716]
Windows-compatible git hooks scripts are needed for developers.

**Comment by nashif** [comment]
what git hooks are you referring to exactly? We do not have any git hooks in the tree

**Comment by dbkinder** [comment]
When you clone the zephyr repo, you get a ``.git/hooks`` folder with sample hooks scripts that are all Linux-specific.  In the Zephyr [contributing guidelines](http://docs.zephyrproject.org/contribute/contribute_guidelines.html#coding-style) we direct developers to create a pre-commit script with linux commands.

**Comment by nashif** [comment]
not a bug
