### ISSUE TITLE
hardening: hardened.csv is outdated

### ISSUE THREAD

**Issue by kartben** [zephyrproject-rtos/zephyr#57166]
**Describe the bug**

Zephyr's hardening tool might be one of those hidden gems that many folks (including maintainers) don't even know exist.
https://docs.zephyrproject.org/latest/security/hardening-tool.html#usage

The [hardened.csv](https://github.com/zephyrproject-rtos/zephyr/blob/main/scripts/kconfig/hardened.csv) file is meant to help with flagging the use of features not recommended for production devices (ex. experimental features, logging, ...).
It appears that the file hasn't been maintained and several features that moved out of experimentals (NET_SOCKETS_OFFLOAD, UART_ASYNC_API, ...) are still marked experimental there. What's more, there's probably many other features added over the years that'd need to be properly documented w.r.t their recommended values.

**To Reproduce**

1.  `west build -b nrf52840dk_nrf52840 .\samples\subsys\logging\logger` (a samples that uses UART_ASYNC_API)
2. `cd build`
3. `ninja hardenconfig`
4. FAIL due to CONFIG_UART_ASYNC_API being set to Y when recommend is N. But this API is not experimental anymore so shouldn't be "not" recommended.

**Expected behavior**

`hardened.csv` file should reflect actual recommended values as per maintainers/security group, in particular all the experimental/beta features should be aligned with current codebase.

**Impact**
Lack of clarity w.r.t relevance/usefulness of the hardening tool.

**Environment (please complete the following information):**
 - OS: all
 - Toolchain: 0.16.0
 - Commit SHA or Version: 3a08d9620ae5528d36f3b013b906eadfc9fed5e7

**Additional context**

cc @ceolin @kestewart

**Comment by nordicjm** [comment]
@de-nordic seems like this feature is similar to https://github.com/zephyrproject-rtos/zephyr/pull/47698

**Comment by kartben** [comment]
> @de-nordic seems like this feature is similar to #47698

indeed, thanks for flagging

**Comment by stephanosio** [comment]
> indeed, thanks for flagging, this might end up being a good replacement for the hardening tool altogether?

I do not think so: https://github.com/zephyrproject-rtos/zephyr/pull/47698#pullrequestreview-1418466474
