### ISSUE TITLE
sanitycheck doesn't work on Windows (mkfifo not supported)

### ISSUE THREAD

**Issue by dbkinder** [zephyrproject-rtos/zephyr#5718]
The instructions to invoke ``sanitycheck`` (in CONTRIBUTING) are Linux-specific.  Running ``python .\scripts\sanitycheck`` (as a workaround), produces errors such as "AttributeError: module 'os' has no attribute 'mkfifo'"  (mkfifo is not available on Windows)

**Comment by carlescufi** [comment]
duplicate of #2664
