### ISSUE TITLE
Add CONFIG_NOOPTIMIZATIONS option

### ISSUE THREAD

**Issue by aescolar-ot** [zephyrproject-rtos/zephyr#5720]
Add a configuration option that only forces the compilation optimizations to -O0 independently of other configuration options.

Background: Currently we have CONFIG_DEBUG which enables some extra code and sets -Og [-Og does still optimize some relatively trivial code away], and CONFIG_COVERAGE which sets -O0 and enables coverage dumping.
So neither is appropriate if one wants to debug or instrument the code that otherwise would be compiled without either option, and does not want to dump coverage info.

It should be possible to combine this new option with either CONFIG_DEBUG or CONFIG_COVERAGE . This new option should not have any other effect more than lowering optimizations to -O0

**Comment by SebastianBoe** [comment]
+1
See also https://github.com/zephyrproject-rtos/zephyr/pull/5225#issuecomment-358762195
