### ISSUE TITLE
dts board configuration is incompatible with "build all" kind of test

### ISSUE THREAD

**Issue by erwango** [zephyrproject-rtos/zephyr#5722]
As identified in #5698, "build all" kind of test conflicts with deployment of dts.

Indeed, when a SW element is converted to DTS, config pieces of Kconfig files are by passed with a 
HAS_DTS_XXX flag, for instance:

`config HTS221_NAME
	string
	prompt "Driver name"
	default "HTS221"
	depends on HTS221 && !HAS_DTS_I2C_DEVICE`

As a consequence, whenever the SW element is activated but not configured in dts (like in "build all" tests), default configuration is no more available form Kconfig file and build fails

**Comment by galak** [comment]
So I think we can fix this by introducing an application level dts.fixup.  In the 'build all' we can define dummy values for the cases that need them to build.
