### ISSUE TITLE
posix: posix_internal.h is sensitive to include order

### ISSUE THREAD

**Issue by cfriedt** [zephyrproject-rtos/zephyr#57232]
**Is your enhancement proposal related to a problem? Please describe.**
`lib/posix/posix_internal.h` is sensitive to include order issues and that needs to be fixed.

There was an RFC by @gmarull a while back about standardizing on include order and automatically enforcing that with `clang-format`. It would be a good idea to adopt.

**Describe the solution you'd like**
Include necessary headers internally so that `lib/posix/posix_internal.h` is not sensitive to include order issues, or find some other solution that makes it a non-issue.

**Describe alternatives you've considered**
Perpetuating the madness of include-order sensitive headers!

**Additional context**
Improve Header Structure and Usage (https://github.com/zephyrproject-rtos/zephyr/issues/41543)

**Comment by gmarull** [comment]
FYI https://github.com/zephyrproject-rtos/zephyr/issues/41543
