### ISSUE TITLE
The stm32 SPI driver does not work if one tries to send several buffers with a frame size of 16 bits.

### ISSUE THREAD

**Issue by dgastonochoa** [zephyrproject-rtos/zephyr#57247]
Problem description
-------------------

The stm32 SPI driver's send functions receive a set buffers to be sent one next to the other. If the SPI's transaction's frame size is set to 16 bits and more than one buffer wants to be sent, the data sent is wrong. In particular, some of the data is not sent.

This occurs because:
 * The SPI `spi_buf_set` length represents the length of the buffer in units of
   frame size.
 * The function `spi_context_get_next_buf` calculates the length of the next
   buffer wrong, because it assumes that the above parameter is set in bytes.
   Thus, it divides this length by `dfs`, which gives the wrong result.

E.g. let's suppose an SPI transaction with a frame size of 16 bits, sending 3 elements (3 half-words, so 6 bytes). `len` will be 3, and `dfs` will be 2. `spi_context_get_next_buf` will calculate the buffer length as 3/2 = 1 (integer division), which is wrong.

Notice the first buffer in the `spi_buf_set` is sent correctly because `transceive` in `spi_ll_stm32` does `spi_context_buffers_setup(&data->ctx, tx_bufs, rx_bufs, 1);`, in other words, it hard-codes `dfs` to 1 regardless of the transaction frame size.

I'm using a nucleo-h743zi board as target platform.

How to reproduce
----------------

This issue contains an attached file which is a Zephyr application called 'spi-double-buffer' that can be placed in `zephyr/samples/basic`, then built and run to reproduce the error. It has been tested on a nucleo-h743zi board.

[spi-double-buffer.zip](https://github.com/zephyrproject-rtos/zephyr/files/11323636/spi-double-buffer.zip)

The command to build it would be: `west build -p always -b nucleo_h743zi zephyr/samples/basic/spi-double-buffer`

Below you can fined a code summary about the above:
```
struct spi_cs_control csc = {...};

struct spi_config cfg = {
    .frequency = 200000,
    .operation = SPI_OP_MODE_MASTER |
                    SPI_WORD_SET(16) |
                    SPI_TRANSFER_LSB,
    .slave = 0,
    .cs = &csc,
};

s_buf[0] = 0xaaaaaaaa;
s_buf[1] = 0x55555555;
struct spi_buf tx_buf[2] = {
    {.buf = s_buf, .len = 2},
    {.buf = &s_buf[1], .len = 2},
};
struct spi_buf_set tx_bufs = { .buffers = tx_buf, .count = 2 };

int rc = spi_write(spi1, &cfg, &tx_bufs);
rc = spi_write(spi1, &cfg, &tx_bufs);
return rc;
```
A capture of a logic analyzer is shown below

![before-fix](https://user-images.githubusercontent.com/127399215/234311155-2d0c0fb9-500f-44f4-8093-d2701668164d.png)

As you can see, the data above is wrong. It should send 64 bits in each transaction, but it sends 48 (as expected, as the second buffer's length is divided by 2 due to the problem mentioned above)

Proposed change
-----------------
Avoid dividing the buffer length by `dfs` in `spi_context_get_next_buf`

**Comment by anangl** [comment]
> - The SPI spi_buf_set length represents the length of the buffer in units of
frame size.

This is incorrect. The length is specified in bytes.

> Notice the first buffer in the `spi_buf_set` is sent correctly because `transceive` in `spi_ll_stm32` does `spi_context_buffers_setup(&data->ctx, tx_bufs, rx_bufs, 1);`, in other words, it hard-codes `dfs` to 1 regardless of the transaction frame size.

And that seems to be the actual problem. `spi_context_buffers_setup()` should be called with the correct `dfs` value and in your test application you should use:
```
struct spi_buf tx_buf[2] = {
    {.buf = s_buf, .len = sizeof(s_buf[0])},
    {.buf = &s_buf[1], .len = sizeof(s_buf[1])},
};
```
Then the output should be as expected (i.e. 64 bits sent).

**Comment by dgastonochoa** [comment]
> This is incorrect. The length is specified in bytes.

I see. I imagine that means that using frame sizes smaller than 1 bytes is not supported. I will update my PR to fix the actual problem. I suggest to add to this comment: `@param len is the length of the buffer or,[...]` that the length must be specified in bytes.
