### ISSUE TITLE
error: '__device_dts_ord_DT_CHOSEN_zephyr_display_ORD' undeclared 

### ISSUE THREAD

**Issue by DuyTrandeLion** [zephyrproject-rtos/zephyr#57258]
**Describe the bug**
I am trying to run the *cfb* example with the nrf52-dk and ssd1306 display. When I compiled the code, I received the following error:
```
/opt/nordic/ncs/v2.2.0/zephyr/include/zephyr/device.h:83:41: error: '__device_dts_ord_DT_CHOSEN_zephyr_display_ORD' undeclared (first use in this function)
   83 | #define DEVICE_NAME_GET(dev_id) _CONCAT(__device_, dev_id)
      |                                         ^~~~~~~~~
```
The error occured in this function:
```
	dev = DEVICE_DT_GET(DT_CHOSEN(zephyr_display));
	if (!device_is_ready(dev)) {
		printf("Device %s not ready\n", dev->name);
		return 0;
	}
```
This is my .overlay file:
```
&spi2 {
	compatible = "nordic,nrf-spi";
	status = "okay";
    cs-gpios = <&arduino_header 16 GPIO_ACTIVE_LOW>; /* D10 */
	pinctrl-0 = <&spi2_default>;
	pinctrl-1 = <&spi2_sleep>;
	pinctrl-names = "default", "sleep";

    ssd1306: ssd1306@0 {
        compatible = "solomon,ssd1306fb";

        reg = <0x0>;
        // label = "SSD1306";
		spi-max-frequency = <8000000>;
		width = <128>;
		height = <64>;
		segment-offset = <0>;
		page-offset = <0>;
		display-offset = <0>;
		multiplex-ratio = <63>;
		segment-remap;
		// com-invdir;
        // com-sequential;
        // duplex;
        // frame-format;
        // supply-gpios;
        // vin-supply;
		prechargep = <0x22>;
		data_cmd-gpios = <&gpio0 9 GPIO_ACTIVE_LOW>;
		reset-gpios = <&gpio0 10 GPIO_ACTIVE_LOW>;
    };
};
```
I checked `buid/zephyr/zephyr.dts` file and the .overlay file was successfully applied.

*Environment*:
OS: MacOS Ventura
Platform: nRF52-DK
Toolchain nrf-connect.toolchain:2.3.0
Zephyr version: 3.3.0

**Comment by galak** [comment]
@DuyTrandeLion what does your dts look like as part of the build (<BUILD_DIR>/zephyr/zephyr.dts)

**Comment by DuyTrandeLion** [comment]
@galak please see the attachment. It is a default nrf52-dk dts with 1 modification in spi2 for ssd1306 (solomon).
[zephyr.txt](https://github.com/zephyrproject-rtos/zephyr/files/11328465/zephyr.txt)

**Comment by henrikbrixandersen** [comment]
Did you add a `zephyr,display` chosen DTS property?

**Comment by DuyTrandeLion** [comment]
@henrikbrixandersen I just added and it works for me now. Thanks. I think we can close the issue.
I made a reference from [here](https://github.com/zephyrproject-rtos/zephyr/blob/a5bd666f4e1c887b0cf05738d017d7fb024997bb/boards/shields/ssd1306/ssd1306_128x64_spi.overlay)

**Comment by DuyTrandeLion** [comment]
Hi @henrikbrixandersen , @galak , I was able to compile the code but the display did not show up anything. This is my wiring:
CLK -> P0.25
MOSI -> P0.23
CS -> P0.22
RES -> P0.10
DC -> P0.09

Here is my project configuration
```
CONFIG_HEAP_MEM_POOL_SIZE=2048
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=2048

CONFIG_BT=y
CONFIG_BT_PERIPHERAL=y
CONFIG_BT_DEVICE_NAME="Nordic_Lion"
CONFIG_BT_SMP=y
CONFIG_BT_GATT_CLIENT=y
CONFIG_BT_GATT_DM=y

# Enable AMS client
CONFIG_BT_AMS_CLIENT=y

# Enable GATT Service client
CONFIG_BT_GATTP=y

# Enable ANCS client
CONFIG_BT_ANCS_CLIENT=y

# Enable bonding
CONFIG_BT_SETTINGS=y
CONFIG_FLASH=y
CONFIG_FLASH_PAGE_LAYOUT=y
CONFIG_FLASH_MAP=y
CONFIG_NVS=y
CONFIG_SETTINGS=y

# Enable DK LED and Buttons library
CONFIG_DK_LIBRARY=y
CONFIG_SPI=y
CONFIG_NRFX_SPI2=y

CONFIG_DISPLAY=y
CONFIG_SSD1306=y
CONFIG_SSD1306_SH1106_COMPATIBLE=y
CONFIG_CHARACTER_FRAMEBUFFER=y
CONFIG_MAIN_STACK_SIZE=2048
```

Do I have to make any other configuration? Or did I do something wrong?

**Comment by Amritha-124** [comment]
/home/amritha/zephyr_workspace/zephyr/include/zephyr/device.h:96:41:error: '__device_dts_ord_DT_CHOSEN_zephyr_bt_uart_ORD' undeclared (first use in this function)
   96 | #define DEVICE_NAME_GET(dev_id) _CONCAT(__device_, dev_id)

i tried to enable bluetooth,but getting this error
