### ISSUE TITLE
Ninja: Running sanitycheck has byproducts outside of sanity-out

### ISSUE THREAD

**Issue by SebastianBoe** [zephyrproject-rtos/zephyr#5725]
Running sanitycheck with ninja will dirty the repo with untracked files.

e.g. tests/net/arp/test/

All files should be written to sanity-out.

**Comment by nashif** [comment]
I have noticed this, but was never able to reproduce it, is there a simple way to reproduce this?

**Comment by SebastianBoe** [comment]
Run it from my machine? ;)

Will take a closer look.

**Comment by nashif** [comment]
have not see this issue and can't reproduce, closing
