### ISSUE TITLE
RFC: API Change: Bluetooth Mesh

### ISSUE THREAD

**Issue by LingaoM** [zephyrproject-rtos/zephyr#57267]
- Problem Description: https://github.com/zephyrproject-rtos/zephyr/pull/57215
   - Change Define Mesh element and models as const, the reason is that the Mesh Profile clearly stipulates that Mesh nodes cannot change their own element definitions.their own element definitions.
 - Proposed Change (detailed):
   - The `elem->addr` has been changed to `elem->rt->addr`
   - All bluetooth models prefix `const`
 - Detailed RFC:
   - Function call changes
        The `elem->addr` has been changed to `elem->rt->addr`
   - Device Tree changes (source and bindings)
      No
   - Kconfig option changes
      No
 - Dependencies:
    Any access `elem->addr` should replace with `elem->rt->addr`.

**Comment by carlescufi** [comment]
@LingaoM you are missing a couple of steps:
https://docs.zephyrproject.org/latest/develop/api/api_lifecycle.html#introducing-incompatible-changes

In particular, you need to send an email to devel@ and bring the topic to the Architecture WG meeting (you don't need to be present, just ask for the topic to be discussed there).

**Comment by LingaoM** [comment]
> @LingaoM you are missing a couple of steps: https://docs.zephyrproject.org/latest/develop/api/api_lifecycle.html#introducing-incompatible-changes
> 
> In particular, you need to send an email to devel@ and bring the topic to the Architecture WG meeting (you don't need to be present, just ask for the topic to be discussed there).

Thanks for the reminder, done.

**Comment by LingaoM** [comment]
Merged
