### ISSUE TITLE
tests/kernel/timer/timer_behavior fails on test_jitter_drift_timer_startdelay for some stm32 boards 

### ISSUE THREAD

**Issue by FRASTM** [zephyrproject-rtos/zephyr#57288]
Executing the tests/kernel/timer/timer_behavior/ fails  when running with twister

failure occurs on the timer_jitter_drift.test_jitter_drift_timer_startdelay
nucleo_wb55rg
stm32l562e_dk

**To Reproduce**
1. twister --device-testing --device-serial /dev/ttyACM0 --disable-suite-name-check -p nucleo_wb55rg -T tests/kernel/timer/timer_behavior/
2. See error

**Expected behavior**
Test PASSED ---> execution is correct when running 
$ west build -p always -b nucleo_wb55rg tests/kernel/timer/timer_behavior/

**Impact**
CI failure

**Logs and console output**
```
===================================================================
START - test_jitter_drift_timer_startdelay
periodic timer behavior test using explicit start with delay
collecting time samples for approx 10 seconds
periodic timer samples gathered, calculating statistics
timer clock rate 32000000, kernel tick rate 10000
period duration statistics for 10000 samples (0 rollovers):
expected: 1000 us,              32000.000000 cycles
min:      899.437500 us,        28782 cycles
max:      1000.000000 us,       32000 cycles
mean:     999.989944 us,        31999.678200 cycles
variance: 1.011181 us,  1035.448845 cycles
stddev:   1.005575 us,  32.178391 cycles
timer start cycle 332627678, end cycle 652624460,
total time 9999899.437500 us, expected time 10000000.000000 us,
expected time drift 0.000000 us, difference -100.562500 us
Assertion failed at WEST_TOPDIR/zephyr/tests/kernel/timer/timer_behavior/src/jitter_drift.c:239: do_test_using: (min_us >= min_us_bound is false)
Shortest timer period too short (off by more than expected 10%)
FAIL - test_jitter_drift_timer_startdelay in 10.373 seconds
===================================================================

```

**Environment (please complete the following information):**
 - OS: Ubuntu
 - Toolchain Zephyr SDK 0.15.2
 - Commit SHA d2917610a5ba2f190c7e8cfa49db93fab0e2f99e

**Additional context**

- same assertion as reported by the https://github.com/zephyrproject-rtos/zephyr/issues/56589
-  running the same test on the nucleo_l552ze_q --> PASSED (The nucleo_l552ze_q has console on the LPUART1)

**Comment by FRASTM** [comment]
branch https://github.com/FRASTM/zephyr/tree/timer_behavior is an adaptation to PASS the testcase

**Comment by galak** [comment]
@teburd

**Comment by teburd** [comment]
This seems to be the same as #57285 where one timer runs short (probably the first one)

**Comment by FRASTM** [comment]
not fixed

**Comment by FRASTM** [comment]
Now (SHA1  d2e89eb512) seen with _nucleo_f429zi_ and _nucleo_l152re_
Reported also by https://github.com/zephyrproject-rtos/zephyr/issues/58729

**Comment by teburd** [comment]
#63086 as a possible fix

**Comment by FRASTM** [comment]
I confirm https://github.com/zephyrproject-rtos/zephyr/pull/63086  is fixing this error

**Comment by FRASTM** [comment]
fixed by https://github.com/zephyrproject-rtos/zephyr/pull/63210
