### ISSUE TITLE
cppcheck warnings in the eth_stm32_hal driver

### ISSUE THREAD

**Issue by spe-ciellt** [zephyrproject-rtos/zephyr#57336]
**Describe the bug**

When running cppcheck (cppcheck-2.7)  it reported some suspicious code in `drivers/ethernet/eth_stm32_hal.c`.

```
drivers/ethernet/eth_stm32_hal.c:1398:16: portability: Shifting signed 32-bit value by 31 bits is implementation-defined behaviour [shiftTooManyBitsSigned]
  if (val & (1 << i)) {
               ^
drivers/ethernet/eth_stm32_hal.c:1397:16: note: Assuming that condition 'i<32' is not redundant
 for (i = 0; i < 32; i++) {
               ^
drivers/ethernet/eth_stm32_hal.c:1398:16: note: Shift
  if (val & (1 << i)) {
               ^
drivers/ethernet/eth_stm32_hal.c:1398:16: error: Signed integer overflow for expression '1<<i'. [integerOverflow]
  if (val & (1 << i)) {
               ^
drivers/ethernet/eth_stm32_hal.c:1397:16: note: Assuming that condition 'i<32' is not redundant
 for (i = 0; i < 32; i++) {
               ^
drivers/ethernet/eth_stm32_hal.c:1398:16: note: Integer overflow
  if (val & (1 << i)) {
               ^
```

**To Reproduce**

Use cppcheck to analyze the code.

**Expected behavior**
No warnings.

**Impact**

Mostly annoying, but being in the murky corners of the C standard is never good (see "undefined behaviour)

**Fix**

In function `reverse()` of `drivers/ethernet/eth_stm32_hal.c`, on line 1353, change
`if (val & (1 << i)) {`
to
`if (val & (1UL << i)) {`

**Additional context**

The change is so small and silly so it would be more job to produce a pull request. Hope this is acceptable.

**Comment by FRASTM** [comment]
Thanks for reporting the analysis of the cppcheck.

Even if "trivial" you could _directly_ raise a Pull Request with this fix (without going through an issue). Then sort that  PR with  _trivial_ label
