### ISSUE TITLE
Instruction Cache is disabled during boot of NXP i.MX RT10xx for specific configurations

### ISSUE THREAD

**Issue by kt-peters** [zephyrproject-rtos/zephyr#57349]
**Describe the bug**

For a specific set of configurations, the instruction cache of i.MX RT10xx MCUs is disabled during boot resulting in significantly worse performance.

- Tested on mimxrt1064_evk but should be relevant to all i.MX RT10xx MCUs.
- The problem occurs if the configuration settings `CONFIG_INIT_ARCH_HW_AT_BOOT` (implied by `BOOTLOADER_MCUBOOT`) and `CONFIG_ARCH_CACHE` (default choice if `CONFIG_CACHE_MANAGEMENT` is enabled) are both enabled.
- the problem was introduced in commit 1ed776a218ad10b0aa9454b1a3f7517a0f3a63fb:
  - a call to `SCB_EnableICache()` was removed from `imxrt_init()` (zephyr\soc\arm\nxp_imx\rt\soc_rt10xx.c) and a call to `SystemInit()` was added to `z_arm_platform_init()`. 
  - `SystemInit()` does enable the instruction cache (also by calling `SCB_EnableICache()`).
  - If `CONFIG_INIT_ARCH_HW_AT_BOOT` is enabled, the function `z_arm_init_arch_hw_at_boot()` (arch\arm\core\aarch32\cortex_m\scb.c) is called after `z_arm_platform_init()` during the boot sequence in `z_arm_reset()` (arch\arm\core\aarch32\cortex_m\reset.S).
  - If `CONFIG_ARCH_CACHE` is enabled, `z_arm_init_arch_hw_at_boot()` disables the instruction cache.
  - `imxrt_init()` is called after `z_arm_init_arch_hw_at_boot()`, so previously to commit 1ed776a218ad10b0aa9454b1a3f7517a0f3a63fb, the instruction cache was enabled anyway.

As a workaround, I restored the call to  `SCB_EnableICache()` in `imxrt_init()`. This restored the expected behavior.

**To Reproduce**

The easiest way to reproduce this is to build the SMP Server Sample (https://docs.zephyrproject.org/latest/samples/subsys/mgmt/mcumgr/smp_svr/README.html#smp-svr-sample) with `CONFIG_CACHE_MANAGEMENT=y`.

Since the SMP server is not very complex, the performance loss is not easily noticable. The state of the instruction cache can be determined from the corresponding register (SystemControl(0xe000e000)->CCR.IR).

**Expected behavior**

Unless otherwise configured (`CONFIG_IMXRT1XXX_CODE_CACHE=n`), the instruction cache should be enabled.

**Impact**

A reasonably complex application (usually >90% idle according to thread statistics) is significanly slowed down without the instruction cache.

**Comment by danieldegrasse** [comment]
Hi @kt-peters, thank you for outlining the issue so clearly.

I think that your solution makes sense here- perhaps a block like the following can be added to the RT10xx `imxrt_init` function:

```
if (IS_ENABLED(CONFIG_IMXRT1XXX_CODE_CACHE)) {
     SCB_EnableICache();
else {
     SCB_DisableICache();
}
```
Would you be willing to open a PR with this fix, since you are able to verify that performance is as you expect with this change?
