### ISSUE TITLE
HW WDT would  be a default channel, and fed on default,  if the HW fall back activated even none of the task wdt channel added and fed yet .

### ISSUE THREAD

**Issue by mehmetcanbalci** [zephyrproject-rtos/zephyr#57389]
When  Hw WDT's configured  as fallback for the task wdt , hw wdt's  "wdt_install_timeout"  and "wdt_setup" functions are handled by "task_wdt_init" and "wdt_setup"
Task Wdt documentation is pretty  draft and lack of details. 
IF CONFIG_TASK_WDT_HW_FALLBACK configured , HW wdt will not start ( wdt_setup wont be called) as a default channel until the first  sw wdt channel added. 

Solution of this , 
A-)  documenting the current behavior clearly 

OR , 
B-) calling the task_wdt_add function first time in the task_wdt_init so  registering the  the hw wdt as channel 0.

OR;
c-) Calling task_wdt_feed in the task_wdt_init(0) and / or removing the this check 
```c
	if (channel_id < 0 || channel_id >= ARRAY_SIZE(channels)) {
		return -EINVAL;
	}
``` 

Conclusion we need to call schedule_next_timeout and wdt_setup even none of task wdt channel added ,or documenting it clearly.
My suggestion is , hw wdt functionality  could be utilized even none of the channel added yet . 

_**Currently work around for this issue is  calling the  task_wdt_feed with a channel 0  ,even it is not added yet , right after the task_wdt_init(hw_wdt)

This works as how i want but calling  task_wdt_feed(0); without task_wdt_add seems little bit weird. since i didn't added the channel 0 yet . 

Another simple solution is 
Replacing this 
#define TASK_WDT_BACKGROUND_CHANNEL (-1)

With this 
#define TASK_WDT_BACKGROUND_CHANNEL (0)

And task_wdt_add will add the first channel as 1 not 0 , 0 will be dedicated to hw wdt . 
and we will call 
task_wdt_feed(TASK_WDT_BACKGROUND_CHANNEL);   right after the task_wdt_init(hw_wdt) call.**_

Thanks

**Comment by henrikbrixandersen** [comment]
Fixed in https://github.com/zephyrproject-rtos/zephyr/commit/fdea8518783a5d8c4421595341f8332ac5714167
