### ISSUE TITLE
Atmel header files with bsd-atmel license

### ISSUE THREAD

**Issue by nandojve** [zephyrproject-rtos/zephyr#57400]
## Origin

Atmel Packs Repository (former Microchip Packs Repository)
http://packs.download.atmel.com

## Purpose

The Atmel Packs contains registers macros definitions to allow use of Atmel SAM3U SoCs series.

## Mode of integration

The integration is made as-is and corrections are performed using individual commits on inconsistencies.

## Maintainership

The Atmel Packs are already part of Zephyr Project available on https://github.com/zephyrproject-rtos/hal_atmel. There is no  active maintainer. Usually @galak , @stephanosio, @nandojve are people that at some point were involved or helped.

## Pull Request

#55416

## Description

The issue is that now CI performs license scans using [OSI approved licenses](https://opensource.org/license/) only and can not identify exceptions, like `bsd-atmel` license. This recently rule blocks to merge the Atmel Pack dependency.

The `bsd-atmel` is permissive as found in https://scancode-licensedb.aboutcode.org/bsd-atmel.html. This license is already accepted in the project and SAM3X SoC (Arduino Due), for instance, which is one of first devices in the project. The Arduino Due is a well example of Open Hardware and Open Source which many people have access and play around.

The manufacturer have been licensing as Apache 2 the recently versions of Packs. It seems that manufacturer have been updating licenses only when a new release is made, which proves intention to make code complete Open Source over time. However the old packages stay with the BSD-2/3 special clause, denominated `bsd-atmel`.

Since community is working with many of those SoCs it is possible that overtime more issues related to `bsd-atmel` licenses may happen if an exception is not made.

## License

``bsd-atmel``

**Comment by carlescufi** [comment]
I am sorry but there is a clear policy for non-OSI licenses: reject the code directly:

https://docs.zephyrproject.org/latest/contribute/external.html#software-license
https://www.zephyrproject.org/wp-content/uploads/sites/38/2021/05/Board-Policies-04.26.2021.pdf
