### ISSUE TITLE
LE Audio: ASCS ensure that notifications are sent 

### ISSUE THREAD

**Issue by Thalley** [zephyrproject-rtos/zephyr#57451]
**Is your enhancement proposal related to a problem? Please describe.**
In ASCS we don't verify that all notifications are actually sent. Since this may cause issues for remote devices (and is in fact not spec compliant), we should ensure that all notifications (or at least the latest value) is sent as notifications. 

**Describe the solution you'd like**
If a notification fails to be sent, it can either be re-triggered by using a `k_work` or similar, or the change request can be rejected. 

This should also ensure that we correctly send notifications to re-connecting bonded devices when applicable.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by MariuszSkamra** [comment]
Done with ba6142050493eb5f6b0f1233cf4a313eb4d162b5
