### ISSUE TITLE
The stm32 SPI driver seems to not work properly, when DMA is enabled, for the stm32h7 series

### ISSUE THREAD

**Issue by dgastonochoa** [zephyrproject-rtos/zephyr#57515]
@r-neal and I have found a problem when trying to use DMA with SPI in STM32H7.

Problem description
===================
Configuring SPI2 to be used with DMA, streams 1 and 2, and DMAMUX requests 39 and 40, for tx and rx respectively, the following error is thrown:
```
[00:00:00.000,000] <err> spi_ll_stm32: DMA callback channel 0 is not valid.
```
Target platform is nucleo-h743zi2.

An initial investigation has revealed that the problem comes from the fact that the DMA stream provided in DT is modified at runtime by subtracting 1 to it. The error is thrown by the SPI DMA callback, when the received stream id (0) does not match with any of those configured in devicetree (1 and 2, see below).

This offset (which is subtracted to the channel specified in DT) seems to exist to convert DMAMUX stream IDs from 1..n to 0..n-1, according to the comment `/* Give channel from index 0 */` in `dma_stm32.c`. This seems to not be correct, since the DMAMUX channels in stm32h7 go from 0 to n, not from 1 to n-1. See the [stm32h7 datasheet](https://www.st.com/resource/en/reference_manual/dm00314099-stm32h742-stm32h743-753-and-stm32h750-value-line-advanced-arm-based-32-bit-mcus-stmicroelectronics.pdf)  capture below:

![dmamux-idx-0](https://user-images.githubusercontent.com/127399215/235916573-db3372b9-d3c6-4546-821b-905b36bf9c10.png)

Is this the right interpretation of what this offset does? If so, I'm happy to create a PR to fix this problem.

How to reproduce
================
This issue contains an attached file which is a Zephyr application called 'dma-test' that can be placed in zephyr/samples/basic, then built and run to reproduce the error. It has been tested on a nucleo-h743zi board.

[dma-test.tar.gz](https://github.com/zephyrproject-rtos/zephyr/files/11382535/dma-test.tar.gz)

The command to build it is: `west build -p always -b nucleo_h743zi zephyr/samples/basic/spi-test`

Below you can fine a code summary about the above:

Overlay file
-------------
```
&dmamux1 {
	status = "okay";
};

&dma1 {
	status = "okay";
};

&spi2 {
	status = "okay";
	pinctrl-0 = <&spi2_sck_pd3 &spi2_miso_pb14 &spi2_mosi_pb15>;
	pinctrl-names = "default";
	cs-gpios = <&gpiog 8 (GPIO_ACTIVE_LOW | GPIO_PULL_UP)>;

	dmas = <&dma1 2 39 0x480 0x3>, /* 39 = DMA_REQUEST_SPI2_RX; 0x480 = periph-to-mem | mem-increase-addr | mem-size-byte | periph-size-byte; 0x03 = fifo-threshold-full */
		   <&dma1 1 40 0x440 0x3>; /* 40 = DMA_REQUEST_SPI2_TX; 0x440 = mem-to-periph | mem-increase-addr | mem-size-byte | periph-size-byte; 0x03 = fifo-threshold-full */
	dma-names = "rx", "tx";
};
```

Requests are 39 and 40 as specified by the stm32h7 datasheet:

![dmamux-table](https://user-images.githubusercontent.com/127399215/235916909-61137f31-6b89-4c86-8712-40fa144092b3.png)

Config file
-----------
```
CONFIG_SPI=y
# CONFIG_SPI_STM32_USE_HW_SS is not set
CONFIG_PINCTRL=y
CONFIG_SERIAL=y
CONFIG_SPI_STM32_DMA=y
```

As explained above, if an spi transaction is sent, an error regarding a non-existing channel will be thrown.

**Comment by FRASTM** [comment]
Because the stm32h743 has a DMAMUX in front of dma1 & dma2, when transferring on the SPI2, the DMAMUX instance is the phandle ; did you  try with  : 
```
&spi2 {
	dmas = <&dmamux1 2 39 0x480 0x3>, 
		   <&dmamux1 1 40 0x440 0x3>;
	dma-names = "rx", "tx";
```
