### ISSUE TITLE
I2C stats don't work on ESP32

### ISSUE THREAD

**Issue by xyzzy42** [zephyrproject-rtos/zephyr#57532]
**Describe the bug**
I2C stats bytes read and bytes written are always zero with ESP32.

**To Reproduce**
Enable statistics and I2C statistics, use I2C, look at stats.

**Expected behavior**
Should have correct stats.

**Impact**
Using I2C stats doesn't work.

**Logs and console output**
```
Stats Group i2c@3ff53000 (hdr addr: 0x3ffb1c28)
        bytes_read (offset: 24, addr: 0x3ffb1c40): 0
        bytes_written (offset: 28, addr: 0x3ffb1c44): 0
        message_count (offset: 32, addr: 0x3ffb1c48): 14
        transfer_call_count (offset: 36, addr: 0x3ffb1c4c): 9
```

bytes read and written should not be zero.

**Environment (please complete the following information):**
 - Commit zephyr-v3.3.0-2374-gb272f468d3

**Additional context**
The reason this happens is that the ESP32 I2C driver modifies the i2c_msg's `buf` and `len` fields when it processes the messages.  This messes up the stats, which are gathered after the message is processed.  It also messes up the logging of i2c messages, if that is enabled.  

And probably also causes a few app bugs, since while the i2c_msg field isn't marked const, there really is no expectation that the buffer pointer and length will be modified.  Any code that tries to access i2c read data from the i2c_msg[x].buf pointer will access beyond the buffer.  And any code that re-uses an array of i2c_msgs for multiple transactions won't expect the length fields to have changed.

**Comment by sylvioalves** [comment]
@xyzzy42, can you also check this PR?
