### ISSUE TITLE
SystemView: add mode configurable options through KConfig

### ISSUE THREAD

**Issue by nono313** [zephyrproject-rtos/zephyr#57603]
**Is your enhancement proposal related to a problem? Please describe.**
SEGGER SysView has lots of configurable options, like the RTT channel. The `SEGGER_SysVIEW_ConfDefaults.h` header provides a few options that are not configurable through KConfig

**Describe the solution you'd like**
Allow configuration of all values from `SEGGER_SYSVIEW_Conf` using KConfig

**Describe alternatives you've considered**
Alternative is to use a global header compiled with all files in which we could override the defines before the _Conf header file is included.

**Additional context**
N/A

**Comment by henrikbrixandersen** [comment]
@nono313 Can you submit a PR adding Kconfig symbols for the needed configuration definitions in the header?
