### ISSUE TITLE
NRF5 BLE radio driver: PPI18 is cleared unconditionally

### ISSUE THREAD

**Issue by ioannisg** [zephyrproject-rtos/zephyr#5761]
In radio_tmr_status_reset(), PPI18 (now HAL_SW_SWITCH_TIMER_S8_DISABLE_PPI_DISABLE, after  #5682)  is cleared, if we compile for NRF52840. However, this PPI is only used if SW-auto switch is enabled. If SW-auto switch is not used for nRF52840 (I would like to ask whether this is an interesting use-case), we might want to leave this PPI to be used by application code, instead.

cc @cvinayak

**Comment by cvinayak** [comment]
Relates to #5779
