### ISSUE TITLE
BUS FAULT: Hard fault arising from gpio_add_callback() and potentially slist pointers?

### ISSUE THREAD

**Issue by savvn001** [zephyrproject-rtos/zephyr#57612]
Zephyr OS Build: v3.2.99-ncs2 (nRF connect SDK fork BUT this is Zephyr specific issue I think)
Platform: NRF52

Hi, got an issue that I'm stuck on currently, when trying to initialise some callbacks for GPIO interrupts.
The issue arises when I try to call `gpio_add_callback` for the 2nd time in the application.

So let's say in sensor driver 1 .c file I have the textbook setup for a GPIO interrupt, and assigning a cb fn.

```
static const struct gpio_dt_spec _max30101_int_pin = GPIO_DT_SPEC_GET(DT_NODELABEL(ppgint), gpios);
static struct gpio_callback _max30101_int_cb_data;

static void _max30101_int_cb(const struct device *dev, struct gpio_callback *cb, uint32_t pins)
{
    LOG_DBG("int cb");
    // Submit a work item to the sensors work queue to read out the sensor's FIFO
    k_work_submit_to_queue(&sensors_ctrl_work_q, &_read_fifo_work_item.work);
}

// Config interrupt on PPG int pin - for MAX30101 it is active low when int is triggered
ret = gpio_pin_configure_dt(&_max30101_int_pin, GPIO_INPUT);
ret = gpio_pin_interrupt_configure_dt(&_max30101_int_pin, GPIO_INT_EDGE_FALLING);

if (ret < 0)
{
    LOG_ERR("Err initing GPIO for int pin");
    return;
}

// Config callback on int pin
gpio_init_callback(&_max30101_int_cb_data, _max30101_int_cb, BIT(_max30101_int_pin.pin));
gpio_add_callback(_max30101_int_pin.port, &_max30101_int_cb_data);
```

That works ok. It builds and runs. Now in `sensor driver 2.c` file I have the exact same thing. The exact same snippet except, for the pin being different. The variable names are **different** and it is in a **separate** .c file. The callback function is a different statically defined function inside this `sensor driver 2.c`.

When this snippet from `sensor driver 2.c` get's called after `sensor driver 1 .c` I get the following error:

```
[00:00:00.014,709] <err> os: bus_fault: ***** BUS FAULT *****
[00:00:00.021,484] <err> os: bus_fault:   Precise data bus error
[00:00:00.028,533] <err> os: bus_fault:   BFAR Address: 0x30b44908
[00:00:00.035,797] <err> os: esf_dump: r0/a1:  0x20003fd8  r1/a2:  0x30b44908  r2/a3:  0x200032c8
[00:00:00.045,928] <err> os: esf_dump: r3/a4:  0x30b44908 r12/ip:  0x00000006 r14/lr:  0x00035107
[00:00:00.055,999] <err> os: esf_dump:  xpsr:  0x21000000
[00:00:00.062,469] <err> os: esf_dump: Faulting instruction address (r15/pc): 0x000350e2
[00:00:00.071,716] <err> os: z_fatal_error: >>> ZEPHYR FATAL ERROR 0: CPU exception on CPU 0
[00:00:00.081,298] <err> os: z_fatal_error: Current thread: 0x200030a8 (main)
```

The offending line is `gpio_add_callback()` from  `sensor driver 2.c`. So I dug into it, and the issue starts at this snippet from `gpio_utils.h`

```
/**
 * @brief Generic function to insert or remove a callback from a callback list
 *
 * @param callbacks A pointer to the original list of callbacks (can be NULL)
 * @param callback A pointer of the callback to insert or remove from the list
 * @param set A boolean indicating insertion or removal of the callback
 *
 * @return 0 on success, negative errno otherwise.
 */
static inline int gpio_manage_callback(sys_slist_t *callbacks,
					struct gpio_callback *callback,
					bool set)
{
	__ASSERT(callback, "No callback!");
	__ASSERT(callback->handler, "No callback handler!");

	if (!sys_slist_is_empty(callbacks)) {
		if (!sys_slist_find_and_remove(callbacks, &callback->node)) {
			if (!set) {
				return -EINVAL;
			}
		}
	} else if (!set) {
		return -EINVAL;
	}

	if (set) {
		sys_slist_prepend(callbacks, &callback->node);
	}

	return 0;
}
```

It goes into `sys_slist_find_and_remove()`and somewhere in there it ends up at `slist.h`

```
static inline sys_snode_t *z_snode_next_peek(sys_snode_t *node)
{
	return node->next;
}
```
`node->next` is just 0 and I guess maybe returning this null pointer causes a hard fault. I'm not sure why it's 0 as the slist implementation is beyond what I know, but I just dug into this using the debugger and saw this was the offending line.

**Comment by anangl** [comment]
@savvn001 Please provide a minimal application with which the problem could be observed. I was not able to reproduce such behavior using the information you provided. There is no problem with adding a second GPIO callback in an application. I tried this with the latest Zephyr and with NCS 2.3.0 and everything worked fine, so the problem you are encountering is probably caused by something else. But the exact code that you are using is required for any further investigation.

**Comment by anangl** [comment]
> I then found, for some reason, commenting out these lines:
> 
> ```
>     strcpy(_max30101_work.name, "max30101_read_fifo");
>     k_work_init(&_max30101_work.work, _read_fifo);
> ```
> 
> Fixes the issue - no hard faults. I'm struggling to see the connection here between initialising that work item and the callback init function.

I guess that commenting out just the line with `strcpy` should help, as it tries to copy 19 characters to a 16-character array.
