### ISSUE TITLE
Windows 10 WSL does not supports Native POSIX Boards

### ISSUE THREAD

**Issue by xianrenqiu** [zephyrproject-rtos/zephyr#5762]
I refer to [《Native POSIX execution (native_posix)》](http://docs.zephyrproject.org/boards/posix/native_posix/doc/board.html) chapter，When I execute zephyr/zephyr.exe command.  An Error Has Occurred：
> **-bash: zephyr/zephyr.exe: cannot execute binary file: Exec format error**

the process is as follows：
```
$ cd $ZEPHYR_BASE/samples/hello_world
$ mkdir -p build && cd build
$ cmake -DBOARD=native_posix ..
$ make
$ zephyr/zephyr.exe
-bash: zephyr/zephyr.exe: cannot execute binary file: Exec format error
```
test on master commit [6f88c2](https://github.com/zephyrproject-rtos/zephyr/commit/6f88c284871374fe5cf059d7c97c76a4c80df094), I use the ubuntu 16.04(64 bit) operating system(win10 wsl). and i have already install the gcc-multilib package. What might be the problem? Thank you.
```
$ uname -a
Linux DESKTOP-QK68FB0 4.4.0-43-Microsoft #1-Microsoft Wed Dec 31 14:42:53 PST 2014 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by xianrenqiu** [comment]
I found it was a [WSL problem](https://github.com/Microsoft/WSL/issues/390)，Currently WSL only supports amd64 (native 64bit) ，does not supports 32-bit i386 ELF binaries 

> Whether we can add relevant explanations in [relevant chapters](http://docs.zephyrproject.org/getting_started/installation_win.html#using-windows-10-wsl-windows-subsystem-for-linux).

**Comment by aescolar-ot** [comment]
Thanks, I never expected it to work in WSL, you may have been the 1st one to try it out.

@carlescufi Will you consider @xianrenqiu request on the warning in the WSL installation chapter?

**Comment by nashif** [comment]
no plans to support this in WSL since it only supports 64bit.
