### ISSUE TITLE
Checking if its the user's first contribution failing with Error: You have exceeded a secondary rate limit. Please wait a few minutes before you try again.

### ISSUE THREAD

**Issue by fabiobaltieri** [zephyrproject-rtos/zephyr#57644]
**Describe the bug**
Hi, just noticed the "first time contributor" workflow occasionally fails with "You have exceeded a secondary rate limit. Please wait a few minutes before you try again.", see https://github.com/zephyrproject-rtos/zephyr/actions/workflows/greet_first_time_contributor.yml.

@kartben is that something you want to look into? Maybe add a retry somewhere in there.

**To Reproduce**
Unclear, but there's plenty in https://github.com/zephyrproject-rtos/zephyr/actions/workflows/greet_first_time_contributor.yml

**Expected behavior**
Should always succeed.

**Impact**
Just generates some email.

**Comment by kartben** [comment]
Implemented a fix here: https://github.com/zephyrproject-rtos/action-first-interaction/pull/3
