### ISSUE TITLE
boards: nucleo_f413zh: Likely outdated OpenOCD info in docs

### ISSUE THREAD

**Issue by pfalcon** [zephyrproject-rtos/zephyr#5766]
boards/arm/nucleo_f413zh/doc/nucleof413zh.rst says:

~~~
Nucleo F413ZH board includes an ST-LINK/V2-1 embedded debug tool interface.
However this interface is currently not supported by OpenOCD. You will need
to use ST tools or an external JTAG probe.
~~~

Most other STM32 boards say:

~~~
Nucleo L432KC board includes an ST-LINK/V2-1 embedded debug tool
interface.  This interface is supported by the openocd version
included in the Zephyr SDK since v0.9.2.
~~~

Perhaps, nucleo_f413zh docs need to be updated?

**Comment by pfalcon** [comment]
Same for nucleof429zi.rst.

**Comment by pfalcon** [comment]
Also nucleo412zg.rst

**Comment by galak** [comment]
@erwango any comments on this?

**Comment by erwango** [comment]
Well, I think this is indeed incorrect information.
I've been able to check flash is successful on nucleo_f429zi and nucleo_f412zg and I don't see why it shouldn't work on last one.
I'll fix this.
