### ISSUE TITLE
Bluetooth: Controller: Assert on CIS when connecting ACL after CIS disconnect

### ISSUE THREAD

**Issue by Thalley** [zephyrproject-rtos/zephyr#57744]
**Describe the bug**
The central will hit an assert if connecting and pairing an ACL after disconnecting a CIS:
```
ASSERTION FAIL [cis] @ WEST_TOPDIR/zephyr/subsys/bluetooth/controller/ll_sw/ull_conn_iso.c:215
```

**To Reproduce**
1. Build `/samples/bluetooth/hci_rpmsg/` with `nrf5340_cpunet_iso-bt_ll_sw_split.conf` for the nRF5340 netcore, then as the central do the following
2. Connect ACL_1
3. Pair ACL_1
4. Create CIG_1
5. Connect CIS_1
6. Disconnect CIS_1
7. Delete CIG_1
8. Connect ACL_2
9. Pair ACL_2
10. See the above assert

**Expected behavior**
Expect pairing to not have anything to do with CIS and the assert. 

**Impact**
Significant

**Logs and console output**
[central_cis_disconnect.txt](https://github.com/zephyrproject-rtos/zephyr/files/11442605/central_cis_disconnect.txt)

**Environment (please complete the following information):**
 - Commit SHA or Version used: f66b14974268b9692980317dfb4663a03aee949b

**Additional context**
N/A

**Comment by cvinayak** [comment]
@erbr-ot seems like https://github.com/zephyrproject-rtos/zephyr/pull/56979 has exposed possible issue in use of `ll_conn_iso_stream_get_by_acl` ?
