### ISSUE TITLE
Introduce `EXTRA_DTC_OVERLAY_FILE`, `EXTRA_CONF_FILE` and improve naming consistency.

### ISSUE THREAD

**Issue by tejlmand** [zephyrproject-rtos/zephyr#57775]
**Is your enhancement proposal related to a problem? Please describe.**
The name `OVERLAY_CONFIG` sometimes causes confusion with `DTC_OVERLAY_FILE`, both in what they configure and how they behave.

An example is the way `DTC_OVERLAY_FILE` is used. `DTC_OVERLAY_FILE` behave similar to `CONF_FILE` in the sense that when it is defined, then it will be used instead on automatic selection of app / board specific overlays, ref: https://docs.zephyrproject.org/latest/build/dts/howtos.html#set-devicetree-overlays
Whereas `OVERLAY_CONFIG` is appended to config files defined by `CONF_FILE`.

This proposal is to deprecate `OVERLAY_CONFIG` and instead introduce EXTRA_CONF_FILE, and introduce an `EXTRA_DTC_OVERLAY_FILE` which behave similarly, but for devicetree overlays.

That way Zephyr will have:

-    `DTC_OVERLAY_FILE`, and `EXTRA_DTC_OVERLAY_FILE`
-    `CONF_FILE`, and `EXTRA_CONF_FILE`

this resembles what we have with `ZEPHYR_MODULES`, like

-    `ZEPHYR_MODULES` and `ZEPHYR_EXTRA_MODULES`

Note, `ZEPHYR_EXTRA_MODULES` should be renamed to `EXTRA_ZEPHYR_MODULES` for consistency with above naming scheme.

this will bring more consistency to how build variables are named and used, as well as being more intuitive in how they behave.

Existing variables, `OVERLAY_CONFIG` and `ZEPHYR_EXTRA_MODULES` can thus be deprecated.

This will create the following pattern:
`<var-name>` replaces any automatic / default assignment.
`EXTRA_<var-name>` extends `<var-name>` with extra values.

**Additional context**
Ref:
https://github.com/zephyrproject-rtos/zephyr/pull/57661#issuecomment-1541784467
https://github.com/zephyrproject-rtos/zephyr/pull/57661#issuecomment-1542591163

**Comment by jfischer-no** [comment]
> An example is the way `DTC_OVERLAY_FILE` is used. `DTC_OVERLAY_FILE` behave similar to `CONF_FILE` in the sense that when it is defined, then it will be used instead on automatic selection of app / board specific overlays, ref: https://docs.zephyrproject.org/latest/build/dts/howtos.html#set-devicetree-overlays
> Whereas `OVERLAY_CONFIG` is appended to config files defined by `CONF_FILE`.

>This proposal is to deprecate OVERLAY_CONFIG and instead introduce EXTRA_CONF_FILE, and introduce an EXTRA_DTC_OVERLAY_FILE which behave similarly, but for devicetree overlays.

So add more confusion. Better to rename OVERLAY_CONFIG to CONFIG_OVERLAY_FILE. 
IIRC `DTC_OVERLAY_FILE` should not behave how it is described in the documentation, but like EXTRA_DTC_OVERLAY_FILE suggested by you. IMO EXTRA_.*_OVERLAY_FILE combination is awkward, but I can live with it if we keep and rename `DTC_OVERLAY_FILE` to `ULTRA_DTC_OVERLAY_FILE`.
