### ISSUE TITLE
bluetooth test_controller_4_0 fails to build on nrf52840_pca10056

### ISSUE THREAD

**Issue by galak** [zephyrproject-rtos/zephyr#5779]
./scripts/sanitycheck -p nrf52840_pca10056 -s tests/bluetooth/init/test_controller_4_0

fails due to:

/home/galak/git/zephyr/subsys/bluetooth/controller/hal/nrf5/radio/radio.c:609:4: error: ‘HAL_SW_SWITCH_TIMER_S8_DISABLE_PPI_DISABLE’ undeclared (first use in this function)
    HAL_SW_SWITCH_TIMER_S8_DISABLE_PPI_DISABLE |
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

This seems to be due to the define of HAL_SW_SWITCH_TIMER_S8_DISABLE_PPI_DISABLE in subsys/bluetooth/controller/hal/nrf5/radio/radio_nrf5_ppi.h only being valid if !CONFIG_BT_CTLR_TIFS_HW.

So not sure what the proper fix is.

**Comment by carlescufi** [comment]
@ioannis, @cvinayak can you help out with this one? I think it might be related to the latest refactor
