### ISSUE TITLE
ILPS22QS missing in Kconfig.st

### ISSUE THREAD

**Issue by rubienr** [zephyrproject-rtos/zephyr#57825]
In order to be able to use the ILPS22QS driver it should be select-able in kcofig (i.e. `west build -t menuconfig`). 

I assume in [zephyr/modules/Kconfig.st](https://github.com/zephyrproject-rtos/zephyr/blame/6535d6a0e66df21cbfa7d2b949763d5a74930583/modules/Kconfig.st#L57) in section `HAS_STMEMSC` the following is missing:
```
config USE_STDC_ILPS22QS
    bool
```

Alternatively I added the mentioned lines manually to the `Kconfig.st` file, run `west build -t menuconfig`, built the project successfully and used the exposed API from `ilps22qs_reg.h`.

**Comment by erwango** [comment]
Thanks @rubienr for catching this!
Since you've been able to fix it, would you mind contribute your fix directly ?
