### ISSUE TITLE
BLE Host may send an uninitialized sec_adv_phy 

### ISSUE THREAD

**Issue by yeaissa** [zephyrproject-rtos/zephyr#57885]
**Describe the bug**

The host may send an uninitialized sec_adv_phy (secondary advertising phy) parameter to the controller when using extended advertising.

The code bellow shows how the value of sec_adv_phy is determined right now depending on the advertising options (source zephyr/subsys/bluetooth/host/adv.c):

```c
if (param->options & BT_LE_ADV_OPT_EXT_ADV) {
	if (param->options & BT_LE_ADV_OPT_NO_2M) {
		cp->sec_adv_phy = BT_HCI_LE_PHY_1M;
	} else {
		cp->sec_adv_phy = BT_HCI_LE_PHY_2M;
	}
}

if (param->options & BT_LE_ADV_OPT_CODED) {
	cp->prim_adv_phy = BT_HCI_LE_PHY_CODED;
	cp->sec_adv_phy = BT_HCI_LE_PHY_CODED;
}
```

It may happen that the host sends an unknown value of secondary PHY to the controller when none of those advertising parameters are enabled. (It is the case for BLE tester application)

**Impact**

A controller may fail to set advertising parameters when receiving an unknown value.

**Environment (please complete the following information):**
 - Zephyr version 3.3.0

**Comment by hermabe** [comment]
- The command struct is memset to 0 and a secondary phy value of 0 is RFU, which will be rejected by the controller. The function would simply return `-EIO`.
- Parameters are checked by `valid_adv_ext_param`, so one cannot set `BT_LE_ADV_OPT_CODED` but not `BT_LE_ADV_OPT_EXT_ADV`. Can you provide a test case that reproduces your issue?
