### ISSUE TITLE
wiki/Development-Model is out of date

### ISSUE THREAD

**Issue by galak** [zephyrproject-rtos/zephyr#5794]
https://github.com/zephyrproject-rtos/zephyr/wiki/Development-Model references JIRA & gerrit which we clearly don't use anymore.

**Comment by dbkinder** [comment]
I've done a first pass changing references to Jira and Gerrit and updating the images accordingly.  @galak can you look through the instructions at https://github.com/zephyrproject-rtos/zephyr/wiki/Development-Model#Maintaining_subsystem_branches and update them to the correct non-Gerrit workflow steps (or let me know what the steps should be and I can edit)

**Comment by galak** [comment]
I updated to remove the subsystem stuff since we don't really have proper subsystem branches at this point.

**Comment by galak** [comment]
@dbkinder can you look at the 'Flow3' link in Communication and Collaboration going nowhere.

**Comment by dbkinder** [comment]
Typo in the link to this image is fixed.
