### ISSUE TITLE
release: release-notes: Release notes should not list closed stale issues as "addressed"

### ISSUE THREAD

**Issue by kartben** [zephyrproject-rtos/zephyr#57966]
Spotted this completely by chance: the "Addressed Issues" list of issues in the release notes includes *all* closed issue in the release time frame, no matter why they were closed. This includes issues that have been closed as being stale, and hence not acted upon in any way. These issues may or may not have been "invalid"/"not a bug", but since no human got involved in making this decision, I don't think they should be considered "Addressed".

From Release notes 3.3, see e.g. #51873  as one of the many issues listed as addressed

Relevant section of `list_issues.py`

https://github.com/zephyrproject-rtos/zephyr/blob/7039f8ce9c2787f37f5a97c3aca1e1541a0d7d07/scripts/release/list_issues.py#L108

**Comment by stephanosio** [comment]
To fix this, two things need to be done:

1. Make the "stale bot" close issues as "not planned" instead of "completed."
2. Make `list_issues.py` filter by `reason:completed`.

**Comment by stephanosio** [comment]
> * Make the "stale bot" close issues as "not planned" instead of "completed."

That was (unintentionally) done by https://github.com/zephyrproject-rtos/zephyr/commit/f03190a2e1ce6f442f0b956de51229851846e3c8, because `actions/stale@v8` closes stale issues as `not_planned`.

So only the `list_issues.py` needs to be updated.

**Comment by kartben** [comment]
> > * Make the "stale bot" close issues as "not planned" instead of "completed."
> 
> That was (unintentionally) done by https://github.com/zephyrproject-rtos/zephyr/commit/f03190a2e1ce6f442f0b956de51229851846e3c8, because `actions/stale@v8` closes stale issues as `not_planned`.

Neat :)

> So only the `list_issues.py` needs to be updated.

Yes and no: the status of issues that where improperly marked as completed pre https://github.com/zephyrproject-rtos/zephyr/commit/f03190a2e1ce6f442f0b956de51229851846e3c8 would still need to be fixed (or worst case scenario treated as a special case in `list_issues.py`)
