### ISSUE TITLE
SPI subsystem API & features updates

### ISSUE THREAD

**Issue by galak** [zephyrproject-rtos/zephyr#5797]
This issue catches the major issues that need to be finished for 
- [x] update controller drivers to new API
- [x] update sensor/client drivers to new API
- [ ] utilize device tree for all new client and sensor drivers

**Comment by tbursztyka** [comment]
For the 2 firsts point, see PR #5921 all is done there.

For the third, I have a PR in preparation already.

**Comment by carlescufi** [comment]
@tbursztyka Can we close this?

**Comment by tbursztyka** [comment]
yes!
