### ISSUE TITLE
hal: renesas: Add precompiled BLE controller image

### ISSUE THREAD

**Issue by andrzej-kaczmarek** [zephyrproject-rtos/zephyr#57987]
## Origin

This is a library which includes firmware for CMAC controller in Renesas SmartBond(tm) SoCs.

## Type

- [x] Precompiled library
- [x] Firmware image

## Module

hal_renesas

## Purpose

The purpose is to enable BLE support on DA1469x SoC. The library includes firmware for CMAC controller which is a separate core in DA1469x SoC. The firmware is copied to RAM and is executed by CMAC controller core from there.

## Pull Request

https://github.com/zephyrproject-rtos/hal_renesas/pull/2

## Dependencies

none

## License

Apache-2.0

**Comment by carlescufi** [comment]
@andrzej-kaczmarek this was discussed in yesterday's TSC, here's an excerpt from the minutes:

![image](https://github.com/zephyrproject-rtos/zephyr/assets/12450381/7eb8edf7-45b9-4ee9-9b21-ca0093961c52)

https://docs.google.com/document/d/1cMkXkFN-Yje-7zIGZmWMfkrVCju85UNnKDfjng9vEv0/edit#

**Comment by carlescufi** [comment]
@andrzej-kaczmarek the firts thing to be fixed is that we do not host `.a` files of any kind in repos in this organization. Please read through the binary blobs page and move the blob to an external hosting provider (can be for example nimble's GitHub):

https://docs.zephyrproject.org/latest/contribute/bin_blobs.html
https://docs.zephyrproject.org/latest/develop/modules.html#binary-blobs

You can find multiple examples in hal_infineon and hal_espressif

**Comment by carlescufi** [comment]
This passed the TSC vote on 31st May 2023.
