### ISSUE TITLE
rtio: doc: RTIO doc still refers to cancellation as an "outstanding question"

### ISSUE THREAD

**Issue by kartben** [zephyrproject-rtos/zephyr#58083]
@yperess I just spotted https://docs.zephyrproject.org/latest/services/rtio/index.html#cancellation -- this section should be removed, right? or rather, maybe turned into a proper paragraph outside of the "outstanding questions" section to document what the new cancellation API allows to do?

https://github.com/zephyrproject-rtos/zephyr/blob/main/doc/services/rtio/index.rst?plain=1#L215-L221

Thanks!

**Comment by kartben** [comment]
@yperess just making sure this gets your attention - thanks!

**Comment by yperess** [comment]
> @yperess just making sure this gets your attention - thanks!

Ack, I'll send a PR later this week
