### ISSUE TITLE
CII Badge: Default crytpo chooses weak algorithms

### ISSUE THREAD

**Issue by agross-linaro** [zephyrproject-rtos/zephyr#5813]
The default security mechanisms within the software produced by the project MUST NOT depend on cryptographic algorithms or modes with known serious weaknesses (e.g., the SHA-1 cryptographic hash algorithm or the CBC mode in SSH). 

We need to modify the current crypto samples to use algorithms with no known weaknesses.

**Comment by nashif** [comment]
> We need to modify the current crypto samples to use algorithms with no known weaknesses.

I do not think this need to depend on samples, if we have some default system configuration that selects a weak crypto, then it should be changed, the samples and tests need to test all cryptos, also the weak ones.

So this should be seen as "Met" if we have no defaults in the system pointing to weak cryptos, and I do not think we have this, do we?

**Comment by agross-linaro** [comment]
Samples have been added/modified to avoid non-weak crypto.  Specifically we have a google iot application that shows an example of how to properly implement TLS communications with a cloud service.
