### ISSUE TITLE
Zephyr APIs for STM32 Controller - Write/Erase/Read time measurement for Internal Flash

### ISSUE THREAD

**Issue by bhardadinesh-eaton** [zephyrproject-rtos/zephyr#58137]
I want to calculate the Read/Write/Erase Time for Internal Flash of STM32 Controller. I want to know, Is there any APIs are available to measure the Read/Write/Erase Time?. We have used standard API for the Read/Write/Erase for Internal Flash of STM32 Controller.

If any APIs are available, Please suggest where I can find it.

**Comment by nordicjm** [comment]
You can use the flash shell functions, e.g. see https://github.com/zephyrproject-rtos/zephyr/blob/main/drivers/flash/flash_shell.c#L325
