### ISSUE TITLE
usbd_shell: Conflict USB devices with user-defined USB device

### ISSUE THREAD

**Issue by Cherish-Gww** [zephyrproject-rtos/zephyr#58168]
**Describe the bug**
The USBD_DEVICE_DEFINE defined in zephyr/subsys/usb/device_next/usbd_shell.c will conflict the user-defined USB device
Thereby affecting the enumeration of user-defined USB devices

https://github.com/zephyrproject-rtos/zephyr/blob/91ffb72c3b07338f5f001d98b51417fa59d53a62/subsys/usb/device_next/usbd_shell.c#LL245C1-L245C1

the usbd_event_handler will be trigger twice

```
static void usbd_thread(void)
{
	struct udc_event event;

	while (true) {
		k_msgq_get(&usbd_msgq, &event, K_FOREVER);

		STRUCT_SECTION_FOREACH(usbd_contex, uds_ctx) {
			if (uds_ctx->dev == event.dev) {
				usbd_event_handler(uds_ctx, &event);
			}
		}
	}
}
```

**Comment by jfischer-no** [comment]
I already have a fix for that.
