### ISSUE TITLE
socket.h: Using #define for POSIX redefinition of zsock_ functions has unintended consequences

### ISSUE THREAD

**Issue by GAnthony** [zephyrproject-rtos/zephyr#5817]
While porting mqtt to sockets, by including socket.h in mqtt.c, the socket.h definition:

`#define connect zsock_connect
`

breaks mqtt.c compilation by replacing ctx->connect with ctx->zsock_connect; however, zsock_connect is not a field of the struct mqtt_ctx  (but 'connect' is).

In general, this could be an issue with any function symbol re-definition made via #define.

A safer though more verbose approach which resolves the problem would be to use inline functions for the re-definitions:

```
static inline int connect(int sock,
			  const struct sockaddr *addr,
			  socklen_t addrlen)
{
	return zsock_connect(sock, addr, addrlen);
}
```

I log this as an issue to see if there are any other better suggestions.

I can workaround the problem for now by ensuring socket.h comes before all appearances of the symbol 'connect' in all headers and source files (the pre-processor effectively converting each instance consistently to 'zsock_connect').

**Comment by pfalcon** [comment]
@GAnthony : Ack. Well, that shows why I'm conservative with not touching "connect" and friends by default - even if planned about, some issues still pop up (so not planning even worse ;-) ). Preprocessor defines were also selected as a conservative measure "working everywhere for decades", but I agree that the issue you present needs to be fixed, in the way suggested.

Let me know if you're interested to prepare a patch, or if you'd prefer that I did that.

**Comment by GAnthony** [comment]
@pfalcon: I can do the patch.

**Comment by pfalcon** [comment]
Thanks!
