### ISSUE TITLE
rtio: Sign compare error during project build with I2C enabled

### ISSUE THREAD

**Issue by Zzzwierzak** [zephyrproject-rtos/zephyr#58186]
Describe the bug
Compiling project with I2C enabled and -Werror and -Wsign-compare ends with error in rtio header and others.

To Reproduce

    In i2c_api test sample CMakeList file add :
    set(CMAKE_CXX_FLAGS "-Wall -Werror -Wsign-compare")
    set(CMAKE_C_FLAGS "${CMAKE_CXX_FLAGS}")
    Build sample for qemu_cortex_m3.

Expected behavior
No sign compare errors.

Logs and console output:
In file included from /home/zephyr/include/zephyr/drivers/i2c.h:28,
                 from /home/zephyr/samples/drivers/i2s/echo/src/codec.c:10:
/home/zephyr/include/zephyr/rtio/rtio.h: In function 'z_impl_rtio_cqe_copy_out':
/home/zephyr/include/zephyr/rtio/rtio.h:1385:44: error: comparison of integer expressions of different signedness: 'uint64_t' {aka 'long long unsigned int'} and 'int64_t' {aka 'long long int'} [-Werror=sign-compare]
 1385 |         } while (copied < cqe_count && end > k_uptime_ticks());

and others.

Environment:

    OS: Ubuntu 22.04
    Toolchain: Zephyr SDK 16.0
    Commit SHA : https://github.com/zephyrproject-rtos/zephyr/commit/91ffb72c3b07338f5f001d98b51417fa59d53a62

**Comment by teburd** [comment]
Believe this is fixed with #58422 please reopen if not
