### ISSUE TITLE
Bluetooth: Host: hci.h header include depends on conn.h

### ISSUE THREAD

**Issue by cvinayak** [zephyrproject-rtos/zephyr#58214]
**Describe the bug**
Samples, application and controller implementation needing `hci.h` header include has dependency on `conn.h` which makes host connection data types be included in source code compilations.

Dependency introduced in 0f06c7d

Refer to https://github.com/zephyrproject-rtos/zephyr/pull/58154#discussion_r1203243070

**To Reproduce**
NA

**Expected behavior**
`hci.h` should not include `conn.h` .

**Impact**
annoyance. stable API change?

**Logs and console output**
NA

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: Zephyr SDK,
 - Commit SHA or Version used: 5181b53

**Additional context**
NA

**Comment by kruithofa** [comment]
The fix for this issue is that hci.h only has typedefs and struct definitions. hci.h should be agnostic about the implementation
Create a new header file (for ex. hci_host.h) that contains the function prototypes
