### ISSUE TITLE
STM32F7 clock support should not be limited to F4

### ISSUE THREAD

**Issue by nickstoughton** [zephyrproject-rtos/zephyr#58249]
The `include/zephyr/drivers/clock_control/stm32_clock_control.h` header file treats F2X, F4X and F7X as all being supported by the `stmf4_clock.h` header. However, the F7 has additional clocks that are available as domain clocks for devices (such as the stm32 uart) and these do not work with the f4 header.

For example, the following DTS fragment while valid
```
&uart7 {
        clocks = <&rcc STM32_CLOCK_BUS_APB1 0x40000000>,
                 <&rcc STM32_SRC_HSI USART7_SEL(2)>;
};
```
does not work since `STM32_SRC_HSI` is not enabled in the F4 header.

**To Reproduce**
Using `samples/basic/button`, add an overlay for `nucleo_f746zg.overlay` like this:
```
&clk_hsi {
	status = "okay";
};

&usart3 {
	pinctrl-0 = < &usart3_tx_pc10 &usart3_rx_pc11 >;
	clocks = <&rcc STM32_CLOCK_BUS_APB1 0x40000000>,
                 <&rcc STM32_SRC_HSI USART3_SEL(2)>;
};
```
and build it. Note the failure to print anything.

1. cd samples/basic/button
2. west build --board=nucleo_746zg
3. west flash
4. connect external UART to pins PC10 and PC11
5. press button and observe no printk output

**Impact**
It is not possible to use domain clocks for STM32F7 UARTs (and possibly other peripherals).

**Patch**
```
diff --git a/include/zephyr/drivers/clock_control/stm32_clock_control.h b/include/zephyr/drivers/clock_control/stm32_clock_control.h
index 57a982388b..36ba6369c5 100644
--- a/include/zephyr/drivers/clock_control/stm32_clock_control.h
+++ b/include/zephyr/drivers/clock_control/stm32_clock_control.h
@@ -18,9 +18,10 @@
 #elif defined(CONFIG_SOC_SERIES_STM32F3X)
 #include <zephyr/dt-bindings/clock/stm32f3_clock.h>
 #elif defined(CONFIG_SOC_SERIES_STM32F2X) || \
-       defined(CONFIG_SOC_SERIES_STM32F4X) || \
-       defined(CONFIG_SOC_SERIES_STM32F7X)
+       defined(CONFIG_SOC_SERIES_STM32F4X)
 #include <zephyr/dt-bindings/clock/stm32f4_clock.h>
+#elif defined(CONFIG_SOC_SERIES_STM32F7X)
+#include <zephyr/dt-bindings/clock/stm32f7_clock.h>
 #elif defined(CONFIG_SOC_SERIES_STM32G0X)
 #include <zephyr/dt-bindings/clock/stm32g0_clock.h>
 #elif defined(CONFIG_SOC_SERIES_STM32G4X)
```

**Comment by erwango** [comment]
@nickstoughton Thanks for catching this.
Since you have the fix, would you mind pushing the change ?
