### ISSUE TITLE
Modem Shell missing line ending \r\n

### ISSUE THREAD

**Issue by ShahinHaque97-CT** [zephyrproject-rtos/zephyr#58307]
https://github.com/zephyrproject-rtos/zephyr/blob/main/drivers/modem/modem_shell.c @ line 141

		if (i == argc - 1) {
			ret = ms_send(mdm_ctx, "\r", 1);
		} else {
			ret = ms_send(mdm_ctx, " ", 1);
		}

changed to 

		if (i == argc - 1) {
			ret = ms_send(mdm_ctx, "\r", 1);
			ret = ms_send(mdm_ctx, "\n", 1);
		} else {
			ret = ms_send(mdm_ctx, " ", 1);
		}

The modem shell only sends back \r, some devices require \r\n. Is there a config to accommodate both options?

**Comment by nashif** [comment]
can you please submit a PR with the fix?
