### ISSUE TITLE
Script to import mcux sdk

### ISSUE THREAD

**Issue by MaureenHelm** [zephyrproject-rtos/zephyr#5833]
New versions of the mcux sdk need to be imported whenever a new nxp soc is added to zephyr, or when nxp releases updated mcux drivers for an existing soc. Create a script to automate importing the mcux sdk into zephyr.

**Comment by SebastianBoe** [comment]
For nrf's equivalent problem we intend to eventually re-use the mechanism used by OpenThread to import external source code. 

To solve this problem one might want to look into if using CMake's ExternalProject feature is powerful enough.

https://github.com/SebastianBoe/zephyr/blob/50e285cd6879da8941dab56d348ce222bc11dff0/subsys/net/lib/openthread/CMakeLists.txt

https://cmake.org/cmake/help/latest/module/ExternalProject.html

**Comment by MaureenHelm** [comment]
Fixed by #8923
