### ISSUE TITLE
tests: drivers: dma: build failure for mimxrt595_evk_cm33 and mimxrt685_evk_cm33

### ISSUE THREAD

**Issue by cfriedt** [zephyrproject-rtos/zephyr#58376]
**Describe the bug**
Multiple DMA testsuites were failing to build in CI for the `mimxrt595_evk_cm33` and `mimxrt685_evk_cm33` boards.

The failures were determined to be unrelated to the changes in https://github.com/zephyrproject-rtos/zephyr/pull/58375.

the problem you're facing:
 - What target platform are you using? CI Only
 - What have you tried to diagnose or workaround this issue? Read the logs at the linked PR
 - Is this a regression? Presumably, yes, but I have not bisected it.
 - ...

**To Reproduce**
* `west build -b mimxrt595_evk_cm33  tests/drivers/dma/loop_transfer`
* `west build -b mimxrt595_evk_cm33  tests/drivers/dma/chan_blen_transfer`
* `west build -b mimxrt685_evk_cm33  tests/drivers/dma/loop_transfer`
* `west build -b mimxrt685_evk_cm33  tests/drivers/dma/chan_blen_transfer`

**Expected behavior**
CI shouldn't fail

**Impact**
Currently breaking CI

**Logs and console output**
See https://github.com/zephyrproject-rtos/zephyr/actions/runs/5106587709/jobs/9178887624

**Environment (please complete the following information):**
 - OS: (e.g. Linux, MacOS, Windows): CI (Linux)
 - Toolchain (e.g Zephyr SDK, ...): Zephyr SDK v0.16.1 
 - Commit SHA or Version used: 86d63c5cff11654088db423c6d419aa8c0304c6c

**Additional context**

**Comment by ycsin** [comment]
1. https://github.com/zephyrproject-rtos/zephyr/blob/main/drivers/dma/dma_mcux_lpc.c#L754
2. https://github.com/zephyrproject-rtos/zephyr/blob/main/boards/arm/mimxrt595_evk/mimxrt595_evk_cm33.dts#L401
3. https://github.com/zephyrproject-rtos/zephyr/blob/main/dts/arm/nxp/nxp_rt5xx_common.dtsi#L325
4. https://github.com/zephyrproject-rtos/zephyr/blob/main/dts/bindings/dma/nxp%2Clpc-dma.yaml#L20

Looks like `nxp,dma-num-of-otrigs` should be a required property if it is unconditionally used in the [dma driver](https://github.com/zephyrproject-rtos/zephyr/blob/main/drivers/dma/dma_mcux_lpc.c#L754), it was introduced in #57049 a few days ago, CC @EmilioCBen 

Everything that uses `compatible = "nxp,lpc-dma"` should have [these](https://github.com/zephyrproject-rtos/zephyr/blob/main/dts/arm/nxp/nxp_lpc55S6x_common.dtsi#L182)
