### ISSUE TITLE
can anyone help me to sort out this issue..!

### ISSUE THREAD

**Issue by hariprasath1163** [zephyrproject-rtos/zephyr#58424]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context or graphics (drag-and-drop an image) about the feature request here.

**Comment by hariprasath1163** [comment]
![image](https://github.com/zephyrproject-rtos/zephyr/assets/134058526/60004d3a-f9cc-40d2-aea5-145b3b9d8a9b)

I am using a 2.8 inch TFT display.
while including the #include <display> shows error.
Will you ppl please help to sort it out.

Thankyou.

**Comment by carlescufi** [comment]
Please use Discord or any of the other means of help we have. GitHub issues are for bugs or enhancements.
