### ISSUE TITLE
Bluetooth: Host: GATT CCC not stored when `CONFIG_BT_SETTINGS_CCC_STORE_ON_WRITE=n`

### ISSUE THREAD

**Issue by theob-pro** [zephyrproject-rtos/zephyr#58471]
**Describe the bug**

When CCC or CF store on write is disabled and the other one is enabled, leading to the delayed store being enabled. This cause the value of the corresponding `n` selected option to not be stored at all.

**To Reproduce**

See the BabbleSim test with `prj_2.conf` of this PR: https://github.com/zephyrproject-rtos/zephyr/pull/58470.

**Expected behavior**

If `CONFIG_BT_SETTINGS_CCC_STORE_ON_WRITE` or `CONFIG_BT_SETTINGS_CF_STORE_ON_WRITE` are not selected they should be stored on disconnection. 

**Impact**

The impact of this bug is not big, by default `CONFIG_BT_SETTINGS_CCC_STORE_ON_WRITE` and `CONFIG_BT_SETTINGS_CF_STORE_ON_WRITE` are selected.

**Comment by alwa-nordic** [comment]
Thanks for the bug report! Do we know when this bug was introduced?
