### ISSUE TITLE
drivers: ieee802154: RSSI value converted inconsistently across drivers

### ISSUE THREAD

**Issue by fgrandel** [zephyrproject-rtos/zephyr#58494]
**Describe the bug**

The RSSI value in net_pkt (net_pkt_cb_ieee802154.rssi) is used inconsistently across drivers.

Example 1: At least one driver (nRF5) casts the signed RSSI (dBm?) value returned from the HW to the unsigned net_pkt_cb_ieee802154.rssi value without conversion.

Example 2: The cc13/26xx drivers convert the signed RSSI dBm value returned from the HW to an unsigned unitless value evenly spread to the 0-255 uint8 range of net_pkt_cb_ieee802154.rssi.

What is the intended use and range of this value? Depending on the answer one of the two implementations is probably wrong.

**To Reproduce**

n/a

**Expected behavior**

As proposed by @nandojve below, the RSSI value in net_pkt could be interpreted as defined in the IEEE 802.15.4 standard. This makes even more sense as the attribute is part of an IEEE 802.15.4-specific control block. This means that we don't have to change the API of net_pkt at all but only document the expected value range plus provide some utility functions for dBm-to-macRSSI and macRSSI-to-dBm conversion.

> 6.16.2.8 Received Signal Strength Indicator (RSSI)
> ...
> RSSI is represented as one octet of integer as shown in Table 8-108; therefore, the minimum and maximum values
> are 0 (–174 dBm) and 254 (80 dBm), respectively. 255 is reserved.

I can provide fixes for net core and at least the nRF5 and CC13/26xx drivers if we agree on this intended behavior.

**Impact**

RSSI value is not comparable between different driver implementations and its physical interpretation unclear or ambivalent. Therefore it is probably not too useful right now.

**Logs and console output**

n/a

**Environment (please complete the following information):**

n/a

**Comment by nandojve** [comment]
Just to mention that IEEE Std 802.15.4-2020 well define the **RSSI** or **macRSSI** and maybe we should consider this to take decision.

_6.16.2.8 Received Signal Strength Indicator (RSSI)
...
RSSI is represented as one octet of integer as shown in Table 8-108; therefore, the minimum and maximum values
are 0 (–174 dBm) and 254 (80 dBm), respectively. 255 is reserved._

There are mentions of `RSSI` at _MCPS-DATA.indication_ introduced at IEEE Std 802.15.4-2015 and `macRSSI` at _7.4.2.17 SRM IE_ since IEEE Std 802.15.4-2020.

**Comment by nandojve** [comment]
There is another option which is provide a `dBm` version of set `rssi` that maps to correct integer range directly.
https://github.com/zephyrproject-rtos/zephyr/blob/941e4f000b4175b7c7d8cb30c56931b172eb68d3/include/zephyr/net/ieee802154_pkt.h#L90-L93

**Comment by fgrandel** [comment]
@rlubos Just a heads up to you as I suppose that this is your area of maintenance. If you agree with the solution proposed by Gerson I'll provide a patch.

**Comment by rlubos** [comment]
Sounds reasonable to standardize this. Just note, that OT layer should do the reverse conversion, as it expects RSSI in dBm.

> At least one driver (nRF5) casts the signed RSSI (dBm?)

It's most likely the case, but @jciupis can you confirm that the nRF 15.4 driver reports RSSI in dBm?

**Comment by jciupis** [comment]
@rlubos that's correct, the nRF driver reports RSSI in dBm.

**Comment by fgrandel** [comment]
@rlubos @nandojve @jciupis Thanks for looking into this. I'll provide a PR for this along the lines proposed by @nandojve then. :-)
