### ISSUE TITLE
Issue with capturing phandles in a property 

### ISSUE THREAD

**Issue by aisri** [zephyrproject-rtos/zephyr#58501]
**NOTE**
please use uploaded patch for replicating the issue:
[0001-issue-with-capturing-phandles-in-a-parent-s-property.patch](https://github.com/zephyrproject-rtos/zephyr/files/11618578/0001-issue-with-capturing-phandles-in-a-parent-s-property.patch)

**Describe the bug**
build fails when capturing phandles of nodes. 
in the below device node definition, capturing phandles of d1, d2 and d3 in `devs` fails
```
{
        test_dev: test_dev@deadbeef {
            status = "okay";
            compatible = "test,device";
            reg = <0xdeadbeef 0x100>;

            fsms = <&a_fsm>, <&b_fsm>;
            devs = <&d1>, <&d2>, <&d3>;

            #address-cells = <1>;
            #size-cells = <0>;

            edge: arrow {
                compatible = "test,edge";
                #edge-cells = <2>;
            };

            vertex: point {
                compatible = "test,node";
                #edge-cells = <1>;
            };

            a_fsm: aa_fsm {
                compatible = "test,fsm";
                edges = <&vertex ST_B &edge ST_A 2>,
                        <&vertex ST_B &edge ST_A 11>,
                        <&vertex ST_C &edge ST_A 14>,
                        <&vertex ST_A &edge ST_C 12 &edge ST_B 7 &edge ST_B 1>;
            };

            b_fsm: bb_fsm {
                compatible = "test,fsm";
                edges = <&vertex ST_B &edge ST_A 3>,
                        <&vertex ST_C &edge ST_A 5>,
                        <&vertex ST_B &edge ST_A 1>,
                        <&vertex ST_A &edge ST_C 4 &edge ST_B 10 &edge ST_B 0>;
            };

            d1: dev@200 {
                reg = <0x200>;
                parent = <&d1>;
                profile = <&a_fsm>;
            };
            d2: dev@400 {
                reg = <0x400>;
                parent = <&d1>;
                profile = <&b_fsm>;
            };
            d3: dev@600 {
                reg = <0x600>;
                parent = <&d1>;
                profile = <&b_fsm>;
            };
        };
    };

```

Platform independent fails in c-preprocessing expansion

**To Reproduce**
Apply the patch above
and run the following command:
```
west build -b 96b_carbon samples/hello_world/ -DEXTRA_CFLAGS=-save-temps=obj --pristine
```

**Expected behavior**
Build succeeds

**Impact**
Found a workaround. 

**Logs and console output**
error:

```
/Users/$HOME/projects/zephyr/zephyr/include/zephyr/device.h:975:1: note: in expansion of macro 'DT_FOREACH_STATUS_OKAY_NODE'
  975 | DT_FOREACH_STATUS_OKAY_NODE(Z_MAYBE_DEVICE_DECLARE_INTERNAL)
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/$HOME/projects/zephyr/zephyr/include/zephyr/device.h:95:45: error: pasting "dts_ord_" and "-" does not give a valid preprocessing token
   95 | #define Z_DEVICE_DT_DEV_ID(node_id) _CONCAT(dts_ord_, DT_DEP_ORD(node_id))
      |                                             ^~~~~~~~
/Users/sreekanth/projects/zephyr/zephyr/include/zephyr/toolchain/common.h:132:26: note: in definition of macro '_DO_CONCAT'
  132 | #define _DO_CONCAT(x, y) x ## y
      |                          ^
```

**Environment (please complete the following information):**
 - OS: MacOS
 - Toolchain: e.g Zephyr SDK
 - Commit SHA or Version used 
    - ```commit b97a4a52a8e957dc41b7a7c2bf67a877b35f96b3 (origin/main, origin/HEAD)```

[0001-issue-with-capturing-phandles-in-a-parent-s-property.patch](https://github.com/zephyrproject-rtos/zephyr/files/11618578/0001-issue-with-capturing-phandles-in-a-parent-s-property.patch)

**Comment by mbolivar-nordic** [comment]
From Discord, this looks like a bug in the DT python tooling. Some nodes appear not to be getting dependency ordinals assigned. Root cause still TBD.

**Comment by 57300** [comment]
> Some nodes appear not to be getting dependency ordinals assigned. Root cause still TBD.

The ordinals are unassigned, because the nodes in question have circular dependencies. This is a known limitation; see https://github.com/zephyrproject-rtos/zephyr/issues/57708 for more information.

What you could do now is delete the `fsms` and `devs` properties from your `test_dev` node, which would remove the circular dependencies and allow the build to succeed. Those properties look redundant anyway, because `test_dev` shouldn't need to reference its own child nodes using phandles, and it should be possible to tell whether a child node is an "fsm" or a "dev" based on its `compatible`.

**Comment by mbolivar-ampere** [comment]
> The ordinals are unassigned, because the nodes in question have circular dependencies. This is a known limitation; see #57708 for more information.

If that is the only error, then the SCC algorithm should have detected the cycle, though, I think.
