### ISSUE TITLE
    tests-ci : lpcxpresso54114_m4: libraries: spsc_pbuf_cache:  test Failed    

### ISSUE THREAD

**Issue by hakehuang** [zephyrproject-rtos/zephyr#58727]
**Describe the bug**
     test is Failed on v3.4.0-rc1-24-g5f5b34793dc8 on lpcxpresso54114_m4
    testcase path is libraries/spsc_pbuf_cache/stress

    see logs for details

    **To Reproduce**
    1. 
    ```
    scripts/twister --device-testing --device-serial /dev/ttyACM0 -p lpcxpresso54114_m4      --sub-test libraries.spsc_pbuf_cache
    ```
    or
    ```
    # cd tests/libraries/spsc_pbuf_cache/stress
    # west build -b lpcxpresso54114_m4
    # west flash
    ```
    2. See error

    **Expected behavior**
    test pass

    **Impact**

    **Logs and console output**
    
    ```
    START - test_stress
Reading from an interrupt, writing from a thread
0% remaining:14000 ms
0% remaining:13000 ms
0% remaining:12000 ms
0% remaining:11000 ms
0% remaining:10000 ms
0% remaining:9000 ms
0% remaining:8000 ms
0% remaining:7000 ms
0% remaining:6000 ms
0% remaining:5000 ms
0% remaining:4000 ms
0% remaining:3000 ms
0% remaining:2000 ms
0% remaining:1000 ms
Ztress execution report:
context 0:
- executed:36075, preempted:0
- ticks initial:4, optimized:4
context 1:
- executed:23513, preempted:2000
- ticks initial:4, optimized:4
Average CPU load:18%, measurements:144
Writes:35197 failures: 29
Writing from an interrupt, reading from a thread
100% remaining:14000 ms
Assertion failed at WEST_TOPDIR/zephyr/tests/lib/spsc_pbuf/src/main.c:439: stress_read: check_buffer(buf, len, ctx->read_cnt) is non-zero

FAIL - test_stress in 16.485 seconds

        
    ```

    **Environment (please complete the following information):**
     - OS: (e.g. Linux )
     - Toolchain (e.g Zephyr SDK)
     - Commit SHA or Version used: v3.4.0-rc1-24-g5f5b34793dc8
     
last pass on: zephyr-v3.3.0-4123-gd01780fc9403

**Comment by hakehuang** [comment]
@dleach02

**Comment by decsny** [comment]
Hi @hakehuang, I tried this test on the latest commit 44e691e20e0b323ad67227ee072bd4166c75d894 using this build command `west build -b lpcxpresso54114_m4 -p always tests/lib/spsc_pbuf/ -DCONFIG_SPSC_PBUF_CACHE_ALWAYS=y` and ran it on the board and the test passed. Is this the correct command to try to replicate the issue?

**Comment by hakehuang** [comment]
@decsny , Thanks a lor fo double checking, in v3.4.0-rc2-5-g98810bc7a1, I can not reproduce this issue.
