### ISSUE TITLE
    tests-ci : mimxrt1015_evk: portability: posix: headers.newlib.without_posix_api test fatal error

### ISSUE THREAD

**Issue by hakehuang** [zephyrproject-rtos/zephyr#58730]
**Describe the bug**
    headers.newlib.without_posix_api test is Timeout on v3.4.0-rc1-24-g5f5b34793dc8 on mimxrt1015_evk
    testcases include:
    - portability/posix/headers/newlib/without_posix_api/arpa_inet_h
    - portability/posix/headers/newlib/with_posix_api/arpa_inet_h
    - portability/posix/eventfd_basic/newlib/posix_api/eventfd_write_then_read

    see logs for details

    **To Reproduce**
    1. 
    ```
    scripts/twister --device-testing --device-serial /dev/ttyACM0 -p mimxrt1015_evk      --sub-test portability.posix
    ```
    or
    ```
    # cd tests/portability/posix/headers/newlib/without_posix_api/arpa_inet_h
    # west build -b mimxrt1015_evk
    # west flash
    ```
    2. See error

    **Expected behavior**
    test pass

    **Impact**

    **Logs and console output**
    
    ```
    ASSERTION FAIL [((((size_t)32) << 10) - (((uintptr_t) (&_end)) - 0x20000000)) >= 8192] @ WEST_TOPDIR/zephyr/lib/libc/newlib/libc-hooks.c:128
memory space available for newlib heap is less than the minimum required size specified by CONFIG_NEWLIB_LIBC_MIN_REQUIRED_HEAP_SIZE
E: r0/a1:  0x00000004  r1/a2:  0x00000080  r2/a3:  0x40184000
E: r3/a4:  0x6000a61d r12/ip:  0x00000000 r14/lr:  0x60004c0d
E:  xpsr:  0x410f0000
E: Faulting instruction address (r15/pc): 0x60011ad2
E: >>> ZEPHYR FATAL ERROR 4: Kernel panic on CPU 0
E: Current thread: 0x200017f8 (main)
E: Halting system

        
    ```

    **Environment (please complete the following information):**
     - OS: (e.g. Linux )
     - Toolchain (e.g Zephyr SDK)
     - Commit SHA or Version used: v3.4.0-rc1-24-g5f5b34793dc8

**Comment by dleach02** [comment]
@hakehuang, did this ever work before?
