### ISSUE TITLE
drivers: designware spi: uint8_t is not enough for fifo_depth

### ISSUE THREAD

**Issue by botbotty** [zephyrproject-rtos/zephyr#58771]
---
name: Bug report
about: drivers: designware spi
title: 'uint8_t is not enough for fifo_depth'
labels: bug
assignees: ''
---

**Describe the bug**
According to https://www.synopsys.com/dw/doc.php/iip/DW_apb_ssi/4.04a/doc/DW_apb_ssi_databook.pdf:
![image](https://github.com/zephyrproject-rtos/zephyr/assets/54848714/271b54a8-3430-4654-bc71-167ca46d263c)

FIFO depth can be 256, which will overflow the 8-bit unsigned int field shown below:
https://github.com/zephyrproject-rtos/zephyr/blob/b12eb78f35cecfda1e80cb37564d97b8a424f53b/drivers/spi/spi_dw.h#L35

Please also mention any information which could help others to understand
the problem you're facing:
 - What target platform are you using: any platform that uses designware spi

**To Reproduce**
1. set "fifo-depth = <256>" for any "snps,designware-spi" compatible node in devicetree source file, for example, `zephyr/dts/arc/synopsys/emsdp.dtsi`, which is included by `zephyr/boards/arc/emsdp/emsdp.dts`:
```diff
diff --git a/dts/arc/synopsys/emsdp.dtsi b/dts/arc/synopsys/emsdp.dtsi
index 375eb74559..58623fd4e0 100644
--- a/dts/arc/synopsys/emsdp.dtsi
+++ b/dts/arc/synopsys/emsdp.dtsi
@@ -111,7 +111,7 @@
                        compatible = "snps,designware-spi";
                        reg = <0xf1000000 0x1000>;
                        clocks = <&spiclk>;
-                       fifo-depth = <32>;
+                       fifo-depth = <256>;
                        interrupt-parent = <&intc>;
                        #address-cells = <1>;
                        #size-cells = <0>;
```
2. west build --board emsdp zephyr/samples/hello_world/ -- -DCMAKE_C_FLAGS=-Werror
3. build will fail:
```
...
In file included from .../zephyr/include/zephyr/devicetree.h:19,
                 from .../zephyr/include/zephyr/arch/arc/arch.h:19,
                 from .../zephyr/include/zephyr/arch/cpu.h:21,
                 from .../zephyr/include/zephyr/sys/cbprintf_internal.h:17,
                 from .../zephyr/include/zephyr/sys/cbprintf.h:124,
                 from .../zephyr/include/zephyr/logging/log_msg.h:11,
                 from .../zephyr/include/zephyr/logging/log_core.h:9,
                 from .../zephyr/include/zephyr/logging/log.h:11,
                 from .../zephyr/drivers/spi/spi_dw.c:13:
.../build/zephyr/include/generated/devicetree_generated.h:5954:48: error: unsigned conversion from 'int' to 'unsigned char' changes value from '256' to '0' [-Werror=overflow]
 5954 | #define DT_N_S_soc_S_spi_f1000000_P_fifo_depth 256
...
```

**Expected behavior**
build succeed without any warning or error

**Impact**
cannot use designware spi driver for my chip that has fifo-depth configured to 256.

**Logs and console output**
See above

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: Zephyr SDK 0.16.0
 - Commit SHA or Version used: ccfbac8b0721745b8bd4fb7386eb09086775765c

**Additional context**
none

**Comment by henrikbrixandersen** [comment]
Please use our bug template when reporting bugs. You need to edit this issue to include the needed information from https://github.com/zephyrproject-rtos/zephyr/blob/main/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by botbotty** [comment]
> Please use our bug template when reporting bugs. You need to edit this issue to include the needed information from https://github.com/zephyrproject-rtos/zephyr/blob/main/.github/ISSUE_TEMPLATE/bug_report.md

issue edited
