### ISSUE TITLE
enabling THREAD_MONITOR causes tests to fail

### ISSUE THREAD

**Issue by nashif** [zephyrproject-rtos/zephyr#5881]
I was trying something where I needed THREAD_MONITOR enabled, this caused the test to fail by just enabling the option without any code changes.

To reproduce:
```
$ cd tests/kernel/semaphore/sema_api
$ echo "CONFIG_THREAD_MONITOR=y" >> prj.conf
# build and run under qemu
```

Results:
```
***** BOOTING ZEPHYR OS v1.10.99 - BUILD: Jan 29 2018 20:18:28 *****
Running test suite test_sema_api
===================================================================
starting test - test_sema_thread2thread
0x00412098 is not a valid k_sem
FATAL: syscall _handler_k_sem_init failed check: access denied
***** Kernel OOPS! *****
Current thread ID = 0x004120c0
Faulting segment:address = 0x002b:0x00001370
eax: 0x00000000, ebx: 0x00000000, ecx: 0x00000000, edx: 0x00000000
esi: 0x00000000, edi: 0x00000000, ebp: 0x00000000, esp: 0x004083b8
eflags: 0x246
Fatal fault in thread 0x004120c0! Aborting.
QEMU: Terminated
```

**Comment by lpereira** [comment]
Requires CONFIG_OBJECT_TRACING=y in order to reproduce.

**Comment by andrewboie** [comment]
I still cannot reproduce this. The test passes for me.
My prj.conf:

```
CONFIG_ZTEST=y
CONFIG_IRQ_OFFLOAD=y
CONFIG_THREAD_MONITOR=y
CONFIG_OBJECT_TRACING=y
```

I verified these are all getting set in the generated .config

**Comment by nashif** [comment]
looks like it is a build system issue, @SebastianBoe , can you take a look?
if I first set configure in THREAD_MONITOR, it works. If I add OBJECT_TRACING=y and rebuild without cleaning, it fails, so something is off with kobject generation.

**Comment by SebastianBoe** [comment]
I think I have found the root-cause will push a fix when I have it.
