### ISSUE TITLE
Document IEEE 802.15.4 API

### ISSUE THREAD

**Issue by nandojve** [zephyrproject-rtos/zephyr#58818]
**Is your enhancement proposal related to a problem? Please describe.**
The documentation of **struct ieee802154_radio_api** is not clear. It is necessary know the return values that L2 handle and what calls are mandatory/optional.

**Describe the solution you'd like**
Improve documentation of **struct ieee802154_radio_api** with expected return values and identify what are the optional and mandatory calls.

**Comment by fgrandel** [comment]
Should be implemented now. Please recheck and consider closing.

**Comment by fgrandel** [comment]
Closing as done. Please re-open if I'm overlooking something.
