### ISSUE TITLE
RFC: API Change: BLE Mesh (cdb)

### ISSUE THREAD

**Issue by alxelax** [zephyrproject-rtos/zephyr#58883]
### Problem description

https://github.com/zephyrproject-rtos/zephyr/pull/57788

Tinycrypt is deprecated. BLE Mesh has strict architecture dependency on Tinycrypt. Additionally, strict dependency on Tinycrypt doesn't allow using ARM Trustzone feature that is represented on many modern chips as well as multicore chips where security is managed by a separate core.

### Proposed change

1. Make BLE Mesh architecture\implementation flexible and scalable in aspect of third party crypto libraries. 
2. Make API scalable to key representations.
3. Key representation within BLE Mesh within BLE Mesh depends on KConfig options (depends on chosen crypto library).
4. Support both Tinycrypt and PSA based crypto libraries. Tinycrypt is supported while it is alive, or PSA based crypto libraries reach comparable memory footprint.

## Detailed RFC

1. Key representation is hidden beyond abstract structure type. Real key representation depends on KConfig option (crypto library).
2. All functional collaboration within mesh is performed (if specification doesn't require pure key presence) using abstract type.
3. All public API operates only with abstract type. The PR changes only cdb structure.
4. Setting\getting keys in cdb is performed via new import\export API. Access to keys via pointer is not valid anymore.

### Dependencies

Access to keys those have been set via cdb via pointer is not valid anymore. This should be replaced by import\export functionality.
Sample:
old:
```
struct bt_mesh_cdb_app_key *key;

key = bt_mesh_cdb_app_key_alloc(net_idx, app_idx);
if (key == NULL) {
	printk("Failed to allocate app-key 0x%04x\n", app_idx);
	return;
}

bt_rand(key->keys[0].app_key, 16);
```
new:
```
struct bt_mesh_cdb_app_key *key;
uint8_t app_key[16];
int err;

key = bt_mesh_cdb_app_key_alloc(net_idx, app_idx);
if (key == NULL) {
	printk("Failed to allocate app-key 0x%04x\n", app_idx);
	return;
}

bt_rand(app_key, 16);

err = bt_mesh_cdb_app_key_import(key, 0, app_key);
if (err) {
	printk("Failed to import appkey into cdb. Err:%d\n", err);
	return;
}
```

### Concerns and Unresolved Questions

1. Bad integration mbedTLS PSA into Zephyr's build system. There is no any case CI that checks it. During refactoring, there were some regressions in this.
2. Enormously huge mbedTLS footprint.
3. mbedTLS PSA ITS doesn't support Zephyr's settings subsystem. It is possible to use only on POSIX platforms.
4. mbedTLS PSA ITS based on POSIX file access to that is not thread safe. Parallel bsim tests running is always failed.
5. TF-M doesn't work correctly with Zephyr's settings subsystem. 

## Alternatives

Tinycrypt is morally deprecated.
If Tinycrypt is not going to support ARM Trustzone and HW features related to Trustzone chip vendors features, then there are no alternatives.

**Comment by carlescufi** [comment]
Architecture WG:

- Nearly no changes to users that want to continue to use TinyCrypt
- No objections
