### ISSUE TITLE
Not able to build zephyr example application

### ISSUE THREAD

**Issue by Kannannnnn** [zephyrproject-rtos/zephyr#58892]
steps to reproduce the error
step 1) west init -m https://github.com/zephyrproject-rtos/example-application --mr main my-workspace
Output:nan@Kannan:~$ west init -m https://github.com/zephyrproject-rtos/example-application --mr main my-workspace
=== Initializing in /home/kannan/my-workspace
--- Cloning manifest repository from https://github.com/zephyrproject-rtos/example-application, rev. main
Cloning into '/home/kannan/my-workspace/.west/manifest-tmp'...
remote: Enumerating objects: 371, done.
remote: Counting objects: 100% (296/296), done.
remote: Compressing objects: 100% (144/144), done.
remote: Total 371 (delta 127), reused 209 (delta 98), pack-reused 75
Receiving objects: 100% (371/371), 58.86 KiB | 369.00 KiB/s, done.
Resolving deltas: 100% (139/139), done.
--- setting manifest.path to example-application
=== Initialized. Now run "west update" inside /home/kannan/my-workspace.
step 2)west update
output:nan@Kannan:~$ cd my-workspace
kannan@Kannan:~/my-workspace$ west update
=== updating zephyr (zephyr):
--- zephyr: initializing
Initialized empty Git repository in /home/kannan/my-workspace/zephyr/.git/
--- zephyr: fetching, need revision main
remote: Enumerating objects: 867340, done.
remote: Counting objects: 100% (787/787), done.
remote: Compressing objects: 100% (413/413), done.
remote: Total 867340 (delta 369), reused 632 (delta 346), pack-reused 866553
Receiving objects: 100% (867340/867340), 573.63 MiB | 3.45 MiB/s, done.
Resolving deltas: 100% (657283/657283), done.
From https://github.com/zephyrproject-rtos/zephyr
 * branch                  main           -> FETCH_HEAD
 * [new tag]               v1.0.0         -> v1.0.0
 * [new tag]               v1.1.0         -> v1.1.0
 * [new tag]               v1.1.0-rc1     -> v1.1.0-rc1
 * [new tag]               v1.10.0        -> v1.10.0
 * [new tag]               v1.10.0-rc1    -> v1.10.0-rc1
 * [new tag]               v1.10.0-rc2    -> v1.10.0-rc2
 * [new tag]               v1.10.0-rc3    -> v1.10.0-rc3
 * [new tag]               v1.11.0        -> v1.11.0
 * [new tag]               v1.11.0-rc1    -> v1.11.0-rc1
 * [new tag]               v1.11.0-rc2    -> v1.11.0-rc2
 * [new tag]               v1.11.0-rc3    -> v1.11.0-rc3
 * [new tag]               v1.12.0        -> v1.12.0
 * [new tag]               v1.12.0-rc1    -> v1.12.0-rc1
 * [new tag]               v1.12.0-rc2    -> v1.12.0-rc2
 * [new tag]               v1.12.0-rc3    -> v1.12.0-rc3
 * [new tag]               v1.13.0        -> v1.13.0
 * [new tag]               v1.13.0-rc1    -> v1.13.0-rc1
 * [new tag]               v1.13.0-rc2    -> v1.13.0-rc2
 * [new tag]               v1.13.0-rc3    -> v1.13.0-rc3
 * [new tag]               v1.14.0        -> v1.14.0
 * [new tag]               v1.14.0-rc1    -> v1.14.0-rc1
 * [new tag]               v1.14.0-rc2    -> v1.14.0-rc2
 * [new tag]               v1.14.0-rc3    -> v1.14.0-rc3
 * [new tag]               v1.14.1        -> v1.14.1
 * [new tag]               v1.14.1-rc1    -> v1.14.1-rc1
 * [new tag]               v1.14.1-rc2    -> v1.14.1-rc2
 * [new tag]               v1.14.1-rc3    -> v1.14.1-rc3
 * [new tag]               v1.14.2        -> v1.14.2
 * [new tag]               v1.14.3        -> v1.14.3
 * [new tag]               v1.14.3-rc1    -> v1.14.3-rc1
 * [new tag]               v1.14.3-rc2    -> v1.14.3-rc2
 * [new tag]               v1.2.0         -> v1.2.0
 * [new tag]               v1.2.0-rc1     -> v1.2.0-rc1
 * [new tag]               v1.2.0-rc2     -> v1.2.0-rc2
 * [new tag]               v1.3.0         -> v1.3.0
 * [new tag]               v1.3.0-rc1     -> v1.3.0-rc1
 * [new tag]               v1.3.0-rc2     -> v1.3.0-rc2
 * [new tag]               v1.4.0         -> v1.4.0
 * [new tag]               v1.4.0-rc1     -> v1.4.0-rc1
 * [new tag]               v1.4.0-rc2     -> v1.4.0-rc2
 * [new tag]               v1.4.0-rc3     -> v1.4.0-rc3
 * [new tag]               v1.5.0         -> v1.5.0
 * [new tag]               v1.5.0-rc0     -> v1.5.0-rc0
 * [new tag]               v1.5.0-rc1     -> v1.5.0-rc1
 * [new tag]               v1.5.0-rc2     -> v1.5.0-rc2
 * [new tag]               v1.5.0-rc3     -> v1.5.0-rc3
 * [new tag]               v1.5.0-rc4     -> v1.5.0-rc4
 * [new tag]               v1.6.0         -> v1.6.0
 * [new tag]               v1.6.0-rc1     -> v1.6.0-rc1
 * [new tag]               v1.6.0-rc2     -> v1.6.0-rc2
 * [new tag]               v1.6.0-rc3     -> v1.6.0-rc3
 * [new tag]               v1.6.0-rc4     -> v1.6.0-rc4
 * [new tag]               v1.6.1         -> v1.6.1
 * [new tag]               v1.6.1-rc      -> v1.6.1-rc
 * [new tag]               v1.6.99        -> v1.6.99
 * [new tag]               v1.7.0         -> v1.7.0
 * [new tag]               v1.7.0-rc1     -> v1.7.0-rc1
 * [new tag]               v1.7.0-rc2     -> v1.7.0-rc2
 * [new tag]               v1.7.0-rc3     -> v1.7.0-rc3
 * [new tag]               v1.7.0-rc4     -> v1.7.0-rc4
 * [new tag]               v1.7.1         -> v1.7.1
 * [new tag]               v1.7.1-rc      -> v1.7.1-rc
 * [new tag]               v1.7.99        -> v1.7.99
 * [new tag]               v1.8.0         -> v1.8.0
 * [new tag]               v1.8.0-rc1     -> v1.8.0-rc1
 * [new tag]               v1.8.0-rc2     -> v1.8.0-rc2
 * [new tag]               v1.8.0-rc3     -> v1.8.0-rc3
 * [new tag]               v1.8.0-rc4     -> v1.8.0-rc4
 * [new tag]               v1.8.99        -> v1.8.99
 * [new tag]               v1.9.0         -> v1.9.0
 * [new tag]               v1.9.0-rc1     -> v1.9.0-rc1
 * [new tag]               v1.9.0-rc2     -> v1.9.0-rc2
 * [new tag]               v1.9.0-rc3     -> v1.9.0-rc3
 * [new tag]               v1.9.0-rc4     -> v1.9.0-rc4
 * [new tag]               v1.9.1         -> v1.9.1
 * [new tag]               v1.9.2         -> v1.9.2
 * [new tag]               v2.0.0         -> v2.0.0
 * [new tag]               v2.0.0-rc1     -> v2.0.0-rc1
 * [new tag]               v2.0.0-rc2     -> v2.0.0-rc2
 * [new tag]               v2.0.0-rc3     -> v2.0.0-rc3
 * [new tag]               v2.1.0         -> v2.1.0
 * [new tag]               v2.1.0-rc1     -> v2.1.0-rc1
 * [new tag]               v2.1.0-rc2     -> v2.1.0-rc2
 * [new tag]               v2.1.0-rc3     -> v2.1.0-rc3
 * [new tag]               v2.2.0         -> v2.2.0
 * [new tag]               v2.2.0-rc1     -> v2.2.0-rc1
 * [new tag]               v2.2.0-rc2     -> v2.2.0-rc2
 * [new tag]               v2.2.0-rc3     -> v2.2.0-rc3
 * [new tag]               v2.2.1         -> v2.2.1
 * [new tag]               v2.3.0         -> v2.3.0
 * [new tag]               v2.3.0-rc1     -> v2.3.0-rc1
 * [new tag]               v2.3.0-rc2     -> v2.3.0-rc2
 * [new tag]               v2.4.0         -> v2.4.0
 * [new tag]               v2.4.0-rc1     -> v2.4.0-rc1
 * [new tag]               v2.4.0-rc2     -> v2.4.0-rc2
 * [new tag]               v2.4.0-rc3     -> v2.4.0-rc3
 * [new tag]               v2.5.0         -> v2.5.0
 * [new tag]               v2.5.0-rc1     -> v2.5.0-rc1
 * [new tag]               v2.5.0-rc2     -> v2.5.0-rc2
 * [new tag]               v2.5.0-rc3     -> v2.5.0-rc3
 * [new tag]               v2.5.0-rc4     -> v2.5.0-rc4
 * [new tag]               v2.5.1-rc1     -> v2.5.1-rc1
 * [new tag]               v2.6.0         -> v2.6.0
 * [new tag]               v2.6.0-rc1     -> v2.6.0-rc1
 * [new tag]               v2.6.0-rc2     -> v2.6.0-rc2
 * [new tag]               v2.6.0-rc3     -> v2.6.0-rc3
 * [new tag]               v2.6.1-rc1     -> v2.6.1-rc1
 * [new tag]               v2.6.1-rc2     -> v2.6.1-rc2
 * [new tag]               v2.7.0         -> v2.7.0
 * [new tag]               v2.7.0-rc1     -> v2.7.0-rc1
 * [new tag]               v2.7.0-rc2     -> v2.7.0-rc2
 * [new tag]               v2.7.0-rc3     -> v2.7.0-rc3
 * [new tag]               v2.7.0-rc4     -> v2.7.0-rc4
 * [new tag]               v2.7.0-rc5     -> v2.7.0-rc5
 * [new tag]               v2.7.1         -> v2.7.1
 * [new tag]               v2.7.2         -> v2.7.2
 * [new tag]               v2.7.2-rc1     -> v2.7.2-rc1
 * [new tag]               v2.7.3         -> v2.7.3
 * [new tag]               v2.7.4         -> v2.7.4
 * [new tag]               v2.7.5         -> v2.7.5
 * [new tag]               v2.7.99        -> v2.7.99
 * [new tag]               v3.0.0         -> v3.0.0
 * [new tag]               v3.0.0-rc1     -> v3.0.0-rc1
 * [new tag]               v3.0.0-rc2     -> v3.0.0-rc2
 * [new tag]               v3.0.0-rc3     -> v3.0.0-rc3
 * [new tag]               v3.1.0         -> v3.1.0
 * [new tag]               v3.1.0-rc1     -> v3.1.0-rc1
 * [new tag]               v3.1.0-rc2     -> v3.1.0-rc2
 * [new tag]               v3.1.0-rc3     -> v3.1.0-rc3
 * [new tag]               v3.2.0         -> v3.2.0
 * [new tag]               v3.2.0-rc1     -> v3.2.0-rc1
 * [new tag]               v3.2.0-rc2     -> v3.2.0-rc2
 * [new tag]               v3.2.0-rc3     -> v3.2.0-rc3
 * [new tag]               v3.3.0         -> v3.3.0
 * [new tag]               v3.3.0-rc1     -> v3.3.0-rc1
 * [new tag]               v3.3.0-rc2     -> v3.3.0-rc2
 * [new tag]               v3.3.0-rc3     -> v3.3.0-rc3
 * [new tag]               v3.4.0-rc1     -> v3.4.0-rc1
 * [new tag]               v3.4.0-rc2     -> v3.4.0-rc2
 * [new tag]               zephyr-v1.0.0  -> zephyr-v1.0.0
 * [new tag]               zephyr-v1.1.0  -> zephyr-v1.1.0
 * [new tag]               zephyr-v1.10.0 -> zephyr-v1.10.0
 * [new tag]               zephyr-v1.11.0 -> zephyr-v1.11.0
 * [new tag]               zephyr-v1.12.0 -> zephyr-v1.12.0
 * [new tag]               zephyr-v1.13.0 -> zephyr-v1.13.0
 * [new tag]               zephyr-v1.14.0 -> zephyr-v1.14.0
 * [new tag]               zephyr-v1.14.1 -> zephyr-v1.14.1
 * [new tag]               zephyr-v1.2.0  -> zephyr-v1.2.0
 * [new tag]               zephyr-v1.3.0  -> zephyr-v1.3.0
 * [new tag]               zephyr-v1.4.0  -> zephyr-v1.4.0
 * [new tag]               zephyr-v1.5.0  -> zephyr-v1.5.0
 * [new tag]               zephyr-v1.6.0  -> zephyr-v1.6.0
 * [new tag]               zephyr-v1.6.1  -> zephyr-v1.6.1
 * [new tag]               zephyr-v1.7.0  -> zephyr-v1.7.0
 * [new tag]               zephyr-v1.7.1  -> zephyr-v1.7.1
 * [new tag]               zephyr-v1.8.0  -> zephyr-v1.8.0
 * [new tag]               zephyr-v1.9.0  -> zephyr-v1.9.0
 * [new tag]               zephyr-v1.9.1  -> zephyr-v1.9.1
 * [new tag]               zephyr-v1.9.2  -> zephyr-v1.9.2
 * [new tag]               zephyr-v2.0.0  -> zephyr-v2.0.0
 * [new tag]               zephyr-v2.1.0  -> zephyr-v2.1.0
 * [new tag]               zephyr-v2.2.0  -> zephyr-v2.2.0
 * [new tag]               zephyr-v2.2.1  -> zephyr-v2.2.1
 * [new tag]               zephyr-v2.3.0  -> zephyr-v2.3.0
 * [new tag]               zephyr-v2.4.0  -> zephyr-v2.4.0
 * [new tag]               zephyr-v2.5.0  -> zephyr-v2.5.0
 * [new tag]               zephyr-v2.6.0  -> zephyr-v2.6.0
 * [new tag]               zephyr-v2.7.0  -> zephyr-v2.7.0
 * [new tag]               zephyr-v2.7.1  -> zephyr-v2.7.1
 * [new tag]               zephyr-v2.7.2  -> zephyr-v2.7.2
 * [new tag]               zephyr-v2.7.3  -> zephyr-v2.7.3
 * [new tag]               zephyr-v3.0.0  -> zephyr-v3.0.0
 * [new tag]               zephyr-v3.1.0  -> zephyr-v3.1.0
 * [new tag]               zephyr-v3.2.0  -> zephyr-v3.2.0
 * [new tag]               zephyr-v3.3.0  -> zephyr-v3.3.0
HEAD is now at 290777b2b5 drivers: interrupt_controller: Use macros to access line_range prop values
HEAD is now at 290777b2b5 drivers: interrupt_controller: Use macros to access line_range prop values
=== updating cmsis (modules/hal/cmsis):
--- cmsis: initializing
Initialized empty Git repository in /home/kannan/my-workspace/modules/hal/cmsis/.git/
--- cmsis: fetching, need revision 74981bf893e8b10931464b9945e2143d99a3f0a3
remote: Enumerating objects: 1372, done.
remote: Counting objects: 100% (181/181), done.
remote: Compressing objects: 100% (104/104), done.
remote: Total 1372 (delta 100), reused 111 (delta 77), pack-reused 1191
Receiving objects: 100% (1372/1372), 3.30 MiB | 553.00 KiB/s, done.
Resolving deltas: 100% (861/861), done.
From https://github.com/zephyrproject-rtos/cmsis
 * [new branch]      master     -> refs/west/master
HEAD is now at 74981bf Update DSP library for additional platforms
HEAD is now at 74981bf Update DSP library for additional platforms
=== updating hal_nordic (modules/hal/nordic):
--- hal_nordic: initializing
Initialized empty Git repository in /home/kannan/my-workspace/modules/hal/nordic/.git/
--- hal_nordic: fetching, need revision a1c3e0fbaafda091139b8744becd4853ada2f747
remote: Enumerating objects: 6608, done.
remote: Counting objects: 100% (1530/1530), done.
remote: Compressing objects: 100% (581/581), done.
remote: Total 6608 (delta 963), reused 1386 (delta 939), pack-reused 5078
Receiving objects: 100% (6608/6608), 18.08 MiB | 3.32 MiB/s, done.
Resolving deltas: 100% (4753/4753), done.
From https://github.com/zephyrproject-rtos/hal_nordic
 * [new branch]      master       -> refs/west/master
 * [new branch]      v1.14-branch -> refs/west/v1.14-branch
 * [new tag]         nrfx-2.10.0  -> nrfx-2.10.0
 * [new tag]         nrfx-2.11.0  -> nrfx-2.11.0
HEAD is now at a1c3e0f nrf_ccm: Fix events and tasks for nRF51 SoCs
HEAD is now at a1c3e0f nrf_ccm: Fix events and tasks for nRF51 SoCs
=== updating hal_stm32 (modules/hal/stm32):
--- hal_stm32: initializing
Initialized empty Git repository in /home/kannan/my-workspace/modules/hal/stm32/.git/
--- hal_stm32: fetching, need revision c865374fc83d93416c0f380e6310368ff55d6ce2
remote: Enumerating objects: 29039, done.
remote: Counting objects: 100% (2920/2920), done.
remote: Compressing objects: 100% (650/650), done.
remote: Total 29039 (delta 2387), reused 2381 (delta 2265), pack-reused 26119
Receiving objects: 100% (29039/29039), 73.23 MiB | 1.97 MiB/s, done.
Resolving deltas: 100% (26303/26303), done.
From https://github.com/zephyrproject-rtos/hal_stm32
 * [new branch]        dev_ucpd_cc_pins -> refs/west/dev_ucpd_cc_pins
 * [new branch]        main             -> refs/west/main
 * [new branch]        master           -> refs/west/master
HEAD is now at c865374f dts: pinctrl: add autogenerated BKIN entries
HEAD is now at c865374f dts: pinctrl: add autogenerated BKIN entries
step 3) west build -b esp32 example-application/app
output:kannan@Kannan:~/my-workspace$ west build -b esp32 example-application/app
-- west build: generating a build system
Loading Zephyr default modules (Zephyr base).
-- Application: /home/kannan/my-workspace/example-application/app
-- CMake version: 3.26.4
-- Found Python3: /usr/bin/python3.10 (found suitable exact version "3.10.6") found components: Interpreter 
-- Cache files will be written to: /home/kannan/.cache/zephyr
-- Zephyr version: 3.4.0-rc2 (/home/kannan/my-workspace/zephyr)
-- Found west (found suitable version "1.1.0", minimum required is "0.14.0")
-- Board: esp32
-- ZEPHYR_TOOLCHAIN_VARIANT not set, trying to locate Zephyr SDK
-- Found host-tools: zephyr 0.16.1 (/home/kannan/zephyr-sdk-0.16.1)
-- Found toolchain: zephyr 0.16.1 (/home/kannan/zephyr-sdk-0.16.1)
-- Found Dtc: /home/kannan/zephyr-sdk-0.16.1/sysroots/x86_64-pokysdk-linux/usr/bin/dtc (found suitable version "1.6.0", minimum required is "1.4.6") 
-- Found BOARD.dts: /home/kannan/my-workspace/zephyr/boards/xtensa/esp32/esp32.dts
In file included from /home/kannan/my-workspace/zephyr/boards/xtensa/esp32/esp32.dts:8,
                 from <command-line>:
/home/kannan/my-workspace/zephyr/dts/xtensa/espressif/esp32.dtsi:13:10: fatal error: dt-bindings/pinctrl/esp32-pinctrl.h: No such file or directory
   13 | #include <dt-bindings/pinctrl/esp32-pinctrl.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
CMake Error at /home/kannan/my-workspace/zephyr/cmake/modules/extensions.cmake:3714 (message):
  failed to preprocess devicetree files (error code 1):
  /home/kannan/my-workspace/zephyr/boards/xtensa/esp32/esp32.dts
Call Stack (most recent call first):
  /home/kannan/my-workspace/zephyr/cmake/modules/dts.cmake:223 (zephyr_dt_preprocess)
  /home/kannan/my-workspace/zephyr/cmake/modules/zephyr_default.cmake:115 (include)
  /home/kannan/my-workspace/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:66 (include)
  /home/kannan/my-workspace/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:92 (include_boilerplate)
  CMakeLists.txt:8 (find_package)

-- Configuring incomplete, errors occurred!
FATAL ERROR: command exited with status 1: /usr/bin/cmake -DWEST_PYTHON=/usr/bin/python3 -B/home/kannan/my-workspace/build -GNinja -DBOARD=esp32 -S/home/kannan/my-workspace/example-application/app
Imapact: Not able to proceed further.

**Comment by carlescufi** [comment]
Did you forget to run `west update` ?

**Comment by Ananyaaynana** [comment]
I have the same issue. Ran west update after going into the my-workspace directory right after west init -m https://github.com/zephyrproject-rtos/example-application --mr main my-workspace. Not able to build the example application.
