### ISSUE TITLE
[Coverity CID: 182588] Integer handling issues in /drivers/sensor/hts221/hts221.c

### ISSUE THREAD

**Issue by Shilpashree3lc** [zephyrproject-rtos/zephyr#5890]
Static code scan issues seen in File: /drivers/sensor/hts221/hts221.c
 Category: Integer handling issues
 Function: hts221_channel_get
 Component: Drivers
 CID: 182588
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by nashif** [comment]
fixed
