### ISSUE TITLE
POSIX stat function returns filesystem statistics, not file statistics

### ISSUE THREAD

**Issue by plinnie** [zephyrproject-rtos/zephyr#58911]
Please see Discord discussion https://discord.com/channels/720317445772017664/883450954878439445/1115355325055381625 .

**Describe the bug**
When using the POSIX function stat the returned statistics are not those of the file passed as an argument, but that from the filesystem the file is located on.

The bug present in the current master, and appears in the POSIX filesystem layer of Zephyr.

**To Reproduce**
Write application which uses stat function with CONFIG_POSIX_FS=y  . 

**Expected behavior**
To get actual information of the file.

**Impact**
File size and attribute retrieval will not return the expected result. For example our application using mongoose did not function properly, as mongoose uses the stat function to determine the file size when using the default filesystem API.

**Environment (please complete the following information):**
 - Linux (Ubuntu 20.04)
 - Zephyr SDK 0.15.2
 - Zephyr 3.3.0

**Additional context**
CONFIG_POSIX_FS=y
See:
https://github.com/zephyrproject-rtos/zephyr/blob/be1e7e8c37a6ebedd830a0cc73d33c3407b04029/lib/posix/fs.c#L359
I would expect it to call fs_stat and not fs_statvfs  as it does now.

**Comment by cfriedt** [comment]
@plinnie - are you able to make a PR? Looks like it might be a 1-line fix. Feel free to ping me if you require any assistance.

**Comment by plinnie** [comment]
> @plinnie - are you able to make a PR? Looks like it might be a 1-line fix. Feel free to ping me if you require any assistance.

Yes, but at a second glance it is a bit more involved. I need to gather from fs_stat and fs_statvfs. Additionally I will add unit tests. Also some corner cases need to be defined in more detail (e.g.. `stat('SD:/', &buf)` ). Needs some consideration. I hope somewhere next week
