### ISSUE TITLE
[Coverity CID: 182585] Integer handling issues in /arch/x86/core/thread.c

### ISSUE THREAD

**Issue by Shilpashree3lc** [zephyrproject-rtos/zephyr#5891]
Static code scan issues seen in File: /arch/x86/core/thread.c
 Category: Integer handling issues
 Function: _new_thread
 Component: Architectures
 CID: 182585
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by andrewboie** [comment]
The coverity site is inaccessible and I am completely blocked

**Comment by andrewboie** [comment]
false positive
