### ISSUE TITLE
Documentation SPI not parsed properly

### ISSUE THREAD

**Issue by jasperjonker** [zephyrproject-rtos/zephyr#58912]
**Describe the bug**
The [documentation for the SPI bus](https://docs.zephyrproject.org/latest/hardware/peripherals/spi.html#c.SPI_CS_ACTIVE_HIGH) is showing some weird behaviour:
![image](https://github.com/zephyrproject-rtos/zephyr/assets/44026484/18d31610-b468-4acd-aefe-9822e8cb23e1)

**Expected behavior**
Proper title

**Environment (please complete the following information):**
 - OS: Linux, firefox

**Comment by kartben** [comment]
Thanks again @jasperjonker for taking the time to report the issue - much appreciated!
