### ISSUE TITLE
[Coverity CID: 182584] Integer handling issues in /kernel/sched.c

### ISSUE THREAD

**Issue by Shilpashree3lc** [zephyrproject-rtos/zephyr#5892]
Static code scan issues seen in File: /kernel/sched.c
 Category: Integer handling issues
 Function: _impl_k_thread_priority_set
 Component: Kernel
 CID: 182584
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by andrewboie** [comment]
The coverity site is inaccessible and I am completely blocked

**Comment by andrewboie** [comment]
false positive
