### ISSUE TITLE
Userspace: Disabled APIs have impact on binary size

### ISSUE THREAD

**Issue by erwango** [zephyrproject-rtos/zephyr#58936]
**Describe the bug**
Seen when investigating https://github.com/zephyrproject-rtos/zephyr/issues/58416

When building an application with `CONFIG_USERSPACE=y`, non used APIs have impact on final binary size.

**To Reproduce**
1. west build -p always -b nucleo_l073rz samples/hello_world -- -DCONFIG_USERSPACE=y
```
[181/181] Linking C executable zephyr/zephyr.elf
Memory region         Used Size  Region Size  %age Used
           FLASH:       29592 B       192 KB     15.05%
             RAM:        7544 B        20 KB     36.84%
        IDT_LIST:          0 GB         2 KB      0.00%
```
2. Make some modification in an API disabled. Eg, in `include/zephyr/drivers/counter.h`
```
- __syscall int counter_start(const struct device *dev);
```
Note: COUNTER API is disabled:
```
$ grep -r CONFIG_COUNTER build/nucleo_l073rz/
build/nucleo_l073rz/zephyr/.config:# CONFIG_COUNTER is not set
```
Note: Line should be removed: commenting or `#if 0` have no effect

3. Build again: `west build -p always -b nucleo_l073rz samples/hello_world -- -DCONFIG_USERSPACE=y`
4. Compare Flash footprint:
```
[181/181] Linking C executable zephyr/zephyr.elf
Memory region         Used Size  Region Size  %age Used
           FLASH:       29588 B       192 KB     15.05%
             RAM:        7544 B        20 KB     36.84%
        IDT_LIST:          0 GB         2 KB      0.00%
```

Final ROM size decreased by 4 bytes.

**Expected behavior**
Disabled APIs should not have impact on final binary size.

**Impact**
In USERSPACE config, binaries are bloated with disabled/non supported APIs.
In long term, some small devices might not support USERSPACE anymore because too much APIs are available in Zephyr.

**Comment by erwango** [comment]
Reducing bug priority as potential gain is not huge.
```
$ grep -r __syscall include/zephyr/drivers/  | wc -l
299
```

**Comment by nashif** [comment]
see #58351

**Comment by erwango** [comment]
> see #58351

The power of community work!

Will test on https://github.com/zephyrproject-rtos/zephyr/issues/58416

**Comment by erwango** [comment]
Fixed by https://github.com/zephyrproject-rtos/zephyr/pull/58351
