### ISSUE TITLE
Bluetooth: ACL: Unnecessary fragmentation

### ISSUE THREAD

**Issue by rugeGerritsen** [zephyrproject-rtos/zephyr#58967]
**Describe the bug**
ACL packets are fragmented over HCI more than necessary when the provided buffer is close to or equal to the MTU. That is. If the ACL MTU is 251 bytes, and the provided ACL buffer is 251 bytes, it is fragmented.

**Expected behavior**
No fragmentation

**Impact**
This may result in reduced throughput

**Additional context**
The bug can be found here: https://github.com/zephyrproject-rtos/zephyr/blame/main/subsys/bluetooth/host/conn.c#LL743.
`buf->len` represents the total HCI buffer, not the data itself. For ISO we correctly subtract the header, for ACL we do not.

**Comment by jori-nordic** [comment]
Closing as invalid:
ISO is a special case as it has two headers: the packet header and the data header. ACL has only the packet header.

At that point in code, `buf->len` does not represent the total HCI buffer: it does not yet have the packet header. The packet header is pushed right before the `bt_send` in  `send_acl` / `send_iso`.

For ISO though, the data header (`struct bt_hci_iso_data_hdr` or `struct bt_hci_iso_ts_data_hdr` depending on TS flag) is present. That is also omitted in the conn mtu for some reason (spec thing), so this is what we're removing from the calculation.
