### ISSUE TITLE
Shell should accept all characters (even non-printable ones) while entering Wi-FIi SSID 

### ISSUE THREAD

**Issue by ajayparida** [zephyrproject-rtos/zephyr#59048]
**Describe the bug**
AP's SSID can be configured with all characters including *, ?, non-printable ones.
While using shell to connect  to AP configured with special characters, 
it seems shell is not treating them as expected.

With AP's SSID not containing any special characters
If AP's SSID is "1" and we use  "wifi connect 1" it returns argc as 2. 
There is no specical character for SSID. Able to connect the AP.

With AP's SSID containing any special characters
if SSID is "1*" and we use "wifi connect 1*", it returns argc as 1.
shell is not treating "1*" as a separate argument. Not able to connect AP.

Same behaviour also observed with character "?".

**To Reproduce**
(1) configure access point with ssid containing special characters.
(2) Try connecting to AP using "wifi connect <ssid>" and observe that ssid is not being accepted properly and connect fails.

**Expected behavior**
Shell should accept all characters(including non-printable and special characters) given for SSID.

**Impact**
The application will not take the argument passed for SSID. The application will not able to process the SSID and thus connect to AP will not happen.

**Environment (please complete the following information):**
OS: Yes
Toolchain: Zephyr SDK
Commit SHA: https://github.com/zephyrproject-rtos/zephyr/commit/242c8f1c7727b74af758ecbe235aecf161594f48

**Comment by henrikbrixandersen** [comment]
Please use our bug template when reporting bugs. You need to edit this issue to include the needed information from https://github.com/zephyrproject-rtos/zephyr/blob/main/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by jakub-uC** [comment]
@ajayparida Do you have `SHELL_WILDCARD` feature enabled? In such case characters: `* and ?` are handled in a special way.

**Comment by krish2718** [comment]
> Apart from that there is implemented an ascii filter in the shell.c.
> https://github.com/zephyrproject-rtos/zephyr/blob/main/subsys/shell/shell.c#L992

Can we make the ASCII filtering optional by adding a Kconfig? For `wifi connect <SSID>` we need the shell to accept all and give that information to command handler (not the other direction).

**Comment by jakub-uC** [comment]
Sure we can, I will start PR shortly.
