### ISSUE TITLE
Wrong partitioning in nucleo_f410rb devicetree 

### ISSUE THREAD

**Issue by nguyenmthien** [zephyrproject-rtos/zephyr#59096]
**Describe the bug**
The board nucleo_f410rb apparently have a erroneous devicetree definition file. The devicetree partitioned the chip to [four differnt partitions with total size of 512KB](https://github.com/zephyrproject-rtos/zephyr/blob/a8ed28ab6fc868ac73eed56fc3b46c23df52adde/boards/arm/nucleo_f410rb/nucleo_f410rb.dts#L121) although the [flash size is only 128KB](https://www.st.com/en/microcontrollers-microprocessors/stm32f410rb.html).

**Impact**
This will make some firmware e.g. mcuboot unable to be flashed into the device.

**Comment by erwango** [comment]
@nguyenmthien Fell free to update the partition to something more reasonable (or purely remove it)

**Comment by FRASTM** [comment]
Would it be better to reduce the boot_partition to 32KB, and use the 128KB in 4 partitions of 32K each 

```
/*
		boot_partition: partition@0 {
			label = "mcuboot";
			reg = <0x00000000 DT_SIZE_K(32)>;
			read-only;
		};

		slot0_partition: partition@8000 {
			label = "image-0";
			reg = <0x00008000 DT_SIZE_K(32)>;
		};
		slot1_partition: partition@10000 {
			label = "image-1";
			reg = <0x00010000 DT_SIZE_K(32)>;
		};
		scratch_partition: partition@18000 {
			label = "image-scratch";
			reg = <0x000018000 DT_SIZE_K(32)>;
		};


```

**Comment by FRASTM** [comment]
![stm32f410_flash_memory](https://github.com/zephyrproject-rtos/zephyr/assets/51417392/78e17aad-f80f-4b4d-953b-af2732adf84a)

**Comment by nguyenmthien** [comment]
> Would it be better to reduce the boot_partition to 32KB, and use the 128KB in 4 partitions of 32K each
> 
> ```
> 		boot_partition: partition@0 {
> 			label = "mcuboot";
> 			reg = <0x00000000 DT_SIZE_K(32)>;
> 			read-only;
> 		};
> 
> 		slot0_partition: partition@8000 {
> 			label = "image-0";
> 			reg = <0x00008000 DT_SIZE_K(32)>;
> 		};
> 		slot1_partition: partition@10000 {
> 			label = "image-1";
> 			reg = <0x00010000 DT_SIZE_K(32)>;
> 		};
> 		scratch_partition: partition@18000 {
> 			label = "image-scratch";
> 			reg = <0x000018000 DT_SIZE_K(32)>;
> 		};
> ```

Hi, for MCUBoot, 32KB of Flash memory is a bit strict. I suggest having a single-slot configuration with 64KB for MCUBoot and the rest for the image

**Comment by FRASTM** [comment]
> 
> Hi, for MCUBoot, 32KB of Flash memory is a bit strict. I suggest having a single-slot configuration with 64KB for MCUBoot and the rest for the image

Yes, however some boards have boot_partition of 32KB.  
It is still possible to have a boot_partition of 48K and reduce the scratch_partition to 16KB
and several other combinations are still valid.
