### ISSUE TITLE
Arduino Portenta H7 

### ISSUE THREAD

**Issue by bdunlay** [zephyrproject-rtos/zephyr#59174]
**Describe the bug**
The Arduino Portenta H7 clocks are not correct. According to some prior discussion around this board, "the system is still running at 100 MHz while the system thinks it is running at 480 MHz (UART corrupted and blink sketch 4,8 times too slow).”

https://forum.arduino.cc/t/portenta-h7-stm32cubeide-please-join-me/1010091/6

The issue may related to the fact that the board is "confined to the internal clock and cannot use the external clock" -- maybe due to some power settings occurring in the bootloader? I don't have a clear understanding of what's going on beyond observing that the clocks are indeed too slow. 

https://github.com/zephyrproject-rtos/zephyr/pull/45221#issuecomment-1190285580

Please also mention any information which could help others to understand
the problem you're facing:
 - What target platform are you using? arduino_portenta_h7_m4/arduino_portenta_h7_m7
 - What have you tried to diagnose or workaround this issue?
 - Is this a regression? If yes, have you been able to "git bisect" it to a
   specific commit? No, this seems to be a known bug.

**To Reproduce**

I am able to replicate this by flashing the Blinky app:

west build -b arduino_portenta_h7_m7 -d build-portenta-m7-hello-world samples/basic/blinky
west flash -d build-portenta-m7-hello-world

The LED should toggle at 1 Hz, but appears to toggle closer to 5 Hz. 

Further, I am not sure if this is related to the clock issue, but I do not see any tty device for accessing uart output whenever I flash this or other examples (e.g. subsys/console/echo)

**Expected behavior**
With blinky, I expect the 1 Hz blink to blink at 1 Hz.

**Impact**
What impact does this issue have on your progress (e.g., annoyance, showstopper): show stopper

**Environment (please complete the following information):**
 - OS: (e.g. Linux, MacOS, Windows): OS X
 - Toolchain (e.g Zephyr SDK, ...): Zephyr 0.15.2
 - Commit SHA or Version used: zephyr-v3.3.0

**Comment by erwango** [comment]
Looking to board dts description, it seems board is missing bus speeds configuration, it is likely not correctly configured.
Can you provide a known working configuration and we'll see how to convert it to dts ?
