### ISSUE TITLE
boards: mec2016evb_assy6797: uses custom pinmux scheme

### ISSUE THREAD

**Issue by gmarull** [zephyrproject-rtos/zephyr#59187]
**Describe the bug**

Board still uses a custom pinmux scheme, but this is no longer allowed and pinctrl API needs to be used.

**To Reproduce**

https://github.com/zephyrproject-rtos/zephyr/blob/bfa0a87277c31d9e1b36104a29b17f3fc1a47444/boards/arm/mec2016evb_assy6797/pinmux.c#L13-L38

**Expected behavior**

Pinctrl is used

**Impact**

N/A

**Logs and console output**

N/A

**Environment (please complete the following information):**

- OS: Linux
- Toolchain: Zephyr SDK 0.16.1
- Commit SHA or Version used https://github.com/zephyrproject-rtos/zephyr/commit/bfa0a87277c31d9e1b36104a29b17f3fc1a47444

**Additional context**

Discovered as part of a round of SYS_INIT usage cleanups

**Comment by jvasanth1** [comment]
We need to remove mec2016 board - we are not supporting that

**Comment by gmarull** [comment]
@jvasanth1 can you submit a PR deleting it?

**Comment by jvasanth1** [comment]
> 

yes, we will do so

**Comment by jvasanth1** [comment]
> @jvasanth1 can you submit a PR deleting it?

yes, we will do so
