### ISSUE TITLE
Remove obsolete FLASH_DRIVER_NAME

### ISSUE THREAD

**Issue by erwango** [zephyrproject-rtos/zephyr#5919]
FLASH_DRIVER_NAME could be found in some samples and defined in some socs.

It should be removed FLASH_DEV_NAME should be used instead.

**Comment by galak** [comment]
I believe FLASH_DRIVER_NAME is used by MCUBoot, but not sure.

**Comment by mbolivar** [comment]
I'll add a shim in MCUboot to work around this name change and ping back this issue when it's safe to rename in Zephyr

**Comment by mbolivar** [comment]
> I'll add a shim in MCUboot to work around this name change

Pending review in mcuboot: https://github.com/runtimeco/mcuboot/pull/201
