### ISSUE TITLE
tests/drivers/adc/adc_api/drivers.adc on nucleo_<several> & stm32g081b_eval fails to build in main / CI

### ISSUE THREAD

**Issue by aescolar** [zephyrproject-rtos/zephyr#59315]
**Describe the bug**
tests/drivers/adc/adc_api/drivers.adc fails to build for several nucleo boards in main.

**To Reproduce**
* twister -p nucleo_f070rb -s tests/drivers/adc/adc_api/drivers.adc
 &
* nucleo_f446ze
* nucleo_f303k8
* nucleo_g0b1re
* nucleo_f767zi
* nucleo_u575zi_q
* stm32g081b_eval

**Expected behavior**
No build failures

**Impact**
Blocks PRs which touch files triggering these tests to be run in CI.

**Logs and console output**
https://github.com/zephyrproject-rtos/zephyr/actions/runs/5290178670/jobs/9574122473#step:13:380
https://github.com/zephyrproject-rtos/zephyr/actions/runs/5290178670/jobs/9574122846#step:13:618
https://github.com/zephyrproject-rtos/zephyr/actions/runs/5290178670/jobs/9574122674#step:13:1136

**Environment (please complete the following information):**
 - Host/toolchain: CI
 - Commit SHA: Today's main tip: 7d89f784a47a37a611939bff171d40bbd35b3049

**Comment by erwango** [comment]
I think the main issue on this test is that it misses an `integration_platforms` to avoid compiling each and every board in CI that declares supporting adc
