### ISSUE TITLE
esp32: Output frequency is different from that configured on I2C and PWM drivers

### ISSUE THREAD

**Issue by iha** [zephyrproject-rtos/zephyr#5934]
Setting the frequency in the I2C driver, for example 100kHz, the SCL frequency is 50kHz measured on an oscilloscope. 

The same behaviour is found in the PWM driver. The measured frequency  at the output is half of the configured.

I tested the I2C and PWM drivers using the Espressif RTOS drivers, and the frequency measured on the oscilloscope was the same as configured.

**Comment by carlescufi** [comment]
@nashif is this still an issue?
