### ISSUE TITLE
Bluetooth: Host: Fail to initiate a connection to a synced paired device from a PAwR train if BT_PRIVACY=y

### ISSUE THREAD

**Issue by laxiLang** [zephyrproject-rtos/zephyr#59364]
**Describe the bug**
Do pairing before initiating a connection to a synced paired device from a PAwR train will lead to the connection v2 failing to be established. The reason is that on the synced device, the device address is the resolvable private address, while the local identity address is used as the peer address by the controller when establishing a connection from PAwR. 

**To Reproduce**
1. both devices create new identity with device address and IRK pairs
2. both devices call bt_enable()
3. connect the two devices and set security level 2 for adding peer device to resolving list
4. on device starting PAwR adverting while the other syncs to it
5. the PAwR advertiser initiates a connection to the synced device

**Expected behavior**
The connection v2 initiation will get 0x3E (Failed to be established) error

**Impact**
This will affect the establishment of PAwR connection v2 with privacy enabled

**Comment by jori-nordic** [comment]
@laxiLang moved to low as this is still experimental in Zephyr.

**Comment by alwa-nordic** [comment]
@hermabe FYI if you are still working on PAwR :)

**Comment by alwa-nordic** [comment]
Is this related to PR https://github.com/zephyrproject-rtos/zephyr/pull/57668?

**Comment by hermabe** [comment]
> Is this related to PR #57668?

That is a separate issue.

I am aware of this but have not looked too much into it.
