### ISSUE TITLE
Docs / 2.7.4 » CONFIG_MINIMAL_LIBC_RAND leads to "Sorry, Page Not Found"

### ISSUE THREAD

**Issue by Aemperior** [zephyrproject-rtos/zephyr#59363]
At the following location (documentation of 2.7.4): 

https://docs.zephyrproject.org/2.7.4/reference/kconfig/CONFIG_MINIMAL_LIBC_RAND.html

I was prompted with

"The [latest development version](https://docs.zephyrproject.org/latest/reference/kconfig/CONFIG_MINIMAL_LIBC_RAND.html) of this page may be more current than this released 2.7.4 version."

Leading me to:

https://docs.zephyrproject.org/latest/reference/kconfig/CONFIG_MINIMAL_LIBC_RAND.html

Where I was asked to please submit a github issue. 

The 2.7.4 documentation is the one that shows up on google if you are confused about how to obtain reproducible randomness with zephyr. As it happens, I am still confused about how to do that, and I am so far unable to find where the documentation has been moved to now that the 2.7.4 version is outdated. But I think that is a separate issue from this one.

**Comment by nashif** [comment]
go to https://docs.zephyrproject.org/latest/kconfig.html and search for the above kconfig, lots has changed since 2.7 and kconfigs are being handled differently. Closing as a no-bug
