### ISSUE TITLE
net: lwm2m: lwm2m_observation: Update to a resource's pmax does not work properly

### ISSUE THREAD

**Issue by v2h** [zephyrproject-rtos/zephyr#59397]
**Describe the bug**
Prerequisites:
- The value of the LwM2M resource doesn't change during runtime.
- The LwM2M resource does not have any periodic service configured for it (using `lwm2m_engine_add_service()`)

After the server has sent a `PUT` with a (higher) pmax value to set the resource's pmax, a subsequent `PUT` from the server with a (lower) pmax value to update the resource's pmax will not come into effect.
My suspicion is at `lwm2m_write_attr_handler()` where the server's `PUT` is handled: in there, `lwm2m_engine_observer_timestamp_update()` is called and this path is always executed: https://github.com/zephyrproject-rtos/zephyr/blob/df0e03c5512c03f4e3e641cc37641abb1f76082b/subsys/net/lib/lwm2m/lwm2m_observation.c#L918
before the resource's pmax is read out.

This is seen on an nRF9160.

**To Reproduce**
1. Set `LWM2M_SERVER_DEFAULT_PMIN` and `LWM2M_SERVER_DEFAULT_PMAX` to zero at compile time.
2. Make sure the prerequisites above are met.
3. Configure the LwM2M server to send a `PUT` to set the resource's pmax value to a high value (e.g. `PUT /5/0/7?pmin=0&pmax=86400`)
4. Wait a few seconds, then send another `PUT` to update the resource's pmax to a lower value (e.g. `PUT /5/0/7?pmin=0&pmax=30`)

**Expected behavior**
The client/device should report the resource's value periodically _according to the newly updated pmax value_.

**Comment by SeppoTakalo** [comment]
I can verify this:
In the Wireshark screenshot here, I have server observing 5/0/3 and PMAX is set to 60s and time reference is set to Observation message:
![image](https://github.com/zephyrproject-rtos/zephyr/assets/3104794/612a2ab9-b9a5-4da2-84ac-eb3fd548a747)
As seen, changing the PMAX did not trigger Notify at 30s mark, but instead used the previous timestamp.

After the Notify, timestamp is recalculated and now the new PMAX is used:
![image](https://github.com/zephyrproject-rtos/zephyr/assets/3104794/db63e0d3-8040-4c17-aa3c-25c34b40aa11)


Fix submitted in: https://github.com/zephyrproject-rtos/zephyr/pull/59487

**Comment by v2h** [comment]
Could you guys double check if the fix (and also the expected behavior) doesn't violate the LwM2M spec? Even though the spec doesn't explicitly say what should happen when Pmax is updated, it does say 
> Each time a Resource notification is sent, the "Minimum Period" and "Maximum Period" timers associated to this
Resource are restarted.
page 22-23: https://www.openmobilealliance.org/release/LightweightM2M/V1_1_1-20190617-A/OMA-TS-LightweightM2M_Core-V1_1_1-20190617-A.pdf

**Comment by SeppoTakalo** [comment]
You are right, spec is not clear about this.

I don't think the word `timer` in the spec means that is is specifically a downward counting timer.

In the table that describes `pmax` it is written as follows [5.1.2.-2 <NOTIFICATION> class Attributes](https://www.openmobilealliance.org/release/LightweightM2M/V1_1_1-20190617-A/HTML-Version/OMA-TS-LightweightM2M_Core-V1_1_1-20190617-A.html#Table-512-2-lessNOTIFICATIONgreater-class-Attributes)
> Notes: The Maximum Period Attribute indicates the maximum time in seconds the LwM2M Client MAY wait between two notifications.

There is no mention of timers, or when attributes are written. The wording sound like there is only one pmax value to be considered.

My interpretation of the spec is that timer refers to upward counting time value (or timestamp) to which the pmax value is compared. That is how it is implemented in our engine. When pmax is updated, new value should take effect immediately.
