### ISSUE TITLE
NRF5 I2C (TWI) driver

### ISSUE THREAD

**Issue by thomafred** [zephyrproject-rtos/zephyr#5939]
Currently, the NRF5 I2C-driver is implemented in the way of GPIO bit-banging.

the NRF5 SOCs support TWI (I2C-compatible two-wire interface) sub-systems with EasyDMA, although drivers for this is lacking in Zephyr.

Furthermore, I2C and SPI devices may not share the same ID.

**Comment by pdunaj** [comment]
There is no asynchronous notification about transmission being done. 
I guess this is because the implementation is not using DMA. 

Do we know when this driver will be ready?

**Comment by carlescufi** [comment]
@pdunaj no, but @anangl is the person to ask

**Comment by pdunaj** [comment]
@carlescufi thanks

**Comment by carlescufi** [comment]
This is done.
