### ISSUE TITLE
Idle function do not take care of Synchronizing the multi core states during S2I and S2R.

### ISSUE THREAD

**Issue by SumitJain3083** [zephyrproject-rtos/zephyr#59428]
**Is your feature request related to a problem? Please describe.**
In Multicore environment , if the policy manager decides that the system has to go to S2I or S2R then the idle framework will set S2I / S2R state for all the cores and once the pm_state_set is called on respective cores all the cores goes to suspend state.
There is no synchronization between the cores , if last core failed to go to the desired state.

**Describe the solution you'd like**
Once the last core finalize to go to desired state ( S2I or S2R )  then other cores should be notified else they should be notified for going to active state.

**Comment by nashif** [comment]
This issue is lacking details, not sure what architecture or platform is this referring to, please reopen with more details.
