### ISSUE TITLE
Sample project wsen-itds does not work

### ISSUE THREAD

**Issue by StevenBoeckx** [zephyrproject-rtos/zephyr#59463]
**Describe the bug**
The sample project doesn't work out of the box.
In function:
```
static int itds_sample_fetch(const struct device *dev, enum sensor_channel chan)
         {
	struct itds_device_data *ddata = dev->data;
	const struct itds_device_config *cfg = dev->config;
	switch (chan) {
	case SENSOR_CHAN_ACCEL_XYZ:
	case SENSOR_CHAN_ACCEL_X:
	case SENSOR_CHAN_ACCEL_Y:
	case SENSOR_CHAN_ACCEL_Z:
		return itds_fetch_accel(ddata, cfg);
	case SENSOR_CHAN_DIE_TEMP:
		return itds_fetch_temprature(ddata, cfg);
	default:
		return -EINVAL;
	}
}
```
https://github.com/zephyrproject-rtos/zephyr/blob/001795b24c980df3a3dfc0e7b385f93a9392d4f9/drivers/sensor/wsen_itds/itds.c#L217

There is no reference to all channels and this is necessary to run the example:
two options:
change the sample project to:
```
static void test_polling_mode(const struct device *itds)
     {
	int32_t remaining_test_time = MAX_TEST_TIME;
	do {
		if (sensor_sample_fetch_chan(itds, SENSOR_CHAN_ACCEL_XYZ) < 0) {
			printf("accl sample update error.\n");
		} else {
			print_accl_data(itds);
		}
		if (sensor_sample_fetch_chan(itds, SENSOR_CHAN_DIE_TEMP) < 0) {
			printf("accl sample update error.\n");
		} else {
			print_temp_data(itds);
		}
		/* wait a while */
		k_sleep(K_MSEC(SLEEPTIME));
		remaining_test_time -= SLEEPTIME;
	} while (remaining_test_time > 0);
    }
```

or add the next line in the itds_itds_sample fetch function:
`case SENSOR_CHAN_ALL:
		return itds_fetch_accel(ddata, cfg) ||
		       itds_fetch_temprature(ddata, cfg);`
complete function is then:
```
static int itds_sample_fetch(const struct device *dev,
			     enum sensor_channel chan)
{
	struct itds_device_data *ddata = dev->data;
	const struct itds_device_config *cfg = dev->config;
	switch (chan) {
	case SENSOR_CHAN_ACCEL_XYZ:
	case SENSOR_CHAN_ACCEL_X:
	case SENSOR_CHAN_ACCEL_Y:
	case SENSOR_CHAN_ACCEL_Z:
		return itds_fetch_accel(ddata, cfg);
	case SENSOR_CHAN_DIE_TEMP:
		return itds_fetch_temprature(ddata, cfg);
	case SENSOR_CHAN_ALL:
		return itds_fetch_accel(ddata, cfg) ||
		       itds_fetch_temprature(ddata, cfg);
	default:
		return -EINVAL;
	}
}
```

**To Reproduce**
Try the sample project of the sensor

**Expected behavior**
Samples are fetched and shown in the serial console

**Impact**
Total blocker because the library can't be used

**Environment (please complete the following information):**
Zephyr version: 3.3.99 (/opt/nordic/ncs/v2.4.0/zephyr), build: v3.3.99-ncs1

@MaureenHelm please give ownership to @mah-eiSmart so the libraries can be fixed and official support of the manufacture can be done. The current process just takes to long

**Comment by nordicjm** [comment]
> Environment (please complete the following information):
> Zephyr version: 3.3.99 (/opt/nordic/ncs/v2.4.0/zephyr), build: v3.3.99-ncs1

You are using a downstream fork of zephyr, not zephyr itself, will leave this issue open because it appears to be an issue in zephyr but in future please only report issues reproduced in upstream zephyr with details (e.g. commit SHA) of the upstream you tested
