### ISSUE TITLE
check-warns false positive

### ISSUE THREAD

**Issue by tautologyclub** [zephyrproject-rtos/zephyr#59588]
This line

```
cfg->uart_buf[i] &= ~BIT(7);
```

triggers ` SPACING: spaces required around that '=' (ctx:WxO)` which feels incorrect to me.

**Comment by henrikbrixandersen** [comment]
Please use our bug template when reporting bugs. You need to edit this issue to include the information requested in https://github.com/zephyrproject-rtos/zephyr/blob/main/.github/ISSUE_TEMPLATE/001_bug_report.md

**Comment by henrikbrixandersen** [comment]
Please reopen when the missing information has been provided. Thanks.
