### ISSUE TITLE
npcx9m6f_evb: drivers/watchdog/wdt_basic_api/ failing

### ISSUE THREAD

**Issue by pkunieck** [zephyrproject-rtos/zephyr#59596]
**Describe the bug**
Tests from drivers/watchdog/wdt_basic_api/ failing. There is no console output and timeout as a result.

**To Reproduce**
1. cd <path/to>zephyrproject/zephyr
2. source zephyr-env.sh
3. twister --device-testing --hardware-map <path/to>/map.yaml -T tests/drivers/watchdog/wdt_basic_api/ -vv

**Expected behavior**
The tests pass

**Impact**
annoyance

**Logs and console output**
-- runners.openocd: Flashing file: /home/ztest/zephyrproject/zephyr/twister-out/npcx9m6f_evb/tests/drivers/watchdog/wdt_basic_api/drivers.watchdog/zephyr/zephyr.npcx.hex

DEBUG   - Timed out while monitoring serial output on npcx9m6f_evb
DEBUG   - Expected suite names:['wdt_basic_test_suite']
DEBUG   - Detected suite names:['wdt_basic_test_suite']
DEBUG   - run status: npcx9m6f_evb/tests/drivers/watchdog/wdt_basic_api/drivers.watchdog failed
INFO    - 10/10 npcx9m6f_evb              tests/drivers/watchdog/wdt_basic_api/drivers.watchdog  FAILED Timeout (device 61.920s)

**Environment (please complete the following information):**
- OS: Linux
- Toolchain Zephyr SDK 16.0
- Commit: tested on the newest and older, always the same issue

**Comment by MulinChao** [comment]
@pkunieck, thanks for reporting this. The root cause of this issue is npcx wdt driver doesn't support `WDT_OPT_PAUSE_HALTED_BY_DBG` option so far. Nuvoton will submit a PR to resolve this.
