### ISSUE TITLE
samples/net/mbedtls_dtlsserver needs fixing

### ISSUE THREAD

**Issue by galak** [zephyrproject-rtos/zephyr#596]
samples/net/mbedtls_dtlsserver/sample.yaml has:

arch_whitelist: qemu_x86

This should be:

platform_whitelist: qemu_x86

Once we make that change, there are a number of code updates that need to be made to get the sample to build again.  Can you please look at fixing all this up.

**Comment by nashif** [comment]
actually @jukkar  fixed that already in the ini file, it was my mistake, so taking over :)

**Comment by nashif** [comment]
actually not. for some reason I though it was fixed.., i was mistaken.
