### ISSUE TITLE
Instruction Access Violation -- MPU Fault

### ISSUE THREAD

**Issue by nkaufmn** [zephyrproject-rtos/zephyr#59636]
I have an issue on the send request of LoRaWAN.

I work with an NRF52840 with external NOR Memory (MX25L3233F), the partition "settings" is on external memory, and a SX1276 is used as LoRa module.  I use the NRF Connect SDK 2.4.0 on Visual Studio Code.

Behavior: My device could join to thethingsnetwork but when it sends a message to ttn it crashes with an fatal error. 

This is the DEBUG output:

> *** Booting Zephyr OS build v3.3.99-ncs1 ***
> Attempting to boot slot 0.
> Attempting to boot from address 0x9200.
> Verifying signature against key 0.
> Hash: 0x5b...a3
> Firmware signature verified.
> Firmware version 1
> Setting monotonic counter (version: 1, slot: 0)
> [00:00:00.000,152] <inf> board_control: Board configured.
> [00:00:00.200,866] <inf> sx127x: SX127x version 0x12 found
> --- 18 messages dropped ---
> Starting LoRaWAN stack.
> [00:00:00.360,260] <dbg> lorawan: lorawan_start: LoRaMAC Initialized
> [00:00:00.388,183] <inf> fs_nvs: 4 Sectors of 4096 bytes
> [00:00:00.388,183] <inf> fs_nvs: alloc wra: 2, f68
> [00:00:00.388,214] <inf> fs_nvs: data wra: 2, d08
> [00:00:00.393,615] <dbg> lorawan_nvm: lorawan_nvm_data_restore: Restoring LoRaWAN settings
> [00:00:00.404,693] <dbg> lorawan_nvm: on_setting_loaded: Key: ClassB
> [00:00:00.417,846] <dbg> lorawan_nvm: on_setting_loaded: Key: RegionGroup2
> [00:00:00.426,300] <dbg> lorawan_nvm: on_setting_loaded: Key: SecureElement
> [00:00:00.433,441] <dbg> lorawan_nvm: on_setting_loaded: Key: MacGroup2
> [00:00:00.440,460] <dbg> lorawan_nvm: on_setting_loaded: Key: MacGroup1
> [00:00:00.447,479] <dbg> lorawan_nvm: on_setting_loaded: Key: Crypto
> [00:00:00.448,059] <dbg> lorawan_nvm: lorawan_nvm_data_restore: Crypto version: 16777472, DevNonce: 112, JoinNonce: 333
> [00:00:00.449,188] <dbg> lorawan_nvm: lorawan_nvm_data_restore: LoRaWAN context restored
> Joining network using OTAA, dev nonce 0, attempt 1:
> [00:00:00.454,040] <dbg> lorawan: lorawan_join: Network join request sent!
> [00:00:05.591,552] <dbg> lorawan: mlme_confirm_handler: Received MlmeConfirm (for MlmeRequest 1)
> [00:00:05.591,583] <inf> lorawan: Joined network! DevAddr: 260b0264
> [00:00:05.592,834] <dbg> lorawan_nvm: lorawan_nvm_save_settings: Saving LoRaWAN settings
> [00:00:05.592,864] <dbg> lorawan_nvm: lorawan_nvm_save_settings: Crypto version: 16777472, DevNonce: 113, JoinNonce: 334
> [00:00:05.592,895] <dbg> lorawan_nvm: lorawan_nvm_save_settings: Saving configuration lorawan/nvm/Crypto
> New Datarate: DR_5, Max Payload 242[00:00:05.658,691] <inf> lorawan: Datarate changed: DR_5
> [00:00:05.628,997] <dbg> lorawan_nvm: lorawan_nvm_save_settings: Saving configuration lorawan/nvm/MacGroup1
> Join successful.
> [00:00:05.659,393] <dbg> lorawan_nvm: lorawan_nvm_save_settings: Saving configuration lorawan/nvm/MacGroup2
> LoRa init complete
> [00:00:05.685,791] <dbg> lorawan_nvm: lorawan_nvm_save_settings: Saving configuration lorawan/nvm/SecureElement
> [00:00:10.958,068] <dbg> lorawan: mcps_confirm_handler: Received McpsConfirm (for McpsRequest 0)
> [00:00:10.958,099] <dbg> lorawan: mcps_confirm_handler: McpsRequest success!
> [00:00:10.958,129] <dbg> lorawan: mcps_indication_handler: Received McpsIndication 0
> [00:00:10.958,160] <err> os: ***** MPU FAULT *****
> [00:00:10.958,160] <err> os:   Instruction Access Violation
> [00:00:10.958,190] <err> os: r0/a1:  0x00000000  r1/a2:  0x00000000  r2/a3:  0xffffffd6
> [00:00:10.958,221] <err> os: r3/a4:  0x00000008 r12/ip:  0xffffffff r14/lr:  0x0004959d
> [00:00:10.958,221] <err> os:  xpsr:  0x01000000
> [00:00:10.958,251] <err> os: Faulting instruction address (r15/pc): 0x20006d30
> [00:00:10.958,282] <err> os: >>> ZEPHYR FATAL ERROR 20: Unknown error on CPU 0
> [00:00:10.958,312] <err> os: Current thread: 0x20004448 (unknown)

I figured out, that the system crashes when it tries to do this:
The code snippet is from "lorawan.c" line 136 - 165

```
static void mcps_indication_handler(McpsIndication_t *mcps_indication)
{
	struct lorawan_downlink_cb *cb;

	LOG_DBG("Received McpsIndication %d", mcps_indication->McpsIndication);

	if (mcps_indication->Status != LORAMAC_EVENT_INFO_STATUS_OK) {
		LOG_ERR("McpsIndication failed : %s",
			lorawan_eventinfo2str(mcps_indication->Status));
		return;
	}
	/* Datarate can change as result of ADR command from server */
	if (lorawan_adr_enable) {
		datarate_observe(false);
	}
	/* Iterate over all registered downlink callbacks */
	SYS_SLIST_FOR_EACH_CONTAINER(&dl_callbacks, cb, node) {
		if ((cb->port == LW_RECV_PORT_ANY) ||
		    (cb->port == mcps_indication->Port)) {
			/* IsUplinkTxPending also indicates pending downlinks */
			cb->cb(mcps_indication->Port, \
			       mcps_indication->IsUplinkTxPending == 1, \
			       mcps_indication->Rssi, \
				   mcps_indication->Snr,\
			       mcps_indication->BufferSize,\
			       mcps_indication->Buffer);
		}
	}
	last_mcps_indication_status = mcps_indication->Status;
}
```
On detail it is crashing when doing this part:
```
/* IsUplinkTxPending also indicates pending downlinks */
cb->cb(mcps_indication->Port, \
mcps_indication->IsUplinkTxPending == 1, \
mcps_indication->Rssi, \
mcps_indication->Snr,\
mcps_indication->BufferSize,\
mcps_indication->Buffer);
```
For test reasons I added the '\' commands. 

My proj.conf looks like this:

> #UART
> CONFIG_SERIAL=y
> CONFIG_UART_LINE_CTRL=n
> CONFIG_UART_ASYNC_API=y
> CONFIG_UART_DRV_CMD=n
> CONFIG_UART_INTERRUPT_DRIVEN=y
> 
> #Console
> CONFIG_CONSOLE=y
> CONFIG_CONSOLE_SUBSYS=n
> CONFIG_USE_SEGGER_RTT=n
> CONFIG_RTT_CONSOLE=n
> CONFIG_UART_CONSOLE=y
> CONFIG_CONSOLE_GETLINE=n
> 
> #BOOTLOADER
> CONFIG_BOOTLOADER_MCUBOOT=y
> CONFIG_SECURE_BOOT=y
> CONFIG_BUILD_OUTPUT_HEX=y
> CONFIG_MCUBOOT_BOOTUTIL_LIB=y
> CONFIG_IMG_MANAGER=y
> CONFIG_MCUBOOT_IMG_MANAGER=y
> CONFIG_IMG_ENABLE_IMAGE_CHECK=y
> 
> #Storage-Partitions
> CONFIG_FLASH=y
> CONFIG_FLASH_PAGE_LAYOUT=y
> CONFIG_FLASH_MAP=y
> CONFIG_NVS=y
> CONFIG_SETTINGS_NVS=y
> CONFIG_PM_PARTITION_REGION_SETTINGS_STORAGE_EXTERNAL=y
> CONFIG_MPU_ALLOW_FLASH_WRITE=y
> CONFIG_PARTITION_MANAGER_ENABLED=y
> 
> #External Storage
> CONFIG_SPI_NOR=y
> CONFIG_SPI_NOR_FLASH_LAYOUT_PAGE_SIZE=4096
> CONFIG_PM_EXTERNAL_FLASH_MCUBOOT_SECONDARY=y
> CONFIG_STREAM_FLASH=y
> 
> #Storage
> CONFIG_MAIN_STACK_SIZE=8192
> CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=8192
> CONFIG_NEWLIB_LIBC_MIN_REQUIRED_HEAP_SIZE=2048
> CONFIG_HEAP_MEM_POOL_SIZE=2048
> CONFIG_IMG_BLOCK_BUF_SIZE=4096
> CONFIG_LORAWAN_SERVICES_THREAD_STACK_SIZE=2048
> 
> #Config logger
> CONFIG_LOG=y
> CONFIG_LOG_BACKEND_RTT=n
> CONFIG_LOG_BACKEND_UART=y
> 
> #USB
> CONFIG_USB_DEVICE_STACK=n
> #CONFIG_USB_DEVICE_PRODUCT="xxxx"
> #CONFIG_USB_DEVICE_VID=0x1915
> #CONFIG_USB_DEVICE_PID=0x9100
> CONFIG_USB_CDC_ACM=n
> CONFIG_USB_NRFX=n
> CONFIG_USB_DEVICE_DRIVER=n
> 
> #I2C
> CONFIG_I2C=y
> #CONFIG_NRFX_TWIM0=n
> 
> #CONFIG_I2C_TARGET=y
> #CONFIG_I2C_CALLBACK=y
> 
> #SPI
> CONFIG_SPI=y
> CONFIG_SPI_NRFX=y
> 
> #GPIO
> CONFIG_GPIO=y
> CONFIG_PINCTRL_NRF=y
> 
> #Sensors
> CONFIG_SENSOR=y
> 
> #PM
> CONFIG_PM=y
> CONFIG_PM_DEVICE=y
> CONFIG_PM_DEVICE_RUNTIME=y
> 
> #Watchdog
> CONFIG_WATCHDOG=y
> CONFIG_WDT_DISABLE_AT_BOOT=y
> 
> #LoRa
> CONFIG_LORA=y
> CONFIG_LORA_LOG_LEVEL_DBG=n
> CONFIG_LORA_SX127X=y
> CONFIG_NO_OPTIMIZATIONS=n
> 
> #LoRaWAN
> CONFIG_LORAWAN=y
> CONFIG_LORAWAN_LOG_LEVEL_DBG=y
> CONFIG_LORAMAC_REGION_EU868=y
> CONFIG_HAS_SEMTECH_LORAMAC=y
> CONFIG_HAS_SEMTECH_SOFT_SE=y
> CONFIG_HAS_SEMTECH_RADIO_DRIVERS=y
> CONFIG_LORAWAN_SERVICES=y 
> CONFIG_LORAWAN_APP_CLOCK_SYNC=y 
> 
> #BLE
> CONFIG_BT=y
> CONFIG_BT_PERIPHERAL=y
> CONFIG_BT_DEVICE_NAME="xxxxxxx"
> CONFIG_BT_DEVICE_APPEARANCE=833
> CONFIG_BT_DEBUG_LOG=n
> CONFIG_BT_SMP=y
> CONFIG_BT_MAX_CONN=2
> CONFIG_BT_MAX_PAIRED=1
> CONFIG_BT_NUS=y
> #CONFIG_BT_NUS_SECURITY_ENABLED=y
> CONFIG_BT_SETTINGS=y
> CONFIG_BT_GATT_CLIENT=y
> CONFIG_BT_USER_DATA_LEN_UPDATE=y
> CONFIG_BT_USER_PHY_UPDATE=y
> CONFIG_BT_GAP_AUTO_UPDATE_CONN_PARAMS=n
> CONFIG_BT_BUF_ACL_RX_SIZE=251
> CONFIG_BT_ATT_PREPARE_COUNT=2
> CONFIG_BT_L2CAP_TX_BUF_COUNT=10
> CONFIG_BT_L2CAP_TX_MTU=247
> CONFIG_BT_L2CAP_DYNAMIC_CHANNEL=n
> CONFIG_BT_CONN_TX_MAX=10
> CONFIG_BT_BUF_ACL_TX_COUNT=10
> CONFIG_BT_BUF_ACL_TX_SIZE=251
> CONFIG_BT_CTLR_DATA_LENGTH_MAX=251
> CONFIG_BT_CTLR_PHY_2M=y
> CONFIG_BT_CTLR_RX_BUFFERS=2
> CONFIG_BT_CTLR_SDC_MAX_CONN_EVENT_LEN_DEFAULT=4000000
> CONFIG_BT_PRIVACY=n
> CONFIG_BT_CONN_PARAM_UPDATE_TIMEOUT=300
> 
> #Libs
> CONFIG_ASSERT=y
> CONFIG_NEWLIB_LIBC_FLOAT_PRINTF=y
> CONFIG_CBPRINTF_FP_SUPPORT=y
> CONFIG_SETTINGS=y
> CONFIG_NEWLIB_LIBC=y
> CONFIG_CPLUSPLUS=y

And the sx1276 is configured in the overlay file as followed:

> &spi1 {
> 	compatible = "nordic,nrf-spi";
> 	status = "okay";
> 	cs-gpios = <&gpio0 12 GPIO_ACTIVE_LOW>;
> 	pinctrl-0 = <&spi1_default>;
> 	pinctrl-1 = <&spi1_sleep>;
> 	pinctrl-names = "default", "sleep";
> 	lora: sx1276@0 {
>         compatible = "semtech,sx1276";
>         reg = <0>;
> 		reset-gpios = <&gpio0 14 GPIO_ACTIVE_LOW>; //reset-gpios = <&gpio1 8 GPIO_ACTIVE_LOW>;
>         dio-gpios = <&gpio0 11 (GPIO_PULL_DOWN | GPIO_ACTIVE_HIGH)>,
>                     <&gpio0 21 (GPIO_PULL_DOWN | GPIO_ACTIVE_HIGH)>,
>                     <&gpio0 25 (GPIO_PULL_DOWN | GPIO_ACTIVE_HIGH)>;
> 	power-amplifier-output = "pa-boost";
> 	spi-max-frequency = <1000000>;
>     };
> };

**Comment by Mani-Sadhasivam** [comment]
@nkaufmn Can you share the downlink callback that has been registered using `lorawan_register_downlink_callback()` in the sample application?

**Comment by Mani-Sadhasivam** [comment]
@mniestroj @JordanYates FYI

**Comment by nkaufmn** [comment]
In my initialisation of lorawan I have this code snippet:

```
struct lorawan_downlink_cb downlink_cb = {
.port = LW_RECV_PORT_ANY,
.cb = dl_callback
};

lorawan_register_downlink_callback(&downlink_cb);
```
 and the dl_callback is defined in the same file as:

```
static void dl_callback(uint8_t port, bool data_pending, int16_t rssi, int8_t snr, uint8_t len, const uint8_t *data)
{
	printk("Port %d, Pending %d, RSSI %ddB, SNR %ddBm\n", port, data_pending, rssi, snr);
	printk("Payload: ");
	if (data) {
		for(int i = 0; i < len; i++){
			printk("%d", data);
		}
	}
	printk("\n");
}
```

**Comment by mniestroj** [comment]
> It only runs when everything is placed in one subprogramm, why can't I use more than one subprogram to access lorawan?

Could you elaborate? What do you mean by subprogram? Like using LoRaWAN APIs from two separate threads or what?

**Comment by craigpeacock** [comment]
I appear to be having a similar issue. I get the following run-time error:

```
[00:00:23.037,000] <dbg> lorawan: mcps_indication_handler: Received McpsIndication 0
[00:00:23.037,000] <dbg> lorawan: mcps_confirm_handler: Received McpsConfirm (for McpsRequest 1)
[00:00:23.037,000] <dbg> lorawan: mcps_confirm_handler: McpsRequest success!
[00:00:46.788,000] <dbg> lorawan: mcps_indication_handler: Received McpsIndication 0
[00:00:46.788,000] <err> os: ***** BUS FAULT *****
[00:00:46.788,000] <err> os:   Precise data bus error
[00:00:46.788,000] <err> os:   BFAR Address: 0x11f3861e
[00:00:46.789,000] <err> os: r0/a1:  0x00000001  r1/a2:  0x00ff7c82  r2/a3:  0x593e22d4
[00:00:46.789,000] <err> os: r3/a4:  0x000004af r12/ip:  0x00000c80 r14/lr:  0x0800ecdf
[00:00:46.789,000] <err> os:  xpsr:  0x21000000
[00:00:46.789,000] <err> os: Faulting instruction address (r15/pc): 0x08006142
[00:00:46.789,000] <err> os: >>> ZEPHYR FATAL ERROR 25: Unknown error on CPU 0
[00:00:46.789,000] <err> os: Current thread: 0x20001170 (unknown)
[00:00:46.859,000] <err> os: Halting system
```

I moved all the LoRaWAN functions into subroutines called from main. 

What I have found through trial and error is  

```
	struct lorawan_downlink_cb downlink_cb = {
		.port = LW_RECV_PORT_ANY,
		.cb = &dl_callback
	};

	lorawan_register_downlink_callback(&downlink_cb);
```
has to be called from main. All the other functions can be put into subroutines.

Is it something like lorawan_register_downlink_callback() references the structure, not copies it and the compiler destroys the structure once the routine has been called.

**Comment by JordanYates** [comment]
Almost certainly your problem is that your callback struct is being declared on the stack, and disappearing when the function returns. For example doing this WILL cause hard fault the next time a callback is generated:
```
void setup(void) {
	struct lorawan_downlink_cb downlink_cb = {
		.port = LW_RECV_PORT_ANY,
		.cb = &dl_callback
	};

	lorawan_register_downlink_callback(&downlink_cb);
}
```
The LoRaWAN subsystem requires that the provided struct remain valid for the lifetime of the program. Some ways to achieve that are:
1. Declare the struct in a function that never returns (your `main` suggestion above)
2. Declare the struct with the `static` qualifier, which will ensure it has a global lifetime
3. Declare the struct as a global variable

**Comment by jhedberg** [comment]
> Yes it solved the problem. Thank you.

Thanks! Closing this then.
