### ISSUE TITLE
drivers: eth_mcux: manage PHY reset without interrupt GPIO

### ISSUE THREAD

**Issue by blemouzy** [zephyrproject-rtos/zephyr#59709]
MCUX Ethernet driver allows PHY reset management through the `CONFIG_ETH_MCUX_PHY_RESET` option.
When this option is enabled, a reset GPIO and a interrupt GPIO must be provide.

This interrupt GPIO should be optional.

Board can have a reset GPIO and no interrupt GPIO (not connected).

**Comment by decsny** [comment]
closed with merge of new nxp_enet driver, eth_mcux will not support this
