### ISSUE TITLE
Update new contributor message to directly describe PR escalation

### ISSUE THREAD

**Issue by keith-zephyr** [zephyrproject-rtos/zephyr#59741]
The welcome message points new contributors to https://docs.zephyrproject.org/latest/contribute/contributor_expectations.html

However, the PR escalation information is found buried in this doc here: https://docs.zephyrproject.org/latest/contribute/contributor_expectations.html#pr-review-escalation

Update the new contributor message to also link directly to PR escalation, or potentially have standalone text included directly in the new contributor message.

**Comment by Pranitk1501** [comment]
Are there any additional details or suggestions you would like to add regarding the PR review escalation section on the new contributors' expectations page, considering that the information is already present there?
