### ISSUE TITLE
doc: code relocate: Function position note is invalid

### ISSUE THREAD

**Issue by nordicjm** [zephyrproject-rtos/zephyr#59782]
On https://docs.zephyrproject.org/latest/kernel/code-relocation.html it states the following:

> function zephyr_code_relocate() can be called as many times as required. This step has to be performed before calling find_package(Zephyr …) in the application’s CMakeLists.txt.

However this is incorrect, in fact the in-tree sample does not follow this rule: https://github.com/zephyrproject-rtos/zephyr/blob/main/samples/application_development/code_relocation_nocopy/CMakeLists.txt

**Comment by carlocaione** [comment]
@nordicjm do you mind opening a PR for this?
