### ISSUE TITLE
STM32H723 USB CDC ACM sample stops working when sending packets >= 64 byte

### ISSUE THREAD

**Issue by oktokl** [zephyrproject-rtos/zephyr#59828]
**Describe the bug**
When I send packets >= 64 bytes to the USB CDC ACM sample, I either get no reponse or get one after several more transmission without response.

**To Reproduce**
1. Flash usb cdc acm sample on nucleo_h723zg
4. Either send packets >= 64 bytes or use my [test program](https://github.com/oktokl/SerialTest): SerialTest COMxx 64

**Expected behavior**
USB full speed packets have a maximum size of 64 bytes. Data packets >= 64 bytes are assembled out of multiple USB packets. The sample should handle this packets or at least the receiver shouldn't stop working.

**Impact**
In case it is the usb cdc implementation, it's really bad if it can be put in a freezed state. Also, in order to reach high data rates, it's generally a good idea to transmit big packets. Actually, that seems not possible. 

**Logs and console output**
Here are different outputs of SerialTest and the corresponding traces:  [wireshark-trace.zip](https://github.com/zephyrproject-rtos/zephyr/files/11902675/wireshark-trace.zip)
The traces show that the sample application successfully echos the first 64 bytes of the first 64+ bytes packet. After this reponse, rx doesn't accept any further packets. 

***Packet size 63 (working)***
```
Sending 63 bytes:
0: AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
Sending 63 bytes:
1: AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
Sending 63 bytes:
2: AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
...
```

***Packet size 64 (not working)***
```
Sending 64 bytes:
Timeout
Sending 64 bytes:
Timeout
Sending 64 bytes:
Timeout
Sending 64 bytes:
Timeout
Sending 64 bytes:
Timeout
Sending 64 bytes:
Timeout
Sending 64 bytes:
Timeout
Sending 64 bytes:
0: AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
Sending 64 bytes:

[tx freezes here]
```

***Packet size 65 (not working)***
```
Sending 65 bytes:
Timeout
Sending 65 bytes:

[tx freezes here]
```

**Environment (please complete the following information):**
Platform: nucleo_h723zg; full speed usb interface with internal PHY
Host: Windows 10 Pro 22H2
Zephyr version: v3.4.0

**Comment by erwango** [comment]
@loicpoulain Would you have time to take a look ?

**Comment by Desvauxm-st** [comment]
@oktokl
i confirm that when we send a packets >= 64 bytes it doesn't works with the nucleo_h723zg
in fact the nucleo_h723zg use Otg_HS and not Otg_FS
to increase the length of the packet you must enable the CONFIG_USB_DC_HAS_HS_SUPPORT=y
after that in my case i can send more than 64 byte for example 101  bytes see after:

![image](https://github.com/zephyrproject-rtos/zephyr/assets/119042859/d6083252-240b-4bb2-9d2a-2682cf2d6070)


and in debug mode see the console ( first 64 byte and after 37 bytes)
![image](https://github.com/zephyrproject-rtos/zephyr/assets/119042859/85420e59-9f7e-4c5c-b7b6-447b095c5bd1)

I read that the host must also manage the ZLP ( zero length packet).

**Comment by erwango** [comment]
@oktokl We consider this is closed by https://github.com/zephyrproject-rtos/zephyr/pull/66692.
Please reopen if it is not the case.

**Comment by marwaiehm-st** [comment]
I reopened this issue because the proposed solution caused a problem with the WebUSB sample. 

- Enabling the **CONFIG_USB_DC_HAS_HS_SUPPORT** flag with the current OTG_HS configuration leads to issues with USB. 

- We may need to add an external ULPI PHY to support High-Speed USB operation to be able to set **CONFIG_USB_DC_HAS_HS_SUPPORT** without having any issues with High-Speed USB operation.

**Comment by marwaiehm-st** [comment]
This issue was fixed by this commit https://github.com/zephyrproject-rtos/zephyr/commit/c7cc58ca771a18faa0a8cb5c7f10a3b8bd429776
