### ISSUE TITLE
Issue about LoRaWAN specification version and Regional Parameters

### ISSUE THREAD

**Issue by shiwzhi** [zephyrproject-rtos/zephyr#59897]
**Is your enhancement proposal related to a problem? Please describe.**
In TTN's frequency plan of China 470-510 MHz, FSB 11 (used by TTN) only support older version of LoRaWAN Specification 1.0.3 and RP001 Regional Parameters. LoRaMac-node after [v4.4.7](https://github.com/Lora-net/LoRaMac-node/releases/tag/v4.4.7) is based on newer version of LoRaWAN specification

**Describe the solution you'd like**
Be able to config LoRaWAN version and Regional Parameters

**Describe alternatives you've considered**

**Additional context**
![1](https://github.com/zephyrproject-rtos/zephyr/assets/16424934/7b29dfc5-9004-487e-a761-a25833c63be3)

**Comment by JordanYates** [comment]
Supported LoRaWAN versions are driven by the upstream project (https://github.com/Lora-net/LoRaMac-node), and it is not feasible to support older specifications to enable this request.
