### ISSUE TITLE
Enabling PXP accelearion for lvgl for i. MXRT1064 

### ISSUE THREAD

**Issue by Gigate** [zephyrproject-rtos/zephyr#59921]
Greetings all,
Currently it isn't possible to use pxp gpu acceleration for 2D lvgl rendering in ZephyrOS. Pxp acceleration not only is necessary for faster rendering, but also for display rotation, which doesn't seem to be possible (with acceptable performance) without the pxp accel.

Here is some research of files that would be need. But just adding them to a Project isn't enough: 
- lv_gpu/lv_gpu_nxp.c, lv_gpu/lv_gpu_nxp.h: low level drawing calls for LVGL
- lv_gpu/lv_gpu_nxp_osa.c, lv_gpu/lv_gpu_osa.h: default implementation of OS-specific functions (bare metal and FreeRTOS only)
     - optional, required only if `LV_USE_GPU_NXP_PXP_AUTO_INIT` is set to 1
- PXP related code depends on two drivers provided by MCU SDK. These drivers need to be added to project:
    - fsl_pxp.c, fsl_pxp.h: PXP driver
    - fsl_cache.c, fsl_cache.h: CPU cache handling functions

**Comment by arfoll** [comment]
@danieldegrasse this is what we discussed in Prague at EOSS :) If we can help or you can point us how to contribute here we'd be open to this.

**Comment by danieldegrasse** [comment]
Hi @arfoll, I think integrating the PXP into LVGL directly would come later, as there are additional functions the PXP supports (like blending) that LVGL leverages. For the display rotation use case, I will look into exposing the PXP driver using the DMA API to see if it can satisfy your needs there.
