### ISSUE TITLE
posix: implement `mmap()`

### ISSUE THREAD

**Issue by ycsin** [zephyrproject-rtos/zephyr#59950]
There are currently 20 missing POSIX functions with trivial implementations, `mmap()` is one of them.

> mmap - map pages of memory
> 
> The mmap() function shall establish a mapping between an address space of a process and a memory object.
> ...

See https://pubs.opengroup.org/onlinepubs/9699919799/functions/mmap.html

See RFC #51211 for more info.

**Comment by KaiserS0ze** [comment]
Hi @ycsin I am a first-time contributor. Can I take a crack at this?

**Comment by ycsin** [comment]
> Hi @ycsin I am a first-time contributor. Can I take a crack at this?

Hi, please feel free to submit PR for anything

**Comment by KaiserS0ze** [comment]
Thanks. Yes, I think there are a lot of edge cases. I will start off with a simple implementation.
