### ISSUE TITLE
net_if_dev structure documentation seems cut off

### ISSUE THREAD

**Issue by decsny** [zephyrproject-rtos/zephyr#59975]
**Describe the bug**
The documentation of net_if_dev seems to be cut off suddenly and missing some information, I am not sure if this is intentional or not but it seems to be by accident that a sentence/paragraph is not finished. If it is intentional then the meaning is very confusing.

The documentation of the Network Interface Device structure is currently as follows:
```/**
 * @brief Network Interface Device structure
 *
 * Used to handle a network interface on top of a device driver instance.
 * There can be many net_if_dev instance against the same device.
 *
 * Such interface is mainly to be used by the link layer, but is also tight
 * to a network context: it then makes the relation with a network context
 * and the network device.
 *
 * Because of the strong relationship between a device driver and such
 * network interface, each net_if_dev should be instantiated by
 */
 ```

At the very end it says 

> Because of the strong relationship between a device driver and such network interface, each net_if_dev should be instantiated by

By what? How? I did not understand when I read this.

**Impact**
Confusing to understand network interface API

**Comment by jukkar** [comment]
Indeed, the wording here is missing something. I think it was suppose to read something like
```
... instantiated by one of the network device macros found in net_if.h.
```
Thanks for reporting it, the comment is very ancient but so far you have the first person to noticed it.
