### ISSUE TITLE
scripts: pylib: twister: twisterlib: environment: Probable incorrect check of device_testing argument

### ISSUE THREAD

**Issue by LukaszMrugala** [zephyrproject-rtos/zephyr#60035]
Note these two checks in `environment.py`, which are supposed to act as an early check for errors in `twister` call.

https://github.com/zephyrproject-rtos/zephyr/blob/c3dc01ddf3a5bdd599af08657a2052c57e0a093f/scripts/pylib/twister/twisterlib/environment.py#L732-L738

While the checks seem sensible, they conflict with the standard parser definition of the `add_parse_arguments()`. Here we have a definition of `device-testing`:

https://github.com/zephyrproject-rtos/zephyr/blob/c3dc01ddf3a5bdd599af08657a2052c57e0a093f/scripts/pylib/twister/twisterlib/environment.py#L141-L144

We can see that it uses `store_true`. This makes the variable have either `True` or `False` value. It cannot be None without further interference. Thus, in most cases, those previously mentioned if blocks will never be entered.

However, a simple change of `device-testing is None` to `not device-testing` is probably not sufficient. Here we have a definition of `device-flash-timeout`:

https://github.com/zephyrproject-rtos/zephyr/blob/c3dc01ddf3a5bdd599af08657a2052c57e0a093f/scripts/pylib/twister/twisterlib/environment.py#L171-L173

Thanks to that, we know that were that simple change to happen, we would force a typical twister user to have either `--device-testing` or `--device-flash-timeout=0` as arguments. It would not be advisable, as specifying an argument regarding a device without using a device is, at best, counter-intuitive.

**Comment by golowanow** [comment]
@LukaszMrugala please look at #60061
