### ISSUE TITLE
USB composite ACM and DFU gives error : MPU Fault on STM32F429I-DISCO

### ISSUE THREAD

**Issue by albayenes** [zephyrproject-rtos/zephyr#60065]
**Describe the bug**
Setting usb as composite of usb acm and dfu causes MPU fault error during firmware update on STM32F429I-DISCO. To prevent MPU fault, size check is necessary before usb_transfer.

I have one possible solution

```

diff --git a/subsys/usb/device/class/cdc_acm.c b/subsys/usb/device/class/cdc_acm.c
index ab14732440..3cc5bbc319 100644
--- a/subsys/usb/device/class/cdc_acm.c
+++ b/subsys/usb/device/class/cdc_acm.c
@@ -302,7 +302,8 @@ static void cdc_acm_read_cb(uint8_t ep, int size, void *priv)
        }

done:
-       usb_transfer(ep, dev_data->rx_buf, sizeof(dev_data->rx_buf),
+       if (size > 0)
+               usb_transfer(ep, dev_data->rx_buf, sizeof(dev_data->rx_buf),
                     USB_TRANS_READ, cdc_acm_read_cb, dev_data);
}

```

**To Reproduce**

DTS file

```

/*
 * Copyright (c) 2017 Linaro Limited
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/dts-v1/;
#include <st/f4/stm32f429Xi.dtsi>
#include <st/f4/stm32f429zitx-pinctrl.dtsi>
#include <zephyr/dt-bindings/display/ili9xxx.h>

/ {
	model = "STMicroelectronics STM32F429I_DISC1 board";
	compatible = "st,stm32f4discovery";

	chosen {
		zephyr,code-partition = &slot0_partition;
		zephyr,console = &usart1;
		zephyr,shell-uart = &usart1;
		zephyr,sram = &sram0;
		zephyr,flash = &flash0;
		zephyr,ccm = &ccm0;
		zephyr,display = &ili9341;
	};

	sdram2: sdram@d0000000 {
		compatible = "zephyr,memory-region", "mmio-sram";
		device_type = "memory";
		reg = <0xd0000000 DT_SIZE_M(8)>;
		zephyr,memory-region = "SDRAM2";
	};

	leds {
		compatible = "gpio-leds";
		orange_led_3: led_3 {
			gpios = <&gpiog 13 GPIO_ACTIVE_HIGH>;
			label = "User LD3";
		};
		green_led_4: led_4 {
			gpios = <&gpiog 14 GPIO_ACTIVE_HIGH>;
			label = "User LD4";
		};
	};

	gpio_keys {
		compatible = "gpio-keys";
		user_button: button {
			label = "User";
			gpios = <&gpioa 0 GPIO_ACTIVE_LOW>;
		};
	};

	aliases {
		led0 = &green_led_4;
		sw0 = &user_button;
	};
};

&clk_lsi {
	status = "okay";
};

&clk_hse {
	clock-frequency = <DT_FREQ_M(8)>;
	status = "okay";
};

&pll {
	div-m = <8>;
	mul-n = <336>;
	div-p = <2>;
	div-q = <7>;
	clocks = <&clk_hse>;
	status = "okay";
};

&rcc {
	clocks = <&pll>;
	clock-frequency = <DT_FREQ_M(168)>;
	ahb-prescaler = <1>;
	apb1-prescaler = <4>;
	apb2-prescaler = <2>;
};

&usart1 {
	pinctrl-0 = <&usart1_tx_pa9 &usart1_rx_pa10>;
	pinctrl-names = "default";
	current-speed = <115200>;
	status = "okay";
};

&rtc {
	clocks = <&rcc STM32_CLOCK_BUS_APB1 0x10000000>,
		 <&rcc STM32_SRC_LSI RTC_SEL(2)>;
	status = "okay";
};

&i2c1 {
	pinctrl-0 = <&i2c1_scl_pb8 &i2c1_sda_pb9>;
	pinctrl-names = "default";
	status = "okay";
	clock-frequency = <I2C_BITRATE_FAST>;
};

&i2c2 {
	pinctrl-0 = <&i2c2_scl_pb10 &i2c2_sda_pb11>;
	pinctrl-names = "default";
	status = "okay";
	clock-frequency = <I2C_BITRATE_FAST>;
};

&i2c3 {
	pinctrl-0 = <&i2c3_scl_pa8 &i2c3_sda_pc9>;
	pinctrl-names = "default";
	status = "okay";
	clock-frequency = <I2C_BITRATE_FAST>;
};

&spi5 {
	pinctrl-0 = <&spi5_nss_pf6 &spi5_sck_pf7
		     &spi5_miso_pf8 &spi5_mosi_pf9>;
	pinctrl-names = "default";
	status = "okay";
	cs-gpios = <&gpioc 2 GPIO_ACTIVE_LOW>;
	ili9341: ili9341@0 {
		compatible = "ilitek,ili9341";
		spi-max-frequency = <5625000>;
		reg = <0>;
		cmd-data-gpios = <&gpiod 13 GPIO_ACTIVE_LOW>;
		width = <240>;
		height = <320>;
		rotation = <180>;
		pixel-format = <ILI9XXX_PIXEL_FORMAT_RGB565>;
		pwctrla = [39 2c 00 34 02];
		pwctrlb = [00 c1 30];
		timctrla = [85 00 78];
		timctrlb = [00 00];
		pwseqctrl = [64 03 12 81];
		pumpratioctrl = [20];
		disctrl = [08 82 27 04];
		vmctrl1 = [45 15];
		vmctrl2 = [90];
		enable3g = [00];
		ifctl = [01 00 06];
		ifmode = [c2];
		gamset = [01];
		frmctr1 = [00 1b];
		pwctrl1 = [10];
		pwctrl2 = [10];
		pgamctrl = [0F 29 24 0c 0e 09 4e 78 3c 09 13 05 17 11 00];
		ngamctrl = [00 16 1b 04 11 07 31 33 42 05 0c 0a 28 2f 0f];
	};
};

&fmc {
	status = "okay";
	pinctrl-0 = <&fmc_nbl0_pe0 &fmc_nbl1_pe1
		     &fmc_sdclk_pg8 &fmc_sdnwe_pc0 &fmc_sdcke1_pb5
		     &fmc_sdne1_pb6 &fmc_sdnras_pf11 &fmc_sdncas_pg15
		     &fmc_a0_pf0 &fmc_a1_pf1 &fmc_a2_pf2 &fmc_a3_pf3
		     &fmc_a4_pf4 &fmc_a5_pf5 &fmc_a6_pf12 &fmc_a7_pf13
		     &fmc_a8_pf14 &fmc_a9_pf15 &fmc_a10_pg0 &fmc_a11_pg1
		     &fmc_a12_pg2 &fmc_a13_pg3 &fmc_a14_pg4 &fmc_a15_pg5
		     &fmc_d0_pd14 &fmc_d1_pd15 &fmc_d2_pd0 &fmc_d3_pd1
		     &fmc_d4_pe7 &fmc_d5_pe8 &fmc_d6_pe9 &fmc_d7_pe10
		     &fmc_d8_pe11 &fmc_d9_pe12 &fmc_d10_pe13 &fmc_d11_pe14
		     &fmc_d12_pe15 &fmc_d13_pd8 &fmc_d14_pd9 &fmc_d15_pd10>;
	pinctrl-names = "default";

	sdram {
		status = "okay";

		power-up-delay = <100>;
		num-auto-refresh = <1>;
		mode-register = <0>;
		refresh-rate = <1386>;

		bank@1 {
			reg = <1>;

			st,sdram-control = <STM32_FMC_SDRAM_NC_8
					    STM32_FMC_SDRAM_NR_12
					    STM32_FMC_SDRAM_MWID_16
					    STM32_FMC_SDRAM_NB_4
					    STM32_FMC_SDRAM_CAS_2
					    STM32_FMC_SDRAM_SDCLK_PERIOD_3
					    STM32_FMC_SDRAM_RBURST_DISABLE
					    STM32_FMC_SDRAM_RPIPE_1>;
			st,sdram-timing = <2 7 4 7 2 2 2>;
		};
	};
};

&ltdc {
	pinctrl-0 = <&ltdc_r2_pc10 &ltdc_r3_pb0 &ltdc_r4_pa11 &ltdc_r5_pa12
		     &ltdc_r6_pb1 &ltdc_r7_pg6 &ltdc_g2_pa6 &ltdc_g3_pg10
		     &ltdc_g4_pb10 &ltdc_g5_pb11 &ltdc_g6_pc7 &ltdc_g7_pd3
		     &ltdc_b2_pd6 &ltdc_b3_pg11 &ltdc_b4_pg12 &ltdc_b5_pa3
		     &ltdc_b6_pb8 &ltdc_b7_pb9 &ltdc_de_pf10 &ltdc_clk_pg7
		     &ltdc_hsync_pc6 &ltdc_vsync_pa4>;
	pinctrl-names = "default";
	ext-sdram = <&sdram2>;
	status = "okay";

	width = <240>;
	height = <320>;
	pixel-format = <PANEL_PIXEL_FORMAT_RGB_565>;
	display-timings {
		compatible = "zephyr,panel-timing";
		de-active = <0>;
		pixelclk-active = <0>;
		hsync-active = <0>;
		vsync-active = <0>;
		hsync-len = <10>;
		vsync-len = <2>;
		hback-porch= <20>;
		vback-porch = <2>;
		hfront-porch = <10>;
		vfront-porch = <4>;
	};
	def-back-color-red = <0xFF>;
	def-back-color-green = <0xFF>;
	def-back-color-blue = <0xFF>;
};

zephyr_udc0: &usbotg_hs {
	pinctrl-0 = <&usb_otg_hs_vbus_pb13 &usb_otg_hs_dm_pb14 &usb_otg_hs_dp_pb15>;
	pinctrl-names = "default";
	status = "okay";
	cdc_acm_uart0: cdc_acm_uart0 {
		compatible = "zephyr,cdc-acm-uart";
	};
};


&flash0 {
	partitions {
		compatible = "fixed-partitions";
		#address-cells = <1>;
		#size-cells = <1>;

		/* 64KB for bootloader */
		boot_partition: partition@0 {
			label = "mcuboot";
			reg = <0x00000000 DT_SIZE_K(64)>;
			read-only;
		};

		/* storage: 8KB for settings */
		storage_partition: partition@1e000 {
			label = "storage";
			reg = <0x0001e000 DT_SIZE_K(8)>;
		};

		/* application image slot: 384KB */
		slot0_partition: partition@20000 {
			label = "image-0";
			reg = <0x00020000 DT_SIZE_K(384)>;
		};

		/* backup slot: 384KB */
		slot1_partition: partition@80000 {
			label = "image-1";
			reg = <0x00080000 DT_SIZE_K(384)>;
		};

		/* swap slot: 128KB */
		scratch_partition: partition@e0000 {
			label = "image-scratch";
			reg = <0x000e0000 DT_SIZE_K(128)>;
		};

	};
};
 
```

1. west build \<zephyr-workspace\>/zephyr/samples/subsys/usb/cdc_acm -d 01-build-usb-cdc-acm-STM32F429ZI-DISC1 -b stm32f429i_disc1 -DEXTRA_CONF_FILE=overlay-composite-cdc-dfu.conf -p
2.\<zephyr-workspace\>/bootloader/mcuboot/scripts/imgtool.py sign \\
--key\<zephyr-workspace\>/bootloader/mcuboot/root-rsa-2048.pem \\
--header-size 0x200 \\
--align 8 \\
--version 1.2 \\
--slot-size 0x60000 \\
\<zephyr-workspace\>/01-build-usb-cdc-acm-STM32F429ZI-DISC1/zephyr/zephyr.bin \\
\<zephyr-workspace\>/01-build-usb-cdc-acm-STM32F429ZI-DISC1/zephyr/signed-usb-cdc-acm-app.bin
3. openocd -f /usr/share/openocd/scripts/interface/stlink-v2.cfg -f /usr/share/openocd/scripts/target/stm32f4x.cfg
4. telnet 127.0.0.1 4444
5. Using telnet connection format flash using following commands
6. reset
7. halt
8. stm32f2x mass_erase 0
9. reset
10. halt
11. flash write_image erase /home/enes/projects/zephyr-main-repo-workspace/01-build-mcuboot-STM32f429I_DISC1/zephyr/zephyr.bin 0x08000000
12. flash write_image erase <zephyr-workspace>/01-build-dfu-STM32f429I_DISC1/zephyr/signed-usb-cdc-acm-app.bin 0x0802000
13. exit
14. sudo dfu-util --alt 1 -D <sample-project-build-directory>/zephyr/signed-app.bin

**Expected behavior**
`dfu-util` should correctly upload the firmware image that is currently stored on the device flash.

**Impact**
Prevent my project from enabling the DFU function.

**Logs and console output**
```
I: Starting bootloader
I: Primary image: magic=unset, swap_type=0x1, copy_done=0x3, image_ok=0x3
I: Scratch: magic=unset, swap_type=0x1, copy_done=0x3, image_ok=0x3
I: Boot source: primary slot
I: Swap type: none
I: Bootloader chainload address offset: 0x20000
I: Jumping to the first image slot
*** Booting Zephyr OS build zephyr-v3.4.0-316-g86d7bd229e64 ***
Hello world 3 
[00:00:00.014,000] <inf> usb_cdc_acm: Device suspended
[00:00:00.414,000] <inf> usb_cdc_acm: Device configured
[00:00:00.419,000] <inf> usb_cdc_acm: ep 1 size 0 dev_data 0x20000000 rx_ringbuf space 1024
[00:00:06.816,000] <inf> usb_cdc_acm: Device suspended
[00:00:07.043,000] <inf> usb_cdc_acm: ep 1 size 0 dev_data 0x20000000 rx_ringbuf space 1024
[00:00:07.051,000] <err> os: ***** USAGE FAULT *****
[00:00:07.057,000] <err> os:   Division by zero
[00:00:07.062,000] <err> os: r0/a1:  0x40040000  r1/a2:  0x00000020  r2/a3:  0x000001ff
[00:00:07.071,000] <err> os: r3/a4:  0x00000000 r12/ip:  0x00000000 r14/lr:  0x0803c41f
[00:00:07.079,000] <err> os:  xpsr:  0x21000000
[00:00:07.085,000] <err> os: Faulting instruction address (r15/pc): 0x08030a78
[00:00:07.093,000] <err> os: >>> ZEPHYR FATAL ERROR 30: Unknown error on CPU 0
[00:00:07.100,000] <err> os: Current thread: 0x200006b8 (unknown)
[00:00:07.107,000] <err> os: Halting system
```

**Environment :**
Operating System: Manjaro Linux 
KDE Plasma Version: 5.27.5
KDE Frameworks Version: 5.106.0
Qt Version: 5.15.9
Kernel Version: 6.1.31-2-MANJARO (64-bit)
Graphics Platform: X11
Processors: 20 × 12th Gen Intel® Core™ i9-12900H
Memory: 15,4 GiB of RAM
Graphics Processor: Mesa Intel® Graphics
Manufacturer: HUAWEI
Product Name: CREF-XX
System Version: M1010

**Additional context**

I've found the solution, adding sleep between HAL_PCD_Init and HAL_PCD_Stop solves the problem.

```
diff --git a/subsys/usb/device/class/cdc_acm.c b/subsys/usb/device/class/cdc_acm.c
index ab14732440..3cc5bbc319 100644
--- a/subsys/usb/device/class/cdc_acm.c
+++ b/subsys/usb/device/class/cdc_acm.c
@@ -302,7 +302,8 @@ static void cdc_acm_read_cb(uint8_t ep, int size, void *priv)
        }

done:
-       usb_transfer(ep, dev_data->rx_buf, sizeof(dev_data->rx_buf),
+       if (size > 0)
+               usb_transfer(ep, dev_data->rx_buf, sizeof(dev_data->rx_buf),
                     USB_TRANS_READ, cdc_acm_read_cb, dev_data);
}
```

**Comment by tmon-nordic** [comment]
> I have one possible solution
> 
> ```
> 
> diff --git a/subsys/usb/device/class/cdc_acm.c b/subsys/usb/device/class/cdc_acm.c
> index ab14732440..3cc5bbc319 100644
> --- a/subsys/usb/device/class/cdc_acm.c
> +++ b/subsys/usb/device/class/cdc_acm.c
> @@ -302,7 +302,8 @@ static void cdc_acm_read_cb(uint8_t ep, int size, void *priv)
>         }
> 
> done:
> -       usb_transfer(ep, dev_data->rx_buf, sizeof(dev_data->rx_buf),
> +       if (size > 0)
> +               usb_transfer(ep, dev_data->rx_buf, sizeof(dev_data->rx_buf),
>                      USB_TRANS_READ, cdc_acm_read_cb, dev_data);
> }
> ```

But this would kill the IN endpoint, wouldn't it? Are you able to receive anything after the `if (size > 0)` branch is not taken?

**Comment by albayenes** [comment]
> > I have one possible solution
> > ```
> > 
> > diff --git a/subsys/usb/device/class/cdc_acm.c b/subsys/usb/device/class/cdc_acm.c
> > index ab14732440..3cc5bbc319 100644
> > --- a/subsys/usb/device/class/cdc_acm.c
> > +++ b/subsys/usb/device/class/cdc_acm.c
> > @@ -302,7 +302,8 @@ static void cdc_acm_read_cb(uint8_t ep, int size, void *priv)
> >         }
> > 
> > done:
> > -       usb_transfer(ep, dev_data->rx_buf, sizeof(dev_data->rx_buf),
> > +       if (size > 0)
> > +               usb_transfer(ep, dev_data->rx_buf, sizeof(dev_data->rx_buf),
> >                      USB_TRANS_READ, cdc_acm_read_cb, dev_data);
> > }
> > ```
> 
> But this would kill the OUT endpoint, wouldn't it? Are you able to receive anything after the `if (size > 0)` branch is not taken?

Yes you are right. I am working on it. I have to fins a way to prevent usb transfer during DFU communication. Are there such flags? Is it valid usb transfer during DFU update?

**Comment by tmon-nordic** [comment]
> Yes you are right. I am working on it. I have to find a way to prevent usb transfer during DFU communication. Are there such flags? Is it valid usb transfer during DFU update?

The is what the Run-Time and DFU Mode are for in the DFU Specification. In Run-Time mode, the host executes DFU_DETACH and then device switch to DFU Mode (enumerates again on the bus exposing different configuration and different product ID).

USB Device Firmware Upgrade Specification, Revision 1.1
> 4.2.2 DFU Mode Configuration Descriptor
> This descriptor is identical to the standard configuration descriptor described in the USB specification
> version 1.0, with the exception that the bNumInterfaces field must contain the value 01h.

This basically means you cannot have CDC ACM simultaneously when device is in DFU Mode. You can only have simultaneous Run-Time and CDC ACM.

The first thing to check would be to determine whether DFU_DETACH correctly frees all resources on your target.

**Comment by albayenes** [comment]
> > Yes you are right. I am working on it. I have to find a way to prevent usb transfer during DFU communication. Are there such flags? Is it valid usb transfer during DFU update?
> 
> The is what the Run-Time and DFU Mode are for in the DFU Specification. In Run-Time mode, the host executes DFU_DETACH and then device switch to DFU Mode (enumerates again on the bus exposing different configuration and different product ID).
> 
> USB Device Firmware Upgrade Specification, Revision 1.1
> 
> > 4.2.2 DFU Mode Configuration Descriptor
> > This descriptor is identical to the standard configuration descriptor described in the USB specification
> > version 1.0, with the exception that the bNumInterfaces field must contain the value 01h.
> 
> This basically means you cannot have CDC ACM simultaneously when device is in DFU Mode. You can only have simultaneous Run-Time and CDC ACM.
> 
> The first thing to check would be to determine whether DFU_DETACH correctly frees all resources on your target.

As far as I understand, ` usb_dc_detach ` in usb_dc_stm32.c is not working correctly. Do you think this is the possible reason?

**Comment by tmon-nordic** [comment]
> As far as I understand, `usb_dc_detach` in usb_dc_stm32.c is not working correctly. Do you think this is the possible reason?

Yes if `CONFIG_USB_DFU_WILL_DETACH` is enabled. You can disable `USB_DFU_WILL_DETACH` in Kconfig and check.

**Comment by albayenes** [comment]
> USB_DFU_WILL_DETACH

Disabling CONFIG_USB_DFU_WILL_DETACH solves the problem. Thanks for your help. But now gives following error

```
Waiting for device, exit with ctrl-C
Opening DFU capable USB device...
Device ID 2fe3:0001
Run-Time device DFU version 0110
Claiming USB DFU (Run-Time) Interface...
Setting Alternate Interface zero...
Determining device status...
DFU state(0) = appIDLE, status(0) = No error condition is present
Device really in Run-Time Mode, send DFU detach request...
Resetting USB...
Opening DFU USB Device...
Claiming USB DFU Interface...
Setting Alternate Interface #1 ...
Determining device status...
DFU state(2) = dfuIDLE, status(0) = No error condition is present
DFU mode device DFU version 0110
Device returned transfer size 128
Copying data from PC to DFU device
Download        [==                       ]   8%        21376 bytesdfu-util: Error during download (LIBUSB_ERROR_TIMEOUT)

```

**Comment by albayenes** [comment]
> > USB_DFU_WILL_DETACH
> 
> Disabling CONFIG_USB_DFU_WILL_DETACH solves the problem. Thanks for your help. But now gives following error
> 
> ```
> Waiting for device, exit with ctrl-C
> Opening DFU capable USB device...
> Device ID 2fe3:0001
> Run-Time device DFU version 0110
> Claiming USB DFU (Run-Time) Interface...
> Setting Alternate Interface zero...
> Determining device status...
> DFU state(0) = appIDLE, status(0) = No error condition is present
> Device really in Run-Time Mode, send DFU detach request...
> Resetting USB...
> Opening DFU USB Device...
> Claiming USB DFU Interface...
> Setting Alternate Interface #1 ...
> Determining device status...
> DFU state(2) = dfuIDLE, status(0) = No error condition is present
> DFU mode device DFU version 0110
> Device returned transfer size 128
> Copying data from PC to DFU device
> Download        [==                       ]   8%        21376 bytesdfu-util: Error during download (LIBUSB_ERROR_TIMEOUT)
> ```

Increasing stack sizes solves the problem.

```


CONFIG_ISR_STACK_SIZE=9096

CONFIG_IDLE_STACK_SIZE=9096
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=9096
CONFIG_USB_WORKQUEUE_STACK_SIZE=9096

CONFIG_PRIVILEGED_STACK_SIZE=9096

```
