### ISSUE TITLE
native: Add support for TAP net device 

### ISSUE THREAD

**Issue by nashif** [zephyrproject-rtos/zephyr#6007]
Now that we have native_posix port, we need to add a TAP net device to be able to utilize the host network for testing and simulation.

**Comment by jukkar** [comment]
@aescolar-ot Do you have plans to work on this? If not, I could start to look into it.

**Comment by aescolar-ot** [comment]
> Do you have plans to work on this? If not, I could start to look into it.

No plans from my side, so feel free.

**Comment by jukkar** [comment]
Ok, taking this one.
