### ISSUE TITLE
west autocompletion in CLI is missing directories

### ISSUE THREAD

**Issue by ericsunplus** [zephyrproject-rtos/zephyr#60127]
I am using west version v1.0.0 in bash. bash has builtin path auto completion, but when I execute a west command, the bash auto completion seems to be bypassed.

Suppose I have the following directory structure
```
|
+--- .west
|
+--- main_repo
        |
        +--- west.yml
        |
        +--- repoSet
                |
                +--- repo1
                |
                +--- repo2
                |
                +--- ...
```
I am in directory `main_repo` and try to see information of a sub repo
```
west list repoSet/repo1
```
When I type the command, `repoSet/repo1` do not have autocomplete. But when I use other bash commands, the path have auto complete.

**Comment by carlescufi** [comment]
> I don't know if it's even possible to performed "advanced" auto completion for `west list lz4` AND "basic", path-based auto completion for `west list ../modules/lib/lz4` _at the same time_, is it? @carlescufi do you know?

I don't really know @marc-hb sorry. I wrote the autocompletion for bash a while back and it was a bit of an amateur attempt on my side. I then cleaned it up a bit after I added zsh support, but that's about it. @ericsunplus feel free to propose a patch to implement what you describe, but like @marc-hb already said, this is not common in autocompletion.
