### ISSUE TITLE
Code relocation generation script tries to parse global compile definitions as files

### ISSUE THREAD

**Issue by MarijnStam** [zephyrproject-rtos/zephyr#60220]
**Describe the bug**
It seems that globally added compile definitions added through CMake's `add_compile_definition()` call, are somehow parsed by the gen_relocate.py python script as files, leading to parsing error when building an otherwise valid project/sample.

**To Reproduce**
1. Start from a clean Zephyr repo. I just followed https://docs.zephyrproject.org/latest/develop/getting_started/index.html to reproduce this issue 
2. Add any global compile definition in the CMakeLists.txt file of `samples/application_development/code_relocation_nocopy/`  In my case I added `add_compile_definitions(FRAMEWORK_DISABLE_ARRAY_SIZE)`
3. Build the aforementioned sample with the following command: `west build -p always -b nrf5340dk_nrf5340_cpuapp samples/application_development/code_relocation_nocopy`
4. The build output spits out the following warning: 
```
[166/176] Generating code_relocation.c, include/generated/linker_relocate.ld
/home/marijn/zephyrsamples/zephyr/scripts/build/gen_relocate_app.py:530: UserWarning: File: FRAMEWORKMACROS_DISABLE_ARRAY_SIZE Not found
  warnings.warn("File: "+file_glob+" Not found")
```

**Expected behavior**
I expect global compile definitions not to be parsed by this code relocation script. I verified that this is actually happening by checking the build.ninja file, in which the full invocation of this script can be found. In the input string for the script, this compile definition along with any others you may pass will be parsed by the gen_relocation.py script. 

**Impact**
This warning can be solved by using `target_compile_definition` instead of the global version, however I think it is not very workable that global compilation definitions cannot be added now if you use code_relocation, or you will get this warning. 

**Environment (please complete the following information):**
 - OS: Linux 5.15.90.1-microsoft-standard-WSL2
 - Toolchain zephyr-sdk-0.16.1
 - Version 3.4.0 used (3.4 patchlevel 99 )

**Comment by dcpleung** [comment]
@danieldegrasse Could you take a look at this? I am not really familiar with all the code relocation code, and you are the last person overhauling the cmake function. From what I can tell, using the named property `COMPILE_DEFINITIONS` is what causing the issue as CMake adds all the global compile definitions to all targets. Changing the named property would not work as this needs the magic touch of `COMPILE_DEFINITIONS` as it evals/expands all the generator expressions before sending them to ninja. Or else the command line would still contain the generator expressions, which ninja fails to parse.

**Comment by danieldegrasse** [comment]
@tejlmand Do you have any thoughts here? We could switch to another variable supported by CMake generator expressions, such as INTERFACE_SOURCES, but only a subset of all CMake properties support expanding generator expressions as far as I know.

**Comment by MarijnStam** [comment]
I would like to have the Stale label removed as this issue has not been closed yet and is still relevant.

**Comment by danieldegrasse** [comment]
> @tejlmand Do you have any thoughts here? We could switch to another variable supported by CMake generator expressions, such as INTERFACE_SOURCES, but only a subset of all CMake properties support expanding generator expressions as far as I know.

@tejlmand ping- I'm wondering if there is a way to use CMake to expand a custom variable within generator expressions, so we can stop overloading the `COMPILE_DEFINITIONS` variable when using code relocation

**Comment by danieldegrasse** [comment]
> @tejlmand ping- I'm wondering if there is a way to use CMake to expand a custom variable within generator expressions, so we can stop overloading the COMPILE_DEFINITIONS variable when using code relocation

@tejlmand pinging again here- I'm not sure what the best way to solve this is, but it does seem like an issue. Do we want to treat the workaround proposed in the initial issue description:

> This warning can be solved by using target_compile_definition instead of the global version, however I think it is not very workable that global compilation definitions cannot be added now if you use code_relocation, or you will get this warning.

as the long term solution here?
