### ISSUE TITLE
Consistent feature dependency checks based on ARMvX-M

### ISSUE THREAD

**Issue by carlescufi** [zephyrproject-rtos/zephyr#6022]
Introduce checks for the different ARMvX-M registers and features so that we make sure that they are not accidentally enabled by the users.
This includes VTOR, BASEPRI and all of the rest of the ARMvX-M features.

**Comment by ioannisg** [comment]
VTOR register
 - holds the vector table [offset] address

**Comment by ioannisg** [comment]
Closing this (#6143) is reviewed and merged.
