### ISSUE TITLE
Zephyr module uoscore-uedhoc sample `samples/zephyr_oscore/server` refers to tinycbor which no longer exists

### ISSUE THREAD

**Issue by nordicjm** [zephyrproject-rtos/zephyr#60235]
**Describe the bug**
This file: https://github.com/zephyrproject-rtos/uoscore-uedhoc/blob/zephyr/samples/zephyr_oscore/server/CMakeLists.txt refers to tinycbor in zephyr, a module which no longer exists. It also uses the old `$ENV{ZEPHYR_BASE}` variable which should be replaced with `${ZEPHYR_BASE}`

**Expected behavior**
Issues to be addressed

**Impact**
Probably NIL since no one has reported this issue before so assuming no-one uses this codebase and/or sample

**Comment by nordicjm** [comment]
@StefanHri since you seem to maintain this module

**Comment by carlescufi** [comment]
@nordicjm I just discussed this with @rlubos and apparently the samples included  in the module are not used at all by Zephyr, only the library itself is. So perhaps this issue should be moved to the upstream project?

**Comment by rlubos** [comment]
I've opened #60789 which updates the module to the latest revision. Tinycbor is no longer in use.
