### ISSUE TITLE
Voltage sensor

### ISSUE THREAD

**Issue by nixward** [zephyrproject-rtos/zephyr#60251]
**Is your feature request related to a problem? Please describe.**
Similar to other ADC based sensors, like the mcp970x temperature sensor, it would be great to have a voltage sensor that would be useful for checking a device's battery voltage.

**Describe the solution you'd like**
A voltage sensor based on the voltage-divider binding.

**Describe alternatives you've considered**
Using the voltage-divider binding on it's own.

**Additional context**
Having access to one or more voltage sensors from the Zephyr shell with only a little bit of Devicetree configuration is a nice feature to have.

**Comment by diegoherranz** [comment]
Given https://github.com/zephyrproject-rtos/zephyr/pull/59132 was merged, can this be closed?

**Comment by nixward** [comment]
https://github.com/zephyrproject-rtos/zephyr/pull/59132
