### ISSUE TITLE
lpadc driver does not correctly handle sampling more than 2 channels

### ISSUE THREAD

**Issue by danieldegrasse** [zephyrproject-rtos/zephyr#60277]
**Describe the bug**
The MCUX LPADC driver does not correctly handle chaining more than 2 channels together since https://github.com/zephyrproject-rtos/zephyr/commit/e587047dc6b77c28ea399e272c41beb2cd52f142. The core issue is that the `last_channel` variable is only set after the first channel chaining occurs. This means that all future channels will be chained to the first (highest) channel, and thus not all channels will be triggered.

For example, if channels 0, 1, and 2 are enabled, the following chain should be built:
0 -> 1 -> 2
The driver instead builds this chain:
1->2; 0->2.

Therefore, channel 0 will be triggered, and channel 2 will complete. Channel 1 will never run, so the `adc_read` function will not return.

**To Reproduce**
1. Use #60276, which updates the ADC API test to support sampling with 3 channels
2. Attempt to run the test on an LPCXpresso55s69
3. the `adc_read` call in `test_task_multiple_channels` will not return.

**Expected behavior**
A correct ADC command chain should be built, and all samples should complete.

**Additional Context**
Issue was first reported by @tyalie in #60111, this issue simply is to track the backport to 3.4

**Comment by DerekSnell** [comment]
Fixed by https://github.com/zephyrproject-rtos/zephyr/pull/60278
