### ISSUE TITLE
Enable Issues for the zephyrproject-rtos/example-application repo

### ISSUE THREAD

**Issue by IvanVnucec** [zephyrproject-rtos/zephyr#60286]
### Discussed in https://github.com/zephyrproject-rtos/zephyr/discussions/59983

<div type='discussions-op-text'>

<sup>Originally posted by **IvanVnucec** July  4, 2023</sup>
I want to improve the https://github.com/zephyrproject-rtos/example-application repo but there is no way to create an Issue. I think this would improve repo quality.</div>

**Comment by gmarull** [comment]
Just open issues in the main Zephyr repo, or open PRs with patches there.

**Comment by IvanVnucec** [comment]
> Just open issues in the main Zephyr repo, or open PRs with patches there.

I've just did and they're being closed without explanation why.
