### ISSUE TITLE
West flash error: FATAL ERROR: command exited with status 1: /opt/SEGGER/JLink_V770e/JLinkExe -nogui 1 -if swd -speed 4000 -device nrf52 -CommanderScript /tmp/tmpk3q73nykjlink/runner.jlink -nogui 1

### ISSUE THREAD

**Issue by rubenwat** [zephyrproject-rtos/zephyr#60303]
Hi,

I am having troubles when I try to flash my microcontroller nrf52840 with the command "west flash" and the error I get is the next:
FATAL ERROR: command exited with status 1: /opt/SEGGER/JLink_V770e/JLinkExe -nogui 1 -if swd -speed 4000 -device nrf52 -CommanderScript /tmp/tmpk3q73nykjlink/runner.jlink -nogui 1

-In the past I was working with zephyr vanila and everything was working fine but now that I work with nrf 2.2.0 I have troubles.
![image](https://github.com/zephyrproject-rtos/zephyr/assets/113450433/9c5545c4-d237-4b3b-b187-9f5ae1ec51c1)
![image](https://github.com/zephyrproject-rtos/zephyr/assets/113450433/a56d03ec-d3fe-4f6b-bbcd-b62451d3c40b)
-I only get to flash with the next comand correctly nrfjprog -f nrf52 --debugreset && nrfjprog -f nrf52 --program build/zephyr/zephyr.hex --sectorerase --verify && nrfjprog -f nrf52 --debugreset.
![image](https://github.com/zephyrproject-rtos/zephyr/assets/113450433/8457a0a5-ddfb-403b-92c5-239b08a5a5b4)

-This error just happens when my memory flash used is larger than 50% so seems maybe is something related to partitions but I do not understand because I have other project that I can flash correctly so the problems seems is just related to this project.

¿maybe the bootloader is not working correctly?

I can send you all information you need, thank you in advance.

Best regards

**Comment by nordicjm** [comment]
Use the nrfjprog flash runner, not jlink, e.g. `west flash -r nrfjrpog`

**Comment by rubenwat** [comment]
What you say kind of work I will keep checking, but what could be the reason this command works in one project and not in another, the error message I get does not specify if my problem is about the memory or another reason, I would like to make it work with west flash because I always pass a preconfiguration of the flash before flashing the program.bin and I have some troubles when I use west flash -r nrfjprog after pass the preconfiguration.

**Comment by carlescufi** [comment]
@rubenwat this is not a Zephyr bug, but rather an NCS one if at all. Please post this question in the Nordic DevZone instead.
