### ISSUE TITLE
posix: uname: follow up enhancements

### ISSUE THREAD

**Issue by ycsin** [zephyrproject-rtos/zephyr#60377]
Follow up enhancements to the `uname` PR in #59981
- https://github.com/zephyrproject-rtos/zephyr/pull/59981#discussion_r1257471696
- https://github.com/zephyrproject-rtos/zephyr/pull/59981#issuecomment-1627699316#63973 

**EDIT:**
This issue is about the namespacing of the generated `version.h`

**Comment by ycsin** [comment]
Probably not solved yet

**Comment by cfriedt** [comment]
@ycsin - is there anything specifically that needs to be done here?

**Comment by ycsin** [comment]
> I guess it depends on #63973 ?

yeah
