### ISSUE TITLE
Implement interrupt driven USART on LPC54114

### ISSUE THREAD

**Issue by MaureenHelm** [zephyrproject-rtos/zephyr#6039]
Currently the usart shim driver for LPC54114 only supports polling mode; add support for interrupt-driven mode. This is needed to support the console shell.

**Comment by galak** [comment]
@agansari can you look at adding interrupt support to the UART driver.

**Comment by agansari** [comment]
@MaureenHelm  @galak  I have this ready working, but it depends on pull #15647 as I developed and tested on LPC55S69.
