### ISSUE TITLE
LE Audio: ASCS check codec cid and vid field cause endpoint set codec fail.

### ISSUE THREAD

**Issue by ChangNice** [zephyrproject-rtos/zephyr#60492]
When set codec in ascs, the function **codec_lookup_id()** will check cid and vid. And if server and client have different cid or vid, a 
BT_BAP_ASCS_RSP_CODE_CONF_INVALID with BT_BAP_ASCS_REASON_CODEC will be triggered.

Consider this case, client and server come from different company both use LC3 codec, but with different cid with not work. This means that there will no compatible between devices.

You could ask user do not fill cid and vid to walkaround this, but I think this is not reasonable to check cid and vid.

**To Reproduce**
Since unicast_audio_server/client both use preset parameters, cid and vid both filled with zero, so we need modify the demo code and fill cid or vid to trigger this issue.

For unicast_audio_client add `codec_configuration.codec.cid = 1;` at init will trigger this issue.
For unicast_audio_server add `lc3_codec.cid = 2;` at init will trigger this issue.

**Comment by Thalley** [comment]
The `cid` of the codec does not refer to the company of the device, but the company of the codec. 

For LC3 (or any non-vendor specific codecs) both the `cid` and `vid` shall be 0. 

The triple, `{id, cid, vid}` is the unique identifier of a codec. 

Closing the issue due to this
