### ISSUE TITLE
Bluetooth: No BLE ext adv btp commands support in bt_tester app

### ISSUE THREAD

**Issue by jsplyy** [zephyrproject-rtos/zephyr#60494]
**Is your feature request related to a problem? Please describe.**
we are in enabling the TMAP pts test cases with auto-pts
but for the TMAP device discovery test suite, it requires to set the different TMAP Role characteristic in extended advertising.
![image](https://github.com/zephyrproject-rtos/zephyr/assets/3600912/8a61474b-887f-4520-a3d3-12e3b6a935a3)

but we could not find the ext_adv btp commands in bt_tester, 
https://github.com/zephyrproject-rtos/zephyr/blob/main/tests/bluetooth/tester/src/btp_gap.c

**Describe the solution you'd like**
add some btp commands and events in bt_tester app for the ext_adv apis.
![image](https://github.com/zephyrproject-rtos/zephyr/assets/3600912/44b0051b-41ad-4644-b611-d475e5964edf)

**Comment by mkasenberg** [comment]
I already have a patch for ext adv, because I needed it for BAP tests for unicast server. I'll post a PR soon.
