### ISSUE TITLE
LE audio TMAP: Add role verification

### ISSUE THREAD

**Issue by JingsaiLu** [zephyrproject-rtos/zephyr#60495]
**Is your enhancement proposal related to a problem? Please describe.**
want to discuss if we should add any abstraction layers for the different TMAP roles in tmap driver?

each TMAP role requires some special settings and low layer profile procedures.
![image](https://github.com/zephyrproject-rtos/zephyr/assets/3600912/82a9ce78-c758-4bc7-b6e7-0f2f6652777d)
but there is no more implementation for these in tmap.c
https://github.com/zephyrproject-rtos/zephyr/blob/main/subsys/bluetooth/audio/tmap.c

we do these in demo apps:
https://github.com/zephyrproject-rtos/zephyr/pull/60288/commits/b926b294610a255eb81079a68764e3a486848e95#diff-cc104b7b2a9cb82bee5f3b6d56b8f3a54b4d2660731f7546c26bbd2eca310f5f
https://github.com/zephyrproject-rtos/zephyr/pull/56686/commits/f4f0f003a4e6cb3d88a7049a0c59625588eced32#diff-48dd3e98c744416052457825e6733baa10cfc8d0bfa0644aee65dddab49317c4

**Describe the solution you'd like**
add more apis to simplify the TMAP role usages.

**Comment by Thalley** [comment]
Indeed. `bt_tmap_register` and `bt_tmap_set_role` should return an error if the supplied role is not supported by the device
