### ISSUE TITLE
scripts: pylib: twister: twisterlib: environment: Unguarded member access in TwisterEnv __init__()

### ISSUE THREAD

**Issue by LukaszMrugala** [zephyrproject-rtos/zephyr#60522]
Initialisation of `TwisterEnv` is careful as to check whether `options` parameter is not `None` before trying to access it. 

https://github.com/zephyrproject-rtos/zephyr/blob/b8f7c81dd3930ae1dde60dcf1daba32d03176816/scripts/pylib/twister/twisterlib/environment.py#L800-L820

However, at the very end of `__init__`, we've got two accesses that fail to check for whether any `options` exist.

https://github.com/zephyrproject-rtos/zephyr/blob/b8f7c81dd3930ae1dde60dcf1daba32d03176816/scripts/pylib/twister/twisterlib/environment.py#L824-L826

In my opinion, that should be guarded against.

**Comment by nashif** [comment]
@LukaszMrugala  can you please subit a PR fixing this?

**Comment by LukaszMrugala** [comment]
> @LukaszMrugala can you please subit a PR fixing this?

Done in PR #60526
