### ISSUE TITLE
[version 3.4] Linker scripts do not define _end correctly

### ISSUE THREAD

**Issue by keith-packard** [zephyrproject-rtos/zephyr#60545]
In version 3.4, The various sample linker scripts do not define `_end` correctly or consistently. This breaks code using this symbol, such as the common malloc implementation. This has been fixed upstream in #57727 which should be backported.

**Comment by fabiobaltieri** [comment]
Hey @keith-packard, 3.4 has been unsupported for a while, closing this down.
