### ISSUE TITLE
NXP enable RTIO for lpspi on rt.

### ISSUE THREAD

**Issue by bperseghetti** [zephyrproject-rtos/zephyr#60543]
**Is your enhancement proposal related to a problem? Please describe.**
Currently cannot use the streaming pipeline for sensors due to no enablement for RTIO with lpspi on NXP mimxrts.

**Describe the solution you'd like**
Allow for using RTIO_SPI for sensors NXP VMU_RT7 reference design board.

**Describe alternatives you've considered**
N/A
**Additional context**
N/A

**Comment by teburd** [comment]
I believe this has been completed by #62057
