### ISSUE TITLE
LE Audio: Host: Wrong state after link loss of a CIS

### ISSUE THREAD

**Issue by mkasenberg** [zephyrproject-rtos/zephyr#60669]
The PTS BAP/USR/SCC/BV-168-C test case fails because at sudden link loss of CIS, the IUT (in server role) acts according to Table 3.2: 'ASE state machine transitions', which are valid for ASE Control Operations, but does not include the exception described in ASCS specification (ACSC_v1.0-1.pdf, 3.2 ASE state machine transitions):

'If the server detects link loss of a CIS for an ASE in the Streaming state or the Disabling state, the server shall immediately transition that ASE to the QoS Configured state. Link loss of a CIS for an ASE in any state other than Streaming or Disabling shall not cause a transition of the ASE state machine.'

So, even if ASE is Source, it should end up in QoS Configured, not in Disabling state.
https://github.com/zephyrproject-rtos/zephyr/blob/b69cd3cbc101cae3558a4730fa320e25a43b1543/subsys/bluetooth/audio/ascs.c#L898-L912

PTS logs:
[BAP_USR_SCC_BV_168_C_2023_07_21_09_15_30.zip](https://github.com/zephyrproject-rtos/zephyr/files/12117590/BAP_USR_SCC_BV_168_C_2023_07_21_09_15_30.zip)

IUT logs:
[BAP_USR_SCC_BV-168-C_iutctl.log](https://github.com/zephyrproject-rtos/zephyr/files/12117582/BAP_USR_SCC_BV-168-C_iutctl.log)

**Comment by MariuszSkamra** [comment]
I've reported an issue on PTS: https://support.bluetooth.com/hc/en-us/requests/27007 for BAP_USR_SCC_BV-167-C and BAP_USR_SCC_BV-168-C as those does not test link-loss
