### ISSUE TITLE
LwM2M: support object versioning in register / discover operations

### ISSUE THREAD

**Issue by mike-scott** [zephyrproject-rtos/zephyr#6066]
The only item left to meet OMA LwM2M 1.0 Enabler Static Conformance Requirements (mandatory items) is the following:
LwM2M-CR-012-C-M: Support of Object Versioning in the Object and Object Instances parameter list (Section 5.3.1)

Per the LwM2M tech specification if an object only has 1 version then the version doesn't need to be specified.  And if an object is part of the LwM2M enabler specification then it doesn't need to be specified.  However, objects defined outside of the LwM2M enabler (read as IPSO Temp / Light Control objects) *DO* need to support a version parameter when the object has more than 1 version.

Example Registration of imaginary object 44 w/ a version 2.2:
LwM2M Client “Register” operation: ep=nodename,</1/0>,</1/1>,</3/0>,</44>;ver= “2.2”,</44/0>

As far as I know, all of the objects which are present in Zephyr use the initial (1.0) version, but the client should support the version parameter if configured.

**Comment by dleach02** [comment]
Moving to 2.2

**Comment by jukkar** [comment]
@rlubos is this still valid?

**Comment by rlubos** [comment]
Not implemented yet.
