### ISSUE TITLE
twister: Add option to print boards id along tests results

### ISSUE THREAD

**Issue by PerMac** [zephyrproject-rtos/zephyr#60673]
**Is your enhancement proposal related to a problem? Please describe.**
We run tests on board farms with multiple hw instances of the same zephyr's platform (e.g. 3x board_x, 3x board_y, 4x board_z, ...) to speedup execution by parallelization. Twister supports this with hw map feature. However, when printing results, twister only states which platform it was (e.g. board_x test_A falied). It is not possible to figure out if failures can be related to a certain hw. E.g. one will see that several tests failed on board_x, and starts looking for issues with tests, whereas it was issue with a single dk (certain id). 

**Describe the solution you'd like**
A flag `--show-hw-id` is added. If so, an id of a board is printed next to it's name, when tests' statuses are printed. In addition, this id will be stored in test reports. 

**Describe alternatives you've considered**
This is available by default when hw maps ar used.

**Comment by carlescufi** [comment]
Fixed by https://github.com/zephyrproject-rtos/zephyr/pull/61623
