### ISSUE TITLE
system crashs when optimization level is optimize nothing(-O0)

### ISSUE THREAD

**Issue by Jan9401** [zephyrproject-rtos/zephyr#60719]
I used stm32f746g-disco evb board, when I enable Level optimize option to O0, system can enter in fatal immediately, I am not familiar with zephyr kernel,So I can't solve this problem.  Thanks .

**Comment by nordicjm** [comment]
This is likely because you have not increased the stack sizes, no optimisation means more RAM is needed, closing.
