### ISSUE TITLE
cdc_acm sample fails for board 'adafruit_feather_m0_basic_proto', node zephyr_udc0 missing

### ISSUE THREAD

**Issue by aeckstein** [zephyrproject-rtos/zephyr#60715]
Host OS: Linux (amd64)
Environment version: git latest, c094bd
Target: adafruit_feather_m0_basic_proto
Sample: cdc_acm
Problem: build error (full build log attached)

I've followed 'Getting started', and successfully built and flashed the 'blink' sample. Switching to cdc_acm, and executing

$ west build -b adafruit_feather_m0_basic_proto samples/subsys/usb/cdc_acm --build-dir ~/tmp/cdc_acm/

I encountered the error

-- Found devicetree overlay: /home/devuser/zephyrproject/zephyr/samples/subsys/usb/cdc_acm/app.overlay
devicetree error: /home/devuser/zephyrproject/zephyr/samples/subsys/usb/cdc_acm/app.overlay:7 (column 1): parse error: undefined node label 'zephyr_udc0'

From information gleaned from adafruit_trinket_m0.dts, I simply added the section 
```
zephyr_udc0: &usb0 {
        status = "okay";

        pinctrl-0 = <&usb_dc_default>;
        pinctrl-names = "default";
};
```
to adafruit_feather_m0_basic_proto.dts, and cdc_acm built and worked fine (patch attached). If that was the right thing to do, can somebody upstream it please? Thanks!
[adafruit_feather_m0_basic_proto.cdc_acm.error.txt](https://github.com/zephyrproject-rtos/zephyr/files/12137361/adafruit_feather_m0_basic_proto.cdc_acm.error.txt)
[adafruit_feather_m0_basic_proto.dts.patch.gz](https://github.com/zephyrproject-rtos/zephyr/files/12137364/adafruit_feather_m0_basic_proto.dts.patch.gz)

**Comment by nordicjm** [comment]
Please port a PR with the fixes, we do not accept patch files.
