### ISSUE TITLE
RTIO: Update dead dependencies to RTIO simple executor

### ISSUE THREAD

**Issue by kmeinhar** [zephyrproject-rtos/zephyr#60730]
**Is your enhancement proposal related to a problem? Please describe.**

There are still references in code and documentation to RTIO simple executor.
These were removed with PR #57436

**Describe the solution you'd like**

Find and remove all references similar to the following:
* https://github.com/zephyrproject-rtos/zephyr/blob/main/drivers/i2c/i2c_sam_twihs_rtio.c#L425
* https://github.com/zephyrproject-rtos/zephyr/blob/main/doc/services/rtio/index.rst?plain=1#L150

```[tasklist]
### Tasks
- [ ] Remove https://github.com/zephyrproject-rtos/zephyr/blob/main/drivers/i2c/i2c_sam_twihs_rtio.c#L425
- [ ] Remove https://github.com/zephyrproject-rtos/zephyr/blob/main/doc/services/rtio/index.rst?plain=1#L150
```

**Comment by kmeinhar** [comment]
@teburd Am I correct that in the assumption that `RTIO_EXECUTOR_SIMPLE_DEFINE` was replaced with `RTIO_DEFINE`?

**Comment by teburd** [comment]
@kmeinhar In effect yes, there were two executors with different memory footprints at one point. There is only one now with a very low footprint. Thanks for finding these, will send a patch up.
