### ISSUE TITLE
posix: implement pthread_yield()

### ISSUE THREAD

**Issue by cfriedt** [zephyrproject-rtos/zephyr#60757]
There are currently 20 missing POSIX functions with trivial implementations, `pthread_yield()` is one of them.

See https://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_yield.html

See RFC #51211 for more info.

**Comment by kartben** [comment]
> See https://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_yield.html

FWIW this leads to a 404 for me

**Comment by cfriedt** [comment]
Boo yeah, maybe don't implement the deprecated interfaces :(
