### ISSUE TITLE
MPU region error on nRF52833

### ISSUE THREAD

**Issue by vmsh0** [zephyrproject-rtos/zephyr#60788]
**Describe the bug**

I'm benchmarking a cryptographic library on a nRF52833-based dev board (DWM3001CDK). In certain situations which I have not isolated, the following error prints repeatedly, while the benchmark still successfully completes:

> E: Failed to allocate new MPU region 20

I do not think the application puts the platform under any memory pressure:

```
Memory region         Used Size  Region Size  %age Used
           FLASH:      155196 B       512 KB     29.60%
             RAM:       18608 B       128 KB     14.20%
        IDT_LIST:          0 GB         2 KB      0.00%
```

While some dynamic allocation is performed, the expected total allocated RAM from dynamic allocation is under a few KB -- and at any rate, no dynamic allocations fail during the benchmarks.

 - **What have you tried to diagnose or workaround this issue?** Nothing much, disabling MPU support obviously avoids the printouts
 - **Is this a regression? If yes, have you been able to "git bisect" it to a specific commit?** I have not tried this yet; please advise on whether it might be useful

**To Reproduce**
Should I upload a small-as-possible example here? It's going to be relatively big nonetheless, as it includes an entire cryptographic library

**Expected behavior**
No printouts

**Impact**
Apparently, just an annoyance. However, I would like to fully understand the implications of that printout. Particularly, it seems conceivable to me that I'm just missing out on a security feature, while the program still runs correctly

**Logs and console output**
![image](https://github.com/zephyrproject-rtos/zephyr/assets/1955497/09dd90c0-d735-4e49-87a5-67f25de51eed)

**Environment (please complete the following information):**
Linux / Zephyr SDK / 8512bd18c66699046dffb7da0b02d72301fe8e5b

**Additional context**

```
CONFIG_NEWLIB_LIBC=y

CONFIG_TIMING_FUNCTIONS=y
CONFIG_SERIAL=y
CONFIG_UART_INTERRUPT_DRIVEN=y
CONFIG_CONSOLE=y
CONFIG_RTT_CONSOLE=y
CONFIG_USE_SEGGER_RTT=y
CONFIG_UART_CONSOLE=y
CONFIG_LOG=y
CONFIG_LOG_MODE_MINIMAL=y
CONFIG_EVENTS=y
CONFIG_FLASH=y
CONFIG_FLASH_MAP=y
CONFIG_NVS=y

CONFIG_MAIN_STACK_SIZE=4096

CONFIG_ENTROPY_GENERATOR=y
CONFIG_ENTROPY_INIT_PRIORITY=50
CONFIG_ENTROPY_NRF5_RNG=y
CONFIG_ENTROPY_NRF5_THR_POOL_SIZE=8
CONFIG_ENTROPY_NRF5_THR_THRESHOLD=4
CONFIG_ENTROPY_NRF5_ISR_POOL_SIZE=16
CONFIG_ENTROPY_NRF5_ISR_THRESHOLD=12
CONFIG_ENTROPY_DEVICE_RANDOM_GENERATOR=y
CONFIG_HARDWARE_DEVICE_CS_GENERATOR=y
```

**Comment by carlocaione** [comment]
@vmsh0 can you check if you still get the same when using https://github.com/zephyrproject-rtos/zephyr/pull/60780 ?
