### ISSUE TITLE
api: pinmux/gpio: It isn't possible to set pins as input and output simultaneously

### ISSUE THREAD

**Issue by iha** [zephyrproject-rtos/zephyr#6084]
To configure the pins to be used in an i2c driver I had to do a workaround (https://github.com/zephyrproject-rtos/zephyr/pull/5850) so that the input was always enabled. Because the PINMUX and GPIO APIs don't allow the pins to be input and output simultaneously.

This issue is related to https://github.com/zephyrproject-rtos/zephyr/issues/5697

**Comment by mnkp** [comment]
Is fixed by #16648 (not yet on master).

**Comment by mnkp** [comment]
#16648 was merged to master. It is possible now to configure pin as input/output.
