### ISSUE TITLE
Bluetooth: audio: csip: Provide the service context of CSIS instance

### ISSUE THREAD

**Issue by MariuszSkamra** [zephyrproject-rtos/zephyr#60860]
**Is your enhancement proposal related to a problem? Please describe.**
Currently, the CSIP API does not provide the context of the CSIS instance that can be included by other service.
As there might be multiple instances of CSIS on the server, each instance shall be included by other service.
The remote GATT Database might look like:
Coordinated Set Identification Service (1st instance)
Coordinated Set Identification Service (2nd instance)
Common Audio Service (includes 2nd CSIS)
Battery Service (includes 1st CSIS)

Meaning that the device is in 2 sets: Audio Set and Battery Set.
The `struct bt_csip_set_coordinator_cb.discover` callback provides information about CSIS instances found:
```
typedef void (*bt_csip_set_coordinator_discover_cb)(
	struct bt_conn *conn,
	const struct bt_csip_set_coordinator_set_member *member,
	int err, size_t set_count);
```
where:
```
struct bt_csip_set_coordinator_set_info {
	uint8_t set_sirk[BT_CSIP_SET_SIRK_SIZE];
	uint8_t set_size;
	uint8_t rank;
	bool lockable;
};

struct bt_csip_set_coordinator_csis_inst {
	struct bt_csip_set_coordinator_set_info info;
	void *svc_inst;
};

struct bt_csip_set_coordinator_set_member {
	struct bt_csip_set_coordinator_csis_inst insts[BT_CSIP_SET_COORDINATOR_MAX_CSIS_INSTANCES];
};
```

As shown, there is no service context given, thus the information about `insts` found is unusable e.g. in the context of audio operations because one does not know which `inst` to refer.

**Describe the solution you'd like**
I was thinking of changing
```
int bt_csip_set_coordinator_discover(struct bt_conn *conn);
```
to
``` 
int bt_csip_set_coordinator_discover(struct bt_conn *conn, const struct bt_uuid *uuid);
```
so that the `discover` callback would return the CSIS instance that is used in the context of service with `uuid`, but as there might be multiple instances of the service with given `uuid` maybe additional `service_handle` parameter is needed.

I think that there is no point of discovering all of the instances as implementation might be interested in some specific CSIS only that can be used in the context on some service only.

**Comment by Thalley** [comment]
Closing due to lack of response and that I don't think this is necessary.
