### ISSUE TITLE
Contributor self-nomination for tristan-google

### ISSUE THREAD

**Issue by tristan-google** [zephyrproject-rtos/zephyr#60940]
# Background

The [TSC Project Roles] defines the main roles for the Zephyr Project, including
Maintainer, Collaborator, and Contributor.

By default anyone that contributes code or documentation is a Contributor, but
with the lowest [GitHub Permission Level] of Read. For example, Contributors
with Read permission do not have the permission to add reviewers to a pull
request.

Use this template to nominate a GitHub user for the Contributor role with
Triage permission level, which allows the user to add reviewers to a pull
request and be added as a reviewer by other users.

# Nomination

## GitHub User

Provide the following information about the GitHub user:

1. Tristan Honscheid
1. tristan-google
1. Google

## Supporting Documents

Add links to 3-5 GitHub pull requests, in the Zephyr project, authored or
reviewed by the GitHub user that demonstrate the user's dedication to the
Zephyr project.

### Features
  * [Backend Sensor Emulator API](https://github.com/zephyrproject-rtos/zephyr/pull/60394)
  * [twister: Fields for Kconfig and DT overlay files in testcase.yaml](https://github.com/zephyrproject-rtos/zephyr/pull/52810)
  * [sensors: Create sensor trig subcommand](https://github.com/zephyrproject-rtos/zephyr/pull/58257)

### Recent bug fixes / cleanup
  * [tests: Clean up sensor driver build_all test](https://github.com/zephyrproject-rtos/zephyr/pull/60275)
  * [sensor: ism330dhcx: Incorrect handle passed to ctx struct in SPI mode](https://github.com/zephyrproject-rtos/zephyr/pull/60119)
  * [emul: spi: SPI_EMUL_INIT(n) hard-coded to instance #0](https://github.com/zephyrproject-rtos/zephyr/pull/60118)

[See full PR list here](https://github.com/zephyrproject-rtos/zephyr/pulls?q=is%3Apr+author%3Atristan-google)

[TSC Project Roles]: <https://docs.zephyrproject.org/latest/project/project_roles.html>
[GitHub Permission Level]: <https://docs.github.com/en/organizations/managing-access-to-your-organizations-repositories/repository-roles-for-an-organization>

**Comment by nashif** [comment]
https://github.com/zephyrproject-rtos/zephyr/invitations
