### ISSUE TITLE
tests: thrift: binaryProtocol test still failing in CI

### ISSUE THREAD

**Issue by cfriedt** [zephyrproject-rtos/zephyr#60941]
**Describe the bug**
Thrift has a few timing-related issues left over, it seems on x86_64. Due to an unrelated twister issue, they were failing silently.

Please also mention any information which could help others to understand
the problem you're facing:
 - What target platform are you using? `qemu_x86_64`
 - What have you tried to diagnose or workaround this issue? manual stress tests
[run-thrift-trials.sh.txt](https://github.com/zephyrproject-rtos/zephyr/files/12201792/run-thrift-trials.sh.txt)
 - Is this a regression? If yes, have you been able to "git bisect" it to a
   specific commit? Unknown at this time
 - ...

**To Reproduce**
* `twister -i -p qemu_x86_64 -T tests/lib/thrift/ThriftTest`
* `./run-thrift-trials.sh`

**Expected behavior**
It should work to a reasonable degree of 9's.

**Impact**
It was holding up CI today

**Logs and console output**
```
INFO    - 214/617 qemu_x86_64               tests/lib/thrift/ThriftTest/thrift.ThriftTest.newlib.binaryProtocol  FAILED unexpected eof (qemu 0.652s)
INFO    - /__w/zephyr/zephyr/twister-out/qemu_x86_64/tests/lib/thrift/ThriftTest/thrift.ThriftTest.newlib.binaryProtocol/handler.log
ERROR   - SeaBIOS (version zephyr-v1.0.0-0-g31d4e0e-dirty-20200714_234759-fv-az50-zephyr)
Booting from ROM..
*** Booting Zephyr OS build zephyr-v3.4.0-1746-g87a836c2f900 ***
Running TESTSUITE thrift
===================================================================
...

 PASS - test_list in 0.014 seconds
===================================================================
START - test_map
testMap({0 => -10, 1 => -9, 2 => -8, 3 => -7, 4 => -6})

E: failed to poll fds 4, 5: 1
abort()
E: RAX: 0x0000000000000004 RBX: 0x0000000000704e80 RCX: 0x0000000000000001 RDX: 0x0000000000000001
E: RSI: 0x00000000000003f8 RDI: 0x00000000001c8190 RBP: 0x00000000001cbb30 RSP: 0x00000000001cbb30
E:  R8: 0x0000000000000000  R9: 0x00000000001a17c2 R10: 0x00000000001cb6b0 R11: 0x000000000000000b
E: R12: 0x00000000001f47b0 R13: 0x00000000006fd910 R14: 0x00000000001cbc8f R15: 0x00000000001cbd38
E: RSP: 0x00000000001cbb30 RFLAGS: 0x0000000000000203 CS: 0x0018 CR3: 0x00000000001fb000
E: RIP: 0x000000000016e195
E: >>> ZEPHYR FATAL ERROR 4: Kernel panic on CPU 1
E: Current thread: 0x1c11a0 (unknown)
E: Halting system

INFO    - /__w/zephyr/zephyr/twister-out/qemu_x86_64/tests/lib/thrift/ThriftTest/thrift.ThriftTest.newlib.binaryProtocol/handler.log
INFO    - 215/617 qemu_x86_64               tests/drivers/can/api/drivers.can.api              SKIPPED (runtime filter)
```

**Environment (please complete the following information):**
 - OS: (e.g. Linux, MacOS, Windows) Linux
 - Toolchain (e.g Zephyr SDK, ...): Zephyr SDK 0.16.1
 - Commit SHA or Version used: 488fd89e2bd64c60354378fdec33b7e65c713d38

**Additional context**

**Comment by de-nordic** [comment]
Sorry for setting the backports, wrong issue.
