### ISSUE TITLE
stm32h7 tests: spi_loopback fails due to mem_region 

### ISSUE THREAD

**Issue by FRASTM** [zephyrproject-rtos/zephyr#60977]
**Describe the bug**
The tescase tests/drivers/spi/spi_loopback/  now fails when ruuning on a stm32h7 target

After the merge of https://github.com/zephyrproject-rtos/zephyr/pull/57786
There is a mem region definition missing to PASS the testcase

**To Reproduce**
1. west build -p auto -b nucleo_h753zi tests/drivers/spi/spi_loopback/
2. west flash
3. connect D11 <--> D12 on the nucleo 144 target board

**Expected behavior**
test PASSED
```
PASS - test_spi_loopback in 0.049 seconds
===================================================================
TESTSUITE spi_loopback succeeded

------ TESTSUITE SUMMARY START ------

SUITE PASS - 100.00% [spi_loopback]: pass = 1, fail = 0, skip = 0, total = 1 dus
 - PASS - [spi_loopback.test_spi_loopback] duration = 0.049 seconds

------ TESTSUITE SUMMARY END -----
```

**Impact**
CI failure

**Logs and console output**
```
*** Booting Zephyr OS build zephyr-v3.4.0-1785-gdfeb2d902756 ***                
Running TESTSUITE spi_loopback                                                  
===================================================================             
START - test_spi_loopback                                                       
I: SPI test on buffers TX/RX 0x240001b5/0x240009ce                              
I: SPI test slow config                                                         
I: Start complete multiple                                                      
E: Code -14                                                                     

    Assertion failed at WEST_TOPDIR/zephyr/tests/drivers/spi/spi_loopback/src/spi.c:111: spi_complete_multiple: (ret is true)
SPI transceive failed                                                                                                                                                                              
 FAIL - test_spi_loopback in 0.024 seconds                                      
===================================================================             
TESTSUITE spi_loopback failed.  
```                                                

**Environment (please complete the following information):**
 - OS: Ubuntu
 - Toolchain  0.16.1
 - Commit SHA : dfeb2d902756863c7bb1ae47c0996be678669f20

**Comment by FRASTM** [comment]
@dgastonochoa what would be a right definition to prepare a spi buffers in no cache region ?

**Comment by dgastonochoa** [comment]
> @dgastonochoa what would be a right definition to prepare a spi buffer in no cache region ?

Hi @FRASTM ,

First, enable a memory region that DMA can access and set it as NOCACHE, e.g.:
```
&sram2 {
	status = "okay";
	zephyr,memory-region-mpu = "RAM_NOCACHE";
};
```
Then, declare a buffer in that region, e.g.:
```
#define NOCACHE_SECTION __attribute__((section("SRAM2")))
#define ALIGNED __attribute__((aligned(32)))
...
static uint32_t s_buf[32] NOCACHE_SECTION ALIGNED;
```
Finally, you can use it normally:
```
    s_buf[0] = 0xaaaaaaaa;
    s_buf[1] = 0x55555555;
    struct spi_buf tx_buf = {
        .buf = s_buf, .len = 8,
    };
    struct spi_buf_set tx_bufs = { .buffers = &tx_buf, .count = 1 };


    int rc = spi_write(spi1, &cfg, &tx_bufs);
```
You can see a complete example in https://github.com/zephyrproject-rtos/zephyr/pull/57786#issuecomment-1549500051, see "How to test" section.
 
Regards.

**Comment by dgastonochoa** [comment]
I have tried to reproduce the error as explained in the description but I get a build failure. However, I can build and run the same test for h743.

**Comment by FRASTM** [comment]
That does not seem sufficient, the `SPI test on buffers TX/RX 0x24000260/0x24000240 `

**Comment by dgastonochoa** [comment]
> That does not seem sufficient, the `SPI test on buffers TX/RX 0x24000260/0x24000240 ` --> not SRAM2 area

I think I see the problem. The buffers in this test are declared as `__attribute__((__section__(".nocache")));`. That puts them in a nocache memory area (sram0) but that is not declared as so in devicetree. Because of this, even them being in a nocache region, the STM32 SPI driver does not recognize them as so. 

As a quick solution for the tests, I would set sram2 as nocache in the required devicetree files and then declare the buffers to be in this region, in other words, replace this
```
static __aligned(32) char buffer_tx[BUF_SIZE] __used __attribute__((__section__(".nocache")));
```
by this
```
static __aligned(32) char buffer_tx[BUF_SIZE] __used ALIGNED NOCACHE_REGION
```
and so on for the rest of the buffers. Also, `sram0` could be made `"zephyr,memory-region"` in  `stm32h743.dtsi`, and then mark it as nocache in devicetree. Although I imagine if it is not `"zephyr,memory-region"` yet, it is for a reason.

As I see it, the problem is that `sram0` is not marked as `nocache` in devicetree, but it ends app being so by a different mechanism, or more in general, there are 2 different mechanisms to achieve a nocache area and they can clash. One solution would be to abandon the `__attribute__((__section__(".nocache")));` mechanism in favor the devicetree mechanism, so there are no room for contradictions. However, I understand this breaks backwards compatibility. Then, the STM32 SPI driver should check if the region is nocache regardless of what devicetree says but I'm not sure how to do this.

**Comment by FRASTM** [comment]
I have a branch https://github.com/FRASTM/zephyr/tree/issue60977 for testing on the nucleo_h753zi
(should also add the following to the the prj.conf when building $ west build -p auto -b nucleo_h753zi tests/drivers/spi/spi_loopback/) : 
```
CONFIG_SPI_STM32_DMA=y
CONFIG_SPI_STM32_INTERRUPT=n
CONFIG_SPI_ASYNC=n
CONFIG_NOCACHE_MEMORY=y
```

**Comment by dgastonochoa** [comment]
I have tried that branch and still don't see any reference to h753 in `tests/spi/spi_loopback`.

**Comment by FRASTM** [comment]
Adding the 
```
&sram2 {
	zephyr,memory-attr = "RAM_NOCACHE";
};
```

to the overlay file for that board tests/drivers/spi/spi_loopback/boards/nucleo_h753zi.overlay
will improve the test result:
```
START - test_spi_loopback
I: SPI test on buffers TX/RX 0x300200a0/0x30020080
I: SPI test slow config
I: Start complete multiple
I: Passed
I: Start complete loop
I: Passed
I: Start null tx
E: Code -14

    Assertion failed at WEST_TOPDIR/zephyr/tests/drivers/spi/spi_loopback/src/spi.c:230: spi_null_tx_buf: (ret is true)
SPI transceive failed

```

**Comment by FRASTM** [comment]
> I have tried that branch and still don't see any reference to h753 in `tests/spi/spi_loopback`.

Use the existing https://github.com/zephyrproject-rtos/zephyr/tree/main/tests/drivers/spi/spi_loopback

**Comment by dgastonochoa** [comment]
> Use the existing https://github.com/zephyrproject-rtos/zephyr/tree/main/tests/drivers/spi/spi_loopback

Not sure what do you mean, I have checked out your branch and executed the command you provided above and the still the tests don't build. I still cannot find references to h7 so it seems to me the tests don't exist in this branch.

With regards to the test that fails:

The test that keeps failing says:
```
/* According to documentation, when sending NULL tx buf -
		 *  NOP frames should be sent on MOSI line
		 */
```
To achieve this, the `if ((tx_bufs != NULL && !spi_buf_set_in_nocache(tx_bufs))` statement needs to be modified to account for the fact that, if `tx_bufs` contains one buffer and it is NULL, it should not return error. So replace this
```
if ((tx_bufs != NULL && !spi_buf_set_in_nocache(tx_bufs))
```
by
```
static bool is_null_buffer(const struct spi_buf_set *tx_bufs)
{
   return (tx_bufs.count >=1 && tx_bufs.buffers[0].buf == NULL;
}

if ((tx_bufs != NULL && !is_null_buffer(tx_bufs) && !spi_buf_set_in_nocache(tx_bufs))
```
Or something similar.

**Comment by dgastonochoa** [comment]
> Use the existing https://github.com/zephyrproject-rtos/zephyr/tree/main/tests/drivers/spi/spi_loopback

Nevermind, I needed to pull.

**Comment by dgastonochoa** [comment]
> also check the tx_bufs->buf and/or the tx_bufs->len ?

I think https://github.com/zephyrproject-rtos/zephyr/issues/60977#issuecomment-1658605836 answers this, doesn't it? Also, the provided patch fixes this problem.

**Comment by FRASTM** [comment]
> 

Yes, it is. I am currently preparing the PR. thank for your support

**Comment by FRASTM** [comment]
fixed by the https://github.com/zephyrproject-rtos/zephyr/pull/61265
