### ISSUE TITLE
Watchdog fires during task_wdt_add()

### ISSUE THREAD

**Issue by dpkristensen** [zephyrproject-rtos/zephyr#61004]
The task watchdog will fire while the calling thread is in the middle of the task_wdt_add() function.

**To Reproduce**

Build Zephyr, add preemptible thread that only activates the watchdog while the thread is active.

**Expected behavior**
Watchdog does not fire before timeout.

**Impact**
Critical bug - watchdog must be reliable.

**Logs and console output**
N/A - See stack information in description.

**Environment (please complete the following information):**
 - OS: Windows 11
 - Hardware: nRF52840 DK board
 - Toolchain: nRF Connect SDK v2.2.0
 - Zephyr: Tag v3.2.99-ncs1

**Additional context**
I captured the condition in a debugger and this is what's happening at the point of failure.

 	for (int id = 0; id < ARRAY_SIZE(channels); id++) {
		if (channels[id].reload_period == 0) {
			channels[id].reload_period = reload_period;
			channels[id].user_data = user_data;
			channels[id].timeout_abs_ticks = K_TICKS_FOREVER;
			channels[id].callback = callback;

			####<<<< TASK PC IS HERE >>>>####
			if (!hw_wdt_started && hw_wdt_dev) {
				/* also start fallback hw wdt *

The "expiration" happens because reload_period has been set to a non-zero value and wdt_feed() has not yet occurred.

	if (bg_channel || channels[channel_id].reload_period == 0) {
		schedule_next_timeout(sys_clock_tick_get());
		return;
	}

	if (channels[channel_id].callback) {
		####<<<< SYSWORKQ PC IS HERE >>>>####
		channels[channel_id].callback(channel_id,
			channels[channel_id].user_data);
	} else {

It should be noted that the task calling task_wdt_add() uses *preemptible* priority, whereas the sysworkq and timer threads are *cooperative*.  There are no synchronization primitives being used in task_wdt to guard against timer expiration between the reload value becoming non-zero and the initial feeding of the watchdog (added in #39523).

The use case behind this is having a watchdog that is only active when the task is not sleeping.  task_wdt does not support suspending a watchdog after being added, so the main loop executes code like this:

    // Start of (preemptible) thread loop
    int wd_id = task_wdt_add(5000, my_watchdog_handler, k_current_get());
    // Do stuff with watchdog active...
    task_wdt_delete(wd_id);
    // End of thread loop

**Comment by martinjaeger** [comment]
Thanks @dpkristensen for reporting the bug.

I'm not quite sure if I fully understand the circumstances where this race condition happens. Do you have a complete example to reproduce the issue that you could push to a git repo somewhere? I've got a nRF52840 DK which I could use to test.

And do you think another `k_sched_lock()` in the `task_wdt_add()` function would do the trick?

> The "expiration" happens because reload_period has been set to a non-zero value (-1 in this case) and wdt_feed() has not yet occurred.

How can `reload_period` be set to `-1`? It is a `uint32_t`.

**Comment by dpkristensen** [comment]
WRT your other question:

> And do you think another k_sched_lock() in the task_wdt_add() function would do the trick?

Yes, it should fix it too; my solution with the boolean may not be ideal, just offering it up since it did work for me on this MCU.
