### ISSUE TITLE
Bluetooth: Host: identity resolution causes CCC issues on other connections with the same peer

### ISSUE THREAD

**Issue by kapi-no** [zephyrproject-rtos/zephyr#61028]
**Describe the bug**

The bug assumes that the application uses `CONFIG_BT_PRIVACY` and `CONFIG_BT_SMP` configurations. It also assumes that the application exchanges the Identity Address with the connected peer during the pairing phase.

When the Bluetooth GATT layer (`gatt.c`) gets notified about the identity resolution in the `bt_gatt_identity_resolved` function during the bonding phase for one Bluetooth identity, it converts the BLE address field (called `peer`) in all affected CCC descriptors from RPA into the Identity address:

```
for (size_t i = 0; i < ARRAY_SIZE(ccc->cfg); i++) {
	if (bt_addr_le_eq(&ccc->cfg[i].peer, match->private_addr)) {
		bt_addr_le_copy(&ccc->cfg[i].peer, match->id_addr);
	}
}
```
If another connection object associated with the second identity is connected simultaneously with the same peer, its peer destination address (`conn->le.dst`) is not converted from RPA into an Identity address. Once the second identity attempts to send a GATT notification or indication, it fails in the `bt_gatt_is_subscribed` function as the stack cannot find the CCC descriptor using the RPA address from the `conn->le.dst` field. The failure happens because of the conversion of the BLE address field in the CCC descriptor that was performed during the bonding phase on the first identity.

**To Reproduce**
1. Create the Bluetooth sample with two Bluetooth identities and two advertising sets with the Privacy feature enabled.
2. Connect to the second identity and subscribe to any characteristic.
3. Connect to the first identity while maintaining the connection with the second identity using the same central device (with the same peer address) as the one used to connect to the first identity (e.g. the same smartphone).
4. Complete the pairing and bonding procedure with the first identity.
5. Observe that GATT notifications or indications fail to be sent on the second identity. 

**Expected behavior**

The identity resolution on one connection should not impact the CCC configuration on the second (parallel connections) even if you maintain two different connections with the same peer.

**Impact**

The Bluetooth stack fails to send GATT notifications or indications on other connection objects associated with the same peer address than the one on which the identity resolution and the pairing happened.

**Environment (please complete the following information):**
 - OS: Linux
 - Commit SHA: the main branch (https://github.com/zephyrproject-rtos/zephyr/commit/f16c4324a7e28c929f7226dd06fef87d951431c9)

**Comment by jori-nordic** [comment]
You might be able to work around that bug by unsetting `CONFIG_BT_GATT_ENFORCE_SUBSCRIPTION`
