### ISSUE TITLE
tinycrypt tests build failed

### ISSUE THREAD

**Issue by snowuyl** [zephyrproject-rtos/zephyr#61053]
D:\ncs\v2.4.0>cd D:\ncs\v2.4.0\bootloader\mcuboot\ext\tinycrypt\tests

D:\ncs\v2.4.0\bootloader\mcuboot\ext\tinycrypt\tests>ls
include                 test_cbc_mode.c   test_ctr_prng.c   test_hmac.c
Makefile                test_ccm_mode.c   test_ecc_dh.c     test_hmac_prng.c
pseudo-random-data.bin  test_cmac_mode.c  test_ecc_dsa.c    test_sha256.c
test_aes.c              test_ctr_mode.c   test_ecc_utils.c

D:\ncs\v2.4.0\bootloader\mcuboot\ext\tinycrypt\tests>make
gcc -Os -std=c99 -Wall -Wextra -D_ISOC99_SOURCE -MMD -I../lib/include/ -I../lib/source/ -I../tests/include/ -DENABLE_TESTS   -c -o test_aes.o test_aes.c
process_begin: CreateProcess(NULL, gcc -Os -std=c99 -Wall -Wextra -D_ISOC99_SOURCE -MMD -I../lib/include/ -I../lib/source/ -I../tests/include/ -DENABLE_TESTS -c -o test_aes.o test_aes.c, ...) failed.
make (e=2): 系統找不到指定的檔案。
make: *** [test_aes.o] Error 2

**Comment by nordicjm** [comment]
1. Not enough information provided, not using template
2. Not using zephyr, using NCS
3. NCS bugs get reported to https://devzone.nordicsemi.com/ unless you can replicate the issue in zephyr itself i.e. not zephyr as part of NCS
