### ISSUE TITLE
uvc_stream and lovyangfx librarys  file synchronized error in main.cpp file 

### ISSUE THREAD

**Issue by Nadeemranm** [zephyrproject-rtos/zephyr#61062]
C:/Users/Guest-08/Downloads/esp-iot-solution-usb-add_usb_solutions/examples/usb/host/usb_camera_lcd_display/main/main.cpp:281:5: error: designator order for field 'uvc_config::frame_index' does not match declaration order in 'uvc_config_t' {aka 'uvc_config'}
cc1plus.exe: some warnings being treated as errors
What is this error !!
plz help me

**Comment by nordicjm** [comment]
I don't see how this relates to zephyr in any way, if you are having an issue with an espressif SDK then please contact espressif.
