### ISSUE TITLE
Sample STM32PM Blinky higher energy usage on nucleo_wb55rg since adding prescaler for lptim1

### ISSUE THREAD

**Issue by jbr-ia** [zephyrproject-rtos/zephyr#61099]
**Describe the bug**
When running the sample stm32 power_mgmt blinky (zephyr/samples/boards/stm32/power_mgmt/blinky/) on the nucleo_wb55rg board, the microcontroller seems to wake up from sleep every 2 ms. This causes higher energy-usage than expected (on average between 600 and 700 uA when the LED is off).
With an older version of zephyr (before commit 29ef82cfaf02a6171eb85462bda73d11e7bd84bf), the microcontroller did not wake up so frequently, and the current was a about 100 to 130 uA with the LED off. 

My assumption is that is has to do with the prescaler which is set to 32 in the overlay for the nucleo_wb55rg. This results in 1024 ticks per second, but the default CONFIG_SYS_CLOCK_TICKS_PER_SEC is at 4096.
When I set the prescaler to 8 in nucleo_wb55rg.overlay, or the CONFIG_SYS_CLOCK_TICKS_PER_SEC to 1024 in prj.conf, the microcontroller does not wake up that often, and the energy-usage is about the same as before commit 29ef82cfaf02a6171eb85462bda73d11e7bd84bf. Each of these changes (changing prescaler, or changing  CONFIG_SYS_CLOCK_TICKS_PER_SEC) can solve the problem, but I don't know the root cause of the problem, and do not know if this is the desired solution.

**To Reproduce**
build the example:
west build -b nucleo_wb55rg samples/boards/stm32/power_mgmt/blinky

flash it to the microcontroller
west flash

Analyse the energy-consumption

**Expected behavior**
I expect the microcontroller to be sleeping for longer periods of time than 2 ms

**Impact**
Higher enenergy-consumption than expected

**Logs and console output**
Current with sample:
![afbeelding](https://github.com/zephyrproject-rtos/zephyr/assets/141256366/44768713-e1b6-4306-8c2c-dfca12b40559)

Detail of current with peak every 2 ms:
![afbeelding](https://github.com/zephyrproject-rtos/zephyr/assets/141256366/196a7389-0dac-4385-a43b-15211fceef1d)

Current with prescaler at 8:
![afbeelding](https://github.com/zephyrproject-rtos/zephyr/assets/141256366/064f4b91-774e-490d-93c7-36acac52a0af)

**Environment:**
 - OS: Linux
 - Toolchain: zephyr-sdk-0.16.1
 - Commit SHA or Version used: 0a2d538c2bc442e64b3b86f3cf05a311223466ac

**Additional context**
When the current is measured in the nucleo wb55rg, the jumpers for the STlink (JP5) are removed, the USB-cable disconnected, and voltage supplied via JP2.

**Comment by FRASTM** [comment]
Thanks for your deep and pertinent analysis. 
In case of nucleo_wb55rg, the LPTIM prescaler was arbitrary set to 32 to have a large timeout period (several seconds).
The prescaler value is set in the  overlay file to be adjusted depending on the application. So that you can easily set the prescaler to 8 for your need.

**Comment by jbr-ia** [comment]
Thanks a lot for the quick response. For now I will use a prescaler of 8 in my application.

**Comment by fabiobaltieri** [comment]
Hey, seems like this has been resolved, I'll close this one.

**Comment by FRASTM** [comment]
I do not see many diff on low power (zephyr v3.5.0.rc1) when LPTIM prescaler  = <32>;
![nucleo_wb55_lptim32_4s](https://github.com/zephyrproject-rtos/zephyr/assets/51417392/c18284d3-bba5-4ffd-ac1f-c356e8f4560b)
compared to prescaler = <8>;
![nucleo_wb55_lptim8_4s](https://github.com/zephyrproject-rtos/zephyr/assets/51417392/55d5abf5-f308-4c94-a90b-fcfbfe96316d)

**Comment by FRASTM** [comment]
We do see the correlation  between the lptim presecaler and the CONFIG_SYS_CLOCK_TICKS_PER_SEC
