### ISSUE TITLE
Add a tag to the python-devicetree

### ISSUE THREAD

**Issue by xiaoxiao997** [zephyrproject-rtos/zephyr#61155]
Hi, excuse me, since I need to use the Device tree conversion tool in zyphyr. Could you please add a new tag in the zephyrproject-rtos/python-devicetree directory for the conversion of devicetree dts in the latest zephyr?

**Comment by carlescufi** [comment]
> Hi, excuse me, since I need to use the Device tree conversion tool in zyphyr. Could you please add a new tag in the zephyrproject-rtos/python-devicetree directory for the conversion of devicetree dts in the latest zephyr?

Hi @xiaoxiao997, what kind of tag do you mean? a Git tag?

**Comment by xiaoxiao997** [comment]
yes，i want to a git tag,for zephyr/python-devicetree



---Original---
From: "Carles ***@***.***&gt;
Date: Fri, Aug 4, 2023 18:27 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [zephyrproject-rtos/zephyr] Add a tag to the python-devicetree(Issue #61155)




  
Hi, excuse me, since I need to use the Device tree conversion tool in zyphyr. Could you please add a new tag in the zephyrproject-rtos/python-devicetree directory for the conversion of devicetree dts in the latest zephyr?
  
Hi @xiaoxiao997, what kind of tag do you mean? a Git tag?

**Comment by mbolivar-ampere** [comment]
What sort of tagging policy are you asking for? The directory is part of the zephyr tree so any tagged zephyr release is also a tag of that directory.

**Comment by xiaoxiao997** [comment]
Hello, I just need this tag from the device tree. Could you please insert a tag only for the latest device tree?

**Comment by xiaoxiao997** [comment]
![image](https://github.com/zephyrproject-rtos/zephyr/assets/75780200/1a39b642-4f40-41e2-8764-a9e8c0bc1193)

**Comment by xiaoxiao997** [comment]
yes，I want to  the tag for https://github.com/zephyrproject-rtos/python-devicetree

**Comment by mbolivar-ampere** [comment]
> Is this being kept up to date with whatever is happening inside the zephyr tree?

It is not. It was an experiment and I think we do not need it. I think we can keep the package in the tree and deprecate this repository. Any comments from anyone else?

**Comment by nashif** [comment]
Yep, lets archive that repo.
