### ISSUE TITLE
Contributor nomination for knthm

### ISSUE THREAD

**Issue by ceolin** [zephyrproject-rtos/zephyr#61176]
# Background

The [TSC Project Roles] defines the main roles for the Zephyr Project, including
Maintainer, Collaborator, and Contributor.

By default anyone that contributes code or documentation is a Contributor, but
with the lowest [GitHub Permission Level] of Read. For example, Contributors
with Read permission do not have the permission to add reviewers to a pull
request.

Use this template to nominate a GitHub user for the Contributor role with
Triage permission level, which allows the user to add reviewers to a pull
request and be added as a reviewer by other users.

# Nomination

## GitHub User

Provide the following information about the GitHub user:

1. Full Name:  Kenneth J. Miller
1. GitHub username: knthm
1. Organization (optional)

## Supporting Documents

https://github.com/zephyrproject-rtos/zephyr/pull/56330
https://github.com/zephyrproject-rtos/zephyr/pull/56833
https://github.com/zephyrproject-rtos/zephyr/issues/59194
https://github.com/zephyrproject-rtos/zephyr/pull/59406
https://github.com/zephyrproject-rtos/zephyr/pull/60369
https://github.com/zephyrproject-rtos/zephyr/pull/60998

[TSC Project Roles]: <https://docs.zephyrproject.org/latest/project/project_roles.html>
[GitHub Permission Level]: <https://docs.github.com/en/organizations/managing-access-to-your-organizations-repositories/repository-roles-for-an-organization>

**Comment by nashif** [comment]
@knthm  check https://github.com/zephyrproject-rtos/zephyr/invitations
