### ISSUE TITLE
CMSIS RTOS V2 Queue - undefined reference to `k_calloc`

### ISSUE THREAD

**Issue by srkapil** [zephyrproject-rtos/zephyr#61196]
**Describe the bug**

We are using Zephyr's CMSIS RTOS v2. When building the project with no dynamic memory enabled (CONFIG_HEAP_MEM_POOL_SIZE defaulted to 0) and using msgq causes the following linking error:
`zephyr/subsys/portability/cmsis_rtos_v2/msgq.c:58: undefined reference to 'k_calloc'`.

`k_calloc` definition from Zephyr kernel's mempool.c, is only included if `CONFIG_HEAP_MEM_POOL_SIZE` is larger than 0.  In msgq's `osMessageQueueNew` function [line 58](https://github.com/zephyrproject-rtos/zephyr/blob/5c7c099891fd06284b32baa12c6de04a30d3b127/subsys/portability/cmsis_rtos_v2/msgq.c#L58C3-L58C3) , `k_calloc` is not surrounded by a `#ifdef CONFIG_HEAP_MEM_POOL_SIZE `. which causes the linking issue to show up.

**To Reproduce**
1. set CONFIG_HEAP_MEM_POOL_SIZE=0 in prj.conf
1. create a queue using cmsis-rtos v2 in main function
1. west build
1. Linking error

**Expected behavior**
No linking errors

**Impact**
Having to enable dynamic memory or provide a dummy k_calloc function to get around the issue.

**Logs and console output**

```bash
`zephyr/subsys/portability/cmsis_rtos_v2/msgq.c:58: undefined reference to 'k_calloc'
```
> Full log cannot be provided due to IP reasons.

**Environment:**
 - OS: Ubuntu 22.04
 - Toolchain : Zephyr SDK
 - Version: v3.3.0

**Comment by henrikbrixandersen** [comment]
Please use our bug template when reporting bugs. You need to edit this issue to include the information requested in https://github.com/zephyrproject-rtos/zephyr/blob/main/.github/ISSUE_TEMPLATE/001_bug_report.md
