### ISSUE TITLE
doc: unit tests documentation refers to non existing sample code

### ISSUE THREAD

**Issue by aescolar-ot** [zephyrproject-rtos/zephyr#6121]
http://docs.zephyrproject.org/subsystems/test/ztest.html#quick-start-unit-testing
Refers to samples/testing/unit/ which does not exist anymore:
bd989a79bae2791f7365325c16769442e26cab51

**Comment by nashif** [comment]
in all fairness, bug should be assigned to @jhedberg  who removed that code :)

**Comment by jhedberg** [comment]
Ah, there's still a left-over in the documentation. I removed the part that CI grumpy, but seems this part didn't cause any CI warnings.

**Comment by jhedberg** [comment]
Is it really so that the net_buf test was the only available unit test to make references to? It'd have been nicer to refer to some other test than remove the references complete.

**Comment by jhedberg** [comment]
Actually, this is exactly what I removed from the documentation. Perhaps we just need to wait for the online documentation to be regenerated?

**Comment by dbkinder** [comment]
FYI, docs are generated nightly about 11PM GMT

**Comment by aescolar-ot** [comment]
My bad => I close it
