### ISSUE TITLE
mgmt: mcumgr: add support for indications/notifications

### ISSUE THREAD

**Issue by kunoh** [zephyrproject-rtos/zephyr#61249]
**Is your feature request related to a problem? Please describe.**

The current implementation of the SMP only allows for handling requests coming from a client. The server side may want to inform the client about a time critical issue but would have to wait until a client poll for that specific request.

A device using the SMP server may go to error state and would therefore like to inform the client, by sending either a notification or indication, that it is in error state.

**Describe the solution you'd like**

Open up for an api a user can use to send notifications/indication through the SMP server.

**Comment by nordicjm** [comment]
Asynchronous responses are not supported and will not be supported due to issues noticed when testing it before whereby flash is stalled during a flash erase/program for an extended period of time and commands sent during that time (i.e. over UART) are corrupted.

**Comment by nordicjm** [comment]
Though as an alternative system, there is now MCUmgr client support in-tree with implementations for os_mgmt and img_mgmt so you could use that in an application, it can act as a server and respond to incoming queries and act as a client to asynchronously send commands to the other device (which would be in server mode)

**Comment by kunoh** [comment]
What about in a synchronous way where the SMP server will handle each (request/response, indication, notification) in a blocking way?

**Comment by nordicjm** [comment]
There would be nothing to do as that is already supported, MCUmgr client writes to characteristic with data, MCUmgr server processes command, then writes response back to client via characteristic write. Indication/notification isn't going to improve anything

**Comment by kunoh** [comment]
Okay, can the client and server co-exist?

**Comment by nordicjm** [comment]
Yes

**Comment by kunoh** [comment]
Cool, I will try to work out a solution using the smp client also, thank you :)
