### ISSUE TITLE
mgmt: mcumgr: improve custom payload types

### ISSUE THREAD

**Issue by kunoh** [zephyrproject-rtos/zephyr#61248]
**Is your enhancement proposal related to a problem? Please describe.**

The SMP Protocol allow users to add their own custom groups (user groups) after group 64, using any type of data as payload. Currently the implementation is tightly coupled with cbor and adds a start and end byte in the payload which happens outside of the users scope. The start byte indicates the cbor format used in the payload, and is not changeable from userspace.

As a user, I would like to add custom handlers that uses Protobuf as the payload format, but I would now have to ignore the 2 byte overhead start- and end byte as they are pointless to custom payload format.

**Describe the solution you'd like**

Extend the Major Types to allow users to add their own payload types, currently described in `c:struct:zcbor_major_type_t` and give the user access to set the start byte using the relevant payload type.

**Comment by nordicjm** [comment]
There was a previous PR about this before the transition to zcbor, it is worth looking at again. Though errors would still be reported in zcbor format.

**Comment by nordicjm** [comment]
https://github.com/zephyrproject-rtos/zephyr/pull/42611

**Comment by kunoh** [comment]
Thank you, will have a look :-)
