### ISSUE TITLE
Sensor vl53l1x fails on sensor_sample_fetch

### ISSUE THREAD

**Issue by boaks** [zephyrproject-rtos/zephyr#61283]
NCS 2.4.1 / zephyr 3.3.99

As far as could verify, this is an issue of [vl53l1.c](https://github.com/zephyrproject-rtos/zephyr/blob/main/drivers/sensor/vl53l1x/vl53l1.c) and occurs also with the current version of that file here in this repository.

If `sensor_sample_fetch` is called, `SENSOR_CHAN_ALL` is provided as channel. With that, the [check __ASSERT_NO_MSG(chan == SENSOR_CHAN_DISTANCE);](https://github.com/zephyrproject-rtos/zephyr/blob/main/drivers/sensor/vl53l1x/vl53l1.c#L310)  fails.

Currently only using `sensor_sample_fetch_chan(dev, SENSOR_CHAN_DISTANCE);` works.

I would enjoy it, if the general fetch could also be supported by extending the check to

```
__ASSERT_NO_MSG(chan == SENSOR_CHAN_DISTANCE || chan == SENSOR_CHAN_ALL);
```
 
(The function doesn't use the channel, only for that ASSERT.)

**Comment by MaureenHelm** [comment]
Fixed by #61620
