### ISSUE TITLE
usb_dc_ep_flush on nrfx does not flush the buffer

### ISSUE THREAD

**Issue by bmulder-innoseis** [zephyrproject-rtos/zephyr#61296]
**Describe the bug**
When I cancel a USB transfer (made with `usb_transfer(...)` followed by `usb_cancel_transfer(ep)`, the buffer remains full. The next time a host reads data from the USB, it will receive the last failed transfer before receiving anything new.

This should be solved by calling `usb_dc_ep_flush`, but on nrfx this does not have the correct effect and the data is not flushed.
As suggested by Johann F. on Discord, I tried to work around it by calling usb_dc_ep_disable() followed by usb_dc_ep_enable() instead of usb_dc_ep_flush, and this seems to solve my issue.

**To Reproduce**
Implement a custom usb class, and have it send data using the asynchronous `usb_transfer()` function.
Before the callback is raised, cancel the transfer using `usb_cancel_transfer` and try to flush the buffer using `usb_dc_ep_flush`.
Then, read data from the host, and you should receive the last buffered data (the next time a transfer is done).

**Expected behavior**
The last buffered data should be purged and never seen on the host.

**Impact**
Nuking the dc endpoint instead of graciously flushing it might have unwanted side-effects.

**Environment (please complete the following information):**
 - OS: Linux, some application using libusb
 - Zephyr version: 3.2.0

**Comment by tmon-nordic** [comment]
Not sure what you really want to achieve, but no matter what you do there will always be a race condition window in between application wanting to disarm endpoint and the host actually asking for data (issuing IN token).
