### ISSUE TITLE
STM32 b_u585i_iot02a, reading vrefint problem

### ISSUE THREAD

**Issue by JiiZR** [zephyrproject-rtos/zephyr#61368]
*
**Describe the bug**
I tried sample, samples\sensor\soc_voltage.

**To Reproduce**
1. west build -p auto -b b_u585i_iot02a samples\sensor\soc_voltage
2. west flash
3. see error

**Expected behavior**
Should vref_1 be around 1,2 V ? ADC1 channel 0.

**Impact**
Minor

**Logs and console output**

*** Booting Zephyr OS build zephyr-v3.4.0-2226-g4cbb9d8f5f46 ***
Sensor voltage[vref_1]: 13.20 V
Sensor voltage[vbat_4]: 3.32 V

**Environment (please complete the following information):**
 - OS:Windows
 - Toolchain Zephyr SDK, 0.16.1
 - latest codes from github

**Additional context**

**Comment by FRASTM** [comment]
The error comes form the VREF int calibration value which is 14bit and has to be converted to 12bit value when the ADC channel is measured on 12 bits.
