### ISSUE TITLE
Migrate "Process" project from classic to new

### ISSUE THREAD

**Issue by keith-zephyr** [zephyrproject-rtos/zephyr#61400]
All working groups should move away from using Github's classic projects. 

I don't have the necessary permissions to perform the [project migration](https://docs.github.com/en/issues/planning-and-tracking-with-projects/creating-projects/migrating-from-projects-classic).

**Comment by nashif** [comment]
done, automation also enabled...  https://github.com/orgs/zephyrproject-rtos/projects/36
