### ISSUE TITLE
GATT server fails to elevate security when there is insufficient security to send a notification/indication

### ISSUE THREAD

**Issue by demantmrrv** [zephyrproject-rtos/zephyr#61427]
**Describe the bug**
This issue is created due to several of our existing BabbleSims failing when merging Zephyr version 3.4.99 - tests that depend on service changed indications to some extent and are failing due to them not being sent after reconnecting.

The bug was found when transitioning from Zephyr 3.3.99 to Zephyr 3.4.99 and commit cfd368fef1, “Bluetooth: Host: Fix GATT server handling of CCC” is of particular interest here.

Overall, this happens when a device reconnects, and the GATT server is checking the security level of a CCC that was written while the link was encrypted. With the change in commit cfd368fef1 the security is not elevated by the GATT server for CCCs that were written with an encrypted connection and checked for  a change upon reconnect (while the connection is still unencrypted).

Specifically, it all happens in **gatt.c** when the **bt_gatt_connected()** is called. It traverses all characteristics with a call to **update_ccc()** with a pointer to a **struct conn_data**, which holds a **sec** member, containing the maximum security required for any of the CCCs.
In **update_ccc()** the newly introduced **bt_gatt_ccc_cfg_is_matching_conn()** function is called, that in turn compares the CCC's **link_encrypted** member with the encryption level of the connection and return false if they differ. The false return value will cause **update_ccc()** to skip the CCC hence, the **struct conn_data** pointer’s **sec** member is never updated.
When the call to **update_ccc()** has finished, the **bt_gatt_connected()** function checks its **sec** value, which, in this case, is left untouched, that is, security level 1. Consequently, it will not call **bt_conn_set_security()** with the higher level required by the CCC as intended and the notification/indication will not be sent to the client.

**To Reproduce**
1.	Pair two devices (which implies security level 2).
2.	Let the Central subscribe to a service changed indication from the Peripheral.
3.	Disconnect link.
4.	Change something in the Peripheral’s GATT database to trigger the service changed indication.
5.	Reconnect the two devices (without encrypting, i.e. security level is 1).
6.	Observe that the Peripheral’s GATT server does not elevate the security and the Central’s client receives no notification.

**Expected behavior**
When reconnecting, the GATT server must check the CCCs and if a CCC requires encryption the GATT server shall request encryption.
Refer comment excerpt from gatt.c:
`	/* BLUETOOTH CORE SPECIFICATION Version 5.1 | Vol 3, Part C page 2192:
	 *
	 * 10.3.1.1 Handling of GATT indications and notifications
	 *
	 * A client “requests” a server to send indications and notifications
	 * by appropriately configuring the server via a Client Characteristic
	 * Configuration Descriptor. Since the configuration is persistent
	 * across a disconnection and reconnection, security requirements must
	 * be checked against the configuration upon a reconnection before
	 * sending indications or notifications. When a server reconnects to a
	 * client to send an indication or notification for which security is
	 * required, the server shall initiate or request encryption with the
	 * client prior to sending an indication or notification. If the client
	 * does not have an LTK indicating that the client has lost the bond,
	 * enabling encryption will fail.
	 */`

Specifically, the **sec** member passed to **update_ccc()** must be updated to the security level required. This will trigger the **bt_gatt_connected()** to call **bt_conn_set_security()** in order to encrypt the connection.
Subsequently, the **bt_gatt_encrypt_change()** is called when the link is encrypted and **update_ccc()** is then called, this time triggering a service changed notification.

**Impact**
Can cause missing GATT notifications/indications, unless the Central explicitly enables encryption for other reasons.

**Environment**
 - OS: Debian 11.
 - Toolchain Zephyr SDK, BabbleSim, gcc.
 - Based on Zephyr 3.4.99 + non-related cherry-picks.

**Additional context**
Requires:
CONFIG_BT_GATT_AUTO_SEC_REQ
CONFIG_BT_GATT_SERVICE_CHANGED
CONFIG_BT_SMP

**Comment by carlescufi** [comment]
This was discussed and will be fixed by @theob-pro.
