### ISSUE TITLE
MPU9250 does not initialize

### ISSUE THREAD

**Issue by fatimatayyab71** [zephyrproject-rtos/zephyr#61452]
I am using the mpu9250 driver in zephyr-rtos, with sensor API generated with the help of MPU6050, but it does not initialize. Interfacing MPU9250 with nRF52832. Although there is no error detected at the time of compiling.
Sensor API for MPU9250 [https://github.com/fatimatayyab71/mpu9250](url) 
@anangl

**Comment by nordicjm** [comment]
Did you enable debugging? What does the debugging error message show?

**Comment by fatimatayyab71** [comment]
I am new to the nRF connect sdk, i had run the debug on the connected device. 
![Debug console 1](https://github.com/zephyrproject-rtos/zephyr/assets/135751177/45c9b571-8b6b-48cf-b33c-0665ab8315c2)

**Comment by nordicjm** [comment]
Debugging as in the logging subsystem and monitored the UART for any errors

**Comment by henrikbrixandersen** [comment]
Please use our bug template when reporting bugs. You need to edit this issue to include the information requested in https://github.com/zephyrproject-rtos/zephyr/blob/main/.github/ISSUE_TEMPLATE/001_bug_report.md
