### ISSUE TITLE
Rename module TraceRecorder/ to percepio/

### ISSUE THREAD

**Issue by nashif** [zephyrproject-rtos/zephyr#61557]
Rename module TraceRecorder/ to percepio to allow for additional functionality expanding multiple products.

**Comment by nashif** [comment]
@eriktamlin FYI

**Comment by galak** [comment]
> Sounds like the correct solution. Ensure you keep the existing repo (deprecated) for downstream users.

Agree with @henrikbrixandersen lets make sure not break old versions of zephyr if we "rename" the module.

**Comment by eriktamlin** [comment]
If someone creates a fork of https://github.com/percepio/percepio to zephyrproject-rtos/percepio and gives me access I can get to work making sure it is set up correctly.
