### ISSUE TITLE
can2 -> fdcan2 label change was missed in arduino_giga_r1 dts

### ISSUE THREAD

**Issue by peter-mitsis** [zephyrproject-rtos/zephyr#61569]
Running the following command

twister -p arduino_giga_r1_m7 -T tests/kernel/common/

has been resulting in build failures. See below. This has been traced to commit 03f20698aecf8586cfcf52ee24b8a3577731276c.

Renaming output directory to /home/pmitsis/zephyrproject/zephyr/twister-out.13
INFO    - Using Ninja..
INFO    - Zephyr version: zephyr-v3.4.0-2360-g03f20698aecf
INFO    - Using 'zephyr' toolchain.
INFO    - Building initial testsuite list...
INFO    - Writing JSON report /home/pmitsis/zephyrproject/zephyr/twister-out/testplan.json
INFO    - JOBS: 24
INFO    - Adding tasks to the queue...
INFO    - Added initial list of jobs to queue
ERROR   - Cmake build failure: /home/pmitsis/zephyrproject/zephyr/tests/kernel/common for arduino_giga_r1_m7
ERROR   - Cmake build failure: /home/pmitsis/zephyrproject/zephyr/tests/kernel/common for arduino_giga_r1_m7
ERROR   - arduino_giga_r1_m7        tests/kernel/common/kernel.common.misra             ERROR : Cmake build failure
ERROR   - see: /home/pmitsis/zephyrproject/zephyr/twister-out/arduino_giga_r1_m7/tests/kernel/common/kernel.common.misra/build.log
...

*** Impact ***
I am also seeing this show up in CI runs on new PRs.

**Comment by henrikbrixandersen** [comment]
Fixed in https://github.com/zephyrproject-rtos/zephyr/commit/77698e8a2235f575a64a58d19b3205f6e0c6b85b
