### ISSUE TITLE
tests/kernel/mem_protect/protection/kernel.memory_protection.protection fails on qemu_cortex_r5

### ISSUE THREAD

**Issue by fabiobaltieri** [zephyrproject-rtos/zephyr#61572]
**Describe the bug**
Hi, seems like `tests/kernel/mem_protect/protection/kernel.memory_protection.protection fails` started timing out on `qemu_cortex_r5` since 33a25371b6dcc3cfeb7df31f7ae9ba014830545f.

@tnmysh: any chance you could look into it?

**To Reproduce**
`./scripts/twister -v -n -M -p qemu_cortex_r5 -T tests/kernel/mem_protect/protection` on main

Also https://github.com/zephyrproject-rtos/zephyr/runs/15955541825, fails with `Timeout`.

Bisected down to 33a25371b6dcc3cfeb7df31f7ae9ba014830545f, reverting om main fixes the issue.

**Expected behavior**
Test should pass.

**Impact**
Broken in CI, pretty bad.

**Environment (please complete the following information):**
Linux, main (77698e8a22), Zephyr SDK 0.16.1

**Comment by fabiobaltieri** [comment]
cc @tnmysh @carlocaione @uLipe

**Comment by tnmysh** [comment]
@fabiobaltieri  Sure I will look into it.

**Comment by tnmysh** [comment]
I built that test and run on qemu_cortex_r5 platform with commit `https://github.com/zephyrproject-rtos/zephyr/commit/33a25371b6dcc3cfeb7df31f7ae9ba014830545f ` and it is passing.

```
===================================================================                                             
TESTSUITE protection succeeded                                                                                  
                                                                                                                
------ TESTSUITE SUMMARY START ------                                                                           
                                                                                                                
SUITE PASS - 100.00% [protection]: pass = 5, fail = 0, skip = 0, total = 5 duration = 3.943 seconds             
 - PASS - [protection.test_exec_data] duration = 0.582 seconds                                                  
 - PASS - [protection.test_exec_heap] duration = 2.694 seconds                                                  
 - PASS - [protection.test_exec_stack] duration = 0.363 seconds                                                 
 - PASS - [protection.test_write_ro] duration = 0.164 seconds                                                   
 - PASS - [protection.test_write_text] duration = 0.140 seconds                                                 
                                                                                                                
------ TESTSUITE SUMMARY END ------                                                                             
                                                                                                                
===================================================================                                             
```

@fabiobaltieri I am not sure why it is failing with CI. Any workaround to that? Can we skip it for this platform?

**Comment by tnmysh** [comment]
I tried this in my local repo: `west build -d /tmp/build -p -b qemu_cortex_r5 tests/kernel/mem_protect/protection/ -t run`

and hit this issue:

```
[142/143] To exit from QEMU enter: 'CTRL+a, x'[QEMU] CPU: cortex-r5
/bin/sh: QEMU-NOTFOUND: command not found
FAILED: zephyr/CMakeFiles/run_qemu /tmp/build/zephyr/CMakeFiles/run_qemu 
cd /tmp/build && QEMU-NOTFOUND -nographic -machine arm-generic-fdt -dtb /scratch/openamp/src/zephyr_3_4/zephyrproject/zephyr/boards/arm/qemu_cortex_r5/fdt-single_arch-zcu102-arm.dtb -net none -pidfile qemu.pid -chardev stdio,id=con,mux=on -serial chardev:con -mon chardev=con,mode=readline -icount shift=3,align=off,sleep=off -rtc clock=vm -device loader,file=/tmp/build/zephyr/zephyr.elf,cpu-num=4 -device loader,addr=0xff5e023c,data=0x80008fde,data-len=4 -device loader,addr=0xff9a0000,data=0x80000218,data-len=4
ninja: build stopped: subcommand failed.

```
Just want to check If CI is running this with QEMU or not.

**Comment by fabiobaltieri** [comment]
Yeah CI is running qemy, but I realize now that @dcpleung landed on a different commit than I in #61571 and his one looks more plausible. @dcpleung should we close this and follow up on yours?

**Comment by fabiobaltieri** [comment]
So on my system https://github.com/zephyrproject-rtos/zephyr/commit/36997de796261cf17a59072fd3f4b77e4706c93e works, https://github.com/zephyrproject-rtos/zephyr/commit/33a25371b6dcc3cfeb7df31f7ae9ba014830545f, fails, but revert either works. welp.

**Comment by dcpleung** [comment]
> @dcpleung should we close this and follow up on yours?

We can use this one since this has more information.

**Comment by tnmysh** [comment]
> So on my system [36997de](https://github.com/zephyrproject-rtos/zephyr/commit/36997de796261cf17a59072fd3f4b77e4706c93e) works, [33a2537](https://github.com/zephyrproject-rtos/zephyr/commit/33a25371b6dcc3cfeb7df31f7ae9ba014830545f), fails, but reverting either on top of mains works. welp.

@fabiobaltieri What is the error message you get when it fails ? Also, How do you run test with QEMU? Does zephyr provide some qemu binary I should test with ? For now, I am running zephyr binary on QEMU provided with Petalinux SDK. I would like to run with QEMU provided with Zephyr SDK.

**Comment by fabiobaltieri** [comment]
@tnmysh it fails with a timeout, the test runs with `./scripts/twister -v -n -M -p qemu_cortex_r5 -T tests/kernel/mem_protect/protection` (it runs on qemu) and it's using a qemu version that ships with the Zephyr SDK. That may explain why it's not failing on your side.

**Comment by fabiobaltieri** [comment]
You could also use `west build -d /tmp/build -p -b qemu_cortex_r5 tests/kernel/mem_protect/protection/ -t run`, that should finish with a `PROJECT EXECUTION SUCCESSFUL`, instead it hangs after

```
START - test_exec_heap
trying to call code written to 0x9858
```

**Comment by povergoing** [comment]
ping @SgrrZhf since https://github.com/zephyrproject-rtos/zephyr/pull/61200 has the same issue

**Comment by tnmysh** [comment]
Finally, after new setup of SDK, I am able to reproduce the issue.

**Comment by SgrrZhf** [comment]
Not only on `qemu_cortex_r5` but also on `fvp_baser_aemv8r_aarch32`, and I'm also looking into this.

**Comment by ibirnbaum** [comment]
In my case, I get the "Project execution successful" output in handler.log from the kernel.memory_protection.protection test case on qemu_cortex_r5, but also get the timeout from twister. A long, long time ago, we had a QEMU-related issue where test cases executed all the way to the end, but the test framework couldn't terminate QEMU. There was a workaround prior to this issue being fixed in the Xilinx-QEMU branch, which I just activated, hoping that this old issue might be back. Unfortunately, this didn't help. Guess I'll be looking for any unusual behaviour post the "Project Execution Successful" output next.

**Comment by fabiobaltieri** [comment]
@SgrrZhf could you test on `fvp_baser_aemv8r_aarch32` if rolling back [36997de](https://github.com/zephyrproject-rtos/zephyr/commit/36997de796261cf17a59072fd3f4b77e4706c93e) or [33a2537](https://github.com/zephyrproject-rtos/zephyr/commit/33a25371b6dcc3cfeb7df31f7ae9ba014830545f) fixes the issue? I'm not setup to run on that platform but I'd imagine that the Xilinx change does not affect it.

Since this is blocking PR runs I think that while it's being investigated we should either rollback on of the two or exclude the tests if we think that qemu is at fault there.

**Comment by ibirnbaum** [comment]
About to run the test on actual R5 hardware now in order to determine if QEMU is at fault.

**Comment by SgrrZhf** [comment]
This test can not pass on `fvp_baser_aemv8r_aarch32` because `__kernel_ram_start` is 0x0 and conflicts with other mpu regions.

I also tested this test case just now  on `qemu_cortex_r5` and it's ok on  `6f2e73a32f` which is the parent commit of `33a25371b6`.

So they are two different issues.

**Comment by SgrrZhf** [comment]
This test can pass on `qemu_cortex_r5` when `CONFIG_COMPILER_OPTIMIZATIONS` is selected. It's too bad.

**Comment by fabiobaltieri** [comment]
Sure but if it used to work then there's probably something wrong with https://github.com/zephyrproject-rtos/zephyr/commit/36997de796261cf17a59072fd3f4b77e4706c93e, I'd be laying toward reverting https://github.com/zephyrproject-rtos/zephyr/pull/60368 at this point, unless you folks have a better work around in mind.

**Comment by ibirnbaum** [comment]
Commenting my investigation results in Fabio's revert PR.

**Comment by ibirnbaum** [comment]
@fabiobaltieri I doubt that this is solely down to the linker command file modifications and therefore likely can't be fixed by just applying another patch to #60368. Looks like a multi-PR fix to me, starting with the hardcoded MPU range base addresses for the ZynqMP which break qemu_cortex_r5 easily regardless of the linker command file. If there's more to fix in the MPU area, that's another PR, and then finally re-applying #60368 (which fixed two other issues and therefore should ultimately be included). As I'm about to wrap it up for today, I just approved the revert PR. I'll keep posting updates over there, eventually setting up a problem report should one be required.

**Comment by tnmysh** [comment]
Thanks @ibirnbaum. On ZynqMP MPU ranges should be picked from device-tree I agree with that. It's okay to skip this test case for this platform until it is resolved. This will allow linker script change without breaking CI.

**Comment by fabiobaltieri** [comment]
Thanks for the detailed investigation, just merged the rollback, going to close the issue since CI should pass again, feel free to reopen if you want to keep it for following up for whatever reason.

**Comment by gramsay0** [comment]
Hey, out of interest I went back and had a look at this failure.

I checked out 0538041cd68f84c04e23e6f987082fb1ec2b6330 (the commit before this revert) and could reproduce the tests/kernel/mem_protect/protection failure.

I noticed a couple of things:.

1. That test does some magic to handle thumb instructions for Cortex-M but not for Cortex-R.
Changing `#ifdef CONFIG_CPU_CORTEX_M` -> `#ifdef CONFIG_COMPILER_ISA_THUMB2` results in a different failure:
"Execute from heap did not fault"/"Execute from stack did not fault"
2. soc/arm/xilinx_zynqmp/arm_mpu_regions.c does not set the "Execute Never" flag `MPU_RASR_XN_Msk`.
So I modified `MPUTYPE_PRIV_WBWACACHE` to add that flag.

After these two changes that test passes.

I didn't look into any other test, but hopefully that is helpful is someone wants to carry this on

Full patch:
```diff
diff --git a/soc/arm/xilinx_zynqmp/arm_mpu_regions.c b/soc/arm/xilinx_zynqmp/arm_mpu_regions.c
index f10ba5d94e..e03fef61b5 100644
--- a/soc/arm/xilinx_zynqmp/arm_mpu_regions.c
+++ b/soc/arm/xilinx_zynqmp/arm_mpu_regions.c
@@ -22,11 +22,12 @@
                                | MPU_RASR_B_Msk) \
        }
 
-#define MPUTYPE_PRIV_WBWACACHE \
+#define MPUTYPE_PRIV_WBWACACHE_XN \
        { \
                .rasr = (P_RW_U_NA_Msk \
                                | (5 << MPU_RASR_TEX_Pos) \
-                               | MPU_RASR_B_Msk) \
+                               | MPU_RASR_B_Msk \
+                               | MPU_RASR_XN_Msk) \
        }
 
 #define MPUTYPE_PRIV_DEVICE \
@@ -45,7 +46,7 @@ static const struct arm_mpu_region mpu_regions[] = {
        MPU_REGION_ENTRY("SRAM_PRIV",
                        0x00000000,
                        REGION_2G,
-                       MPUTYPE_PRIV_WBWACACHE),
+                       MPUTYPE_PRIV_WBWACACHE_XN),
 
        MPU_REGION_ENTRY("SRAM",
                        0x00000000,
diff --git a/tests/kernel/mem_protect/protection/src/main.c b/tests/kernel/mem_protect/protection/src/main.c
index fcd14e1eff..2f66edcdb9 100644
--- a/tests/kernel/mem_protect/protection/src/main.c
+++ b/tests/kernel/mem_protect/protection/src/main.c
@@ -34,8 +34,7 @@ void k_sys_fatal_error_handler(unsigned int reason, const z_arch_esf_t *pEsf)
        ztest_test_pass();
 }
 
-#ifdef CONFIG_CPU_CORTEX_M
-#include <zephyr/arch/arm/aarch32/cortex_m/cmsis.h>
+#ifdef CONFIG_COMPILER_ISA_THUMB2
 /* Must clear LSB of function address to access as data. */
 #define FUNC_TO_PTR(x) (void *)((uintptr_t)(x) & ~0x1)
 /* Must set LSB of function address to call in Thumb mode. */
```

```
west build -b qemu_cortex_r5 tests/kernel/mem_protect/protection -t run
<test output...>
===================================================================
PROJECT EXECUTION SUCCESSFUL
```

**Comment by fabiobaltieri** [comment]
@gramsay0 could you open a PR for that and then we can use that to followup with the ARM maintainers about it?

**Comment by gramsay0** [comment]
@fabiobaltieri ok, I opened a PR https://github.com/zephyrproject-rtos/zephyr/pull/68191

**Comment by ibirnbaum** [comment]
@gramsay0 Thanks for looking into this. I'm still working on a new (device tree- based) MPU setup in the UltraScale MPU init code, I'll apply your patch to that right away.

**Comment by ibirnbaum** [comment]
Any thoughts on re-applying #60368 once the proposed fixes have been integrated?
