### ISSUE TITLE
SMP lacks low-power idle

### ISSUE THREAD

**Issue by andyross** [zephyrproject-rtos/zephyr#6157]
Right now the SMP implementation has an idle loop for auxiliary CPUs that simply spins on the scheduler waiting for a runnable thread to appear.  That minimizes latency at the expense of power (the opposite tradeoff would be to wait for our next timer tick, but that can be a very long time).

A proper architecture would have the scheduler issue an inter-processor interrupt to idle CPUs whenever a thread was added to the ready queue so that they can synchronously wake up.  (Even this might require some performance tuning in the long term, though, because in many cases the thread is being added just as the current thread is being removed and we don't want to incur the wakeup costs).

**Comment by nashif** [comment]
fixed
