### ISSUE TITLE
Nominate faxe1008 as contributor with triage rights

### ISSUE THREAD

**Issue by fabiobaltieri** [zephyrproject-rtos/zephyr#61639]
# Nomination

## GitHub User

Provide the following information about the GitHub user:

1. Fabian Blatz
1. @faxe1008

## Supporting Documents

- https://github.com/zephyrproject-rtos/lvgl/pull/42
- https://github.com/zephyrproject-rtos/zephyr/pull/60498
- https://github.com/zephyrproject-rtos/zephyr/pull/61300
- https://github.com/zephyrproject-rtos/zephyr/pull/60867

Fabian is willing to take the maintainer rode for LVGL (currently in odd fixes): https://github.com/zephyrproject-rtos/zephyr/pull/61638

[TSC Project Roles]: <https://docs.zephyrproject.org/latest/project/project_roles.html>
[GitHub Permission Level]: <https://docs.github.com/en/organizations/managing-access-to-your-organizations-repositories/repository-roles-for-an-organization>

**Comment by nashif** [comment]
https://github.com/zephyrproject-rtos/zephyr/invitations
