### ISSUE TITLE
I made a standalone menuconfig

### ISSUE THREAD

**Issue by JiauZhang** [zephyrproject-rtos/zephyr#61664]
Hey, guys.

I made a standalone menuconfig --> https://github.com/JiauZhang/menuconfig

Kconfig is an important configuration tool that is used in many projects. The commonly used Kconfig implementation, [Kconfiglib](https://github.com/ulfalizer/Kconfiglib), has not been updated since Jan 31 and 2020, so I created this project. Most of the source code is synchronized from the Linux kernel, and I have added some additional code to enable menuconfig to run independently.

I will regularly synchronize the relevant code in the Linux kernel into this project.

Welcome everyone to use it and provide good suggestions.

**Comment by gmarull** [comment]
we use https://github.com/zephyrproject-rtos/zephyr/tree/main/scripts/kconfig

**Comment by henrikbrixandersen** [comment]
@JiauZhang What are you suggesting?
