### ISSUE TITLE
Incorrect docstring in atomic.h

### ISSUE THREAD

**Issue by hershjos** [zephyrproject-rtos/zephyr#61661]
zephyr/include/zephyr/sys/atomic.h: 165 is incorrect.

```
"* Atomically set bit number @a bit of @a target and return its old value.
 * The target may be a single atomic variable or an array of them."
```

The return tag is also poorly phrased `@return true if the bit was set, false if it wasn't.`. Would make more sense if it was `@return the value of the bit after it is set`

The function returns the current value of the bit being set, not the old value. May seem minor but I've already dealt with supplier code that is incorrect because it assumes its behavior.

[atomic.h: 165](https://github.com/zephyrproject-rtos/zephyr/blob/45a4177704247e22f45a699d3a376b8b564b4b7e/include/zephyr/sys/atomic.h#L165
)
Zephyr. Branch main, version 3-4-0.  Latest commit for the file is 24d09d363c59ca3d18dd24d3fc7c80582af56075

**Comment by nashif** [comment]
> The function returns the current value of the bit being set, not the old value.

not sure I am following. This function is returning a boolean, not the current value...

**Comment by fabiobaltieri** [comment]
Hi, Zephyr is an open-source project, and as such we welcome and encourage the community to submit patches directly. Would you be able to submit a pull request with the fix? This is the [contribution guideline documentation](https://docs.zephyrproject.org/latest/contribute/guidelines.html#contribution-guidelines).

**Comment by nashif** [comment]
> not sure I am following. This function is returning a boolean, not the current value...

ok, this is an issue, i see the wrong language now.

**Comment by kartben** [comment]
@hershjos Please let me know if you need help with the PR, I'll be happy to assist!

**Comment by hershjos** [comment]
@nashif I realized the first half of the docstring is correct since atomic_or returns the previous and not current value. its the @return that's incorrect "* @return true if the bit was set, false if it wasn't."

I'm going on vacation but I'll improve the wording and submit a PR afterwards.
