### ISSUE TITLE
Error in SD card storage init 

### ISSUE THREAD

**Issue by tanmaygoyal875** [zephyrproject-rtos/zephyr#61669]
I am using STM32F469i_disco which has inbuild SD-Card slot. I am using 16GB of sd-card. I have done every possible solution to resolve below error but cant please suggest me the solution for it. i am using the zephyr fs fat code for that and below the error i am putting overlay file for that 

*** Booting Zephyr OS build zephyr-v3.4.0-1798-ga0a9539d0223 ***
[00:00:00.000,000] <inf> flashdisk: Initialize device noname
[00:00:00.000,000] <inf> flashdisk: offset d8000, sector size 512, page size072, volume size 163840
[00:00:00.000,000] <err> flashdisk: Disk noname does not start at page bound
[00:00:00.000,000] <err> main: Storage init ERROR!
[00:00:00.000,000] <err> fs: fs mount error (-19)
Error mounting disk.

~~~~~~~~~~~~~~~~~~~~~~~~~~~Overlay~~~~~~~~~~~~
&flash0 {

	partitions {
		compatible = "fixed-partitions";
		#address-cells = <1>;
		#size-cells = <1>;
		storage_partition: partition@d8000 {
			label = "storage";
			reg = <0x000d8000 0x00028000>;
		};
	};
};

/ {
	msc_disk0 {
		status="okay";
		compatible = "zephyr,flash-disk";
		partition = <&storage_partition>;
		disk-name = "SD";
		/* cache-size == page erase size */
		cache-size = <4096>;
	};
};
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by Desvauxm-st** [comment]
@tanmaygoyal875
Can you tell me how to reproduce this problem.
do you use samples\subsys\fs\fs_sample for this?

**Comment by tanmaygoyal875** [comment]
yes sir

**Comment by Laczen** [comment]
@tanmaygoyal875 your setup is describing a disk on the internal flash of your device. This description is not honoring the flash erase-blocks of the device and this is why you are getting this error.

To enable the use of an SD-card slot your overlay file should use something similar to the one provided in https://github.com/zephyrproject-rtos/zephyr/blob/main/samples/subsys/fs/fs_sample/boards/nucleo_f429zi.overlay

**Comment by Desvauxm-st** [comment]
@tanmaygoyal875
I try  and i see the same error message  Storage init ERROR!
I will try to push a new PR to try to fix this bug 
regards

**Comment by Desvauxm-st** [comment]
@tanmaygoyal875
can you try this modification:
boards: arm: stm32f469i_disco: add sdmmc1 #61859
