### ISSUE TITLE
CONFIG_IS_BOOTLOADER is poorly named and documented

### ISSUE THREAD

**Issue by SebastianBoe** [zephyrproject-rtos/zephyr#6180]
See https://github.com/runtimeco/mcuboot/issues/230 for details

**Comment by nashif** [comment]
put MCUBOOT aside, you can build zephyr to act as a bootloader, so there is nothing confusing here

```
This option indicates that Zephyr will act as a bootloader to execute
a separate Zephyr image payload.
```

Not sure how this can be written in some other way, IMO it is clear enough.

**Comment by SebastianBoe** [comment]
Perhaps:

This option will offset the ORIGIN of the MEMORY region SRAM by "CONFIG_BOOTLOADER_SRAM_SIZE" kB and reduce it's SIZE by the same amount.
