### ISSUE TITLE
RFC: add heatshrink compression library support

### ISSUE THREAD

**Issue by RomainPelletant** [zephyrproject-rtos/zephyr#61822]
## Origin

Name of project hosting the original open source code : [Heatshrink](https://github.com/atomicobject/heatshrink)

## Purpose

Compression/Decompression library with low memory footprint.
Decompression takes 800 bytes flash usage and 512 bytes to 2kB of RAM depending on compression level.

<img width="299" alt="ram" src="https://github.com/zephyrproject-rtos/zephyr/assets/91246595/78906c69-a388-4506-98e2-0de8e2cfcb5d">

**RAM report**

<img width="398" alt="rom" src="https://github.com/zephyrproject-rtos/zephyr/assets/91246595/9473b50d-92c2-497f-94ab-10f9f4ee1a20">

**ROM report**

## Mode of integration

Offer a low memory footprint compression library to enable OTA or Delta OTA on most constrained platforms.
Heatshrink is used in several Delta processing tentatives (combined with delta algorithms) for MCU.
Integration as module, named heatshrink.

## Maintainership

List the person(s) that will be maintaining the integration of this external code
for the foreseeable future. Please use GitHub IDs to identify them. You can
choose to identify a single maintainer only or add collaborators as well
- @RomainPelletant : [ID](https://github.com/RomainPelletant)
- @ClovisCorde : [ID](https://github.com/ClovisCorde)

## Pull Request

Please see that PR integrating heatshrink as a module (with an external heatshrink repository for test purpose)
[PR](https://github.com/zephyrproject-rtos/zephyr/pull/61821)

<img width="1283" alt="HS-lz4" src="https://github.com/zephyrproject-rtos/zephyr/assets/91246595/c752858e-4d7f-4270-b4db-888b7aa27eb5">
Heatshrink sample on the left / LZ4 sample on the right

## Description

Heatshrink is a low memory footprint compression/decompression library.
It enables on-the-fly decompression, useful to directly save on flash decompression output without the need of consequent buffer length.
That library is used in several Delta update tentatives/thesis and it could be a first step to implement a Delta API.

## Dependencies

Direct calls to the library are preferred.

## Revision

SHA : 7d419e1fa4830d0b919b9b6a91fe2fb786cf3280

## License

``ISC``

**Comment by nordicjm** [comment]
Have previously used this library in MCU-based applications and was seeing ~27% average reduction in bin filesize (which was great), the library itself has a small overhead.

**Comment by nashif** [comment]
TSC: under review, we are considering to introduce an area for integration optional modules which will allow listing this as something a user can integrate in their application without making it a module maintained in the default manifest.

**Comment by nashif** [comment]
this should be done as an external module, i.e. by providing a reference and enabled by those who need it in their manifest, see https://docs.zephyrproject.org/latest/develop/manifest/index.html#external-projects-modules

**Comment by RomainPelletant** [comment]
@nashif thanks for your feedback

**Comment by RomainPelletant** [comment]
@nashif if I well understood, we shall only update our repository to be included as external module and we shall update documentation to add our external module to replace "TBD".
![image](https://github.com/zephyrproject-rtos/zephyr/assets/91246595/9830cf38-841b-4505-8da9-968048909324)
Is that array, the expected columns could be: "project", "revision", "url", and maybe a description?
