### ISSUE TITLE
sensor: Handling sensors with long measurement times

### ISSUE THREAD

**Issue by tkln** [zephyrproject-rtos/zephyr#6183]
There are sensors with relatively long sampling times. For example the CCS811 gas sensor has different measurement modes with measurement latencies varying between 1 s, 10 s or 60 s. This rises two issues: how should this be controlled and is it reasonable for `sensor_sample_fetch` to block up to a minute, or should there be some sort of an asynchronous alternative.

Some sensor drivers use SENSOR_ATTR_SAMPLING_FREQUENCY for controlling the sampling frequency, but in the case of CCS811, the user would have to calculate the frequency that corresponds to the desired sampling interval. This is quite inconvenient. One solution could be adding a new attribute for sampling intervals or a helper function for converting intervals to frequencies.

**Comment by MaureenHelm** [comment]
There is an asynchronous alternative via the sensor trigger `SENSOR_TRIG_DATA_READY`, but the CCS811 driver needs to implement it. cc: @Mani-Sadhasivam 

`SENSOR_ATTR_SAMPLING_FREQUENCY` allows values less than 1 Hz so I don't see a need for a new interval attribute.
