### ISSUE TITLE
mgmt: mcumgr: Compilation error when img status hook is enabled and upload check hook is not enabled

### ISSUE THREAD

**Issue by spe-ciellt** [zephyrproject-rtos/zephyr#61833]
**Describe the bug**
When adding the flag `CONFIG_MCUMGR_GRP_IMG_STATUS_HOOKS` but not the flag `CONFIG_MCUMGR_GRP_IMG_UPLOAD_CHECK_HOOK` there is a compilation error 
```
<project directory>/zephyr/subsys/mgmt/mcumgr/grp/img_mgmt/src/img_mgmt.c:430:29: error: unused variable 'status' [-Werror=unused-variable]
  430 |         enum mgmt_cb_return status;
      |                             ^~~~~~
cc1: all warnings being treated as errors
```

The status variable inclusion depends on either of the flags mentioned above. The usage of that variable only depends on `CONFIG_MCUMGR_GRP_IMG_UPLOAD_CHECK_HOOK`.

The mitigation is to enable both flags. I do not know if one flag is used without the other.  Since the mitigation is simple, this is not a problem for us.

**To Reproduce**
Enable the flags `CONFIG_MCUMGR_MGMT_NOTIFICATION_HOOKS` and `CONFIG_MCUMGR_GRP_IMG_STATUS_HOOKS` but not the flag `CONFIG_MCUMGR_GRP_IMG_UPLOAD_CHECK_HOOK`

**Expected behavior**
No compilation error/warning.

**Impact**
Since the mitigation is simple it does not have any real impact for us.

**Environment (please complete the following information):**
 - OS:Linux
 - Zephyr SDK 0.16.1
 - Zephyr 3.4

**Comment by nordicjm** [comment]
This was fixed for `main` by https://github.com/zephyrproject-rtos/zephyr/pull/59739 but was not backported, will add the backport label
