### ISSUE TITLE
RFC: Stable API Change: `k_mem_slab_free()`

### ISSUE THREAD

**Issue by carlescufi** [zephyrproject-rtos/zephyr#61937]
### Problem description

See https://github.com/zephyrproject-rtos/zephyr/issues/61888

### Proposed change

See https://github.com/zephyrproject-rtos/zephyr/issues/61888.

## Detailed RFC

See https://github.com/zephyrproject-rtos/zephyr/pull/61901

### Dependencies

Users will have to modify their code using `k_mem_slab_free`, typically removing the `&` or adding `*` depending on the original code. See examples in the commits here:
https://github.com/zephyrproject-rtos/zephyr/pull/61901/commits

Note that this particular case is quite tricky because, in most cases,  users will not get neither a compiler warning nor error. Failure will happen at runtime, typically with an invalid memory access.

**Comment by nashif** [comment]
> ### Dependencies
> None

Is this really the case?

Per the docs:

   - Dependencies:
             - Impact to users of the API, including the steps required
               to adapt out-of-tree users of the API to the change

So you are saying there is no impact? If I take the first commit from https://github.com/zephyrproject-rtos/zephyr/issues/61888 and run twister on the code base, I get no build errors and no warnings, many samples and tests would fail however. 
Given that we are not deprecating the API, it means that user code will stop working as expected and that is going to be difficult to detect and debug. 
The only information we give the user is a one-liner in the release notes, which is going to be easy to miss.

**Comment by carlescufi** [comment]
> Per the docs:
> 
> * Dependencies:
>   - Impact to users of the API, including the steps required
>   to adapt out-of-tree users of the API to the change
> 
> So you are saying there is no impact? If I take the first commit from #61888 and run twister on the code base, I get no build errors and no warnings, many samples and tests would fail however.

No, I clearly misread the docs, thanks for pointing it out. I have updated this now.

**Comment by carlescufi** [comment]
Complete
