### ISSUE TITLE
K64F ethernet regression since f7ec62eb

### ISSUE THREAD

**Issue by mike-scott** [zephyrproject-rtos/zephyr#6194]
Looks like this commit broke the K64F ethernet functionality:
https://github.com/zephyrproject-rtos/zephyr/commit/f7ec62eb8525b5d3f5351df183c1f550d77d4e80

I'm guessing there are registers being used by the ethernet driver which are not allowed to be touched now?

NOTE: This came up during testing of a network sample on K64F using master branch.

**Comment by pfalcon** [comment]
Perhaps https://github.com/zephyrproject-rtos/zephyr/pull/6214 was posted to address this.
