### ISSUE TITLE
MTD api: unified method to work with memory technology devices and their partitioning

### ISSUE THREAD

**Issue by Laczen** [zephyrproject-rtos/zephyr#61979]
**Is your enhancement proposal related to a problem? Please describe.**

In zephyr flash devices are partitioned using the `flash_map` subsystem. The `flash_map` system has some disadvantages when used with multiple flash devices because it operates on a global array of flash partitions that are defined using devicetree. This results in the inclusion of flash devices even when they are not used (#52395).

In zephyr there also is a need to support partitioning of devices that are not flash devices, e.g. eeprom, bbram and retained_mem. Partitioning of these devices is either enabled in a higher level subsystem (e.g. retention for retained_mem) or is not available (eeprom, bbram).

When storage solutions (nvs, fcb, little-fs, fat-fs) are used they support being enabled on top of flash_map system and are not available for other backends.

**Describe the solution you'd like**

Instead of the `flash_map` solution an alternative is proposed that enables support of a partitioned mtd device that basically supports 3 main routines:
```
int mtd_read(const struct mtd_info *info, off_t offset, void *data, size_t len);
int mtd_write(const struct mtd_info *info, off_t offset, const void *data, size_t len);
int mtd_erase(const struct mtd_info *info, off_t offset, size_t len);
```
With
```
enum mtd_type = {FLASH, EEPROM, BBRAM, RETAINED_MEM};
struct mtd_info_cfg = {
	const enum mtd_type type;
	const struct device *mtd_device;
	const struct mtd_info *mtd_parent; /* NULL for "main" device */ 
	const off_t off;
	const size_t size;
	const bool read_only;
};
struct mtd_info {
	const struct mtd_info_cfg *cfg;
	const struct mtd_info_data *data; // Unused at the moment.
};
```

The "fixed-partition" compatible would be used to create a `mtd_info` struct for each partition. Also a `mtd_info` struct is created for the main device.

To enable other devices (eeprom, bbram, retained_mem) to also have partioning and at the same time enable them to be used for fs storage for each of these devices a compatible `zephyr,xxx-mtd-emul` is provided that describes the mapping of the specific device to a mtd device (erase-block, write-block).

If a defined `mtd_info` struct for a main device or a partition is not used it would be removed from the binary during compilation.

**Describe alternatives you've considered**
Leave it as is. To support devices like eeprom, bbram, retained_mem a compatible `zephyr,xxx-flash-emul` could be created and flash_map used for the partitioning.

**08/29 Modified the proposal to avoid clarify**
**08/29 Modified to include the mtd_type in `mtd_info_cfg`, this allows a user to find out what backend is used and allows direct call of a implementation routine**

**Comment by Laczen** [comment]
@de-nordic (flash), @henrikbrixandersen (eeprom), @nordicjm (retained_mem), @yperess (bbram), @jfisher-no (disk), @danieldegrasse (disk).

**Comment by Laczen** [comment]
In linux the name mtd is limited to flash devices (nand flash, nor flash, ...). The name `mtd` is badly chosen as the proposal targets other devices as well.

**Comment by henrikbrixandersen** [comment]
While I'd like to see generic support for partitioning MTD devices, I don't think we should introduce any "emulators" in order to do so. The term "emulator" should be reserved for emulation, which - at least in my vocabulary - is not something that is used in production firmware.

We could have a proper MTD _subsystem_ with support for the various backends (flash, EEPROM, BBRAM, ...). However, this will not magically solve the issue of being able to use all sorts of different storage _frontends_ on top (settings, filesystems, NVS, ...) since many of these make assumptions about the underlying technology (e.g. assumes that pages needs erasing before being able to write them, which is not true for a number of MTD technologies).

**Comment by Laczen** [comment]
@henrikbrixandersen there might be some confusion about the meaning of mtd devices. In zephyr eeprom are also under the mtd umbrella. In linux eeproms are not considered mtd devices. When referring to mtd devices I would be referring to devices that require erase in pages before being written.

If it is accepted that mtd devices would require erase before being written than the mtd subsystem would solve the problem of support for multiple backends, eeprom, bbram,... could receive the erase before write property trough an emulation (couldn't find a better name yet) layer. The name emulation could be avoided by just calling the compatibles `zephyr,eeprom-mtd`, `zephyr,bbram-mtd`.

**Comment by Laczen** [comment]
Maybe the layer for eeprom, bbram, retained_mem could be called the "adaptation" layer.

**Comment by Laczen** [comment]
I'm stopping my pursuit to try and unify working with different memories as this could be seen alternatives to existing solutions.
