### ISSUE TITLE
SAM devices are missing the DMA API get_status() implementation

### ISSUE THREAD

**Issue by tswaehn** [zephyrproject-rtos/zephyr#62003]
**Is your enhancement proposal related to a problem? Please describe.**
The DMA API allows to read the current status of a DMA channel. However this is not yet implemented for SAM XDMAC. 

**Describe the solution you'd like**
All required registers are defined. Would be a small fix to add this functionality.

**Describe alternatives you've considered**
I could patch the zephyr after downloading via git and use my patched version.

**Additional context**
I will create a fork and merge request with the required changes.

**Comment by tswaehn** [comment]
@henrikbrixandersen just wondering how to find a reviewer for the PR ?

**Comment by henrikbrixandersen** [comment]
> @henrikbrixandersen just wondering how to find a reviewer for the PR ?

A few reviewers are assigned now.

**Comment by tswaehn** [comment]
thanks, that is great. I allready had to fix some style related things. :smile:
