### ISSUE TITLE
    tests-ci : drivers: flash: falsh.common.default test Device issue (Flash error?)    

### ISSUE THREAD

**Issue by hakehuang** [zephyrproject-rtos/zephyr#62067]
**Describe the bug**
drivers.flash.common.default test has Device issue (Flash error?) on zephyr-v3.4.0-2851-g34fddd8b4c09 on lpcxpresso55s28
  
**To Reproduce**
1. 
  
` scripts/twister --device-testing --device-serial /dev/ttyACM0 -p lpcxpresso55s28   --sub-test drivers.flash.common.default`
  
or
 
`
    # cd tests/drivers/flash/common
    # west build -b lpcxpresso55s28
    # west flash
`

 2. See error

**Expected behavior**
    test pass

**Impact**

**Logs and console output**
    
no log output when this happen

**Environment (please complete the following information):**
 - OS: (e.g. Linux )
 - Toolchain (e.g Zephyr SDK)
 - Commit SHA or Version used: zephyr-v3.4.0-2851-g34fddd8b4c09

**Comment by nashif** [comment]
@hakehuang  please fix whatever scripts you are using to create issues, the layout of the bug is malformed.

**Comment by hakehuang** [comment]
> @hakehuang please fix whatever scripts you are using to create issues, the layout of the bug is malformed.

sorry, let me check my scripts.

**Comment by hakehuang** [comment]
fixed in : 69643d575d6b95b29f2847ebfeaa150d758bb87f
