### ISSUE TITLE
Setup override after setting up sysclock

### ISSUE THREAD

**Issue by maxvankessel** [zephyrproject-rtos/zephyr#62130]
**Describe the bug**
Unable to boot Zephyr on STM32F7 with 216MHz fomr MCUboot

**Expected behavior**
Normal boot procedure

**Impact**
Showstopper, CPU doesn't boot.

**Logs and console output**
Before log output

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: Zephyr SDK
 - Commit SHA: 07c6af3b 
 - Version used v3.3

**Additional context**
According to the reference manual the overdrive can be enabled when the sysclock source is set and  the PLL has been turned on:

![image](https://github.com/zephyrproject-rtos/zephyr/assets/37693428/6458d7de-49c6-477a-914b-4398696034db)

I believe the following code block (including the FLASH ACR LATENCY) should be moved below `set_up_plls();`

https://github.com/zephyrproject-rtos/zephyr/blob/64e841152737507c62f9daa8009be0a0dbfcdc99/drivers/clock_control/clock_stm32_ll_common.c#L726-L739

I'm having issues in combination with MCUboot, standalone I don't have any issues.

**Comment by nordicjm** [comment]
We have a template for reporting issues, can you fill it in instead of clearing it and making it impossible to know what you're using?

**Comment by maxvankessel** [comment]
> We have a template for reporting issues, can you fill it in instead of clearing it and making it impossible to know what you're using?

Just used the github interface:
![image](https://github.com/zephyrproject-rtos/zephyr/assets/37693428/88994efa-05fc-40c0-8e38-1fe6766b0760)

**Comment by nordicjm** [comment]
https://github.com/zephyrproject-rtos/zephyr/issues/new/choose is where issues should be raised

@nashif can this other way of raising issues be blocked?

**Comment by erwango** [comment]
> I believe the following code block (including the FLASH ACR LATENCY) should be moved below set_up_plls();

Did you have a try?

**Comment by maxvankessel** [comment]
> > I believe the following code block (including the FLASH ACR LATENCY) should be moved below set_up_plls();
> 
> Did you have a try?

Yes, but it's not exactly as the reference manual states.

**Comment by maxvankessel** [comment]
Do you want me to create a PR @erwango?
