### ISSUE TITLE
Interrupt number generation fails when *_LEVEL_INTERRUPT_BITS are set to a value other than 8 bits

### ISSUE THREAD

**Issue by xakep-amatop** [zephyrproject-rtos/zephyr#62224]
In the context of the [GitHub merge request](https://github.com/zephyrproject-rtos/zephyr/pull/61050), a mechanism was introduced that enables the use of more than 255 IRQs per interrupt level.

However, it appears that during the implementation, the `encode_zephyr_multi_level_irq` function (located [here](https://github.com/zephyrproject-rtos/zephyr/blob/main/scripts/dts/gen_defines.py#L463)) was not updated to correctly generate IRQ numbers. Currently, it is only possible to use `*_LEVEL_INTERRUPT_BITS` values that are equal to 8.

For instance, suppose a second-level interrupt controller maps IRQ 0 (2nd level IRQ line) to IRQ 4 (SPI parent IRQ line), and we have 512 IRQ lines on the 1st level. In this case, we would need to set `1ST_LEVEL_INTERRUPT_BITS` to 9. The current implementation generates IRQ numbers using the following rules: `(irq_line2 + 1) << 8 + irq_line1`. In my particular case the final IRQ number will be `0x104`. Subsequently, if we call `irq_get_level` for this IRQ line, e.g., `0x104`:
```
	const uint32_t mask2 = BIT_MASK(CONFIG_2ND_LEVEL_INTERRUPT_BITS) <<
		CONFIG_1ST_LEVEL_INTERRUPT_BITS;
``` 
`mask2` will be equal to `0x1FE00`. Lastly, we want to check whether this is a 2nd level IRQ or not:
```
	if (IS_ENABLED(CONFIG_2ND_LEVEL_INTERRUPTS) && (irq & mask2) != 0) {
		return 2;
	}
```
`0x104 & 0x1FE00 != 0` returns `false`.

-----
So, I believe that we should fix the logic inside `encode_zephyr_multi_level_irq`.

**To Reproduce**
* set 1ST_LEVEL_INTERRUPT_BITS to 9 bits;
* build a sample using a board that supports 2nd/3rd level interrupt controller, sample should use 2nd/3rd level interrupts.

**Expected behavior**
The Python script should correctly generate IRQ numbers when *_LEVEL_INTERRUPT_BITS are not set to 8 bits.

**Comment by ycsin** [comment]
I guess this is covered by #63289?
