### ISSUE TITLE
IRC-bot sample eventually stops responding to IRC commands

### ISSUE THREAD

**Issue by mike-scott** [zephyrproject-rtos/zephyr#6226]
Symptom:
After a while (not sure on the exact timing), the Zephyr device stops responding to IRC commands.

Expectation:
No matter how long the device has been running, commands on IRC should still work.

Needs debugging.

**Comment by jukkar** [comment]
Just guessing here but if there is a net_buf leak we could get into this issue easily.

**Comment by nashif** [comment]
@mike-scott still an issue?

**Comment by mike-scott** [comment]
@nashif haven't checked this lately.  But we need to migrate the entire sample to use sockets.  We can close now and re-open later if needed.
