### ISSUE TITLE
k_fifo_cancel_wait does not cause pending k_fifo_get() to return NULL

### ISSUE THREAD

**Issue by mtpr-ot** [zephyrproject-rtos/zephyr#62274]
**Description**
According to the documentation, calling `k_fifo_cancel_wait()` shall cause a pending thread to return from `k_fifo_get()` with NULL: _"This routine causes first thread pending on @a fifo, if any, to return from k_fifo_get() call with NULL value (as if timeout expired)."_
What happens is that in any case where a data item has been added to the fifo using `k_fifo_put()`, this item is returned when calling `k_fifo_cancel_wait()`, and not NULL.

**To Reproduce**
1. Set `CONFIG_BT_HCI_ACL_FLOW_CONTROL=n`
2. Add code to inject a dummy RX node into `recv_fifo`, e.g. `k_fifo_put(&recv_fifo, &dummy_node);`. This may be done in `hci_recv_fifo_reset()`
3. Boot any sample
4. Observe return value in `recv_thread`, at `node_rx = k_fifo_get(&recv_fifo, K_FOREVER);`
5. Return value is address of `dummy_node`
6. If no dummy node is added (fifo is empty), `hci_recv_fifo_reset()` correctly makes `k_fifo_get()` return NULL

**Expected behavior**
When `k_fifo_cancel_wait()` is called on a fifo, `k_fifo_get()` in pending thread should return NULL, even if there is actually data in the fifo.

**Impact**
At HCI reset, RX nodes that have been reset are returned and used in the RX thread, causing asserts on invalid type and class.
EBQ tests become flaky.

**Comment by fabiobaltieri** [comment]
@mtpr-ot could you send a patch with the proposed fix?

**Comment by DariusBabrauskas** [comment]
I think this is not a bug, but normal operation.
