### ISSUE TITLE
retain state of port expander from bootloader

### ISSUE THREAD

**Issue by benediktibk** [zephyrproject-rtos/zephyr#62293]
### Problem Description
I have a setup with a bootloader and a firmware, both using zephyr. The bootloader configures a port expander (to be specific: a PCAL6416) and set a few of the pins as output. The state of these pins as outputs now should be retained during the boot into the firmware. As by default the firmware initializes the same port expander again and triggers a reset the configuration gets lost.

### Solution Proposals

- no-reset: Introducing something as a no-reset flag in the devicetree for the port expander would allow the driver to react correctly. In case it is set (for instance in the app.overlay of the firmware) the reset won't be triggered, but instead the current state (in/out confiugrations, out pin states, ...) read and stored.
- power management: One could consider the switch from bootloader to firmware similar to a wakeup from a very deep sleep state of the SoC. This could mean that a reset of the port expander is only triggered in PM_DEVICE_ACTION_TURN_ON and the switch from bootloader to firmware only triggers a PM_DEVICE_ACTION_RESUME.

Especially regarding the power management I am uncertain if such a thing is possible currently. On the other hand, the no-reset approach feels a little bit hacky. Therefore I would like to check which approach would be considered as acceptable for an upstream push. And maybe somebody has an even better idea?

**Comment by nordicjm** [comment]
I could see this working if init of GPIO could be "skipped" by the application, though both bootloader and application would need to have the exact same GPIO configuration, maybe by use of retention subsystem so that the bootloader can indicate to the application if GPIO should be initialised or not.

**Comment by benediktibk** [comment]
> I could see this working if init of GPIO could be "skipped" by the application, though both bootloader and application would need to have the exact same GPIO configuration, maybe by use of retention subsystem so that the bootloader can indicate to the application if GPIO should be initialised or not.

Yes, something along this line. Although skipping alone won't be sufficient, as it is also necessary to get the current state of the expander. Information, which could either be read out by the firmware or taken from the bootloader via the retention subsystem.

**Comment by Laczen** [comment]
@benediktibk doesn't something like this exist already. I remember that some user needed a pwm pin output to be retained to avoid a voltage regulator to be powered down (or something similar).

I guess this could be added by looking if the compilation is done for a bootloader or not: if it is a bootloader: reset, if not read and keep the setup. This of course supposes that the bootloader will always set it up.

**Comment by benediktibk** [comment]
> @benediktibk doesn't something like this exist already. I remember that some user needed a pwm pin output to be retained to avoid a voltage regulator to be powered down (or something similar).
> 
> I guess this could be added by looking if the compilation is done for a bootloader or not: if it is a bootloader: reset, if not read and keep the setup. This of course supposes that the bootloader will always set it up.

The detection if it is a bootloader or not is not the big issue. The question is, if such a change of the GPIO driver would be accetable upstream? Because I am trying to stick with vanilla zephyr as close as possible, therefore I would like to avoid to maintain a custom driver version of the port expander.

**Comment by nordicjm** [comment]
@henrikbrixandersen @gmarull

**Comment by Laczen** [comment]
> The detection if it is a bootloader or not is not the big issue. The question is, if such a change of the GPIO driver would be accetable upstream? Because I am trying to stick with vanilla zephyr as close as possible, therefore I would like to avoid to maintain a custom driver version of the port expander.

To me this seems a genuine request. The need to keep pin state retained/pwm output retained/.. during the switch from bootloader to application is something that should be possible. A no-reset flag or something similar seems the simplest solution.

**Comment by benediktibk** [comment]
Thinking about it I am more and more in favor of the approach with the power management. In combination with the retention subsystem the current state could be stored in RAM and read out again during wakeup. This would then solve two issues at once:

- Switch from Bootloader to Firmware
- Wakeup from a very deep sleep state

It would also represent a minimal performance hit during runtime.

**Comment by Laczen** [comment]
> Thinking about it I am more and more in favor of the approach with the power management. In combination with the retention subsystem the current state could be stored in RAM and read out again during wakeup. This would then solve two issues at once:
> 
> * Switch from Bootloader to Firmware
> * Wakeup from a very deep sleep state
> 
> It would also represent a minimal performance hit during runtime.

@benediktibk, I am not in favor of that approach:
a. When this method needs to be extended for other devices it would be needed to be able to uniquely link between the device and the stored state,
b. When retention is used with the prefix to identify the device it is not possible to write firmware that could cover different prefixes: once the prefix is set in the bootloader all applications that are using this should use the same prefix. An application supporting two different prefixes is not supported (at least not at the moment).

**Comment by nordicjm** [comment]
>  b. When retention is used with the prefix to identify the device it is not possible to write firmware that could cover different prefixes: once the prefix is set in the bootloader all applications that are using this should use the same prefix. An application supporting two different prefixes is not supported (at least not at the moment).

How lucky that prefixes aren't picked by a random number generator each time the firmware boots then isn't it!

**Comment by benediktibk** [comment]
I'm uncertain which prefix you are referring to, maybe the device ordinals?

But you are right, there would have to be a mapping between the stored state which would have to be stable not only between reboots of the firmware (deep sleep -> run), but as well from a bootloader to a firmware. I could think of maybe using the string device names, as they should be the same as long as the bootloader and the firmware are using the same devicetree.

@nordicjm It feels like I'm missing a discussion on this topic which went on previously? Maybe you could link, so that I understand the context?

**Comment by benediktibk** [comment]
Thanks for the clarification, I am already aware of the retention system prefix. I just was confused and thought you meant a prefix in the context of the device. And also thanks for the wrap up of the previous discussion, this helps me a lot.

Anyway, I don't want to delve to deep into the history of the retention system and would like to take its current state as given.

> a. When this method needs to be extended for other devices it would be needed to be able to uniquely link between the device and the stored state,

This unique link between the device and the stored data should be achievable, for instance via the device name. Which has to be unique, as far as I understood it. Otherwise device_get_binding wouldn't make much sense.

> When retention is used with the prefix to identify the device it is not possible to write firmware that could cover different prefixes: once the prefix is set in the bootloader all applications that are using this should use the same prefix. An application supporting two different prefixes is not supported (at least not at the moment).

Yes, there has to be a common ground between a bootloader and a firmware about how the device state should be communicated. Having a single prefix given in the devicetree seems to be reasonable to me. But besides this, just taking the retention system as the current state-of-the-art approach to communicate between the bootloader and the firmware, this possible problem is separate from the current issue at hand. I will just be a user of the retention system, and how the retention system is implemented internally should not matter that much in this case.

**Comment by nordicjm** [comment]
Retention subsystem is safe for use however you want to use it, including for implementing this function.

**Comment by benediktibk** [comment]
The discussion moved to the PR #71336
