### ISSUE TITLE
adc_sam0: calibration register macro wrong

### ISSUE THREAD

**Issue by wag-thom** [zephyrproject-rtos/zephyr#62297]
The macro ADC_SAM0_CALIB in [adc_fixup_sam0.h](https://github.com/zephyrproject-rtos/zephyr/blob/a768a05e6205e415564226543cee67559d15b736/soc/arm/atmel_sam0/common/adc_fixup_sam0.h#L77) seems wrong.

The mask used (`ADCx_FUSES_xxx_Msk`) is already left-shifted and should be applied to the raw register value.
But the code shifts the register value first and applies the mask after that.

If I change the order, the calibration gets set correctly on my SAMD51 board.
`( xxx_ADDR & xxx_Msk ) >> xxx_Pos`

**Comment by nandojve** [comment]
Hi @wag-thom ,

Did would like send a fix for this? I think it would be a good start to contribute : )
