### ISSUE TITLE
ssd1306: Addition of M5stack OLED display shield

### ISSUE THREAD

**Issue by rjmaris** [zephyrproject-rtos/zephyr#62300]
**Is your feature request related to a problem? Please describe.**
No, except that a display is owned that should be controlled in Zephyr.

**Describe the solution you'd like**
I have written shield code for this (named) display that should almost be ready as a merge candidate. Main changes are a new overlay file and Kconfig files.

**Additional context**
Because the display has portrait orientation and the `ssd1306` does (yet) not support orientation setting, in the `LVGL sample code` I also added a newline in between the words "hello world!". This should not negatively impact landscape displays.

Please apologize for the patch size which contains an image for the `doc/img` folder.
[0001-boards-shields-ssd1306-add-support-to-M5stack-OLED-d.patch.txt](https://github.com/zephyrproject-rtos/zephyr/files/12524932/0001-boards-shields-ssd1306-add-support-to-M5stack-OLED-d.patch.txt)

**Comment by henrikbrixandersen** [comment]
Please submit proposed code changes in the form of a pull request, not as a feature request with an attached diff.
