### ISSUE TITLE
ESP32S3 build mcuboot error

### ISSUE THREAD

**Issue by sam131208** [zephyrproject-rtos/zephyr#62322]
**Describe the bug**
 An error occurred when I compiled mcuboot.  error is "fatal error: cmsis_core.h: No such file or directory #include <cmsis_core.h>".

**To Reproduce**
1. cd zephyr
2. west build -b esp32s3_devkitm --sysbuild samples/hello_world

**Expected behavior**
build the mcuboot  successful.

**Logs and console output**
.....
Loading Zephyr default modules (Zephyr base).
-- Application: D:/zephyr3/bootloader/mcuboot/boot/zephyr
-- CMake version: 3.22.1
-- Found Python3: C:/Python38/python.exe (found suitable version "3.8.10", minimum required is "3.8") found components: Interpreter
-- Cache files will be written to: D:/zephyr3/zephyr/.cache
-- Zephyr version: 3.4.99 (D:/zephyr3/zephyr)
-- Found west (found suitable version "1.0.0", minimum required is "0.14.0")
-- Board: esp32s3_devkitm
-- ZEPHYR_TOOLCHAIN_VARIANT not set, trying to locate Zephyr SDK
-- Found host-tools: zephyr 0.16.1 (C:/Users/sam/zephyr-sdk-0.16.1)
-- Found toolchain: zephyr 0.16.1 (C:/Users/sam/zephyr-sdk-0.16.1)
-- Found Dtc: C:/ProgramData/chocolatey/bin/dtc.exe (found suitable version "1.5.0", minimum required is "1.4.6")
-- Found BOARD.dts: D:/zephyr3/zephyr/boards/xtensa/esp32s3_devkitm/esp32s3_devkitm.dts
-- Found devicetree overlay: D:/zephyr3/bootloader/mcuboot/boot/zephyr/app.overlay
-- Generated zephyr.dts: D:/zephyr3/zephyr/build/mcuboot/zephyr/zephyr.dts
-- Generated devicetree_generated.h: D:/zephyr3/zephyr/build/mcuboot/zephyr/include/generated/devicetree_generated.h
-- Including generated dts.cmake file: D:/zephyr3/zephyr/build/mcuboot/zephyr/dts.cmake
Parsing D:/zephyr3/bootloader/mcuboot/boot/zephyr/Kconfig
Loaded configuration 'D:/zephyr3/zephyr/boards/xtensa/esp32s3_devkitm/esp32s3_devkitm_defconfig'
Merged configuration 'D:/zephyr3/bootloader/mcuboot/boot/zephyr/prj.conf'
Merged configuration 'D:/zephyr3/bootloader/mcuboot/boot/zephyr/boards/esp32s3_devkitm.conf'
Merged configuration 'D:/zephyr3/zephyr/build/mcuboot/zephyr/.config.sysbuild'
....
[11/16] Performing build step for 'mcuboot'
[4/175] Generating include/generated/version.h
-- Zephyr version: 3.4.99 (D:/zephyr3/zephyr), build: zephyr-v3.4.0-3278-g9a9855f711d0
[104/175] Building C object CMakeFiles/app.dir/main.c.obj
FAILED: CMakeFiles/app.dir/main.c.obj
.....
D:/zephyr3/bootloader/mcuboot/boot/zephyr/main.c:30:10: fatal error: cmsis_core.h: No such file or directory
   30 | #include <cmsis_core.h>
      |          ^~~~~~~~~~~~~~

**Environment (please complete the following information):**
 - OS: Windows
 - Toolchain :Zephyr SDK

**Comment by nordicjm** [comment]
There is a pending change that fixes this https://github.com/mcu-tools/mcuboot/pull/1800

Note @gmarull
