### ISSUE TITLE
Add documentation for new modem subsystem

### ISSUE THREAD

**Issue by kartben** [zephyrproject-rtos/zephyr#62327]
**Is your enhancement proposal related to a problem? Please describe.**

The recently added modem subsystem does not show up in the documentation, making it potentially difficult to know of its existence in the first place, and to learn how to use it for folks who'd be looking for that information.

**Describe the solution you'd like**

* Add documentation in OS Services section of the documentation
* The Doxygen documentation for chat, cmux, etc API, needs to be completed, in particular add groups and make sure they are "mounted" properly in a relevant parent group (`connectivity`?)
   * Please make sure that internal stuff is flagged appropriately (`@cond INTERNAL_HIDDEN`) so that it does not show up in the generated docs, and that all other public API has documentation.
* Update the cellular_modem sample using the change introduced in #62029 (when/if merged) so that it references the doxygen group(s) that are relevant.

**Describe alternatives you've considered**

N/A

**Additional context**

Sligthly related: functions that have multiple return values should use `@retval`, not `@returns` in their Doxygen docstring.

Thanks!

**Comment by bjarki-trackunit** [comment]
Just letting you know I have indeed seen the issue and plan to to start work on the it within a couple of weeks :)

**Comment by bjarki-trackunit** [comment]
In progress #63949

**Comment by bjarki-trackunit** [comment]
@kartben Did you have some more nits before we close this issue? :)

**Comment by kartben** [comment]
Ahah no, thanks, this is great :)
