### ISSUE TITLE
boot_write_img_confirmed not working on stm32g474ce

### ISSUE THREAD

**Issue by st0ne** [zephyrproject-rtos/zephyr#62346]
**Describe the bug**
After updating the firmware with mcuboot and dfu-util the firmware will start after swapping the images.
But it gets Error -5 on confirming the image.

I am using a custom board with stm32g474ce.

**Expected behavior**
confirming the new running image should work as expected.

**Impact**
can not update my firmware after deployment of hardware.

**Logs and console output**
With CONFIG_FLASH_LOG_LEVEL_DBG=y i will get the following output:
```
[00:00:03.030,000] <dbg> flash_stm32: flash_stm32_read: Read offset: 311280, len: 16
 [00:00:03.030,000] <dbg> flash_stm32: flash_stm32_read: Read offset: 311256, len: 1
 [00:00:03.030,000] <dbg> flash_stm32: flash_stm32_read: Read offset: 311264, len: 1
 [00:00:03.030,000] <dbg> flash_stm32: flash_stm32_read: Read offset: 311272, len: 1
 [00:00:03.030,000] <inf> main: Confirming Boot Image
 [00:00:03.030,000] <dbg> flash_stm32: flash_stm32_read: Read offset: 311280, len: 16
 [00:00:03.030,000] <dbg> flash_stm32: flash_stm32_read: Read offset: 311256, len: 1
 [00:00:03.030,000] <dbg> flash_stm32: flash_stm32_read: Read offset: 311264, len: 1
 [00:00:03.030,000] <dbg> flash_stm32: flash_stm32_read: Read offset: 311272, len: 1
 [00:00:03.030,000] <dbg> flash_stm32: flash_stm32_write: Write offset: 311272, len: 8
 [00:00:03.030,000] <dbg> flash_stm32: flash_stm32_write_protection: Disable write protection
 [00:00:03.030,000] <dbg> flash_stm32: flash_stm32_check_status: Status: 0x000000c0
 [00:00:03.030,000] <dbg> flash_stm32: flash_stm32_write_protection: Enable write protection
```

Version: 3.4.0
Git Commit: cb3ae1779f7c814b72df298a41a8b0bc68500ba5

**Comment by nordicjm** [comment]
You have not included the zephyr commit you are using, please update with this information

**Comment by nordicjm** [comment]
CC: @de-nordic

**Comment by st0ne** [comment]
> You have not included the zephyr commit you are using, please update with this information

added the missing information :-)

**Comment by erwango** [comment]
@st0ne Can you provide the flash partition you're using ?
Also, the error you mention doesn't appear clearly in the log. Would you  have a way to provide full extent log ?

**Comment by st0ne** [comment]
@erwango i will try to get a better log. The main error is return of -5 when boot_write_img_confirmed is called. 
Therefore the new image will be switched back after reboot.

flash partition:

`&flash0 {
	partitions {
		compatible = "fixed-partitions";
		#address-cells = <1>;
		#size-cells = <1>;

		boot_partition: partition@0 {
			label = "mcuboot";
			reg = <0x0 DT_SIZE_K(96)>;
			read-only;
		};

		slot0_partition: partition@18000 {
			label = "image-0";
			reg = <0x00018000 DT_SIZE_K(208)>;
		};

		slot1_partition: partition@4C000 {
			label = "image-1";
			reg = <0x0004C000 DT_SIZE_K(208)>;
		};

		/*scratch_partition: partition@70000 {
			reg = <0x00070000 DT_SIZE_K(16)>;
		};*/

		/* Set 4Kb of storage at the end of the 512Kb of flash */
		/*storage_partition: partition@70000 {
			label = "storage";
			reg = <0x00070000 DT_SIZE_K(64)>;
		};*/
	};
};`

**Comment by st0ne** [comment]
no it is not needed anymore. They have a new swap algorithm which does not wear out the flash at the scratch partition.

**Comment by st0ne** [comment]
ah, maybe this could be a reason, i have not used mcumgr. I used to start into the bootloader with a button and then used dfu_util for updating.
Is it in function different than mcumgr?

Reason to do this was because of saving space for the main app.

**Comment by erwango** [comment]
Sorry, I won't be able to help on reasons why it is different.
Anyway, I would tend to close the issue as using mcumgr demonstrates mcuboot is working on G4 with the provided flash partition.
@st0ne Thoughts ?

**Comment by de-nordic** [comment]
> ah, maybe this could be a reason, i have not used mcumgr. I used to start into the bootloader with a button and then used dfu_util for updating. Is it in function different than mcumgr?
> 
> Reason to do this was because of saving space for the main app.

dfu-util works with USB, mcumgr relies on Serial Recovery feature of MCUboot.
USB support in MCUboot make bigger MCUboot, serial recovery is smaller in size.

You upload image using dfu-util and then confirm it using MCUmgr?

**Comment by st0ne** [comment]
I upload the image with dfu-util, which is working. And then after a reboot it should get confirmed when it is running.

The reason for this is, that i have not enough space for my application. In this case, only mcuboot has to do the update and everything elese.

**Comment by erwango** [comment]
@st0ne Is there anything more that can be done or can we close the issue ?

**Comment by st0ne** [comment]
Hi,
did not have time to work on the project for some time. But i got another idea. STM32G474 is dual bank by default. Could this be the reason why it is not working correctly? Do i have to set DBANK=0 before flashing zephyr?
I may have time to test this next week.
