### ISSUE TITLE
ism330dhcx: sensor initialisation fails if sensor is in unknown state

### ISSUE THREAD

**Issue by HenrikKaa** [zephyrproject-rtos/zephyr#62350]
**Describe the bug**
Said sensors initialisation function `ism330dhcx_init_chip` does not work properly if the sensor ends up in some unknown state where it does not function properly. The function tries to first read chip ID which will fail and then fail the initialisation.
An easy fix for this is to move `ism330dhcx_reset_set` before `ism330dhcx_device_id_get`.

**To Reproduce**
No specific reproduce method, the sensor just ended up randomly in a state where all reads return zeros or carbage until power cycling the sensor.

**Expected behavior**
Sensor initialisation should reset badly behaving sensor and carry on with initialisation.

**Impact**
The impact was small because I could power cycle the system but in future that will not be possible and the sensor will get stuck un-initialisable.

**Logs and console output**
None

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: Zephyr SDK
 - Version 3.3.0 (problem persist in newer versions)
 - NXP LPC55S69

**Additional context**
I could have fixed this myself and made a pull request but it is possible that more sensors than this use the same logic and can experience the same issue. Someone should probably look into this.

**Comment by MaureenHelm** [comment]
@avisconti please take a look

**Comment by 03Filip0001** [comment]
Have you found the solution for your problem ?

I have the same problem and I can't understand why.

**Comment by avisconti** [comment]
> Have you found the solution for your problem ?
> 
> I have the same problem and I can't understand why.

Are you able to fix this issue following what is suggested here?
(i.e. moving  ```ism330dhcx_reset_set``` before ```ism330dhcx_device_id_get```)

I don't like this solution, as the current API order is correct to me. But just to understand what's going on...

**Comment by avisconti** [comment]
I'm not able to reproduce it on x_nucleo_iks02a1 shield. I'm using ```samples/shield/x_nucleo_iks02a1/standard``` sample.
I do not know what is happening, but I tend to think that it is not a driver issue, bit more a hardware issue. 
@03Filip0001 can you please add more details on it?

**Comment by 03Filip0001** [comment]
@avisconti 
I opened new issue on my profile and there you can see more info and images of communication.
[https://github.com/03Filip0001/ism330dhcx/issues/1](url)

**Comment by HyperionCoding** [comment]
> Have you found the solution for your problem ?
> 
> I have the same problem and I can't understand why.

We ended up not using the sensor in the end. 

> I'm not able to reproduce it on x_nucleo_iks02a1 shield. I'm using `samples/shield/x_nucleo_iks02a1/standard` sample. I do not know what is happening, but I tend to think that it is not a driver issue, bit more a hardware issue. [@03Filip0001](https://github.com/03Filip0001) can you please add more details on it?

It does not matter if it is HW or SW, the device driver should be able to handle error cases. This overall is my pet peeve with Zephyr, it expects devices to always work and when they don't it's really hard to do anything meaningful to them. Deferred init improved it a bit but device drivers should be more robust.

**Comment by HenrikKaa** [comment]
> Have you found the solution for your problem ?
> 
> I have the same problem and I can't understand why.

We ended up not using the sensor in the end for other reasons.

> I'm not able to reproduce it on x_nucleo_iks02a1 shield. I'm using `samples/shield/x_nucleo_iks02a1/standard` sample. I do not know what is happening, but I tend to think that it is not a driver issue, bit more a hardware issue. [@03Filip0001](https://github.com/03Filip0001) can you please add more details on it?

It does not matter if it is HW or SW, the device driver should be able to handle error cases. This overall is my pet peeve with Zephyr, it expects devices to always work and when they don't it's really hard to do anything meaningful to them. Deferred init improved it a bit but device drivers should be more robust.

**Comment by avisconti** [comment]
> > Have you found the solution for your problem ?
> > I have the same problem and I can't understand why.
> 
> We ended up not using the sensor in the end for other reasons.
> 
> > I'm not able to reproduce it on x_nucleo_iks02a1 shield. I'm using `samples/shield/x_nucleo_iks02a1/standard` sample. I do not know what is happening, but I tend to think that it is not a driver issue, bit more a hardware issue. [@03Filip0001](https://github.com/03Filip0001) can you please add more details on it?
> 
> It does not matter if it is HW or SW, the device driver should be able to handle error cases. This overall is my pet peeve with Zephyr, it expects devices to always work and when they don't it's really hard to do anything meaningful to them. Deferred init improved it a bit but device drivers should be more robust.

Actually it DOES matter if it is h/w or s/w. In the former case, e.g. a bus communication issue, a robust device driver should do nothing more than test the error case and return a failure. I'm not saying it is a h/w issue; what I'm saying is that we need to rule this out first and dig a bit more into it.

**Comment by avisconti** [comment]
@03Filip0001 can you possibly check if #84152 fix this issue? Thanks
