### ISSUE TITLE
"Previous execution" and "Next execution" display problem.

### ISSUE THREAD

**Issue by Jveyrat** [zephyrproject-rtos/zephyr#6240]
IC:
- Have a project with several Test Cycle created inside.

Steps:
- Create several folders under 1 Test Cycle.
- Put some Tests inside those folders.
- Click on "E" to execute a test.

Expected result:
- When selecting a folder, and clicking on "E", the test execution page open, and display 2 arrows for "Next execution" and "Previous execution" to allow navigate on tests.

Actual result:
- When selecting a folder, and clicking on "E", the test execution page open, and the 2 arrows for "Next execution" and "Previous execution" are not visible.

Notes:
The problem don't appears on every folder.
All folders have several Test inside.

Attachment:
<img width="800" alt="step1" src="https://user-images.githubusercontent.com/36534889/36314134-25077758-1334-11e8-87b7-9ba53cdcf403.PNG">
<img width="827" alt="step2" src="https://user-images.githubusercontent.com/36534889/36314135-253ad882-1334-11e8-8d93-bae4497540c8.PNG">
<img width="797" alt="step3" src="https://user-images.githubusercontent.com/36534889/36314136-256eac5c-1334-11e8-915f-91cf5d866ad3.PNG">
<img width="812" alt="step4" src="https://user-images.githubusercontent.com/36534889/36314137-259d0d68-1334-11e8-8d56-1dae859f40d5.PNG">

**Comment by nashif** [comment]
Wrong project, this is not Zephyr, the test framework, this is Zephyr the RTOS.
