### ISSUE TITLE
[RFC][RISCV] Support for multiple instances of multi-level interrupt controller

### ISSUE THREAD

**Issue by ycsin** [zephyrproject-rtos/zephyr#62441]
## Introduction

Hi all, I'm looking at our custom [`intc_plic`](https://github.com/zephyrproject-rtos/zephyr/blob/main/drivers/interrupt_controller/intc_plic.c) implementation and really feel like we should do something upstream to minimize the gap between upstream & our codebase, our [`intc_plic`](https://github.com/zephyrproject-rtos/zephyr/blob/main/drivers/interrupt_controller/intc_plic.c) has some patch to support multi-instance, alongside with some hacks to the RISCV's [`irq_manage.c`](https://github.com/zephyrproject-rtos/zephyr/blob/main/arch/riscv/core/irq_manage.c) to complete that change, all only works under a very specific configurations.

### Problem description

As far as I can tell, Zephyr's build system and/or the RISCV's [`arch_irq_connect_dynamic`](https://github.com/zephyrproject-rtos/zephyr/blob/main/arch/riscv/core/irq_manage.c#L35) install approach do not support such multi-instance & multi-level interrupt controller driver. For [`intc_plic`](https://github.com/zephyrproject-rtos/zephyr/blob/main/drivers/interrupt_controller/intc_plic.c) to support multiple instances, we need to be able to discern the IRQs between the instances, and install them accordingly into the [`_sw_isr_table`](https://github.com/zephyrproject-rtos/zephyr/blob/main/include/zephyr/sw_isr_table.h#L44). To do that we will need to extend the existing LUT in the `sw_isr_common` to record the corresponding interrupt controller device along with its IRQN & ISR table offset.

### Proposed change

Some ideas, starting from the easiest one..

1. Allow soc/driver implementation of the (RISCV's) `arch_irq_connect_dynamic`, to facilitate custom implementation downstream - #62442
2. Update the `sw_isr_common` and headers so that we can discern the parent interrupt controller device from the multi-level IRQN, update `intc_plic` to support multiple instances & pass in unmodified version of the `irq` number from RISCV's `soc_common_irq` when PLIC & multilevel is enabled - https://github.com/zephyrproject-rtos/zephyr/pull/62907

**Comment by ycsin** [comment]
cc @carlocaione @cfriedt @jgl-meta

**Comment by carlocaione** [comment]
Thanks for opening this. A couple of questions:
1. When you say multi-instance & multi-level you mean different interrupt controllers, possibly in cascade managing different IRQ ranges?
2. Why are you interested only in the dynamic IRQs? Isn't this problem also valid for statically installed handlers with `IRQ_CONNECT`?

**Comment by cfriedt** [comment]
The PLIC definitely needs to be made multi-instance (if only to support `build_all` tests with different configurations).

So I agree to that.

I think the scenario that @ycsin is talking about does have more than one "root" interrupt controller while also supporting multi-level interrupts.

To address that, it could be useful to make a variant of `arch_irq_connect_dynamic()`, say `arch_irq_connect_dynamic_dev(..., const struct device *dev)`, such that the former could wrap around the latter. If the `dev` parameter were non-`NULL` it could override whatever interrupt controller is normally used.

However, I'm also interested in the proposal by @dcpleung and @andyross about chained interrupts / a DAG, which is IIRC how it's done in Linux. We may be able to get that done for LTSv3? Hard to say..

**Comment by cfriedt** [comment]
Also, cc @fkokosinski @npitre
