### ISSUE TITLE
too few arguments in invocation of macro "Z_FOR_LOOP_1"

### ISSUE THREAD

**Issue by dpkristensen** [zephyrproject-rtos/zephyr#62460]
**Describe the bug**
When using LOG_* macros with a single argument, linters and compilers at high warning levels can emit show warnings like this:
~~~~
too few arguments in invocation of macro "Z_FOR_LOOP_1"
~~~~

This is mentioned in comments on #21119; the ticket opened in https://github.com/microsoft/vscode-cpptools/issues/9187 was closed due to inactivity.  I don't think it's a problem with cpptools, per se; likely a problem in how the macro is created.

**To Reproduce**
Steps to reproduce the behavior via VS Code:

1. Ensure `ms-vscode.cpptools-extension-pack` is installed.
2. Open vscode to sample app `zephyr/samples/subsys/shell/shell_module`
3. Run the build to generate the configuration: `west build -b nrf52dk_nrf52832`
4. Populate `.vscode/c_cpp_configuration.json` file:
~~~~
{
    "configurations": [
        {
        "name": "Test",
        "compileCommands": "build/compile_commands.json",
        }
    ],
    "version": 4
}
~~~~
5. Open src/main.c and look at the `problems` output

**Expected behavior**
No problems reported

**Impact**
Many problems reported makes it more difficult to find actual problems with the code.

**Logs and console output**
Problems output:
~~~~
too few arguments in invocation of macro "Z_FOR_LOOP_1"
~~~~

**Environment (please complete the following information):**
 - OS: Ubuntu 22.04
 - Toolchain: Zephyr SDK, gcc 11.4.0
 - Zephyr commit 8ea58fc43b77859df713712cc5be2c33a10b0e7e

**Additional context**
I have seen this specifically with nRF Connect SDK v2.2.0 (v3.2.99-ncs1), but the problem is generic to Zephyr code itself.  I was able to reproduce it with Zephyr only using the steps above on a computer in a standalone zephyr installation.

I've narrowed it down to this section of Z_LOG_MSG_CREATE3():
~~~~
	bool has_rw_str = CBPRINTF_MUST_RUNTIME_PACKAGE( \
					Z_LOG_MSG_CBPRINTF_FLAGS(_cstr_cnt), \
					__VA_ARGS__); \
~~~~

It seems there is some old logic in CBPRINTF_MUST_RUNTIME_PACKAGE where it used to take separate fmt and ... args, but now just takes ... instead.  In other parts of this macro, `Z_LOG_FMT_ARGS(_fmt, ##__VA_ARGS__)` is used instead to reduce the number of arguments to just format when there are no subsequent arguments.

There's probably some other history on this, and I haven't had time to dig further.

**Comment by mrclark25** [comment]
This impacts my project as well.

**Comment by ryland-mueller** [comment]
This has been an issue for years, can we please keep this issue open (remove stale label)

**Comment by dpkristensen** [comment]
I don't believe I have access to remove the label or re-open the issue; one of the maintainers will have to do this.

**Comment by nordic-krch** [comment]
Can you check if that was the fix? #46532

**Comment by dpkristensen** [comment]
I applied the change from #46532 and it silenced the warning from the checker.  Also both single and multi-argument versions of LOG_INF() macro produced the expected output.  So I think it will fix it.

**Comment by nordic-krch** [comment]
@dpkristensen @ryland-mueller I've reopened the PR with the fix.
