### ISSUE TITLE
Add partitions to pinetime_devkit0.dts to support MCUboot

### ISSUE THREAD

**Issue by ljunquera** [zephyrproject-rtos/zephyr#62469]
**Is your enhancement proposal related to a problem? Please describe.**
I am trying to get MCUboot to work with the pinetime_devkit0 board and would like the partitions to be added to the dts file, as that is how I understand it should be done.

**Describe the solution you'd like**
Add these partitions to the [pinetime_devkit0.dts](https://github.com/zephyrproject-rtos/zephyr/blob/main/boards/arm/pinetime_devkit0/pinetime_devkit0.dts):

- boot_partition: for MCUboot itself
- slot0_partition: the primary slot of Image 0
- slot1_partition: the secondary slot of Image 0

in the manner described [here](https://github.com/najnesnaj/pinetime-zephyr/blob/b9ed4ff7036cfc4059f52c08527194c602b60288/docs/fota/partitions.md?plain=1#L13).

```
chosen {
        zephyr,flash = &flash0;
        //zephyr,flash = &flash1;
        zephyr,code-partition = &slot0_partition;
};


Rename the SPI JEDEC NOR Flash definition to : flash1

flash1: mx25r6435f@1 {
        compatible = "jedec,spi-nor";
        reg = <1>;
        spi-max-frequency = <80000000>;
        label = "MX25R64";
        jedec-id = [0b 40 16];
        size = <67108864>;
        has-be32k;
        erase-block-size = <4096>;
        write-block-size = <4>;
};




 &flash0 {
        /*
         * For more information, see:
         * http://docs.zephyrproject.org/latest/guides/dts/index.html#flash-partitions
         */
        partitions {
                compatible = "fixed-partitions";
                #address-cells = <1>;
                #size-cells = <1>;

                boot_partition: partition@0 {
                        label = "mcuboot";
                        reg = <0x00000000 0xc000>;
                };
                slot0_partition: partition@c000 {
                        label = "image-0";

                change the size of partition 0 from 0x32000 to 0x64000

                        reg = <0x0000C000 0x64000>;
                };

                move slot1 partition to &flash1

                //slot1_partition: partition@3e000 {
                //      label = "image-1";
                //      reg = <0x0003e000 0x32000>;
                //};
                scratch_partition: partition@70000 {
                        label = "image-scratch";
                        reg = <0x00070000 0xa000>;
                };
                storage_partition: partition@7a000 {
                        label = "storage";
                        reg = <0x0007a000 0x00006000>;
                };
        };
 };

 &flash1 {
        partitions {
                compatible = "fixed-partitions";
                #address-cells = <1>;
                #size-cells = <1>;
                slot1_partition: partition@3e000 {
                        label = "image-1";
                        reg = <0x00000000 0x64000>;
                };
        };
 };
```

**Describe alternatives you've considered**
I have considered making changes in an overlay but got [this feedback](https://discord.com/channels/720317445772017664/884454075595390986/1150084034832117832) from Discord:
"not really no, you would then need to copy these overlays to multiple locations making them error prone either update the original or fork the board (with a modified name) and use the forked board name with the updated partitions"

**Comment by nordicjm** [comment]
The flash partitions for MCUboot including external flash are already part of the board: https://github.com/zephyrproject-rtos/zephyr/blob/main/boards/arm/pinetime_devkit0/pinetime_devkit0.dts
