### ISSUE TITLE
shell: modules: kernel: Human readable uptime

### ISSUE THREAD

**Issue by jeppenodgaard** [zephyrproject-rtos/zephyr#62543]
**Is your enhancement proposal related to a problem? Please describe.**
Kernel uptime is shown in ms. An uptime of 13445303 ms is not easily readable.

**Describe the solution you'd like**
Keep the original functionality and add an option to print the uptime in e.g. day, hours, minutes, seconds, and milliseconds.
Maybe do like [uptime](https://www.man7.org/linux/man-pages/man1/uptime.1.html) -p but with higher resolution.

**Comment by henrikbrixandersen** [comment]
That's a good idea. Please submit a patch for implementing this functionality.
