### ISSUE TITLE
drivers: intc: plic: erroneous calculation of trig register

### ISSUE THREAD

**Issue by ycsin** [zephyrproject-rtos/zephyr#62563]
The address calculation of the `trig` register in the `intc_plic` shouldn't depend on the `PLIC_MAX_PRIO`, specifying the correct address offset in the DT using `riscv,trigger-reg-offset` should be all it takes.

**Comment by henrikbrixandersen** [comment]
Please use our bug template when reporting bugs. You need to edit this issue to include the information requested in https://github.com/zephyrproject-rtos/zephyr/blob/main/.github/ISSUE_TEMPLATE/001_bug_report.md
