### ISSUE TITLE
tests/kernel/mem_protect fails on stm32f746 nucleo: memory partitionning error

### ISSUE THREAD

**Issue by FRASTM** [zephyrproject-rtos/zephyr#62574]
**Describe the bug**
Running the  tests/kernel/mem_protect/userspace/kernel.memory_protection.userspace
The test case fails with an Error due to memory partitionning on the nucleo_f746zg platrform

```
E: no free partition slots available
Failed to add default memory partition (-28)

```

Also seen with samples/userspace/shared_mem/sample.kernel.memory_protection.shared_mem/
```
*** Booting Zephyr OS build zephyr-v3.4.0-3504-ga532dbab510f ***
ENC Thread Created 0x200114a0
E: num_parts of 4 exceeds maximum allowable partitions (3)
ASSERTION FAIL [ret == 0] @ WEST_TOPDIR/zephyr/samples/userspace/shared_mem/src/main.c:144
k_mem_domain_init() on enc_domain failed -22
E: r0/a1:  0x00000004  r1/a2:  0x00000090  r2/a3:  0x40004800
E: r3/a4:  0x00000000 r12/ip:  0x2001081c r14/lr:  0x08008dbb
E:  xpsr:  0x61000000
E: Faulting instruction address (r15/pc): 0x08008dd4
E: >>> ZEPHYR FATAL ERROR 4: Kernel panic on CPU 0
E: Current thread: 0x20011630 (main)
E: Halting system
```

Is this a regression ? seems to be related to  commits
 - f0daf904bb0202c9247cdcf4d1186e0762a9db67
 and/or
 - 844c78cf3a7e16d7ff016a7b88d405068c241be6
 

**To Reproduce**
1. west build -p always -b nucleo_f746zg tests/kernel/mem_protect/userspace/
2. west flash
3. See error

**Expected behavior**
`PROJECT EXECUTION SUCCESSFUL`

**Impact**
CI test failure

**Logs and console output**
```
Running TESTSUITE userspace_domain_ctx
===================================================================
START - test_domain_add_part_context_switch
E: no free partition slots available
Assertion failed at WEST_TOPDIR/zephyr/tests/kernel/mem_protect/userspace/src/main.c:779: userspace_domain_ctx_test_domain_add_part_context_switch: (k_mem_domain_add_partition(&k_mem_domain_default, &alt_part) not equal to 0)
failed to add memory partition
FAIL - test_domain_add_part_context_switch in 0.027 seconds
===================================================================
START - test_domain_add_thread_context_switch
PASS - test_domain_add_thread_context_switch in 0.001 seconds
===================================================================
START - test_domain_remove_part_context_switch
E: no matching partition found
Assertion failed at WEST_TOPDIR/zephyr/tests/kernel/mem_protect/userspace/src/main.c:800: userspace_domain_ctx_test_domain_remove_part_context_switch: (k_mem_domain_remove_partition(&k_mem_domain_default, &alt_part) not equal to 0)
failed to remove memory partition
FAIL - test_domain_remove_part_context_switch in 0.027 seconds
===================================================================
TESTSUITE userspace_domain_ctx failed.

```

**Environment (please complete the following information):**
 - OS: ubuntu
 - Toolchain Zephyr SDK 0.16.1
 - Commit SHA 07ece0cb1dfa9a1aaf7af3fe94792cc3b7572fa0

**Additional context**
Add any other context that could be relevant to your issue, such as pin setting,
target configuration, ...

**Comment by fabiobaltieri** [comment]
@keith-packard could you look into this? Looks like it's been rootcaused to the picolibc commit

**Comment by keith-packard** [comment]
I don't think I have this particular board, so I can't directly evaluate the issue. I can this of a couple of possible causes:

 1. Default malloc arena. Minimal libc has a zero-sized arena, picolibc has a non-zero sized. You can check this by forcing the arena to zero size under.
 2. thread local storage. https://github.com/zephyrproject-rtos/zephyr/pull/62319 allows you to disable this while using picolibc.

Both of these generate additional memory partitions which might be causing this issue? I fixed numerous test issues caused by assumptions in the code about the precise memory configuration provided in the minimal C library build, I suspect this is likely to have a similar cause.

If there's some way I can test this, let me know. I have a stack of nucleo and disco boards here, but not this particular one, alas.

**Comment by keith-packard** [comment]
In the case of thread local storage on targets without a TLS base register, like many small single-core ARM SoCs, the TLS base pointer is saved in memory in the z_libc_partition, and that partition doesn't contain anything else. Is there some other partition, shared between kernel and user space, which could be used to hold this value? Creating a partition for a single integer doesn't seem ideal.

**Comment by FRASTM** [comment]
Setting the `CONFIG_COMMON_LIBC_MALLOC_ARENA_SIZE=0`  for the nucleo_f746zg board is not enough. The quadspi_memory `compatible = "zephyr,memory-region"` also has to be removed from the dts/arm/st/f7/stm32f7.dtsi  to PASS the test

**Comment by FRASTM** [comment]
not failing since Zephyr v3.6.0-rc3
