### ISSUE TITLE
STM32G0 flash driver error

### ISSUE THREAD

**Issue by andy3469** [zephyrproject-rtos/zephyr#62581]
**Describe the bug**
The regs variable is not defined on [Line 234](https://github.com/zephyrproject-rtos/zephyr/blob/9f52fac1eaed7bd34fb5fd072176ca8f3e1d909c/drivers/flash/flash_stm32g0x.c#L234C49-L234C49) of the flash driver for STM32G0 MCUs.

**Impact**
The code can't be built with this issue.

**How to solve**
Replace `if ((regs->OPTR & FLASH_OPTR_DUAL_BANK) == 0)` with `if ((FLASH->OPTR & FLASH_OPTR_DUAL_BANK) == 0)`

**Comment by erwango** [comment]
Thanks @andy3469 for spotting this.
Would you be able to send a PR to fix this ?

**Comment by erwango** [comment]
Fixed by https://github.com/zephyrproject-rtos/zephyr/pull/62626
