### ISSUE TITLE
wifi_mgmt: `struct wifi_scan_params` is now very large

### ISSUE THREAD

**Issue by JordanYates** [zephyrproject-rtos/zephyr#62584]
**Is your enhancement proposal related to a problem? Please describe.**

With the addition of #60686, the `struct wifi_scan_params` field is now huge, over 1kB.
This makes it very awkward to create an instance of this in a function call.

The `chan` parameter is extremely un-optimised. According to my count of [Wikipedia](https://en.wikipedia.org/wiki/List_of_WLAN_channels):
* 2.4 GHz band has 14 channels. (219 wasted slots)
* 5 GHz band has 31 channels. (201 wasted slots)
* 6 GHz band has 60 channels. (173 wasted slots)

`WIFI_CHANNEL_MAX` is not the correct define to be using in the instantiation of this array.

**Describe the solution you'd like**

The structure should not be larger than many thread stacks.

**Describe alternatives you've considered**

There are a few options, which can be mixed and matched.

* Immediately swap `WIFI_CHANNEL_MAX` to 60 (`WIFI_CHANNEL_NUM_ASSIGNED`)
* Split the bands into separate arrays so 2.4 GHz doesn't pay the cost of 5GHz channels
* Use defines to compress the structure to only assigned channels.
* Use a bitmask to specify channels instead of integers.

Implementing all of these suggestions would reduce the `chan` field to 14 bytes, down from 932.

An alternative solution would be to encode the band into the top 2 bits of the 16bit channel number, and then provide a single Kconfig option which defines the maximum length of a single array (`uint16_t chans[CONFIG_MAX_SCAN_CHANNELS]`)

**Comment by JordanYates** [comment]
@sachinthegreen

**Comment by jukkar** [comment]
Very good points, I have to say I missed the memory usage problem during the review, sorry about that :disappointed:
