### ISSUE TITLE
Incorrect function signature for ADC data acquisition threads

### ISSUE THREAD

**Issue by benediktibk** [zephyrproject-rtos/zephyr#62637]
Data acquisition threads for ADCs usually have the incorrect function signature. Examples are:

- https://github.com/zephyrproject-rtos/zephyr/blob/94cc1bf4551a933200f1f65777a19869264bc5bf/drivers/adc/adc_ads1119.c#L436
- https://github.com/zephyrproject-rtos/zephyr/blob/94cc1bf4551a933200f1f65777a19869264bc5bf/drivers/adc/adc_ads114s0x.c#L1066
- https://github.com/zephyrproject-rtos/zephyr/blob/94cc1bf4551a933200f1f65777a19869264bc5bf/drivers/adc/adc_ads1x1x.c#L540
- https://github.com/zephyrproject-rtos/zephyr/blob/94cc1bf4551a933200f1f65777a19869264bc5bf/drivers/adc/adc_ads7052.c#L222

They all have one parameter, but the thread entry function pointer is defined as:

    typedef void (*k_thread_entry_t)(void *p1, void *p2, void *p3);

Therefore these functions would corrupt the stack if they would return, which they luckily won't ever do.

I'm uncertain if this is intended, but I wanted to at least mentioned this imperfection.

**Comment by fabiobaltieri** [comment]
@benediktibk would you be better off opening a PR to fix the functions if you have a chance?
