### ISSUE TITLE
Bluetooth: Host: Possibly race condition between GAP and L2CAP

### ISSUE THREAD

**Issue by Thalley** [zephyrproject-rtos/zephyr#62645]
**Describe the bug**
In a babblesim test implemented in https://github.com/zephyrproject-rtos/zephyr/pull/62604, I noticed the error log `<err> bt_conn: bt_conn_send_cb: not connected!` appears. 

It appears at a point where

1. The ACL has just disconnected
2. The peripheral restarted advertising
3. The central restarted scanning
4. On connection complete, the central will (based on an `atomic` flag) disconnect the ACL immediately
5. The `<err> bt_conn: bt_conn_send_cb: not connected!` comes while the ACL is in the `BT_CONN_DISCONNECTING` state

During the last ACL connection (where the issue happens), the application does nothing. The issue is trigger because `bt_conn_send_cb` is called from `bt_l2cap_send_cb`. 

The only idea I for what triggers it, is that `CONFIG_BT_GATT_AUTO_UPDATE_MTU=y` which triggers an GATT MTU exchange when the ACL has been connected. 

**To Reproduce**
1. Build `tests/bsim/bluetooth/audio` 
2. Run `tests/bsim/bluetooth/audio/test_scripts/bap_unicast_audio_acl_disconnect.sh` from https://github.com/zephyrproject-rtos/zephyr/pull/62604
3. See error

**Expected behavior**
Expect that the stack does not generate any `<err>` log entries when the application does nothing but simply disconnecting a connection. 

**Impact**
Minor as it just triggers an error log statement. 

**Logs and console output**
```
d_01: @00:00:11.663950  Restarting ext_adv after disconnect
d_00: @00:00:12.115379  Device found: E9:10:C0:CC:5C:05 (random) (RSSI -59)
d_00: @00:00:12.115379  Found ASCS with announcement type 0x01, sink ctx 0x0006, source ctx 0x0006
d_00: @00:00:12.115379  Stopping scan
d_00: @00:00:12.335962  MTU exchanged
d_00: @00:00:12.335962  Connected to E9:10:C0:CC:5C:05 (random)
d_00: @00:00:12.335962  [00:00:12.335,937] <dbg> bt_has: connected: conn 0x8209f80 err 0
d_01: @00:00:12.335962  Connected to CC:AB:C3:77:B1:7A (random)
d_01: @00:00:12.335962  [00:00:12.335,937] <dbg> bt_has: connected: conn 0x8209f80 err 0
d_01: @00:00:12.336091 INFO: PASSED: Unicast server ACL disconnect  passed
d_00: @00:00:12.339329  [00:00:12.339,324] <err> bt_conn: bt_conn_send_cb: not connected!
d_00: @00:00:12.339329  MTU exchanged
d_00: @00:00:12.339329  [00:00:12.339,324] <wrn> bt_gatt: gatt_exchange_mtu_func: conn 0x8209f80 err 0x0e
d_00: @00:00:12.339329  [00:00:12.339,324] <dbg> bt_bap_unicast_client: unicast_client_disconnected: conn 0x8209f80 reason 0x16
d_00: @00:00:12.339329  [00:00:12.339,324] <dbg> bt_bap_unicast_client: unicast_client_ep_reset: conn 0x8209f80
d_00: @00:00:12.339329  [00:00:12.339,324] <dbg> bt_bap_unicast_client: unicast_client_reset: ep 0x820ffe0
d_00: @00:00:12.339329  [00:00:12.339,324] <dbg> bt_bap_unicast_client: unicast_client_ep_set_status: ep 0x820ffe0 handle 0x0000 id 0x00 dir Unknown state idle -> idle
d_00: @00:00:12.339329  [00:00:12.339,324] <dbg> bt_bap_unicast_client: unicast_client_reset: ep 0x821017c
d_00: @00:00:12.339329  [00:00:12.339,324] <dbg> bt_bap_unicast_client: unicast_client_ep_set_status: ep 0x821017c handle 0x0000 id 0x00 dir Unknown state idle -> idle
d_00: @00:00:12.339329  [00:00:12.339,324] <dbg> bt_bap_unicast_client: unicast_client_reset: ep 0x8210318
d_00: @00:00:12.339329  [00:00:12.339,324] <dbg> bt_bap_unicast_client: unicast_client_ep_set_status: ep 0x8210318 handle 0x0000 id 0x00 dir Unknown state idle -> idle
d_00: @00:00:12.339329  [00:00:12.339,324] <dbg> bt_bap_unicast_client: unicast_client_reset: ep 0x82104b4
d_00: @00:00:12.339329  [00:00:12.339,324] <dbg> bt_bap_unicast_client: unicast_client_ep_set_status: ep 0x82104b4 handle 0x0000 id 0x00 dir Unknown state idle -> idle
d_00: @00:00:12.339329  Disconnected: E9:10:C0:CC:5C:05 (random) (reason 0x16)
d_00: @00:00:12.339329  [00:00:12.339,324] <dbg> bt_has: disconnected: conn 0x8209f80 reason 22
d_00: @00:00:12.340149 INFO: PASSED: Unicast client ACL disconnect passed
d_01: @00:00:12.339514  [00:00:12.339,508] <wrn> bt_gatt: gatt_exchange_mtu_func: conn 0x8209f80 err 0x0e
d_01: @00:00:12.339514  Disconnected: CC:AB:C3:77:B1:7A (random) (reason 0x13)
d_01: @00:00:12.339514  [00:00:12.339,508] <dbg> bt_has: disconnected: conn 0x8209f80 reason 19
d_01: @00:00:12.339514  Restarting ext_adv after disconnect
```

**Environment (please complete the following information):**
 - Commit SHA or Version used: https://github.com/zephyrproject-rtos/zephyr/pull/62604 based on a6540164d44d1f7d2715280cf1dc0bc40a6c423f

**Additional context**
N/A

**Comment by jori-nordic** [comment]
![image](https://github.com/zephyrproject-rtos/zephyr/assets/68428270/7dcca8ef-c1ec-43d3-bd4f-dba23cf18fde)

stacktrace.
So it's responding to an ATT REQ too late, after `bt_conn_disconnect` has been called, but before its ATT bearer has been destroyed.
