### ISSUE TITLE
printf not linked correctly in armclang

### ISSUE THREAD

**Issue by tejlmand** [zephyrproject-rtos/zephyr#62677]
**Describe the bug**
The  commit f623fcf3987cb35d73e1e5537822da5af865269f (#61423) causes hello world to not function properly when building with armclang toolchain.

Works with previous commit: 42ddc614b1a513497da449a25607e574fe33ea48

**To Reproduce**
1. git checkout f623fcf3987cb35d73e1e5537822da5af865269f 
2. export ZEPHYR_TOOLCHAIN_VARIANT=armclang
3. cmake -DBOARD=qemu_cortex_m3 -Bbuild samples/hello_world
4. ninja -Cbuild run

**Expected behavior**
Actual output:
```
[113/114] To exit from QEMU enter: 'CTRL+a, x'[QEMU] CPU: cortex-m3
qemu-system-arm: warning: nic stellaris_enet.0 has no peer
*** Booting Zephyr OS build zephyr-v3.4.0-2462-gf623fcf3987 ***
qemu-system-arm: terminating on signal 2
```

Expected output:
```
113/114] To exit from QEMU enter: 'CTRL+a, x'[QEMU] CPU: cortex-m3
qemu-system-arm: warning: nic stellaris_enet.0 has no peer
*** Booting Zephyr OS build zephyr-v3.4.0-2461-g42ddc614b1a ***
Hello World! qemu_cortex_m3
qemu-system-arm: terminating on signal 2
```

**Impact**

**Logs and console output**
See above

**Environment (please complete the following information):**
 - OS: Linux, ubuntu
 - Toolchain: ARM Compiler v6, 6.20
 - Commit SHA or Version used: f623fcf3987cb35d73e1e5537822da5af865269f 

**Additional context**
N/A

**Comment by ithinuel** [comment]
Hello, I replicated the issue and can confirm this is a (missing) retargetting issue.
The current build links to fputc relying on semi-hosting to work.

I have a fix under tests. You can expect a PR fixing this in the next coming days.
