### ISSUE TITLE
ESP32: FLASH_SIZE should be in kB

### ISSUE THREAD

**Issue by horakdavid** [zephyrproject-rtos/zephyr#62696]
**Describe the bug**
`CONFIG_FLASH_SIZE` symbol should be set to flash size in kB, but on all esp32 boards the value is in bytes.

**Comment by henrikbrixandersen** [comment]
Please use our bug template when reporting bugs. You need to edit this issue to include the information requested in https://github.com/zephyrproject-rtos/zephyr/blob/main/.github/ISSUE_TEMPLATE/001_bug_report.md
