### ISSUE TITLE
upsquared: tests/kernel/threads/dynamic_thread_stack fails

### ISSUE THREAD

**Issue by KamilxPaszkiet** [zephyrproject-rtos/zephyr#62714]
**Describe the bug**
Out of 10 tests in the test suite, 2 fail.
`tests/kernel/threads/dynamic_thread_stack/kernel.threads.dynamic_thread.stack.pool.alloc.user`
and
`tests/kernel/threads/dynamic_thread_stack/kernel.threads.dynamic_thread.stack.pool.no_alloc.user`
timeout.

**To Reproduce**
```twister --device-testing --hardware-map up2.map -T tests/kernel/threads/dynamic_thread_stack/ -vv```

**Logs and console output**
kernel.threads.dynamic_thread.stack.pool.alloc.user:
```
DEBUG   - DEVICE: *** Zephyr EFI Loader ***
DEBUG   - DEVICE: RSDP found at 0x79c34000
DEBUG   - DEVICE: Zeroing 11214848 bytes of memory at 0x11f000
DEBUG   - DEVICE: Zeroing 2816 bytes of memory at 0xdfa500
DEBUG   - DEVICE: Copying 32768 data bytes to 0x1000 from image offset
DEBUG   - DEVICE: Copying 126976 data bytes to 0x100000 from image offset 32768
DEBUG   - DEVICE: Copying 2266368 data bytes to 0xbd1000 from image offset 159744
DEBUG   - DEVICE: Jumping to Entry Point: 0x1153 (48 31 c0 48 31 d2 48)
DEBUG   - DEVICE: *** Booting Zephyr OS build zephyr-v3.5.0-553-g96c5052733be ***
DEBUG   - DEVICE: Running TESTSUITE dynamic_thread_stack
DEBUG   - DEVICE: ===================================================================
DEBUG   - DEVICE: START - test_dynamic_thread_stack_alloc
DEBUG   - DEVICE: HHeelllloo,,  ddyynnaammiicc  wwoorrlldd!!
DEBUG   - Timed out while monitoring serial output on up_squared
```
kernel.threads.dynamic_thread.stack.pool.no_alloc.user:
```
DEBUG   - DEVICE: *** Zephyr EFI Loader ***
DEBUG   - DEVICE: RSDP found at 0x79c34000
DEBUG   - DEVICE: Zeroing 11214848 bytes of memory at 0x11f000
DEBUG   - DEVICE: Zeroing 2816 bytes of memory at 0xdfa500
DEBUG   - DEVICE: Copying 32768 data bytes to 0x1000 from image offset
DEBUG   - DEVICE: Copying 126976 data bytes to 0x100000 from image offset 32768
DEBUG   - DEVICE: Copying 2266368 data bytes to 0xbd1000 from image offset 159744
DEBUG   - DEVICE: Jumping to Entry Point: 0x1153 (48 31 c0 48 31 d2 48)
DEBUG   - DEVICE: *** Booting Zephyr OS build zephyr-v3.5.0-553-g96c5052733be ***
DEBUG   - DEVICE: Running TESTSUITE dynamic_thread_stack
DEBUG   - DEVICE: ===================================================================
DEBUG   - DEVICE: START - test_dynamic_thread_stack_alloc
DEBUG   - DEVICE: SKIP - test_dynamic_thread_stack_alloc in 0.001 seconds
DEBUG   - DEVICE: ===================================================================
DEBUG   - DEVICE: START - test_dynamic_thread_stack_pool
dEBUG   - DEVICE: HelHleol,l od,y ndaymniacm iwco rwlodr!l
DEBUG   - Timed out while monitoring serial output on up_squared
```
**Expected behavior**
kernel.threads.dynamic_thread.stack.pool.alloc.user:
```
DEBUG   - DEVICE: Running TESTSUITE dynamic_thread_stack
DEBUG   - DEVICE: ===================================================================
DEBUG   - DEVICE: START - test_dynamic_thread_stack_alloc
DEBUG   - DEVICE: HHeelllloo,,  ddyynnaammiicc  wwoorrlldd!!
DEBUG   - DEVICE: 
DEBUG   - DEVICE: PASS - test_dynamic_thread_stack_alloc in 0.005 seconds
DEBUG   - DEVICE: ===================================================================
DEBUG   - DEVICE: START - test_dynamic_thread_stack_pool
DEBUG   - DEVICE: SKIP - test_dynamic_thread_stack_pool in 0.001 seconds
DEBUG   - DEVICE: ===================================================================
DEBUG   - DEVICE: TESTSUITE dynamic_thread_stack succeeded
DEBUG   - DEVICE: 
DEBUG   - DEVICE: ------ TESTSUITE SUMMARY START ------
DEBUG   - DEVICE: 
DEBUG   - DEVICE: SUITE PASS - 100.00% [dynamic_thread_stack]: pass = 1, fail = 0, skip = 1, total = 2 duration = 0.006 seconds
DEBUG   - DEVICE: - PASS - [dynamic_thread_stack.test_dynamic_thread_stack_alloc] duration = 0.005 seconds
DEBUG   - DEVICE: - SKIP - [dynamic_thread_stack.test_dynamic_thread_stack_pool] duration = 0.001 seconds
DEBUG   - DEVICE: 
DEBUG   - DEVICE: ------ TESTSUITE SUMMARY END ------
DEBUG   - DEVICE: 
DEBUG   - DEVICE: ===================================================================
DEBUG   - DEVICE: RunID: f4f320d6a3804509ae7a33c0c3b14855
DEBUG   - DEVICE: PROJECT EXECUTION SUCCESSFUL
```
kernel.threads.dynamic_thread.stack.pool.no_alloc.user:
```
DEBUG   - DEVICE: Running TESTSUITE dynamic_thread_stack
DEBUG   - DEVICE: ===================================================================
DEBUG   - DEVICE: START - test_dynamic_thread_stack_alloc
DEBUG   - DEVICE: SKIP - test_dynamic_thread_stack_alloc in 0.001 seconds
DEBUG   - DEVICE: ===================================================================
DEBUG   - DEVICE: START - test_dynamic_thread_stack_pool
DEBUG   - DEVICE: HHeelllloo,,  ddyynnaammiicc  wwoorrlldd!!
DEBUG   - DEVICE: 
DEBUG   - DEVICE: PASS - test_dynamic_thread_stack_pool in 0.005 seconds
DEBUG   - DEVICE: ===================================================================
DEBUG   - DEVICE: TESTSUITE dynamic_thread_stack succeeded
DEBUG   - DEVICE: 
DEBUG   - DEVICE: ------ TESTSUITE SUMMARY START ------
DEBUG   - DEVICE: 
DEBUG   - DEVICE: SUITE PASS - 100.00% [dynamic_thread_stack]: pass = 1, fail = 0, skip = 1, total = 2 duration = 0.006 seconds
DEBUG   - DEVICE: - SKIP - [dynamic_thread_stack.test_dynamic_thread_stack_alloc] duration = 0.001 seconds
DEBUG   - DEVICE: - PASS - [dynamic_thread_stack.test_dynamic_thread_stack_pool] duration = 0.005 seconds
DEBUG   - DEVICE: 
DEBUG   - DEVICE: ------ TESTSUITE SUMMARY END ------
DEBUG   - DEVICE: 
DEBUG   - DEVICE: ===================================================================
DEBUG   - DEVICE: RunID: ebb362fb39b57d9c85d8660fa58c5510
DEBUG   - DEVICE: PROJECT EXECUTION SUCCESSFUL
```

**Environment:**
- OS: Ubuntu
- Toolchain: zephyr-sdk-0.16.3
- zephyr-v3.5.0-553-g96c5052733be

**Comment by nashif** [comment]
@KamilxPaszkiet  that log you provide does not show any failures, it shows tests passing, please provide accurate logs of the test that is failing.

**Comment by KamilxPaszkiet** [comment]
This [PR](https://github.com/zephyrproject-rtos/zephyr/pull/64362) fix this issue

**Comment by jhedberg** [comment]
@KamilxPaszkiet I don't see any errors when running this test app multiple times with the latest tree (just building the full app and booting it through USB on my up_squared board):
```
------ TESTSUITE SUMMARY START ------

SUITE PASS - 100.00% [dynamic_thread_stack]: pass = 1, fail = 0, skip = 1, total = 2 duration = 0.005 seconds
 - SKIP - [dynamic_thread_stack.test_dynamic_thread_stack_alloc] duration = 0.001 seconds
 - PASS - [dynamic_thread_stack.test_dynamic_thread_stack_pool] duration = 0.004 seconds

------ TESTSUITE SUMMARY END ------

===================================================================
PROJECT EXECUTION SUCCESSFUL
```
I don't have a way to run this with twister however. Could this be an issue with your test harness? Upstream doesn't seem have any documentation or claimed support for any `twister --device-testing` features with this board, so if it's an issue with your setup then an upstream GitHub issue is probably not the right place for this report.

**Comment by KamilxPaszkiet** [comment]
> @KamilxPaszkiet I don't see any errors when running this test app multiple times with the latest tree (just building the full app and booting it through USB on my up_squared board):
> 
> ```
> ------ TESTSUITE SUMMARY START ------
> 
> SUITE PASS - 100.00% [dynamic_thread_stack]: pass = 1, fail = 0, skip = 1, total = 2 duration = 0.005 seconds
>  - SKIP - [dynamic_thread_stack.test_dynamic_thread_stack_alloc] duration = 0.001 seconds
>  - PASS - [dynamic_thread_stack.test_dynamic_thread_stack_pool] duration = 0.004 seconds
> 
> ------ TESTSUITE SUMMARY END ------
> 
> ===================================================================
> PROJECT EXECUTION SUCCESSFUL
> ```
> 
> I don't have a way to run this with twister however. Could this be an issue with your test harness? Upstream doesn't seem have any documentation or claimed support for any `twister --device-testing` features with this board, so if it's an issue with your setup then an upstream GitHub issue is probably not the right place for this report.

You checked the wrong tests, the problem occurs in:
`tests/kernel/threads/dynamic_thread_stack/kernel.threads.dynamic_thread.stack.pool.no_alloc.user`
and
`tests/kernel/threads/dynamic_thread_stack/kernel.threads.dynamic_thread.stack.pool.alloc.user`

**Comment by jhedberg** [comment]
@KamilxPaszkiet thanks, I can see the issue now

**Comment by jhedberg** [comment]
@KamilxPaszkiet and now the issue is gone. Maybe merging #65428 fixed this one as well for `up_squared`. Could you try with latest main branch?

**Comment by KamilxPaszkiet** [comment]
> @KamilxPaszkiet and now the issue is gone. Maybe merging #65428 fixed this one as well for `up_squared`. Could you try with latest main branch?

You're right, the problem has been fixed. I'm closing the issue.
