### ISSUE TITLE
lvgl: Input subsys port possibly not working as expected.

### ISSUE THREAD

**Issue by jakkra** [zephyrproject-rtos/zephyr#62754]
**Describe the bug**
- Scrolling a list of items sometimes triggers unexpected/accidental clicks on the items in the list.
- I think there is a bug/problem in the input port that feeds LVGL with touch input.
- Possibly due to the change from kscan to input subsys.

Initially I had the issue using the `input_cst816s.c` but I can also reproduce the issue in `native_posix` using SDL, so it's likely not a driver issue.

I have made modifications to the https://github.com/zephyrproject-rtos/zephyr/tree/main/samples/subsys/display/lvgl sample in order to reproduce. Just replace the [main.c](https://github.com/zephyrproject-rtos/zephyr/blob/main/samples/subsys/display/lvgl/src/main.c) with [this main.c](https://gist.github.com/jakkra/1e75712a8ed69645351b0fc5684137d8)

I have tested this sample application using:
- Zephyr 3.4.0 (LVGL 8.2.0) => Working as expected
- Zephyr (almost main 4cf5d5cf8b84221310677706441b9324d04521d7) (LVGL 8.3.7) => **Not** working as expected
- LVGL PC Simulator (LVGL 8.3.7) => Working as expected

The above tests does indicate the issue is not in the updated LVGL version, but in the Zephyr port.
My suspicion is that it's due to the new input subsys that replaced kscan for LVGL input handling, but it's more of a guess. 

One random idea/guess is that in the new input subsys it's feeding X, Y and button press as three different events and not as one, maybe this could cause LVGL to think there was a click? https://github.com/zephyrproject-rtos/zephyr/blob/main/drivers/input/input_sdl_touch.c#L25-L27

**To Reproduce**
1. Replace main.c in https://github.com/zephyrproject-rtos/zephyr/tree/main/samples/subsys/display/lvgl [with this main.c](https://gist.github.com/jakkra/1e75712a8ed69645351b0fc5684137d8)
2. west build -b native_posix
3. west build -t run
4. Use your mouse and scroll the list. Notice the behavior of clicks during scrolling.

**Expected behavior**
No clicks triggering on list items during scrolling of the list.

**Impact**
LVGL not working good for input on main

**Logs and console output**
Here is a screen recording of the three different versions listed above.
First thing I do is to click on a list item, after than I only scroll the list. Expected behaviour is one initial print of a item click.
[Screencast from 2023-09-18 00:44:42.webm](https://github.com/zephyrproject-rtos/zephyr/assets/4318648/6412d123-1eb9-4ed7-8dc3-f16a21a84bd9)

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: zephyr-sdk-0.16.1
 - Commit SHA or Version used: 4cf5d5cf8b84221310677706441b9324d04521d7

**Additional context**
Note that LVGL input does not work on current main due to https://github.com/zephyrproject-rtos/zephyr/issues/62753, so test with the commit I specified as that's before the breaking change.

**Comment by faxe1008** [comment]
@jakkra I think that it's a side effect of this:
[issues/62512#issuecomment-1714402271](https://github.com/zephyrproject-rtos/zephyr/issues/62512#issuecomment-1714402271). 

I will ping you in the PR that hopefully also fixes your issue.
