### ISSUE TITLE
assert when running sys_kernel on disco_l475_iot1 (with asserts enabled)

### ISSUE THREAD

**Issue by nashif** [zephyrproject-rtos/zephyr#6276]
add CONFIG_ASSERT=y, build and flash on device:

```
disco_l475_iot1           tests/benchmarks/sys_kernel/test                   building
MAKE: 'sanity_test_finished disco_l475_iot1/tests/benchmarks/sys_kernel/test'
DEVICE: ASSERTION FAIL [sys_clock_hw_cycles_per_tick <= (1 << 24)] @ /home/nashif/Work/github/zephyr/drivers/timer/cortex_m_systick.c:714:

```

**Comment by nashif** [comment]
actually this looks like a common problem, not only on disco_l475_iot1, I was able to reproduce on frdm_k64f as well.

**Comment by MaureenHelm** [comment]
Yes, this is a problem for any ARM platform running over 16 MHz. The test tries to eliminate timer interrupts by setting `CONFIG_SYS_CLOCK_TICKS_PER_SEC=1`, which overflows the systick timer. Can we run this test in tickless mode instead?

**Comment by nashif** [comment]
can't reproduce anymore.
