### ISSUE TITLE
samples: subsys: pm: device_pm: sample.power.ospm.dev_idle_pm fails

### ISSUE THREAD

**Issue by katgiadla** [zephyrproject-rtos/zephyr#62772]
**Describe the bug**
The test `sample.power.ospm.dev_idle_pm` fails.

Observed for:
- `nrf52dk_nrf52832`
- `nrf52840dk_nrf52840`

**To Reproduce**
1. have `nrf52840dk_nrf52840` connected
2. go to your zephyr dir
3. call `./scripts/twister -T samples/subsys/pm/device_pm/ -p nrf52840dk_nrf52840 --device-testing --device-serial /dev/ttyACM0 -v --inline-logs`
4. See console output with error

**Expected behavior**
Valid console output

**Impact**
Not clear

**Logs and console output**
```
[2023-09-18T03:40:26.192Z] ERROR   - parent not found
[2023-09-18T03:40:26.192Z] child suspending..
[2023-09-18T03:40:26.192Z] parent suspending..
[2023-09-18T03:40:26.192Z] *** Booting Zephyr OS build zephyr-v3.4.0-3830-gad8f3e5b4e28 ***
[2023-09-18T03:40:26.192Z] Device PM sample app start
[2023-09-18T03:40:26.192Z] child resuming..
[2023-09-18T03:40:26.192Z] Dummy device resumed
```

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04.1 LTS
 - Toolchain Zephyr SDK 0.16.0
 - Commit SHA or Version used: zephyr-v3.4.0-3830-gad8f3e5b4e28

**Comment by gmarull** [comment]
could you send a PR deleting such sample? it looks like it adds no value, there are already tests and docs covering the same functionality.

**Comment by nashif** [comment]
commit that broke this:

4dd7bc997ffa6480afea93bb47236df04d36f7c4

**Comment by nashif** [comment]
> could you send a PR deleting such sample? it looks like it adds no value, there are already tests and docs covering the same functionality.

There is value and probably it needs some love. I do not understand why it was locked on nordic hardware, this sample runs fine in qemu.
