### ISSUE TITLE
drivers: i2c: stm32: Power management doesn't work correctly with PM_DEVICE_RUNTIME enabled

### ISSUE THREAD

**Issue by coran21** [zephyrproject-rtos/zephyr#62790]
**Describe the bug**
I'm still not sure if there is some hidden meaning for the multiple usage of `pm_device_runtime_get` which I believe is wrong.

File `i2c_ll_stm32.c`, function  `i2c_stm32_transfer`

```
        ret = pm_device_runtime_get(dev);
	if (ret < 0) {
		return ret;
	}

	/* Send out messages */
	k_sem_take(&data->bus_mutex, K_FOREVER);

	/* Prevent driver from being suspended by PM until I2C transaction is complete */
#ifdef CONFIG_PM_DEVICE_RUNTIME
	(void)pm_device_runtime_get(dev);
#else
	pm_device_busy_set(dev);
#endif

	current = msg;

	while (num_msgs > 0) {
		uint8_t *next_msg_flags = NULL;

		if (num_msgs > 1) {
			next = current + 1;
			next_msg_flags = &(next->flags);
		}
		ret = stm32_i2c_transaction(dev, *current, next_msg_flags, slave);
		if (ret < 0) {
			break;
		}
		current++;
		num_msgs--;
	}

#ifdef CONFIG_PM_DEVICE_RUNTIME
	(void)pm_device_runtime_put(dev);
#else
	pm_device_busy_clear(dev);
#endif

	k_sem_give(&data->bus_mutex);

	return ret;
}

```

You can see that in this code `pm_device_runtime_get` is called twice, but `pm_device_runtime_put` only once. This makes the power management in my opinion not working correctly.

Please also mention any information which could help others to understand
the problem you're facing:
 - What target platform are you using?
   STM32L4R5
 - What have you tried to diagnose or workaround this issue?
   Yes, removing the first `pm_device_runtime_get` would help.

**To Reproduce**
1. enable runtime power management, set sleep pins for I2C
2. work with EEPROM

**Expected behavior**
EEPROM works correctly

**Impact**
EEPROM doesn't work correctly

**Environment (please complete the following information):**
 - OS:  Linux
 - Toolchain (e.g Zephyr SDK, ...):  Zephyr SDK
 - Commit SHA or Version used

I can prepare a PR with a fix if it's really a bug.

**Comment by erwango** [comment]
Thanks for raising this. That's indeed a genuine bug. A PR would be welcome to fix it.
