### ISSUE TITLE
Networking API documentation reordering

### ISSUE THREAD

**Issue by tbursztyka** [zephyrproject-rtos/zephyr#6281]
In doxygen part, Network API should be reordered:
- those who belong to user API (socket, net mgmt, packet and buf, and higher level protocols such as coap, mqtt, http...)
- rest being part of core stack APIs (udp, ipv4/6, 15.4, l2, etc...)

Looks like we have namespace issues as well (2 15.4 library though one is the l2 part, one is the net mgmt part). Http seems to be out of the networking apis, in root level of apis (as kernel apis) also.

**Comment by jukkar** [comment]
I think we have this covered atm so closing.
