### ISSUE TITLE
rx_timeout_slab shouldn't consider CONFIG_SYS_CLOCK_TICKS_PER_SEC when hardware timers are used

### ISSUE THREAD

**Issue by pres2300** [zephyrproject-rtos/zephyr#62828]
**Describe the bug**
Small `rx_timeout` values can cause spurious `UART_RX_RDY` events when using ASYNC UART.

Please also mention any information which could help others to understand
the problem you're facing:
 - What target platform are you using?
 nRF52840

 - What have you tried to diagnose or workaround this issue?
 Yes, more details below

**To Reproduce**
1. Enable the following options in the prj.conf file:
```
CONFIG_UART_ASYNC_API=y
CONFIG_UART_0_ASYNC=y
CONFIG_UART_0_NRF_HW_ASYNC=y
CONFIG_UART_0_NRF_HW_ASYNC_TIMER=0
```

2. When setting up the async uart, use a timeout smaller than `( 3000000 / CONFIG_SYS_CLOCK_TICKS_PER_SEC)*5`.
3. Send a large packet size to the device (multiple may be required to observe the issue)

**Expected behavior**
`UART_RX_RDY` event only occurs when the internal DMA buffer switches to the next prepared buffer OR the timeout occurs.

**Impact**
You cannot determine the end of received data with an ASYNC UART using `UART_RX_RDY` because the event will sometimes happen at the incorrect time.

**Environment (please complete the following information):**
 - OS: macOS
 - Toolchain: Zephyr SDK, nRF SDK 2.3.0

**Additional context**

From looking at the code, the current code implementation in `uart_nrfx_uarte.c` (referenced below) can potentially set `rx_timeout_slab` to a much greater value than `rx_timeout` if `CONFIG_SYS_CLOCK_TICKS_PER_SEC` is a relatively low value.  I've noticed that when this happens you can get spurious `UART_RX_RDY` events.  That can be explained due to these lines of code (1045-1055):

```
               if (clipped ||
			(data->async->rx_timeout_left
				< data->async->rx_timeout_slab)) {
			/* rx_timeout us elapsed since last receiving */
			notify_uart_rx_rdy(dev, len);
			data->async->rx_offset += len;
			data->async->rx_total_user_byte_cnt += len;
		} else {
			data->async->rx_timeout_left -=
				data->async->rx_timeout_slab;
		}
```

The `else` condition above will set `rx_timeout_left` to a much smaller value than expected causing `notify_uart_rx_rdy` to be called on the next iteration.

This can be fixed by modifying the lines where `rx_timeout_slab` gets set to check for the use of hardware timers.  I'm assuming that when hardware timers are used the consideration for sys tick time need not be made.  I ran a test on my setup by quickly changing the code to set `rx_timeout_slab` to the following:
`data->async->rx_timeout_slab = timeout / RX_TIMEOUT_DIV;`

It appears to work, but I'm not sure how best to check for the use of hardware timers in all scenarios to make an official fix for this issue (nor if my understanding is good enough that I could make a fix that wouldn't impact other users of the driver).

https://github.com/zephyrproject-rtos/zephyr/blob/2ea2d37d60ada33bdf051eb9d699f4db9123c3ff/drivers/serial/uart_nrfx_uarte.c#L855

**Comment by henrikbrixandersen** [comment]
If you are reporting a bug (difficult to tell from the description above), please use our bug template. You can edit this issue to include the information requested in https://github.com/zephyrproject-rtos/zephyr/blob/main/.github/ISSUE_TEMPLATE/001_bug_report.md

**Comment by anangl** [comment]
> From looking at the code, the current code implementation in `uart_nrfx_uarte.c` (referenced below) can potentially set `rx_timeout_slab` to a much greater value than `rx_timeout` if `CONFIG_SYS_CLOCK_TICKS_PER_SEC` is a relatively low value. I've noticed that when this happens you can get spurious `UART_RX_RDY` events. That can be explained due to these lines of code (1045-1055):
> 
> [..]
> 
> The `else` condition above will set `rx_timeout_left` to a much smaller value than expected causing `notify_uart_rx_rdy` to be called on the next iteration.

The actual problem here is that when `rx_timeout_slab` is greater than `rx_timeout_left` (and it can be because of that rounding up to 3 system clock ticks), the timeout is reported (i.e. the `UART_RX_RDY` is generated) in every entry to the `rx_timeout` function, even if new data is continuously received. And this is obviously not the way that `UART_RX_RDY` is supposed to be used.

> This can be fixed by modifying the lines where `rx_timeout_slab` gets set to check for the use of hardware timers. I'm assuming that when hardware timers are used the consideration for sys tick time need not be made.

This assumption is incorrect. Hardware timers are used (as counters) for counting of incoming bytes, not for checking the RX timeouts - for this, always the kernel timers are used.

> I ran a test on my setup by quickly changing the code to set `rx_timeout_slab` to the following:
> `data->async->rx_timeout_slab = timeout / RX_TIMEOUT_DIV;`
> 
> It appears to work, but I'm not sure how best to check for the use of hardware timers in all scenarios to make an official fix for this issue

Yes, that works and it should be used always, no matter if a hardware timer is used for counting of incoming bytes or not.
