### ISSUE TITLE
nRF53: Workaround for network core malfunction after CPU sleep

### ISSUE THREAD

**Issue by cvinayak** [zephyrproject-rtos/zephyr#62871]
**Describe the bug**
nRF53 Symptoms: Network core behaves erratically.

Refer to: https://infocenter.nordicsemi.com/topic/errata_nRF5340_Rev1/ERR/nRF5340/Rev1/latest/anomaly_340_165.html

**To Reproduce**
See above reference link.

**Expected behavior**
Application on nRF53 APP Core and Network Core function as  per expectation of the designed application requirements.

**Impact**
showstopper

**Logs and console output**
NA

**Environment (please complete the following information):**
 - OS: (e.g. Linux, MacOS, Windows)
 - Toolchain (e.g Zephyr SDK, ...)
 - Commit SHA or Version used

**Additional context**
NA

**Comment by carlescufi** [comment]
Fixed by https://github.com/zephyrproject-rtos/zephyr/pull/63148
