### ISSUE TITLE
[build][interrupts] Configurable number of bits for multi-level interrupts

### ISSUE THREAD

**Issue by ycsin** [zephyrproject-rtos/zephyr#62883]
**Describe the bug**
#61050 introduced the support of configurable bitmasks for multi-level interrupt, however, Zephyr's [`gen_defines.py`](https://github.com/zephyrproject-rtos/zephyr/blob/main/scripts/dts/gen_defines.py) script still expects each level to be 8, see: still hardcoding the number of bits for the levels, i.e.:

https://github.com/zephyrproject-rtos/zephyr/blob/1fc16e65656e742fbe0adc89e0fdf685c51525a5/scripts/dts/gen_defines.py#L462-L468

This results in incorrectly encoded IRQ number from DT macros like `DT_INST_IRQN`:

https://github.com/zephyrproject-rtos/zephyr/blob/1fc16e65656e742fbe0adc89e0fdf685c51525a5/drivers/serial/uart_ns16550.c#L1248

And may cause issues in build-time installed ISRs, i.e. IRQ collision / installing ISR to the wrong offset / mismatch between static and dynamic IRQN.

**To Reproduce**
1. Use anything after #61050 - cce530cae4cac4ac46d5c932267d8156377578bd
2. Use a board with `MULTI_LEVEL_INTERRUPTS` enabled
3. Configure the 1st level interrupt bits to anything other than 8

**Expected behavior**
Zephyr should build and work normally for any plausible value of 1st level interrupt bits

**Impact**
This can be a showstopper for boards that requires the 1st level interrupt bits to be something other than 8

**Environment (please complete the following information):**
 - Zephyr rev: cce530cae4cac4ac46d5c932267d8156377578bd

**Comment by cfriedt** [comment]
This technically would fall into the category of a bug. Can you grab the template for a bug report and update the description?

**Comment by cfriedt** [comment]
@fabiobaltieri @jhedberg - this will be pretty critical for functional risc-v plic.
