### ISSUE TITLE
k_timer_start asserts when called from multiple preemptive contexts

### ISSUE THREAD

**Issue by nordic-krch** [zephyrproject-rtos/zephyr#62908]
**Describe the bug**
`k_timer_start` documentation does not mention that it cannot be called from multiple preemptive contexts for the same instance. However, application may stop on an assert if one `k_timer_start` is preempted by another.

Please also mention any information which could help others to understand
the problem you're facing:
 - What target platform are you using?
 - What have you tried to diagnose or workaround this issue?
 - Is this a regression? If yes, have you been able to "git bisect" it to a
   specific commit?
 - ...

**To Reproduce**
1. Use modified hello_world from here: https://github.com/zephyrproject-rtos/zephyr/compare/main...nordic-krch:zephyr:timeout_assert
2. Compile it for `qemu_cortex_m3`
3. Run it for few seconds and observe following assert:
`ASSERTION FAIL [!sys_dnode_is_linked(&to->node)] @ WEST_TOPDIR/zephyr/kernel/timeout.c:110`

**Expected behavior**
Application should not fail.

**Environment (please complete the following information):**
 - Os: Linux
 - Toolchain: 0.16.1
 - Commit SHA: b0f92e13b92e5a3d54f2d3694f623aef7cf71f72

**Additional context**
It seems that the reason why assert is hit is that timer is started in a following way:
- previous timer is aborted https://github.com/zephyrproject-rtos/zephyr/blob/f74bbc8d4886c445ce12d00e11bbd363834932cd/kernel/timer.c#L157
- new values for timer are set (not under lock)
- assert checks that `timeout` is not active - not in list) https://github.com/zephyrproject-rtos/zephyr/blob/f74bbc8d4886c445ce12d00e11bbd363834932cd/kernel/timeout.c#L110
- new timeout is set (under lock)

If context is preempted after timer is aborted but before assert and in that new context same time is started then assert will be triggered.

**Comment by sousapedro596** [comment]
Created a Pull Request (https://github.com/zephyrproject-rtos/zephyr/pull/63491) to address this issue. Implemented a spinlock in `k_timer_start` to resolve the race condition. It's my first PR to the project, feedback is highly appreciated! Thank you.
