### ISSUE TITLE
userspace: support MMU-based memory virtualization

### ISSUE THREAD

**Issue by andrewboie** [zephyrproject-rtos/zephyr#6291]
Container issue; split into various MMU/VM related stories

- [ ] Virtualize address space, 2G/2G user/kernel VM split
- [ ] New APIs for supporting Zephyr "processes" which have their own VM, multiple Zephyr threads per process.
- [ ] Deprecate Memory Domains for MMU systems.
- [ ] ASLR
- [ ] Separately loaded position-independent application binaries loaded at runtime
- [ ] NuttX style demand paging
- [ ] x86: SMEP/SMAP

**Comment by Deliver88** [comment]
Is there any activity to support container for Zephyr, e.g. approaches like BalenaEngine?

**Comment by andrewboie** [comment]
> Hello, is there any activity to support container for Zephyr, e.g. approaches like BalenaEngine?

No this is not currently planned.

**Comment by Deliver88** [comment]
> > Hello, is there any activity to support container for Zephyr, e.g. approaches like BalenaEngine?
> 
> No this is not currently planned.

Hi, thank you for the answer. Is there references how to setup/run a container on Zephyr? Thanks a lot

**Comment by andrewboie** [comment]
> Is there references, ideas or approaches how to setup/run a container on Zephyr? Thanks a lot

There's no container support on Zephyr and nobody has indicated plans to investigate doing so.

**Comment by Deliver88** [comment]
> > Is there references, ideas or approaches how to setup/run a container on Zephyr? Thanks a lot
> 
> There's no container support on Zephyr and nobody has indicated plans to investigate doing so.

thank you very much for answering! 

Is there an alternative / possibility in Zephyr to separate / hide applications from each other? container-like

**Comment by andrewboie** [comment]
@Deliver88 what we have right now is documented here:

https://docs.zephyrproject.org/latest/reference/usermode/index.html

Provided virtual memory spaces for devices with an MMU and introducing the concept of Zephyr processes, is the next step and is being looked at this winter.

**Comment by Deliver88** [comment]
> @Deliver88 what we have right now is documented here:
> 
> https://docs.zephyrproject.org/latest/reference/usermode/index.html
> 
> Provided virtual memory spaces for devices with an MMU and introducing the concept of Zephyr processes, is the next step and is being looked at this winter.

@andrewboie thanks a lot, it sounds good :)

**Comment by nashif** [comment]
AFAIK most of this was done in the context of other issues/enhancements
