### ISSUE TITLE
drivers: ieee802154: improved driver support for enhanced ACK IE offloading

### ISSUE THREAD

**Issue by fgrandel** [zephyrproject-rtos/zephyr#62940]
**Problem Description**

As has been pointed out in #61227, configuring IE offloading for enhanced ACK IEs could be improved to make it easier for drivers that do not want to implement their own IE parser/writer internally by introducing improved types and appropriate helpers to be re-used across all drivers (optionally including nRF5).

In #61227 this was referred to as "moving soft MAC parts out of proprietary drivers into cross-vendor L2 callbacks".

**Proposed Solution**

In the context of #50336 (TSCH roadmap) many types and IE parser/writer helpers need to be introduced into L2 (soft MAC). Some of these are immediately relevant to #61227 and make it easier for other drivers to support CSL IE offloading. More specifically the existing implementation could be moved forward immediately by providing more structured IE types that help driver maintainers to construct CSL IEs with little effort. Later on in the TSCH roadmap, additional writers and parsers will be introduced that will make it even easier to support IE offloading in any driver.

Here some sample code how this could be used in TSCH context also showcasing the "unfiltered address" proposal:

```c
	if (ieee802154_radio_get_hw_capabilities(iface) & IEEE802154_HW_RX_TX_ACK) {
		/* Inject Time Correction IE to be used in enhanced ACK packets
		 * for offloading of synchronization if the driver implements
		 * auto-ACK, see section 6.5.4.3.
		 */
		struct ieee802154_header_ie header_ie = {
			.type = IEEE802154_IE_TYPE_HEADER,
			.length = sizeof(struct ieee802154_header_ie_time_correction)};
		struct ieee802154_config config;

		ieee802154_header_ie_set_element_id(
			&header_ie, IEEE802154_HEADER_IE_ELEMENT_ID_TIME_CORRECTION_IE);

		/* The time correction IE is to be injected in all enhanced ACK
		 * frames.
		 */
		config = (struct ieee802154_config){
			.ack_ie = {.header_ie = &header_ie,
				   .short_addr = IEEE802154_BROADCAST_ADDRESS},
		};
		(void)ieee802154_radio_configure(iface, IEEE802154_CONFIG_ENH_ACK_HEADER_IE,
						 &config);
	}
```

**Possible Alternatives**

nRF5's IE parser/writer could be ported out of the driver internals and placed into a cross-vendor layer shared by OT and native L2. The nRF5 IE parser/write is however less generic and complete than the one required for TSCH so it probably makes more sense to either keep it in parallel or successively replace it as additional re-usable helpers are introduced into Zephyr. These helpers already exist in the [TSCH development branch](https://github.com/fgrandel/zephyr/tree/feat/ieee802154-tsch-ie-support) and can be previewed there, see `ieee802154_frame_ie.*`.

**Additional Context**

The changes proposed in this enhancement are a precondition to support hardware offloading for ACK IE injection in TSCH. Additionally, the TSCH roadmap not only introduces IEs specific to TSCH but will immediately provide types also that help to offload other IEEE 802.15.4 timing sensitive protocols that involve IE signaling in enhanced ACKs (one of which is CSL).

**Comment by fgrandel** [comment]
@edmont @jciupis @rlubos Another enhancement proposal, this time for improved (more flexible) enhanced ACK IE offloading. This is a precondition for TSCH support, too, but is more generally useful than that. PR follows as soon as the two blocking PRs #62413 and #62503. You can preview the proposed change here: https://github.com/fgrandel/zephyr/commit/e70933b9914687a437dcf90f88b90f885cb6f5c7

**Comment by Prasanna1717** [comment]
Hello sir,
From my understanding, the problem is about the `CONFIG_GPIO_SCH311X` configuration not being enabled for the `nrf_sch311x` board. To resolve this issue, the GPIO driver for the SCH311X chip needs to be enabled for the `nRF Connect SCH311x` board.

To fix this issue, we need to enable the CONFIG_GPIO_SCH311X configuration option for the nrf_sch311x board. This can be done by editing the board's **Kconfig. board** file. I guess this code snippet which help you enable it.

     config BOARD_NRF_SCH311X
     bool "nRF Connect SCH311x"
     source "drivers/gpio/Kconfig.gpio"
     config GPIO_SCH311X
     bool "GPIO Driver for SCH311X"
     select GPIO
     help
     Enable the GPIO driver for SCH311X

If I'm correct I can make a PR regarding this after some testing is done Locally. If I misunderstood the problem, You can let me know, I try my best to work on it.
Thank You

Regards 
Prasanna
