### ISSUE TITLE
lpcxpresso55s69: Support for the flash hardware is broken

### ISSUE THREAD

**Issue by butok** [zephyrproject-rtos/zephyr#62963]
**Describe the bug**
If to enable the FLASH support for lpcxpresso55s69 or lpcxpresso55s16 , an application is stuck and never reaches its main() function.

**To Reproduce**
1. Use zephyr\samples\basic\blinky sample example.
2. Enable the FLASH hardware support in the application, by adding CONFIG_FLASH=y to the project configuration. 
5. Build and run it for lpcxpresso55s69_cpu0 or lpcxpresso55s16.
6. The application is stuck and never reaches its main() function.

If to delete CONFIG_FLASH=y, the application is functional as expected.

**Expected behavior**
Enabling of FLASH should not break the application functionality.

**Impact**
Any application, that requires the FLASH support, is not functional.

**Logs and console output**
N/A

**Environment**

OS: Windows
Toolchain: Zephyr SDK 0.16.1
Commit: bf830ba780b8a76bf8962857b72b551c41f628ee Date: 9/22/2023

**Additional context**
N/A

**Comment by danieldegrasse** [comment]
I've bisected this issue down to c6e3bac4f20a659. It appears the LPC55S69 requires the CPU core clock be less than 100MHz when flash operations are being performed:
![image](https://github.com/zephyrproject-rtos/zephyr/assets/34665051/997635d7-ab73-44dc-a0e5-2b53886918e9)
(section 5.3 of the LPC55S69 reference manual)

**Comment by butok** [comment]
The #62963 is flash initialization issue. No write/erase is done yet.

**Comment by danieldegrasse** [comment]
@butok This is a good point- however, I see flash API tests able to pass prior to c6e3bac. I wonder if the issue is that we call the `flash_init` ROM API during flash init? Perhaps the ROM code there runs into issues if the clock is over 100MHz. The SDK `FLASH_Init` function seems to suggest 96MHz is expected: https://github.com/zephyrproject-rtos/hal_nxp/blob/master/mcux/mcux-sdk/drivers/iap1/fsl_iap.c#L237

**Comment by butok** [comment]
Hi Daniel (@danieldegrasse )

>  I see flash API tests able to pass
What test application are you using?

>The SDK FLASH_Init function seems to suggest 96MHz
It is true. Checked on practice for LPC55S69, it should be <100 for a flash write.
But for reading, it had no issue.

Now, I am working on LPC55S36 & FLASH & MCUboot. I have  a working prototype, I need to prepare/clean code for upstreaming and to add final improvements.
When it is finished (during next week), I will switch to this LPC55S69/16/06 issue.

BTW: 55S69/16/06 and 55S36 are too different. 
Do we want to split them to separate source files to have cleaner code and to avoid repetitive #ifdef ?

**Comment by danieldegrasse** [comment]
> What test application are you using?

`tests/drivers/flash/common`

> BTW: 55S69/16/06 and 55S36 are too different.
Do we want to split them to separate source files to have cleaner code and to avoid repetitive #ifdef ?

Yes, we should probably split the SOC initialization for the LPC5536 into another file, if that is what you mean.

**Comment by butok** [comment]
Tested on my side, on LPC55S16/69. 
Confirm, it is fixed.
