### ISSUE TITLE
send_sd_response() passing a NULL in6_addr* to net_if_ipv6_select_src_addr() accessing invalid memory and causing fault

### ISSUE THREAD

**Issue by chmorgan** [zephyrproject-rtos/zephyr#63066]
mdns_responder.c:374 is passing a NULL in6_addr* for *dst* to net_if_ipv6_select_src_addr() if the family is not AF_INET6. net_if_ipv6_select_src_addr() dereferences this null and accesses invalid memory (causing an MPU fault on my system)

https://github.com/zephyrproject-rtos/zephyr/blob/f1bf05e63a5447c7a935c371d22182a80319c08a/subsys/net/ip/net_if.c#L2867
```

	if (!net_ipv6_is_ll_addr(dst) && !net_ipv6_is_addr_mcast_link(dst)) {
		/* If caller has supplied interface, then use that */
		if (dst_iface) {
			src = net_if_ipv6_get_best_match(dst_iface, dst,
```

net_ipv6_is_ll_addr() is https://github.com/zephyrproject-rtos/zephyr/blob/f1bf05e63a5447c7a935c371d22182a80319c08a/include/zephyr/net/net_ip.h#L839:

```
static inline bool net_ipv6_is_ll_addr(const struct in6_addr *addr)
{
	return UNALIGNED_GET(&addr->s6_addr16[0]) == htons(0xFE80);
}
```

It's this dereference of 'addr' (which is dst and 0x0 in net_if_ipv6_select_src_addr()) that triggers the MPU fault (afaict).

Using stm32h723, zephyr 3.4 (checked on zephyr main and no changes are present to either of these lowest level functions to adjust, although its possible higher level changes have fixed this issue). I *thought* this worked with 3.2 but again I'm not judging the change that broke things, it could be more correct this way but not fully plumbed up, or an unintended side effect.

zephyr 3.2 had different code in v3.2:

https://github.com/zephyrproject-rtos/zephyr/blob/4256cd41df6c60f1832fd2deb14edc30ac7debab/subsys/net/lib/dns/mdns_responder.c#L374
```
	if (IS_ENABLED(CONFIG_NET_IPV6)) {
		/* Look up the local IPv6 address */
		addr6 = net_if_ipv6_select_src_addr(net_pkt_iface(pkt),
						    (struct in6_addr *)ip_hdr->ipv6->src);
	}
```

vs. 3.4 which passes null (which may be more correct for sure but that NULL is what causes the crash):
https://github.com/zephyrproject-rtos/zephyr/blob/356c8cbe63ae01b3ab438382639d25bb418a0213/subsys/net/lib/dns/mdns_responder.c#L374
```
	if (IS_ENABLED(CONFIG_NET_IPV6)) {
		/* Look up the local IPv6 address */
		addr6 = net_if_ipv6_select_src_addr(iface,
			family == AF_INET6 ? (struct in6_addr *)src_addr : NULL);
	}
```

**To Reproduce**
1. Enable mdns responder
2. Enable ipv4 and ipv6 support
3. Attach to Ethernet with mdns traffic

**Expected behavior**
I'd hope it wouldn't crash at the least. I don't understand the issue and its solution well enough yet to say more here.

**Impact**
Showstopper here. I'll have to disable ipv6 support I think so I can continue.

**Logs and console output**

```
00:00:00.014,000] <inf> main: registering shell command
[00:00:02.636,000] <inf> dhcp: IPv4 address: 192.168.1.168
[00:00:02.636,000] <inf> dhcp: Lease time: 83627 seconds
[00:00:02.636,000] <inf> dhcp: Subnet: 255.255.255.0
[00:00:02.636,000] <inf> dhcp: Router: 192.168.1.1
[00:00:26.266,000] <err> os: ***** MPU FAULT *****
[00:00:26.266,000] <err> os:   Data Access Violation
[00:00:26.266,000] <err> os:   MMFAR Address: 0x0
[00:00:26.266,000] <err> os: r0/a1:  0x24002cf8  r1/a2:  0x00000000  r2/a3:  0x00000000
[00:00:26.266,000] <err> os: r3/a4:  0x00000000 r12/ip:  0x240090bc r14/lr:  0x08028b9b
[00:00:26.266,000] <err> os:  xpsr:  0x610f0000
[00:00:26.266,000] <err> os: Faulting instruction address (r15/pc): 0x080148da
[00:00:26.266,000] <err> os: >>> ZEPHYR FATAL ERROR 19: Unknown error on CPU 0
[00:00:26.266,000] <err> os: Current thread: 0x24003de0 (rx_q[0])
[00:00:26.354,000] <err> os: Halting system
```

**Environment (please complete the following information):**
- OS: osx
- Toolchain: zephyr-sdk-0.16.0
- Commit: commit 356c8cbe63ae01b3ab438382639d25bb418a0213 (HEAD, tag: zephyr-v3.4.0, tag: v3.4.0, manifest-rev)

**Comment by jukkar** [comment]
The code was changed in #56973. I did not quite catch the purpose of the changes to `net_if_ipvX_select_src_addr()` in the PR so my change below is probably way off. Anyway, lets start with something here, there are four calls to `net_if_ipvX_select_src_addr()` in this file, the latter two are in `send_sd_response()` where I imagine this might solve the issue
```
diff --git a/subsys/net/lib/dns/mdns_responder.c b/subsys/net/lib/dns/mdns_responder.c
index 0542acad78..864f643b38 100644
--- a/subsys/net/lib/dns/mdns_responder.c
+++ b/subsys/net/lib/dns/mdns_responder.c
@@ -361,14 +363,16 @@ static void send_sd_response(struct net_context *ctx,
 
        if (IS_ENABLED(CONFIG_NET_IPV4)) {
                /* Look up the local IPv4 address */
-               addr4 = net_if_ipv4_select_src_addr(iface,
-                       family == AF_INET ? (struct in_addr *)src_addr : NULL);
+               addr4 = family == AF_INET ?
+                       net_if_ipv4_select_src_addr(iface,
+                                                   (struct in_addr *)src_addr) : NULL;
        }
 
        if (IS_ENABLED(CONFIG_NET_IPV6)) {
                /* Look up the local IPv6 address */
-               addr6 = net_if_ipv6_select_src_addr(iface,
-                       family == AF_INET6 ? (struct in6_addr *)src_addr : NULL);
+               addr6 = family == AF_INET6 ?
+                       net_if_ipv6_select_src_addr(iface,
+                                                   (struct in6_addr *)src_addr) : NULL;
        }
 
        ret = dns_sd_query_extract(dns_msg->msg,
```

But that would not work for the calls in `send_response()`. Regardless of what the correct fix is, the destination address cannot be null when calling `net_if_ipv6_select_src_addr()`

@pdgendt can you take a look and suggest a proper fix for this one?

**Comment by pdgendt** [comment]
@chmorgan thanks for the detailed report!

If submitted a fix PR #63081 to prevent the crash from occurring.

@jukkar I'm not entirely sure how the mDNS specification want us to handle A type queries on IPv6 addresses or AAAA type queries on IPv4 addresses.

**Comment by pdgendt** [comment]
@jukkar I've created a PR #63084 to allow mixing IPv4/IPv6 requests.

**Comment by pdgendt** [comment]
@chmorgan can you confirm that #63084 fixes your issue and the behavior is as expected.

**Comment by chmorgan** [comment]
@pdgendt thank you for taking a look at this. I was only testing that the code didn't crash but I can test tomorrow, US eastern time, to confirm that's fixed and the system responds to the proper mdns name.
