### ISSUE TITLE
it8xxx2_evb: kernel: tests/kernel/interrupt/ Timeout in arch.shared_interrupt

### ISSUE THREAD

**Issue by pkunieck** [zephyrproject-rtos/zephyr#63114]
**Describe the bug**
During test run on it8xxx2_evb platform, there is a timeout in new test case added recently. This is output from git bisect:

127696383f5f7707bd95fca21ecf347b7fecfd40 is the first bad commit
commit 127696383f5f7707bd95fca21ecf347b7fecfd40
Author: Laurentiu Mihalcea <laurentiu.mihalcea@nxp.com>
Date:   Fri Aug 11 15:41:51 2023 +0300

    tests: kernel: interrupt: Add testcase for shared interrupts
    
    This commit introduces a new testcase for shared interrupts.
    
    Signed-off-by: Laurentiu Mihalcea <laurentiu.mihalcea@nxp.com>

 tests/kernel/interrupt/CMakeLists.txt           |   5 +
 tests/kernel/interrupt/src/dynamic_shared_irq.c | 227 ++++++++++++++++++++++++
 tests/kernel/interrupt/src/static_shared_irq.c  |  96 ++++++++++
 tests/kernel/interrupt/src/test_shared_irq.h    |  69 +++++++
 tests/kernel/interrupt/testcase.yaml            |  16 ++
 5 files changed, 413 insertions(+)
 create mode 100644 tests/kernel/interrupt/src/dynamic_shared_irq.c
 create mode 100644 tests/kernel/interrupt/src/static_shared_irq.c
 create mode 100644 tests/kernel/interrupt/src/test_shared_irq.h

**To Reproduce**
1. cd <path/to>zephyrproject/zephyr
2. source zephyr-env.sh
3. twister --device-testing --hardware-map <path/to>/map.yaml -T tests/kernel/interrupt/ -vv

**Expected behavior**
Test pass or is skipped 

**Impact**
annoyance 

**Logs and console output**
DEBUG   - Timed out while monitoring serial output on it8xxx2_evb
DEBUG   - Expected suite names:['interrupt_feature', 'shared_irq_feature', 'interrupt_feature', 'shared_irq_feature']
DEBUG   - Detected suite names:['interrupt_feature', 'shared_irq_feature']
DEBUG   - run status: it8xxx2_evb/tests/kernel/interrupt/arch.shared_interrupt failed
INFO    - 4/5 it8xxx2_evb               tests/kernel/interrupt/arch.shared_interrupt        FAILED Timeout (device 75.194s)

**Environment (please complete the following information):**
- OS: Linux
- Toolchain Zephyr SDK 16.1

**Comment by fabiobaltieri** [comment]
@pkunieck would you be able to debug this on the board and see if there's something that could be fixed in general or send a PR to exclude this test for the specific paltform if that's appropriate?

**Comment by pkunieck** [comment]
There are additional logs from this test, looks like maybe ITE board does not waking up after interrupt? This test works fine on simulator(quemu). Logs: 
DEBUG   - DEVICE: ***** delaying boot 1ms (per build configuration) *****
DEBUG   - DEVICE: *** Booting Zephyr OS build v3.5.0-rc1-85-g6552e05100aa (delayed boot 1ms) ***
DEBUG   - DEVICE: Running TESTSUITE interrupt_feature
DEBUG   - DEVICE: ===================================================================
DEBUG   - DEVICE: START - test_isr_dynamic
DEBUG   - DEVICE: installing dynamic ISR for IRQ 0
DEBUG   - DEVICE: PASS - test_isr_dynamic in 0.004 seconds
DEBUG   - DEVICE: ===================================================================
DEBUG   - DEVICE: START - test_isr_offload_job
DEBUG   - DEVICE: SKIP - test_isr_offload_job in 0.001 seconds
DEBUG   - DEVICE: ===================================================================
DEBUG   - DEVICE: START - test_isr_offload_job_identi
DEBUG   - DEVICE: PASS - test_isr_offload_job_identi in 0.004 seconds
DEBUG   - DEVICE: ===================================================================
DEBUG   - DEVICE: START - test_isr_offload_job_multiple
DEBUG   - DEVICE: PASS - test_isr_offload_job_multiple in 0.006 seconds
DEBUG   - DEVICE: ===================================================================
DEBUG   - DEVICE: START - test_nested_isr
DEBUG   - DEVICE: SKIP - test_nested_isr in 0.001 seconds
DEBUG   - DEVICE: ===================================================================
DEBUG   - DEVICE: START - test_prevent_interruption
DEBUG   - DEVICE: locking interrupts
DEBUG   - DEVICE: unlocking interrupts
DEBUG   - DEVICE: timer fired
DEBUG   - DEVICE: PASS - test_prevent_interruption in 0.068 seconds
DEBUG   - DEVICE: ===================================================================
DEBUG   - DEVICE: START - test_static_shared_irq_write
DEBUG   - DEVICE: SKIP - test_static_shared_irq_write in 0.001 seconds
DEBUG   - DEVICE: ===================================================================
DEBUG   - DEVICE: TESTSUITE interrupt_feature succeeded
DEBUG   - DEVICE: Running TESTSUITE shared_irq_feature
DEBUG   - DEVICE: ===================================================================
DEBUG   - -- west flash: using runner misc-flasher



FIRMWARE = 
/home/zephyr/zephyrproject/zephyr/twister-out/it8xxx2_evb/tests/kernel/interrupt/arch.shared_interrupt
/home/zephyr/ite_t /home/zephyr/zephyrproject/zephyr/twister-out/it8xxx2_evb/tests/kernel/interrupt/arch.shared_interrupt/zephyr/zephyr.bin
is_watchdog = 0

DEBUG   - Timed out while monitoring serial output on it8xxx2_evb
DEBUG   - Expected suite names:['interrupt_feature', 'shared_irq_feature', 'interrupt_feature', 'shared_irq_feature']
DEBUG   - Detected suite names:['interrupt_feature', 'shared_irq_feature']
DEBUG   - run status: it8xxx2_evb/tests/kernel/interrupt/arch.shared_interrupt failed
INFO    - 1/1 it8xxx2_evb               tests/kernel/interrupt/arch.shared_interrupt        FAILED Timeout (device 75.423s)
ERROR   - see: /home/zephyr/zephyrproject/zephyr/twister-out/it8xxx2_evb/tests/kernel/interrupt/arch.shared_interrupt/handler.log

**Comment by Dino-Li** [comment]
This test triggers an interrupt but doesn't clear interrupt pending status in its ISR.
On it8xxx2, interrupt will continue to be triggered, causing system to get stuck.
Disable interrupt in ISR will make this test pass:
https://github.com/Dino-Li/zephyr/commit/850d9073f8c2a0299a64431b5b7c7e2663da08e8
Is this right solution?

**Comment by pkunieck** [comment]
After run this test on ite with those changes it seems to be working. I run test a couple of times and I see no errors or failures.

**Comment by Dino-Li** [comment]
@pkunieck,

Can it8xxx2_evb board skip this test?
Because this test needs to trigger a software interrupt after calling trigger_irq. On it8xxx2_evb, current trigger_irq implementation of RISC-V architecture does not trigger interrupts. Instead, a floating GPIO interrupt is triggered after calling irq_enable().
Without adding callback for GPIO ISR to clear pending interrupt status, system will get stuck.
