### ISSUE TITLE
The shell sample does not working on k64f board

### ISSUE THREAD

**Issue by kkc0505** [zephyrproject-rtos/zephyr#6312]
When I test the shell on k64f, the following message is displayed after input command.

Zephyr Shell, Zephyr version: 1.10.99
Type 'help' for a list of available commands
shell> help
***** BUS FAULT *****
  Executing thread ID (thread): 0x200002d0
  Faulting instruction address:  0x224a
  Imprecise data bus error
Fatal fault in ISR! Spinning...

please help this issue.

thinks

**Comment by MaureenHelm** [comment]
Thanks for reporting this. I'm still debugging, but after some git bisecting it looks like the introduction of mcumgr may be to blame

@carlescufi @ccollins476ad

**Comment by ccollins476ad** [comment]
I don't believe I have access to a k64f, but I'll see if I can replicate it with other hardware.

**Comment by MaureenHelm** [comment]
Fixed by #6313

**Comment by kkc0505** [comment]
Thinks for your comment.
I will check shell on k64f.
