### ISSUE TITLE
The host_io->power_mode did not be initialized as SDHC_POWER_OFF in the imx_usdhc.c

### ISSUE THREAD

**Issue by CristXu** [zephyrproject-rtos/zephyr#63130]
According to the below code, can not find where to init the host_io->power_mode. In other words, the host_io->power_mode did not be initialized as SDHC_POWER_OFF. Which will maybe cause some potential issues.
https://github.com/zephyrproject-rtos/zephyr/blob/f51575212b3574e9d97b804d87c3803e8ed31480/drivers/sdhc/imx_usdhc.c#L335
```[tasklist]
### Tasks
```

**Comment by henrikbrixandersen** [comment]
Please use our bug template when reporting bugs. You need to edit this issue to include the information requested in https://github.com/zephyrproject-rtos/zephyr/blob/main/.github/ISSUE_TEMPLATE/001_bug_report.md
