### ISSUE TITLE
Domains initialisation possibly insane

### ISSUE THREAD

**Issue by LukaszMrugala** [zephyrproject-rtos/zephyr#63166]
**Describe the bug**
Let's take a look at the initialisation of the Domains class:

https://github.com/zephyrproject-rtos/zephyr/blob/73b803ab4b50847f3865f3da1b175b07038a9f62/scripts/pylib/build_helpers/domains.py#L54-L69

We can see that a case where the data is incomplete, lacking domains, was considered, as a warning is then generated. However, such a consideration misses the point.

If `data` dictionary lacks the `domains` key entirely, the `__init__` will crash just after the warning is generated. If the key has an empty list, the object becomes a ticking timebomb, ready to crash at a `get_default_domain()` call. That is caused by a naming error, where a default value of `[]` is assigned to `self._domain_default` rather than `self._default_domain`. 

**Expected behavior**
Initialisation raises error or gracefully ends rather than crashing and does not leave the created object in an unstable state.

**Impact**
Domains module is unstable.

**Proposed solution**
```python
 def __init__(self, data): 
     self._domains = [] 
     self._domain_names = [] 
     self._default_domain = [] 
  
    if data is None:
      raise ValueError('Data not provided.') 
  
     self._build_dir = data.get('build_dir') 
     domain_list = data.get('domains') 
     if not domain_list: 
         raise ValueError('No domains provided.')
  
     for d in domain_list: 
         domain = Domain(d['name'], d['build_dir']) 
         self._domains.append(domain) 
         self._domain_names.append(domain.name) 
         if domain.name == data['default']: 
             self._default_domain = domain 
```

**Comment by thedjnK** [comment]
CC @57300

**Comment by 57300** [comment]
This is improved somewhat on `main` now (https://github.com/zephyrproject-rtos/zephyr/commit/05d77690736b5ad022ee1d0f7dc9b4fea2bd2c24). `from_file()` and `get_default_domain()` will no longer crash.

But I can think of more improvements. The warning is indeed unnecessary, and more error checks can be added.

**Comment by golowanow** [comment]
some new issue at CI:
see https://github.com/zephyrproject-rtos/zephyr/actions/runs/6417150473/job/17422293239?pr=63472
