### ISSUE TITLE
samples: subsys: mgmt: mcumgr: smp_svr: sample.mcumgr.smp_svr.mcuboot_flags.direct_xip_withrevert 

### ISSUE THREAD

**Issue by katgiadla** [zephyrproject-rtos/zephyr#63229]
**Describe the bug**
The test `sample.mcumgr.smp_svr.mcuboot_flags.direct_xip_withrevert` fails.

Observed for `nrf52840dk_nrf52840`.

**To Reproduce**
1. have nrf52840dk_nrf52840 connected
2. go to your zephyr dir
3. call `./scripts/twister -T samples/subsys/mgmt/mcumgr/smp_svr -p nrf52840dk_nrf52840 --device-testing --device-serial /dev/ttyACM0 -v --inline-logs`
4. See console output with error

**Expected behavior**
Valid console output

**Impact**
Not clear

**Logs and console output**
```
warning: MCUBOOT_BOOTLOADER_NO_DOWNGRADE (defined at modules/Kconfig.mcuboot:220) has direct dependencies MCUBOOT_BOOTLOADER_MODE_HAS_NO_DOWNGRADE && BOOTLOADER_MCUBOOT with value n, but is currently being y-selected by the following symbols:
 - MCUBOOT_BOOTLOADER_MODE_DIRECT_XIP_WITH_REVERT (defined at modules/Kconfig.mcuboot:192), with value y, direct dependencies <choice MCUBOOT_BOOTLOADER_MODE> (value: y), and select condition <choice MCUBOOT_BOOTLOADER_MODE> (value: y)
ect_xip_withrevert/zephyr/misc/generated/extra_kconfig_options.conf'

error: Aborting due to Kconfig warnings
```

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04.1 LTS
- Toolchain Zephyr SDK 0.16.0
 - Commit SHA or Version used: zephyr-v3.4.0-4394-gb1b4932373c6

**Comment by nordicjm** [comment]
*Was fixed by https://github.com/zephyrproject-rtos/zephyr/pull/63117*
