### ISSUE TITLE
Mcumgr img on V3.2-branch crashes nios2

### ISSUE THREAD

**Issue by Nelson-Atema** [zephyrproject-rtos/zephyr#63313]
**Describe the bug**
In v3.2-branch Mcumgr img command contains packed structs that cause unaligned memory access issues on the nios2 architecture

**To Reproduce**
build and run v3.2 with CONFIG_MCUMGR_CMD_IMG_MGMT on a nios2 board

**Impact**
Mcumgr img not usable on V3.2-branch

**Workaround**
Backport: #63312

**Comment by nordicjm** [comment]
3.2 is an old version and we do not backport to old branches, only the LTS branch(es) and the last released branch, you should update to 3.4
