### ISSUE TITLE
samples/drivers/gpio Sample doesn't work on ESP32 after SMP support was added

### ISSUE THREAD

**Issue by iha** [zephyrproject-rtos/zephyr#6339]
After this commit 245b54ed56868310fd9251a9710b85f194d5ca0c the gpio sample doesn't work. The sample get stuck. 

Running on ESP32

**Comment by andyross** [comment]
Yes, there are some regressions that snuck into the ESP-32 code when used with the asm2 layer.  Looking at this now.

If you're blocked, you can add CONFIG_XTENSA_ASM2=n to your kconfig as a workaround.

**Comment by andyross** [comment]
Opened https://github.com/zephyrproject-rtos/zephyr/issues/6346 to track the low level details, which don't have anything to do with GPIO or this test in particular.  I have a handle on where I think the problem lies.

**Comment by andyross** [comment]
@iha: The fix for the root cause is in master now.  Can you try this specific issue and verify it works for you now?

**Comment by iha** [comment]
@andyross The behaviour is better now: the gpio input is triggered, but after several tests in succession it stops working, but the gpio output continues to run.
