### ISSUE TITLE
drivers: uart_emul: unable to connect to console

### ISSUE THREAD

**Issue by cfriedt** [zephyrproject-rtos/zephyr#63415]
**Describe the bug**
The `uart_emul` driver currently does not support being picked as the `zephyr,console` device because it silently fails at runtime. This is a slight improvement from before #63000 was merged, because in that case, it would just get stuck in an infinite loop, which is a _different_ and technically worse kind of silently failing at runtime.

An "unspoken" requirement for the Zephyr console is that it the underlying UART device must support interrupt-enabled receive. The `uart_emul` driver does not.

While using `uart_emul` as a zephyr console is likely an unusual choice, it has some advantages in that it allows us to perform testing at the ZTest level in C. Writing ZTests in C allows for a far greater breadth and depth of tests above the twister console test harness level.

Please also mention any information which could help others to understand
the problem you're facing:
 - What target platform are you using? any
 - What have you tried to diagnose or workaround this issue? found the root cause and fixed the issue
 - Is this a regression? No, it was just not part of the initial implementation.
 - ...

**To Reproduce**
1. run the test added in #62998 without the associated `uart_emul.c` changes.
2. See error

**Expected behavior**
Tests should pass. The `uart_emul` driver should be usable by other OS facilities more or less as if it were a fully featured uart.

There are likely other improvements to be made for `uart_emul`, eventually, but for now, this enables a sufficient amount of functionality, and gets development unstuck.

**Impact**
It's a showstopper at the moment because having functional tests should be a strong requirement for PRs relating to core Zephyr components like this (i.e. `zephyr,console`). Additionally, switching between `uart_emul` and the regular console device is the only convenient method for me to provide verifiable results that the changes in #62998 work, aside from running on custom silicon.

**Logs and console output**
Note: console output stops because the test in question has failed.
```shell
west build -p auto -b qemu_riscv64 -t run tests/drivers/console_switching
-- west build: running target run
[0/1] To exit from QEMU enter: 'CTRL+a, x'[QEMU] CPU: riscv64
*** Booting Zephyr OS build zephyr-v3.4.0-4277-gae0d63471be1 ***
Running TESTSUITE console_switching
===================================================================
START - test_read


```

**Environment (please complete the following information):**
 - OS: (e.g. Linux, MacOS, Windows): Linux
 - Toolchain (e.g Zephyr SDK, ...): Zephyr SDK v0.16.1
 - Commit SHA or Version used: 927f09c1b62849e04624609b70528dd2f9394f7e

**Additional context**

**Comment by dcpleung** [comment]
@cfriedt Since you already have a PR, I am assigning this back to you.
