### ISSUE TITLE
echo server: incorrect Ethernet FCS and checksum in echo response when running in QEMU

### ISSUE THREAD

**Issue by rmstoi** [zephyrproject-rtos/zephyr#6342]
This test case fails with echo server in QEMU. echo server responds to echo request with malformed response. In the response Ethernet Frame Check Sequence and ICMPv6 checksum are incorrect.
[icmpv6-71191-replay.zip](https://github.com/zephyrproject-rtos/zephyr/files/1752359/icmpv6-71191-replay.zip)
[icmpv6-71191.zip](https://github.com/zephyrproject-rtos/zephyr/files/1752360/icmpv6-71191.zip)

**Comment by laperie** [comment]
@rmstoi , can you please see if you can fix the bug as well?

**Comment by rmstoi** [comment]
@laperie I will look into it

It seems also data in ICMPv6 echo response is malformed. Looks like a memory corruption.
