### ISSUE TITLE
drivers: i2c: stm32: driver stuck after failed transfer

### ISSUE THREAD

**Issue by mjaun** [zephyrproject-rtos/zephyr#63449]
**Describe the bug**
When the `i2c_ll_stm32_v2` driver is used in interrupt mode and a transfer error occurs while reload mode is active, the reload mode is not disabled. Any subsequent I2C transfers are then no longer executed because of a check in `msg_init()`.

**Expected behavior**
On error the I2C transfer should fail but subsequent I2C transfers should be possible.

**Impact**
Blocker because I2C errors might happen sporadically e.g. due to EMC interferences and currently the device gets stuck.

**Proposed solution**
https://github.com/zephyrproject-rtos/zephyr/pull/63439

**Comment by erwango** [comment]
Fixed by https://github.com/zephyrproject-rtos/zephyr/pull/63439
