### ISSUE TITLE
Compile error after changing the definition of `struct _static_thread_data`

### ISSUE THREAD

**Issue by alikovvl** [zephyrproject-rtos/zephyr#63453]
zephyr/include/zephyr/kernel.h:712:9: error: designator order for field '_static_thread_data::init_name' does not match declaration order in '_static_thread_data'

after https://github.com/zephyrproject-rtos/zephyr/commit/41e8b44619c7dd60ccf91ac642c49e68d14f7ede

**Comment by ycsin** [comment]
@alikovvl could you provide the full build log?
cc @keith-packard

**Comment by fabiobaltieri** [comment]
Hi, could you change the issue description so that it uses the [bug report template](https://github.com/zephyrproject-rtos/zephyr/issues/new?template=001_bug_report.md)? It asks for some important information that are very useful for us to understand the issue. Thanks.

**Comment by keith-packard** [comment]
I think I understand the problem -- the indicated patch changes the order of members of the _static_thread_data struct to avoid inserting padding before the 8-byte init_delay member. C++ appears to complain about a struct initialization where the order of initializers doesn't match the struct order. Which is silly as that's kinda the point of named initializers, but one doesn't generally get far arguing with the compiler.

Closed by: #63468
