### ISSUE TITLE
Filter for libcxx tests use TOOLCHAIN_HAS_PICOLIBC rather than CONFIG_PICOLIBC_SUPPORTED

### ISSUE THREAD

**Issue by alpsayin** [zephyrproject-rtos/zephyr#63488]
**Describe the bug**
https://github.com/zephyrproject-rtos/zephyr/blob/99ab1ab06cda167a633c4047d327141a19cbafaa/tests/lib/cpp/libcxx/testcase.yaml#L27

All other `picolibc` tests use the config flag. Is this an issue?

p.s. this may give me some headache with microblaze while I'm getting picolibc up. Though not that much, because CI still won't build nor run tests.

**Please also mention any information which could help others to understand
the problem you're facing:**
 - What target platform are you using?
_Experimental microblaze with no picolibc support._
 - What have you tried to diagnose or workaround this issue?
_Modified the filter to `CONFIG_PICOLIBC_SUPPORTED` and test was skipped. I also checked if I can turn off `TOOLCHAIN_HAS_PICOLIBC` from sdk-ng side of things. But it seems it's been set `ON` as a cached CMake variable (which is very annoying to alter once it's cached)._
https://github.com/zephyrproject-rtos/sdk-ng/blob/3e434173c283fbf808f825b8a88abbba7ca43d7c/cmake/zephyr/generic.cmake#L33
 - Is this a regression? If yes, have you been able to "git bisect" it to a
   specific commit?
_Not a regression._

**To Reproduce**
Change -for example- [mips arch Kconfig](https://github.com/zephyrproject-rtos/zephyr/blob/main/arch/mips/Kconfig) to override the `CONFIG_PICOLIBC_SUPPORTED` flag
```
config PICOLIBC_SUPPORTED
	bool
	default n
```
And then
```
west twister -p qemu_malta -s tests/lib/cpp/libcxx/cpp.libcxx.glibcxx.picolibc
```

**Expected behavior**
A lot of other picolibc subtests use `CONFIG_PICOLIBC_SUPPORTED` as their filter so they're skipped.
However, `libcxx`'s picolibc subtest in testcase.yml uses `TOOLCHAIN_HAS_PICOLIBC` as filter allowing the test to proceed. For MIPS the test will pass of course. 

**Impact**
Merely an inconvenience. I expect to get picolibc support ready for microblaze too, but until then I noticed I can't filter out this one single test. Otherwise, I raised it because it seems like this was forgotten during the filter change of the other testcases.

**Logs and console output**
Not really applicable.

**Environment (please complete the following information):**
Probably not very relevant that I hyperlinked the relative blobs.

**Additional context**
I'm just trying to bring this really minor thing into your attention and ask if this indeed needs addressing?

**Comment by henrikbrixandersen** [comment]
If you are reporting a bug, please use our bug template (You need to edit this issue to include the information requested in https://github.com/zephyrproject-rtos/zephyr/blob/main/.github/ISSUE_TEMPLATE/001_bug_report.md).

**Comment by alpsayin** [comment]
> If you are reporting a bug, please use our bug template (You need to edit this issue to include the information requested in https://github.com/zephyrproject-rtos/zephyr/blob/main/.github/ISSUE_TEMPLATE/001_bug_report.md).

My bad, this is what I get for using "Create a new issue referencing this line". Github clearly ignores the template.

**Comment by keith-packard** [comment]
Hrm. Any C++ tests using the C++ standard library from the toolchain must also use the C library from the toolchain, and that's what this test is trying to check for. Maybe this check should *also* include `PICOLIBC_SUPPORTED`? That would have seemed redundant when this was written as the set of targets with picolibc support was greater than the set of targets with picolibc in the SDK

**Comment by alpsayin** [comment]
I genuinely can't comment. It's a minor detail, and I only brought it to attention due to seeming inconsistency. 
Another way to look at this is: as of this moment `sdk-ng` always marks `TOOLCHAIN_HAS_PICOLIBC` so it's akin to not having a filter.

**Comment by keith-packard** [comment]
yes, and sdk-ng also always supports picolibc. But presumably some other toolchain wouldn't set this? Like clang?
