### ISSUE TITLE
Doc: The version of SDK and checksum are not aligned

### ISSUE THREAD

**Issue by ChiaoY** [zephyrproject-rtos/zephyr#63518]
**Describe the bug**
In the section [Install Zephyr SDK](https://docs.zephyrproject.org/latest/develop/getting_started/index.html#install-zephyr-sdk) of Getting started Guide, the version of the SDK is updated to 0.16.3 while the version of checksum is still 0.16.1
```
cd ~
wget https://github.com/zephyrproject-rtos/sdk-ng/releases/download/v0.16.3/zephyr-sdk-0.16.3_macos-x86_64.tar.xz
wget -O - https://github.com/zephyrproject-rtos/sdk-ng/releases/download/v0.16.1/sha256.sum | shasum --check --ignore-missing
```

**To Reproduce**
1. `cd ~`
2. `wget https://github.com/zephyrproject-rtos/sdk-ng/releases/download/v0.16.3/zephyr-sdk-0.16.3_macos-x86_64.tar.xz`
3. `wget -O - https://github.com/zephyrproject-rtos/sdk-ng/releases/download/v0.16.1/sha256.sum | shasum --check --ignore-missing`
4. output of step 3.: `shasum: standard input: no file was verified`

**Expected behavior**
4. output of step 3.: `zephyr-sdk-0.16.3_macos-aarch64.tar.xz: OK`

**Impact**
Can not check to checksum of the SDK

**Logs and console output**
If applicable, add console logs or other types of debug information
e.g Wireshark capture or Logic analyzer capture (upload in zip archive).
copy-and-paste text and put a code fence (\`\`\`) before and after, to help
explain the issue. (if unable to obtain text log, add a screenshot)

**Environment (please complete the following information):**
 - OS: MacOS
 - Toolchain : Zephyr SDK
 - Commit SHA or Version used

**Additional context**
N/A

**Suggest Fix**
Update the checksum to `0.16.3`

**Comment by kartben** [comment]
Addressed by PR #63480.
Thanks for taking the time to report the issue, much appreciated!
