### ISSUE TITLE
Modbus module's read function returns obsolete data

### ISSUE THREAD

**Issue by hongquan-prog** [zephyrproject-rtos/zephyr#63668]
**Describe the bug**
 The code my colleague wrote uses the Modbus to read the device's holding registers. The first time the read timeout occurs, and from then on each read is the result of the previous read.

After careful investigation I found the reason for the problem, the baud rate of the serial port is 9600, the Modbus timeout is 3000us, the read command is 8 bytes, it takes about 8.3ms to complete the send, plus the time used to receive is much greater than 3000us, so the first time to read the registers will be prompted to read failed, but the second time to return to the data received after the first read timeout, and from then on every time will read outdated data.

The following is the code of modbus_tx_wait_rx_adu function, its role is to send the data through the interrupt and wait for the answer, after receiving the answer and checking the serial port to receive the interrupt to release the semaphore, as long as the modbus occurs a timeout, it will lead to each time to read the data is the data of the last time, so each time to read the semaphore should be cleared before.

```
int modbus_tx_wait_rx_adu(struct modbus_context *ctx)
{
	modbus_tx_adu(ctx);

	if (k_sem_take(&ctx->client_wait_sem, K_USEC(ctx->rxwait_to)) != 0) {
		LOG_WRN("Client wait-for-RX timeout");
		return -ETIMEDOUT;
	}

	return ctx->rx_adu_err;
}
```

**Expected behavior**
Returns an error code when a read timeout occurs, instead of returning obsolete data

**Environment (please complete the following information):**
 - OS: MacOS, Windows
 - Toolchain: Zephyr SDK 0.15.2
 - Commit SHA: a287c88326

**Comment by jfischer-no** [comment]
> After careful investigation I found the reason for the problem, the baud rate of the serial port is 9600, the Modbus timeout is 3000us, the read command is 8 bytes, it takes about 8.3ms to complete the send, plus the time used to receive is much greater than 3000us, so the first time to read the registers will be prompted to read failed, but the second time to return to the data received after the first read timeout, and from then on every time will read outdated data.

I finally found some time to understand it and check the timings and code. I think there is no easy solution to prevent this kind of misconfiguration where the client sets the timeout parameter to a small value relative to the baudrate, and retries immediately after the timeout. What could mitigate the issue is to use different command after timeout, e.g. FC08.
I do not consider this a bug and have no plans to resolve it.
