### ISSUE TITLE
Blinky and button samples not working for Nucleo F411RE

### ISSUE THREAD

**Issue by gabohc** [zephyrproject-rtos/zephyr#63727]
Blinky and button samples not working for Nucleo F411RE

Successfully built the sample, without issues or errors, with:

```
west build -p always -b nucleo_f411re samples/basic/blinky
```
Programming the board directly with the binary file (.hex, .bin) via STM-32 LINK UTILITY does not work.
 (`west flash` does not either, but that's for another issue)

However, using the blinky sample from Mbed IOS, compiling via Keil Studio Cloud and programming with the same method DOES work (ruling out faulty board, checking connection, etc)

**Expected behavior**
Samples working out of the box, given that it is a supported board

**Environment (listing the two that I used):**
 - WSL Ubuntu 22.04    -- Ubuntu 20.04
 - Zephyr SDK 0.16.3     -- 0.13.0
 - Zephyr 3.5.0rc2          -- 2.6.0

**Additional context**
I have successfully used Zephyr previously with a custom board, in another computer. Also tried building the binary with that environment (the second one listed, v2.6.0), with the same result

I also tried modifying the used gpios in the sample, to no avail.

**Comment by FRASTM** [comment]
This seems to be a pin conflict on the GPIO PA5

**Comment by erwango** [comment]
On my side, this sample works out of the box using default `west flash`.
I'm using Ubuntu 20.04, `v3.5.0-rc2-56`.

Please note that `Programming the board directly with the binary file (.hex, .bin) via STM-32 LINK UTILITY does not work.` is not the usual flashing process, even if I don't see why it wouldn't work.

**Comment by FRASTM** [comment]
@gabohc  can you please check your hardware board : SB12 (NRST) is not open (on the bottom side of the MB1136 nucleo_f411re board)

![MB1136-REVC03-SB12](https://github.com/zephyrproject-rtos/zephyr/assets/51417392/ff9c9a6e-0bf5-4e37-8415-b6a04504642c)

**Comment by gabohc** [comment]
@FRASTM I can confirm, it is **not** open. 

@erwango Yes, I know it's not the standard flashing, but I assumed it would be no problem since in the past I was able to manually flash the other board with the bin file via JTAG with a Raspberry Pi

**Comment by erwango** [comment]
@gabohc What's your board revision ?

**Comment by gabohc** [comment]
Hi apologies for the late reply

I tested this once again, both by repeating the process in Windows and Linux, but same result
