### ISSUE TITLE
Avoid lis2dh interrupt multiple triggers

### ISSUE THREAD

**Issue by gwa-simon** [zephyrproject-rtos/zephyr#63736]
### Problem description

I am using the accelerometer lis3dh in a project that requires very low power consumption and I am having to high power when implementing anymotion interrupt. I notice that the driver [drivers/sensor/lis2dh](url) configures the interrupt pin as GPIO_INT_LEVEL_ACTIVE and turn it OFF while processing to avoid multiple triggers. Although there is a situation that multiple triggers still happen.

Lis3dh (or lis2dh) does not clear the interrupt immediately after INTx_SRC is read, but only at the next sample read. So lets say we implement a 50Hz sampling rate, it means readings every 20ms. 
The callback `lis2dh_thread_cb` can be executed much faster than 20 ms and it creates a loop that runs for 20 ms every time that the interrupt is triggered by the accelerometer (When lis2dh_thread_cb is finished the pin will still be high and a new call will be generated). 

Since the register INTx_SRC is read in the first loop, it will be cleared and `handler_anymotion` will be called only once. But the loop will still be running and consuming power, as can be seen in the picture below.

![Interrupt current](https://github.com/zephyrproject-rtos/zephyr/assets/126065516/f32e662c-7a20-4655-9f3f-cdc05cc5ea6f)

### Proposed change

I propose that the type of interrupt is changed from **GPIO_INT_LEVEL_ACTIVE** to **GPIO_INT_EDGE_RISING**, which will ensure that it is triggered only once. 

Since the interrupt is changed to EDGE type, the multiple calls for `setup_int1` and `setup_int2` can be removed and the interrupt can be initialized only once.

**Comment by gwa-simon** [comment]
Actually, I think it would be better to be able to configure which type of interrupt is generated (GPIO_INT_EDGE, GPIO_INT_EDGE_RISING, GPIO_INT_EDGE_FALLING, GPIO_INT_LEVEL_ACTIVE, ...)

Turns out that for the model micro I am using (nrf52832), some edge interrupts cause a static 400 µA current. So being able to select the type might be interesting since different applications might require different setups.

Best regards

**Comment by avisconti** [comment]
> Actually, I think it would be better to be able to configure which type of interrupt is generated (GPIO_INT_EDGE, GPIO_INT_EDGE_RISING, GPIO_INT_EDGE_FALLING, GPIO_INT_LEVEL_ACTIVE, ...)
> 
> Turns out that for the model micro I am using (nrf52832), some edge interrupts cause a static 400 µA current. So being able to select the type might be interesting since different applications might require different setups.
> 
> Best regards

I'm investigating feasibility of adding this configuration in DT. But there are no other examples

**Comment by avisconti** [comment]
@gwa-simon can you please take a look and test #63876? I just tested compilation, but I'd appreciate if you could help me testing it out... Thanks

**Comment by gwa-simon** [comment]
Hi @avisconti, 

thank you for implementing the changes. It looks to work fine, but could you please add one extra type, GPIO_INT_EDGE. 

For some reason with the micro NRF52832, if I configure it directly with GPIO_INT_EDGE_RISING or GPIO_INT_EDGE_FALLING, there is a constant current of 400uA. But with GPIO_INT_EDGE it works fine.

**Comment by avisconti** [comment]
> Hi @avisconti,
> 
> thank you for implementing the changes. It looks to work fine, but could you please add one extra type, GPIO_INT_EDGE.
> 
> For some reason with the micro NRF52832, if I configure it directly with GPIO_INT_EDGE_RISING or GPIO_INT_EDGE_FALLING, there is a constant current of 400uA. But with GPIO_INT_EDGE it works fine.

mmmh, sure. But it is strange.

**Comment by avisconti** [comment]
> Hi @avisconti,
> 
> thank you for implementing the changes. It looks to work fine, but could you please add one extra type, GPIO_INT_EDGE.
> 
> For some reason with the micro NRF52832, if I configure it directly with GPIO_INT_EDGE_RISING or GPIO_INT_EDGE_FALLING, there is a constant current of 400uA. But with GPIO_INT_EDGE it works fine.

Maybe you can add your comments/thoughts directly on #63876. Thanks

**Comment by avisconti** [comment]
@gwa-simon can you please take a look to what have been requested in #69487? I don't want that something would be broken

**Comment by avisconti** [comment]
#71229 may potentially broke this issue. But the PR makes sense and should be approved. I kindly ask @gwa-simon to test his case against that PR once merged and re-open this issue if the case.
