### ISSUE TITLE
OpenThread: otPlatRandomGetTrue() implementation is not up to spec, may lead to security issues

### ISSUE THREAD

**Issue by pfalcon** [zephyrproject-rtos/zephyr#6389]
https://openthread.io/reference/group/plat-random#otplatrandomgettrue specifies:

>otPlatRandomGetTrue
>
>Get true random value sequence.
>
>This function MUST be implemented using a true random number generator (TRNG).

However, implementation in Zephyr:
https://github.com/zephyrproject-rtos/zephyr/blob/master/subsys/net/lib/openthread/platform/random.c#L19 uses sys_rand32_get(), which may return pseudo-random value. For TRNG, Zephyr offers entropy subsystem (entropy_get_entropy() function).

**Comment by pfalcon** [comment]
This goes with the same disclaimer as the text in parens in https://github.com/zephyrproject-rtos/zephyr/issues/6388#issuecomment-368585206 .

**Comment by d3zd3z** [comment]
Also, if the Thread spec does require a TRNG, we should probably document that a device will only be able to be compliant with Thread if the hardware contains a TRNG. It is not possible to implement a TRNG in software (that's kind of the point of the 'True'). It is a little unusual of a requirement, though, since most things will specify a CSPRNG (cryptographically secure pseudo random number generator), even if that is seeded from a TRNG.

**Comment by nashif** [comment]
@d3zd3z Can you guys in the SecWG propose a solution and submit it?

**Comment by d3zd3z** [comment]
NIST SP 800-90C describes "true", and it should be doable with an entropy source.

**Comment by agross-linaro** [comment]
We are going to shelve this for now.  Setting the priority approriately.

**Comment by d3zd3z** [comment]
@dleach02 I think this can also be closed as part of your randomness work.

**Comment by dleach02** [comment]
@d3zd3z , yep. My intent was to get the csrand stuff merged then make a pass to start putting into use.

 #17736

**Comment by rlubos** [comment]
From the OpenThread point of view, this should be resolved in https://github.com/zephyrproject-rtos/zephyr/pull/20106, where I update the OpenThread version used with Zephyr.

The new OpenThread got rid of the `random.c` platform module, and introduced `entropy.c` which is supposed to serve as an entropy source for OpenThread (or rather mbedTLS which OT uses underneath). I've used the Zephyr's entropy subsystem in the new implementation.

**Comment by d3zd3z** [comment]
I'm ok closing this, then.

**Comment by rlubos** [comment]
No longer an issue with #20106, closing.
