### ISSUE TITLE
Repeated west sysbuild of hello_world from within samples/hello_world directory fails

### ISSUE THREAD

**Issue by lectronix-mahaney** [zephyrproject-rtos/zephyr#63934]
**Describe the bug**
Building the hello_world sample from the samples/hello_world directory the first time using

```west build -b esp32s2_saola --sysbuild -- -DSB_CONFIG_BOOTLOADER_MCUBOOT=y```

succeeds. Immediately running the same command again fails. Also tried with ```nrf52840dk_nrf52840``` with same result. Found using v3.4.0, but confirmed also on  main as of f6fe61e598. Repeated west sysbuilds work when building from the zephyr directory as

```west build -b esp32s2_saola --sysbuild samples/hello_world -- -DSB_CONFIG_BOOTLOADER_MCUBOOT=y```

When building in the samples/hello_world directory adding ```-p always``` works, but of course causes a full rebuild.

Repeatedly running cmake/ninja from within the samples/hello_world directory also works:
```
cmake -Bbuild -GNinja -DBOARD=esp32s2_saola -DAPP_DIR=. ../../share/sysbuild
ninja -C build
```

**To Reproduce**
1. cd samples/hello_world
2. west build -b esp32s2_saola --sysbuild -- -DSB_CONFIG_BOOTLOADER_MCUBOOT=y
3. west build -b esp32s2_saola --sysbuild -- -DSB_CONFIG_BOOTLOADER_MCUBOOT=y

**Expected behavior**
Subsequent west sysbuilds from within the samples/hello_world directory and other out-of-tree projects) should succeed.

**Impact**
Impacts sysbuilds of out-of-tree projects. Using cmake/ninja directly or ```-p always``` with west build are workarounds.

**Logs and console output**
Notably, the first build shows (in part):
```
   *****************************
   * Running CMake for mcuboot *
   *****************************
followed by
   *********************************
   * Running CMake for hello_world *
   *********************************
```
but the second build shows:
```
   *****************************
   * Running CMake for mcuboot *
   *****************************
followed by
   ******************************
   * Running CMake for sysbuild *
   ******************************
```

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: Zephyr SDK 0.16.1
 - Version: v3.4.0

**Comment by MaureenHelm** [comment]
cc @tejlmand
