### ISSUE TITLE
net: ip: Does not reset expired TCP session

### ISSUE THREAD

**Issue by chih-hung-yu** [zephyrproject-rtos/zephyr#63966]
**Describe the bug**
A TCP client can be programmed to use a fixed TCP source port. When we perform a power cycle to a target running the fixed-source-port TCP client that has already connected to the TCP server, the target will make a new TCP session with the same TCP source port, but the old TCP session is still kept by the TCP server which replies with the old ACK number.

<B>For Linux TCP client</B>, RST is issued if the TCP server ACKed unseen segment, and then the TCP server can accept new SYN with the same TCP source port.
(At packet No. 93, the TCP client restarts and sends a new SYN.)
![image](https://github.com/zephyrproject-rtos/zephyr/assets/147849083/052e44b8-24b3-4839-a5f6-ea9fc6410be3)

If the Linux TCP client issues random-source-port SYN after a power cycle and hence the new connection is established immediately, the TCP server still issues TCP Keep-Alive for the old session, and the Linux TCP client will reset the old connection when it receives  TCP Keep-Alive.
(At packet No. 107, the TCP client restarts and sends a new SYN.)
![image](https://github.com/zephyrproject-rtos/zephyr/assets/147849083/d3c80dab-53f8-4ef5-856a-d1c4efa1d227)

<B>For Zephyr TCP client</B>, ACK is ignored if the TCP server ACKed unseen segment, and the Zephyr TCP client keeps retransmitting SYN, the connection cannot be established until the old TCP session kept by the TCP server reaches TCP-Keep-Alive timeout.
(At packet No. 49, the TCP client restarts and sends a new SYN.)
![image](https://github.com/zephyrproject-rtos/zephyr/assets/147849083/374183ec-87a4-4d78-a094-b62528af100c)

**To Reproduce**
1. Power the Zephyr TCP client up to make a TCP connection to the TCP server.
2. Power the Zephyr TCP client down, and then power the Zephyr TCP client up again.
```
#include <zephyr/net/socket.h>

int main(void)
{
    int fd, ret;
    struct sockaddr_in sin, servaddr;
    struct in_addr inaddr;

    fd = zsock_socket(AF_INET, SOCK_STREAM, 0);

    sin.sin_family = AF_INET;
    sin.sin_addr.s_addr = INADDR_ANY;
    sin.sin_port = htons(4044);
    zsock_bind(fd, (const struct sockaddr *)&sin, sizeof(sin));

    inet_pton(AF_INET, "10.123.4.223", (void *)&inaddr);

    servaddr.sin_family = AF_INET;
    servaddr.sin_addr = inaddr;
    servaddr.sin_port = htons(502);

    ret = zsock_connect(fd, (const struct sockaddr *)&servaddr, sizeof(servaddr));
    printk("zsock_connect()=%d\n", ret);

    return 0;
}
```

**Expected behavior**
Zephyr will reset the expired TCP session kept by the peer when the peer replies with an unexpected ACK number.

**Environment**
 - OS: Linux
 - Toolchain: Zephyr SDK
 - Commit: https://github.com/zephyrproject-rtos/zephyr/commit/433a85e7bf32ffc77ba194bb903bcca84c44c047

**Comment by rlubos** [comment]
@chih-hung-yu Please give https://github.com/zephyrproject-rtos/zephyr/pull/64029 a try.

**Comment by chih-hung-yu** [comment]
> @chih-hung-yu Please give #64029 a try.

 For fixed-source-port Zephyr TCP client, the behaviour is now the same as Linux TCP client.
![image](https://github.com/zephyrproject-rtos/zephyr/assets/147849083/cafc89c3-7fe7-47ed-bd99-9a6c903df8b5)

 For random-source-port Zephyr TCP client, RST is sent for unexpected TCP Keep-Alive packet, and an extra ICMP Port unreachable is also sent.
![image](https://github.com/zephyrproject-rtos/zephyr/assets/147849083/956bedab-bf2d-4a51-bd11-19c8e2b40629)

**Comment by rlubos** [comment]
> For random-source-port Zephyr TCP client, RST is sent for unexpected TCP Keep-Alive packet, and an extra ICMP Port unreachable is also sent.

Zephyr stack currently sends ICMP Destination Unreachable for any IP-based protocol, so it indeed duplicates with the RST behavior introduced. What's the expected behavior for TCP, shall it reply with RST only, and forfeit error reporting at the ICMP level?

Also @jukkar, regarding the Kconfig option to disable RST sending for unbound ports - shall we still send ICMP error in case RST's are disabled, or just silently ignore the packet?

In any case, adjusting this behavior is just a matter of minor tweaks in the code at this point, we just need to agree on the expected behavior.
