### ISSUE TITLE
precision is limited on lsm6dsl sensor measurements.

### ISSUE THREAD

**Issue by Alessio-Parmeggiani** [zephyrproject-rtos/zephyr#63980]
I noticed that in the driver for the lsm6dsl sensor the precision of the measurement is limited to 3 decimal numbers, when the datasheet specifies that it could be much higher. In fact the sensitivity is 0.004375 dps/LSB or 0.0000763582 rad/LSB.

In particular in the function to convert the measurement to the sensor_value struct the following function is applied:
[code](https://github.com/zephyrproject-rtos/zephyr/blob/137097f5c3153cefb9f585aa7b2d88bf09a384aa/drivers/sensor/lsm6dsl/lsm6dsl.c#L517C1-L527C2)
`val->val2 = (((int32_t)(dval * 1000)) % 1000) * 1000;` limiting the value to 3 decimal digits.

The same applies also to the acceleration measurements because a similar function is used. [Code](https://github.com/zephyrproject-rtos/zephyr/blob/137097f5c3153cefb9f585aa7b2d88bf09a384aa/drivers/sensor/lsm6dsl/lsm6dsl.c#L467C1-L478C2)

**Possible solution**
A possible solution that would allow 6 decimal digits is the following:

~~`val->val2= (((int32_t)(dval * 100000)) % 100000);`~~

EDIT (26/10/2023):
The possible solution is: `val->val2= (((int32_t)(dval * 1000000)) % 1000000);` 
I forgot a zero before. Otherwise the suggested implementation for recovering the original value (i.e. the formula val1 + val2 * 10^(-6)  ) is not valid.

**Other minor related precision error**
In the same conversion function there is also a conversion from degrees to radians but the constant used to perform the conversion doesn't have enough decimal digits to allow a precise conversion. For example I measured a sensitivity of 0.00893 instead of the nominal 0.00875 on the gyroscope. By using the measurement in degree I get the nominal value.

**Comment by avisconti** [comment]
@Alessio-Parmeggiani Sorry for the long delay in asnwering. If you are still interested can you possibly submit a PR for this enhancement? Thanks

**Comment by Alessio-Parmeggiani** [comment]
> @Alessio-Parmeggiani Sorry for the long delay in asnwering. If you are still interested can you possibly submit a PR for this enhancement? Thanks

Sure, here it is #70718
