### ISSUE TITLE
fs_open error log

### ISSUE THREAD

**Issue by clamattia** [zephyrproject-rtos/zephyr#64030]
The documentation suggests to use `fs_open` with `flags=0` and presumably `fs_opendir` to detect existence/non-existence of a file.
In case the file does not exists the `fs.c` logs an error: [LOG_ERR("file open error (%d)", rc)](https://github.com/zephyrproject-rtos/zephyr/blob/b732c6d564e542fd25b63041ec713346e01711aa/subsys/fs/fs.c#L166). Since this is the intended outcome it surely is not an error.

There will be false positives in the log, if as suggested by the documentation `fs_open` is used to detect existence/non-existence of a file.

Ideally `fs_` would:
- [ ] <del>Either not log an error if the file/directory does not exist in such circumstance
- [ ] <del>Or provide an additional API function to detect existence/non-existence of files/directories
- [ ] If instead an alternative exists (for example `fs_stat`), the documentation may be updated to say so clearly.

I am opening the issue, because I do not know how to filter out real errors from the false positive.
I would imagine something like:
```
	rc = mp->fs->open(zfp, file_name, flags);
        bool false_positive = (rc == NOT_EXISTS && flags == 0);
	if (rc < 0 && !false_positive) {
		LOG_ERR("file open error (%d)", rc);
        }
	if (rc < 0) {
		zfp->mp = NULL;
		return rc;
	}
```

- [ ] <del>Ideally something similar could be done for `fs_opendir`

Thanks in advance.

**Comment by nordicjm** [comment]
`fs_open` shouldn't be used for that, use `fs_stat`: https://docs.zephyrproject.org/latest/services/file_system/index.html#c.fs_stat

**Comment by clamattia** [comment]
> `fs_open` shouldn't be used for that, use `fs_stat`: https://docs.zephyrproject.org/latest/services/file_system/index.html#c.fs_stat

Thanks for the quick reply. Maybe the documentation (`If flags are set to 0 the function will attempt to open an existing file with no read/write access; this may be used to e.g. check if the file exists.`) could be adjusted then, to reference `fs_stat` instead?

Maybe the documentation of `fs_stat` could explicitly mention existence checks?

**Comment by de-nordic** [comment]
> > `fs_open` shouldn't be used for that, use `fs_stat`: https://docs.zephyrproject.org/latest/services/file_system/index.html#c.fs_stat
> 
> Thanks for the quick reply. Maybe the documentation (`If flags are set to 0 the function will attempt to open an existing file with no read/write access; this may be used to e.g. check if the file exists.`) could be adjusted then, to reference `fs_stat` instead?
> 
> Maybe the documentation of `fs_stat` could explicitly mention existence checks?

Yeah, we should mention that it will log error.

**Comment by clamattia** [comment]
Please feel free to change the area to `documentation` or let me know, if I should make a separate issue.

**Comment by de-nordic** [comment]
> Please feel free to change the area to `documentation` or let me know, if I should make a separate issue.

I will change the doc, no need for another issue.

**Comment by clamattia** [comment]
Thanks
