### ISSUE TITLE
stm32 has SYS_CLOCK_TICKS_PER_SEC  defined twice for LPTIM

### ISSUE THREAD

**Issue by FRASTM** [zephyrproject-rtos/zephyr#64066]
**Describe the bug**

When the stm32  LPTIM is enabled for counting ticks during stm32 low power mode, the  SYS_CLOCK_TICKS_PER_SEC  is defined by the soc/arm/st_stm32/common/Kconfig.defconfig.series. 
It mainly depends on the LPTIM clock source (LSE/LSI).
For  some stm32 boards DTS file it is also defined by the Kconfig.defconfig --> not needed

 
**Expected behavior**
Define the SYS_CLOCK_TICKS_PER_SEC only once

**Comment by erwango** [comment]
Note: In some cases `CONFIG_STM32_LPTIM_CLOCK_LSE=y` is not set which also leads to actual issues
