### ISSUE TITLE
LE Audio: Host: No Broadcast Receive State notification when small ATT_MTU

### ISSUE THREAD

**Issue by mkasenberg** [zephyrproject-rtos/zephyr#64183]
**Describe the bug**
In the BASS/SR/CP/BV-04-C test case [(BASS.TS.p1.pdf)](https://www.bluetooth.org/docman/handlers/downloaddoc.ashx?doc_id=524502) the PTS executes an Add Source operation to the Broadcast Audio Scan Control Point characteristic that uses Write Long Characteristic Value sub-procedure with random Metadata longer than the negotiated ATT_MTU. The Zephyr Host successfully updates its state but fails to send a notification of the Broadcast Receive State characteristic at this function:
https://github.com/zephyrproject-rtos/zephyr/blob/a6eef0ba3755f2530c5ce93524e5ac4f5be30194/subsys/bluetooth/audio/bap_scan_delegator.c#L140-L149

**To Reproduce**
Can be reproduced with AutoPTS. I will edit this to add all steps later.

**Expected behavior**
Based on what was written in [BASS spec](https://www.bluetooth.com/specifications/bass-1-0/):
"If the server supports characteristic values larger than the minimum ATT_MTU for the Unenhanced ATT bearer, then the server should support the Read Long Characteristic Values GATT sub-procedure if not already required by the Bluetooth Core Specification."

I would expect that in this this scenario the Zephyr Host should send a truncated notification of the Broadcast Receive State characteristic, so a client can know whether the operation was successful and eventually decide if it needs to perform the Read Long Characteristic Values GATT sub-procedure to get the full Broadcast Receive State characteristic value.

**Impact**
The BASS/SR/CP/BV-04-C test case fails.

**Logs and console output**
PTS logs:
[BASS_SR_CP_BV_04_C_2023_10_20_12_18_26.zip](https://github.com/zephyrproject-rtos/zephyr/files/13053376/BASS_SR_CP_BV_04_C_2023_10_20_12_18_26.zip)

**Environment:**
 - OS: Windows 11
 - Toolchain: Zephyr SDK 0.16.3
 - Commit SHA: a6eef0b

**Comment by Thalley** [comment]
Thanks for reporting this. It relates to https://github.com/zephyrproject-rtos/zephyr/issues/63362 and will likely be fixed as part of fixing that.
