### ISSUE TITLE
Tests: Bluetooth: host: babblesim test for ISO CIS gives error messages

### ISSUE THREAD

**Issue by kruithofa** [zephyrproject-rtos/zephyr#64187]
The test in the babblesim test under tests/bsim/bluetooth/host/iso/cis gives the following error message:

> bt_hci_core: packets count mismatch

The test does not fail however.

Please also mention any information which could help others to understand
the problem you're facing:
This error message first showed up after commit 7fa77a67fc1c924899982bbcde3d87c80b3e13cb

**To Reproduce**
Build the tests/bsim/bluetooth/host/iso/cis project
Run the testscript tests/bsim/bluetooth/host/iso/cis/testscripts/cis.h and watch the output

**Expected behavior**
1. There should not be a packet count mismatch.
2. In case of a packet count mismatch the test should fail

**Impact**

**Logs and console output**
n/a

**Environment (please complete the following information):**
babblesim

**Additional context**

**Comment by Thalley** [comment]
As per of today, this issue isn't there anymore. Not sure when it was fixed, but there is no packet count mismatch.
