### ISSUE TITLE
driver: modem_cellular: hard fault on network disconnection

### ISSUE THREAD

**Issue by RomainPelletant** [zephyrproject-rtos/zephyr#64291]
**Describe the bug**
Based on BG95 modem, a hard fault occurs on network reconnection, and on device resume.
Hard fault occurs in subsys/modem/modem_chat.c:
static void modem_chat_script_stop(struct modem_chat *chat, enum modem_chat_script_result result)

**To Reproduce**
1. Build sample modem cellular
3. On network disconnection, suspend then resume

**Expected behavior**
No faults

**Environment (please complete the following information):**
 - OS: MacOS
 - Toolchain 0.16.1
 - Zephyr 3.5

**Additional context**
By checking chat and chat->script null pointer, everything is working well.

**Comment by rerickson1** [comment]
@bjarki-trackunit FYI
