### ISSUE TITLE
RFC: API Change: BLE Mesh (prov)

### ISSUE THREAD

**Issue by Andrewpini** [zephyrproject-rtos/zephyr#64315]
### Problem description
https://github.com/zephyrproject-rtos/zephyr/pull/64252

With the release of the Bluetooth Mesh Protocol specification v1.1, the specification (section 5.4) now clearly defines the roles in a provisioning process. It states that: "The Provisionee is a device that participates in the execution of the provisioning protocol with the Provisioner, upon request from the Provisioner." Up until this point references to the `provisionee` role has been called `prov_device` in the Zephyr BLE Mesh implementation. The `prov_device` reference is IMO ambiguous and can be misinterpreted by the end user.

### Proposed change

Change previous `prov_device` references and options to `provisionee` in the implementation.

## Detailed RFC

1. Change internal references from `prov_device` to `provisionee`.
2. Deprecate Kconfig option `CONFIG_BT_MESH_PROV_DEVICE` and replace it with new option `CONFIG_BT_MESH_PROVISIONEE`.

### Dependencies

None

### Concerns and Unresolved Questions

None

**Comment by carlescufi** [comment]
Architecture WG:

- No objections, but this did not require going through the process if the old Kconfig option was being deprecated. This process is only for changes that do not deprecate but break directly
