### ISSUE TITLE
npcx9m6f_evb: sample.sensor.adc_cmp failing

### ISSUE THREAD

**Issue by pkunieck** [zephyrproject-rtos/zephyr#64334]
**Describe the bug**
Test from samples/sensor/adc_cmp_npcx/sample.sensor.adc_cmp failing with timeout and we don't have any logs, just a clear empty output

**To Reproduce**
1. cd <path/to>zephyrproject/zephyr
2. source zephyr-env.sh
3. twister --device-testing --hardware-map <path/to>/map.yaml -T samples/sensor/adc_cmp_npcx/ -vv

**Expected behavior**
Test pass

**Impact**
annoyance

**Logs and console output**
***** delaying boot 500ms (per build configuration) *****
*** Booting Zephyr OS build zephyr-v3.5.0-728-gfd118bbf7c76 (delayed boot 500ms) ***

**Environment (please complete the following information):**
- OS: Linux
- Toolchain Zephyr SDK 16.1
- Commit: tested on the newest, 100% reproduction on the newest commits

**Comment by MulinChao** [comment]
Here is the log from npcx9m6f evb with a patch. (It adds LR at the end of messages printed by `printf()` for better observation.)
```
*** Booting Zephyr OS build v3.5.0-rc1-93-g438b816657f3 ***
ADC CMP: Set Upper threshold
ADC CMP: Lower threshold detected
ADC CMP: Set Lower threshold
ADC CMP: Upper threshold detected
ADC CMP: Set Upper threshold
ADC CMP: Lower threshold detected
ADC CMP: Set Lower threshold
ADC CMP: Upper threshold detected
ADC CMP: Set Upper threshold
...
```
First, it isn`t made by Nuvoton and also not a Zephyr test suite. The users need to connect ADC8 pad manually to the specific voltage and observe whether threshold detection occurred. Once it succeed, the console prints `ADC CMP: Upper/Lower threshold detected` message and starts the other voltage detection again. It seems an infinite loop, and I don`t know how to jump out. From the driver's perspective, npcx adc comparator driver works fine. I will assign it to the owner of this sample code.

**Comment by MulinChao** [comment]
@perezpri Could you take a look?

**Comment by perezpri** [comment]
Hello @MulinChao thanks for providing background. I am not clear what is the expected behavior.
Should this have a way to exit loop or add more messages?

**Comment by MulinChao** [comment]
> Hello @MulinChao thanks for providing background. I am not clear what is the expected behavior. Should this have a way to exit loop or add more messages?

Hi @pkunieck, could we know what is the expected behavior and how to resolve this issue?
