### ISSUE TITLE
TINYCRYPT kconfig bug caused BT tests to fail

### ISSUE THREAD

**Issue by aescolar** [zephyrproject-rtos/zephyr#64344]
**Describe the bug**
In 713ca15224c3223e99bf045b1ab50a6917bf60ea , the TINYCRYPT kconfiguration was changed, to depend on ZEPHYR_TINYCRYPT_MODULE which is not set for unit tests. Which causes all BT unit tests builds using TINYCRYPT to produce a kconfig warning, which leads to a cmake error, and therefore those tests to fail.

**To Reproduce**
1. twister -T  tests/bluetooth/audio/ascs/
2. See error

**Expected behavior**
No kconfig warnings and test failures

**Impact**
Blocked development in main branch and specially around BT development.

**Logs and console output**
https://github.com/zephyrproject-rtos/zephyr/actions/runs/6625055972/job/17995280341

**Environment (please complete the following information):**
 - OS: CI / Ubuntu 22.04
 - Toolchain (e.g Zephyr SDK, ...): Host gcc (11, 12)
 - Commit SHA or Version used: Any after 713ca15224c3223e99bf045b1ab50a6917bf60ea

**Additional context**
Introduced by 713ca15224c3223e99bf045b1ab50a6917bf60ea

**Comment by aescolar** [comment]
CC @ceolin @Thalley @jhedberg

**Comment by ppryga-nordic** [comment]
The issue blocks: https://github.com/zephyrproject-rtos/zephyr/pull/61468 and other Bluetooth subsystem PRs that are pending.
