### ISSUE TITLE
ZEPHYR_{MODULE_NAME}_MODULE not defined for unit tests

### ISSUE THREAD

**Issue by aescolar** [zephyrproject-rtos/zephyr#64348]
**Describe the bug**

https://github.com/zephyrproject-rtos/zephyr/pull/57759
Introduced a new kconfig dependency for modules kconfiguration on the set of automatically defined Kconfig options `ZEPHYR_{MODULE_NAME}_MODULE`.
But these options are not set for unit tests, which leads to unit tests (or they dependencies) not being able to selected those modules.
This broke some unit tests (see https://github.com/zephyrproject-rtos/zephyr/issues/64344 ) 

**To Reproduce**
See https://github.com/zephyrproject-rtos/zephyr/issues/64344 for an example.

**Expected behavior**
ZEPHYR_{MODULE_NAME}_MODULE also defined for unit tests (`unit_testing` target)

**Impact**
Confused developers, and failing unit tests

**Logs and console output**
See https://github.com/zephyrproject-rtos/zephyr/issues/64344

**Environment (please complete the following information):**
 - OS: Linux (Ubuntu 22.04)
 - Toolchain (e.g Zephyr SDK, ...): Host gcc (11 or 12)
 - Commit SHA or Version used: Any after ffe128534370de1de9f5a6ff60a11cf7f411c26b 

**Additional context**
Related to  https://github.com/zephyrproject-rtos/zephyr/issues/64344

**Comment by ceolin** [comment]
The problem, from my understanding, is that these unit tests are using zephyr modules without really declare them, it seems that was working by chance. I sent a pr that runs zephyr_module for unit tests and consequently generates the missing symbol.
