### ISSUE TITLE
RFC: Stable API Change: Rename hci_rpmsg to hci_ipc

### ISSUE THREAD

**Issue by carlescufi** [zephyrproject-rtos/zephyr#64477]
- Problem Description:
  The HCI driver in ``drivers/bluetooth/hci/rpmsg`` and the HCI sample in
  ``samples/bluetooth/hci_rpmsg`` are no longer appropriately named. Both now use
  the IPC subsystem, which can in turn use (but does not have to) RPMsg under
  the hood.
- Proposed Change (detailed):
  The proposal, as shown in Pull Request #64391, is to rename anything related
  to HCI and RPMsg to use the term IPC instead.
- Detailed RFC:
  - Function call changes
    None that are public
  - Device Tree changes (source and bindings)
    The following chose node has been changed:
    ``zephyr,bt-hci-rpmsg-ipc`` has been renamed to ``zephyr,bt-hci-ipc``
  - Kconfig option changes
    ``CONFIG_BT_RPMSG`` has been renamed to ``CONFIG_BT_HCI_IPC``
  - Sample names changes
    ``samples/bluetooth/hci_rpmsg`` has been renamed to ``samples/bluetooth/hci_ipc``
- Dependencies:
  Users will need to use the new Kconfig option and Devicetree chosen node in
  their out of tree boards and applications.
  Users will need to compile the sample with the new name and path.

**Comment by koffes** [comment]
Will these changes break messaging between cores? E.g. if we flash core A after this change has been merged, and we have an older firmware on core B?

**Comment by carlescufi** [comment]
> Will these changes break messaging between cores? E.g. if we flash core A after this change has been merged, and we have an older firmware on core B?

No, because there are no runtime changes at all. Everything is compile-time.

**Comment by carlescufi** [comment]
Architecture WG:

- No objections
