### ISSUE TITLE
Jumbled Console log over USB

### ISSUE THREAD

**Issue by ajaykish** [zephyrproject-rtos/zephyr#6452]
Tested with sample/subsys/usb/console (zephyr 1.11.rc1 release) on Arduino 101 connected to Linux host:

Plug the board into a Linux host. 
The board will be detected as a CDC_ACM serial device. To see the console output
from the zephyr board, used  command  "minicom -D /dev/ttyACM0".

The console output we are getting is jumbled:
ld!x8
Hello World! x86
HellWorld! x86
              llo Word! x6
                          Hello Wordx6
                                      Hello World! x86
Hello World!x6
              Hello World! x86
Hel Wol! x6
HelWrdx6
        Hlo Worl!x6
                   Hello o6
                           Heo rl!x6
                                    Hello World! x86
Hello World! x86
Hello World! x86

Issue is easily reproducible in almost every iteration.

**Comment by finikorg** [comment]
This looks related to  #3614

**Comment by finikorg** [comment]
@nashif This is not fixed yet

**Comment by jfischer-phytec-iot** [comment]
Can not confirm, tested with current master, connected to xhci and ehci.

**Comment by finikorg** [comment]
@jfischer-phytec-iot Do you mean it works for you? I just tested on master + PR #4661 - I see the same issue described in this bug and bug #3614.

**Comment by jfischer-phytec-iot** [comment]
@finikorg it works for me, also I noticed that the errors with Arduino 101 are host controller dependent.

**Comment by galak** [comment]
@finikorg is still an issue?

**Comment by nashif** [comment]
any update?

**Comment by laperie** [comment]
That's a true low-priority bug, we don't see it on any other hardware than Arduino 101

**Comment by laperie** [comment]
Just like in #5678, we're closing it based on Arduino 101 not being actively maintained
