### ISSUE TITLE
k_sleep() fails on ESP32 sometimes

### ISSUE THREAD

**Issue by nniranjhana** [zephyrproject-rtos/zephyr#6455]
used toolchain version:

`xtensa-esp32-elf-gcc (crosstool-NG crosstool-ng-1.22.0-61-gab8375a) 5.2.0`

I had added a loop that runs `k_sleep(1000)` in the hello world sample (while narrowing down the likely issue from another test case). I had added print statements before and after, and as per the log below, it returns from sleep the first time, but fails the second time:

`
***** BOOTING ZEPHYR OS v1.10.99 - BUILD: Mar  5 2018 19:12:04 *****`
`
Hello World! xtensa`
`==> going to sleep      ==> woke up`
`==> going to sleep
`

**Comment by nniranjhana** [comment]
@lpereira @youvedeep FYI

**Comment by lpereira** [comment]
This is most likely related to #6346

**Comment by lpereira** [comment]
In fact, it looks like the same issue. Closing this one as @andyross is already working on the matter.
