### ISSUE TITLE
Usage fault for increased system clock ticks

### ISSUE THREAD

**Issue by javlands** [zephyrproject-rtos/zephyr#64580]
**Describe the bug**
When increasing the system clock ticks per second to 100000, a usage fault occurs when certain Kconfigs are turned on.

We're using the mimxrt1064_evk evaluation kit with no GPIO attached and are checked out to commit [927f09c1b6](https://github.com/zephyrproject-rtos/zephyr/commit/927f09c1b62849e04624609b70528dd2f9394f7e). 

The problem originaly came up in a project, where adding a `LOG_DBG()` would toggle the crash. After some digging, the problem could be pin pointed to the use of 5 Kconfigs with an almost empty main. 
 
**Logs and console output**
```
*** Booting Zephyr OS build zephyr-v3.4.0-4293-g863d4f05e93d ***
[00:00:00.501,000] <err> os: ***** USAGE FAULT *****
[00:00:00.501,000] <err> os:   Illegal use of the EPSR
[00:00:00.501,000] <err> os: r0/a1:  0x00000000  r1/a2:  0x7001b24c  r2/a3:  0x00000003
[00:00:00.501,000] <err> os: r3/a4:  0x00000000 r12/ip:  0x00000003 r14/lr:  0x700082af
[00:00:00.501,000] <err> os:  xpsr:  0x20000024
[00:00:00.501,000] <err> os: Faulting instruction address (r15/pc): 0x00000000
[00:00:00.501,000] <err> os: >>> ZEPHYR FATAL ERROR 35: Unknown error on CPU 0
[00:00:00.501,000] <err> os: Fault during interrupt handling

[00:00:00.501,000] <err> os: Current thread: 0x80001810 (shell_uart)
[00:00:00.543,000] <err> os: Halting system
```

**To Reproduce**
1. Create an empty project
2. Add minimal west.yml + CMakeLists.txt
3. In src/main.c:
```
#include <zephyr/kernel.h>
#include <zephyr/device.h>

#include <zephyr/logging/log.h>
LOG_MODULE_REGISTER(main, LOG_LEVEL_DBG);

int main(void)
{
	return 0;
}
```
4. In prj.conf:
```
CONFIG_LOG=y
CONFIG_SYS_CLOCK_TICKS_PER_SEC=100000
CONFIG_NETWORKING=y
CONFIG_NET_SHELL=y
CONFIG_FLASH=y
```
5. Build and flash the project using the evaluation kit.

**Impact**
Can't initialize device.

**Environment**
 - OS: Linux
 - Toolchain: Zephyr SDK
 - Commit SHA or Version used: [927f09c1b6](https://github.com/zephyrproject-rtos/zephyr/commit/927f09c1b62849e04624609b70528dd2f9394f7e)

**Comment by DerekSnell** [comment]
Hi @javlands ,
Thank you for reporting this.  [CONFIG_SYS_CLOCK_TICKS_PER_SEC](https://docs.zephyrproject.org/latest/kconfig.html#CONFIG_SYS_CLOCK_TICKS_PER_SEC) sets the frequency of the kernel tick interrupt.  At the default 10000, it interrupts every 100us.  Changing to 100000 will interrupt every 10us.  In that case, the CPU will spend a high percentage of its bandwidth interrupting the threads and kernel.  Is there a reason you want the kernel ticks occurring so frequently?  It may reduce the overall performance.  Is there another option to achieve your goal, like using the Counter driver with a hardware timer to achieve the timing you want, and trigger a thread or event?

Best regards
