### ISSUE TITLE
[doc] Documentation issue in 'develop/application/index'

### ISSUE THREAD

**Issue by Asireesha** [zephyrproject-rtos/zephyr#64605]
**Describe the bug**

<< Please describe the issue here >>
<< You may also want to update the automatically generated issue title above. >>

**Environment**

* Page: `develop/application/index`
* Version: main
* SHA-1: 8f01cb81471f90bd60e274455583df62aec139fe

**Comment by Asireesha** [comment]
tflite library is unable to add to zepyhr project

**Comment by Asireesha** [comment]
i want to ai run  inference on microcontroller

**Comment by nordicjm** [comment]
What issue is there in the documentation page you have linked to?

**Comment by henrikbrixandersen** [comment]
> i want to ai run inference on microcontroller

Please see the following samples:
- https://docs.zephyrproject.org/latest/samples/modules/tflite-micro/hello_world/README.html
- https://docs.zephyrproject.org/latest/samples/modules/tflite-micro/magic_wand/README.html
