### ISSUE TITLE
kernel: mmu: compilation warnings when memory size is 0

### ISSUE THREAD

**Issue by ycsin** [zephyrproject-rtos/zephyr#64633]
**Describe the bug**

The following code might generate compilation warnings if:
- `CONFIG_SRAM_BASE_ADDRESS` is 0, or
- `CONFIG_SRAM_BASE_ADDRESS` is 0 and `CONFIG_SRAM_SIZE` is 0, or
- `CONFIG_KERNEL_VM_BASE` is 0, or
- `CONFIG_KERNEL_VM_BASE` is 0 and `CONFIG_KERNEL_VM_SIZE` is 0

as the assert test would be essentially comparing unsigned int against 0, which will be escalated into error in Twister, see [this CI run](https://github.com/zephyrproject-rtos/zephyr/actions/runs/6705912230/job/18221509407?pr=63172).

https://github.com/zephyrproject-rtos/zephyr/blob/67676d8fbcf5d742bdc6bbf0635d79499fa66062/include/zephyr/sys/mem_manage.h#L193-L199

https://github.com/zephyrproject-rtos/zephyr/blob/67676d8fbcf5d742bdc6bbf0635d79499fa66062/include/zephyr/sys/mem_manage.h#L202-L209

https://github.com/zephyrproject-rtos/zephyr/blob/67676d8fbcf5d742bdc6bbf0635d79499fa66062/include/zephyr/sys/mem_manage.h#L226-L232

**To Reproduce**
1. Checkout `main` branch
2. In `sw_isr_table.h`, include additional `zephyr/device.h`, see https://github.com/zephyrproject-rtos/zephyr/pull/64630/commits/39e73a7c6b9e98a4a728597ff095f6b6c3bd5581
3. `west build -b nrf5340bsim_nrf5340_cpuapp -p always -T samples/subsys/logging/multidomain/sample.logging.multidomain.ipc_static_vrings.simu`

**Expected behavior**
Should compile without error nor warnings regardless of the configuration & without header dependency.

**Impact**
Blocking #63172

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: Zephyr SDK
 - Commit SHA or Version used: 639d1f803b

**Additional context**

While this issue doesn't appear directly in `main` for some reason, including an additional `zephyr/device.h` in the `sw_isr_table.h` seems to 'reveal' the underlying issue.

**Comment by MaureenHelm** [comment]
@andyross please raise the priority if needed

**Comment by ycsin** [comment]
Update:

This issue only exists in #63172 and can't repro on `main`, see https://github.com/zephyrproject-rtos/zephyr/pull/64630#issuecomment-1787639513

**Comment by nashif** [comment]
> Update:
> 
> This issue only exists in #63172 and can't repro on `main`, see [#64630 (comment)](https://github.com/zephyrproject-rtos/zephyr/pull/64630#issuecomment-1787639513)

then we should close this as a non bug

**Comment by ycsin** [comment]
> > Update:
> > This issue only exists in #63172 and can't repro on `main`, see [#64630 (comment)](https://github.com/zephyrproject-rtos/zephyr/pull/64630#issuecomment-1787639513)
> 
> then we should close this as a non bug

This might still be a bug, #63172 probably just uncovered it - somehow the compiler decides to compile that part of code when `sw_isr_tables.h` includes `device.h`
