### ISSUE TITLE
report_excluded_tests from Twister's TestPlan is doomed to fail

### ISSUE THREAD

**Issue by LukaszMrugala** [zephyrproject-rtos/zephyr#64644]
**Describe the bug**
`report_excluded_tests()` in the `TestPlan` class attempts to subtract a set from a list, which is an illegal operation.

Code in question:
https://github.com/zephyrproject-rtos/zephyr/blob/67676d8fbcf5d742bdc6bbf0635d79499fa66062/scripts/pylib/twister/twisterlib/testplan.py#L389-L398

**To Reproduce**
1. Run `report_excluded_tests()`

**Expected behavior**
Report is printed out.

**Impact**
Report method is useless.

**Logs and console output**
```python
    def report_excluded_tests(self):
        all_tests = self.get_all_tests()
        to_be_run = set()
        for _, p in self.instances.items():
            to_be_run.update(p.testsuite.cases)

>       if all_tests - to_be_run:
E       TypeError: unsupported operand type(s) for -: 'list' and 'set'
```
.
**Environment (please complete the following information):**
 - Commit SHA or Version used: bc43e890fd7a6035438a47b8853b6fe652472da2

**Additional context**
Proposed change:
```python
 def report_excluded_tests(self): 
     all_tests = self.get_all_tests() 
     to_be_run = set() 
     for _, p in self.instances.items(): 
         to_be_run.update(p.testsuite.cases) 
  
     unrun = set(all_tests) - to_be_run
     if unrun: 
         print("Tests that never build or run:") 
     for not_run in unrun: 
         print("- {}".format(not_run)) 
```

**Comment by henrikbrixandersen** [comment]
@LukaszMrugala Please make a habit of 1) using the bug template when reporting bugs, and 2) submit code change proposals as pull requests.
