### ISSUE TITLE
drivers: console can leave characters in UART buffer if using server hooks

### ISSUE THREAD

**Issue by mgolu** [zephyrproject-rtos/zephyr#64661]
**Describe the bug**

When using `CONFIG_UART_CONSOLE_DEBUG_SERVER_HOOKS`, if there are multiple characters in the buffer when the ISR is called, not all characters are processed if the server hook returns non-zero (i.e. indicates that the console shouldn't process this character).

What target platform are you using?
nRF5340

What have you tried to diagnose or workaround this issue?
I changed this line, which currently is `return;` to `continue;` so that the `while` loop continues with the next character. This fixed the issue:

https://github.com/zephyrproject-rtos/zephyr/blob/d89938f4b978c3a9a7f8f711b0b65c7cca983d3e/drivers/console/uart_console.c#L477

**To Reproduce**

Create a project that uses the Console.
Add a debug server hook that prints one character at a time, and returns 1.
Use USB as the Console to send multiple characters before an ISR.
Watch characters be dropped

**Impact** 
Major bug.

**Environment (please complete the following information):**

OS: Linux
Toolchain: nRF Connect SDK v2.5.0

**Comment by henrikbrixandersen** [comment]
Please use our bug template when reporting bugs. You need to edit this issue to include the information requested in https://github.com/zephyrproject-rtos/zephyr/blob/main/.github/ISSUE_TEMPLATE/001_bug_report.md

**Comment by mgolu** [comment]
Thank you for pointing out the template, I updated the issue.

**Comment by henrikbrixandersen** [comment]
Thank you. I see you are referencing NCS v2.5.0. Can you reproduce this issue on mainline Zephyr? If not, please report it against NCS using the Nordic DevZone.

**Comment by mgolu** [comment]
Yes, the issue is also in main:
https://github.com/zephyrproject-rtos/zephyr/blob/main/drivers/console/uart_console.c#L477

**Comment by henrikbrixandersen** [comment]
@anangl Please raise the priority (and perhaps reassign) if this affects multiple platforms.

**Comment by carlescufi** [comment]
@mgolu could you please open a Pull Request with the change you suggest in the description (i.e. replace `return` with `continue`)? Thanks!
