### ISSUE TITLE
[riscv-privileged] PLIC is not compliant with the Spec

### ISSUE THREAD

**Issue by amr-sc** [zephyrproject-rtos/zephyr#64675]
**Describe the bug**

RISC-V PLIC driver no more conforms to the Spec after the 8db1a5a, see https://github.com/zephyrproject-rtos/zephyr/pull/63273

Trigger Type register is not defined in the recent PLIC Spec and so is not compliant with RISC-V Privileged Standard: https://github.com/riscv/riscv-plic-spec/blob/master/riscv-plic-1.0.0.pdf
IMHO this is a miss in the Spec and it results in a situation when all the vendors who support Triggering type configuration implement it in a proprietary way, using the custom offsets and custom codes for the triggering types.

So until the Trigger Type becomes a standard, it would be nice if we leave a room for flexibility here: by default PLIC should be compliant with the Spec while the Trigger Type register could be optionally enabled  as an extension for particular platforms. 

**Environment**
Zephyr v3.5

* Page: `project/issues`
* Version: main
* SHA-1: 8db1a5add221b5e47ad4e01dfcb3b4064a8299f4

**Comment by ycsin** [comment]
This is currently being escalated, see https://github.com/riscv/riscv-plic-spec/issues/52, are you using some PLIC that has a different offset for the trigger type registers?

**Comment by amr-sc** [comment]
Hi @ycsin , 

> This is currently being escalated, see [riscv/riscv-plic-spec#52](https://github.com/riscv/riscv-plic-spec/issues/52),

Thanks! Nice to know there is already a ticket for the RISC-V Spec.

>  are you using some PLIC that has a different offset for the trigger type registers?

Right, we have some similar register called IRQ triggering mode and it has different offset: 
https://github.com/syntacore/zephyr/blob/sc/main-3.4/soc/riscv/riscv-privileged/syntacore-scr/common/plic.c

We implemented it as a proprietary SoC-specific extension for a regular standard PLIC. 
It's not yet upstreamed but we are working in this direction
