### ISSUE TITLE
[doc] Documentation issue in 'connectivity/usb/host/api/uhc'

### ISSUE THREAD

**Issue by GauravPathak-eaton** [zephyrproject-rtos/zephyr#64677]
Describe the bug: USB host (STM32H743) not able to communicate with USB device (Pen drive - Mass storage class).

<< Please describe the issue here >>
I am using STM32H7 hal & ll (low level) driver files in Zephyr.
1. STM32H743 act as USB host & USB based Pen drive is connected to Nucleo-H743ZI2 board.
2. STM32H7 able to detect the Pen drive.
3. while starting the Enumeration, I am receiving the STALL error from USB device (Pen drive).
4. 
<< You may also want to update the automatically generated issue title above. >>

**Environment**
1. Zephyr V3.2.0 with STM32H7 Hal & LL (Low Level) driver files.
2. Eclipse as IDE.

Thanks for your support.

**Comment by erwango** [comment]
USB Host is not yet supported on STM32/Zephyr. Closing
