### ISSUE TITLE
[tutorial] %HOMEPATH% is missing

### ISSUE THREAD

**Issue by mrx23dot** [zephyrproject-rtos/zephyr#64682]
I'm following 
https://docs.zephyrproject.org/latest/develop/getting_started/index.html

but  %HOMEPATH% doesn't exist in win10 powershell.

```
(.venv) PS C:\Users\xxx\zephyrproject> pip install -r %HOMEPATH%\zephyrproject\zephyr\scripts\requirements.txt
ERROR: Could not open requirements file: [Errno 2] No such file or directory: '%HOMEPATH%\\zephyrproject\\zephyr\\scripts\\requirements.txt'
```

It does in cmd, but then I have to reactivate venv.
Would be great to simply avoid using powershell.

Anyway tutorial needs updating

**Comment by nordicjm** [comment]
Powershell is not supported, this is detailed on that page:
> These instructions must be run in a cmd.exe command prompt. The required commands differ on PowerShell.

**Comment by nordicjm** [comment]
If you are using python 3.12 then you need to get python 3.11

**Comment by kartben** [comment]
> ?? only constrain mentioned was ![image](https://user-images.githubusercontent.com/4163396/279659664-71055a57-9345-4c26-9571-7dfa4339c59c.png)
> 
> no version constrain was specified during: `choco install ninja gperf python git dtc-msys2 wget 7zip`
> 
> so it installed 3.12, now you telling me it's too new?
> 
> Tutorial needs updating either way. Currently it seems impossible for someone to install Zephyr on Windows, maybe on linux it's 2lines. I'm simply following the tutorial.

I'll update the guide to document the (hopefully very temporary) limitation to Python <3.12 - I believe at this point we'd only need https://github.com/trezor/cython-hidapi/issues/160 to be fixed.

Regarding the confusion due to some mentions of Powershell, #64726 will be taking care of that.
