### ISSUE TITLE
Update the documentation for Sipeed longan nano

### ISSUE THREAD

**Issue by Rhvarrier** [zephyrproject-rtos/zephyr#64759]
Driver support for SPI seems to have been added for this board but the [documentation](https://docs.zephyrproject.org/latest/boards/riscv/longan_nano/doc/index.html) still does not list SPI.

**Comment by henrikbrixandersen** [comment]
@Rhvarrier Are you able to confirm that SPI is now supported by testing it? If so, please submit a pull request for updating the board documentation.

**Comment by kartben** [comment]
@Rhvarrier Please see previous comment - would be great to have a PR for sure! Thanks.

**Comment by maxinbjohn** [comment]
@Rhvarrier  Please comment on this documentation change. Do we need further changes?
