### ISSUE TITLE
NXP: hal: `reinterpret_cast<…>(…) is not a constant expression` in enum variants

### ISSUE THREAD

**Issue by ithinuel** [zephyrproject-rtos/zephyr#64784]
`soc_clk_freq.h` and `ccm_imx7d.h` define variants with value generated from macros.
When building in c++ context, the compiler rejects the construct.

This was discovered on `warp7_m4` but applies to any board using `mcimx7_m4`.

Changing the affected enums with `#define` does solve the issue.

**To Reproduce**

1. add `#include "soc.h"` to `tests/lib/cpp/cxx/src/main.cpp`
2. build for `warp7_m4`
5. See error

**Expected behavior**
The test to build & run successfully.

**Impact**
Prevents cpp sources from including `cmsis_core.h` and from benifitting from the instrinsics.

**Comment by dleach02** [comment]
@ithinuel  can you post the actual error? When I run the build for tests/lib/cpp/cxx I get an error on the linker step where something doesn't fit.

**Comment by ithinuel** [comment]
Using `west twister -n -p warp7_m4 -T tests/lib/cpp/cxx` on 

```diff
diff --git a/tests/lib/cpp/cxx/src/main.cpp b/tests/lib/cpp/cxx/src/main.cpp
index 43bc14f65a..a31ea7299f 100644
--- a/tests/lib/cpp/cxx/src/main.cpp
+++ b/tests/lib/cpp/cxx/src/main.cpp
@@ -85,6 +85,8 @@

 #include <zephyr/ztest.h>

+#include <soc.h>
+
 class foo_class {
 public:
        foo_class(int foo) : foo(foo) {}
```

[result.txt](https://github.com/zephyrproject-rtos/zephyr/files/13877136/result.txt)
[build.log](https://github.com/zephyrproject-rtos/zephyr/files/13877145/build.log)
[build.log](https://github.com/zephyrproject-rtos/zephyr/files/13877148/build.log)

**Comment by dleach02** [comment]
@ithinuel can you provide a PR to the HAL_NXP with your recommended fix?

**Comment by ithinuel** [comment]
Unfortunately no, I do not have the expertise of C++ to do that.
This is why I reported this as an issue rather than creating a PR to fix it directly 🙁

**Comment by jlh-makeen** [comment]
Experiencing the same issue, prior to 

To reproduce:
```
cd ~/zephyrproject/zephyr/samples/cpp/cpp_synchronization/
west build -p always -b colibri_imx7/mcimx7d/m4
```

Was compiling at commit (last time of my fork rebasin):
2b549daabc9d2cddda3e22c6ec1f5b27ea1997ad

If someone knows what happened to the build config files or toolchain in the meantime that would probably help solving the issue.

**Comment by JiafeiPan** [comment]
Hi, @ithinuel and @jlh-makeen, I created one PR to fix this issue: https://github.com/zephyrproject-rtos/zephyr/pull/72047
But I have no imx7d board, so would you please help to verify the patch works although this PR has fixed building errors, but let's make sure it actually works on real board. thanks.

**Comment by decsny** [comment]
it looks like this issue was not linked to the PR that fixed it, I believe it was fixed, reopen if that is not the case
