### ISSUE TITLE
Setting T1S ETH (e.g. PLCA) parameters from user program

### ISSUE THREAD

**Issue by lmajewski** [zephyrproject-rtos/zephyr#64844]
**Current state:**
The OA TC6 T1S implementation (for LAN8651) has been posted as PR https://github.com/zephyrproject-rtos/zephyr/pull/63614
It requires some extra information - like `PLCA; node_id, node_count, burst_count, burst_timer, etc.`, which need to be  provided for correct operation of T1S ethernet.

As presented in https://github.com/zephyrproject-rtos/zephyr/pull/63614 - it is now done via device-tree.
However, it is not flexible enough - as there may be up to 8 different T1S devices connected together and each one will
receive its own PLCA "slot".

**The problem:**
Allow user program to adjust those parameters during system initialization.

**The solution:**
It looks like the most straightforward solution would be to mimic the code to change MAC address (or enable ETH promiscous mode) in the system.
To be more specific - `CONFIG_NET_L2_ETHERNET_MGMT=y` would be used and `.set_config()` callback (in the ETH device driver) from `struct ethernet_api`. Such approach is already used in testing the OA TC6 PR (https://github.com/lmajewski/zephyr/commit/96a35ced36776a4de94fa238f887e039a3b59ef3)

The `enum ethernet_config_type` would be extended to have e.g. `ETHERNET_CONFIG_TYPE_T1S_{PLCA}` and `struct ethernet_config` to provide `PLCA` parameters.

**Describe alternatives you've considered:**
The `.set_config()` approach seems to be the most straightforward one. However, I could export to user space the `struct lan865x_config` structure and modify its values. However, this requires the driver to restart the device itself anyway.

**Comment by jukkar** [comment]
Using `.set_config()` sounds like a good plan, +1 to that.
