### ISSUE TITLE
[Backport] LPC55XXX Series system clock hw cycles per sec configuration is wrong

### ISSUE THREAD

**Issue by decsny** [zephyrproject-rtos/zephyr#64865]
**Describe the bug**
LPC 55xxx series system timer hw clock cycle configuration is wrong

**Impact**
System time on LPC55xxx series is recorded as 150% of reality

see #64787 for details and fix, affects 3.5 too

**Comment by henrikbrixandersen** [comment]
Closing as https://github.com/zephyrproject-rtos/zephyr/pull/64835 was merged.
