### ISSUE TITLE
gcc optimizes calloc to an infinite recursive call when CONFIG_SPEED_OPTIMIZATION=y

### ISSUE THREAD

**Issue by talih0** [zephyrproject-rtos/zephyr#64941]
gcc is optimizing out calloc to an infinite recursive call
when CONFIG_COMMON_LIB_CALLOC=y and CONFIG_SPEED_OPTIMIZATIONS=y

See godbolt example (credit @gramsay0 ):
https://godbolt.org/z/s4E9csMa4

@gramsay0 has the following explanation for infinite call:
"I think GCC version 12 -O2 finds and replaces certain code with C std library code.
i.e. a for loop setting values to zero will be replaced with memset, or in this case a call to malloc + memset is replaced by calloc.
The problem being the call to malloc + memset is calloc... so it starts recursing.
I think this would only effect C libraries with CONFIG_COMMON_LIBC_CALLOC=y and CONFIG_COMPILER_FREESTANDING=n (i.e. picolibc)."

**Environment:**
 - OS: Linux
 -  Zephyr SDK (16.1)

To reproduce: 
QEMU board (CONFIG_COMMON_LIBC_CALLOC=y and  CONFIG_SPEED_OPTIMIZATIONS=y) with the following code:
printk("%p\n", calloc(1, 1));

**Comment by gramsay0** [comment]
@talih0 this is my github account, not sure who you're crediting 😂

Discord link: https://discord.com/channels/720317445772017664/720317445772017667/1171557752376660048
