### ISSUE TITLE
Question: Is dynamical module loader supported in Zephyr? Or any plan?

### ISSUE THREAD

**Issue by xwang98** [zephyrproject-rtos/zephyr#6496]
From the introduction materials, it seems this feature is not supported yet. Can anyone confirm this? 

If it is not supported now, I wonder if there is any plan to support it in future roadmap?

**Comment by xwang98** [comment]
Just saw it is in the  roadmap "Parking lot"

**Comment by nashif** [comment]
@xwang98 what platforms are you targeting? What exactly is your usecase?

**Comment by carlescufi** [comment]
There's an issue already for this, please comment here: https://github.com/zephyrproject-rtos/zephyr/issues/2746

**Comment by henrikbrixandersen** [comment]
I suggest we close this issue and track the feature request (along with use cases) in #2746.

**Comment by nashif** [comment]
It is not supported.
