### ISSUE TITLE
Linking errors while compiling the `echo_server` sample with netusb overlay on stm32

### ISSUE THREAD

**Issue by roygedge** [zephyrproject-rtos/zephyr#64981]
Hey!
I'm experiencing some difficulties with stm32f411e_disco , I'm trying to compile the echo_server sample with the netusb overlay, however it throws me linking errors such as:

>  /home/c456913/zephyr-sdk-0.16.3/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/../../../../arm-zephyr-eabi/bin/ld.bfd:zephyr/subsys/usb/device/class/netusb/libsubsys__usb__device__class__netusb.a(function_ecm.c.obj): in functionecm_read_cb':
> /home/c456913/zephyrproject/zephyr/subsys/usb/device/class/netusb/function_ecm.c:295:undefined reference tonet_pkt_rx_alloc_with_buffer'
>  /home/c456913/zephyr-sdk-0.16.3/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/../../../../arm-zephyr-eabi/bin/ld.bfd:/home/c456913/zephyrproject/zephyr/subsys/usb/device/class/netusb/function_ecm.c:302: undefined reference tonet_pkt_write'
> /home/c456913/zephyr-sdk-0.16.3/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/../../../../arm-zephyr-eabi/bin/ld.bfd: /home/c456913/zephyrproject/zephyr/subsys/usb/device/class/netusb/function_ecm.c:304: undefined reference to net_pkt_unref' /home/c456913/zephyr-sdk-0.16.3/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/../../../../arm-zephyr-eabi/bin/ld.bfd: zephyr/subsys/usb/device/class/netusb/libsubsys__usb__device__class__netusb.a(function_ecm.c.obj): in function ecm_send':
> /home/c456913/zephyrproject/zephyr/subsys/usb/device/class/netusb/function_ecm.c:260: undefined reference to `net_pkt_read'
> 

Does that mean this board doesn't support netusb and if so how can I fix that?

**Comment by Desvauxm-st** [comment]
@roygedge
can you give me more information
- what is the exact command you used:
like  : west build -p always -b   stm32f411e_disco  samples/net/sockets/echo_server/
- if you add some overlay can you give me the file you use
- do you have already use with success  the sample you hope to use  with another board ?
