### ISSUE TITLE
nios2 msgdma semaphore usage

### ISSUE THREAD

**Issue by teburd** [zephyrproject-rtos/zephyr#64985]
The nios2 msgdma DMA driver contributed by Intel uses a semaphore for synchronization around channel state transition and configuration functions. This is unlike most of the other drivers in the tree and the expectation is that all drivers in the tree at least adhere to a few simple rules around when dma calls are allowed and the what the behavior (in terms of state transitioning) is.

See https://github.com/zephyrproject-rtos/zephyr/pull/64982 to get a clearer picture of what the expectations of each DMA driver are

**Comment by teburd** [comment]
I don't own nios2 and do not have time to resolve this issue for an architecture/platform I do not maintain, unassigned myself

**Comment by nashif** [comment]
Planning to remove nios2 support after 3.6, so will not invest time on fixing a driver.
