### ISSUE TITLE
doc: samples/compression/lz4/README should indicate how to enable lz4 module

### ISSUE THREAD

**Issue by kartben** [zephyrproject-rtos/zephyr#65127]
**Describe the bug**

The documentation for the LZ4 sample needs to be updated to indicate that LZ4 is an optional module, and should give guidance on how to activate it.

**Environment**

* Page: `samples/compression/lz4/README`
* Version: main
* SHA-1: 588e0a69dc3c3d907b299878ae558876d0839b9b

**Comment by parthitce** [comment]
https://github.com/zephyrproject-rtos/zephyr/pull/76184 address the document update
