### ISSUE TITLE
Scheduler needs spinlock-based synchronization

### ISSUE THREAD

**Issue by andyross** [zephyrproject-rtos/zephyr#6521]
The scheduler API is still written to assume locking with irq_lock(), which in SMP is the global lock.  That's a fairly serious performance problem as the idle threads currently need to spin on the scheduler waiting for a runnable thread to appear (ESP-32 lacks an interprocessor interrupt AFAICT), which then spams the locking for the whole system.

This needs to be the first subsystem cleaned up to use fine-grained locking.  Requires a few API changes as right now some of the calls rely on the caller to have already grabbed a lock.

Consider combining with work on https://github.com/zephyrproject-rtos/zephyr/issues/5132 and https://github.com/zephyrproject-rtos/zephyr/issues/2422 , both of which involve scheduler design changes.

**Comment by lpereira** [comment]
I remember seeing interprocessor interrupts while reading through the NuttX ESP32 port.  Let me see if I can find it.  Found some things; not sure if they're useful for this, though:

https://bitbucket.org/nuttx/nuttx/src/3a95464153e5d5cd3d0ecdb66a695cc7b21be6f6/arch/xtensa/src/esp32/esp32_cpustart.c?at=master&fileviewer=file-view-default

https://bitbucket.org/nuttx/nuttx/src/3a95464153e5d5cd3d0ecdb66a695cc7b21be6f6/arch/xtensa/src/esp32/esp32_intercpu_interrupt.c?at=master&fileviewer=file-view-default
