### ISSUE TITLE
doc: Documentation lacking in 'services/crypto/index'

### ISSUE THREAD

**Issue by ielpo** [zephyrproject-rtos/zephyr#65230]
**Describe the bug**
The list of included Cryptographic libraries is outdated: as I understood MbedTLS is now also supported?

**Environment**

* Page: `services/crypto/index`
* Version: main
* SHA-1: fb892e0fbf62a4d9ba4c27bb7a16f2a4668c03e4

**Comment by ceolin** [comment]
Indeed, only TinyCrypt was listed. This was recently updated with the PSA Crypto adoption.

This issue is no longer needed. @ielpo thanks for reporting it !
