### ISSUE TITLE
Support for more SOC_PART_NUMBER options under the SOC_SERIES_ESP32S3

### ISSUE THREAD

**Issue by naNEQ** [zephyrproject-rtos/zephyr#65302]
**Describe the solution you'd like**
I noticed that not all parts from the ESP32-S3-WROOM series are included as options for SOC_PART_NUMBER [here](https://github.com/zephyrproject-rtos/zephyr/blob/main/soc/xtensa/espressif_esp32/esp32s3/Kconfig.soc).

That is relevant, because different part numbers have different PSRAM sizes (and/or Flash sizes).

From a quick look we are missing the following:

- SOC_ESP32S3_WROOM_N4R2
- SOC_ESP32S3_WROOM_N8R2
- SOC_ESP32S3_WROOM_N16R2
- SOC_ESP32S3_WROOM_N16R8

Except for the Zephyr/soc folder, changes have to be made also to Zephyr/dts folder and more specifically [here](https://github.com/zephyrproject-rtos/zephyr/tree/main/dts/xtensa/espressif/esp32s3), where new .dtsi files need to be added for the new part numbers, stating the Flash and PSRAM sizes.

**Additional context**
Taken from [here](https://www.espressif.com/sites/default/files/documentation/esp32-s3-wroom-1_wroom-1u_datasheet_en.pdf).
![esp32_wroom_socs](https://github.com/zephyrproject-rtos/zephyr/assets/135322804/c74e039e-e3bc-4b34-a11c-6a9d7aa312d5)

**Comment by marekmatej** [comment]
Hi @naNEQ, thanks for bringing this. Please take a look, and comment 
 https://github.com/zephyrproject-rtos/zephyr/pull/65319
