### ISSUE TITLE
coap-server: Canceling Observation not working

### ISSUE THREAD

**Issue by baw-serafin** [zephyrproject-rtos/zephyr#6534]
On release 1.10 cancelling observation does not work

reproduce
--------------
* Get latest release (1.10)
* compile coap_server example with  `cmake -DBOARD=qemu_x86 ../..
* run in in coap with instructions from http://docs.zephyrproject.org/1.10.0/subsystems/networking/qemu_setup.html?highlight=networking%20qemu
* observe /obs resource with client (I used copper)
* make a lazy cancel (reset on notification)

expected
------------
* Notification should stop

result
--------
* Notification still arrive all 5s

I also tried explicit cancel (get with observe=1) but no result either

**Comment by rveerama1** [comment]
@baw-serafin can you please try with latest upstream and share wireshark logs?

**Comment by baw-serafin** [comment]
@rveerama1 Thx for the fix, sorry I forgot to provide wireshark. COAP is unfortunatly not my top priority at the moment
