### ISSUE TITLE
net: Networking initialisation doesn't check device init status

### ISSUE THREAD

**Issue by krish2718** [zephyrproject-rtos/zephyr#65423]
**Describe the bug**
Zephyr has a framework to check if a device is ready i.e., successfully initialised and ready to use. But networking subsystem in the initialisation `net_init` doesn't propagate the network device initialisation errors (most functions in that path return `void`), so, even though a network device initialisation fails the check `device_is_ready(net_dev)` returns `ready`.

**To Reproduce**
1. Fake a failure in any network device init, note the return value is still void.
2. the `net_if_up` is still called (if auto start is set), and check for `device_is_ready()` it returns success.

**Expected behavior**
All network device errors should be propagated up.

**Impact**
As the standard API to check for readiness doesn't work, need to resort to custom checks.

**Logs and console output**
Screenshot of callstack during init.

![image](https://github.com/zephyrproject-rtos/zephyr/assets/100136718/551157fb-84f7-42e6-9cfb-eb5ef2ffc3e2)

**Additional context**
None.

**Comment by jukkar** [comment]
The problem in network upper stack is that the only way to recover from the network device init failure is to reboot the device. So it is expected in network upper layers that the net device is ready when it is needed. The network device would need to make sure that it is ready before letting the system continue booting.
We can certainly print errors if `device_is_ready()` returns false but it does not help much. We could start to wait until `device_is_ready()` return true, but this requires that the network device driver is really doing something behind the scene to make the device ready. So in this respect, the driver could make sure itself that it is ready before letting network init to be done.
