### ISSUE TITLE
ARM Cortex R Architecture support

### ISSUE THREAD

**Issue by timork** [zephyrproject-rtos/zephyr#6545]
Hi,

Cortex R popular architecture widely used in real-time sensitive applications in automotive, storage controllers (HDD and SSD), robotics, aerospace and other areas.
Since no really popular RTOS have support of Cortex R arch it can widely extend Zephyr applications coverage.

SoC platforms with Cortex R CPUs available for mass markets:
Cypress Traveo 
TI TMS570L
TI Hercules RM

and endless number of closed infrastructure ASICs 

Thanks

**Comment by salerio-gs** [comment]
I would add the Xilinx US+ MPSoC (as found on 96 Boards Ultra96), this will become popular I think.

**Comment by galak** [comment]
> I would add the Xilinx US+ MPSoC (as found on 96 Boards Ultra96), this will become popular I think.

That would be awesome!

**Comment by galak** [comment]
> I would add the Xilinx US+ MPSoC (as found on 96 Boards Ultra96), this will become popular I think.

@salerio-gs is this something you are looking at or just saying would be nice?
