### ISSUE TITLE
Testplan platform key checking may not work at all

### ISSUE THREAD

**Issue by LukaszMrugala** [zephyrproject-rtos/zephyr#65477]
**Describe the bug**
Lines 845-870 of the testplan module describe our approach to filtering test platforms with regard to specified platform key fields.

However, the code seems to be incorrect. The explanatory text is describing one approach, the variable names suggest a different approach and the code itself does something else entirely, checking whether a testsuite platform key list has `None`s in it or `'na'`s. From context, I think it is a bug and instead the code should check whether given platform has all fields specified in the testsuite.

**To Reproduce**
N/A

**Expected behavior**
Platform key checking should verify that all required platform keys exist on a given platform.

**Impact**
Platform key functionality seems to be effectively missing.

**Logs and console output**
N/A

**Environment (please complete the following information):**
 - OS: Linux
 - 26fd55e0a750305fbd5d9db750225d7e707458ae

**Additional context**
https://github.com/zephyrproject-rtos/zephyr/blob/6b87eedee02020392270305fac8258557598b074/scripts/pylib/twister/twisterlib/testplan.py#L845-L870
A PR is currently in the works.

**Comment by nashif** [comment]
@teburd  FYI
