### ISSUE TITLE
drivers: counter: stm32_rtc: `rtc_stm32_read` potential overflow issue

### ISSUE THREAD

**Issue by JiapengLi** [zephyrproject-rtos/zephyr#65494]
**Describe the bug**

rtc_time and rtc_date are not read in a way to avoid overflow. 

```
static uint32_t rtc_stm32_read(const struct device *dev)
{
...
	/* Read time and date registers */
	rtc_time = LL_RTC_TIME_Get(RTC);
#if !defined(COUNTER_NO_DATE)
	rtc_date = LL_RTC_DATE_Get(RTC);
#endif
...

}
```

**To Reproduce**
it can happen in extreme cases, for example rtc_time overflow in serveral cpu cycles after read, then the read back rtc_date and rtc_time will be not matched. The returned ticks suffer a big increase, and lead ticks revert.

**Expected behavior**
Continuous read and compare the two result to filter out wrong data.

**Impact**
N/A

**Logs and console output**
N/A

**Environment (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by erwango** [comment]
My understanding is that this was fixed recently, see https://github.com/zephyrproject-rtos/zephyr/commit/16370a259a3642273b8cdc3faaf7d8e2b9e772c2
