### ISSUE TITLE
Two SPI device control errors with one cs-gpio pin.

### ISSUE THREAD

**Issue by 2songh** [zephyrproject-rtos/zephyr#65504]
**To Reproduce**

Zephyr Version: 3.4
Board: STM32L433
SPI Device: MAX31865 (1, 2)

1. west build -b "stm32l433"
2. west flash

**Describe the bug**

I'm trying to use two spi devices in reverse mode using one chip select pin.

* device tree
![image](https://github.com/zephyrproject-rtos/zephyr/assets/126455296/52297b74-b6de-48cc-9ec6-db237cb58921)

When configured like this and spi_read() on device 1 and device 2,
Action is performed only with CS_ACTIVE_LOW.

![image](https://github.com/zephyrproject-rtos/zephyr/assets/126455296/8646c80d-0fb4-40b7-8bc1-0a03aa7a0a73)

This causes problems with the return values ​​of the two devices being the same.
I want CS_ACTIVE_LOW and CS_ACTIVE_HIGH to alternate.

There is no problem when configuring and using the devices one by one.

* **CS_ACTIVE_LOW**
![image](https://github.com/zephyrproject-rtos/zephyr/assets/126455296/04b7b799-3d36-43d0-b669-ac9fe0a072f5)
![image](https://github.com/zephyrproject-rtos/zephyr/assets/126455296/34c87284-bac1-41e7-b50f-3b05a3ddcafc)

* **CS_ACTIVE_HIGH**
![image](https://github.com/zephyrproject-rtos/zephyr/assets/126455296/ce7cc93f-edb8-4832-82ef-7e3d2304d6c7)
![image](https://github.com/zephyrproject-rtos/zephyr/assets/126455296/6b628612-6f73-47a8-af29-fd797cc62fd0)

Please give me a solution or advice on this issue.

**Comment by fabiobaltieri** [comment]
That's a bit of an odd use case, I think  you may make it work by writing a driver implementing the GPIO API handling the two chip select as if they were two different GPIOs and then driving a single GPIO as an output with whatever logic you need. Prob not worth upstreaming though, it's a bit of an odd use case, not sure we want to encourage that.

**Comment by fabiobaltieri** [comment]
Would not call this a bug though.

**Comment by 2songh** [comment]
> That's a bit of an odd use case, I think you may make it work by writing a driver implementing the GPIO API handling the two chip select as if they were two different GPIOs and then driving a single GPIO as an output with whatever logic you need. Prob not worth upstreaming though, it's a bit of an odd use case, not sure we want to encourage that.

First of all, thank you very much for answering.
I have a few additional questions.

We already used this method in Zephyr version 2.4, it was no problem.
Has anything changed since the version was upgraded?

*****

It shares our circuit using two MAX31865 sensors.

![image](https://github.com/zephyrproject-rtos/zephyr/assets/126455296/10816e99-b047-4342-ae15-7711800ed3cf)

*****

These two share the same SPI Line.

![image](https://github.com/zephyrproject-rtos/zephyr/assets/126455296/67803b73-5c53-40cd-abd0-16b937318381)

*****

**Question**
1. Are there any differences between versions 2.4 and 3.4?
2. Is there any way to control it using one CS gpio?
3. Is adding a new CS Pin the best option?

**Comment by fabiobaltieri** [comment]
>     1. Are there any differences between versions 2.4 and 3.4?

Yeah one or two things:

```console
$ git diff --shortstat v2.4.0..v3.4.0
 27599 files changed, 2294837 insertions(+), 671014 deletions(-)
```

>     2. Is there any way to control it using one CS gpio?

If it used to work you could try and bisect, see if you can find what broke it, maybe something to do with `SPI_STM32_USE_HW_SS`?

>     3. Is adding a new CS Pin the best option?

If you have pins available it's certainly the more conventional option and less likely to cause issues, plus it's usually not a great idea to keep an SPI device selected all the time.

**Comment by tbursztyka** [comment]
Sounds like an STM32 issue to me (pehaps a gpio one, though unlikely)

**Comment by 2songh** [comment]
> Sounds like an STM32 issue to me (pehaps a gpio one, though unlikely)

Do you have any experience testing with boards other than STM32?

**Comment by FRASTM** [comment]
@2songh can you please check when the DTS has no spi2_nss declared in the <pinctrl-0> but <cs-gpios>
--> set either the CS by spi pin NSS _or_ GPIO control (not both)
