### ISSUE TITLE
up_squared: tests/subsys/logging/log_custom_header/logging.log_custom_header ASSERTION FAIL.

### ISSUE THREAD

**Issue by KamilxPaszkiet** [zephyrproject-rtos/zephyr#65516]
**Describe the bug**
`tests/subsys/logging/log_custom_header/logging.log_custom_header' ASSERTION FAIL.

**To Reproduce**
```twister --device-testing --hardware-map up2.map -s tests/subsys/logging/log_custom_header/logging.log_custom_header -vv```

**Logs and console output**
```
DEBUG   - DEVICE: >>Checking Media Presence......
DEBUG   - DEVICE: >>Media Present......
DEBUG   - DEVICE: Downloading NBP file...
DEBUG   - DEVICE: 
DEBUG   - DEVICE: Succeed to download NBP file.
DEBUG   - DEVICE: *** Zephyr EFI Loader ***
DEBUG   - DEVICE: RSDP found at 0x79c34000
DEBUG   - DEVICE: Zeroing 4907008 bytes of memory at 0x111000
DEBUG   - DEVICE: Copying 32768 data bytes to 0x1000 from image offset
DEBUG   - DEVICE: Copying 69632 data bytes to 0x100000 from image offset 32768
DEBUG   - DEVICE: Copying 2265088 data bytes to 0x5bf000 from image offset 102400
DEBUG   - DEVICE: Jumping to Entry Point: 0x1137 (48 31 c0 48 31 d2 48)
DEBUG   - DEVICE: ASSERTION FAIL [device_is_ready(uart_dev)] @ WEST_TOPDIR/zephyr/subsys/logging/backends/log_backend_uart.c:127
```

**Environment:**
- OS: Linux
- Toolchain: zephyr-sdk-0.16.3
- zephyr-v3.5.0-556-g530a3092feef

**Comment by jhedberg** [comment]
@KamilxPaszkiet looks like #62717, #62761 and this issue all have the same root cause (UART init level/priority is too late), so is it really worth to keep three issues open about it?
