### ISSUE TITLE
STM32 i2c multiple target address are ignored 

### ISSUE THREAD

**Issue by timwoolliscroft-opteran** [zephyrproject-rtos/zephyr#65527]
---
name: Bug report
about: Create a report to help us improve Zephyr
title: 'STM32 i2c multiple target address are ignored'
labels: bug
assignees: ''

---
**Describe the bug**
The secondary target address / configuration is ignored by the i2c_ll_stm32_v2.c driver in `stm32_i2c_slave_event()`

Removing the following line fixes the issue:
https://github.com/zephyrproject-rtos/zephyr/blob/a43e516ff2f7bc7091835bf9a97c979937a75366/drivers/i2c/i2c_ll_stm32_v2.c#L147

as it overrides the arbitration of the dual addressing done here:
https://github.com/zephyrproject-rtos/zephyr/blob/a43e516ff2f7bc7091835bf9a97c979937a75366/drivers/i2c/i2c_ll_stm32_v2.c#L138

And forces all data received on the secondary i2c address to be presented to the callbacks registered on the primary i2c address.

**To Reproduce**
Steps to reproduce the behaviour:
Make minimal i2c target test app, register 2 target configs into the driver and use an external device to stimulate the i2c bus.
```
static int target_write_requested(struct i2c_target_config *config)
{
	LOG_DBG("target_write_requested (0x%02x)\n", config->address);
	return 0;
}

static int target_read_requested(struct i2c_target_config *config, uint8_t *val)
{
	LOG_DBG("target_read_requested (0x%02x)\n", config->address);
	return 0;
}

static int target_write_received(struct i2c_target_config *config, uint8_t val)
{
	LOG_DBG("target_write_received (0x%02x)\n", config->address);
	return 0;
}

static int target_read_processed(struct i2c_target_config *config, uint8_t *val)
{
	LOG_DBG("target_read_processed (0x%02x)\n", config->address);
	return 0;
}

static int target_stop(struct i2c_target_config *config)
{
	LOG_DBG("target_stop( 0x%02x)\n", config->address);	 
	return 0;
}

/* Driver callback functions */
static const struct i2c_target_callbacks target_callbacks = {
	.write_requested = target_write_requested,
	.read_requested = target_read_requested,
	.write_received = target_write_received,
	.read_processed = target_read_processed,
	.stop = target_stop,
};
/* Driver configurations */
static const struct i2c_target_config cfg_1 = {
	.address = 0x54,
	.flags = 0,
	.callbacks = &target_callbacks
};
static const struct i2c_target_config cfg_2 =  {
	.address = 0x12,
	.flags = 0,
	.callbacks = &target_callbacks
};
int i2c_target_test_app(void){
	int ret;

	if(!device_is_ready(i2c_dev)){
		LOG_ERR("I2C device not found!\n");
		return 0;
	}
	ret = i2c_target_register(i2c_dev, &cfg_1);
	ret = i2c_target_register(i2c_dev, &cfg_2);
return 0;
}
```

**Expected behaviour**
On external stimulation / traffic the device should report the correct i2c device address. eg
`[00:00:14.496,000] <dbg> i2c_target_demo: target_write_requested: target_write_requested (0x54)`
and
`[00:00:14.496,000] <dbg> i2c_target_demo: target_write_requested: target_write_requested (0x12)`

**Impact**
Dual target address mode cannot be used.

**Logs and console output**
If applicable, add console logs or other types of debug information
e.g Wireshark capture or Logic analyzer capture (upload in zip archive).
copy-and-paste text and put a code fence (\`\`\`) before and after, to help
explain the issue. (if unable to obtain text log, add a screenshot)

**Environment (please complete the following information):**
 - Platform/board: stm32h7b3i_dk
 - OS: Linux
 - Toolchain: Zephyr SDK
 - Commit: 97956e402ec21965f6e8bf9aacd13bd342d2f889

**Additional context**

**Comment by henrikbrixandersen** [comment]
Please use our bug template when reporting bugs. You need to edit this issue to include the information requested in https://github.com/zephyrproject-rtos/zephyr/blob/main/.github/ISSUE_TEMPLATE/001_bug_report.md
