### ISSUE TITLE
samples/net/echo_client: Failed to connect to samples/net/echo_server for IPV4 test

### ISSUE THREAD

**Issue by tarunkum** [zephyrproject-rtos/zephyr#6564]
I was trying to test echo_server along with echo_client with two different frdm_k64f boards.
The steps I have followed for echo_server & echo_client is as below:

cd zephyr/samples/net/echo_client
mkdir build && cd build && cmake -GNinja -DBOARD=frdm_k64f ../
ninja
cp -vr outdir/frdm_k64f/zephyr.bin /run/media/MBED/

cd zephyr/samples/net/echo_server
mkdir build && cd build && cmake -GNinja -DBOARD=frdm_k64f ../
ninja
cp -vr outdir/frdm_k64f/zephyr.bin /run/media/MBED1/

•Here I am trying make one frdm_k64f as echo_client & other one as echo_server.

The configuration used for building the echo_server

# For Freedom board with ethernet support
	CONFIG_NETWORKING=y
	CONFIG_NET_LOG=y
	CONFIG_NET_IPV6=n
	CONFIG_NET_IPV4=y
	CONFIG_NET_DHCPV4=n
	CONFIG_NET_UDP=n
	CONFIG_NET_TCP=y
	CONFIG_NET_STATISTICS=y

	CONFIG_NET_PKT_RX_COUNT=50
	CONFIG_NET_PKT_TX_COUNT=50
	CONFIG_NET_BUF_RX_COUNT=50
	CONFIG_NET_BUF_TX_COUNT=50
	CONFIG_NET_IF_UNICAST_IPV6_ADDR_COUNT=3
	CONFIG_NET_IF_MCAST_IPV6_ADDR_COUNT=5
	CONFIG_NET_IF_UNICAST_IPV4_ADDR_COUNT=1
	CONFIG_NET_MAX_CONTEXTS=10

	CONFIG_INIT_STACKS=y
	CONFIG_SYS_LOG_SHOW_COLOR=y
	CONFIG_PRINTK=y

	CONFIG_NET_SHELL=y

	CONFIG_NET_APP_SERVER=y
	CONFIG_NET_APP_NEED_IPV6=n
	CONFIG_NET_APP_NEED_IPV4=y
	CONFIG_NET_APP_SETTINGS=y
	CONFIG_NET_APP_MY_IPV4_ADDR="192.0.2.1"
	CONFIG_NET_APP_MY_IPV6_ADDR="2001:db8::1"

The configuration used for building the echo_client
# For Freedom board with ethernet support
	CONFIG_NETWORKING=y
	CONFIG_NET_LOG=y
	CONFIG_NET_IPV6=n
	CONFIG_NET_IPV4=y
	CONFIG_NET_DHCPV4=n
	CONFIG_NET_UDP=n
	CONFIG_NET_TCP=y
	CONFIG_NET_STATISTICS=y

	CONFIG_NET_PKT_RX_COUNT=50
	CONFIG_NET_PKT_TX_COUNT=50
	CONFIG_NET_BUF_RX_COUNT=50
	CONFIG_NET_BUF_TX_COUNT=50
	CONFIG_NET_IF_UNICAST_IPV6_ADDR_COUNT=3
	CONFIG_NET_IF_MCAST_IPV6_ADDR_COUNT=5
	CONFIG_NET_IF_UNICAST_IPV4_ADDR_COUNT=1
	CONFIG_NET_MAX_CONTEXTS=10

	CONFIG_INIT_STACKS=y
	CONFIG_SYS_LOG_SHOW_COLOR=y
	CONFIG_PRINTK=y

	CONFIG_NET_L2_ETHERNET=y

	CONFIG_NET_SHELL=y

	CONFIG_NET_APP=y
	CONFIG_NET_APP_NEED_IPV6=n
	CONFIG_NET_APP_NEED_IPV4=y
	CONFIG_NET_APP_CLIENT=y
	CONFIG_NET_APP_SETTINGS=y
	CONFIG_NET_APP_MY_IPV4_ADDR="192.0.2.2"
	CONFIG_NET_APP_PEER_IPV4_ADDR="192.0.2.1"

	CONFIG_NET_APP_MY_IPV6_ADDR="2001:db8::2"
	CONFIG_NET_APP_PEER_IPV6_ADDR="2001:db8::1"

### Logs on echo_server
***** BOOTING ZEPHYR OS v1.11.0-rc3 - BUILD: Mar 12 2018 06:58:41 *****
Zephyr Shell, Zephyr version: 1.11.0-rc3
Type 'help' for a list of available commands
shell> [echo-server] [INF] build_reply_pkt: TCP IPv4 received 372 bytes
[dev/eth_mcux] [INF] eth_mcux_phy_event: Enabled 100M full-duplex mode.
[dev/eth_mcux] [DBG] eth_0_init: MAC 00:04:9f:7e:22:ce
***** BOOTING ZEPHYR OS v1.11.0-rc3 - BUILD: Mar 12 2018 06:58:41 *****
Zephyr Shell, Zephyr version: 1.11.0-rc3
Type 'help' for a list of available commands
shell> [dev/eth_mcux] [INF] eth_mcux_phy_event: Enabled 100M full-duplex mode.
[echo-server] [INF] build_reply_pkt: TCP IPv4 received 115 bytes

### Logs on echo_client
Type 'help' for a list of available commands
shell> [echo-client] [INF] init_app: Run echo client
[dev/eth_mcux] [INF] eth_mcux_phy_event: Enabled 100M full-duplex mode.
[dev/eth_mcux] [INF] eth_mcux_phy_event: Link down
[dev/eth_mcux] [DBG] eth_0_init: MAC 00:04:9f:d6:ea:12
***** BOOTING ZEPHYR OS v1.11.0-rc3 - BUILD: Mar 12 2018 06:58:55 *****
Zephyr Shell, Zephyr version: 1.11.0-rc3
Type 'help' for a list of available commands
shell> [dev/eth_mcux] [INF] eth_mcux_phy_event: Enabled 100M full-duplex mode.
[echo-client] [INF] init_app: Run echo client

In Client console I am not able to see any response back from server. Lilke the way I receive if I test for IPV6 on echo_client.
[echo-client] [DBG] compare_tcp_data: (0x20001f8c): Compared 54 bytes, all ok
[echo-client] [DBG] tcp_received: (0x20001f8c): IPv6: Sent 173 bytes, received 173 bytes

Please tell I need to do some changes in configuration in order to make it working.

**Comment by rveerama1** [comment]
@tarunkum Provided a fix https://github.com/zephyrproject-rtos/zephyr/pull/7580, I have tested with above configuration files with echo_server and echo_client running on two frdm_k64f boards also between qemu. Works fine.
