### ISSUE TITLE
samples/net/sockets/echo: Failed to connect to samples/net/echo_server for IPV6 test

### ISSUE THREAD

**Issue by tarunkum** [zephyrproject-rtos/zephyr#6565]
I was trying to test echo_server along with echo_client with two different frdm_k64f boards.
 The steps I have followed for server & client is as below:

Client :: zephyr/samples/net/echo_client
Server :: zephyr/samples/net/sockets/echo

cd zephyr/samples/net/echo_client
 mkdir build && cd build && cmake -GNinja -DBOARD=frdm_k64f ../
 ninja
 cp -vr outdir/frdm_k64f/zephyr.bin /run/media/MBED/

cd zephyr/samples/net/sockets/echo
 mkdir build && cd build && cmake -GNinja -DBOARD=frdm_k64f ../
 ninja
 cp -vr outdir/frdm_k64f/zephyr.bin /run/media/MBED1/

•Here I am trying make one frdm_k64f as client & other one as server.

The configuration used for building the server

For Freedom board with ethernet support

# General config
CONFIG_NEWLIB_LIBC=y

# Networking config
CONFIG_NETWORKING=y
CONFIG_NET_IPV4=n
CONFIG_NET_IPV6=y
CONFIG_NET_TCP=y
CONFIG_NET_SOCKETS=y
CONFIG_NET_SOCKETS_POSIX_NAMES=y

# Network driver config
CONFIG_TEST_RANDOM_GENERATOR=y

# Network address config
CONFIG_NET_APP_SETTINGS=y
CONFIG_NET_APP_NEED_IPV4=n
CONFIG_NET_APP_MY_IPV4_ADDR="192.0.2.1"
CONFIG_NET_APP_PEER_IPV4_ADDR="192.0.2.2"
CONFIG_NET_APP_MY_IPV6_ADDR="2001:db8::1"

# Network debug config
#CONFIG_NET_DEBUG_SOCKETS=y
CONFIG_SYS_LOG_NET_LEVEL=2
CONFIG_NET_APP_SERVER=y

The configuration used for building the echo_client

For Freedom board with ethernet support

# For Freedom board with ethernet support
CONFIG_NETWORKING=y
CONFIG_NET_LOG=y
CONFIG_NET_IPV6=y
CONFIG_NET_IPV4=n
CONFIG_NET_DHCPV4=n
CONFIG_NET_UDP=n
CONFIG_NET_TCP=y
CONFIG_NET_STATISTICS=y

CONFIG_NET_PKT_RX_COUNT=50
CONFIG_NET_PKT_TX_COUNT=50
CONFIG_NET_BUF_RX_COUNT=50
CONFIG_NET_BUF_TX_COUNT=50
CONFIG_NET_IF_UNICAST_IPV6_ADDR_COUNT=3
CONFIG_NET_IF_MCAST_IPV6_ADDR_COUNT=5
CONFIG_NET_IF_UNICAST_IPV4_ADDR_COUNT=1
CONFIG_NET_MAX_CONTEXTS=10

CONFIG_INIT_STACKS=y
CONFIG_SYS_LOG_SHOW_COLOR=y
CONFIG_PRINTK=y

CONFIG_NET_L2_ETHERNET=y

CONFIG_NET_SHELL=y

CONFIG_NET_APP=y
CONFIG_NET_APP_NEED_IPV6=n
CONFIG_NET_APP_NEED_IPV4=y
CONFIG_NET_APP_CLIENT=y
CONFIG_NET_APP_SETTINGS=y
CONFIG_NET_APP_MY_IPV4_ADDR="192.0.2.2"
CONFIG_NET_APP_PEER_IPV4_ADDR="192.0.2.1"

CONFIG_NET_APP_MY_IPV6_ADDR="2001:db8::2"
CONFIG_NET_APP_PEER_IPV6_ADDR="2001:db8::1"

Logs on echo_server

 BOOTING ZEP1.0-rc3 - BU 2018 08:23:Single-threaded TCP echo server waits for a connection on port 4242...
***** BUS FAULT *****
  Executing thread ID (thread): 0x20002444
  Faulting instruction address:  0xcd42
  Precise data bus error
  Address: 0x2d2100
Fatal fault in essential thread! Spinning...

Logs on echo_client

[dev/eth_mcux] [DBG] eth_0_init: MAC 00:04:9f:1c:84:b6
***** BOOTING ZEPHYR OS v1.11.0-rc3 - BUILD: Mar 12 2018 08:23:12 *****
Zephyr Shell, Zephyr version: 1.11.0-rc3
Type 'help' for a list of available commands
shell> [dev/eth_mcux] [INF] eth_mcux_phy_event: Enabled 100M full-duplex mode.
[echo-client] [INF] init_app: Run echo client
[echo-client] [ERR] connect_tcp: Cannot connect TCP (-60)
[echo-client] [ERR] start_tcp: Cannot init IPv6 TCP client (-60)
[echo-client] [ERR] connect_tcp: Cannot connect TCP (-60)
[echo-client] [ERR] start_tcp: Cannot init IPv4 TCP client (-60)
[echo-client] [ERR] send_tcp_data: Cannot send IPv6 data to peer (-57)
[echo-client] [ERR] send_tcp_data: Cannot send IPv4 data to peer (-57)
[echo-client] [INF] main: Stopping...

I am not able to find the communication between client & server.

**Comment by rveerama1** [comment]
samples/net/sockets/echo is binding to only IPv4 address. Running IPv6 client against it doesn't work. So closing issue.
