### ISSUE TITLE
twister: test_config.yaml is loaded by default 

### ISSUE THREAD

**Issue by PerMac** [zephyrproject-rtos/zephyr#65682]
Twister allows for using yaml files where certain configurations can be stored and used during the call, e.g. testing scope, default platforms etc. Should this file https://github.com/zephyrproject-rtos/zephyr/blob/main/tests/test_config.yaml be loaded and used by default, even when no CLI options are used https://github.com/zephyrproject-rtos/zephyr/blob/main/scripts/pylib/twister/twisterlib/environment.py#L315? Is this a feature or a bug? If feature, what value it brings getting it loaded silently? 
I am playing with this file within the contexed of on-target testing for tier 1 platforms. The idea was, that this file can be used to synchronize testing scope and configs between vendors. If this file has to be loaded by default then I can create a new one, which will serve for tier 1 testing purpose. I modified locally "default_platforms" section in this file and added there some candidates for tier 1. The idea was that a tester can call twister pointing to that file and adding "--vendor" filter and will end up with tier 1 platforms of the given vendor. However, I was surprised to see that the behavior of twister changed even when I didn't want to use the file. The default platforms were overwritten with the ones from the file regardless of pointing twister to it in CLI. IMO this can be rather problematic. 

Zephyr version: since 14d88f8425cb35be52c81d8b928f123b4e89984d
other details shouldn't matter since it is pure software question

**Comment by nashif** [comment]
This is not a bug, the file is supposed to be loaded by default.
