### ISSUE TITLE
twister: Always change skip to error on integration platforms - re-consider.

### ISSUE THREAD

**Issue by gbarkadiusz** [zephyrproject-rtos/zephyr#65743]
**Describe the bug**
Despite not using the parameter `-G` or `--integration` a few tests or samples are executed, although they aren't included in the test plan. Those executed samples or tests have changed status from `skipped` to `error`.

This issue is regarding these changes https://github.com/zephyrproject-rtos/zephyr/commit/42aa8fd72c716aa1042e946afa03d94294994f07

![image](https://github.com/zephyrproject-rtos/zephyr/assets/122030181/f8011e81-bca2-4a80-827f-f82dc8031ffb)

The test's status will be switched to error if only `integration_platforms` is set in `testcase.yaml`. It doesn't matter if integration is set in options or not.

**To Reproduce**
Prepare `test_config.yaml` file
```
levels:
  - name: semaphore
    adds:
      - kernel.semaphore.*
```
Use the above `test_config.yaml` file while creating the test plan. `twister -E testplan --test-config <path_to>/test_config.yaml --level semaphore  -p frdm_k64f`
In generated `./twister-out/testplan.json` file we can find tests and even samples with `error` state and `Not part of requested test plan but is one of the integration platforms` as a reason. It means that those tests were changed from `skipped` to `error` although there weren't integration parameters in the twister command.

**Expected behavior**
Function `def change_skip_to_error_if_integration(options, instance)` should verify whether integration was used. 

**Impact**
Defining the scope of the test via `--test-config` parameter doesn't work properly.

**Logs and console output**
Fragment of generated test plan according to `kernel.semaphore.*` template.
```
...
           {
            "name":"samples/sensor/accel_polling/sample.sensor.accel_polling",
            "arch":"arm",
            "platform":"frdm_k64f",
            "path":"samples/sensor/accel_polling",
            "run_id":"04fc24cb29a5de2dfb54e0fab67323b3",
            "runnable":true,
            "retries":0,
            "status":"error",
            "reason":"Not part of requested test plan but is one of the integration platforms",
            "log":"",
            "execution_time":"0.00",
            "testcases":[
                {
                    "identifier":"sample.sensor.accel_polling",
                    "execution_time":"0.00",
                    "status":"error",
                    "reason":"Not part of requested test plan but is one of the integration platforms"
                }
            ]
        },
...
```

**Environment:**
 - OS: Linux
 - Toolchain Zephyr SDK 0.16.3

**Comment by PerMac** [comment]
Changing skips to error on integration_platforms regardless of using -G or not is the intended default behavior. The linked commit explains the change. However, skips due to configurations not being part of a test plan should remains skips, linked PR is fixing the issue.
