### ISSUE TITLE
MQTT publish fails with sys_rand32_get() for message ID on nRF9160

### ISSUE THREAD

**Issue by OmarM17** [zephyrproject-rtos/zephyr#65777]
**Describe the bug**
 I'm working on an application that runs on nRF9160 using Zephyr V3.4.0/V3.5.0. This application uses NB-IoT connection and has a stable connection to an MQTT broker. I want to publish data to a topic periodically using a timer every 2 seconds, but I am facing a problem with the publish function. 
 I get an error when I use sys_rand32_get() for message ID and It works only once when I use a static number, but then it fails to publish again. 
I have followed the Zephyr RTOS publisher sample (https://github.com/zephyrproject-rtos/zephyr/tree/main/samples/net/mqtt_publisher) :
```
 static int publish(struct mqtt_client *client, enum mqtt_qos qos), and I am using the same publish function as in the sample.
 {
 	struct mqtt_publish_param param;

	param.message.topic.qos = qos;
	param.message.topic.topic.utf8 = (uint8_t *)get_mqtt_topic();
	param.message.topic.topic.size =
			strlen(param.message.topic.topic.utf8);
	param.message.payload.data = get_mqtt_payload(qos);
	param.message.payload.len =
			strlen(param.message.payload.data);
	param.message_id = sys_rand32_get();
	param.dup_flag = 0U;
	param.retain_flag = 0U;

	return mqtt_publish(client, &param);
 }

```

However, when I use a static number instead (e.g. param.message_id = 7;) the publish succeeds but only for the first time ! 

**To Reproduce**
- board : nRF9160
- i'm using this [sample ](https://github.com/NordicDeveloperAcademy/cell-fund/blob/master/v2.4.0/lesson4/cellfund_less4_exer1_solution/src/main.c) for modem configuration and LTE-M connection.
- build and flash using west

**Expected behavior**
I expected to publish data to a topic periodically using a timer every 2 seconds without any error.

**Impact**
This issue is a showstopper for me as I need to publish data reliably and frequently.

**Logs and console output**
The board rebooted without any error logs

**Environment (please complete the following information):**
 - OS: Windows 10
 - Toolchain: nRF SDK toolchain V2.4.0/V2.5.0
 - Version: tested both in  zephyr V3.4.0/V3.5.0

**Additional context**
I have enabled these two config parameters:

```
CONFIG_ENTROPY_GENERATOR=y
CONFIG_TEST_RANDOM_GENERATOR=y
```

**Comment by kartben** [comment]
Please provide more details regarding the error you get, ex. logs, error code, ...
