### ISSUE TITLE
Potential bugs in zephyr\dts\bindings\dma\raspberrypi,pico-dma.yaml, irq0-channels definition

### ISSUE THREAD

**Issue by renestraub** [zephyrproject-rtos/zephyr#65778]
**Describe the bug**
1. irq0_channel array misses entry 6. Is this by intent or a bug. If it's intentionally, a comment would be helpful
2. Description in .yaml is wrong, refers to Pi Pico GPIO instead of DMA.
3. There are only 12 DMA channels on RP2040. Why is the array listing channels 12..30? This is unnecessary, and also slows down interrupt handlind due to the inefficient lookup in zephyr\drivers\dma\dma_rpi_pico.c, dma_rpi_pico_channel_irq()

**To Reproduce**
Check zephyr\dts\bindings\dma\raspberrypi,pico-dma.yaml

**Expected behavior**
1. irq behavior of DMA channel 6 is clarified.
2. Description is correct (DMA not GPIO)
3. Only available channels are defined in irq0-channels[] array

**Impact**
- channel 6 might not run at expected IRQ 0.
- handling of channels using IRQ1 is unnecessarily slowed down.

**Environment**
 - Rasperry Pi Pico Port
 - Commit * 1a0b1124c6 - (2 weeks ago) MAINTAINERS: charger: Adds entry for "Chargers" - Ricardo Rivera-Matos (HEAD -> main, origin/main, origin/HEAD)

**Comment by kartben** [comment]
Maybe @soburi can help here
