### ISSUE TITLE
Add GPIO as the link layer for the 1-Wire bus

### ISSUE THREAD

**Issue by hcd-bdltd** [zephyrproject-rtos/zephyr#65787]
**Is your feature request related to a problem? Please describe.**
At the moment, the implementation of the 1-Wire bus requires using the UART as the link layer.

**Describe the solution you'd like**
The possibility to choose to a different link layer, i.e. GPIO.

**Describe alternatives you've considered**
I've considered using a I2C multiplexer to connect the UART to all my sensors, but that requires additional cost and changes in the hardware. I've also considered implementing the 1-Wire through GPIO without integrating into Zephyr, but then I would not be able to use the existing DS18B20 library.

**Additional context**
I am developing a solution using nRF5340 and DS18B20 sensors, where I need to know the physical location of each sensor. To achieve this, I have connected each sensor to a different GPIO to map the location to the pin. But that means I can not use the provided DS18B20 library because the underlying link layer requires using the UART peripheral.

I am willing to develop the GPIO link layer and create a PR to merge with Zephyr. But since it is my first contribution to the project, I will definitely need guidance for this.

My initial thought was to implement the following functions found at `zephyr/include/zephyr/drivers/w1.h`

``` c
typedef int (*w1_reset_bus_t)(const struct device *dev);
typedef int (*w1_read_bit_t)(const struct device *dev);
typedef int (*w1_write_bit_t)(const struct device *dev, bool bit);
typedef int (*w1_read_byte_t)(const struct device *dev);
typedef int (*w1_write_byte_t)(const struct device *dev, const uint8_t byte);
typedef int (*w1_read_block_t)(const struct device *dev, uint8_t *buffer,
			       size_t len);
typedef int (*w1_write_block_t)(const struct device *dev, const uint8_t *buffer,
				size_t len);
typedef size_t (*w1_get_slave_count_t)(const struct device *dev);
typedef int (*w1_configure_t)(const struct device *dev,
			      enum w1_settings_type type, uint32_t value);
typedef int (*w1_change_bus_lock_t)(const struct device *dev, bool lock);
```

Something similar to what have been done at `drivers/w1/w1_zephyr_serial.c`, but maybe create a new file `drivers/w1/w1_zephyr_gpio.c` ?

**Comment by nordicjm** [comment]
> Something similar to what have been done at drivers/w1/w1_zephyr_serial.c, but maybe create a new file drivers/w1/w1_zephyr_gpio.c ?

yes

**Comment by nixward** [comment]
I second that @hcd-bdltd, sounds good 👍

**Comment by str4t0m** [comment]
> At the moment, the implementation of the 1-Wire bus requires using the UART as the link layer.

Depending on your exact project requirements using a I2C 1-Wire master might also be an option, as there exists one that has 8 1-Wire lines  (DS2482-800).

>  The possibility to choose to a different link layer, i.e. GPIO.

> I am willing to develop the GPIO link layer and create a PR to merge with Zephyr.

Yes, I to my knowledge there are no ongoing efforts to implement it, but contributions would be very welcome.

> Something similar to what have been done at drivers/w1/w1_zephyr_serial.c, but maybe create a new file drivers/w1/w1_zephyr_gpio.c ?

As @nordicjm has already confirmed, that is the way to go. As a reference, the w1-zephar-serial driver was introduced in commit https://github.com/zephyrproject-rtos/zephyr/pull/37663/commits/7066f5494db65b36f9a8303af875c2169567f165

**Comment by hcd-bdltd** [comment]
Thanks very much @str4t0m. I will have a look and try to implement the GPIO link layer based on it. Any further questions, I will let you all know.
