### ISSUE TITLE
adp_xc7k_ae350 build fails with CONFIG_CACHE_MANAGEMENT

### ISSUE THREAD

**Issue by tbursztyka** [zephyrproject-rtos/zephyr#65870]
**Describe the bug**
The title says it all.
Building with CONFIG_CACHE_MANAGEMENT ends up with such errors for adp_xc7k_ae350:
```
/__w/zephyr/zephyr/include/zephyr/cache.h:94: undefined reference to `arch_icache_disable'
```

To "fix" it, it only requires to de-select CPU_HAS_DCACHE and CPU_HAS_ICACHE which happen to be selected in soc/riscv/riscv-privileged/andes_v5/Kconfig.soc for the config option SOC_RISCV_ANDES_AE350

I could not find any cache implementation in arch/riscv nor soc/riscv, should CPU_HAS_DCACHE and CPU_HAS_ICACHE be de-selected then? Or someone to implement the relevant API for this soc.

**To Reproduce**
(make sure CONFIG_CACHE_MANAGEMENT is set in test's prj.conf)
1. scripts/twister -p adp_xc7k_ae350 -T tests/kernel/cache

**Expected behavior**
should be probably skipped by twister until the cache api is implemented 

**Impact**
CI failure

**Comment by henrikbrixandersen** [comment]
Tagging as medium since this is blocking other PRs.
