### ISSUE TITLE
Getting I2C error even when read and write is happening correctly

### ISSUE THREAD

**Issue by abhijitgundawar-eaton** [zephyrproject-rtos/zephyr#65952]
Zephr Version : 2.7.99

Nordic SDK Version: 1.9.1

Description of bug::

I2C is configured to read/write RTC time from external RTC (Real time clock)

When I tried to **write** the time (7 bytes), I can write it but gets the error (Response = -134)
When I tried to read the time, I can read it without error (Response = 0)

I want to know why this error is occuring even when I am able to read the time successfully. 

Also when When I tried to **write** the configuration byte (1 byte), I can write it but gets the error (Response = -5) ( (#define EIO 5   /* I/O error */)

Above behaviour is repetative

API used:

_int uC_I2C::Write( uint16_t chip_address, uint16_t length, uint8_t* datasource )
{
	struct i2c_msg msg;
	int transfer_status;

	msg.buf = datasource;
	msg.len = length;
	msg.flags = I2C_MSG_WRITE | I2C_MSG_STOP;

	transfer_status = i2c_transfer( m_i2c_dev, &msg, length, chip_address );

	if ( transfer_status != 0 )
	{
		LOG_ERR( "Failed to Write\n" );
	}
	return ( transfer_status );
}_

**To Reproduce**
1. Configure the I2C by using "i2c_configure( m_i2c_dev, dev_config );"
2. Write the RTC time using "int uC_I2C::Write( uint16_t chip_address, uint16_t length, uint8_t* datasource )"

Every time i get error response as -134 (#define ENOTSUP 134   /* Not supported */) 
3. Read the I2C time (No error)

**Expected behavior**
If  i am able to write the time correctly then the response code must be 0 

**Impact**
Though functionally we are good, but we could not detect actual error situation and unable to implement diagnostics.

**Comment by henrikbrixandersen** [comment]
> Zephr Version : 2.7.99
> 
> Nordic SDK Version: 1.9.1

Please report bugs against NCS to the NordicSemi DevZone instead.
