### ISSUE TITLE
Unable to flash EFR32 BRD4187C

### ISSUE THREAD

**Issue by n-lawson** [zephyrproject-rtos/zephyr#65989]
**Description**
Unable to flash EFR32 BRD4187C board ('efr32_radio_brd4187c') after building demos (hello_world and/or blinky). I am able to build and flash demos for 'stm32f3_disco@E' and 'nrf52840dk_nrf52840' using the given process.

**To Reproduce**
* west build -p always -b efr32_radio_brd4187c samples/hello_world
* west flash

Error: Target is not Cortex-Mx Device

**Logs and console output**

West Flash output:
![image](https://github.com/zephyrproject-rtos/zephyr/assets/152517987/8e75170b-a1ea-4eed-b374-edffb540411f)

West Debug output:
<img width="493" alt="image" src="https://github.com/zephyrproject-rtos/zephyr/assets/152517987/935f4a52-8634-4580-8644-95c8ec8dd83d">

There also appears to be an issue with recognizing multiple devices when I'm flashing EFR32 BRD4187C:
![image](https://github.com/zephyrproject-rtos/zephyr/assets/152517987/73bfdb16-a9e4-4c6e-94f7-f9d48c69cd85)

When I have multiple devices connected and I try to flash nRF52840 DK, I'm able to properly select the SN to flash:
![image](https://github.com/zephyrproject-rtos/zephyr/assets/152517987/5829fec3-ef96-4bf5-8ff3-788d1623fca8)

**Expected Behavior**
I expected to be able to flash the demos (hello_world and blinky) on my EFR32 BRD4187C board, just as I was able to flash demos on my other boards. 

**Impact**
I am helping to scope out the use of Zephyr in a future project that would be based on the EFR32 BRD4187C board, but I am currently unable to build the demos.

**Environment**
* Page: `boards/arm/efr32_radio/doc/brd4187c`
* OS: MacOS
* Toolchain: Zephyr SDK
* Version: main
* SHA-1: 9f4bbf9c6a47b391611da3e750d9eab34c1cbb7d

**Comment by henrikbrixandersen** [comment]
Please use our bug template when reporting bugs. You need to edit this issue to include the information requested in https://github.com/zephyrproject-rtos/zephyr/blob/main/.github/ISSUE_TEMPLATE/001_bug_report.md
