### ISSUE TITLE
[MIMXRT1040-EVK] Blinky example does not blink

### ISSUE THREAD

**Issue by butok** [zephyrproject-rtos/zephyr#65983]
**Describe the bug**
The samples\basic\blinky example for MIMXRT1040-EVK does not blink any LED.

**To Reproduce**
1. `west build -p always -b mimxrt1040_evk samples\basic\blinky`
2. `west flash`
3. In a terminal window:
`*** Booting Zephyr OS build zephyr-v3.5.0-2160-g5bfed9ef6b27 ***`

**Expected behavior**
Blinking LED.

**Impact**
Basic MIMXRT1040-EVK support is not complete.

**Logs and console output**
`*** Booting Zephyr OS build zephyr-v3.5.0-2160-g5bfed9ef6b27 ***`
But there is no LED blinking.

**Environment (please complete the following information):**
 - OS: Windows
 - Toolchain zephyr-sdk-0.16.3
 - Commit SHA 5bfed9ef6b27b225ace044807fbad3a5d68b598c

**Comment by DerekSnell** [comment]
Hi @butok ,

Did you already remove jumper J80 on the MIMXRT1040-EVK board?  The signal driving the LED on that board is shared, and this jumper is frequently the reason the LED does not blink.  See this [Readme](https://github.com/nxp-mcuxpresso/mcux-sdk-examples/blob/5b31db02655917d53600978fe7f0cc314e5def21/evkmimxrt1040/demo_apps/led_blinky/readme.txt#L21) from the MCUXpresso SDK.

**Comment by DerekSnell** [comment]
Hi @butok ,

I updated the MIMXRT1040-EVK doc page in https://github.com/zephyrproject-rtos/zephyr/pull/66037 to help make others aware of this jumper.  Please let us know if that jumper resolves the issue, and please add your feedback to the PR.

Thanks for raising this.

**Comment by DerekSnell** [comment]
Hi @butok ,
> Can we use a different LED for the LED example, and avoid jumper changes?

Can you find another LED on that board to use?  I believe it is the only LED connected to GPIO pins.  Thanks

**Comment by butok** [comment]
> Hi @butok ,
> 
> > Can we use a different LED for the LED example, and avoid jumper changes?
> 
> Can you find another LED on that board to use? I believe it is the only LED connected to GPIO pins. Thanks

Right. Unfortunatly, the board has only one User Led, which is disabled by default.
