### ISSUE TITLE
RFC: API Change: Bluetooth: Mesh: Remove the CONFIG_BT_MESH_V1d1 and the legacy transport Kconfig options

### ISSUE THREAD

**Issue by PavelVPV** [zephyrproject-rtos/zephyr#65985]
## Introduction

Remove the [CONFIG_BT_MESH_V1d1](https://github.com/zephyrproject-rtos/zephyr/blob/c94cd30cecbf8247e1f1c776d065a07b59b0fc25/subsys/bluetooth/mesh/Kconfig#L1051-L1055) Kconfig option and the legacy transport [Kconfig options](https://github.com/zephyrproject-rtos/zephyr/blob/c94cd30cecbf8247e1f1c776d065a07b59b0fc25/subsys/bluetooth/mesh/Kconfig#L508-L552) and make Zephyr Bluetooth Mesh stack 1.1 compatible.

### Problem description

Currently, the Bluetooth Mesh Profile 1.0.1 is supported by the Zephyr Bluetooth Mesh implementation by default and the Bluetooth Mesh Protocol 1.1 and the corresponding features are enabled through `CONFIG_BT_MESH_V1d1` Kconfig option. However, we want to drop the support of Bluetooth Mesh Profile 1.0.1 and replace it with the Bluetooth Mesh Protocol 1.1. The explicit support of both versions requires additional maintenance efforts and doubles the CI time (if tests are not parallelized). The 1.1 version is backward compatible with the 1.0.1, if one needs, they can still qualify the stack for 1.0.1. But in this case they need to remove private beacon reception. This also means that we need to drop support for the legacy transport Kconfig options. Following the [regular deprecation procedure](https://docs.zephyrproject.org/latest/develop/api/api_lifecycle.html#deprecated) will make us spend effort on maintaining these Kconfigs and the legacy transport layer for 2 more releases.

### Proposed change

- Remove the `CONFIG_BT_MESH_V1d1` Kconfig option.
- Remove the legacy transport [Kconfig options](https://github.com/zephyrproject-rtos/zephyr/blob/c94cd30cecbf8247e1f1c776d065a07b59b0fc25/subsys/bluetooth/mesh/Kconfig#L508-L552).
    - They are superseded by the [new Kconfig options](https://github.com/zephyrproject-rtos/zephyr/blob/c94cd30cecbf8247e1f1c776d065a07b59b0fc25/subsys/bluetooth/mesh/Kconfig#L1513-L1631).

PR #65984 implements the proposed changes.

## Detailed RFC

In addition to Kconfigs, this change will affect:
- BabbleSim tests for 1.0.1 will be removed.
- Tester app will use 1.1 features by default. AutoPTS will still run 1.0.1 qualification tests until it is requested to run 1.1 qualification tests.
- Samples will run with mesh 1.1.

### Dependencies

The users of the stack will have to replace the legacy transport Kconfig options with the new options.

### Concerns and Unresolved Questions

Those who want to use 1.0.1 and keep their qualification, should remove the private beacons reception and disable SHA256 algorithm in the provisioning (`CONFIG_BT_MESH_ECDH_P256_HMAC_SHA256_AES_CCM`).

## Alternatives

- Keep Kconfigs as is (1.1 support and the legacy transport with its Kconfig options) forever and spend efforts on maintaining them.
- Drop the legacy transport, but keep 1.1 support toggleable.
- Mark `CONFIG_BT_MESH_V1d1` and the legacy transport Kconfig options as `DEPRECATED` and follow the [regular deprecation procedure](https://docs.zephyrproject.org/latest/develop/api/api_lifecycle.html#deprecated) for 2 more releases.

**Comment by henrikbrixandersen** [comment]
I've added this on today's Arch WG meeting as per our guidelines. If someone wishes to present the issue there, that'll be great. If not, I'll just mention it for added visibility.

**Comment by PavelVPV** [comment]
I'll present the issue.

**Comment by PavelVPV** [comment]
Closing as fixed
