### ISSUE TITLE
doc: Documentation issue in 'kernel/services/data_passing/mailboxes'

### ISSUE THREAD

**Issue by adamtheone** [zephyrproject-rtos/zephyr#66016]
**Describe the bug**

In the '[Retrieving Data Later Using a Message Buffer](https://docs.zephyrproject.org/latest/kernel/services/data_passing/mailboxes.html#retrieving-data-later-using-a-message-buffer)' section, in the 3rd bullet point, there's an extra '.' after k_mbox_data_get() which should not be there, as that's not the end of the sentence. 

**Environment**

* Page: `kernel/services/data_passing/mailboxes`
* Version: main
* SHA-1: e9987aabbcd46dc583624f10004ddd2b32bbeb3d

**Comment by MaureenHelm** [comment]
Would you mind sending a pull request?
