### ISSUE TITLE
LPSPI does not work on MKE512XXX16 processor family

### ISSUE THREAD

**Issue by danielskatt** [zephyrproject-rtos/zephyr#66036]
**Describe the bug**

LPSPI does not work on processor MKE512XXX16 which is on development board TWR-KE18F. When running any code with SPI the code crashes when setting the Module Enable (MEN) bit in the Control Register (LPSPIx_CR) on adress 0x4002_C010 for LPSPI0 to disable the module before setting the baud rate and run LPSPI_MasterInit() function. This is due to the clock not being enabled before setting the MEN register bit in CR according to data-sheet of the processor . This is the same for all LPSPI available on this processor.

 - Target platform 

Processor MKE512VLL16 which is on TWR-KE18F
 - Workaround for this issue
   
If setting LPSPI_MasterInit() before LPSPI_Enable() in spi_mcux_lpspi.c LPSPI works, for example

LPSPI_MasterInit(base, &master_config, clock_freq);

/* Setting the baud rate in LPSPI_MasterInit requires module to be disabled */

LPSPI_Enable(base, false);

while ((base->CR & LPSPI_CR_MEN_MASK) != 0U) {
/* Wait until LPSPI is disabled. */
	
}

/* Enable LPSPI module */
LPSPI_Enable(base, true);

**To Reproduce**

1. Build a SPI sample or communicate with a sensor/display via SPI for development board TWR-KE18F as master
2. Flash to board with processor MKE512XXX16, example TWR-KE18F
3. See if code crashes during boot

**Expected behavior**

SPI should be able to run on this processor family to communicate with sensors, other processors and similar

**Impact**

Everyone who is using SPI on this processor needs to do minor changes in Zephyr code

**Logs and console output**

*** Booting Zephyr OS build zephyr-v3.4.0 ***
[00:00:00.007,000] <err> os: ***** BUS FAULT *****
[00:00:00.007,000] <err> os:   Precise data bus error
[00:00:00.007,000] <err> os:   BFAR Address: 0x4002d010
[00:00:00.007,000] <err> os: r0/a1:  0x00000000  r1/a2:  0x00000001  r2/a3:  0x02dc6c00
[00:00:00.007,000] <err> os: r3/a4:  0x00000002 r12/ip:  0x00f2440b r14/lr:  0x000044fd
[00:00:00.007,000] <err> os:  xpsr:  0x61000000
[00:00:00.007,000] <err> os: Faulting instruction address (r15/pc): 0x00003ea0
[00:00:00.007,000] <err> os: >>> ZEPHYR FATAL ERROR 25: Unknown error on CPU 0
[00:00:00.007,000] <err> os: Current thread: 0x20000738 (unknown)
[00:00:00.073,000] <err> os: Halting system

**Environment:**

 - OS: MacOS
 - Toolchain: Zephyr SDK 0.16.1
 - Zephyr 3.4.0

**Additional context**

Has also tested the code when re-order LPSPI_MasterInit on processor MIMXRT1024 (which works without this fix) and worked without problems.

**Comment by henrikbrixandersen** [comment]
Git bisect points to commit d3415e2ce117ea6e439c9e14c797bd239ef202a1, which is present in v3.3.0, v3.4.0, and v3.5.0.
