### ISSUE TITLE
tests/net/lib/dns_sd  doesn't pass :issue

### ISSUE THREAD

**Issue by Desvauxm-st** [zephyrproject-rtos/zephyr#66033]
Describe the bug:
if you run tests/net/lib/dns_sd it doesn't pass
on the pass (in beginning of october) this test passed well

information which could help others to understand the problem you're facing:
platform: frdm_k64f

for exemple if you try that :
 west build -p always -b  frdm_k64f  tests/net/lib/dns_sd/

it is the same thing with nucleo_f746zg,nucleo_f429zi ... 
the result is like that : 
**Assertion failed at WEST_TOPDIR/zephyr/tests/net/lib/dns_sd/src/main.c:715: dns_sd_test_setup_dst_addr: (ret not equal to 0)
Create IPV4 udp context failed
 FAIL - test_setup_dst_addr in 0.015 seconds**

![image](https://github.com/zephyrproject-rtos/zephyr/assets/119042859/ebc8b9a4-31e3-4cd5-9eea-0810ac0872f0)

and 
![image](https://github.com/zephyrproject-rtos/zephyr/assets/119042859/b03d05d2-4e69-4a90-95e5-760ed62941bd)

it is a regression because in beginning of october it  was ok

**Comment by jukkar** [comment]
I just tried this with latest upstream HEAD
with this command
`west build -p always -b frdm_k64f tests/net/lib/dns_sd/ -d ../build/test`
and see no issues.
