### ISSUE TITLE
rzt2m_starterkit: Doc tags are wrong

### ISSUE THREAD

**Issue by nordicjm** [zephyrproject-rtos/zephyr#66094]
**Describe the bug**
The doc for `rzt2m_starterkit` on the ARM boards page does not list this board, instead it lists `Supported Features`, `Connections and IOs` and `Debugging`. This should be fixed. https://docs.zephyrproject.org/latest/boards/arm/index.html

**Expected behavior**
Board to be listed properly

**Impact**
Annoyance

**Comment by andrzej-kaczmarek** [comment]
@nordicjm I'm not the proper assignee for this issue, it's not a SmartBond platform and I don't know anything about it.

**Comment by nordicjm** [comment]
> @nordicjm I'm not the proper assignee for this issue, it's not a SmartBond platform and I don't know anything about it.

Will search git history and reassign
