### ISSUE TITLE
doc: Documentation issue in 'samples/sensor/lps22hb/README'

### ISSUE THREAD

**Issue by icatorze** [zephyrproject-rtos/zephyr#66117]
**Describe the bug**

The title of LPS22HB sample page, show it as a temperature and humidity sensor, but it is a **pressure sensor.**

**Environment**

* Page: `samples/sensor/lps22hb/README`
* Version: main
* SHA-1: 14c92da96d5613b48610fa9bfe284528a814a4e6

**Comment by kartben** [comment]
Thanks for reporting this, @icatorze -- please feel free to submit a PR unless someone else beats you to it :)
