### ISSUE TITLE
readelf not found in llvm only dev environment

### ISSUE THREAD

**Issue by yperess** [zephyrproject-rtos/zephyr#66122]
When using llvm as the toolchain, we end up including `cmake/bintools/llvm/target.cmake` which in turn looks for `readelf`. But in dev machines with only llvm tools, `readelf` is actually called `llvm-readelf`. This is a common pattern already accounted for with `objcopy` and others. The search for `readelf` should allow for the alternate names when llvm is selected.

**Comment by marc-hb** [comment]
> But in dev machines with only llvm tools, readelf is actually called llvm-readelf.

I don't think it's that simple. This is one LLVM-based toolchain I have now:

```
ls -l $(find tools/RI-2022.10-linux/ -name *readelf)

-rwxr-xr-x  765736 Dec  1  2022 tools/RI-2022.10-linux/XtensaTools/bin/xtensa-elf-readelf
-rwxr-xr-x   39320 Dec  1  2022 tools/RI-2022.10-linux/XtensaTools/bin/xt-readelf
lrwxrwxrwx      12 Dec  1  2022 tools/RI-2022.10-linux/XtensaTools/llvm/bin/llvm-readelf -> llvm-readobj
-rwxr-xr-x  660787 Aug  7  2022 tools/RI-2022.10-linux/XtensaTools/Tools/bin/readelf
lrwxrwxrwx      17 Dec  1  2022 tools/RI-2022.10-linux/XtensaTools/Tools/x86_64-pc-linux-gnu/bin/readelf -> ../../bin/readelf

```
The last two are just `readelf` without prefix.

Maybe there's a reason why some binaries are prefixed with `llvm-`; maybe they don't want to be found?
