### ISSUE TITLE
drivers: sensor: MCP9600: Wrong register addresses

### ISSUE THREAD

**Issue by naNEQ** [zephyrproject-rtos/zephyr#66150]
Most of the internal registers of the MCP9600 in the code have wrong addresses.

Starting [from ](https://github.com/zephyrproject-rtos/zephyr/blob/3d3b287b7908625dc8356ac3532d9b6943edbb50/drivers/sensor/mcp9600/mcp9600.c#L28) the `MCP9600_REG_A1_CONFIG`, all registers with higher addresses have wrong address.

From TABLE 5-1 in the [datasheet ](https://ww1.microchip.com/downloads/en/DeviceDoc/MCP960X-Data-Sheet-20005426.pdf) we can see the list of registers: 

![image](https://github.com/zephyrproject-rtos/zephyr/assets/135322804/bb4af34e-f156-4ef0-bec3-ce106017a3a7)

**Comment by naNEQ** [comment]
I offer to open a PR with proposed changes, if that is OK.

**Comment by kartben** [comment]
marking as low priority as, thankfully, and unless I'm mistaken, none of these "bad" register are actually used by the driver.

**Comment by naNEQ** [comment]
Off to it!

Well, one of them is actually used and that's how I found this out: the `MCP9600_REG_ID_REVISION` at the `mcp9600_init()`, but the values read (which are wrong, obviously), are not used to anything.
