### ISSUE TITLE
Request to support Application's Kconfig tree 

### ISSUE THREAD

**Issue by jli157** [zephyrproject-rtos/zephyr#6623]
Some applications could need sophisticated configuration requirements, thus need to define Kconfig tree on its own to support that. 

Before cmake based building system was implemented, an application can define its Kconfig tree by the following way in the Makefile:
```
KBUILD_KCONFIG = $(PWD)/Kconfig
export KBUILD_KCONFIG
```
and in its Kconfig:
```
config PROJECT_BASE
    string
    option env="PROJECT_BASE"

source "Kconfig.zephyr"
source "$PROJECT_BASE/src/Kconfig"
```

However, this way is not well supported in the current cmake based building system. The existing example which is using the most similar way to define its Kconfig is `tests/drivers/spi/spi_loopback`. The project redefined the KCONFIG_ROOT by the command
```
set(KCONFIG_ROOT ${CMAKE_CURRENT_SOURCE_DIR}/Kconfig)
```
in its CMakeLists.txt. Thus, an application level Kconfig can be defined. However, the application can't implement hierarchy Kconfig tree like before. This is why that example defines all of its new macros in just one Kconfig file, which is cumbersome. 

So, a hierarchy Kconfig tree at the application level should also be supported.

**Comment by jli157** [comment]
The PR #7293 has resolved the issue thus it can be closed.

**Comment by SebastianBoe** [comment]
Thank you for reporting :)
