### ISSUE TITLE
tests: crypto: rand32 test issue regression

### ISSUE THREAD

**Issue by Desvauxm-st** [zephyrproject-rtos/zephyr#66312]
Describe the bug:

in our bench tester many board test fail now  with:

tests/crypto/rand32
for example:

west build -p always -b   nucleo_f746zg  tests/crypto/rand32
![image](https://github.com/zephyrproject-rtos/zephyr/assets/119042859/c194e64e-3420-4899-a6a8-40ab259fd290)

test is blocked

it is due to this commit:
https://github.com/zephyrproject-rtos/zephyr/commit/78af1c1e3878c410067bd49846771300fa86b840

entropy: stm32: suspend when pool is full
78af1c1e3878c410067bd49846771300fa86b840
author: Dawid Niedzwiecki <dawidn@google.com>  2023-12-01 11:27:37
Committer: Maureen Helm <maureen.helm@analog.com>  2023-12-05 23:27:53

thanks  to have a look

**Comment by niedzwiecki-dawid** [comment]
I've sent a fix to review. Would you be able to confirm it works? 

Sorry for the bug.

**Comment by niedzwiecki-dawid** [comment]
@Desvauxm-st sorry for a late question. Are the results of your test runs available somewhere or it is an internal thing?

**Comment by erwango** [comment]
@niedzwiecki-dawid Tests results might be available here: https://github.com/zephyrproject-rtos/test_results/
Updated once/week. 
Regarding internal archives, they are not deep enough to be able to retrieve the info that late. Would be easier to re-run test

**Comment by niedzwiecki-dawid** [comment]
Thanks for the info. I don't need archive of this test, just asking about access to test results :).

**Comment by niedzwiecki-dawid** [comment]
One more question, is there any easy way to read the result? E.g. If I would like to get 5 last results of a specific test for a specific board. Or I just need to grep commits.

**Comment by erwango** [comment]
TBH, I don't know. @hakehuang might be able to answer as Testing group chairman
