### ISSUE TITLE
[CI] Some ST boards are failing the `tests/benchmarks/footprints/benchmark.kernel.footprints.pm` test

### ISSUE THREAD

**Issue by ycsin** [zephyrproject-rtos/zephyr#66360]
**Describe the bug**
At least the `mikroe_mini_m4_for_stm32` & `96b_aerocore2` boards are failing the `zephyr/tests/benchmarks/footprints/benchmark.kernel.footprints.pm` test.

Please also mention any information which could help others to understand
the problem you're facing:
 - What target platform are you using
   - `mikroe_mini_m4_for_stm32`
 - What have you tried to diagnose or workaround this issue?
   - `COUNTER_RTC_STM32_SUBSECONDS` is getting y-selected by `PM`, despite `mikroe_mini_m4_for_stm32` not having its RTC enabled.

**To Reproduce**
1. Checkout latest main
2. `west build -b mikroe_mini_m4_for_stm32 -p auto -T zephyr/tests/benchmarks/footprints/benchmark.kernel.footprints.pm`
3. See error

**Expected behavior**
Test should pass

**Impact**
Blocking #63973

**Logs and console output**
```
warning: COUNTER_RTC_STM32_SUBSECONDS (defined at drivers/counter/Kconfig.stm32_rtc:47) has direct dependencies !SOC_SERIES_STM32F1X && COUNTER_RTC_STM32 && COUNTER with value n, but is currently being y-selected by the following symbols:
 - PM (defined at soc/arm/silabs_exx32/efr32bg22/Kconfig.defconfig.series:18, soc/arm/silabs_exx32/efr32bg27/Kconfig.defconfig.series:18, soc/arm/silabs_exx32/efr32mg24/Kconfig.defconfig.series:19, soc/arm/st_stm32/stm32f4/Kconfig.defconfig.series:20, subsys/pm/Kconfig:13), with value y, direct dependencies (SOC_SERIES_EFR32BG22 && SOC_FAMILY_EXX32) || (SOC_SERIES_EFR32BG27 && SOC_FAMILY_EXX32) || (SOC_SERIES_EFR32MG24 && SOC_FAMILY_EXX32) || SOC_SERIES_STM32F4X || (SYS_CLOCK_EXISTS && HAS_PM) (value: y), and select condition SOC_SERIES_STM32F4X (value: y)
```

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: Zephyr SDK
 - Commit SHA or Version used: 0bf4efc78080ceefaad7becf0d01c8d7fb2a8119

**Comment by ycsin** [comment]
Reopened the issue as `96b_aerocore2` also fails the test, currently running the `tests/benchmarks/footprints/benchmark.kernel.footprints.pm` test on vendor `st` with Twister to hopefully find out all ST boards that fail the test

**Comment by FRASTM** [comment]
Same fix to be applied to `96b_aerocore2`  I guess

```
diff --git a/boards/arm/96b_aerocore2/96b_aerocore2.dts b/boards/arm/96b_aerocore2/96b_aerocore2.dts
index 4a4e8672f7..dd5f8d8a89 100644
--- a/boards/arm/96b_aerocore2/96b_aerocore2.dts
+++ b/boards/arm/96b_aerocore2/96b_aerocore2.dts
@@ -42,6 +42,10 @@
 
 };
 
+&clk_lsi {
+	status = "okay";
+};
+
 &clk_hse {
 	clock-frequency = <DT_FREQ_M(24)>;
 	status = "okay";
@@ -180,6 +184,12 @@ zephyr_udc0: &usbotg_fs {
 	status = "okay";
 };
 
+&rtc {
+	clocks = <&rcc STM32_CLOCK_BUS_APB1 0x10000000>,
+		 <&rcc STM32_SRC_LSI RTC_SEL(2)>;
+	status = "okay";
+};
+
 &rng {
 	status = "okay";
 };

```

**Comment by erwango** [comment]
Ideally we need a better solution than the need to enable RTC on all boards, otherwise this will pop up every now and then.
