### ISSUE TITLE
Enable hardware flow control in mcux uart shim driver

### ISSUE THREAD

**Issue by MaureenHelm** [zephyrproject-rtos/zephyr#6636]
Update the imported mcux uart driver to a newer upstream version that includes support for hardware flow control, then expose that feature in the zephyr shim.

Depends on #6633
 
cc: @mike-scott

**Comment by mike-scott** [comment]
@MaureenHelm What's the status on https://github.com/zephyrproject-rtos/zephyr/pull/6633?

**Comment by MaureenHelm** [comment]
The board decided not to accept the license, so now we have to wait for multi-git repos (#6770).

**Comment by mike-scott** [comment]
Thank you for the update.  Makes sense.

**Comment by MaureenHelm** [comment]
Fixed by #12835
