### ISSUE TITLE
nrf5340 bluetooth iso_receive & iso_broadcast data error

### ISSUE THREAD

**Issue by dabeixiaomibujiatang** [zephyrproject-rtos/zephyr#66371]
I have tried the zephyr bluetooth examples iso_receive & iso_broadcast on two nrf5340 board, iso_receive  board can sync to iso_broadcast board, but the receive data len is 0 byte. So i added the iso_broadcast send data from 4 bytes to 8 bytes, the iso_receive  board can received 8 bytes data. But after some time, the the iso_receive  board receive data len changed to 0 byte.

*** Booting Zephyr OS build v3.3.99-ncs1-1 ***
Starting ISO Broadcast Demo
*** Booting Zephyr OS build v3.3.99-ncs1-1 ***
Starting Synchronized Receiver Demo

logs:
PER_ADV_SYNC[0]: [DEVICE]: 0E:79:EC:1C:79:1F (random), tx_power 127, RSSI -53, CTE 0, data length 0, data: 
BIG INFO[0]: [DEVICE]: 0E:79:EC:1C:79:1F (random), sid 0x00, num_bis 2, nse 3, interval 0x0050 (100 ms), bn 1, pto 1, irc 2, max_pdu 8, sdu_interval 100000 us, max_sdu 8, phy LE 2M, without framing, not encrypted
Incoming data channel 0x2000012c flags 0x9 seq_num 239 ts 26589338 len 8: 0001020304050607 (counter value 0)
Incoming data channel 0x20000140 flags 0x9 seq_num 239 ts 26589338 len 8: 0001020304050607 (counter value 0)
Incoming data channel 0x2000012c flags 0x9 seq_num 240 ts 26689340 len 8: 0001020304050607 (counter value 0)
Incoming data channel 0x20000140 flags 0x9 seq_num 240 ts 26689340 len 8: 0001020304050607 (counter value 0)
Incoming data channel 0x2000012c flags 0x9 seq_num 241 ts 26789342 len 8: 0001020304050607 (counter value 0)
Incoming data channel 0x20000140 flags 0x9 seq_num 241 ts 26789342 len 8: 0001020304050607 (counter value 0)
Incoming data channel 0x2000012c flags 0x9 seq_num 242 ts 26889344 len 8: 0001020304050607 (counter value 0)
Incoming data channel 0x20000140 flags 0x9 seq_num 242 ts 26889344 len 8: 0001020304050607 (counter value 0)
Incoming data channel 0x2000012c flags 0x9 seq_num 243 ts 26989345 len 8: 0001020304050607 (counter value 0)
Incoming data channel 0x20000140 flags 0x9 seq_num 243 ts 26989345 len 8: 0001020304050607 (counter value 0)
Incoming data channel 0x2000012c flags 0x9 seq_num 244 ts 27089347 len 8: 0001020304050607 (counter value 0)
Incoming data channel 0x20000140 flags 0x9 seq_num 244 ts 27089347 len 8: 0001020304050607 (counter value 0)
Incoming data channel 0x2000012c flags 0x9 seq_num 245 ts 27189349 len 8: 0001020304050607 (counter value 0)
Incoming data channel 0x20000140 flags 0x9 seq_num 245 ts 27189349 len 8: 0001020304050607 (counter value 0)
Incoming data channel 0x2000012c flags 0x9 seq_num 246 ts 27289351 len 8: 0001020304050607 (counter value 0)
Incoming data channel 0x20000140 flags 0x9 seq_num 246 ts 27289351 len 8: 0001020304050607 (counter value 0)
Incoming data channel 0x2000012c flags 0x9 seq_num 247 ts 27389352 len 8: 0001020304050607 (counter value 0)
Incoming data channel 0x20000140 flags 0x9 seq_num 247 ts 27389352 len 8: 0001020304050607 (counter value 0)
Incoming data channel 0x2000012c flags 0x9 seq_num 248 ts 27489355 len 8: 0001020304050607 (counter value 0)
Incoming data channel 0x20000140 flags 0x9 seq_num 248 ts 27489355 len 8: 0001020304050607 (counter value 0)
Incoming data channel 0x2000012c flags 0x9 seq_num 249 ts 27589357 len 8: 0001020304050607 (counter value 0)
Incoming data channel 0x20000140 flags 0x9 seq_num 249 ts 27589357 len 8: 0001020304050607 (counter value 0)
Incoming data channel 0x2000012c flags 0x9 seq_num 250 ts 27689358 len 8: 0001020304050607 (counter value 0)
Incoming data channel 0x20000140 flags 0x9 seq_num 250 ts 27689358 len 8: 0001020304050607 (counter value 0)
PER_ADV_SYNC[0]: [DEVICE]: 0E:79:EC:1C:79:1F (random), tx_power 127, RSSI -54, CTE 0, data length 0, data: 
BIG INFO[0]: [DEVICE]: 0E:79:EC:1C:79:1F (random), sid 0x00, num_bis 2, nse 3, interval 0x0050 (100 ms), bn 1, pto 1, irc 2, max_pdu 8, sdu_interval 100000 us, max_sdu 8, phy LE 2M, without framing, not encrypted
Incoming data channel 0x2000012c flags 0x9 seq_num 251 ts 27789360 len 8: 0001020304050607 (counter value 0)
Incoming data channel 0x20000140 flags 0x9 seq_num 251 ts 27789360 len 8: 0001020304050607 (counter value 0)
Incoming data channel 0x2000012c flags 0x9 seq_num 252 ts 27889363 len 8: 0001020304050607 (counter value 0)
Incoming data channel 0x20000140 flags 0x9 seq_num 252 ts 27889363 len 8: 0001020304050607 (counter value 0)
Incoming data channel 0x2000012c flags 0x9 seq_num 253 ts 27989364 len 8: 0001020304050607 (counter value 0)
Incoming data channel 0x20000140 flags 0x9 seq_num 253 ts 27989364 len 8: 0001020304050607 (counter value 0)
Incoming data channel 0x2000012c flags 0x9 seq_num 254 ts 28089365 len 8: 0001020304050607 (counter value 0)
Incoming data channel 0x20000140 flags 0x9 seq_num 254 ts 28089365 len 8: 0001020304050607 (counter value 0)
Incoming data channel 0x2000012c flags 0x9 seq_num 255 ts 28189367 len 8: 0001020304050607 (counter value 0)
Incoming data channel 0x20000140 flags 0x9 seq_num 255 ts 28189367 len 8: 0001020304050607 (counter value 0)
Incoming data channel 0x2000012c flags 0x9 seq_num 256 ts 28289369 len 8: 0001020304050607 (counter value 0)
Incoming data channel 0x20000140 flags 0x9 seq_num 256 ts 28289369 len 8: 0001020304050607 (counter value 0)
Incoming data channel 0x2000012c flags 0x9 seq_num 257 ts 28389370 len 8: 0001020304050607 (counter value 0)
Incoming data channel 0x20000140 flags 0x9 seq_num 257 ts 28389370 len 8: 0001020304050607 (counter value 0)
Incoming data channel 0x2000012c flags 0xa seq_num 258 ts 28489372 len 0:  (counter value 0)
Incoming data channel 0x20000140 flags 0xa seq_num 258 ts 28489372 len 0:  (counter value 0)
Incoming data channel 0x2000012c flags 0xa seq_num 259 ts 28589374 len 0:  (counter value 0)
Incoming data channel 0x20000140 flags 0xa seq_num 259 ts 28589374 len 0:  (counter value 0)
Incoming data channel 0x2000012c flags 0xa seq_num 260 ts 28689376 len 0:  (counter value 0)
Incoming data channel 0x20000140 flags 0xa seq_num 260 ts 28689376 len 0:  (counter value 0)
Incoming data channel 0x2000012c flags 0xa seq_num 261 ts 28789378 len 0:  (counter value 0)
Incoming data channel 0x20000140 flags 0xa seq_num 261 ts 28789378 len 0:  (counter value 0)
Incoming data channel 0x2000012c flags 0xa seq_num 262 ts 28889379 len 0:  (counter value 0)
Incoming data channel 0x20000140 flags 0xa seq_num 262 ts 28889379 len 0:  (counter value 0)
PER_ADV_SYNC[0]: [DEVICE]: 0E:79:EC:1C:79:1F (random), tx_power 127, RSSI -56, CTE 0, data length 0, data: 
BIG INFO[0]: [DEVICE]: 0E:79:EC:1C:79:1F (random), sid 0x00, num_bis 2, nse 3, interval 0x0050 (100 ms), bn 1, pto 1, irc 2, max_pdu 8, sdu_interval 100000 us, max_sdu 8, phy LE 2M, without framing, not encrypted
Incoming data channel 0x2000012c flags 0xa seq_num 263 ts 28989381 len 0:  (counter value 0)
Incoming data channel 0x20000140 flags 0xa seq_num 263 ts 28989381 len 0:  (counter value 0)
Incoming data channel 0x2000012c flags 0xa seq_num 264 ts 29089384 len 0:  (counter value 0)
Incoming data channel 0x20000140 flags 0xa seq_num 264 ts 29089384 len 0:  (counter value 0)
Incoming data channel 0x2000012c flags 0xa seq_num 265 ts 29189385 len 0:  (counter value 0)
Incoming data channel 0x20000140 flags 0xa seq_num 265 ts 29189385 len 0:  (counter value 0)
Incoming data channel 0x2000012c flags 0xa seq_num 266 ts 29289388 len 0:  (counter value 0)
Incoming data channel 0x20000140 flags 0xa seq_num 266 ts 29289388 len 0:  (counter value 0)
Incoming data channel 0x2000012c flags 0xa seq_num 267 ts 29389388 len 0:  (counter value 0)
Incoming data channel 0x20000140 flags 0xa seq_num 267 ts 29389388 len 0:  (counter value 0)
Incoming data channel 0x2000012c flags 0xa seq_num 268 ts 29489391 len 0:  (counter value 0)
Incoming data channel 0x20000140 flags 0xa seq_num 268 ts 29489391 len 0:  (counter value 0)
Incoming data channel 0x2000012c flags 0xa seq_num 269 ts 29589393 len 0:  (counter value 0)
Incoming data channel 0x20000140 flags 0xa seq_num 269 ts 29589393 len 0:  (counter value 0)
Incoming data channel 0x2000012c flags 0xa seq_num 270 ts 29689394 len 0:  (counter value 0)
Incoming data channel 0x20000140 flags 0xa seq_num 270 ts 29689394 len 0:  (counter value 0)
Incoming data channel 0x2000012c flags 0xa seq_num 271 ts 29789396 len 0:  (counter value 0)
Incoming data channel 0x20000140 flags 0xa seq_num 271 ts 29789396 len 0:  (counter value 0)
Incoming data channel 0x2000012c flags 0xa seq_num 272 ts 29889398 len 0:  (counter value 0)
Incoming data channel 0x20000140 flags 0xa seq_num 272 ts 29889398 len 0:  (counter value 0)
Incoming data channel 0x2000012c flags 0xa seq_num 273 ts 29989399 len 0:  (counter value 0)
Incoming data channel 0x20000140 flags 0xa seq_num 273 ts 29989399 len 0:  (counter value 0)
Incoming data channel 0x2000012c flags 0xa seq_num 274 ts 30089402 len 0:  (counter value 0)
Incoming data channel 0x20000140 flags 0xa seq_num 274 ts 30089402 len 0:  (counter value 0)
PER_ADV_SYNC[0]: [DEVICE]: 0E:79:EC:1C:79:1F (random), tx_power 127, RSSI -54, CTE 0, data length 0, data: 
BIG INFO[0]: [DEVICE]: 0E:79:EC:1C:79:1F (random), sid 0x00, num_bis 2, nse 3, interval 0x0050 (100 ms), bn 1, pto 1, irc 2, max_pdu 8, sdu_interval 100000 us, max_sdu 8, phy LE 2M, without framing, not encrypted

In the iso_broadcast zephyr code, the iso send  function bt_iso_chan_send(&bis_iso_chan[chan], buf,seq_num, BT_ISO_TIMESTAMP_NONE); the timestamp parameter is "BT_ISO_TIMESTAMP_NONE". It means no timestamp?
And why iso_receive  board can analysis a timestamp?

**Comment by nordicjm** [comment]
> *** Booting Zephyr OS build v3.3.99-ncs1-1 ***

You are using ncs, not zephyr, this issue should be reported to https://devzone.nordicsemi.com unless you can reproduce the issue in upstream zephyr without using NCS.
