### ISSUE TITLE
tests/net/hostname test issue regression

### ISSUE THREAD

**Issue by Desvauxm-st** [zephyrproject-rtos/zephyr#66380]
Describe the bug:

in our bench tester many board test fail now with:

tests/net/hostname
for example:

 west build -p always -b   nucleo_h743zi  tests/net/hostname

test is blocked in the console nothing is displayed

it is due to this commit:
https://github.com/zephyrproject-rtos/zephyr/commit/78af1c1e3878c410067bd49846771300fa86b840

entropy: stm32: suspend when pool is full
https://github.com/zephyrproject-rtos/zephyr/commit/78af1c1e3878c410067bd49846771300fa86b840
author: Dawid Niedzwiecki [dawidn@google.com](mailto:dawidn@google.com) 2023-12-01 11:27:37
Committer: Maureen Helm [maureen.helm@analog.com](mailto:maureen.helm@analog.com) 2023-12-05 23:27:53

thanks to have a look

**Comment by niedzwiecki-dawid** [comment]
Can we close this one?

**Comment by erwango** [comment]
> Can we close this one?

Yes, closing. Thanks for the support
