### ISSUE TITLE
Fix custom no-init RAM definition

### ISSUE THREAD

**Issue by bfa8** [zephyrproject-rtos/zephyr#66422]
**Related problem**
In our project we need to use the no-init RAM. Since we are using a bootloader (mcuboot), we need to define the no-init RAM memory at a fix address, so this memory area is located at the same address for the bootloader and the productive firmware. In this case, we are forced to customize the main linker script in Zephyr.

**The solution we are looking for**
Zephyr already provides a no-init RAM section. However, the problem is that this section is placed right after the .bss data. So it's not at the same address for the bootloader and the productive firmware. The wish would be that it's possible to place the no-init RAM section provided by Zephyr at a defined address (without customizing the main linker script in Zephyr).

**Current solution**
Currently we are forced to customize the main linker script in Zephyr.

**Comment by nordicjm** [comment]
Already supported in retention subsystem using retained memory
