### ISSUE TITLE
net: socket: tcp: net.socket.tcp and net.socket.tcp.preempt fail

### ISSUE THREAD

**Issue by katgiadla** [zephyrproject-rtos/zephyr#66469]
**Describe the bug**
The tests `net.socket.tcp` and `net.socket.tcp.preempt` fail.

Observed for `nrf5340dk_nrf5340_cpuapp_ns`

**To Reproduce**
1. have `nrf5340dk_nrf5340_cpuapp_ns` connected
2. go to your zephyr dir
3. call `./scripts/twister -T tests/net/socket/tcp -p nrf5340dk_nrf5340_cpuapp_ns --device-testing --device-serial /dev/ttyACM1 -v --inline-logs`
4. See console output with error

**Expected behavior**
Valid console output

**Impact**
Not clear

**Logs and console output**
```
Error: Image size (0x2ffee) + trailer (0x1b0) exceeds requested size 0x30000
```

**Environment (please complete the following information):**
- OS: Ubuntu 20.04.1 LTS
- Toolchain Zephyr SDK 0.16.1
- Commit SHA or Version used: zephyr-v3.5.0-2927-g03b702690ae7

**Comment by carlescufi** [comment]
@joerchan this is TF-M related, correct?

**Comment by joerchan** [comment]
> @joerchan this is TF-M related, correct?

@carlescufi It's a size problem. test application does not fit into 192 KB. Easiest fix it to disable the bootloader to give the application more space.

**Comment by carlescufi** [comment]
@joerchan probably better to disable the bootloader for now then please.
cc @nordicjm @de-nordic
