### ISSUE TITLE
CONFIG_NET_RPL_DAG_MC_NONE is not defined anywhere

### ISSUE THREAD

**Issue by nashif** [zephyrproject-rtos/zephyr#665]
Option being used here:

subsys/net/ip/rpl.c:#if !defined(CONFIG_NET_RPL_DAG_MC_NONE)
subsys/net/ip/rpl.c:#if !defined(CONFIG_NET_RPL_DAG_MC_NONE)

but is not defined in Kconfig.

**Comment by rveerama1** [comment]
https://github.com/zephyrproject-rtos/zephyr/pull/751
