### ISSUE TITLE
Adding Xtensa MPU Support

### ISSUE THREAD

**Issue by dcpleung** [zephyrproject-rtos/zephyr#66546]
Since we already have MMU support for Xtensa, we need MPU to complete the circle.

**Comment by jcmvbkbc-issues** [comment]
It should be possible. I have a couple LX configurations with MPU, the most relevant seems to be the sample_controller version configured with MPU. I can submit it for QEMU 9 and publish its overlay so that you could make a toolchain and QEMU for it.

**Comment by dcpleung** [comment]
That's awesome. Thank you very much.

**Comment by jcmvbkbc-issues** [comment]
I've pushed the original and the preprocessed overlays for the sample_controller32 here: https://github.com/jcmvbkbc/xtensa-toolchain-build/commit/435c5e8b108de520565886f3f2349cc6be3fe712
and QEMU branch with this core and a couple minor issues fixed is available here: https://github.com/OSLL/qemu-xtensa/commits/xtensa-9.0-mpu/

**Comment by dcpleung** [comment]
@jcmvbkbc Is it possible to have a MPU capable SoC configuration for Zephyr? We wish to incorporate testing of the MPU code in CI, which means the overlay and QEMU patches will need to be publicly available (even if we are to keep them with Zephyr trees).
