### ISSUE TITLE
efm32wg_stk3800 bluetooth sample do not compile (add support)

### ISSUE THREAD

**Issue by deadpoolcode1** [zephyrproject-rtos/zephyr#6654]
when trying to compile central_hr example for board efm32wg_stk3800, I get the following error: 

```
drivers/bluetooth/hci/h4.c:462:30: error: ‘CONFIG_BT_UART_ON_DEV_NAME’ undeclared (first use in this function)
h4_dev = device_get_binding(CONFIG_BT_UART_ON_DEV_NAME);
```

**Comment by chrta** [comment]
So something like this is missing in the board's dts file, right?

~~~
#ifdef CONFIG_BT
                zephyr,bt-uart = &uart3;
#endif
~~~

Which UART and pins should be used for this?
I will not be able to test any implementation, since i do not have any bt hardware.

**Comment by warner83** [comment]
Same issue also with cc2650_sensortag
Any workaround?

**Comment by a46554** [comment]
I add 

`#ifdef CONFIG_BT
        zephyr,bt-uart = &uart0;
#endif
`
in boards/arm/cc2650_sensortag/cc2650_sensortag.dts.
Build success but can't scan the BLE signal from my CC2640 board

**Comment by chrta** [comment]
I think that should be a dedicated uart that is not used otherwise, like for the console, right?

**Comment by a46554** [comment]
bt-uart is use to communication between BLE host and BLE controller. CC2650 is totally BLE SOC solution like nrf52832. So that bt-uart shouldn't exist when TI CC2650 BLE function is support.

**Comment by a46554** [comment]
bt-uart is use to communication between BLE host and BLE controller. CC2650 is totally BLE SOC solution like nrf52832. So that bt-uart shouldn't exist when TI CC2650 BLE function is support.

**Comment by redradist** [comment]
Hi guys,

I have the same issue as @warner83 on **cc2650_sensortag**
This hardware is not supported yet or something missed in config file ?

**Comment by PingiliV** [comment]
Hi, Iam getting this issue while compiling samples/bluetooth/beacon for psoc6. Is this issue resolved?
Any workaround?

**Comment by chrta** [comment]
Just to clarify: The board efm32wg_stk3800 does not have any bluetooth hardware.

Question from me? Is there anything generic that can/should be done here? Or should we close this issue?

**Comment by chrta** [comment]
Closing this because there was no feedback for over a year.
