### ISSUE TITLE
Question: Is Bluetooth avrcp supported in Zephyr? Or any plan? 

### ISSUE THREAD

**Issue by hongshui3000** [zephyrproject-rtos/zephyr#6657]

**Comment by carlescufi** [comment]
There's basic support for AVDTP here: https://github.com/zephyrproject-rtos/zephyr/blob/master/subsys/bluetooth/host/avdtp.c. Feel free to contribute usage samples.

**Comment by mbrunnen** [comment]
I think AVDTP is not same as AVRCP.

**Comment by DR-DXC** [comment]
Any new on this? is AVRCP supported?
