### ISSUE TITLE
k_thread_foreach in kernel shell commands can trigger kernel panic

### ISSUE THREAD

**Issue by benediktibk** [zephyrproject-rtos/zephyr#66660]
In a minimal sample, where k_thread_foreach is executed regularly, it is possible to trigger a kernel panic when one issues the shell command `kernel threads`.

main.c:

    static void thread_callback(const struct k_thread *thread, void *user_data)
    {
    }
    
    int main(void)
    {
        while (true) {
            k_sleep(K_MSEC(10));
            k_thread_foreach(thread_callback, NULL);
        }
    }

prj.conf:

    CONFIG_DEBUG_OPTIMIZATIONS=y
    CONFIG_LOG=y
    CONFIG_ASAN=y
    CONFIG_SHELL=y
    CONFIG_THREAD_MONITOR=y
    CONFIG_THREAD_RUNTIME_STATS=y
    CONFIG_ASSERT=y

shell:

    uart:~$ kernel threads
    Scheduler: 86 since last call
    Threads:
    0x20010c40 sysworkq  
        options: 0x0, priority: -1 timeout: 0
        state: pending, entry: ba9

    ASSERTION FAIL [z_spin_lock_valid(l)] @ WEST_TOPDIR/zephyr/include/zephyr/spinlock.h:136
        Invalid spinlock 0x20011264
    [00:00:06.353,000] <err> os: r0/a1:  0x00000004  r1/a2:  0x00000088  r2/a3:  0x00000001
    [00:00:06.353,000] <err> os: r3/a4:  0x00000088 r12/ip:  0x0000f82a r14/lr:  0x08009537
    [00:00:06.353,000] <err> os:  xpsr:  0x41000000
    [00:00:06.353,000] <err> os: Faulting instruction address (r15/pc): 0x0800e7dc
    [00:00:06.353,000] <err> os: >>> ZEPHYR FATAL ERROR 4: Kernel panic on CPU 0
    [00:00:06.353,000] <err> os: Current thread: 0x20010b18 (main)
    [00:00:06.415,000] <err> os: Halting system

I can reproduce this issue with zephyr-v3.5.0-3271-g67099d2bbade on a stm32f746g_disco.

From my analysis I nailed it down to happening only if two calls to k_thread_foreach are executed in parallel. Theoretically there is a spinlock in place. The spinlock first executes `arch_irq_lock()` and then `z_spinlock_validate_pre`, which in turn fails at `__ASSERT(z_spin_lock_valid(l), "Invalid spinlock %p", l);`.

Looking at the implementation of z_spin_lock_valid I assume that one thread on the CPU has already acquired the spinlock. But this should be in theory not possible due to `arch_irq_lock()` . At least this is how I understood it.

    bool z_spin_lock_valid(struct k_spinlock *l)
    {
        uintptr_t thread_cpu = l->thread_cpu;
    
        if (thread_cpu != 0U) {
            if ((thread_cpu & 3U) == _current_cpu->id) {
                return false;
            }
        }
        return true;
    }

The impact for me is that I cannot use kernel shell commands like `stacks` or `threads` anymore, as I have a background task which runs `k_thread_foreach`.

**Comment by cfriedt** [comment]
I've encountered exactly this issue, and IIRC, we did need to use the same solution in the linked PR.
