### ISSUE TITLE
[Coverity CID: 183066] Error handling issues in /tests/kernel/mbox/mbox_api/src/test_mbox_api.c

### ISSUE THREAD

**Issue by Shilpashree3lc** [zephyrproject-rtos/zephyr#6666]
Static code scan issues seen in File: /tests/kernel/mbox/mbox_api/src/test_mbox_api.c
 Category: Error handling issues
 Function: tmbox_get
 Component: Tests
 CID: 183066
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by spoorthik** [comment]
The issue is already fixed in the latest version of code base. This can be closed.

**Comment by mandarcthorat1** [comment]
The problem is detected again by latest coverity scan. Please have a look

**Comment by ceolin** [comment]
#14857
