### ISSUE TITLE
[Coverity CID: 183062] Error handling issues in /samples/net/sockets/big_http_download/src/big_http_download.c

### ISSUE THREAD

**Issue by Shilpashree3lc** [zephyrproject-rtos/zephyr#6670]
Static code scan issues seen in File: /samples/net/sockets/big_http_download/src/big_http_download.c
 Category: Error handling issues
 Function: download
 Component: Samples
 CID: 183062
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by nashif** [comment]
this is now fixed in #7517
