### ISSUE TITLE
doc: Documentation issue in 'guides/kconfig/tips' - broken hyperlink from kconfiglib to zephyrproject

### ISSUE THREAD

**Issue by ngenetzky-appareo** [zephyrproject-rtos/zephyr#66701]
**Describe the bug**

Broke hyperlink from https://pypi.org/project/kconfiglib/ to [zephyrproject](https://docs.zephyrproject.org/latest/guides/kconfig/tips.html).

Here is the text with the hyperlink:

> See [this page](https://docs.zephyrproject.org/latest/guides/kconfig/tips.html) for some Kconfig tips and best practices.

**Environment**

* Page: https://docs.zephyrproject.org/latest/guides/kconfig/tips.html
* Version: main
* SHA-1: 8c361404085f9ba407cce731076cbcc33ae86213

CC: @ulfalizer 

Cross-Posted: 

- https://github.com/zephyrproject-rtos/zephyr/issues/66701
- https://github.com/ulfalizer/Kconfiglib/issues/135

**Comment by kartben** [comment]
Hi @ngenetzky-appareo -- thanks for the report! It's not clear to me if there is anything to track on the Zephyr side of things? The "Kconfig - Tips and Best Practices" page doesn't have any broken links, correct? It looks as it's rather some broken links in the upstream Kconfiglib docs and published pypi package?

**Comment by ngenetzky-appareo** [comment]
If this information has been moved and you know where that would be helpful
to add here or in the linked ticket.

I am not very familiar with the documentation generator you use, but it's
possibly that an "alias" or "redirect" could be added to fix the issue.

Zephyr has a much larger contributor base and higher quality documentation
than the other project. It is also possible that other projects have also
linked to zephyr's great documentation.

**Comment by kartben** [comment]
Oh, I see! It used to be at a different URL, gotcha. Yes, we have a way to have redirects. Will make a PR :)
