### ISSUE TITLE
stm32f412cg unexpected power consumption for MCO2

### ISSUE THREAD

**Issue by niedzwiecki-dawid** [zephyrproject-rtos/zephyr#66720]
The STM32F412 chips have 2 MCO pins:
![image](https://github.com/zephyrproject-rtos/zephyr/assets/72437029/17a4d2da-c156-439b-b419-2425fb3abd00)

The MCO2 pin can have 4 different source clocks:
![image](https://github.com/zephyrproject-rtos/zephyr/assets/72437029/7c5fd67f-f53e-48bd-b0d2-351cdbe37b6d)

I've noticed that when I change the source from a default one (SYSCLK) to PLLI2S (PLLI2S not enabled) or HSE (not connected), the power consumption drops ~0,5mW.

I'm working with [google_dragonclaw](https://github.com/zephyrproject-rtos/zephyr/tree/main/boards/arm/google_dragonclaw) board, which uses STM32F412CG chip in UFQFPN48 package. This chip version doesn't even have the MCO2 pin (PC9).
![image](https://github.com/zephyrproject-rtos/zephyr/assets/72437029/ff457909-f647-4ba3-8ab4-3e93cd37beef)

This behavior can't be observed for the MCO1 pin in my case. 

The STM32 HAL doesn't even define bits for MCO2 configuration for [STM32F412cx](https://github.com/zephyrproject-rtos/hal_stm32/blob/main/stm32cube/stm32f4xx/soc/stm32f412cx.h#L8485) boards. I guess it is done this way because none of the STM32F412cx chips don't have the MCO2 pin. This doesn't even allow changing the source with the config `CONFIG_CLOCK_STM32_MCO2_SRC_x`.

Unfortunately, there is no nucleo board with that version of chip to confirm that issue.

Would you be able to somehow confirm that this is expected behavior or it is kind of silicon bug?

**Comment by erwango** [comment]
> Would you be able to somehow confirm that this is expected behavior or it is kind of silicon bug?

Nothing is specified in Errata sheet around such behavior. I'd suggesting asking st.community.

**Comment by niedzwiecki-dawid** [comment]
Will do. Do you think it is a good approach from HAL side that it doesn't allow changing the MCO2 bits when the PC9 pin is not present?

**Comment by erwango** [comment]
@niedzwiecki-dawid To be sure I understand correctly: What are you doing to solve the point ?
Also, IIUC, by default, you don't have any setting on PC9, right ?

**Comment by niedzwiecki-dawid** [comment]
I would like to set the MCO2 source clock to HSE, because it saves 0,5mW
![image](https://github.com/zephyrproject-rtos/zephyr/assets/72437029/06d3b05f-6da7-4437-a4e7-8d8c6adf66a0)

It is not related to MCO1 in any way.

>Also, IIUC, by default, you don't have any setting on PC9, right ?

My chip doesn't have the PC9 pin, so I don't configure it.

**Comment by erwango** [comment]
So, from zephyr perspective, what would be the change required ?
I guess you're able to do a: CONFIG_CLOCK_STM32_MCO2_SRC_HSE=y, right ?

Or maybe this doesn't compile because of missing HAL defines ?

**Comment by niedzwiecki-dawid** [comment]
>Or maybe this doesn't compile because of missing HAL defines ?
Yes, the MCO2 bits are [not defined](https://github.com/zephyrproject-rtos/hal_stm32/blob/main/stm32cube/stm32f4xx/soc/stm32f412cx.h#L8485).

**Comment by niedzwiecki-dawid** [comment]
Ok, I will.

One side question, also in the clock area. Is there any way to set the PLLR division factor for STM32F412 chips? I've notice that increasing the division factor also reduces power consumption, which of course make sense and have confirmation in an application note regarding power consumption.

![image](https://github.com/zephyrproject-rtos/zephyr/assets/72437029/a199aa31-92f2-4693-aa6a-cc56ff98a49e)

**Comment by erwango** [comment]
> One side question, also in the clock area. Is there any way to set the PLLR division factor for STM32F412 chips? I've notice that increasing the division factor also reduces power consumption, which of course make sense and have confirmation in an application note regarding power consumption.

It isn't indeed. What you'd need to do is to add the matching prop in `dts/bindings/clock/st,stm32f4-pll-clock.yaml`, and update `include/zephyr/drivers/clock_control/stm32_clock_control.h`. The c driver should already be compatible.
One tricky part might be that this PLL R output might not be available on all F4 series, so you might have to create a f412-pll dedicated binding, similarly to what was done for `dts/bindings/clock/st,stm32f412-plli2s-clock.yaml`

**Comment by niedzwiecki-dawid** [comment]
Ok, thanks for the info. I wasn't sure if I've missed something and it can be done without changes.

**Comment by niedzwiecki-dawid** [comment]
FYI ST community [post](https://community.st.com/t5/stm32-mcus-products/stm32412cg-ufqfpn48-mco2-unexpected-power-consumption/m-p/622038) regarding MCO2.

**Comment by niedzwiecki-dawid** [comment]
@erwango Is there any procedure to cherry-pick https://github.com/STMicroelectronics/cmsis_device_f4/commit/2e1724e592931693ce4dfc43e2fd6b3bc375d6a0 ?

**Comment by niedzwiecki-dawid** [comment]
Great, thanks

**Comment by niedzwiecki-dawid** [comment]
@erwango The MCO2 [commit](https://github.com/STMicroelectronics/cmsis_device_f4/commit/2e1724e592931693ce4dfc43e2fd6b3bc375d6a0)  has been merged some time ago, but I still can't see it in [hal_stm32](https://github.com/zephyrproject-rtos/hal_stm32/). Is there anything I should do to pull the commit?

**Comment by erwango** [comment]
> @erwango The MCO2 [commit](https://github.com/STMicroelectronics/cmsis_device_f4/commit/2e1724e592931693ce4dfc43e2fd6b3bc375d6a0) has been merged some time ago, but I still can't see it in [hal_stm32](https://github.com/zephyrproject-rtos/hal_stm32/). Is there anything I should do to pull the commit?

You can push a PR to update west.yaml.
But this is also on going with https://github.com/zephyrproject-rtos/zephyr/pull/71484

**Comment by niedzwiecki-dawid** [comment]
Ok, thanks :-)
