### ISSUE TITLE
[Coverity CID: 183056] Memory - corruptions in /tests/kernel/common/src/atomic.c

### ISSUE THREAD

**Issue by Shilpashree3lc** [zephyrproject-rtos/zephyr#6676]
Static code scan issues seen in File: /tests/kernel/common/src/atomic.c
 Category: Memory - corruptions
 Function: test_atomic
 Component: Tests
 CID: 183056
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by nashif** [comment]
intentional
