### ISSUE TITLE
[Coverity CID: 183055] Concurrent data access violations in /kernel/posix/pthread.c

### ISSUE THREAD

**Issue by Shilpashree3lc** [zephyrproject-rtos/zephyr#6677]
Static code scan issues seen in File: /kernel/posix/pthread.c
 Category: Concurrent data access violations
 Function: pthread_cancel
 Component: Kernel
 CID: 183055
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by ramakrishnapallala** [comment]
@Shilpashree3lc fixed already in lib/posix/pthread.c
