### ISSUE TITLE
[Coverity CID: 183054] Memory - corruptions in /tests/lib/c_lib/src/main.c

### ISSUE THREAD

**Issue by Shilpashree3lc** [zephyrproject-rtos/zephyr#6678]
Static code scan issues seen in File: /tests/lib/c_lib/src/main.c
 Category: Memory - corruptions
 Function: test_strcpy
 Component: Tests
 CID: 183054
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by SavinayDharmappa** [comment]
> 1. string_overflow: You might overrun the 10-character destination string buffer by writing 11 characters from "10 chars!".
189        strcpy(buffer, "10 chars!\0");

**Comment by SavinayDharmappa** [comment]
closing this as this not an issue
