### ISSUE TITLE
We still have references to wiki.zephyrproject.org

### ISSUE THREAD

**Issue by nashif** [zephyrproject-rtos/zephyr#668]
The files below should be adapted to point to the right location in the Zephyr documentation:

- samples/net/mbedtls_sslclient/README:[2] https://wiki.zephyrproject.org/view/Galileo_Gen1_Gen2
- samples/subsys/usb/console/README.txt:Refer to https://wiki.zephyrproject.org/view/Arduino_101 for details on flashing
- samples/subsys/usb/mass/README.txt:Refer to https://wiki.zephyrproject.org/view/Arduino_101 for details on flashing
- samples/subsys/usb/webusb/README.txt:Refer to https://wiki.zephyrproject.org/view/Arduino_101 for details on
- tests/bluetooth/tester/README:[1] https://wiki.zephyrproject.org/view/Arduino_101#Bluetooth_firmware_for_the_Arduino_101
- tests/net/lib/mqtt_packet/README:  https://wiki.zephyrproject.org/view/Arduino_101

**Comment by dbkinder** [comment]
Addressed with PR #757
