### ISSUE TITLE
[Coverity CID: 183052] Memory - corruptions in /tests/net/app/src/main.c

### ISSUE THREAD

**Issue by Shilpashree3lc** [zephyrproject-rtos/zephyr#6680]
Static code scan issues seen in File: /tests/net/app/src/main.c
 Category: Memory - corruptions
 Function: app_udp4_client_peer_addr
 Component: Tests
 CID: 183052
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by jukkar** [comment]
False positive.
