### ISSUE TITLE
[Coverity CID: 183047] Uninitialized variables in /kernel/smp.c

### ISSUE THREAD

**Issue by Shilpashree3lc** [zephyrproject-rtos/zephyr#6685]
Static code scan issues seen in File: /kernel/smp.c
 Category: Uninitialized variables
 Function: smp_init
 Component: Kernel
 CID: 183047
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by nashif** [comment]
dismissed as intentional
