### ISSUE TITLE
posix: implement `setenv()`

### ISSUE THREAD

**Issue by cfriedt** [zephyrproject-rtos/zephyr#66863]
This is part of the See [POSIX Roadmap for LTSv3](https://github.com/zephyrproject-rtos/zephyr/issues/51211) (RFC #51211).

`setenv()` is required as part of `POSIX_SINGLE_PROCESS` [Subprofiling Option Group](https://pubs.opengroup.org/onlinepubs/9699919799/xrat/V4_subprofiles.html).

For more information, please refer to https://pubs.opengroup.org/onlinepubs/9699919799/functions/setenv.html

**Comment by Sh0g0-1758** [comment]
hello, @nashif @cfriedt , can you please assign me this issue. I am new to this codebase and eager to contribute. Would like to tackle this.
