### ISSUE TITLE
posix: implement `unsetenv()`

### ISSUE THREAD

**Issue by cfriedt** [zephyrproject-rtos/zephyr#66864]
This is part of the See [POSIX Roadmap for LTSv3](https://github.com/zephyrproject-rtos/zephyr/issues/51211) (RFC #51211).

`unsetenv()` is required as part of `POSIX_SINGLE_PROCESS` [Subprofiling Option Group](https://pubs.opengroup.org/onlinepubs/9699919799/xrat/V4_subprofiles.html).

For more information, please refer to https://pubs.opengroup.org/onlinepubs/9699919799/functions/unsetenv.html

**Comment by Sh0g0-1758** [comment]
hey @cfriedt, I am working on the env part of POSIX calls. Would love to work on this. Can you please assign me it.
