### ISSUE TITLE
[Coverity CID: 183046] Memory - corruptions in /drivers/console/uart_console.c

### ISSUE THREAD

**Issue by Shilpashree3lc** [zephyrproject-rtos/zephyr#6686]
Static code scan issues seen in File: /drivers/console/uart_console.c
 Category: Memory - corruptions
 Function: handle_ansi
 Component: Drivers
 CID: 183046
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by pfalcon** [comment]
The story here is the same as in https://github.com/zephyrproject-rtos/zephyr/issues/6702#issuecomment-388878184 . Closing as no longer relevant, as the CID is marked Fixed in Coverity.
