### ISSUE TITLE
posix: implmement `getenv()`

### ISSUE THREAD

**Issue by cfriedt** [zephyrproject-rtos/zephyr#66862]
This is part of the See [POSIX Roadmap for LTSv3](https://github.com/zephyrproject-rtos/zephyr/issues/51211) (RFC #51211).

`getenv()` is required as part of `POSIX_SINGLE_PROCESS` [Subprofiling Option Group](https://pubs.opengroup.org/onlinepubs/9699919799/xrat/V4_subprofiles.html).

For more information, please refer to https://pubs.opengroup.org/onlinepubs/9699919799/functions/getenv.html

**Comment by Sh0g0-1758** [comment]
hello @cfriedt @nashif , can you please assign me this issue. I am eager to get familiar with Zephyr codebase and this would be a good start.
