### ISSUE TITLE
configurations for nimble still exist in tree

### ISSUE THREAD

**Issue by nashif** [zephyrproject-rtos/zephyr#669]
Are those still being used anywhere?

- ./tests/bluetooth/tester/nimble.conf
- ./tests/bluetooth/shell/prj_nimble.conf

**Comment by jhedberg** [comment]
Doesn't look like they're used. I'll send a PR to remove them. Btw, there are some references to "nimble" in the context of the A101 environmental_sensing apps test definitions as well, and e.g. a reference to a non-existing prj_nimble.conf in scripts/sanity_chk/sanity_last_release.csv which should also be fixed.

**Comment by jhedberg** [comment]
https://github.com/zephyrproject-rtos/zephyr/pull/670
