### ISSUE TITLE
[Coverity CID: 183038] Integer handling issues in /kernel/posix/timer.c

### ISSUE THREAD

**Issue by Shilpashree3lc** [zephyrproject-rtos/zephyr#6694]
Static code scan issues seen in File: /kernel/posix/timer.c
 Category: Integer handling issues
 Function: timer_gettime
 Component: Kernel
 CID: 183038
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by ramakrishnapallala** [comment]
Fix is already in place in lib/posix/timer.c

Please close this issue.

**Comment by ramakrishnapallala** [comment]
@Shilpashree3lc
