### ISSUE TITLE
[Coverity CID: 183037] Memory - corruptions in /samples/net/mbedtls_dtlsclient/src/dtls_client.c

### ISSUE THREAD

**Issue by Shilpashree3lc** [zephyrproject-rtos/zephyr#6695]
Static code scan issues seen in File: /samples/net/mbedtls_dtlsclient/src/dtls_client.c
 Category: Memory - corruptions
 Function: dtls_client
 Component: Samples
 CID: 183037
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by nashif** [comment]
samples/net/mbedtls_dtlsclient/ is removed from the repo
