### ISSUE TITLE
posix: implement `sched_getparam()`

### ISSUE THREAD

**Issue by ycsin** [zephyrproject-rtos/zephyr#66959]
This is part of the See [POSIX Roadmap for LTSv3](https://github.com/zephyrproject-rtos/zephyr/issues/51211) (RFC #51211).

`sched_getparam()` is required as part of `_POSIX_PRIORITY_SCHEDULING` Option Group.

For more information, please refer to https://pubs.opengroup.org/onlinepubs/9699919799/functions/sched_getparam.html

**Comment by golowanow** [comment]
related/depends on #67017
