### ISSUE TITLE
[Coverity CID: 183036] Control flow issues in /drivers/gpio/gpio_sam.c

### ISSUE THREAD

**Issue by Shilpashree3lc** [zephyrproject-rtos/zephyr#6696]
Static code scan issues seen in File: /drivers/gpio/gpio_sam.c
 Category: Control flow issues
 Function: gpio_sam_config
 Component: Drivers
 CID: 183036
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by himanshujha199640** [comment]
It is maked as `Fixed` in Coverity.
Please close this issue!
