### ISSUE TITLE
posix: implement `sched_rr_get_interval()`

### ISSUE THREAD

**Issue by ycsin** [zephyrproject-rtos/zephyr#66961]
This is part of the See [POSIX Roadmap for LTSv3](https://github.com/zephyrproject-rtos/zephyr/issues/51211) (RFC #51211).

`sched_rr_get_interval()` is required as part of `_POSIX_PRIORITY_SCHEDULING` Option Group.

For more information, please refer to https://pubs.opengroup.org/onlinepubs/9699919799/functions/sched_rr_get_interval.html

**Comment by moonlight83340** [comment]
> The sched_rr_get_interval() function shall update the timespec structure referenced by the interval argument to contain the current execution time limit (that is, time quantum) for the process specified by pid. If pid is zero, the current execution time limit for the calling process shall be returned.

Currently Zephyr has no concept of processes or process identifiers (PIDs) ?
Where should I start if I want to take a look at it ?
