### ISSUE TITLE
posix: implement `pthread_rwlockattr_setpshared()`

### ISSUE THREAD

**Issue by ycsin** [zephyrproject-rtos/zephyr#66965]
This is part of the See [POSIX Roadmap for LTSv3](https://github.com/zephyrproject-rtos/zephyr/issues/51211) (RFC #51211).

`pthread_rwlockattr_setpshared()` is required as part of `_POSIX_READER_WRITER_LOCKS` Option Group.

For more information, please refer to https://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_rwlockattr_setpshared.html

**Comment by moonlight83340** [comment]
I think https://github.com/zephyrproject-rtos/zephyr/pull/70421 close that issue.
And also this one https://github.com/zephyrproject-rtos/zephyr/issues/66964.
