### ISSUE TITLE
posix: implement `getpmsg()`

### ISSUE THREAD

**Issue by ycsin** [zephyrproject-rtos/zephyr#66976]
This is part of the See [POSIX Roadmap for LTSv3](https://github.com/zephyrproject-rtos/zephyr/issues/51211) (RFC #51211).

`getpmsg()` is required as part of `_XOPEN_STREAMS` Option Group.

For more information, please refer to https://pubs.opengroup.org/onlinepubs/9699919799/functions/getpmsg.html

**Comment by Sh0g0-1758** [comment]
hey @ycsin, I am new to Zephyr and would like to work on this issue. Can you please assign me it.
