### ISSUE TITLE
[Coverity CID: 183035] Null pointer dereferences in /tests/net/udp/src/main.c

### ISSUE THREAD

**Issue by Shilpashree3lc** [zephyrproject-rtos/zephyr#6697]
Static code scan issues seen in File: /tests/net/udp/src/main.c
 Category: Null pointer dereferences
 Function: setup_ipv6_udp_long
 Component: Tests
 CID: 183035
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by jukkar** [comment]
No actual issue here, the function cannot fail in this case.
