### ISSUE TITLE
posix: implement `mq_timedsend()`

### ISSUE THREAD

**Issue by ycsin** [zephyrproject-rtos/zephyr#66971]
This is part of the See [POSIX Roadmap for LTSv3](https://github.com/zephyrproject-rtos/zephyr/issues/51211) (RFC #51211).

`mq_timedsend()` is required as part of `_POSIX_TIMEOUTS` Option Group.

For more information, please refer to https://pubs.opengroup.org/onlinepubs/9699919799/functions/mq_timedsend.html

**Comment by awojasinski** [comment]
It is implemented https://github.com/zephyrproject-rtos/zephyr/blob/e78aacdf29f8d23c1d2a4f70e0925fb68236f238/lib/posix/mqueue.c#L254-L261

**Comment by cfriedt** [comment]
I think it's just not marked as implemented in the docs
