### ISSUE TITLE
[Coverity CID: 183032] Error handling issues in /tests/net/websocket/src/main.c

### ISSUE THREAD

**Issue by Shilpashree3lc** [zephyrproject-rtos/zephyr#6700]
Static code scan issues seen in File: /tests/net/websocket/src/main.c
 Category: Error handling issues
 Function: test_v4_init
 Component: Tests
 CID: 183032
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by jukkar** [comment]
No actual issue here, the function cannot fail in this case.
