### ISSUE TITLE
doc: CAN-FD support not in support matrix for STM32 Nucleo G0B1 or G474

### ISSUE THREAD

**Issue by WardBenjamin** [zephyrproject-rtos/zephyr#67087]
**Describe the bug**

The STM32G0B1 has two CAN-FD peripherals available. Zephyr already supports one since https://github.com/zephyrproject-rtos/zephyr/pull/54403. Here is the current permalink: https://github.com/zephyrproject-rtos/zephyr/blob/e67b12e63611291ac567bac4abfb9d43ecac0ce8/boards/arm/nucleo_g0b1re/nucleo_g0b1re.dts#L180 

Meanwhile, the "[supported features](https://docs.zephyrproject.org/latest/boards/arm/nucleo_g0b1re/doc/index.html#supported-features)" matrix on the Nucleo G0B1RE page does not list any CAN support. 

**Environment**

* Page: `boards/arm/nucleo_g0b1re/doc/index`
* Version: main
* SHA-1: 5d5249d85bb7bb779314693baa230195c0b070e0

**Comment by WardBenjamin** [comment]
Side note: what needs to happen for Zephyr to properly support the second CAN-FD peripheral on this chip? I saw some notes about shared IRQs being an issue here https://github.com/zephyrproject-rtos/zephyr/pull/34963 but it is unclear to me whether that's been resolved in the two years since.

**Comment by WardBenjamin** [comment]
It looks like this is also an issue on the [Nucleo G474 page](https://docs.zephyrproject.org/latest/boards/arm/nucleo_g474re/doc/index.html#supported-features): https://github.com/zephyrproject-rtos/zephyr/blob/e67b12e63611291ac567bac4abfb9d43ecac0ce8/boards/arm/nucleo_g474re/nucleo_g474re.dts#L207

**Comment by henrikbrixandersen** [comment]
Documentation additions: #67430
