### ISSUE TITLE
Question: Is LittlevGL supported in Zephyr? Or any plan?

### ISSUE THREAD

**Issue by hongshui3000** [zephyrproject-rtos/zephyr#6709]
LittlevGL is a free and open-source graphics library providing everything you need to create embedded GUI with easy-to-use graphical elements, beautiful visual effects and low memory footprint.
https://github.com/littlevgl/lvgl

**Comment by carlescufi** [comment]
Nice timing, see https://github.com/zephyrproject-rtos/zephyr/pull/6826

**Comment by vanwinkeljan** [comment]
Closing issue, #6826 got merged
