### ISSUE TITLE
Invalid procedure collision handling, leading to possible invalid local procedure initiation 

### ISSUE THREAD

**Issue by erbr-ot** [zephyrproject-rtos/zephyr#67144]
**Describe the bug**
Due to invalid handling in remote LLCP mechanism, it is allowed that a local instant based procedure is initiated even though a remotely initiated incompatible procedure is still incomplete. This will lead to improper collision handling and consequently unforeseen/unexpected PDUs in procedure handling.  

**To Reproduce**
Error was seen on target with overlapping CPRs, where a central (non Zephyr) initiated CPR overlapped with peripheral (Zephyr) CPR, noticing that the the peripheral initiated procedure was not properly held back, but was allowed to start.
  
**Expected behavior**
Local procedures should not start if incompatible with remote initiated.

Fixed by: https://github.com/zephyrproject-rtos/zephyr/pull/67141

**Comment by cvinayak** [comment]
Fixed by https://github.com/zephyrproject-rtos/zephyr/pull/67141
