### ISSUE TITLE
"dumb_http_server" getting stuck in "net_tcp : Cannot allocate a new TCP connection"

### ISSUE THREAD

**Issue by nikhilbhume-eaton** [zephyrproject-rtos/zephyr#67155]
### Discussed in https://github.com/zephyrproject-rtos/zephyr/discussions/67043

<div type='discussions-op-text'>

<sup>Originally posted by **nikhilbhume-eaton** December 28, 2023</sup>
Controller STM32
Zephyr main branch dated : 26-Dec-2023

I tried the intruder tool from burp suite sommunity edition [https://portswigger.net/burp/communitydownload] on "dump_http_server".
I wanted to test DOS and brute force attack on this server, just to check any crash happens on server or network layer. But once I start the attack immediately within some seconds, device stops responding, only ping works and gets below messages on serial console.
_net_tcp: Cannot allocate a new TCP connection
net_tcp: net_context_get(): -2_

I checked in wireshark, server only respond "RST, ACK" to any http request. Webpage is not loading at all.

Then I kept device as it is for overnight to check recovery [burp suite stopped and no request going to server].
But it is still not getting recovered. Means after many idle hours as well, device is not able to load webpage or accept any http request.

Issue is easily reproduceable.

**Please refer discussion first, there are latest updates and details about the issue.**
</div>

**Comment by carlescufi** [comment]
Fixed by https://github.com/zephyrproject-rtos/zephyr/pull/67067
