### ISSUE TITLE
tests: posix: pthread_attr_destroy() not consistently called after pthread_attr_init()

### ISSUE THREAD

**Issue by cfriedt** [zephyrproject-rtos/zephyr#67178]
**Describe the bug**

Pthread stacks should be managed by `pthread_attr_init()` and `pthread_attr_destroy()`.

Dynamic thread stacks (including pooled thread stacks) were not done in Zephyr this way due to... difficulties getting that accepted in the first place (it took years), but also due to the implementation of the POSIX API, testsuite, and so on.

The model is clear - either use a `NULL` `pthread_attr_t *` and the implementation will manage the stack for the caller, or call `pthread_attr_init()` **with a matching call** to `pthread_attr_destroy()`.

In many areas in the POSIX testsuite, calls to `pthread_attr_destroy()` were missing or an assertion would occur prior to `pthread_attr_destroy()` being called.

It would seem that the testsuite leaks memory and resources substantially due to this.

Please also mention any information which could help others to understand
the problem you're facing:
 - What target platform are you using? All
 - What have you tried to diagnose or workaround this issue? #67094 #67085
 - Is this a regression? No.
 
**To Reproduce**
1. Pull in #67223 (it's actually too late now, because that PR pulls in much of the cleanup from #67575)
2. Execute tests where there is a call to `pthread_attr_init()` but no matching call to `pthread_attr_destroy()`, or tests that assert before calling `pthread_attr_destroy()`
3. See error

**Expected behavior**
There should be no memory leaks

**Impact**
It's a showstopper for #51211 which is why I'm in such a hurry to fix it 😁 

**Logs and console output**
Would see things like
```shell
E: Unable to allocate thread stack
```

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: Zephyr SDK v0.16.4
 - Commit: c0bb064d4e

**Additional context**

This bug will likely be comprised of several partial fixes
- [x] https://github.com/zephyrproject-rtos/zephyr/pull/67094
- [x] https://github.com/zephyrproject-rtos/zephyr/pull/67575
- [ ] https://github.com/zephyrproject-rtos/zephyr/pull/67223

**Comment by cfriedt** [comment]
Intentionally did not select high priority here, even though it affects all platforms, since it's being actively worked on

**Comment by cfriedt** [comment]
> Intentionally did not select high priority here, even though it affects all platforms, since it's being actively worked on

Actually no, I'll mark this as high. Maybe people will stop accusing me of trying to fast-track things if I escalate priority when appropriate. It affects multiple platforms.

**Comment by cfriedt** [comment]
Not completely fixed yet...

**Comment by jobol** [comment]
If I understand correctly, the pthread_attr_t instance must live all long the thread extend.

So the following code is bad:

```C
int x_thread_create(
			x_thread_t *tid,
                        x_thread_cb entry,
			void *arg,
			int detached)
{
        int rc;
	pthread_attr_t attr;

	pthread_attr_init(&attr);
	if (detached)
		pthread_attr_setdetachstate(&attr, PTHREAD_CREATE_DETACHED);
	rc = pthread_create(tid, &attr, (void*(*)(void*))entry, arg) ? -errno : 0;
	pthread_attr_destroy(&attr);
       return rc;
}
```

I reached it because logs are telling `<err> os: tid 0x20001418 is in use!`
And IMHO it leads to memory leak because when the thread stops, k_thread_stack_free isn't called.

Can you confirm my analysis please?

**Comment by cfriedt** [comment]
@jobol - I'm not sure what the analysis is here or what the goal is for that matter.

This is also not really a great place to start a random discussion.

Have you considered asking your question(s) on Discord?

**Comment by jobol** [comment]
@cfriedt - hi thak you for your quick reply. I was searching for a bug related to what I was facing. This bug is very related to that issue and I wanted to have your feedback on that topic. No I didn't consider asking on discord because I'm not on discort but I can do it as well. Nevetheless you are probably the most involved man on that topic and your feedback on my question would be very appreciated.
