### ISSUE TITLE
sysbuild: prep-artifacts-for-testing does not support systebuild well

### ISSUE THREAD

**Issue by hakehuang** [zephyrproject-rtos/zephyr#67238]
**Describe the bug**
if run with below build command line, the build binary is removed from pacakge
```
scripts/twister --prep-artifacts-for-testing --package-artifacts test_twister_test_only.tar.gz -p nrf5340dk_nrf5340_cpuapp  -T samples/drivers/mbox/
```

Please also mention any information which could help others to understand
the problem you're facing:
 - What target platform are you using?
 - nrf5340dk_nrf5340_cpuapp  
 - What have you tried to diagnose or workaround this issue?
 - remove  --prep-artifacts-for-testing  works fine
 - Is this a regression? If yes, have you been able to "git bisect" it to a
   specific commit?
 - no

**To Reproduce**
```
scripts/twister --prep-artifacts-for-testing --package-artifacts test_twister_test_only.tar.gz -p nrf5340dk_nrf5340_cpuapp  -T samples/drivers/mbox/
```
**Expected behavior**
the binary with sysbuild staff can be kept

**Impact**
--prep-artifacts-for-testing 

**Environment (please complete the following information):**
 - OS: (e.g. Linux, MacOS, Windows)
 - Toolchain (e.g Zephyr SDK, ...)
 - Commit SHA or Version used: 312e000a5fd1a05fe8422300af5c4452e2a69e25

**Comment by szczys** [comment]
I can confirm that I'm seeing the same behavior. The result of this operation is an archive missing all binaries, as shown by this tree:

```
➜ tree -a twister-out/
twister-out/
├── nrf52840dk_nrf52840
│   └── sample.golioth.fw_update.sysbuild
│       ├── build.log
│       ├── build.ninja
│       ├── CMakeCache.txt
│       ├── CMakeFiles
│       │   └── rules.ninja
│       └── zephyr
│           └── .config
├── testplan.json
└── twister.json

```
