### ISSUE TITLE
LZ4 Example No longer builds for multiple boards

### ISSUE THREAD

**Issue by jasshapiro** [zephyrproject-rtos/zephyr#67288]
LZ4 example does not build in v3.5. Builds in v3.4

<< Please describe the issue here >>

Building on freshly built ubuntu 22.04 environment.
After cloning zephyrproject

<code>
git checkout v3.4.0
west update
mkdir tmp && cd tmp && west build -p -b adafruit_feather_stm32f405 ../samples/compression/lz4
</code>
results in a clean build

<code>
git checkout v3.5.0
west update
mkdir tmp && cd tmp && west build -p -b adafruit_feather_stm32f405 ../samples/compression/lz4
</code>
results in 

<code>
 Loading Zephyr default modules (Zephyr base).
-- Application: /home/carson/code/bsd/zephyr/samples/compression/lz4
-- CMake version: 3.22.1
-- Found Python3: /home/carson/code/bsd/.venv/bin/python3 (found suitable version "3.10.12", minimum required is "3.8") found components: Interpreter 
-- Cache files will be written to: /home/carson/.cache/zephyr
-- Zephyr version: 3.5.99 (/home/carson/code/bsd/zephyr)
-- Found west (found suitable version "1.2.0", minimum required is "0.14.0")
-- Board: adafruit_feather_stm32f405
-- ZEPHYR_TOOLCHAIN_VARIANT not set, trying to locate Zephyr SDK
-- Found host-tools: zephyr 0.16.4 (/home/carson/.local/opt/zephyr-sdk-0.16.4)
-- Found toolchain: zephyr 0.16.4 (/home/carson/.local/opt/zephyr-sdk-0.16.4)
-- Found Dtc: /home/carson/.local/opt/zephyr-sdk-0.16.4/sysroots/x86_64-pokysdk-linux/usr/bin/dtc (found suitable version "1.6.0", minimum required is "1.4.6") 
-- Found BOARD.dts: /home/carson/code/bsd/zephyr/boards/arm/adafruit_feather_stm32f405/adafruit_feather_stm32f405.dts
-- Generated zephyr.dts: /home/carson/code/bsd/zephyr/tmp/build/zephyr/zephyr.dts
-- Generated devicetree_generated.h: /home/carson/code/bsd/zephyr/tmp/build/zephyr/include/generated/devicetree_generated.h
-- Including generated dts.cmake file: /home/carson/code/bsd/zephyr/tmp/build/zephyr/dts.cmake

warning: LZ4 (defined at modules/lz4/Kconfig:7) was assigned the value 'y' but got the value 'n'.
Check these unsatisfied dependencies: 0 (=n). See
http://docs.zephyrproject.org/latest/kconfig.html#CONFIG_LZ4 and/or look up LZ4 in the
menuconfig/guiconfig interface. The Application Development Primer, Setting Configuration Values,
and Kconfig - Tips and Best Practices sections of the manual might be helpful too.

Parsing /home/carson/code/bsd/zephyr/Kconfig
Loaded configuration '/home/carson/code/bsd/zephyr/boards/arm/adafruit_feather_stm32f405/adafruit_feather_stm32f405_defconfig'
Merged configuration '/home/carson/code/bsd/zephyr/samples/compression/lz4/prj.conf'
Configuration saved to '/home/carson/code/bsd/zephyr/tmp/build/zephyr/.config'
Kconfig header saved to '/home/carson/code/bsd/zephyr/tmp/build/zephyr/include/generated/autoconf.h'
-- Found GnuLd: /home/carson/.local/opt/zephyr-sdk-0.16.4/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/../../../../arm-zephyr-eabi/bin/ld.bfd (found version "2.38") 
-- The C compiler identification is GNU 12.2.0
-- The CXX compiler identification is GNU 12.2.0
-- The ASM compiler identification is GNU
-- Found assembler: /home/carson/.local/opt/zephyr-sdk-0.16.4/arm-zephyr-eabi/bin/arm-zephyr-eabi-gcc
-- Using ccache: /usr/bin/ccache
-- Configuring done
-- Generating done
-- Build files have been written to: /home/carson/code/bsd/zephyr/tmp/build
-- west build: building application
[1/130] Preparing syscall dependency handling

[2/130] Generating include/generated/version.h
-- Zephyr version: 3.5.99 (/home/carson/code/bsd/zephyr), build: zephyr-v3.5.0-3686-g7382dbd13aca
[21/130] Building C object CMakeFiles/app.dir/src/main.c.obj
FAILED: CMakeFiles/app.dir/src/main.c.obj 
ccache /home/carson/.local/opt/zephyr-sdk-0.16.4/arm-zephyr-eabi/bin/arm-zephyr-eabi-gcc -DCORE_CM4 -DHSE_VALUE=12000000 -DKERNEL -DK_HEAP_MEM_POOL_SIZE=16384 -DPICOLIBC_LONG_LONG_PRINTF_SCANF -DSTM32F405xx -DUSE_FULL_LL_DRIVER -DUSE_HAL_DRIVER -D_FORTIFY_SOURCE=1 -D_POSIX_C_SOURCE=200809 -D__LINUX_ERRNO_EXTENSIONS__ -D__PROGRAM_START -D__ZEPHYR__=1 -I/home/carson/code/bsd/zephyr/include -I/home/carson/code/bsd/zephyr/tmp/build/zephyr/include/generated -I/home/carson/code/bsd/zephyr/soc/arm/st_stm32/stm32f4 -I/home/carson/code/bsd/zephyr/drivers -I/home/carson/code/bsd/zephyr/soc/arm/st_stm32/common -I/home/carson/code/bsd/modules/hal/cmsis/CMSIS/Core/Include -I/home/carson/code/bsd/zephyr/modules/cmsis/. -I/home/carson/code/bsd/modules/hal/stm32/stm32cube/stm32f4xx/soc -I/home/carson/code/bsd/modules/hal/stm32/stm32cube/stm32f4xx/drivers/include -I/home/carson/code/bsd/modules/hal/stm32/stm32cube/stm32f4xx/drivers/include/Legacy -I/home/carson/code/bsd/modules/hal/stm32/stm32cube/common_ll/include -isystem /home/carson/code/bsd/zephyr/lib/libc/common/include -fno-strict-aliasing -Os -imacros /home/carson/code/bsd/zephyr/tmp/build/zephyr/include/generated/autoconf.h -fno-printf-return-value -fno-common -g -gdwarf-4 -fdiagnostics-color=always -mcpu=cortex-m4 -mthumb -mabi=aapcs -mfp16-format=ieee -mtp=soft --sysroot=/home/carson/.local/opt/zephyr-sdk-0.16.4/arm-zephyr-eabi/arm-zephyr-eabi -imacros /home/carson/code/bsd/zephyr/include/zephyr/toolchain/zephyr_stdint.h -Wall -Wformat -Wformat-security -Wno-format-zero-length -Wno-pointer-sign -Wpointer-arith -Wexpansion-to-defined -Wno-unused-but-set-variable -Werror=implicit-int -fno-pic -fno-pie -fno-asynchronous-unwind-tables -ftls-model=local-exec -fno-reorder-functions --param=min-pagesize=0 -fno-defer-pop -fmacro-prefix-map=/home/carson/code/bsd/zephyr/samples/compression/lz4=CMAKE_SOURCE_DIR -fmacro-prefix-map=/home/carson/code/bsd/zephyr=ZEPHYR_BASE -fmacro-prefix-map=/home/carson/code/bsd=WEST_TOPDIR -ffunction-sections -fdata-sections --specs=picolibc.specs -std=c99 -MD -MT CMakeFiles/app.dir/src/main.c.obj -MF CMakeFiles/app.dir/src/main.c.obj.d -o CMakeFiles/app.dir/src/main.c.obj -c /home/carson/code/bsd/zephyr/samples/compression/lz4/src/main.c
/home/carson/code/bsd/zephyr/samples/compression/lz4/src/main.c:11:10: fatal error: lz4.h: No such file or directory
   11 | #include "lz4.h"
      |          ^~~~~~~
compilation terminated.
[26/130] Building C object zephyr/CMakeFiles/zephyr.dir/soc/arm/st_stm32/common/stm32cube_hal.c.obj
ninja: build stopped: subcommand failed.
FATAL ERROR: command exited with status 1: /usr/bin/cmake --build /home/carson/code/bsd/zephyr/tmp/build
</code>

same occurs for nrf52840dk_nrf52840

I'm migrating an application that uses lz4 from 3.1.99 up to current and have run into this as a roadblock. This is the minimal example. Thank you.

* Page: `samples/compression/lz4/README`
* Version: main
* SHA-1: 588e0a69dc3c3d907b299878ae558876d0839b9b

**Comment by nordicjm** [comment]
the `lz4` module is now optional, see https://docs.zephyrproject.org/latest/releases/migration-guide-3.5.html#optional-modules for details
