### ISSUE TITLE
LE Audio: Track Position Notification not send

### ISSUE THREAD

**Issue by piotrnarajowski** [zephyrproject-rtos/zephyr#67312]
**Describe the bug**
GMCS server IUT doesn't send notification for track position characteristic after Media Control Point is written to with Stop opcode. The initial media state is Playing/Paused/Seeking.

**To Reproduce**
Can be reproduced with AutoPTS

**Expected behavior**
According to [MCS Spec](https://www.bluetooth.com/specifications/mcs-1-0/): "If the Track Position characteristic supports notification, a server device shall notify this characteristic to
the client device based on the value of the Client Characteristic Configuration descriptor when the Track Position characteristic value is changed, when the track is paused, or when the playback speed is changed."

According to [MCS TS](https://www.bluetooth.org/docman/handlers/DownloadDoc.ashx?doc_id=514418): "If Track Position notification is supported, the IUT sends a GATT Characteristic Value Notification
for the Track Position characteristic"

Not sure if this applies for case where initial Media State is Paused...

**Impact**
GMCS/SR/MCP/BV-09-C
GMCS/SR/MCP/BV-10-C
GMCS/SR/MCP/BV-11-C
Verdict for these testcases is inconclusive.

**Logs and console output**
[GMCS Logs.zip](https://github.com/zephyrproject-rtos/zephyr/files/13860575/GMCS.Logs.zip)

**Environment (please complete the following information):**
 - OS: Windows 11
 - Toolchain: Zephyr SDK 0.16.4

**Comment by Thalley** [comment]
The issue here is that the track position is not incremented in the player, and then we stopping the track (which sets the track position to 0), then we are not notifying because of 

```c
	if (new_pos != old_pos) {
		/* Set new position and notify it */
		media_player.track_pos = new_pos;
		media_proxy_pl_track_position_cb(new_pos);
	}
```
