### ISSUE TITLE
drivers: flash: spi_nor: acquire/release_device calls are not consistently paired

### ISSUE THREAD

**Issue by ndrs-pst** [zephyrproject-rtos/zephyr#67336]
**Describe the bug**
There's a bug in the drivers: flash: spi_nor module where acquire/release_device calls are not paired correctly. This leads to improper resource management, especially evident when operations fail, potentially causing resource blocking issues in the SPI NOR driver.

https://github.com/zephyrproject-rtos/zephyr/blob/9c3ca4573a8ebddfc37fcadf2a770b128845b5bd/drivers/flash/spi_nor.c#L655-L664

https://github.com/zephyrproject-rtos/zephyr/blob/9c3ca4573a8ebddfc37fcadf2a770b128845b5bd/drivers/flash/spi_nor.c#L1226-L1235

https://github.com/zephyrproject-rtos/zephyr/blob/9c3ca4573a8ebddfc37fcadf2a770b128845b5bd/drivers/flash/spi_nor.c#L1273-L1289

**To Reproduce**
N/A

**Expected behavior**
`release_device(dev)` calls shall match pair with `acquire_device(dev);`

**Impact**
This is a showstopper issue.
The device could become locked due to the mismatched pairing of acquire/release_device calls.

**Logs and console output**
N/A

**Environment (please complete the following information):**
 - OS: Windows
 - Zephyr SDK: 0.16.4
 - Zephyr Version: 3.5.99

**Additional context**
This issue is related to the following pull request: https://github.com/zephyrproject-rtos/zephyr/pull/66907/

**Comment by de-nordic** [comment]
The issue will be closed when the PR with fix gets merged.
