### ISSUE TITLE
Could not able overwrite LOG_MODE as LOG_MODE_IMMEDIATE using kconfig choice choice.

### ISSUE THREAD

**Issue by Mruthyunjaya-M** [zephyrproject-rtos/zephyr#67378]
@ulfalizer  @carlescufi @nashif 

I am writing code to redirecting logs to ram console, So I used select LOG in my Kconfig to enable the Logging subsystem. And I am trying to select LOG_MODE as LOG_MODE_IMMEDIATE instead of LOG_MODE_DEFERRED.
Because of default log mode is LOG_MODE_DEFERRED zephyr/scripts/kconfig/kconfiglib.py is not overwriting LOG_MODE to LOG_MODE_IMMEDIATE.

In my Simple example also not worked. Below is my simple example.
choice MY_MODE
    prompt "Mode"
    default CHOICE_SYM_A

config CHOICE_SYM_A
        bool "A"
config CHOICE_SYM_B
        bool "B"
endchoice

choice MY_MODE
	default  @CHOICE_SYM_B
endchoice

**> **But it is working when we didn’t add any default value to choice
> choice MY_MODE
>     prompt "Mode"
> 
> config CHOICE_SYM_A
>         bool "A"
> config CHOICE_SYM_B
>         bool "B"
> endchoice
> 
> choice MY_MODE
> 	default CHOICE_SYM_B
> endchoice**
>**

**Comment by henrikbrixandersen** [comment]
Please use our bug template when reporting bugs. You need to edit this issue to include the information requested in https://github.com/zephyrproject-rtos/zephyr/blob/main/.github/ISSUE_TEMPLATE/001_bug_report.md
