### ISSUE TITLE
Sample example for zperf application is not working 

### ISSUE THREAD

**Issue by selvakumarm-eaton** [zephyrproject-rtos/zephyr#67420]
Test zperf sample application with nucleo_h743zi board.
Follow the steps specified this link:  https://github.com/zephyrproject-rtos/zephyr/issues/24770

Set IP Address in zephyrproject/zephyr/samples/net/zperf/prj.conf in my case:

CONFIG_NET_CONFIG_MY_IPV4="192.168.76.20"
CONFIG_NET_CONFIG_PEER_IPV4="192.168.76.11"

On the host (IP 192.168.76.11) run iperf:
iperf -s -p 5001 -B 192.168.76.11

No response on the Zephyr target.

**Comment by henrikbrixandersen** [comment]
Please use our bug template when reporting bugs. You need to edit this issue to include the information requested in https://github.com/zephyrproject-rtos/zephyr/blob/main/.github/ISSUE_TEMPLATE/001_bug_report.md

**Comment by jukkar** [comment]
You could also set the gateway address `CONFIG_NET_CONFIG_MY_IPV4_GW="192.168.76.xx"` just in case although as both the device and peer are in the same subnet, setting it should not matter.

**Comment by jukkar** [comment]
> iperf -s -p 5001 -B 192.168.76.11

You are running iperf in server mode, you need to initiate the test from zephyr side to continue.

**Comment by jukkar** [comment]
This looks like a configuration issue. @selvakumarm-eaton if you run Linux iperf in server mode (`-s` option), then you need to start the communication in zephyr side manually from zperf-shell using the `upload` command.
Closing this, reopen if needed.
