### ISSUE TITLE
GD32 timer don't work with GD32V

### ISSUE THREAD

**Issue by soburi** [zephyrproject-rtos/zephyr#67425]
This driver depends NVIC_SetPendingIRQ in ARM architecture,
but Nuclei's RISC-V core behave not same.

Several improvement strategies are possible.

1. Use CLIC's irq-pending function.

From what I've tried, RISC-V (Nuclei core) also has a pending function, but it doesn't seem to be the same as ARM.
I think it will be difficult to implement this way.

2. Implementation that does not depend on pending

I made this driver based on another SoC's driver, so I followed the idea of using irq-pending, but it may be possible to do it without doing that.
Irq-pending is used here to generate an interrupt triggered by software, but it may be possible to use a software event generation register instead.

**Comment by henrikbrixandersen** [comment]
@gmarull Was this fixed in #67147?

**Comment by gmarull** [comment]
No

**Comment by cameled** [comment]
refer https://people.eecs.berkeley.edu/~krste/papers/riscv-privileged-v1.9.1.pdf

3.1.13 Machine Interrupt Registers (mip and mie)

```
The UTIP, STIP and
HTIP bits may be written by M-mode software to deliver timer interrupts to lower privilege levels.
User, supervisor and hypervisor software may clear the UTIP, STIP and HTIP bits with calls to
the AEE, SEE, or HEE, respectively.
```
