### ISSUE TITLE
Default call to net_if_up() will always fail because device is not ready

### ISSUE THREAD

**Issue by AlessioLei94** [zephyrproject-rtos/zephyr#67448]
In my modem driver i define a network interface using `NET_DEVICE_INIT` macro.

After pulling from the main branch (on which i was already) i noticed that the interface associated with the net device is not up by default as it used to be, the call to `net_if_up()` is still done automatically but now it fails.

After some debugging i found that the issue is that inside `net_if_up()` there is a check on the fact that the device associated to the iface is ready (in subsys/net/ip/net_if.c at line 4486), this is always failing because the init function of the device (that sets the initialized flag to true) is called after `net_if_up()`.

I am not sure which change caused this behavior.

**Comment by jukkar** [comment]
It is probably this change d8ec9118b48232aecb285f31dea651f5847d32d2

**Comment by jukkar** [comment]
> this is always failing because the init function of the device (that sets the initialized flag to true) is called after `net_if_up()`.

The device should be initialized before calling `net_if_up()`

**Comment by AlessioLei94** [comment]
@jukkar yes, i agree that the commit you linked it's what caused this behavior.

**Comment by AlessioLei94** [comment]
@jukkar should this be fixed within Zephyr?

I am just trying to understand if i am doing something wrong and need to fix my driver. If that's the case i am not sure how to control when the device gets initialized as at the moment the calls are triggered automatically because of the `NET_DEVICE_INIT` macro.

**Comment by jukkar** [comment]
@AlessioLei94 do you have your driver somewhere it could be reviewed?

I do not quite understand what you mean by "calls are triggered automatically because of the NET_DEVICE_INIT macro". There should be no way that `net_if_up()` is called from action in network device init function.
The `net_if_up()` is called if network interface flag `NET_IF_NO_AUTO_START` is not set during the device booting. But at point the network device driver should be already set up properly in the system.

What network technology your driver is, Ethernet or something else?

**Comment by AlessioLei94** [comment]
@jukkar I mean that the device and the net_if are initialized and the net_if is enabled just by having the `NET_DEVICE_INIT` macro in my driver file to define the network interface that is part of the modem driver. As you also said the net_if is enabled because i do not set the `NET_IF_NO_AUTOSTART` flag.

I found the way to fix this behavior in the driver tho, i see that the net_if is initialized and then started at `POST_KERNEL` level with priority 80 (not set by me). While the priority passed to the `NET_DEVICE_INIT` is used to initialize the device associated to the net_if, again at `POST_KERNEL` level (this is not configurable). So just by giving a priority < 80 i get the same behavior as i did before, so the net_if is initialized and properly enabled.

It was just a bit tricky because i had to find out at what level the net_if was initialized.

**Comment by AlessioLei94** [comment]
@jukkar Sorry for the confusion, i managed to understand how it works now.

In my driver i define a modem device and a network interface that is controlled by the modem. I just need to make sure to have the network interface to have higher init priority (lower number) compared to the modem device and it will work properly.

**Comment by jukkar** [comment]
Great, I will close this one then.
