### ISSUE TITLE
power-domain-gpio **must** have configurable init priority

### ISSUE THREAD

**Issue by GrantRolls** [zephyrproject-rtos/zephyr#67467]
Current implementation of `power-domain-gpio` does not have a configurable init priority. It is hardcoded to 75.

This makes it incompatible with any device drivers that have a lower priority.

The init priority of `power-domain-gpio` should be configurable via Kconfig

![image](https://github.com/zephyrproject-rtos/zephyr/assets/18736760/69937002-59ce-419e-9e08-6de6fa255fd0)

**Comment by henrikbrixandersen** [comment]
@GrantRolls Could you submit a PR for fixing this?

**Comment by GrantRolls** [comment]
> @GrantRolls Could you submit a PR for fixing this?

Yes, I can try get around to this sometime in the next week

**Comment by ceolin** [comment]
I have created a pr adding option to change init priority in all available domains

**Comment by GrantRolls** [comment]
Thanks for that. 

Closing this regardless because I didn't realise it had already been resolved to some degree with the common config option. I'm running an older version.
