### ISSUE TITLE
intel_adsp: cavs25 tests/drivers/uart/uart_async_rx/drivers.uart.async_rx fails

### ISSUE THREAD

**Issue by majunkier** [zephyrproject-rtos/zephyr#67514]
**Describe the bug**
tests/drivers/uart/uart_async_rx/drivers.uart.async_rx fails on intel_adsp_cavs25

**To Reproduce**
twister -p intel_adsp_cavs25 --device-testing --hardware-map <path_to_cavs.map> -T tests/drivers/uart/uart_async_rx/ -v

**Expected behavior**
Test should pass.

**Logs and console output**
```
===================================================================
START - test_rx_ztress_no_chunks
Assertion failed at WEST_TOPDIR/os.rtos.zephyr.zephyr/tests/drivers/uart/uart_async_rx/src/main.c:214: consumer: (buf[j] not equal to test_data->exp_consume)
01 (exp:02) len:2, total:4
FAIL - test_rx_ztress_no_chunks in 0.023 seconds
===================================================================
```

**Environment (please complete the following information):**
 - OS: Ubuntu
 - Toolchain: Zephyr SDK 0.16.4
 - Zephyr version: zephyr-v3.5.0-4020-g0ee1e28a2f5f

**Comment by nashif** [comment]
fixed by #67640
