### ISSUE TITLE
doc: kconfig: links to "very" invisible symbols do not work

### ISSUE THREAD

**Issue by mimvdb** [zephyrproject-rtos/zephyr#67582]
**Describe the bug**
https://docs.zephyrproject.org/latest/kconfig.html#CONFIG_MAIN_THREAD_PRIORITY

CONFIG_MAIN_THREAD_PRIORITY refers to CONFIG_PREEMPT_ENABLED in the defaults, but this is a dead link.

**Environment**

* Page: `kconfig`
* Version: main
* SHA-1: fc942ef7d30dea3a5b4e0d9644cc9f586385ecf0

**Comment by kartben** [comment]
@gmarull Should we make it so that invisible symbols don't get rendered, or should we have "very" invisible symbols actually show up in docs (right now a symbol such as ``PREEMPT_ENABLED`` does not show up for it has neither help nor prompt)?

**Comment by gmarull** [comment]
what could be done is that such symbols do not get rendered as a link?
