### ISSUE TITLE
Add ajarmouni-st as project contributor

### ISSUE THREAD

**Issue by erwango** [zephyrproject-rtos/zephyr#67598]
# Background

The [TSC Project Roles] defines the main roles for the Zephyr Project, including
Maintainer, Collaborator, and Contributor.

By default anyone that contributes code or documentation is a Contributor, but
with the lowest [GitHub Permission Level] of Read. For example, Contributors
with Read permission do not have the permission to add reviewers to a pull
request.

Use this template to nominate a GitHub user for the Contributor role with
Triage permission level, which allows the user to add reviewers to a pull
request and be added as a reviewer by other users.

# Nomination

I'd like to nominate @ajarmouni-st as project contributor to be able to assign him issues and reviews

## GitHub User

Provide the following information about the GitHub user:

1. Full Name: Abderrahmane Jarmouni
1. GitHub username: @ajarmouni-st 
1. Organization (optional): STMicroelectonics

## Supporting Documents

https://github.com/zephyrproject-rtos/zephyr/pull/64932
https://github.com/zephyrproject-rtos/zephyr/pull/65467
https://github.com/zephyrproject-rtos/hal_stm32/pull/191

[TSC Project Roles]: <https://docs.zephyrproject.org/latest/project/project_roles.html>
[GitHub Permission Level]: <https://docs.github.com/en/organizations/managing-access-to-your-organizations-repositories/repository-roles-for-an-organization>

**Comment by nashif** [comment]
invite sent, see https://github.com/zephyrproject-rtos/zephyr/invitations
