### ISSUE TITLE
Tests: lib: gui: lvgl: test causes a Kernel Panic on stm32h747i_disco_m7

### ISSUE THREAD

**Issue by ajarmouni-st** [zephyrproject-rtos/zephyr#67685]
**Describe the bug**
Tests/lib/gui/lvgl test does not run on stm32h747i_disco_m7, & possibly other platforms as well, & causes a **kernel panic**. LittleFS appears to be the cause (as seen in the console output below).

 - target platform: tested on stm32h747i_disco_m7
 - Attempted workaround: update LittleFS to 2.8.1 using [PR 65414 ](https://github.com/zephyrproject-rtos/zephyr/pull/65414)
 - Still don't know if it's a regression

**To Reproduce**
1. cd ~/zephyrproject/zephyr
2. west build -p always -b stm32h747i_disco_m7 tests/lib/gui/lvgl -DSHIELD="st_b_lcd40_dsi1_mb1166"
4. west flash

**Expected behavior**
Random noise on the screen

**Impact**
Cannot run test

**Logs and console output**

```
I: Reading SFDP
I: qspi-nor-flash-1@0: SFDP v 1.6 AP ff with 2 PH
I: PH0: ff00 rev 1.6: 16 DW @ 30
I: Reading SFDP
I: qspi-nor-flash-1@0: 64 MiBy flash
I: Flash - address mode: 4B
I: Quad read mode 4 instr [0x6b] supported
I: Quad read mode 7 instr [0xeb] supported
I: Quad read mode 7 instr [0xeb] will be used
I: QE requirement mode: 0
I: Quad mode enabled
I: PH1: ff84 rev 1.0: 2 DW @ 80
*** Booting Zephyr OS build zephyr-v3.5.0-4181-g4204ca9bcb3f ***
Running TESTSUITE lvgl_fs
===================================================================
I: LittleFS version 2.5, disk version 2.0
I: FS at flash-controller@52002000:0xff800 is 0 0x20000-byte blocks with 512 cycle
I: sizes: rd 16 ; pr 16 ; ca 64 ; la 32
ASSERTION FAIL [block_count != 0] @ WEST_TOPDIR/zephyr/subsys/fs/littlefs_fs.c:813
E: r0/a1:  0x00000004  r1/a2:  0x0000032d  r2/a3:  0x40011000
E: r3/a4:  0x08037ec9 r12/ip:  0x00000000 r14/lr:  0x0800276f
E:  xpsr:  0x61000000
E: Faulting instruction address (r15/pc): 0x080270e4
E: >>> ZEPHYR FATAL ERROR 4: Kernel panic on CPU 0
E: Current thread: 0x24004670 (main)
E: Halting system
```

**Environment:**
 - OS: Linux
 - Toolchain: Zephyr SDK 0.16.3
 - Commit SHA: main branch, 4204ca9bcb3f675a0e63f647931ffe2c4b515729

**Additional context**
None for now

**Comment by de-nordic** [comment]
By:
```
I: FS at flash-controller@52002000:0xff800 is 0 0x20000-byte blocks with 512 cycle
```
it seems that there are 0 blocks of 128k. Is the partition properly configured?
