### ISSUE TITLE
Publish doxygen-generated API pages

### ISSUE THREAD

**Issue by dbkinder** [zephyrproject-rtos/zephyr#6773]
We use doxygen to process header files to collect public API information.  Today we use the XML output to feed into the Sphinx/Breathe processing to create the published [API documentation](http://docs.zephyrproject.org/api/api.html).  Doxygen also produces an HTML version of the API documentation that we generate but don't publish.  Some developers have asked for alternative ways of presenting the API docs and cross-references (e.g., #6739).  Publishing the doxygen-generated API material is another.  We should first though, do some customization of the doxygen output to make it more presentable and improve the user experience: Zephyr theme, intro on the doxygen index page, and such.

Also, consider cleaning up the doxygen-generated HTML presentation and completely replace the Sphinx/Breathe-generated API material with that (rather than having duplicated presentations of the same material.)

**Comment by dbkinder** [comment]
Doxygen-generated API docs are published at https://docs.zephyrproject.org/apidoc/latest/modules.html but could use some improvements on the mainpage...

**Comment by marc-hb** [comment]
Plus breathe is not actively developed right now, see for instance https://github.com/michaeljones/breathe/issues/420
