### ISSUE TITLE
doc: Documentation issue in 'samples/boards/arc_secure_services/README'

### ISSUE THREAD

**Issue by nordicjm** [zephyrproject-rtos/zephyr#67800]
**Describe the bug**
This whole page needs to be checked, there is no nsim_sem_normal board and the formatting is not done correctly.

**Environment**

* Page: `samples/boards/arc_secure_services/README`
* Version: main
* SHA-1: f483b1bc4cfe2381624fac6337cc74d3ce2bc850

**Comment by ruuddw** [comment]
The nsim_sem_normal board definition is in the samples/boards/arc_secure_services directory. It's not a real board, but a different configuration of the same board/SoC/CPU but in normal instead of secure mode (resulting in two binaries for the same physical board).

**Comment by nordicjm** [comment]
> Here,take :ref:’dining-philosophers-sample’ as an example for normal application.
> west build -b em_starterkit_em7d_normal nsim_sem_normal samples/philosophers

Then this cannot work?
