### ISSUE TITLE
Create PDF version of the project documentation

### ISSUE THREAD

**Issue by dbkinder** [zephyrproject-rtos/zephyr#6782]
Sphinx documentation generation can create LaTeX output that can then be used to create a PDF file, but we've not exercised that path in our documentation generation system.  Figure out the configuration tweaking and additional tools (e.g., ``pdflatex``) needed to make it so.

We also need the ability to create PDF versions for a subset of the documentation tree, e.g., Kernel documentation only.

**Comment by pfalcon** [comment]
@dbkinder: Are we ready to enable PDF generation/download for http://docs.zephyrproject.org/ yet? I could use some re-reading of the docs with a PDF on a plane, but ... bummer.

**Comment by nashif** [comment]
@pfalcon you can already create PDFs. You can also generate html and read it on the plane, unless you want to read things on some special device.

**Comment by nashif** [comment]
@dcpleung isnt this resolved already?

**Comment by nashif** [comment]
> In terms of having PDFs on the website, the CI needs to install some additional packages.

some... to get text up I had to install thousands :)

**Comment by carlescufi** [comment]
I will be pushing a PR soon with the ability to generate PDF on Windows.

**Comment by dbkinder** [comment]
We can generate PDFs (manually) now for the whole document tree, so closing this issue. Issue  #10324 tracks doing a PDF generation with a release.  No intention to add PDF generation with the daily build or CI check. The need for section PDF generation (much harder problem) will be looked into further.
