### ISSUE TITLE
Clean up wiki.zephyrproject.org content

### ISSUE THREAD

**Issue by dbkinder** [zephyrproject-rtos/zephyr#6783]
Some material in the project wiki was migrated to other locations but the old content remains.  Walk through the wiki pages and either update or remove.  Also, fix the manually maintained TOC on the right to include important pages not currently listed.

**Comment by nashif** [comment]
wiki.zephyrproject.org? We do not have this anymore!

**Comment by dbkinder** [comment]
https://wiki.zephyrproject.org still exists as a link to the GitHub wiki https://github.com/zephyrproject-rtos/zephyr/wiki

**Comment by nashif** [comment]
dont think we need to track this as an enhancement, this will evolve on its own.
