### ISSUE TITLE
scripts: pylib: twister: Environment variable description-implementation mismatch

### ISSUE THREAD

**Issue by LukaszMrugala** [zephyrproject-rtos/zephyr#67832]
When we take a look at the `--save-tests` Twister parameter, we can see that its description says that it "appends" tests to a given file:

https://github.com/zephyrproject-rtos/zephyr/blob/bea34c599d22468fb1851149d6f451880330ead0/scripts/pylib/twister/twisterlib/environment.py#L84-L89

However, when we cross-check it with the actual implementation, the file is just written (overwritten) to:

https://github.com/zephyrproject-rtos/zephyr/blob/bea34c599d22468fb1851149d6f451880330ead0/scripts/pylib/twister/twisterlib/reports.py#L357-L358

This mismatch makes the reader think that they can call Twister multiple times pointing to the same file with the  `--save-tests` flag and thus amass a collection of tests to execute, which is incorrect.

In my opinion, the word "Append" should be changed to "Write".

**Comment by nashif** [comment]
@LukaszMrugala  please submit a PR fixing that.
