### ISSUE TITLE
[Coverity CID: 183443] Memory - corruptions in /subsys/bluetooth/controller/ll_sw/ctrl.c

### ISSUE THREAD

**Issue by Shilpashree3lc** [zephyrproject-rtos/zephyr#6792]
Static code scan issues seen in File: /subsys/bluetooth/controller/ll_sw/ctrl.c
 Category: Memory - corruptions
 Function: radio_connect_enable
 Component: Bluetooth
 CID: 183443
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by carlescufi** [comment]
Intentional, commented on Coverity
