### ISSUE TITLE
[Coverity CID: 183442] Null pointer dereferences in /subsys/net/ip/icmpv6.c

### ISSUE THREAD

**Issue by Shilpashree3lc** [zephyrproject-rtos/zephyr#6793]
Static code scan issues seen in File: /subsys/net/ip/icmpv6.c
 Category: Null pointer dereferences
 Function: handle_echo_request
 Component: Networking
 CID: 183442
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by jukkar** [comment]
Already fixed by commit c288bf7aeb1
