### ISSUE TITLE
Host the source code of the J-Link Zephyr plugin in our org

### ISSUE THREAD

**Issue by carlescufi** [zephyrproject-rtos/zephyr#67936]
The source code for the plugin that ships with the Segger J-Link [software distribution](https://www.segger.com/downloads/jlink/#J-LinkSoftwareAndDocumentationPack), and that enables RTOS awareness for Zephyr, currently lives in a repo under the Nordic org.
Now that Segger has given us a copy of the required header files that can be freely distributable, we propose to host the repo in the Zephyr Project org.

This is the current repo: https://github.com/NordicSemiconductor/jlink-zephyr

To be discussed in the TSC.

**Comment by stephanosio** [comment]
Approved by TSC on 2024-01-24

**Comment by carlescufi** [comment]
Repo transferred:
https://github.com/zephyrproject-rtos/jlink-zephyr
