### ISSUE TITLE
[RFC] build: namespace generated headers with `zephyr/`

### ISSUE THREAD

**Issue by ycsin** [zephyrproject-rtos/zephyr#68035]
## Introduction

Two years ago there was a header migration in #45410 to namespace all the headers in the `include` directory to `include/zephyr`, however the build-time generated headers are (still) not namespaced, i.e.:

- `app_version.h`
- `cmake_intdef.h`
- `core-isa-dM.h`
- `devicetree_generated.h`
- `driver-validation.h`
- `kobj-types-enum.h`
- `linker-kobject-prebuilt-data.h`
- `mcuboot_version.h`
- `offsets.h`
- `otype-to-size.h`
- `otype-to-str.h`
- `strerror_table.h`
- `strsignal_table.h`
- `syscall_list.h`
- `version.h`
- `zsr.h`
- Kconfig headers (`autoconf.h`)
- and all the syscalls headers

Generated headers, especially `version.h`, can easily conflict with other libraries & user applications. This RFC is proposing to namespace the generated headers into the `zephyr/` directory as well.

### Problem description

Some of the generated headers have pretty generic names, i.e.: `version.h`, and can potentially conflict with other library / user applications. Ideally, all Zephyr's headers, in-tree or generated, should be namespaced with `zephyr/`.

### Proposed change

The generated headers previously in `build/zephyr/include/generated/` will now be placed in `build/zephyr/include/generated/zephyr/`, Zephyr sources that are including these headers will be updated accordingly, i.e.:

https://github.com/zephyrproject-rtos/zephyr/blob/114548ef607aefd712dda7e5ea954981e778185b/kernel/banner.c#L10

will be changed to 

```c
#include <zephyr/version.h>
```

## Detailed RFC

The task involves modifying CMake files and scripts to output generated headers in the `include/generated/zephyr/` directory, updating dependencies on these headers accordingly, changing include paths for in-tree sources, creating a compatibility Kconfig for uninterrupted user application builds, and updating migration and release notes with details on this change and its mitigation steps.

### Proposed change (Detailed)

- Modify CMake files and scripts to output headers to the `include/generated/zephyr/` directory
- Update CMake files and scripts to depend on headers in the `include/generated/zephyr/` directory
- Update in-tree sources' include paths to `zephyr/<header.h>`
- Create a compatibility Kconfig so that user applications will still continue to build
- Update the migration/release notes about the change, and steps to mitigate

### Dependencies

External libraries and user applications can be affected, in that case they may use the migration script.

   - [sof](https://github.com/thesofproject/sof)
     - https://github.com/thesofproject/sof/pull/8459
     - https://github.com/zephyrproject-rtos/sof/pull/34
   - [percepio](https://github.com/percepio/percepio)
     - https://github.com/percepio/percepio/pull/5
     - https://github.com/percepio/percepio/pull/6
     - https://github.com/zephyrproject-rtos/percepio/pull/10

### Concerns and Unresolved Questions

Can't think of any

## Alternatives

Rely on all external libaries & user applications to namespace their header so that no conflicts can occur.

**Comment by henrikbrixandersen** [comment]
Thanks! I'd very much like to see this happen.
