### ISSUE TITLE
doc: Documentation issue in 'kconfig'

### ISSUE THREAD

**Issue by PBA12695** [zephyrproject-rtos/zephyr#68075]
**Describe the bug**
CONFIG_BT_LONG_WQ_STACK_SIZE cannot be found in the documentation

**Environment**

* Page: `kconfig`
* Version: main
* SHA-1: fc942ef7d30dea3a5b4e0d9644cc9f586385ecf0

**Comment by kartben** [comment]
It's a hidden Kconfig so AFAICT this is intended behavior https://github.com/zephyrproject-rtos/zephyr/blob/main/subsys/bluetooth/host/Kconfig#L15-L16
@jori-nordic @nordicjm

**Comment by PBA12695** [comment]
Wouldn't it be good to document invisible symbols as well? In some circumstances, you need to modify them.

**Comment by kartben** [comment]
> Wouldn't it be good to document invisible symbols as well? In some circumstances, you need to modify them.

Probably very related to #67582
