### ISSUE TITLE
Bluetooth: host: add conn-recycled event

### ISSUE THREAD

**Issue by jori-nordic** [zephyrproject-rtos/zephyr#68114]
**Is your enhancement proposal related to a problem? Please describe.**

As a user of extended advertising, I would like to have advertising be resumed when possible.
We have a feature that does this, but it only works with advertising. side-effects may include: deadlocks.

> As a host developer, I don't want another bespoke `BT_LE_ADV_OPT`.

I can implement this myself by periodically trying to re-start advertising, but it hurts in the batteries.

**Describe the solution you'd like**

I would like to be notified when a connection slot becomes available, so I can try to re-start advertising.
An extension to `struct bt_conn_cb` that would look like this:
```c
struct bt_conn_cb {
	/** @brief A connection object has been returned to the pool.
	 *
	 *  This callback notifies the application that it might be able to
	 *  allocate a connection object. No guarantee, first come, first serve.
	 *
	 *  Use this to e.g. re-start connectable advertising or scanning.
	 */
	void (*recycled)(void);
```
<sub>...wait for it</sub>
```c
} // 😌
```

**Comment by ubieda** [comment]
@jori-nordic I can check out this issue!
