### ISSUE TITLE
RFC: Use MIMXRT1040-EVK as the Bluetooth BR/EDR development platform

### ISSUE THREAD

**Issue by lylezhu2012** [zephyrproject-rtos/zephyr#68154]
## Introduction

I recommend using MIMXRT1040-EVK as the BR/EDR development platform.

### Problem description

There is currently no platform that can run/test BR/EDR.

### Proposed change

N/A

## Detailed RFC

[MIMXRT1040-EVK](https://www.nxp.com/design/design-center/development-boards/i-mx-evaluation-and-development-boards/i-mx-rt1040-evaluation-kit:MIMXRT1040-EVK)  includes two parts, MIMXRT1040-EVK board and [Murata 1XK module](https://www.embeddedartists.com/products/1xk-m-2-module/).

Murata 1XK module is a dual mode Bluetooth 5.2 controller, BLE and BR/EDR could work at same time. 

MIMXRT1040-EVK has been supported in zephyr community. Murata 1XK module is not supported.

MIMXRT1040-EVK board and Murata 1XK module are purchased as a whole. Purchase link [here](https://www.nxp.com/part/MIMXRT1040-EVK#/). For a quantity of 1, the cost is $90.85.

### Proposed change (Detailed)

Murata 1XK module is a flashless board. The Firmware needs to be downloaded by MIMXRT1040-EVK board. Currently, firmware downloading is unsupported in community. Need to support it.

### Dependencies

Murata 1XK module need to be supported in zephyr community.

### Concerns and Unresolved Questions

N/A

## Alternatives

N/A

**Comment by dleach02** [comment]
@lylezhu2012, what format is the firmware for the Murata part? If it is a binary blob then there is a Zephyr process for supporting binary blobs that have to be considered:

https://docs.zephyrproject.org/latest/contribute/bin_blobs.html
