### ISSUE TITLE
Question: Is KProbes supported in Zephyr? Or any plan?

### ISSUE THREAD

**Issue by hongshui3000** [zephyrproject-rtos/zephyr#6816]
KProbes, dynamic instrumentation system inspired by Linux Kernel, allowing developers to gather additional information about kernel operation without recompiling or rebooting the kernel. It enables locations in the kernel to be instrumented with code, and the instrumentation code runs when the ARM core encounters that probe point. Once the instrumentation code completes execution, the kernel continues normal execution.
https://github.com/f9micro/f9-kernel

**Comment by nashif** [comment]
it is not supported. we have plans to add more tracepoints. right now this is covered with the kernel event logger, but coverage is minimal.
