### ISSUE TITLE
scripts: tests: Harness not working properly

### ISSUE THREAD

**Issue by pkunieck** [zephyrproject-rtos/zephyr#68172]
**Describe the bug**
Test pytest-twister-harness seems to not be working. After bisect this commit 3e234966dc46e41b1fa55a9a0e92589a6a9e7fdc is causing issues. 

**To Reproduce**
pytest ./scripts/pylib/pytest-twister-harness/tests

**Expected behavior**
Test pass

**Impact**
Affects CI

**Logs and console output**

FAILED scripts/pylib/pytest-twister-harness/tests/fixtures/mcumgr_fixture_test.py::test_if_mcumgr_fixture_parse_image_list - AssertionError: expected call not found.
Expected: mock('image test 1111')
Actual: mock('image test 0000')

more on https://github.com/zephyrproject-rtos/zephyr/actions/runs/7668713726/job/20901070478

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: zephyr-sdk-0.16.4
 - Commit 64423e269e

**Comment by LukaszMrugala** [comment]
Just fixing the test will not prevent future similar issues.

The base cause is the fact that tests acting on files outside twisterlib have been added to automatic tests, while not adding those files to the GitHub automatic PR checks.

At the very least `scripts/pylib/pytest-twister-harness/*` must be added to `on:` part of `tiwster_tests.yml`.
