### ISSUE TITLE
Question: Is supported for stack sharing among tasks  in Zephyr? Or any plan?

### ISSUE THREAD

**Issue by hongshui3000** [zephyrproject-rtos/zephyr#6817]
Support for stack sharing techniques, and one-shot task model to reduce the overall stack usage.

**Comment by ioannisg** [comment]
I don't know if an answer here is relevant any more.
However, Zephyr Kernel allocates one stack per thread (so no stack sharing). Interrupt stack is shared, however. No plans AFAIK
