### ISSUE TITLE
Missing st/l4/stm32l432k(b-c)ux-pinctrl.dtsi file while building Zephyr in nRF Connect

### ISSUE THREAD

**Issue by Masood-Salik** [zephyrproject-rtos/zephyr#68187]
I am currently trying to build Zephyr for the Nucleo L432KC board in nRF Connect, but I am encountering an error while building.

It appears that the build process is unable to locate the "st/l4/stm32l432k(b-c)ux-pinctrl.dtsi" file causing the build to fail. 

Can you please advise on how to resolve this issue and successfully build ?
Thank you in advance for your help.

https://github.com/zephyrproject-rtos/zephyr/blob/cf14d4f1fd6d3049e3417d82ab18a2c9aa43b370/boards/arm/nucleo_l432kc/nucleo_l432kc.dts#L9

Error:
` *  Executing task: nRF Connect: Build: practice_zephyr/build (active) 

Building practice_zephyr
west build --build-dir f:/practice_zephyr/build f:/practice_zephyr

-- west build: generating a build system
Loading Zephyr default modules (Zephyr base (cached)).
-- Application: F:/practice_zephyr
-- CMake version: 3.20.5
-- Cache files will be written to: F:/nrf_sdk/v2.5.1/zephyr/.cache
-- Zephyr version: 3.4.99 (F:/nrf_sdk/v2.5.1/zephyr)
-- Found west (found suitable version "1.1.0", minimum required is "0.14.0")
-- Board: nucleo_l432kc
-- Found host-tools: zephyr 0.16.1 (C:/ncs/toolchains/c57af46cb7/opt/zephyr-sdk)
-- Found toolchain: zephyr 0.16.1 (C:/ncs/toolchains/c57af46cb7/opt/zephyr-sdk)
-- Found BOARD.dts: F:/nrf_sdk/v2.5.1/zephyr/boards/arm/nucleo_l432kc/nucleo_l432kc.dts
In file included from <command-line>:
F:/nrf_sdk/v2.5.1/zephyr/boards/arm/nucleo_l432kc/nucleo_l432kc.dts:9:10: fatal error: st/l4/stm32l432k(b-c)ux-pinctrl.dtsi: No such file or directory
    9 | #include <st/l4/stm32l432k(b-c)ux-pinctrl.dtsi>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
CMake Error at F:/nrf_sdk/v2.5.1/zephyr/cmake/modules/extensions.cmake:3885 (message):
  failed to preprocess devicetree files (error code 1):
  F:/nrf_sdk/v2.5.1/zephyr/boards/arm/nucleo_l432kc/nucleo_l432kc.dts
Call Stack (most recent call first):
  F:/nrf_sdk/v2.5.1/zephyr/cmake/modules/dts.cmake:226 (zephyr_dt_preprocess)
  F:/nrf_sdk/v2.5.1/zephyr/cmake/modules/zephyr_default.cmake:129 (include)
  F:/nrf_sdk/v2.5.1/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:66 (include)
  F:/nrf_sdk/v2.5.1/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:97 (include_boilerplate)
  CMakeLists.txt:4 (find_package)

-- Configuring incomplete, errors occurred!
FATAL ERROR: command exited with status 1: 'C:\ncs\toolchains\c57af46cb7\opt\bin\cmake.EXE' -DWEST_PYTHON=C:/ncs/toolchains/c57af46cb7/opt/bin/python.exe '-Bf:\practice_zephyr\build' -GNinja '-Sf:\practice_zephyr'

 *  The terminal process terminated with exit code: 1. 
 *  Terminal will be reused by tasks, press any key to close it. `
 
 
 My configuration are
 `IMPORTANT: The data below could contain sensitive or confidential information about your environment.
If you do not wish this to be seen by others, please make sure to remove it before sharing.

For help and support, visit the Nordic DevZone at https://devzone.nordicsemi.com/.

{
  "platform": {
    "os": "win32",
    "osVersion": "Windows 10 Home Single Language",
    "osKernel": "10.0.22631",
    "vscode": "1.85.2",
    "electron": "25.9.7",
    "node": "v18.15.0"
  },
  "system": {
    "date": "2024-01-27T16:19:54.990Z",
    "vscodeRoot": "c:\\Users\\asus\\AppData\\Local\\Programs\\Microsoft VS Code\\resources\\app",
    "nrfConnectForDesktopInstalled": false,
    "vscodeUptime": "00:01:12",
    "osUptime": "03:56:29",
    "cpu": "AMD Ryzen 7 4800H with Radeon Graphics"
  },
  "workspace": {
    "name": "blinky",
    "workspaceFile": null,
    "folders": [
      "f:\\blinky"
    ]
  },
  "sdks": [
    {
      "version": "v2.5.1",
      "path": "f:\\nrf_sdk\\v2.5.1"
    }
  ],
  "activeBuild": "f:\\blinky\\build",
  "apps": [
    {
      "workspace": "f:\\blinky",
      "uri": "f:\\blinky",
      "buildConfigurations": [
        {
          "id": "f:\\blinky\\build",
          "name": "build",
          "boardId": "nucleo_l432kc",
          "type": "Zephyr",
          "isChild": false,
          "isStale": false,
          "taskBindings": {
            "build": [],
            "pristineBuild": [],
            "flash": [],
            "eraseAndFlash": []
          }
        }
      ]
    }
  ],
  "topdir": "f:\\nrf_sdk\\v2.5.1",
  "workspaceState": "freestanding-ready",
  "toolchains": [
    {
      "version": "2.5.1",
      "path": "c:\\ncs\\toolchains\\c57af46cb7"
    }
  ],
  "connectedDevices": [],
  "deviceProvider": "nrfutil",
  "tools": {
    "C:\\ncs\\toolchains\\c57af46cb7\\opt\\zephyr-sdk\\arm-zephyr-eabi\\bin\\arm-zephyr-eabi-gcc.exe": "0.16.1",
    "C:\\Program Files\\SEGGER\\JLink\\JLink.exe": "7.88j",
    "nrfjprog": "Not found",
    "nrfutil": "Not found",
    "C:\\ncs\\toolchains\\c57af46cb7\\opt\\bin\\cmake.exe": "3.20.5",
    "C:\\ncs\\toolchains\\c57af46cb7\\opt\\bin\\Scripts\\west.exe": "1.1.0",
    "C:\\ncs\\toolchains\\c57af46cb7\\opt\\bin\\python.exe": "3.8.2",
    "C:\\ncs\\toolchains\\c57af46cb7\\opt\\bin\\ninja.exe": "1.9.0",
    "C:\\ncs\\toolchains\\c57af46cb7\\opt\\bin\\gperf.exe": "3.1",
    "C:\\ncs\\toolchains\\c57af46cb7\\opt\\bin\\dtc.exe": "1.4.7",
    "C:\\ncs\\toolchains\\c57af46cb7\\opt\\bin\\gn.exe": "2122",
    "C:\\ncs\\toolchains\\c57af46cb7\\mingw64\\bin\\git.exe": "2.37.3.windows.1",
    "gdbPath": "c:\\ncs\\toolchains\\c57af46cb7\\opt\\zephyr-sdk\\arm-zephyr-eabi\\bin\\arm-zephyr-eabi-gdb.exe"
  },
  "nrfutil": {
    "nrfutil-device": {
      "version": "2.0.0",
      "binPath": "c:\\Users\\asus\\.vscode\\extensions\\nordic-semiconductor.nrf-connect-2023.11.301-win32-x64\\platform\\nrfutil\\bin\\nrfutil-device"
    },
    "nrfutil-toolchain-manager": {
      "version": "0.14.1",
      "binPath": "c:\\Users\\asus\\.vscode\\extensions\\nordic-semiconductor.nrf-connect-2023.11.301-win32-x64\\platform\\nrfutil\\bin\\nrfutil-toolchain-manager"
    }
  },
  "environment": {
    "westEnv": {
      "ELECTRON_RUN_AS_NODE": "1",
      "HOME": "C:\\Users\\asus",
      "HOMEDRIVE": "C:",
      "HOMEPATH": "\\Users\\asus",
      "PATH": "C:\\ncs\\toolchains\\c57af46cb7;C:\\ncs\\toolchains\\c57af46cb7\\mingw64\\bin;C:\\ncs\\toolchains\\c57af46cb7\\bin;C:\\ncs\\toolchains\\c57af46cb7\\opt\\bin;C:\\ncs\\toolchains\\c57af46cb7\\opt\\bin\\Scripts;C:\\ncs\\toolchains\\c57af46cb7\\opt\\nanopb\\generator-bin;C:\\ncs\\toolchains\\c57af46cb7\\opt\\zephyr-sdk\\aarch64-zephyr-elf\\bin;C:\\ncs\\toolchains\\c57af46cb7\\opt\\zephyr-sdk\\x86_64-zephyr-elf\\bin;C:\\ncs\\toolchains\\c57af46cb7\\opt\\zephyr-sdk\\arm-zephyr-eabi\\bin;c:\\Users\\asus\\.vscode\\extensions\\nordic-semiconductor.nrf-connect-2023.11.301-win32-x64\\platform\\nrfutil\\lib\\nrfutil-toolchain-manager;C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v12.1\\bin;C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v12.1\\libnvvp;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Windows\\System32\\OpenSSH\\;C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common;C:\\Program Files\\NVIDIA Corporation\\NVIDIA NvDLISR;C:\\Program Files\\MATLAB\\R2023a\\runtime\\win64;C:\\Program Files\\MATLAB\\R2023a\\bin;C:\\Program Files\\NVIDIA Corporation\\Nsight Compute 2023.1.0\\;C:\\Program Files\\Git\\cmd;C:\\Program Files\\dotnet\\;C:\\Program Files (x86)\\IVI Foundation\\VISA\\WinNT\\Bin\\;C:\\Program Files\\IVI Foundation\\VISA\\Win64\\Bin\\;C:\\Program Files (x86)\\IVI Foundation\\VISA\\WinNT\\Bin;C:\\ProgramData\\chocolatey\\bin;C:\\Program Files\\CMake\\bin;C:\\Users\\asus\\AppData\\Roaming\\OpenOCD\\bin;C:\\Users\\asus\\AppData\\Local\\Programs\\Microsoft VS Code\\bin",
      "ZEPHYR_BASE": "f:\\nrf_sdk\\v2.5.1\\zephyr",
      "ZEPHYR_TOOLCHAIN_VARIANT": "zephyr",
      "ZEPHYR_SDK_INSTALL_DIR": "C:\\ncs\\toolchains\\c57af46cb7\\opt\\zephyr-sdk",
      "PYTHONPATH": "C:\\ncs\\toolchains\\c57af46cb7\\opt\\bin;C:\\ncs\\toolchains\\c57af46cb7\\opt\\bin\\Lib;C:\\ncs\\toolchains\\c57af46cb7\\opt\\bin\\Lib\\site-packages"
    },
    "inherited": {
      "ELECTRON_RUN_AS_NODE": "1",
      "HOME": "C:\\Users\\asus",
      "HOMEDRIVE": "C:",
      "HOMEPATH": "\\Users\\asus",
      "Path": "C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v12.1\\bin;C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v12.1\\libnvvp;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Windows\\System32\\OpenSSH\\;C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common;C:\\Program Files\\NVIDIA Corporation\\NVIDIA NvDLISR;C:\\Program Files\\MATLAB\\R2023a\\runtime\\win64;C:\\Program Files\\MATLAB\\R2023a\\bin;C:\\Program Files\\NVIDIA Corporation\\Nsight Compute 2023.1.0\\;C:\\Program Files\\Git\\cmd;C:\\Program Files\\dotnet\\;C:\\Program Files (x86)\\IVI Foundation\\VISA\\WinNT\\Bin\\;C:\\Program Files\\IVI Foundation\\VISA\\Win64\\Bin\\;C:\\Program Files (x86)\\IVI Foundation\\VISA\\WinNT\\Bin;C:\\ProgramData\\chocolatey\\bin;C:\\Program Files\\CMake\\bin;C:\\Users\\asus\\AppData\\Roaming\\OpenOCD\\bin;C:\\Users\\asus\\AppData\\Local\\Programs\\Microsoft VS Code\\bin",
      "PATH": "C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v12.1\\bin;C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v12.1\\libnvvp;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Windows\\System32\\OpenSSH\\;C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common;C:\\Program Files\\NVIDIA Corporation\\NVIDIA NvDLISR;C:\\Program Files\\MATLAB\\R2023a\\runtime\\win64;C:\\Program Files\\MATLAB\\R2023a\\bin;C:\\Program Files\\NVIDIA Corporation\\Nsight Compute 2023.1.0\\;C:\\Program Files\\Git\\cmd;C:\\Program Files\\dotnet\\;C:\\Program Files (x86)\\IVI Foundation\\VISA\\WinNT\\Bin\\;C:\\Program Files\\IVI Foundation\\VISA\\Win64\\Bin\\;C:\\Program Files (x86)\\IVI Foundation\\VISA\\WinNT\\Bin;C:\\ProgramData\\chocolatey\\bin;C:\\Program Files\\CMake\\bin;C:\\Users\\asus\\AppData\\Roaming\\OpenOCD\\bin;C:\\Users\\asus\\AppData\\Local\\Programs\\Microsoft VS Code\\bin"
    },
    "toolchainPath": "c:\\ncs\\toolchains\\c57af46cb7",
    "toolchainBinPath": "c:\\ncs\\toolchains\\c57af46cb7\\opt\\zephyr-sdk\\arm-zephyr-eabi\\bin",
    "toolchainVersion": "2.5.1"
  },
  "terminal": {
    "defaultProfile": null
  },
  "config": {
    "nordic-semiconductor.nrf-connect": {
      "topdir": "",
      "toolchain": {
        "path": ""
      },
      "ozonePath": "",
      "applications": [],
      "applicationOptions": {},
      "kconfig": {
        "interface": "kconfig"
      },
      "west": {
        "env": {
          "$base": "terminal"
        }
      },
      "boardRoots": [],
      "taskBindings": {},
      "debugging": {
        "flash": true,
        "bindings": {},
        "justMyCode": true
      },
      "activeAppFollowActiveEditor": true,
      "deviceProvider": "",
      "flash": {
        "softreset": false,
        "erase": false,
        "recover": false
      },
      "enableTelemetry": true,
      "thirdpartyIntegration": {},
      "toolchainManager": {
        "indexURL": null,
        "installDirectory": null
      },
      "nrfutil": {
        "home": null
      },
      "defaultOpenAction": "ask"
    }
  },
  "extensions": {
    "internal": {
      "nordic-semiconductor.nrf-connect": {
        "version": "2023.11.301",
        "path": "c:\\Users\\asus\\.vscode\\extensions\\nordic-semiconductor.nrf-connect-2023.11.301-win32-x64",
        "isActive": true
      },
      "nordic-semiconductor.nrf-terminal": null,
      "nordic-semiconductor.nrf-devicetree": null,
      "nordic-semiconductor.nrf-kconfig": null
    },
    "external": {
      "marus25.cortex-debug": null,
      "ms-vscode.cpptools": null,
      "ms-vscode.js-debug": "1.85.0",
      "ms-vscode.js-debug-companion": "1.1.2",
      "ms-vscode.vscode-js-profile-table": "1.0.8"
    }
  }
}

`

**Comment by henrikbrixandersen** [comment]
You cannot use NCS for building for non-nRF devices. Please report this to Nordic Semiconductors, not Zephyr.
