### ISSUE TITLE
net: ipv6: nbr: Thread-safe implementation of ICMPv6 Neighbor Discovery

### ISSUE THREAD

**Issue by LuDuda** [zephyrproject-rtos/zephyr#68229]
**Describe the bug**
The implementation of ICMPv6 Neighbor Discovery in [`ipv6_nbr.c`](https://github.com/zephyrproject-rtos/zephyr/blob/main/subsys/net/ip/ipv6_nbr.c) file does not seem to be particularly Thread-safe.

Although I have not experienced any issue, by inspecting the code, there are multiple places when neighbor data or neighbor table, in general, is modified. For example from the `ipv6_nd_reachable_timeout` function, which is executed by a `workqueue`, also from public API like `net_ipv6_nbr_rm`, or by ICMPv6 handler like `handle_na_neighbor` via `handle_na_input`. I might be wrong, but I don't believe there is some synchronization mechanism in the upper layers to ensure mutually exclusive execution. The use of the semaphore in this file raises further doubts.

**Expected behavior**
The implementation of ICMPv6 Neighbor Discovery in Thread-safe. Maybe following `route.c` implementation and utilizing mutex lock.

**Additional context**
Issue spotted during the implementation of a new IPv6 ND API here: https://github.com/zephyrproject-rtos/zephyr/pull/68226

**Comment by jukkar** [comment]
Thanks for the analysis! And yes, it looks like the code could benefit from better locking. Would you be able to send a PR for it?
