### ISSUE TITLE
Logging with CONFIG_LOG_USE_TAGGED_ARGUMENTS=y failes when %% is used

### ISSUE THREAD

**Issue by nordic-krch** [zephyrproject-rtos/zephyr#68271]
**Describe the bug**
There is a segmentation fault on `native_sim` sample when logging with tagging is enabled and `%%` is used in a string.

**To Reproduce**
1. Enabling logging with tagging: `CONFIG_LOG_USE_TAGGED_ARGUMENTS=y` `CONFIG_LOG=y`
2. Add log like `LOG_INF("Hello World! %% %s\n",CONFIG_BOARD);`
3. Run on `native_sim` board and observe `Segmentation fault`
4. Remove `%%` from the string and run again to see that sample runs ok.

**Expected behavior**
There should be no `Segmentation fault`

**Impact**
Unexpected failures and a blocker for #68230 where it was noticed

**Environment (please complete the following information):**
 - Toolchain: Zephyr SDK 0.16.1
 - 0b8c4d5e65

**Comment by henrikbrixandersen** [comment]
CC: @aescolar
