### ISSUE TITLE
Add driver that support cf1133 touchscreen controller from Sitronix

### ISSUE THREAD

**Issue by clemdy** [zephyrproject-rtos/zephyr#68306]
Currently Zephyr proposes no driver to support Sitronix I2C touchscreen controller.

Adding an out of tree driver that support Sitronix I2C touchscreen controller.

**Comment by kartben** [comment]
Just to make sure I understand correctly, it looks likes you are intersted in contributing your driver (https://github.com/zephyrproject-rtos/zephyr/commit/14197b3075c237e1ff649989b4430a3d0805d45f), right?
Thanks in advance :)

**Comment by kartben** [comment]
> Hey yes exactly ! But i'm wondering if a pull request would be accepted right now or if i need to do more things

Of course it would be accepted! You could even have directly submitted the PR and not bothered with opening an issue, even if having the issue is nice for tracking that there's a need and WIP for this.
