### ISSUE TITLE
Update template docs with build example

### ISSUE THREAD

**Issue by dbkinder** [zephyrproject-rtos/zephyr#6831]
We've got a sphinx extension used to generate example build instructions.  Include use of the ``zephyr-app-commands`` extension in the sample templates found in the ``doc/templates`` folder, to help show how to use it (vs. using a ``code-block``)

**Comment by nashif** [comment]
@mbolivar I thought we had docs for the commands, can you please point us to where you have documented this?

**Comment by mbolivar** [comment]
@nashif it's in pydoc:

https://github.com/zephyrproject-rtos/zephyr/blob/master/doc/extensions/zephyr/application.py#L16

I'll move the content to something under doc/templates and provide examples for the main use cases.

**Comment by nashif** [comment]
@mbolivar thanks

**Comment by mbolivar** [comment]
Switched assignment to @dbkinder as discused in #7312
