### ISSUE TITLE
LE Audio: Broadcast Assistant API should not use `struct bt_bap_scan_delegator_subgroup`

### ISSUE THREAD

**Issue by Thalley** [zephyrproject-rtos/zephyr#68338]
**Describe the bug**
The `struct bt_bap_broadcast_assistant_add_src_param` and `struct bt_bap_broadcast_assistant_mod_src_param` use the `struct bt_bap_scan_delegator_subgroup` to provide subgroup information to the scan delegator. 

The issue is that the `struct bt_bap_scan_delegator_subgroup` depend on a Kconfig value that only exists for the Scan Delegator (guarded by `CONFIG_BT_BAP_SCAN_DELEGATOR`). 

**To Reproduce**
Build the sample from https://github.com/zephyrproject-rtos/zephyr/pull/68228 with `CONFIG_BT_BAP_SCAN_DELEGATOR=n`.

**Expected behavior**
The Broadcast Assistant API should be fully independent of the scan delegator. 
Either the struct needs to be redone to avoid a dependency on `CONFIG_BT_BAP_SCAN_DELEGATOR`, or the add/mod source parameters need their own way to describing subgroups. 

**Impact**
Annoyance as it requires enabling more features that should be necessary. 

**Logs and console output**
N/A

**Environment (please complete the following information):**
 - Commit SHA or Version used: 19700040afb78e165eb0b988c55472b5e1c0b717

**Additional context**
N/A

**Comment by pin-zephyr** [comment]
@Thalley I can fix this bug
