### ISSUE TITLE
npcx9m6f_evb: hanging while testing.

### ISSUE THREAD

**Issue by gbarkadiusz** [zephyrproject-rtos/zephyr#68453]
**Describe the bug**
This `pm.device_runtime.isr_safe.api` test is Passing but causes hanging the board. 
After this test the board is bricked that all other tests fail.

**To Reproduce**
```
<path/to>/scripts/twister --device-testing --hardware-map <path/to>/map.yml -T <path/to>tests/subsys/pm/device_runtime_api/ -v
```
**Logs and console output:**
`<path_to>/twister-out/tests/subsys/pm/device_runtime/handler.log`
```
***** delaying boot 500ms (per build configuration) *****
*** Booting Zephyr OS build zephyr-v3.5.0-5420-gc1a774baab7c (delayed boot 500ms) ***
Running TESTSUITE device_runtime_api
===================================================================
START - test_api
PASS - test_api in 0.001 seconds
===================================================================
START - test_pm_device_runtime_auto
PASS - test_pm_device_runtime_auto in 0.001 seconds
===================================================================
START - test_unsupported
PASS - test_unsupported in 0.001 seconds
===================================================================
TESTSUITE device_runtime_api succeeded
------ TESTSUITE SUMMARY START ------
SUITE PASS - 100.00% [device_runtime_api]: pass = 3, fail = 0, skip = 0, total = 3 duration = 0.003 seconds
- PASS - [device_runtime_api.test_api] duration = 0.001 seconds
- PASS - [device_runtime_api.test_pm_device_runtime_auto] duration = 0.001 seconds
- PASS - [device_runtime_api.test_unsupported] duration = 0.001 seconds
------ TESTSUITE SUMMARY END ------
===================================================================
RunID: 10fa24014630b8f8ec0a1ed0685a8b15
PROJECT EXECUTION SUCCESSFUL

```
**Environment:**
OS: Linux
Toolchain: zephyr-sdk-0.16.4
Commit SHA or Version used: zephyr-v3.5.0-5420-gc1a774baab7c

**Additional context:**
This bug is related to https://github.com/zephyrproject-rtos/zephyr/issues/55085 
The Commit added the new test case.
`pm.device_runtime.isr_safe.api:`https://github.com/zephyrproject-rtos/zephyr/commit/5ce4348311f7ee022ebeafbe5958df9d15793521

**Comment by majunkier** [comment]
same issue in intel_adsp_cavs25

**Comment by henrikbrixandersen** [comment]
Please use our bug template when reporting bugs. You need to edit this issue to include the information requested in https://github.com/zephyrproject-rtos/zephyr/blob/main/.github/ISSUE_TEMPLATE/001_bug_report.md
