### ISSUE TITLE
need console subsystem abstraction for console syscalls

### ISSUE THREAD

**Issue by andrewboie** [zephyrproject-rtos/zephyr#6846]
We currently have the printk/stdout/stdin hook registration mechanism which, among other things, doesn't have a good place to implement system calls.

We put something together specific to printk(), but we need to do this for various C library functions as well that emit to the console in both newlib and minimal libc.

A first attempt added syscalls to the C libraries (see #6815 ) but it would be MUCH better if there was a dedicated syscall layer independent of the C library, or specific device drivers. A subsystem like other drivers have, with perhaps some optimizations since we know it is a singleton.

This is both a bug and a feature since the underlying issue is that user threads calling printf(), or newlib read/write, crash.

**Comment by linkmeyer** [comment]
@andrewboie , what's the status?
