### ISSUE TITLE
Python 3.10.12 venv install failure in Ubuntu 22.04

### ISSUE THREAD

**Issue by rrozario1968** [zephyrproject-rtos/zephyr#68580]
![Python_venv_Install_failure](https://github.com/zephyrproject-rtos/zephyr/assets/110847153/66086fe1-2538-4c0f-8017-c15dbe1bbf81)

**Comment by JPHutchins** [comment]
Hi @rrozario1968, I believe that venv is already installed in all recent distributions of python.  Please proceed with the command to create a venv:
```
python3 -m venv .venv
```

Note here that I named the venv `.venv`.

If that is working for you then please close this ticket.

Cheers,
JP

**Comment by kartben** [comment]
What install instructions are you following? I would recommend you follow the getting started instructions to the letter, in this case it would have you install `python3-venv`, which I think should get you past the error your having by trying to force a specific version.

**Comment by henrikbrixandersen** [comment]
> What install instructions are you following? I would recommend you follow the getting started instructions to the letter, in this case it would have you install `python3-venv`, which I think should get you past the error your having by trying to force a specific version.

I can confirm that following the getting started instructions and using `sudo apt-get install python3-venv` succeeds on Ubuntu 22.04.

@rrozario1968 Please reopen this issue with further details if this does not work for you.

**Comment by rrozario1968** [comment]
Hi,
I tried it in different ways but it would not install venv. I tried to follow the guide word for word and it did not work.
Best Regards,
Robert

**Comment by kartben** [comment]
As mentioned, please share more details (and actual text, not screenshots, please) if you want help. It is virtually impossible to troubleshoot your problem if all we know is that "[you] tried it in different ways but it would not install". Thanks!
