### ISSUE TITLE
Dependency installation as shown in step2 does not work

### ISSUE THREAD

**Issue by rrozario1968** [zephyrproject-rtos/zephyr#68581]
![Dependency_install_step2_fail](https://github.com/zephyrproject-rtos/zephyr/assets/110847153/74c8538d-b8d0-4f30-a06b-351a6739417c)

**Comment by nordicjm** [comment]
For 2 in a row this seems more like you have a broken system/package manager

**Comment by henrikbrixandersen** [comment]
> For 2 in a row this seems more like you have a broken system/package manager

Context for the above: #68580

**Comment by henrikbrixandersen** [comment]
@rrozario1968 Hi! Looks like your system package manager (apt) is not in a good shape. Take a note of the error message `E: Unable to correct problems, you have held broken packages.` and search the Ubuntu help forums for tips on how to repair it.
