### ISSUE TITLE
Not able to join OpenThread BorderRouter or a ot-ftd-cli network

### ISSUE THREAD

**Issue by ekarlso** [zephyrproject-rtos/zephyr#6874]
Copied from Google groups:
Hmm, So I tried now using a NRF52840 as the joiner using the ot-ftd-cli firmware and using a Zephyr with joiner enabled.

The OT firmware works fine and there I get join success.

But with Zephyr I get a different EUI64 then on the ot-ftd-cli firmware as well as that it fails with NotFound:

So I enabled join using "wpanctl permit-join 7200" and "sudo wpanctl permit-join 7200", then I verify that the net is joinable
t> cmd scan[echo-client] [ERR] wait_reply: ␛[0;31mData packet not received␛[0m
[openthread] [INF] otPlatLog: -MAC-----: Dropping IPv6 UDP msg, len:213, chksum:5889, sec:yes, error:Drop, prio:low
[openthread] [INF] otPlatLog: -MAC-----: src: fdde:ad00:beef:0:0:0:0:1
[openthread] [INF] otPlatLog: -MAC-----: dst: fdde:ad00:beef:0:0:0:0:2

| J | Network Name     | Extended PAN     | PAN  | MAC Address      | Ch | dBm | LQI |
+---+------------------+------------------+------+------------------+----+-----+-----+
[openthread] [DBG] otPlatLog: -MAC-----: Request to start operation "ActiveScan"
[otPlat/radio] [DBG] otPlatRadioGetPromiscuous: PromiscuousMode=0
[openthread] [DBG] otPlatLog: -MAC-----: Starting operation "ActiveScan"
ot> [openthread] [INF] otPlatLog: -MAC-----: Sending Beacon Request
[otPlat/radio] [DBG] otPlatRadioGetPromiscuous: PromiscuousMode=0
[openthread] [INF] otPlatLog: -MAC-----: Sending Beacon Request
[otPlat/radio] [DBG] otPlatRadioGetPromiscuous: PromiscuousMode=0
[openthread] [INF] otPlatLog: -MAC-----: Sending Beacon Request
[otPlat/radio] [DBG] otPlatRadioGetPromiscuous: PromiscuousMode=0
[openthread] [INF] otPlatLog: -MAC-----: Sending Beacon Request
[otPlat/radio] [DBG] otPlatRadioGetPromiscuous: PromiscuousMode=0
[openthread] [INF] otPlatLog: -MAC-----: Sending Beacon Request
[openthread] [DBG] otPlatLog: -MAC-----: Received frame from short address 0xe1d4
[openthread] [INF] otPlatLog: -MAC-----: Frame rx failed, error:UnknownNeighbor, len:28, seqnum:131, type:Beacon, src:0xe1d4, dst:None, sec:no, ackreq:no
[otPlat/radio] [DBG] otPlatRadioGetPromiscuous: PromiscuousMode=0
[openthread] [INF] otPlatLog: -MAC-----: Sending Beacon Request
[openthread] [INF] otPlatLog: -MAC-----: Received Beacon, name:OpenThreadGuide, xpanid:dead1111dead2222, id:3 ver:2, joinable:yes, native:no
| 1 | OpenThreadGuide  | dead1111dead2222 | abcd | 52e7d3b0457aa2b6 | 13 | -39 |  54 |
[otPlat/radio] [DBG] otPlatRadioGetPromiscuous: PromiscuousMode=0
[openthread] [INF] otPlatLog: -MAC-----: Sending Beacon Request
[otPlat/radio] [DBG] otPlatRadioGetPromiscuous: PromiscuousMode=0
[openthread] [INF] otPlatLog: -MAC-----: Sending Beacon Request
[otPlat/radio] [DBG] otPlatRadioGetPromiscuous: PromiscuousMode=0
[openthread] [INF] otPlatLog: -MAC-----: Sending Beacon Request
[otPlat/radio] [DBG] otPlatRadioGetPromiscuous: PromiscuousMode=0
[openthread] [INF] otPlatLog: -MAC-----: Sending Beacon Request
[otPlat/radio] [DBG] otPlatRadioGetPromiscuous: PromiscuousMode=0
[openthread] [INF] otPlatLog: -MAC-----: Sending Beacon Request
[otPlat/radio] [DBG] otPlatRadioGetPromiscuous: PromiscuousMode=0
[openthread] [INF] otPlatLog: -MAC-----: Sending Beacon Request
[otPlat/radio] [DBG] otPlatRadioGetPromiscuous: PromiscuousMode=0
[openthread] [INF] otPlatLog: -MAC-----: Sending Beacon Request
[otPlat/radio] [DBG] otPlatRadioGetPromiscuous: PromiscuousMode=0
[openthread] [INF] otPlatLog: -MAC-----: Sending Beacon Request
[otPlat/radio] [DBG] otPlatRadioGetPromiscuous: PromiscuousMode=0
[openthread] [INF] otPlatLog: -MAC-----: Sending Beacon Request
[otPlat/radio] [DBG] otPlatRadioGetPromiscuous: PromiscuousMode=0
[openthread] [INF] otPlatLog: -MAC-----: Sending Beacon Request
Done
[openthread] [DBG] otPlatLog: -MAC-----: Finishing operation "ActiveScan"
[otPlat/radio] [DBG] otPlatRadioGetPromiscuous: PromiscuousMode=0
[openthread] [DBG] otPlatLog: -MAC-----: Idle mode: Radio sleeping

# Start a join
ot> cmd joiner start J01NME
[openthread] [INF] otPlatLog: -MLE-----: Send Discovery Request (ff02:0:0:0:0:0:0:2)
Done
ot> [net] [INF] ot_state_changed_handler: State changed! Flags: 0x0000800b Current role: 0
[openthread] [DBG] otPlatLog: -MAC-----: Request to start operation "TransmitData"
[otPlat/radio] [DBG] otPlatRadioGetPromiscuous: PromiscuousMode=0
[openthread] [DBG] otPlatLog: -MAC-----: Starting operation "TransmitData"
[openthread] [DBG] otPlatLog: ==============================[TX len=035]===============================
[openthread] [DBG] otPlatLog: | 41 D8 CD CD AB FF FF 03 | 1E E3 DB 64 AA 14 37 7F | AXMM+....c[d*.7.
[openthread] [DBG] otPlatLog: | 3B 02 F0 4D 4C 4D 4C CD | 38 FF 10 1A 04 80 02 28 | ;.pMLMLM8......(
[openthread] [DBG] otPlatLog: | 00 4B F4 .. .. .. .. .. | .. .. .. .. .. .. .. .. | .Kt.............
[openthread] [DBG] otPlatLog: ------------------------------------------------------------------------
[openthread] [DBG] otPlatLog: -MAC-----: Finishing operation "TransmitData"
[otPlat/radio] [DBG] otPlatRadioGetPromiscuous: PromiscuousMode=0
[openthread] [DBG] otPlatLog: -MAC-----: Idle mode: Radio sleeping
[echo-client] [ERR] wait_reply: ␛[0;31mData packet not received␛[0m
[openthread] [DBG] otPlatLog: -MAC-----: Request to start operation "TransmitData"
[otPlat/radio] [DBG] otPlatRadioGetPromiscuous: PromiscuousMode=0
[openthread] [DBG] otPlatLog: -MAC-----: Starting operation "TransmitData"
[openthread] [DBG] otPlatLog: ==============================[TX len=035]===============================
[openthread] [DBG] otPlatLog: | 41 D8 CE CD AB FF FF 03 | 1E E3 DB 64 AA 14 37 7F | AXNM+....c[d*.7.
[openthread] [DBG] otPlatLog: | 3B 02 F0 4D 4C 4D 4C CD | 38 FF 10 1A 04 80 02 28 | ;.pMLMLM8......(
[openthread] [DBG] otPlatLog: | 00 4B F4 .. .. .. .. .. | .. .. .. .. .. .. .. .. | .Kt.............
[openthread] [DBG] otPlatLog: ------------------------------------------------------------------------
[openthread] [DBG] otPlatLog: -MAC-----: Finishing operation "TransmitData"
[otPlat/radio] [DBG] otPlatRadioGetPromiscuous: PromiscuousMode=0
[openthread] [DBG] otPlatLog: -MAC-----: Idle mode: Radio sleeping
[openthread] [DBG] otPlatLog: -MAC-----: Request to start operation "TransmitData"
[otPlat/radio] [DBG] otPlatRadioGetPromiscuous: PromiscuousMode=0
[openthread] [DBG] otPlatLog: -MAC-----: Starting operation "TransmitData"
[openthread] [DBG] otPlatLog: ==============================[TX len=035]===============================
[openthread] [DBG] otPlatLog: | 41 D8 CF CD AB FF FF 03 | 1E E3 DB 64 AA 14 37 7F | AXOM+....c[d*.7.
[openthread] [DBG] otPlatLog: | 3B 02 F0 4D 4C 4D 4C CD | 38 FF 10 1A 04 80 02 28 | ;.pMLMLM8......(
[openthread] [DBG] otPlatLog: | 00 4B F4 .. .. .. .. .. | .. .. .. .. .. .. .. .. | .Kt.............
[openthread] [DBG] otPlatLog: ------------------------------------------------------------------------
[openthread] [DBG] otPlatLog: -MAC-----: Finishing operation "TransmitData"
[otPlat/radio] [DBG] otPlatRadioGetPromiscuous: PromiscuousMode=0
[openthread] [DBG] otPlatLog: -MAC-----: Idle mode: Radio sleeping
[openthread] [DBG] otPlatLog: -MAC-----: Request to start operation "TransmitData"
[otPlat/radio] [DBG] otPlatRadioGetPromiscuous: PromiscuousMode=0
[openthread] [DBG] otPlatLog: -MAC-----: Starting operation "TransmitData"
[openthread] [DBG] otPlatLog: ==============================[TX len=035]===============================
[openthread] [DBG] otPlatLog: | 41 D8 D0 CD AB FF FF 03 | 1E E3 DB 64 AA 14 37 7F | AXPM+....c[d*.7.
[openthread] [DBG] otPlatLog: | 3B 02 F0 4D 4C 4D 4C CD | 38 FF 10 1A 04 80 02 28 | ;.pMLMLM8......(
[openthread] [DBG] otPlatLog: | 00 4B F4 .. .. .. .. .. | .. .. .. .. .. .. .. .. | .Kt.............
[openthread] [DBG] otPlatLog: ------------------------------------------------------------------------
[openthread] [DBG] otPlatLog: -MAC-----: Finishing operation "TransmitData"
[otPlat/radio] [DBG] otPlatRadioGetPromiscuous: PromiscuousMode=0
[openthread] [DBG] otPlatLog: -MAC-----: Idle mode: Radio sleeping
[openthread] [DBG] otPlatLog: -MAC-----: Request to start operation "TransmitData"
[otPlat/radio] [DBG] otPlatRadioGetPromiscuous: PromiscuousMode=0
[openthread] [DBG] otPlatLog: -MAC-----: Starting operation "TransmitData"
[openthread] [DBG] otPlatLog: ==============================[TX len=035]===============================
[openthread] [DBG] otPlatLog: | 41 D8 D1 CD AB FF FF 03 | 1E E3 DB 64 AA 14 37 7F | AXQM+....c[d*.7.
[openthread] [DBG] otPlatLog: | 3B 02 F0 4D 4C 4D 4C CD | 38 FF 10 1A 04 80 02 28 | ;.pMLMLM8......(
[openthread] [DBG] otPlatLog: | 00 4B F4 .. .. .. .. .. | .. .. .. .. .. .. .. .. | .Kt.............
[openthread] [DBG] otPlatLog: ------------------------------------------------------------------------
[openthread] [DBG] otPlatLog: -MAC-----: Finishing operation "TransmitData"
[otPlat/radio] [DBG] otPlatRadioGetPromiscuous: PromiscuousMode=0
[openthread] [DBG] otPlatLog: -MAC-----: Idle mode: Radio sleeping
[openthread] [DBG] otPlatLog: -MAC-----: Request to start operation "TransmitData"
[otPlat/radio] [DBG] otPlatRadioGetPromiscuous: PromiscuousMode=0
[openthread] [DBG] otPlatLog: -MAC-----: Starting operation "TransmitData"
[openthread] [DBG] otPlatLog: ==============================[TX len=035]===============================
[openthread] [DBG] otPlatLog: | 41 D8 D2 CD AB FF FF 03 | 1E E3 DB 64 AA 14 37 7F | AXRM+....c[d*.7.
[openthread] [DBG] otPlatLog: | 3B 02 F0 4D 4C 4D 4C CD | 38 FF 10 1A 04 80 02 28 | ;.pMLMLM8......(
[openthread] [DBG] otPlatLog: | 00 4B F4 .. .. .. .. .. | .. .. .. .. .. .. .. .. | .Kt.............
[openthread] [DBG] otPlatLog: ------------------------------------------------------------------------
[openthread] [DBG] otPlatLog: -MAC-----: Finishing operation "TransmitData"
[otPlat/radio] [DBG] otPlatRadioGetPromiscuous: PromiscuousMode=0
[openthread] [DBG] otPlatLog: -MAC-----: Idle mode: Radio sleeping
[openthread] [DBG] otPlatLog: -MAC-----: Request to start operation "TransmitData"
[otPlat/radio] [DBG] otPlatRadioGetPromiscuous: PromiscuousMode=0
[openthread] [DBG] otPlatLog: -MAC-----: Starting operation "TransmitData"
[openthread] [DBG] otPlatLog: ==============================[TX len=035]===============================
[openthread] [DBG] otPlatLog: | 41 D8 D3 CD AB FF FF 03 | 1E E3 DB 64 AA 14 37 7F | AXSM+....c[d*.7.
[openthread] [DBG] otPlatLog: | 3B 02 F0 4D 4C 4D 4C CD | 38 FF 10 1A 04 80 02 28 | ;.pMLMLM8......(
[openthread] [DBG] otPlatLog: | 00 4B F4 .. .. .. .. .. | .. .. .. .. .. .. .. .. | .Kt.............
[openthread] [DBG] otPlatLog: ------------------------------------------------------------------------
[openthread] [DBG] otPlatLog: -MAC-----: Finishing operation "TransmitData"
[otPlat/radio] [DBG] otPlatRadioGetPromiscuous: PromiscuousMode=0
[openthread] [DBG] otPlatLog: -MAC-----: Idle mode: Radio sleeping
[openthread] [DBG] otPlatLog: -MAC-----: Request to start operation "TransmitData"
[otPlat/radio] [DBG] otPlatRadioGetPromiscuous: PromiscuousMode=0
[openthread] [DBG] otPlatLog: -MAC-----: Starting operation "TransmitData"
[openthread] [DBG] otPlatLog: ==============================[TX len=035]===============================
[openthread] [DBG] otPlatLog: | 41 D8 D4 CD AB FF FF 03 | 1E E3 DB 64 AA 14 37 7F | AXTM+....c[d*.7.
[openthread] [DBG] otPlatLog: | 3B 02 F0 4D 4C 4D 4C CD | 38 FF 10 1A 04 80 02 28 | ;.pMLMLM8......(
[openthread] [DBG] otPlatLog: | 00 4B F4 .. .. .. .. .. | .. .. .. .. .. .. .. .. | .Kt.............
[openthread] [DBG] otPlatLog: ------------------------------------------------------------------------
[openthread] [DBG] otPlatLog: -MAC-----: Finishing operation "TransmitData"
[otPlat/radio] [DBG] otPlatRadioGetPromiscuous: PromiscuousMode=0
[openthread] [DBG] otPlatLog: -MAC-----: Idle mode: Radio sleeping
[openthread] [DBG] otPlatLog: -MAC-----: Request to start operation "TransmitData"
[otPlat/radio] [DBG] otPlatRadioGetPromiscuous: PromiscuousMode=0
[openthread] [DBG] otPlatLog: -MAC-----: Starting operation "TransmitData"
[openthread] [DBG] otPlatLog: ==============================[TX len=035]===============================
[openthread] [DBG] otPlatLog: | 41 D8 D5 CD AB FF FF 03 | 1E E3 DB 64 AA 14 37 7F | AXUM+....c[d*.7.
[openthread] [DBG] otPlatLog: | 3B 02 F0 4D 4C 4D 4C CD | 38 FF 10 1A 04 80 02 28 | ;.pMLMLM8......(
[openthread] [DBG] otPlatLog: | 00 4B F4 .. .. .. .. .. | .. .. .. .. .. .. .. .. | .Kt.............
[openthread] [DBG] otPlatLog: ------------------------------------------------------------------------
[openthread] [DBG] otPlatLog: -MAC-----: Finishing operation "TransmitData"
[otPlat/radio] [DBG] otPlatRadioGetPromiscuous: PromiscuousMode=0
[openthread] [DBG] otPlatLog: -MAC-----: Idle mode: Radio sleeping
[openthread] [DBG] otPlatLog: -MAC-----: Request to start operation "TransmitData"
[otPlat/radio] [DBG] otPlatRadioGetPromiscuous: PromiscuousMode=0
[openthread] [DBG] otPlatLog: -MAC-----: Starting operation "TransmitData"
[openthread] [DBG] otPlatLog: ==============================[TX len=035]===============================
[openthread] [DBG] otPlatLog: | 41 D8 D6 CD AB FF FF 03 | 1E E3 DB 64 AA 14 37 7F | AXVM+....c[d*.7.
[openthread] [DBG] otPlatLog: | 3B 02 F0 4D 4C 4D 4C CD | 38 FF 10 1A 04 80 02 28 | ;.pMLMLM8......(
[openthread] [DBG] otPlatLog: | 00 4B F4 .. .. .. .. .. | .. .. .. .. .. .. .. .. | .Kt.............
[openthread] [DBG] otPlatLog: ------------------------------------------------------------------------
[openthread] [DBG] otPlatLog: -MAC-----: Finishing operation "TransmitData"
[otPlat/radio] [DBG] otPlatRadioGetPromiscuous: PromiscuousMode=0
[openthread] [DBG] otPlatLog: -MAC-----: Idle mode: Radio sleeping
[openthread] [DBG] otPlatLog: -MAC-----: Request to start operation "TransmitData"
[otPlat/radio] [DBG] otPlatRadioGetPromiscuous: PromiscuousMode=0
[openthread] [DBG] otPlatLog: -MAC-----: Starting operation "TransmitData"
[openthread] [DBG] otPlatLog: ==============================[TX len=035]===============================
[openthread] [DBG] otPlatLog: | 41 D8 D7 CD AB FF FF 03 | 1E E3 DB 64 AA 14 37 7F | AXWM+....c[d*.7.
[openthread] [DBG] otPlatLog: | 3B 02 F0 4D 4C 4D 4C CD | 38 FF 10 1A 04 80 02 28 | ;.pMLMLM8......(
[openthread] [DBG] otPlatLog: | 00 4B F4 .. .. .. .. .. | .. .. .. .. .. .. .. .. | .Kt.............
[openthread] [DBG] otPlatLog: ------------------------------------------------------------------------
[openthread] [DBG] otPlatLog: -MAC-----: Finishing operation "TransmitData"
[otPlat/radio] [DBG] otPlatRadioGetPromiscuous: PromiscuousMode=0
[openthread] [DBG] otPlatLog: -MAC-----: Idle mode: Radio sleeping
[openthread] [DBG] otPlatLog: -MAC-----: Request to start operation "TransmitData"
[otPlat/radio] [DBG] otPlatRadioGetPromiscuous: PromiscuousMode=0
[openthread] [DBG] otPlatLog: -MAC-----: Starting operation "TransmitData"
[openthread] [DBG] otPlatLog: ==============================[TX len=035]===============================
[openthread] [DBG] otPlatLog: | 41 D8 D8 CD AB FF FF 03 | 1E E3 DB 64 AA 14 37 7F | AXXM+....c[d*.7.
[openthread] [DBG] otPlatLog: | 3B 02 F0 4D 4C 4D 4C CD | 38 FF 10 1A 04 80 02 28 | ;.pMLMLM8......(
[openthread] [DBG] otPlatLog: | 00 4B F4 .. .. .. .. .. | .. .. .. .. .. .. .. .. | .Kt.............
[openthread] [DBG] otPlatLog: ------------------------------------------------------------------------
[openthread] [DBG] otPlatLog: -MAC-----: Finishing operation "TransmitData"
[otPlat/radio] [DBG] otPlatRadioGetPromiscuous: PromiscuousMode=0
[openthread] [DBG] otPlatLog: -MAC-----: Idle mode: Radio sleeping
[openthread] [DBG] otPlatLog: -MAC-----: Request to start operation "TransmitData"
[otPlat/radio] [DBG] otPlatRadioGetPromiscuous: PromiscuousMode=0
[openthread] [DBG] otPlatLog: -MAC-----: Starting operation "TransmitData"
[openthread] [DBG] otPlatLog: ==============================[TX len=035]===============================
[openthread] [DBG] otPlatLog: | 41 D8 D9 CD AB FF FF 03 | 1E E3 DB 64 AA 14 37 7F | AXYM+....c[d*.7.
[openthread] [DBG] otPlatLog: | 3B 02 F0 4D 4C 4D 4C CD | 38 FF 10 1A 04 80 02 28 | ;.pMLMLM8......(
[openthread] [DBG] otPlatLog: | 00 4B F4 .. .. .. .. .. | .. .. .. .. .. .. .. .. | .Kt.............
[openthread] [DBG] otPlatLog: ------------------------------------------------------------------------
[openthread] [DBG] otPlatLog: -MAC-----: Finishing operation "TransmitData"
[otPlat/radio] [DBG] otPlatRadioGetPromiscuous: PromiscuousMode=0
[openthread] [DBG] otPlatLog: -MAC-----: Idle mode: Radio sleeping
[openthread] [DBG] otPlatLog: -MAC-----: Request to start operation "TransmitData"
[otPlat/radio] [DBG] otPlatRadioGetPromiscuous: PromiscuousMode=0
[openthread] [DBG] otPlatLog: -MAC-----: Starting operation "TransmitData"
[openthread] [DBG] otPlatLog: ==============================[TX len=035]===============================
[openthread] [DBG] otPlatLog: | 41 D8 DA CD AB FF FF 03 | 1E E3 DB 64 AA 14 37 7F | AXZM+....c[d*.7.
[openthread] [DBG] otPlatLog: | 3B 02 F0 4D 4C 4D 4C CD | 38 FF 10 1A 04 80 02 28 | ;.pMLMLM8......(
[openthread] [DBG] otPlatLog: | 00 4B F4 .. .. .. .. .. | .. .. .. .. .. .. .. .. | .Kt.............
[openthread] [DBG] otPlatLog: ------------------------------------------------------------------------
[openthread] [DBG] otPlatLog: -MAC-----: Finishing operation "TransmitData"
[otPlat/radio] [DBG] otPlatRadioGetPromiscuous: PromiscuousMode=0
[openthread] [DBG] otPlatLog: -MAC-----: Idle mode: Radio sleeping
[openthread] [DBG] otPlatLog: -MAC-----: Request to start operation "TransmitData"
[otPlat/radio] [DBG] otPlatRadioGetPromiscuous: PromiscuousMode=0
[openthread] [DBG] otPlatLog: -MAC-----: Starting operation "TransmitData"
[openthread] [DBG] otPlatLog: ==============================[TX len=035]===============================
[openthread] [DBG] otPlatLog: | 41 D8 DB CD AB FF FF 03 | 1E E3 DB 64 AA 14 37 7F | AX[M+....c[d*.7.
[openthread] [DBG] otPlatLog: | 3B 02 F0 4D 4C 4D 4C CD | 38 FF 10 1A 04 80 02 28 | ;.pMLMLM8......(
[openthread] [DBG] otPlatLog: | 00 4B F4 .. .. .. .. .. | .. .. .. .. .. .. .. .. | .Kt.............
[openthread] [DBG] otPlatLog: ------------------------------------------------------------------------
[openthread] [DBG] otPlatLog: -MAC-----: Finishing operation "TransmitData"
[otPlat/radio] [DBG] otPlatRadioGetPromiscuous: PromiscuousMode=0
[openthread] [DBG] otPlatLog: -MAC-----: Idle mode: Radio sleeping
[openthread] [DBG] otPlatLog: -MAC-----: Request to start operation "TransmitData"
[otPlat/radio] [DBG] otPlatRadioGetPromiscuous: PromiscuousMode=0
[openthread] [DBG] otPlatLog: -MAC-----: Starting operation "TransmitData"
[openthread] [DBG] otPlatLog: ==============================[TX len=035]===============================
[openthread] [DBG] otPlatLog: | 41 D8 DC CD AB FF FF 03 | 1E E3 DB 64 AA 14 37 7F | AX\M+....c[d*.7.
[openthread] [DBG] otPlatLog: | 3B 02 F0 4D 4C 4D 4C CD | 38 FF 10 1A 04 80 02 28 | ;.pMLMLM8......(
[openthread] [DBG] otPlatLog: | 00 4B F4 .. .. .. .. .. | .. .. .. .. .. .. .. .. | .Kt.............
[openthread] [DBG] otPlatLog: ------------------------------------------------------------------------
[openthread] [DBG] otPlatLog: -MAC-----: Finishing operation "TransmitData"
[otPlat/radio] [DBG] otPlatRadioGetPromiscuous: PromiscuousMode=0
[openthread] [DBG] otPlatLog: -MAC-----: Idle mode: Radio sleeping
[otPlat/radio] [DBG] otPlatRadioGetPromiscuous: PromiscuousMode=0
[openthread] [DBG] otPlatLog: -MAC-----: Idle mode: Radio sleeping
[openthread] [DBG] otPlatLog: -MESH-CP-: No joinable networks remaining to try
Join failed [NotFound]

**Comment by ekarlso** [comment]
cc @KaSroka

**Comment by rlubos** [comment]
Hi,
I did some investigation on your issue and I've noticed that OT version that we are using is taken in the middle of some rework regarding Joiner ID and a bugfix it has introduced:

Rework -> https://github.com/openthread/openthread/pull/2311
Bugfix -> https://github.com/openthread/openthread/pull/2426

It seems that due to that bug, Joiner will reject a valid, joinable network, because steering data is calculated incorrectly. I guess that might be what you observe.

Any chance to verify the commit with a bugfix to see if it helps?

**Comment by ekarlso** [comment]
@rlubos of course I can test it! Do you have a bugfixed commit?

**Comment by rlubos** [comment]
@ekarlso So the specific OT commit with a bugfix is debf68dd09da9a8c08e3567e884e2dc81414bd77

Actually, while I was veryfing that this specifc commit compiles well with Zephyr, I've crated a branch, as some changes to the Zephyr port were required. I didn't check the Joiner functionality though as I don't have a valid BR setup on my desk now. You can check the branch here:
https://github.com/rlubos/zephyr/tree/bump-ot-version-to-commit-debf68dd09da9a8c08e3567e884e2dc81414bd77

**Comment by ekarlso** [comment]
Hi sadly towards the OTBR (Border Router) it didnt seem to work yet. WIll test tomorrow also.

**Comment by rlubos** [comment]
Hey, thanks for the reply.

So I did some further digging about this commissioning issue and have the following feedback. OT commit had to be bumped up even more to enable proper radio operation after `cmd thread stop` is called (I presume you use existing examples, which start Thread at initialization). Without this bugfix Discovery Response message wasn't even forwarded to the Thread stack from the radio (and it wasn't acknowledged). Here's the updated branch:
https://github.com/rlubos/zephyr/tree/bump-ot-version-to-commit-db4759cc

Another thing is, that as the examples in Zephyr are precomissioned, you have to revert the PanID parameter to the default value, otherwise Thread Discovery will be targeted to a specific PanID (that's one of the reasons it works out of the box with two Zephyr examples). You can set it with command `cmd panid 0xffff`.

Last thing, sadly a limitation of current OT port, is a fact that currently 802.15.4 channel during frame reception is hardcoded to the `CONFIG_OPENTHREAD_CHANNEL`.
https://github.com/zephyrproject-rtos/zephyr/blob/9968cda453ac7a91d513b6a50817c926c3fe5cc6/subsys/net/ip/l2/openthread/openthread.c#L203
 In result, Thread ignores actual information about disovered channel, and always uses hardcoded channel to join. Therefore, joining a network works only if the joinable network operates on `CONFIG_OPENTHREAD_CHANNEL`.

So to summarize, I was able to join an OpenThread BR network with success, using the branch I've provided, on the following conditions:
* OTBR network operated on channel 13,
* I've used `echo_server` example with joiner and commissioner options enabled (comissioner probably not needed, I've used the exampes as both commissioner and joiner at some point, hence I've enabled it),
* I've issued the following commands on the `echo_client`:
`cmd thread stop`
`cmd panid 0xffff`
`cmd eut64` <- to obtain EUI64 for commissioner
`cmd joiner start N0RD1C`.
* Of course joiner have to be registered at the commissiner before joining:
`wpanctl commissioner -a N0RD1C 746ad626ef112e00`

Unfortunately I won't be able to propose improvements to the OT port in a near future so any contribution would be appreciated.

**Comment by ekarlso** [comment]
Uhm, any idea on / from Nordic about this? We're wanting to use OpenThread and Zephyr so a working integration is fine.

**Comment by rlubos** [comment]
I've added a fix to my branch:
https://github.com/rlubos/zephyr/tree/bump-ot-version-to-commit-db4759cc

With this fix, channel in received frame is no longer hardcoded, but read from OT platform radio port (new function was provied for that). You can check this out, feedback would be appreciated.

**Comment by ekarlso** [comment]
Hi @rlubos this seems to have fixed this issue at least so that it works after setting the correct panid.

Is there a way to not having to reset the panid?

**Comment by Craigzyc** [comment]
How do you issue thread commands with the echo_client example?
