### ISSUE TITLE
samples/modules/thrift/hello loadCertificateFromBuffer() needs 0 termination

### ISSUE THREAD

**Issue by lucasvdp** [zephyrproject-rtos/zephyr#68755]
**Describe the bug**
`loadCertificateFromBuffer()` expects a buffer to be 0 terminated. The `*.pem.inc` do not end with a 0.
This means that the size of the pem file (gotten from `strlen()`) passed on to `tls_credential_add()` is random and too large.
In the tests this might be hidden by using `(const char *)&cert_pem[0]`?

**To Reproduce**
Look at the code, probably not noticeable, could give a compiler warning.

**Expected behavior**
The zephyr PEM decoder expects a pem file followed by a NULL byte.

**Impact**
Minimal, as long as the pem file has a correct ending and there is a 0 somewhere in memory.

**Logs and console output**

**Environment (please complete the following information):**
Don't know how to compile this sample, that is why I made an issue not a PR.

**Additional context**

**Comment by henrikbrixandersen** [comment]
Please use our bug template when reporting bugs. You need to edit this issue to include the information requested in https://github.com/zephyrproject-rtos/zephyr/blob/main/.github/ISSUE_TEMPLATE/001_bug_report.md

**Comment by cfriedt** [comment]
I have a quick fix for this on the way.

Thank you for reporting the issue @lucasvdp 👍
