### ISSUE TITLE
The newline character is not getting parsed correctly, hence gen_syscalls.py throws up the following exception `raise SyscallParseException("Malformed system call invocation")`

### ISSUE THREAD

**Issue by jilaypandya** [zephyrproject-rtos/zephyr#68799]
The newline character is not getting parsed correctly, hence gen_syscalls.py throws up the following exception `raise SyscallParseException("Malformed system call invocation")`

_Originally posted by @jilaypandya in https://github.com/zephyrproject-rtos/zephyr/pull/68774#discussion_r1484140422_

**Comment by nordicjm** [comment]
Put it on the same line? We do not add newline for parameters in functions

**Comment by nashif** [comment]
Please file a bug using the bug template and make sure you have a short and a consice title. This bug as it is now, is very difficult to comprehend.
