### ISSUE TITLE
[Coverity CID: 183487] Control flow issues in /subsys/net/ip/net_core.c

### ISSUE THREAD

**Issue by Shilpashree3lc** [zephyrproject-rtos/zephyr#6881]
Static code scan issues seen in File: /subsys/net/ip/net_core.c
 Category: Control flow issues
 Function: net_send_data
 Component: Networking
 CID: 183487
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by jukkar** [comment]
False positive
