### ISSUE TITLE
[Coverity CID: 183486] Null pointer dereferences in /tests/net/traffic_class/src/main.c

### ISSUE THREAD

**Issue by Shilpashree3lc** [zephyrproject-rtos/zephyr#6882]
Static code scan issues seen in File: /tests/net/traffic_class/src/main.c
 Category: Null pointer dereferences
 Function: address_setup
 Component: Tests
 CID: 183486
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by jukkar** [comment]
False positive
