### ISSUE TITLE
[Coverity CID: 183480] Null pointer dereferences in /tests/net/checksum_offload/src/main.c

### ISSUE THREAD

**Issue by Shilpashree3lc** [zephyrproject-rtos/zephyr#6887]
Static code scan issues seen in File: /tests/net/checksum_offload/src/main.c
 Category: Null pointer dereferences
 Function: recv_cb_offload_enabled
 Component: Tests
 CID: 183480
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by jukkar** [comment]
Already fixed by commit d76cc488a2a216f1d49776823aba1838305d8e5d
