### ISSUE TITLE
ADXL367 adxl367_fifo_setup incorrect param type

### ISSUE THREAD

**Issue by sidmodi-mw** [zephyrproject-rtos/zephyr#68879]
**Describe the bug**
The `sets_nb` param in the function `adxl367_fifo_setup` in the file `drivers/sensor/adxl367/adxl367.c` is of type `uint8_t` but it should be of type `uint16_t` given that the function `adxl367_set_fifo_sample_sets_nb` takes in this parameter and is declared as `uint16_t` for that function.

Please also mention any information which could help others to understand
the problem you're facing:
 - nRF52832
- Manually setting the sample count using an I2C command

**Expected behavior**
Calling the function `adxl367_fifo_setup` with `sets_nb` with a value greater than 255 should not trigger an overflow.

**Impact**
Annoyance

**Comment by MaureenHelm** [comment]
would you be able to send a PR to fix?
