### ISSUE TITLE
[Coverity CID: 183478] Error handling issues in /tests/net/ipv6/src/main.c

### ISSUE THREAD

**Issue by Shilpashree3lc** [zephyrproject-rtos/zephyr#6889]
Static code scan issues seen in File: /tests/net/ipv6/src/main.c
 Category: Error handling issues
 Function: test_init
 Component: Tests
 CID: 183478
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by jukkar** [comment]
Already fixed by commit f71e497d98f34c4c1ce2553367363a1b898f7da6
