### ISSUE TITLE
MS5837 driver ms5837_compensate_30 seems different with the data sheet

### ISSUE THREAD

**Issue by EthanAussie** [zephyrproject-rtos/zephyr#68908]
The current MS5837 driver seems to have some different paramters for 30BA compensation.

The current implementation based on data sheet from following page?
https://www.te.com/usa-en/product-CAT-BLPS0017.html
![compensation from data sheet](https://github.com/zephyrproject-rtos/zephyr/assets/50738558/8db681f3-87a6-43fa-b85c-4d00bd1f1691)
![maybe correct](https://github.com/zephyrproject-rtos/zephyr/assets/50738558/a18fe4ca-6871-4d78-9a9e-65d204e93754)

But if you go througth the data sheet and compare with the source code.
https://github.com/zephyrproject-rtos/zephyr/blob/main/drivers/sensor/ms5837/ms5837.c
The code are different with some parameters.

I attached the diagram from data sheet and my version of the 30BA compensation.
Please have a look and confirm whether there is any thing wrong.

**Comment by MaureenHelm** [comment]
Would you be able to send a pull request to fix?

**Comment by EthanAussie** [comment]
> Would you be able to send a pull request to fix?

Will have a look for how to do it.

**Comment by EthanAussie** [comment]
Created a pull request.
https://github.com/zephyrproject-rtos/zephyr/pull/69069
