### ISSUE TITLE
issues filed by scripts have newlines in the title...

### ISSUE THREAD

**Issue by nashif** [zephyrproject-rtos/zephyr#69027]
issues filed by some scripts have newlines int the title, skewing output when listing issues in other scripts and tools

listing all open bugs for example right now results in:

```
58929: [STM32F103] first I2C transaction always fails when PM_DEVICE_RUNTIME is enabled - low
58888:
    tests-ci : drivers: uart: async_api.lpuart test Failed
     - low
58684: [Coverity CID: 316016] Use of 32-bit time_t in lib/os/timeutil.c - medium
```

Those issues reported with tests-ci need to be fixed.

Also: `tests-ci` is a misleading prefix to add to issues and seems vendor specific, please do not use prefix that do not mean anything to other people that can  be confusing, i.e. what ci? zephyr ci? is the issue in CI or the tests etc...?

**Comment by nashif** [comment]
@dleach02  FYI

**Comment by hakehuang** [comment]
I will fixed my sripts
