### ISSUE TITLE
hwmv2: Board documentation that references files that do not exist

### ISSUE THREAD

**Issue by nordicjm** [zephyrproject-rtos/zephyr#69065]
A list of files that have been updated to boards v2 in the collab-hwm branch which reference files (using `:zephyr_file:` or \`\`boards/...\`\`) which do not exist, as of commit f2d4787fe1773be7d4ef0b6ffa0540553aa0da83:

 - boards/arduino/arduino_opta/doc/index.rst
   * [ ] boards/arduino/arduino_opta/arduino_opta_m4_defconfig

 - boards/st/nucleo_l011k4/doc/index.rst
   * [ ] oards/st/nucleo_l011k4/nucleo_l011k4_defconfig

 - boards/st/nucleo_u575zi_q/doc/index.rst
   * [ ] boards/st/boards/st/nucleo_u575zi_q/nucleo_u575zi_q_defconfig

 - boards/st/nucleo_wba52cg/doc/nucleo_wba52cg.rst
   * [ ] boards/arm/nucleo_wba52cg/board.cmake
   * [ ] boards/arm/nucleo_wba52cg/nucleo_wba52cg_defconfig

 - boards/st/nucleo_wba55cg/doc/nucleo_wba55cg.rst
   * [ ] boards/arm/nucleo_wba55cg/board.cmake
   * [ ] boards/arm/nucleo_wba55cg/nucleo_wba55cg_defconfig

 - boards/st/nucleo_f207zg/doc/index.rst
   * [ ] boards/arm/nucleo_f207zg/nucleo_f207zg_defconfig

 - boards/fanke/fk7b0m1_vbt6/doc/index.rst
   * [ ] boards/arm/fk7b0m1-vbt6/fk7b0m1_vbt6_defconfig

Generation note:

Using https://pastebin.com/XHbGKL9z
```
cd <zephyr>
grep -r "zephyr_file" boards/ > /tmp/file_list
grep -r "\`\`boards" boards/ >> /tmp/file_list
php check.php /tmp/file_list > /tmp/file_list_output
```

**Comment by nordicjm** [comment]
@erwango @fabiobaltieri @nordicjm please check above and submit fix PRs

**Comment by nordicjm** [comment]
@golowanow

**Comment by golowanow** [comment]
@nordicjm no docs with broken references yet in my scope

**Comment by golowanow** [comment]
> > @nordicjm no docs with broken references yet in my scope
> 
> Right you are, I ported nios2

wait i see there is this one:
https://github.com/zephyrproject-rtos/zephyr/actions/runs/7928256606/job/21646167791?pr=68178
```
/runner/_work/zephyr/zephyr/doc/_build/src/boards/boards_legacy/x86/index.rst:6: WARNING: toctree glob pattern '[!common]*/**/*' didn't match any documents
```

**Comment by fabiobaltieri** [comment]
hey I'll just send another followup and do them all, no sense sending 1000 PRs for this

**Comment by fabiobaltieri** [comment]
https://github.com/zephyrproject-rtos/zephyr/pull/69074

**Comment by golowanow** [comment]
#69075

**Comment by nordicjm** [comment]
@erwango updated list above

**Comment by erwango** [comment]
> @erwango updated list above

Thanks. Will fix

**Comment by erwango** [comment]
@nordicjm https://github.com/zephyrproject-rtos/zephyr/pull/69205
