### ISSUE TITLE
Rename overlay and conf files in Zephyr modules required for HWv2

### ISSUE THREAD

**Issue by mmahadevan108** [zephyrproject-rtos/zephyr#69087]
**Describe the bug**
Some of the `overlay` and `conf` files in Zephyr modules will need to be renamed to match the requirement of HWv2

**Comment by henrikbrixandersen** [comment]
This hardly qualifies as a bug?

**Comment by mmahadevan108** [comment]
This will break the build once HWv2 gets merged. So maybe we can change this to an enhancement?

**Comment by dleach02** [comment]
@mmahadevan108, is this still an open issue?
