### ISSUE TITLE
nxp_rt1170: Flash driver does not work 

### ISSUE THREAD

**Issue by nguyenmthien-gin** [zephyrproject-rtos/zephyr#69088]
**Describe the bug**
The flash driver no longer working with the NXP iMXRT1170 development board. All firmwares built with `CONFIG_FLASH=y` cannot boot pass the `POST_KERNEL` system init stage.

We are able to confirm this is found from [this commit](https://github.com/zephyrproject-rtos/zephyr/commit/f81113e94811e2e7381f9a6c78dc5f0e29bc6bd7) onwards.

**To Reproduce**
Here we use `mimxrt1170_evk_cm7` with the Flash Shell example, but please notice this behavior is seen across the board with all kind of applications:
1. `cd zephyr`
1. `west build --pristine always --board mimxrt1170_evk_cm7 samples/drivers/flash_shell`
1. `west flash`
1. monitor the UART console 

**Expected behavior**
There should be the Zephyr boot message printed to the console, followed by the shell prompt.

In this case, nothing is printed to the console.

**Impact**
We are unable to confirm if this happens to other boards in the series or not.

**Comment by nguyenmthien-gin** [comment]
@danieldegrasse Do you have any thoughts on this?

**Comment by danieldegrasse** [comment]
Updating the title, please let me know if this is incorrect. I'll see if I can reproduce the issue on my hardware. I assume you are using the RT1170 EVK revision A?

**Comment by danieldegrasse** [comment]
Confirmed I can reproduce this issue on `2f8c58120e`

**Comment by danieldegrasse** [comment]
@nguyenmthien-gin can you test #69102 to verify it fixes the issue on your board? For me, this fixes the issue on `2f8c58120e`. It looks like the clock frequency for the flash was being set higher than desired, leading to the crash.

**Comment by nguyenmthien-gin** [comment]
> @nguyenmthien-gin can you test #69102 to verify it fixes the issue on your board? For me, this fixes the issue on `2f8c58120e`. It looks like the clock frequency for the flash was being set higher than desired, leading to the crash.

We verify that this PR fixes our boards. Thank you all for your blazing fast PR and the merging process :smile:
