### ISSUE TITLE
System freezing in case of k_sleep() usage

### ISSUE THREAD

**Issue by yuri-tikhonov-hiqo** [zephyrproject-rtos/zephyr#69184]
**Describe the bug**

*Application*: commercial project.

*Short Description of the Application*: accumulation of the BLE advertising data and sending it to another chip by UART (for interconnection between chips, we use nRF RPC with a custom transport layer). The system is protected from freezing by `task_wdt`.

*System behaviour*
1) After some period of time (it depends; it might be just an hour or even a few days), the system is partially frozen when calling `k_msleep()`.
2) The standard `task_wdt` feature does not reboot the MCU in this case.

**To Reproduce**
Unknown. The issue may appear in just an hour of uptime or a few days of uptime.

**Expected behavior**
The threads and threads watchdog shouldn't freeze permanently in case of `k_sleep()` usage.

**Impact**
Showstopper. The system is permanently stuck (a manual reboot is needed).

**Environment**
 - MCU: nRF52840
 - Toolchain: nRF Connect SDK 2.3.0 / 2.5.2 (the same behavior on both versions)

**Additional Notes**

- Threads that use `k_msleep()` totally freeze (we see it because it has a light indication).
- `task_wdt` doesn't reboot the system (it's strange because we have a task watchdog for each user-defined thread).
- Threads that use, for example, `k_sem_take()` work correctly because they are given after some period of time by `k_sem_give()`.
- UART communication works fine (we use the UART async API).
- Via UART, we transmit a timestamp, which is gotten by `k_uptime_get()`, and the timestamp is changing (so at least the RTC1 is counting).
- Also, we have one thread that calls `sys_reboot()` in the case of the specific UART command, but before it, it's waiting 1 second using `k_msleep()`. So this thread is also getting stuck if another thread is already stuck as described above (we send the command via UART, but the system doesn't reboot).

**Comment by henrikbrixandersen** [comment]
> - MCU: nRF52840
>  - Toolchain: nRF Connect SDK 2.3.0 / 2.5.2 (the same behavior on both versions)

Thank you for reporting this. However - unless you are able to reproduce this issue with upstream Zephyr `main` - please report issues with the nRF Connect SDK (NCS) on the [Nordic Semiconductor DevZone](https://devzone.nordicsemi.com/).
