### ISSUE TITLE
STM32 Mailbox API communication issues 

### ISSUE THREAD

**Issue by RIPHeisenberg** [zephyrproject-rtos/zephyr#69219]
Information:

    Board: STM32H747i_DISCOVERY
    Zephyr version: 3.5.99
    Zephyr SDK version: 0.16.5
    Commit: https://github.com/zephyrproject-rtos/zephyr/commit/023d4838fbb8513f9d9ff6f26b065591131c347d

Hi everyone,

I've recently begun developing a CAN to OPC-UA modeler on the STM32H747i-Discovery Board. The idea is to utilize the M4 chip for CAN communication and the M7 for OPC-UA. The pre-defined device tree bindings support the mailbox feature for IPM (Inter-Processor Communication).

My code is equivalent to the example found at samples/boards/stm32/h7_dual_core.

The code compiles, and I can successfully send pings between both boards. However, when attempting to send data between the two devices, issues arise. The channel fails to send data with error code 122 (EMSGSIZE).

The code structure resembles the example found at samples/drivers/ipm/ipm_mcux/src, which demonstrates IPM communication working with a NXP board.

Is there a potential issue with the STM32 implementation of the mailbox? Would it be preferable to use IPC (Inter-Process Communication)? How can I encapsulate IPM within an IPC interface? Is this even possible?

**Comment by erwango** [comment]
Advice to check on https://github.com/zephyrproject-rtos/zephyr/pull/68758
