### ISSUE TITLE
doc: Documentation issue in 'kconfig'

### ISSUE THREAD

**Issue by joaodiogogithub** [zephyrproject-rtos/zephyr#69238]
**After the last update, ili9xxx drivers don´t work corretly**

<< Display don´t working >>
<< SPI to MIPI-DBI BUS >>

**Zephyr, LVGL, ili9488, black_f407ve**

* Version: main

**Comment by nordicjm** [comment]
Don't see what this has to do with kconfig and the description means nothing, please use the nearest template in https://github.com/zephyrproject-rtos/zephyr/tree/main/.github/ISSUE_TEMPLATE and fill in the required information
