### ISSUE TITLE
hwmv2: west boards output with identifiers contains board name as part of the identifier

### ISSUE THREAD

**Issue by nordicjm** [zephyrproject-rtos/zephyr#69329]
~~It seems that `west boards --format "{identifiers}"` gives a python array output:~~
```
['stm32wb5mmg/stm32wb55xx']
['em_starterkit/emsk_em7d', 'em_starterkit/emsk_em9d', 'em_starterkit/emsk_em11d']
['emsdp/emsdp_em4', 'emsdp/emsdp_em5d', 'emsdp/emsdp_em6', 'emsdp/emsdp_em7d', 'emsdp/emsdp_em7d_esp', 'emsdp/emsdp_em9d', 'emsdp/emsdp_em11d']
['hsdk/arc_hsdk', 'hsdk/arc_hsdk/2cores']
['hsdk4xd/arc_hsdk4xd']
['iotdk/arc_iot']
['nsim/nsim_em', 'nsim/nsim_em7d_v22', 'nsim/nsim_em11d', 'nsim/nsim_hs', 'nsim/nsim_hs/sram', 'nsim/nsim_hs/smp', 'nsim/nsim_hs/flash_xip', 'nsim/nsim_hs/mpuv6', 'nsim/nsim_hs/hostlink', 'nsim/nsim_hs5x', 'nsim/nsim_hs5x/smp', 'nsim/nsim_hs5x/smp/12cores', 'nsim/nsim_hs6x', 'nsim/nsim_hs6x/smp', 'nsim/nsim_hs6x/smp/12cores', 'nsim/nsim_sem', 'nsim/nsim_sem/mpu_stack_guard', 'nsim/nsim_vpx5']
['robokit1/same70q21b']
['tlsr9518adk80d/tlsr9518']
```

~~Which does not go to stdout, it does not include any hwmv1 boards either~~

It seems that using the command `west boards --format "{identifiers}" | less` makes it look like there is no output, but there is output, but there is a huge amount of empty lines at the top (hwmv1 boards?) which should be fixed

**Comment by nordicjm** [comment]
Yes the actual issue here is the output of `west boards --format="{name} {identifiers}"` is wrong, identifiers is outputting board names along with identifiers when it should just be identifiers, so that is the bug that needs fixing

**Comment by aescolar** [comment]
Reopened as the commit that fixed this was reverted
