### ISSUE TITLE
Add option for configuring P0.9 and P0.10 as GPIO

### ISSUE THREAD

**Issue by alexsven** [zephyrproject-rtos/zephyr#6937]
P0.9 and P0.10 are usually reserved for NFC, need a define in Kconfig to activate the code snippet found here: [https://github.com/zephyrproject-rtos/zephyr/blob/master/arch/arm/soc/nordic_nrf/nrf52/soc.c#L407](url)

**Comment by SebastianBoe** [comment]
@alexsven is correct to identify that this belongs in Kconfig IMHO.

Until this has been resolved users can do

echo "zephyr_compile_definitions(CONFIG_NFCT_PINS_AS_GPIOS)" >> my/app/CMakeLists.txt

**Comment by nvlsianpu** [comment]
done by PR #7449
