### ISSUE TITLE
LE Audio: bt_bap_broadcast_sink_cb.syncable should provide the BIGInfo

### ISSUE THREAD

**Issue by Thalley** [zephyrproject-rtos/zephyr#69386]
**Is your enhancement proposal related to a problem? Please describe.**
The `syncable` callback only provides the encryption field of the BIGInfo, but since the BIGInfo also contains information about SDU sizes and other useful values, it makes sense to provide the entire struct. 

**Describe the solution you'd like**
Modify `bt_bap_broadcast_sink_cb.syncable` to provide the BIGInfo instead of just the encryption field. 

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by ChangNice** [comment]
Hi, Emil you could assign this issue to me.

**Comment by Thalley** [comment]
Implemented by https://github.com/zephyrproject-rtos/zephyr/pull/69729
