### ISSUE TITLE
STM32H5 Missing from MCO2

### ISSUE THREAD

**Issue by cradzik** [zephyrproject-rtos/zephyr#69483]
Hello,

I'm trying to get a clock out on MCO2 on a STM32H5, and ran into some issues.  

I couldn't get it to work until I added "SOC_SERIES_STM32H5X || \" after this line:
https://github.com/zephyrproject-rtos/zephyr/blob/4a72cb16cfd5a8df86b7f1653632dd49b3ea5ff5/drivers/clock_control/Kconfig.stm32#L256C1-L256C36

I believe the STM32H5 is missing from the list of dependencies.

Thanks
Chris

**Comment by FRASTM** [comment]
thank @cradzik to raise the pb , 
Yes, the MCO2 div is actually missing the stm32H5 serie.
Do you intend to push a PR for correcting this ?

**Comment by cradzik** [comment]
@FRASTM.  Here is my pull request:
https://github.com/zephyrproject-rtos/zephyr/pull/69535

Please let me know if I did anything incorrectly.

Thanks!
Chris
