### ISSUE TITLE
STM32WBA52 bootloader cannot jump to application code.

### ISSUE THREAD

**Issue by lnhao** [zephyrproject-rtos/zephyr#69509]
**Describe the bug**
STM32WBA cannot jump to application code, on the same bootloader and application code, but stm32f429 can jump to application and working.

**To Reproduce**
 1. Flash partitions in the dts file:
```
&flash0 {
	partitions {
		compatible = "fixed-partitions";
		#address-cells = <1>;
		#size-cells = <1>;
		 boot_partition: partition@0 {
			label = "mcuboot";
			reg = <0x00000000 DT_SIZE_K(64)>;
		};
		/* storage: 64KB for settings */
		storage_partition: partition@10000 {
			label = "storage";
			reg = <0x00010000 DT_SIZE_K(64)>;
		};
		slot0_partition: partition@20000 {
			label = "image-0";
			reg = <0x00020000 DT_SIZE_K(256)>;
		};
		slot1_partition: partition@60000 {
			label = "image-1";
			reg = <0x00060000 DT_SIZE_K(256)>;
		};
 		scratch_partition: partition@A0000 {
			label = "image-scratch";
			reg = <0x000A0000 DT_SIZE_K(16)>;
		};
	};
};
```
 2. Go to the ./zephyrproject/bootloader/mcuboot/boot/zephyr, added stm32wba52_board.conf file
   `CONFIG_CONSOLE=y`
   `CONFIG_UART_CONSOLE=y`
   `CONFIG_BOOT_MAX_IMG_SECTORS=128`
 3. Building mcuboot.
    west build -b stm32wba52_board -p
 4. Flashing the mcuboot.
    west flash
 5. Go to the application path, added `CONFIG_BOOTLOADER_MCUBOOT=y` in the stm32wba52_board.conf file.
 6. Building Application `west build -b stm32wba52_board -p`
 7. Sign application code `west sign -t imgtool -- --key root-rsa-2048.pem`
 8. Flash Application `west flash --file build/zephyr/zephyr.signed.hex`

**Expected behavior**
After a reset, mcuboot finds the signed binary in the image slot and jumps into it for running the application.

**Experienced behavior**
STM32WBA bootloader cannot jump to application code. I have used `wese debug` to debug the bootloader code.  It has into do_boot() and jumping address is correct but cannot into application code.

Log as following:
```
*** Booting Zephyr OS build v3.6.0 ***
I: Starting bootloader
I: Primary image: magic=unset, swap_type=0x1, copy_done=0x3, image_ok=0x3
I: Scratch: magic=unset, swap_type=0x1, copy_done=0x3, image_ok=0x3
I: Boot source: primary slot
I: Image index: 0, Swap type: none
I: Bootloader chainload address offset: 0x20000
I: Jumping to the first image slot
```

**Impact**
We have used the stm32wba chip as the main controller of the product and need to implement DFU and FOTA features, but we are currently stuck at this point.

**Environment**
 - West runner: jlink
 - Board: nucleo_wba52cg
 - Zephyr OS: v3.5.0, v3.6.0
 - OS: ubuntu 22.04
 - Toolchain: Zephyr SDK 0.16.0

Thank you!

**Comment by nordicjm** [comment]
Can you fill the information in from https://github.com/zephyrproject-rtos/zephyr/blob/main/.github/ISSUE_TEMPLATE/001_bug_report.md this is not optional

**Comment by lnhao** [comment]
@nordicjm  Will do, thank you！

**Comment by erwango** [comment]
> Can you fill the information in from https://github.com/zephyrproject-rtos/zephyr/blob/main/.github/ISSUE_TEMPLATE/001_bug_report.md this is not optional

That would help to provide efficient support indeed

Anyway, can you have a try with what was done for U5 [here](https://github.com/zephyrproject-rtos/zephyr/blame/main/soc/arm/st_stm32/stm32u5/Kconfig.defconfig.series#L13) ?

**Comment by lnhao** [comment]
> > Can you fill the information in from https://github.com/zephyrproject-rtos/zephyr/blob/main/.github/ISSUE_TEMPLATE/001_bug_report.md this is not optional
> 
> That would help to provide efficient support indeed
> 
> Anyway, can you have a try with what was done for U5 [here](https://github.com/zephyrproject-rtos/zephyr/blame/main/soc/arm/st_stm32/stm32u5/Kconfig.defconfig.series#L13) ?

Referenced U5, I experimented on the stm32wba, but still can't jump.

Br, thank you!

**Comment by erwango** [comment]
> Referenced U5, I experimented on the stm32wba, but still can't jump.

Then, we're coming back to the initial request. If you want us to help investigating this point, please use the bug template form.

**Comment by lnhao** [comment]
> > Referenced U5, I experimented on the stm32wba, but still can't jump.
> 
> Then, we're coming back to the initial request. If you want us to help investigating this point, please use the bug template form.

Yes, I want you to help to investigate this point. 
I use a bug template to re-publish an issue ticket, right?

**Comment by nordicjm** [comment]
> > > Referenced U5, I experimented on the stm32wba, but still can't jump.
> > 
> > 
> > Then, we're coming back to the initial request. If you want us to help investigating this point, please use the bug template form.
> 
> Yes, I want you to help to investigate this point. I use a bug template to re-publish an issue ticket, right?

No, go to the top post, click the 3 dots in the top right corner and click edit, then add the information to your post and update

**Comment by lnhao** [comment]
@erwango @nordicjm Updated

**Comment by erwango** [comment]
There maybe an issue in your configuration.
I had a try with `samples/application_development/sysbuild/with_mcuboot`:
```
west build -p always -b nucleo_wba55cg --sysbuild samples/application_development/sysbuild/with_mcuboot
west flash -d build/nucleo_wba55cg/
```
Note that you need to add :
```
	chosen {
		zephyr,code-partition = &slot0_partition;
	};
```

**Comment by erwango** [comment]
You used nucleo_wba55cg board, it can jump to application. Yes it is jumping in application.
nucleo_wba52cg and nucleo_wba55cg are pretty close. I doubt it can have an impact.
Also note that BLE isn't available yet on nucleo_wba52cg due to STM32Cube package limitation (provided BLE controller library not compatible with STM32WBA52 cut).

**Comment by erwango** [comment]
> If I use the wba55cg board to build an application image. Flashing to HW board of wba52cg It should be able to run, right?

Not sure as it enabled SMPS wich is not supported on WB52... (only difference).

**Comment by lnhao** [comment]
> > If I use the wba55cg board to build an application image. Flashing to HW board of wba52cg It should be able to run, right?
> 
> Not sure as it enabled SMPS wich is not supported on WB52... (only difference).

Can you use a WBA52's board to verify bootloader?

**Comment by lnhao** [comment]
> @lnhao Did you try to run these exact commands ?
> 
> > west build -p always -b nucleo_wba52cg --sysbuild samples/application_development/sysbuild/with_mcuboot
> > west flash -d build

yes, I have tried.

**Comment by lnhao** [comment]
Hi @erwango, do you try to run WBA52's board?

**Comment by erwango** [comment]
> Hi @erwango, did you try to run WBA52's board?

I've just managed to get one and I can confirm the issue, which is linked to clock configuration.
As a workaround, you can retrieve clock_configuration from nucleo_wba55cg board:
```diff
&clk_hse {
	status = "okay";
+	hse-div2;
};
&rcc {
-	clocks = <&pll1>;
+	clocks = <&clk_hse>; 
-	clock-frequency = <DT_FREQ_M(96)>;
+	clock-frequency = <DT_FREQ_M(16)>;
	ahb-prescaler = <1>;
-	ahb5-prescaler = <4>;
+	ahb5-prescaler = <2>;
	apb1-prescaler = <1>;
	apb2-prescaler = <1>;
	apb7-prescaler = <1>;
};
```
In parallel, I'm working on a more complete fix.

**Comment by erwango** [comment]
> If I want a larger system clock speed, it still depends on PLL.

Sure. I'm looking into it.

**Comment by erwango** [comment]
@lnhao See https://github.com/zephyrproject-rtos/zephyr/pull/70175 for more complete fix

**Comment by lnhao** [comment]
> @lnhao See #70175 for more complete fix

@erwango Thank you for your update. This is good news. I will try to do this verifying later.

**Comment by lnhao** [comment]
Hi @erwango, I have pulled your branch (`fix_wba_chainloaded`) and tested the bootloader jumping. It can jump to the application code. Looking forward to merging into the Zephyr code repository.

**Comment by erwango** [comment]
> Hi @erwango, I have pulled your branch (`fix_wba_chainloaded`) and tested the bootloader jumping. It can jump to the application code. Looking forward to merging into the Zephyr code repository.

Ok, so please comment on the PR that you've tested it successfully (I guess you can also approve).

**Comment by lnhao** [comment]
Log of successful testing: 
```
*** Booting Zephyr OS build v3.6.0-693-gf9372d62dd9a ***
I: Starting bootloader
I: Image index: 0, Swap type: none
I: Bootloader chainload address offset: 0x20000
*** Booting Zephyr OS build v3.6.0-693-gf9372d62dd9a ***
Address of sample 0x8020000
Hello sysbuild with mcuboot! nucleo_wba52cg
```

**Comment by erwango** [comment]
> Log of successful testing:
> 
> ```
> *** Booting Zephyr OS build v3.6.0-693-gf9372d62dd9a ***
> I: Starting bootloader
> I: Image index: 0, Swap type: none
> I: Bootloader chainload address offset: 0x20000
> *** Booting Zephyr OS build v3.6.0-693-gf9372d62dd9a ***
> Address of sample 0x8020000
> Hello sysbuild with mcuboot! nucleo_wba52cg
> ```

Great, can you put this directly in https://github.com/zephyrproject-rtos/zephyr/pull/70175 ?
This could be useful to speed up the review.
