### ISSUE TITLE
NRF52840: I2C, SPI driver

### ISSUE THREAD

**Issue by IotPanorama** [zephyrproject-rtos/zephyr#6957]
does zephyr has i2c support for nrf52840? if yes then please redirect me to that.

**Comment by anangl** [comment]
@IotPanorama Currently, I2C on nRF52840 is supported by the same driver as for nRF52832 and nRF51822. It uses the TWI peripheral, which is the same in these chips. You can find its implementation [here](https://github.com/zephyrproject-rtos/zephyr/blob/master/drivers/i2c/i2c_nrf5.c), and you activate it using CONFIG_I2C_NRF5 setting.

**Comment by carlescufi** [comment]
@IotPanorama The new SPI driver is ready for review here: https://github.com/zephyrproject-rtos/zephyr/pull/6985

**Comment by carlescufi** [comment]
Closing since the questions have been answered
