### ISSUE TITLE
doc: Documentation issue in 'releases/index'

### ISSUE THREAD

**Issue by alwa-nordic** [zephyrproject-rtos/zephyr#69614]
There is an inconsistency in [Supported Releases].

- [Release Management] says 3.7 (LTS) release is 2024/07/26.

- [Supported Releases] says the following:

  > Support and maintenance for an LTS release stops at least half a year after the following LTS release is published.

- That implies [Supported Releases] **entry for the previous LTS, Zephyr 2.7.5, must have EOL no sooner than 2025/01/26**.
	
[Supported Releases]: https://docs.zephyrproject.org/latest/releases/index.html#supported-releases
[Release Management]: https://github.com/zephyrproject-rtos/zephyr/wiki/Release-Management

**Comment by kartben** [comment]
@nashif @aescolar @cfriedt

**Comment by cfriedt** [comment]
Given that 2.7.6 is getting cut today, it would probably make some sense to update the wiki too.
