### ISSUE TITLE
net: IPv4 TOS option not working in zperf

### ISSUE THREAD

**Issue by jukkar** [zephyrproject-rtos/zephyr#69627]
When the zperf command is called with '-S' option which means IP_TOS
for IPv4 and IPV6_TCLASS for IPv6, an error is printed and the
setting does not work. The socket option handling was changed by
commit https://github.com/zephyrproject-rtos/zephyr/commit/77e522a5a243717bee869a5a932e91873ee03281('net: context: Refactor option setters'), but the
callers of option setters were not changed. This causes the IP_TOS
or IPV6_TCLASS option failed to set. The fix is to use uint8_t to
store the value of the -S option.

**Comment by jukkar** [comment]
Fixed by #69610

**Comment by henrikbrixandersen** [comment]
@jukkar Can this be closed?

**Comment by jukkar** [comment]
Yes, lets close it.
