### ISSUE TITLE
nrfx_timer driver uses wrong base address

### ISSUE THREAD

**Issue by marcowidmer** [zephyrproject-rtos/zephyr#69631]
Commit 9a27906e38343b07cbdf1b4aca5451c5886dbd41 changed the derivation of the base address of the NRF_TIMER. However, instead of taking the index of the selected timer peripheral, it takes the index of the timer in the list of activated timers. In some of the timers are disabled in the device tree, this results in a wrong base address.

Let's assume the following device tree:
```
timer0: timer@40008000 {
	compatible = "nordic,nrf-timer";
	status = "disabled";
	reg = <0x40008000 0x1000>;
};

timer1: timer@40009000 {
	compatible = "nordic,nrf-timer";
	status = "okay";
	reg = <0x40009000 0x1000>;
};
```
`DT_INST_FOREACH_STATUS_OKAY(COUNTER_NRFX_TIMER_DEVICE)` will call `COUNTER_NRFX_TIMER_DEVICE` for timer1 with idx=0 (since it is the first activated nrf-timer). The base address is set to NRF_TIMER0 (0x40008000). The correct address would be NRF_TIMER1 (0x40009000).

Users of the driver will now unexpectedly interact with NRF_TIMER0 instead of NRF_TIMER1.

**Comment by aescolar** [comment]
Closing as dup of #69216
