### ISSUE TITLE
Documentation build using Sphinx 4.x is broken on LTS2 branch

### ISSUE THREAD

**Issue by kartben** [zephyrproject-rtos/zephyr#69656]
Sphinx 4.x is way past EOL and not properly working out of the box as of today. This breaks the documentation build in LTS branch.
Fix would be to update to Sphinx 5.0.2, as recommended in https://github.com/sphinx-doc/sphinx/issues/11890.
For the upcoming LTS, we will want to be extra careful and make sure that we're using the most recent version of Sphinx we can to minimize the risk of ending up in a similar situation.

**Comment by aescolar** [comment]
Fixed
