### ISSUE TITLE
doc: Documentation issue in 'boards/arm64/mimx8mp_evk/doc/index'

### ISSUE THREAD

**Issue by ndpires** [zephyrproject-rtos/zephyr#69686]
**Description typo**

In the debug description of the board features section there is a typo:
It is written:
MicroUSB for UART debug, two COM ports for A53 and **M4**
whereas it should be:
MicroUSB for UART debug, two COM ports for A53 and **M7**

**Environment**

* Page: `boards/arm64/mimx8mp_evk/doc/index`
* Version: main
* SHA-1: 59e4c5aed0b0b9ae870cc3b1667c6e781c409070

**Comment by kartben** [comment]
@ndpires could you send a PR to fix this? Thanks!
