### ISSUE TITLE
rpi_pico: Making possible to set the initial state of PIO pins with pinctrl

### ISSUE THREAD

**Issue by soburi** [zephyrproject-rtos/zephyr#69714]
I want to initialize PIO output and side set pins, but
That is not possible with the current pinctrl.

Settings must be made before gpio_set_function.

MicroPython implementation is good example.
https://github.com/micropython/micropython/blob/bc424ddc4165ffd8203b4e781f7c686598601e15/ports/rp2/rp2_pio.c#L226-L233

**Comment by nordicjm** [comment]
Note: initial state should be set using gpio-hogs

**Comment by henrikbrixandersen** [comment]
> Note: initial state should be set using gpio-hogs

Agreed. This is the solution implemented by all other Zephyr platforms. Closing as not planned.
