### ISSUE TITLE
Bluetooth: ATT: att_req_send_process() fails assert on pre-emptive thread

### ISSUE THREAD

**Issue by martintv** [zephyrproject-rtos/zephyr#69737]
**Describe the bug**
I did a minor adjustment to llpm sample in NCS, so that it ends up sending write commands from both central and peripheral very often. If sample is run in noisy rf-environment, this assert is reproducible pretty quickly. within 5 min normaly.
Assert Im getting:
https://github.com/zephyrproject-rtos/zephyr/blob/72a17b6d887ef20b3cc08a25d8ea1d622792d57a/subsys/bluetooth/host/att.c#L822

 - What target platform are you using?
 NRF52840DK
 
- What have you tried to diagnose or workaround this issue?
I tried a quickfix by disabling shceduler like [this](https://github.com/martintv/sdk-zephyr/commit/209bbcd3995bb711f0911d4c0b3c4b0c2d3808d9) and assert in question does go away. But when I leave it running overnight (so takes longer to reproduce) I still get a different assert [__ASSERT_NO_MSG(req->func);](https://github.com/zephyrproject-rtos/zephyr/blob/72a17b6d887ef20b3cc08a25d8ea1d622792d57a/subsys/bluetooth/host/att.c#L821).

Hypothesis then is that it is the iterator in [att_req_send_process](https://github.com/zephyrproject-rtos/zephyr/blob/72a17b6d887ef20b3cc08a25d8ea1d622792d57a/subsys/bluetooth/host/att.c#L834), but I havent looked into it further.

**To Reproduce**
setup ncs enviormnet, checkout this
https://github.com/martintv/sdk-nrf/commits/reproducing_att_assert/
west build --pristine -b nrf52840dk_nrf52840 nrf/samples/bluetooth/llpm
west flash  <--- on two dks.

**Expected behavior**
Shouldn't assert

**Impact**
Possible corruption when asserts are disabled.
Application crash when asserts are enabled.

**Comment by nordicjm** [comment]
You are reporting an issue in ncs which is not zephyr, ncs bugs go to https://devzone.nordicsemi.com/ so you need to reproduce this bug using upstream zephyr for it to be valid here

**Comment by jori-nordic** [comment]
I asked martin to post it here. 
We have had host bug reports that use the host in combination w/ a closed-source controller *and* we have tried to debug them. In that case, martin raises a valid concern, that the code in att_process is not thread-safe.

**Comment by jori-nordic** [comment]
Adding medium priority, as this iterator corruption ends up crashing the whole app.
