### ISSUE TITLE
Contributor Nomination tomi-font

### ISSUE THREAD

**Issue by bjarki-trackunit** [zephyrproject-rtos/zephyr#69761]
# Nomination

## GitHub User

Provide the following information about the GitHub user:

Full Name: Tomi Fontanilles
GitHub username: tomi-font
Organization: Nordic Semiconductor

## Supporting Documents

#68981
#68651
#68206
#67062
#66522

[TSC Project Roles]: <https://docs.zephyrproject.org/latest/project/project_roles.html>
[GitHub Permission Level]: <https://docs.github.com/en/organizations/managing-access-to-your-organizations-repositories/repository-roles-for-an-organization>

**Comment by aescolar** [comment]
CC @nashif @MaureenHelm @carlescufi

**Comment by bjarki-trackunit** [comment]
@kartben This one is stuck I think :)

**Comment by nashif** [comment]
https://github.com/zephyrproject-rtos/zephyr/invitations
