### ISSUE TITLE
hwmv2: Out of tree hwmv1 boards/socs do not work

### ISSUE THREAD

**Issue by nordicjm** [zephyrproject-rtos/zephyr#69785]
**Describe the bug**
Seemingly getting a second zephyr checkout on 3.6 and commenting the deprecation of a board then prevents the original board from being found. Indeed it seems that `scripts/list_boards.py` just returns nothing at all when using the SOC and BOARD roots of the zephyr 3.6 directory.

**To Reproduce**
Comment out a board deprecating and try building for it with BOARD_ROOT and SOC_ROOT set to the zephyr 3.6 directory. As a bonus just run the list_boards script, e.g. `/tmp/aa/zephyr/scripts/list_boards.py --board-root=/tmp/bb/zephyr/ --arch-root=/tmp/aa/zephyr --soc-root=/tmp/bb/zephyr/` gives no output at all. Running the 3.6 script with the same parameters minus SOC root gives a full output `/tmp/bb/zephyr/scripts/list_boards.py --board-root=/tmp/bb/zephyr/ --arch-root=/tmp/aa/zephyr`:
```
...
nios2:
  altera_max10
  qemu_nios2
posix:
  native_posix
  native_posix_64
  native_sim
  native_sim_64
  nrf52_bsim
  nrf5340bsim_nrf5340_cpuapp
  nrf5340bsim_nrf5340_cpunet
riscv:
  adp_xc7k_ae350
  beaglev_fire
  esp32c3_devkitm
  esp32c3_luatos_core
  esp32c3_luatos_core_usb
...
```

**Expected behavior**
Boards to be detected and work

**Impact**
Showstopper, release blocker

**Environment (please complete the following information):**
 - Commit SHA or Version used: 72a17b6d887ef20b3cc08a25d8ea1d622792d57a

**Comment by tejlmand** [comment]
same is seen for Zephyr modules.
