### ISSUE TITLE
v3.6: STM32WBA: Do not enable Standby by default

### ISSUE THREAD

**Issue by gautierg-st** [zephyrproject-rtos/zephyr#69782]
**Describe the bug**
On Zephyr 3.6, STM32WBA has Standby low-power mode enabled by default. That can cause issues if Kconfig PM_S2RAM is disabled (which is the default state) since we could enter an unsupported low power mode.

**Expected behavior**
Standby mode shouldn't be enabled by default, to keep things consistent with Kconfig PM_S2RAM.

**Comment by henrikbrixandersen** [comment]
> On Zephyr 3.5, ...

Did you mean to write 3.6 here and in the title?

**Comment by gautierg-st** [comment]
> > On Zephyr 3.5, ...
> 
> Did you mean to write 3.6 here and in the title?

Yes sorry, I mixed things up. Fixed

**Comment by erwango** [comment]
Merged
