### ISSUE TITLE
Moving the Zephyr merge list dashboard under the org

### ISSUE THREAD

**Issue by fabiobaltieri** [zephyrproject-rtos/zephyr#69815]
## Introduction

Hi, so it looks like https://fabiobaltieri.github.io/zephyr-merge-queue/, much to my surprise, survived the release without any major drama, guess it's time to figure what to do with it.

### Problem description

My name is in that URL.

### Proposed change

Move it under the org.

## Detailed RFC

Push it under an org repo, delete my repo forever.

### Concerns and Unresolved Questions

1. This should be renamed to `zephyr-merge-list`, it's not a queue, I never claimed to be good at naming things.
2. This currently depends on GitHub pages and uses the action API key. Pages are free and the key is automatically generated per action, which guarantees isolation between other repo actions. Now I was about to write a page of details on how the thing works and how it gets occasionally close to the 1000RPCs/h limit that GH action keys have and how I had to tweak the update cadence few times, but now it looks like GH silentely increased the limit to 5000RPCs/h, so that's not a problem anymore. Just for reference this script eats up 3 RPC per PR (PR data, review list and event list) and tries to run every 5 minutes.
3. People already started forking this and use their own filters, maybe the code made to be a bit more reusable.
4. This could use a template engine, probably a good job for someone who actually enjoys working on that stuff.
5. ~The milestone filter (the thing that hides PRs marked for a specifc release) is currently a flag, it can and should be automated by reading the tag list on the main repository so it enters "feature freeze" mode automatically (I can look into that).~ done
6. The action tries to disable itself 60 days after the last commit, then someone has to press a "continue running" button and the countdown restarts, not ideal

### Alternatives considered

1. Host the pages on AWS (like with the generated documentation), easy change, could even coexist with gh pages, problem is that in my experience the server side caching gets in the way (at least it does for the generated documentation), and then this also requires importing a secret into the workflow, which means it's harder for people to fork and reuse it. Don't see any advatage but is there any negative implications for using GH pages for an org repo?
2. Run this as part of the project infrastructure on hosted instances: this would allow to rewrite the script to save the state between runs, which would increase the complexity a fair bit but would reduce the RPC count significantly and allow to run more often. I would have advocated for that with the 1k rpc limit but now I think it's totally not worth it and there's more value in keeping the code simpler.
3. Redesign the whole thing to use webhook rather than scraping periodically. Sounds like a great project. For somebody else.

**Comment by fabiobaltieri** [comment]
cc @zephyrproject-rtos/release

**Comment by fabiobaltieri** [comment]
@stephanosio have you had any chance to think about this? Would it make sense to push it on an org repo and run it as-is for now? It's pretty much a no maintanence deal at the moment.

**Comment by stephanosio** [comment]
> @stephanosio have you had any chance to think about this? Would it make sense to push it on an org repo and run it as-is for now? It's pretty much a no maintanence deal at the moment.

No objection to moving https://github.com/fabiobaltieri/zephyr-merge-queue under the zephyrproject-rtos organisation and running it as-is. It would be good to rename to repository to something like `zephyr-merge-list` as part of the move though.

@fabiobaltieri Would you like me to create `zephyr-merge-list` repository under the org so that you can push to it?

**Comment by stephanosio** [comment]
https://github.com/zephyrproject-rtos/zephyr-merge-list has been created.

**Comment by fabiobaltieri** [comment]
Thanks Stephanos, pushed my branch and enabled pages, this is now live at https://zephyrproject-rtos.github.io/zephyr-merge-list/. I'll let it bake a bit to make sure everything is running smoothly and then stop my copy and put a redirect warning.

**Comment by stephanosio** [comment]
> this is now live at https://zephyrproject-rtos.github.io/zephyr-merge-list/.

It is now live at https://merge-list.zephyrproject.io/ with a bit nicer URL.
