### ISSUE TITLE
userspace malloc fails on Cortex-M0+

### ISSUE THREAD

**Issue by d3zd3z** [zephyrproject-rtos/zephyr#69819]
When enabling the MPU and USERSPACE on the rp2040 (Cortex-M0+) target, the heap used by `malloc` is not made accessible in the MPU to userspace, resulting in an immediate fault upon calling `malloc`. I have found this to be the case whether using the newlib malloc, or the common libc malloc.

I can build with:
```
west build \
  -b sparkfun_pro_micro_rp2040 \
  tests/lib/newlib/thread_safety \
  -- \
  -DCONFIG_ARM_MPU=y \
  -DCONFIG_USERSPACE=y \
  -DCONFIG_NEWLIB_THREAD_SAFETY_TEST_STRESS=y \
  -DCONF_FILE=prj_userspace.conf \
```

I don't have a console on this target, but with a debugger, it shows that I am within a hard fault handler called while in `malloc`.

I can also reproduce this by using the common libc malloc, with an arena size, and confirm that `mpu_configure_region` is never called on the region containing the `z_malloc_heap`.

**Expected behavior**
Per documentation, the malloc heap should be accessible from userspace, as there is an explicit region defined for this.

**Impact**
Most use of the rp2040 seems to be without userspace defined, which is probably why this hasn't been noticed until now.

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: Zephyr SDK 0.16.1
 - Zephyr tree: a48c958c8fb85a0985880482df9c79407a8fc55e

Board is the Sparkfun pro micro rp2040, although this should be reproducible on any rp2040 board. There are a few other Cortex-M0+ targets that support the MPU as well, such as the stm32g0, and stm32c0.

**Comment by aescolar** [comment]
CC @microbuilder
