### ISSUE TITLE
ESP32 telnet sample. There is no network interface to work with!

### ISSUE THREAD

**Issue by nychyporuk** [zephyrproject-rtos/zephyr#69839]
**Describe the bug**
The telnet sample doesn't work with esp32_devkitc_wroom board.
The console shows "There is no network interface to work with!"

**To Reproduce**
1. build and flash samples\net\telnet app
2. Open the console and see the error: There is no network interface to work with!

**Expected behavior**
The working telnet server is expected

**Logs and console output**
There is no network interface to work with
Booting Zephyr OS build v3.6.0-rc2-28-gded0d48779e2
Backtrace:0x4008219f:0x3ffe8220 0x400d9849:0x3ffe8240 0x400d985c:0x3ffe8260 0x400db262:0x3ffe8280 0x400d0ffd:0x3ffe82b0 0x40081187:0x3ffe82e0 0x400d1503:0x3ffe8300

**Environment (please complete the following information):**
 - OS: Windows 11
 - Toolchain: Zephyr SDK
 - Zephyr OS build: v3.6.0-rc2-28-gded0d48779e2

**Additional context**
I am using esp32_devkitc_wroom board

**Comment by AdamBenSalah2000** [comment]
Hello , can you share the solution please
