### ISSUE TITLE
Sample Devicetree configuration for DS18B20

### ISSUE THREAD

**Issue by maxkraft7** [zephyrproject-rtos/zephyr#69863]
**Is your feature request related to a problem? Please describe.**
I'm not able to use the W1 GPIO-Drivers with a DS18B20. 

**Describe the solution you'd like**
An example configuration of a DS18B20 devicetree using GPIO. 

**Describe alternatives you've considered**
Using it via the UART interface but that doesn't work. 

**Additional context**
This is what I tried so far, but it's not buildable: 

```c
	ds18b20gp {
		compatible = "maxim,ds18b20";
		family-code = <0x28>;
		resolution = <12>;
		gpios = <&gpio0 18 (GPIO_ACTIVE_HIGH | GPIO_OPEN_DRAIN | GPIO_PULL_UP)>;
		status = "okay";
	};
```

I cherrypicked this commit: [drivers: w1: add zephyr-gpio driver ](https://github.com/zephyrproject-rtos/zephyr/pull/65948/commits/16ead9fb1d693c0dcb67ae7cbc8c4a062bcb96b7) into that repo: [nrfconnect/sdk-zephyr](https://github.com/nrfconnect/sdk-zephyr). Sadly nordic hasn't yet implemented this commit in their version.

**Comment by nordicjm** [comment]
This is for reporting zephyr bugs, not ncs bugs. If you can reproduce the issue using upstream zephyr and edit your comment to include all the information required in https://github.com/zephyrproject-rtos/zephyr/blob/main/.github/ISSUE_TEMPLATE/001_bug_report.md which **is mandatory** then the issue can be reopened.
