### ISSUE TITLE
Compile error while building tests\bluetooth\shell for Silabs board

### ISSUE THREAD

**Issue by Dermiste** [zephyrproject-rtos/zephyr#69902]
**Describe the bug**
Error while building the bluetooth shell sample for efr32xg24_dk2601b
![image](https://github.com/zephyrproject-rtos/zephyr/assets/1168706/078bbb2e-0b38-45a4-8716-838e4269a62e)

**To Reproduce**
Run command:
`west build -p -b efr32xg24_dk2601b tests\bluetooth\shell`

**Expected behavior**
Build completes

**Impact**
Can't run the shell on my board

**Environment (please complete the following information):**
 - Windows
 - Zephyr 3.6.99

** Other informations **
- my workspace was initiated months ago using Zephyr 3.5.99 and updated later on using `west update`
- tests\bluetooth\shell used to work back then

**Comment by fkokosinski** [comment]
Hey, thanks for reporting this issue.

> **To Reproduce**
> Run command:
> `west build -p -b efr32xg24_dk2601b samples/hello_world`

Is this the right command to reproduce this issue? Because Hello world build normally for me, and I don't see how it is related to the sample in the title.

**Comment by Dermiste** [comment]
My bad I updated the command

**Comment by pepe2k** [comment]
@fkokosinski looks like `hal_silabs` related, the `SOC_GECKO_SERIESx` (see https://github.com/zephyrproject-rtos/hal_silabs/blob/master/gecko/CMakeLists.txt#L28) has to be updated to recently introduced `SOC_FAMILY_SILABS_Sx`.

**Comment by Dermiste** [comment]
If it's hal related I assume that same kind of error will pop up at some point for other samples and project related to SiLabs boards ? i.e, a fix will happen by itself since the "bug" is wirespread?

**Comment by pepe2k** [comment]
> If it's hal related I assume that same kind of error will pop up at some point for other samples and project related to SiLabs boards ? i.e, a fix will happen by itself since the "bug" is wirespread?

I believe the problem is BLE and two SOC series related only and seems to be caused by migration to the new h/w model v2. You can just apply my hotfix (inside `modules/hal/silabs`) for now to be able to build without the error.

**Comment by Dermiste** [comment]
I don't work on my Zephyr project anymore, I made this PR because I thought the stack size fix would benefit other people at some point. I guess it will remain a draft until a clean build is once again possible, then I'll check again the stack size requirements

**Comment by fabiobaltieri** [comment]
@pepe2k the fix is correct, that symbol changed as part of the hwmv2 migration, could you open a PR for it?

**Comment by pepe2k** [comment]
@fabiobaltieri sure, will send PR.

**Comment by pepe2k** [comment]
@fabiobaltieri FYI: https://github.com/zephyrproject-rtos/hal_silabs/pull/61
