### ISSUE TITLE
Hardware model v2: terminology

### ISSUE THREAD

**Issue by carlescufi** [zephyrproject-rtos/zephyr#69905]
This issue is here to decide together on the terminology related to boards after the introduction of hardware model v2.
See the [Discord thread](https://discord.com/channels/720317445772017664/1214957177941524501/1214957591969533962) for more context.

EDIT: As per the Discord thread above, the current winning candidate is 3.a.

## Terms to be decided upon

As a reference example, we will use the Laird BL5340 Development Kit (`bl5340_dvk`, which is a board that has a single SoC (`nrf5340`), with two cores (`cpuapp` and `cpunet`) and a single variant (`ns`). Let's also assume the board has a revision named `1.2.0`.

The terms that need defining are:

a. `bl5340_dvk`
b. `nrf5340`, `cpuapp`, `ns`
c. `nrf5340/cpuapp/ns`
d. `bl5340_dvk@1.2.0/nrf5340/cpuapp/ns`
e. `bl5340_dvk_nrf5340_cpuapp_ns`
f. `1.2.0`: This is called **board revision** in all options below

### Option 1.a

This is the option that maps the closest to what is today in the tree.

a. `bl5340_dvk`: **board name**
b. `nrf5340`, `cpuapp`, `ns`: **board identifier** (**soc**, **cpu cluster**, **variant**)
c. `nrf5340/cpuapp/ns`: **board identifiers**
d. `bl5340_dvk@1.2.0/nrf5340/cpuapp/ns`: **board target**
e. `bl5340_dvk_nrf5340_cpuapp_ns`: **normalized board target**

### Option 1.b

This is Option 1.a but with the "identifier" plurals flipped.

a. `bl5340_dvk`: **board name**
b. `nrf5340`, `cpuapp`, `ns`:  **soc**, **cpu cluster**, **variant**
c. `nrf5340/cpuapp/ns`: **board identifier**
d. `bl5340_dvk@1.2.0/nrf5340/cpuapp/ns`: **board target**
e. `bl5340_dvk_nrf5340_cpuapp_ns`: **normalized board target**

### Option 2

Proposed in the Discord thread.

a. `bl5340_dvk`: **board name**
b. `nrf5340`, `cpuapp`, `ns`: **board attribute** (**soc**, **cpu cluster**, **variant**)
c. `nrf5340/cpuapp/ns`: **board configuration**
d. `bl5340_dvk@1.2.0/nrf5340/cpuapp/ns`: **board target** or **board target identifier**
e. `bl5340_dvk_nrf5340_cpuapp_ns`: **(normalized) board build identifier**

### Option 3.a

A hybrid to avoid the term "identifier".

a. `bl5340_dvk`: **board name**
b. `nrf5340`, `cpuapp`, `ns`:  **soc**, **cpu cluster**, **variant**
c. `nrf5340/cpuapp/ns`: **board qualifiers**
d. `bl5340_dvk@1.2.0/nrf5340/cpuapp/ns`: **board target**
e. `bl5340_dvk_nrf5340_cpuapp_ns`: **normalized board target**

### Option 3.b

This is Option 3.a but with the "identifier" plurals flipped.

a. `bl5340_dvk`: **board name**
b. `nrf5340`, `cpuapp`, `ns`: **board qualifiers** (**soc**, **cpu cluster**, **variant**)
c. `nrf5340/cpuapp/ns`: **board qualifier**
d. `bl5340_dvk@1.2.0/nrf5340/cpuapp/ns`: **board target**
e. `bl5340_dvk_nrf5340_cpuapp_ns`: **normalized board target**

### Option 3.c

This is Option 3.b but without a specific name for the `nrf5340`, `cpuapp`, `ns`.

a. `bl5340_dvk`: **board name**
b. `nrf5340`, `cpuapp`, `ns`:  **soc**, **cpu cluster**, **variant**
c. `nrf5340/cpuapp/ns`: **board qualifier**
d. `bl5340_dvk@1.2.0/nrf5340/cpuapp/ns`: **board target**
e. `bl5340_dvk_nrf5340_cpuapp_ns`: **normalized board target**

### Option 4

A variation using "board target identifier".

a. `bl5340_dvk`: **board name**
b. `nrf5340`, `cpuapp`, `ns`:  **soc**, **cpu cluster**, **variant**
c. `nrf5340/cpuapp/ns`: **target identifier** (`{soc}/{cpu cluster}/{variant}`)
d. `bl5340_dvk@1.2.0/nrf5340/cpuapp/ns`: **board target** (`board name}[@{revision}]/{board target identifier}`)
e. `bl5340_dvk_nrf5340_cpuapp_ns`: **normalized board target**

## Diagram of the options

![boards drawio (9)](https://github.com/zephyrproject-rtos/zephyr/assets/12450381/83dabf92-9bb3-4111-b7df-4b043dd59bc0)

**Comment by tejlmand** [comment]
Let's use:
e. nrf5340dk_nrf5340_cpuapp_ns: **sanitized** board ...

**Comment by gmarull** [comment]
## Option 4

a. `nrf5340dk`: **board name**
b. `nrf5340`, `cpuapp`, `ns`:  already defined terms? (see (c))
c. `nrf5340/cpuapp/ns`: **board target identifier**, defined as the composition of `{soc}/{cpu cluster}/{variant}`.
d. `nrf5340dk@x/nrf5340/cpuapp/ns`: **board target**, defined as the composition of `{board name}[@{revision}]/{board target identifier}`, `[]` means optional.
e. `nrf5340dk_x_nrf5340_cpuapp_ns`: **sanitized/normalized board target**

**Comment by nordicjm** [comment]
Can we have an option 5 which is a clone of 1 with b and c plurality flipped e.g. b are board identifiers and c is the board identifier (consisting of identifiers)?

**Comment by nashif** [comment]
you probably want to pick a different example or generalize it, because for the ignorant user

`nrf5340/cpuapp/ns` and `nrf5340dk/nrf5340/cpuapp/ns` look both like board names

**Comment by gmarull** [comment]
please add board revision into the equation

**Comment by carlescufi** [comment]
Closing this as decided.
