### ISSUE TITLE
tests: v3.6.0-598-g9f7695dda0c3:lpcxpresso55s69/lpc55s69/cpu0/ns : ADC build failure

### ISSUE THREAD

**Issue by hakehuang** [zephyrproject-rtos/zephyr#69945]
**Describe the bug**

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<body lang=ZH-CN style='tab-interval:21.0pt;word-wrap:break-word;text-justify-trim:
punctuation'>

CASE_NAME | ZEPHYR_VERSION | RESULT | PLATFORM | TEST_PATH
-- | -- | -- | -- | --
mgmt.mcumgr.fs.mgmt.hash.supported.crc32 | v3.6.0-598-g9f7695dda0c3 | Build   failure | lpcxpresso55s69/lpc55s69/cpu0/ns | tests/subsys/mgmt/mcumgr/fs_mgmt_hash_supported
mgmt.mcumgr.fs.mgmt.hash.supported.sha256 | v3.6.0-598-g9f7695dda0c3 | Build   failure | lpcxpresso55s69/lpc55s69/cpu0/ns | tests/subsys/mgmt/mcumgr/fs_mgmt_hash_supported
mgmt.mcumgr.fs.mgmt.hash.supported.all | v3.6.0-598-g9f7695dda0c3 | Build   failure | lpcxpresso55s69/lpc55s69/cpu0/ns | tests/subsys/mgmt/mcumgr/fs_mgmt_hash_supported
drivers.adc | v3.6.0-598-g9f7695dda0c3 | Build   failure | lpcxpresso55s69/lpc55s69/cpu0/ns | tests/drivers/adc/adc_api

</body>

</html>

**To Reproduce**

**Expected behavior**
Build PASS

**Impact**
What impact does this issue have on your progress (e.g., annoyance, showstopper)

**Logs and console output**

```
/home/jenkins/agent/workspace/bitbucket_build_platform/zephyr/tests/drivers/adc/adc_api/src/test_adc.c
/home/jenkins/agent/workspace/bitbucket_build_platform/zephyr/tests/drivers/adc/adc_api/src/test_adc.c:33:2: error: #error "Unsupported board."
   33 | #error "Unsupported board."
      |  ^~~~~
/home/jenkins/agent/workspace/bitbucket_build_platform/zephyr/tests/drivers/adc/adc_api/src/test_adc.c: In function 'get_adc_device':
/home/jenkins/agent/workspace/bitbucket_build_platform/zephyr/tests/drivers/adc/adc_api/src/test_adc.c:38:31: error: 'adc_channels' undeclared (first use in this function); did you mean 'adc_channel_cfg'?
   38 |         if (!adc_is_ready_dt(&adc_channels[0])) {
      |                               ^~~~~~~~~~~~
      |                               adc_channel_cfg
```

**Environment (please complete the following information):**
 - OS: (e.g. Linux, MacOS, Windows)
 - Toolchain (e.g Zephyr SDK, ...)
 - Commit SHA or Version used: v3.6.0-598-g9f7695dda0c3

**Comment by aescolar** [comment]
Commit which claimed to fix it has been merged => closing
