### ISSUE TITLE
BSIM test - RPA expired test- To add adv sets which will return `false` for the first set and `true` for the second on rpa_expired cb

### ISSUE THREAD

**Issue by niym-ot** [zephyrproject-rtos/zephyr#69969]
Could you post a follow-up PR where you add another id w/ two other adv sets, that return `false` for the first one and `true` for the second one? Ie started in reverse order so the iterator hits the `false` first.

_Originally posted by @jori-nordic in https://github.com/zephyrproject-rtos/zephyr/pull/68892#discussion_r1514395345_

**Comment by henrikbrixandersen** [comment]
Please use our bug template when reporting bugs. You need to edit this issue to include the information requested in https://github.com/zephyrproject-rtos/zephyr/blob/main/.github/ISSUE_TEMPLATE/001_bug_report.md
