### ISSUE TITLE
doc: broken link in 'hardware/porting/soc_porting'

### ISSUE THREAD

**Issue by TheSilverBB** [zephyrproject-rtos/zephyr#69990]
**Describe the bug**

In section SoC Porting Guide, hyperlink attached to text [dts/&lt;ARCH&gt;/](https://github.com/zephyrproject-rtos/zephyr/blob/main/VENDOR) is broken.
Should this be changed to https://github.com/zephyrproject-rtos/zephyr/tree/main/dts?

**Environment**

* Page: `hardware/porting/soc_porting`
* Version: main
* SHA-1: 37c1c541e6a14bd2a4e56ccce29bdec189f88589

**Comment by aescolar** [comment]
CC @tejlmand

**Comment by aescolar** [comment]
@TheSilverBB could you provide a link to the page where the issue is?
