### ISSUE TITLE
NXP: Enabling frdm_k64f usb host controller leads CI fail because frdm_k64f + max3421e is default used in CI

### ISSUE THREAD

**Issue by MarkWangChinese** [zephyrproject-rtos/zephyr#70013]
**Describe the bug**
When implementing https://github.com/zephyrproject-rtos/zephyr/pull/68232, find: Enabling frdm_k64f usb host controller leads CI fail because frdm_k64f + max3421e is default used in CI

**Comment by hakehuang** [comment]
@MarkWangChinese  please follow the community style to report issue. and this is not a bug but a feature enhance/missing

**Comment by decsny** [comment]
I am going to close this because it doesn't seem to be reporting a bug and don't know what the meaning is. If there is a bug please edit the original message to follow the reporting template and then you can reopen this issue.
