### ISSUE TITLE
ADS1119 configuration register access macros do not work

### ISSUE THREAD

**Issue by jan-kubiznak** [zephyrproject-rtos/zephyr#70091]
**Describe the bug**
Following macros in drivers/adc/ads1119.c always produce result = 0, because bitmask is shifted first.
```
#define ADS1119_CONFIG_CM(x) ((x) & BIT(1))
#define ADS1119_CONFIG_DR(x) ((x) & (BIT_MASK(2) << 2))
#define ADS1119_CONFIG_GAIN(x) ((x) & BIT(4))
#define ADS1119_CONFIG_MUX(x) ((x) & (BIT_MASK(3) << 5))
```

Example:
```
enum {
	ADS1119_CONFIG_DR_20            = 0,
	ADS1119_CONFIG_DR_90            = 1,
	ADS1119_CONFIG_DR_330           = 2,
	ADS1119_CONFIG_DR_1000          = 3,
	ADS1119_CONFIG_DR_DEFAULT       = ADS1119_CONFIG_DR_20,
};
```
Calculation:
`ADS1119_CONFIG_DR(ADS1119_CONFIG_DR_90) -> (0x01) & (0x03 << 2) -> 0x01 & 0x0C -> 0x00`

**To Reproduce**
1. Try to change ADS1119 configuration register.

**Expected behavior**
With following change the macros produce expected result. See adc_ads1112.c driver, which macros look like this as well.
```
#define ADS1119_CONFIG_CM(x) (((x) & BIT(0)) << 1)
#define ADS1119_CONFIG_DR(x) (((x) & BIT_MASK(2)) << 2)
#define ADS1119_CONFIG_GAIN(x) ((x) & BIT(0) << 4)
#define ADS1119_CONFIG_MUX(x) (((x) & BIT_MASK(3)) << 5)
```
Calculation:
`ADS1119_CONFIG_DR(ADS1119_CONFIG_DR_90) -> (0x01 & 0x03) << 2) -> 0x01 << 2 -> 0x04`

**Impact**
Cannot properly set ADS1119 configuration register. ADC always works with its default settings.

**Logs and console output**
No error logged.

**Environment (please complete the following information):**
* OS: Ubuntu 22.04.4 LTS
* Toolchain: Zephyr SDK v0.16.5
* Commit SHA or Version used: v3.6.0

**Additional context**
Nothing specific.

**Comment by aescolar** [comment]
@jan-kubiznak would you like to send a PR with a fix?

**Comment by jan-kubiznak** [comment]
Yes, I can create a pull request.
