### ISSUE TITLE
LSM6DSL: Isse with spi_config

### ISSUE THREAD

**Issue by erwango** [zephyrproject-rtos/zephyr#7009]
Seems that since recent SPI API update, spi_config as lost dev element.

In LSM6DSL new SPI interface is not in line: in lsm6dsl_spi_init
``
	lsm6dsl_spi_conf.dev = data->comm_master;
``
This should be reviewed

**Comment by erwango** [comment]
@avisconti , can you have a look?

**Comment by tbursztyka** [comment]
Ah, seems like I forgot that one when rebasing to add dev parameter again to spi functions. I can fix that

**Comment by avisconti** [comment]
> Ah, seems like I forgot that one when rebasing to add dev parameter again to spi functions. 
> I can fix that

@tbursztyka 
OK, good. I was looking into that, but for you it is definitely easier, as you know the SPI API evolution
