### ISSUE TITLE
mimxrt1010_evk:  board does not work well after HWv2 upgrading

### ISSUE THREAD

**Issue by hakehuang** [zephyrproject-rtos/zephyr#70090]
**Describe the bug**

after the v3.6.0-312-g8dc3f856229 HWv2 integrate, mimxrt1010_evk can not runs well after download, there is no serial output for hello_world after `west flash`. But it is ok if I run `west debug` and then `c`.  this issue is also found in latest code bases(v3.6.0-735-ga10b8429916)

**To Reproduce**
west build -b mimxrt1010_evk samples/hello_world

**Expected behavior**
serial console has 'Hello World' output

**Impact**
mimxrt1010_evk platforms

**Logs and console output**

there is no outputs

**Environment (please complete the following information):**
 - OS: (e.g. Linux, MacOS, Windows)
 - Toolchain (e.g Zephyr SDK, ...)
 - Commit SHA or Version used: v3.6.0-735-ga10b8429916

**Comment by danieldegrasse** [comment]
> @danieldegrasse @dleach02 , it is very strange failure, west debug works. looks like something wrong with the flash config staff

Looks like the FCB needs to be at 0x400 on this part, not 0x0 (like the remainder of the RT10xx series)
