### ISSUE TITLE
Bluetooth extended advertising not work on STM32WB55

### ISSUE THREAD

**Issue by rokobert** [zephyrproject-rtos/zephyr#70161]
**Describe the bug**
I'm noticed that extended advertising not work on STM32WB55. It is tested on Nucleo-WB55 board with Zephyr 3.6.0 and stm32wb5x_BLE_HCILayer_extended_fw.bin V1.18.0 on radio CPU2.
If I using normal advertising it is work.

Warning is produced calling function "bt_hci_cmd_send_sync" at "bluetooth/host/adv.c" line 1214.
And exactly at "bluetooth/host/hci_core.c" line 333.
	status = cmd(buf)->status;
	if (status) {
		LOG_WRN("opcode 0x%04x status 0x%02x", opcode, status);
		net_buf_unref(buf);

**Logs and console output**
Here is part of log:
0:00:00.025,000] <inf> blecpp: BLE device INIT
[00:00:00.025,000] <inf> blecpp: Start BLE app
[00:00:00.051,000] <inf> bt_hci_core: Identity: 02:80:E1:00:00:00 (public)
[00:00:00.051,000] <inf> bt_hci_core: HCI: version 1.0b (0x00) revision 0x8077, manufacturer 0x0030
[00:00:00.051,000] <inf> bt_hci_core: LMP: version 1.0b (0x00) subver 0x2177
[00:00:00.051,000] <wrn> bt_hci_core: opcode 0x2036 status 0x01
[00:00:00.051,000] <err> blecpp: Advertising ext. create failed(err -5)

**Environment (please complete the following information):**
 - OS: (MacOS aarch64)
 - Toolchain (Zephyr SDK)
 - Zephyr V3.6.0

**Comment by hermabe** [comment]
> [00:00:00.051,000] bt_hci_core: opcode 0x2036 status 0x01

This is the error "Unknown command", check that you have enabled support in the controller or contact your controller vendor.

**Comment by erwango** [comment]
This feature is not implemented. See https://github.com/zephyrproject-rtos/zephyr/issues/51430

**Comment by rokobert** [comment]
@erwango, thank you for answer. Sorry for not search open issues.
Since there is no date when this features will be implemented I have a question.
Is it possible to implement under Zephyr RTOS STM32 Bluetooth SDK?
In short. Using "stm32wb5x_BLE_Stack_full_extended_fw.bin" on CPU2, use source code from STM32CUBE_WB SDK and integrate into Zephyr app. Is there any guides yet?

**Comment by erwango** [comment]
> In short. Using "stm32wb5x_BLE_Stack_full_extended_fw.bin" on CPU2, use source code from STM32CUBE_WB SDK and integrate into Zephyr app. Is there any guides yet?

No, but [here](https://github.com/zephyrproject-rtos/zephyr/discussions/62001) you'll find a discussion about preliminary work. You could ping guys there to know what is their status and if they're willing to collaborate and upstream a solution with your help.
