### ISSUE TITLE
twister: --no-update option, wrong or old help explanation

### ISSUE THREAD

**Issue by pkunieck** [zephyrproject-rtos/zephyr#70173]
**Describe the bug**
When calling for twister help option, there is explanation of "-u, --no-update" flag, but it's either wrong or old. It needs to be more clear, or updated. 

**To Reproduce**
twister --help

**Expected behavior**
Clear explanation of what exactly this option do. 

**Impact**
annoyance

**Logs and console output**
  -u, --no-update       Do not update the results of the last run of twister.

**Environment (please complete the following information):**
 - OS Linux

**Comment by nashif** [comment]
ok, that is no bug, this option is an old one, but still works as expected, basically with this option we do not override the the test results in he current tree. will submit a PR to clarify
