### ISSUE TITLE
HTTP Server crashes on native posix

### ISSUE THREAD

**Issue by oxalistriangularis** [zephyrproject-rtos/zephyr#7022]
HTTP Server crashes on native POSIX target on http_server_init - console output below.

```
[net/app] [ERR] net_app_init: No network interfaces
[net/app] [ERR] init_net_app: Network initialization failed (-19)
[http/server] [DBG] http_server_add_url: (0x080e66e0): [0] HTTP URL /headers
[http/server] [DBG] http_server_add_url: (0x080e66e0): [1] HTTP URL /index.html
[http/server] [DBG] http_server_add_url: (0x080e66e0): [2] HTTP URL /
[http/server] [INF] new_server: Zephyr HTTP Server (0x080d22e0)
Segmentation fault (core dumped)
```

Debug shows that the problem is NULL pointer access on net_sin(&ctx->local)->sin_port = htons(port) from init_net (ctx=0x80d22e0 <http_ctx>, server_addr=0x0, port=80) at /home/khalbali/data/kalaghoda/zephyr/subsys/net/lib/http/http_server.c:840.

My suspicion is the mismatch in sockaddr structure on various platforms. This may be a good reason to align the structures.

**Comment by jukkar** [comment]
> [net/app] [ERR] net_app_init: No network interfaces

The crash happens because of this, not because of sockaddr stuff.

**Comment by jukkar** [comment]
Works for me, just tried http-server sample application with native_posix target. Notice that you need to run the binary as a root in order to create the zeth network interface in the host side.

```
cd samples/net/http_server
mkdir build && cd build
cmake -DBOARD=native_posix ..
make
sudo --preserve-env=ZEPHYR_BASE zephyr/zephyr.exe
```

After this I was able to connect to 192.0.2.1:80 from host side.
