### ISSUE TITLE
ESP32 DAC: Incorrect Clock Initialization

### ISSUE THREAD

**Issue by ku3mich** [zephyrproject-rtos/zephyr#70295]
Zephyr crashes during the initialization of the DAC with an ESP32-DEVKITC-WROOM Development Kit.

incorrect parameter pass

```
(clock_control_subsys_t) &cfg->clock_subsys
should be
cfg->clock_subsys
```

in `static int dac_esp32_init(const struct device *dev)`  `dac_esp32.c` should be
```
	if (clock_control_on(cfg->clock_dev, cfg->clock_subsys) != 0) {
		LOG_ERR("DAC clock setup failed (%d)", -EIO);
		return -EIO;
	}
```

To Reproduce

I use the DAC example from Zephyr.

west build -p always -b esp32_devkitc_wroom samples/drivers/dac/
west flash

See Error

Expected behavior

Zephyr should not crash during initialization of the DAC.

Impact
Showstopper

Logs and console output

```
assertion "periph < PERIPH_MODULE_MAX" failed: file "WEST_TOPDIR/modules/hal/espressif/components/driver/periph_ctrl.c", line 30, function: periph_module_enable
abort()


Backtrace:0x40080988:0x3ffe6520 0x400d2593:0x3ffe6530 0x400822ff:0x3ffe6550 0x400d2351:0x3ffe6580 0x400d2bbd:0x3ffe65a0 0x400d2dc5:0x3ffe65c0 0x40081086:0x3ffe65e0 0x400810bd:0x3ffe6600 0x400d0477:0x3ffe6620
```

**Comment by aescolar** [comment]
@ku3mich Would you want to send a PR?
