### ISSUE TITLE
Provide a way to mark System workqueue thread as K_ESSENTIAL

### ISSUE THREAD

**Issue by ExtremeGTX** [zephyrproject-rtos/zephyr#70293]
**Is your enhancement proposal related to a problem? Please describe.**
When system is highly dependent on system workqueue, (for example multiple drivers defer interrupt work to be done later by system workqueue) if the system workqueue thread crashed then a reboot is needed to get the system back up and running and there is no point in continuing to operate in such state.

**Describe the solution you'd like**
The Best solution would be to make use of Zephyr `K_ESSENTIAL` flag. so when sysworkq thread crash the fault handler can act accordingly for all essential threads in the system without special `if` statements or trying to match thread name to do special handling.

**Describe alternatives you've considered**
use `k_thread_foreach` to loop over all threads to find the sysworkq thread by its name then act.

**Additional context**
Add any other context or graphics (drag-and-drop an image) about the feature request here.

**Comment by ExtremeGTX** [comment]
@henrikbrixandersen Should I make it configurable via KCONFIG ?

**Comment by henrikbrixandersen** [comment]
> @henrikbrixandersen Should I make it configurable via KCONFIG ?

I don't see why the system work queue thread would not be essential. I am actually surprised it is not marked as such already. I'd go for a solution without a Kconfig unless others can come up with a good reason for making it configurable.
