### ISSUE TITLE
dts: bindings: ethernet-fixed-link.yaml: Ethernet fixed link requires hardcoding node labels in drivers

### ISSUE THREAD

**Issue by decsny** [zephyrproject-rtos/zephyr#70323]
**Problem**
Ethernet fixed link scheme causes node label to need to be hardcoded into drivers.

**Describe the solution you'd like**
Remove ethernet-fixed-link.yaml and describe all phys properly in DT.

**Describe alternatives you've considered**
- Have a compatible on the fixed link node and find the node from that.
- Make the fixed link parameters optional properties on the ethernet controller node instead of making a child node.

**Comment by henrikbrixandersen** [comment]
A DTS code example in this report could help others to understand the nature of this issue.
