### ISSUE TITLE
McuBoot Build Error When Serial Recovery is enabled

### ISSUE THREAD

**Issue by AlbertPJoshi** [zephyrproject-rtos/zephyr#70352]
This issue list is only for bugs in the main Zephyr code base
(https://github.com/zephyrproject-rtos/zephyr/). If the bug is for a project
fork (such as NCS) specific feature, please open an issue in the fork project
instead.

**Describe the bug**
It seems like it is trying to use both zcbor from mcuboot and zcbor from zephyr.

Please also mention any information which could help others to understand
the problem you're facing:
 - Tried to build for frdm_k64, nrf52840_dongle

**To Reproduce**
Followed Instructions from [here](https://docs.mcuboot.com/readme-zephyr.html)

**Expected behavior**
Successful Build of McuBoot

**Logs and console output**
Console Output during Build

```
warning: ZCBOR (defined at modules/zcbor/Kconfig:7, modules/zcbor/Kconfig:7) has direct dependencies ZEPHYR_ZCBOR_MODULE || (ZEPHYR_ZCBOR_MODULE && 0) with value n, but is currently being y-selected by the following symbols:
- MCUBOOT_SERIAL (defined at /home/devuser/NrfMcuBootTest/my-workspace/bootloader/mcuboot/boot/zephyr/Kconfig.serial_recovery:7), with value y, direct dependencies y (value: y)
 
error: Aborting due to Kconfig warnings

```

**Environment (please complete the following information):**
 - OS:  Linux

**Comment by nordicjm** [comment]
You do not have zcbor in your manifest, add it to your manifest and run `west update`
