### ISSUE TITLE
Bluetooth: The work `struct bt_conn::tx_complete_work`  cannot be submitted due to the flag K_WORK_CANCELING_BIT of k_sys_work_q is set

### ISSUE THREAD

**Issue by lylezhu2012** [zephyrproject-rtos/zephyr#70353]
**Describe the bug**

After the hci_num_completed_packets is received, the pending conn_tx will be appeded to the queue `struct bt_conn::tx_complete`. And the work `struct bt_conn::tx_complete_work` will be submitted.
But the work `struct bt_conn::tx_complete_work`  cannot be submitted due to the flag K_WORK_CANCELING_BIT of k_sys_work_q is set. 
When the issue occurs, the error code `-EBUSY` will be returned by `k_work_submit(&conn->tx_complete_work);` in function `hci_num_completed_packets` of file `hci_core.c`. While the error code is ignored by the function `hci_num_completed_packets`.

Because the error code is ignored, this causes the Bluetooth Host stack to hang.

![image](https://github.com/zephyrproject-rtos/zephyr/assets/47838210/bd2cc5d2-4198-42b1-bfd0-d397eeaa9e02)
Form the debug log, there are three conn_tx nodes 0x5659aa80,0x5659aa60,0x5659aa70 completed. 

![image](https://github.com/zephyrproject-rtos/zephyr/assets/47838210/e7e72db2-35b2-4c54-a11b-afa6deafe4eb)
After check all appended note of `struct bt_conn::tx_complete`, all of these nodes are appended.

![image](https://github.com/zephyrproject-rtos/zephyr/assets/47838210/da2f3f6f-abfc-471e-ab50-9b9d069986cc)
Meanwhile, the BIT K_WORK_CANCELING_BIT of `flags` is set in `k_sys_work_q`.

**Comment by jori-nordic** [comment]
Is this for classic or LE?

**Comment by lylezhu2012** [comment]
> Is this for classic or LE?

I found this issue in BR/EDR examples. However, I think this issue should not be unique to BE/EDR. From a code perspective, the function `hci_num_completed_packets` does not capture and handle all possible exceptions.

**Comment by jhedberg** [comment]
@lylezhu2012 do you have a fix proposal?

**Comment by lylezhu2012** [comment]
> @lylezhu2012 do you have a fix proposal?

After in-depth research, I found that the cause of the issue was inconsistent with my previous description. The work work `struct bt_conn::tx_complete_work` has been submitted, but it is not executed. The system work queue is in canceling state. The pending work is not executed normally.
The function `bt_conn_create_pdu_timeout` is called in system work queue thread context. It blocks the thread of `k_sys_work_q`. It make the system work queue to hang.
It seams the wrong usage. The function `bt_conn_create_pdu_timeout` cannot be called in context of the thread of `k_sys_work_q`.
