### ISSUE TITLE
nRF ASYNC UART driver receive off by one byte 

### ISSUE THREAD

**Issue by pres2300** [zephyrproject-rtos/zephyr#70387]
**Describe the bug**
If the UART is busy at boot (i.e. on a bus situation) and the nRF boots, the UART can report `UART_RX_RDY` events with data that are off by one byte.

Please also mention any information which could help others to understand
the problem you're facing:
Platform: nRF52840
SDK: v2.5.1

This issue has only been observed when we boot the nRF52840 with RX traffic already present on the UART.  This is possible for our use case as we are connecting devices to an RS485 bus with a transceiver connected to the nRF's UART (i.e. traffic can already be present from other devices).  We are using an ASYNC UART driver with HW timers enabled and a short rx_timeout interval to detect received data.  On occasion, the nRF will boot and report received data that appears off by one byte.  The data is missing the first byte of actual data, and the last byte seems to be whatever data was already present on the receive buffer in that location.  The receive length appears correct, but the data appears shifted by one byte.

**To Reproduce**

1. Connect an nRF52840 via UART to another device (i.e. PC with FTDI cable)
2. Load firmware on the nRF52840 that reports data received over an ASYNC UART with HW timers enabled (i.e. reports via RTT)
3. Hold the nRF in reset
4. Start transmitting varying data on the other device to the nRF
5. Release the nRF52840 from reset
6. The nRF may report data that is missing the first received byte

It can be helpful to have an rx_timeout defined that the other device transmitting data to the nRF abides by.  That is, it sends a few bytes, waits a millisecond or two, and then sends another few bytes.  This can also make it easier to verify the received data is off by one byte when received by the nRF.

**Expected behavior**
As the nRF can boot to existing traffic being transmitted to it, I would expect that the first few bytes received will cause an error at the application layer since a partial packet will be received and it will violate checks such as length or CRC.  However, after that I would expect the application to recover on subsequent received data.  This does not appear to be the case with this bug as all `UART_RX_RDY` events will be missing the first byte and have seemingly random data as the last byte.

**Impact**
We can recover the device by resetting it, but we intend to have thousands deployed and it would make it non-functional if this bug occurs and resetting is difficult when deployed.

**Logs and console output**
Log from RTT:
```
E: RX Data
E: 01 00 a0 11 00 
```

Actual sent data (this is sent every 1 to 2 ms on our bus):
<img width="524" alt="Screenshot 2024-03-18 at 9 47 26 AM" src="https://github.com/zephyrproject-rtos/zephyr/assets/1944835/46fa618a-812b-472a-b7c0-8687b7597ed7">

**Environment (please complete the following information):**
 - OS: MacOS
 - Toolchain: NCS v2.5.1

**Additional information**
This appears to be the same bug reported in [this devzone post](https://devzone.nordicsemi.com/f/nordic-q-a/100737/zephyr-uart-async-receive-drops-a-single-character).

**Comment by aescolar** [comment]
@pres2300 This bug report seems to be related to Nordic's SDK, if this bug is applicable to Zephyr please provide a reproduction case with just vanilla Zephyr.
CC @carlescufi
