### ISSUE TITLE
LED: ti,lp5562 driver ignores vin-supply and supply-gpio device tree settings

### ISSUE THREAD

**Issue by timKnodel** [zephyrproject-rtos/zephyr#70397]
**Describe the bug**
The TI LP5562 driver binding includes the i2c-device binding, which in turn includes the power binding. This binding specifies a vin-supply for a power regulator and supply-gpios for a power enable GPIO for the device. The driver does not do anything with these device tree arguments.

**To Reproduce**
Create an instance of an ti,lp5562 device.
Set the vin-supply and supply-gpios values.
Compile the blinky app.
The regulator will not be turned on, and the GPIO will not be set.

**Expected behavior**
The driver should enable power to the LP5562 before trying to communicate with it over I2C.

**Comment by simonguinot** [comment]
A fixed regulator should be used.
