### ISSUE TITLE
Zephyr's Kconfig implementation should not behave subtly differently from Linux

### ISSUE THREAD

**Issue by SebastianBoe** [zephyrproject-rtos/zephyr#7054]
Zephyr's Kconfig implementation diverges from Linux by prefering later defaults. This is a problem for several reasons:

### Problem description

Zephyr can no longer rely on the existing Kconfig ecosystem for documentation. Everything in the Linux kernel's Kconfig documentation applies to Zephyr's Kconfig except that the documentation is wrong when it states that earlier defaults have precedence.

The divergence must be implemented in Kconfig tools. Currently this is done with an out-of-tree patch on kconfiglib that is expensive to maintain.

Readers already familiar with the original Kconfig language will read Zephyr Kconfig files incorrectly. The above two issues are resolvable without aligning with Linux, but this is not.

### Problem solutions

The cleanest solution is simply to follow the Linux kernel's behaviour. But to do this
it must be better understood why the divergence occured and what the alternatives for diverging were. @ulfalizer has already looked into this here (https://github.com/zephyrproject-rtos/zephyr/issues/6890#issuecomment-377946637), so we have some idea of why the divergence occured, but our options for re-aligning are not well understood.

**Comment by ulfalizer** [comment]
The documentation added in https://github.com/zephyrproject-rtos/zephyr/pull/7199 mentions that Zephyr's Kconfig prefers later defaults. Do you think that's enough?

Might be easy to miss, but it's a big improvement from nothing at least. :)

**Comment by SebastianBoe** [comment]
It helps :)

But it would still be better to avoid this patch. I will re-write this issue from a doc bug to an enhancement.

**Comment by SebastianBoe** [comment]
@ulfalizer : Any ideas on how to align?

I assume that simply re-ordering and doing:

> config FOO
>   default 42
> 
> config FOO
>   int
>   default 32
> 

instead of

> config FOO
>   int
>   default 32
> 
> config FOO
>   default 42
> 



is not valid?

**Comment by ulfalizer** [comment]
@SebastianBoe 
Yeah, I've also been thinking about whether you can simply switch them around. Think it might work.

One messy thing is that many symbols already have many `default`s in the same location and depend on the prefer-later-defaults behavior. Might be a lot of stuff that would need to be fixed.

**Comment by SebastianBoe** [comment]
This has been fixed.
