### ISSUE TITLE
scripts: extract_dts_includes: fails on multiple includes in yaml bindings file

### ISSUE THREAD

**Issue by b0661** [zephyrproject-rtos/zephyr#7067]
Inheriting from multiple bindings fails.

    inherits:
        !include [binding1.yaml, binding2.yaml]

Following the above the 'node_type' node property does not account for multiple base types.

Loader.include for yaml.SequenceNode and yaml_traverse_inherited seems to be broken.

**Comment by galak** [comment]
@erwango can you look into this issue.

**Comment by erwango** [comment]
@b0661 : In order to solve this is a coherent way, do you have any example of use for multiple bindings inclusion?

**Comment by erwango** [comment]
@b0661 : Is that ok if we set this ticket as 'enhancement' instead of 'bug'? (Medium priority 'bug' issues are blocking for upcoming release)
This is blocking further advanced development but not breaking anything currently.

**Comment by b0661** [comment]
@erwango 

>Is that ok if we set this ticket as 'enhancement' instead of 'bug'?

Yes, shure it is ok to set it to 'enhancement'.
