### ISSUE TITLE
build warning on  cast removes address space '__cache' of expression

### ISSUE THREAD

**Issue by kv2019i** [zephyrproject-rtos/zephyr#70725]
**Describe the bug**
Sparse warning on use of __cache attribute:

https://github.com/thesofproject/sof/actions/runs/8422916305/job/23063323303?pr=8981

 /zep_workspace/zephyr/soc/intel/intel_adsp/ace/power.c:46:12: warning: cast removes address space '__cache' of expression
/zep_workspace/zephyr/soc/intel/intel_adsp/ace/power.c:48:9: warning: incorrect type in argument 1 (different address spaces)
Regression in 

**To Reproduce**
https://github.com/thesofproject/sof/actions/runs/8422916305/job/23063323303?pr=8981

**Expected behavior**
No sparse warnings on __cache attribute usage.

**Impact**
Build warning

**Logs and console output**
https://github.com/thesofproject/sof/actions/runs/8422916305/job/23063323303?pr=8981

**Environment (please complete the following information):**
 - https://github.com/thesofproject/sof/actions/runs/8422916305/job/23063323303?pr=8981
 
**Additional context**
Regression in commit 6b9d01f995c72d1c747a98dbc866d052a0f29cb0  . Seems cache_data_flush_range() does not have cache attributes.

**Comment by nashif** [comment]
@ceolin  can you please take a look?

**Comment by ceolin** [comment]
> @nashif , @ceolin can we add this check to either [`main`/.github](https://github.com/zephyrproject-rtos/zephyr/tree/main/.github?rgh-link-date=2024-03-28T16%3A02%3A06Z) or Internal Intel CI? Either would shorten the feedback loop considerably.
> 
> The required dependencies are small:
> 
> [thesofproject/sof@0698fa334ae16b7709f08](https://github.com/thesofproject/sof/commit/0698fa334ae16b7709f08)

I think so ... also we probably need to have our sparse fork. The way it is on Zephyr right now assumes that you can get any sparse (from your distro for example) and it will work

**Comment by marc-hb** [comment]
> > [thesofproject/sof@0698fa334ae16b7709f08](https://github.com/thesofproject/sof/commit/0698fa334ae16b7709f08)

> I think so ... also we probably need to have our sparse fork. 

- Compile a reasonably recent version from the sparse main branch: yes. This is trivial, see link above.
- "Fork": no, not needed any more. We worked with the sparse maintainer and sparse now works with Zephyr out of the box.

All what's required is at the link above, it's pretty short.
