### ISSUE TITLE
[Coverity CID: 185284] Error handling issues in /subsys/settings/src/settings_fcb.c

### ISSUE THREAD

**Issue by Shilpashree3lc** [zephyrproject-rtos/zephyr#7080]
Static code scan issues seen in File: /subsys/settings/src/settings_fcb.c
 Category: Error handling issues
 Function: settings_fcb_compress
 Component: Other
 CID: 185284
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by nvlsianpu** [comment]
fixed in #7093
