### ISSUE TITLE
doc: Documentation issue in 'boards/arduino/uno_r4_minima/doc/index'

### ISSUE THREAD

**Issue by Gerriko** [zephyrproject-rtos/zephyr#70808]
**Describe the bug**

The documentation states the following "You can build and flash an application in the usual way".

However, when I use the command `west flash` it expects pyocd to be connected. I was not expecting this to be the "usual way", as in I was expecting the usual way to mean via a bootloader and usb. 

```
-- west flash: rebuilding
ninja: no work to do.
-- west flash: using runner pyocd
-- runners.pyocd: Flashing file: /home/bigg/zephyrproject/zephyr/build/zephyr/zephyr.hex

```

It eventually times out with an error.

Hence, either I have done something wrong (expecting the device to be flashed via usb), or I have misinterpreted the documentation (as in I thought it could be flashed via usb). 

If this is the correct behaviour, it would be helpful if further clarification could be added to the documentation. Thanks.

**Environment**

Linux OS (22.04 Ubuntu).

* Page: `boards/arduino/uno_r4_minima/doc/index`
* Version: main
* SHA-1: 8dc3f856229ce083c956aa301c31a23e65bd8cd8

**Comment by soburi** [comment]
It may was misleading expression.
I was writing this on the assumption that using a debugger is the general method for Zephyr.
Change to explicit expression.
