### ISSUE TITLE
[Coverity CID:185283] Control flow issues in /subsys/fs/nffs_fs.c

### ISSUE THREAD

**Issue by Shilpashree3lc** [zephyrproject-rtos/zephyr#7081]
Static code scan issues seen in File: /subsys/fs/nffs_fs.c
 Category: Control flow issues
 Function: nffs_tell
 Component: Other
 CID: 185283
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by lpereira** [comment]
Fixed by #7068
