### ISSUE TITLE
[Coverity CID: 185282] Error handling issues in /subsys/settings/src/settings_init.c

### ISSUE THREAD

**Issue by Shilpashree3lc** [zephyrproject-rtos/zephyr#7082]
Static code scan issues seen in File: /subsys/settings/src/settings_init.c
 Category: Error handling issues
 Function: settings_subsys_init
 Component: Other
 CID: 185282
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by nvlsianpu** [comment]
fixed in #7093
