### ISSUE TITLE
[Coverity CID: 185281] Null pointer dereferences in /kernel/posix/mqueue.c

### ISSUE THREAD

**Issue by Shilpashree3lc** [zephyrproject-rtos/zephyr#7083]
Static code scan issues seen in File: /kernel/posix/mqueue.c
 Category: Null pointer dereferences
 Function: mq_getattr
 Component: Kernel
 CID: 185281
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by ramakrishnapallala** [comment]
@Shilpashree3lc issue is not valid anymore. we can close this.
