### ISSUE TITLE
LE Audio: Add `create_by_broadcast_name` for the broadcast sink shell

### ISSUE THREAD

**Issue by Thalley** [zephyrproject-rtos/zephyr#70837]
**Is your enhancement proposal related to a problem? Please describe.**
There are 2 typical ways of identifying a broadcast source as a person: By broadcast Id or by broadcast name. 

The broadcast sink already has `create_broadcast_sink` that uses the broadcast ID, but could use a `create_by_broadcast_name` as well that works similarly (or a way to specify whether to scan for broadcast ID or name in the `create_broadcast_sink` command), but matches on name instead of broadcast ID. 

**Describe the solution you'd like**
Add a `create_by_broadcast_name` command that scan for broadcast sources has `BT_DATA_BROADCAST_NAME` that matches with whatever name is given to the shell command. 

**Describe alternatives you've considered**
Modify `create_broadcast_sink` to take either a broadcast ID or a name. 

**Additional context**
N/A

**Comment by babrsn** [comment]
@Thalley please assign it to @babrsn
