### ISSUE TITLE
LE Audio: `bap list` should also show the states of each stream/endpoint

### ISSUE THREAD

**Issue by Thalley** [zephyrproject-rtos/zephyr#70838]
**Is your enhancement proposal related to a problem? Please describe.**
The `bap list` command is a nice way to get an overview of the existing streams and endpoints, but it does not show the states of them, which makes it hard to tell what commands can be done on which streams. 

**Describe the solution you'd like**
The command should use the `bt_bap_ep_get_info` to get the state of each stream/endpoint and show that as well. 

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by jthm-ot** [comment]
I will take a look at this issue
