### ISSUE TITLE
[Coverity CID: 185280] Error handling issues in /tests/posix/pthread_rwlock/src/posix_rwlock.c

### ISSUE THREAD

**Issue by Shilpashree3lc** [zephyrproject-rtos/zephyr#7084]
Static code scan issues seen in File: /tests/posix/pthread_rwlock/src/posix_rwlock.c
 Category: Error handling issues
 Function: test_rw_lock
 Component: Tests
 CID: 185280
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by sritej20** [comment]
Can anyone assign this issue to me so i can push the changes ?
