### ISSUE TITLE
check_compliance.py complains about `LV_*` being without types in `stm32h7b3i_dk` board's `Kconfig.defconfig`

### ISSUE THREAD

**Issue by dcpleung** [zephyrproject-rtos/zephyr#70859]
**Describe the bug**
When running `check_compliance.py` locally, it complains that
```
warning: LV_USE_GPU_STM32_DMA2D (defined at boards/st/stm32h7b3i_dk/Kconfig.defconfig:25) defined without a type
warning: LV_GPU_DMA2D_CMSIS_INCLUDE (defined at boards/st/stm32h7b3i_dk/Kconfig.defconfig:28) defined without a type
```

These were added via commit a0ddba5faa750b35cdc60949034b54544a79a612.

**To Reproduce**
1. scripts/ci/check_compliance.py -e KconfigBasic --annotate -c main..
2. See error

**Expected behavior**
No warning.

**Impact**
Simply annoyance as it used to have no warnings.

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: Zephyr SDK 0.16.5
 - Commit cb331c2371144f3c391856eec4417ce65cbf0957

**Comment by faxe1008** [comment]
Opened this PR which should resolve the issue: [https://github.com/zephyrproject-rtos/zephyr/pull/71313](https://github.com/zephyrproject-rtos/zephyr/pull/71313)
