### ISSUE TITLE
[Coverity CID: 185279] Resource leaks in /tests/net/socket/getaddrinfo/src/main.c

### ISSUE THREAD

**Issue by Shilpashree3lc** [zephyrproject-rtos/zephyr#7085]
Static code scan issues seen in File: /tests/net/socket/getaddrinfo/src/main.c
 Category: Resource leaks
 Function: test_getaddrinfo_no_host
 Component: Tests
 CID: 185279
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by pfalcon** [comment]
@stig-bjorlykke: As the author of this test, would you like to have a look/try to do something? If there're any issues, just let me know and I'll cover it. Thanks.

(Similar to https://github.com/zephyrproject-rtos/zephyr/issues/7091)
