### ISSUE TITLE
[Coverity CID: 185278] Null pointer dereferences in /samples/net/coap_server/src/coap-server.c

### ISSUE THREAD

**Issue by Shilpashree3lc** [zephyrproject-rtos/zephyr#7086]
Static code scan issues seen in File: /samples/net/coap_server/src/coap-server.c
 Category: Null pointer dereferences
 Function: test_put
 Component: Samples
 CID: 185278
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by rveerama1** [comment]
https://github.com/zephyrproject-rtos/zephyr/pull/7223 fixes issue.
