### ISSUE TITLE
[Coverity CID: 185275] Integer handling issues in /kernel/posix/pthread_common.c

### ISSUE THREAD

**Issue by Shilpashree3lc** [zephyrproject-rtos/zephyr#7089]
Static code scan issues seen in File: /kernel/posix/pthread_common.c
 Category: Integer handling issues
 Function: timespec_to_timeoutms
 Component: Kernel
 CID: 185275
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by ramakrishnapallala** [comment]
not valid anymore, closing this issue.
