### ISSUE TITLE
[Coverity CID: 185274] Error handling issues in /subsys/settings/src/settings_store.c

### ISSUE THREAD

**Issue by Shilpashree3lc** [zephyrproject-rtos/zephyr#7090]
Static code scan issues seen in File: /subsys/settings/src/settings_store.c
 Category: Error handling issues
 Function: settings_store_one
 Component: Other
 CID: 185274
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by nvlsianpu** [comment]
fixed in https://github.com/zephyrproject-rtos/zephyr/pull/7093
