### ISSUE TITLE
cortex_m_systick issue

### ISSUE THREAD

**Issue by hongshui3000** [zephyrproject-rtos/zephyr#70916]
cortex_m_systick.c
I actually use cortex_m_systick.c,
If I call the following function in my code
```
void sys_clock_disable(void)
{
SysTick->CTRL &= ~SysTick_CTRL_ENABLE_Msk;
}
```
when, I wanted to restore the clock, but I found that the driver didn't have any interface that allowed me to do this.

For example, if I call the following function, it will be because of last_load! = TIMER_STOPPED and could not successfully open the clock
```
void sys_clock_idle_exit(void)
{
	if (last_load == TIMER_STOPPED) {
		SysTick->CTRL |= SysTick_CTRL_ENABLE_Msk;
	}
}
```

**Comment by henrikbrixandersen** [comment]
Please use our bug template when reporting bugs. You need to edit this issue to include the information requested in https://github.com/zephyrproject-rtos/zephyr/blob/main/.github/ISSUE_TEMPLATE/001_bug_report.md
