### ISSUE TITLE
net: mr_canhubk3: build failure

### ISSUE THREAD

**Issue by hakehuang** [zephyrproject-rtos/zephyr#70955]
**Describe the bug**

<html>
<body>

CASE_NAME | ZEPHYR_VERSION | RESULT | PLATFORM | TEST_PATH
-- | -- | -- | -- | --
sample.net.sockets.net_mgmt.usermode | v3.6.0-1947-g0714052c74bf | Build failure | mr_canhubk3 | samples/net/sockets/net_mgmt

</body>
</html>

Please also mention any information which could help others to understand
the problem you're facing:
 - What target platform are you using?
 mr_canhubk3
 - What have you tried to diagnose or workaround this issue?
 add CONFIG_MAX_THREAD_BYTES=3 in the prj.conf
 - Is this a regression? If yes, have you been able to "git bisect" it to a
   specific commit? @jukkar (5c3fa85bc829)

```
5c3fa85bc829e1a90df80e0052453baa881d1309 is the first bad commit
commit 5c3fa85bc829e1a90df80e0052453baa881d1309
Author: Jukka Rissanen <jukka.rissanen@nordicsemi.no>
```

**To Reproduce**

west build -b mr_canhubk3 samples/net/sockets/net_mgmt

**Expected behavior**
build pass

**Impact**
networking support

**Logs and console output**

```
[413/430] Generating kobject_prebuilt_hash.gperf
FAILED: zephyr/kobject_prebuilt_hash.gperf /home/jenkins/agent/workspace/bitbucket_build_platform/zephyr/twister-out/mr_canhubk3/samples/net/sockets/net_mgmt/sample.net.sockets.net_mgmt.usermode/zephyr/kobject_prebuilt_hash.gperf 
cd /home/jenkins/agent/workspace/bitbucket_build_platform/zephyr/twister-out/mr_canhubk3/samples/net/sockets/net_mgmt/sample.net.sockets.net_mgmt.usermode/zephyr && /usr/bin/python /home/jenkins/agent/workspace/bitbucket_build_platform/zephyr/scripts/build/gen_kobject_list.py --kernel /home/jenkins/agent/workspace/bitbucket_build_platform/zephyr/twister-out/mr_canhubk3/samples/net/sockets/net_mgmt/sample.net.sockets.net_mgmt.usermode/zephyr/zephyr_pre0.elf --gperf-output kobject_prebuilt_hash.gperf --include-subsystem-list /home/jenkins/agent/workspace/bitbucket_build_platform/zephyr/twister-out/mr_canhubk3/samples/net/sockets/net_mgmt/sample.net.sockets.net_mgmt.usermode/zephyr/misc/generated/struct_tags.json
Too many thread objects (18)
Increase CONFIG_MAX_THREAD_BYTES to 3
ninja: build stopped: subcommand failed.

INFO    - /home/jenkins/agent/workspace/bitbucket_build_platform/zephyr/twister-

```

**Environment (please complete the following information):**
 - OS: (e.g. Linux)
 - Toolchain (e.g Zephyr SDK, ...)
 - Commit SHA or Version used: v3.6.0-1947-g0714052c74bf

**Comment by jukkar** [comment]
Similar issue was recently fixed in commit c4216dd65c193fc40f6f3477fb0a4c504f87ba15
