### ISSUE TITLE
Contributor Nomination marwaiehm-st

### ISSUE THREAD

**Issue by erwango** [zephyrproject-rtos/zephyr#70995]
# Nomination

## GitHub User

Provide the following information about the GitHub user:

1. Full Name: Marwa IBEN EL HADJ MESSAOUD
1. GitHub username: marwaiehm-st
1. Organization (optional): ST-Microelectronics

## Supporting Documents

https://github.com/zephyrproject-rtos/zephyr/pull/70569
https://github.com/zephyrproject-rtos/zephyr/pull/69567

**Comment by stephanosio** [comment]
@marwaiehm-st has been invited as a contributor with "Triage" permission level.

**Comment by erwango** [comment]
Thanks @stephanosio
