### ISSUE TITLE
Bluetooth Configuration in MQTT sample 

### ISSUE THREAD

**Issue by dingiso** [zephyrproject-rtos/zephyr#71019]
Hi, 

in the [MQTT-based publisher](https://github.com/zephyrproject-rtos/zephyr/tree/main/samples/net/mqtt_publisher) example, I came across a Bluetooth configuration file named overlay-bt.conf. How this file can be used in a real-world environment? Additionally, is it possible for Bluetooth to operate over IPv6? If so, how can a border router be set up to convert raw Bluetooth packets into IPv6-based packets? 

Thanks,
Dingisoul

**Comment by jukkar** [comment]
That is the IPSP feature where IPv6 can be run on top of BT connection. IPSP is not very widely used and there is a proposal to remove it in https://github.com/zephyrproject-rtos/zephyr/issues/68629

**Comment by dingiso** [comment]
Thanks, I have received from the discord server too
