### ISSUE TITLE
Nominate myself for contributor role

### ISSUE THREAD

**Issue by dnltz** [zephyrproject-rtos/zephyr#71018]
# Background

The [TSC Project Roles] defines the main roles for the Zephyr Project, including
Maintainer, Collaborator, and Contributor.

By default anyone that contributes code or documentation is a Contributor, but
with the lowest [GitHub Permission Level] of Read. For example, Contributors
with Read permission do not have the permission to add reviewers to a pull
request.

Use this template to nominate a GitHub user for the Contributor role with
Triage permission level, which allows the user to add reviewers to a pull
request and be added as a reviewer by other users.

# Nomination

## GitHub User

Provide the following information about the GitHub user:

1. Daniel Schultz
1. dnltz
1. PHYTEC

## Supporting Documents

https://github.com/zephyrproject-rtos/zephyr/pull/62462
https://github.com/zephyrproject-rtos/zephyr/pull/60603
https://github.com/zephyrproject-rtos/zephyr/pull/57802

[TSC Project Roles]: <https://docs.zephyrproject.org/latest/project/project_roles.html>
[GitHub Permission Level]: <https://docs.github.com/en/organizations/managing-access-to-your-organizations-repositories/repository-roles-for-an-organization>

**Comment by stephanosio** [comment]
@dnltz has been invited as a contributor with "Triage" permission level.

**Comment by dnltz** [comment]
@stepanosio I'm now collaborator for the TI K3 Platforms (https://github.com/zephyrproject-rtos/zephyr/commit/b96b91c965ca48f2dc24f5e8dd8a0451b95a85cb). Should I open a new issue or can we re-use this one to increase my role?

**Comment by stephanosio** [comment]
@dnltz I have added you as a collaborator now.

**Comment by dnltz** [comment]
@stephanosio I'm maintainer of the `PHYTEC Platforms` now to manage PHYTEC boards. Is that already enough to grant me the maintainer role?

https://github.com/zephyrproject-rtos/zephyr/commit/836370f67cd0064817deacb3c4231d9976bfd54e

**Comment by stephanosio** [comment]
> @stephanosio I'm maintainer of the `PHYTEC Platforms` now to manage PHYTEC boards. Is that already enough to grant me the maintainer role?

Yes, I have added you as a maintainer now.
