### ISSUE TITLE
intel_adsp/cavs25: board hang after running kernel.timer.tickless

### ISSUE THREAD

**Issue by majunkier** [zephyrproject-rtos/zephyr#71027]
**Describe the bug**
After run the test case kernel.timer.tickless cavs25 board would run it and pass the testcase but any tests after this would fail due to timeout. Platform is not responsive and the only way to recover is to reboot the HW.

**To Reproduce**
```
twister -p intel_adsp/cavs25 --device-testing --hardware-map PATH-TO-HWMAP -s tests/kernel/timer/timer_api/kernel.timer.tickless

```
**Expected behavior**
Test should not hang platform

**Logs and console output**
`Output for this test is correct but all executed tests after this will got timeout status.`

**Environment (please complete the following information):**
```
 - OS: Linux
 - Toolchain: Zephyr
 - Version used: v3.6.0-2004-g8f9c28282b19
```

**Comment by ceolin** [comment]
Fixed with bafdbe8906d1dcf85833976615cea99d5061618a
