### ISSUE TITLE
Crash while running echo_server with openthread

### ISSUE THREAD

**Issue by vakulgarg** [zephyrproject-rtos/zephyr#7107]
I am trying echo_server sample on frdm_kw41z board with prj_frdm_kw41z_ot.conf.
The configuration crashes immediately upon startup.

> ***** HARD FAULT *****
>   Executing thread ID (thread): 0x20006f70
>   Faulting instruction address:  0x183a
> Fatal fault in ISR! Spinning...

The faulting instruction address is at:

> [b16394@lti frdm_kw41z]$ addr2line -e zephyr/zephyr.elf 0x183a
> /usr/src/debug/newlib/2.4.0-r0/newlib-2.4.0/newlib/libc/string/memcpy.c:107

**Comment by dleach02** [comment]
Identified source of crash. The original changes to enable KW41Z and OpenThread lost a set of changes related to FLASH device information. OT code is attempting to do a memcpy past the end of the flash device. PR is being prepared now.
