### ISSUE TITLE
doc: Documentation issue in 'develop/getting_started/index' on mac

### ISSUE THREAD

**Issue by toonst** [zephyrproject-rtos/zephyr#71101]
Since Openocd is not part of the SDK for mac, it should be installed through brew as well. This is currently not part of the installation instructions.

**Environment**

* Page: `develop/getting_started/index`
* Version: main
* SHA-1: 68eb97ea05450f3ebfd718470db84e42e988cbf6

**Comment by toonst** [comment]
PR here: https://github.com/zephyrproject-rtos/zephyr/pull/71103

**Comment by kartben** [comment]
fixed with #71103
