### ISSUE TITLE
LE Audio: BAP broadcast source does not store level 3 information in codec configuration

### ISSUE THREAD

**Issue by Thalley** [zephyrproject-rtos/zephyr#71125]
**Describe the bug**
When creating a BAP broadcast source with `bt_bap_broadcast_source_create`, only the subgroup information is stored in the streams when calling `broadcast_source_setup_stream`, and the remaining BIS specific information (where location is typically stored), is not stored in the `stream->codec_cfg`, which it should. 

**To Reproduce**
N/A

**Expected behavior**
Expect the `stream->codec_cfg` to contain the information for the specific stream, which is a union of the Level 2 (subgroup) and Level 3 (BIS) data in the BASE. 

**Impact**
Annoyance as it's harder to use the existing codec configuration helper functions. 

**Logs and console output**
N/A

**Environment (please complete the following information):**
 - Commit SHA or Version used: cd2c7874b95eed7505620534b4b216ef42b7ce2b

**Additional context**
This is a similar issue as was fixed for the broadcast sink in https://github.com/zephyrproject-rtos/zephyr/pull/69342

**Comment by niym-ot** [comment]
@Thalley Will start looking into the issue
