### ISSUE TITLE
samples: nrfx_prs: Failing after nrfx update

### ISSUE THREAD

**Issue by joerchan** [zephyrproject-rtos/zephyr#71154]
**Describe the bug**
The sample nrfx_prs appears to not have been updated after recent nrfx updates.
Following the sample I'm unable to communicate with my SPI device.

Sample was last working in NCS 2.4.x (nrfx 2.11.0).

In recent versions this fails even in init.
This looks to be just because the init function expects raw integer as frequency instead of NRF defines.
However with that change the transfer still fails, so probably more changes are needed in the sample.
There appears to be a different behavior in zephyr main branch compared to NCS 2.6.0 release.

**To Reproduce**
NCS 2.6.0
1. west build -b  nrf5340dk_nrf5340_cpuapp samples/boards/nrf/nrfx_prs
2. west flash --erase
3. Push button 2

```
*** Booting nRF Connect SDK v3.5.99-ncs1 ***
nrfx PRS example on nrf5340dk_nrf5340_cpuapp
-> press "Push button 1" to trigger a transfer
-> press "Push button 2" to switch the type of peripheral
Switched to SPIM
-- SPIM transfer --
Tx: 00 01 02 03 04 05 06 07 08 09
Rx: 00 00 00 00 00 00 00 00 00 00
nrfx_uarte_init() failed: 0x0bad0001
```

Zephyr commit cd685bdce82d.
```
*** Booting Zephyr OS build v3.6.0-2198-gcd685bdce82d ***
nrfx PRS example on nrf5340dk
-> press "Push button 1" to trigger a transfer
-> press "Push button 2" to switch the type of peripheral
nrfx_spim_init() failed: 0x0bad0004
```

**Expected behavior**
Sample should work.

**Impact**
SPI driver not working when sharing the serial box.

**Comment by joerchan** [comment]
Found the second problem I was having. Since I'm using SPI mode 3 the SCK needs to be set, this is missing from the sample.

**Comment by nashif** [comment]
This is not a zephyr upstream issue, please do not file issues of NCS upstream(zephyr), file those downstream (NCS).

**Comment by joerchan** [comment]
> This is not a zephyr upstream issue, please do not file issues of NCS upstream(zephyr), file those downstream (NCS).

It is a zephyr upstream issue. I've reproduced it first in NCS, and then in zephyr commit cd685bdce82d1d3843bcd56b67a086278e59e3e5.
