### ISSUE TITLE
Peripheral fails to disconnect on invalid central procedure collision handling

### ISSUE THREAD

**Issue by erbr-ot** [zephyrproject-rtos/zephyr#71249]
Peripheral device fails to disconnect when central initiates parameter request procedure after having sent PHY_UPDATE_IND but before instant.

This was found during UPF London, testing an Oticon peripheral device connected to a Windows Host central. 

Acting as peripheral, during local initiated phy update, if central initiates an incompatible parameter request after having replied with PHY_UPDATE_IND but before instant (ie before local procedure is complete) specification states the peripheral must disconnect.

Unittest covering this central behavior confirms the issue.

Fixed by:  https://github.com/zephyrproject-rtos/zephyr/pull/71221

**Comment by henrikbrixandersen** [comment]
Please use our bug template when reporting bugs. You need to edit this issue to include the information requested in https://github.com/zephyrproject-rtos/zephyr/blob/main/.github/ISSUE_TEMPLATE/001_bug_report.md
