### ISSUE TITLE
doc: Documentation issue in 'connectivity/networking/native_sim_setup'

### ISSUE THREAD

**Issue by Kwangbaek** [zephyrproject-rtos/zephyr#71243]
**Describe the bug**

"Using offloaded sockets" case, only IPv6 TCP test case('./echo_client -t 127.0.0.1') is working.

Need to revise the test scenario since only one TCP/UDP port, i.e., regardless of protocol family, is allowed to be binded on a single host for each protocol(IPv4 and IPv6 each).
In this example, "Using offloaded sockets" case, only IPv6 TCP test case is working at the moment.
Because both process_tcp6() and process_tcp4() is being called, IPv6 TCP socket(port 4242) is binded first and then IPv4 TCP socket(same port !, 4242), so IPv4 TCP socket bind failure happens.
Maybe, give some Kconfig option for IPv4 or IPv6 which is mutually exclusive could be an alternative.

![image](https://github.com/zephyrproject-rtos/zephyr/assets/151586840/c52ef5bc-a047-4ce2-961e-38e3a0754802)

One more thing is the tool('net-tools') should be built after fetching from the Git repository.

<< Please describe the issue here >>
1. 'Using offloaded sockets' case, the test is working only for IPv6 TCP case.
2. 'net-tools' should be built by running 'make' before running an 'echo-client' command.

<< You may also want to update the automatically generated issue title above. >>

**Environment**

* Page: `connectivity/networking/native_sim_setup`
* Version: main
* SHA-1: 64ff60a870e30a6394e892666f98295db8b53940

**Comment by jukkar** [comment]
This seems to be related to nsos, @mniestroj please take a look.
