### ISSUE TITLE
RFC: Breaking API Change: SMF: change SMF_CREATE_STATE()

### ISSUE THREAD

**Issue by maass-hamburg** [zephyrproject-rtos/zephyr#71252]
## Problem description

Currently the number of arguments of `SMF_CREATE_STATE()` is dependent on the Kconfig options `CONFIG_SMF_ANCESTOR_SUPPORT` and `CONFIG_SMF_INITIAL_TRANSITION`, IMO this is bad, as it breaks existing code if a Kconfig option is enabled, that wasn't enabled when the existing code was written.

As the USB-C subsystem uses the SMF with `CONFIG_SMF_ANCESTOR_SUPPORT` enabled and `CONFIG_SMF_INITIAL_TRANSITION` disabled, so the user can’t use hierarchical state machine with support for initial transitions in the same project together with using the USB-C subsystem, as enabling `CONFIG_SMF_INITIAL_TRANSITION` would break the USB-C subsystem.

## Proposed Change (detailed):

`SMF_CREATE_STATE()` should always have 5 arguments and the unused arguments should be set to `NULL`.
See #71250 for that.

## Detailed RFC
`SMF_CREATE_STATE()` should be defined as the following:
```
#define SMF_CREATE_STATE(_entry, _run, _exit, _parent, _initial)               \
{                                                                              \
	.entry = _entry,                                                       \
	.run   = _run,                                                         \
	.exit  = _exit,                                                        \
	IF_ENABLED(CONFIG_SMF_ANCESTOR_SUPPORT, (.parent = _parent,))          \
	IF_ENABLED(CONFIG_SMF_INITIAL_TRANSITION, (.initial = _initial,))      \
}
```

### Dependencies

In code parts, where `CONFIG_SMF_ANCESTOR_SUPPORT` and `CONFIG_SMF_INITIAL_TRANSITION` were not enabled,  users have to add `NULL` arguments to their call of  `SMF_CREATE_STATE()`

**Comment by keith-zephyr** [comment]
The proposal makes sense.  @sambhurst Do you have any objections?

**Comment by glenn-andrews** [comment]
Thinking about it, if `CONFIG_SMF_ANCESTOR_SUPPORT` is not enabled, you don't want the `.parent` field, to save memory in flat state machines that don't use it.

**Comment by sambhurst** [comment]
Seems like a good idea to me.

**Comment by glenn-andrews** [comment]
> > Thinking about it, if `CONFIG_SMF_ANCESTOR_SUPPORT` is not enabled, you don't want the `.parent` field, to save memory in flat state machines that don't use it.
> 
> It should be no problem changing that in another PR after my proposal has been accepted und my PR been merged.

The current state machine omits it for flat state machines, so permanently adding it is a memory waste on resource-constrained devices (So I'm told).

**Comment by maass-hamburg** [comment]
> > > Thinking about it, if `CONFIG_SMF_ANCESTOR_SUPPORT` is not enabled, you don't want the `.parent` field, to save memory in flat state machines that don't use it.
> > 
> > 
> > It should be no problem changing that in another PR after my proposal has been accepted und my PR been merged.
> 
> The current state machine omits it for flat state machines, so permanently adding it is a memory waste on resource-constrained devices (So I'm told).

In the current main the `const struct smf_state *parent` it is a permanent member of `struct smf_state`.  My proposal would work with having and not having it as a permanent member.  For not having it as a permanent member feel free to open a new issue and PR to have it changed. By the way having a permanent member of a struct, that is not used in some configurations is not forbidden and the conditional inclusion is not mandatory, but allowed [see here](https://docs.zephyrproject.org/latest/contribute/coding_guidelines/index.html#rule-a-1-conditional-compilation).

**Comment by keith-zephyr** [comment]
I think it was on oversight that the initial implementation of the SMF made  `const struct smf_state *parent` a permanent member.

**Comment by glenn-andrews** [comment]
> In the current main the `const struct smf_state *parent` it is a permanent member of `struct smf_state`. 

https://github.com/zephyrproject-rtos/zephyr/blob/84e7107b32f9babdab7c74a7b2a3f96df1f5172b/include/zephyr/smf.h#L69

It's not there if `CONFIG_SMF_ANCESTOR_SUPPORT` is not set.

**Comment by glenn-andrews** [comment]
> In the current main the `const struct smf_state *parent` it is a permanent member of `struct smf_state`. 

You are correct, my mistake.

**Comment by carlescufi** [comment]
Architecture WG:

- No objections

**Comment by carlescufi** [comment]
@maass-hamburg have you sent an email to the devel@ mailing list about this breaking change?

**Comment by maass-hamburg** [comment]
> @maass-hamburg have you sent an email to the devel@ mailing list about this breaking change?

Yes, here https://lists.zephyrproject.org/g/devel/message/9472
