### ISSUE TITLE
STM32 ethernet driver crashes without connected cable

### ISSUE THREAD

**Issue by therealprof** [zephyrproject-rtos/zephyr#7127]
If the STM32 ethernet driver is enabled and a networking capable firmware run without connected cable, the firmware will almost immediately crash with a MPU error:
```
***** MPU FAULT *****
  Executing thread ID (thread): 0x20003db0
  Faulting instruction address:  0x8000bba
  Data Access Violation
  Address: 0x8001a69
Fatal fault in thread 0x20003db0! Aborting.
```

Analysis shows this is due to an attempt to copy data out of the DMA buffer which was never correctly initialised in in `eth_tx()`:
```
#0  memcpy (d=d@entry=0x8001a69 <__nmi>, s=0x20007e18 <net_buf_data_tx_bufs+128>, n=106) at zephyr/lib/libc/minimal/source/string/string.c:237
#1  0x080055b6 in eth_tx (iface=<optimized out>, pkt=0x20007618 <_k_mem_slab_buf_tx_pkts+640>) at zephyr/drivers/ethernet/eth_stm32_hal.c:96
```

The problem is obviously caused by `eth_iface_init()` exiting early due to `HAL_ETH_Init()` returning with a `HAL_TIMEOUT` and never finishing up the initialisation, yet the system will still happily use the driver functionality.

Tests show that without the return in `HAL_ETH_init()` the system runs just fine and will also pick up SLAAC addresses automatically after plugging in an ethernet cable.

**Comment by erwango** [comment]
Could be closed once #7344 gets merged
