### ISSUE TITLE
drivers: LIS2DH needs an additional register read before waking up from suspend

### ISSUE THREAD

**Issue by deveritec-rosc** [zephyrproject-rtos/zephyr#71371]
**Describe the bug**
As stated in the Manual Rev 6, e.g. section 8.9 footnote 1, the LSI2DH should read the the REFERENCE register once to reset the filter block before going back to an active state to ensure proper device functionality.

**Environment (please complete the following information):**
 - d9fd292f4b9af24cb4c1f16ea73c3a857d6af42f

**Comment by avisconti** [comment]
Have you experimented a real issue on a board or just by code review? (in the former case. can you possible add details?)

**Comment by deveritec-rosc** [comment]
I have a board for a customer with a LIS2DH, and in high performance mode the values were sometimes really strange after wakeup.
