### ISSUE TITLE
I2C Driver does not compile for nrf5 boards

### ISSUE THREAD

**Issue by hakonfam** [zephyrproject-rtos/zephyr#7137]
When enabling I2C driver for nrf52_pca10040 or nrf51_pca10028 the following error is given:

```
zephyr/include/generated/generated_dts_board.h:91:33: error: 'NORDIC_NRF5_I2C0_40003000_BASE_ADDRESS_0' undeclared here (not in a function); did you mean 'NORDIC_NRF_UART_40002000_BASE_ADDRESS_0'?
zephyr/include/generated/generated_dts_board.h:93:31: error: 'NORDIC_NRF5_I2C0_40003000_CLOCK_FREQUENCY' undeclared here (not in a function); did you mean 'NORDIC_NRF5_I2C0_40003000_BASE_ADDRESS_0'?
zephyr/include/generated/generated_dts_board.h:92:28: error: 'NORDIC_NRF5_I2C0_40003000_LABEL' undeclared here (not in a function); did you mean 'NORDIC_NRF_UART_40002000_LABEL'?
```
And so on.

Tested on version c0d0a61bcc4f
To reproduce, build `samples/bluetooth/beacon/` for either nrf52_pca10040 or nrf51_pca10028 with the following configuration set:

CONFIG_I2C=y
CONFIG_I2C_NRF5=y
CONFIG_I2C_0=y
CONFIG_I2C_NRF5_0_GPIO_SDA_PIN=12
CONFIG_I2C_NRF5_0_GPIO_SCL_PIN=13

**Comment by hakonfam** [comment]
It looks like putting 
```
&i2c0{
    status = "ok";
    compatible = "nordic,nrf5-i2c";
}; 
```

into `boards/arm/nrf52_pca10040/nrf52_pca10040.dts` fixes the issue, although I do not know why yet.

**Comment by SebastianBoe** [comment]
@anangl : AFAICT from the description this means that I2C is broken on nRF devices for release 1.11.

**Comment by hakonfam** [comment]
It looks like 51ba17 and 422bc2 moved the I2C configuration into DTS, but forgot to enable I2C on the board specific dts files.
