### ISSUE TITLE
Kconfig board warnings when building docs

### ISSUE THREAD

**Issue by gmarull** [zephyrproject-rtos/zephyr#71418]
**Describe the bug**

When building the documentation, some Kconfig warnings related to board options are shown:

```
warning: BOARD_EBYTE_E73_TBB_NRF52832 (defined at boards/ebyte/e73_tbb/Kconfig.ebyte_e73_tbb:6) defined without a type
warning: BOARD_VISIONFIVE2_JH7110 (defined at boards/starfive/visionfive2/Kconfig.visionfive2:4) defined without a type
warning: BOARD_VMU_RT1170_MIMXRT1176_CM7 (defined at boards/nxp/vmu_rt1170/Kconfig.vmu_rt1170:4) defined without a type
warning: BOARD_IMX93_EVK_MIMX9352_A[55](https://github.com/zephyrproject-rtos/zephyr/actions/runs/8658849039/job/23743561136?pr=71402#step:9:56) (defined at boards/nxp/imx93_evk/Kconfig.imx93_evk:4) defined without a type
warning: BOARD_NRF54L15PDK_NRF54L15_CPUAPP (defined at boards/nordic/nrf54l15pdk/Kconfig.nrf54l15pdk:4) defined without a type
warning: BOARD_WE_PROTEUS2EV_NRF52832 (defined at boards/we/proteus2ev/Kconfig.we_proteus2ev:4) defined without a type
warning: BOARD_SK_AM62_AM6234_M4 (defined at boards/ti/sk_am62/Kconfig.sk_am62:8) defined without a type
warning: BOARD_RAK5010_NRF52840 (defined at boards/rak/rak5010/Kconfig.rak5010:6) defined without a type
warning: BOARD_BLUECLOVER_PLT_DEMO_V2_NRF52832 (defined at boards/bcdevices/plt_demo_v2/Kconfig.blueclover_plt_demo_v2:6) defined without a type
```

**To Reproduce**

```
cd doc
cmake -B _build
cmake --build _build --target html
``` 

**Expected behavior**

No warnings are shown

**Impact**

Annoyance

**Logs and console output**

See above.

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain Zephyr SDK
 - Commit SHA or Version used f9e7861f53aeb721853f84d7ce51460c3576775c

**Additional context**

Likely related to the introduction of HWMv2.

**Comment by soysaucewaso** [comment]
Hey, I'd love to work on this if no one else takes it. My approach would be to edit the CMakeLists in zephyr/doc and find a flag to mute warnings. Specifically, I'd edit this portion:
add_doc_target(
  html
  COMMAND ${CMAKE_COMMAND} -E env ${SPHINX_ENV}
  ${SPHINXBUILD}
    -b html
    -c ${DOCS_CFG_DIR}
    -d ${DOCS_DOCTREE_DIR}
    -w ${DOCS_BUILD_DIR}/html.log
    -t ${DOC_TAG}
    ${SPHINXOPTS}
    ${SPHINXOPTS_EXTRA}
    ${DOCS_SRC_DIR}
    ${DOCS_HTML_DIR}
  USES_TERMINAL
  COMMENT "Running Sphinx HTML build..."
)
