### ISSUE TITLE
drivers: adc: adc_api test failed on some platforms

### ISSUE THREAD

**Issue by kl-cruz** [zephyrproject-rtos/zephyr#71437]
**Describe the bug**
I am adding new target platform nRF54L15. I see some platforms that are not touched by me failed. Precisely: Twister tests run on adc_api are failing. The main error is 
`#error "Unsupported board."`

See: https://github.com/zephyrproject-rtos/zephyr/actions/runs/8647725675/job/23710168247?pr=68692

Platforms affected:
- bl654_dvk/nrf52840/pa
- esp32s2_devkitc
- esp_wrover_kit/esp32/procpu
- lpcxpresso55s69/lpc55s69/cpu0/ns
- vmu_rt1170/mimxrt1176/cm7
- yd_esp32/esp32/procpu

Problem occurs on main as well (tested @ 97177ba01a829511826c5e5cdb55f611c08b172f). 
It looks like overlays consists of incorrect information or lacks of adc entries.

**To Reproduce**
Steps to reproduce the behavior (for example):
1. west build -p -b lpcxpresso55s69/lpc55s69/cpu0/ns tests/drivers/adc/adc_api -T drivers.adc

**Expected behavior**
To compile tests without errors.

**Impact**
It is showstopper for PR https://github.com/zephyrproject-rtos/zephyr/pull/68692

**Logs and console output**

See: https://github.com/zephyrproject-rtos/zephyr/actions/runs/8647725675/job/23710168247?pr=68692

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: zephyr 0.16.5
 - main@97177ba01a829511826c5e5cdb55f611c08b172f

**Additional context**
No additional context

**Comment by ajarmouni-st** [comment]
You just need to rename the overlays in `tests/drivers/adc/adc_api/boards`:
`yd_esp32.overlay` -> `yd_esp32_esp32_procpu.overlay`
`bl654_dvk.overlay` -> `bl654_dvk_nrf52840_pa.overlay`
...
