### ISSUE TITLE
Bluetooth: host: add `prj.conf` for ATT illegal pipeline test with rx/tx priorities inverted

### ISSUE THREAD

**Issue by alwa-nordic** [zephyrproject-rtos/zephyr#71444]
> @alwa-nordic can you add a `prj.conf` for the pipeline test with the priorities inverted? can be in a future PR

_Originally posted by @jori-nordic in https://github.com/zephyrproject-rtos/zephyr/issues/71391#issuecomment-2051909240_

tests/bsim/bluetooth/host/att/pipeline

**Comment by jori-nordic** [comment]
we need a bot for this kinda stuff lol
