### ISSUE TITLE
Configuration file for Cross Toolchain on macOS

### ISSUE THREAD

**Issue by wenhuizhang** [zephyrproject-rtos/zephyr#7145]
Hi, 

Just confused on which configuration sample should be used as base for which cross-arch.
It was saying that : 

- i586.config: for standard ABI, for example for Galileo and qemu_x86
- iamcu.config: for IAMCU ABI, for example for the Arduino 101
- nios2.config: for Nios II boards

(ref http://docs.zephyrproject.org/getting_started/installation_mac.html)

However when I was trying to cross compile to `cmake -GNinja -DBOARD=qemu_x86 ..`

It is looking for `/Volumes/CrossToolNG/x-tools/i586-zephyr-elfiamcu/bin/i586-zephyr-elfiamcu-`
which seems to be generated from `iamcu.config`. 

Any suggestions please?
Also, if I'd like to cross compile to armv7 (qemu_cortex_m3) on macOS, which configuration should I start with for the toolchain build process please?

Thanks,
Wenhui

**Comment by nashif** [comment]
Please take a look at sdk-ng project, it has a script to build those toolchains and updated configs for various architectures.
