### ISSUE TITLE
#error "Unsupported board." of twister build ./tests/drivers/adc/adc_api

### ISSUE THREAD

**Issue by cyliangtw** [zephyrproject-rtos/zephyr#71494]
**Describe the bug**
Got #error "Unsupported board." of twister build ./tests/drivers/adc/adc_api.
About the failing check of "Run tests with twister / twister-build (1)", it's not caused by modification of the PR.
According to the build log, lpcxpresso55s69_lpc55s69_cpu0_ns seems fail to build /tests/drivers/adc/adc_api/drivers.adc.

The snippet of log as below:

/__w/zephyr/zephyr/tests/drivers/adc/adc_api/src/test_adc.c:45:2: error: #error "Unsupported board."
   45 | #error "Unsupported board."
      |  ^~~~~

https://github.com/zephyrproject-rtos/zephyr/actions/runs/8645366060/job/23733494554?pr=71267

**To Reproduce**
1. Send PR of ./tests/drivers/adc/adc_api/boards
2. Twister build
3. Got error  "Unsupported board." of vmu_rt1170/mimxrt1176/cm7, yd_esp32/esp32/procpu, lpcxpresso55s69_lpc55s69_cpu0_ns s
https://github.com/zephyrproject-rtos/zephyr/actions/runs/8645366060/job/23733495034?pr=71267

**Comment by hakehuang** [comment]
fix is here #71472
