### ISSUE TITLE
board: particle argon - nRF52840 : Not booting

### ISSUE THREAD

**Issue by WilliamGFish** [zephyrproject-rtos/zephyr#71565]
**Describe the bug**
After downloading the latest changes in zephyr applications that previously worked on the Particle Argon now will not boot.

I have compiled other applications and they still work other devices

**Expected behavior**
device booting correctly 

**Impact**
Personally showstopper...

**Logs and console output**
No output to capture

**Environment (please complete the following information):**
 - OS: Windows 10
-- CMake version: 3.25.0-rc2
-- Zephyr version: 3.6.99
-- Found west (found suitable version "1.2.0", minimum required is "0.14.0")
-- Board: particle_argon, qualifiers: nrf52840
-- Found toolchain: gnuarmemb (C:\gnu_arm_embedded_10)

**Comment by henrikbrixandersen** [comment]
Please use our bug template when reporting bugs. You need to edit this issue to include the information requested in https://github.com/zephyrproject-rtos/zephyr/blob/main/.github/ISSUE_TEMPLATE/001_bug_report.md

**Comment by anangl** [comment]
@WilliamGFish Could you check if #71593 fixed this issue?

**Comment by WilliamGFish** [comment]
All working as before

**Comment by oscar-lauth** [comment]
How were you able to flash ZephyrOS programs onto the particle argon, removing DeviceOS? Very curious as I am trying to find a way to flash my particle argon using ZephyrOS.

**Comment by WilliamGFish** [comment]
Look up the device in documentation and follow the flashing instructions. There esp32 firmware will not work without being manually updated.
