### ISSUE TITLE
ISR access to BSS section is not working

### ISSUE THREAD

**Issue by Amit-Radur** [zephyrproject-rtos/zephyr#71564]
I have following snippet where trying to access global object from an ISR but it failed, for instance printing the value pointed by global pointer gives a garbage value, and the global pointer is nil.

``
struct abc {
uint32_t val;
};

struct abc *xyz;

void my_isr(void *arg)
{
   printk("val is %x\n", xyz->val); // gives garbase
   printk("pointer value  is %p\n", xyz); // give nil
}

void my_isr_installer(void)
{
   xyz = malloc(sizeof(struct abc));
   xyz->val = 10;

   ...
   IRQ_CONNECT(MY_DEV_IRQ, MY_DEV_PRIO, my_isr, NULL, 0);
   irq_enable(MY_DEV_IRQ);
   ...

}

Same snippet work when gcc attribute "data" is used , for instance struct abc *xyz  __attribute__((section("data")));

**Comment by henrikbrixandersen** [comment]
Please use our bug template when reporting bugs. You need to edit this issue to include the information requested in https://github.com/zephyrproject-rtos/zephyr/blob/main/.github/ISSUE_TEMPLATE/001_bug_report.md

**Comment by henrikbrixandersen** [comment]
Please provide the missing information and reopen this issue report.
