### ISSUE TITLE
Kconfig.defconfig is undocumented and unclear

### ISSUE THREAD

**Issue by ulfalizer** [zephyrproject-rtos/zephyr#7159]
`Kconfig.defconfig` files were mysterious to me, meaning they're probably super mysterious to people who are less used to Kconfig. They ought to be documented, both to make the design clearer, and to prevent people from putting stuff in random places.

The prefer-later-defaults behavior (see https://github.com/zephyrproject-rtos/zephyr/issues/7054) could be documented at the same time.

Here's an overview of what I think the thinking behind those files is, taken from https://github.com/zephyrproject-rtos/zephyr/issues/6890#issuecomment-377946637:

 1. Boards have some fixed setting/symbol X.

  2. If a user picks a particular board, they shouldn't be able to change X in e.g. `menuconfig`, so X has no `prompt`.

  3. Since X has no prompt, it can't be assigned its board-specific value via a `.config` (`*_defconfig` in this case) file.

  4. X still needs to get its board-specific value somehow though, and that's what those `Kconfig.defconfig` files are for. You could have a single symbol definition with all the `default`s too, but it would get spammy.

**Comment by ulfalizer** [comment]
CC @carlescufi

**Comment by SebastianBoe** [comment]
I don't know what the design behind Kconfig.defconfig is either.

But one would think that the use-case for having board-specific immutable/fixed configs should be covered by DTS and then input to Kconfig like ARCH is.

**Comment by carlescufi** [comment]
Agreed, these files are a mystery. I've assigned you to this @ulfalizer so you can document them.
