### ISSUE TITLE
mgmt: hawkbit: always approves the cancelation of an action

### ISSUE THREAD

**Issue by maass-hamburg** [zephyrproject-rtos/zephyr#71691]
**Describe the bug**

Our hawkBit subsystem currently always approves the cancellation of a action (doing a firmware update) even if the firmware update had been completed.

**To Reproduce**
Create and assign a update via the hawkBit update server and cancel the update at the server between installing and starting the hawkbit subsystem after rebooting

**Expected behavior**
The hawkbit subsystem should check the saved action id and if it is identical with the one of the cancellation it should  deny the cancellation.

**Impact**
annoyance, will only happen in rare cases.

**Logs and console output**
NA

**Additional context**
NA

**Comment by henrikbrixandersen** [comment]
Please use our bug template when reporting bugs. You need to edit this issue to include the information requested in https://github.com/zephyrproject-rtos/zephyr/blob/main/.github/ISSUE_TEMPLATE/001_bug_report.md
