### ISSUE TITLE
Zephyr Tests are skipped and HARD FAULT after printing

### ISSUE THREAD

**Issue by RichardSWheatley** [zephyrproject-rtos/zephyr#71714]
**Describe the bug**
Running tests gpio_basic_api and counter_basic_api.
The tests _appear_ to pass and then HARD FAULT at the end of the printout.
The test isn't actually running, though. Tests that should fail (no GPIO pins connected) are labelled as passing.

**To Reproduce**
Build and run either gpio_basic_api or counter_basic_api on the apollo4p_evb from Ambiq.

**Expected behavior**
Tests should run properly whether fail or pass.

**Impact**
showstopper

**Logs and console output**
I am having an Issue and it is due to this commit:

> Commit: f11027df8061932ddf1209f985a67164d140f303 [f11027d]
> Parents: 72312feead
> Author: Wilfried Chauveau <wilfried.chauveau@arm.com>
> Date: Friday, October 6, 2023 10:45:48 PM
> Committer: Carles Cufí
> Commit Date: Monday, April 15, 2024 9:09:28 AM
> arch: arm: cortex_m: Use outlined arch_irq_(un)lock in assembly
> 
> Asm is notoriously harder to maintain than C and requires core specific
> adaptation which impairs even more the readability of the code.
> 
> This change reduces the need for core specific conditional compilation.
> 
> Signed-off-by: Wilfried Chauveau <wilfried.chauveau@arm.com>

My error says:

> **ASSERTION FAIL [!terminate] @ WEST_TOPDIR/zephyr/kernel/sched.c:529**
>         **aborted _current back from dead**
> E: ***** HARD FAULT *****
> E:   Fault escalation (see below)
> E: ARCH_EXCEPT with reason 4
> 
> E: r0/a1:  0x00000004  r1/a2:  0x00000211  r2/a3:  0x00000001
> E: r3/a4:  0x00000004 r12/ip:  0x00000000 r14/lr:  0x0001ef71
> E:  xpsr:  0x21000000
> E: Faulting instruction address (r15/pc): 0x00020e5a
> E: >>> ZEPHYR FATAL ERROR 4: Kernel panic on CPU 0
> E: Current thread: 0x100101e0 (main)
> E: Halting system

@ithinuel Hello! It looks like some of the changes in that commit are causing issues for some of us.
Since I am not an Arm expert, would you please take a look?

**Environment (please complete the following information):**
any

**Comment by RichardSWheatley** [comment]
@ithinuel 

Is this considered fixed with your PR?
As I mentioned in your request, the code did fix our issue!

**Comment by ithinuel** [comment]
I would only consider this fixed once it is merged but hopefully yes.
It is now only missing some reviews.

**Comment by ithinuel** [comment]
Out of curiousity, Is `INIT_ARCH_HW_AT_BOOT` enabled in your case?
And if not, does enabling it also solves your issue?

**Comment by ithinuel** [comment]
Are you happy closing this issue with the fix that was merged?

**Comment by RichardSWheatley** [comment]
> Out of curiousity, Is `INIT_ARCH_HW_AT_BOOT` enabled in your case? And if not, does enabling it also solves your issue?

I will check with both teams but it is not in my case.

**Comment by RichardSWheatley** [comment]
@ithinuel Thank you for you hard work!
