### ISSUE TITLE
Mcr20a initialization crashes with frdm_k64f board

### ISSUE THREAD

**Issue by rveerama1** [zephyrproject-rtos/zephyr#7172]
Mcr20a initialization crashes in frdm_k64f, latest upstream commit I noticed this crash is
--------------------------------------------------------------------------------------
commit f5f95ee3a909e522acb1a8ee534635d45803441c
Author: Leandro Pereira <leandro.pereira@intel.com>
Date:   Fri Apr 6 15:55:11 2018 -0700

    kernel: sem: Ensure that initial count is lesser or equal than limit
--------------------------------------------------------------------------------------

***** BUS FAULT *****
  Executing thread ID (thread): 0x20008a14
  Faulting instruction address:  0x11f38020
  Instruction bus error
Fatal fault in essential thread! Spinning...

**Comment by rveerama1** [comment]
@mjs-arm @MaureenHelm assign to right person if it is not related to you.

**Comment by MaureenHelm** [comment]
Thanks @mike-scott for reporting the additional failures. I was thinking about fixing the mcr20a driver by adding dts bindings, but with the additional dependencies in the sensor drivers, I'll revert the bad PR.
