### ISSUE TITLE
MCUboot example does not build on INFINEON PSoC6 WiFi-BT Pioneer Kit board

### ISSUE THREAD

**Issue by hcd-bdltd** [zephyrproject-rtos/zephyr#71736]
**Describe the bug**

Currently, the MCUboot example is not building when using the INFINEON PSoC6 WiFi-BT Pioneer Kit board.

The error is related with missing `boot_partition`

```
devicetree error: /chosen: undefined node label `boot_partition`
```

I have added the `boot_partition` by adding the following in `cypress/cy8ckit_062_wifi_bt/cy8ckit_062_wifi_bt_cy8c6247_m0.dts`, just to get it to build it.

``` dts
&flash0 {

	partitions {
		compatible = "fixed-partitions";
		#address-cells = <1>;
		#size-cells = <1>;

		boot_partition: partition@0 {
			label = "mcuboot";
			reg = <0x00000000 0xc000>;
		};
		slot0_partition: partition@c000 {
			label = "image-0";
			reg = <0x0000C000 0x37000>;
		};
		slot1_partition: partition@43000 {
			label = "image-1";
			reg = <0x00043000 0x37000>;
		};
		storage_partition: partition@7a000 {
			label = "storage";
			reg = <0x0007a000 0x00006000>;
		};
	};
};
```

But then I have the following error
```
warning: FLASH_MAP (defined at subsys/storage/flash_map/Kconfig:10) has direct dependencies FLASH_HAS_DRIVER_ENABLED with value n, but is currently being y-selected by the following symbols:
 - MCUBOOT_DEVICE_SETTINGS (defined at /home/hudson/zephyrproject/bootloader/mcuboot/boot/zephyr/Kconfig:705), with value y, direct dependencies y (value: y)
```

Which I am not sure how to solve it. I would be happy to help with it, just need guidance about what to do.

**To Reproduce**
```
west build -p always -b cy8ckit_062_wifi_bt/cy8c6247/m0 --sysbuild zephyr/samples/application_development/sysbuild/with_mcuboot
```

**Impact**
At the moment is blocking me to progress further.

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: zephyr-sdk-0.16.5-1
 - Commit SHA: `45205f865e`

**Comment by ifyall** [comment]
@hcd-bdltd, I have added an internal ticket for us to track this. Do you have an Infineon sales or support contact? If you want such a contact, you can go to https://www.infineon.com/cms/en/about-infineon/company/contacts/support/.
