### ISSUE TITLE
build  failure on samples/drivers/spi_flash with em_starterkit/emsk_em11d 

### ISSUE THREAD

**Issue by FRASTM** [zephyrproject-rtos/zephyr#71753]
Building the `west build -p auto -b em_starterkit/emsk_em11d samples/drivers/spi_flash`
fails `with undefined reference to __device_dts_ord_43'`

**Impact**
CI failure

**Environment (please complete the following information):**
 - OS: ubuntu
 - Toolchain SDK 0.16.3
 - Commit SHA 5919bd988b9dfb40a6b4ab5a3fd4af2dccda3c95

**Comment by kokas-a** [comment]
boards/snps/em_starterkit/em_starterkit_emsk_em11d_defconfig is omitted. This cause some of devices are not presented in the system
