### ISSUE TITLE
Missing instructions for unit testing

### ISSUE THREAD

**Issue by NFerragut** [zephyrproject-rtos/zephyr#71837]
**Describe the bug**

The "_Quick start - Unit testing_" section as presented is not very useful. It states that unit testing can be done, but it is missing instructions on how to implement the unit tests.

The missing **HOW** information should include the following:

- The use of `COMPONENTS unittest` in the `find_package()` command in the _CMakeLists.txt_.
- The use of `testbinary` in the `target_sources` command in the _CMakeLists.txt_.
- A reference to an example unit test from the Zephyr repository.

Additionally, the "_Quick start - Unit testing_" section contains the "_Best practices for declaring the test suite_" as a sub-section which seems misplaced.

**Environment**

* Page: `develop/test/ztest`
* Version: main
* SHA-1: 72c6ffb2d04bf1d9c23e0ef71464b3693d96ba98

**Comment by meetbariya** [comment]
Yes, I'm also facing the same issue.
There is not enough information for the unit testing in "https://docs.zephyrproject.org/latest/develop/test/ztest.html#quick-start-unit-testing".

As unit testing is a critical aspect of software development, having accurate and thorough documentation can greatly benefit developers working with Zephyr.
I believe that clarifying these points will help me and many other community developers who may be facing similar challenges.

It would be great to add unit testing information like integration testing "https://docs.zephyrproject.org/latest/develop/test/ztest.html#quick-start-integration-testing" with an example.

Thanks!!
