### ISSUE TITLE
Bluetooth: Mesh: Update models metadata API

### ISSUE THREAD

**Issue by omkar3141** [zephyrproject-rtos/zephyr#71866]
## Introduction

The current implementation of the models metadata API in Bluetooth Mesh subsystem is as follows:

1. Current API has metadata pointer `const struct bt_mesh_models_metadata_entry *` in the model contexts that have metadata (For example: in [`struct bt_mesh_health_srv`](https://github.com/zephyrproject-rtos/zephyr/blob/aa87ed5d8a711c50c5db325b543068ac583d2a6b/include/zephyr/bluetooth/mesh/health_srv.h#L162)). The actual variable that is used for preparing models metadata status response ([`const struct bt_mesh_models_metadata_entry * const * const metadata;`](https://github.com/zephyrproject-rtos/zephyr/blob/aa87ed5d8a711c50c5db325b543068ac583d2a6b/include/zephyr/bluetooth/mesh/access.h#L927)) resides in `struct bt_mesh_model` in `access.h`. The metadata double pointer in access layer gets simply assigned from the metadata pointer in corresponding model context. The pointer in model context has no other usage.

2. The metadata double pointer in [`access.h`](https://github.com/zephyrproject-rtos/zephyr/blob/aa87ed5d8a711c50c5db325b543068ac583d2a6b/include/zephyr/bluetooth/mesh/access.h#L927) adds extra complexity.

### Problem description

This implementation is inefficient, a bit complex, and requires [two variants](https://github.com/zephyrproject-rtos/zephyr/blob/aa87ed5d8a711c50c5db325b543068ac583d2a6b/include/zephyr/bluetooth/mesh/health_srv.h#L177) of model initializer macros for each model that supports optional metadata. 

### Proposed change

Simplify and optimize API by removing redundant pointer in model context.

## Detailed RFC

1. Remove redundant pointer from model context.
2. Just have a single variant of a model initializer macro in model header file. 
3. Replace double pointer by single pointer in `access.h`.

### Proposed change (Detailed)

1. Remove redundant pointer from model context.
2. Just have a single variant of a model initializer macro in model header file. 
3. Replace double pointer by single pointer in `access.h`.

See PR #71281.

### Dependencies

Zephyr code is affected only in three files: 
- Health Server Model context and Health Server Model init macro in `health_srv.h` header
- Model context in `access.h`
- Relevant updates in `shell.h`

Impact:
- For implementations **not** using optional metadata feature of health server model: **nothing changes**.
- For implementations using optional metadata feature: address of the application defined metadata structure will have to be supplied at a different place than before. This should be trivial change. This is documented in migration guide.

### Concerns and Unresolved Questions

none so far

## Alternatives

No specific alternative. Proposed solution in PR #71281 emerged as a result of design discussions.

**Comment by carlescufi** [comment]
Architecture WG:

- No objections
