### ISSUE TITLE
xtensa: remove unnecessary padding in arch_mem_domain

### ISSUE THREAD

**Issue by ldmstm** [zephyrproject-rtos/zephyr#71896]
**Is your enhancement proposal related to a problem? Please describe.**
The current definition of `arch_mem_domain` for the xtensa architecture (https://github.com/zephyrproject-rtos/zephyr/blob/023248a1f33cfd29655de2c4a9bfd13f2af3424b/include/zephyr/arch/xtensa/arch.h#L65) forcefully aligns one of its members to a page boundary, adding unnecessary padding.

I suspect the intention behind this alignment is to indicate the pointer points to an MMU page-size aligned address, but instead it aligns the pointer storage itself.

**Describe the solution you'd like**
The `__aligned` directive needs to be removed.

**Comment by dcpleung** [comment]
Reopening this for backporting to v3.7
