### ISSUE TITLE
tickless and timeslicing don't play well together

### ISSUE THREAD

**Issue by andyross** [zephyrproject-rtos/zephyr#7193]
Specific bug: wake up a thread (or create a new one) at the same priority as the currently running thread, both of which are at the same preemptible priority and in a situation where no other threads exist at that priority.  In theory, the CPU timer should be adjusted to reflect the new situation and expire in one slicing tick.  In practice, the timer is not adjusted and the new thread won't get any CPU until whenever the next interrupt fires, which could be a long time.

That issue was found via inspection as I stumpled over this code while working on the scheduler.  The more general problem is that we have pretty poor test coverage for both timeslicing and tickless behaviors, this situation needs to be tested and handled, along with (probably) others.

**Comment by jli157** [comment]
Could the issue https://github.com/zephyrproject-rtos/zephyr/issues/7048 be caused by same root cause?

**Comment by andyross** [comment]
The bug found by inspection will be fixed.  Probably need some sort of longer term tracking on enhancing tickless (making it default where possible, expanding tests) and coming up with a better set of tests on timeslicing that look for fairness issues like this.

**Comment by pizi-nordic** [comment]
FYI: @pizi-nordic

**Comment by andyross** [comment]
Fix for the specific bug above is submitted.  Probably should reprioritize rather than close this one, as the rework is if anything needed more now than before, given that we've added another #ifdef TICKLESS case.

**Comment by andyross** [comment]
Ugh, fixed correctly this time.   No idea what happened earlier, presumably I rebased, but then forgot the "-a" on the commit?

**Comment by andyross** [comment]
Fixed as of the big timer rework.  Tickless is default and all timeslicing tests pass with it enabled. Closing as I'm the one who opened it to begin with.
