### ISSUE TITLE
OpenOCD: Fragile handling of version discovery while supporting thread awareness

### ISSUE THREAD

**Issue by nick-kraus** [zephyrproject-rtos/zephyr#71955]
**Describe the bug**
West produces a FATAL ERROR with the OpenOCD runner when trying to check for a suitable version of OpenOCD for thread-aware debugging, **IF** your installed version of OpenOCD adds new tokens into the version string.

Breaks `west debug` with thread-awareness:
```
$ openocd --version
xPack Open On-Chip Debugger 0.12.0+dev-01312-g18281b0c4-dirty (2023-09-04-22:32)
Licensed under GNU GPL v2
For bug reports, read
        http://openocd.org/doc/doxygen/bugs.html
```

Doesn't break (works) `west debug` with thread-awareness (from a different machine):
```
$ openocd --version
Open On-Chip Debugger 0.10.0
Licensed under GNU GPL v2
For bug reports, read
        http://openocd.org/doc/doxygen/bugs.html
```

**To Reproduce**
1. install OpenOCD from https://github.com/xpack-dev-tools/openocd-xpack/ and add to $PATH
2. Build and flash a sample with CONFIG_DEBUG_THREAD_INFO=y
3. run `west debug`
4. see FATAL ERROR saying `invalid literal for int() with base 10: ''`

**Expected behavior**
West should use more reliable methods of getting the OpenOCD version number, so that it works on non-mainline OpenOCD forks which may modify the version string.

**Impact**
Makes it potentially more difficult for Windows users to debug, since the Windows ecosystem is more likely to rely on pre-built forks of OpenOCD instead of getting it from a package manager or compiling. May also be difficult for people needing newer (nightly) binary builds of OpenOCD for newer hardware or feature support.

**Console output**
```
$ west -v debug
-- west debug: rebuilding
cmake version 3.22.1 is OK; minimum version is 3.13.1
Running CMake: 'C:\Program Files\CMake\bin\cmake.EXE' --build 'C:\Users\Nick\Projects\zephyr\build'
ninja: no work to do.
-- west debug: using runner openocd
runners.openocd: 'C:/Program Files (x86)/OpenOCD/xpack-openocd-0.12.0-2/bin/openocd.exe' --version
FATAL ERROR: invalid literal for int() with base 10: ''
An exception trace has been saved in C:\Users\NICKKR~1\AppData\Local\Temp\west-exc-ry9eb7nj.txt
```

**Exception trace**
```
Traceback (most recent call last):
  File "C:\Users\Nick\Projects\zephyr\scripts/west_commands\run_common.py", line 228, in do_run_common
    runner.run(command_name)
  File "C:\Users\Nick\Projects\zephyr\scripts/west_commands\runners\core.py", line 509, in run
    self.do_run(command, **kwargs)
  File "C:\Users\Nick\Projects\zephyr\scripts/west_commands\runners\openocd.py", line 188, in do_run
    self.do_attach_debug(command, **kwargs)
  File "C:\Users\Nick\Projects\zephyr\scripts/west_commands\runners\openocd.py", line 268, in do_attach_debug
    if self.thread_info_enabled and self.supports_thread_info():
  File "C:\Users\Nick\Projects\zephyr\scripts/west_commands\runners\openocd.py", line 168, in supports_thread_info
    (major, minor, rev) = [self.to_num(i) for i in version]
  File "C:\Users\Nick\Projects\zephyr\scripts/west_commands\runners\openocd.py", line 168, in <listcomp>
    (major, minor, rev) = [self.to_num(i) for i in version]
  File "C:\Users\Nick\Projects\zephyr\scripts/west_commands\runners\openocd.py", line 145, in to_num
    num = int(num_match.group(0))
ValueError: invalid literal for int() with base 10: ''
```

**Environment**
 - OS: Windows 10 22H2
 - Toolchain: GNU Arm Embedded Toolchain v10.2.1 2020-q4-major, xPack OpenOCD 0.12.0

**Suggested resolution**
The problem is specifically [in this function and the one below](https://github.com/zephyrproject-rtos/zephyr/blob/main/scripts/west_commands/runners/openocd.py#L191). The functions assume that the important number in the `openocd --version` output will always be at the fourth word (index 3) of the first line. Instead it would be more reliable to use a regex to search for the properly formatted version string.

Something like this should work, by grabbing the number from within group 0: `'Open On-Chip Debugger (\d+.\d+.\d+)'`

If this is a suitable solution to this issue, please let me know and I can work it into a pull request.

**Comment by aescolar** [comment]
CC @carlescufi @nordicjm @tejlmand

**Comment by nick-kraus** [comment]
This is still unresolved (PR is submitted but pending review), would like to have this not marked as stale.
