### ISSUE TITLE
Documentation issue in 'boards/espressif/esp32s3_devkitc/doc/index' - ESP32S3-Devkitc Board not supported

### ISSUE THREAD

**Issue by rvalvekar** [zephyrproject-rtos/zephyr#71973]
**Describe the bug**

Trying to build ESP32S3-Devkitc with Zephyr

**Environment**
Linux Ubuntu 20.04 

* Page: `boards/espressif/esp32s3_devkitc/doc/index`
* Version: main
* SHA-1: b29be06ec2560bff36a61a25b4a4f666144c1f98

I am trying to build the application helllo world using the same instructions from the page mentioned above. Unfortunately i am getting an "Invalid Board Error" while cmake is running, and the build stops. 

I am not sure if the board is indeed supported, since it is also not mentioned in the list of the supported boards that is printed with the error. 

Error : No Board named 'esp32s3_devkitc' found. 

Help and support greately appreciated.
Thank you 
Rohan Valvekar.

**Comment by nordicjm** [comment]
Seemingly you are using zephyr 3.6 or older, this board was added 3 weeks ago, so you need to use `main` to use this board.
