### ISSUE TITLE
Commit 'tests: kernel: mem_protect: tests for userspace mode' breaks scripts/sanitycheck

### ISSUE THREAD

**Issue by ulfalizer** [zephyrproject-rtos/zephyr#7200]
Now get this error:

    E: /home/ulf/zephyr/tests/kernel/mem_protect/mem_protect/testcase.yaml: can't load (skipping): 
    sequence item 0: expected str instance, bytes found

`tests/kernel/mem_protect/mem_protect/testcase.yaml` seems to be causing it.

CC @AdithyaBaglody

**Comment by galak** [comment]
This is also reported in #7198

**Comment by ulfalizer** [comment]
@galak 
Alright, closing then.
