### ISSUE TITLE
check_compliance.py: Use inclusive naming, replace UNDEF_KCONFIG_WHITELIST

### ISSUE THREAD

**Issue by cvinayak** [zephyrproject-rtos/zephyr#72044]
**Describe the bug**
Use of inclusive naming, replace `UNDEF_KCONFIG_WHITELIST` to maybe `UNDEF_KCONFIG_ACCEPTLIST` ?

>  Found references to undefined Kconfig symbols. If any of these are false
positives, then add them to UNDEF_KCONFIG_WHITELIST in /home/runner/work/zephyr/zephyr/./scripts/ci/check_compliance.py.

Please also mention any information which could help others to understand
the problem you're facing:
 - What target platform are you using?
 - What have you tried to diagnose or workaround this issue?
 - Is this a regression? If yes, have you been able to "git bisect" it to a
   specific commit?
 - ...

**To Reproduce**
1. mkdir build; cd build
2. cmake -DBOARD=board\_xyz
3. make

**Expected behavior**

**Impact**
What impact does this issue have on your progress (e.g., annoyance, showstopper)

**Logs and console output**
If applicable, add console logs or other types of debug information
e.g Wireshark capture or Logic analyzer capture (upload in zip archive).
copy-and-paste text and put a code fence (\`\`\`) before and after, to help
explain the issue. (if unable to obtain text log, add a screenshot)

**Environment (please complete the following information):**
 - OS: (e.g. Linux, MacOS, Windows)
 - Toolchain (e.g Zephyr SDK, ...)
 - Commit SHA or Version used

**Additional context**
Add any other context that could be relevant to your issue, such as pin setting,
target configuration, ...

**Comment by cfriedt** [comment]
Alternatively, maybe `UNDEF_KCONFIG_ALLOWLIST` ?
