### ISSUE TITLE
riscv: context switch issue in interrupt handler 

### ISSUE THREAD

**Issue by zxtxin** [zephyrproject-rtos/zephyr#72123]
In the current implementation of riscv _isr_wrapper(), z_riscv_switch will probably be called, then the context will switch to a normal thread, while the mret will not be excecuted to return from the interrupt mode. For MCUs with CLIC interrupt controller such as gd32vf103, mintstatus.mil will not be restored if mret is not executed. As a result, no other interrupts with the same level will be executed.

**Comment by zxtxin** [comment]
any update?

**Comment by fkokosinski** [comment]
Hi @zxtxin, thanks for submitting this bug report.

> In the current implementation of riscv _isr_wrapper(), z_riscv_switch will probably be called, then the context will switch to a normal thread, while the mret will not be excecuted to return from the interrupt mode

I'm not sure I follow. If `z_riscv_switch` is called (when we jump to `no_reschedule`), then we still still return to `_isr_wrapper`, which eventually ends with `mret`.

Could you perhaps provide a more detailed description using the template, and e.g. include the trace of the interrupt handling routine that you're describing? That would be much appreciated. Thanks

**Comment by zxtxin** [comment]
```
check_reschedule:

#ifdef CONFIG_MULTITHREADING

	/* Get pointer to current thread on this CPU */
	lr a1, ___cpu_t_current_OFFSET(s0)

	/*
	 * Get next thread to schedule with z_get_next_switch_handle().
	 * We pass it a NULL as we didn't save the whole thread context yet.
	 * If no scheduling is necessary then NULL will be returned.
	 */
	addi sp, sp, -16
	sr a1, 0(sp)
	mv a0, zero
	call z_get_next_switch_handle
	lr a1, 0(sp)
	addi sp, sp, 16
	beqz a0, no_reschedule

reschedule:

	/*
	 * Perform context switch:
	 * a0 = new thread
	 * a1 = old thread
	 */
	call z_riscv_switch

z_riscv_thread_start:
might_have_rescheduled:
	/* reload s0 with &_current_cpu as it might have changed or be unset */
	get_current_cpu s0

#endif /* CONFIG_MULTITHREADING */

no_reschedule:
```
z_riscv_switch() is called if z_get_next_switch_handle() returns non-zero.
the register sp will directly move to the new thread and the register pc will be changed to the new thread after z_riscv_switch() executed.

` If z_riscv_switch is called (when we jump to no_reschedule), then we still still return to _isr_wrapper `
when we directly jumo to no_reschedule, z_riscv_switch will not be called.
z_riscv_switch is called when we jump to reschedule.

**Comment by fkokosinski** [comment]
> and the register pc will be changed to the new thread

Yes, with `mret` in question setting it with the value of the `mepc` CSR

> z_riscv_switch will probably be called, then the context will switch to a normal thread, while the mret will not be excecuted to return from the interrupt mode

This doesn't seem to be the case, though. In the case of reschedule, stepping with gdb from `call z_riscv_switch` shows that we do the following:
1. `call z_riscv_switch`
2. `ret` from `z_riscv_switch`
3. encounter the `z_riscv_thread_start` label
4. encounter the `no_reschedule` label
5. return from the interrupt context with `mret`

I still can't reproduce a scenario you're describing. Could you please provide more detailed instructions using the standard bug report template that can be found [here](https://github.com/zephyrproject-rtos/zephyr/blob/main/.github/ISSUE_TEMPLATE/001_bug_report.md)? Thanks

**Comment by zxtxin** [comment]
```
080012d4 <z_riscv_switch>:
 80012d4:	0415a623          	sw	ra,76(a1)
 80012d8:	c9a0                	sw	s0,80(a1)
 80012da:	c9e4                	sw	s1,84(a1)
 80012dc:	0525ac23          	sw	s2,88(a1)
 80012e0:	0535ae23          	sw	s3,92(a1)
 80012e4:	0745a023          	sw	s4,96(a1)
 80012e8:	0755a223          	sw	s5,100(a1)
 80012ec:	0765a423          	sw	s6,104(a1)
 80012f0:	0775a623          	sw	s7,108(a1)
 80012f4:	0785a823          	sw	s8,112(a1)
 80012f8:	0795aa23          	sw	s9,116(a1)
 80012fc:	07a5ac23          	sw	s10,120(a1)
 8001300:	07b5ae23          	sw	s11,124(a1)
 8001304:	0425a423          	sw	sp,72(a1)
 8001308:	0cb5ac23          	sw	a1,216(a1)
 800130c:	04852103          	lw	sp,72(a0)
 8001310:	04c52083          	lw	ra,76(a0)
 8001314:	4920                	lw	s0,80(a0)
 8001316:	4964                	lw	s1,84(a0)
 8001318:	05852903          	lw	s2,88(a0)
 800131c:	05c52983          	lw	s3,92(a0)
 8001320:	06052a03          	lw	s4,96(a0)
 8001324:	06452a83          	lw	s5,100(a0)
 8001328:	06852b03          	lw	s6,104(a0)
 800132c:	06c52b83          	lw	s7,108(a0)
 8001330:	07052c03          	lw	s8,112(a0)
 8001334:	07452c83          	lw	s9,116(a0)
 8001338:	07852d03          	lw	s10,120(a0)
 800133c:	07c52d83          	lw	s11,124(a0)
 8001340:	8082                	ret
```
Hi @fkokosinski ,
This is the assembly of z_riscv_switch. reg a0 points to the new thread control block. At 0x8001310, reg ra is updated to the address inside arch_switch() where thread a0 was switched out.

**Comment by zxtxin** [comment]
Here is a way to reproduce this issue:
1.cd to the hello_world sample folder
2.modify the `src/main.c` as follows
```
#include <stdio.h>
#include <zephyr/kernel.h>
#include <zephyr/device.h>
int main(void)
{
	while(1)
	{
		printf("Hello World! %s\n", CONFIG_BOARD);
		k_sleep(K_MSEC(1000));
	}

	return 0;
}
```
3.build the image with the following command:
`west build -p auto -b gd32vf103c_starter`
4.set a breakpoint at `printf(...)`
5.start debuging
6.at the first time encountering the breakpoint, mintstatus.mil is 0.
7.countinue the program.
8.at the second time encountering the breakpoint, mintstatus.mil is non-zero.

**Comment by zxtxin** [comment]
any update?

**Comment by zxtxin** [comment]
z_riscv_switch has been called in _isr_wrapper since commit ce8dabfe9e83e1c3d53c6462a890c5a18468caff.
before that, all context switch was performed by ecall,which would not cause this problem in clic.

**Comment by zxtxin** [comment]
@npitre

**Comment by npitre** [comment]
The "mret" instruction is used to return to threads that were preempted by
an IRQ. When returning to a thread that voluntarily yielded the CPU then 
it is not necessary to do a mode switch as that thread didn't do a mode 
switch when it yielded either. In that case interrupts should be re-enabled
later on the return path with a call to irq_unlock(key) depending on the
value of the key argument.

The RISC-V standard documentation does not mention any extra interaction
between the "mret" instruction and any other MSTATUS bits other than those 
listed in the spec. It is not expected to have side effects on interrupt
controllers.

If your implementation is not standard compliant then you might try with
`CONFIG_RISCV_ALWAYS_SWITCH_THROUGH_ECALL=y`. In that case it will not be
as efficient as you'll have to pay the overhead of an "ecall" with each
task switches but it will always return through a "mret".

**Comment by zxtxin** [comment]
In the base specification of RISC-V, there is no extra interaction between the "mret" and CSRs. But in the
CLIC spec (https://github.com/riscv/riscv-fast-interrupt/blob/master/clic.adoc#clic-interrupt-operation) of RISC-V, which is widely implemented in RISC-V MCUs, such as RISC-V CPU IPs from Nuclei, T-Head, Andes, MINTSTATUS is modified becasue of "mret". The original text from this spec says that "Additionally in CLIC mode, xRET sets xintstatus.xil to xcause.xpil."
  MINTSTATUS.MIL indicates the current interrupt level, just like inerrupt priority in ARM Cortex-M NVIC. Cortex-M must properly return from the interrupt mode to thread mode before a new interrupt with the same priority can be serviced.
      The macro CONFIG_RISCV_ALWAYS_SWITCH_THROUGH_ECALL is currently an effective workaround. I'm not sure if this is a proper solution for all the MCUs with CLIC. Besides, there are some fails in Ztest with CONFIG_RISCV_ALWAYS_SWITCH_THROUGH_ECALL.

**Comment by npitre** [comment]
OK.

In that case I think `MINTSTATUS` might have to be preserved/restored
on a per thread basis in `z_riscv_switch`.

Or even simpler: when returning from `z_riscv_switch`, the interrupt level
can be manually overwritten to 0 in `arch_switch()` and to 1 in
`_irq_wrapper`. Then everything will balance as this would reflect the
expected logical level for those code paths.

**Comment by zxtxin** [comment]
![image](https://github.com/zephyrproject-rtos/zephyr/assets/5063358/45d53f7e-1d2b-4f3b-b89f-4c4d02e0f389)
Unfortunately, MINTSTATUS is not writable according to the spec

**Comment by zxtxin** [comment]
any update?

**Comment by npitre** [comment]
As I said, there must be a way to programmatically modify MINTSTATUS.MIL 
somehow to be optimal. I don't have access to a device with a CLIC and 
currently don't have the time to study the CLIC documentation though.

So either you use CONFIG_RISCV_ALWAYS_SWITCH_THROUGH_ECALL=y or figure 
out how MINTSTATUS.MIL can be modified without using MRET. I can help 
you with Zephyr changes in the later case if you find the information.

**Comment by zxtxin** [comment]
There is no way to programmatically modify MINTSTATUS.MIL without using MRET in the devices implementing CLIC . The only way to work properly with these devices is making sure that CONFIG_RISCV_ALWAYS_SWITCH_THROUGH_ECALL=y.
It's reasonable that MINTSTATUS.MIL is read-only, becasue it just represents a internal state of CPU. Just like ARM Cortex-M，we cannot return from the interrupt mode to thread mode without loading 0xfffffffd or 0xfffffff1 to pc.

**Comment by zxtxin** [comment]
reopen this issue

**Comment by npitre** [comment]
PRS #75587 and #75960 should have fixed this issue.

**Comment by zxtxin** [comment]
> PRS #75587 and #75960 should have fixed this issue.

These two PRs do nothing about MINTSTATUS.MIL and the case when CONFIG_RISCV_ALWAYS_SWITCH_THROUGH_ECALL=n. They are irrelevant to this issue.

**Comment by npitre** [comment]
> These two PRs do nothing about MINTSTATUS.MIL and the case when
> CONFIG_RISCV_ALWAYS_SWITCH_THROUGH_ECALL=n.

Sorry, but this is impossible to support with CONFIG_RISCV_ALWAYS_SWITCH_THROUGH_ECALL=n.

You must have CONFIG_RISCV_ALWAYS_SWITCH_THROUGH_ECALL=y.
