### ISSUE TITLE
doc: bad list formatting in 'samples/subsys/fs/format/README'

### ISSUE THREAD

**Issue by Vyjill** [zephyrproject-rtos/zephyr#72269]
Bad formatting for a list in the first paragraph :

```md
This sample shows how to format different storage devices for different file systems. There are 2 scenarios prepared for this sample: 
* littleFS on flash device
* FAT file system on RAM disk
```

is most likely missing a line feed

```md
This sample shows how to format different storage devices for different file systems. There are 2 scenarios prepared for this sample: 

* littleFS on flash device
* FAT file system on RAM disk
```

**Environment**

N/A

* Page: `samples/subsys/fs/format/README`
* Version: main
* SHA-1: 8dc3f856229ce083c956aa301c31a23e65bd8cd8

**Comment by kartben** [comment]
@Vyjill thanks for the report! If you could send a pull request fixing this, it would be much appreciated!

**Comment by de-nordic** [comment]
[heart]         Ermel, Dominik reacted to your message:
________________________________
