### ISSUE TITLE
Atmel SAM0 ADC driver implementation error

### ISSUE THREAD

**Issue by PeeJay** [zephyrproject-rtos/zephyr#72320]
While using the adc_dt sample with an Atmel SamE51 board with multiple adc inputs, I noticed that all channels were reading from the same mux input on the ADC. 
Inspecting adc_sam0.c reveals that the mux position is set inside of adc_channel_setup_dt, so naturally the last chanel to get setup is the one actually read, regardless of what is passed to adc_read_dt(). Having a quick look at adc_nrfx_adc.c it appears that the channels are selected inside of start_read().
If I run adc_channel_setup_dt() before adc_sequence_init_dt() then it works as expected, however that doesn't seem to be the intended behaviour.

**Comment by henrikbrixandersen** [comment]
Please use our bug template when reporting bugs. You need to edit this issue to include the information requested in https://github.com/zephyrproject-rtos/zephyr/blob/main/.github/ISSUE_TEMPLATE/001_bug_report.md
