### ISSUE TITLE
tests/subsys/logging/log_timestamp/ failing on qemu_x86[_64] on main

### ISSUE THREAD

**Issue by aescolar** [zephyrproject-rtos/zephyr#72344]
**Describe the bug**
tests/subsys/logging/log_timestamp/logging.output.custom_timestamp is failing in main since #69705 was merged

**To Reproduce**
1. twister -p qemu_x86 -T tests/subsys/logging/log_timestamp/ -s logging.output.custom_timestamp 

**Expected behavior**
No errors

**Impact**
main CI broken

**Logs and console output**
https://github.com/zephyrproject-rtos/zephyr/actions/runs/8951164071/job/24587211348#step:11:3389
```
SeaBIOS (version zephyr-v1.0.0-0-g31d4e0e-dirty-20200714_234759-fv-az50-zephyr)
Booting from ROM..
*** Booting Zephyr OS build v3.6.0-3414-gfa7c05cf4718 ***
Running TESTSUITE test_timestamp
===================================================================
START - test_custom_timestamp

    Assertion failed at WEST_TOPDIR/zephyr/tests/subsys/logging/log_timestamp/src/log_timestamp_test.c:78: test_timestamp_test_custom_timestamp: strcmp(exp_str, mock_buffer) not equal to 0

 FAIL - test_custom_timestamp in 0.002 seconds
===================================================================
TESTSUITE test_timestamp failed.

------ TESTSUITE SUMMARY START ------

SUITE FAIL -   0.00% [test_timestamp]: pass = 0, fail = 1, skip = 0, total = 1 duration = 0.002 seconds
 - FAIL - [test_timestamp.test_custom_timestamp] duration = 0.002 seconds

------ TESTSUITE SUMMARY END ------

===================================================================
RunID: d540a6b01e39b244047af44d6af1d792
PROJECT EXECUTION FAILED
```

**Environment (please complete the following information):**
 - OS: Linux Ubuntu 22.04 (CI)
 - Toolchain  Zephyr SDK (CI)
 - Commit SHA or Version used: fa7c05cf4718be15adad0e913fa51a2d5b5bf3dc

**Additional context**
Introduced by https://github.com/zephyrproject-rtos/zephyr/commit/7c03e5de7f0298e9219f82da52b75696c45baa9d

**Comment by najumon1980** [comment]
The regression is due to following reason:
sys_clock_hw_cycles_per_sec() used in log_core_init() which invoked during cstart (EARLY init) but HPET driver init is PRE_KERNEL_2. So the z_clock_hw_cycles_per_sec need to init with some default CONFIG_SYS_CLOCK_HW_CYCLES_PER_SEC (though it is not right) or ideally need to init z_clock_hw_cycles_per_sec run time during cstart (EARLY init).

**Comment by najumon1980** [comment]
Provided following fix for the regression: 
https://github.com/zephyrproject-rtos/zephyr/pull/72352
