### ISSUE TITLE
drivers: sdhc: Why does sdhc_spi_request not spi_release() on error?

### ISSUE THREAD

**Issue by hellesvik-nordic** [zephyrproject-rtos/zephyr#72364]
**Describe the bug**
Suspected bug: [sdhc_spi_request()](https://github.com/nrfconnect/sdk-zephyr/blob/b5cf3040298410845311ff7397374540d3451528/drivers/sdhc/sdhc_spi.c#L600) calls spi_release() at its end.  
However, if it returns an error, the function does not release the SPI. 

**Expected behavior**
The current behaviour assumes that on an error, other parts of the SPI would have either not locked SPI, or properly release the SPI on errors.  Instead, would it not be more robust to release the SPI when the sdhc_spi_request exists, regardless of error?

**Context**
I work with Nordic Semiconductor DevZone, and a user asked me about this over there. Private ticket so I can not link it here.

**Comment by danieldegrasse** [comment]
Thanks for highlighting this, linked PR should fix the issue
