### ISSUE TITLE
sd: sd_ops: Data Race in `card_ioctl`

### ISSUE THREAD

**Issue by clamattia** [zephyrproject-rtos/zephyr#72368]
The function `card_ioctl` in `subsys/sd/sd_ops.c` calls `sdmmc_wait_ready`, which calls `sdhc_card_busy` without taking the `card->lock` mutex. This leads to a data-race on the lower layers (for example spi).

Problematic line: https://github.com/zephyrproject-rtos/zephyr/blob/main/subsys/sd/sd_ops.c#L790

Suggested fix:

```diff
-   switch (cmd) {
-   case DISK_IOCTL_GET_SECTOR_COUNT:
-       (*(uint32_t *)buf) = card->block_count;
-       break;
-   case DISK_IOCTL_GET_SECTOR_SIZE:
-   case DISK_IOCTL_GET_ERASE_BLOCK_SZ:
-       (*(uint32_t *)buf) = card->block_size;
-       break;
-   case DISK_IOCTL_CTRL_SYNC:
-       /* Ensure card is not busy with data write.
-        * Note that SD stack does not support enabling caching, so
-        * cache flush is not required here
-        */
-       return sdmmc_wait_ready(card);
-   default:
-       return -ENOTSUP;
-   }
-   return 0;
+   int ret = 0;
+   ret = k_mutex_lock(&card->lock, K_MSEC(CONFIG_SD_DATA_TIMEOUT));
+   if (ret) {
+       LOG_WRN("Could not get SD card mutex");
+       return -EBUSY;
+   }
+   switch (cmd) {
+   case DISK_IOCTL_GET_SECTOR_COUNT:
+   (*(uint32_t *)buf) = card->block_count;
+       break;
+   case DISK_IOCTL_GET_SECTOR_SIZE:
+   case DISK_IOCTL_GET_ERASE_BLOCK_SZ:
+       (*(uint32_t *)buf) = card->block_size;
+       break;
+   case DISK_IOCTL_CTRL_SYNC:
+       /* Ensure card is not busy with data write.
+        * Note that SD stack does not support enabling caching, so
+        * cache flush is not required here
+        */
+       ret = sdmmc_wait_ready(card);
+       break;
+   default:
+       ret = -ENOTSUP;
+       break;
+   }
+   k_mutex_unlock(&card->lock);
+   return ret;

```

To reproduce: two threads concurrently accessing the sd-card. At least one of them issues `ioclt`s. For example filesystem.

Expected behavior: No data race. With a data race, anything is possible. Of the possible scenarios, crashes are the least problematic.

Severly impacts all applications with concurrent access to the sd-card, when at least one of them uses `ioctl`.

Similar mutex problem in same file: https://github.com/zephyrproject-rtos/zephyr/issues/72287

Let me know, if you need additional information.

**Comment by andyross** [comment]
Nice catch.  But FWIW: "Suggested fixes" are usually best expressed as pull requests. :)

**Comment by clamattia** [comment]
> Nice catch. But FWIW: "Suggested fixes" are usually best expressed as pull requests. :)

Good point. Will try to do so next time 👍

**Comment by clamattia** [comment]
Thank you @danieldegrasse
