### ISSUE TITLE
BLE DTM ll_test does not set correct TXPower

### ISSUE THREAD

**Issue by paulgavrikov** [zephyrproject-rtos/zephyr#7243]
According to the Bluetooth Core Spec v5 Direct Test Mode shall transmit with maximum txpower. However ll_test sets the txpower to 0dBm, which is not the highest txpower for many device including Nordics nRF52 family.

**Comment by cvinayak** [comment]
@paulgavrikov if you do have a PR to use the Max Tx Power for nRF5 series SoCs, I will be happy to review the PR.
@carlescufi This will need use re-run tests on the RF tester.

**Comment by paulgavrikov** [comment]
@cvinayak I don't think I can create a PR for this repo. But you can checkout [this commit ](https://github.com/zephyrproject-rtos/zephyr/commit/a41f4a7b0cc214daaa1eb20953447900f907e766)

**Comment by cvinayak** [comment]
@paulgavrikov ok. I will prepare a PR and let you know soon.
