### ISSUE TITLE
Bluetooth: Move LE Audio from Experimental to unstable

### ISSUE THREAD

**Issue by Thalley** [zephyrproject-rtos/zephyr#72464]
## Introduction
LE Audio have existing in Zephyr for > 5 years (some profile implementations are of course newer). The APIs have been marked as Experimental, both in Kconfig and in the header files, for many years, and while there are still changes, it's mostly stable. 

### Problem description
Having them as experimental generate warnings when enabling them. This warning is no longer meaningful. 

### Proposed change
The proposal is to change the LE Audio APIs from experimental to unstable (as defined by https://docs.zephyrproject.org/latest/develop/api/api_lifecycle.html). 

## Detailed RFC
To move from experimental to unstable is not a hard task, and will not affect development significant, but does give more confidence for users to use the API knowing that it won't suddenly be removed completely. 

### Proposed change (Detailed)
To move from experimental to unstable we need to do the following steps for all LE Audio kconfig files and public header files:

1. Remove `select EXPERIMENTAL` and any mentions of the word in the Kconfig files
2. Remove `[experimental]` and any mention of the word in the public LE Audio header files
3. Add `@version 0.8.0` as per https://docs.zephyrproject.org/latest/develop/api/overview.html#api-overview to each header file to denote them as unstable

### Dependencies
None

### Concerns and Unresolved Questions
None

## Alternatives
None. We cannot (and probably don't want to yet) make them stable, as we are passing the requirements for making the LE Audio APIs stable.

**Comment by asbjornsabo** [comment]
I support this.
The LE Audio APIs are here to stay. And while we still want to make some changes, the LE Audio functionality is quite mature, and (for many parts) has been so for a long while.
