### ISSUE TITLE
i2c: Seems issue in dts

### ISSUE THREAD

**Issue by diytronic** [zephyrproject-rtos/zephyr#7248]
Tried to add i2c device to stm32f103 under Zephyr. After lot of frustrations finally got what here 
https://github.com/zephyrproject-rtos/zephyr/blob/master/arch/arm/soc/st_stm32/stm32f1/dts.fixup#L23 is only configuration for I2C_2, but where is a 1-st port I2C_1? Why it absent here?

Here https://github.com/zephyrproject-rtos/zephyr/blob/1f43e7b684c550737a06319a901badd5054c3499/dts/arm/st/stm32f1.dtsi#L81 we can see i2c_1 present.

Really if you confirm this is a bug I can fix it.

**Comment by ydamigos** [comment]
Hi, thanks for reporting it. I created PR #7250 to fix it.

**Comment by diytronic** [comment]
Great! Thank you
