### ISSUE TITLE
select GPIO is broken

### ISSUE THREAD

**Issue by swift-tk** [zephyrproject-rtos/zephyr#72556]
**Describe the bug**
"select GPIO" spit out dependency loop as of commit id 422092f2d3f.
going back to the last one 80c5f72fe26f44 have no such problem.

This is caused by "select PM_DEVICE if PM" in Kconfig.smartbond

**How to reproduce**

Add select GPIO to Kconfig.mcux
```
config MEMC_MCUX_FLEXSPI
	bool
	select PINCTRL
	select GPIO #add
```

Try
west build -p always -b mimxrt595_evk/mimxrt595s/cm33 samples/drivers/memc

 error log attached
[log.txt](https://github.com/zephyrproject-rtos/zephyr/files/15273036/log.txt)

If I delete "select PM_DEVICE if PM" in Kconfig.smartbond, then it compiles.

**Comment by swift-tk** [comment]
@RichardSWheatley @AlessandroLuo for awareness

**Comment by henrikbrixandersen** [comment]
@ceolin This is power-management related, caused by `select PM_DEVICE if PM` in `drivers/gpio/Kconfig.smartbond`.

**Comment by henrikbrixandersen** [comment]
Introduced in https://github.com/zephyrproject-rtos/zephyr/pull/61857

**Comment by henrikbrixandersen** [comment]
This can be reproduced on `main` without introducing changes by running:
`west build -b ucans32k1sic -p always tests/drivers/can/api/`

**Comment by carlescufi** [comment]
@sjanc this was introduced by Smartbond.

**Comment by sjanc** [comment]
@kasjer FYI

**Comment by swift-tk** [comment]
@andrzej-kaczmarek Hi, a quick fix is appreciated as my PR kind of depending on select GPIO to compile.

**Comment by kasjer** [comment]
@swift-tk working on it, stay tuned...
