### ISSUE TITLE
[Coverity CID :185394] Null pointer dereferences in /subsys/net/ip/l2/ethernet/arp.c

### ISSUE THREAD

**Issue by Shilpashree3lc** [zephyrproject-rtos/zephyr#7261]
Static code scan issues seen in File: /subsys/net/ip/l2/ethernet/arp.c
 Category: Null pointer dereferences
 Function: net_arp_prepare
 Component: Networking
 CID: 185394
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by subbu147** [comment]
I am new to zephyr, and interested in contribution. Can this be assigned to me.

Thanks

**Comment by nashif** [comment]
@subbu147 please submit a PR, it is not possible to assign to you due to how github works, but feel free to submit a fix.

**Comment by jukkar** [comment]
Already fixed by 2002a4e2450ee594ff1be41f31c5b809bc3ec9a5
