### ISSUE TITLE
RTC can't run with BLE enable

### ISSUE THREAD

**Issue by hoangvanloc** [zephyrproject-rtos/zephyr#72616]
- I run project ncs\v2.5.3\zephyr\samples\drivers\counter\alarm success.
- When I add # CONFIG_BT=y log show 
*** Booting nRF Connect SDK v2.5.3 ***
Counter alarm sample

Set alarm in 2 sec (65536 ticks)

It mean RTC alarm callback can't be call.

**Comment by henrikbrixandersen** [comment]
Thank you for reporting this. However - unless you are able to reproduce this issue with upstream Zephyr `main` - please report issues with the nRF Connect SDK (NCS) on the [Nordic Semiconductor DevZone](https://devzone.nordicsemi.com/).
