### ISSUE TITLE
ISM330DHCX driver: wrong FS bitmask for gyroscope calculated 

### ISSUE THREAD

**Issue by DeMurlot** [zephyrproject-rtos/zephyr#72617]
**Describe the bug**
The driver for the ism330dhcx incorrectly calculates the bitmap for the fs bits in the CTRL2_G register. The driver uses the ST hal to set the values, but hands over an incorrect bitmask leading to wrong configuration.

HAL values for given FS: https://github.com/zephyrproject-rtos/hal_st/blob/b77157f6bc4395e398d90ab02a7d2cbc01ab2ce7/sensor/stmemsc/ism330dhcx_STdC/driver/ism330dhcx_reg.h#L2894
Zephyr driver logic for getting the value from the devicetree: https://github.com/zephyrproject-rtos/zephyr/blob/be682e22e166c33a67c1db0755f8ca20c37b6576/drivers/sensor/st/ism330dhcx/ism330dhcx.c#L70C2-L70C17

in my opinion, the lines in the zephyr driver should be
```
static const uint16_t ism330dhcx_gyro_fs_map[] = {250, 4000, 125, 4000, 500, 4000, 125, 4000, 1000, 4000, 125, 4000, 2000};
static const uint16_t ism330dhcx_gyro_fs_sens[] = {2, 32, 1, 32, 4, 32, 1, 32, 8, 32, 1, 32, 16};
```

In addition the devicetree binding should be adapted to allow a FS value of 4000 (dps).

For convenience, here is a screenshot from the datasheet: 
![image](https://github.com/zephyrproject-rtos/zephyr/assets/108518291/d15ae143-4d75-4bd5-b4dc-1f7a10d71be8)
And the link to how the ST HAL parses this value: https://github.com/zephyrproject-rtos/hal_st/blob/b77157f6bc4395e398d90ab02a7d2cbc01ab2ce7/sensor/stmemsc/ism330dhcx_STdC/driver/ism330dhcx_reg.h#L357

**To Reproduce**
Not applicable

**Expected behavior**
The devicetree full-scale property for gyroscope to be correctly applied.

**Impact**
Unintended FS selection and wrong gyroscope readings, since raw to dps conversion is intended sensitivity but not the actual one.

**Comment by MaureenHelm** [comment]
@avisconti please take a look
