### ISSUE TITLE
[Coverity CID :185393] Memory - illegal accesses in /drivers/interrupt_controller/plic_fe310.c

### ISSUE THREAD

**Issue by Shilpashree3lc** [zephyrproject-rtos/zephyr#7262]
Static code scan issues seen in File: /drivers/interrupt_controller/plic_fe310.c
 Category: Memory - illegal accesses
 Function: plic_fe310_irq_handler
 Component: Drivers
 CID: 185393
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by nashif** [comment]
dismissed as false positive
