### ISSUE TITLE
[Coverity CID :185392] Null pointer dereferences in /drivers/spi/spi_dw.c

### ISSUE THREAD

**Issue by Shilpashree3lc** [zephyrproject-rtos/zephyr#7263]
Static code scan issues seen in File: /drivers/spi/spi_dw.c
 Category: Null pointer dereferences
 Function: transceive
 Component: Drivers
 CID: 185392
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by tbursztyka** [comment]
it was set as false positive in coverity
