### ISSUE TITLE
samples: drivers: mbox: sample.drivers.mbox.nrf54h20_vevif and sample.drivers.mbox.nrf54h20_bellboard fails at nrf54h20

### ISSUE THREAD

**Issue by nordic-piks** [zephyrproject-rtos/zephyr#72661]
**Describe the bug**
The samples/drivers/mbox/sample.drivers.mbox.nrf54h20_vevif and samples/drivers/mbox/sample.drivers.mbox.nrf54h20_bellboard

Observed for
- nrf54h20dk/nrf54h20/cpuapp

**To Reproduce**
1. have nrf54h20dk/nrf54h20/cpuapp connected
2. go to your zephyr dir
3. call ./scripts/twister -T samples/drivers/mbox -p nrf54h20dk/nrf54h20/cpuapp--device-testing --device-serial /dev/ttyACM0 -v --inline-logs
4. See console output with error

**Expected behavior**
Valid console output

**Impact**
Not clear

**Logs and console output**
```
*** Booting Zephyr OS build v3.6.0-3753-gbe682e22e166 ***
Hello from APP
```
Missing: 
```
Pong (on channel 0)
Ping (on channel 1)
```

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04.1 LTS
 - Toolchain Zephyr SDK 0.16.5
 - Commit SHA or Version used: v3.6.0-3753-gbe682e22e166

**Comment by gmarull** [comment]
Something must be broken on your setup. First, 54H20 has never used channels 0/1, so logs are likely wrong.

Then, I've tested this successfully (it's true that required a few retries, not sure what twister is doing because the application behaves correctly):
```
west twister -p nrf54h20dk/nrf54h20/cpuapp --device-testing --device-serial /dev/ttyACM0 -s sample.drivers.mbox.nrf54h20_app_ppr -T samples/drivers/mbox --west-flash -vv
```

```
west twister -p nrf54h20dk/nrf54h20/cpurad --device-testing --device-serial /dev/ttyACM1 -s sample.drivers.mbox.nrf54h20_rad_app -T samples/drivers/mbox --west-flash -vv
```
