### ISSUE TITLE
nrf5340 build fail

### ISSUE THREAD

**Issue by Wise-scholar-Li** [zephyrproject-rtos/zephyr#72670]
[3/10] Linking C executable zephyr\zephyr_pre0.elf
FAILED: zephyr/zephyr_pre0.elf zephyr/zephyr_pre0.map D:/project_ble/1-init/2.SW/v2.6.0/nrf/samples/bluetooth/peripheral_uart/build/hci_ipc/zephyr/zephyr_pre0.map 
cmd.exe /C "cd . && D:\project_ble\1-init\2.SW\v2.6.0\toolchains\toolchains\cf2149caf2\opt\zephyr-sdk\arm-zephyr-eabi\bin\arm-zephyr-eabi-gcc.exe  -gdwarf-4 @CMakeFiles\zephyr_pre0.rsp -o zephyr\zephyr_pre0.elf  && cmd.exe /C "cd /D D:\project_ble\1-init\2.SW\v2.6.0\nrf\samples\bluetooth\peripheral_uart\build\hci_ipc\zephyr && D:\project_ble\1-init\2.SW\v2.6.0\toolchains\toolchains\cf2149caf2\opt\bin\cmake.exe -E true""
d:/project_ble/1-init/2.sw/v2.6.0/toolchains/toolchains/cf2149caf2/opt/zephyr-sdk/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/../../../../arm-zephyr-eabi/bin/ld.bfd.exe: cannot open linker script file zephyrlinker_zephyr_pre0.cmd: No such file or directory
collect2.exe: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.

**Comment by henrikbrixandersen** [comment]
Please reopen when bug report template has been filled in.
