### ISSUE TITLE
rtio: Possibly missed callback when linking

### ISSUE THREAD

**Issue by teburd** [zephyrproject-rtos/zephyr#72740]
**Describe the bug**
@swift-tk had a question in [discord](https://discord.com/channels/720317445772017664/902932500672827432/1238438721729204295) that lead to me believing a bug exists in the current way we do callback ops.

We currently do callback ops only on submit https://github.com/zephyrproject-rtos/zephyr/blob/main/subsys/rtio/rtio_executor.c#L65

But not if they are chained from a completion https://github.com/zephyrproject-rtos/zephyr/blob/main/subsys/rtio/rtio_executor.c#L164

A test should easily show this to be reproducible when fixing.

**Expected behavior**
Linked callback ops occur after the ops they are linked to complete

**Impact**
Out of order operations are possible

**Comment by aescolar** [comment]
@teburd as you are the maintainer of RTIO, you are probably the best to assign this bug a priority. 
Would you be so kind as to do so?
