### ISSUE TITLE
spi_context_Lock leakage when exception occurs

### ISSUE THREAD

**Issue by foxriver1025** [zephyrproject-rtos/zephyr#72782]
https://github.com/zephyrproject-rtos/zephyr/blob/d0ae1a8b1057c0a8b510860d1cbdbb1cb79f2411/drivers/spi/spi_andes_atcspi200.c#L649

Here, spi_context_release is not called before the return error, causing the lock to be leaked.

**Comment by tbursztyka** [comment]
Easy fix, just replace that line into a goto out, and put the out: label at line 658. Can you send a patch?

**Comment by henrikbrixandersen** [comment]
Please use our bug template when reporting bugs. You need to edit this issue to include the information requested in https://github.com/zephyrproject-rtos/zephyr/blob/main/.github/ISSUE_TEMPLATE/001_bug_report.md

**Comment by nashif** [comment]
@tbursztyka  can you send a patch please?
