### ISSUE TITLE
STM32H743 + more: DMA stream locked when transferring data to/from USART

### ISSUE THREAD

**Issue by HelligeChris** [zephyrproject-rtos/zephyr#72790]
**Describe the bug**
Using the UART async driver, when a USART is issuing a DMA request to transfer data, if a concurrent transfer occurs, the requested transfer may not be served, and the DMA stream may stay locked. This causes the UART async driver to lock up and stop sending packages (uart_tx keeps reporting EBUSY).

**To Reproduce**
Using the board stm32h743Xi.dtsi

1. Use UART async driver
2. Setup DMA to use another stream and trigger on timer (we used a DMA to update DAC output at 1MHz)
4. Create while loop that keeps sending messages through UART
5. The fault is sporadic, though on our system the UART sent 3~10 messages before locking up

**Expected behavior**
The UART kept sending messages without locking up

**Impact**
We used a workaround where we manually set bit 20 in DMA_SxCR on UART streams.

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain GCC 12.3.1
 - Zephyr 3.6.0

**Additional context**
Issue is described in the [stm32h7 errata](https://www.st.com/resource/en/errata_sheet/dm00368411-stm32h742xi-g-and-stm32h743xi-g-device-limitations-stmicroelectronics.pdf) section 2.20.6 and effect the following microcontrollers:

* STM32H742xI/G
* STM32H743xI/G
*  STM32H750xB
* STM32H753xI

**Comment by henrikbrixandersen** [comment]
Please use our bug template when reporting bugs. You need to edit this issue to include the information requested in https://github.com/zephyrproject-rtos/zephyr/blob/main/.github/ISSUE_TEMPLATE/001_bug_report.md

**Comment by HelligeChris** [comment]
> Please use our bug template when reporting bugs. You need to edit this issue to include the information requested in https://github.com/zephyrproject-rtos/zephyr/blob/main/.github/ISSUE_TEMPLATE/001_bug_report.md

Hey, I reformatted the issue, though the "Steps to reproduce" section leaves much to be desired...

**Comment by ajarmouni-st** [comment]
Hi @HelligeChris

>  if a concurrent transfer occurs,

By this you mean another UART DMA transfer or just another DMA transfer from any other device?

**Comment by ajarmouni-st** [comment]
> Hi @HelligeChris
> 
> > if a concurrent transfer occurs,
> 
> By this you mean another UART DMA transfer or just another DMA transfer from any other device?

okey. I just noticed

> we used a DMA to update DAC output at 1MHz

So it's the 2nd case right?

**Comment by HelligeChris** [comment]
Hi @ajarmouni-st, from what I can see in the errata it shouldn't matter if it's a UART DMA transfer or DMA transfer to the DAC. Since both the UART and DAC request the DMA to transfer data,  though we only noticed it when using the DMA to update the DAC while the also having the UART running. 

This is properly because the DAC was request DMA transfers so quickly.

**Comment by aescolar** [comment]
@ajarmouni-st as there is no assignee, this PR pops up for triaging again. Should be consider this issue resolved?

**Comment by dakejahl** [comment]
Any updates on this? I am having the same problem in NuttX and simply setting the TRBUFF bit doesn't solve the issue as the errata suggests.
