### ISSUE TITLE
if we have two flash on board?

### ISSUE THREAD

**Issue by zhxianbin** [zephyrproject-rtos/zephyr#7280]
for example,if we have two flash W25QXX on board, but DEVICE_INIT just defined one, we should copy and paste ?

**Comment by MaureenHelm** [comment]
You can copy the DEVICE_INIT, but make sure to give the new instance a different name. You'll also need to create a new instance of `struct spi_flash_data`. Is this on the arduino 101 board?

**Comment by zhxianbin** [comment]
thank for your answer！it is not arduino 101 board，I just read the source and find the issue.
I think we should find a more effective method! but i have no idea.
