### ISSUE TITLE
Support of Flash and EEPROM drivers for SoC S32K1 (NXP)

### ISSUE THREAD

**Issue by vChavezB** [zephyrproject-rtos/zephyr#72952]
**Is your feature request related to a problem? Please describe.**

The support of the S32K1 SoC is not entirely complete. See e.g., https://github.com/zephyrproject-rtos/zephyr/issues/22594 .

Currently there is no Zephyr integration of the EEPROM and Flash drivers from the MCUX SDK (The SDK from NXP).

**Describe the solution you'd like**

Integration of the MCUX drivers (https://github.com/zephyrproject-rtos/hal_nxp/tree/master/mcux/mcux-sdk/drivers/flash) for use of the Flash and EEPROM.

**Describe alternatives you've considered**

Manual integration of the aforementioned mcux drivers, use of not official device tree to integrate the driver, and application note AN12323SW.

I discussed this briefly in https://github.com/zephyrproject-rtos/hal_nxp/pull/382 with @manuargue .

**Comment by manuargue** [comment]
NXP currently don't have plans to support S32K1 devices. Community contributions to extend existing support are welcome. If further questions about NXP plans, please reach out to https://community.nxp.com/
