### ISSUE TITLE
minnowboard DTS is not configured correctly

### ISSUE THREAD

**Issue by andrewboie** [zephyrproject-rtos/zephyr#7309]
According to marketing materials, minnowboard has 2GB of RAM and 4MB of flash.

However, our minnowboard.dts has this:

```
#define DT_FLASH_SIZE		__SIZE_K(72)

#if XIP
	#define DT_SRAM_SIZE		__SIZE_K(128)
#else
	#define DT_SRAM_SIZE		__SIZE_K(256)
#endif
```

Two problems:
1. These values are way too small.
2. The board either uses XIP or it doesn't. AFAIK minnowboard has a bootloader so it doesn't. We should NOT have ifdef XIP here.

**Comment by andrewboie** [comment]
This is even worse than I previously suspected -- the build is not using the DT_SRAM_SIZE definition in DTS anyway, it's still getting the data from somewhere else. Was this ever tested??

**Comment by andrewboie** [comment]
OK this needs major cleanup.
The RAM size is currently coming from arch/x86/soc/atom/Kconfig.defconfig via CONFIG_RAM_SIZE and CONFIG_ROM_SIZE.
For ATOM the RAM/ROM size needs to be expressed on a per BOARD basis, and derived from DTS.

**Comment by SavinayDharmappa** [comment]
RAM ,ROM and XIP data are  derived from arch/x86/soc/atom/Kconfig.defconfig.

**Comment by nashif** [comment]
@SavinayDharmappa ping, are you looking into this?

**Comment by SavinayDharmappa** [comment]
yeah. None of x86 boards derive RAM and ROM size from dts. So I am moving all boards boards to derive RAM and ROM size from dts. Will push the patch by EOD

**Comment by SavinayDharmappa** [comment]
https://github.com/zephyrproject-rtos/zephyr/pull/7451/commits/467983ab9b4051825083dfb77e8bb8188dc08afa
