### ISSUE TITLE
FCB: CRC write size in append_finish doesn't honor flash min write size

### ISSUE THREAD

**Issue by mike-scott** [zephyrproject-rtos/zephyr#7311]
In append_finish:
https://github.com/zephyrproject-rtos/zephyr/blob/master/subsys/fs/fcb/fcb_append.c#L127

The CRC write is aligned at the offset, but the write size itself will always be 1.  So on HW like K64F where a minimum write size of 8 is needed, this write fails.

**Comment by nvlsianpu** [comment]
CC @lemrey @carlescufi

**Comment by mike-scott** [comment]
Fixed by: https://github.com/zephyrproject-rtos/zephyr/pull/7343
