### ISSUE TITLE
Contributor nomination: valeriosetti

### ISSUE THREAD

**Issue by valeriosetti** [zephyrproject-rtos/zephyr#73127]
## GitHub User

Provide the following information about the GitHub user:

1. Valerio Setti
1. valeriosetti
1. BayLibre

## Supporting Documents

Ongoing:
https://github.com/zephyrproject-rtos/zephyr/pull/73061
https://github.com/zephyrproject-rtos/zephyr/pull/73049
https://github.com/zephyrproject-rtos/zephyr/pull/72243

Merged:
https://github.com/zephyrproject-rtos/zephyr/pull/72747
https://github.com/zephyrproject-rtos/zephyr/pull/71830
https://github.com/zephyrproject-rtos/zephyr/pull/71827
https://github.com/zephyrproject-rtos/zephyr/pull/51236
https://github.com/zephyrproject-rtos/zephyr/pull/49694
https://github.com/zephyrproject-rtos/zephyr/pull/43934
https://github.com/zephyrproject-rtos/zephyr/pull/43607

**Comment by tomi-font** [comment]
@ceolin @d3zd3z @dleach02 @MaureenHelm @carlescufi @aescolar

**Comment by ceolin** [comment]
+1 for sure.

**Comment by dleach02** [comment]
+1... is this our process?

**Comment by pamolloy** [comment]
:+1:

**Comment by carlescufi** [comment]
@valeriosetti wouldn't you rather become a collaborator here:
https://github.com/zephyrproject-rtos/zephyr/blob/41389fbb818616fa1f1127be4a87f1c183a9ab09/MAINTAINERS.yml#L2432

and here:

https://github.com/zephyrproject-rtos/zephyr/blob/41389fbb818616fa1f1127be4a87f1c183a9ab09/MAINTAINERS.yml#L3901

More info here:

https://docs.zephyrproject.org/latest/project/project_roles.html#collaborator

**Comment by carlescufi** [comment]
+1 from me too

**Comment by nashif** [comment]
https://github.com/zephyrproject-rtos/zephyr/invitations
