### ISSUE TITLE
Error : undefined reference when using a function from 'lz4frame.h'.

### ISSUE THREAD

**Issue by bubilili** [zephyrproject-rtos/zephyr#73262]
**Describe the bug**

 I am developing a Zephyr project for an STM32 H747BIT6. I'm trying to use LZ4 frame for message compression.
So I added `#include "lz4frame.h"` to a source cpp file and then tried to use 'LZ4F_compressFrameBound(input_size, NULL)'. As in the code snippet below..

`std::vector<uint8_t> LZ4MessageCompression::compress_frame(const std::string &input) 
{
	LOG_INF("compress input: %s", input.c_str());

	/* Cal input size for mem allocation */
	const size_t input_size = input.size();
        const int dst_size = LZ4F_compressFrameBound(input_size, NULL);
}
`
When I compiled the project I got this error `undefined reference to `LZ4F_compressFrameBound'`

The prj.conf contains `CONFIG_LZ4=y`
I was able to use `LZ4_compressBound` with `lz4.h`included.

**Environment**
 - OS: MacOS Sonoma 14.5
 - CMake version: 3.28.3
 - Zephyr version: 3.5.0

**Comment by parthitce** [comment]
@bubilili not sure if you are still looking to work with lz4 for the mentioned usecase. If so, I have tried adding the needed files and compiled the lz4 frametest sample in zephyr.

I can add the support officially into zephyr samples once https://github.com/zephyrproject-rtos/zephyr/pull/76184 is merged.

changes are here: https://github.com/zephyrproject-rtos/zephyr/compare/main...linumiz:zephyr:fix/zephyr/73262
