### ISSUE TITLE
Interrupt stack is not initialized for Xtensa target

### ISSUE THREAD

**Issue by aborany** [zephyrproject-rtos/zephyr#7327]
On Xtensa target the configuration CONFIG_INIT_STACKS is not properly applied to the _interrupt_stack. The IRQ stack stays uninitialized instead of being initialized with 0xAA, which makes it hard to analyze any stack size issues. Furthermore when configuring CONFIG_STACK_SENTINEL the sentinel 0xF0F0F0F0 is also not set to the upper most 32-Bits of the interrupt stack.

**Comment by andrewboie** [comment]
CONFIG_STACK_SENTINEL is only for thread stacks.
However CONFIG_INIT_STACKS not setting the IRQ stack to 0xAA is definitely a bug.

**Comment by aborany** [comment]
Agree that CONFIG_STACK_SENTINEL is only for thread stack at the moment, but maybe this would be also an enhancement for the interrupt_stack in the future. Maybe it is worth to check that the interrupt stack did not overflow when leaving the interrupt and in case of overflow raise another exception, which would end up as double exception in the case of Xtensa architecture.

**Comment by andrewboie** [comment]
> Agree that CONFIG_STACK_SENTINEL is only for thread stack at the moment, but maybe this would be also an enhancement for the interrupt_stack in the future.

Patches are welcome if you want to implement that for all our arches, but the scope of this ticket is limited to CONFIG_INIT_STACKS on Xtensa.
