### ISSUE TITLE
mqtt_azure example uses the Baltimore certificate

### ISSUE THREAD

**Issue by uriel-kluk** [zephyrproject-rtos/zephyr#73281]
### Summary
_Azure IoT Hub and Device Provisioning Service (DPS) use TLS certificates issued by the Baltimore CyberTrust Root, which expires in 2025. Starting in February 2023, all IoT hubs in the global Azure cloud will migrate to a new TLS certificate issued by the DigiCert Global Root G2._

### Details
_The example provided conatins a file named `digicert.cer`, but it contains the `Baltimore CyberTrust Root`. The solution should include `DigiCert Global Root G2` instead._

### Reproduce

1. Run the example as is, entering the username, password, and hostname in the configuration.
2. Observe the following error:

```text
[00:00:11.336,000] <dbg> mqtt_azure: try_to_connect: attempting to connect...
[00:00:11.401,000] <err> net_sock_tls: Failed to parse CA certificate, err: -0xfffffffe
```

3. Replace the certificate using the certificates provided [here](https://github.com/Azure/azure-iot-sdk-c/blob/main/certs/certs.c).
4. Observe that the same error persists.
5. Change the certificate to include only the DigiCert Global Root G2.
6. Observe the new error:
```text
[00:00:16.308,000] <dbg> mqtt_azure: try_to_connect: attempting to connect...
[00:00:16.420,000] <err> net_sock_tls: TLS handshake error: -0x7280
[00:00:16.430,000] <err> mqtt_azure: mqtt_connect failed -113
```

### Impact
It might be my configuration that is failing, but if developers base their code on the example provided, devices will stop connecting in 2025.

**Comment by uriel-kluk** [comment]
Thanks Robert,

Here is the PR, but heads up, it is having trouble parsing the CA certificates:
Add SHA1 to project configuration and added new certificates to conne… by uriel-kluk · Pull Request #73426 · zephyrproject-rtos/zephyr (github.com)<https://github.com/zephyrproject-rtos/zephyr/pull/73426>

You should reject the PR
________________________________

**Comment by rlubos** [comment]
I've opened https://github.com/zephyrproject-rtos/zephyr/pull/73557 with the fixes discussed.

**Comment by uriel-kluk** [comment]
Great job! Thanks

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
