### ISSUE TITLE
ICM42688 is not configurable from DTS and gyro does not work with sensor shell

### ISSUE THREAD

**Issue by bperseghetti** [zephyrproject-rtos/zephyr#73296]
**Describe the bug**

Please also mention any information which could help others to understand
the problem you're facing:
 - Using platform VMU_RT1170
 - Unable to set params for ICM42688 from dts (just overrides with fixed values at lowest settings that clip in most use cases): https://github.com/zephyrproject-rtos/zephyr/blob/68bd4da4c64ca0c19cee0334bee6496ec8cde2b9/drivers/sensor/tdk/icm42688/icm42688.c#L274-L286

Also sensor shell does not work properly for gyro:
![Screenshot_from_2024-05-25_11-50-17](https://github.com/zephyrproject-rtos/zephyr/assets/10233412/b8918323-98a6-42a5-b0b5-4fe6f667b2e0)

**To Reproduce**
1. Attempt to set sensor attributes with DTS for ICM42688
2. Test shaking and see it locks to 125 deg/sec (hard coded gyro FS)
3. Run sensor shell and see it does not output gyro 

**Expected behavior**
Sensor should be configurable and sensor shell should work for the gyro.

**Impact**
Makes sensor not work as expected.

**Comment by teburd** [comment]
Thanks for the report, I’ll try and take a look next week

**Comment by teburd** [comment]
The shell issue seems tied to the way the sensor_shell currently works, and @ycsin noted issues as well in #72841 and related PRs/issues. I'm looking at this, and it is a bug but I don't think its solely tied to this driver. Notably if I force using the fetch + channel_get API with some Kconfig hacks the gyro works mostly fine

**Comment by ycsin** [comment]
Should be the same as #72840

**Comment by teburd** [comment]
Not quite fixed, needs #74267 still

**Comment by teburd** [comment]
Fixed as #74267 is merged
