### ISSUE TITLE
is there has anyone who having portting stm32f2?

### ISSUE THREAD

**Issue by zhaozhongchen** [zephyrproject-rtos/zephyr#7329]

**Comment by erwango** [comment]
Hi,

I haven't heard anyone working on STM32F2 till now.
Your contribution would be welcome though, if you're interested.

You could use https://github.com/zephyrproject-rtos/zephyr/pull/5949 as example

Erwan

**Comment by zhaozhongchen** [comment]
@erwango thanks and I will have a try.

**Comment by zhaozhongchen** [comment]
I am portting stm32f2 to zephyr, if someone interested can based on my branch: stm32f2
