### ISSUE TITLE
setting adc_prescaler in st,stm32f1-rcc node produces build failure

### ISSUE THREAD

**Issue by kuroneko** [zephyrproject-rtos/zephyr#73375]
**Describe the bug**
Setting the adc prescaler on the stm32f1 rcc node produces a build failure due to a missing definition for `adc_prescaler`.

**To Reproduce**

Include `adc-prescaler` in your rcc on a stm32f103 family MCU ala:

```
&rcc {
    clocks = <&pll>;
    clock-frequency = <DT_FREQ_M(72)>;
    ahb-prescaler = <1>;
    apb1-prescaler = <2>;
    apb2-prescaler = <1>;
    adc-prescaler = <6>;
};
```

Builds fail with:
```
/opt/zephyr-sdk-0.16.5/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/../../../../arm-zephyr-eabi/bin/ld.bfd: zephyr/drivers/clock_control/libdrivers__clock_control.a(clock_stm32_ll_common.c.obj): in function `stm32_clock_control_init':
...projectpath.../zephyr/drivers/clock_control/clock_stm32_ll_common.c:805: undefined reference to `adc_prescaler'
```

Checking clock_stm32_ll_common.c shows that it needs a defintion for `adc_prescaler` but that is absent.  The correct definition appears to be in `clock_stm32f0_f3.c`.

**Expected behavior**
Build to complete

**Impact**
Showstopper for anybody needing ADC support on STM32F1.  (however, we've now worked around this in our own fork by copying the definition as noted above).

**Environment (please complete the following information):**
 - OS: MacOS
 - Toolchain: Zephy SDK 0.16.5 macos-arm64
 - Checked against: v3.5-branch

**Comment by FRASTM** [comment]
@kuroneko thanks for reporting this build failure
As a 1st analysis, I see that adc_prescaler from the drivers/clock_control/clock_stm32f1.c  is not evaluated at the time the drivers/clock_control/clock_stm32_ll_common.c is being built
So I suggest to include the 
```
#define z_adc_prescaler(v) LL_RCC_ADC_CLKSRC_PCLK2_DIV_ ## v
#define adc_prescaler(v) z_adc_prescaler(v)

``` 
directly in the **drivers/clock_control/clock_stm32_ll_common.c** as another "/* Macros to fill up prescaler values */"
(and remove if from the clockf1 or clockf0_f3) It will not disturb the macro definition
