### ISSUE TITLE
ESP32C3 ADC does not work along with the MCUboot.

### ISSUE THREAD

**Issue by rana-roy** [zephyrproject-rtos/zephyr#73400]
**Describe the bug**
The sample [zephyr/samples/drivers/adc](https://github.com/zephyrproject-rtos/zephyr/tree/main/samples/drivers/adc) builds successfully for the **esp32c3_devkitm** in both cases, the simple west build and sysbuild for MCUboot. 
The issue is when I just use the west build, it displays the console logs for the ADC readings, while in case of sysbuild, it does not display any logs over the console.

**To Reproduce**
1. west build --sysbuild -b esp32c3_devkitm .
2. west flash

**Expected behavior**
The logs should be visible over the console for both the builds.

**Environment:**
- OS: Ubuntu 22.04.4 LTS
- Toolchain: Zephyr SDK 0.16.5 & MCUboot with rev 9bf7ce8c5fe8152836a6e00bd4444153bd950342
- Board: ESP32C3 devkitm (development board)

**Comment by de-nordic** [comment]
Can you confirm that the same sample works without MCUboot first.
There is possibility that there is something not properly de-initialized before control is passed to an application and was accidentally initialized while executing MCUboot.

**Comment by rana-roy** [comment]
> Can you confirm that the same sample works without MCUboot first.

Yes, both the things work properly when they are handled individually. 

The ADC counts are proper when the sample is built without sysbuild. And, the MCUboot works when built with another sample code.

**Comment by de-nordic** [comment]
How other sample works with MCUboot does not matter. We need to figure out whether MCUboot affects this specific sample.

Can you build the ADC sample for MCUBoot without sysbuild and MCUboot separately, upload those to pre-erased board and check if that shows the same symptoms?
To build application for MCUboot you need to set CONFIG_BOOTLOADER_MCUBOOT=y.

**Comment by rana-roy** [comment]
> Can you build the ADC sample for MCUBoot without sysbuild and MCUboot separately, upload those to the pre-erased board, and check if that shows the same symptoms?
> To build the application for MCUboot you need to set CONFIG_BOOTLOADER_MCUBOOT=y.

Thank you for getting back to me so quickly. I followed the steps you suggested:
1. Erased the board using the esptool.py erase_flash
2. Built and flashed the MCUboot separately using ninja -C build/ flash from the bootloader/mcuboot/boot/espressif
3. Added the macro in the prj.conf file
4. Built and flashed the Zephyr ADC sample code into the ESP32C3 devkitm

The behavior of the board is expected. I can get the ADC readings on the console.

**Comment by rana-roy** [comment]
**https://github.com/zephyrproject-rtos/zephyr/pull/73480**.
Thank you for your support!
You have mentioned the ESP32-S3 chip. But, I am facing an issue with the ESP32-C3 chip.

**Comment by de-nordic** [comment]
> 
> Thank you for getting back to me so quickly. I followed the steps you suggested:
> 
>     1. Erased the board using the esptool.py erase_flash
> 
>     2. Built and flashed the MCUboot separately using ninja -C build/ flash from the bootloader/mcuboot/boot/espressif
> 
>     3. Added the macro in the prj.conf file
> 
>     4. Built and flashed the Zephyr ADC sample code into the ESP32C3 devkitm
> 
> 
> The behavior of the board is expected. I can get the ADC readings on the console.

OK so it does not be seem to be issue with MCUboot,

> **#73480**. Thank you for your support! You have mentioned the ESP32-S3 chip. But, I am facing an issue with the ESP32-C3 chip.

@marekmatej Do you maybe have any ideas here? And why separate building MCUboot and app seems to work?

**Comment by marekmatej** [comment]
> 2\. Built and flashed the MCUboot separately using ninja -C build/ flash from the bootloader/mcuboot/boot/espressif

@rana-roy The `boot/zephyr` is used in Espressif port of MCUboot. To build the MCUboot Zephyr port please use `boot/zephyr`. The Zephyr port is used during the `--sysbuild`. 

@de-nordic The recent changes in Zephyr bring additional code to `iram0.text` section, which size was optimised in MCUboot Zephyr port. This can be fixed easily by increasing the segment length, but there are related issues in other SOCs, which we are fixing now. This is a memory fix PR https://github.com/zephyrproject-rtos/zephyr/pull/73292 preceding the current issue.

The reason for separate build works is because `--sysbuild` is using sources from west.yml, while separate build use the sources you choose to use.

**Comment by de-nordic** [comment]
> > And why separate building MCUboot and app seems to work?
> 
> The reason for separate build works is because `--sysbuild` is using sources from west.yml, while separate build use the sources you choose to use.

Thanks, I have not noticed that different MCUboot path is used.

**Comment by de-nordic** [comment]
@rana-roy Is the issue still present after https://github.com/zephyrproject-rtos/zephyr/pull/73292 got merged?

**Comment by de-nordic** [comment]
@rana-roy Can you verify whether issue is there and close the report if does not apply anymore?

**Comment by sylvioalves** [comment]
Tested esp32c3_devkitm with `samples/drivers/adc/adc_dt`. Works with https://github.com/zephyrproject-rtos/zephyr/pull/75533

**Comment by rana-roy** [comment]
My apologies for the long delay as I was occupied with another task.

Now, I have cloned the latest Zephyr release with the tag: Zephyr v3.7.0.
I tried to build my custom code using --sysbuild, but it shows the iram_segment overflow error. So, I tried with the blinky_pwm sample code with the following configurations:
**Sample**: blinky_pwm
**Board**: esp32c3_devkitm
**Zephyr SDK**: 0.16.8
**Zephyr Version**: 3.7.0 (LTS)
**Build configs**: west build with --sysbuild
**Command**: west build --sysbuild -b esp32c3_devkitm .

The results are memory overflow errors and other multiple errors. Attached is the log file containing the build logs for your reference:
[zephyr_build_err.txt](https://github.com/user-attachments/files/16729264/zephyr_build_err.txt)

**Comment by rana-roy** [comment]
I am trying to clone the Zephyr using commit IDs: 
adec316cd7f5edcfb70a0e6c37989e80e75c9f07 
3416f9ab47cef05308f635a1d8af0a10a36b4556 in my west.yml file, but it shows the update error:
**FATAL ERROR: command exited with status 128: rev-parse 'adec316cd7f5edcfb70a0e6c37989e80e75c9f07^{commit}'**

The west.yml file contents are as follows:
manifest:
  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
      
  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      repo-path: zephyr
      clone-depth: 1
      west-commands: scripts/west-commands.yml
      revision: adec316cd7f5edcfb70a0e6c37989e80e75c9f07 # v3.7.0  # zephyr-v3.5.0
      import:
        name-allowlist:
          - hal_espressif
    - name: mcuboot
      remote: zephyrproject-rtos
      revision: 9bf7ce8c5fe8152836a6e00bd4444153bd950342
      path: bootloader/mcuboot
    - name: tinycrypt
      remote: zephyrproject-rtos
      revision: master
      path: modules/crypto/tinycrypt
      groups:
        - crypto
    - name: mbedtls
      remote: zephyrproject-rtos
      revision: v3.0.0 # zephyr
      path: modules/crypto/mbedtls
      groups:
        - crypto
    - name: zcbor
      remote: zephyrproject-rtos
      revision: release/0.6.1
      path: modules/lib/zcbor

self:
    path: Dev_Board
    
I want to know if I am missing out on something. Any references will be great.

**Comment by rana-roy** [comment]
I appreciate your support. I can resolve the issue by updating the version of **mcuboot**.
