### ISSUE TITLE
doc: Documentation issue in 'kernel/services/data_passing/pipes'

### ISSUE THREAD

**Issue by Xcross74** [zephyrproject-rtos/zephyr#73419]
**No mention of CONFIG_PIPE=y in documentation**

<< This page doesn't mention that the prj.conf should enable CONFIG_PIPE=y to allow pipes to be used.  >>

**Environment**

* Page: `kernel/services/data_passing/pipes`
* Version: main
* SHA-1: 3fab7624eb4b31dd6caa33ad50adb18b51cc9a60

**Comment by andyross** [comment]
Calling not-it and bouncing to @peter-mitsis as he's touched pipes most recently :)

**Comment by peter-mitsis** [comment]
Although the page in question does list the CONFIG_PIPES Kconfig option, it does not provide a link to its description. I expect that fixing the documentation to generate the link ought to be sufficient as it will then bring the pipes page into alignment with other kernel documentation pages whose features need a Kconfig option to be enabled to use the feature (e.g. polling, events).
