### ISSUE TITLE
STM32WB5MM-DK Button support

### ISSUE THREAD

**Issue by QuentinCaldeira-eaton** [zephyrproject-rtos/zephyr#73414]
**Is your feature request related to a problem? Please describe.**
I tried to add support for both buttons on the STM32WB5MM-DK. I guess both are mapped to PC12 and PC13 according to the doc.

**Describe the solution you'd like**
I add these to `stm32wb5mm_dk.dts`, but it don't work. To test I used the button sample. The first button doesn't trigger, and the second button trigger once then no interruption is detected.

```c
gpio_keys {
		compatible = "gpio-keys";
		user_button1: button {
			label = "BTN_USR1";
			gpios = <&gpioc 12 GPIO_ACTIVE_LOW>;
			zephyr,code = <INPUT_KEY_0>;
		};
	};
```

```c
aliases {
            watchdog0 = &iwdg;
            die-temp0 = &die_temp;
            volt-sensor0 = &vref;
            volt-sensor1 = &vbat;
            led-strip = &rgb_led_strip;
            sw0 = &user_button1;
};
```

**Comment by ajarmouni-st** [comment]
Hi @QuentinCaldeira-eaton did you try adding `GPIO_PULL_UP` flag to `gpios`?

**Comment by QuentinCaldeira-eaton** [comment]
It seems to be the issue. Thanks ! Do I have to add it in the current dts of the board and made a PR ? I'm working with an overlay rn so it doesn't matter for me.

**Comment by ajarmouni-st** [comment]
> Do I have to add it in the current dts of the board and made a PR

Yes, that would be great !
