### ISSUE TITLE
apollo4p_blue_kxr_evb: Multiple samples/tests fails to build in CI due to warnings

### ISSUE THREAD

**Issue by aescolar** [zephyrproject-rtos/zephyr#73443]
**Describe the bug**

* samples/subsys/llext/shell_loader/
* tests/kernel/cache/*
* tests/subsys/llext/simple/*
* samples/subsys/llext/shell_loader/

Build with warnings due to a missing CMSIS header , which are promoted to errors in CI resulting in CI failures for this platform (currently 12 samples/tests).

**To Reproduce**
1. twister -T samples/subsys/llext/shell_loader/  -p apollo4p_blue_kxr_evb

**Expected behavior**
No build warnings/errors

**Impact**
CI failing when this target x sample combination is triggerd.
12 failures in weekly CI job

**Logs and console output**
https://github.com/zephyrproject-rtos/zephyr/actions/runs/9240178517/job/25420194674#step:13:4995

**Environment (please complete the following information):**
 - OS: Ubuntu 22.04
 - Toolchain (e.g Zephyr SDK, ...): 0.16.5
 - Commit SHA or Version used: ea29ef36bbedeacd171199d6feea5e699fa64447

**Comment by aescolar** [comment]
CC @aaronyegx @AlessandroLuo @RichardSWheatley

**Comment by aaronyegx** [comment]
@RichardSWheatley I see you are looking at the issue (maybe another similar ticket) and have some fix in the HAL?

**Comment by RichardSWheatley** [comment]
I have an AmbiqHal branch updated to include the folders. Let's speak at Ambiq to determine best path.

**Comment by nashif** [comment]
> I have an AmbiqHal branch updated to include the folders. Let's speak at Ambiq to determine best path.

any updates?

**Comment by pillo79** [comment]
Previous ticket for the same issue: https://github.com/zephyrproject-rtos/zephyr/issues/72775

**Comment by RichardSWheatley** [comment]
> Previous ticket for the same issue: https://github.com/zephyrproject-rtos/zephyr/issues/72775

Just a question for reference, how come this failure wasn't noticed until months after the hal addition that causes this failure?

**Comment by aescolar** [comment]
> Just a question for reference, how come this failure wasn't noticed until months after the hal addition that causes this failure?

The CI run in a PR is a small subset of tests. What tests on what targets is run is based on what files are changed. Sometimes the subset does not cover enough and some issue gets in.
Other PRs which later affect a test may trigger the test being built/run on the affected targets revealing the issue.
The runs in main merge jobs are bigger, but still, do not cover everything. Though when something is detected there it tends to be reported quite soon though.
We also have a weekly job running on a lot of tests x targets combinations, but due to the amount of tests failures are too normal, so only when a pattern is clear it is seen and reported. That is what led to this issue being opened.

**Comment by RichardSWheatley** [comment]
> > Just a question for reference, how come this failure wasn't noticed until months after the hal addition that causes this failure?
> 
> 
> 
> The CI run in a PR is a small subset of tests. What tests on what targets is run is based on what files are changed. Sometimes the subset does not cover enough and some issue gets in.
> 
> Other PRs which later affect a test may trigger the test being built/run on the affected targets revealing the issue.
> 
> The runs in main merge jobs are bigger, but still, do not cover everything. Though when something is detected there it tends to be reported quite soon though.
> 
> We also have a weekly job running on a lot of tests x targets combinations, but due to the amount of tests failures are too normal, so only when a pattern is clear it is seen and reported. That is what led to this issue being opened.
> 
> 

Did you see the PR my colleague made for this?

PR #74232

If you approve, I will approve.

**Comment by aescolar** [comment]
https://github.com/zephyrproject-rtos/zephyr/pull/74275 ?
That one is not building yet

**Comment by RichardSWheatley** [comment]
> https://github.com/zephyrproject-rtos/zephyr/pull/74275 ?
> 
> That one is not building yet

They mad to add HAL changes to support the kconfig changes.

I am asking about whether that will work for you.

**Comment by aescolar** [comment]
> I am asking about whether that will work for you.

If the tests pass again, sure. I only disabled it to unblock CI for others.
