### ISSUE TITLE
subsys/fs/: shell command for mounting the file system is unimplemneted

### ISSUE THREAD

**Issue by nvlsianpu** [zephyrproject-rtos/zephyr#7348]
After introduction of VFS the mount operation is required in order to setup the FS.

**Comment by ramakrishnapallala** [comment]
@nvlsianpu what is expected input here? are you expecting something like below?

mount NFFS "nffs"

**Comment by koffes** [comment]
Yes, this would be beneficial. If appropriate, the file system could also be mounted automatically when the relevant settings have been selected. Alternatively have a separate setting for auto mount.

**Comment by nvlsianpu** [comment]
@ramakrishnapallala 
Yes - something like that.
We simultaneously might looks forward for automatically mounting the FS.

**Comment by ramakrishnapallala** [comment]
moving to v1.13

**Comment by varun-sha** [comment]
fs Shell module is created, which can be enabled by CONFIG_FS_SHELL=y
mount commands example:-
format:- fs mount <fs e.g: fat/nffs> <mount-point>
example commands:- 
fs mount fat /RAM
fs mount nffs /nffs

**Comment by varun-sha** [comment]
@nvlsianpu @nashif @ramakrishnapallala 
pls review https://github.com/zephyrproject-rtos/zephyr/pull/8384

**Comment by ramakrishnapallala** [comment]
@varun-sha I think you need to migrate the PR to new shell implementation from Nordic.

**Comment by varun-sha** [comment]
@ramakrishnapallala i think Nordic cli is not targeted for 1.13 release
@nvlsianpu @koffes : can you pls comment, i have done implementation for this and submitted pr as per current cli which we have in zephyr, should we go ahead with this pr? or should wait for nordic cli which will be integrated into Zephyr..and then integrate our changes into that...

**Comment by koffes** [comment]
I have no say here, but if we can have this feature as part of the existing CLI instead of waiting it would be beneficial.

**Comment by varun-sha** [comment]
@nashif  Can you share your thoughts...
