### ISSUE TITLE
I would like to become a Zephyr contributor

### ISSUE THREAD

**Issue by morandg** [zephyrproject-rtos/zephyr#73666]
# Nomination

I would like to become a Zephyr contributor!

## GitHub User

1. Guy Morand
1. https://github.com/morandg
1. https://github.com/bytesatwork/

## Supporting Documents

* https://github.com/zephyrproject-rtos/zephyr/pull/42345
* https://github.com/zephyrproject-rtos/zephyr/pull/51391
* https://github.com/zephyrproject-rtos/zephyr/pull/51392
* https://github.com/zephyrproject-rtos/zephyr/pull/57061

**Comment by aescolar** [comment]
CC @MaureenHelm @carlescufi

**Comment by nashif** [comment]
https://github.com/zephyrproject-rtos/zephyr/invitations
