### ISSUE TITLE
I would like to become a Zephyr contributor

### ISSUE THREAD

**Issue by dariis** [zephyrproject-rtos/zephyr#73706]
# Nomination

I would like to become a Zephyr contributor!

## GitHub User

Provide the following information about the GitHub user:

1. Rico Ganahl
1. @dariis 
1. bytesatwork AG, https://github.com/bytesatwork/

## Supporting Documents

1. #35093
2. #41625
3. #44444
4. #53044
5. #54594

**Comment by kartben** [comment]
+1

**Comment by aescolar** [comment]
CC @MaureenHelm @carlescufi

**Comment by nashif** [comment]
https://github.com/zephyrproject-rtos/zephyr/invitations
