### ISSUE TITLE
Codecov does not report coverage of code that is not covered by the native_posix test suite

### ISSUE THREAD

**Issue by SebastianBoe** [zephyrproject-rtos/zephyr#7375]
PR https://codecov.io/gh/zephyrproject-rtos/zephyr/pull/6748/

demonstrates that codecov is not able to detect when new code that is untested is committed. Such code should be considered a coverage-regression. It is not clear why it does not catch this.

**Comment by aescolar-ot** [comment]
As of now we are only feeding codecov the code that is compiled and run by sanitycheck in the native_posix tests.

**Comment by SebastianBoe** [comment]
Right, that would explain it. I guess this will be difficult to resolve then.

**Comment by aescolar-ot** [comment]
Yep, it would not be easy to resolve. Our only source of coverage are the native_posix runs. So code in, for ex., arch/arm is out of scope for the current setup. And so are all boards and drivers.
You can see here what is actually part of coverage analysis:
https://codecov.io/gh/zephyrproject-rtos/zephyr/tree/master

**Comment by nashif** [comment]
we are not using codecov anymore, so closing.
