### ISSUE TITLE
Renesas smartbond DMA DT does not use dma-cells

### ISSUE THREAD

**Issue by decsny** [zephyrproject-rtos/zephyr#73803]
The [`renesas,smartbond-dma`](https://github.com/zephyrproject-rtos/zephyr/blob/main/dts/bindings/dma/renesas%2Csmartbond-dma.yaml) binding does not define dma-cells, and consequence of this is that renesas bindings have different ways of specifying things like dma channels associated with a node. This needs to be made coherent and align with how most of the rest of zephyr DMA DT is done, using #dma-cells and phandle array.

How I found this bug: #73747 adding SPI

Another example I found: [`renesas,smartbond-usbd`](https://github.com/zephyrproject-rtos/zephyr/blob/main/dts/bindings/usb/renesas%2Csmartbond-usbd.yaml)

**Comment by ioannis-karachalios** [comment]
@decsny you are right. I will take care of it immediately.
