### ISSUE TITLE
drivers: can: s32: canxl: driver does not set Transceiver Delay Compensation Offset (TDCO)

### ISSUE THREAD

**Issue by henrikbrixandersen** [zephyrproject-rtos/zephyr#73824]
**Describe the bug**
The NXP S32 CANXL driver does not calculate and set the Transceiver Delay Compensation Offset (TDCO) when CAN FD is enabled. TDCO is needed for correct sampling of own TX line at higher data phase bitrates.

**To Reproduce**
1. Inspect the driver code.
2. Notice TDCO is not set up.

**Expected behavior**
TDCO should be calculated using `CAN_CALC_TDCO()` and written to the respective register and Transceiver Delay Compensation (TDC) should be enabled when using CAN FD.

**Impact**
Likely issues with using higher data phase bitrates.

**Additional context**
Please see the following commits for inspiration on how to calculate and set TDCO:
- https://github.com/zephyrproject-rtos/zephyr/commit/633065ec3b78bc15722b02804ad9d72450ebec71
- https://github.com/zephyrproject-rtos/zephyr/commit/bfad7bc00e734010d059d5ba7eb4cd2187eb1c8d

**Comment by manuargue** [comment]
@Dat-NguyenDuy pls have a look at this

**Comment by congnguyenhuu** [comment]
Hello @henrikbrixandersen , I tried reproducing this issue but I'm NOT possible.
I tried a test CAN traffic with multiple CAN-FD frames between 2 instance CANXL_0 and CANXL_1 on board S32Z270.

I set CAN PE clock 160MHz and bitrate for  arbitration phase 125kbit/s, for data phase 8Mbit/s
![image](https://github.com/zephyrproject-rtos/zephyr/assets/76719459/7984eda4-7233-4947-ab96-c231992646d5)

I have this test for reproducing 
[can_fd_traffic.zip](https://github.com/user-attachments/files/15692038/can_fd_traffic.zip)
and the result test
![image](https://github.com/zephyrproject-rtos/zephyr/assets/76719459/2d535e3d-a545-4a22-9509-0259936c0ed0)


Do you have any suggestion about bitrate and test steps that help me to reproduce this issue. Thank you.

**Comment by henrikbrixandersen** [comment]
> Hello @henrikbrixandersen , I tried reproducing this issue but I'm NOT possible. I tried a test CAN traffic with multiple CAN-FD frames between 2 instance CANXL_0 and CANXL_1 on board S32Z270.

Reproducing this greatly depends on the actual CAN tranceiver used, but nevertheless this needs to be set up. 

You need to set `BTDCC[FTDCEN]` to enable TDC for CAN FD, calculate the TDCO using `CAN_CALC_TDCO()` and write it to `BTDCC[FTDCOFF]`. Check the reference manual chapter on "Transceiver Delay Compensation".

**Comment by congnguyenhuu** [comment]
> > Hello @henrikbrixandersen , I tried reproducing this issue but I'm NOT possible. I tried a test CAN traffic with multiple CAN-FD frames between 2 instance CANXL_0 and CANXL_1 on board S32Z270.
> 
> Reproducing this greatly depends on the actual CAN tranceiver used, but nevertheless this needs to be set up.
> 
> You need to set `BTDCC[FTDCEN]` to enable TDC for CAN FD, calculate the TDCO using `CAN_CALC_TDCO()` and write it to `BTDCC[FTDCOFF]`. Check the reference manual chapter on "Transceiver Delay Compensation".

yes, I opened PR to fix
