### ISSUE TITLE
LE Audio: Implement function to get the size of the BASE

### ISSUE THREAD

**Issue by Thalley** [zephyrproject-rtos/zephyr#73847]
**Is your enhancement proposal related to a problem? Please describe.**
When using the `bt_bap_base` API the application gets a opaque pointer to a `struct bt_bap_base`. 
If the application wants to store the BASE for later use, it needs to know the size of the base. 

**Describe the solution you'd like**
Implement a `size_t bt_bap_base_get_size(struct bt_bap_base *base)` returns the size of the BASE. 
The (several) places where something like `base_size = data->data_len - BT_UUID_SIZE_16;` is done, should be replaced by this function. 

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by jthm-ot** [comment]
I can take a look at this
