### ISSUE TITLE
ARM MPU region configuration possibly out of bounds

### ISSUE THREAD

**Issue by andrewboie** [zephyrproject-rtos/zephyr#7384]
in arm_mpu.c arm_core_mpu_configure_mem_partition(), the region index is computed from _get_region_index_by_type(THREAD_DOMAIN_PARTITION_REGION).

THREAD_DOMAIN_PARITITON_REGION is defined as 4.
However, consider a SOC like the Beetle. mpu_config.num_regions = 6. _get_region_by_type(THREAD_DOMAIN_PARITITON_REGION) will return 9, which is greater than the maximum amount of MPU regions (0-7)

At minimum needs some assertions here.

**Comment by ioannisg** [comment]
@andrewboie I believe you're suggesting ASSERTS in the arm_mpu.c driver, so certain operations will return error (and be caught by other parts of the code)?

**Comment by ioannisg** [comment]
Could this be closed, @andrewboie?

**Comment by linkmeyer** [comment]
@andrewboie , did you see the question above about whether this bug can be closed?
