### ISSUE TITLE
i2c_esp32 can write past checked buffer length

### ISSUE THREAD

**Issue by andrewboie** [zephyrproject-rtos/zephyr#7385]
The input I2C message length is checked by the toplevel syscall handler. The driver should not access memory in the buffer past the input length.

In the ESP32 I2C driver, the message length value is incremented when the operation is a write, as per message flags. This will allow operation 1-2 bytes past the message length checked by the system call handler.

NOTE: user mode is not yet enabled for Xtensa/ESP32, low priority

**Comment by carlescufi** [comment]
@nashif is this still an issue?
