### ISSUE TITLE
Contributor nomination mathieuchopstm

### ISSUE THREAD

**Issue by teburd** [zephyrproject-rtos/zephyr#73865]
# Nomination

## GitHub User

Provide the following information about the GitHub user:

1. Mathieu Choplain
2. [mathieuchopstm](https://github.com/mathieuchopstm)
3. STMicroelectronics

## Supporting Documents

#72358 
#73856
#73425

**Comment by mathieuchopstm** [comment]
>Matthieu Choplain

Spelled with a single `t` :smiley: 

>Presumably ST

STMicroelectronics indeed :smile:

**Comment by nashif** [comment]
https://github.com/zephyrproject-rtos/zephyr/invitations
