### ISSUE TITLE
nxp_mpu: suspicious ENDADDR_ROUND() macro

### ISSUE THREAD

**Issue by andrewboie** [zephyrproject-rtos/zephyr#7388]
This is currently implemented as:

#define ENDADDR_ROUND(x) (x - 0x1f)

This is not a rounding operation unless the last 5 bits are always 1.
Please double-check what this is supposed to be doing.

**Comment by agross-linaro** [comment]
Yeah looking at the NXP reference manual, it does appear that the lower 5 bits are all considered to be 1's.  So this works correctly as currently implemented.
