### ISSUE TITLE
FLASH_PAGE_SIZE on stm32h5

### ISSUE THREAD

**Issue by QuentinCaldeira-eaton** [zephyrproject-rtos/zephyr#73896]
I've seen that this issue was patched with the new commit of hal_stm32, by removing the include of Legacy.
However, when I tried to build a connectedhomeip application, which rely on this KConfig, I still have the issue.
I don't have the issue with any other application. When I build, it seems that he is able to find Legacy

`/home/quentin/github/workspace/modules/hal/stm32/stm32cube/stm32h5xx/drivers/include/Legacy/stm32_hal_legacy.h:475:39: error: 'FLASH_PAGE_SIZE' undeclared (first use in this function); did you mean 'FLASH_BANK_SIZE'?`

If I comment the definition of `FLASH_PAGE`, everything works fine.

- platform : nucleo_h563zi
- patch : comment the definition

**To Reproduce**
1. add CONFIG_POSIX_API=y in prj.conf
2. west build
3. See error

**Expected behavior**
Application build with no zephyr related error

**Environment (please complete the following information):**
 - OS: Ubuntu 22.04 on WSL2
 - Toolchain : Zephyr SDK
 - Commit : main/master

**Comment by FRASTM** [comment]
For the STM32H5 serie, the drivers/flash/flash_stm32.h is defining the _Page_ as a _Sector_
```
/* Values are redefined below from the stm32h5_hal_flash.h */
#define FLASH_PAGE_SIZE          (FLASH_SECTOR_SIZE)
```

**Comment by QuentinCaldeira-eaton** [comment]
@FRASTM, oh okay, thanks ! And how can I include this in my app ? Is there any Kconfig value to be set ? Or should I put the path in CMakeLists ?

**Comment by FRASTM** [comment]
> @FRASTM, oh okay, thanks ! And how can I include this in my app ? Is there any Kconfig value to be set ? Or should I put the path in CMakeLists ? Because even if I put CONFIG_FLASH=y, I have the error

This is not coming from a KCONFIG. Did you #include "flash_stm32.h"  ? if you build the flash_stm32.c, for the stm32h5, the FLASH_PAGE_SIZE should come

**Comment by erwango** [comment]
@QuentinCaldeira-eaton Did you try to run "west update" to be sure you use the latest "hal_stm32" version ?
Anyway, if the issue you're facing is on current main, there is not much more that can be done ...

**Comment by QuentinCaldeira-eaton** [comment]
@erwango Yes I have west updaye, and I am on the current main. I thought this problem was resolved by this previous PR https://github.com/zephyrproject-rtos/zephyr/pull/73363, which say that Legacy will not be included anymore. So why build system find it ? 

`/home/quentin/github/workspace/modules/hal/stm32/stm32cube/stm32h5xx/drivers/include/Legacy/stm32_hal_legacy.h:475:39: error: 'FLASH_PAGE_SIZE' undeclared (first use in this function); did you mean 'FLASH_BANK_SIZE'?`

**Comment by FRASTM** [comment]
@QuentinCaldeira-eaton can you please detail your build command ?

**Comment by QuentinCaldeira-eaton** [comment]
@FRASTM Yes ! As an example, you can take the `samples/cpp/hello_world`. Add, in the prj.conf, those lines :

```Kconfig
CONFIG_CPP=y
CONFIG_REQUIRES_FULL_LIBCPP=y
CONFIG_REQUIRES_FULL_LIBC=y
CONFIG_NEWLIB_LIBC_NANO=y
CONFIG_CBPRINTF_LIBC_SUBSTS=y
CONFIG_POSIX_API=y
CONFIG_EVENTFD=y
CONFIG_REBOOT=y
CONFIG_ENTROPY_GENERATOR=y
CONFIG_NET_UDP=y
CONFIG_NET_IPV6=y
CONFIG_NET_CONFIG_NEED_IPV6=y
CONFIG_NET_SOCKETS=y
CONFIG_NET_SOCKETS_POSIX_NAMES=y
CONFIG_NETWORKING=y
CONFIG_HWINFO=y
CONFIG_FLASH=y
CONFIG_FLASH_MAP=y
CONFIG_NVS=y
CONFIG_SETTINGS=y
```

Then, `west build -b nucleo_h563zi samples/cpp/hello_world/ --pristine` and see the error. If I remove all extra CONFIG in prj.conf, the error disappears.

**Comment by FRASTM** [comment]
Yes, even if removed from headers inclusin, for each stm32 serie,  each stm32XXxx_hal_def.h is including individually
 #include "Legacy/stm32_hal_legacy.h"

**Comment by QuentinCaldeira-eaton** [comment]
@FRASTM Then, why not just removing the #define depending on FLASH_PAGE_SIZE in each Legacy/stm32hal_legacy.h ? It seems to do the trick for me, but I haven't tested all cases

**Comment by FRASTM** [comment]
Adding to **../modules/hal/stm32/stm32cube/stm32h5xx/drivers/include/Legacy/stm32_hal_legacy.h**
`#define FLASH_PAGE_SIZE FLASH_SECTOR_SIZE
`
plus **drivers/flash/flash_stm32.h**
```
#ifndef FLASH_PAGE_SIZE
#define FLASH_PAGE_SIZE          (FLASH_SECTOR_SIZE)
#endif /* FLASH_PAGE_SIZE */

```

can fix the error for the stm32h5x serie
