### ISSUE TITLE
GNSS Sample - Callbacks do not get called with PuTTY and nRF7002DK

### ISSUE THREAD

**Issue by BlimbBoat** [zephyrproject-rtos/zephyr#73927]
**Describe the bug**
I am using the nRF7002-DK with PuTTY to test the [GNSS sample](https://docs.zephyrproject.org/latest/samples/drivers/gnss/README.html#gnss). 

My problem is whenever I send a NMEA0183 sentence: `$GPGGA,092750.000,5321.6802,N,00630.3372,W,1,8,1.03,61.7,M,55.2,M,,*76`
Nothing seems to happen. After spamming the message the following can be seen:
```
[00:00:25.367,645] <wrn> modem_chat: argv buffer overrun
[00:00:27.525,207] <wrn> modem_chat: receive buffer overrun
```

in my boards/nrf7002dk_nrf5340_cpuapp.overlay I added:
```
/ {
	aliases {
		gnss = &gnssdev;
	};
};

&uart2{
    status = "okay";

    current-speed = <9600>;
    data-bits = <8>;
    stop-bits = "1";
    parity = "none";

    pinctrl-0 = <&uart2_default>;
    pinctrl-names = "default";
    gnssdev: gnss-nmea-generic{
        compatible = "gnss-nmea-generic";
    };
};

&pinctrl {
    uart2_default: uart2_default {
        group1{
            psels = <NRF_PSEL(UART_TX, 0, 6)>;
        };
        group2{
            psels = <NRF_PSEL(UART_RX, 0, 7)>;
			bias-pull-up;
        };
    };
};

```
**Environment (please complete the following information):**
 - OS: Windows 
 - Toolchain: nRF Connect SDK Toolchain v2.6.0

In the GNSS sample, it does state that a GNSS device is present, I thought that before having a GNSS device I could test it with PuTTY first, so maybe that is the problem.

**Comment by bjarki-trackunit** [comment]
Can you enable this option `CONFIG_MODEM_MODULES_LOG_LEVEL_DBG=y` in your `prj.conf` or using `west build -t menuconfig`?

My initial suspicion is that you are not sending the expected end delimiters when sending via PuTTY, should be "\r\n" :)

**Comment by bjarki-trackunit** [comment]
Additionally, you need to send both RMC and GGA before the driver calls back, since it uses data from both of those messages to populate `struct gnss_data`

**Comment by bjarki-trackunit** [comment]
oh, nvm, you need to add `status="okay"` to the gnssdev node :)

```
    gnssdev: gnss-nmea-generic{
        compatible = "gnss-nmea-generic";
        status = "okay";
    };
```

**Comment by BlimbBoat** [comment]
Thanks for your comments!

I did not manage to do it using PuTTY, but I managed to send a GGA and RMC with the Serial Monitor in the Arduino IDE.

**Comment by bjarki-trackunit** [comment]
Good to know you made it work :)
