### ISSUE TITLE
modules: canopennode: program download sometimes fails

### ISSUE THREAD

**Issue by jeppenodgaard** [zephyrproject-rtos/zephyr#73987]
**Describe the bug**
Program download via `west flash --runner canopen` fails on `nucleo_h563zi`.

Please also mention any information which could help others to understand
the problem you're facing:
 - What target platform are you using?:
 `nucleo_h563zi`
 - What have you tried to diagnose or workaround this issue?:
 Adding `k_msleep(10)` to the sample `samples/modules/canopennode/src/main.c` fixes the issue:

```c
int main(void)
...
	while (reset != CO_RESET_APP) {
...
		while (true) {
...
			if (reset != CO_RESET_NOT) {
                                k_msleep(10)
				break;
			}
...
```

 - Is this a regression? 
I do not know.

**To Reproduce**
1. Add `nucleo_h563zi.overlay` to the sample:
```overlay
/ {
    chosen {
        zephyr-canbus = &fdcan1;
    };
};

&fdcan1 {
    status = "okay";
    pinctrl-0 = <&fdcan1_rx_pd0 &fdcan1_tx_pd1>;
    pinctrl-names = "default";
    bus-speed = <125000>;
    bus-speed-data = <1000000>;
};
```
1. Append this line to `nucleo_h563zi/board.cmake`:
```c
include(${ZEPHYR_BASE}/boards/common/canopen.board.cmake)
```
1. Follow the steps in the README for program download:
https://docs.zephyrproject.org/latest/samples/modules/canopennode/README.html#testing-canopen-program-download
1. See error

**Expected behavior**
No error:

```shell
100% |################################| 73208/73208B
-- runners.canopen: Waiting for flash status ok
-- runners.canopen: Program software identification: 0xffde8244
-- runners.canopen: Starting program
-- runners.canopen: Waiting for boot-up message...
-- runners.canopen: Program software identification: 0xffde8244
-- runners.canopen: Entering pre-operational mode
-- runners.canopen: Confirming program
```

**Impact**
Not possible to do program download without magic delay (which might not always work).

**Logs and console output**

```shell
100% |################################| 73200/73200B
-- runners.canopen: Waiting for flash status ok
-- runners.canopen: Program software identification: 0x0bb461e3
-- runners.canopen: Starting program
Transfer aborted by client with code 0x05040000
FATAL ERROR: Unable to write control command 0x01
An exception trace has been saved in /tmp/west-exc-93q5lwph.txt
```

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: `zephyr-sdk-0.16.5-1`
 - 3.6.0 with a few cherry-picks and also fd236ee991e704d4bb560a8d691b2f8b4da07ba6

**Additional context**
CAN adaptor:
https://www.peak-system.com/PCAN-USB-FD.365.0.html

**Comment by henrikbrixandersen** [comment]
@jeppenodgaard Please try increasing the SDO timeout (i.e. `west flash --domain ... -r canopen --dev-id .. --can-context ... --sdo-timeout 1` for 1 one second timeout).
