### ISSUE TITLE
Contributor nominations for @nordic-piks and @katgiadla

### ISSUE THREAD

**Issue by PerMac** [zephyrproject-rtos/zephyr#74025]
# Nomination
 
for Contributors

## GitHub User

Piotr Kosycarz
@nordic-piks 
Nordic Semiconductor

Katarzyna Giądła
@katgiadla 
Nordic Semiconductor

## Supporting Documents
Both Piotr and Katarzyna are actively reporting issues detected when executing tests on Nordic hardware. Adding them as contributors to the project and giving them triage rights would reduce the amount of work done by Triage wg for the issues they report. They already provided multiple fixes to test configurations and some improvements to test related tooling used in the project:

https://github.com/zephyrproject-rtos/zephyr/pulls?q=is%3Apr+author%3Akatgiadla
https://github.com/zephyrproject-rtos/zephyr/pulls?q=is%3Apr+author%3Anordic-piks

**Comment by nashif** [comment]
https://github.com/zephyrproject-rtos/zephyr/invitations

**Comment by katgiadla** [comment]
> https://github.com/zephyrproject-rtos/zephyr/invitations

After click into link, I see message:

![image](https://github.com/zephyrproject-rtos/zephyr/assets/43877781/f570b661-b6cf-49ee-8b31-c60c04a30dc5)

could you sent invitation once again, please?

**Comment by nordic-piks** [comment]
For me working fine, thanks for nomination!

**Comment by PerMac** [comment]
@nashif Can you send/check the invitation for @katgiadla? As reported, the link doesn't work for Katarzyna. Katarzyna also haven't received mail invitation (we checked in spam).

**Comment by katgiadla** [comment]
The e-mail with invitation reach to me. Thanks :)
