### ISSUE TITLE
doc: Documentation issue in 'boards/luatos/esp32s3_luatos_core/doc/index'

### ISSUE THREAD

**Issue by EricNRS** [zephyrproject-rtos/zephyr#74041]
**Describe the bug**
The getting started documentation has the following line for using serial over JTAG USB using the `esp32s3_luatos_core_usb` config, but this path does not exist.
`west build -b esp32s3_luatos_core_usb/esp32s3/procpu samples/hello_world`

I believe this should instead be:
`west build -b esp32s3_luatos_core/esp32s3/procpu/usb samples/hello_world`

**Environment**

* Page: `boards/luatos/esp32s3_luatos_core/doc/index`
* Version: main
* SHA-1: c0866030ebc9c0588eb349de34eb96af5317161e

**Comment by kartben** [comment]
Indeed. Could you send a PR fixing this?

**Comment by EricNRS** [comment]
@kartben - done, PR #74198
