### ISSUE TITLE
Broken Link: ZephyrProject.Org main page; About->Governance Documents->Charter returns a 404 error.

### ISSUE THREAD

**Issue by Timotheous** [zephyrproject-rtos/zephyr#74040]
I need to reference the Zephyr Project Charter.
I used to be able to access it from the ZephyrProject.Org main page; About->Governance Documents->Charter.  
https://zephyrproject.org/wp-content/uploads/sites/38/2023/08/LF-Zephyr-Charter-2023.08.21.pdf
But that is now returning a 404 error.

The Charter appears to have been updated because the link I used to have was: 
https://zephyrproject.org/wp-content/uploads/sites/38/2020/09/CLEAN-LF-Zephyr-Charter-20200624-effective-20200901.pdf

Where can I access the new Charter?

**Comment by kestewart** [comment]
@Timotheous - it should be fixed now:  https://zephyrproject.org/wp-content/uploads/2023/08/LF-Zephyr-Charter-2023.08.21.pdf is where I'm able to navigate to from the menues.

I'm going to close this now, but please reopen and include how you were navigating to it, if it's still a problem.
