### ISSUE TITLE
tests/posix/common/ portability.posix.common.static_stack failing to build for riscv

### ISSUE THREAD

**Issue by aescolar** [zephyrproject-rtos/zephyr#74296]
**Describe the bug**
tests/posix/common/ failing to build for m2gl025_miv

**To Reproduce**
1. twister -p m2gl025_miv -T tests/posix/common -s portability.posix.common.static_stack

**Expected behavior**
No build errors

**Impact**
main CI failing

**Logs and console output**
https://github.com/zephyrproject-rtos/zephyr/actions/runs/9510842407/job/26216040417#step:11:1441

**Environment (please complete the following information):**
 - OS: Ubuntu 22.04
 - Toolchain (e.g Zephyr SDK, ...): 0.16.8
 - Commit SHA or Version used: main after b98a60773b3f2a592b9a1dea4899ec26ca2ab4fb

**Additional context**
Introduced by 726fefd12c660158715d6e8b1d34dcb63cf1d08a

**Comment by aescolar** [comment]
CC @fkokosinski @kgugala @tgorochowik 
@mgielda @katsuster @edersondisouza @carlocaione @npitre

**Comment by ycsin** [comment]
Fix is in #74282
