### ISSUE TITLE
PWM Clock does not work if SOC clock is changed [NXP S32K1]

### ISSUE THREAD

**Issue by vChavezB** [zephyrproject-rtos/zephyr#74348]
**Describe the bug**
If I change the system clock configuration of the SOC NXP S32K146 through the SoC definition [here](https://github.com/zephyrproject-rtos/hal_nxp/blob/bee15c31e19ff1982583d9b750ef844d64320160/s32/soc/s32k146/src/Clock_Ip_Cfg.c), the PWM clock is not updated correctly.

**To Reproduce**
1. Change the system clock (`BUS_CLK`) which is named as `CORE_RUN_CLK` in [`Clock_Ip_Cfg.c`](https://github.com/zephyrproject-rtos/hal_nxp/blob/bee15c31e19ff1982583d9b750ef844d64320160/s32/soc/s32k146/src/Clock_Ip_Cfg.c). This can be done by for example changing the Predivider to 4 [here](https://github.com/zephyrproject-rtos/hal_nxp/blob/bee15c31e19ff1982583d9b750ef844d64320160/s32/soc/s32k146/src/Clock_Ip_Cfg.c#L524).

2. Create a PWM node for tests

```ini
my_pwm: my-pwm-node {
	pwms = <&ftm0 1 PWM_HZ(2400) PWM_POLARITY_NORMAL>;
	label = "My NXP PWM;
};

&ftm0 {
	clock-source = "system";
};
```

3. Add some source code to test this

```c
void test(){
  static const struct pwm_dt_spec pwm_out= PWM_DT_SPEC_GET(DT_ALIAS(my_pwm));
  pwm_set_pulse_dt(&pwm_out, pwm_out.period/2);  // 50 % duty cycle	
}
```

**Expected behavior**
That the PWM frequency corresponds to the one set in the device tree.

**Impact**
I have to manually modify the PWM frequency speed in the device tree to match 2400 Hz (in this example) each time I change the system clock speed.

## Possible solution

After checking the source code for the HAL NXP S32K146 and mcux pwm [driver  ](https://github.com/zephyrproject-rtos/zephyr/blob/66630961627f4d8625e2dbe1cb7afe4abd690b2e/drivers/pwm/pwm_mcux.c#L63) I noticed that the FTM clock source is set to `SPLLDIV1_CLK `[here](https://github.com/zephyrproject-rtos/hal_nxp/blob/bee15c31e19ff1982583d9b750ef844d64320160/s32/soc/s32k146/src/Clock_Ip_Cfg.c#L312).

As per the Reference Manual I understand that the System clock is not `SPLLDIV1_CLK` but rather `CORE_RUN_CLK` defined in [`Clock_Ip_Cfg.c`](https://github.com/zephyrproject-rtos/hal_nxp/blob/bee15c31e19ff1982583d9b750ef844d64320160/s32/soc/s32k146/src/Clock_Ip_Cfg.c). 

![grafik](https://github.com/zephyrproject-rtos/zephyr/assets/47216966/fc1b0f92-2e8d-4471-b46f-570d57c720dd)

**Possible code change**
```c
            {
                FTM0_CLK,                    /* Clock name associated to selector */
                CORE_RUN_CLK,                    /* Name of the selected input source */
            },
```

I also confirmde this with the excel tool provided from Applicatio Note AN5408SW and the excel calculator `S32K1xx_Clock_Calculator_Rev1`

![grafik](https://github.com/zephyrproject-rtos/zephyr/assets/47216966/ebcfb3f5-6b80-40aa-a25f-1d60856c2f8a)

**Comment by vChavezB** [comment]
Could you have a look @manuargue  ?

**Comment by manuargue** [comment]
Well we haven't supported running with other clocks configurations than the existing one in hal_nxp, but is good that you have tried it out.

I believe the problem is that `NXP_S32_FTMx_CLK` is referencing the `PCC_FTMx` clock (selected by `PCC_FLEXTMRn[PCS]`) and not the effective `FTM_CLK` selected by `FTMn_SC[CLKS]`.

Leaving the clock config in `Clock_Ip_Cfg.c` as is (`FTM0_CLK` to `SPLLDIV1_CLK`), but changing in devicetree:
```devicetree
&ftm0 {
    clocks = <&clock NXP_S32_CORE_CLK>;
};
```
does it solve your issue?

**Comment by vChavezB** [comment]
Thanks for quick reply. I do not have the board with me but will try this out on the next days.

**Comment by manuargue** [comment]
tested with `pwm usec ftm@40039000 1 1000 500`

1. with existing clock configuration:
![image](https://github.com/zephyrproject-rtos/zephyr/assets/511857/73821a17-9a4a-4613-b51e-36e6e025e97b)

2. changing the predivider to 4 [here](https://github.com/zephyrproject-rtos/hal_nxp/blob/bee15c31e19ff1982583d9b750ef844d64320160/s32/soc/s32k146/src/Clock_Ip_Cfg.c#L524)
![image](https://github.com/zephyrproject-rtos/zephyr/assets/511857/5ea4cea8-76b5-47cd-b8a5-a47c525032ab)

3. same change in predivider + patch from https://github.com/zephyrproject-rtos/zephyr/pull/74355
![image](https://github.com/zephyrproject-rtos/zephyr/assets/511857/a9b9872d-390c-4832-a2b5-6d4f0544b16c)

**Comment by vChavezB** [comment]
That looks good. Thanks for the test results.

Just as a small context on why I noticed this. I am trying to reduce the current consumption for my application and was testing different clock speeds. The other peripherals behaved the same but since I have some pwm outputs thats when I noticed this.
