### ISSUE TITLE
With PM enabled, LPUART shell consistently misses 2nd character when sending multiple characters at once

### ISSUE THREAD

**Issue by kyleboudreau** [zephyrproject-rtos/zephyr#74441]
**Describe the bug**
Using a custom board based on the STM32U5A5 MCU, when using an LPUART shell with power management enabled (`CONFIG_PM=y`), sending multiple characters results in the 2nd character consistently being missed. This happens when pasting multiple characters to the shell, and also causes compound commands to fail. For example, pasting `12345` to the shell results in `1345` being received and pressing the left arrow key results in nothing happening because `ESC D` is received instead of `ESC [ D`.

As far as I can tell, `uart_stm32_irq_tx_disable()` is triggered after echoing the first character, which in turn results in a `pm_policy_state_lock_put(PM_STATE_SUSPEND_TO_IDLE, PM_ALL_SUBSTATES)` call to return the device to a low-power state. As a sanity check I disabled that `put` call and confirmed that characters are no longer missed, but this obviously keeps the device from re-entering a low-power state. It appears that `pm_policy_state_lock_put()` and `pm_policy_state_lock_get()` are only called in relation to TX events, and RX events are simply treated as a wakeup source.

Setting a breakpoint in the serial driver file `uart_stm32.c` I also realized that the PM handler `uart_stm32_pm_action()` was not triggering, so I added `zephyr,pm-device-runtime-auto;` to the LPUART devicetree node. With that set, the LPUART shell does not work at all - the `PM_DEVICE_ACTION_SUSPEND` action is processed at startup and then the device never resumes, even when attempting to enter characters into the shell (which again is configured as a wakeup source).

I also tried increasing/decreasing the interrupt priorities for LPUART and the LPTIMER, which had no effect.

**To Reproduce**
- Use an STM32U5A5 board
- Set `CONFIG_SHELL=y`
- Set `CONFIG_UART_INTERRUPT_DRIVEN=y`
- Set `CONFIG_PM=y`
- Enable `&lpuart1` in the devicetree (9600 baud)
- Enable `&lptim1` in the devicetree
- Paste `12345` into the shell (`1345` is echoed, i.e., the 2nd character is missing)

**Expected behavior**
When entering `12345` into the shell, I expect `12345` to be received and echoed to the shell.

**Impact**
This leaves us unable to use arrow keys or any other compound commands with the shell, unable to copy/paste commands to the shell, and complicates any automated testing using the shell.

**Environment (please complete the following information):**
 - OS: Windows
 - Zephyr SDK
 - v3.6.0

**Comment by erwango** [comment]
I can answer on the following part:

> Setting a breakpoint in the serial driver file `uart_stm32.c` I also realized that the PM handler `uart_stm32_pm_action()` was not triggering, so I added `zephyr,pm-device-runtime-auto;` to the LPUART devicetree node. With that set, the LPUART shell does not work at all - the `PM_DEVICE_ACTION_SUSPEND` action is processed at startup and then the device never resumes, even when attempting to enter characters into the shell (which again is configured as a wakeup source).

For some reason, zephyr,pm-device-runtime-auto;`  is indeed not usable. Though, when calling `pm_device_wakeup_enable(dev, true);` it should work. See `samples/boards/stm32/power_mgmt/serial_wakeup/src/main.c`. I've just tested it on `b_u585i_iot02a`.
This allows to observe that problem also happens with PM_DEVICE_RUNTIME enabled.


Then regarding the solution, it seems enabling fifo (`fifo-enable;`) has a positive effect, at least on the tests I've performed.
Can you have a try ?
