### ISSUE TITLE
nRF52, NXP kinetis, ARM Beetle and  STM `MPU` option appear for every MPU-equipped device

### ISSUE THREAD

**Issue by nvlsianpu** [zephyrproject-rtos/zephyr#7452]
Such options appear in menuconfig under [ARM Options]->[SoC Options]->*

Looks like it is required to make them dependent on appropriate architectures is only reqired for fix this issue.

![image](https://user-images.githubusercontent.com/17042885/39876936-db68c1c4-5474-11e8-92c8-a66d0805f7d0.png)

**Comment by nvlsianpu** [comment]
fix for nRF52xx is included in https://github.com/zephyrproject-rtos/zephyr/pull/7449

**Comment by nvlsianpu** [comment]
cc @MaureenHelm @galak @nashif @fvincenzo 

I don't have enough knowledge (about device families) for fix this for particular devices - what i can suggest is that it has to by fixed by appropriate maintainers.

**Comment by galak** [comment]
Can you explain this a bit more, how are things show up in menuconfig?

**Comment by nvlsianpu** [comment]
I added the snipped.

**Comment by galak** [comment]
Thanks, I've got a fix I think across all the SoCs.  Will post in a minute.
