### ISSUE TITLE
samples: sensor: qdec: Sample reports timeout

### ISSUE THREAD

**Issue by katgiadla** [zephyrproject-rtos/zephyr#74531]
**Describe the bug**
Samples:
- `samples/sensor/qdec/sample.sensor.qdec_sensor`
-  `samples/sensor/qdec/sample.sensor.nrf_qdec_sensor`

report timout.

Observed for:
- `nrf54l15pdk/nrf54l15/cpuapp`
- ` nrf5340dk/nrf5340/cpuapp`
- ` nrf52840dk/nrf52840`
- `nrf54h20dk/nrf54h20/cpuapp`

**To Reproduce**
1. have `nrf52840dk/nrf52840` connected
2. go to your zephyr dir
3. call `./scripts/twister -T samples/sensor/qdec/ -p nrf52840dk/nrf52840 --device-testing --device-serial /dev/ttyACM0 -v --inline-logs --west-flash="--erase"`
4. See console output with error

**Expected behavior**
Valid console output

**Impact**
Not clear

**Logs and console output**
```
*** Booting Zephyr OS build v3.7.0-rc1-80-g694428947ae3 ***
Quadrature decoder sensor test
Quadrature encoder emulator enabled with 100 ms period
Position = 0 degrees
Position = -57 degrees
Position = -60 degrees
Position = -60 degrees
Position = -60 degrees
```

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04.1 LTS
 - Toolchain: Zephyr SDK 0.16.5-1
 - Commit SHA or Version used: `v3.7.0-rc1-24-g0561d74d31c4`

**Additional context**
Probably introduced by d52db56ac3be6f21287c8691069976e30c4d11a9

**Comment by nordic-piks** [comment]
@nandojve FYI
