### ISSUE TITLE
Add support for Broadcom APDS9306

### ISSUE THREAD

**Issue by Kampi** [zephyrproject-rtos/zephyr#74546]
**Is your enhancement proposal related to a problem? Please describe.**
The driver for the sensor module is missing.

**Describe the solution you'd like**
I prepare a PR to add the driver for the module from our Smartwatch project (see [here](https://github.com/jakkra/ZSWatch/tree/main/app/drivers/sensor/apds9306)).

**Additional context**
[APDS9306](https://www.broadcom.com/products/optical-sensors/ambient-light-photo-sensors/apds-9306-065)

**Comment by henrikbrixandersen** [comment]
Fixed in #74547
