### ISSUE TITLE
drivers: usb: Port `usb_dc_smartbond` to `UDC API`

### ISSUE THREAD

**Issue by carlescufi** [zephyrproject-rtos/zephyr#74662]
In order for the `USB_DEVICE_STACK_NEXT` to become the default, existing USB device drivers must be ported to it.
See #42066 for additional details.

Note that if this driver is not ported by Zephyr 4.0.0, this hardware will not work with the default USB stack in 4.0.0.

Example ports:
- udc_kinetis and udc_nrf PR #38679
- udc_it82xx2 PR #65792
- udc_dwc2 PR  #64943
- udc_stm32 PR #53408
- udc_mcux PR #70401

Skeleton file to use as a starting point:
https://github.com/zephyrproject-rtos/zephyr/blob/main/drivers/usb/udc/udc_skeleton.c

Documentation:
https://docs.zephyrproject.org/latest/connectivity/usb/device_next/usb_device.html
https://docs.zephyrproject.org/latest/connectivity/usb/device_next/api/index.html

**Comment by carlescufi** [comment]
@ioannis-karachalios are you going to post a PR porting this USB driver?

**Comment by carlescufi** [comment]
@sjanc do you know if there's any ongoing work related to this?

**Comment by sjanc** [comment]
@carlescufi we are likely going to start working on this this week

**Comment by ioannis-karachalios** [comment]
@carlescufi, thanks for the info provided and sorry for my late response. We will assign an engineer to start working on USB porting and most likely we will be able to kick it off mid this week.

**Comment by kasjer** [comment]
@carlescufi I'm currently working on this port, is there a way for me to assign this issue to myself?

**Comment by carlescufi** [comment]
> @carlescufi I'm currently working on this port, is there a way for me to assign this issue to myself?

I see @henrikbrixandersen did that, thanks @kasjer.

**Comment by carlescufi** [comment]
@kasjer do you have an ETA for a PR?

**Comment by kasjer** [comment]
@carlescufi I expect to finish it in a week or so.
