### ISSUE TITLE
Select HAS_SEGGER_RTT=y for NXP  SOC_SERIES_S32K1

### ISSUE THREAD

**Issue by vChavezB** [zephyrproject-rtos/zephyr#74702]
**Describe the solution you'd like**
Automatic selection of `HAS_SEGGER_RTT` for the S32K1 SOC in https://github.com/zephyrproject-rtos/zephyr/blob/0910c86231b700dbf6cdaf02090e9360a83a3148/soc/nxp/s32/s32k1/Kconfig#L6

**Describe alternatives you've considered**
Manually set `select HAS_SEGGER_RTT` in the SOC Kconfig for `SOC_SERIES_S32K1`

**Comment by manuargue** [comment]
hi @vChavezB, thanks for logging this issue. I just came across this request while going through the backlog and unfortunately was left unassigned. I've opened a pr to follow up on it.
