### ISSUE TITLE
pthread_attr_init( ) does not conform to POSIX specification

### ISSUE THREAD

**Issue by aescolar-ot** [zephyrproject-rtos/zephyr#7480]
Currently `pthread_attr_init()` checks the content of the input pthread_attr.
Therefore if its input was not initialized before the call, the behavior of the function is unpredictable.
Note that the point of pthread_attr_init() is to actually initialize it after it was declared and before it is used.

The POSIX spec. for this function can be found here:
http://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_attr_init.html

An appropriate behavior of the function would be to always copy into its input the init structure without checks. As the specification allows undefined behavior for `pthread_attr_init()` if the input had been initialized before hand.

Related: #7446

**Comment by aescolar-ot** [comment]
@nashif would you be so kind as to reassign it to whoever maintains this part of the code?

**Comment by nashif** [comment]
@ramakrishnapallala please take a look at this.
