### ISSUE TITLE
mDNS Responder Failure when Query Type contains DNS_CLASS_FLUSH

### ISSUE THREAD

**Issue by EricNRS** [zephyrproject-rtos/zephyr#74829]
**Describe the bug**
WIth CONFIG_MDNS_RESPONDER enabled, I see the following recv() errors caused by -EINVAL periodically from the network.

```
[00:25:02.278,000] <err> net_dns_dispatcher: DNS recv error (-22)
[00:26:25.237,000] <err> net_dns_dispatcher: DNS recv error (-22)
[00:30:07.945,000] <err> net_dns_dispatcher: DNS recv error (-22)
```

I tracked it down to Android and iPhone devices issuing DNS requests with the class bit DNS_CLASS_FLUSH set.  This causes the `query_class` check in `dns_unpack_query()` to fail:

https://github.com/zephyrproject-rtos/zephyr/blob/e5c05da9cbda7bc68aa84b796b828767b5eea6d7/subsys/net/lib/dns/dns_pack.c#L593-L595

Can the flush bit be masked off for this implementation to prevent the error?  Is there a better way to handle this to prevent the logs from being spammed with error messages?

**To Reproduce**
Should work on any board. I am using an ESP32-S3 board with the following configuration items set:

```
CONFIG_DNS_RESOLVER=y
CONFIG_MDNS_RESPONDER=y
```

**Expected behavior**
The query either works correctly (the DNS_CLASS_FLUSH is masked) or the failure is silently ignored unless INF of DBG logs are enabled.

**Impact**
Mainly an annoyance, but the failed mDNS response likely causes partial mDNS functionality loss for Android and iPhone devices.

**Environment (please complete the following information):**
Zephyr 3.7-rc1 @ e5c05da9cbda7bc68aa84b796b828767b5eea6d7

@jukkar
@rlubos

**Comment by jukkar** [comment]
@EricNRS please try the proposal I sent if it fixes your issue.

**Comment by EricNRS** [comment]
@jukkar Yes, the patch fixes the Android / iPhone `<err> net_dns_dispatcher: DNS recv error (-22)` error.
