### ISSUE TITLE
soc: esp32: undefined symbol SRAM1_DRAM_USABLE_START

### ISSUE THREAD

**Issue by RomainPelletant** [zephyrproject-rtos/zephyr#74836]
**Describe the bug**
On ESP32 boards, linker show the following error when CONFIG_BT is enabled

```
zephyr-sdk-0.16.8/xtensa-espressif_esp32_zephyr-elf/bin/../lib/gcc/xtensa-espressif_esp32_zephyr-elf/12.2.0/../../../../xtensa-espressif_esp32_zephyr-elf/bin/ld.bfd:zephyr/linker_zephyr_pre0.cmd:28: undefined symbol `SRAM1_DRAM_USABLE_START' referenced in expression
```

**To Reproduce**
1. build a sample with CONFIG_BT=y on ESP32 boar
2. See error

**Environment (please complete the following information):**
 - OS: MacOS
 - Toolchain Zephyr SDK
 - main branch

**Additional context**
In soc/espressif/esp32/default.ld,

```
 #ifdef CONFIG_BT
_heap_sentry = SRAM1_DRAM_USABLE_START;
```
shall be replaced by
```
 #ifdef CONFIG_BT
_heap_sentry = SRAM1_DRAM_USER_START;
```

**Comment by sylvioalves** [comment]
@RomainPelletant thanks for submitting. I was about to do it. :)
