### ISSUE TITLE
croxel_cx1825 fails to build samples which require arduino_header

### ISSUE THREAD

**Issue by aescolar** [zephyrproject-rtos/zephyr#74889]
**Describe the bug**
Samples which require the DT node arduino_header fail to build in the croxel_cx1825
The board claims support for arduino_i2c & arduino_gpio in its twister yaml, but with those several samples which filter on those tags and require arduino_header will fail to build.

**To Reproduce**
1. twister -p croxel_cx1825/nrf52840  -T samples/shields/x_nucleo_iks4a1/
4. See errors

Same for samples/sensor/amg88xx/sample.sensor.amg88xx.amg88xx_eval_kit 

**Expected behavior**
No build failures, or tags which properly filter this board out of these tests.

**Impact**
11 failures in weekly CI related to this.

**Logs and console output**
```
devicetree error: /soc/i2c@40003000/lsm6dso16is@6a: undefined node label 'arduino_header'
``` 

**Environment (please complete the following information):**
 - OS: Linux, Ubuntu 22.04 CI
 - Toolchain (e.g Zephyr SDK, ...): 0.16.8
 - Commit SHA or Version used: Main as of now 18ebfe59d043f8b53bdd0c7ed48e2c9920abb881

**Comment by ubieda** [comment]
Looking now. Thanks for tagging me, @aescolar
