### ISSUE TITLE
Infineon Airoc WiFi driver fails to connect to correct AP

### ISSUE THREAD

**Issue by lawrencek52** [zephyrproject-rtos/zephyr#74910]
**Describe the bug**
I have two access points (AP) in my house with two similar SSIDs. They are MySSID and MySSID_Guest with passwords of MyPass, and GuestPass. Building the sample ~/zephyrproject/zephyr/samples/net/wifi and run the command `wifi connect -s "MySSID_Guest" -k 1 -p GuestPass` fails to connect.

Target platform is cy8cproto_062_4343w.

**To Reproduce**
To reproduce the behavior, put the following into a bash shell script and run the script from a local work directory:
```
set -e
rm -rf wifi_zephyr
cp -r ~/zephyrproject/zephyr/samples/net/wifi  wifi_zephyr
cd wifi_zephyr
echo CONFIG_NET_MGMT_EVENT_QUEUE_SIZE=100 >>prj.conf
echo CONFIG_NET_MGMT_EVENT_QUEUE_TIMEOUT=100 >>prj.conf
echo CONFIG_DNS_RESOLVER=y >>prj.conf
rm -rf build
time west build -t initlevels -b cy8cproto_062_4343w
time west flash --openocd /opt/Tools/ModusToolboxProgtools-1.1/openocd/bin/openocd
echo
echo ------------------------------------
echo in the serial terminal, at the uart:~$ prompt, enter the commands: 
echo wifi scan
echo wifi connect -s \"MySSID_Guest\" -k 1 -p GuestPass
echo net dns query pool.ntp.org
echo ------------------------------------
echo
```
The connection will fail with the error message
```
Function whd_wifi_join failed at line 1769 checkres = 33555457 
Connection request failed (-11)
[00:00:20.573,000] <err> infineon_airoc_wifi: Failed to connect with network
Connection request failed with error: -11
```

**Expected behavior**
The board should connect to the AP. and display 
```
Connected
Connection requested
[00:00:13.388,000] <inf> net_dhcpv4: Received: 192.168.87.20
```

**Impact**
Unable to connect with some APs where there are two similarly named APs.

**Logs and console output**
See above in reproduce and expected behaviour.

**Environment:**
 - OS: Linux
 - Toolchain: Zephyr SDK, 0.16.8
 - Zephyr mainline 2024-06-24

**Additional context**
The issue is in the Infineon airoc wifi driver. The following patch resolves the issue, but has not been extensively tested.
```
diff --git a/drivers/wifi/infineon/airoc_wifi.c b/drivers/wifi/infineon/airoc_wifi.c
index 1b4ccaa1cf4..73a942d16b3 100644
--- a/drivers/wifi/infineon/airoc_wifi.c
+++ b/drivers/wifi/infineon/airoc_wifi.c
@@ -125,7 +125,7 @@ static void airoc_wifi_scan_cb_search(whd_scan_result_t **result_ptr, void *user
        if (status == WHD_SCAN_COMPLETED_SUCCESSFULLY) {
                k_sem_give(&airoc_wifi_data.sema_scan);
        } else if ((status == WHD_SCAN_INCOMPLETE) && (user_data != NULL) &&
-                  ((**result_ptr).SSID.length > 0)) {
+                  ((**result_ptr).SSID.length == ((whd_scan_result_t *)user_data)->SSID.length)) {
 
                if (strncmp(((whd_scan_result_t *)user_data)->SSID.value, (**result_ptr).SSID.value,
                            (**result_ptr).SSID.length) == 0) {
```

**Comment by npal-cy** [comment]
this issue resolved in https://github.com/zephyrproject-rtos/zephyr/pull/75238
