### ISSUE TITLE
doc: Asynchronous Notifications: Public User API sys_notify_get_method() is not documented.

### ISSUE THREAD

**Issue by butok** [zephyrproject-rtos/zephyr#75038]
**Describe the bug**
Public User API sys_notify_get_method() function is not documented: https://docs.zephyrproject.org/latest/services/notify.html#c.sys_notify_get_method

**Expected behavior**
All Public User API functions should be documented.

**Environment (please complete the following information):**

 - Commit SHA 4a47803b0c06fa6081cfc1a1051433cc81ce0469

**Comment by henrikbrixandersen** [comment]
@butok Could you submit a PR for adding the missing Doxygen?

**Comment by butok** [comment]
> @butok Could you submit a PR for adding the missing Doxygen?

It should be done by an author of this function.

**Comment by kartben** [comment]
> All Public User API functions should be documented.

This function is actually marked as internal. But since it's not done with the correct Doxygen construct, that makes it show up in the docs making people think it's public, while it's not
