### ISSUE TITLE
[Coverity CID :185523] Memory - illegal accesses in /drivers/sensor/lsm6dsl/lsm6dsl.c

### ISSUE THREAD

**Issue by mandarcthorat1** [zephyrproject-rtos/zephyr#7508]
Static code scan issues seen in File: /drivers/sensor/lsm6dsl/lsm6dsl.c
 Category: Memory - illegal accesses
 Function: lsm6dsl_odr_to_freq_val
 Component: Drivers
 CID: 185523
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by MaureenHelm** [comment]
@avisconti Will you please have a look at this?

**Comment by avisconti** [comment]
@MaureenHelm 
It seems already fixed by commit 3ff4065cb3ad2490183bc0d60cb985c7e4c3b9e0
Thanks to Andy Gross!

**Comment by nashif** [comment]
fixed, closing
