### ISSUE TITLE
esp32: temp sensor fails due to constructor attribute

### ISSUE THREAD

**Issue by sylvioalves** [zephyrproject-rtos/zephyr#75169]
**Describe the bug**
After #74682, some samples started failing for ESP32 SoC due to
unused constructor attribute present in hal_espressif.

Build error:
`GNU-style constructors required but STATIC_INIT_GNU not enabled`

**To Reproduce**
1.  rm -rf build; west build -p -b esp32c3_devkitm samples/sensor/die_temp_polling -T sample.sensor.die_temperature_polling

**Expected behavior**
Build working.

**Environment (please complete the following information):**
 - OS: Linux
 - Zephyr SDK: 0.16.8

**Comment by jean-roland** [comment]
Hello guys, I have the same error message on Zephyr 3.7.0 through platformio on stm32 boards. It worked fine with Zephyr 3.5.0, any idea what could cause this?
