### ISSUE TITLE
Blinky sample fail to build for nucleo_wb55rg

### ISSUE THREAD

**Issue by jovasco** [zephyrproject-rtos/zephyr#75519]
**Describe the bug**

I've followed the Getting Started Guide to build blinky on nucleo_wb55rg. It fails with the below log.

It seems to be missing the file *stm32wb55rgvx-pinctrl.dtsi*

**To Reproduce**
1. Follow the Getting Started Guide
2. west build -p always -b nucleo_wb55rg samples\basic\blinky
3. See error

**Expected behavior**

I would expect a good build.

**Logs and console output**
```
-- Found BOARD.dts: C:/.../zephyrproject/zephyr/boards/st/nucleo_wb55rg/nucleo_wb55rg.dts
In file included from <command-line>:
C:/.../zephyrproject/zephyr/boards/st/nucleo_wb55rg/nucleo_wb55rg.dts:9:10: fatal error: st/wb/stm32wb55rgvx-pinctrl.dtsi: No such file or directory
    9 | #include <st/wb/stm32wb55rgvx-pinctrl.dtsi>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
CMake Error at C:/.../zephyrproject/zephyr/cmake/modules/extensions.cmake:4362 (message):
  failed to preprocess devicetree files (error code 1):
  C:/.../zephyrproject/zephyr/boards/st/nucleo_wb55rg/nucleo_wb55rg.dts
Call Stack (most recent call first):
  C:/.../zephyrproject/zephyr/cmake/modules/dts.cmake:243 (zephyr_dt_preprocess)
  C:/.../zephyrproject/zephyr/cmake/modules/zephyr_default.cmake:132 (include)
  C:/.../zephyrproject/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:66 (include)
  C:/.../zephyrproject/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:92 (include_boilerplate)
  CMakeLists.txt:4 (find_package)
```

**Environment (please complete the following information):**
 - OS: (Windows
 - Toolchain Zephyr SDK 0.16.8
 - zephyr main branch c9708ff951e5915a9b68d23e6ec960fc265bb2a6

**Comment by erwango** [comment]
The missing file is provided in https://github.com/zephyrproject-rtos/hal_stm32/tree/main/dts/st/wb.
Please run `west update`, to ensure that `hal_stm32` is available in your workspace.

Closing this issue, as this is a wokspace configuration issue.
If you still face the same issue, please reach #stm32 channel on Zephyr discord server.
