### ISSUE TITLE
cst816s not working with Waveshare 1.69inch Touch LCD Module

### ISSUE THREAD

**Issue by ljunquera** [zephyrproject-rtos/zephyr#75514]
**Describe the bug**
I am using a [Waveshare 1.69inch Touch LCD Module 1](https://www.waveshare.com/wiki/1.69inch_Touch_LCD_Module) which states it uses a cst816s driver for touch, yet in my testing swipes and button presses are not being recognized properly. I don't see any one (1) events which seem to indicate a release.

There are numerous examples for other platforms using this Waveshare: Raspberry Pi Pico User Guide, ESP32S3 User Guide, STM32 User Guide, and Arduino User Guide. I was looking to create one for Zephyr. They have samples for each and [cst816 reference documentation](https://files.waveshare.com/upload/c/c2/CST816S_register_declaration.pdf).

Please also mention any information which could help others to understand
the problem you're facing:
 - I am using [nRF5340 Development Kit](https://www.nordicsemi.com/Products/Development-hardware/nRF5340-DK)
 - printk statements from within the cst816s driver
 - not regression

**To Reproduce**
1. I have changed the [lvgl sample to test for swipes](https://github.com/ljunquera/lvgl_swipe).
2. I have added printk statements to the cst816 driver:
```
	if (pressed) {
		printk("pressed event: %d, row: %d, col: %d\n", event, row, col);
		input_report_abs(dev, INPUT_ABS_X, col, false, K_FOREVER);
		input_report_abs(dev, INPUT_ABS_Y, row, false, K_FOREVER);
		input_report_key(dev, INPUT_BTN_TOUCH, 1, true, K_FOREVER);
	} else {
		printk("not pressed event: %d, row: %d, col: %d\n", event, row, col);
		input_report_key(dev, INPUT_BTN_TOUCH, 0, true, K_FOREVER);
	}
```
 3. In the driver I have `#define CST816S_CHIP_ID 0xB5` and commented out `//#define CST816S_CHIP_ID 0xB4` which is a recent change.

**Expected behavior**
- I expect a left swipe to register as a left swipe, right as a right, top as a top, bottom as a bottom.
- I expect a button press to register as a button press.

**Impact**
Show stopper currently

**Logs and console output**
This is a button press (with printk in interrupt):
```
cst816s_isr_handler
cst816s_isr_handler
pressed event: 0, row: 86, col: 109
pressed event: 0, row: 86, col: 109
cst816s_isr_handler
cst816s_isr_handler
pressed event: 2, row: 86, col: 109
pressed event: 2, row: 86, col: 109
cst816s_isr_handler
cst816s_isr_handler
pressed event: 2, row: 86, col: 109
[00:00:05.567,932] <err> cst816s: Could not read x data
```

This is a swipe from the left most of the screen to the right in the midpoint vertically of a 240x280 screen (removed the pintk from interrup):
```
*** Booting nRF Connect SDK v3.5.99-ncs1-1 ***
pressed event: 0, row: 129, col: 20
pressed event: 0, row: 129, col: 20
pressed event: 2, row: 129, col: 20
pressed event: 2, row: 129, col: 20
pressed event: 2, row: 129, col: 20
pressed event: 2, row: 129, col: 20
pressed event: 2, row: 129, col: 20
pressed event: 2, row: 129, col: 20
pressed event: 2, row: 129, col: 20
pressed event: 2, row: 129, col: 20
pressed event: 0, row: 189, col: 200
pressed event: 0, row: 189, col: 200
pressed event: 2, row: 189, col: 200
pressed event: 2, row: 189, col: 200
pressed event: 2, row: 189, col: 201
pressed event: 2, row: 189, col: 201
pressed event: 2, row: 188, col: 203
pressed event: 2, row: 188, col: 203
pressed event: 2, row: 187, col: 205
pressed event: 2, row: 187, col: 205
[00:00:01.794,952] <dbg> app: on_lvgl_screen_gesture_event_callback: Gesture event detected 12
[00:00:01.794,982] <dbg> app: handle_screen_gesture: BOTTOM gesture detected
```

**Environment (please complete the following information):**
 - OS: MacOS
 - Toolchain Zephyr

**Additional Information
-Waveshare provided me with [some documentation](https://github.com/ljunquera/lvgl_swipe/blob/main/documents/%E8%A7%A6%E6%91%B8%E8%8A%AF%E7%89%87cst78XX%E9%A9%B1%E5%8A%A8%E8%B0%83%E8%AF%95V1.0.pdf) on cst816d and cst816t, but support said the driver was cst816s.

**Comment by fabiobaltieri** [comment]
I don't have any hardware to check these, joelguittet@ could you verify that release events work on your boards?

@ljunquera that `[00:00:05.567,932] <err> cst816s: Could not read x data` may be the handler failing on the release event, can you try to figure out more about the error? Is it a NACK from the device?

**Comment by ljunquera** [comment]
I can send you a device if you want.

**Comment by fabiobaltieri** [comment]
> I can send you a device if you want.

I'd rather you send me a PR with the fix instead. :-)

**Comment by ljunquera** [comment]
How can I get you more information? I can use a logic analyzer or add more debug statements?

**Comment by fabiobaltieri** [comment]
Sure grab a trace or add some prints, printing the i2c error code in the log could be a start. That said, this is a contributed driver so you'll have to contribute the fix yourself (or find some other contributor to do it).

**Comment by ljunquera** [comment]
@fabiobaltieri do you know anybody who would be interested in contracting to do this?

**Comment by ljunquera** [comment]
![Testing Results 1](https://github.com/user-attachments/assets/ddb250ce-f06b-4a9f-b5c5-33d6555029e7)

**Comment by ljunquera** [comment]
![Testing Results 1](https://github.com/user-attachments/assets/3caa37f0-9bca-4038-99b7-d7f7dbf99412)

**Comment by ljunquera** [comment]
Here are some testing results:
[Testing Results 1.pdf](https://github.com/user-attachments/files/16391168/Testing.Results.1.pdf)

**Comment by ljunquera** [comment]
Here are some testing results:
![Testing Image small](https://github.com/user-attachments/assets/78ce2965-6cc8-48c8-9f5a-7e3c44b23ffd)


| Gesture | Results |
|---------|--------|
| 1 | pressed event: 0, row: 33, col: 52<br>pressed event: 2, row: 33, col: 52<br>pressed event: 2, row: 33, col: 52<br>pressed event: 2, row: 33, col: 52<br>pressed event: 2, row: 33, col: 52<br>pressed event: 2, row: 33, col: 52<br>pressed event: 2, row: 33, col: 52<br>pressed event: 2, row: 33, col: 52<br>pressed event: 2, row: 33, col: 52<br>pressed event: 2, row: 33, col: 52<br>pressed event: 0, row: 278, col: 69<br>pressed event: 2, row: 278, col: 69<br>pressed event: 2, row: 278, col: 69<br>pressed event: 2, row: 278, col: 69<br>pressed event: 2, row: 278, col: 69<br>pressed event: 2, row: 278, col: 69<br>pressed event: 2, row: 278, col: 69<br>pressed event: 2, row: 278, col: 69<br>pressed event: 2, row: 278, col: 69<br>pressed event: 2, row: 278, col: 68 |
| 2 |  pressed event: 0, row: 33, col: 118<br>pressed event: 2, row: 33, col: 118<br>pressed event: 2, row: 33, col: 118<br>pressed event: 2, row: 33, col: 118<br>pressed event: 2, row: 33, col: 118v<br>pressed event: 2, row: 33, col: 118<br>pressed event: 2, row: 33, col: 118<br>pressed event: 2, row: 33, col: 118<br>pressed event: 2, row: 33, col: 118<br>pressed event: 2, row: 33, col: 118<br>pressed event: 0, row: 278, col: 104<br>pressed event: 2, row: 278, col: 104<br>pressed event: 2, row: 278, col: 104<br>pressed event: 2, row: 278, col: 104<br>pressed event: 2, row: 278, col: 104<br>pressed event: 2, row: 278, col: 104<br>pressed event: 2, row: 278, col: 104<br>pressed event: 2, row: 278, col: 104<br>pressed event: 2, row: 278, col: 104<br>pressed event: 2, row: 278, col: 104 |
| 3 |  pressed event: 0, row: 51, col: 183<br>pressed event: 2, row: 51, col: 183<br>pressed event: 2, row: 51, col: 183<br>pressed event: 2, row: 51, col: 183<br>pressed event: 2, row: 51, col: 183<br>pressed event: 2, row: 51, col: 183<br>pressed event: 2, row: 51, col: 183<br>pressed event: 2, row: 51, col: 183<br>pressed event: 2, row: 51, col: 183<br>pressed event: 2, row: 51, col: 183<br>pressed event: 0, row: 278, col: 188<br>pressed event: 2, row: 278, col: 188<br>pressed event: 2, row: 278, col: 188<br>pressed event: 2, row: 278, col: 188<br>pressed event: 2, row: 278, col: 188<br>pressed event: 2, row: 278, col: 188<br>pressed event: 2, row: 278, col: 188<br>pressed event: 2, row: 278, col: 188<br>pressed event: 2, row: 278, col: 188<br>pressed event: 2, row: 278, col: 188 |
| 4 | pressed event: 0, row: 151, col: 218<br>pressed event: 2, row: 151, col: 218<br>pressed event: 2, row: 151, col: 218<br>pressed event: 2, row: 151, col: 218<br>pressed event: 2, row: 151, col: 218<br>pressed event: 2, row: 151, col: 218<br>pressed event: 2, row: 151, col: 218<br>pressed event: 2, row: 151, col: 218<br>pressed event: 2, row: 151, col: 218<br>pressed event: 2, row: 150, col: 218<br>pressed event: 0, row: 94, col: 157<br>pressed event: 2, row: 94, col: 157<br>pressed event: 2, row: 94, col: 157<br>pressed event: 2, row: 94, col: 157<br>pressed event: 2, row: 94, col: 157<br>pressed event: 2, row: 94, col: 157<br>pressed event: 2, row: 94, col: 157<br>pressed event: 2, row: 93, col: 157<br>pressed event: 2, row: 92, col: 157<br>pressed event: 2, row: 91, col: 156<br>pressed event: 0, row: 81, col: 80<br>pressed event: 2, row: 81, col: 80<br>pressed event: 2, row: 81, col: 80<br>pressed event: 2, row: 81, col: 80<br>pressed event: 2, row: 81, col: 80<br>pressed event: 2, row: 81, col: 80<br>pressed event: 2, row: 80, col: 79<br>pressed event: 2, row: 79, col: 78<br>pressed event: 2, row: 78, col: 77<br>pressed event: 2, row: 77, col: 75 |
| 5 |  pressed event: 0, row: 160, col: 214<br>pressed event: 2, row: 160, col: 214<br>pressed event: 2, row: 160, col: 214<br>pressed event: 2, row: 160, col: 214<br>pressed event: 2, row: 160, col: 214<br>pressed event: 2, row: 160, col: 214<br>pressed event: 2, row: 160, col: 214<br>pressed event: 2, row: 160, col: 214<br>pressed event: 2, row: 160, col: 214<br>pressed event: 2, row: 160, col: 214<br>pressed event: 0, row: 122, col: 125<br>pressed event: 2, row: 122, col: 125<br>pressed event: 2, row: 122, col: 125<br>pressed event: 2, row: 122, col: 125<br>pressed event: 2, row: 123, col: 124<br>pressed event: 2, row: 125, col: 123<br>pressed event: 2, row: 127, col: 122<br>pressed event: 2, row: 129, col: 121<br>pressed event: 2, row: 131, col: 120<br>pressed event: 2, row: 133, col: 119<br>pressed event: 0, row: 160, col: 0<br>pressed event: 2, row: 160, col: 0<br>pressed event: 2, row: 160, col: 0<br>pressed event: 2, row: 160, col: 0<br>pressed event: 2, row: 160, col: 0<br>pressed event: 2, row: 160, col: 0<br>pressed event: 2, row: 160, col: 0<br>pressed event: 2, row: 160, col: 0<br>pressed event: 2, row: 160, col: 0<br>pressed event: 2, row: 160, col: 0 | 
| 6 |  pressed event: 0, row: 241, col: 214<br>pressed event: 2, row: 241, col: 214<br>pressed event: 2, row: 241, col: 214<br>pressed event: 2, row: 241, col: 214<br>pressed event: 2, row: 241, col: 214<br>pressed event: 2, row: 241, col: 214<br>pressed event: 2, row: 241, col: 214<br>pressed event: 2, row: 241, col: 214<br>pressed event: 2, row: 241, col: 214<br>pressed event: 2, row: 241, col: 214<br>pressed event: 0, row: 251, col: 155<br>pressed event: 2, row: 251, col: 155<br>pressed event: 2, row: 251, col: 155<br>pressed event: 2, row: 251, col: 155<br>pressed event: 2, row: 251, col: 155<br>pressed event: 2, row: 251, col: 155<br>pressed event: 2, row: 251, col: 155<br>pressed event: 2, row: 251, col: 155<br>pressed event: 2, row: 251, col: 155<br>pressed event: 2, row: 251, col: 155<br>pressed event: 0, row: 213, col: 77<br>pressed event: 2, row: 213, col: 77<br>pressed event: 2, row: 213, col: 77<br>pressed event: 2, row: 213, col: 77<br>pressed event: 2, row: 213, col: 77<br>pressed event: 2, row: 214, col: 77<br>pressed event: 2, row: 216, col: 77<br>pressed event: 2, row: 218, col: 77<br>pressed event: 2, row: 220, col: 77<br>pressed event: 2, row: 222, col: 77 |
| 7 | pressed event: 0, row: 224, col: 186<br>pressed event: 2, row: 224, col: 186<br>pressed event: 2, row: 224, col: 186<br>pressed event: 2, row: 224, col: 186<br>pressed event: 2, row: 224, col: 186<br>pressed event: 2, row: 224, col: 186<br>pressed event: 2, row: 224, col: 186<br>pressed event: 2, row: 224, col: 186<br>pressed event: 2, row: 224, col: 186<br>pressed event: 2, row: 224, col: 186<br>pressed event: 0, row: 1, col: 155<br>pressed event: 2, row: 1, col: 155<br>pressed event: 2, row: 1, col: 155<br>pressed event: 2, row: 1, col: 155<br>pressed event: 2, row: 1, col: 155<br>pressed event: 2, row: 1, col: 155<br>pressed event: 2, row: 1, col: 155<br>pressed event: 2, row: 1, col: 155<br>pressed event: 2, row: 1, col: 155<br>pressed event: 2, row: 1, col: 155 |
| 8 |  pressed event: 0, row: 240, col: 122<br>pressed event: 2, row: 240, col: 122<br>pressed event: 2, row: 240, col: 122<br>pressed event: 2, row: 240, col: 122<br>pressed event: 2, row: 240, col: 122<br>pressed event: 2, row: 240, col: 122<br>pressed event: 2, row: 240, col: 122<br>pressed event: 2, row: 240, col: 122<br>pressed event: 2, row: 240, col: 122<br>pressed event: 2, row: 240, col: 122<br>pressed event: 0, row: 1, col: 148<br>pressed event: 2, row: 1, col: 148<br>pressed event: 2, row: 1, col: 148<br>pressed event: 2, row: 1, col: 148<br>pressed event: 2, row: 1, col: 148<br>pressed event: 2, row: 1, col: 148<br>pressed event: 2, row: 1, col: 148<br>pressed event: 2, row: 1, col: 148<br>pressed event: 2, row: 1, col: 148<br>pressed event: 2, row: 1, col: 148 |
| 9 | pressed event: 0, row: 260, col: 45<br>pressed event: 2, row: 260, col: 45<br>pressed event: 2, row: 260, col: 45<br>pressed event: 2, row: 260, col: 45<br>pressed event: 2, row: 260, col: 45<br>pressed event: 2, row: 260, col: 45<br>pressed event: 2, row: 260, col: 45<br>pressed event: 2, row: 260, col: 45<br>pressed event: 2, row: 260, col: 45<br>pressed event: 2, row: 260, col: 45<br>pressed event: 0, row: 1, col: 87<br>pressed event: 2, row: 1, col: 87<br>pressed event: 2, row: 1, col: 87<br>pressed event: 2, row: 1, col: 87<br>pressed event: 2, row: 1, col: 87<br>pressed event: 2, row: 1, col: 87<br>pressed event: 2, row: 1, col: 87<br>pressed event: 2, row: 1, col: 87<br>pressed event: 2, row: 1, col: 87<br>pressed event: 2, row: 1, col: 87 |
| 10 |  pressed event: 0, row: 179, col: 7<br>pressed event: 2, row: 179, col: 7<br>pressed event: 2, row: 179, col: 7<br>pressed event: 2, row: 179, col: 7<br>pressed event: 2, row: 179, col: 7<br>pressed event: 2, row: 179, col: 7<br>pressed event: 2, row: 179, col: 7<br>pressed event: 2, row: 179, col: 7<br>pressed event: 2, row: 179, col: 7<br>pressed event: 2, row: 179, col: 7<br>pressed event: 0, row: 238, col: 89<br>pressed event: 2, row: 238, col: 89<br>pressed event: 2, row: 238, col: 89<br>pressed event: 2, row: 238, col: 89<br>pressed event: 2, row: 238, col: 89<br>pressed event: 2, row: 238, col: 89<br>pressed event: 2, row: 238, col: 89<br>pressed event: 2, row: 238, col: 89<br>pressed event: 2, row: 238, col: 89<br>pressed event: 2, row: 238, col: 89<br>pressed event: 0, row: 238, col: 171<br>pressed event: 2, row: 238, col: 171<br>pressed event: 2, row: 238, col: 171<br>pressed event: 2, row: 238, col: 171<br>pressed event: 2, row: 238, col: 171<br>pressed event: 2, row: 238, col: 171<br>pressed event: 2, row: 238, col: 171<br>pressed event: 2, row: 238, col: 171<br>pressed event: 2, row: 238, col: 171<br>pressed event: 2, row: 238, col: 171 |
| 11 | pressed event: 0, row: 144, col: 7<br>pressed event: 2, row: 144, col: 7<br>pressed event: 2, row: 144, col: 7<br>pressed event: 2, row: 144, col: 7<br>pressed event: 2, row: 144, col: 7<br>pressed event: 2, row: 144, col: 7<br>pressed event: 2, row: 144, col: 7<br>pressed event: 2, row: 144, col: 7<br>pressed event: 2, row: 144, col: 7<br>pressed event: 2, row: 144, col: 7<br>pressed event: 0, row: 161, col: 111<br>pressed event: 2, row: 161, col: 111<br>pressed event: 2, row: 161, col: 111<br>pressed event: 2, row: 161, col: 111<br>pressed event: 2, row: 160, col: 111<br>pressed event: 2, row: 159, col: 111<br>pressed event: 2, row: 158, col: 111<br>pressed event: 2, row: 157, col: 111<br>pressed event: 2, row: 156, col: 111<br>pressed event: 2, row: 156, col: 111<br>pressed event: 0, row: 156, col: 237<br>pressed event: 2, row: 156, col: 237<br>pressed event: 2, row: 156, col: 237<br>pressed event: 2, row: 156, col: 237<br>pressed event: 2, row: 156, col: 237<br>pressed event: 2, row: 156, col: 237<br>pressed event: 2, row: 156, col: 237<br>pressed event: 2, row: 156, col: 237<br>pressed event: 2, row: 156, col: 237<br>pressed event: 2, row: 156, col: 237 |
| 12 | pressed event: 0, row: 54, col: 6<br>pressed event: 2, row: 54, col: 6<br>pressed event: 2, row: 54, col: 6<br>pressed event: 2, row: 54, col: 6<br>pressed event: 2, row: 54, col: 6<br>pressed event: 2, row: 54, col: 6<br>pressed event: 2, row: 54, col: 6<br>pressed event: 2, row: 54, col: 6<br>pressed event: 2, row: 54, col: 6<br>pressed event: 2, row: 54, col: 6<br>pressed event: 0, row: 90, col: 120<br>pressed event: 2, row: 90, col: 120<br>pressed event: 2, row: 90, col: 120<br>pressed event: 2, row: 90, col: 120<br>pressed event: 2, row: 90, col: 120<br>pressed event: 2, row: 90, col: 120<br>pressed event: 2, row: 90, col: 120<br>pressed event: 2, row: 90, col: 120<br>pressed event: 2, row: 90, col: 120<br>pressed event: 2, row: 90, col: 120 |
| 13 | pressed event: 0, row: 82, col: 47<br>pressed event: 2, row: 82, col: 47<br>pressed event: 2, row: 82, col: 47<br>pressed event: 2, row: 82, col: 47<br>pressed event: 2, row: 82, col: 47<br>pressed event: 2, row: 82, col: 47<br>pressed event: 2, row: 82, col: 47<br>pressed event: 2, row: 82, col: 47<br>pressed event: 2, row: 82, col: 47<br>pressed event: 2, row: 82, col: 47 |
| 14 |. pressed event: 0, row: 104, col: 176<br>pressed event: 2, row: 104, col: 176<br>pressed event: 2, row: 104, col: 176<br>pressed event: 2, row: 104, col: 176<br>pressed event: 2, row: 104, col: 176<br>pressed event: 2, row: 104, col: 176<br>pressed event: 2, row: 104, col: 176<br>pressed event: 2, row: 104, col: 176<br>pressed event: 2, row: 104, col: 176<br>pressed event: 2, row: 104, col: 176 |
| 15 | pressed event: 0, row: 163, col: 116<br>pressed event: 2, row: 163, col: 116<br>pressed event: 2, row: 163, col: 116<br>pressed event: 2, row: 163, col: 116<br>pressed event: 2, row: 163, col: 116<br>pressed event: 2, row: 163, col: 116<br>pressed event: 2, row: 163, col: 116<br>pressed event: 2, row: 163, col: 116<br>pressed event: 2, row: 163, col: 116<br>pressed event: 2, row: 163, col: 116 |
| 16 | pressed event: 0, row: 228, col: 42<br>pressed event: 2, row: 228, col: 42<br>pressed event: 2, row: 228, col: 42<br>pressed event: 2, row: 228, col: 42<br>pressed event: 2, row: 228, col: 42<br>pressed event: 2, row: 228, col: 42<br>pressed event: 2, row: 228, col: 42<br>pressed event: 2, row: 228, col: 42<br>pressed event: 2, row: 228, col: 42<br>pressed event: 2, row: 228, col: 42 |
| 17 | pressed event: 0, row: 238, col: 154<br>pressed event: 2, row: 238, col: 154<br>pressed event: 2, row: 238, col: 154<br>pressed event: 2, row: 238, col: 154<br>pressed event: 2, row: 238, col: 154<br>pressed event: 2, row: 238, col: 154<br>pressed event: 2, row: 238, col: 154<br>pressed event: 2, row: 238, col: 154<br>pressed event: 2, row: 238, col: 154<br>pressed event: 2, row: 238, col: 154 |

**Comment by fabiobaltieri** [comment]
> @fabiobaltieri do you know anybody who would be interested in contracting to do this?

Not really, try asking in #job-posting on http://chat.zephyrproject.org/

**Comment by ljunquera** [comment]
It's possible it might be the cst816t. Just a guess but I see that one referenced on one of their pages. [Here is a reference](https://github.com/koendv/cst816t) to a library I found as well.

**Comment by ljunquera** [comment]
Closing the loop on this a while later — for my case, the root cause was self-inflicted, not a driver bug: separate bring-up code I'd added was clearing bit 5 (IRQ_EN_CHANGE) of the CST816S's IRQ_CTL register (0xFA) to silence an unrelated idle-interrupt flood. That bit turns out to control the chip's ability to signal a touched→released transition at all — clearing it left IRQ_EN_TOUCH still firing for press/contact, but release interrupts never arrived, exactly matching the event: 0 → repeated event: 2 → nothing pattern in my trace above. Confirmed via a live I2C register read against the running chip, and cross-checked against a second board that never ran the offending init code and swiped reliably the whole time. Re-enabling the bit fixed it immediately (release now reported ~4ms after press). Flagging in case anyone else hits this: the stock driver never writes to IRQ_CTL itself, so if you're seeing this with an unmodified driver, check whether any board-specific init code (yours or a vendor HAL) is touching that register — that's the one thing that reproduces this exact failure signature.
