### ISSUE TITLE
No multithreading mode with CONFIG_NO_OPTIMIZATIONS=y fails to start (Cortex-M)

### ISSUE THREAD

**Issue by nordic-krch** [zephyrproject-rtos/zephyr#75586]
**Describe the bug**
Application fails to start after disabling optimization and multithreading on Cortex-M. Code seems to stuck in `z_arm_switch_to_main_no_multithreading` function.

**To Reproduce**
1. `west build -p -b qemu_cortex_m3 samples/hello_world -- -DCONFIG_MULTITHREADING=n -DCONFIG_NO_OPTIMIZATIONS=y`
2. run sample and observe that there is no expected output.

**Expected behavior**
Code should execute as with optimization (if stack sizes are correct).

**Impact**
Hard to debug no-multithreading applications.

**Environment (please complete the following information):**
 -Linux
 - Zephyr SDK 0.16.8
 - Commit SHA: c9708ff951e5915a9b68d23e6ec960fc265bb2a6

**Comment by ithinuel** [comment]
Hi, thank you for that report.
Have you tried increasing the various stack size involved (see documentation [here](https://docs.zephyrproject.org/latest/kconfig.html#CONFIG_NO_OPTIMIZATIONS))?

`NO_OPTIMIZATIONS` has a significant impact on the application’s stack usage.
