### ISSUE TITLE
samples/subsys/logging/logger/sample.logger.usermode fails to build for bytesensi_l & bl654_dvk/nrf52840/pa

### ISSUE THREAD

**Issue by aescolar** [zephyrproject-rtos/zephyr#75617]
**Describe the bug**
samples/subsys/logging/logger/sample.logger.usermode fails to build for both
* bytesensi_l 
* bl654_dvk/nrf52840/pa

**To Reproduce**
1. twister -p bytesensi_l -T samples/subsys/logging/logger -s sample.logger.usermode

**Expected behavior**
No build errors (or platforms filtered out from test)

**Impact**
2 failures in weekly CI

**Logs and console output**
```
warning: LOG_PRINTK (defined at subsys/logging/Kconfig.processing:8) has direct dependencies !USERSPACE && !LOG_MODE_MINIMAL && LOG with value n, but is currently being y-selected by the following symbols:
 - LOG_BACKEND_RTT_FORCE_PRINTK (defined at subsys/logging/backends/Kconfig.rtt:104), with value y, direct dependencies LOG_BACKEND_RTT && !LOG_FRONTEND_ONLY && !LOG_MODE_MINIMAL && LOG (value: y), and select condition LOG_BACKEND_RTT && !LOG_FRONTEND_ONLY && !LOG_MODE_MINIMAL && LOG (value: y)
```

**Environment (please complete the following information):**
 - OS: Linux, Ubuntu 22.04 CI
 - Toolchain (e.g Zephyr SDK, ...): 0.16.8
 - Commit SHA or Version used: main as of now 980d3f4c4f4ef4ec15c5bcd538155a184df6e1b8

**Comment by aescolar** [comment]
CC @dariis @rerickson1 @greg-leach

**Comment by morandg** [comment]
Same for ``bytesensi_l`` that produces the same error as the other excluded platform.
