### ISSUE TITLE
Luong Minh Thao Contributor Nomination

### ISSUE THREAD

**Issue by ydamigos** [zephyrproject-rtos/zephyr#75667]
# Nomination

## GitHub User

Full Name: Luong Minh Thao
GitHub username: @thaoluonguw
Organization: Renesas

## Supporting Documents
https://github.com/zephyrproject-rtos/zephyr/pull/72150

**Comment by nashif** [comment]
https://github.com/zephyrproject-rtos/zephyr/invitations
