### ISSUE TITLE
usb: update bcdUSB to 2.00

### ISSUE THREAD

**Issue by jfischer-phytec-iot** [zephyrproject-rtos/zephyr#7570]
There is suggestion/need to increase bcdUSB to 2.00. Are all supported controllers USB Rev. 2.0 compliant?

- Kinetis (USBFSOTG) is USB 2.0 full-speed/low-speed compliant
- NRF52 is Fully compliant to Universal Serial Bus Specification Revision 2.0 Full Speed part
- STM32 Cube HAL, are all supported controllers USB 2.0 compliant ~?~ :ok: (STM32F1, STM32F3, STM32F4, STM32L4 USB 2.0 Specification compliant )
- usb_dc_dw.c, #7356 
- usb_dc_sam0.c ~?~ :ok: (SAM D21, SAM R21 Family module complies with the Universal Serial Bus (USB) 2.1
specification)

@ydamigos, @carlescufi, @nzmichaelh @finikorg @loicpoulain

**Comment by carlescufi** [comment]
CC @pawelzadrozniak, will defer to him

**Comment by pawelzadrozniak** [comment]
There could be a configuration option to choose between 1.1 and 2.0.

**Comment by jfischer-phytec-iot** [comment]
>There could be a configuration option to choose between 1.1 and 2.0.

Only if there is no other way. e.g. if we have a non 2.0 compatible controller

**Comment by nzmichaelh** [comment]
The SAM0 is USB2 so you're good there.  I can't think of any reasons to support USB1.1.
