### ISSUE TITLE
z_unpend_thread_no_timeout inlining issues with 3rd party compiler

### ISSUE THREAD

**Issue by Hadatko** [zephyrproject-rtos/zephyr#75704]
**Describe the bug**

Please also mention any information which could help others to understand
the problem you're facing:
 - What target platform are you using?
 - What have you tried to diagnose or workaround this issue?
 - Is this a regression? If yes, have you been able to "git bisect" it to a
   specific commit?
 - ...

![image](https://github.com/zephyrproject-rtos/zephyr/assets/13130700/9c68348f-6670-4015-b7cd-f5e03b39b8f6)

Usage ALWAYS_INLINE in definition in sched.c file makes our compiler complaning for missing implementation of that function in timer.c

**To Reproduce**
1. mkdir build; cd build
2. cmake -DBOARD=board\_xyz
3. make

Maybe others compilers are not complaning. Currently we are using unsupported architecture

**Expected behavior**

Removing ALWAYS_INLINE from source definition fixed issue.

**Impact**
What impact does this issue have on your progress (e.g., annoyance, showstopper)

**Logs and console output**
If applicable, add console logs or other types of debug information
e.g Wireshark capture or Logic analyzer capture (upload in zip archive).
copy-and-paste text and put a code fence (\`\`\`) before and after, to help
explain the issue. (if unable to obtain text log, add a screenshot)

![image](https://github.com/zephyrproject-rtos/zephyr/assets/13130700/f80dc83b-647e-4508-99e8-827b03e6e634)

**Environment (please complete the following information):**
 - OS: (e.g. Linux, MacOS, Windows) Linux
 - Toolchain (e.g Zephyr SDK, ...) CGT from TI
 - Commit SHA or Version used
VERSION_MAJOR = 3
VERSION_MINOR = 6
PATCHLEVEL = 99
VERSION_TWEAK = 0
EXTRAVERSION =

**Additional context**
Add any other context that could be relevant to your issue, such as pin setting,
target configuration, ...

**Comment by nashif** [comment]
@Hadatko  your bug text has lots of boilerplate and template text, please clarify what the bug is exaxtly, starting with the title.

**Comment by Hadatko** [comment]
Hi, maybe you could use markdown brackets for disabling description in posted file. Like here: https://github.com/EmbeddedRPC/erpc/blob/develop/.github/ISSUE_TEMPLATE/bug_report.md?plain=1
I saw this also in other projects.

That is just an suggestion.
The desription:
![image](https://github.com/zephyrproject-rtos/zephyr/assets/13130700/87ebf9f5-62b4-488a-8005-7e280bed62a6)
Usage ALWAYS_INLINE in definition in sched.c file makes our compiler complaning for missing implementation of that function in timer.c
Maybe others compilers are not complaning. Currently we are using unsupported architecture
![image](https://github.com/zephyrproject-rtos/zephyr/assets/13130700/d868730f-716c-49bc-b41d-8309ee01462f)
Removing ALWAYS_INLINE from source definition fixed issue.
