### ISSUE TITLE
Fail to build samples/sysbuild/hello_world

### ISSUE THREAD

**Issue by aaronyegx** [zephyrproject-rtos/zephyr#75746]
**Describe the bug**
Following the https://docs.zephyrproject.org/latest/samples/sysbuild/hello_world/README.html, we always see "warning: malformed string literal in assignment to REMOTE_BOARD" warning then fail to build the image.

**To Reproduce**
1. cd zephyr
2. west build -b nrf54h20dk/nrf54h20/cpuapp --sysbuild samples/sysbuild/hello_world -- -DSB_CONFIG_REMOTE_BOARD='"nrf54h20dk/nrf54h20/cpurad"'
3. See error

**Expected behavior**
No compiling issue.

**Logs and console output**

```
PS C:\ambiqzephyr\zephyr> west build -b nrf54h20dk/nrf54h20/cpuapp --sysbuild .\samples\sysbuild\hello_world -- -DSB_CONFIG_REMOTE_BOARD='"nrf54h20dk/nrf54h20/cpurad"'
-- west build: generating a build system
Loading Zephyr module(s) (Zephyr base (cached)): sysbuild_default
-- Cache files will be written to: C:/ambiqcodes/ambiqzephyr/zephyr/.cache
-- Found west (found suitable version "1.0.0", minimum required is "0.14.0")
-- Board: nrf54h20dk, qualifiers: nrf54h20/cpuapp

C:/ambiqcodes/ambiqzephyr/zephyr/build/zephyr/misc/generated/extra_kconfig_options.conf:2: warning: malformed string literal in assignment to REMOTE_BOARD (defined at C:/ambiqcodes/ambiqzephyr/zephyr/samples/sysbuild/hello_world/Kconfig.sysbuild:6). Assignment ignored.Parsing C:/ambiqcodes/ambiqzephyr/zephyr/samples/sysbuild/hello_world/Kconfig.sysbuild
Loaded configuration 'C:/ambiqcodes/ambiqzephyr/zephyr/build/_sysbuild/empty.conf'
Merged configuration 'C:/ambiqcodes/ambiqzephyr/zephyr/build/_sysbuild/empty.conf'
Merged configuration 'C:/ambiqcodes/ambiqzephyr/zephyr/build/zephyr/misc/generated/extra_kconfig_options.conf'


error: Aborting due to Kconfig warnings

CMake Error at C:/ambiqcodes/ambiqzephyr/zephyr/cmake/modules/kconfig.cmake:389 (message):
  command failed with return code: 1
Call Stack (most recent call first):
  cmake/modules/sysbuild_kconfig.cmake:103 (include)
  cmake/modules/sysbuild_default.cmake:17 (include)
  C:/ambiqcodes/ambiqzephyr/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:75 (include)
  C:/ambiqcodes/ambiqzephyr/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:97 (include_boilerplate)
  C:/ambiqcodes/ambiqzephyr/zephyr/share/sysbuild-package/cmake/SysbuildConfig.cmake:8 (include)
  template/CMakeLists.txt:10 (find_package)

-- Configuring incomplete, errors occurred!
```

**Environment (please complete the following information):**
 - OS: Windows
 - Toolchain: Zephyr-SDK-0.16.8, 
 - Commit SHA: 80ce7d2315046e0852e6b95036baf29d62ac731b in main branch (after west update)

**Comment by aaronyegx** [comment]
Hi @gmarull , I encounter the building issue on samples/sysbuild/hello_world. Could you help check if I miss anything? Thanks.

**Comment by henrikbrixandersen** [comment]
The command `west build -b nrf54h20dk/nrf54h20/cpuapp --sysbuild samples/sysbuild/hello_world -- -DSB_CONFIG_REMOTE_BOARD='"nrf54h20dk/nrf54h20/cpurad"'` builds fine under GNU/Linux. I assume this must be a Windows CMD issue.

**Comment by gmarull** [comment]
The issue you are observing is likely due to https://github.com/zephyrproject-rtos/zephyr/issues/69552, which has not been fixed yet. On Linux the escaping trick `'"` works fine, maybe not on Windows. You can still make use of twister configurations as suggested in the sample, that is, run:

```
west build -b nrf54h20dk/nrf54h20/cpuapp -T sample.sysbuild.hello_world.nrf54h20dk_cpuapp_cpurad samples/sysbuild/hello_world
```

I'll close this issue as there's another tracking the problem, please, add your details there if necessary.

**Comment by krissrex** [comment]
On Windows, try `-DSB_CONFIG_REMOTE_BOARD='\"nrf54h20dk/nrf54h20/cpurad\"'`
