### ISSUE TITLE
Migrate Websocket to BSD sockets

### ISSUE THREAD

**Issue by laperie** [zephyrproject-rtos/zephyr#7589]
As a part of the Zephyr Networking API rework we need to update all protocols to be based on socket.h instead of net_app/net_context.

**Comment by pfalcon** [comment]
Following @jukkar's recent issue cleanup, let me close this one too. We removed websockets lib from Zephyr, so formally websockets can be "migrated" to sockets. Such a lib would need to be made from start (written from scratch or suitable 3rd-aprty lib picked up). And that's definitely another issue. Closing. (Feel free to reopen if disagree).
