### ISSUE TITLE
update BSD sockets  implementation to use optimized networking buffers

### ISSUE THREAD

**Issue by laperie** [zephyrproject-rtos/zephyr#7590]
In order to fully benefit from new networking buffers, BSD sockets needs to be re-implemented using the new net_buf

**Comment by tautologyclub** [comment]
Anyone mind pasting a link to discussion/PR on "new net_buf"?

**Comment by laperie** [comment]
> Anyone mind pasting a link to discussion/PR on "new net_buf"?

You can monitor progress of this work in #7578

**Comment by pfalcon** [comment]
@tbursztyka: This can be effectively closed now, right? (Thanks btw for taking charge of consistent upgrade of the all parts of the stack to new API.)

**Comment by tbursztyka** [comment]
already in now sockets pushes the buf/len to net_context. closing
