### ISSUE TITLE
[backport v3.5-branch, v3.6-branch] Bluetooth: Controller: Control procedure and compiler re-ordering fixes

### ISSUE THREAD

**Issue by cvinayak** [zephyrproject-rtos/zephyr#75981]
**Describe the bug**

1. A Host shall consider any error code that it does not
explicitly understand equivalent to the error code
Unspecified Error (0x1F).
Related to #74926

2. Fix missing validation of Connection Update Ind PDU. Ignore
invalid connection update parameters and force a silent
local connection termination.

3. Ensure that in LLCP reference to node_rx is cleared when
retention is NOT used, to avoid corruption of node_rx later
re-allocated

4. In case a CPR is intiated but rejected due to CPR active on
other connection, rx nodes are leaked due to retained node not
being properly released.

5. In ull_disable, it is imperative that the callback is set up before a
second reference counter check, otherwise it may happen that an LLL done
event has already passed when the disable callback and semaphore is
assigned.
This causes the HCI thread to wait until timeout and assert after
ull_ticker_stop_with_mark.
For certain compilers, due to compiler optimizations, it can be seen
from the assembler code that the callback is assigned after the second
reference counter check.
By adding memory barriers, the code correctly reorders code to the
expected sequence.

**Impact**
- Unresponsive implementation due to incorrect control procedure handling and other memory corruptions during runtime.

**Comment by henrikbrixandersen** [comment]
@cvinayak Zephyr v3.5 is EOL. Do you still plan to work on this?
