### ISSUE TITLE
Display does not work on `bl5340_dvk`

### ISSUE THREAD

**Issue by danieldegrasse** [zephyrproject-rtos/zephyr#75991]
**Describe the bug**
PR #64587 unintentionally changed the SPI device used for the display on the `bl5340_dvk` to `spi2` from `spi4`. This breaks the functionality of the display.

**To Reproduce**
1. `west build -p always -b bl5340_dvk//cpuapp samples/drivers/display`
2. `west flash`
3. display will not function

**Expected behavior**
Display should work

**Additional Context**

Issue reported (and fix suggested) by @dberlin [here](https://github.com/zephyrproject-rtos/zephyr/pull/64587#issuecomment-2229337258)

**Comment by nordicjm** [comment]
Duplicate of https://github.com/zephyrproject-rtos/zephyr/issues/75967

**Comment by dleach02** [comment]
lol... okay. Daniel reached out internally (he is traveling around the world) and asked for someone to submit...

**Comment by dberlin** [comment]
No worries - i had suggested he do it originally, but discovered a clean zephyr client laying around so just built and tested it myself :)
Hopefully he's enjoying his travel.
