### ISSUE TITLE
Integrate wolfSSL external code

### ISSUE THREAD

**Issue by ColtonWilley** [zephyrproject-rtos/zephyr#76002]
## Origin

https://github.com/wolfSSL/wolfssl

## Purpose

The wolfSSL embedded SSL library is a lightweight SSL/TLS library written in ANSI C and targeted for embedded, RTOS, and resource-constrained environments.

## Mode of integration

I would like to integrate this as a module similar to mbedTLS, module name could be wolfSSL.

## Maintainership

Myself Colton Willey (https://github.com/ColtonWilley) will maintain integration. 

## Pull Request

Following PR has TLS 1.2 integration for zephyr sockets layer.
https://github.com/zephyrproject-rtos/zephyr/pull/75828

## Description

The primary functionality is to facilitate TLS connections in resource constrained devices, and provide a more robust cryptographic library to zephyr users. 

The end goal here is to extend the implementation to support TLS 1.3, giving zephyr users an out of the box option for TLS 1.3. Furthermore given the deployment life-cycles of some systems using zephyr, they may already be looking at more forward thinking cryptographic solutions. WolfSSL gives out of the box support to zephyr users for TLS 1.3, a robust cryptographic library, and post quantum cryptography all designed for embedded targets.

## Dependencies

This component has no dependencies. Zephyr would have a dependency on the component but all calls will be guarded with CONFIG_WOLFSSL. 

## Revision

Latest master branch is fine. 

## License

GPL-2.0

**Comment by henrikbrixandersen** [comment]
> License
> 
> GPL-2.0

GPL-2.0 licensed software cannot be included in an Apache-2.0 licensed project like Zephyr. See https://www.apache.org/licenses/GPL-compatibility.html

**Comment by ColtonWilley** [comment]
I am aware that wolfSSL is GPL-2.0, which is not allowed under normal circumstances. I am petitioning the TSC for a possible license exemption as described in https://docs.zephyrproject.org/latest/contribute/external.html, and have filed this issue so the TSC members can determine the merit of this request.

**Comment by henrikbrixandersen** [comment]
> I am aware that wolfSSL is GPL-2.0, which is not allowed under normal circumstances. I am petitioning the TSC for a possible license exemption as described in https://docs.zephyrproject.org/latest/contribute/external.html, and have filed this issue so the TSC members can determine the merit of this request. 

This two licenses are _incompatible_ in this regard (linking against GPL-2.0 licensed code from Apache-2.0 licensed code). Please re-read the article linked above for further details. No TSC exemption can fix this incompatibility.

**Comment by nashif** [comment]
> I would like to integrate this as a module similar to mbedTLS, module name could be wolfSSL.

Please read https://docs.zephyrproject.org/latest/contribute/external.html#software-license. GPLv2 is incompatible with with Apache 2.0 and we will not be able to include GPLv2 as a module.

The only method of "integration" is outside of the zephyr project as an external module that users can include in their manifest if they have obtained a compatible license. See https://docs.zephyrproject.org/latest/contribute/external.html#integration-as-external-modules

You are welcome to contribute any changes to the project that would facilitate such integration with libraries other than mbedTLS.

> I am aware that wolfSSL is GPL-2.0, which is not allowed under normal circumstances. I am petitioning the TSC for a possible license exemption as described in [docs.zephyrproject.org/latest/contribute/external.html](https://docs.zephyrproject.org/latest/contribute/external.html), and have filed this issue so the TSC members can determine the merit of this request.

exepmtions are usually granted to licenses that are not OSI compatible or approved. GPLv2 is approved, however it is not compatible, so no exemptions can be done here.

**Comment by ColtonWilley** [comment]
Thank you all for your time on this issue. I see now that the licensing issues cannot be overcome. I mistakenly thought there were already GPLv2 modules in the zephyr tree like piclobc and qemu, but after looking closer I see now that those are either conditionally licensed per file groups, or are external tooling with no references. 

I will be closing this issue and its associated PR. My work did extend the existing TLS test suite for mbedTLS as well, so I will look at committing that separately.
