### ISSUE TITLE
 lpc55s69 flash block size issue

### ISSUE THREAD

**Issue by guicnDell** [zephyrproject-rtos/zephyr#76029]
This https://github.com/zephyrproject-rtos/zephyr/pull/68658 by @de-nordic introduced a bug for the lpc55s69 flash block size.

```
struct stream_flash_ctx {
	uint8_t *buf; /* Write buffer */
	size_t buf_len; /* Length of write buffer */
	size_t buf_bytes; /* Number of bytes currently stored in write buf */
	const struct device *fdev; /* Flash device */
	size_t bytes_written; /* Number of bytes written to flash */
	size_t offset; /* Offset from base of flash device to write area */
	size_t available; /* Available bytes in write area */
	stream_flash_callback_t callback; /* Callback invoked after write op */
#ifdef CONFIG_STREAM_FLASH_ERASE
	off_t last_erased_page_start_offset; /* Last erased offset */
#endif
	uint8_t erase_value;
	uint8_t write_block_size;	/* Offset/size device write alignment */
};
```

**write_block_size** and **erase_value** are 512 bytes on the lpc55s69, @decsny can confirm this.

During the stream_flash_init call:

```
	ctx->write_block_size = params->write_block_size;

	if (buf_len % ctx->write_block_size) {
		LOG_ERR("Buffer size is not aligned to minimal write-block-size");
		return -EFAULT;
	}
```

Causes a hard fault since` ctx->write_block_size` ends up being zero.
In my view, this is a critical bug and needs to be addressed before the Zephyr 3.7.0 release.

Can we just modify it to be size_t?

**Comment by de-nordic** [comment]
I have marked the bug as high priority because it hard faults devices with write-block-size >= 256, when using stream flash, which means that stream flash is not usable for these devices.
