### ISSUE TITLE
FCB Write Issue with Flash Sector Management

### ISSUE THREAD

**Issue by ananya-wattsnext** [zephyrproject-rtos/zephyr#76041]
I'm experiencing an issue with the FCB write functionality, specifically with how it manages flash sectors. I've followed the documentation to write data to the flash using the fcb_append function, but I'm seeing unexpected behavior when restarting the program. I am running this on esp32c3_devkitm.

`ret = fcb_append(&test_fcb, sizeof(logDataT), &loc);
if(ret == -ENOSPC)
{
    printf("Append failed. No memory left. Number of logData struct written: %d. Rotating.\n", logData_elem_count);                  
    ret = fcb_rotate(&test_fcb);
    if(ret != 0)
    {
        printf("Rotate failed.\n");
    }
    ret = fcb_append(&test_fcb, sizeof(logDataT), &loc);
    if(ret == -ENOSPC)
    {
        printf("Second append failure. Quitting.\n");
        return -ENOSPC;
    }
}

/* Data to be written to the flash. */
logDataT test_data = {.packCurrentMamps = logData_elem_count};
        
/* Write to the flash. */
ret = flash_area_write(test_fcb.fap, 
                        FCB_ENTRY_FA_DATA_OFF(loc),
                        &test_data, sizeof(logDataT));

if(ret != 0)
{
    printf("Failed to write to the flash.\n");
    return -1;
}
else{
    /* Finishes the entry append operation. */
    ret = fcb_append_finish(&test_fcb, &loc);
    if(ret != 0)
    {
        printf("Append finish failed.\n");
        return -1;
    }
    else{
        printf("Append finish success. Count: %d, loc: %ld\n", logData_elem_count, FCB_ENTRY_FA_DATA_OFF(loc));  
        logData_elem_count++; 
    }
}`

When I run this code, it writes data to the flash until location 14272. When I exit the program and run it again, I expect the next write to occur at location 14272 + 68 (since each element is 68 bytes). However, instead, it writes to location 12300. The active sector location is 12216.

![Screenshot from 2024-07-18 10-54-08](https://github.com/user-attachments/assets/76f9ad29-2656-4bad-a3fa-3a49b771c639)
![Screenshot from 2024-07-18 10-54-42](https://github.com/user-attachments/assets/276d40d8-69fd-4a02-befb-fd111d7e3ddd)

Expected Behavior:

I believe the correct behavior should be for fcb_init to find the last element written to in the sector and set the active sector accordingly in the fcb struct.

Additional observation:
On restarting the program another time the program is working as expected where fcb_init is able to find the sector that was last written to and set the location of the next element to write to correctly.

![Screenshot from 2024-07-18 10-59-05](https://github.com/user-attachments/assets/edc16d63-0cbc-4d22-b53c-0514f933d5ff)
![Screenshot from 2024-07-18 10-59-28](https://github.com/user-attachments/assets/a7a56a51-b1fb-4e6c-9b59-e563147b0418)

**To Reproduce**

**Impact**
I am not able to implement the data storing feature in the esp32c3 which is a very important feature of my project.

**Environment (please complete the following information):**

 - OS: Ubuntu 22.04.4 LTS 
 - Toolchain: Zephyr SDK
 - Version: zephyr-sdk-0.16.4

**Comment by aescolar** [comment]
@de-nordic please reprioritize if you think it should be otherwise
