### ISSUE TITLE
ARC objdump crash when creating zephyr.lst for one test

### ISSUE THREAD

**Issue by andrewboie** [zephyrproject-rtos/zephyr#7608]
This is a very strange issue which is believed to be a compiler bug.

The pull request #7609  introduces support for user mode access to k_queue objects. It doesn't do anything crazy. However, after the patch is applied, the invocation of objdump at the end of the build to disassemble the ELF file and create zephyr.lst generates a segmentation fault:

```
[100%] Linking C executable zephyr.elf
Generating files from zephyr.elf for board: quark_se_c1000_ss_devboard
/bin/sh: line 1: 30579 Segmentation fault      (core dumped) /opt/zephyr-sdk/sysroots/x86_64-pokysdk-linux/usr/bin/arc-zephyr-elf/arc-zephyr-elf-objdump -S zephyr.elf > zephyr.lst
make[2]: *** [zephyr/CMakeFiles/kernel_elf.dir/build.make:118: zephyr/zephyr.elf] Error 139
make[2]: *** Deleting file 'zephyr/zephyr.elf'
make[1]: *** [CMakeFiles/Makefile2:276: zephyr/CMakeFiles/kernel_elf.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
```

This only happens for ONE test in the tree, tests/power/multicore/arc on quark_se_c1000_ss_devboard, and ONLY if CONFIG_ASSERT is enabled.

The pull request was amended to disable CONFIG_OUTPUT_DISASSEMBLY for this test only. However this problem needs to reported to whoever maintains the ARC port of GCC. To reproduce the issue, delete the line which disables CONFIG_OUTPUT_DISASSEMBLY in the prj.conf for the test, enable CONFIG_ASSERT=y and CONFIG_ASSERT_LEVEL=2 and try to build for the quark_se_c1000_ss_devboard.

**Comment by moto-timo** [comment]
https://github.com/zephyrproject-rtos/meta-zephyr-sdk/pull/99 Fixes the binutils issue, but I only verified the test in question.
