### ISSUE TITLE
Provide a Requirements Traceability Matrix (RTM)

### ISSUE THREAD

**Issue by nashif** [zephyrproject-rtos/zephyr#7618]
Provide a way to link requirements throughout the validation process. The purpose of the Requirements Traceability Matrix is to ensure that all requirements defined are tested.

From wikipedia:

_"A traceability matrix is a document, usually in the form of a table, used to assist in determining the completeness of a relationship by correlating any two baselined documents using a many-to-many relationship comparison.[1] It is often used with high-level requirements (these often consist of marketing requirements) and detailed requirements of the product to the matching parts of high-level design, detailed design, test plan, and test cases."_

Goal is to use existing documentation infrastructure on top of doxygen and enhance it to  give us the traceability between 
 - implementation
 - documentation 
 - tests

This has the advantage of not having to duplicate information and reusing resources we already have and use. It should also be developer friendly and easy to use and adapt to.

 - [ ] Requirement Catalog
   - [ ] Provide unique requirement IDs 
 - [ ] Link implementation of features to high level requirements
 - [ ] link test cases and tests in general to feature implementation
 - [ ] Document tests cases
   - [ ] Provide unique test case IDs

**Comment by herve0026** [comment]
Hi Nashif. 
I just start documenting my code with  custom doxygen tags @req, @satisfy . As explained in zephyr projet documentation page. 
By the way, thanks very much for this page.
I was wondering, if by any chance the script to generate the RTM, could also be shared by the zephyr project ?
I found this RTM very nice and would like to obtain the same kind of report but my skill in writing script is quiet poor. I guess you have used python.
Best regards.
