### ISSUE TITLE
Bluetooth: bt_disable() creates HCI Reset Timeout when IPC driver is used

### ISSUE THREAD

**Issue by rugeGerritsen** [zephyrproject-rtos/zephyr#76202]
**Describe the bug**
When bt_disable() is called using the IPC driver, the HCI Reset command times out.
This is because the RX thread is already aborted, therefore not allowing the command complete to arrive.

**To Reproduce**
Build a Bluetooth app for nRF53 and set `CONFIG_BT_RECV_WORKQ_BT`. Call `bt_disable()`. Observe that HCI reset times out.

**Impact**
`bt_disable()` doesn't work.

**Environment (please complete the following information):**
Started happening after https://github.com/zephyrproject-rtos/zephyr/pull/72323, d0e75ab87c4b53d66008c941c38709a2fca9dbea.

**Comment by jhedberg** [comment]
The proposed fix is reverting the order in bt_disable() to what it was before the HCI API PR, so I think this is a fairly safe change which can be justified for inclusion in the upcoming release (hence the added release blocker label).
