### ISSUE TITLE
drivers: usb: udc: udc_mcux_ip3511 does not report UDC_EVT_SOF

### ISSUE THREAD

**Issue by henrikbrixandersen** [zephyrproject-rtos/zephyr#76228]
**Describe the bug**
The USB device_next driver for the NXP IP3511 IP does not report start of frame (`UDC_EVT_SOF`) events.

**Expected behavior**
All USB device controller drivers should report Start of Frame (SoF) events.

**Impact**
Unable to create a hardware-agnostic application making use of SoF events (described further in https://github.com/zephyrproject-rtos/zephyr/pull/76073).

**Environment (please complete the following information):**
 - OS: Any
 - Toolchain: Any
 - Commit SHA: v3.7.0-rc3

**Comment by jfischer-no** [comment]
@MarkWangChinese can you please take a look, we would need it for v4.0.0. Would it require a HAL driver update?

**Comment by MarkWangChinese** [comment]
> @MarkWangChinese can you please take a look, we would need it for v4.0.0. Would it require a HAL driver update?

Hi @jfischer-no , OK, I will handle it.
