### ISSUE TITLE
Nominate Duy Nguyen as a collaborator 

### ISSUE THREAD

**Issue by duynguyenxa** [zephyrproject-rtos/zephyr#76220]
# Nomination
TSC Project Roles: Collaborator
GitHub Permission Level: Write

## GitHub User

Provide the following information about the GitHub user:

1. Full Name Duy Nguyen
1. GitHub username duynguyenxa
1. Organization (optional): Renesas 

## Supporting Documents
https://github.com/zephyrproject-rtos/zephyr/commits?author=duynguyenxa
https://github.com/zephyrproject-rtos/zephyr/pull/75498/files

**Comment by nashif** [comment]
done
