### ISSUE TITLE
drivers: usb: udc: udc_it82xx2 does not report UDC_EVT_SOF

### ISSUE THREAD

**Issue by henrikbrixandersen** [zephyrproject-rtos/zephyr#76225]
**Describe the bug**
The USB device_next driver for the ITE IT82XX2 does not report start of frame (`UDC_EVT_SOF`) events.

**Expected behavior**
All USB device controller drivers should report Start of Frame (SoF) events.

**Impact**
Unable to create a hardware-agnostic application making use of SoF events (described further in https://github.com/zephyrproject-rtos/zephyr/pull/76073).

**Environment (please complete the following information):**
 - OS: Any
 - Toolchain: Any
 - Commit SHA: v3.7.0-rc3

**Comment by jfischer-no** [comment]
@Chenhongren, can you please take a look, we would need it for v4.0.0.

**Comment by Chenhongren** [comment]
> @Chenhongren, can you please take a look, we would need it for v4.0.0.

We are working on this ([link](https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/5767074)). However, there are other urgent issues we need to address at the moment. We will come back and create a PR ASAP.
