### ISSUE TITLE
Zephyr version: 3.7.0-rc3 has error when building Lora sx1276

### ISSUE THREAD

**Issue by hongphucpolycrystech** [zephyrproject-rtos/zephyr#76249]
Zephyr version: 3.7.0-rc3
# From the root of the zephyr repository
west build -b nucleo_l073rz --shield semtech_sx1276mb1mas samples/subsys/lorawan/class_a

Has error
D:/2024/ZephyrWorkspace/zephyr/build/zephyr/zephyr.dts:497.10-504.5: Warning (simple_bus_reg): /soc/clocks: missing or empty reg/ranges property
warning: HAS_SEMTECH_SX1276 (defined at modules\loramac-node\Kconfig:19) has direct dependencies 0 with value n, but is currently being y-selected by the following symbols:
 - LORA_SX127X (defined at drivers/lora/Kconfig.sx12xx:7), with value y, direct dependencies (DT_HAS_SEMTECH_SX1272_ENABLED || DT_HAS_SEMTECH_SX1276_ENABLED) && SPI && LORA (value: y), and select condition DT_HAS_SEMTECH_SX1276_ENABLED && (DT_HAS_SEMTECH_SX1272_ENABLED || DT_HAS_SEMTECH_SX1276_ENABLED) && SPI && LORA (value: y)Parsing D:/2024/ZephyrWorkspace/zephyr/Kconfig
Loaded configuration 'D:/2024/ZephyrWorkspace/zephyr/boards/st/nucleo_l073rz/nucleo_l073rz_defconfig'
Merged configuration 'D:/2024/ZephyrWorkspace/zephyr/samples/subsys/lorawan/class_a/prj.conf'

**Comment by nordicjm** [comment]
Builds fine, you are likely missing the lora module from your custom manifest
