### ISSUE TITLE
RTIO: buffer `const` qualifiers for TX buffers

### ISSUE THREAD

**Issue by JordanYates** [zephyrproject-rtos/zephyr#76353]
**Is your enhancement proposal related to a problem? Please describe.**

It is quite common for higher level API's to define their TX buffers with `const` qualifers. For example:
```
int modem_pipe_transmit(struct modem_pipe *pipe, const uint8_t *buf, size_t size);
int flash_write(const struct device *dev, off_t offset, const void *data, size_t len);
int disk_access_write(const char *pdrv, const uint8_t *data_buf, uint32_t start_sector, uint32_t num_sector);
```
When implementing drivers for these API's using RTIO, users are forced to explicitly discard the `const` qualifiers due to the internal types of the RTIO interface and its underlying storage structure (`struct rtio_sqe`):
```
static inline void rtio_sqe_prep_write(
    struct rtio_sqe *sqe, const struct rtio_iodev *iodev, int8_t prio, uint8_t *buf, uint32_t len, void *userdata);
static inline void rtio_sqe_prep_transceive(
    struct rtio_sqe *sqe, const struct rtio_iodev *iodev, int8_t prio, uint8_t *tx_buf, uint8_t *rx_buf, uint32_t buf_len, void *userdata)
```

Apart from the added casting, there is also the loss of compiler checking that the buffer is indeed not modified.

**Describe the solution you'd like**

Proper `const` qualifiers on buffers marked for transmission.

**Comment by teburd** [comment]
We could make tx_buf const, that would be fine and likely add some minimal safety.
