### ISSUE TITLE
qemu_cortex_a53_smp board can not support `CONFIG_NO_OPTIMIZATIONS=y` config.

### ISSUE THREAD

**Issue by cocoeoli** [zephyrproject-rtos/zephyr#76362]
**Describe the bug**
When I enable the 'CONFIG_NO_OPTIMIZATIONS=y' option and run sample/synchronization, it can not work well(Just print two line and no ohter message):
![image](https://github.com/user-attachments/assets/6d70580f-77f8-4de9-b452-5ed87796cf83)

**To Reproduce**
1. Adding 'CONFIG_NO_OPTIMIZATIONS=y' to 'qemu_cortex_a53_qemu_cortex_a53_smp_defconfig';
2. west build -b qemu_cortex_a53_smp samples/synchronization/
3. west build -t run
4. See bug;

**Environment (please complete the following information):**

 - OS: 
![image](https://github.com/user-attachments/assets/c7da4460-fc84-4fa5-9d7e-43783359334b)

 - Zephyr Version and Toolchain:
![image](https://github.com/user-attachments/assets/f28868c6-0742-4fd4-afc8-8d90a79be40c)

**Comment by thedjnK** [comment]
Did you increase the stack sizes?

**Comment by cocoeoli** [comment]
> Did you increase the stack sizes?

No, the stack size is default value(4096). I try to increase it, but it still not wrok.

**Comment by jhedberg** [comment]
> > Did you increase the stack sizes?
> 
> No, the stack size is default value(4096). I try to increase it, but it still not wrok.

Which stack did you increase? There are probably several thread stacks that may need modification (e.g. system work queue, main, interrupt, etc)

**Comment by cfriedt** [comment]
@cocoeoli - have you tried debugging with gdb? It would be great if you could help pinpoint where the issue is. E.g. by providing a stack trace

**Comment by jhedberg** [comment]
In general, these stack size increase situations when disabling optimizations is something that we can't (and won't) fix upstream for all cases.

**Comment by cocoeoli** [comment]
> > > Did you increase the stack sizes?
> > 
> > 
> > No, the stack size is default value(4096). I try to increase it, but it still not wrok.
> 
> Which stack did you increase? There are probably several thread stacks that may need modification (e.g. system work queue, main, interrupt, etc)

The stack size I increased are below:
![image](https://github.com/user-attachments/assets/77c34277-b7f4-4544-90d2-fb8a103543bb)

**Comment by cocoeoli** [comment]
> @cocoeoli - have you tried debugging with gdb? It would be great if you could help pinpoint where the issue is. E.g. by providing a stack trace

I am trying to debug.

**Comment by cocoeoli** [comment]
> In general, these stack size increase situations when disabling optimizations is something that we can't (and won't) fix upstream for all cases.

Yes, I think some user cases may need disable optimizations.
