### ISSUE TITLE
lwm2m rd_client does not emit disconnect event

### ISSUE THREAD

**Issue by SebastianSchueller** [zephyrproject-rtos/zephyr#76422]
**Describe the bug**

Target Platform: nRF9160 based custom board

Calling `rd_client_stop()` with `deregister == true` does not emit a `LWM2M_RD_CLIENT_DISCONNECT` event when the rd client is in state `ENGINE_NETWORK_ERROR`, even if the network is available again at the time of calling.

We noticed this issue during field tests with a device that would sometimes get stuck when trying to gracefully shut down all network activity.
A graceful shutdown here means that the device first de-registers from the lwm2m server and then disconnects the mobile network.
The device was connected to the network via NB-IoT with fairly bad coverage. Shortly before they tried to shut down, the device lost connectivity for roughly one second.
Since the the network again at the time the shutdown had been issued, it tried to shut down the rd_client with a de-registration from the server.

**To Reproduce**
1. Build lwm2m client sample on board with manual control over network stack
2. Start system and wait for the lwm2m  client to be registered
3. Manually disable networking
4. Wait for lwm2m client to log a poll error
5. Manuall enable network again
6. Call `rd_client_stop(…,…,true)` _before_ the rd_client has recovered

**Expected behavior**

The rd_client always needs to somehow indicate that it is stopped after `rd_client_stop` has been called. 
Ideally the rd_client should be able leave the `ENGINE_NETWORK_ERROR` state as soon as the network is available again.
Alternatively it could emit an event when it enters this state allowing applications to track its internal state.

**Impact**

Since the application can't tell when the rd_client is stopped, it remains unresponsive until it's reset by a watchdog.

**Environment (please complete the following information):**

 - Zephyr version: 3.3

**Comment by SebastianSchueller** [comment]
> Wouldn't `LWM2M_RD_CLIENT_EVENT_DEREGISTER_FAILURE` be issued in such case instead? CC @SeppoTakalo

I don't think so. AFAICT the rd client only actually tries to de-register if `sm_is_registered()` returns true, which it doesn't in the case of `ENGINE_NETWORK_ERROR`.
I think the rd client just goes to idle state and waits to be restarted, it just doesn't emit an event that this happened.

**Comment by SeppoTakalo** [comment]
@SebastianSchueller I think this works like it is documented.
https://docs.zephyrproject.org/latest/connectivity/networking/api/lwm2m.html#lwm2m-engine-and-application-events

`NETWORK_ERROR` is the last event. It means that the engine has stopped. And its own state shows that it is not registered.
Therefore asking for de-registration does not do anything. Please see the table: https://docs.zephyrproject.org/latest/connectivity/networking/api/lwm2m.html#id4


Inside LwM2M engine, there is nothing that follows the network states. It should be done in application logic. Engine only uses one socket, and follows its state. CoAP timeouts, or socket failures causes it to drop the registration status, as there is no connection to server anymore.

So when application knows that network is dropped, it can pause the client. We do this on our nRF Connect SDK sample as it follows the LTE states: https://github.com/nrfconnect/sdk-nrf/blob/2ff9430caa1dcb226e6531f0f21fcba877e5cb27/samples/cellular/lwm2m_client/src/main.c#L552
And resumption is similar https://github.com/nrfconnect/sdk-nrf/blob/2ff9430caa1dcb226e6531f0f21fcba877e5cb27/samples/cellular/lwm2m_client/src/main.c#L699

**Comment by SebastianSchueller** [comment]
`NETWORK_ERROR` is never emitted, I think because the LwM2M client only emits it after `CONFIG_LWM2M_RD_CLIENT_MAX_RETRIES`.
So if the network recovers before all retries are exhausted, there is a time between the network recovery and the next LwM2M client retry in which the client presents itself as registered but is internally in `ENGINE_NETWORK_ERROR` state.


> So when application knows that network is dropped, it can pause the client. 
True, that might be a workaround. But this would also mean sending a registration update on any network issue, even if the LwM2M engine wouldn't notice it otherwise.

**Comment by SeppoTakalo** [comment]
Oh.. I see.

During the NETWORK_ERROR state, the DISCONNECTED event is not emitted if you call the `rd_client_stop()`.
I think this is a bug... I'll send a fix this this shortly.

**Comment by SebastianSchueller** [comment]
#76470 should fix this issue, and seems generally more robust, thanks! :)

But just out of interest: Why doesn't the LwM2M engine emit an event when it first enters `ENGINE_NETWORK_ERROR`?
This causes a very related issue, namely that `lwm2m_send_cb` calls

**Comment by SeppoTakalo** [comment]
> But just out of interest: Why doesn't the LwM2M engine emit an event when it first enters `ENGINE_NETWORK_ERROR`?

Because it tries to recover properly.
1. First it tries to update registration with current server
2. If it fails, it tries to re-register with current server (by establishing a new DTLS connection also)
3. If it fails, it drops the connection and tries if there is another server configured.
4. If it fails, it drops into the bootstrap mode (configurable on LwM2M 1.1)
5. Finally, if it cannot recover, it signals the application.

So the `NETWORK_ERROR` event is the last indication, that the engine cannot recover.
But already in phase 1, you should see `LWM2M_RD_CLIENT_EVENT_REG_TIMEOUT` event, or `LWM2M_RD_CLIENT_EVENT_REGISTRATION_FAILURE` (if server rejected, or socket failure)

On the case you have, have you seen these events?

**Comment by SeppoTakalo** [comment]
@SebastianSchueller Please see https://github.com/zephyrproject-rtos/zephyr/pull/65745 where the fallback mechanism was rewritten.

**Comment by SebastianSchueller** [comment]
No, none of these events have been emitted. In one case we observed, the last event from LwM2M was `LWM2M_RD_CLIENT_EVENT_REGISTRATION_COMPLETE`:
```
[03:08:59.693,389] <dbg> ct: log_lwm2m_rd_client_event: Registration complete
[03:08:59.693,542] <inf> net_lwm2m_rd_client: Registration Done (EP='wXFNAfYbts')
…
[03:09:23.932,922] <dbg> lte_lc: at_handler_cereg: +CEREG notification: +CEREG: 2
…
[03:09:24.564,849] <err> net_lwm2m_engine: Poll reported a socket error, 08.
[03:09:24.564,880] <err> net_lwm2m_rd_client: RD Client socket error: 5
…
[03:09:24.833,007] <err> net_lwm2m_engine: Cannot connect UDP (-114)
[03:09:24.833,251] <err> net_lwm2m_rd_client: Failed to start socket -114
…
[03:09:25.834,045] <err> net_lwm2m_engine: Cannot connect UDP (-114)
[03:09:25.834,228] <err> net_lwm2m_rd_client: Failed to start socket -114
…
[03:09:27.633,575] <dbg> lte_lc: at_handler_cereg: +CEREG notification: +CEREG: 5,"5808","0189BE00",7,0,2,"11100000","11100000"
…
[03:09:27.634,643] <err> app_lwm2m: Send error -1
```
I assume that the LwM2M client never actually got to try to fall back to anything, because once the network was available again, the LwM2M engine waited for the next re-try.

**Comment by SeppoTakalo** [comment]
Oh.. I see it now..

```
uart:~$ lwm2m update
[12:01:04.676,544] <dbg> app_lwm2m_client: rd_client_event: Registration update started
[12:01:05.763,336] <inf> net_lwm2m_rd_client: Update callback (code:2.4)
[12:01:05.763,397] <dbg> app_lwm2m_client: rd_client_event: Registration update complete
[12:01:05.763,519] <inf> net_lwm2m_rd_client: Update Done
uart:~$ lte offline
[12:01:09.890,777] <dbg> app_lwm2m_client: lwm2m_lte_reg_handler_notify: LTE NW status: 0
uart:~$ lwm2m send 3
[12:01:13.546,325] <inf> net_lwm2m_message_handling: Send op to server (/dp)
[12:01:13.555,694] <err> net_lwm2m_engine: Failed to send packet, err 114
[12:01:13.555,694] <err> net_lwm2m_engine: send() reported a socket error, 114
[12:01:13.555,725] <err> net_lwm2m_rd_client: RD Client socket error: 114
[12:01:13.562,988] <err> net_lwm2m_rd_client: sm_do_network_error, retries 5
uart:~$ lte normal
[12:01:17.130,401] <dbg> app_lwm2m_client: lwm2m_lte_reg_handler_notify: LTE NW status: 2
[12:01:17.734,252] <dbg> app_lwm2m_client: lwm2m_lte_reg_handler_notify: LTE NW status: 1
[12:01:29.563,812] <err> net_lwm2m_rd_client: sm_do_network_error, retries 5
[12:01:29.563,903] <err> net_lwm2m_rd_client: Network error, max retries reached (6)
[12:01:29.563,934] <err> net_lwm2m_obj_server: No server candidate found
[12:01:29.564,636] <inf> net_lwm2m_rd_client: Bootstrap started with endpoint 'urn:imei:358299840003962' using security object 0
[12:01:29.874,481] <inf> lwm2m_rai: RAI disabled
```

This case is possible when the device is not yet in queue mode and just tries `lwm2m_send()`, or as a result of `poll()` error.

I see two issues:
* retry counter was not reset to zero on last succesful update.
* socket_fail_cb() restarts the recovery logic, but when it calls `sm_handle_timeout_state()` it does not send any event because it was not a update or registration message that we sent.


I'll work on this for a while.
