### ISSUE TITLE
Nominate asm5878 as project contributor

### ISSUE THREAD

**Issue by erwango** [zephyrproject-rtos/zephyr#76467]
# Nomination

## GitHub User

Provide the following information about the GitHub user:

1. Full name: Alessandro-Salvatore Manganaro
1. Github account: @asm5878
1. Organization: STMicroelectronics

## Supporting Documents

@asm5878 is in charge of BLE support for STM32WB/WBA products.

See following contributions:
https://github.com/zephyrproject-rtos/zephyr/pull/75176
https://github.com/zephyrproject-rtos/zephyr/pull/75091
https://github.com/zephyrproject-rtos/zephyr/pull/73585

**Comment by nashif** [comment]
https://github.com/zephyrproject-rtos/zephyr/invitations
