### ISSUE TITLE
cbvprintf crashes on call to strlen for %s format argument with NULL value

### ISSUE THREAD

**Issue by devanl** [zephyrproject-rtos/zephyr#76509]
**Describe the bug**
While cbvprintf is processing format string, if it encounters a NULL argument for "%s" it will crash on strlen(). 

**To Reproduce**
Submit log message with "%s" of NULL value and apply post-formatting.

**Expected behavior**
Similar to "%p" behavior, could add "(nil)" to output, don't crash.

**Impact**
Medium

**Logs and console output**
N/A

**Environment (please complete the following information):**
Zephyr 3.0.0 on arm-m7

**Additional context**

**Comment by mmahadevan108** [comment]
Can you reproduce this with the latest Zephyr code.

**Comment by devanl** [comment]
Can we please remove the stale market on this?

**Comment by devanl** [comment]
> Can you reproduce this with the latest Zephyr code.

This was encountered with 3.4.0 but I can confirm that this same issue exists on the latest.
