### ISSUE TITLE
WiFi ESP_AT: SecureFault on WiFi Disconnects

### ISSUE THREAD

**Issue by ligogeorge** [zephyrproject-rtos/zephyr#76523]
**Describe the bug**

ESP_AT WiFi driver causing secure fault on WiFi disconnects. 
<img width="299" alt="image" src="https://github.com/user-attachments/assets/69db0def-ca32-4728-8ee1-1d14fbaa9bb0">

**To Reproduce**
1. Add ESP_AT WiFi driver with TFM enabled
2. Connect to WiFi
3. Perform a DNS Query
4. Disconnect WiFi

**Expected behavior**

WiFi disconnect should not cause any hard fault.
**Impact**

This causes unintentional reboots.
**Logs and console output**

- It is found that this is caused due to a null pointer access (0x0C).
![image](https://github.com/user-attachments/assets/ac523eec-8e72-4f7d-be82-774ed0618728)

- ESP AT driver is notifying zephyr network layer that the socket connection is closed with a NULL pointer.
![image](https://github.com/user-attachments/assets/7f21f34b-6302-4d4a-b49f-c35310985aaa)

- This NULL pointer is being used in the zehyr network layer without any checks.
![image](https://github.com/user-attachments/assets/dd3a0a56-3434-4ae8-837c-899c00285f0a)

- This causing SecureFault as the address 0x0C is under secure domain now.

**Environment (please complete the following information):**

 - Using nRF SDK v2.6.1

**Additional context**

**Comment by rftafas** [comment]
> Environment (please complete the following information):
> 
> -  Using nRF SDK v2.6.1
> 

Maybe this should be _plaftorm: nRF_.

**Comment by ligogeorge** [comment]
nRF SDK 2.6.1 implies corresponding Zephyr version 3.6.x. 

It looks like this fault is not happening on Zephyr 3.7.0, but ESP AT code looks same, probably Zephyr layers handling it.

**Comment by rftafas** [comment]
ESP-AT runs ESP-IDF and it is not related to Platform:ESP32 (which is Zephyr on ESP32). This gets the right eyes with the right label.

**Comment by mmahadevan108** [comment]
@ligogeorge, is this issue seen with the latest Zephyr [main](https://github.com/zephyrproject-rtos/zephyr/commits/main/)

**Comment by ligogeorge** [comment]
No, i didn't faced this issue in the next revision.
