### ISSUE TITLE
Bug in STM32 Disco L475 Arduino I2C header

### ISSUE THREAD

**Issue by kartben** [zephyrproject-rtos/zephyr#76549]
**Describe the bug**

disco l475 board exposes I2C3 on standard Arduino Uno pins A4/A5, but the DTS file exposes I2C1 instead.

**To Reproduce**

**Environment (please complete the following information):**

 - OS: all
 - Toolchain (e.g Zephyr SDK, ...) 0.16.8
 - Commit SHA or Version used v3.6.0

**Additional context**

**Comment by erwango** [comment]
PR Merged (https://github.com/zephyrproject-rtos/zephyr/pull/76497)
