### ISSUE TITLE
Documentation: Default way of denoting Kconfig requirements

### ISSUE THREAD

**Issue by Thalley** [zephyrproject-rtos/zephyr#76578]
**Is your enhancement proposal related to a problem? Please describe.**
Several functions and occasionally entire APIs have dependencies on specific Kconfig options. Several, but probably not the majority, of these add text like `Requires that @kconfig{CONFIG_BT_CONN} is enabled.` to denote that the function/API is guarded by a Kconfig option, and failing to enable this Kconfig option will result in linker errors. 

**Describe the solution you'd like**
The request is to have a generic and standard way of denoting a Kconfig requirement so that the function/API can omit e.g. `Requires that @kconfig{CONFIG_BT_CONN} is enabled.` and e.g. just have `@req_kconfig{CONFIG_BT_CONN}` or `@kconfig_req{CONFIG_BT_CONN}`. 

Adding such as requirement should add some default text or possibly also specific formatting so that's obvious from the documentation that there is a conditional requirement for the function. 

**Describe alternatives you've considered**
The issue is primarily for Kconfig options, but may extend to other values as well, although I am unaware of any such examples. 

**Additional context**
N/A

**Comment by kartben** [comment]
Hi @Thalley -- I am about to send a PR proposing a fix, can you point me to an API where this would apply and that I can use as a demonstrator?
