### ISSUE TITLE
[NRFX-6220] Test

### ISSUE THREAD

**Issue by nordic-piks** [zephyrproject-rtos/zephyr#76634]
Jira: NRFX-6220

Ref: NRFX-6220

**Comment by nordicjm** [comment]
Not sure the relevance of this to zephyr? If you want to test something can you use https://github.com/zephyrproject-rtos/zephyr-testing ?

**Comment by nordic-piks** [comment]
> Not sure the relevance of this to zephyr? If you want to test something can you use https://github.com/zephyrproject-rtos/zephyr-testing ?

Thanks, I will clean this and try in testing space :)
