### ISSUE TITLE
doc: Documentation issue in 'kernel/services/polling'

### ISSUE THREAD

**Issue by clamattia** [zephyrproject-rtos/zephyr#76685]
**Describe the bug**

The documentation is misleading. It reads :  "... it is possible for more than one to be fulfilled when k_poll() returns, ..."
But the example is not implemented accordingly:
```C
void do_stuff(void)
{
    for(;;) {
        rc = k_poll(events, ARRAY_SIZE(events), K_FOREVER);
        if (events[0].state == K_POLL_STATE_SEM_AVAILABLE) {
            k_sem_take(events[0].sem, 0);
        } else if (events[1].state == K_POLL_STATE_FIFO_DATA_AVAILABLE) {
            data = k_fifo_get(events[1].fifo, 0);
            // handle data
        } else if (events[2].state == K_POLL_STATE_MSGQ_DATA_AVAILABLE) {
            ret = k_msgq_get(events[2].msgq, buf, K_NO_WAIT);
            // handle data
        } else if (events[3].state == K_POLL_STATE_PIPE_DATA_AVAILABLE) {
            ret = k_pipe_get(events[3].pipe, buf, bytes_to_read, &bytes_read, min_xfer, K_NO_WAIT);
            // handle data
        }
        events[0].state = K_POLL_STATE_NOT_READY;
        events[1].state = K_POLL_STATE_NOT_READY;
        events[2].state = K_POLL_STATE_NOT_READY;
        events[3].state = K_POLL_STATE_NOT_READY;
    }
}
```

The `if`-`else`-chain encodes the assumption, that only one event can be active at a time and then all states are reset. If an event lower in the if else chain is active at the same time with another, then it is never handled and the state reset nonetheless.

Suggestion: Adjust ALL examples accordingly and add a note, why it is not an `if`-`else`-chain:

```C
void do_stuff(void)
{
    for(;;) {
        rc = k_poll(events, ARRAY_SIZE(events), K_FOREVER);
        if (events[0].state == K_POLL_STATE_SEM_AVAILABLE) {
            k_sem_take(events[0].sem, 0);
        }
        if (events[1].state == K_POLL_STATE_FIFO_DATA_AVAILABLE) {
            data = k_fifo_get(events[1].fifo, 0);
            // handle data
        }
        if (events[2].state == K_POLL_STATE_MSGQ_DATA_AVAILABLE) {
            ret = k_msgq_get(events[2].msgq, buf, K_NO_WAIT);
            // handle data
        }
        if (events[3].state == K_POLL_STATE_PIPE_DATA_AVAILABLE) {
            ret = k_pipe_get(events[3].pipe, buf, bytes_to_read, &bytes_read, min_xfer, K_NO_WAIT);
            // handle data
        }
        events[0].state = K_POLL_STATE_NOT_READY;
        events[1].state = K_POLL_STATE_NOT_READY;
        events[2].state = K_POLL_STATE_NOT_READY;
        events[3].state = K_POLL_STATE_NOT_READY;
    }
}
```

**Environment**

* Page: `kernel/services/polling`
* Version: main
* SHA-1: 0e830b3f100d1a1e768857450ada8be0db5a7634

**Comment by andyross** [comment]
Those two examples are semantically equivalent.  It's a loop: if the first if/else chain has two events flagged, it will return synchronously from the next k_poll() call and see it the second time around.  It's idiomatic enough and I wouldn't reject submitted code that worked like this.  In practice truly simultaneous events are rare and apps that care about precedence between them in this way are probably hiding bugs.

That said, I agree that as **documentation** it's not clearly showing the documented/tested behavior of the call, so the suggested change would make sense to me.

**Comment by henrikbrixandersen** [comment]
@clamattia Coule you submit a PR for updating the documentation?

**Comment by clamattia** [comment]
> Those two examples are semantically equivalent. It's a loop: if the first if/else chain has two events flagged, it will return synchronously from the next k_poll() call

I am not so familiar with the code, so bare with me. But, would not the reseting of the state: 
```C
        events[0].state = K_POLL_STATE_NOT_READY;
        events[1].state = K_POLL_STATE_NOT_READY;
        events[2].state = K_POLL_STATE_NOT_READY;
        events[3].state = K_POLL_STATE_NOT_READY;
```
avoid the synchronous return from the next `k_poll`-call? If not, how is the kernel supposed to know wether a poll-event was handled or not? So if lets say `events[0]` and `events[1]` were active at the same time, only `event[0]` will be handled but both their `state` will be set to `K_POLL_STATE_NOT_READY` before the next call to `k_poll`. If, as you say, the next call to `k_poll` will return immediately with `events[1]`, how can they know, that we handled `events[0]` but not `events[1]`, as both their `state` was reset?

I would have thought, that the behavior you describe is only possible if the code looks like this, which would probably be fine too (personally, I prefer original proposal):
```C
void do_stuff(void)
{
    for(;;) {
        rc = k_poll(events, ARRAY_SIZE(events), K_FOREVER);
        if (events[0].state == K_POLL_STATE_SEM_AVAILABLE) {
            k_sem_take(events[0].sem, 0);
            events[0].state = K_POLL_STATE_NOT_READY;
        } else if (events[1].state == K_POLL_STATE_FIFO_DATA_AVAILABLE) {
            data = k_fifo_get(events[1].fifo, 0);
            // handle data
            events[1].state = K_POLL_STATE_NOT_READY;
        } else if (events[2].state == K_POLL_STATE_MSGQ_DATA_AVAILABLE) {
            ret = k_msgq_get(events[2].msgq, buf, K_NO_WAIT);
            // handle data
            events[2].state = K_POLL_STATE_NOT_READY;
        } else if (events[3].state == K_POLL_STATE_PIPE_DATA_AVAILABLE) {
            ret = k_pipe_get(events[3].pipe, buf, bytes_to_read, &bytes_read, min_xfer, K_NO_WAIT);
            // handle data
            events[3].state = K_POLL_STATE_NOT_READY;
        }
    }
}
```


> . In practice truly simultaneous events are rare and apps that care about precedence between them in this way are probably hiding bugs.

Agree, but as most developers will take the example code as their starting point, a lot of apps will have bugs (rarely dropping events) in this way.


> @clamattia Coule you submit a PR for updating the documentation?

Will try.

**Comment by clamattia** [comment]
> Those two examples are semantically equivalent.

I mean to say, to my current understanding (maybe wrong), they are not equivalent as one potentially drops events and the other does not.
