### ISSUE TITLE
Nominate zkat2 as Contributor

### ISSUE THREAD

**Issue by zkat2** [zephyrproject-rtos/zephyr#76722]
# Nomination

## GitHub User

Provide the following information about the GitHub user:

1. Full Name
Zoe Kaute
1. GitHub username
Zkat2
1. Organization (optional)

## Supporting Documents

https://github.com/zephyrproject-rtos/zephyr/pull/74977

[TSC Project Roles]: <https://docs.zephyrproject.org/latest/project/project_roles.html>
[GitHub Permission Level]: <https://docs.github.com/en/organizations/managing-access-to-your-organizations-repositories/repository-roles-for-an-organization>

**Comment by nashif** [comment]
https://github.com/zephyrproject-rtos/zephyr/invitations
