### ISSUE TITLE
doc: Documentation issue in 'services/pm/device_runtime'

### ISSUE THREAD

**Issue by colincina** [zephyrproject-rtos/zephyr#76741]
**Describe the bug**

device_pm_action callback example 

The example code of the callback takes a pointer on a pm_device_action enum element but the switch case does not dereference the pointer for the evaluation.  Could this be a mistake on your part? 
This leads to compiler errors of type: "expression must have integral type"

**Environment**

* Page: `services/pm/device_runtime`
* Version: main
* SHA-1: b4d3f47466f07379614a7a761e00d868635a96d0

**Comment by ceolin** [comment]
Fixed in #76836
