### ISSUE TITLE
http1 dynamic post request response doesn't send header a second time

### ISSUE THREAD

**Issue by LukasTaroza** [zephyrproject-rtos/zephyr#76776]
I am using sample http_server and found that if I post to a URL with dynamic context, the first time I get a packet with a header and if I post again without waiting for client timeout, I don't get a header.

Log with additional messages added to show what header is sent:
![image](https://github.com/user-attachments/assets/9f07319b-b9cd-4010-8a8a-0c66291941ad)

I've added a line client->http1_header_sent = false when status is HTTP_SERVER_DATA_FINAL to fix the issue, but I don't think that is a good fix.

I am using zephyr commit 5305aa615b0f800508e253c3398712eca1b209b4

**Comment by rlubos** [comment]
Thanks for the report, I've managed to reproduce the issue. I'll send a fix shortly.

**Comment by rlubos** [comment]
@LukasTaroza https://github.com/zephyrproject-rtos/zephyr/pull/76845

**Comment by LukasTaroza** [comment]
Thank you, the fix now sends a header on every request.
