### ISSUE TITLE
Multiple tests/drivers/uart fails on nrf54h20

### ISSUE THREAD

**Issue by nordic-krch** [zephyrproject-rtos/zephyr#76830]
**Describe the bug**

#75451 introduced new device tree property (`nordic,clock-enable`) and overlays for uart tests were not updated and they are failing for nrf54h20dk (cpuapp and cpurad):
- tests/drivers/uart/uart_mix_fifo_poll
- tests/dirvers/uart/uart_async_api
- tests/drivers/uart/uart_pm
- tests/drivers/uart/uart_elementary

**To Reproduce**

1. Run twister on nrf54h20dk/nrf54h20/cpuapp or nrf54h20dk/nrf54h20/cpurad for `tests/drivers/uart`
2. See error

**Expected behavior**

Tests shall pass.

**Environment (please complete the following information):**

 - Commit SHA: 3240b034fee

**Comment by nordic-piks** [comment]
tests/drivers/spi/spi_controller_peripheral/drivers.spi.spi_fast is affected too
