### ISSUE TITLE
stm32: hal: ospi: dma read not working

### ISSUE THREAD

**Issue by sageve** [zephyrproject-rtos/zephyr#76834]
There is an bug in the ospi hal that was fixed 3 month ago:

https://github.com/STMicroelectronics/stm32h7xx_hal_driver/commit/cff8a947c901b8db3f94f731e3aef516c7c60d8b

Please update the stm32cube h7 hal.

**Comment by FRASTM** [comment]
Correct, stm32H7 drivers latest version is  V1.11.3 / 15-March-2024
