### ISSUE TITLE
Bluetooth logging Kconfig options are unconditionally always enabled

### ISSUE THREAD

**Issue by jhedberg** [zephyrproject-rtos/zephyr#76863]
**Describe the bug**

We have a single `subsys/bluetooth/Kconfig.logging` file that defines all Bluetooth logging Kconfig options. This is not a problem as such, except that there are no other conditions required besides `CONFIG_BT=y` for all of these options becoming enabled. That means that even the simplest Bluetooth application will cause "Kconfig symbol polution" in `build/zephyr/.config`.

**To Reproduce**

```shell
❯ west build -b qemu_x86 samples/bluetooth/beacon
❯ grep ^CONFIG_BT_.\*LOG_LEVEL build/zephyr/.config|wc -l
     172
```

**Expected behavior**

Only logging options for Bluetooth features which were actually enabled are visible in the build.

**Impact**

Unnecessary Kconfig symbol polution in the build.

**Possible solutions**

Either our `Kconfig.logging` should get `if BT_FOO` style blocks for each logging symbol, or then the definitions of these should move into the respective Kconfig files where the features are defined. The latter could mean that the centralized `Kconfig.logging` completely goes away.

**Comment by jori-nordic** [comment]
Bluetooth WG: 
Do it in steps:
- add an `if` block around each feature in the global logging file
- move the log kconfigs into their corresponding module Kconfig
  - might be worse UX. User usually wants logging, but doesn't know which ones.
