### ISSUE TITLE
Add Espressif Collaborators

### ISSUE THREAD

**Issue by sylvioalves** [zephyrproject-rtos/zephyr#77121]
# Background

The [TSC Project Roles] defines the main roles for the Zephyr Project, including
Maintainer, Collaborator, and Contributor.

By default anyone that contributes code or documentation is a Contributor, but
with the lowest [GitHub Permission Level] of Read. For example, Contributors
with Read permission do not have the permission to add reviewers to a pull
request.

Use this template to nominate a GitHub user for the Contributor role with
Triage permission level, which allows the user to add reviewers to a pull
request and be added as a reviewer by other users.

# Nomination

## GitHub User

Provide the following information about the GitHub user:

1. Raffael Rostagno
2. raffarost
3. Espressif Systems

## Supporting Documents
https://github.com/zephyrproject-rtos/zephyr/pull/71165
https://github.com/zephyrproject-rtos/zephyr/pull/72427
https://github.com/zephyrproject-rtos/zephyr/pull/75379

1. Márcio Ribeiro
2. wmrsouza
3. Espressif Systems

## Supporting Documents
https://github.com/zephyrproject-rtos/zephyr/pull/64931
https://github.com/zephyrproject-rtos/zephyr/pull/65970
https://github.com/zephyrproject-rtos/zephyr/pull/73228

**Comment by kartben** [comment]
+1 🥳
