### ISSUE TITLE
ESP32C3: Inconsistent flash erase times in ESP32-C3-MINI-1 (ESP32-C3FN4) modules [zephyr-v3.6.99]

### ISSUE THREAD

**Issue by abdulble** [zephyrproject-rtos/zephyr#77169]
**Describe the bug**
There is a consistent variation in the time it takes to erase flash across different ESP32-C3-MINI-1 (ESP32-C3FN4) modules. THe variation has been measured to be between 3.5 and 5 seconds so far, in 5 samples.

This was discovered by measuring the time needed to erase 1MB of flash (update partition) in multiple development kits (all `esp32c3_devkitm1` boards). The erase time is similar (±1% deviation) for each individual module but differs significantly (~±18% deviation) across different modules of the same part number.

**To Reproduce**

- Use the ESP32-C3-DevKitM-1 with the ESP32-C3-MINI-1 (ESP32-C3FN4) module.
- Erase 1MB of flash (e.g. secondary slot) in either the Espressif port of MCUboot or a Zephyr application.
- Measure the time taken to erase using either:
  - Immediate logs from the debug UART (for testing in MCUboot).
  - Deferred logs with timestamps (for testing in Zephyr application).
  
Code snippet to erase flash in a Zephyr application (same can be modified for MCUboot):
```
#define IMAGE_INDEX_0   0
#define SECONDARY_SLOT  1
// CONFIG_ESP_IMAGE0_SECONDARY_START_ADDRESS 0x110000
// CONFIG_ESP_APPLICATION_SIZE 0x100000

static int test_erasing_flash_slot1(void){
    int rc;
    int area_id;
    const struct flash_area* fa;

    area_id = flash_area_id_from_multi_image_slot(IMAGE_INDEX_0, SECONDARY_SLOT);
    rc = flash_area_open(area_id, &fa);
    if (rc) {
        LOG_ERR("flash_area_open failed with %d", rc);
        return rc;
    }

    LOG_DBG("[test] erasing flash - slot %d, area_id: %d, start=0x%x, size=0x%x", SECONDARY_SLOT, area_id, CONFIG_ESP_IMAGE0_SECONDARY_START_ADDRESS, CONFIG_ESP_APPLICATION_SIZE);    
    
    rc = flash_area_erase(fa, CONFIG_ESP_IMAGE0_SECONDARY_START_ADDRESS, CONFIG_ESP_APPLICATION_SIZE);
    if (rc){
        LOG_ERR("[test] flash_area_erase failed with %d", rc);
        return rc;
    }

    LOG_DBG("[test]  erased flash - slot %d, area_id: %d, start=0x%x, size=0x%x", SECONDARY_SLOT, area_id, CONFIG_ESP_IMAGE0_SECONDARY_START_ADDRESS, CONFIG_ESP_APPLICATION_SIZE);

    flash_area_close(fa);
    return rc;
}
```

**Expected behavior**
Flash erase times should be consistent across different ESP32-C3 modules of the same type.

**Impact**
This issue could lead to performance unpredictability and timing inconsistencies when in production devices.

**Logs and console output**
Example log for the module with shortest average erase time (± 1% deviation in 10 tests)  **[3.528 seconds]**:
```
[00:00:17.435,000] <dbg> [test] erasing flash - slot 1, area_id: 2, start=0x110000, size=0x100000
[00:00:20.963,000] <dbg> [test]  erased flash - slot 1, area_id: 2, start=0x110000, size=0x100000
```

Example log for the module with longest average erase time (± 1% deviation in 10 tests) **[5.050 seconds]**:
```
[00:00:31.326,000] <dbg> [test] erasing flash - slot 1, area_id: 2, start=0x110000, size=0x100000
[00:00:36.376,000] <dbg> [test]  erased flash - slot 1, area_id: 2, start=0x110000, size=0x100000
```

Details on the flash according to `esptool.py flash_id`: 
```
Detecting chip type... ESP32-C3
Chip is ESP32-C3 (QFN32) (revision v0.4)
Features: WiFi, BLE, Embedded Flash 4MB (XMC)
Crystal is 40MHz
MAC: c0:4e:30:ef:44:f4
Uploading stub...
Running stub...
Stub running...
Manufacturer: 20
Device: 4016
Detected flash size: 4MB
Hard resetting via RTS pin...
```

**Environment**
- Devcontainer based on image: zephyrprojectrtos/zephyr-build:v0.26.11
- Toolchain: Zephyr SDK 0.16.5-1
- Zephyr branch: zephyr-v3.6.99 @ hal_v5.1 merge [[revision](https://github.com/zephyrproject-rtos/zephyr/commit/46a0a72be855e34bbee8f86d79aac2c91c0ba207)]
- Target: `esp32c3_devkitm`

**Comment by Shreeyash-17** [comment]
@abdulble can you help me to how to run esp32 on zephyr from scratch?

**Comment by rftafas** [comment]
> @abdulble could you please help me to how to run esp32 on zephyr from scratch?

@Shreeyash-17 this seems off-topic. For the sake of a reply, start with https://docs.zephyrproject.org/latest/develop/getting_started/index.html

This issue can be closed, as the reported problem is within component parameter range even though not close to typical values.

**Comment by abdulble** [comment]
@sylvioalves Thank you for the detailed explanation. 
@rftafas Alright I will close the issue.
