### ISSUE TITLE
off-by-one error on month counting in rtc rv8263 driver

### ISSUE THREAD

**Issue by jakubtopic** [zephyrproject-rtos/zephyr#77189]
**Describe the bug**
I assume there is an error in how the month field is handled within the `rv8263` driver. `tm_mon` in `rtc_time` structure has a range [0, 11], while the RTC expects [1, 12]. The current implementation does not increase/decrease the value by one when setting or getting the time.

**Expected behavior**
The driver should adjust the `tm_mon` value to match the RTC hardware's range.

**Comment by jakubtopic** [comment]
@Kampi could you take a look, please?

**Comment by Kampi** [comment]
You´re right. It´s different from other RTCs.
