### ISSUE TITLE
[Coverity CID :186049] Memory - corruptions in /samples/subsys/mgmt/mcumgr/smp_svr/src/main.c

### ISSUE THREAD

**Issue by mandarcthorat1** [zephyrproject-rtos/zephyr#7722]
Static code scan issues seen in File: /samples/subsys/mgmt/mcumgr/smp_svr/src/main.c
 Category: Memory - corruptions
 Function: main
 Component: Samples
 CID: 186049
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by carlescufi** [comment]
@nvlsianpu can you please take a look at this one?

**Comment by nvlsianpu** [comment]
sure

**Comment by nvlsianpu** [comment]
issue is false positive - memory corruption doesn't happen - just function for clearing the statistic data (`void
stats_reset(struct stats_hdr *hdr)`) doesn't know the peculiar structure of  statistic group (and can not know as the function is generic).

**Comment by lpereira** [comment]
Closing as false positive.  Marked the issue in Coverity as such as well.
