### ISSUE TITLE
Nominate myself as contributor

### ISSUE THREAD

**Issue by LaurentiuM1234** [zephyrproject-rtos/zephyr#77243]
# Background

The [TSC Project Roles] defines the main roles for the Zephyr Project, including
Maintainer, Collaborator, and Contributor.

By default anyone that contributes code or documentation is a Contributor, but
with the lowest [GitHub Permission Level] of Read. For example, Contributors
with Read permission do not have the permission to add reviewers to a pull
request.

Use this template to nominate a GitHub user for the Contributor role with
Triage permission level, which allows the user to add reviewers to a pull
request and be added as a reviewer by other users.

# Nomination

## GitHub User

Provide the following information about the GitHub user:

1. Full Name: Laurentiu Mihalcea
1. GitHub username: LaurentiuM1234 
1. Organization (optional): NXP

## Supporting Documents

https://github.com/zephyrproject-rtos/zephyr/pull/75102
https://github.com/zephyrproject-rtos/zephyr/pull/72791
https://github.com/zephyrproject-rtos/zephyr/pull/71535
https://github.com/zephyrproject-rtos/zephyr/pull/71482
https://github.com/zephyrproject-rtos/zephyr/pull/71340

**Comment by nashif** [comment]
https://github.com/zephyrproject-rtos/zephyr/invitations
