### ISSUE TITLE
[Coverity CID :186042] Program hangs in /tests/posix/mutex/src/posix_mutex.c

### ISSUE THREAD

**Issue by mandarcthorat1** [zephyrproject-rtos/zephyr#7729]
Static code scan issues seen in File: /tests/posix/mutex/src/posix_mutex.c
 Category: Program hangs
 Function: recursive_mutex_entry
 Component: Tests
 CID: 186042
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by punitvara** [comment]
This is intentional to lock mutex twice to check recursive functionality of mutex.
