### ISSUE TITLE
doc: Documentation issue in 'samples/drivers/i2c/custom_target/README'

### ISSUE THREAD

**Issue by ypearson-bdai** [zephyrproject-rtos/zephyr#77294]
**Describe the bug**

old
`west build -b lpcxpresso55s69/lpc55s69/cpu0 samples/drivers/i2c_target`

new
`west build -b lpcxpresso55s69/lpc55s69/cpu0 samples/drivers/i2c/custom_target/`

<< Please describe the issue here >>
<< You may also want to update the automatically generated issue title above. >>

**Environment**

* Page: `samples/drivers/i2c/custom_target/README`
* Version: main
* SHA-1: 00ffad91027873d8edbfb3bbef1706c8a86e0144

**Comment by dkalowsk** [comment]
@ypearson-bdai can you open PR for this?
