### ISSUE TITLE
net: socket: recvmsg() doesn't update msg_controllen accordingly

### ISSUE THREAD

**Issue by axelnxp** [zephyrproject-rtos/zephyr#77303]
**Describe the bug**

The bug is exactly the same than it was with #68352.
This was fixed at the time, but I think the changes from #73713 introduced the regression.
`msg_controllen` is still set to the initial length, while `csmg_len` is set to 0.

If I bypass this added code, I don't reproduce the issue.

Maybe the problem comes from `add_timestamping` ? Does it update the `csmg_len` accordingly (if applicable) ?

**To Reproduce**
One can reuse the matter function where the issue is observed:
https://github.com/project-chip/connectedhomeip/blob/master/src/inet/UDPEndPointImplSockets.cpp#L611
And make sure no control data is received.

**Expected behavior**
`msg_controllen` field shall be updated by `recvmsg` according to the control data received.

**Impact**
Impact is high, in the current state, any Matter application over Zephyr would be impacted, likely unable to even perform a commissioning.

**Comment by axelnxp** [comment]
cc @jukkar

**Comment by jukkar** [comment]
Cc: @awojasinski please take a look, seems to be related to the ptp pr

**Comment by axelnxp** [comment]
I've been able to get more info on the root cause.
In my case, `add_timestamping` returns `-ENOTSUP` because `net_context_get_option` sets `timestamping` to 0.
In this case, `csmg_len` is not updated, so `msg_controllen` should be cleared, as no pkt info has been added.

So the problem comes from the `clear_controllen` logic.

**Comment by jukkar** [comment]
@axelnxp looks good, please send a PR for it.

**Comment by axelnxp** [comment]
@jukkar done, refer to #77345
