### ISSUE TITLE
Problem with newly introduced feature regarding pytest-args

### ISSUE THREAD

**Issue by KamilxPaszkiet** [zephyrproject-rtos/zephyr#77319]
PR [75893](https://github.com/zephyrproject-rtos/zephyr/pull/75893) introduced a change that allows variables to be added to pytest-args. Unfortunately, this broke our test with the logic analyzer. Twister now added data twice. This should not happen. It should find certain variables if they already exist and overwrite them. Unfortunately in this case this data from testcase.ymal is loaded into saleae_logic2, and those given as a parameter are ignored.

example command:
```
twister --device-testing --hardware-map ./map.yml -s tests/kernel/timer/timer_behavior/kernel.timer.timer_behavior_external -vv -X gpio_timerout --pytest-args='--tool='saleae_logic2'' --pytest-args="--tool-options=address=127.0.0.1,port=10430,channel=1,sample-rate=8_000_000,threshold-volts=0.0"
```
log fragment:
_in our case we change sample rate and threshold_
```
'--device-product=DAPLink CMSIS-DAP' --twister-fixture=gpio_timerout --tool=saleae_logic2 --tool-options=address=127.0.0.1,port=10430,channel=1,sample-rate=8_000_000,threshold-volts=0.0 --tool saleae_logic2 --tool-options address=127.0.0.1,port=10430,channel=1,sample-rate=6_250_000,threshold-volts=3.3 -p twister_harness.plugin
```

**Comment by gchwier** [comment]
Added fix to add pytest-args from command line as the last arguments. `argparse` takes the last one, so args from command line will be considered.
However, still all parameters will be provided to pytest command. I don't know, if adding extra logic to remove duplicated parameters is the right approach, you can extend your tests with parameters with `nargs+`, where more input is allowed, then adding the same parameter is ok (like `--verbose`).
