### ISSUE TITLE
[Coverity CID :186039] Control flow issues in /subsys/net/ip/connection.c

### ISSUE THREAD

**Issue by mandarcthorat1** [zephyrproject-rtos/zephyr#7732]
Static code scan issues seen in File: /subsys/net/ip/connection.c
 Category: Control flow issues
 Function: is_invalid_packet
 Component: Networking
 CID: 186039
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by jukkar** [comment]
Already fixed by commit 4dd5867a79b8919c89e1f19544480446af51d6d8
