### ISSUE TITLE
[Coverity CID :186034] Memory - corruptions in /tests/net/udp/src/main.c

### ISSUE THREAD

**Issue by mandarcthorat1** [zephyrproject-rtos/zephyr#7736]
Static code scan issues seen in File: /tests/net/udp/src/main.c
 Category: Memory - corruptions
 Function: test_udp
 Component: Tests
 CID: 186034
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by jukkar** [comment]
False positive
