### ISSUE TITLE
[Coverity CID :186033] Control flow issues in /subsys/mgmt/smp.c

### ISSUE THREAD

**Issue by mandarcthorat1** [zephyrproject-rtos/zephyr#7737]
Static code scan issues seen in File: /subsys/mgmt/smp.c
 Category: Control flow issues
 Function: zephyr_smp_write_at
 Component: Other
 CID: 186033
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by jhedberg** [comment]
@nashif why did you assign this to me? I'm not at all familiar with this code.

**Comment by nashif** [comment]
![image](https://user-images.githubusercontent.com/180017/40934991-aec9f9c8-6804-11e8-9526-5d119f9ba329.png)
