### ISSUE TITLE
unittest: add example for unittest in downstream tree to example-application

### ISSUE THREAD

**Issue by helo9** [zephyrproject-rtos/zephyr#77385]
**Is your enhancement proposal related to a problem? Please describe.**

I have issues creating unit-tests for a library in downstream tree.

**Describe the solution you'd like**

If possible, adding a unit test for the library in https://github.com/zephyrproject-rtos/example-application would be awesome.

**Describe alternatives you've considered**

Don't do it.

**Additional context**

**Comment by henrikbrixandersen** [comment]
Feel free to open a pull request for adding this in https://github.com/zephyrproject-rtos/example-application - the enhancement issue doesn't really belong in this repository.
