### ISSUE TITLE
[Coverity CID :186030] Error handling issues in /subsys/bluetooth/host/settings.c

### ISSUE THREAD

**Issue by mandarcthorat1** [zephyrproject-rtos/zephyr#7739]
Static code scan issues seen in File: /subsys/bluetooth/host/settings.c
 Category: Error handling issues
 Function: set
 Component: Bluetooth
 CID: 186030
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by nashif** [comment]
@jhedberg how about this one?

![image](https://user-images.githubusercontent.com/180017/40935067-e8bf55c4-6804-11e8-9012-8f2017c5cb3b.png)

**Comment by jhedberg** [comment]
> @jhedberg how about this one?

@nashif looks real enough. PR opened for it.
