### ISSUE TITLE
ci: missing kernel  MBEDTLS_ENTROPY_ENABLED symbol break CI

### ISSUE THREAD

**Issue by avolkov-1221** [zephyrproject-rtos/zephyr#77518]
**Describe the bug**

Hello

The latest merged mbestls related PR break the CI on unrelated projects due to bugs in some Kconfig(s).
Particularly my PR stop building due to missing  MBEDTLS_ENTROPY_ENABLED symbol (while it's not used mbedTLS at all).

**To Reproduce**

Just activate the CI build.

**Expected behavior**

**Impact**

**Logs and console output**

The output of broken CI can be found here:
https://github.com/zephyrproject-rtos/zephyr/actions/runs/10539828148/job/29203831920

**Environment (please complete the following information):**

 - OS: (e.g. Linux, MacOS, Windows)
 - Toolchain (e.g Zephyr SDK, ...)
 - Commit SHA or Version used

**Additional context**

**Comment by henrikbrixandersen** [comment]
Should be fixed by https://github.com/zephyrproject-rtos/zephyr/pull/77517
