### ISSUE TITLE
Nominate myself as Contributor 

### ISSUE THREAD

**Issue by avolkov-1221** [zephyrproject-rtos/zephyr#77528]
# Nomination

## GitHub User

Provide the following information about the GitHub user:

1. Full Name: 
    Andrey Volkov
1. GitHub username
   avolkov-1221
1. Organization (optional)
   MUNIC SA
## Supporting Documents
https://github.com/zephyrproject-rtos/zephyr/pull/75695
https://github.com/zephyrproject-rtos/zephyr/pull/56295

**Comment by nashif** [comment]
Thank you for your contribution to the Zephyr project. 

An invite was sent to you to join the project. You can find the invite here: https://github.com/zephyrproject-rtos/zephyr/invitations.

Note that further access and permissoins to the project will be provided following the project [guidelines](https://docs.zephyrproject.org/latest/project/project_roles.html#tsc-project-roles).
