### ISSUE TITLE
doc: Documentation issue in 'samples/sensor/lsm6dso/README'

### ISSUE THREAD

**Issue by MichalBiolik** [zephyrproject-rtos/zephyr#77537]
**Describe the bug**

Is:
`This project outputs sensor data to the console. It requires an LSM6DSO sensor, which is present on the [ST STM32L562E-DK Discovery](https://docs.zephyrproject.org/latest/boards/st/stm32l562e_dk/doc/index.html#stm32l562e-dk-board).`

Should be:
`This project outputs sensor data to the console. It requires a LSM6DSO sensor, which is present on the [ST STM32L562E-DK Discovery](https://docs.zephyrproject.org/latest/boards/st/stm32l562e_dk/doc/index.html#stm32l562e-dk-board).`

**Environment**

* Page: `samples/sensor/lsm6dso/README`
* Version: main
* SHA-1: 14c92da96d5613b48610fa9bfe284528a814a4e6

**Comment by kartben** [comment]
Hi @MichalBiolik 
Thanks for the bug report. The text is actually correct. "an" is used before words that starts with a vowel sound, which is the case for "L-S-M-6-D-S-O" :)
