### ISSUE TITLE
getchar sample not working on nRF5x

### ISSUE THREAD

**Issue by carlescufi** [zephyrproject-rtos/zephyr#7755]
[This commit](https://github.com/zephyrproject-rtos/zephyr/commit/05c45e359a94e96353dfac1f0abeccf6893e988a#diff-fb209e20d9cf9e70b3dbd2748ae43f90) broke the `samples/subsys/console/getchar` sample.

**Comment by carlescufi** [comment]
@jarz-nordic can you make sure your PR fixes this?

**Comment by pfalcon** [comment]
> This commit 05c45e359a94e96353dfac1f0abeccf6893e988a https://github.com/zephyrproject-rtos/zephyr/pull/7431 broke the samples/subsys/console/getchar sample.

There's a comment on that commit that zephyr shell is broken too:
https://github.com/zephyrproject-rtos/zephyr/commit/05c45e359a94e96353dfac1f0abeccf6893e988a#commitcomment-29012316 . 

I don't have a nRF5x system with UART connection, so can't check it myself.

**Comment by carlescufi** [comment]
@pfalcon different issue though. Both shell and getchar work with this PR anyway, so this is fine
