### ISSUE TITLE
sanitycheck error with --coverage

### ISSUE THREAD

**Issue by ramakrishnapallala** [zephyrproject-rtos/zephyr#7758]
Getting following error when running sanitycheck with --coverage option

genhtml: ERROR: cannot read /home/rpallala/ssg-otc/Zephyr/gcov-tests/22nd-May/zephyr/sanity-out/native_posix/samples/application_development/external_lib/test/mylib/obj/src/mylib.c

Due to the above error, index.html is not getting created (HTML generation is incomplete)

**Comment by nashif** [comment]
I do not get this error:

```
i9:zephyr(master): sanitycheck -p native_posix --coverage
Cleaning output directory /home/nashif/Work/github/zephyr/sanity-out
Building testcase defconfigs...
221 tests selected, 54887 tests discarded due to filters
total complete:  221/ 221  100%  failed:    0
Generating coverage files...
Cannot open source file src/mylib.c
HTML report generated: /home/nashif/Work/github/zephyr/sanity-out/coverage/index.html
221 of 221 tests passed with 0 warnings in 268 seconds
i9:zephyr(master):
```

**Comment by nashif** [comment]
you can exclude src/mylib.c, see .shippable.yaml for an example.
