### ISSUE TITLE
cmake failure using ExternalProject and dependancies w/ninja

### ISSUE THREAD

**Issue by galak** [zephyrproject-rtos/zephyr#7760]
The following testcase fails:

./scripts/sanitycheck -p lpcxpresso54114_m4 -s samples/subsys/ipc/ipm_mcux/test -N

We get the following error:

```
-- Build files have been written to: /home/galak/git/zephyr/sanity-out/lpcxpresso54114_m4/samples/subsys/ipc/ipm_mcux/test
ninja: Entering directory `/home/galak/git/zephyr/sanity-out/lpcxpresso54114_m4/samples/subsys/ipc/ipm_mcux/test'
ninja: error: 'ipm_mcux_remote-prefix/src/ipm_mcux_remote-build/zephyr/zephyr.bin', needed by 'zephyr/include/generated/core-m0.inc', missing and no known rule to make it
```

**Comment by SebastianBoe** [comment]
This due to the dependencies being wrong.

I would recommend reading 

https://samthursfield.wordpress.com/2015/11/21/cmake-dependencies-between-targets-and-files-and-custom-commands/

and then having a look at how the dependencies are set up.

An example of this working in practice can be seen in the toplevel CMakeLists.txt

```
  # Use gperf to generate C code (PRIV_STACKS_OUTPUT_SRC_PRE) which implements a
  # perfect hashtable based on PRIV_STACKS
  add_custom_command(
    OUTPUT ${PRIV_STACKS_OUTPUT_SRC_PRE}
    COMMAND
    ${GPERF} -C
    --output-file ${PRIV_STACKS_OUTPUT_SRC_PRE}
    ${PRIV_STACKS}
    DEPENDS priv_stacks ${PRIV_STACKS}
    WORKING_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR}
    )
  add_custom_target(priv_stacks_output_src_pre DEPENDS ${CMAKE_CURRENT_BINARY_DIR}/${PRIV_STACKS_OUTPUT_SRC_PRE})

```

**Comment by galak** [comment]
I've read the link, but not sure I quite follow or understand how the dependancies are wrong in the case of this issue.

**Comment by SebastianBoe** [comment]
Pretty sure this is due to the lack of BUILD_BYPRODUCTS.  See https://stackoverflow.com/questions/40314785/linking-against-an-externalproject-add-dependency-in-cmake

**Comment by nashif** [comment]
bug in a sample, this should not be blocking a release, so move to low priority

**Comment by galak** [comment]
@tejlmand Can you take a look at this and see how we should fix it.

**Comment by tejlmand** [comment]
@galak Will do
