### ISSUE TITLE
Zbus heap increase

### ISSUE THREAD

**Issue by chirambaht** [zephyrproject-rtos/zephyr#77613]
**Is your feature request related to a problem? Please describe.**
When running a code with a few message subscribers and listeners, an error started to appear described as follows:
```txt
ASSERTION FAIL [buf != ((void *)0)] @ WEST_TOPDIR/deps/zephyr/subsys/zbus/zbus.c:133
    net_buf zbus_msg_subscribers_pool is unavailable or heap is full
@ WEST_TOPDIR/deps/zephyr/lib/os/assert.c:43
[00:00:00.000,000] <err> os: >>> ZEPHYR FATAL ERROR 4: Kernel panic on CPU 0
[00:00:00.000,000] <err> os: Current thread: 0x80bad00 (test_thread)
[00:00:00.000,000] <err> os: Halting system
```
This is run with no **CONFIG_HEAP_MEM_POOL_SIZE** option defined to use the auto heap calculation introduced recently in Zephyr.

**Describe the solution you'd like**
Adding a Kconfig allowing Zbus users to add heap to their projects as is needed. This is done by setting adding the following lines to the `zephyr/subsys/zbus/Kconfig` file:
```kconfig
config HEAP_MEM_POOL_ADD_SIZE_ZBUS
    int "The size of heap to add to the memory pool on behalf of ZBUS."
    default 0
    depends on ZBUS_MSG_SUBSCRIBER_BUF_ALLOC_DYNAMIC
```

**Comment by rodrigopex** [comment]
@chirambaht, thanks for pointing out this improvement on zbus. I have added a PR for adding that. I added a default value of 1024 for the heap size for zbus. 

I hope, soon, you will see that available in the main.

**Comment by rodrigopex** [comment]
Solve by #77631
