### ISSUE TITLE
net: lib: http_server: enable application to set response headers

### ISSUE THREAD

**Issue by kica-z** [zephyrproject-rtos/zephyr#77689]
**Is your enhancement proposal related to a problem? Please describe.**
I am currently evaluating the Zephyr HTTP Server for a new Project we will soon be starting. The problem I stumbled upon was that there currently is no possibility to set response headers. Specifically I would need to set the `status code` as well as the `content type` dynamically within the dynamic HTTP resource callback.

**Describe the solution you'd like**
Ideally we would add an additional `http_data_status` called `HTTP_SERVER_HEADER` in which the callback can put header data into the buffer and return the byte-count written. The API could then depending on HTTP1/2 take those headers and send them to the client. If 0 is returned on the first call with status `HTTP_SERVER_HEADER` the default headers would be used.

**Describe alternatives you've considered**
One alternative would be to not provide this functionality at all. Another would be to add the status code header option to the `http_resource_detail_dynamic` struct like the `content_type`. But this would not address the issue of dynamically changing headers as well as other custom headers that might be needed in the future.

**Additional context**
\-

**Comment by jukkar** [comment]
This is already implemented and merged.
