### ISSUE TITLE
Ethernet does not work on sam_v71_xult board

### ISSUE THREAD

**Issue by talih0** [zephyrproject-rtos/zephyr#77714]
**Describe the bug**

Pinging or connecting to the sam_v71_xult  board via telnet does not work,
The same test with my network configuration works fine on xmc47_relax_kit.

 - What target platform are you using?
   sam_v71_xult
 - What have you tried to diagnose or workaround this issue?
   Haven't diagnosed issue.
 - Is this a regression? If yes, have you been able to "git bisect" it to a
  Uknown

**To Reproduce**

$ west build -p -b sam_v71_xult samples/net/telnet/ 
$ west flash

$ ping 192.0.2.1
PING 192.0.2.1 (192.0.2.1) 56(84) bytes of data.
From 192.0.2.10 icmp_seq=1 Destination Host Unreachable
From 192.0.2.10 icmp_seq=2 Destination Host Unreachable
From 192.0.2.10 icmp_seq=3 Destination Host Unreachable

or 
$ telnet 192.0.2.1

**Expected behavior**

**Environment (please complete the following information):**

 - OS: (Linux)
 - Toolchain (e.g Zephyr SDK, ...)
 - Commit origin/main 386263cc

**Comment by dkalowsk** [comment]
@talih0 can you please fill out more of the bug issue?  It's not clear how to reproduce this issue from what you filed here, or what we're looking for as a result.

**Comment by talih0** [comment]
@dkalowsk, sorry I just saw that part of issue didn't get rendered properly.

Did you try to do a simple ping test on the board?

**Comment by dkalowsk** [comment]
> @dkalowsk, sorry I just saw that part of issue didn't get rendered properly.
> 
> Did you try to do a simple ping test on the board?

@talih0 no I don't have the board in question.  I'm simply working through the open issues to help get them resolved faster by those with the needed hardware.

**Comment by talih0** [comment]
I did more troubleshooting in the eth_sam_gmac.c driver.
The issue is that transmitted packets are never sent out (rx is working fine). The driver gets stuck in waiting for the confirmation semaphore:
https://github.com/zephyrproject-rtos/zephyr/blob/main/drivers/ethernet/eth_sam_gmac.c#L1555

**Comment by talih0** [comment]
I figured out the problem, there are two revisions (A, B) of this board with a different number of priority queues. I was using the wrong revision in the build.
