### ISSUE TITLE
tests/kernel/mem_protect/stack_random hangs without any console output on frdm_k64f

### ISSUE THREAD

**Issue by pswarnak** [zephyrproject-rtos/zephyr#7782]
The test **tests/kernel/mem_protect/stack_random** hangs without any console log or error message.

Arch: arm
Board: frdm_k64f
Zephyr tag:  v1.12.0-rc1

**Error:**
*No console log available at all.*

To further debug, tried reproducing the issue on other targets "sam_e70_xplained - arm board", "qemu_cortex_m3 - arm", "arduino_101 - x86 board" and "qemu_x86 - x86".
The test passes on the boards mentioned above, except frdm_k64f.

**Steps to reproduce:**
```
rm -rf build && mkdir build && cd build
cmake -D BOARD=frdm_k64f ../
cp build/zephyr/zephyr.bin /run/media/pswarnak<use your username>/MBED/ 


Check the console log.
```

**Expected output:**
```
PASS - test_stack_pt_randomization
```

**Comment by carlescufi** [comment]
@pswarnak can you try reverting commit 72c7ded5612870c20a3efc3f36a9688ff85a4418 ? It seems to break completely the build for Nordic chips

**Comment by nashif** [comment]
which commit are you testing here?
seems to work in master:
```
EVICE: ***** Booting Zephyr OS v1.12.0-rc1-41-gfcc56e315f *****
DEVICE: Running test suite stack_pointer_randomness
DEVICE: ===================================================================
DEVICE: starting test - test_stack_pt_randomization
DEVICE: Test Stack pointer randomization
DEVICE: stack pointer changed 57 times out of 64 tests
DEVICE: PASS - test_stack_pt_randomization
DEVICE: ===================================================================
DEVICE: ===================================================================
DEVICE: PROJECT EXECUTION SUCCESSFUL
```

**Comment by pswarnak** [comment]
>> which commit are you testing here?
I was testing it as part of v1.12.0-rc1 zephyr tag validation(mentioned in issue description) - commit e7509c17c5938b48f9ad4b7ae78199bb0faa6113.
Thank you for confirming, just tried out, test passing in master.

Sorry for the inconvenience.
Closing the issue, will validate on master next time, before reporting any issues.
