### ISSUE TITLE
CI: shippable - provide some means to allow users to rebuild

### ISSUE THREAD

**Issue by galak** [zephyrproject-rtos/zephyr#779]
Right now the only way to force a rebuild with shippable appears to be either asking someone who is an Admin or pushing an update to the PR.  We should have some means to allow users to do this on their PRs (ie equiv a gerrit recheck)

**Comment by dbkinder** [comment]
Shouldn't this be submitted as a Jira issue?

**Comment by nashif** [comment]
this is fixed now, "recheck" comment on a PR should trigger a rebuild.
