### ISSUE TITLE
[backport]  Bluetooth: RFCOMM: check the validity of received frame

### ISSUE THREAD

**Issue by ceolin** [zephyrproject-rtos/zephyr#77968]
Missing validation fixed in #74640 must be backported.

**Comment by henrikbrixandersen** [comment]
For some reason, a backport PR was not automatically created.

**Comment by ceolin** [comment]
@lylezhu2012 can you take a look please ?

**Comment by lylezhu2012** [comment]
> @lylezhu2012 can you take a look please ?

What do I need to do?

**Comment by henrikbrixandersen** [comment]
Anybody working on this?

**Comment by Thalley** [comment]
> Anybody working on this?

I don't think so. Ideally the maintainer, @lylezhu2012, would take this up, but I don't think the backporting procedure is defined well enough for people unfamiliar with the process to easily do it.

**Comment by henrikbrixandersen** [comment]
> I don't think so. Ideally the maintainer, @lylezhu2012, would take this up, but I don't think the backporting procedure is defined well enough for people unfamiliar with the process to easily do it.

Okay. I have created a manual backport PR here: https://github.com/zephyrproject-rtos/zephyr/pull/78860

**Comment by henrikbrixandersen** [comment]
Fixed in #78860.
