### ISSUE TITLE
[backport]  Bluetooth: SDP: Fix stack override issue

### ISSUE THREAD

**Issue by ceolin** [zephyrproject-rtos/zephyr#77962]
Missing check fixed in #75575 must be backported.

**Comment by henrikbrixandersen** [comment]
For some reason, a backport PR was not automatically created.

**Comment by ceolin** [comment]
> For some reason, a backport PR was not automatically created.

yep, that is weird. It wasn't a glitch, @jhedberg removed/created the backport and no pr was created.

**Comment by henrikbrixandersen** [comment]
I have created a manual backport PR here: https://github.com/zephyrproject-rtos/zephyr/pull/78858

**Comment by henrikbrixandersen** [comment]
Fixed in #78858.
