### ISSUE TITLE
`CONFIG_NET_CONFIG_CLOCK_SNTP_INIT` depends on deprecated `CONFIG_POSIX_CLOCK`

### ISSUE THREAD

**Issue by lucaato** [zephyrproject-rtos/zephyr#77977]
I think this should be changed to `depends on SNTP && CONFIG_POSIX_TIMERS`.

https://github.com/zephyrproject-rtos/zephyr/blob/689d1edee1d57f052b1d4572d67618c0b0e2b8a4/subsys/net/lib/config/Kconfig#L209

**Comment by jukkar** [comment]
@lucaato could you send a PR for this?
