### ISSUE TITLE
edtlib: wrong endianess at least in '_raw_unit_addr()'

### ISSUE THREAD

**Issue by avolkov-1221** [zephyrproject-rtos/zephyr#78020]
**Describe the bug**

Despite the Zephyr [documentation](https://docs.zephyrproject.org/latest/build/dts/intro-syntax-structure.html#writing-property-values) is clear enough about the 64 bits integers:

> 64-bit integers are written as two 32-bit cells in big-endian order. The value 0xaaaa0000bbbb1111 would be written <0xaaaa0000 0xbbbb1111>.

At least '_raw_unit_addr()' function of  'edtlib', assume the opposite and treat values as little-endian (using [:4*addr_len] in Python semantics). As a result, declarations like the following:

 ```
parent {
    #address-cell = <1>;
    node-1@1 {
        regs = <0 1>;
    };
};
```
are handled incorrectly. Specifically, the `reg` value should be 1, but the function will treat the `reg`'s property value as 0. As if it had been written:
 ```
parent {
    #address-cell = <1>;
    node-1@1 {
        regs = <1 0>;
    };
};
```
**To Reproduce**

Use any edtlib based script with the above snippets, and check the result.

**Expected behavior**

The 64-bit values (and above) should be handled as big-endian, not little- one. Otherwise, device trees for Zephyr and other software will become incompatible.

**Impact**

All edtlib based software.

**Logs and console output**

**Environment (please complete the following information):**

 - OS: any
 - Toolchain Zephyr SDK
 - Commit SHA or Version used: any up to and including the 3.7.99

**Additional context**

The conversion and handling of raw byte arrays should be rechecked; other parts of edtlib may potentially have the same error.

**Comment by 57300** [comment]
> ```
> parent {
>    #address-cell = <1>;
>    node-1@1 {
>        regs = <0 1>;
>    };
> };
> ```
> 
> 
>     
>   
> 
> are handled incorrectly. Specifically, the `reg` value should be 1, but the function will treat the `reg`'s property value as 0. As if it had been written:

It's 0 because `#address-cells = <1>`. The second `reg` cell (1) would be the size (assuming implicit `#size-cells = <1>`).
Try setting `#address-cells = <2>` to represent 64-bit addresses.

**Comment by avolkov-1221** [comment]
> > declarations like the following:
> > ```
> > parent {
> >    #address-cell = <1>;
> >    node-1@1 {
> >        regs = <0 1>;
> >    };
> > };
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > are handled incorrectly. Specifically, the `reg` value should be 1, but the function will treat the `reg`'s property value as 0. As if it had been written:
> 
> It's 0 because `#address-cells = <1>`. The second `reg` cell (1) would be the size (assuming implicit `#size-cells = <1>`). Try setting `#address-cells = <2>` to represent 64-bit addresses.

I know. It's not a bug, it was an easiest way to demonstrate the incorrect work of the library. In case of big endian, it should be 1, not 0.

**Comment by mmahadevan108** [comment]
@avolkov-1221 , can you submit a PR for this issue?

**Comment by mmahadevan108** [comment]
@decsny @galak , do you have the bandwidth to look into this.

**Comment by avolkov-1221** [comment]
> @avolkov-1221 , can you submit a PR for this issue?

It's https://github.com/zephyrproject-rtos/zephyr/pull/77900 PR. It's under development.

**Comment by decsny** [comment]
I will say, it looks like that function is only used for interrupt mapping, and I don't think the rest of the DT tooling treats addresses like little endian, because there are many examples of big endian multi-cell addresses being actively used in zephyr such as in I2C and I3C addresses which are 96 bits and written in big endian format and resulting in a big endian unit address.

**Comment by ydamigos** [comment]
This issue should be closed as fixed. PR [#91011](https://github.com/zephyrproject-rtos/zephyr/pull/91011) fixed it.
