### ISSUE TITLE
STM32 *.dtsi: configure `clocks` via macro similar to `STM32_RESET`

### ISSUE THREAD

**Issue by mathieuchopstm** [zephyrproject-rtos/zephyr#78106]
**Is your enhancement proposal related to a problem? Please describe.**
Currently, the `resets` property of nodes in STM32 DTSI files is filled using a macro called `STM32_RESET`.
https://github.com/zephyrproject-rtos/zephyr/blob/34982bb00b57486aeb83a6cb3bb7433791302aed/dts/arm/st/c0/stm32c0.dtsi#L177-L184

The macro's implementation is found in `include/zephyr/dt-bindings/reset/stm32-common.h`:
https://github.com/zephyrproject-rtos/zephyr/blob/34982bb00b57486aeb83a6cb3bb7433791302aed/include/zephyr/dt-bindings/reset/stm32-common.h#L20

Ignoring the bitpacking detail, this macro provides two benefits for users:
1. removes the need to type `STM32_RESET_BUS_` every time
2. accepts a bit number, which is the form used in RefMan

TL;DR: this macro makes both authoring ***and*** reading of DTSI files a much better experience.

Currently, there is unfortunately no equivalent to this macro for the `clocks` property.
To make matters worse, (nearly) all DTSI files are using raw hex values for the `clocks` properties. This makes reading and authoring of these files tedious.

**Describe the solution you'd like**

A new macro - ideally named `STM32_CLOCK` - should be created to offer the same feature for `clocks` property:
```c
/* Whitespace between 'STM32_CLOCK_BUS_##bus' and '(1 << (bit))'
 * is necessary - this macro must expand to two DTS cells.
 */
#define STM32_CLOCK(bus, bit) STM32_CLOCK_BUS_##bus  (1 << (bit))
```

> However, note that `STM32_CLOCK` is already used for domain clock (a.k.a. kernel clock) selection:
> https://github.com/zephyrproject-rtos/zephyr/blob/34982bb00b57486aeb83a6cb3bb7433791302aed/include/zephyr/dt-bindings/clock/stm32c0_clock.h#L54-L58
> There are two solutions to this issue:
> * Circumventing by using a different name (for example, `STM32_CLOCK_GATE`)
> * Renaming the existing macro beforehand (for example, `STM32_CLOCK` --> `STM32_DOMAIN_CLOCK`)
>   * This *should* not be a breaking change, as this macro is for internal use (wrapped by `xxx_SEL()` which are for public usage) 
>   * N.B.: A revamp of this macro is already under consideration; if performed, this issue may be solved as a bonus

After the introduction of this macro, the existing DTSI files would have to be modified to use it.

Taking the earlier example: (note that `1 << 14` is `0x00004000`)
```diff
 usart1: serial@40013800 { 
 	compatible = "st,stm32-usart", "st,stm32-uart"; 
 	reg = <0x40013800 0x400>; 
- 	clocks = <&rcc STM32_CLOCK_BUS_APB1_2 0x00004000>;
+ 	clocks = <&rcc STM32_CLOCK(APB1_2, 14U)>; 
 	resets = <&rctl STM32_RESET(APB1H, 14U)>; 
 	interrupts = <27 0>; 
 	status = "disabled"; 
 }; 
```

**Describe alternatives you've considered**

Without introducing any macro, all raw hex values in DTSI files could be replaced with the equivalent `(1 << X)` notation.
This would make DTSI files more readable, but still tedious to write.

**Comment by HubertYGuan** [comment]
Hi @mathieuchopstm and @erwango, I'd like to try implementing this macro. Would you mind assigning me?
