### ISSUE TITLE
CAVS Interrupt controller - using undefined Kconfig symbols

### ISSUE THREAD

**Issue by galak** [zephyrproject-rtos/zephyr#7811]
The following Kconfig symbols are used in drivers/interrupt_controller/cavs_ictl.c but aren't defined.
CONFIG_CAVS_ICTL_0_IRQ_PRI
CONFIG_CAVS_ICTL_1_IRQ_PRI
CONFIG_CAVS_ICTL_2_IRQ_PRI
CONFIG_CAVS_ICTL_3_IRQ_PRI

**Comment by nashif** [comment]
@SavinayDharmappa please take a look.

**Comment by nashif** [comment]
@rgundi ping
