### ISSUE TITLE
HTTP server sample not working, after change to listen on any address

### ISSUE THREAD

**Issue by mrodgers-witekio** [zephyrproject-rtos/zephyr#78112]
**Describe the bug**
With latest `main` branch, there is no response to curl requests to the HTTP server sample.

Looking into the problem a bit further, it seems the TCP connection is not established.

The problem appears to be caused by a combination of commits:
- `5e7d7302740 samples: net: http_server: Create service binding to all addresses`
- `3949873886a net: http_server: Allow service to be created with NULL host`

If I revert either one of these it is working again.

I had a brief look at the changes in `http_server_core.c` and I think the issue might be that when the `svc->host` is NULL, the `sin_addr`/`sin6_addr` field of the `sockaddr` is never set. Since the struct is stack-allocated, it could contain any random value for the address. But I haven't had time to confirm this, I'll have another look on Monday if no-one has checked before that.

**To Reproduce**
Build and run `samples/net/sockets/http_server` on the `native_sim` board. Send an HTTP request via curl.

**Expected behavior**
HTTP response should be received.

**Impact**
Sample not functional

**Environment (please complete the following information):**
Linux, commit `5a3c9c914a6`, Zephyr SDK toolchain

**Comment by jukkar** [comment]
If you have IPv6 enabled, and are trying to connect using IPv4, then set `CONFIG_NET_IPV4_MAPPING_TO_IPV6=y`.
I should have set this in samples prj.conf but forgot to do so, I will send a fix for it.
