### ISSUE TITLE
Confusing macros: SECONDS vs K_SECONDS, MSEC vs K_MSEC

### ISSUE THREAD

**Issue by pfalcon** [zephyrproject-rtos/zephyr#7817]
We have 2 very similarly named, but sufficiently different sets of macros:

* SECONDS() and MSEC() are defined in https://github.com/zephyrproject-rtos/zephyr/blob/master/include/sys_clock.h#L113 and described as "Number of ticks for x seconds."
* K_SECONDS() and K_MSEC() are defined in https://github.com/zephyrproject-rtos/zephyr/blob/master/include/kernel.h#L1186 and are used to "convert" a numeric value to milliseconds.

Taking subsys/net/ip/ as an example, between K_SECONDS and SECONDS, it always used K_SECONDS. And vice versa, it never used K_MSEC, and instead used MSEC. This was recently fixed with #7711.

At the same time, https://github.com/zephyrproject-rtos/zephyr/issues/7657 shows that the confusion happens in other parts of the codebase too.

The suggestion is to rename SECONDS() and MSEC() in such a way that it was clear that they deal with sys clock ticks, e.g. to TICKS_SECONDS() and TICKS_MSEC().

**Comment by nashif** [comment]
please do not assign to more than 1 person, multiple assignees leads to no action at all.

**Comment by nashif** [comment]
@andyross can you take a look at this as part of your timer rewrite series?

**Comment by andyross** [comment]
Yeah.  There's a growing list of "missed cleanup opportunities" with the timer code that I keep discovering, will add this to the list.
