### ISSUE TITLE
build breakage due to enabling USER_SPACE by default

### ISSUE THREAD

**Issue by galak** [zephyrproject-rtos/zephyr#7819]
The following change breaks building several configs:

`./scripts/sanitycheck -p minnowboard -s tests/benchmarks/footprint/benchmark.footprint.regular`

efe0c4b
```
commit efe0c4b7647c5e5aa53af47679bb8625fb387b19 (refs/bisect/bad)
Author: Andrew Boie <andrew.p.boie@intel.com>
Date:   Mon May 21 12:44:38 2018 -0700

    tests: enable user mode by default
```

**Comment by galak** [comment]
Seeing a number of failures related to this change:
https://app.shippable.com/github/zephyrproject-rtos/ci-test/runs/2036/summary/console

**Comment by galak** [comment]
These 2 tests seem to be the majority of issue, in the size growing to big:
tests/crypto/sha256/crypto.sha256 
tests/crypto/hmac_prng/crypto.hmac_prng

**Comment by andrewboie** [comment]
Looking at these now.
