### ISSUE TITLE
Renesas Kconfig bleeding into every device

### ISSUE THREAD

**Issue by nordicjm** [zephyrproject-rtos/zephyr#78205]
This pr by @quytranpzz https://github.com/zephyrproject-rtos/zephyr/pull/76304 was wrongly merged when it had mistakes:

https://github.com/zephyrproject-rtos/zephyr/pull/76304/files#diff-5a699a6bc2707cd34cca411cb123ebce8011ad81d7fb7075bc856911ea0ec4f7R23 this Kconfig has nothing to do with the Kconfig.soc file and has no depends on, move it to Kconfig and add the correct if/depends on for it

https://github.com/zephyrproject-rtos/zephyr/pull/76304/files#diff-094b8121e8f50519a4c6b32697103993ea7a3699d879eeb36ff1e5d415c76c1fR23 Same as above

https://github.com/zephyrproject-rtos/zephyr/pull/76304/files#diff-908b8e02f4aba2416d2310209e67e6cddb873d5904935cbca6e8eba5d2f13443R23 Same as above

Also https://github.com/zephyrproject-rtos/zephyr/blob/main/soc/renesas/ra/ra8d1/Kconfig.soc#L9 Kconfig help text spacing is 1x tab followed by 2x spaces, it is not 2x tabs

**Comment by duynguyenxa** [comment]
@nordicjm , I've created https://github.com/zephyrproject-rtos/zephyr/pull/78208/files to fix this
