### ISSUE TITLE
doc: Documentation issue in 'hardware/peripherals/i3c'  Incorrect detail for SETDASA I3C CCC usage

### ISSUE THREAD

**Issue by quic-bkulkarn** [zephyrproject-rtos/zephyr#78259]
On https://docs.zephyrproject.org/latest/hardware/peripherals/i3c.html, it is mentioned as 
**Do SETDASA to use static addresses as dynamic address if so desired**
![image](https://github.com/user-attachments/assets/31088cef-c1cd-4c96-ae9c-67fcb5efbc67)

But it should rather be as below:
**Do SETDASA to assign a dynamic address using the static address of the device**

**Environment**

* Page: `hardware/peripherals/i3c`
* Version: main
* SHA-1: 512dc9ff38d8dad84b340712e71a20185fe59819

**Comment by henrikbrixandersen** [comment]
@quic-bkulkarn Could you submit a PR for fixing this?

**Comment by quic-bkulkarn** [comment]
Sure, I will be submitting a PR soon. @dcpleung can you please assign this issue to me?

**Comment by kartben** [comment]
fixed with #78537
