### ISSUE TITLE
Transfer Collaborator status from GRobertZeiba to RobertZ2011

### ISSUE THREAD

**Issue by rriveramcrus** [zephyrproject-rtos/zephyr#78297]
# Background

The [TSC Project Roles] defines the main roles for the Zephyr Project, including
Maintainer, Collaborator, and Contributor.

By default anyone that contributes code or documentation is a Contributor, but
with the lowest [GitHub Permission Level] of Read. For example, Contributors
with Read permission do not have the permission to add reviewers to a pull
request.

Use this template to nominate a GitHub user for the Contributor role with
Triage permission level, which allows the user to add reviewers to a pull
request and be added as a reviewer by other users.

# Nomination

## GitHub User

Provide the following information about the GitHub user:

1. Robert Zeiba
1. @RobertZ2011
1. Individual

## Supporting Documents

Add links to 3-5 GitHub pull requests, in the Zephyr project, authored or
reviewed by the GitHub user that demonstrate the user's dedication to the
Zephyr project.

@GRobertZieba was already acting as a collaborator for the Charger API. Robert's account was tied to his former employer's email and became inaccessible once Robert departed that role.  Robert has started using his personal account (@RobertZ2011) to continue contributing to the Zephyr project.
- https://github.com/zephyrproject-rtos/zephyr/pull/77087#issuecomment-2332133977

[TSC Project Roles]: <https://docs.zephyrproject.org/latest/project/project_roles.html>
[GitHub Permission Level]: <https://docs.github.com/en/organizations/managing-access-to-your-organizations-repositories/repository-roles-for-an-organization>

**Comment by nashif** [comment]
Thank you for your contribution to the Zephyr project. 

An invite was sent to you to join the project. You can find the invite here: https://github.com/zephyrproject-rtos/zephyr/invitations.

Note that further access and permissoins to the project will be provided following the project [guidelines](https://docs.zephyrproject.org/latest/project/project_roles.html#tsc-project-roles).

**Comment by RobertZ2011** [comment]
Sorry, could I get another invitation? I didn't see the original one as it ended up in my spam folder.
