### ISSUE TITLE
NXP display sample HAL regression issue

### ISSUE THREAD

**Issue by DerekSnell** [zephyrproject-rtos/zephyr#78299]
After NXP's HAL update [e4cc0f2](https://github.com/zephyrproject-rtos/zephyr/commit/e4cc0f27807e02e253e49a7318a1e779c328b481), the display driver and sample fails on some NXP boards, including the MIMXRT1170-EVK board.  

This issue likely fails on other NXP boards.  The issue also causes failures in other samples using the display driver like samples/drivers/video/capture.  The issue prevents these apps from booting correctly, the boot banner and other console output do not print.

To replicate with the working commit before the HAL update e8a375e, these steps show the display sample working.  Build the sample with:
```
west build -b mimxrt1170_evk//cm7 samples/drivers/display/ --shield=rk055hdmipi4ma0 --pristine
```
Flashing to the board, the display shows the expected pattern: the 4 corners have colored rectangles on a white background, with the black corner fading to white.  This console output also prints after the display background is initialized:
```
*** Booting Zephyr OS build v3.7.0-1024-ge8a375ec2387 ***               
[00:00:00.185,000] <inf> sample: Display sample for display-controller@40804000
```
But when building the same sample with [e4cc0f2](https://github.com/zephyrproject-rtos/zephyr/commit/e4cc0f27807e02e253e49a7318a1e779c328b481) or later, no boot banner or any console output prints.  The display backlight turns on, but the display is not updated.

**Comment by pdgendt** [comment]
I bumped into the same issue, the driver initialization for `himax,hx8394` gets stuck.
Putting an `k_msleep(1)` in `hx8394_mipi_tx` seemed to get the samples working again, but doesn't feel like a proper solution.
