### ISSUE TITLE
CONFIG_ESP32_WIFI_NET_ALLOC_SPIRAM has no effect

### ISSUE THREAD

**Issue by sam-golioth** [zephyrproject-rtos/zephyr#78308]
**Describe the bug**

`CONFIG_ESP32_WIFI_NET_ALLOC_SPIRAM` has no effect. Enabling this option does not change the size of the used space in either `ext_ram_seg` or `dram0_0_seg`. This was tested with `esp32_devkitc_wrover/esp32/procpu`
**To Reproduce**

**Expected behavior**

**Impact**

**Logs and console output**

**Environment (please complete the following information):**

 - OS: (e.g. Linux, MacOS, Windows)
 - Toolchain (e.g Zephyr SDK, ...)
 - Commit SHA or Version used

**Additional context**

**Comment by EricNRS** [comment]
FYI, related issues:

- https://github.com/zephyrproject-rtos/zephyr/issues/74246
- https://github.com/zephyrproject-rtos/zephyr/issues/74675
- https://github.com/zephyrproject-rtos/zephyr/issues/74284

**Comment by marekmatej** [comment]
This issue is previously described here https://github.com/zephyrproject-rtos/zephyr/issues/74675

**Comment by sylvioalves** [comment]
Closing as duplicated: #74675
