### ISSUE TITLE
[MESH] 

### ISSUE THREAD

**Issue by caogule** [zephyrproject-rtos/zephyr#78341]
![image](https://github.com/user-attachments/assets/cc1b90c3-d7dc-4dc6-9fb1-7c1817618d09)
![image](https://github.com/user-attachments/assets/cc1b90c3-d7dc-4dc6-9fb1-7c1817618d09)

bt_mesh_cfg_cli_net_key_add(msg->len = 20) -> bt_mesh_msg_ackd_send->bt_mesh_msg_send->bt_mesh_access_send->bt_mesh_trans_send. msg->len > (BT_MESH_TX_SDU_MAX - BT_MESH_MIC_SHORT), cause error. is this right?
```[tasklist]
### Tasks
```

**Comment by nordicjm** [comment]
If submitting a bug, you need to fill in all the fields from the template here: https://github.com/zephyrproject-rtos/zephyr/blob/main/.github/ISSUE_TEMPLATE/001_bug_report.md?plain=1

Closing since this is just 2 giant pictures with no description or relevance
