### ISSUE TITLE
CONFIG_BMM150_SET_ATTR not defined (and now removed), giving dead code

### ISSUE THREAD

**Issue by ulfalizer** [zephyrproject-rtos/zephyr#7848]
`drivers/sensor/bmm150/Kconfig` has no definition for `BMM150_SET_ATTR`, which is set by `samples/sensor/bmm150/prj.conf`.

`drivers/sensor/bmm150/bmm150.c` has a bunch of `#if defined(BMM150_SET_ATTR)` (and some `#if defined(BMM150_SET_ATTR_REP)`), which are probably dead code. If those are meant to be Kconfig symbols, they'll need Kconfig definitions (and a `CONFIG_` prefix in the `#ifdef`s).

**Comment by ulfalizer** [comment]
CC @punitvara 

I'm trying to get rid of all assignments to undefined Kconfig symbols, so it can be turned into an error during testing.

**Comment by ulfalizer** [comment]
I'm removing just the `CONFIG_BMM150_SET_ATTR` assignment in https://github.com/zephyrproject-rtos/zephyr/pull/7935. Remove the code as well if it isn't needed.

**Comment by punitvara** [comment]
@ulfalizer  Extra code could be useful when interrupt functionality will be added. @ulfalizer @MaureenHelm  Do you suggest to remove extra code as of now ?

**Comment by punitvara** [comment]
@ulfalizer  ??

**Comment by ulfalizer** [comment]
@punitvara 
Sorry, missed it.

No panic to remove it on my part, if you think it might get used.

**Comment by punitvara** [comment]
Ok no problem @ulfalizer Closing this issue as code is reusable to enable interrupt
