### ISSUE TITLE
Nominate myself (vaishnavachath) as Collaborator

### ISSUE THREAD

**Issue by vaishnavachath** [zephyrproject-rtos/zephyr#78526]
# Background

The [TSC Project Roles] defines the main roles for the Zephyr Project, including
Maintainer, Collaborator, and Contributor.

By default anyone that contributes code or documentation is a Contributor, but
with the lowest [GitHub Permission Level] of Read. For example, Contributors
with Read permission do not have the permission to add reviewers to a pull
request.

Use this template to nominate a GitHub user for the Contributor role with
Triage permission level, which allows the user to add reviewers to a pull
request and be added as a reviewer by other users.

# Nomination
Maintainer - TI Platforms
https://github.com/zephyrproject-rtos/zephyr/blob/main/MAINTAINERS.yml#L4004
Collaborator - Beagleboard Platforms
https://github.com/zephyrproject-rtos/zephyr/blob/main/MAINTAINERS.yml#L271
## GitHub User

Provide the following information about the GitHub user:

1. Full Name : Vaishnav Mohandas Achath
1. GitHub username : @vaishnavachath 
1. Organization (optional) : Texas Instruments

## Supporting Documents

Add links to 3-5 GitHub pull requests, in the Zephyr project, authored or
reviewed by the GitHub user that demonstrate the user's dedication to the
Zephyr project.
https://github.com/zephyrproject-rtos/zephyr/pull/54324
https://github.com/zephyrproject-rtos/zephyr/pull/44492
https://github.com/zephyrproject-rtos/zephyr/pull/77197
https://github.com/zephyrproject-rtos/zephyr/pull/75198
https://github.com/zephyrproject-rtos/zephyr/pull/74558\
https://github.com/zephyrproject-rtos/zephyr/pull/74426

[TSC Project Roles]: <https://docs.zephyrproject.org/latest/project/project_roles.html>
[GitHub Permission Level]: <https://docs.github.com/en/organizations/managing-access-to-your-organizations-repositories/repository-roles-for-an-organization>

**Comment by nashif** [comment]
https://github.com/zephyrproject-rtos/zephyr/invitations
