### ISSUE TITLE
Blobs: nRF70 series Wi-Fi firmware images

### ISSUE THREAD

**Issue by carlescufi** [zephyrproject-rtos/zephyr#78639]
## Origin

Nordic Semiconductor ASA, internally developed.

## Type

- [ ] Precompiled library
- [x] Firmware image

## Module

[hal_nordic](https://github.com/zephyrproject-rtos/hal_nordic)

## Purpose

Implementation of both Upper and Lower MAC, as well as the Baseband and RF firmware for the Nordic nRF70 series of Wi-Fi companion chips.

## Pull Request

https://github.com/zephyrproject-rtos/hal_nordic/pull/192

IMPORTANT NOTE: This PR was already merged by mistake, due to the people involved not being aware of the process being followed here. Additional measures will be taken in the CI infrastructure so that this does not happen again.

## Dependencies

None

## License

[Nordic 5-clause license](https://github.com/zephyrproject-rtos/hal_nordic/blob/master/zephyr/LICENSE.txt)

**Comment by nashif** [comment]
approved
