### ISSUE TITLE
`NUM_ITER_PER_SUITE` and `NUM_ITER_PER_TEST` redefined with compiler warnings

### ISSUE THREAD

**Issue by dcpleung** [zephyrproject-rtos/zephyr#78677]
**Describe the bug**
[121/147] Building C object zephyr/subsys/testsuite/ztest/CMakeFiles/subsys__testsuite__ztest.dir/src/ztest.c.obj
```
zephyr/rtos/zephyr/subsys/testsuite/ztest/src/ztest.c:43: warning: "NUM_ITER_PER_SUITE" redefined
   43 | #define NUM_ITER_PER_SUITE 1
      | 
zephyr/rtos/zephyr/subsys/testsuite/ztest/src/ztest.c:34: note: this is the location of the previous definition
   34 | #define NUM_ITER_PER_SUITE CONFIG_ZTEST_SHUFFLE_SUITE_REPEAT_COUNT
      | 
zephyr/rtos/zephyr/subsys/testsuite/ztest/src/ztest.c:44: warning: "NUM_ITER_PER_TEST" redefined
   44 | #define NUM_ITER_PER_TEST  1
      | 
zephyr/rtos/zephyr/subsys/testsuite/ztest/src/ztest.c:35: note: this is the location of the previous definition
   35 | #define NUM_ITER_PER_TEST  CONFIG_ZTEST_SHUFFLE_TEST_REPEAT_COUNT
      | 
```

Issue was introduced via commit 9d9089edd09919c90c4224222fc2c560410e6c85.

**To Reproduce**
`west build -d /tmp/build -p -b qemu_x86 tests/ztest/ztest_param/`

**Expected behavior**
No compiler warnings so CI will pass.

**Impact**
Annoyance for now.

**Environment (please complete the following information):**

 - OS: Linux
 - Toolchain: Zephyr SDK 0.16.8
 - Commit SHA: fd5ecef59e489f0e3b0f269a653e3afefd83af9b

**Comment by ycsin** [comment]
cc @gbarkadiusz
