### ISSUE TITLE
doc: Documentation issue in 'contribute/guidelines'

### ISSUE THREAD

**Issue by rlneumiller** [zephyrproject-rtos/zephyr#78713]
Add instructions to the section "Git Setup" regarding ensuring that the users github profile name is the users full name (first and last) and to ensure that the github profile name and email address matches git config user:name and user:email.

* Page: `contribute/guidelines`
* Version: main
* SHA-1: 9e2c7731377c99f5c2eb3b8889886e82e213963c

**Comment by henrikbrixandersen** [comment]
@rlneumiller Could you please submit a PR for adding these instructions?

**Comment by rlneumiller** [comment]
Ok.
