### ISSUE TITLE
Bluetooth: Starting an already started advertiser messes up state

### ISSUE THREAD

**Issue by rugeGerritsen** [zephyrproject-rtos/zephyr#78721]
**Describe the bug**
1. Call `bt_le_adv_start()`
2. Call `bt_le_adv_start()` again -> will return EALREADY. But internally the state is messed up.
3. Call `bt_le_adv_start()` again -> The host thinks the advertiser is not running 

Fix: Do not call `bt_le_adv_delete_legacy()` upon error. Is this safe?

Triggers here: https://github.com/zephyrproject-rtos/zephyr/blob/main/samples/bluetooth/periodic_sync_rsp/src/main.c#L234 if a sync is not established within 10 seconds

**Comment by jori-nordic** [comment]
_patient_ "Doctor, it hurts when I do this"
_doctor_ "Don't do this then"
