### ISSUE TITLE
Nominate myself (jimmyzhe) as Contributor 

### ISSUE THREAD

**Issue by jimmyzhe** [zephyrproject-rtos/zephyr#78760]
# Background

The [TSC Project Roles] defines the main roles for the Zephyr Project, including
Maintainer, Collaborator, and Contributor.

By default anyone that contributes code or documentation is a Contributor, but
with the lowest [GitHub Permission Level] of Read. For example, Contributors
with Read permission do not have the permission to add reviewers to a pull
request.

Use this template to nominate a GitHub user for the Contributor role with
Triage permission level, which allows the user to add reviewers to a pull
request and be added as a reviewer by other users.

# Nomination

## GitHub User

Provide the following information about the GitHub user:

1. Full Name: Xi He Zheng
1. GitHub username: @jimmyzhe
1. Organization: Andes Technology

## Supporting Documents

- Andes platform
#68265
#59813
#49013
#47821

- RISC-V related
#76777
#75960
#75587

- Misc
#76212
#75580

[TSC Project Roles]: <https://docs.zephyrproject.org/latest/project/project_roles.html>
[GitHub Permission Level]: <https://docs.github.com/en/organizations/managing-access-to-your-organizations-repositories/repository-roles-for-an-organization>

**Comment by nashif** [comment]
https://github.com/zephyrproject-rtos/zephyr/invitations
