### ISSUE TITLE
Exception Stack Frames are not correct in coredumps

### ISSUE THREAD

**Issue by vbrzeski** [zephyrproject-rtos/zephyr#78788]
**Exception Stack Frames are not correct in coredumps**

The stack pointer in the Zephyr ARM Coredumps are imprecise due to an error in the stack offset calculation:
https://github.com/zephyrproject-rtos/zephyr/blob/c3438903d25c8cc9b06c9663f84ab6e37ec00673/arch/arm/core/cortex_m/fault.c#L1115-L1117

The stackpointer can't be calculated without EXC_RETURN. We don't have a reliable way to calculate it outside of the coredump handler.

I see we have an existing PR that would resolve this issue: PR #73189.

**To Reproduce**
With an ARM M4 MCU with FPU extension (e.g. nRF52833):
  1. have one thread doing floating point math
  2. have one thread that doesn't do floating point math
  3. grab a few coredumps
  4. unwind and symbolicate the coredumps, one will fail to unwind properly

**Expected behavior**
I expect the SP to be accurate :)

**Impact**
This prevents us from using upstream Zephyr.

**Interesting Docs**
 * [Exception Return Behavior](https://developer.arm.com/documentation/ddi0403/d/System-Level-Architecture/System-Level-Programmers--Model/ARMv7-M-exception-model/Exception-return-behavior?lang=en)
  * [Exception Stack Frames](https://developer.arm.com/documentation/107706/0100/Exceptions-and-interrupts-overview/Stack-frames)
   * [Stack Alignment](https://developer.arm.com/documentation/ddi0403/d/System-Level-Architecture/System-Level-Programmers--Model/ARMv7-M-exception-model/Stack-alignment-on-exception-entry?lang=en#:~:text=On%20an%20exception%20return%20when,performed%20on%20the%20exception%20entry)

**Comment by ycsin** [comment]
Reopen as #73189 has been reverted
