### ISSUE TITLE
doc: Documentation issue in 'build/kconfig/setting'

### ISSUE THREAD

**Issue by rlneumiller** [zephyrproject-rtos/zephyr#78815]
In the first "Note" under section "Setting symbols in configuration files" the location of the merged Kconfig file at "zephyr/.config" should be specified explicitly in relation to root of the root of the zephyr repository.

Suggested fix:
Change the reference to the location of the file "zephyr/.config" explicitly as "<root of the zephyr repository>/build/zephyr/.config" or similar.  

* Page: `build/kconfig/setting`
* Version: main
* SHA-1: ed954bf63895538547c51418d1fa1e7be0e800c9

**Comment by henrikbrixandersen** [comment]
Please submit a PR proposing this change.

**Comment by rlneumiller** [comment]
Ok.

**Comment by kartben** [comment]
fixed with #79164
