### ISSUE TITLE
USB Audio: Unaligned address data access

### ISSUE THREAD

**Issue by LuoZhongYao** [zephyrproject-rtos/zephyr#78920]
https://github.com/zephyrproject-rtos/zephyr/blob/810f978bed4fbc35eec165eaaedd17745b1ec255/subsys/usb/device/class/audio/audio.c#L598
https://github.com/zephyrproject-rtos/zephyr/blob/810f978bed4fbc35eec165eaaedd17745b1ec255/subsys/usb/device/class/audio/audio.c#L580
https://github.com/zephyrproject-rtos/zephyr/blob/810f978bed4fbc35eec165eaaedd17745b1ec255/subsys/usb/device/class/audio/audio.c#L592
  
https://github.com/zephyrproject-rtos/zephyr/blob/810f978bed4fbc35eec165eaaedd17745b1ec255/samples/subsys/usb/audio/headphones_microphone/src/main.c#L56
https://github.com/zephyrproject-rtos/zephyr/blob/810f978bed4fbc35eec165eaaedd17745b1ec255/samples/subsys/usb/audio/headset/src/main.c#L54

`int16_t` access to unaligned memory, which will cause exceptions on some platforms, such as mips

**Comment by henrikbrixandersen** [comment]
Please use our bug template when reporting bugs. You need to edit this issue to include the information requested in https://github.com/zephyrproject-rtos/zephyr/blob/main/.github/ISSUE_TEMPLATE/001_bug_report.md

**Comment by tmon-nordic** [comment]
Would the solution be to change these accesses to `UNALIGNED_PUT()`/`UNALIGNED_GET()`? Can you submit the PR with the fix?
