### ISSUE TITLE
Board nrf7002dk/nrf5340/cpuapp/ns does not build wifi sample

### ISSUE THREAD

**Issue by nordicjm** [zephyrproject-rtos/zephyr#78942]
**Describe the bug**
Board fails to build, see https://github.com/zephyrproject-rtos/zephyr/actions/runs/10918300637/job/30303866778?pr=78621 for log

**Expected behavior**
CI to not be broken

**Impact**
Showstopper, CI fails on unrelated changes

**Comment by dkalowsk** [comment]
@d3zd3z @ceolin this looks like a possible mbedTLS compile issue.

**Comment by nordic-piks** [comment]
Triaged internally

**Comment by nordicjm** [comment]
> Triaged internally

What is the outcome then? This is holding up multiple PRs and broken in main, when can a fix be expected?

**Comment by nordic-piks** [comment]
> > Triaged internally
> 
> What is the outcome then? This is holding up multiple PRs and broken in main, when can a fix be expected?

This means that we agreed that there is proper assignee (agree with @carlescufi ).
@krish2718 Can you provide some response here?

**Comment by krish2718** [comment]
Temporary work around is done https://github.com/zephyrproject-rtos/zephyr/pull/79248 I will do some RCA and update here.

**Comment by krish2718** [comment]
1. It build fine in downstream (NCS)
2. Upstream build fails due conflicting Legacy vs PSA, e.g., ECDH legacy is enabled by TF-M needs PSA + ECDH.

AFAIK, The co-existence of Legacy and PSA is handled downstream only, @frkv can you please confirm this statement and then we can conclude that NS build (TF-M) is downstream only if using mixed mode crypto?

**Comment by nordicjm** [comment]
This is still not fixed, there are more failures with this board: https://github.com/zephyrproject-rtos/zephyr/actions/runs/11214804463/job/31214301756?pr=78621

**Comment by nordicjm** [comment]
Original reported issue is also not fixed https://github.com/zephyrproject-rtos/zephyr/actions/runs/11214871800/job/31214152920?pr=78657

**Comment by krish2718** [comment]
Yes, the issues aren't fixes, my comment https://github.com/zephyrproject-rtos/zephyr/issues/78942#issuecomment-2395099849 is about working in NCS, but upstream I don't think this would work, waiting on @frkv to comment.

**Comment by nordicjm** [comment]
Is this broken in zephyr 3.7 as well? Because if so, that is a big problem

**Comment by nordicjm** [comment]
@krish2718

> Please filter out NS build for WIFI for this test for the time being. Fixing this would rely on optimizations for the TF-M build that doesn't exist in Zephyr at the moment

Please submit a PR

**Comment by krish2718** [comment]
> @krish2718
> 
> > Please filter out NS build for WIFI for this test for the time being. Fixing this would rely on optimizations for the TF-M build that doesn't exist in Zephyr at the moment
> 
> Please submit a PR

The 7002 NS build is not added to twister, so, I don't think there is anything that needs to be done.

**Comment by nordicjm** [comment]
> > @krish2718
> > > Please filter out NS build for WIFI for this test for the time being. Fixing this would rely on optimizations for the TF-M build that doesn't exist in Zephyr at the moment
> > 
> > 
> > Please submit a PR
> 
> The 7002 NS build is not added to twister, so, I don't think there is anything that needs to be done.

I posted links above, it is causing multiple issues in CI for completely unrelated PRs

**Comment by krish2718** [comment]
Raised PR https://github.com/zephyrproject-rtos/zephyr/pull/79615
