### ISSUE TITLE
Board nrf9131ek/nrf9131/ns fails to build minimal c library application

### ISSUE THREAD

**Issue by nordicjm** [zephyrproject-rtos/zephyr#78943]
**Describe the bug**
Board is failing to build sample as per log on https://github.com/zephyrproject-rtos/zephyr/actions/runs/10918300637/job/30303868974?pr=78621

**Expected behavior**
CI to not be broken

**Impact**
Showstopper, CI is broken on unrelated changes

@maxd-nordic please take a look

**Comment by maxd-nordic** [comment]
TF-M wasn't a possibility in upstream-zephyr when the board was added AFAIK.
Maybe a TF-M expert can help here?

**Comment by maxd-nordic** [comment]
Looks like ZRESTRICT is not defined.

**Comment by dkalowsk** [comment]
is this a regression?  @d3zd3z this is the second TF-M issue we're seeing this morning.  Is it possible a TF-M update went wonky?

**Comment by nordic-piks** [comment]
Triaged internally

**Comment by tomi-font** [comment]
This is not a TF-M issue. Fixed by https://github.com/zephyrproject-rtos/zephyr/pull/78991.
