### ISSUE TITLE
BAP/USR/STR/BV-369-C test fails. 

### ISSUE THREAD

**Issue by MicImbriani** [zephyrproject-rtos/zephyr#79059]
**Describe the bug**

The test BAP/USR/STR/BV-369-C fails. Looking at the traces, the ISO data being sent has payload 0, when it should instead be 40.

From my understanding, during the test procedure, PTS should send a MMI that would trigger hdl_wid_377. This would then in turn trigger the BTP_BAS_SEND callback in the tester app, which would fill up the ring buffer with the data. However, the MMI is not sent, and therefore the payload is 0. 
This lead to test failure.

Looking into the history of the test results reports:

- Test added: [week 33.7](https://lists.zephyrproject.org/g/Bluetooth-sig/message/1086?p=%2C%2C%2C20%2C0%2C0%2C0%3A%3ACreated%2C%2Cautopts+test+session%2C20%2C2%2C160%2C100846836)
- Test regressed: [week 39.6](https://lists.zephyrproject.org/g/Bluetooth-sig/message/1133?p=%2C%2C%2C20%2C0%2C0%2C0%3A%3ACreated%2C%2Cautopts+test+session%2C20%2C2%2C140%2C101672471)

The test has failed ever since. It was mistakenly marked to be related to the "[2nd CIS establishment issue](https://github.com/zephyrproject-rtos/zephyr/issues/60132)", but has now been corrected, as it is not affected by that issue.

**To Reproduce**

1. setup Zephyr environment and Auto PTS https://docs.zephyrproject.org/latest/connectivity/bluetooth/autopts/autopts-win10.html#setup-zephyr-project-for-windows
2. Build the auto pts tester app
3. Program the board
4. start the auto PTS server
5. Run the test case BAP/USR/STR/BV-369-C

**Expected behavior**

IUT starts CIS stream, PTS verifies its its content and test passes.

**Impact**

Zephyr Host conformance test fails. 

**Logs and console output**

PTS logs : [HERE](https://github.com/zephyrproject-rtos/bluetooth-qualification/tree/main/leaudio/autopts_report/pts_logs/BAP_USR_STR_BV_369_C_2024_10_13_05_40_33)
(EDIT: updated to latest Zephyr qualification run)

**Environment (please complete the following information):**

 - OS: (e.g. Linux, MacOS, Windows)
 - Toolchain (e.g Zephyr SDK, ...)
 - Commit SHA or Version used

**Additional context**

Toolchain Zephyr SDK
Zephyr Main - OS: Windows 10 
Commit SHA: eb98483769b5418969e25c87b2746cd5f05cc4cf

**Comment by henrikbrixandersen** [comment]
Please use our bug template when reporting bugs. You need to edit this issue to include the information requested in https://github.com/zephyrproject-rtos/zephyr/blob/main/.github/ISSUE_TEMPLATE/001_bug_report.md (e.g. how to reproduce, which subsystem this affects, ...).

**Comment by MicImbriani** [comment]
> Please use our bug template when reporting bugs. You need to edit this issue to include the information requested in https://github.com/zephyrproject-rtos/zephyr/blob/main/.github/ISSUE_TEMPLATE/001_bug_report.md (e.g. how to reproduce, which subsystem this affects, ...).

Hi Henrik. Apologies for omitting the information. I (mistakenly) assumed that this being an AutoPTS test, those information might be redundant. I updated the issue description now.
