### ISSUE TITLE
drivers: flash: simulator: fix address resolution

### ISSUE THREAD

**Issue by fgrandel** [zephyrproject-rtos/zephyr#79082]
**Describe the bug**

The flash simulator currently treats relative flash offsets as if they were absolute addresses. This didn't have an impact so far, because the base address is always zero when the flash simulator is used in practice.

Experimenting with non-zero offsets for the memory region revealed the error.

As I'm intending to support non-zero offsets for the flash simulator in a future PR, this bug should be fixed first.

PR with a fix follows.

**To Reproduce**

According to https://github.com/zephyrproject-rtos/zephyr/blob/24851026064d7912a9f91031e95ed71445842fd9/dts/bindings/mtd/fixed-partitions.yaml#L93

A fixed flash partition's `reg` address'...

> [...] is the offset of the flash partition **relative to the base address** of the parent memory.

In https://github.com/zephyrproject-rtos/zephyr/blob/24851026064d7912a9f91031e95ed71445842fd9/subsys/storage/flash_map/flash_map_default.c#L25

This _relative_ address of the partition is assigned to the `fa_off` member of `struct flash_area`.

The relative address is then propagated to the file system. In the case of the NVS settings backend and NVS, this is for example being done here:

https://github.com/zephyrproject-rtos/zephyr/blob/24851026064d7912a9f91031e95ed71445842fd9/subsys/settings/src/settings_nvs.c#L424

This offset is the base address for writes to the flash drivers, see e.g.

https://github.com/zephyrproject-rtos/zephyr/blob/24851026064d7912a9f91031e95ed71445842fd9/subsys/fs/nvs/nvs.c#L116

Which again is propagated verbatim to the flash driver:

https://github.com/zephyrproject-rtos/zephyr/blob/24851026064d7912a9f91031e95ed71445842fd9/include/zephyr/drivers/flash.h#L274

In the case of the flash simulator, however, the base address of the flash memory region is being **deduced** from the offset as if the offset was an **absolute** address, see for example here

https://github.com/zephyrproject-rtos/zephyr/blob/24851026064d7912a9f91031e95ed71445842fd9/drivers/flash/flash_simulator.c#L241

and here

https://github.com/zephyrproject-rtos/zephyr/blob/24851026064d7912a9f91031e95ed71445842fd9/drivers/flash/flash_simulator.c#L51

**Expected behavior**

The flash simulator should treat relative addresses as relative to the base address rather than as absolute addresses.

**Impact**

Illegal addresses are being accessed (page fault, mem fault) with a non-zero flash memory-region base address.

**Logs and console output**

n/a (processor halts)

**Environment (please complete the following information):**

all

**Additional context**

n/a

**Comment by de-nordic** [comment]
Setting severity to low: it has been forever and nobody have noticed before so I guess that customer impact is not severe.
