### ISSUE TITLE
Bluetooth: Audio: Change dependency of BT_BAP_SCAN_DELEGATOR to GATT_DYNAMIC_DB from 'select' to 'depends on'

### ISSUE THREAD

**Issue by babrsn** [zephyrproject-rtos/zephyr#79108]
**Is your enhancement proposal related to a problem? Please describe.**

Currently, in `subsys/bluetooth/audio/Kconfig.bap`, `BT_BAP_SCAN_DELEGATOR` uses `select` to manage its dependency on `GATT_DYNAMIC_DB`. The `select` mechanism can create issues because it forces the selection of certain options without checking if those dependencies are met. This can lead to configurations that are invalid or unexpected.

**Describe the solution you'd like**

I propose changing the dependency management of `BT_BAP_SCAN_DELEGATOR` from `select` to `depends on`. Using `depends on` ensures that the dependency on `GATT_DYNAMIC_DB` is only satisfied if it has already been selected or enabled elsewhere, thus preventing the automatic selection that can lead to invalid configurations. This approach promotes better modularity and clarity in configuration management.

**Describe alternatives you've considered**

One option is to retain the current configuration using `select`, perhaps with enhanced documentation to explain its use and implications. However, this approach does not eliminate the risk of generating invalid configurations.

**Additional context**

This change might introduce a dependency loop, which will need to be carefully investigated and resolved. Ensuring that dependencies are correctly managed without loops is crucial for maintaining a stable and predictable build system. Further testing and validation will be required to ensure that this change does not negatively impact other parts of the system.

**Comment by Thalley** [comment]
@babrsn Please follow the templates when creating issues:

```
**Is your enhancement proposal related to a problem? Please describe.**
<!--
A clear and concise description of what the problem is.
-->

**Describe the solution you'd like**
<!--
A clear and concise description of what you want to happen.
-->

**Describe alternatives you've considered**
<!--
A clear and concise description of any alternative solutions or features you've considered.
-->

**Additional context**
<!--
Add any other context or graphics (drag-and-drop an image) about the feature request here.
-->
```

**Comment by babrsn** [comment]
> @babrsn Please follow the templates when creating issues:
> 
> ```
> **Is your enhancement proposal related to a problem? Please describe.**
> 
> 
> **Describe the solution you'd like**
> 
> 
> **Describe alternatives you've considered**
> 
> 
> **Additional context**
> 
> ```

The issue description has been updated to follow the template.

**Comment by babrsn** [comment]
@Thalley please assign it to @babrsn
