### ISSUE TITLE
Bluetooth: Audio:  BAP Broadcast Assistant fails on broadcast_id = 0x000000

### ISSUE THREAD

**Issue by larsgk** [zephyrproject-rtos/zephyr#79189]
**Describe the bug**
With a broadcast ID of 0x000000, the BAP Broadcast Assistant fails validity check for broadcast_id.

The issue seems that on reset, broadcast_id gets set to 0 and later comparison with a broadcast ID of 0x000000 then get's faulty detected as "already added".

**To Reproduce**
Add a broadcast source with broadcast ID 0x000000

**Expected behavior**
The broadcast source is added to the connected sink.

**Impact**
Although unlikely (1 of 2^24 combinations), broadcast ID = 0x000000 can't be added.

**Logs and console output**
N/A

**Suggested solution**
Assign a value higher than 0xFFFFFF (largest broadcast ID) to broadcast_id on reset.

**Comment by Thalley** [comment]
@larsgk Please use the bug template when reporting bugs. Please update this bug report to contain the requested information
