### ISSUE TITLE
Function usbd_ep_ctrl_set_zlp() works incorrect for devices with MPS != 64

### ISSUE THREAD

**Issue by kasjer** [zephyrproject-rtos/zephyr#79194]
**Describe the bug**
For devices that have *EP0 MPS < 64* function `usbd_ep_ctrl_set_zlp()` will not
set zlp bit when all data was already sent and ZLP is required by host.

```c
static void usbd_ep_ctrl_set_zlp(struct usbd_context *const uds_ctx,
				 struct net_buf *const buf)
   ...
	if (setup->wLength > min_len && !(min_len % USB_CONTROL_EP_MPS)) { // !! Offending line
```
Definition of USB_CONTROL_EP_MPS is hardcoded this way
```c
#define USB_CONTROL_EP_MPS		64U
```

This was discovered during implementation #79184 of UDC driver for Smartbond #74662 .

Sample `samples/subsys/usb/mass` that triggers error since it generates 32 bytes long
descriptor.

It can also be triggered if other descriptors (like string descriptors) have length `8 * n`.

I think it can be also tested on other boards if MPS is artificially change to be 8 (this scenario was
tested on previous USB stack on STM32 devices that are capable to be configured
with EP0 MPS < 64.

**To Reproduce**

```sh
west build -b da1469x_dk_pro samples/subsys/usb/mass -DEXTRA_DTC_OVERLAY_FILE="ramdisk.overlay" -DCONFIG_APP_MSC_STORAGE_RAM=y -DCONF_FILE="usbd_next_prj.conf"
```

**Impact**

Devices with EP0 MPS < 64 will not work (This applies to Smartbond and some other device)

**Environment:**

 - OS: any
 - Commit SHA or Version used: 2815b6d710ad9c7ba25725ae34c402fc9153c427

**Comment by jfischer-no** [comment]
> Just a note that this issue is a **blocker** for #74662

Do not panic, the fix is underway.
