### ISSUE TITLE
West runner command doesn't work for em-starterkit

### ISSUE THREAD

**Issue by ruuddw** [zephyrproject-rtos/zephyr#7927]
debug and flash commands for em-starterkit generate an error:

 Using runner: em-starterkit
 fatal error: command debug cannot be run in this context: Runner em-starterkit received unknown arguments ['']

parse_known_args() returns a list with an empty string instead of an empty list. No idea if this is ok and the check should be changed, or something else should be fixed...
See:
https://github.com/zephyrproject-rtos/zephyr/blob/f3f767a2ae276fc6a12fbec1ca8fca312b80342d/scripts/meta/west/cmd/run_common.py#L209

**Comment by nashif** [comment]
@mbolivar ping
