### ISSUE TITLE
arch: riscv: the `s0` dumped during a fatal error is not correct

### ISSUE THREAD

**Issue by ycsin** [zephyrproject-rtos/zephyr#79298]
**Describe the bug**
The content of the `s0` register dump during a fatal error is not the one at the time of the crash. On exception the `isr.S`, made a copy of the `s0` register and then made some changes to the reg, but it didn't restore the `s0` to the saved value before it jumps to the `z_riscv_fatal_error_csf()`.

**To Reproduce**
1. Run the test added in #79096 with Zephyr v3.7-branch
2. The test will fail

**Expected behavior**
The test should pass

**Impact**
Incorrect `s0` content shown in the fatal error message

**Comment by fkokosinski** [comment]
I believe this one should have been closed automaically when #79299 and #79096 were merged.
