### ISSUE TITLE
Documentation references non existing file: llext/shell_loader/README.rst

### ISSUE THREAD

**Issue by markus-becker-tridonic-com** [zephyrproject-rtos/zephyr#79318]
**Describe the bug**

https://github.com/zephyrproject-rtos/zephyr/blob/main/samples/subsys/llext/shell_loader/README.rst references to a file tests/subsys/llext/hello_world/hello_world.c, which is not existent anymore. Possibly it is now samples/subsys/llext/modules/src/hello_world_ext.c .

**To Reproduce**

**Impact**

LLEXT shell loader sample cannot be used.

**Logs and console output**
N/A

**Environment (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by teburd** [comment]
Thanks for reporting, I am working on this
