### ISSUE TITLE
drivers: can: stm32_can: bitrate ignored

### ISSUE THREAD

**Issue by karstenkoenig** [zephyrproject-rtos/zephyr#7933]
The CAN peripheral prescaler is not calculated based on the bitrate passed in or overridden if not passed in, but always on cfg->bus_speed

Also the can.h interface doesn't really specify that bitrate can be zero and will then be overridden with a value from dts or kconfig, not sure if that matters

https://github.com/zephyrproject-rtos/zephyr/blob/8364b223e485c331f99c0c55c8064bce80dd857e/drivers/can/stm32_can.c#L165

**Comment by karstenkoenig** [comment]
ping @alexanderwachter as the author

**Comment by alexanderwachter** [comment]
Thats a bug. Sorry for that. I will korrekt it in my next rework PR.
Thanks for that!

**Comment by MaureenHelm** [comment]
Fixed by #8001
