### ISSUE TITLE
Nominate myself as Contributor

### ISSUE THREAD

**Issue by rettichschnidi** [zephyrproject-rtos/zephyr#79402]
# Background

The [TSC Project Roles] defines the main roles for the Zephyr Project, including
Maintainer, Collaborator, and Contributor.

By default anyone that contributes code or documentation is a Contributor, but
with the lowest [GitHub Permission Level] of Read. For example, Contributors
with Read permission do not have the permission to add reviewers to a pull
request.

Use this template to nominate a GitHub user for the Contributor role with
Triage permission level, which allows the user to add reviewers to a pull
request and be added as a reviewer by other users.

# Nomination

## GitHub User

Provide the following information about the GitHub user:

1. Reto Schneider
1. rettichschnidi
1. Gardena GmbH (part of Husqvarna AB)

## Supporting Documents

Add links to 3-5 GitHub pull requests, in the Zephyr project, authored or
reviewed by the GitHub user that demonstrate the user's dedication to the
Zephyr project.

* #78253
* #76677
* #79401
* #17005
* #18473

[TSC Project Roles]: <https://docs.zephyrproject.org/latest/project/project_roles.html>
[GitHub Permission Level]: <https://docs.github.com/en/organizations/managing-access-to-your-organizations-repositories/repository-roles-for-an-organization>

**Comment by stephanosio** [comment]
@rettichschnidi I noticed that you are already listed in `MAINTAINERS.yml`. I have added you to the relevant GitHub teams.
