### ISSUE TITLE
kernel: Missing calloc equivalent funciton

### ISSUE THREAD

**Issue by sorru94** [zephyrproject-rtos/zephyr#79417]
**Is your enhancement proposal related to a problem? Please describe.**
The Zephyr kernel contains various allocation functions: `k_heap_alloc`, `k_heap_realloc`, `k_heap_free`, etc.
Those can be seen as wrappers to the standard C functions `malloc`, `realloc`, `free`, etc.
However, there is no equivalent function to `calloc`.

**Describe the solution you'd like**
An additional allocation function could be added alongside the already present ones.

**Comment by jukkar** [comment]
There is `k_calloc`
