### ISSUE TITLE
Blobs: Add support to pull in NXP MCXW71 NBU binary blob

### ISSUE THREAD

**Issue by mmahadevan108** [zephyrproject-rtos/zephyr#79431]
## Origin
The following binary blob is being added:
`mcxw71/mcxw71_nbu_ble.sb3`

## Type

- [ ] Precompiled library
- [X] Firmware image

## Module

hal_nxp: [https://github.com/zephyrproject-rtos/hal_nxp/](https://github.com/zephyrproject-rtos/hal_nxp)

## Purpose

Precompiled firmware (binary blob) supporting BLE on NXP MCXW71 SoC.

## Pull Request

HAL: https://github.com/zephyrproject-rtos/hal_nxp/pull/445

## Dependencies

None

## License

[LA_OPT_NXP_Software_License](https://github.com/zephyrproject-rtos/hal_nxp/blob/master/zephyr/blobs/license/LA_OPT_NXP_Software_License.txt)
Some parts of this license is being updated as part of the above HAL PR.

**Comment by dleach02** [comment]
TSC approved on 10/23/2024
