### ISSUE TITLE
Nominate myself as contributor

### ISSUE THREAD

**Issue by JarmouniA** [zephyrproject-rtos/zephyr#79450]
# Nomination

## GitHub User

Provide the following information about the GitHub user:

1. Full Name: Abderrahmane JARMOUNI
1. GitHub username: JarmouniA
1. Organization (optional)

## Supporting Documents

Add links to 3-5 GitHub pull requests, in the Zephyr project, authored or reviewed by the GitHub user that demonstrate the user's dedication to the Zephyr project.

Merged PRs: #77854, #77950, #78448, #75284, #79437
Reviewed PRs: #77949, #78171, #78725
Previously, I was a contributor & a STM32 collaborator with my work account (@ajarmouni-st).

**Comment by erwango** [comment]
I support the request.
