### ISSUE TITLE
Wrong Assertion in sensor.h

### ISSUE THREAD

**Issue by mirkobeckerPxC** [zephyrproject-rtos/zephyr#79550]
This `__ASSERT(cqe->userdata != buf,
		 "consumed non-matching completion for sensor read into buffer %p\n", buf);` should be changed to `__ASSERT(cqe->userdata == buf,
		 "consumed non-matching completion for sensor read into buffer %p\n", buf);`

https://github.com/zephyrproject-rtos/zephyr/blob/41e4b5323ac3888c45763ed7574c892cf3907fb5/include/zephyr/drivers/sensor.h#L1067

**Comment by henrikbrixandersen** [comment]
Please use our bug template when reporting bugs. You need to edit this issue to include the information requested in https://github.com/zephyrproject-rtos/zephyr/blob/main/.github/ISSUE_TEMPLATE/001_bug_report.md

**Comment by fabiobaltieri** [comment]
Hey @mirkobeckerPxC, could you open a pull request with the fix? The contribution guideline is https://docs.zephyrproject.org/latest/contribute/guidelines.html#contribution-guidelines. Thanks!
