### ISSUE TITLE
Bluetooth: BAP: Allow for static broadcast_id for broadcast sources

### ISSUE THREAD

**Issue by Thalley** [zephyrproject-rtos/zephyr#79600]
**Is your enhancement proposal related to a problem? Please describe.**
BAP 1.0.2 allows for broadcast source to reuse the broadcast ID instead of generating a new one each time a BIG is created. This also removes the requirement that the broadcast ID shall be randomly generated, and can be set to any value, as long as each BIG has a unique broadcast ID.

**Describe the solution you'd like**
`bt_bap_broadcast_source_create` should no longer call `generate_broadcast_id` and assign a broadcast ID to a broadcast source object. 

Instead we can either

1. Have the application control the broadcast ID. That means removing the broadcast ID completely from the stack for the broadcast source (including removing `bt_bap_broadcast_source_get_id`). The application would be in charge of ensuring that the broadcast IDs are unique. 
2. Add `broadcast_id` as a parameters to `bt_bap_broadcast_source_create` so that the `broadcast_id` is assigned to a broadcast source so that the stack can help ensure uniqueness. 

Since the `broadcast_id` is only used for advertisement data, which the application fully controls, then option 1. may be better than option 2., as we cannot ensure that the application correctly uses the broadcast ID in the advertisement data anyhow. 

We can keep `generate_broadcast_id` and make it public as a way to help generate broadcast IDs, but that will only really work if option 2. is implemented, as we cannot ensure uniqueness otherwise. 

**Describe alternatives you've considered**
N/A

**Additional context**
These are changes from BAP 1.0.1 to BAP 1.0.2

**Comment by kruithofa** [comment]
After discussion Emil and I concluded that option 1 makes most sense.
- use of broadcast_id is out of our controll already
- option 1 saves memory in the stack

whereas we see no advantages for option 2.
