### ISSUE TITLE
HTTP server causes assertion failure when uploading large files via POST

### ISSUE THREAD

**Issue by madscientist159** [zephyrproject-rtos/zephyr#79625]
**Describe the bug**
The Zephyr HTTP server throws an assertion failure when uploading large (roughly 1MB or larger) files via HTTP POST.

**To Reproduce**
Register a dynamic page for the HTTP server, and use an HTML form to upload a binary file (e.g. a firmware image) via POST to that dynamic page.

**Expected behavior**
HTTP dynamic page callbacks should be called repeatedly until the file has been received, and no assertions should be thrown.

**Impact**
Makes firmware upload unusable in one of our applications.

**Logs and console output**
`ASSERTION FAIL [((header_field_mark ? 1 : 0) + (header_value_mark ? 1 : 0) + (url_mark ? 1 : 0) + (body_mark ? 1 : 0) + (status_mark ? 1 : 0)) <= 1] @ ZEPHYR_BASE/subsys/net/lib/http/http_parser.c:2225`

**Environment (please complete the following information):**

 - OS: Linux
 - Toolchain: Debian 12
 - Commit SHA or Version used: Zephyr 3.7.0

**Additional context**
The assertion is not always hit, but the probability grows with file size.

**Comment by jukkar** [comment]
Would you be able to provide a minimal application that shows the issue, the assertion seems to suggest an issue in received data or parsing of it?
Just to clarify the version, did you see the issue in 3.7 or in latest upstream?

**Comment by rlubos** [comment]
I think we need some hint here, I've tried to reproduce this with `http_server` sample on qemu_x86, no success neither on current `main`, nor on `v3.7-branch`.

**Comment by rlubos** [comment]
I've tried to reproduce on real hw (`nucleo_h723zg`) on 3.7 branch, asserts on, still no luck reproducing though...
Perhaps would be good to check if it's still reproducible on Zephyr 4.0.0 as the release is now out.

**Comment by carlescufi** [comment]
Closing as this cannot be reproduced. Please reopen if you have a means to reproduce it.
