### ISSUE TITLE
Introduce STM32WB0x Binary BLOB to provide BLE controller

### ISSUE THREAD

**Issue by HoZHel** [zephyrproject-rtos/zephyr#79652]
## Origin

The following binary BLOB is introduced:

1- stm32wb0x_ble_stack_controller_only.a

The origin of this binary BLOB is the STMicroelectronics STM32WB0 Cube package repository: https://github.com/STMicroelectronics/STM32CubeWB0/raw/v1.0.0/Middlewares/ST/STM32_BLE/stack/lib/

## Type

- [x] Precompiled library
- [ ] Firmware image

## Module

hal_stm32: https://github.com/zephyrproject-rtos/hal_stm32/

## Purpose

Precompiled static library (binary BLOB) which provides BLE controller functionality on STM32WB0x based boards.

## Pull Request

Zephyr: https://github.com/zephyrproject-rtos/zephyr/pull/79734
hal_stm32: https://github.com/zephyrproject-rtos/hal_stm32/pull/236

## Dependencies

None

## License

Blobs is licensed using STMicroeletronics "ULTIMATE LIBERTY SOFTWARE LICENSE". License text is available [here](https://github.com/STMicroelectronics/STM32CubeWB0/blob/v1.0.0/Middlewares/ST/STM32_BLE/LICENSE.md) and provided in hal_stm32 PR.

**Comment by erwango** [comment]
Approved by TSC (25/10/24)
