### ISSUE TITLE
tests: drivers: sensor: temp_sensor: drivers.sensor.temp_sensor fails on nrf54h20

### ISSUE THREAD

**Issue by nordic-piks** [zephyrproject-rtos/zephyr#79701]
**Describe the bug**
The tests:
- tests/drivers/sensor/temp_sensor/drivers.sensor.temp_sensor

Observed for
- nrf54h20dk/nrf54h20/cpuap

**To Reproduce**
1. have nrf54h20dk/nrf54h20/cpuap connected
2. go to your zephyr dir
3. call ./scripts/twister -T  tests/drivers/sensor/temp_sensor -p nrf54h20dk/nrf54h20/cpuapp --device-testing --device-serial /dev/ttyACM0 -v --inline-logs
4. See console output with error

**Expected behavior**
Valid console output

**Impact**
Not clear

**Logs and console output**
```
**ASSERTION FAIL [len <= sizeof(rx_buffer)] @ ../../../../../../../../../../zephyr/zephyr/subsys/ipc/ipc_service/lib/icmsg.c:190
E: r0/a1:  0x00000004  r1/a2:  0x000000be  r2/a3:  0x00000000
E: r3/a4:  0x00000004 r12/ip:  0x00000001 r14/lr:  0x0e0a8129
E:  xpsr:  0x21000000
E: Faulting instruction address (r15/pc): 0x0e0b04f6
E: >>> ZEPHYR FATAL ERROR 4: Kernel panic on CPU 0
E: Current thread: 0x2f0119a8 (icmsg_workq)
E: Halting system
```
There are expected ping/pong messages.

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04.1 LTS
 - Toolchain Zephyr SDK 0.16.8
 - Commit SHA or Version used: v3.7.0-4183-g66ff30efb4d7

**Comment by anangl** [comment]
This assertion (or another one in the test itself) starts to fail with 022122d659a7c10180b8a91c6a0b49874f2850fa, but the problem disappears when the SysCtrl firmware is updated accordingly. Thus, there's nothing to be fixed here.
