### ISSUE TITLE
DTS files should not directly contain #define

### ISSUE THREAD

**Issue by ajf58** [zephyrproject-rtos/zephyr#79719]
Taken from https://github.com/zephyrproject-rtos/zephyr/pull/77368

> We should not use Kconfig symbols in DTS. We also should not use `#define`. Instead, include a `dt-bindings` header including the definitions.

_Originally posted by @henrikbrixandersen in https://github.com/zephyrproject-rtos/zephyr/pull/77368#discussion_r1796795293_

A quick grep of the codebase suggests that this happens a lot. If this is not correct, then it needs fixing in a number of places.

**Comment by Tarangraval21** [comment]
Hi @henrikbrixandersen , Could you assign this task to me? I will take care of creating the dt-bindings header and fix this
