### ISSUE TITLE
nrf9131ek/nrf9131 CI failure with Device initialization priority validation failed

### ISSUE THREAD

**Issue by nordicjm** [zephyrproject-rtos/zephyr#79772]
**Describe the bug**
Board CI failing, see: https://github.com/zephyrproject-rtos/zephyr/actions/runs/11322012174/job/31482120728?pr=78621

**Expected behavior**
Board to work

**Impact**
Showstopper

@maxd-nordic @aasinclair

**Comment by maxd-nordic** [comment]
These tests are failing:
drivers.eeprom.emul.build
drivers.eeprom.build

Now, what makes eeprom tests fail on a board without eeprom?

**Comment by maxd-nordic** [comment]
/soc/peripheral@50000000/i2c@a000/npm1300@6b/charger <npm1300_charger_init> is initialized before its dependency /soc/peripheral@50000000/i2c@a000/npm1300@6b <mfd_npm1300_init>

**Comment by maxd-nordic** [comment]
charger is sensor priority and the mfd device has its own prio.

**Comment by maxd-nordic** [comment]
This patch could fix it:
```
diff --git a/tests/drivers/build_all/eeprom/boards/nrf9131ek_nrf9131.conf b/tests/drivers/build_all/eeprom/boards/nrf9131ek_nrf9131.conf
new file mode 100644
index 00000000000..cbe703cf555
--- /dev/null
+++ b/tests/drivers/build_all/eeprom/boards/nrf9131ek_nrf9131.conf
@@ -0,0 +1 @@
+CONFIG_MFD_INIT_PRIORITY=55
```

**Comment by maxd-nordic** [comment]
@nordicjm This fails because this PR https://github.com/zephyrproject-rtos/zephyr/pull/79138 messes with the sensor priority. Maybe you can add the above change to https://github.com/zephyrproject-rtos/zephyr/pull/78621 to fix CI since you are already changing nrf9131ek.

**Comment by nordicjm** [comment]
@masz-nordic now a new build error: https://github.com/zephyrproject-rtos/zephyr/actions/runs/11324295360/job/31492031631?pr=78621

**Comment by maxd-nordic** [comment]
> @masz-nordic now a new build error: https://github.com/zephyrproject-rtos/zephyr/actions/runs/11324295360/job/31492031631?pr=78621

I recommend this change:
```
diff --git a/drivers/regulator/regulator_npm1300.c b/drivers/regulator/regulator_npm1300.c
index 8adb2d3cb81..aa99cafb725 100644
--- a/drivers/regulator/regulator_npm1300.c
+++ b/drivers/regulator/regulator_npm1300.c
@@ -581,7 +581,7 @@ static int soft_start_set(const struct device *dev, uint8_t soft_start)
 int regulator_npm1300_init(const struct device *dev)
 {
        const struct regulator_npm1300_config *config = dev->config;
-       bool enabled;
+       bool enabled = false;
        int ret = 0;
 
        if (!device_is_ready(config->mfd)) {
```

**Comment by nordicjm** [comment]
> > @masz-nordic now a new build error: https://github.com/zephyrproject-rtos/zephyr/actions/runs/11324295360/job/31492031631?pr=78621
> 
> I recommend this change:
> 
> ```
> diff --git a/drivers/regulator/regulator_npm1300.c b/drivers/regulator/regulator_npm1300.c
> index 8adb2d3cb81..aa99cafb725 100644
> --- a/drivers/regulator/regulator_npm1300.c
> +++ b/drivers/regulator/regulator_npm1300.c
> @@ -581,7 +581,7 @@ static int soft_start_set(const struct device *dev, uint8_t soft_start)
>  int regulator_npm1300_init(const struct device *dev)
>  {
>         const struct regulator_npm1300_config *config = dev->config;
> -       bool enabled;
> +       bool enabled = false;
>         int ret = 0;
>  
>         if (!device_is_ready(config->mfd)) {
> ```

Can you submit a PR with this? It's no longer holding my PRs up, but the board is currently broken

**Comment by maxd-nordic** [comment]
https://github.com/zephyrproject-rtos/zephyr/pull/80159

**Comment by nordic-auko** [comment]
@nordicjm this warning should be fixed no with https://github.com/zephyrproject-rtos/zephyr/pull/80276
