### ISSUE TITLE
ARC_INIT is set on boards that don't have it, triggering Kconfig warnings

### ISSUE THREAD

**Issue by ulfalizer** [zephyrproject-rtos/zephyr#7977]
The `ARC_INIT` symbol is only defined on the `intel_quark` SoC (see the [symbol reference](http://docs.zephyrproject.org/reference/kconfig/CONFIG_ARC_INIT.html#cmdoption-arg-config-arc-init)), but is set by `samples/subsys/ipc/ipm_mailbox/ap/prj.conf`, giving a Kconfig warning for assigning an undefined symbol on these boards:

```
qemu_xtensa
qemu_riscv32
native_posix
qemu_nios2
frdm_k64f
qemu_cortex
lpcxpresso54114_m0
bbc_microbit
```

Should I just whitelist `ARC_INIT` warnings (about to turn many warnings into errors), or is there something worthwhile to do here?

**Comment by SebastianBoe** [comment]
This is a bug in the sample.yaml file.

This sample only runs on the intel_quark SoC.

This should have been enforced by 

```
tests:
  test:
    filter: CONFIG_SOC_QUARK_SE_C1000
    tags: samples ipm

```

I can't explain why it isn't.

**Comment by SebastianBoe** [comment]
Ah, I see @nashif has explained this.

sanitycheck runs kconfig (indirectly I assume) to determine if CONFIG_SOC_QUARK_SE_C1000 is set. When it does this, it causes a configuration error.

**Comment by ulfalizer** [comment]
Wonder if `platform_whitelist` would help here, similar to the fix in https://github.com/zephyrproject-rtos/zephyr/pull/8344/commits/eafcba56675200d65f6e83d4db8a1547f0215528.
