### ISSUE TITLE
drivers: dma: dma_cavs: DMA driver does not support per-channel callbacks

### ISSUE THREAD

**Issue by sathishkuttan** [zephyrproject-rtos/zephyr#7979]
The current driver `drivers/dma/dma_cavs.c` allows DMA completion callback functions to be one per device.
Since each DMA device has 8 channels with each channel potentially used by different peripheral drivers, the DMA driver should instead allow registration of completion callback function for each channel.

**Comment by tbursztyka** [comment]
Added this issue to #5697
