### ISSUE TITLE
Percepio Tracelyzer is not working for zephyr 3.6.0

### ISSUE THREAD

**Issue by rahulprajapati-eaton** [zephyrproject-rtos/zephyr#79803]
Recently, I updated Zephyr to version 3.6.0 and started facing issues with Percepio Tracealyzer. Previously, it was working fine with Zephyr 3.2.0. Below are the configurations I added to my application:
```
CONFIG_TRACING=y
CONFIG_PERCEPIO_TRACERECORDER=y
```
When I tried to test, I encountered the error in percepio tracelyzer connection.

I want use Percepio Tracealyzer in snapshot mode.

**Comment by nashif** [comment]
you should open a bug using the bug template

**Comment by bdijkstra82** [comment]
What is the error that you encountered?

**Comment by dkalowsk** [comment]
More details will be needed to resolve the issue.  Please use the template as requested already.

**Comment by rahulprajapati-eaton** [comment]
I have enable this config
![image](https://github.com/user-attachments/assets/58fb6d7f-f304-4a41-a0d0-c953c472f4f6)
and got this error
![image](https://github.com/user-attachments/assets/0451b8a2-e643-4af0-acf0-6931cb9ec3f9)

**Comment by rahulprajapati-eaton** [comment]
I clone zephyr and its module again and issue got resolved. It's look like some module was not installed properly. Now everything working fine.

**Comment by bdijkstra82** [comment]
Probably the Segger module wasn't installed probably. It defines `HAS_SEGGER_RTT`. Note that if you want to use snapshots, you should have
`PERCEPIO_TRC_CFG_STREAM_PORT=PERCEPIO_TRC_CFG_STREAM_PORT_RINGBUFFER`
