### ISSUE TITLE
Kconfig.defconfig.apollo4p:13: error: couldn't parse 'default $(dt_node_reg_size_int,$(DT_NODE_SRAM),1,K)': macro expanded to blank string

### ISSUE THREAD

**Issue by ziqi-zhou02** [zephyrproject-rtos/zephyr#79804]
**Describe the bug**
Followed instructions to install nRF command line tools + nRF connect + VS Code Extensions.
OS: Mac Sonoma 14.5
Errors when building:
`soc/arm/ambiq/apollo4x/Kconfig.defconfig.apollo4p:13: error: couldn't parse 'default $(dt_node_reg_size_int,$(DT_NODE_SRAM),1,K)': macro expanded to blank string`

![image](https://github.com/user-attachments/assets/d3ec023b-ad1d-4b61-b753-b10cefa8ece9)

**To Reproduce**

**Expected behavior**

**Impact**

**Logs and console output**

**Environment (please complete the following information):**

 - OS: (e.g. Linux, MacOS, Windows)
 - Toolchain (e.g Zephyr SDK, ...)
 - Commit SHA or Version used

**Additional context**

**Comment by dkalowsk** [comment]
Can you reproduce this with a `west build` without using NRF?  Otherwise this likely needs to be routed to the Nordic folks for any solution.

**Comment by CocoaBob** [comment]
I suddenly have the same issue, and I didn't change anything in the project...
<img width="1202" alt="image" src="https://github.com/user-attachments/assets/db5b5a33-cd0e-4989-bbc8-d3650311a94c">

**Comment by CocoaBob** [comment]
Okay, find the solution from Nordic DevZone https://devzone.nordicsemi.com/f/nordic-q-a/114672/zephyr-compile-error-after-unknown-update, roll back `nRF Kconfig` to **v2024.6.20** solves the problem. I think we could close the ticket for now.
