### ISSUE TITLE
intel_adsp_cavs25 and intel_adsp_ace15/20/30: tests/drivers/comparator/shell/drivers.comparator.shell fails.

### ISSUE THREAD

**Issue by pkunieck** [zephyrproject-rtos/zephyr#79918]
**Describe the bug**
The tests/drivers/comparator/shell/drivers.comparator.shell fails with timeout on:
 - intel_adsp/ace15_mtpm
 - intel_adsp/ace15_mtpm/sim
 - intel_adsp/ace20_lnl
 - intel_adsp/ace20_lnl/sim
 - intel_adsp/ace30/ptl/sim
 - intel_adsp/cavs25

**To Reproduce**
scripts/twister -W -p intel_adsp_cavs25 --device-testing --hardware-map <path_to>/cavs/cavs.map -T tests/drivers/comparator/shell/ -v

**Logs and console output**
Log attached from run on intel_adsp_cavs25.
```
*** Booting Zephyr OS build v3.7.0-4463-g03959a20f783 (delayed boot 500ms) ***
Running TESTSUITE comparator_shell
===================================================================
START - test_await_trigger
ASSERTION FAIL [arch_mem_coherent(sync)] @ WEST_TOPDIR/os.rtos.zephyr.zephyr/kernel/work.c:1072
E:  ** FATAL EXCEPTION
E:  ** CPU 0 EXCCAUSE 63 (zephyr exception)
E:  **  PC 0xbe015caf VADDR 0
E:  **  PS 0x60420
E:  **    (INTLEVEL:0 EXCM: 0 UM:1 RING:0 WOE:1 OWB:4 CALLINC:2)
E:  **  A0 0xbe012a64  SP 0xbe025ca0  A2 0x4  A3 0x9e02a77c
E:  **  A4 0  A5 0x60020  A6 0x1  A7 0x1b
E:  **  A8 0x1  A9 0xbe025c20 A10 0x1 A11 0
E:  ** A12 0x9e02a0d8 A13 0x25 A14 0x4 A15 0x10
E:  ** LBEG 0xbe01e04c LEND 0xbe01e057 LCOUNT 0
E:  ** SAR 0
E:  **  THREADPTR 0xaaaaaaaa


Backtrace:0xbe015cac:0xbe025ca0 0xbe012a61:0xbe025cb0 0xbe0196f9:0xbe025cd0 0xbe011c2c:0xbe025d00 0xbe016e39:0xbe025d50 0xbe012a53:0xbe025d70 

E: >>> ZEPHYR FATAL ERROR 4: Kernel panic on CPU 0
E: Current thread: 0x9e02a0d8 (test_await_trigger)
E: Halting system
```
**Environment (please complete the following information):**

 - OS: Linux
 - Zephyr version: v3.7.0-4463-g03959a20f783

**Comment by bjarki-andreasen** [comment]
no idea what coherent memory means, but its looks like the intel platform requires the k_work_sync be defined in some special way to make it coherent, see https://github.com/zephyrproject-rtos/zephyr/blob/8c705cabab8ad3eb66949f97b862f3da9f708455/tests/drivers/comparator/shell/src/test.c#L148

maybe someone can propose a solution to make it coherent
