### ISSUE TITLE
Nominate myself as Contributor

### ISSUE THREAD

**Issue by M1cha** [zephyrproject-rtos/zephyr#79928]
# Background

# Nomination

## GitHub User

Provide the following information about the GitHub user:

1. Michael Zimmermann
2. M1cha

## Supporting Documents
- https://github.com/zephyrproject-rtos/zephyr/pull/76677
- https://github.com/zephyrproject-rtos/zephyr/pull/78695
- https://github.com/zephyrproject-rtos/zephyr/pull/78696
- https://github.com/zephyrproject-rtos/zephyr/pull/79401

**Comment by stephanosio** [comment]
@M1cha has been added to the Collaborator team as per [MAINTAINERS.yml](https://github.com/zephyrproject-rtos/zephyr/blob/8c705cabab8ad3eb66949f97b862f3da9f708455/MAINTAINERS.yml#L3544).
