### ISSUE TITLE
Bluetooth: Shell: User input validation

### ISSUE THREAD

**Issue by ekleezg** [zephyrproject-rtos/zephyr#80012]
In the function `bt_mesh_comp_p1_elem_pull`,

```
struct bt_mesh_comp_p1_elem *bt_mesh_comp_p1_elem_pull(struct net_buf_simple *buf,
						       struct bt_mesh_comp_p1_elem *elem)
{
	if (buf->len < 4) {
		LOG_DBG("No more elements to pull or missing data");
		return NULL;
	}
	size_t elem_size = 0;
	uint8_t header, ext_item_cnt;
	bool fmt, cor_present;
	int i;

	elem->nsig = net_buf_simple_pull_u8(buf);
	elem->nvnd = net_buf_simple_pull_u8(buf);
	for (i = 0; i < elem->nsig + elem->nvnd; i++) {
		header = buf->data[elem_size];
```

 there is no validation of `elem->nsig` and `elem->nvnd` against `buf->len`, which can result in referencing memory outside of `buf->data`.

It doesn't seem to be a security issue, but improving it would help prevent bugs.

**Comment by jhedberg** [comment]
I took a quick look at `cfg_cli.c`, and there seems to be similar checks missing in other places too (e.g. `bt_mesh_comp_p1_item_pull()`).
