### ISSUE TITLE
Cannot retry fs mount command if first attempt failed

### ISSUE THREAD

**Issue by pahindman** [zephyrproject-rtos/zephyr#80024]
**Describe the bug**

When using the `fs mount littlefs` command, the command may fail, typically due to a typo in the mount point name.  Unfortunately, once this happens it cannot be used again until resetting Zephyr.

**To Reproduce**

Steps to reproduce:
```
uart:~$ fs mount littlefs invalid_mount_point
Error mounting as littlefs: -22
uart:~$ fs ls
uart:~$ fs mount littlefs /mount_point
uart:~$ fs ls
uart:~$
```

**Expected behavior**

```
uart:~$ fs mount littlefs invalid_mount_point
Error mounting as littlefs: -22
uart:~$ fs ls
uart:~$ fs mount littlefs /mount_point
uart:~$ fs ls
mount_point/
uart:~$
```

**Impact**

It's a minor annoyance.  I've fixed it locally, and plan on posting a PR shortly.

**Logs and console output**

**Environment (please complete the following information):**

 - OS: Ubuntu
 - Toolchain: Zephyr SDK
 - Commit SHA or Version used: 2bfc2a3cc57f37a29d988092ce3c127ce9de2274

**Additional context**

**Comment by de-nordic** [comment]
Buge is present since release v2.0.0
