### ISSUE TITLE
MSPI driver does not assign the 'op_mode' and 'duplex' in mspi_cfg

### ISSUE THREAD

**Issue by FRASTM** [zephyrproject-rtos/zephyr#80064]
**Describe the bug**
in the description of the devicetree for the  [Multi-bit SPI Bus](https://docs.zephyrproject.org/latest/hardware/peripherals/mspi.html#device-tree) 
property  op-mode and duplex are supposed to be set  as follows

```
 			op-mode = "MSPI_CONTROLLER";
			duplex = "MSPI_HALF_DUPLEX";
```

The MSPI_CONFIG macro is capturing the mspi_cfg  with   (see drivers/mspi/mspi_emul.c)

```
		.op_mode = DT_ENUM_IDX_OR(n, op_mode, MSPI_OP_MODE_CONTROLLER),
		.duplex = DT_ENUM_IDX_OR(n, duplex, MSPI_HALF_DUPLEX),
```

which does not accept 
 			op-mode = "MSPI_CONTROLLER";
			duplex = "MSPI_HALF_DUPLEX";

**To Reproduce**
1. add overlay file for the mspi1 node with properties 'op-mode' and 'duplex' as above
2. west build
3. See error

**Expected behavior**
Use the appropriate DT macro to retrieve the mspi_config
```
mspi_config = 	
	{
		.channel_num = EMUL_MSPI_INST_ID, 		
		.op_mode = MSPI_OP_MODE_CONTROLLER,
		.duplex = MSPI_HALF_DUPLEX,
		etc.
	}
```

**Logs and console output**
```
devicetree_generated.h:8377:46: error: incompatible types when initializing type 'enum mspi_op_mode' using type 'char *'
...
in expansion of macro 'MSPI_BUS_NODE'
   37 |         .op_mode                  = DT_PROP_OR(MSPI_BUS_NODE, op_mode, MSPI_OP_MODE_CONTROLLER),


devicetree_generated.h:8393:45: error: incompatible types when initializing type 'enum mspi_duplex' using type 'char *'
...
 in expansion of macro 'MSPI_BUS_NODE'
   38 |         .duplex                   = DT_PROP_OR(MSPI_BUS_NODE, duplex, MSPI_HALF_DUPLEX),

```

**Environment (please complete the following information):**

 - OS: (e.g. Linux, MacOS, Windows) ubuntu
 - Toolchain (e.g Zephyr SDK, ...) 0.16.8
 - Commit SHA or Version used 03959a20f7834ffe50a51df2b2e45ef87d1b610b

-->

**Comment by swift-tk** [comment]
In the error, it uses `DT_PROP_OR` not `DT_ENUM_IDX_OR`. 
Although it should have been `DT_INST_ENUM_IDX_OR`...
