### ISSUE TITLE
Nominate myself as Collaborator

### ISSUE THREAD

**Issue by michalsimek** [zephyrproject-rtos/zephyr#80124]
# Nomination

## GitHub User

Provide the following information about the GitHub user:

1. Full name: Michal Šimek
1. GitHub username: @michalsimek
1. Organization (optional): Advanced Micro Devices, Inc. (@xilinx)

## Supporting Documents

Before pull requests listing I would like to introduce myself. I am working on Xilinx devices for 18+ years.
I am U-Boot custodian(17+ years)  and TF-A platform maintainer for all Xilinx SOCs (4years). 
I am also Microblaze Linux kernel maintainer(15+ years) and Xilinx SOC Linux maintainers (12+ years). 
And author of initial Device Tree Generator. 
Based on my history from other project I want to make sure that platforms are wired properly
without any shortcuts and hacks. And also be informed about it. 
I also have access to various HW resources to be able to test and validate changes. 

We are planning to extend our contribution to Zephyr project which is starting with initial 
32bit Microblaze V soft core cpu (based on Risc-V) with using Xilinx soft IPs.
Also wire it in CI. That's why also starting to upstream Qemu description for it. 
https://lore.kernel.org/r/20241017072507.4033413-1-sai.pavan.boddu@amd.com

For more information you can look at my linkedin profile:
https://www.linkedin.com/in/simekmichal/

I forget to mentioned one more thing. I am interested in all AMD/Xilinx drivers and platforms.

Here are some initial pull requests but other will shortly be coming. 
https://github.com/zephyrproject-rtos/zephyr/pull/79608
https://github.com/zephyrproject-rtos/zephyr/pull/80059
https://github.com/zephyrproject-rtos/zephyr/pull/80069
https://github.com/zephyrproject-rtos/zephyr/pull/80057 - MAINTAINERS.yml

**Comment by stephanosio** [comment]
@michalsimek has been added as a Contributor with Triage permission level.
