### ISSUE TITLE
IEEE 802.1 AS gPTP  grandmaster support 

### ISSUE THREAD

**Issue by laperie** [zephyrproject-rtos/zephyr#8017]
In addition to gPTP slave support which will be implemented in [PR #6570](https://github.com/zephyrproject-rtos/zephyr/pull/6570),  Zephyr needs to support gPTP Grandmaster role, as specified by IEEE standard

**Comment by jukkar** [comment]
Fixed by commit 68127a3100ab32f8d0060745b00e08a4b19c9698
