### ISSUE TITLE
adafruit_feather_nrf52840: tests/subsys/portability/cmsis_rtos_v2/portability.cmsis_rtos_v2 fails when building

### ISSUE THREAD

**Issue by fkokosinski** [zephyrproject-rtos/zephyr#80215]
**Describe the bug**

The test in `tests/subsys/portability/cmsis_rtos_v2/portability.cmsis_rtos_v2` fails to build for the following two Zephyr targets:
* `adafruit_feather_nrf52840/nrf52840/sense`
* `adafruit_feather_nrf52840/nrf52840/sense/uf2`

The following compilation error is reported:
```
/home/filip/zephyrproject/zephyr/drivers/sensor/voltage_divider/voltage.c:118:41: warning: implicit
declaration of function 'K_TIMEOUT_ABS_TICKS'; did you mean 'Z_TIMEOUT_MS_TICKS'? [-Wimplicit-function-declaration]
  118 |                 data->earliest_sample = K_TIMEOUT_ABS_TICKS(
      |                                         ^~~~~~~~~~~~~~~~~~~
      |                                         Z_TIMEOUT_MS_TICKS
/home/filip/zephyrproject/zephyr/drivers/sensor/voltage_divider/voltage.c:118:41: error: incompatible types when assigning to type 'k_timeout_t' from type 'int'
/home/filip/zephyrproject/zephyr/drivers/sensor/voltage_divider/voltage.c: In function 'voltage_ini
':
/home/filip/zephyrproject/zephyr/drivers/sensor/voltage_divider/voltage.c:145:33: error: incompatible types when assigning to type 'k_timeout_t' from type 'int'
  145 |         data->earliest_sample = K_TIMEOUT_ABS_TICKS(0);
```

**To Reproduce**
1. `west build -p -b adafruit_feather_nrf52840/nrf52840/sense tests/subsys/portability/cmsis_rtos_v2`
2. See error

**Expected behavior**

Build doesn't end with an error.

**Impact**

Showstopper (failing CI). See #80038.

**Environment (please complete the following information):**

 - OS: Linux
 - Toolchain: Zephyr SDK
 - Commit SHA or Version used: 185432c96dd74fb30edc334f973a5a42876d22f0

**Comment by nashif** [comment]
well, when a board enables more than the basic and the test has its own requirement, worlds collide. This test should just be built/run on simulation platforms IMO and not on every other board we have.
