### ISSUE TITLE
Nominate doki-nordic as collaborator

### ISSUE THREAD

**Issue by aescolar** [zephyrproject-rtos/zephyr#80219]
# Nomination

## GitHub User

1. Name: Dominik Kilian
1. GH user: [doki-nordic](https://github.com/doki-nordic) 
1. Org: Nordic Semi

## Supporting Documents

* https://github.com/zephyrproject-rtos/zephyr/pull/58741
* https://github.com/zephyrproject-rtos/zephyr/pull/59371
* https://github.com/zephyrproject-rtos/zephyr/pull/44632
* https://github.com/zephyrproject-rtos/zephyr/pull/71492
* https://github.com/zephyrproject-rtos/zephyr/pull/72377
* https://github.com/zephyrproject-rtos/zephyr/pull/37361

**Comment by stephanosio** [comment]
@doki-nordic has been added to the GitHub `collaborators` team.

**Comment by aescolar** [comment]
@stephanosio, @doki-nordic 's reviews still appeare grayed out, and he is not a member in https://github.com/orgs/zephyrproject-rtos/people?query=doki-nordic
should he be there?

**Comment by doki-nordic** [comment]
I accepted yesterday. I think, it was just after you checked.
