### ISSUE TITLE
Nominate rugeGerritsen as collaborator

### ISSUE THREAD

**Issue by aescolar** [zephyrproject-rtos/zephyr#80233]
# Nomination

## GitHub User

1. Rubin Gerritsen
1. [rugeGerritsen](https://github.com/rugeGerritsen)
1. Nordic Semi

## Supporting Documents

* https://github.com/zephyrproject-rtos/zephyr/pull/78897
* https://github.com/zephyrproject-rtos/zephyr/pull/78284
* https://github.com/zephyrproject-rtos/zephyr/pull/78267
* https://github.com/zephyrproject-rtos/zephyr/pull/77925
* https://github.com/zephyrproject-rtos/zephyr/pull/78675
* https://github.com/zephyrproject-rtos/zephyr/pull/78092
* https://github.com/zephyrproject-rtos/zephyr/pull/77704

**Comment by stephanosio** [comment]
@rugeGerritsen is not currently listed as a collaborator in the MAINTAINERS file.

**Comment by aescolar** [comment]
> @rugeGerritsen is not currently listed as a collaborator in the MAINTAINERS file.

Correct. I will add him (but this is a bit of a chicken and egg :) )

**Comment by aescolar** [comment]
@stephanosio the maintainers file now lists @rugeGerritsen :)

**Comment by stephanosio** [comment]
@rugeGerritsen has been added as a Maintainer.
