### ISSUE TITLE
drivers: flash: spi_nor: values vom DT not correctly used, when `CONFIG_SPI_NOR_SFDP_RUNTIME=y`

### ISSUE THREAD

**Issue by maass-hamburg** [zephyrproject-rtos/zephyr#80383]
**Describe the bug**

when `CONFIG_SPI_NOR_SFDP_RUNTIME=y`, configs from the dts like the wp, hold and reset pins are not parsed correctly into the `struct spi_nor_config` and therefore can't be used by the driver.

**To Reproduce**
set `CONFIG_SPI_NOR_SFDP_RUNTIME=y`, when using the jedec,spi-nor flash driver

**Expected behavior**
dts configuration is used correctly

**Impact**
most of the available configuration, that can be done via the dts wont work when `CONFIG_SPI_NOR_SFDP_RUNTIME=y`,

**Logs and console output**

**Environment (please complete the following information):**
NA

**Additional context**
Got introduced with https://github.com/zephyrproject-rtos/zephyr/pull/70415

**Comment by de-nordic** [comment]
Bug level set to low, seems to go mainly undetected by users.

**Comment by alexgoldstone** [comment]
This just bit me for several hours so its definitely impacting more than just the original reporter.

**Comment by de-nordic** [comment]
> This just bit me for several hours so its definitely impacting more than just the original reporter.

Sorry. Have you reported that? It is hard to evaluate user impact without reports.

**Comment by alexgoldstone** [comment]
No, it literally just occurred as an issue for us today and once I identified the issues I searched to see if anyone else had the same issue and commented above. Is there somewhere else I should flag this also please?

**Comment by de-nordic** [comment]
Ok, so you are the second person to report this since it went in as part of 3.7.0.
This is the right place to report it.
