### ISSUE TITLE
HAS_SWO not getting selected by STM32U5 series

### ISSUE THREAD

**Issue by moiflo033** [zephyrproject-rtos/zephyr#80479]
**Describe the bug**

I'm developing a custom board based on the STM32U5A5 and wanted to debug it through SWO.
When selecting 'CONFIG_LOG_BACKEND_SWO' i get the error that HAS_SWO (=n).
Tried builtin Boards but those have the same issue.

**To Reproduce**

```bash
west build -p -b nucleo_u5a5zj_q samples/hello_world/ -DCONFIG_LOG_BACKEND_SWO=y -DCONFIG_LOG=y
```

**Expected behavior**

I would expect to be able to log to SWO.

**Impact**

Console output through SWO on STM32U5x not possible.

**Environment (please complete the following information):**

 - OS: Windows
 - Toolchain: Zephyr SDK 0.17.0
 - g26603cefaf41 (main at time of creation) and v3.7.0

**Additional context**

**Comment by FRASTM** [comment]
Despite the -DCONFIG_LOG_BACKEND_SWO=y  I do not see the CONFIG_LOG_BACKEND_SWO
then the DBGMCU trace pin is not assigned by the st_stm32_common_config
