### ISSUE TITLE
shell module not working for nRF5340 DK

### ISSUE THREAD

**Issue by aghuang1** [zephyrproject-rtos/zephyr#80481]
**Describe the bug**
 The shell module sample from Zephyr does not provide an interactive shell for me to type in. 

**To Reproduce**
 1. cd zephyr/samples/subsys/shell/shell_module
2.  west build -b nrf5340dk/nrf5340/cpuapp -p
3. west flash --erase --reset
4. Open a new terminal window and type screen /dev/ttyACM0 115200. 
5. If this doesn't work, try with screen /dev/ttyACM1 115200.

**Expected behavior**
 opening screen should yield an interactive shell interface where I can use UART. 

**Impact**
 Showstopper - doesn't allow me to use shell interfaces with the nRF5340 DK. 

**Logs and console output**
 after using /dev/ttyACM0 115200, it shows nothing in the terminal window. 

**Environment (please complete the following information):**

 - OS: Linux
 - Toolchain Zephyr SDK
 - Zephyr version: 3.6.99. NCS version: 2.7.0

**Additional context**

**Comment by henrikbrixandersen** [comment]
Thank you for reporting this. However - unless you are able to reproduce this issue with upstream Zephyr `main` - please report issues with the nRF Connect SDK (NCS) on the [Nordic Semiconductor DevZone](https://devzone.nordicsemi.com/).
