### ISSUE TITLE
Nominate myself (rghaddab) as Contributor

### ISSUE THREAD

**Issue by rghaddab** [zephyrproject-rtos/zephyr#80518]
# Background

The [TSC Project Roles] defines the main roles for the Zephyr Project, including
Maintainer, Collaborator, and Contributor.

By default anyone that contributes code or documentation is a Contributor, but
with the lowest [GitHub Permission Level] of Read. For example, Contributors
with Read permission do not have the permission to add reviewers to a pull
request.

Use this template to nominate a GitHub user for the Contributor role with
Triage permission level, which allows the user to add reviewers to a pull
request and be added as a reviewer by other users.

# Nomination

## GitHub User

Provide the following information about the GitHub user:

1. Full Name: Riadh Ghaddab
1. GitHub username: @rghaddab
1. Organization (optional): Baylibre

## Supporting Documents

Here is a list of some of my merged PRs:
https://github.com/zephyrproject-rtos/zephyr/pull/62073
https://github.com/zephyrproject-rtos/zephyr/pull/69331
https://github.com/zephyrproject-rtos/zephyr/pull/74235

I am also the author of the new storage system ZMS:
https://github.com/zephyrproject-rtos/zephyr/pull/77930

[TSC Project Roles]: <https://docs.zephyrproject.org/latest/project/project_roles.html>
[GitHub Permission Level]: <https://docs.github.com/en/organizations/managing-access-to-your-organizations-repositories/repository-roles-for-an-organization>

**Comment by stephanosio** [comment]
@rghaddab has been added as a Contributor with Triage permission level.

p.s. Please note that this template is for "Contributor with Triage permission level." For Collaborator level access, please submit a PR adding yourself as a Collaborator in the MAINTAINERS file.
