### ISSUE TITLE
Ethernet initialization is unreliable and gets stuck on frdm-k64f

### ISSUE THREAD

**Issue by vakulgarg** [zephyrproject-rtos/zephyr#8054]
I am using ethernet on frdm-k64f. I find that a lot of times, the ethernet phy initialization function eth_mcux_phy_start() gets stuck (i.e. never returns). This prevents zephyr boot (the shell prompt never appears).

I tried adding a printf before eth_mcux_phy_start() is called in function eth_0_init(). This effectively inserts some delay. Doing this workaround the problem. Alternatively, adding k_busy_wait(1000000) also workaround the issue.

**Comment by mike-scott** [comment]
Which sample are you running?

Could it be that you're experiencing this:
https://github.com/zephyrproject-rtos/zephyr/issues/8049 ?
(more detail in https://github.com/zephyrproject-rtos/zephyr/issues/8005)

It manifests as a hung boot right after the ethernet DBG message.

**Comment by vakulgarg** [comment]
I am running mbedtls_sslclient (prj.conf modified to use ethernet).
It is hung boot right after ethernet DBG message.

**Comment by vakulgarg** [comment]
Your patch below worked for me.
https://github.com/mike-scott/zephyr/commit/4054d85d44fe48f6594a7dfeea6cf7f5af1b761f

**Comment by mike-scott** [comment]
@nashif Can we mark this as a duplicate of https://github.com/zephyrproject-rtos/zephyr/issues/8049 ?

**Comment by MaureenHelm** [comment]
Duplicate of #8049

**Comment by mike-scott** [comment]
https://github.com/zephyrproject-rtos/zephyr/pull/8077 is merged and should fix this as well (as it's a duplicate).

Can @vakulgarg confirm that latest master does not exhibit hung boot?

**Comment by vakulgarg** [comment]
With latest master, it works fine.

**Comment by pfalcon** [comment]
> I find that a lot of times, the ethernet phy initialization function eth_mcux_phy_start() gets stuck (i.e. never returns).

Funnily, I never saw this with my samples (which are usually from samples/net/socksts/). Just trying to compare my experiences with other people's (given that everyone seems to see different picture).
