### ISSUE TITLE
Add Support for different stack protector options

### ISSUE THREAD

**Issue by vujjuri** [zephyrproject-rtos/zephyr#80559]
Currently, the Zephyr project only supports the `-fstack-protector-all` option for stack protection. To better tune memory footprint and security requirements, it is necessary to add support for other stack protector options such as,
- `-fstack-protector, `
- `-fstack-protector-strong`, and 
- `-fstack-protector-explicit`.

**Rationale:**

- **Memory Footprint:** Different stack protector options provide varying levels of protection, which can help optimize the memory usage for different applications. For instance, `-fstack-protector-all` adds stack protection to all functions regardless of their vulnerability, that increases memory footprint significantly, while `-fstack-protector`/ `-fstack-protector-strong` provides a more balanced approach by protecting functions with certain characteristics.
- **Security Requirements:** Allowing more granular control over stack protection can help meet diverse security needs. For example, `-fstack-protector-explicit` allows developers to manually specify which functions should be protected, offering a tailored security approach.

**Proposed Changes:**

- **Build System Modifications:**
  - Update the CMake build scripts to accept new stack protector options.
  - Introduce configuration options in Kconfig to select the desired stack protector level.
  - Ensure compatibility with different compiler versions and platforms supported by Zephyr.
- **Codebase Adjustments:**
   - Modify the compiler flags in the build system to include the selected stack protector option.
   - Implement conditional compilation to apply the appropriate stack protector based on the configuration.
- **Documentation Updates:**
   - Update the Zephyr documentation to include detailed descriptions of each stack protector option.
   - Provide guidelines on how to select the appropriate stack protector based on application requirements.
   - Include examples demonstrating the impact of different stack protector options on memory usage and security.
- **Testing and Validation:**
   - Develop unit tests to verify the correct application of each stack protector option.
   - Perform regression testing to ensure that the new options do not introduce any issues.
   - Conduct performance benchmarking to evaluate the impact of different stack protector options on memory footprint and execution time.

**Comment by ceolin** [comment]
@vujjuri It makes sense to me.
