### ISSUE TITLE
sysbuild: not encrypting binaries anymore

### ISSUE THREAD

**Issue by wag-thom** [zephyrproject-rtos/zephyr#80560]
### **Describe the bug**

In [v4.0.0-rc1](https://github.com/zephyrproject-rtos/zephyr/releases/tag/v4.0.0-rc1) sysbuild does not encrypt the binaries anymore with my configuration. 

I got this warning about `BOOT_ENCRYPTION`: 
```
warning: BOOT_ENCRYPTION (defined at zephyr/share/sysbuild/images/bootloader/Kconfig:155) was assigned the value 'y' but got  
the value 'n'. Check these unsatisfied dependencies: SUPPORT_BOOT_ENCRYPTION (=n).
```

The bug was introduced with the commit 9e1b3bbb6579f6bef27c4e558db4ff3ca0e435e1 (pr #79707).  
I checked out commit 00c119776bc3be9711aeb16b83ad76661cb944ed (one commit before 9e1b3bbb6579f6bef27c4e558db4ff3ca0e435e1) and could confirm, that it worked with that version.

### **To Reproduce**

I used the following configuration:

app/**sysbuild.conf**:
```
SB_CONFIG_BOOTLOADER_MCUBOOT=y
SB_CONFIG_MCUBOOT_MODE_SINGLE_APP=y
SB_CONFIG_BOOT_SIGNATURE_TYPE_ECDSA_P256=y
SB_CONFIG_BOOT_SIGNATURE_KEY_FILE="${APP_DIR}/sysbuild/keys/root-ec-p256.pem"
SB_CONFIG_BOOT_ENCRYPTION=y
SB_CONFIG_BOOT_ENCRYPTION_KEY_FILE="${APP_DIR}/sysbuild/keys/enc-ec256-priv.pem"
```

app/sysbuild/**app.conf**:
```
CONFIG_MCUBOOT_ENCRYPTION_KEY_FILE="${APP_DIR}/sysbuild/keys/enc-ec256-pub.pem"
```

app/sysbuild/**mcuboot.conf**: Other mcuboot settings...

Built with west: `west build app -p always -b myboard --sysbuild`

Then I got the mentioned warning about `BOOT_ENCRYPTION` and at the end of the build, no encrypted files were generated, only the signed binaries (myapp.signed).

### **Expected behavior**

At the end of the build, the signed and encrypted images are should be generated: myapp.signed.encryped.bin / hex

### **Environment:**
 - OS: Windows
 - Toolchain Zephyr SDK 1.16.4
 - Commit SHA with bug: 9e1b3bbb6579f6bef27c4e558db4ff3ca0e435e1
 - Commit SHA where it still worked: 00c119776bc3be9711aeb16b83ad76661cb944ed

**Comment by nordicjm** [comment]
Indeed a silly Kconfig mistake
