### ISSUE TITLE
RW612 based boards hang when wlan reset

### ISSUE THREAD

**Issue by GaofengZhangNXP** [zephyrproject-rtos/zephyr#80598]
**Describe the bug**
•	When triggering Wi-Fi/BLE reset in Wi-Fi/BLE sample application the Wi-Fi and BLE cores are powered off and then have to be reset. The processing of the reset doesn't properly set status resulting in improper reuse and reinitialization of an existing task handle to the kernel. On next reset, the kernel gets stuck in an infinite loop when handling a z_thread_abort due to this duplicate task handle.

**To Reproduce**
•	On RW612 based boards input wlan reset command and you can reproduce the issue 

**Expected behavior**
•	wlan reset command will reboot successfully

**Comment by nordicjm** [comment]
> zephyr system hang and can't input any command

Based on the very limited information provided (i.e. none) I disagree, it works fine here?

**Comment by danieldegrasse** [comment]
@GaofengZhangNXP please expand this issue to list (at a minimum) the following:
- What platform and SHA of Zephyr you can reproduce the issue on
- Specific steps (IE a build and flash command) to reproduce the issue
- Any specific logs that would help understand the issue

The guidelines within the bug template are helpful for this, usually I try to fill all of them out. For an example of an issue with this information, take a look here: https://github.com/zephyrproject-rtos/zephyr/issues/80590

**Comment by dkalowsk** [comment]
No details.  Marking as closed.
