### ISSUE TITLE
[Coverity CID :186196] Error handling issues in /samples/sensor/mcp9808/src/main.c

### ISSUE THREAD

**Issue by mandarcthorat1** [zephyrproject-rtos/zephyr#8062]
Static code scan issues seen in File: /samples/sensor/mcp9808/src/main.c
 Category: Error handling issues
 Function: main
 Component: Samples
 CID: 186196
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by parasjain2000** [comment]
Fixed via pull request https://github.com/zephyrproject-rtos/zephyr/pull/8046, merge pending

**Comment by maxxlife** [comment]
@mandarcthorat1 Hi. We have a new Coverity issue with the same number
I fixed it, #15743
