### ISSUE TITLE
dma: drop the `isr-ok` tag from channel request and release functions and add release API function

### ISSUE THREAD

**Issue by LaurentiuM1234** [zephyrproject-rtos/zephyr#80746]
## Introduction

The current DMA API doesn't allow DMA drivers to perform "allocation" and de-"allocation" of channel resources, which is fine if the drivers are simple enough, but becomes a problem when dealing with more complex drivers. An example of such a driver is `dma_nxp_edma.c`, which for imx8 SoCs:

1. Needs to enable/disable interrupts when not required as the interrupt controller has a power domain attached to it.
3. Needs to enable/disable channel power domains (1 domain per channel) when a channel is not used.

First of all, `dma_request_channel()` is tagged with `isr-ok`, meaning we can't perform blocking operations inside the filter function (in our example, we'd want to `pm_device_runtime_get()` but that's just not possible because the PM callback itself is not ok for usage inside ISRs).

Secondly, `dma_release_channel()` has no channel release callback so there's no undo operation for the "allocations" performed inside `dma_request_channel()`. As for the `isr-ok` tag: the issue's the same as for `dma_request_channel()`.

### Proposed change

There's two proposed changes:

1. Add a channel release callback.
2. Drop the `isr-ok` tag from both `dma_request_channel()` and `dma_release_channel()`. Whether these functions are ok to use inside ISRs or not should depend on the underlying implementation (like it's the case for `pm_device_runtime_get()`)

### Proposed change (Detailed)

Not much else to be said about the change itself. The main benefit from it that I see is it would give drivers a proper way to perform resource "allocation" and de-"allocation" if required (IRQ management, PD management are also included here).

### Dependencies

N/A

### Concerns and Unresolved Questions

1. How will this affect vendors making use of `dma_request_channel()` in their ISRs? Is it alright to make the `isr-ok` behavior implementation-dependent?
2. Are there any other people who would benefit from doing this?

## Alternatives

For the example above, @teburd proposed the option of offloading the work from `dma_start()` (the place in which we enable the interrupts, which is not right as described in https://github.com/zephyrproject-rtos/zephyr/issues/80573), which, IMO is a workaround the fact that the current API doesn't have a proper way of "allocating"/de-"allocating" channel resources (IRQ management, PD management included here).

## Relevant PR
https://github.com/zephyrproject-rtos/zephyr/pull/80745

**Comment by teburd** [comment]
I'm ok making isr-ok optional here, dependent on implemention
