### ISSUE TITLE
STM32 L562 Nucleo - TF-M sample hardfault

### ISSUE THREAD

**Issue by Yidaen** [zephyrproject-rtos/zephyr#80792]
Hello everyone,

I'm trying to run a TF-M example on the STM32 L562 Discovery Kit. I followed the example steps provided on the board’s page (https://docs.zephyrproject.org/latest/boards/st/stm32l562e_dk/doc/index.html).

However, when I run the example, I keep getting a Hard Fault error. When I connected to the debug tool to understand the cause of the Hard Fault, I noticed that the program counter (PC) was stuck at 0x0c000c28. When I checked this address in memory, I found it was empty.

What steps could I take to diagnose or resolve this issue?

**To Reproduce**

1. west build -b stm32l562e_dk/stm32l562xx/ns samples/tfm_integration/tfm_ipc/
2. ./build/tfm/api_ns/regression.sh
3.  west flash
 
**Expected behavior**

he expected output for TF-M IPC is provided at the very bottom of the example documentation.
https://docs.zephyrproject.org/latest/samples/tfm_integration/tfm_ipc/README.html

**Logs and console output**

![image](https://github.com/user-attachments/assets/8c8704cc-16f5-4be1-8cfb-3f12b70fd0f0)

![image](https://github.com/user-attachments/assets/65484b0a-c8d5-49ec-a8b5-94d4b8678335)

![image](https://github.com/user-attachments/assets/89d5d608-af6a-414b-9ab4-4cac9243e3ed)

**Environment (please complete the following information):**

Ubuntu 24.04
Zephyr SDK 0.17.0
Commit: e90c58a

**Comment by erwango** [comment]
Same as https://github.com/zephyrproject-rtos/zephyr/issues/77847. I propose to close this one and focus on the oldest one.

**Comment by dkalowsk** [comment]
Marking closed due to duplicate.
