### ISSUE TITLE
Bluetooth ATT trying to access invalid pointer after disconnect

### ISSUE THREAD

**Issue by danielwidmann** [zephyrproject-rtos/zephyr#8083]
Think of the following scenario on a BLE central device:

* CONFIG_BT_ATT_TX_MAX + 1 GATT requests are issued within a short time (The last request is blocked until one of the other requests complete)
* The BLE connection is lost. `bt_att_disconnected` is called

When a BLE connection is terminated, the ATT layer first wakes up all waiting threads, but they might not be scheduled right away:
https://github.com/zephyrproject-rtos/zephyr/blob/43553da9b2bb9e537185695899fb5184c3b17ebe/subsys/bluetooth/host/att.c#L1967-L1970

Then the used ATT data-structure is cleared:
https://github.com/zephyrproject-rtos/zephyr/blob/43553da9b2bb9e537185695899fb5184c3b17ebe/subsys/bluetooth/host/att.c#L2044

And finally the waiting thread wakes up and tries to release a semaphore that has just been wiped:
https://github.com/zephyrproject-rtos/zephyr/blob/43553da9b2bb9e537185695899fb5184c3b17ebe/subsys/bluetooth/host/att.c#L268-L273

This causes access to invalid memory and a FAULT on the thread.

**Comment by nashif** [comment]
@jhedberg FYI, @Vudentz what is the status?

**Comment by Vudentz** [comment]
@nashif Will send a fix for this in a moment.
