### ISSUE TITLE
nvs: zephyr is blocked in nvs_recover_last_ate while loop

### ISSUE THREAD

**Issue by spayet2024** [zephyrproject-rtos/zephyr#80835]
**Describe the bug**

I use nvs to save data in flash as following : 3 sectors (each sector is 2048 bytes beacause of use of STM32G0C1KE) to save a maximum of 250 data of 8 bytes structure. Each data use an ID.
Datas are saved when power down is detected. The device have around 600ms to save all data.
In some cases, when maximum of data saved is reachd and many datas have been update, we don't have the sufficiant time to save all data before shut down of the device, and also data corruption can occurs (see this in attached).
In a few case, when data corruption occurs, zephyr remains blocked at the next startup, and applicative threads and also log can't start. More particulary, it is blocked in nvs_mount() function and more particulary in the while loop of nvs_recover_last_ate function().

As following, here is tests i realised to analyse this bug : 

Test 1 : If i remove the call of nvs_mount() in my code, and then i build and flash my device, then the device startup is succesfully performed and all threads work. However, nvs don't work.

Test 2 : If i reintegrate nvs_mount in my code, then i add a skip of the while loop of nvs_recover_last_ate, and then i build and flash my device, then the device startup is succesfully performed and all threads work. Then, i remove previous modification, and i build and flash the device. After that, the device startup is succesfully performed and all threads work. nvs work fine, but some datas has been lost.

Do you have any idea why zephyr remains blocked in the nvs_recover_last_ate function if data corruption occurs ?
Do you have a workaround for this bug, to avoid the startup error, even if some data are lost.

- custom device with STM32G0C1KE
- zephyr-v3.4.0

**Expected behavior**

device startup should be succesfully performed. 

**Impact**

Several devices on the field can't startup and don't wwork.

**Logs and console output**

FLash start addr = 0x0807E800
Flash end addr = 0x0807FFF0

Flash partition below =

0A000132 00016E2F  0A0000E7 00012E24  0A000866 00003E78  0A0005D2 00004288  0A0007AD 00003D3F  0A0003AC 00003C23  0A000B7C 00004113  0A000758 00003AEC
0A000019 00003F65  0A0006C2 00003E49  0A00087F 00003BAB  0A000708 00003E23  0A000839 00003E8A  0A0008A7 00003EFE  0A00060E 00003E6A  0A00051E 00003E93
0A00065E 00003BBE  0A000492 00003E94  0A00045B 00003BBF  0A000037 000041DF  0A0006CC 00003BFB  0A0009E7 00003E19  0A0000BE 00000DC2  0A0009E3 00000048
0A0000C7 00000045  24110677 000007E6  0A000442 0000004A  0A00003A 0000243A  0A000026 000022E1  0A0000D8 0000004C  0A000A51 00000041  0A0004C8 00000047
0A000907 00000044  0A00034E 00000041  0A000A33 0000004E  0A0008E7 0000004A  0A0008A5 0000004A  0A00002E 00001F34  0A0003E2 0000004B  0A000853 0000004D
0A000969 00000001  0A000B75 0000004E  0A000015 00002063  0A000022 0000250E  0A000B8E 0000004D  0A00011B 0000004E  0A00088A 0000004D  0A000139 0000004E
0A000088 0000004E  0A000386 0000004A  0A000A18 0000004E  0A000A95 00000038  0A000119 00000044  0A000498 0000004E  0A00099E 00000046  0A0000D4 00000045
0A000016 000028DA  0A000043 0000278D  0A0003CC 00000027  0A00002C 0000269C  0A000934 00000036  0A0008F1 00000048  0A00039A 0000004A  0A000902 0000004E
0A0000CB 00000052  0A00012D 0000004E  0A000099 00000051  0A00013E 0000004F  0A00008A 00000047  0A00009D 0000004C  0A0000A7 00000051  0A0009FA 0000004E
0A0003CE 0000004E  0A00012A 00000050  0A000034 0000213D  0A000B58 00000045  0A0000F9 0000003B  0A0005BF 0000004B  0A000AB3 00000047  0A0000AB 0000004A
0A0008D5 0000004C  0A000518 00000043  0A0004D5 00000044  0A00007A 00000050  0A000628 00000049  0A000B80 0000004C  0A000616 0000004D  0A000A74 00000042
0A0002E3 00000043  0A00012E 00000050  0A000B1B 0000003B  0A000540 00000038  0A000018 0000254C  0A000025 0000271C  0A00043E 00000045  0A0000F2 0000004F
0A000095 0000004E  0A00007C 0000004E  0A0009EE 00000045  0A00016D 00003D4D  0A000730 00003D75  0A00080C 00003C3C  0A00005D 00003215  0A00006D 00003374
0A000055 0000154A  0A000127 00000F75  0A000078 000025B7  0A000B8B 00004053  0A00067C 00003ED1  0A0005B9 00003C61  0A000B90 00003E12  0A000AC3 00003EDC
0A0008B6 00004102  0A0008FC 00003C50  0A0007A8 00003B62  0A0003A7 00003EA5  0A000870 00003E43  0A000AAA 000040A3  0A000B4A 00003E9A  0A000640 000041C4
0A0007B7 00003EF9  0A00094C 00004067  0A000087 000034EE  0A00090B 000023B0  00014307 FFFFFFFF  00014308 FFFFFFFF  FFFFFFFF FFFFFFFF  FFFFFFFF FFFFFFFF
03E80001 DBFF0004  03E8FFFF 44FF0000  03E00001 C2FF0004  03D8006F B5FF0008  03D0006E 73FF0008  03C80067 6DFF0008  03C00065 CDFF0008  03B80061 3FFF0008
03B00060 F9FF0008  03A8005C 3FFF0008  03A0005B 35FF0008  03980057 E5FF0008  03900056 23FF0008  03880053 A2FF0008  03800052 64FF0008  0378004C 81FF0008
0370004B 8BFF0008  03680048 C6FF0008  03600047 26FF0008  03580043 1CFF0008  03500041 BCFF0008  0348003A 2CFF0008  03400039 53FF0008  0338001A 13FF0008
03300095 79FF0008  03280066 89FF0008  03200050 2EFF0008  0318003E A3FF0008  031000B9 23FF0008  030800B8 D7FF0008  030000B7 37FF0008  02F800B6 EEFF0008
02F000B5 91FF0008  02E800B4 65FF0008  02E000B3 6FFF0008  02D800B2 FFFF0008  02D000B1 80FF0008  02C800B0 74FF0008  02C000AF 47FF0008  02B800AE 1FFF0008
02B000AD 60FF0008  02A800AC 94FF0008  02A000AB 9EFF0008  029800AA 0EFF0008  029000A9 71FF0008  028800A8 85FF0008  028000A7 65FF0008  027800A6 AAFF0008
027000A5 D5FF0008  026800A4 21FF0008  026000A3 2BFF0008  025800A2 BBFF0008  025000A1 C4FF0008  024800A0 30FF0008  0240009F A2FF0008  0238009E FAFF0008
0230009D 85FF0008  0228009C 71FF0008  0220009B 7BFF0008  0218009A EBFF0008  02100099 94FF0008  02080098 60FF0008  02000097 80FF0008  01F80096 75FF0008
01F00094 D5FF0008  01E80093 EDFF0008  01E00092 2BFF0008  01D80091 02FF0008  01D00090 C4FF0008  01C8008F C5FF0008  01C0008E 03FF0008  01B8008D E2FF0008
01B0008C 24FF0008  01A8008B 1CFF0008  01A0008A DAFF0008  01980089 F3FF0008  01900088 35FF0008  01880087 E7FF0008  01800086 21FF0008  01780085 57FF0008
01700084 91FF0008  01680083 A9FF0008  01600082 6FFF0008  01580081 46FF0008  01500080 80FF0008  0148007F EFFF0008  0140007E 29FF0008  0138007D C8FF0008
0130007C 0EFF0008  0128007B 36FF0008  0120007A F0FF0008  01180079 D9FF0008  01100078 1FFF0008  01080077 CDFF0008  01000076 0BFF0008  00F80075 6BFF0008
00F00074 ADFF0008  00E80073 95FF0008  00E00072 53FF0008  00D80071 7AFF0008  00D0004E E8FF0008  00C8006C DBFF0008  00C000F9 31FF0008  00B800FA D0FF0008
00B0003C CAFF0008  00A80059 AFFF0008  00A0006A A2FF0008  00980036 E4FF0008  0090003B BDFF0008  0088003F E3FF0008  00800045 9EFF0008  00780049 11FF0008
0070004A 6EFF0008  0068004D 56FF0008  0060004F F6FF0008  00580054 E6FF0008  00500055 20FF0008  00480058 4BFF0008  0040005A EBFF0008  0038005E 19FF0008
0030005F DFFF0008  00280062 C6FF0008  00200063 00FF0008  00180068 C3FF0008  00100069 05FF0008  0008001B A0FF0008  00000003 80FF0008  0400FFFF 04FF0000
0A00009E 00013C34  0A0000ED 00012CF0  00068F30 00000E65  0A000070 0001204B  0A0000B8 0000CD85  0A0009B0 00003BF1  0A0003C5 00003F26  0A000B95 00003FCA
0A000023 000047D6  0A0000B4 0000382E  0A000091 00003775  0A0000BB 0000322C  0A000063 0000335B  0A00008B 000033D3  0A000081 00003361  0A000069 0000371A
0A0000A0 000037D5  0A000090 000034F6  0A0000C0 00003388  0A000059 00003389  0A000144 000033E8  0A00002D 000037C4  0238DA12 00000A1E  0A000164 00000002
0A000170 00000001  0A00016F 00000001  0A00016B 00000001  02B69494 00000033  0A000165 00000002  0A000148 00000002  0A00007E 00000001  0A000118 00000001
0A00008C 00000001  0A0000FF 00000001  0A0000A4 00000001  0A00006E 00000001  058A140C 00000229  0A000145 00000001  0A00013F 00000001  05E5059F 00000165
00000000 FFFFFFFF  0A0008D4 00000003  0A000884 00000051  0A000577 0000003C  0A0000E0 00000051  0A000916 00000005  0A00011E 00000010  0A00057A 0000004E
0A0004A0 00000047  0A000A36 00000046  0A0004F9 00000047  0A0009E4 00000049  0A000024 0000213A  0A00086A 0000004E  0A000146 00000049  0A00012F 0000004D
0A000124 0000003F  0A000ADD 0000004E  0A000A45 0000004E  0A00050C 00000043  0A0005D4 00000008  0A0005DE 0000004A  0A00002B 0000284E  0A000042 00002144
0A000911 0000004B  0A000A9E 00000048  0A0007E3 00000049  0A000156 0000004C  0A000892 0000004E  0A000651 0000004C  0A000161 00000039  0A000826 00000042
0A0008AB 0000004E  0A00090C 0000004B  0A00061C 0000004E  0A000130 0000000E  0A0002DE 00000046  0A000803 0000004C  0A000608 0000004E  0A0004C7 00000046
0A0004A4 0000004E  0A0008CE 0000003A  0A000AD1 00000011  0A00084A 0000004B  0A000038 0000273B  0A000AD3 00000011  0A000B03 0000004E  0A000873 00000047
0A000827 0000003D  0A00089E 0000003D  0A000B7E 0000004C  0A00057C 0000004D  0A000836 0000004E  0A000A6B 0000004E  0A00099B 00000032  0A0007F0 0000004E
0A000666 00000043  0A00044D 00000046  0A0007B8 0000004E  0A00078D 00000048  0A0000EA 0000001F  0A000439 00000036  0A000093 00000038  0A00060B 0000004E
0A0007DD 0000001B  0A00049D 0000004E  0A00037A 00004204  0A000084 0000330E  0A0000EE 000033D6  0A00009F 000034AB  0A0000AE 0000370D  0A000079 00003604
0A0000BC 0000358B  0A0000CC 000033B1  0A0000F4 000033A4  0A000060 00003394  0A0000C4 0000360F  0A00005A 000037EB  0A000113 00000EE5  0A000B81 00003DBF
0A00066D 00003E7E  0A000CDA 000023F0  0A00007B 00012660  0A0000B1 00015591  0A00006A 00012167  00068F30 00000EBD  FFFFFFFF FFFFFFFF  FFFFFFFF FFFFFFFF
03E80016 E1FF0008  03E8FFFF 44FF0000  03E00017 27FF0008  03D80015 D1FF0008  03D00018 88FF0008  03C80070 ADFF0008  03C0005D 55FF0008  03B80044 34FF0008
03B00035 C5FF0008  03A80034 31FF0008  03A00031 82FF0008  03980030 12FF0008  0390002D 98FF0008  0388002C 6CFF0008  03800029 DFFF0008  03780028 10FF0008
03700025 49FF0008  03680024 BDFF0008  03600021 0EFF0008  03580020 9EFF0008  03500040 63FF0008  034800F8 5AFF0008  034000F7 BAFF0008  033800F6 E2FF0008
033000F5 9DFF0008  032800F4 69FF0008  032000F3 63FF0008  031800F2 F3FF0008  031000F1 8CFF0008  030800F0 78FF0008  030000EF 4BFF0008  02F800EE 92FF0008
02F000ED EDFF0008  02E800EC 19FF0008  02E000EB 13FF0008  02D800EA 83FF0008  02D000E9 FCFF0008  02C800E8 08FF0008  02C000E7 E8FF0008  02B800E6 B0FF0008
02B000E5 CFFF0008  02A800E4 3BFF0008  02A000E3 31FF0008  029800E2 A1FF0008  029000E1 DEFF0008  028800E0 2AFF0008  028000DF B8FF0008  027800DE 77FF0008
027000DD 08FF0008  026800DC FCFF0008  026000DB F6FF0008  025800DA 66FF0008  025000D9 19FF0008  024800D8 EDFF0008  024000D7 0DFF0008  023800D6 55FF0008
023000D5 2AFF0008  022800D4 DEFF0008  022000D3 D4FF0008  021800D2 44FF0008  021000D1 3BFF0008  020800D0 CFFF0008  020000CF FCFF0008  01F800CE 09FF0008
01F000CD 76FF0008  01E800CC 82FF0008  01E000CB 88FF0008  01D800CA 18FF0008  01D000C9 67FF0008  01C800C8 93FF0008  01C000C7 73FF0008  01B800C6 2BFF0008
01B000C5 54FF0008  01A800C4 A0FF0008  01A000C3 AAFF0008  019800C2 3AFF0008  019000C1 45FF0008  018800C0 B1FF0008  018000BF 66FF0008  017800BE A9FF0008
017000BD D6FF0008  016800BC 22FF0008  016000BB 28FF0008  015800BA B8FF0008  01500064 9BFF0008  01480042 DDFF0008  01400002 7BFF0004  01380004 CAFF0008
01300005 0CFF0008  01280006 41FF0008  01200007 87FF0008  01180008 31FF0008  01100009 F7FF0008  0108000C 76FF0008  0100000D B0FF0008  00F8000E D0FF0008
00F0000F 16FF0008  00E8000A 97FF0008  00E0000B 51FF0008  00D80010 41FF0008  00D00011 87FF0008  00C80012 CAFF0008  00C00013 0CFF0008  00B80014 98FF0008
00B0006B 4FFF0008  00A8003D 3EFF0008  00A0001F 3FFF0008  00980022 42FF0008  00900023 84FF0008  00880026 05FF0008  00800027 C3FF0008  0078002A 93FF0008
0070002B 55FF0008  0068002E D4FF0008  0060002F 12FF0008  00580032 CEFF0008  00500033 08FF0008  00480037 56FF0008  00400038 B6FF0008  00380046 20FF0008
00300051 F9FF0008  0028006D 3FFF0008  00200019 64FF0008  0018001C 81FF0008  00100016 CBFF0008  0008001D 6CFF0008  0000001E 13FF0008  0400FFFF 04FF0000
00014308 FFFFFFFF  0A00090B 000023B0  0A000087 000034EE  0A00094C 00004067  0A0007B7 00003EF9  0A000640 000041C4  0A000B4A 00003E9A  0A000AAA 000040A3
0A000870 00003E43  0A0003A7 00003EA5  0A0007A8 00003B62  0A0008FC 00003C50  0A0008B6 00004102  0A000AC3 00003EDC  0A000B90 00003E12  0A0005B9 00003C61
0A00067C 00003ED1  0A000B8B 00004053  0A000078 000025B7  0A000127 00000F75  0A000055 0000154A  0A00006D 00003374  0A00005D 00003215  0A00080C 00003C3C
0A000730 00003D75  0A00016D 00003D4D  0A0009EE 00000045  0A00007C 0000004E  0A000095 0000004E  0A0000F2 0000004F  0A00043E 00000045  0A000025 0000271C
0A000018 0000254C  0A000540 00000038  0A000B1B 0000003B  0A00012E 00000050  0A0002E3 00000043  0A000A74 00000042  0A000616 0000004D  0A000B80 0000004C
0A000628 00000049  0A00007A 00000050  0A0004D5 00000044  0A000518 00000043  0A0008D5 0000004C  0A0000AB 0000004A  0A000AB3 00000047  0A0005BF 0000004B
0A0000F9 0000003B  0A000B58 00000045  0A000034 0000213D  0A00012A 00000050  0A0003CE 0000004E  0A0009FA 0000004E  0A0000A7 00000051  0A00009D 0000004C
0A00008A 00000047  0A00013E 0000004F  0A000099 00000051  0A00012D 0000004E  0A0000CB 00000052  0A000902 0000004E  0A00039A 0000004A  0A0008F1 00000048
0A000934 00000036  0A00002C 0000269C  0A0003CC 00000027  0A000043 0000278D  0A000016 000028DA  0A0000D4 00000045  0A00099E 00000046  0A000498 0000004E
0A000119 00000044  0A000A95 00000038  0A000A18 0000004E  0A000386 0000004A  0A000088 0000004E  0A000139 0000004E  0A00088A 0000004D  0A00011B 0000004E
0A000B8E 0000004D  0A000022 0000250E  0A000015 00002063  0A000B75 0000004E  0A000969 00000001  0A000853 0000004D  0A0003E2 0000004B  0A00002E 00001F34
0A0008A5 0000004A  0A0008E7 0000004A  0A000A33 0000004E  0A00034E 00000041  FFFFFFFF FFFFFFFF  FFFFFFFF FFFFFFFF  FFFFFFFF FFFFFFFF  FFFFFFFF FFFFFFFF
FFFFFFFF FFFFFFFF  FFFFFFFF FFFFFFFF  FFFFFFFF FFFFFFFF  FFFFFFFF FFFFFFFF  FFFFFFFF FFFFFFFF  FFFFFFFF FFFFFFFF  FFFFFFFF FFFFFFFF  FFFFFFFF FFFFFFFF
FFFFFFFF FFFFFFFF  FFFFFFFF FFFFFFFF  FFFFFFFF FFFFFFFF  FFFFFFFF FFFFFFFF  FFFFFFFF FFFFFFFF  FFFFFFFF FFFFFFFF  FFFFFFFF FFFFFFFF  FFFFFFFF FFFFFFFF
FFFFFFFF FFFFFFFF  FFFFFFFF FFFFFFFF  FFFFFFFF FFFFFFFF  FFFFFFFF FFFFFFFF  FFFFFFFF FFFFFFFF  FFFFFFFF FFFFFFFF  FFFFFFFF FFFFFFFF  FFFFFFFF FFFFFFFF
FFFFFFFF FFFFFFFF  FFFFFFFF FFFFFFFF  FFFFFFFF FFFFFFFF  FFFFFFFF FFFFFFFF  FFFFFFFF FFFFFFFF  FFFFFFFF FFFFFFFF  FFFFFFFF FFFFFFFF  FFFFFFFF FFFFFFFF
FFFFFFFF FFFFFFFF  FFFFFFFF FFFFFFFF  FFFFFFFF FFFFFFFF  FFFFFFFF FFFFFFFF  FFFFFFFF FFFFFFFF  FFFFFFFF FFFFFFFF  FFFFFFFF FFFFFFFF  FFFFFFFF FFFFFFFF
FFFFFFFF FFFFFFFF  FFFFFFFF FFFFFFFF  FFFFFFFF FFFFFFFF  FFFFFFFF FFFFFFFF  FFFFFFFF FFFFFFFF  FFFFFFFF FFFFFFFF  FFFFFFFF FFFFFFFF  FFFFFFFF FFFFFFFF
FFFFFFFF FFFFFFFF  FFFFFFFF FFFFFFFF  FFFFFFFF FFFFFFFF  FFFFFFFF FFFFFFFF  FFFFFFFF FFFFFFFF  FFFFFFFF FFFFFFFF  FFFFFFFF FFFFFFFF  FFFFFFFF FFFFFFFF
FFFFFFFF FFFFFFFF  FFFFFFFF FFFFFFFF  FFFFFFFF FFFFFFFF  FFFFFFFF FFFFFFFF  FFFFFFFF FFFFFFFF  FFFFFFFF FFFFFFFF  FFFFFFFF FFFFFFFF  FFFFFFFF FFFFFFFF
FFFFFFFF FFFFFFFF  FFFFFFFF FFFFFFFF  FFFFFFFF FFFFFFFF  02D80077 0000007F  0000007F 0000007F  0000007F 0000007F  0000007F 0000007F  0000007F 0000007F
0000007F 0000007F  0000007F 0000007F  0000007F 0000007F  0000007F 0000007F  0000007F 0000007F  0000007F 0000007F  0000007F 0000007F  0000007F 0000007F
0000007F 0000007F  0000007F 0000007F  0000007F 0000007F  0000007F 0000007F  0000007F 0000007F  0000007F 0000007F  0000007F 0000007F  0000007F 0000007F
0000007F 0000007F  0000007F 0000007F  0000007F 0000007F  0000007F 0000007F  0000007F 0000007F  0000007F 0000007F  0000007F 0000007F  0000007F 0000007F
0000007F 0000007F  0000007F 0000007F  0000007F 0000007F  0000007F 0000007F  0000007F 0000007F  0000007F 0000007F  0000007F 0000007F  0000007F 0000007F
0000007F 0000007F  0000007F 0000007F  0000007F 0000007F  0000007F 0000007F  0000007F 0000007F  0000007F 0000007F  0000007F 0000007F  0000007F 0000007F
0000007F 0000007F  0000007F 0000007F  0000007F 0000007F  0000007F 0000007F  0000007F 0000007F  0000007F 0000007F  0000007F 0000007F  0000007F 0000007F
0000007F 0000007F  0000007F 0000007F  0000007F 0000007F  0000007F 0000007F  0000007F 0000007F  0000007F 0000007F  0000007F 0000007F  0000007F 0000007F
0000007F 0000007F  0000007F 0000007F  0000007F 0000007F  0000007F 0000007F  0000007F 0000007F  0000007F 0000007F  0000007F 0000007F  0000007F 0000007F
0000007F 0000007F  0000007F 0000007F  0000007F 0000007F  0000007F 0000007F  0000007F 0000007F  0000007F 0000007F  0000007F 0000007F  0000007F 0000007F
0000007F 0000007F  0000007F 0000007F  0000007F 0000007F  0000007F 0000007F  0000007F 0000007F  0000007F 0000007F  0000007F 0000007F  0000007F 0000007F
0000007F 0000007F  0000007F 0000007F  0000007F 0000007F  0000007F 0000007F  0000007F 0000007F  0000007F 0000007F  0000007F 0000007F  0000007F 0000007F

**Comment by henrikbrixandersen** [comment]
Please use our bug template when reporting bugs. You need to edit this issue to include the information requested in https://github.com/zephyrproject-rtos/zephyr/blob/main/.github/ISSUE_TEMPLATE/001_bug_report.md

**Comment by nordicjm** [comment]
If you are reporting a bug you need to fill in all the required information https://github.com/zephyrproject-rtos/zephyr/blob/main/.github/ISSUE_TEMPLATE/001_bug_report.md?plain=1 I have removed your doc link as it poses a possible security issue

**Comment by spayet2024** [comment]
hello, 

Sorry, i getting start on git hub. how can i edit my post? When i commited my post, i loose my description.

**Comment by Laczen** [comment]
Hi @spayet2024, could it be that the device is detecting a double ecc error (when reading from the last sector) and is generating a NMI? This kind of error (that can occur on your device) is not handled by any flash driver. If this is the case there is nothing that nvs can do to correct this.

**Comment by spayet2024** [comment]
Hi,
Thanks for your reply.
In fact, it could be that. I will investigate this lead. So, is zephyr remains blocked when 'nvs_flash_ate_rd' is called, and more particulary when call 'flash_read' or is it blocked beacause it can't go out of the while loop of 'nvs_recover_last_ate' ?

**Comment by Laczen** [comment]
> Hi, Thanks for your reply. In fact, it could be that. I will investigate this lead. So, is zephyr remains blocked when 'nvs_flash_ate_rd' is called, and more particulary when call 'flash_read' or is it blocked beacause it can't go out of the while loop of 'nvs_recover_last_ate' ?

If my assumption is right it would be "blocked" because it can't do a `flash_read` without generating a NMI. You could test this by not mounting nvs but instead just perform a read of all data in the storage area. If the flash has a problem it should halt. From your data I suspect the problem is in the last sector.

**Comment by spayet2024** [comment]
Hi,

You are right, the problem occurs in the last sector. Is there a way to recover of ecc double error when use zephyr? if i understand, this flag is triggered when you read the corrupted flash, but it's too late and the device is blocked.

**Comment by Laczen** [comment]
> Hi,
> 
> You are right, the problem occurs in the last sector. Is there a way to recover of ecc double error when use zephyr? if i understand, this flag is triggered when you read the corrupted flash, but it's too late and the device is blocked.

Hi, so you can confirm this problem also occurs when doing only flash_read ? At the moment there is no way to recover from this problem. The flash drivers would need to be modified to support this behavior of a flash device.
