### ISSUE TITLE
Building TFM applications on nRF5340

### ISSUE THREAD

**Issue by norrathep** [zephyrproject-rtos/zephyr#80848]
**Describe the bug**
tfm_ipc sample fails to print anything when I build and run it on nRF5340-PDK.
Non-TFM samples (e.g., hello_world) seem to work though.
I tried using both west tool and the steps from [this page](https://docs.zephyrproject.org/latest/samples/tfm_integration/tfm_ipc/README.html#on-nrf5340-and-nrf9160).

I also tried the same tfm_ipc sample on nRF9160-DK board and it works fine.

**To Reproduce**
1. west build -p -b nrf5340dk/nrf5340/cpuapp/ns ./zephyr/samples/tfm_integration/tfm_ipc/ && west flash
2. Observe no printout from /dev/ttyACM0,1,2

OR

```
cd <ZEPHYR_ROOT>/samples/tfm_integration/tfm_ipc/
rm -rf build
mkdir build && cd build
cmake -GNinja -DBOARD=nrf5340dk/nrf5340/cpuapp/ns ..
ninja
nrfjprog -f NRF53 --program tfm/bin/bl2.hex --sectorerase --verify
ninja flash
```

**Expected behavior**
The following printout:
```
[INF] Starting bootloader
[INF] Beginning BL2 provisioning
[WRN] TFM_DUMMY_PROVISIONING is not suitable for production! This device is NOT SECURE
[INF] Image index: 1, Swap type: none
[INF] Image index: 0, Swap type: none
[INF] Bootloader chainload address offset: 0x80000
[INF] Jumping to the first image slot
[INF] Beginning TF-M provisioning
[WRN] TFM_DUMMY_PROVISIONING is not suitable for production! This device is NOT SECURE
[WRN] This device was provisioned with dummy keys. This device is NOT SECURE
[Sec Thread] Secure image initializing!
Booting TF-M v2.0.0
Creating an empty ITS flash layout.
Creating an empty PS flash layout.
[INF][Crypto] Provisioning entropy seed... complete.
Timer with period zero, disabling
*** Booting Zephyr OS build v3.6.0 ***
TF-M IPC on (.*)
The version of the PSA Framework API is 257.
The PSA Crypto service minor version is 1.
Generating 256 bytes of random data:
[...]
```

**Impact**
Can't move on to implement my code on nRF5340-PDK board

**Environment (please complete the following information):**

 - OS: Ubuntu 24.04 on VMWare
 - Toolchain: Zephyr OS build v3.7.0-4378-g1a89e1640c14

**Comment by nordicjm** [comment]
PDK support was dropped years ago, it is not supported, you need to update to a DK. You can possibly get a very old version of zephyr to use with a PDK, the silicon however is not supported
