### ISSUE TITLE
tests/net/ieee802154/crypto fails on Quark SE / x86

### ISSUE THREAD

**Issue by inakypg** [zephyrproject-rtos/zephyr#8086]
commit v1.12.0-rc2-45-g43553da9b2

No output is printed upon booting (no Booting Zephyr or anything at all) [same result on six different boards]

**Comment by tbursztyka** [comment]
I'll check but not even the boot message... isn't this the same as #8039 ?

**Comment by inakypg** [comment]
not sure if it is the same -- the symptoms look the same,

**Comment by inakypg** [comment]
Confirmed fixed.
