### ISSUE TITLE
tests/kernel/xip fails on QEMU riscv32 with no output

### ISSUE THREAD

**Issue by inakypg** [zephyrproject-rtos/zephyr#8088]
commmit v1.12.0-rc2-45-g43553da9b2

No output is produced on the console, not even 'Booting Zephyr'.

**Comment by spoorthik** [comment]
This issue is found only when CONFIG_BOOT_DELAY is introduced. #5485 reports the same issue.

**Comment by nashif** [comment]
duplicate
