### ISSUE TITLE
tests/drivers/watchdog/wdt_basic_api fails on Quark SE / ARC with no output

### ISSUE THREAD

**Issue by inakypg** [zephyrproject-rtos/zephyr#8096]
Toolchain: ZEPHYR_GCC_VARIANT=zephyr

Commit 43553da9b2bb9e537185695899fb5184c3b17ebe

No output is generated by the targets (tried in six different Quark boards

**Comment by tbursztyka** [comment]
@inakypg can you retry? I haven't been able to find the original culprit: before we were setting various priorities such as 2 or 3 etc... Now it seems that ARC only takes 0 or 1. As you can see, my patch fixes a line that was introduced 2 years ago.

Now I get output. However, there is a crash but that's another issue then.

**Comment by nashif** [comment]
only partially fixed by #8153
