### ISSUE TITLE
tests/drivers/rtc/rtc_basic_api assertion failure on Arduino 101 / ARC

### ISSUE THREAD

**Issue by inakypg** [zephyrproject-rtos/zephyr#8099]
Toolchain: ZEPHYR_GCC_VARIANT=zephyr

Commit 43553da9b2bb9e537185695899fb5184c3b17ebe

Not even a Booting Zephyr message is found, except for:

```
ASSERTION FAIL [prio < 2] @ zephyr.git/arch/arc/core/irq_manage.c:85:
	invalid priority 2 for irq 47
```

Also affects tests/drivers/aon_counter/aon_api, tests/drivers/adc/adc_simple|adc_api on Quark SE

**Comment by pswarnak** [comment]
**Additional Information:**
Same error signature seen for "tests/power/power_states".

Console output: 
ASSERTION FAIL [prio < 2] @ /home/pswarnak/workspace/1.12_execution/zephyr/arch/arc/core/irq_manage.c:85:
invalid priority 2 for irq 21

CC @ramakrishnapallala
