### ISSUE TITLE
External module request: nRF Wi-Fi (split off of hal_nordic)

### ISSUE THREAD

**Issue by carlescufi** [zephyrproject-rtos/zephyr#81002]
## Origin

nRF Wi-Fi is a cross-platform, RTOS-agnostic Wi-Fi framework for nRF Wi-Fi ICs.

The current repo is here:
https://github.com/nrfconnect/nrf_wifi

Note that this code is currently in [hal_nordic](https://github.com/zephyrproject-rtos/hal_nordic/tree/master/drivers/nrf_wifi)

## Purpose

The purpose of this request is to split up the nRF Wi-Fi source code from hal_nordic, for a couple of reasons:

1. The releases of nrfx (our HAL) and nrf_wifi are completely independent, and having them in the same repo brings issues when updating the SHA of it in the main manifest
2. While nrfx belongs to Zephyr as a built-in module, we think that nrf_wifi could be entirely optional
3. This aligns hal_nordic to what other vendors do, such as ST with [hal_st](https://github.com/zephyrproject-rtos/hal_st) and [hal_stm32](https://github.com/zephyrproject-rtos/hal_stm32)

## Mode of integration

As a **optional** module, with the name `nrf_wifi`.

## Maintainership

@sachinthegreen  @krish2718

## Pull Request

https://github.com/zephyrproject-rtos/zephyr/pull/81101

## Description

This is an existing component, it essentially contains the software framework necessary for the Wi-Fi functionality in the nRF Wi-Fi ICs.

## Dependencies

None

## Revision

1c85b3c927897c752c155560e263d4947ddcc6e4

## License

`SPDX-License-Identifier: BSD-3-Clause`

**Comment by nashif** [comment]
https://github.com/zephyrproject-rtos/zephyr/pull/81101/commits/c4c2b58e29ea6677008329a3069a8435dd1831c7 is not adding this as optional module, it is in the default manifest.

**Comment by krish2718** [comment]
> [c4c2b58](https://github.com/zephyrproject-rtos/zephyr/commit/c4c2b58e29ea6677008329a3069a8435dd1831c7) is not adding this as optional module, it is in the default manifest.

Sorry, https://github.com/zephyrproject-rtos/zephyr/pull/81101/commits/ca5bcc8f2fce547eb3fa683edd73ad87d492b80e#diff-d7f4082837dc3cb270fcf1abd68188216fdadee294e01611b8ca59ddea7fdbb3 reverts that change, I will fix the commits, but overally that PR still adds it to the optional manifests.

**Comment by krish2718** [comment]
Fixed and updated the PR.

**Comment by carlescufi** [comment]
Repo created: https://github.com/zephyrproject-rtos/nrf_wifi
