### ISSUE TITLE
Typo error in soc nxp rt11xx usb2 clock initialization

### ISSUE THREAD

**Issue by Raymond0225** [zephyrproject-rtos/zephyr#81027]
**Describe the bug**

In file soc.c under directory soc/nxp/imxrt/imxrt11xx line 539.  This part of code is obviously used to initialize the usbs but use usb1 as device tree node label.

**Comment by decsny** [comment]
@Raymond0225 it looks like you put the content in markdown comments, so the issue appeared empty, i fixed it for you, if i missed something you will need to edit also
