### ISSUE TITLE
soc: nrf54h: GPD service calls may stall

### ISSUE THREAD

**Issue by gmarull** [zephyrproject-rtos/zephyr#81057]
**Describe the bug**

nRF54H SoC GPD service may stall busy-looping for nRFS result

**To Reproduce**

Enable the service and use `nrf_gpd_request()` on a driver.

**Expected behavior**

Request succeeds

**Impact**

Blocker

**Logs and console output**

N/A

**Environment (please complete the following information):**

 - OS: Linux
 - Toolchain Zephyr SDK
 - Commit SHA or Version used c3466b14d09b1e51b6ca472f3b3654e40cba12d8

**Additional context**

N/A

**Comment by nordic-piks** [comment]
Triaged internally
