### ISSUE TITLE
make 'rom_report' misreports _sw_isr_table

### ISSUE THREAD

**Issue by vakulgarg** [zephyrproject-rtos/zephyr#8108]
I am creating a 'rom_report' for mbedtls_sslclient.
The symbol _sw_isr_table is shown and counted under ext/lib/crypto/mbedtls/lib/bignum.c ROM usage.

_sw_isr_table is not defined in mbedtls library. Thus the rom usage of mbedtls is seen inflated.

**Comment by nashif** [comment]
can't reproduce, in other mbedtls samples this appears in the root.
