### ISSUE TITLE
doc: Documentation typo in 'boards/weact/blackpill_f401cc/doc/index'

### ISSUE THREAD

**Issue by thetechmusician** [zephyrproject-rtos/zephyr#81253]
**Links and text typo**

In the section [supported features](https://docs.zephyrproject.org/latest/boards/weact/blackpill_f401cc/doc/index.html#supported-features), 'blackpill_f401ce' is mentioned instead of 'blackpill_f401cc'.

"The default configuration can be found in [boards/weact/blackpill_f401ce/blackpill_f401ce_defconfig](https://github.com/zephyrproject-rtos/zephyr/blob/main/boards/weact/blackpill_f401ce/blackpill_f401ce_defconfig)".
The above link should have been [this link](https://github.com/zephyrproject-rtos/zephyr/blob/main/boards/weact/blackpill_f401cc/blackpill_f401cc_defconfig) instead.

**Environment**

* Page: `boards/weact/blackpill_f401cc/doc/index`
* Version: main
* SHA-1: f2c2cc334d486ec613463774ac009df3982b3221

**Comment by kartben** [comment]
@thetechmusician thanks for noticing it and opening an issue! Can you please send a pull request to fix it, by any chance?

**Comment by thetechmusician** [comment]
@kartben added pull request for the fix [#81291](https://github.com/zephyrproject-rtos/zephyr/pull/81291)
