### ISSUE TITLE
Broken Link: i2c_bitbang_configure function description specification

### ISSUE THREAD

**Issue by spchee** [zephyrproject-rtos/zephyr#81269]
Link at https://github.com/zephyrproject-rtos/zephyr/blob/65511eacf9d17bf22a6cf28c3ace467a86a159f5/drivers/i2c/i2c_bitbang.c#L17 is broken.

Needs to be replaced with https://www.nxp.com/docs/en/user-guide/UM10204.pdf.

**Comment by henrikbrixandersen** [comment]
Fixed in #81556.
