### ISSUE TITLE
stm3210c_eval.dts_compiled: Warning

### ISSUE THREAD

**Issue by hongshui3000** [zephyrproject-rtos/zephyr#8132]
-- Found PythonInterp: C:/Python36/python3.exe (found suitable version "3.6.4", minimum required is "3.4")
-- Selected BOARD stm3210c_eval
Zephyr version: 1.12.0
Parsing Kconfig tree in D:/work/fr3190/software/V2/zephyr//Kconfig
Using D:/work/fr3190/software/V2/zephyr/boards/arm/stm3210c_eval/stm3210c_eval_defconfig as base
Merging D:/work/fr3190/software/V2/zephyr/samples/hello_world/prj.conf
-- Generating zephyr/include/generated/generated_dts_board.h
stm3210c_eval.dts_compiled: Warning (unit_address_vs_reg): Node /soc/pin-controller@40010800/usart1@0 has a unit name, but no reg property
stm3210c_eval.dts_compiled: Warning (unit_address_vs_reg): Node /soc/pin-controller@40010800/usart2@0 has a unit name, but no reg property
stm3210c_eval.dts_compiled: Warning (unit_address_vs_reg): Node /soc/pin-controller@40010800/usart2@1 has a unit name, but no reg property
stm3210c_eval.dts_compiled: Warning (unit_address_vs_reg): Node /soc/pin-controller@40010800/usart3@0 has a unit name, but no reg property
stm3210c_eval.dts_compiled: Warning (unit_address_vs_reg): Node /soc/pin-controller@40010800/uart4@0 has a unit name, but no reg property
stm3210c_eval.dts_compiled: Warning (unit_address_vs_reg): Node /leds/led@0 has a unit name, but no reg property
stm3210c_eval.dts_compiled: Warning (unit_address_vs_reg): Node /gpio_keys/button@0 has a unit name, but no reg property

**Comment by erwango** [comment]
Hi, Thanks for reporting.
This warning is known (#https://github.com/zephyrproject-rtos/zephyr/issues/7013), and for now we prefer keeping it and remove it with a waiver rather than fixing it (because of drawbacks). Detailled here: #7564.
Closing this ticket
