### ISSUE TITLE
Driver for BMA400 accelerometer

### ISSUE THREAD

**Issue by pdunaj** [zephyrproject-rtos/zephyr#8139]

**Comment by nashif** [comment]
can you please add more information? What is this about?

**Comment by pdunaj** [comment]
Hi @nashif , sure. We need a driver for BMA400 accelerometer. Minimum is to support delta trigger as we will use it for device wake up. I don't know what more can be said about it.
We will work on the driver if nobody implements it earlier.

**Comment by zille77** [comment]
Does anybody have an api or command set already? Tried to read registers (with no useful information received - 8-bit SPI) but it seems different from the other chips before.

**Comment by pdunaj** [comment]
@zille77 not yet

**Comment by carlescufi** [comment]
Please submit a Pull Request

**Comment by Olfox59** [comment]
Hi guys, any news about this driver please ? thanks a lot

**Comment by tautologyclub** [comment]
Working on this currently.

**Comment by AndrewAWG97** [comment]
> Working on this currently.

any news about the driver .. thanks in advance

**Comment by tautologyclub** [comment]
> > Working on this currently.
> 
> any news about the driver .. thanks in advance

So what happened was that we did like 60-70% of a driver, then our customer decided to use another accelerometer. We still have plans to finalize and upstream our work, but obviously the urgency is slightly lower now. I can push a WIP pull request if you're in a hurry though?

**Comment by AndrewAWG97** [comment]
> 

I will be more than thankful if you send me the basics of of the driver as I don't a fully implemented one.

**Comment by tautologyclub** [comment]
https://github.com/zephyrproject-rtos/zephyr/pull/52193

**Comment by rlimberger** [comment]
Im trung to use the BMA4xx driver (via i2c) in 2.7.0. The driver seems to init the device ok but I am getting a "SECURE FAULT" as soon as I do a `sensor_sample_fetch`. Attached is a minimal project to reproduce the issue.
[bma4xx_example.zip](https://github.com/user-attachments/files/16685287/bma4xx_example.zip)
