### ISSUE TITLE
Wrong load address of .last_ram_section

### ISSUE THREAD

**Issue by FranciszekPin** [zephyrproject-rtos/zephyr#81392]
Fixed by #80554

cc @mmahadevan108

**Describe the bug**

When building `hello_world` for `qemu_x86_tiny`, `.last_ram_section` gets wrong LMA - it's the same as virtual address, but it should be physical.

`GROUP_NOLOAD_LINK_IN` macro takes virtual and load region addresses, so `.last_ram_section` definition in `ram-end.ld`:

```
SECTION_PROLOGUE(.last_ram_section, (NOLOAD),)
[...]
    } GROUP_NOLOAD_LINK_IN(RAMABLE_REGION, ROMABLE_REGION)
```

looks like a typo.

**To Reproduce**

Build `hello_world` for `qemu_x86_tiny`:
```
west build -p -b qemu_x86_tiny samples/hello_world
```

Print address of `LMA` section:

```
objdump -h build/zephyr/zephyr.elf
[...]
Sections:                                                                                                                                                       
Idx Name          Size      VMA       LMA       File off  Algn
[...]
 21 .last_ram_section 00000ff0  40115010  40115010  0000f0e0  2**0
                  ALLOC
```

**Expected behavior**
Following change in `ram-end.ld`:

```
diff --git a/include/zephyr/linker/ram-end.ld b/include/zephyr/linker/ram-end.ld
index ad4da2b46f3..71d4571e0fb 100644
--- a/include/zephyr/linker/ram-end.ld
+++ b/include/zephyr/linker/ram-end.ld
@@ -12,4 +12,4 @@
 	_image_ram_size = _image_ram_end - _image_ram_start;
 	_end = .; /* end of image */
 	z_mapped_end = .;
-    } GROUP_NOLOAD_LINK_IN(RAMABLE_REGION, RAMABLE_REGION)
+    } GROUP_NOLOAD_LINK_IN(RAMABLE_REGION, ROMABLE_REGION)
```

Fixes the issue:

```
objdump -h build/zephyr/zephyr.elf
[...]
Sections:                                                                                                                                                       
Idx Name          Size      VMA       LMA       File off  Algn
[...]
 21 .last_ram_section 00000ff0  40115010  00515010  0000f0c0  2**0
                  ALLOC
```
This platform has `dram` between `0x100000` and `0x140000` and `flash` between `0x500000` and `0x900000`, so `.last_ram_section` lands in `flash`.

**Impact**
`.last_ram_section` is loaded at virtual address instead of physical.

**Environment (please complete the following information):**

 - OS: Linux
 - Toolchain: Zephyr SDK
 - Zephyr SHA: `a6466249a9c17eecffff35e65dc73ce7fbd115f9`

**Comment by mmahadevan108** [comment]
Fixed by https://github.com/zephyrproject-rtos/zephyr/pull/80554
