### ISSUE TITLE
west debug: openocd: console garbled with `--tui` option

### ISSUE THREAD

**Issue by erwango** [zephyrproject-rtos/zephyr#81405]
**Describe the bug**

gdb option `--tui` to split screen and display source along with gdb console is available as an openocd runner option.
Though, when used with `west debug`, it provides a garbled output:

![Screenshot from 2024-11-14 14-10-33](https://github.com/user-attachments/assets/40ab865d-6513-4ba2-9d39-2e93f13f6d67)

When using `--tui` gdb arg outside of `west debug`, it works as expected
![Screenshot from 2024-11-14 14-07-55](https://github.com/user-attachments/assets/0b4bf11d-3995-45fe-9057-a89f8940dd14)
with following commands run in 2 different windows:
```
$ ~/zephyr-sdk-0.17.0/sysroots/x86_64-pokysdk-linux/usr/bin/openocd -s ~/zephyrproject/zephyr/boards/st/nucleo_l152re/support -s ~/zephyr-sdk-0.17.0/sysroots/x86_64-pokysdk-linux/usr/share/openocd/scripts -f ~/zephyrproject/zephyr/boards/st/nucleo_l152re/support/openocd.cfg -c 'tcl_port 6333' -c 'telnet_port 4444' -c 'gdb_port 3333' '-c init' '-c targets' '-c halt'
```
```
$ ~/zephyr-sdk-0.17.0/arm-zephyr-eabi/bin/arm-zephyr-eabi-gdb-py -ex 'target extended-remote :3333' build/nucleo_l152re/zephyr/zephyr.elf -tui -ex load
```

**To Reproduce**
1. west build -b nucleo_f401re sample/hello_word
2. west debug -d build --tui

**Expected behavior**
`--tui` should help debug experience, not garble it.

**Impact**
`west debug` not usable with --tui option

**Logs and console output**

**Environment (please complete the following information):**

 - OS: (e.g. Linux, MacOS, Windows): Ubuntu
 - Toolchain (e.g Zephyr SDK, ...): zephyr-sdk-0.17.0
 - Commit SHA or Version used: v4.0.0.rc3

**Additional context**
~~I suspect a timing issue between gdb server and client command~~ Doesn't seem to be the case.

**Comment by kartben** [comment]
@pdgendt thoughts on this one?

**Comment by pdgendt** [comment]
I don't have something at hand to test the `openocd` runner, what's the output of `west debug` without the `--tui` option?

My guess would be that the `gdb` server is also started as a child proces for `west`?

**Comment by erwango** [comment]
>  what's the output of west debug without the --tui option?

Works as expected.
![Screenshot from 2024-12-04 09-09-56](https://github.com/user-attachments/assets/f6c4620e-3b2a-4662-882e-6f26ca05b2c7)

**Comment by pdgendt** [comment]
> Works as expected.

Yes, I didn't doubt that, but from the garbled image there's a print `Listening on por` in between all the output. Is this also printed when not passing `--tui`? This to confirm my suspicion of having the server output interfering with the client output.

**Comment by pdgendt** [comment]
Does the following naive fix help?

```diff
diff --git a/scripts/west_commands/runners/openocd.py b/scripts/west_commands/runners/openocd.py
index 9b39791e1ee..0e477135687 100644
--- a/scripts/west_commands/runners/openocd.py
+++ b/scripts/west_commands/runners/openocd.py
@@ -396,7 +396,7 @@ class OpenOcdBinaryRunner(ZephyrBinaryRunner):
         self.print_gdbserver_message()

         if command in ('attach', 'debug'):
-            self.run_server_and_client(server_cmd, gdb_cmd)
+            self.run_server_and_client(server_cmd, gdb_cmd, stderr=subprocess.DEVNULL)
         elif command == 'rtt':
             self.print_rttserver_message()
             server_proc = self.popen_ignore_int(server_cmd)
```

**Comment by erwango** [comment]
> Does the following naive fix help?

Nope
```
-- runners.openocd: OpenOCD GDB server running on port 3333; no thread info available
FATAL ERROR: command exited with status 1: ~/zephyr-sdk-0.17.0/arm-zephyr-eabi/bin/arm-zephyr-eabi-gdb-py -tui -ex 'target extended-remote :3333' build/disco_l475_iot1/zephyr/zephyr.elf -ex load
```

**Comment by kartben** [comment]
@erwango I am not familiar with TUI but it looks like west has supposedly included support for it since almost forever. Just curious if you were using it successfully before and it broke at some point?

**Comment by pdgendt** [comment]
New attempt:

```diff
diff --git a/scripts/west_commands/runners/openocd.py b/scripts/west_commands/runners/openocd.py
index 9b39791e1ee..d97cec1fe1e 100644
--- a/scripts/west_commands/runners/openocd.py
+++ b/scripts/west_commands/runners/openocd.py
@@ -396,7 +396,12 @@ class OpenOcdBinaryRunner(ZephyrBinaryRunner):
         self.print_gdbserver_message()

         if command in ('attach', 'debug'):
-            self.run_server_and_client(server_cmd, gdb_cmd)
+            server_proc = self.popen_ignore_int(server_cmd, stderr=subprocess.DEVNULL)
+            try:
+                self.run_client(gdb_cmd)
+            finally:
+                server_proc.terminate()
+                server_proc.wait()
         elif command == 'rtt':
             self.print_rttserver_message()
             server_proc = self.popen_ignore_int(server_cmd)
```

**Comment by erwango** [comment]
> New attempt:

and this will be the last... It works like a charm, now. Thanks !

**Comment by kartben** [comment]
Confirmed!
It does look like this will need to be applied (factorized?) to other runners too. I can confirm that a similar fix seems to be needed for e.g. pyocd runner, so I wouldn't be surprized if it's needed for jlink too... maybe others?

**Comment by pdgendt** [comment]
Maybe some option like `suppress_server_output` could be introduced for all runners?

**Comment by pdgendt** [comment]
> @pdgendt @erwango sounds like you have a workaround, are any of you planning to open a PR for this?

I'll open a PR with the current suggestion, I don't have the bandwidth for a more generic solution.

**Comment by marc-hb** [comment]
> stderr=subprocess.DEVNULL

Merely discarding stderr (as opposed to redirecting it) is an "anti-pattern" and unsurprisingly hiding issues:
- #108961
- #108806
