### ISSUE TITLE
stm32: stm32u0 clock dt-binding: the RTC_SEL macro should use the BDCR_REG value

### ISSUE THREAD

**Issue by ExaltZephyr** [zephyrproject-rtos/zephyr#81493]
**Describe the bug**

In [stm32u0_clock.h:90](https://github.com/zephyrproject-rtos/zephyr/blob/main/include/zephyr/dt-bindings/clock/stm32u0_clock.h#L90)
The `RTC_SEL` macro should use the `BDCR_REG` register value instead of `CSR_REG`, the register `CSR_REG` does not exist for the STM32U0 boards.

**To Reproduce**
The issue can be seen when using the `RTC_SEL` macro on the devicetree, as of now there's no support for the RTC, but it will be visible once an RTC device is supported.

**Expected behavior**
It is expected for the macro `RTC_SEL` to use `BDCR_REG` register so the dts build would not fail.

**Impact**
Minimal impact, however, it blocks future support of the RTC device.

**Environment (please complete the following information):**
OS: Windows
Toolchain: Zephyr SDK
Commit SHA or Version used: ed48de2

**Additional context**
```diff
- #define RTC_SEL(val)		STM32_DOMAIN_CLOCK(val, 3, 8, CSR_REG)
+ #define RTC_SEL(val)		STM32_DOMAIN_CLOCK(val, 3, 8, BDCR_REG)
```

**Comment by henrikbrixandersen** [comment]
Please use our bug template when reporting bugs. You need to edit this issue to include the information requested in https://github.com/zephyrproject-rtos/zephyr/blob/main/.github/ISSUE_TEMPLATE/001_bug_report.md

**Comment by henrikbrixandersen** [comment]
Please use our bug template when reporting bugs. You need to edit this issue to include the information requested in https://github.com/zephyrproject-rtos/zephyr/blob/main/.github/ISSUE_TEMPLATE/001_bug_report.md

**Comment by rruuaanng** [comment]
If we can, I'll commit a PR :)
