### ISSUE TITLE
BUILD_ASSERT doesn't work outside gcc

### ISSUE THREAD

**Issue by andyross** [zephyrproject-rtos/zephyr#8160]
As discovered in #8093, our generic implementation of BUILD_ASSERT produces preprocessor errors always, not just when the assertion case is failing.

We don't actually use this on any platforms that don't already support C11's _Static_assert(), so this is fairly low priority.  But someone should look at it at some point.

**Comment by andyross** [comment]
Closing this one.  We have toolchain support for this already in non-gcc toolchains, and no gcc ones known are going to hit the "no _Static_assert() available" case anyway.

**Comment by rgundi** [comment]
@andyross XCC currently doesn't have _Static_assert() defined, but the generic BUILD_ASSERT defined in include/toolchain/common.h works just fine. I see that the error like below is generated only when the assertion case is failing.
warning: division by zero
error: enumerator value for ‘__build_assert15’ is not an integer constant
