### ISSUE TITLE
Zephyr Versions 3.7 and above no longer support promiscuous raw sockets (AF_PACKET) like traditional embedded Linux does.

### ISSUE THREAD

**Issue by bob2oneil** [zephyrproject-rtos/zephyr#81668]
**Describe the bug**

I have created a working application which under Native-POSIX emulation, acts like a radio, with a wired and wireless interfaces.  Under Linux, these Zephyr virtual Ethernet interfaces tie into 2 separate TAP interfaces created on the Linux host computer.

This has been a stable and working application using Zephyr v3.2.  It requires the use of Linux raw sockets (AF_PACKET) on the radio ingress, because the radio needs to act like a Layer 2 device, where the entire network packet is available including the 12 byte leading L2 header.  This includes the need to obtain from the wired interface, non-IPv4 packets such as ARPs and ICMPs.  Having support for just UDP and TCP sockets is not sufficient.

I also need to populate Layer 2 content such as broadcast destination MACs and broadcast IPs, content that might not be resolved by the Zephyr IP stack.

What I now observe with Zephry release 3.7 (and 4.0), that support for raw promiscuous sockets (AF_PACKET) is no longer supported.

What is the Zephyr philosophy on these network implementation changes?

How might I achieve the same behaviors supported by Zephyr 3.2 to more recent versions?

The target platform for testing is native-posix-64 (or native_sim_64 for Zephyr 3.7)

Testing involves walking into the Zephyr source code.

Zephyr v3.2 does not exhibit this behavior.

**To Reproduce**
"west build -p always -b native_sim_64 ${workspaceFolder} -- -DOVERLAY_CONFIG=${workspaceFolder}/conf/prj1.conf",

**Expected behavior**
An example of the open call from working code is as attached.

The primary API that now fails is as follows:

        sock = zsock_socket(AF_PACKET, SOCK_RAW, /* ipOnly ? ETH_P_IP : ETH_P_ALL */ ETH_P_ALL);
        
It returns a failure code of an unsupported protocol type.
        
initializeWiredInterface: Wired interface 'zethblk1.0', MTU 1600, MAC Address: 0200:5e08:5331
Interface flags for zethblk1.0: 0x341
[00:00:00.000,000] <err> app: createSocket: Failed to create socket: 97 - Address family not supported by protocol

**Impact**
Show stopper in behavior

**Logs and console output**
The callstack for the failure is as follows, with the failure being in inet_is_supported() method under Zephyr source:
  zephyr/subsys/net/lib/sockets.c

#if defined(CONFIG_NET_NATIVE)
static bool inet_is_supported(int family, int type, int proto)
{
	if (family != AF_INET && family != AF_INET6) {
		return false;
	}
inet_is_supported(int family, int type, int proto) (zephyr/subsys/net/lib/sockets/sockets.c:3950)
z_impl_zsock_socket(int family, int type, int proto) zephyr/subsys/net/lib/sockets/sockets.c:231)
zsock_socket(int protoint App::createSocket(int &sock, struct net_if *iface, const char *deviceName, bool ipOnly, bool rawSocket, int udpListenPort)

The Zephyr API to set promiscous mode now fails for a valid interface:

int ret = net_if_set_promisc(iface);

[00:00:00.000,000] <err> app: ifaceCallbackSetIfacePromisc: Cannot set promiscuous mode for interface 0x4fcb08 (-2 - No such file or directory)

Source code for the open API is as follows:

```
int App::createSocket(int &sock, struct net_if *iface, const char *deviceName, bool ipOnly, bool rawSocket, int udpListenPort)
{
    TRACE();

    // Create socket
    if (rawSocket)
    {
        // Create raw socket for any IP bound to iface
        // To receive all packets, the macro is ETH_P_ALL and to
        // receive IP packets, the macro is ETH_P_IP for the protocol field.
        // NOTE: Zephyr only supports ETH_P_ALL for raw sockets
#if (KERNEL_VERSION_MAJOR > 3)
        sock = zsock_socket(AF_INET, SOCK_RAW, /* ipOnly ? ETH_P_IP : ETH_P_ALL */ ETH_P_ALL);
#else
        sock = zsock_socket(AF_PACKET, SOCK_RAW, /* ipOnly ? ETH_P_IP : ETH_P_ALL */ ETH_P_ALL);
#endif
    }
    else
    {
        // Create UDP socket
        sock = zsock_socket(AF_INET, SOCK_DGRAM, IPPROTO_UDP);
    }

    if (sock < 0)
    {
        LOG_ERR("Failed to create socket: %d - %s", errno, strerror(errno));
        return -errno;
    }
    else
    {
        LOG_INF("Succeeded in creating socket %d", sock);
    }

    // NOTE: Kernel configuration NET_MAX_CONNS must be set to the total number
    // of socket connnections or else binding will fail.  This value defaults
    // to a value of 4.

    // Bind sockets
    if (rawSocket)
    {
        struct sockaddr_ll addr = {0};
        addr.sll_ifindex = net_if_get_by_iface(iface);

#if (KERNEL_VERSION_MAJOR > 3)
        addr.sll_family = AF_INET;
#else
        addr.sll_family = AF_PACKET;
#endif

        // Bind socket to specifiedint App::createSocket(int &sock, struct net_if *iface, const char *deviceName, bool ipOnly, bool rawSocket, int udpListenPort)
{
    TRACE();

    // Create socket
    if (rawSocket)
    {
        // Create raw socket for any IP bound to iface
        // To receive all packets, the macro is ETH_P_ALL and to
        // receive IP packets, the macro is ETH_P_IP for the protocol field.
        // NOTE: Zephyr only supports ETH_P_ALL for raw sockets
#if (KERNEL_VERSION_MAJOR > 3)
        sock = zsock_socket(AF_INET, SOCK_RAW, /* ipOnly ? ETH_P_IP : ETH_P_ALL */ ETH_P_ALL);
#else
        sock = zsock_socket(AF_PACKET, SOCK_RAW, /* ipOnly ? ETH_P_IP : ETH_P_ALL */ ETH_P_ALL);
#endif
    }
    else
    {
        // Create UDP socket
        sock = zsock_socket(AF_INET, SOCK_DGRAM, IPPROTO_UDP);
    }

    if (sock < 0)
    {
        LOG_ERR("Failed to create socket: %d - %s", errno, strerror(errno));
        return -errno;
    }
    else
    {
        LOG_INF("Succeeded in creating socket %d", sock);
    }

    // NOTE: Kernel configuration NET_MAX_CONNS must be set to the total number
    // of socket connnections or else binding will fail.  This value defaults
    // to a value of 4.

    // Bind sockets
    if (rawSocket)
    {
        struct sockaddr_ll addr = {0};
        addr.sll_ifindex = net_if_get_by_iface(iface);

#if (KERNEL_VERSION_MAJOR > 3)
        addr.sll_family = AF_INET;
#else
        addr.sll_family = AF_PACKET;
#endif

        // Bind socket to specified interface
        // NOTE: binding to iface for raw socket requires CONFIG_NET_SOCKETS_PACKET=y

        /*
         This is an initial version of packet socket support (special type raw socket)
         Packets are passed to and from the device driver without any changes in the packet
         headers.It's API caller responsibility to provide all the headers (e.g L2, L3 and so on)
         while sending. While receiving, packets (including all the headers) will be feed to sockets
         as it as from the driver.
        */
        LOG_DBG("Binding raw socket to interface %d (%p)", addr.sll_ifindex, net_if_get_by_index(addr.sll_ifindex));

        if (zsock_bind(sock, (const struct sockaddr *)&addr, sizeof(struct sockaddr_ll)) < 0)
        {
            LOG_ERR("Failed to bind raw packet socket: %d - %s", errno, strerror(errno));
            return -errno;
        }
        else
        {
            LOG_INF("Succeeded in binding raw packet socket %d to iface %p", sock, iface);
        }
    } interface
        // NOTE: binding to iface for raw socket requires CONFIG_NET_SOCKETS_PACKET=y

        /*
         This is an initial version of packet socket support (special type raw socket)
         Packets are passed to and from the device driver without any changes in the packet
         headers.It's API caller responsibility to provide all the headers (e.g L2, L3 and so on)
         while sending. While receiving, packets (including all the headers) will be feed to sockets
         as it as from the driver.
        */
        LOG_DBG("Binding raw socket to interface %d (%p)", addr.sll_ifindex, net_if_get_by_index(addr.sll_ifindex));

        if (zsock_bind(sock, (const struct sockaddr *)&addr, sizeof(struct sockaddr_ll)) < 0)
        {
            LOG_ERR("Failed to bind raw packet socket: %d - %s", errno, strerror(errno));
            return -errno;
        }
        else
        {
            LOG_INF("Succeeded in binding raw packet socket %d to iface %p", sock, iface);
        }
    }


```

**Comment by bob2oneil** [comment]
Thanks, will try that out

**Comment by jukkar** [comment]
> The other element of this issue was promiscuous mode which fails runtime unless the application is run with root privileges, and change from the previous implementation.
> 
> Was that change on purpose and is there any ramifications for that changes for boards other than Native-POSIX (Native-sim)?

Hmm, in order to set the promisc mode in Linux, one needs to have admin rights. I don't think this has changed.
There was this change a year ago 28bd5423fff961b82f084e2925fce6f56e9087ff, just wondering if you are referring to something like that.

**Comment by bob2oneil** [comment]
In the 3.2 code, the Zephyr net_if_set_promisc() API returned a successful value when setting promiscuous mode, where 3.7 will return an error, when the Zephyr binary was invoked without root privilege.  It could be that the newer version has more feedback from the network layer indicating a failure to do so whereas the previous might have just set some flags.   It is not unreasonable under Linux to expect root privilege, so I will close out this issue.  Thanks for the help and conversation.

**Comment by jukkar** [comment]
I am trying to understand what is going on with the promisc mode issue.

One big change between 3.2 and 3.7, is that the native_posix Ethernet driver in 3.2 was replaced by native_sim Ethernet driver in 3.7. They work a bit differently but are still mostly looking the same. Just wondering if this is related to your issue.

In 3.2 the code looks like this (from `eth_native_posix_adapt.c` file
```
#if defined(CONFIG_NET_PROMISCUOUS_MODE)
int eth_promisc_mode(const char *if_name, bool enable)
{
	if (!IS_ENABLED(CONFIG_ETH_NATIVE_POSIX_STARTUP_AUTOMATIC)) {
		return 0;
	}

	return ssystem("ip link set dev %s promisc %s",
		       if_name, enable ? "on" : "off");
}
#endif /* CONFIG_NET_PROMISCUOUS_MODE */
```
In 3.7 the same code looks like this:
```
int eth_promisc_mode(const char *if_name, bool enable)
{
	return ssystem("ip link set dev %s promisc %s",
		       if_name, enable ? "on" : "off");
}
```
The code is pretty much identical so you should not be able to set the host promiscuous mode without admin rights. It is totally different matter if the error is ignored etc.
Anyway, if you are able to get things working in 3.7 then no need to dig any deeper.
