### ISSUE TITLE
Nominate MaochenWang1 as a contributor

### ISSUE THREAD

**Issue by MaochenWang1** [zephyrproject-rtos/zephyr#81759]
1. Full Name:
    Maochen Wang
2. GitHub username:
    MaochenWang1
3. Organization:
    NXP
4. Supporting Documents:
https://github.com/zephyrproject-rtos/zephyr/pull/73119
https://github.com/zephyrproject-rtos/zephyr/pull/70275
https://github.com/zephyrproject-rtos/zephyr/pull/76289
https://github.com/zephyrproject-rtos/zephyr/pull/74579
https://github.com/zephyrproject-rtos/zephyr/pull/77866

**Comment by nashif** [comment]
Thank you for your contribution to the Zephyr project. 

An invite was sent to you to join the project. You can find the invite here: https://github.com/zephyrproject-rtos/zephyr/invitations.

Note that further access and permissoins to the project will be provided following the project [guidelines](https://docs.zephyrproject.org/latest/project/project_roles.html#tsc-project-roles).
