### ISSUE TITLE
objcopy bug？

### ISSUE THREAD

**Issue by hongshui3000** [zephyrproject-rtos/zephyr#8180]
objcopy  -V

GNU objcopy (GNU Tools for Arm Embedded Processors 7-2017-q4-major) 2.29.51.20171128
Copyright (C) 2017 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or (at your option) any later version.
This program has absolutely no warranty.

arm-none-eabi-objcopy -S -Obinary -R .comment -R COMMON -R .eh_frame zephyr.elf zephyr.x
zephyr.x ：data are correct

arm-none-eabi-objcopy -S -Obinary -R .comment -R COMMON -R .eh_frame zephyr.elf zephyr.bin

 zephyr.bin ：data error

**Comment by SebastianBoe** [comment]
There is not enough information here to reproduce or fix the bug.

Please post more information, e.g. a problem description and steps to reproduce.
