### ISSUE TITLE
Boards with 16 and 32MB flash has no suitable partition table

### ISSUE THREAD

**Issue by marekmatej** [zephyrproject-rtos/zephyr#81898]
**Describe the bug**
Some of ESP32 boards does include 16MB or even 32MB flash, but maximum flash size supported by the current partition table is 8MB.

**To Reproduce**
Trying to use bigger slots than 8MB flash partition tables provide.

**Expected behavior**
Ability to utilize flash bigger than 8MB.

**Comment by de-nordic** [comment]
Closed with https://github.com/zephyrproject-rtos/zephyr/pull/81874
