### ISSUE TITLE
CI failure for net.mqtt_sn.packet on some platforms

### ISSUE THREAD

**Issue by JiafeiPan** [zephyrproject-rtos/zephyr#82003]
CI failed for net.mqtt_sn.packet  on some ARM Cortex-A Core platforms, such as board: imx95_evk/mimx9596/a55, imx8mp_evk/mimx8ml8/a53 etc.

**Describe the bug**
INFO    - The following issues were found (showing the top 10 items):
INFO    - 1) net.mqtt_sn.packet on imx95_evk/mimx9596/a55 error (Build failure)
INFO    - 
INFO    - To rerun the tests, call twister using the following commandline:
INFO    - west twister -p <PLATFORM> -s <TEST ID> --no-detailed-test-id, for example:
INFO    - 
INFO    - west twister -p imx95_evk/mimx[959](https://github.com/zephyrproject-rtos/zephyr/actions/runs/12013099283/job/33490833324?pr=81012#step:12:961)6/a55 -s net.mqtt_sn.packet --no-detailed-test-id
INFO    - or with west:
INFO    - west build -p -b imx95_evk/mimx9596/a55 tests/net/lib/mqtt_sn_packet -T net.mqtt_sn.packet
INFO    - -+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
INFO    - Run completed

/__w/zephyr/zephyr/subsys/net/lib/mqtt_sn/mqtt_sn.c: In function 'mqtt_sn_publish_create':
/__w/zephyr/zephyr/subsys/net/lib/mqtt_sn/mqtt_sn.c:187:33: error: format '%hu' expects argument of type 'int', but argument 2 has type 'size_t' {aka 'long unsigned int'} [-Werror=format=]
  187 |                         LOG_ERR("Can't create PUB: Too much data (%" PRIu16 ")", data->size);
      |                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~             ~~~~~~~~~~
      |                                                                                      |
      |                                                                                      size_t {aka long unsigned int}
/__w/zephyr/zephyr/include/zephyr/logging/log_core.h:315:50: note: in definition of macro 'Z_LOG2'
  315 |                         z_log_printf_arg_checker(__VA_ARGS__);                                     \
      |                                                  ^~~~~~~~~~~
/__w/zephyr/zephyr/include/zephyr/logging/log.h:44:25: note: in expansion of macro 'Z_LOG'
   44 | #define LOG_ERR(...)    Z_LOG(LOG_LEVEL_ERR, __VA_ARGS__)
      |                         ^~~~~
/__w/zephyr/zephyr/subsys/net/lib/mqtt_sn/mqtt_sn.c:187:25: note: in expansion of macro 'LOG_ERR'
  187 |                         LOG_ERR("Can't create PUB: Too much data (%" PRIu16 ")", data->size);
      |                         ^~~~~~~
/__w/zephyr/zephyr/subsys/net/lib/mqtt_sn/mqtt_sn.c: In function 'mqtt_sn_topic_create':
/__w/zephyr/zephyr/subsys/net/lib/mqtt_sn/mqtt_sn.c:245:25: error: format '%hu' expects argument of type 'int', but argument 2 has type 'size_t' {aka 'long unsigned int'} [-Werror=format=]
  245 |                 LOG_ERR("Can't create topic: name too long (%" PRIu16 ")", name->size);
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~             ~~~~~~~~~~
      |                                                                                |
      |                                                                                size_t {aka long unsigned int}
/__w/zephyr/zephyr/include/zephyr/logging/log_core.h:315:50: note: in definition of macro 'Z_LOG2'
  315 |                         z_log_printf_arg_checker(__VA_ARGS__);                                     \
      |                                                  ^~~~~~~~~~~
/__w/zephyr/zephyr/include/zephyr/logging/log.h:44:25: note: in expansion of macro 'Z_LOG'
   44 | #define LOG_ERR(...)    Z_LOG(LOG_LEVEL_ERR, __VA_ARGS__)
      |                         ^~~~~
/__w/zephyr/zephyr/subsys/net/lib/mqtt_sn/mqtt_sn.c:245:17: note: in expansion of macro 'LOG_ERR'
  245 |                 LOG_ERR("Can't create topic: name too long (%" PRIu16 ")", name->size);
      |                 ^~~~~~~
cc1: all warnings being treated as errors
ninja: build stopped: subcommand failed.

**To Reproduce**

west build -p -b imx95_evk/mimx9596/a55 tests/net/lib/mqtt_sn_packet -T net.mqtt_sn.packet
west build -p -b imx8mp_evk/mimx8ml8/a53 tests/net/lib/mqtt_sn_packet -T net.mqtt_sn.packet

**Expected behavior**

Fix CI build issue.

**Impact**

CI fails for some platforms.

**Comment by jukkar** [comment]
There is a fix for this in https://github.com/zephyrproject-rtos/zephyr/pull/81803
