### ISSUE TITLE
Tests: arm_irq_vector_table: Assertion failure on nrf52840_pca10056

### ISSUE THREAD

**Issue by spoorthik** [zephyrproject-rtos/zephyr#8200]
**Test location:** tests/kernel/arm_irq_vector_table

**Test identifier:** arch.interrupt.arm_irq_vector_table

**Execution log:**
```
Running test suite vector_table
===================================================================
starting test - test_arm_irq_vector_table
Test Cortex-M3 IRQ installed directly in vector table
ASSERTION FAIL [RTC1_IRQn >= 48] @ zephyr.git/tests/kernel/arm_irq_vector_table/src/arm_irq_vector_table.c:105:
RTC1_IRQn < NUM_IRQs. Consider rework manual vector table.
```
**Latest commit on which the test fails:** 265f502b8e48ba3299bfbbef7814cbab196af0b3

**Comment by carlescufi** [comment]
Investigating

**Comment by carlescufi** [comment]
The reason this is failing is that `CONFIG_NUM_IRQS` is set to 3 in the `prj.conf` but it actually gets the value from the SoC, leaving it at 39 which makes the assertion trigger.
@ulfalizer any ideas on why this is the case (it didn't use to be)
