### ISSUE TITLE
doc: Documentation issue in 'build/dts/bindings-syntax'

### ISSUE THREAD

**Issue by eriwave** [zephyrproject-rtos/zephyr#82031]
**Describe the bug**

Where it reads:
"In this example, a node with compatible "manufacturer,serial" must contain a node named current-speed."

believe it should be:
"In this example, a node with compatible "manufacturer,serial" must contain a **property** named current-speed."

**Environment**

* Page: `build/dts/bindings-syntax`
* Version: main
* SHA-1: 9e4328cdcd7fbd13c738e962fd9832de9e14f4ac

**Comment by kartben** [comment]
Hi @eriwave -- thanks for spotting this! Would you like to send a pull request to get this fixed?

**Comment by eriwave** [comment]
Sure, I'll prepare a PR.
