### ISSUE TITLE
tests: posix: common: userspace: qemu_arc_em triggers assertion in linker script

### ISSUE THREAD

**Issue by cfriedt** [zephyrproject-rtos/zephyr#82059]
**Describe the bug**
At some point there was a disconnect in `KOBJECT_RODATA_SZ` between

`build/zephyr/include/generated/zephyr/linker-kobject-prebuilt-rodata.h`
```cpp
#ifndef KOBJECT_RODATA_SZ
#define KOBJECT_RODATA_SZ 348
#endif
```

and the actual rodata generated.

from `zephyr_final.map`
```
                0x0000000080028860                _kobject_rodata_area_start = .
 *(SORT_BY_ALIGNMENT(.kobject_data.rodata*))
 .kobject_data.rodata
                0x0000000080028860      0x24c zephyr/kobject_hash_renamed.o
                0x0000000080028aac                _kobject_rodata_area_end = .
                0x000000008001bb58                _kobject_rodata_area_used = (_kobject_rodata_area_end - _kobject_rodata_area_start)
                0x0000000000000000                ASSERT ((_kobject_rodata_area_used <= 0x15c), scripts/build/gen_kobject_placeholders.py did not reserve enough space for kobject rodata.)
```

In the case above the value of `KOBJECT_RODATA_SZ` is 348 (0x15c), but the actual `_kobject_rodata_area_used` is `0x80028aac - 0x80028860 = 0x24c = 588`.

Please also mention any information which could help others to understand
the problem you're facing:
 - What target platform are you using? `qemu_arc/qemu_arc_em`
 - What have you tried to diagnose or workaround this issue? Followed build steps, inspected build output 
 - Is this a regression? It seems not to be. This has passed CI and manual testing in the past already. But seems to be consistently reproducible at least on the latest from `main`.

**To Reproduce**
1. `west twister -i -p qemu_arc/qemu_arc_em -s tests/posix/common/portability.posix.common.userspace`
2. See error

**Expected behavior**
Test passes

**Impact**
CI is broken.

**Logs and console output**
```shell
west twister -i -p qemu_arc/qemu_arc_em -s tests/posix/common/portability.posix.common.userspace
...
scripts/build/gen_kobject_placeholders.py did not reserve enough space for kobject rodata.
```

**Environment (please complete the following information):**

 - OS: Linux
 - Toolchain: Zephyr SDK
 - Commit SHA: 6d87bd65aebf2db1b31bf524e158c49646dd05c5

**Additional context**

Previously built / ran fine in https://github.com/zephyrproject-rtos/zephyr/pull/81505

**Comment by tagunil** [comment]
OK, so that's a gperf issue.
kobject_prebuilt_hash.c: MAX_HASH_VALUE is 225, so the asso_values data type is unsigned char.
kobject_hash.c: MAX_HASH_VALUE is 258, so the asso_values data type is unsigned short.
