### ISSUE TITLE
Stray files in libapp.a

### ISSUE THREAD

**Issue by tejlmand** [zephyrproject-rtos/zephyr#8206]
I have noticed that stray files occurs in the libapp.a which are not coming from the sample applications.

Those files are:
atoi.c
strtol.c
strtoul.c
strncasecmp.c
strstr.c
string.c
prf.c
stdout_console.c
sprintf.c
fprintf.c

The files are present when the minimal C lib in zephyr is used.
The files are populated to libapp.a in the following CMakeLists.txt file:
lib/libc/minimal/CMakeLists.txt

I propose that those files are placed in their own minimal C library and then linked to the app instead.

**Comment by SebastianBoe** [comment]
I agree, I don't know why they were added to the 'app' library.

This is non-standard.
