### ISSUE TITLE
Always rebuilding even though there are no changes.

### ISSUE THREAD

**Issue by tejlmand** [zephyrproject-rtos/zephyr#8210]
Hi,

I have noticed that when running ninja, there is always something to rebuild / the project is out-of-date.
The reason for this is the generation of syscalls.json.

To me it seems that what is trying to be achived is to re-run parse_syscalls.py whenever a header file is added/removed/updated in ${PROJECT_SOURCE_DIR}/include 

Therefore the add_custom_command depends on the always_rebuild target.
My suggestion is to make parse_syscalls.py depend on the folder (works in Linux both whenever a file is modified/added/removed).
On windows each header must be monitored, as well as the folder.

This way, the always_rebuild can be removed.
Currently only parse_syscalls.py depends on always_rebuild, and the reason I suggest removing that target, is to not tempt others to use it, if they can find a way to avoid.
Keeping always_rebuild might make someone choose the easy path.

**Comment by SebastianBoe** [comment]
"To me it seems that what is trying to be achived is to re-run parse_syscalls.py whenever a header file is added/removed/updated in ${PROJECT_SOURCE_DIR}/include"

Correct. If we can achieve this without using always_rebuild then that would be great.

"Therefore the add_custom_command depends on the always_rebuild target.
My suggestion is to make parse_syscalls.py depend on the folder (works in Linux both whenever a file is modified/added/removed).
On windows each header must be monitored, as well as the folder."

This works for subfolders as well right?

**Comment by tejlmand** [comment]
Monitoring of a folder is only active for that folder (CMake basically just uses the information from the filesystem).
So in this case:
include/crypto/
if only monitoring include, changes inside crypto will not be detected.
So both include and include/crypto must be monitored (and on windows even the files inside)

**Comment by SebastianBoe** [comment]
Right. So we just glob everything in include/, folders and header files alike, and we should be good.

**Comment by tejlmand** [comment]
basically yes.
But we need to remember to be able to detect not only new files but also new sub-(sub)-foldes.
