### ISSUE TITLE
build_all: display: Fails on boards already declaring display support

### ISSUE THREAD

**Issue by erwango** [zephyrproject-rtos/zephyr#82116]
**Describe the bug**

#79545 extended `build_all/display` coverage to more boards, specially ones already declaring `display support`.
Test is now built on boards with existing display support using the overlay file provided for that test which enable more display support:
https://github.com/zephyrproject-rtos/zephyr/blob/5be4aed6209963cb26ee5c6171a595c2440f03fd/tests/drivers/build_all/display/app.overlay#L37-L45

It now happens that 2 different versions of displays are being compiled on one single board, as this is the case for `stm32f429i_disc1` which compiles with `"ilitek,ili9342c"` and `"ilitek,ili9341"` enabled, leading to a conflict in headers:

```
In file included from /local/home/zephyrproject/zephyr/drivers/display/display_ili9xxx.c:563:
/local/home/zephyrproject/zephyr/drivers/display/display_ili9342c.h:70:43: error: conflicting types for 'ili9xxx_regs_0'; have 'const struct ili9342c_regs'
   70 |         static const struct ili9342c_regs ili9xxx_regs_##n = {          \
      |                                           ^~~~~~~~~~~~~
[...]
In file included from /local/home/zephyrproject/zephyr/drivers/display/display_ili9xxx.c:558:
/local/home/zephyrproject/zephyr/drivers/display/display_ili9341.h:124:42: note: previous definition of 'ili9xxx_regs_0' with type 'const struct ili9341_regs'
  124 |         static const struct ili9341_regs ili9xxx_regs_##n = {                                      \
      |                                          ^~~~~~~~~~~~~
[...]
```

**To Reproduce**
1. west twister -p stm32f429i_disc1 -s tests/drivers/build_all/display/drivers.display.build.default
2. See error

**Expected behavior**

Test should compile.
I'm not sure the issue actually comes from the test definition. One can argue that one board should support using these two dfifferent versions of displays.

**Impact**

CI issue

**Environment (please complete the following information):**

 - Commit SHA or Version used: v4.0.0-978-g113875d53c7

**Comment by kartben** [comment]
assigning to the author of the PR mentioned in the initial description
