### ISSUE TITLE
west: add modules that are not git repositories to the project 

### ISSUE THREAD

**Issue by alexdr3437** [zephyrproject-rtos/zephyr#82159]
Hello,

I have not labeled this is an enhancement or feature request since I am not sure if there is a way to do this already, but I have not seen direct documentation related to this.

I have a project structured like so:

```
root
├── .git/
├── app1/
├── app2/
├── modules/lib/company_name/lib1/
└── manifest/
    └── west.yml
```

I then init the project from a github repo like so 

```
git clone <project url>
cd root
west init -l manifest
west update
```

Both `app1` and `app2` use the module `lib1`. This is all in one repository which seems to go against the manifest design philosophy where each entry is a git repo. 

I can add `list (APPEND ZEPHYR_EXTRA_MODULES ...)` in the CMakeLists.txt  of app1 and app2 and compile successfully, but this might get a bit cumbersome as the number of libraries and things like tests/examples grow. It would be nice if I could specify a "local" module in the manifest and have it behave like a normal entry.

I have tried adding this to `manifest/west.yml`
```
    - name: lib1
      path: modules/lib/company_name/lib1
      import: false
```

But this does not give the desired behaviour. It tries to initialize the module as a git repo and gives an error related to the revision when I compile app1 or app2. 

Is there a way to specify that this NOT a git repo, but still have it picked up as a zephyr module?

**Comment by nordicjm** [comment]
> Is there a way to specify that this NOT a git repo, but still have it picked up as a zephyr module?
> I can add list (APPEND ZEPHYR_EXTRA_MODULES ...) in the CMakeLists.txt of app1 and app2 and compile successfully, but this might get a bit cumbersome as the number of libraries and things like tests/examples grow. It would be nice if I could specify a "local" module in the manifest and have it behave like a normal entry.
That is how, west.yml entries are git repos
