### ISSUE TITLE
drivers: can: stm32_can: various issues

### ISSUE THREAD

**Issue by karstenkoenig** [zephyrproject-rtos/zephyr#8226]
a)
https://github.com/zephyrproject-rtos/zephyr/blob/2dd91eca0e25e35ab00567461ff4f3d773db24db/drivers/can/stm32_can.c#L74

This line assigns tx errors for mb1 to mb0

b)
https://github.com/zephyrproject-rtos/zephyr/blob/2dd91eca0e25e35ab00567461ff4f3d773db24db/drivers/can/stm32_can.c#L713
and
https://github.com/zephyrproject-rtos/zephyr/blob/2dd91eca0e25e35ab00567461ff4f3d773db24db/drivers/can/stm32_can.c#L725

are not thread safe, they also need to be protected by &data->set_filter_mutex, otherwise it might be interrupted with a stale mask that gets updated at a different bit position meanwhile

c)
https://github.com/zephyrproject-rtos/zephyr/blob/8b9042c4192e1625744eb3b7fe60bc82ac6f336d/drivers/can/stm32_can.c#L294
Any non zero return code is failure, I think if the _send function is called is called with K_NO_WAIT and the semaphore is taken already the sem_take() will return with -EBUSY

d)
https://github.com/zephyrproject-rtos/zephyr/blob/f58d9caba242e52a4e0150dd1be0c99e239a9d42/drivers/can/stm32_can.c#L342

This reset of the semaphore can happen after the tx interrupt, thus the following take will block even though the message was already transmitted

**Comment by karstenkoenig** [comment]
ping @alexanderwachter

**Comment by alexanderwachter** [comment]
Thanks @karstenkoenig.
Are you currently using this driver/API?
Does it satisfy your demands?
I think I need to extend the API a little bit, because at the moment it's impossible to get the state of the bus and recover from bus-off state.

**Comment by karstenkoenig** [comment]
@alexanderwachter 
I am actually working on an MCP2515 driver, because I like the NRF chips but they lack a CAN controller
https://github.com/karstenkoenig/zephyr/blob/wip_mcp2515/drivers/can/mcp2515.c

It is still rough around the edges and the branch has a lot of extra stuff thrown in to use it on my nucleo l4r5zi board. I just want to clean out a couple of more nooks and then open a pull request for discussion. 

Your code often serves as a reference so of course, so when trying to understand it I stumble over things like these minor bugs :-)

**Comment by karstenkoenig** [comment]
Sorry there is one more issue

d)
https://github.com/zephyrproject-rtos/zephyr/blob/f58d9caba242e52a4e0150dd1be0c99e239a9d42/drivers/can/stm32_can.c#L342

This reset of the semaphore can happen after the tx interrupt, thus the following take will block even though the message was already transmitted

**Comment by alexanderwachter** [comment]
Thx. Just updated the PR.

**Comment by nashif** [comment]
fixed in #8276
