### ISSUE TITLE
Nominate mrodgers_witekio as contributor

### ISSUE THREAD

**Issue by mrodgers-witekio** [zephyrproject-rtos/zephyr#82276]
# Nomination

## GitHub User

Provide the following information about the GitHub user:

1. Full Name: Matt Rodgers
1. GitHub username: mrodgers_witekio
1. Organization: Witekio

## Supporting Documents

https://github.com/zephyrproject-rtos/zephyr/pull/80395
https://github.com/zephyrproject-rtos/zephyr/pull/77982
https://github.com/zephyrproject-rtos/zephyr/pull/77125
https://github.com/zephyrproject-rtos/zephyr/pull/77003
https://github.com/zephyrproject-rtos/zephyr/pull/76850

[TSC Project Roles]: <https://docs.zephyrproject.org/latest/project/project_roles.html>
[GitHub Permission Level]: <https://docs.github.com/en/organizations/managing-access-to-your-organizations-repositories/repository-roles-for-an-organization>

**Comment by jukkar** [comment]
@mrodgers-witekio I think you need to send a PR that adds yourself to desired places in MAINTAINERS file

**Comment by mrodgers-witekio** [comment]
Based on this: https://docs.zephyrproject.org/latest/project/project_roles.html I think the MAINTAINERS file just needs to be changed for the collaborator or maintainer roles, rather than contributor.

**Comment by jukkar** [comment]
Indeed, my bad. I mis read it as collaborator, probably need to get new glasses 😄

**Comment by kartben** [comment]
> Indeed, my bad. I mis read it as collaborator, probably need to get new glasses 😄 

Or simply a sign that you'd apparently happily welcome a new collaborator :) hint hint @mrodgers-witekio

**Comment by nashif** [comment]
Thank you for your contribution to the Zephyr project. 

An invite was sent to you to join the project. You can find the invite here: https://github.com/zephyrproject-rtos/zephyr/invitations.

Note that further access and permissoins to the project will be provided following the project [guidelines](https://docs.zephyrproject.org/latest/project/project_roles.html#tsc-project-roles).
