### ISSUE TITLE
Missing board image for Waveshare esp32s3_touch_lcd_1_28 board

### ISSUE THREAD

**Issue by rlneumiller** [zephyrproject-rtos/zephyr#82358]
**Describe the bug**
Waveshare esp32s3_touch_lcd_1_28 board is missing board img

**To Reproduce**
The documentation [page](https://docs.zephyrproject.org/latest/boards/waveshare/esp32s3_touch_lcd_1_28/doc/index.html) for the Waveshare esp32s3_touch_lcd_1.28 board lacks an image of the board itself. 

**Expected behavior**
The documentation page should display a clear image of the Waveshare esp32s3_touch_lcd_1.28 board. 

**Impact**
The documentation appears incomplete and less user-friendly.

**Comment by henrikbrixandersen** [comment]
Please submit a PR adding an image.
