### ISSUE TITLE
zms does not initiate correctly for esp32

### ISSUE THREAD

**Issue by vietlb2017** [zephyrproject-rtos/zephyr#82378]
**Describe the bug**
I tried to bring up zms for my new project on esp32-devkitc-wroom. When I run the sample implementation for zms, it consistently errors at the first iteration

> [00:00:00.150,000] <inf> fs_zms: 1085 sector: 0, ate_wra: 0
> [00:00:00.150,000] <inf> fs_zms: 1089 sector: 0, isClosed: 1
> [00:00:00.150,000] <inf> fs_zms: 1098 this line will be run if isClose == 1
> [00:00:00.155,000] <inf> fs_zms: 11 ate_wra: 0, data_wra: 0
> [00:00:00.155,000] <inf> fs_zms: 1 ate_wra: 1, data_wra: 1
> [00:00:00.155,000] <inf> fs_zms: 2 ate_wra: 1, data_wra: 1
> [00:00:00.155,000] <inf> fs_zms: 1335 sector: 0, ate_wra: 1
> [00:00:00.155,000] <inf> fs_zms: 3 Sectors of 4096 bytes
> [00:00:00.155,000] <inf> fs_zms: alloc wra: 1, 7b0
> [00:00:00.155,000] <inf> fs_zms: data wra: 1, c
> ITERATION: 0
> ID: 1, IP Address: 172.16.254.1
> Adding IP_ADDRESS 172.16.254.1 at id 1
> Id: beefdead, Key: de ad be ef de ad be ef
> Adding key/value at id beefdead 
> Id: 2, loop_cnt: 2
> Error: Something went wrong at iteration 0 rc=4

Tried to debug it for a bit, this is my finding:
- this happen only if the esp32 storage partition is not empty:
   ~~- if I do west flash --erase, the process hangs~~
   - then I do west flash, the process proceeds to continue with aforementioned error
- in the scenario where the process does not hang, zms checked and found empty_ate as well as closed_ate of the first sector. The crc_check returns 0 verifies that these are valid (not sure why both of them are valid).

P/s: after further testing, I found that west flash --erase does not make the process hang.

All the config is ran as default, except from the log buffer size - it was set to 10240 to collect more logs. I will have more boards shipped tomorrow (a Rpi Pico and a RTL8720DN), will check if the behavior consistent.
**To Reproduce**

1. cd ./samples/subsys/fs/zms
2. west build --pristine -b esp32_devkitc_wroom
3. west flash --erase
4. Check the output of COM port (it hangs in my case)
5. west flash
6. Check the output of COM port (it should stop after first iteration due to incorrect information)
**Expected behavior**

**Impact**

Showstopper: the zms component seems to have some incompatibility with a popular embedded module.
**Logs and console output**

Modified of zms.c for more logs together with expectedLog and errorLog attached.
[bug_zms.zip](https://github.com/user-attachments/files/17968924/bug_zms.zip)
**Environment (please complete the following information):**

 - OS: wsl 2 on windows
 - Toolchain: west
 - Commit SHA or Version used: 2f583a8369e

**Additional context**

**Comment by rghaddab** [comment]
@vietlb2017 the ZMS sample has not been tested on all boards and may need to be adapted to some boards.
As I can see, the flash is not empty when the sample started, that's why it failed.
Maybe as a fix we should clear the flash using zms_clear before starting to run the sample

**Comment by sylvioalves** [comment]
in addition to add `zms_clear`, you can try erasing the ESP32 flash memory by `west flash --erase` command.

**Comment by rghaddab** [comment]
@vietlb2017 I just verified that clearing a non mounted storage won't work.
clearing the flash should be kept at the end of the sample app or when an error occured (I will add this).
If you flash using --erase option, you should normally have an empty flash and you will see it through zms logs :
```
   [00:00:00.000,000] <inf> fs_zms: 3 Sectors of 4096 bytes
   [00:00:00.000,000] <inf> fs_zms: alloc wra: 0, fc0
   [00:00:00.000,000] <inf> fs_zms: data wra: 0, 0
```
alloc wra : 0 => this means that it starts at sector 0 and 0xfc0 is the first ATE location
data wra: 0, 0 => this means that it starts at sector 0 and the address 0x0

If you see other values at the begining of the sample app, that means that your flash memory is not empty and something else is not working

**Comment by vietlb2017** [comment]
> @vietlb2017 I just verified that clearing a non mounted storage won't work. clearing the flash should be kept at the end of the sample app or when an error occured (I will add this). If you flash using --erase option, you should normally have an empty flash and you will see it through zms logs :
> 
> ```
>    [00:00:00.000,000] <inf> fs_zms: 3 Sectors of 4096 bytes
>    [00:00:00.000,000] <inf> fs_zms: alloc wra: 0, fc0
>    [00:00:00.000,000] <inf> fs_zms: data wra: 0, 0
> ```
> 
> alloc wra : 0 => this means that it starts at sector 0 and 0xfc0 is the first ATE location data wra: 0, 0 => this means that it starts at sector 0 and the address 0x0
> 
> If you see other values at the begining of the sample app, that means that your flash memory is not empty and something else is not working

Yeah, I figured the same. Dont know why it is consistently stuck at this.  The sample doesnt work for any of my 2 esp32 boards. Could it be that after west flash --erase, the board is reset without being monitored, and then when I do west espressif monitor, some thing was left over from the previous boot-up?

**Comment by rghaddab** [comment]
@vietlb2017 can you try to compile the sample using -- -DCONFIG_HEAP_MEM_POOL_SIZE=256 ?

**Comment by vietlb2017** [comment]
> -- -DCONFIG_HEAP_MEM_POOL_SIZE=256

`CMake Warning at /root/zephyrproject/zephyr/kernel/CMakeLists.txt:171 (message):


          CONFIG_HEAP_MEM_POOL_SIZE is less than requested minimum:
            256 < 4096
          Setting the system heap size to 4096`

It's too smalll, the default value is enforced.

**Comment by sylvioalves** [comment]
@vietlb2017 Did you get it working?

**Comment by rghaddab** [comment]
@vietlb2017 can you dump the full log after boot ?

**Comment by vietlb2017** [comment]
> @vietlb2017 can you dump the full log after boot ?

I'm not sure how to dump the full log, since I'm quite new to Zephyr. Though, I have added my own log in zms.c, and packed it together with the output in the .zip file. You can find it in my initial post (bug_zms.zip).



> @vietlb2017 Did you get it working?

Not yet. I suppose I can provide more logs and tests if needed. Now I'm moving on to other parts of my project.

**Comment by sylvioalves** [comment]
If possible, provide some minimal code as well.

**Comment by vietlb2017** [comment]
> If possible, provide some minimal code as well.

modified_zms.txt is where I'd added info log. To open the log files, please use Notepad++ or vim, there seems to be error detecting encoding on some other document editors.
[errorLog.txt](https://github.com/user-attachments/files/17995773/errorLog.txt)
[expectedLog.txt](https://github.com/user-attachments/files/17995774/expectedLog.txt)
[modified_zms.txt](https://github.com/user-attachments/files/17995781/modified_zms.txt)

**Comment by rghaddab** [comment]
> I'm not sure how to dump the full log, since I'm quite new to Zephyr. Though, I have added my own log in zms.c, and packed it together with the output in the .zip file. You can find it in my initial post (bug_zms.zip).
> 
> >

I understood that your initial log was run without --erase when flashing.
When looking at your logs some data exists already in the flash.
The sample code supposes that the flash is erased. In your case this is a NOR Spi flash which should be initialized to all 0xffff values

**Comment by vietlb2017** [comment]
> > I'm not sure how to dump the full log, since I'm quite new to Zephyr. Though, I have added my own log in zms.c, and packed it together with the output in the .zip file. You can find it in my initial post (bug_zms.zip).
> > >
> 
> I understood that your initial log was run without --erase when flashing. When looking at your logs some data exists already in the flash. The sample code supposes that the flash is erased. In your case this is a NOR Spi flash which should be initialized to all 0xffff values

Unfortunately, that's not the case, even with "--erase", same error showed up.
Steps I've done:
- west flash --erase
- west espressif monitor

Log:
[errorLog2.txt](https://github.com/user-attachments/files/17996566/errorLog2.txt)

**Comment by vietlb2017** [comment]
> > > I'm not sure how to dump the full log, since I'm quite new to Zephyr. Though, I have added my own log in zms.c, and packed it together with the output in the .zip file. You can find it in my initial post (bug_zms.zip).
> > > >
> > 
> > 
> > I understood that your initial log was run without --erase when flashing. When looking at your logs some data exists already in the flash. The sample code supposes that the flash is erased. In your case this is a NOR Spi flash which should be initialized to all 0xffff values
> 
> Unfortunately, that's not the case, even with "--erase", same error showed up. Steps I've done:
> 
>     * west flash --erase
> 
>     * west espressif monitor
> 
> 
> Log: [errorLog2.txt](https://github.com/user-attachments/files/17996566/errorLog2.txt)

I managed to get the sample code to work, though the process is painful:
- esptool.py --port /dev/ttyUSB0 --baud 921600 erase_flash
- esptool.py --port /dev/ttyUSB0 --baud 921600 **_--after no_reset_** write_flash --verify 0x1000 /root/zephyrproject/zephyr/samples/subsys/fs/zms/build/zephyr/zephyr.bin
- west espressif monitor
I put "--after no_reset" into the command just to make sure nothing goes wrong in the first bootup (apparently using west flash --erase --no-reset doesnt work, that's why I have to facilitated esptool.py). This time, after the third command (west espressif monitor) I was very patient to wait. After ~45 secs, the process returns successful. Remember when I said that I observed the process hangs? Turns out it's just slow; and when I interrupt it prematurely, it returns error in the next run. 
Removing all the added log in zms.c doesn't seem to solve this slow-ness; it took roughly 35 secs to complete. Not sure whether or not because all the printf or smt. Maybe I'll check that later.

Overall, the sample runs, the zms seems to work. Though I'm a bit concerned about its performance.

Thank you for the support 👍 . Zephyr community rocks 🪨 

P/s: it would be appreciated if someone can point out how to make "west flash --no-reset" work.

**Comment by rghaddab** [comment]
> Overall, the sample runs, the zms seems to work. Though I'm a bit concerned about its performance.

The sample actually looks like a stress test more than a simple sample code.
It tries all the combinations of read/write/delete to make sure that everything works
It is performing 1500 entry writes + filling all the memory + deleting all of them (these are also writes) and also calculating the remaining free space which is a very time consuming operation.
