### ISSUE TITLE
File system (littlefs & FAT) examples

### ISSUE THREAD

**Issue by koffes** [zephyrproject-rtos/zephyr#8242]
As far as I can see, there are no examples for FAT or littlefs file system setup in Zephyr.
It would be great to have an example which:
- Creates a file system in flash
- Creates a folder structure
- Navigates in the folder structure
- Writes to and reads back files

I created a PR for this some time ago: #4751, but this became outdated and did lack some functionality. Hence, I tried to update it to Zephyr 1.11.xx, but with no code or doc to follow this proved challenging.
This issue relates to https://github.com/zephyrproject-rtos/zephyr/issues/1845

**Comment by carlescufi** [comment]
@nvlsianpu is this still applicable or should we close it?

**Comment by nvlsianpu** [comment]
I see `samples/subsys/fs/littlefs/` samle which shows LittleFS usage via VFS.
also `samples/subsys/fs/fat_fs` shows FAT usage via VFS on target witch SD.

@koffes I feel that examples I mentioned above are enough. Can we close this issue?
