### ISSUE TITLE
doc: Documentation issue in 'develop/getting_started/index'

### ISSUE THREAD

**Issue by zhangyouq** [zephyrproject-rtos/zephyr#82467]
**Describe the bug**

<< Please describe the issue here >>
<< You may also want to update the automatically generated issue title above. >>

**Environment**

* Page: `develop/getting_started/index`
* Version: main
* SHA-1: 2f583a8369ef5b67c4438c40d17721d31db952a0

**Comment by kartben** [comment]
please re-open with actual details about the issue you're trying to report :)
