### ISSUE TITLE
Input 'wifi connect' using Wi-Fi shell, shows redundant log of 'Subcommands:'

### ISSUE THREAD

**Issue by MaochenWang1** [zephyrproject-rtos/zephyr#82633]
**Describe the bug**
Using rd_rw612_bga board (or any board supports Wi-Fi), Input 'wifi connect' using Wi-Fi shell, shows large redundant log of 'Subcommands:'.
This issue is not seen in v3.7.

**To Reproduce**
Input 'wifi connect' in console.

**Expected behavior**
Expected only shows 'wifi connect' related parameters prompt.
But actually will show all the redundant wifi cmd help log.

**Impact**
Difficult for user to use shell.

**Logs and console output**
```
uart:~$ wifi connect
connect: wrong parameter count
connect - Connect to a Wi-Fi AP
          <-s --ssid "<SSID>">: SSID.
          [-c --channel]: Channel that needs to be scanned for connection. 0:any
          channel.
          [-b, --band] 0: any band (2:2.4GHz, 5:5GHz, 6:6GHz]
          [-p, --psk]: Passphrase (valid only for secure SSIDs)
          [-k, --key-mgmt]: Key Management type (valid only for secure SSIDs)
          0:None, 1:WPA2-PSK, 2:WPA2-PSK-256, 3:SAE-HNP, 4:SAE-H2E, 5:SAE-AUTO,
          6:WAPI,7:EAP-TLS, 8:WEP, 9: WPA-PSK, 10: WPA-Auto-Personal, 11: DPP
          12: EAP-PEAP-MSCHAPv2, 13: EAP-PEAP-GTC, 14: EAP-TTLS-MSCHAPv2,
          15: EAP-PEAP-TLS, 16:EAP_TLS_SHA256
          17: FT_PSK, 18: FT_SAE, 19: FT_EAP, 20: FT_EAP_SHA384
          21: WPA-Auto-Personal-H2E, 22: WPA-Auto-Personal-AUTO
          [-w, --ieee-80211w]: MFP (optional: needs security type to be
          specified)
          : 0:Disable, 1:Optional, 2:Required.
          [-m, --bssid]: MAC address of the AP (BSSID).
          [-t, --timeout]: Timeout for the connection attempt (in seconds).
          [-a, --anon-id]: Anonymous identity for enterprise mode.
          [-K, --key1-pwd for eap phase1 or --key2-pwd for eap phase2]:
          Private key passwd for enterprise mode. Default no password for
          private key.
          [-S, --suiteb-type]: 1:suiteb, 2:suiteb-192. Default 0: not suiteb
          mode.
          [-T, --TLS-cipher]: 0:TLS-NONE, 1:TLS-ECC-P384, 2:TLS-RSA-3K.
          [-V, --eap-version]: 0 or 1. Default 1: eap version 1.
          [-I, --eap-id1]: Client Identity. Default no eap identity.
          [-P, --eap-pwd1]: Client Password.
          Default no password for eap user.
          [-R, --ieee-80211r]: Use IEEE80211R fast BSS transition connect.[-d,
          --domain-match]: Server domain name constraint.
          [-h, --help]: Print out the help for the connect command.

Subcommands:
  11k                   : Configure 11k or get 11k status.
                          [enable/disable]

  11k_neighbor_request  : Send Neighbor Report Request frame.
                          [ssid <ssid>]

  11v_btm_query         : <query_reason: The reason code for a BSS transition
                          management query>.

  ap                    : Access Point mode commands.
  channel               : wifi channel setting
                          This command is used to set the channel when
                          monitor or TX-Injection mode is enabled
                          Currently 20 MHz is only supported and no BW parameter
                          is provided
                          [-i, --if-index <idx>] : Interface index
                          [-c, --channel <chan>] : Set a specific channel number
                          to the lower layer
                          [-g, --get] : Get current set channel number from the
                          lower layer
                          [-h, --help] : Help
                          Usage: Get operation example for interface index 1
                          wifi channel -g -i1
                          Set operation example for interface index 1 (setting
                          channel 5)
                          wifi -i1 -c5.

  connect               : Connect to a Wi-Fi AP
                          <-s --ssid "<SSID>">: SSID.
                          [-c --channel]: Channel that needs to be scanned for
                          connection. 0:any channel.
                          [-b, --band] 0: any band (2:2.4GHz, 5:5GHz, 6:6GHz]
                          [-p, --psk]: Passphrase (valid only for secure SSIDs)
                          [-k, --key-mgmt]: Key Management type (valid only for
                          secure SSIDs)
                          0:None, 1:WPA2-PSK, 2:WPA2-PSK-256, 3:SAE-HNP,
                          4:SAE-H2E, 5:SAE-AUTO, 6:WAPI,7:EAP-TLS, 8:WEP, 9:
                          WPA-PSK, 10: WPA-Auto-Personal, 11: DPP
                          12: EAP-PEAP-MSCHAPv2, 13: EAP-PEAP-GTC, 14:
                          EAP-TTLS-MSCHAPv2,
                          15: EAP-PEAP-TLS, 16:EAP_TLS_SHA256
                          17: FT_PSK, 18: FT_SAE, 19: FT_EAP, 20: FT_EAP_SHA384
                          21: WPA-Auto-Personal-H2E, 22: WPA-Auto-Personal-AUTO
                          [-w, --ieee-80211w]: MFP (optional: needs security
                          type to be specified)
                          : 0:Disable, 1:Optional, 2:Required.
                          [-m, --bssid]: MAC address of the AP (BSSID).
                          [-t, --timeout]: Timeout for the connection attempt
                          (in seconds).
                          [-a, --anon-id]: Anonymous identity for enterprise
                          mode.
                          [-K, --key1-pwd for eap phase1 or --key2-pwd for eap
                          phase2]:
                          Private key passwd for enterprise mode. Default no
                          password for private key.
                          [-S, --suiteb-type]: 1:suiteb, 2:suiteb-192. Default
                          0: not suiteb mode.
                          [-T, --TLS-cipher]: 0:TLS-NONE, 1:TLS-ECC-P384,
                          2:TLS-RSA-3K.
                          [-V, --eap-version]: 0 or 1. Default 1: eap version 1.
                          [-I, --eap-id1]: Client Identity. Default no eap
                          identity.
                          [-P, --eap-pwd1]: Client Password.
                          Default no password for eap user.
                          [-R, --ieee-80211r]: Use IEEE80211R fast BSS
                          transition connect.[-d, --domain-match]: Server domain
                          name constraint.
                          [-h, --help]: Print out the help for the connect
                          command.

  disconnect            : Disconnect from the Wi-Fi AP.

  dpp                   : DPP actions.
  mode                  : mode operational setting
                          This command may be used to set the Wi-Fi device into
                          a specific mode of operation
                          [-i, --if-index <idx>] : Interface index
                          [-s, --sta] : Station mode
                          [-m, --monitor] : Monitor mode
                          [-a, --ap] : AP mode
                          [-k, --softap] : Softap mode
                          [-h, --help] : Help
                          [-g, --get] : Get current mode for a specific
                          interface index
                          Usage: Get operation example for interface index 1
                          wifi mode -g -i1
                          Set operation example for interface index 1 - set
                          station+promiscuous
                          wifi mode -i1 -sp.

  packet_filter         : mode filter setting
                          This command is used to set packet filter setting when
                          monitor, TX-Injection and promiscuous mode is enabled
                          The different packet filter modes are control,
                          management, data and enable all filters
                          [-i, --if-index <idx>] : Interface index
                          [-a, --all] : Enable all packet filter modes
                          [-m, --mgmt] : Enable management packets to allowed up
                          the stack
                          [-c, --ctrl] : Enable control packets to be allowed up
                          the stack
                          [-d, --data] : Enable Data packets to be allowed up
                          the stack
                          [-g, --get] : Get current filter settings for a
                          specific interface index
                          [-b, --capture-len <len>] : Capture length buffer size
                          for each packet to be captured
                          [-h, --help] : Help
                          Usage: Get operation example for interface index 1
                          wifi packet_filter -g -i1
                          Set operation example for interface index 1 - set
                          data+management frame filter
                          wifi packet_filter -i1 -md.

  pmksa_flush           : Flush PMKSA cache entries.

  ps                    : Configure or display Wi-Fi power save state.
                          [on/off]

  ps_exit_strategy      : <tim> : Set PS exit strategy to Every TIM
                          <custom> : Set PS exit strategy to Custom
  ps_listen_interval    : <val> - Listen interval in the range of <0-65535>.

  ps_mode               : <mode: legacy/WMM>.

  ps_timeout            : <val> - PS inactivity timer(in ms).

  ps_wakeup_mode        : <wakeup_mode: DTIM/Listen Interval>.

  reg_domain            : Set or Get Wi-Fi regulatory domain
                          [ISO/IEC 3166-1 alpha2]: Regulatory domain
                          [-f]: Force to use this regulatory hint over any other
                          regulatory hints
                          Note: This may cause regulatory compliance issues, use
                          it at your own risk.

  rts_threshold         : <rts_threshold: rts threshold/off>.

  scan                  : Scan for Wi-Fi APs
                          [-t, --type <active/passive>] : Preferred mode of
                          scan. The actual mode of scan can depend on factors
                          such as the Wi-Fi chip implementation, regulatory
                          domain restrictions. Default type is active
                          [-b, --bands <Comma separated list of band values
                          (2/5/6)>] : Bands to be scanned where 2: 2.4 GHz, 5: 5
                          GHz, 6: 6 GHz
                          [-a, --dwell_time_active <val_in_ms>] : Active scan
                          dwell time (in ms) on a channel. Range 5 ms to 1000 ms
                          [-p, --dwell_time_passive <val_in_ms>] : Passive scan
                          dwell time (in ms) on a channel. Range 10 ms to 1000
                          ms
                          [-s, --ssid] : SSID to scan for. Can be provided
                          multiple times
                          [-m, --max_bss <val>] : Maximum BSSes to scan for.
                          Range 1 - 65535
                          [-c, --chans <Comma separated list of channel ranges>]
                          : Channels to be scanned. The channels must be
                          specified in the form
                          band1:chan1,chan2_band2:chan3,..etc. band1, band2 must
                          be valid band values and chan1, chan2, chan3 must be
                          specified as a list of comma separated values where
                          each value is either a single channel or a channel
                          range specified as chan_start-chan_end. Each band
                          channel set has to be separated by a _. For example, a
                          valid channel specification can be 2:1,6_5:36 or
                          2:1,6-11,14_5:36,163-177,52. Care should be taken to
                          ensure that configured channels don't exceed
                          CONFIG_WIFI_MGMT_SCAN_CHAN_MAX_MANUAL
                          [-h, --help] : Print out the help for the scan
                          command.

  statistics            : Wi-Fi interface statistics.
                          [reset] : Reset Wi-Fi interface statistics
                          [help] :  Print out the help for the statistics
                          command.
  status                : Status of the Wi-Fi interface.

  twt                   : Manage TWT flows.
  version               : Print Wi-Fi Driver and Firmware versions

  wps_pbc               : Start a WPS PBC connection.

  wps_pin               : Set and get WPS pin.
                          [pin] Only applicable for set.
```

**Additional context**
This issue is introduced by https://github.com/zephyrproject-rtos/zephyr/commit/32aa1d634ed9992505ea551b567cdb2e65d418b9.

**Comment by MaochenWang1** [comment]
`uart:~$ wifi connect
connect: wrong parameter count
connect - Connect to a Wi-Fi AP
          <-s --ssid "<SSID>">: SSID.
          [-c --channel]: Channel that needs to be scanned for connection. 0:any
          channel.
          [-b, --band] 0: any band (2:2.4GHz, 5:5GHz, 6:6GHz]
          [-p, --psk]: Passphrase (valid only for secure SSIDs)
          [-k, --key-mgmt]: Key Management type (valid only for secure SSIDs)
          0:None, 1:WPA2-PSK, 2:WPA2-PSK-256, 3:SAE-HNP, 4:SAE-H2E, 5:SAE-AUTO,
          6:WAPI,7:EAP-TLS, 8:WEP, 9: WPA-PSK, 10: WPA-Auto-Personal, 11: DPP
          12: EAP-PEAP-MSCHAPv2, 13: EAP-PEAP-GTC, 14: EAP-TTLS-MSCHAPv2,
          15: EAP-PEAP-TLS, 16:EAP_TLS_SHA256
          17: FT_PSK, 18: FT_SAE, 19: FT_EAP, 20: FT_EAP_SHA384
          21: WPA-Auto-Personal-H2E, 22: WPA-Auto-Personal-AUTO
          [-w, --ieee-80211w]: MFP (optional: needs security type to be
          specified)
          : 0:Disable, 1:Optional, 2:Required.
          [-m, --bssid]: MAC address of the AP (BSSID).
          [-t, --timeout]: Timeout for the connection attempt (in seconds).
          [-a, --anon-id]: Anonymous identity for enterprise mode.
          [-K, --key1-pwd for eap phase1 or --key2-pwd for eap phase2]:
          Private key passwd for enterprise mode. Default no password for
          private key.
          [-S, --suiteb-type]: 1:suiteb, 2:suiteb-192. Default 0: not suiteb
          mode.
          [-T, --TLS-cipher]: 0:TLS-NONE, 1:TLS-ECC-P384, 2:TLS-RSA-3K.
          [-V, --eap-version]: 0 or 1. Default 1: eap version 1.
          [-I, --eap-id1]: Client Identity. Default no eap identity.
          [-P, --eap-pwd1]: Client Password.
          Default no password for eap user.
          [-R, --ieee-80211r]: Use IEEE80211R fast BSS transition connect.[-d,
          --domain-match]: Server domain name constraint.
          [-h, --help]: Print out the help for the connect command.

Subcommands:
  11k                   : Configure 11k or get 11k status.
                          [enable/disable]

  11k_neighbor_request  : Send Neighbor Report Request frame.
                          [ssid <ssid>]

  11v_btm_query         : <query_reason: The reason code for a BSS transition
                          management query>.

  ap                    : Access Point mode commands.
  channel               : wifi channel setting
                          This command is used to set the channel when
                          monitor or TX-Injection mode is enabled
                          Currently 20 MHz is only supported and no BW parameter
                          is provided
                          [-i, --if-index <idx>] : Interface index
                          [-c, --channel <chan>] : Set a specific channel number
                          to the lower layer
                          [-g, --get] : Get current set channel number from the
                          lower layer
                          [-h, --help] : Help
                          Usage: Get operation example for interface index 1
                          wifi channel -g -i1
                          Set operation example for interface index 1 (setting
                          channel 5)
                          wifi -i1 -c5.

  connect               : Connect to a Wi-Fi AP
                          <-s --ssid "<SSID>">: SSID.
                          [-c --channel]: Channel that needs to be scanned for
                          connection. 0:any channel.
                          [-b, --band] 0: any band (2:2.4GHz, 5:5GHz, 6:6GHz]
                          [-p, --psk]: Passphrase (valid only for secure SSIDs)
                          [-k, --key-mgmt]: Key Management type (valid only for
                          secure SSIDs)
                          0:None, 1:WPA2-PSK, 2:WPA2-PSK-256, 3:SAE-HNP,
                          4:SAE-H2E, 5:SAE-AUTO, 6:WAPI,7:EAP-TLS, 8:WEP, 9:
                          WPA-PSK, 10: WPA-Auto-Personal, 11: DPP
                          12: EAP-PEAP-MSCHAPv2, 13: EAP-PEAP-GTC, 14:
                          EAP-TTLS-MSCHAPv2,
                          15: EAP-PEAP-TLS, 16:EAP_TLS_SHA256
                          17: FT_PSK, 18: FT_SAE, 19: FT_EAP, 20: FT_EAP_SHA384
                          21: WPA-Auto-Personal-H2E, 22: WPA-Auto-Personal-AUTO
                          [-w, --ieee-80211w]: MFP (optional: needs security
                          type to be specified)
                          : 0:Disable, 1:Optional, 2:Required.
                          [-m, --bssid]: MAC address of the AP (BSSID).
                          [-t, --timeout]: Timeout for the connection attempt
                          (in seconds).
                          [-a, --anon-id]: Anonymous identity for enterprise
                          mode.
                          [-K, --key1-pwd for eap phase1 or --key2-pwd for eap
                          phase2]:
                          Private key passwd for enterprise mode. Default no
                          password for private key.
                          [-S, --suiteb-type]: 1:suiteb, 2:suiteb-192. Default
                          0: not suiteb mode.
                          [-T, --TLS-cipher]: 0:TLS-NONE, 1:TLS-ECC-P384,
                          2:TLS-RSA-3K.
                          [-V, --eap-version]: 0 or 1. Default 1: eap version 1.
                          [-I, --eap-id1]: Client Identity. Default no eap
                          identity.
                          [-P, --eap-pwd1]: Client Password.
                          Default no password for eap user.
                          [-R, --ieee-80211r]: Use IEEE80211R fast BSS
                          transition connect.[-d, --domain-match]: Server domain
                          name constraint.
                          [-h, --help]: Print out the help for the connect
                          command.

  disconnect            : Disconnect from the Wi-Fi AP.

  dpp                   : DPP actions.
  mode                  : mode operational setting
                          This command may be used to set the Wi-Fi device into
                          a specific mode of operation
                          [-i, --if-index <idx>] : Interface index
                          [-s, --sta] : Station mode
                          [-m, --monitor] : Monitor mode
                          [-a, --ap] : AP mode
                          [-k, --softap] : Softap mode
                          [-h, --help] : Help
                          [-g, --get] : Get current mode for a specific
                          interface index
                          Usage: Get operation example for interface index 1
                          wifi mode -g -i1
                          Set operation example for interface index 1 - set
                          station+promiscuous
                          wifi mode -i1 -sp.

  packet_filter         : mode filter setting
                          This command is used to set packet filter setting when
                          monitor, TX-Injection and promiscuous mode is enabled
                          The different packet filter modes are control,
                          management, data and enable all filters
                          [-i, --if-index <idx>] : Interface index
                          [-a, --all] : Enable all packet filter modes
                          [-m, --mgmt] : Enable management packets to allowed up
                          the stack
                          [-c, --ctrl] : Enable control packets to be allowed up
                          the stack
                          [-d, --data] : Enable Data packets to be allowed up
                          the stack
                          [-g, --get] : Get current filter settings for a
                          specific interface index
                          [-b, --capture-len <len>] : Capture length buffer size
                          for each packet to be captured
                          [-h, --help] : Help
                          Usage: Get operation example for interface index 1
                          wifi packet_filter -g -i1
                          Set operation example for interface index 1 - set
                          data+management frame filter
                          wifi packet_filter -i1 -md.

  pmksa_flush           : Flush PMKSA cache entries.

  ps                    : Configure or display Wi-Fi power save state.
                          [on/off]

  ps_exit_strategy      : <tim> : Set PS exit strategy to Every TIM
                          <custom> : Set PS exit strategy to Custom
  ps_listen_interval    : <val> - Listen interval in the range of <0-65535>.

  ps_mode               : <mode: legacy/WMM>.

  ps_timeout            : <val> - PS inactivity timer(in ms).

  ps_wakeup_mode        : <wakeup_mode: DTIM/Listen Interval>.

  reg_domain            : Set or Get Wi-Fi regulatory domain
                          [ISO/IEC 3166-1 alpha2]: Regulatory domain
                          [-f]: Force to use this regulatory hint over any other
                          regulatory hints
                          Note: This may cause regulatory compliance issues, use
                          it at your own risk.

  rts_threshold         : <rts_threshold: rts threshold/off>.

  scan                  : Scan for Wi-Fi APs
                          [-t, --type <active/passive>] : Preferred mode of
                          scan. The actual mode of scan can depend on factors
                          such as the Wi-Fi chip implementation, regulatory
                          domain restrictions. Default type is active
                          [-b, --bands <Comma separated list of band values
                          (2/5/6)>] : Bands to be scanned where 2: 2.4 GHz, 5: 5
                          GHz, 6: 6 GHz
                          [-a, --dwell_time_active <val_in_ms>] : Active scan
                          dwell time (in ms) on a channel. Range 5 ms to 1000 ms
                          [-p, --dwell_time_passive <val_in_ms>] : Passive scan
                          dwell time (in ms) on a channel. Range 10 ms to 1000
                          ms
                          [-s, --ssid] : SSID to scan for. Can be provided
                          multiple times
                          [-m, --max_bss <val>] : Maximum BSSes to scan for.
                          Range 1 - 65535
                          [-c, --chans <Comma separated list of channel ranges>]
                          : Channels to be scanned. The channels must be
                          specified in the form
                          band1:chan1,chan2_band2:chan3,..etc. band1, band2 must
                          be valid band values and chan1, chan2, chan3 must be
                          specified as a list of comma separated values where
                          each value is either a single channel or a channel
                          range specified as chan_start-chan_end. Each band
                          channel set has to be separated by a _. For example, a
                          valid channel specification can be 2:1,6_5:36 or
                          2:1,6-11,14_5:36,163-177,52. Care should be taken to
                          ensure that configured channels don't exceed
                          CONFIG_WIFI_MGMT_SCAN_CHAN_MAX_MANUAL
                          [-h, --help] : Print out the help for the scan
                          command.

  statistics            : Wi-Fi interface statistics.
                          [reset] : Reset Wi-Fi interface statistics
                          [help] :  Print out the help for the statistics
                          command.
  status                : Status of the Wi-Fi interface.

  twt                   : Manage TWT flows.
  version               : Print Wi-Fi Driver and Firmware versions

  wps_pbc               : Start a WPS PBC connection.

  wps_pin               : Set and get WPS pin.
                          [pin] Only applicable for set.
`

**Comment by MaochenWang1** [comment]
Hi @jukkar 
Is there any reason why need to change the wifi shell cmd in https://github.com/zephyrproject-rtos/zephyr/commit/32aa1d634ed9992505ea551b567cdb2e65d418b9?
This issue that I report, is expected by your change or not?

**Comment by jukkar** [comment]
The reason for that change was to allow wifi credentials shell commands to be found under wifi shell.
https://github.com/zephyrproject-rtos/zephyr/blob/main/subsys/net/lib/wifi_credentials/wifi_credentials_shell.c

**Comment by jukkar** [comment]
The issue seems to be related to shell, it prints all the commands if there is an error when giving the command.
Not sure if there is a way around this.

**Comment by jukkar** [comment]
I will investigate this more, there is something wrong with the wifi shell. For example it does not print help for each command properly, like what net-shell is doing.
