### ISSUE TITLE
Tracing macros cause memory leaks/duplicate function calls.

### ISSUE THREAD

**Issue by anthony289478** [zephyrproject-rtos/zephyr#82634]
**Describe the bug**
When tracing is enabled zephyr tracing macros cause extra function calls to be executed if used as macro arguments.

Previously net_buf_put() was a function but was replaced by a macro k_fifo_put which causes the preprocessor to repeat function arguments as multiple calls.
Discovered on [nrf devzone](https://devzone.nordicsemi.com/f/nordic-q-a/116975/systemview-broken-on-sdk-2-8-0-kernel-3-7-99)

Example of the problem in disassembly:
![image](https://github.com/user-attachments/assets/13a571e3-ff0e-41b9-8c66-7df481128db8)

Example of solution using a temporary variable:
![image](https://github.com/user-attachments/assets/7319574d-402d-4cd8-8536-b6468ff72188)

Multiple other usages of inline functions to tracing macros were also discovered, also noted in the devzone post.

**To Reproduce**
1. Build an example such as peripheral_bms with tracing enabled and a backed that is not CONFIG_TRACING_NONE
2. view disassembly at [hci_core.c#L396](https://github.com/nrfconnect/sdk-zephyr/blob/main/subsys/bluetooth/host/hci_core.c#L396)
```
west build -b nrf5340dk/nrf5340/cpuapp --pristine=always nrf/samples/bluetooth/peripheral_bms -- -DCONFIG_TRACING=y -DCONFIG_SEGGER_SYSTEMVIEW=y
```
**Expected behavior**
Reference counters, allocators, etc should only be executed once per desired call.

**Impact**
System locks waiting for reference counters or leaks memory when tracing.

**Environment (please complete the following information):**
Fresh ncs sdk 2.8.0 with Zephyr Kernel 3.7.99-ncs1.
Zephyr SDK 0.16.9
build command:

**Comment by fabiobaltieri** [comment]
Hi, Zephyr is an open-source project, and as such we welcome and encourage the community to send patches directly. Would you be able to open a pull request with the fix? This is the [contribution guideline documentation](https://docs.zephyrproject.org/latest/contribute/guidelines.html#contribution-guidelines).

**Comment by HaavardRei** [comment]
Should we also add a similar edit for the first parameters? (fifo/lifo)
I. e. 
```
#define k_fifo_put(fifo, data) \
	({ \
        struct k_fifo *_fifo = fifo; \
	void *_d = data;					\
	SYS_PORT_TRACING_OBJ_FUNC_ENTER(k_fifo, put, _fifo, _d); \
	k_queue_append(&(_fifo)->_queue, _d); \
	SYS_PORT_TRACING_OBJ_FUNC_EXIT(k_fifo, put, _fifo, _d); \
	})
```
