### ISSUE TITLE
doc: Documentation issue in 'boards/shields/semtech_sx1276mb1mas/doc/index'

### ISSUE THREAD

**Issue by maunix74** [zephyrproject-rtos/zephyr#82688]
**Describe the bug**

The shield name is ok but when giving the sample code on how to invoque it, there is a typo

In the programming section says:

Set --shield semtech_sx1271mb1mas when you invoke west build. 

And it should be
Set --shield **semtech_sx1276mb1mas** when you invoke west build. 

<< You may also want to update the automatically generated issue title above. >>

**Environment**

* Page: `boards/shields/semtech_sx1276mb1mas/doc/index`
* Version: main
* SHA-1: ec601b89df93ee0054c9317e80974a924b65e332

**Comment by henrikbrixandersen** [comment]
Please submit a pull request for fixing the documentation.
