### ISSUE TITLE
kernel: threads: no-multithreading: kernel.threads.no-multithreading fails

### ISSUE THREAD

**Issue by katgiadla** [zephyrproject-rtos/zephyr#82736]
**Describe the bug**
Test `tests/kernel/threads/no-multithreading/kernel.threads.no-multithreading` fails.

Observed for 
- `nrf52840dk/nrf52840`
- `nrf9160dk@0.14.0/nrf9160`

**To Reproduce**
1. have `nrf52840dk/nrf52840` connected
2. go to your zephyr dir
3. call `./scripts/twister -s kernel.threads.no-multithreading -p nrf52840dk/nrf52840 --device-testing --device-serial /dev/ttyACM0 -v --inline-logs --west-flash="--erase"`
4. See console output with error (using e.g. minicom)

**Expected behavior**
Console output

**Impact**
Not clear

**Logs and console output**
```
*** Booting Zephyr OS build v4.0.0-1367-g41b0bd12eddb ***
Running TESTSUITE no_multithreading
===================================================================
START - test_cpu_idle

    Assertion failed at zephyr/tests/kernel/threads/no-multithreading/src/main.c:74: no_multithreading_test_cpu_idle: (timeout_run is false)
Timeout should expire
 FAIL - test_cpu_idle in 0.017 seconds
===================================================================
START - test_irq_locking
 PASS - test_irq_locking in 0.015 seconds
===================================================================
START - test_k_busy_wait
 PASS - test_k_busy_wait in 0.010 seconds
===================================================================
START - test_sys_init
 PASS - test_sys_init in 0.001 seconds
===================================================================
TESTSUITE no_multithreading failed.

------ TESTSUITE SUMMARY START ------

SUITE FAIL -  75.00% [no_multithreading]: pass = 3, fail = 1, skip = 0, total = 4 duration = 0.043 seconds
 - FAIL - [no_multithreading.test_cpu_idle] duration = 0.017 seconds
 - PASS - [no_multithreading.test_irq_locking] duration = 0.015 seconds
 - PASS - [no_multithreading.test_k_busy_wait] duration = 0.010 seconds
 - PASS - [no_multithreading.test_sys_init] duration = 0.001 seconds

------ TESTSUITE SUMMARY END ------

===================================================================
RunID: 6aa87f8c651b24cf115f6101728f98a3
PROJECT EXECUTION FAILED
```

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04.1 LTS
- Toolchain Zephyr SDK 0.16.8
- Commit SHA or Version used: ` v4.0.0-1367-g41b0bd`

**Additional information:**
Probably introduced by ec1f662dc96a72b6e4b8b3443915c202ff2240d8

**Comment by RobinKastberg** [comment]
We see these in our testing as well. On this card every time, but intermittently on other targets. e.g. qemu_cortex_m0 as well.
