### ISSUE TITLE
Make flash doesn't work on nrf51_pca10028

### ISSUE THREAD

**Issue by punitvara** [zephyrproject-rtos/zephyr#8274]
```
Using runner: nrfjprog
fatal error: 2 No such file or directory: 'nrfjprog'
run as "west -v ... flash ..." for a stack trace
```

**Comment by punitvara** [comment]
cc: @pizi-nordic

**Comment by nashif** [comment]
`fatal error: 2 No such file or directory: 'nrfjprog'`

Isn't this enough of a hint? Follow the instructions of the board and install the needed dependencies. This is not a bug.
