### ISSUE TITLE
when zephyr can support popular IDE develop?

### ISSUE THREAD

**Issue by fghjhuang** [zephyrproject-rtos/zephyr#8275]
as i say, zephyr is a really good micro system,but i take lots of time to learn and use, if it can support some IDE like keilMDK, IAR, cilon will be make it very popular in increasing developors.

**Comment by MaureenHelm** [comment]
We don't currently support the Keil or IAR compilers, but would welcome pull requests to add them. It is possible to debug Zephyr in Eclipse, see http://docs.zephyrproject.org/application/application.html#eclipse-debugging

**Comment by proverifTmp** [comment]
Hey, the link is broken. Can you update it or point me to some other document about setting debugging environment.

**Comment by aescolar** [comment]
@proverifTmp https://docs.zephyrproject.org/latest/application/index.html#eclipse-debugging

**Comment by mrezaanony** [comment]
Hi

**Comment by mrezaanony** [comment]
Hi

**Comment by mrezaanony** [comment]
Hi 
can zephyr now support Keil or IAR please let me know t if you know .
 Thanks.

**Comment by suja8742** [comment]
Hello. Regarding this topic, is there documentation to run Zephyr on IAR?
