### ISSUE TITLE
ARM: MPU faults should indicate faulting memory address

### ISSUE THREAD

**Issue by andrewboie** [zephyrproject-rtos/zephyr#8293]
MPU faults print something like this:

```
�***** MPU FAULT *****
  Executing thread ID (thread): 0x20002a00
  Faulting instruction address:  0x57a7150c
  Instruction Access Violation
Fatal fault in thread 0x20002a00! Aborting.
```

We need it to show the memory address which was being accessed to trigger the fault which will greatly assist with debugging issues.

**Comment by andrewboie** [comment]
in that case we can close this

**Comment by ioannisg** [comment]
that's my opinion, at least.
