### ISSUE TITLE
Add SWD pinmux to STM32F1 MCU family .dtsi

### ISSUE THREAD

**Issue by alteman** [zephyrproject-rtos/zephyr#82981]
**Is your enhancement proposal related to a problem? Please describe.**
Currently STM32F1 .dtsi files are missing SWD pinmux definitions.

**Describe the solution you'd like**
PR in hal_stm32 to add SWD pins to the f1 .dtsi files: https://github.com/zephyrproject-rtos/hal_stm32/pull/247 

Mentioning maintainer: @erwango

**Comment by erwango** [comment]
Merged.
