### ISSUE TITLE
mimxrt10xx series use flexram-control but does not support magic feature

### ISSUE THREAD

**Issue by hakehuang** [zephyrproject-rtos/zephyr#83036]
**Describe the bug**

mimxrt10xx series use flexram-control but does not support magic feature.

Please also mention any information which could help others to understand
the problem you're facing:
 - What target platform are you using?
 - mimxrt1040/ and all other mimxrt10xx series platforms
 - What have you tried to diagnose or workaround this issue?
 - code check
 - Is this a regression? If yes, have you been able to "git bisect" it to a
   specific commit?
 - 19155bdb26736cc50898a249428e2d7caba443b7

**To Reproduce**

```
scripts/twister -p mimxrt1040_evk -T samples/boards/nxp/mimxrt1170_evk_cm7/magic_addr/ --build-only
```

**Expected behavior**

the case is not supported need skip

**Impact**

CI report

**Logs and console output**

build on not support platform

**Environment (please complete the following information):**

 - OS: (e.g. Linux, MacOS, Windows)
 - Toolchain (e.g Zephyr SDK, ...)
 - Commit SHA or Version used: 29208fe7c45c43997c5099718958f3535f33465b

**Comment by kartben** [comment]
triaging as low, esp. as a fix is already on its way
