### ISSUE TITLE
Bluetooth GATT/SR/GAS/BV-01-C qualification test regression

### ISSUE THREAD

**Issue by piotrnarajowski** [zephyrproject-rtos/zephyr#83178]
**Describe the bug**
Bluetooth GATT qualification test regression after #82062 merge. This commit was indicated by git bisect as first bad commit and reverting it resolves the issue

**To Reproduce**
Execute GATT/SR/GAS/BV-01-C qualification test case with AutoPTS on nRF52

**Expected behavior**
Pass verdict

**Impact**
Bluetooth qualification is affected

**Comment by sjanc** [comment]
@akredalen FYI

**Comment by sjanc** [comment]
GATT/SR/GAS/BV-01-C is about sending Service Changed indication

**Comment by sjanc** [comment]
Fix:  https://github.com/zephyrproject-rtos/zephyr/pull/83221
