### ISSUE TITLE
crypto: drivers use cipher_aead_pkt.tag differently

### ISSUE THREAD

**Issue by jfischer-phytec-iot** [zephyrproject-rtos/zephyr#8339]
API describes that for an encrypton the tag  [will be populated by the driver](https://github.com/zephyrproject-rtos/zephyr/blob/master/include/crypto/cipher_structs.h#L231)

The drivers [crypto_ataes132a.c](https://github.com/zephyrproject-rtos/zephyr/blob/master/drivers/crypto/crypto_ataes132a.c#L549) and [mbedtls ](https://github.com/zephyrproject-rtos/zephyr/blob/master/ext/lib/crypto/mbedtls/library/ccm.c#L301) seem to follow the API. [crypto_tc_shim.c](https://github.com/zephyrproject-rtos/zephyr/blob/master/drivers/crypto/crypto_tc_shim.c#L123 ) and [_cc2520_crypto_ccm(...)](https://github.com/zephyrproject-rtos/zephyr/blob/master/drivers/ieee802154/ieee802154_cc2520.c#L1336) assign a matching address from the cipher_pkt.out_buf to the tag pointer.

**Comment by wentongwu** [comment]
from the code (./ext/lib/crypto/tinycrypt),  it seems TinyCrypt appends encrypted authentication data to the end of out_buf. User needs to be aware of this and provide sufficient buffer space in output buffer to hold both encrypted output and the tag(encrypted authentication data). 

and from mbed code(./ext/lib/crypto/mbedtls), it just copy the encrypted authentication data to tag buffer, and there is no  relevance between tag buffer and output buffer.

Zephyr do the shim for both libraries( tinycrypt and mbedtls), and each of the shim just follows the library accordingly, so crypto_tc_shim.c doesn't follow the API defined in the .h file.

two methods to solve this problem. First,  in the shim function for tinycrypt, allocate one buffer in heap to hold encrypted output and the tag and give this buffer to tinycrypt. And when done the tinycrypt calculation, copy the output data and tag data to user buffer separately from the allocated buffer, and finally do the release.  Second, just hack the tinycrypt CCM algorithm's code and behaves like mbedtls. 
The second one need change some API but doesn't need extra buffer, so I'm doing the second development...

**Comment by wentongwu** [comment]
PR #14103 should fix this issue
