### ISSUE TITLE
mcumgr: unable to properly read big files

### ISSUE THREAD

**Issue by nvlsianpu** [zephyrproject-rtos/zephyr#8364]
Can't to read bigger files. Looks lik it is possible to write big files (tested up to 8 KB) - they are sends as small chunks. Reading of such files is impossible - suspected thet the library can not divide bigger files into chunks.

Issue reported for the smp_svr@nrf52_pca10040

related to https://github.com/apache/mynewt-mcumgr/issues/6

**Comment by carlescufi** [comment]
CC @philips77

**Comment by nashif** [comment]
external project issue, lowering priority.

**Comment by rljordan** [comment]
Any updates on this issue?

**Comment by nvlsianpu** [comment]
cc @de-nordic

**Comment by de-nordic** [comment]
My first finding is that: the problem is with cbor encoder running out of memory, while trying to encode  single buffer of  FS_MGMT_DL_CHUNK_SIZE.

**Comment by de-nordic** [comment]
It seems that cbor it trying to fit entire FS_MGMT_DL_CHUNK_SIZE (default 512 bytes) into MCUMGR_BUF_SIZE of buffer which is already partially filled with header data and by default it is 384 bytes in size.

**Comment by de-nordic** [comment]
I think this has been fixed her: https://github.com/zephyrproject-rtos/zephyr/pull/23515

**Comment by nvlsianpu** [comment]
Thanks @de-nordic!
