### ISSUE TITLE
nRF5: enable UARTE peripheral support

### ISSUE THREAD

**Issue by mike-scott** [zephyrproject-rtos/zephyr#8371]
The currently supported nRF52832 and nRF52840 boards have the option of using UARTE0 peripheral instead of UART0.  This provides better power usage due to EasyDMA use.

On nRF52840 there is also a UARTE1 peripheral.

This issue tracks efforts to enable UARTE.

**Comment by jarz-nordic** [comment]
[PR8640](https://github.com/zephyrproject-rtos/zephyr/pull/8640) will provide UARTE0 and UARTE1 driver.

**Comment by mike-scott** [comment]
@jarz-nordic: its on my TODO list :)

**Comment by carlescufi** [comment]
Completed
