### ISSUE TITLE
cmake: ninja clean tries to remove include folders

### ISSUE THREAD

**Issue by tejlmand** [zephyrproject-rtos/zephyr#8380]
Discovered that the following code from #8211 has a very bad side effect.
add_custom_command(OUTPUT ${PARSE_SYSCALLS_PATHS_DEPENDS}
  COMMAND ${CMAKE_COMMAND} -E echo ""                                                                                                                 
  COMMENT "Preparing syscall dependency handling"                                                                                                                                                           )
as specifying OUTPUT this way is causing ninja to try removing the folders during a 'ninja clean'

Error seen during ninja clean:
ninja clean
[1/1] Cleaning all built files...
FAILED: /usr/bin/ninja -t clean
ninja: error: remove(/projects/github/tejlmand/zephyr/include): Directory not empty
ninja: error: remove(/projects/github/tejlmand/zephyr/include/logging): Directory not empty
ninja: error: remove(/projects/github/tejlmand/zephyr/include/drivers): Directory not empty
......

Looking into a fix already.

**Comment by yashi** [comment]
Make is worse.  I does delete the include dir.
```
$ make clean
$ git status
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	deleted:    ../../../include/adc.h
	deleted:    ../../../include/aio_comparator.h
	deleted:    ../../../include/arch/arc/arch.h
   :
   :
```
