### ISSUE TITLE
Assigning to promptless symbols should have a better error message

### ISSUE THREAD

**Issue by SebastianBoe** [zephyrproject-rtos/zephyr#8388]
Hi,

I accidentally tried to assign to a promptless symbol and got the error message:

`warning: COOP_ENABLED (defined at kernel/Kconfig:88) was assigned the value "n" but got the value "y". Check its dependencies in the 'menuconfig' interface (see the Application Development Primer section of the manual), or in the Kconfig reference at http://docs.zephyrproject.org/reference/kconfig/CONFIG_COOP_ENABLED.html (which is updated regularly from the master branch)`

This feedback sent me down the wrong path as I was checking it's dependencies instead of checking if it had a prompt. Is it possible for Kconfiglib to detect assignments to promptless symbols?

**Comment by ulfalizer** [comment]
@SebastianBoe 
Yep, should be easy to add. Will do.
