### ISSUE TITLE
Add input capability to the RTT console

### ISSUE THREAD

**Issue by rodrigopex** [zephyrproject-rtos/zephyr#8394]
The host (computer with RTT) will be able to send data to the device through RTT Console subsystem. For now, only the device can send data to the host using RTT console.

**Comment by zhaozhongchen** [comment]
![60ade5bcf8b649ac](https://user-images.githubusercontent.com/16350380/41445138-098a6c30-707a-11e8-8409-07728619ef3e.gif)

I had write one but seems RTT inputs is not good

**Comment by rodrigopex** [comment]
I was taking a look at your code and I could not find the code you've implemented this. The [rtt_console.c](https://github.com/zhaozhongchen/zephyr/blob/master/drivers/console/rtt_console.c) seems to be the same as the master. Can you share the code? I was planning to create a low priority task that would be running inside the console RTT driver checking the haskey function from RTT SEGGER lib.

**Comment by zhaozhongchen** [comment]
I haven't push that branch because I think thats was not useful. I will push them later if you like it. All Chinese has a 3 days holiday now.

I created a thread running every 10ms and check RTT inputs, process RX data if available.

**Comment by zhaozhongchen** [comment]
I had updated my code and pushed them on my local branch: [rtt](https://github.com/zhaozhongchen/zephyr/tree/rtt)

![rtt_console](https://user-images.githubusercontent.com/16350380/41591317-f4dde0e4-73eb-11e8-804c-c3dc14558c4c.gif)
