### ISSUE TITLE
[Coverity CID :186583] Error handling issues in /samples/net/sockets/dumb_http_server/src/socket_dumb_http.c

### ISSUE THREAD

**Issue by mandarcthorat1** [zephyrproject-rtos/zephyr#8413]
Static code scan issues seen in File: /samples/net/sockets/dumb_http_server/src/socket_dumb_http.c
 Category: Error handling issues
 Function: main
 Component: Samples
 CID: 186583
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by satyacube** [comment]
Working on addressing this issue!
