### ISSUE TITLE
[Coverity CID :186582] Memory - corruptions in /subsys/bluetooth/host/gatt.c

### ISSUE THREAD

**Issue by mandarcthorat1** [zephyrproject-rtos/zephyr#8414]
Static code scan issues seen in File: /subsys/bluetooth/host/gatt.c
 Category: Memory - corruptions
 Function: gatt_indicate
 Component: Bluetooth
 CID: 186582
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by jhedberg** [comment]
Marked as false positive in coverity (like all the bt_uuid_t issues)
