### ISSUE TITLE
[Coverity CID :186581] Memory - corruptions in /subsys/bluetooth/host/gatt.c

### ISSUE THREAD

**Issue by mandarcthorat1** [zephyrproject-rtos/zephyr#8415]
Static code scan issues seen in File: /subsys/bluetooth/host/gatt.c
 Category: Memory - corruptions
 Function: bt_gatt_notify
 Component: Bluetooth
 CID: 186581
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by Vudentz** [comment]
I guess it is this issue:

'Overrunning struct type bt_uuid_16 of 4 bytes by passing it to a function which accesses it at byte offset 16.'

That shall be considered a false positive, if the type is different then uuid128_cmp is used so I wonder why Coverity is not able to detect it.
