### ISSUE TITLE
mqtt: unimplemented MQTT_UNSUBACK in mqtt_parser function in mqtt.c file

### ISSUE THREAD

**Issue by changkong5** [zephyrproject-rtos/zephyr#8431]
```
static int mqtt_parser(struct mqtt_ctx *ctx, struct net_pkt *rx)
{
	u16_t pkt_type = MQTT_INVALID;
	struct net_buf *data = NULL;
	int rc = -EINVAL;

	data = mqtt_linearize_packet(ctx, rx, MQTT_PUBLISHER_MIN_MSG_SIZE);
	if (!data) {
		return -ENOMEM;
	}

	pkt_type = MQTT_PACKET_TYPE(data->data[0]);

	switch (pkt_type) {
	case MQTT_CONNACK:
		if (!ctx->connected) {
			rc = mqtt_rx_connack(ctx, data, ctx->clean_session);
		} else {
			rc = -EINVAL;
		}
		break;
	case MQTT_PUBACK:
		rc = mqtt_rx_puback(ctx, data);
		break;
	case MQTT_PUBREC:
		rc = mqtt_rx_pubrec(ctx, data);
		break;
	case MQTT_PUBCOMP:
		rc = mqtt_rx_pubcomp(ctx, data);
		break;
	case MQTT_PINGRESP:
		rc = mqtt_rx_pingresp(ctx, data);
		break;
	case MQTT_PUBLISH:
		rc = mqtt_rx_publish(ctx, data);
		break;
	case MQTT_PUBREL:
		rc = mqtt_rx_pubrel(ctx, data);
		break;
	case MQTT_SUBACK:
		rc = mqtt_rx_suback(ctx, data);
		break;
	default:
		rc = -EINVAL;
		break;
	}

	if (rc != 0 && ctx->malformed) {
		ctx->malformed(ctx, pkt_type);
	}

	net_pkt_frag_unref(data);

	return rc;
}
```

running log:

publish_rx_cb:188] <MQTT_PUBLISH> msg->pkt_id = 0x0 msg->topic_len = 7 topic = sensorsmsg->msg_len = 15 msg: DOORS:OPEN_QoS2, user_data: SUBSCRIBE
[publisher_subscriber:484] mqtt_tx_publish: 0 <OK>
[malformed_cb:277] pkt_type: 11
[disconnect_cb:104] user_data: DISCONNECTED
[publisher_subscriber:491] mqtt_tx_disconnect: 0 <OK>

**Comment by XXXXzzzz000** [comment]
i found a function in the `mqtt.c`     
```c
int mqtt_rx_unsuback(struct mqtt_ctx *ctx, struct net_buf `*rx)
```
and i think just need fix the missing case in the function `mqtt_parser`

```c
case MQTT_UNSUBACK:
        rc = mqtt_rx_unsuback(ctx, data);
        break;
```

**Comment by nashif** [comment]
can you please submit a PR with this fix?

**Comment by changkong5** [comment]
@nashif  I will try to do it . I add the code rc = mqtt_rx_unsuback(ctx, data); to mqtt_parser and test it on nucleo_f429zi board.

**Comment by changkong5** [comment]
@XXXXzzzz000  yes  I think you are right. add the code to mqtt_parser and the run log following.

static int mqtt_parser(struct mqtt_ctx *ctx, struct net_pkt *rx)
{
	u16_t pkt_type = MQTT_INVALID;
	struct net_buf *data = NULL;
	int rc = -EINVAL;

	data = mqtt_linearize_packet(ctx, rx, MQTT_PUBLISHER_MIN_MSG_SIZE);
	if (!data) {
		return -ENOMEM;
	}

	pkt_type = MQTT_PACKET_TYPE(data->data[0]);

	switch (pkt_type) {
	case MQTT_CONNACK:
		if (!ctx->connected) {
			rc = mqtt_rx_connack(ctx, data, ctx->clean_session);
		} else {
			rc = -EINVAL;
		}
		break;
	case MQTT_PUBACK:
		rc = mqtt_rx_puback(ctx, data);
		break;
	case MQTT_PUBREC:
		rc = mqtt_rx_pubrec(ctx, data);
		break;
	case MQTT_PUBCOMP:
		rc = mqtt_rx_pubcomp(ctx, data);
		break;
	case MQTT_PINGRESP:
		rc = mqtt_rx_pingresp(ctx, data);
		break;
	case MQTT_PUBLISH:
		rc = mqtt_rx_publish(ctx, data);
		break;
	case MQTT_PUBREL:
		rc = mqtt_rx_pubrel(ctx, data);
		break;
	case MQTT_SUBACK:
		rc = mqtt_rx_suback(ctx, data);
		break;
	case MQTT_UNSUBACK:
		rc = mqtt_rx_unsuback(ctx, data);
		break;
	default:
		rc = -EINVAL;
		break;
	}

	if (rc != 0 && ctx->malformed) {
		ctx->malformed(ctx, pkt_type);
	}

	net_pkt_frag_unref(data);

	return rc;
}

lsb-ThinkPad-E470:~$ mosquitto_sub -t "sensors" -v
sensors DOORS:OPEN_QoS0
sensors DOORS:OPEN_QoS1
sensors DOORS:OPEN_QoS2
sensors DOORS:OPEN_QoS0
sensors DOORS:OPEN_QoS1
sensors DOORS:OPEN_QoS2
sensors DOORS:OPEN_QoS0
sensors DOORS:OPEN_QoS1
sensors DOORS:OPEN_QoS2
sensors DOORS:OPEN_QoS0
sensors DOORS:OPEN_QoS1
sensors DOORS:OPEN_QoS2
sensors DOORS:OPEN_QoS0
sensors DOORS:OPEN_QoS1
sensors DOORS:OPEN_QoS2
sensors DOORS:OPEN_QoS0
sensors DOORS:OPEN_QoS1
sensors DOORS:OPEN_QoS2





***** Booting Zephyr OS 1.12.99 *****
[publisher_subscriber:431] network_setup: 0 <OK>
[publisher_subscriber:438] mqtt_init: 0 <OK>
[publisher_subscriber:445] mqtt_connect: 0 <OK>
[connect_cb:85] user_data: CONNECTED
[try_to_connect:339] mqtt_tx_connect: 0 <OK>
[publisher_subscriber:456] try_to_connect: 0 <OK>
[publisher_subscriber:461] mqtt_subscribe ... [subscriber_cb:236] items: 1 packet id: 51395 user_data: SUBSCRIBE
[publisher_subscriber:470] mqtt_tx_pingreq: 0 <OK>
[publish_rx_cb:188] <MQTT_PUBLISH> msg->pkt_id = 0x0 msg->topic_len = 7 topic = sensorsmsg->msg_len = 15 msg: DOORS:OPEN_QoS0, user_data: SUBSCRIBE
[publisher_subscriber:475] mqtt_tx_publish: 0 <OK>
[publish_cb:151] <MQTT_PUBACK> packet id: 26527, user_data: PUBLISH
[publish_rx_cb:188] <MQTT_PUBLISH> msg->pkt_id = 0x0 msg->topic_len = 7 topic = sensorsmsg->msg_len = 15 msg: DOORS:OPEN_QoS1, user_data: SUBSCRIBE
[publisher_subscriber:480] mqtt_tx_publish: 0 <OK>
[publish_cb:151] <MQTT_PUBREC> packet id: 36916, user_data: PUBLISH
[publish_cb:151] <MQTT_PUBCOMP> packet id: 36916, user_data: PUBLISH
[publisher_subscriber:485] mqtt_tx_publish: 0 <OK>
[publisher_subscriber:470] mqtt_tx_pingreq: 0 <OK>
[publish_rx_cb:188] <MQTT_PUBLISH> msg->pkt_id = 0x0 msg->topic_len = 7 topic = sensorsmsg->msg_len = 15 msg: DOORS:OPEN_QoS0, user_data: SUBSCRIBE
[publisher_subscriber:475] mqtt_tx_publish: 0 <OK>
[publish_cb:151] <MQTT_PUBACK> packet id: 21426, user_data: PUBLISH
[publish_rx_cb:188] <MQTT_PUBLISH> msg->pkt_id = 0x0 msg->topic_len = 7 topic = sensorsmsg->msg_len = 15 msg: DOORS:OPEN_QoS1, user_data: SUBSCRIBE
[publisher_subscriber:480] mqtt_tx_publish: 0 <OK>
[publish_cb:151] <MQTT_PUBREC> packet id: 17407, user_data: PUBLISH
[publish_cb:151] <MQTT_PUBCOMP> packet id: 17407, user_data: PUBLISH
[publish_rx_cb:188] <MQTT_PUBLISH> msg->pkt_id = 0x0 msg->topic_len = 7 topic = sensorsmsg->msg_len = 15 msg: DOORS:OPEN_QoS2, user_data: SUBSCRIBE
[publisher_subscriber:485] mqtt_tx_publish: 0 <OK>
[publisher_subscriber:470] mqtt_tx_pingreq: 0 <OK>
[publish_rx_cb:188] <MQTT_PUBLISH> msg->pkt_id = 0x0 msg->topic_len = 7 topic = sensorsmsg->msg_len = 15 msg: DOORS:OPEN_QoS0, user_data: SUBSCRIBE
[publisher_subscriber:475] mqtt_tx_publish: 0 <OK>
[publish_cb:151] <MQTT_PUBACK> packet id: 18827, user_data: PUBLISH
[publish_rx_cb:188] <MQTT_PUBLISH> msg->pkt_id = 0x0 msg->topic_len = 7 topic = sensorsmsg->msg_len = 15 msg: DOORS:OPEN_QoS1, user_data: SUBSCRIBE
[publisher_subscriber:480] mqtt_tx_publish: 0 <OK>
[publish_cb:151] <MQTT_PUBREC> packet id: 36248, user_data: PUBLISH
[publish_cb:151] <MQTT_PUBCOMP> packet id: 36248, user_data: PUBLISH
[publish_rx_cb:188] <MQTT_PUBLISH> msg->pkt_id = 0x0 msg->topic_len = 7 topic = sensorsmsg->msg_len = 15 msg: DOORS:OPEN_QoS2, user_data: SUBSCRIBE
[publisher_subscriber:485] mqtt_tx_publish: 0 <OK>
[publisher_subscriber:488] mqtt_unsubscribe ... [unsubscribe_cb:259] packet id: 49670 user_data: UNSUBSCRIBE
[disconnect_cb:104] user_data: DISCONNECTED
[publisher_subscriber:493] mqtt_tx_disconnect: 0 <OK>

Bye!

**Comment by changkong5** [comment]
ThinkPad-E470:~$ mosquitto -v
1531148576: mosquitto version 1.4.5 (build date 2017-10-25 22:14:47+0800) starting
1531148576: Using default config.
1531148576: Opening ipv4 listen socket on port 1883.
1531148576: Opening ipv6 listen socket on port 1883.
1531148591: New connection from 127.0.0.1 on port 1883.
1531148591: New client connected from 127.0.0.1 as mosqsub/5981-lsb-ThinkP (c1, k60).
1531148591: Sending CONNACK to mosqsub/5981-lsb-ThinkP (0, 0)
1531148591: Received SUBSCRIBE from mosqsub/5981-lsb-ThinkP
1531148591: 	sensors (QoS 0)
1531148591: mosqsub/5981-lsb-ThinkP 0 sensors
1531148591: Sending SUBACK to mosqsub/5981-lsb-ThinkP
1531148616: New connection from 192.168.0.102 on port 1883.
1531148616: New client connected from 192.168.0.102 as zephyr_publisher (c1, k0).
1531148616: Sending CONNACK to zephyr_publisher (0, 0)
1531148616: Received SUBSCRIBE from zephyr_publisher
1531148616: 	sensors (QoS 0)
1531148616: zephyr_publisher 0 sensors
1531148616: Sending SUBACK to zephyr_publisher
1531148617: Received PINGREQ from zephyr_publisher
1531148617: Sending PINGRESP to zephyr_publisher
1531148617: Received PUBLISH from zephyr_publisher (d0, q0, r0, m0, 'sensors', ... (15 bytes))
1531148617: Sending PUBLISH to mosqsub/5981-lsb-ThinkP (d0, q0, r0, m0, 'sensors', ... (15 bytes))
1531148617: Sending PUBLISH to zephyr_publisher (d0, q0, r0, m0, 'sensors', ... (15 bytes))
1531148618: Received PUBLISH from zephyr_publisher (d0, q1, r0, m11185, 'sensors', ... (15 bytes))
1531148618: Sending PUBACK to zephyr_publisher (Mid: 11185)
1531148618: Sending PUBLISH to mosqsub/5981-lsb-ThinkP (d0, q0, r0, m0, 'sensors', ... (15 bytes))
1531148618: Sending PUBLISH to zephyr_publisher (d0, q0, r0, m0, 'sensors', ... (15 bytes))
1531148618: Received PUBLISH from zephyr_publisher (d0, q2, r0, m46876, 'sensors', ... (15 bytes))
1531148618: Sending PUBREC to zephyr_publisher (Mid: 46876)
1531148618: Received PUBREL from zephyr_publisher (Mid: 46876)
1531148618: Sending PUBCOMP to zephyr_publisher (Mid: 46876)
1531148618: Sending PUBLISH to mosqsub/5981-lsb-ThinkP (d0, q0, r0, m0, 'sensors', ... (15 bytes))
1531148618: Sending PUBLISH to zephyr_publisher (d0, q0, r0, m0, 'sensors', ... (15 bytes))
1531148619: Received PINGREQ from zephyr_publisher
1531148619: Sending PINGRESP to zephyr_publisher
1531148619: Received PUBLISH from zephyr_publisher (d0, q0, r0, m0, 'sensors', ... (15 bytes))
1531148619: Sending PUBLISH to mosqsub/5981-lsb-ThinkP (d0, q0, r0, m0, 'sensors', ... (15 bytes))
1531148619: Sending PUBLISH to zephyr_publisher (d0, q0, r0, m0, 'sensors', ... (15 bytes))
1531148620: Received PUBLISH from zephyr_publisher (d0, q1, r0, m44260, 'sensors', ... (15 bytes))
1531148620: Sending PUBACK to zephyr_publisher (Mid: 44260)
1531148620: Sending PUBLISH to mosqsub/5981-lsb-ThinkP (d0, q0, r0, m0, 'sensors', ... (15 bytes))
1531148620: Sending PUBLISH to zephyr_publisher (d0, q0, r0, m0, 'sensors', ... (15 bytes))
1531148620: Received PUBLISH from zephyr_publisher (d0, q2, r0, m24526, 'sensors', ... (15 bytes))
1531148620: Sending PUBREC to zephyr_publisher (Mid: 24526)
1531148620: Received PUBREL from zephyr_publisher (Mid: 24526)
1531148620: Sending PUBCOMP to zephyr_publisher (Mid: 24526)
1531148620: Sending PUBLISH to mosqsub/5981-lsb-ThinkP (d0, q0, r0, m0, 'sensors', ... (15 bytes))
1531148620: Sending PUBLISH to zephyr_publisher (d0, q0, r0, m0, 'sensors', ... (15 bytes))
1531148621: Received PINGREQ from zephyr_publisher
1531148621: Sending PINGRESP to zephyr_publisher
1531148621: Received PUBLISH from zephyr_publisher (d0, q0, r0, m0, 'sensors', ... (15 bytes))
1531148621: Sending PUBLISH to mosqsub/5981-lsb-ThinkP (d0, q0, r0, m0, 'sensors', ... (15 bytes))
1531148621: Sending PUBLISH to zephyr_publisher (d0, q0, r0, m0, 'sensors', ... (15 bytes))
1531148622: Received PUBLISH from zephyr_publisher (d0, q1, r0, m51296, 'sensors', ... (15 bytes))
1531148622: Sending PUBACK to zephyr_publisher (Mid: 51296)
1531148622: Sending PUBLISH to mosqsub/5981-lsb-ThinkP (d0, q0, r0, m0, 'sensors', ... (15 bytes))
1531148622: Sending PUBLISH to zephyr_publisher (d0, q0, r0, m0, 'sensors', ... (15 bytes))
1531148622: Received PUBLISH from zephyr_publisher (d0, q2, r0, m21881, 'sensors', ... (15 bytes))
1531148622: Sending PUBREC to zephyr_publisher (Mid: 21881)
1531148622: Received PUBREL from zephyr_publisher (Mid: 21881)
1531148622: Sending PUBCOMP to zephyr_publisher (Mid: 21881)
1531148622: Sending PUBLISH to mosqsub/5981-lsb-ThinkP (d0, q0, r0, m0, 'sensors', ... (15 bytes))
1531148622: Sending PUBLISH to zephyr_publisher (d0, q0, r0, m0, 'sensors', ... (15 bytes))
1531148623: Received UNSUBSCRIBE from zephyr_publisher
1531148623: 	sensors
1531148623: zephyr_publisher sensors
1531148625: Received DISCONNECT from zephyr_publisher
1531148625: Client zephyr_publisher disconnected.
1531148651: Received PINGREQ from mosqsub/5981-lsb-ThinkP
1531148651: Sending PINGRESP to mosqsub/5981-lsb-ThinkP
