### ISSUE TITLE
Broken Arduino 101 Bluetooth Core flashing

### ISSUE THREAD

**Issue by MariuszSkamra** [zephyrproject-rtos/zephyr#8470]
I tried to flash Arduino 101 according to instructions from here: http://docs.zephyrproject.org/boards/x86/arduino_101/doc/board.html#flashing-the-bluetooth-core
I get an error "No flash runner available for curie_ble. https://pastebin.com/ExrYYfPG

On the other hand, calling dfu-util directly `dfu-util -a ble_core -D zephyr/zephyr.bin` works
Flashing HelloWorld on x86 core works as well.

**Comment by jfischer-phytec-iot** [comment]
see #8177

**Comment by nashif** [comment]
fixed by #8177

**Comment by hulkco** [comment]
hi, i have the same isue, and fix by using: dfu-util -a ble_core -D zephyr/zephyr.bin
i using Zephyr SDK 0.9.3 with git checkout tags/v1.12.0
