### ISSUE TITLE
Remove the Kconfig helper options for nRF ICs once DT can replace them

### ISSUE THREAD

**Issue by carlescufi** [zephyrproject-rtos/zephyr#8481]
The helper options introduced by #8363 are a temporary measure until #7302 is resolved in a way that allows us to handle the equivalent hardware support mapping into ICs properly.

Remove them once the relationship between Kconfig and DT is clarified and there is a clear path ahead on how to deal with instancing.

**Comment by galak** [comment]
Not sure if this can be resolved yet or not.

**Comment by galak** [comment]
@carlescufi is this resolved?

**Comment by galak** [comment]
@carlescufi ?

**Comment by carlescufi** [comment]
@galak this is not resolved, the Kconfig options are still [there](https://github.com/zephyrproject-rtos/zephyr/blob/master/soc/arm/nordic_nrf/Kconfig.peripherals). 
@anangl will follow-up after 2.1 code freeze.

**Comment by nashif** [comment]
@carlescufi  Any updates on this?

**Comment by mbolivar-nordic** [comment]
There is some work in progress in https://github.com/zephyrproject-rtos/zephyr/pull/35398

**Comment by carlescufi** [comment]
> There is some work in progress in #35398

Thanks.
@anangl we should try to close this in the 2.7 release cycle.

**Comment by mbolivar-nordic** [comment]
@anangl I think this one is finally done, right?

**Comment by anangl** [comment]
> @anangl I think this one is finally done, right?

Yes, it is resolved by #44276.
