### ISSUE TITLE
I think there is a issue about shell.

### ISSUE THREAD

**Issue by walter-xie** [zephyrproject-rtos/zephyr#8501]
In shell.c file  "get_completion_module" function ,the code "return str ? dest : NULL;" should be "return str ? NULL : dest;"

**Comment by carlescufi** [comment]
Assigning to @jhedberg after git blaming

**Comment by walter-xie** [comment]
I think line shell.c:522 should be fixed too.

**Comment by jhedberg** [comment]
> I think line shell.c:522 should be fixed too.

@walter-xie it seems you're right, but this issue is already closed. You'll need to open a new one. Even better, do you want to try to submit a pull request to fix this second line? This would be an easy task to get started as a contributor to the Zephyr project.

**Comment by jhedberg** [comment]
>> I think line shell.c:522 should be fixed too.

> @walter-xie it seems you're right, but this issue is already closed. You'll need to open a new one. Even better, do you want to try to submit a pull request to fix this second line? This would be an easy task to get started as a contributor to the Zephyr project.

It's now a couple of weeks since the above comment, and I haven't seen any response or new pull request, so I went ahead and created one myself: #8795
