### ISSUE TITLE
Compiling for native_posix with newlib is missing various math symbols

### ISSUE THREAD

**Issue by jukkar** [zephyrproject-rtos/zephyr#8502]
Just noticed that if I have

```
CONFIG_NEWLIB_LIBC=y
CONFIG_NEWLIB_LIBC_FLOAT_PRINTF=y
```

defined and my application tries to use `sqrt()` or `pow()` math functions, then with native_posix board I will get following linker error:

```
subsys/net/ip/l2/gptp/libsubsys__net__ip__l2__gptp.a(gptp.c.obj): In function `get_stats':
zephyr/subsys/net/ip/l2/gptp/gptp.c:922: undefined reference to `sqrt'
subsys/net/ip/l2/gptp/libsubsys__net__ip__l2__gptp.a(gptp_messages.c.obj): In function `gptp_handle_sync':
zephyr/subsys/net/ip/l2/gptp/gptp_messages.c:885: undefined reference to `pow'
subsys/net/ip/l2/gptp/libsubsys__net__ip__l2__gptp.a(gptp_mi.c.obj): In function `gptp_mi_pss_rcv_compute':
zephyr/subsys/net/ip/l2/gptp/gptp_mi.c:315: undefined reference to `pow'
collect2: error: ld returned 1 exit status
```

There is no error if minimal libc and native_posix are being used. I need to use newlib in some cases because %f print modifier does not work with minimal libc.

Tested this with frdm_k64f and sam_e70_xplained boards, and there the math symbols are found just fine during linking if newlib is enabled. So this only affects newlib with native_posix board.

**Comment by aescolar** [comment]
PR with fix coming
