### ISSUE TITLE
rpl-mesh-qemu sample, the net inface init failed.

### ISSUE THREAD

**Issue by walter-xie** [zephyrproject-rtos/zephyr#8528]
[net/rpl] [DBG] dio_timer: (0x20000df0): Sending DIO later because IPv6 link local address is not found 

CONFIG_NET_APP_SETTINGS=y
samples: rpl-mesh-qemu
_net_app_ieee802154_setup() function would return -EINVAL in line 51.
upipe_set_channel() and upipe_set_txpower() function should just "return 0;"

**Comment by nashif** [comment]
@rveerama1 ping

**Comment by rveerama1** [comment]
I will check.
