### ISSUE TITLE
samples/mpu/mem_domain_apis_test/kernel.memory_protection.memory_domains fails to build

### ISSUE THREAD

**Issue by galak** [zephyrproject-rtos/zephyr#8593]
On several of the STM32 platforms the test fails:

./scripts/sanitycheck -p 96b_carbon  -s  samples/mpu/mem_domain_apis_test/kernel.memory_protection.memory_domains

This is due to the following change:

"arch: arm: mpu: include CMSIS header in arm_mpu.h"

**Comment by erwango** [comment]
It is strange this has not been detected by shippable.
Do we know how it happened?
