### ISSUE TITLE
Not able to bind the adc device structure for nrf52832 controller

### ISSUE THREAD

**Issue by rajatkalyan** [zephyrproject-rtos/zephyr#8600]
I am not able to bind the adc device structure for nrf52832(nrf52__pca10040 ).
When i define configuration in prj.conf file, cmake says "Warning: ADC_0_NAME was assigned the value "ADC_0" but got the value "", Check dependencies.
What is the solution to this?

**Comment by carlescufi** [comment]
Hi @rajatkalyan. ADC support is not merged yet. Please track this PR until it gets merged:
https://github.com/zephyrproject-rtos/zephyr/pull/7691/commits
