### ISSUE TITLE
[Coverity CID :186851] Error handling issues in /tests/bluetooth/mesh/src/microbit.c

### ISSUE THREAD

**Issue by mandarcthorat1** [zephyrproject-rtos/zephyr#8690]
Static code scan issues seen in File: /tests/bluetooth/mesh/src/microbit.c
 Category: Error handling issues
 Function: configure_button
 Component: Tests
 CID: 186851
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by jhedberg** [comment]
classified as intentional in coverity
