### ISSUE TITLE
[Coverity CID :186846] Null pointer dereferences in /tests/net/ptp/clock/src/main.c

### ISSUE THREAD

**Issue by mandarcthorat1** [zephyrproject-rtos/zephyr#8695]
Static code scan issues seen in File: /tests/net/ptp/clock/src/main.c
 Category: Null pointer dereferences
 Function: test_ptp_clock_iface
 Component: Tests
 CID: 186846
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by jukkar** [comment]
False positive.
