### ISSUE TITLE
[Coverity CID :186845] Parse warnings in /tests/net/ieee802154/l2/src/ieee802154_test.c

### ISSUE THREAD

**Issue by mandarcthorat1** [zephyrproject-rtos/zephyr#8696]
Static code scan issues seen in File: /tests/net/ieee802154/l2/src/ieee802154_test.c
 Category: Parse warnings
 Function: 
 Component: Tests
 CID: 186845
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by jukkar** [comment]
False positive

**Comment by mandarcthorat1** [comment]
Fixed with #8645
