### ISSUE TITLE
[Coverity CID :186844] Parse warnings in /tests/net/ieee802154/fragment/src/main.c

### ISSUE THREAD

**Issue by mandarcthorat1** [zephyrproject-rtos/zephyr#8697]
Static code scan issues seen in File: /tests/net/ieee802154/fragment/src/main.c
 Category: Parse warnings
 Function: 
 Component: Tests
 CID: 186844
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by jukkar** [comment]
False positive.

**Comment by mandarcthorat1** [comment]
Fixed with #8645
