### ISSUE TITLE
Out of the box error in samples/subsys/nvs with nRF52-PCA10040

### ISSUE THREAD

**Issue by GerlichM** [zephyrproject-rtos/zephyr#8705]
Hello,

i want to use the subsys/nvs sample with the nRF52-PCA10040 board with Zephyr version 1.12
The (unedited) sample compiles fine with cmake and ninja but after flashing the following error messages occur:

***** Booting Zephyr OS 1.12.99 *****                                           
Flash Init failed                                                               
No address found, adding 192.168.1.1 at id 1                                    
No key found, adding it at id 2                                                 
No Reboot counter found, adding it at id 3                                      
Id: 4 not found, adding it                                                      
Reboot counter history: Error, no Reboot counter

![screenshot at 2018-07-03 14 40 01](https://user-images.githubusercontent.com/40766950/42220363-00ebf536-7ecf-11e8-9e2a-0f9e46b44fe2.png)

For some reason it cannot initialize the nvs in
...
rc = nvs_init(&fs, FLASH_DEV_NAME, STORAGE_MAGIC);
	if (rc) {
		printk("Flash Init failed\n");
	}
...

The default configurations in prj.config are:
CONFIG_FLASH=y

CONFIG_NVS=y
CONFIG_NVS_LOG=y
CONFIG_NVS_LOG_LEVEL=4
CONFIG_REBOOT=y

Thanks!

**Comment by carlescufi** [comment]
CC @Laczen

**Comment by Laczen** [comment]
Hi @GerlichM , could you add the following line to the config file:
CONFIG_MPU_ALLOW_FLASH_WRITE=y

**Comment by GerlichM** [comment]
Hi @Laczen ,
thank you for your answer.
I added  CONFIG_MPU_ALLOW_FLASH_WRITE=y to the config file,
the output still shows "flash init failed"

**Comment by Laczen** [comment]
Hi @GerlichM, I don't have a nrf52-PCA10040 board, so it is quite difficult for me to guide you.

However I have seen that the nrf52 has a flash page size of 4096, maybe this is the reason. Could you change the sample to: NVS_SECTOR_SIZE 4096 and retry.

**Comment by nashif** [comment]
not able to reproduce this with the mentioned board.
