### ISSUE TITLE
posix:  Memory is not returned to mempool when a pthread complete its execution

### ISSUE THREAD

**Issue by punitvara** [zephyrproject-rtos/zephyr#8717]
Currently thread object is allocated space through mempool.
we are not returning allocated memory back to pool when thread exits.

Testcase to Reproduce
==================
create and delete multiple threads using pthread_create, You will run out of slace soon.

**Comment by nashif** [comment]
@punitvara what is the status?

**Comment by nashif** [comment]
@punitvara  status?

**Comment by ManojSubbarao** [comment]
@rgundi Please look into this issue.
