### ISSUE TITLE
Network stack cleanup: RPL

### ISSUE THREAD

**Issue by tbursztyka** [zephyrproject-rtos/zephyr#8724]
rpl.c needs cleanup:
 . instances should be managed through sys_slist, see what has been done in subsys/net/l2/ethernet/arp.c
 . revise struct net_rpl_instance: k_delayed_work is an heavy object, 1 for each timer should be enough. See again arp.c
 . If possible (I don't know rpl myself so, just wet-finger idea): once sys_slist logic is in place, try using union on some of the attributes. Like done in struct arp_entry
 . it should not fill in the icmpv6 header by itself but use a relevant icmpv6 function for it (create one if necessary)

declutter using #8723 rules

**Comment by rveerama1** [comment]
Deprecating RPL, so closing this issue.

**Comment by tbursztyka** [comment]
@jfischer-phytec-iot Are you planning to maintain rpl code?

**Comment by jfischer-phytec-iot** [comment]
@tbursztyka at last keep it alive

**Comment by tbursztyka** [comment]
@jfischer-phytec-iot ok, because there is a lot of work in there. Not only cleaning up the code base I mean. A lot of features are still missing

**Comment by laperie** [comment]
Closing since we removed RPL
