### ISSUE TITLE
ARM: Use a unified K-config option for enabling (default) ARM MPU support

### ISSUE THREAD

**Issue by ioannisg** [zephyrproject-rtos/zephyr#8730]
Several ARM-based SOCs provide a K-config option to allow the user to choose whether to enable the ARM MPU. Example from Beetle:

```
config ARM_MPU_ENABLE
	bool "Enable MPU on ARM Beetle"
	depends on CPU_HAS_MPU
	select ARM_MPU
	help
	  Enable MPU support on ARM Beetle SoCs
```
This option is re-defined in several SOCs
- Beetle
- Nordic nRF52
- NXP i.MX RT
- STM32 SoCs,

however, it always does the same thing: selecting ARM_MPU.

There is a proposal (by @pizi-nordic ) to define a common option in arch/arm/core/Kconfig instead of multiple duplicate options in the respective SOC definition folders:

```
config ARM_MPU_ENABLE
	bool "Enable the use of ARM MPU"
	depends on CPU_HAS_MPU
	select ARM_MPU
	help
	  Enable MPU on ARM SoCs that implement the standard ARM MPU.
```
Does this K-config simplification make sense?

**Comment by ioannisg** [comment]
Copying @galak , @MaureenHelm , @erwango , @carlescufi

**Comment by pizi-nordic** [comment]
I see no difference between ARM_MPU_ENABLE and ARM_MPU in proposed scheme. Could we just make ARM_MPU visible to the developer?
