### ISSUE TITLE
All nRF drivers: migrate configuration from Kconfig to DTS

### ISSUE THREAD

**Issue by jakub-uC** [zephyrproject-rtos/zephyr#8758]
Move all possible configuration like: IRQ level or pinout,  from Kconfig to DTS.

This applies to:

- [x] UART
- [x] UARTE
- [x] TWI
- [x] SPI
- [x] I2C
- [x] clock_control
- [x] PWM (https://github.com/zephyrproject-rtos/zephyr/issues/11368)
- [x] ADC
- [x] GPIO
- [x] USB
- [ ] ieee802154
- [x] Watchdog
- [x] sensor/qdec
- [x] sensor/temp
- [ ] entropy
- [x] Cryptocell

**Comment by carlescufi** [comment]
This will be done by @Mierunski and @jarz-nordic

**Comment by carlescufi** [comment]
CC @galak

**Comment by jarz-nordic** [comment]
Serial driver in the PR: #8847

**Comment by jdemar** [comment]
Has the SPI driver been migrated or will be in for v1.13?

**Comment by jarz-nordic** [comment]
Hi,
SPI is not migrated yet, we aim for 1.14.

**Comment by carlescufi** [comment]
@jarz-nordic @Mierunski @anangl can you please check the table in the description and tick off what's needed?

**Comment by gamnes** [comment]
sensor/QDEC has already been migrated.

**Comment by carlescufi** [comment]
All peripherals with actual DT support have been ported now, closing.
