### ISSUE TITLE
tests/ztest/test/mock fails to complete on max10/nios2

### ISSUE THREAD

**Issue by inakypg** [zephyrproject-rtos/zephyr#8789]
Toolchain: ZEPHYR_GCC_VARIANT=zephyr

Commit ID cc5ae49133b48d4a7b3372f0bf22f942416debb7

```
***** Booting Zephyr OS 1.12.99 (delayed boot 3000ms) *****
Running test suite mock_framework_tests

===================================================================

starting test - parameter_tests

```
after 30s the test was canceled

**Comment by nashif** [comment]
@kumarvikash1 assign to some please..

**Comment by kumarvikash1** [comment]
@ajaykish , Can you please look into this test failure.

**Comment by kumarvikash1** [comment]
@nashif , somehow i am not able to assign to @ajaykish . Can you please assign to him.

**Comment by nashif** [comment]
outdates, no response
