### ISSUE TITLE
BLE "device name" characteristic of Generic Access Service is read only

### ISSUE THREAD

**Issue by lpasteau** [zephyrproject-rtos/zephyr#8829]
In "Generic Access Service", the characteristics "device name" can have the write permission optionnaly.  This feature is actually not available in BLE API, which registered mandatory services automatically in init step.
The name could also be stored in the flash in order to be restored correctly.

This issue is linked to https://github.com/zephyrproject-rtos/zephyr/issues/8357

**Comment by Vudentz** [comment]
Duplicated of https://github.com/zephyrproject-rtos/zephyr/issues/8357
