### ISSUE TITLE
Proposal - Simplifying the settings system

### ISSUE THREAD

**Issue by Laczen** [zephyrproject-rtos/zephyr#8854]
Hi Zephyr Developers and Users,

I have been studying the settings system and its use in btmesh. The settings system is a very nice idea to support persistent storage of settings or configuration variables. It is however heavily integrated with how the variables are stored and possibly this is limiting its full potential. From how the settings are used in bt I got the idea to simplify the settings solution and to expand its possibilities:

1. Make the settings part itself only provide the routines: settings_set, settings_commit and settings_export, these routines would call set, commit and export routines for each module or user application that would like to use settings. The settings_set would retrieve variables from storage. settings_commit would be called after settings_set to apply the settings. settings_export is for exporting the variables either to persistent storage or somewhere else.
2. Each module or user application would register its own routines by inserting them in a specific region in flash.

This is illustrated by the following code [settings.zip](https://github.com/zephyrproject-rtos/zephyr/files/2184478/settings.zip)

A second part of the system would be the persistent storage. This would provide the following routines to be called by the set and export routines of each module:
1. `load_var_by_name(char *name, void *data, size_t len)` and `load_var_by_id(int id, void *data, size_t len)` to load variables.
2. `save_var_by_name(char *name, void *data, size_t len)` and `save_var_by_id(int id, void *data, size_t len)` to save variables.
3. `del_var_by_name(char *name)` and `del_var_by_id(int id)` to delete variables.
4. `init_storage()` to initialize the storage.
The possibility to store by id is there to reduce flash use, store by name provides easier reading.

An advantage of decoupling the settings part from the persistent storage part is that it allows modules to use their own persistent storage solution, and/or to use their own persistent storage for a part of the variables while using the "generic" storage solution for another part. A major difference with the present settings solution is that the set routines are no longer called based upon a variable name but are calling the `load`routines themselves.

@jhedberg, @nvlsianpu, @carlescufi what is your opinion on this.

**Comment by Laczen** [comment]
Update [settings.zip](https://github.com/zephyrproject-rtos/zephyr/files/2188411/settings.zip). It contained some unnecessary comments in settings.h.

**Comment by carlescufi** [comment]
@Laczen why don't you send a PR instead of a .zip files? you can mark the PR as [DNM][RFC] and that would make it easier for people to see your code
