### ISSUE TITLE
GATT MTU Callback

### ISSUE THREAD

**Issue by bfrog** [zephyrproject-rtos/zephyr#8860]
It appears there's an automatic call to bt_gatt_exchange_mtu going on except there's no real way in my application to get that mtu value as the only callback available is the connect callback. The exchange for mtu hasn't happened at that point.

It would be nice to be able to register a callback to find out what the exchanged mtu was in my application so I can size my notifications appropriately.

**Comment by Vudentz** [comment]
You can read the MTU size at any point with use  of bt_gatt_get_mtu.
