### ISSUE TITLE
ARM MPU _arch_buffer_validate allowing reads to kernel memory

### ISSUE THREAD

**Issue by andrewboie** [zephyrproject-rtos/zephyr#8864]
Reproducible with this PR:
https://github.com/zephyrproject-rtos/zephyr/pull/8863
Run tests/kernel/mem_protect/syscalls on sam_e70_xplained.

The check to _arch_buffer_validate on a buffer defined with __kernel is not failing as it ought to be.

Not reproducible on frdm_k64f, so this seems specific to ARM MPU.

**Comment by andrewboie** [comment]
The MPU *is* protecting the memory if I call libc strlen on the same string, so this is definitely a problem with the validation function and not the MPU configuration itself.

**Comment by ioannisg** [comment]
@andrewboie submitted a PR that fixes this; the test you indicate is now successful after re-basing PR over #8868 .

**Comment by andrewboie** [comment]
thanks so much!!
