### ISSUE TITLE
Failed test: net.app.no-ipv6 (/tests/net/app/) on sam_e70_xplained

### ISSUE THREAD

**Issue by kumarvikash1** [zephyrproject-rtos/zephyr#8914]
Many networking tests are failing on same70 platform with " Illegal use of the EPSR" message.

Target :  sam_e70_xplained

Tests affected : All " net.app.no-ipv6"  & net.management.mgmt tests.

Failure message : 
***** USAGE FAULT *****
Executing thread ID (thread): 0x20400a0c
Faulting instruction address: 0x7f363bb6
Illegal use of the EPSR
Fatal fault in essential thread! Spinning...

**Comment by nashif** [comment]
net_app removed
