### ISSUE TITLE
[Coverity CID :187079] Integer handling issues in /subsys/net/l2/ethernet/gptp/gptp.c

### ISSUE THREAD

**Issue by mandarcthorat1** [zephyrproject-rtos/zephyr#8988]
Static code scan issues seen in File: /subsys/net/l2/ethernet/gptp/gptp.c
 Category: Integer handling issues
 Function: gptp_set_time_itv
 Component: Networking
 CID: 187079
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by mandarcthorat1** [comment]
The problem is detected again by latest coverity scan. Please have a look

**Comment by jukkar** [comment]
What is the coverity scan id for this new issue? The original one 187079 points to code that is already fixed.

**Comment by jukkar** [comment]
I wonder why coverity is reporting this now instead of immediately after the previous fix was reported. Anyway, investigating.
