### ISSUE TITLE
[Coverity CID :187077] Memory - corruptions in /samples/net/rpl_border_router/src/http.c

### ISSUE THREAD

**Issue by mandarcthorat1** [zephyrproject-rtos/zephyr#8990]
Static code scan issues seen in File: /samples/net/rpl_border_router/src/http.c
 Category: Memory - corruptions
 Function: start_http_server
 Component: Samples
 CID: 187077
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by rveerama1** [comment]
false-positive
