### ISSUE TITLE
[Coverity CID :187075] Memory - corruptions in /subsys/net/l2/ethernet/gptp/gptp_mi.c

### ISSUE THREAD

**Issue by mandarcthorat1** [zephyrproject-rtos/zephyr#8991]
Static code scan issues seen in File: /subsys/net/l2/ethernet/gptp/gptp_mi.c
 Category: Memory - corruptions
 Function: compare_priority_vectors
 Component: Networking
 CID: 187075
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by jukkar** [comment]
False positive

**Comment by mandarcthorat1** [comment]
Marked as intentional with following comment.
"This is intentional and there is enough space after root_system_id  that enables this."
