### ISSUE TITLE
[Coverity CID :187074] Incorrect expression in /samples/net/traffic_class/src/main.c

### ISSUE THREAD

**Issue by mandarcthorat1** [zephyrproject-rtos/zephyr#8992]
Static code scan issues seen in File: /samples/net/traffic_class/src/main.c
 Category: Incorrect expression
 Function: connect_udp
 Component: Samples
 CID: 187074
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by jukkar** [comment]
Already fixed
