### ISSUE TITLE
[Coverity CID :187071] Insecure data handling in /subsys/net/l2/ethernet/gptp/gptp_mi.c

### ISSUE THREAD

**Issue by mandarcthorat1** [zephyrproject-rtos/zephyr#8995]
Static code scan issues seen in File: /subsys/net/l2/ethernet/gptp/gptp_mi.c
 Category: Insecure data handling
 Function: copy_path_trace
 Component: Networking
 CID: 187071
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by jukkar** [comment]
False positive
