### ISSUE TITLE
[Coverity CID :187069] Memory - illegal accesses in /subsys/logging/log_msg.c

### ISSUE THREAD

**Issue by mandarcthorat1** [zephyrproject-rtos/zephyr#8997]
Static code scan issues seen in File: /subsys/logging/log_msg.c
 Category: Memory - illegal accesses
 Function: log_msg_hexdump_data_op
 Component: Other
 CID: 187069
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by nashif** [comment]
@nordic-krch can you please take a look?
