### ISSUE TITLE
[Coverity CID :187068] Memory - illegal accesses in /subsys/bluetooth/host/mesh/cfg_srv.c

### ISSUE THREAD

**Issue by mandarcthorat1** [zephyrproject-rtos/zephyr#8998]
Static code scan issues seen in File: /subsys/bluetooth/host/mesh/cfg_srv.c
 Category: Memory - illegal accesses
 Function: bt_mesh_cfg_reset
 Component: Bluetooth
 CID: 187068
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by jhedberg** [comment]
Marked as intentional in coverity
