### ISSUE TITLE
[Coverity CID :187067] Memory - corruptions in /subsys/logging/log_output.c

### ISSUE THREAD

**Issue by mandarcthorat1** [zephyrproject-rtos/zephyr#8999]
Static code scan issues seen in File: /subsys/logging/log_output.c
 Category: Memory - corruptions
 Function: std_print
 Component: Other
 CID: 187067
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by nashif** [comment]
@nordic-krch can you please take a look?

**Comment by nordic-krch** [comment]
@nashif, I have no access to the report (same in #8997)

**Comment by nashif** [comment]
@nordic-krch are you able to see the coverity report now? can you please take a look?
