### ISSUE TITLE
[Coverity CID :187065] Memory - corruptions in /subsys/net/l2/ethernet/gptp/gptp_mi.c

### ISSUE THREAD

**Issue by mandarcthorat1** [zephyrproject-rtos/zephyr#9000]
Static code scan issues seen in File: /subsys/net/l2/ethernet/gptp/gptp_mi.c
 Category: Memory - corruptions
 Function: copy_priority_vector
 Component: Networking
 CID: 187065
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by jukkar** [comment]
False positive
