### ISSUE TITLE
[Coverity CID :187064] Control flow issues in /subsys/bluetooth/host/mesh/cfg_srv.c

### ISSUE THREAD

**Issue by mandarcthorat1** [zephyrproject-rtos/zephyr#9001]
Static code scan issues seen in File: /subsys/bluetooth/host/mesh/cfg_srv.c
 Category: Control flow issues
 Function: bt_mesh_label_uuid_get
 Component: Bluetooth
 CID: 187064
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by jhedberg** [comment]
Marked as false positive in coverity (see the the issue there for a more detailed explanation)
