### ISSUE TITLE
[Coverity CID :187062] Incorrect expression in /samples/net/sockets/echo_server/src/udp.c

### ISSUE THREAD

**Issue by mandarcthorat1** [zephyrproject-rtos/zephyr#9003]
Static code scan issues seen in File: /samples/net/sockets/echo_server/src/udp.c
 Category: Incorrect expression
 Function: process_udp
 Component: Samples
 CID: 187062
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by rlubos** [comment]
This one looks like a false-positive to me. The code pointed by Coverity is valid and is not a copy paste.

**Comment by jukkar** [comment]
False positive.
