### ISSUE TITLE
Create driver for the MMA8451Q accelerometer sensor on FRDM-KL25Z

### ISSUE THREAD

**Issue by larsgk** [zephyrproject-rtos/zephyr#9006]
Inspiration:  https://os.mbed.com/users/emilmont/code/MMA8451Q/file/c4d879a39775/MMA8451Q.cpp/

I might look into this myself.  Do I need to sign an online NDA/code collab doc?

**Comment by MaureenHelm** [comment]
> Do I need to sign an online NDA/code collab doc?

No. http://docs.zephyrproject.org/contribute/contribute_guidelines.html

**Comment by larsgk** [comment]
(working on this + a sample app to join it at the moment)
