### ISSUE TITLE
net/sockets/echo_async crashes after several connections (qemu_x86)

### ISSUE THREAD

**Issue by rlubos** [zephyrproject-rtos/zephyr#9032]
I've experienced an `echo_async` sample crash when I was playing with it on qemu_x86. Actually, it's pretty simple to reproduce, just connect/disconnect a few times with telnet (for me two times is enough). Here's the log:
```
***** Booting Zephyr OS v1.12.0-880-g86b5edc4d *****
Asynchronous TCP echo server waits for connections on port 4242...
Connection #0 from 192.0.2.2 fd=4198848
poll error: 4
Connection #1 from 192.0.2.2 fd=4198848
poll error: 4
***** CPU Page Fault (error code 0x00000000)
Supervisor thread read address 0x00000000
PDE: 0x025 Present, Read-only, User, Execute Enabled
PTE: 0x00 Non-present, Read-only, Supervisor, Execute Enabled
Current thread ID = 0x00402180
eax: 0x00000000, ebx: 0x00401230, ecx: 0x0041521c, edx: 0x0041527c
esi: 0x00000001, edi: 0x0041527c, ebp: 0x0041520c, esp: 0x004151f8
eflags: 0x00000006 cs: 0x0008
call trace:
eip: 0x00015742
     0x00015940 (0x293)
     0x000056fd (0x415254)
     0x00003c5c (0x400340)
     0x000128ed (0x4153e8)
     0x00003e03 (0x0)
Fatal fault in essential thread! Spinning...
```

Didn't have too much time to dive in, but the crash itself takes place within `k_poll` function. Yet it looks that the problem here is that sockets are not being closed. Not sure about the error returned by the `poll` function (`EINTR` doesn't look too scary), but the fact that sockets are not closed is disturbing. Perhaps `net_context` for whatever reason is not notyfing the socket shim about connection being closed, so in result `recv` and `close` are not called?

Nothing fancy in wireshark logs, just two opened and closed connections:
![image](https://user-images.githubusercontent.com/22167799/42949606-67976a40-8b72-11e8-8dc9-d459bf4da051.png)

**Comment by rlubos** [comment]
Moreover, it looks that second `accept` returned `net_context` pointer (socket id) to the same context as the first one, even though it was still in use by the application...
So I guess it might be yet another consequence of #8008.

**Comment by nashif** [comment]
@pfalcon ping

**Comment by pfalcon** [comment]
Ok, I went on vacation and completely forgot about this issue. Hope to get to it soon.

**Comment by pfalcon** [comment]
Reproduced with 469bd39b82cd20d732a4e5032dc8b7e895614125. Still reproduced with zephyr-v1.12.0 ;-(. Still with zephyr-v1.11.0 ;-(. Still with zephyr-v1.10.0 ;-(. Ok with zephyr-v1.9.0 (that's before cmake, old good days!).

Yeah, so that's pretty sucky a picture ;-(. Blame cmake I guess? ;-)

**Comment by pfalcon** [comment]
Ok, this bisects to 48fadfe6232a4520f13da6c54a8dd204f8c5ece2. And it's dejavu and overall nonsense - of course I was in the middle of discussion leading to that change (and ones around it). What would be the explanation of that? That blocking socket handling was updated/tested after that change, but poll() implementation wasn't?

**Comment by pfalcon** [comment]
"poll error: 4" is EINTR of course.
