### ISSUE TITLE
bluetooth ：BR ：The sample is incomplete

### ISSUE THREAD

**Issue by hongshui3000** [zephyrproject-rtos/zephyr#9070]
handsfree ： The phone cannot search for this service。I can only verify my code（controller） with bluez？
I have not found examples of SDP and RFCOMM and A2DP related.

**Comment by jhedberg** [comment]
We don't really have anyone actively working on BR/EDR support, so everything that's in the tree should be considered experimental. However, I welcome any contributions to make the BR/EDR stack and related samples more complete!

**Comment by carlescufi** [comment]
Closing this since there are no plans for adding additional BR/EDR support
