### ISSUE TITLE
doc: correct SMP server sample imgtool.py sign usage

### ISSUE THREAD

**Issue by Flo3561** [zephyrproject-rtos/zephyr#9076]
The current (v12) SMP server sample doc (http://docs.zephyrproject.org/samples/subsys/mgmt/mcumgr/smp_svr/README.html) notes a wrong usage of the "imtool.py sign" tool. There is no "--included-header" option but the "--slot-size" option with the corresponding slot-size is required.

**Comment by carlescufi** [comment]
Already fixed
