### ISSUE TITLE
driver: CAN interface should be compatible with CAN-FD interface

### ISSUE THREAD

**Issue by walter-xie** [zephyrproject-rtos/zephyr#9087]
FYI: https://www.can-cia.org/can-knowledge/can/can-fd/

**Comment by alexanderwachter** [comment]
I dont't think so.
- CAN-FD is not compatible with CAN.
The size of the data buffer is 64 not 8 bytes (waste of memory when allocating message buffers).
- The send function would need to have a parameter defining the data rate which is confusing when only dealing with CAN.
- There is no CAN-FD controller available in any controller supported by zephyr.

@walter-xie do you need CAN-FD for a project or product up to date?

**Comment by alexanderwachter** [comment]
It is compatible now. CAN-FD drivers are wip
