### ISSUE TITLE
Out of tree BSP

### ISSUE THREAD

**Issue by nashif** [zephyrproject-rtos/zephyr#9172]
Zephyr shall support out-of-tree BSPs (Board definition packages) with BSPs including board, soc, driver definitions and code. A BSP shall be able to have its own configuration system that integrates with the overall Zephyr configuration system.

The following shall be supported with out-of-tree feature:

- Independent applications and BSP repositories
- Ability to build applications by referencing both Zephyr and BSP
- Sanitycheck can run Zephyr tests on BSP
- Sanitycheck can test out-of-tree applications.

![image](https://user-images.githubusercontent.com/180017/43398483-3307b912-93d6-11e8-9d4f-68c2527806cd.png)

We already have out of tree board support, but that is done right now within an application and only supports boards. We should have the same thing for SoCs and drivers and should be able to build multiple application using this out-of-tree BSP.

**Comment by nashif** [comment]
Perquisite of this is 34438

**Comment by aescolar** [comment]
Having also support for out of tree archs would be very welcome for us.

**Comment by nashif** [comment]
> Having also support for out of tree archs would be very welcome for us.
> (even if it would be limited to build, without sanitycheck support)

you need to open a new feature item for that. This is only for BSP

**Comment by aescolar** [comment]
> you need to open a new feature item for that. This is only for BSP

It is already done :)
