### ISSUE TITLE
cmake: kconfig: menuconfig is not writing zephyr/.config

### ISSUE THREAD

**Issue by ramonhpr** [zephyrproject-rtos/zephyr#9270]
Hello,

When I fetch the repository yesterday I couldn't select the packages in menuconfig anymore.

I think this could be related from commit hash: `5402662dd96112fc69d304175f2cf453f1b203da`
Because it is not writing in `zephyr/.config` file anymore.

Thanks in advance.

**Comment by ulfalizer** [comment]
@ramonhpr 
See if https://github.com/zephyrproject-rtos/zephyr/pull/9274 fixes it. Sorry about that!

**Comment by ramonhpr** [comment]
Yes. It is fixed!
Thanks @ulfalizer
