### ISSUE TITLE
net_buf: fix void * vs. u8_t * inconsistencies

### ISSUE THREAD

**Issue by mike-scott** [zephyrproject-rtos/zephyr#9283]
The net_buf APIs take a mix of `void * `and `u8_t *` when passing buffer pointers.

We should consolidate on 1 or the other.

**Comment by pfalcon** [comment]
IMHO, that should be void*, so we could pass pointers to variables of different sizes without verbose casts. I'll be happy to +1 such a patch.

**Comment by mped-oticon** [comment]
Related to #9879.
