### ISSUE TITLE
[Coverity CID :187323] Control flow issues in /subsys/net/ip/net_if.c

### ISSUE THREAD

**Issue by mandarcthorat1** [zephyrproject-rtos/zephyr#9292]
Static code scan issues seen in File: /subsys/net/ip/net_if.c
 Category: Control flow issues
 Function: net_if_set_promisc
 Component: Networking
 CID: 187323
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by jukkar** [comment]
False positive
