### ISSUE TITLE
[Coverity CID :187322] Incorrect expression in /tests/posix/pthread_key/src/pthread_key.c

### ISSUE THREAD

**Issue by mandarcthorat1** [zephyrproject-rtos/zephyr#9293]
Static code scan issues seen in File: /tests/posix/pthread_key/src/pthread_key.c
 Category: Incorrect expression
 Function: thread_top
 Component: Tests
 CID: 187322
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by nniranjhana** [comment]
#9085 which fixes this has been merged, hence closing this issue.
