### ISSUE TITLE
[Coverity CID :187318] Error handling issues in /tests/posix/pthread_key/src/pthread_key.c

### ISSUE THREAD

**Issue by mandarcthorat1** [zephyrproject-rtos/zephyr#9297]
Static code scan issues seen in File: /tests/posix/pthread_key/src/pthread_key.c
 Category: Error handling issues
 Function: test_pthread_key
 Component: Tests
 CID: 187318
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by nniranjhana** [comment]
#9085 which fixes this issue has been merged, hence closing this issue.
