### ISSUE TITLE
samples: net: echo_client/echo_server does not work with IPv4 qemu_x86

### ISSUE THREAD

**Issue by rlubos** [zephyrproject-rtos/zephyr#9348]
It looks like `echo_server`/`echo_client` and probably other samples that use IPv4 does not work on `qemu_x86`. Bisecting showed up that https://github.com/zephyrproject-rtos/zephyr/commit/bab35512f87b3bc9804a3b90d489c911701cfae8 broke them. It kinda makes sense, because IPv6 communication works, while IPv4 is broken.

I'm not sure what exactly is wrong in ARP as I'm not familiar with the implementation, but perhaps someone more familiar with it could take a look.

**Comment by rlubos** [comment]
CC @jukkar

**Comment by jukkar** [comment]
Thanks for a report, I will look into it.
