### ISSUE TITLE
./loop-socat.sh not running

### ISSUE THREAD

**Issue by electrocraz** [zephyrproject-rtos/zephyr#9396]
There is no response to ./loop-socat.sh in net-tools.
Please help as soon as possible.

**Comment by jukkar** [comment]
It works ok for me. Can you elaborate a bit more what kind of symptoms your have?
What happens if you run `socat PTY,link=/tmp/slip.dev UNIX-LISTEN:/tmp/slip.sock` manually?

**Comment by jukkar** [comment]
This works for me and no response from reporter -> closing.

**Comment by pfalcon** [comment]
Indeed, I think there's a confusion. There should be no output (if that's meant by "response") from loop-socat.sh, it's kind of daemon. Just follow instructions in http://docs.zephyrproject.org/subsystems/networking/qemu_setup.html, and you should be fine. If not, submit another ticket with step by step description of what you do, and exact output you get. Thanks.
