### ISSUE TITLE
samples/drivers/watchdog fails on frdm_k64f

### ISSUE THREAD

**Issue by spoorthik** [zephyrproject-rtos/zephyr#9402]
Execution log:

```
Start watchdog test
***** BUS FAULT *****
  Instruction bus error
  NXP MPU error, port 4
    Mode: Supervisor, Instruction Address: 0x9f38018
    Type: Read, Master: 0, Regions: 0xc000
***** Hardware exception *****
Current thread ID = 0x200000d4
Faulting instruction address = 0x9f38018
Fatal fault in essential thread! Spinning...
```

Board: freedom_k64f
Architecture: ARM

Latest commit: d71a1dfefd3ea0b7cefa3a3d1958a9238b5b1861

**Comment by MaureenHelm** [comment]
This sample needs to be updated to the new watchdog API. See #8215 

@kl-cruz Would it be possible to update the sample for 1.13?

**Comment by kl-cruz** [comment]
I'll try to update it today, but I do not want to promise anything. There is "Feature Merge Window Close" tomorrow

**Comment by nashif** [comment]
this is now fixed, however quark is still broken, but that could be the driver.
