### ISSUE TITLE
Overriding `LOG_LEVEL` could crash the firmware

### ISSUE THREAD

**Issue by Olivier-ProGlove** [zephyrproject-rtos/zephyr#9432]
Here is a test based on `sample/hello_world` that crashes:

```
#include <zephyr.h>

#define LOG_MODULE_NAME main
#define LOG_LEVEL 0
#include <logging/log.h>
LOG_MODULE_REGISTER();

void main(void)
{
	LOG_DBG("Hello World!");
}
```

with `prj.conf`:

```
# Enable console
CONFIG_CONSOLE=y

# Enabling logging
CONFIG_LOG=y
CONFIG_LOG_RUNTIME_FILTERING=y

# Override lowest log level to DEBUG(=4)
CONFIG_LOG_OVERRIDE_LEVEL=4
```

- Commenting `CONFIG_LOG_OVERRIDE_LEVEL=4` does not make the firmware crash
- Commenting `CONFIG_LOG_RUNTIME_FILTERING=y` does not make the firmware crash
- Commenting `#define LOG_LEVEL 0` does not make the firmware crash

**Comment by dleach02** [comment]
I tried to reproduce this but was not able to. Can @Olivier-ProGlove, retest and put the exact code/prj config values that crashes?

**Comment by nashif** [comment]
not able to reproduce
