### ISSUE TITLE
Enable mpu on lpc54114

### ISSUE THREAD

**Issue by MaureenHelm** [zephyrproject-rtos/zephyr#9482]

**Comment by Jeepgoing** [comment]
hello @MaureenHelm, i am know using lpc54114, when i write something to flash(on chip), error code as below:
`***** MPU FAULT *****
  Instruction Access Violation
***** Hardware exception *****
Current thread ID = 0x02010320
Faulting instruction address = 0xfffffffe
Fatal fault in ISR! Spinning...`

so, could you give me some advises about this, thanks.

**Comment by MaureenHelm** [comment]
Hi @Jeepgoing. I'm surprised to see this fault since I haven't enabled the MPU on this platform yet. Did you enable it in some out-of-tree code?

**Comment by Jeepgoing** [comment]
Hi @MaureenHelm. I'm using lpc54102 Soc, both M4 and M0 cores are running on flash ,and I have add all things by myself, including flash driver
`soc_flash_lpc54xxx.c`,  I havn't add anything about MPU, I don't know why occur this fault, I operating flash on M0 core, is this fault caused by this operation?

**Comment by MaureenHelm** [comment]
I don't know why this would occur with the MPU disabled. Can you share your code?

@stanislav-poboril Any ideas?

**Comment by Jeepgoing** [comment]
@MaureenHelm, I have not commit any code before, but i think i will try to do this. i will arrange my code  and commit as soon as possible

**Comment by Jeepgoing** [comment]
`/*
 * Copyright (c) 2018 Noitom
 *
 * SPDX-License-Identifier: Apache-2.0
 */
#include <kernel.h>
#include <device.h>
#include <string.h>
#include <flash.h>
#include <errno.h>
#include <init.h>
#include <soc.h>

#include "fsl_common.h"
#include "fsl_flashiap.h"

#define LPC_PAGE_SIZE FSL_FEATURE_SYSCON_FLASH_PAGE_SIZE_BYTES
#define LPC_SECTOR_SIZE FSL_FEATURE_SYSCON_FLASH_SECTOR_SIZE_BYTES 

#define LPC_FLASH_CLOCK	CONFIG_SYS_CLOCK_HW_CYCLES_PER_SEC

struct flash_lpc54xxx_data {
	struct k_sem write_lock;
};

static int flash_lpc54xxx_erase(struct device *dev, off_t offset, size_t len)
{
	struct flash_lpc54xxx_data *flash_data = dev->driver_data;
	u32_t start_sector,end_sector;
	int key;
	status_t rc;
	u32_t addr = CONFIG_FLASH_BASE_ADDRESS + offset;

	if (k_sem_take(&flash_data->write_lock, K_NO_WAIT)) {
		return -EACCES;
	}

	start_sector = addr/LPC_SECTOR_SIZE; 
	end_sector = (addr + len)/LPC_SECTOR_SIZE;
    if (len%LPC_SECTOR_SIZE == 0) {
        if (len > 0)
            end_sector -= 1;
    }

	key = irq_lock();
	
    rc = FLASHIAP_PrepareSectorForWrite(start_sector, end_sector);
	if(rc != kStatus_FLASHIAP_Success){
		return -EIO; 
	}

	rc = FLASHIAP_EraseSector(start_sector, end_sector, LPC_FLASH_CLOCK);
	if(rc != kStatus_FLASHIAP_Success){
		return -EIO; 
	}

	irq_unlock(key);

	k_sem_give(&flash_data->write_lock);

	return 0;
}

static int flash_lpc54xxx_read(struct device *dev, off_t offset,
				void *data, size_t len)
{
	u32_t addr;

	addr = CONFIG_FLASH_BASE_ADDRESS + offset;

	memcpy(data, (void *) addr, len);
	
	return 0;
}

static int flash_lpc54xxx_write(struct device *dev, off_t offset,
				const void *data, size_t len)
{
	struct flash_lpc54xxx_data *flash_data = dev->driver_data;
	u32_t start_sector,end_sector;
	int key = -1;
	status_t rc;
	u32_t addr, copy_addr, start_len, total_len;
    u32_t datalen = 0;
    int ret;
	u8_t *pdata = (u8_t *)data;

	if((0 == len) || (NULL == data)){
		return -EINVAL;
	}

	if (k_sem_take(&flash_data->write_lock, K_NO_WAIT)) {
	    return -EACCES;
	}

	addr = CONFIG_FLASH_BASE_ADDRESS + offset;
    start_len = addr%LPC_PAGE_SIZE;
    copy_addr = addr - start_len;
    start_sector = addr/LPC_SECTOR_SIZE; 
	end_sector = (addr + len - 1)/LPC_SECTOR_SIZE;

    total_len = start_len + len;
    datalen = (total_len / LPC_PAGE_SIZE) * LPC_PAGE_SIZE;
    if (total_len % LPC_PAGE_SIZE)
        datalen += LPC_PAGE_SIZE;

    u8_t ptmp[datalen + 4];

    memset(ptmp, 0xFF, datalen);

	key = irq_lock();

    memcpy(ptmp, (void *)copy_addr, start_len);
    memcpy(&ptmp[start_len], pdata, len);
	
    rc = FLASHIAP_PrepareSectorForWrite(start_sector, end_sector);
	if(rc != kStatus_FLASHIAP_Success){
		ret = -EIO;
		goto err;
	}

    rc = FLASHIAP_CopyRamToFlash(copy_addr, (uint32_t *)ptmp, datalen, LPC_FLASH_CLOCK);
    if(rc != kStatus_FLASHIAP_Success){
        ret = -EIO;
        goto err;
    }

    rc = FLASHIAP_Compare(copy_addr, (uint32_t *)ptmp,datalen);
    if(rc != kStatus_FLASHIAP_Success){
        ret = -EIO;
        goto err;
    }

    irq_unlock(key);	

    k_sem_give(&flash_data->write_lock);

    return 0;

err:

	if(key != -1){
		irq_unlock(key);
	}

	k_sem_give(&flash_data->write_lock);
	
	return ret;
}

static int flash_lpc54xxx_write_protection(struct device *dev, bool enable)
{
	struct flash_lpc54xxx_data *flash_data = dev->driver_data;
	int rc = 0;

	if (enable) {
		rc = k_sem_take(&flash_data->write_lock, K_FOREVER);
	} else {
		k_sem_give(&flash_data->write_lock);
	}

	return rc;
}

#if defined(CONFIG_FLASH_PAGE_LAYOUT)
static const struct flash_pages_layout dev_layout = {
	.pages_count = KB(CONFIG_FLASH_SIZE) / LPC_SECTOR_SIZE,
	.pages_size = LPC_SECTOR_SIZE,
};

static void flash_lpc54xxx_pages_layout(struct device *dev,
									const struct flash_pages_layout **layout,
									size_t *layout_size)
{
	*layout = &dev_layout;
	*layout_size = 1;
}
#endif /* CONFIG_FLASH_PAGE_LAYOUT */

static struct flash_lpc54xxx_data flash_data;

static const struct flash_driver_api flash_mcux_api = {
	.write_protection = flash_lpc54xxx_write_protection,
	.erase = flash_lpc54xxx_erase,
	.write = flash_lpc54xxx_write,
	.read = flash_lpc54xxx_read,
#if defined(CONFIG_FLASH_PAGE_LAYOUT)
	.page_layout = flash_lpc54xxx_pages_layout,
#endif
	.write_block_size = 1,
};

static int flash_lpc54xxx_init(struct device *dev)
{
	struct flash_lpc54xxx_data *data = dev->driver_data;

	k_sem_init(&data->write_lock, 0, 1);

	return 0;
}

DEVICE_AND_API_INIT(flash_lpc54xxx, FLASH_DEV_NAME,
			flash_lpc54xxx_init, &flash_data, NULL, POST_KERNEL,
			CONFIG_KERNEL_INIT_PRIORITY_DEVICE, &flash_mcux_api);

`

**Comment by stanislav-poboril** [comment]
The "Instruction Access Violation" exception (IACCVIOL bit set in SCB's MMFSR register) can happen even with MPU not present or disabled. Looks like an attempt to fetch/execute instruction from an invalid address or a non-executable memory region (0xfffffffe).

http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.dui0552a/Cihcfefj.html
http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.dui0553a/CIHGEIID.html

**Comment by Jeepgoing** [comment]
thanks, @MaureenHelm @stanislav-poboril , i will check my code.
