### ISSUE TITLE
soc: exx32: Use the same soc.c for all Silabs exx32 mcus

### ISSUE THREAD

**Issue by chrta** [zephyrproject-rtos/zephyr#9520]
The change from #9473 should be applied for all Silicon Labs EFM32 and EFR32 MCUs.
The differentiation between the MCUs is handled in the HAL from Silabs, that is used.
So all EXX32 MCUs should use the same soc.c file.

**Comment by pfalcon** [comment]
Assigning to @mnkp as the author of https://github.com/zephyrproject-rtos/zephyr/pull/9473

**Comment by mnkp** [comment]
I don't have necessary hardware to test the change on all supported SiLabs SoCs. @chrta promised that he will have a look at the issue when he has some time. I'm removing myself from Assigned list.
