### ISSUE TITLE
broken callback handling in nrfx gpio driver

### ISSUE THREAD

**Issue by pdunaj** [zephyrproject-rtos/zephyr#9535]
In `drivers/gpio/gpio_nrfx.c` function `gpiote_pin_int_cfg` calls `gpiote_channel_alloc` and takes its return value as its own.
The problem is that `gpiote_channel_alloc` (if successful) returns the channel number. In this case value is interpreted as an error.

I guess the best fix is to return 0 in `gpiote_channel_alloc` every time channel is found.

The problem is that new gpio driver seems have more bugs. When I disable callbacks while in callback, I receive another interrupt. It was working correctly and disabling the callback as expected in the old driver.

**Comment by pdunaj** [comment]
Fix is ready - I will try to push it in few minutes

**Comment by pdunaj** [comment]
@carlescufi Can I push the change to our fork or should it go to main zephyr repo? If it is the second case, will you pull it to our fork from there?

**Comment by carlescufi** [comment]
@pdunaj let's fix it upstream
