### ISSUE TITLE
console: missing kernel.h include in header

### ISSUE THREAD

**Issue by lemrey** [zephyrproject-rtos/zephyr#9536]
console.h requires k_fifo but kernel.h is not included.
CC @pfalcon.

**Comment by pfalcon** [comment]
@lemrey : How did you hit it? (Generally, we should back such things with regression tests. Maybe we'll be too lazy to write one, but we should not be lazy to discuss *how* to write one ;-).

**Comment by lemrey** [comment]
I hit a compiler warning; perhaps it is possible to reproduce by including console.h before kernel.h:
`warning: ‘struct k_fifo’ declared inside parameter list will not be visible outside of this definition or declaration`

**Comment by pfalcon** [comment]
Thanks. Fairly speaking, I had an idea that all Zephyr apps should start with `#include <zephyr.h>`. Dunno where I got the from though, probably because all in-tree samples do that. Anyway, it's an easy fix, posted as https://github.com/zephyrproject-rtos/zephyr/pull/9541
