### ISSUE TITLE
Unclear definition of CONFIG_IS_BOOTLOADER

### ISSUE THREAD

**Issue by JoeHut** [zephyrproject-rtos/zephyr#9566]
The ``CONFIG_IS_BOOTLOADER`` option was apparently introduced by STM for disabling vector relocation on Cortex-M0. The naming or its usage is misleading since the config's help says "Zephyr will act as a bootloader to execute" but the config is selected in board files. What I would expect that this option is only used in applications that act as a bootloader such as MCUboot.

**Comment by nvlsianpu** [comment]
CONFIG_IS_BOOTLOADER used to enable vector relocation mechanism which is specific for cortex-m0 stm32f0 family. Parallel to this feature some time ago we implemented generic cortex-m0 vector relocation (https://github.com/zephyrproject-rtos/zephyr/pull/4536/files). What I can suggest is to rename this keyword to something more suitable. I think feature enabled by this keyword is something vendor specific.

**Comment by nvlsianpu** [comment]
cc @erwango If you can answer in your convenience or redirect to someone (no rush).

**Comment by b0661** [comment]
CONFIG_IS_BOOTLOADER is used for the situation where you **do not need vector relocation** for the cortex-m0.

**Comment by SebastianBoe** [comment]
This issue relates to: https://github.com/zephyrproject-rtos/zephyr/issues/6180

**Comment by nvlsianpu** [comment]
> CONFIG_IS_BOOTLOADER is used for the situation where you do not need vector relocation for the cortex-m0.

Ach yes, you are right.

**Comment by erwango** [comment]
CONFIG_IS_BOOTLOADER was introduced by 21628d41d02115090208b42739ff5448c801900a so not introduced by or for STM.
Since authors do not contribute to zephyr anymore, maybe @andyross would be the right person for this point?

**Comment by erwango** [comment]
@JoeHut Is this issue still valid ?

**Comment by JoeHut** [comment]
We worked around it and I am currently not up to date with the 2.x branches since we stayed with the LTS. If noone else complains I guess you can close it.

**Comment by erwango** [comment]
Txs @JoeHut , I'm closing
