### ISSUE TITLE
Windows installation of SDK needs 'just works' installer

### ISSUE THREAD

**Issue by smartyw** [zephyrproject-rtos/zephyr#9578]
Hi

I ran a Zephyr coding workshop last night. Attendees were supposed to arrive with their laptops with the Zephyr SDK already installed and Hello World building without errors. 66% of people had failed to get the SDK installed and working and we then spent a good part of the class trying to solve the various problems. Some were never solved so people had to give up on any hands-on participation.

I had Windows, Mac and Linux users in the class. Most people with problems were Windows users. One was a Mac user.

I think the Mac user's problem was of his own making so we can ignore this.

The Windows users had got to various points, with various issues including:

1. No CMAKE_CXX_COMPILER could be found.

(user had not run zephyr-env.cmd)

2.   if given arguments:

    "STREQUAL" "gccarmemb"

  Unknown arguments specified

ZEPHYR_TOOLCHAIN_VARIANT and GNUARMEMB_TOOLCHAIN_PATH were not defined. User had set these up as Windows system variables but not exited and reopened a cmd shell.

3. Assertion failed: The toolchain is unable to build a dummy C file. 

Compiler: CMAKE_C_COMPILER-NOTFOUND 

Not sure about this one. User had environment variable GNUARMEMB_TOOLCHAIN_PATH=c:\gnuarmemb and that is the correct path for the ARM toolchain. 

I think a proper Windows installer (setup.exe) is needed. This should automate all steps and update environment variables and paths as required. Manually installing the various parts is error prone. Yes, these are generally user errors, failure to follow the instructions properly but that's an inevitable outcome with people!

If a proper installer is not possible, one small improvement would be to tell people to set proper Windows System Variables via the Control Panel rather than running a shell script (zephyr-env.cmd) every time and having the variables vanish every time a shell is closed.

That's it!

Martin

AKA @bluetooth-mdw

**Comment by smartyw** [comment]
Recreated the last issue in my initial description and solved it by deleting everything in the build/ folder.

**Comment by bluetooth-mdw** [comment]
I created a video to (hopefully) help Windows users: https://www.youtube.com/watch?v=SjHpqK5jmVk&feature=youtu.be 

AKA @smartyw

**Comment by arturorosete0** [comment]
> Recreated the last issue in my initial description and solved it by deleting everything in the build/ folder.

This worked for me. All the system variables were setted correctly. My error was the following:
![image](https://user-images.githubusercontent.com/19495617/55198777-106f4400-517d-11e9-9303-e782f0b5719e.png)

**Comment by stephanosio** [comment]
This can be considered fixed with the release of new multi-platform Zephyr SDK:
https://github.com/zephyrproject-rtos/sdk-ng/releases/tag/v0.14.0
