### ISSUE TITLE
tests/subsys/logging/log_core fails on ESP32 with no console output

### ISSUE THREAD

**Issue by inakypg** [zephyrproject-rtos/zephyr#9596]
commit v1.13.0-rc1-4-g0d0b221efa

the testcase produces no console output, so we cannot tell what is going on. This was built with CONFIG_BOOT_DELAY=1000.

**Comment by henrikbrixandersen** [comment]
This is likely the same cause as #10628 and #10915.

**Comment by ExtremeGTX** [comment]
#### an update:
- `samples/subsys/logging/logger/` this is not even working in `qemu_xtensa` so i think it is architecture support problem
- On `esp32` got `LoadStoreError` then `IllegalInstruction`
- will attach gdb to qemu_xtensa and share more info here

**Comment by nashif** [comment]
stale
