### ISSUE TITLE
BLE mesh on ESP32

### ISSUE THREAD

**Issue by thanhhaiittalk** [zephyrproject-rtos/zephyr#9613]
I'm trying to use BLE mesh with ESP32, can anyone confirm if it works ?

**Comment by nashif** [comment]
this is not supported yet.

**Comment by thanhhaiittalk** [comment]
Thanks for your help nashif.

**Comment by tunted** [comment]
So @nashif, will it be supported in near future? I also wonder if esp32 could run ble mesh protocol with its limited resource.

**Comment by XXXXzzzz000** [comment]
＃8830 this is my question. wifi and bluetooth not be supported,because these parts are not open source.they will open wifi source in the future,so we need wait.
