### ISSUE TITLE
Add support for the FRDM-KL28Z board

### ISSUE THREAD

**Issue by larsgk** [zephyrproject-rtos/zephyr#9626]
The FRDM-KL28Z is very like the already supported FRDM-KL25Z with the addition of some of the sensors available on the Hexiwear unit.

It would be a nice addition to be able to utilize a board with more sensors than FRDM-KL25Z at a similar price point.

(I'll give it a go)

**Comment by nashif** [comment]
closing, if you have this, just submit as a PR.
