### ISSUE TITLE
nRF52x USB device stack support

### ISSUE THREAD

**Issue by RonAmihai** [zephyrproject-rtos/zephyr#9628]
I want to integrate nRF52840-PCA10056 board with WebUSB. 
Does nRF52x USB device stack is supported by Zephyr?

**Comment by RonAmihai** [comment]
Any news?

**Comment by carlescufi** [comment]
@RonAmihai yes, we are about to release a version of nrfx with USB support on it. After that, we will push a PR that makes use of it. Should all happen in the next few days.
