### ISSUE TITLE
[Coverity CID :187824] Integer handling issues in /lib/cmsis_rtos_v1/cmsis_thread.c

### ISSUE THREAD

**Issue by mandarcthorat1** [zephyrproject-rtos/zephyr#9637]
Static code scan issues seen in File: /lib/cmsis_rtos_v1/cmsis_thread.c
 Category: Integer handling issues
 Function: osThreadCreate
 Component: Other
 CID: 187824
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by rgundi** [comment]
Fixed in #9655.
