### ISSUE TITLE
[Coverity CID :187820] Memory - illegal accesses in /subsys/bluetooth/host/hci_core.c

### ISSUE THREAD

**Issue by mandarcthorat1** [zephyrproject-rtos/zephyr#9641]
Static code scan issues seen in File: /subsys/bluetooth/host/hci_core.c
 Category: Memory - illegal accesses
 Function: bt_id_reset
 Component: Bluetooth
 CID: 187820
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by jhedberg** [comment]
Please check Coverity status before filing issues. This was already flagged as a false-positive.
