### ISSUE TITLE
[Coverity CID :187819] Memory - illegal accesses in /subsys/logging/log_msg.c

### ISSUE THREAD

**Issue by mandarcthorat1** [zephyrproject-rtos/zephyr#9642]
Static code scan issues seen in File: /subsys/logging/log_msg.c
 Category: Memory - illegal accesses
 Function: log_msg_hexdump_data_op
 Component: Other
 CID: 187819
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by ceolin** [comment]
fixed in 9624593a0ca128faa4465796c4e456a5674a964f
Forgot to check/close it.

**Comment by ceolin** [comment]
actually realize that I referenced the wrong coverity ID in that commit. My bad.

**Comment by nashif** [comment]
fixed already in the above commit.
