### ISSUE TITLE
LwM2M: Writeable parameter /3311/0/5850 doesn't persist write

### ISSUE THREAD

**Issue by therealprof** [zephyrproject-rtos/zephyr#9667]
I just noticed that the writable parameter /3311/0/5850 to turn on a LED on a board can be written and changes LED state just fine but when read it is always a boolean `true`.

**Comment by mike-scott** [comment]
@therealprof how was support for object 3311 setup?  Did you do a CREATE and then WRITE and then READ?  Or did you have a sample that created the initial object and setup the backing?  IE: without a variable buffer for /3311/0/5850, I'm not sure the boolean value would be stored.

**Comment by therealprof** [comment]
@mike-scott Sorry, forgot to mention that this is with the `samples/net/lwm2m_client` (as usual).

**Comment by mike-scott** [comment]
@therealprof thanks, I'll debug

**Comment by mike-scott** [comment]
@therealprof Having a hard time reproducing this.  I tested this using both Leshan and Wakaama as LwM2M Servers.  Here's the output from a Wakaama session (NOTE: I had to edit part of the Wakaama source to allow creation of the /3311 object)   Also, not sure why Wakaama was showing a NOT_FOUND when I used the create command.  It's very "hard-coded" in this regard.  Leshan worked perfectly.

```
New client #0 registered.
Client #0:
	name: "qemu_x86"
	binding: "Not specified"
	lifetime: 30 sec
	objects: /1/0, /3/0, /5/0, /3303/0, /3311/0, 

> create 0 /3311 1
OK

Client #0 /3311 : 4.04 (COAP_404_NOT_FOUND)
    0 bytes received of type text/plain:


> read 0 /3311/0
OK

Client #0 /3311/0 : 2.05 (COAP_205_CONTENT)
    169 bytes received of type application/vnd.oma.lwm2m+json:
    {"bn":"/3311/0/","e":[{"n":"5850","bv":false},{"n":"5851","v":0},{"n":"5852","v":0},{"n":"5805","v":0.0},{"n":"5820","v":0.0},{"n":"5706","sv":""},{"n":"5701","sv":""}]}

> write 0 /3311/0/5850 1
OK

Client #0 /3311/0/5850 : 2.04 (COAP_204_CHANGED)
    0 bytes received of type text/plain:

read 0 /3311/0/5850
OK

Client #0 /3311/0/5850 : 2.05 (COAP_205_CONTENT)
    46 bytes received of type application/vnd.oma.lwm2m+json:
    {"bn":"/3311/0/","e":[{"n":"5850","bv":true}]}

> write 0 /3311/0/5850 0
OK

Client #0 /3311/0/5850 : 2.04 (COAP_204_CHANGED)
    0 bytes received of type text/plain:

> read 0 /3311/0/5850
OK

Client #0 /3311/0/5850 : 2.05 (COAP_205_CONTENT)
    47 bytes received of type application/vnd.oma.lwm2m+json:
    {"bn":"/3311/0/","e":[{"n":"5850","bv":false}]}

> 
```

**Comment by mike-scott** [comment]
@therealprof update on this?

**Comment by therealprof** [comment]
Yeah, it's not you, it's me.

Our software learned a lot of nice things lately which exposed quite a few bugs, too. 😞
