### ISSUE TITLE
tests/posix/ fails on sam_e70_xplained

### ISSUE THREAD

**Issue by nniranjhana** [zephyrproject-rtos/zephyr#9684]
POSIX tests fail with _MPU FAULT_ on sam_e70_xplained

The following tests in posix fail with this error:
semaphore, mutex, rw_lock, all pthread tests, pthread_key, mqueue

**Arch:** ARM
**Platform:** sam_e70_xplained
**Error console log:**

```
 Running test suite test_pthreads
 ===================================================================
 starting test - test_pthread
 POSIX thread IPC APIs
 ***** MPU FAULT *****
   Data Access Violation
   MMFAR Address: 0x402325
 ***** Hardware exception *****
 Current thread ID = 0x20403850
 Faulting instruction address = 0x400f5e
 Fatal fault in thread 0x20403850! Aborting.
```

Commit: c0907762f3f15116732f434937fc3a5737c3d40b

**Comment by nashif** [comment]
fixed now
