### ISSUE TITLE
STM32: Add erase-block-size to flash node

### ISSUE THREAD

**Issue by erwango** [zephyrproject-rtos/zephyr#9686]
Similarly to what is done in https://github.com/zephyrproject-rtos/zephyr/pull/9681, 
define erase-block-size to all STM32 flash nodes with constant page size (F0, F3, not F4). Others TBD.

**Comment by aurel32** [comment]
It's possible to do that on at least the STM32F0 and STM32F3, but for the others platform like STM32F4, the page size is not constant. Instead the NVS sample should be modified to use the `FLASH_PAGE_LAYOUT` API to get the page size.

**Comment by erwango** [comment]
@aurel32 , thanks. I've been a bit fast to do raise this issue. Updating the description.
