### ISSUE TITLE
Deprecated configurations around `SPI_CS_GPIO`

### ISSUE THREAD

**Issue by Olivier-ProGlove** [zephyrproject-rtos/zephyr#9695]
I was rebasing my Zephyr application on v1.13 RC1 when I noticed `warning: SPI_CS_GPIO defined without a type`.

Searching into Zephyr code base for the new feature that has been used to replace this configuration shows me there are few platforms (`arch/x86/soc/intel_quark`, `boards/arc/arduino_101_sss`, `boards/x86/arduino_101`) and SPI options (`SPI_n_CS_GPIO_PORT`  and `SPI_n_CS_GPIO_PIN`) depending on this non-existing KConfig option.

I guess it should be fixed/cleaned for v1.13.

I am not sure if `SPI_CS_GPIO`, `SPI_n_CS_GPIO_PORT`  and `SPI_n_CS_GPIO_PIN` can be simply removed.

**Comment by galak** [comment]
Looks like we've removed these so closing this issue.  Please re-open if I missed something.
