### ISSUE TITLE
[Coverity CID :187905] Incorrect expression in /arch/arc/core/thread.c

### ISSUE THREAD

**Issue by mandarcthorat1** [zephyrproject-rtos/zephyr#9765]
Static code scan issues seen in File: /arch/arc/core/thread.c
 Category: Incorrect expression
 Function: _new_thread
 Component: Architectures
 CID: 187905
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by vonhust** [comment]
@ruuddw  @nashif  I can't access the details of coverity result.  It needs approval which i applied in Sept. 5th. 
But current status is still Pending Approval

**Comment by ruuddw** [comment]
@Wayne: Coverity access approved
