### ISSUE TITLE
[Coverity CID :187904] Integer handling issues in /tests/benchmarks/timing_info/src/semaphore_bench.c

### ISSUE THREAD

**Issue by mandarcthorat1** [zephyrproject-rtos/zephyr#9766]
Static code scan issues seen in File: /tests/benchmarks/timing_info/src/semaphore_bench.c
 Category: Integer handling issues
 Function: mutex_bench
 Component: Tests
 CID: 187904
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by AdithyaBaglody** [comment]
False positive. Divide by zero for the faulting expression is never possible. Updated the same in coverity.
