### ISSUE TITLE
samples/drivers/i2c fails with error writing to FRAM sensor

### ISSUE THREAD

**Issue by nniranjhana** [zephyrproject-rtos/zephyr#9849]
This test is failing on arduino_101's arc core and also x86 core of quark_d2000 with the following log:

```
 ***** delaying boot 1000ms (per build configuration) *****
 ***** Booting Zephyr OS v1.13.0-rc3 (delayed boot 1000ms) *****
 Error writing to FRAM! error code (-5)
```

**Comment by varun-sha** [comment]
@nniranjhana : I have tested this sample with MB85RC16V and its working fine.
Also please mention which chip you used while testing....when it was failing...

**Comment by varun-sha** [comment]
@nniranjhana waiting for retest results....as share pls close this as it was was working fine with MB85RC16V
