### ISSUE TITLE
samples/subsys/usb/hid/  test hangs on quark_se_c1000_devboard

### ISSUE THREAD

**Issue by ajaykish** [zephyrproject-rtos/zephyr#9861]
samples/subsys/usb/hid/  test hangs on quark_se_c1000_devboard

Arch: x86
Board: quark_se_c1000_devboard

Error Console log:
***** Booting Zephyr OS v1.13.0-rc3 *****
[main] [DBG] main: Starting application
[main] [DBG] set_idle_cb: Set Idle callback
[main] [DBG] main: Wrote 2 bytes with ret 0 

Steps to reproduce:
cd samples/subsys/usb/hid
rm -rf build && mkdir build && cd build
cmake -D BOARD=quark_se_c1000_devboard ../
make BOARD=quark_se_c1000_devboard flash

**Comment by finikorg** [comment]
@ajaykish Have you tested this sample recently, It should work now.

**Comment by ManojSubbarao** [comment]
@ajaykish re-check

**Comment by ajaykish** [comment]
Tested again and test is passing now.
Console log for passing test with  quark_se_c1000_devboard board:
[ajaykish@10-66-192-130 ~]$ sudo usbhid-dump -d 2fe3:0100 -es
 
Starting dumping interrupt transfer stream
with 1 minute timeout.

001:019:000:STREAM             1543326836.246900
 01 00

001:019:000:STREAM             1543326838.255044
 01 01

001:019:000:STREAM             1543326840.271056
 01 02

001:019:000:STREAM             1543326842.279044
 01 03

001:019:000:STREAM             1543326844.287071
 01 04

001:019:000:STREAM             1543326846.295055
 01 05
