### ISSUE TITLE
External flash driver for the MX25Rxx

### ISSUE THREAD

**Issue by GiulianoFranchetto** [zephyrproject-rtos/zephyr#9873]
Hi,

The Nordic nRF52840 PDK has an external flash built-in, connected to the nRF52840 by QSPI.

The driver is available using the nordic SDK, but it's not in Zephyr yet. 

Has anybody already ported this driver on Zephyr, or @carlescufi does the Nordic team plan to do so?

We do not need a XIP-enabled driver, we just want to read-write on the flash.
 
Regards

**Comment by GiulianoFranchetto** [comment]
Hi,

any update on this issue?

**Comment by carlescufi** [comment]
Copying @kl-cruz who has more details on this flash.

**Comment by GiulianoFranchetto** [comment]
Hi,

The QSPI part is not really what we want for now, as we don't have code in the external flash.

Did Nordic developped a driver for the  MX25Rxx when creating the nrf52 PDK?

Could it be easily ported using the Zephyr API?

Regards

**Comment by kl-cruz** [comment]
Hi,
I think QSPI could fit to your requirements. You do not have to use XiP. Just initialize QSPI and read/write/erase data from external memory. There is example application in Nordic's SDK (for example 15.2.0) based on QSPI. I think it is good starting point  to write shim layer.
In my opinion using QSPI to drive MX25xxx memories is easier than preparing SPI driver

**Comment by nvlsianpu** [comment]
@kl-cruz is this somehow related? https://github.com/zephyrproject-rtos/zephyr/pull/7561

**Comment by findlayfeng** [comment]
@kl-cruz 
Reading sfdp using QSPI first is defined in the sfdp documentation.
And this attempt is only done during initialization, and the result can be returned immediately without waiting. It has little effect on the initialization time.
And for devices that only support spi to read sfdp, this is a more expensive attempt, but it will be faster for devices that support qspi to read sfdp.

**Comment by nvlsianpu** [comment]
QSPI based driver Introduced as Nordic QSPI nor driver (usage examples tests/subsys/fs/littlefs on nrf52840_pca10056). 
https://github.com/zephyrproject-rtos/zephyr/pull/21535

Also possible to use spi nor driver.
