### ISSUE TITLE
Bluetooth: Host LE Extended Advertising

### ISSUE THREAD

**Issue by Vudentz** [zephyrproject-rtos/zephyr#9875]
Add support for Extended Advertising features on the Host:

- [x] Add support for using Extended Scan command and Extended Advertising Report Event

- [x] Add support for using Extended Advertising commands

- [x] Enable advertising with different sets/instances

- [x] Add support for using Periodic Advertising commands

- [x] Enable periodic advertising with different sets/instances

**Comment by carlescufi** [comment]
Counterpart issue for the controller is here: https://github.com/zephyrproject-rtos/zephyr/issues/3514

**Comment by carlescufi** [comment]
This is done
