### ISSUE TITLE
MISRA C Do not have dead code

### ISSUE THREAD

**Issue by ceolin** [zephyrproject-rtos/zephyr#9885]
According with Wikipedia, "In computer programming, dead code is a section in the source code of a program which is executed but whose result is never used in any other computation.". The presence of dead code is specially bad in embedded systems - like Zephyr - because it wasting resources and, possibly, affecting timing constraints.

Dead code is also doomed by several "process" standards like IEC 61508 and ISO 26262.

Static analysis tools like coverity can be used to check it.

part of #9552

**Comment by ceolin** [comment]
rules 2.1 and 2.2

**Comment by ioannisg** [comment]
We do have coverity, right? So i suppose we are able to catch dead code, no?
