### ISSUE TITLE
Default nrfx PWM interrupt prio results in assert

### ISSUE THREAD

**Issue by sjanc** [zephyrproject-rtos/zephyr#9901]
NRFX_PWM_DEFAULT_CONFIG_IRQ_PRIORITY defaults to 7 on all nRF52 SOCs

enabling CONFIG_ASSERT=y results in following assert on boot:

ASSERTION FAIL [prio <= ((1 << 3) - 1)] @ /home/janc/devel/external/zephyr/arch/arm/core/irq_manage.c:114:
invalid priority 7! values must be less than 7

**Comment by anangl** [comment]
The IRQ priority values from "nrfx_config_*.h" files are not used in Zephyr.
And they are not supposed to be used by any application built on Zephyr.
We'll be refactoring these files soon and such non-relevant entries will be removed from them to avoid confusion like this.

**Comment by sjanc** [comment]
All clear now. Thanks!
