### ISSUE TITLE
wrong behavior in pthread_barrier_wait()

### ISSUE THREAD

**Issue by ceolin** [zephyrproject-rtos/zephyr#9953]
This function does not have the behaviour defined in IEEE Std 1003.1.
It should return PTHREAD_BARRIER_SERIAL_THREAD constant for an arbitrary thread and 0 for the others synchronized threads.

**Comment by nashif** [comment]
@nniranjhana fyi

**Comment by andyross** [comment]
Pushed a quick fix for the bug (which was mine).  Probably wants a test to check this added somewhere too.

**Comment by nniranjhana** [comment]
@andyross I will add this check to the test and push as part of my PR for #9912
