### ISSUE TITLE
Build failed when CONFIG_STM32_ARM_MPU_ENABLE=y

### ISSUE THREAD

**Issue by erwango** [zephyrproject-rtos/zephyr#9956]
Following merge of #9776, building STM32 platform is failed when STM32_ARM_MPU_ENABLE is enabled.

Build error reported:
```
zephyr/arch/arm/core/cortex_m/mpu/libarch__arm__core__cortex_m__mpu.a(arm_mpu.c.obj): In function `arm_mpu_init':
/local/mcu/zephyr/zephyr-project/arch/arm/core/cortex_m/mpu/arm_mpu.c:368: undefined reference to `mpu_config'
```

`mpu_config` is defined in `soc/arm/st_stm32/common/arm_mpu_regions.c` which is not compiled since soc/arm/st_stm32/common/CMakeLists.txt is not parsed anymore

**Comment by erwango** [comment]
Seems CMakeLists behavior has changed:

I can build sucessfully frdm_k64f after deleting soc/arm/CMakeLists.txt

**Comment by erwango** [comment]
Seems following line at (https://github.com/zephyrproject-rtos/zephyr/blob/7fe3a481d015880e1213e79c95e522b9b97f0278/CMakeLists.txt#L339
is always false even if `soc/${ARCH}/CMakeLists.txt` actually exists.

**Comment by carlescufi** [comment]
@SebastianBoe any advice on this one?

**Comment by erwango** [comment]
Got it:
```
if(EXISTS ${ZEPHYR_BASE}/soc/${ARCH}/CMakeLists.txt) 
```
