### ISSUE TITLE
Native posix port drivers need to be documented

### ISSUE THREAD

**Issue by pfl** [zephyrproject-rtos/zephyr#9970]
The native posix port needs to document the drivers implemented and their usage. Currently the port page on the web doesn't mention anything about the fact that the native posix port has support for ethernet, timer, entropy and console drivers. The only documentation right now seem to be Kconfig files.

**Comment by pfl** [comment]
Let's close this, documentation is there but not in a very user friendly layout, section on peripherals should come first, but YMMV.

**Comment by aescolar** [comment]
There is a TOC at the beginning of the page..

**Comment by pfl** [comment]
> There is a TOC at the beginning of the page..

Yes...
