### ISSUE TITLE
soc: stm32: Extra tree soc configuration is blocked by /dts/arm/st/mem.h

### ISSUE THREAD

**Issue by ibisz** [zephyrproject-rtos/zephyr#9978]
After configuring an extra tree SOC based on documentation from #9776 "Move soc code under ZEPHYR_PROJECT/soc" , the build stopps with:
```
.../mem.h:128:2: error: #error "Flash, RAM, and CCM sizes not defined for this chip"
 #error "Flash, RAM, and CCM sizes not defined for this chip"
  ^~~~~
```

**Comment by erwango** [comment]
To better understand your issue, are you using a STM32 out of tree?
Or is that a STM32 point blocking other SoCs as well?

**Comment by erwango** [comment]
@ibisz , would the following work?
 
```
-#error "Flash, RAM, and CCM sizes not defined for this chip"
+#ifndef DT_FLASH_SIZE
+#ifndef DT_SRAM_SIZE
+#error "Flash, RAM, or CCM sizes not defined for this chip"
+#endif /* DT_SRAM_SIZE */
+#endif /* DT_FLASH_SIZE */
```

**Comment by erwango** [comment]
@ibisz : Ok, thanks, will push it.
Btw, I'm interested by your feedback of using STM32 SoC out of tree.
Don't hesitate to raise other issues, even for enhancements!
